In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
current_dir = "/home/nfash/EECS_545"

# List all files in the current directory (excluding subdirectories)
files_in_dir = [f for f in os.listdir(current_dir)]
for file in files_in_dir:
    print(file)

    
# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

catboost_info
.ipynb_checkpoints
isic-2024-challenge.zip
tree-based-models.ipynb
cnn-based-models.ipynb
testdir
isic-2024-challenge
metadata_model.ipynb
train-metadata-preprocessed-tree-model.csv
test-metadata-preprocessed-tree-model.csv

## Libraries and dependencies

In [2]:
import numpy as np 
import pandas as pd 
import os 
import h5py
import cv2
#from google.colab.patches import cv2_imshow
from IPython.display import display, Javascript
import plotly.express as px
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer,KNNImputer
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder, FunctionTransformer
from sklearn.feature_extraction import FeatureHasher
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.metrics import accuracy_score, mean_squared_error,get_scorer_names
from sklearn.preprocessing import LabelEncoder,MinMaxScaler
from sklearn.linear_model import LogisticRegression, LinearRegression,SGDClassifier,BayesianRidge
from sklearn.utils import resample
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from imblearn.combine import *
from imblearn.under_sampling import *
from imblearn.over_sampling import *
from imblearn.pipeline import Pipeline
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import xgboost as xgb
from sklearn.model_selection import cross_val_score
from sklearn.metrics import roc_auc_score
import lightgbm as lgb
import catboost as cb
from sklearn.ensemble import VotingClassifier,StackingClassifier
import matplotlib.pyplot as plt

In [3]:
np.__version__

'1.23.5'

In [4]:
# Deep learning keras libraries
import keras
print(keras.__version__)
import tensorflow as tf

3.5.0

## Data loading

In [5]:
current_dir = "/home/nfash/EECS_545/isic-2024-challenge"
sample_submission = pd.read_csv(os.path.join(current_dir,'sample_submission.csv'))
sample_submission.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   isic_id  3 non-null      object
 1   target   3 non-null      float64
dtypes: float64(1), object(1)
memory usage: 180.0+ bytes

In [6]:
sample_submission.head()

        isic_id  target
0  ISIC_0015657     0.3
1  ISIC_0015729     0.3
2  ISIC_0015740     0.3

In [7]:
train_metadata = pd.read_csv(os.path.join(current_dir,'train-metadata.csv'),low_memory=False)
#train_metadata.info()

In [8]:
train_metadata.head()

,isic_id,target,patient_id,age_approx,sex,anatom_site_general,clin_size_long_diam_mm,image_type,tbp_tile_type,tbp_lv_A,...,lesion_id,iddx_full,iddx_1,iddx_2,iddx_3,iddx_4,iddx_5,mel_mitotic_index,mel_thick_mm,tbp_lv_dnn_lesion_confidence
0,ISIC_0015670,0,IP_1235828,60.0,male,lower extremity,3.04,TBP tile: close-up,3D: white,20.244422,...,NaN,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,97.517282
1,ISIC_0015845,0,IP_8170065,60.0,male,head/neck,1.10,TBP tile: close-up,3D: white,31.712570,...,IL_6727506,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,3.141455
2,ISIC_0015864,0,IP_6724798,60.0,male,posterior torso,3.40,TBP tile: close-up,3D: XP,22.575830,...,NaN,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,99.804040
3,ISIC_0015902,0,IP_4111386,65.0,male,anterior torso,3.22,TBP tile: close-up,3D: XP,14.242329,...,NaN,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,99.989998
4,ISIC_0024200,0,IP_8313778,55.0,male,anterior torso,2.73,TBP tile: close-up,3D: white,24.725520,...,NaN,Benign,Benign,NaN,NaN,NaN,NaN,NaN,NaN,70.442510

In [9]:
test_metadata = pd.read_csv(os.path.join(current_dir,'test-metadata.csv'),low_memory=False)
#test_metadata.info()

In [10]:
test_metadata.head()

,isic_id,patient_id,age_approx,sex,anatom_site_general,clin_size_long_diam_mm,image_type,tbp_tile_type,tbp_lv_A,tbp_lv_Aext,...,tbp_lv_radial_color_std_max,tbp_lv_stdL,tbp_lv_stdLExt,tbp_lv_symm_2axis,tbp_lv_symm_2axis_angle,tbp_lv_x,tbp_lv_y,tbp_lv_z,attribution,copyright_license
0,ISIC_0015657,IP_6074337,45.0,male,posterior torso,2.70,TBP tile: close-up,3D: XP,22.80433,20.007270,...,0.304827,1.281532,2.299935,0.479339,20,-155.06510,1511.222000,113.980100,Memorial Sloan Kettering Cancer Center,CC-BY
1,ISIC_0015729,IP_1664139,35.0,female,lower extremity,2.52,TBP tile: close-up,3D: XP,16.64867,9.657964,...,0.000000,1.271940,2.011223,0.426230,25,-112.36924,629.535889,-15.019287,"Frazer Institute, The University of Queensland...",CC-BY
2,ISIC_0015740,IP_7142616,65.0,male,posterior torso,3.16,TBP tile: close-up,3D: XP,24.25384,19.937380,...,0.230742,1.080308,2.705857,0.366071,110,-84.29282,1303.978000,-28.576050,FNQH Cairns,CC-BY

#### Load Image Byte String

In this competition, images are provided as byte strings. The following code snippet demonstrates how to load these images into memory. One might wonder why the provided jpeg images aren't being used in the /train-image folder for training. This is because testing images are not provided as JPEG images; instead, they are provided as byte strings. Why use byte strings? They occupy significantly less memory compared to np.array representations.

In [11]:
# image sample visualization
training_validation_hdf5 = h5py.File(f"{current_dir}/train-image.hdf5", 'r')
testing_hdf5 = h5py.File(f"{current_dir}/test-image.hdf5", 'r')

In [12]:
# sample randomly two images from the train dataset
img_sample = train_metadata['isic_id'].sample(n=2).to_list()

# load the image from byte arrays, 
byte_str = [training_validation_hdf5[isic_id][()] for isic_id in img_sample]

# convert byte str to numpy array
img_arr = [np.frombuffer(byte, np.uint8) for byte in byte_str]

# convert cv2 image
img_cv2 = [cv2.imdecode(nparr, cv2.IMREAD_COLOR) for nparr in img_arr] 
for ind,val in enumerate(img_cv2):
    print(f"Image {img_sample[ind]}:")
    print(f"Shape:{val.shape}")
    #cv2_imshow(val)

Image ISIC_1291355:
Shape:(119, 119, 3)
Image ISIC_4776899:
Shape:(125, 125, 3)

In [13]:
# sample randomly two images from the train dataset
img_sample = test_metadata['isic_id'].sample(n=3).to_list()

# load the image from byte arrays, 
byte_str = [testing_hdf5[isic_id][()] for isic_id in img_sample]

# convert byte str to numpy array
img_arr = [np.frombuffer(byte, np.uint8) for byte in byte_str]

# convert cv2 image
img_cv2 = [cv2.imdecode(nparr, cv2.IMREAD_COLOR) for nparr in img_arr] 
for ind,val in enumerate(img_cv2):
    print(f"Image {img_sample[ind]}:")
    print(f"Shape:{val.shape}")
    #cv2_imshow(val)

Image ISIC_0015740:
Shape:(119, 119, 3)
Image ISIC_0015657:
Shape:(141, 141, 3)
Image ISIC_0015729:
Shape:(125, 125, 3)

## Preprocessing

In [14]:
class DataPreprocessor:
    def __init__(self):
        self.preprocessor = None
        self.train_columns = None

    def fit_transform(self, df):
        """Preprocess training data and store transformations."""
        df = df.copy()
        df = self._drop_irrelevant_columns(df)
        df = self._drop_train_only_columns(df)
        categorical_cols, numerical_cols = self._identify_column_types(df)
        
        # Define preprocessing pipelines
        numerical_pipeline = Pipeline([
            # ("imputer", SimpleImputer(strategy="median")),
            ("imputer", KNNImputer()),
            ("scaler", StandardScaler())
        ])
        
        categorical_pipeline = Pipeline([
            ("onehot", OneHotEncoder(handle_unknown="ignore"))
        ])
        
        self.preprocessor = ColumnTransformer([
            ("num", numerical_pipeline, numerical_cols),
            ("cat", categorical_pipeline, categorical_cols)
        ])
        
        transformed_data = self.preprocessor.fit_transform(df)
        
        cat_feature_names = self.preprocessor.named_transformers_["cat"].named_steps["onehot"].get_feature_names_out(categorical_cols)
        all_columns = numerical_cols + list(cat_feature_names)
        
        df_processed = pd.DataFrame(transformed_data, columns=all_columns)
        df_processed["isic_id"] = df["isic_id"].values
        df_processed["target"] = df["target"].values
        
        self.train_columns = df_processed.columns  # Store train columns
        return df_processed

    def transform(self, df):
        """Preprocess test data using stored transformations from training."""
        df = df.copy()
        df = self._drop_irrelevant_columns(df)
        
        transformed_data = self.preprocessor.transform(df)
        cat_feature_names = self.preprocessor.named_transformers_["cat"].named_steps["onehot"].get_feature_names_out()
        all_columns = self.train_columns[:-2]  # Exclude 'isic_id' and 'target'
        
        df_processed = pd.DataFrame(transformed_data, columns=all_columns)
        df_processed["isic_id"] = df["isic_id"].values
        # df_processed["target"] = df["target"].values
        
        # Align test dataset with train columns
        df_processed = self._align_train_test_columns(df_processed)
        return df_processed

    def _drop_irrelevant_columns(self, df):
        """Remove unnecessary columns."""
        return df.drop(columns=['patient_id','image_type', 'tbp_tile_type', 'attribution', 'copyright_license'], errors="ignore")

    def _drop_train_only_columns(self,df):
        """Remove columns that are present only in the train set and not in the test set"""
        drop_train_only_columns = [
            'lesion_id', 'iddx_full', 'iddx_1', 'iddx_2', 'iddx_3', 'iddx_4', 'iddx_5',
            'mel_mitotic_index', 'mel_thick_mm', 'tbp_lv_dnn_lesion_confidence'
            ]
        return df.drop(columns=drop_train_only_columns,errors='ignore')
        

    def _identify_column_types(self, df):
        """Identify categorical and numerical columns, excluding 'isic_id' and 'target'."""
        categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
        numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
        categorical_cols = [col for col in categorical_cols if col != "isic_id"]
        numerical_cols = [col for col in numerical_cols if col != "target"]
        return categorical_cols, numerical_cols
    
    def _align_train_test_columns(self, df):
        """Ensure test data has the same columns as train data."""
        train_cols = list(self.train_columns)
        train_cols.remove('target')
        missing_cols = set(train_cols) - set(df.columns)
        for col in missing_cols:
            df[col] = 0
        return df[train_cols]

In [15]:
train_metadata = pd.read_csv(os.path.join(current_dir, 'train-metadata.csv'), low_memory=False)
test_metadata = pd.read_csv(os.path.join(current_dir, 'test-metadata.csv'), low_memory=False)

In [38]:
data_object = DataPreprocessor() #SLOW
#train_metadata_processed = data_object.fit_transform(train_metadata)
#test_metadata_processed = data_object.transform(test_metadata)

train_metadata_processed = pd.read_csv('train-metadata-preprocessed-tree-model.csv',low_memory=False)
test_metadata_processed = pd.read_csv('test-metadata-preprocessed-tree-model.csv',low_memory=False)

(401059, 74)

In [39]:
# Save the preprocessed data
#train_metadata_processed.to_csv('train-metadata-preprocessed-tree-model.csv')
#test_metadata_processed.to_csv('test-metadata-preprocessed-tree-model.csv')

In [40]:
X_train = train_metadata_processed.drop(columns=['target'])
y_train = train_metadata_processed['target']
X_test = test_metadata_processed.copy()

## handling class imbalance

In [41]:
def resampler_data(X, Y):
    
    # Apply undersampling only on numerical data
    resampler = RandomUnderSampler(sampling_strategy=0.1,)
    X_resampled, Y_resampled = resampler.fit_resample(X,Y)
    
    # now apply over sampling for the minorit class
    resampler = RandomOverSampler(sampling_strategy=0.3)
    X_resampled, Y_resampled = resampler.fit_resample(X_resampled, Y_resampled)

    print("X_final shape;",X_resampled.shape)
    print("Y_final shape:",Y_resampled.shape)
    
    return X_resampled, Y_resampled

In [42]:
X_train_final, y_train_final = resampler_data(X_train, y_train)

/home/nfash/miniconda3/envs/keras_env/lib/python3.11/site-packages/sklearn/base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
/home/nfash/miniconda3/envs/keras_env/lib/python3.11/site-packages/sklearn/base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

X_final shape; (5109, 73)
Y_final shape: (5109,)

/home/nfash/miniconda3/envs/keras_env/lib/python3.11/site-packages/sklearn/base.py:484: FutureWarning: `BaseEstimator._check_n_features` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_n_features` instead.
  warnings.warn(
/home/nfash/miniconda3/envs/keras_env/lib/python3.11/site-packages/sklearn/base.py:493: FutureWarning: `BaseEstimator._check_feature_names` is deprecated in 1.6 and will be removed in 1.7. Use `sklearn.utils.validation._check_feature_names` instead.
  warnings.warn(

## metadata only model for submission checking

In [43]:
# Compute class weights
class_weights = y_train_final.value_counts(normalize=True).to_dict()
class_weights = {k: 1/v for k, v in class_weights.items()}
print(class_weights)

{0: 1.2999999999999998, 1: 4.333333333333333}

In [44]:
# Convert data to DMatrix for XGBoost
dtrain = xgb.DMatrix(X_train_final.drop(columns=['isic_id'],axis=1), label=y_train_final, 
                     weight=[class_weights[y] for y in y_train_final])
# dval = xgb.DMatrix(X_val.drop(columns=['isic_id'],axis=1), label=y_val)

In [45]:
# Define XGBoost parameters
params = {
    'objective': 'binary:logistic',
    'eval_metric': 'logloss',
    'scale_pos_weight': class_weights[1] / class_weights[0],
    'max_depth': 10,
    'eta': 0.01,
    'subsample': 0.9,
    'colsample_bytree': 0.9,
    'random_state': 63
}

# # Train the XGBoost classifier with cross-validation
# cv_results = xgb.cv(
#     params,
#     dtrain,
#     num_boost_round=10000,
#     nfold=5,
#     early_stopping_rounds=10,
#     metrics='logloss',
#     as_pandas=True,
#     seed=42
# )

In [46]:
# # View the train set results
# print("Cross-validation results:")
# print(cv_results)

In [47]:
# num_boost_rounds = cv_results['test-logloss-mean'].idxmin()
# xgb_model = xgb.train(params, dtrain, num_boost_round=num_boost_rounds)
# print(num_boost_rounds)

In [48]:
# light gbm model
lgb_matrix = lgb.Dataset(X_train_final.drop(columns=['isic_id'],axis=1), label=y_train_final, weight=[class_weights[y] for y in y_train_final])

lgb_params = {
    'objective': 'binary',
    'metric': 'binary_logloss',
    'eta': 0.01,
    'num_iterations':10000,
    'num_leaves':63,
    'random_state': 42,
    'verbose':-1
}

In [49]:
# lgb_model = lgb.train(lgb_params, lgb_matrix, num_boost_round=1000)

In [50]:
# # CatBoost model
# cb_model = cb.CatBoostClassifier(iterations=10000, depth=6, learning_rate=0.01, loss_function='Logloss', random_seed=42)
# cb_model.fit(X_train_final.drop(columns=['isic_id'],axis=1), y_train_final, sample_weight=[class_weights[y] for y in y_train_final], verbose=0)

In [51]:
# Predict class probabilities on the test data
dtest = xgb.DMatrix(X_test.drop(columns=['isic_id'],axis=1))
# y_test_pred_proba = model.predict(dtest)
# # Output the predicted probabilities
# print(y_test_pred_proba)

In [52]:
xgb_pred = lambda X: xgb_model.predict(dtest)
lgb_pred = lambda X: lgb_model.predict(X_test.drop(columns=['isic_id'],axis=1))
cb_pred = lambda X: cb_model.predict_proba(X_test.drop(columns=['isic_id'],axis=1))[:, 1]

In [53]:
# xgb_pred(dtest)

In [54]:
# lgb_pred(X_test)

In [55]:
# cb_pred(X_test)

In [56]:
# final_pred = np.mean([xgb_pred(dtest),lgb_pred(X_test),cb_pred(X_test)],axis=0)
# final_pred

In [83]:
# Create Stacking Model
stacking_model = StackingClassifier(
    estimators=[
        ('xgb', xgb.XGBClassifier(**params)),
        ('lgb', lgb.LGBMClassifier(**lgb_params)),
        ('cb', cb.CatBoostClassifier(iterations=10000,depth=10, learning_rate=0.01, 
                                     loss_function='Logloss', random_seed=42))
    ],
    final_estimator=LogisticRegression(),
    stack_method='predict_proba',
    verbose=2,
    n_jobs=-1,
    cv = 5
)

In [84]:
stacking_model.fit(X_train_final.drop(columns=['isic_id'],axis=1), y_train_final)
final_pred = stacking_model.predict_proba(X_test.drop(columns=['isic_id'],axis=1))

TBB Warning: The number of workers is currently limited to 15. The request for 35 workers is ignored. Further requests for more workers will be silently ignored until the limit changes.

0:	learn: 0.6803878	total: 73.2ms	remaining: 12m 12s
1:	learn: 0.6680535	total: 128ms	remaining: 10m 39s
2:	learn: 0.6557396	total: 174ms	remaining: 9m 39s
3:	learn: 0.6442398	total: 270ms	remaining: 11m 13s
4:	learn: 0.6337820	total: 344ms	remaining: 11m 28s
5:	learn: 0.6229353	total: 387ms	remaining: 10m 45s
6:	learn: 0.6118546	total: 467ms	remaining: 11m 6s
7:	learn: 0.6006781	total: 502ms	remaining: 10m 26s
8:	learn: 0.5890460	total: 556ms	remaining: 10m 17s
9:	learn: 0.5779352	total: 579ms	remaining: 9m 37s
10:	learn: 0.5704045	total: 648ms	remaining: 9m 48s
11:	learn: 0.5610709	total: 704ms	remaining: 9m 46s
12:	learn: 0.5511940	total: 742ms	remaining: 9m 30s
13:	learn: 0.5420906	total: 786ms	remaining: 9m 20s
14:	learn: 0.5326233	total: 826ms	remaining: 9m 10s
15:	learn: 0.5236715	total: 892ms	remaining: 9m 16s
16:	learn: 0.5148699	total: 962ms	remaining: 9m 24s
17:	learn: 0.5068862	total: 1.05s	remaining: 9m 44s
18:	learn: 0.4982475	total: 1.08s	remaining: 9m 28s
19:	learn: 0.4907106	total: 1.16s	remaining: 9m 38s
20:	learn: 0.4828638	total: 1.19s	remaining: 9m 23s
21:	learn: 0.4762355	total: 1.21s	remaining: 9m 10s
22:	learn: 0.4707361	total: 1.24s	remaining: 8m 59s
23:	learn: 0.4646760	total: 1.29s	remaining: 8m 57s
24:	learn: 0.4582206	total: 1.31s	remaining: 8m 42s
25:	learn: 0.4525640	total: 1.36s	remaining: 8m 42s
26:	learn: 0.4460639	total: 1.39s	remaining: 8m 33s
27:	learn: 0.4392312	total: 1.44s	remaining: 8m 32s
28:	learn: 0.4330831	total: 1.49s	remaining: 8m 31s
29:	learn: 0.4276866	total: 1.51s	remaining: 8m 23s
30:	learn: 0.4215615	total: 1.55s	remaining: 8m 19s
31:	learn: 0.4161542	total: 1.57s	remaining: 8m 10s
32:	learn: 0.4103307	total: 1.6s	remaining: 8m 4s
33:	learn: 0.4059643	total: 1.63s	remaining: 7m 56s
34:	learn: 0.4004650	total: 1.65s	remaining: 7m 49s
35:	learn: 0.3957046	total: 1.68s	remaining: 7m 44s
36:	learn: 0.3902307	total: 1.71s	remaining: 7m 40s
37:	learn: 0.3855236	total: 1.74s	remaining: 7m 36s
38:	learn: 0.3815025	total: 1.77s	remaining: 7m 32s
39:	learn: 0.3769339	total: 1.82s	remaining: 7m 32s
40:	learn: 0.3721766	total: 1.88s	remaining: 7m 36s
41:	learn: 0.3678910	total: 1.92s	remaining: 7m 35s
42:	learn: 0.3632925	total: 1.99s	remaining: 7m 41s
43:	learn: 0.3594331	total: 2.06s	remaining: 7m 46s
44:	learn: 0.3554676	total: 2.1s	remaining: 7m 44s
45:	learn: 0.3513018	total: 2.12s	remaining: 7m 39s
46:	learn: 0.3470749	total: 2.14s	remaining: 7m 33s
47:	learn: 0.3433599	total: 2.16s	remaining: 7m 27s
48:	learn: 0.3404868	total: 2.18s	remaining: 7m 22s
49:	learn: 0.3365105	total: 2.19s	remaining: 7m 16s
50:	learn: 0.3324693	total: 2.21s	remaining: 7m 11s
51:	learn: 0.3296434	total: 2.23s	remaining: 7m 6s
52:	learn: 0.3269191	total: 2.25s	remaining: 7m 1s
53:	learn: 0.3232150	total: 2.27s	remaining: 6m 57s
54:	learn: 0.3201471	total: 2.29s	remaining: 6m 53s
55:	learn: 0.3170521	total: 2.31s	remaining: 6m 50s
56:	learn: 0.3135387	total: 2.33s	remaining: 6m 47s
57:	learn: 0.3099838	total: 2.35s	remaining: 6m 43s
58:	learn: 0.3070967	total: 2.37s	remaining: 6m 39s
59:	learn: 0.3045009	total: 2.39s	remaining: 6m 35s
60:	learn: 0.3008749	total: 2.41s	remaining: 6m 32s
61:	learn: 0.2982586	total: 2.42s	remaining: 6m 28s
62:	learn: 0.2959722	total: 2.44s	remaining: 6m 25s
63:	learn: 0.2935580	total: 2.47s	remaining: 6m 23s
64:	learn: 0.2905029	total: 2.49s	remaining: 6m 21s
65:	learn: 0.2881933	total: 2.52s	remaining: 6m 19s
66:	learn: 0.2862876	total: 2.54s	remaining: 6m 16s
67:	learn: 0.2837364	total: 2.56s	remaining: 6m 14s
68:	learn: 0.2811239	total: 2.59s	remaining: 6m 13s
69:	learn: 0.2789984	total: 2.61s	remaining: 6m 10s
70:	learn: 0.2760072	total: 2.63s	remaining: 6m 8s
71:	learn: 0.2731200	total: 2.65s	remaining: 6m 5s
72:	learn: 0.2710235	total: 2.68s	remaining: 6m 4s
73:	learn: 0.2689154	total: 2.7s	remaining: 6m 2s
74:	learn: 0.2663367	total: 2.73s	remaining: 6m 1s
75:	learn: 0.2643113	total: 2.75s	remaining: 5m 58s
76:	learn: 0.2618985	total: 2.77s	remaining: 5m 57s
77:	learn: 0.2597713	total: 2.79s	remaining: 5m 55s
78:	learn: 0.2576315	total: 2.81s	remaining: 5m 53s
79:	learn: 0.2555776	total: 2.83s	remaining: 5m 50s
80:	learn: 0.2536230	total: 2.85s	remaining: 5m 48s
81:	learn: 0.2516424	total: 2.88s	remaining: 5m 48s
82:	learn: 0.2498535	total: 2.9s	remaining: 5m 47s
83:	learn: 0.2484441	total: 2.96s	remaining: 5m 48s
84:	learn: 0.2463442	total: 2.98s	remaining: 5m 47s
85:	learn: 0.2446672	total: 3s	remaining: 5m 45s
86:	learn: 0.2427510	total: 3.03s	remaining: 5m 45s
87:	learn: 0.2414408	total: 3.09s	remaining: 5m 47s
88:	learn: 0.2399550	total: 3.11s	remaining: 5m 46s
89:	learn: 0.2381288	total: 3.14s	remaining: 5m 45s
90:	learn: 0.2364056	total: 3.2s	remaining: 5m 48s
91:	learn: 0.2347673	total: 3.24s	remaining: 5m 48s
92:	learn: 0.2333601	total: 3.28s	remaining: 5m 49s
93:	learn: 0.2315943	total: 3.31s	remaining: 5m 48s
94:	learn: 0.2302155	total: 3.35s	remaining: 5m 48s
95:	learn: 0.2290278	total: 3.39s	remaining: 5m 50s
96:	learn: 0.2275606	total: 3.44s	remaining: 5m 51s
97:	learn: 0.2258471	total: 3.47s	remaining: 5m 51s
98:	learn: 0.2243364	total: 3.53s	remaining: 5m 52s
99:	learn: 0.2226970	total: 3.55s	remaining: 5m 51s
100:	learn: 0.2216008	total: 3.57s	remaining: 5m 49s
101:	learn: 0.2198012	total: 3.58s	remaining: 5m 47s
102:	learn: 0.2184501	total: 3.62s	remaining: 5m 47s
103:	learn: 0.2173276	total: 3.63s	remaining: 5m 45s
104:	learn: 0.2159308	total: 3.67s	remaining: 5m 45s
105:	learn: 0.2144471	total: 3.69s	remaining: 5m 44s
106:	learn: 0.2130403	total: 3.71s	remaining: 5m 43s
107:	learn: 0.2118024	total: 3.76s	remaining: 5m 44s
108:	learn: 0.2106275	total: 3.78s	remaining: 5m 43s
109:	learn: 0.2096206	total: 3.82s	remaining: 5m 43s
110:	learn: 0.2082712	total: 3.86s	remaining: 5m 44s
111:	learn: 0.2070002	total: 3.9s	remaining: 5m 43s
112:	learn: 0.2057889	total: 3.92s	remaining: 5m 43s
113:	learn: 0.2044000	total: 3.95s	remaining: 5m 42s
114:	learn: 0.2032478	total: 3.99s	remaining: 5m 42s
115:	learn: 0.2019371	total: 4.02s	remaining: 5m 42s
116:	learn: 0.2006703	total: 4.07s	remaining: 5m 44s
117:	learn: 0.1994203	total: 4.09s	remaining: 5m 42s
118:	learn: 0.1983243	total: 4.13s	remaining: 5m 42s
119:	learn: 0.1970594	total: 4.16s	remaining: 5m 42s
120:	learn: 0.1959994	total: 4.2s	remaining: 5m 42s
121:	learn: 0.1950426	total: 4.23s	remaining: 5m 42s
122:	learn: 0.1942178	total: 4.31s	remaining: 5m 46s
123:	learn: 0.1929044	total: 4.39s	remaining: 5m 49s
124:	learn: 0.1917737	total: 4.41s	remaining: 5m 48s
125:	learn: 0.1908549	total: 4.44s	remaining: 5m 47s
126:	learn: 0.1899710	total: 4.47s	remaining: 5m 47s
127:	learn: 0.1891942	total: 4.49s	remaining: 5m 45s
128:	learn: 0.1882970	total: 4.5s	remaining: 5m 44s
129:	learn: 0.1872430	total: 4.53s	remaining: 5m 44s
130:	learn: 0.1864091	total: 4.58s	remaining: 5m 44s
131:	learn: 0.1853986	total: 4.63s	remaining: 5m 46s
132:	learn: 0.1844328	total: 4.66s	remaining: 5m 45s
133:	learn: 0.1832451	total: 4.69s	remaining: 5m 45s
134:	learn: 0.1823133	total: 4.73s	remaining: 5m 45s
135:	learn: 0.1816175	total: 4.75s	remaining: 5m 44s
136:	learn: 0.1806726	total: 4.78s	remaining: 5m 44s
137:	learn: 0.1797387	total: 4.81s	remaining: 5m 43s
138:	learn: 0.1786385	total: 4.85s	remaining: 5m 44s
139:	learn: 0.1775674	total: 4.88s	remaining: 5m 43s
140:	learn: 0.1765578	total: 4.93s	remaining: 5m 44s
141:	learn: 0.1756671	total: 4.96s	remaining: 5m 44s
142:	learn: 0.1748275	total: 4.98s	remaining: 5m 43s
143:	learn: 0.1737063	total: 5.02s	remaining: 5m 43s
144:	learn: 0.1728217	total: 5.05s	remaining: 5m 43s
145:	learn: 0.1720120	total: 5.1s	remaining: 5m 44s
146:	learn: 0.1713006	total: 5.12s	remaining: 5m 43s
147:	learn: 0.1704111	total: 5.15s	remaining: 5m 42s
148:	learn: 0.1697204	total: 5.18s	remaining: 5m 42s
149:	learn: 0.1688847	total: 5.2s	remaining: 5m 41s
150:	learn: 0.1680787	total: 5.22s	remaining: 5m 40s
151:	learn: 0.1673454	total: 5.26s	remaining: 5m 40s
152:	learn: 0.1666840	total: 5.27s	remaining: 5m 39s
153:	learn: 0.1659902	total: 5.29s	remaining: 5m 38s
154:	learn: 0.1652737	total: 5.31s	remaining: 5m 37s
155:	learn: 0.1647344	total: 5.33s	remaining: 5m 36s
156:	learn: 0.1641546	total: 5.35s	remaining: 5m 35s
157:	learn: 0.1635141	total: 5.38s	remaining: 5m 34s
158:	learn: 0.1625817	total: 5.42s	remaining: 5m 35s
159:	learn: 0.1616893	total: 5.44s	remaining: 5m 34s
160:	learn: 0.1608800	total: 5.46s	remaining: 5m 33s
161:	learn: 0.1601663	total: 5.53s	remaining: 5m 35s
162:	learn: 0.1594656	total: 5.55s	remaining: 5m 34s
163:	learn: 0.1589245	total: 5.57s	remaining: 5m 33s
164:	learn: 0.1581136	total: 5.59s	remaining: 5m 33s
165:	learn: 0.1574641	total: 5.62s	remaining: 5m 32s
166:	learn: 0.1567954	total: 5.65s	remaining: 5m 32s
167:	learn: 0.1560721	total: 5.69s	remaining: 5m 32s
168:	learn: 0.1554017	total: 5.72s	remaining: 5m 32s
169:	learn: 0.1546327	total: 5.76s	remaining: 5m 32s
170:	learn: 0.1540061	total: 5.79s	remaining: 5m 32s
171:	learn: 0.1533112	total: 5.82s	remaining: 5m 32s
172:	learn: 0.1525047	total: 5.85s	remaining: 5m 32s
173:	learn: 0.1517855	total: 5.87s	remaining: 5m 31s
174:	learn: 0.1511685	total: 5.89s	remaining: 5m 30s
175:	learn: 0.1505168	total: 5.91s	remaining: 5m 29s
176:	learn: 0.1496849	total: 5.93s	remaining: 5m 28s
177:	learn: 0.1490344	total: 5.96s	remaining: 5m 28s
178:	learn: 0.1485067	total: 5.99s	remaining: 5m 28s
179:	learn: 0.1478773	total: 6.02s	remaining: 5m 28s
180:	learn: 0.1472731	total: 6.08s	remaining: 5m 30s
181:	learn: 0.1467881	total: 6.13s	remaining: 5m 30s
182:	learn: 0.1459977	total: 6.16s	remaining: 5m 30s
183:	learn: 0.1454581	total: 6.21s	remaining: 5m 31s
184:	learn: 0.1449240	total: 6.24s	remaining: 5m 30s
185:	learn: 0.1445358	total: 6.26s	remaining: 5m 30s
186:	learn: 0.1440345	total: 6.29s	remaining: 5m 30s
187:	learn: 0.1434367	total: 6.33s	remaining: 5m 30s
188:	learn: 0.1428117	total: 6.39s	remaining: 5m 31s
189:	learn: 0.1422764	total: 6.42s	remaining: 5m 31s
190:	learn: 0.1415929	total: 6.46s	remaining: 5m 31s
191:	learn: 0.1410211	total: 6.49s	remaining: 5m 31s
192:	learn: 0.1405283	total: 6.54s	remaining: 5m 32s
193:	learn: 0.1398025	total: 6.57s	remaining: 5m 32s
194:	learn: 0.1392833	total: 6.63s	remaining: 5m 33s
195:	learn: 0.1388687	total: 6.67s	remaining: 5m 33s
196:	learn: 0.1383286	total: 6.71s	remaining: 5m 33s
197:	learn: 0.1378174	total: 6.75s	remaining: 5m 34s
198:	learn: 0.1373205	total: 6.78s	remaining: 5m 34s
199:	learn: 0.1368091	total: 6.84s	remaining: 5m 35s
200:	learn: 0.1365199	total: 6.87s	remaining: 5m 34s
201:	learn: 0.1359627	total: 6.9s	remaining: 5m 34s
202:	learn: 0.1354302	total: 6.92s	remaining: 5m 34s
203:	learn: 0.1349900	total: 6.96s	remaining: 5m 34s
204:	learn: 0.1344322	total: 6.99s	remaining: 5m 34s
205:	learn: 0.1339154	total: 7.03s	remaining: 5m 34s
206:	learn: 0.1334856	total: 7.08s	remaining: 5m 35s
207:	learn: 0.1329750	total: 7.11s	remaining: 5m 34s
208:	learn: 0.1323941	total: 7.14s	remaining: 5m 34s
209:	learn: 0.1315962	total: 7.18s	remaining: 5m 34s
210:	learn: 0.1310831	total: 7.21s	remaining: 5m 34s
211:	learn: 0.1306023	total: 7.28s	remaining: 5m 36s
212:	learn: 0.1300654	total: 7.3s	remaining: 5m 35s
213:	learn: 0.1295827	total: 7.36s	remaining: 5m 36s
214:	learn: 0.1289780	total: 7.41s	remaining: 5m 37s
215:	learn: 0.1285093	total: 7.44s	remaining: 5m 36s
216:	learn: 0.1279858	total: 7.49s	remaining: 5m 37s
217:	learn: 0.1276177	total: 7.52s	remaining: 5m 37s
218:	learn: 0.1270142	total: 7.54s	remaining: 5m 36s
219:	learn: 0.1266222	total: 7.6s	remaining: 5m 37s
220:	learn: 0.1261474	total: 7.62s	remaining: 5m 37s
221:	learn: 0.1254893	total: 7.64s	remaining: 5m 36s
222:	learn: 0.1251443	total: 7.67s	remaining: 5m 36s
223:	learn: 0.1247394	total: 7.68s	remaining: 5m 35s
224:	learn: 0.1241933	total: 7.71s	remaining: 5m 34s
225:	learn: 0.1237575	total: 7.72s	remaining: 5m 34s
226:	learn: 0.1233669	total: 7.75s	remaining: 5m 33s
227:	learn: 0.1229584	total: 7.77s	remaining: 5m 33s
228:	learn: 0.1225068	total: 7.79s	remaining: 5m 32s
229:	learn: 0.1220491	total: 7.82s	remaining: 5m 31s
230:	learn: 0.1214692	total: 7.85s	remaining: 5m 31s
231:	learn: 0.1209299	total: 7.88s	remaining: 5m 31s
232:	learn: 0.1205957	total: 7.89s	remaining: 5m 30s
233:	learn: 0.1199518	total: 7.93s	remaining: 5m 31s
234:	learn: 0.1192361	total: 7.99s	remaining: 5m 32s
235:	learn: 0.1187552	total: 8.02s	remaining: 5m 31s
236:	learn: 0.1183727	total: 8.06s	remaining: 5m 32s
237:	learn: 0.1180180	total: 8.08s	remaining: 5m 31s
238:	learn: 0.1175352	total: 8.11s	remaining: 5m 31s
239:	learn: 0.1170420	total: 8.19s	remaining: 5m 32s
240:	learn: 0.1165513	total: 8.21s	remaining: 5m 32s
241:	learn: 0.1162391	total: 8.24s	remaining: 5m 32s
242:	learn: 0.1157100	total: 8.27s	remaining: 5m 31s
243:	learn: 0.1152113	total: 8.29s	remaining: 5m 31s
244:	learn: 0.1146305	total: 8.31s	remaining: 5m 30s
245:	learn: 0.1143418	total: 8.32s	remaining: 5m 29s
246:	learn: 0.1138281	total: 8.37s	remaining: 5m 30s
247:	learn: 0.1133699	total: 8.43s	remaining: 5m 31s
248:	learn: 0.1129857	total: 8.47s	remaining: 5m 31s
249:	learn: 0.1125976	total: 8.53s	remaining: 5m 32s
250:	learn: 0.1122424	total: 8.55s	remaining: 5m 32s
251:	learn: 0.1117055	total: 8.57s	remaining: 5m 31s
252:	learn: 0.1113127	total: 8.58s	remaining: 5m 30s
253:	learn: 0.1108613	total: 8.61s	remaining: 5m 30s
254:	learn: 0.1104501	total: 8.67s	remaining: 5m 31s
255:	learn: 0.1099712	total: 8.71s	remaining: 5m 31s
256:	learn: 0.1095847	total: 8.73s	remaining: 5m 30s
257:	learn: 0.1092088	total: 8.75s	remaining: 5m 30s
258:	learn: 0.1088677	total: 8.77s	remaining: 5m 29s
259:	learn: 0.1085029	total: 8.82s	remaining: 5m 30s
260:	learn: 0.1080713	total: 8.86s	remaining: 5m 30s
261:	learn: 0.1076905	total: 8.87s	remaining: 5m 29s
262:	learn: 0.1073114	total: 8.89s	remaining: 5m 29s
263:	learn: 0.1068777	total: 8.91s	remaining: 5m 28s
264:	learn: 0.1066549	total: 8.94s	remaining: 5m 28s
265:	learn: 0.1063858	total: 9s	remaining: 5m 29s
266:	learn: 0.1059963	total: 9.03s	remaining: 5m 29s
267:	learn: 0.1057208	total: 9.06s	remaining: 5m 29s
268:	learn: 0.1053310	total: 9.1s	remaining: 5m 29s
269:	learn: 0.1050400	total: 9.13s	remaining: 5m 29s
270:	learn: 0.1045610	total: 9.16s	remaining: 5m 29s
271:	learn: 0.1042481	total: 9.2s	remaining: 5m 29s
272:	learn: 0.1038041	total: 9.25s	remaining: 5m 29s
273:	learn: 0.1034619	total: 9.29s	remaining: 5m 29s
274:	learn: 0.1030264	total: 9.33s	remaining: 5m 29s
275:	learn: 0.1027287	total: 9.37s	remaining: 5m 29s
276:	learn: 0.1023573	total: 9.41s	remaining: 5m 30s
277:	learn: 0.1019886	total: 9.45s	remaining: 5m 30s
278:	learn: 0.1016526	total: 9.49s	remaining: 5m 30s
279:	learn: 0.1013553	total: 9.54s	remaining: 5m 31s
280:	learn: 0.1010058	total: 9.61s	remaining: 5m 32s
281:	learn: 0.1006084	total: 9.66s	remaining: 5m 32s
282:	learn: 0.1002004	total: 9.69s	remaining: 5m 32s
283:	learn: 0.0997745	total: 9.75s	remaining: 5m 33s
284:	learn: 0.0993172	total: 9.82s	remaining: 5m 34s
285:	learn: 0.0991048	total: 9.86s	remaining: 5m 34s
286:	learn: 0.0987239	total: 9.92s	remaining: 5m 35s
287:	learn: 0.0984493	total: 9.96s	remaining: 5m 35s
288:	learn: 0.0982159	total: 9.99s	remaining: 5m 35s
289:	learn: 0.0977761	total: 10s	remaining: 5m 35s
290:	learn: 0.0975107	total: 10.1s	remaining: 5m 35s
291:	learn: 0.0972795	total: 10.1s	remaining: 5m 35s
292:	learn: 0.0969536	total: 10.1s	remaining: 5m 34s
293:	learn: 0.0966892	total: 10.1s	remaining: 5m 34s
294:	learn: 0.0963226	total: 10.2s	remaining: 5m 34s
295:	learn: 0.0960486	total: 10.2s	remaining: 5m 34s
296:	learn: 0.0956614	total: 10.3s	remaining: 5m 35s
297:	learn: 0.0953314	total: 10.3s	remaining: 5m 35s
298:	learn: 0.0950522	total: 10.3s	remaining: 5m 35s
299:	learn: 0.0946235	total: 10.4s	remaining: 5m 36s
300:	learn: 0.0942295	total: 10.5s	remaining: 5m 37s
301:	learn: 0.0939488	total: 10.5s	remaining: 5m 37s
302:	learn: 0.0936474	total: 10.5s	remaining: 5m 36s
303:	learn: 0.0932465	total: 10.5s	remaining: 5m 36s
304:	learn: 0.0929345	total: 10.6s	remaining: 5m 36s
305:	learn: 0.0924775	total: 10.6s	remaining: 5m 36s
306:	learn: 0.0922511	total: 10.7s	remaining: 5m 36s
307:	learn: 0.0920682	total: 10.7s	remaining: 5m 35s
308:	learn: 0.0916884	total: 10.7s	remaining: 5m 35s
309:	learn: 0.0913793	total: 10.7s	remaining: 5m 35s
310:	learn: 0.0910904	total: 10.7s	remaining: 5m 34s
311:	learn: 0.0907589	total: 10.8s	remaining: 5m 34s
312:	learn: 0.0904799	total: 10.8s	remaining: 5m 34s
313:	learn: 0.0901894	total: 10.8s	remaining: 5m 33s
314:	learn: 0.0898787	total: 10.8s	remaining: 5m 33s
315:	learn: 0.0895142	total: 10.9s	remaining: 5m 32s
316:	learn: 0.0892019	total: 10.9s	remaining: 5m 33s
317:	learn: 0.0889844	total: 11s	remaining: 5m 35s
318:	learn: 0.0886148	total: 11s	remaining: 5m 35s
319:	learn: 0.0884646	total: 11.1s	remaining: 5m 34s
320:	learn: 0.0882707	total: 11.1s	remaining: 5m 34s
321:	learn: 0.0880888	total: 11.1s	remaining: 5m 34s
322:	learn: 0.0878180	total: 11.2s	remaining: 5m 35s
323:	learn: 0.0875988	total: 11.3s	remaining: 5m 36s
324:	learn: 0.0873774	total: 11.3s	remaining: 5m 36s
325:	learn: 0.0869908	total: 11.3s	remaining: 5m 35s
326:	learn: 0.0866704	total: 11.3s	remaining: 5m 35s
327:	learn: 0.0863935	total: 11.4s	remaining: 5m 34s
328:	learn: 0.0861211	total: 11.4s	remaining: 5m 34s
329:	learn: 0.0857910	total: 11.4s	remaining: 5m 34s
330:	learn: 0.0855340	total: 11.4s	remaining: 5m 34s
331:	learn: 0.0852271	total: 11.5s	remaining: 5m 33s
332:	learn: 0.0849898	total: 11.5s	remaining: 5m 33s
333:	learn: 0.0847259	total: 11.5s	remaining: 5m 34s
334:	learn: 0.0845470	total: 11.6s	remaining: 5m 34s
335:	learn: 0.0842730	total: 11.6s	remaining: 5m 33s
336:	learn: 0.0841093	total: 11.6s	remaining: 5m 33s
337:	learn: 0.0838622	total: 11.7s	remaining: 5m 33s
338:	learn: 0.0837087	total: 11.7s	remaining: 5m 33s
339:	learn: 0.0834767	total: 11.7s	remaining: 5m 33s
340:	learn: 0.0832757	total: 11.8s	remaining: 5m 32s
341:	learn: 0.0831261	total: 11.8s	remaining: 5m 32s
342:	learn: 0.0828379	total: 11.8s	remaining: 5m 32s
343:	learn: 0.0825899	total: 11.9s	remaining: 5m 33s
344:	learn: 0.0823477	total: 11.9s	remaining: 5m 34s
345:	learn: 0.0821846	total: 12s	remaining: 5m 34s
346:	learn: 0.0818812	total: 12s	remaining: 5m 33s
347:	learn: 0.0815740	total: 12s	remaining: 5m 33s
348:	learn: 0.0812568	total: 12.1s	remaining: 5m 34s
349:	learn: 0.0809872	total: 12.1s	remaining: 5m 33s
350:	learn: 0.0808026	total: 12.2s	remaining: 5m 34s
351:	learn: 0.0805490	total: 12.2s	remaining: 5m 34s
352:	learn: 0.0802570	total: 12.2s	remaining: 5m 34s
353:	learn: 0.0800500	total: 12.3s	remaining: 5m 34s
354:	learn: 0.0798542	total: 12.4s	remaining: 5m 35s
355:	learn: 0.0795288	total: 12.4s	remaining: 5m 36s
356:	learn: 0.0793562	total: 12.4s	remaining: 5m 35s
357:	learn: 0.0791113	total: 12.5s	remaining: 5m 35s
358:	learn: 0.0788387	total: 12.5s	remaining: 5m 35s
359:	learn: 0.0785975	total: 12.5s	remaining: 5m 35s
360:	learn: 0.0784064	total: 12.6s	remaining: 5m 36s
361:	learn: 0.0781079	total: 12.6s	remaining: 5m 35s
362:	learn: 0.0779092	total: 12.7s	remaining: 5m 36s
363:	learn: 0.0776883	total: 12.7s	remaining: 5m 36s
364:	learn: 0.0774245	total: 12.7s	remaining: 5m 36s
365:	learn: 0.0772257	total: 12.8s	remaining: 5m 35s
366:	learn: 0.0769243	total: 12.8s	remaining: 5m 36s
367:	learn: 0.0767169	total: 12.8s	remaining: 5m 35s
368:	learn: 0.0765045	total: 12.9s	remaining: 5m 36s
369:	learn: 0.0763452	total: 12.9s	remaining: 5m 35s
370:	learn: 0.0761059	total: 12.9s	remaining: 5m 35s
371:	learn: 0.0757892	total: 13s	remaining: 5m 35s
372:	learn: 0.0755378	total: 13s	remaining: 5m 35s
373:	learn: 0.0752958	total: 13.1s	remaining: 5m 36s
374:	learn: 0.0750628	total: 13.1s	remaining: 5m 36s
375:	learn: 0.0748153	total: 13.1s	remaining: 5m 36s
376:	learn: 0.0746850	total: 13.2s	remaining: 5m 37s
377:	learn: 0.0744223	total: 13.2s	remaining: 5m 36s
378:	learn: 0.0741300	total: 13.3s	remaining: 5m 37s
379:	learn: 0.0739562	total: 13.3s	remaining: 5m 37s

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 16 concurrent workers.
TBB Warning: The number of workers is currently limited to 15. The request for 35 workers is ignored. Further requests for more workers will be silently ignored until the limit changes.

0:	learn: 0.6817439	total: 212ms	remaining: 35m 17s
0:	learn: 0.6813822	total: 280ms	remaining: 46m 44s
0:	learn: 0.6817888	total: 300ms	remaining: 49m 57s
0:	learn: 0.6812625	total: 105ms	remaining: 17m 34s
1:	learn: 0.6695413	total: 364ms	remaining: 30m 17s
0:	learn: 0.6801470	total: 208ms	remaining: 34m 34s
1:	learn: 0.6697312	total: 463ms	remaining: 38m 34s
1:	learn: 0.6683263	total: 476ms	remaining: 39m 39s
1:	learn: 0.6694501	total: 251ms	remaining: 20m 52s
2:	learn: 0.6579010	total: 501ms	remaining: 27m 49s
1:	learn: 0.6686978	total: 325ms	remaining: 27m 5s
2:	learn: 0.6582874	total: 605ms	remaining: 33m 34s
2:	learn: 0.6574239	total: 614ms	remaining: 34m 6s
2:	learn: 0.6581006	total: 367ms	remaining: 20m 24s
3:	learn: 0.6466555	total: 640ms	remaining: 26m 40s
2:	learn: 0.6560778	total: 467ms	remaining: 25m 57s
3:	learn: 0.6460333	total: 714ms	remaining: 29m 44s
3:	learn: 0.6468479	total: 476ms	remaining: 19m 48s
3:	learn: 0.6464700	total: 771ms	remaining: 32m 7s
3:	learn: 0.6447225	total: 584ms	remaining: 24m 19s
4:	learn: 0.6346064	total: 820ms	remaining: 27m 18s
4:	learn: 0.6362008	total: 594ms	remaining: 19m 47s
4:	learn: 0.6356123	total: 822ms	remaining: 27m 22s
4:	learn: 0.6356360	total: 892ms	remaining: 29m 42s
5:	learn: 0.6245049	total: 895ms	remaining: 24m 51s
4:	learn: 0.6339144	total: 719ms	remaining: 23m 56s
5:	learn: 0.6235161	total: 956ms	remaining: 26m 31s
5:	learn: 0.6251057	total: 730ms	remaining: 20m 16s
5:	learn: 0.6248618	total: 1.02s	remaining: 28m 17s
5:	learn: 0.6227222	total: 814ms	remaining: 22m 35s
6:	learn: 0.6138957	total: 1.07s	remaining: 25m 26s
6:	learn: 0.6120844	total: 1.09s	remaining: 26m 1s
6:	learn: 0.6132184	total: 1.16s	remaining: 27m 38s
6:	learn: 0.6139772	total: 917ms	remaining: 21m 49s
6:	learn: 0.6109628	total: 964ms	remaining: 22m 55s
7:	learn: 0.6041011	total: 1.17s	remaining: 24m 23s
7:	learn: 0.6026594	total: 1.27s	remaining: 26m 22s
7:	learn: 0.6020662	total: 1.3s	remaining: 27m 5s
7:	learn: 0.6033673	total: 1.03s	remaining: 21m 31s
8:	learn: 0.5920519	total: 1.28s	remaining: 23m 36s
7:	learn: 0.6001589	total: 1.09s	remaining: 22m 38s
8:	learn: 0.5926241	total: 1.39s	remaining: 25m 47s
8:	learn: 0.5922728	total: 1.14s	remaining: 21m 8s
9:	learn: 0.5821570	total: 1.39s	remaining: 23m 7s
8:	learn: 0.5935578	total: 1.42s	remaining: 26m 14s
8:	learn: 0.5897675	total: 1.24s	remaining: 22m 51s
9:	learn: 0.5840792	total: 1.48s	remaining: 24m 37s
9:	learn: 0.5821553	total: 1.51s	remaining: 25m 11s
10:	learn: 0.5732184	total: 1.5s	remaining: 22m 44s
9:	learn: 0.5822594	total: 1.3s	remaining: 21m 37s
9:	learn: 0.5804347	total: 1.36s	remaining: 22m 38s
10:	learn: 0.5760972	total: 1.6s	remaining: 24m 13s
10:	learn: 0.5731314	total: 1.64s	remaining: 24m 48s
10:	learn: 0.5736669	total: 1.42s	remaining: 21m 26s
11:	learn: 0.5636760	total: 1.66s	remaining: 22m 57s
10:	learn: 0.5707429	total: 1.46s	remaining: 22m 6s
11:	learn: 0.5663532	total: 1.72s	remaining: 23m 51s
11:	learn: 0.5638907	total: 1.76s	remaining: 24m 28s
12:	learn: 0.5541393	total: 1.76s	remaining: 22m 32s
11:	learn: 0.5613965	total: 1.58s	remaining: 21m 55s
11:	learn: 0.5655565	total: 1.55s	remaining: 21m 34s
12:	learn: 0.5574548	total: 1.86s	remaining: 23m 48s
12:	learn: 0.5560626	total: 1.67s	remaining: 21m 19s
13:	learn: 0.5462133	total: 1.9s	remaining: 22m 33s
12:	learn: 0.5544172	total: 1.94s	remaining: 24m 52s
12:	learn: 0.5518559	total: 1.74s	remaining: 22m 13s
13:	learn: 0.5490857	total: 2.06s	remaining: 24m 26s
13:	learn: 0.5458648	total: 2.08s	remaining: 24m 46s
14:	learn: 0.5361458	total: 2.04s	remaining: 22m 41s
13:	learn: 0.5475337	total: 1.83s	remaining: 21m 44s
13:	learn: 0.5435517	total: 1.94s	remaining: 23m 6s
14:	learn: 0.5405249	total: 2.16s	remaining: 24m
14:	learn: 0.5379581	total: 1.92s	remaining: 21m 18s
15:	learn: 0.5270815	total: 2.21s	remaining: 22m 58s
15:	learn: 0.5319680	total: 2.26s	remaining: 23m 32s
14:	learn: 0.5345027	total: 2.08s	remaining: 23m 5s
15:	learn: 0.5298062	total: 2.05s	remaining: 21m 21s
14:	learn: 0.5360767	total: 2.33s	remaining: 25m 54s
16:	learn: 0.5188517	total: 2.33s	remaining: 22m 49s
16:	learn: 0.5247484	total: 2.36s	remaining: 23m 5s
16:	learn: 0.5215843	total: 2.16s	remaining: 21m 9s
15:	learn: 0.5258575	total: 2.25s	remaining: 23m 22s
17:	learn: 0.5112198	total: 2.48s	remaining: 22m 55s
17:	learn: 0.5173244	total: 2.51s	remaining: 23m 12s
15:	learn: 0.5273334	total: 2.54s	remaining: 26m 26s
17:	learn: 0.5147066	total: 2.32s	remaining: 21m 25s
16:	learn: 0.5178517	total: 2.37s	remaining: 23m 12s
18:	learn: 0.5037571	total: 2.57s	remaining: 22m 31s
18:	learn: 0.5103035	total: 2.61s	remaining: 22m 49s
16:	learn: 0.5204070	total: 2.69s	remaining: 26m 21s
18:	learn: 0.5074996	total: 2.45s	remaining: 21m 26s
19:	learn: 0.5030820	total: 2.71s	remaining: 22m 34s
19:	learn: 0.4960863	total: 2.71s	remaining: 22m 31s
17:	learn: 0.5098081	total: 2.52s	remaining: 23m 16s
19:	learn: 0.5004795	total: 2.54s	remaining: 21m 7s
20:	learn: 0.4967665	total: 2.83s	remaining: 22m 24s
17:	learn: 0.5123012	total: 2.85s	remaining: 26m 20s
20:	learn: 0.4880962	total: 2.82s	remaining: 22m 21s
18:	learn: 0.5016955	total: 2.64s	remaining: 23m 8s
20:	learn: 0.4926805	total: 2.64s	remaining: 20m 56s
21:	learn: 0.4902867	total: 2.93s	remaining: 22m 10s
21:	learn: 0.4811543	total: 2.92s	remaining: 22m 5s
18:	learn: 0.5055882	total: 2.99s	remaining: 26m 12s
19:	learn: 0.4937482	total: 2.77s	remaining: 23m 5s
22:	learn: 0.4831576	total: 3.04s	remaining: 21m 59s
22:	learn: 0.4759428	total: 3.04s	remaining: 21m 58s
21:	learn: 0.4855162	total: 2.83s	remaining: 21m 24s
23:	learn: 0.4764862	total: 3.12s	remaining: 21m 35s
20:	learn: 0.4862857	total: 2.92s	remaining: 23m 5s
19:	learn: 0.4978870	total: 3.18s	remaining: 26m 28s
23:	learn: 0.4698398	total: 3.17s	remaining: 21m 58s
24:	learn: 0.4696197	total: 3.22s	remaining: 21m 26s
21:	learn: 0.4798351	total: 3.02s	remaining: 22m 49s
22:	learn: 0.4801601	total: 3.02s	remaining: 21m 47s
25:	learn: 0.4632726	total: 3.29s	remaining: 21m 2s
20:	learn: 0.4913925	total: 3.33s	remaining: 26m 23s
24:	learn: 0.4633924	total: 3.3s	remaining: 21m 57s
22:	learn: 0.4741238	total: 3.14s	remaining: 22m 42s
23:	learn: 0.4737643	total: 3.12s	remaining: 21m 38s
26:	learn: 0.4571630	total: 3.4s	remaining: 20m 56s
25:	learn: 0.4573303	total: 3.4s	remaining: 21m 46s
23:	learn: 0.4686900	total: 3.25s	remaining: 22m 29s
21:	learn: 0.4840120	total: 3.5s	remaining: 26m 26s
24:	learn: 0.4669079	total: 3.24s	remaining: 21m 32s
26:	learn: 0.4504637	total: 3.51s	remaining: 21m 35s
27:	learn: 0.4506009	total: 3.55s	remaining: 21m 5s
24:	learn: 0.4622743	total: 3.35s	remaining: 22m 17s
25:	learn: 0.4611578	total: 3.37s	remaining: 21m 31s
27:	learn: 0.4442747	total: 3.6s	remaining: 21m 23s
22:	learn: 0.4785137	total: 3.66s	remaining: 26m 28s
25:	learn: 0.4559717	total: 3.45s	remaining: 22m 2s
28:	learn: 0.4444565	total: 3.68s	remaining: 21m 4s
28:	learn: 0.4383475	total: 3.71s	remaining: 21m 14s
26:	learn: 0.4541818	total: 3.49s	remaining: 21m 28s
26:	learn: 0.4490159	total: 3.55s	remaining: 21m 50s
23:	learn: 0.4716573	total: 3.81s	remaining: 26m 22s
29:	learn: 0.4382306	total: 3.81s	remaining: 21m 6s
29:	learn: 0.4330930	total: 3.81s	remaining: 21m 7s
27:	learn: 0.4484923	total: 3.61s	remaining: 21m 27s
27:	learn: 0.4430000	total: 3.66s	remaining: 21m 42s
30:	learn: 0.4319902	total: 3.92s	remaining: 21m 1s
30:	learn: 0.4268652	total: 3.91s	remaining: 20m 58s
24:	learn: 0.4640354	total: 3.97s	remaining: 26m 23s
28:	learn: 0.4364713	total: 3.77s	remaining: 21m 36s
28:	learn: 0.4419488	total: 3.76s	remaining: 21m 32s
31:	learn: 0.4211854	total: 4.01s	remaining: 20m 49s
31:	learn: 0.4263565	total: 4.06s	remaining: 21m 3s
29:	learn: 0.4310196	total: 3.87s	remaining: 21m 24s
25:	learn: 0.4581089	total: 4.13s	remaining: 26m 22s
32:	learn: 0.4155775	total: 4.12s	remaining: 20m 44s
29:	learn: 0.4365122	total: 3.9s	remaining: 21m 36s
32:	learn: 0.4204903	total: 4.21s	remaining: 21m 11s
30:	learn: 0.4253227	total: 3.99s	remaining: 21m 24s
33:	learn: 0.4104160	total: 4.22s	remaining: 20m 36s
26:	learn: 0.4514958	total: 4.28s	remaining: 26m 22s
31:	learn: 0.4188484	total: 4.08s	remaining: 21m 10s
30:	learn: 0.4307392	total: 4.07s	remaining: 21m 49s
33:	learn: 0.4151758	total: 4.34s	remaining: 21m 13s
34:	learn: 0.4057411	total: 4.32s	remaining: 20m 30s
27:	learn: 0.4456146	total: 4.41s	remaining: 26m 12s
35:	learn: 0.4005161	total: 4.42s	remaining: 20m 22s
32:	learn: 0.4129336	total: 4.25s	remaining: 21m 22s
34:	learn: 0.4098054	total: 4.47s	remaining: 21m 13s
31:	learn: 0.4247579	total: 4.25s	remaining: 22m 2s
36:	learn: 0.3954077	total: 4.5s	remaining: 20m 12s
28:	learn: 0.4404221	total: 4.57s	remaining: 26m 10s
33:	learn: 0.4085164	total: 4.34s	remaining: 21m 11s
37:	learn: 0.3908684	total: 4.59s	remaining: 20m 2s
35:	learn: 0.4036358	total: 4.62s	remaining: 21m 17s
32:	learn: 0.4187196	total: 4.44s	remaining: 22m 20s
36:	learn: 0.3987597	total: 4.69s	remaining: 21m 2s
29:	learn: 0.4348288	total: 4.71s	remaining: 26m 6s
34:	learn: 0.4035961	total: 4.47s	remaining: 21m 14s
38:	learn: 0.3863105	total: 4.71s	remaining: 20m 3s
37:	learn: 0.3943926	total: 4.77s	remaining: 20m 51s
35:	learn: 0.3992893	total: 4.59s	remaining: 21m 11s
30:	learn: 0.4286837	total: 4.84s	remaining: 25m 57s
33:	learn: 0.4139217	total: 4.59s	remaining: 22m 26s
39:	learn: 0.3812088	total: 4.82s	remaining: 20m 1s
38:	learn: 0.3907101	total: 4.86s	remaining: 20m 42s
36:	learn: 0.3939173	total: 4.69s	remaining: 21m 3s
34:	learn: 0.4089267	total: 4.66s	remaining: 22m 6s
39:	learn: 0.3851818	total: 4.95s	remaining: 20m 31s
31:	learn: 0.4225655	total: 4.99s	remaining: 25m 55s
40:	learn: 0.3765248	total: 4.98s	remaining: 20m 10s
35:	learn: 0.4047143	total: 4.79s	remaining: 22m 4s
40:	learn: 0.3816343	total: 5.04s	remaining: 20m 23s
37:	learn: 0.3888201	total: 4.83s	remaining: 21m 5s
41:	learn: 0.3772348	total: 5.12s	remaining: 20m 14s
32:	learn: 0.4170273	total: 5.16s	remaining: 25m 57s
38:	learn: 0.3842490	total: 4.93s	remaining: 21m
36:	learn: 0.4000709	total: 4.91s	remaining: 22m 2s
41:	learn: 0.3722106	total: 5.17s	remaining: 20m 25s
39:	learn: 0.3789620	total: 5.02s	remaining: 20m 49s
42:	learn: 0.3725979	total: 5.25s	remaining: 20m 15s
37:	learn: 0.3946762	total: 5s	remaining: 21m 51s
33:	learn: 0.4123925	total: 5.32s	remaining: 26m
42:	learn: 0.3674654	total: 5.3s	remaining: 20m 28s
38:	learn: 0.3906151	total: 5.1s	remaining: 21m 41s
40:	learn: 0.3741818	total: 5.13s	remaining: 20m 45s
43:	learn: 0.3681605	total: 5.41s	remaining: 20m 24s
39:	learn: 0.3855204	total: 5.19s	remaining: 21m 32s
34:	learn: 0.4069995	total: 5.47s	remaining: 25m 57s
43:	learn: 0.3629934	total: 5.45s	remaining: 20m 32s
41:	learn: 0.3686974	total: 5.26s	remaining: 20m 47s
44:	learn: 0.3586364	total: 5.59s	remaining: 20m 37s
44:	learn: 0.3639136	total: 5.63s	remaining: 20m 45s
35:	learn: 0.4016244	total: 5.66s	remaining: 26m 6s
40:	learn: 0.3811942	total: 5.4s	remaining: 21m 50s
45:	learn: 0.3599163	total: 5.68s	remaining: 20m 29s
42:	learn: 0.3641084	total: 5.49s	remaining: 21m 10s
41:	learn: 0.3766134	total: 5.48s	remaining: 21m 39s
46:	learn: 0.3555107	total: 5.76s	remaining: 20m 19s
45:	learn: 0.3542989	total: 5.76s	remaining: 20m 47s
36:	learn: 0.3965187	total: 5.83s	remaining: 26m 9s
47:	learn: 0.3511619	total: 5.83s	remaining: 20m 8s
43:	learn: 0.3592774	total: 5.62s	remaining: 21m 12s
42:	learn: 0.3715865	total: 5.6s	remaining: 21m 37s
48:	learn: 0.3474109	total: 5.91s	remaining: 20m
43:	learn: 0.3676276	total: 5.67s	remaining: 21m 22s
46:	learn: 0.3506350	total: 5.95s	remaining: 21m
37:	learn: 0.3913356	total: 6s	remaining: 26m 13s
44:	learn: 0.3556820	total: 5.77s	remaining: 21m 16s
49:	learn: 0.3440756	total: 6.06s	remaining: 20m 5s
44:	learn: 0.3637910	total: 5.83s	remaining: 21m 29s
47:	learn: 0.3465519	total: 6.11s	remaining: 21m 6s
38:	learn: 0.3865277	total: 6.16s	remaining: 26m 13s
45:	learn: 0.3515897	total: 5.92s	remaining: 21m 21s
50:	learn: 0.3410238	total: 6.18s	remaining: 20m 5s
45:	learn: 0.3602234	total: 5.94s	remaining: 21m 25s
48:	learn: 0.3432991	total: 6.23s	remaining: 21m 5s
39:	learn: 0.3813216	total: 6.29s	remaining: 26m 5s
46:	learn: 0.3475339	total: 6.06s	remaining: 21m 22s
51:	learn: 0.3372816	total: 6.29s	remaining: 20m 2s
46:	learn: 0.3561367	total: 6.06s	remaining: 21m 22s
49:	learn: 0.3397521	total: 6.35s	remaining: 21m 4s
52:	learn: 0.3338968	total: 6.39s	remaining: 19m 59s
47:	learn: 0.3435740	total: 6.18s	remaining: 21m 21s
40:	learn: 0.3763403	total: 6.42s	remaining: 26m
47:	learn: 0.3522864	total: 6.16s	remaining: 21m 16s
48:	learn: 0.3405889	total: 6.24s	remaining: 21m 6s
41:	learn: 0.3721122	total: 6.53s	remaining: 25m 47s
50:	learn: 0.3357491	total: 6.48s	remaining: 21m 4s
48:	learn: 0.3491174	total: 6.28s	remaining: 21m 14s
49:	learn: 0.3373135	total: 6.36s	remaining: 21m 5s
53:	learn: 0.3299322	total: 6.58s	remaining: 20m 11s
49:	learn: 0.3451841	total: 6.37s	remaining: 21m 7s
51:	learn: 0.3326565	total: 6.6s	remaining: 21m 2s
42:	learn: 0.3675614	total: 6.67s	remaining: 25m 44s
50:	learn: 0.3337154	total: 6.46s	remaining: 21m 1s
50:	learn: 0.3416955	total: 6.52s	remaining: 21m 12s
52:	learn: 0.3298706	total: 6.75s	remaining: 21m 6s
43:	learn: 0.3631218	total: 6.8s	remaining: 25m 38s
54:	learn: 0.3266012	total: 6.78s	remaining: 20m 26s
53:	learn: 0.3261660	total: 6.81s	remaining: 20m 54s
51:	learn: 0.3309063	total: 6.64s	remaining: 21m 10s
51:	learn: 0.3378896	total: 6.63s	remaining: 21m 8s
54:	learn: 0.3230722	total: 6.91s	remaining: 20m 48s
44:	learn: 0.3595234	total: 6.96s	remaining: 25m 39s
52:	learn: 0.3282070	total: 6.74s	remaining: 21m 4s
55:	learn: 0.3225715	total: 6.96s	remaining: 20m 36s
53:	learn: 0.3247544	total: 6.8s	remaining: 20m 53s
55:	learn: 0.3205046	total: 7s	remaining: 20m 43s
52:	learn: 0.3349429	total: 6.8s	remaining: 21m 17s
45:	learn: 0.3556723	total: 7.08s	remaining: 25m 31s
56:	learn: 0.3195848	total: 7.13s	remaining: 20m 43s
54:	learn: 0.3217879	total: 6.95s	remaining: 20m 55s
56:	learn: 0.3171147	total: 7.14s	remaining: 20m 46s
53:	learn: 0.3313586	total: 6.92s	remaining: 21m 14s
46:	learn: 0.3514753	total: 7.24s	remaining: 25m 32s
57:	learn: 0.3133389	total: 7.21s	remaining: 20m 36s
57:	learn: 0.3165116	total: 7.25s	remaining: 20m 43s
55:	learn: 0.3185593	total: 7.04s	remaining: 20m 49s
54:	learn: 0.3283070	total: 7.08s	remaining: 21m 20s
47:	learn: 0.3476458	total: 7.36s	remaining: 25m 25s
56:	learn: 0.3150573	total: 7.15s	remaining: 20m 46s
58:	learn: 0.3132278	total: 7.37s	remaining: 20m 41s
58:	learn: 0.3106613	total: 7.35s	remaining: 20m 37s
59:	learn: 0.3107160	total: 7.44s	remaining: 20m 32s
48:	learn: 0.3444239	total: 7.46s	remaining: 25m 14s
57:	learn: 0.3119398	total: 7.24s	remaining: 20m 41s
59:	learn: 0.3079898	total: 7.5s	remaining: 20m 41s
55:	learn: 0.3242716	total: 7.27s	remaining: 21m 31s
49:	learn: 0.3407183	total: 7.56s	remaining: 25m 4s
60:	learn: 0.3081853	total: 7.54s	remaining: 20m 28s
58:	learn: 0.3090262	total: 7.36s	remaining: 20m 39s
61:	learn: 0.3053866	total: 7.61s	remaining: 20m 19s
59:	learn: 0.3063095	total: 7.41s	remaining: 20m 27s
50:	learn: 0.3373504	total: 7.68s	remaining: 24m 57s
62:	learn: 0.3020129	total: 7.67s	remaining: 20m 10s
60:	learn: 0.3050427	total: 7.65s	remaining: 20m 46s
60:	learn: 0.3034247	total: 7.49s	remaining: 20m 20s
56:	learn: 0.3207208	total: 7.47s	remaining: 21m 43s
63:	learn: 0.2993058	total: 7.74s	remaining: 20m 2s
61:	learn: 0.3008376	total: 7.54s	remaining: 20m 8s
51:	learn: 0.3338309	total: 7.82s	remaining: 24m 55s
64:	learn: 0.2970609	total: 7.8s	remaining: 19m 53s
61:	learn: 0.3023472	total: 7.8s	remaining: 20m 50s
62:	learn: 0.2981134	total: 7.62s	remaining: 20m 2s
65:	learn: 0.2942296	total: 7.87s	remaining: 19m 45s
52:	learn: 0.3308580	total: 7.93s	remaining: 24m 48s
57:	learn: 0.3171274	total: 7.68s	remaining: 21m 57s
63:	learn: 0.2951669	total: 7.74s	remaining: 20m 1s
66:	learn: 0.2918318	total: 7.97s	remaining: 19m 41s
62:	learn: 0.2992473	total: 7.95s	remaining: 20m 53s
64:	learn: 0.2922044	total: 7.79s	remaining: 19m 50s
53:	learn: 0.3273301	total: 8.04s	remaining: 24m 41s
67:	learn: 0.2885675	total: 8.05s	remaining: 19m 36s
58:	learn: 0.3143001	total: 7.85s	remaining: 22m 2s
63:	learn: 0.2966712	total: 8.08s	remaining: 20m 54s
54:	learn: 0.3242935	total: 8.14s	remaining: 24m 32s
65:	learn: 0.2897984	total: 7.91s	remaining: 19m 50s
68:	learn: 0.2859870	total: 8.21s	remaining: 19m 41s
64:	learn: 0.2936499	total: 8.19s	remaining: 20m 51s

[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:   10.7s finished

55:	learn: 0.3209284	total: 8.27s	remaining: 24m 28s
66:	learn: 0.2875223	total: 8.06s	remaining: 19m 54s
69:	learn: 0.2838100	total: 8.34s	remaining: 19m 43s
65:	learn: 0.2911463	total: 8.33s	remaining: 20m 53s
56:	learn: 0.3174065	total: 8.38s	remaining: 24m 22s
59:	learn: 0.3117699	total: 8.12s	remaining: 22m 24s
67:	learn: 0.2853386	total: 8.18s	remaining: 19m 55s
60:	learn: 0.3091989	total: 8.18s	remaining: 22m 12s
70:	learn: 0.2812967	total: 8.45s	remaining: 19m 42s
66:	learn: 0.2890218	total: 8.45s	remaining: 20m 53s
57:	learn: 0.3139188	total: 8.51s	remaining: 24m 19s
61:	learn: 0.3063686	total: 8.28s	remaining: 22m 6s
71:	learn: 0.2788470	total: 8.54s	remaining: 19m 37s
68:	learn: 0.2829016	total: 8.35s	remaining: 20m 1s
67:	learn: 0.2863468	total: 8.59s	remaining: 20m 55s
58:	learn: 0.3114999	total: 8.65s	remaining: 24m 17s
62:	learn: 0.3036417	total: 8.39s	remaining: 22m 3s
72:	learn: 0.2769307	total: 8.65s	remaining: 19m 36s
63:	learn: 0.3011399	total: 8.49s	remaining: 21m 58s
73:	learn: 0.2747669	total: 8.74s	remaining: 19m 32s
69:	learn: 0.2804245	total: 8.53s	remaining: 20m 10s
68:	learn: 0.2839856	total: 8.73s	remaining: 20m 56s
59:	learn: 0.3090353	total: 8.78s	remaining: 24m 14s
64:	learn: 0.2980389	total: 8.59s	remaining: 21m 53s
74:	learn: 0.2730432	total: 8.86s	remaining: 19m 32s
70:	learn: 0.2778049	total: 8.66s	remaining: 20m 11s
69:	learn: 0.2810283	total: 8.86s	remaining: 20m 57s
60:	learn: 0.3062814	total: 8.94s	remaining: 24m 16s
65:	learn: 0.2957822	total: 8.73s	remaining: 21m 53s
71:	learn: 0.2754501	total: 8.78s	remaining: 20m 10s
75:	learn: 0.2707870	total: 9s	remaining: 19m 35s
70:	learn: 0.2781787	total: 9.02s	remaining: 21m 1s
61:	learn: 0.3032675	total: 9.07s	remaining: 24m 14s
66:	learn: 0.2937896	total: 8.85s	remaining: 21m 52s
76:	learn: 0.2686331	total: 9.12s	remaining: 19m 35s
72:	learn: 0.2733180	total: 8.92s	remaining: 20m 13s
62:	learn: 0.3009102	total: 9.19s	remaining: 24m 8s
71:	learn: 0.2757647	total: 9.16s	remaining: 21m 2s
77:	learn: 0.2661725	total: 9.22s	remaining: 19m 32s
67:	learn: 0.2909864	total: 8.99s	remaining: 21m 52s
63:	learn: 0.2984597	total: 9.3s	remaining: 24m 3s
72:	learn: 0.2734907	total: 9.28s	remaining: 21m 2s
73:	learn: 0.2710925	total: 9.11s	remaining: 20m 22s
78:	learn: 0.2640362	total: 9.34s	remaining: 19m 32s
68:	learn: 0.2882652	total: 9.1s	remaining: 21m 50s
79:	learn: 0.2620450	total: 9.41s	remaining: 19m 27s
64:	learn: 0.2956164	total: 9.45s	remaining: 24m 3s
73:	learn: 0.2710547	total: 9.41s	remaining: 21m 1s
69:	learn: 0.2860245	total: 9.22s	remaining: 21m 48s
74:	learn: 0.2686313	total: 9.26s	remaining: 20m 25s
80:	learn: 0.2603011	total: 9.51s	remaining: 19m 24s
74:	learn: 0.2681661	total: 9.54s	remaining: 21m 1s
65:	learn: 0.2931779	total: 9.59s	remaining: 24m 3s
81:	learn: 0.2583377	total: 9.61s	remaining: 19m 21s
70:	learn: 0.2833307	total: 9.38s	remaining: 21m 52s
75:	learn: 0.2664617	total: 9.41s	remaining: 20m 29s
75:	learn: 0.2662296	total: 9.66s	remaining: 21m 1s
82:	learn: 0.2564192	total: 9.7s	remaining: 19m 19s
66:	learn: 0.2910357	total: 9.73s	remaining: 24m 3s
71:	learn: 0.2806953	total: 9.51s	remaining: 21m 51s
76:	learn: 0.2643307	total: 9.57s	remaining: 20m 34s
83:	learn: 0.2550426	total: 9.81s	remaining: 19m 17s
76:	learn: 0.2642039	total: 9.79s	remaining: 21m 2s
67:	learn: 0.2884303	total: 9.9s	remaining: 24m 6s
84:	learn: 0.2535973	total: 9.88s	remaining: 19m 12s
72:	learn: 0.2783984	total: 9.65s	remaining: 21m 52s
77:	learn: 0.2621827	total: 9.9s	remaining: 20m 58s
77:	learn: 0.2624794	total: 9.74s	remaining: 20m 39s
85:	learn: 0.2514801	total: 9.99s	remaining: 19m 11s
68:	learn: 0.2857696	total: 10s	remaining: 24m 3s
73:	learn: 0.2757761	total: 9.77s	remaining: 21m 50s
78:	learn: 0.2601335	total: 10s	remaining: 20m 57s
86:	learn: 0.2497321	total: 10.1s	remaining: 19m 9s
78:	learn: 0.2607188	total: 9.89s	remaining: 20m 42s
74:	learn: 0.2735475	total: 9.88s	remaining: 21m 47s
69:	learn: 0.2831213	total: 10.2s	remaining: 24m 2s
79:	learn: 0.2581047	total: 10.1s	remaining: 20m 57s
87:	learn: 0.2477781	total: 10.2s	remaining: 19m 9s
75:	learn: 0.2714733	total: 10s	remaining: 21m 47s
80:	learn: 0.2561281	total: 10.2s	remaining: 20m 53s
79:	learn: 0.2583984	total: 10.1s	remaining: 20m 46s
70:	learn: 0.2801456	total: 10.3s	remaining: 24m 2s
88:	learn: 0.2458317	total: 10.3s	remaining: 19m 10s
81:	learn: 0.2541213	total: 10.3s	remaining: 20m 48s
76:	learn: 0.2694016	total: 10.2s	remaining: 21m 48s
80:	learn: 0.2563692	total: 10.2s	remaining: 20m 50s
89:	learn: 0.2444078	total: 10.5s	remaining: 19m 12s
71:	learn: 0.2776981	total: 10.5s	remaining: 24m 6s
82:	learn: 0.2524025	total: 10.5s	remaining: 20m 50s
77:	learn: 0.2669834	total: 10.3s	remaining: 21m 47s
90:	learn: 0.2421139	total: 10.5s	remaining: 19m 7s
81:	learn: 0.2543990	total: 10.4s	remaining: 20m 53s
83:	learn: 0.2503346	total: 10.6s	remaining: 20m 48s
72:	learn: 0.2754046	total: 10.6s	remaining: 24m 6s
91:	learn: 0.2403503	total: 10.7s	remaining: 19m 7s
78:	learn: 0.2650300	total: 10.4s	remaining: 21m 47s
82:	learn: 0.2527563	total: 10.5s	remaining: 20m 54s
84:	learn: 0.2482064	total: 10.7s	remaining: 20m 49s
73:	learn: 0.2731332	total: 10.8s	remaining: 24m 3s
92:	learn: 0.2386818	total: 10.8s	remaining: 19m 5s
79:	learn: 0.2625812	total: 10.5s	remaining: 21m 46s
85:	learn: 0.2464322	total: 10.8s	remaining: 20m 47s
83:	learn: 0.2508749	total: 10.6s	remaining: 20m 54s
93:	learn: 0.2373796	total: 10.9s	remaining: 19m 7s
74:	learn: 0.2708164	total: 10.9s	remaining: 24m 3s
80:	learn: 0.2609300	total: 10.7s	remaining: 21m 49s
86:	learn: 0.2446659	total: 10.9s	remaining: 20m 45s
84:	learn: 0.2494047	total: 10.8s	remaining: 20m 54s
75:	learn: 0.2688288	total: 11s	remaining: 23m 57s
94:	learn: 0.2359559	total: 11s	remaining: 19m 6s
87:	learn: 0.2431252	total: 11s	remaining: 20m 42s
81:	learn: 0.2590080	total: 10.8s	remaining: 21m 50s
85:	learn: 0.2476454	total: 10.9s	remaining: 20m 55s
95:	learn: 0.2344205	total: 11.1s	remaining: 19m 6s
76:	learn: 0.2664268	total: 11.2s	remaining: 23m 58s
88:	learn: 0.2417745	total: 11.1s	remaining: 20m 38s
96:	learn: 0.2325004	total: 11.2s	remaining: 19m 2s
82:	learn: 0.2572504	total: 11s	remaining: 21m 50s
86:	learn: 0.2458145	total: 11s	remaining: 20m 57s
89:	learn: 0.2399726	total: 11.2s	remaining: 20m 37s
77:	learn: 0.2641818	total: 11.3s	remaining: 23m 57s
97:	learn: 0.2310673	total: 11.3s	remaining: 19m 1s
83:	learn: 0.2556346	total: 11.1s	remaining: 21m 49s
90:	learn: 0.2386150	total: 11.3s	remaining: 20m 34s
78:	learn: 0.2618223	total: 11.4s	remaining: 23m 55s
98:	learn: 0.2298167	total: 11.4s	remaining: 19m 1s
87:	learn: 0.2438438	total: 11.2s	remaining: 21m 2s
84:	learn: 0.2534564	total: 11.2s	remaining: 21m 49s
91:	learn: 0.2366236	total: 11.5s	remaining: 20m 33s
79:	learn: 0.2594014	total: 11.6s	remaining: 23m 52s
99:	learn: 0.2279717	total: 11.5s	remaining: 19m 3s
88:	learn: 0.2421517	total: 11.4s	remaining: 21m 4s
100:	learn: 0.2263246	total: 11.6s	remaining: 19m
85:	learn: 0.2517165	total: 11.4s	remaining: 21m 54s
92:	learn: 0.2348460	total: 11.6s	remaining: 20m 39s
80:	learn: 0.2577152	total: 11.7s	remaining: 23m 51s
89:	learn: 0.2404384	total: 11.5s	remaining: 21m 3s
101:	learn: 0.2249004	total: 11.8s	remaining: 19m
86:	learn: 0.2496063	total: 11.5s	remaining: 21m 53s
93:	learn: 0.2330927	total: 11.8s	remaining: 20m 41s
81:	learn: 0.2555806	total: 11.8s	remaining: 23m 50s
90:	learn: 0.2386731	total: 11.6s	remaining: 21m 4s
102:	learn: 0.2237261	total: 11.9s	remaining: 19m 1s
91:	learn: 0.2368602	total: 11.7s	remaining: 20m 59s
82:	learn: 0.2537919	total: 11.9s	remaining: 23m 47s
87:	learn: 0.2480664	total: 11.7s	remaining: 21m 56s
94:	learn: 0.2316774	total: 11.9s	remaining: 20m 44s
92:	learn: 0.2355807	total: 11.8s	remaining: 20m 54s
103:	learn: 0.2223814	total: 12s	remaining: 19m 4s
83:	learn: 0.2520139	total: 12.1s	remaining: 23m 44s
88:	learn: 0.2459948	total: 11.8s	remaining: 21m 55s
93:	learn: 0.2339846	total: 11.9s	remaining: 20m 51s
104:	learn: 0.2208401	total: 12.1s	remaining: 19m 1s
95:	learn: 0.2302920	total: 12.1s	remaining: 20m 48s
89:	learn: 0.2442366	total: 11.9s	remaining: 21m 52s
105:	learn: 0.2198635	total: 12.2s	remaining: 18m 58s
84:	learn: 0.2501777	total: 12.2s	remaining: 23m 46s
94:	learn: 0.2325721	total: 12s	remaining: 20m 51s
96:	learn: 0.2287705	total: 12.2s	remaining: 20m 47s
90:	learn: 0.2425185	total: 12s	remaining: 21m 49s
85:	learn: 0.2486136	total: 12.3s	remaining: 23m 41s
106:	learn: 0.2185174	total: 12.3s	remaining: 18m 58s
97:	learn: 0.2275766	total: 12.3s	remaining: 20m 46s
95:	learn: 0.2310089	total: 12.2s	remaining: 20m 53s
91:	learn: 0.2405717	total: 12.1s	remaining: 21m 48s
86:	learn: 0.2467218	total: 12.5s	remaining: 23m 39s
107:	learn: 0.2171836	total: 12.4s	remaining: 18m 59s
98:	learn: 0.2262317	total: 12.5s	remaining: 20m 46s
96:	learn: 0.2292667	total: 12.3s	remaining: 20m 52s
92:	learn: 0.2390992	total: 12.3s	remaining: 21m 47s
108:	learn: 0.2158651	total: 12.5s	remaining: 18m 58s
87:	learn: 0.2451373	total: 12.6s	remaining: 23m 40s
97:	learn: 0.2274617	total: 12.4s	remaining: 20m 53s
99:	learn: 0.2247005	total: 12.6s	remaining: 20m 47s
93:	learn: 0.2375553	total: 12.4s	remaining: 21m 45s
109:	learn: 0.2145621	total: 12.7s	remaining: 18m 58s
98:	learn: 0.2260189	total: 12.5s	remaining: 20m 49s
88:	learn: 0.2432765	total: 12.7s	remaining: 23m 38s
100:	learn: 0.2237097	total: 12.7s	remaining: 20m 47s
110:	learn: 0.2132926	total: 12.8s	remaining: 18m 56s
94:	learn: 0.2363482	total: 12.5s	remaining: 21m 46s
99:	learn: 0.2242906	total: 12.6s	remaining: 20m 47s
89:	learn: 0.2417820	total: 12.9s	remaining: 23m 38s
101:	learn: 0.2221850	total: 12.8s	remaining: 20m 46s
111:	learn: 0.2119455	total: 12.9s	remaining: 18m 56s
95:	learn: 0.2349444	total: 12.6s	remaining: 21m 44s
100:	learn: 0.2229286	total: 12.7s	remaining: 20m 47s
102:	learn: 0.2204950	total: 12.9s	remaining: 20m 43s
90:	learn: 0.2397408	total: 13s	remaining: 23m 36s
112:	learn: 0.2106848	total: 13s	remaining: 18m 58s
96:	learn: 0.2333702	total: 12.8s	remaining: 21m 46s
91:	learn: 0.2380421	total: 13.1s	remaining: 23m 30s
101:	learn: 0.2214804	total: 12.9s	remaining: 20m 49s
103:	learn: 0.2193197	total: 13.1s	remaining: 20m 43s
97:	learn: 0.2318992	total: 12.9s	remaining: 21m 41s
113:	learn: 0.2093588	total: 13.2s	remaining: 19m 2s
104:	learn: 0.2179767	total: 13.2s	remaining: 20m 39s
92:	learn: 0.2368670	total: 13.3s	remaining: 23m 32s
102:	learn: 0.2201213	total: 13s	remaining: 20m 53s
114:	learn: 0.2079044	total: 13.3s	remaining: 19m
98:	learn: 0.2305056	total: 13s	remaining: 21m 41s
93:	learn: 0.2350081	total: 13.4s	remaining: 23m 27s
105:	learn: 0.2169371	total: 13.3s	remaining: 20m 42s
115:	learn: 0.2064563	total: 13.4s	remaining: 19m
103:	learn: 0.2187873	total: 13.2s	remaining: 20m 53s
94:	learn: 0.2334789	total: 13.4s	remaining: 23m 21s
99:	learn: 0.2288070	total: 13.2s	remaining: 21m 45s
106:	learn: 0.2156531	total: 13.5s	remaining: 20m 43s
104:	learn: 0.2175132	total: 13.3s	remaining: 20m 50s
116:	learn: 0.2052690	total: 13.5s	remaining: 19m 2s
95:	learn: 0.2321926	total: 13.6s	remaining: 23m 20s
117:	learn: 0.2038248	total: 13.6s	remaining: 18m 58s
107:	learn: 0.2142993	total: 13.6s	remaining: 20m 43s
100:	learn: 0.2271458	total: 13.4s	remaining: 21m 48s
105:	learn: 0.2164288	total: 13.4s	remaining: 20m 51s
96:	learn: 0.2306555	total: 13.7s	remaining: 23m 17s
118:	learn: 0.2026115	total: 13.7s	remaining: 18m 57s
106:	learn: 0.2151264	total: 13.5s	remaining: 20m 50s
108:	learn: 0.2129537	total: 13.7s	remaining: 20m 45s
101:	learn: 0.2256203	total: 13.5s	remaining: 21m 51s
119:	learn: 0.2011140	total: 13.8s	remaining: 18m 56s
97:	learn: 0.2290419	total: 13.8s	remaining: 23m 18s
109:	learn: 0.2117124	total: 13.8s	remaining: 20m 40s
107:	learn: 0.2137597	total: 13.7s	remaining: 20m 52s
102:	learn: 0.2240504	total: 13.7s	remaining: 21m 52s
120:	learn: 0.2002338	total: 13.9s	remaining: 18m 57s
110:	learn: 0.2106456	total: 13.9s	remaining: 20m 40s
108:	learn: 0.2126797	total: 13.8s	remaining: 20m 50s
98:	learn: 0.2275392	total: 14s	remaining: 23m 23s
111:	learn: 0.2093847	total: 14s	remaining: 20m 35s
103:	learn: 0.2228675	total: 13.8s	remaining: 21m 55s
121:	learn: 0.1991595	total: 14.1s	remaining: 19m
109:	learn: 0.2115067	total: 13.9s	remaining: 20m 47s
99:	learn: 0.2259708	total: 14.1s	remaining: 23m 19s
112:	learn: 0.2082870	total: 14.1s	remaining: 20m 35s
122:	learn: 0.1978668	total: 14.2s	remaining: 19m
104:	learn: 0.2215745	total: 14s	remaining: 21m 56s
110:	learn: 0.2101515	total: 14s	remaining: 20m 48s
113:	learn: 0.2069393	total: 14.2s	remaining: 20m 34s
100:	learn: 0.2243801	total: 14.3s	remaining: 23m 20s
123:	learn: 0.1968143	total: 14.3s	remaining: 18m 59s
111:	learn: 0.2092059	total: 14.1s	remaining: 20m 47s
105:	learn: 0.2202352	total: 14.2s	remaining: 22m 1s
101:	learn: 0.2229331	total: 14.4s	remaining: 23m 21s
114:	learn: 0.2053982	total: 14.4s	remaining: 20m 38s
124:	learn: 0.1955883	total: 14.5s	remaining: 19m 2s
112:	learn: 0.2079655	total: 14.2s	remaining: 20m 46s
106:	learn: 0.2190662	total: 14.3s	remaining: 22m
115:	learn: 0.2040658	total: 14.5s	remaining: 20m 38s
125:	learn: 0.1943541	total: 14.6s	remaining: 19m 2s
102:	learn: 0.2214717	total: 14.6s	remaining: 23m 23s
113:	learn: 0.2064941	total: 14.4s	remaining: 20m 48s
116:	learn: 0.2033504	total: 14.7s	remaining: 20m 37s
107:	learn: 0.2178218	total: 14.4s	remaining: 22m 1s
126:	learn: 0.1934442	total: 14.7s	remaining: 19m 2s
103:	learn: 0.2200765	total: 14.8s	remaining: 23m 24s
114:	learn: 0.2052639	total: 14.5s	remaining: 20m 49s
117:	learn: 0.2021960	total: 14.8s	remaining: 20m 36s
127:	learn: 0.1925276	total: 14.8s	remaining: 19m 1s
108:	learn: 0.2163628	total: 14.6s	remaining: 22m 2s
104:	learn: 0.2189316	total: 14.9s	remaining: 23m 23s
128:	learn: 0.1913934	total: 14.9s	remaining: 18m 57s
118:	learn: 0.2010911	total: 14.9s	remaining: 20m 35s
115:	learn: 0.2039037	total: 14.7s	remaining: 20m 52s
129:	learn: 0.1902129	total: 15s	remaining: 18m 55s
109:	learn: 0.2150952	total: 14.7s	remaining: 22m 4s
105:	learn: 0.2175847	total: 15s	remaining: 23m 22s
119:	learn: 0.1997509	total: 15s	remaining: 20m 34s
130:	learn: 0.1891522	total: 15s	remaining: 18m 53s
116:	learn: 0.2026949	total: 14.9s	remaining: 20m 55s
110:	learn: 0.2138257	total: 14.9s	remaining: 22m 4s
120:	learn: 0.1985166	total: 15.1s	remaining: 20m 34s
131:	learn: 0.1879423	total: 15.2s	remaining: 18m 53s
106:	learn: 0.2162133	total: 15.2s	remaining: 23m 23s
132:	learn: 0.1867632	total: 15.2s	remaining: 18m 49s
117:	learn: 0.2013538	total: 15s	remaining: 20m 59s
121:	learn: 0.1975559	total: 15.2s	remaining: 20m 33s
111:	learn: 0.2126183	total: 15s	remaining: 22m 5s
107:	learn: 0.2152563	total: 15.3s	remaining: 23m 23s
133:	learn: 0.1858603	total: 15.3s	remaining: 18m 48s
122:	learn: 0.1960599	total: 15.3s	remaining: 20m 31s
118:	learn: 0.2002286	total: 15.1s	remaining: 20m 57s
108:	learn: 0.2140580	total: 15.4s	remaining: 23m 20s
112:	learn: 0.2117185	total: 15.2s	remaining: 22m 8s
134:	learn: 0.1848277	total: 15.5s	remaining: 18m 49s
123:	learn: 0.1948080	total: 15.5s	remaining: 20m 30s
119:	learn: 0.1989812	total: 15.3s	remaining: 20m 58s
109:	learn: 0.2127778	total: 15.5s	remaining: 23m 16s
113:	learn: 0.2103423	total: 15.3s	remaining: 22m 7s
135:	learn: 0.1838307	total: 15.6s	remaining: 18m 49s
124:	learn: 0.1938715	total: 15.6s	remaining: 20m 29s
110:	learn: 0.2115157	total: 15.7s	remaining: 23m 16s
120:	learn: 0.1979211	total: 15.5s	remaining: 21m 3s
136:	learn: 0.1830105	total: 15.7s	remaining: 18m 50s
114:	learn: 0.2090862	total: 15.5s	remaining: 22m 8s
125:	learn: 0.1928396	total: 15.7s	remaining: 20m 30s
111:	learn: 0.2102654	total: 15.8s	remaining: 23m 13s
137:	learn: 0.1818562	total: 15.8s	remaining: 18m 47s
121:	learn: 0.1970343	total: 15.6s	remaining: 21m 6s
115:	learn: 0.2078414	total: 15.6s	remaining: 22m 10s
126:	learn: 0.1918270	total: 15.8s	remaining: 20m 31s
138:	learn: 0.1810916	total: 15.9s	remaining: 18m 47s
112:	learn: 0.2088064	total: 15.9s	remaining: 23m 15s
127:	learn: 0.1907418	total: 15.9s	remaining: 20m 27s
139:	learn: 0.1803206	total: 16s	remaining: 18m 46s
122:	learn: 0.1959980	total: 15.8s	remaining: 21m 7s
116:	learn: 0.2064319	total: 15.8s	remaining: 22m 12s
128:	learn: 0.1899128	total: 16s	remaining: 20m 26s
113:	learn: 0.2075227	total: 16.1s	remaining: 23m 15s
140:	learn: 0.1792585	total: 16.1s	remaining: 18m 46s
123:	learn: 0.1951218	total: 15.9s	remaining: 21m 7s
117:	learn: 0.2052447	total: 15.9s	remaining: 22m 12s
129:	learn: 0.1889020	total: 16.1s	remaining: 20m 25s
114:	learn: 0.2060655	total: 16.2s	remaining: 23m 13s
141:	learn: 0.1781855	total: 16.2s	remaining: 18m 47s
124:	learn: 0.1939864	total: 16s	remaining: 21m 7s
130:	learn: 0.1880235	total: 16.2s	remaining: 20m 23s
118:	learn: 0.2041292	total: 16.1s	remaining: 22m 13s
142:	learn: 0.1774164	total: 16.3s	remaining: 18m 44s
115:	learn: 0.2048145	total: 16.4s	remaining: 23m 14s
131:	learn: 0.1871484	total: 16.4s	remaining: 20m 23s
125:	learn: 0.1929740	total: 16.2s	remaining: 21m 9s
143:	learn: 0.1764356	total: 16.4s	remaining: 18m 43s
116:	learn: 0.2039718	total: 16.5s	remaining: 23m 14s
119:	learn: 0.2028781	total: 16.2s	remaining: 22m 16s
144:	learn: 0.1756408	total: 16.5s	remaining: 18m 42s
132:	learn: 0.1862165	total: 16.5s	remaining: 20m 24s
126:	learn: 0.1917058	total: 16.4s	remaining: 21m 11s
145:	learn: 0.1748965	total: 16.6s	remaining: 18m 39s
120:	learn: 0.2016842	total: 16.4s	remaining: 22m 15s
117:	learn: 0.2029633	total: 16.7s	remaining: 23m 14s
127:	learn: 0.1908574	total: 16.5s	remaining: 21m 9s
133:	learn: 0.1850951	total: 16.7s	remaining: 20m 26s
146:	learn: 0.1741323	total: 16.7s	remaining: 18m 39s
121:	learn: 0.2008494	total: 16.5s	remaining: 22m 13s
118:	learn: 0.2016296	total: 16.8s	remaining: 23m 11s
128:	learn: 0.1897547	total: 16.5s	remaining: 21m 6s
147:	learn: 0.1733206	total: 16.8s	remaining: 18m 36s
134:	learn: 0.1841297	total: 16.8s	remaining: 20m 27s
119:	learn: 0.2003401	total: 16.9s	remaining: 23m 8s
122:	learn: 0.1998026	total: 16.6s	remaining: 22m 13s
148:	learn: 0.1724872	total: 16.9s	remaining: 18m 35s
129:	learn: 0.1886016	total: 16.7s	remaining: 21m 5s
120:	learn: 0.1993323	total: 17s	remaining: 23m 5s
135:	learn: 0.1833011	total: 16.9s	remaining: 20m 28s
123:	learn: 0.1987240	total: 16.7s	remaining: 22m 12s
130:	learn: 0.1877579	total: 16.8s	remaining: 21m 3s
149:	learn: 0.1716687	total: 17s	remaining: 18m 36s
124:	learn: 0.1974745	total: 16.8s	remaining: 22m 8s
121:	learn: 0.1984960	total: 17.1s	remaining: 23m 4s
131:	learn: 0.1866778	total: 16.9s	remaining: 21m 1s
136:	learn: 0.1823420	total: 17.1s	remaining: 20m 30s
125:	learn: 0.1963913	total: 16.9s	remaining: 22m 6s
150:	learn: 0.1707671	total: 17.2s	remaining: 18m 41s
122:	learn: 0.1971398	total: 17.2s	remaining: 23m 3s
132:	learn: 0.1857348	total: 17s	remaining: 21m 2s
137:	learn: 0.1816012	total: 17.2s	remaining: 20m 31s
151:	learn: 0.1698568	total: 17.3s	remaining: 18m 40s
126:	learn: 0.1955268	total: 17.1s	remaining: 22m 5s
123:	learn: 0.1960038	total: 17.3s	remaining: 23m 1s
133:	learn: 0.1845961	total: 17.1s	remaining: 21m
138:	learn: 0.1805485	total: 17.4s	remaining: 20m 31s
152:	learn: 0.1691487	total: 17.4s	remaining: 18m 41s
124:	learn: 0.1949063	total: 17.5s	remaining: 22m 58s
127:	learn: 0.1944843	total: 17.2s	remaining: 22m 6s
134:	learn: 0.1835977	total: 17.2s	remaining: 20m 59s
153:	learn: 0.1682309	total: 17.5s	remaining: 18m 40s
139:	learn: 0.1793283	total: 17.5s	remaining: 20m 32s
135:	learn: 0.1827721	total: 17.3s	remaining: 20m 56s
128:	learn: 0.1933036	total: 17.3s	remaining: 22m 5s
125:	learn: 0.1939225	total: 17.6s	remaining: 23m
154:	learn: 0.1676728	total: 17.6s	remaining: 18m 39s
129:	learn: 0.1922231	total: 17.4s	remaining: 22m
140:	learn: 0.1783715	total: 17.6s	remaining: 20m 32s
126:	learn: 0.1927224	total: 17.7s	remaining: 22m 57s
136:	learn: 0.1820858	total: 17.5s	remaining: 20m 58s
155:	learn: 0.1668165	total: 17.8s	remaining: 18m 42s

[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:  1.5min finished

1115:	learn: 0.0175187	total: 1m 32s	remaining: 12m 12s
1198:	learn: 0.0159813	total: 1m 32s	remaining: 11m 18s
1246:	learn: 0.0143628	total: 1m 32s	remaining: 10m 48s
1192:	learn: 0.0155782	total: 1m 32s	remaining: 11m 21s
1116:	learn: 0.0174858	total: 1m 32s	remaining: 12m 12s
1199:	learn: 0.0159591	total: 1m 32s	remaining: 11m 17s
1176:	learn: 0.0161487	total: 1m 32s	remaining: 11m 30s
1193:	learn: 0.0155591	total: 1m 32s	remaining: 11m 21s
1247:	learn: 0.0143492	total: 1m 32s	remaining: 10m 47s
1117:	learn: 0.0174577	total: 1m 32s	remaining: 12m 11s
1177:	learn: 0.0161317	total: 1m 32s	remaining: 11m 30s
1200:	learn: 0.0159345	total: 1m 32s	remaining: 11m 17s
1194:	learn: 0.0155391	total: 1m 32s	remaining: 11m 20s
1118:	learn: 0.0174394	total: 1m 32s	remaining: 12m 11s
1248:	learn: 0.0143362	total: 1m 32s	remaining: 10m 47s
1178:	learn: 0.0161083	total: 1m 32s	remaining: 11m 30s
1195:	learn: 0.0155179	total: 1m 32s	remaining: 11m 20s
1201:	learn: 0.0159215	total: 1m 32s	remaining: 11m 17s
1119:	learn: 0.0174113	total: 1m 32s	remaining: 12m 11s
1249:	learn: 0.0143180	total: 1m 32s	remaining: 10m 47s
1196:	learn: 0.0154975	total: 1m 32s	remaining: 11m 20s
1179:	learn: 0.0160788	total: 1m 32s	remaining: 11m 29s
1120:	learn: 0.0173786	total: 1m 32s	remaining: 12m 10s
1202:	learn: 0.0158941	total: 1m 32s	remaining: 11m 16s
1197:	learn: 0.0154728	total: 1m 32s	remaining: 11m 19s
1180:	learn: 0.0160497	total: 1m 32s	remaining: 11m 29s
1121:	learn: 0.0173492	total: 1m 32s	remaining: 12m 10s
1203:	learn: 0.0158753	total: 1m 32s	remaining: 11m 16s
1250:	learn: 0.0142978	total: 1m 32s	remaining: 10m 47s
1198:	learn: 0.0154458	total: 1m 32s	remaining: 11m 19s
1181:	learn: 0.0160259	total: 1m 32s	remaining: 11m 28s
1251:	learn: 0.0142842	total: 1m 32s	remaining: 10m 46s
1204:	learn: 0.0158516	total: 1m 32s	remaining: 11m 15s
1122:	learn: 0.0173260	total: 1m 32s	remaining: 12m 9s
1182:	learn: 0.0160096	total: 1m 32s	remaining: 11m 28s
1199:	learn: 0.0154215	total: 1m 32s	remaining: 11m 18s
1183:	learn: 0.0159787	total: 1m 32s	remaining: 11m 27s
1205:	learn: 0.0158329	total: 1m 32s	remaining: 11m 15s
1252:	learn: 0.0142609	total: 1m 32s	remaining: 10m 46s
1200:	learn: 0.0153948	total: 1m 32s	remaining: 11m 18s
1123:	learn: 0.0172941	total: 1m 32s	remaining: 12m 9s
1184:	learn: 0.0159620	total: 1m 32s	remaining: 11m 27s
1206:	learn: 0.0158157	total: 1m 32s	remaining: 11m 14s
1201:	learn: 0.0153685	total: 1m 32s	remaining: 11m 18s
1253:	learn: 0.0142431	total: 1m 32s	remaining: 10m 46s
1124:	learn: 0.0172629	total: 1m 32s	remaining: 12m 8s
1185:	learn: 0.0159254	total: 1m 32s	remaining: 11m 26s
1207:	learn: 0.0158004	total: 1m 32s	remaining: 11m 14s
1254:	learn: 0.0142255	total: 1m 32s	remaining: 10m 45s
1202:	learn: 0.0153430	total: 1m 32s	remaining: 11m 17s
1186:	learn: 0.0158997	total: 1m 32s	remaining: 11m 26s
1125:	learn: 0.0172385	total: 1m 32s	remaining: 12m 8s
1208:	learn: 0.0157784	total: 1m 32s	remaining: 11m 14s
1255:	learn: 0.0141985	total: 1m 32s	remaining: 10m 45s
1203:	learn: 0.0153211	total: 1m 32s	remaining: 11m 17s
1187:	learn: 0.0158720	total: 1m 32s	remaining: 11m 25s
1256:	learn: 0.0141845	total: 1m 32s	remaining: 10m 44s
1188:	learn: 0.0158580	total: 1m 32s	remaining: 11m 25s
1209:	learn: 0.0157620	total: 1m 32s	remaining: 11m 13s
1126:	learn: 0.0172137	total: 1m 32s	remaining: 12m 8s
1204:	learn: 0.0153040	total: 1m 32s	remaining: 11m 16s
1257:	learn: 0.0141714	total: 1m 32s	remaining: 10m 44s
1205:	learn: 0.0152862	total: 1m 32s	remaining: 11m 16s
1189:	learn: 0.0158305	total: 1m 32s	remaining: 11m 25s
1127:	learn: 0.0171913	total: 1m 32s	remaining: 12m 7s
1258:	learn: 0.0141572	total: 1m 32s	remaining: 10m 43s
1210:	learn: 0.0157453	total: 1m 32s	remaining: 11m 13s
1259:	learn: 0.0141261	total: 1m 32s	remaining: 10m 43s
1190:	learn: 0.0158095	total: 1m 32s	remaining: 11m 24s
1128:	learn: 0.0171664	total: 1m 32s	remaining: 12m 7s
1206:	learn: 0.0152550	total: 1m 32s	remaining: 11m 16s
1260:	learn: 0.0140996	total: 1m 32s	remaining: 10m 43s
1211:	learn: 0.0157185	total: 1m 32s	remaining: 11m 13s
1191:	learn: 0.0157900	total: 1m 32s	remaining: 11m 24s
1207:	learn: 0.0152315	total: 1m 32s	remaining: 11m 15s
1261:	learn: 0.0140763	total: 1m 32s	remaining: 10m 42s
1129:	learn: 0.0171471	total: 1m 32s	remaining: 12m 6s
1208:	learn: 0.0152050	total: 1m 32s	remaining: 11m 15s
1212:	learn: 0.0157007	total: 1m 32s	remaining: 11m 12s
1192:	learn: 0.0157718	total: 1m 32s	remaining: 11m 23s
1262:	learn: 0.0140588	total: 1m 32s	remaining: 10m 42s
1130:	learn: 0.0171288	total: 1m 32s	remaining: 12m 6s
1263:	learn: 0.0140401	total: 1m 32s	remaining: 10m 41s
1209:	learn: 0.0151850	total: 1m 32s	remaining: 11m 14s
1193:	learn: 0.0157501	total: 1m 32s	remaining: 11m 23s
1213:	learn: 0.0156906	total: 1m 32s	remaining: 11m 12s
1210:	learn: 0.0151592	total: 1m 32s	remaining: 11m 14s
1264:	learn: 0.0140208	total: 1m 32s	remaining: 10m 41s
1131:	learn: 0.0170985	total: 1m 32s	remaining: 12m 5s
1194:	learn: 0.0157240	total: 1m 32s	remaining: 11m 23s
1211:	learn: 0.0151371	total: 1m 32s	remaining: 11m 13s
1214:	learn: 0.0156711	total: 1m 32s	remaining: 11m 12s
1195:	learn: 0.0156986	total: 1m 32s	remaining: 11m 22s
1265:	learn: 0.0139921	total: 1m 32s	remaining: 10m 41s
1132:	learn: 0.0170616	total: 1m 32s	remaining: 12m 5s
1212:	learn: 0.0151110	total: 1m 32s	remaining: 11m 13s
1196:	learn: 0.0156801	total: 1m 32s	remaining: 11m 22s
1133:	learn: 0.0170407	total: 1m 32s	remaining: 12m 4s
1266:	learn: 0.0139695	total: 1m 32s	remaining: 10m 40s
1213:	learn: 0.0150922	total: 1m 32s	remaining: 11m 12s
1215:	learn: 0.0156500	total: 1m 33s	remaining: 11m 11s
1214:	learn: 0.0150726	total: 1m 32s	remaining: 11m 12s
1197:	learn: 0.0156487	total: 1m 32s	remaining: 11m 21s
1267:	learn: 0.0139526	total: 1m 33s	remaining: 10m 40s
1134:	learn: 0.0170000	total: 1m 32s	remaining: 12m 4s
1215:	learn: 0.0150557	total: 1m 33s	remaining: 11m 11s
1216:	learn: 0.0156349	total: 1m 33s	remaining: 11m 11s
1198:	learn: 0.0156237	total: 1m 32s	remaining: 11m 21s
1268:	learn: 0.0139333	total: 1m 33s	remaining: 10m 40s
1216:	learn: 0.0150334	total: 1m 33s	remaining: 11m 11s
1135:	learn: 0.0169804	total: 1m 32s	remaining: 12m 4s
1199:	learn: 0.0156072	total: 1m 32s	remaining: 11m 20s
1269:	learn: 0.0139161	total: 1m 33s	remaining: 10m 39s
1217:	learn: 0.0156098	total: 1m 33s	remaining: 11m 11s
1200:	learn: 0.0155904	total: 1m 32s	remaining: 11m 20s
1136:	learn: 0.0169544	total: 1m 32s	remaining: 12m 3s
1217:	learn: 0.0150082	total: 1m 33s	remaining: 11m 11s
1270:	learn: 0.0138954	total: 1m 33s	remaining: 10m 39s
1218:	learn: 0.0155913	total: 1m 33s	remaining: 11m 10s
1137:	learn: 0.0169390	total: 1m 32s	remaining: 12m 3s
1201:	learn: 0.0155720	total: 1m 32s	remaining: 11m 19s
1271:	learn: 0.0138848	total: 1m 33s	remaining: 10m 38s
1219:	learn: 0.0155762	total: 1m 33s	remaining: 11m 10s
1218:	learn: 0.0149846	total: 1m 33s	remaining: 11m 10s
1272:	learn: 0.0138737	total: 1m 33s	remaining: 10m 38s
1220:	learn: 0.0155516	total: 1m 33s	remaining: 11m 9s
1202:	learn: 0.0155446	total: 1m 32s	remaining: 11m 19s
1138:	learn: 0.0169137	total: 1m 32s	remaining: 12m 2s
1219:	learn: 0.0149692	total: 1m 33s	remaining: 11m 10s
1273:	learn: 0.0138532	total: 1m 33s	remaining: 10m 38s
1221:	learn: 0.0155348	total: 1m 33s	remaining: 11m 9s
1203:	learn: 0.0155255	total: 1m 32s	remaining: 11m 19s
1220:	learn: 0.0149482	total: 1m 33s	remaining: 11m 10s
1139:	learn: 0.0168781	total: 1m 32s	remaining: 12m 2s
1274:	learn: 0.0138336	total: 1m 33s	remaining: 10m 37s
1204:	learn: 0.0155054	total: 1m 32s	remaining: 11m 18s
1222:	learn: 0.0155170	total: 1m 33s	remaining: 11m 9s
1275:	learn: 0.0138148	total: 1m 33s	remaining: 10m 37s
1205:	learn: 0.0154833	total: 1m 33s	remaining: 11m 18s
1140:	learn: 0.0168390	total: 1m 32s	remaining: 12m 1s
1221:	learn: 0.0149229	total: 1m 33s	remaining: 11m 9s
1276:	learn: 0.0137943	total: 1m 33s	remaining: 10m 36s
1223:	learn: 0.0154937	total: 1m 33s	remaining: 11m 8s
1206:	learn: 0.0154555	total: 1m 33s	remaining: 11m 17s
1222:	learn: 0.0149103	total: 1m 33s	remaining: 11m 9s
1141:	learn: 0.0168002	total: 1m 33s	remaining: 12m 1s
1207:	learn: 0.0154391	total: 1m 33s	remaining: 11m 17s
1277:	learn: 0.0137756	total: 1m 33s	remaining: 10m 36s
1224:	learn: 0.0154793	total: 1m 33s	remaining: 11m 8s
1142:	learn: 0.0167769	total: 1m 33s	remaining: 12m
1223:	learn: 0.0148898	total: 1m 33s	remaining: 11m 8s
1278:	learn: 0.0137569	total: 1m 33s	remaining: 10m 36s
1208:	learn: 0.0154196	total: 1m 33s	remaining: 11m 16s
1143:	learn: 0.0167484	total: 1m 33s	remaining: 12m
1225:	learn: 0.0154531	total: 1m 33s	remaining: 11m 8s
1224:	learn: 0.0148638	total: 1m 33s	remaining: 11m 8s
1209:	learn: 0.0153915	total: 1m 33s	remaining: 11m 16s
1144:	learn: 0.0167248	total: 1m 33s	remaining: 11m 59s
1279:	learn: 0.0137387	total: 1m 33s	remaining: 10m 35s
1226:	learn: 0.0154324	total: 1m 33s	remaining: 11m 7s
1210:	learn: 0.0153720	total: 1m 33s	remaining: 11m 16s
1280:	learn: 0.0137182	total: 1m 33s	remaining: 10m 35s
1145:	learn: 0.0167043	total: 1m 33s	remaining: 11m 59s
1225:	learn: 0.0148429	total: 1m 33s	remaining: 11m 8s
1227:	learn: 0.0154136	total: 1m 33s	remaining: 11m 7s
1211:	learn: 0.0153531	total: 1m 33s	remaining: 11m 15s
1146:	learn: 0.0166724	total: 1m 33s	remaining: 11m 58s
1281:	learn: 0.0137017	total: 1m 33s	remaining: 10m 35s
1226:	learn: 0.0148283	total: 1m 33s	remaining: 11m 7s
1228:	learn: 0.0153911	total: 1m 33s	remaining: 11m 6s
1212:	learn: 0.0153332	total: 1m 33s	remaining: 11m 15s
1147:	learn: 0.0166537	total: 1m 33s	remaining: 11m 58s
1282:	learn: 0.0136790	total: 1m 33s	remaining: 10m 34s
1229:	learn: 0.0153790	total: 1m 33s	remaining: 11m 6s
1213:	learn: 0.0153229	total: 1m 33s	remaining: 11m 14s
1227:	learn: 0.0148080	total: 1m 33s	remaining: 11m 7s
1148:	learn: 0.0166343	total: 1m 33s	remaining: 11m 57s
1230:	learn: 0.0153646	total: 1m 33s	remaining: 11m 6s
1283:	learn: 0.0136628	total: 1m 33s	remaining: 10m 34s
1214:	learn: 0.0153022	total: 1m 33s	remaining: 11m 14s
1228:	learn: 0.0147903	total: 1m 33s	remaining: 11m 7s
1231:	learn: 0.0153390	total: 1m 33s	remaining: 11m 5s
1284:	learn: 0.0136428	total: 1m 33s	remaining: 10m 34s
1229:	learn: 0.0147634	total: 1m 33s	remaining: 11m 6s
1149:	learn: 0.0166106	total: 1m 33s	remaining: 11m 57s
1215:	learn: 0.0152769	total: 1m 33s	remaining: 11m 13s
1232:	learn: 0.0153272	total: 1m 33s	remaining: 11m 5s
1285:	learn: 0.0136273	total: 1m 33s	remaining: 10m 33s
1216:	learn: 0.0152585	total: 1m 33s	remaining: 11m 13s
1150:	learn: 0.0165857	total: 1m 33s	remaining: 11m 57s
1230:	learn: 0.0147369	total: 1m 33s	remaining: 11m 6s
1233:	learn: 0.0153053	total: 1m 33s	remaining: 11m 4s
1217:	learn: 0.0152264	total: 1m 33s	remaining: 11m 13s
1286:	learn: 0.0136081	total: 1m 33s	remaining: 10m 33s
1234:	learn: 0.0152800	total: 1m 33s	remaining: 11m 4s
1218:	learn: 0.0151970	total: 1m 33s	remaining: 11m 12s
1231:	learn: 0.0147219	total: 1m 33s	remaining: 11m 5s
1235:	learn: 0.0152560	total: 1m 33s	remaining: 11m 3s
1151:	learn: 0.0165662	total: 1m 33s	remaining: 11m 56s
1287:	learn: 0.0135899	total: 1m 33s	remaining: 10m 33s
1236:	learn: 0.0152408	total: 1m 33s	remaining: 11m 3s
1219:	learn: 0.0151828	total: 1m 33s	remaining: 11m 12s
1232:	learn: 0.0147023	total: 1m 33s	remaining: 11m 5s
1152:	learn: 0.0165409	total: 1m 33s	remaining: 11m 56s
1288:	learn: 0.0135783	total: 1m 33s	remaining: 10m 32s
1237:	learn: 0.0152241	total: 1m 33s	remaining: 11m 2s
1220:	learn: 0.0151514	total: 1m 33s	remaining: 11m 11s
1289:	learn: 0.0135616	total: 1m 33s	remaining: 10m 32s
1233:	learn: 0.0146770	total: 1m 33s	remaining: 11m 5s
1221:	learn: 0.0151327	total: 1m 33s	remaining: 11m 11s
1153:	learn: 0.0165217	total: 1m 33s	remaining: 11m 56s
1238:	learn: 0.0152023	total: 1m 33s	remaining: 11m 2s
1290:	learn: 0.0135449	total: 1m 33s	remaining: 10m 31s
1222:	learn: 0.0151003	total: 1m 33s	remaining: 11m 10s
1234:	learn: 0.0146606	total: 1m 33s	remaining: 11m 4s
1239:	learn: 0.0151842	total: 1m 33s	remaining: 11m 2s
1291:	learn: 0.0135330	total: 1m 33s	remaining: 10m 31s
1223:	learn: 0.0150815	total: 1m 33s	remaining: 11m 10s
1154:	learn: 0.0164967	total: 1m 33s	remaining: 11m 55s
1235:	learn: 0.0146413	total: 1m 33s	remaining: 11m 4s
1292:	learn: 0.0135177	total: 1m 33s	remaining: 10m 31s
1240:	learn: 0.0151633	total: 1m 33s	remaining: 11m 1s
1224:	learn: 0.0150554	total: 1m 33s	remaining: 11m 9s
1293:	learn: 0.0134966	total: 1m 33s	remaining: 10m 30s
1155:	learn: 0.0164718	total: 1m 33s	remaining: 11m 55s
1236:	learn: 0.0146232	total: 1m 33s	remaining: 11m 4s
1241:	learn: 0.0151408	total: 1m 33s	remaining: 11m 1s
1294:	learn: 0.0134815	total: 1m 33s	remaining: 10m 30s
1225:	learn: 0.0150225	total: 1m 33s	remaining: 11m 9s
1156:	learn: 0.0164357	total: 1m 33s	remaining: 11m 54s
1242:	learn: 0.0151285	total: 1m 33s	remaining: 11m 1s
1237:	learn: 0.0146003	total: 1m 33s	remaining: 11m 3s
1243:	learn: 0.0151052	total: 1m 33s	remaining: 11m
1226:	learn: 0.0150069	total: 1m 33s	remaining: 11m 9s
1157:	learn: 0.0164080	total: 1m 33s	remaining: 11m 54s
1295:	learn: 0.0134636	total: 1m 33s	remaining: 10m 30s
1238:	learn: 0.0145843	total: 1m 33s	remaining: 11m 3s
1244:	learn: 0.0150916	total: 1m 33s	remaining: 11m
1158:	learn: 0.0163854	total: 1m 33s	remaining: 11m 53s
1227:	learn: 0.0149897	total: 1m 33s	remaining: 11m 8s
1296:	learn: 0.0134480	total: 1m 33s	remaining: 10m 29s
1239:	learn: 0.0145617	total: 1m 33s	remaining: 11m 3s
1245:	learn: 0.0150671	total: 1m 33s	remaining: 10m 59s
1240:	learn: 0.0145423	total: 1m 33s	remaining: 11m 2s
1159:	learn: 0.0163629	total: 1m 33s	remaining: 11m 53s
1297:	learn: 0.0134275	total: 1m 33s	remaining: 10m 29s
1228:	learn: 0.0149732	total: 1m 33s	remaining: 11m 8s
1241:	learn: 0.0145281	total: 1m 33s	remaining: 11m 2s
1160:	learn: 0.0163415	total: 1m 33s	remaining: 11m 53s
1246:	learn: 0.0150463	total: 1m 33s	remaining: 10m 59s
1298:	learn: 0.0134170	total: 1m 33s	remaining: 10m 29s
1247:	learn: 0.0150213	total: 1m 33s	remaining: 10m 59s
1242:	learn: 0.0145115	total: 1m 33s	remaining: 11m 1s
1161:	learn: 0.0163256	total: 1m 33s	remaining: 11m 52s
1229:	learn: 0.0149497	total: 1m 33s	remaining: 11m 8s
1299:	learn: 0.0134021	total: 1m 33s	remaining: 10m 28s
1162:	learn: 0.0162897	total: 1m 33s	remaining: 11m 52s
1243:	learn: 0.0144880	total: 1m 33s	remaining: 11m 1s
1248:	learn: 0.0150003	total: 1m 34s	remaining: 10m 58s
1230:	learn: 0.0149316	total: 1m 33s	remaining: 11m 7s
1249:	learn: 0.0149846	total: 1m 34s	remaining: 10m 58s
1163:	learn: 0.0162675	total: 1m 33s	remaining: 11m 51s
1300:	learn: 0.0133805	total: 1m 33s	remaining: 10m 28s
1231:	learn: 0.0149138	total: 1m 33s	remaining: 11m 7s
1244:	learn: 0.0144740	total: 1m 34s	remaining: 11m 1s
1250:	learn: 0.0149683	total: 1m 34s	remaining: 10m 57s
1164:	learn: 0.0162528	total: 1m 33s	remaining: 11m 51s
1232:	learn: 0.0148926	total: 1m 33s	remaining: 11m 7s
1301:	learn: 0.0133665	total: 1m 34s	remaining: 10m 28s
1251:	learn: 0.0149518	total: 1m 34s	remaining: 10m 57s
1165:	learn: 0.0162209	total: 1m 33s	remaining: 11m 50s
1233:	learn: 0.0148764	total: 1m 33s	remaining: 11m 6s
1245:	learn: 0.0144584	total: 1m 34s	remaining: 11m
1302:	learn: 0.0133491	total: 1m 34s	remaining: 10m 27s
1252:	learn: 0.0149402	total: 1m 34s	remaining: 10m 56s
1234:	learn: 0.0148609	total: 1m 33s	remaining: 11m 6s
1166:	learn: 0.0161967	total: 1m 33s	remaining: 11m 50s
1253:	learn: 0.0149314	total: 1m 34s	remaining: 10m 56s
1246:	learn: 0.0144378	total: 1m 34s	remaining: 11m
1303:	learn: 0.0133328	total: 1m 34s	remaining: 10m 27s
1235:	learn: 0.0148463	total: 1m 33s	remaining: 11m 5s
1254:	learn: 0.0149187	total: 1m 34s	remaining: 10m 56s
1167:	learn: 0.0161754	total: 1m 33s	remaining: 11m 49s
1236:	learn: 0.0148277	total: 1m 33s	remaining: 11m 5s
1304:	learn: 0.0133159	total: 1m 34s	remaining: 10m 27s
1255:	learn: 0.0149012	total: 1m 34s	remaining: 10m 55s
1247:	learn: 0.0144226	total: 1m 34s	remaining: 11m
1237:	learn: 0.0148127	total: 1m 33s	remaining: 11m 4s
1168:	learn: 0.0161492	total: 1m 33s	remaining: 11m 49s
1305:	learn: 0.0132986	total: 1m 34s	remaining: 10m 26s
1248:	learn: 0.0143972	total: 1m 34s	remaining: 10m 59s
1256:	learn: 0.0148842	total: 1m 34s	remaining: 10m 55s
1238:	learn: 0.0147990	total: 1m 33s	remaining: 11m 4s
1169:	learn: 0.0161257	total: 1m 33s	remaining: 11m 48s
1239:	learn: 0.0147755	total: 1m 33s	remaining: 11m 3s
1306:	learn: 0.0132879	total: 1m 34s	remaining: 10m 26s
1249:	learn: 0.0143832	total: 1m 34s	remaining: 10m 59s
1257:	learn: 0.0148700	total: 1m 34s	remaining: 10m 54s
1240:	learn: 0.0147611	total: 1m 34s	remaining: 11m 3s
1170:	learn: 0.0160999	total: 1m 33s	remaining: 11m 48s
1250:	learn: 0.0143686	total: 1m 34s	remaining: 10m 58s
1307:	learn: 0.0132686	total: 1m 34s	remaining: 10m 26s
1241:	learn: 0.0147359	total: 1m 34s	remaining: 11m 3s
1258:	learn: 0.0148465	total: 1m 34s	remaining: 10m 54s
1242:	learn: 0.0147198	total: 1m 34s	remaining: 11m 2s
1171:	learn: 0.0160739	total: 1m 34s	remaining: 11m 48s
1251:	learn: 0.0143534	total: 1m 34s	remaining: 10m 58s
1308:	learn: 0.0132497	total: 1m 34s	remaining: 10m 25s
1243:	learn: 0.0146920	total: 1m 34s	remaining: 11m 2s
1172:	learn: 0.0160506	total: 1m 34s	remaining: 11m 47s
1259:	learn: 0.0148273	total: 1m 34s	remaining: 10m 54s
1244:	learn: 0.0146734	total: 1m 34s	remaining: 11m 1s
1252:	learn: 0.0143261	total: 1m 34s	remaining: 10m 58s
1309:	learn: 0.0132352	total: 1m 34s	remaining: 10m 25s
1173:	learn: 0.0160201	total: 1m 34s	remaining: 11m 47s
1260:	learn: 0.0148149	total: 1m 34s	remaining: 10m 53s
1253:	learn: 0.0143072	total: 1m 34s	remaining: 10m 57s
1245:	learn: 0.0146599	total: 1m 34s	remaining: 11m 1s
1310:	learn: 0.0132206	total: 1m 34s	remaining: 10m 25s
1246:	learn: 0.0146401	total: 1m 34s	remaining: 11m
1261:	learn: 0.0147950	total: 1m 34s	remaining: 10m 53s
1311:	learn: 0.0132080	total: 1m 34s	remaining: 10m 24s
1254:	learn: 0.0142798	total: 1m 34s	remaining: 10m 57s
1174:	learn: 0.0160006	total: 1m 34s	remaining: 11m 46s
1247:	learn: 0.0146133	total: 1m 34s	remaining: 11m
1312:	learn: 0.0131920	total: 1m 34s	remaining: 10m 24s
1255:	learn: 0.0142558	total: 1m 34s	remaining: 10m 57s
1262:	learn: 0.0147814	total: 1m 34s	remaining: 10m 53s
1248:	learn: 0.0145972	total: 1m 34s	remaining: 10m 59s
1175:	learn: 0.0159809	total: 1m 34s	remaining: 11m 46s
1313:	learn: 0.0131777	total: 1m 34s	remaining: 10m 24s
1263:	learn: 0.0147683	total: 1m 34s	remaining: 10m 52s
1249:	learn: 0.0145822	total: 1m 34s	remaining: 10m 59s
1256:	learn: 0.0142374	total: 1m 34s	remaining: 10m 56s
1314:	learn: 0.0131538	total: 1m 34s	remaining: 10m 23s
1176:	learn: 0.0159534	total: 1m 34s	remaining: 11m 46s
1250:	learn: 0.0145614	total: 1m 34s	remaining: 10m 59s
1264:	learn: 0.0147397	total: 1m 34s	remaining: 10m 52s
1315:	learn: 0.0131338	total: 1m 34s	remaining: 10m 23s
1257:	learn: 0.0142177	total: 1m 34s	remaining: 10m 56s
1177:	learn: 0.0159284	total: 1m 34s	remaining: 11m 45s
1265:	learn: 0.0147163	total: 1m 34s	remaining: 10m 52s
1251:	learn: 0.0145454	total: 1m 34s	remaining: 10m 58s
1258:	learn: 0.0142028	total: 1m 34s	remaining: 10m 56s
1316:	learn: 0.0131105	total: 1m 34s	remaining: 10m 23s
1178:	learn: 0.0159062	total: 1m 34s	remaining: 11m 45s
1252:	learn: 0.0145237	total: 1m 34s	remaining: 10m 58s
1266:	learn: 0.0146983	total: 1m 34s	remaining: 10m 51s
1259:	learn: 0.0141856	total: 1m 34s	remaining: 10m 55s
1179:	learn: 0.0158778	total: 1m 34s	remaining: 11m 44s
1317:	learn: 0.0130942	total: 1m 34s	remaining: 10m 22s
1253:	learn: 0.0145059	total: 1m 34s	remaining: 10m 57s
1267:	learn: 0.0146752	total: 1m 34s	remaining: 10m 51s
1260:	learn: 0.0141729	total: 1m 34s	remaining: 10m 55s
1318:	learn: 0.0130808	total: 1m 34s	remaining: 10m 22s
1180:	learn: 0.0158520	total: 1m 34s	remaining: 11m 44s
1254:	learn: 0.0144910	total: 1m 34s	remaining: 10m 57s
1261:	learn: 0.0141546	total: 1m 34s	remaining: 10m 54s
1268:	learn: 0.0146534	total: 1m 34s	remaining: 10m 51s

[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:  6.2min finished

534:	learn: 0.0508611	total: 1m 3s	remaining: 18m 41s
523:	learn: 0.0466801	total: 1m 3s	remaining: 19m 7s
537:	learn: 0.0497952	total: 1m 3s	remaining: 18m 38s
519:	learn: 0.0514384	total: 1m 3s	remaining: 19m 18s
535:	learn: 0.0507072	total: 1m 3s	remaining: 18m 41s
490:	learn: 0.0573397	total: 1m 3s	remaining: 20m 31s
524:	learn: 0.0465722	total: 1m 3s	remaining: 19m 6s
538:	learn: 0.0496876	total: 1m 3s	remaining: 18m 38s
520:	learn: 0.0513312	total: 1m 3s	remaining: 19m 17s
536:	learn: 0.0505880	total: 1m 3s	remaining: 18m 40s
525:	learn: 0.0464909	total: 1m 3s	remaining: 19m 6s
491:	learn: 0.0572037	total: 1m 3s	remaining: 20m 31s
521:	learn: 0.0512169	total: 1m 3s	remaining: 19m 16s
539:	learn: 0.0495917	total: 1m 3s	remaining: 18m 38s
537:	learn: 0.0505104	total: 1m 3s	remaining: 18m 40s
526:	learn: 0.0463932	total: 1m 3s	remaining: 19m 5s
492:	learn: 0.0570826	total: 1m 3s	remaining: 20m 31s
540:	learn: 0.0494194	total: 1m 3s	remaining: 18m 37s
538:	learn: 0.0503898	total: 1m 3s	remaining: 18m 39s
522:	learn: 0.0511190	total: 1m 3s	remaining: 19m 16s
527:	learn: 0.0462582	total: 1m 3s	remaining: 19m 4s
541:	learn: 0.0492567	total: 1m 4s	remaining: 18m 37s
493:	learn: 0.0569708	total: 1m 3s	remaining: 20m 30s
539:	learn: 0.0502942	total: 1m 3s	remaining: 18m 39s
523:	learn: 0.0509325	total: 1m 3s	remaining: 19m 16s
528:	learn: 0.0461810	total: 1m 3s	remaining: 19m 4s
529:	learn: 0.0460539	total: 1m 3s	remaining: 19m 3s
494:	learn: 0.0568080	total: 1m 4s	remaining: 20m 30s
540:	learn: 0.0501780	total: 1m 3s	remaining: 18m 38s
542:	learn: 0.0491869	total: 1m 4s	remaining: 18m 37s
524:	learn: 0.0508111	total: 1m 4s	remaining: 19m 16s
530:	learn: 0.0459587	total: 1m 4s	remaining: 19m 2s
541:	learn: 0.0500077	total: 1m 4s	remaining: 18m 37s
543:	learn: 0.0490383	total: 1m 4s	remaining: 18m 36s
495:	learn: 0.0566870	total: 1m 4s	remaining: 20m 29s
531:	learn: 0.0458278	total: 1m 4s	remaining: 19m 1s
542:	learn: 0.0499136	total: 1m 4s	remaining: 18m 37s
525:	learn: 0.0507148	total: 1m 4s	remaining: 19m 16s
544:	learn: 0.0489259	total: 1m 4s	remaining: 18m 35s
496:	learn: 0.0565353	total: 1m 4s	remaining: 20m 28s
543:	learn: 0.0498452	total: 1m 4s	remaining: 18m 36s
532:	learn: 0.0456663	total: 1m 4s	remaining: 19m 1s
545:	learn: 0.0488080	total: 1m 4s	remaining: 18m 35s
497:	learn: 0.0563095	total: 1m 4s	remaining: 20m 28s
526:	learn: 0.0505939	total: 1m 4s	remaining: 19m 16s
544:	learn: 0.0497498	total: 1m 4s	remaining: 18m 35s
533:	learn: 0.0455623	total: 1m 4s	remaining: 19m 1s
546:	learn: 0.0487313	total: 1m 4s	remaining: 18m 35s
498:	learn: 0.0561884	total: 1m 4s	remaining: 20m 27s
545:	learn: 0.0496188	total: 1m 4s	remaining: 18m 34s
527:	learn: 0.0504585	total: 1m 4s	remaining: 19m 16s
534:	learn: 0.0454739	total: 1m 4s	remaining: 19m
547:	learn: 0.0486062	total: 1m 4s	remaining: 18m 34s
499:	learn: 0.0560807	total: 1m 4s	remaining: 20m 27s
546:	learn: 0.0495371	total: 1m 4s	remaining: 18m 34s
528:	learn: 0.0502944	total: 1m 4s	remaining: 19m 15s
548:	learn: 0.0485092	total: 1m 4s	remaining: 18m 34s
500:	learn: 0.0559283	total: 1m 4s	remaining: 20m 25s
535:	learn: 0.0453915	total: 1m 4s	remaining: 19m
529:	learn: 0.0501567	total: 1m 4s	remaining: 19m 15s
547:	learn: 0.0494596	total: 1m 4s	remaining: 18m 34s
549:	learn: 0.0483800	total: 1m 4s	remaining: 18m 33s
536:	learn: 0.0452541	total: 1m 4s	remaining: 18m 59s
501:	learn: 0.0558055	total: 1m 4s	remaining: 20m 25s
548:	learn: 0.0493059	total: 1m 4s	remaining: 18m 34s
530:	learn: 0.0500530	total: 1m 4s	remaining: 19m 14s
550:	learn: 0.0483285	total: 1m 4s	remaining: 18m 32s
537:	learn: 0.0451700	total: 1m 4s	remaining: 18m 59s
502:	learn: 0.0556791	total: 1m 4s	remaining: 20m 25s
551:	learn: 0.0482216	total: 1m 4s	remaining: 18m 31s
549:	learn: 0.0491873	total: 1m 4s	remaining: 18m 33s
538:	learn: 0.0451038	total: 1m 4s	remaining: 18m 58s
503:	learn: 0.0555312	total: 1m 4s	remaining: 20m 23s
531:	learn: 0.0498696	total: 1m 4s	remaining: 19m 15s
552:	learn: 0.0481447	total: 1m 5s	remaining: 18m 31s
550:	learn: 0.0490248	total: 1m 4s	remaining: 18m 33s
504:	learn: 0.0554185	total: 1m 5s	remaining: 20m 23s
539:	learn: 0.0450475	total: 1m 4s	remaining: 18m 58s
553:	learn: 0.0480357	total: 1m 5s	remaining: 18m 30s
532:	learn: 0.0497445	total: 1m 5s	remaining: 19m 15s
551:	learn: 0.0489312	total: 1m 5s	remaining: 18m 32s
505:	learn: 0.0552934	total: 1m 5s	remaining: 20m 22s
540:	learn: 0.0449456	total: 1m 5s	remaining: 18m 57s
554:	learn: 0.0479604	total: 1m 5s	remaining: 18m 30s
533:	learn: 0.0496057	total: 1m 5s	remaining: 19m 15s
552:	learn: 0.0488333	total: 1m 5s	remaining: 18m 32s
541:	learn: 0.0448468	total: 1m 5s	remaining: 18m 57s
506:	learn: 0.0551540	total: 1m 5s	remaining: 20m 21s
555:	learn: 0.0478164	total: 1m 5s	remaining: 18m 30s
542:	learn: 0.0447826	total: 1m 5s	remaining: 18m 56s
534:	learn: 0.0494389	total: 1m 5s	remaining: 19m 14s
553:	learn: 0.0486857	total: 1m 5s	remaining: 18m 32s
507:	learn: 0.0550724	total: 1m 5s	remaining: 20m 20s
535:	learn: 0.0492801	total: 1m 5s	remaining: 19m 13s
556:	learn: 0.0477018	total: 1m 5s	remaining: 18m 29s
543:	learn: 0.0446704	total: 1m 5s	remaining: 18m 55s
554:	learn: 0.0486108	total: 1m 5s	remaining: 18m 31s
536:	learn: 0.0491733	total: 1m 5s	remaining: 19m 13s
557:	learn: 0.0476269	total: 1m 5s	remaining: 18m 29s
508:	learn: 0.0549636	total: 1m 5s	remaining: 20m 21s
544:	learn: 0.0445937	total: 1m 5s	remaining: 18m 55s
555:	learn: 0.0485189	total: 1m 5s	remaining: 18m 31s
558:	learn: 0.0475291	total: 1m 5s	remaining: 18m 28s
545:	learn: 0.0445137	total: 1m 5s	remaining: 18m 54s
537:	learn: 0.0490591	total: 1m 5s	remaining: 19m 13s
509:	learn: 0.0548324	total: 1m 5s	remaining: 20m 20s
556:	learn: 0.0484498	total: 1m 5s	remaining: 18m 31s
546:	learn: 0.0444348	total: 1m 5s	remaining: 18m 53s
559:	learn: 0.0474185	total: 1m 5s	remaining: 18m 28s
538:	learn: 0.0489493	total: 1m 5s	remaining: 19m 12s
510:	learn: 0.0546963	total: 1m 5s	remaining: 20m 20s
547:	learn: 0.0443607	total: 1m 5s	remaining: 18m 52s
557:	learn: 0.0483325	total: 1m 5s	remaining: 18m 31s
560:	learn: 0.0473126	total: 1m 5s	remaining: 18m 28s
558:	learn: 0.0482451	total: 1m 5s	remaining: 18m 30s
539:	learn: 0.0488717	total: 1m 5s	remaining: 19m 12s
511:	learn: 0.0546202	total: 1m 5s	remaining: 20m 20s
548:	learn: 0.0442712	total: 1m 5s	remaining: 18m 52s
561:	learn: 0.0472183	total: 1m 5s	remaining: 18m 27s
540:	learn: 0.0487530	total: 1m 5s	remaining: 19m 11s
559:	learn: 0.0481023	total: 1m 5s	remaining: 18m 29s
549:	learn: 0.0441266	total: 1m 5s	remaining: 18m 51s
512:	learn: 0.0544895	total: 1m 5s	remaining: 20m 19s
541:	learn: 0.0485652	total: 1m 5s	remaining: 19m 10s
562:	learn: 0.0471207	total: 1m 6s	remaining: 18m 27s
560:	learn: 0.0480372	total: 1m 5s	remaining: 18m 29s
513:	learn: 0.0543822	total: 1m 6s	remaining: 20m 18s
550:	learn: 0.0440019	total: 1m 5s	remaining: 18m 51s
542:	learn: 0.0484762	total: 1m 6s	remaining: 19m 10s
563:	learn: 0.0470413	total: 1m 6s	remaining: 18m 27s
561:	learn: 0.0479088	total: 1m 6s	remaining: 18m 29s
514:	learn: 0.0542847	total: 1m 6s	remaining: 20m 18s
543:	learn: 0.0483492	total: 1m 6s	remaining: 19m 9s
551:	learn: 0.0439017	total: 1m 6s	remaining: 18m 51s
564:	learn: 0.0469785	total: 1m 6s	remaining: 18m 26s
562:	learn: 0.0478038	total: 1m 6s	remaining: 18m 28s
515:	learn: 0.0541458	total: 1m 6s	remaining: 20m 17s
544:	learn: 0.0482442	total: 1m 6s	remaining: 19m 9s
552:	learn: 0.0437911	total: 1m 6s	remaining: 18m 51s
565:	learn: 0.0468730	total: 1m 6s	remaining: 18m 25s
563:	learn: 0.0477070	total: 1m 6s	remaining: 18m 28s
516:	learn: 0.0540028	total: 1m 6s	remaining: 20m 17s
553:	learn: 0.0437138	total: 1m 6s	remaining: 18m 50s
566:	learn: 0.0467472	total: 1m 6s	remaining: 18m 25s
545:	learn: 0.0481167	total: 1m 6s	remaining: 19m 8s
564:	learn: 0.0476179	total: 1m 6s	remaining: 18m 28s
517:	learn: 0.0538800	total: 1m 6s	remaining: 20m 16s
554:	learn: 0.0436494	total: 1m 6s	remaining: 18m 49s
567:	learn: 0.0466515	total: 1m 6s	remaining: 18m 24s
546:	learn: 0.0480313	total: 1m 6s	remaining: 19m 8s
565:	learn: 0.0475009	total: 1m 6s	remaining: 18m 27s
518:	learn: 0.0537253	total: 1m 6s	remaining: 20m 15s
555:	learn: 0.0435321	total: 1m 6s	remaining: 18m 49s
568:	learn: 0.0465345	total: 1m 6s	remaining: 18m 24s
547:	learn: 0.0479287	total: 1m 6s	remaining: 19m 8s
566:	learn: 0.0474193	total: 1m 6s	remaining: 18m 27s
519:	learn: 0.0535791	total: 1m 6s	remaining: 20m 15s
556:	learn: 0.0434293	total: 1m 6s	remaining: 18m 49s
569:	learn: 0.0464150	total: 1m 6s	remaining: 18m 24s
548:	learn: 0.0478070	total: 1m 6s	remaining: 19m 7s
567:	learn: 0.0473406	total: 1m 6s	remaining: 18m 26s
557:	learn: 0.0433399	total: 1m 6s	remaining: 18m 48s
520:	learn: 0.0534346	total: 1m 6s	remaining: 20m 15s
570:	learn: 0.0462701	total: 1m 6s	remaining: 18m 24s
549:	learn: 0.0477255	total: 1m 6s	remaining: 19m 7s
568:	learn: 0.0472090	total: 1m 6s	remaining: 18m 26s
558:	learn: 0.0432391	total: 1m 6s	remaining: 18m 47s
571:	learn: 0.0461611	total: 1m 6s	remaining: 18m 23s
521:	learn: 0.0533287	total: 1m 6s	remaining: 20m 15s
559:	learn: 0.0431311	total: 1m 6s	remaining: 18m 47s
550:	learn: 0.0476267	total: 1m 6s	remaining: 19m 7s
569:	learn: 0.0471087	total: 1m 6s	remaining: 18m 26s
572:	learn: 0.0460695	total: 1m 7s	remaining: 18m 22s
522:	learn: 0.0532414	total: 1m 7s	remaining: 20m 14s
560:	learn: 0.0430409	total: 1m 6s	remaining: 18m 46s
551:	learn: 0.0475678	total: 1m 7s	remaining: 19m 6s
570:	learn: 0.0469896	total: 1m 6s	remaining: 18m 25s
573:	learn: 0.0459591	total: 1m 7s	remaining: 18m 22s
561:	learn: 0.0429511	total: 1m 7s	remaining: 18m 45s
552:	learn: 0.0474801	total: 1m 7s	remaining: 19m 5s
523:	learn: 0.0531386	total: 1m 7s	remaining: 20m 14s
571:	learn: 0.0468836	total: 1m 7s	remaining: 18m 25s
574:	learn: 0.0458632	total: 1m 7s	remaining: 18m 21s
562:	learn: 0.0428431	total: 1m 7s	remaining: 18m 45s
553:	learn: 0.0473600	total: 1m 7s	remaining: 19m 5s
575:	learn: 0.0456809	total: 1m 7s	remaining: 18m 21s
524:	learn: 0.0529970	total: 1m 7s	remaining: 20m 13s
572:	learn: 0.0467635	total: 1m 7s	remaining: 18m 25s
554:	learn: 0.0472851	total: 1m 7s	remaining: 19m 5s
576:	learn: 0.0455878	total: 1m 7s	remaining: 18m 20s
563:	learn: 0.0427412	total: 1m 7s	remaining: 18m 45s
573:	learn: 0.0466845	total: 1m 7s	remaining: 18m 24s
525:	learn: 0.0528187	total: 1m 7s	remaining: 20m 13s
555:	learn: 0.0471868	total: 1m 7s	remaining: 19m 4s
577:	learn: 0.0454705	total: 1m 7s	remaining: 18m 19s
564:	learn: 0.0426060	total: 1m 7s	remaining: 18m 44s
556:	learn: 0.0471169	total: 1m 7s	remaining: 19m 3s
574:	learn: 0.0465763	total: 1m 7s	remaining: 18m 24s
526:	learn: 0.0526726	total: 1m 7s	remaining: 20m 13s
565:	learn: 0.0424835	total: 1m 7s	remaining: 18m 44s
578:	learn: 0.0453537	total: 1m 7s	remaining: 18m 19s
557:	learn: 0.0469921	total: 1m 7s	remaining: 19m 2s
527:	learn: 0.0525401	total: 1m 7s	remaining: 20m 12s
575:	learn: 0.0464903	total: 1m 7s	remaining: 18m 24s
566:	learn: 0.0423625	total: 1m 7s	remaining: 18m 43s
579:	learn: 0.0452189	total: 1m 7s	remaining: 18m 19s
558:	learn: 0.0468973	total: 1m 7s	remaining: 19m 1s
528:	learn: 0.0524144	total: 1m 7s	remaining: 20m 11s
567:	learn: 0.0422491	total: 1m 7s	remaining: 18m 42s
576:	learn: 0.0464001	total: 1m 7s	remaining: 18m 24s
580:	learn: 0.0451195	total: 1m 7s	remaining: 18m 19s
559:	learn: 0.0467967	total: 1m 7s	remaining: 19m 1s
568:	learn: 0.0421673	total: 1m 7s	remaining: 18m 42s
577:	learn: 0.0463211	total: 1m 7s	remaining: 18m 23s
529:	learn: 0.0523399	total: 1m 7s	remaining: 20m 11s
581:	learn: 0.0450422	total: 1m 7s	remaining: 18m 18s
569:	learn: 0.0420616	total: 1m 7s	remaining: 18m 41s
560:	learn: 0.0466876	total: 1m 7s	remaining: 19m 1s
578:	learn: 0.0462020	total: 1m 7s	remaining: 18m 23s
582:	learn: 0.0449122	total: 1m 7s	remaining: 18m 18s
530:	learn: 0.0522469	total: 1m 7s	remaining: 20m 11s
570:	learn: 0.0419675	total: 1m 7s	remaining: 18m 41s
561:	learn: 0.0465985	total: 1m 7s	remaining: 19m
579:	learn: 0.0461228	total: 1m 7s	remaining: 18m 22s
583:	learn: 0.0448274	total: 1m 8s	remaining: 18m 17s
571:	learn: 0.0418456	total: 1m 7s	remaining: 18m 40s
562:	learn: 0.0465140	total: 1m 8s	remaining: 19m
580:	learn: 0.0460593	total: 1m 8s	remaining: 18m 22s
531:	learn: 0.0520792	total: 1m 8s	remaining: 20m 12s
584:	learn: 0.0447405	total: 1m 8s	remaining: 18m 17s
572:	learn: 0.0417627	total: 1m 8s	remaining: 18m 39s
581:	learn: 0.0459459	total: 1m 8s	remaining: 18m 21s
563:	learn: 0.0463832	total: 1m 8s	remaining: 19m
585:	learn: 0.0446242	total: 1m 8s	remaining: 18m 16s
573:	learn: 0.0416801	total: 1m 8s	remaining: 18m 39s
532:	learn: 0.0518722	total: 1m 8s	remaining: 20m 11s
574:	learn: 0.0416149	total: 1m 8s	remaining: 18m 38s
582:	learn: 0.0458179	total: 1m 8s	remaining: 18m 21s
586:	learn: 0.0445111	total: 1m 8s	remaining: 18m 16s
564:	learn: 0.0463312	total: 1m 8s	remaining: 19m
533:	learn: 0.0517289	total: 1m 8s	remaining: 20m 11s
575:	learn: 0.0415057	total: 1m 8s	remaining: 18m 37s
587:	learn: 0.0444039	total: 1m 8s	remaining: 18m 15s
583:	learn: 0.0457296	total: 1m 8s	remaining: 18m 21s
534:	learn: 0.0515712	total: 1m 8s	remaining: 20m 10s
565:	learn: 0.0462080	total: 1m 8s	remaining: 19m
576:	learn: 0.0414620	total: 1m 8s	remaining: 18m 36s
588:	learn: 0.0443216	total: 1m 8s	remaining: 18m 15s
535:	learn: 0.0515133	total: 1m 8s	remaining: 20m 10s
566:	learn: 0.0460804	total: 1m 8s	remaining: 18m 59s
584:	learn: 0.0456469	total: 1m 8s	remaining: 18m 21s
577:	learn: 0.0413984	total: 1m 8s	remaining: 18m 36s
589:	learn: 0.0442159	total: 1m 8s	remaining: 18m 15s
567:	learn: 0.0459912	total: 1m 8s	remaining: 18m 58s
585:	learn: 0.0455677	total: 1m 8s	remaining: 18m 21s
578:	learn: 0.0412780	total: 1m 8s	remaining: 18m 36s
536:	learn: 0.0514040	total: 1m 8s	remaining: 20m 10s
590:	learn: 0.0441339	total: 1m 8s	remaining: 18m 14s
568:	learn: 0.0458424	total: 1m 8s	remaining: 18m 58s
586:	learn: 0.0454192	total: 1m 8s	remaining: 18m 20s
579:	learn: 0.0411743	total: 1m 8s	remaining: 18m 35s
537:	learn: 0.0512861	total: 1m 8s	remaining: 20m 9s
591:	learn: 0.0440357	total: 1m 8s	remaining: 18m 14s
569:	learn: 0.0457085	total: 1m 8s	remaining: 18m 58s
580:	learn: 0.0410818	total: 1m 8s	remaining: 18m 34s
587:	learn: 0.0453389	total: 1m 8s	remaining: 18m 20s
538:	learn: 0.0511688	total: 1m 8s	remaining: 20m 8s
592:	learn: 0.0439374	total: 1m 8s	remaining: 18m 13s
570:	learn: 0.0456110	total: 1m 8s	remaining: 18m 57s
581:	learn: 0.0410024	total: 1m 8s	remaining: 18m 34s
588:	learn: 0.0452583	total: 1m 8s	remaining: 18m 20s
539:	learn: 0.0510955	total: 1m 8s	remaining: 20m 8s
571:	learn: 0.0454844	total: 1m 8s	remaining: 18m 56s
593:	learn: 0.0438415	total: 1m 9s	remaining: 18m 13s
582:	learn: 0.0409196	total: 1m 8s	remaining: 18m 33s
589:	learn: 0.0451373	total: 1m 8s	remaining: 18m 19s
540:	learn: 0.0509605	total: 1m 9s	remaining: 20m 7s
572:	learn: 0.0453854	total: 1m 9s	remaining: 18m 56s
583:	learn: 0.0408470	total: 1m 9s	remaining: 18m 33s
590:	learn: 0.0450518	total: 1m 9s	remaining: 18m 19s
594:	learn: 0.0437355	total: 1m 9s	remaining: 18m 13s
541:	learn: 0.0508125	total: 1m 9s	remaining: 20m 6s
584:	learn: 0.0407619	total: 1m 9s	remaining: 18m 32s
573:	learn: 0.0452626	total: 1m 9s	remaining: 18m 56s
595:	learn: 0.0436530	total: 1m 9s	remaining: 18m 13s
591:	learn: 0.0449235	total: 1m 9s	remaining: 18m 19s
542:	learn: 0.0507114	total: 1m 9s	remaining: 20m 6s
585:	learn: 0.0406974	total: 1m 9s	remaining: 18m 32s
574:	learn: 0.0451643	total: 1m 9s	remaining: 18m 55s
592:	learn: 0.0448491	total: 1m 9s	remaining: 18m 18s
596:	learn: 0.0435515	total: 1m 9s	remaining: 18m 13s
543:	learn: 0.0506034	total: 1m 9s	remaining: 20m 5s
586:	learn: 0.0406035	total: 1m 9s	remaining: 18m 31s
593:	learn: 0.0447451	total: 1m 9s	remaining: 18m 18s
597:	learn: 0.0434634	total: 1m 9s	remaining: 18m 12s
575:	learn: 0.0450143	total: 1m 9s	remaining: 18m 55s
544:	learn: 0.0504864	total: 1m 9s	remaining: 20m 5s
598:	learn: 0.0433630	total: 1m 9s	remaining: 18m 11s
587:	learn: 0.0404948	total: 1m 9s	remaining: 18m 31s
594:	learn: 0.0446556	total: 1m 9s	remaining: 18m 17s
588:	learn: 0.0404060	total: 1m 9s	remaining: 18m 30s
576:	learn: 0.0449101	total: 1m 9s	remaining: 18m 55s
599:	learn: 0.0432929	total: 1m 9s	remaining: 18m 11s
545:	learn: 0.0503864	total: 1m 9s	remaining: 20m 5s

589:	learn: 0.0403299	total: 1m 9s	remaining: 18m 29s
595:	learn: 0.0445651	total: 1m 9s	remaining: 18m 17s
600:	learn: 0.0431890	total: 1m 9s	remaining: 18m 10s
577:	learn: 0.0447979	total: 1m 9s	remaining: 18m 55s
590:	learn: 0.0402712	total: 1m 9s	remaining: 18m 28s
546:	learn: 0.0502891	total: 1m 9s	remaining: 20m 5s
591:	learn: 0.0401782	total: 1m 9s	remaining: 18m 27s
596:	learn: 0.0444748	total: 1m 9s	remaining: 18m 17s
601:	learn: 0.0431182	total: 1m 9s	remaining: 18m 10s
578:	learn: 0.0446883	total: 1m 9s	remaining: 18m 55s
592:	learn: 0.0401040	total: 1m 9s	remaining: 18m 26s
547:	learn: 0.0502060	total: 1m 9s	remaining: 20m 5s
597:	learn: 0.0443202	total: 1m 9s	remaining: 18m 17s
602:	learn: 0.0429936	total: 1m 9s	remaining: 18m 10s
579:	learn: 0.0446295	total: 1m 9s	remaining: 18m 54s
593:	learn: 0.0400206	total: 1m 9s	remaining: 18m 26s
548:	learn: 0.0500445	total: 1m 9s	remaining: 20m 4s
598:	learn: 0.0442133	total: 1m 9s	remaining: 18m 17s
603:	learn: 0.0428716	total: 1m 10s	remaining: 18m 9s
580:	learn: 0.0445347	total: 1m 9s	remaining: 18m 54s
594:	learn: 0.0398928	total: 1m 9s	remaining: 18m 25s
549:	learn: 0.0498881	total: 1m 10s	remaining: 20m 4s
599:	learn: 0.0441588	total: 1m 10s	remaining: 18m 16s
604:	learn: 0.0427976	total: 1m 10s	remaining: 18m 9s
581:	learn: 0.0444290	total: 1m 10s	remaining: 18m 53s
595:	learn: 0.0398236	total: 1m 10s	remaining: 18m 25s
600:	learn: 0.0440711	total: 1m 10s	remaining: 18m 16s
550:	learn: 0.0498010	total: 1m 10s	remaining: 20m 3s
605:	learn: 0.0427169	total: 1m 10s	remaining: 18m 9s
582:	learn: 0.0443137	total: 1m 10s	remaining: 18m 53s
596:	learn: 0.0397059	total: 1m 10s	remaining: 18m 25s
601:	learn: 0.0439970	total: 1m 10s	remaining: 18m 15s
606:	learn: 0.0426158	total: 1m 10s	remaining: 18m 8s
551:	learn: 0.0496867	total: 1m 10s	remaining: 20m 3s
583:	learn: 0.0442599	total: 1m 10s	remaining: 18m 53s
597:	learn: 0.0396387	total: 1m 10s	remaining: 18m 24s
607:	learn: 0.0425299	total: 1m 10s	remaining: 18m 8s
602:	learn: 0.0438953	total: 1m 10s	remaining: 18m 15s
584:	learn: 0.0441654	total: 1m 10s	remaining: 18m 52s
552:	learn: 0.0495836	total: 1m 10s	remaining: 20m 3s
598:	learn: 0.0395790	total: 1m 10s	remaining: 18m 24s
608:	learn: 0.0424172	total: 1m 10s	remaining: 18m 7s
603:	learn: 0.0437771	total: 1m 10s	remaining: 18m 15s
585:	learn: 0.0440917	total: 1m 10s	remaining: 18m 52s
609:	learn: 0.0423612	total: 1m 10s	remaining: 18m 6s
553:	learn: 0.0494576	total: 1m 10s	remaining: 20m 2s
599:	learn: 0.0395089	total: 1m 10s	remaining: 18m 24s
604:	learn: 0.0436948	total: 1m 10s	remaining: 18m 14s
586:	learn: 0.0439649	total: 1m 10s	remaining: 18m 51s
610:	learn: 0.0422475	total: 1m 10s	remaining: 18m 6s
600:	learn: 0.0394456	total: 1m 10s	remaining: 18m 23s
554:	learn: 0.0493767	total: 1m 10s	remaining: 20m 2s
587:	learn: 0.0438574	total: 1m 10s	remaining: 18m 50s
605:	learn: 0.0436231	total: 1m 10s	remaining: 18m 14s
611:	learn: 0.0421728	total: 1m 10s	remaining: 18m 6s
601:	learn: 0.0393850	total: 1m 10s	remaining: 18m 23s
555:	learn: 0.0492536	total: 1m 10s	remaining: 20m 2s
588:	learn: 0.0437785	total: 1m 10s	remaining: 18m 50s
606:	learn: 0.0435559	total: 1m 10s	remaining: 18m 14s
612:	learn: 0.0420962	total: 1m 10s	remaining: 18m 6s
602:	learn: 0.0393235	total: 1m 10s	remaining: 18m 23s
589:	learn: 0.0437053	total: 1m 10s	remaining: 18m 49s
556:	learn: 0.0491845	total: 1m 10s	remaining: 20m 1s
607:	learn: 0.0434749	total: 1m 10s	remaining: 18m 13s
613:	learn: 0.0420264	total: 1m 10s	remaining: 18m 5s
590:	learn: 0.0435869	total: 1m 10s	remaining: 18m 49s
603:	learn: 0.0392002	total: 1m 10s	remaining: 18m 23s
608:	learn: 0.0433785	total: 1m 10s	remaining: 18m 13s
557:	learn: 0.0490728	total: 1m 10s	remaining: 20m 1s
609:	learn: 0.0433073	total: 1m 10s	remaining: 18m 12s
614:	learn: 0.0419497	total: 1m 11s	remaining: 18m 5s
604:	learn: 0.0391325	total: 1m 11s	remaining: 18m 22s
591:	learn: 0.0435117	total: 1m 11s	remaining: 18m 49s
558:	learn: 0.0489723	total: 1m 11s	remaining: 20m 1s
610:	learn: 0.0432244	total: 1m 11s	remaining: 18m 11s
592:	learn: 0.0434045	total: 1m 11s	remaining: 18m 48s
615:	learn: 0.0418676	total: 1m 11s	remaining: 18m 4s
605:	learn: 0.0390530	total: 1m 11s	remaining: 18m 22s
611:	learn: 0.0431474	total: 1m 11s	remaining: 18m 11s
559:	learn: 0.0488585	total: 1m 11s	remaining: 20m
593:	learn: 0.0432569	total: 1m 11s	remaining: 18m 47s
616:	learn: 0.0418131	total: 1m 11s	remaining: 18m 4s
560:	learn: 0.0488072	total: 1m 11s	remaining: 20m
612:	learn: 0.0430639	total: 1m 11s	remaining: 18m 11s
594:	learn: 0.0431538	total: 1m 11s	remaining: 18m 46s
606:	learn: 0.0389114	total: 1m 11s	remaining: 18m 22s
617:	learn: 0.0417633	total: 1m 11s	remaining: 18m 4s
613:	learn: 0.0429615	total: 1m 11s	remaining: 18m 10s
595:	learn: 0.0430778	total: 1m 11s	remaining: 18m 46s
561:	learn: 0.0486654	total: 1m 11s	remaining: 19m 59s
607:	learn: 0.0388471	total: 1m 11s	remaining: 18m 22s
618:	learn: 0.0416925	total: 1m 11s	remaining: 18m 4s
596:	learn: 0.0429649	total: 1m 11s	remaining: 18m 45s
614:	learn: 0.0428898	total: 1m 11s	remaining: 18m 9s
562:	learn: 0.0485969	total: 1m 11s	remaining: 19m 59s
608:	learn: 0.0387528	total: 1m 11s	remaining: 18m 22s
619:	learn: 0.0415928	total: 1m 11s	remaining: 18m 3s
615:	learn: 0.0427733	total: 1m 11s	remaining: 18m 9s
597:	learn: 0.0428827	total: 1m 11s	remaining: 18m 45s
563:	learn: 0.0484912	total: 1m 11s	remaining: 19m 58s
609:	learn: 0.0386453	total: 1m 11s	remaining: 18m 22s
620:	learn: 0.0414767	total: 1m 11s	remaining: 18m 3s
564:	learn: 0.0484096	total: 1m 11s	remaining: 19m 57s
616:	learn: 0.0427098	total: 1m 11s	remaining: 18m 9s
598:	learn: 0.0427586	total: 1m 11s	remaining: 18m 45s
610:	learn: 0.0385628	total: 1m 11s	remaining: 18m 21s
621:	learn: 0.0413808	total: 1m 11s	remaining: 18m 3s
617:	learn: 0.0426373	total: 1m 11s	remaining: 18m 8s
565:	learn: 0.0482886	total: 1m 11s	remaining: 19m 57s
599:	learn: 0.0426600	total: 1m 11s	remaining: 18m 45s
611:	learn: 0.0385065	total: 1m 11s	remaining: 18m 21s
622:	learn: 0.0412962	total: 1m 11s	remaining: 18m 2s
618:	learn: 0.0425415	total: 1m 11s	remaining: 18m 8s
566:	learn: 0.0481871	total: 1m 11s	remaining: 19m 56s
600:	learn: 0.0425710	total: 1m 11s	remaining: 18m 44s
623:	learn: 0.0412253	total: 1m 12s	remaining: 18m 1s
612:	learn: 0.0384058	total: 1m 11s	remaining: 18m 21s
619:	learn: 0.0424620	total: 1m 11s	remaining: 18m 8s
624:	learn: 0.0411214	total: 1m 12s	remaining: 18m 1s
601:	learn: 0.0424849	total: 1m 11s	remaining: 18m 43s
613:	learn: 0.0383228	total: 1m 12s	remaining: 18m 20s
567:	learn: 0.0480797	total: 1m 12s	remaining: 19m 57s
602:	learn: 0.0423508	total: 1m 12s	remaining: 18m 43s
620:	learn: 0.0423483	total: 1m 12s	remaining: 18m 7s
625:	learn: 0.0410064	total: 1m 12s	remaining: 18m
614:	learn: 0.0382455	total: 1m 12s	remaining: 18m 20s
568:	learn: 0.0479941	total: 1m 12s	remaining: 19m 56s
603:	learn: 0.0422555	total: 1m 12s	remaining: 18m 42s
621:	learn: 0.0422584	total: 1m 12s	remaining: 18m 7s
615:	learn: 0.0381580	total: 1m 12s	remaining: 18m 19s
626:	learn: 0.0409215	total: 1m 12s	remaining: 18m 1s
569:	learn: 0.0478531	total: 1m 12s	remaining: 19m 56s
604:	learn: 0.0421701	total: 1m 12s	remaining: 18m 42s
627:	learn: 0.0408281	total: 1m 12s	remaining: 18m
616:	learn: 0.0380794	total: 1m 12s	remaining: 18m 19s
622:	learn: 0.0421624	total: 1m 12s	remaining: 18m 7s
605:	learn: 0.0420935	total: 1m 12s	remaining: 18m 41s
570:	learn: 0.0477170	total: 1m 12s	remaining: 19m 55s
617:	learn: 0.0379752	total: 1m 12s	remaining: 18m 18s
628:	learn: 0.0407319	total: 1m 12s	remaining: 18m
623:	learn: 0.0420702	total: 1m 12s	remaining: 18m 7s
606:	learn: 0.0420004	total: 1m 12s	remaining: 18m 40s
571:	learn: 0.0476074	total: 1m 12s	remaining: 19m 55s
618:	learn: 0.0379166	total: 1m 12s	remaining: 18m 18s
629:	learn: 0.0406571	total: 1m 12s	remaining: 17m 59s
624:	learn: 0.0419365	total: 1m 12s	remaining: 18m 7s
607:	learn: 0.0419208	total: 1m 12s	remaining: 18m 40s
619:	learn: 0.0377876	total: 1m 12s	remaining: 18m 17s
572:	learn: 0.0475103	total: 1m 12s	remaining: 19m 54s
630:	learn: 0.0405487	total: 1m 12s	remaining: 17m 59s
625:	learn: 0.0418092	total: 1m 12s	remaining: 18m 7s
620:	learn: 0.0376839	total: 1m 12s	remaining: 18m 17s
631:	learn: 0.0404611	total: 1m 12s	remaining: 17m 58s
574:	learn: 0.0473069	total: 1m 12s	remaining: 19m 53s
632:	learn: 0.0403556	total: 1m 12s	remaining: 17m 58s
609:	learn: 0.0417752	total: 1m 12s	remaining: 18m 40s
626:	learn: 0.0417173	total: 1m 12s	remaining: 18m 7s
621:	learn: 0.0375831	total: 1m 12s	remaining: 18m 17s
633:	learn: 0.0402920	total: 1m 12s	remaining: 17m 57s
575:	learn: 0.0471780	total: 1m 12s	remaining: 19m 52s
627:	learn: 0.0416203	total: 1m 12s	remaining: 18m 6s
610:	learn: 0.0416801	total: 1m 12s	remaining: 18m 40s
622:	learn: 0.0375344	total: 1m 12s	remaining: 18m 16s
634:	learn: 0.0402009	total: 1m 13s	remaining: 17m 56s
576:	learn: 0.0470733	total: 1m 12s	remaining: 19m 52s
628:	learn: 0.0415352	total: 1m 12s	remaining: 18m 6s
623:	learn: 0.0374617	total: 1m 12s	remaining: 18m 16s
635:	learn: 0.0401281	total: 1m 13s	remaining: 17m 56s
611:	learn: 0.0416015	total: 1m 13s	remaining: 18m 40s
577:	learn: 0.0469520	total: 1m 13s	remaining: 19m 51s
629:	learn: 0.0414541	total: 1m 13s	remaining: 18m 5s
636:	learn: 0.0400365	total: 1m 13s	remaining: 17m 55s
624:	learn: 0.0373669	total: 1m 13s	remaining: 18m 16s
578:	learn: 0.0468422	total: 1m 13s	remaining: 19m 50s
612:	learn: 0.0415052	total: 1m 13s	remaining: 18m 40s
637:	learn: 0.0399572	total: 1m 13s	remaining: 17m 54s
625:	learn: 0.0372722	total: 1m 13s	remaining: 18m 15s
630:	learn: 0.0413149	total: 1m 13s	remaining: 18m 6s
579:	learn: 0.0467398	total: 1m 13s	remaining: 19m 50s
613:	learn: 0.0414188	total: 1m 13s	remaining: 18m 40s
638:	learn: 0.0398635	total: 1m 13s	remaining: 17m 54s
626:	learn: 0.0371969	total: 1m 13s	remaining: 18m 15s
631:	learn: 0.0412275	total: 1m 13s	remaining: 18m 6s
580:	learn: 0.0466754	total: 1m 13s	remaining: 19m 49s
627:	learn: 0.0370757	total: 1m 13s	remaining: 18m 14s
639:	learn: 0.0397693	total: 1m 13s	remaining: 17m 54s
614:	learn: 0.0413517	total: 1m 13s	remaining: 18m 39s
581:	learn: 0.0465888	total: 1m 13s	remaining: 19m 48s
632:	learn: 0.0411349	total: 1m 13s	remaining: 18m 5s
628:	learn: 0.0370371	total: 1m 13s	remaining: 18m 14s
640:	learn: 0.0396829	total: 1m 13s	remaining: 17m 53s
615:	learn: 0.0412721	total: 1m 13s	remaining: 18m 39s
582:	learn: 0.0464929	total: 1m 13s	remaining: 19m 48s
629:	learn: 0.0369664	total: 1m 13s	remaining: 18m 13s
633:	learn: 0.0410236	total: 1m 13s	remaining: 18m 5s
641:	learn: 0.0396067	total: 1m 13s	remaining: 17m 53s
583:	learn: 0.0464193	total: 1m 13s	remaining: 19m 47s
616:	learn: 0.0411920	total: 1m 13s	remaining: 18m 39s
642:	learn: 0.0395332	total: 1m 13s	remaining: 17m 52s
634:	learn: 0.0409673	total: 1m 13s	remaining: 18m 5s
630:	learn: 0.0369045	total: 1m 13s	remaining: 18m 13s
584:	learn: 0.0463160	total: 1m 13s	remaining: 19m 46s
617:	learn: 0.0410829	total: 1m 13s	remaining: 18m 39s
643:	learn: 0.0394553	total: 1m 13s	remaining: 17m 52s
631:	learn: 0.0368136	total: 1m 13s	remaining: 18m 13s
585:	learn: 0.0462060	total: 1m 13s	remaining: 19m 46s
635:	learn: 0.0408595	total: 1m 13s	remaining: 18m 5s
618:	learn: 0.0409888	total: 1m 13s	remaining: 18m 38s
644:	learn: 0.0393940	total: 1m 13s	remaining: 17m 52s
632:	learn: 0.0367109	total: 1m 13s	remaining: 18m 12s
586:	learn: 0.0461118	total: 1m 13s	remaining: 19m 45s
636:	learn: 0.0407561	total: 1m 13s	remaining: 18m 5s
645:	learn: 0.0392990	total: 1m 14s	remaining: 17m 51s
619:	learn: 0.0409366	total: 1m 13s	remaining: 18m 38s
633:	learn: 0.0365965	total: 1m 13s	remaining: 18m 12s
587:	learn: 0.0460036	total: 1m 14s	remaining: 19m 45s
646:	learn: 0.0391854	total: 1m 14s	remaining: 17m 51s
637:	learn: 0.0406575	total: 1m 13s	remaining: 18m 5s
620:	learn: 0.0408321	total: 1m 14s	remaining: 18m 38s
634:	learn: 0.0365123	total: 1m 14s	remaining: 18m 11s
647:	learn: 0.0390512	total: 1m 14s	remaining: 17m 50s
588:	learn: 0.0458776	total: 1m 14s	remaining: 19m 44s
638:	learn: 0.0406034	total: 1m 14s	remaining: 18m 5s
621:	learn: 0.0407065	total: 1m 14s	remaining: 18m 37s
635:	learn: 0.0364414	total: 1m 14s	remaining: 18m 11s
622:	learn: 0.0405987	total: 1m 14s	remaining: 18m 37s
648:	learn: 0.0390017	total: 1m 14s	remaining: 17m 50s
639:	learn: 0.0405321	total: 1m 14s	remaining: 18m 4s
589:	learn: 0.0457888	total: 1m 14s	remaining: 19m 44s
636:	learn: 0.0363543	total: 1m 14s	remaining: 18m 11s
649:	learn: 0.0389019	total: 1m 14s	remaining: 17m 50s
623:	learn: 0.0405260	total: 1m 14s	remaining: 18m 36s
640:	learn: 0.0404610	total: 1m 14s	remaining: 18m 4s
590:	learn: 0.0456553	total: 1m 14s	remaining: 19m 44s
650:	learn: 0.0388412	total: 1m 14s	remaining: 17m 49s
637:	learn: 0.0362504	total: 1m 14s	remaining: 18m 11s
624:	learn: 0.0403989	total: 1m 14s	remaining: 18m 36s
641:	learn: 0.0404087	total: 1m 14s	remaining: 18m 4s
591:	learn: 0.0455270	total: 1m 14s	remaining: 19m 43s
651:	learn: 0.0387512	total: 1m 14s	remaining: 17m 48s
638:	learn: 0.0361780	total: 1m 14s	remaining: 18m 11s
592:	learn: 0.0454060	total: 1m 14s	remaining: 19m 42s
625:	learn: 0.0402922	total: 1m 14s	remaining: 18m 36s
652:	learn: 0.0386807	total: 1m 14s	remaining: 17m 48s
642:	learn: 0.0403093	total: 1m 14s	remaining: 18m 4s
639:	learn: 0.0360886	total: 1m 14s	remaining: 18m 10s
593:	learn: 0.0452664	total: 1m 14s	remaining: 19m 42s
653:	learn: 0.0385949	total: 1m 14s	remaining: 17m 47s
643:	learn: 0.0402455	total: 1m 14s	remaining: 18m 3s
626:	learn: 0.0402089	total: 1m 14s	remaining: 18m 35s
594:	learn: 0.0451770	total: 1m 14s	remaining: 19m 41s
654:	learn: 0.0385174	total: 1m 14s	remaining: 17m 47s
640:	learn: 0.0360410	total: 1m 14s	remaining: 18m 10s
644:	learn: 0.0401726	total: 1m 14s	remaining: 18m 3s
627:	learn: 0.0401370	total: 1m 14s	remaining: 18m 35s
595:	learn: 0.0450814	total: 1m 14s	remaining: 19m 41s
641:	learn: 0.0359777	total: 1m 14s	remaining: 18m 10s
655:	learn: 0.0384382	total: 1m 14s	remaining: 17m 47s
645:	learn: 0.0400820	total: 1m 14s	remaining: 18m 3s
628:	learn: 0.0400273	total: 1m 14s	remaining: 18m 35s
596:	learn: 0.0449639	total: 1m 14s	remaining: 19m 40s
642:	learn: 0.0359073	total: 1m 14s	remaining: 18m 9s
656:	learn: 0.0383645	total: 1m 15s	remaining: 17m 46s
646:	learn: 0.0399920	total: 1m 14s	remaining: 18m 2s
629:	learn: 0.0399190	total: 1m 14s	remaining: 18m 35s
643:	learn: 0.0358144	total: 1m 14s	remaining: 18m 9s
597:	learn: 0.0448437	total: 1m 15s	remaining: 19m 39s
657:	learn: 0.0382633	total: 1m 15s	remaining: 17m 46s
647:	learn: 0.0398933	total: 1m 14s	remaining: 18m 2s
630:	learn: 0.0398471	total: 1m 15s	remaining: 18m 34s
644:	learn: 0.0357413	total: 1m 15s	remaining: 18m 8s
598:	learn: 0.0447731	total: 1m 15s	remaining: 19m 39s
658:	learn: 0.0381877	total: 1m 15s	remaining: 17m 46s
648:	learn: 0.0398310	total: 1m 15s	remaining: 18m 2s
631:	learn: 0.0397690	total: 1m 15s	remaining: 18m 34s
645:	learn: 0.0356711	total: 1m 15s	remaining: 18m 8s
659:	learn: 0.0381306	total: 1m 15s	remaining: 17m 45s
599:	learn: 0.0447005	total: 1m 15s	remaining: 19m 39s
632:	learn: 0.0396684	total: 1m 15s	remaining: 18m 33s
649:	learn: 0.0397516	total: 1m 15s	remaining: 18m 1s
646:	learn: 0.0356126	total: 1m 15s	remaining: 18m 7s
660:	learn: 0.0380442	total: 1m 15s	remaining: 17m 45s
600:	learn: 0.0446092	total: 1m 15s	remaining: 19m 39s
633:	learn: 0.0395759	total: 1m 15s	remaining: 18m 33s
650:	learn: 0.0396918	total: 1m 15s	remaining: 18m 1s
647:	learn: 0.0355402	total: 1m 15s	remaining: 18m 7s
661:	learn: 0.0379719	total: 1m 15s	remaining: 17m 44s
634:	learn: 0.0394919	total: 1m 15s	remaining: 18m 32s
601:	learn: 0.0445085	total: 1m 15s	remaining: 19m 38s
651:	learn: 0.0396028	total: 1m 15s	remaining: 18m 1s
648:	learn: 0.0354808	total: 1m 15s	remaining: 18m 7s
662:	learn: 0.0378760	total: 1m 15s	remaining: 17m 44s
602:	learn: 0.0444085	total: 1m 15s	remaining: 19m 37s
635:	learn: 0.0393976	total: 1m 15s	remaining: 18m 32s
652:	learn: 0.0395111	total: 1m 15s	remaining: 18m
649:	learn: 0.0354292	total: 1m 15s	remaining: 18m 6s
663:	learn: 0.0377793	total: 1m 15s	remaining: 17m 44s
4s	remaining: 22m 55s
246:	learn: 0.1144236	total: 34.6s	remaining: 22m 44s

243:	learn: 0.1066516	total: 34.5s603:	learn: 0.0442814	total: 1m 15s	remaining: 19m 37s
636:	learn: 0.0393316	total: 1m 15s	remaining: 18m 31s
653:	learn: 0.0394518	total: 1m 15s	remaining: 18m
650:	learn: 0.0353319	total: 1m 15s	remaining: 18m 6s
664:	learn: 0.0376687	total: 1m 15s	remaining: 17m 43s
604:	learn: 0.0442078	total: 1m 15s	remaining: 19m 37s
654:	learn: 0.0393604	total: 1m 15s	remaining: 18m
637:	learn: 0.0392757	total: 1m 15s	remaining: 18m 31s
665:	learn: 0.0375579	total: 1m 15s	remaining: 17m 43s
651:	learn: 0.0352501	total: 1m 15s	remaining: 18m 6s
655:	learn: 0.0392934	total: 1m 15s	remaining: 17m 59s
638:	learn: 0.0392197	total: 1m 15s	remaining: 18m 30s
605:	learn: 0.0441414	total: 1m 15s	remaining: 19m 36s
666:	learn: 0.0374602	total: 1m 15s	remaining: 17m 43s
652:	learn: 0.0351560	total: 1m 15s	remaining: 18m 6s
639:	learn: 0.0391449	total: 1m 15s	remaining: 18m 30s
656:	learn: 0.0392230	total: 1m 15s	remaining: 17m 59s
667:	learn: 0.0373688	total: 1m 16s	remaining: 17m 42s
606:	learn: 0.0440786	total: 1m 16s	remaining: 19m 36s
653:	learn: 0.0350839	total: 1m 15s	remaining: 18m 5s
668:	learn: 0.0372738	total: 1m 16s	remaining: 17m 42s
657:	learn: 0.0391461	total: 1m 16s	remaining: 17m 59s
640:	learn: 0.0390883	total: 1m 16s	remaining: 18m 30s
607:	learn: 0.0440146	total: 1m 16s	remaining: 19m 36s
654:	learn: 0.0350074	total: 1m 16s	remaining: 18m 5s
669:	learn: 0.0371810	total: 1m 16s	remaining: 17m 41s
658:	learn: 0.0390490	total: 1m 16s	remaining: 17m 58s
608:	learn: 0.0438738	total: 1m 16s	remaining: 19m 35s
641:	learn: 0.0390066	total: 1m 16s	remaining: 18m 30s
655:	learn: 0.0349203	total: 1m 16s	remaining: 18m 5s
670:	learn: 0.0370970	total: 1m 16s	remaining: 17m 41s
659:	learn: 0.0389787	total: 1m 16s	remaining: 17m 58s
609:	learn: 0.0437695	total: 1m 16s	remaining: 19m 35s
642:	learn: 0.0389291	total: 1m 16s	remaining: 18m 30s
656:	learn: 0.0348605	total: 1m 16s	remaining: 18m 4s
671:	learn: 0.0370173	total: 1m 16s	remaining: 17m 40s
660:	learn: 0.0388795	total: 1m 16s	remaining: 17m 57s
610:	learn: 0.0436774	total: 1m 16s	remaining: 19m 34s
657:	learn: 0.0347996	total: 1m 16s	remaining: 18m 4s
643:	learn: 0.0388373	total: 1m 16s	remaining: 18m 30s
661:	learn: 0.0388141	total: 1m 16s	remaining: 17m 57s
672:	learn: 0.0369559	total: 1m 16s	remaining: 17m 40s
611:	learn: 0.0435942	total: 1m 16s	remaining: 19m 34s
662:	learn: 0.0387486	total: 1m 16s	remaining: 17m 56s
658:	learn: 0.0347299	total: 1m 16s	remaining: 18m 4s
644:	learn: 0.0387402	total: 1m 16s	remaining: 18m 30s
673:	learn: 0.0369055	total: 1m 16s	remaining: 17m 40s
612:	learn: 0.0435029	total: 1m 16s	remaining: 19m 33s
663:	learn: 0.0386886	total: 1m 16s	remaining: 17m 56s
659:	learn: 0.0346708	total: 1m 16s	remaining: 18m 3s
645:	learn: 0.0386569	total: 1m 16s	remaining: 18m 29s
664:	learn: 0.0386312	total: 1m 16s	remaining: 17m 55s
674:	learn: 0.0368412	total: 1m 16s	remaining: 17m 40s
613:	learn: 0.0434442	total: 1m 16s	remaining: 19m 33s
660:	learn: 0.0345981	total: 1m 16s	remaining: 18m 3s
646:	learn: 0.0385868	total: 1m 16s	remaining: 18m 29s
665:	learn: 0.0385694	total: 1m 16s	remaining: 17m 55s
675:	learn: 0.0367757	total: 1m 16s	remaining: 17m 40s
614:	learn: 0.0433738	total: 1m 16s	remaining: 19m 32s
661:	learn: 0.0345203	total: 1m 16s	remaining: 18m 3s
666:	learn: 0.0384759	total: 1m 16s	remaining: 17m 54s
647:	learn: 0.0384940	total: 1m 16s	remaining: 18m 29s
676:	learn: 0.0366807	total: 1m 16s	remaining: 17m 40s
615:	learn: 0.0432882	total: 1m 16s	remaining: 19m 32s
662:	learn: 0.0344494	total: 1m 16s	remaining: 18m 2s
667:	learn: 0.0383989	total: 1m 16s	remaining: 17m 53s
648:	learn: 0.0384241	total: 1m 16s	remaining: 18m 28s
677:	learn: 0.0366015	total: 1m 17s	remaining: 17m 39s
668:	learn: 0.0383445	total: 1m 16s	remaining: 17m 53s
616:	learn: 0.0432222	total: 1m 17s	remaining: 19m 32s
663:	learn: 0.0343610	total: 1m 17s	remaining: 18m 2s
649:	learn: 0.0383026	total: 1m 17s	remaining: 18m 28s
678:	learn: 0.0365196	total: 1m 17s	remaining: 17m 39s
669:	learn: 0.0382929	total: 1m 17s	remaining: 17m 53s
664:	learn: 0.0343028	total: 1m 17s	remaining: 18m 2s
617:	learn: 0.0431320	total: 1m 17s	remaining: 19m 31s
650:	learn: 0.0382534	total: 1m 17s	remaining: 18m 28s
679:	learn: 0.0364560	total: 1m 17s	remaining: 17m 39s
670:	learn: 0.0381818	total: 1m 17s	remaining: 17m 52s
665:	learn: 0.0342492	total: 1m 17s	remaining: 18m 1s
618:	learn: 0.0430199	total: 1m 17s	remaining: 19m 31s
680:	learn: 0.0363967	total: 1m 17s	remaining: 17m 38s
651:	learn: 0.0381523	total: 1m 17s	remaining: 18m 27s
671:	learn: 0.0381262	total: 1m 17s	remaining: 17m 52s
666:	learn: 0.0341689	total: 1m 17s	remaining: 18m 1s
681:	learn: 0.0362968	total: 1m 17s	remaining: 17m 38s
619:	learn: 0.0429299	total: 1m 17s	remaining: 19m 31s
652:	learn: 0.0380682	total: 1m 17s	remaining: 18m 27s
672:	learn: 0.0380490	total: 1m 17s	remaining: 17m 52s
682:	learn: 0.0362109	total: 1m 17s	remaining: 17m 37s
667:	learn: 0.0340851	total: 1m 17s	remaining: 18m 2s
653:	learn: 0.0379963	total: 1m 17s	remaining: 18m 27s
620:	learn: 0.0428428	total: 1m 17s	remaining: 19m 31s
673:	learn: 0.0379572	total: 1m 17s	remaining: 17m 51s
668:	learn: 0.0339868	total: 1m 17s	remaining: 18m 1s
654:	learn: 0.0379229	total: 1m 17s	remaining: 18m 26s
683:	learn: 0.0361102	total: 1m 17s	remaining: 17m 37s
621:	learn: 0.0427386	total: 1m 17s	remaining: 19m 30s
674:	learn: 0.0379101	total: 1m 17s	remaining: 17m 51s
655:	learn: 0.0378273	total: 1m 17s	remaining: 18m 25s
669:	learn: 0.0339300	total: 1m 17s	remaining: 18m 1s
684:	learn: 0.0360419	total: 1m 17s	remaining: 17m 37s
622:	learn: 0.0426178	total: 1m 17s	remaining: 19m 30s
675:	learn: 0.0378563	total: 1m 17s	remaining: 17m 51s
670:	learn: 0.0338377	total: 1m 17s	remaining: 18m
685:	learn: 0.0359517	total: 1m 17s	remaining: 17m 37s
656:	learn: 0.0377280	total: 1m 17s	remaining: 18m 25s
676:	learn: 0.0377427	total: 1m 17s	remaining: 17m 51s
623:	learn: 0.0425553	total: 1m 17s	remaining: 19m 30s
671:	learn: 0.0337661	total: 1m 17s	remaining: 18m
657:	learn: 0.0376558	total: 1m 17s	remaining: 18m 25s
686:	learn: 0.0358957	total: 1m 17s	remaining: 17m 36s
672:	learn: 0.0337114	total: 1m 17s	remaining: 17m 59s
677:	learn: 0.0376833	total: 1m 17s	remaining: 17m 50s
624:	learn: 0.0424594	total: 1m 18s	remaining: 19m 30s
658:	learn: 0.0375631	total: 1m 17s	remaining: 18m 24s
687:	learn: 0.0358124	total: 1m 18s	remaining: 17m 36s
673:	learn: 0.0336430	total: 1m 17s	remaining: 17m 59s
678:	learn: 0.0376125	total: 1m 18s	remaining: 17m 50s
625:	learn: 0.0423969	total: 1m 18s	remaining: 19m 29s
659:	learn: 0.0374745	total: 1m 18s	remaining: 18m 24s
688:	learn: 0.0357734	total: 1m 18s	remaining: 17m 36s
674:	learn: 0.0335918	total: 1m 18s	remaining: 17m 58s
660:	learn: 0.0373978	total: 1m 18s	remaining: 18m 24s
679:	learn: 0.0375462	total: 1m 18s	remaining: 17m 50s
626:	learn: 0.0422968	total: 1m 18s	remaining: 19m 29s
689:	learn: 0.0356825	total: 1m 18s	remaining: 17m 35s
675:	learn: 0.0335300	total: 1m 18s	remaining: 17m 58s
680:	learn: 0.0374790	total: 1m 18s	remaining: 17m 50s
690:	learn: 0.0356171	total: 1m 18s	remaining: 17m 35s
661:	learn: 0.0373149	total: 1m 18s	remaining: 18m 24s
627:	learn: 0.0422199	total: 1m 18s	remaining: 19m 29s
676:	learn: 0.0334698	total: 1m 18s	remaining: 17m 57s
691:	learn: 0.0355459	total: 1m 18s	remaining: 17m 35s
677:	learn: 0.0334220	total: 1m 18s	remaining: 17m 57s
681:	learn: 0.0373921	total: 1m 18s	remaining: 17m 50s
628:	learn: 0.0421275	total: 1m 18s	remaining: 19m 28s
662:	learn: 0.0372526	total: 1m 18s	remaining: 18m 24s
678:	learn: 0.0333598	total: 1m 18s	remaining: 17m 56s
692:	learn: 0.0354572	total: 1m 18s	remaining: 17m 34s
682:	learn: 0.0373052	total: 1m 18s	remaining: 17m 49s
629:	learn: 0.0420306	total: 1m 18s	remaining: 19m 28s
663:	learn: 0.0371775	total: 1m 18s	remaining: 18m 23s
683:	learn: 0.0372046	total: 1m 18s	remaining: 17m 49s
693:	learn: 0.0353701	total: 1m 18s	remaining: 17m 34s
679:	learn: 0.0332802	total: 1m 18s	remaining: 17m 56s
664:	learn: 0.0370580	total: 1m 18s	remaining: 18m 23s
630:	learn: 0.0419212	total: 1m 18s	remaining: 19m 27s
694:	learn: 0.0352845	total: 1m 18s	remaining: 17m 33s

684:	learn: 0.0371225	total: 1m 18s	remaining: 17m 48s
680:	learn: 0.0332075	total: 1m 18s	remaining: 17m 56s
665:	learn: 0.0369740	total: 1m 18s	remaining: 18m 22s
631:	learn: 0.0418685	total: 1m 18s	remaining: 19m 27s
695:	learn: 0.0352188	total: 1m 18s	remaining: 17m 33s
685:	learn: 0.0370353	total: 1m 18s	remaining: 17m 48s
632:	learn: 0.0417638	total: 1m 18s	remaining: 19m 26s
681:	learn: 0.0331162	total: 1m 18s	remaining: 17m 56s
666:	learn: 0.0369196	total: 1m 18s	remaining: 18m 22s
696:	learn: 0.0351314	total: 1m 18s	remaining: 17m 33s
686:	learn: 0.0369705	total: 1m 18s	remaining: 17m 48s
682:	learn: 0.0330305	total: 1m 18s	remaining: 17m 56s
633:	learn: 0.0416557	total: 1m 18s	remaining: 19m 26s
667:	learn: 0.0368557	total: 1m 18s	remaining: 18m 22s
687:	learn: 0.0368928	total: 1m 18s	remaining: 17m 47s
697:	learn: 0.0350774	total: 1m 19s	remaining: 17m 33s
683:	learn: 0.0329689	total: 1m 18s	remaining: 17m 55s
688:	learn: 0.0368505	total: 1m 18s	remaining: 17m 47s
668:	learn: 0.0367894	total: 1m 19s	remaining: 18m 22s
698:	learn: 0.0349834	total: 1m 19s	remaining: 17m 32s
634:	learn: 0.0415994	total: 1m 19s	remaining: 19m 26s
684:	learn: 0.0328996	total: 1m 19s	remaining: 17m 55s
669:	learn: 0.0367295	total: 1m 19s	remaining: 18m 21s
635:	learn: 0.0415085	total: 1m 19s	remaining: 19m 25s
699:	learn: 0.0348851	total: 1m 19s	remaining: 17m 32s
689:	learn: 0.0367849	total: 1m 19s	remaining: 17m 47s
670:	learn: 0.0366340	total: 1m 19s	remaining: 18m 21s
685:	learn: 0.0328385	total: 1m 19s	remaining: 17m 55s
636:	learn: 0.0414176	total: 1m 19s	remaining: 19m 25s
700:	learn: 0.0348211	total: 1m 19s	remaining: 17m 32s
690:	learn: 0.0367039	total: 1m 19s	remaining: 17m 46s
686:	learn: 0.0327716	total: 1m 19s	remaining: 17m 54s
701:	learn: 0.0347501	total: 1m 19s	remaining: 17m 31s
637:	learn: 0.0413320	total: 1m 19s	remaining: 19m 24s
691:	learn: 0.0365942	total: 1m 19s	remaining: 17m 46s
671:	learn: 0.0365553	total: 1m 19s	remaining: 18m 21s
687:	learn: 0.0327067	total: 1m 19s	remaining: 17m 53s
702:	learn: 0.0346962	total: 1m 19s	remaining: 17m 31s
638:	learn: 0.0412307	total: 1m 19s	remaining: 19m 24s
688:	learn: 0.0326378	total: 1m 19s	remaining: 17m 53s
672:	learn: 0.0364980	total: 1m 19s	remaining: 18m 21s
692:	learn: 0.0365419	total: 1m 19s	remaining: 17m 46s
703:	learn: 0.0346542	total: 1m 19s	remaining: 17m 31s
639:	learn: 0.0411331	total: 1m 19s	remaining: 19m 24s
673:	learn: 0.0364112	total: 1m 19s	remaining: 18m 21s
693:	learn: 0.0364603	total: 1m 19s	remaining: 17m 46s
689:	learn: 0.0325459	total: 1m 19s	remaining: 17m 53s
704:	learn: 0.0345944	total: 1m 19s	remaining: 17m 30s
694:	learn: 0.0363964	total: 1m 19s	remaining: 17m 46s
640:	learn: 0.0410653	total: 1m 19s	remaining: 19m 24s
705:	learn: 0.0345283	total: 1m 19s	remaining: 17m 30s
690:	learn: 0.0324587	total: 1m 19s	remaining: 17m 53s
674:	learn: 0.0363320	total: 1m 19s	remaining: 18m 20s
695:	learn: 0.0363369	total: 1m 19s	remaining: 17m 45s
706:	learn: 0.0344746	total: 1m 19s	remaining: 17m 29s
641:	learn: 0.0410088	total: 1m 19s	remaining: 19m 23s
691:	learn: 0.0324040	total: 1m 19s	remaining: 17m 53s
675:	learn: 0.0362581	total: 1m 19s	remaining: 18m 20s
696:	learn: 0.0362505	total: 1m 19s	remaining: 17m 44s
692:	learn: 0.0323309	total: 1m 19s	remaining: 17m 52s
707:	learn: 0.0343981	total: 1m 19s	remaining: 17m 29s
642:	learn: 0.0408899	total: 1m 19s	remaining: 19m 23s
676:	learn: 0.0361930	total: 1m 19s	remaining: 18m 20s
697:	learn: 0.0361977	total: 1m 19s	remaining: 17m 44s
693:	learn: 0.0322753	total: 1m 19s	remaining: 17m 51s
708:	learn: 0.0343390	total: 1m 20s	remaining: 17m 29s
643:	learn: 0.0407725	total: 1m 20s	remaining: 19m 23s
694:	learn: 0.0321943	total: 1m 19s	remaining: 17m 50s
677:	learn: 0.0361086	total: 1m 20s	remaining: 18m 20s
698:	learn: 0.0360964	total: 1m 20s	remaining: 17m 44s
709:	learn: 0.0342876	total: 1m 20s	remaining: 17m 29s
695:	learn: 0.0321419	total: 1m 20s	remaining: 17m 50s
644:	learn: 0.0406571	total: 1m 20s	remaining: 19m 22s
699:	learn: 0.0360151	total: 1m 20s	remaining: 17m 43s
678:	learn: 0.0360271	total: 1m 20s	remaining: 18m 20s
710:	learn: 0.0342164	total: 1m 20s	remaining: 17m 28s
645:	learn: 0.0405905	total: 1m 20s	remaining: 19m 22s
696:	learn: 0.0321071	total: 1m 20s	remaining: 17m 50s
700:	learn: 0.0359467	total: 1m 20s	remaining: 17m 43s
711:	learn: 0.0341707	total: 1m 20s	remaining: 17m 28s
679:	learn: 0.0359646	total: 1m 20s	remaining: 18m 20s
646:	learn: 0.0404876	total: 1m 20s	remaining: 19m 21s
697:	learn: 0.0320314	total: 1m 20s	remaining: 17m 49s
701:	learn: 0.0358770	total: 1m 20s	remaining: 17m 43s
712:	learn: 0.0341210	total: 1m 20s	remaining: 17m 27s
680:	learn: 0.0359196	total: 1m 20s	remaining: 18m 19s
698:	learn: 0.0319892	total: 1m 20s	remaining: 17m 49s
713:	learn: 0.0340481	total: 1m 20s	remaining: 17m 27s
647:	learn: 0.0403942	total: 1m 20s	remaining: 19m 21s
699:	learn: 0.0319325	total: 1m 20s	remaining: 17m 48s
702:	learn: 0.0358034	total: 1m 20s	remaining: 17m 43s
681:	learn: 0.0358496	total: 1m 20s	remaining: 18m 19s
648:	learn: 0.0403125	total: 1m 20s	remaining: 19m 21s
714:	learn: 0.0339818	total: 1m 20s	remaining: 17m 27s
703:	learn: 0.0357286	total: 1m 20s	remaining: 17m 43s
682:	learn: 0.0357633	total: 1m 20s	remaining: 18m 19s
700:	learn: 0.0318703	total: 1m 20s	remaining: 17m 48s
649:	learn: 0.0401916	total: 1m 20s	remaining: 19m 20s
715:	learn: 0.0338964	total: 1m 20s	remaining: 17m 26s
704:	learn: 0.0356785	total: 1m 20s	remaining: 17m 42s
701:	learn: 0.0318008	total: 1m 20s	remaining: 17m 48s
683:	learn: 0.0356786	total: 1m 20s	remaining: 18m 19s
650:	learn: 0.0400994	total: 1m 20s	remaining: 19m 20s
716:	learn: 0.0338276	total: 1m 20s	remaining: 17m 26s
705:	learn: 0.0356179	total: 1m 20s	remaining: 17m 42s
651:	learn: 0.0399998	total: 1m 20s	remaining: 19m 19s
717:	learn: 0.0337600	total: 1m 20s	remaining: 17m 26s
684:	learn: 0.0356057	total: 1m 20s	remaining: 18m 19s
702:	learn: 0.0317429	total: 1m 20s	remaining: 17m 48s
706:	learn: 0.0355502	total: 1m 20s	remaining: 17m 42s
685:	learn: 0.0355643	total: 1m 20s	remaining: 18m 18s
718:	learn: 0.0336713	total: 1m 21s	remaining: 17m 25s
652:	learn: 0.0399103	total: 1m 20s	remaining: 19m 18s
707:	learn: 0.0354908	total: 1m 20s	remaining: 17m 41s
703:	learn: 0.0316891	total: 1m 20s	remaining: 17m 48s
686:	learn: 0.0355038	total: 1m 20s	remaining: 18m 17s
719:	learn: 0.0336040	total: 1m 21s	remaining: 17m 25s
653:	learn: 0.0398502	total: 1m 21s	remaining: 19m 18s
708:	learn: 0.0354436	total: 1m 21s	remaining: 17m 41s
704:	learn: 0.0316281	total: 1m 21s	remaining: 17m 48s
687:	learn: 0.0354268	total: 1m 21s	remaining: 18m 17s
654:	learn: 0.0397800	total: 1m 21s	remaining: 19m 17s
720:	learn: 0.0335161	total: 1m 21s	remaining: 17m 25s
709:	learn: 0.0353942	total: 1m 21s	remaining: 17m 41s
705:	learn: 0.0315786	total: 1m 21s	remaining: 17m 48s
688:	learn: 0.0353492	total: 1m 21s	remaining: 18m 17s
655:	learn: 0.0396899	total: 1m 21s	remaining: 19m 17s
710:	learn: 0.0353369	total: 1m 21s	remaining: 17m 40s
721:	learn: 0.0334767	total: 1m 21s	remaining: 17m 25s
706:	learn: 0.0315015	total: 1m 21s	remaining: 17m 47s
689:	learn: 0.0352602	total: 1m 21s	remaining: 18m 16s
711:	learn: 0.0352927	total: 1m 21s	remaining: 17m 40s
656:	learn: 0.0396271	total: 1m 21s	remaining: 19m 17s
722:	learn: 0.0333935	total: 1m 21s	remaining: 17m 24s
707:	learn: 0.0314311	total: 1m 21s	remaining: 17m 47s
690:	learn: 0.0351659	total: 1m 21s	remaining: 18m 16s
657:	learn: 0.0395265	total: 1m 21s	remaining: 19m 16s
712:	learn: 0.0352476	total: 1m 21s	remaining: 17m 40s
723:	learn: 0.0333296	total: 1m 21s	remaining: 17m 24s
708:	learn: 0.0313499	total: 1m 21s	remaining: 17m 47s
691:	learn: 0.0351059	total: 1m 21s	remaining: 18m 16s
724:	learn: 0.0332581	total: 1m 21s	remaining: 17m 24s
658:	learn: 0.0394100	total: 1m 21s	remaining: 19m 16s
713:	learn: 0.0351800	total: 1m 21s	remaining: 17m 40s
709:	learn: 0.0312865	total: 1m 21s	remaining: 17m 47s
725:	learn: 0.0331891	total: 1m 21s	remaining: 17m 23s
692:	learn: 0.0350394	total: 1m 21s	remaining: 18m 15s
659:	learn: 0.0393312	total: 1m 21s	remaining: 19m 16s
710:	learn: 0.0311982	total: 1m 21s	remaining: 17m 46s
726:	learn: 0.0331294	total: 1m 21s	remaining: 17m 23s
693:	learn: 0.0349769	total: 1m 21s	remaining: 18m 15s
715:	learn: 0.0350542	total: 1m 21s	remaining: 17m 39s
660:	learn: 0.0392396	total: 1m 21s	remaining: 19m 15s
711:	learn: 0.0311491	total: 1m 21s	remaining: 17m 46s
727:	learn: 0.0330552	total: 1m 21s	remaining: 17m 23s
694:	learn: 0.0348958	total: 1m 21s	remaining: 18m 15s
716:	learn: 0.0349804	total: 1m 21s	remaining: 17m 39s
661:	learn: 0.0391600	total: 1m 21s	remaining: 19m 15s
712:	learn: 0.0310736	total: 1m 21s	remaining: 17m 45s
728:	learn: 0.0329924	total: 1m 21s	remaining: 17m 22s
695:	learn: 0.0348282	total: 1m 21s	remaining: 18m 15s
717:	learn: 0.0349096	total: 1m 21s	remaining: 17m 38s
729:	learn: 0.0329079	total: 1m 22s	remaining: 17m 22s
713:	learn: 0.0310199	total: 1m 21s	remaining: 17m 45s
662:	learn: 0.0391005	total: 1m 22s	remaining: 19m 15s
696:	learn: 0.0347595	total: 1m 22s	remaining: 18m 15s
718:	learn: 0.0348547	total: 1m 22s	remaining: 17m 38s
730:	learn: 0.0328610	total: 1m 22s	remaining: 17m 21s
714:	learn: 0.0309325	total: 1m 22s	remaining: 17m 45s
663:	learn: 0.0390361	total: 1m 22s	remaining: 19m 15s
731:	learn: 0.0327920	total: 1m 22s	remaining: 17m 21s
697:	learn: 0.0346814	total: 1m 22s	remaining: 18m 14s
715:	learn: 0.0308740	total: 1m 22s	remaining: 17m 44s
719:	learn: 0.0348244	total: 1m 22s	remaining: 17m 38s
732:	learn: 0.0327505	total: 1m 22s	remaining: 17m 20s
664:	learn: 0.0389757	total: 1m 22s	remaining: 19m 14s
698:	learn: 0.0346114	total: 1m 22s	remaining: 18m 14s
716:	learn: 0.0308262	total: 1m 22s	remaining: 17m 44s
720:	learn: 0.0347621	total: 1m 22s	remaining: 17m 38s
733:	learn: 0.0326745	total: 1m 22s	remaining: 17m 20s
665:	learn: 0.0389057	total: 1m 22s	remaining: 19m 14s
717:	learn: 0.0307830	total: 1m 22s	remaining: 17m 43s
699:	learn: 0.0345621	total: 1m 22s	remaining: 18m 14s
721:	learn: 0.0346660	total: 1m 22s	remaining: 17m 38s
734:	learn: 0.0325915	total: 1m 22s	remaining: 17m 19s
666:	learn: 0.0388247	total: 1m 22s	remaining: 19m 14s
718:	learn: 0.0307421	total: 1m 22s	remaining: 17m 43s
735:	learn: 0.0325023	total: 1m 22s	remaining: 17m 19s
722:	learn: 0.0345693	total: 1m 22s	remaining: 17m 37s
700:	learn: 0.0345245	total: 1m 22s	remaining: 18m 14s
667:	learn: 0.0387348	total: 1m 22s	remaining: 19m 13s
719:	learn: 0.0307007	total: 1m 22s	remaining: 17m 43s
723:	learn: 0.0345294	total: 1m 22s	remaining: 17m 37s
736:	learn: 0.0324461	total: 1m 22s	remaining: 17m 19s
701:	learn: 0.0344582	total: 1m 22s	remaining: 18m 14s
720:	learn: 0.0306378	total: 1m 22s	remaining: 17m 43s
724:	learn: 0.0344618	total: 1m 22s	remaining: 17m 36s
668:	learn: 0.0386692	total: 1m 22s	remaining: 19m 13s
737:	learn: 0.0323662	total: 1m 22s	remaining: 17m 18s
702:	learn: 0.0343956	total: 1m 22s	remaining: 18m 13s
721:	learn: 0.0305561	total: 1m 22s	remaining: 17m 42s
725:	learn: 0.0343782	total: 1m 22s	remaining: 17m 36s
738:	learn: 0.0323059	total: 1m 22s	remaining: 17m 18s
669:	learn: 0.0386091	total: 1m 22s	remaining: 19m 13s
703:	learn: 0.0343230	total: 1m 22s	remaining: 18m 13s
722:	learn: 0.0305022	total: 1m 22s	remaining: 17m 42s
726:	learn: 0.0343286	total: 1m 22s	remaining: 17m 36s
739:	learn: 0.0322302	total: 1m 22s	remaining: 17m 18s
704:	learn: 0.0342770	total: 1m 22s	remaining: 18m 12s
670:	learn: 0.0385301	total: 1m 22s	remaining: 19m 13s
723:	learn: 0.0304387	total: 1m 22s	remaining: 17m 41s
727:	learn: 0.0342454	total: 1m 22s	remaining: 17m 35s
740:	learn: 0.0321753	total: 1m 23s	remaining: 17m 17s
705:	learn: 0.0342202	total: 1m 23s	remaining: 18m 12s
724:	learn: 0.0303902	total: 1m 22s	remaining: 17m 41s
671:	learn: 0.0384659	total: 1m 23s	remaining: 19m 13s
728:	learn: 0.0341360	total: 1m 23s	remaining: 17m 35s
741:	learn: 0.0321323	total: 1m 23s	remaining: 17m 17s
706:	learn: 0.0341435	total: 1m 23s	remaining: 18m 12s
725:	learn: 0.0303189	total: 1m 23s	remaining: 17m 41s
672:	learn: 0.0384037	total: 1m 23s	remaining: 19m 12s
729:	learn: 0.0340677	total: 1m 23s	remaining: 17m 35s
742:	learn: 0.0320668	total: 1m 23s	remaining: 17m 17s
707:	learn: 0.0340564	total: 1m 23s	remaining: 18m 12s
673:	learn: 0.0382808	total: 1m 23s	remaining: 19m 12s
726:	learn: 0.0302755	total: 1m 23s	remaining: 17m 41s
730:	learn: 0.0340093	total: 1m 23s	remaining: 17m 34s
743:	learn: 0.0320133	total: 1m 23s	remaining: 17m 17s
727:	learn: 0.0302109	total: 1m 23s	remaining: 17m 40s
674:	learn: 0.0382038	total: 1m 23s	remaining: 19m 11s
708:	learn: 0.0339880	total: 1m 23s	remaining: 18m 12s
731:	learn: 0.0339457	total: 1m 23s	remaining: 17m 34s
744:	learn: 0.0319756	total: 1m 23s	remaining: 17m 16s
728:	learn: 0.0301565	total: 1m 23s	remaining: 17m 40s
732:	learn: 0.0338795	total: 1m 23s	remaining: 17m 34s
709:	learn: 0.0339080	total: 1m 23s	remaining: 18m 11s
675:	learn: 0.0381236	total: 1m 23s	remaining: 19m 11s
745:	learn: 0.0319072	total: 1m 23s	remaining: 17m 16s
729:	learn: 0.0301014	total: 1m 23s	remaining: 17m 39s
733:	learn: 0.0337900	total: 1m 23s	remaining: 17m 33s
710:	learn: 0.0338595	total: 1m 23s	remaining: 18m 11s
676:	learn: 0.0380430	total: 1m 23s	remaining: 19m 11s
746:	learn: 0.0318442	total: 1m 23s	remaining: 17m 16s
730:	learn: 0.0300470	total: 1m 23s	remaining: 17m 39s
734:	learn: 0.0337340	total: 1m 23s	remaining: 17m 33s
711:	learn: 0.0337954	total: 1m 23s	remaining: 18m 11s
677:	learn: 0.0379816	total: 1m 23s	remaining: 19m 10s
731:	learn: 0.0299784	total: 1m 23s	remaining: 17m 38s
747:	learn: 0.0317630	total: 1m 23s	remaining: 17m 16s
735:	learn: 0.0336599	total: 1m 23s	remaining: 17m 33s
712:	learn: 0.0337472	total: 1m 23s	remaining: 18m 10s
732:	learn: 0.0299189	total: 1m 23s	remaining: 17m 38s
678:	learn: 0.0378980	total: 1m 23s	remaining: 19m 10s
748:	learn: 0.0316946	total: 1m 23s	remaining: 17m 16s
713:	learn: 0.0336849	total: 1m 23s	remaining: 18m 9s
736:	learn: 0.0335878	total: 1m 23s	remaining: 17m 33s
679:	learn: 0.0378240	total: 1m 23s	remaining: 19m 10s
733:	learn: 0.0298395	total: 1m 23s	remaining: 17m 38s
749:	learn: 0.0316036	total: 1m 23s	remaining: 17m 15s
714:	learn: 0.0336049	total: 1m 23s	remaining: 18m 9s
737:	learn: 0.0335069	total: 1m 23s	remaining: 17m 32s
680:	learn: 0.0377106	total: 1m 24s	remaining: 19m 9s
750:	learn: 0.0315359	total: 1m 24s	remaining: 17m 15s
734:	learn: 0.0297939	total: 1m 23s	remaining: 17m 38s
738:	learn: 0.0334571	total: 1m 23s	remaining: 17m 32s
715:	learn: 0.0335079	total: 1m 24s	remaining: 18m 9s
681:	learn: 0.0376158	total: 1m 24s	remaining: 19m 9s
751:	learn: 0.0314864	total: 1m 24s	remaining: 17m 15s
735:	learn: 0.0297392	total: 1m 24s	remaining: 17m 38s
716:	learn: 0.0334435	total: 1m 24s	remaining: 18m 9s
739:	learn: 0.0334085	total: 1m 24s	remaining: 17m 32s
682:	learn: 0.0375559	total: 1m 24s	remaining: 19m 8s
736:	learn: 0.0296837	total: 1m 24s	remaining: 17m 37s
752:	learn: 0.0314467	total: 1m 24s	remaining: 17m 15s
740:	learn: 0.0333546	total: 1m 24s	remaining: 17m 31s
717:	learn: 0.0333883	total: 1m 24s	remaining: 18m 8s
683:	learn: 0.0375041	total: 1m 24s	remaining: 19m 8s
753:	learn: 0.0314064	total: 1m 24s	remaining: 17m 14s
737:	learn: 0.0296351	total: 1m 24s	remaining: 17m 37s
741:	learn: 0.0333204	total: 1m 24s	remaining: 17m 31s
684:	learn: 0.0374180	total: 1m 24s	remaining: 19m 7s
718:	learn: 0.0333041	total: 1m 24s	remaining: 18m 8s
754:	learn: 0.0313413	total: 1m 24s	remaining: 17m 14s
738:	learn: 0.0295896	total: 1m 24s	remaining: 17m 37s
742:	learn: 0.0332707	total: 1m 24s	remaining: 17m 31s
719:	learn: 0.0332481	total: 1m 24s	remaining: 18m 8s
685:	learn: 0.0373584	total: 1m 24s	remaining: 19m 7s
755:	learn: 0.0312926	total: 1m 24s	remaining: 17m 14s
743:	learn: 0.0331873	total: 1m 24s	remaining: 17m 31s
739:	learn: 0.0295261	total: 1m 24s	remaining: 17m 37s
720:	learn: 0.0331787	total: 1m 24s	remaining: 18m 7s
756:	learn: 0.0312566	total: 1m 24s	remaining: 17m 13s
686:	learn: 0.0372862	total: 1m 24s	remaining: 19m 7s
721:	learn: 0.0331402	total: 1m 24s	remaining: 18m 7s
740:	learn: 0.0294662	total: 1m 24s	remaining: 17m 36s
744:	learn: 0.0331270	total: 1m 24s	remaining: 17m 30s

3:	learn: 0.1066516	total: 34.5s remaining: !      238687:	learn: 0.0372044	total: 1m 24s	remaining: 19m 6s
757:	learn: 0.0312153	total: 1m 24s	remaining: 17m 13s
741:	learn: 0.0294277	total: 1m 24s	remaining: 17m 36s
722:	learn: 0.0330673	total: 1m 24s	remaining: 18m 7s
745:	learn: 0.0330772	total: 1m 24s	remaining: 17m 30s
758:	learn: 0.0311607	total: 1m 24s	remaining: 17m 13s
688:	learn: 0.0371468	total: 1m 24s	remaining: 19m 6s
746:	learn: 0.0330382	total: 1m 24s	remaining: 17m 30s
742:	learn: 0.0293758	total: 1m 24s	remaining: 17m 36s
723:	learn: 0.0330116	total: 1m 24s	remaining: 18m 6s
747:	learn: 0.0329907	total: 1m 24s	remaining: 17m 29s
759:	learn: 0.0311246	total: 1m 25s	remaining: 17m 13s
724:	learn: 0.0329501	total: 1m 24s	remaining: 18m 6s
689:	learn: 0.0370544	total: 1m 24s	remaining: 19m 6s
743:	learn: 0.0293210	total: 1m 24s	remaining: 17m 36s
748:	learn: 0.0329174	total: 1m 24s	remaining: 17m 29s
760:	learn: 0.0310946	total: 1m 25s	remaining: 17m 13s
725:	learn: 0.0329053	total: 1m 25s	remaining: 18m 5s
744:	learn: 0.0292525	total: 1m 25s	remaining: 17m 35s
690:	learn: 0.0369661	total: 1m 25s	remaining: 19m 6s
749:	learn: 0.0328571	total: 1m 25s	remaining: 17m 28s
726:	learn: 0.0328412	total: 1m 25s	remaining: 18m 5s
761:	learn: 0.0310313	total: 1m 25s	remaining: 17m 12s
750:	learn: 0.0328147	total: 1m 25s	remaining: 17m 28s
745:	learn: 0.0292071	total: 1m 25s	remaining: 17m 35s
691:	learn: 0.0368914	total: 1m 25s	remaining: 19m 6s
762:	learn: 0.0309828	total: 1m 25s	remaining: 17m 12s
727:	learn: 0.0327668	total: 1m 25s	remaining: 18m 4s
751:	learn: 0.0327505	total: 1m 25s	remaining: 17m 27s
746:	learn: 0.0291617	total: 1m 25s	remaining: 17m 35s
763:	learn: 0.0309058	total: 1m 25s	remaining: 17m 12s
692:	learn: 0.0368151	total: 1m 25s	remaining: 19m 6s
728:	learn: 0.0326888	total: 1m 25s	remaining: 18m 4s
752:	learn: 0.0326930	total: 1m 25s	remaining: 17m 27s
747:	learn: 0.0291070	total: 1m 25s	remaining: 17m 35s
764:	learn: 0.0308582	total: 1m 25s	remaining: 17m 11s
729:	learn: 0.0326364	total: 1m 25s	remaining: 18m 4s
753:	learn: 0.0326527	total: 1m 25s	remaining: 17m 26s
693:	learn: 0.0367539	total: 1m 25s	remaining: 19m 6s
765:	learn: 0.0308172	total: 1m 25s	remaining: 17m 11s
748:	learn: 0.0290573	total: 1m 25s	remaining: 17m 35s
730:	learn: 0.0325866	total: 1m 25s	remaining: 18m 3s
754:	learn: 0.0325965	total: 1m 25s	remaining: 17m 26s
694:	learn: 0.0366672	total: 1m 25s	remaining: 19m 5s
731:	learn: 0.0325076	total: 1m 25s	remaining: 18m 3s
749:	learn: 0.0289777	total: 1m 25s	remaining: 17m 34s
766:	learn: 0.0307414	total: 1m 25s	remaining: 17m 11s
755:	learn: 0.0325638	total: 1m 25s	remaining: 17m 26s
695:	learn: 0.0366167	total: 1m 25s	remaining: 19m 5s
732:	learn: 0.0324503	total: 1m 25s	remaining: 18m 2s
767:	learn: 0.0306771	total: 1m 25s	remaining: 17m 11s
750:	learn: 0.0289293	total: 1m 25s	remaining: 17m 34s
756:	learn: 0.0325091	total: 1m 25s	remaining: 17m 26s
733:	learn: 0.0323645	total: 1m 25s	remaining: 18m 2s
768:	learn: 0.0306256	total: 1m 25s	remaining: 17m 10s
696:	learn: 0.0365764	total: 1m 25s	remaining: 19m 5s
751:	learn: 0.0288998	total: 1m 25s	remaining: 17m 34s
757:	learn: 0.0324583	total: 1m 25s	remaining: 17m 25s
769:	learn: 0.0305645	total: 1m 25s	remaining: 17m 10s
734:	learn: 0.0322911	total: 1m 25s	remaining: 18m 2s
697:	learn: 0.0365152	total: 1m 25s	remaining: 19m 5s
758:	learn: 0.0324082	total: 1m 25s	remaining: 17m 25s
770:	learn: 0.0305104	total: 1m 26s	remaining: 17m 9s
752:	learn: 0.0288473	total: 1m 25s	remaining: 17m 34s
735:	learn: 0.0322247	total: 1m 25s	remaining: 18m 2s
698:	learn: 0.0364277	total: 1m 26s	remaining: 19m 5s
759:	learn: 0.0323628	total: 1m 25s	remaining: 17m 25s
771:	learn: 0.0304604	total: 1m 26s	remaining: 17m 9s
753:	learn: 0.0287938	total: 1m 25s	remaining: 17m 34s
736:	learn: 0.0321615	total: 1m 26s	remaining: 18m 1s
760:	learn: 0.0323046	total: 1m 26s	remaining: 17m 24s
699:	learn: 0.0363471	total: 1m 26s	remaining: 19m 4s
754:	learn: 0.0287602	total: 1m 26s	remaining: 17m 34s
737:	learn: 0.0321049	total: 1m 26s	remaining: 18m 1s
772:	learn: 0.0304186	total: 1m 26s	remaining: 17m 9s
761:	learn: 0.0322750	total: 1m 26s	remaining: 17m 24s
700:	learn: 0.0362850	total: 1m 26s	remaining: 19m 4s
773:	learn: 0.0303558	total: 1m 26s	remaining: 17m 9s
755:	learn: 0.0287143	total: 1m 26s	remaining: 17m 34s
738:	learn: 0.0320688	total: 1m 26s	remaining: 18m
762:	learn: 0.0322105	total: 1m 26s	remaining: 17m 23s
701:	learn: 0.0362461	total: 1m 26s	remaining: 19m 4s
756:	learn: 0.0286538	total: 1m 26s	remaining: 17m 33s
739:	learn: 0.0319943	total: 1m 26s	remaining: 18m
774:	learn: 0.0302762	total: 1m 26s	remaining: 17m 9s
763:	learn: 0.0321055	total: 1m 26s	remaining: 17m 23s
757:	learn: 0.0286222	total: 1m 26s	remaining: 17m 32s
702:	learn: 0.0361905	total: 1m 26s	remaining: 19m 3s
775:	learn: 0.0302201	total: 1m 26s	remaining: 17m 8s
758:	learn: 0.0285627	total: 1m 26s	remaining: 17m 32s
740:	learn: 0.0319551	total: 1m 26s	remaining: 18m
764:	learn: 0.0320090	total: 1m 26s	remaining: 17m 23s
776:	learn: 0.0301764	total: 1m 26s	remaining: 17m 8s
759:	learn: 0.0285196	total: 1m 26s	remaining: 17m 31s
703:	learn: 0.0361231	total: 1m 26s	remaining: 19m 3s
741:	learn: 0.0319216	total: 1m 26s	remaining: 18m
765:	learn: 0.0319698	total: 1m 26s	remaining: 17m 23s
777:	learn: 0.0301355	total: 1m 26s	remaining: 17m 8s
760:	learn: 0.0284879	total: 1m 26s	remaining: 17m 31s
742:	learn: 0.0318759	total: 1m 26s	remaining: 17m 59s
704:	learn: 0.0360731	total: 1m 26s	remaining: 19m 3s
766:	learn: 0.0319135	total: 1m 26s	remaining: 17m 23s
761:	learn: 0.0284260	total: 1m 26s	remaining: 17m 30s
743:	learn: 0.0318133	total: 1m 26s	remaining: 17m 59s
778:	learn: 0.0300907	total: 1m 26s	remaining: 17m 8s
705:	learn: 0.0359826	total: 1m 26s	remaining: 19m 3s
767:	learn: 0.0318698	total: 1m 26s	remaining: 17m 23s
744:	learn: 0.0317549	total: 1m 26s	remaining: 17m 58s
762:	learn: 0.0283770	total: 1m 26s	remaining: 17m 30s
706:	learn: 0.0359147	total: 1m 26s	remaining: 19m 2s
779:	learn: 0.0300274	total: 1m 26s	remaining: 17m 8s
745:	learn: 0.0316935	total: 1m 26s	remaining: 17m 58s
768:	learn: 0.0317969	total: 1m 26s	remaining: 17m 23s
763:	learn: 0.0283015	total: 1m 26s	remaining: 17m 30s
707:	learn: 0.0358375	total: 1m 27s	remaining: 19m 2s
746:	learn: 0.0316426	total: 1m 26s	remaining: 17m 57s
780:	learn: 0.0299489	total: 1m 27s	remaining: 17m 8s
769:	learn: 0.0317490	total: 1m 26s	remaining: 17m 22s
764:	learn: 0.0282578	total: 1m 27s	remaining: 17m 30s
747:	learn: 0.0315862	total: 1m 27s	remaining: 17m 56s
708:	learn: 0.0357801	total: 1m 27s	remaining: 19m 1s
781:	learn: 0.0298967	total: 1m 27s	remaining: 17m 7s
770:	learn: 0.0316996	total: 1m 27s	remaining: 17m 22s
765:	learn: 0.0282210	total: 1m 27s	remaining: 17m 30s
748:	learn: 0.0315242	total: 1m 27s	remaining: 17m 56s
709:	learn: 0.0357360	total: 1m 27s	remaining: 19m 1s
782:	learn: 0.0298560	total: 1m 27s	remaining: 17m 7s
766:	learn: 0.0281746	total: 1m 27s	remaining: 17m 29s
771:	learn: 0.0316389	total: 1m 27s	remaining: 17m 22s
749:	learn: 0.0314603	total: 1m 27s	remaining: 17m 56s
710:	learn: 0.0356686	total: 1m 27s	remaining: 19m 1s
783:	learn: 0.0298186	total: 1m 27s	remaining: 17m 7s
767:	learn: 0.0281193	total: 1m 27s	remaining: 17m 29s
772:	learn: 0.0316067	total: 1m 27s	remaining: 17m 22s
750:	learn: 0.0313938	total: 1m 27s	remaining: 17m 55s
711:	learn: 0.0356187	total: 1m 27s	remaining: 19m
768:	learn: 0.0280629	total: 1m 27s	remaining: 17m 28s
784:	learn: 0.0297713	total: 1m 27s	remaining: 17m 7s
773:	learn: 0.0315214	total: 1m 27s	remaining: 17m 21s
751:	learn: 0.0313457	total: 1m 27s	remaining: 17m 55s
712:	learn: 0.0355604	total: 1m 27s	remaining: 19m
769:	learn: 0.0280103	total: 1m 27s	remaining: 17m 28s
774:	learn: 0.0314705	total: 1m 27s	remaining: 17m 21s
785:	learn: 0.0297166	total: 1m 27s	remaining: 17m 7s
752:	learn: 0.0312822	total: 1m 27s	remaining: 17m 55s
713:	learn: 0.0354999	total: 1m 27s	remaining: 18m 59s
775:	learn: 0.0314418	total: 1m 27s	remaining: 17m 21s
786:	learn: 0.0296815	total: 1m 27s	remaining: 17m 7s
770:	learn: 0.0279550	total: 1m 27s	remaining: 17m 28s
753:	learn: 0.0312364	total: 1m 27s	remaining: 17m 54s

714:	learn: 0.0354142	total: 1m 27s	remaining: 18m 59s
787:	learn: 0.0296145	total: 1m 27s	remaining: 17m 6s
771:	learn: 0.0279070	total: 1m 27s	remaining: 17m 28s
776:	learn: 0.0313544	total: 1m 27s	remaining: 17m 21s
754:	learn: 0.0311874	total: 1m 27s	remaining: 17m 54s
715:	learn: 0.0353500	total: 1m 27s	remaining: 18m 59s
788:	learn: 0.0295577	total: 1m 27s	remaining: 17m 6s
772:	learn: 0.0278449	total: 1m 27s	remaining: 17m 28s
777:	learn: 0.0313058	total: 1m 27s	remaining: 17m 20s
755:	learn: 0.0311167	total: 1m 27s	remaining: 17m 54s
716:	learn: 0.0352779	total: 1m 27s	remaining: 18m 58s
778:	learn: 0.0312478	total: 1m 27s	remaining: 17m 20s
789:	learn: 0.0294912	total: 1m 28s	remaining: 17m 6s
773:	learn: 0.0277855	total: 1m 27s	remaining: 17m 27s
756:	learn: 0.0310269	total: 1m 27s	remaining: 17m 53s
717:	learn: 0.0352250	total: 1m 28s	remaining: 18m 58s
790:	learn: 0.0294459	total: 1m 28s	remaining: 17m 5s
779:	learn: 0.0311798	total: 1m 27s	remaining: 17m 20s
757:	learn: 0.0309714	total: 1m 28s	remaining: 17m 53s
774:	learn: 0.0277351	total: 1m 28s	remaining: 17m 27s
718:	learn: 0.0351797	total: 1m 28s	remaining: 18m 58s
791:	learn: 0.0293954	total: 1m 28s	remaining: 17m 5s
780:	learn: 0.0311077	total: 1m 28s	remaining: 17m 20s
775:	learn: 0.0276883	total: 1m 28s	remaining: 17m 27s
758:	learn: 0.0309127	total: 1m 28s	remaining: 17m 53s
719:	learn: 0.0351238	total: 1m 28s	remaining: 18m 57s
792:	learn: 0.0293389	total: 1m 28s	remaining: 17m 5s
759:	learn: 0.0308682	total: 1m 28s	remaining: 17m 52s
776:	learn: 0.0276351	total: 1m 28s	remaining: 17m 27s
781:	learn: 0.0310607	total: 1m 28s	remaining: 17m 20s
720:	learn: 0.0350287	total: 1m 28s	remaining: 18m 57s
793:	learn: 0.0292861	total: 1m 28s	remaining: 17m 4s
760:	learn: 0.0308117	total: 1m 28s	remaining: 17m 52s
782:	learn: 0.0310141	total: 1m 28s	remaining: 17m 19s
777:	learn: 0.0275811	total: 1m 28s	remaining: 17m 27s
794:	learn: 0.0292218	total: 1m 28s	remaining: 17m 4s
721:	learn: 0.0349374	total: 1m 28s	remaining: 18m 56s
761:	learn: 0.0307783	total: 1m 28s	remaining: 17m 52s
778:	learn: 0.0275429	total: 1m 28s	remaining: 17m 26s
783:	learn: 0.0309574	total: 1m 28s	remaining: 17m 19s
795:	learn: 0.0291826	total: 1m 28s	remaining: 17m 4s
722:	learn: 0.0348773	total: 1m 28s	remaining: 18m 56s
762:	learn: 0.0307352	total: 1m 28s	remaining: 17m 51s
796:	learn: 0.0291384	total: 1m 28s	remaining: 17m 3s
779:	learn: 0.0275173	total: 1m 28s	remaining: 17m 26s
784:	learn: 0.0308913	total: 1m 28s	remaining: 17m 19s
723:	learn: 0.0348084	total: 1m 28s	remaining: 18m 56s
763:	learn: 0.0306528	total: 1m 28s	remaining: 17m 51s
797:	learn: 0.0290704	total: 1m 28s	remaining: 17m 3s
780:	learn: 0.0274432	total: 1m 28s	remaining: 17m 26s
785:	learn: 0.0308477	total: 1m 28s	remaining: 17m 19s
724:	learn: 0.0347309	total: 1m 28s	remaining: 18m 55s
798:	learn: 0.0290126	total: 1m 28s	remaining: 17m 3s
781:	learn: 0.0273874	total: 1m 28s	remaining: 17m 25s
764:	learn: 0.0306126	total: 1m 28s	remaining: 17m 51s
786:	learn: 0.0308072	total: 1m 28s	remaining: 17m 19s
725:	learn: 0.0346584	total: 1m 28s	remaining: 18m 55s
799:	learn: 0.0289502	total: 1m 28s	remaining: 17m 2s
782:	learn: 0.0273211	total: 1m 28s	remaining: 17m 25s
787:	learn: 0.0307389	total: 1m 28s	remaining: 17m 18s
765:	learn: 0.0305708	total: 1m 28s	remaining: 17m 51s
726:	learn: 0.0345887	total: 1m 28s	remaining: 18m 55s
783:	learn: 0.0272888	total: 1m 28s	remaining: 17m 25s
766:	learn: 0.0305151	total: 1m 28s	remaining: 17m 51s
800:	learn: 0.0288923	total: 1m 29s	remaining: 17m 3s
788:	learn: 0.0306876	total: 1m 28s	remaining: 17m 18s
727:	learn: 0.0345282	total: 1m 29s	remaining: 18m 54s
784:	learn: 0.0272468	total: 1m 29s	remaining: 17m 25s
801:	learn: 0.0288388	total: 1m 29s	remaining: 17m 2s
789:	learn: 0.0306437	total: 1m 29s	remaining: 17m 18s
767:	learn: 0.0304552	total: 1m 29s	remaining: 17m 51s
728:	learn: 0.0344421	total: 1m 29s	remaining: 18m 54s
790:	learn: 0.0305933	total: 1m 29s	remaining: 17m 17s
785:	learn: 0.0271722	total: 1m 29s	remaining: 17m 24s
802:	learn: 0.0287843	total: 1m 29s	remaining: 17m 2s
768:	learn: 0.0304152	total: 1m 29s	remaining: 17m 51s
791:	learn: 0.0305288	total: 1m 29s	remaining: 17m 17s
803:	learn: 0.0287302	total: 1m 29s	remaining: 17m 2s
729:	learn: 0.0343634	total: 1m 29s	remaining: 18m 54s
786:	learn: 0.0271200	total: 1m 29s	remaining: 17m 24s
769:	learn: 0.0303527	total: 1m 29s	remaining: 17m 50s
792:	learn: 0.0304702	total: 1m 29s	remaining: 17m 16s
804:	learn: 0.0286623	total: 1m 29s	remaining: 17m 1s
730:	learn: 0.0342918	total: 1m 29s	remaining: 18m 53s
787:	learn: 0.0270876	total: 1m 29s	remaining: 17m 24s
770:	learn: 0.0302884	total: 1m 29s	remaining: 17m 50s
793:	learn: 0.0304264	total: 1m 29s	remaining: 17m 16s
805:	learn: 0.0286182	total: 1m 29s	remaining: 17m 1s
731:	learn: 0.0342061	total: 1m 29s	remaining: 18m 53s
788:	learn: 0.0270220	total: 1m 29s	remaining: 17m 24s
806:	learn: 0.0285686	total: 1m 29s	remaining: 17m 1s
771:	learn: 0.0302362	total: 1m 29s	remaining: 17m 50s
789:	learn: 0.0269680	total: 1m 29s	remaining: 17m 23s
794:	learn: 0.0303567	total: 1m 29s	remaining: 17m 16s
732:	learn: 0.0341533	total: 1m 29s	remaining: 18m 53s
807:	learn: 0.0285089	total: 1m 29s	remaining: 17m
772:	learn: 0.0301953	total: 1m 29s	remaining: 17m 49s
790:	learn: 0.0269223	total: 1m 29s	remaining: 17m 23s
795:	learn: 0.0302784	total: 1m 29s	remaining: 17m 16s
733:	learn: 0.0340571	total: 1m 29s	remaining: 18m 53s
808:	learn: 0.0284628	total: 1m 29s	remaining: 17m
773:	learn: 0.0301219	total: 1m 29s	remaining: 17m 49s
791:	learn: 0.0268877	total: 1m 29s	remaining: 17m 23s
796:	learn: 0.0302274	total: 1m 29s	remaining: 17m 16s
734:	learn: 0.0339773	total: 1m 29s	remaining: 18m 52s
809:	learn: 0.0283956	total: 1m 29s	remaining: 17m
774:	learn: 0.0300670	total: 1m 29s	remaining: 17m 49s
792:	learn: 0.0268349	total: 1m 29s	remaining: 17m 23s
810:	learn: 0.0283464	total: 1m 29s	remaining: 16m 59s
797:	learn: 0.0301821	total: 1m 29s	remaining: 17m 16s
735:	learn: 0.0339077	total: 1m 29s	remaining: 18m 52s
775:	learn: 0.0300261	total: 1m 29s	remaining: 17m 49s
811:	learn: 0.0283122	total: 1m 30s	remaining: 16m 59s
793:	learn: 0.0267936	total: 1m 29s	remaining: 17m 22s
736:	learn: 0.0338282	total: 1m 30s	remaining: 18m 51s
798:	learn: 0.0301297	total: 1m 29s	remaining: 17m 16s
776:	learn: 0.0299882	total: 1m 30s	remaining: 17m 48s
794:	learn: 0.0267419	total: 1m 30s	remaining: 17m 22s
812:	learn: 0.0282512	total: 1m 30s	remaining: 16m 59s
799:	learn: 0.0300810	total: 1m 30s	remaining: 17m 15s
777:	learn: 0.0298999	total: 1m 30s	remaining: 17m 48s
737:	learn: 0.0337740	total: 1m 30s	remaining: 18m 51s
795:	learn: 0.0266829	total: 1m 30s	remaining: 17m 22s
813:	learn: 0.0281899	total: 1m 30s	remaining: 16m 58s
800:	learn: 0.0300205	total: 1m 30s	remaining: 17m 15s
738:	learn: 0.0337037	total: 1m 30s	remaining: 18m 51s
778:	learn: 0.0298392	total: 1m 30s	remaining: 17m 48s
796:	learn: 0.0266302	total: 1m 30s	remaining: 17m 21s
814:	learn: 0.0281321	total: 1m 30s	remaining: 16m 58s
801:	learn: 0.0299625	total: 1m 30s	remaining: 17m 15s
779:	learn: 0.0298133	total: 1m 30s	remaining: 17m 47s
739:	learn: 0.0336504	total: 1m 30s	remaining: 18m 51s
815:	learn: 0.0280791	total: 1m 30s	remaining: 16m 58s
802:	learn: 0.0299202	total: 1m 30s	remaining: 17m 14s
797:	learn: 0.0265915	total: 1m 30s	remaining: 17m 21s
780:	learn: 0.0297575	total: 1m 30s	remaining: 17m 47s
816:	learn: 0.0280303	total: 1m 30s	remaining: 16m 57s
798:	learn: 0.0265571	total: 1m 30s	remaining: 17m 21s
740:	learn: 0.0336024	total: 1m 30s	remaining: 18m 51s
803:	learn: 0.0298807	total: 1m 30s	remaining: 17m 14s
799:	learn: 0.0265177	total: 1m 30s	remaining: 17m 20s
781:	learn: 0.0296857	total: 1m 30s	remaining: 17m 47s
817:	learn: 0.0279812	total: 1m 30s	remaining: 16m 57s
804:	learn: 0.0298246	total: 1m 30s	remaining: 17m 14s
741:	learn: 0.0335476	total: 1m 30s	remaining: 18m 50s
800:	learn: 0.0264735	total: 1m 30s	remaining: 17m 20s
818:	learn: 0.0279333	total: 1m 30s	remaining: 16m 57s
782:	learn: 0.0296225	total: 1m 30s	remaining: 17m 47s
742:	learn: 0.0334604	total: 1m 30s	remaining: 18m 50s
805:	learn: 0.0297806	total: 1m 30s	remaining: 17m 14s
801:	learn: 0.0264227	total: 1m 30s	remaining: 17m 20s
819:	learn: 0.0278925	total: 1m 30s	remaining: 16m 57s
783:	learn: 0.0295740	total: 1m 30s	remaining: 17m 46s
743:	learn: 0.0334089	total: 1m 30s	remaining: 18m 50s
802:	learn: 0.0263788	total: 1m 30s	remaining: 17m 19s
806:	learn: 0.0297279	total: 1m 30s	remaining: 17m 14s
820:	learn: 0.0278572	total: 1m 30s	remaining: 16m 56s
784:	learn: 0.0295107	total: 1m 30s	remaining: 17m 46s
821:	learn: 0.0278377	total: 1m 31s	remaining: 16m 56s
803:	learn: 0.0263364	total: 1m 30s	remaining: 17m 19s
744:	learn: 0.0333421	total: 1m 30s	remaining: 18m 50s
807:	learn: 0.0296914	total: 1m 30s	remaining: 17m 14s
822:	learn: 0.0277884	total: 1m 31s	remaining: 16m 55s
785:	learn: 0.0294694	total: 1m 31s	remaining: 17m 46s
804:	learn: 0.0262839	total: 1m 30s	remaining: 17m 19s
808:	learn: 0.0296368	total: 1m 31s	remaining: 17m 13s
745:	learn: 0.0333119	total: 1m 31s	remaining: 18m 50s
823:	learn: 0.0277383	total: 1m 31s	remaining: 16m 55s
786:	learn: 0.0294259	total: 1m 31s	remaining: 17m 46s
805:	learn: 0.0262583	total: 1m 31s	remaining: 17m 18s
809:	learn: 0.0295813	total: 1m 31s	remaining: 17m 13s
746:	learn: 0.0332555	total: 1m 31s	remaining: 18m 49s
787:	learn: 0.0293629	total: 1m 31s	remaining: 17m 45s
824:	learn: 0.0276720	total: 1m 31s	remaining: 16m 55s
806:	learn: 0.0262251	total: 1m 31s	remaining: 17m 18s
810:	learn: 0.0295173	total: 1m 31s	remaining: 17m 13s
788:	learn: 0.0292988	total: 1m 31s	remaining: 17m 45s
747:	learn: 0.0331882	total: 1m 31s	remaining: 18m 50s
807:	learn: 0.0261874	total: 1m 31s	remaining: 17m 18s
811:	learn: 0.0294812	total: 1m 31s	remaining: 17m 12s
825:	learn: 0.0276056	total: 1m 31s	remaining: 16m 55s
789:	learn: 0.0292243	total: 1m 31s	remaining: 17m 45s
808:	learn: 0.0261338	total: 1m 31s	remaining: 17m 17s
748:	learn: 0.0331302	total: 1m 31s	remaining: 18m 49s
826:	learn: 0.0275360	total: 1m 31s	remaining: 16m 55s
812:	learn: 0.0294190	total: 1m 31s	remaining: 17m 12s
790:	learn: 0.0291834	total: 1m 31s	remaining: 17m 44s
809:	learn: 0.0260940	total: 1m 31s	remaining: 17m 17s
827:	learn: 0.0274703	total: 1m 31s	remaining: 16m 55s
749:	learn: 0.0330621	total: 1m 31s	remaining: 18m 49s
813:	learn: 0.0293836	total: 1m 31s	remaining: 17m 12s
791:	learn: 0.0291317	total: 1m 31s	remaining: 17m 44s
810:	learn: 0.0260586	total: 1m 31s	remaining: 17m 17s
750:	learn: 0.0330218	total: 1m 31s	remaining: 18m 48s
814:	learn: 0.0293250	total: 1m 31s	remaining: 17m 12s
828:	learn: 0.0274295	total: 1m 31s	remaining: 16m 55s
792:	learn: 0.0290891	total: 1m 31s	remaining: 17m 44s
811:	learn: 0.0260122	total: 1m 31s	remaining: 17m 16s
751:	learn: 0.0329755	total: 1m 31s	remaining: 18m 48s
815:	learn: 0.0292712	total: 1m 31s	remaining: 17m 11s
829:	learn: 0.0273972	total: 1m 31s	remaining: 16m 54s
793:	learn: 0.0290452	total: 1m 31s	remaining: 17m 44s
752:	learn: 0.0329106	total: 1m 31s	remaining: 18m 47s
816:	learn: 0.0292342	total: 1m 31s	remaining: 17m 11s
812:	learn: 0.0259686	total: 1m 31s	remaining: 17m 16s
830:	learn: 0.0273393	total: 1m 31s	remaining: 16m 54s
753:	learn: 0.0328600	total: 1m 31s	remaining: 18m 47s
817:	learn: 0.0291948	total: 1m 31s	remaining: 17m 11s
813:	learn: 0.0259288	total: 1m 31s	remaining: 17m 16s
794:	learn: 0.0289800	total: 1m 31s	remaining: 17m 44s
831:	learn: 0.0272944	total: 1m 32s	remaining: 16m 54s
818:	learn: 0.0291441	total: 1m 31s	remaining: 17m 10s
795:	learn: 0.0289196	total: 1m 31s	remaining: 17m 43s
754:	learn: 0.0328066	total: 1m 32s	remaining: 18m 47s
814:	learn: 0.0258845	total: 1m 31s	remaining: 17m 16s
832:	learn: 0.0272461	total: 1m 32s	remaining: 16m 54s
819:	learn: 0.0290809	total: 1m 32s	remaining: 17m 10s
815:	learn: 0.0258354	total: 1m 32s	remaining: 17m 16s
796:	learn: 0.0288626	total: 1m 32s	remaining: 17m 43s
755:	learn: 0.0327485	total: 1m 32s	remaining: 18m 46s
820:	learn: 0.0290324	total: 1m 32s	remaining: 17m 9s
833:	learn: 0.0271774	total: 1m 32s	remaining: 16m 54s
816:	learn: 0.0258017	total: 1m 32s	remaining: 17m 15s
797:	learn: 0.0288115	total: 1m 32s	remaining: 17m 43s
756:	learn: 0.0326372	total: 1m 32s	remaining: 18m 47s
834:	learn: 0.0271246	total: 1m 32s	remaining: 16m 53s
821:	learn: 0.0289773	total: 1m 32s	remaining: 17m 9s
798:	learn: 0.0287448	total: 1m 32s	remaining: 17m 42s
817:	learn: 0.0257748	total: 1m 32s	remaining: 17m 15s
835:	learn: 0.0270861	total: 1m 32s	remaining: 16m 53s
757:	learn: 0.0325648	total: 1m 32s	remaining: 18m 46s
818:	learn: 0.0257190	total: 1m 32s	remaining: 17m 15s
799:	learn: 0.0286858	total: 1m 32s	remaining: 17m 42s
822:	learn: 0.0289174	total: 1m 32s	remaining: 17m 9s
758:	learn: 0.0325027	total: 1m 32s	remaining: 18m 46s
836:	learn: 0.0270335	total: 1m 32s	remaining: 16m 53s
800:	learn: 0.0286125	total: 1m 32s	remaining: 17m 42s
819:	learn: 0.0256758	total: 1m 32s	remaining: 17m 15s
823:	learn: 0.0288795	total: 1m 32s	remaining: 17m 9s
759:	learn: 0.0324342	total: 1m 32s	remaining: 18m 45s
837:	learn: 0.0269935	total: 1m 32s	remaining: 16m 53s
820:	learn: 0.0256254	total: 1m 32s	remaining: 17m 14s
801:	learn: 0.0285687	total: 1m 32s	remaining: 17m 41s
824:	learn: 0.0288179	total: 1m 32s	remaining: 17m 9s
760:	learn: 0.0323887	total: 1m 32s	remaining: 18m 45s
821:	learn: 0.0255926	total: 1m 32s	remaining: 17m 14s
838:	learn: 0.0269526	total: 1m 32s	remaining: 16m 52s
802:	learn: 0.0285147	total: 1m 32s	remaining: 17m 41s
761:	learn: 0.0323526	total: 1m 32s	remaining: 18m 44s
825:	learn: 0.0287643	total: 1m 32s	remaining: 17m 9s
822:	learn: 0.0255424	total: 1m 32s	remaining: 17m 13s
839:	learn: 0.0269205	total: 1m 32s	remaining: 16m 52s
803:	learn: 0.0284864	total: 1m 32s	remaining: 17m 41s
762:	learn: 0.0323034	total: 1m 32s	remaining: 18m 44s
826:	learn: 0.0287343	total: 1m 32s	remaining: 17m 9s
823:	learn: 0.0255113	total: 1m 32s	remaining: 17m 13s
840:	learn: 0.0268662	total: 1m 32s	remaining: 16m 52s
804:	learn: 0.0284223	total: 1m 32s	remaining: 17m 41s
763:	learn: 0.0322013	total: 1m 32s	remaining: 18m 43s
827:	learn: 0.0287057	total: 1m 32s	remaining: 17m 9s
824:	learn: 0.0254374	total: 1m 32s	remaining: 17m 13s
841:	learn: 0.0268149	total: 1m 33s	remaining: 16m 52s
805:	learn: 0.0283946	total: 1m 32s	remaining: 17m 40s
764:	learn: 0.0321458	total: 1m 33s	remaining: 18m 43s
828:	learn: 0.0286623	total: 1m 32s	remaining: 17m 8s
825:	learn: 0.0254055	total: 1m 33s	remaining: 17m 13s
842:	learn: 0.0267618	total: 1m 33s	remaining: 16m 52s
806:	learn: 0.0283538	total: 1m 33s	remaining: 17m 40s
829:	learn: 0.0286026	total: 1m 33s	remaining: 17m 8s
765:	learn: 0.0320955	total: 1m 33s	remaining: 18m 43s
826:	learn: 0.0253640	total: 1m 33s	remaining: 17m 12s
843:	learn: 0.0266930	total: 1m 33s	remaining: 16m 51s
830:	learn: 0.0285598	total: 1m 33s	remaining: 17m 8s
807:	learn: 0.0283125	total: 1m 33s	remaining: 17m 40s
766:	learn: 0.0320451	total: 1m 33s	remaining: 18m 43s
827:	learn: 0.0253315	total: 1m 33s	remaining: 17m 12s
831:	learn: 0.0285019	total: 1m 33s	remaining: 17m 7s
808:	learn: 0.0282861	total: 1m 33s	remaining: 17m 39s
844:	learn: 0.0266456	total: 1m 33s	remaining: 16m 52s
767:	learn: 0.0319951	total: 1m 33s	remaining: 18m 42s
828:	learn: 0.0253048	total: 1m 33s	remaining: 17m 12s
832:	learn: 0.0284783	total: 1m 33s	remaining: 17m 7s
809:	learn: 0.0282133	total: 1m 33s	remaining: 17m 39s
845:	learn: 0.0265998	total: 1m 33s	remaining: 16m 51s
829:	learn: 0.0252823	total: 1m 33s	remaining: 17m 11s
768:	learn: 0.0319265	total: 1m 33s	remaining: 18m 42s
833:	learn: 0.0284336	total: 1m 33s	remaining: 17m 6s
810:	learn: 0.0281798	total: 1m 33s	remaining: 17m 39s
846:	learn: 0.0265638	total: 1m 33s	remaining: 16m 51s
830:	learn: 0.0252480	total: 1m 33s	remaining: 17m 11s
811:	learn: 0.0281233	total: 1m 33s	remaining: 17m 38s
769:	learn: 0.0318461	total: 1m 33s	remaining: 18m 42s
834:	learn: 0.0283980	total: 1m 33s	remaining: 17m 6s
847:	learn: 0.0265206	total: 1m 33s	remaining: 16m 51s
831:	learn: 0.0252053	total: 1m 33s	remaining: 17m 11s
770:	learn: 0.0318051	total: 1m 33s	remaining: 18m 42s
832:	learn: 0.0251460	total: 1m 33s	remaining: 17m 10s
835:	learn: 0.0283660	total: 1m 33s	remaining: 17m 6s

812:	learn: 0.0280962	total: 1m 33s	remaining: 17m 38s
848:	learn: 0.0264530	total: 1m 33s	remaining: 16m 51s
813:	learn: 0.0280507	total: 1m 33s	remaining: 17m 38s
771:	learn: 0.0317552	total: 1m 33s	remaining: 18m 41s
849:	learn: 0.0264179	total: 1m 33s	remaining: 16m 51s
833:	learn: 0.0251076	total: 1m 33s	remaining: 17m 10s
836:	learn: 0.0283277	total: 1m 33s	remaining: 17m 7s
814:	learn: 0.0280145	total: 1m 33s	remaining: 17m 37s
772:	learn: 0.0317151	total: 1m 33s	remaining: 18m 41s
850:	learn: 0.0263619	total: 1m 34s	remaining: 16m 50s
834:	learn: 0.0250835	total: 1m 33s	remaining: 17m 10s
837:	learn: 0.0282756	total: 1m 33s	remaining: 17m 6s
815:	learn: 0.0279599	total: 1m 33s	remaining: 17m 37s
851:	learn: 0.0263070	total: 1m 34s	remaining: 16m 50s
773:	learn: 0.0316471	total: 1m 34s	remaining: 18m 41s
835:	learn: 0.0250434	total: 1m 33s	remaining: 17m 10s
838:	learn: 0.0282316	total: 1m 34s	remaining: 17m 6s
852:	learn: 0.0262571	total: 1m 34s	remaining: 16m 49s
816:	learn: 0.0279047	total: 1m 34s	remaining: 17m 37s
836:	learn: 0.0249874	total: 1m 34s	remaining: 17m 9s
774:	learn: 0.0315652	total: 1m 34s	remaining: 18m 41s
853:	learn: 0.0262104	total: 1m 34s	remaining: 16m 49s
839:	learn: 0.0281772	total: 1m 34s	remaining: 17m 6s
817:	learn: 0.0278640	total: 1m 34s	remaining: 17m 37s
837:	learn: 0.0249318	total: 1m 34s	remaining: 17m 9s
775:	learn: 0.0315280	total: 1m 34s	remaining: 18m 40s
854:	learn: 0.0261683	total: 1m 34s	remaining: 16m 49s
840:	learn: 0.0281345	total: 1m 34s	remaining: 17m 6s
818:	learn: 0.0278044	total: 1m 34s	remaining: 17m 37s
838:	learn: 0.0248993	total: 1m 34s	remaining: 17m 9s
776:	learn: 0.0314581	total: 1m 34s	remaining: 18m 40s
855:	learn: 0.0261041	total: 1m 34s	remaining: 16m 48s
841:	learn: 0.0280628	total: 1m 34s	remaining: 17m 6s
777:	learn: 0.0313917	total: 1m 34s	remaining: 18m 39s
819:	learn: 0.0277609	total: 1m 34s	remaining: 17m 36s
839:	learn: 0.0248586	total: 1m 34s	remaining: 17m 9s
856:	learn: 0.0260656	total: 1m 34s	remaining: 16m 48s
842:	learn: 0.0280127	total: 1m 34s	remaining: 17m 5s
820:	learn: 0.0277177	total: 1m 34s	remaining: 17m 36s
778:	learn: 0.0313494	total: 1m 34s	remaining: 18m 39s
840:	learn: 0.0248168	total: 1m 34s	remaining: 17m 9s
857:	learn: 0.0260203	total: 1m 34s	remaining: 16m 48s
843:	learn: 0.0279548	total: 1m 34s	remaining: 17m 5s
821:	learn: 0.0276615	total: 1m 34s	remaining: 17m 36s
779:	learn: 0.0313086	total: 1m 34s	remaining: 18m 39s
841:	learn: 0.0247712	total: 1m 34s	remaining: 17m 8s
858:	learn: 0.0259853	total: 1m 34s	remaining: 16m 48s
844:	learn: 0.0279066	total: 1m 34s	remaining: 17m 5s
822:	learn: 0.0276195	total: 1m 34s	remaining: 17m 35s
842:	learn: 0.0247228	total: 1m 34s	remaining: 17m 8s
780:	learn: 0.0312442	total: 1m 34s	remaining: 18m 38s
859:	learn: 0.0259531	total: 1m 34s	remaining: 16m 47s
823:	learn: 0.0275753	total: 1m 34s	remaining: 17m 35s
845:	learn: 0.0278524	total: 1m 34s	remaining: 17m 5s
843:	learn: 0.0246702	total: 1m 34s	remaining: 17m 8s
860:	learn: 0.0259048	total: 1m 34s	remaining: 16m 47s
781:	learn: 0.0311739	total: 1m 34s	remaining: 18m 38s
846:	learn: 0.0277953	total: 1m 34s	remaining: 17m 5s
824:	learn: 0.0275472	total: 1m 34s	remaining: 17m 35s
844:	learn: 0.0246352	total: 1m 34s	remaining: 17m 8s
861:	learn: 0.0258599	total: 1m 35s	remaining: 16m 47s
847:	learn: 0.0277386	total: 1m 34s	remaining: 17m 4s
782:	learn: 0.0311146	total: 1m 35s	remaining: 18m 38s
825:	learn: 0.0275061	total: 1m 34s	remaining: 17m 34s
848:	learn: 0.0276947	total: 1m 35s	remaining: 17m 4s
862:	learn: 0.0258336	total: 1m 35s	remaining: 16m 47s
845:	learn: 0.0245979	total: 1m 35s	remaining: 17m 8s
783:	learn: 0.0310566	total: 1m 35s	remaining: 18m 38s
826:	learn: 0.0274726	total: 1m 35s	remaining: 17m 34s
846:	learn: 0.0245456	total: 1m 35s	remaining: 17m 7s
863:	learn: 0.0257999	total: 1m 35s	remaining: 16m 46s
849:	learn: 0.0276482	total: 1m 35s	remaining: 17m 4s
827:	learn: 0.0274272	total: 1m 35s	remaining: 17m 34s
784:	learn: 0.0310021	total: 1m 35s	remaining: 18m 38s
847:	learn: 0.0244998	total: 1m 35s	remaining: 17m 7s
864:	learn: 0.0257573	total: 1m 35s	remaining: 16m 46s
850:	learn: 0.0276028	total: 1m 35s	remaining: 17m 3s
828:	learn: 0.0273883	total: 1m 35s	remaining: 17m 34s
848:	learn: 0.0244775	total: 1m 35s	remaining: 17m 6s
785:	learn: 0.0309527	total: 1m 35s	remaining: 18m 38s
865:	learn: 0.0257023	total: 1m 35s	remaining: 16m 46s
851:	learn: 0.0275689	total: 1m 35s	remaining: 17m 3s
786:	learn: 0.0309034	total: 1m 35s	remaining: 18m 37s
849:	learn: 0.0244212	total: 1m 35s	remaining: 17m 6s
866:	learn: 0.0256568	total: 1m 35s	remaining: 16m 45s
829:	learn: 0.0273548	total: 1m 35s	remaining: 17m 34s
852:	learn: 0.0275290	total: 1m 35s	remaining: 17m 3s
850:	learn: 0.0243875	total: 1m 35s	remaining: 17m 6s
867:	learn: 0.0256237	total: 1m 35s	remaining: 16m 45s
787:	learn: 0.0308405	total: 1m 35s	remaining: 18m 37s
830:	learn: 0.0273117	total: 1m 35s	remaining: 17m 34s
851:	learn: 0.0243400	total: 1m 35s	remaining: 17m 5s
853:	learn: 0.0274777	total: 1m 35s	remaining: 17m 3s
788:	learn: 0.0307768	total: 1m 35s	remaining: 18m 36s
868:	learn: 0.0255534	total: 1m 35s	remaining: 16m 45s
831:	learn: 0.0272680	total: 1m 35s	remaining: 17m 33s
852:	learn: 0.0242973	total: 1m 35s	remaining: 17m 5s
854:	learn: 0.0274135	total: 1m 35s	remaining: 17m 2s
869:	learn: 0.0255270	total: 1m 35s	remaining: 16m 45s
789:	learn: 0.0307280	total: 1m 35s	remaining: 18m 36s
832:	learn: 0.0272410	total: 1m 35s	remaining: 17m 33s
853:	learn: 0.0242621	total: 1m 35s	remaining: 17m 5s
855:	learn: 0.0273760	total: 1m 35s	remaining: 17m 2s
870:	learn: 0.0254788	total: 1m 35s	remaining: 16m 45s
790:	learn: 0.0306830	total: 1m 35s	remaining: 18m 36s
833:	learn: 0.0271906	total: 1m 35s	remaining: 17m 33s
854:	learn: 0.0242032	total: 1m 35s	remaining: 17m 5s
856:	learn: 0.0273274	total: 1m 35s	remaining: 17m 2s
871:	learn: 0.0254503	total: 1m 35s	remaining: 16m 44s
791:	learn: 0.0306454	total: 1m 35s	remaining: 18m 35s
834:	learn: 0.0271292	total: 1m 35s	remaining: 17m 33s
855:	learn: 0.0241702	total: 1m 35s	remaining: 17m 4s
857:	learn: 0.0272756	total: 1m 35s	remaining: 17m 2s
872:	learn: 0.0254182	total: 1m 36s	remaining: 16m 44s
792:	learn: 0.0305693	total: 1m 36s	remaining: 18m 35s
835:	learn: 0.0270939	total: 1m 36s	remaining: 17m 33s
856:	learn: 0.0241277	total: 1m 36s	remaining: 17m 4s
858:	learn: 0.0272030	total: 1m 36s	remaining: 17m 2s
873:	learn: 0.0253840	total: 1m 36s	remaining: 16m 44s
793:	learn: 0.0305280	total: 1m 36s	remaining: 18m 35s
836:	learn: 0.0270578	total: 1m 36s	remaining: 17m 32s
859:	learn: 0.0271698	total: 1m 36s	remaining: 17m 1s
857:	learn: 0.0240817	total: 1m 36s	remaining: 17m 4s
874:	learn: 0.0253277	total: 1m 36s	remaining: 16m 44s
794:	learn: 0.0304930	total: 1m 36s	remaining: 18m 35s
860:	learn: 0.0271357	total: 1m 36s	remaining: 17m 1s
837:	learn: 0.0270092	total: 1m 36s	remaining: 17m 32s
858:	learn: 0.0240320	total: 1m 36s	remaining: 17m 4s
875:	learn: 0.0252848	total: 1m 36s	remaining: 16m 44s
861:	learn: 0.0270883	total: 1m 36s	remaining: 17m
795:	learn: 0.0304448	total: 1m 36s	remaining: 18m 34s
838:	learn: 0.0269792	total: 1m 36s	remaining: 17m 32s
859:	learn: 0.0239911	total: 1m 36s	remaining: 17m 4s
862:	learn: 0.0270539	total: 1m 36s	remaining: 17m
876:	learn: 0.0252390	total: 1m 36s	remaining: 16m 44s
839:	learn: 0.0269548	total: 1m 36s	remaining: 17m 31s
860:	learn: 0.0239558	total: 1m 36s	remaining: 17m 3s
796:	learn: 0.0304040	total: 1m 36s	remaining: 18m 34s
863:	learn: 0.0270100	total: 1m 36s	remaining: 17m
877:	learn: 0.0252099	total: 1m 36s	remaining: 16m 43s
840:	learn: 0.0269167	total: 1m 36s	remaining: 17m 31s
861:	learn: 0.0239205	total: 1m 36s	remaining: 17m 3s
864:	learn: 0.0269628	total: 1m 36s	remaining: 16m 59s
797:	learn: 0.0303640	total: 1m 36s	remaining: 18m 34s
878:	learn: 0.0251823	total: 1m 36s	remaining: 16m 43s
862:	learn: 0.0238638	total: 1m 36s	remaining: 17m 3s
841:	learn: 0.0268656	total: 1m 36s	remaining: 17m 31s
865:	learn: 0.0269375	total: 1m 36s	remaining: 16m 59s
879:	learn: 0.0251481	total: 1m 36s	remaining: 16m 43s
798:	learn: 0.0303291	total: 1m 36s	remaining: 18m 34s
842:	learn: 0.0268329	total: 1m 36s	remaining: 17m 30s
863:	learn: 0.0238308	total: 1m 36s	remaining: 17m 2s
866:	learn: 0.0269064	total: 1m 36s	remaining: 16m 59s
880:	learn: 0.0250980	total: 1m 36s	remaining: 16m 42s
843:	learn: 0.0267731	total: 1m 36s	remaining: 17m 30s
799:	learn: 0.0302805	total: 1m 36s	remaining: 18m 34s
864:	learn: 0.0237934	total: 1m 36s	remaining: 17m 2s
881:	learn: 0.0250459	total: 1m 36s	remaining: 16m 42s
867:	learn: 0.0268766	total: 1m 36s	remaining: 16m 59s
844:	learn: 0.0267286	total: 1m 36s	remaining: 17m 30s
800:	learn: 0.0302099	total: 1m 37s	remaining: 18m 34s
865:	learn: 0.0237568	total: 1m 36s	remaining: 17m 2s
868:	learn: 0.0268292	total: 1m 36s	remaining: 16m 58s
882:	learn: 0.0250074	total: 1m 37s	remaining: 16m 42s
845:	learn: 0.0266761	total: 1m 37s	remaining: 17m 29s
801:	learn: 0.0301647	total: 1m 37s	remaining: 18m 33s
866:	learn: 0.0236995	total: 1m 37s	remaining: 17m 2s
883:	learn: 0.0249544	total: 1m 37s	remaining: 16m 42s
846:	learn: 0.0266356	total: 1m 37s	remaining: 17m 29s
869:	learn: 0.0267848	total: 1m 37s	remaining: 16m 59s
802:	learn: 0.0301128	total: 1m 37s	remaining: 18m 33s
867:	learn: 0.0236642	total: 1m 37s	remaining: 17m 1s
870:	learn: 0.0267452	total: 1m 37s	remaining: 16m 58s
884:	learn: 0.0249226	total: 1m 37s	remaining: 16m 42s
847:	learn: 0.0265830	total: 1m 37s	remaining: 17m 29s
868:	learn: 0.0236234	total: 1m 37s	remaining: 17m 1s
803:	learn: 0.0300488	total: 1m 37s	remaining: 18m 33s
871:	learn: 0.0267103	total: 1m 37s	remaining: 16m 58s
848:	learn: 0.0265300	total: 1m 37s	remaining: 17m 28s
885:	learn: 0.0248912	total: 1m 37s	remaining: 16m 42s
869:	learn: 0.0235832	total: 1m 37s	remaining: 17m 1s
804:	learn: 0.0299905	total: 1m 37s	remaining: 18m 33s
849:	learn: 0.0264787	total: 1m 37s	remaining: 17m 28s
872:	learn: 0.0266723	total: 1m 37s	remaining: 16m 58s
886:	learn: 0.0248607	total: 1m 37s	remaining: 16m 41s
850:	learn: 0.0264138	total: 1m 37s	remaining: 17m 27s
870:	learn: 0.0235407	total: 1m 37s	remaining: 17m 1s
805:	learn: 0.0299491	total: 1m 37s	remaining: 18m 32s
887:	learn: 0.0248064	total: 1m 37s	remaining: 16m 41s
873:	learn: 0.0266476	total: 1m 37s	remaining: 16m 58s
871:	learn: 0.0234990	total: 1m 37s	remaining: 17m
851:	learn: 0.0263883	total: 1m 37s	remaining: 17m 27s
806:	learn: 0.0299026	total: 1m 37s	remaining: 18m 32s
872:	learn: 0.0234492	total: 1m 37s	remaining: 17m
874:	learn: 0.0266109	total: 1m 37s	remaining: 16m 58s
888:	learn: 0.0247581	total: 1m 37s	remaining: 16m 41s
852:	learn: 0.0263406	total: 1m 37s	remaining: 17m 27s
873:	learn: 0.0234038	total: 1m 37s	remaining: 16m 59s
875:	learn: 0.0265568	total: 1m 37s	remaining: 16m 57s
807:	learn: 0.0298284	total: 1m 37s	remaining: 18m 32s
889:	learn: 0.0247275	total: 1m 37s	remaining: 16m 41s
874:	learn: 0.0233771	total: 1m 37s	remaining: 16m 59s
853:	learn: 0.0262903	total: 1m 37s	remaining: 17m 27s
876:	learn: 0.0265072	total: 1m 37s	remaining: 16m 57s
890:	learn: 0.0246849	total: 1m 37s	remaining: 16m 41s
875:	learn: 0.0233372	total: 1m 37s	remaining: 16m 59s
808:	learn: 0.0297736	total: 1m 37s	remaining: 18m 32s
854:	learn: 0.0262385	total: 1m 37s	remaining: 17m 27s
877:	learn: 0.0264519	total: 1m 37s	remaining: 16m 57s
876:	learn: 0.0232912	total: 1m 37s	remaining: 16m 58s
891:	learn: 0.0246536	total: 1m 38s	remaining: 16m 41s
809:	learn: 0.0297276	total: 1m 38s	remaining: 18m 32s
855:	learn: 0.0261972	total: 1m 38s	remaining: 17m 26s
878:	learn: 0.0264175	total: 1m 38s	remaining: 16m 57s
892:	learn: 0.0245958	total: 1m 38s	remaining: 16m 40s
877:	learn: 0.0232357	total: 1m 38s	remaining: 16m 58s
856:	learn: 0.0261585	total: 1m 38s	remaining: 17m 26s
810:	learn: 0.0296814	total: 1m 38s	remaining: 18m 32s
879:	learn: 0.0263853	total: 1m 38s	remaining: 16m 56s
893:	learn: 0.0245475	total: 1m 38s	remaining: 16m 40s
878:	learn: 0.0232076	total: 1m 38s	remaining: 16m 58s
857:	learn: 0.0261315	total: 1m 38s	remaining: 17m 26s
811:	learn: 0.0296277	total: 1m 38s	remaining: 18m 32s
880:	learn: 0.0263396	total: 1m 38s	remaining: 16m 56s
894:	learn: 0.0244844	total: 1m 38s	remaining: 16m 40s
879:	learn: 0.0231829	total: 1m 38s	remaining: 16m 58s
812:	learn: 0.0295564	total: 1m 38s	remaining: 18m 31s
895:	learn: 0.0244330	total: 1m 38s	remaining: 16m 39s
881:	learn: 0.0262980	total: 1m 38s	remaining: 16m 56s
858:	learn: 0.0260894	total: 1m 38s	remaining: 17m 26s
880:	learn: 0.0231270	total: 1m 38s	remaining: 16m 58s
896:	learn: 0.0243865	total: 1m 38s	remaining: 16m 39s
813:	learn: 0.0295229	total: 1m 38s	remaining: 18m 31s
882:	learn: 0.0262569	total: 1m 38s	remaining: 16m 56s
881:	learn: 0.0230912	total: 1m 38s	remaining: 16m 57s
859:	learn: 0.0260551	total: 1m 38s	remaining: 17m 26s
860:	learn: 0.0259908	total: 1m 38s	remaining: 17m 25s
897:	learn: 0.0243587	total: 1m 38s	remaining: 16m 39s
882:	learn: 0.0230607	total: 1m 38s	remaining: 16m 57s
883:	learn: 0.0262240	total: 1m 38s	remaining: 16m 55s
814:	learn: 0.0294574	total: 1m 38s	remaining: 18m 31s
898:	learn: 0.0243218	total: 1m 38s	remaining: 16m 39s
861:	learn: 0.0259488	total: 1m 38s	remaining: 17m 25s
883:	learn: 0.0230124	total: 1m 38s	remaining: 16m 56s
884:	learn: 0.0261855	total: 1m 38s	remaining: 16m 55s
815:	learn: 0.0293983	total: 1m 38s	remaining: 18m 31s
862:	learn: 0.0258925	total: 1m 38s	remaining: 17m 25s
884:	learn: 0.0229861	total: 1m 38s	remaining: 16m 56s
899:	learn: 0.0242574	total: 1m 38s	remaining: 16m 39s
885:	learn: 0.0261446	total: 1m 38s	remaining: 16m 55s
863:	learn: 0.0258556	total: 1m 38s	remaining: 17m 24s
816:	learn: 0.0293359	total: 1m 38s	remaining: 18m 31s
886:	learn: 0.0261040	total: 1m 38s	remaining: 16m 55s
885:	learn: 0.0229460	total: 1m 38s	remaining: 16m 56s
900:	learn: 0.0242092	total: 1m 38s	remaining: 16m 39s
817:	learn: 0.0293134	total: 1m 38s	remaining: 18m 30s
864:	learn: 0.0258072	total: 1m 38s	remaining: 17m 24s
887:	learn: 0.0260640	total: 1m 38s	remaining: 16m 54s
886:	learn: 0.0229146	total: 1m 38s	remaining: 16m 56s
901:	learn: 0.0241759	total: 1m 39s	remaining: 16m 39s
818:	learn: 0.0292493	total: 1m 39s	remaining: 18m 30s
865:	learn: 0.0257501	total: 1m 39s	remaining: 17m 24s
887:	learn: 0.0228709	total: 1m 38s	remaining: 16m 55s
888:	learn: 0.0260188	total: 1m 39s	remaining: 16m 54s
902:	learn: 0.0241364	total: 1m 39s	remaining: 16m 38s
888:	learn: 0.0228225	total: 1m 39s	remaining: 16m 55s
866:	learn: 0.0257103	total: 1m 39s	remaining: 17m 23s
819:	learn: 0.0291852	total: 1m 39s	remaining: 18m 30s
889:	learn: 0.0259785	total: 1m 39s	remaining: 16m 54s
903:	learn: 0.0240962	total: 1m 39s	remaining: 16m 38s
867:	learn: 0.0256697	total: 1m 39s	remaining: 17m 23s
890:	learn: 0.0259445	total: 1m 39s	remaining: 16m 54s
889:	learn: 0.0227835	total: 1m 39s	remaining: 16m 55s
820:	learn: 0.0291144	total: 1m 39s	remaining: 18m 30s
868:	learn: 0.0256281	total: 1m 39s	remaining: 17m 22s
904:	learn: 0.0240504	total: 1m 39s	remaining: 16m 38s
890:	learn: 0.0227457	total: 1m 39s	remaining: 16m 54s
821:	learn: 0.0290737	total: 1m 39s	remaining: 18m 29s
891:	learn: 0.0259083	total: 1m 39s	remaining: 16m 53s
869:	learn: 0.0255785	total: 1m 39s	remaining: 17m 22s
891:	learn: 0.0227129	total: 1m 39s	remaining: 16m 54s
822:	learn: 0.0290123	total: 1m 39s	remaining: 18m 29s
905:	learn: 0.0239921	total: 1m 39s	remaining: 16m 38s
892:	learn: 0.0258624	total: 1m 39s	remaining: 16m 53s
892:	learn: 0.0226807	total: 1m 39s	remaining: 16m 54s
823:	learn: 0.0289597	total: 1m 39s	remaining: 18m 28s
906:	learn: 0.0239481	total: 1m 39s	remaining: 16m 38s
870:	learn: 0.0255290	total: 1m 39s	remaining: 17m 22s
893:	learn: 0.0258254	total: 1m 39s	remaining: 16m 53s
893:	learn: 0.0226501	total: 1m 39s	remaining: 16m 54s
824:	learn: 0.0288921	total: 1m 39s	remaining: 18m 28s
907:	learn: 0.0239272	total: 1m 39s	remaining: 16m 38s
894:	learn: 0.0257631	total: 1m 39s	remaining: 16m 53s
871:	learn: 0.0254802	total: 1m 39s	remaining: 17m 23s
894:	learn: 0.0226059	total: 1m 39s	remaining: 16m 53s
908:	learn: 0.0238923	total: 1m 39s	remaining: 16m 37s
895:	learn: 0.0225700	total: 1m 39s	remaining: 16m 53s
825:	learn: 0.0288482	total: 1m 39s	remaining: 18m 28s
872:	learn: 0.0254302	total: 1m 39s	remaining: 17m 22s

895:	learn: 0.0257167	total: 1m 39s	remaining: 16m 53s
909:	learn: 0.0238489	total: 1m 39s	remaining: 16m 37s
896:	learn: 0.0256869	total: 1m 39s	remaining: 16m 52s
896:	learn: 0.0225312	total: 1m 39s	remaining: 16m 52s
873:	learn: 0.0253974	total: 1m 39s	remaining: 17m 22s
826:	learn: 0.0288126	total: 1m 39s	remaining: 18m 28s
897:	learn: 0.0256534	total: 1m 39s	remaining: 16m 52s
910:	learn: 0.0238027	total: 1m 40s	remaining: 16m 37s
897:	learn: 0.0224973	total: 1m 39s	remaining: 16m 52s
874:	learn: 0.0253457	total: 1m 39s	remaining: 17m 22s
827:	learn: 0.0287756	total: 1m 40s	remaining: 18m 28s
898:	learn: 0.0256140	total: 1m 39s	remaining: 16m 52s
911:	learn: 0.0237823	total: 1m 40s	remaining: 16m 37s
898:	learn: 0.0224719	total: 1m 39s	remaining: 16m 52s
875:	learn: 0.0252968	total: 1m 40s	remaining: 17m 22s
899:	learn: 0.0255744	total: 1m 40s	remaining: 16m 51s
828:	learn: 0.0287146	total: 1m 40s	remaining: 18m 28s
899:	learn: 0.0224434	total: 1m 40s	remaining: 16m 51s
912:	learn: 0.0237547	total: 1m 40s	remaining: 16m 37s
900:	learn: 0.0255426	total: 1m 40s	remaining: 16m 51s
876:	learn: 0.0252547	total: 1m 40s	remaining: 17m 22s
829:	learn: 0.0286573	total: 1m 40s	remaining: 18m 27s
900:	learn: 0.0224204	total: 1m 40s	remaining: 16m 51s
913:	learn: 0.0237133	total: 1m 40s	remaining: 16m 37s
877:	learn: 0.0252014	total: 1m 40s	remaining: 17m 21s
901:	learn: 0.0255027	total: 1m 40s	remaining: 16m 50s
830:	learn: 0.0286315	total: 1m 40s	remaining: 18m 27s
901:	learn: 0.0223874	total: 1m 40s	remaining: 16m 51s
878:	learn: 0.0251711	total: 1m 40s	remaining: 17m 21s
914:	learn: 0.0236656	total: 1m 40s	remaining: 16m 37s
902:	learn: 0.0254444	total: 1m 40s	remaining: 16m 50s
831:	learn: 0.0285770	total: 1m 40s	remaining: 18m 26s
902:	learn: 0.0223670	total: 1m 40s	remaining: 16m 51s
879:	learn: 0.0251391	total: 1m 40s	remaining: 17m 20s
903:	learn: 0.0254064	total: 1m 40s	remaining: 16m 50s
915:	learn: 0.0236274	total: 1m 40s	remaining: 16m 37s
832:	learn: 0.0285227	total: 1m 40s	remaining: 18m 26s
880:	learn: 0.0250839	total: 1m 40s	remaining: 17m 20s
903:	learn: 0.0223281	total: 1m 40s	remaining: 16m 51s
904:	learn: 0.0253641	total: 1m 40s	remaining: 16m 50s
916:	learn: 0.0235918	total: 1m 40s	remaining: 16m 37s
881:	learn: 0.0250365	total: 1m 40s	remaining: 17m 20s
833:	learn: 0.0284682	total: 1m 40s	remaining: 18m 26s
904:	learn: 0.0222922	total: 1m 40s	remaining: 16m 51s
917:	learn: 0.0235445	total: 1m 40s	remaining: 16m 36s
905:	learn: 0.0253117	total: 1m 40s	remaining: 16m 50s
882:	learn: 0.0249943	total: 1m 40s	remaining: 17m 19s
834:	learn: 0.0284160	total: 1m 40s	remaining: 18m 26s
905:	learn: 0.0222815	total: 1m 40s	remaining: 16m 51s
918:	learn: 0.0234914	total: 1m 40s	remaining: 16m 36s
883:	learn: 0.0249545	total: 1m 40s	remaining: 17m 19s
906:	learn: 0.0252842	total: 1m 40s	remaining: 16m 50s
835:	learn: 0.0283602	total: 1m 40s	remaining: 18m 25s
906:	learn: 0.0222432	total: 1m 40s	remaining: 16m 50s
919:	learn: 0.0234604	total: 1m 40s	remaining: 16m 36s
884:	learn: 0.0248945	total: 1m 40s	remaining: 17m 19s
907:	learn: 0.0252367	total: 1m 40s	remaining: 16m 49s
920:	learn: 0.0234007	total: 1m 41s	remaining: 16m 35s
907:	learn: 0.0222128	total: 1m 40s	remaining: 16m 50s
836:	learn: 0.0283285	total: 1m 41s	remaining: 18m 25s
885:	learn: 0.0248448	total: 1m 40s	remaining: 17m 18s
908:	learn: 0.0251942	total: 1m 40s	remaining: 16m 49s
921:	learn: 0.0233579	total: 1m 41s	remaining: 16m 35s
908:	learn: 0.0221892	total: 1m 41s	remaining: 16m 50s
837:	learn: 0.0282836	total: 1m 41s	remaining: 18m 25s
886:	learn: 0.0248164	total: 1m 41s	remaining: 17m 18s
909:	learn: 0.0251510	total: 1m 41s	remaining: 16m 49s
922:	learn: 0.0233231	total: 1m 41s	remaining: 16m 35s
909:	learn: 0.0221626	total: 1m 41s	remaining: 16m 50s
838:	learn: 0.0282370	total: 1m 41s	remaining: 18m 25s
887:	learn: 0.0247837	total: 1m 41s	remaining: 17m 18s
910:	learn: 0.0251082	total: 1m 41s	remaining: 16m 49s
910:	learn: 0.0221126	total: 1m 41s	remaining: 16m 49s
923:	learn: 0.0232734	total: 1m 41s	remaining: 16m 35s
839:	learn: 0.0281878	total: 1m 41s	remaining: 18m 24s
888:	learn: 0.0247320	total: 1m 41s	remaining: 17m 17s
911:	learn: 0.0250698	total: 1m 41s	remaining: 16m 49s
911:	learn: 0.0220795	total: 1m 41s	remaining: 16m 49s
889:	learn: 0.0246874	total: 1m 41s	remaining: 17m 17s
924:	learn: 0.0232204	total: 1m 41s	remaining: 16m 35s
912:	learn: 0.0250334	total: 1m 41s	remaining: 16m 48s
840:	learn: 0.0281542	total: 1m 41s	remaining: 18m 25s
912:	learn: 0.0220435	total: 1m 41s	remaining: 16m 49s
890:	learn: 0.0246548	total: 1m 41s	remaining: 17m 17s
925:	learn: 0.0231809	total: 1m 41s	remaining: 16m 35s
913:	learn: 0.0249981	total: 1m 41s	remaining: 16m 48s
913:	learn: 0.0220017	total: 1m 41s	remaining: 16m 48s
841:	learn: 0.0281017	total: 1m 41s	remaining: 18m 24s
926:	learn: 0.0231586	total: 1m 41s	remaining: 16m 34s
891:	learn: 0.0246102	total: 1m 41s	remaining: 17m 17s
914:	learn: 0.0249701	total: 1m 41s	remaining: 16m 48s
914:	learn: 0.0219561	total: 1m 41s	remaining: 16m 48s
842:	learn: 0.0280558	total: 1m 41s	remaining: 18m 24s
927:	learn: 0.0231094	total: 1m 41s	remaining: 16m 34s
915:	learn: 0.0249320	total: 1m 41s	remaining: 16m 47s
892:	learn: 0.0245699	total: 1m 41s	remaining: 17m 16s
843:	learn: 0.0280012	total: 1m 41s	remaining: 18m 24s
915:	learn: 0.0219058	total: 1m 41s	remaining: 16m 48s
916:	learn: 0.0249053	total: 1m 41s	remaining: 16m 47s
928:	learn: 0.0230796	total: 1m 41s	remaining: 16m 34s
893:	learn: 0.0245432	total: 1m 41s	remaining: 17m 16s
844:	learn: 0.0279537	total: 1m 41s	remaining: 18m 23s
916:	learn: 0.0218572	total: 1m 41s	remaining: 16m 48s
917:	learn: 0.0248774	total: 1m 41s	remaining: 16m 47s
845:	learn: 0.0279114	total: 1m 41s	remaining: 18m 23s
894:	learn: 0.0244923	total: 1m 41s	remaining: 17m 16s
929:	learn: 0.0230241	total: 1m 41s	remaining: 16m 34s
917:	learn: 0.0218113	total: 1m 41s	remaining: 16m 48s
918:	learn: 0.0248372	total: 1m 41s	remaining: 16m 46s
930:	learn: 0.0229829	total: 1m 42s	remaining: 16m 34s
918:	learn: 0.0217794	total: 1m 41s	remaining: 16m 47s
846:	learn: 0.0278496	total: 1m 42s	remaining: 18m 23s
919:	learn: 0.0247916	total: 1m 42s	remaining: 16m 46s
895:	learn: 0.0244389	total: 1m 42s	remaining: 17m 16s
931:	learn: 0.0229479	total: 1m 42s	remaining: 16m 33s
919:	learn: 0.0217328	total: 1m 42s	remaining: 16m 47s
847:	learn: 0.0278106	total: 1m 42s	remaining: 18m 22s
920:	learn: 0.0247551	total: 1m 42s	remaining: 16m 46s
932:	learn: 0.0229218	total: 1m 42s	remaining: 16m 33s
896:	learn: 0.0244072	total: 1m 42s	remaining: 17m 16s
920:	learn: 0.0216972	total: 1m 42s	remaining: 16m 47s
933:	learn: 0.0228743	total: 1m 42s	remaining: 16m 33s
848:	learn: 0.0277677	total: 1m 42s	remaining: 18m 22s
921:	learn: 0.0247118	total: 1m 42s	remaining: 16m 46s
897:	learn: 0.0243754	total: 1m 42s	remaining: 17m 16s
921:	learn: 0.0216590	total: 1m 42s	remaining: 16m 46s
922:	learn: 0.0246556	total: 1m 42s	remaining: 16m 45s
934:	learn: 0.0228407	total: 1m 42s	remaining: 16m 33s
849:	learn: 0.0277214	total: 1m 42s	remaining: 18m 22s
898:	learn: 0.0243392	total: 1m 42s	remaining: 17m 16s
922:	learn: 0.0216145	total: 1m 42s	remaining: 16m 46s
923:	learn: 0.0246319	total: 1m 42s	remaining: 16m 45s
850:	learn: 0.0276815	total: 1m 42s	remaining: 18m 22s
935:	learn: 0.0227974	total: 1m 42s	remaining: 16m 33s
899:	learn: 0.0242931	total: 1m 42s	remaining: 17m 16s
924:	learn: 0.0245907	total: 1m 42s	remaining: 16m 45s
923:	learn: 0.0215815	total: 1m 42s	remaining: 16m 46s
851:	learn: 0.0276549	total: 1m 42s	remaining: 18m 21s
936:	learn: 0.0227536	total: 1m 42s	remaining: 16m 32s
900:	learn: 0.0242544	total: 1m 42s	remaining: 17m 15s
925:	learn: 0.0245467	total: 1m 42s	remaining: 16m 45s
924:	learn: 0.0215441	total: 1m 42s	remaining: 16m 46s
937:	learn: 0.0227002	total: 1m 42s	remaining: 16m 32s
852:	learn: 0.0276166	total: 1m 42s	remaining: 18m 21s
901:	learn: 0.0242199	total: 1m 42s	remaining: 17m 15s
925:	learn: 0.0214997	total: 1m 42s	remaining: 16m 46s
926:	learn: 0.0245241	total: 1m 42s	remaining: 16m 44s
938:	learn: 0.0226708	total: 1m 42s	remaining: 16m 32s
902:	learn: 0.0241921	total: 1m 42s	remaining: 17m 15s
853:	learn: 0.0275722	total: 1m 42s	remaining: 18m 21s
926:	learn: 0.0214639	total: 1m 42s	remaining: 16m 45s
927:	learn: 0.0244937	total: 1m 42s	remaining: 16m 44s
939:	learn: 0.0226368	total: 1m 42s	remaining: 16m 32s
903:	learn: 0.0241458	total: 1m 42s	remaining: 17m 15s
927:	learn: 0.0214357	total: 1m 42s	remaining: 16m 45s
854:	learn: 0.0275184	total: 1m 42s	remaining: 18m 21s
928:	learn: 0.0244483	total: 1m 42s	remaining: 16m 44s
940:	learn: 0.0226052	total: 1m 43s	remaining: 16m 32s
904:	learn: 0.0241153	total: 1m 42s	remaining: 17m 14s
928:	learn: 0.0214174	total: 1m 42s	remaining: 16m 45s
855:	learn: 0.0274664	total: 1m 43s	remaining: 18m 20s
929:	learn: 0.0244094	total: 1m 42s	remaining: 16m 44s
905:	learn: 0.0240878	total: 1m 43s	remaining: 17m 14s
941:	learn: 0.0225737	total: 1m 43s	remaining: 16m 31s
929:	learn: 0.0213801	total: 1m 43s	remaining: 16m 44s
856:	learn: 0.0274261	total: 1m 43s	remaining: 18m 20s
930:	learn: 0.0243644	total: 1m 43s	remaining: 16m 44s
906:	learn: 0.0240560	total: 1m 43s	remaining: 17m 14s
942:	learn: 0.0225389	total: 1m 43s	remaining: 16m 31s
857:	learn: 0.0273758	total: 1m 43s	remaining: 18m 20s
930:	learn: 0.0213545	total: 1m 43s	remaining: 16m 45s
931:	learn: 0.0243288	total: 1m 43s	remaining: 16m 44s
907:	learn: 0.0240238	total: 1m 43s	remaining: 17m 13s
943:	learn: 0.0224960	total: 1m 43s	remaining: 16m 31s
858:	learn: 0.0273450	total: 1m 43s	remaining: 18m 19s
931:	learn: 0.0213193	total: 1m 43s	remaining: 16m 44s
908:	learn: 0.0239877	total: 1m 43s	remaining: 17m 13s
932:	learn: 0.0242765	total: 1m 43s	remaining: 16m 43s
944:	learn: 0.0224488	total: 1m 43s	remaining: 16m 31s
859:	learn: 0.0273066	total: 1m 43s	remaining: 18m 19s
932:	learn: 0.0212743	total: 1m 43s	remaining: 16m 44s
933:	learn: 0.0242326	total: 1m 43s	remaining: 16m 43s
909:	learn: 0.0239351	total: 1m 43s	remaining: 17m 13s
945:	learn: 0.0224161	total: 1m 43s	remaining: 16m 31s
934:	learn: 0.0242119	total: 1m 43s	remaining: 16m 43s
933:	learn: 0.0212426	total: 1m 43s	remaining: 16m 44s
910:	learn: 0.0239066	total: 1m 43s	remaining: 17m 12s
860:	learn: 0.0272459	total: 1m 43s	remaining: 18m 19s
946:	learn: 0.0223905	total: 1m 43s	remaining: 16m 30s
935:	learn: 0.0241865	total: 1m 43s	remaining: 16m 42s
934:	learn: 0.0212164	total: 1m 43s	remaining: 16m 44s
861:	learn: 0.0271903	total: 1m 43s	remaining: 18m 19s
911:	learn: 0.0238593	total: 1m 43s	remaining: 17m 12s
947:	learn: 0.0223500	total: 1m 43s	remaining: 16m 30s
935:	learn: 0.0211788	total: 1m 43s	remaining: 16m 43s
936:	learn: 0.0241509	total: 1m 43s	remaining: 16m 42s
862:	learn: 0.0271450	total: 1m 43s	remaining: 18m 18s
948:	learn: 0.0223109	total: 1m 43s	remaining: 16m 30s
912:	learn: 0.0238196	total: 1m 43s	remaining: 17m 12s
936:	learn: 0.0211545	total: 1m 43s	remaining: 16m 43s
937:	learn: 0.0241067	total: 1m 43s	remaining: 16m 42s
863:	learn: 0.0271072	total: 1m 43s	remaining: 18m 18s
949:	learn: 0.0222681	total: 1m 43s	remaining: 16m 30s
913:	learn: 0.0237848	total: 1m 43s	remaining: 17m 12s
937:	learn: 0.0210974	total: 1m 43s	remaining: 16m 43s
938:	learn: 0.0240614	total: 1m 43s	remaining: 16m 42s
864:	learn: 0.0270712	total: 1m 43s	remaining: 18m 18s
950:	learn: 0.0222338	total: 1m 44s	remaining: 16m 29s
938:	learn: 0.0210694	total: 1m 43s	remaining: 16m 42s
914:	learn: 0.0237344	total: 1m 43s	remaining: 17m 12s
939:	learn: 0.0240220	total: 1m 43s	remaining: 16m 42s
865:	learn: 0.0270443	total: 1m 44s	remaining: 18m 18s
939:	learn: 0.0210459	total: 1m 44s	remaining: 16m 42s
951:	learn: 0.0222084	total: 1m 44s	remaining: 16m 29s
915:	learn: 0.0237066	total: 1m 44s	remaining: 17m 12s
940:	learn: 0.0239894	total: 1m 44s	remaining: 16m 41s
952:	learn: 0.0221635	total: 1m 44s	remaining: 16m 29s
866:	learn: 0.0270053	total: 1m 44s	remaining: 18m 17s
916:	learn: 0.0236782	total: 1m 44s	remaining: 17m 11s
940:	learn: 0.0210190	total: 1m 44s	remaining: 16m 42s
941:	learn: 0.0239546	total: 1m 44s	remaining: 16m 41s
953:	learn: 0.0221308	total: 1m 44s	remaining: 16m 29s
867:	learn: 0.0269661	total: 1m 44s	remaining: 18m 17s
917:	learn: 0.0236334	total: 1m 44s	remaining: 17m 11s
941:	learn: 0.0209829	total: 1m 44s	remaining: 16m 42s
954:	learn: 0.0220974	total: 1m 44s	remaining: 16m 28s
942:	learn: 0.0239159	total: 1m 44s	remaining: 16m 41s
868:	learn: 0.0269250	total: 1m 44s	remaining: 18m 17s
918:	learn: 0.0236097	total: 1m 44s	remaining: 17m 11s
955:	learn: 0.0220612	total: 1m 44s	remaining: 16m 28s
942:	learn: 0.0209510	total: 1m 44s	remaining: 16m 42s
943:	learn: 0.0238880	total: 1m 44s	remaining: 16m 41s
919:	learn: 0.0235606	total: 1m 44s	remaining: 17m 10s
956:	learn: 0.0220307	total: 1m 44s	remaining: 16m 28s
869:	learn: 0.0268861	total: 1m 44s	remaining: 18m 17s
943:	learn: 0.0209209	total: 1m 44s	remaining: 16m 42s
944:	learn: 0.0238401	total: 1m 44s	remaining: 16m 41s
957:	learn: 0.0220027	total: 1m 44s	remaining: 16m 27s
920:	learn: 0.0235145	total: 1m 44s	remaining: 17m 10s
870:	learn: 0.0268351	total: 1m 44s	remaining: 18m 16s
944:	learn: 0.0208807	total: 1m 44s	remaining: 16m 42s
921:	learn: 0.0234785	total: 1m 44s	remaining: 17m 10s
945:	learn: 0.0238102	total: 1m 44s	remaining: 16m 41s
871:	learn: 0.0267816	total: 1m 44s	remaining: 18m 16s
958:	learn: 0.0219616	total: 1m 44s	remaining: 16m 27s
945:	learn: 0.0208400	total: 1m 44s	remaining: 16m 41s
872:	learn: 0.0267515	total: 1m 44s	remaining: 18m 16s
946:	learn: 0.0237835	total: 1m 44s	remaining: 16m 41s
959:	learn: 0.0219245	total: 1m 44s	remaining: 16m 27s
922:	learn: 0.0234318	total: 1m 44s	remaining: 17m 10s
946:	learn: 0.0208076	total: 1m 44s	remaining: 16m 41s
960:	learn: 0.0218856	total: 1m 44s	remaining: 16m 27s
923:	learn: 0.0233904	total: 1m 44s	remaining: 17m 10s
873:	learn: 0.0267225	total: 1m 44s	remaining: 18m 15s
947:	learn: 0.0237433	total: 1m 44s	remaining: 16m 41s
947:	learn: 0.0207833	total: 1m 44s	remaining: 16m 41s
924:	learn: 0.0233669	total: 1m 44s	remaining: 17m 9s
961:	learn: 0.0218630	total: 1m 45s	remaining: 16m 27s
948:	learn: 0.0236978	total: 1m 44s	remaining: 16m 40s
948:	learn: 0.0207422	total: 1m 44s	remaining: 16m 41s
874:	learn: 0.0266678	total: 1m 45s	remaining: 18m 15s
962:	learn: 0.0218429	total: 1m 45s	remaining: 16m 26s
925:	learn: 0.0233252	total: 1m 45s	remaining: 17m 9s
949:	learn: 0.0236535	total: 1m 45s	remaining: 16m 40s
949:	learn: 0.0207025	total: 1m 45s	remaining: 16m 40s
875:	learn: 0.0266104	total: 1m 45s	remaining: 18m 15s
963:	learn: 0.0218076	total: 1m 45s	remaining: 16m 26s
926:	learn: 0.0232927	total: 1m 45s	remaining: 17m 9s
876:	learn: 0.0265703	total: 1m 45s	remaining: 18m 14s
950:	learn: 0.0236160	total: 1m 45s	remaining: 16m 40s
950:	learn: 0.0206790	total: 1m 45s	remaining: 16m 40s
964:	learn: 0.0217693	total: 1m 45s	remaining: 16m 26s
927:	learn: 0.0232555	total: 1m 45s	remaining: 17m 9s
877:	learn: 0.0265275	total: 1m 45s	remaining: 18m 14s
951:	learn: 0.0235766	total: 1m 45s	remaining: 16m 40s
951:	learn: 0.0206409	total: 1m 45s	remaining: 16m 40s
965:	learn: 0.0217496	total: 1m 45s	remaining: 16m 26s
878:	learn: 0.0264723	total: 1m 45s	remaining: 18m 14s
928:	learn: 0.0232168	total: 1m 45s	remaining: 17m 9s
952:	learn: 0.0235400	total: 1m 45s	remaining: 16m 40s
966:	learn: 0.0217138	total: 1m 45s	remaining: 16m 25s
952:	learn: 0.0206060	total: 1m 45s	remaining: 16m 40s
879:	learn: 0.0264389	total: 1m 45s	remaining: 18m 13s
929:	learn: 0.0231744	total: 1m 45s	remaining: 17m 8s
953:	learn: 0.0234956	total: 1m 45s	remaining: 16m 40s
953:	learn: 0.0205817	total: 1m 45s	remaining: 16m 40s
967:	learn: 0.0216843	total: 1m 45s	remaining: 16m 25s
880:	learn: 0.0263904	total: 1m 45s	remaining: 18m 13s
954:	learn: 0.0234633	total: 1m 45s	remaining: 16m 39s
968:	learn: 0.0216530	total: 1m 45s	remaining: 16m 25s
930:	learn: 0.0231357	total: 1m 45s	remaining: 17m 8s
954:	learn: 0.0205506	total: 1m 45s	remaining: 16m 40s
881:	learn: 0.0263328	total: 1m 45s	remaining: 18m 13s
955:	learn: 0.0234393	total: 1m 45s	remaining: 16m 39s
931:	learn: 0.0230956	total: 1m 45s	remaining: 17m 8s
955:	learn: 0.0205112	total: 1m 45s	remaining: 16m 40s
969:	learn: 0.0216232	total: 1m 45s	remaining: 16m 25s

932:	learn: 0.0230708	total: 1m 45s	remaining: 17m 8s
882:	learn: 0.0262903	total: 1m 45s	remaining: 18m 13s
956:	learn: 0.0234068	total: 1m 45s	remaining: 16m 39s
956:	learn: 0.0204692	total: 1m 45s	remaining: 16m 39s
970:	learn: 0.0215982	total: 1m 45s	remaining: 16m 25s
933:	learn: 0.0230411	total: 1m 45s	remaining: 17m 7s
883:	learn: 0.0262572	total: 1m 45s	remaining: 18m 12s
957:	learn: 0.0233649	total: 1m 45s	remaining: 16m 39s
934:	learn: 0.0229847	total: 1m 45s	remaining: 17m 7s
957:	learn: 0.0204331	total: 1m 45s	remaining: 16m 39s
971:	learn: 0.0215579	total: 1m 46s	remaining: 16m 25s
884:	learn: 0.0262223	total: 1m 46s	remaining: 18m 12s
958:	learn: 0.0233363	total: 1m 45s	remaining: 16m 39s
972:	learn: 0.0215180	total: 1m 46s	remaining: 16m 24s
958:	learn: 0.0204083	total: 1m 46s	remaining: 16m 39s
935:	learn: 0.0229481	total: 1m 46s	remaining: 17m 7s
885:	learn: 0.0261833	total: 1m 46s	remaining: 18m 12s
959:	learn: 0.0233106	total: 1m 46s	remaining: 16m 38s
973:	learn: 0.0214730	total: 1m 46s	remaining: 16m 24s
959:	learn: 0.0203754	total: 1m 46s	remaining: 16m 39s
936:	learn: 0.0229017	total: 1m 46s	remaining: 17m 7s
960:	learn: 0.0232629	total: 1m 46s	remaining: 16m 38s
886:	learn: 0.0261149	total: 1m 46s	remaining: 18m 12s
974:	learn: 0.0214493	total: 1m 46s	remaining: 16m 24s
937:	learn: 0.0228523	total: 1m 46s	remaining: 17m 6s
960:	learn: 0.0203462	total: 1m 46s	remaining: 16m 39s
961:	learn: 0.0232420	total: 1m 46s	remaining: 16m 38s
938:	learn: 0.0228263	total: 1m 46s	remaining: 17m 6s
887:	learn: 0.0260845	total: 1m 46s	remaining: 18m 12s
975:	learn: 0.0214236	total: 1m 46s	remaining: 16m 24s
962:	learn: 0.0232118	total: 1m 46s	remaining: 16m 37s
961:	learn: 0.0203258	total: 1m 46s	remaining: 16m 39s
976:	learn: 0.0213788	total: 1m 46s	remaining: 16m 24s
939:	learn: 0.0228000	total: 1m 46s	remaining: 17m 6s
963:	learn: 0.0231783	total: 1m 46s	remaining: 16m 37s
888:	learn: 0.0260284	total: 1m 46s	remaining: 18m 11s
962:	learn: 0.0203010	total: 1m 46s	remaining: 16m 39s
977:	learn: 0.0213507	total: 1m 46s	remaining: 16m 23s
940:	learn: 0.0227714	total: 1m 46s	remaining: 17m 5s
964:	learn: 0.0231479	total: 1m 46s	remaining: 16m 37s
889:	learn: 0.0259997	total: 1m 46s	remaining: 18m 11s
978:	learn: 0.0213201	total: 1m 46s	remaining: 16m 23s
941:	learn: 0.0227369	total: 1m 46s	remaining: 17m 5s
963:	learn: 0.0202791	total: 1m 46s	remaining: 16m 39s
965:	learn: 0.0231148	total: 1m 46s	remaining: 16m 37s
890:	learn: 0.0259554	total: 1m 46s	remaining: 18m 11s
966:	learn: 0.0230755	total: 1m 46s	remaining: 16m 36s
942:	learn: 0.0226922	total: 1m 46s	remaining: 17m 5s
979:	learn: 0.0212847	total: 1m 46s	remaining: 16m 23s
964:	learn: 0.0202403	total: 1m 46s	remaining: 16m 39s
891:	learn: 0.0259307	total: 1m 46s	remaining: 18m 10s
967:	learn: 0.0230450	total: 1m 46s	remaining: 16m 36s
965:	learn: 0.0202105	total: 1m 46s	remaining: 16m 38s
980:	learn: 0.0212496	total: 1m 46s	remaining: 16m 23s
943:	learn: 0.0226576	total: 1m 46s	remaining: 17m 5s
892:	learn: 0.0258888	total: 1m 46s	remaining: 18m 10s
968:	learn: 0.0229996	total: 1m 46s	remaining: 16m 35s
966:	learn: 0.0201815	total: 1m 46s	remaining: 16m 38s
893:	learn: 0.0258435	total: 1m 47s	remaining: 18m 10s
981:	learn: 0.0212164	total: 1m 47s	remaining: 16m 23s
944:	learn: 0.0226204	total: 1m 46s	remaining: 17m 5s
969:	learn: 0.0229771	total: 1m 46s	remaining: 16m 35s
967:	learn: 0.0201379	total: 1m 46s	remaining: 16m 38s
982:	learn: 0.0211799	total: 1m 47s	remaining: 16m 23s
894:	learn: 0.0257713	total: 1m 47s	remaining: 18m 10s
945:	learn: 0.0225953	total: 1m 47s	remaining: 17m 5s
970:	learn: 0.0229498	total: 1m 47s	remaining: 16m 35s
968:	learn: 0.0201189	total: 1m 47s	remaining: 16m 38s
983:	learn: 0.0211450	total: 1m 47s	remaining: 16m 22s
895:	learn: 0.0257313	total: 1m 47s	remaining: 18m 9s
946:	learn: 0.0225691	total: 1m 47s	remaining: 17m 4s
971:	learn: 0.0229077	total: 1m 47s	remaining: 16m 35s
969:	learn: 0.0200829	total: 1m 47s	remaining: 16m 37s
984:	learn: 0.0211301	total: 1m 47s	remaining: 16m 22s
896:	learn: 0.0256921	total: 1m 47s	remaining: 18m 9s
947:	learn: 0.0225282	total: 1m 47s	remaining: 17m 4s
970:	learn: 0.0200569	total: 1m 47s	remaining: 16m 37s
972:	learn: 0.0228696	total: 1m 47s	remaining: 16m 35s
897:	learn: 0.0256416	total: 1m 47s	remaining: 18m 8s
985:	learn: 0.0210824	total: 1m 47s	remaining: 16m 22s
948:	learn: 0.0224970	total: 1m 47s	remaining: 17m 4s
971:	learn: 0.0200239	total: 1m 47s	remaining: 16m 37s
973:	learn: 0.0228335	total: 1m 47s	remaining: 16m 35s
898:	learn: 0.0256147	total: 1m 47s	remaining: 18m 8s
986:	learn: 0.0210415	total: 1m 47s	remaining: 16m 22s
972:	learn: 0.0199830	total: 1m 47s	remaining: 16m 36s
949:	learn: 0.0224446	total: 1m 47s	remaining: 17m 4s
974:	learn: 0.0228075	total: 1m 47s	remaining: 16m 35s
899:	learn: 0.0255875	total: 1m 47s	remaining: 18m 8s
987:	learn: 0.0210210	total: 1m 47s	remaining: 16m 22s
973:	learn: 0.0199513	total: 1m 47s	remaining: 16m 36s
950:	learn: 0.0224105	total: 1m 47s	remaining: 17m 3s
975:	learn: 0.0227613	total: 1m 47s	remaining: 16m 34s
974:	learn: 0.0199128	total: 1m 47s	remaining: 16m 36s
988:	learn: 0.0209821	total: 1m 47s	remaining: 16m 21s
900:	learn: 0.0255567	total: 1m 47s	remaining: 18m 8s
951:	learn: 0.0223773	total: 1m 47s	remaining: 17m 3s
976:	learn: 0.0227225	total: 1m 47s	remaining: 16m 34s
989:	learn: 0.0209501	total: 1m 47s	remaining: 16m 21s
975:	learn: 0.0198852	total: 1m 47s	remaining: 16m 36s
952:	learn: 0.0223328	total: 1m 47s	remaining: 17m 3s
901:	learn: 0.0255230	total: 1m 47s	remaining: 18m 8s
977:	learn: 0.0226838	total: 1m 47s	remaining: 16m 34s
953:	learn: 0.0222858	total: 1m 47s	remaining: 17m 3s
990:	learn: 0.0209240	total: 1m 47s	remaining: 16m 21s
978:	learn: 0.0226401	total: 1m 47s	remaining: 16m 34s
976:	learn: 0.0198390	total: 1m 47s	remaining: 16m 36s
902:	learn: 0.0254781	total: 1m 47s	remaining: 18m 7s
991:	learn: 0.0208912	total: 1m 48s	remaining: 16m 21s
954:	learn: 0.0222464	total: 1m 47s	remaining: 17m 2s
977:	learn: 0.0197972	total: 1m 47s	remaining: 16m 35s
979:	learn: 0.0226181	total: 1m 47s	remaining: 16m 33s
903:	learn: 0.0254094	total: 1m 48s	remaining: 18m 7s
992:	learn: 0.0208698	total: 1m 48s	remaining: 16m 21s
978:	learn: 0.0197710	total: 1m 48s	remaining: 16m 35s
955:	learn: 0.0222186	total: 1m 48s	remaining: 17m 2s
904:	learn: 0.0253522	total: 1m 48s	remaining: 18m 7s
993:	learn: 0.0208428	total: 1m 48s	remaining: 16m 20s
980:	learn: 0.0225696	total: 1m 48s	remaining: 16m 34s
979:	learn: 0.0197430	total: 1m 48s	remaining: 16m 35s
956:	learn: 0.0221878	total: 1m 48s	remaining: 17m 2s
981:	learn: 0.0225365	total: 1m 48s	remaining: 16m 33s
905:	learn: 0.0253179	total: 1m 48s	remaining: 18m 7s
994:	learn: 0.0208131	total: 1m 48s	remaining: 16m 20s
980:	learn: 0.0197207	total: 1m 48s	remaining: 16m 35s
982:	learn: 0.0225113	total: 1m 48s	remaining: 16m 33s
906:	learn: 0.0252966	total: 1m 48s	remaining: 18m 6s
957:	learn: 0.0221436	total: 1m 48s	remaining: 17m 2s
995:	learn: 0.0207838	total: 1m 48s	remaining: 16m 20s
983:	learn: 0.0224829	total: 1m 48s	remaining: 16m 32s
981:	learn: 0.0196925	total: 1m 48s	remaining: 16m 35s
907:	learn: 0.0252637	total: 1m 48s	remaining: 18m 6s
996:	learn: 0.0207495	total: 1m 48s	remaining: 16m 20s
984:	learn: 0.0224345	total: 1m 48s	remaining: 16m 32s
958:	learn: 0.0221108	total: 1m 48s	remaining: 17m 2s
982:	learn: 0.0196731	total: 1m 48s	remaining: 16m 34s
997:	learn: 0.0207242	total: 1m 48s	remaining: 16m 19s
983:	learn: 0.0196473	total: 1m 48s	remaining: 16m 34s
908:	learn: 0.0252342	total: 1m 48s	remaining: 18m 6s
985:	learn: 0.0224001	total: 1m 48s	remaining: 16m 32s
959:	learn: 0.0220747	total: 1m 48s	remaining: 17m 2s
998:	learn: 0.0206886	total: 1m 48s	remaining: 16m 19s
984:	learn: 0.0196304	total: 1m 48s	remaining: 16m 34s
960:	learn: 0.0220427	total: 1m 48s	remaining: 17m 2s
986:	learn: 0.0223748	total: 1m 48s	remaining: 16m 32s
909:	learn: 0.0251970	total: 1m 48s	remaining: 18m 6s
999:	learn: 0.0206642	total: 1m 48s	remaining: 16m 19s
961:	learn: 0.0220109	total: 1m 48s	remaining: 17m 1s
987:	learn: 0.0223450	total: 1m 48s	remaining: 16m 31s
985:	learn: 0.0196027	total: 1m 48s	remaining: 16m 33s
910:	learn: 0.0251344	total: 1m 48s	remaining: 18m 6s
1000:	learn: 0.0206302	total: 1m 48s	remaining: 16m 19s
988:	learn: 0.0223065	total: 1m 48s	remaining: 16m 31s
986:	learn: 0.0195738	total: 1m 48s	remaining: 16m 33s
962:	learn: 0.0219822	total: 1m 48s	remaining: 17m 1s
1001:	learn: 0.0206072	total: 1m 48s	remaining: 16m 18s
911:	learn: 0.0250928	total: 1m 49s	remaining: 18m 6s
1002:	learn: 0.0205868	total: 1m 49s	remaining: 16m 18s
987:	learn: 0.0195462	total: 1m 48s	remaining: 16m 33s
963:	learn: 0.0219569	total: 1m 48s	remaining: 17m 1s
989:	learn: 0.0222722	total: 1m 48s	remaining: 16m 31s
912:	learn: 0.0250543	total: 1m 49s	remaining: 18m 6s
988:	learn: 0.0195325	total: 1m 49s	remaining: 16m 33s
964:	learn: 0.0219180	total: 1m 49s	remaining: 17m 1s
1003:	learn: 0.0205509	total: 1m 49s	remaining: 16m 18s
990:	learn: 0.0222431	total: 1m 49s	remaining: 16m 31s
965:	learn: 0.0218933	total: 1m 49s	remaining: 17m
989:	learn: 0.0195048	total: 1m 49s	remaining: 16m 33s
913:	learn: 0.0250149	total: 1m 49s	remaining: 18m 6s
1004:	learn: 0.0205104	total: 1m 49s	remaining: 16m 18s
991:	learn: 0.0222225	total: 1m 49s	remaining: 16m 31s
966:	learn: 0.0218621	total: 1m 49s	remaining: 17m
990:	learn: 0.0194721	total: 1m 49s	remaining: 16m 32s
1005:	learn: 0.0204912	total: 1m 49s	remaining: 16m 17s
914:	learn: 0.0249688	total: 1m 49s	remaining: 18m 5s
967:	learn: 0.0218289	total: 1m 49s	remaining: 17m
1006:	learn: 0.0204624	total: 1m 49s	remaining: 16m 17s
992:	learn: 0.0221960	total: 1m 49s	remaining: 16m 31s
991:	learn: 0.0194289	total: 1m 49s	remaining: 16m 32s
915:	learn: 0.0249252	total: 1m 49s	remaining: 18m 5s
1007:	learn: 0.0204291	total: 1m 49s	remaining: 16m 17s
968:	learn: 0.0217967	total: 1m 49s	remaining: 17m
992:	learn: 0.0193814	total: 1m 49s	remaining: 16m 32s
993:	learn: 0.0221586	total: 1m 49s	remaining: 16m 31s
916:	learn: 0.0248864	total: 1m 49s	remaining: 18m 5s
969:	learn: 0.0217662	total: 1m 49s	remaining: 16m 59s
1008:	learn: 0.0204042	total: 1m 49s	remaining: 16m 17s
994:	learn: 0.0221382	total: 1m 49s	remaining: 16m 31s
917:	learn: 0.0248385	total: 1m 49s	remaining: 18m 4s
993:	learn: 0.0193413	total: 1m 49s	remaining: 16m 32s
1009:	learn: 0.0203548	total: 1m 49s	remaining: 16m 16s
970:	learn: 0.0217464	total: 1m 49s	remaining: 16m 59s
995:	learn: 0.0221100	total: 1m 49s	remaining: 16m 31s
918:	learn: 0.0247950	total: 1m 49s	remaining: 18m 4s
994:	learn: 0.0193131	total: 1m 49s	remaining: 16m 32s
1010:	learn: 0.0203111	total: 1m 49s	remaining: 16m 16s
971:	learn: 0.0216974	total: 1m 49s	remaining: 16m 59s
996:	learn: 0.0220691	total: 1m 49s	remaining: 16m 30s
919:	learn: 0.0247512	total: 1m 49s	remaining: 18m 4s
972:	learn: 0.0216714	total: 1m 49s	remaining: 16m 58s
995:	learn: 0.0192961	total: 1m 49s	remaining: 16m 32s
1011:	learn: 0.0202650	total: 1m 49s	remaining: 16m 16s
997:	learn: 0.0220369	total: 1m 49s	remaining: 16m 30s
973:	learn: 0.0216347	total: 1m 49s	remaining: 16m 58s
996:	learn: 0.0192733	total: 1m 49s	remaining: 16m 32s
920:	learn: 0.0247297	total: 1m 49s	remaining: 18m 4s
1012:	learn: 0.0202199	total: 1m 50s	remaining: 16m 16s
998:	learn: 0.0220069	total: 1m 49s	remaining: 16m 30s
974:	learn: 0.0216057	total: 1m 49s	remaining: 16m 58s
997:	learn: 0.0192405	total: 1m 49s	remaining: 16m 31s
921:	learn: 0.0246727	total: 1m 50s	remaining: 18m 4s
1013:	learn: 0.0201842	total: 1m 50s	remaining: 16m 16s
999:	learn: 0.0219707	total: 1m 50s	remaining: 16m 30s
975:	learn: 0.0215759	total: 1m 50s	remaining: 16m 57s
998:	learn: 0.0192161	total: 1m 50s	remaining: 16m 31s
922:	learn: 0.0246401	total: 1m 50s	remaining: 18m 3s
1000:	learn: 0.0219483	total: 1m 50s	remaining: 16m 29s
1014:	learn: 0.0201503	total: 1m 50s	remaining: 16m 15s
976:	learn: 0.0215448	total: 1m 50s	remaining: 16m 57s
999:	learn: 0.0191831	total: 1m 50s	remaining: 16m 31s
1001:	learn: 0.0219167	total: 1m 50s	remaining: 16m 29s
1015:	learn: 0.0201242	total: 1m 50s	remaining: 16m 15s
923:	learn: 0.0246021	total: 1m 50s	remaining: 18m 3s
977:	learn: 0.0215227	total: 1m 50s	remaining: 16m 57s
1000:	learn: 0.0191512	total: 1m 50s	remaining: 16m 31s
1016:	learn: 0.0200908	total: 1m 50s	remaining: 16m 15s
1002:	learn: 0.0218847	total: 1m 50s	remaining: 16m 29s
924:	learn: 0.0245586	total: 1m 50s	remaining: 18m 3s
978:	learn: 0.0214834	total: 1m 50s	remaining: 16m 57s
1001:	learn: 0.0191226	total: 1m 50s	remaining: 16m 31s
1003:	learn: 0.0218577	total: 1m 50s	remaining: 16m 29s
1017:	learn: 0.0200713	total: 1m 50s	remaining: 16m 15s
979:	learn: 0.0214497	total: 1m 50s	remaining: 16m 56s
925:	learn: 0.0245312	total: 1m 50s	remaining: 18m 3s
1002:	learn: 0.0191026	total: 1m 50s	remaining: 16m 31s
1004:	learn: 0.0218290	total: 1m 50s	remaining: 16m 28s
1018:	learn: 0.0200332	total: 1m 50s	remaining: 16m 15s
980:	learn: 0.0214113	total: 1m 50s	remaining: 16m 56s
926:	learn: 0.0244982	total: 1m 50s	remaining: 18m 2s
1019:	learn: 0.0199939	total: 1m 50s	remaining: 16m 14s
1003:	learn: 0.0190776	total: 1m 50s	remaining: 16m 31s
1005:	learn: 0.0218052	total: 1m 50s	remaining: 16m 28s
927:	learn: 0.0244685	total: 1m 50s	remaining: 18m 2s
981:	learn: 0.0213835	total: 1m 50s	remaining: 16m 56s
1004:	learn: 0.0190427	total: 1m 50s	remaining: 16m 30s
1020:	learn: 0.0199595	total: 1m 50s	remaining: 16m 14s
1006:	learn: 0.0217852	total: 1m 50s	remaining: 16m 28s
928:	learn: 0.0244423	total: 1m 50s	remaining: 18m 2s
982:	learn: 0.0213537	total: 1m 50s	remaining: 16m 56s
1005:	learn: 0.0190213	total: 1m 50s	remaining: 16m 30s
1007:	learn: 0.0217617	total: 1m 50s	remaining: 16m 28s
1021:	learn: 0.0199258	total: 1m 50s	remaining: 16m 14s
929:	learn: 0.0243809	total: 1m 50s	remaining: 18m 2s
983:	learn: 0.0213288	total: 1m 50s	remaining: 16m 56s
1006:	learn: 0.0189870	total: 1m 50s	remaining: 16m 30s
1022:	learn: 0.0198990	total: 1m 51s	remaining: 16m 14s
1008:	learn: 0.0217276	total: 1m 50s	remaining: 16m 28s
1007:	learn: 0.0189503	total: 1m 50s	remaining: 16m 29s
984:	learn: 0.0212899	total: 1m 51s	remaining: 16m 55s
930:	learn: 0.0243436	total: 1m 51s	remaining: 18m 2s
1009:	learn: 0.0217023	total: 1m 50s	remaining: 16m 27s
1023:	learn: 0.0198780	total: 1m 51s	remaining: 16m 14s
1008:	learn: 0.0189254	total: 1m 51s	remaining: 16m 29s
985:	learn: 0.0212490	total: 1m 51s	remaining: 16m 55s
1024:	learn: 0.0198529	total: 1m 51s	remaining: 16m 13s
931:	learn: 0.0242982	total: 1m 51s	remaining: 18m 2s
1010:	learn: 0.0216634	total: 1m 51s	remaining: 16m 27s
1009:	learn: 0.0189098	total: 1m 51s	remaining: 16m 29s
1025:	learn: 0.0198114	total: 1m 51s	remaining: 16m 13s
986:	learn: 0.0212312	total: 1m 51s	remaining: 16m 55s
932:	learn: 0.0242450	total: 1m 51s	remaining: 18m 1s
1011:	learn: 0.0216257	total: 1m 51s	remaining: 16m 27s
1026:	learn: 0.0197867	total: 1m 51s	remaining: 16m 13s
1010:	learn: 0.0188884	total: 1m 51s	remaining: 16m 29s
987:	learn: 0.0212086	total: 1m 51s	remaining: 16m 55s
933:	learn: 0.0242150	total: 1m 51s	remaining: 18m 1s
1012:	learn: 0.0216046	total: 1m 51s	remaining: 16m 27s
1027:	learn: 0.0197531	total: 1m 51s	remaining: 16m 13s
934:	learn: 0.0241926	total: 1m 51s	remaining: 18m
1011:	learn: 0.0188580	total: 1m 51s	remaining: 16m 29s
988:	learn: 0.0211688	total: 1m 51s	remaining: 16m 55s
1013:	learn: 0.0215630	total: 1m 51s	remaining: 16m 27s
1028:	learn: 0.0197145	total: 1m 51s	remaining: 16m 12s
935:	learn: 0.0241690	total: 1m 51s	remaining: 18m
989:	learn: 0.0211352	total: 1m 51s	remaining: 16m 54s
1012:	learn: 0.0188385	total: 1m 51s	remaining: 16m 29s
1014:	learn: 0.0215417	total: 1m 51s	remaining: 16m 27s
1029:	learn: 0.0196992	total: 1m 51s	remaining: 16m 12s
936:	learn: 0.0241358	total: 1m 51s	remaining: 18m
1013:	learn: 0.0188135	total: 1m 51s	remaining: 16m 28s
990:	learn: 0.0211128	total: 1m 51s	remaining: 16m 54s
1014:	learn: 0.0187837	total: 1m 51s	remaining: 16m 28s
1015:	learn: 0.0215002	total: 1m 51s	remaining: 16m 27s
937:	learn: 0.0240865	total: 1m 51s	remaining: 17m 59s
1030:	learn: 0.0196883	total: 1m 51s	remaining: 16m 12s
991:	learn: 0.0210764	total: 1m 51s	remaining: 16m 54s
1015:	learn: 0.0187579	total: 1m 51s	remaining: 16m 28s

1016:	learn: 0.0214682	total: 1m 51s	remaining: 16m 26s
938:	learn: 0.0240392	total: 1m 51s	remaining: 17m 59s
992:	learn: 0.0210517	total: 1m 51s	remaining: 16m 54s
1031:	learn: 0.0196606	total: 1m 51s	remaining: 16m 12s
1016:	learn: 0.0187342	total: 1m 51s	remaining: 16m 27s
1017:	learn: 0.0214323	total: 1m 51s	remaining: 16m 26s
939:	learn: 0.0240194	total: 1m 51s	remaining: 17m 59s
1032:	learn: 0.0196411	total: 1m 52s	remaining: 16m 12s
993:	learn: 0.0210211	total: 1m 51s	remaining: 16m 54s
1017:	learn: 0.0187010	total: 1m 51s	remaining: 16m 27s
1018:	learn: 0.0214098	total: 1m 51s	remaining: 16m 26s
1033:	learn: 0.0196161	total: 1m 52s	remaining: 16m 11s
940:	learn: 0.0239819	total: 1m 52s	remaining: 17m 59s
994:	learn: 0.0210002	total: 1m 52s	remaining: 16m 54s
1019:	learn: 0.0213756	total: 1m 52s	remaining: 16m 26s
1018:	learn: 0.0186767	total: 1m 52s	remaining: 16m 27s
1034:	learn: 0.0195817	total: 1m 52s	remaining: 16m 11s
941:	learn: 0.0239349	total: 1m 52s	remaining: 17m 58s
1020:	learn: 0.0213293	total: 1m 52s	remaining: 16m 25s
1019:	learn: 0.0186514	total: 1m 52s	remaining: 16m 27s
995:	learn: 0.0209690	total: 1m 52s	remaining: 16m 54s
1035:	learn: 0.0195583	total: 1m 52s	remaining: 16m 11s
942:	learn: 0.0239064	total: 1m 52s	remaining: 17m 58s
1036:	learn: 0.0195427	total: 1m 52s	remaining: 16m 11s
1020:	learn: 0.0186339	total: 1m 52s	remaining: 16m 27s
996:	learn: 0.0209403	total: 1m 52s	remaining: 16m 53s
1021:	learn: 0.0213050	total: 1m 52s	remaining: 16m 26s
943:	learn: 0.0238784	total: 1m 52s	remaining: 17m 58s
1037:	learn: 0.0195133	total: 1m 52s	remaining: 16m 10s
997:	learn: 0.0209083	total: 1m 52s	remaining: 16m 53s
1021:	learn: 0.0186055	total: 1m 52s	remaining: 16m 26s
1022:	learn: 0.0212755	total: 1m 52s	remaining: 16m 25s
944:	learn: 0.0238257	total: 1m 52s	remaining: 17m 57s
998:	learn: 0.0208797	total: 1m 52s	remaining: 16m 53s
1022:	learn: 0.0185826	total: 1m 52s	remaining: 16m 26s
1038:	learn: 0.0194728	total: 1m 52s	remaining: 16m 10s
1023:	learn: 0.0212534	total: 1m 52s	remaining: 16m 25s
945:	learn: 0.0237868	total: 1m 52s	remaining: 17m 57s
1024:	learn: 0.0212205	total: 1m 52s	remaining: 16m 25s
999:	learn: 0.0208495	total: 1m 52s	remaining: 16m 53s
1039:	learn: 0.0194580	total: 1m 52s	remaining: 16m 10s
946:	learn: 0.0237535	total: 1m 52s	remaining: 17m 57s
1023:	learn: 0.0185416	total: 1m 52s	remaining: 16m 26s
1000:	learn: 0.0208300	total: 1m 52s	remaining: 16m 52s
1025:	learn: 0.0211932	total: 1m 52s	remaining: 16m 24s
1040:	learn: 0.0194289	total: 1m 52s	remaining: 16m 10s
947:	learn: 0.0237124	total: 1m 52s	remaining: 17m 56s
1024:	learn: 0.0185304	total: 1m 52s	remaining: 16m 26s
1026:	learn: 0.0211553	total: 1m 52s	remaining: 16m 24s
1001:	learn: 0.0207944	total: 1m 52s	remaining: 16m 52s
1041:	learn: 0.0193946	total: 1m 52s	remaining: 16m 10s
1025:	learn: 0.0185038	total: 1m 52s	remaining: 16m 26s
948:	learn: 0.0236761	total: 1m 52s	remaining: 17m 56s
1027:	learn: 0.0211297	total: 1m 52s	remaining: 16m 24s
1002:	learn: 0.0207669	total: 1m 52s	remaining: 16m 52s
1026:	learn: 0.0184902	total: 1m 52s	remaining: 16m 26s
1042:	learn: 0.0193736	total: 1m 53s	remaining: 16m 10s
1028:	learn: 0.0211084	total: 1m 52s	remaining: 16m 24s
949:	learn: 0.0236452	total: 1m 53s	remaining: 17m 56s
1003:	learn: 0.0207407	total: 1m 52s	remaining: 16m 52s
1027:	learn: 0.0184645	total: 1m 52s	remaining: 16m 25s
1029:	learn: 0.0210844	total: 1m 52s	remaining: 16m 23s
1043:	learn: 0.0193448	total: 1m 53s	remaining: 16m 10s
1004:	learn: 0.0207164	total: 1m 53s	remaining: 16m 51s
950:	learn: 0.0235902	total: 1m 53s	remaining: 17m 56s
1028:	learn: 0.0184408	total: 1m 53s	remaining: 16m 25s
1044:	learn: 0.0193130	total: 1m 53s	remaining: 16m 10s
1030:	learn: 0.0210425	total: 1m 53s	remaining: 16m 23s
1029:	learn: 0.0183976	total: 1m 53s	remaining: 16m 25s
1005:	learn: 0.0206797	total: 1m 53s	remaining: 16m 51s
951:	learn: 0.0235564	total: 1m 53s	remaining: 17m 56s
1045:	learn: 0.0192704	total: 1m 53s	remaining: 16m 9s
1031:	learn: 0.0210131	total: 1m 53s	remaining: 16m 23s
1030:	learn: 0.0183763	total: 1m 53s	remaining: 16m 24s
1006:	learn: 0.0206386	total: 1m 53s	remaining: 16m 51s
1046:	learn: 0.0192592	total: 1m 53s	remaining: 16m 9s
952:	learn: 0.0235289	total: 1m 53s	remaining: 17m 56s
1032:	learn: 0.0209888	total: 1m 53s	remaining: 16m 23s
1007:	learn: 0.0206064	total: 1m 53s	remaining: 16m 51s
1047:	learn: 0.0192427	total: 1m 53s	remaining: 16m 9s
1031:	learn: 0.0183479	total: 1m 53s	remaining: 16m 25s
953:	learn: 0.0234966	total: 1m 53s	remaining: 17m 56s
1033:	learn: 0.0209512	total: 1m 53s	remaining: 16m 22s
1032:	learn: 0.0183240	total: 1m 53s	remaining: 16m 24s
1008:	learn: 0.0205765	total: 1m 53s	remaining: 16m 51s
1048:	learn: 0.0192121	total: 1m 53s	remaining: 16m 9s
1034:	learn: 0.0209160	total: 1m 53s	remaining: 16m 22s
954:	learn: 0.0234616	total: 1m 53s	remaining: 17m 55s
1033:	learn: 0.0182959	total: 1m 53s	remaining: 16m 24s
1009:	learn: 0.0205600	total: 1m 53s	remaining: 16m 50s
1049:	learn: 0.0191684	total: 1m 53s	remaining: 16m 9s
1035:	learn: 0.0208949	total: 1m 53s	remaining: 16m 22s
955:	learn: 0.0234139	total: 1m 53s	remaining: 17m 55s
1034:	learn: 0.0182655	total: 1m 53s	remaining: 16m 24s
1010:	learn: 0.0205328	total: 1m 53s	remaining: 16m 50s
1036:	learn: 0.0208592	total: 1m 53s	remaining: 16m 22s
1050:	learn: 0.0191396	total: 1m 53s	remaining: 16m 9s
956:	learn: 0.0233768	total: 1m 53s	remaining: 17m 55s
1035:	learn: 0.0182361	total: 1m 53s	remaining: 16m 23s
1037:	learn: 0.0208284	total: 1m 53s	remaining: 16m 21s
1011:	learn: 0.0205075	total: 1m 53s	remaining: 16m 50s
1051:	learn: 0.0191072	total: 1m 53s	remaining: 16m 8s
957:	learn: 0.0233140	total: 1m 53s	remaining: 17m 55s
1012:	learn: 0.0204803	total: 1m 53s	remaining: 16m 50s
1038:	learn: 0.0208049	total: 1m 53s	remaining: 16m 21s
1036:	learn: 0.0182112	total: 1m 53s	remaining: 16m 23s
1052:	learn: 0.0190679	total: 1m 54s	remaining: 16m 8s
1039:	learn: 0.0207659	total: 1m 53s	remaining: 16m 21s
1013:	learn: 0.0204630	total: 1m 53s	remaining: 16m 49s
958:	learn: 0.0232774	total: 1m 54s	remaining: 17m 55s
1037:	learn: 0.0181938	total: 1m 53s	remaining: 16m 23s
1014:	learn: 0.0204318	total: 1m 54s	remaining: 16m 49s
1053:	learn: 0.0190397	total: 1m 54s	remaining: 16m 8s
1040:	learn: 0.0207343	total: 1m 54s	remaining: 16m 21s
959:	learn: 0.0232319	total: 1m 54s	remaining: 17m 54s
1038:	learn: 0.0181599	total: 1m 54s	remaining: 16m 23s
1015:	learn: 0.0203937	total: 1m 54s	remaining: 16m 49s
1054:	learn: 0.0190143	total: 1m 54s	remaining: 16m 8s
960:	learn: 0.0231979	total: 1m 54s	remaining: 17m 54s
1041:	learn: 0.0206943	total: 1m 54s	remaining: 16m 21s
1039:	learn: 0.0181277	total: 1m 54s	remaining: 16m 23s
1055:	learn: 0.0189937	total: 1m 54s	remaining: 16m 8s
1016:	learn: 0.0203618	total: 1m 54s	remaining: 16m 48s
1040:	learn: 0.0180931	total: 1m 54s	remaining: 16m 23s
1042:	learn: 0.0206541	total: 1m 54s	remaining: 16m 20s
961:	learn: 0.0231661	total: 1m 54s	remaining: 17m 54s
1056:	learn: 0.0189708	total: 1m 54s	remaining: 16m 7s
1017:	learn: 0.0203310	total: 1m 54s	remaining: 16m 48s
962:	learn: 0.0231373	total: 1m 54s	remaining: 17m 53s
1041:	learn: 0.0180720	total: 1m 54s	remaining: 16m 22s
1043:	learn: 0.0206085	total: 1m 54s	remaining: 16m 20s
1057:	learn: 0.0189461	total: 1m 54s	remaining: 16m 7s
1018:	learn: 0.0202984	total: 1m 54s	remaining: 16m 48s
963:	learn: 0.0230973	total: 1m 54s	remaining: 17m 53s
1044:	learn: 0.0205779	total: 1m 54s	remaining: 16m 20s
1042:	learn: 0.0180485	total: 1m 54s	remaining: 16m 22s
1058:	learn: 0.0189173	total: 1m 54s	remaining: 16m 7s
1019:	learn: 0.0202576	total: 1m 54s	remaining: 16m 48s
964:	learn: 0.0230557	total: 1m 54s	remaining: 17m 53s
1045:	learn: 0.0205396	total: 1m 54s	remaining: 16m 20s
1043:	learn: 0.0180273	total: 1m 54s	remaining: 16m 22s
1020:	learn: 0.0202333	total: 1m 54s	remaining: 16m 48s
1059:	learn: 0.0188777	total: 1m 54s	remaining: 16m 7s
1046:	learn: 0.0205071	total: 1m 54s	remaining: 16m 20s
1044:	learn: 0.0180076	total: 1m 54s	remaining: 16m 22s
965:	learn: 0.0230206	total: 1m 54s	remaining: 17m 53s
1021:	learn: 0.0202062	total: 1m 54s	remaining: 16m 47s
1060:	learn: 0.0188530	total: 1m 54s	remaining: 16m 7s
1047:	learn: 0.0204751	total: 1m 54s	remaining: 16m 19s
966:	learn: 0.0229924	total: 1m 54s	remaining: 17m 52s
1045:	learn: 0.0179871	total: 1m 54s	remaining: 16m 22s
1022:	learn: 0.0201789	total: 1m 54s	remaining: 16m 47s
1061:	learn: 0.0188232	total: 1m 54s	remaining: 16m 7s
1048:	learn: 0.0204432	total: 1m 54s	remaining: 16m 19s
967:	learn: 0.0229249	total: 1m 54s	remaining: 17m 52s
1046:	learn: 0.0179700	total: 1m 54s	remaining: 16m 22s
1023:	learn: 0.0201571	total: 1m 54s	remaining: 16m 47s
1062:	learn: 0.0187957	total: 1m 55s	remaining: 16m 7s
968:	learn: 0.0228898	total: 1m 55s	remaining: 17m 52s
1049:	learn: 0.0203987	total: 1m 54s	remaining: 16m 19s
1047:	learn: 0.0179493	total: 1m 54s	remaining: 16m 21s
1024:	learn: 0.0201164	total: 1m 55s	remaining: 16m 47s
969:	learn: 0.0228594	total: 1m 55s	remaining: 17m 51s
1048:	learn: 0.0179148	total: 1m 55s	remaining: 16m 21s
1063:	learn: 0.0187559	total: 1m 55s	remaining: 16m 7s
1050:	learn: 0.0203729	total: 1m 55s	remaining: 16m 19s
1025:	learn: 0.0200913	total: 1m 55s	remaining: 16m 47s
1049:	learn: 0.0178820	total: 1m 55s	remaining: 16m 21s
970:	learn: 0.0228266	total: 1m 55s	remaining: 17m 51s
1051:	learn: 0.0203486	total: 1m 55s	remaining: 16m 19s
1064:	learn: 0.0187277	total: 1m 55s	remaining: 16m 7s
1050:	learn: 0.0178581	total: 1m 55s	remaining: 16m 21s
1026:	learn: 0.0200595	total: 1m 55s	remaining: 16m 47s
971:	learn: 0.0227939	total: 1m 55s	remaining: 17m 51s
1052:	learn: 0.0203258	total: 1m 55s	remaining: 16m 18s
1065:	learn: 0.0186995	total: 1m 55s	remaining: 16m 6s
1027:	learn: 0.0200265	total: 1m 55s	remaining: 16m 46s
972:	learn: 0.0227723	total: 1m 55s	remaining: 17m 50s
1053:	learn: 0.0203010	total: 1m 55s	remaining: 16m 18s
1066:	learn: 0.0186737	total: 1m 55s	remaining: 16m 6s
1051:	learn: 0.0178339	total: 1m 55s	remaining: 16m 21s
973:	learn: 0.0227232	total: 1m 55s	remaining: 17m 50s
1054:	learn: 0.0202697	total: 1m 55s	remaining: 16m 18s
1028:	learn: 0.0199989	total: 1m 55s	remaining: 16m 46s
1067:	learn: 0.0186392	total: 1m 55s	remaining: 16m 6s
1052:	learn: 0.0178141	total: 1m 55s	remaining: 16m 21s
974:	learn: 0.0226961	total: 1m 55s	remaining: 17m 49s
1055:	learn: 0.0202326	total: 1m 55s	remaining: 16m 18s
1029:	learn: 0.0199601	total: 1m 55s	remaining: 16m 46s
1053:	learn: 0.0177855	total: 1m 55s	remaining: 16m 20s
975:	learn: 0.0226568	total: 1m 55s	remaining: 17m 49s
1068:	learn: 0.0186192	total: 1m 55s	remaining: 16m 6s
1056:	learn: 0.0201983	total: 1m 55s	remaining: 16m 17s
1030:	learn: 0.0199306	total: 1m 55s	remaining: 16m 46s
976:	learn: 0.0226164	total: 1m 55s	remaining: 17m 49s
1054:	learn: 0.0177593	total: 1m 55s	remaining: 16m 20s
1069:	learn: 0.0185814	total: 1m 55s	remaining: 16m 6s
1057:	learn: 0.0201812	total: 1m 55s	remaining: 16m 17s
1031:	learn: 0.0198816	total: 1m 55s	remaining: 16m 46s
977:	learn: 0.0225634	total: 1m 55s	remaining: 17m 48s
1070:	learn: 0.0185579	total: 1m 55s	remaining: 16m 6s
1058:	learn: 0.0201471	total: 1m 55s	remaining: 16m 17s
1055:	learn: 0.0177371	total: 1m 55s	remaining: 16m 20s
1032:	learn: 0.0198438	total: 1m 55s	remaining: 16m 45s
978:	learn: 0.0225318	total: 1m 55s	remaining: 17m 48s
1059:	learn: 0.0201212	total: 1m 55s	remaining: 16m 17s
1071:	learn: 0.0185249	total: 1m 56s	remaining: 16m 6s
1056:	learn: 0.0177139	total: 1m 55s	remaining: 16m 20s
1033:	learn: 0.0197984	total: 1m 55s	remaining: 16m 45s
979:	learn: 0.0224967	total: 1m 56s	remaining: 17m 48s
1072:	learn: 0.0184905	total: 1m 56s	remaining: 16m 5s
1060:	learn: 0.0201058	total: 1m 55s	remaining: 16m 17s
1057:	learn: 0.0176859	total: 1m 56s	remaining: 16m 20s
980:	learn: 0.0224558	total: 1m 56s	remaining: 17m 47s
1034:	learn: 0.0197675	total: 1m 56s	remaining: 16m 45s
1073:	learn: 0.0184708	total: 1m 56s	remaining: 16m 5s
1061:	learn: 0.0200910	total: 1m 56s	remaining: 16m 16s
1058:	learn: 0.0176731	total: 1m 56s	remaining: 16m 20s
981:	learn: 0.0224287	total: 1m 56s	remaining: 17m 47s
1062:	learn: 0.0200647	total: 1m 56s	remaining: 16m 16s
1035:	learn: 0.0197531	total: 1m 56s	remaining: 16m 45s
1074:	learn: 0.0184293	total: 1m 56s	remaining: 16m 5s
1059:	learn: 0.0176422	total: 1m 56s	remaining: 16m 20s
982:	learn: 0.0223850	total: 1m 56s	remaining: 17m 47s
1063:	learn: 0.0200302	total: 1m 56s	remaining: 16m 16s
1036:	learn: 0.0197142	total: 1m 56s	remaining: 16m 45s
1075:	learn: 0.0184103	total: 1m 56s	remaining: 16m 5s
1060:	learn: 0.0176189	total: 1m 56s	remaining: 16m 19s
983:	learn: 0.0223375	total: 1m 56s	remaining: 17m 46s
1064:	learn: 0.0200022	total: 1m 56s	remaining: 16m 16s
1037:	learn: 0.0196902	total: 1m 56s	remaining: 16m 45s
1076:	learn: 0.0183870	total: 1m 56s	remaining: 16m 5s
1061:	learn: 0.0175900	total: 1m 56s	remaining: 16m 19s
1065:	learn: 0.0199703	total: 1m 56s	remaining: 16m 15s
984:	learn: 0.0223097	total: 1m 56s	remaining: 17m 46s
1038:	learn: 0.0196619	total: 1m 56s	remaining: 16m 45s
1077:	learn: 0.0183635	total: 1m 56s	remaining: 16m 5s
1062:	learn: 0.0175605	total: 1m 56s	remaining: 16m 19s
1066:	learn: 0.0199415	total: 1m 56s	remaining: 16m 15s
1078:	learn: 0.0183258	total: 1m 56s	remaining: 16m 4s
985:	learn: 0.0222612	total: 1m 56s	remaining: 17m 46s
1039:	learn: 0.0196357	total: 1m 56s	remaining: 16m 45s
1067:	learn: 0.0199130	total: 1m 56s	remaining: 16m 15s
1063:	learn: 0.0175376	total: 1m 56s	remaining: 16m 19s
1079:	learn: 0.0183119	total: 1m 56s	remaining: 16m 4s
1068:	learn: 0.0198812	total: 1m 56s	remaining: 16m 15s
986:	learn: 0.0222217	total: 1m 56s	remaining: 17m 46s
1080:	learn: 0.0182855	total: 1m 56s	remaining: 16m 4s
1064:	learn: 0.0175026	total: 1m 56s	remaining: 16m 19s
1040:	learn: 0.0196216	total: 1m 56s	remaining: 16m 45s
1069:	learn: 0.0198369	total: 1m 56s	remaining: 16m 14s
1081:	learn: 0.0182591	total: 1m 56s	remaining: 16m 3s
1065:	learn: 0.0174945	total: 1m 56s	remaining: 16m 19s
987:	learn: 0.0221921	total: 1m 56s	remaining: 17m 46s
1041:	learn: 0.0195966	total: 1m 56s	remaining: 16m 44s
1070:	learn: 0.0198090	total: 1m 56s	remaining: 16m 14s
1082:	learn: 0.0182333	total: 1m 57s	remaining: 16m 3s
1066:	learn: 0.0174702	total: 1m 56s	remaining: 16m 19s
988:	learn: 0.0221439	total: 1m 57s	remaining: 17m 46s
1042:	learn: 0.0195664	total: 1m 56s	remaining: 16m 44s
1071:	learn: 0.0197748	total: 1m 56s	remaining: 16m 14s
1083:	learn: 0.0181954	total: 1m 57s	remaining: 16m 3s
1067:	learn: 0.0174589	total: 1m 57s	remaining: 16m 18s
1072:	learn: 0.0197456	total: 1m 57s	remaining: 16m 13s
1043:	learn: 0.0195499	total: 1m 57s	remaining: 16m 44s
989:	learn: 0.0221051	total: 1m 57s	remaining: 17m 46s
1068:	learn: 0.0174363	total: 1m 57s	remaining: 16m 18s
1084:	learn: 0.0181760	total: 1m 57s	remaining: 16m 3s
1073:	learn: 0.0197294	total: 1m 57s	remaining: 16m 13s
1044:	learn: 0.0195216	total: 1m 57s	remaining: 16m 44s
990:	learn: 0.0220669	total: 1m 57s	remaining: 17m 46s
1069:	learn: 0.0174147	total: 1m 57s	remaining: 16m 18s
1085:	learn: 0.0181440	total: 1m 57s	remaining: 16m 3s
1074:	learn: 0.0197040	total: 1m 57s	remaining: 16m 13s
1045:	learn: 0.0194999	total: 1m 57s	remaining: 16m 44s
1086:	learn: 0.0181213	total: 1m 57s	remaining: 16m 3s
1070:	learn: 0.0173901	total: 1m 57s	remaining: 16m 18s
991:	learn: 0.0220333	total: 1m 57s	remaining: 17m 46s
1075:	learn: 0.0196833	total: 1m 57s	remaining: 16m 12s
1046:	learn: 0.0194814	total: 1m 57s	remaining: 16m 43s
1071:	learn: 0.0173532	total: 1m 57s	remaining: 16m 17s
1087:	learn: 0.0180995	total: 1m 57s	remaining: 16m 2s
992:	learn: 0.0219999	total: 1m 57s	remaining: 17m 46s
1076:	learn: 0.0196575	total: 1m 57s	remaining: 16m 12s
1047:	learn: 0.0194476	total: 1m 57s	remaining: 16m 43s
1072:	learn: 0.0173330	total: 1m 57s	remaining: 16m 17s
1088:	learn: 0.0180697	total: 1m 57s	remaining: 16m 2s
993:	learn: 0.0219607	total: 1m 57s	remaining: 17m 45s
1077:	learn: 0.0196254	total: 1m 57s	remaining: 16m 12s
994:	learn: 0.0219246	total: 1m 57s	remaining: 17m 45s
1073:	learn: 0.0173079	total: 1m 57s	remaining: 16m 17s
1048:	learn: 0.0194217	total: 1m 57s	remaining: 16m 43s
1089:	learn: 0.0180531	total: 1m 57s	remaining: 16m 2s
1078:	learn: 0.0196029	total: 1m 57s	remaining: 16m 12s

995:	learn: 0.0218902	total: 1m 57s	remaining: 17m 44s
1049:	learn: 0.0193953	total: 1m 57s	remaining: 16m 43s
1074:	learn: 0.0172721	total: 1m 57s	remaining: 16m 17s
1079:	learn: 0.0195781	total: 1m 57s	remaining: 16m 12s
1090:	learn: 0.0180361	total: 1m 57s	remaining: 16m 2s
996:	learn: 0.0218658	total: 1m 57s	remaining: 17m 44s
1075:	learn: 0.0172501	total: 1m 57s	remaining: 16m 16s
1050:	learn: 0.0193580	total: 1m 57s	remaining: 16m 43s
1091:	learn: 0.0180217	total: 1m 57s	remaining: 16m 2s
997:	learn: 0.0218428	total: 1m 57s	remaining: 17m 43s
1080:	learn: 0.0195580	total: 1m 57s	remaining: 16m 12s
1076:	learn: 0.0172244	total: 1m 57s	remaining: 16m 16s
1051:	learn: 0.0193418	total: 1m 57s	remaining: 16m 43s
1092:	learn: 0.0179963	total: 1m 58s	remaining: 16m 2s
1081:	learn: 0.0195220	total: 1m 57s	remaining: 16m 12s
1077:	learn: 0.0172051	total: 1m 57s	remaining: 16m 16s
998:	learn: 0.0218156	total: 1m 58s	remaining: 17m 43s
1052:	learn: 0.0193145	total: 1m 58s	remaining: 16m 43s
1082:	learn: 0.0195050	total: 1m 58s	remaining: 16m 11s
1093:	learn: 0.0179609	total: 1m 58s	remaining: 16m 2s
1078:	learn: 0.0171849	total: 1m 58s	remaining: 16m 16s
999:	learn: 0.0217905	total: 1m 58s	remaining: 17m 43s
1083:	learn: 0.0194702	total: 1m 58s	remaining: 16m 11s
1053:	learn: 0.0192755	total: 1m 58s	remaining: 16m 43s
1094:	learn: 0.0179379	total: 1m 58s	remaining: 16m 1s
1000:	learn: 0.0217722	total: 1m 58s	remaining: 17m 43s
1079:	learn: 0.0171613	total: 1m 58s	remaining: 16m 16s
1095:	learn: 0.0179239	total: 1m 58s	remaining: 16m 1s
1054:	learn: 0.0192564	total: 1m 58s	remaining: 16m 42s
1084:	learn: 0.0194496	total: 1m 58s	remaining: 16m 11s
1080:	learn: 0.0171437	total: 1m 58s	remaining: 16m 15s
1001:	learn: 0.0217411	total: 1m 58s	remaining: 17m 43s
1096:	learn: 0.0179015	total: 1m 58s	remaining: 16m 1s
1055:	learn: 0.0192422	total: 1m 58s	remaining: 16m 42s
1097:	learn: 0.0178744	total: 1m 58s	remaining: 16m
1085:	learn: 0.0194101	total: 1m 58s	remaining: 16m 11s
1081:	learn: 0.0171324	total: 1m 58s	remaining: 16m 15s
1002:	learn: 0.0217237	total: 1m 58s	remaining: 17m 42s
1098:	learn: 0.0178368	total: 1m 58s	remaining: 16m
1056:	learn: 0.0192117	total: 1m 58s	remaining: 16m 42s
1082:	learn: 0.0171043	total: 1m 58s	remaining: 16m 15s
1086:	learn: 0.0193784	total: 1m 58s	remaining: 16m 11s
1003:	learn: 0.0216869	total: 1m 58s	remaining: 17m 42s
1099:	learn: 0.0178244	total: 1m 58s	remaining: 16m
1083:	learn: 0.0170768	total: 1m 58s	remaining: 16m 15s
1057:	learn: 0.0191849	total: 1m 58s	remaining: 16m 42s
1087:	learn: 0.0193551	total: 1m 58s	remaining: 16m 11s
1100:	learn: 0.0177816	total: 1m 58s	remaining: 15m 59s
1004:	learn: 0.0216559	total: 1m 58s	remaining: 17m 42s
1058:	learn: 0.0191525	total: 1m 58s	remaining: 16m 42s
1101:	learn: 0.0177655	total: 1m 58s	remaining: 15m 59s
1084:	learn: 0.0170416	total: 1m 58s	remaining: 16m 15s
1088:	learn: 0.0193204	total: 1m 58s	remaining: 16m 11s
1005:	learn: 0.0216293	total: 1m 58s	remaining: 17m 42s
1059:	learn: 0.0191250	total: 1m 58s	remaining: 16m 41s
1089:	learn: 0.0193003	total: 1m 58s	remaining: 16m 10s
1102:	learn: 0.0177432	total: 1m 58s	remaining: 15m 59s
1085:	learn: 0.0170241	total: 1m 58s	remaining: 16m 15s
1060:	learn: 0.0191001	total: 1m 58s	remaining: 16m 41s
1006:	learn: 0.0215904	total: 1m 58s	remaining: 17m 42s
1086:	learn: 0.0169979	total: 1m 58s	remaining: 16m 14s
1090:	learn: 0.0192720	total: 1m 58s	remaining: 16m 10s
1103:	learn: 0.0177218	total: 1m 59s	remaining: 15m 59s
1061:	learn: 0.0190642	total: 1m 58s	remaining: 16m 41s
1007:	learn: 0.0215748	total: 1m 59s	remaining: 17m 41s
1087:	learn: 0.0169677	total: 1m 58s	remaining: 16m 14s
1104:	learn: 0.0176920	total: 1m 59s	remaining: 15m 58s
1091:	learn: 0.0192490	total: 1m 59s	remaining: 16m 10s
1062:	learn: 0.0190423	total: 1m 59s	remaining: 16m 41s
1105:	learn: 0.0176648	total: 1m 59s	remaining: 15m 58s
1008:	learn: 0.0215432	total: 1m 59s	remaining: 17m 41s
1088:	learn: 0.0169518	total: 1m 59s	remaining: 16m 14s
1092:	learn: 0.0192221	total: 1m 59s	remaining: 16m 10s
1063:	learn: 0.0190174	total: 1m 59s	remaining: 16m 40s
1106:	learn: 0.0176297	total: 1m 59s	remaining: 15m 58s
1009:	learn: 0.0215130	total: 1m 59s	remaining: 17m 41s
1064:	learn: 0.0189876	total: 1m 59s	remaining: 16m 40s
1089:	learn: 0.0169273	total: 1m 59s	remaining: 16m 14s
1093:	learn: 0.0191923	total: 1m 59s	remaining: 16m 10s
1107:	learn: 0.0176098	total: 1m 59s	remaining: 15m 58s
1010:	learn: 0.0214807	total: 1m 59s	remaining: 17m 41s
1090:	learn: 0.0169095	total: 1m 59s	remaining: 16m 14s
1065:	learn: 0.0189486	total: 1m 59s	remaining: 16m 40s
1094:	learn: 0.0191570	total: 1m 59s	remaining: 16m 10s
1108:	learn: 0.0175787	total: 1m 59s	remaining: 15m 57s
1011:	learn: 0.0214532	total: 1m 59s	remaining: 17m 41s
1091:	learn: 0.0168742	total: 1m 59s	remaining: 16m 13s
1066:	learn: 0.0189284	total: 1m 59s	remaining: 16m 39s
1109:	learn: 0.0175517	total: 1m 59s	remaining: 15m 57s
1095:	learn: 0.0191407	total: 1m 59s	remaining: 16m 10s
1092:	learn: 0.0168644	total: 1m 59s	remaining: 16m 13s
1012:	learn: 0.0214269	total: 1m 59s	remaining: 17m 41s
1067:	learn: 0.0188867	total: 1m 59s	remaining: 16m 39s
1110:	learn: 0.0175256	total: 1m 59s	remaining: 15m 57s
1096:	learn: 0.0191182	total: 1m 59s	remaining: 16m 10s
1093:	learn: 0.0168270	total: 1m 59s	remaining: 16m 13s
1111:	learn: 0.0174956	total: 1m 59s	remaining: 15m 56s
1068:	learn: 0.0188461	total: 1m 59s	remaining: 16m 39s
1013:	learn: 0.0214052	total: 1m 59s	remaining: 17m 40s
1094:	learn: 0.0168092	total: 1m 59s	remaining: 16m 13s
1097:	learn: 0.0190942	total: 1m 59s	remaining: 16m 10s
1112:	learn: 0.0174687	total: 1m 59s	remaining: 15m 56s
1069:	learn: 0.0188124	total: 1m 59s	remaining: 16m 39s
1095:	learn: 0.0167830	total: 1m 59s	remaining: 16m 12s
1014:	learn: 0.0213723	total: 1m 59s	remaining: 17m 40s
1098:	learn: 0.0190715	total: 1m 59s	remaining: 16m 10s
1070:	learn: 0.0187826	total: 1m 59s	remaining: 16m 39s
1113:	learn: 0.0174483	total: 1m 59s	remaining: 15m 56s
1096:	learn: 0.0167628	total: 1m 59s	remaining: 16m 12s
1015:	learn: 0.0213378	total: 1m 59s	remaining: 17m 40s
1099:	learn: 0.0190562	total: 1m 59s	remaining: 16m 9s
1071:	learn: 0.0187538	total: 1m 59s	remaining: 16m 38s
1114:	learn: 0.0174283	total: 2m	remaining: 15m 56s
1097:	learn: 0.0167476	total: 1m 59s	remaining: 16m 12s
1016:	learn: 0.0212985	total: 2m	remaining: 17m 40s
1100:	learn: 0.0190360	total: 1m 59s	remaining: 16m 9s
1072:	learn: 0.0187196	total: 2m	remaining: 16m 38s
1115:	learn: 0.0174000	total: 2m	remaining: 15m 56s
1098:	learn: 0.0167158	total: 2m	remaining: 16m 12s
1073:	learn: 0.0186954	total: 2m	remaining: 16m 38s
1017:	learn: 0.0212642	total: 2m	remaining: 17m 40s
1101:	learn: 0.0190078	total: 2m	remaining: 16m 9s
1116:	learn: 0.0173665	total: 2m	remaining: 15m 56s
1099:	learn: 0.0166976	total: 2m	remaining: 16m 12s
1074:	learn: 0.0186799	total: 2m	remaining: 16m 37s
1018:	learn: 0.0212389	total: 2m	remaining: 17m 40s
1102:	learn: 0.0189886	total: 2m	remaining: 16m 9s
1100:	learn: 0.0166899	total: 2m	remaining: 16m 11s
1117:	learn: 0.0173497	total: 2m	remaining: 15m 56s
1019:	learn: 0.0212002	total: 2m	remaining: 17m 39s
1075:	learn: 0.0186549	total: 2m	remaining: 16m 38s
1103:	learn: 0.0189577	total: 2m	remaining: 16m 9s
1101:	learn: 0.0166675	total: 2m	remaining: 16m 11s
1118:	learn: 0.0173230	total: 2m	remaining: 15m 55s
1076:	learn: 0.0186273	total: 2m	remaining: 16m 37s
1104:	learn: 0.0189331	total: 2m	remaining: 16m 9s
1020:	learn: 0.0211540	total: 2m	remaining: 17m 39s
1102:	learn: 0.0166452	total: 2m	remaining: 16m 11s
1119:	learn: 0.0173034	total: 2m	remaining: 15m 55s
1077:	learn: 0.0186170	total: 2m	remaining: 16m 37s
1105:	learn: 0.0188961	total: 2m	remaining: 16m 8s
1103:	learn: 0.0166102	total: 2m	remaining: 16m 11s
1120:	learn: 0.0172728	total: 2m	remaining: 15m 55s
1021:	learn: 0.0211124	total: 2m	remaining: 17m 39s
1078:	learn: 0.0185966	total: 2m	remaining: 16m 37s
1106:	learn: 0.0188638	total: 2m	remaining: 16m 8s
1121:	learn: 0.0172574	total: 2m	remaining: 15m 55s
1104:	learn: 0.0165903	total: 2m	remaining: 16m 10s
1107:	learn: 0.0188336	total: 2m	remaining: 16m 8s
1022:	learn: 0.0210872	total: 2m	remaining: 17m 39s
1105:	learn: 0.0165719	total: 2m	remaining: 16m 10s
1079:	learn: 0.0185666	total: 2m	remaining: 16m 37s
1108:	learn: 0.0188118	total: 2m	remaining: 16m 8s
1123:	learn: 0.0171966	total: 2m	remaining: 15m 54s
1023:	learn: 0.0210618	total: 2m	remaining: 17m 39s
1080:	learn: 0.0185476	total: 2m	remaining: 16m 37s
1106:	learn: 0.0165590	total: 2m	remaining: 16m 10s
1124:	learn: 0.0171673	total: 2m	remaining: 15m 54s
1024:	learn: 0.0210323	total: 2m	remaining: 17m 39s
1109:	learn: 0.0187832	total: 2m	remaining: 16m 8s
1081:	learn: 0.0185133	total: 2m	remaining: 16m 36s
1125:	learn: 0.0171399	total: 2m 1s	remaining: 15m 54s
1107:	learn: 0.0165338	total: 2m	remaining: 16m 10s
1025:	learn: 0.0210045	total: 2m 1s	remaining: 17m 38s
1082:	learn: 0.0185005	total: 2m 1s	remaining: 16m 36s
1110:	learn: 0.0187497	total: 2m 1s	remaining: 16m 8s
1108:	learn: 0.0165090	total: 2m 1s	remaining: 16m 10s
1026:	learn: 0.0209766	total: 2m 1s	remaining: 17m 38s
1126:	learn: 0.0171289	total: 2m 1s	remaining: 15m 54s
1083:	learn: 0.0184696	total: 2m 1s	remaining: 16m 36s
1111:	learn: 0.0187118	total: 2m 1s	remaining: 16m 8s
1027:	learn: 0.0209544	total: 2m 1s	remaining: 17m 38s
1109:	learn: 0.0164984	total: 2m 1s	remaining: 16m 10s
1127:	learn: 0.0171115	total: 2m 1s	remaining: 15m 54s
1084:	learn: 0.0184452	total: 2m 1s	remaining: 16m 36s
1112:	learn: 0.0186853	total: 2m 1s	remaining: 16m 7s
1028:	learn: 0.0209121	total: 2m 1s	remaining: 17m 37s
1110:	learn: 0.0164795	total: 2m 1s	remaining: 16m 10s
1128:	learn: 0.0170955	total: 2m 1s	remaining: 15m 53s
1085:	learn: 0.0184317	total: 2m 1s	remaining: 16m 35s
1113:	learn: 0.0186576	total: 2m 1s	remaining: 16m 7s
1029:	learn: 0.0208897	total: 2m 1s	remaining: 17m 37s
1111:	learn: 0.0164520	total: 2m 1s	remaining: 16m 9s
1129:	learn: 0.0170652	total: 2m 1s	remaining: 15m 53s
1114:	learn: 0.0186375	total: 2m 1s	remaining: 16m 7s
1086:	learn: 0.0184030	total: 2m 1s	remaining: 16m 35s
1130:	learn: 0.0170470	total: 2m 1s	remaining: 15m 53s
1112:	learn: 0.0164341	total: 2m 1s	remaining: 16m 9s
1030:	learn: 0.0208585	total: 2m 1s	remaining: 17m 37s
1115:	learn: 0.0186209	total: 2m 1s	remaining: 16m 7s
1087:	learn: 0.0183638	total: 2m 1s	remaining: 16m 35s
1113:	learn: 0.0164079	total: 2m 1s	remaining: 16m 9s
1131:	learn: 0.0170289	total: 2m 1s	remaining: 15m 53s
1031:	learn: 0.0208302	total: 2m 1s	remaining: 17m 37s
1116:	learn: 0.0185934	total: 2m 1s	remaining: 16m 6s
1088:	learn: 0.0183206	total: 2m 1s	remaining: 16m 35s
1114:	learn: 0.0163699	total: 2m 1s	remaining: 16m 9s
1132:	learn: 0.0170086	total: 2m 1s	remaining: 15m 52s
1032:	learn: 0.0208114	total: 2m 1s	remaining: 17m 36s
1117:	learn: 0.0185596	total: 2m 1s	remaining: 16m 6s
1089:	learn: 0.0183057	total: 2m 1s	remaining: 16m 35s
1133:	learn: 0.0169834	total: 2m 1s	remaining: 15m 52s
1115:	learn: 0.0163451	total: 2m 1s	remaining: 16m 9s
1118:	learn: 0.0185394	total: 2m 1s	remaining: 16m 6s
1033:	learn: 0.0207786	total: 2m 1s	remaining: 17m 36s
1116:	learn: 0.0163324	total: 2m 1s	remaining: 16m 8s
1090:	learn: 0.0182794	total: 2m 1s	remaining: 16m 35s
1134:	learn: 0.0169662	total: 2m 1s	remaining: 15m 52s
1119:	learn: 0.0185226	total: 2m 1s	remaining: 16m 6s
1034:	learn: 0.0207437	total: 2m 1s	remaining: 17m 36s
1117:	learn: 0.0163140	total: 2m 1s	remaining: 16m 8s
1135:	learn: 0.0169503	total: 2m 2s	remaining: 15m 52s
1091:	learn: 0.0182585	total: 2m 2s	remaining: 16m 35s
1035:	learn: 0.0207166	total: 2m 2s	remaining: 17m 36s
1120:	learn: 0.0185090	total: 2m 1s	remaining: 16m 6s
1118:	learn: 0.0163024	total: 2m 2s	remaining: 16m 8s
1136:	learn: 0.0169355	total: 2m 2s	remaining: 15m 52s
1036:	learn: 0.0206926	total: 2m 2s	remaining: 17m 35s
1092:	learn: 0.0182325	total: 2m 2s	remaining: 16m 34s
1137:	learn: 0.0169165	total: 2m 2s	remaining: 15m 51s
1121:	learn: 0.0184887	total: 2m 2s	remaining: 16m 6s
1119:	learn: 0.0162838	total: 2m 2s	remaining: 16m 8s
1037:	learn: 0.0206691	total: 2m 2s	remaining: 17m 35s
1093:	learn: 0.0181998	total: 2m 2s	remaining: 16m 34s
1138:	learn: 0.0168971	total: 2m 2s	remaining: 15m 51s
1122:	learn: 0.0184650	total: 2m 2s	remaining: 16m 5s
1120:	learn: 0.0162598	total: 2m 2s	remaining: 16m 8s
1038:	learn: 0.0206346	total: 2m 2s	remaining: 17m 35s
1094:	learn: 0.0181827	total: 2m 2s	remaining: 16m 34s
1139:	learn: 0.0168752	total: 2m 2s	remaining: 15m 51s
1123:	learn: 0.0184428	total: 2m 2s	remaining: 16m 5s
1121:	learn: 0.0162443	total: 2m 2s	remaining: 16m 8s
1039:	learn: 0.0206095	total: 2m 2s	remaining: 17m 34s
1095:	learn: 0.0181544	total: 2m 2s	remaining: 16m 34s
1140:	learn: 0.0168502	total: 2m 2s	remaining: 15m 51s
1124:	learn: 0.0184221	total: 2m 2s	remaining: 16m 5s
1040:	learn: 0.0205780	total: 2m 2s	remaining: 17m 34s
1122:	learn: 0.0162219	total: 2m 2s	remaining: 16m 8s
1141:	learn: 0.0168113	total: 2m 2s	remaining: 15m 50s
1096:	learn: 0.0181348	total: 2m 2s	remaining: 16m 34s
1041:	learn: 0.0205560	total: 2m 2s	remaining: 17m 34s
1125:	learn: 0.0183906	total: 2m 2s	remaining: 16m 5s
1142:	learn: 0.0167966	total: 2m 2s	remaining: 15m 50s
1123:	learn: 0.0162048	total: 2m 2s	remaining: 16m 8s
1042:	learn: 0.0205433	total: 2m 2s	remaining: 17m 33s
1097:	learn: 0.0181022	total: 2m 2s	remaining: 16m 34s
1126:	learn: 0.0183640	total: 2m 2s	remaining: 16m 5s
1124:	learn: 0.0161865	total: 2m 2s	remaining: 16m 7s
1143:	learn: 0.0167801	total: 2m 2s	remaining: 15m 50s
1043:	learn: 0.0205090	total: 2m 2s	remaining: 17m 33s
1098:	learn: 0.0180672	total: 2m 2s	remaining: 16m 34s
1127:	learn: 0.0183293	total: 2m 2s	remaining: 16m 5s
1144:	learn: 0.0167582	total: 2m 2s	remaining: 15m 50s
1125:	learn: 0.0161582	total: 2m 2s	remaining: 16m 7s
1099:	learn: 0.0180337	total: 2m 2s	remaining: 16m 34s
1044:	learn: 0.0204847	total: 2m 2s	remaining: 17m 33s
1128:	learn: 0.0183129	total: 2m 2s	remaining: 16m 5s
1126:	learn: 0.0161317	total: 2m 2s	remaining: 16m 7s
1145:	learn: 0.0167304	total: 2m 2s	remaining: 15m 50s
1100:	learn: 0.0180058	total: 2m 2s	remaining: 16m 33s
1129:	learn: 0.0182928	total: 2m 2s	remaining: 16m 4s
1045:	learn: 0.0204516	total: 2m 3s	remaining: 17m 33s
1127:	learn: 0.0160917	total: 2m 2s	remaining: 16m 7s
1101:	learn: 0.0179746	total: 2m 3s	remaining: 16m 33s
1146:	learn: 0.0167119	total: 2m 3s	remaining: 15m 50s
1130:	learn: 0.0182756	total: 2m 3s	remaining: 16m 4s
1128:	learn: 0.0160713	total: 2m 3s	remaining: 16m 6s
1046:	learn: 0.0204274	total: 2m 3s	remaining: 17m 33s
1131:	learn: 0.0182394	total: 2m 3s	remaining: 16m 4s
1102:	learn: 0.0179504	total: 2m 3s	remaining: 16m 33s
1147:	learn: 0.0166827	total: 2m 3s	remaining: 15m 50s
1129:	learn: 0.0160399	total: 2m 3s	remaining: 16m 6s
1132:	learn: 0.0182049	total: 2m 3s	remaining: 16m 3s
1047:	learn: 0.0203919	total: 2m 3s	remaining: 17m 33s
1103:	learn: 0.0179151	total: 2m 3s	remaining: 16m 33s
1148:	learn: 0.0166503	total: 2m 3s	remaining: 15m 50s
1133:	learn: 0.0181898	total: 2m 3s	remaining: 16m 3s
1130:	learn: 0.0160236	total: 2m 3s	remaining: 16m 6s
1048:	learn: 0.0203700	total: 2m 3s	remaining: 17m 32s
1104:	learn: 0.0178798	total: 2m 3s	remaining: 16m 32s
1134:	learn: 0.0181668	total: 2m 3s	remaining: 16m 3s
1149:	learn: 0.0166246	total: 2m 3s	remaining: 15m 50s
1131:	learn: 0.0160041	total: 2m 3s	remaining: 16m 6s
1105:	learn: 0.0178580	total: 2m 3s	remaining: 16m 32s
1135:	learn: 0.0181411	total: 2m 3s	remaining: 16m 2s
1049:	learn: 0.0203375	total: 2m 3s	remaining: 17m 32s
1132:	learn: 0.0159743	total: 2m 3s	remaining: 16m 6s
1150:	learn: 0.0165994	total: 2m 3s	remaining: 15m 50s
1106:	learn: 0.0178341	total: 2m 3s	remaining: 16m 32s
1136:	learn: 0.0181097	total: 2m 3s	remaining: 16m 2s
1050:	learn: 0.0203188	total: 2m 3s	remaining: 17m 32s
1133:	learn: 0.0159532	total: 2m 3s	remaining: 16m 5s
1151:	learn: 0.0165904	total: 2m 3s	remaining: 15m 50s
1137:	learn: 0.0180887	total: 2m 3s	remaining: 16m 2s
1051:	learn: 0.0202849	total: 2m 3s	remaining: 17m 32s
1107:	learn: 0.0177960	total: 2m 3s	remaining: 16m 32s
1152:	learn: 0.0165584	total: 2m 3s	remaining: 15m 49s
1134:	learn: 0.0159309	total: 2m 3s	remaining: 16m 5s
n: 0.0187579	total: 1m 51s	remaining: 16m 28s

 al:a1138:	learn: 0.0180707	total: 2m 3s	remaining: 16m 2s
1052:	learn: 0.0202605	total: 2m 3s	remaining: 17m 31s
1108:	learn: 0.0177668	total: 2m 3s	remaining: 16m 32s
1153:	learn: 0.0165297	total: 2m 3s	remaining: 15m 49s
1135:	learn: 0.0159099	total: 2m 3s	remaining: 16m 5s
1139:	learn: 0.0180432	total: 2m 3s	remaining: 16m 2s
1053:	learn: 0.0202366	total: 2m 3s	remaining: 17m 31s
1109:	learn: 0.0177350	total: 2m 3s	remaining: 16m 32s
1154:	learn: 0.0165217	total: 2m 3s	remaining: 15m 49s
1136:	learn: 0.0158882	total: 2m 3s	remaining: 16m 5s
1140:	learn: 0.0180221	total: 2m 3s	remaining: 16m 1s
1054:	learn: 0.0201941	total: 2m 3s	remaining: 17m 31s
1155:	learn: 0.0165022	total: 2m 4s	remaining: 15m 49s
1110:	learn: 0.0177113	total: 2m 4s	remaining: 16m 32s
1137:	learn: 0.0158546	total: 2m 3s	remaining: 16m 5s
1141:	learn: 0.0179939	total: 2m 3s	remaining: 16m 1s
1055:	learn: 0.0201574	total: 2m 4s	remaining: 17m 30s
1156:	learn: 0.0164735	total: 2m 4s	remaining: 15m 49s
1138:	learn: 0.0158422	total: 2m 4s	remaining: 16m 5s
1111:	learn: 0.0176872	total: 2m 4s	remaining: 16m 32s
1142:	learn: 0.0179658	total: 2m 4s	remaining: 16m 1s
1056:	learn: 0.0201256	total: 2m 4s	remaining: 17m 30s
1139:	learn: 0.0158152	total: 2m 4s	remaining: 16m 4s
1157:	learn: 0.0164514	total: 2m 4s	remaining: 15m 49s
1143:	learn: 0.0179475	total: 2m 4s	remaining: 16m 1s
1112:	learn: 0.0176609	total: 2m 4s	remaining: 16m 31s
1140:	learn: 0.0157876	total: 2m 4s	remaining: 16m 4s
1144:	learn: 0.0179194	total: 2m 4s	remaining: 16m
1057:	learn: 0.0201000	total: 2m 4s	remaining: 17m 30s
1158:	learn: 0.0164262	total: 2m 4s	remaining: 15m 49s
1113:	learn: 0.0176302	total: 2m 4s	remaining: 16m 31s
1141:	learn: 0.0157777	total: 2m 4s	remaining: 16m 4s
1145:	learn: 0.0178961	total: 2m 4s	remaining: 16m
1114:	learn: 0.0175955	total: 2m 4s	remaining: 16m 31s
1058:	learn: 0.0200568	total: 2m 4s	remaining: 17m 31s
1146:	learn: 0.0178731	total: 2m 4s	remaining: 16m
1159:	learn: 0.0164060	total: 2m 4s	remaining: 15m 49s
1142:	learn: 0.0157551	total: 2m 4s	remaining: 16m 4s
1115:	learn: 0.0175663	total: 2m 4s	remaining: 16m 31s
1147:	learn: 0.0178484	total: 2m 4s	remaining: 15m 59s
1059:	learn: 0.0200316	total: 2m 4s	remaining: 17m 30s
1116:	learn: 0.0175466	total: 2m 4s	remaining: 16m 30s
1160:	learn: 0.0163811	total: 2m 4s	remaining: 15m 49s
1143:	learn: 0.0157311	total: 2m 4s	remaining: 16m 4s
1060:	learn: 0.0199990	total: 2m 4s	remaining: 17m 30s
1148:	learn: 0.0178194	total: 2m 4s	remaining: 15m 59s
1117:	learn: 0.0175184	total: 2m 4s	remaining: 16m 30s
1161:	learn: 0.0163550	total: 2m 4s	remaining: 15m 49s
1144:	learn: 0.0157154	total: 2m 4s	remaining: 16m 4s
1061:	learn: 0.0199676	total: 2m 4s	remaining: 17m 30s
1118:	learn: 0.0175022	total: 2m 4s	remaining: 16m 30s
1149:	learn: 0.0178054	total: 2m 4s	remaining: 15m 59s
1145:	learn: 0.0156816	total: 2m 4s	remaining: 16m 3s
1162:	learn: 0.0163282	total: 2m 4s	remaining: 15m 48s
1119:	learn: 0.0174917	total: 2m 4s	remaining: 16m 29s
1150:	learn: 0.0177852	total: 2m 4s	remaining: 15m 59s
1062:	learn: 0.0199384	total: 2m 4s	remaining: 17m 30s
1146:	learn: 0.0156511	total: 2m 4s	remaining: 16m 3s
1163:	learn: 0.0163077	total: 2m 4s	remaining: 15m 48s
1120:	learn: 0.0174805	total: 2m 4s	remaining: 16m 29s
1151:	learn: 0.0177624	total: 2m 4s	remaining: 15m 59s
1063:	learn: 0.0199130	total: 2m 5s	remaining: 17m 30s
1147:	learn: 0.0156236	total: 2m 4s	remaining: 16m 3s
1164:	learn: 0.0162858	total: 2m 5s	remaining: 15m 48s
1121:	learn: 0.0174604	total: 2m 5s	remaining: 16m 29s
1064:	learn: 0.0198842	total: 2m 5s	remaining: 17m 29s
1152:	learn: 0.0177286	total: 2m 5s	remaining: 15m 59s
1148:	learn: 0.0156163	total: 2m 5s	remaining: 16m 3s
1122:	learn: 0.0174435	total: 2m 5s	remaining: 16m 28s
1165:	learn: 0.0162595	total: 2m 5s	remaining: 15m 48s
1065:	learn: 0.0198557	total: 2m 5s	remaining: 17m 29s
1149:	learn: 0.0155929	total: 2m 5s	remaining: 16m 3s
1153:	learn: 0.0177125	total: 2m 5s	remaining: 15m 59s
1123:	learn: 0.0174127	total: 2m 5s	remaining: 16m 28s
1166:	learn: 0.0162436	total: 2m 5s	remaining: 15m 48s
1066:	learn: 0.0198132	total: 2m 5s	remaining: 17m 29s
1150:	learn: 0.0155742	total: 2m 5s	remaining: 16m 2s
1154:	learn: 0.0176906	total: 2m 5s	remaining: 15m 59s
1124:	learn: 0.0173946	total: 2m 5s	remaining: 16m 28s
1167:	learn: 0.0162075	total: 2m 5s	remaining: 15m 48s
1151:	learn: 0.0155553	total: 2m 5s	remaining: 16m 2s
1155:	learn: 0.0176712	total: 2m 5s	remaining: 15m 58s
1067:	learn: 0.0197806	total: 2m 5s	remaining: 17m 29s
1168:	learn: 0.0161792	total: 2m 5s	remaining: 15m 48s
1125:	learn: 0.0173741	total: 2m 5s	remaining: 16m 28s
1156:	learn: 0.0176458	total: 2m 5s	remaining: 15m 58s
1152:	learn: 0.0155388	total: 2m 5s	remaining: 16m 2s
1068:	learn: 0.0197588	total: 2m 5s	remaining: 17m 28s
1169:	learn: 0.0161689	total: 2m 5s	remaining: 15m 47s
1126:	learn: 0.0173479	total: 2m 5s	remaining: 16m 28s
1157:	learn: 0.0176194	total: 2m 5s	remaining: 15m 58s
1170:	learn: 0.0161456	total: 2m 5s	remaining: 15m 47s
1127:	learn: 0.0173233	total: 2m 5s	remaining: 16m 28s
1153:	learn: 0.0155126	total: 2m 5s	remaining: 16m 2s
1069:	learn: 0.0197320	total: 2m 5s	remaining: 17m 28s
1158:	learn: 0.0175904	total: 2m 5s	remaining: 15m 58s
1171:	learn: 0.0161203	total: 2m 5s	remaining: 15m 47s
1154:	learn: 0.0154941	total: 2m 5s	remaining: 16m 2s
1128:	learn: 0.0173090	total: 2m 5s	remaining: 16m 27s
1159:	learn: 0.0175682	total: 2m 5s	remaining: 15m 57s
1070:	learn: 0.0197091	total: 2m 5s	remaining: 17m 28s
1172:	learn: 0.0161034	total: 2m 5s	remaining: 15m 47s
1129:	learn: 0.0172976	total: 2m 5s	remaining: 16m 27s
1155:	learn: 0.0154667	total: 2m 5s	remaining: 16m 2s
1160:	learn: 0.0175504	total: 2m 5s	remaining: 15m 57s
1173:	learn: 0.0160753	total: 2m 5s	remaining: 15m 46s
1071:	learn: 0.0196830	total: 2m 5s	remaining: 17m 28s
1156:	learn: 0.0154539	total: 2m 5s	remaining: 16m 2s
1161:	learn: 0.0175181	total: 2m 5s	remaining: 15m 57s
1130:	learn: 0.0172633	total: 2m 5s	remaining: 16m 27s
1072:	learn: 0.0196656	total: 2m 5s	remaining: 17m 28s
1174:	learn: 0.0160506	total: 2m 6s	remaining: 15m 46s
1157:	learn: 0.0154222	total: 2m 5s	remaining: 16m 1s
1162:	learn: 0.0174932	total: 2m 5s	remaining: 15m 57s
1073:	learn: 0.0196413	total: 2m 6s	remaining: 17m 27s
1175:	learn: 0.0160383	total: 2m 6s	remaining: 15m 46s
1131:	learn: 0.0172398	total: 2m 6s	remaining: 16m 27s
1158:	learn: 0.0154034	total: 2m 6s	remaining: 16m 1s
1163:	learn: 0.0174736	total: 2m 6s	remaining: 15m 57s
1176:	learn: 0.0160257	total: 2m 6s	remaining: 15m 46s
1074:	learn: 0.0196166	total: 2m 6s	remaining: 17m 27s
1132:	learn: 0.0172256	total: 2m 6s	remaining: 16m 27s
1164:	learn: 0.0174466	total: 2m 6s	remaining: 15m 56s
1159:	learn: 0.0153808	total: 2m 6s	remaining: 16m 1s
1177:	learn: 0.0160015	total: 2m 6s	remaining: 15m 46s
1133:	learn: 0.0171962	total: 2m 6s	remaining: 16m 27s
1075:	learn: 0.0195906	total: 2m 6s	remaining: 17m 27s
1160:	learn: 0.0153607	total: 2m 6s	remaining: 16m 1s
1165:	learn: 0.0174264	total: 2m 6s	remaining: 15m 56s
1134:	learn: 0.0171593	total: 2m 6s	remaining: 16m 26s
1178:	learn: 0.0159844	total: 2m 6s	remaining: 15m 46s
1076:	learn: 0.0195592	total: 2m 6s	remaining: 17m 27s
1161:	learn: 0.0153517	total: 2m 6s	remaining: 16m 1s
1166:	learn: 0.0174131	total: 2m 6s	remaining: 15m 56s
1135:	learn: 0.0171474	total: 2m 6s	remaining: 16m 26s
1179:	learn: 0.0159671	total: 2m 6s	remaining: 15m 45s
1162:	learn: 0.0153384	total: 2m 6s	remaining: 16m
1167:	learn: 0.0173955	total: 2m 6s	remaining: 15m 56s
1136:	learn: 0.0171220	total: 2m 6s	remaining: 16m 26s
1180:	learn: 0.0159405	total: 2m 6s	remaining: 15m 45s
1077:	learn: 0.0195352	total: 2m 6s	remaining: 17m 27s
1163:	learn: 0.0153186	total: 2m 6s	remaining: 16m
1181:	learn: 0.0159216	total: 2m 6s	remaining: 15m 45s
1168:	learn: 0.0173729	total: 2m 6s	remaining: 15m 56s
1137:	learn: 0.0170994	total: 2m 6s	remaining: 16m 26s
1164:	learn: 0.0152992	total: 2m 6s	remaining: 16m
1078:	learn: 0.0195079	total: 2m 6s	remaining: 17m 27s
1182:	learn: 0.0159066	total: 2m 6s	remaining: 15m 44s
1169:	learn: 0.0173454	total: 2m 6s	remaining: 15m 56s
1138:	learn: 0.0170870	total: 2m 6s	remaining: 16m 26s
1079:	learn: 0.0194784	total: 2m 6s	remaining: 17m 27s
1165:	learn: 0.0152732	total: 2m 6s	remaining: 16m
1183:	learn: 0.0158776	total: 2m 6s	remaining: 15m 44s
1170:	learn: 0.0173157	total: 2m 6s	remaining: 15m 56s
1139:	learn: 0.0170658	total: 2m 6s	remaining: 16m 25s
1184:	learn: 0.0158503	total: 2m 6s	remaining: 15m 44s
1080:	learn: 0.0194490	total: 2m 6s	remaining: 17m 27s
1166:	learn: 0.0152461	total: 2m 6s	remaining: 16m
1171:	learn: 0.0172905	total: 2m 6s	remaining: 15m 55s
1185:	learn: 0.0158363	total: 2m 7s	remaining: 15m 44s
1172:	learn: 0.0172638	total: 2m 6s	remaining: 15m 55s
1167:	learn: 0.0152263	total: 2m 6s	remaining: 15m 59s
1140:	learn: 0.0170541	total: 2m 7s	remaining: 16m 26s
1081:	learn: 0.0194097	total: 2m 7s	remaining: 17m 27s
1186:	learn: 0.0158216	total: 2m 7s	remaining: 15m 44s
1173:	learn: 0.0172487	total: 2m 7s	remaining: 15m 55s
1168:	learn: 0.0151993	total: 2m 7s	remaining: 15m 59s
1141:	learn: 0.0170299	total: 2m 7s	remaining: 16m 26s
1187:	learn: 0.0157953	total: 2m 7s	remaining: 15m 43s
1082:	learn: 0.0193753	total: 2m 7s	remaining: 17m 27s
1169:	learn: 0.0151767	total: 2m 7s	remaining: 15m 59s
1174:	learn: 0.0172357	total: 2m 7s	remaining: 15m 55s
1142:	learn: 0.0170032	total: 2m 7s	remaining: 16m 25s
1188:	learn: 0.0157618	total: 2m 7s	remaining: 15m 43s
1083:	learn: 0.0193507	total: 2m 7s	remaining: 17m 27s
1170:	learn: 0.0151687	total: 2m 7s	remaining: 15m 59s
1143:	learn: 0.0169860	total: 2m 7s	remaining: 16m 25s
1189:	learn: 0.0157222	total: 2m 7s	remaining: 15m 43s
1084:	learn: 0.0193305	total: 2m 7s	remaining: 17m 26s
1175:	learn: 0.0172199	total: 2m 7s	remaining: 15m 55s
1171:	learn: 0.0151477	total: 2m 7s	remaining: 15m 59s
1144:	learn: 0.0169523	total: 2m 7s	remaining: 16m 25s
1190:	learn: 0.0156963	total: 2m 7s	remaining: 15m 42s
1085:	learn: 0.0192967	total: 2m 7s	remaining: 17m 26s
1176:	learn: 0.0172028	total: 2m 7s	remaining: 15m 55s
1172:	learn: 0.0151319	total: 2m 7s	remaining: 15m 59s
1145:	learn: 0.0169242	total: 2m 7s	remaining: 16m 25s
1191:	learn: 0.0156772	total: 2m 7s	remaining: 15m 42s
1177:	learn: 0.0171858	total: 2m 7s	remaining: 15m 54s
1086:	learn: 0.0192709	total: 2m 7s	remaining: 17m 26s
1192:	learn: 0.0156624	total: 2m 7s	remaining: 15m 42s
1146:	learn: 0.0168931	total: 2m 7s	remaining: 16m 24s
1173:	learn: 0.0151102	total: 2m 7s	remaining: 15m 59s
1178:	learn: 0.0171680	total: 2m 7s	remaining: 15m 54s
1087:	learn: 0.0192488	total: 2m 7s	remaining: 17m 26s
1174:	learn: 0.0150917	total: 2m 7s	remaining: 15m 58s
1193:	learn: 0.0156397	total: 2m 7s	remaining: 15m 42s
1147:	learn: 0.0168668	total: 2m 7s	remaining: 16m 24s
1179:	learn: 0.0171505	total: 2m 7s	remaining: 15m 54s
1088:	learn: 0.0192149	total: 2m 7s	remaining: 17m 25s
1175:	learn: 0.0150745	total: 2m 7s	remaining: 15m 58s
1194:	learn: 0.0156161	total: 2m 7s	remaining: 15m 42s
1148:	learn: 0.0168451	total: 2m 7s	remaining: 16m 24s
1180:	learn: 0.0171214	total: 2m 7s	remaining: 15m 54s
1089:	learn: 0.0191915	total: 2m 7s	remaining: 17m 25s
1195:	learn: 0.0155908	total: 2m 7s	remaining: 15m 42s
1149:	learn: 0.0168276	total: 2m 7s	remaining: 16m 24s
1176:	learn: 0.0150617	total: 2m 7s	remaining: 15m 58s
1090:	learn: 0.0191751	total: 2m 7s	remaining: 17m 25s
1181:	learn: 0.0170998	total: 2m 7s	remaining: 15m 54s
1196:	learn: 0.0155591	total: 2m 8s	remaining: 15m 42s
1177:	learn: 0.0150455	total: 2m 7s	remaining: 15m 58s
1150:	learn: 0.0167987	total: 2m 8s	remaining: 16m 24s
1182:	learn: 0.0170850	total: 2m 7s	remaining: 15m 53s
1091:	learn: 0.0191532	total: 2m 8s	remaining: 17m 24s
1197:	learn: 0.0155362	total: 2m 8s	remaining: 15m 41s
1178:	learn: 0.0150376	total: 2m 8s	remaining: 15m 58s
1092:	learn: 0.0191287	total: 2m 8s	remaining: 17m 24s
1151:	learn: 0.0167651	total: 2m 8s	remaining: 16m 24s
1183:	learn: 0.0170723	total: 2m 8s	remaining: 15m 53s
1179:	learn: 0.0150198	total: 2m 8s	remaining: 15m 57s
1198:	learn: 0.0155066	total: 2m 8s	remaining: 15m 41s
1093:	learn: 0.0190993	total: 2m 8s	remaining: 17m 24s
1152:	learn: 0.0167475	total: 2m 8s	remaining: 16m 24s
1184:	learn: 0.0170410	total: 2m 8s	remaining: 15m 53s
1180:	learn: 0.0150023	total: 2m 8s	remaining: 15m 57s
1199:	learn: 0.0154830	total: 2m 8s	remaining: 15m 41s
1094:	learn: 0.0190589	total: 2m 8s	remaining: 17m 24s
1185:	learn: 0.0170163	total: 2m 8s	remaining: 15m 53s
1153:	learn: 0.0167391	total: 2m 8s	remaining: 16m 23s
1200:	learn: 0.0154666	total: 2m 8s	remaining: 15m 41s
1181:	learn: 0.0149962	total: 2m 8s	remaining: 15m 57s
1154:	learn: 0.0167121	total: 2m 8s	remaining: 16m 23s
1095:	learn: 0.0190144	total: 2m 8s	remaining: 17m 23s
1201:	learn: 0.0154508	total: 2m 8s	remaining: 15m 41s
1186:	learn: 0.0170029	total: 2m 8s	remaining: 15m 53s
1182:	learn: 0.0149736	total: 2m 8s	remaining: 15m 57s
1096:	learn: 0.0189957	total: 2m 8s	remaining: 17m 23s
1155:	learn: 0.0166995	total: 2m 8s	remaining: 16m 23s
1202:	learn: 0.0154427	total: 2m 8s	remaining: 15m 40s
1187:	learn: 0.0169864	total: 2m 8s	remaining: 15m 53s
1183:	learn: 0.0149562	total: 2m 8s	remaining: 15m 57s
1097:	learn: 0.0189774	total: 2m 8s	remaining: 17m 23s
1156:	learn: 0.0166769	total: 2m 8s	remaining: 16m 23s
1203:	learn: 0.0154211	total: 2m 8s	remaining: 15m 40s
1188:	learn: 0.0169623	total: 2m 8s	remaining: 15m 53s
1184:	learn: 0.0149407	total: 2m 8s	remaining: 15m 57s
1157:	learn: 0.0166567	total: 2m 8s	remaining: 16m 22s
1098:	learn: 0.0189446	total: 2m 8s	remaining: 17m 23s
1204:	learn: 0.0153868	total: 2m 8s	remaining: 15m 40s
1185:	learn: 0.0149334	total: 2m 8s	remaining: 15m 56s
1189:	learn: 0.0169446	total: 2m 8s	remaining: 15m 53s
1205:	learn: 0.0153774	total: 2m 8s	remaining: 15m 40s
1158:	learn: 0.0166403	total: 2m 8s	remaining: 16m 22s
1099:	learn: 0.0189227	total: 2m 8s	remaining: 17m 23s
1186:	learn: 0.0149195	total: 2m 8s	remaining: 15m 56s
1190:	learn: 0.0169265	total: 2m 8s	remaining: 15m 53s
1206:	learn: 0.0153569	total: 2m 9s	remaining: 15m 39s
1159:	learn: 0.0166278	total: 2m 8s	remaining: 16m 22s
1100:	learn: 0.0188908	total: 2m 8s	remaining: 17m 22s
1187:	learn: 0.0149101	total: 2m 8s	remaining: 15m 56s
1191:	learn: 0.0169061	total: 2m 8s	remaining: 15m 53s
1207:	learn: 0.0153344	total: 2m 9s	remaining: 15m 39s
1160:	learn: 0.0166158	total: 2m 9s	remaining: 16m 22s
1101:	learn: 0.0188686	total: 2m 9s	remaining: 17m 22s
1188:	learn: 0.0148979	total: 2m 9s	remaining: 15m 56s
1192:	learn: 0.0168900	total: 2m 9s	remaining: 15m 52s
1208:	learn: 0.0153256	total: 2m 9s	remaining: 15m 39s
1161:	learn: 0.0165934	total: 2m 9s	remaining: 16m 22s
1102:	learn: 0.0188433	total: 2m 9s	remaining: 17m 22s
1189:	learn: 0.0148790	total: 2m 9s	remaining: 15m 56s
1209:	learn: 0.0153011	total: 2m 9s	remaining: 15m 39s
1193:	learn: 0.0168655	total: 2m 9s	remaining: 15m 52s
1162:	learn: 0.0165782	total: 2m 9s	remaining: 16m 22s
1103:	learn: 0.0188226	total: 2m 9s	remaining: 17m 22s
1190:	learn: 0.0148604	total: 2m 9s	remaining: 15m 55s
1210:	learn: 0.0152859	total: 2m 9s	remaining: 15m 39s
1194:	learn: 0.0168490	total: 2m 9s	remaining: 15m 52s
1104:	learn: 0.0187915	total: 2m 9s	remaining: 17m 21s
1163:	learn: 0.0165552	total: 2m 9s	remaining: 16m 22s
1191:	learn: 0.0148443	total: 2m 9s	remaining: 15m 55s
1195:	learn: 0.0168273	total: 2m 9s	remaining: 15m 52s
1211:	learn: 0.0152648	total: 2m 9s	remaining: 15m 38s
1105:	learn: 0.0187491	total: 2m 9s	remaining: 17m 21s
1192:	learn: 0.0148213	total: 2m 9s	remaining: 15m 55s
1164:	learn: 0.0165308	total: 2m 9s	remaining: 16m 22s
1196:	learn: 0.0167965	total: 2m 9s	remaining: 15m 52s
1212:	learn: 0.0152466	total: 2m 9s	remaining: 15m 38s
1106:	learn: 0.0187142	total: 2m 9s	remaining: 17m 21s
1165:	learn: 0.0165104	total: 2m 9s	remaining: 16m 21s
1213:	learn: 0.0152127	total: 2m 9s	remaining: 15m 38s
1197:	learn: 0.0167861	total: 2m 9s	remaining: 15m 51s
1193:	learn: 0.0147942	total: 2m 9s	remaining: 15m 55s
1107:	learn: 0.0186765	total: 2m 9s	remaining: 17m 20s
1194:	learn: 0.0147765	total: 2m 9s	remaining: 15m 55s
1198:	learn: 0.0167652	total: 2m 9s	remaining: 15m 51s
1214:	learn: 0.0151822	total: 2m 9s	remaining: 15m 38s
1166:	learn: 0.0164873	total: 2m 9s	remaining: 16m 21s

1108:	learn: 0.0186488	total: 2m 9s	remaining: 17m 20s
1195:	learn: 0.0147466	total: 2m 9s	remaining: 15m 55s
1215:	learn: 0.0151676	total: 2m 9s	remaining: 15m 38s
1199:	learn: 0.0167301	total: 2m 9s	remaining: 15m 51s
1167:	learn: 0.0164624	total: 2m 9s	remaining: 16m 21s
1109:	learn: 0.0186084	total: 2m 9s	remaining: 17m 20s
1196:	learn: 0.0147347	total: 2m 9s	remaining: 15m 54s
1216:	learn: 0.0151483	total: 2m 9s	remaining: 15m 38s
1200:	learn: 0.0167089	total: 2m 9s	remaining: 15m 51s
1168:	learn: 0.0164365	total: 2m 9s	remaining: 16m 21s
1197:	learn: 0.0147183	total: 2m 9s	remaining: 15m 54s
1217:	learn: 0.0151317	total: 2m 10s	remaining: 15m 37s
1110:	learn: 0.0185919	total: 2m 10s	remaining: 17m 20s
1201:	learn: 0.0166850	total: 2m 9s	remaining: 15m 51s
1169:	learn: 0.0164236	total: 2m 10s	remaining: 16m 21s
1198:	learn: 0.0146915	total: 2m 10s	remaining: 15m 54s
1218:	learn: 0.0151060	total: 2m 10s	remaining: 15m 37s
1202:	learn: 0.0166689	total: 2m 10s	remaining: 15m 51s
1170:	learn: 0.0164115	total: 2m 10s	remaining: 16m 21s
1111:	learn: 0.0185739	total: 2m 10s	remaining: 17m 20s
1199:	learn: 0.0146649	total: 2m 10s	remaining: 15m 54s
1219:	learn: 0.0150956	total: 2m 10s	remaining: 15m 37s
1203:	learn: 0.0166545	total: 2m 10s	remaining: 15m 51s
1171:	learn: 0.0163955	total: 2m 10s	remaining: 16m 20s
1112:	learn: 0.0185493	total: 2m 10s	remaining: 17m 20s
1200:	learn: 0.0146326	total: 2m 10s	remaining: 15m 54s
1220:	learn: 0.0150675	total: 2m 10s	remaining: 15m 37s
1113:	learn: 0.0185151	total: 2m 10s	remaining: 17m 19s
1204:	learn: 0.0166313	total: 2m 10s	remaining: 15m 50s
1172:	learn: 0.0163772	total: 2m 10s	remaining: 16m 20s
1201:	learn: 0.0146054	total: 2m 10s	remaining: 15m 53s
1221:	learn: 0.0150476	total: 2m 10s	remaining: 15m 37s
1205:	learn: 0.0166164	total: 2m 10s	remaining: 15m 50s
1114:	learn: 0.0184779	total: 2m 10s	remaining: 17m 19s
1173:	learn: 0.0163495	total: 2m 10s	remaining: 16m 20s
1202:	learn: 0.0145786	total: 2m 10s	remaining: 15m 53s
1222:	learn: 0.0150320	total: 2m 10s	remaining: 15m 37s
1206:	learn: 0.0165871	total: 2m 10s	remaining: 15m 50s
1115:	learn: 0.0184562	total: 2m 10s	remaining: 17m 19s
1174:	learn: 0.0163293	total: 2m 10s	remaining: 16m 20s
1223:	learn: 0.0150075	total: 2m 10s	remaining: 15m 36s
1203:	learn: 0.0145531	total: 2m 10s	remaining: 15m 53s
1116:	learn: 0.0184162	total: 2m 10s	remaining: 17m 19s
1207:	learn: 0.0165704	total: 2m 10s	remaining: 15m 50s
1175:	learn: 0.0163010	total: 2m 10s	remaining: 16m 20s
1224:	learn: 0.0149908	total: 2m 10s	remaining: 15m 36s
1117:	learn: 0.0183769	total: 2m 10s	remaining: 17m 18s
1204:	learn: 0.0145413	total: 2m 10s	remaining: 15m 53s
1208:	learn: 0.0165586	total: 2m 10s	remaining: 15m 50s
1176:	learn: 0.0162875	total: 2m 10s	remaining: 16m 19s
1225:	learn: 0.0149793	total: 2m 10s	remaining: 15m 36s
1118:	learn: 0.0183445	total: 2m 10s	remaining: 17m 18s
1205:	learn: 0.0145243	total: 2m 10s	remaining: 15m 53s
1209:	learn: 0.0165457	total: 2m 10s	remaining: 15m 50s
1177:	learn: 0.0162646	total: 2m 10s	remaining: 16m 19s
1226:	learn: 0.0149580	total: 2m 10s	remaining: 15m 36s
1206:	learn: 0.0144963	total: 2m 10s	remaining: 15m 53s
1119:	learn: 0.0183182	total: 2m 10s	remaining: 17m 18s
1210:	learn: 0.0165224	total: 2m 10s	remaining: 15m 49s
1178:	learn: 0.0162499	total: 2m 10s	remaining: 16m 19s
1207:	learn: 0.0144774	total: 2m 10s	remaining: 15m 52s
1227:	learn: 0.0149384	total: 2m 11s	remaining: 15m 36s
1120:	learn: 0.0182891	total: 2m 11s	remaining: 17m 18s
1211:	learn: 0.0164992	total: 2m 11s	remaining: 15m 49s
1208:	learn: 0.0144602	total: 2m 10s	remaining: 15m 52s
1179:	learn: 0.0162374	total: 2m 11s	remaining: 16m 19s
1228:	learn: 0.0149231	total: 2m 11s	remaining: 15m 36s
1209:	learn: 0.0144398	total: 2m 11s	remaining: 15m 52s
1121:	learn: 0.0182734	total: 2m 11s	remaining: 17m 17s
1212:	learn: 0.0164830	total: 2m 11s	remaining: 15m 49s
1180:	learn: 0.0162244	total: 2m 11s	remaining: 16m 19s
1229:	learn: 0.0149068	total: 2m 11s	remaining: 15m 36s
1122:	learn: 0.0182512	total: 2m 11s	remaining: 17m 17s
1210:	learn: 0.0144219	total: 2m 11s	remaining: 15m 52s
1213:	learn: 0.0164529	total: 2m 11s	remaining: 15m 49s
1181:	learn: 0.0161975	total: 2m 11s	remaining: 16m 19s
1230:	learn: 0.0148750	total: 2m 11s	remaining: 15m 35s
1123:	learn: 0.0182284	total: 2m 11s	remaining: 17m 17s
1182:	learn: 0.0161809	total: 2m 11s	remaining: 16m 18s
1211:	learn: 0.0143969	total: 2m 11s	remaining: 15m 52s
1214:	learn: 0.0164391	total: 2m 11s	remaining: 15m 49s
1231:	learn: 0.0148501	total: 2m 11s	remaining: 15m 35s
1124:	learn: 0.0182016	total: 2m 11s	remaining: 17m 17s
1183:	learn: 0.0161537	total: 2m 11s	remaining: 16m 18s
1212:	learn: 0.0143871	total: 2m 11s	remaining: 15m 51s
1232:	learn: 0.0148318	total: 2m 11s	remaining: 15m 35s
1215:	learn: 0.0164246	total: 2m 11s	remaining: 15m 49s
1184:	learn: 0.0161336	total: 2m 11s	remaining: 16m 18s
1125:	learn: 0.0181760	total: 2m 11s	remaining: 17m 16s
1233:	learn: 0.0148103	total: 2m 11s	remaining: 15m 35s
1213:	learn: 0.0143609	total: 2m 11s	remaining: 15m 51s
1216:	learn: 0.0164068	total: 2m 11s	remaining: 15m 49s
1126:	learn: 0.0181571	total: 2m 11s	remaining: 17m 16s
1185:	learn: 0.0161110	total: 2m 11s	remaining: 16m 18s
1234:	learn: 0.0147890	total: 2m 11s	remaining: 15m 34s
1214:	learn: 0.0143464	total: 2m 11s	remaining: 15m 51s
1217:	learn: 0.0163937	total: 2m 11s	remaining: 15m 49s
1186:	learn: 0.0160933	total: 2m 11s	remaining: 16m 18s
1235:	learn: 0.0147786	total: 2m 11s	remaining: 15m 34s
1127:	learn: 0.0181354	total: 2m 11s	remaining: 17m 16s
1215:	learn: 0.0143272	total: 2m 11s	remaining: 15m 51s
1128:	learn: 0.0181045	total: 2m 11s	remaining: 17m 16s
1218:	learn: 0.0163814	total: 2m 11s	remaining: 15m 49s
1236:	learn: 0.0147517	total: 2m 11s	remaining: 15m 34s
1187:	learn: 0.0160782	total: 2m 11s	remaining: 16m 17s
1216:	learn: 0.0143071	total: 2m 11s	remaining: 15m 51s
1219:	learn: 0.0163666	total: 2m 11s	remaining: 15m 48s
1237:	learn: 0.0147231	total: 2m 12s	remaining: 15m 34s
1129:	learn: 0.0180632	total: 2m 11s	remaining: 17m 15s
1188:	learn: 0.0160514	total: 2m 11s	remaining: 16m 17s
1217:	learn: 0.0142909	total: 2m 11s	remaining: 15m 51s
1238:	learn: 0.0147085	total: 2m 12s	remaining: 15m 33s
1220:	learn: 0.0163559	total: 2m 11s	remaining: 15m 48s
1130:	learn: 0.0180481	total: 2m 12s	remaining: 17m 15s
1189:	learn: 0.0160256	total: 2m 12s	remaining: 16m 17s
1239:	learn: 0.0146910	total: 2m 12s	remaining: 15m 33s
1218:	learn: 0.0142689	total: 2m 12s	remaining: 15m 51s
1131:	learn: 0.0180323	total: 2m 12s	remaining: 17m 15s
1221:	learn: 0.0163407	total: 2m 12s	remaining: 15m 48s
1190:	learn: 0.0160100	total: 2m 12s	remaining: 16m 17s
1240:	learn: 0.0146714	total: 2m 12s	remaining: 15m 33s
1219:	learn: 0.0142516	total: 2m 12s	remaining: 15m 51s
1222:	learn: 0.0163225	total: 2m 12s	remaining: 15m 48s
1132:	learn: 0.0180018	total: 2m 12s	remaining: 17m 14s
1191:	learn: 0.0159941	total: 2m 12s	remaining: 16m 17s
1241:	learn: 0.0146559	total: 2m 12s	remaining: 15m 33s
1220:	learn: 0.0142349	total: 2m 12s	remaining: 15m 50s
1133:	learn: 0.0179790	total: 2m 12s	remaining: 17m 14s
1223:	learn: 0.0163059	total: 2m 12s	remaining: 15m 48s
1192:	learn: 0.0159819	total: 2m 12s	remaining: 16m 17s
1242:	learn: 0.0146433	total: 2m 12s	remaining: 15m 33s
1221:	learn: 0.0142138	total: 2m 12s	remaining: 15m 50s
1134:	learn: 0.0179536	total: 2m 12s	remaining: 17m 14s
1224:	learn: 0.0162885	total: 2m 12s	remaining: 15m 48s
1193:	learn: 0.0159500	total: 2m 12s	remaining: 16m 16s
1243:	learn: 0.0146248	total: 2m 12s	remaining: 15m 33s
1222:	learn: 0.0141922	total: 2m 12s	remaining: 15m 50s
1135:	learn: 0.0179243	total: 2m 12s	remaining: 17m 14s
1194:	learn: 0.0159294	total: 2m 12s	remaining: 16m 16s
1225:	learn: 0.0162686	total: 2m 12s	remaining: 15m 48s
1244:	learn: 0.0146143	total: 2m 12s	remaining: 15m 32s
1136:	learn: 0.0179031	total: 2m 12s	remaining: 17m 13s
1195:	learn: 0.0159046	total: 2m 12s	remaining: 16m 16s
1223:	learn: 0.0141855	total: 2m 12s	remaining: 15m 50s
1226:	learn: 0.0162507	total: 2m 12s	remaining: 15m 48s
1245:	learn: 0.0145985	total: 2m 12s	remaining: 15m 32s
1137:	learn: 0.0178873	total: 2m 12s	remaining: 17m 13s
1224:	learn: 0.0141741	total: 2m 12s	remaining: 15m 50s
1196:	learn: 0.0158882	total: 2m 12s	remaining: 16m 16s
1246:	learn: 0.0145702	total: 2m 12s	remaining: 15m 32s
1227:	learn: 0.0162279	total: 2m 12s	remaining: 15m 48s
1138:	learn: 0.0178670	total: 2m 12s	remaining: 17m 13s
1225:	learn: 0.0141594	total: 2m 12s	remaining: 15m 50s
1197:	learn: 0.0158736	total: 2m 12s	remaining: 16m 15s
1247:	learn: 0.0145466	total: 2m 12s	remaining: 15m 32s
1228:	learn: 0.0162029	total: 2m 12s	remaining: 15m 48s
1226:	learn: 0.0141368	total: 2m 12s	remaining: 15m 49s
1139:	learn: 0.0178399	total: 2m 12s	remaining: 17m 13s
1248:	learn: 0.0145260	total: 2m 13s	remaining: 15m 31s
1198:	learn: 0.0158395	total: 2m 12s	remaining: 16m 16s
1227:	learn: 0.0141171	total: 2m 12s	remaining: 15m 49s
1229:	learn: 0.0161874	total: 2m 12s	remaining: 15m 47s
1140:	learn: 0.0178090	total: 2m 13s	remaining: 17m 12s
1249:	learn: 0.0145161	total: 2m 13s	remaining: 15m 31s
1199:	learn: 0.0158255	total: 2m 13s	remaining: 16m 15s
1228:	learn: 0.0141014	total: 2m 13s	remaining: 15m 49s
1230:	learn: 0.0161697	total: 2m 13s	remaining: 15m 47s
1250:	learn: 0.0144836	total: 2m 13s	remaining: 15m 31s
1141:	learn: 0.0177925	total: 2m 13s	remaining: 17m 13s
1200:	learn: 0.0157934	total: 2m 13s	remaining: 16m 15s
1229:	learn: 0.0140932	total: 2m 13s	remaining: 15m 49s
1231:	learn: 0.0161524	total: 2m 13s	remaining: 15m 47s
1251:	learn: 0.0144682	total: 2m 13s	remaining: 15m 31s
1201:	learn: 0.0157811	total: 2m 13s	remaining: 16m 15s
1142:	learn: 0.0177786	total: 2m 13s	remaining: 17m 12s
1230:	learn: 0.0140773	total: 2m 13s	remaining: 15m 49s
1232:	learn: 0.0161310	total: 2m 13s	remaining: 15m 47s
1252:	learn: 0.0144599	total: 2m 13s	remaining: 15m 31s
1202:	learn: 0.0157668	total: 2m 13s	remaining: 16m 15s
1143:	learn: 0.0177631	total: 2m 13s	remaining: 17m 12s
1231:	learn: 0.0140674	total: 2m 13s	remaining: 15m 48s
1233:	learn: 0.0161105	total: 2m 13s	remaining: 15m 47s
1253:	learn: 0.0144477	total: 2m 13s	remaining: 15m 31s
1203:	learn: 0.0157559	total: 2m 13s	remaining: 16m 14s
1144:	learn: 0.0177413	total: 2m 13s	remaining: 17m 12s
1232:	learn: 0.0140521	total: 2m 13s	remaining: 15m 48s
1254:	learn: 0.0144257	total: 2m 13s	remaining: 15m 30s
1234:	learn: 0.0160845	total: 2m 13s	remaining: 15m 47s
1204:	learn: 0.0157344	total: 2m 13s	remaining: 16m 14s
1233:	learn: 0.0140298	total: 2m 13s	remaining: 15m 48s
1235:	learn: 0.0160680	total: 2m 13s	remaining: 15m 47s
1145:	learn: 0.0177209	total: 2m 13s	remaining: 17m 12s
1205:	learn: 0.0157124	total: 2m 13s	remaining: 16m 14s
1255:	learn: 0.0144004	total: 2m 13s	remaining: 15m 30s
1236:	learn: 0.0160519	total: 2m 13s	remaining: 15m 46s
1234:	learn: 0.0140141	total: 2m 13s	remaining: 15m 48s
1146:	learn: 0.0176956	total: 2m 13s	remaining: 17m 12s
1206:	learn: 0.0156858	total: 2m 13s	remaining: 16m 14s
1237:	learn: 0.0160374	total: 2m 13s	remaining: 15m 46s
1256:	learn: 0.0143849	total: 2m 13s	remaining: 15m 30s
1235:	learn: 0.0139922	total: 2m 13s	remaining: 15m 48s
1147:	learn: 0.0176708	total: 2m 13s	remaining: 17m 12s
1207:	learn: 0.0156611	total: 2m 13s	remaining: 16m 14s
1257:	learn: 0.0143709	total: 2m 13s	remaining: 15m 30s
1238:	learn: 0.0160198	total: 2m 13s	remaining: 15m 46s
1236:	learn: 0.0139688	total: 2m 13s	remaining: 15m 48s
1208:	learn: 0.0156512	total: 2m 13s	remaining: 16m 13s
1239:	learn: 0.0160040	total: 2m 13s	remaining: 15m 45s
1148:	learn: 0.0176327	total: 2m 13s	remaining: 17m 12s
1258:	learn: 0.0143539	total: 2m 14s	remaining: 15m 30s
1237:	learn: 0.0139532	total: 2m 13s	remaining: 15m 48s
1240:	learn: 0.0159839	total: 2m 13s	remaining: 15m 45s
1209:	learn: 0.0156340	total: 2m 14s	remaining: 16m 13s
1149:	learn: 0.0176128	total: 2m 14s	remaining: 17m 11s
1238:	learn: 0.0139300	total: 2m 14s	remaining: 15m 47s
1259:	learn: 0.0143389	total: 2m 14s	remaining: 15m 30s
1150:	learn: 0.0175840	total: 2m 14s	remaining: 17m 11s
1241:	learn: 0.0159700	total: 2m 14s	remaining: 15m 45s
1239:	learn: 0.0139070	total: 2m 14s	remaining: 15m 47s
1260:	learn: 0.0143279	total: 2m 14s	remaining: 15m 30s
1210:	learn: 0.0156054	total: 2m 14s	remaining: 16m 13s
1242:	learn: 0.0159533	total: 2m 14s	remaining: 15m 45s
1151:	learn: 0.0175610	total: 2m 14s	remaining: 17m 11s
1261:	learn: 0.0143140	total: 2m 14s	remaining: 15m 30s
1240:	learn: 0.0138860	total: 2m 14s	remaining: 15m 47s
1211:	learn: 0.0155850	total: 2m 14s	remaining: 16m 13s
1243:	learn: 0.0159336	total: 2m 14s	remaining: 15m 45s
1152:	learn: 0.0175246	total: 2m 14s	remaining: 17m 11s
1241:	learn: 0.0138700	total: 2m 14s	remaining: 15m 47s
1262:	learn: 0.0142867	total: 2m 14s	remaining: 15m 30s
1244:	learn: 0.0159157	total: 2m 14s	remaining: 15m 44s
1212:	learn: 0.0155716	total: 2m 14s	remaining: 16m 13s
1263:	learn: 0.0142703	total: 2m 14s	remaining: 15m 29s
1153:	learn: 0.0174996	total: 2m 14s	remaining: 17m 11s
1245:	learn: 0.0158968	total: 2m 14s	remaining: 15m 44s
1242:	learn: 0.0138489	total: 2m 14s	remaining: 15m 47s
1264:	learn: 0.0142505	total: 2m 14s	remaining: 15m 29s
1213:	learn: 0.0155455	total: 2m 14s	remaining: 16m 13s
1246:	learn: 0.0158804	total: 2m 14s	remaining: 15m 44s
1243:	learn: 0.0138384	total: 2m 14s	remaining: 15m 46s
1154:	learn: 0.0174706	total: 2m 14s	remaining: 17m 11s
1265:	learn: 0.0142212	total: 2m 14s	remaining: 15m 29s
1214:	learn: 0.0155382	total: 2m 14s	remaining: 16m 13s
1247:	learn: 0.0158622	total: 2m 14s	remaining: 15m 43s
1244:	learn: 0.0138176	total: 2m 14s	remaining: 15m 46s
1155:	learn: 0.0174503	total: 2m 14s	remaining: 17m 10s
1266:	learn: 0.0142085	total: 2m 14s	remaining: 15m 29s
1248:	learn: 0.0158391	total: 2m 14s	remaining: 15m 43s
1215:	learn: 0.0155246	total: 2m 14s	remaining: 16m 13s
1245:	learn: 0.0138018	total: 2m 14s	remaining: 15m 46s
1156:	learn: 0.0174263	total: 2m 14s	remaining: 17m 10s
1267:	learn: 0.0141961	total: 2m 14s	remaining: 15m 28s
1249:	learn: 0.0158226	total: 2m 14s	remaining: 15m 43s
1216:	learn: 0.0155026	total: 2m 14s	remaining: 16m 13s
1246:	learn: 0.0137818	total: 2m 14s	remaining: 15m 46s
1157:	learn: 0.0173994	total: 2m 14s	remaining: 17m 10s
1268:	learn: 0.0141685	total: 2m 15s	remaining: 15m 28s
1250:	learn: 0.0158012	total: 2m 14s	remaining: 15m 43s
1217:	learn: 0.0154828	total: 2m 14s	remaining: 16m 13s
1247:	learn: 0.0137686	total: 2m 14s	remaining: 15m 46s
1158:	learn: 0.0173683	total: 2m 15s	remaining: 17m 9s
1269:	learn: 0.0141475	total: 2m 15s	remaining: 15m 28s
1251:	learn: 0.0157734	total: 2m 15s	remaining: 15m 43s
1159:	learn: 0.0173468	total: 2m 15s	remaining: 17m 9s
1218:	learn: 0.0154662	total: 2m 15s	remaining: 16m 13s
1270:	learn: 0.0141176	total: 2m 15s	remaining: 15m 28s
1248:	learn: 0.0137434	total: 2m 15s	remaining: 15m 46s
1271:	learn: 0.0141038	total: 2m 15s	remaining: 15m 28s
1252:	learn: 0.0157572	total: 2m 15s	remaining: 15m 43s
1160:	learn: 0.0173251	total: 2m 15s	remaining: 17m 9s
1249:	learn: 0.0137240	total: 2m 15s	remaining: 15m 46s
1219:	learn: 0.0154430	total: 2m 15s	remaining: 16m 13s
1272:	learn: 0.0140892	total: 2m 15s	remaining: 15m 27s
1253:	learn: 0.0157367	total: 2m 15s	remaining: 15m 43s
1161:	learn: 0.0172986	total: 2m 15s	remaining: 17m 9s
1250:	learn: 0.0137019	total: 2m 15s	remaining: 15m 46s
1273:	learn: 0.0140666	total: 2m 15s	remaining: 15m 27s
1220:	learn: 0.0154190	total: 2m 15s	remaining: 16m 13s
1254:	learn: 0.0157193	total: 2m 15s	remaining: 15m 42s
1162:	learn: 0.0172740	total: 2m 15s	remaining: 17m 9s
1221:	learn: 0.0154100	total: 2m 15s	remaining: 16m 12s
1251:	learn: 0.0136922	total: 2m 15s	remaining: 15m 45s
1274:	learn: 0.0140537	total: 2m 15s	remaining: 15m 27s
1255:	learn: 0.0156910	total: 2m 15s	remaining: 15m 43s
1252:	learn: 0.0136800	total: 2m 15s	remaining: 15m 45s
1163:	learn: 0.0172491	total: 2m 15s	remaining: 17m 8s
1275:	learn: 0.0140349	total: 2m 15s	remaining: 15m 27s
1253:	learn: 0.0136680	total: 2m 15s	remaining: 15m 45s
1222:	learn: 0.0153832	total: 2m 15s	remaining: 16m 12s
1256:	learn: 0.0156646	total: 2m 15s	remaining: 15m 42s
1164:	learn: 0.0172309	total: 2m 15s	remaining: 17m 8s
1254:	learn: 0.0136508	total: 2m 15s	remaining: 15m 44s

1276:	learn: 0.0140172	total: 2m 15s	remaining: 15m 27s
1223:	learn: 0.0153528	total: 2m 15s	remaining: 16m 12s
1257:	learn: 0.0156363	total: 2m 15s	remaining: 15m 42s
1165:	learn: 0.0172104	total: 2m 15s	remaining: 17m 8s
1255:	learn: 0.0136263	total: 2m 15s	remaining: 15m 44s
1224:	learn: 0.0153445	total: 2m 15s	remaining: 16m 12s
1277:	learn: 0.0139977	total: 2m 15s	remaining: 15m 27s
1256:	learn: 0.0136046	total: 2m 15s	remaining: 15m 44s
1258:	learn: 0.0156240	total: 2m 15s	remaining: 15m 42s
1166:	learn: 0.0171945	total: 2m 15s	remaining: 17m 8s
1225:	learn: 0.0153243	total: 2m 15s	remaining: 16m 12s
1278:	learn: 0.0139821	total: 2m 15s	remaining: 15m 27s
1257:	learn: 0.0135828	total: 2m 15s	remaining: 15m 44s
1259:	learn: 0.0156029	total: 2m 15s	remaining: 15m 42s
1167:	learn: 0.0171723	total: 2m 15s	remaining: 17m 8s
1226:	learn: 0.0153026	total: 2m 15s	remaining: 16m 12s
1258:	learn: 0.0135574	total: 2m 15s	remaining: 15m 43s
1279:	learn: 0.0139636	total: 2m 16s	remaining: 15m 27s
1260:	learn: 0.0155899	total: 2m 15s	remaining: 15m 42s
1168:	learn: 0.0171419	total: 2m 16s	remaining: 17m 7s
1259:	learn: 0.0135361	total: 2m 16s	remaining: 15m 43s
1227:	learn: 0.0152916	total: 2m 16s	remaining: 16m 11s
1280:	learn: 0.0139425	total: 2m 16s	remaining: 15m 27s
1261:	learn: 0.0155733	total: 2m 16s	remaining: 15m 42s
1260:	learn: 0.0135197	total: 2m 16s	remaining: 15m 43s
1169:	learn: 0.0171221	total: 2m 16s	remaining: 17m 7s
1228:	learn: 0.0152693	total: 2m 16s	remaining: 16m 11s
1262:	learn: 0.0155567	total: 2m 16s	remaining: 15m 41s
1281:	learn: 0.0139150	total: 2m 16s	remaining: 15m 26s
1263:	learn: 0.0155340	total: 2m 16s	remaining: 15m 41s
1261:	learn: 0.0135071	total: 2m 16s	remaining: 15m 43s
1170:	learn: 0.0170974	total: 2m 16s	remaining: 17m 7s
1229:	learn: 0.0152468	total: 2m 16s	remaining: 16m 11s
1282:	learn: 0.0138953	total: 2m 16s	remaining: 15m 26s
1264:	learn: 0.0155141	total: 2m 16s	remaining: 15m 41s
1262:	learn: 0.0134914	total: 2m 16s	remaining: 15m 43s
1171:	learn: 0.0170709	total: 2m 16s	remaining: 17m 7s
1230:	learn: 0.0152355	total: 2m 16s	remaining: 16m 11s
1283:	learn: 0.0138820	total: 2m 16s	remaining: 15m 26s
1265:	learn: 0.0154920	total: 2m 16s	remaining: 15m 40s
1263:	learn: 0.0134769	total: 2m 16s	remaining: 15m 42s
1172:	learn: 0.0170481	total: 2m 16s	remaining: 17m 7s
1231:	learn: 0.0152251	total: 2m 16s	remaining: 16m 11s
1266:	learn: 0.0154732	total: 2m 16s	remaining: 15m 40s
1284:	learn: 0.0138677	total: 2m 16s	remaining: 15m 26s
1173:	learn: 0.0170260	total: 2m 16s	remaining: 17m 6s
1264:	learn: 0.0134595	total: 2m 16s	remaining: 15m 42s
1232:	learn: 0.0152012	total: 2m 16s	remaining: 16m 11s
1267:	learn: 0.0154590	total: 2m 16s	remaining: 15m 40s
1174:	learn: 0.0170047	total: 2m 16s	remaining: 17m 6s
1285:	learn: 0.0138476	total: 2m 16s	remaining: 15m 26s
1265:	learn: 0.0134428	total: 2m 16s	remaining: 15m 42s
1233:	learn: 0.0151784	total: 2m 16s	remaining: 16m 11s
1175:	learn: 0.0169780	total: 2m 16s	remaining: 17m 6s
1268:	learn: 0.0154337	total: 2m 16s	remaining: 15m 40s
1286:	learn: 0.0138266	total: 2m 16s	remaining: 15m 26s
1266:	learn: 0.0134255	total: 2m 16s	remaining: 15m 42s
1234:	learn: 0.0151679	total: 2m 16s	remaining: 16m 10s
1269:	learn: 0.0154075	total: 2m 16s	remaining: 15m 40s
1176:	learn: 0.0169571	total: 2m 16s	remaining: 17m 6s
1235:	learn: 0.0151590	total: 2m 16s	remaining: 16m 10s
1267:	learn: 0.0134109	total: 2m 16s	remaining: 15m 42s
1270:	learn: 0.0153867	total: 2m 16s	remaining: 15m 39s
1287:	learn: 0.0138055	total: 2m 16s	remaining: 15m 26s
1268:	learn: 0.0133869	total: 2m 16s	remaining: 15m 42s
1177:	learn: 0.0169386	total: 2m 17s	remaining: 17m 6s
1271:	learn: 0.0153686	total: 2m 16s	remaining: 15m 39s
1236:	learn: 0.0151406	total: 2m 17s	remaining: 16m 10s
1288:	learn: 0.0137921	total: 2m 17s	remaining: 15m 26s
1269:	learn: 0.0133721	total: 2m 17s	remaining: 15m 41s
1178:	learn: 0.0169041	total: 2m 17s	remaining: 17m 5s
1272:	learn: 0.0153425	total: 2m 17s	remaining: 15m 39s
1237:	learn: 0.0151232	total: 2m 17s	remaining: 16m 10s
1270:	learn: 0.0133513	total: 2m 17s	remaining: 15m 41s
1273:	learn: 0.0153221	total: 2m 17s	remaining: 15m 39s
1289:	learn: 0.0137744	total: 2m 17s	remaining: 15m 26s
1179:	learn: 0.0168837	total: 2m 17s	remaining: 17m 5s
1238:	learn: 0.0151131	total: 2m 17s	remaining: 16m 10s
1271:	learn: 0.0133348	total: 2m 17s	remaining: 15m 41s
1274:	learn: 0.0153074	total: 2m 17s	remaining: 15m 38s
1290:	learn: 0.0137538	total: 2m 17s	remaining: 15m 26s
1239:	learn: 0.0150909	total: 2m 17s	remaining: 16m 10s
1180:	learn: 0.0168659	total: 2m 17s	remaining: 17m 5s
1272:	learn: 0.0133237	total: 2m 17s	remaining: 15m 41s
1275:	learn: 0.0152883	total: 2m 17s	remaining: 15m 38s
1291:	learn: 0.0137288	total: 2m 17s	remaining: 15m 26s
1181:	learn: 0.0168272	total: 2m 17s	remaining: 17m 5s
1240:	learn: 0.0150730	total: 2m 17s	remaining: 16m 10s
1273:	learn: 0.0133102	total: 2m 17s	remaining: 15m 41s
1292:	learn: 0.0137156	total: 2m 17s	remaining: 15m 26s
1276:	learn: 0.0152741	total: 2m 17s	remaining: 15m 38s
1182:	learn: 0.0168100	total: 2m 17s	remaining: 17m 5s
1241:	learn: 0.0150537	total: 2m 17s	remaining: 16m 9s
1293:	learn: 0.0137059	total: 2m 17s	remaining: 15m 26s
1274:	learn: 0.0132872	total: 2m 17s	remaining: 15m 41s
1277:	learn: 0.0152540	total: 2m 17s	remaining: 15m 38s
1183:	learn: 0.0167951	total: 2m 17s	remaining: 17m 4s
1242:	learn: 0.0150395	total: 2m 17s	remaining: 16m 9s
1294:	learn: 0.0136907	total: 2m 17s	remaining: 15m 25s
1275:	learn: 0.0132658	total: 2m 17s	remaining: 15m 40s
1278:	learn: 0.0152362	total: 2m 17s	remaining: 15m 38s
1184:	learn: 0.0167701	total: 2m 17s	remaining: 17m 4s
1243:	learn: 0.0150263	total: 2m 17s	remaining: 16m 9s
1276:	learn: 0.0132427	total: 2m 17s	remaining: 15m 40s
1295:	learn: 0.0136719	total: 2m 17s	remaining: 15m 25s
1279:	learn: 0.0152154	total: 2m 17s	remaining: 15m 38s
1185:	learn: 0.0167600	total: 2m 17s	remaining: 17m 4s
1244:	learn: 0.0150126	total: 2m 17s	remaining: 16m 9s
1296:	learn: 0.0136604	total: 2m 17s	remaining: 15m 25s
1277:	learn: 0.0132260	total: 2m 17s	remaining: 15m 40s
1280:	learn: 0.0152022	total: 2m 17s	remaining: 15m 38s
1186:	learn: 0.0167396	total: 2m 17s	remaining: 17m 4s
1297:	learn: 0.0136459	total: 2m 18s	remaining: 15m 25s
1278:	learn: 0.0132034	total: 2m 17s	remaining: 15m 40s
1245:	learn: 0.0149953	total: 2m 17s	remaining: 16m 9s
1281:	learn: 0.0151884	total: 2m 17s	remaining: 15m 37s
1187:	learn: 0.0167199	total: 2m 18s	remaining: 17m 4s
1298:	learn: 0.0136262	total: 2m 18s	remaining: 15m 25s
1246:	learn: 0.0149796	total: 2m 18s	remaining: 16m 8s
1279:	learn: 0.0131857	total: 2m 18s	remaining: 15m 40s
1188:	learn: 0.0166887	total: 2m 18s	remaining: 17m 3s
1282:	learn: 0.0151724	total: 2m 18s	remaining: 15m 38s
1247:	learn: 0.0149695	total: 2m 18s	remaining: 16m 8s
1299:	learn: 0.0136125	total: 2m 18s	remaining: 15m 25s
1280:	learn: 0.0131690	total: 2m 18s	remaining: 15m 40s
1283:	learn: 0.0151559	total: 2m 18s	remaining: 15m 37s
1189:	learn: 0.0166508	total: 2m 18s	remaining: 17m 3s
1300:	learn: 0.0136013	total: 2m 18s	remaining: 15m 24s
1248:	learn: 0.0149484	total: 2m 18s	remaining: 16m 8s
1281:	learn: 0.0131555	total: 2m 18s	remaining: 15m 39s
1190:	learn: 0.0166359	total: 2m 18s	remaining: 17m 3s
1301:	learn: 0.0135902	total: 2m 18s	remaining: 15m 24s
1284:	learn: 0.0151316	total: 2m 18s	remaining: 15m 37s
1249:	learn: 0.0149385	total: 2m 18s	remaining: 16m 8s
1302:	learn: 0.0135715	total: 2m 18s	remaining: 15m 24s
1282:	learn: 0.0131437	total: 2m 18s	remaining: 15m 39s
1191:	learn: 0.0166035	total: 2m 18s	remaining: 17m 3s
1285:	learn: 0.0151115	total: 2m 18s	remaining: 15m 37s
1250:	learn: 0.0149301	total: 2m 18s	remaining: 16m 8s
1303:	learn: 0.0135433	total: 2m 18s	remaining: 15m 23s
1283:	learn: 0.0131282	total: 2m 18s	remaining: 15m 39s
1192:	learn: 0.0165820	total: 2m 18s	remaining: 17m 2s
1286:	learn: 0.0150986	total: 2m 18s	remaining: 15m 37s
1304:	learn: 0.0135255	total: 2m 18s	remaining: 15m 23s
1251:	learn: 0.0149020	total: 2m 18s	remaining: 16m 8s
1284:	learn: 0.0131098	total: 2m 18s	remaining: 15m 39s
1287:	learn: 0.0150797	total: 2m 18s	remaining: 15m 37s
1193:	learn: 0.0165681	total: 2m 18s	remaining: 17m 2s
1305:	learn: 0.0135120	total: 2m 18s	remaining: 15m 23s
1285:	learn: 0.0130960	total: 2m 18s	remaining: 15m 39s
1252:	learn: 0.0148958	total: 2m 18s	remaining: 16m 8s
1288:	learn: 0.0150653	total: 2m 18s	remaining: 15m 36s
1194:	learn: 0.0165464	total: 2m 18s	remaining: 17m 2s
1306:	learn: 0.0134988	total: 2m 18s	remaining: 15m 23s
1286:	learn: 0.0130831	total: 2m 18s	remaining: 15m 39s
1195:	learn: 0.0165145	total: 2m 18s	remaining: 17m 1s
1253:	learn: 0.0148761	total: 2m 18s	remaining: 16m 8s
1289:	learn: 0.0150505	total: 2m 18s	remaining: 15m 36s
1307:	learn: 0.0134878	total: 2m 18s	remaining: 15m 23s
1254:	learn: 0.0148632	total: 2m 18s	remaining: 16m 7s
1287:	learn: 0.0130620	total: 2m 18s	remaining: 15m 39s
1196:	learn: 0.0164916	total: 2m 18s	remaining: 17m 1s
1290:	learn: 0.0150306	total: 2m 18s	remaining: 15m 36s
1308:	learn: 0.0134754	total: 2m 19s	remaining: 15m 23s
1255:	learn: 0.0148435	total: 2m 19s	remaining: 16m 7s
1288:	learn: 0.0130411	total: 2m 18s	remaining: 15m 39s
1291:	learn: 0.0150165	total: 2m 18s	remaining: 15m 36s
1309:	learn: 0.0134620	total: 2m 19s	remaining: 15m 22s
1197:	learn: 0.0164726	total: 2m 19s	remaining: 17m 1s
1289:	learn: 0.0130205	total: 2m 19s	remaining: 15m 38s
1292:	learn: 0.0150079	total: 2m 19s	remaining: 15m 36s
1256:	learn: 0.0148282	total: 2m 19s	remaining: 16m 7s
1310:	learn: 0.0134476	total: 2m 19s	remaining: 15m 22s
1198:	learn: 0.0164476	total: 2m 19s	remaining: 17m 1s
1290:	learn: 0.0130076	total: 2m 19s	remaining: 15m 38s
1293:	learn: 0.0149882	total: 2m 19s	remaining: 15m 36s
1257:	learn: 0.0148125	total: 2m 19s	remaining: 16m 7s
1199:	learn: 0.0164236	total: 2m 19s	remaining: 17m 1s
1291:	learn: 0.0129928	total: 2m 19s	remaining: 15m 38s
1311:	learn: 0.0134183	total: 2m 19s	remaining: 15m 22s
1294:	learn: 0.0149731	total: 2m 19s	remaining: 15m 36s
1258:	learn: 0.0147859	total: 2m 19s	remaining: 16m 7s
1200:	learn: 0.0164104	total: 2m 19s	remaining: 17m 1s
1292:	learn: 0.0129774	total: 2m 19s	remaining: 15m 38s
1312:	learn: 0.0134048	total: 2m 19s	remaining: 15m 22s
1259:	learn: 0.0147743	total: 2m 19s	remaining: 16m 7s
1295:	learn: 0.0149506	total: 2m 19s	remaining: 15m 35s
1313:	learn: 0.0133911	total: 2m 19s	remaining: 15m 22s
1293:	learn: 0.0129665	total: 2m 19s	remaining: 15m 38s
1201:	learn: 0.0163917	total: 2m 19s	remaining: 17m 1s
1260:	learn: 0.0147568	total: 2m 19s	remaining: 16m 6s
1296:	learn: 0.0149322	total: 2m 19s	remaining: 15m 35s
1314:	learn: 0.0133784	total: 2m 19s	remaining: 15m 22s
1294:	learn: 0.0129519	total: 2m 19s	remaining: 15m 37s
1297:	learn: 0.0149163	total: 2m 19s	remaining: 15m 35s
1261:	learn: 0.0147299	total: 2m 19s	remaining: 16m 6s
1202:	learn: 0.0163692	total: 2m 19s	remaining: 17m 1s
1315:	learn: 0.0133709	total: 2m 19s	remaining: 15m 21s
1295:	learn: 0.0129377	total: 2m 19s	remaining: 15m 37s
1298:	learn: 0.0148983	total: 2m 19s	remaining: 15m 35s
1316:	learn: 0.0133448	total: 2m 19s	remaining: 15m 21s
1262:	learn: 0.0147064	total: 2m 19s	remaining: 16m 6s
1203:	learn: 0.0163601	total: 2m 19s	remaining: 17m 1s
1296:	learn: 0.0129313	total: 2m 19s	remaining: 15m 37s
1317:	learn: 0.0133314	total: 2m 19s	remaining: 15m 21s
1299:	learn: 0.0148767	total: 2m 19s	remaining: 15m 35s
1263:	learn: 0.0146913	total: 2m 19s	remaining: 16m 6s
1297:	learn: 0.0129237	total: 2m 19s	remaining: 15m 37s
1204:	learn: 0.0163349	total: 2m 19s	remaining: 17m
1318:	learn: 0.0133100	total: 2m 19s	remaining: 15m 21s
1300:	learn: 0.0148610	total: 2m 19s	remaining: 15m 35s
1264:	learn: 0.0146731	total: 2m 19s	remaining: 16m 6s
1319:	learn: 0.0132874	total: 2m 20s	remaining: 15m 20s
1298:	learn: 0.0129020	total: 2m 19s	remaining: 15m 37s
1205:	learn: 0.0163133	total: 2m 20s	remaining: 17m
1301:	learn: 0.0148466	total: 2m 19s	remaining: 15m 34s
1320:	learn: 0.0132773	total: 2m 20s	remaining: 15m 20s
1265:	learn: 0.0146595	total: 2m 20s	remaining: 16m 6s
1299:	learn: 0.0128783	total: 2m 20s	remaining: 15m 37s
1206:	learn: 0.0162924	total: 2m 20s	remaining: 17m
1321:	learn: 0.0132644	total: 2m 20s	remaining: 15m 20s
1302:	learn: 0.0148327	total: 2m 20s	remaining: 15m 34s
1207:	learn: 0.0162688	total: 2m 20s	remaining: 17m
1266:	learn: 0.0146476	total: 2m 20s	remaining: 16m 6s
1300:	learn: 0.0128657	total: 2m 20s	remaining: 15m 37s
1303:	learn: 0.0148114	total: 2m 20s	remaining: 15m 34s
1322:	learn: 0.0132401	total: 2m 20s	remaining: 15m 20s
1208:	learn: 0.0162507	total: 2m 20s	remaining: 16m 59s
1267:	learn: 0.0146388	total: 2m 20s	remaining: 16m 5s
1301:	learn: 0.0128424	total: 2m 20s	remaining: 15m 36s
1323:	learn: 0.0132248	total: 2m 20s	remaining: 15m 20s
1304:	learn: 0.0147995	total: 2m 20s	remaining: 15m 34s
1209:	learn: 0.0162305	total: 2m 20s	remaining: 16m 59s
1268:	learn: 0.0146279	total: 2m 20s	remaining: 16m 5s
1302:	learn: 0.0128228	total: 2m 20s	remaining: 15m 36s
1324:	learn: 0.0132117	total: 2m 20s	remaining: 15m 19s
1305:	learn: 0.0147822	total: 2m 20s	remaining: 15m 34s
1210:	learn: 0.0162108	total: 2m 20s	remaining: 16m 59s
1325:	learn: 0.0132025	total: 2m 20s	remaining: 15m 19s
1269:	learn: 0.0146091	total: 2m 20s	remaining: 16m 5s
1303:	learn: 0.0128073	total: 2m 20s	remaining: 15m 36s
1306:	learn: 0.0147722	total: 2m 20s	remaining: 15m 34s
1211:	learn: 0.0161828	total: 2m 20s	remaining: 16m 59s
1326:	learn: 0.0131851	total: 2m 20s	remaining: 15m 19s
1304:	learn: 0.0127933	total: 2m 20s	remaining: 15m 36s
1212:	learn: 0.0161685	total: 2m 20s	remaining: 16m 58s
1270:	learn: 0.0145806	total: 2m 20s	remaining: 16m 5s
1327:	learn: 0.0131727	total: 2m 20s	remaining: 15m 19s
1307:	learn: 0.0147532	total: 2m 20s	remaining: 15m 34s
1305:	learn: 0.0127792	total: 2m 20s	remaining: 15m 36s
1213:	learn: 0.0161455	total: 2m 20s	remaining: 16m 58s
1328:	learn: 0.0131620	total: 2m 20s	remaining: 15m 18s
1271:	learn: 0.0145702	total: 2m 20s	remaining: 16m 5s
1306:	learn: 0.0127751	total: 2m 20s	remaining: 15m 35s
1308:	learn: 0.0147363	total: 2m 20s	remaining: 15m 34s
1329:	learn: 0.0131492	total: 2m 20s	remaining: 15m 18s
1214:	learn: 0.0161313	total: 2m 20s	remaining: 16m 58s
1307:	learn: 0.0127539	total: 2m 20s	remaining: 15m 35s
1272:	learn: 0.0145524	total: 2m 20s	remaining: 16m 5s
1309:	learn: 0.0147120	total: 2m 20s	remaining: 15m 34s
1330:	learn: 0.0131345	total: 2m 21s	remaining: 15m 18s
1308:	learn: 0.0127275	total: 2m 20s	remaining: 15m 35s
1215:	learn: 0.0161135	total: 2m 21s	remaining: 16m 58s
1273:	learn: 0.0145431	total: 2m 20s	remaining: 16m 5s
1310:	learn: 0.0146980	total: 2m 20s	remaining: 15m 34s
1331:	learn: 0.0131251	total: 2m 21s	remaining: 15m 18s
1309:	learn: 0.0127154	total: 2m 20s	remaining: 15m 35s
1216:	learn: 0.0160969	total: 2m 21s	remaining: 16m 58s
1274:	learn: 0.0145245	total: 2m 21s	remaining: 16m 5s
1332:	learn: 0.0131099	total: 2m 21s	remaining: 15m 17s
1311:	learn: 0.0146828	total: 2m 21s	remaining: 15m 33s
1310:	learn: 0.0127051	total: 2m 21s	remaining: 15m 35s
1275:	learn: 0.0145067	total: 2m 21s	remaining: 16m 5s
1333:	learn: 0.0130972	total: 2m 21s	remaining: 15m 17s
1217:	learn: 0.0160772	total: 2m 21s	remaining: 16m 58s
1312:	learn: 0.0146644	total: 2m 21s	remaining: 15m 33s
1311:	learn: 0.0126908	total: 2m 21s	remaining: 15m 35s
1334:	learn: 0.0130881	total: 2m 21s	remaining: 15m 17s
1276:	learn: 0.0144870	total: 2m 21s	remaining: 16m 5s
1218:	learn: 0.0160484	total: 2m 21s	remaining: 16m 57s
1313:	learn: 0.0146502	total: 2m 21s	remaining: 15m 33s
1312:	learn: 0.0126779	total: 2m 21s	remaining: 15m 34s
1219:	learn: 0.0160275	total: 2m 21s	remaining: 16m 57s
1335:	learn: 0.0130729	total: 2m 21s	remaining: 15m 17s
1277:	learn: 0.0144798	total: 2m 21s	remaining: 16m 5s
1314:	learn: 0.0146331	total: 2m 21s	remaining: 15m 33s
1313:	learn: 0.0126606	total: 2m 21s	remaining: 15m 34s
1220:	learn: 0.0160106	total: 2m 21s	remaining: 16m 57s
1336:	learn: 0.0130554	total: 2m 21s	remaining: 15m 17s
1278:	learn: 0.0144595	total: 2m 21s	remaining: 16m 4s
1314:	learn: 0.0126458	total: 2m 21s	remaining: 15m 34s
1315:	learn: 0.0146220	total: 2m 21s	remaining: 15m 33s
1221:	learn: 0.0159901	total: 2m 21s	remaining: 16m 57s

1337:	learn: 0.0130409	total: 2m 21s	remaining: 15m 17s
1279:	learn: 0.0144398	total: 2m 21s	remaining: 16m 4s
1316:	learn: 0.0146038	total: 2m 21s	remaining: 15m 33s
1222:	learn: 0.0159810	total: 2m 21s	remaining: 16m 56s
1338:	learn: 0.0130286	total: 2m 21s	remaining: 15m 17s
1280:	learn: 0.0144205	total: 2m 21s	remaining: 16m 4s
1316:	learn: 0.0126189	total: 2m 21s	remaining: 15m 34s
1317:	learn: 0.0145894	total: 2m 21s	remaining: 15m 33s
1223:	learn: 0.0159687	total: 2m 21s	remaining: 16m 56s
1281:	learn: 0.0144004	total: 2m 21s	remaining: 16m 4s
1317:	learn: 0.0125982	total: 2m 21s	remaining: 15m 33s
1339:	learn: 0.0130077	total: 2m 21s	remaining: 15m 16s
1318:	learn: 0.0145746	total: 2m 21s	remaining: 15m 33s
1340:	learn: 0.0129974	total: 2m 21s	remaining: 15m 16s
1282:	learn: 0.0143780	total: 2m 21s	remaining: 16m 4s
1318:	learn: 0.0125885	total: 2m 21s	remaining: 15m 33s
1224:	learn: 0.0159563	total: 2m 21s	remaining: 16m 56s
1319:	learn: 0.0125673	total: 2m 21s	remaining: 15m 33s
1319:	learn: 0.0145601	total: 2m 21s	remaining: 15m 33s
1341:	learn: 0.0129782	total: 2m 22s	remaining: 15m 16s
1283:	learn: 0.0143643	total: 2m 22s	remaining: 16m 4s
1225:	learn: 0.0159366	total: 2m 22s	remaining: 16m 56s
1320:	learn: 0.0125508	total: 2m 22s	remaining: 15m 33s
1320:	learn: 0.0145504	total: 2m 22s	remaining: 15m 33s
1284:	learn: 0.0143587	total: 2m 22s	remaining: 16m 3s
1342:	learn: 0.0129632	total: 2m 22s	remaining: 15m 16s
1226:	learn: 0.0159196	total: 2m 22s	remaining: 16m 56s
1321:	learn: 0.0125378	total: 2m 22s	remaining: 15m 32s
1321:	learn: 0.0145324	total: 2m 22s	remaining: 15m 32s
1285:	learn: 0.0143428	total: 2m 22s	remaining: 16m 3s
1343:	learn: 0.0129543	total: 2m 22s	remaining: 15m 16s
1227:	learn: 0.0159074	total: 2m 22s	remaining: 16m 56s
1322:	learn: 0.0125201	total: 2m 22s	remaining: 15m 32s
1322:	learn: 0.0145057	total: 2m 22s	remaining: 15m 32s
1286:	learn: 0.0143341	total: 2m 22s	remaining: 16m 3s
1344:	learn: 0.0129473	total: 2m 22s	remaining: 15m 16s
1228:	learn: 0.0158892	total: 2m 22s	remaining: 16m 56s
1323:	learn: 0.0124990	total: 2m 22s	remaining: 15m 32s
1323:	learn: 0.0144938	total: 2m 22s	remaining: 15m 32s
1345:	learn: 0.0129292	total: 2m 22s	remaining: 15m 16s
1287:	learn: 0.0143205	total: 2m 22s	remaining: 16m 3s
1229:	learn: 0.0158742	total: 2m 22s	remaining: 16m 55s
1324:	learn: 0.0124820	total: 2m 22s	remaining: 15m 32s
1324:	learn: 0.0144791	total: 2m 22s	remaining: 15m 32s
1346:	learn: 0.0129100	total: 2m 22s	remaining: 15m 15s
1288:	learn: 0.0143061	total: 2m 22s	remaining: 16m 3s
1230:	learn: 0.0158502	total: 2m 22s	remaining: 16m 55s
1325:	learn: 0.0124725	total: 2m 22s	remaining: 15m 32s
1325:	learn: 0.0144656	total: 2m 22s	remaining: 15m 32s
1347:	learn: 0.0129012	total: 2m 22s	remaining: 15m 15s
1231:	learn: 0.0158312	total: 2m 22s	remaining: 16m 55s
1289:	learn: 0.0142926	total: 2m 22s	remaining: 16m 3s
1326:	learn: 0.0144472	total: 2m 22s	remaining: 15m 32s
1348:	learn: 0.0128902	total: 2m 22s	remaining: 15m 15s
1326:	learn: 0.0124508	total: 2m 22s	remaining: 15m 32s
1232:	learn: 0.0158105	total: 2m 22s	remaining: 16m 55s
1290:	learn: 0.0142733	total: 2m 22s	remaining: 16m 3s
1349:	learn: 0.0128731	total: 2m 22s	remaining: 15m 15s
1327:	learn: 0.0144329	total: 2m 22s	remaining: 15m 31s
1233:	learn: 0.0157799	total: 2m 22s	remaining: 16m 54s
1327:	learn: 0.0124250	total: 2m 22s	remaining: 15m 32s
1350:	learn: 0.0128609	total: 2m 22s	remaining: 15m 14s
1291:	learn: 0.0142599	total: 2m 22s	remaining: 16m 2s
1328:	learn: 0.0144224	total: 2m 22s	remaining: 15m 31s
1234:	learn: 0.0157575	total: 2m 22s	remaining: 16m 54s
1328:	learn: 0.0124127	total: 2m 22s	remaining: 15m 32s
1292:	learn: 0.0142386	total: 2m 22s	remaining: 16m 2s
1351:	learn: 0.0128505	total: 2m 23s	remaining: 15m 14s
1329:	learn: 0.0144057	total: 2m 22s	remaining: 15m 31s
1235:	learn: 0.0157374	total: 2m 23s	remaining: 16m 54s
1329:	learn: 0.0123971	total: 2m 22s	remaining: 15m 32s
1293:	learn: 0.0142193	total: 2m 23s	remaining: 16m 2s
1352:	learn: 0.0128357	total: 2m 23s	remaining: 15m 14s
1330:	learn: 0.0143930	total: 2m 23s	remaining: 15m 31s
1236:	learn: 0.0157174	total: 2m 23s	remaining: 16m 53s
1294:	learn: 0.0142062	total: 2m 23s	remaining: 16m 2s
1330:	learn: 0.0123832	total: 2m 23s	remaining: 15m 32s
1353:	learn: 0.0128144	total: 2m 23s	remaining: 15m 14s
1331:	learn: 0.0143764	total: 2m 23s	remaining: 15m 31s
1295:	learn: 0.0141932	total: 2m 23s	remaining: 16m 2s
1237:	learn: 0.0157002	total: 2m 23s	remaining: 16m 54s
1331:	learn: 0.0123694	total: 2m 23s	remaining: 15m 31s
1332:	learn: 0.0143590	total: 2m 23s	remaining: 15m 31s
1354:	learn: 0.0128051	total: 2m 23s	remaining: 15m 14s
1238:	learn: 0.0156809	total: 2m 23s	remaining: 16m 53s
1296:	learn: 0.0141664	total: 2m 23s	remaining: 16m 1s
1332:	learn: 0.0123544	total: 2m 23s	remaining: 15m 31s
1355:	learn: 0.0127889	total: 2m 23s	remaining: 15m 14s
1333:	learn: 0.0143408	total: 2m 23s	remaining: 15m 31s
1239:	learn: 0.0156597	total: 2m 23s	remaining: 16m 53s
1297:	learn: 0.0141472	total: 2m 23s	remaining: 16m 1s
1333:	learn: 0.0123399	total: 2m 23s	remaining: 15m 31s
1240:	learn: 0.0156397	total: 2m 23s	remaining: 16m 53s
1356:	learn: 0.0127758	total: 2m 23s	remaining: 15m 14s
1334:	learn: 0.0143211	total: 2m 23s	remaining: 15m 31s
1298:	learn: 0.0141351	total: 2m 23s	remaining: 16m 1s
1334:	learn: 0.0123269	total: 2m 23s	remaining: 15m 31s
1241:	learn: 0.0156245	total: 2m 23s	remaining: 16m 52s
1335:	learn: 0.0143049	total: 2m 23s	remaining: 15m 30s
1357:	learn: 0.0127605	total: 2m 23s	remaining: 15m 14s
1335:	learn: 0.0123119	total: 2m 23s	remaining: 15m 31s
1299:	learn: 0.0141161	total: 2m 23s	remaining: 16m 1s
1336:	learn: 0.0142910	total: 2m 23s	remaining: 15m 30s
1242:	learn: 0.0156052	total: 2m 23s	remaining: 16m 52s
1358:	learn: 0.0127527	total: 2m 23s	remaining: 15m 14s
1336:	learn: 0.0122998	total: 2m 23s	remaining: 15m 31s
1337:	learn: 0.0142788	total: 2m 23s	remaining: 15m 30s
1300:	learn: 0.0141033	total: 2m 23s	remaining: 16m 1s
1337:	learn: 0.0122787	total: 2m 23s	remaining: 15m 30s
1243:	learn: 0.0155758	total: 2m 23s	remaining: 16m 52s
1338:	learn: 0.0142642	total: 2m 23s	remaining: 15m 30s
1359:	learn: 0.0127431	total: 2m 23s	remaining: 15m 14s
1301:	learn: 0.0140968	total: 2m 23s	remaining: 16m 1s
1338:	learn: 0.0122664	total: 2m 23s	remaining: 15m 30s
1339:	learn: 0.0142528	total: 2m 23s	remaining: 15m 29s
1360:	learn: 0.0127313	total: 2m 24s	remaining: 15m 14s
1244:	learn: 0.0155527	total: 2m 23s	remaining: 16m 52s
1339:	learn: 0.0122539	total: 2m 23s	remaining: 15m 30s
1302:	learn: 0.0140851	total: 2m 24s	remaining: 16m 1s
1340:	learn: 0.0142346	total: 2m 23s	remaining: 15m 29s
1361:	learn: 0.0127120	total: 2m 24s	remaining: 15m 13s
1245:	learn: 0.0155328	total: 2m 24s	remaining: 16m 52s
1340:	learn: 0.0122382	total: 2m 24s	remaining: 15m 30s
1341:	learn: 0.0142250	total: 2m 24s	remaining: 15m 29s
1303:	learn: 0.0140664	total: 2m 24s	remaining: 16m 1s
1362:	learn: 0.0127049	total: 2m 24s	remaining: 15m 13s
1341:	learn: 0.0122229	total: 2m 24s	remaining: 15m 29s
1246:	learn: 0.0155031	total: 2m 24s	remaining: 16m 52s
1342:	learn: 0.0142074	total: 2m 24s	remaining: 15m 29s
1304:	learn: 0.0140538	total: 2m 24s	remaining: 16m
1342:	learn: 0.0122102	total: 2m 24s	remaining: 15m 29s
1363:	learn: 0.0126873	total: 2m 24s	remaining: 15m 13s
1247:	learn: 0.0154802	total: 2m 24s	remaining: 16m 52s
1305:	learn: 0.0140361	total: 2m 24s	remaining: 16m
1343:	learn: 0.0121980	total: 2m 24s	remaining: 15m 29s
1343:	learn: 0.0141936	total: 2m 24s	remaining: 15m 29s
1364:	learn: 0.0126698	total: 2m 24s	remaining: 15m 13s
1306:	learn: 0.0140177	total: 2m 24s	remaining: 16m
1344:	learn: 0.0121871	total: 2m 24s	remaining: 15m 29s
1365:	learn: 0.0126559	total: 2m 24s	remaining: 15m 13s
1248:	learn: 0.0154671	total: 2m 24s	remaining: 16m 52s
1344:	learn: 0.0141794	total: 2m 24s	remaining: 15m 29s
1307:	learn: 0.0139988	total: 2m 24s	remaining: 16m
1345:	learn: 0.0121762	total: 2m 24s	remaining: 15m 28s
1249:	learn: 0.0154540	total: 2m 24s	remaining: 16m 52s
1345:	learn: 0.0141644	total: 2m 24s	remaining: 15m 28s
0.0159901	total: 2m 21s	remaining: 16m 57s
 s
 
 1      1366:	learn: 0.0126417	total: 2m 24s	remaining: 15m 13s
1308:	learn: 0.0139864	total: 2m 24s	remaining: 16m
1346:	learn: 0.0121638	total: 2m 24s	remaining: 15m 28s
1346:	learn: 0.0141529	total: 2m 24s	remaining: 15m 28s
1367:	learn: 0.0126192	total: 2m 24s	remaining: 15m 13s
1250:	learn: 0.0154366	total: 2m 24s	remaining: 16m 51s
1347:	learn: 0.0121509	total: 2m 24s	remaining: 15m 28s
1309:	learn: 0.0139728	total: 2m 24s	remaining: 15m 59s
1347:	learn: 0.0141431	total: 2m 24s	remaining: 15m 28s
1368:	learn: 0.0126020	total: 2m 24s	remaining: 15m 13s
1251:	learn: 0.0154116	total: 2m 24s	remaining: 16m 51s
1348:	learn: 0.0121335	total: 2m 24s	remaining: 15m 28s
1310:	learn: 0.0139641	total: 2m 24s	remaining: 15m 59s
1348:	learn: 0.0141254	total: 2m 24s	remaining: 15m 28s
1252:	learn: 0.0153944	total: 2m 24s	remaining: 16m 51s
1369:	learn: 0.0125886	total: 2m 24s	remaining: 15m 12s
1349:	learn: 0.0121216	total: 2m 24s	remaining: 15m 27s
1311:	learn: 0.0139450	total: 2m 24s	remaining: 15m 59s
1253:	learn: 0.0153753	total: 2m 24s	remaining: 16m 50s
1349:	learn: 0.0141145	total: 2m 24s	remaining: 15m 28s
1370:	learn: 0.0125753	total: 2m 25s	remaining: 15m 12s
1350:	learn: 0.0121093	total: 2m 24s	remaining: 15m 28s
1350:	learn: 0.0140856	total: 2m 24s	remaining: 15m 27s
1312:	learn: 0.0139221	total: 2m 25s	remaining: 15m 59s
1371:	learn: 0.0125550	total: 2m 25s	remaining: 15m 12s
1254:	learn: 0.0153613	total: 2m 25s	remaining: 16m 50s
1351:	learn: 0.0120936	total: 2m 25s	remaining: 15m 27s
1351:	learn: 0.0140716	total: 2m 25s	remaining: 15m 27s
1313:	learn: 0.0139098	total: 2m 25s	remaining: 15m 59s
1372:	learn: 0.0125347	total: 2m 25s	remaining: 15m 12s
1352:	learn: 0.0120767	total: 2m 25s	remaining: 15m 27s
1352:	learn: 0.0140543	total: 2m 25s	remaining: 15m 27s
1314:	learn: 0.0138966	total: 2m 25s	remaining: 15m 59s
1255:	learn: 0.0153409	total: 2m 25s	remaining: 16m 51s
1373:	learn: 0.0125235	total: 2m 25s	remaining: 15m 12s
1353:	learn: 0.0120564	total: 2m 25s	remaining: 15m 27s
1353:	learn: 0.0140369	total: 2m 25s	remaining: 15m 27s
1256:	learn: 0.0153077	total: 2m 25s	remaining: 16m 50s
1315:	learn: 0.0138851	total: 2m 25s	remaining: 15m 59s
1354:	learn: 0.0120407	total: 2m 25s	remaining: 15m 27s
1374:	learn: 0.0125063	total: 2m 25s	remaining: 15m 12s
1257:	learn: 0.0152867	total: 2m 25s	remaining: 16m 50s
1354:	learn: 0.0140197	total: 2m 25s	remaining: 15m 27s
1316:	learn: 0.0138664	total: 2m 25s	remaining: 15m 58s
1375:	learn: 0.0124868	total: 2m 25s	remaining: 15m 12s
1355:	learn: 0.0120290	total: 2m 25s	remaining: 15m 27s
1258:	learn: 0.0152646	total: 2m 25s	remaining: 16m 50s
1355:	learn: 0.0140079	total: 2m 25s	remaining: 15m 27s
1317:	learn: 0.0138579	total: 2m 25s	remaining: 15m 58s
1356:	learn: 0.0120152	total: 2m 25s	remaining: 15m 26s
1259:	learn: 0.0152535	total: 2m 25s	remaining: 16m 50s
1376:	learn: 0.0124663	total: 2m 25s	remaining: 15m 12s
1318:	learn: 0.0138494	total: 2m 25s	remaining: 15m 58s
1356:	learn: 0.0139944	total: 2m 25s	remaining: 15m 27s
1357:	learn: 0.0120046	total: 2m 25s	remaining: 15m 26s
1377:	learn: 0.0124537	total: 2m 25s	remaining: 15m 11s
1260:	learn: 0.0152380	total: 2m 25s	remaining: 16m 49s
1319:	learn: 0.0138283	total: 2m 25s	remaining: 15m 58s
1357:	learn: 0.0139819	total: 2m 25s	remaining: 15m 27s
1358:	learn: 0.0119949	total: 2m 25s	remaining: 15m 26s
1378:	learn: 0.0124364	total: 2m 25s	remaining: 15m 11s
1261:	learn: 0.0152259	total: 2m 25s	remaining: 16m 49s
1320:	learn: 0.0138220	total: 2m 25s	remaining: 15m 57s
1359:	learn: 0.0119814	total: 2m 25s	remaining: 15m 26s
1358:	learn: 0.0139712	total: 2m 25s	remaining: 15m 26s
1262:	learn: 0.0152084	total: 2m 25s	remaining: 16m 49s
1379:	learn: 0.0124167	total: 2m 25s	remaining: 15m 11s
1321:	learn: 0.0138100	total: 2m 25s	remaining: 15m 57s
1360:	learn: 0.0119609	total: 2m 25s	remaining: 15m 26s
1359:	learn: 0.0139545	total: 2m 25s	remaining: 15m 26s
1263:	learn: 0.0151899	total: 2m 26s	remaining: 16m 49s
1380:	learn: 0.0124099	total: 2m 26s	remaining: 15m 11s
1322:	learn: 0.0137908	total: 2m 26s	remaining: 15m 57s
1361:	learn: 0.0119448	total: 2m 26s	remaining: 15m 25s
1264:	learn: 0.0151692	total: 2m 26s	remaining: 16m 48s
1360:	learn: 0.0139428	total: 2m 26s	remaining: 15m 26s
1381:	learn: 0.0124002	total: 2m 26s	remaining: 15m 11s
1323:	learn: 0.0137603	total: 2m 26s	remaining: 15m 57s
1362:	learn: 0.0119303	total: 2m 26s	remaining: 15m 25s
1361:	learn: 0.0139338	total: 2m 26s	remaining: 15m 26s
1382:	learn: 0.0123878	total: 2m 26s	remaining: 15m 11s
1265:	learn: 0.0151444	total: 2m 26s	remaining: 16m 48s
1324:	learn: 0.0137485	total: 2m 26s	remaining: 15m 57s
1363:	learn: 0.0119185	total: 2m 26s	remaining: 15m 25s
1362:	learn: 0.0139162	total: 2m 26s	remaining: 15m 26s
1266:	learn: 0.0151289	total: 2m 26s	remaining: 16m 48s
1383:	learn: 0.0123772	total: 2m 26s	remaining: 15m 11s
1325:	learn: 0.0137328	total: 2m 26s	remaining: 15m 57s
1364:	learn: 0.0119059	total: 2m 26s	remaining: 15m 25s
1363:	learn: 0.0139010	total: 2m 26s	remaining: 15m 26s
1267:	learn: 0.0151001	total: 2m 26s	remaining: 16m 48s
1384:	learn: 0.0123676	total: 2m 26s	remaining: 15m 10s
1365:	learn: 0.0118901	total: 2m 26s	remaining: 15m 25s
1326:	learn: 0.0137149	total: 2m 26s	remaining: 15m 57s
1268:	learn: 0.0150834	total: 2m 26s	remaining: 16m 47s
1385:	learn: 0.0123516	total: 2m 26s	remaining: 15m 10s
1364:	learn: 0.0138873	total: 2m 26s	remaining: 15m 26s
1366:	learn: 0.0118761	total: 2m 26s	remaining: 15m 25s
1269:	learn: 0.0150647	total: 2m 26s	remaining: 16m 47s
1327:	learn: 0.0136994	total: 2m 26s	remaining: 15m 57s
1365:	learn: 0.0138698	total: 2m 26s	remaining: 15m 26s
1386:	learn: 0.0123343	total: 2m 26s	remaining: 15m 10s
1367:	learn: 0.0118612	total: 2m 26s	remaining: 15m 24s
1270:	learn: 0.0150371	total: 2m 26s	remaining: 16m 47s
1366:	learn: 0.0138579	total: 2m 26s	remaining: 15m 25s
1328:	learn: 0.0136909	total: 2m 26s	remaining: 15m 56s
1387:	learn: 0.0123172	total: 2m 26s	remaining: 15m 10s
1368:	learn: 0.0118495	total: 2m 26s	remaining: 15m 24s
1329:	learn: 0.0136650	total: 2m 26s	remaining: 15m 56s
1271:	learn: 0.0150186	total: 2m 26s	remaining: 16m 47s
1367:	learn: 0.0138405	total: 2m 26s	remaining: 15m 25s
1388:	learn: 0.0123061	total: 2m 26s	remaining: 15m 10s
1369:	learn: 0.0118445	total: 2m 26s	remaining: 15m 24s
1330:	learn: 0.0136430	total: 2m 26s	remaining: 15m 56s
1368:	learn: 0.0138239	total: 2m 26s	remaining: 15m 25s
1272:	learn: 0.0150087	total: 2m 26s	remaining: 16m 47s
1389:	learn: 0.0122950	total: 2m 26s	remaining: 15m 10s
1370:	learn: 0.0118336	total: 2m 26s	remaining: 15m 24s
1369:	learn: 0.0138072	total: 2m 26s	remaining: 15m 25s
1273:	learn: 0.0150029	total: 2m 26s	remaining: 16m 46s
1331:	learn: 0.0136225	total: 2m 26s	remaining: 15m 56s
1390:	learn: 0.0122817	total: 2m 27s	remaining: 15m 10s
1370:	learn: 0.0137826	total: 2m 26s	remaining: 15m 24s
1371:	learn: 0.0118141	total: 2m 26s	remaining: 15m 24s
1391:	learn: 0.0122635	total: 2m 27s	remaining: 15m 9s
1274:	learn: 0.0149852	total: 2m 27s	remaining: 16m 46s
1332:	learn: 0.0135974	total: 2m 27s	remaining: 15m 56s
1371:	learn: 0.0137698	total: 2m 27s	remaining: 15m 24s
1372:	learn: 0.0117948	total: 2m 27s	remaining: 15m 24s
1392:	learn: 0.0122458	total: 2m 27s	remaining: 15m 9s
1333:	learn: 0.0135858	total: 2m 27s	remaining: 15m 56s
1373:	learn: 0.0117835	total: 2m 27s	remaining: 15m 23s
1275:	learn: 0.0149747	total: 2m 27s	remaining: 16m 46s
1372:	learn: 0.0137535	total: 2m 27s	remaining: 15m 24s
1393:	learn: 0.0122381	total: 2m 27s	remaining: 15m 9s
1374:	learn: 0.0117736	total: 2m 27s	remaining: 15m 23s
1276:	learn: 0.0149591	total: 2m 27s	remaining: 16m 46s
1334:	learn: 0.0135779	total: 2m 27s	remaining: 15m 56s
1394:	learn: 0.0122265	total: 2m 27s	remaining: 15m 9s
1373:	learn: 0.0137372	total: 2m 27s	remaining: 15m 24s
1395:	learn: 0.0122145	total: 2m 27s	remaining: 15m 8s
1335:	learn: 0.0135626	total: 2m 27s	remaining: 15m 56s
1277:	learn: 0.0149391	total: 2m 27s	remaining: 16m 46s
1375:	learn: 0.0117506	total: 2m 27s	remaining: 15m 23s
1374:	learn: 0.0137218	total: 2m 27s	remaining: 15m 24s
1396:	learn: 0.0121988	total: 2m 27s	remaining: 15m 8s

1278:	learn: 0.0149173	total: 2m 27s	remaining: 16m 46s
1376:	learn: 0.0117458	total: 2m 27s	remaining: 15m 23s
1336:	learn: 0.0135511	total: 2m 27s	remaining: 15m 55s
1397:	learn: 0.0121896	total: 2m 27s	remaining: 15m 8s
1375:	learn: 0.0137047	total: 2m 27s	remaining: 15m 24s
1279:	learn: 0.0149017	total: 2m 27s	remaining: 16m 45s
1337:	learn: 0.0135339	total: 2m 27s	remaining: 15m 55s
1377:	learn: 0.0117344	total: 2m 27s	remaining: 15m 23s
1398:	learn: 0.0121731	total: 2m 27s	remaining: 15m 8s
1376:	learn: 0.0136945	total: 2m 27s	remaining: 15m 24s
1338:	learn: 0.0135151	total: 2m 27s	remaining: 15m 55s
1280:	learn: 0.0148866	total: 2m 27s	remaining: 16m 45s
1378:	learn: 0.0117197	total: 2m 27s	remaining: 15m 23s
1399:	learn: 0.0121600	total: 2m 27s	remaining: 15m 8s
1377:	learn: 0.0136833	total: 2m 27s	remaining: 15m 24s
1400:	learn: 0.0121507	total: 2m 27s	remaining: 15m 7s
1281:	learn: 0.0148679	total: 2m 27s	remaining: 16m 45s
1339:	learn: 0.0135037	total: 2m 27s	remaining: 15m 55s
1378:	learn: 0.0136738	total: 2m 27s	remaining: 15m 23s
1379:	learn: 0.0117029	total: 2m 27s	remaining: 15m 23s
1401:	learn: 0.0121347	total: 2m 28s	remaining: 15m 7s
1340:	learn: 0.0134927	total: 2m 27s	remaining: 15m 55s
1282:	learn: 0.0148551	total: 2m 27s	remaining: 16m 45s
1379:	learn: 0.0136555	total: 2m 27s	remaining: 15m 23s
1380:	learn: 0.0116971	total: 2m 27s	remaining: 15m 23s
1402:	learn: 0.0121230	total: 2m 28s	remaining: 15m 7s
1380:	learn: 0.0136428	total: 2m 27s	remaining: 15m 23s
1341:	learn: 0.0134757	total: 2m 28s	remaining: 15m 55s
1403:	learn: 0.0121091	total: 2m 28s	remaining: 15m 7s
1283:	learn: 0.0148379	total: 2m 28s	remaining: 16m 45s
1381:	learn: 0.0116848	total: 2m 28s	remaining: 15m 23s
1381:	learn: 0.0136306	total: 2m 28s	remaining: 15m 23s
1342:	learn: 0.0134573	total: 2m 28s	remaining: 15m 55s
1382:	learn: 0.0116697	total: 2m 28s	remaining: 15m 23s
1284:	learn: 0.0148111	total: 2m 28s	remaining: 16m 45s
1404:	learn: 0.0120945	total: 2m 28s	remaining: 15m 7s
1382:	learn: 0.0136206	total: 2m 28s	remaining: 15m 23s
1343:	learn: 0.0134452	total: 2m 28s	remaining: 15m 54s
1383:	learn: 0.0116509	total: 2m 28s	remaining: 15m 22s
1285:	learn: 0.0147933	total: 2m 28s	remaining: 16m 45s
1405:	learn: 0.0120868	total: 2m 28s	remaining: 15m 7s
1383:	learn: 0.0136063	total: 2m 28s	remaining: 15m 23s
1384:	learn: 0.0116307	total: 2m 28s	remaining: 15m 22s
1344:	learn: 0.0134283	total: 2m 28s	remaining: 15m 54s
1286:	learn: 0.0147642	total: 2m 28s	remaining: 16m 44s
1406:	learn: 0.0120766	total: 2m 28s	remaining: 15m 6s
1384:	learn: 0.0135889	total: 2m 28s	remaining: 15m 23s
1385:	learn: 0.0116186	total: 2m 28s	remaining: 15m 22s
1345:	learn: 0.0134117	total: 2m 28s	remaining: 15m 54s
1287:	learn: 0.0147379	total: 2m 28s	remaining: 16m 44s
1385:	learn: 0.0135718	total: 2m 28s	remaining: 15m 22s
1407:	learn: 0.0120631	total: 2m 28s	remaining: 15m 6s
1386:	learn: 0.0116067	total: 2m 28s	remaining: 15m 22s
1346:	learn: 0.0134007	total: 2m 28s	remaining: 15m 54s
1288:	learn: 0.0147217	total: 2m 28s	remaining: 16m 44s
1386:	learn: 0.0135566	total: 2m 28s	remaining: 15m 22s
1408:	learn: 0.0120465	total: 2m 28s	remaining: 15m 6s
1387:	learn: 0.0115979	total: 2m 28s	remaining: 15m 22s
1409:	learn: 0.0120295	total: 2m 28s	remaining: 15m 6s
1347:	learn: 0.0133894	total: 2m 28s	remaining: 15m 54s
1387:	learn: 0.0135338	total: 2m 28s	remaining: 15m 22s
1289:	learn: 0.0147022	total: 2m 28s	remaining: 16m 44s
1388:	learn: 0.0115836	total: 2m 28s	remaining: 15m 22s
1410:	learn: 0.0120205	total: 2m 28s	remaining: 15m 6s
1388:	learn: 0.0135244	total: 2m 28s	remaining: 15m 22s
1348:	learn: 0.0133701	total: 2m 28s	remaining: 15m 54s
1389:	learn: 0.0115659	total: 2m 28s	remaining: 15m 21s
1290:	learn: 0.0146818	total: 2m 28s	remaining: 16m 44s
1411:	learn: 0.0120064	total: 2m 28s	remaining: 15m 5s
1389:	learn: 0.0135114	total: 2m 28s	remaining: 15m 22s
1390:	learn: 0.0115454	total: 2m 28s	remaining: 15m 21s
1291:	learn: 0.0146660	total: 2m 28s	remaining: 16m 44s
1412:	learn: 0.0119884	total: 2m 29s	remaining: 15m 5s
1349:	learn: 0.0133618	total: 2m 28s	remaining: 15m 54s
1390:	learn: 0.0134983	total: 2m 28s	remaining: 15m 21s
1413:	learn: 0.0119748	total: 2m 29s	remaining: 15m 5s
1391:	learn: 0.0115331	total: 2m 29s	remaining: 15m 21s
1391:	learn: 0.0134829	total: 2m 29s	remaining: 15m 21s
1292:	learn: 0.0146512	total: 2m 29s	remaining: 16m 44s
1350:	learn: 0.0133471	total: 2m 29s	remaining: 15m 54s
1414:	learn: 0.0119622	total: 2m 29s	remaining: 15m 5s
1293:	learn: 0.0146362	total: 2m 29s	remaining: 16m 43s
1415:	learn: 0.0119484	total: 2m 29s	remaining: 15m 4s
1392:	learn: 0.0115183	total: 2m 29s	remaining: 15m 21s
1392:	learn: 0.0134734	total: 2m 29s	remaining: 15m 21s
1351:	learn: 0.0133259	total: 2m 29s	remaining: 15m 54s
1294:	learn: 0.0146102	total: 2m 29s	remaining: 16m 43s
1393:	learn: 0.0115082	total: 2m 29s	remaining: 15m 21s
1416:	learn: 0.0119395	total: 2m 29s	remaining: 15m 4s
1352:	learn: 0.0132973	total: 2m 29s	remaining: 15m 54s
1393:	learn: 0.0134596	total: 2m 29s	remaining: 15m 21s
1394:	learn: 0.0114968	total: 2m 29s	remaining: 15m 21s
1295:	learn: 0.0145946	total: 2m 29s	remaining: 16m 43s
1417:	learn: 0.0119227	total: 2m 29s	remaining: 15m 4s
1353:	learn: 0.0132830	total: 2m 29s	remaining: 15m 54s
1394:	learn: 0.0134468	total: 2m 29s	remaining: 15m 21s
1395:	learn: 0.0114882	total: 2m 29s	remaining: 15m 20s
1418:	learn: 0.0119073	total: 2m 29s	remaining: 15m 4s
1296:	learn: 0.0145724	total: 2m 29s	remaining: 16m 43s
1354:	learn: 0.0132634	total: 2m 29s	remaining: 15m 53s
1395:	learn: 0.0134295	total: 2m 29s	remaining: 15m 21s
1396:	learn: 0.0114745	total: 2m 29s	remaining: 15m 20s
1297:	learn: 0.0145522	total: 2m 29s	remaining: 16m 42s
1419:	learn: 0.0118972	total: 2m 29s	remaining: 15m 4s
1355:	learn: 0.0132547	total: 2m 29s	remaining: 15m 53s
1420:	learn: 0.0118910	total: 2m 29s	remaining: 15m 3s
1396:	learn: 0.0134168	total: 2m 29s	remaining: 15m 21s
1397:	learn: 0.0114587	total: 2m 29s	remaining: 15m 20s
1298:	learn: 0.0145335	total: 2m 29s	remaining: 16m 42s
1421:	learn: 0.0118798	total: 2m 29s	remaining: 15m 3s
1356:	learn: 0.0132384	total: 2m 29s	remaining: 15m 53s
1397:	learn: 0.0133934	total: 2m 29s	remaining: 15m 21s
1398:	learn: 0.0114419	total: 2m 29s	remaining: 15m 20s
1299:	learn: 0.0145204	total: 2m 29s	remaining: 16m 42s
1422:	learn: 0.0118711	total: 2m 29s	remaining: 15m 3s
1398:	learn: 0.0133777	total: 2m 29s	remaining: 15m 20s
1357:	learn: 0.0132277	total: 2m 29s	remaining: 15m 53s
1399:	learn: 0.0114309	total: 2m 29s	remaining: 15m 20s
1300:	learn: 0.0145106	total: 2m 29s	remaining: 16m 42s
1423:	learn: 0.0118593	total: 2m 29s	remaining: 15m 3s
1358:	learn: 0.0132153	total: 2m 29s	remaining: 15m 53s
1399:	learn: 0.0133689	total: 2m 29s	remaining: 15m 20s
1400:	learn: 0.0114120	total: 2m 29s	remaining: 15m 20s
1301:	learn: 0.0144921	total: 2m 30s	remaining: 16m 42s
1424:	learn: 0.0118410	total: 2m 30s	remaining: 15m 3s
1400:	learn: 0.0133553	total: 2m 29s	remaining: 15m 20s
1359:	learn: 0.0131951	total: 2m 30s	remaining: 15m 53s
1401:	learn: 0.0113881	total: 2m 30s	remaining: 15m 20s
1302:	learn: 0.0144703	total: 2m 30s	remaining: 16m 42s
1425:	learn: 0.0118336	total: 2m 30s	remaining: 15m 2s
1360:	learn: 0.0131777	total: 2m 30s	remaining: 15m 52s
1401:	learn: 0.0133401	total: 2m 30s	remaining: 15m 20s
1426:	learn: 0.0118200	total: 2m 30s	remaining: 15m 2s
1303:	learn: 0.0144405	total: 2m 30s	remaining: 16m 41s
1402:	learn: 0.0113770	total: 2m 30s	remaining: 15m 20s
1361:	learn: 0.0131586	total: 2m 30s	remaining: 15m 52s
1402:	learn: 0.0133299	total: 2m 30s	remaining: 15m 20s
1304:	learn: 0.0144236	total: 2m 30s	remaining: 16m 41s
1427:	learn: 0.0118076	total: 2m 30s	remaining: 15m 2s
1362:	learn: 0.0131506	total: 2m 30s	remaining: 15m 52s
1403:	learn: 0.0113635	total: 2m 30s	remaining: 15m 20s
1403:	learn: 0.0133150	total: 2m 30s	remaining: 15m 20s
1305:	learn: 0.0144149	total: 2m 30s	remaining: 16m 41s
1363:	learn: 0.0131395	total: 2m 30s	remaining: 15m 52s
1404:	learn: 0.0113505	total: 2m 30s	remaining: 15m 20s
1404:	learn: 0.0133021	total: 2m 30s	remaining: 15m 19s
1428:	learn: 0.0117936	total: 2m 30s	remaining: 15m 2s
1306:	learn: 0.0143931	total: 2m 30s	remaining: 16m 41s
1405:	learn: 0.0132820	total: 2m 30s	remaining: 15m 19s
1364:	learn: 0.0131287	total: 2m 30s	remaining: 15m 52s
1405:	learn: 0.0113377	total: 2m 30s	remaining: 15m 20s
1429:	learn: 0.0117784	total: 2m 30s	remaining: 15m 2s
1307:	learn: 0.0143780	total: 2m 30s	remaining: 16m 40s
1365:	learn: 0.0131113	total: 2m 30s	remaining: 15m 51s
1406:	learn: 0.0132700	total: 2m 30s	remaining: 15m 19s
1406:	learn: 0.0113251	total: 2m 30s	remaining: 15m 19s
1430:	learn: 0.0117653	total: 2m 30s	remaining: 15m 2s
1407:	learn: 0.0132561	total: 2m 30s	remaining: 15m 19s
1366:	learn: 0.0130883	total: 2m 30s	remaining: 15m 51s
1308:	learn: 0.0143483	total: 2m 30s	remaining: 16m 40s
1407:	learn: 0.0113133	total: 2m 30s	remaining: 15m 19s
1408:	learn: 0.0132407	total: 2m 30s	remaining: 15m 18s
1431:	learn: 0.0117508	total: 2m 30s	remaining: 15m 2s
1408:	learn: 0.0112961	total: 2m 30s	remaining: 15m 19s
1367:	learn: 0.0130697	total: 2m 30s	remaining: 15m 51s
1409:	learn: 0.0132304	total: 2m 30s	remaining: 15m 18s
1432:	learn: 0.0117421	total: 2m 30s	remaining: 15m 2s
1309:	learn: 0.0143368	total: 2m 30s	remaining: 16m 41s
1409:	learn: 0.0112865	total: 2m 30s	remaining: 15m 19s
1368:	learn: 0.0130471	total: 2m 30s	remaining: 15m 51s
1410:	learn: 0.0132200	total: 2m 30s	remaining: 15m 18s
1433:	learn: 0.0117306	total: 2m 31s	remaining: 15m 2s
1310:	learn: 0.0143091	total: 2m 31s	remaining: 16m 41s
1410:	learn: 0.0112779	total: 2m 30s	remaining: 15m 19s
1369:	learn: 0.0130283	total: 2m 31s	remaining: 15m 51s
1411:	learn: 0.0132053	total: 2m 30s	remaining: 15m 18s
1434:	learn: 0.0117248	total: 2m 31s	remaining: 15m 2s
1311:	learn: 0.0142910	total: 2m 31s	remaining: 16m 40s
1411:	learn: 0.0112630	total: 2m 31s	remaining: 15m 18s
1370:	learn: 0.0130047	total: 2m 31s	remaining: 15m 51s
1412:	learn: 0.0131947	total: 2m 31s	remaining: 15m 18s
1435:	learn: 0.0117118	total: 2m 31s	remaining: 15m 1s
1312:	learn: 0.0142824	total: 2m 31s	remaining: 16m 40s
1371:	learn: 0.0129940	total: 2m 31s	remaining: 15m 50s
1412:	learn: 0.0112517	total: 2m 31s	remaining: 15m 18s
1436:	learn: 0.0116966	total: 2m 31s	remaining: 15m 1s
1413:	learn: 0.0131804	total: 2m 31s	remaining: 15m 18s
1372:	learn: 0.0129707	total: 2m 31s	remaining: 15m 50s
1413:	learn: 0.0112433	total: 2m 31s	remaining: 15m 18s
1313:	learn: 0.0142611	total: 2m 31s	remaining: 16m 40s
1437:	learn: 0.0116880	total: 2m 31s	remaining: 15m 1s
1414:	learn: 0.0131653	total: 2m 31s	remaining: 15m 17s
1373:	learn: 0.0129578	total: 2m 31s	remaining: 15m 50s
1414:	learn: 0.0112319	total: 2m 31s	remaining: 15m 18s
1438:	learn: 0.0116805	total: 2m 31s	remaining: 15m 1s
1314:	learn: 0.0142450	total: 2m 31s	remaining: 16m 40s
1415:	learn: 0.0131504	total: 2m 31s	remaining: 15m 17s
1374:	learn: 0.0129496	total: 2m 31s	remaining: 15m 50s
1415:	learn: 0.0112203	total: 2m 31s	remaining: 15m 18s
1439:	learn: 0.0116659	total: 2m 31s	remaining: 15m 1s
1315:	learn: 0.0142192	total: 2m 31s	remaining: 16m 40s
1416:	learn: 0.0131413	total: 2m 31s	remaining: 15m 17s
1375:	learn: 0.0129265	total: 2m 31s	remaining: 15m 50s
1416:	learn: 0.0112109	total: 2m 31s	remaining: 15m 18s
1440:	learn: 0.0116524	total: 2m 31s	remaining: 15m
1376:	learn: 0.0129082	total: 2m 31s	remaining: 15m 49s
1417:	learn: 0.0112021	total: 2m 31s	remaining: 15m 17s
1316:	learn: 0.0142031	total: 2m 31s	remaining: 16m 40s
1441:	learn: 0.0116414	total: 2m 31s	remaining: 15m
1417:	learn: 0.0131293	total: 2m 31s	remaining: 15m 17s
1377:	learn: 0.0129004	total: 2m 31s	remaining: 15m 49s
1418:	learn: 0.0111910	total: 2m 31s	remaining: 15m 17s
1418:	learn: 0.0131149	total: 2m 31s	remaining: 15m 17s
1317:	learn: 0.0141821	total: 2m 31s	remaining: 16m 40s
1442:	learn: 0.0116328	total: 2m 31s	remaining: 15m
1378:	learn: 0.0128824	total: 2m 31s	remaining: 15m 49s
1419:	learn: 0.0111780	total: 2m 31s	remaining: 15m 17s
1419:	learn: 0.0131062	total: 2m 31s	remaining: 15m 17s
1318:	learn: 0.0141550	total: 2m 31s	remaining: 16m 40s
1443:	learn: 0.0116193	total: 2m 32s	remaining: 15m
1379:	learn: 0.0128724	total: 2m 31s	remaining: 15m 49s
1420:	learn: 0.0111687	total: 2m 31s	remaining: 15m 17s
1420:	learn: 0.0130906	total: 2m 31s	remaining: 15m 17s
1319:	learn: 0.0141370	total: 2m 32s	remaining: 16m 39s
1380:	learn: 0.0128623	total: 2m 32s	remaining: 15m 49s
1444:	learn: 0.0116085	total: 2m 32s	remaining: 15m
1421:	learn: 0.0111583	total: 2m 32s	remaining: 15m 17s
1421:	learn: 0.0130765	total: 2m 32s	remaining: 15m 17s
1381:	learn: 0.0128523	total: 2m 32s	remaining: 15m 48s
1320:	learn: 0.0141226	total: 2m 32s	remaining: 16m 39s
1445:	learn: 0.0115936	total: 2m 32s	remaining: 15m
1422:	learn: 0.0111486	total: 2m 32s	remaining: 15m 17s
1382:	learn: 0.0128286	total: 2m 32s	remaining: 15m 48s
1422:	learn: 0.0130659	total: 2m 32s	remaining: 15m 17s
1446:	learn: 0.0115841	total: 2m 32s	remaining: 15m
1321:	learn: 0.0141140	total: 2m 32s	remaining: 16m 39s
1383:	learn: 0.0128093	total: 2m 32s	remaining: 15m 48s
1423:	learn: 0.0111433	total: 2m 32s	remaining: 15m 17s
1423:	learn: 0.0130524	total: 2m 32s	remaining: 15m 17s
1447:	learn: 0.0115704	total: 2m 32s	remaining: 15m
1424:	learn: 0.0111341	total: 2m 32s	remaining: 15m 16s
1384:	learn: 0.0127993	total: 2m 32s	remaining: 15m 47s
1322:	learn: 0.0140882	total: 2m 32s	remaining: 16m 39s
1424:	learn: 0.0130440	total: 2m 32s	remaining: 15m 16s
1448:	learn: 0.0115557	total: 2m 32s	remaining: 15m
1425:	learn: 0.0111267	total: 2m 32s	remaining: 15m 16s
1385:	learn: 0.0127886	total: 2m 32s	remaining: 15m 47s
1323:	learn: 0.0140622	total: 2m 32s	remaining: 16m 39s
1425:	learn: 0.0130297	total: 2m 32s	remaining: 15m 16s
1449:	learn: 0.0115422	total: 2m 32s	remaining: 15m
1386:	learn: 0.0127782	total: 2m 32s	remaining: 15m 47s
1426:	learn: 0.0111100	total: 2m 32s	remaining: 15m 16s
1324:	learn: 0.0140467	total: 2m 32s	remaining: 16m 39s
1426:	learn: 0.0130094	total: 2m 32s	remaining: 15m 16s
1387:	learn: 0.0127706	total: 2m 32s	remaining: 15m 47s
1450:	learn: 0.0115283	total: 2m 32s	remaining: 14m 59s
1427:	learn: 0.0110939	total: 2m 32s	remaining: 15m 16s
1325:	learn: 0.0140292	total: 2m 32s	remaining: 16m 39s
1427:	learn: 0.0129927	total: 2m 32s	remaining: 15m 16s
1388:	learn: 0.0127558	total: 2m 32s	remaining: 15m 47s
1451:	learn: 0.0115174	total: 2m 32s	remaining: 14m 59s
1428:	learn: 0.0110840	total: 2m 32s	remaining: 15m 16s
1428:	learn: 0.0129802	total: 2m 32s	remaining: 15m 16s
1326:	learn: 0.0140036	total: 2m 32s	remaining: 16m 39s
1452:	learn: 0.0115062	total: 2m 32s	remaining: 14m 59s
1389:	learn: 0.0127318	total: 2m 32s	remaining: 15m 47s
1429:	learn: 0.0110803	total: 2m 32s	remaining: 15m 16s
1429:	learn: 0.0129740	total: 2m 32s	remaining: 15m 15s
1453:	learn: 0.0114910	total: 2m 33s	remaining: 14m 59s
1430:	learn: 0.0129625	total: 2m 32s	remaining: 15m 15s
1327:	learn: 0.0139893	total: 2m 33s	remaining: 16m 39s
1390:	learn: 0.0127138	total: 2m 33s	remaining: 15m 46s
1430:	learn: 0.0110624	total: 2m 32s	remaining: 15m 16s
1454:	learn: 0.0114829	total: 2m 33s	remaining: 14m 59s
1431:	learn: 0.0129523	total: 2m 33s	remaining: 15m 15s
1455:	learn: 0.0114707	total: 2m 33s	remaining: 14m 58s
1431:	learn: 0.0110492	total: 2m 33s	remaining: 15m 15s
1391:	learn: 0.0126970	total: 2m 33s	remaining: 15m 46s
1328:	learn: 0.0139709	total: 2m 33s	remaining: 16m 39s
1432:	learn: 0.0129432	total: 2m 33s	remaining: 15m 15s
1456:	learn: 0.0114605	total: 2m 33s	remaining: 14m 58s
1432:	learn: 0.0110371	total: 2m 33s	remaining: 15m 15s
1392:	learn: 0.0126839	total: 2m 33s	remaining: 15m 46s
1329:	learn: 0.0139457	total: 2m 33s	remaining: 16m 39s
1433:	learn: 0.0129316	total: 2m 33s	remaining: 15m 15s
1457:	learn: 0.0114476	total: 2m 33s	remaining: 14m 58s
1393:	learn: 0.0126759	total: 2m 33s	remaining: 15m 46s
1433:	learn: 0.0110252	total: 2m 33s	remaining: 15m 15s
1394:	learn: 0.0126685	total: 2m 33s	remaining: 15m 46s
1330:	learn: 0.0139330	total: 2m 33s	remaining: 16m 39s
1434:	learn: 0.0110189	total: 2m 33s	remaining: 15m 15s
1434:	learn: 0.0129167	total: 2m 33s	remaining: 15m 15s
1458:	learn: 0.0114367	total: 2m 33s	remaining: 14m 58s

1395:	learn: 0.0126493	total: 2m 33s	remaining: 15m 45s
1435:	learn: 0.0110056	total: 2m 33s	remaining: 15m 15s
1459:	learn: 0.0114212	total: 2m 33s	remaining: 14m 58s
1331:	learn: 0.0139108	total: 2m 33s	remaining: 16m 39s
1435:	learn: 0.0128958	total: 2m 33s	remaining: 15m 15s
1436:	learn: 0.0109937	total: 2m 33s	remaining: 15m 14s
1396:	learn: 0.0126304	total: 2m 33s	remaining: 15m 45s
1460:	learn: 0.0114131	total: 2m 33s	remaining: 14m 58s
1332:	learn: 0.0138946	total: 2m 33s	remaining: 16m 38s
1397:	learn: 0.0126181	total: 2m 33s	remaining: 15m 45s
1437:	learn: 0.0109833	total: 2m 33s	remaining: 15m 14s
1436:	learn: 0.0128868	total: 2m 33s	remaining: 15m 15s
1461:	learn: 0.0114025	total: 2m 33s	remaining: 14m 57s
1333:	learn: 0.0138756	total: 2m 33s	remaining: 16m 38s
1438:	learn: 0.0109722	total: 2m 33s	remaining: 15m 14s
1398:	learn: 0.0126009	total: 2m 33s	remaining: 15m 45s
1462:	learn: 0.0113888	total: 2m 33s	remaining: 14m 57s
1437:	learn: 0.0128758	total: 2m 33s	remaining: 15m 15s
1334:	learn: 0.0138614	total: 2m 33s	remaining: 16m 38s
1439:	learn: 0.0109610	total: 2m 33s	remaining: 15m 14s
1399:	learn: 0.0125774	total: 2m 33s	remaining: 15m 45s
1463:	learn: 0.0113790	total: 2m 33s	remaining: 14m 57s
1438:	learn: 0.0128623	total: 2m 33s	remaining: 15m 15s
1440:	learn: 0.0109475	total: 2m 33s	remaining: 15m 14s
1400:	learn: 0.0125666	total: 2m 33s	remaining: 15m 44s
1335:	learn: 0.0138477	total: 2m 33s	remaining: 16m 38s
1464:	learn: 0.0113647	total: 2m 34s	remaining: 14m 57s
1441:	learn: 0.0109346	total: 2m 33s	remaining: 15m 13s
1439:	learn: 0.0128493	total: 2m 33s	remaining: 15m 15s
1336:	learn: 0.0138311	total: 2m 34s	remaining: 16m 38s
1465:	learn: 0.0113576	total: 2m 34s	remaining: 14m 57s
1401:	learn: 0.0125559	total: 2m 34s	remaining: 15m 44s
1442:	learn: 0.0109301	total: 2m 34s	remaining: 15m 13s
1440:	learn: 0.0128349	total: 2m 34s	remaining: 15m 14s
1466:	learn: 0.0113495	total: 2m 34s	remaining: 14m 57s
1337:	learn: 0.0138059	total: 2m 34s	remaining: 16m 38s
1402:	learn: 0.0125405	total: 2m 34s	remaining: 15m 44s
1443:	learn: 0.0109119	total: 2m 34s	remaining: 15m 13s
1467:	learn: 0.0113356	total: 2m 34s	remaining: 14m 56s
1441:	learn: 0.0128258	total: 2m 34s	remaining: 15m 14s
1338:	learn: 0.0137814	total: 2m 34s	remaining: 16m 37s
1403:	learn: 0.0125231	total: 2m 34s	remaining: 15m 44s
1442:	learn: 0.0128146	total: 2m 34s	remaining: 15m 14s
1444:	learn: 0.0109003	total: 2m 34s	remaining: 15m 13s
1468:	learn: 0.0113204	total: 2m 34s	remaining: 14m 56s
1339:	learn: 0.0137623	total: 2m 34s	remaining: 16m 37s
1404:	learn: 0.0125129	total: 2m 34s	remaining: 15m 44s
1443:	learn: 0.0128023	total: 2m 34s	remaining: 15m 14s
1469:	learn: 0.0113116	total: 2m 34s	remaining: 14m 56s
1445:	learn: 0.0108867	total: 2m 34s	remaining: 15m 13s
1444:	learn: 0.0127881	total: 2m 34s	remaining: 15m 14s
1405:	learn: 0.0124905	total: 2m 34s	remaining: 15m 44s
1470:	learn: 0.0112971	total: 2m 34s	remaining: 14m 56s
1340:	learn: 0.0137464	total: 2m 34s	remaining: 16m 37s
1446:	learn: 0.0108766	total: 2m 34s	remaining: 15m 13s
1445:	learn: 0.0127745	total: 2m 34s	remaining: 15m 13s
1406:	learn: 0.0124697	total: 2m 34s	remaining: 15m 44s
1341:	learn: 0.0137338	total: 2m 34s	remaining: 16m 37s
1471:	learn: 0.0112811	total: 2m 34s	remaining: 14m 56s
1447:	learn: 0.0108661	total: 2m 34s	remaining: 15m 13s
1446:	learn: 0.0127645	total: 2m 34s	remaining: 15m 13s
1407:	learn: 0.0124590	total: 2m 34s	remaining: 15m 43s
1342:	learn: 0.0137151	total: 2m 34s	remaining: 16m 37s
1448:	learn: 0.0108538	total: 2m 34s	remaining: 15m 12s
1447:	learn: 0.0127527	total: 2m 34s	remaining: 15m 13s
1472:	learn: 0.0112712	total: 2m 34s	remaining: 14m 56s
1408:	learn: 0.0124443	total: 2m 34s	remaining: 15m 43s
1343:	learn: 0.0136992	total: 2m 34s	remaining: 16m 37s
1449:	learn: 0.0108408	total: 2m 34s	remaining: 15m 12s
1448:	learn: 0.0127416	total: 2m 34s	remaining: 15m 13s
1409:	learn: 0.0124309	total: 2m 34s	remaining: 15m 43s
1473:	learn: 0.0112610	total: 2m 34s	remaining: 14m 56s
1344:	learn: 0.0136872	total: 2m 34s	remaining: 16m 36s
1450:	learn: 0.0108246	total: 2m 34s	remaining: 15m 12s
1449:	learn: 0.0127291	total: 2m 34s	remaining: 15m 13s
1410:	learn: 0.0124083	total: 2m 34s	remaining: 15m 43s
1474:	learn: 0.0112453	total: 2m 35s	remaining: 14m 56s
1345:	learn: 0.0136726	total: 2m 35s	remaining: 16m 36s
1451:	learn: 0.0108169	total: 2m 34s	remaining: 15m 12s
1450:	learn: 0.0127074	total: 2m 34s	remaining: 15m 13s
1411:	learn: 0.0123852	total: 2m 35s	remaining: 15m 43s
1475:	learn: 0.0112382	total: 2m 35s	remaining: 14m 55s
1452:	learn: 0.0108090	total: 2m 35s	remaining: 15m 12s
1346:	learn: 0.0136585	total: 2m 35s	remaining: 16m 36s
1476:	learn: 0.0112254	total: 2m 35s	remaining: 14m 55s
1453:	learn: 0.0107966	total: 2m 35s	remaining: 15m 11s
1451:	learn: 0.0126961	total: 2m 35s	remaining: 15m 13s
1412:	learn: 0.0123716	total: 2m 35s	remaining: 15m 43s
1347:	learn: 0.0136413	total: 2m 35s	remaining: 16m 36s
1477:	learn: 0.0112170	total: 2m 35s	remaining: 14m 55s
1454:	learn: 0.0107863	total: 2m 35s	remaining: 15m 11s
1452:	learn: 0.0126876	total: 2m 35s	remaining: 15m 12s
1413:	learn: 0.0123497	total: 2m 35s	remaining: 15m 43s
1478:	learn: 0.0112084	total: 2m 35s	remaining: 14m 55s
1348:	learn: 0.0136283	total: 2m 35s	remaining: 16m 36s
1455:	learn: 0.0107732	total: 2m 35s	remaining: 15m 11s
1453:	learn: 0.0126749	total: 2m 35s	remaining: 15m 12s
1479:	learn: 0.0111911	total: 2m 35s	remaining: 14m 55s
1414:	learn: 0.0123329	total: 2m 35s	remaining: 15m 43s
1456:	learn: 0.0107609	total: 2m 35s	remaining: 15m 11s
1349:	learn: 0.0136129	total: 2m 35s	remaining: 16m 36s
1454:	learn: 0.0126653	total: 2m 35s	remaining: 15m 12s
1480:	learn: 0.0111793	total: 2m 35s	remaining: 14m 54s
1457:	learn: 0.0107533	total: 2m 35s	remaining: 15m 10s
1415:	learn: 0.0123271	total: 2m 35s	remaining: 15m 42s
1350:	learn: 0.0135995	total: 2m 35s	remaining: 16m 36s
1455:	learn: 0.0126531	total: 2m 35s	remaining: 15m 12s
1481:	learn: 0.0111662	total: 2m 35s	remaining: 14m 54s
1458:	learn: 0.0107443	total: 2m 35s	remaining: 15m 10s
1416:	learn: 0.0123041	total: 2m 35s	remaining: 15m 42s
1351:	learn: 0.0135845	total: 2m 35s	remaining: 16m 35s
1456:	learn: 0.0126389	total: 2m 35s	remaining: 15m 12s
1417:	learn: 0.0122936	total: 2m 35s	remaining: 15m 42s
1482:	learn: 0.0111568	total: 2m 35s	remaining: 14m 54s
1459:	learn: 0.0107323	total: 2m 35s	remaining: 15m 10s
1352:	learn: 0.0135695	total: 2m 35s	remaining: 16m 35s
1457:	learn: 0.0126288	total: 2m 35s	remaining: 15m 12s
1418:	learn: 0.0122741	total: 2m 35s	remaining: 15m 42s
1483:	learn: 0.0111492	total: 2m 35s	remaining: 14m 54s
1353:	learn: 0.0135544	total: 2m 35s	remaining: 16m 35s
1460:	learn: 0.0107193	total: 2m 35s	remaining: 15m 10s
1458:	learn: 0.0126157	total: 2m 35s	remaining: 15m 12s
1419:	learn: 0.0122599	total: 2m 35s	remaining: 15m 41s
1484:	learn: 0.0111376	total: 2m 35s	remaining: 14m 54s
1354:	learn: 0.0135338	total: 2m 35s	remaining: 16m 35s
1459:	learn: 0.0126047	total: 2m 35s	remaining: 15m 11s
1461:	learn: 0.0107068	total: 2m 35s	remaining: 15m 10s
1420:	learn: 0.0122437	total: 2m 36s	remaining: 15m 41s
1485:	learn: 0.0111301	total: 2m 36s	remaining: 14m 54s
1355:	learn: 0.0135253	total: 2m 36s	remaining: 16m 34s
1462:	learn: 0.0106927	total: 2m 36s	remaining: 15m 10s
1460:	learn: 0.0125943	total: 2m 36s	remaining: 15m 11s
1486:	learn: 0.0111203	total: 2m 36s	remaining: 14m 53s
1356:	learn: 0.0135083	total: 2m 36s	remaining: 16m 34s
1421:	learn: 0.0122212	total: 2m 36s	remaining: 15m 41s
1463:	learn: 0.0106822	total: 2m 36s	remaining: 15m 10s
1487:	learn: 0.0111091	total: 2m 36s	remaining: 14m 53s
1461:	learn: 0.0125839	total: 2m 36s	remaining: 15m 11s
1357:	learn: 0.0134838	total: 2m 36s	remaining: 16m 34s
1464:	learn: 0.0106737	total: 2m 36s	remaining: 15m 10s
1422:	learn: 0.0122138	total: 2m 36s	remaining: 15m 41s
1462:	learn: 0.0125719	total: 2m 36s	remaining: 15m 11s
1488:	learn: 0.0110971	total: 2m 36s	remaining: 14m 53s
1358:	learn: 0.0134694	total: 2m 36s	remaining: 16m 34s
1423:	learn: 0.0121918	total: 2m 36s	remaining: 15m 41s
1465:	learn: 0.0106602	total: 2m 36s	remaining: 15m 9s
1463:	learn: 0.0125627	total: 2m 36s	remaining: 15m 11s
1489:	learn: 0.0110885	total: 2m 36s	remaining: 14m 53s
1424:	learn: 0.0121701	total: 2m 36s	remaining: 15m 41s
1466:	learn: 0.0106518	total: 2m 36s	remaining: 15m 9s
1359:	learn: 0.0134507	total: 2m 36s	remaining: 16m 34s
1490:	learn: 0.0110761	total: 2m 36s	remaining: 14m 53s
1464:	learn: 0.0125471	total: 2m 36s	remaining: 15m 11s
1360:	learn: 0.0134336	total: 2m 36s	remaining: 16m 33s
1467:	learn: 0.0106452	total: 2m 36s	remaining: 15m 9s
1425:	learn: 0.0121518	total: 2m 36s	remaining: 15m 41s
1465:	learn: 0.0125345	total: 2m 36s	remaining: 15m 11s
1491:	learn: 0.0110692	total: 2m 36s	remaining: 14m 53s
1361:	learn: 0.0134203	total: 2m 36s	remaining: 16m 33s
1426:	learn: 0.0121433	total: 2m 36s	remaining: 15m 41s
1468:	learn: 0.0106354	total: 2m 36s	remaining: 15m 9s
1492:	learn: 0.0110561	total: 2m 36s	remaining: 14m 53s
1466:	learn: 0.0125234	total: 2m 36s	remaining: 15m 11s
1362:	learn: 0.0134055	total: 2m 36s	remaining: 16m 33s
1427:	learn: 0.0121280	total: 2m 36s	remaining: 15m 40s
1469:	learn: 0.0106170	total: 2m 36s	remaining: 15m 9s
1493:	learn: 0.0110429	total: 2m 36s	remaining: 14m 52s
1467:	learn: 0.0125029	total: 2m 36s	remaining: 15m 11s
1363:	learn: 0.0133941	total: 2m 36s	remaining: 16m 33s
1494:	learn: 0.0110340	total: 2m 36s	remaining: 14m 52s
1470:	learn: 0.0106060	total: 2m 36s	remaining: 15m 9s
1428:	learn: 0.0121073	total: 2m 36s	remaining: 15m 40s
1468:	learn: 0.0124945	total: 2m 36s	remaining: 15m 10s
1364:	learn: 0.0133806	total: 2m 36s	remaining: 16m 33s
1495:	learn: 0.0110243	total: 2m 37s	remaining: 14m 52s
1429:	learn: 0.0120924	total: 2m 36s	remaining: 15m 40s
1471:	learn: 0.0105951	total: 2m 36s	remaining: 15m 9s
1469:	learn: 0.0124750	total: 2m 36s	remaining: 15m 10s
1365:	learn: 0.0133559	total: 2m 37s	remaining: 16m 32s
1430:	learn: 0.0120831	total: 2m 37s	remaining: 15m 40s
1496:	learn: 0.0110135	total: 2m 37s	remaining: 14m 52s
1472:	learn: 0.0105795	total: 2m 37s	remaining: 15m 9s
1470:	learn: 0.0124631	total: 2m 37s	remaining: 15m 10s
1497:	learn: 0.0109992	total: 2m 37s	remaining: 14m 52s
1431:	learn: 0.0120717	total: 2m 37s	remaining: 15m 40s
1366:	learn: 0.0133484	total: 2m 37s	remaining: 16m 32s
1473:	learn: 0.0105705	total: 2m 37s	remaining: 15m 9s
1471:	learn: 0.0124556	total: 2m 37s	remaining: 15m 10s
1498:	learn: 0.0109869	total: 2m 37s	remaining: 14m 52s
1432:	learn: 0.0120509	total: 2m 37s	remaining: 15m 40s
1367:	learn: 0.0133399	total: 2m 37s	remaining: 16m 32s
1499:	learn: 0.0109806	total: 2m 37s	remaining: 14m 51s
1474:	learn: 0.0105648	total: 2m 37s	remaining: 15m 8s
1472:	learn: 0.0124491	total: 2m 37s	remaining: 15m 10s
1433:	learn: 0.0120417	total: 2m 37s	remaining: 15m 39s
1500:	learn: 0.0109689	total: 2m 37s	remaining: 14m 51s
1368:	learn: 0.0133225	total: 2m 37s	remaining: 16m 32s
1473:	learn: 0.0124358	total: 2m 37s	remaining: 15m 10s
1475:	learn: 0.0105506	total: 2m 37s	remaining: 15m 9s
1434:	learn: 0.0120200	total: 2m 37s	remaining: 15m 39s
1501:	learn: 0.0109580	total: 2m 37s	remaining: 14m 51s
1369:	learn: 0.0133070	total: 2m 37s	remaining: 16m 32s
1474:	learn: 0.0124216	total: 2m 37s	remaining: 15m 10s
1502:	learn: 0.0109482	total: 2m 37s	remaining: 14m 51s
1435:	learn: 0.0120044	total: 2m 37s	remaining: 15m 39s
1476:	learn: 0.0105401	total: 2m 37s	remaining: 15m 8s
1503:	learn: 0.0109415	total: 2m 37s	remaining: 14m 50s
1370:	learn: 0.0132854	total: 2m 37s	remaining: 16m 32s
1475:	learn: 0.0124088	total: 2m 37s	remaining: 15m 9s
1477:	learn: 0.0105288	total: 2m 37s	remaining: 15m 8s
1436:	learn: 0.0119853	total: 2m 37s	remaining: 15m 39s
1504:	learn: 0.0109275	total: 2m 37s	remaining: 14m 50s
1371:	learn: 0.0132671	total: 2m 37s	remaining: 16m 31s
1476:	learn: 0.0123972	total: 2m 37s	remaining: 15m 9s
1478:	learn: 0.0105169	total: 2m 37s	remaining: 15m 8s
1437:	learn: 0.0119734	total: 2m 37s	remaining: 15m 39s
1505:	learn: 0.0109103	total: 2m 37s	remaining: 14m 50s
1372:	learn: 0.0132554	total: 2m 37s	remaining: 16m 31s
1477:	learn: 0.0123844	total: 2m 37s	remaining: 15m 9s
1438:	learn: 0.0119587	total: 2m 37s	remaining: 15m 39s
1479:	learn: 0.0105035	total: 2m 37s	remaining: 15m 8s
1506:	learn: 0.0108999	total: 2m 37s	remaining: 14m 50s
1373:	learn: 0.0132319	total: 2m 37s	remaining: 16m 31s
1478:	learn: 0.0123653	total: 2m 37s	remaining: 15m 9s
1480:	learn: 0.0104911	total: 2m 37s	remaining: 15m 8s
1439:	learn: 0.0119449	total: 2m 37s	remaining: 15m 39s
1374:	learn: 0.0132150	total: 2m 38s	remaining: 16m 31s
1507:	learn: 0.0108851	total: 2m 38s	remaining: 14m 50s
1479:	learn: 0.0123568	total: 2m 37s	remaining: 15m 9s
1481:	learn: 0.0104781	total: 2m 38s	remaining: 15m 8s
1440:	learn: 0.0119243	total: 2m 38s	remaining: 15m 38s
1508:	learn: 0.0108747	total: 2m 38s	remaining: 14m 50s
1375:	learn: 0.0132010	total: 2m 38s	remaining: 16m 31s
1480:	learn: 0.0123435	total: 2m 38s	remaining: 15m 9s
1482:	learn: 0.0104658	total: 2m 38s	remaining: 15m 8s
1509:	learn: 0.0108615	total: 2m 38s	remaining: 14m 49s
1441:	learn: 0.0119177	total: 2m 38s	remaining: 15m 38s
1376:	learn: 0.0131808	total: 2m 38s	remaining: 16m 30s
1481:	learn: 0.0123300	total: 2m 38s	remaining: 15m 9s
1483:	learn: 0.0104526	total: 2m 38s	remaining: 15m 7s
1510:	learn: 0.0108549	total: 2m 38s	remaining: 14m 49s
1482:	learn: 0.0123110	total: 2m 38s	remaining: 15m 8s
1377:	learn: 0.0131725	total: 2m 38s	remaining: 16m 30s
1511:	learn: 0.0108459	total: 2m 38s	remaining: 14m 49s
1442:	learn: 0.0119045	total: 2m 38s	remaining: 15m 39s
1484:	learn: 0.0104461	total: 2m 38s	remaining: 15m 7s
1483:	learn: 0.0122918	total: 2m 38s	remaining: 15m 8s
1512:	learn: 0.0108363	total: 2m 38s	remaining: 14m 49s
1443:	learn: 0.0118891	total: 2m 38s	remaining: 15m 38s
1378:	learn: 0.0131586	total: 2m 38s	remaining: 16m 30s
1485:	learn: 0.0104274	total: 2m 38s	remaining: 15m 7s
1444:	learn: 0.0118739	total: 2m 38s	remaining: 15m 38s
1484:	learn: 0.0122760	total: 2m 38s	remaining: 15m 8s
1513:	learn: 0.0108288	total: 2m 38s	remaining: 14m 49s
1379:	learn: 0.0131381	total: 2m 38s	remaining: 16m 30s
1486:	learn: 0.0104186	total: 2m 38s	remaining: 15m 7s
1445:	learn: 0.0118565	total: 2m 38s	remaining: 15m 38s
1485:	learn: 0.0122630	total: 2m 38s	remaining: 15m 8s
1380:	learn: 0.0131192	total: 2m 38s	remaining: 16m 30s
1514:	learn: 0.0108183	total: 2m 38s	remaining: 14m 49s
1487:	learn: 0.0104104	total: 2m 38s	remaining: 15m 7s
1446:	learn: 0.0118493	total: 2m 38s	remaining: 15m 38s
1486:	learn: 0.0122528	total: 2m 38s	remaining: 15m 8s
1515:	learn: 0.0108067	total: 2m 38s	remaining: 14m 48s
1447:	learn: 0.0118308	total: 2m 38s	remaining: 15m 37s
1488:	learn: 0.0104058	total: 2m 38s	remaining: 15m 7s
1381:	learn: 0.0131067	total: 2m 38s	remaining: 16m 30s
1516:	learn: 0.0107922	total: 2m 38s	remaining: 14m 48s
1487:	learn: 0.0122436	total: 2m 38s	remaining: 15m 8s
1448:	learn: 0.0118241	total: 2m 38s	remaining: 15m 37s
1489:	learn: 0.0103949	total: 2m 38s	remaining: 15m 7s
1488:	learn: 0.0122268	total: 2m 38s	remaining: 15m 7s
1517:	learn: 0.0107786	total: 2m 38s	remaining: 14m 48s
1382:	learn: 0.0130943	total: 2m 38s	remaining: 16m 30s
1490:	learn: 0.0103847	total: 2m 38s	remaining: 15m 7s
1449:	learn: 0.0118069	total: 2m 38s	remaining: 15m 37s
1489:	learn: 0.0122163	total: 2m 38s	remaining: 15m 7s
1518:	learn: 0.0107712	total: 2m 39s	remaining: 14m 48s
1491:	learn: 0.0103674	total: 2m 39s	remaining: 15m 6s
1383:	learn: 0.0130864	total: 2m 39s	remaining: 16m 30s
1450:	learn: 0.0117927	total: 2m 39s	remaining: 15m 37s
1490:	learn: 0.0122039	total: 2m 39s	remaining: 15m 7s
1519:	learn: 0.0107609	total: 2m 39s	remaining: 14m 48s
1492:	learn: 0.0103612	total: 2m 39s	remaining: 15m 6s
1451:	learn: 0.0117746	total: 2m 39s	remaining: 15m 37s
1384:	learn: 0.0130733	total: 2m 39s	remaining: 16m 30s
1491:	learn: 0.0121854	total: 2m 39s	remaining: 15m 7s
1520:	learn: 0.0107557	total: 2m 39s	remaining: 14m 47s
1452:	learn: 0.0117547	total: 2m 39s	remaining: 15m 36s
1493:	learn: 0.0103485	total: 2m 39s	remaining: 15m 6s
1385:	learn: 0.0130567	total: 2m 39s	remaining: 16m 30s
1521:	learn: 0.0107480	total: 2m 39s	remaining: 14m 47s
1492:	learn: 0.0121695	total: 2m 39s	remaining: 15m 7s

1494:	learn: 0.0103354	total: 2m 39s	remaining: 15m 6s
1386:	learn: 0.0130387	total: 2m 39s	remaining: 16m 29s
1453:	learn: 0.0117400	total: 2m 39s	remaining: 15m 36s
1522:	learn: 0.0107378	total: 2m 39s	remaining: 14m 47s
1493:	learn: 0.0121516	total: 2m 39s	remaining: 15m 7s
1454:	learn: 0.0117214	total: 2m 39s	remaining: 15m 36s
1495:	learn: 0.0103262	total: 2m 39s	remaining: 15m 6s
1387:	learn: 0.0130219	total: 2m 39s	remaining: 16m 29s
1523:	learn: 0.0107284	total: 2m 39s	remaining: 14m 47s
1494:	learn: 0.0121439	total: 2m 39s	remaining: 15m 7s
1496:	learn: 0.0103173	total: 2m 39s	remaining: 15m 6s
1455:	learn: 0.0117088	total: 2m 39s	remaining: 15m 36s
1388:	learn: 0.0130047	total: 2m 39s	remaining: 16m 29s
1524:	learn: 0.0107210	total: 2m 39s	remaining: 14m 47s
1497:	learn: 0.0103097	total: 2m 39s	remaining: 15m 5s
1495:	learn: 0.0121318	total: 2m 39s	remaining: 15m 7s
1456:	learn: 0.0116922	total: 2m 39s	remaining: 15m 36s
1389:	learn: 0.0129906	total: 2m 39s	remaining: 16m 29s
1496:	learn: 0.0121241	total: 2m 39s	remaining: 15m 6s
1525:	learn: 0.0107124	total: 2m 39s	remaining: 14m 47s
1498:	learn: 0.0102980	total: 2m 39s	remaining: 15m 5s
1457:	learn: 0.0116797	total: 2m 39s	remaining: 15m 36s
1390:	learn: 0.0129760	total: 2m 39s	remaining: 16m 29s
1499:	learn: 0.0102876	total: 2m 39s	remaining: 15m 5s
1526:	learn: 0.0107037	total: 2m 39s	remaining: 14m 47s
1497:	learn: 0.0121114	total: 2m 39s	remaining: 15m 6s
1500:	learn: 0.0102814	total: 2m 39s	remaining: 15m 5s
1458:	learn: 0.0116601	total: 2m 39s	remaining: 15m 36s
1391:	learn: 0.0129606	total: 2m 39s	remaining: 16m 29s
1498:	learn: 0.0121034	total: 2m 39s	remaining: 15m 6s
1527:	learn: 0.0106897	total: 2m 40s	remaining: 14m 47s
1392:	learn: 0.0129521	total: 2m 40s	remaining: 16m 28s
1459:	learn: 0.0116434	total: 2m 40s	remaining: 15m 35s
1499:	learn: 0.0120913	total: 2m 39s	remaining: 15m 6s
1501:	learn: 0.0102725	total: 2m 39s	remaining: 15m 5s
1528:	learn: 0.0106808	total: 2m 40s	remaining: 14m 47s
1500:	learn: 0.0120784	total: 2m 40s	remaining: 15m 6s
1460:	learn: 0.0116346	total: 2m 40s	remaining: 15m 35s
1393:	learn: 0.0129356	total: 2m 40s	remaining: 16m 28s
1502:	learn: 0.0102616	total: 2m 40s	remaining: 15m 5s
1501:	learn: 0.0120659	total: 2m 40s	remaining: 15m 5s
1529:	learn: 0.0106684	total: 2m 40s	remaining: 14m 47s
1461:	learn: 0.0116220	total: 2m 40s	remaining: 15m 35s
1503:	learn: 0.0102459	total: 2m 40s	remaining: 15m 4s
1394:	learn: 0.0129208	total: 2m 40s	remaining: 16m 28s
1502:	learn: 0.0120571	total: 2m 40s	remaining: 15m 5s
1530:	learn: 0.0106580	total: 2m 40s	remaining: 14m 46s
1462:	learn: 0.0116057	total: 2m 40s	remaining: 15m 35s
1503:	learn: 0.0120448	total: 2m 40s	remaining: 15m 5s
1504:	learn: 0.0102346	total: 2m 40s	remaining: 15m 4s
1395:	learn: 0.0128985	total: 2m 40s	remaining: 16m 28s
1531:	learn: 0.0106448	total: 2m 40s	remaining: 14m 46s
1463:	learn: 0.0115936	total: 2m 40s	remaining: 15m 35s
1504:	learn: 0.0120339	total: 2m 40s	remaining: 15m 5s
1505:	learn: 0.0102192	total: 2m 40s	remaining: 15m 4s
1396:	learn: 0.0128915	total: 2m 40s	remaining: 16m 28s
1532:	learn: 0.0106340	total: 2m 40s	remaining: 14m 46s
1464:	learn: 0.0115826	total: 2m 40s	remaining: 15m 35s
1506:	learn: 0.0102095	total: 2m 40s	remaining: 15m 4s
1505:	learn: 0.0120233	total: 2m 40s	remaining: 15m 5s
1397:	learn: 0.0128769	total: 2m 40s	remaining: 16m 28s
1533:	learn: 0.0106256	total: 2m 40s	remaining: 14m 46s
1465:	learn: 0.0115730	total: 2m 40s	remaining: 15m 35s
1506:	learn: 0.0120053	total: 2m 40s	remaining: 15m 4s
1507:	learn: 0.0101943	total: 2m 40s	remaining: 15m 4s
1466:	learn: 0.0115566	total: 2m 40s	remaining: 15m 34s
1398:	learn: 0.0128661	total: 2m 40s	remaining: 16m 28s
1534:	learn: 0.0106160	total: 2m 40s	remaining: 14m 46s
1508:	learn: 0.0101840	total: 2m 40s	remaining: 15m 4s
1507:	learn: 0.0119911	total: 2m 40s	remaining: 15m 4s
1467:	learn: 0.0115418	total: 2m 40s	remaining: 15m 34s
1509:	learn: 0.0101755	total: 2m 40s	remaining: 15m 3s
1535:	learn: 0.0106074	total: 2m 40s	remaining: 14m 46s
1508:	learn: 0.0119803	total: 2m 40s	remaining: 15m 4s
1399:	learn: 0.0128522	total: 2m 40s	remaining: 16m 28s
1510:	learn: 0.0101653	total: 2m 40s	remaining: 15m 3s
1468:	learn: 0.0115365	total: 2m 40s	remaining: 15m 34s
1536:	learn: 0.0105918	total: 2m 40s	remaining: 14m 46s
1511:	learn: 0.0101524	total: 2m 40s	remaining: 15m 3s
1509:	learn: 0.0119627	total: 2m 40s	remaining: 15m 4s
1400:	learn: 0.0128435	total: 2m 40s	remaining: 16m 28s
1469:	learn: 0.0115205	total: 2m 40s	remaining: 15m 34s
1537:	learn: 0.0105820	total: 2m 41s	remaining: 14m 46s
1510:	learn: 0.0119532	total: 2m 40s	remaining: 15m 4s
1470:	learn: 0.0115067	total: 2m 41s	remaining: 15m 33s
1512:	learn: 0.0101424	total: 2m 41s	remaining: 15m 3s
1538:	learn: 0.0105719	total: 2m 41s	remaining: 14m 45s
1401:	learn: 0.0128273	total: 2m 41s	remaining: 16m 28s
1511:	learn: 0.0119411	total: 2m 41s	remaining: 15m 4s
1402:	learn: 0.0128153	total: 2m 41s	remaining: 16m 27s
1471:	learn: 0.0114934	total: 2m 41s	remaining: 15m 33s
1513:	learn: 0.0101337	total: 2m 41s	remaining: 15m 3s
1539:	learn: 0.0105601	total: 2m 41s	remaining: 14m 45s
1514:	learn: 0.0101242	total: 2m 41s	remaining: 15m 2s
1472:	learn: 0.0114773	total: 2m 41s	remaining: 15m 33s
1512:	learn: 0.0119285	total: 2m 41s	remaining: 15m 4s
1403:	learn: 0.0127993	total: 2m 41s	remaining: 16m 27s
1540:	learn: 0.0105466	total: 2m 41s	remaining: 14m 45s
1515:	learn: 0.0101139	total: 2m 41s	remaining: 15m 2s
1513:	learn: 0.0119152	total: 2m 41s	remaining: 15m 4s
1473:	learn: 0.0114654	total: 2m 41s	remaining: 15m 33s
1541:	learn: 0.0105404	total: 2m 41s	remaining: 14m 45s
1404:	learn: 0.0127859	total: 2m 41s	remaining: 16m 27s
1516:	learn: 0.0100984	total: 2m 41s	remaining: 15m 2s
1514:	learn: 0.0119041	total: 2m 41s	remaining: 15m 3s
1474:	learn: 0.0114463	total: 2m 41s	remaining: 15m 33s
1542:	learn: 0.0105289	total: 2m 41s	remaining: 14m 45s
1405:	learn: 0.0127709	total: 2m 41s	remaining: 16m 27s
1517:	learn: 0.0100836	total: 2m 41s	remaining: 15m 2s
1475:	learn: 0.0114245	total: 2m 41s	remaining: 15m 33s
1543:	learn: 0.0105191	total: 2m 41s	remaining: 14m 45s
1515:	learn: 0.0118929	total: 2m 41s	remaining: 15m 3s
1518:	learn: 0.0100724	total: 2m 41s	remaining: 15m 2s
1406:	learn: 0.0127552	total: 2m 41s	remaining: 16m 27s
1476:	learn: 0.0114096	total: 2m 41s	remaining: 15m 32s
1516:	learn: 0.0118775	total: 2m 41s	remaining: 15m 3s
1544:	learn: 0.0105118	total: 2m 41s	remaining: 14m 45s
1519:	learn: 0.0100651	total: 2m 41s	remaining: 15m 1s
1407:	learn: 0.0127405	total: 2m 41s	remaining: 16m 27s
1477:	learn: 0.0113940	total: 2m 41s	remaining: 15m 32s
1545:	learn: 0.0105036	total: 2m 41s	remaining: 14m 45s
1520:	learn: 0.0100515	total: 2m 41s	remaining: 15m 1s
1517:	learn: 0.0118656	total: 2m 41s	remaining: 15m 3s
1408:	learn: 0.0127250	total: 2m 41s	remaining: 16m 27s
1521:	learn: 0.0100419	total: 2m 41s	remaining: 15m 1s
1546:	learn: 0.0104907	total: 2m 41s	remaining: 14m 44s
1478:	learn: 0.0113799	total: 2m 41s	remaining: 15m 32s
1518:	learn: 0.0118545	total: 2m 41s	remaining: 15m 3s
1409:	learn: 0.0127186	total: 2m 41s	remaining: 16m 26s
1547:	learn: 0.0104836	total: 2m 42s	remaining: 14m 44s
1479:	learn: 0.0113646	total: 2m 41s	remaining: 15m 32s
1522:	learn: 0.0100337	total: 2m 41s	remaining: 15m 1s
1519:	learn: 0.0118397	total: 2m 41s	remaining: 15m 3s
1548:	learn: 0.0104754	total: 2m 42s	remaining: 14m 44s
1520:	learn: 0.0118247	total: 2m 42s	remaining: 15m 3s
1410:	learn: 0.0127034	total: 2m 42s	remaining: 16m 26s
1480:	learn: 0.0113465	total: 2m 42s	remaining: 15m 32s
1523:	learn: 0.0100244	total: 2m 42s	remaining: 15m 1s
1549:	learn: 0.0104625	total: 2m 42s	remaining: 14m 44s
1521:	learn: 0.0118180	total: 2m 42s	remaining: 15m 3s
1411:	learn: 0.0126969	total: 2m 42s	remaining: 16m 26s
1481:	learn: 0.0113321	total: 2m 42s	remaining: 15m 32s
1524:	learn: 0.0100173	total: 2m 42s	remaining: 15m 1s
1522:	learn: 0.0118034	total: 2m 42s	remaining: 15m 2s
1550:	learn: 0.0104555	total: 2m 42s	remaining: 14m 44s
1482:	learn: 0.0113179	total: 2m 42s	remaining: 15m 32s
1525:	learn: 0.0100089	total: 2m 42s	remaining: 15m 1s
1412:	learn: 0.0126856	total: 2m 42s	remaining: 16m 26s
1523:	learn: 0.0117926	total: 2m 42s	remaining: 15m 2s
1551:	learn: 0.0104488	total: 2m 42s	remaining: 14m 44s
1483:	learn: 0.0113126	total: 2m 42s	remaining: 15m 31s
1526:	learn: 0.0099976	total: 2m 42s	remaining: 15m
1413:	learn: 0.0126684	total: 2m 42s	remaining: 16m 26s
1484:	learn: 0.0113024	total: 2m 42s	remaining: 15m 31s
1524:	learn: 0.0117810	total: 2m 42s	remaining: 15m 2s
1552:	learn: 0.0104408	total: 2m 42s	remaining: 14m 44s
1527:	learn: 0.0099944	total: 2m 42s	remaining: 15m
1485:	learn: 0.0112891	total: 2m 42s	remaining: 15m 31s
1414:	learn: 0.0126554	total: 2m 42s	remaining: 16m 26s
1525:	learn: 0.0117630	total: 2m 42s	remaining: 15m 2s
1528:	learn: 0.0099861	total: 2m 42s	remaining: 15m
1486:	learn: 0.0112793	total: 2m 42s	remaining: 15m 31s
1553:	learn: 0.0104292	total: 2m 42s	remaining: 14m 44s
1415:	learn: 0.0126464	total: 2m 42s	remaining: 16m 26s
1526:	learn: 0.0117561	total: 2m 42s	remaining: 15m 2s
1487:	learn: 0.0112678	total: 2m 42s	remaining: 15m 30s
1554:	learn: 0.0104203	total: 2m 42s	remaining: 14m 44s
1529:	learn: 0.0099781	total: 2m 42s	remaining: 15m
1527:	learn: 0.0117477	total: 2m 42s	remaining: 15m 2s
1416:	learn: 0.0126260	total: 2m 42s	remaining: 16m 26s
1555:	learn: 0.0104097	total: 2m 42s	remaining: 14m 43s
1488:	learn: 0.0112519	total: 2m 42s	remaining: 15m 30s
1528:	learn: 0.0117334	total: 2m 42s	remaining: 15m 1s
1530:	learn: 0.0099695	total: 2m 42s	remaining: 15m
1489:	learn: 0.0112384	total: 2m 42s	remaining: 15m 30s
1417:	learn: 0.0126093	total: 2m 42s	remaining: 16m 26s
1556:	learn: 0.0103956	total: 2m 42s	remaining: 14m 43s
1531:	learn: 0.0099573	total: 2m 42s	remaining: 15m
1529:	learn: 0.0117217	total: 2m 42s	remaining: 15m 1s
1490:	learn: 0.0112253	total: 2m 42s	remaining: 15m 30s
1557:	learn: 0.0103826	total: 2m 43s	remaining: 14m 43s
1418:	learn: 0.0125938	total: 2m 43s	remaining: 16m 25s
1532:	learn: 0.0099490	total: 2m 42s	remaining: 15m
1530:	learn: 0.0117111	total: 2m 42s	remaining: 15m 1s
1491:	learn: 0.0112173	total: 2m 43s	remaining: 15m 29s
1558:	learn: 0.0103770	total: 2m 43s	remaining: 14m 43s
1419:	learn: 0.0125826	total: 2m 43s	remaining: 16m 25s
1533:	learn: 0.0099417	total: 2m 43s	remaining: 15m
1531:	learn: 0.0117009	total: 2m 43s	remaining: 15m 1s
1559:	learn: 0.0103652	total: 2m 43s	remaining: 14m 43s
1492:	learn: 0.0112040	total: 2m 43s	remaining: 15m 29s
1420:	learn: 0.0125669	total: 2m 43s	remaining: 16m 25s
1534:	learn: 0.0099309	total: 2m 43s	remaining: 14m 59s
1560:	learn: 0.0103525	total: 2m 43s	remaining: 14m 42s
1532:	learn: 0.0116943	total: 2m 43s	remaining: 15m 1s
1493:	learn: 0.0111909	total: 2m 43s	remaining: 15m 29s
1535:	learn: 0.0099205	total: 2m 43s	remaining: 14m 59s
1561:	learn: 0.0103448	total: 2m 43s	remaining: 14m 42s
1421:	learn: 0.0125554	total: 2m 43s	remaining: 16m 25s
1533:	learn: 0.0116842	total: 2m 43s	remaining: 15m 1s
1494:	learn: 0.0111802	total: 2m 43s	remaining: 15m 29s
1536:	learn: 0.0099109	total: 2m 43s	remaining: 14m 59s
1562:	learn: 0.0103354	total: 2m 43s	remaining: 14m 42s
1422:	learn: 0.0125424	total: 2m 43s	remaining: 16m 25s
1534:	learn: 0.0116777	total: 2m 43s	remaining: 15m 1s
1495:	learn: 0.0111676	total: 2m 43s	remaining: 15m 29s
1537:	learn: 0.0099027	total: 2m 43s	remaining: 14m 59s
1563:	learn: 0.0103261	total: 2m 43s	remaining: 14m 42s
1535:	learn: 0.0116722	total: 2m 43s	remaining: 15m
1496:	learn: 0.0111586	total: 2m 43s	remaining: 15m 29s
1423:	learn: 0.0125296	total: 2m 43s	remaining: 16m 25s
1538:	learn: 0.0098951	total: 2m 43s	remaining: 14m 59s
1536:	learn: 0.0116646	total: 2m 43s	remaining: 15m
1564:	learn: 0.0103163	total: 2m 43s	remaining: 14m 42s
1539:	learn: 0.0098846	total: 2m 43s	remaining: 14m 58s
1424:	learn: 0.0125086	total: 2m 43s	remaining: 16m 25s
1497:	learn: 0.0111407	total: 2m 43s	remaining: 15m 29s
1537:	learn: 0.0116579	total: 2m 43s	remaining: 15m
1540:	learn: 0.0098755	total: 2m 43s	remaining: 14m 58s
1565:	learn: 0.0103042	total: 2m 43s	remaining: 14m 42s
1425:	learn: 0.0124980	total: 2m 43s	remaining: 16m 25s
1498:	learn: 0.0111218	total: 2m 43s	remaining: 15m 29s
1538:	learn: 0.0116423	total: 2m 43s	remaining: 15m
1541:	learn: 0.0098674	total: 2m 43s	remaining: 14m 58s
1566:	learn: 0.0102917	total: 2m 43s	remaining: 14m 42s
1426:	learn: 0.0124839	total: 2m 43s	remaining: 16m 24s
1539:	learn: 0.0116318	total: 2m 43s	remaining: 15m
1542:	learn: 0.0098555	total: 2m 43s	remaining: 14m 58s
1499:	learn: 0.0111038	total: 2m 43s	remaining: 15m 29s
1567:	learn: 0.0102846	total: 2m 44s	remaining: 14m 42s
1427:	learn: 0.0124686	total: 2m 44s	remaining: 16m 24s
1540:	learn: 0.0116173	total: 2m 43s	remaining: 14m 59s
1500:	learn: 0.0110924	total: 2m 44s	remaining: 15m 28s
1543:	learn: 0.0098480	total: 2m 44s	remaining: 14m 58s
1568:	learn: 0.0102721	total: 2m 44s	remaining: 14m 42s
1428:	learn: 0.0124577	total: 2m 44s	remaining: 16m 24s
1541:	learn: 0.0116067	total: 2m 44s	remaining: 14m 59s
1501:	learn: 0.0110787	total: 2m 44s	remaining: 15m 28s
1569:	learn: 0.0102599	total: 2m 44s	remaining: 14m 41s
1544:	learn: 0.0098382	total: 2m 44s	remaining: 14m 58s
1429:	learn: 0.0124331	total: 2m 44s	remaining: 16m 24s
1542:	learn: 0.0116015	total: 2m 44s	remaining: 14m 59s
1545:	learn: 0.0098290	total: 2m 44s	remaining: 14m 57s
1570:	learn: 0.0102514	total: 2m 44s	remaining: 14m 41s
1502:	learn: 0.0110713	total: 2m 44s	remaining: 15m 28s
1543:	learn: 0.0115902	total: 2m 44s	remaining: 14m 59s
1430:	learn: 0.0124123	total: 2m 44s	remaining: 16m 24s
1546:	learn: 0.0098208	total: 2m 44s	remaining: 14m 57s
1571:	learn: 0.0102420	total: 2m 44s	remaining: 14m 41s
1544:	learn: 0.0115793	total: 2m 44s	remaining: 14m 59s
1431:	learn: 0.0123975	total: 2m 44s	remaining: 16m 23s
1547:	learn: 0.0098100	total: 2m 44s	remaining: 14m 57s
1503:	learn: 0.0110574	total: 2m 44s	remaining: 15m 28s
1572:	learn: 0.0102307	total: 2m 44s	remaining: 14m 41s
1545:	learn: 0.0115681	total: 2m 44s	remaining: 14m 59s
1548:	learn: 0.0098029	total: 2m 44s	remaining: 14m 57s
1432:	learn: 0.0123791	total: 2m 44s	remaining: 16m 23s
1504:	learn: 0.0110444	total: 2m 44s	remaining: 15m 28s
1573:	learn: 0.0102229	total: 2m 44s	remaining: 14m 41s
1549:	learn: 0.0097942	total: 2m 44s	remaining: 14m 57s
1546:	learn: 0.0115608	total: 2m 44s	remaining: 14m 58s
1433:	learn: 0.0123651	total: 2m 44s	remaining: 16m 23s
1574:	learn: 0.0102143	total: 2m 44s	remaining: 14m 41s
1505:	learn: 0.0110339	total: 2m 44s	remaining: 15m 28s
1550:	learn: 0.0097907	total: 2m 44s	remaining: 14m 56s
1547:	learn: 0.0115494	total: 2m 44s	remaining: 14m 58s
1434:	learn: 0.0123487	total: 2m 44s	remaining: 16m 23s
1575:	learn: 0.0102040	total: 2m 44s	remaining: 14m 40s
1506:	learn: 0.0110168	total: 2m 44s	remaining: 15m 28s
1576:	learn: 0.0101948	total: 2m 44s	remaining: 14m 40s
1551:	learn: 0.0097798	total: 2m 44s	remaining: 14m 56s
1435:	learn: 0.0123332	total: 2m 44s	remaining: 16m 23s
1548:	learn: 0.0115396	total: 2m 44s	remaining: 14m 58s
1507:	learn: 0.0110010	total: 2m 44s	remaining: 15m 28s
1549:	learn: 0.0115286	total: 2m 44s	remaining: 14m 58s
1552:	learn: 0.0097739	total: 2m 44s	remaining: 14m 56s
1577:	learn: 0.0101889	total: 2m 44s	remaining: 14m 40s
1436:	learn: 0.0123225	total: 2m 44s	remaining: 16m 23s
1508:	learn: 0.0109900	total: 2m 44s	remaining: 15m 28s
1550:	learn: 0.0115169	total: 2m 44s	remaining: 14m 58s
1553:	learn: 0.0097595	total: 2m 44s	remaining: 14m 56s
1578:	learn: 0.0101788	total: 2m 45s	remaining: 14m 40s
1437:	learn: 0.0123073	total: 2m 45s	remaining: 16m 22s
1554:	learn: 0.0097528	total: 2m 45s	remaining: 14m 56s
1551:	learn: 0.0115081	total: 2m 45s	remaining: 14m 58s
1509:	learn: 0.0109791	total: 2m 45s	remaining: 15m 28s
1438:	learn: 0.0122968	total: 2m 45s	remaining: 16m 22s
1579:	learn: 0.0101734	total: 2m 45s	remaining: 14m 40s
1555:	learn: 0.0097376	total: 2m 45s	remaining: 14m 56s
1552:	learn: 0.0114902	total: 2m 45s	remaining: 14m 58s
1510:	learn: 0.0109652	total: 2m 45s	remaining: 15m 28s
1580:	learn: 0.0101630	total: 2m 45s	remaining: 14m 40s
1439:	learn: 0.0122774	total: 2m 45s	remaining: 16m 22s
1556:	learn: 0.0097270	total: 2m 45s	remaining: 14m 55s

1553:	learn: 0.0114774	total: 2m 45s	remaining: 14m 58s
1440:	learn: 0.0122604	total: 2m 45s	remaining: 16m 22s
1581:	learn: 0.0101549	total: 2m 45s	remaining: 14m 40s
1512:	learn: 0.0109378	total: 2m 45s	remaining: 15m 27s
1554:	learn: 0.0114658	total: 2m 45s	remaining: 14m 57s
1557:	learn: 0.0097145	total: 2m 45s	remaining: 14m 55s
1582:	learn: 0.0101431	total: 2m 45s	remaining: 14m 40s
1555:	learn: 0.0114561	total: 2m 45s	remaining: 14m 57s
1441:	learn: 0.0122402	total: 2m 45s	remaining: 16m 22s
1558:	learn: 0.0097031	total: 2m 45s	remaining: 14m 55s
1513:	learn: 0.0109305	total: 2m 45s	remaining: 15m 27s
1583:	learn: 0.0101288	total: 2m 45s	remaining: 14m 39s
1559:	learn: 0.0096949	total: 2m 45s	remaining: 14m 55s
1556:	learn: 0.0114443	total: 2m 45s	remaining: 14m 57s
1514:	learn: 0.0109199	total: 2m 45s	remaining: 15m 27s
1442:	learn: 0.0122265	total: 2m 45s	remaining: 16m 22s
1557:	learn: 0.0114345	total: 2m 45s	remaining: 14m 57s
1584:	learn: 0.0101219	total: 2m 45s	remaining: 14m 39s
1560:	learn: 0.0096876	total: 2m 45s	remaining: 14m 55s
1515:	learn: 0.0109045	total: 2m 45s	remaining: 15m 27s
1443:	learn: 0.0122121	total: 2m 45s	remaining: 16m 21s
1558:	learn: 0.0114228	total: 2m 45s	remaining: 14m 57s
1561:	learn: 0.0096783	total: 2m 45s	remaining: 14m 55s
1444:	learn: 0.0121970	total: 2m 45s	remaining: 16m 21s
1585:	learn: 0.0101158	total: 2m 45s	remaining: 14m 39s
1516:	learn: 0.0108928	total: 2m 45s	remaining: 15m 27s
1562:	learn: 0.0096705	total: 2m 45s	remaining: 14m 55s
1586:	learn: 0.0101121	total: 2m 45s	remaining: 14m 39s
1559:	learn: 0.0114140	total: 2m 45s	remaining: 14m 57s
1445:	learn: 0.0121892	total: 2m 45s	remaining: 16m 21s
1517:	learn: 0.0108813	total: 2m 45s	remaining: 15m 27s
1563:	learn: 0.0096593	total: 2m 45s	remaining: 14m 54s
1587:	learn: 0.0100992	total: 2m 46s	remaining: 14m 39s
1560:	learn: 0.0114080	total: 2m 45s	remaining: 14m 56s
1446:	learn: 0.0121758	total: 2m 46s	remaining: 16m 21s
1518:	learn: 0.0108696	total: 2m 46s	remaining: 15m 26s
1564:	learn: 0.0096451	total: 2m 45s	remaining: 14m 54s
1588:	learn: 0.0100887	total: 2m 46s	remaining: 14m 39s
1561:	learn: 0.0113973	total: 2m 46s	remaining: 14m 56s
1447:	learn: 0.0121603	total: 2m 46s	remaining: 16m 21s
1519:	learn: 0.0108537	total: 2m 46s	remaining: 15m 26s
1565:	learn: 0.0096339	total: 2m 46s	remaining: 14m 54s
1589:	learn: 0.0100841	total: 2m 46s	remaining: 14m 39s
1562:	learn: 0.0113855	total: 2m 46s	remaining: 14m 56s
1448:	learn: 0.0121503	total: 2m 46s	remaining: 16m 21s
1566:	learn: 0.0096217	total: 2m 46s	remaining: 14m 54s
1520:	learn: 0.0108494	total: 2m 46s	remaining: 15m 26s
1590:	learn: 0.0100755	total: 2m 46s	remaining: 14m 39s
1449:	learn: 0.0121383	total: 2m 46s	remaining: 16m 20s
1563:	learn: 0.0113777	total: 2m 46s	remaining: 14m 56s
1591:	learn: 0.0100697	total: 2m 46s	remaining: 14m 38s
1567:	learn: 0.0096098	total: 2m 46s	remaining: 14m 54s
1521:	learn: 0.0108398	total: 2m 46s	remaining: 15m 26s
1450:	learn: 0.0121240	total: 2m 46s	remaining: 16m 20s
1564:	learn: 0.0113671	total: 2m 46s	remaining: 14m 56s
1568:	learn: 0.0096038	total: 2m 46s	remaining: 14m 54s
1592:	learn: 0.0100588	total: 2m 46s	remaining: 14m 38s
1451:	learn: 0.0121085	total: 2m 46s	remaining: 16m 20s
1522:	learn: 0.0108273	total: 2m 46s	remaining: 15m 26s
1565:	learn: 0.0113590	total: 2m 46s	remaining: 14m 56s
1593:	learn: 0.0100485	total: 2m 46s	remaining: 14m 38s
1569:	learn: 0.0096008	total: 2m 46s	remaining: 14m 54s
1452:	learn: 0.0120941	total: 2m 46s	remaining: 16m 20s
1566:	learn: 0.0113475	total: 2m 46s	remaining: 14m 56s
1523:	learn: 0.0108210	total: 2m 46s	remaining: 15m 26s
1594:	learn: 0.0100395	total: 2m 46s	remaining: 14m 38s
1567:	learn: 0.0113394	total: 2m 46s	remaining: 14m 55s
1453:	learn: 0.0120835	total: 2m 46s	remaining: 16m 19s
1570:	learn: 0.0095905	total: 2m 46s	remaining: 14m 54s
1524:	learn: 0.0108056	total: 2m 46s	remaining: 15m 26s
1595:	learn: 0.0100283	total: 2m 46s	remaining: 14m 38s
1568:	learn: 0.0113243	total: 2m 46s	remaining: 14m 55s
1571:	learn: 0.0095777	total: 2m 46s	remaining: 14m 53s
1525:	learn: 0.0107881	total: 2m 46s	remaining: 15m 26s
1454:	learn: 0.0120744	total: 2m 46s	remaining: 16m 19s
1596:	learn: 0.0100166	total: 2m 46s	remaining: 14m 38s
1569:	learn: 0.0113086	total: 2m 46s	remaining: 14m 55s
1572:	learn: 0.0095705	total: 2m 46s	remaining: 14m 53s
1526:	learn: 0.0107778	total: 2m 46s	remaining: 15m 26s
1455:	learn: 0.0120604	total: 2m 46s	remaining: 16m 19s
1597:	learn: 0.0100070	total: 2m 46s	remaining: 14m 37s
1573:	learn: 0.0095592	total: 2m 46s	remaining: 14m 53s
1570:	learn: 0.0112972	total: 2m 46s	remaining: 14m 55s
1456:	learn: 0.0120384	total: 2m 47s	remaining: 16m 19s
1598:	learn: 0.0099950	total: 2m 47s	remaining: 14m 37s
1527:	learn: 0.0107671	total: 2m 47s	remaining: 15m 26s
1571:	learn: 0.0112822	total: 2m 46s	remaining: 14m 55s
1574:	learn: 0.0095510	total: 2m 47s	remaining: 14m 53s
1457:	learn: 0.0120314	total: 2m 47s	remaining: 16m 19s
1572:	learn: 0.0112678	total: 2m 47s	remaining: 14m 54s
1599:	learn: 0.0099866	total: 2m 47s	remaining: 14m 37s
1528:	learn: 0.0107497	total: 2m 47s	remaining: 15m 26s
1458:	learn: 0.0120121	total: 2m 47s	remaining: 16m 18s
1573:	learn: 0.0112618	total: 2m 47s	remaining: 14m 54s
1575:	learn: 0.0095401	total: 2m 47s	remaining: 14m 53s
1600:	learn: 0.0099781	total: 2m 47s	remaining: 14m 37s
1529:	learn: 0.0107374	total: 2m 47s	remaining: 15m 25s
1459:	learn: 0.0120003	total: 2m 47s	remaining: 16m 18s
1576:	learn: 0.0095318	total: 2m 47s	remaining: 14m 53s
1530:	learn: 0.0107214	total: 2m 47s	remaining: 15m 25s
1574:	learn: 0.0112518	total: 2m 47s	remaining: 14m 54s
1601:	learn: 0.0099674	total: 2m 47s	remaining: 14m 37s
1531:	learn: 0.0107091	total: 2m 47s	remaining: 15m 25s
1460:	learn: 0.0119853	total: 2m 47s	remaining: 16m 18s
1577:	learn: 0.0095207	total: 2m 47s	remaining: 14m 53s
1575:	learn: 0.0112408	total: 2m 47s	remaining: 14m 54s
1602:	learn: 0.0099593	total: 2m 47s	remaining: 14m 37s
1532:	learn: 0.0106983	total: 2m 47s	remaining: 15m 25s
1578:	learn: 0.0095135	total: 2m 47s	remaining: 14m 53s
1461:	learn: 0.0119770	total: 2m 47s	remaining: 16m 18s
1576:	learn: 0.0112340	total: 2m 47s	remaining: 14m 54s
1603:	learn: 0.0099539	total: 2m 47s	remaining: 14m 37s
1462:	learn: 0.0119670	total: 2m 47s	remaining: 16m 18s
1579:	learn: 0.0095074	total: 2m 47s	remaining: 14m 52s
1533:	learn: 0.0106843	total: 2m 47s	remaining: 15m 25s
1577:	learn: 0.0112268	total: 2m 47s	remaining: 14m 54s
1580:	learn: 0.0094997	total: 2m 47s	remaining: 14m 52s
1604:	learn: 0.0099422	total: 2m 47s	remaining: 14m 37s
1463:	learn: 0.0119485	total: 2m 47s	remaining: 16m 18s
1534:	learn: 0.0106708	total: 2m 47s	remaining: 15m 25s
1578:	learn: 0.0112120	total: 2m 47s	remaining: 14m 54s
1605:	learn: 0.0099378	total: 2m 47s	remaining: 14m 37s
1581:	learn: 0.0094921	total: 2m 47s	remaining: 14m 52s
1535:	learn: 0.0106622	total: 2m 47s	remaining: 15m 24s
1579:	learn: 0.0112023	total: 2m 47s	remaining: 14m 54s
1464:	learn: 0.0119431	total: 2m 47s	remaining: 16m 17s
1606:	learn: 0.0099294	total: 2m 47s	remaining: 14m 37s
1582:	learn: 0.0094844	total: 2m 47s	remaining: 14m 52s
1580:	learn: 0.0111882	total: 2m 47s	remaining: 14m 53s
1536:	learn: 0.0106479	total: 2m 47s	remaining: 15m 24s
1465:	learn: 0.0119229	total: 2m 47s	remaining: 16m 17s
1607:	learn: 0.0099210	total: 2m 48s	remaining: 14m 36s
1581:	learn: 0.0111805	total: 2m 47s	remaining: 14m 53s
1583:	learn: 0.0094751	total: 2m 47s	remaining: 14m 52s
1537:	learn: 0.0106383	total: 2m 48s	remaining: 15m 24s
1608:	learn: 0.0099107	total: 2m 48s	remaining: 14m 36s
1466:	learn: 0.0119047	total: 2m 48s	remaining: 16m 17s
1582:	learn: 0.0111715	total: 2m 48s	remaining: 14m 53s
1584:	learn: 0.0094649	total: 2m 48s	remaining: 14m 52s
1538:	learn: 0.0106340	total: 2m 48s	remaining: 15m 24s
1609:	learn: 0.0099045	total: 2m 48s	remaining: 14m 36s
1467:	learn: 0.0118918	total: 2m 48s	remaining: 16m 17s
1583:	learn: 0.0111558	total: 2m 48s	remaining: 14m 53s
1585:	learn: 0.0094558	total: 2m 48s	remaining: 14m 52s
1539:	learn: 0.0106256	total: 2m 48s	remaining: 15m 24s
	learn: 0.0100089	total: 2m 42s	remaining: 15m 1s
      1468:	learn: 0.0118780	total: 2m 48s	remaining: 16m 17s
1610:	learn: 0.0098915	total: 2m 48s	remaining: 14m 36s
1586:	learn: 0.0094461	total: 2m 48s	remaining: 14m 51s
1584:	learn: 0.0111460	total: 2m 48s	remaining: 14m 53s
1540:	learn: 0.0106139	total: 2m 48s	remaining: 15m 24s
1587:	learn: 0.0094378	total: 2m 48s	remaining: 14m 51s
1611:	learn: 0.0098790	total: 2m 48s	remaining: 14m 36s
1469:	learn: 0.0118685	total: 2m 48s	remaining: 16m 17s
1585:	learn: 0.0111386	total: 2m 48s	remaining: 14m 53s
1541:	learn: 0.0106092	total: 2m 48s	remaining: 15m 24s
1612:	learn: 0.0098660	total: 2m 48s	remaining: 14m 36s
1588:	learn: 0.0094289	total: 2m 48s	remaining: 14m 51s
1470:	learn: 0.0118549	total: 2m 48s	remaining: 16m 17s
1586:	learn: 0.0111328	total: 2m 48s	remaining: 14m 52s
1542:	learn: 0.0105944	total: 2m 48s	remaining: 15m 23s
1613:	learn: 0.0098584	total: 2m 48s	remaining: 14m 36s
1589:	learn: 0.0094181	total: 2m 48s	remaining: 14m 51s
1471:	learn: 0.0118324	total: 2m 48s	remaining: 16m 16s
1587:	learn: 0.0111184	total: 2m 48s	remaining: 14m 52s
1614:	learn: 0.0098528	total: 2m 48s	remaining: 14m 35s
1543:	learn: 0.0105767	total: 2m 48s	remaining: 15m 23s
1472:	learn: 0.0118210	total: 2m 48s	remaining: 16m 16s
1590:	learn: 0.0094072	total: 2m 48s	remaining: 14m 51s
1588:	learn: 0.0111045	total: 2m 48s	remaining: 14m 52s
1615:	learn: 0.0098399	total: 2m 48s	remaining: 14m 35s
1591:	learn: 0.0093996	total: 2m 48s	remaining: 14m 51s
1544:	learn: 0.0105729	total: 2m 48s	remaining: 15m 23s
1473:	learn: 0.0118025	total: 2m 48s	remaining: 16m 16s
1589:	learn: 0.0110969	total: 2m 48s	remaining: 14m 52s
1616:	learn: 0.0098357	total: 2m 48s	remaining: 14m 35s
1545:	learn: 0.0105587	total: 2m 48s	remaining: 15m 23s
1592:	learn: 0.0093969	total: 2m 48s	remaining: 14m 51s
1474:	learn: 0.0117828	total: 2m 48s	remaining: 16m 16s
1590:	learn: 0.0110830	total: 2m 48s	remaining: 14m 52s
1593:	learn: 0.0093935	total: 2m 48s	remaining: 14m 50s
1546:	learn: 0.0105464	total: 2m 48s	remaining: 15m 23s
1617:	learn: 0.0098293	total: 2m 49s	remaining: 14m 35s
1475:	learn: 0.0117717	total: 2m 49s	remaining: 16m 16s
1591:	learn: 0.0110724	total: 2m 48s	remaining: 14m 52s
1594:	learn: 0.0093846	total: 2m 49s	remaining: 14m 50s
1618:	learn: 0.0098207	total: 2m 49s	remaining: 14m 35s
1547:	learn: 0.0105382	total: 2m 49s	remaining: 15m 23s
1476:	learn: 0.0117574	total: 2m 49s	remaining: 16m 15s
1592:	learn: 0.0110618	total: 2m 49s	remaining: 14m 52s
1595:	learn: 0.0093776	total: 2m 49s	remaining: 14m 50s
1619:	learn: 0.0098130	total: 2m 49s	remaining: 14m 35s
1548:	learn: 0.0105296	total: 2m 49s	remaining: 15m 23s
1477:	learn: 0.0117499	total: 2m 49s	remaining: 16m 15s
1593:	learn: 0.0110529	total: 2m 49s	remaining: 14m 51s
1596:	learn: 0.0093698	total: 2m 49s	remaining: 14m 50s
1620:	learn: 0.0098024	total: 2m 49s	remaining: 14m 35s
1549:	learn: 0.0105199	total: 2m 49s	remaining: 15m 22s
1594:	learn: 0.0110365	total: 2m 49s	remaining: 14m 51s
1478:	learn: 0.0117371	total: 2m 49s	remaining: 16m 15s
1597:	learn: 0.0093640	total: 2m 49s	remaining: 14m 50s
1621:	learn: 0.0097925	total: 2m 49s	remaining: 14m 35s
1550:	learn: 0.0105108	total: 2m 49s	remaining: 15m 22s
1595:	learn: 0.0110263	total: 2m 49s	remaining: 14m 51s
1479:	learn: 0.0117293	total: 2m 49s	remaining: 16m 15s
1598:	learn: 0.0093521	total: 2m 49s	remaining: 14m 49s
1622:	learn: 0.0097821	total: 2m 49s	remaining: 14m 35s
1596:	learn: 0.0110180	total: 2m 49s	remaining: 14m 51s
1551:	learn: 0.0104995	total: 2m 49s	remaining: 15m 22s
1480:	learn: 0.0117157	total: 2m 49s	remaining: 16m 15s
1599:	learn: 0.0093433	total: 2m 49s	remaining: 14m 50s
1623:	learn: 0.0097751	total: 2m 49s	remaining: 14m 34s
1597:	learn: 0.0110032	total: 2m 49s	remaining: 14m 51s
1552:	learn: 0.0104891	total: 2m 49s	remaining: 15m 22s
1598:	learn: 0.0109953	total: 2m 49s	remaining: 14m 51s
1600:	learn: 0.0093376	total: 2m 49s	remaining: 14m 49s
1481:	learn: 0.0117079	total: 2m 49s	remaining: 16m 15s
1624:	learn: 0.0097652	total: 2m 49s	remaining: 14m 34s
1553:	learn: 0.0104709	total: 2m 49s	remaining: 15m 22s
1482:	learn: 0.0116970	total: 2m 49s	remaining: 16m 15s
1599:	learn: 0.0109839	total: 2m 49s	remaining: 14m 50s
1625:	learn: 0.0097567	total: 2m 49s	remaining: 14m 34s
1601:	learn: 0.0093270	total: 2m 49s	remaining: 14m 49s
1554:	learn: 0.0104669	total: 2m 49s	remaining: 15m 22s
1626:	learn: 0.0097426	total: 2m 49s	remaining: 14m 34s
1483:	learn: 0.0116838	total: 2m 49s	remaining: 16m 14s
1600:	learn: 0.0109727	total: 2m 49s	remaining: 14m 50s
1602:	learn: 0.0093181	total: 2m 49s	remaining: 14m 49s
1555:	learn: 0.0104593	total: 2m 49s	remaining: 15m 22s
1627:	learn: 0.0097355	total: 2m 49s	remaining: 14m 34s
1603:	learn: 0.0093076	total: 2m 49s	remaining: 14m 49s
1601:	learn: 0.0109614	total: 2m 49s	remaining: 14m 50s
1484:	learn: 0.0116696	total: 2m 50s	remaining: 16m 14s
1556:	learn: 0.0104462	total: 2m 50s	remaining: 15m 21s
1628:	learn: 0.0097301	total: 2m 50s	remaining: 14m 34s
1604:	learn: 0.0093010	total: 2m 50s	remaining: 14m 49s
1485:	learn: 0.0116649	total: 2m 50s	remaining: 16m 14s
1557:	learn: 0.0104318	total: 2m 50s	remaining: 15m 21s
1602:	learn: 0.0109485	total: 2m 50s	remaining: 14m 50s
1605:	learn: 0.0092914	total: 2m 50s	remaining: 14m 49s
1629:	learn: 0.0097220	total: 2m 50s	remaining: 14m 33s
1558:	learn: 0.0104140	total: 2m 50s	remaining: 15m 21s
1486:	learn: 0.0116558	total: 2m 50s	remaining: 16m 14s
1603:	learn: 0.0109356	total: 2m 50s	remaining: 14m 50s
1606:	learn: 0.0092782	total: 2m 50s	remaining: 14m 48s
1630:	learn: 0.0097125	total: 2m 50s	remaining: 14m 33s
1487:	learn: 0.0116443	total: 2m 50s	remaining: 16m 14s
1559:	learn: 0.0104051	total: 2m 50s	remaining: 15m 21s
1604:	learn: 0.0109276	total: 2m 50s	remaining: 14m 50s
1607:	learn: 0.0092696	total: 2m 50s	remaining: 14m 48s
1631:	learn: 0.0096982	total: 2m 50s	remaining: 14m 33s
1560:	learn: 0.0104000	total: 2m 50s	remaining: 15m 21s
1608:	learn: 0.0092564	total: 2m 50s	remaining: 14m 48s
1488:	learn: 0.0116343	total: 2m 50s	remaining: 16m 14s
1605:	learn: 0.0109193	total: 2m 50s	remaining: 14m 50s
1561:	learn: 0.0103912	total: 2m 50s	remaining: 15m 20s
1632:	learn: 0.0096898	total: 2m 50s	remaining: 14m 33s
1489:	learn: 0.0116217	total: 2m 50s	remaining: 16m 14s
1609:	learn: 0.0092480	total: 2m 50s	remaining: 14m 48s
1562:	learn: 0.0103767	total: 2m 50s	remaining: 15m 20s
1606:	learn: 0.0109060	total: 2m 50s	remaining: 14m 50s
1633:	learn: 0.0096836	total: 2m 50s	remaining: 14m 33s
1610:	learn: 0.0092447	total: 2m 50s	remaining: 14m 48s
1607:	learn: 0.0108918	total: 2m 50s	remaining: 14m 50s
1490:	learn: 0.0116088	total: 2m 50s	remaining: 16m 13s
1563:	learn: 0.0103616	total: 2m 50s	remaining: 15m 20s
1634:	learn: 0.0096753	total: 2m 50s	remaining: 14m 33s
1608:	learn: 0.0108833	total: 2m 50s	remaining: 14m 49s
1491:	learn: 0.0115990	total: 2m 50s	remaining: 16m 13s
1611:	learn: 0.0092317	total: 2m 50s	remaining: 14m 48s
1564:	learn: 0.0103523	total: 2m 50s	remaining: 15m 20s
1635:	learn: 0.0096710	total: 2m 50s	remaining: 14m 33s
1609:	learn: 0.0108696	total: 2m 50s	remaining: 14m 49s
1492:	learn: 0.0115813	total: 2m 50s	remaining: 16m 13s
1612:	learn: 0.0092208	total: 2m 50s	remaining: 14m 48s
1565:	learn: 0.0103440	total: 2m 50s	remaining: 15m 20s
1636:	learn: 0.0096652	total: 2m 50s	remaining: 14m 33s
1610:	learn: 0.0108538	total: 2m 50s	remaining: 14m 49s
1613:	learn: 0.0092110	total: 2m 50s	remaining: 14m 47s
1493:	learn: 0.0115683	total: 2m 50s	remaining: 16m 13s
1566:	learn: 0.0103352	total: 2m 50s	remaining: 15m 20s
1637:	learn: 0.0096574	total: 2m 51s	remaining: 14m 33s
1611:	learn: 0.0108408	total: 2m 50s	remaining: 14m 49s
1614:	learn: 0.0092007	total: 2m 50s	remaining: 14m 47s
1567:	learn: 0.0103198	total: 2m 51s	remaining: 15m 19s
1494:	learn: 0.0115565	total: 2m 51s	remaining: 16m 13s
1612:	learn: 0.0108276	total: 2m 51s	remaining: 14m 49s
1638:	learn: 0.0096497	total: 2m 51s	remaining: 14m 33s
1615:	learn: 0.0091904	total: 2m 51s	remaining: 14m 47s
1568:	learn: 0.0103040	total: 2m 51s	remaining: 15m 19s
1495:	learn: 0.0115391	total: 2m 51s	remaining: 16m 13s
1613:	learn: 0.0108193	total: 2m 51s	remaining: 14m 49s

1639:	learn: 0.0096391	total: 2m 51s	remaining: 14m 33s
1496:	learn: 0.0115315	total: 2m 51s	remaining: 16m 12s
1614:	learn: 0.0108067	total: 2m 51s	remaining: 14m 49s
1617:	learn: 0.0091684	total: 2m 51s	remaining: 14m 47s
1640:	learn: 0.0096257	total: 2m 51s	remaining: 14m 32s
1570:	learn: 0.0102845	total: 2m 51s	remaining: 15m 19s
1497:	learn: 0.0115125	total: 2m 51s	remaining: 16m 12s
1615:	learn: 0.0107966	total: 2m 51s	remaining: 14m 48s
1618:	learn: 0.0091601	total: 2m 51s	remaining: 14m 47s
1641:	learn: 0.0096142	total: 2m 51s	remaining: 14m 32s
1571:	learn: 0.0102728	total: 2m 51s	remaining: 15m 19s
1498:	learn: 0.0115019	total: 2m 51s	remaining: 16m 12s
1619:	learn: 0.0091519	total: 2m 51s	remaining: 14m 46s
1642:	learn: 0.0096032	total: 2m 51s	remaining: 14m 32s
1616:	learn: 0.0107879	total: 2m 51s	remaining: 14m 48s
1499:	learn: 0.0114949	total: 2m 51s	remaining: 16m 12s
1572:	learn: 0.0102624	total: 2m 51s	remaining: 15m 19s
1620:	learn: 0.0091438	total: 2m 51s	remaining: 14m 46s
1617:	learn: 0.0107802	total: 2m 51s	remaining: 14m 48s
1643:	learn: 0.0095909	total: 2m 51s	remaining: 14m 32s
1500:	learn: 0.0114823	total: 2m 51s	remaining: 16m 12s
1621:	learn: 0.0091368	total: 2m 51s	remaining: 14m 46s
1573:	learn: 0.0102586	total: 2m 51s	remaining: 15m 19s
1618:	learn: 0.0107734	total: 2m 51s	remaining: 14m 48s
1644:	learn: 0.0095767	total: 2m 51s	remaining: 14m 32s
1501:	learn: 0.0114732	total: 2m 51s	remaining: 16m 11s
1622:	learn: 0.0091265	total: 2m 51s	remaining: 14m 46s
1645:	learn: 0.0095699	total: 2m 51s	remaining: 14m 32s
1619:	learn: 0.0107553	total: 2m 51s	remaining: 14m 48s
1574:	learn: 0.0102494	total: 2m 51s	remaining: 15m 19s
1502:	learn: 0.0114625	total: 2m 51s	remaining: 16m 11s
1623:	learn: 0.0091165	total: 2m 51s	remaining: 14m 46s
1575:	learn: 0.0102362	total: 2m 51s	remaining: 15m 18s
1620:	learn: 0.0107421	total: 2m 51s	remaining: 14m 48s
1646:	learn: 0.0095618	total: 2m 51s	remaining: 14m 32s
1503:	learn: 0.0114514	total: 2m 51s	remaining: 16m 11s
1624:	learn: 0.0091085	total: 2m 51s	remaining: 14m 46s
1576:	learn: 0.0102239	total: 2m 52s	remaining: 15m 18s
1647:	learn: 0.0095494	total: 2m 52s	remaining: 14m 32s
1504:	learn: 0.0114328	total: 2m 52s	remaining: 16m 11s
1625:	learn: 0.0090995	total: 2m 52s	remaining: 14m 45s
1621:	learn: 0.0107267	total: 2m 51s	remaining: 14m 48s
1648:	learn: 0.0095404	total: 2m 52s	remaining: 14m 31s
1577:	learn: 0.0102138	total: 2m 52s	remaining: 15m 18s
1505:	learn: 0.0114281	total: 2m 52s	remaining: 16m 10s
1622:	learn: 0.0107137	total: 2m 52s	remaining: 14m 48s
1626:	learn: 0.0090961	total: 2m 52s	remaining: 14m 45s
1649:	learn: 0.0095331	total: 2m 52s	remaining: 14m 31s
1578:	learn: 0.0102043	total: 2m 52s	remaining: 15m 18s
1623:	learn: 0.0107030	total: 2m 52s	remaining: 14m 47s
1506:	learn: 0.0114177	total: 2m 52s	remaining: 16m 10s
1627:	learn: 0.0090866	total: 2m 52s	remaining: 14m 45s
1624:	learn: 0.0106875	total: 2m 52s	remaining: 14m 47s
1650:	learn: 0.0095230	total: 2m 52s	remaining: 14m 31s
1579:	learn: 0.0101963	total: 2m 52s	remaining: 15m 18s
1507:	learn: 0.0114052	total: 2m 52s	remaining: 16m 10s
1628:	learn: 0.0090815	total: 2m 52s	remaining: 14m 45s
1651:	learn: 0.0095076	total: 2m 52s	remaining: 14m 31s
1580:	learn: 0.0101829	total: 2m 52s	remaining: 15m 18s
1625:	learn: 0.0106697	total: 2m 52s	remaining: 14m 47s
1508:	learn: 0.0113868	total: 2m 52s	remaining: 16m 10s
1629:	learn: 0.0090706	total: 2m 52s	remaining: 14m 45s
1581:	learn: 0.0101757	total: 2m 52s	remaining: 15m 17s
1652:	learn: 0.0094966	total: 2m 52s	remaining: 14m 31s
1626:	learn: 0.0106622	total: 2m 52s	remaining: 14m 47s
1509:	learn: 0.0113737	total: 2m 52s	remaining: 16m 10s
1653:	learn: 0.0094898	total: 2m 52s	remaining: 14m 31s
1630:	learn: 0.0090610	total: 2m 52s	remaining: 14m 45s
1582:	learn: 0.0101720	total: 2m 52s	remaining: 15m 17s
1627:	learn: 0.0106524	total: 2m 52s	remaining: 14m 47s
1654:	learn: 0.0094845	total: 2m 52s	remaining: 14m 30s
1583:	learn: 0.0101582	total: 2m 52s	remaining: 15m 17s
1510:	learn: 0.0113580	total: 2m 52s	remaining: 16m 10s
1628:	learn: 0.0106382	total: 2m 52s	remaining: 14m 47s
1631:	learn: 0.0090497	total: 2m 52s	remaining: 14m 45s
1655:	learn: 0.0094734	total: 2m 52s	remaining: 14m 30s
1511:	learn: 0.0113506	total: 2m 52s	remaining: 16m 10s
1584:	learn: 0.0101488	total: 2m 52s	remaining: 15m 17s
1632:	learn: 0.0090392	total: 2m 52s	remaining: 14m 45s
1629:	learn: 0.0106277	total: 2m 52s	remaining: 14m 47s
1656:	learn: 0.0094627	total: 2m 52s	remaining: 14m 30s
1585:	learn: 0.0101399	total: 2m 52s	remaining: 15m 17s
1630:	learn: 0.0106159	total: 2m 52s	remaining: 14m 46s
1633:	learn: 0.0090281	total: 2m 52s	remaining: 14m 45s
1512:	learn: 0.0113418	total: 2m 52s	remaining: 16m 10s
1657:	learn: 0.0094571	total: 2m 52s	remaining: 14m 30s
1586:	learn: 0.0101246	total: 2m 52s	remaining: 15m 16s
1513:	learn: 0.0113314	total: 2m 53s	remaining: 16m 9s
1631:	learn: 0.0106090	total: 2m 52s	remaining: 14m 46s
1634:	learn: 0.0090183	total: 2m 53s	remaining: 14m 45s
1658:	learn: 0.0094478	total: 2m 53s	remaining: 14m 30s
1587:	learn: 0.0101160	total: 2m 53s	remaining: 15m 16s
1514:	learn: 0.0113137	total: 2m 53s	remaining: 16m 9s
1632:	learn: 0.0106010	total: 2m 53s	remaining: 14m 46s
1635:	learn: 0.0090101	total: 2m 53s	remaining: 14m 45s
1659:	learn: 0.0094416	total: 2m 53s	remaining: 14m 30s
1515:	learn: 0.0112996	total: 2m 53s	remaining: 16m 9s
1588:	learn: 0.0101063	total: 2m 53s	remaining: 15m 16s
1660:	learn: 0.0094355	total: 2m 53s	remaining: 14m 30s
1516:	learn: 0.0112935	total: 2m 53s	remaining: 16m 9s
1636:	learn: 0.0090058	total: 2m 53s	remaining: 14m 44s
1633:	learn: 0.0105841	total: 2m 53s	remaining: 14m 46s
1589:	learn: 0.0100926	total: 2m 53s	remaining: 15m 16s
1637:	learn: 0.0089949	total: 2m 53s	remaining: 14m 44s
1634:	learn: 0.0105718	total: 2m 53s	remaining: 14m 46s
1517:	learn: 0.0112833	total: 2m 53s	remaining: 16m 8s
1661:	learn: 0.0094273	total: 2m 53s	remaining: 14m 30s
1590:	learn: 0.0100833	total: 2m 53s	remaining: 15m 16s
1638:	learn: 0.0089840	total: 2m 53s	remaining: 14m 44s
1635:	learn: 0.0105559	total: 2m 53s	remaining: 14m 46s
1518:	learn: 0.0112672	total: 2m 53s	remaining: 16m 8s
1662:	learn: 0.0094235	total: 2m 53s	remaining: 14m 30s
1639:	learn: 0.0089759	total: 2m 53s	remaining: 14m 44s
1591:	learn: 0.0100747	total: 2m 53s	remaining: 15m 16s
1636:	learn: 0.0105497	total: 2m 53s	remaining: 14m 46s
1519:	learn: 0.0112542	total: 2m 53s	remaining: 16m 8s
1663:	learn: 0.0094157	total: 2m 53s	remaining: 14m 29s
1640:	learn: 0.0089726	total: 2m 53s	remaining: 14m 44s
1637:	learn: 0.0105429	total: 2m 53s	remaining: 14m 45s
1592:	learn: 0.0100607	total: 2m 53s	remaining: 15m 16s
1520:	learn: 0.0112469	total: 2m 53s	remaining: 16m 8s
1664:	learn: 0.0094113	total: 2m 53s	remaining: 14m 29s
1641:	learn: 0.0089609	total: 2m 53s	remaining: 14m 44s
1521:	learn: 0.0112379	total: 2m 53s	remaining: 16m 8s
1638:	learn: 0.0105308	total: 2m 53s	remaining: 14m 45s
1593:	learn: 0.0100459	total: 2m 53s	remaining: 15m 16s
1665:	learn: 0.0094022	total: 2m 53s	remaining: 14m 29s
1642:	learn: 0.0089561	total: 2m 53s	remaining: 14m 43s
1639:	learn: 0.0105219	total: 2m 53s	remaining: 14m 45s
1594:	learn: 0.0100366	total: 2m 53s	remaining: 15m 16s
1522:	learn: 0.0112227	total: 2m 53s	remaining: 16m 7s
1666:	learn: 0.0093984	total: 2m 53s	remaining: 14m 29s
1640:	learn: 0.0105098	total: 2m 53s	remaining: 14m 45s
1595:	learn: 0.0100232	total: 2m 53s	remaining: 15m 15s
1643:	learn: 0.0089463	total: 2m 53s	remaining: 14m 43s
1523:	learn: 0.0112186	total: 2m 54s	remaining: 16m 7s
1667:	learn: 0.0093928	total: 2m 54s	remaining: 14m 29s
1596:	learn: 0.0100158	total: 2m 54s	remaining: 15m 15s
1644:	learn: 0.0089332	total: 2m 54s	remaining: 14m 43s
1641:	learn: 0.0105009	total: 2m 53s	remaining: 14m 45s
1668:	learn: 0.0093829	total: 2m 54s	remaining: 14m 29s
1524:	learn: 0.0112003	total: 2m 54s	remaining: 16m 7s
1597:	learn: 0.0100081	total: 2m 54s	remaining: 15m 15s
1642:	learn: 0.0104940	total: 2m 54s	remaining: 14m 45s
39s	remaining: 16m 30s
1521:	learn: 0.0107480	total: 2m 39s	remaining: 14m 47s
1492:	learn: 0.0121695	total: 2m 1645:	learn: 0.0089258	total: 2m 54s	remaining: 14m 43s
1669:	learn: 0.0093751	total: 2m 54s	remaining: 14m 29s
1525:	learn: 0.0111861	total: 2m 54s	remaining: 16m 7s
1643:	learn: 0.0104859	total: 2m 54s	remaining: 14m 45s
1598:	learn: 0.0100045	total: 2m 54s	remaining: 15m 15s
1646:	learn: 0.0089186	total: 2m 54s	remaining: 14m 43s
1670:	learn: 0.0093644	total: 2m 54s	remaining: 14m 28s
1644:	learn: 0.0104789	total: 2m 54s	remaining: 14m 45s
1526:	learn: 0.0111761	total: 2m 54s	remaining: 16m 7s
1599:	learn: 0.0099887	total: 2m 54s	remaining: 15m 15s
1671:	learn: 0.0093589	total: 2m 54s	remaining: 14m 28s
1647:	learn: 0.0089107	total: 2m 54s	remaining: 14m 43s
1645:	learn: 0.0104736	total: 2m 54s	remaining: 14m 44s
1527:	learn: 0.0111662	total: 2m 54s	remaining: 16m 7s
1600:	learn: 0.0099732	total: 2m 54s	remaining: 15m 15s
1672:	learn: 0.0093531	total: 2m 54s	remaining: 14m 28s
1648:	learn: 0.0089026	total: 2m 54s	remaining: 14m 43s
1646:	learn: 0.0104668	total: 2m 54s	remaining: 14m 44s
1601:	learn: 0.0099601	total: 2m 54s	remaining: 15m 14s
1528:	learn: 0.0111615	total: 2m 54s	remaining: 16m 7s
1649:	learn: 0.0088949	total: 2m 54s	remaining: 14m 43s
1673:	learn: 0.0093479	total: 2m 54s	remaining: 14m 28s
1647:	learn: 0.0104503	total: 2m 54s	remaining: 14m 44s
1602:	learn: 0.0099494	total: 2m 54s	remaining: 15m 14s
1529:	learn: 0.0111498	total: 2m 54s	remaining: 16m 7s
1650:	learn: 0.0088877	total: 2m 54s	remaining: 14m 43s
1648:	learn: 0.0104387	total: 2m 54s	remaining: 14m 44s
1674:	learn: 0.0093402	total: 2m 54s	remaining: 14m 28s
1603:	learn: 0.0099404	total: 2m 54s	remaining: 15m 14s
1530:	learn: 0.0111372	total: 2m 54s	remaining: 16m 6s
1649:	learn: 0.0104318	total: 2m 54s	remaining: 14m 44s
1675:	learn: 0.0093270	total: 2m 54s	remaining: 14m 28s
1604:	learn: 0.0099328	total: 2m 54s	remaining: 15m 14s
1651:	learn: 0.0088839	total: 2m 54s	remaining: 14m 43s
1650:	learn: 0.0104170	total: 2m 54s	remaining: 14m 43s
1531:	learn: 0.0111229	total: 2m 54s	remaining: 16m 6s
1676:	learn: 0.0093168	total: 2m 54s	remaining: 14m 28s
1605:	learn: 0.0099196	total: 2m 54s	remaining: 15m 14s
1652:	learn: 0.0088764	total: 2m 54s	remaining: 14m 43s
1651:	learn: 0.0104052	total: 2m 54s	remaining: 14m 43s
1532:	learn: 0.0111065	total: 2m 55s	remaining: 16m 6s
1606:	learn: 0.0099098	total: 2m 55s	remaining: 15m 14s
1677:	learn: 0.0093051	total: 2m 55s	remaining: 14m 28s
1653:	learn: 0.0088684	total: 2m 54s	remaining: 14m 42s
1533:	learn: 0.0110920	total: 2m 55s	remaining: 16m 6s
1652:	learn: 0.0103951	total: 2m 55s	remaining: 14m 43s
1607:	learn: 0.0098976	total: 2m 55s	remaining: 15m 13s
1678:	learn: 0.0092939	total: 2m 55s	remaining: 14m 28s
1654:	learn: 0.0088622	total: 2m 55s	remaining: 14m 42s
1534:	learn: 0.0110776	total: 2m 55s	remaining: 16m 6s
1655:	learn: 0.0088546	total: 2m 55s	remaining: 14m 42s
1653:	learn: 0.0103882	total: 2m 55s	remaining: 14m 43s
1608:	learn: 0.0098861	total: 2m 55s	remaining: 15m 13s
1679:	learn: 0.0092844	total: 2m 55s	remaining: 14m 28s
1535:	learn: 0.0110633	total: 2m 55s	remaining: 16m 5s
1656:	learn: 0.0088443	total: 2m 55s	remaining: 14m 42s
1654:	learn: 0.0103777	total: 2m 55s	remaining: 14m 43s
1609:	learn: 0.0098796	total: 2m 55s	remaining: 15m 13s
1680:	learn: 0.0092740	total: 2m 55s	remaining: 14m 27s
1536:	learn: 0.0110557	total: 2m 55s	remaining: 16m 5s
1657:	learn: 0.0088338	total: 2m 55s	remaining: 14m 42s
1610:	learn: 0.0098655	total: 2m 55s	remaining: 15m 13s
1655:	learn: 0.0103713	total: 2m 55s	remaining: 14m 43s
1537:	learn: 0.0110367	total: 2m 55s	remaining: 16m 5s
1681:	learn: 0.0092675	total: 2m 55s	remaining: 14m 27s
1658:	learn: 0.0088265	total: 2m 55s	remaining: 14m 41s
1611:	learn: 0.0098603	total: 2m 55s	remaining: 15m 13s
1538:	learn: 0.0110217	total: 2m 55s	remaining: 16m 5s
1656:	learn: 0.0103617	total: 2m 55s	remaining: 14m 43s
1682:	learn: 0.0092545	total: 2m 55s	remaining: 14m 27s
1659:	learn: 0.0088199	total: 2m 55s	remaining: 14m 41s
1612:	learn: 0.0098529	total: 2m 55s	remaining: 15m 13s
1657:	learn: 0.0103520	total: 2m 55s	remaining: 14m 43s
1539:	learn: 0.0110079	total: 2m 55s	remaining: 16m 5s
1613:	learn: 0.0098402	total: 2m 55s	remaining: 15m 12s
1683:	learn: 0.0092458	total: 2m 55s	remaining: 14m 27s
1660:	learn: 0.0088107	total: 2m 55s	remaining: 14m 41s
1658:	learn: 0.0103453	total: 2m 55s	remaining: 14m 43s
1540:	learn: 0.0109981	total: 2m 55s	remaining: 16m 4s
1614:	learn: 0.0098262	total: 2m 55s	remaining: 15m 12s
1661:	learn: 0.0088034	total: 2m 55s	remaining: 14m 41s
1659:	learn: 0.0103386	total: 2m 55s	remaining: 14m 42s
1684:	learn: 0.0092422	total: 2m 55s	remaining: 14m 27s
1541:	learn: 0.0109933	total: 2m 55s	remaining: 16m 4s
1662:	learn: 0.0087963	total: 2m 55s	remaining: 14m 41s
1615:	learn: 0.0098192	total: 2m 55s	remaining: 15m 12s
1660:	learn: 0.0103335	total: 2m 55s	remaining: 14m 42s
1685:	learn: 0.0092358	total: 2m 55s	remaining: 14m 27s
1542:	learn: 0.0109812	total: 2m 55s	remaining: 16m 4s
1663:	learn: 0.0087888	total: 2m 55s	remaining: 14m 41s
1616:	learn: 0.0098105	total: 2m 55s	remaining: 15m 12s
1661:	learn: 0.0103267	total: 2m 55s	remaining: 14m 42s
1686:	learn: 0.0092274	total: 2m 56s	remaining: 14m 27s
1543:	learn: 0.0109712	total: 2m 56s	remaining: 16m 4s
1664:	learn: 0.0087738	total: 2m 56s	remaining: 14m 41s
1617:	learn: 0.0097956	total: 2m 56s	remaining: 15m 12s
1662:	learn: 0.0103152	total: 2m 56s	remaining: 14m 42s
1544:	learn: 0.0109566	total: 2m 56s	remaining: 16m 4s
1687:	learn: 0.0092192	total: 2m 56s	remaining: 14m 27s
1665:	learn: 0.0087644	total: 2m 56s	remaining: 14m 41s
1618:	learn: 0.0097908	total: 2m 56s	remaining: 15m 11s
1545:	learn: 0.0109448	total: 2m 56s	remaining: 16m 3s
1663:	learn: 0.0103057	total: 2m 56s	remaining: 14m 42s
1688:	learn: 0.0092119	total: 2m 56s	remaining: 14m 27s
1666:	learn: 0.0087565	total: 2m 56s	remaining: 14m 40s
1546:	learn: 0.0109377	total: 2m 56s	remaining: 16m 3s
1619:	learn: 0.0097774	total: 2m 56s	remaining: 15m 11s
1664:	learn: 0.0102971	total: 2m 56s	remaining: 14m 42s
1689:	learn: 0.0092011	total: 2m 56s	remaining: 14m 27s
1665:	learn: 0.0102890	total: 2m 56s	remaining: 14m 42s
1667:	learn: 0.0087489	total: 2m 56s	remaining: 14m 41s
1690:	learn: 0.0091956	total: 2m 56s	remaining: 14m 27s
1620:	learn: 0.0097727	total: 2m 56s	remaining: 15m 11s
1547:	learn: 0.0109278	total: 2m 56s	remaining: 16m 3s
1666:	learn: 0.0102799	total: 2m 56s	remaining: 14m 41s
1691:	learn: 0.0091836	total: 2m 56s	remaining: 14m 26s
1621:	learn: 0.0097616	total: 2m 56s	remaining: 15m 11s
1668:	learn: 0.0087393	total: 2m 56s	remaining: 14m 40s
1548:	learn: 0.0109236	total: 2m 56s	remaining: 16m 3s
1667:	learn: 0.0102635	total: 2m 56s	remaining: 14m 41s
1692:	learn: 0.0091744	total: 2m 56s	remaining: 14m 26s
1622:	learn: 0.0097523	total: 2m 56s	remaining: 15m 11s
1669:	learn: 0.0087320	total: 2m 56s	remaining: 14m 40s
1668:	learn: 0.0102538	total: 2m 56s	remaining: 14m 41s
1693:	learn: 0.0091647	total: 2m 56s	remaining: 14m 26s
1549:	learn: 0.0109083	total: 2m 56s	remaining: 16m 3s
1623:	learn: 0.0097436	total: 2m 56s	remaining: 15m 11s
1670:	learn: 0.0087254	total: 2m 56s	remaining: 14m 40s
1669:	learn: 0.0102462	total: 2m 56s	remaining: 14m 41s
1550:	learn: 0.0109029	total: 2m 56s	remaining: 16m 3s
1694:	learn: 0.0091547	total: 2m 56s	remaining: 14m 26s
1671:	learn: 0.0087178	total: 2m 56s	remaining: 14m 40s
1624:	learn: 0.0097385	total: 2m 56s	remaining: 15m 11s
1670:	learn: 0.0102314	total: 2m 56s	remaining: 14m 41s
1551:	learn: 0.0108882	total: 2m 56s	remaining: 16m 2s
1695:	learn: 0.0091456	total: 2m 56s	remaining: 14m 26s
1672:	learn: 0.0087106	total: 2m 56s	remaining: 14m 40s
1625:	learn: 0.0097304	total: 2m 56s	remaining: 15m 11s
1671:	learn: 0.0102225	total: 2m 56s	remaining: 14m 41s
1552:	learn: 0.0108775	total: 2m 57s	remaining: 16m 2s
1696:	learn: 0.0091371	total: 2m 57s	remaining: 14m 26s
1673:	learn: 0.0087043	total: 2m 57s	remaining: 14m 40s
1672:	learn: 0.0102080	total: 2m 56s	remaining: 14m 40s
1626:	learn: 0.0097148	total: 2m 57s	remaining: 15m 11s
1553:	learn: 0.0108640	total: 2m 57s	remaining: 16m 2s
1697:	learn: 0.0091279	total: 2m 57s	remaining: 14m 26s

1674:	learn: 0.0086933	total: 2m 57s	remaining: 14m 40s
1627:	learn: 0.0097026	total: 2m 57s	remaining: 15m 10s
1673:	learn: 0.0101948	total: 2m 57s	remaining: 14m 40s
1675:	learn: 0.0086858	total: 2m 57s	remaining: 14m 39s
1698:	learn: 0.0091153	total: 2m 57s	remaining: 14m 26s
1628:	learn: 0.0096981	total: 2m 57s	remaining: 15m 10s
1554:	learn: 0.0108548	total: 2m 57s	remaining: 16m 2s
1674:	learn: 0.0101879	total: 2m 57s	remaining: 14m 40s
1699:	learn: 0.0091050	total: 2m 57s	remaining: 14m 25s
1676:	learn: 0.0086760	total: 2m 57s	remaining: 14m 39s
1629:	learn: 0.0096915	total: 2m 57s	remaining: 15m 10s
1555:	learn: 0.0108404	total: 2m 57s	remaining: 16m 2s
1675:	learn: 0.0101737	total: 2m 57s	remaining: 14m 40s
1700:	learn: 0.0090967	total: 2m 57s	remaining: 14m 25s
1677:	learn: 0.0086668	total: 2m 57s	remaining: 14m 39s
1556:	learn: 0.0108280	total: 2m 57s	remaining: 16m 2s
1630:	learn: 0.0096851	total: 2m 57s	remaining: 15m 10s
1678:	learn: 0.0086596	total: 2m 57s	remaining: 14m 39s
1701:	learn: 0.0090889	total: 2m 57s	remaining: 14m 25s
1676:	learn: 0.0101581	total: 2m 57s	remaining: 14m 40s
1631:	learn: 0.0096696	total: 2m 57s	remaining: 15m 10s
1557:	learn: 0.0108185	total: 2m 57s	remaining: 16m 2s
1677:	learn: 0.0101462	total: 2m 57s	remaining: 14m 40s
1679:	learn: 0.0086533	total: 2m 57s	remaining: 14m 39s
1702:	learn: 0.0090851	total: 2m 57s	remaining: 14m 25s
1558:	learn: 0.0108116	total: 2m 57s	remaining: 16m 1s
1678:	learn: 0.0101352	total: 2m 57s	remaining: 14m 40s
1632:	learn: 0.0096632	total: 2m 57s	remaining: 15m 10s
1680:	learn: 0.0086478	total: 2m 57s	remaining: 14m 39s
1703:	learn: 0.0090742	total: 2m 57s	remaining: 14m 25s
1559:	learn: 0.0108042	total: 2m 57s	remaining: 16m 1s
1679:	learn: 0.0101215	total: 2m 57s	remaining: 14m 39s
1633:	learn: 0.0096567	total: 2m 57s	remaining: 15m 10s
1681:	learn: 0.0086354	total: 2m 57s	remaining: 14m 38s
1704:	learn: 0.0090655	total: 2m 57s	remaining: 14m 25s
1560:	learn: 0.0107913	total: 2m 57s	remaining: 16m 1s
1682:	learn: 0.0086265	total: 2m 57s	remaining: 14m 38s
1634:	learn: 0.0096407	total: 2m 57s	remaining: 15m 10s
1705:	learn: 0.0090592	total: 2m 57s	remaining: 14m 25s
1680:	learn: 0.0101078	total: 2m 57s	remaining: 14m 39s
1561:	learn: 0.0107741	total: 2m 57s	remaining: 16m 1s
1683:	learn: 0.0086187	total: 2m 57s	remaining: 14m 38s
1635:	learn: 0.0096276	total: 2m 57s	remaining: 15m 9s
1681:	learn: 0.0100925	total: 2m 57s	remaining: 14m 39s
1706:	learn: 0.0090519	total: 2m 58s	remaining: 14m 24s
1562:	learn: 0.0107590	total: 2m 58s	remaining: 16m 1s
1684:	learn: 0.0086075	total: 2m 58s	remaining: 14m 38s
1682:	learn: 0.0100864	total: 2m 57s	remaining: 14m 39s
1636:	learn: 0.0096156	total: 2m 58s	remaining: 15m 9s
1707:	learn: 0.0090432	total: 2m 58s	remaining: 14m 24s
1685:	learn: 0.0085974	total: 2m 58s	remaining: 14m 38s
1563:	learn: 0.0107474	total: 2m 58s	remaining: 16m 1s
1683:	learn: 0.0100803	total: 2m 58s	remaining: 14m 39s
1637:	learn: 0.0096105	total: 2m 58s	remaining: 15m 9s
1686:	learn: 0.0085884	total: 2m 58s	remaining: 14m 37s
1708:	learn: 0.0090325	total: 2m 58s	remaining: 14m 24s
1684:	learn: 0.0100646	total: 2m 58s	remaining: 14m 39s
1564:	learn: 0.0107344	total: 2m 58s	remaining: 16m
1687:	learn: 0.0085820	total: 2m 58s	remaining: 14m 37s
1638:	learn: 0.0096039	total: 2m 58s	remaining: 15m 9s
1709:	learn: 0.0090277	total: 2m 58s	remaining: 14m 24s
1565:	learn: 0.0107204	total: 2m 58s	remaining: 16m
1639:	learn: 0.0096001	total: 2m 58s	remaining: 15m 9s
1685:	learn: 0.0100539	total: 2m 58s	remaining: 14m 39s
1688:	learn: 0.0085708	total: 2m 58s	remaining: 14m 37s
1710:	learn: 0.0090240	total: 2m 58s	remaining: 14m 24s
1566:	learn: 0.0107023	total: 2m 58s	remaining: 16m
1686:	learn: 0.0100440	total: 2m 58s	remaining: 14m 39s
1640:	learn: 0.0095847	total: 2m 58s	remaining: 15m 9s
1689:	learn: 0.0085624	total: 2m 58s	remaining: 14m 37s
1711:	learn: 0.0090108	total: 2m 58s	remaining: 14m 24s
1687:	learn: 0.0100336	total: 2m 58s	remaining: 14m 38s
1641:	learn: 0.0095728	total: 2m 58s	remaining: 15m 9s
1567:	learn: 0.0106885	total: 2m 58s	remaining: 16m
1712:	learn: 0.0090027	total: 2m 58s	remaining: 14m 24s
1690:	learn: 0.0085481	total: 2m 58s	remaining: 14m 37s
1688:	learn: 0.0100201	total: 2m 58s	remaining: 14m 38s
1642:	learn: 0.0095621	total: 2m 58s	remaining: 15m 8s
1568:	learn: 0.0106741	total: 2m 58s	remaining: 16m
1713:	learn: 0.0089945	total: 2m 58s	remaining: 14m 24s
1689:	learn: 0.0100141	total: 2m 58s	remaining: 14m 38s
1691:	learn: 0.0085393	total: 2m 58s	remaining: 14m 37s
1643:	learn: 0.0095525	total: 2m 58s	remaining: 15m 8s
1692:	learn: 0.0085307	total: 2m 58s	remaining: 14m 37s
1714:	learn: 0.0089806	total: 2m 58s	remaining: 14m 24s
1569:	learn: 0.0106698	total: 2m 58s	remaining: 16m
1690:	learn: 0.0100072	total: 2m 58s	remaining: 14m 38s
1644:	learn: 0.0095444	total: 2m 58s	remaining: 15m 8s
1715:	learn: 0.0089704	total: 2m 58s	remaining: 14m 23s
1693:	learn: 0.0085183	total: 2m 58s	remaining: 14m 37s
1570:	learn: 0.0106606	total: 2m 58s	remaining: 16m
1645:	learn: 0.0095382	total: 2m 58s	remaining: 15m 8s
1691:	learn: 0.0099975	total: 2m 58s	remaining: 14m 38s
1716:	learn: 0.0089619	total: 2m 59s	remaining: 14m 23s
1571:	learn: 0.0106547	total: 2m 59s	remaining: 15m 59s
1694:	learn: 0.0085060	total: 2m 58s	remaining: 14m 36s
1646:	learn: 0.0095335	total: 2m 59s	remaining: 15m 8s
1572:	learn: 0.0106440	total: 2m 59s	remaining: 15m 59s
1692:	learn: 0.0099843	total: 2m 59s	remaining: 14m 38s
1717:	learn: 0.0089554	total: 2m 59s	remaining: 14m 23s
1695:	learn: 0.0084941	total: 2m 59s	remaining: 14m 36s
1647:	learn: 0.0095228	total: 2m 59s	remaining: 15m 7s
1718:	learn: 0.0089471	total: 2m 59s	remaining: 14m 23s
1693:	learn: 0.0099795	total: 2m 59s	remaining: 14m 38s
1648:	learn: 0.0095103	total: 2m 59s	remaining: 15m 7s
1696:	learn: 0.0084854	total: 2m 59s	remaining: 14m 36s
1573:	learn: 0.0106353	total: 2m 59s	remaining: 15m 59s
1694:	learn: 0.0099705	total: 2m 59s	remaining: 14m 38s
1719:	learn: 0.0089383	total: 2m 59s	remaining: 14m 23s
1649:	learn: 0.0094994	total: 2m 59s	remaining: 15m 7s
1574:	learn: 0.0106188	total: 2m 59s	remaining: 15m 59s
1697:	learn: 0.0084782	total: 2m 59s	remaining: 14m 36s
1695:	learn: 0.0099545	total: 2m 59s	remaining: 14m 37s
1720:	learn: 0.0089302	total: 2m 59s	remaining: 14m 23s
1650:	learn: 0.0094908	total: 2m 59s	remaining: 15m 7s
1698:	learn: 0.0084706	total: 2m 59s	remaining: 14m 36s
1575:	learn: 0.0106085	total: 2m 59s	remaining: 15m 59s
1721:	learn: 0.0089232	total: 2m 59s	remaining: 14m 23s
1651:	learn: 0.0094861	total: 2m 59s	remaining: 15m 7s
1696:	learn: 0.0099484	total: 2m 59s	remaining: 14m 37s
1699:	learn: 0.0084586	total: 2m 59s	remaining: 14m 36s
1652:	learn: 0.0094765	total: 2m 59s	remaining: 15m 6s
1722:	learn: 0.0089082	total: 2m 59s	remaining: 14m 22s
1576:	learn: 0.0105942	total: 2m 59s	remaining: 15m 59s
1697:	learn: 0.0099395	total: 2m 59s	remaining: 14m 37s
1700:	learn: 0.0084460	total: 2m 59s	remaining: 14m 36s
1723:	learn: 0.0089040	total: 2m 59s	remaining: 14m 22s
1653:	learn: 0.0094627	total: 2m 59s	remaining: 15m 6s
1577:	learn: 0.0105853	total: 2m 59s	remaining: 15m 59s
1698:	learn: 0.0099300	total: 2m 59s	remaining: 14m 37s
1701:	learn: 0.0084426	total: 2m 59s	remaining: 14m 36s
1724:	learn: 0.0088949	total: 2m 59s	remaining: 14m 22s
1578:	learn: 0.0105759	total: 2m 59s	remaining: 15m 58s
1699:	learn: 0.0099152	total: 2m 59s	remaining: 14m 37s
1702:	learn: 0.0084359	total: 2m 59s	remaining: 14m 35s
1654:	learn: 0.0094506	total: 2m 59s	remaining: 15m 6s
1725:	learn: 0.0088851	total: 2m 59s	remaining: 14m 22s
1579:	learn: 0.0105598	total: 2m 59s	remaining: 15m 58s
1700:	learn: 0.0099044	total: 2m 59s	remaining: 14m 37s
1703:	learn: 0.0084289	total: 2m 59s	remaining: 14m 35s
1655:	learn: 0.0094422	total: 2m 59s	remaining: 15m 6s
1726:	learn: 0.0088773	total: 3m	remaining: 14m 22s
1580:	learn: 0.0105565	total: 3m	remaining: 15m 58s
1701:	learn: 0.0098856	total: 2m 59s	remaining: 14m 37s
1704:	learn: 0.0084205	total: 2m 59s	remaining: 14m 35s
1727:	learn: 0.0088706	total: 3m	remaining: 14m 22s
1702:	learn: 0.0098762	total: 2m 59s	remaining: 14m 36s
1656:	learn: 0.0094310	total: 3m	remaining: 15m 6s
1581:	learn: 0.0105460	total: 3m	remaining: 15m 58s
1705:	learn: 0.0084099	total: 3m	remaining: 14m 35s
1657:	learn: 0.0094244	total: 3m	remaining: 15m 6s
1728:	learn: 0.0088596	total: 3m	remaining: 14m 21s
1703:	learn: 0.0098635	total: 3m	remaining: 14m 36s
1582:	learn: 0.0105388	total: 3m	remaining: 15m 58s
1706:	learn: 0.0083974	total: 3m	remaining: 14m 35s
1658:	learn: 0.0094170	total: 3m	remaining: 15m 6s
1729:	learn: 0.0088511	total: 3m	remaining: 14m 21s
1704:	learn: 0.0098533	total: 3m	remaining: 14m 36s
1707:	learn: 0.0083832	total: 3m	remaining: 14m 35s
1583:	learn: 0.0105274	total: 3m	remaining: 15m 58s
1730:	learn: 0.0088424	total: 3m	remaining: 14m 21s
1659:	learn: 0.0094071	total: 3m	remaining: 15m 6s
1705:	learn: 0.0098455	total: 3m	remaining: 14m 36s
1708:	learn: 0.0083716	total: 3m	remaining: 14m 34s
1584:	learn: 0.0105172	total: 3m	remaining: 15m 58s
1660:	learn: 0.0093965	total: 3m	remaining: 15m 5s
1731:	learn: 0.0088329	total: 3m	remaining: 14m 21s
1709:	learn: 0.0083582	total: 3m	remaining: 14m 34s
1585:	learn: 0.0105072	total: 3m	remaining: 15m 57s
1706:	learn: 0.0098330	total: 3m	remaining: 14m 36s
1732:	learn: 0.0088227	total: 3m	remaining: 14m 21s
1661:	learn: 0.0093827	total: 3m	remaining: 15m 5s
1710:	learn: 0.0083526	total: 3m	remaining: 14m 34s
1707:	learn: 0.0098238	total: 3m	remaining: 14m 36s
1586:	learn: 0.0104954	total: 3m	remaining: 15m 57s
1733:	learn: 0.0088133	total: 3m	remaining: 14m 21s
1662:	learn: 0.0093709	total: 3m	remaining: 15m 5s
1711:	learn: 0.0083457	total: 3m	remaining: 14m 34s
1708:	learn: 0.0098173	total: 3m	remaining: 14m 36s
1587:	learn: 0.0104867	total: 3m	remaining: 15m 57s
1734:	learn: 0.0088063	total: 3m	remaining: 14m 21s
1712:	learn: 0.0083318	total: 3m	remaining: 14m 34s
1663:	learn: 0.0093613	total: 3m	remaining: 15m 5s
1735:	learn: 0.0088000	total: 3m	remaining: 14m 20s
1588:	learn: 0.0104776	total: 3m	remaining: 15m 57s
1709:	learn: 0.0098084	total: 3m	remaining: 14m 36s
1713:	learn: 0.0083264	total: 3m	remaining: 14m 34s
1664:	learn: 0.0093532	total: 3m	remaining: 15m 5s
1736:	learn: 0.0087928	total: 3m	remaining: 14m 20s
1710:	learn: 0.0097982	total: 3m	remaining: 14m 36s
1589:	learn: 0.0104663	total: 3m	remaining: 15m 57s
1737:	learn: 0.0087847	total: 3m 1s	remaining: 14m 20s
1714:	learn: 0.0083199	total: 3m	remaining: 14m 34s
1665:	learn: 0.0093472	total: 3m	remaining: 15m 5s
1711:	learn: 0.0097927	total: 3m	remaining: 14m 36s
1590:	learn: 0.0104507	total: 3m 1s	remaining: 15m 57s
1738:	learn: 0.0087746	total: 3m 1s	remaining: 14m 20s
1666:	learn: 0.0093436	total: 3m 1s	remaining: 15m 5s
1715:	learn: 0.0083097	total: 3m 1s	remaining: 14m 34s
1712:	learn: 0.0097845	total: 3m 1s	remaining: 14m 35s
1739:	learn: 0.0087662	total: 3m 1s	remaining: 14m 20s
1591:	learn: 0.0104423	total: 3m 1s	remaining: 15m 57s
1716:	learn: 0.0083024	total: 3m 1s	remaining: 14m 33s
1713:	learn: 0.0097736	total: 3m 1s	remaining: 14m 35s
1667:	learn: 0.0093340	total: 3m 1s	remaining: 15m 5s
1740:	learn: 0.0087565	total: 3m 1s	remaining: 14m 20s
1717:	learn: 0.0082930	total: 3m 1s	remaining: 14m 33s
1592:	learn: 0.0104291	total: 3m 1s	remaining: 15m 56s
1714:	learn: 0.0097597	total: 3m 1s	remaining: 14m 35s
1668:	learn: 0.0093295	total: 3m 1s	remaining: 15m 5s
1741:	learn: 0.0087454	total: 3m 1s	remaining: 14m 19s
1718:	learn: 0.0082863	total: 3m 1s	remaining: 14m 33s
1669:	learn: 0.0093215	total: 3m 1s	remaining: 15m 4s
1593:	learn: 0.0104255	total: 3m 1s	remaining: 15m 56s
1715:	learn: 0.0097496	total: 3m 1s	remaining: 14m 35s
1742:	learn: 0.0087341	total: 3m 1s	remaining: 14m 19s
1719:	learn: 0.0082789	total: 3m 1s	remaining: 14m 33s
1670:	learn: 0.0093103	total: 3m 1s	remaining: 15m 4s
1594:	learn: 0.0104167	total: 3m 1s	remaining: 15m 56s
1743:	learn: 0.0087294	total: 3m 1s	remaining: 14m 19s
1716:	learn: 0.0097426	total: 3m 1s	remaining: 14m 35s
1720:	learn: 0.0082716	total: 3m 1s	remaining: 14m 33s
1744:	learn: 0.0087212	total: 3m 1s	remaining: 14m 19s
1671:	learn: 0.0092964	total: 3m 1s	remaining: 15m 4s
1595:	learn: 0.0104041	total: 3m 1s	remaining: 15m 56s
1717:	learn: 0.0097304	total: 3m 1s	remaining: 14m 35s
1721:	learn: 0.0082637	total: 3m 1s	remaining: 14m 33s
1745:	learn: 0.0087114	total: 3m 1s	remaining: 14m 19s
1596:	learn: 0.0103906	total: 3m 1s	remaining: 15m 56s
1672:	learn: 0.0092904	total: 3m 1s	remaining: 15m 4s
1718:	learn: 0.0097251	total: 3m 1s	remaining: 14m 35s
1746:	learn: 0.0087039	total: 3m 1s	remaining: 14m 19s
1722:	learn: 0.0082570	total: 3m 1s	remaining: 14m 33s
1597:	learn: 0.0103746	total: 3m 1s	remaining: 15m 56s
1719:	learn: 0.0097194	total: 3m 1s	remaining: 14m 34s
1673:	learn: 0.0092856	total: 3m 1s	remaining: 15m 4s
1723:	learn: 0.0082502	total: 3m 1s	remaining: 14m 33s
1747:	learn: 0.0086994	total: 3m 1s	remaining: 14m 19s
1598:	learn: 0.0103659	total: 3m 1s	remaining: 15m 55s
1720:	learn: 0.0097094	total: 3m 1s	remaining: 14m 34s
1674:	learn: 0.0092776	total: 3m 1s	remaining: 15m 4s
1724:	learn: 0.0082403	total: 3m 1s	remaining: 14m 32s
1599:	learn: 0.0103620	total: 3m 2s	remaining: 15m 55s
1721:	learn: 0.0097025	total: 3m 1s	remaining: 14m 34s
1748:	learn: 0.0086943	total: 3m 2s	remaining: 14m 18s
1675:	learn: 0.0092661	total: 3m 2s	remaining: 15m 4s
1600:	learn: 0.0103509	total: 3m 2s	remaining: 15m 55s
1722:	learn: 0.0096923	total: 3m 2s	remaining: 14m 34s
1725:	learn: 0.0082313	total: 3m 2s	remaining: 14m 32s
1749:	learn: 0.0086879	total: 3m 2s	remaining: 14m 18s
1676:	learn: 0.0092548	total: 3m 2s	remaining: 15m 4s
1601:	learn: 0.0103417	total: 3m 2s	remaining: 15m 55s
1723:	learn: 0.0096846	total: 3m 2s	remaining: 14m 34s
1726:	learn: 0.0082261	total: 3m 2s	remaining: 14m 32s
1677:	learn: 0.0092429	total: 3m 2s	remaining: 15m 3s
1750:	learn: 0.0086818	total: 3m 2s	remaining: 14m 18s
1602:	learn: 0.0103361	total: 3m 2s	remaining: 15m 54s
1724:	learn: 0.0096700	total: 3m 2s	remaining: 14m 34s
1727:	learn: 0.0082185	total: 3m 2s	remaining: 14m 32s
1678:	learn: 0.0092366	total: 3m 2s	remaining: 15m 3s
1751:	learn: 0.0086737	total: 3m 2s	remaining: 14m 18s
1603:	learn: 0.0103297	total: 3m 2s	remaining: 15m 54s
1725:	learn: 0.0096570	total: 3m 2s	remaining: 14m 34s
1728:	learn: 0.0082097	total: 3m 2s	remaining: 14m 32s
1679:	learn: 0.0092265	total: 3m 2s	remaining: 15m 3s
1752:	learn: 0.0086644	total: 3m 2s	remaining: 14m 18s
1604:	learn: 0.0103212	total: 3m 2s	remaining: 15m 54s
1726:	learn: 0.0096394	total: 3m 2s	remaining: 14m 33s
1753:	learn: 0.0086570	total: 3m 2s	remaining: 14m 18s
1729:	learn: 0.0082020	total: 3m 2s	remaining: 14m 32s
1680:	learn: 0.0092151	total: 3m 2s	remaining: 15m 3s
1727:	learn: 0.0096220	total: 3m 2s	remaining: 14m 33s
1605:	learn: 0.0103084	total: 3m 2s	remaining: 15m 54s
1754:	learn: 0.0086488	total: 3m 2s	remaining: 14m 18s
1730:	learn: 0.0081891	total: 3m 2s	remaining: 14m 32s
1681:	learn: 0.0092093	total: 3m 2s	remaining: 15m 3s
1728:	learn: 0.0096123	total: 3m 2s	remaining: 14m 33s
1606:	learn: 0.0102975	total: 3m 2s	remaining: 15m 54s
1755:	learn: 0.0086405	total: 3m 2s	remaining: 14m 18s
1731:	learn: 0.0081772	total: 3m 2s	remaining: 14m 32s
1682:	learn: 0.0092026	total: 3m 2s	remaining: 15m 3s
1729:	learn: 0.0095980	total: 3m 2s	remaining: 14m 33s
1607:	learn: 0.0102876	total: 3m 2s	remaining: 15m 54s
1756:	learn: 0.0086332	total: 3m 2s	remaining: 14m 17s
1683:	learn: 0.0091949	total: 3m 2s	remaining: 15m 2s
1732:	learn: 0.0081662	total: 3m 2s	remaining: 14m 32s
1730:	learn: 0.0095872	total: 3m 2s	remaining: 14m 33s
1757:	learn: 0.0086291	total: 3m 2s	remaining: 14m 17s
1608:	learn: 0.0102748	total: 3m 2s	remaining: 15m 54s
1684:	learn: 0.0091825	total: 3m 2s	remaining: 15m 2s
1733:	learn: 0.0081597	total: 3m 2s	remaining: 14m 31s
1731:	learn: 0.0095740	total: 3m 2s	remaining: 14m 33s
1758:	learn: 0.0086219	total: 3m 3s	remaining: 14m 17s
1685:	learn: 0.0091784	total: 3m 3s	remaining: 15m 2s
1734:	learn: 0.0081522	total: 3m 3s	remaining: 14m 31s
1609:	learn: 0.0102661	total: 3m 3s	remaining: 15m 54s
1732:	learn: 0.0095656	total: 3m 3s	remaining: 14m 33s
1686:	learn: 0.0091642	total: 3m 3s	remaining: 15m 2s
1759:	learn: 0.0086134	total: 3m 3s	remaining: 14m 17s

1735:	learn: 0.0081405	total: 3m 3s	remaining: 14m 31s
1610:	learn: 0.0102578	total: 3m 3s	remaining: 15m 54s
1687:	learn: 0.0091607	total: 3m 3s	remaining: 15m 2s
1733:	learn: 0.0095600	total: 3m 3s	remaining: 14m 33s
1760:	learn: 0.0086004	total: 3m 3s	remaining: 14m 17s
1736:	learn: 0.0081304	total: 3m 3s	remaining: 14m 31s
1734:	learn: 0.0095549	total: 3m 3s	remaining: 14m 32s
1761:	learn: 0.0085951	total: 3m 3s	remaining: 14m 17s
1688:	learn: 0.0091494	total: 3m 3s	remaining: 15m 2s
1611:	learn: 0.0102456	total: 3m 3s	remaining: 15m 54s
1737:	learn: 0.0081204	total: 3m 3s	remaining: 14m 31s
1735:	learn: 0.0095450	total: 3m 3s	remaining: 14m 32s
1762:	learn: 0.0085880	total: 3m 3s	remaining: 14m 17s
1612:	learn: 0.0102425	total: 3m 3s	remaining: 15m 53s
1738:	learn: 0.0081129	total: 3m 3s	remaining: 14m 31s
1689:	learn: 0.0091454	total: 3m 3s	remaining: 15m 2s
1690:	learn: 0.0091353	total: 3m 3s	remaining: 15m 1s
1763:	learn: 0.0085810	total: 3m 3s	remaining: 14m 17s
1736:	learn: 0.0095314	total: 3m 3s	remaining: 14m 32s
1739:	learn: 0.0081049	total: 3m 3s	remaining: 14m 30s
1613:	learn: 0.0102337	total: 3m 3s	remaining: 15m 53s
1691:	learn: 0.0091296	total: 3m 3s	remaining: 15m 1s
1740:	learn: 0.0080935	total: 3m 3s	remaining: 14m 30s
1764:	learn: 0.0085750	total: 3m 3s	remaining: 14m 16s
1737:	learn: 0.0095241	total: 3m 3s	remaining: 14m 32s
1614:	learn: 0.0102211	total: 3m 3s	remaining: 15m 53s
1741:	learn: 0.0080847	total: 3m 3s	remaining: 14m 30s
1692:	learn: 0.0091205	total: 3m 3s	remaining: 15m 1s
1765:	learn: 0.0085663	total: 3m 3s	remaining: 14m 16s
1738:	learn: 0.0095146	total: 3m 3s	remaining: 14m 32s
1615:	learn: 0.0102108	total: 3m 3s	remaining: 15m 53s
1742:	learn: 0.0080782	total: 3m 3s	remaining: 14m 30s
1693:	learn: 0.0091150	total: 3m 3s	remaining: 15m 1s
1739:	learn: 0.0095090	total: 3m 3s	remaining: 14m 32s
1766:	learn: 0.0085603	total: 3m 3s	remaining: 14m 16s
1616:	learn: 0.0102068	total: 3m 3s	remaining: 15m 53s
1743:	learn: 0.0080693	total: 3m 3s	remaining: 14m 30s
1740:	learn: 0.0095036	total: 3m 3s	remaining: 14m 32s
1694:	learn: 0.0091016	total: 3m 3s	remaining: 15m 1s
1767:	learn: 0.0085481	total: 3m 3s	remaining: 14m 16s
1617:	learn: 0.0101943	total: 3m 3s	remaining: 15m 53s
1744:	learn: 0.0080599	total: 3m 3s	remaining: 14m 30s
1741:	learn: 0.0094954	total: 3m 3s	remaining: 14m 31s
1695:	learn: 0.0090900	total: 3m 4s	remaining: 15m 1s
1768:	learn: 0.0085429	total: 3m 4s	remaining: 14m 16s
1618:	learn: 0.0101865	total: 3m 4s	remaining: 15m 53s
1745:	learn: 0.0080533	total: 3m 4s	remaining: 14m 29s
1742:	learn: 0.0094875	total: 3m 4s	remaining: 14m 31s
1769:	learn: 0.0085318	total: 3m 4s	remaining: 14m 16s
1696:	learn: 0.0090842	total: 3m 4s	remaining: 15m 1s
1743:	learn: 0.0094781	total: 3m 4s	remaining: 14m 31s
1746:	learn: 0.0080418	total: 3m 4s	remaining: 14m 29s
1619:	learn: 0.0101730	total: 3m 4s	remaining: 15m 53s
1770:	learn: 0.0085250	total: 3m 4s	remaining: 14m 16s
1697:	learn: 0.0090776	total: 3m 4s	remaining: 15m
1744:	learn: 0.0094654	total: 3m 4s	remaining: 14m 31s
1747:	learn: 0.0080349	total: 3m 4s	remaining: 14m 29s
1745:	learn: 0.0094503	total: 3m 4s	remaining: 14m 31s
1620:	learn: 0.0101634	total: 3m 4s	remaining: 15m 53s
1771:	learn: 0.0085172	total: 3m 4s	remaining: 14m 16s
1698:	learn: 0.0090728	total: 3m 4s	remaining: 15m
1746:	learn: 0.0094411	total: 3m 4s	remaining: 14m 30s
1748:	learn: 0.0080237	total: 3m 4s	remaining: 14m 29s
1621:	learn: 0.0101548	total: 3m 4s	remaining: 15m 52s
1772:	learn: 0.0085080	total: 3m 4s	remaining: 14m 16s
1699:	learn: 0.0090681	total: 3m 4s	remaining: 15m
1747:	learn: 0.0094315	total: 3m 4s	remaining: 14m 30s
1749:	learn: 0.0080119	total: 3m 4s	remaining: 14m 29s
1622:	learn: 0.0101418	total: 3m 4s	remaining: 15m 52s
1700:	learn: 0.0090620	total: 3m 4s	remaining: 15m
1773:	learn: 0.0085006	total: 3m 4s	remaining: 14m 16s
1748:	learn: 0.0094262	total: 3m 4s	remaining: 14m 30s
1623:	learn: 0.0101318	total: 3m 4s	remaining: 15m 52s
1750:	learn: 0.0080013	total: 3m 4s	remaining: 14m 29s
1701:	learn: 0.0090531	total: 3m 4s	remaining: 15m
1749:	learn: 0.0094200	total: 3m 4s	remaining: 14m 30s
1774:	learn: 0.0084938	total: 3m 4s	remaining: 14m 15s
1624:	learn: 0.0101233	total: 3m 4s	remaining: 15m 52s
1751:	learn: 0.0079950	total: 3m 4s	remaining: 14m 29s
1750:	learn: 0.0094143	total: 3m 4s	remaining: 14m 30s
1775:	learn: 0.0084813	total: 3m 4s	remaining: 14m 15s
1702:	learn: 0.0090500	total: 3m 4s	remaining: 15m
1751:	learn: 0.0093982	total: 3m 4s	remaining: 14m 29s
1776:	learn: 0.0084692	total: 3m 4s	remaining: 14m 15s
1625:	learn: 0.0101110	total: 3m 4s	remaining: 15m 52s
1752:	learn: 0.0079824	total: 3m 4s	remaining: 14m 29s
1703:	learn: 0.0090436	total: 3m 4s	remaining: 15m
1777:	learn: 0.0084627	total: 3m 4s	remaining: 14m 15s
1752:	learn: 0.0093891	total: 3m 4s	remaining: 14m 29s
1753:	learn: 0.0079738	total: 3m 4s	remaining: 14m 29s
1704:	learn: 0.0090362	total: 3m 5s	remaining: 15m
1778:	learn: 0.0084559	total: 3m 5s	remaining: 14m 15s
1626:	learn: 0.0101023	total: 3m 5s	remaining: 15m 52s
1753:	learn: 0.0093799	total: 3m 4s	remaining: 14m 29s
1754:	learn: 0.0079683	total: 3m 4s	remaining: 14m 29s
1705:	learn: 0.0090262	total: 3m 5s	remaining: 14m 59s
1779:	learn: 0.0084509	total: 3m 5s	remaining: 14m 15s
1627:	learn: 0.0100883	total: 3m 5s	remaining: 15m 52s
1755:	learn: 0.0079573	total: 3m 5s	remaining: 14m 28s
1754:	learn: 0.0093730	total: 3m 5s	remaining: 14m 29s
1706:	learn: 0.0090167	total: 3m 5s	remaining: 14m 59s
1780:	learn: 0.0084443	total: 3m 5s	remaining: 14m 14s
1756:	learn: 0.0079458	total: 3m 5s	remaining: 14m 28s
1755:	learn: 0.0093680	total: 3m 5s	remaining: 14m 29s
1628:	learn: 0.0100731	total: 3m 5s	remaining: 15m 52s
1707:	learn: 0.0090099	total: 3m 5s	remaining: 14m 59s
1781:	learn: 0.0084367	total: 3m 5s	remaining: 14m 14s
1757:	learn: 0.0079396	total: 3m 5s	remaining: 14m 28s
1756:	learn: 0.0093557	total: 3m 5s	remaining: 14m 29s
1629:	learn: 0.0100639	total: 3m 5s	remaining: 15m 52s
1708:	learn: 0.0089959	total: 3m 5s	remaining: 14m 59s
1782:	learn: 0.0084304	total: 3m 5s	remaining: 14m 14s
1758:	learn: 0.0079335	total: 3m 5s	remaining: 14m 28s
1709:	learn: 0.0089897	total: 3m 5s	remaining: 14m 59s
1630:	learn: 0.0100577	total: 3m 5s	remaining: 15m 51s
1757:	learn: 0.0093516	total: 3m 5s	remaining: 14m 29s
1783:	learn: 0.0084216	total: 3m 5s	remaining: 14m 14s
1759:	learn: 0.0079267	total: 3m 5s	remaining: 14m 28s
1710:	learn: 0.0089784	total: 3m 5s	remaining: 14m 58s
1631:	learn: 0.0100450	total: 3m 5s	remaining: 15m 51s
1758:	learn: 0.0093454	total: 3m 5s	remaining: 14m 29s
1784:	learn: 0.0084137	total: 3m 5s	remaining: 14m 14s
1632:	learn: 0.0100327	total: 3m 5s	remaining: 15m 51s
1760:	learn: 0.0079155	total: 3m 5s	remaining: 14m 28s
1711:	learn: 0.0089680	total: 3m 5s	remaining: 14m 58s
1759:	learn: 0.0093409	total: 3m 5s	remaining: 14m 28s
1785:	learn: 0.0084059	total: 3m 5s	remaining: 14m 14s
1761:	learn: 0.0079086	total: 3m 5s	remaining: 14m 28s
1760:	learn: 0.0093272	total: 3m 5s	remaining: 14m 28s
1786:	learn: 0.0084021	total: 3m 5s	remaining: 14m 14s
1633:	learn: 0.0100241	total: 3m 5s	remaining: 15m 51s
1712:	learn: 0.0089616	total: 3m 5s	remaining: 14m 58s
1762:	learn: 0.0079024	total: 3m 5s	remaining: 14m 27s
1787:	learn: 0.0083944	total: 3m 5s	remaining: 14m 13s
1761:	learn: 0.0093191	total: 3m 5s	remaining: 14m 28s
1634:	learn: 0.0100168	total: 3m 5s	remaining: 15m 51s
1713:	learn: 0.0089538	total: 3m 5s	remaining: 14m 58s
1788:	learn: 0.0083883	total: 3m 5s	remaining: 14m 13s
1763:	learn: 0.0078901	total: 3m 5s	remaining: 14m 27s
1762:	learn: 0.0093102	total: 3m 5s	remaining: 14m 28s
1635:	learn: 0.0100075	total: 3m 6s	remaining: 15m 50s
1714:	learn: 0.0089461	total: 3m 6s	remaining: 14m 58s
1764:	learn: 0.0078818	total: 3m 5s	remaining: 14m 27s
1636:	learn: 0.0099936	total: 3m 6s	remaining: 15m 50s
1763:	learn: 0.0093022	total: 3m 5s	remaining: 14m 28s
1789:	learn: 0.0083817	total: 3m 6s	remaining: 14m 13s
1715:	learn: 0.0089350	total: 3m 6s	remaining: 14m 58s
1765:	learn: 0.0078709	total: 3m 6s	remaining: 14m 27s
1764:	learn: 0.0092951	total: 3m 6s	remaining: 14m 28s
1637:	learn: 0.0099810	total: 3m 6s	remaining: 15m 50s
1790:	learn: 0.0083760	total: 3m 6s	remaining: 14m 13s
1766:	learn: 0.0078589	total: 3m 6s	remaining: 14m 27s
1765:	learn: 0.0092871	total: 3m 6s	remaining: 14m 27s
1716:	learn: 0.0089243	total: 3m 6s	remaining: 14m 58s
1638:	learn: 0.0099749	total: 3m 6s	remaining: 15m 50s
1791:	learn: 0.0083700	total: 3m 6s	remaining: 14m 13s
1767:	learn: 0.0078516	total: 3m 6s	remaining: 14m 27s
1766:	learn: 0.0092812	total: 3m 6s	remaining: 14m 27s
1717:	learn: 0.0089170	total: 3m 6s	remaining: 14m 58s
1639:	learn: 0.0099655	total: 3m 6s	remaining: 15m 50s
1792:	learn: 0.0083604	total: 3m 6s	remaining: 14m 13s
1768:	learn: 0.0078410	total: 3m 6s	remaining: 14m 27s
1718:	learn: 0.0089093	total: 3m 6s	remaining: 14m 58s
1767:	learn: 0.0092703	total: 3m 6s	remaining: 14m 27s
1640:	learn: 0.0099626	total: 3m 6s	remaining: 15m 50s
1793:	learn: 0.0083554	total: 3m 6s	remaining: 14m 13s
1769:	learn: 0.0078330	total: 3m 6s	remaining: 14m 26s
1719:	learn: 0.0089051	total: 3m 6s	remaining: 14m 57s
1768:	learn: 0.0092633	total: 3m 6s	remaining: 14m 27s
1641:	learn: 0.0099504	total: 3m 6s	remaining: 15m 49s
1770:	learn: 0.0078275	total: 3m 6s	remaining: 14m 26s
1794:	learn: 0.0083488	total: 3m 6s	remaining: 14m 13s
1720:	learn: 0.0088965	total: 3m 6s	remaining: 14m 57s
1769:	learn: 0.0092606	total: 3m 6s	remaining: 14m 27s
1642:	learn: 0.0099417	total: 3m 6s	remaining: 15m 49s
1771:	learn: 0.0078217	total: 3m 6s	remaining: 14m 26s
1795:	learn: 0.0083409	total: 3m 6s	remaining: 14m 13s
1721:	learn: 0.0088890	total: 3m 6s	remaining: 14m 57s
1770:	learn: 0.0092517	total: 3m 6s	remaining: 14m 27s
1772:	learn: 0.0078102	total: 3m 6s	remaining: 14m 26s
1643:	learn: 0.0099385	total: 3m 6s	remaining: 15m 49s
1796:	learn: 0.0083370	total: 3m 6s	remaining: 14m 12s
1722:	learn: 0.0088818	total: 3m 6s	remaining: 14m 57s
1773:	learn: 0.0077998	total: 3m 6s	remaining: 14m 26s
1797:	learn: 0.0083324	total: 3m 6s	remaining: 14m 12s
1771:	learn: 0.0092434	total: 3m 6s	remaining: 14m 27s
1644:	learn: 0.0099289	total: 3m 6s	remaining: 15m 49s
1798:	learn: 0.0083271	total: 3m 7s	remaining: 14m 12s
1723:	learn: 0.0088788	total: 3m 6s	remaining: 14m 57s
1774:	learn: 0.0077880	total: 3m 6s	remaining: 14m 26s
1772:	learn: 0.0092301	total: 3m 6s	remaining: 14m 27s
1645:	learn: 0.0099187	total: 3m 7s	remaining: 15m 49s
1799:	learn: 0.0083199	total: 3m 7s	remaining: 14m 12s
1724:	learn: 0.0088726	total: 3m 7s	remaining: 14m 57s
1773:	learn: 0.0092198	total: 3m 6s	remaining: 14m 27s
1775:	learn: 0.0077813	total: 3m 7s	remaining: 14m 26s
1646:	learn: 0.0099035	total: 3m 7s	remaining: 15m 49s
1800:	learn: 0.0083135	total: 3m 7s	remaining: 14m 12s
1774:	learn: 0.0092113	total: 3m 7s	remaining: 14m 27s
1725:	learn: 0.0088612	total: 3m 7s	remaining: 14m 57s
1776:	learn: 0.0077732	total: 3m 7s	remaining: 14m 25s
1647:	learn: 0.0098948	total: 3m 7s	remaining: 15m 48s
1801:	learn: 0.0083074	total: 3m 7s	remaining: 14m 12s
1775:	learn: 0.0092025	total: 3m 7s	remaining: 14m 26s
1726:	learn: 0.0088521	total: 3m 7s	remaining: 14m 57s
1777:	learn: 0.0077684	total: 3m 7s	remaining: 14m 25s
1648:	learn: 0.0098908	total: 3m 7s	remaining: 15m 48s
1802:	learn: 0.0083008	total: 3m 7s	remaining: 14m 11s
1776:	learn: 0.0091916	total: 3m 7s	remaining: 14m 26s
1778:	learn: 0.0077582	total: 3m 7s	remaining: 14m 25s
1727:	learn: 0.0088459	total: 3m 7s	remaining: 14m 57s
1777:	learn: 0.0091867	total: 3m 7s	remaining: 14m 26s
1803:	learn: 0.0082948	total: 3m 7s	remaining: 14m 11s
1779:	learn: 0.0077502	total: 3m 7s	remaining: 14m 25s
1649:	learn: 0.0098822	total: 3m 7s	remaining: 15m 48s
1728:	learn: 0.0088400	total: 3m 7s	remaining: 14m 57s
1778:	learn: 0.0091779	total: 3m 7s	remaining: 14m 26s
1804:	learn: 0.0082909	total: 3m 7s	remaining: 14m 11s
1780:	learn: 0.0077442	total: 3m 7s	remaining: 14m 25s
1650:	learn: 0.0098708	total: 3m 7s	remaining: 15m 48s
1729:	learn: 0.0088353	total: 3m 7s	remaining: 14m 56s
1805:	learn: 0.0082823	total: 3m 7s	remaining: 14m 11s
1781:	learn: 0.0077386	total: 3m 7s	remaining: 14m 25s
1779:	learn: 0.0091726	total: 3m 7s	remaining: 14m 26s
1651:	learn: 0.0098627	total: 3m 7s	remaining: 15m 48s
1782:	learn: 0.0077313	total: 3m 7s	remaining: 14m 24s
1806:	learn: 0.0082732	total: 3m 7s	remaining: 14m 11s
1730:	learn: 0.0088282	total: 3m 7s	remaining: 14m 56s
1780:	learn: 0.0091620	total: 3m 7s	remaining: 14m 26s
1783:	learn: 0.0077212	total: 3m 7s	remaining: 14m 24s
1652:	learn: 0.0098592	total: 3m 7s	remaining: 15m 48s
1807:	learn: 0.0082674	total: 3m 7s	remaining: 14m 11s
1731:	learn: 0.0088192	total: 3m 7s	remaining: 14m 56s
1781:	learn: 0.0091566	total: 3m 7s	remaining: 14m 25s
1784:	learn: 0.0077129	total: 3m 7s	remaining: 14m 24s
1653:	learn: 0.0098467	total: 3m 7s	remaining: 15m 48s
1732:	learn: 0.0088063	total: 3m 7s	remaining: 14m 56s
1808:	learn: 0.0082581	total: 3m 7s	remaining: 14m 11s
1782:	learn: 0.0091508	total: 3m 7s	remaining: 14m 25s
1654:	learn: 0.0098354	total: 3m 8s	remaining: 15m 48s
1785:	learn: 0.0077058	total: 3m 7s	remaining: 14m 24s
1733:	learn: 0.0088034	total: 3m 8s	remaining: 14m 56s
1809:	learn: 0.0082502	total: 3m 8s	remaining: 14m 11s
1783:	learn: 0.0091376	total: 3m 7s	remaining: 14m 25s
1655:	learn: 0.0098296	total: 3m 8s	remaining: 15m 47s
1734:	learn: 0.0087964	total: 3m 8s	remaining: 14m 56s
1786:	learn: 0.0076989	total: 3m 8s	remaining: 14m 24s
1810:	learn: 0.0082421	total: 3m 8s	remaining: 14m 11s
1784:	learn: 0.0091295	total: 3m 8s	remaining: 14m 25s
1656:	learn: 0.0098197	total: 3m 8s	remaining: 15m 47s
1787:	learn: 0.0076931	total: 3m 8s	remaining: 14m 24s
1735:	learn: 0.0087837	total: 3m 8s	remaining: 14m 56s
1785:	learn: 0.0091225	total: 3m 8s	remaining: 14m 25s
1657:	learn: 0.0098069	total: 3m 8s	remaining: 15m 47s
1811:	learn: 0.0082357	total: 3m 8s	remaining: 14m 11s
1736:	learn: 0.0087733	total: 3m 8s	remaining: 14m 55s
1788:	learn: 0.0076853	total: 3m 8s	remaining: 14m 24s
1786:	learn: 0.0091109	total: 3m 8s	remaining: 14m 25s
1812:	learn: 0.0082250	total: 3m 8s	remaining: 14m 10s
1658:	learn: 0.0098036	total: 3m 8s	remaining: 15m 47s
1737:	learn: 0.0087642	total: 3m 8s	remaining: 14m 55s
1813:	learn: 0.0082146	total: 3m 8s	remaining: 14m 10s
1787:	learn: 0.0090978	total: 3m 8s	remaining: 14m 25s
1789:	learn: 0.0076771	total: 3m 8s	remaining: 14m 24s
1659:	learn: 0.0097917	total: 3m 8s	remaining: 15m 47s
1738:	learn: 0.0087568	total: 3m 8s	remaining: 14m 55s
1788:	learn: 0.0090892	total: 3m 8s	remaining: 14m 24s
1814:	learn: 0.0082086	total: 3m 8s	remaining: 14m 10s
1660:	learn: 0.0097774	total: 3m 8s	remaining: 15m 46s
1790:	learn: 0.0076673	total: 3m 8s	remaining: 14m 24s
1789:	learn: 0.0090822	total: 3m 8s	remaining: 14m 24s
1739:	learn: 0.0087495	total: 3m 8s	remaining: 14m 55s
1815:	learn: 0.0082005	total: 3m 8s	remaining: 14m 10s
1661:	learn: 0.0097693	total: 3m 8s	remaining: 15m 46s
1791:	learn: 0.0076604	total: 3m 8s	remaining: 14m 23s
1816:	learn: 0.0081916	total: 3m 8s	remaining: 14m 10s
1790:	learn: 0.0090747	total: 3m 8s	remaining: 14m 24s
1740:	learn: 0.0087467	total: 3m 8s	remaining: 14m 55s
1662:	learn: 0.0097621	total: 3m 8s	remaining: 15m 46s
1792:	learn: 0.0076507	total: 3m 8s	remaining: 14m 23s
1791:	learn: 0.0090661	total: 3m 8s	remaining: 14m 24s
1817:	learn: 0.0081879	total: 3m 8s	remaining: 14m 10s
1741:	learn: 0.0087406	total: 3m 8s	remaining: 14m 55s
1663:	learn: 0.0097553	total: 3m 8s	remaining: 15m 46s
1793:	learn: 0.0076410	total: 3m 8s	remaining: 14m 23s
1818:	learn: 0.0081811	total: 3m 8s	remaining: 14m 9s
1742:	learn: 0.0087340	total: 3m 8s	remaining: 14m 55s
1792:	learn: 0.0090585	total: 3m 8s	remaining: 14m 24s
1664:	learn: 0.0097464	total: 3m 8s	remaining: 15m 46s
1794:	learn: 0.0076313	total: 3m 8s	remaining: 14m 23s
1819:	learn: 0.0081762	total: 3m 9s	remaining: 14m 9s
1743:	learn: 0.0087283	total: 3m 9s	remaining: 14m 55s
1793:	learn: 0.0090515	total: 3m 8s	remaining: 14m 24s
1665:	learn: 0.0097347	total: 3m 9s	remaining: 15m 46s
1820:	learn: 0.0081698	total: 3m 9s	remaining: 14m 9s
1795:	learn: 0.0076217	total: 3m 9s	remaining: 14m 23s
1744:	learn: 0.0087255	total: 3m 9s	remaining: 14m 54s
1794:	learn: 0.0090410	total: 3m 9s	remaining: 14m 24s

1666:	learn: 0.0097316	total: 3m 9s	remaining: 15m 45s
1796:	learn: 0.0076121	total: 3m 9s	remaining: 14m 23s
1821:	learn: 0.0081600	total: 3m 9s	remaining: 14m 9s
1745:	learn: 0.0087195	total: 3m 9s	remaining: 14m 54s
1795:	learn: 0.0090293	total: 3m 9s	remaining: 14m 24s
1797:	learn: 0.0076066	total: 3m 9s	remaining: 14m 23s
1667:	learn: 0.0097234	total: 3m 9s	remaining: 15m 45s
1822:	learn: 0.0081517	total: 3m 9s	remaining: 14m 9s
1746:	learn: 0.0087127	total: 3m 9s	remaining: 14m 54s
1798:	learn: 0.0075988	total: 3m 9s	remaining: 14m 23s
1796:	learn: 0.0090208	total: 3m 9s	remaining: 14m 24s
1668:	learn: 0.0097150	total: 3m 9s	remaining: 15m 45s
1823:	learn: 0.0081461	total: 3m 9s	remaining: 14m 9s
1747:	learn: 0.0087031	total: 3m 9s	remaining: 14m 54s
1799:	learn: 0.0075875	total: 3m 9s	remaining: 14m 22s
1797:	learn: 0.0090152	total: 3m 9s	remaining: 14m 23s
1824:	learn: 0.0081382	total: 3m 9s	remaining: 14m 9s
1669:	learn: 0.0097022	total: 3m 9s	remaining: 15m 45s
1748:	learn: 0.0086976	total: 3m 9s	remaining: 14m 54s
1798:	learn: 0.0090098	total: 3m 9s	remaining: 14m 23s
1800:	learn: 0.0075782	total: 3m 9s	remaining: 14m 22s
1825:	learn: 0.0081338	total: 3m 9s	remaining: 14m 8s
1670:	learn: 0.0096952	total: 3m 9s	remaining: 15m 45s
1749:	learn: 0.0086896	total: 3m 9s	remaining: 14m 54s
1799:	learn: 0.0089970	total: 3m 9s	remaining: 14m 23s
1801:	learn: 0.0075702	total: 3m 9s	remaining: 14m 22s
1826:	learn: 0.0081271	total: 3m 9s	remaining: 14m 8s
1671:	learn: 0.0096878	total: 3m 9s	remaining: 15m 45s
1802:	learn: 0.0075639	total: 3m 9s	remaining: 14m 22s
1750:	learn: 0.0086816	total: 3m 9s	remaining: 14m 53s
1800:	learn: 0.0089853	total: 3m 9s	remaining: 14m 23s
1827:	learn: 0.0081209	total: 3m 9s	remaining: 14m 8s
1672:	learn: 0.0096808	total: 3m 9s	remaining: 15m 45s
1803:	learn: 0.0075584	total: 3m 9s	remaining: 14m 22s
1751:	learn: 0.0086759	total: 3m 9s	remaining: 14m 53s
1801:	learn: 0.0089770	total: 3m 9s	remaining: 14m 23s
1828:	learn: 0.0081135	total: 3m 9s	remaining: 14m 8s
1673:	learn: 0.0096729	total: 3m 9s	remaining: 15m 44s
1752:	learn: 0.0086686	total: 3m 9s	remaining: 14m 53s
1804:	learn: 0.0075492	total: 3m 9s	remaining: 14m 22s
1802:	learn: 0.0089723	total: 3m 9s	remaining: 14m 23s
1829:	learn: 0.0081053	total: 3m 10s	remaining: 14m 8s
1674:	learn: 0.0096644	total: 3m 10s	remaining: 15m 44s
1753:	learn: 0.0086657	total: 3m 10s	remaining: 14m 53s
1830:	learn: 0.0080976	total: 3m 10s	remaining: 14m 8s
1805:	learn: 0.0075418	total: 3m 10s	remaining: 14m 22s
1803:	learn: 0.0089682	total: 3m 10s	remaining: 14m 23s
1675:	learn: 0.0096498	total: 3m 10s	remaining: 15m 44s
1831:	learn: 0.0080893	total: 3m 10s	remaining: 14m 8s
1806:	learn: 0.0075324	total: 3m 10s	remaining: 14m 21s
1754:	learn: 0.0086587	total: 3m 10s	remaining: 14m 53s
1804:	learn: 0.0089639	total: 3m 10s	remaining: 14m 23s
1676:	learn: 0.0096446	total: 3m 10s	remaining: 15m 44s
1832:	learn: 0.0080831	total: 3m 10s	remaining: 14m 7s
1755:	learn: 0.0086533	total: 3m 10s	remaining: 14m 53s
1807:	learn: 0.0075240	total: 3m 10s	remaining: 14m 21s
1805:	learn: 0.0089539	total: 3m 10s	remaining: 14m 23s
1677:	learn: 0.0096329	total: 3m 10s	remaining: 15m 44s
1833:	learn: 0.0080760	total: 3m 10s	remaining: 14m 7s
1756:	learn: 0.0086409	total: 3m 10s	remaining: 14m 53s
1808:	learn: 0.0075164	total: 3m 10s	remaining: 14m 21s
1806:	learn: 0.0089456	total: 3m 10s	remaining: 14m 22s
1678:	learn: 0.0096205	total: 3m 10s	remaining: 15m 43s
1834:	learn: 0.0080667	total: 3m 10s	remaining: 14m 7s
1757:	learn: 0.0086304	total: 3m 10s	remaining: 14m 53s
1809:	learn: 0.0075072	total: 3m 10s	remaining: 14m 21s
1679:	learn: 0.0096083	total: 3m 10s	remaining: 15m 43s
1807:	learn: 0.0089410	total: 3m 10s	remaining: 14m 22s
1810:	learn: 0.0074959	total: 3m 10s	remaining: 14m 21s
1758:	learn: 0.0086250	total: 3m 10s	remaining: 14m 52s
1835:	learn: 0.0080567	total: 3m 10s	remaining: 14m 7s
1680:	learn: 0.0096014	total: 3m 10s	remaining: 15m 43s
1808:	learn: 0.0089286	total: 3m 10s	remaining: 14m 22s
1811:	learn: 0.0074903	total: 3m 10s	remaining: 14m 21s
1759:	learn: 0.0086185	total: 3m 10s	remaining: 14m 52s
1836:	learn: 0.0080496	total: 3m 10s	remaining: 14m 7s
1809:	learn: 0.0089184	total: 3m 10s	remaining: 14m 22s
1681:	learn: 0.0095900	total: 3m 10s	remaining: 15m 43s
1760:	learn: 0.0086124	total: 3m 10s	remaining: 14m 52s
1812:	learn: 0.0074802	total: 3m 10s	remaining: 14m 21s
1837:	learn: 0.0080453	total: 3m 10s	remaining: 14m 7s
1810:	learn: 0.0089116	total: 3m 10s	remaining: 14m 22s
1682:	learn: 0.0095818	total: 3m 10s	remaining: 15m 43s
1761:	learn: 0.0086060	total: 3m 10s	remaining: 14m 52s
1813:	learn: 0.0074714	total: 3m 10s	remaining: 14m 21s
1683:	learn: 0.0095745	total: 3m 10s	remaining: 15m 42s
1838:	learn: 0.0080391	total: 3m 10s	remaining: 14m 7s
1811:	learn: 0.0088988	total: 3m 10s	remaining: 14m 22s
1762:	learn: 0.0086009	total: 3m 10s	remaining: 14m 52s
1814:	learn: 0.0074620	total: 3m 10s	remaining: 14m 20s
1684:	learn: 0.0095674	total: 3m 11s	remaining: 15m 42s
1839:	learn: 0.0080317	total: 3m 11s	remaining: 14m 7s
1763:	learn: 0.0085963	total: 3m 11s	remaining: 14m 52s
1812:	learn: 0.0088907	total: 3m 10s	remaining: 14m 22s
1815:	learn: 0.0074549	total: 3m 11s	remaining: 14m 20s
1685:	learn: 0.0095619	total: 3m 11s	remaining: 15m 42s
1840:	learn: 0.0080240	total: 3m 11s	remaining: 14m 7s
1813:	learn: 0.0088826	total: 3m 11s	remaining: 14m 22s
1764:	learn: 0.0085910	total: 3m 11s	remaining: 14m 52s
1816:	learn: 0.0074499	total: 3m 11s	remaining: 14m 20s
1686:	learn: 0.0095518	total: 3m 11s	remaining: 15m 42s
1841:	learn: 0.0080191	total: 3m 11s	remaining: 14m 7s
1814:	learn: 0.0088702	total: 3m 11s	remaining: 14m 21s
1817:	learn: 0.0074430	total: 3m 11s	remaining: 14m 20s
1765:	learn: 0.0085847	total: 3m 11s	remaining: 14m 51s
1815:	learn: 0.0088634	total: 3m 11s	remaining: 14m 21s
1842:	learn: 0.0080118	total: 3m 11s	remaining: 14m 7s
1687:	learn: 0.0095385	total: 3m 11s	remaining: 15m 42s
1818:	learn: 0.0074348	total: 3m 11s	remaining: 14m 20s
1766:	learn: 0.0085787	total: 3m 11s	remaining: 14m 51s
1816:	learn: 0.0088516	total: 3m 11s	remaining: 14m 21s
1843:	learn: 0.0080068	total: 3m 11s	remaining: 14m 6s
1688:	learn: 0.0095301	total: 3m 11s	remaining: 15m 42s
1819:	learn: 0.0074263	total: 3m 11s	remaining: 14m 20s
1767:	learn: 0.0085731	total: 3m 11s	remaining: 14m 51s
1817:	learn: 0.0088437	total: 3m 11s	remaining: 14m 21s
1844:	learn: 0.0080022	total: 3m 11s	remaining: 14m 6s
1689:	learn: 0.0095218	total: 3m 11s	remaining: 15m 42s
1820:	learn: 0.0074207	total: 3m 11s	remaining: 14m 20s
1768:	learn: 0.0085696	total: 3m 11s	remaining: 14m 51s
1818:	learn: 0.0088357	total: 3m 11s	remaining: 14m 21s
1845:	learn: 0.0079970	total: 3m 11s	remaining: 14m 6s
1821:	learn: 0.0074114	total: 3m 11s	remaining: 14m 20s
1769:	learn: 0.0085601	total: 3m 11s	remaining: 14m 51s
1690:	learn: 0.0095103	total: 3m 11s	remaining: 15m 42s
1819:	learn: 0.0088255	total: 3m 11s	remaining: 14m 21s
1846:	learn: 0.0079895	total: 3m 11s	remaining: 14m 6s
1822:	learn: 0.0074047	total: 3m 11s	remaining: 14m 19s
1691:	learn: 0.0095009	total: 3m 11s	remaining: 15m 41s
1770:	learn: 0.0085479	total: 3m 11s	remaining: 14m 51s
1820:	learn: 0.0088170	total: 3m 11s	remaining: 14m 21s
1847:	learn: 0.0079825	total: 3m 11s	remaining: 14m 6s
1823:	learn: 0.0073958	total: 3m 11s	remaining: 14m 19s
1692:	learn: 0.0094963	total: 3m 11s	remaining: 15m 41s
1821:	learn: 0.0088057	total: 3m 11s	remaining: 14m 20s
1771:	learn: 0.0085423	total: 3m 11s	remaining: 14m 51s
1848:	learn: 0.0079772	total: 3m 11s	remaining: 14m 6s
1824:	learn: 0.0073871	total: 3m 11s	remaining: 14m 19s
1772:	learn: 0.0085325	total: 3m 11s	remaining: 14m 50s
1693:	learn: 0.0094881	total: 3m 12s	remaining: 15m 41s
1822:	learn: 0.0087976	total: 3m 11s	remaining: 14m 20s
1849:	learn: 0.0079727	total: 3m 12s	remaining: 14m 6s
1825:	learn: 0.0073814	total: 3m 11s	remaining: 14m 19s
1773:	learn: 0.0085248	total: 3m 12s	remaining: 14m 50s
1823:	learn: 0.0087926	total: 3m 12s	remaining: 14m 20s
1850:	learn: 0.0079665	total: 3m 12s	remaining: 14m 5s
1694:	learn: 0.0094761	total: 3m 12s	remaining: 15m 41s
1851:	learn: 0.0079616	total: 3m 12s	remaining: 14m 5s
1826:	learn: 0.0073763	total: 3m 12s	remaining: 14m 19s
1774:	learn: 0.0085149	total: 3m 12s	remaining: 14m 50s
1824:	learn: 0.0087849	total: 3m 12s	remaining: 14m 20s
1827:	learn: 0.0073718	total: 3m 12s	remaining: 14m 19s
1852:	learn: 0.0079544	total: 3m 12s	remaining: 14m 5s
1695:	learn: 0.0094692	total: 3m 12s	remaining: 15m 41s
1825:	learn: 0.0087730	total: 3m 12s	remaining: 14m 20s
1775:	learn: 0.0085114	total: 3m 12s	remaining: 14m 50s
1828:	learn: 0.0073669	total: 3m 12s	remaining: 14m 18s
1853:	learn: 0.0079485	total: 3m 12s	remaining: 14m 5s
1826:	learn: 0.0087634	total: 3m 12s	remaining: 14m 20s
1696:	learn: 0.0094607	total: 3m 12s	remaining: 15m 41s
1776:	learn: 0.0085063	total: 3m 12s	remaining: 14m 50s
1829:	learn: 0.0073614	total: 3m 12s	remaining: 14m 18s
1854:	learn: 0.0079401	total: 3m 12s	remaining: 14m 5s
1697:	learn: 0.0094495	total: 3m 12s	remaining: 15m 41s
1827:	learn: 0.0087515	total: 3m 12s	remaining: 14m 20s
1830:	learn: 0.0073549	total: 3m 12s	remaining: 14m 18s
1777:	learn: 0.0084983	total: 3m 12s	remaining: 14m 50s
1855:	learn: 0.0079319	total: 3m 12s	remaining: 14m 5s
1828:	learn: 0.0087440	total: 3m 12s	remaining: 14m 19s
1831:	learn: 0.0073483	total: 3m 12s	remaining: 14m 18s
1778:	learn: 0.0084932	total: 3m 12s	remaining: 14m 50s
1698:	learn: 0.0094368	total: 3m 12s	remaining: 15m 41s
1856:	learn: 0.0079276	total: 3m 12s	remaining: 14m 4s
1832:	learn: 0.0073416	total: 3m 12s	remaining: 14m 18s
1829:	learn: 0.0087335	total: 3m 12s	remaining: 14m 19s
1779:	learn: 0.0084861	total: 3m 12s	remaining: 14m 49s
1857:	learn: 0.0079242	total: 3m 12s	remaining: 14m 4s
1699:	learn: 0.0094271	total: 3m 12s	remaining: 15m 41s
1833:	learn: 0.0073366	total: 3m 12s	remaining: 14m 18s
1780:	learn: 0.0084801	total: 3m 12s	remaining: 14m 49s
1830:	learn: 0.0087254	total: 3m 12s	remaining: 14m 19s
1858:	learn: 0.0079155	total: 3m 12s	remaining: 14m 4s
1781:	learn: 0.0084710	total: 3m 12s	remaining: 14m 49s
1700:	learn: 0.0094178	total: 3m 12s	remaining: 15m 41s
1834:	learn: 0.0073285	total: 3m 12s	remaining: 14m 18s
1831:	learn: 0.0087188	total: 3m 12s	remaining: 14m 19s
1859:	learn: 0.0079102	total: 3m 12s	remaining: 14m 4s
1782:	learn: 0.0084662	total: 3m 12s	remaining: 14m 49s
1832:	learn: 0.0087106	total: 3m 12s	remaining: 14m 19s
1835:	learn: 0.0073242	total: 3m 12s	remaining: 14m 17s
1701:	learn: 0.0094086	total: 3m 13s	remaining: 15m 41s
1860:	learn: 0.0079019	total: 3m 13s	remaining: 14m 4s
1783:	learn: 0.0084587	total: 3m 13s	remaining: 14m 49s
1833:	learn: 0.0087038	total: 3m 13s	remaining: 14m 19s
1836:	learn: 0.0073158	total: 3m 13s	remaining: 14m 17s
1861:	learn: 0.0078949	total: 3m 13s	remaining: 14m 4s
1702:	learn: 0.0094037	total: 3m 13s	remaining: 15m 41s
1784:	learn: 0.0084552	total: 3m 13s	remaining: 14m 48s
1834:	learn: 0.0086970	total: 3m 13s	remaining: 14m 19s
1837:	learn: 0.0073089	total: 3m 13s	remaining: 14m 17s
1703:	learn: 0.0093922	total: 3m 13s	remaining: 15m 40s
1862:	learn: 0.0078863	total: 3m 13s	remaining: 14m 4s
1785:	learn: 0.0084482	total: 3m 13s	remaining: 14m 48s
1835:	learn: 0.0086893	total: 3m 13s	remaining: 14m 19s
1838:	learn: 0.0073047	total: 3m 13s	remaining: 14m 17s
1704:	learn: 0.0093853	total: 3m 13s	remaining: 15m 40s
1863:	learn: 0.0078779	total: 3m 13s	remaining: 14m 4s
1786:	learn: 0.0084392	total: 3m 13s	remaining: 14m 48s
1705:	learn: 0.0093723	total: 3m 13s	remaining: 15m 40s
1836:	learn: 0.0086780	total: 3m 13s	remaining: 14m 19s
1839:	learn: 0.0073004	total: 3m 13s	remaining: 14m 17s
1864:	learn: 0.0078728	total: 3m 13s	remaining: 14m 4s
1787:	learn: 0.0084297	total: 3m 13s	remaining: 14m 48s
1837:	learn: 0.0086725	total: 3m 13s	remaining: 14m 18s
1840:	learn: 0.0072928	total: 3m 13s	remaining: 14m 17s
1706:	learn: 0.0093640	total: 3m 13s	remaining: 15m 40s
1865:	learn: 0.0078644	total: 3m 13s	remaining: 14m 3s
1788:	learn: 0.0084239	total: 3m 13s	remaining: 14m 48s
1838:	learn: 0.0086613	total: 3m 13s	remaining: 14m 18s
1841:	learn: 0.0072844	total: 3m 13s	remaining: 14m 17s
1866:	learn: 0.0078548	total: 3m 13s	remaining: 14m 3s
1707:	learn: 0.0093598	total: 3m 13s	remaining: 15m 40s
1789:	learn: 0.0084191	total: 3m 13s	remaining: 14m 48s
1842:	learn: 0.0072774	total: 3m 13s	remaining: 14m 17s
1839:	learn: 0.0086499	total: 3m 13s	remaining: 14m 18s
1867:	learn: 0.0078496	total: 3m 13s	remaining: 14m 3s
1790:	learn: 0.0084105	total: 3m 13s	remaining: 14m 48s
1708:	learn: 0.0093487	total: 3m 13s	remaining: 15m 40s
1843:	learn: 0.0072732	total: 3m 13s	remaining: 14m 16s
1840:	learn: 0.0086399	total: 3m 13s	remaining: 14m 18s
1868:	learn: 0.0078404	total: 3m 13s	remaining: 14m 3s
1791:	learn: 0.0084058	total: 3m 13s	remaining: 14m 47s
1709:	learn: 0.0093450	total: 3m 13s	remaining: 15m 40s
1844:	learn: 0.0072691	total: 3m 13s	remaining: 14m 16s
1841:	learn: 0.0086349	total: 3m 13s	remaining: 14m 18s
1869:	learn: 0.0078361	total: 3m 13s	remaining: 14m 3s
1710:	learn: 0.0093370	total: 3m 14s	remaining: 15m 39s
1845:	learn: 0.0072630	total: 3m 13s	remaining: 14m 16s
1792:	learn: 0.0084015	total: 3m 13s	remaining: 14m 47s
1842:	learn: 0.0086243	total: 3m 13s	remaining: 14m 18s
1870:	learn: 0.0078293	total: 3m 14s	remaining: 14m 3s
1846:	learn: 0.0072589	total: 3m 14s	remaining: 14m 16s
1711:	learn: 0.0093247	total: 3m 14s	remaining: 15m 39s
1793:	learn: 0.0083932	total: 3m 14s	remaining: 14m 47s
1871:	learn: 0.0078224	total: 3m 14s	remaining: 14m 3s
1843:	learn: 0.0086194	total: 3m 14s	remaining: 14m 18s
1712:	learn: 0.0093174	total: 3m 14s	remaining: 15m 39s
1872:	learn: 0.0078153	total: 3m 14s	remaining: 14m 2s
1847:	learn: 0.0072539	total: 3m 14s	remaining: 14m 16s
1794:	learn: 0.0083842	total: 3m 14s	remaining: 14m 47s
1844:	learn: 0.0086126	total: 3m 14s	remaining: 14m 18s
1873:	learn: 0.0078097	total: 3m 14s	remaining: 14m 2s
1713:	learn: 0.0093088	total: 3m 14s	remaining: 15m 39s
1795:	learn: 0.0083781	total: 3m 14s	remaining: 14m 47s
1848:	learn: 0.0072467	total: 3m 14s	remaining: 14m 16s
1845:	learn: 0.0086065	total: 3m 14s	remaining: 14m 17s
1849:	learn: 0.0072380	total: 3m 14s	remaining: 14m 16s
1874:	learn: 0.0078056	total: 3m 14s	remaining: 14m 2s
1796:	learn: 0.0083695	total: 3m 14s	remaining: 14m 47s
1714:	learn: 0.0092984	total: 3m 14s	remaining: 15m 39s
1846:	learn: 0.0085978	total: 3m 14s	remaining: 14m 17s
1850:	learn: 0.0072332	total: 3m 14s	remaining: 14m 15s
1875:	learn: 0.0077978	total: 3m 14s	remaining: 14m 2s
1797:	learn: 0.0083599	total: 3m 14s	remaining: 14m 47s
1715:	learn: 0.0092866	total: 3m 14s	remaining: 15m 39s
1847:	learn: 0.0085898	total: 3m 14s	remaining: 14m 17s
1798:	learn: 0.0083565	total: 3m 14s	remaining: 14m 47s
1876:	learn: 0.0077912	total: 3m 14s	remaining: 14m 2s
1851:	learn: 0.0072266	total: 3m 14s	remaining: 14m 15s
1716:	learn: 0.0092771	total: 3m 14s	remaining: 15m 39s
1848:	learn: 0.0085856	total: 3m 14s	remaining: 14m 17s
1799:	learn: 0.0083483	total: 3m 14s	remaining: 14m 46s
1877:	learn: 0.0077835	total: 3m 14s	remaining: 14m 2s
1852:	learn: 0.0072212	total: 3m 14s	remaining: 14m 15s
1717:	learn: 0.0092704	total: 3m 14s	remaining: 15m 38s
1849:	learn: 0.0085771	total: 3m 14s	remaining: 14m 17s
1800:	learn: 0.0083444	total: 3m 14s	remaining: 14m 46s
1853:	learn: 0.0072165	total: 3m 14s	remaining: 14m 15s
1718:	learn: 0.0092566	total: 3m 14s	remaining: 15m 38s
1801:	learn: 0.0083391	total: 3m 14s	remaining: 14m 46s
1878:	learn: 0.0077785	total: 3m 14s	remaining: 14m 2s
1850:	learn: 0.0085664	total: 3m 14s	remaining: 14m 17s
1719:	learn: 0.0092527	total: 3m 14s	remaining: 15m 38s
1854:	learn: 0.0072080	total: 3m 14s	remaining: 14m 15s
1851:	learn: 0.0085592	total: 3m 14s	remaining: 14m 17s
1802:	learn: 0.0083362	total: 3m 14s	remaining: 14m 46s
1879:	learn: 0.0077709	total: 3m 15s	remaining: 14m 2s
1855:	learn: 0.0072030	total: 3m 14s	remaining: 14m 15s
1720:	learn: 0.0092427	total: 3m 15s	remaining: 15m 38s
1803:	learn: 0.0083252	total: 3m 15s	remaining: 14m 46s
1852:	learn: 0.0085521	total: 3m 14s	remaining: 14m 17s
1880:	learn: 0.0077639	total: 3m 15s	remaining: 14m 2s
1721:	learn: 0.0092347	total: 3m 15s	remaining: 15m 38s

1853:	learn: 0.0085436	total: 3m 15s	remaining: 14m 16s
1856:	learn: 0.0071950	total: 3m 15s	remaining: 14m 15s
1881:	learn: 0.0077548	total: 3m 15s	remaining: 14m 2s
1857:	learn: 0.0071884	total: 3m 15s	remaining: 14m 15s
1722:	learn: 0.0092265	total: 3m 15s	remaining: 15m 37s
1805:	learn: 0.0083068	total: 3m 15s	remaining: 14m 45s
1854:	learn: 0.0085379	total: 3m 15s	remaining: 14m 16s
1882:	learn: 0.0077468	total: 3m 15s	remaining: 14m 1s
1806:	learn: 0.0083034	total: 3m 15s	remaining: 14m 45s
1855:	learn: 0.0085284	total: 3m 15s	remaining: 14m 16s
1858:	learn: 0.0071845	total: 3m 15s	remaining: 14m 15s
1723:	learn: 0.0092090	total: 3m 15s	remaining: 15m 37s
1807:	learn: 0.0082937	total: 3m 15s	remaining: 14m 45s
1883:	learn: 0.0077418	total: 3m 15s	remaining: 14m 1s
1856:	learn: 0.0085223	total: 3m 15s	remaining: 14m 16s
1859:	learn: 0.0071802	total: 3m 15s	remaining: 14m 15s
1724:	learn: 0.0092033	total: 3m 15s	remaining: 15m 37s
1808:	learn: 0.0082852	total: 3m 15s	remaining: 14m 45s
1884:	learn: 0.0077343	total: 3m 15s	remaining: 14m 1s
1860:	learn: 0.0071752	total: 3m 15s	remaining: 14m 14s
1857:	learn: 0.0085166	total: 3m 15s	remaining: 14m 16s
1809:	learn: 0.0082785	total: 3m 15s	remaining: 14m 44s
1725:	learn: 0.0091930	total: 3m 15s	remaining: 15m 37s
1885:	learn: 0.0077237	total: 3m 15s	remaining: 14m 1s
1861:	learn: 0.0071675	total: 3m 15s	remaining: 14m 14s
1858:	learn: 0.0085091	total: 3m 15s	remaining: 14m 16s
1810:	learn: 0.0082720	total: 3m 15s	remaining: 14m 44s
1726:	learn: 0.0091878	total: 3m 15s	remaining: 15m 37s
1886:	learn: 0.0077178	total: 3m 15s	remaining: 14m 1s
1862:	learn: 0.0071625	total: 3m 15s	remaining: 14m 14s
1859:	learn: 0.0084996	total: 3m 15s	remaining: 14m 16s
1727:	learn: 0.0091800	total: 3m 15s	remaining: 15m 37s
1887:	learn: 0.0077128	total: 3m 15s	remaining: 14m 1s
1811:	learn: 0.0082654	total: 3m 15s	remaining: 14m 44s
1863:	learn: 0.0071541	total: 3m 15s	remaining: 14m 14s
1728:	learn: 0.0091711	total: 3m 15s	remaining: 15m 37s
1860:	learn: 0.0084941	total: 3m 15s	remaining: 14m 16s
1888:	learn: 0.0077071	total: 3m 15s	remaining: 14m 1s
1864:	learn: 0.0071483	total: 3m 15s	remaining: 14m 14s
1812:	learn: 0.0082612	total: 3m 15s	remaining: 14m 44s
1729:	learn: 0.0091639	total: 3m 16s	remaining: 15m 36s
1865:	learn: 0.0071435	total: 3m 15s	remaining: 14m 13s
1889:	learn: 0.0077006	total: 3m 16s	remaining: 14m 1s
1861:	learn: 0.0084838	total: 3m 15s	remaining: 14m 16s
1813:	learn: 0.0082518	total: 3m 16s	remaining: 14m 44s
1730:	learn: 0.0091567	total: 3m 16s	remaining: 15m 36s
1866:	learn: 0.0071393	total: 3m 16s	remaining: 14m 13s
1890:	learn: 0.0076972	total: 3m 16s	remaining: 14m 1s
1862:	learn: 0.0084738	total: 3m 16s	remaining: 14m 16s
1731:	learn: 0.0091469	total: 3m 16s	remaining: 15m 36s
1814:	learn: 0.0082461	total: 3m 16s	remaining: 14m 44s
1867:	learn: 0.0071342	total: 3m 16s	remaining: 14m 13s
1891:	learn: 0.0076921	total: 3m 16s	remaining: 14m 1s
1732:	learn: 0.0091353	total: 3m 16s	remaining: 15m 36s
1863:	learn: 0.0084698	total: 3m 16s	remaining: 14m 15s
1815:	learn: 0.0082375	total: 3m 16s	remaining: 14m 44s
1864:	learn: 0.0084606	total: 3m 16s	remaining: 14m 15s
1892:	learn: 0.0076894	total: 3m 16s	remaining: 14m
1733:	learn: 0.0091244	total: 3m 16s	remaining: 15m 36s
1868:	learn: 0.0071291	total: 3m 16s	remaining: 14m 13s
1816:	learn: 0.0082291	total: 3m 16s	remaining: 14m 44s
1865:	learn: 0.0084548	total: 3m 16s	remaining: 14m 15s
1893:	learn: 0.0076841	total: 3m 16s	remaining: 14m
1734:	learn: 0.0091171	total: 3m 16s	remaining: 15m 35s
1817:	learn: 0.0082214	total: 3m 16s	remaining: 14m 44s
1869:	learn: 0.0071226	total: 3m 16s	remaining: 14m 13s
1866:	learn: 0.0084509	total: 3m 16s	remaining: 14m 15s
1894:	learn: 0.0076787	total: 3m 16s	remaining: 14m
1870:	learn: 0.0071150	total: 3m 16s	remaining: 14m 13s
1735:	learn: 0.0091068	total: 3m 16s	remaining: 15m 35s
1818:	learn: 0.0082125	total: 3m 16s	remaining: 14m 44s
1867:	learn: 0.0084417	total: 3m 16s	remaining: 14m 15s
1895:	learn: 0.0076705	total: 3m 16s	remaining: 14m
1871:	learn: 0.0071091	total: 3m 16s	remaining: 14m 13s
1819:	learn: 0.0082060	total: 3m 16s	remaining: 14m 43s
1868:	learn: 0.0084383	total: 3m 16s	remaining: 14m 15s
1896:	learn: 0.0076618	total: 3m 16s	remaining: 14m
1736:	learn: 0.0090993	total: 3m 16s	remaining: 15m 35s
1872:	learn: 0.0071023	total: 3m 16s	remaining: 14m 13s
1820:	learn: 0.0081965	total: 3m 16s	remaining: 14m 43s
1869:	learn: 0.0084277	total: 3m 16s	remaining: 14m 14s
1897:	learn: 0.0076569	total: 3m 16s	remaining: 14m
1737:	learn: 0.0090923	total: 3m 16s	remaining: 15m 35s
1870:	learn: 0.0084243	total: 3m 16s	remaining: 14m 14s
1873:	learn: 0.0070940	total: 3m 16s	remaining: 14m 13s
1821:	learn: 0.0081924	total: 3m 16s	remaining: 14m 43s
1898:	learn: 0.0076495	total: 3m 16s	remaining: 14m
1871:	learn: 0.0084170	total: 3m 16s	remaining: 14m 14s
1738:	learn: 0.0090855	total: 3m 16s	remaining: 15m 35s
1822:	learn: 0.0081845	total: 3m 16s	remaining: 14m 43s
1874:	learn: 0.0070878	total: 3m 16s	remaining: 14m 13s
1872:	learn: 0.0084131	total: 3m 16s	remaining: 14m 14s
1899:	learn: 0.0076443	total: 3m 17s	remaining: 13m 59s
1823:	learn: 0.0081770	total: 3m 17s	remaining: 14m 43s
1739:	learn: 0.0090817	total: 3m 17s	remaining: 15m 35s
1875:	learn: 0.0070809	total: 3m 16s	remaining: 14m 13s
1900:	learn: 0.0076364	total: 3m 17s	remaining: 13m 59s
1824:	learn: 0.0081718	total: 3m 17s	remaining: 14m 42s
1873:	learn: 0.0084063	total: 3m 17s	remaining: 14m 14s
1740:	learn: 0.0090720	total: 3m 17s	remaining: 15m 35s
1901:	learn: 0.0076293	total: 3m 17s	remaining: 13m 59s
1876:	learn: 0.0070759	total: 3m 17s	remaining: 14m 13s
1874:	learn: 0.0084022	total: 3m 17s	remaining: 14m 14s
1825:	learn: 0.0081642	total: 3m 17s	remaining: 14m 42s
1902:	learn: 0.0076233	total: 3m 17s	remaining: 13m 59s
1741:	learn: 0.0090664	total: 3m 17s	remaining: 15m 35s
1875:	learn: 0.0083987	total: 3m 17s	remaining: 14m 13s
1877:	learn: 0.0070682	total: 3m 17s	remaining: 14m 12s
1826:	learn: 0.0081566	total: 3m 17s	remaining: 14m 42s
1903:	learn: 0.0076188	total: 3m 17s	remaining: 13m 59s
1742:	learn: 0.0090565	total: 3m 17s	remaining: 15m 35s
1878:	learn: 0.0070614	total: 3m 17s	remaining: 14m 12s
1876:	learn: 0.0083919	total: 3m 17s	remaining: 14m 13s
1827:	learn: 0.0081525	total: 3m 17s	remaining: 14m 42s
1904:	learn: 0.0076116	total: 3m 17s	remaining: 13m 59s
1877:	learn: 0.0083858	total: 3m 17s	remaining: 14m 13s
1743:	learn: 0.0090467	total: 3m 17s	remaining: 15m 35s
1879:	learn: 0.0070558	total: 3m 17s	remaining: 14m 12s
1828:	learn: 0.0081460	total: 3m 17s	remaining: 14m 42s
1905:	learn: 0.0076064	total: 3m 17s	remaining: 13m 59s
1878:	learn: 0.0083750	total: 3m 17s	remaining: 14m 13s
1744:	learn: 0.0090365	total: 3m 17s	remaining: 15m 34s
1880:	learn: 0.0070480	total: 3m 17s	remaining: 14m 12s
1906:	learn: 0.0075976	total: 3m 17s	remaining: 13m 58s
1829:	learn: 0.0081360	total: 3m 17s	remaining: 14m 42s
1879:	learn: 0.0083659	total: 3m 17s	remaining: 14m 13s
1745:	learn: 0.0090232	total: 3m 17s	remaining: 15m 34s
1881:	learn: 0.0070413	total: 3m 17s	remaining: 14m 12s
1907:	learn: 0.0075906	total: 3m 17s	remaining: 13m 58s
1830:	learn: 0.0081324	total: 3m 17s	remaining: 14m 42s
1880:	learn: 0.0083625	total: 3m 17s	remaining: 14m 13s
1882:	learn: 0.0070338	total: 3m 17s	remaining: 14m 12s
1908:	learn: 0.0075850	total: 3m 17s	remaining: 13m 58s
1746:	learn: 0.0090127	total: 3m 17s	remaining: 15m 34s
1881:	learn: 0.0083546	total: 3m 17s	remaining: 14m 12s
1831:	learn: 0.0081249	total: 3m 17s	remaining: 14m 42s
1909:	learn: 0.0075787	total: 3m 17s	remaining: 13m 58s
1883:	learn: 0.0070259	total: 3m 17s	remaining: 14m 12s
1832:	learn: 0.0081165	total: 3m 17s	remaining: 14m 42s
1747:	learn: 0.0090008	total: 3m 17s	remaining: 15m 34s
1884:	learn: 0.0070184	total: 3m 17s	remaining: 14m 12s
1910:	learn: 0.0075718	total: 3m 18s	remaining: 13m 58s
1882:	learn: 0.0083433	total: 3m 17s	remaining: 14m 12s
1748:	learn: 0.0089940	total: 3m 18s	remaining: 15m 34s
1833:	learn: 0.0081078	total: 3m 18s	remaining: 14m 41s
: 14m 2s
1721:	learn: 0.0092347	total: 3m 15s	remaining:1883:	learn: 0.0083377	total: 3m 17s	remaining: 14m 12s
1911:	learn: 0.0075681	total: 3m 18s	remaining: 13m 58s
1749:	learn: 0.0089860	total: 3m 18s	remaining: 15m 34s
1884:	learn: 0.0083328	total: 3m 18s	remaining: 14m 12s
1886:	learn: 0.0070070	total: 3m 18s	remaining: 14m 11s
1912:	learn: 0.0075624	total: 3m 18s	remaining: 13m 58s
1834:	learn: 0.0081031	total: 3m 18s	remaining: 14m 41s
1750:	learn: 0.0089774	total: 3m 18s	remaining: 15m 34s
1913:	learn: 0.0075587	total: 3m 18s	remaining: 13m 57s
1885:	learn: 0.0083288	total: 3m 18s	remaining: 14m 12s
1887:	learn: 0.0069998	total: 3m 18s	remaining: 14m 11s
1835:	learn: 0.0080939	total: 3m 18s	remaining: 14m 41s
1751:	learn: 0.0089718	total: 3m 18s	remaining: 15m 33s
1886:	learn: 0.0083256	total: 3m 18s	remaining: 14m 12s
1914:	learn: 0.0075507	total: 3m 18s	remaining: 13m 57s
1888:	learn: 0.0069952	total: 3m 18s	remaining: 14m 11s
1752:	learn: 0.0089632	total: 3m 18s	remaining: 15m 33s
1836:	learn: 0.0080900	total: 3m 18s	remaining: 14m 41s
1887:	learn: 0.0083185	total: 3m 18s	remaining: 14m 12s
1915:	learn: 0.0075466	total: 3m 18s	remaining: 13m 57s
1889:	learn: 0.0069889	total: 3m 18s	remaining: 14m 11s
1753:	learn: 0.0089566	total: 3m 18s	remaining: 15m 33s
1916:	learn: 0.0075388	total: 3m 18s	remaining: 13m 57s
1888:	learn: 0.0083138	total: 3m 18s	remaining: 14m 12s
1837:	learn: 0.0080838	total: 3m 18s	remaining: 14m 41s
1890:	learn: 0.0069835	total: 3m 18s	remaining: 14m 11s
1754:	learn: 0.0089499	total: 3m 18s	remaining: 15m 33s
1889:	learn: 0.0083032	total: 3m 18s	remaining: 14m 11s
1917:	learn: 0.0075357	total: 3m 18s	remaining: 13m 57s
1838:	learn: 0.0080806	total: 3m 18s	remaining: 14m 41s
1891:	learn: 0.0069782	total: 3m 18s	remaining: 14m 11s
1890:	learn: 0.0082967	total: 3m 18s	remaining: 14m 11s
1755:	learn: 0.0089333	total: 3m 18s	remaining: 15m 33s
1839:	learn: 0.0080728	total: 3m 18s	remaining: 14m 41s
1918:	learn: 0.0075309	total: 3m 18s	remaining: 13m 57s
1892:	learn: 0.0069714	total: 3m 18s	remaining: 14m 11s
1891:	learn: 0.0082868	total: 3m 18s	remaining: 14m 11s
1756:	learn: 0.0089255	total: 3m 18s	remaining: 15m 33s
1840:	learn: 0.0080649	total: 3m 18s	remaining: 14m 41s
1919:	learn: 0.0075232	total: 3m 18s	remaining: 13m 57s
1893:	learn: 0.0069627	total: 3m 18s	remaining: 14m 11s
1892:	learn: 0.0082830	total: 3m 18s	remaining: 14m 11s
1841:	learn: 0.0080551	total: 3m 18s	remaining: 14m 41s
1757:	learn: 0.0089188	total: 3m 19s	remaining: 15m 33s
1920:	learn: 0.0075136	total: 3m 19s	remaining: 13m 57s
1893:	learn: 0.0082762	total: 3m 18s	remaining: 14m 11s
1894:	learn: 0.0069572	total: 3m 18s	remaining: 14m 10s
1842:	learn: 0.0080510	total: 3m 19s	remaining: 14m 41s
1921:	learn: 0.0075056	total: 3m 19s	remaining: 13m 56s
1758:	learn: 0.0089104	total: 3m 19s	remaining: 15m 32s
1894:	learn: 0.0082678	total: 3m 18s	remaining: 14m 11s
1843:	learn: 0.0080433	total: 3m 19s	remaining: 14m 40s
1895:	learn: 0.0069504	total: 3m 19s	remaining: 14m 10s
1922:	learn: 0.0075003	total: 3m 19s	remaining: 13m 56s
1759:	learn: 0.0088995	total: 3m 19s	remaining: 15m 32s
1895:	learn: 0.0082576	total: 3m 19s	remaining: 14m 10s
1896:	learn: 0.0069456	total: 3m 19s	remaining: 14m 10s
1923:	learn: 0.0074955	total: 3m 19s	remaining: 13m 56s
1844:	learn: 0.0080352	total: 3m 19s	remaining: 14m 40s
1896:	learn: 0.0082479	total: 3m 19s	remaining: 14m 10s
1760:	learn: 0.0088912	total: 3m 19s	remaining: 15m 32s
1924:	learn: 0.0074880	total: 3m 19s	remaining: 13m 56s
1897:	learn: 0.0082451	total: 3m 19s	remaining: 14m 10s
1897:	learn: 0.0069394	total: 3m 19s	remaining: 14m 10s
1845:	learn: 0.0080257	total: 3m 19s	remaining: 14m 40s
1761:	learn: 0.0088841	total: 3m 19s	remaining: 15m 32s
1925:	learn: 0.0074854	total: 3m 19s	remaining: 13m 56s
1898:	learn: 0.0069332	total: 3m 19s	remaining: 14m 10s
1762:	learn: 0.0088772	total: 3m 19s	remaining: 15m 32s
1898:	learn: 0.0082414	total: 3m 19s	remaining: 14m 10s
1846:	learn: 0.0080171	total: 3m 19s	remaining: 14m 40s
1926:	learn: 0.0074808	total: 3m 19s	remaining: 13m 56s
1899:	learn: 0.0069274	total: 3m 19s	remaining: 14m 10s
1847:	learn: 0.0080062	total: 3m 19s	remaining: 14m 40s
1763:	learn: 0.0088696	total: 3m 19s	remaining: 15m 32s
1899:	learn: 0.0082344	total: 3m 19s	remaining: 14m 10s
1927:	learn: 0.0074746	total: 3m 19s	remaining: 13m 55s
1900:	learn: 0.0069214	total: 3m 19s	remaining: 14m 10s
1848:	learn: 0.0080022	total: 3m 19s	remaining: 14m 40s
1764:	learn: 0.0088578	total: 3m 19s	remaining: 15m 31s
1900:	learn: 0.0082293	total: 3m 19s	remaining: 14m 10s
1928:	learn: 0.0074692	total: 3m 19s	remaining: 13m 55s
1901:	learn: 0.0069167	total: 3m 19s	remaining: 14m 10s
1765:	learn: 0.0088537	total: 3m 19s	remaining: 15m 31s
1849:	learn: 0.0079935	total: 3m 19s	remaining: 14m 40s
1901:	learn: 0.0082170	total: 3m 19s	remaining: 14m 10s
1929:	learn: 0.0074634	total: 3m 19s	remaining: 13m 55s
1902:	learn: 0.0069124	total: 3m 19s	remaining: 14m 9s
1766:	learn: 0.0088475	total: 3m 19s	remaining: 15m 31s
1850:	learn: 0.0079854	total: 3m 19s	remaining: 14m 40s
1902:	learn: 0.0082134	total: 3m 19s	remaining: 14m 10s
1930:	learn: 0.0074579	total: 3m 19s	remaining: 13m 55s
1903:	learn: 0.0069060	total: 3m 19s	remaining: 14m 9s
1767:	learn: 0.0088407	total: 3m 20s	remaining: 15m 31s
1851:	learn: 0.0079760	total: 3m 20s	remaining: 14m 39s
1931:	learn: 0.0074525	total: 3m 20s	remaining: 13m 55s
1903:	learn: 0.0082064	total: 3m 19s	remaining: 14m 9s
1904:	learn: 0.0069005	total: 3m 19s	remaining: 14m 9s
1768:	learn: 0.0088282	total: 3m 20s	remaining: 15m 30s
1904:	learn: 0.0081991	total: 3m 19s	remaining: 14m 9s
1852:	learn: 0.0079689	total: 3m 20s	remaining: 14m 39s
1932:	learn: 0.0074480	total: 3m 20s	remaining: 13m 55s
1769:	learn: 0.0088232	total: 3m 20s	remaining: 15m 30s
1905:	learn: 0.0068953	total: 3m 20s	remaining: 14m 9s
1933:	learn: 0.0074427	total: 3m 20s	remaining: 13m 55s
1905:	learn: 0.0081883	total: 3m 20s	remaining: 14m 9s
1770:	learn: 0.0088149	total: 3m 20s	remaining: 15m 30s
1853:	learn: 0.0079583	total: 3m 20s	remaining: 14m 39s
1906:	learn: 0.0068889	total: 3m 20s	remaining: 14m 9s
1906:	learn: 0.0081788	total: 3m 20s	remaining: 14m 9s
1934:	learn: 0.0074373	total: 3m 20s	remaining: 13m 55s
1854:	learn: 0.0079505	total: 3m 20s	remaining: 14m 39s
1907:	learn: 0.0068830	total: 3m 20s	remaining: 14m 9s
1771:	learn: 0.0088060	total: 3m 20s	remaining: 15m 30s
1907:	learn: 0.0081670	total: 3m 20s	remaining: 14m 9s
1935:	learn: 0.0074334	total: 3m 20s	remaining: 13m 55s
1855:	learn: 0.0079426	total: 3m 20s	remaining: 14m 39s
1908:	learn: 0.0068765	total: 3m 20s	remaining: 14m 9s
1772:	learn: 0.0088002	total: 3m 20s	remaining: 15m 30s
1908:	learn: 0.0081635	total: 3m 20s	remaining: 14m 9s
1856:	learn: 0.0079378	total: 3m 20s	remaining: 14m 39s
1936:	learn: 0.0074281	total: 3m 20s	remaining: 13m 55s
1909:	learn: 0.0068705	total: 3m 20s	remaining: 14m 9s
1773:	learn: 0.0087924	total: 3m 20s	remaining: 15m 30s
1909:	learn: 0.0081545	total: 3m 20s	remaining: 14m 9s
1857:	learn: 0.0079310	total: 3m 20s	remaining: 14m 39s
1910:	learn: 0.0068623	total: 3m 20s	remaining: 14m 9s
1910:	learn: 0.0081458	total: 3m 20s	remaining: 14m 8s
1774:	learn: 0.0087860	total: 3m 20s	remaining: 15m 30s
1937:	learn: 0.0074212	total: 3m 20s	remaining: 13m 54s
1858:	learn: 0.0079271	total: 3m 20s	remaining: 14m 39s
1775:	learn: 0.0087813	total: 3m 20s	remaining: 15m 29s
1911:	learn: 0.0081374	total: 3m 20s	remaining: 14m 8s
1911:	learn: 0.0068569	total: 3m 20s	remaining: 14m 9s
1938:	learn: 0.0074164	total: 3m 20s	remaining: 13m 54s
1859:	learn: 0.0079219	total: 3m 20s	remaining: 14m 38s
1776:	learn: 0.0087710	total: 3m 20s	remaining: 15m 29s
1912:	learn: 0.0081292	total: 3m 20s	remaining: 14m 8s
1912:	learn: 0.0068514	total: 3m 20s	remaining: 14m 8s
1860:	learn: 0.0079141	total: 3m 20s	remaining: 14m 38s
1939:	learn: 0.0074092	total: 3m 20s	remaining: 13m 54s
1913:	learn: 0.0081210	total: 3m 20s	remaining: 14m 8s
1777:	learn: 0.0087595	total: 3m 21s	remaining: 15m 29s
1861:	learn: 0.0079090	total: 3m 20s	remaining: 14m 38s
1913:	learn: 0.0068468	total: 3m 20s	remaining: 14m 8s
 14m 5s

1694:	learn: 0.0094761	total: 3m 12s	remaining: 1940:	learn: 0.0074032	total: 3m 21s	remaining: 13m 54s
1914:	learn: 0.0081092	total: 3m 20s	remaining: 14m 8s
1862:	learn: 0.0079052	total: 3m 21s	remaining: 14m 38s
1914:	learn: 0.0068395	total: 3m 21s	remaining: 14m 8s
1778:	learn: 0.0087532	total: 3m 21s	remaining: 15m 29s
1941:	learn: 0.0073987	total: 3m 21s	remaining: 13m 54s
1915:	learn: 0.0081004	total: 3m 21s	remaining: 14m 8s
1863:	learn: 0.0078968	total: 3m 21s	remaining: 14m 38s
1915:	learn: 0.0068359	total: 3m 21s	remaining: 14m 8s
1942:	learn: 0.0073901	total: 3m 21s	remaining: 13m 54s
1916:	learn: 0.0080938	total: 3m 21s	remaining: 14m 7s
1779:	learn: 0.0087455	total: 3m 21s	remaining: 15m 29s
1864:	learn: 0.0078917	total: 3m 21s	remaining: 14m 37s
1916:	learn: 0.0068301	total: 3m 21s	remaining: 14m 8s
1943:	learn: 0.0073836	total: 3m 21s	remaining: 13m 54s
1917:	learn: 0.0080863	total: 3m 21s	remaining: 14m 7s
1780:	learn: 0.0087340	total: 3m 21s	remaining: 15m 29s
1865:	learn: 0.0078849	total: 3m 21s	remaining: 14m 37s
1944:	learn: 0.0073809	total: 3m 21s	remaining: 13m 54s
1917:	learn: 0.0068227	total: 3m 21s	remaining: 14m 8s
1918:	learn: 0.0080796	total: 3m 21s	remaining: 14m 7s
1866:	learn: 0.0078773	total: 3m 21s	remaining: 14m 37s
1781:	learn: 0.0087239	total: 3m 21s	remaining: 15m 29s
1945:	learn: 0.0073780	total: 3m 21s	remaining: 13m 54s
1918:	learn: 0.0068167	total: 3m 21s	remaining: 14m 8s
1919:	learn: 0.0080758	total: 3m 21s	remaining: 14m 7s
1782:	learn: 0.0087136	total: 3m 21s	remaining: 15m 29s
1867:	learn: 0.0078719	total: 3m 21s	remaining: 14m 37s
1919:	learn: 0.0068087	total: 3m 21s	remaining: 14m 8s
1946:	learn: 0.0073718	total: 3m 21s	remaining: 13m 53s
1920:	learn: 0.0080694	total: 3m 21s	remaining: 14m 7s
1868:	learn: 0.0078641	total: 3m 21s	remaining: 14m 37s
1947:	learn: 0.0073658	total: 3m 21s	remaining: 13m 53s
1920:	learn: 0.0068052	total: 3m 21s	remaining: 14m 7s
1783:	learn: 0.0087052	total: 3m 21s	remaining: 15m 29s
1921:	learn: 0.0080636	total: 3m 21s	remaining: 14m 7s
1948:	learn: 0.0073588	total: 3m 21s	remaining: 13m 53s
1869:	learn: 0.0078595	total: 3m 21s	remaining: 14m 37s
1784:	learn: 0.0087001	total: 3m 21s	remaining: 15m 28s
1921:	learn: 0.0068000	total: 3m 21s	remaining: 14m 7s
1922:	learn: 0.0080564	total: 3m 21s	remaining: 14m 7s
1870:	learn: 0.0078535	total: 3m 21s	remaining: 14m 37s
1949:	learn: 0.0073552	total: 3m 21s	remaining: 13m 53s
1785:	learn: 0.0086903	total: 3m 21s	remaining: 15m 28s
1923:	learn: 0.0080519	total: 3m 21s	remaining: 14m 7s
1871:	learn: 0.0078480	total: 3m 21s	remaining: 14m 36s
1922:	learn: 0.0067924	total: 3m 21s	remaining: 14m 7s
1950:	learn: 0.0073489	total: 3m 21s	remaining: 13m 53s
1786:	learn: 0.0086818	total: 3m 22s	remaining: 15m 28s
1924:	learn: 0.0080486	total: 3m 21s	remaining: 14m 6s
1951:	learn: 0.0073443	total: 3m 22s	remaining: 13m 53s
1923:	learn: 0.0067879	total: 3m 21s	remaining: 14m 7s
1872:	learn: 0.0078392	total: 3m 22s	remaining: 14m 36s
1925:	learn: 0.0080387	total: 3m 21s	remaining: 14m 6s
1787:	learn: 0.0086758	total: 3m 22s	remaining: 15m 28s
1924:	learn: 0.0067829	total: 3m 22s	remaining: 14m 7s
1873:	learn: 0.0078342	total: 3m 22s	remaining: 14m 36s
1952:	learn: 0.0073390	total: 3m 22s	remaining: 13m 53s
1926:	learn: 0.0080288	total: 3m 22s	remaining: 14m 6s
1788:	learn: 0.0086673	total: 3m 22s	remaining: 15m 28s
1925:	learn: 0.0067776	total: 3m 22s	remaining: 14m 7s
1874:	learn: 0.0078303	total: 3m 22s	remaining: 14m 36s
1927:	learn: 0.0080222	total: 3m 22s	remaining: 14m 6s
1953:	learn: 0.0073341	total: 3m 22s	remaining: 13m 53s
1789:	learn: 0.0086585	total: 3m 22s	remaining: 15m 27s
1875:	learn: 0.0078199	total: 3m 22s	remaining: 14m 36s
1926:	learn: 0.0067717	total: 3m 22s	remaining: 14m 7s
1928:	learn: 0.0080119	total: 3m 22s	remaining: 14m 6s
1954:	learn: 0.0073282	total: 3m 22s	remaining: 13m 52s
1790:	learn: 0.0086526	total: 3m 22s	remaining: 15m 27s
1876:	learn: 0.0078131	total: 3m 22s	remaining: 14m 36s
1929:	learn: 0.0080052	total: 3m 22s	remaining: 14m 6s
1927:	learn: 0.0067657	total: 3m 22s	remaining: 14m 7s
1955:	learn: 0.0073254	total: 3m 22s	remaining: 13m 52s
1791:	learn: 0.0086467	total: 3m 22s	remaining: 15m 27s
1877:	learn: 0.0078100	total: 3m 22s	remaining: 14m 35s
1956:	learn: 0.0073202	total: 3m 22s	remaining: 13m 52s
1930:	learn: 0.0080019	total: 3m 22s	remaining: 14m 5s
1928:	learn: 0.0067590	total: 3m 22s	remaining: 14m 7s
1792:	learn: 0.0086390	total: 3m 22s	remaining: 15m 27s
1878:	learn: 0.0078047	total: 3m 22s	remaining: 14m 35s
1931:	learn: 0.0079953	total: 3m 22s	remaining: 14m 5s
1957:	learn: 0.0073136	total: 3m 22s	remaining: 13m 52s
1929:	learn: 0.0067546	total: 3m 22s	remaining: 14m 7s
1793:	learn: 0.0086294	total: 3m 22s	remaining: 15m 27s
1930:	learn: 0.0067508	total: 3m 22s	remaining: 14m 6s
1879:	learn: 0.0077959	total: 3m 22s	remaining: 14m 35s
1958:	learn: 0.0073079	total: 3m 22s	remaining: 13m 52s
1932:	learn: 0.0079875	total: 3m 22s	remaining: 14m 5s
1931:	learn: 0.0067430	total: 3m 22s	remaining: 14m 6s
1794:	learn: 0.0086172	total: 3m 22s	remaining: 15m 27s
1959:	learn: 0.0073043	total: 3m 22s	remaining: 13m 52s
1933:	learn: 0.0079788	total: 3m 22s	remaining: 14m 5s
1880:	learn: 0.0077921	total: 3m 22s	remaining: 14m 35s
1795:	learn: 0.0086117	total: 3m 22s	remaining: 15m 27s
1932:	learn: 0.0067380	total: 3m 22s	remaining: 14m 6s
1960:	learn: 0.0072963	total: 3m 22s	remaining: 13m 52s
1934:	learn: 0.0079723	total: 3m 22s	remaining: 14m 5s
1881:	learn: 0.0077838	total: 3m 22s	remaining: 14m 35s
1796:	learn: 0.0086051	total: 3m 23s	remaining: 15m 26s
1933:	learn: 0.0067312	total: 3m 22s	remaining: 14m 6s
1961:	learn: 0.0072892	total: 3m 23s	remaining: 13m 51s
1935:	learn: 0.0079674	total: 3m 22s	remaining: 14m 5s
1882:	learn: 0.0077755	total: 3m 23s	remaining: 14m 35s
1934:	learn: 0.0067251	total: 3m 23s	remaining: 14m 6s
1797:	learn: 0.0085989	total: 3m 23s	remaining: 15m 26s
1962:	learn: 0.0072819	total: 3m 23s	remaining: 13m 51s
1936:	learn: 0.0079604	total: 3m 23s	remaining: 14m 5s
1798:	learn: 0.0085915	total: 3m 23s	remaining: 15m 26s
1883:	learn: 0.0077672	total: 3m 23s	remaining: 14m 35s
1935:	learn: 0.0067217	total: 3m 23s	remaining: 14m 6s
1937:	learn: 0.0079507	total: 3m 23s	remaining: 14m 4s
1963:	learn: 0.0072760	total: 3m 23s	remaining: 13m 51s
1799:	learn: 0.0085843	total: 3m 23s	remaining: 15m 26s
1936:	learn: 0.0067160	total: 3m 23s	remaining: 14m 6s
1884:	learn: 0.0077619	total: 3m 23s	remaining: 14m 35s
1938:	learn: 0.0079454	total: 3m 23s	remaining: 14m 4s
1964:	learn: 0.0072690	total: 3m 23s	remaining: 13m 51s
1800:	learn: 0.0085785	total: 3m 23s	remaining: 15m 26s
1937:	learn: 0.0067089	total: 3m 23s	remaining: 14m 5s
1939:	learn: 0.0079384	total: 3m 23s	remaining: 14m 4s
1885:	learn: 0.0077588	total: 3m 23s	remaining: 14m 35s
1965:	learn: 0.0072650	total: 3m 23s	remaining: 13m 51s
1801:	learn: 0.0085675	total: 3m 23s	remaining: 15m 25s
1938:	learn: 0.0067024	total: 3m 23s	remaining: 14m 5s
1940:	learn: 0.0079299	total: 3m 23s	remaining: 14m 4s
1966:	learn: 0.0072586	total: 3m 23s	remaining: 13m 51s
1886:	learn: 0.0077535	total: 3m 23s	remaining: 14m 35s
1802:	learn: 0.0085571	total: 3m 23s	remaining: 15m 25s
1939:	learn: 0.0066976	total: 3m 23s	remaining: 14m 5s
1941:	learn: 0.0079240	total: 3m 23s	remaining: 14m 4s
1803:	learn: 0.0085483	total: 3m 23s	remaining: 15m 25s
1887:	learn: 0.0077488	total: 3m 23s	remaining: 14m 35s
1967:	learn: 0.0072515	total: 3m 23s	remaining: 13m 51s
1940:	learn: 0.0066914	total: 3m 23s	remaining: 14m 5s
1804:	learn: 0.0085426	total: 3m 23s	remaining: 15m 25s
1942:	learn: 0.0079192	total: 3m 23s	remaining: 14m 4s
1888:	learn: 0.0077436	total: 3m 23s	remaining: 14m 35s
1968:	learn: 0.0072443	total: 3m 23s	remaining: 13m 51s
1941:	learn: 0.0066859	total: 3m 23s	remaining: 14m 5s
1805:	learn: 0.0085356	total: 3m 23s	remaining: 15m 24s
1943:	learn: 0.0079094	total: 3m 23s	remaining: 14m 4s
1889:	learn: 0.0077388	total: 3m 23s	remaining: 14m 34s
1969:	learn: 0.0072400	total: 3m 23s	remaining: 13m 51s
1806:	learn: 0.0085269	total: 3m 23s	remaining: 15m 24s
1942:	learn: 0.0066819	total: 3m 23s	remaining: 14m 5s
1944:	learn: 0.0079012	total: 3m 23s	remaining: 14m 4s

1970:	learn: 0.0072293	total: 3m 24s	remaining: 13m 51s
1890:	learn: 0.0077320	total: 3m 24s	remaining: 14m 34s
1943:	learn: 0.0066768	total: 3m 23s	remaining: 14m 5s
1807:	learn: 0.0085239	total: 3m 24s	remaining: 15m 24s
1971:	learn: 0.0072257	total: 3m 24s	remaining: 13m 50s
1945:	learn: 0.0078952	total: 3m 23s	remaining: 14m 4s
1891:	learn: 0.0077239	total: 3m 24s	remaining: 14m 34s
1944:	learn: 0.0066698	total: 3m 24s	remaining: 14m 4s
1808:	learn: 0.0085187	total: 3m 24s	remaining: 15m 24s
1972:	learn: 0.0072175	total: 3m 24s	remaining: 13m 50s
1946:	learn: 0.0078895	total: 3m 24s	remaining: 14m 4s
1892:	learn: 0.0077189	total: 3m 24s	remaining: 14m 34s
1945:	learn: 0.0066646	total: 3m 24s	remaining: 14m 4s
1947:	learn: 0.0078832	total: 3m 24s	remaining: 14m 3s
1973:	learn: 0.0072125	total: 3m 24s	remaining: 13m 50s
1809:	learn: 0.0085083	total: 3m 24s	remaining: 15m 24s
1893:	learn: 0.0077124	total: 3m 24s	remaining: 14m 34s
1946:	learn: 0.0066585	total: 3m 24s	remaining: 14m 4s
1974:	learn: 0.0072044	total: 3m 24s	remaining: 13m 50s
1948:	learn: 0.0078785	total: 3m 24s	remaining: 14m 3s
1894:	learn: 0.0077085	total: 3m 24s	remaining: 14m 34s
1810:	learn: 0.0085005	total: 3m 24s	remaining: 15m 24s
1947:	learn: 0.0066540	total: 3m 24s	remaining: 14m 4s
1949:	learn: 0.0078689	total: 3m 24s	remaining: 14m 3s
1975:	learn: 0.0071984	total: 3m 24s	remaining: 13m 50s
1895:	learn: 0.0077023	total: 3m 24s	remaining: 14m 34s
1811:	learn: 0.0084950	total: 3m 24s	remaining: 15m 24s
1948:	learn: 0.0066490	total: 3m 24s	remaining: 14m 4s
1950:	learn: 0.0078632	total: 3m 24s	remaining: 14m 3s
1976:	learn: 0.0071901	total: 3m 24s	remaining: 13m 50s
1949:	learn: 0.0066435	total: 3m 24s	remaining: 14m 4s
1896:	learn: 0.0076943	total: 3m 24s	remaining: 14m 34s
1812:	learn: 0.0084836	total: 3m 24s	remaining: 15m 24s
1951:	learn: 0.0078575	total: 3m 24s	remaining: 14m 3s
1977:	learn: 0.0071846	total: 3m 24s	remaining: 13m 50s
1950:	learn: 0.0066369	total: 3m 24s	remaining: 14m 4s
1897:	learn: 0.0076896	total: 3m 24s	remaining: 14m 33s
1952:	learn: 0.0078493	total: 3m 24s	remaining: 14m 3s
1813:	learn: 0.0084754	total: 3m 24s	remaining: 15m 24s
1978:	learn: 0.0071804	total: 3m 24s	remaining: 13m 49s
1951:	learn: 0.0066303	total: 3m 24s	remaining: 14m 4s
1898:	learn: 0.0076820	total: 3m 24s	remaining: 14m 33s
1979:	learn: 0.0071741	total: 3m 24s	remaining: 13m 49s
1953:	learn: 0.0078434	total: 3m 24s	remaining: 14m 2s
1814:	learn: 0.0084646	total: 3m 24s	remaining: 15m 23s
1980:	learn: 0.0071693	total: 3m 24s	remaining: 13m 49s
1899:	learn: 0.0076757	total: 3m 24s	remaining: 14m 33s
1952:	learn: 0.0066241	total: 3m 24s	remaining: 14m 4s
1815:	learn: 0.0084542	total: 3m 24s	remaining: 15m 23s
1954:	learn: 0.0078375	total: 3m 24s	remaining: 14m 2s
1981:	learn: 0.0071628	total: 3m 25s	remaining: 13m 49s
1953:	learn: 0.0066198	total: 3m 24s	remaining: 14m 3s
1900:	learn: 0.0076703	total: 3m 25s	remaining: 14m 33s
1955:	learn: 0.0078307	total: 3m 24s	remaining: 14m 2s
1816:	learn: 0.0084487	total: 3m 25s	remaining: 15m 23s
1954:	learn: 0.0066146	total: 3m 25s	remaining: 14m 3s
1982:	learn: 0.0071564	total: 3m 25s	remaining: 13m 49s
1901:	learn: 0.0076671	total: 3m 25s	remaining: 14m 33s
1955:	learn: 0.0066087	total: 3m 25s	remaining: 14m 3s
1956:	learn: 0.0078246	total: 3m 25s	remaining: 14m 2s
1817:	learn: 0.0084431	total: 3m 25s	remaining: 15m 23s
1983:	learn: 0.0071516	total: 3m 25s	remaining: 13m 49s
1956:	learn: 0.0066044	total: 3m 25s	remaining: 14m 3s
1818:	learn: 0.0084355	total: 3m 25s	remaining: 15m 23s
1902:	learn: 0.0076605	total: 3m 25s	remaining: 14m 33s
1957:	learn: 0.0078201	total: 3m 25s	remaining: 14m 2s
1957:	learn: 0.0065994	total: 3m 25s	remaining: 14m 3s
1984:	learn: 0.0071480	total: 3m 25s	remaining: 13m 49s
1903:	learn: 0.0076566	total: 3m 25s	remaining: 14m 33s
1958:	learn: 0.0078139	total: 3m 25s	remaining: 14m 2s
1819:	learn: 0.0084259	total: 3m 25s	remaining: 15m 23s
1958:	learn: 0.0065955	total: 3m 25s	remaining: 14m 2s
1985:	learn: 0.0071447	total: 3m 25s	remaining: 13m 49s
1904:	learn: 0.0076526	total: 3m 25s	remaining: 14m 33s
1959:	learn: 0.0078041	total: 3m 25s	remaining: 14m 2s
1959:	learn: 0.0065894	total: 3m 25s	remaining: 14m 2s
1986:	learn: 0.0071383	total: 3m 25s	remaining: 13m 48s
1820:	learn: 0.0084159	total: 3m 25s	remaining: 15m 23s
1960:	learn: 0.0077982	total: 3m 25s	remaining: 14m 2s
1987:	learn: 0.0071348	total: 3m 25s	remaining: 13m 48s
1905:	learn: 0.0076489	total: 3m 25s	remaining: 14m 33s
1821:	learn: 0.0084093	total: 3m 25s	remaining: 15m 23s
1960:	learn: 0.0065828	total: 3m 25s	remaining: 14m 2s
1961:	learn: 0.0077919	total: 3m 25s	remaining: 14m 2s
1988:	learn: 0.0071282	total: 3m 25s	remaining: 13m 48s
1906:	learn: 0.0076403	total: 3m 25s	remaining: 14m 33s
1822:	learn: 0.0084039	total: 3m 25s	remaining: 15m 22s
1961:	learn: 0.0065760	total: 3m 25s	remaining: 14m 2s
1962:	learn: 0.0077860	total: 3m 25s	remaining: 14m 1s
1907:	learn: 0.0076334	total: 3m 25s	remaining: 14m 32s
1989:	learn: 0.0071217	total: 3m 25s	remaining: 13m 48s
1962:	learn: 0.0065711	total: 3m 25s	remaining: 14m 2s
1823:	learn: 0.0083943	total: 3m 25s	remaining: 15m 22s
1963:	learn: 0.0065651	total: 3m 25s	remaining: 14m 2s
1963:	learn: 0.0077776	total: 3m 25s	remaining: 14m 1s
1990:	learn: 0.0071154	total: 3m 25s	remaining: 13m 48s
1908:	learn: 0.0076259	total: 3m 25s	remaining: 14m 32s
1964:	learn: 0.0065609	total: 3m 25s	remaining: 14m 1s
1824:	learn: 0.0083880	total: 3m 26s	remaining: 15m 22s
1964:	learn: 0.0077704	total: 3m 25s	remaining: 14m 1s
1991:	learn: 0.0071095	total: 3m 26s	remaining: 13m 48s
1909:	learn: 0.0076189	total: 3m 26s	remaining: 14m 32s
1965:	learn: 0.0077609	total: 3m 25s	remaining: 14m 1s
1965:	learn: 0.0065549	total: 3m 25s	remaining: 14m 1s
1825:	learn: 0.0083807	total: 3m 26s	remaining: 15m 22s
1992:	learn: 0.0071035	total: 3m 26s	remaining: 13m 48s
1966:	learn: 0.0065485	total: 3m 26s	remaining: 14m 1s
1966:	learn: 0.0077563	total: 3m 26s	remaining: 14m 1s
1910:	learn: 0.0076116	total: 3m 26s	remaining: 14m 32s
1993:	learn: 0.0070984	total: 3m 26s	remaining: 13m 47s
1826:	learn: 0.0083756	total: 3m 26s	remaining: 15m 22s
1967:	learn: 0.0077475	total: 3m 26s	remaining: 14m 1s
1994:	learn: 0.0070947	total: 3m 26s	remaining: 13m 47s
1967:	learn: 0.0065430	total: 3m 26s	remaining: 14m 1s
1911:	learn: 0.0076071	total: 3m 26s	remaining: 14m 32s
1827:	learn: 0.0083688	total: 3m 26s	remaining: 15m 22s
1968:	learn: 0.0077416	total: 3m 26s	remaining: 14m 1s
1912:	learn: 0.0076007	total: 3m 26s	remaining: 14m 32s
1968:	learn: 0.0065389	total: 3m 26s	remaining: 14m 1s
1995:	learn: 0.0070868	total: 3m 26s	remaining: 13m 47s
1828:	learn: 0.0083596	total: 3m 26s	remaining: 15m 22s
1969:	learn: 0.0077328	total: 3m 26s	remaining: 14m
1913:	learn: 0.0075936	total: 3m 26s	remaining: 14m 32s
1996:	learn: 0.0070827	total: 3m 26s	remaining: 13m 47s
1970:	learn: 0.0077272	total: 3m 26s	remaining: 14m
1969:	learn: 0.0065323	total: 3m 26s	remaining: 14m 1s
1829:	learn: 0.0083506	total: 3m 26s	remaining: 15m 22s
1914:	learn: 0.0075888	total: 3m 26s	remaining: 14m 32s
1997:	learn: 0.0070771	total: 3m 26s	remaining: 13m 47s
1970:	learn: 0.0065256	total: 3m 26s	remaining: 14m 1s
1971:	learn: 0.0077225	total: 3m 26s	remaining: 14m
1915:	learn: 0.0075849	total: 3m 26s	remaining: 14m 31s
1830:	learn: 0.0083405	total: 3m 26s	remaining: 15m 22s
1998:	learn: 0.0070736	total: 3m 26s	remaining: 13m 47s
1971:	learn: 0.0065193	total: 3m 26s	remaining: 14m 1s
1916:	learn: 0.0075778	total: 3m 26s	remaining: 14m 31s
1831:	learn: 0.0083349	total: 3m 26s	remaining: 15m 21s
1972:	learn: 0.0077172	total: 3m 26s	remaining: 14m
1999:	learn: 0.0070672	total: 3m 26s	remaining: 13m 47s
1972:	learn: 0.0065143	total: 3m 26s	remaining: 14m 1s
1917:	learn: 0.0075714	total: 3m 26s	remaining: 14m 31s
1832:	learn: 0.0083240	total: 3m 26s	remaining: 15m 21s
2000:	learn: 0.0070615	total: 3m 26s	remaining: 13m 47s
1973:	learn: 0.0077107	total: 3m 26s	remaining: 14m
1918:	learn: 0.0075652	total: 3m 26s	remaining: 14m 31s
1973:	learn: 0.0065086	total: 3m 26s	remaining: 14m
1833:	learn: 0.0083142	total: 3m 26s	remaining: 15m 21s
2001:	learn: 0.0070523	total: 3m 27s	remaining: 13m 47s
1919:	learn: 0.0075565	total: 3m 26s	remaining: 14m 31s
1974:	learn: 0.0077065	total: 3m 26s	remaining: 14m
1974:	learn: 0.0065023	total: 3m 26s	remaining: 14m
1834:	learn: 0.0083051	total: 3m 27s	remaining: 15m 21s
2002:	learn: 0.0070474	total: 3m 27s	remaining: 13m 46s
1920:	learn: 0.0075510	total: 3m 27s	remaining: 14m 30s
1975:	learn: 0.0077025	total: 3m 26s	remaining: 14m
1975:	learn: 0.0064969	total: 3m 27s	remaining: 14m
1835:	learn: 0.0082969	total: 3m 27s	remaining: 15m 21s
2003:	learn: 0.0070427	total: 3m 27s	remaining: 13m 46s
1976:	learn: 0.0076960	total: 3m 27s	remaining: 14m
1921:	learn: 0.0075425	total: 3m 27s	remaining: 14m 30s
1836:	learn: 0.0082885	total: 3m 27s	remaining: 15m 20s
1976:	learn: 0.0064902	total: 3m 27s	remaining: 14m
2004:	learn: 0.0070369	total: 3m 27s	remaining: 13m 46s
1922:	learn: 0.0075349	total: 3m 27s	remaining: 14m 30s
1977:	learn: 0.0076896	total: 3m 27s	remaining: 14m
1837:	learn: 0.0082820	total: 3m 27s	remaining: 15m 20s
1923:	learn: 0.0075322	total: 3m 27s	remaining: 14m 30s
1977:	learn: 0.0064840	total: 3m 27s	remaining: 14m
2005:	learn: 0.0070292	total: 3m 27s	remaining: 13m 46s
1978:	learn: 0.0076835	total: 3m 27s	remaining: 14m
1838:	learn: 0.0082728	total: 3m 27s	remaining: 15m 20s
1978:	learn: 0.0064802	total: 3m 27s	remaining: 14m
2006:	learn: 0.0070206	total: 3m 27s	remaining: 13m 46s
1924:	learn: 0.0075273	total: 3m 27s	remaining: 14m 30s
1979:	learn: 0.0076799	total: 3m 27s	remaining: 13m 59s
2007:	learn: 0.0070168	total: 3m 27s	remaining: 13m 46s
1925:	learn: 0.0075206	total: 3m 27s	remaining: 14m 30s
1979:	learn: 0.0064754	total: 3m 27s	remaining: 14m
1839:	learn: 0.0082636	total: 3m 27s	remaining: 15m 20s
1980:	learn: 0.0076752	total: 3m 27s	remaining: 13m 59s
2008:	learn: 0.0070078	total: 3m 27s	remaining: 13m 45s
1926:	learn: 0.0075169	total: 3m 27s	remaining: 14m 29s
1840:	learn: 0.0082572	total: 3m 27s	remaining: 15m 20s
1980:	learn: 0.0064697	total: 3m 27s	remaining: 14m
1981:	learn: 0.0076671	total: 3m 27s	remaining: 13m 59s
2009:	learn: 0.0070042	total: 3m 27s	remaining: 13m 45s
1841:	learn: 0.0082495	total: 3m 27s	remaining: 15m 20s
1927:	learn: 0.0075119	total: 3m 27s	remaining: 14m 29s
1981:	learn: 0.0064656	total: 3m 27s	remaining: 14m
1982:	learn: 0.0076606	total: 3m 27s	remaining: 13m 59s
2010:	learn: 0.0069984	total: 3m 27s	remaining: 13m 45s
1928:	learn: 0.0075080	total: 3m 27s	remaining: 14m 29s
1842:	learn: 0.0082393	total: 3m 27s	remaining: 15m 20s
1982:	learn: 0.0064594	total: 3m 27s	remaining: 14m
1983:	learn: 0.0076547	total: 3m 27s	remaining: 13m 59s
2011:	learn: 0.0069909	total: 3m 27s	remaining: 13m 45s
1929:	learn: 0.0075043	total: 3m 27s	remaining: 14m 29s
1983:	learn: 0.0064545	total: 3m 27s	remaining: 14m
1984:	learn: 0.0076506	total: 3m 27s	remaining: 13m 59s
1843:	learn: 0.0082339	total: 3m 28s	remaining: 15m 20s
2012:	learn: 0.0069878	total: 3m 28s	remaining: 13m 45s
1930:	learn: 0.0075006	total: 3m 28s	remaining: 14m 29s
1984:	learn: 0.0064501	total: 3m 28s	remaining: 13m 59s
1985:	learn: 0.0076441	total: 3m 27s	remaining: 13m 59s
1844:	learn: 0.0082275	total: 3m 28s	remaining: 15m 19s
2013:	learn: 0.0069842	total: 3m 28s	remaining: 13m 45s
1931:	learn: 0.0074940	total: 3m 28s	remaining: 14m 29s
1985:	learn: 0.0064454	total: 3m 28s	remaining: 13m 59s
1986:	learn: 0.0076382	total: 3m 28s	remaining: 13m 59s
1845:	learn: 0.0082251	total: 3m 28s	remaining: 15m 19s
2014:	learn: 0.0069806	total: 3m 28s	remaining: 13m 45s
1932:	learn: 0.0074876	total: 3m 28s	remaining: 14m 29s
1986:	learn: 0.0064415	total: 3m 28s	remaining: 13m 59s
1987:	learn: 0.0076329	total: 3m 28s	remaining: 13m 58s
1846:	learn: 0.0082145	total: 3m 28s	remaining: 15m 19s
2015:	learn: 0.0069751	total: 3m 28s	remaining: 13m 45s
1933:	learn: 0.0074837	total: 3m 28s	remaining: 14m 28s
1987:	learn: 0.0064350	total: 3m 28s	remaining: 13m 59s
1988:	learn: 0.0076299	total: 3m 28s	remaining: 13m 58s
1847:	learn: 0.0082045	total: 3m 28s	remaining: 15m 19s
2016:	learn: 0.0069719	total: 3m 28s	remaining: 13m 45s
1934:	learn: 0.0074754	total: 3m 28s	remaining: 14m 28s
1988:	learn: 0.0064289	total: 3m 28s	remaining: 13m 59s
1989:	learn: 0.0076248	total: 3m 28s	remaining: 13m 58s
1848:	learn: 0.0081979	total: 3m 28s	remaining: 15m 19s
1989:	learn: 0.0064234	total: 3m 28s	remaining: 13m 59s
2017:	learn: 0.0069644	total: 3m 28s	remaining: 13m 45s
1990:	learn: 0.0076166	total: 3m 28s	remaining: 13m 58s
1935:	learn: 0.0074717	total: 3m 28s	remaining: 14m 28s
1990:	learn: 0.0064197	total: 3m 28s	remaining: 13m 58s
2018:	learn: 0.0069612	total: 3m 28s	remaining: 13m 44s
1849:	learn: 0.0081922	total: 3m 28s	remaining: 15m 19s
1936:	learn: 0.0074653	total: 3m 28s	remaining: 14m 28s
1991:	learn: 0.0076131	total: 3m 28s	remaining: 13m 58s
1991:	learn: 0.0064140	total: 3m 28s	remaining: 13m 58s
1850:	learn: 0.0081847	total: 3m 28s	remaining: 15m 19s
2019:	learn: 0.0069556	total: 3m 28s	remaining: 13m 44s
1937:	learn: 0.0074599	total: 3m 28s	remaining: 14m 28s
1992:	learn: 0.0064078	total: 3m 28s	remaining: 13m 58s
1992:	learn: 0.0076031	total: 3m 28s	remaining: 13m 58s
2020:	learn: 0.0069499	total: 3m 28s	remaining: 13m 44s
1851:	learn: 0.0081761	total: 3m 28s	remaining: 15m 18s
1938:	learn: 0.0074516	total: 3m 28s	remaining: 14m 28s
1993:	learn: 0.0075968	total: 3m 28s	remaining: 13m 58s
1993:	learn: 0.0064038	total: 3m 28s	remaining: 13m 58s
2021:	learn: 0.0069454	total: 3m 28s	remaining: 13m 44s
1939:	learn: 0.0074482	total: 3m 28s	remaining: 14m 28s
1852:	learn: 0.0081702	total: 3m 29s	remaining: 15m 18s
1994:	learn: 0.0063979	total: 3m 28s	remaining: 13m 58s
1994:	learn: 0.0075940	total: 3m 28s	remaining: 13m 58s
1940:	learn: 0.0074428	total: 3m 29s	remaining: 14m 28s
2022:	learn: 0.0069389	total: 3m 29s	remaining: 13m 44s
1853:	learn: 0.0081628	total: 3m 29s	remaining: 15m 18s
1995:	learn: 0.0063933	total: 3m 29s	remaining: 13m 58s
1995:	learn: 0.0075853	total: 3m 28s	remaining: 13m 57s
2023:	learn: 0.0069337	total: 3m 29s	remaining: 13m 44s
1996:	learn: 0.0075800	total: 3m 29s	remaining: 13m 57s
1941:	learn: 0.0074360	total: 3m 29s	remaining: 14m 27s
1854:	learn: 0.0081556	total: 3m 29s	remaining: 15m 18s
1996:	learn: 0.0063888	total: 3m 29s	remaining: 13m 58s
2024:	learn: 0.0069294	total: 3m 29s	remaining: 13m 44s
1942:	learn: 0.0074320	total: 3m 29s	remaining: 14m 27s
1997:	learn: 0.0075750	total: 3m 29s	remaining: 13m 57s
1997:	learn: 0.0063836	total: 3m 29s	remaining: 13m 57s
1855:	learn: 0.0081450	total: 3m 29s	remaining: 15m 18s
1998:	learn: 0.0075714	total: 3m 29s	remaining: 13m 57s
1943:	learn: 0.0074283	total: 3m 29s	remaining: 14m 27s
2025:	learn: 0.0069262	total: 3m 29s	remaining: 13m 44s
1856:	learn: 0.0081376	total: 3m 29s	remaining: 15m 18s
1998:	learn: 0.0063777	total: 3m 29s	remaining: 13m 57s
1999:	learn: 0.0075675	total: 3m 29s	remaining: 13m 57s
1944:	learn: 0.0074240	total: 3m 29s	remaining: 14m 27s
2026:	learn: 0.0069209	total: 3m 29s	remaining: 13m 44s
1857:	learn: 0.0081312	total: 3m 29s	remaining: 15m 18s
1999:	learn: 0.0063719	total: 3m 29s	remaining: 13m 57s
2000:	learn: 0.0075645	total: 3m 29s	remaining: 13m 57s
1945:	learn: 0.0074176	total: 3m 29s	remaining: 14m 27s
2027:	learn: 0.0069163	total: 3m 29s	remaining: 13m 43s
2000:	learn: 0.0063662	total: 3m 29s	remaining: 13m 57s
1858:	learn: 0.0081240	total: 3m 29s	remaining: 15m 18s
2001:	learn: 0.0075581	total: 3m 29s	remaining: 13m 57s
1946:	learn: 0.0074101	total: 3m 29s	remaining: 14m 27s
2028:	learn: 0.0069118	total: 3m 29s	remaining: 13m 43s
1859:	learn: 0.0081189	total: 3m 29s	remaining: 15m 17s
2001:	learn: 0.0063625	total: 3m 29s	remaining: 13m 57s
2002:	learn: 0.0075527	total: 3m 29s	remaining: 13m 56s
1947:	learn: 0.0074042	total: 3m 29s	remaining: 14m 27s
2029:	learn: 0.0069063	total: 3m 29s	remaining: 13m 43s
1860:	learn: 0.0081092	total: 3m 29s	remaining: 15m 17s
2003:	learn: 0.0075474	total: 3m 29s	remaining: 13m 56s
2002:	learn: 0.0063567	total: 3m 29s	remaining: 13m 57s
1948:	learn: 0.0073999	total: 3m 29s	remaining: 14m 26s
2030:	learn: 0.0069018	total: 3m 29s	remaining: 13m 43s
2004:	learn: 0.0075400	total: 3m 29s	remaining: 13m 56s

1861:	learn: 0.0080998	total: 3m 29s	remaining: 15m 17s
1949:	learn: 0.0073918	total: 3m 29s	remaining: 14m 26s
2031:	learn: 0.0068967	total: 3m 30s	remaining: 13m 43s
2005:	learn: 0.0075370	total: 3m 29s	remaining: 13m 56s
2004:	learn: 0.0063456	total: 3m 29s	remaining: 13m 57s
1862:	learn: 0.0080906	total: 3m 30s	remaining: 15m 17s
2032:	learn: 0.0068928	total: 3m 30s	remaining: 13m 43s
2006:	learn: 0.0075341	total: 3m 29s	remaining: 13m 56s
1950:	learn: 0.0073870	total: 3m 30s	remaining: 14m 26s
2005:	learn: 0.0063417	total: 3m 30s	remaining: 13m 57s
2033:	learn: 0.0068888	total: 3m 30s	remaining: 13m 43s
2007:	learn: 0.0075283	total: 3m 30s	remaining: 13m 56s
1863:	learn: 0.0080859	total: 3m 30s	remaining: 15m 17s
1951:	learn: 0.0073785	total: 3m 30s	remaining: 14m 26s
2006:	learn: 0.0063361	total: 3m 30s	remaining: 13m 56s
2034:	learn: 0.0068828	total: 3m 30s	remaining: 13m 43s
1864:	learn: 0.0080765	total: 3m 30s	remaining: 15m 17s
2008:	learn: 0.0075191	total: 3m 30s	remaining: 13m 55s
1952:	learn: 0.0073751	total: 3m 30s	remaining: 14m 26s
2007:	learn: 0.0063316	total: 3m 30s	remaining: 13m 56s
2035:	learn: 0.0068766	total: 3m 30s	remaining: 13m 42s
1865:	learn: 0.0080743	total: 3m 30s	remaining: 15m 17s
2009:	learn: 0.0075119	total: 3m 30s	remaining: 13m 55s
2008:	learn: 0.0063257	total: 3m 30s	remaining: 13m 56s
1953:	learn: 0.0073715	total: 3m 30s	remaining: 14m 26s
2009:	learn: 0.0063209	total: 3m 30s	remaining: 13m 56s
2036:	learn: 0.0068707	total: 3m 30s	remaining: 13m 42s
2010:	learn: 0.0075051	total: 3m 30s	remaining: 13m 55s
1866:	learn: 0.0080697	total: 3m 30s	remaining: 15m 17s
1954:	learn: 0.0073635	total: 3m 30s	remaining: 14m 26s
2010:	learn: 0.0063173	total: 3m 30s	remaining: 13m 56s
2037:	learn: 0.0068668	total: 3m 30s	remaining: 13m 42s
1867:	learn: 0.0080646	total: 3m 30s	remaining: 15m 16s
2011:	learn: 0.0075018	total: 3m 30s	remaining: 13m 55s
2011:	learn: 0.0063119	total: 3m 30s	remaining: 13m 55s
1955:	learn: 0.0073600	total: 3m 30s	remaining: 14m 26s
2038:	learn: 0.0068634	total: 3m 30s	remaining: 13m 42s
1868:	learn: 0.0080584	total: 3m 30s	remaining: 15m 16s
2012:	learn: 0.0074957	total: 3m 30s	remaining: 13m 55s
2012:	learn: 0.0063062	total: 3m 30s	remaining: 13m 55s
2039:	learn: 0.0068584	total: 3m 30s	remaining: 13m 42s
1869:	learn: 0.0080533	total: 3m 30s	remaining: 15m 16s
1956:	learn: 0.0073531	total: 3m 30s	remaining: 14m 26s
2013:	learn: 0.0074933	total: 3m 30s	remaining: 13m 55s
2013:	learn: 0.0063016	total: 3m 30s	remaining: 13m 55s
2040:	learn: 0.0068520	total: 3m 30s	remaining: 13m 42s
1957:	learn: 0.0073479	total: 3m 30s	remaining: 14m 26s
1870:	learn: 0.0080485	total: 3m 30s	remaining: 15m 16s
2014:	learn: 0.0074859	total: 3m 30s	remaining: 13m 55s
2014:	learn: 0.0062970	total: 3m 30s	remaining: 13m 55s
1958:	learn: 0.0073384	total: 3m 30s	remaining: 14m 25s
2041:	learn: 0.0068468	total: 3m 30s	remaining: 13m 42s
1871:	learn: 0.0080430	total: 3m 31s	remaining: 15m 16s
2015:	learn: 0.0062911	total: 3m 30s	remaining: 13m 55s
2015:	learn: 0.0074779	total: 3m 30s	remaining: 13m 55s
1959:	learn: 0.0073301	total: 3m 31s	remaining: 14m 25s
2042:	learn: 0.0068434	total: 3m 31s	remaining: 13m 42s
2016:	learn: 0.0062868	total: 3m 31s	remaining: 13m 55s
1872:	learn: 0.0080346	total: 3m 31s	remaining: 15m 16s
2016:	learn: 0.0074725	total: 3m 31s	remaining: 13m 55s
2017:	learn: 0.0062809	total: 3m 31s	remaining: 13m 54s
1960:	learn: 0.0073250	total: 3m 31s	remaining: 14m 25s
2043:	learn: 0.0068376	total: 3m 31s	remaining: 13m 42s
2017:	learn: 0.0074682	total: 3m 31s	remaining: 13m 55s
1873:	learn: 0.0080297	total: 3m 31s	remaining: 15m 16s
2018:	learn: 0.0062749	total: 3m 31s	remaining: 13m 54s
2044:	learn: 0.0068314	total: 3m 31s	remaining: 13m 41s
1961:	learn: 0.0073202	total: 3m 31s	remaining: 14m 25s
2018:	learn: 0.0074622	total: 3m 31s	remaining: 13m 54s
1874:	learn: 0.0080261	total: 3m 31s	remaining: 15m 15s
2045:	learn: 0.0068255	total: 3m 31s	remaining: 13m 41s
2019:	learn: 0.0062696	total: 3m 31s	remaining: 13m 54s
1962:	learn: 0.0073130	total: 3m 31s	remaining: 14m 25s
2046:	learn: 0.0068204	total: 3m 31s	remaining: 13m 41s
2019:	learn: 0.0074526	total: 3m 31s	remaining: 13m 54s
1875:	learn: 0.0080192	total: 3m 31s	remaining: 15m 15s
2020:	learn: 0.0062640	total: 3m 31s	remaining: 13m 54s
1963:	learn: 0.0073049	total: 3m 31s	remaining: 14m 25s
2047:	learn: 0.0068134	total: 3m 31s	remaining: 13m 41s
2020:	learn: 0.0074480	total: 3m 31s	remaining: 13m 54s
2021:	learn: 0.0062581	total: 3m 31s	remaining: 13m 54s
1964:	learn: 0.0072965	total: 3m 31s	remaining: 14m 25s
1876:	learn: 0.0080124	total: 3m 31s	remaining: 15m 15s
2048:	learn: 0.0068071	total: 3m 31s	remaining: 13m 41s
2022:	learn: 0.0062523	total: 3m 31s	remaining: 13m 54s
2021:	learn: 0.0074418	total: 3m 31s	remaining: 13m 54s
1965:	learn: 0.0072876	total: 3m 31s	remaining: 14m 25s
1877:	learn: 0.0080067	total: 3m 31s	remaining: 15m 15s
2049:	learn: 0.0068017	total: 3m 31s	remaining: 13m 41s
2023:	learn: 0.0062471	total: 3m 31s	remaining: 13m 54s
2022:	learn: 0.0074384	total: 3m 31s	remaining: 13m 54s
1878:	learn: 0.0079998	total: 3m 31s	remaining: 15m 15s
1966:	learn: 0.0072819	total: 3m 31s	remaining: 14m 25s
2050:	learn: 0.0067973	total: 3m 31s	remaining: 13m 41s
2024:	learn: 0.0062422	total: 3m 31s	remaining: 13m 53s
2023:	learn: 0.0074306	total: 3m 31s	remaining: 13m 54s
1967:	learn: 0.0072781	total: 3m 31s	remaining: 14m 24s
1879:	learn: 0.0079902	total: 3m 31s	remaining: 15m 15s
2051:	learn: 0.0067931	total: 3m 31s	remaining: 13m 40s
2025:	learn: 0.0062353	total: 3m 31s	remaining: 13m 53s
2024:	learn: 0.0074242	total: 3m 31s	remaining: 13m 54s
1968:	learn: 0.0072717	total: 3m 31s	remaining: 14m 24s
2052:	learn: 0.0067861	total: 3m 32s	remaining: 13m 40s
1880:	learn: 0.0079780	total: 3m 32s	remaining: 15m 15s
2026:	learn: 0.0062304	total: 3m 31s	remaining: 13m 53s
1969:	learn: 0.0072660	total: 3m 32s	remaining: 14m 24s
2025:	learn: 0.0074173	total: 3m 31s	remaining: 13m 54s
2053:	learn: 0.0067822	total: 3m 32s	remaining: 13m 40s
1881:	learn: 0.0079723	total: 3m 32s	remaining: 15m 15s
2027:	learn: 0.0062243	total: 3m 32s	remaining: 13m 53s
1970:	learn: 0.0072619	total: 3m 32s	remaining: 14m 24s
2026:	learn: 0.0074114	total: 3m 32s	remaining: 13m 54s
2054:	learn: 0.0067778	total: 3m 32s	remaining: 13m 40s
1882:	learn: 0.0079673	total: 3m 32s	remaining: 15m 14s
1971:	learn: 0.0072560	total: 3m 32s	remaining: 14m 24s
2028:	learn: 0.0062182	total: 3m 32s	remaining: 13m 53s
1883:	learn: 0.0079582	total: 3m 32s	remaining: 15m 14s
2027:	learn: 0.0074033	total: 3m 32s	remaining: 13m 54s
2055:	learn: 0.0067718	total: 3m 32s	remaining: 13m 40s
1972:	learn: 0.0072525	total: 3m 32s	remaining: 14m 23s
2029:	learn: 0.0062129	total: 3m 32s	remaining: 13m 53s
2028:	learn: 0.0073961	total: 3m 32s	remaining: 13m 53s
1884:	learn: 0.0079517	total: 3m 32s	remaining: 15m 14s
2056:	learn: 0.0067635	total: 3m 32s	remaining: 13m 40s
1973:	learn: 0.0072481	total: 3m 32s	remaining: 14m 23s
2030:	learn: 0.0062068	total: 3m 32s	remaining: 13m 53s
1885:	learn: 0.0079420	total: 3m 32s	remaining: 15m 14s
2029:	learn: 0.0073894	total: 3m 32s	remaining: 13m 53s
2057:	learn: 0.0067581	total: 3m 32s	remaining: 13m 40s
1974:	learn: 0.0072434	total: 3m 32s	remaining: 14m 23s
2031:	learn: 0.0062033	total: 3m 32s	remaining: 13m 53s
2030:	learn: 0.0073818	total: 3m 32s	remaining: 13m 53s
1886:	learn: 0.0079371	total: 3m 32s	remaining: 15m 14s
2058:	learn: 0.0067521	total: 3m 32s	remaining: 13m 40s
2032:	learn: 0.0061974	total: 3m 32s	remaining: 13m 53s
1975:	learn: 0.0072346	total: 3m 32s	remaining: 14m 23s
2031:	learn: 0.0073762	total: 3m 32s	remaining: 13m 53s
2059:	learn: 0.0067473	total: 3m 32s	remaining: 13m 40s
2033:	learn: 0.0061938	total: 3m 32s	remaining: 13m 52s
1976:	learn: 0.0072256	total: 3m 32s	remaining: 14m 23s
1887:	learn: 0.0079282	total: 3m 32s	remaining: 15m 14s
2032:	learn: 0.0073711	total: 3m 32s	remaining: 13m 53s
1977:	learn: 0.0072213	total: 3m 32s	remaining: 14m 23s
2060:	learn: 0.0067443	total: 3m 32s	remaining: 13m 39s
2034:	learn: 0.0061887	total: 3m 32s	remaining: 13m 52s
0185966	total: 2m	remaining: 16m 37s
1106:	learn: 0.01881888:	learn: 0.0079205	total: 3m 32s	remaining: 15m 14s
2033:	learn: 0.0073638	total: 3m 32s	remaining: 13m 53s
1978:	learn: 0.0072119	total: 3m 32s	remaining: 14m 22s
2061:	learn: 0.0067379	total: 3m 32s	remaining: 13m 39s
2035:	learn: 0.0061848	total: 3m 32s	remaining: 13m 52s
1889:	learn: 0.0079134	total: 3m 32s	remaining: 15m 13s
2034:	learn: 0.0073568	total: 3m 32s	remaining: 13m 53s
1979:	learn: 0.0072076	total: 3m 32s	remaining: 14m 22s
2036:	learn: 0.0061805	total: 3m 32s	remaining: 13m 52s
2062:	learn: 0.0067322	total: 3m 33s	remaining: 13m 39s
1890:	learn: 0.0079082	total: 3m 33s	remaining: 15m 13s
2035:	learn: 0.0073500	total: 3m 32s	remaining: 13m 53s
1980:	learn: 0.0072043	total: 3m 33s	remaining: 14m 22s
2037:	learn: 0.0061746	total: 3m 33s	remaining: 13m 52s
1891:	learn: 0.0079025	total: 3m 33s	remaining: 15m 13s
2063:	learn: 0.0067284	total: 3m 33s	remaining: 13m 39s
2036:	learn: 0.0073427	total: 3m 33s	remaining: 13m 52s
2038:	learn: 0.0061675	total: 3m 33s	remaining: 13m 52s
1981:	learn: 0.0071992	total: 3m 33s	remaining: 14m 22s
2064:	learn: 0.0067242	total: 3m 33s	remaining: 13m 39s
1892:	learn: 0.0078936	total: 3m 33s	remaining: 15m 13s
2037:	learn: 0.0073333	total: 3m 33s	remaining: 13m 52s
2039:	learn: 0.0061618	total: 3m 33s	remaining: 13m 51s
1982:	learn: 0.0071953	total: 3m 33s	remaining: 14m 22s
2065:	learn: 0.0067179	total: 3m 33s	remaining: 13m 39s
1893:	learn: 0.0078836	total: 3m 33s	remaining: 15m 13s
2038:	learn: 0.0073237	total: 3m 33s	remaining: 13m 52s
2040:	learn: 0.0061576	total: 3m 33s	remaining: 13m 51s
1983:	learn: 0.0071916	total: 3m 33s	remaining: 14m 22s
2066:	learn: 0.0067156	total: 3m 33s	remaining: 13m 39s
1894:	learn: 0.0078745	total: 3m 33s	remaining: 15m 13s
2041:	learn: 0.0061518	total: 3m 33s	remaining: 13m 51s
2039:	learn: 0.0073183	total: 3m 33s	remaining: 13m 52s
1984:	learn: 0.0071858	total: 3m 33s	remaining: 14m 22s
1895:	learn: 0.0078686	total: 3m 33s	remaining: 15m 12s
2067:	learn: 0.0067109	total: 3m 33s	remaining: 13m 39s
2042:	learn: 0.0061466	total: 3m 33s	remaining: 13m 51s
1985:	learn: 0.0071799	total: 3m 33s	remaining: 14m 21s
2040:	learn: 0.0073123	total: 3m 33s	remaining: 13m 52s
1896:	learn: 0.0078630	total: 3m 33s	remaining: 15m 12s
2068:	learn: 0.0067059	total: 3m 33s	remaining: 13m 39s
1986:	learn: 0.0071757	total: 3m 33s	remaining: 14m 21s
1897:	learn: 0.0078574	total: 3m 33s	remaining: 15m 12s
2043:	learn: 0.0061412	total: 3m 33s	remaining: 13m 51s
2069:	learn: 0.0067022	total: 3m 33s	remaining: 13m 38s
2041:	learn: 0.0073090	total: 3m 33s	remaining: 13m 52s
1898:	learn: 0.0078525	total: 3m 33s	remaining: 15m 12s
1987:	learn: 0.0071712	total: 3m 33s	remaining: 14m 21s
2044:	learn: 0.0061375	total: 3m 33s	remaining: 13m 51s
2042:	learn: 0.0073023	total: 3m 33s	remaining: 13m 52s
2070:	learn: 0.0066981	total: 3m 33s	remaining: 13m 38s
2045:	learn: 0.0061328	total: 3m 33s	remaining: 13m 51s
1899:	learn: 0.0078472	total: 3m 33s	remaining: 15m 12s
1988:	learn: 0.0071662	total: 3m 33s	remaining: 14m 21s
2043:	learn: 0.0072948	total: 3m 33s	remaining: 13m 52s
2046:	learn: 0.0061274	total: 3m 33s	remaining: 13m 51s
2071:	learn: 0.0066936	total: 3m 34s	remaining: 13m 38s
1989:	learn: 0.0071613	total: 3m 34s	remaining: 14m 21s
2044:	learn: 0.0072881	total: 3m 33s	remaining: 13m 52s
1900:	learn: 0.0078402	total: 3m 34s	remaining: 15m 12s
2072:	learn: 0.0066858	total: 3m 34s	remaining: 13m 38s
2047:	learn: 0.0061218	total: 3m 34s	remaining: 13m 50s
2045:	learn: 0.0072810	total: 3m 33s	remaining: 13m 51s
1990:	learn: 0.0071567	total: 3m 34s	remaining: 14m 21s
2073:	learn: 0.0066799	total: 3m 34s	remaining: 13m 38s
1901:	learn: 0.0078357	total: 3m 34s	remaining: 15m 11s
2048:	learn: 0.0061170	total: 3m 34s	remaining: 13m 50s
2046:	learn: 0.0072745	total: 3m 34s	remaining: 13m 51s
1991:	learn: 0.0071497	total: 3m 34s	remaining: 14m 21s
2074:	learn: 0.0066728	total: 3m 34s	remaining: 13m 38s
2049:	learn: 0.0061125	total: 3m 34s	remaining: 13m 50s
1902:	learn: 0.0078266	total: 3m 34s	remaining: 15m 11s
1992:	learn: 0.0071434	total: 3m 34s	remaining: 14m 21s
2047:	learn: 0.0072672	total: 3m 34s	remaining: 13m 51s
2050:	learn: 0.0061068	total: 3m 34s	remaining: 13m 50s
1903:	learn: 0.0078183	total: 3m 34s	remaining: 15m 11s
2075:	learn: 0.0066674	total: 3m 34s	remaining: 13m 38s
1993:	learn: 0.0071385	total: 3m 34s	remaining: 14m 20s
2048:	learn: 0.0072578	total: 3m 34s	remaining: 13m 51s
1904:	learn: 0.0078124	total: 3m 34s	remaining: 15m 11s
2051:	learn: 0.0061012	total: 3m 34s	remaining: 13m 50s
2049:	learn: 0.0072508	total: 3m 34s	remaining: 13m 51s
2076:	learn: 0.0066638	total: 3m 34s	remaining: 13m 38s
1994:	learn: 0.0071335	total: 3m 34s	remaining: 14m 20s
1905:	learn: 0.0078032	total: 3m 34s	remaining: 15m 11s
2052:	learn: 0.0060954	total: 3m 34s	remaining: 13m 50s
2077:	learn: 0.0066579	total: 3m 34s	remaining: 13m 38s
2050:	learn: 0.0072466	total: 3m 34s	remaining: 13m 51s
1995:	learn: 0.0071274	total: 3m 34s	remaining: 14m 20s
1906:	learn: 0.0077934	total: 3m 34s	remaining: 15m 10s
2078:	learn: 0.0066523	total: 3m 34s	remaining: 13m 38s
2053:	learn: 0.0060897	total: 3m 34s	remaining: 13m 50s
2051:	learn: 0.0072393	total: 3m 34s	remaining: 13m 51s
1996:	learn: 0.0071240	total: 3m 34s	remaining: 14m 20s
1907:	learn: 0.0077890	total: 3m 34s	remaining: 15m 10s
2079:	learn: 0.0066473	total: 3m 34s	remaining: 13m 37s
2054:	learn: 0.0060847	total: 3m 34s	remaining: 13m 50s
2052:	learn: 0.0072324	total: 3m 34s	remaining: 13m 50s
1997:	learn: 0.0071169	total: 3m 34s	remaining: 14m 20s
1908:	learn: 0.0077836	total: 3m 34s	remaining: 15m 10s
2080:	learn: 0.0066423	total: 3m 34s	remaining: 13m 37s
2055:	learn: 0.0060808	total: 3m 34s	remaining: 13m 50s
2053:	learn: 0.0072261	total: 3m 34s	remaining: 13m 50s
1998:	learn: 0.0071135	total: 3m 34s	remaining: 14m 20s
1909:	learn: 0.0077790	total: 3m 34s	remaining: 15m 10s
2081:	learn: 0.0066383	total: 3m 34s	remaining: 13m 37s
2056:	learn: 0.0060759	total: 3m 34s	remaining: 13m 49s
1999:	learn: 0.0071087	total: 3m 35s	remaining: 14m 20s
2054:	learn: 0.0072192	total: 3m 34s	remaining: 13m 50s
1910:	learn: 0.0077747	total: 3m 35s	remaining: 15m 10s
2057:	learn: 0.0060711	total: 3m 34s	remaining: 13m 49s
2082:	learn: 0.0066342	total: 3m 35s	remaining: 13m 37s
2055:	learn: 0.0072136	total: 3m 34s	remaining: 13m 50s
2000:	learn: 0.0071060	total: 3m 35s	remaining: 14m 19s
1911:	learn: 0.0077679	total: 3m 35s	remaining: 15m 10s
2058:	learn: 0.0060644	total: 3m 35s	remaining: 13m 49s
2083:	learn: 0.0066297	total: 3m 35s	remaining: 13m 37s
2001:	learn: 0.0071010	total: 3m 35s	remaining: 14m 19s
2056:	learn: 0.0072108	total: 3m 35s	remaining: 13m 50s
1912:	learn: 0.0077638	total: 3m 35s	remaining: 15m 10s
2059:	learn: 0.0060594	total: 3m 35s	remaining: 13m 49s
2084:	learn: 0.0066241	total: 3m 35s	remaining: 13m 37s
2002:	learn: 0.0070956	total: 3m 35s	remaining: 14m 19s
2057:	learn: 0.0072040	total: 3m 35s	remaining: 13m 50s
1913:	learn: 0.0077568	total: 3m 35s	remaining: 15m 10s
2003:	learn: 0.0070914	total: 3m 35s	remaining: 14m 19s
2058:	learn: 0.0071951	total: 3m 35s	remaining: 13m 50s
2085:	learn: 0.0066171	total: 3m 35s	remaining: 13m 37s
2060:	learn: 0.0060550	total: 3m 35s	remaining: 13m 49s
2086:	learn: 0.0066124	total: 3m 35s	remaining: 13m 37s
2059:	learn: 0.0071884	total: 3m 35s	remaining: 13m 50s
1914:	learn: 0.0077482	total: 3m 35s	remaining: 15m 9s
2061:	learn: 0.0060501	total: 3m 35s	remaining: 13m 49s
2004:	learn: 0.0070866	total: 3m 35s	remaining: 14m 19s
2060:	learn: 0.0071858	total: 3m 35s	remaining: 13m 49s
2087:	learn: 0.0066055	total: 3m 35s	remaining: 13m 36s
1915:	learn: 0.0077395	total: 3m 35s	remaining: 15m 9s
2062:	learn: 0.0060442	total: 3m 35s	remaining: 13m 49s
2088:	learn: 0.0066019	total: 3m 35s	remaining: 13m 36s
2005:	learn: 0.0070814	total: 3m 35s	remaining: 14m 19s
2061:	learn: 0.0071805	total: 3m 35s	remaining: 13m 49s
1916:	learn: 0.0077350	total: 3m 35s	remaining: 15m 9s
2089:	learn: 0.0065969	total: 3m 35s	remaining: 13m 36s
2006:	learn: 0.0070768	total: 3m 35s	remaining: 14m 19s
2062:	learn: 0.0071777	total: 3m 35s	remaining: 13m 49s
2063:	learn: 0.0060387	total: 3m 35s	remaining: 13m 49s

1917:	learn: 0.0077291	total: 3m 35s	remaining: 15m 9s
2064:	learn: 0.0060333	total: 3m 35s	remaining: 13m 49s
2090:	learn: 0.0065937	total: 3m 35s	remaining: 13m 36s
2063:	learn: 0.0071711	total: 3m 35s	remaining: 13m 49s
2007:	learn: 0.0070719	total: 3m 35s	remaining: 14m 19s
1918:	learn: 0.0077210	total: 3m 35s	remaining: 15m 9s
2064:	learn: 0.0071645	total: 3m 35s	remaining: 13m 49s
2065:	learn: 0.0060275	total: 3m 35s	remaining: 13m 48s
2091:	learn: 0.0065888	total: 3m 35s	remaining: 13m 36s
2008:	learn: 0.0070656	total: 3m 35s	remaining: 14m 19s
2065:	learn: 0.0071615	total: 3m 35s	remaining: 13m 49s
1919:	learn: 0.0077162	total: 3m 36s	remaining: 15m 9s
2066:	learn: 0.0060222	total: 3m 35s	remaining: 13m 48s
2009:	learn: 0.0070622	total: 3m 36s	remaining: 14m 18s
2066:	learn: 0.0071556	total: 3m 35s	remaining: 13m 48s
2092:	learn: 0.0065827	total: 3m 36s	remaining: 13m 36s
1920:	learn: 0.0077070	total: 3m 36s	remaining: 15m 9s
2067:	learn: 0.0060172	total: 3m 36s	remaining: 13m 48s
2010:	learn: 0.0070585	total: 3m 36s	remaining: 14m 18s
2067:	learn: 0.0071498	total: 3m 36s	remaining: 13m 48s
2093:	learn: 0.0065754	total: 3m 36s	remaining: 13m 36s
2068:	learn: 0.0060122	total: 3m 36s	remaining: 13m 48s
1921:	learn: 0.0077024	total: 3m 36s	remaining: 15m 8s
2011:	learn: 0.0070533	total: 3m 36s	remaining: 14m 18s
2068:	learn: 0.0071433	total: 3m 36s	remaining: 13m 48s
2094:	learn: 0.0065724	total: 3m 36s	remaining: 13m 36s
2069:	learn: 0.0060071	total: 3m 36s	remaining: 13m 48s
1922:	learn: 0.0076960	total: 3m 36s	remaining: 15m 8s
2012:	learn: 0.0070475	total: 3m 36s	remaining: 14m 18s
2095:	learn: 0.0065663	total: 3m 36s	remaining: 13m 36s
2070:	learn: 0.0060020	total: 3m 36s	remaining: 13m 48s
2069:	learn: 0.0071338	total: 3m 36s	remaining: 13m 48s
1923:	learn: 0.0076886	total: 3m 36s	remaining: 15m 8s
2013:	learn: 0.0070431	total: 3m 36s	remaining: 14m 18s
2070:	learn: 0.0071282	total: 3m 36s	remaining: 13m 48s
2096:	learn: 0.0065643	total: 3m 36s	remaining: 13m 35s
2071:	learn: 0.0059982	total: 3m 36s	remaining: 13m 48s
1924:	learn: 0.0076850	total: 3m 36s	remaining: 15m 8s
2014:	learn: 0.0070387	total: 3m 36s	remaining: 14m 18s
2072:	learn: 0.0059946	total: 3m 36s	remaining: 13m 47s
2071:	learn: 0.0071232	total: 3m 36s	remaining: 13m 48s
2097:	learn: 0.0065611	total: 3m 36s	remaining: 13m 36s
2015:	learn: 0.0070354	total: 3m 36s	remaining: 14m 18s
1925:	learn: 0.0076775	total: 3m 36s	remaining: 15m 8s
2073:	learn: 0.0059895	total: 3m 36s	remaining: 13m 47s
2072:	learn: 0.0071162	total: 3m 36s	remaining: 13m 48s
2098:	learn: 0.0065544	total: 3m 36s	remaining: 13m 35s
2016:	learn: 0.0070312	total: 3m 36s	remaining: 14m 17s
2074:	learn: 0.0059853	total: 3m 36s	remaining: 13m 47s
1926:	learn: 0.0076732	total: 3m 36s	remaining: 15m 8s
2073:	learn: 0.0071102	total: 3m 36s	remaining: 13m 48s
2099:	learn: 0.0065502	total: 3m 36s	remaining: 13m 35s
2075:	learn: 0.0059805	total: 3m 36s	remaining: 13m 47s
2017:	learn: 0.0070275	total: 3m 36s	remaining: 14m 17s
1927:	learn: 0.0076686	total: 3m 36s	remaining: 15m 8s
2074:	learn: 0.0071034	total: 3m 36s	remaining: 13m 47s
2076:	learn: 0.0059767	total: 3m 36s	remaining: 13m 47s
2100:	learn: 0.0065471	total: 3m 36s	remaining: 13m 35s
2018:	learn: 0.0070201	total: 3m 36s	remaining: 14m 17s
1928:	learn: 0.0076639	total: 3m 37s	remaining: 15m 8s
2077:	learn: 0.0059734	total: 3m 36s	remaining: 13m 47s
2075:	learn: 0.0070986	total: 3m 36s	remaining: 13m 47s
2101:	learn: 0.0065420	total: 3m 37s	remaining: 13m 35s
2019:	learn: 0.0070165	total: 3m 37s	remaining: 14m 17s
2078:	learn: 0.0059701	total: 3m 37s	remaining: 13m 46s
1929:	learn: 0.0076587	total: 3m 37s	remaining: 15m 7s
2076:	learn: 0.0070928	total: 3m 37s	remaining: 13m 47s
2102:	learn: 0.0065355	total: 3m 37s	remaining: 13m 35s
2079:	learn: 0.0059653	total: 3m 37s	remaining: 13m 46s
2020:	learn: 0.0070126	total: 3m 37s	remaining: 14m 17s
1930:	learn: 0.0076556	total: 3m 37s	remaining: 15m 7s
2077:	learn: 0.0070886	total: 3m 37s	remaining: 13m 47s
2103:	learn: 0.0065285	total: 3m 37s	remaining: 13m 35s
2080:	learn: 0.0059600	total: 3m 37s	remaining: 13m 46s
1931:	learn: 0.0076510	total: 3m 37s	remaining: 15m 7s
2021:	learn: 0.0070069	total: 3m 37s	remaining: 14m 17s
2078:	learn: 0.0070817	total: 3m 37s	remaining: 13m 47s
2104:	learn: 0.0065235	total: 3m 37s	remaining: 13m 35s
2081:	learn: 0.0059554	total: 3m 37s	remaining: 13m 46s
1932:	learn: 0.0076450	total: 3m 37s	remaining: 15m 7s
2022:	learn: 0.0070023	total: 3m 37s	remaining: 14m 17s
2079:	learn: 0.0070756	total: 3m 37s	remaining: 13m 47s
2023:	learn: 0.0069965	total: 3m 37s	remaining: 14m 16s
2082:	learn: 0.0059499	total: 3m 37s	remaining: 13m 46s
1933:	learn: 0.0076376	total: 3m 37s	remaining: 15m 7s
2105:	learn: 0.0065196	total: 3m 37s	remaining: 13m 35s
2024:	learn: 0.0069926	total: 3m 37s	remaining: 14m 16s
2080:	learn: 0.0070727	total: 3m 37s	remaining: 13m 47s
2083:	learn: 0.0059452	total: 3m 37s	remaining: 13m 46s
2106:	learn: 0.0065129	total: 3m 37s	remaining: 13m 35s
1934:	learn: 0.0076324	total: 3m 37s	remaining: 15m 7s
2025:	learn: 0.0069891	total: 3m 37s	remaining: 14m 16s
2107:	learn: 0.0065110	total: 3m 37s	remaining: 13m 35s
2084:	learn: 0.0059424	total: 3m 37s	remaining: 13m 46s
2081:	learn: 0.0070676	total: 3m 37s	remaining: 13m 47s
1935:	learn: 0.0076279	total: 3m 37s	remaining: 15m 6s
2026:	learn: 0.0069848	total: 3m 37s	remaining: 14m 16s
2108:	learn: 0.0065070	total: 3m 37s	remaining: 13m 34s
2085:	learn: 0.0059385	total: 3m 37s	remaining: 13m 45s
2082:	learn: 0.0070641	total: 3m 37s	remaining: 13m 47s
1936:	learn: 0.0076223	total: 3m 37s	remaining: 15m 6s
2027:	learn: 0.0069790	total: 3m 37s	remaining: 14m 16s
2109:	learn: 0.0065006	total: 3m 37s	remaining: 13m 34s
2086:	learn: 0.0059327	total: 3m 37s	remaining: 13m 45s
1937:	learn: 0.0076159	total: 3m 37s	remaining: 15m 6s
2083:	learn: 0.0070555	total: 3m 37s	remaining: 13m 47s
2028:	learn: 0.0069747	total: 3m 37s	remaining: 14m 16s
2110:	learn: 0.0064971	total: 3m 37s	remaining: 13m 34s
2087:	learn: 0.0059288	total: 3m 37s	remaining: 13m 45s
2084:	learn: 0.0070498	total: 3m 37s	remaining: 13m 47s
1938:	learn: 0.0076066	total: 3m 38s	remaining: 15m 6s
2029:	learn: 0.0069690	total: 3m 38s	remaining: 14m 16s
2111:	learn: 0.0064918	total: 3m 38s	remaining: 13m 34s
2085:	learn: 0.0070440	total: 3m 37s	remaining: 13m 46s
2088:	learn: 0.0059233	total: 3m 38s	remaining: 13m 45s
2030:	learn: 0.0069642	total: 3m 38s	remaining: 14m 15s
2112:	learn: 0.0064867	total: 3m 38s	remaining: 13m 34s
2086:	learn: 0.0070382	total: 3m 38s	remaining: 13m 46s
1939:	learn: 0.0075997	total: 3m 38s	remaining: 15m 6s
2113:	learn: 0.0064820	total: 3m 38s	remaining: 13m 34s
2089:	learn: 0.0059195	total: 3m 38s	remaining: 13m 45s
2031:	learn: 0.0069580	total: 3m 38s	remaining: 14m 15s
2087:	learn: 0.0070346	total: 3m 38s	remaining: 13m 46s
1940:	learn: 0.0075952	total: 3m 38s	remaining: 15m 6s
2114:	learn: 0.0064781	total: 3m 38s	remaining: 13m 33s
2090:	learn: 0.0059153	total: 3m 38s	remaining: 13m 45s
2032:	learn: 0.0069538	total: 3m 38s	remaining: 14m 15s
2088:	learn: 0.0070282	total: 3m 38s	remaining: 13m 46s
1941:	learn: 0.0075908	total: 3m 38s	remaining: 15m 6s
2091:	learn: 0.0059113	total: 3m 38s	remaining: 13m 45s
2115:	learn: 0.0064710	total: 3m 38s	remaining: 13m 33s
2033:	learn: 0.0069494	total: 3m 38s	remaining: 14m 15s
2089:	learn: 0.0070181	total: 3m 38s	remaining: 13m 46s
1942:	learn: 0.0075822	total: 3m 38s	remaining: 15m 5s
2034:	learn: 0.0069445	total: 3m 38s	remaining: 14m 15s
2092:	learn: 0.0059067	total: 3m 38s	remaining: 13m 45s
2116:	learn: 0.0064666	total: 3m 38s	remaining: 13m 33s
1943:	learn: 0.0075736	total: 3m 38s	remaining: 15m 5s
2090:	learn: 0.0070124	total: 3m 38s	remaining: 13m 46s
2035:	learn: 0.0069405	total: 3m 38s	remaining: 14m 15s
2117:	learn: 0.0064626	total: 3m 38s	remaining: 13m 33s
2093:	learn: 0.0059011	total: 3m 38s	remaining: 13m 45s
2091:	learn: 0.0070073	total: 3m 38s	remaining: 13m 46s
1944:	learn: 0.0075664	total: 3m 38s	remaining: 15m 5s
2036:	learn: 0.0069350	total: 3m 38s	remaining: 14m 14s
2118:	learn: 0.0064572	total: 3m 38s	remaining: 13m 33s
2094:	learn: 0.0058969	total: 3m 38s	remaining: 13m 45s
2092:	learn: 0.0070024	total: 3m 38s	remaining: 13m 45s
1945:	learn: 0.0075605	total: 3m 38s	remaining: 15m 5s
2095:	learn: 0.0058916	total: 3m 38s	remaining: 13m 44s
2037:	learn: 0.0069293	total: 3m 38s	remaining: 14m 14s
2119:	learn: 0.0064499	total: 3m 38s	remaining: 13m 33s
2093:	learn: 0.0069974	total: 3m 38s	remaining: 13m 45s
1946:	learn: 0.0075537	total: 3m 38s	remaining: 15m 5s
2120:	learn: 0.0064444	total: 3m 38s	remaining: 13m 33s
2096:	learn: 0.0058862	total: 3m 38s	remaining: 13m 44s
2038:	learn: 0.0069245	total: 3m 38s	remaining: 14m 14s
2094:	learn: 0.0069918	total: 3m 38s	remaining: 13m 45s
2121:	learn: 0.0064403	total: 3m 39s	remaining: 13m 33s
1947:	learn: 0.0075489	total: 3m 39s	remaining: 15m 5s
2039:	learn: 0.0069159	total: 3m 39s	remaining: 14m 14s
2095:	learn: 0.0069890	total: 3m 38s	remaining: 13m 45s
2097:	learn: 0.0058834	total: 3m 38s	remaining: 13m 44s
2122:	learn: 0.0064339	total: 3m 39s	remaining: 13m 32s
2040:	learn: 0.0069124	total: 3m 39s	remaining: 14m 14s
1948:	learn: 0.0075406	total: 3m 39s	remaining: 15m 5s
2096:	learn: 0.0069841	total: 3m 39s	remaining: 13m 45s
2098:	learn: 0.0058802	total: 3m 39s	remaining: 13m 44s
2123:	learn: 0.0064300	total: 3m 39s	remaining: 13m 32s
2041:	learn: 0.0069087	total: 3m 39s	remaining: 14m 14s
1949:	learn: 0.0075321	total: 3m 39s	remaining: 15m 5s
2099:	learn: 0.0058762	total: 3m 39s	remaining: 13m 44s
2097:	learn: 0.0069765	total: 3m 39s	remaining: 13m 45s
2124:	learn: 0.0064241	total: 3m 39s	remaining: 13m 32s
2042:	learn: 0.0069030	total: 3m 39s	remaining: 14m 14s
2125:	learn: 0.0064209	total: 3m 39s	remaining: 13m 32s
1950:	learn: 0.0075274	total: 3m 39s	remaining: 15m 5s
2098:	learn: 0.0069728	total: 3m 39s	remaining: 13m 45s
2100:	learn: 0.0058717	total: 3m 39s	remaining: 13m 44s
2126:	learn: 0.0064184	total: 3m 39s	remaining: 13m 32s
2043:	learn: 0.0068982	total: 3m 39s	remaining: 14m 14s
2101:	learn: 0.0058669	total: 3m 39s	remaining: 13m 44s
2099:	learn: 0.0069672	total: 3m 39s	remaining: 13m 45s
1951:	learn: 0.0075210	total: 3m 39s	remaining: 15m 4s
2127:	learn: 0.0064122	total: 3m 39s	remaining: 13m 32s
2044:	learn: 0.0068939	total: 3m 39s	remaining: 14m 13s
2102:	learn: 0.0058641	total: 3m 39s	remaining: 13m 44s
1952:	learn: 0.0075167	total: 3m 39s	remaining: 15m 4s
2100:	learn: 0.0069584	total: 3m 39s	remaining: 13m 45s
2128:	learn: 0.0064084	total: 3m 39s	remaining: 13m 31s
2045:	learn: 0.0068898	total: 3m 39s	remaining: 14m 13s
1953:	learn: 0.0075122	total: 3m 39s	remaining: 15m 4s
2103:	learn: 0.0058593	total: 3m 39s	remaining: 13m 44s
2101:	learn: 0.0069540	total: 3m 39s	remaining: 13m 45s
2046:	learn: 0.0068850	total: 3m 39s	remaining: 14m 13s
2129:	learn: 0.0064037	total: 3m 39s	remaining: 13m 31s
1954:	learn: 0.0075056	total: 3m 39s	remaining: 15m 4s
2104:	learn: 0.0058545	total: 3m 39s	remaining: 13m 44s
2130:	learn: 0.0064004	total: 3m 39s	remaining: 13m 31s
2047:	learn: 0.0068794	total: 3m 39s	remaining: 14m 13s
2102:	learn: 0.0069476	total: 3m 39s	remaining: 13m 44s
1955:	learn: 0.0075008	total: 3m 39s	remaining: 15m 4s
2048:	learn: 0.0068757	total: 3m 39s	remaining: 14m 13s
2105:	learn: 0.0058513	total: 3m 39s	remaining: 13m 43s
2131:	learn: 0.0063932	total: 3m 39s	remaining: 13m 31s
2103:	learn: 0.0069425	total: 3m 39s	remaining: 13m 44s
1956:	learn: 0.0074917	total: 3m 39s	remaining: 15m 4s
2049:	learn: 0.0068719	total: 3m 39s	remaining: 14m 12s
2106:	learn: 0.0058467	total: 3m 39s	remaining: 13m 43s
2104:	learn: 0.0069373	total: 3m 39s	remaining: 13m 44s
2132:	learn: 0.0063894	total: 3m 40s	remaining: 13m 31s
1957:	learn: 0.0074871	total: 3m 40s	remaining: 15m 3s
2050:	learn: 0.0068664	total: 3m 40s	remaining: 14m 12s
2107:	learn: 0.0058440	total: 3m 40s	remaining: 13m 43s
2105:	learn: 0.0069326	total: 3m 39s	remaining: 13m 44s
1958:	learn: 0.0074830	total: 3m 40s	remaining: 15m 3s
2133:	learn: 0.0063839	total: 3m 40s	remaining: 13m 31s
2051:	learn: 0.0068629	total: 3m 40s	remaining: 14m 12s
2108:	learn: 0.0058398	total: 3m 40s	remaining: 13m 43s
2106:	learn: 0.0069279	total: 3m 40s	remaining: 13m 44s
1959:	learn: 0.0074747	total: 3m 40s	remaining: 15m 3s
2134:	learn: 0.0063806	total: 3m 40s	remaining: 13m 31s
2052:	learn: 0.0068585	total: 3m 40s	remaining: 14m 12s
2107:	learn: 0.0069223	total: 3m 40s	remaining: 13m 44s
2109:	learn: 0.0058355	total: 3m 40s	remaining: 13m 43s
1960:	learn: 0.0074678	total: 3m 40s	remaining: 15m 3s
2135:	learn: 0.0063744	total: 3m 40s	remaining: 13m 31s
2053:	learn: 0.0068520	total: 3m 40s	remaining: 14m 12s
2108:	learn: 0.0069168	total: 3m 40s	remaining: 13m 44s
1961:	learn: 0.0074653	total: 3m 40s	remaining: 15m 3s
2110:	learn: 0.0058302	total: 3m 40s	remaining: 13m 43s
2054:	learn: 0.0068474	total: 3m 40s	remaining: 14m 12s
2136:	learn: 0.0063692	total: 3m 40s	remaining: 13m 31s
2109:	learn: 0.0069133	total: 3m 40s	remaining: 13m 44s
1962:	learn: 0.0074613	total: 3m 40s	remaining: 15m 2s
2137:	learn: 0.0063641	total: 3m 40s	remaining: 13m 31s
2111:	learn: 0.0058259	total: 3m 40s	remaining: 13m 43s
2055:	learn: 0.0068420	total: 3m 40s	remaining: 14m 12s
1963:	learn: 0.0074545	total: 3m 40s	remaining: 15m 2s
2110:	learn: 0.0069084	total: 3m 40s	remaining: 13m 43s
2138:	learn: 0.0063580	total: 3m 40s	remaining: 13m 30s
1964:	learn: 0.0074499	total: 3m 40s	remaining: 15m 2s
2112:	learn: 0.0058219	total: 3m 40s	remaining: 13m 43s
2056:	learn: 0.0068382	total: 3m 40s	remaining: 14m 12s
2111:	learn: 0.0069027	total: 3m 40s	remaining: 13m 43s
2139:	learn: 0.0063543	total: 3m 40s	remaining: 13m 30s
2112:	learn: 0.0068976	total: 3m 40s	remaining: 13m 43s
2113:	learn: 0.0058182	total: 3m 40s	remaining: 13m 43s
1965:	learn: 0.0074413	total: 3m 40s	remaining: 15m 2s
2057:	learn: 0.0068342	total: 3m 40s	remaining: 14m 12s
2113:	learn: 0.0068926	total: 3m 40s	remaining: 13m 43s
2114:	learn: 0.0058127	total: 3m 40s	remaining: 13m 43s
2140:	learn: 0.0063484	total: 3m 40s	remaining: 13m 30s
1966:	learn: 0.0074331	total: 3m 40s	remaining: 15m 2s
2114:	learn: 0.0068860	total: 3m 40s	remaining: 13m 43s
2058:	learn: 0.0068300	total: 3m 40s	remaining: 14m 11s
2115:	learn: 0.0058070	total: 3m 40s	remaining: 13m 42s
2141:	learn: 0.0063418	total: 3m 40s	remaining: 13m 30s
2115:	learn: 0.0068828	total: 3m 40s	remaining: 13m 42s
2116:	learn: 0.0058024	total: 3m 40s	remaining: 13m 42s
2059:	learn: 0.0068255	total: 3m 41s	remaining: 14m 11s
1967:	learn: 0.0074291	total: 3m 41s	remaining: 15m 2s
2142:	learn: 0.0063352	total: 3m 41s	remaining: 13m 30s
2116:	learn: 0.0068778	total: 3m 40s	remaining: 13m 42s
2060:	learn: 0.0068201	total: 3m 41s	remaining: 14m 11s
2117:	learn: 0.0057994	total: 3m 41s	remaining: 13m 42s
1968:	learn: 0.0074202	total: 3m 41s	remaining: 15m 2s
2117:	learn: 0.0068743	total: 3m 41s	remaining: 13m 42s
2143:	learn: 0.0063322	total: 3m 41s	remaining: 13m 30s
2061:	learn: 0.0068159	total: 3m 41s	remaining: 14m 11s
2118:	learn: 0.0057967	total: 3m 41s	remaining: 13m 42s
2144:	learn: 0.0063277	total: 3m 41s	remaining: 13m 30s
2118:	learn: 0.0068701	total: 3m 41s	remaining: 13m 42s
1969:	learn: 0.0074147	total: 3m 41s	remaining: 15m 2s
2062:	learn: 0.0068116	total: 3m 41s	remaining: 14m 11s
2145:	learn: 0.0063232	total: 3m 41s	remaining: 13m 30s
2119:	learn: 0.0057926	total: 3m 41s	remaining: 13m 42s
1970:	learn: 0.0074098	total: 3m 41s	remaining: 15m 1s
2119:	learn: 0.0068647	total: 3m 41s	remaining: 13m 42s
2063:	learn: 0.0068067	total: 3m 41s	remaining: 14m 11s
2146:	learn: 0.0063196	total: 3m 41s	remaining: 13m 29s
2120:	learn: 0.0057872	total: 3m 41s	remaining: 13m 42s
2120:	learn: 0.0068582	total: 3m 41s	remaining: 13m 42s
1971:	learn: 0.0074060	total: 3m 41s	remaining: 15m 1s
2064:	learn: 0.0068030	total: 3m 41s	remaining: 14m 11s
2147:	learn: 0.0063131	total: 3m 41s	remaining: 13m 29s
2121:	learn: 0.0068551	total: 3m 41s	remaining: 13m 42s
2121:	learn: 0.0057820	total: 3m 41s	remaining: 13m 42s
2148:	learn: 0.0063085	total: 3m 41s	remaining: 13m 29s
1972:	learn: 0.0073999	total: 3m 41s	remaining: 15m 1s
2065:	learn: 0.0067987	total: 3m 41s	remaining: 14m 11s
2122:	learn: 0.0068496	total: 3m 41s	remaining: 13m 41s

2149:	learn: 0.0063026	total: 3m 41s	remaining: 13m 29s
1973:	learn: 0.0073926	total: 3m 41s	remaining: 15m 1s
2122:	learn: 0.0057768	total: 3m 41s	remaining: 13m 42s
2066:	learn: 0.0067957	total: 3m 41s	remaining: 14m 10s
2123:	learn: 0.0068423	total: 3m 41s	remaining: 13m 41s
2150:	learn: 0.0062983	total: 3m 41s	remaining: 13m 29s
1974:	learn: 0.0073861	total: 3m 41s	remaining: 15m 1s
2067:	learn: 0.0067908	total: 3m 41s	remaining: 14m 10s
2123:	learn: 0.0057709	total: 3m 41s	remaining: 13m 42s
2151:	learn: 0.0062925	total: 3m 41s	remaining: 13m 29s
2124:	learn: 0.0068391	total: 3m 41s	remaining: 13m 41s
2068:	learn: 0.0067858	total: 3m 41s	remaining: 14m 10s
1975:	learn: 0.0073794	total: 3m 41s	remaining: 15m 1s
2125:	learn: 0.0068342	total: 3m 41s	remaining: 13m 41s
2124:	learn: 0.0057666	total: 3m 41s	remaining: 13m 42s
2152:	learn: 0.0062895	total: 3m 41s	remaining: 13m 29s
2069:	learn: 0.0067813	total: 3m 41s	remaining: 14m 10s
2125:	learn: 0.0057630	total: 3m 41s	remaining: 13m 41s
1976:	learn: 0.0073695	total: 3m 42s	remaining: 15m 1s
2126:	learn: 0.0068304	total: 3m 41s	remaining: 13m 41s
2070:	learn: 0.0067748	total: 3m 42s	remaining: 14m 10s
2153:	learn: 0.0062866	total: 3m 42s	remaining: 13m 28s
2126:	learn: 0.0057588	total: 3m 42s	remaining: 13m 41s
2127:	learn: 0.0068247	total: 3m 41s	remaining: 13m 41s
1977:	learn: 0.0073620	total: 3m 42s	remaining: 15m
2071:	learn: 0.0067695	total: 3m 42s	remaining: 14m 10s
2127:	learn: 0.0057535	total: 3m 42s	remaining: 13m 41s
2128:	learn: 0.0068204	total: 3m 42s	remaining: 13m 41s
2154:	learn: 0.0062811	total: 3m 42s	remaining: 13m 28s
1978:	learn: 0.0073544	total: 3m 42s	remaining: 15m
2128:	learn: 0.0057503	total: 3m 42s	remaining: 13m 41s
2072:	learn: 0.0067635	total: 3m 42s	remaining: 14m 9s
2129:	learn: 0.0068157	total: 3m 42s	remaining: 13m 40s
2155:	learn: 0.0062762	total: 3m 42s	remaining: 13m 28s
1979:	learn: 0.0073500	total: 3m 42s	remaining: 15m
2073:	learn: 0.0067596	total: 3m 42s	remaining: 14m 9s
2129:	learn: 0.0057460	total: 3m 42s	remaining: 13m 41s
2130:	learn: 0.0068121	total: 3m 42s	remaining: 13m 40s
1980:	learn: 0.0073413	total: 3m 42s	remaining: 15m
2074:	learn: 0.0067532	total: 3m 42s	remaining: 14m 9s
2156:	learn: 0.0062725	total: 3m 42s	remaining: 13m 28s
2130:	learn: 0.0057407	total: 3m 42s	remaining: 13m 41s
2131:	learn: 0.0068065	total: 3m 42s	remaining: 13m 40s
2075:	learn: 0.0067452	total: 3m 42s	remaining: 14m 9s
1981:	learn: 0.0073360	total: 3m 42s	remaining: 15m
2157:	learn: 0.0062662	total: 3m 42s	remaining: 13m 28s
2131:	learn: 0.0057360	total: 3m 42s	remaining: 13m 41s
2132:	learn: 0.0068019	total: 3m 42s	remaining: 13m 40s
1982:	learn: 0.0073285	total: 3m 42s	remaining: 15m
2158:	learn: 0.0062607	total: 3m 42s	remaining: 13m 28s
2076:	learn: 0.0067413	total: 3m 42s	remaining: 14m 9s
2132:	learn: 0.0057327	total: 3m 42s	remaining: 13m 40s
2133:	learn: 0.0067981	total: 3m 42s	remaining: 13m 40s
2159:	learn: 0.0062578	total: 3m 42s	remaining: 13m 28s
1983:	learn: 0.0073243	total: 3m 42s	remaining: 15m
2077:	learn: 0.0067377	total: 3m 42s	remaining: 14m 9s
2133:	learn: 0.0057282	total: 3m 42s	remaining: 13m 40s
2134:	learn: 0.0067931	total: 3m 42s	remaining: 13m 40s
2160:	learn: 0.0062528	total: 3m 42s	remaining: 13m 28s
1984:	learn: 0.0073199	total: 3m 42s	remaining: 15m
2134:	learn: 0.0057241	total: 3m 42s	remaining: 13m 40s
2135:	learn: 0.0067879	total: 3m 42s	remaining: 13m 40s
2078:	learn: 0.0067341	total: 3m 42s	remaining: 14m 9s
2161:	learn: 0.0062501	total: 3m 42s	remaining: 13m 28s
2135:	learn: 0.0057202	total: 3m 42s	remaining: 13m 40s
1985:	learn: 0.0073156	total: 3m 43s	remaining: 14m 59s
2136:	learn: 0.0067841	total: 3m 42s	remaining: 13m 40s
2079:	learn: 0.0067289	total: 3m 42s	remaining: 14m 9s
2162:	learn: 0.0062430	total: 3m 43s	remaining: 13m 28s
1986:	learn: 0.0073087	total: 3m 43s	remaining: 14m 59s
2136:	learn: 0.0057170	total: 3m 43s	remaining: 13m 40s
2137:	learn: 0.0067796	total: 3m 42s	remaining: 13m 39s
2080:	learn: 0.0067256	total: 3m 43s	remaining: 14m 9s
2163:	learn: 0.0062375	total: 3m 43s	remaining: 13m 27s
1987:	learn: 0.0073031	total: 3m 43s	remaining: 14m 59s
2137:	learn: 0.0057132	total: 3m 43s	remaining: 13m 40s
2081:	learn: 0.0067191	total: 3m 43s	remaining: 14m 8s
2138:	learn: 0.0067739	total: 3m 43s	remaining: 13m 39s
1988:	learn: 0.0072977	total: 3m 43s	remaining: 14m 59s
2164:	learn: 0.0062323	total: 3m 43s	remaining: 13m 27s
2082:	learn: 0.0067132	total: 3m 43s	remaining: 14m 8s
2138:	learn: 0.0057082	total: 3m 43s	remaining: 13m 40s
2139:	learn: 0.0067680	total: 3m 43s	remaining: 13m 39s
2083:	learn: 0.0067081	total: 3m 43s	remaining: 14m 8s
2165:	learn: 0.0062280	total: 3m 43s	remaining: 13m 27s
1989:	learn: 0.0072936	total: 3m 43s	remaining: 14m 59s
2139:	learn: 0.0057045	total: 3m 43s	remaining: 13m 40s
2140:	learn: 0.0067619	total: 3m 43s	remaining: 13m 39s
2166:	learn: 0.0062236	total: 3m 43s	remaining: 13m 27s
2084:	learn: 0.0067031	total: 3m 43s	remaining: 14m 8s
1990:	learn: 0.0072865	total: 3m 43s	remaining: 14m 59s
2140:	learn: 0.0057002	total: 3m 43s	remaining: 13m 40s
2141:	learn: 0.0067562	total: 3m 43s	remaining: 13m 39s
2167:	learn: 0.0062218	total: 3m 43s	remaining: 13m 27s
1991:	learn: 0.0072822	total: 3m 43s	remaining: 14m 58s
2141:	learn: 0.0056947	total: 3m 43s	remaining: 13m 39s
2085:	learn: 0.0066971	total: 3m 43s	remaining: 14m 8s
2168:	learn: 0.0062151	total: 3m 43s	remaining: 13m 27s
2142:	learn: 0.0067490	total: 3m 43s	remaining: 13m 39s
2142:	learn: 0.0056912	total: 3m 43s	remaining: 13m 39s
2086:	learn: 0.0066921	total: 3m 43s	remaining: 14m 8s
1992:	learn: 0.0072754	total: 3m 43s	remaining: 14m 58s
2143:	learn: 0.0067443	total: 3m 43s	remaining: 13m 39s
2169:	learn: 0.0062103	total: 3m 43s	remaining: 13m 27s
2087:	learn: 0.0066885	total: 3m 43s	remaining: 14m 7s
2143:	learn: 0.0056872	total: 3m 43s	remaining: 13m 39s
1993:	learn: 0.0072713	total: 3m 43s	remaining: 14m 58s
2144:	learn: 0.0067395	total: 3m 43s	remaining: 13m 39s
2088:	learn: 0.0066830	total: 3m 43s	remaining: 14m 7s
2170:	learn: 0.0062067	total: 3m 43s	remaining: 13m 27s
2144:	learn: 0.0056820	total: 3m 43s	remaining: 13m 39s
2145:	learn: 0.0067356	total: 3m 43s	remaining: 13m 39s
2171:	learn: 0.0062037	total: 3m 43s	remaining: 13m 27s
1994:	learn: 0.0072690	total: 3m 43s	remaining: 14m 58s
2089:	learn: 0.0066766	total: 3m 43s	remaining: 14m 7s
2145:	learn: 0.0056766	total: 3m 43s	remaining: 13m 39s
2172:	learn: 0.0061989	total: 3m 43s	remaining: 13m 26s
2090:	learn: 0.0066730	total: 3m 44s	remaining: 14m 7s
2146:	learn: 0.0067292	total: 3m 43s	remaining: 13m 39s
1995:	learn: 0.0072612	total: 3m 44s	remaining: 14m 58s
2173:	learn: 0.0061950	total: 3m 44s	remaining: 13m 26s
2146:	learn: 0.0056721	total: 3m 44s	remaining: 13m 39s
2147:	learn: 0.0067248	total: 3m 44s	remaining: 13m 38s
2091:	learn: 0.0066668	total: 3m 44s	remaining: 14m 7s
1996:	learn: 0.0072548	total: 3m 44s	remaining: 14m 58s
2174:	learn: 0.0061916	total: 3m 44s	remaining: 13m 26s
2147:	learn: 0.0056695	total: 3m 44s	remaining: 13m 39s
2148:	learn: 0.0067214	total: 3m 44s	remaining: 13m 38s
2092:	learn: 0.0066597	total: 3m 44s	remaining: 14m 7s
2175:	learn: 0.0061881	total: 3m 44s	remaining: 13m 26s
2148:	learn: 0.0056645	total: 3m 44s	remaining: 13m 39s
1997:	learn: 0.0072478	total: 3m 44s	remaining: 14m 58s
2176:	learn: 0.0061839	total: 3m 44s	remaining: 13m 26s
2093:	learn: 0.0066564	total: 3m 44s	remaining: 14m 7s
2149:	learn: 0.0067171	total: 3m 44s	remaining: 13m 38s
2149:	learn: 0.0056601	total: 3m 44s	remaining: 13m 38s
2094:	learn: 0.0066536	total: 3m 44s	remaining: 14m 6s
2150:	learn: 0.0067127	total: 3m 44s	remaining: 13m 38s
1998:	learn: 0.0072423	total: 3m 44s	remaining: 14m 58s
2177:	learn: 0.0061776	total: 3m 44s	remaining: 13m 26s
2150:	learn: 0.0056568	total: 3m 44s	remaining: 13m 38s
2151:	learn: 0.0067079	total: 3m 44s	remaining: 13m 38s
2095:	learn: 0.0066493	total: 3m 44s	remaining: 14m 6s
2178:	learn: 0.0061734	total: 3m 44s	remaining: 13m 25s
1999:	learn: 0.0072355	total: 3m 44s	remaining: 14m 58s
2151:	learn: 0.0056540	total: 3m 44s	remaining: 13m 38s
2152:	learn: 0.0067012	total: 3m 44s	remaining: 13m 38s
2096:	learn: 0.0066438	total: 3m 44s	remaining: 14m 6s
2000:	learn: 0.0072288	total: 3m 44s	remaining: 14m 58s
2179:	learn: 0.0061683	total: 3m 44s	remaining: 13m 25s
2152:	learn: 0.0056492	total: 3m 44s	remaining: 13m 38s
2153:	learn: 0.0066939	total: 3m 44s	remaining: 13m 37s
2097:	learn: 0.0066402	total: 3m 44s	remaining: 14m 6s
2180:	learn: 0.0061647	total: 3m 44s	remaining: 13m 25s
2001:	learn: 0.0072240	total: 3m 44s	remaining: 14m 58s
2154:	learn: 0.0066894	total: 3m 44s	remaining: 13m 37s
2153:	learn: 0.0056466	total: 3m 44s	remaining: 13m 38s
2098:	learn: 0.0066352	total: 3m 44s	remaining: 14m 6s
2181:	learn: 0.0061616	total: 3m 44s	remaining: 13m 25s
2002:	learn: 0.0072191	total: 3m 44s	remaining: 14m 57s
2155:	learn: 0.0066870	total: 3m 44s	remaining: 13m 37s
2154:	learn: 0.0056424	total: 3m 44s	remaining: 13m 38s
2182:	learn: 0.0061573	total: 3m 44s	remaining: 13m 25s
2099:	learn: 0.0066305	total: 3m 44s	remaining: 14m 6s
2156:	learn: 0.0066844	total: 3m 44s	remaining: 13m 37s
2003:	learn: 0.0072146	total: 3m 45s	remaining: 14m 57s
2183:	learn: 0.0061530	total: 3m 45s	remaining: 13m 25s
2155:	learn: 0.0056392	total: 3m 44s	remaining: 13m 38s
2100:	learn: 0.0066264	total: 3m 45s	remaining: 14m 5s
2157:	learn: 0.0066788	total: 3m 44s	remaining: 13m 37s
2184:	learn: 0.0061481	total: 3m 45s	remaining: 13m 25s
2004:	learn: 0.0072073	total: 3m 45s	remaining: 14m 57s
2101:	learn: 0.0066187	total: 3m 45s	remaining: 14m 5s
2156:	learn: 0.0056350	total: 3m 45s	remaining: 13m 38s
2158:	learn: 0.0066730	total: 3m 45s	remaining: 13m 37s
2185:	learn: 0.0061445	total: 3m 45s	remaining: 13m 24s
2005:	learn: 0.0072017	total: 3m 45s	remaining: 14m 57s
2159:	learn: 0.0066683	total: 3m 45s	remaining: 13m 37s
2157:	learn: 0.0056300	total: 3m 45s	remaining: 13m 38s
2186:	learn: 0.0061402	total: 3m 45s	remaining: 13m 24s
2102:	learn: 0.0066137	total: 3m 45s	remaining: 14m 5s
2006:	learn: 0.0071966	total: 3m 45s	remaining: 14m 57s
2187:	learn: 0.0061372	total: 3m 45s	remaining: 13m 24s
2158:	learn: 0.0056259	total: 3m 45s	remaining: 13m 38s
2160:	learn: 0.0066646	total: 3m 45s	remaining: 13m 36s
2103:	learn: 0.0066070	total: 3m 45s	remaining: 14m 5s
2007:	learn: 0.0071899	total: 3m 45s	remaining: 14m 57s
2159:	learn: 0.0056208	total: 3m 45s	remaining: 13m 37s
2188:	learn: 0.0061321	total: 3m 45s	remaining: 13m 24s
2161:	learn: 0.0066594	total: 3m 45s	remaining: 13m 36s
2104:	learn: 0.0066029	total: 3m 45s	remaining: 14m 5s
2160:	learn: 0.0056172	total: 3m 45s	remaining: 13m 37s
2008:	learn: 0.0071850	total: 3m 45s	remaining: 14m 57s
2162:	learn: 0.0066532	total: 3m 45s	remaining: 13m 36s
2189:	learn: 0.0061289	total: 3m 45s	remaining: 13m 24s
2105:	learn: 0.0065955	total: 3m 45s	remaining: 14m 5s
2161:	learn: 0.0056135	total: 3m 45s	remaining: 13m 37s
2009:	learn: 0.0071763	total: 3m 45s	remaining: 14m 56s
2163:	learn: 0.0066468	total: 3m 45s	remaining: 13m 36s
2190:	learn: 0.0061241	total: 3m 45s	remaining: 13m 24s
2106:	learn: 0.0065906	total: 3m 45s	remaining: 14m 5s
2010:	learn: 0.0071739	total: 3m 45s	remaining: 14m 56s
2162:	learn: 0.0056100	total: 3m 45s	remaining: 13m 37s
2191:	learn: 0.0061198	total: 3m 45s	remaining: 13m 24s
2164:	learn: 0.0066426	total: 3m 45s	remaining: 13m 36s
2107:	learn: 0.0065877	total: 3m 45s	remaining: 14m 5s
2011:	learn: 0.0071659	total: 3m 45s	remaining: 14m 56s
2192:	learn: 0.0061163	total: 3m 45s	remaining: 13m 23s
2163:	learn: 0.0056064	total: 3m 45s	remaining: 13m 37s
2165:	learn: 0.0066381	total: 3m 45s	remaining: 13m 36s
2108:	learn: 0.0065839	total: 3m 45s	remaining: 14m 5s
2012:	learn: 0.0071584	total: 3m 45s	remaining: 14m 56s
2164:	learn: 0.0056036	total: 3m 45s	remaining: 13m 37s
2193:	learn: 0.0061120	total: 3m 45s	remaining: 13m 23s
2166:	learn: 0.0066345	total: 3m 45s	remaining: 13m 36s
2109:	learn: 0.0065780	total: 3m 46s	remaining: 14m 5s
2165:	learn: 0.0055992	total: 3m 45s	remaining: 13m 37s
2194:	learn: 0.0061095	total: 3m 46s	remaining: 13m 23s
2013:	learn: 0.0071544	total: 3m 46s	remaining: 14m 56s
2167:	learn: 0.0066301	total: 3m 45s	remaining: 13m 36s
2195:	learn: 0.0061057	total: 3m 46s	remaining: 13m 23s
2166:	learn: 0.0055951	total: 3m 46s	remaining: 13m 37s
2168:	learn: 0.0066236	total: 3m 46s	remaining: 13m 36s
2110:	learn: 0.0065728	total: 3m 46s	remaining: 14m 5s
2014:	learn: 0.0071479	total: 3m 46s	remaining: 14m 56s
2167:	learn: 0.0055911	total: 3m 46s	remaining: 13m 37s
2196:	learn: 0.0061011	total: 3m 46s	remaining: 13m 23s
2111:	learn: 0.0065665	total: 3m 46s	remaining: 14m 5s
2169:	learn: 0.0066193	total: 3m 46s	remaining: 13m 35s
2015:	learn: 0.0071416	total: 3m 46s	remaining: 14m 56s
2168:	learn: 0.0055863	total: 3m 46s	remaining: 13m 36s
2197:	learn: 0.0060981	total: 3m 46s	remaining: 13m 23s
2112:	learn: 0.0065618	total: 3m 46s	remaining: 14m 4s
2016:	learn: 0.0071350	total: 3m 46s	remaining: 14m 56s
2170:	learn: 0.0066151	total: 3m 46s	remaining: 13m 35s
2169:	learn: 0.0055818	total: 3m 46s	remaining: 13m 36s
2113:	learn: 0.0065583	total: 3m 46s	remaining: 14m 4s
2198:	learn: 0.0060923	total: 3m 46s	remaining: 13m 23s
2017:	learn: 0.0071306	total: 3m 46s	remaining: 14m 55s
2171:	learn: 0.0066121	total: 3m 46s	remaining: 13m 35s
2170:	learn: 0.0055770	total: 3m 46s	remaining: 13m 36s
2199:	learn: 0.0060893	total: 3m 46s	remaining: 13m 23s
2114:	learn: 0.0065524	total: 3m 46s	remaining: 14m 4s
2172:	learn: 0.0066089	total: 3m 46s	remaining: 13m 35s
2018:	learn: 0.0071240	total: 3m 46s	remaining: 14m 55s
2200:	learn: 0.0060841	total: 3m 46s	remaining: 13m 23s
2115:	learn: 0.0065478	total: 3m 46s	remaining: 14m 4s
2171:	learn: 0.0055712	total: 3m 46s	remaining: 13m 36s
2019:	learn: 0.0071204	total: 3m 46s	remaining: 14m 55s
2173:	learn: 0.0066052	total: 3m 46s	remaining: 13m 35s
2172:	learn: 0.0055664	total: 3m 46s	remaining: 13m 36s
2116:	learn: 0.0065423	total: 3m 46s	remaining: 14m 4s
2201:	learn: 0.0060812	total: 3m 46s	remaining: 13m 23s
2174:	learn: 0.0065980	total: 3m 46s	remaining: 13m 35s
2020:	learn: 0.0071139	total: 3m 46s	remaining: 14m 55s
2173:	learn: 0.0055634	total: 3m 46s	remaining: 13m 36s
2202:	learn: 0.0060781	total: 3m 46s	remaining: 13m 22s
2117:	learn: 0.0065385	total: 3m 46s	remaining: 14m 4s
2175:	learn: 0.0065923	total: 3m 46s	remaining: 13m 35s
2203:	learn: 0.0060729	total: 3m 46s	remaining: 13m 22s
2118:	learn: 0.0065348	total: 3m 46s	remaining: 14m 3s
2021:	learn: 0.0071104	total: 3m 46s	remaining: 14m 55s
2174:	learn: 0.0055591	total: 3m 46s	remaining: 13m 36s
2176:	learn: 0.0065883	total: 3m 46s	remaining: 13m 35s
2204:	learn: 0.0060684	total: 3m 47s	remaining: 13m 22s
2022:	learn: 0.0071036	total: 3m 47s	remaining: 14m 55s
2119:	learn: 0.0065280	total: 3m 47s	remaining: 14m 3s
2175:	learn: 0.0055566	total: 3m 46s	remaining: 13m 36s
2177:	learn: 0.0065825	total: 3m 46s	remaining: 13m 34s
2205:	learn: 0.0060645	total: 3m 47s	remaining: 13m 22s
2120:	learn: 0.0065217	total: 3m 47s	remaining: 14m 3s
2023:	learn: 0.0070968	total: 3m 47s	remaining: 14m 55s
2176:	learn: 0.0055525	total: 3m 47s	remaining: 13m 36s
2178:	learn: 0.0065762	total: 3m 47s	remaining: 13m 34s
2206:	learn: 0.0060607	total: 3m 47s	remaining: 13m 22s
2024:	learn: 0.0070937	total: 3m 47s	remaining: 14m 55s
2121:	learn: 0.0065180	total: 3m 47s	remaining: 14m 3s
2177:	learn: 0.0055483	total: 3m 47s	remaining: 13m 35s
2179:	learn: 0.0065709	total: 3m 47s	remaining: 13m 34s
2207:	learn: 0.0060559	total: 3m 47s	remaining: 13m 22s
2122:	learn: 0.0065125	total: 3m 47s	remaining: 14m 3s
2025:	learn: 0.0070867	total: 3m 47s	remaining: 14m 54s
2178:	learn: 0.0055433	total: 3m 47s	remaining: 13m 35s
2180:	learn: 0.0065656	total: 3m 47s	remaining: 13m 34s
2208:	learn: 0.0060526	total: 3m 47s	remaining: 13m 22s
2123:	learn: 0.0065089	total: 3m 47s	remaining: 14m 3s
2026:	learn: 0.0070832	total: 3m 47s	remaining: 14m 54s
2179:	learn: 0.0055398	total: 3m 47s	remaining: 13m 35s
2209:	learn: 0.0060506	total: 3m 47s	remaining: 13m 21s
2181:	learn: 0.0065608	total: 3m 47s	remaining: 13m 34s
2027:	learn: 0.0070769	total: 3m 47s	remaining: 14m 54s
2124:	learn: 0.0065052	total: 3m 47s	remaining: 14m 3s
2180:	learn: 0.0055370	total: 3m 47s	remaining: 13m 35s

2028:	learn: 0.0070733	total: 3m 47s	remaining: 14m 54s
2182:	learn: 0.0065576	total: 3m 47s	remaining: 13m 34s
2210:	learn: 0.0060480	total: 3m 47s	remaining: 13m 21s
2125:	learn: 0.0065010	total: 3m 47s	remaining: 14m 3s
2181:	learn: 0.0055314	total: 3m 47s	remaining: 13m 35s
2183:	learn: 0.0065523	total: 3m 47s	remaining: 13m 34s
2211:	learn: 0.0060448	total: 3m 47s	remaining: 13m 21s
2029:	learn: 0.0070692	total: 3m 47s	remaining: 14m 54s
2126:	learn: 0.0064972	total: 3m 47s	remaining: 14m 2s
2184:	learn: 0.0065475	total: 3m 47s	remaining: 13m 34s
2182:	learn: 0.0055285	total: 3m 47s	remaining: 13m 35s
2212:	learn: 0.0060401	total: 3m 47s	remaining: 13m 21s
2030:	learn: 0.0070627	total: 3m 47s	remaining: 14m 54s
2127:	learn: 0.0064938	total: 3m 47s	remaining: 14m 2s
2213:	learn: 0.0060350	total: 3m 47s	remaining: 13m 21s
2183:	learn: 0.0055241	total: 3m 47s	remaining: 13m 35s
2185:	learn: 0.0065429	total: 3m 47s	remaining: 13m 34s
2128:	learn: 0.0064892	total: 3m 47s	remaining: 14m 2s
2214:	learn: 0.0060320	total: 3m 47s	remaining: 13m 21s
2031:	learn: 0.0070577	total: 3m 47s	remaining: 14m 54s
2184:	learn: 0.0055193	total: 3m 47s	remaining: 13m 35s
2186:	learn: 0.0065385	total: 3m 47s	remaining: 13m 33s
2215:	learn: 0.0060290	total: 3m 48s	remaining: 13m 20s
2129:	learn: 0.0064862	total: 3m 48s	remaining: 14m 2s
2032:	learn: 0.0070543	total: 3m 48s	remaining: 14m 53s
2187:	learn: 0.0065337	total: 3m 47s	remaining: 13m 33s
2185:	learn: 0.0055151	total: 3m 48s	remaining: 13m 35s
2130:	learn: 0.0064830	total: 3m 48s	remaining: 14m 2s
2216:	learn: 0.0060249	total: 3m 48s	remaining: 13m 20s
2033:	learn: 0.0070492	total: 3m 48s	remaining: 14m 53s
2188:	learn: 0.0065299	total: 3m 48s	remaining: 13m 33s
2186:	learn: 0.0055103	total: 3m 48s	remaining: 13m 34s
2034:	learn: 0.0070433	total: 3m 48s	remaining: 14m 53s
2131:	learn: 0.0064773	total: 3m 48s	remaining: 14m 2s
2217:	learn: 0.0060211	total: 3m 48s	remaining: 13m 20s
2189:	learn: 0.0065255	total: 3m 48s	remaining: 13m 33s
2187:	learn: 0.0055064	total: 3m 48s	remaining: 13m 34s
2132:	learn: 0.0064713	total: 3m 48s	remaining: 14m 2s
2218:	learn: 0.0060147	total: 3m 48s	remaining: 13m 20s
2035:	learn: 0.0070393	total: 3m 48s	remaining: 14m 53s
2188:	learn: 0.0055015	total: 3m 48s	remaining: 13m 34s
2190:	learn: 0.0065222	total: 3m 48s	remaining: 13m 33s
2219:	learn: 0.0060099	total: 3m 48s	remaining: 13m 20s
2133:	learn: 0.0064648	total: 3m 48s	remaining: 14m 2s
2036:	learn: 0.0070332	total: 3m 48s	remaining: 14m 53s
2189:	learn: 0.0054989	total: 3m 48s	remaining: 13m 34s
2191:	learn: 0.0065167	total: 3m 48s	remaining: 13m 33s
2134:	learn: 0.0064621	total: 3m 48s	remaining: 14m 1s
2220:	learn: 0.0060054	total: 3m 48s	remaining: 13m 20s
2190:	learn: 0.0054954	total: 3m 48s	remaining: 13m 34s
2037:	learn: 0.0070270	total: 3m 48s	remaining: 14m 53s
2192:	learn: 0.0065126	total: 3m 48s	remaining: 13m 33s
2135:	learn: 0.0064571	total: 3m 48s	remaining: 14m 1s
2221:	learn: 0.0060017	total: 3m 48s	remaining: 13m 20s
2191:	learn: 0.0054926	total: 3m 48s	remaining: 13m 34s
2193:	learn: 0.0065097	total: 3m 48s	remaining: 13m 33s
2038:	learn: 0.0070218	total: 3m 48s	remaining: 14m 53s
2136:	learn: 0.0064533	total: 3m 48s	remaining: 14m 1s
2222:	learn: 0.0059986	total: 3m 48s	remaining: 13m 20s
2192:	learn: 0.0054891	total: 3m 48s	remaining: 13m 34s
2194:	learn: 0.0065032	total: 3m 48s	remaining: 13m 33s
2039:	learn: 0.0070179	total: 3m 48s	remaining: 14m 52s
2137:	learn: 0.0064495	total: 3m 48s	remaining: 14m 1s
2223:	learn: 0.0059957	total: 3m 48s	remaining: 13m 20s
2193:	learn: 0.0054857	total: 3m 48s	remaining: 13m 33s
2040:	learn: 0.0070129	total: 3m 48s	remaining: 14m 52s
2195:	learn: 0.0064988	total: 3m 48s	remaining: 13m 33s
2138:	learn: 0.0064441	total: 3m 48s	remaining: 14m 1s
2194:	learn: 0.0054814	total: 3m 48s	remaining: 13m 33s
2224:	learn: 0.0059930	total: 3m 48s	remaining: 13m 20s
2041:	learn: 0.0070066	total: 3m 49s	remaining: 14m 52s
2196:	learn: 0.0064928	total: 3m 48s	remaining: 13m 32s
2195:	learn: 0.0054788	total: 3m 48s	remaining: 13m 33s
2225:	learn: 0.0059869	total: 3m 49s	remaining: 13m 19s
2139:	learn: 0.0064394	total: 3m 49s	remaining: 14m 1s
2226:	learn: 0.0059845	total: 3m 49s	remaining: 13m 19s
2042:	learn: 0.0069990	total: 3m 49s	remaining: 14m 52s
2196:	learn: 0.0054759	total: 3m 49s	remaining: 13m 33s
2197:	learn: 0.0064898	total: 3m 48s	remaining: 13m 32s
2227:	learn: 0.0059813	total: 3m 49s	remaining: 13m 19s
2140:	learn: 0.0064344	total: 3m 49s	remaining: 14m 1s
2043:	learn: 0.0069945	total: 3m 49s	remaining: 14m 52s
2198:	learn: 0.0064851	total: 3m 49s	remaining: 13m 32s
2197:	learn: 0.0054702	total: 3m 49s	remaining: 13m 33s
2228:	learn: 0.0059750	total: 3m 49s	remaining: 13m 19s
2141:	learn: 0.0064299	total: 3m 49s	remaining: 14m 1s
2199:	learn: 0.0064794	total: 3m 49s	remaining: 13m 32s
2044:	learn: 0.0069873	total: 3m 49s	remaining: 14m 52s
2198:	learn: 0.0054674	total: 3m 49s	remaining: 13m 33s
2142:	learn: 0.0064262	total: 3m 49s	remaining: 14m 1s
2200:	learn: 0.0064754	total: 3m 49s	remaining: 13m 32s
2229:	learn: 0.0059709	total: 3m 49s	remaining: 13m 19s
2045:	learn: 0.0069797	total: 3m 49s	remaining: 14m 52s
2199:	learn: 0.0054631	total: 3m 49s	remaining: 13m 33s
2230:	learn: 0.0059683	total: 3m 49s	remaining: 13m 19s
2046:	learn: 0.0069737	total: 3m 49s	remaining: 14m 51s
2143:	learn: 0.0064223	total: 3m 49s	remaining: 14m
2201:	learn: 0.0064698	total: 3m 49s	remaining: 13m 32s
2200:	learn: 0.0054594	total: 3m 49s	remaining: 13m 33s
2231:	learn: 0.0059633	total: 3m 49s	remaining: 13m 19s
2047:	learn: 0.0069710	total: 3m 49s	remaining: 14m 51s
2201:	learn: 0.0054547	total: 3m 49s	remaining: 13m 32s
2202:	learn: 0.0064653	total: 3m 49s	remaining: 13m 32s
2144:	learn: 0.0064186	total: 3m 49s	remaining: 14m
2232:	learn: 0.0059601	total: 3m 49s	remaining: 13m 18s
2048:	learn: 0.0069668	total: 3m 49s	remaining: 14m 51s
2202:	learn: 0.0054500	total: 3m 49s	remaining: 13m 32s
2233:	learn: 0.0059565	total: 3m 49s	remaining: 13m 18s
2145:	learn: 0.0064135	total: 3m 49s	remaining: 14m
2203:	learn: 0.0064616	total: 3m 49s	remaining: 13m 32s
2049:	learn: 0.0069604	total: 3m 49s	remaining: 14m 51s
2234:	learn: 0.0059514	total: 3m 49s	remaining: 13m 18s
2203:	learn: 0.0054463	total: 3m 49s	remaining: 13m 32s
2146:	learn: 0.0064075	total: 3m 49s	remaining: 14m
2204:	learn: 0.0064569	total: 3m 49s	remaining: 13m 32s
2050:	learn: 0.0069553	total: 3m 49s	remaining: 14m 51s
2235:	learn: 0.0059465	total: 3m 49s	remaining: 13m 18s
2204:	learn: 0.0054414	total: 3m 49s	remaining: 13m 32s
2205:	learn: 0.0064512	total: 3m 49s	remaining: 13m 31s
2147:	learn: 0.0064008	total: 3m 49s	remaining: 14m
2051:	learn: 0.0069492	total: 3m 50s	remaining: 14m 50s
2236:	learn: 0.0059420	total: 3m 50s	remaining: 13m 18s
2206:	learn: 0.0064456	total: 3m 49s	remaining: 13m 31s
2205:	learn: 0.0054377	total: 3m 49s	remaining: 13m 32s
2148:	learn: 0.0063963	total: 3m 50s	remaining: 14m
2207:	learn: 0.0064381	total: 3m 49s	remaining: 13m 31s
2237:	learn: 0.0059370	total: 3m 50s	remaining: 13m 18s
2052:	learn: 0.0069421	total: 3m 50s	remaining: 14m 50s
2206:	learn: 0.0054343	total: 3m 50s	remaining: 13m 32s
2238:	learn: 0.0059315	total: 3m 50s	remaining: 13m 17s
2208:	learn: 0.0064333	total: 3m 50s	remaining: 13m 31s
2149:	learn: 0.0063915	total: 3m 50s	remaining: 14m
2053:	learn: 0.0069357	total: 3m 50s	remaining: 14m 50s
2207:	learn: 0.0054307	total: 3m 50s	remaining: 13m 32s
2209:	learn: 0.0064277	total: 3m 50s	remaining: 13m 31s
2239:	learn: 0.0059286	total: 3m 50s	remaining: 13m 17s
2150:	learn: 0.0063889	total: 3m 50s	remaining: 14m
2208:	learn: 0.0054268	total: 3m 50s	remaining: 13m 32s
2054:	learn: 0.0069308	total: 3m 50s	remaining: 14m 50s
2210:	learn: 0.0064230	total: 3m 50s	remaining: 13m 31s
2209:	learn: 0.0054234	total: 3m 50s	remaining: 13m 31s
2240:	learn: 0.0059257	total: 3m 50s	remaining: 13m 17s
2151:	learn: 0.0063838	total: 3m 50s	remaining: 14m
2211:	learn: 0.0064165	total: 3m 50s	remaining: 13m 30s
2055:	learn: 0.0069230	total: 3m 50s	remaining: 14m 50s
2152:	learn: 0.0063794	total: 3m 50s	remaining: 14m
2241:	learn: 0.0059217	total: 3m 50s	remaining: 13m 17s
2210:	learn: 0.0054196	total: 3m 50s	remaining: 13m 31s
2212:	learn: 0.0064105	total: 3m 50s	remaining: 13m 30s
2056:	learn: 0.0069169	total: 3m 50s	remaining: 14m 50s
2242:	learn: 0.0059187	total: 3m 50s	remaining: 13m 17s
2153:	learn: 0.0063753	total: 3m 50s	remaining: 14m
2211:	learn: 0.0054151	total: 3m 50s	remaining: 13m 31s
2213:	learn: 0.0064050	total: 3m 50s	remaining: 13m 30s
2057:	learn: 0.0069110	total: 3m 50s	remaining: 14m 50s
2212:	learn: 0.0054110	total: 3m 50s	remaining: 13m 31s
2243:	learn: 0.0059156	total: 3m 50s	remaining: 13m 17s
2154:	learn: 0.0063694	total: 3m 50s	remaining: 13m 59s
2058:	learn: 0.0069048	total: 3m 50s	remaining: 14m 50s
2214:	learn: 0.0063991	total: 3m 50s	remaining: 13m 30s
2155:	learn: 0.0063638	total: 3m 50s	remaining: 13m 59s
2213:	learn: 0.0054070	total: 3m 50s	remaining: 13m 31s
2244:	learn: 0.0059130	total: 3m 50s	remaining: 13m 17s
2059:	learn: 0.0068983	total: 3m 50s	remaining: 14m 49s
2215:	learn: 0.0063947	total: 3m 50s	remaining: 13m 30s
2156:	learn: 0.0063598	total: 3m 50s	remaining: 13m 59s
2060:	learn: 0.0068921	total: 3m 50s	remaining: 14m 49s
2214:	learn: 0.0054023	total: 3m 50s	remaining: 13m 31s
2245:	learn: 0.0059098	total: 3m 50s	remaining: 13m 17s
2216:	learn: 0.0063909	total: 3m 50s	remaining: 13m 30s
2215:	learn: 0.0053988	total: 3m 50s	remaining: 13m 31s
2061:	learn: 0.0068860	total: 3m 51s	remaining: 14m 49s
2157:	learn: 0.0063552	total: 3m 51s	remaining: 13m 59s
2217:	learn: 0.0063877	total: 3m 50s	remaining: 13m 30s
2246:	learn: 0.0059065	total: 3m 51s	remaining: 13m 17s
2158:	learn: 0.0063511	total: 3m 51s	remaining: 13m 59s
2216:	learn: 0.0053941	total: 3m 51s	remaining: 13m 31s
2062:	learn: 0.0068802	total: 3m 51s	remaining: 14m 49s
2247:	learn: 0.0059047	total: 3m 51s	remaining: 13m 17s
2218:	learn: 0.0063826	total: 3m 51s	remaining: 13m 30s
2217:	learn: 0.0053912	total: 3m 51s	remaining: 13m 30s
2159:	learn: 0.0063476	total: 3m 51s	remaining: 13m 59s
2248:	learn: 0.0059003	total: 3m 51s	remaining: 13m 16s
2063:	learn: 0.0068743	total: 3m 51s	remaining: 14m 49s
2219:	learn: 0.0063796	total: 3m 51s	remaining: 13m 29s
2218:	learn: 0.0053865	total: 3m 51s	remaining: 13m 30s
2160:	learn: 0.0063406	total: 3m 51s	remaining: 13m 59s
2249:	learn: 0.0058962	total: 3m 51s	remaining: 13m 16s
2064:	learn: 0.0068695	total: 3m 51s	remaining: 14m 49s
2219:	learn: 0.0053825	total: 3m 51s	remaining: 13m 30s
2220:	learn: 0.0063759	total: 3m 51s	remaining: 13m 29s
2161:	learn: 0.0063371	total: 3m 51s	remaining: 13m 59s
2250:	learn: 0.0058921	total: 3m 51s	remaining: 13m 16s
2065:	learn: 0.0068664	total: 3m 51s	remaining: 14m 49s
2220:	learn: 0.0053783	total: 3m 51s	remaining: 13m 30s
2221:	learn: 0.0063694	total: 3m 51s	remaining: 13m 29s
2162:	learn: 0.0063336	total: 3m 51s	remaining: 13m 58s
2221:	learn: 0.0053746	total: 3m 51s	remaining: 13m 30s
2251:	learn: 0.0058894	total: 3m 51s	remaining: 13m 16s
2066:	learn: 0.0068612	total: 3m 51s	remaining: 14m 48s
2222:	learn: 0.0063647	total: 3m 51s	remaining: 13m 29s
2222:	learn: 0.0053720	total: 3m 51s	remaining: 13m 30s
2163:	learn: 0.0063291	total: 3m 51s	remaining: 13m 58s
2252:	learn: 0.0058864	total: 3m 51s	remaining: 13m 16s
2067:	learn: 0.0068539	total: 3m 51s	remaining: 14m 48s
2223:	learn: 0.0063619	total: 3m 51s	remaining: 13m 29s
2223:	learn: 0.0053682	total: 3m 51s	remaining: 13m 29s
2253:	learn: 0.0058839	total: 3m 51s	remaining: 13m 16s
2164:	learn: 0.0063246	total: 3m 51s	remaining: 13m 58s
2068:	learn: 0.0068478	total: 3m 51s	remaining: 14m 48s
2224:	learn: 0.0063559	total: 3m 51s	remaining: 13m 29s
2224:	learn: 0.0053658	total: 3m 51s	remaining: 13m 29s
2165:	learn: 0.0063201	total: 3m 51s	remaining: 13m 58s
2254:	learn: 0.0058793	total: 3m 51s	remaining: 13m 16s
2225:	learn: 0.0063504	total: 3m 51s	remaining: 13m 29s
2069:	learn: 0.0068442	total: 3m 51s	remaining: 14m 48s
2225:	learn: 0.0053622	total: 3m 51s	remaining: 13m 29s
2255:	learn: 0.0058764	total: 3m 51s	remaining: 13m 16s
2226:	learn: 0.0063450	total: 3m 51s	remaining: 13m 29s
2166:	learn: 0.0063157	total: 3m 51s	remaining: 13m 58s
2070:	learn: 0.0068416	total: 3m 52s	remaining: 14m 48s
2226:	learn: 0.0053589	total: 3m 51s	remaining: 13m 29s
2256:	learn: 0.0058733	total: 3m 52s	remaining: 13m 16s
2227:	learn: 0.0063410	total: 3m 51s	remaining: 13m 29s
2071:	learn: 0.0068369	total: 3m 52s	remaining: 14m 48s
2167:	learn: 0.0063113	total: 3m 52s	remaining: 13m 58s
2257:	learn: 0.0058687	total: 3m 52s	remaining: 13m 15s
2072:	learn: 0.0068300	total: 3m 52s	remaining: 14m 47s
2227:	learn: 0.0053550	total: 3m 52s	remaining: 13m 29s
2228:	learn: 0.0063357	total: 3m 52s	remaining: 13m 28s
2168:	learn: 0.0063057	total: 3m 52s	remaining: 13m 58s
2258:	learn: 0.0058668	total: 3m 52s	remaining: 13m 15s
2228:	learn: 0.0053499	total: 3m 52s	remaining: 13m 29s
2229:	learn: 0.0063328	total: 3m 52s	remaining: 13m 28s
2073:	learn: 0.0068240	total: 3m 52s	remaining: 14m 47s
2169:	learn: 0.0063010	total: 3m 52s	remaining: 13m 58s
2259:	learn: 0.0058634	total: 3m 52s	remaining: 13m 15s
2229:	learn: 0.0053472	total: 3m 52s	remaining: 13m 29s
2230:	learn: 0.0063283	total: 3m 52s	remaining: 13m 28s
2170:	learn: 0.0062973	total: 3m 52s	remaining: 13m 58s
2260:	learn: 0.0058577	total: 3m 52s	remaining: 13m 15s
2074:	learn: 0.0068173	total: 3m 52s	remaining: 14m 47s
2231:	learn: 0.0063247	total: 3m 52s	remaining: 13m 28s
2261:	learn: 0.0058547	total: 3m 52s	remaining: 13m 15s
2230:	learn: 0.0053444	total: 3m 52s	remaining: 13m 29s
2171:	learn: 0.0062939	total: 3m 52s	remaining: 13m 57s
2075:	learn: 0.0068102	total: 3m 52s	remaining: 14m 47s
2232:	learn: 0.0063200	total: 3m 52s	remaining: 13m 28s
2262:	learn: 0.0058510	total: 3m 52s	remaining: 13m 15s
2231:	learn: 0.0053403	total: 3m 52s	remaining: 13m 29s
2172:	learn: 0.0062905	total: 3m 52s	remaining: 13m 57s
2233:	learn: 0.0063123	total: 3m 52s	remaining: 13m 28s
2076:	learn: 0.0068049	total: 3m 52s	remaining: 14m 47s
2232:	learn: 0.0053366	total: 3m 52s	remaining: 13m 29s
2173:	learn: 0.0062865	total: 3m 52s	remaining: 13m 57s
2234:	learn: 0.0063070	total: 3m 52s	remaining: 13m 28s
2263:	learn: 0.0058475	total: 3m 52s	remaining: 13m 15s
2077:	learn: 0.0067974	total: 3m 52s	remaining: 14m 47s
2233:	learn: 0.0053326	total: 3m 52s	remaining: 13m 28s
2235:	learn: 0.0063039	total: 3m 52s	remaining: 13m 27s
2264:	learn: 0.0058448	total: 3m 52s	remaining: 13m 15s
2174:	learn: 0.0062832	total: 3m 52s	remaining: 13m 57s
2078:	learn: 0.0067926	total: 3m 52s	remaining: 14m 47s
2234:	learn: 0.0053295	total: 3m 52s	remaining: 13m 28s
2236:	learn: 0.0063008	total: 3m 52s	remaining: 13m 27s
2265:	learn: 0.0058412	total: 3m 52s	remaining: 13m 14s
2175:	learn: 0.0062772	total: 3m 52s	remaining: 13m 57s
2079:	learn: 0.0067859	total: 3m 52s	remaining: 14m 47s
2237:	learn: 0.0062979	total: 3m 52s	remaining: 13m 27s
2235:	learn: 0.0053254	total: 3m 52s	remaining: 13m 28s
2266:	learn: 0.0058367	total: 3m 53s	remaining: 13m 14s
2080:	learn: 0.0067801	total: 3m 53s	remaining: 14m 46s
2176:	learn: 0.0062732	total: 3m 53s	remaining: 13m 57s
2238:	learn: 0.0062948	total: 3m 52s	remaining: 13m 27s
2236:	learn: 0.0053206	total: 3m 53s	remaining: 13m 28s
2267:	learn: 0.0058352	total: 3m 53s	remaining: 13m 14s
2239:	learn: 0.0062905	total: 3m 52s	remaining: 13m 27s
2081:	learn: 0.0067736	total: 3m 53s	remaining: 14m 46s
2177:	learn: 0.0062698	total: 3m 53s	remaining: 13m 57s
2237:	learn: 0.0053165	total: 3m 53s	remaining: 13m 28s
2240:	learn: 0.0062877	total: 3m 53s	remaining: 13m 26s
2268:	learn: 0.0058321	total: 3m 53s	remaining: 13m 14s
2082:	learn: 0.0067654	total: 3m 53s	remaining: 14m 46s
2178:	learn: 0.0062667	total: 3m 53s	remaining: 13m 57s
2238:	learn: 0.0053125	total: 3m 53s	remaining: 13m 28s
2241:	learn: 0.0062844	total: 3m 53s	remaining: 13m 26s
2269:	learn: 0.0058278	total: 3m 53s	remaining: 13m 14s
2179:	learn: 0.0062616	total: 3m 53s	remaining: 13m 57s
2083:	learn: 0.0067573	total: 3m 53s	remaining: 14m 46s
2239:	learn: 0.0053080	total: 3m 53s	remaining: 13m 28s
2242:	learn: 0.0062820	total: 3m 53s	remaining: 13m 26s
2270:	learn: 0.0058245	total: 3m 53s	remaining: 13m 14s
2180:	learn: 0.0062573	total: 3m 53s	remaining: 13m 56s

2084:	learn: 0.0067512	total: 3m 53s	remaining: 14m 46s
2240:	learn: 0.0053050	total: 3m 53s	remaining: 13m 28s
2243:	learn: 0.0062758	total: 3m 53s	remaining: 13m 26s
2271:	learn: 0.0058206	total: 3m 53s	remaining: 13m 14s
2085:	learn: 0.0067463	total: 3m 53s	remaining: 14m 46s
2181:	learn: 0.0062533	total: 3m 53s	remaining: 13m 56s
2241:	learn: 0.0053013	total: 3m 53s	remaining: 13m 28s
2272:	learn: 0.0058179	total: 3m 53s	remaining: 13m 14s
2244:	learn: 0.0062718	total: 3m 53s	remaining: 13m 26s
2086:	learn: 0.0067409	total: 3m 53s	remaining: 14m 46s
2182:	learn: 0.0062489	total: 3m 53s	remaining: 13m 56s
2242:	learn: 0.0052963	total: 3m 53s	remaining: 13m 28s
2087:	learn: 0.0067364	total: 3m 53s	remaining: 14m 45s
2273:	learn: 0.0058150	total: 3m 53s	remaining: 13m 14s
2183:	learn: 0.0062435	total: 3m 53s	remaining: 13m 56s
2245:	learn: 0.0062688	total: 3m 53s	remaining: 13m 26s
2243:	learn: 0.0052918	total: 3m 53s	remaining: 13m 27s
2088:	learn: 0.0067294	total: 3m 53s	remaining: 14m 45s
2274:	learn: 0.0058102	total: 3m 53s	remaining: 13m 14s
2184:	learn: 0.0062378	total: 3m 53s	remaining: 13m 56s
2246:	learn: 0.0062649	total: 3m 53s	remaining: 13m 26s
2244:	learn: 0.0052875	total: 3m 53s	remaining: 13m 27s
2089:	learn: 0.0067253	total: 3m 53s	remaining: 14m 45s
2275:	learn: 0.0058064	total: 3m 53s	remaining: 13m 13s
2185:	learn: 0.0062332	total: 3m 53s	remaining: 13m 56s
2247:	learn: 0.0062623	total: 3m 53s	remaining: 13m 26s
2090:	learn: 0.0067181	total: 3m 54s	remaining: 14m 45s
2245:	learn: 0.0052842	total: 3m 53s	remaining: 13m 27s
2186:	learn: 0.0062300	total: 3m 54s	remaining: 13m 56s
2276:	learn: 0.0058031	total: 3m 54s	remaining: 13m 13s
2248:	learn: 0.0062575	total: 3m 53s	remaining: 13m 26s
2246:	learn: 0.0052816	total: 3m 54s	remaining: 13m 27s
2091:	learn: 0.0067146	total: 3m 54s	remaining: 14m 45s
2277:	learn: 0.0057986	total: 3m 54s	remaining: 13m 13s
2187:	learn: 0.0062267	total: 3m 54s	remaining: 13m 56s
2249:	learn: 0.0062551	total: 3m 54s	remaining: 13m 26s
2278:	learn: 0.0057956	total: 3m 54s	remaining: 13m 13s
2092:	learn: 0.0067067	total: 3m 54s	remaining: 14m 44s
2247:	learn: 0.0052784	total: 3m 54s	remaining: 13m 27s
2250:	learn: 0.0062523	total: 3m 54s	remaining: 13m 26s
2279:	learn: 0.0057922	total: 3m 54s	remaining: 13m 13s
2188:	learn: 0.0062231	total: 3m 54s	remaining: 13m 56s
2248:	learn: 0.0052734	total: 3m 54s	remaining: 13m 27s
2093:	learn: 0.0067032	total: 3m 54s	remaining: 14m 44s
2280:	learn: 0.0057874	total: 3m 54s	remaining: 13m 13s
2251:	learn: 0.0062485	total: 3m 54s	remaining: 13m 25s
2249:	learn: 0.0052701	total: 3m 54s	remaining: 13m 27s
2189:	learn: 0.0062191	total: 3m 54s	remaining: 13m 56s
2094:	learn: 0.0066953	total: 3m 54s	remaining: 14m 44s
2281:	learn: 0.0057850	total: 3m 54s	remaining: 13m 12s
2250:	learn: 0.0052660	total: 3m 54s	remaining: 13m 27s
2282:	learn: 0.0057822	total: 3m 54s	remaining: 13m 12s
2252:	learn: 0.0062423	total: 3m 54s	remaining: 13m 25s
2190:	learn: 0.0062148	total: 3m 54s	remaining: 13m 55s
2095:	learn: 0.0066918	total: 3m 54s	remaining: 14m 44s
2283:	learn: 0.0057791	total: 3m 54s	remaining: 13m 12s
2251:	learn: 0.0052628	total: 3m 54s	remaining: 13m 26s
2253:	learn: 0.0062400	total: 3m 54s	remaining: 13m 25s
2191:	learn: 0.0062105	total: 3m 54s	remaining: 13m 55s
2096:	learn: 0.0066900	total: 3m 54s	remaining: 14m 44s
2284:	learn: 0.0057752	total: 3m 54s	remaining: 13m 12s
2254:	learn: 0.0062359	total: 3m 54s	remaining: 13m 25s
2252:	learn: 0.0052592	total: 3m 54s	remaining: 13m 26s
2192:	learn: 0.0062066	total: 3m 54s	remaining: 13m 55s
2097:	learn: 0.0066822	total: 3m 54s	remaining: 14m 44s
2285:	learn: 0.0057729	total: 3m 54s	remaining: 13m 12s
2255:	learn: 0.0062330	total: 3m 54s	remaining: 13m 25s
2253:	learn: 0.0052546	total: 3m 54s	remaining: 13m 26s
2193:	learn: 0.0062031	total: 3m 54s	remaining: 13m 55s
2098:	learn: 0.0066767	total: 3m 54s	remaining: 14m 44s
2286:	learn: 0.0057700	total: 3m 54s	remaining: 13m 12s
2254:	learn: 0.0052506	total: 3m 54s	remaining: 13m 26s
2194:	learn: 0.0062000	total: 3m 54s	remaining: 13m 55s
2256:	learn: 0.0062303	total: 3m 54s	remaining: 13m 25s
2099:	learn: 0.0066699	total: 3m 55s	remaining: 14m 44s
2287:	learn: 0.0057658	total: 3m 54s	remaining: 13m 12s
2255:	learn: 0.0052475	total: 3m 54s	remaining: 13m 26s
2195:	learn: 0.0061958	total: 3m 55s	remaining: 13m 55s
2257:	learn: 0.0062250	total: 3m 54s	remaining: 13m 25s
2100:	learn: 0.0066659	total: 3m 55s	remaining: 14m 43s
2288:	learn: 0.0057626	total: 3m 55s	remaining: 13m 11s
2256:	learn: 0.0052445	total: 3m 55s	remaining: 13m 26s
2196:	learn: 0.0061914	total: 3m 55s	remaining: 13m 55s
2101:	learn: 0.0066614	total: 3m 55s	remaining: 14m 43s
2258:	learn: 0.0062202	total: 3m 55s	remaining: 13m 25s
2257:	learn: 0.0052418	total: 3m 55s	remaining: 13m 26s
2289:	learn: 0.0057581	total: 3m 55s	remaining: 13m 11s
2197:	learn: 0.0061882	total: 3m 55s	remaining: 13m 54s
2102:	learn: 0.0066550	total: 3m 55s	remaining: 14m 43s
2259:	learn: 0.0062173	total: 3m 55s	remaining: 13m 25s
2258:	learn: 0.0052374	total: 3m 55s	remaining: 13m 25s
2290:	learn: 0.0057565	total: 3m 55s	remaining: 13m 11s
2259:	learn: 0.0052331	total: 3m 55s	remaining: 13m 25s
2198:	learn: 0.0061840	total: 3m 55s	remaining: 13m 54s
2260:	learn: 0.0062144	total: 3m 55s	remaining: 13m 25s
2103:	learn: 0.0066479	total: 3m 55s	remaining: 14m 43s
2291:	learn: 0.0057521	total: 3m 55s	remaining: 13m 11s
2260:	learn: 0.0052288	total: 3m 55s	remaining: 13m 25s
2199:	learn: 0.0061799	total: 3m 55s	remaining: 13m 54s
2261:	learn: 0.0062095	total: 3m 55s	remaining: 13m 25s
2104:	learn: 0.0066419	total: 3m 55s	remaining: 14m 43s
2292:	learn: 0.0057474	total: 3m 55s	remaining: 13m 11s
2261:	learn: 0.0052248	total: 3m 55s	remaining: 13m 25s
2200:	learn: 0.0061775	total: 3m 55s	remaining: 13m 54s
2262:	learn: 0.0062054	total: 3m 55s	remaining: 13m 24s
2293:	learn: 0.0057462	total: 3m 55s	remaining: 13m 11s
2262:	learn: 0.0052216	total: 3m 55s	remaining: 13m 25s
2263:	learn: 0.0061999	total: 3m 55s	remaining: 13m 24s
2105:	learn: 0.0066394	total: 3m 55s	remaining: 14m 43s
2201:	learn: 0.0061720	total: 3m 55s	remaining: 13m 54s
2294:	learn: 0.0057417	total: 3m 55s	remaining: 13m 11s
2264:	learn: 0.0061951	total: 3m 55s	remaining: 13m 24s
2263:	learn: 0.0052176	total: 3m 55s	remaining: 13m 25s
2202:	learn: 0.0061684	total: 3m 55s	remaining: 13m 54s
2265:	learn: 0.0061918	total: 3m 55s	remaining: 13m 24s
2295:	learn: 0.0057375	total: 3m 55s	remaining: 13m 11s
2106:	learn: 0.0066340	total: 3m 55s	remaining: 14m 43s
2264:	learn: 0.0052133	total: 3m 55s	remaining: 13m 25s
2203:	learn: 0.0061649	total: 3m 55s	remaining: 13m 54s
2266:	learn: 0.0061871	total: 3m 55s	remaining: 13m 24s
2107:	learn: 0.0066286	total: 3m 55s	remaining: 14m 43s
2296:	learn: 0.0057325	total: 3m 55s	remaining: 13m 11s
2265:	learn: 0.0052088	total: 3m 55s	remaining: 13m 24s
2204:	learn: 0.0061605	total: 3m 55s	remaining: 13m 54s
2108:	learn: 0.0066220	total: 3m 56s	remaining: 14m 43s
2267:	learn: 0.0061830	total: 3m 55s	remaining: 13m 24s
2297:	learn: 0.0057271	total: 3m 55s	remaining: 13m 10s
2266:	learn: 0.0052051	total: 3m 55s	remaining: 13m 24s
2109:	learn: 0.0066164	total: 3m 56s	remaining: 14m 42s
2205:	learn: 0.0061538	total: 3m 56s	remaining: 13m 54s
2268:	learn: 0.0061770	total: 3m 55s	remaining: 13m 23s
2298:	learn: 0.0057237	total: 3m 56s	remaining: 13m 10s
2110:	learn: 0.0066109	total: 3m 56s	remaining: 14m 42s
2206:	learn: 0.0061507	total: 3m 56s	remaining: 13m 53s
2269:	learn: 0.0061741	total: 3m 56s	remaining: 13m 23s
2267:	learn: 0.0052014	total: 3m 56s	remaining: 13m 24s
2299:	learn: 0.0057198	total: 3m 56s	remaining: 13m 10s
2111:	learn: 0.0066064	total: 3m 56s	remaining: 14m 42s
2207:	learn: 0.0061440	total: 3m 56s	remaining: 13m 53s
2270:	learn: 0.0061692	total: 3m 56s	remaining: 13m 23s
2268:	learn: 0.0051979	total: 3m 56s	remaining: 13m 24s
2300:	learn: 0.0057161	total: 3m 56s	remaining: 13m 10s
2112:	learn: 0.0066016	total: 3m 56s	remaining: 14m 42s
2208:	learn: 0.0061409	total: 3m 56s	remaining: 13m 53s
2271:	learn: 0.0061665	total: 3m 56s	remaining: 13m 23s
2269:	learn: 0.0051950	total: 3m 56s	remaining: 13m 24s
2301:	learn: 0.0057134	total: 3m 56s	remaining: 13m 10s
2113:	learn: 0.0065972	total: 3m 56s	remaining: 14m 42s
2272:	learn: 0.0061637	total: 3m 56s	remaining: 13m 23s
2209:	learn: 0.0061348	total: 3m 56s	remaining: 13m 53s
2270:	learn: 0.0051928	total: 3m 56s	remaining: 13m 24s
2302:	learn: 0.0057095	total: 3m 56s	remaining: 13m 10s
2114:	learn: 0.0065907	total: 3m 56s	remaining: 14m 41s
2273:	learn: 0.0061585	total: 3m 56s	remaining: 13m 23s
2210:	learn: 0.0061315	total: 3m 56s	remaining: 13m 53s
2271:	learn: 0.0051896	total: 3m 56s	remaining: 13m 24s
2303:	learn: 0.0057059	total: 3m 56s	remaining: 13m 10s
2115:	learn: 0.0065842	total: 3m 56s	remaining: 14m 41s
2272:	learn: 0.0051863	total: 3m 56s	remaining: 13m 24s
2211:	learn: 0.0061289	total: 3m 56s	remaining: 13m 53s
2304:	learn: 0.0057029	total: 3m 56s	remaining: 13m 10s
2274:	learn: 0.0061530	total: 3m 56s	remaining: 13m 23s
2116:	learn: 0.0065790	total: 3m 56s	remaining: 14m 41s
2305:	learn: 0.0056984	total: 3m 56s	remaining: 13m 9s
2275:	learn: 0.0061485	total: 3m 56s	remaining: 13m 23s
2273:	learn: 0.0051826	total: 3m 56s	remaining: 13m 24s
2212:	learn: 0.0061247	total: 3m 56s	remaining: 13m 53s
2306:	learn: 0.0056941	total: 3m 56s	remaining: 13m 9s
2117:	learn: 0.0065741	total: 3m 56s	remaining: 14m 41s
2274:	learn: 0.0051802	total: 3m 56s	remaining: 13m 24s
2276:	learn: 0.0061458	total: 3m 56s	remaining: 13m 22s
2213:	learn: 0.0061181	total: 3m 56s	remaining: 13m 53s
2307:	learn: 0.0056923	total: 3m 56s	remaining: 13m 9s
2118:	learn: 0.0065665	total: 3m 57s	remaining: 14m 41s
2275:	learn: 0.0051771	total: 3m 56s	remaining: 13m 23s
2277:	learn: 0.0061410	total: 3m 56s	remaining: 13m 22s
2308:	learn: 0.0056899	total: 3m 57s	remaining: 13m 9s
2119:	learn: 0.0065641	total: 3m 57s	remaining: 14m 41s
2214:	learn: 0.0061139	total: 3m 57s	remaining: 13m 53s
2278:	learn: 0.0061383	total: 3m 56s	remaining: 13m 22s
2276:	learn: 0.0051736	total: 3m 57s	remaining: 13m 23s
2309:	learn: 0.0056858	total: 3m 57s	remaining: 13m 9s
2120:	learn: 0.0065591	total: 3m 57s	remaining: 14m 41s
2279:	learn: 0.0061357	total: 3m 57s	remaining: 13m 22s
2215:	learn: 0.0061112	total: 3m 57s	remaining: 13m 53s
2277:	learn: 0.0051700	total: 3m 57s	remaining: 13m 23s
2121:	learn: 0.0065524	total: 3m 57s	remaining: 14m 40s
2280:	learn: 0.0061311	total: 3m 57s	remaining: 13m 22s
2310:	learn: 0.0056835	total: 3m 57s	remaining: 13m 9s
2216:	learn: 0.0061066	total: 3m 57s	remaining: 13m 52s
2278:	learn: 0.0051669	total: 3m 57s	remaining: 13m 23s
2311:	learn: 0.0056823	total: 3m 57s	remaining: 13m 9s
2122:	learn: 0.0065460	total: 3m 57s	remaining: 14m 40s
2281:	learn: 0.0061256	total: 3m 57s	remaining: 13m 22s
2217:	learn: 0.0061029	total: 3m 57s	remaining: 13m 52s
2279:	learn: 0.0051602	total: 3m 57s	remaining: 13m 23s
2312:	learn: 0.0056787	total: 3m 57s	remaining: 13m 9s
2282:	learn: 0.0061202	total: 3m 57s	remaining: 13m 22s
2123:	learn: 0.0065402	total: 3m 57s	remaining: 14m 40s
2218:	learn: 0.0060992	total: 3m 57s	remaining: 13m 52s
2280:	learn: 0.0051570	total: 3m 57s	remaining: 13m 23s
2313:	learn: 0.0056750	total: 3m 57s	remaining: 13m 8s
2124:	learn: 0.0065346	total: 3m 57s	remaining: 14m 40s
2283:	learn: 0.0061152	total: 3m 57s	remaining: 13m 22s
2219:	learn: 0.0060948	total: 3m 57s	remaining: 13m 52s
2281:	learn: 0.0051542	total: 3m 57s	remaining: 13m 23s
2314:	learn: 0.0056724	total: 3m 57s	remaining: 13m 8s
2284:	learn: 0.0061114	total: 3m 57s	remaining: 13m 21s
2125:	learn: 0.0065304	total: 3m 57s	remaining: 14m 40s
2220:	learn: 0.0060912	total: 3m 57s	remaining: 13m 52s
2282:	learn: 0.0051513	total: 3m 57s	remaining: 13m 23s
2285:	learn: 0.0061078	total: 3m 57s	remaining: 13m 21s
2315:	learn: 0.0056681	total: 3m 57s	remaining: 13m 8s
2286:	learn: 0.0061033	total: 3m 57s	remaining: 13m 21s
2283:	learn: 0.0051463	total: 3m 57s	remaining: 13m 23s
2126:	learn: 0.0065240	total: 3m 57s	remaining: 14m 40s
2316:	learn: 0.0056636	total: 3m 57s	remaining: 13m 8s
2221:	learn: 0.0060872	total: 3m 57s	remaining: 13m 52s
2284:	learn: 0.0051437	total: 3m 57s	remaining: 13m 22s
2317:	learn: 0.0056595	total: 3m 57s	remaining: 13m 8s
2287:	learn: 0.0061002	total: 3m 57s	remaining: 13m 21s
2127:	learn: 0.0065179	total: 3m 57s	remaining: 14m 40s
2222:	learn: 0.0060837	total: 3m 57s	remaining: 13m 52s
2285:	learn: 0.0051409	total: 3m 57s	remaining: 13m 22s
2288:	learn: 0.0060952	total: 3m 57s	remaining: 13m 21s
2318:	learn: 0.0056543	total: 3m 58s	remaining: 13m 8s
2128:	learn: 0.0065144	total: 3m 58s	remaining: 14m 40s
2223:	learn: 0.0060801	total: 3m 58s	remaining: 13m 52s
2286:	learn: 0.0051372	total: 3m 57s	remaining: 13m 22s
2319:	learn: 0.0056515	total: 3m 58s	remaining: 13m 8s
2289:	learn: 0.0060898	total: 3m 57s	remaining: 13m 21s
2224:	learn: 0.0060756	total: 3m 58s	remaining: 13m 52s
2287:	learn: 0.0051341	total: 3m 58s	remaining: 13m 22s
2129:	learn: 0.0065097	total: 3m 58s	remaining: 14m 40s
2320:	learn: 0.0056455	total: 3m 58s	remaining: 13m 7s
2225:	learn: 0.0060718	total: 3m 58s	remaining: 13m 51s
2288:	learn: 0.0051306	total: 3m 58s	remaining: 13m 22s
2290:	learn: 0.0060874	total: 3m 58s	remaining: 13m 21s
2321:	learn: 0.0056429	total: 3m 58s	remaining: 13m 7s
2130:	learn: 0.0065033	total: 3m 58s	remaining: 14m 40s
2226:	learn: 0.0060678	total: 3m 58s	remaining: 13m 51s
2289:	learn: 0.0051264	total: 3m 58s	remaining: 13m 22s
2322:	learn: 0.0056391	total: 3m 58s	remaining: 13m 7s
2291:	learn: 0.0060835	total: 3m 58s	remaining: 13m 21s
2227:	learn: 0.0060648	total: 3m 58s	remaining: 13m 51s
2131:	learn: 0.0064970	total: 3m 58s	remaining: 14m 39s
2290:	learn: 0.0051236	total: 3m 58s	remaining: 13m 22s
2323:	learn: 0.0056380	total: 3m 58s	remaining: 13m 7s
2292:	learn: 0.0060778	total: 3m 58s	remaining: 13m 21s
2228:	learn: 0.0060617	total: 3m 58s	remaining: 13m 51s
2132:	learn: 0.0064928	total: 3m 58s	remaining: 14m 39s
2291:	learn: 0.0051201	total: 3m 58s	remaining: 13m 21s
2293:	learn: 0.0060727	total: 3m 58s	remaining: 13m 20s
2324:	learn: 0.0056343	total: 3m 58s	remaining: 13m 7s
2229:	learn: 0.0060572	total: 3m 58s	remaining: 13m 51s
2133:	learn: 0.0064862	total: 3m 58s	remaining: 14m 39s
2292:	learn: 0.0051164	total: 3m 58s	remaining: 13m 21s
2325:	learn: 0.0056320	total: 3m 58s	remaining: 13m 7s
2294:	learn: 0.0060689	total: 3m 58s	remaining: 13m 20s
2230:	learn: 0.0060543	total: 3m 58s	remaining: 13m 51s
2134:	learn: 0.0064819	total: 3m 58s	remaining: 14m 39s
2293:	learn: 0.0051122	total: 3m 58s	remaining: 13m 21s
2326:	learn: 0.0056262	total: 3m 58s	remaining: 13m 7s
2295:	learn: 0.0060657	total: 3m 58s	remaining: 13m 20s
2231:	learn: 0.0060500	total: 3m 58s	remaining: 13m 51s
2294:	learn: 0.0051093	total: 3m 58s	remaining: 13m 21s
2135:	learn: 0.0064755	total: 3m 58s	remaining: 14m 39s
2327:	learn: 0.0056220	total: 3m 58s	remaining: 13m 7s
2296:	learn: 0.0060594	total: 3m 58s	remaining: 13m 20s
2232:	learn: 0.0060461	total: 3m 58s	remaining: 13m 51s
2295:	learn: 0.0051057	total: 3m 58s	remaining: 13m 21s
2328:	learn: 0.0056172	total: 3m 58s	remaining: 13m 6s
2136:	learn: 0.0064734	total: 3m 58s	remaining: 14m 39s
2297:	learn: 0.0060555	total: 3m 58s	remaining: 13m 20s
2233:	learn: 0.0060422	total: 3m 59s	remaining: 13m 50s
2137:	learn: 0.0064669	total: 3m 59s	remaining: 14m 39s
2296:	learn: 0.0051021	total: 3m 58s	remaining: 13m 21s
2329:	learn: 0.0056127	total: 3m 59s	remaining: 13m 6s
2298:	learn: 0.0060530	total: 3m 58s	remaining: 13m 20s
2234:	learn: 0.0060394	total: 3m 59s	remaining: 13m 50s
2297:	learn: 0.0050980	total: 3m 59s	remaining: 13m 21s
2138:	learn: 0.0064621	total: 3m 59s	remaining: 14m 38s
2330:	learn: 0.0056085	total: 3m 59s	remaining: 13m 6s
2299:	learn: 0.0060492	total: 3m 59s	remaining: 13m 20s
2235:	learn: 0.0060365	total: 3m 59s	remaining: 13m 50s
2139:	learn: 0.0064589	total: 3m 59s	remaining: 14m 38s
2298:	learn: 0.0050942	total: 3m 59s	remaining: 13m 21s
2236:	learn: 0.0060343	total: 3m 59s	remaining: 13m 50s
2331:	learn: 0.0056046	total: 3m 59s	remaining: 13m 6s
2300:	learn: 0.0060439	total: 3m 59s	remaining: 13m 20s
2140:	learn: 0.0064529	total: 3m 59s	remaining: 14m 38s
2299:	learn: 0.0050909	total: 3m 59s	remaining: 13m 21s

2332:	learn: 0.0056017	total: 3m 59s	remaining: 13m 6s
2301:	learn: 0.0060413	total: 3m 59s	remaining: 13m 20s
2237:	learn: 0.0060299	total: 3m 59s	remaining: 13m 50s
2141:	learn: 0.0064466	total: 3m 59s	remaining: 14m 38s
2333:	learn: 0.0055988	total: 3m 59s	remaining: 13m 6s
2300:	learn: 0.0050864	total: 3m 59s	remaining: 13m 21s
2302:	learn: 0.0060367	total: 3m 59s	remaining: 13m 19s
2142:	learn: 0.0064408	total: 3m 59s	remaining: 14m 38s
2238:	learn: 0.0060261	total: 3m 59s	remaining: 13m 50s
2334:	learn: 0.0055956	total: 3m 59s	remaining: 13m 6s
2301:	learn: 0.0050824	total: 3m 59s	remaining: 13m 20s
2143:	learn: 0.0064356	total: 3m 59s	remaining: 14m 38s
2303:	learn: 0.0060341	total: 3m 59s	remaining: 13m 19s
2335:	learn: 0.0055902	total: 3m 59s	remaining: 13m 6s
2239:	learn: 0.0060212	total: 3m 59s	remaining: 13m 50s
2144:	learn: 0.0064316	total: 3m 59s	remaining: 14m 37s
2302:	learn: 0.0050785	total: 3m 59s	remaining: 13m 20s
2240:	learn: 0.0060161	total: 3m 59s	remaining: 13m 49s
2336:	learn: 0.0055865	total: 3m 59s	remaining: 13m 5s
2304:	learn: 0.0060300	total: 3m 59s	remaining: 13m 19s
2145:	learn: 0.0064264	total: 3m 59s	remaining: 14m 37s
2337:	learn: 0.0055839	total: 3m 59s	remaining: 13m 5s
2303:	learn: 0.0050744	total: 3m 59s	remaining: 13m 20s
2241:	learn: 0.0060124	total: 3m 59s	remaining: 13m 49s
2305:	learn: 0.0060269	total: 3m 59s	remaining: 13m 19s
2146:	learn: 0.0064217	total: 3m 59s	remaining: 14m 37s
2338:	learn: 0.0055813	total: 3m 59s	remaining: 13m 5s
2306:	learn: 0.0060231	total: 3m 59s	remaining: 13m 19s
2304:	learn: 0.0050720	total: 3m 59s	remaining: 13m 20s
2242:	learn: 0.0060072	total: 3m 59s	remaining: 13m 49s
2147:	learn: 0.0064172	total: 4m	remaining: 14m 37s
2339:	learn: 0.0055784	total: 3m 59s	remaining: 13m 5s
2307:	learn: 0.0060188	total: 3m 59s	remaining: 13m 19s
2305:	learn: 0.0050676	total: 3m 59s	remaining: 13m 20s
2243:	learn: 0.0060032	total: 4m	remaining: 13m 49s
2148:	learn: 0.0064123	total: 4m	remaining: 14m 37s
2340:	learn: 0.0055753	total: 4m	remaining: 13m 5s
2308:	learn: 0.0060157	total: 3m 59s	remaining: 13m 19s
2306:	learn: 0.0050646	total: 4m	remaining: 13m 20s
2244:	learn: 0.0059983	total: 4m	remaining: 13m 49s
2341:	learn: 0.0055715	total: 4m	remaining: 13m 5s
2149:	learn: 0.0064062	total: 4m	remaining: 14m 37s
2309:	learn: 0.0060119	total: 4m	remaining: 13m 19s
2307:	learn: 0.0050606	total: 4m	remaining: 13m 20s
2245:	learn: 0.0059941	total: 4m	remaining: 13m 49s
2310:	learn: 0.0060079	total: 4m	remaining: 13m 18s
2342:	learn: 0.0055679	total: 4m	remaining: 13m 5s
2308:	learn: 0.0050567	total: 4m	remaining: 13m 20s
2150:	learn: 0.0064013	total: 4m	remaining: 14m 37s
2311:	learn: 0.0060044	total: 4m	remaining: 13m 18s
2246:	learn: 0.0059904	total: 4m	remaining: 13m 49s
2343:	learn: 0.0055641	total: 4m	remaining: 13m 5s
2309:	learn: 0.0050534	total: 4m	remaining: 13m 20s
2151:	learn: 0.0063946	total: 4m	remaining: 14m 36s
2312:	learn: 0.0060017	total: 4m	remaining: 13m 18s
2247:	learn: 0.0059881	total: 4m	remaining: 13m 49s
2344:	learn: 0.0055586	total: 4m	remaining: 13m 5s
2310:	learn: 0.0050494	total: 4m	remaining: 13m 19s
2313:	learn: 0.0059979	total: 4m	remaining: 13m 18s
2152:	learn: 0.0063914	total: 4m	remaining: 14m 36s
2248:	learn: 0.0059846	total: 4m	remaining: 13m 49s
2345:	learn: 0.0055545	total: 4m	remaining: 13m 4s
2314:	learn: 0.0059923	total: 4m	remaining: 13m 18s
2311:	learn: 0.0050445	total: 4m	remaining: 13m 19s
2249:	learn: 0.0059817	total: 4m	remaining: 13m 48s
2153:	learn: 0.0063891	total: 4m	remaining: 14m 36s
2315:	learn: 0.0059898	total: 4m	remaining: 13m 18s
2346:	learn: 0.0055521	total: 4m	remaining: 13m 4s
2312:	learn: 0.0050402	total: 4m	remaining: 13m 19s
2250:	learn: 0.0059771	total: 4m	remaining: 13m 48s
2154:	learn: 0.0063841	total: 4m	remaining: 14m 36s
2316:	learn: 0.0059864	total: 4m	remaining: 13m 17s
2347:	learn: 0.0055496	total: 4m	remaining: 13m 4s
2313:	learn: 0.0050379	total: 4m	remaining: 13m 19s
2251:	learn: 0.0059729	total: 4m	remaining: 13m 48s
2155:	learn: 0.0063792	total: 4m	remaining: 14m 36s
2317:	learn: 0.0059839	total: 4m	remaining: 13m 17s
2314:	learn: 0.0050339	total: 4m	remaining: 13m 19s
2252:	learn: 0.0059692	total: 4m	remaining: 13m 48s
2348:	learn: 0.0055464	total: 4m	remaining: 13m 4s
2156:	learn: 0.0063721	total: 4m 1s	remaining: 14m 36s
2318:	learn: 0.0059797	total: 4m	remaining: 13m 17s
2253:	learn: 0.0059658	total: 4m 1s	remaining: 13m 48s
2315:	learn: 0.0050302	total: 4m	remaining: 13m 19s
2157:	learn: 0.0063647	total: 4m 1s	remaining: 14m 36s
2319:	learn: 0.0059772	total: 4m	remaining: 13m 17s
2349:	learn: 0.0055424	total: 4m 1s	remaining: 13m 4s
2254:	learn: 0.0059620	total: 4m 1s	remaining: 13m 48s
2316:	learn: 0.0050262	total: 4m 1s	remaining: 13m 19s
2158:	learn: 0.0063631	total: 4m 1s	remaining: 14m 35s
2320:	learn: 0.0059717	total: 4m 1s	remaining: 13m 17s
2350:	learn: 0.0055386	total: 4m 1s	remaining: 13m 4s
2255:	learn: 0.0059584	total: 4m 1s	remaining: 13m 48s
2317:	learn: 0.0050218	total: 4m 1s	remaining: 13m 19s
2159:	learn: 0.0063582	total: 4m 1s	remaining: 14m 35s
2321:	learn: 0.0059662	total: 4m 1s	remaining: 13m 17s
2351:	learn: 0.0055353	total: 4m 1s	remaining: 13m 4s
2256:	learn: 0.0059537	total: 4m 1s	remaining: 13m 47s
2318:	learn: 0.0050185	total: 4m 1s	remaining: 13m 19s
2160:	learn: 0.0063543	total: 4m 1s	remaining: 14m 35s
2322:	learn: 0.0059636	total: 4m 1s	remaining: 13m 17s
2257:	learn: 0.0059500	total: 4m 1s	remaining: 13m 47s
2319:	learn: 0.0050146	total: 4m 1s	remaining: 13m 18s
2352:	learn: 0.0055338	total: 4m 1s	remaining: 13m 4s
2161:	learn: 0.0063492	total: 4m 1s	remaining: 14m 35s
2258:	learn: 0.0059467	total: 4m 1s	remaining: 13m 47s
2323:	learn: 0.0059604	total: 4m 1s	remaining: 13m 17s
2353:	learn: 0.0055294	total: 4m 1s	remaining: 13m 4s
2259:	learn: 0.0059421	total: 4m 1s	remaining: 13m 47s
2320:	learn: 0.0050112	total: 4m 1s	remaining: 13m 18s
2162:	learn: 0.0063432	total: 4m 1s	remaining: 14m 35s
2324:	learn: 0.0059575	total: 4m 1s	remaining: 13m 17s
2354:	learn: 0.0055259	total: 4m 1s	remaining: 13m 4s
2321:	learn: 0.0050063	total: 4m 1s	remaining: 13m 18s
2260:	learn: 0.0059379	total: 4m 1s	remaining: 13m 47s
2355:	learn: 0.0055228	total: 4m 1s	remaining: 13m 4s
2163:	learn: 0.0063389	total: 4m 1s	remaining: 14m 35s
2325:	learn: 0.0059540	total: 4m 1s	remaining: 13m 16s
2322:	learn: 0.0050030	total: 4m 1s	remaining: 13m 18s
2261:	learn: 0.0059339	total: 4m 1s	remaining: 13m 47s
2356:	learn: 0.0055186	total: 4m 1s	remaining: 13m 4s
2164:	learn: 0.0063337	total: 4m 1s	remaining: 14m 35s
2323:	learn: 0.0049991	total: 4m 1s	remaining: 13m 18s
2326:	learn: 0.0059492	total: 4m 1s	remaining: 13m 16s
2262:	learn: 0.0059276	total: 4m 1s	remaining: 13m 46s
2324:	learn: 0.0049958	total: 4m 1s	remaining: 13m 18s
2357:	learn: 0.0055171	total: 4m 1s	remaining: 13m 3s
2165:	learn: 0.0063275	total: 4m 1s	remaining: 14m 35s
2327:	learn: 0.0059459	total: 4m 1s	remaining: 13m 16s
2263:	learn: 0.0059236	total: 4m 1s	remaining: 13m 46s
2358:	learn: 0.0055117	total: 4m 1s	remaining: 13m 3s
2325:	learn: 0.0049924	total: 4m 1s	remaining: 13m 18s
2359:	learn: 0.0055084	total: 4m 2s	remaining: 13m 3s
2328:	learn: 0.0059429	total: 4m 1s	remaining: 13m 16s
2166:	learn: 0.0063234	total: 4m 2s	remaining: 14m 35s
2264:	learn: 0.0059197	total: 4m 2s	remaining: 13m 46s
2326:	learn: 0.0049870	total: 4m 2s	remaining: 13m 18s
2360:	learn: 0.0055061	total: 4m 2s	remaining: 13m 3s
2329:	learn: 0.0059397	total: 4m 2s	remaining: 13m 16s
2327:	learn: 0.0049823	total: 4m 2s	remaining: 13m 17s
2167:	learn: 0.0063197	total: 4m 2s	remaining: 14m 35s
2361:	learn: 0.0055017	total: 4m 2s	remaining: 13m 3s
2265:	learn: 0.0059171	total: 4m 2s	remaining: 13m 46s
2330:	learn: 0.0059372	total: 4m 2s	remaining: 13m 16s
2328:	learn: 0.0049796	total: 4m 2s	remaining: 13m 17s
2362:	learn: 0.0054982	total: 4m 2s	remaining: 13m 3s
2168:	learn: 0.0063139	total: 4m 2s	remaining: 14m 34s
2266:	learn: 0.0059135	total: 4m 2s	remaining: 13m 46s
2329:	learn: 0.0049762	total: 4m 2s	remaining: 13m 17s
2331:	learn: 0.0059336	total: 4m 2s	remaining: 13m 16s
2363:	learn: 0.0054958	total: 4m 2s	remaining: 13m 2s
2267:	learn: 0.0059087	total: 4m 2s	remaining: 13m 46s
2169:	learn: 0.0063090	total: 4m 2s	remaining: 14m 34s
2330:	learn: 0.0049730	total: 4m 2s	remaining: 13m 17s
2332:	learn: 0.0059300	total: 4m 2s	remaining: 13m 16s
2364:	learn: 0.0054927	total: 4m 2s	remaining: 13m 2s
2268:	learn: 0.0059058	total: 4m 2s	remaining: 13m 46s
2170:	learn: 0.0063048	total: 4m 2s	remaining: 14m 34s
2331:	learn: 0.0049694	total: 4m 2s	remaining: 13m 17s
2365:	learn: 0.0054894	total: 4m 2s	remaining: 13m 2s
2333:	learn: 0.0059276	total: 4m 2s	remaining: 13m 16s
2269:	learn: 0.0059022	total: 4m 2s	remaining: 13m 46s
2171:	learn: 0.0062999	total: 4m 2s	remaining: 14m 34s
2332:	learn: 0.0049647	total: 4m 2s	remaining: 13m 17s
2366:	learn: 0.0054869	total: 4m 2s	remaining: 13m 2s
2334:	learn: 0.0059234	total: 4m 2s	remaining: 13m 16s
2270:	learn: 0.0058989	total: 4m 2s	remaining: 13m 46s
2172:	learn: 0.0062976	total: 4m 2s	remaining: 14m 34s
2333:	learn: 0.0049624	total: 4m 2s	remaining: 13m 17s
2367:	learn: 0.0054821	total: 4m 2s	remaining: 13m 2s
2335:	learn: 0.0059183	total: 4m 2s	remaining: 13m 16s
2271:	learn: 0.0058952	total: 4m 2s	remaining: 13m 45s
2334:	learn: 0.0049577	total: 4m 2s	remaining: 13m 16s
2336:	learn: 0.0059132	total: 4m 2s	remaining: 13m 15s
2368:	learn: 0.0054797	total: 4m 2s	remaining: 13m 2s
2173:	learn: 0.0062914	total: 4m 2s	remaining: 14m 34s
2335:	learn: 0.0049538	total: 4m 2s	remaining: 13m 16s
2337:	learn: 0.0059109	total: 4m 2s	remaining: 13m 15s
2272:	learn: 0.0058919	total: 4m 2s	remaining: 13m 45s
2369:	learn: 0.0054768	total: 4m 2s	remaining: 13m 2s
2174:	learn: 0.0062892	total: 4m 3s	remaining: 14m 34s
2273:	learn: 0.0058882	total: 4m 3s	remaining: 13m 45s
2338:	learn: 0.0059080	total: 4m 2s	remaining: 13m 15s
2336:	learn: 0.0049502	total: 4m 2s	remaining: 13m 16s
2370:	learn: 0.0054719	total: 4m 3s	remaining: 13m 2s
2274:	learn: 0.0058851	total: 4m 3s	remaining: 13m 45s
2339:	learn: 0.0059044	total: 4m 3s	remaining: 13m 15s
2337:	learn: 0.0049465	total: 4m 3s	remaining: 13m 16s
2175:	learn: 0.0062839	total: 4m 3s	remaining: 14m 34s
2371:	learn: 0.0054680	total: 4m 3s	remaining: 13m 1s
2340:	learn: 0.0058980	total: 4m 3s	remaining: 13m 15s
2275:	learn: 0.0058821	total: 4m 3s	remaining: 13m 45s
2176:	learn: 0.0062801	total: 4m 3s	remaining: 14m 34s
2338:	learn: 0.0049427	total: 4m 3s	remaining: 13m 16s
2372:	learn: 0.0054665	total: 4m 3s	remaining: 13m 1s
2341:	learn: 0.0058951	total: 4m 3s	remaining: 13m 15s
2276:	learn: 0.0058788	total: 4m 3s	remaining: 13m 45s
2339:	learn: 0.0049378	total: 4m 3s	remaining: 13m 16s
2177:	learn: 0.0062755	total: 4m 3s	remaining: 14m 34s
2373:	learn: 0.0054644	total: 4m 3s	remaining: 13m 1s
2342:	learn: 0.0058908	total: 4m 3s	remaining: 13m 14s
2374:	learn: 0.0054611	total: 4m 3s	remaining: 13m 1s
2277:	learn: 0.0058744	total: 4m 3s	remaining: 13m 45s
2340:	learn: 0.0049352	total: 4m 3s	remaining: 13m 16s
2178:	learn: 0.0062689	total: 4m 3s	remaining: 14m 34s
2343:	learn: 0.0058874	total: 4m 3s	remaining: 13m 14s
2375:	learn: 0.0054584	total: 4m 3s	remaining: 13m 1s
2278:	learn: 0.0058706	total: 4m 3s	remaining: 13m 45s
2179:	learn: 0.0062652	total: 4m 3s	remaining: 14m 33s
2344:	learn: 0.0058841	total: 4m 3s	remaining: 13m 14s
2341:	learn: 0.0049326	total: 4m 3s	remaining: 13m 16s
2376:	learn: 0.0054546	total: 4m 3s	remaining: 13m 1s
2279:	learn: 0.0058675	total: 4m 3s	remaining: 13m 44s
2345:	learn: 0.0058805	total: 4m 3s	remaining: 13m 14s
2342:	learn: 0.0049296	total: 4m 3s	remaining: 13m 16s
2180:	learn: 0.0062606	total: 4m 3s	remaining: 14m 33s
2280:	learn: 0.0058631	total: 4m 3s	remaining: 13m 44s
2377:	learn: 0.0054498	total: 4m 3s	remaining: 13m 1s
2346:	learn: 0.0058769	total: 4m 3s	remaining: 13m 14s
2343:	learn: 0.0049273	total: 4m 3s	remaining: 13m 16s
2281:	learn: 0.0058596	total: 4m 3s	remaining: 13m 44s
2181:	learn: 0.0062557	total: 4m 3s	remaining: 14m 33s
2378:	learn: 0.0054463	total: 4m 3s	remaining: 13m 1s
2347:	learn: 0.0058744	total: 4m 3s	remaining: 13m 14s
2344:	learn: 0.0049240	total: 4m 3s	remaining: 13m 15s
2182:	learn: 0.0062514	total: 4m 3s	remaining: 14m 33s
2282:	learn: 0.0058548	total: 4m 3s	remaining: 13m 44s
2379:	learn: 0.0054440	total: 4m 3s	remaining: 13m
2348:	learn: 0.0058710	total: 4m 3s	remaining: 13m 14s
2345:	learn: 0.0049216	total: 4m 3s	remaining: 13m 15s
2183:	learn: 0.0062477	total: 4m 4s	remaining: 14m 33s
2283:	learn: 0.0058520	total: 4m 4s	remaining: 13m 44s
2346:	learn: 0.0049183	total: 4m 3s	remaining: 13m 15s
2380:	learn: 0.0054394	total: 4m 4s	remaining: 13m
2349:	learn: 0.0058687	total: 4m 3s	remaining: 13m 14s
2184:	learn: 0.0062429	total: 4m 4s	remaining: 14m 33s
2284:	learn: 0.0058497	total: 4m 4s	remaining: 13m 44s
2347:	learn: 0.0049150	total: 4m 4s	remaining: 13m 15s
2381:	learn: 0.0054373	total: 4m 4s	remaining: 13m
2350:	learn: 0.0058654	total: 4m 4s	remaining: 13m 13s
2185:	learn: 0.0062408	total: 4m 4s	remaining: 14m 32s
2382:	learn: 0.0054338	total: 4m 4s	remaining: 13m
2285:	learn: 0.0058464	total: 4m 4s	remaining: 13m 44s
2348:	learn: 0.0049115	total: 4m 4s	remaining: 13m 15s
2186:	learn: 0.0062339	total: 4m 4s	remaining: 14m 32s
2351:	learn: 0.0058601	total: 4m 4s	remaining: 13m 13s
2349:	learn: 0.0049083	total: 4m 4s	remaining: 13m 15s
2383:	learn: 0.0054320	total: 4m 4s	remaining: 13m
2187:	learn: 0.0062289	total: 4m 4s	remaining: 14m 32s
2286:	learn: 0.0058429	total: 4m 4s	remaining: 13m 44s
2352:	learn: 0.0058574	total: 4m 4s	remaining: 13m 13s
2350:	learn: 0.0049053	total: 4m 4s	remaining: 13m 14s
2384:	learn: 0.0054290	total: 4m 4s	remaining: 13m
2188:	learn: 0.0062233	total: 4m 4s	remaining: 14m 32s
2287:	learn: 0.0058390	total: 4m 4s	remaining: 13m 44s
2353:	learn: 0.0058551	total: 4m 4s	remaining: 13m 13s
2351:	learn: 0.0049017	total: 4m 4s	remaining: 13m 14s
2385:	learn: 0.0054250	total: 4m 4s	remaining: 13m
2189:	learn: 0.0062183	total: 4m 4s	remaining: 14m 32s
2352:	learn: 0.0048987	total: 4m 4s	remaining: 13m 14s
2288:	learn: 0.0058362	total: 4m 4s	remaining: 13m 44s
2354:	learn: 0.0058520	total: 4m 4s	remaining: 13m 13s
2386:	learn: 0.0054222	total: 4m 4s	remaining: 13m
2353:	learn: 0.0048950	total: 4m 4s	remaining: 13m 14s
2190:	learn: 0.0062158	total: 4m 4s	remaining: 14m 32s
2289:	learn: 0.0058306	total: 4m 4s	remaining: 13m 43s
2387:	learn: 0.0054173	total: 4m 4s	remaining: 13m
2354:	learn: 0.0048910	total: 4m 4s	remaining: 13m 14s
2355:	learn: 0.0058491	total: 4m 4s	remaining: 13m 13s
2290:	learn: 0.0058272	total: 4m 4s	remaining: 13m 43s
2191:	learn: 0.0062104	total: 4m 4s	remaining: 14m 32s
2388:	learn: 0.0054146	total: 4m 4s	remaining: 12m 59s
2356:	learn: 0.0058451	total: 4m 4s	remaining: 13m 13s
2355:	learn: 0.0048873	total: 4m 4s	remaining: 13m 14s
2192:	learn: 0.0062059	total: 4m 4s	remaining: 14m 31s
2291:	learn: 0.0058236	total: 4m 4s	remaining: 13m 43s
2356:	learn: 0.0048820	total: 4m 4s	remaining: 13m 13s
2357:	learn: 0.0058401	total: 4m 4s	remaining: 13m 13s
2389:	learn: 0.0054097	total: 4m 4s	remaining: 12m 59s
2193:	learn: 0.0062037	total: 4m 5s	remaining: 14m 31s
2292:	learn: 0.0058201	total: 4m 5s	remaining: 13m 43s
2357:	learn: 0.0048783	total: 4m 4s	remaining: 13m 13s
2358:	learn: 0.0058372	total: 4m 4s	remaining: 13m 13s
2390:	learn: 0.0054048	total: 4m 5s	remaining: 12m 59s
2194:	learn: 0.0061970	total: 4m 5s	remaining: 14m 31s
2293:	learn: 0.0058168	total: 4m 5s	remaining: 13m 43s
2359:	learn: 0.0058342	total: 4m 4s	remaining: 13m 13s
2358:	learn: 0.0048743	total: 4m 5s	remaining: 13m 13s
2391:	learn: 0.0054004	total: 4m 5s	remaining: 12m 59s
2195:	learn: 0.0061903	total: 4m 5s	remaining: 14m 31s
2294:	learn: 0.0058143	total: 4m 5s	remaining: 13m 43s
2359:	learn: 0.0048693	total: 4m 5s	remaining: 13m 13s
2392:	learn: 0.0053952	total: 4m 5s	remaining: 12m 59s
2360:	learn: 0.0058317	total: 4m 5s	remaining: 13m 13s
2196:	learn: 0.0061858	total: 4m 5s	remaining: 14m 31s
2295:	learn: 0.0058102	total: 4m 5s	remaining: 13m 43s
2360:	learn: 0.0048654	total: 4m 5s	remaining: 13m 13s
2361:	learn: 0.0058277	total: 4m 5s	remaining: 13m 12s
2393:	learn: 0.0053904	total: 4m 5s	remaining: 12m 59s
2197:	learn: 0.0061813	total: 4m 5s	remaining: 14m 31s

2296:	learn: 0.0058055	total: 4m 5s	remaining: 13m 42s
2361:	learn: 0.0048618	total: 4m 5s	remaining: 13m 13s
2362:	learn: 0.0058253	total: 4m 5s	remaining: 13m 12s
2394:	learn: 0.0053867	total: 4m 5s	remaining: 12m 59s
2198:	learn: 0.0061780	total: 4m 5s	remaining: 14m 30s
2297:	learn: 0.0058009	total: 4m 5s	remaining: 13m 42s
2362:	learn: 0.0048585	total: 4m 5s	remaining: 13m 13s
2395:	learn: 0.0053840	total: 4m 5s	remaining: 12m 59s
2363:	learn: 0.0058205	total: 4m 5s	remaining: 13m 12s
2199:	learn: 0.0061736	total: 4m 5s	remaining: 14m 30s
2298:	learn: 0.0057967	total: 4m 5s	remaining: 13m 42s
2363:	learn: 0.0048561	total: 4m 5s	remaining: 13m 13s
2396:	learn: 0.0053818	total: 4m 5s	remaining: 12m 59s
2364:	learn: 0.0058179	total: 4m 5s	remaining: 13m 12s
2200:	learn: 0.0061676	total: 4m 5s	remaining: 14m 30s
2299:	learn: 0.0057944	total: 4m 5s	remaining: 13m 42s
2364:	learn: 0.0048533	total: 4m 5s	remaining: 13m 13s
2397:	learn: 0.0053770	total: 4m 5s	remaining: 12m 58s
2365:	learn: 0.0058144	total: 4m 5s	remaining: 13m 12s
2300:	learn: 0.0057910	total: 4m 5s	remaining: 13m 42s
2201:	learn: 0.0061643	total: 4m 5s	remaining: 14m 30s
2365:	learn: 0.0048496	total: 4m 5s	remaining: 13m 12s
2398:	learn: 0.0053747	total: 4m 5s	remaining: 12m 58s
2366:	learn: 0.0058102	total: 4m 5s	remaining: 13m 12s
2301:	learn: 0.0057868	total: 4m 5s	remaining: 13m 42s
2202:	learn: 0.0061586	total: 4m 5s	remaining: 14m 30s
2366:	learn: 0.0048459	total: 4m 5s	remaining: 13m 12s
2367:	learn: 0.0058079	total: 4m 5s	remaining: 13m 12s
2399:	learn: 0.0053699	total: 4m 5s	remaining: 12m 58s
2302:	learn: 0.0057841	total: 4m 6s	remaining: 13m 42s
2368:	learn: 0.0058059	total: 4m 5s	remaining: 13m 12s
2203:	learn: 0.0061551	total: 4m 6s	remaining: 14m 30s
2367:	learn: 0.0048438	total: 4m 5s	remaining: 13m 12s
2400:	learn: 0.0053684	total: 4m 6s	remaining: 12m 58s
2369:	learn: 0.0058024	total: 4m 5s	remaining: 13m 11s
2204:	learn: 0.0061510	total: 4m 6s	remaining: 14m 30s
2303:	learn: 0.0057812	total: 4m 6s	remaining: 13m 42s
2368:	learn: 0.0048403	total: 4m 6s	remaining: 13m 12s
2401:	learn: 0.0053658	total: 4m 6s	remaining: 12m 58s
2370:	learn: 0.0057983	total: 4m 6s	remaining: 13m 11s
2304:	learn: 0.0057765	total: 4m 6s	remaining: 13m 41s
2369:	learn: 0.0048361	total: 4m 6s	remaining: 13m 12s
2205:	learn: 0.0061476	total: 4m 6s	remaining: 14m 30s
2402:	learn: 0.0053611	total: 4m 6s	remaining: 12m 58s
2371:	learn: 0.0057951	total: 4m 6s	remaining: 13m 11s
2305:	learn: 0.0057719	total: 4m 6s	remaining: 13m 41s
2370:	learn: 0.0048332	total: 4m 6s	remaining: 13m 12s
2206:	learn: 0.0061430	total: 4m 6s	remaining: 14m 30s
2372:	learn: 0.0057905	total: 4m 6s	remaining: 13m 11s
2403:	learn: 0.0053586	total: 4m 6s	remaining: 12m 58s
2306:	learn: 0.0057669	total: 4m 6s	remaining: 13m 41s
2371:	learn: 0.0048304	total: 4m 6s	remaining: 13m 12s
2373:	learn: 0.0057883	total: 4m 6s	remaining: 13m 11s
2207:	learn: 0.0061409	total: 4m 6s	remaining: 14m 29s
2404:	learn: 0.0053551	total: 4m 6s	remaining: 12m 58s
2372:	learn: 0.0048269	total: 4m 6s	remaining: 13m 12s
2405:	learn: 0.0053518	total: 4m 6s	remaining: 12m 58s
2307:	learn: 0.0057640	total: 4m 6s	remaining: 13m 41s
2374:	learn: 0.0057841	total: 4m 6s	remaining: 13m 11s
2208:	learn: 0.0061370	total: 4m 6s	remaining: 14m 29s
2308:	learn: 0.0057610	total: 4m 6s	remaining: 13m 41s
2406:	learn: 0.0053468	total: 4m 6s	remaining: 12m 58s
2373:	learn: 0.0048242	total: 4m 6s	remaining: 13m 12s
2209:	learn: 0.0061299	total: 4m 6s	remaining: 14m 29s
2375:	learn: 0.0057785	total: 4m 6s	remaining: 13m 11s
2309:	learn: 0.0057589	total: 4m 6s	remaining: 13m 41s
2374:	learn: 0.0048198	total: 4m 6s	remaining: 13m 11s
2407:	learn: 0.0053426	total: 4m 6s	remaining: 12m 58s
2376:	learn: 0.0057759	total: 4m 6s	remaining: 13m 10s
2310:	learn: 0.0057549	total: 4m 6s	remaining: 13m 41s
2210:	learn: 0.0061240	total: 4m 6s	remaining: 14m 29s
2375:	learn: 0.0048167	total: 4m 6s	remaining: 13m 11s
2408:	learn: 0.0053379	total: 4m 6s	remaining: 12m 57s
2377:	learn: 0.0057724	total: 4m 6s	remaining: 13m 10s
2211:	learn: 0.0061194	total: 4m 6s	remaining: 14m 29s
2311:	learn: 0.0057496	total: 4m 6s	remaining: 13m 41s
2376:	learn: 0.0048143	total: 4m 6s	remaining: 13m 11s
2378:	learn: 0.0057670	total: 4m 6s	remaining: 13m 10s
2409:	learn: 0.0053332	total: 4m 6s	remaining: 12m 57s
2212:	learn: 0.0061150	total: 4m 7s	remaining: 14m 29s
2312:	learn: 0.0057460	total: 4m 7s	remaining: 13m 40s
2377:	learn: 0.0048122	total: 4m 6s	remaining: 13m 11s
2379:	learn: 0.0057634	total: 4m 6s	remaining: 13m 10s
2213:	learn: 0.0061094	total: 4m 7s	remaining: 14m 29s
2410:	learn: 0.0053308	total: 4m 7s	remaining: 12m 57s
2378:	learn: 0.0048090	total: 4m 7s	remaining: 13m 11s
2313:	learn: 0.0057419	total: 4m 7s	remaining: 13m 40s
2380:	learn: 0.0057602	total: 4m 6s	remaining: 13m 10s
2411:	learn: 0.0053282	total: 4m 7s	remaining: 12m 57s
2379:	learn: 0.0048043	total: 4m 7s	remaining: 13m 11s
2314:	learn: 0.0057390	total: 4m 7s	remaining: 13m 40s
2214:	learn: 0.0061050	total: 4m 7s	remaining: 14m 29s
2381:	learn: 0.0057575	total: 4m 7s	remaining: 13m 10s
2412:	learn: 0.0053236	total: 4m 7s	remaining: 12m 57s
2380:	learn: 0.0048008	total: 4m 7s	remaining: 13m 11s
2382:	learn: 0.0057554	total: 4m 7s	remaining: 13m 10s
2315:	learn: 0.0057350	total: 4m 7s	remaining: 13m 40s
2413:	learn: 0.0053214	total: 4m 7s	remaining: 12m 57s
2215:	learn: 0.0060992	total: 4m 7s	remaining: 14m 29s
2381:	learn: 0.0047987	total: 4m 7s	remaining: 13m 11s
2383:	learn: 0.0057515	total: 4m 7s	remaining: 13m 9s
2316:	learn: 0.0057279	total: 4m 7s	remaining: 13m 40s
2414:	learn: 0.0053192	total: 4m 7s	remaining: 12m 57s
2384:	learn: 0.0057477	total: 4m 7s	remaining: 13m 9s
2216:	learn: 0.0060961	total: 4m 7s	remaining: 14m 29s
2382:	learn: 0.0047945	total: 4m 7s	remaining: 13m 10s
2415:	learn: 0.0053140	total: 4m 7s	remaining: 12m 57s
2317:	learn: 0.0057257	total: 4m 7s	remaining: 13m 40s
2385:	learn: 0.0057443	total: 4m 7s	remaining: 13m 9s
2383:	learn: 0.0047919	total: 4m 7s	remaining: 13m 10s
2217:	learn: 0.0060890	total: 4m 7s	remaining: 14m 29s
2416:	learn: 0.0053093	total: 4m 7s	remaining: 12m 56s
2318:	learn: 0.0057216	total: 4m 7s	remaining: 13m 40s
2386:	learn: 0.0057419	total: 4m 7s	remaining: 13m 9s
2384:	learn: 0.0047877	total: 4m 7s	remaining: 13m 10s
2319:	learn: 0.0057170	total: 4m 7s	remaining: 13m 40s
2417:	learn: 0.0053067	total: 4m 7s	remaining: 12m 56s
2387:	learn: 0.0057365	total: 4m 7s	remaining: 13m 9s
2218:	learn: 0.0060839	total: 4m 7s	remaining: 14m 28s
2385:	learn: 0.0047837	total: 4m 7s	remaining: 13m 10s
2320:	learn: 0.0057129	total: 4m 7s	remaining: 13m 39s
2386:	learn: 0.0047816	total: 4m 7s	remaining: 13m 10s
2418:	learn: 0.0053025	total: 4m 7s	remaining: 12m 56s
2219:	learn: 0.0060816	total: 4m 7s	remaining: 14m 28s
2388:	learn: 0.0057332	total: 4m 7s	remaining: 13m 9s
2321:	learn: 0.0057108	total: 4m 7s	remaining: 13m 39s
2419:	learn: 0.0053001	total: 4m 7s	remaining: 12m 56s
2387:	learn: 0.0047796	total: 4m 7s	remaining: 13m 10s
2389:	learn: 0.0057298	total: 4m 7s	remaining: 13m 9s
2220:	learn: 0.0060772	total: 4m 8s	remaining: 14m 28s
2322:	learn: 0.0057083	total: 4m 8s	remaining: 13m 39s
2420:	learn: 0.0052965	total: 4m 8s	remaining: 12m 56s
2388:	learn: 0.0047765	total: 4m 7s	remaining: 13m 10s
2390:	learn: 0.0057276	total: 4m 7s	remaining: 13m 9s
2421:	learn: 0.0052932	total: 4m 8s	remaining: 12m 56s
2323:	learn: 0.0057062	total: 4m 8s	remaining: 13m 39s
2391:	learn: 0.0057242	total: 4m 8s	remaining: 13m 8s
2221:	learn: 0.0060729	total: 4m 8s	remaining: 14m 28s
2389:	learn: 0.0047736	total: 4m 8s	remaining: 13m 9s
2422:	learn: 0.0052907	total: 4m 8s	remaining: 12m 56s
2222:	learn: 0.0060672	total: 4m 8s	remaining: 14m 28s
2324:	learn: 0.0057030	total: 4m 8s	remaining: 13m 39s
2392:	learn: 0.0057206	total: 4m 8s	remaining: 13m 8s
2390:	learn: 0.0047689	total: 4m 8s	remaining: 13m 9s
2223:	learn: 0.0060613	total: 4m 8s	remaining: 14m 28s
2423:	learn: 0.0052875	total: 4m 8s	remaining: 12m 56s
2393:	learn: 0.0057172	total: 4m 8s	remaining: 13m 8s
2325:	learn: 0.0057004	total: 4m 8s	remaining: 13m 39s
2391:	learn: 0.0047660	total: 4m 8s	remaining: 13m 9s
2424:	learn: 0.0052839	total: 4m 8s	remaining: 12m 55s
2394:	learn: 0.0057147	total: 4m 8s	remaining: 13m 8s
2224:	learn: 0.0060567	total: 4m 8s	remaining: 14m 28s
2392:	learn: 0.0047633	total: 4m 8s	remaining: 13m 9s
2326:	learn: 0.0056960	total: 4m 8s	remaining: 13m 39s
2425:	learn: 0.0052783	total: 4m 8s	remaining: 12m 55s
2225:	learn: 0.0060519	total: 4m 8s	remaining: 14m 28s
2395:	learn: 0.0057123	total: 4m 8s	remaining: 13m 8s
2393:	learn: 0.0047603	total: 4m 8s	remaining: 13m 9s
2426:	learn: 0.0052759	total: 4m 8s	remaining: 12m 55s
2327:	learn: 0.0056916	total: 4m 8s	remaining: 13m 39s
2427:	learn: 0.0052713	total: 4m 8s	remaining: 12m 55s
2226:	learn: 0.0060484	total: 4m 8s	remaining: 14m 27s
2396:	learn: 0.0057096	total: 4m 8s	remaining: 13m 8s
2394:	learn: 0.0047570	total: 4m 8s	remaining: 13m 9s
2428:	learn: 0.0052689	total: 4m 8s	remaining: 12m 55s
2328:	learn: 0.0056876	total: 4m 8s	remaining: 13m 39s
2397:	learn: 0.0057072	total: 4m 8s	remaining: 13m 8s
2227:	learn: 0.0060428	total: 4m 8s	remaining: 14m 27s
2395:	learn: 0.0047536	total: 4m 8s	remaining: 13m 9s
2429:	learn: 0.0052638	total: 4m 8s	remaining: 12m 55s
2329:	learn: 0.0056835	total: 4m 8s	remaining: 13m 39s
2398:	learn: 0.0057045	total: 4m 8s	remaining: 13m 8s
2228:	learn: 0.0060380	total: 4m 8s	remaining: 14m 27s
2396:	learn: 0.0047508	total: 4m 8s	remaining: 13m 9s
2430:	learn: 0.0052591	total: 4m 8s	remaining: 12m 54s
2399:	learn: 0.0057006	total: 4m 8s	remaining: 13m 7s
2330:	learn: 0.0056784	total: 4m 8s	remaining: 13m 39s
2229:	learn: 0.0060333	total: 4m 8s	remaining: 14m 27s
2397:	learn: 0.0047473	total: 4m 8s	remaining: 13m 9s
2431:	learn: 0.0052546	total: 4m 8s	remaining: 12m 54s
2400:	learn: 0.0056979	total: 4m 8s	remaining: 13m 7s
2432:	learn: 0.0052513	total: 4m 9s	remaining: 12m 54s
2331:	learn: 0.0056746	total: 4m 9s	remaining: 13m 38s
2230:	learn: 0.0060287	total: 4m 9s	remaining: 14m 27s
2398:	learn: 0.0047445	total: 4m 9s	remaining: 13m 9s
2401:	learn: 0.0056950	total: 4m 8s	remaining: 13m 7s
2433:	learn: 0.0052472	total: 4m 9s	remaining: 12m 54s
2402:	learn: 0.0056894	total: 4m 9s	remaining: 13m 7s
2332:	learn: 0.0056708	total: 4m 9s	remaining: 13m 38s
2231:	learn: 0.0060232	total: 4m 9s	remaining: 14m 27s
2399:	learn: 0.0047406	total: 4m 9s	remaining: 13m 8s
2434:	learn: 0.0052418	total: 4m 9s	remaining: 12m 54s
2403:	learn: 0.0056847	total: 4m 9s	remaining: 13m 7s
2232:	learn: 0.0060181	total: 4m 9s	remaining: 14m 27s
2333:	learn: 0.0056652	total: 4m 9s	remaining: 13m 38s
2400:	learn: 0.0047370	total: 4m 9s	remaining: 13m 8s
2435:	learn: 0.0052369	total: 4m 9s	remaining: 12m 54s
2233:	learn: 0.0060133	total: 4m 9s	remaining: 14m 26s
2404:	learn: 0.0056810	total: 4m 9s	remaining: 13m 7s
2334:	learn: 0.0056621	total: 4m 9s	remaining: 13m 38s
2401:	learn: 0.0047346	total: 4m 9s	remaining: 13m 8s
2436:	learn: 0.0052323	total: 4m 9s	remaining: 12m 54s
2405:	learn: 0.0056776	total: 4m 9s	remaining: 13m 6s
2234:	learn: 0.0060102	total: 4m 9s	remaining: 14m 26s
2335:	learn: 0.0056587	total: 4m 9s	remaining: 13m 38s
2402:	learn: 0.0047305	total: 4m 9s	remaining: 13m 8s
2437:	learn: 0.0052293	total: 4m 9s	remaining: 12m 53s
2406:	learn: 0.0056723	total: 4m 9s	remaining: 13m 6s
2235:	learn: 0.0060071	total: 4m 9s	remaining: 14m 26s
2336:	learn: 0.0056549	total: 4m 9s	remaining: 13m 38s
2403:	learn: 0.0047272	total: 4m 9s	remaining: 13m 8s
2438:	learn: 0.0052280	total: 4m 9s	remaining: 12m 53s
2407:	learn: 0.0056704	total: 4m 9s	remaining: 13m 6s
2236:	learn: 0.0060027	total: 4m 9s	remaining: 14m 26s
2337:	learn: 0.0056510	total: 4m 9s	remaining: 13m 38s
2408:	learn: 0.0056672	total: 4m 9s	remaining: 13m 6s
2404:	learn: 0.0047234	total: 4m 9s	remaining: 13m 8s
2439:	learn: 0.0052238	total: 4m 9s	remaining: 12m 53s
2237:	learn: 0.0059989	total: 4m 9s	remaining: 14m 26s
2338:	learn: 0.0056476	total: 4m 9s	remaining: 13m 38s
2409:	learn: 0.0056643	total: 4m 9s	remaining: 13m 6s
2440:	learn: 0.0052196	total: 4m 9s	remaining: 12m 53s
2405:	learn: 0.0047186	total: 4m 9s	remaining: 13m 8s
2238:	learn: 0.0059943	total: 4m 9s	remaining: 14m 26s
2339:	learn: 0.0056443	total: 4m 9s	remaining: 13m 38s
2441:	learn: 0.0052174	total: 4m 9s	remaining: 12m 53s
2410:	learn: 0.0056610	total: 4m 9s	remaining: 13m 6s
2406:	learn: 0.0047151	total: 4m 9s	remaining: 13m 8s
2442:	learn: 0.0052134	total: 4m 9s	remaining: 12m 53s
2239:	learn: 0.0059883	total: 4m 10s	remaining: 14m 26s
2340:	learn: 0.0056410	total: 4m 10s	remaining: 13m 38s
2411:	learn: 0.0056586	total: 4m 9s	remaining: 13m 6s
2407:	learn: 0.0047110	total: 4m 10s	remaining: 13m 8s
2443:	learn: 0.0052096	total: 4m 10s	remaining: 12m 53s
2240:	learn: 0.0059830	total: 4m 10s	remaining: 14m 26s
2412:	learn: 0.0056556	total: 4m 10s	remaining: 13m 6s
2341:	learn: 0.0056346	total: 4m 10s	remaining: 13m 38s
2444:	learn: 0.0052060	total: 4m 10s	remaining: 12m 52s
2408:	learn: 0.0047087	total: 4m 10s	remaining: 13m 8s
2241:	learn: 0.0059810	total: 4m 10s	remaining: 14m 25s
2413:	learn: 0.0056526	total: 4m 10s	remaining: 13m 5s
2342:	learn: 0.0056312	total: 4m 10s	remaining: 13m 37s
2409:	learn: 0.0047052	total: 4m 10s	remaining: 13m 7s
2445:	learn: 0.0052023	total: 4m 10s	remaining: 12m 52s
2242:	learn: 0.0059749	total: 4m 10s	remaining: 14m 25s
2414:	learn: 0.0056474	total: 4m 10s	remaining: 13m 5s
2410:	learn: 0.0047026	total: 4m 10s	remaining: 13m 7s
2446:	learn: 0.0051976	total: 4m 10s	remaining: 12m 52s
2343:	learn: 0.0056279	total: 4m 10s	remaining: 13m 37s
2243:	learn: 0.0059704	total: 4m 10s	remaining: 14m 25s
2415:	learn: 0.0056449	total: 4m 10s	remaining: 13m 5s
2411:	learn: 0.0046998	total: 4m 10s	remaining: 13m 7s
2447:	learn: 0.0051963	total: 4m 10s	remaining: 12m 52s
2244:	learn: 0.0059652	total: 4m 10s	remaining: 14m 25s
2344:	learn: 0.0056249	total: 4m 10s	remaining: 13m 37s
2412:	learn: 0.0046964	total: 4m 10s	remaining: 13m 7s
2448:	learn: 0.0051940	total: 4m 10s	remaining: 12m 52s
2416:	learn: 0.0056413	total: 4m 10s	remaining: 13m 5s
2245:	learn: 0.0059596	total: 4m 10s	remaining: 14m 25s
2345:	learn: 0.0056181	total: 4m 10s	remaining: 13m 37s
2413:	learn: 0.0046925	total: 4m 10s	remaining: 13m 7s
2449:	learn: 0.0051898	total: 4m 10s	remaining: 12m 52s
2417:	learn: 0.0056391	total: 4m 10s	remaining: 13m 5s
2246:	learn: 0.0059560	total: 4m 10s	remaining: 14m 25s
2414:	learn: 0.0046881	total: 4m 10s	remaining: 13m 7s
2346:	learn: 0.0056149	total: 4m 10s	remaining: 13m 37s
2450:	learn: 0.0051859	total: 4m 10s	remaining: 12m 52s
2418:	learn: 0.0056358	total: 4m 10s	remaining: 13m 5s
2451:	learn: 0.0051813	total: 4m 10s	remaining: 12m 52s
2415:	learn: 0.0046839	total: 4m 10s	remaining: 13m 7s
2247:	learn: 0.0059515	total: 4m 10s	remaining: 14m 25s
2347:	learn: 0.0056098	total: 4m 10s	remaining: 13m 37s
2419:	learn: 0.0056335	total: 4m 10s	remaining: 13m 5s
2452:	learn: 0.0051775	total: 4m 10s	remaining: 12m 51s
2416:	learn: 0.0046794	total: 4m 10s	remaining: 13m 7s
2348:	learn: 0.0056054	total: 4m 10s	remaining: 13m 37s
2248:	learn: 0.0059465	total: 4m 10s	remaining: 14m 25s
2420:	learn: 0.0056298	total: 4m 10s	remaining: 13m 5s
2453:	learn: 0.0051747	total: 4m 10s	remaining: 12m 51s
2349:	learn: 0.0056025	total: 4m 11s	remaining: 13m 37s
2417:	learn: 0.0046764	total: 4m 10s	remaining: 13m 6s
2249:	learn: 0.0059421	total: 4m 11s	remaining: 14m 24s
2454:	learn: 0.0051712	total: 4m 11s	remaining: 12m 51s
2421:	learn: 0.0056267	total: 4m 10s	remaining: 13m 5s
2350:	learn: 0.0055996	total: 4m 11s	remaining: 13m 37s
2250:	learn: 0.0059365	total: 4m 11s	remaining: 14m 24s
2422:	learn: 0.0056244	total: 4m 11s	remaining: 13m 5s
2455:	learn: 0.0051678	total: 4m 11s	remaining: 12m 51s
2418:	learn: 0.0046724	total: 4m 11s	remaining: 13m 6s
2351:	learn: 0.0055970	total: 4m 11s	remaining: 13m 36s
2423:	learn: 0.0056218	total: 4m 11s	remaining: 13m 4s
2251:	learn: 0.0059314	total: 4m 11s	remaining: 14m 24s
2456:	learn: 0.0051638	total: 4m 11s	remaining: 12m 51s
2419:	learn: 0.0046685	total: 4m 11s	remaining: 13m 6s
2352:	learn: 0.0055939	total: 4m 11s	remaining: 13m 36s
2424:	learn: 0.0056194	total: 4m 11s	remaining: 13m 4s
2252:	learn: 0.0059252	total: 4m 11s	remaining: 14m 24s

2457:	learn: 0.0051600	total: 4m 11s	remaining: 12m 51s
2420:	learn: 0.0046640	total: 4m 11s	remaining: 13m 6s
2353:	learn: 0.0055884	total: 4m 11s	remaining: 13m 36s
2425:	learn: 0.0056146	total: 4m 11s	remaining: 13m 4s
2458:	learn: 0.0051577	total: 4m 11s	remaining: 12m 51s
2253:	learn: 0.0059199	total: 4m 11s	remaining: 14m 24s
2421:	learn: 0.0046602	total: 4m 11s	remaining: 13m 6s
2426:	learn: 0.0056113	total: 4m 11s	remaining: 13m 4s
2354:	learn: 0.0055844	total: 4m 11s	remaining: 13m 36s
2254:	learn: 0.0059144	total: 4m 11s	remaining: 14m 24s
2459:	learn: 0.0051538	total: 4m 11s	remaining: 12m 51s
2422:	learn: 0.0046571	total: 4m 11s	remaining: 13m 6s
2427:	learn: 0.0056075	total: 4m 11s	remaining: 13m 4s
2355:	learn: 0.0055788	total: 4m 11s	remaining: 13m 36s
2460:	learn: 0.0051508	total: 4m 11s	remaining: 12m 50s
2255:	learn: 0.0059092	total: 4m 11s	remaining: 14m 24s
2428:	learn: 0.0056053	total: 4m 11s	remaining: 13m 4s
2356:	learn: 0.0055757	total: 4m 11s	remaining: 13m 36s
2423:	learn: 0.0046545	total: 4m 11s	remaining: 13m 6s
2461:	learn: 0.0051472	total: 4m 11s	remaining: 12m 50s
2429:	learn: 0.0056026	total: 4m 11s	remaining: 13m 4s
2256:	learn: 0.0059047	total: 4m 11s	remaining: 14m 24s
2424:	learn: 0.0046515	total: 4m 11s	remaining: 13m 6s
2462:	learn: 0.0051454	total: 4m 11s	remaining: 12m 50s
2357:	learn: 0.0055721	total: 4m 11s	remaining: 13m 36s
2430:	learn: 0.0055984	total: 4m 11s	remaining: 13m 3s
2257:	learn: 0.0058987	total: 4m 11s	remaining: 14m 23s
2463:	learn: 0.0051420	total: 4m 11s	remaining: 12m 50s
2358:	learn: 0.0055683	total: 4m 11s	remaining: 13m 36s
2425:	learn: 0.0046482	total: 4m 11s	remaining: 13m 6s
2431:	learn: 0.0055945	total: 4m 11s	remaining: 13m 3s
2464:	learn: 0.0051390	total: 4m 11s	remaining: 12m 50s
2258:	learn: 0.0058935	total: 4m 12s	remaining: 14m 23s
2426:	learn: 0.0046455	total: 4m 11s	remaining: 13m 6s
2359:	learn: 0.0055614	total: 4m 12s	remaining: 13m 36s
2432:	learn: 0.0055905	total: 4m 11s	remaining: 13m 3s
2465:	learn: 0.0051351	total: 4m 12s	remaining: 12m 50s
2433:	learn: 0.0055866	total: 4m 12s	remaining: 13m 3s
2360:	learn: 0.0055586	total: 4m 12s	remaining: 13m 35s
2259:	learn: 0.0058878	total: 4m 12s	remaining: 14m 23s
2427:	learn: 0.0046416	total: 4m 12s	remaining: 13m 6s
2466:	learn: 0.0051332	total: 4m 12s	remaining: 12m 50s
2434:	learn: 0.0055821	total: 4m 12s	remaining: 13m 3s
2361:	learn: 0.0055539	total: 4m 12s	remaining: 13m 35s
2428:	learn: 0.0046388	total: 4m 12s	remaining: 13m 6s
2467:	learn: 0.0051308	total: 4m 12s	remaining: 12m 49s
2260:	learn: 0.0058820	total: 4m 12s	remaining: 14m 23s
2435:	learn: 0.0055782	total: 4m 12s	remaining: 13m 3s
2362:	learn: 0.0055516	total: 4m 12s	remaining: 13m 35s
2468:	learn: 0.0051267	total: 4m 12s	remaining: 12m 49s
2429:	learn: 0.0046368	total: 4m 12s	remaining: 13m 6s
2261:	learn: 0.0058787	total: 4m 12s	remaining: 14m 23s
2436:	learn: 0.0055734	total: 4m 12s	remaining: 13m 2s
2363:	learn: 0.0055491	total: 4m 12s	remaining: 13m 35s
2430:	learn: 0.0046337	total: 4m 12s	remaining: 13m 5s
2469:	learn: 0.0051221	total: 4m 12s	remaining: 12m 49s
2437:	learn: 0.0055694	total: 4m 12s	remaining: 13m 2s
2262:	learn: 0.0058735	total: 4m 12s	remaining: 14m 23s
2470:	learn: 0.0051183	total: 4m 12s	remaining: 12m 49s
2438:	learn: 0.0055665	total: 4m 12s	remaining: 13m 2s
2431:	learn: 0.0046311	total: 4m 12s	remaining: 13m 5s
2364:	learn: 0.0055457	total: 4m 12s	remaining: 13m 35s
2263:	learn: 0.0058707	total: 4m 12s	remaining: 14m 23s
2439:	learn: 0.0055617	total: 4m 12s	remaining: 13m 2s
2432:	learn: 0.0046292	total: 4m 12s	remaining: 13m 5s
2471:	learn: 0.0051160	total: 4m 12s	remaining: 12m 49s
2365:	learn: 0.0055418	total: 4m 12s	remaining: 13m 35s
2440:	learn: 0.0055588	total: 4m 12s	remaining: 13m 2s
2264:	learn: 0.0058646	total: 4m 12s	remaining: 14m 23s
2433:	learn: 0.0046255	total: 4m 12s	remaining: 13m 5s
2472:	learn: 0.0051128	total: 4m 12s	remaining: 12m 49s
2441:	learn: 0.0055565	total: 4m 12s	remaining: 13m 2s
2366:	learn: 0.0055364	total: 4m 12s	remaining: 13m 35s
2434:	learn: 0.0046232	total: 4m 12s	remaining: 13m 5s
2265:	learn: 0.0058586	total: 4m 12s	remaining: 14m 23s
2473:	learn: 0.0051091	total: 4m 12s	remaining: 12m 49s
2442:	learn: 0.0055518	total: 4m 12s	remaining: 13m 1s
2367:	learn: 0.0055336	total: 4m 12s	remaining: 13m 35s
2435:	learn: 0.0046201	total: 4m 12s	remaining: 13m 5s
2474:	learn: 0.0051044	total: 4m 12s	remaining: 12m 49s
2266:	learn: 0.0058545	total: 4m 13s	remaining: 14m 23s
2443:	learn: 0.0055497	total: 4m 12s	remaining: 13m 1s
2368:	learn: 0.0055310	total: 4m 13s	remaining: 13m 35s
2436:	learn: 0.0046160	total: 4m 12s	remaining: 13m 5s
2475:	learn: 0.0051021	total: 4m 13s	remaining: 12m 48s
2444:	learn: 0.0055458	total: 4m 12s	remaining: 13m 1s
2437:	learn: 0.0046127	total: 4m 13s	remaining: 13m 4s
2267:	learn: 0.0058494	total: 4m 13s	remaining: 14m 23s
2369:	learn: 0.0055266	total: 4m 13s	remaining: 13m 35s
2476:	learn: 0.0050981	total: 4m 13s	remaining: 12m 48s
2445:	learn: 0.0055421	total: 4m 13s	remaining: 13m 1s
2438:	learn: 0.0046098	total: 4m 13s	remaining: 13m 4s
2268:	learn: 0.0058449	total: 4m 13s	remaining: 14m 23s
2370:	learn: 0.0055243	total: 4m 13s	remaining: 13m 34s
2477:	learn: 0.0050955	total: 4m 13s	remaining: 12m 48s
2439:	learn: 0.0046069	total: 4m 13s	remaining: 13m 4s
2446:	learn: 0.0055395	total: 4m 13s	remaining: 13m 1s
2371:	learn: 0.0055226	total: 4m 13s	remaining: 13m 34s
2269:	learn: 0.0058407	total: 4m 13s	remaining: 14m 22s
2478:	learn: 0.0050923	total: 4m 13s	remaining: 12m 48s
2440:	learn: 0.0046036	total: 4m 13s	remaining: 13m 4s
2447:	learn: 0.0055364	total: 4m 13s	remaining: 13m 1s
2372:	learn: 0.0055202	total: 4m 13s	remaining: 13m 34s
2479:	learn: 0.0050885	total: 4m 13s	remaining: 12m 48s
2270:	learn: 0.0058368	total: 4m 13s	remaining: 14m 22s
2441:	learn: 0.0046003	total: 4m 13s	remaining: 13m 4s
2448:	learn: 0.0055332	total: 4m 13s	remaining: 13m 1s
2373:	learn: 0.0055175	total: 4m 13s	remaining: 13m 34s
2480:	learn: 0.0050839	total: 4m 13s	remaining: 12m 48s
2442:	learn: 0.0045956	total: 4m 13s	remaining: 13m 4s
2271:	learn: 0.0058333	total: 4m 13s	remaining: 14m 22s
2449:	learn: 0.0055285	total: 4m 13s	remaining: 13m 1s
2374:	learn: 0.0055142	total: 4m 13s	remaining: 13m 34s
2481:	learn: 0.0050809	total: 4m 13s	remaining: 12m 48s
2450:	learn: 0.0055235	total: 4m 13s	remaining: 13m
2443:	learn: 0.0045922	total: 4m 13s	remaining: 13m 4s
2482:	learn: 0.0050787	total: 4m 13s	remaining: 12m 48s
2272:	learn: 0.0058302	total: 4m 13s	remaining: 14m 22s
2375:	learn: 0.0055086	total: 4m 13s	remaining: 13m 34s
2444:	learn: 0.0045890	total: 4m 13s	remaining: 13m 4s
2451:	learn: 0.0055189	total: 4m 13s	remaining: 13m
2273:	learn: 0.0058266	total: 4m 13s	remaining: 14m 22s
2483:	learn: 0.0050752	total: 4m 13s	remaining: 12m 48s
2376:	learn: 0.0055060	total: 4m 13s	remaining: 13m 34s
2452:	learn: 0.0055159	total: 4m 13s	remaining: 13m
2445:	learn: 0.0045863	total: 4m 13s	remaining: 13m 3s
2274:	learn: 0.0058216	total: 4m 13s	remaining: 14m 22s
2484:	learn: 0.0050710	total: 4m 13s	remaining: 12m 47s
2446:	learn: 0.0045847	total: 4m 13s	remaining: 13m 3s
2377:	learn: 0.0055028	total: 4m 14s	remaining: 13m 34s
2453:	learn: 0.0055139	total: 4m 13s	remaining: 13m
2485:	learn: 0.0050691	total: 4m 14s	remaining: 12m 47s
2275:	learn: 0.0058178	total: 4m 14s	remaining: 14m 22s
2447:	learn: 0.0045820	total: 4m 13s	remaining: 13m 3s
2378:	learn: 0.0054991	total: 4m 14s	remaining: 13m 34s
2276:	learn: 0.0058137	total: 4m 14s	remaining: 14m 21s
2454:	learn: 0.0055111	total: 4m 13s	remaining: 13m
2486:	learn: 0.0050649	total: 4m 14s	remaining: 12m 47s
2448:	learn: 0.0045791	total: 4m 14s	remaining: 13m 3s
2277:	learn: 0.0058102	total: 4m 14s	remaining: 14m 21s
2379:	learn: 0.0054964	total: 4m 14s	remaining: 13m 33s
2455:	learn: 0.0055091	total: 4m 14s	remaining: 13m
2487:	learn: 0.0050610	total: 4m 14s	remaining: 12m 47s
2449:	learn: 0.0045751	total: 4m 14s	remaining: 13m 3s
2380:	learn: 0.0054925	total: 4m 14s	remaining: 13m 33s
2278:	learn: 0.0058065	total: 4m 14s	remaining: 14m 21s
2456:	learn: 0.0055055	total: 4m 14s	remaining: 13m
2488:	learn: 0.0050568	total: 4m 14s	remaining: 12m 47s
2381:	learn: 0.0054899	total: 4m 14s	remaining: 13m 33s
2450:	learn: 0.0045712	total: 4m 14s	remaining: 13m 3s
2279:	learn: 0.0058028	total: 4m 14s	remaining: 14m 21s
2457:	learn: 0.0055003	total: 4m 14s	remaining: 13m
2489:	learn: 0.0050532	total: 4m 14s	remaining: 12m 47s
2382:	learn: 0.0054859	total: 4m 14s	remaining: 13m 33s
2451:	learn: 0.0045683	total: 4m 14s	remaining: 13m 3s
2280:	learn: 0.0057994	total: 4m 14s	remaining: 14m 21s
2458:	learn: 0.0054973	total: 4m 14s	remaining: 13m
2490:	learn: 0.0050489	total: 4m 14s	remaining: 12m 47s
2452:	learn: 0.0045652	total: 4m 14s	remaining: 13m 3s
2383:	learn: 0.0054832	total: 4m 14s	remaining: 13m 33s
2459:	learn: 0.0054953	total: 4m 14s	remaining: 12m 59s
2281:	learn: 0.0057962	total: 4m 14s	remaining: 14m 21s
2491:	learn: 0.0050446	total: 4m 14s	remaining: 12m 47s
2453:	learn: 0.0045605	total: 4m 14s	remaining: 13m 2s
2384:	learn: 0.0054803	total: 4m 14s	remaining: 13m 33s
2492:	learn: 0.0050420	total: 4m 14s	remaining: 12m 46s
2282:	learn: 0.0057925	total: 4m 14s	remaining: 14m 21s
2460:	learn: 0.0054908	total: 4m 14s	remaining: 12m 59s
2454:	learn: 0.0045566	total: 4m 14s	remaining: 13m 2s
2385:	learn: 0.0054781	total: 4m 14s	remaining: 13m 33s
2493:	learn: 0.0050378	total: 4m 14s	remaining: 12m 46s
2283:	learn: 0.0057862	total: 4m 14s	remaining: 14m 21s
2461:	learn: 0.0054883	total: 4m 14s	remaining: 12m 59s
2455:	learn: 0.0045547	total: 4m 14s	remaining: 13m 2s
2386:	learn: 0.0054754	total: 4m 14s	remaining: 13m 32s
2494:	learn: 0.0050347	total: 4m 14s	remaining: 12m 46s
2462:	learn: 0.0054853	total: 4m 14s	remaining: 12m 59s
2284:	learn: 0.0057827	total: 4m 14s	remaining: 14m 20s
2387:	learn: 0.0054718	total: 4m 14s	remaining: 13m 32s
2456:	learn: 0.0045507	total: 4m 14s	remaining: 13m 2s
2495:	learn: 0.0050307	total: 4m 14s	remaining: 12m 46s
2463:	learn: 0.0054831	total: 4m 14s	remaining: 12m 59s
2388:	learn: 0.0054683	total: 4m 15s	remaining: 13m 32s
2285:	learn: 0.0057781	total: 4m 15s	remaining: 14m 20s
2496:	learn: 0.0050265	total: 4m 15s	remaining: 12m 46s
2457:	learn: 0.0045474	total: 4m 15s	remaining: 13m 2s
2389:	learn: 0.0054635	total: 4m 15s	remaining: 13m 32s
2464:	learn: 0.0054803	total: 4m 15s	remaining: 12m 59s
2286:	learn: 0.0057750	total: 4m 15s	remaining: 14m 20s
2497:	learn: 0.0050230	total: 4m 15s	remaining: 12m 46s
2458:	learn: 0.0045444	total: 4m 15s	remaining: 13m 2s
2287:	learn: 0.0057721	total: 4m 15s	remaining: 14m 20s
2390:	learn: 0.0054610	total: 4m 15s	remaining: 13m 32s
2465:	learn: 0.0054784	total: 4m 15s	remaining: 12m 59s
2498:	learn: 0.0050180	total: 4m 15s	remaining: 12m 46s
2459:	learn: 0.0045414	total: 4m 15s	remaining: 13m 2s
2288:	learn: 0.0057672	total: 4m 15s	remaining: 14m 20s
2391:	learn: 0.0054590	total: 4m 15s	remaining: 13m 32s
2466:	learn: 0.0054764	total: 4m 15s	remaining: 12m 59s
2499:	learn: 0.0050139	total: 4m 15s	remaining: 12m 46s
2460:	learn: 0.0045384	total: 4m 15s	remaining: 13m 2s
2289:	learn: 0.0057635	total: 4m 15s	remaining: 14m 20s
2467:	learn: 0.0054719	total: 4m 15s	remaining: 12m 59s
2392:	learn: 0.0054564	total: 4m 15s	remaining: 13m 32s
2461:	learn: 0.0045352	total: 4m 15s	remaining: 13m 2s
2500:	learn: 0.0050105	total: 4m 15s	remaining: 12m 46s
2290:	learn: 0.0057608	total: 4m 15s	remaining: 14m 20s
2393:	learn: 0.0054500	total: 4m 15s	remaining: 13m 31s
2468:	learn: 0.0054690	total: 4m 15s	remaining: 12m 59s
2501:	learn: 0.0050074	total: 4m 15s	remaining: 12m 45s
2462:	learn: 0.0045326	total: 4m 15s	remaining: 13m 2s
2394:	learn: 0.0054465	total: 4m 15s	remaining: 13m 31s
2469:	learn: 0.0054654	total: 4m 15s	remaining: 12m 58s
2502:	learn: 0.0050046	total: 4m 15s	remaining: 12m 45s
2291:	learn: 0.0057568	total: 4m 15s	remaining: 14m 19s
2463:	learn: 0.0045301	total: 4m 15s	remaining: 13m 1s
2470:	learn: 0.0054618	total: 4m 15s	remaining: 12m 58s
2503:	learn: 0.0050016	total: 4m 15s	remaining: 12m 45s
2395:	learn: 0.0054426	total: 4m 15s	remaining: 13m 31s
2464:	learn: 0.0045276	total: 4m 15s	remaining: 13m 1s
2292:	learn: 0.0057517	total: 4m 15s	remaining: 14m 19s
2471:	learn: 0.0054594	total: 4m 15s	remaining: 12m 58s
2465:	learn: 0.0045251	total: 4m 15s	remaining: 13m 1s
2504:	learn: 0.0049976	total: 4m 15s	remaining: 12m 45s
2396:	learn: 0.0054396	total: 4m 15s	remaining: 13m 31s
2293:	learn: 0.0057486	total: 4m 15s	remaining: 14m 19s
2472:	learn: 0.0054562	total: 4m 15s	remaining: 12m 58s
2505:	learn: 0.0049945	total: 4m 15s	remaining: 12m 45s
2397:	learn: 0.0054362	total: 4m 15s	remaining: 13m 31s
2466:	learn: 0.0045226	total: 4m 15s	remaining: 13m 1s
2294:	learn: 0.0057453	total: 4m 16s	remaining: 14m 19s
2473:	learn: 0.0054512	total: 4m 15s	remaining: 12m 58s
2506:	learn: 0.0049923	total: 4m 16s	remaining: 12m 45s
2398:	learn: 0.0054333	total: 4m 16s	remaining: 13m 31s
2467:	learn: 0.0045195	total: 4m 16s	remaining: 13m 1s
2295:	learn: 0.0057411	total: 4m 16s	remaining: 14m 19s
2507:	learn: 0.0049891	total: 4m 16s	remaining: 12m 45s
2468:	learn: 0.0045172	total: 4m 16s	remaining: 13m 1s
2474:	learn: 0.0054487	total: 4m 16s	remaining: 12m 58s
2399:	learn: 0.0054304	total: 4m 16s	remaining: 13m 31s
2296:	learn: 0.0057379	total: 4m 16s	remaining: 14m 19s
2508:	learn: 0.0049851	total: 4m 16s	remaining: 12m 45s
2469:	learn: 0.0045140	total: 4m 16s	remaining: 13m 1s
2475:	learn: 0.0054454	total: 4m 16s	remaining: 12m 58s
2400:	learn: 0.0054283	total: 4m 16s	remaining: 13m 31s
2297:	learn: 0.0057329	total: 4m 16s	remaining: 14m 19s
2509:	learn: 0.0049819	total: 4m 16s	remaining: 12m 44s
2510:	learn: 0.0049794	total: 4m 16s	remaining: 12m 44s
2470:	learn: 0.0045107	total: 4m 16s	remaining: 13m 1s
2476:	learn: 0.0054424	total: 4m 16s	remaining: 12m 58s
2401:	learn: 0.0054255	total: 4m 16s	remaining: 13m 31s
2298:	learn: 0.0057275	total: 4m 16s	remaining: 14m 19s
2511:	learn: 0.0049768	total: 4m 16s	remaining: 12m 44s
2471:	learn: 0.0045089	total: 4m 16s	remaining: 13m
2402:	learn: 0.0054215	total: 4m 16s	remaining: 13m 30s
2477:	learn: 0.0054399	total: 4m 16s	remaining: 12m 58s
2299:	learn: 0.0057249	total: 4m 16s	remaining: 14m 18s
2512:	learn: 0.0049739	total: 4m 16s	remaining: 12m 44s
2472:	learn: 0.0045065	total: 4m 16s	remaining: 13m
2478:	learn: 0.0054373	total: 4m 16s	remaining: 12m 58s
2403:	learn: 0.0054180	total: 4m 16s	remaining: 13m 30s
2513:	learn: 0.0049708	total: 4m 16s	remaining: 12m 44s
2300:	learn: 0.0057206	total: 4m 16s	remaining: 14m 18s
2473:	learn: 0.0045040	total: 4m 16s	remaining: 13m
2479:	learn: 0.0054343	total: 4m 16s	remaining: 12m 58s
2301:	learn: 0.0057173	total: 4m 16s	remaining: 14m 18s
2514:	learn: 0.0049678	total: 4m 16s	remaining: 12m 44s
2404:	learn: 0.0054160	total: 4m 16s	remaining: 13m 30s
2474:	learn: 0.0045021	total: 4m 16s	remaining: 13m
2302:	learn: 0.0057120	total: 4m 16s	remaining: 14m 18s
2515:	learn: 0.0049638	total: 4m 16s	remaining: 12m 43s
2480:	learn: 0.0054321	total: 4m 16s	remaining: 12m 57s
2405:	learn: 0.0054123	total: 4m 16s	remaining: 13m 30s
2475:	learn: 0.0044993	total: 4m 16s	remaining: 13m
2481:	learn: 0.0054276	total: 4m 16s	remaining: 12m 57s
2516:	learn: 0.0049602	total: 4m 16s	remaining: 12m 43s
2303:	learn: 0.0057097	total: 4m 16s	remaining: 14m 18s
2406:	learn: 0.0054097	total: 4m 16s	remaining: 13m 30s
2476:	learn: 0.0044948	total: 4m 16s	remaining: 13m
2482:	learn: 0.0054238	total: 4m 16s	remaining: 12m 57s
2517:	learn: 0.0049588	total: 4m 17s	remaining: 12m 43s
2407:	learn: 0.0054074	total: 4m 17s	remaining: 13m 30s
2477:	learn: 0.0044929	total: 4m 17s	remaining: 13m
2304:	learn: 0.0057049	total: 4m 17s	remaining: 14m 18s
2483:	learn: 0.0054216	total: 4m 16s	remaining: 12m 57s
2408:	learn: 0.0054043	total: 4m 17s	remaining: 13m 30s
2518:	learn: 0.0049562	total: 4m 17s	remaining: 12m 43s
2305:	learn: 0.0057016	total: 4m 17s	remaining: 14m 18s
2478:	learn: 0.0044904	total: 4m 17s	remaining: 13m
2409:	learn: 0.0054014	total: 4m 17s	remaining: 13m 30s
2484:	learn: 0.0054170	total: 4m 17s	remaining: 12m 57s
2519:	learn: 0.0049521	total: 4m 17s	remaining: 12m 43s
2306:	learn: 0.0056980	total: 4m 17s	remaining: 14m 18s
2410:	learn: 0.0053989	total: 4m 17s	remaining: 13m 29s

2479:	learn: 0.0044884	total: 4m 17s	remaining: 12m 59s
2485:	learn: 0.0054137	total: 4m 17s	remaining: 12m 57s
2520:	learn: 0.0049496	total: 4m 17s	remaining: 12m 43s
2411:	learn: 0.0053962	total: 4m 17s	remaining: 13m 29s
2307:	learn: 0.0056913	total: 4m 17s	remaining: 14m 17s
2480:	learn: 0.0044843	total: 4m 17s	remaining: 12m 59s
2486:	learn: 0.0054113	total: 4m 17s	remaining: 12m 57s
2412:	learn: 0.0053926	total: 4m 17s	remaining: 13m 29s
2521:	learn: 0.0049471	total: 4m 17s	remaining: 12m 43s
2308:	learn: 0.0056880	total: 4m 17s	remaining: 14m 17s
2487:	learn: 0.0054078	total: 4m 17s	remaining: 12m 57s
2413:	learn: 0.0053894	total: 4m 17s	remaining: 13m 29s
2481:	learn: 0.0044796	total: 4m 17s	remaining: 12m 59s
2522:	learn: 0.0049432	total: 4m 17s	remaining: 12m 43s
2309:	learn: 0.0056833	total: 4m 17s	remaining: 14m 17s
2488:	learn: 0.0054048	total: 4m 17s	remaining: 12m 56s
2414:	learn: 0.0053859	total: 4m 17s	remaining: 13m 29s
2523:	learn: 0.0049394	total: 4m 17s	remaining: 12m 43s
2482:	learn: 0.0044755	total: 4m 17s	remaining: 12m 59s
2489:	learn: 0.0054011	total: 4m 17s	remaining: 12m 56s
2310:	learn: 0.0056787	total: 4m 17s	remaining: 14m 17s
2490:	learn: 0.0053981	total: 4m 17s	remaining: 12m 56s
2415:	learn: 0.0053839	total: 4m 17s	remaining: 13m 29s
2524:	learn: 0.0049359	total: 4m 17s	remaining: 12m 43s
2483:	learn: 0.0044726	total: 4m 17s	remaining: 12m 59s
2311:	learn: 0.0056740	total: 4m 17s	remaining: 14m 17s
2491:	learn: 0.0053959	total: 4m 17s	remaining: 12m 56s
2484:	learn: 0.0044705	total: 4m 17s	remaining: 12m 59s
2525:	learn: 0.0049321	total: 4m 17s	remaining: 12m 43s
2416:	learn: 0.0053817	total: 4m 17s	remaining: 13m 29s
2312:	learn: 0.0056702	total: 4m 17s	remaining: 14m 17s
2492:	learn: 0.0053923	total: 4m 17s	remaining: 12m 56s
2485:	learn: 0.0044675	total: 4m 17s	remaining: 12m 59s
2417:	learn: 0.0053766	total: 4m 18s	remaining: 13m 29s
2526:	learn: 0.0049283	total: 4m 17s	remaining: 12m 42s
2313:	learn: 0.0056669	total: 4m 18s	remaining: 14m 17s
2493:	learn: 0.0053893	total: 4m 17s	remaining: 12m 56s
2486:	learn: 0.0044651	total: 4m 18s	remaining: 12m 59s
2418:	learn: 0.0053729	total: 4m 18s	remaining: 13m 28s
2527:	learn: 0.0049254	total: 4m 18s	remaining: 12m 42s
2494:	learn: 0.0053875	total: 4m 17s	remaining: 12m 56s
2314:	learn: 0.0056613	total: 4m 18s	remaining: 14m 17s
2419:	learn: 0.0053690	total: 4m 18s	remaining: 13m 28s
2487:	learn: 0.0044623	total: 4m 18s	remaining: 12m 59s
2495:	learn: 0.0053832	total: 4m 18s	remaining: 12m 55s
2315:	learn: 0.0056566	total: 4m 18s	remaining: 14m 16s
2528:	learn: 0.0049223	total: 4m 18s	remaining: 12m 42s
2420:	learn: 0.0053663	total: 4m 18s	remaining: 13m 28s
2488:	learn: 0.0044596	total: 4m 18s	remaining: 12m 59s
2496:	learn: 0.0053801	total: 4m 18s	remaining: 12m 55s
2529:	learn: 0.0049194	total: 4m 18s	remaining: 12m 42s
2421:	learn: 0.0053607	total: 4m 18s	remaining: 13m 28s
2316:	learn: 0.0056515	total: 4m 18s	remaining: 14m 16s
2489:	learn: 0.0044571	total: 4m 18s	remaining: 12m 59s
2497:	learn: 0.0053752	total: 4m 18s	remaining: 12m 55s
2422:	learn: 0.0053554	total: 4m 18s	remaining: 13m 28s
2530:	learn: 0.0049172	total: 4m 18s	remaining: 12m 42s
2490:	learn: 0.0044547	total: 4m 18s	remaining: 12m 58s
2317:	learn: 0.0056486	total: 4m 18s	remaining: 14m 16s
2498:	learn: 0.0053728	total: 4m 18s	remaining: 12m 55s
2423:	learn: 0.0053524	total: 4m 18s	remaining: 13m 28s
2531:	learn: 0.0049142	total: 4m 18s	remaining: 12m 42s
2491:	learn: 0.0044507	total: 4m 18s	remaining: 12m 58s
2318:	learn: 0.0056438	total: 4m 18s	remaining: 14m 16s
2532:	learn: 0.0049105	total: 4m 18s	remaining: 12m 42s
2499:	learn: 0.0053707	total: 4m 18s	remaining: 12m 55s
2492:	learn: 0.0044459	total: 4m 18s	remaining: 12m 58s
2424:	learn: 0.0053493	total: 4m 18s	remaining: 13m 27s
2533:	learn: 0.0049084	total: 4m 18s	remaining: 12m 42s
2500:	learn: 0.0053673	total: 4m 18s	remaining: 12m 55s
2425:	learn: 0.0053477	total: 4m 18s	remaining: 13m 27s
2493:	learn: 0.0044435	total: 4m 18s	remaining: 12m 58s
2319:	learn: 0.0056397	total: 4m 18s	remaining: 14m 16s
2534:	learn: 0.0049058	total: 4m 18s	remaining: 12m 42s
2501:	learn: 0.0053630	total: 4m 18s	remaining: 12m 55s
2494:	learn: 0.0044408	total: 4m 18s	remaining: 12m 58s
2426:	learn: 0.0053435	total: 4m 18s	remaining: 13m 27s
2320:	learn: 0.0056332	total: 4m 18s	remaining: 14m 16s
2535:	learn: 0.0049018	total: 4m 18s	remaining: 12m 41s
2502:	learn: 0.0053609	total: 4m 18s	remaining: 12m 55s
2495:	learn: 0.0044382	total: 4m 18s	remaining: 12m 58s
2427:	learn: 0.0053410	total: 4m 18s	remaining: 13m 27s
2536:	learn: 0.0048986	total: 4m 18s	remaining: 12m 41s
2321:	learn: 0.0056282	total: 4m 19s	remaining: 14m 16s
2503:	learn: 0.0053572	total: 4m 18s	remaining: 12m 55s
2496:	learn: 0.0044356	total: 4m 18s	remaining: 12m 58s
2537:	learn: 0.0048965	total: 4m 19s	remaining: 12m 41s
2428:	learn: 0.0053384	total: 4m 19s	remaining: 13m 27s
2322:	learn: 0.0056232	total: 4m 19s	remaining: 14m 16s
2504:	learn: 0.0053542	total: 4m 18s	remaining: 12m 54s
2497:	learn: 0.0044332	total: 4m 19s	remaining: 12m 58s
2429:	learn: 0.0053341	total: 4m 19s	remaining: 13m 27s
2538:	learn: 0.0048934	total: 4m 19s	remaining: 12m 41s
2323:	learn: 0.0056209	total: 4m 19s	remaining: 14m 16s
2505:	learn: 0.0053503	total: 4m 19s	remaining: 12m 54s
2498:	learn: 0.0044294	total: 4m 19s	remaining: 12m 57s
2430:	learn: 0.0053317	total: 4m 19s	remaining: 13m 27s
2506:	learn: 0.0053469	total: 4m 19s	remaining: 12m 54s
2539:	learn: 0.0048887	total: 4m 19s	remaining: 12m 41s
2324:	learn: 0.0056162	total: 4m 19s	remaining: 14m 16s
2499:	learn: 0.0044271	total: 4m 19s	remaining: 12m 57s
2431:	learn: 0.0053293	total: 4m 19s	remaining: 13m 27s
2507:	learn: 0.0053428	total: 4m 19s	remaining: 12m 54s
2325:	learn: 0.0056123	total: 4m 19s	remaining: 14m 15s
2540:	learn: 0.0048849	total: 4m 19s	remaining: 12m 41s
2432:	learn: 0.0053258	total: 4m 19s	remaining: 13m 26s
2500:	learn: 0.0044240	total: 4m 19s	remaining: 12m 57s
2326:	learn: 0.0056094	total: 4m 19s	remaining: 14m 15s
2508:	learn: 0.0053387	total: 4m 19s	remaining: 12m 54s
2433:	learn: 0.0053220	total: 4m 19s	remaining: 13m 26s
2541:	learn: 0.0048809	total: 4m 19s	remaining: 12m 41s
2327:	learn: 0.0056064	total: 4m 19s	remaining: 14m 15s
2501:	learn: 0.0044214	total: 4m 19s	remaining: 12m 57s
2509:	learn: 0.0053346	total: 4m 19s	remaining: 12m 54s
2434:	learn: 0.0053186	total: 4m 19s	remaining: 13m 26s
2542:	learn: 0.0048770	total: 4m 19s	remaining: 12m 41s
2502:	learn: 0.0044190	total: 4m 19s	remaining: 12m 57s
2328:	learn: 0.0056024	total: 4m 19s	remaining: 14m 15s
2510:	learn: 0.0053301	total: 4m 19s	remaining: 12m 54s
2543:	learn: 0.0048741	total: 4m 19s	remaining: 12m 41s
2435:	learn: 0.0053140	total: 4m 19s	remaining: 13m 26s
2503:	learn: 0.0044164	total: 4m 19s	remaining: 12m 57s
2329:	learn: 0.0055994	total: 4m 19s	remaining: 14m 15s
2544:	learn: 0.0048709	total: 4m 19s	remaining: 12m 41s
2511:	learn: 0.0053271	total: 4m 19s	remaining: 12m 54s
2436:	learn: 0.0053107	total: 4m 19s	remaining: 13m 26s
2504:	learn: 0.0044141	total: 4m 19s	remaining: 12m 57s
2512:	learn: 0.0053250	total: 4m 19s	remaining: 12m 53s
2330:	learn: 0.0055935	total: 4m 19s	remaining: 14m 15s
2545:	learn: 0.0048675	total: 4m 19s	remaining: 12m 40s
2437:	learn: 0.0053078	total: 4m 19s	remaining: 13m 26s
2505:	learn: 0.0044114	total: 4m 19s	remaining: 12m 57s
2513:	learn: 0.0053226	total: 4m 19s	remaining: 12m 53s
2331:	learn: 0.0055885	total: 4m 20s	remaining: 14m 15s
2546:	learn: 0.0048650	total: 4m 19s	remaining: 12m 40s
2438:	learn: 0.0053049	total: 4m 20s	remaining: 13m 26s
2506:	learn: 0.0044087	total: 4m 20s	remaining: 12m 57s
2332:	learn: 0.0055851	total: 4m 20s	remaining: 14m 14s
2514:	learn: 0.0053192	total: 4m 19s	remaining: 12m 53s
2547:	learn: 0.0048607	total: 4m 20s	remaining: 12m 40s
2439:	learn: 0.0053001	total: 4m 20s	remaining: 13m 26s
2507:	learn: 0.0044050	total: 4m 20s	remaining: 12m 56s
2333:	learn: 0.0055811	total: 4m 20s	remaining: 14m 14s
2515:	learn: 0.0053168	total: 4m 20s	remaining: 12m 53s
2548:	learn: 0.0048570	total: 4m 20s	remaining: 12m 40s
2440:	learn: 0.0052978	total: 4m 20s	remaining: 13m 25s
2508:	learn: 0.0044025	total: 4m 20s	remaining: 12m 56s
2334:	learn: 0.0055765	total: 4m 20s	remaining: 14m 14s
2516:	learn: 0.0053127	total: 4m 20s	remaining: 12m 53s
2549:	learn: 0.0048540	total: 4m 20s	remaining: 12m 40s
2441:	learn: 0.0052953	total: 4m 20s	remaining: 13m 25s
2509:	learn: 0.0043998	total: 4m 20s	remaining: 12m 56s
2517:	learn: 0.0053108	total: 4m 20s	remaining: 12m 53s
2335:	learn: 0.0055739	total: 4m 20s	remaining: 14m 14s
2442:	learn: 0.0052901	total: 4m 20s	remaining: 13m 25s
2550:	learn: 0.0048509	total: 4m 20s	remaining: 12m 40s
2510:	learn: 0.0043963	total: 4m 20s	remaining: 12m 56s
2518:	learn: 0.0053084	total: 4m 20s	remaining: 12m 53s
2336:	learn: 0.0055700	total: 4m 20s	remaining: 14m 14s
2551:	learn: 0.0048474	total: 4m 20s	remaining: 12m 40s
2511:	learn: 0.0043930	total: 4m 20s	remaining: 12m 56s
2443:	learn: 0.0052876	total: 4m 20s	remaining: 13m 25s
2519:	learn: 0.0053065	total: 4m 20s	remaining: 12m 53s
2337:	learn: 0.0055667	total: 4m 20s	remaining: 14m 14s
2552:	learn: 0.0048445	total: 4m 20s	remaining: 12m 40s
2444:	learn: 0.0052856	total: 4m 20s	remaining: 13m 25s
2520:	learn: 0.0053043	total: 4m 20s	remaining: 12m 52s
2512:	learn: 0.0043911	total: 4m 20s	remaining: 12m 56s
2553:	learn: 0.0048415	total: 4m 20s	remaining: 12m 39s
2338:	learn: 0.0055621	total: 4m 20s	remaining: 14m 14s
2521:	learn: 0.0053023	total: 4m 20s	remaining: 12m 52s
2513:	learn: 0.0043887	total: 4m 20s	remaining: 12m 56s
2554:	learn: 0.0048381	total: 4m 20s	remaining: 12m 39s
2445:	learn: 0.0052828	total: 4m 20s	remaining: 13m 25s
2339:	learn: 0.0055563	total: 4m 20s	remaining: 14m 13s
2522:	learn: 0.0052979	total: 4m 20s	remaining: 12m 52s
2555:	learn: 0.0048352	total: 4m 20s	remaining: 12m 39s
2446:	learn: 0.0052796	total: 4m 20s	remaining: 13m 25s
2514:	learn: 0.0043858	total: 4m 20s	remaining: 12m 56s
2340:	learn: 0.0055505	total: 4m 20s	remaining: 14m 13s
2556:	learn: 0.0048322	total: 4m 20s	remaining: 12m 39s
2523:	learn: 0.0052935	total: 4m 20s	remaining: 12m 52s
2515:	learn: 0.0043835	total: 4m 20s	remaining: 12m 56s
2557:	learn: 0.0048302	total: 4m 20s	remaining: 12m 39s
2447:	learn: 0.0052752	total: 4m 21s	remaining: 13m 25s
2341:	learn: 0.0055469	total: 4m 21s	remaining: 14m 13s
2524:	learn: 0.0052904	total: 4m 20s	remaining: 12m 52s
2516:	learn: 0.0043807	total: 4m 21s	remaining: 12m 56s
2448:	learn: 0.0052724	total: 4m 21s	remaining: 13m 25s
2558:	learn: 0.0048261	total: 4m 21s	remaining: 12m 39s
2342:	learn: 0.0055414	total: 4m 21s	remaining: 14m 13s
2525:	learn: 0.0052854	total: 4m 21s	remaining: 12m 52s
2517:	learn: 0.0043780	total: 4m 21s	remaining: 12m 55s
2559:	learn: 0.0048238	total: 4m 21s	remaining: 12m 39s
2518:	learn: 0.0043753	total: 4m 21s	remaining: 12m 55s
2449:	learn: 0.0052699	total: 4m 21s	remaining: 13m 25s
2343:	learn: 0.0055389	total: 4m 21s	remaining: 14m 13s
2526:	learn: 0.0052831	total: 4m 21s	remaining: 12m 52s
2560:	learn: 0.0048209	total: 4m 21s	remaining: 12m 38s
2519:	learn: 0.0043723	total: 4m 21s	remaining: 12m 55s
2450:	learn: 0.0052675	total: 4m 21s	remaining: 13m 25s
2527:	learn: 0.0052810	total: 4m 21s	remaining: 12m 52s
2344:	learn: 0.0055341	total: 4m 21s	remaining: 14m 13s
2561:	learn: 0.0048178	total: 4m 21s	remaining: 12m 38s
2520:	learn: 0.0043700	total: 4m 21s	remaining: 12m 55s
2562:	learn: 0.0048150	total: 4m 21s	remaining: 12m 38s
2345:	learn: 0.0055303	total: 4m 21s	remaining: 14m 13s
2451:	learn: 0.0052653	total: 4m 21s	remaining: 13m 24s
2528:	learn: 0.0052792	total: 4m 21s	remaining: 12m 52s
2521:	learn: 0.0043667	total: 4m 21s	remaining: 12m 55s
2563:	learn: 0.0048120	total: 4m 21s	remaining: 12m 38s
2346:	learn: 0.0055246	total: 4m 21s	remaining: 14m 13s
2529:	learn: 0.0052767	total: 4m 21s	remaining: 12m 51s
2522:	learn: 0.0043640	total: 4m 21s	remaining: 12m 55s
2452:	learn: 0.0052624	total: 4m 21s	remaining: 13m 24s
2564:	learn: 0.0048098	total: 4m 21s	remaining: 12m 38s
2523:	learn: 0.0043622	total: 4m 21s	remaining: 12m 54s
2530:	learn: 0.0052726	total: 4m 21s	remaining: 12m 51s
2347:	learn: 0.0055193	total: 4m 21s	remaining: 14m 13s
2453:	learn: 0.0052591	total: 4m 21s	remaining: 13m 24s
2531:	learn: 0.0052692	total: 4m 21s	remaining: 12m 51s
2565:	learn: 0.0048070	total: 4m 21s	remaining: 12m 38s
2524:	learn: 0.0043583	total: 4m 21s	remaining: 12m 54s
2348:	learn: 0.0055153	total: 4m 21s	remaining: 14m 12s
2454:	learn: 0.0052557	total: 4m 21s	remaining: 13m 24s
2532:	learn: 0.0052667	total: 4m 21s	remaining: 12m 51s
2525:	learn: 0.0043559	total: 4m 21s	remaining: 12m 54s
2349:	learn: 0.0055118	total: 4m 21s	remaining: 14m 12s
2566:	learn: 0.0048044	total: 4m 21s	remaining: 12m 38s
2455:	learn: 0.0052534	total: 4m 21s	remaining: 13m 24s
2533:	learn: 0.0052622	total: 4m 21s	remaining: 12m 51s
2350:	learn: 0.0055077	total: 4m 22s	remaining: 14m 12s
2567:	learn: 0.0048013	total: 4m 21s	remaining: 12m 38s
2526:	learn: 0.0043534	total: 4m 21s	remaining: 12m 54s
2456:	learn: 0.0052507	total: 4m 22s	remaining: 13m 24s
2534:	learn: 0.0052593	total: 4m 21s	remaining: 12m 51s
2351:	learn: 0.0055030	total: 4m 22s	remaining: 14m 12s
2568:	learn: 0.0047974	total: 4m 22s	remaining: 12m 38s
2527:	learn: 0.0043517	total: 4m 22s	remaining: 12m 54s
2535:	learn: 0.0052562	total: 4m 22s	remaining: 12m 51s
2457:	learn: 0.0052464	total: 4m 22s	remaining: 13m 24s
2352:	learn: 0.0055012	total: 4m 22s	remaining: 14m 12s
2569:	learn: 0.0047943	total: 4m 22s	remaining: 12m 37s
2528:	learn: 0.0043498	total: 4m 22s	remaining: 12m 54s
2536:	learn: 0.0052541	total: 4m 22s	remaining: 12m 51s
2458:	learn: 0.0052413	total: 4m 22s	remaining: 13m 24s
2570:	learn: 0.0047906	total: 4m 22s	remaining: 12m 37s
2353:	learn: 0.0054965	total: 4m 22s	remaining: 14m 12s
2529:	learn: 0.0043473	total: 4m 22s	remaining: 12m 54s
2571:	learn: 0.0047884	total: 4m 22s	remaining: 12m 37s
2459:	learn: 0.0052381	total: 4m 22s	remaining: 13m 24s
2537:	learn: 0.0052501	total: 4m 22s	remaining: 12m 51s
2354:	learn: 0.0054918	total: 4m 22s	remaining: 14m 11s
2530:	learn: 0.0043451	total: 4m 22s	remaining: 12m 54s
2572:	learn: 0.0047864	total: 4m 22s	remaining: 12m 37s
2538:	learn: 0.0052469	total: 4m 22s	remaining: 12m 50s
2460:	learn: 0.0052353	total: 4m 22s	remaining: 13m 24s
2355:	learn: 0.0054873	total: 4m 22s	remaining: 14m 11s
2531:	learn: 0.0043428	total: 4m 22s	remaining: 12m 54s
2461:	learn: 0.0052322	total: 4m 22s	remaining: 13m 23s
2573:	learn: 0.0047826	total: 4m 22s	remaining: 12m 37s
2539:	learn: 0.0052444	total: 4m 22s	remaining: 12m 50s
2532:	learn: 0.0043406	total: 4m 22s	remaining: 12m 53s
2356:	learn: 0.0054832	total: 4m 22s	remaining: 14m 11s
2462:	learn: 0.0052287	total: 4m 22s	remaining: 13m 23s
2574:	learn: 0.0047799	total: 4m 22s	remaining: 12m 37s
2540:	learn: 0.0052424	total: 4m 22s	remaining: 12m 50s
2533:	learn: 0.0043373	total: 4m 22s	remaining: 12m 53s
2357:	learn: 0.0054779	total: 4m 22s	remaining: 14m 11s
2575:	learn: 0.0047768	total: 4m 22s	remaining: 12m 37s
2463:	learn: 0.0052245	total: 4m 22s	remaining: 13m 23s
2534:	learn: 0.0043351	total: 4m 22s	remaining: 12m 53s
2541:	learn: 0.0052399	total: 4m 22s	remaining: 12m 50s
2576:	learn: 0.0047731	total: 4m 22s	remaining: 12m 36s
2358:	learn: 0.0054741	total: 4m 22s	remaining: 14m 11s
2464:	learn: 0.0052212	total: 4m 22s	remaining: 13m 23s
2535:	learn: 0.0043325	total: 4m 22s	remaining: 12m 53s
2542:	learn: 0.0052368	total: 4m 22s	remaining: 12m 50s
2577:	learn: 0.0047694	total: 4m 22s	remaining: 12m 36s
2465:	learn: 0.0052189	total: 4m 22s	remaining: 13m 23s
2359:	learn: 0.0054714	total: 4m 23s	remaining: 14m 11s
2536:	learn: 0.0043308	total: 4m 22s	remaining: 12m 53s
2543:	learn: 0.0052348	total: 4m 22s	remaining: 12m 50s
2578:	learn: 0.0047672	total: 4m 22s	remaining: 12m 36s
2466:	learn: 0.0052156	total: 4m 23s	remaining: 13m 23s
2360:	learn: 0.0054676	total: 4m 23s	remaining: 14m 11s
2544:	learn: 0.0052325	total: 4m 22s	remaining: 12m 50s
2579:	learn: 0.0047633	total: 4m 23s	remaining: 12m 36s
2537:	learn: 0.0043287	total: 4m 23s	remaining: 12m 53s
2467:	learn: 0.0052115	total: 4m 23s	remaining: 13m 23s
2361:	learn: 0.0054632	total: 4m 23s	remaining: 14m 11s
2545:	learn: 0.0052288	total: 4m 23s	remaining: 12m 50s

2580:	learn: 0.0047611	total: 4m 23s	remaining: 12m 36s
2538:	learn: 0.0043270	total: 4m 23s	remaining: 12m 53s
2468:	learn: 0.0052084	total: 4m 23s	remaining: 13m 22s
2581:	learn: 0.0047578	total: 4m 23s	remaining: 12m 36s
2546:	learn: 0.0052249	total: 4m 23s	remaining: 12m 50s
2362:	learn: 0.0054593	total: 4m 23s	remaining: 14m 11s
2539:	learn: 0.0043255	total: 4m 23s	remaining: 12m 53s
2469:	learn: 0.0052056	total: 4m 23s	remaining: 13m 22s
2582:	learn: 0.0047541	total: 4m 23s	remaining: 12m 36s
2540:	learn: 0.0043223	total: 4m 23s	remaining: 12m 53s
2547:	learn: 0.0052232	total: 4m 23s	remaining: 12m 49s
2363:	learn: 0.0054563	total: 4m 23s	remaining: 14m 10s
2470:	learn: 0.0052022	total: 4m 23s	remaining: 13m 22s
2583:	learn: 0.0047504	total: 4m 23s	remaining: 12m 36s
2548:	learn: 0.0052193	total: 4m 23s	remaining: 12m 49s
2364:	learn: 0.0054511	total: 4m 23s	remaining: 14m 10s
2541:	learn: 0.0043203	total: 4m 23s	remaining: 12m 52s
2471:	learn: 0.0051998	total: 4m 23s	remaining: 13m 22s
2584:	learn: 0.0047485	total: 4m 23s	remaining: 12m 35s
2542:	learn: 0.0043185	total: 4m 23s	remaining: 12m 52s
2549:	learn: 0.0052165	total: 4m 23s	remaining: 12m 49s
2365:	learn: 0.0054460	total: 4m 23s	remaining: 14m 10s
2585:	learn: 0.0047446	total: 4m 23s	remaining: 12m 35s
2472:	learn: 0.0051954	total: 4m 23s	remaining: 13m 22s
2543:	learn: 0.0043163	total: 4m 23s	remaining: 12m 52s
2550:	learn: 0.0052146	total: 4m 23s	remaining: 12m 49s
2366:	learn: 0.0054417	total: 4m 23s	remaining: 14m 10s
2586:	learn: 0.0047414	total: 4m 23s	remaining: 12m 35s
2544:	learn: 0.0043140	total: 4m 23s	remaining: 12m 52s
2473:	learn: 0.0051916	total: 4m 23s	remaining: 13m 22s
2551:	learn: 0.0052112	total: 4m 23s	remaining: 12m 49s
2587:	learn: 0.0047394	total: 4m 23s	remaining: 12m 35s
2545:	learn: 0.0043112	total: 4m 23s	remaining: 12m 52s
2367:	learn: 0.0054378	total: 4m 23s	remaining: 14m 10s
2474:	learn: 0.0051896	total: 4m 23s	remaining: 13m 22s
2588:	learn: 0.0047377	total: 4m 23s	remaining: 12m 35s
2552:	learn: 0.0052072	total: 4m 23s	remaining: 12m 49s
2546:	learn: 0.0043077	total: 4m 23s	remaining: 12m 52s
2475:	learn: 0.0051846	total: 4m 23s	remaining: 13m 22s
2589:	learn: 0.0047352	total: 4m 23s	remaining: 12m 35s
2368:	learn: 0.0054366	total: 4m 24s	remaining: 14m 10s
2553:	learn: 0.0052045	total: 4m 23s	remaining: 12m 49s
2547:	learn: 0.0043057	total: 4m 24s	remaining: 12m 52s
2476:	learn: 0.0051822	total: 4m 24s	remaining: 13m 22s
2369:	learn: 0.0054331	total: 4m 24s	remaining: 14m 10s
2590:	learn: 0.0047330	total: 4m 24s	remaining: 12m 35s
2554:	learn: 0.0052020	total: 4m 23s	remaining: 12m 49s
2548:	learn: 0.0043023	total: 4m 24s	remaining: 12m 51s
2591:	learn: 0.0047296	total: 4m 24s	remaining: 12m 34s
2477:	learn: 0.0051808	total: 4m 24s	remaining: 13m 22s
2370:	learn: 0.0054303	total: 4m 24s	remaining: 14m 10s
2555:	learn: 0.0052001	total: 4m 24s	remaining: 12m 49s
2592:	learn: 0.0047265	total: 4m 24s	remaining: 12m 34s
2549:	learn: 0.0043005	total: 4m 24s	remaining: 12m 51s
2371:	learn: 0.0054264	total: 4m 24s	remaining: 14m 10s
2478:	learn: 0.0051761	total: 4m 24s	remaining: 13m 21s
2550:	learn: 0.0042982	total: 4m 24s	remaining: 12m 51s
2593:	learn: 0.0047242	total: 4m 24s	remaining: 12m 34s
2556:	learn: 0.0051958	total: 4m 24s	remaining: 12m 49s
2372:	learn: 0.0054235	total: 4m 24s	remaining: 14m 9s
2479:	learn: 0.0051726	total: 4m 24s	remaining: 13m 21s
2594:	learn: 0.0047209	total: 4m 24s	remaining: 12m 34s
2557:	learn: 0.0051929	total: 4m 24s	remaining: 12m 48s
2551:	learn: 0.0042963	total: 4m 24s	remaining: 12m 51s
2373:	learn: 0.0054184	total: 4m 24s	remaining: 14m 9s
2558:	learn: 0.0051891	total: 4m 24s	remaining: 12m 48s
2595:	learn: 0.0047176	total: 4m 24s	remaining: 12m 34s
2552:	learn: 0.0042937	total: 4m 24s	remaining: 12m 51s
2480:	learn: 0.0051691	total: 4m 24s	remaining: 13m 21s
2374:	learn: 0.0054165	total: 4m 24s	remaining: 14m 9s
2596:	learn: 0.0047142	total: 4m 24s	remaining: 12m 34s
2559:	learn: 0.0051844	total: 4m 24s	remaining: 12m 48s
2553:	learn: 0.0042906	total: 4m 24s	remaining: 12m 51s
2481:	learn: 0.0051652	total: 4m 24s	remaining: 13m 21s
2375:	learn: 0.0054110	total: 4m 24s	remaining: 14m 9s
2560:	learn: 0.0051803	total: 4m 24s	remaining: 12m 48s
2597:	learn: 0.0047098	total: 4m 24s	remaining: 12m 34s
2554:	learn: 0.0042885	total: 4m 24s	remaining: 12m 51s
2482:	learn: 0.0051627	total: 4m 24s	remaining: 13m 21s
2561:	learn: 0.0051785	total: 4m 24s	remaining: 12m 48s
2376:	learn: 0.0054069	total: 4m 24s	remaining: 14m 9s
2598:	learn: 0.0047071	total: 4m 24s	remaining: 12m 34s
2555:	learn: 0.0042861	total: 4m 24s	remaining: 12m 51s
2483:	learn: 0.0051590	total: 4m 24s	remaining: 13m 21s
2377:	learn: 0.0054033	total: 4m 24s	remaining: 14m 9s
2562:	learn: 0.0051752	total: 4m 24s	remaining: 12m 48s
2599:	learn: 0.0047044	total: 4m 24s	remaining: 12m 33s
2556:	learn: 0.0042832	total: 4m 24s	remaining: 12m 51s
2484:	learn: 0.0051556	total: 4m 25s	remaining: 13m 21s
2378:	learn: 0.0053993	total: 4m 25s	remaining: 14m 9s
2557:	learn: 0.0042805	total: 4m 24s	remaining: 12m 50s
2563:	learn: 0.0051702	total: 4m 24s	remaining: 12m 48s
2600:	learn: 0.0047015	total: 4m 25s	remaining: 12m 33s
2485:	learn: 0.0051523	total: 4m 25s	remaining: 13m 21s
2558:	learn: 0.0042784	total: 4m 25s	remaining: 12m 50s
2379:	learn: 0.0053959	total: 4m 25s	remaining: 14m 8s
2601:	learn: 0.0046991	total: 4m 25s	remaining: 12m 33s
2564:	learn: 0.0051681	total: 4m 25s	remaining: 12m 48s
2559:	learn: 0.0042763	total: 4m 25s	remaining: 12m 50s
2486:	learn: 0.0051477	total: 4m 25s	remaining: 13m 21s
2380:	learn: 0.0053923	total: 4m 25s	remaining: 14m 8s
2565:	learn: 0.0051649	total: 4m 25s	remaining: 12m 48s
2602:	learn: 0.0046968	total: 4m 25s	remaining: 12m 33s
2560:	learn: 0.0042732	total: 4m 25s	remaining: 12m 50s
2487:	learn: 0.0051455	total: 4m 25s	remaining: 13m 21s
2603:	learn: 0.0046936	total: 4m 25s	remaining: 12m 33s
2381:	learn: 0.0053880	total: 4m 25s	remaining: 14m 8s
2566:	learn: 0.0051609	total: 4m 25s	remaining: 12m 47s
2561:	learn: 0.0042704	total: 4m 25s	remaining: 12m 50s
2488:	learn: 0.0051410	total: 4m 25s	remaining: 13m 20s
2604:	learn: 0.0046915	total: 4m 25s	remaining: 12m 33s
2382:	learn: 0.0053833	total: 4m 25s	remaining: 14m 8s
2567:	learn: 0.0051582	total: 4m 25s	remaining: 12m 47s
2489:	learn: 0.0051379	total: 4m 25s	remaining: 13m 20s
2605:	learn: 0.0046889	total: 4m 25s	remaining: 12m 33s
2562:	learn: 0.0042671	total: 4m 25s	remaining: 12m 50s
2568:	learn: 0.0051560	total: 4m 25s	remaining: 12m 47s
2383:	learn: 0.0053806	total: 4m 25s	remaining: 14m 8s
2490:	learn: 0.0051357	total: 4m 25s	remaining: 13m 20s
2563:	learn: 0.0042638	total: 4m 25s	remaining: 12m 50s
2606:	learn: 0.0046860	total: 4m 25s	remaining: 12m 33s
2569:	learn: 0.0051516	total: 4m 25s	remaining: 12m 47s
2384:	learn: 0.0053789	total: 4m 25s	remaining: 14m 8s
2607:	learn: 0.0046840	total: 4m 25s	remaining: 12m 33s
2491:	learn: 0.0051334	total: 4m 25s	remaining: 13m 20s
2564:	learn: 0.0042617	total: 4m 25s	remaining: 12m 50s
2570:	learn: 0.0051492	total: 4m 25s	remaining: 12m 47s
2385:	learn: 0.0053739	total: 4m 25s	remaining: 14m 8s
2492:	learn: 0.0051305	total: 4m 25s	remaining: 13m 20s
2608:	learn: 0.0046816	total: 4m 25s	remaining: 12m 32s
2565:	learn: 0.0042597	total: 4m 25s	remaining: 12m 49s
2571:	learn: 0.0051454	total: 4m 25s	remaining: 12m 47s
2609:	learn: 0.0046785	total: 4m 25s	remaining: 12m 32s
2386:	learn: 0.0053693	total: 4m 25s	remaining: 14m 8s
2493:	learn: 0.0051263	total: 4m 25s	remaining: 13m 20s
2566:	learn: 0.0042568	total: 4m 25s	remaining: 12m 49s
2572:	learn: 0.0051410	total: 4m 25s	remaining: 12m 47s
2610:	learn: 0.0046767	total: 4m 25s	remaining: 12m 32s
2494:	learn: 0.0051227	total: 4m 25s	remaining: 13m 20s
2567:	learn: 0.0042534	total: 4m 25s	remaining: 12m 49s
2387:	learn: 0.0053651	total: 4m 26s	remaining: 14m 8s
2573:	learn: 0.0051393	total: 4m 25s	remaining: 12m 47s
2611:	learn: 0.0046746	total: 4m 26s	remaining: 12m 32s
2495:	learn: 0.0051207	total: 4m 26s	remaining: 13m 19s
2568:	learn: 0.0042501	total: 4m 26s	remaining: 12m 49s
2574:	learn: 0.0051359	total: 4m 25s	remaining: 12m 46s
2388:	learn: 0.0053624	total: 4m 26s	remaining: 14m 8s
2496:	learn: 0.0051171	total: 4m 26s	remaining: 13m 19s
2569:	learn: 0.0042476	total: 4m 26s	remaining: 12m 49s
2575:	learn: 0.0051319	total: 4m 26s	remaining: 12m 46s
2613:	learn: 0.0046682	total: 4m 26s	remaining: 12m 32s
2570:	learn: 0.0042450	total: 4m 26s	remaining: 12m 49s
2389:	learn: 0.0053595	total: 4m 26s	remaining: 14m 7s
2497:	learn: 0.0051122	total: 4m 26s	remaining: 13m 19s
2576:	learn: 0.0051283	total: 4m 26s	remaining: 12m 46s
2614:	learn: 0.0046663	total: 4m 26s	remaining: 12m 32s
2571:	learn: 0.0042429	total: 4m 26s	remaining: 12m 49s
2498:	learn: 0.0051087	total: 4m 26s	remaining: 13m 19s
2390:	learn: 0.0053559	total: 4m 26s	remaining: 14m 7s
2577:	learn: 0.0051261	total: 4m 26s	remaining: 12m 46s
2615:	learn: 0.0046632	total: 4m 26s	remaining: 12m 32s
2572:	learn: 0.0042398	total: 4m 26s	remaining: 12m 48s
2499:	learn: 0.0051055	total: 4m 26s	remaining: 13m 19s
2391:	learn: 0.0053518	total: 4m 26s	remaining: 14m 7s
2578:	learn: 0.0051243	total: 4m 26s	remaining: 12m 46s
2616:	learn: 0.0046610	total: 4m 26s	remaining: 12m 31s
2573:	learn: 0.0042376	total: 4m 26s	remaining: 12m 48s
2500:	learn: 0.0050999	total: 4m 26s	remaining: 13m 19s
2392:	learn: 0.0053466	total: 4m 26s	remaining: 14m 7s
2579:	learn: 0.0051202	total: 4m 26s	remaining: 12m 46s
2617:	learn: 0.0046590	total: 4m 26s	remaining: 12m 31s
2574:	learn: 0.0042341	total: 4m 26s	remaining: 12m 48s
2501:	learn: 0.0050963	total: 4m 26s	remaining: 13m 19s
2393:	learn: 0.0053412	total: 4m 26s	remaining: 14m 7s
2618:	learn: 0.0046567	total: 4m 26s	remaining: 12m 31s
2580:	learn: 0.0051174	total: 4m 26s	remaining: 12m 46s
2575:	learn: 0.0042322	total: 4m 26s	remaining: 12m 48s
2502:	learn: 0.0050918	total: 4m 26s	remaining: 13m 19s
2394:	learn: 0.0053370	total: 4m 26s	remaining: 14m 7s
2619:	learn: 0.0046540	total: 4m 26s	remaining: 12m 31s
2503:	learn: 0.0050886	total: 4m 26s	remaining: 13m 18s
2581:	learn: 0.0051135	total: 4m 26s	remaining: 12m 46s
2576:	learn: 0.0042296	total: 4m 26s	remaining: 12m 48s
2620:	learn: 0.0046514	total: 4m 26s	remaining: 12m 31s
2395:	learn: 0.0053347	total: 4m 26s	remaining: 14m 7s
2582:	learn: 0.0051099	total: 4m 26s	remaining: 12m 46s
2504:	learn: 0.0050855	total: 4m 26s	remaining: 13m 18s
2577:	learn: 0.0042272	total: 4m 26s	remaining: 12m 48s
2621:	learn: 0.0046484	total: 4m 26s	remaining: 12m 31s
2505:	learn: 0.0050822	total: 4m 27s	remaining: 13m 18s
2396:	learn: 0.0053305	total: 4m 27s	remaining: 14m 7s
2583:	learn: 0.0051073	total: 4m 26s	remaining: 12m 46s
2578:	learn: 0.0042252	total: 4m 27s	remaining: 12m 48s
2506:	learn: 0.0050792	total: 4m 27s	remaining: 13m 18s
2622:	learn: 0.0046466	total: 4m 27s	remaining: 12m 31s
2397:	learn: 0.0053271	total: 4m 27s	remaining: 14m 6s
2584:	learn: 0.0051036	total: 4m 27s	remaining: 12m 46s
2507:	learn: 0.0050762	total: 4m 27s	remaining: 13m 18s
2579:	learn: 0.0042229	total: 4m 27s	remaining: 12m 48s
2623:	learn: 0.0046426	total: 4m 27s	remaining: 12m 31s
2398:	learn: 0.0053254	total: 4m 27s	remaining: 14m 6s
2580:	learn: 0.0042197	total: 4m 27s	remaining: 12m 48s
2585:	learn: 0.0050995	total: 4m 27s	remaining: 12m 45s
2624:	learn: 0.0046400	total: 4m 27s	remaining: 12m 30s
2508:	learn: 0.0050729	total: 4m 27s	remaining: 13m 18s
2399:	learn: 0.0053213	total: 4m 27s	remaining: 14m 6s
2581:	learn: 0.0042161	total: 4m 27s	remaining: 12m 47s
2625:	learn: 0.0046371	total: 4m 27s	remaining: 12m 30s
2586:	learn: 0.0050978	total: 4m 27s	remaining: 12m 45s
2509:	learn: 0.0050703	total: 4m 27s	remaining: 13m 18s
2582:	learn: 0.0042135	total: 4m 27s	remaining: 12m 47s
2400:	learn: 0.0053174	total: 4m 27s	remaining: 14m 6s
2626:	learn: 0.0046344	total: 4m 27s	remaining: 12m 30s
2510:	learn: 0.0050672	total: 4m 27s	remaining: 13m 17s
2587:	learn: 0.0050947	total: 4m 27s	remaining: 12m 45s
2583:	learn: 0.0042109	total: 4m 27s	remaining: 12m 47s
2401:	learn: 0.0053151	total: 4m 27s	remaining: 14m 6s
2627:	learn: 0.0046323	total: 4m 27s	remaining: 12m 30s
2588:	learn: 0.0050920	total: 4m 27s	remaining: 12m 45s
2511:	learn: 0.0050653	total: 4m 27s	remaining: 13m 17s
2584:	learn: 0.0042082	total: 4m 27s	remaining: 12m 47s
2402:	learn: 0.0053134	total: 4m 27s	remaining: 14m 6s
2628:	learn: 0.0046302	total: 4m 27s	remaining: 12m 30s
2589:	learn: 0.0050884	total: 4m 27s	remaining: 12m 45s
2512:	learn: 0.0050630	total: 4m 27s	remaining: 13m 17s
2585:	learn: 0.0042047	total: 4m 27s	remaining: 12m 47s
2629:	learn: 0.0046284	total: 4m 27s	remaining: 12m 30s
2403:	learn: 0.0053103	total: 4m 27s	remaining: 14m 6s
2513:	learn: 0.0050608	total: 4m 27s	remaining: 13m 17s
2590:	learn: 0.0050856	total: 4m 27s	remaining: 12m 45s
2586:	learn: 0.0042013	total: 4m 27s	remaining: 12m 47s
2630:	learn: 0.0046253	total: 4m 27s	remaining: 12m 30s
2514:	learn: 0.0050577	total: 4m 27s	remaining: 13m 17s
2587:	learn: 0.0041984	total: 4m 27s	remaining: 12m 47s
2404:	learn: 0.0053073	total: 4m 27s	remaining: 14m 6s
2591:	learn: 0.0050819	total: 4m 27s	remaining: 12m 45s
2631:	learn: 0.0046219	total: 4m 27s	remaining: 12m 30s
2588:	learn: 0.0041961	total: 4m 27s	remaining: 12m 46s
2515:	learn: 0.0050551	total: 4m 28s	remaining: 13m 17s
2592:	learn: 0.0050794	total: 4m 27s	remaining: 12m 45s
2405:	learn: 0.0053040	total: 4m 28s	remaining: 14m 6s
2632:	learn: 0.0046202	total: 4m 28s	remaining: 12m 29s
2589:	learn: 0.0041926	total: 4m 28s	remaining: 12m 46s
2516:	learn: 0.0050525	total: 4m 28s	remaining: 13m 17s
2593:	learn: 0.0050777	total: 4m 28s	remaining: 12m 45s
2406:	learn: 0.0053003	total: 4m 28s	remaining: 14m 6s
2633:	learn: 0.0046159	total: 4m 28s	remaining: 12m 29s
2590:	learn: 0.0041900	total: 4m 28s	remaining: 12m 46s
2517:	learn: 0.0050494	total: 4m 28s	remaining: 13m 17s
2594:	learn: 0.0050747	total: 4m 28s	remaining: 12m 45s
2407:	learn: 0.0052960	total: 4m 28s	remaining: 14m 5s
2591:	learn: 0.0041880	total: 4m 28s	remaining: 12m 46s
2634:	learn: 0.0046127	total: 4m 28s	remaining: 12m 29s
2635:	learn: 0.0046104	total: 4m 28s	remaining: 12m 29s
2518:	learn: 0.0050456	total: 4m 28s	remaining: 13m 16s
2592:	learn: 0.0041861	total: 4m 28s	remaining: 12m 46s
2408:	learn: 0.0052928	total: 4m 28s	remaining: 14m 5s
2595:	learn: 0.0050718	total: 4m 28s	remaining: 12m 45s
2519:	learn: 0.0050420	total: 4m 28s	remaining: 13m 16s
2636:	learn: 0.0046079	total: 4m 28s	remaining: 12m 29s
2593:	learn: 0.0041846	total: 4m 28s	remaining: 12m 46s
2596:	learn: 0.0050699	total: 4m 28s	remaining: 12m 44s
2409:	learn: 0.0052902	total: 4m 28s	remaining: 14m 5s
2637:	learn: 0.0046060	total: 4m 28s	remaining: 12m 29s
2594:	learn: 0.0041815	total: 4m 28s	remaining: 12m 46s
2520:	learn: 0.0050380	total: 4m 28s	remaining: 13m 16s
2597:	learn: 0.0050672	total: 4m 28s	remaining: 12m 44s
2638:	learn: 0.0046042	total: 4m 28s	remaining: 12m 29s
2595:	learn: 0.0041789	total: 4m 28s	remaining: 12m 45s
2410:	learn: 0.0052854	total: 4m 28s	remaining: 14m 5s
2598:	learn: 0.0050656	total: 4m 28s	remaining: 12m 44s
2521:	learn: 0.0050354	total: 4m 28s	remaining: 13m 16s
2596:	learn: 0.0041766	total: 4m 28s	remaining: 12m 45s
2639:	learn: 0.0046010	total: 4m 28s	remaining: 12m 29s
2599:	learn: 0.0050629	total: 4m 28s	remaining: 12m 44s
2411:	learn: 0.0052823	total: 4m 28s	remaining: 14m 5s
2522:	learn: 0.0050328	total: 4m 28s	remaining: 13m 16s
2640:	learn: 0.0045979	total: 4m 28s	remaining: 12m 28s
2597:	learn: 0.0041732	total: 4m 28s	remaining: 12m 45s
2523:	learn: 0.0050307	total: 4m 28s	remaining: 13m 16s
2600:	learn: 0.0050603	total: 4m 28s	remaining: 12m 44s
2412:	learn: 0.0052807	total: 4m 28s	remaining: 14m 5s
2641:	learn: 0.0045942	total: 4m 28s	remaining: 12m 28s
2524:	learn: 0.0050259	total: 4m 28s	remaining: 13m 16s
2598:	learn: 0.0041710	total: 4m 28s	remaining: 12m 45s
2601:	learn: 0.0050572	total: 4m 28s	remaining: 12m 44s
2642:	learn: 0.0045911	total: 4m 28s	remaining: 12m 28s
2413:	learn: 0.0052772	total: 4m 29s	remaining: 14m 5s
2599:	learn: 0.0041679	total: 4m 28s	remaining: 12m 45s
2525:	learn: 0.0050226	total: 4m 29s	remaining: 13m 16s
2602:	learn: 0.0050538	total: 4m 28s	remaining: 12m 44s
840	total: 4m 25s	remaining: 12m 33s

2491:	learn: 0.00512414:	learn: 0.0052749	total: 4m 29s	remaining: 14m 5s
2643:	learn: 0.0045868	total: 4m 29s	remaining: 12m 28s
2526:	learn: 0.0050208	total: 4m 29s	remaining: 13m 15s
2600:	learn: 0.0041663	total: 4m 29s	remaining: 12m 45s
2644:	learn: 0.0045845	total: 4m 29s	remaining: 12m 28s
2415:	learn: 0.0052727	total: 4m 29s	remaining: 14m 5s
2603:	learn: 0.0050507	total: 4m 29s	remaining: 12m 44s
2527:	learn: 0.0050165	total: 4m 29s	remaining: 13m 15s
2601:	learn: 0.0041640	total: 4m 29s	remaining: 12m 45s
2604:	learn: 0.0050484	total: 4m 29s	remaining: 12m 44s
2645:	learn: 0.0045823	total: 4m 29s	remaining: 12m 28s
2528:	learn: 0.0050133	total: 4m 29s	remaining: 13m 15s
2602:	learn: 0.0041613	total: 4m 29s	remaining: 12m 45s
2416:	learn: 0.0052687	total: 4m 29s	remaining: 14m 5s
2646:	learn: 0.0045781	total: 4m 29s	remaining: 12m 28s
2605:	learn: 0.0050459	total: 4m 29s	remaining: 12m 43s
2529:	learn: 0.0050105	total: 4m 29s	remaining: 13m 15s
2417:	learn: 0.0052659	total: 4m 29s	remaining: 14m 4s
2603:	learn: 0.0041579	total: 4m 29s	remaining: 12m 45s
2647:	learn: 0.0045749	total: 4m 29s	remaining: 12m 28s
2418:	learn: 0.0052633	total: 4m 29s	remaining: 14m 4s
2530:	learn: 0.0050083	total: 4m 29s	remaining: 13m 15s
2606:	learn: 0.0050416	total: 4m 29s	remaining: 12m 43s
2604:	learn: 0.0041558	total: 4m 29s	remaining: 12m 45s
2648:	learn: 0.0045727	total: 4m 29s	remaining: 12m 28s
2607:	learn: 0.0050398	total: 4m 29s	remaining: 12m 43s
2419:	learn: 0.0052581	total: 4m 29s	remaining: 14m 4s
2531:	learn: 0.0050066	total: 4m 29s	remaining: 13m 15s
2608:	learn: 0.0050357	total: 4m 29s	remaining: 12m 43s
2605:	learn: 0.0041536	total: 4m 29s	remaining: 12m 44s
2649:	learn: 0.0045685	total: 4m 29s	remaining: 12m 27s
2420:	learn: 0.0052548	total: 4m 29s	remaining: 14m 4s
2532:	learn: 0.0050026	total: 4m 29s	remaining: 13m 15s
2650:	learn: 0.0045668	total: 4m 29s	remaining: 12m 27s
2609:	learn: 0.0050317	total: 4m 29s	remaining: 12m 43s
2606:	learn: 0.0041515	total: 4m 29s	remaining: 12m 44s
2421:	learn: 0.0052523	total: 4m 29s	remaining: 14m 4s
2610:	learn: 0.0050295	total: 4m 29s	remaining: 12m 43s
2533:	learn: 0.0050006	total: 4m 29s	remaining: 13m 15s
2607:	learn: 0.0041492	total: 4m 29s	remaining: 12m 44s
2651:	learn: 0.0045636	total: 4m 29s	remaining: 12m 27s
2422:	learn: 0.0052495	total: 4m 29s	remaining: 14m 4s
2611:	learn: 0.0050275	total: 4m 29s	remaining: 12m 43s
2534:	learn: 0.0049977	total: 4m 29s	remaining: 13m 14s
2608:	learn: 0.0041462	total: 4m 29s	remaining: 12m 44s
2652:	learn: 0.0045610	total: 4m 29s	remaining: 12m 27s
2612:	learn: 0.0050254	total: 4m 29s	remaining: 12m 42s
2535:	learn: 0.0049948	total: 4m 30s	remaining: 13m 14s
2423:	learn: 0.0052478	total: 4m 30s	remaining: 14m 4s
2609:	learn: 0.0041441	total: 4m 30s	remaining: 12m 44s
2653:	learn: 0.0045579	total: 4m 30s	remaining: 12m 27s
2613:	learn: 0.0050208	total: 4m 29s	remaining: 12m 42s
2536:	learn: 0.0049919	total: 4m 30s	remaining: 13m 14s
2654:	learn: 0.0045546	total: 4m 30s	remaining: 12m 27s
2424:	learn: 0.0052460	total: 4m 30s	remaining: 14m 3s
2610:	learn: 0.0041415	total: 4m 30s	remaining: 12m 44s
2537:	learn: 0.0049889	total: 4m 30s	remaining: 13m 14s
2614:	learn: 0.0050189	total: 4m 30s	remaining: 12m 42s
2425:	learn: 0.0052425	total: 4m 30s	remaining: 14m 3s
2655:	learn: 0.0045517	total: 4m 30s	remaining: 12m 27s
2611:	learn: 0.0041396	total: 4m 30s	remaining: 12m 44s
2538:	learn: 0.0049871	total: 4m 30s	remaining: 13m 14s
2615:	learn: 0.0050166	total: 4m 30s	remaining: 12m 42s
2426:	learn: 0.0052409	total: 4m 30s	remaining: 14m 3s
2616:	learn: 0.0050144	total: 4m 30s	remaining: 12m 42s
2539:	learn: 0.0049833	total: 4m 30s	remaining: 13m 14s
2612:	learn: 0.0041376	total: 4m 30s	remaining: 12m 44s
2656:	learn: 0.0045489	total: 4m 30s	remaining: 12m 27s
2427:	learn: 0.0052378	total: 4m 30s	remaining: 14m 3s
2617:	learn: 0.0050122	total: 4m 30s	remaining: 12m 42s
2540:	learn: 0.0049803	total: 4m 30s	remaining: 13m 14s
2613:	learn: 0.0041351	total: 4m 30s	remaining: 12m 44s
2428:	learn: 0.0052348	total: 4m 30s	remaining: 14m 3s
2618:	learn: 0.0050111	total: 4m 30s	remaining: 12m 42s
2657:	learn: 0.0045472	total: 4m 30s	remaining: 12m 27s
2541:	learn: 0.0049774	total: 4m 30s	remaining: 13m 13s
2614:	learn: 0.0041322	total: 4m 30s	remaining: 12m 44s
2619:	learn: 0.0050071	total: 4m 30s	remaining: 12m 41s
2429:	learn: 0.0052298	total: 4m 30s	remaining: 14m 3s
2658:	learn: 0.0045443	total: 4m 30s	remaining: 12m 27s
2542:	learn: 0.0049741	total: 4m 30s	remaining: 13m 13s
2615:	learn: 0.0041300	total: 4m 30s	remaining: 12m 44s
2620:	learn: 0.0050049	total: 4m 30s	remaining: 12m 41s
2659:	learn: 0.0045415	total: 4m 30s	remaining: 12m 27s
2430:	learn: 0.0052261	total: 4m 30s	remaining: 14m 3s
2616:	learn: 0.0041266	total: 4m 30s	remaining: 12m 43s
2660:	learn: 0.0045398	total: 4m 30s	remaining: 12m 26s
2621:	learn: 0.0050009	total: 4m 30s	remaining: 12m 41s
2543:	learn: 0.0049717	total: 4m 30s	remaining: 13m 13s
2431:	learn: 0.0052219	total: 4m 30s	remaining: 14m 2s
2617:	learn: 0.0041243	total: 4m 30s	remaining: 12m 43s
2622:	learn: 0.0049997	total: 4m 30s	remaining: 12m 41s
2544:	learn: 0.0049698	total: 4m 30s	remaining: 13m 13s
2661:	learn: 0.0045374	total: 4m 30s	remaining: 12m 26s
2623:	learn: 0.0049978	total: 4m 30s	remaining: 12m 41s
2618:	learn: 0.0041219	total: 4m 30s	remaining: 12m 43s
2545:	learn: 0.0049669	total: 4m 31s	remaining: 13m 13s
2432:	learn: 0.0052191	total: 4m 31s	remaining: 14m 2s
2662:	learn: 0.0045350	total: 4m 31s	remaining: 12m 26s
2624:	learn: 0.0049967	total: 4m 30s	remaining: 12m 41s
2546:	learn: 0.0049644	total: 4m 31s	remaining: 13m 13s
2619:	learn: 0.0041190	total: 4m 31s	remaining: 12m 43s
2663:	learn: 0.0045332	total: 4m 31s	remaining: 12m 26s
2433:	learn: 0.0052152	total: 4m 31s	remaining: 14m 2s
2625:	learn: 0.0049932	total: 4m 31s	remaining: 12m 41s
2547:	learn: 0.0049622	total: 4m 31s	remaining: 13m 13s
2620:	learn: 0.0041156	total: 4m 31s	remaining: 12m 43s
2664:	learn: 0.0045302	total: 4m 31s	remaining: 12m 26s
2434:	learn: 0.0052116	total: 4m 31s	remaining: 14m 2s
2626:	learn: 0.0049896	total: 4m 31s	remaining: 12m 40s
2548:	learn: 0.0049592	total: 4m 31s	remaining: 13m 13s
2665:	learn: 0.0045282	total: 4m 31s	remaining: 12m 26s
2621:	learn: 0.0041129	total: 4m 31s	remaining: 12m 43s
2435:	learn: 0.0052085	total: 4m 31s	remaining: 14m 2s
2627:	learn: 0.0049861	total: 4m 31s	remaining: 12m 40s
2549:	learn: 0.0049572	total: 4m 31s	remaining: 13m 12s
2666:	learn: 0.0045254	total: 4m 31s	remaining: 12m 26s
2622:	learn: 0.0041104	total: 4m 31s	remaining: 12m 43s
2436:	learn: 0.0052040	total: 4m 31s	remaining: 14m 2s
2550:	learn: 0.0049541	total: 4m 31s	remaining: 13m 12s
2628:	learn: 0.0049836	total: 4m 31s	remaining: 12m 40s
2667:	learn: 0.0045213	total: 4m 31s	remaining: 12m 26s
2623:	learn: 0.0041085	total: 4m 31s	remaining: 12m 43s
2551:	learn: 0.0049511	total: 4m 31s	remaining: 13m 12s
2437:	learn: 0.0052016	total: 4m 31s	remaining: 14m 2s
2629:	learn: 0.0049821	total: 4m 31s	remaining: 12m 40s
2624:	learn: 0.0041062	total: 4m 31s	remaining: 12m 42s
2668:	learn: 0.0045183	total: 4m 31s	remaining: 12m 26s
2625:	learn: 0.0041029	total: 4m 31s	remaining: 12m 42s
2552:	learn: 0.0049482	total: 4m 31s	remaining: 13m 12s
2438:	learn: 0.0051989	total: 4m 31s	remaining: 14m 2s
2630:	learn: 0.0049788	total: 4m 31s	remaining: 12m 40s
2669:	learn: 0.0045164	total: 4m 31s	remaining: 12m 25s
2553:	learn: 0.0049451	total: 4m 31s	remaining: 13m 12s
2626:	learn: 0.0040992	total: 4m 31s	remaining: 12m 42s
2631:	learn: 0.0049758	total: 4m 31s	remaining: 12m 40s
2439:	learn: 0.0051964	total: 4m 31s	remaining: 14m 2s
2670:	learn: 0.0045146	total: 4m 31s	remaining: 12m 25s
2554:	learn: 0.0049429	total: 4m 31s	remaining: 13m 12s
2627:	learn: 0.0040971	total: 4m 31s	remaining: 12m 42s
2632:	learn: 0.0049738	total: 4m 31s	remaining: 12m 40s
2440:	learn: 0.0051919	total: 4m 31s	remaining: 14m 2s
2671:	learn: 0.0045123	total: 4m 31s	remaining: 12m 25s
2555:	learn: 0.0049392	total: 4m 31s	remaining: 13m 12s
2628:	learn: 0.0040953	total: 4m 31s	remaining: 12m 42s
2441:	learn: 0.0051871	total: 4m 32s	remaining: 14m 1s
2633:	learn: 0.0049721	total: 4m 31s	remaining: 12m 40s
2672:	learn: 0.0045090	total: 4m 32s	remaining: 12m 25s
2556:	learn: 0.0049363	total: 4m 32s	remaining: 13m 11s
2634:	learn: 0.0049687	total: 4m 31s	remaining: 12m 40s
2629:	learn: 0.0040920	total: 4m 32s	remaining: 12m 42s
2442:	learn: 0.0051824	total: 4m 32s	remaining: 14m 1s
2673:	learn: 0.0045073	total: 4m 32s	remaining: 12m 25s
2635:	learn: 0.0049655	total: 4m 32s	remaining: 12m 40s
2557:	learn: 0.0049345	total: 4m 32s	remaining: 13m 11s
2630:	learn: 0.0040894	total: 4m 32s	remaining: 12m 42s
2674:	learn: 0.0045039	total: 4m 32s	remaining: 12m 25s
2443:	learn: 0.0051792	total: 4m 32s	remaining: 14m 1s
2636:	learn: 0.0049624	total: 4m 32s	remaining: 12m 39s
2675:	learn: 0.0045010	total: 4m 32s	remaining: 12m 25s
2558:	learn: 0.0049311	total: 4m 32s	remaining: 13m 11s
2631:	learn: 0.0040873	total: 4m 32s	remaining: 12m 42s
2444:	learn: 0.0051745	total: 4m 32s	remaining: 14m 1s
2637:	learn: 0.0049589	total: 4m 32s	remaining: 12m 39s
2676:	learn: 0.0044984	total: 4m 32s	remaining: 12m 25s
2632:	learn: 0.0040850	total: 4m 32s	remaining: 12m 41s
2559:	learn: 0.0049287	total: 4m 32s	remaining: 13m 11s
2445:	learn: 0.0051711	total: 4m 32s	remaining: 14m 1s
2638:	learn: 0.0049554	total: 4m 32s	remaining: 12m 39s
2677:	learn: 0.0044968	total: 4m 32s	remaining: 12m 24s
2633:	learn: 0.0040823	total: 4m 32s	remaining: 12m 41s
2446:	learn: 0.0051672	total: 4m 32s	remaining: 14m 1s
2639:	learn: 0.0049510	total: 4m 32s	remaining: 12m 39s
2560:	learn: 0.0049266	total: 4m 32s	remaining: 13m 11s
2678:	learn: 0.0044952	total: 4m 32s	remaining: 12m 24s
2640:	learn: 0.0049488	total: 4m 32s	remaining: 12m 39s
2634:	learn: 0.0040801	total: 4m 32s	remaining: 12m 41s
2447:	learn: 0.0051629	total: 4m 32s	remaining: 14m 1s
2561:	learn: 0.0049243	total: 4m 32s	remaining: 13m 11s
2679:	learn: 0.0044915	total: 4m 32s	remaining: 12m 24s
2641:	learn: 0.0049471	total: 4m 32s	remaining: 12m 39s
2635:	learn: 0.0040783	total: 4m 32s	remaining: 12m 41s
2642:	learn: 0.0049447	total: 4m 32s	remaining: 12m 38s
2448:	learn: 0.0051595	total: 4m 32s	remaining: 14m 1s
2680:	learn: 0.0044889	total: 4m 32s	remaining: 12m 24s
2562:	learn: 0.0049191	total: 4m 32s	remaining: 13m 11s
2636:	learn: 0.0040766	total: 4m 32s	remaining: 12m 41s
2681:	learn: 0.0044869	total: 4m 32s	remaining: 12m 24s
2449:	learn: 0.0051561	total: 4m 32s	remaining: 14m
2643:	learn: 0.0049404	total: 4m 32s	remaining: 12m 38s
2563:	learn: 0.0049165	total: 4m 32s	remaining: 13m 11s
2637:	learn: 0.0040748	total: 4m 32s	remaining: 12m 41s
2682:	learn: 0.0044840	total: 4m 32s	remaining: 12m 24s
2450:	learn: 0.0051520	total: 4m 32s	remaining: 14m
2644:	learn: 0.0049383	total: 4m 32s	remaining: 12m 38s
2638:	learn: 0.0040724	total: 4m 32s	remaining: 12m 41s
2564:	learn: 0.0049148	total: 4m 33s	remaining: 13m 11s
2451:	learn: 0.0051481	total: 4m 33s	remaining: 14m
2683:	learn: 0.0044822	total: 4m 33s	remaining: 12m 24s
2645:	learn: 0.0049352	total: 4m 32s	remaining: 12m 38s
2565:	learn: 0.0049121	total: 4m 33s	remaining: 13m 11s
2639:	learn: 0.0040696	total: 4m 33s	remaining: 12m 41s
2684:	learn: 0.0044791	total: 4m 33s	remaining: 12m 24s
2452:	learn: 0.0051453	total: 4m 33s	remaining: 14m
2646:	learn: 0.0049330	total: 4m 33s	remaining: 12m 38s
2566:	learn: 0.0049095	total: 4m 33s	remaining: 13m 11s
2640:	learn: 0.0040672	total: 4m 33s	remaining: 12m 41s
2453:	learn: 0.0051414	total: 4m 33s	remaining: 14m
2685:	learn: 0.0044773	total: 4m 33s	remaining: 12m 24s
2647:	learn: 0.0049312	total: 4m 33s	remaining: 12m 38s
2567:	learn: 0.0049064	total: 4m 33s	remaining: 13m 11s
2641:	learn: 0.0040648	total: 4m 33s	remaining: 12m 41s
2454:	learn: 0.0051384	total: 4m 33s	remaining: 14m
2686:	learn: 0.0044758	total: 4m 33s	remaining: 12m 23s
2568:	learn: 0.0049038	total: 4m 33s	remaining: 13m 10s
2642:	learn: 0.0040622	total: 4m 33s	remaining: 12m 40s
2648:	learn: 0.0049283	total: 4m 33s	remaining: 12m 38s
2687:	learn: 0.0044730	total: 4m 33s	remaining: 12m 23s
2455:	learn: 0.0051351	total: 4m 33s	remaining: 14m
2649:	learn: 0.0049262	total: 4m 33s	remaining: 12m 38s
2643:	learn: 0.0040596	total: 4m 33s	remaining: 12m 40s
2688:	learn: 0.0044697	total: 4m 33s	remaining: 12m 23s
2569:	learn: 0.0049006	total: 4m 33s	remaining: 13m 10s
2644:	learn: 0.0040559	total: 4m 33s	remaining: 12m 40s
2689:	learn: 0.0044671	total: 4m 33s	remaining: 12m 23s
2650:	learn: 0.0049237	total: 4m 33s	remaining: 12m 38s
2456:	learn: 0.0051327	total: 4m 33s	remaining: 14m
2690:	learn: 0.0044629	total: 4m 33s	remaining: 12m 23s
2570:	learn: 0.0048985	total: 4m 33s	remaining: 13m 10s
2645:	learn: 0.0040538	total: 4m 33s	remaining: 12m 40s
2651:	learn: 0.0049216	total: 4m 33s	remaining: 12m 38s
2457:	learn: 0.0051292	total: 4m 33s	remaining: 13m 59s
2691:	learn: 0.0044606	total: 4m 33s	remaining: 12m 23s
2646:	learn: 0.0040510	total: 4m 33s	remaining: 12m 40s
2571:	learn: 0.0048969	total: 4m 33s	remaining: 13m 10s
2652:	learn: 0.0049175	total: 4m 33s	remaining: 12m 37s
2458:	learn: 0.0051266	total: 4m 33s	remaining: 13m 59s
2692:	learn: 0.0044590	total: 4m 33s	remaining: 12m 22s
2647:	learn: 0.0040485	total: 4m 33s	remaining: 12m 40s
2653:	learn: 0.0049149	total: 4m 33s	remaining: 12m 37s
2572:	learn: 0.0048938	total: 4m 33s	remaining: 13m 10s
2459:	learn: 0.0051234	total: 4m 33s	remaining: 13m 59s
2693:	learn: 0.0044564	total: 4m 33s	remaining: 12m 22s
2654:	learn: 0.0049138	total: 4m 33s	remaining: 12m 37s
2648:	learn: 0.0040459	total: 4m 33s	remaining: 12m 40s
2694:	learn: 0.0044532	total: 4m 34s	remaining: 12m 22s
2573:	learn: 0.0048894	total: 4m 34s	remaining: 13m 10s
2460:	learn: 0.0051196	total: 4m 34s	remaining: 13m 59s
2649:	learn: 0.0040438	total: 4m 34s	remaining: 12m 40s
2655:	learn: 0.0049112	total: 4m 33s	remaining: 12m 37s
2695:	learn: 0.0044509	total: 4m 34s	remaining: 12m 22s
2574:	learn: 0.0048878	total: 4m 34s	remaining: 13m 10s
2461:	learn: 0.0051161	total: 4m 34s	remaining: 13m 59s
2650:	learn: 0.0040417	total: 4m 34s	remaining: 12m 39s
2656:	learn: 0.0049101	total: 4m 34s	remaining: 12m 37s
2696:	learn: 0.0044480	total: 4m 34s	remaining: 12m 22s
2575:	learn: 0.0048845	total: 4m 34s	remaining: 13m 10s
2651:	learn: 0.0040396	total: 4m 34s	remaining: 12m 39s
2462:	learn: 0.0051128	total: 4m 34s	remaining: 13m 59s
2657:	learn: 0.0049084	total: 4m 34s	remaining: 12m 37s
2697:	learn: 0.0044449	total: 4m 34s	remaining: 12m 22s
2652:	learn: 0.0040368	total: 4m 34s	remaining: 12m 39s
2576:	learn: 0.0048817	total: 4m 34s	remaining: 13m 10s
2463:	learn: 0.0051100	total: 4m 34s	remaining: 13m 59s
2698:	learn: 0.0044431	total: 4m 34s	remaining: 12m 22s
2658:	learn: 0.0049073	total: 4m 34s	remaining: 12m 37s
2464:	learn: 0.0051068	total: 4m 34s	remaining: 13m 58s
2653:	learn: 0.0040349	total: 4m 34s	remaining: 12m 39s
2577:	learn: 0.0048789	total: 4m 34s	remaining: 13m 10s
2465:	learn: 0.0051037	total: 4m 34s	remaining: 13m 58s
2699:	learn: 0.0044398	total: 4m 34s	remaining: 12m 22s
2659:	learn: 0.0049050	total: 4m 34s	remaining: 12m 37s
2654:	learn: 0.0040321	total: 4m 34s	remaining: 12m 39s
2578:	learn: 0.0048765	total: 4m 34s	remaining: 13m 10s
2660:	learn: 0.0049016	total: 4m 34s	remaining: 12m 36s
2700:	learn: 0.0044376	total: 4m 34s	remaining: 12m 21s
2466:	learn: 0.0051011	total: 4m 34s	remaining: 13m 58s
2579:	learn: 0.0048726	total: 4m 34s	remaining: 13m 10s
2661:	learn: 0.0048992	total: 4m 34s	remaining: 12m 36s
2655:	learn: 0.0040288	total: 4m 34s	remaining: 12m 39s
2701:	learn: 0.0044352	total: 4m 34s	remaining: 12m 21s
2467:	learn: 0.0050972	total: 4m 34s	remaining: 13m 58s
2580:	learn: 0.0048694	total: 4m 34s	remaining: 13m 9s
2662:	learn: 0.0048967	total: 4m 34s	remaining: 12m 36s
2656:	learn: 0.0040265	total: 4m 34s	remaining: 12m 39s
2702:	learn: 0.0044335	total: 4m 34s	remaining: 12m 21s
2468:	learn: 0.0050934	total: 4m 34s	remaining: 13m 58s
2581:	learn: 0.0048665	total: 4m 34s	remaining: 13m 9s
2663:	learn: 0.0048930	total: 4m 34s	remaining: 12m 36s
2703:	learn: 0.0044308	total: 4m 34s	remaining: 12m 21s
2657:	learn: 0.0040239	total: 4m 34s	remaining: 12m 39s
2469:	learn: 0.0050892	total: 4m 34s	remaining: 13m 58s
2582:	learn: 0.0048637	total: 4m 34s	remaining: 13m 9s

2664:	learn: 0.0048889	total: 4m 34s	remaining: 12m 36s
2704:	learn: 0.0044280	total: 4m 34s	remaining: 12m 21s
2658:	learn: 0.0040202	total: 4m 34s	remaining: 12m 39s
2470:	learn: 0.0050855	total: 4m 35s	remaining: 13m 58s
2583:	learn: 0.0048610	total: 4m 35s	remaining: 13m 9s
2665:	learn: 0.0048865	total: 4m 34s	remaining: 12m 36s
2705:	learn: 0.0044257	total: 4m 35s	remaining: 12m 21s
2471:	learn: 0.0050825	total: 4m 35s	remaining: 13m 57s
2659:	learn: 0.0040175	total: 4m 35s	remaining: 12m 39s
2666:	learn: 0.0048840	total: 4m 35s	remaining: 12m 36s
2584:	learn: 0.0048591	total: 4m 35s	remaining: 13m 9s
2706:	learn: 0.0044218	total: 4m 35s	remaining: 12m 21s
2472:	learn: 0.0050797	total: 4m 35s	remaining: 13m 57s
2660:	learn: 0.0040153	total: 4m 35s	remaining: 12m 38s
2667:	learn: 0.0048810	total: 4m 35s	remaining: 12m 36s
2585:	learn: 0.0048574	total: 4m 35s	remaining: 13m 9s
2473:	learn: 0.0050771	total: 4m 35s	remaining: 13m 57s
2707:	learn: 0.0044182	total: 4m 35s	remaining: 12m 21s
2661:	learn: 0.0040129	total: 4m 35s	remaining: 12m 38s
2668:	learn: 0.0048794	total: 4m 35s	remaining: 12m 36s
2586:	learn: 0.0048545	total: 4m 35s	remaining: 13m 9s
2474:	learn: 0.0050744	total: 4m 35s	remaining: 13m 57s
2662:	learn: 0.0040094	total: 4m 35s	remaining: 12m 38s
2708:	learn: 0.0044159	total: 4m 35s	remaining: 12m 21s
2669:	learn: 0.0048769	total: 4m 35s	remaining: 12m 35s
2587:	learn: 0.0048523	total: 4m 35s	remaining: 13m 9s
2475:	learn: 0.0050709	total: 4m 35s	remaining: 13m 57s
2663:	learn: 0.0040071	total: 4m 35s	remaining: 12m 38s
2709:	learn: 0.0044123	total: 4m 35s	remaining: 12m 21s
2670:	learn: 0.0048739	total: 4m 35s	remaining: 12m 35s
2588:	learn: 0.0048503	total: 4m 35s	remaining: 13m 8s
2664:	learn: 0.0040043	total: 4m 35s	remaining: 12m 38s
2476:	learn: 0.0050678	total: 4m 35s	remaining: 13m 57s
2710:	learn: 0.0044098	total: 4m 35s	remaining: 12m 21s
2671:	learn: 0.0048715	total: 4m 35s	remaining: 12m 35s
2665:	learn: 0.0040016	total: 4m 35s	remaining: 12m 38s
2589:	learn: 0.0048484	total: 4m 35s	remaining: 13m 8s
2477:	learn: 0.0050627	total: 4m 35s	remaining: 13m 57s
2711:	learn: 0.0044081	total: 4m 35s	remaining: 12m 20s
2666:	learn: 0.0039990	total: 4m 35s	remaining: 12m 38s
2672:	learn: 0.0048675	total: 4m 35s	remaining: 12m 35s
2590:	learn: 0.0048460	total: 4m 35s	remaining: 13m 8s
2712:	learn: 0.0044062	total: 4m 35s	remaining: 12m 20s
2478:	learn: 0.0050591	total: 4m 35s	remaining: 13m 56s
2667:	learn: 0.0039972	total: 4m 35s	remaining: 12m 37s
2591:	learn: 0.0048430	total: 4m 35s	remaining: 13m 8s
2673:	learn: 0.0048648	total: 4m 35s	remaining: 12m 35s
2713:	learn: 0.0044040	total: 4m 35s	remaining: 12m 20s
2668:	learn: 0.0039947	total: 4m 35s	remaining: 12m 37s
2479:	learn: 0.0050565	total: 4m 35s	remaining: 13m 56s
2674:	learn: 0.0048611	total: 4m 35s	remaining: 12m 35s
2714:	learn: 0.0044006	total: 4m 35s	remaining: 12m 20s
2592:	learn: 0.0048412	total: 4m 36s	remaining: 13m 8s
2669:	learn: 0.0039928	total: 4m 36s	remaining: 12m 37s
2675:	learn: 0.0048600	total: 4m 35s	remaining: 12m 35s
2715:	learn: 0.0043976	total: 4m 36s	remaining: 12m 20s
2480:	learn: 0.0050525	total: 4m 36s	remaining: 13m 56s
2593:	learn: 0.0048393	total: 4m 36s	remaining: 13m 8s
2676:	learn: 0.0048580	total: 4m 36s	remaining: 12m 35s
2670:	learn: 0.0039905	total: 4m 36s	remaining: 12m 37s
2716:	learn: 0.0043960	total: 4m 36s	remaining: 12m 20s
2481:	learn: 0.0050490	total: 4m 36s	remaining: 13m 56s
2677:	learn: 0.0048543	total: 4m 36s	remaining: 12m 34s
2594:	learn: 0.0048376	total: 4m 36s	remaining: 13m 8s
2671:	learn: 0.0039872	total: 4m 36s	remaining: 12m 37s
2717:	learn: 0.0043942	total: 4m 36s	remaining: 12m 20s
2678:	learn: 0.0048511	total: 4m 36s	remaining: 12m 34s
2595:	learn: 0.0048352	total: 4m 36s	remaining: 13m 8s
2482:	learn: 0.0050460	total: 4m 36s	remaining: 13m 56s
2672:	learn: 0.0039841	total: 4m 36s	remaining: 12m 37s
2718:	learn: 0.0043925	total: 4m 36s	remaining: 12m 20s
2679:	learn: 0.0048479	total: 4m 36s	remaining: 12m 34s
2596:	learn: 0.0048325	total: 4m 36s	remaining: 13m 7s
2673:	learn: 0.0039806	total: 4m 36s	remaining: 12m 37s
2483:	learn: 0.0050422	total: 4m 36s	remaining: 13m 56s
2719:	learn: 0.0043900	total: 4m 36s	remaining: 12m 19s
2680:	learn: 0.0048441	total: 4m 36s	remaining: 12m 34s
2597:	learn: 0.0048289	total: 4m 36s	remaining: 13m 7s
2674:	learn: 0.0039789	total: 4m 36s	remaining: 12m 37s
2720:	learn: 0.0043878	total: 4m 36s	remaining: 12m 19s
2484:	learn: 0.0050370	total: 4m 36s	remaining: 13m 56s
2681:	learn: 0.0048418	total: 4m 36s	remaining: 12m 34s
2598:	learn: 0.0048252	total: 4m 36s	remaining: 13m 7s
2675:	learn: 0.0039769	total: 4m 36s	remaining: 12m 37s
2682:	learn: 0.0048396	total: 4m 36s	remaining: 12m 34s
2485:	learn: 0.0050360	total: 4m 36s	remaining: 13m 56s
2721:	learn: 0.0043840	total: 4m 36s	remaining: 12m 19s
2599:	learn: 0.0048231	total: 4m 36s	remaining: 13m 7s
2683:	learn: 0.0048372	total: 4m 36s	remaining: 12m 34s
2676:	learn: 0.0039745	total: 4m 36s	remaining: 12m 36s
2722:	learn: 0.0043809	total: 4m 36s	remaining: 12m 19s
2486:	learn: 0.0050314	total: 4m 36s	remaining: 13m 56s
2600:	learn: 0.0048208	total: 4m 36s	remaining: 13m 7s
2677:	learn: 0.0039724	total: 4m 36s	remaining: 12m 36s
2684:	learn: 0.0048345	total: 4m 36s	remaining: 12m 33s
2723:	learn: 0.0043790	total: 4m 36s	remaining: 12m 19s
2487:	learn: 0.0050283	total: 4m 36s	remaining: 13m 56s
2678:	learn: 0.0039700	total: 4m 36s	remaining: 12m 36s
2685:	learn: 0.0048313	total: 4m 36s	remaining: 12m 33s
2601:	learn: 0.0048178	total: 4m 36s	remaining: 13m 7s
2724:	learn: 0.0043758	total: 4m 36s	remaining: 12m 19s
2488:	learn: 0.0050249	total: 4m 37s	remaining: 13m 56s
2679:	learn: 0.0039683	total: 4m 36s	remaining: 12m 36s
2686:	learn: 0.0048283	total: 4m 36s	remaining: 12m 33s
2602:	learn: 0.0048162	total: 4m 37s	remaining: 13m 7s
2725:	learn: 0.0043742	total: 4m 37s	remaining: 12m 19s
2680:	learn: 0.0039657	total: 4m 37s	remaining: 12m 36s
2489:	learn: 0.0050200	total: 4m 37s	remaining: 13m 55s
2687:	learn: 0.0048251	total: 4m 37s	remaining: 12m 33s
2603:	learn: 0.0048135	total: 4m 37s	remaining: 13m 7s
2688:	learn: 0.0048221	total: 4m 37s	remaining: 12m 33s
2681:	learn: 0.0039612	total: 4m 37s	remaining: 12m 36s
2726:	learn: 0.0043714	total: 4m 37s	remaining: 12m 19s
2490:	learn: 0.0050163	total: 4m 37s	remaining: 13m 55s
2604:	learn: 0.0048116	total: 4m 37s	remaining: 13m 7s
2689:	learn: 0.0048182	total: 4m 37s	remaining: 12m 33s
2727:	learn: 0.0043692	total: 4m 37s	remaining: 12m 19s
2491:	learn: 0.0050138	total: 4m 37s	remaining: 13m 55s
2682:	learn: 0.0039592	total: 4m 37s	remaining: 12m 36s
2605:	learn: 0.0048096	total: 4m 37s	remaining: 13m 6s
2690:	learn: 0.0048155	total: 4m 37s	remaining: 12m 33s
2728:	learn: 0.0043667	total: 4m 37s	remaining: 12m 19s
2606:	learn: 0.0048077	total: 4m 37s	remaining: 13m 6s
2683:	learn: 0.0039574	total: 4m 37s	remaining: 12m 36s
2691:	learn: 0.0048123	total: 4m 37s	remaining: 12m 32s
2492:	learn: 0.0050110	total: 4m 37s	remaining: 13m 55s
2729:	learn: 0.0043636	total: 4m 37s	remaining: 12m 18s
2607:	learn: 0.0048042	total: 4m 37s	remaining: 13m 6s
2692:	learn: 0.0048090	total: 4m 37s	remaining: 12m 32s
2684:	learn: 0.0039556	total: 4m 37s	remaining: 12m 36s
2493:	learn: 0.0050079	total: 4m 37s	remaining: 13m 55s
2730:	learn: 0.0043603	total: 4m 37s	remaining: 12m 18s
2693:	learn: 0.0048059	total: 4m 37s	remaining: 12m 32s
2685:	learn: 0.0039540	total: 4m 37s	remaining: 12m 35s
2608:	learn: 0.0048008	total: 4m 37s	remaining: 13m 6s
2494:	learn: 0.0050041	total: 4m 37s	remaining: 13m 55s
2731:	learn: 0.0043581	total: 4m 37s	remaining: 12m 18s
2686:	learn: 0.0039520	total: 4m 37s	remaining: 12m 35s
2694:	learn: 0.0048027	total: 4m 37s	remaining: 12m 32s
2732:	learn: 0.0043562	total: 4m 37s	remaining: 12m 18s
2609:	learn: 0.0047979	total: 4m 37s	remaining: 13m 6s
2495:	learn: 0.0050006	total: 4m 37s	remaining: 13m 55s
2687:	learn: 0.0039496	total: 4m 37s	remaining: 12m 35s
2695:	learn: 0.0047990	total: 4m 37s	remaining: 12m 32s
2610:	learn: 0.0047958	total: 4m 37s	remaining: 13m 6s
2696:	learn: 0.0047944	total: 4m 37s	remaining: 12m 32s
2733:	learn: 0.0043545	total: 4m 37s	remaining: 12m 18s
2496:	learn: 0.0049969	total: 4m 37s	remaining: 13m 55s
2688:	learn: 0.0039475	total: 4m 37s	remaining: 12m 35s
2734:	learn: 0.0043532	total: 4m 37s	remaining: 12m 18s
2697:	learn: 0.0047918	total: 4m 37s	remaining: 12m 32s
2611:	learn: 0.0047923	total: 4m 38s	remaining: 13m 6s
2497:	learn: 0.0049932	total: 4m 38s	remaining: 13m 55s
2689:	learn: 0.0039455	total: 4m 38s	remaining: 12m 35s
2698:	learn: 0.0047877	total: 4m 37s	remaining: 12m 31s
2735:	learn: 0.0043500	total: 4m 38s	remaining: 12m 18s
2498:	learn: 0.0049917	total: 4m 38s	remaining: 13m 54s
2612:	learn: 0.0047901	total: 4m 38s	remaining: 13m 6s
2690:	learn: 0.0039437	total: 4m 38s	remaining: 12m 35s
2699:	learn: 0.0047839	total: 4m 38s	remaining: 12m 31s
2736:	learn: 0.0043465	total: 4m 38s	remaining: 12m 18s
2499:	learn: 0.0049889	total: 4m 38s	remaining: 13m 54s
2613:	learn: 0.0047885	total: 4m 38s	remaining: 13m 6s
2691:	learn: 0.0039406	total: 4m 38s	remaining: 12m 35s
2737:	learn: 0.0043441	total: 4m 38s	remaining: 12m 18s
2700:	learn: 0.0047800	total: 4m 38s	remaining: 12m 31s
2614:	learn: 0.0047856	total: 4m 38s	remaining: 13m 5s
2500:	learn: 0.0049848	total: 4m 38s	remaining: 13m 54s
2692:	learn: 0.0039389	total: 4m 38s	remaining: 12m 35s
2738:	learn: 0.0043414	total: 4m 38s	remaining: 12m 17s
2701:	learn: 0.0047783	total: 4m 38s	remaining: 12m 31s
2615:	learn: 0.0047830	total: 4m 38s	remaining: 13m 5s
2501:	learn: 0.0049817	total: 4m 38s	remaining: 13m 54s
2693:	learn: 0.0039365	total: 4m 38s	remaining: 12m 35s
2739:	learn: 0.0043401	total: 4m 38s	remaining: 12m 17s
2702:	learn: 0.0047765	total: 4m 38s	remaining: 12m 31s
2616:	learn: 0.0047803	total: 4m 38s	remaining: 13m 5s
2502:	learn: 0.0049802	total: 4m 38s	remaining: 13m 54s
2694:	learn: 0.0039346	total: 4m 38s	remaining: 12m 34s
2740:	learn: 0.0043380	total: 4m 38s	remaining: 12m 17s
2703:	learn: 0.0047733	total: 4m 38s	remaining: 12m 31s
2503:	learn: 0.0049771	total: 4m 38s	remaining: 13m 54s
2617:	learn: 0.0047768	total: 4m 38s	remaining: 13m 5s
2695:	learn: 0.0039323	total: 4m 38s	remaining: 12m 34s
2741:	learn: 0.0043354	total: 4m 38s	remaining: 12m 17s
2618:	learn: 0.0047747	total: 4m 38s	remaining: 13m 5s
2704:	learn: 0.0047703	total: 4m 38s	remaining: 12m 31s
2504:	learn: 0.0049723	total: 4m 38s	remaining: 13m 54s
2696:	learn: 0.0039300	total: 4m 38s	remaining: 12m 34s
2619:	learn: 0.0047704	total: 4m 38s	remaining: 13m 5s
2742:	learn: 0.0043328	total: 4m 38s	remaining: 12m 17s
2705:	learn: 0.0047675	total: 4m 38s	remaining: 12m 31s
2620:	learn: 0.0047680	total: 4m 38s	remaining: 13m 5s
2505:	learn: 0.0049691	total: 4m 38s	remaining: 13m 53s
2697:	learn: 0.0039276	total: 4m 38s	remaining: 12m 34s
2743:	learn: 0.0043311	total: 4m 38s	remaining: 12m 17s
2706:	learn: 0.0047654	total: 4m 38s	remaining: 12m 31s
2744:	learn: 0.0043295	total: 4m 38s	remaining: 12m 17s
2506:	learn: 0.0049662	total: 4m 38s	remaining: 13m 53s
2698:	learn: 0.0039258	total: 4m 38s	remaining: 12m 34s
2621:	learn: 0.0047664	total: 4m 39s	remaining: 13m 5s
2707:	learn: 0.0047623	total: 4m 38s	remaining: 12m 31s
2507:	learn: 0.0049633	total: 4m 39s	remaining: 13m 53s
2745:	learn: 0.0043267	total: 4m 39s	remaining: 12m 17s
2699:	learn: 0.0039236	total: 4m 39s	remaining: 12m 34s
2622:	learn: 0.0047635	total: 4m 39s	remaining: 13m 4s
2508:	learn: 0.0049601	total: 4m 39s	remaining: 13m 53s
2708:	learn: 0.0047600	total: 4m 39s	remaining: 12m 30s
2700:	learn: 0.0039211	total: 4m 39s	remaining: 12m 34s
2746:	learn: 0.0043252	total: 4m 39s	remaining: 12m 17s
2623:	learn: 0.0047608	total: 4m 39s	remaining: 13m 4s
2709:	learn: 0.0047568	total: 4m 39s	remaining: 12m 30s
2701:	learn: 0.0039193	total: 4m 39s	remaining: 12m 34s
2509:	learn: 0.0049574	total: 4m 39s	remaining: 13m 53s
2747:	learn: 0.0043228	total: 4m 39s	remaining: 12m 16s
2624:	learn: 0.0047589	total: 4m 39s	remaining: 13m 4s
2710:	learn: 0.0047530	total: 4m 39s	remaining: 12m 30s
2748:	learn: 0.0043197	total: 4m 39s	remaining: 12m 16s
2702:	learn: 0.0039163	total: 4m 39s	remaining: 12m 34s
2625:	learn: 0.0047562	total: 4m 39s	remaining: 13m 4s
2510:	learn: 0.0049546	total: 4m 39s	remaining: 13m 53s
2711:	learn: 0.0047500	total: 4m 39s	remaining: 12m 30s
2749:	learn: 0.0043181	total: 4m 39s	remaining: 12m 16s
2703:	learn: 0.0039141	total: 4m 39s	remaining: 12m 34s
2511:	learn: 0.0049518	total: 4m 39s	remaining: 13m 53s
2626:	learn: 0.0047527	total: 4m 39s	remaining: 13m 4s
2712:	learn: 0.0047468	total: 4m 39s	remaining: 12m 30s
2750:	learn: 0.0043153	total: 4m 39s	remaining: 12m 16s
2751:	learn: 0.0043130	total: 4m 39s	remaining: 12m 16s
2627:	learn: 0.0047510	total: 4m 39s	remaining: 13m 4s
2704:	learn: 0.0039105	total: 4m 39s	remaining: 12m 33s
2713:	learn: 0.0047438	total: 4m 39s	remaining: 12m 30s
2512:	learn: 0.0049487	total: 4m 39s	remaining: 13m 53s
2752:	learn: 0.0043105	total: 4m 39s	remaining: 12m 16s
2628:	learn: 0.0047493	total: 4m 39s	remaining: 13m 4s
2705:	learn: 0.0039088	total: 4m 39s	remaining: 12m 33s
2753:	learn: 0.0043089	total: 4m 39s	remaining: 12m 15s
2714:	learn: 0.0047398	total: 4m 39s	remaining: 12m 30s
2513:	learn: 0.0049456	total: 4m 39s	remaining: 13m 53s
2754:	learn: 0.0043068	total: 4m 39s	remaining: 12m 15s
2706:	learn: 0.0039063	total: 4m 39s	remaining: 12m 33s
2629:	learn: 0.0047453	total: 4m 39s	remaining: 13m 4s
2715:	learn: 0.0047367	total: 4m 39s	remaining: 12m 30s
2755:	learn: 0.0043039	total: 4m 39s	remaining: 12m 15s
2514:	learn: 0.0049421	total: 4m 39s	remaining: 13m 53s
2707:	learn: 0.0039038	total: 4m 39s	remaining: 12m 33s
2630:	learn: 0.0047425	total: 4m 39s	remaining: 13m 4s
2756:	learn: 0.0043014	total: 4m 39s	remaining: 12m 15s
2716:	learn: 0.0047337	total: 4m 39s	remaining: 12m 30s
2708:	learn: 0.0039020	total: 4m 39s	remaining: 12m 33s
2515:	learn: 0.0049388	total: 4m 40s	remaining: 13m 52s
2631:	learn: 0.0047405	total: 4m 40s	remaining: 13m 3s
2757:	learn: 0.0042986	total: 4m 40s	remaining: 12m 15s
2717:	learn: 0.0047311	total: 4m 39s	remaining: 12m 30s
2709:	learn: 0.0038996	total: 4m 40s	remaining: 12m 33s
2516:	learn: 0.0049361	total: 4m 40s	remaining: 13m 52s
2758:	learn: 0.0042966	total: 4m 40s	remaining: 12m 15s
2632:	learn: 0.0047372	total: 4m 40s	remaining: 13m 3s
2517:	learn: 0.0049338	total: 4m 40s	remaining: 13m 52s
2718:	learn: 0.0047282	total: 4m 40s	remaining: 12m 29s
2710:	learn: 0.0038971	total: 4m 40s	remaining: 12m 33s
2759:	learn: 0.0042942	total: 4m 40s	remaining: 12m 15s
2633:	learn: 0.0047353	total: 4m 40s	remaining: 13m 3s
2518:	learn: 0.0049318	total: 4m 40s	remaining: 13m 52s
2711:	learn: 0.0038949	total: 4m 40s	remaining: 12m 33s
2719:	learn: 0.0047254	total: 4m 40s	remaining: 12m 29s
2634:	learn: 0.0047329	total: 4m 40s	remaining: 13m 3s
2760:	learn: 0.0042914	total: 4m 40s	remaining: 12m 15s
2519:	learn: 0.0049280	total: 4m 40s	remaining: 13m 52s
2712:	learn: 0.0038915	total: 4m 40s	remaining: 12m 33s
2720:	learn: 0.0047216	total: 4m 40s	remaining: 12m 29s
2635:	learn: 0.0047291	total: 4m 40s	remaining: 13m 3s
2761:	learn: 0.0042887	total: 4m 40s	remaining: 12m 14s
2520:	learn: 0.0049257	total: 4m 40s	remaining: 13m 52s
2713:	learn: 0.0038898	total: 4m 40s	remaining: 12m 32s
2721:	learn: 0.0047188	total: 4m 40s	remaining: 12m 29s
2636:	learn: 0.0047264	total: 4m 40s	remaining: 13m 3s
2762:	learn: 0.0042874	total: 4m 40s	remaining: 12m 14s
2521:	learn: 0.0049226	total: 4m 40s	remaining: 13m 51s
2714:	learn: 0.0038879	total: 4m 40s	remaining: 12m 32s
2722:	learn: 0.0047149	total: 4m 40s	remaining: 12m 29s
2637:	learn: 0.0047235	total: 4m 40s	remaining: 13m 3s
2522:	learn: 0.0049192	total: 4m 40s	remaining: 13m 51s
2763:	learn: 0.0042842	total: 4m 40s	remaining: 12m 14s
2715:	learn: 0.0038858	total: 4m 40s	remaining: 12m 32s
2723:	learn: 0.0047109	total: 4m 40s	remaining: 12m 29s
2764:	learn: 0.0042819	total: 4m 40s	remaining: 12m 14s
2638:	learn: 0.0047210	total: 4m 40s	remaining: 13m 3s
2523:	learn: 0.0049171	total: 4m 40s	remaining: 13m 51s
2724:	learn: 0.0047078	total: 4m 40s	remaining: 12m 29s
2716:	learn: 0.0038824	total: 4m 40s	remaining: 12m 32s
2765:	learn: 0.0042784	total: 4m 40s	remaining: 12m 14s

2725:	learn: 0.0047049	total: 4m 40s	remaining: 12m 29s
2639:	learn: 0.0047180	total: 4m 40s	remaining: 13m 3s
2524:	learn: 0.0049148	total: 4m 40s	remaining: 13m 51s
2717:	learn: 0.0038806	total: 4m 40s	remaining: 12m 32s
2766:	learn: 0.0042758	total: 4m 40s	remaining: 12m 14s
2525:	learn: 0.0049120	total: 4m 40s	remaining: 13m 51s
2718:	learn: 0.0038778	total: 4m 40s	remaining: 12m 32s
2726:	learn: 0.0047020	total: 4m 40s	remaining: 12m 29s
2640:	learn: 0.0047148	total: 4m 41s	remaining: 13m 3s
2767:	learn: 0.0042745	total: 4m 41s	remaining: 12m 14s
2727:	learn: 0.0046989	total: 4m 40s	remaining: 12m 28s
2719:	learn: 0.0038761	total: 4m 41s	remaining: 12m 32s
2526:	learn: 0.0049085	total: 4m 41s	remaining: 13m 51s
2641:	learn: 0.0047126	total: 4m 41s	remaining: 13m 2s
2768:	learn: 0.0042732	total: 4m 41s	remaining: 12m 14s
2728:	learn: 0.0046947	total: 4m 41s	remaining: 12m 28s
2527:	learn: 0.0049057	total: 4m 41s	remaining: 13m 51s
2642:	learn: 0.0047108	total: 4m 41s	remaining: 13m 2s
2720:	learn: 0.0038741	total: 4m 41s	remaining: 12m 32s
2769:	learn: 0.0042720	total: 4m 41s	remaining: 12m 14s
2729:	learn: 0.0046918	total: 4m 41s	remaining: 12m 28s
2528:	learn: 0.0049026	total: 4m 41s	remaining: 13m 51s
2721:	learn: 0.0038725	total: 4m 41s	remaining: 12m 32s
2643:	learn: 0.0047092	total: 4m 41s	remaining: 13m 2s
2770:	learn: 0.0042697	total: 4m 41s	remaining: 12m 13s
2730:	learn: 0.0046888	total: 4m 41s	remaining: 12m 28s
2529:	learn: 0.0048998	total: 4m 41s	remaining: 13m 50s
2644:	learn: 0.0047059	total: 4m 41s	remaining: 13m 2s
2722:	learn: 0.0038709	total: 4m 41s	remaining: 12m 31s
2771:	learn: 0.0042677	total: 4m 41s	remaining: 12m 13s
2731:	learn: 0.0046858	total: 4m 41s	remaining: 12m 28s
2645:	learn: 0.0047024	total: 4m 41s	remaining: 13m 2s
2530:	learn: 0.0048978	total: 4m 41s	remaining: 13m 50s
2723:	learn: 0.0038687	total: 4m 41s	remaining: 12m 31s
2772:	learn: 0.0042666	total: 4m 41s	remaining: 12m 13s
2732:	learn: 0.0046820	total: 4m 41s	remaining: 12m 28s
2646:	learn: 0.0046998	total: 4m 41s	remaining: 13m 2s
2531:	learn: 0.0048968	total: 4m 41s	remaining: 13m 50s
2724:	learn: 0.0038668	total: 4m 41s	remaining: 12m 31s
2773:	learn: 0.0042635	total: 4m 41s	remaining: 12m 13s
2733:	learn: 0.0046792	total: 4m 41s	remaining: 12m 28s
2532:	learn: 0.0048919	total: 4m 41s	remaining: 13m 50s
2647:	learn: 0.0046968	total: 4m 41s	remaining: 13m 2s
2725:	learn: 0.0038649	total: 4m 41s	remaining: 12m 31s
2774:	learn: 0.0042602	total: 4m 41s	remaining: 12m 13s
2533:	learn: 0.0048887	total: 4m 41s	remaining: 13m 50s
2648:	learn: 0.0046942	total: 4m 41s	remaining: 13m 2s
2734:	learn: 0.0046756	total: 4m 41s	remaining: 12m 28s
2726:	learn: 0.0038628	total: 4m 41s	remaining: 12m 31s
2534:	learn: 0.0048847	total: 4m 41s	remaining: 13m 50s
2775:	learn: 0.0042580	total: 4m 41s	remaining: 12m 13s
2649:	learn: 0.0046922	total: 4m 41s	remaining: 13m 1s
2735:	learn: 0.0046727	total: 4m 41s	remaining: 12m 28s
2727:	learn: 0.0038611	total: 4m 41s	remaining: 12m 31s
2650:	learn: 0.0046893	total: 4m 41s	remaining: 13m 1s
2776:	learn: 0.0042568	total: 4m 41s	remaining: 12m 13s
2535:	learn: 0.0048827	total: 4m 41s	remaining: 13m 49s
2728:	learn: 0.0038597	total: 4m 41s	remaining: 12m 31s
2736:	learn: 0.0046699	total: 4m 41s	remaining: 12m 28s
2651:	learn: 0.0046857	total: 4m 42s	remaining: 13m 1s
2777:	learn: 0.0042534	total: 4m 42s	remaining: 12m 13s
2729:	learn: 0.0038578	total: 4m 42s	remaining: 12m 31s
2536:	learn: 0.0048795	total: 4m 42s	remaining: 13m 49s
2652:	learn: 0.0046828	total: 4m 42s	remaining: 13m 1s
2737:	learn: 0.0046663	total: 4m 42s	remaining: 12m 28s
2778:	learn: 0.0042509	total: 4m 42s	remaining: 12m 13s
2730:	learn: 0.0038558	total: 4m 42s	remaining: 12m 30s
2653:	learn: 0.0046817	total: 4m 42s	remaining: 13m 1s
2537:	learn: 0.0048751	total: 4m 42s	remaining: 13m 49s
2779:	learn: 0.0042485	total: 4m 42s	remaining: 12m 13s
2738:	learn: 0.0046634	total: 4m 42s	remaining: 12m 27s
2731:	learn: 0.0038540	total: 4m 42s	remaining: 12m 30s
2538:	learn: 0.0048704	total: 4m 42s	remaining: 13m 49s
2780:	learn: 0.0042452	total: 4m 42s	remaining: 12m 12s
2654:	learn: 0.0046794	total: 4m 42s	remaining: 13m 1s
2732:	learn: 0.0038523	total: 4m 42s	remaining: 12m 30s
2739:	learn: 0.0046605	total: 4m 42s	remaining: 12m 27s
2539:	learn: 0.0048662	total: 4m 42s	remaining: 13m 49s
2655:	learn: 0.0046760	total: 4m 42s	remaining: 13m 1s
2781:	learn: 0.0042424	total: 4m 42s	remaining: 12m 12s
2740:	learn: 0.0046579	total: 4m 42s	remaining: 12m 27s
2733:	learn: 0.0038498	total: 4m 42s	remaining: 12m 30s
2540:	learn: 0.0048632	total: 4m 42s	remaining: 13m 49s
2656:	learn: 0.0046742	total: 4m 42s	remaining: 13m
2782:	learn: 0.0042396	total: 4m 42s	remaining: 12m 12s
2741:	learn: 0.0046543	total: 4m 42s	remaining: 12m 27s
2734:	learn: 0.0038480	total: 4m 42s	remaining: 12m 30s
2541:	learn: 0.0048597	total: 4m 42s	remaining: 13m 49s
2783:	learn: 0.0042369	total: 4m 42s	remaining: 12m 12s
2657:	learn: 0.0046714	total: 4m 42s	remaining: 13m
2742:	learn: 0.0046508	total: 4m 42s	remaining: 12m 27s
2735:	learn: 0.0038455	total: 4m 42s	remaining: 12m 30s
2784:	learn: 0.0042349	total: 4m 42s	remaining: 12m 12s
2542:	learn: 0.0048552	total: 4m 42s	remaining: 13m 49s
2658:	learn: 0.0046694	total: 4m 42s	remaining: 13m
2743:	learn: 0.0046483	total: 4m 42s	remaining: 12m 27s
2736:	learn: 0.0038435	total: 4m 42s	remaining: 12m 30s
2543:	learn: 0.0048527	total: 4m 42s	remaining: 13m 48s
2785:	learn: 0.0042330	total: 4m 42s	remaining: 12m 12s
2744:	learn: 0.0046448	total: 4m 42s	remaining: 12m 27s
2659:	learn: 0.0046669	total: 4m 42s	remaining: 13m
2737:	learn: 0.0038416	total: 4m 42s	remaining: 12m 30s
2544:	learn: 0.0048508	total: 4m 42s	remaining: 13m 48s
2745:	learn: 0.0046411	total: 4m 42s	remaining: 12m 27s
2786:	learn: 0.0042305	total: 4m 42s	remaining: 12m 12s
2738:	learn: 0.0038388	total: 4m 42s	remaining: 12m 30s
2660:	learn: 0.0046654	total: 4m 43s	remaining: 13m
2545:	learn: 0.0048478	total: 4m 43s	remaining: 13m 48s
2746:	learn: 0.0046382	total: 4m 42s	remaining: 12m 27s
2787:	learn: 0.0042277	total: 4m 43s	remaining: 12m 12s
2661:	learn: 0.0046637	total: 4m 43s	remaining: 13m
2739:	learn: 0.0038372	total: 4m 43s	remaining: 12m 29s
2546:	learn: 0.0048448	total: 4m 43s	remaining: 13m 48s
2662:	learn: 0.0046607	total: 4m 43s	remaining: 13m
2747:	learn: 0.0046346	total: 4m 43s	remaining: 12m 26s
2788:	learn: 0.0042260	total: 4m 43s	remaining: 12m 12s
2740:	learn: 0.0038356	total: 4m 43s	remaining: 12m 29s
2547:	learn: 0.0048424	total: 4m 43s	remaining: 13m 48s
2663:	learn: 0.0046588	total: 4m 43s	remaining: 13m
2748:	learn: 0.0046318	total: 4m 43s	remaining: 12m 26s
2789:	learn: 0.0042230	total: 4m 43s	remaining: 12m 12s
2741:	learn: 0.0038322	total: 4m 43s	remaining: 12m 29s
2548:	learn: 0.0048380	total: 4m 43s	remaining: 13m 48s
2664:	learn: 0.0046563	total: 4m 43s	remaining: 12m 59s
2749:	learn: 0.0046292	total: 4m 43s	remaining: 12m 26s
2790:	learn: 0.0042207	total: 4m 43s	remaining: 12m 11s
2742:	learn: 0.0038306	total: 4m 43s	remaining: 12m 29s
2750:	learn: 0.0046257	total: 4m 43s	remaining: 12m 26s
2549:	learn: 0.0048351	total: 4m 43s	remaining: 13m 48s
2665:	learn: 0.0046533	total: 4m 43s	remaining: 12m 59s
2791:	learn: 0.0042176	total: 4m 43s	remaining: 12m 11s
2666:	learn: 0.0046499	total: 4m 43s	remaining: 12m 59s
2743:	learn: 0.0038285	total: 4m 43s	remaining: 12m 29s
2550:	learn: 0.0048321	total: 4m 43s	remaining: 13m 47s
2751:	learn: 0.0046221	total: 4m 43s	remaining: 12m 26s
2792:	learn: 0.0042156	total: 4m 43s	remaining: 12m 11s
2667:	learn: 0.0046473	total: 4m 43s	remaining: 12m 59s
2551:	learn: 0.0048288	total: 4m 43s	remaining: 13m 47s
2744:	learn: 0.0038257	total: 4m 43s	remaining: 12m 29s
2752:	learn: 0.0046195	total: 4m 43s	remaining: 12m 26s
2793:	learn: 0.0042123	total: 4m 43s	remaining: 12m 11s
2552:	learn: 0.0048249	total: 4m 43s	remaining: 13m 47s
2668:	learn: 0.0046457	total: 4m 43s	remaining: 12m 59s
2745:	learn: 0.0038241	total: 4m 43s	remaining: 12m 29s
2794:	learn: 0.0042103	total: 4m 43s	remaining: 12m 11s
2753:	learn: 0.0046163	total: 4m 43s	remaining: 12m 26s
2669:	learn: 0.0046432	total: 4m 43s	remaining: 12m 59s
2553:	learn: 0.0048218	total: 4m 43s	remaining: 13m 47s
2746:	learn: 0.0038222	total: 4m 43s	remaining: 12m 29s
2795:	learn: 0.0042085	total: 4m 43s	remaining: 12m 11s
2754:	learn: 0.0046142	total: 4m 43s	remaining: 12m 26s
2670:	learn: 0.0046403	total: 4m 43s	remaining: 12m 59s
2554:	learn: 0.0048176	total: 4m 43s	remaining: 13m 47s
2755:	learn: 0.0046121	total: 4m 43s	remaining: 12m 26s
2747:	learn: 0.0038204	total: 4m 43s	remaining: 12m 29s
2796:	learn: 0.0042057	total: 4m 43s	remaining: 12m 11s
2555:	learn: 0.0048132	total: 4m 43s	remaining: 13m 47s
2671:	learn: 0.0046372	total: 4m 44s	remaining: 12m 58s
2756:	learn: 0.0046102	total: 4m 43s	remaining: 12m 25s
2748:	learn: 0.0038180	total: 4m 44s	remaining: 12m 29s
2797:	learn: 0.0042033	total: 4m 44s	remaining: 12m 11s
2556:	learn: 0.0048108	total: 4m 44s	remaining: 13m 47s
2672:	learn: 0.0046343	total: 4m 44s	remaining: 12m 58s
2749:	learn: 0.0038162	total: 4m 44s	remaining: 12m 29s
2673:	learn: 0.0046319	total: 4m 44s	remaining: 12m 58s
2757:	learn: 0.0046072	total: 4m 44s	remaining: 12m 25s
2798:	learn: 0.0042011	total: 4m 44s	remaining: 12m 11s
2557:	learn: 0.0048078	total: 4m 44s	remaining: 13m 46s
2750:	learn: 0.0038141	total: 4m 44s	remaining: 12m 28s
2674:	learn: 0.0046288	total: 4m 44s	remaining: 12m 58s
2758:	learn: 0.0046041	total: 4m 44s	remaining: 12m 25s
2799:	learn: 0.0041991	total: 4m 44s	remaining: 12m 11s
2751:	learn: 0.0038123	total: 4m 44s	remaining: 12m 28s
2558:	learn: 0.0048067	total: 4m 44s	remaining: 13m 46s
2559:	learn: 0.0048043	total: 4m 44s	remaining: 13m 46s
2675:	learn: 0.0046266	total: 4m 44s	remaining: 12m 58s
2759:	learn: 0.0046012	total: 4m 44s	remaining: 12m 25s
2752:	learn: 0.0038094	total: 4m 44s	remaining: 12m 28s
2800:	learn: 0.0041967	total: 4m 44s	remaining: 12m 10s
2560:	learn: 0.0048002	total: 4m 44s	remaining: 13m 46s
2676:	learn: 0.0046231	total: 4m 44s	remaining: 12m 58s
2760:	learn: 0.0045992	total: 4m 44s	remaining: 12m 25s
2753:	learn: 0.0038077	total: 4m 44s	remaining: 12m 28s
2801:	learn: 0.0041948	total: 4m 44s	remaining: 12m 10s
2561:	learn: 0.0047960	total: 4m 44s	remaining: 13m 46s
2677:	learn: 0.0046208	total: 4m 44s	remaining: 12m 58s
2761:	learn: 0.0045965	total: 4m 44s	remaining: 12m 25s
2754:	learn: 0.0038051	total: 4m 44s	remaining: 12m 28s
2802:	learn: 0.0041924	total: 4m 44s	remaining: 12m 10s
2678:	learn: 0.0046176	total: 4m 44s	remaining: 12m 58s
2762:	learn: 0.0045926	total: 4m 44s	remaining: 12m 25s
2755:	learn: 0.0038021	total: 4m 44s	remaining: 12m 28s
2562:	learn: 0.0047937	total: 4m 44s	remaining: 13m 46s
2803:	learn: 0.0041896	total: 4m 44s	remaining: 12m 10s
2679:	learn: 0.0046132	total: 4m 44s	remaining: 12m 57s
2756:	learn: 0.0038003	total: 4m 44s	remaining: 12m 28s
2763:	learn: 0.0045891	total: 4m 44s	remaining: 12m 25s
2804:	learn: 0.0041863	total: 4m 44s	remaining: 12m 10s
2563:	learn: 0.0047903	total: 4m 44s	remaining: 13m 46s
2680:	learn: 0.0046081	total: 4m 44s	remaining: 12m 57s
2764:	learn: 0.0045857	total: 4m 44s	remaining: 12m 25s
2805:	learn: 0.0041842	total: 4m 44s	remaining: 12m 10s
2757:	learn: 0.0037976	total: 4m 44s	remaining: 12m 28s
2564:	learn: 0.0047859	total: 4m 44s	remaining: 13m 45s
2681:	learn: 0.0046062	total: 4m 44s	remaining: 12m 57s
2765:	learn: 0.0045843	total: 4m 44s	remaining: 12m 25s
2758:	learn: 0.0037958	total: 4m 44s	remaining: 12m 27s
2806:	learn: 0.0041823	total: 4m 45s	remaining: 12m 10s
2682:	learn: 0.0046051	total: 4m 45s	remaining: 12m 57s
2565:	learn: 0.0047830	total: 4m 45s	remaining: 13m 45s
2759:	learn: 0.0037942	total: 4m 45s	remaining: 12m 27s
2766:	learn: 0.0045804	total: 4m 45s	remaining: 12m 25s
2807:	learn: 0.0041809	total: 4m 45s	remaining: 12m 10s
2683:	learn: 0.0046013	total: 4m 45s	remaining: 12m 57s
2767:	learn: 0.0045769	total: 4m 45s	remaining: 12m 24s
2566:	learn: 0.0047796	total: 4m 45s	remaining: 13m 45s
2760:	learn: 0.0037918	total: 4m 45s	remaining: 12m 27s
2684:	learn: 0.0045996	total: 4m 45s	remaining: 12m 57s
2808:	learn: 0.0041790	total: 4m 45s	remaining: 12m 10s
2567:	learn: 0.0047766	total: 4m 45s	remaining: 13m 45s
2768:	learn: 0.0045749	total: 4m 45s	remaining: 12m 24s
2761:	learn: 0.0037901	total: 4m 45s	remaining: 12m 27s
2809:	learn: 0.0041766	total: 4m 45s	remaining: 12m 10s
2685:	learn: 0.0045975	total: 4m 45s	remaining: 12m 57s
2568:	learn: 0.0047738	total: 4m 45s	remaining: 13m 45s
2769:	learn: 0.0045721	total: 4m 45s	remaining: 12m 24s
2810:	learn: 0.0041740	total: 4m 45s	remaining: 12m 9s
2762:	learn: 0.0037877	total: 4m 45s	remaining: 12m 27s
2686:	learn: 0.0045941	total: 4m 45s	remaining: 12m 56s
2569:	learn: 0.0047717	total: 4m 45s	remaining: 13m 45s
2811:	learn: 0.0041716	total: 4m 45s	remaining: 12m 9s
2770:	learn: 0.0045693	total: 4m 45s	remaining: 12m 24s
2763:	learn: 0.0037858	total: 4m 45s	remaining: 12m 27s
2687:	learn: 0.0045901	total: 4m 45s	remaining: 12m 56s
2771:	learn: 0.0045657	total: 4m 45s	remaining: 12m 24s
2570:	learn: 0.0047682	total: 4m 45s	remaining: 13m 45s
2812:	learn: 0.0041682	total: 4m 45s	remaining: 12m 9s
2764:	learn: 0.0037836	total: 4m 45s	remaining: 12m 27s
2688:	learn: 0.0045881	total: 4m 45s	remaining: 12m 56s
2571:	learn: 0.0047665	total: 4m 45s	remaining: 13m 45s
2772:	learn: 0.0045626	total: 4m 45s	remaining: 12m 24s
2813:	learn: 0.0041664	total: 4m 45s	remaining: 12m 9s
2765:	learn: 0.0037818	total: 4m 45s	remaining: 12m 27s
2689:	learn: 0.0045855	total: 4m 45s	remaining: 12m 56s
2814:	learn: 0.0041636	total: 4m 45s	remaining: 12m 9s
2572:	learn: 0.0047631	total: 4m 45s	remaining: 13m 45s
2773:	learn: 0.0045611	total: 4m 45s	remaining: 12m 24s
2766:	learn: 0.0037805	total: 4m 45s	remaining: 12m 27s
2815:	learn: 0.0041604	total: 4m 45s	remaining: 12m 9s
2573:	learn: 0.0047602	total: 4m 45s	remaining: 13m 44s
2690:	learn: 0.0045824	total: 4m 45s	remaining: 12m 56s
2767:	learn: 0.0037781	total: 4m 45s	remaining: 12m 26s
2774:	learn: 0.0045573	total: 4m 45s	remaining: 12m 24s
2816:	learn: 0.0041583	total: 4m 45s	remaining: 12m 9s
2574:	learn: 0.0047573	total: 4m 45s	remaining: 13m 44s
2691:	learn: 0.0045790	total: 4m 46s	remaining: 12m 56s
2775:	learn: 0.0045547	total: 4m 45s	remaining: 12m 24s
2768:	learn: 0.0037763	total: 4m 45s	remaining: 12m 26s
2817:	learn: 0.0041562	total: 4m 46s	remaining: 12m 9s
2692:	learn: 0.0045751	total: 4m 46s	remaining: 12m 56s
2776:	learn: 0.0045512	total: 4m 45s	remaining: 12m 23s
2769:	learn: 0.0037734	total: 4m 46s	remaining: 12m 26s
2575:	learn: 0.0047538	total: 4m 46s	remaining: 13m 44s
2818:	learn: 0.0041540	total: 4m 46s	remaining: 12m 8s
2777:	learn: 0.0045481	total: 4m 46s	remaining: 12m 23s
2693:	learn: 0.0045711	total: 4m 46s	remaining: 12m 56s
2770:	learn: 0.0037704	total: 4m 46s	remaining: 12m 26s
2576:	learn: 0.0047520	total: 4m 46s	remaining: 13m 44s
2771:	learn: 0.0037687	total: 4m 46s	remaining: 12m 26s
2778:	learn: 0.0045441	total: 4m 46s	remaining: 12m 23s
2819:	learn: 0.0041521	total: 4m 46s	remaining: 12m 8s
2577:	learn: 0.0047479	total: 4m 46s	remaining: 13m 44s
2694:	learn: 0.0045677	total: 4m 46s	remaining: 12m 56s
2772:	learn: 0.0037655	total: 4m 46s	remaining: 12m 26s
2779:	learn: 0.0045416	total: 4m 46s	remaining: 12m 23s
2820:	learn: 0.0041497	total: 4m 46s	remaining: 12m 8s
2578:	learn: 0.0047452	total: 4m 46s	remaining: 13m 44s
2695:	learn: 0.0045657	total: 4m 46s	remaining: 12m 56s
2773:	learn: 0.0037639	total: 4m 46s	remaining: 12m 26s
2780:	learn: 0.0045391	total: 4m 46s	remaining: 12m 23s
2696:	learn: 0.0045630	total: 4m 46s	remaining: 12m 55s
2821:	learn: 0.0041473	total: 4m 46s	remaining: 12m 8s
2579:	learn: 0.0047415	total: 4m 46s	remaining: 13m 44s
2774:	learn: 0.0037612	total: 4m 46s	remaining: 12m 25s
2781:	learn: 0.0045371	total: 4m 46s	remaining: 12m 23s
2697:	learn: 0.0045601	total: 4m 46s	remaining: 12m 55s
2822:	learn: 0.0041450	total: 4m 46s	remaining: 12m 8s
2580:	learn: 0.0047394	total: 4m 46s	remaining: 13m 44s
2775:	learn: 0.0037595	total: 4m 46s	remaining: 12m 25s
2782:	learn: 0.0045337	total: 4m 46s	remaining: 12m 23s
2698:	learn: 0.0045580	total: 4m 46s	remaining: 12m 55s
2823:	learn: 0.0041422	total: 4m 46s	remaining: 12m 8s
2776:	learn: 0.0037580	total: 4m 46s	remaining: 12m 25s

2783:	learn: 0.0045304	total: 4m 46s	remaining: 12m 23s
2581:	learn: 0.0047351	total: 4m 46s	remaining: 13m 43s
2699:	learn: 0.0045549	total: 4m 46s	remaining: 12m 55s
2824:	learn: 0.0041398	total: 4m 46s	remaining: 12m 8s
2784:	learn: 0.0045275	total: 4m 46s	remaining: 12m 22s
2777:	learn: 0.0037559	total: 4m 46s	remaining: 12m 25s
2582:	learn: 0.0047315	total: 4m 46s	remaining: 13m 43s
2785:	learn: 0.0045255	total: 4m 46s	remaining: 12m 22s
2700:	learn: 0.0045515	total: 4m 46s	remaining: 12m 55s
2825:	learn: 0.0041379	total: 4m 46s	remaining: 12m 8s
2583:	learn: 0.0047287	total: 4m 47s	remaining: 13m 43s
2778:	learn: 0.0037542	total: 4m 46s	remaining: 12m 25s
2786:	learn: 0.0045236	total: 4m 46s	remaining: 12m 22s
2701:	learn: 0.0045492	total: 4m 47s	remaining: 12m 55s
2826:	learn: 0.0041358	total: 4m 47s	remaining: 12m 8s
2584:	learn: 0.0047257	total: 4m 47s	remaining: 13m 43s
2779:	learn: 0.0037520	total: 4m 47s	remaining: 12m 25s
2702:	learn: 0.0045469	total: 4m 47s	remaining: 12m 55s
2787:	learn: 0.0045204	total: 4m 47s	remaining: 12m 22s
2827:	learn: 0.0041346	total: 4m 47s	remaining: 12m 8s
2780:	learn: 0.0037497	total: 4m 47s	remaining: 12m 25s
2788:	learn: 0.0045176	total: 4m 47s	remaining: 12m 22s
2585:	learn: 0.0047225	total: 4m 47s	remaining: 13m 43s
2703:	learn: 0.0045447	total: 4m 47s	remaining: 12m 55s
2828:	learn: 0.0041315	total: 4m 47s	remaining: 12m 8s
2781:	learn: 0.0037482	total: 4m 47s	remaining: 12m 25s
2789:	learn: 0.0045151	total: 4m 47s	remaining: 12m 22s
2829:	learn: 0.0041292	total: 4m 47s	remaining: 12m 7s
2586:	learn: 0.0047186	total: 4m 47s	remaining: 13m 43s
2704:	learn: 0.0045421	total: 4m 47s	remaining: 12m 55s
2790:	learn: 0.0045131	total: 4m 47s	remaining: 12m 22s
2830:	learn: 0.0041266	total: 4m 47s	remaining: 12m 7s
2782:	learn: 0.0037466	total: 4m 47s	remaining: 12m 25s
2587:	learn: 0.0047161	total: 4m 47s	remaining: 13m 43s
2705:	learn: 0.0045393	total: 4m 47s	remaining: 12m 54s
2791:	learn: 0.0045104	total: 4m 47s	remaining: 12m 21s
2783:	learn: 0.0037450	total: 4m 47s	remaining: 12m 25s
2831:	learn: 0.0041243	total: 4m 47s	remaining: 12m 7s
2588:	learn: 0.0047133	total: 4m 47s	remaining: 13m 43s
2706:	learn: 0.0045379	total: 4m 47s	remaining: 12m 54s
2792:	learn: 0.0045064	total: 4m 47s	remaining: 12m 21s
2784:	learn: 0.0037426	total: 4m 47s	remaining: 12m 24s
2707:	learn: 0.0045346	total: 4m 47s	remaining: 12m 54s
2589:	learn: 0.0047102	total: 4m 47s	remaining: 13m 42s
2832:	learn: 0.0041208	total: 4m 47s	remaining: 12m 7s
2793:	learn: 0.0045029	total: 4m 47s	remaining: 12m 21s
2785:	learn: 0.0037400	total: 4m 47s	remaining: 12m 24s
2708:	learn: 0.0045329	total: 4m 47s	remaining: 12m 54s
2590:	learn: 0.0047059	total: 4m 47s	remaining: 13m 42s
2833:	learn: 0.0041174	total: 4m 47s	remaining: 12m 7s
2794:	learn: 0.0045010	total: 4m 47s	remaining: 12m 21s
2786:	learn: 0.0037380	total: 4m 47s	remaining: 12m 24s
2709:	learn: 0.0045304	total: 4m 47s	remaining: 12m 54s
2591:	learn: 0.0047033	total: 4m 47s	remaining: 13m 42s
2834:	learn: 0.0041158	total: 4m 47s	remaining: 12m 7s
2787:	learn: 0.0037362	total: 4m 47s	remaining: 12m 24s
2710:	learn: 0.0045265	total: 4m 47s	remaining: 12m 54s
2592:	learn: 0.0047010	total: 4m 47s	remaining: 13m 42s
2795:	learn: 0.0044982	total: 4m 47s	remaining: 12m 21s
2835:	learn: 0.0041140	total: 4m 47s	remaining: 12m 7s
2788:	learn: 0.0037347	total: 4m 47s	remaining: 12m 24s
2796:	learn: 0.0044943	total: 4m 47s	remaining: 12m 21s
2711:	learn: 0.0045247	total: 4m 48s	remaining: 12m 54s
2593:	learn: 0.0046994	total: 4m 48s	remaining: 13m 42s
2836:	learn: 0.0041111	total: 4m 48s	remaining: 12m 7s
2789:	learn: 0.0037330	total: 4m 48s	remaining: 12m 24s
2797:	learn: 0.0044910	total: 4m 47s	remaining: 12m 21s
2712:	learn: 0.0045222	total: 4m 48s	remaining: 12m 53s
2837:	learn: 0.0041092	total: 4m 48s	remaining: 12m 7s
2594:	learn: 0.0046957	total: 4m 48s	remaining: 13m 42s
2790:	learn: 0.0037312	total: 4m 48s	remaining: 12m 24s
2713:	learn: 0.0045195	total: 4m 48s	remaining: 12m 53s
2798:	learn: 0.0044892	total: 4m 48s	remaining: 12m 21s
2838:	learn: 0.0041081	total: 4m 48s	remaining: 12m 6s
2595:	learn: 0.0046922	total: 4m 48s	remaining: 13m 42s
2714:	learn: 0.0045172	total: 4m 48s	remaining: 12m 53s
2791:	learn: 0.0037292	total: 4m 48s	remaining: 12m 24s
2839:	learn: 0.0041063	total: 4m 48s	remaining: 12m 6s
2799:	learn: 0.0044873	total: 4m 48s	remaining: 12m 21s
2715:	learn: 0.0045142	total: 4m 48s	remaining: 12m 53s
2792:	learn: 0.0037274	total: 4m 48s	remaining: 12m 24s
2596:	learn: 0.0046880	total: 4m 48s	remaining: 13m 42s
2840:	learn: 0.0041045	total: 4m 48s	remaining: 12m 6s
2716:	learn: 0.0045119	total: 4m 48s	remaining: 12m 53s
2793:	learn: 0.0037254	total: 4m 48s	remaining: 12m 23s
2800:	learn: 0.0044856	total: 4m 48s	remaining: 12m 21s
2597:	learn: 0.0046841	total: 4m 48s	remaining: 13m 41s
2794:	learn: 0.0037231	total: 4m 48s	remaining: 12m 23s
2841:	learn: 0.0041008	total: 4m 48s	remaining: 12m 6s
2801:	learn: 0.0044828	total: 4m 48s	remaining: 12m 21s
2717:	learn: 0.0045100	total: 4m 48s	remaining: 12m 53s
2598:	learn: 0.0046803	total: 4m 48s	remaining: 13m 41s
2795:	learn: 0.0037212	total: 4m 48s	remaining: 12m 23s
2842:	learn: 0.0040981	total: 4m 48s	remaining: 12m 6s
2718:	learn: 0.0045085	total: 4m 48s	remaining: 12m 53s
2802:	learn: 0.0044792	total: 4m 48s	remaining: 12m 20s
2599:	learn: 0.0046760	total: 4m 48s	remaining: 13m 41s
2796:	learn: 0.0037194	total: 4m 48s	remaining: 12m 23s
2843:	learn: 0.0040942	total: 4m 48s	remaining: 12m 6s
2719:	learn: 0.0045053	total: 4m 48s	remaining: 12m 52s
2803:	learn: 0.0044762	total: 4m 48s	remaining: 12m 20s
2600:	learn: 0.0046736	total: 4m 48s	remaining: 13m 41s
2797:	learn: 0.0037170	total: 4m 48s	remaining: 12m 23s
2844:	learn: 0.0040913	total: 4m 48s	remaining: 12m 6s
2720:	learn: 0.0045028	total: 4m 48s	remaining: 12m 52s
2804:	learn: 0.0044735	total: 4m 48s	remaining: 12m 20s
2845:	learn: 0.0040881	total: 4m 48s	remaining: 12m 6s
2601:	learn: 0.0046696	total: 4m 48s	remaining: 13m 41s
2798:	learn: 0.0037148	total: 4m 48s	remaining: 12m 23s
2721:	learn: 0.0045001	total: 4m 48s	remaining: 12m 52s
2805:	learn: 0.0044710	total: 4m 48s	remaining: 12m 20s
2846:	learn: 0.0040863	total: 4m 48s	remaining: 12m 6s
2602:	learn: 0.0046671	total: 4m 49s	remaining: 13m 41s
2799:	learn: 0.0037125	total: 4m 49s	remaining: 12m 23s
2722:	learn: 0.0044968	total: 4m 49s	remaining: 12m 52s
2847:	learn: 0.0040829	total: 4m 49s	remaining: 12m 5s
2603:	learn: 0.0046634	total: 4m 49s	remaining: 13m 41s
2806:	learn: 0.0044692	total: 4m 49s	remaining: 12m 20s
2800:	learn: 0.0037106	total: 4m 49s	remaining: 12m 22s
2848:	learn: 0.0040810	total: 4m 49s	remaining: 12m 5s
2807:	learn: 0.0044665	total: 4m 49s	remaining: 12m 20s
2723:	learn: 0.0044950	total: 4m 49s	remaining: 12m 52s
2801:	learn: 0.0037090	total: 4m 49s	remaining: 12m 22s
2604:	learn: 0.0046610	total: 4m 49s	remaining: 13m 41s
2849:	learn: 0.0040796	total: 4m 49s	remaining: 12m 5s
2808:	learn: 0.0044631	total: 4m 49s	remaining: 12m 20s
2724:	learn: 0.0044928	total: 4m 49s	remaining: 12m 52s
2850:	learn: 0.0040781	total: 4m 49s	remaining: 12m 5s
2809:	learn: 0.0044599	total: 4m 49s	remaining: 12m 20s
2802:	learn: 0.0037071	total: 4m 49s	remaining: 12m 22s
2605:	learn: 0.0046572	total: 4m 49s	remaining: 13m 41s
2851:	learn: 0.0040751	total: 4m 49s	remaining: 12m 5s
2725:	learn: 0.0044899	total: 4m 49s	remaining: 12m 52s
2810:	learn: 0.0044562	total: 4m 49s	remaining: 12m 19s
2852:	learn: 0.0040738	total: 4m 49s	remaining: 12m 5s
2606:	learn: 0.0046548	total: 4m 49s	remaining: 13m 40s
2803:	learn: 0.0037043	total: 4m 49s	remaining: 12m 22s
2726:	learn: 0.0044882	total: 4m 49s	remaining: 12m 52s
2811:	learn: 0.0044530	total: 4m 49s	remaining: 12m 19s
2853:	learn: 0.0040709	total: 4m 49s	remaining: 12m 5s
2804:	learn: 0.0037012	total: 4m 49s	remaining: 12m 22s
2607:	learn: 0.0046522	total: 4m 49s	remaining: 13m 40s
2812:	learn: 0.0044503	total: 4m 49s	remaining: 12m 19s
2805:	learn: 0.0036984	total: 4m 49s	remaining: 12m 22s
2727:	learn: 0.0044855	total: 4m 49s	remaining: 12m 52s
2854:	learn: 0.0040689	total: 4m 49s	remaining: 12m 4s
2813:	learn: 0.0044472	total: 4m 49s	remaining: 12m 19s
2608:	learn: 0.0046503	total: 4m 49s	remaining: 13m 40s
2806:	learn: 0.0036969	total: 4m 49s	remaining: 12m 22s
2728:	learn: 0.0044824	total: 4m 49s	remaining: 12m 52s
2814:	learn: 0.0044425	total: 4m 49s	remaining: 12m 19s
2855:	learn: 0.0040650	total: 4m 49s	remaining: 12m 4s
2807:	learn: 0.0036952	total: 4m 49s	remaining: 12m 22s
2609:	learn: 0.0046471	total: 4m 49s	remaining: 13m 40s
2856:	learn: 0.0040610	total: 4m 49s	remaining: 12m 4s
2815:	learn: 0.0044398	total: 4m 49s	remaining: 12m 19s
2729:	learn: 0.0044802	total: 4m 49s	remaining: 12m 52s
2808:	learn: 0.0036927	total: 4m 49s	remaining: 12m 22s
2610:	learn: 0.0046447	total: 4m 49s	remaining: 13m 40s
2857:	learn: 0.0040589	total: 4m 49s	remaining: 12m 4s
2816:	learn: 0.0044380	total: 4m 49s	remaining: 12m 19s
2730:	learn: 0.0044787	total: 4m 50s	remaining: 12m 51s
2809:	learn: 0.0036907	total: 4m 49s	remaining: 12m 21s
2611:	learn: 0.0046413	total: 4m 50s	remaining: 13m 40s
2858:	learn: 0.0040573	total: 4m 50s	remaining: 12m 4s
2817:	learn: 0.0044351	total: 4m 49s	remaining: 12m 19s
2731:	learn: 0.0044754	total: 4m 50s	remaining: 12m 51s
2810:	learn: 0.0036885	total: 4m 50s	remaining: 12m 21s
2859:	learn: 0.0040559	total: 4m 50s	remaining: 12m 4s
2612:	learn: 0.0046379	total: 4m 50s	remaining: 13m 40s
2818:	learn: 0.0044315	total: 4m 50s	remaining: 12m 18s
2860:	learn: 0.0040546	total: 4m 50s	remaining: 12m 4s
2732:	learn: 0.0044736	total: 4m 50s	remaining: 12m 51s
2811:	learn: 0.0036870	total: 4m 50s	remaining: 12m 21s
2613:	learn: 0.0046338	total: 4m 50s	remaining: 13m 40s
2819:	learn: 0.0044288	total: 4m 50s	remaining: 12m 18s
2861:	learn: 0.0040532	total: 4m 50s	remaining: 12m 4s
2733:	learn: 0.0044714	total: 4m 50s	remaining: 12m 51s
2812:	learn: 0.0036848	total: 4m 50s	remaining: 12m 21s
2614:	learn: 0.0046311	total: 4m 50s	remaining: 13m 40s
2820:	learn: 0.0044257	total: 4m 50s	remaining: 12m 18s
2862:	learn: 0.0040515	total: 4m 50s	remaining: 12m 3s
2734:	learn: 0.0044691	total: 4m 50s	remaining: 12m 51s
2813:	learn: 0.0036828	total: 4m 50s	remaining: 12m 21s
2821:	learn: 0.0044229	total: 4m 50s	remaining: 12m 18s
2615:	learn: 0.0046282	total: 4m 50s	remaining: 13m 39s
2863:	learn: 0.0040489	total: 4m 50s	remaining: 12m 3s
2735:	learn: 0.0044666	total: 4m 50s	remaining: 12m 51s
2822:	learn: 0.0044203	total: 4m 50s	remaining: 12m 18s
2616:	learn: 0.0046248	total: 4m 50s	remaining: 13m 39s
2814:	learn: 0.0036810	total: 4m 50s	remaining: 12m 21s
2864:	learn: 0.0040475	total: 4m 50s	remaining: 12m 3s
2736:	learn: 0.0044637	total: 4m 50s	remaining: 12m 51s
2617:	learn: 0.0046220	total: 4m 50s	remaining: 13m 39s
2815:	learn: 0.0036792	total: 4m 50s	remaining: 12m 21s
2823:	learn: 0.0044179	total: 4m 50s	remaining: 12m 18s
2865:	learn: 0.0040462	total: 4m 50s	remaining: 12m 3s
2737:	learn: 0.0044610	total: 4m 50s	remaining: 12m 51s
2816:	learn: 0.0036776	total: 4m 50s	remaining: 12m 21s
2618:	learn: 0.0046182	total: 4m 50s	remaining: 13m 39s
2824:	learn: 0.0044161	total: 4m 50s	remaining: 12m 18s
2866:	learn: 0.0040422	total: 4m 50s	remaining: 12m 3s
2738:	learn: 0.0044587	total: 4m 50s	remaining: 12m 51s
2619:	learn: 0.0046148	total: 4m 50s	remaining: 13m 39s
2817:	learn: 0.0036762	total: 4m 50s	remaining: 12m 21s
2825:	learn: 0.0044135	total: 4m 50s	remaining: 12m 18s
2867:	learn: 0.0040392	total: 4m 50s	remaining: 12m 3s
2739:	learn: 0.0044566	total: 4m 50s	remaining: 12m 50s
2620:	learn: 0.0046128	total: 4m 50s	remaining: 13m 39s
2818:	learn: 0.0036741	total: 4m 50s	remaining: 12m 21s
2826:	learn: 0.0044102	total: 4m 50s	remaining: 12m 18s
2740:	learn: 0.0044544	total: 4m 51s	remaining: 12m 50s
2868:	learn: 0.0040369	total: 4m 51s	remaining: 12m 3s
2621:	learn: 0.0046107	total: 4m 51s	remaining: 13m 39s
2819:	learn: 0.0036722	total: 4m 51s	remaining: 12m 21s
2827:	learn: 0.0044071	total: 4m 50s	remaining: 12m 17s
2741:	learn: 0.0044519	total: 4m 51s	remaining: 12m 50s
2869:	learn: 0.0040339	total: 4m 51s	remaining: 12m 3s
2622:	learn: 0.0046083	total: 4m 51s	remaining: 13m 38s
2820:	learn: 0.0036705	total: 4m 51s	remaining: 12m 20s
2742:	learn: 0.0044497	total: 4m 51s	remaining: 12m 50s
2828:	learn: 0.0044040	total: 4m 51s	remaining: 12m 17s
2870:	learn: 0.0040308	total: 4m 51s	remaining: 12m 3s
2821:	learn: 0.0036679	total: 4m 51s	remaining: 12m 20s
2623:	learn: 0.0046043	total: 4m 51s	remaining: 13m 38s
2743:	learn: 0.0044472	total: 4m 51s	remaining: 12m 50s
2871:	learn: 0.0040280	total: 4m 51s	remaining: 12m 3s
2829:	learn: 0.0044004	total: 4m 51s	remaining: 12m 17s
2822:	learn: 0.0036663	total: 4m 51s	remaining: 12m 20s
2624:	learn: 0.0046017	total: 4m 51s	remaining: 13m 38s
2872:	learn: 0.0040263	total: 4m 51s	remaining: 12m 2s
2744:	learn: 0.0044444	total: 4m 51s	remaining: 12m 50s
2830:	learn: 0.0043976	total: 4m 51s	remaining: 12m 17s
2823:	learn: 0.0036652	total: 4m 51s	remaining: 12m 20s
2873:	learn: 0.0040232	total: 4m 51s	remaining: 12m 2s
2625:	learn: 0.0045990	total: 4m 51s	remaining: 13m 38s
2745:	learn: 0.0044427	total: 4m 51s	remaining: 12m 50s
2831:	learn: 0.0043939	total: 4m 51s	remaining: 12m 17s
2824:	learn: 0.0036632	total: 4m 51s	remaining: 12m 20s
2874:	learn: 0.0040209	total: 4m 51s	remaining: 12m 2s
2626:	learn: 0.0045962	total: 4m 51s	remaining: 13m 38s
2746:	learn: 0.0044406	total: 4m 51s	remaining: 12m 50s
2832:	learn: 0.0043904	total: 4m 51s	remaining: 12m 17s
2825:	learn: 0.0036618	total: 4m 51s	remaining: 12m 20s
2747:	learn: 0.0044376	total: 4m 51s	remaining: 12m 49s
2627:	learn: 0.0045949	total: 4m 51s	remaining: 13m 38s
2875:	learn: 0.0040193	total: 4m 51s	remaining: 12m 2s
2833:	learn: 0.0043872	total: 4m 51s	remaining: 12m 17s
2826:	learn: 0.0036602	total: 4m 51s	remaining: 12m 20s
2748:	learn: 0.0044334	total: 4m 51s	remaining: 12m 49s
2628:	learn: 0.0045917	total: 4m 51s	remaining: 13m 38s
2876:	learn: 0.0040163	total: 4m 51s	remaining: 12m 2s
2834:	learn: 0.0043835	total: 4m 51s	remaining: 12m 17s
2749:	learn: 0.0044308	total: 4m 51s	remaining: 12m 49s
2827:	learn: 0.0036571	total: 4m 51s	remaining: 12m 20s
2629:	learn: 0.0045898	total: 4m 51s	remaining: 13m 38s
2877:	learn: 0.0040146	total: 4m 51s	remaining: 12m 2s
2835:	learn: 0.0043805	total: 4m 51s	remaining: 12m 17s
2750:	learn: 0.0044286	total: 4m 51s	remaining: 12m 49s
2828:	learn: 0.0036553	total: 4m 51s	remaining: 12m 19s
2878:	learn: 0.0040116	total: 4m 52s	remaining: 12m 2s
2630:	learn: 0.0045862	total: 4m 52s	remaining: 13m 37s
2836:	learn: 0.0043761	total: 4m 51s	remaining: 12m 17s
2751:	learn: 0.0044268	total: 4m 52s	remaining: 12m 49s
2829:	learn: 0.0036540	total: 4m 52s	remaining: 12m 19s
2879:	learn: 0.0040106	total: 4m 52s	remaining: 12m 2s
2631:	learn: 0.0045833	total: 4m 52s	remaining: 13m 37s
2837:	learn: 0.0043732	total: 4m 52s	remaining: 12m 16s
2752:	learn: 0.0044247	total: 4m 52s	remaining: 12m 49s
2830:	learn: 0.0036529	total: 4m 52s	remaining: 12m 19s
2880:	learn: 0.0040089	total: 4m 52s	remaining: 12m 2s
2632:	learn: 0.0045795	total: 4m 52s	remaining: 13m 37s
2838:	learn: 0.0043692	total: 4m 52s	remaining: 12m 16s
2831:	learn: 0.0036506	total: 4m 52s	remaining: 12m 19s
2753:	learn: 0.0044231	total: 4m 52s	remaining: 12m 49s
2881:	learn: 0.0040062	total: 4m 52s	remaining: 12m 1s
2839:	learn: 0.0043657	total: 4m 52s	remaining: 12m 16s
2633:	learn: 0.0045772	total: 4m 52s	remaining: 13m 37s
2832:	learn: 0.0036493	total: 4m 52s	remaining: 12m 19s
2754:	learn: 0.0044214	total: 4m 52s	remaining: 12m 48s
2882:	learn: 0.0040040	total: 4m 52s	remaining: 12m 1s
2840:	learn: 0.0043626	total: 4m 52s	remaining: 12m 16s
2634:	learn: 0.0045757	total: 4m 52s	remaining: 13m 37s
2833:	learn: 0.0036479	total: 4m 52s	remaining: 12m 19s
2755:	learn: 0.0044183	total: 4m 52s	remaining: 12m 48s
2883:	learn: 0.0040011	total: 4m 52s	remaining: 12m 1s
2841:	learn: 0.0043601	total: 4m 52s	remaining: 12m 16s
2756:	learn: 0.0044163	total: 4m 52s	remaining: 12m 48s
2635:	learn: 0.0045724	total: 4m 52s	remaining: 13m 37s
2834:	learn: 0.0036456	total: 4m 52s	remaining: 12m 19s
2884:	learn: 0.0039973	total: 4m 52s	remaining: 12m 1s
2842:	learn: 0.0043569	total: 4m 52s	remaining: 12m 16s

2757:	learn: 0.0044139	total: 4m 52s	remaining: 12m 48s
2885:	learn: 0.0039961	total: 4m 52s	remaining: 12m 1s
2835:	learn: 0.0036433	total: 4m 52s	remaining: 12m 19s
2636:	learn: 0.0045681	total: 4m 52s	remaining: 13m 37s
2843:	learn: 0.0043539	total: 4m 52s	remaining: 12m 16s
2758:	learn: 0.0044114	total: 4m 52s	remaining: 12m 48s
2836:	learn: 0.0036420	total: 4m 52s	remaining: 12m 19s
2886:	learn: 0.0039932	total: 4m 52s	remaining: 12m 1s
2637:	learn: 0.0045662	total: 4m 52s	remaining: 13m 37s
2837:	learn: 0.0036397	total: 4m 52s	remaining: 12m 18s
2844:	learn: 0.0043500	total: 4m 52s	remaining: 12m 16s
2759:	learn: 0.0044099	total: 4m 52s	remaining: 12m 48s
2887:	learn: 0.0039911	total: 4m 52s	remaining: 12m 1s
2845:	learn: 0.0043474	total: 4m 52s	remaining: 12m 16s
2838:	learn: 0.0036378	total: 4m 52s	remaining: 12m 18s
2638:	learn: 0.0045635	total: 4m 52s	remaining: 13m 37s
2760:	learn: 0.0044083	total: 4m 52s	remaining: 12m 48s
2888:	learn: 0.0039887	total: 4m 53s	remaining: 12m 1s
2839:	learn: 0.0036353	total: 4m 52s	remaining: 12m 18s
2639:	learn: 0.0045595	total: 4m 53s	remaining: 13m 36s
2846:	learn: 0.0043450	total: 4m 52s	remaining: 12m 15s
2761:	learn: 0.0044059	total: 4m 53s	remaining: 12m 48s
2889:	learn: 0.0039873	total: 4m 53s	remaining: 12m 1s
2640:	learn: 0.0045560	total: 4m 53s	remaining: 13m 36s
2762:	learn: 0.0044036	total: 4m 53s	remaining: 12m 47s
2847:	learn: 0.0043426	total: 4m 53s	remaining: 12m 15s
2840:	learn: 0.0036338	total: 4m 53s	remaining: 12m 18s
2890:	learn: 0.0039853	total: 4m 53s	remaining: 12m
2641:	learn: 0.0045523	total: 4m 53s	remaining: 13m 36s
2891:	learn: 0.0039839	total: 4m 53s	remaining: 12m
2848:	learn: 0.0043395	total: 4m 53s	remaining: 12m 15s
2841:	learn: 0.0036314	total: 4m 53s	remaining: 12m 18s
2763:	learn: 0.0044015	total: 4m 53s	remaining: 12m 47s
2892:	learn: 0.0039821	total: 4m 53s	remaining: 12m
2642:	learn: 0.0045499	total: 4m 53s	remaining: 13m 36s
2849:	learn: 0.0043369	total: 4m 53s	remaining: 12m 15s
2764:	learn: 0.0043999	total: 4m 53s	remaining: 12m 47s
2842:	learn: 0.0036297	total: 4m 53s	remaining: 12m 18s
2893:	learn: 0.0039801	total: 4m 53s	remaining: 12m
2643:	learn: 0.0045481	total: 4m 53s	remaining: 13m 36s
2850:	learn: 0.0043330	total: 4m 53s	remaining: 12m 15s
2843:	learn: 0.0036283	total: 4m 53s	remaining: 12m 18s
2765:	learn: 0.0043974	total: 4m 53s	remaining: 12m 47s
2894:	learn: 0.0039783	total: 4m 53s	remaining: 12m
2644:	learn: 0.0045445	total: 4m 53s	remaining: 13m 36s
2766:	learn: 0.0043947	total: 4m 53s	remaining: 12m 47s
2851:	learn: 0.0043306	total: 4m 53s	remaining: 12m 15s
2895:	learn: 0.0039758	total: 4m 53s	remaining: 12m
2844:	learn: 0.0036270	total: 4m 53s	remaining: 12m 18s
2645:	learn: 0.0045409	total: 4m 53s	remaining: 13m 36s
2852:	learn: 0.0043268	total: 4m 53s	remaining: 12m 15s
2767:	learn: 0.0043926	total: 4m 53s	remaining: 12m 47s
2845:	learn: 0.0036253	total: 4m 53s	remaining: 12m 18s
2896:	learn: 0.0039747	total: 4m 53s	remaining: 12m
2646:	learn: 0.0045380	total: 4m 53s	remaining: 13m 35s
2768:	learn: 0.0043901	total: 4m 53s	remaining: 12m 47s
2853:	learn: 0.0043239	total: 4m 53s	remaining: 12m 15s
2846:	learn: 0.0036235	total: 4m 53s	remaining: 12m 18s
2647:	learn: 0.0045341	total: 4m 53s	remaining: 13m 35s
2769:	learn: 0.0043887	total: 4m 53s	remaining: 12m 47s
2854:	learn: 0.0043210	total: 4m 53s	remaining: 12m 15s
2897:	learn: 0.0039722	total: 4m 53s	remaining: 12m
2847:	learn: 0.0036212	total: 4m 53s	remaining: 12m 17s
2770:	learn: 0.0043854	total: 4m 53s	remaining: 12m 46s
2648:	learn: 0.0045307	total: 4m 53s	remaining: 13m 35s
2898:	learn: 0.0039711	total: 4m 53s	remaining: 12m
2855:	learn: 0.0043182	total: 4m 53s	remaining: 12m 15s
2848:	learn: 0.0036190	total: 4m 53s	remaining: 12m 17s
2771:	learn: 0.0043830	total: 4m 54s	remaining: 12m 46s
2649:	learn: 0.0045285	total: 4m 54s	remaining: 13m 35s
2899:	learn: 0.0039689	total: 4m 54s	remaining: 11m 59s
2849:	learn: 0.0036164	total: 4m 54s	remaining: 12m 17s
2856:	learn: 0.0043156	total: 4m 53s	remaining: 12m 15s
2772:	learn: 0.0043800	total: 4m 54s	remaining: 12m 46s
2900:	learn: 0.0039678	total: 4m 54s	remaining: 11m 59s
2850:	learn: 0.0036142	total: 4m 54s	remaining: 12m 17s
2650:	learn: 0.0045252	total: 4m 54s	remaining: 13m 35s
2857:	learn: 0.0043133	total: 4m 54s	remaining: 12m 14s
2773:	learn: 0.0043774	total: 4m 54s	remaining: 12m 46s
2901:	learn: 0.0039649	total: 4m 54s	remaining: 11m 59s
2851:	learn: 0.0036127	total: 4m 54s	remaining: 12m 17s
2651:	learn: 0.0045231	total: 4m 54s	remaining: 13m 35s
2774:	learn: 0.0043750	total: 4m 54s	remaining: 12m 46s
2858:	learn: 0.0043105	total: 4m 54s	remaining: 12m 14s
2902:	learn: 0.0039625	total: 4m 54s	remaining: 11m 59s
2852:	learn: 0.0036110	total: 4m 54s	remaining: 12m 17s
2859:	learn: 0.0043081	total: 4m 54s	remaining: 12m 14s
2775:	learn: 0.0043722	total: 4m 54s	remaining: 12m 46s
2903:	learn: 0.0039611	total: 4m 54s	remaining: 11m 59s
2652:	learn: 0.0045208	total: 4m 54s	remaining: 13m 35s
2853:	learn: 0.0036093	total: 4m 54s	remaining: 12m 17s
2904:	learn: 0.0039583	total: 4m 54s	remaining: 11m 59s
2860:	learn: 0.0043060	total: 4m 54s	remaining: 12m 14s
2776:	learn: 0.0043705	total: 4m 54s	remaining: 12m 46s
2854:	learn: 0.0036074	total: 4m 54s	remaining: 12m 16s
2653:	learn: 0.0045195	total: 4m 54s	remaining: 13m 35s
2777:	learn: 0.0043684	total: 4m 54s	remaining: 12m 45s
2861:	learn: 0.0043038	total: 4m 54s	remaining: 12m 14s
2905:	learn: 0.0039545	total: 4m 54s	remaining: 11m 59s
2855:	learn: 0.0036058	total: 4m 54s	remaining: 12m 16s
2778:	learn: 0.0043653	total: 4m 54s	remaining: 12m 45s
2862:	learn: 0.0043022	total: 4m 54s	remaining: 12m 14s
2654:	learn: 0.0045171	total: 4m 54s	remaining: 13m 35s
2906:	learn: 0.0039526	total: 4m 54s	remaining: 11m 59s
2863:	learn: 0.0043005	total: 4m 54s	remaining: 12m 14s
2856:	learn: 0.0036031	total: 4m 54s	remaining: 12m 16s
2779:	learn: 0.0043631	total: 4m 54s	remaining: 12m 45s
2655:	learn: 0.0045136	total: 4m 54s	remaining: 13m 35s
2864:	learn: 0.0042977	total: 4m 54s	remaining: 12m 13s
2907:	learn: 0.0039512	total: 4m 54s	remaining: 11m 59s
2857:	learn: 0.0036010	total: 4m 54s	remaining: 12m 16s
2780:	learn: 0.0043601	total: 4m 54s	remaining: 12m 45s
2656:	learn: 0.0045110	total: 4m 54s	remaining: 13m 35s
2908:	learn: 0.0039490	total: 4m 54s	remaining: 11m 58s
2858:	learn: 0.0035995	total: 4m 54s	remaining: 12m 16s
2865:	learn: 0.0042947	total: 4m 54s	remaining: 12m 13s
2781:	learn: 0.0043584	total: 4m 55s	remaining: 12m 45s
2657:	learn: 0.0045076	total: 4m 55s	remaining: 13m 34s
2859:	learn: 0.0035973	total: 4m 54s	remaining: 12m 16s
2909:	learn: 0.0039469	total: 4m 55s	remaining: 11m 58s
2866:	learn: 0.0042913	total: 4m 54s	remaining: 12m 13s
2658:	learn: 0.0045051	total: 4m 55s	remaining: 13m 34s
2782:	learn: 0.0043566	total: 4m 55s	remaining: 12m 45s
2910:	learn: 0.0039447	total: 4m 55s	remaining: 11m 58s
2867:	learn: 0.0042897	total: 4m 55s	remaining: 12m 13s
2860:	learn: 0.0035954	total: 4m 55s	remaining: 12m 16s
2659:	learn: 0.0045021	total: 4m 55s	remaining: 13m 34s
2783:	learn: 0.0043545	total: 4m 55s	remaining: 12m 45s
2868:	learn: 0.0042866	total: 4m 55s	remaining: 12m 13s
2911:	learn: 0.0039433	total: 4m 55s	remaining: 11m 58s
2861:	learn: 0.0035932	total: 4m 55s	remaining: 12m 16s
2660:	learn: 0.0044987	total: 4m 55s	remaining: 13m 34s
2912:	learn: 0.0039406	total: 4m 55s	remaining: 11m 58s
2784:	learn: 0.0043521	total: 4m 55s	remaining: 12m 45s
2869:	learn: 0.0042843	total: 4m 55s	remaining: 12m 13s
2862:	learn: 0.0035907	total: 4m 55s	remaining: 12m 16s
2913:	learn: 0.0039376	total: 4m 55s	remaining: 11m 58s
2661:	learn: 0.0044959	total: 4m 55s	remaining: 13m 34s
2870:	learn: 0.0042814	total: 4m 55s	remaining: 12m 13s
2785:	learn: 0.0043501	total: 4m 55s	remaining: 12m 45s
2863:	learn: 0.0035894	total: 4m 55s	remaining: 12m 16s
2914:	learn: 0.0039348	total: 4m 55s	remaining: 11m 58s
2871:	learn: 0.0042786	total: 4m 55s	remaining: 12m 13s
2662:	learn: 0.0044927	total: 4m 55s	remaining: 13m 34s
2786:	learn: 0.0043480	total: 4m 55s	remaining: 12m 44s
2864:	learn: 0.0035874	total: 4m 55s	remaining: 12m 15s
2915:	learn: 0.0039329	total: 4m 55s	remaining: 11m 58s
9969:	learn: 0.0016176	total: 4m 43s	remaining: 854ms
9970:	learn: 0.0016176	total: 4m 43s	remaining: 825ms
9971:	learn: 0.0016176	total: 4m 43s	remaining: 797ms
9972:	learn: 0.0016176	total: 4m 43s	remaining: 768ms
9973:	learn: 0.0016176	total: 4m 43s	remaining: 740ms
9974:	learn: 0.0016170	total: 4m 43s	remaining: 711ms
9975:	learn: 0.0016163	total: 4m 43s	remaining: 683ms
9976:	learn: 0.0016163	total: 4m 43s	remaining: 655ms
9977:	learn: 0.0016163	total: 4m 43s	remaining: 626ms
9978:	learn: 0.0016163	total: 4m 43s	remaining: 598ms
9979:	learn: 0.0016163	total: 4m 44s	remaining: 569ms
9980:	learn: 0.0016163	total: 4m 44s	remaining: 541ms
9981:	learn: 0.0016164	total: 4m 44s	remaining: 512ms
9982:	learn: 0.0016164	total: 4m 44s	remaining: 484ms
9983:	learn: 0.0016164	total: 4m 44s	remaining: 455ms
9984:	learn: 0.0016164	total: 4m 44s	remaining: 427ms
9985:	learn: 0.0016164	total: 4m 44s	remaining: 398ms
9986:	learn: 0.0016164	total: 4m 44s	remaining: 370ms
9987:	learn: 0.0016164	total: 4m 44s	remaining: 341ms
9988:	learn: 0.0016164	total: 4m 44s	remaining: 313ms
9989:	learn: 0.0016164	total: 4m 44s	remaining: 285ms
9990:	learn: 0.0016164	total: 4m 44s	remaining: 256ms
9991:	learn: 0.0016163	total: 4m 44s	remaining: 228ms
9992:	learn: 0.0016162	total: 4m 44s	remaining: 199ms
9993:	learn: 0.0016162	total: 4m 44s	remaining: 171ms
9994:	learn: 0.0016162	total: 4m 44s	remaining: 142ms
9995:	learn: 0.0016162	total: 4m 44s	remaining: 114ms
9996:	learn: 0.0016162	total: 4m 44s	remaining: 85.4ms
9997:	learn: 0.0016162	total: 4m 44s	remaining: 56.9ms
9998:	learn: 0.0016162	total: 4m 44s	remaining: 28.5ms
9999:	learn: 0.0016162	total: 4m 44s	remaining: 0us

2872:	learn: 0.0042754	total: 4m 55s	remaining: 12m 13s
2663:	learn: 0.0044893	total: 4m 55s	remaining: 13m 34s
2787:	learn: 0.0043450	total: 4m 55s	remaining: 12m 44s
2916:	learn: 0.0039316	total: 4m 55s	remaining: 11m 57s
2865:	learn: 0.0035859	total: 4m 55s	remaining: 12m 15s
2873:	learn: 0.0042726	total: 4m 55s	remaining: 12m 12s
2664:	learn: 0.0044857	total: 4m 55s	remaining: 13m 33s
2788:	learn: 0.0043429	total: 4m 55s	remaining: 12m 44s
2874:	learn: 0.0042702	total: 4m 55s	remaining: 12m 12s
2917:	learn: 0.0039288	total: 4m 55s	remaining: 11m 57s
2866:	learn: 0.0035843	total: 4m 55s	remaining: 12m 15s
2665:	learn: 0.0044835	total: 4m 55s	remaining: 13m 33s
2789:	learn: 0.0043411	total: 4m 55s	remaining: 12m 44s
2867:	learn: 0.0035826	total: 4m 55s	remaining: 12m 15s
2875:	learn: 0.0042679	total: 4m 55s	remaining: 12m 12s
2918:	learn: 0.0039264	total: 4m 55s	remaining: 11m 57s
2790:	learn: 0.0043386	total: 4m 55s	remaining: 12m 44s
2666:	learn: 0.0044817	total: 4m 55s	remaining: 13m 33s
2868:	learn: 0.0035813	total: 4m 55s	remaining: 12m 15s
2919:	learn: 0.0039253	total: 4m 55s	remaining: 11m 57s
2791:	learn: 0.0043372	total: 4m 56s	remaining: 12m 44s
2876:	learn: 0.0042656	total: 4m 55s	remaining: 12m 12s
2920:	learn: 0.0039230	total: 4m 56s	remaining: 11m 57s
2869:	learn: 0.0035795	total: 4m 56s	remaining: 12m 15s
2667:	learn: 0.0044786	total: 4m 56s	remaining: 13m 33s
2792:	learn: 0.0043343	total: 4m 56s	remaining: 12m 44s
2877:	learn: 0.0042631	total: 4m 56s	remaining: 12m 12s
2921:	learn: 0.0039201	total: 4m 56s	remaining: 11m 57s
2870:	learn: 0.0035782	total: 4m 56s	remaining: 12m 15s
2668:	learn: 0.0044761	total: 4m 56s	remaining: 13m 33s
2793:	learn: 0.0043323	total: 4m 56s	remaining: 12m 44s
2878:	learn: 0.0042607	total: 4m 56s	remaining: 12m 12s
2922:	learn: 0.0039188	total: 4m 56s	remaining: 11m 57s
2871:	learn: 0.0035758	total: 4m 56s	remaining: 12m 15s
2669:	learn: 0.0044729	total: 4m 56s	remaining: 13m 33s
2794:	learn: 0.0043302	total: 4m 56s	remaining: 12m 43s
2879:	learn: 0.0042572	total: 4m 56s	remaining: 12m 12s
2923:	learn: 0.0039163	total: 4m 56s	remaining: 11m 57s
2872:	learn: 0.0035743	total: 4m 56s	remaining: 12m 15s
2670:	learn: 0.0044705	total: 4m 56s	remaining: 13m 33s
2795:	learn: 0.0043272	total: 4m 56s	remaining: 12m 43s
2880:	learn: 0.0042549	total: 4m 56s	remaining: 12m 12s
2873:	learn: 0.0035729	total: 4m 56s	remaining: 12m 14s
2671:	learn: 0.0044671	total: 4m 56s	remaining: 13m 33s
2924:	learn: 0.0039150	total: 4m 56s	remaining: 11m 57s
2796:	learn: 0.0043252	total: 4m 56s	remaining: 12m 43s
2881:	learn: 0.0042524	total: 4m 56s	remaining: 12m 12s
2874:	learn: 0.0035715	total: 4m 56s	remaining: 12m 14s
2925:	learn: 0.0039138	total: 4m 56s	remaining: 11m 57s
2672:	learn: 0.0044650	total: 4m 56s	remaining: 13m 33s
2882:	learn: 0.0042493	total: 4m 56s	remaining: 12m 11s
2797:	learn: 0.0043227	total: 4m 56s	remaining: 12m 43s
2926:	learn: 0.0039115	total: 4m 56s	remaining: 11m 56s
2875:	learn: 0.0035702	total: 4m 56s	remaining: 12m 14s
2673:	learn: 0.0044624	total: 4m 56s	remaining: 13m 32s
2883:	learn: 0.0042465	total: 4m 56s	remaining: 12m 11s
2798:	learn: 0.0043207	total: 4m 56s	remaining: 12m 43s
2876:	learn: 0.0035680	total: 4m 56s	remaining: 12m 14s
2674:	learn: 0.0044607	total: 4m 56s	remaining: 13m 32s
2927:	learn: 0.0039096	total: 4m 56s	remaining: 11m 56s
2884:	learn: 0.0042441	total: 4m 56s	remaining: 12m 11s
2799:	learn: 0.0043193	total: 4m 56s	remaining: 12m 43s
2877:	learn: 0.0035658	total: 4m 56s	remaining: 12m 14s
2675:	learn: 0.0044571	total: 4m 56s	remaining: 13m 32s
2885:	learn: 0.0042418	total: 4m 56s	remaining: 12m 11s
2928:	learn: 0.0039074	total: 4m 56s	remaining: 11m 56s
2800:	learn: 0.0043158	total: 4m 57s	remaining: 12m 43s
2878:	learn: 0.0035640	total: 4m 56s	remaining: 12m 14s
2886:	learn: 0.0042394	total: 4m 56s	remaining: 12m 11s
2676:	learn: 0.0044546	total: 4m 57s	remaining: 13m 32s
2929:	learn: 0.0039058	total: 4m 57s	remaining: 11m 56s
2801:	learn: 0.0043141	total: 4m 57s	remaining: 12m 43s
2887:	learn: 0.0042372	total: 4m 56s	remaining: 12m 11s
2879:	learn: 0.0035619	total: 4m 57s	remaining: 12m 14s
2930:	learn: 0.0039045	total: 4m 57s	remaining: 11m 56s
2802:	learn: 0.0043121	total: 4m 57s	remaining: 12m 43s
2677:	learn: 0.0044515	total: 4m 57s	remaining: 13m 32s
2888:	learn: 0.0042343	total: 4m 57s	remaining: 12m 11s
2880:	learn: 0.0035605	total: 4m 57s	remaining: 12m 14s
2931:	learn: 0.0039032	total: 4m 57s	remaining: 11m 56s
2678:	learn: 0.0044477	total: 4m 57s	remaining: 13m 32s
2803:	learn: 0.0043106	total: 4m 57s	remaining: 12m 42s
2889:	learn: 0.0042326	total: 4m 57s	remaining: 12m 11s
2881:	learn: 0.0035585	total: 4m 57s	remaining: 12m 14s
2932:	learn: 0.0039020	total: 4m 57s	remaining: 11m 56s
2804:	learn: 0.0043083	total: 4m 57s	remaining: 12m 42s
2679:	learn: 0.0044442	total: 4m 57s	remaining: 13m 32s
2890:	learn: 0.0042290	total: 4m 57s	remaining: 12m 10s
2882:	learn: 0.0035567	total: 4m 57s	remaining: 12m 14s
2933:	learn: 0.0039004	total: 4m 57s	remaining: 11m 56s
2805:	learn: 0.0043067	total: 4m 57s	remaining: 12m 42s
2891:	learn: 0.0042268	total: 4m 57s	remaining: 12m 10s
2680:	learn: 0.0044423	total: 4m 57s	remaining: 13m 32s
2883:	learn: 0.0035545	total: 4m 57s	remaining: 12m 13s
2934:	learn: 0.0038991	total: 4m 57s	remaining: 11m 56s
2806:	learn: 0.0043047	total: 4m 57s	remaining: 12m 42s
2892:	learn: 0.0042234	total: 4m 57s	remaining: 12m 10s
2681:	learn: 0.0044403	total: 4m 57s	remaining: 13m 32s
2884:	learn: 0.0035529	total: 4m 57s	remaining: 12m 13s
2935:	learn: 0.0038965	total: 4m 57s	remaining: 11m 56s
2807:	learn: 0.0043022	total: 4m 57s	remaining: 12m 42s
2893:	learn: 0.0042211	total: 4m 57s	remaining: 12m 10s
2682:	learn: 0.0044376	total: 4m 57s	remaining: 13m 31s
2936:	learn: 0.0038933	total: 4m 57s	remaining: 11m 55s
2885:	learn: 0.0035514	total: 4m 57s	remaining: 12m 13s
2894:	learn: 0.0042196	total: 4m 57s	remaining: 12m 10s
2808:	learn: 0.0043007	total: 4m 57s	remaining: 12m 42s
2937:	learn: 0.0038917	total: 4m 57s	remaining: 11m 55s
2886:	learn: 0.0035493	total: 4m 57s	remaining: 12m 13s
2683:	learn: 0.0044341	total: 4m 57s	remaining: 13m 31s
2895:	learn: 0.0042168	total: 4m 57s	remaining: 12m 10s
2809:	learn: 0.0042993	total: 4m 57s	remaining: 12m 42s
2938:	learn: 0.0038888	total: 4m 57s	remaining: 11m 55s
2887:	learn: 0.0035472	total: 4m 57s	remaining: 12m 13s
2684:	learn: 0.0044315	total: 4m 57s	remaining: 13m 31s
2896:	learn: 0.0042145	total: 4m 57s	remaining: 12m 10s
2810:	learn: 0.0042968	total: 4m 58s	remaining: 12m 42s
2939:	learn: 0.0038869	total: 4m 58s	remaining: 11m 55s
2888:	learn: 0.0035452	total: 4m 57s	remaining: 12m 13s
2685:	learn: 0.0044283	total: 4m 58s	remaining: 13m 31s
2811:	learn: 0.0042941	total: 4m 58s	remaining: 12m 42s
2897:	learn: 0.0042129	total: 4m 57s	remaining: 12m 10s
2686:	learn: 0.0044262	total: 4m 58s	remaining: 13m 31s
2940:	learn: 0.0038849	total: 4m 58s	remaining: 11m 55s
2889:	learn: 0.0035434	total: 4m 58s	remaining: 12m 13s
2812:	learn: 0.0042918	total: 4m 58s	remaining: 12m 41s
2687:	learn: 0.0044237	total: 4m 58s	remaining: 13m 31s
2890:	learn: 0.0035422	total: 4m 58s	remaining: 12m 13s
2898:	learn: 0.0042102	total: 4m 58s	remaining: 12m 10s
2941:	learn: 0.0038823	total: 4m 58s	remaining: 11m 55s
2813:	learn: 0.0042891	total: 4m 58s	remaining: 12m 41s
2688:	learn: 0.0044204	total: 4m 58s	remaining: 13m 31s
2891:	learn: 0.0035393	total: 4m 58s	remaining: 12m 13s
2899:	learn: 0.0042066	total: 4m 58s	remaining: 12m 10s
2942:	learn: 0.0038804	total: 4m 58s	remaining: 11m 55s
2814:	learn: 0.0042867	total: 4m 58s	remaining: 12m 41s
2689:	learn: 0.0044186	total: 4m 58s	remaining: 13m 30s
2892:	learn: 0.0035366	total: 4m 58s	remaining: 12m 12s
2943:	learn: 0.0038782	total: 4m 58s	remaining: 11m 55s
2900:	learn: 0.0042043	total: 4m 58s	remaining: 12m 9s
2690:	learn: 0.0044160	total: 4m 58s	remaining: 13m 30s
2893:	learn: 0.0035349	total: 4m 58s	remaining: 12m 12s
2815:	learn: 0.0042831	total: 4m 58s	remaining: 12m 41s
2944:	learn: 0.0038767	total: 4m 58s	remaining: 11m 55s
2901:	learn: 0.0042021	total: 4m 58s	remaining: 12m 9s
2691:	learn: 0.0044132	total: 4m 58s	remaining: 13m 30s
2945:	learn: 0.0038744	total: 4m 58s	remaining: 11m 54s
2816:	learn: 0.0042813	total: 4m 58s	remaining: 12m 41s
2894:	learn: 0.0035337	total: 4m 58s	remaining: 12m 12s
2692:	learn: 0.0044096	total: 4m 58s	remaining: 13m 30s
2902:	learn: 0.0041994	total: 4m 58s	remaining: 12m 9s
2946:	learn: 0.0038717	total: 4m 58s	remaining: 11m 54s
2895:	learn: 0.0035322	total: 4m 58s	remaining: 12m 12s
2817:	learn: 0.0042796	total: 4m 58s	remaining: 12m 41s
2903:	learn: 0.0041957	total: 4m 58s	remaining: 12m 9s
2693:	learn: 0.0044072	total: 4m 58s	remaining: 13m 30s
2947:	learn: 0.0038692	total: 4m 58s	remaining: 11m 54s
2896:	learn: 0.0035306	total: 4m 58s	remaining: 12m 12s
2818:	learn: 0.0042777	total: 4m 58s	remaining: 12m 41s
2904:	learn: 0.0041935	total: 4m 58s	remaining: 12m 9s
2694:	learn: 0.0044060	total: 4m 58s	remaining: 13m 30s
2948:	learn: 0.0038680	total: 4m 58s	remaining: 11m 54s
2819:	learn: 0.0042758	total: 4m 58s	remaining: 12m 41s
2897:	learn: 0.0035288	total: 4m 58s	remaining: 12m 12s
2905:	learn: 0.0041895	total: 4m 58s	remaining: 12m 9s
2695:	learn: 0.0044035	total: 4m 58s	remaining: 13m 30s
2820:	learn: 0.0042741	total: 4m 59s	remaining: 12m 40s
2898:	learn: 0.0035278	total: 4m 58s	remaining: 12m 12s
2949:	learn: 0.0038658	total: 4m 59s	remaining: 11m 54s
2906:	learn: 0.0041866	total: 4m 58s	remaining: 12m 9s
2696:	learn: 0.0044014	total: 4m 59s	remaining: 13m 29s
2950:	learn: 0.0038646	total: 4m 59s	remaining: 11m 54s
2899:	learn: 0.0035256	total: 4m 59s	remaining: 12m 12s
2821:	learn: 0.0042727	total: 4m 59s	remaining: 12m 40s
2697:	learn: 0.0043996	total: 4m 59s	remaining: 13m 29s
2951:	learn: 0.0038622	total: 4m 59s	remaining: 11m 54s
2907:	learn: 0.0041845	total: 4m 59s	remaining: 12m 9s
2900:	learn: 0.0035226	total: 4m 59s	remaining: 12m 12s
2822:	learn: 0.0042703	total: 4m 59s	remaining: 12m 40s
2952:	learn: 0.0038604	total: 4m 59s	remaining: 11m 54s
2698:	learn: 0.0043963	total: 4m 59s	remaining: 13m 29s
2908:	learn: 0.0041818	total: 4m 59s	remaining: 12m 9s
2901:	learn: 0.0035210	total: 4m 59s	remaining: 12m 11s
2823:	learn: 0.0042674	total: 4m 59s	remaining: 12m 40s
2953:	learn: 0.0038591	total: 4m 59s	remaining: 11m 54s
2902:	learn: 0.0035193	total: 4m 59s	remaining: 12m 11s
2699:	learn: 0.0043941	total: 4m 59s	remaining: 13m 29s
2909:	learn: 0.0041796	total: 4m 59s	remaining: 12m 9s
2824:	learn: 0.0042654	total: 4m 59s	remaining: 12m 40s
2954:	learn: 0.0038578	total: 4m 59s	remaining: 11m 53s
2903:	learn: 0.0035168	total: 4m 59s	remaining: 12m 11s
2825:	learn: 0.0042642	total: 4m 59s	remaining: 12m 40s
2700:	learn: 0.0043907	total: 4m 59s	remaining: 13m 29s
2910:	learn: 0.0041771	total: 4m 59s	remaining: 12m 9s
2955:	learn: 0.0038558	total: 4m 59s	remaining: 11m 53s
2904:	learn: 0.0035148	total: 4m 59s	remaining: 12m 11s
2826:	learn: 0.0042614	total: 4m 59s	remaining: 12m 40s
2701:	learn: 0.0043879	total: 4m 59s	remaining: 13m 29s
2911:	learn: 0.0041756	total: 4m 59s	remaining: 12m 9s
2905:	learn: 0.0035133	total: 4m 59s	remaining: 12m 11s
2956:	learn: 0.0038545	total: 4m 59s	remaining: 11m 53s
2827:	learn: 0.0042599	total: 4m 59s	remaining: 12m 40s
2912:	learn: 0.0041731	total: 4m 59s	remaining: 12m 8s
2957:	learn: 0.0038518	total: 4m 59s	remaining: 11m 53s
2702:	learn: 0.0043854	total: 4m 59s	remaining: 13m 29s
2906:	learn: 0.0035111	total: 4m 59s	remaining: 12m 11s
2913:	learn: 0.0041710	total: 4m 59s	remaining: 12m 8s
2828:	learn: 0.0042576	total: 4m 59s	remaining: 12m 40s
2958:	learn: 0.0038491	total: 4m 59s	remaining: 11m 53s
2703:	learn: 0.0043823	total: 4m 59s	remaining: 13m 29s
2907:	learn: 0.0035099	total: 4m 59s	remaining: 12m 11s
2914:	learn: 0.0041693	total: 4m 59s	remaining: 12m 8s
2829:	learn: 0.0042554	total: 4m 59s	remaining: 12m 39s
2704:	learn: 0.0043806	total: 4m 59s	remaining: 13m 28s
2959:	learn: 0.0038479	total: 4m 59s	remaining: 11m 53s
2908:	learn: 0.0035084	total: 4m 59s	remaining: 12m 11s
2830:	learn: 0.0042537	total: 5m	remaining: 12m 39s
2915:	learn: 0.0041666	total: 4m 59s	remaining: 12m 8s
2705:	learn: 0.0043782	total: 5m	remaining: 13m 28s
2960:	learn: 0.0038464	total: 5m	remaining: 11m 53s
2909:	learn: 0.0035074	total: 5m	remaining: 12m 10s
2831:	learn: 0.0042522	total: 5m	remaining: 12m 39s
2916:	learn: 0.0041652	total: 4m 59s	remaining: 12m 8s
2706:	learn: 0.0043759	total: 5m	remaining: 13m 28s
2961:	learn: 0.0038445	total: 5m	remaining: 11m 53s
2910:	learn: 0.0035050	total: 5m	remaining: 12m 10s
2832:	learn: 0.0042506	total: 5m	remaining: 12m 39s
2707:	learn: 0.0043722	total: 5m	remaining: 13m 28s
2917:	learn: 0.0041631	total: 5m	remaining: 12m 8s
2911:	learn: 0.0035032	total: 5m	remaining: 12m 10s
2962:	learn: 0.0038428	total: 5m	remaining: 11m 53s
2833:	learn: 0.0042492	total: 5m	remaining: 12m 39s
2708:	learn: 0.0043705	total: 5m	remaining: 13m 28s
2918:	learn: 0.0041605	total: 5m	remaining: 12m 8s
2963:	learn: 0.0038413	total: 5m	remaining: 11m 52s
2912:	learn: 0.0035009	total: 5m	remaining: 12m 10s
2834:	learn: 0.0042462	total: 5m	remaining: 12m 39s
2964:	learn: 0.0038389	total: 5m	remaining: 11m 52s
2709:	learn: 0.0043672	total: 5m	remaining: 13m 28s
2919:	learn: 0.0041589	total: 5m	remaining: 12m 8s
2913:	learn: 0.0034995	total: 5m	remaining: 12m 10s
2835:	learn: 0.0042447	total: 5m	remaining: 12m 39s
2920:	learn: 0.0041556	total: 5m	remaining: 12m 8s
2965:	learn: 0.0038377	total: 5m	remaining: 11m 52s
2914:	learn: 0.0034970	total: 5m	remaining: 12m 10s
2710:	learn: 0.0043657	total: 5m	remaining: 13m 28s
2836:	learn: 0.0042428	total: 5m	remaining: 12m 39s
2921:	learn: 0.0041530	total: 5m	remaining: 12m 7s
2966:	learn: 0.0038355	total: 5m	remaining: 11m 52s
2915:	learn: 0.0034960	total: 5m	remaining: 12m 10s
2711:	learn: 0.0043624	total: 5m	remaining: 13m 28s
2837:	learn: 0.0042394	total: 5m	remaining: 12m 38s
2922:	learn: 0.0041504	total: 5m	remaining: 12m 7s
2916:	learn: 0.0034945	total: 5m	remaining: 12m 10s
2967:	learn: 0.0038331	total: 5m	remaining: 11m 52s
2838:	learn: 0.0042370	total: 5m	remaining: 12m 38s
2712:	learn: 0.0043602	total: 5m	remaining: 13m 27s
2917:	learn: 0.0034927	total: 5m	remaining: 12m 9s
2923:	learn: 0.0041473	total: 5m	remaining: 12m 7s
2968:	learn: 0.0038309	total: 5m	remaining: 11m 52s
2918:	learn: 0.0034901	total: 5m	remaining: 12m 9s
2839:	learn: 0.0042349	total: 5m	remaining: 12m 38s
2713:	learn: 0.0043566	total: 5m	remaining: 13m 27s
2969:	learn: 0.0038292	total: 5m	remaining: 11m 52s
2924:	learn: 0.0041438	total: 5m	remaining: 12m 7s
2840:	learn: 0.0042314	total: 5m 1s	remaining: 12m 38s
2919:	learn: 0.0034887	total: 5m	remaining: 12m 9s
2714:	learn: 0.0043535	total: 5m 1s	remaining: 13m 27s
2925:	learn: 0.0041416	total: 5m	remaining: 12m 7s
2970:	learn: 0.0038280	total: 5m 1s	remaining: 11m 52s
2841:	learn: 0.0042304	total: 5m 1s	remaining: 12m 38s
2920:	learn: 0.0034867	total: 5m 1s	remaining: 12m 9s
2926:	learn: 0.0041390	total: 5m 1s	remaining: 12m 7s
2971:	learn: 0.0038262	total: 5m 1s	remaining: 11m 52s
2842:	learn: 0.0042283	total: 5m 1s	remaining: 12m 38s
2715:	learn: 0.0043518	total: 5m 1s	remaining: 13m 27s
2921:	learn: 0.0034853	total: 5m 1s	remaining: 12m 9s
2927:	learn: 0.0041368	total: 5m 1s	remaining: 12m 7s
2843:	learn: 0.0042266	total: 5m 1s	remaining: 12m 38s
2922:	learn: 0.0034835	total: 5m 1s	remaining: 12m 9s
2972:	learn: 0.0038240	total: 5m 1s	remaining: 11m 52s
2716:	learn: 0.0043494	total: 5m 1s	remaining: 13m 27s
2928:	learn: 0.0041341	total: 5m 1s	remaining: 12m 7s
2973:	learn: 0.0038226	total: 5m 1s	remaining: 11m 51s
2844:	learn: 0.0042244	total: 5m 1s	remaining: 12m 38s
2923:	learn: 0.0034813	total: 5m 1s	remaining: 12m 9s
2717:	learn: 0.0043467	total: 5m 1s	remaining: 13m 27s
2929:	learn: 0.0041317	total: 5m 1s	remaining: 12m 7s
2974:	learn: 0.0038214	total: 5m 1s	remaining: 11m 51s
2845:	learn: 0.0042228	total: 5m 1s	remaining: 12m 37s
2924:	learn: 0.0034799	total: 5m 1s	remaining: 12m 9s
2930:	learn: 0.0041302	total: 5m 1s	remaining: 12m 6s
2718:	learn: 0.0043440	total: 5m 1s	remaining: 13m 27s
2975:	learn: 0.0038202	total: 5m 1s	remaining: 11m 51s
2846:	learn: 0.0042195	total: 5m 1s	remaining: 12m 37s
2925:	learn: 0.0034773	total: 5m 1s	remaining: 12m 8s
2719:	learn: 0.0043412	total: 5m 1s	remaining: 13m 27s

2931:	learn: 0.0041275	total: 5m 1s	remaining: 12m 6s
2976:	learn: 0.0038192	total: 5m 1s	remaining: 11m 51s
2847:	learn: 0.0042173	total: 5m 1s	remaining: 12m 37s
2926:	learn: 0.0034748	total: 5m 1s	remaining: 12m 8s
2720:	learn: 0.0043388	total: 5m 1s	remaining: 13m 27s
2977:	learn: 0.0038175	total: 5m 1s	remaining: 11m 51s
2932:	learn: 0.0041253	total: 5m 1s	remaining: 12m 6s
2721:	learn: 0.0043366	total: 5m 1s	remaining: 13m 26s
2927:	learn: 0.0034733	total: 5m 1s	remaining: 12m 8s
2848:	learn: 0.0042151	total: 5m 1s	remaining: 12m 37s
2978:	learn: 0.0038154	total: 5m 1s	remaining: 11m 51s
2933:	learn: 0.0041222	total: 5m 1s	remaining: 12m 6s
2928:	learn: 0.0034719	total: 5m 1s	remaining: 12m 8s
2722:	learn: 0.0043347	total: 5m 1s	remaining: 13m 26s
2849:	learn: 0.0042127	total: 5m 1s	remaining: 12m 37s
2979:	learn: 0.0038132	total: 5m 1s	remaining: 11m 51s
2929:	learn: 0.0034700	total: 5m 1s	remaining: 12m 8s
2850:	learn: 0.0042102	total: 5m 2s	remaining: 12m 37s
2930:	learn: 0.0034680	total: 5m 1s	remaining: 12m 8s
2723:	learn: 0.0043316	total: 5m 2s	remaining: 13m 26s
2934:	learn: 0.0041201	total: 5m 1s	remaining: 12m 6s
2980:	learn: 0.0038111	total: 5m 2s	remaining: 11m 51s
2724:	learn: 0.0043284	total: 5m 2s	remaining: 13m 26s
2851:	learn: 0.0042083	total: 5m 2s	remaining: 12m 37s
2981:	learn: 0.0038093	total: 5m 2s	remaining: 11m 51s
2931:	learn: 0.0034663	total: 5m 2s	remaining: 12m 8s
2935:	learn: 0.0041176	total: 5m 2s	remaining: 12m 6s
2725:	learn: 0.0043266	total: 5m 2s	remaining: 13m 26s
2936:	learn: 0.0041152	total: 5m 2s	remaining: 12m 6s
2982:	learn: 0.0038069	total: 5m 2s	remaining: 11m 50s
2852:	learn: 0.0042065	total: 5m 2s	remaining: 12m 37s
2932:	learn: 0.0034634	total: 5m 2s	remaining: 12m 8s
2726:	learn: 0.0043241	total: 5m 2s	remaining: 13m 26s
2937:	learn: 0.0041127	total: 5m 2s	remaining: 12m 6s
2983:	learn: 0.0038052	total: 5m 2s	remaining: 11m 50s
2933:	learn: 0.0034607	total: 5m 2s	remaining: 12m 8s
2853:	learn: 0.0042042	total: 5m 2s	remaining: 12m 37s
2727:	learn: 0.0043210	total: 5m 2s	remaining: 13m 26s
2938:	learn: 0.0041102	total: 5m 2s	remaining: 12m 6s
2984:	learn: 0.0038037	total: 5m 2s	remaining: 11m 50s
2728:	learn: 0.0043183	total: 5m 2s	remaining: 13m 25s
2934:	learn: 0.0034579	total: 5m 2s	remaining: 12m 7s
2854:	learn: 0.0042026	total: 5m 2s	remaining: 12m 37s
2939:	learn: 0.0041070	total: 5m 2s	remaining: 12m 6s
2985:	learn: 0.0038026	total: 5m 2s	remaining: 11m 50s
2729:	learn: 0.0043155	total: 5m 2s	remaining: 13m 25s
2986:	learn: 0.0038009	total: 5m 2s	remaining: 11m 50s
2855:	learn: 0.0041996	total: 5m 2s	remaining: 12m 36s
2940:	learn: 0.0041044	total: 5m 2s	remaining: 12m 5s
2935:	learn: 0.0034568	total: 5m 2s	remaining: 12m 7s
2730:	learn: 0.0043128	total: 5m 2s	remaining: 13m 25s
2987:	learn: 0.0037983	total: 5m 2s	remaining: 11m 50s
2856:	learn: 0.0041963	total: 5m 2s	remaining: 12m 36s
2936:	learn: 0.0034554	total: 5m 2s	remaining: 12m 7s
2941:	learn: 0.0041016	total: 5m 2s	remaining: 12m 5s
2731:	learn: 0.0043107	total: 5m 2s	remaining: 13m 25s
2942:	learn: 0.0041000	total: 5m 2s	remaining: 12m 5s
2988:	learn: 0.0037963	total: 5m 2s	remaining: 11m 50s
2857:	learn: 0.0041941	total: 5m 2s	remaining: 12m 36s
2937:	learn: 0.0034542	total: 5m 2s	remaining: 12m 7s
2732:	learn: 0.0043078	total: 5m 2s	remaining: 13m 25s
2943:	learn: 0.0040976	total: 5m 2s	remaining: 12m 5s
2858:	learn: 0.0041926	total: 5m 2s	remaining: 12m 36s
2989:	learn: 0.0037951	total: 5m 2s	remaining: 11m 50s
2938:	learn: 0.0034517	total: 5m 2s	remaining: 12m 7s
2733:	learn: 0.0043059	total: 5m 2s	remaining: 13m 25s
2939:	learn: 0.0034494	total: 5m 2s	remaining: 12m 7s
2859:	learn: 0.0041901	total: 5m 3s	remaining: 12m 36s
2990:	learn: 0.0037932	total: 5m 2s	remaining: 11m 50s
2944:	learn: 0.0040956	total: 5m 2s	remaining: 12m 5s
2940:	learn: 0.0034471	total: 5m 2s	remaining: 12m 7s
2860:	learn: 0.0041882	total: 5m 3s	remaining: 12m 36s
2734:	learn: 0.0043028	total: 5m 3s	remaining: 13m 25s
2991:	learn: 0.0037908	total: 5m 3s	remaining: 11m 49s
2945:	learn: 0.0040927	total: 5m 3s	remaining: 12m 5s
2941:	learn: 0.0034450	total: 5m 3s	remaining: 12m 7s
2735:	learn: 0.0043007	total: 5m 3s	remaining: 13m 24s
2861:	learn: 0.0041860	total: 5m 3s	remaining: 12m 36s
2992:	learn: 0.0037894	total: 5m 3s	remaining: 11m 49s
2946:	learn: 0.0040894	total: 5m 3s	remaining: 12m 5s
2942:	learn: 0.0034424	total: 5m 3s	remaining: 12m 7s
2736:	learn: 0.0042980	total: 5m 3s	remaining: 13m 24s
2862:	learn: 0.0041839	total: 5m 3s	remaining: 12m 36s
2993:	learn: 0.0037875	total: 5m 3s	remaining: 11m 49s
2947:	learn: 0.0040867	total: 5m 3s	remaining: 12m 5s
2943:	learn: 0.0034411	total: 5m 3s	remaining: 12m 6s
2737:	learn: 0.0042958	total: 5m 3s	remaining: 13m 24s
2948:	learn: 0.0040847	total: 5m 3s	remaining: 12m 5s
2863:	learn: 0.0041816	total: 5m 3s	remaining: 12m 36s
2994:	learn: 0.0037853	total: 5m 3s	remaining: 11m 49s
2944:	learn: 0.0034387	total: 5m 3s	remaining: 12m 6s
2949:	learn: 0.0040826	total: 5m 3s	remaining: 12m 4s
2738:	learn: 0.0042931	total: 5m 3s	remaining: 13m 24s
2864:	learn: 0.0041789	total: 5m 3s	remaining: 12m 36s
2995:	learn: 0.0037828	total: 5m 3s	remaining: 11m 49s
2950:	learn: 0.0040811	total: 5m 3s	remaining: 12m 4s
2945:	learn: 0.0034360	total: 5m 3s	remaining: 12m 6s
2739:	learn: 0.0042899	total: 5m 3s	remaining: 13m 24s
2865:	learn: 0.0041767	total: 5m 3s	remaining: 12m 35s
2996:	learn: 0.0037808	total: 5m 3s	remaining: 11m 49s
2951:	learn: 0.0040785	total: 5m 3s	remaining: 12m 4s
2946:	learn: 0.0034340	total: 5m 3s	remaining: 12m 6s
2740:	learn: 0.0042869	total: 5m 3s	remaining: 13m 24s
2997:	learn: 0.0037782	total: 5m 3s	remaining: 11m 49s
2866:	learn: 0.0041748	total: 5m 3s	remaining: 12m 35s
2947:	learn: 0.0034318	total: 5m 3s	remaining: 12m 6s
2952:	learn: 0.0040763	total: 5m 3s	remaining: 12m 4s
2741:	learn: 0.0042854	total: 5m 3s	remaining: 13m 24s
2867:	learn: 0.0041728	total: 5m 3s	remaining: 12m 35s
2998:	learn: 0.0037765	total: 5m 3s	remaining: 11m 49s
2953:	learn: 0.0040751	total: 5m 3s	remaining: 12m 4s
2948:	learn: 0.0034297	total: 5m 3s	remaining: 12m 6s
2868:	learn: 0.0041702	total: 5m 3s	remaining: 12m 35s
2742:	learn: 0.0042838	total: 5m 3s	remaining: 13m 24s
2999:	learn: 0.0037754	total: 5m 3s	remaining: 11m 49s
2949:	learn: 0.0034280	total: 5m 3s	remaining: 12m 6s
2954:	learn: 0.0040722	total: 5m 3s	remaining: 12m 4s
2869:	learn: 0.0041691	total: 5m 4s	remaining: 12m 35s
2743:	learn: 0.0042803	total: 5m 4s	remaining: 13m 23s
3000:	learn: 0.0037729	total: 5m 4s	remaining: 11m 49s
2950:	learn: 0.0034258	total: 5m 4s	remaining: 12m 6s
2955:	learn: 0.0040696	total: 5m 3s	remaining: 12m 4s
2744:	learn: 0.0042788	total: 5m 4s	remaining: 13m 23s
2870:	learn: 0.0041667	total: 5m 4s	remaining: 12m 35s
3001:	learn: 0.0037718	total: 5m 4s	remaining: 11m 48s
2951:	learn: 0.0034240	total: 5m 4s	remaining: 12m 6s
2745:	learn: 0.0042765	total: 5m 4s	remaining: 13m 23s
2871:	learn: 0.0041643	total: 5m 4s	remaining: 12m 35s
3002:	learn: 0.0037701	total: 5m 4s	remaining: 11m 48s
2956:	learn: 0.0040670	total: 5m 4s	remaining: 12m 4s
2952:	learn: 0.0034220	total: 5m 4s	remaining: 12m 5s
2746:	learn: 0.0042745	total: 5m 4s	remaining: 13m 23s
3003:	learn: 0.0037674	total: 5m 4s	remaining: 11m 48s
2872:	learn: 0.0041622	total: 5m 4s	remaining: 12m 35s
2957:	learn: 0.0040656	total: 5m 4s	remaining: 12m 4s
2953:	learn: 0.0034201	total: 5m 4s	remaining: 12m 5s
2747:	learn: 0.0042725	total: 5m 4s	remaining: 13m 23s
3004:	learn: 0.0037662	total: 5m 4s	remaining: 11m 48s
2954:	learn: 0.0034182	total: 5m 4s	remaining: 12m 5s
2873:	learn: 0.0041602	total: 5m 4s	remaining: 12m 34s
2958:	learn: 0.0040630	total: 5m 4s	remaining: 12m 4s
3005:	learn: 0.0037642	total: 5m 4s	remaining: 11m 48s
2748:	learn: 0.0042697	total: 5m 4s	remaining: 13m 23s
2955:	learn: 0.0034155	total: 5m 4s	remaining: 12m 5s
2874:	learn: 0.0041586	total: 5m 4s	remaining: 12m 34s
2959:	learn: 0.0040605	total: 5m 4s	remaining: 12m 4s
2749:	learn: 0.0042684	total: 5m 4s	remaining: 13m 23s
3006:	learn: 0.0037629	total: 5m 4s	remaining: 11m 48s
2956:	learn: 0.0034140	total: 5m 4s	remaining: 12m 5s
2875:	learn: 0.0041566	total: 5m 4s	remaining: 12m 34s
2960:	learn: 0.0040585	total: 5m 4s	remaining: 12m 3s
2957:	learn: 0.0034118	total: 5m 4s	remaining: 12m 5s
3007:	learn: 0.0037603	total: 5m 4s	remaining: 11m 48s
2961:	learn: 0.0040569	total: 5m 4s	remaining: 12m 3s
2750:	learn: 0.0042656	total: 5m 4s	remaining: 13m 23s
2876:	learn: 0.0041549	total: 5m 4s	remaining: 12m 34s
2962:	learn: 0.0040548	total: 5m 4s	remaining: 12m 3s
2958:	learn: 0.0034101	total: 5m 4s	remaining: 12m 5s
2877:	learn: 0.0041517	total: 5m 4s	remaining: 12m 34s
3008:	learn: 0.0037592	total: 5m 4s	remaining: 11m 48s
2751:	learn: 0.0042631	total: 5m 4s	remaining: 13m 23s
2963:	learn: 0.0040525	total: 5m 4s	remaining: 12m 3s
2959:	learn: 0.0034076	total: 5m 4s	remaining: 12m 5s
2878:	learn: 0.0041491	total: 5m 4s	remaining: 12m 34s
3009:	learn: 0.0037570	total: 5m 4s	remaining: 11m 48s
2964:	learn: 0.0040506	total: 5m 4s	remaining: 12m 3s
2752:	learn: 0.0042604	total: 5m 5s	remaining: 13m 22s
2960:	learn: 0.0034063	total: 5m 4s	remaining: 12m 4s
2879:	learn: 0.0041466	total: 5m 5s	remaining: 12m 34s
3010:	learn: 0.0037548	total: 5m 5s	remaining: 11m 48s
2965:	learn: 0.0040475	total: 5m 4s	remaining: 12m 3s
2753:	learn: 0.0042581	total: 5m 5s	remaining: 13m 22s
2961:	learn: 0.0034047	total: 5m 5s	remaining: 12m 4s
3011:	learn: 0.0037537	total: 5m 5s	remaining: 11m 47s
2880:	learn: 0.0041443	total: 5m 5s	remaining: 12m 34s
2966:	learn: 0.0040450	total: 5m 5s	remaining: 12m 3s
2754:	learn: 0.0042564	total: 5m 5s	remaining: 13m 22s
2962:	learn: 0.0034024	total: 5m 5s	remaining: 12m 4s
3012:	learn: 0.0037516	total: 5m 5s	remaining: 11m 47s
2881:	learn: 0.0041416	total: 5m 5s	remaining: 12m 34s
2967:	learn: 0.0040429	total: 5m 5s	remaining: 12m 3s
3013:	learn: 0.0037500	total: 5m 5s	remaining: 11m 47s
2755:	learn: 0.0042538	total: 5m 5s	remaining: 13m 22s
2963:	learn: 0.0034002	total: 5m 5s	remaining: 12m 4s
2882:	learn: 0.0041396	total: 5m 5s	remaining: 12m 33s
2968:	learn: 0.0040408	total: 5m 5s	remaining: 12m 2s
3014:	learn: 0.0037488	total: 5m 5s	remaining: 11m 47s
2964:	learn: 0.0033977	total: 5m 5s	remaining: 12m 4s
2756:	learn: 0.0042511	total: 5m 5s	remaining: 13m 22s
2969:	learn: 0.0040383	total: 5m 5s	remaining: 12m 2s
2883:	learn: 0.0041382	total: 5m 5s	remaining: 12m 33s
2757:	learn: 0.0042488	total: 5m 5s	remaining: 13m 22s
3015:	learn: 0.0037458	total: 5m 5s	remaining: 11m 47s
2965:	learn: 0.0033958	total: 5m 5s	remaining: 12m 4s
2970:	learn: 0.0040358	total: 5m 5s	remaining: 12m 2s
2884:	learn: 0.0041364	total: 5m 5s	remaining: 12m 33s
2758:	learn: 0.0042465	total: 5m 5s	remaining: 13m 22s
2966:	learn: 0.0033936	total: 5m 5s	remaining: 12m 4s
3016:	learn: 0.0037445	total: 5m 5s	remaining: 11m 47s
2971:	learn: 0.0040339	total: 5m 5s	remaining: 12m 2s
2885:	learn: 0.0041334	total: 5m 5s	remaining: 12m 33s
2967:	learn: 0.0033921	total: 5m 5s	remaining: 12m 4s
2972:	learn: 0.0040319	total: 5m 5s	remaining: 12m 2s
2759:	learn: 0.0042443	total: 5m 5s	remaining: 13m 22s
3017:	learn: 0.0037426	total: 5m 5s	remaining: 11m 47s
2886:	learn: 0.0041312	total: 5m 5s	remaining: 12m 33s
2968:	learn: 0.0033902	total: 5m 5s	remaining: 12m 4s
2760:	learn: 0.0042408	total: 5m 5s	remaining: 13m 21s
2973:	learn: 0.0040299	total: 5m 5s	remaining: 12m 2s
2887:	learn: 0.0041299	total: 5m 5s	remaining: 12m 33s
3018:	learn: 0.0037412	total: 5m 5s	remaining: 11m 47s
2969:	learn: 0.0033885	total: 5m 5s	remaining: 12m 3s
2761:	learn: 0.0042379	total: 5m 5s	remaining: 13m 21s
2974:	learn: 0.0040269	total: 5m 5s	remaining: 12m 2s
2888:	learn: 0.0041280	total: 5m 5s	remaining: 12m 33s
3019:	learn: 0.0037402	total: 5m 5s	remaining: 11m 47s
2970:	learn: 0.0033869	total: 5m 5s	remaining: 12m 3s
2889:	learn: 0.0041247	total: 5m 6s	remaining: 12m 32s
2762:	learn: 0.0042360	total: 5m 6s	remaining: 13m 21s
2975:	learn: 0.0040249	total: 5m 5s	remaining: 12m 2s
3020:	learn: 0.0037383	total: 5m 6s	remaining: 11m 47s
2971:	learn: 0.0033849	total: 5m 6s	remaining: 12m 3s
2890:	learn: 0.0041240	total: 5m 6s	remaining: 12m 32s
2763:	learn: 0.0042343	total: 5m 6s	remaining: 13m 21s
2976:	learn: 0.0040225	total: 5m 6s	remaining: 12m 2s
3021:	learn: 0.0037351	total: 5m 6s	remaining: 11m 47s
2972:	learn: 0.0033830	total: 5m 6s	remaining: 12m 3s
2891:	learn: 0.0041227	total: 5m 6s	remaining: 12m 32s
2977:	learn: 0.0040199	total: 5m 6s	remaining: 12m 1s
2764:	learn: 0.0042316	total: 5m 6s	remaining: 13m 21s
3022:	learn: 0.0037328	total: 5m 6s	remaining: 11m 46s
2892:	learn: 0.0041210	total: 5m 6s	remaining: 12m 32s
2973:	learn: 0.0033804	total: 5m 6s	remaining: 12m 3s
2978:	learn: 0.0040175	total: 5m 6s	remaining: 12m 1s
2765:	learn: 0.0042294	total: 5m 6s	remaining: 13m 21s
3023:	learn: 0.0037308	total: 5m 6s	remaining: 11m 46s
2979:	learn: 0.0040148	total: 5m 6s	remaining: 12m 1s
2893:	learn: 0.0041190	total: 5m 6s	remaining: 12m 32s
2974:	learn: 0.0033785	total: 5m 6s	remaining: 12m 3s
2766:	learn: 0.0042267	total: 5m 6s	remaining: 13m 21s
2975:	learn: 0.0033762	total: 5m 6s	remaining: 12m 3s
2980:	learn: 0.0040127	total: 5m 6s	remaining: 12m 1s
2894:	learn: 0.0041172	total: 5m 6s	remaining: 12m 32s
2767:	learn: 0.0042233	total: 5m 6s	remaining: 13m 20s
3024:	learn: 0.0037287	total: 5m 6s	remaining: 11m 46s
2976:	learn: 0.0033740	total: 5m 6s	remaining: 12m 3s
2981:	learn: 0.0040102	total: 5m 6s	remaining: 12m 1s
2977:	learn: 0.0033723	total: 5m 6s	remaining: 12m 2s
2895:	learn: 0.0041140	total: 5m 6s	remaining: 12m 32s
3025:	learn: 0.0037273	total: 5m 6s	remaining: 11m 46s
2768:	learn: 0.0042206	total: 5m 6s	remaining: 13m 20s
2982:	learn: 0.0040077	total: 5m 6s	remaining: 12m 1s
3026:	learn: 0.0037253	total: 5m 6s	remaining: 11m 46s
2978:	learn: 0.0033704	total: 5m 6s	remaining: 12m 2s
2983:	learn: 0.0040059	total: 5m 6s	remaining: 12m 1s
2896:	learn: 0.0041128	total: 5m 6s	remaining: 12m 32s
2769:	learn: 0.0042180	total: 5m 6s	remaining: 13m 20s
3027:	learn: 0.0037232	total: 5m 6s	remaining: 11m 46s
2979:	learn: 0.0033688	total: 5m 6s	remaining: 12m 2s
2984:	learn: 0.0040040	total: 5m 6s	remaining: 12m
2897:	learn: 0.0041106	total: 5m 6s	remaining: 12m 32s
3028:	learn: 0.0037212	total: 5m 6s	remaining: 11m 46s
2770:	learn: 0.0042147	total: 5m 6s	remaining: 13m 20s
2985:	learn: 0.0040018	total: 5m 6s	remaining: 12m
2980:	learn: 0.0033674	total: 5m 6s	remaining: 12m 2s
2898:	learn: 0.0041090	total: 5m 7s	remaining: 12m 32s
3029:	learn: 0.0037199	total: 5m 6s	remaining: 11m 46s
2986:	learn: 0.0039994	total: 5m 6s	remaining: 12m
2771:	learn: 0.0042117	total: 5m 7s	remaining: 13m 20s
2899:	learn: 0.0041064	total: 5m 7s	remaining: 12m 31s
2981:	learn: 0.0033657	total: 5m 7s	remaining: 12m 2s
3030:	learn: 0.0037174	total: 5m 7s	remaining: 11m 46s
2772:	learn: 0.0042099	total: 5m 7s	remaining: 13m 20s
2900:	learn: 0.0041048	total: 5m 7s	remaining: 12m 31s
2987:	learn: 0.0039975	total: 5m 7s	remaining: 12m
2982:	learn: 0.0033636	total: 5m 7s	remaining: 12m 2s
3031:	learn: 0.0037149	total: 5m 7s	remaining: 11m 46s
2773:	learn: 0.0042078	total: 5m 7s	remaining: 13m 20s
2901:	learn: 0.0041032	total: 5m 7s	remaining: 12m 31s
2988:	learn: 0.0039962	total: 5m 7s	remaining: 12m
2983:	learn: 0.0033623	total: 5m 7s	remaining: 12m 2s
3032:	learn: 0.0037138	total: 5m 7s	remaining: 11m 45s
2774:	learn: 0.0042052	total: 5m 7s	remaining: 13m 20s
2902:	learn: 0.0041014	total: 5m 7s	remaining: 12m 31s
2984:	learn: 0.0033606	total: 5m 7s	remaining: 12m 2s
3033:	learn: 0.0037117	total: 5m 7s	remaining: 11m 45s
2989:	learn: 0.0039945	total: 5m 7s	remaining: 12m
2775:	learn: 0.0042032	total: 5m 7s	remaining: 13m 20s
2903:	learn: 0.0040991	total: 5m 7s	remaining: 12m 31s
2985:	learn: 0.0033581	total: 5m 7s	remaining: 12m 2s
3034:	learn: 0.0037095	total: 5m 7s	remaining: 11m 45s
2990:	learn: 0.0039925	total: 5m 7s	remaining: 12m
2776:	learn: 0.0042004	total: 5m 7s	remaining: 13m 19s
2904:	learn: 0.0040965	total: 5m 7s	remaining: 12m 31s
2986:	learn: 0.0033568	total: 5m 7s	remaining: 12m 1s
3035:	learn: 0.0037075	total: 5m 7s	remaining: 11m 45s
2991:	learn: 0.0039900	total: 5m 7s	remaining: 12m
2777:	learn: 0.0041983	total: 5m 7s	remaining: 13m 19s
3036:	learn: 0.0037059	total: 5m 7s	remaining: 11m 45s
2987:	learn: 0.0033555	total: 5m 7s	remaining: 12m 1s

2905:	learn: 0.0040946	total: 5m 7s	remaining: 12m 31s
2992:	learn: 0.0039882	total: 5m 7s	remaining: 12m
3037:	learn: 0.0037042	total: 5m 7s	remaining: 11m 45s
2778:	learn: 0.0041956	total: 5m 7s	remaining: 13m 19s
2988:	learn: 0.0033543	total: 5m 7s	remaining: 12m 1s
2906:	learn: 0.0040935	total: 5m 7s	remaining: 12m 31s
2993:	learn: 0.0039863	total: 5m 7s	remaining: 11m 59s
3038:	learn: 0.0037028	total: 5m 7s	remaining: 11m 45s
2989:	learn: 0.0033529	total: 5m 7s	remaining: 12m 1s
2779:	learn: 0.0041932	total: 5m 7s	remaining: 13m 19s
2907:	learn: 0.0040915	total: 5m 7s	remaining: 12m 30s
2994:	learn: 0.0039839	total: 5m 7s	remaining: 11m 59s
3039:	learn: 0.0037015	total: 5m 7s	remaining: 11m 45s
2990:	learn: 0.0033511	total: 5m 7s	remaining: 12m 1s
2908:	learn: 0.0040894	total: 5m 8s	remaining: 12m 30s
2780:	learn: 0.0041908	total: 5m 7s	remaining: 13m 19s
2995:	learn: 0.0039811	total: 5m 7s	remaining: 11m 59s
2991:	learn: 0.0033483	total: 5m 7s	remaining: 12m 1s
3040:	learn: 0.0036990	total: 5m 8s	remaining: 11m 44s
2996:	learn: 0.0039788	total: 5m 7s	remaining: 11m 59s
2781:	learn: 0.0041885	total: 5m 8s	remaining: 13m 19s
2909:	learn: 0.0040880	total: 5m 8s	remaining: 12m 30s
3041:	learn: 0.0036971	total: 5m 8s	remaining: 11m 44s
2997:	learn: 0.0039765	total: 5m 8s	remaining: 11m 59s
2992:	learn: 0.0033465	total: 5m 8s	remaining: 12m 1s
2782:	learn: 0.0041853	total: 5m 8s	remaining: 13m 19s
2910:	learn: 0.0040858	total: 5m 8s	remaining: 12m 30s
3042:	learn: 0.0036950	total: 5m 8s	remaining: 11m 44s
2998:	learn: 0.0039758	total: 5m 8s	remaining: 11m 59s
2993:	learn: 0.0033441	total: 5m 8s	remaining: 12m 1s
2911:	learn: 0.0040826	total: 5m 8s	remaining: 12m 30s
2783:	learn: 0.0041832	total: 5m 8s	remaining: 13m 19s
2999:	learn: 0.0039737	total: 5m 8s	remaining: 11m 59s
3043:	learn: 0.0036935	total: 5m 8s	remaining: 11m 44s
2912:	learn: 0.0040810	total: 5m 8s	remaining: 12m 30s
2994:	learn: 0.0033414	total: 5m 8s	remaining: 12m 1s
2784:	learn: 0.0041805	total: 5m 8s	remaining: 13m 19s
3000:	learn: 0.0039710	total: 5m 8s	remaining: 11m 59s
3044:	learn: 0.0036910	total: 5m 8s	remaining: 11m 44s
2995:	learn: 0.0033396	total: 5m 8s	remaining: 12m
2913:	learn: 0.0040789	total: 5m 8s	remaining: 12m 30s
2785:	learn: 0.0041772	total: 5m 8s	remaining: 13m 18s
3001:	learn: 0.0039688	total: 5m 8s	remaining: 11m 58s
3045:	learn: 0.0036885	total: 5m 8s	remaining: 11m 44s
2996:	learn: 0.0033371	total: 5m 8s	remaining: 12m
2914:	learn: 0.0040758	total: 5m 8s	remaining: 12m 30s
2786:	learn: 0.0041751	total: 5m 8s	remaining: 13m 18s
2997:	learn: 0.0033343	total: 5m 8s	remaining: 12m
3002:	learn: 0.0039666	total: 5m 8s	remaining: 11m 58s
3046:	learn: 0.0036875	total: 5m 8s	remaining: 11m 44s
2915:	learn: 0.0040734	total: 5m 8s	remaining: 12m 29s
2998:	learn: 0.0033327	total: 5m 8s	remaining: 12m
3003:	learn: 0.0039646	total: 5m 8s	remaining: 11m 58s
2787:	learn: 0.0041730	total: 5m 8s	remaining: 13m 18s
2916:	learn: 0.0040708	total: 5m 8s	remaining: 12m 29s
3047:	learn: 0.0036858	total: 5m 8s	remaining: 11m 44s
2999:	learn: 0.0033314	total: 5m 8s	remaining: 12m
3004:	learn: 0.0039619	total: 5m 8s	remaining: 11m 58s
3048:	learn: 0.0036834	total: 5m 8s	remaining: 11m 44s
2788:	learn: 0.0041713	total: 5m 8s	remaining: 13m 18s
2917:	learn: 0.0040681	total: 5m 8s	remaining: 12m 29s
3000:	learn: 0.0033300	total: 5m 8s	remaining: 12m
3005:	learn: 0.0039601	total: 5m 8s	remaining: 11m 58s
3049:	learn: 0.0036812	total: 5m 8s	remaining: 11m 44s
2789:	learn: 0.0041694	total: 5m 9s	remaining: 13m 18s
2918:	learn: 0.0040662	total: 5m 9s	remaining: 12m 29s
3001:	learn: 0.0033289	total: 5m 8s	remaining: 12m
3006:	learn: 0.0039577	total: 5m 8s	remaining: 11m 58s
3050:	learn: 0.0036802	total: 5m 9s	remaining: 11m 44s
2919:	learn: 0.0040633	total: 5m 9s	remaining: 12m 29s
2790:	learn: 0.0041671	total: 5m 9s	remaining: 13m 18s
3002:	learn: 0.0033271	total: 5m 9s	remaining: 12m
3007:	learn: 0.0039558	total: 5m 9s	remaining: 11m 58s
2920:	learn: 0.0040612	total: 5m 9s	remaining: 12m 29s
3051:	learn: 0.0036777	total: 5m 9s	remaining: 11m 43s
3003:	learn: 0.0033258	total: 5m 9s	remaining: 12m
2791:	learn: 0.0041649	total: 5m 9s	remaining: 13m 18s
2921:	learn: 0.0040581	total: 5m 9s	remaining: 12m 29s
3052:	learn: 0.0036765	total: 5m 9s	remaining: 11m 43s
3008:	learn: 0.0039531	total: 5m 9s	remaining: 11m 58s
3004:	learn: 0.0033242	total: 5m 9s	remaining: 11m 59s
3053:	learn: 0.0036752	total: 5m 9s	remaining: 11m 43s
2922:	learn: 0.0040568	total: 5m 9s	remaining: 12m 29s
3009:	learn: 0.0039514	total: 5m 9s	remaining: 11m 58s
2792:	learn: 0.0041619	total: 5m 9s	remaining: 13m 18s
3005:	learn: 0.0033220	total: 5m 9s	remaining: 11m 59s
3054:	learn: 0.0036735	total: 5m 9s	remaining: 11m 43s
2923:	learn: 0.0040550	total: 5m 9s	remaining: 12m 29s
2793:	learn: 0.0041597	total: 5m 9s	remaining: 13m 18s
3010:	learn: 0.0039485	total: 5m 9s	remaining: 11m 58s
3006:	learn: 0.0033203	total: 5m 9s	remaining: 11m 59s
3055:	learn: 0.0036712	total: 5m 9s	remaining: 11m 43s
2924:	learn: 0.0040527	total: 5m 9s	remaining: 12m 28s
2794:	learn: 0.0041562	total: 5m 9s	remaining: 13m 18s
3011:	learn: 0.0039465	total: 5m 9s	remaining: 11m 58s
3007:	learn: 0.0033186	total: 5m 9s	remaining: 11m 59s
3056:	learn: 0.0036701	total: 5m 9s	remaining: 11m 43s
2925:	learn: 0.0040502	total: 5m 9s	remaining: 12m 28s
3012:	learn: 0.0039453	total: 5m 9s	remaining: 11m 57s
2795:	learn: 0.0041533	total: 5m 9s	remaining: 13m 18s
3008:	learn: 0.0033168	total: 5m 9s	remaining: 11m 59s
3057:	learn: 0.0036677	total: 5m 9s	remaining: 11m 43s
3013:	learn: 0.0039427	total: 5m 9s	remaining: 11m 57s
2926:	learn: 0.0040486	total: 5m 9s	remaining: 12m 28s
2796:	learn: 0.0041514	total: 5m 9s	remaining: 13m 17s
3009:	learn: 0.0033154	total: 5m 9s	remaining: 11m 59s
3058:	learn: 0.0036657	total: 5m 9s	remaining: 11m 43s
3014:	learn: 0.0039407	total: 5m 9s	remaining: 11m 57s
3010:	learn: 0.0033136	total: 5m 9s	remaining: 11m 59s
2927:	learn: 0.0040466	total: 5m 9s	remaining: 12m 28s
2797:	learn: 0.0041500	total: 5m 9s	remaining: 13m 17s
3059:	learn: 0.0036637	total: 5m 9s	remaining: 11m 42s
3015:	learn: 0.0039390	total: 5m 9s	remaining: 11m 57s
3011:	learn: 0.0033120	total: 5m 9s	remaining: 11m 59s
2928:	learn: 0.0040447	total: 5m 10s	remaining: 12m 28s
3016:	learn: 0.0039372	total: 5m 9s	remaining: 11m 57s
3060:	learn: 0.0036618	total: 5m 10s	remaining: 11m 42s
2798:	learn: 0.0041480	total: 5m 10s	remaining: 13m 17s
3012:	learn: 0.0033101	total: 5m 10s	remaining: 11m 59s
3061:	learn: 0.0036605	total: 5m 10s	remaining: 11m 42s
3017:	learn: 0.0039352	total: 5m 10s	remaining: 11m 57s
2929:	learn: 0.0040430	total: 5m 10s	remaining: 12m 28s
2799:	learn: 0.0041453	total: 5m 10s	remaining: 13m 17s
3013:	learn: 0.0033081	total: 5m 10s	remaining: 11m 58s
3062:	learn: 0.0036589	total: 5m 10s	remaining: 11m 42s
3018:	learn: 0.0039323	total: 5m 10s	remaining: 11m 57s
2930:	learn: 0.0040398	total: 5m 10s	remaining: 12m 28s
2800:	learn: 0.0041433	total: 5m 10s	remaining: 13m 17s
3014:	learn: 0.0033069	total: 5m 10s	remaining: 11m 58s
3019:	learn: 0.0039311	total: 5m 10s	remaining: 11m 56s
3063:	learn: 0.0036565	total: 5m 10s	remaining: 11m 42s
2801:	learn: 0.0041399	total: 5m 10s	remaining: 13m 17s
2931:	learn: 0.0040384	total: 5m 10s	remaining: 12m 28s
3020:	learn: 0.0039287	total: 5m 10s	remaining: 11m 56s
3015:	learn: 0.0033050	total: 5m 10s	remaining: 11m 58s
3064:	learn: 0.0036541	total: 5m 10s	remaining: 11m 42s
2802:	learn: 0.0041366	total: 5m 10s	remaining: 13m 17s
2932:	learn: 0.0040379	total: 5m 10s	remaining: 12m 28s
3021:	learn: 0.0039270	total: 5m 10s	remaining: 11m 56s
3016:	learn: 0.0033037	total: 5m 10s	remaining: 11m 58s
3065:	learn: 0.0036517	total: 5m 10s	remaining: 11m 42s
2803:	learn: 0.0041339	total: 5m 10s	remaining: 13m 17s
2933:	learn: 0.0040359	total: 5m 10s	remaining: 12m 28s
3022:	learn: 0.0039252	total: 5m 10s	remaining: 11m 56s
3017:	learn: 0.0033023	total: 5m 10s	remaining: 11m 58s
3066:	learn: 0.0036507	total: 5m 10s	remaining: 11m 42s
2934:	learn: 0.0040333	total: 5m 10s	remaining: 12m 27s
2804:	learn: 0.0041320	total: 5m 10s	remaining: 13m 16s
3018:	learn: 0.0033004	total: 5m 10s	remaining: 11m 58s
3023:	learn: 0.0039229	total: 5m 10s	remaining: 11m 56s
3067:	learn: 0.0036483	total: 5m 10s	remaining: 11m 42s
2805:	learn: 0.0041305	total: 5m 10s	remaining: 13m 16s
2935:	learn: 0.0040318	total: 5m 10s	remaining: 12m 27s
3019:	learn: 0.0032986	total: 5m 10s	remaining: 11m 58s
3024:	learn: 0.0039216	total: 5m 10s	remaining: 11m 56s
3068:	learn: 0.0036459	total: 5m 10s	remaining: 11m 42s
2936:	learn: 0.0040289	total: 5m 10s	remaining: 12m 27s
2806:	learn: 0.0041287	total: 5m 10s	remaining: 13m 16s
3020:	learn: 0.0032970	total: 5m 10s	remaining: 11m 58s
3025:	learn: 0.0039189	total: 5m 10s	remaining: 11m 56s
3069:	learn: 0.0036438	total: 5m 10s	remaining: 11m 41s
2937:	learn: 0.0040268	total: 5m 10s	remaining: 12m 27s
2807:	learn: 0.0041268	total: 5m 10s	remaining: 13m 16s
3021:	learn: 0.0032955	total: 5m 10s	remaining: 11m 58s
3026:	learn: 0.0039161	total: 5m 10s	remaining: 11m 56s
3070:	learn: 0.0036419	total: 5m 11s	remaining: 11m 41s
2808:	learn: 0.0041249	total: 5m 11s	remaining: 13m 16s
2938:	learn: 0.0040247	total: 5m 11s	remaining: 12m 27s
3022:	learn: 0.0032921	total: 5m 11s	remaining: 11m 57s
3027:	learn: 0.0039144	total: 5m 10s	remaining: 11m 56s
3071:	learn: 0.0036399	total: 5m 11s	remaining: 11m 41s
2809:	learn: 0.0041224	total: 5m 11s	remaining: 13m 16s
3023:	learn: 0.0032909	total: 5m 11s	remaining: 11m 57s
2939:	learn: 0.0040223	total: 5m 11s	remaining: 12m 27s
3028:	learn: 0.0039125	total: 5m 11s	remaining: 11m 55s
3024:	learn: 0.0032882	total: 5m 11s	remaining: 11m 57s
2940:	learn: 0.0040200	total: 5m 11s	remaining: 12m 27s
3072:	learn: 0.0036384	total: 5m 11s	remaining: 11m 41s
2810:	learn: 0.0041198	total: 5m 11s	remaining: 13m 16s
3029:	learn: 0.0039102	total: 5m 11s	remaining: 11m 55s
2941:	learn: 0.0040175	total: 5m 11s	remaining: 12m 27s
3025:	learn: 0.0032866	total: 5m 11s	remaining: 11m 57s
3073:	learn: 0.0036372	total: 5m 11s	remaining: 11m 41s
2811:	learn: 0.0041178	total: 5m 11s	remaining: 13m 15s
3030:	learn: 0.0039075	total: 5m 11s	remaining: 11m 55s
2942:	learn: 0.0040156	total: 5m 11s	remaining: 12m 26s
3074:	learn: 0.0036357	total: 5m 11s	remaining: 11m 41s
2812:	learn: 0.0041156	total: 5m 11s	remaining: 13m 15s
3026:	learn: 0.0032851	total: 5m 11s	remaining: 11m 57s
2943:	learn: 0.0040146	total: 5m 11s	remaining: 12m 26s
3031:	learn: 0.0039059	total: 5m 11s	remaining: 11m 55s
3075:	learn: 0.0036337	total: 5m 11s	remaining: 11m 41s
2813:	learn: 0.0041132	total: 5m 11s	remaining: 13m 15s
3027:	learn: 0.0032832	total: 5m 11s	remaining: 11m 57s
3076:	learn: 0.0036321	total: 5m 11s	remaining: 11m 41s
3032:	learn: 0.0039036	total: 5m 11s	remaining: 11m 55s
2814:	learn: 0.0041110	total: 5m 11s	remaining: 13m 15s
2944:	learn: 0.0040128	total: 5m 11s	remaining: 12m 26s
3028:	learn: 0.0032820	total: 5m 11s	remaining: 11m 57s
3033:	learn: 0.0039013	total: 5m 11s	remaining: 11m 55s
2815:	learn: 0.0041088	total: 5m 11s	remaining: 13m 15s
3077:	learn: 0.0036302	total: 5m 11s	remaining: 11m 41s
2945:	learn: 0.0040100	total: 5m 11s	remaining: 12m 26s
3029:	learn: 0.0032801	total: 5m 11s	remaining: 11m 57s
3034:	learn: 0.0039000	total: 5m 11s	remaining: 11m 55s
2816:	learn: 0.0041079	total: 5m 11s	remaining: 13m 15s
3078:	learn: 0.0036283	total: 5m 11s	remaining: 11m 41s
2946:	learn: 0.0040081	total: 5m 11s	remaining: 12m 26s
3030:	learn: 0.0032789	total: 5m 11s	remaining: 11m 57s
3035:	learn: 0.0038973	total: 5m 11s	remaining: 11m 55s
3079:	learn: 0.0036272	total: 5m 11s	remaining: 11m 40s
2817:	learn: 0.0041058	total: 5m 11s	remaining: 13m 15s
2947:	learn: 0.0040060	total: 5m 12s	remaining: 12m 26s
3031:	learn: 0.0032773	total: 5m 11s	remaining: 11m 56s
2818:	learn: 0.0041039	total: 5m 12s	remaining: 13m 14s
3036:	learn: 0.0038957	total: 5m 11s	remaining: 11m 55s
3080:	learn: 0.0036250	total: 5m 12s	remaining: 11m 40s
2948:	learn: 0.0040043	total: 5m 12s	remaining: 12m 26s
3032:	learn: 0.0032754	total: 5m 12s	remaining: 11m 56s
2819:	learn: 0.0041015	total: 5m 12s	remaining: 13m 14s
3081:	learn: 0.0036227	total: 5m 12s	remaining: 11m 40s
3037:	learn: 0.0038940	total: 5m 12s	remaining: 11m 55s
3033:	learn: 0.0032738	total: 5m 12s	remaining: 11m 56s
2949:	learn: 0.0040017	total: 5m 12s	remaining: 12m 26s
2820:	learn: 0.0040997	total: 5m 12s	remaining: 13m 14s
3082:	learn: 0.0036200	total: 5m 12s	remaining: 11m 40s
3038:	learn: 0.0038927	total: 5m 12s	remaining: 11m 54s
3034:	learn: 0.0032720	total: 5m 12s	remaining: 11m 56s
2950:	learn: 0.0039992	total: 5m 12s	remaining: 12m 26s
3039:	learn: 0.0038907	total: 5m 12s	remaining: 11m 54s
3083:	learn: 0.0036179	total: 5m 12s	remaining: 11m 40s
2821:	learn: 0.0040977	total: 5m 12s	remaining: 13m 14s
3035:	learn: 0.0032692	total: 5m 12s	remaining: 11m 56s
2951:	learn: 0.0039973	total: 5m 12s	remaining: 12m 25s
3040:	learn: 0.0038890	total: 5m 12s	remaining: 11m 54s
3084:	learn: 0.0036164	total: 5m 12s	remaining: 11m 40s
2822:	learn: 0.0040951	total: 5m 12s	remaining: 13m 14s
3036:	learn: 0.0032678	total: 5m 12s	remaining: 11m 56s
3041:	learn: 0.0038868	total: 5m 12s	remaining: 11m 54s
2952:	learn: 0.0039956	total: 5m 12s	remaining: 12m 25s
2823:	learn: 0.0040932	total: 5m 12s	remaining: 13m 14s
3085:	learn: 0.0036151	total: 5m 12s	remaining: 11m 40s
3037:	learn: 0.0032660	total: 5m 12s	remaining: 11m 56s
3042:	learn: 0.0038845	total: 5m 12s	remaining: 11m 54s
2953:	learn: 0.0039938	total: 5m 12s	remaining: 12m 25s
2824:	learn: 0.0040923	total: 5m 12s	remaining: 13m 14s
3086:	learn: 0.0036131	total: 5m 12s	remaining: 11m 40s
3038:	learn: 0.0032634	total: 5m 12s	remaining: 11m 56s
3043:	learn: 0.0038825	total: 5m 12s	remaining: 11m 54s
2954:	learn: 0.0039922	total: 5m 12s	remaining: 12m 25s
3087:	learn: 0.0036112	total: 5m 12s	remaining: 11m 40s
3039:	learn: 0.0032608	total: 5m 12s	remaining: 11m 55s
2825:	learn: 0.0040908	total: 5m 12s	remaining: 13m 14s
3044:	learn: 0.0038800	total: 5m 12s	remaining: 11m 54s
3088:	learn: 0.0036102	total: 5m 12s	remaining: 11m 39s
2955:	learn: 0.0039900	total: 5m 12s	remaining: 12m 25s
3040:	learn: 0.0032596	total: 5m 12s	remaining: 11m 55s
2826:	learn: 0.0040886	total: 5m 12s	remaining: 13m 13s
3045:	learn: 0.0038780	total: 5m 12s	remaining: 11m 54s
2956:	learn: 0.0039882	total: 5m 12s	remaining: 12m 25s
3089:	learn: 0.0036087	total: 5m 12s	remaining: 11m 39s
3041:	learn: 0.0032577	total: 5m 12s	remaining: 11m 55s
2827:	learn: 0.0040867	total: 5m 13s	remaining: 13m 13s
3046:	learn: 0.0038763	total: 5m 12s	remaining: 11m 54s
3090:	learn: 0.0036061	total: 5m 13s	remaining: 11m 39s
2957:	learn: 0.0039870	total: 5m 13s	remaining: 12m 25s
2828:	learn: 0.0040848	total: 5m 13s	remaining: 13m 13s
3042:	learn: 0.0032557	total: 5m 13s	remaining: 11m 55s
3047:	learn: 0.0038741	total: 5m 13s	remaining: 11m 53s
2958:	learn: 0.0039852	total: 5m 13s	remaining: 12m 25s
3091:	learn: 0.0036042	total: 5m 13s	remaining: 11m 39s
2829:	learn: 0.0040839	total: 5m 13s	remaining: 13m 13s
3043:	learn: 0.0032544	total: 5m 13s	remaining: 11m 55s
3092:	learn: 0.0036024	total: 5m 13s	remaining: 11m 39s
3048:	learn: 0.0038721	total: 5m 13s	remaining: 11m 53s
2959:	learn: 0.0039828	total: 5m 13s	remaining: 12m 25s
3044:	learn: 0.0032524	total: 5m 13s	remaining: 11m 55s
3093:	learn: 0.0035996	total: 5m 13s	remaining: 11m 39s
2830:	learn: 0.0040825	total: 5m 13s	remaining: 13m 13s
3049:	learn: 0.0038695	total: 5m 13s	remaining: 11m 53s
2960:	learn: 0.0039805	total: 5m 13s	remaining: 12m 24s
3045:	learn: 0.0032511	total: 5m 13s	remaining: 11m 55s
3094:	learn: 0.0035970	total: 5m 13s	remaining: 11m 39s
2831:	learn: 0.0040806	total: 5m 13s	remaining: 13m 13s
3046:	learn: 0.0032499	total: 5m 13s	remaining: 11m 55s
2961:	learn: 0.0039787	total: 5m 13s	remaining: 12m 24s
3050:	learn: 0.0038672	total: 5m 13s	remaining: 11m 53s
2832:	learn: 0.0040787	total: 5m 13s	remaining: 13m 13s
3095:	learn: 0.0035946	total: 5m 13s	remaining: 11m 39s
2962:	learn: 0.0039772	total: 5m 13s	remaining: 12m 24s
3047:	learn: 0.0032485	total: 5m 13s	remaining: 11m 55s
3051:	learn: 0.0038644	total: 5m 13s	remaining: 11m 53s
2833:	learn: 0.0040752	total: 5m 13s	remaining: 13m 13s
3096:	learn: 0.0035924	total: 5m 13s	remaining: 11m 39s
2963:	learn: 0.0039750	total: 5m 13s	remaining: 12m 24s

3052:	learn: 0.0038619	total: 5m 13s	remaining: 11m 53s
3048:	learn: 0.0032472	total: 5m 13s	remaining: 11m 54s
2834:	learn: 0.0040733	total: 5m 13s	remaining: 13m 12s
3097:	learn: 0.0035909	total: 5m 13s	remaining: 11m 38s
2964:	learn: 0.0039739	total: 5m 13s	remaining: 12m 24s
3053:	learn: 0.0038606	total: 5m 13s	remaining: 11m 53s
3098:	learn: 0.0035888	total: 5m 13s	remaining: 11m 38s
3049:	learn: 0.0032450	total: 5m 13s	remaining: 11m 54s
2835:	learn: 0.0040711	total: 5m 13s	remaining: 13m 12s
2965:	learn: 0.0039719	total: 5m 13s	remaining: 12m 24s
3054:	learn: 0.0038585	total: 5m 13s	remaining: 11m 53s
3050:	learn: 0.0032430	total: 5m 13s	remaining: 11m 54s
3099:	learn: 0.0035870	total: 5m 13s	remaining: 11m 38s
2836:	learn: 0.0040702	total: 5m 13s	remaining: 13m 12s
3055:	learn: 0.0038566	total: 5m 13s	remaining: 11m 53s
2966:	learn: 0.0039692	total: 5m 13s	remaining: 12m 24s
3051:	learn: 0.0032409	total: 5m 13s	remaining: 11m 54s
3100:	learn: 0.0035855	total: 5m 14s	remaining: 11m 38s
3056:	learn: 0.0038543	total: 5m 13s	remaining: 11m 52s
2837:	learn: 0.0040677	total: 5m 14s	remaining: 13m 12s
3052:	learn: 0.0032395	total: 5m 14s	remaining: 11m 54s
3101:	learn: 0.0035840	total: 5m 14s	remaining: 11m 38s
2967:	learn: 0.0039669	total: 5m 14s	remaining: 12m 24s
3057:	learn: 0.0038525	total: 5m 14s	remaining: 11m 52s
2838:	learn: 0.0040657	total: 5m 14s	remaining: 13m 12s
3053:	learn: 0.0032371	total: 5m 14s	remaining: 11m 54s
3102:	learn: 0.0035822	total: 5m 14s	remaining: 11m 38s
2968:	learn: 0.0039642	total: 5m 14s	remaining: 12m 24s
2839:	learn: 0.0040639	total: 5m 14s	remaining: 13m 12s
3058:	learn: 0.0038510	total: 5m 14s	remaining: 11m 52s
3054:	learn: 0.0032355	total: 5m 14s	remaining: 11m 54s
3103:	learn: 0.0035809	total: 5m 14s	remaining: 11m 38s
2969:	learn: 0.0039628	total: 5m 14s	remaining: 12m 24s
3059:	learn: 0.0038486	total: 5m 14s	remaining: 11m 52s
2840:	learn: 0.0040615	total: 5m 14s	remaining: 13m 12s
3055:	learn: 0.0032339	total: 5m 14s	remaining: 11m 54s
3104:	learn: 0.0035794	total: 5m 14s	remaining: 11m 38s
2970:	learn: 0.0039612	total: 5m 14s	remaining: 12m 23s
3060:	learn: 0.0038474	total: 5m 14s	remaining: 11m 52s
2841:	learn: 0.0040606	total: 5m 14s	remaining: 13m 12s
3105:	learn: 0.0035780	total: 5m 14s	remaining: 11m 38s
3056:	learn: 0.0032327	total: 5m 14s	remaining: 11m 54s
2971:	learn: 0.0039595	total: 5m 14s	remaining: 12m 23s
2842:	learn: 0.0040588	total: 5m 14s	remaining: 13m 11s
3061:	learn: 0.0038447	total: 5m 14s	remaining: 11m 52s
3057:	learn: 0.0032303	total: 5m 14s	remaining: 11m 54s
3106:	learn: 0.0035763	total: 5m 14s	remaining: 11m 37s
2972:	learn: 0.0039578	total: 5m 14s	remaining: 12m 23s
3062:	learn: 0.0038434	total: 5m 14s	remaining: 11m 52s
2843:	learn: 0.0040568	total: 5m 14s	remaining: 13m 11s
3058:	learn: 0.0032281	total: 5m 14s	remaining: 11m 53s
3107:	learn: 0.0035738	total: 5m 14s	remaining: 11m 37s
2973:	learn: 0.0039562	total: 5m 14s	remaining: 12m 23s
3063:	learn: 0.0038418	total: 5m 14s	remaining: 11m 52s
2844:	learn: 0.0040544	total: 5m 14s	remaining: 13m 11s
3059:	learn: 0.0032259	total: 5m 14s	remaining: 11m 53s
3108:	learn: 0.0035716	total: 5m 14s	remaining: 11m 37s
2974:	learn: 0.0039544	total: 5m 14s	remaining: 12m 23s
3064:	learn: 0.0038407	total: 5m 14s	remaining: 11m 52s
3109:	learn: 0.0035693	total: 5m 14s	remaining: 11m 37s
2845:	learn: 0.0040521	total: 5m 14s	remaining: 13m 11s
3060:	learn: 0.0032236	total: 5m 14s	remaining: 11m 53s
2975:	learn: 0.0039523	total: 5m 14s	remaining: 12m 23s
2846:	learn: 0.0040501	total: 5m 14s	remaining: 13m 11s
3061:	learn: 0.0032218	total: 5m 14s	remaining: 11m 53s
3110:	learn: 0.0035676	total: 5m 14s	remaining: 11m 37s
3065:	learn: 0.0038383	total: 5m 14s	remaining: 11m 52s
2847:	learn: 0.0040481	total: 5m 15s	remaining: 13m 11s
2976:	learn: 0.0039505	total: 5m 15s	remaining: 12m 23s
3062:	learn: 0.0032200	total: 5m 14s	remaining: 11m 53s
3111:	learn: 0.0035654	total: 5m 15s	remaining: 11m 37s
3066:	learn: 0.0038363	total: 5m 14s	remaining: 11m 51s
2848:	learn: 0.0040453	total: 5m 15s	remaining: 13m 10s
2977:	learn: 0.0039482	total: 5m 15s	remaining: 12m 23s
3063:	learn: 0.0032177	total: 5m 15s	remaining: 11m 53s
3112:	learn: 0.0035641	total: 5m 15s	remaining: 11m 37s
3067:	learn: 0.0038341	total: 5m 15s	remaining: 11m 51s
2849:	learn: 0.0040428	total: 5m 15s	remaining: 13m 10s
2978:	learn: 0.0039458	total: 5m 15s	remaining: 12m 23s
3064:	learn: 0.0032161	total: 5m 15s	remaining: 11m 53s
3113:	learn: 0.0035621	total: 5m 15s	remaining: 11m 37s
3068:	learn: 0.0038327	total: 5m 15s	remaining: 11m 51s
2979:	learn: 0.0039439	total: 5m 15s	remaining: 12m 22s
2850:	learn: 0.0040405	total: 5m 15s	remaining: 13m 10s
3114:	learn: 0.0035609	total: 5m 15s	remaining: 11m 37s
3065:	learn: 0.0032145	total: 5m 15s	remaining: 11m 53s
3069:	learn: 0.0038304	total: 5m 15s	remaining: 11m 51s
2980:	learn: 0.0039415	total: 5m 15s	remaining: 12m 22s
3115:	learn: 0.0035591	total: 5m 15s	remaining: 11m 36s
3066:	learn: 0.0032130	total: 5m 15s	remaining: 11m 52s
2851:	learn: 0.0040384	total: 5m 15s	remaining: 13m 10s
3070:	learn: 0.0038285	total: 5m 15s	remaining: 11m 51s
2981:	learn: 0.0039393	total: 5m 15s	remaining: 12m 22s
3067:	learn: 0.0032114	total: 5m 15s	remaining: 11m 52s
3116:	learn: 0.0035572	total: 5m 15s	remaining: 11m 36s
3071:	learn: 0.0038261	total: 5m 15s	remaining: 11m 51s
2852:	learn: 0.0040367	total: 5m 15s	remaining: 13m 10s
2982:	learn: 0.0039382	total: 5m 15s	remaining: 12m 22s
3117:	learn: 0.0035550	total: 5m 15s	remaining: 11m 36s
3068:	learn: 0.0032101	total: 5m 15s	remaining: 11m 52s
3072:	learn: 0.0038238	total: 5m 15s	remaining: 11m 51s
2853:	learn: 0.0040350	total: 5m 15s	remaining: 13m 10s
2983:	learn: 0.0039363	total: 5m 15s	remaining: 12m 22s
3073:	learn: 0.0038215	total: 5m 15s	remaining: 11m 51s
3069:	learn: 0.0032080	total: 5m 15s	remaining: 11m 52s
3118:	learn: 0.0035534	total: 5m 15s	remaining: 11m 36s
2984:	learn: 0.0039346	total: 5m 15s	remaining: 12m 22s
2854:	learn: 0.0040327	total: 5m 15s	remaining: 13m 10s
3070:	learn: 0.0032058	total: 5m 15s	remaining: 11m 52s
3074:	learn: 0.0038191	total: 5m 15s	remaining: 11m 51s
2985:	learn: 0.0039324	total: 5m 15s	remaining: 12m 22s
3119:	learn: 0.0035522	total: 5m 15s	remaining: 11m 36s
2855:	learn: 0.0040292	total: 5m 15s	remaining: 13m 10s
3071:	learn: 0.0032043	total: 5m 15s	remaining: 11m 52s
3120:	learn: 0.0035500	total: 5m 15s	remaining: 11m 36s
3075:	learn: 0.0038170	total: 5m 15s	remaining: 11m 51s
2986:	learn: 0.0039309	total: 5m 16s	remaining: 12m 21s
2856:	learn: 0.0040268	total: 5m 16s	remaining: 13m 10s
3072:	learn: 0.0032030	total: 5m 15s	remaining: 11m 52s
3121:	learn: 0.0035478	total: 5m 16s	remaining: 11m 36s
2857:	learn: 0.0040242	total: 5m 16s	remaining: 13m 9s
2987:	learn: 0.0039295	total: 5m 16s	remaining: 12m 21s
3076:	learn: 0.0038154	total: 5m 16s	remaining: 11m 50s
3073:	learn: 0.0032020	total: 5m 16s	remaining: 11m 52s
3122:	learn: 0.0035459	total: 5m 16s	remaining: 11m 36s
2858:	learn: 0.0040225	total: 5m 16s	remaining: 13m 9s
2988:	learn: 0.0039268	total: 5m 16s	remaining: 12m 21s
3077:	learn: 0.0038143	total: 5m 16s	remaining: 11m 50s
3074:	learn: 0.0032003	total: 5m 16s	remaining: 11m 52s
3123:	learn: 0.0035436	total: 5m 16s	remaining: 11m 36s
2989:	learn: 0.0039253	total: 5m 16s	remaining: 12m 21s
2859:	learn: 0.0040201	total: 5m 16s	remaining: 13m 9s
3078:	learn: 0.0038124	total: 5m 16s	remaining: 11m 50s
3075:	learn: 0.0031986	total: 5m 16s	remaining: 11m 51s
3124:	learn: 0.0035420	total: 5m 16s	remaining: 11m 35s
2990:	learn: 0.0039236	total: 5m 16s	remaining: 12m 21s
3079:	learn: 0.0038103	total: 5m 16s	remaining: 11m 50s
2860:	learn: 0.0040182	total: 5m 16s	remaining: 13m 9s
3076:	learn: 0.0031969	total: 5m 16s	remaining: 11m 51s
3125:	learn: 0.0035397	total: 5m 16s	remaining: 11m 35s
3080:	learn: 0.0038085	total: 5m 16s	remaining: 11m 50s
2991:	learn: 0.0039207	total: 5m 16s	remaining: 12m 21s
3077:	learn: 0.0031946	total: 5m 16s	remaining: 11m 51s
3126:	learn: 0.0035376	total: 5m 16s	remaining: 11m 35s
2861:	learn: 0.0040163	total: 5m 16s	remaining: 13m 9s
3081:	learn: 0.0038071	total: 5m 16s	remaining: 11m 50s
2992:	learn: 0.0039186	total: 5m 16s	remaining: 12m 21s
3127:	learn: 0.0035358	total: 5m 16s	remaining: 11m 35s
2862:	learn: 0.0040144	total: 5m 16s	remaining: 13m 9s
3078:	learn: 0.0031925	total: 5m 16s	remaining: 11m 51s
3082:	learn: 0.0038060	total: 5m 16s	remaining: 11m 50s
2993:	learn: 0.0039162	total: 5m 16s	remaining: 12m 21s
3128:	learn: 0.0035344	total: 5m 16s	remaining: 11m 35s
3079:	learn: 0.0031909	total: 5m 16s	remaining: 11m 51s
2863:	learn: 0.0040115	total: 5m 16s	remaining: 13m 9s
3083:	learn: 0.0038037	total: 5m 16s	remaining: 11m 50s
2994:	learn: 0.0039157	total: 5m 16s	remaining: 12m 20s
3129:	learn: 0.0035334	total: 5m 16s	remaining: 11m 35s
3080:	learn: 0.0031891	total: 5m 16s	remaining: 11m 51s
3084:	learn: 0.0038019	total: 5m 16s	remaining: 11m 49s
2864:	learn: 0.0040087	total: 5m 16s	remaining: 13m 9s
3130:	learn: 0.0035323	total: 5m 16s	remaining: 11m 35s
2995:	learn: 0.0039144	total: 5m 16s	remaining: 12m 20s
3081:	learn: 0.0031877	total: 5m 16s	remaining: 11m 51s
3085:	learn: 0.0037996	total: 5m 16s	remaining: 11m 49s
2865:	learn: 0.0040072	total: 5m 17s	remaining: 13m 9s
3131:	learn: 0.0035310	total: 5m 16s	remaining: 11m 35s
3082:	learn: 0.0031857	total: 5m 16s	remaining: 11m 51s
2996:	learn: 0.0039126	total: 5m 17s	remaining: 12m 20s
3086:	learn: 0.0037978	total: 5m 16s	remaining: 11m 49s
2866:	learn: 0.0040054	total: 5m 17s	remaining: 13m 8s
3132:	learn: 0.0035298	total: 5m 17s	remaining: 11m 35s
3083:	learn: 0.0031843	total: 5m 17s	remaining: 11m 51s
2997:	learn: 0.0039109	total: 5m 17s	remaining: 12m 20s
3087:	learn: 0.0037954	total: 5m 17s	remaining: 11m 49s
2867:	learn: 0.0040030	total: 5m 17s	remaining: 13m 8s
3133:	learn: 0.0035285	total: 5m 17s	remaining: 11m 34s
3084:	learn: 0.0031827	total: 5m 17s	remaining: 11m 50s
2998:	learn: 0.0039083	total: 5m 17s	remaining: 12m 20s
3088:	learn: 0.0037932	total: 5m 17s	remaining: 11m 49s
3134:	learn: 0.0035272	total: 5m 17s	remaining: 11m 34s
3085:	learn: 0.0031813	total: 5m 17s	remaining: 11m 50s
2868:	learn: 0.0040007	total: 5m 17s	remaining: 13m 8s
2999:	learn: 0.0039054	total: 5m 17s	remaining: 12m 20s
3089:	learn: 0.0037910	total: 5m 17s	remaining: 11m 49s
3135:	learn: 0.0035260	total: 5m 17s	remaining: 11m 34s
3086:	learn: 0.0031791	total: 5m 17s	remaining: 11m 50s
2869:	learn: 0.0039983	total: 5m 17s	remaining: 13m 8s
3090:	learn: 0.0037892	total: 5m 17s	remaining: 11m 49s
3000:	learn: 0.0039037	total: 5m 17s	remaining: 12m 20s
3136:	learn: 0.0035238	total: 5m 17s	remaining: 11m 34s
3087:	learn: 0.0031771	total: 5m 17s	remaining: 11m 50s
2870:	learn: 0.0039954	total: 5m 17s	remaining: 13m 8s
3091:	learn: 0.0037866	total: 5m 17s	remaining: 11m 49s
3001:	learn: 0.0039021	total: 5m 17s	remaining: 12m 20s
3088:	learn: 0.0031755	total: 5m 17s	remaining: 11m 50s
3137:	learn: 0.0035217	total: 5m 17s	remaining: 11m 34s
2871:	learn: 0.0039918	total: 5m 17s	remaining: 13m 8s
3002:	learn: 0.0039002	total: 5m 17s	remaining: 12m 20s
3092:	learn: 0.0037842	total: 5m 17s	remaining: 11m 49s
3089:	learn: 0.0031741	total: 5m 17s	remaining: 11m 50s
3138:	learn: 0.0035196	total: 5m 17s	remaining: 11m 34s
2872:	learn: 0.0039894	total: 5m 17s	remaining: 13m 8s
3093:	learn: 0.0037821	total: 5m 17s	remaining: 11m 48s
3003:	learn: 0.0038980	total: 5m 17s	remaining: 12m 20s
3090:	learn: 0.0031728	total: 5m 17s	remaining: 11m 50s
2873:	learn: 0.0039869	total: 5m 17s	remaining: 13m 8s
3139:	learn: 0.0035169	total: 5m 17s	remaining: 11m 34s
3004:	learn: 0.0038961	total: 5m 17s	remaining: 12m 19s
3091:	learn: 0.0031705	total: 5m 17s	remaining: 11m 50s
3094:	learn: 0.0037801	total: 5m 17s	remaining: 11m 48s
2874:	learn: 0.0039842	total: 5m 17s	remaining: 13m 7s
3140:	learn: 0.0035156	total: 5m 17s	remaining: 11m 34s
3005:	learn: 0.0038947	total: 5m 17s	remaining: 12m 19s
3092:	learn: 0.0031687	total: 5m 17s	remaining: 11m 49s
3095:	learn: 0.0037778	total: 5m 17s	remaining: 11m 48s
3006:	learn: 0.0038930	total: 5m 17s	remaining: 12m 19s
2875:	learn: 0.0039828	total: 5m 18s	remaining: 13m 7s
3141:	learn: 0.0035134	total: 5m 18s	remaining: 11m 34s
3093:	learn: 0.0031666	total: 5m 18s	remaining: 11m 49s
3096:	learn: 0.0037753	total: 5m 17s	remaining: 11m 48s
3007:	learn: 0.0038914	total: 5m 18s	remaining: 12m 19s
3142:	learn: 0.0035113	total: 5m 18s	remaining: 11m 34s
2876:	learn: 0.0039815	total: 5m 18s	remaining: 13m 7s
3097:	learn: 0.0037729	total: 5m 18s	remaining: 11m 48s
3008:	learn: 0.0038888	total: 5m 18s	remaining: 12m 19s
3094:	learn: 0.0031652	total: 5m 18s	remaining: 11m 49s
3143:	learn: 0.0035103	total: 5m 18s	remaining: 11m 33s
3009:	learn: 0.0038874	total: 5m 18s	remaining: 12m 19s
3098:	learn: 0.0037716	total: 5m 18s	remaining: 11m 48s
2877:	learn: 0.0039793	total: 5m 18s	remaining: 13m 7s
3144:	learn: 0.0035093	total: 5m 18s	remaining: 11m 33s
3095:	learn: 0.0031631	total: 5m 18s	remaining: 11m 49s
3010:	learn: 0.0038857	total: 5m 18s	remaining: 12m 18s
3099:	learn: 0.0037697	total: 5m 18s	remaining: 11m 48s
2878:	learn: 0.0039769	total: 5m 18s	remaining: 13m 7s
3096:	learn: 0.0031610	total: 5m 18s	remaining: 11m 49s
3011:	learn: 0.0038843	total: 5m 18s	remaining: 12m 18s
3145:	learn: 0.0035074	total: 5m 18s	remaining: 11m 33s
3100:	learn: 0.0037684	total: 5m 18s	remaining: 11m 48s
2879:	learn: 0.0039748	total: 5m 18s	remaining: 13m 7s
3012:	learn: 0.0038818	total: 5m 18s	remaining: 12m 18s
3097:	learn: 0.0031589	total: 5m 18s	remaining: 11m 49s
3146:	learn: 0.0035063	total: 5m 18s	remaining: 11m 33s
3101:	learn: 0.0037664	total: 5m 18s	remaining: 11m 48s
3013:	learn: 0.0038800	total: 5m 18s	remaining: 12m 18s
2880:	learn: 0.0039714	total: 5m 18s	remaining: 13m 7s
3147:	learn: 0.0035048	total: 5m 18s	remaining: 11m 33s
3098:	learn: 0.0031570	total: 5m 18s	remaining: 11m 49s
3102:	learn: 0.0037641	total: 5m 18s	remaining: 11m 48s
3148:	learn: 0.0035027	total: 5m 18s	remaining: 11m 33s
3099:	learn: 0.0031559	total: 5m 18s	remaining: 11m 49s
3014:	learn: 0.0038784	total: 5m 18s	remaining: 12m 18s
3103:	learn: 0.0037629	total: 5m 18s	remaining: 11m 47s
2881:	learn: 0.0039679	total: 5m 18s	remaining: 13m 7s
3149:	learn: 0.0035016	total: 5m 18s	remaining: 11m 33s
3100:	learn: 0.0031540	total: 5m 18s	remaining: 11m 49s
3104:	learn: 0.0037609	total: 5m 18s	remaining: 11m 47s
3015:	learn: 0.0038756	total: 5m 18s	remaining: 12m 18s
2882:	learn: 0.0039658	total: 5m 18s	remaining: 13m 7s
3101:	learn: 0.0031521	total: 5m 18s	remaining: 11m 48s
3150:	learn: 0.0034993	total: 5m 18s	remaining: 11m 33s
3105:	learn: 0.0037595	total: 5m 18s	remaining: 11m 47s
3016:	learn: 0.0038737	total: 5m 18s	remaining: 12m 18s
3151:	learn: 0.0034973	total: 5m 18s	remaining: 11m 33s
3102:	learn: 0.0031503	total: 5m 18s	remaining: 11m 48s
3106:	learn: 0.0037577	total: 5m 18s	remaining: 11m 47s
2883:	learn: 0.0039645	total: 5m 19s	remaining: 13m 7s
3152:	learn: 0.0034952	total: 5m 19s	remaining: 11m 32s
3103:	learn: 0.0031486	total: 5m 19s	remaining: 11m 48s
3017:	learn: 0.0038711	total: 5m 19s	remaining: 12m 18s
3107:	learn: 0.0037553	total: 5m 18s	remaining: 11m 47s
2884:	learn: 0.0039626	total: 5m 19s	remaining: 13m 7s
3153:	learn: 0.0034938	total: 5m 19s	remaining: 11m 32s
3018:	learn: 0.0038695	total: 5m 19s	remaining: 12m 18s
2885:	learn: 0.0039605	total: 5m 19s	remaining: 13m 6s
3104:	learn: 0.0031472	total: 5m 19s	remaining: 11m 48s
3108:	learn: 0.0037530	total: 5m 19s	remaining: 11m 47s
3154:	learn: 0.0034914	total: 5m 19s	remaining: 11m 32s
3019:	learn: 0.0038678	total: 5m 19s	remaining: 12m 17s
2886:	learn: 0.0039578	total: 5m 19s	remaining: 13m 6s
3109:	learn: 0.0037510	total: 5m 19s	remaining: 11m 47s
3105:	learn: 0.0031454	total: 5m 19s	remaining: 11m 48s
3155:	learn: 0.0034890	total: 5m 19s	remaining: 11m 32s
2887:	learn: 0.0039555	total: 5m 19s	remaining: 13m 6s
3020:	learn: 0.0038658	total: 5m 19s	remaining: 12m 17s
3110:	learn: 0.0037497	total: 5m 19s	remaining: 11m 47s
3106:	learn: 0.0031439	total: 5m 19s	remaining: 11m 48s
3156:	learn: 0.0034878	total: 5m 19s	remaining: 11m 32s
3021:	learn: 0.0038645	total: 5m 19s	remaining: 12m 17s
2888:	learn: 0.0039530	total: 5m 19s	remaining: 13m 6s
3107:	learn: 0.0031429	total: 5m 19s	remaining: 11m 48s

3111:	learn: 0.0037475	total: 5m 19s	remaining: 11m 46s
3022:	learn: 0.0038626	total: 5m 19s	remaining: 12m 17s
2889:	learn: 0.0039505	total: 5m 19s	remaining: 13m 6s
3158:	learn: 0.0034846	total: 5m 19s	remaining: 11m 32s
3108:	learn: 0.0031412	total: 5m 19s	remaining: 11m 48s
3112:	learn: 0.0037452	total: 5m 19s	remaining: 11m 46s
3023:	learn: 0.0038612	total: 5m 19s	remaining: 12m 17s
2890:	learn: 0.0039472	total: 5m 19s	remaining: 13m 6s
3109:	learn: 0.0031392	total: 5m 19s	remaining: 11m 48s
3159:	learn: 0.0034819	total: 5m 19s	remaining: 11m 32s
3113:	learn: 0.0037441	total: 5m 19s	remaining: 11m 46s
2891:	learn: 0.0039465	total: 5m 19s	remaining: 13m 6s
3024:	learn: 0.0038592	total: 5m 19s	remaining: 12m 17s
3160:	learn: 0.0034799	total: 5m 19s	remaining: 11m 31s
3110:	learn: 0.0031381	total: 5m 19s	remaining: 11m 48s
3114:	learn: 0.0037418	total: 5m 19s	remaining: 11m 46s
2892:	learn: 0.0039432	total: 5m 19s	remaining: 13m 5s
3025:	learn: 0.0038577	total: 5m 19s	remaining: 12m 17s
3111:	learn: 0.0031369	total: 5m 19s	remaining: 11m 48s
3161:	learn: 0.0034772	total: 5m 19s	remaining: 11m 31s
3115:	learn: 0.0037396	total: 5m 19s	remaining: 11m 46s
3026:	learn: 0.0038550	total: 5m 19s	remaining: 12m 17s
2893:	learn: 0.0039413	total: 5m 20s	remaining: 13m 5s
3116:	learn: 0.0037383	total: 5m 19s	remaining: 11m 46s
3162:	learn: 0.0034758	total: 5m 20s	remaining: 11m 31s
3112:	learn: 0.0031352	total: 5m 20s	remaining: 11m 47s
3117:	learn: 0.0037362	total: 5m 19s	remaining: 11m 46s
3027:	learn: 0.0038534	total: 5m 20s	remaining: 12m 17s
2894:	learn: 0.0039381	total: 5m 20s	remaining: 13m 5s
3113:	learn: 0.0031342	total: 5m 20s	remaining: 11m 47s
3163:	learn: 0.0034747	total: 5m 20s	remaining: 11m 31s
3118:	learn: 0.0037347	total: 5m 20s	remaining: 11m 46s
2895:	learn: 0.0039355	total: 5m 20s	remaining: 13m 5s
3164:	learn: 0.0034729	total: 5m 20s	remaining: 11m 31s
3028:	learn: 0.0038524	total: 5m 20s	remaining: 12m 17s
3114:	learn: 0.0031323	total: 5m 20s	remaining: 11m 47s
3119:	learn: 0.0037334	total: 5m 20s	remaining: 11m 45s
2896:	learn: 0.0039343	total: 5m 20s	remaining: 13m 5s
3120:	learn: 0.0037319	total: 5m 20s	remaining: 11m 45s
3029:	learn: 0.0038513	total: 5m 20s	remaining: 12m 16s
3115:	learn: 0.0031302	total: 5m 20s	remaining: 11m 47s
3165:	learn: 0.0034717	total: 5m 20s	remaining: 11m 31s
2897:	learn: 0.0039320	total: 5m 20s	remaining: 13m 5s
3030:	learn: 0.0038496	total: 5m 20s	remaining: 12m 16s
3121:	learn: 0.0037301	total: 5m 20s	remaining: 11m 45s
3166:	learn: 0.0034709	total: 5m 20s	remaining: 11m 31s
3116:	learn: 0.0031285	total: 5m 20s	remaining: 11m 47s
2898:	learn: 0.0039297	total: 5m 20s	remaining: 13m 5s
3122:	learn: 0.0037289	total: 5m 20s	remaining: 11m 45s
3167:	learn: 0.0034690	total: 5m 20s	remaining: 11m 31s
3031:	learn: 0.0038480	total: 5m 20s	remaining: 12m 16s
3117:	learn: 0.0031274	total: 5m 20s	remaining: 11m 47s
2899:	learn: 0.0039280	total: 5m 20s	remaining: 13m 5s
3168:	learn: 0.0034674	total: 5m 20s	remaining: 11m 31s
3123:	learn: 0.0037264	total: 5m 20s	remaining: 11m 45s
3118:	learn: 0.0031258	total: 5m 20s	remaining: 11m 47s
3032:	learn: 0.0038461	total: 5m 20s	remaining: 12m 16s
2900:	learn: 0.0039245	total: 5m 20s	remaining: 13m 4s
3124:	learn: 0.0037246	total: 5m 20s	remaining: 11m 45s
3169:	learn: 0.0034654	total: 5m 20s	remaining: 11m 31s
3033:	learn: 0.0038443	total: 5m 20s	remaining: 12m 16s
3119:	learn: 0.0031242	total: 5m 20s	remaining: 11m 47s
2901:	learn: 0.0039212	total: 5m 20s	remaining: 13m 4s
3125:	learn: 0.0037229	total: 5m 20s	remaining: 11m 45s
3170:	learn: 0.0034633	total: 5m 20s	remaining: 11m 30s
3034:	learn: 0.0038431	total: 5m 20s	remaining: 12m 16s
3126:	learn: 0.0037219	total: 5m 20s	remaining: 11m 45s
3120:	learn: 0.0031229	total: 5m 20s	remaining: 11m 47s
2902:	learn: 0.0039194	total: 5m 20s	remaining: 13m 4s
3035:	learn: 0.0038410	total: 5m 20s	remaining: 12m 16s
3171:	learn: 0.0034610	total: 5m 20s	remaining: 11m 30s
3127:	learn: 0.0037196	total: 5m 20s	remaining: 11m 44s
3121:	learn: 0.0031217	total: 5m 20s	remaining: 11m 47s
2903:	learn: 0.0039175	total: 5m 21s	remaining: 13m 4s
3036:	learn: 0.0038394	total: 5m 21s	remaining: 12m 16s
3172:	learn: 0.0034599	total: 5m 21s	remaining: 11m 30s
3128:	learn: 0.0037183	total: 5m 20s	remaining: 11m 44s
3122:	learn: 0.0031200	total: 5m 21s	remaining: 11m 46s
3173:	learn: 0.0034579	total: 5m 21s	remaining: 11m 30s
2904:	learn: 0.0039152	total: 5m 21s	remaining: 13m 4s
3037:	learn: 0.0038381	total: 5m 21s	remaining: 12m 15s
3123:	learn: 0.0031185	total: 5m 21s	remaining: 11m 46s
3129:	learn: 0.0037163	total: 5m 21s	remaining: 11m 44s
2905:	learn: 0.0039130	total: 5m 21s	remaining: 13m 4s
3174:	learn: 0.0034558	total: 5m 21s	remaining: 11m 30s
3124:	learn: 0.0031166	total: 5m 21s	remaining: 11m 46s
3038:	learn: 0.0038366	total: 5m 21s	remaining: 12m 15s
3125:	learn: 0.0031155	total: 5m 21s	remaining: 11m 46s
3130:	learn: 0.0037141	total: 5m 21s	remaining: 11m 44s
3175:	learn: 0.0034551	total: 5m 21s	remaining: 11m 30s
2906:	learn: 0.0039108	total: 5m 21s	remaining: 13m 4s
3039:	learn: 0.0038353	total: 5m 21s	remaining: 12m 15s
3176:	learn: 0.0034531	total: 5m 21s	remaining: 11m 30s
3126:	learn: 0.0031134	total: 5m 21s	remaining: 11m 46s
2907:	learn: 0.0039091	total: 5m 21s	remaining: 13m 4s
3131:	learn: 0.0037118	total: 5m 21s	remaining: 11m 44s
3040:	learn: 0.0038326	total: 5m 21s	remaining: 12m 15s
3177:	learn: 0.0034524	total: 5m 21s	remaining: 11m 30s
3127:	learn: 0.0031116	total: 5m 21s	remaining: 11m 46s
3132:	learn: 0.0037103	total: 5m 21s	remaining: 11m 44s
3178:	learn: 0.0034501	total: 5m 21s	remaining: 11m 30s
2908:	learn: 0.0039065	total: 5m 21s	remaining: 13m 3s
3041:	learn: 0.0038306	total: 5m 21s	remaining: 12m 15s
3179:	learn: 0.0034493	total: 5m 21s	remaining: 11m 29s
3133:	learn: 0.0037077	total: 5m 21s	remaining: 11m 44s
3128:	learn: 0.0031092	total: 5m 21s	remaining: 11m 46s
3042:	learn: 0.0038286	total: 5m 21s	remaining: 12m 15s
2909:	learn: 0.0039050	total: 5m 21s	remaining: 13m 3s
3180:	learn: 0.0034474	total: 5m 21s	remaining: 11m 29s
3134:	learn: 0.0037056	total: 5m 21s	remaining: 11m 44s
3043:	learn: 0.0038269	total: 5m 21s	remaining: 12m 15s
3181:	learn: 0.0034455	total: 5m 21s	remaining: 11m 29s
3129:	learn: 0.0031079	total: 5m 21s	remaining: 11m 46s
2910:	learn: 0.0039017	total: 5m 21s	remaining: 13m 3s
3135:	learn: 0.0037041	total: 5m 21s	remaining: 11m 44s
3044:	learn: 0.0038248	total: 5m 21s	remaining: 12m 15s
3136:	learn: 0.0037022	total: 5m 21s	remaining: 11m 43s
3182:	learn: 0.0034430	total: 5m 21s	remaining: 11m 29s
3130:	learn: 0.0031058	total: 5m 21s	remaining: 11m 46s
2911:	learn: 0.0038993	total: 5m 21s	remaining: 13m 3s
3045:	learn: 0.0038226	total: 5m 21s	remaining: 12m 15s
3137:	learn: 0.0037003	total: 5m 21s	remaining: 11m 43s
3183:	learn: 0.0034411	total: 5m 22s	remaining: 11m 29s
3131:	learn: 0.0031037	total: 5m 21s	remaining: 11m 46s
2912:	learn: 0.0038971	total: 5m 22s	remaining: 13m 3s
3046:	learn: 0.0038206	total: 5m 22s	remaining: 12m 14s
3184:	learn: 0.0034392	total: 5m 22s	remaining: 11m 29s
3138:	learn: 0.0036983	total: 5m 22s	remaining: 11m 43s
3132:	learn: 0.0031018	total: 5m 22s	remaining: 11m 45s
3047:	learn: 0.0038180	total: 5m 22s	remaining: 12m 14s
2913:	learn: 0.0038956	total: 5m 22s	remaining: 13m 3s
3185:	learn: 0.0034382	total: 5m 22s	remaining: 11m 29s
3139:	learn: 0.0036967	total: 5m 22s	remaining: 11m 43s
3133:	learn: 0.0031004	total: 5m 22s	remaining: 11m 45s
3048:	learn: 0.0038156	total: 5m 22s	remaining: 12m 14s
3186:	learn: 0.0034363	total: 5m 22s	remaining: 11m 28s
2914:	learn: 0.0038931	total: 5m 22s	remaining: 13m 3s
3140:	learn: 0.0036943	total: 5m 22s	remaining: 11m 43s
3134:	learn: 0.0030990	total: 5m 22s	remaining: 11m 45s
3187:	learn: 0.0034353	total: 5m 22s	remaining: 11m 28s
2915:	learn: 0.0038918	total: 5m 22s	remaining: 13m 3s
3049:	learn: 0.0038135	total: 5m 22s	remaining: 12m 14s
3188:	learn: 0.0034342	total: 5m 22s	remaining: 11m 28s
3141:	learn: 0.0036926	total: 5m 22s	remaining: 11m 43s
3135:	learn: 0.0030970	total: 5m 22s	remaining: 11m 45s
n: 0.0034773	total: 5m 1s	remaining: 12m 8s
2719:	learn:2916:	learn: 0.0038894	total: 5m 22s	remaining: 13m 3s
3189:	learn: 0.0034322	total: 5m 22s	remaining: 11m 28s
3142:	learn: 0.0036910	total: 5m 22s	remaining: 11m 43s
3136:	learn: 0.0030960	total: 5m 22s	remaining: 11m 45s
2917:	learn: 0.0038870	total: 5m 22s	remaining: 13m 2s
3051:	learn: 0.0038103	total: 5m 22s	remaining: 12m 14s
3143:	learn: 0.0036886	total: 5m 22s	remaining: 11m 43s
3190:	learn: 0.0034305	total: 5m 22s	remaining: 11m 28s
3137:	learn: 0.0030942	total: 5m 22s	remaining: 11m 45s
2918:	learn: 0.0038850	total: 5m 22s	remaining: 13m 2s
3052:	learn: 0.0038083	total: 5m 22s	remaining: 12m 14s
3191:	learn: 0.0034290	total: 5m 22s	remaining: 11m 28s
3144:	learn: 0.0036870	total: 5m 22s	remaining: 11m 43s
3138:	learn: 0.0030923	total: 5m 22s	remaining: 11m 45s
3053:	learn: 0.0038066	total: 5m 22s	remaining: 12m 14s
2919:	learn: 0.0038828	total: 5m 22s	remaining: 13m 2s
3192:	learn: 0.0034271	total: 5m 22s	remaining: 11m 28s
3145:	learn: 0.0036848	total: 5m 22s	remaining: 11m 43s
3139:	learn: 0.0030909	total: 5m 22s	remaining: 11m 45s
3054:	learn: 0.0038047	total: 5m 22s	remaining: 12m 14s
2920:	learn: 0.0038805	total: 5m 22s	remaining: 13m 2s
3146:	learn: 0.0036832	total: 5m 22s	remaining: 11m 42s
3193:	learn: 0.0034254	total: 5m 22s	remaining: 11m 28s
3140:	learn: 0.0030889	total: 5m 22s	remaining: 11m 45s
2921:	learn: 0.0038775	total: 5m 23s	remaining: 13m 2s
3055:	learn: 0.0038030	total: 5m 23s	remaining: 12m 13s
3194:	learn: 0.0034233	total: 5m 23s	remaining: 11m 28s
3147:	learn: 0.0036817	total: 5m 22s	remaining: 11m 42s
3141:	learn: 0.0030871	total: 5m 23s	remaining: 11m 45s
2922:	learn: 0.0038752	total: 5m 23s	remaining: 13m 2s
3195:	learn: 0.0034220	total: 5m 23s	remaining: 11m 27s
3056:	learn: 0.0038010	total: 5m 23s	remaining: 12m 13s
3148:	learn: 0.0036800	total: 5m 23s	remaining: 11m 42s
3142:	learn: 0.0030859	total: 5m 23s	remaining: 11m 44s
2923:	learn: 0.0038731	total: 5m 23s	remaining: 13m 2s
3057:	learn: 0.0037990	total: 5m 23s	remaining: 12m 13s
3196:	learn: 0.0034203	total: 5m 23s	remaining: 11m 27s
3143:	learn: 0.0030842	total: 5m 23s	remaining: 11m 44s
3149:	learn: 0.0036780	total: 5m 23s	remaining: 11m 42s
3058:	learn: 0.0037964	total: 5m 23s	remaining: 12m 13s
2924:	learn: 0.0038708	total: 5m 23s	remaining: 13m 2s
3144:	learn: 0.0030824	total: 5m 23s	remaining: 11m 44s
3150:	learn: 0.0036763	total: 5m 23s	remaining: 11m 42s
3197:	learn: 0.0034184	total: 5m 23s	remaining: 11m 27s
3059:	learn: 0.0037944	total: 5m 23s	remaining: 12m 13s
3145:	learn: 0.0030802	total: 5m 23s	remaining: 11m 44s
2925:	learn: 0.0038687	total: 5m 23s	remaining: 13m 1s
3151:	learn: 0.0036748	total: 5m 23s	remaining: 11m 42s
3198:	learn: 0.0034177	total: 5m 23s	remaining: 11m 27s
3146:	learn: 0.0030786	total: 5m 23s	remaining: 11m 44s
3060:	learn: 0.0037918	total: 5m 23s	remaining: 12m 13s
3199:	learn: 0.0034169	total: 5m 23s	remaining: 11m 27s
2926:	learn: 0.0038674	total: 5m 23s	remaining: 13m 1s
3152:	learn: 0.0036737	total: 5m 23s	remaining: 11m 42s
3147:	learn: 0.0030767	total: 5m 23s	remaining: 11m 44s
3200:	learn: 0.0034158	total: 5m 23s	remaining: 11m 27s
3061:	learn: 0.0037895	total: 5m 23s	remaining: 12m 13s
3153:	learn: 0.0036718	total: 5m 23s	remaining: 11m 42s
2927:	learn: 0.0038657	total: 5m 23s	remaining: 13m 1s
3148:	learn: 0.0030754	total: 5m 23s	remaining: 11m 44s
3201:	learn: 0.0034146	total: 5m 23s	remaining: 11m 27s
3062:	learn: 0.0037882	total: 5m 23s	remaining: 12m 13s
3154:	learn: 0.0036702	total: 5m 23s	remaining: 11m 42s
2928:	learn: 0.0038625	total: 5m 23s	remaining: 13m 1s
3149:	learn: 0.0030738	total: 5m 23s	remaining: 11m 43s
3202:	learn: 0.0034135	total: 5m 23s	remaining: 11m 27s
3155:	learn: 0.0036683	total: 5m 23s	remaining: 11m 41s
3063:	learn: 0.0037858	total: 5m 23s	remaining: 12m 13s
3150:	learn: 0.0030723	total: 5m 23s	remaining: 11m 43s
2929:	learn: 0.0038594	total: 5m 23s	remaining: 13m 1s
3156:	learn: 0.0036666	total: 5m 23s	remaining: 11m 41s
3203:	learn: 0.0034125	total: 5m 23s	remaining: 11m 27s
3064:	learn: 0.0037832	total: 5m 23s	remaining: 12m 12s
2930:	learn: 0.0038577	total: 5m 23s	remaining: 13m 1s
3151:	learn: 0.0030702	total: 5m 23s	remaining: 11m 43s
3157:	learn: 0.0036655	total: 5m 23s	remaining: 11m 41s
3204:	learn: 0.0034098	total: 5m 24s	remaining: 11m 27s
3065:	learn: 0.0037807	total: 5m 24s	remaining: 12m 12s
3152:	learn: 0.0030684	total: 5m 24s	remaining: 11m 43s
2931:	learn: 0.0038556	total: 5m 24s	remaining: 13m 1s
3158:	learn: 0.0036640	total: 5m 23s	remaining: 11m 41s
3205:	learn: 0.0034078	total: 5m 24s	remaining: 11m 26s
3066:	learn: 0.0037788	total: 5m 24s	remaining: 12m 12s
2932:	learn: 0.0038539	total: 5m 24s	remaining: 13m 1s
3159:	learn: 0.0036621	total: 5m 24s	remaining: 11m 41s
3153:	learn: 0.0030671	total: 5m 24s	remaining: 11m 43s
3206:	learn: 0.0034059	total: 5m 24s	remaining: 11m 26s
3160:	learn: 0.0036598	total: 5m 24s	remaining: 11m 41s
3067:	learn: 0.0037771	total: 5m 24s	remaining: 12m 12s
2933:	learn: 0.0038517	total: 5m 24s	remaining: 13m 1s
3154:	learn: 0.0030657	total: 5m 24s	remaining: 11m 43s
3207:	learn: 0.0034051	total: 5m 24s	remaining: 11m 26s
3068:	learn: 0.0037752	total: 5m 24s	remaining: 12m 12s
3161:	learn: 0.0036575	total: 5m 24s	remaining: 11m 41s
3155:	learn: 0.0030645	total: 5m 24s	remaining: 11m 43s
2934:	learn: 0.0038496	total: 5m 24s	remaining: 13m
3208:	learn: 0.0034033	total: 5m 24s	remaining: 11m 26s
3069:	learn: 0.0037727	total: 5m 24s	remaining: 12m 12s
3156:	learn: 0.0030626	total: 5m 24s	remaining: 11m 43s
3162:	learn: 0.0036556	total: 5m 24s	remaining: 11m 41s
2935:	learn: 0.0038482	total: 5m 24s	remaining: 13m
3209:	learn: 0.0034015	total: 5m 24s	remaining: 11m 26s
3157:	learn: 0.0030609	total: 5m 24s	remaining: 11m 43s
3070:	learn: 0.0037719	total: 5m 24s	remaining: 12m 12s
3163:	learn: 0.0036545	total: 5m 24s	remaining: 11m 41s
3210:	learn: 0.0034003	total: 5m 24s	remaining: 11m 26s
3158:	learn: 0.0030591	total: 5m 24s	remaining: 11m 42s
2936:	learn: 0.0038462	total: 5m 24s	remaining: 13m
3071:	learn: 0.0037695	total: 5m 24s	remaining: 12m 12s
3164:	learn: 0.0036523	total: 5m 24s	remaining: 11m 40s
3211:	learn: 0.0033985	total: 5m 24s	remaining: 11m 26s
2937:	learn: 0.0038450	total: 5m 24s	remaining: 13m
3159:	learn: 0.0030575	total: 5m 24s	remaining: 11m 42s
3165:	learn: 0.0036513	total: 5m 24s	remaining: 11m 40s
3072:	learn: 0.0037679	total: 5m 24s	remaining: 12m 12s
2938:	learn: 0.0038423	total: 5m 24s	remaining: 13m
3212:	learn: 0.0033977	total: 5m 24s	remaining: 11m 26s
3160:	learn: 0.0030563	total: 5m 24s	remaining: 11m 42s
3073:	learn: 0.0037668	total: 5m 24s	remaining: 12m 11s
3166:	learn: 0.0036492	total: 5m 24s	remaining: 11m 40s
2939:	learn: 0.0038404	total: 5m 24s	remaining: 13m
3161:	learn: 0.0030546	total: 5m 24s	remaining: 11m 42s
3213:	learn: 0.0033958	total: 5m 24s	remaining: 11m 26s
3074:	learn: 0.0037648	total: 5m 24s	remaining: 12m 11s
3167:	learn: 0.0036483	total: 5m 24s	remaining: 11m 40s
3162:	learn: 0.0030537	total: 5m 24s	remaining: 11m 42s
2940:	learn: 0.0038379	total: 5m 25s	remaining: 13m
3214:	learn: 0.0033939	total: 5m 25s	remaining: 11m 25s
3075:	learn: 0.0037625	total: 5m 25s	remaining: 12m 11s
3168:	learn: 0.0036465	total: 5m 24s	remaining: 11m 40s
3163:	learn: 0.0030525	total: 5m 25s	remaining: 11m 42s
3215:	learn: 0.0033922	total: 5m 25s	remaining: 11m 25s
3076:	learn: 0.0037603	total: 5m 25s	remaining: 12m 11s
2941:	learn: 0.0038357	total: 5m 25s	remaining: 13m
3164:	learn: 0.0030507	total: 5m 25s	remaining: 11m 42s
3216:	learn: 0.0033903	total: 5m 25s	remaining: 11m 25s
3169:	learn: 0.0036446	total: 5m 25s	remaining: 11m 40s
3077:	learn: 0.0037576	total: 5m 25s	remaining: 12m 11s
3165:	learn: 0.0030490	total: 5m 25s	remaining: 11m 42s
2942:	learn: 0.0038337	total: 5m 25s	remaining: 13m
3170:	learn: 0.0036431	total: 5m 25s	remaining: 11m 40s
3166:	learn: 0.0030475	total: 5m 25s	remaining: 11m 41s
3217:	learn: 0.0033879	total: 5m 25s	remaining: 11m 25s
3078:	learn: 0.0037557	total: 5m 25s	remaining: 12m 11s
3171:	learn: 0.0036425	total: 5m 25s	remaining: 11m 40s
2943:	learn: 0.0038311	total: 5m 25s	remaining: 12m 59s
:	learn: 0.0044132	total: 4m 58s	remaining: 13m 30s

 m 23218:	learn: 0.0033865	total: 5m 25s	remaining: 11m 25s
3167:	learn: 0.0030466	total: 5m 25s	remaining: 11m 41s
3079:	learn: 0.0037541	total: 5m 25s	remaining: 12m 11s
3172:	learn: 0.0036407	total: 5m 25s	remaining: 11m 40s
2944:	learn: 0.0038288	total: 5m 25s	remaining: 12m 59s
3219:	learn: 0.0033846	total: 5m 25s	remaining: 11m 25s
3080:	learn: 0.0037526	total: 5m 25s	remaining: 12m 11s
3168:	learn: 0.0030453	total: 5m 25s	remaining: 11m 41s
3173:	learn: 0.0036391	total: 5m 25s	remaining: 11m 39s
3220:	learn: 0.0033834	total: 5m 25s	remaining: 11m 25s
2945:	learn: 0.0038267	total: 5m 25s	remaining: 12m 59s
3169:	learn: 0.0030441	total: 5m 25s	remaining: 11m 41s
3081:	learn: 0.0037505	total: 5m 25s	remaining: 12m 10s
3174:	learn: 0.0036376	total: 5m 25s	remaining: 11m 39s
3221:	learn: 0.0033823	total: 5m 25s	remaining: 11m 25s
2946:	learn: 0.0038248	total: 5m 25s	remaining: 12m 59s
3082:	learn: 0.0037483	total: 5m 25s	remaining: 12m 10s
3175:	learn: 0.0036354	total: 5m 25s	remaining: 11m 39s
3170:	learn: 0.0030430	total: 5m 25s	remaining: 11m 41s
3222:	learn: 0.0033811	total: 5m 25s	remaining: 11m 25s
2947:	learn: 0.0038232	total: 5m 25s	remaining: 12m 59s
3171:	learn: 0.0030410	total: 5m 25s	remaining: 11m 41s
3223:	learn: 0.0033791	total: 5m 25s	remaining: 11m 24s
3083:	learn: 0.0037461	total: 5m 25s	remaining: 12m 10s
3176:	learn: 0.0036334	total: 5m 25s	remaining: 11m 39s
2948:	learn: 0.0038211	total: 5m 25s	remaining: 12m 59s
3172:	learn: 0.0030394	total: 5m 25s	remaining: 11m 41s
3224:	learn: 0.0033771	total: 5m 25s	remaining: 11m 24s
3177:	learn: 0.0036322	total: 5m 25s	remaining: 11m 39s
3084:	learn: 0.0037437	total: 5m 25s	remaining: 12m 10s
2949:	learn: 0.0038180	total: 5m 26s	remaining: 12m 59s
3178:	learn: 0.0036300	total: 5m 25s	remaining: 11m 39s
3173:	learn: 0.0030372	total: 5m 26s	remaining: 11m 41s
3225:	learn: 0.0033755	total: 5m 26s	remaining: 11m 24s
3085:	learn: 0.0037417	total: 5m 26s	remaining: 12m 10s
2950:	learn: 0.0038164	total: 5m 26s	remaining: 12m 59s
3179:	learn: 0.0036287	total: 5m 26s	remaining: 11m 39s
3226:	learn: 0.0033737	total: 5m 26s	remaining: 11m 24s
3174:	learn: 0.0030358	total: 5m 26s	remaining: 11m 41s
2951:	learn: 0.0038141	total: 5m 26s	remaining: 12m 58s
3086:	learn: 0.0037394	total: 5m 26s	remaining: 12m 10s
3180:	learn: 0.0036268	total: 5m 26s	remaining: 11m 39s
3227:	learn: 0.0033718	total: 5m 26s	remaining: 11m 24s
3175:	learn: 0.0030347	total: 5m 26s	remaining: 11m 40s
2952:	learn: 0.0038119	total: 5m 26s	remaining: 12m 58s
3087:	learn: 0.0037371	total: 5m 26s	remaining: 12m 10s
3228:	learn: 0.0033707	total: 5m 26s	remaining: 11m 24s
3181:	learn: 0.0036248	total: 5m 26s	remaining: 11m 39s
2953:	learn: 0.0038093	total: 5m 26s	remaining: 12m 58s
3176:	learn: 0.0030331	total: 5m 26s	remaining: 11m 40s
3088:	learn: 0.0037348	total: 5m 26s	remaining: 12m 10s
3182:	learn: 0.0036233	total: 5m 26s	remaining: 11m 38s
3229:	learn: 0.0033688	total: 5m 26s	remaining: 11m 24s
3177:	learn: 0.0030313	total: 5m 26s	remaining: 11m 40s
2954:	learn: 0.0038073	total: 5m 26s	remaining: 12m 58s
3183:	learn: 0.0036221	total: 5m 26s	remaining: 11m 38s
3089:	learn: 0.0037324	total: 5m 26s	remaining: 12m 10s
3230:	learn: 0.0033669	total: 5m 26s	remaining: 11m 24s
3178:	learn: 0.0030299	total: 5m 26s	remaining: 11m 40s
2955:	learn: 0.0038058	total: 5m 26s	remaining: 12m 58s
3184:	learn: 0.0036206	total: 5m 26s	remaining: 11m 38s
3231:	learn: 0.0033651	total: 5m 26s	remaining: 11m 24s
3179:	learn: 0.0030284	total: 5m 26s	remaining: 11m 40s
3090:	learn: 0.0037310	total: 5m 26s	remaining: 12m 10s
2956:	learn: 0.0038036	total: 5m 26s	remaining: 12m 58s
3185:	learn: 0.0036185	total: 5m 26s	remaining: 11m 38s
3232:	learn: 0.0033632	total: 5m 26s	remaining: 11m 23s
3180:	learn: 0.0030272	total: 5m 26s	remaining: 11m 40s
3091:	learn: 0.0037296	total: 5m 26s	remaining: 12m 10s
2957:	learn: 0.0038020	total: 5m 26s	remaining: 12m 58s
3186:	learn: 0.0036165	total: 5m 26s	remaining: 11m 38s
3233:	learn: 0.0033614	total: 5m 26s	remaining: 11m 23s
3092:	learn: 0.0037290	total: 5m 26s	remaining: 12m 9s
3181:	learn: 0.0030257	total: 5m 26s	remaining: 11m 40s
3187:	learn: 0.0036153	total: 5m 26s	remaining: 11m 38s
2958:	learn: 0.0037995	total: 5m 26s	remaining: 12m 57s
3234:	learn: 0.0033598	total: 5m 26s	remaining: 11m 23s
3093:	learn: 0.0037280	total: 5m 26s	remaining: 12m 9s
3182:	learn: 0.0030241	total: 5m 26s	remaining: 11m 40s
3188:	learn: 0.0036134	total: 5m 26s	remaining: 11m 38s
2959:	learn: 0.0037979	total: 5m 27s	remaining: 12m 57s
3235:	learn: 0.0033586	total: 5m 27s	remaining: 11m 23s
3094:	learn: 0.0037257	total: 5m 27s	remaining: 12m 9s
3183:	learn: 0.0030222	total: 5m 27s	remaining: 11m 40s
3189:	learn: 0.0036116	total: 5m 26s	remaining: 11m 38s
2960:	learn: 0.0037960	total: 5m 27s	remaining: 12m 57s
3236:	learn: 0.0033575	total: 5m 27s	remaining: 11m 23s
3095:	learn: 0.0037238	total: 5m 27s	remaining: 12m 9s
3184:	learn: 0.0030203	total: 5m 27s	remaining: 11m 39s
3185:	learn: 0.0030192	total: 5m 27s	remaining: 11m 39s
3096:	learn: 0.0037216	total: 5m 27s	remaining: 12m 9s
3190:	learn: 0.0036104	total: 5m 27s	remaining: 11m 38s
3237:	learn: 0.0033557	total: 5m 27s	remaining: 11m 23s
2961:	learn: 0.0037930	total: 5m 27s	remaining: 12m 57s
3186:	learn: 0.0030172	total: 5m 27s	remaining: 11m 39s
3097:	learn: 0.0037205	total: 5m 27s	remaining: 12m 9s
3238:	learn: 0.0033541	total: 5m 27s	remaining: 11m 23s
3191:	learn: 0.0036089	total: 5m 27s	remaining: 11m 37s
3187:	learn: 0.0030154	total: 5m 27s	remaining: 11m 39s
2962:	learn: 0.0037909	total: 5m 27s	remaining: 12m 57s
3239:	learn: 0.0033520	total: 5m 27s	remaining: 11m 23s
3192:	learn: 0.0036073	total: 5m 27s	remaining: 11m 37s
3098:	learn: 0.0037181	total: 5m 27s	remaining: 12m 9s
2963:	learn: 0.0037893	total: 5m 27s	remaining: 12m 57s
3188:	learn: 0.0030137	total: 5m 27s	remaining: 11m 39s
3240:	learn: 0.0033503	total: 5m 27s	remaining: 11m 23s
3193:	learn: 0.0036060	total: 5m 27s	remaining: 11m 37s
3099:	learn: 0.0037155	total: 5m 27s	remaining: 12m 9s
2964:	learn: 0.0037877	total: 5m 27s	remaining: 12m 57s
3189:	learn: 0.0030126	total: 5m 27s	remaining: 11m 39s
3241:	learn: 0.0033492	total: 5m 27s	remaining: 11m 23s
3194:	learn: 0.0036044	total: 5m 27s	remaining: 11m 37s
2965:	learn: 0.0037850	total: 5m 27s	remaining: 12m 57s
3190:	learn: 0.0030109	total: 5m 27s	remaining: 11m 39s
3100:	learn: 0.0037135	total: 5m 27s	remaining: 12m 9s
3195:	learn: 0.0036032	total: 5m 27s	remaining: 11m 37s
3242:	learn: 0.0033474	total: 5m 27s	remaining: 11m 22s
3101:	learn: 0.0037118	total: 5m 27s	remaining: 12m 8s
2966:	learn: 0.0037829	total: 5m 27s	remaining: 12m 57s
3191:	learn: 0.0030095	total: 5m 27s	remaining: 11m 39s
3196:	learn: 0.0036023	total: 5m 27s	remaining: 11m 37s
3102:	learn: 0.0037096	total: 5m 27s	remaining: 12m 8s
3243:	learn: 0.0033454	total: 5m 27s	remaining: 11m 22s
2967:	learn: 0.0037815	total: 5m 27s	remaining: 12m 56s
3192:	learn: 0.0030082	total: 5m 27s	remaining: 11m 39s
3197:	learn: 0.0036005	total: 5m 27s	remaining: 11m 37s
3103:	learn: 0.0037074	total: 5m 27s	remaining: 12m 8s
2968:	learn: 0.0037809	total: 5m 28s	remaining: 12m 56s
3193:	learn: 0.0030070	total: 5m 27s	remaining: 11m 38s
3244:	learn: 0.0033444	total: 5m 28s	remaining: 11m 22s
3104:	learn: 0.0037061	total: 5m 28s	remaining: 12m 8s
3198:	learn: 0.0035987	total: 5m 27s	remaining: 11m 37s
3194:	learn: 0.0030054	total: 5m 28s	remaining: 11m 38s
3245:	learn: 0.0033432	total: 5m 28s	remaining: 11m 22s
2969:	learn: 0.0037781	total: 5m 28s	remaining: 12m 56s
3199:	learn: 0.0035974	total: 5m 28s	remaining: 11m 37s
3105:	learn: 0.0037046	total: 5m 28s	remaining: 12m 8s
3246:	learn: 0.0033419	total: 5m 28s	remaining: 11m 22s
3195:	learn: 0.0030040	total: 5m 28s	remaining: 11m 38s
3200:	learn: 0.0035956	total: 5m 28s	remaining: 11m 36s
2970:	learn: 0.0037749	total: 5m 28s	remaining: 12m 56s
3196:	learn: 0.0030024	total: 5m 28s	remaining: 11m 38s
3106:	learn: 0.0037037	total: 5m 28s	remaining: 12m 8s
3247:	learn: 0.0033407	total: 5m 28s	remaining: 11m 22s
3201:	learn: 0.0035946	total: 5m 28s	remaining: 11m 36s
2971:	learn: 0.0037733	total: 5m 28s	remaining: 12m 56s
3107:	learn: 0.0037015	total: 5m 28s	remaining: 12m 8s
3248:	learn: 0.0033389	total: 5m 28s	remaining: 11m 22s
3202:	learn: 0.0035935	total: 5m 28s	remaining: 11m 36s
2972:	learn: 0.0037706	total: 5m 28s	remaining: 12m 56s
3108:	learn: 0.0037008	total: 5m 28s	remaining: 12m 7s
3198:	learn: 0.0029992	total: 5m 28s	remaining: 11m 38s
2973:	learn: 0.0037691	total: 5m 28s	remaining: 12m 56s
3203:	learn: 0.0035920	total: 5m 28s	remaining: 11m 36s
3249:	learn: 0.0033372	total: 5m 28s	remaining: 11m 22s
3109:	learn: 0.0036987	total: 5m 28s	remaining: 12m 7s
3199:	learn: 0.0029976	total: 5m 28s	remaining: 11m 38s
2974:	learn: 0.0037667	total: 5m 28s	remaining: 12m 56s
3204:	learn: 0.0035902	total: 5m 28s	remaining: 11m 36s
3250:	learn: 0.0033354	total: 5m 28s	remaining: 11m 22s
3110:	learn: 0.0036963	total: 5m 28s	remaining: 12m 7s
2975:	learn: 0.0037650	total: 5m 28s	remaining: 12m 55s
3200:	learn: 0.0029962	total: 5m 28s	remaining: 11m 38s
3251:	learn: 0.0033340	total: 5m 28s	remaining: 11m 22s
3205:	learn: 0.0035880	total: 5m 28s	remaining: 11m 36s
3111:	learn: 0.0036954	total: 5m 28s	remaining: 12m 7s
2976:	learn: 0.0037634	total: 5m 28s	remaining: 12m 55s
3201:	learn: 0.0029950	total: 5m 28s	remaining: 11m 37s
3206:	learn: 0.0035864	total: 5m 28s	remaining: 11m 36s
3252:	learn: 0.0033330	total: 5m 28s	remaining: 11m 22s
2977:	learn: 0.0037619	total: 5m 28s	remaining: 12m 55s
3202:	learn: 0.0029933	total: 5m 28s	remaining: 11m 37s
3112:	learn: 0.0036938	total: 5m 28s	remaining: 12m 7s
3207:	learn: 0.0035850	total: 5m 28s	remaining: 11m 36s
3253:	learn: 0.0033313	total: 5m 28s	remaining: 11m 21s
2978:	learn: 0.0037604	total: 5m 28s	remaining: 12m 55s
3113:	learn: 0.0036918	total: 5m 28s	remaining: 12m 7s
3203:	learn: 0.0029920	total: 5m 28s	remaining: 11m 37s
3254:	learn: 0.0033294	total: 5m 29s	remaining: 11m 21s
3208:	learn: 0.0035838	total: 5m 28s	remaining: 11m 36s
2979:	learn: 0.0037588	total: 5m 29s	remaining: 12m 55s
3114:	learn: 0.0036894	total: 5m 29s	remaining: 12m 7s
3255:	learn: 0.0033276	total: 5m 29s	remaining: 11m 21s
3204:	learn: 0.0029910	total: 5m 29s	remaining: 11m 37s
2980:	learn: 0.0037583	total: 5m 29s	remaining: 12m 55s
3209:	learn: 0.0035823	total: 5m 29s	remaining: 11m 36s
3115:	learn: 0.0036880	total: 5m 29s	remaining: 12m 7s
3256:	learn: 0.0033269	total: 5m 29s	remaining: 11m 21s
3205:	learn: 0.0029894	total: 5m 29s	remaining: 11m 37s
3116:	learn: 0.0036860	total: 5m 29s	remaining: 12m 6s
2981:	learn: 0.0037568	total: 5m 29s	remaining: 12m 54s
3210:	learn: 0.0035805	total: 5m 29s	remaining: 11m 35s
3257:	learn: 0.0033254	total: 5m 29s	remaining: 11m 21s
3117:	learn: 0.0036834	total: 5m 29s	remaining: 12m 6s
2982:	learn: 0.0037546	total: 5m 29s	remaining: 12m 54s
3206:	learn: 0.0029881	total: 5m 29s	remaining: 11m 37s
3211:	learn: 0.0035797	total: 5m 29s	remaining: 11m 35s
3258:	learn: 0.0033244	total: 5m 29s	remaining: 11m 21s
3118:	learn: 0.0036811	total: 5m 29s	remaining: 12m 6s
2983:	learn: 0.0037538	total: 5m 29s	remaining: 12m 54s
3212:	learn: 0.0035777	total: 5m 29s	remaining: 11m 35s
3207:	learn: 0.0029866	total: 5m 29s	remaining: 11m 37s
3259:	learn: 0.0033227	total: 5m 29s	remaining: 11m 21s
3119:	learn: 0.0036790	total: 5m 29s	remaining: 12m 6s
2984:	learn: 0.0037524	total: 5m 29s	remaining: 12m 54s
3213:	learn: 0.0035757	total: 5m 29s	remaining: 11m 35s
3260:	learn: 0.0033203	total: 5m 29s	remaining: 11m 21s
3120:	learn: 0.0036768	total: 5m 29s	remaining: 12m 6s
2985:	learn: 0.0037494	total: 5m 29s	remaining: 12m 54s
3208:	learn: 0.0029854	total: 5m 29s	remaining: 11m 37s
3214:	learn: 0.0035745	total: 5m 29s	remaining: 11m 35s
3121:	learn: 0.0036750	total: 5m 29s	remaining: 12m 6s
3261:	learn: 0.0033181	total: 5m 29s	remaining: 11m 21s
2986:	learn: 0.0037487	total: 5m 29s	remaining: 12m 54s
3209:	learn: 0.0029844	total: 5m 29s	remaining: 11m 37s
3215:	learn: 0.0035731	total: 5m 29s	remaining: 11m 35s
3122:	learn: 0.0036728	total: 5m 29s	remaining: 12m 6s
3262:	learn: 0.0033164	total: 5m 29s	remaining: 11m 21s
2987:	learn: 0.0037462	total: 5m 29s	remaining: 12m 54s
3216:	learn: 0.0035715	total: 5m 29s	remaining: 11m 35s
3210:	learn: 0.0029830	total: 5m 29s	remaining: 11m 37s
3123:	learn: 0.0036708	total: 5m 29s	remaining: 12m 5s
3263:	learn: 0.0033150	total: 5m 29s	remaining: 11m 20s
2988:	learn: 0.0037432	total: 5m 29s	remaining: 12m 53s
3211:	learn: 0.0029820	total: 5m 29s	remaining: 11m 37s
3217:	learn: 0.0035692	total: 5m 29s	remaining: 11m 35s
2989:	learn: 0.0037402	total: 5m 30s	remaining: 12m 53s
3124:	learn: 0.0036699	total: 5m 29s	remaining: 12m 5s
3264:	learn: 0.0033138	total: 5m 30s	remaining: 11m 20s
3212:	learn: 0.0029807	total: 5m 30s	remaining: 11m 37s
3218:	learn: 0.0035669	total: 5m 29s	remaining: 11m 35s
3125:	learn: 0.0036677	total: 5m 30s	remaining: 12m 5s
3265:	learn: 0.0033128	total: 5m 30s	remaining: 11m 20s
2990:	learn: 0.0037377	total: 5m 30s	remaining: 12m 53s
3213:	learn: 0.0029795	total: 5m 30s	remaining: 11m 36s
3219:	learn: 0.0035653	total: 5m 30s	remaining: 11m 34s
3266:	learn: 0.0033112	total: 5m 30s	remaining: 11m 20s
3126:	learn: 0.0036657	total: 5m 30s	remaining: 12m 5s
3214:	learn: 0.0029777	total: 5m 30s	remaining: 11m 36s
2991:	learn: 0.0037365	total: 5m 30s	remaining: 12m 53s
3220:	learn: 0.0035636	total: 5m 30s	remaining: 11m 34s
3215:	learn: 0.0029764	total: 5m 30s	remaining: 11m 36s
3267:	learn: 0.0033095	total: 5m 30s	remaining: 11m 20s
3127:	learn: 0.0036634	total: 5m 30s	remaining: 12m 5s
2992:	learn: 0.0037349	total: 5m 30s	remaining: 12m 53s
3216:	learn: 0.0029748	total: 5m 30s	remaining: 11m 36s
3221:	learn: 0.0035612	total: 5m 30s	remaining: 11m 34s
3128:	learn: 0.0036615	total: 5m 30s	remaining: 12m 5s
3268:	learn: 0.0033081	total: 5m 30s	remaining: 11m 20s
2993:	learn: 0.0037342	total: 5m 30s	remaining: 12m 53s
3269:	learn: 0.0033066	total: 5m 30s	remaining: 11m 20s
3129:	learn: 0.0036588	total: 5m 30s	remaining: 12m 5s
3217:	learn: 0.0029731	total: 5m 30s	remaining: 11m 36s
3222:	learn: 0.0035604	total: 5m 30s	remaining: 11m 34s
2994:	learn: 0.0037315	total: 5m 30s	remaining: 12m 53s
3270:	learn: 0.0033053	total: 5m 30s	remaining: 11m 20s
3130:	learn: 0.0036577	total: 5m 30s	remaining: 12m 5s
3223:	learn: 0.0035595	total: 5m 30s	remaining: 11m 34s
3218:	learn: 0.0029719	total: 5m 30s	remaining: 11m 36s
3271:	learn: 0.0033041	total: 5m 30s	remaining: 11m 19s
2995:	learn: 0.0037302	total: 5m 30s	remaining: 12m 53s
3224:	learn: 0.0035575	total: 5m 30s	remaining: 11m 34s
3131:	learn: 0.0036557	total: 5m 30s	remaining: 12m 5s
3219:	learn: 0.0029708	total: 5m 30s	remaining: 11m 36s
3225:	learn: 0.0035563	total: 5m 30s	remaining: 11m 34s
3272:	learn: 0.0033025	total: 5m 30s	remaining: 11m 19s
3132:	learn: 0.0036533	total: 5m 30s	remaining: 12m 4s
2996:	learn: 0.0037272	total: 5m 30s	remaining: 12m 53s
3220:	learn: 0.0029695	total: 5m 30s	remaining: 11m 36s
3226:	learn: 0.0035551	total: 5m 30s	remaining: 11m 34s
3273:	learn: 0.0033007	total: 5m 30s	remaining: 11m 19s
3133:	learn: 0.0036517	total: 5m 30s	remaining: 12m 4s
2997:	learn: 0.0037247	total: 5m 30s	remaining: 12m 52s
3221:	learn: 0.0029677	total: 5m 30s	remaining: 11m 36s
3227:	learn: 0.0035529	total: 5m 30s	remaining: 11m 34s
3274:	learn: 0.0032993	total: 5m 30s	remaining: 11m 19s
3134:	learn: 0.0036492	total: 5m 30s	remaining: 12m 4s
2998:	learn: 0.0037238	total: 5m 31s	remaining: 12m 52s
3222:	learn: 0.0029664	total: 5m 31s	remaining: 11m 35s
3275:	learn: 0.0032971	total: 5m 31s	remaining: 11m 19s
3228:	learn: 0.0035516	total: 5m 30s	remaining: 11m 33s
3135:	learn: 0.0036467	total: 5m 31s	remaining: 12m 4s
2999:	learn: 0.0037211	total: 5m 31s	remaining: 12m 52s
3276:	learn: 0.0032953	total: 5m 31s	remaining: 11m 19s
3223:	learn: 0.0029656	total: 5m 31s	remaining: 11m 35s
3136:	learn: 0.0036454	total: 5m 31s	remaining: 12m 4s
3229:	learn: 0.0035506	total: 5m 31s	remaining: 11m 33s
3000:	learn: 0.0037182	total: 5m 31s	remaining: 12m 52s
3277:	learn: 0.0032940	total: 5m 31s	remaining: 11m 19s
3137:	learn: 0.0036444	total: 5m 31s	remaining: 12m 4s
3224:	learn: 0.0029642	total: 5m 31s	remaining: 11m 35s
 6s

3107:	learn: 0.0031429	total: 5m 19s	remaining: 11m 3230:	learn: 0.0035491	total: 5m 31s	remaining: 11m 33s
3138:	learn: 0.0036426	total: 5m 31s	remaining: 12m 4s
3001:	learn: 0.0037170	total: 5m 31s	remaining: 12m 52s
3225:	learn: 0.0029634	total: 5m 31s	remaining: 11m 35s
3231:	learn: 0.0035482	total: 5m 31s	remaining: 11m 33s
3279:	learn: 0.0032903	total: 5m 31s	remaining: 11m 19s
3002:	learn: 0.0037157	total: 5m 31s	remaining: 12m 52s
3139:	learn: 0.0036410	total: 5m 31s	remaining: 12m 3s
3232:	learn: 0.0035462	total: 5m 31s	remaining: 11m 33s
3140:	learn: 0.0036394	total: 5m 31s	remaining: 12m 3s
3003:	learn: 0.0037133	total: 5m 31s	remaining: 12m 52s
3226:	learn: 0.0029620	total: 5m 31s	remaining: 11m 35s
3280:	learn: 0.0032885	total: 5m 31s	remaining: 11m 18s
3233:	learn: 0.0035442	total: 5m 31s	remaining: 11m 33s
3141:	learn: 0.0036381	total: 5m 31s	remaining: 12m 3s
3004:	learn: 0.0037116	total: 5m 31s	remaining: 12m 51s
3281:	learn: 0.0032872	total: 5m 31s	remaining: 11m 18s
3227:	learn: 0.0029606	total: 5m 31s	remaining: 11m 35s
3234:	learn: 0.0035426	total: 5m 31s	remaining: 11m 33s
3282:	learn: 0.0032855	total: 5m 31s	remaining: 11m 18s
3142:	learn: 0.0036357	total: 5m 31s	remaining: 12m 3s
3005:	learn: 0.0037087	total: 5m 31s	remaining: 12m 51s
3228:	learn: 0.0029593	total: 5m 31s	remaining: 11m 35s
3283:	learn: 0.0032840	total: 5m 31s	remaining: 11m 18s
3235:	learn: 0.0035416	total: 5m 31s	remaining: 11m 33s
3006:	learn: 0.0037080	total: 5m 31s	remaining: 12m 51s
3143:	learn: 0.0036340	total: 5m 31s	remaining: 12m 3s
3284:	learn: 0.0032822	total: 5m 31s	remaining: 11m 18s
3229:	learn: 0.0029575	total: 5m 31s	remaining: 11m 35s
3236:	learn: 0.0035399	total: 5m 31s	remaining: 11m 33s
3007:	learn: 0.0037057	total: 5m 31s	remaining: 12m 51s
3144:	learn: 0.0036315	total: 5m 31s	remaining: 12m 3s
3285:	learn: 0.0032806	total: 5m 31s	remaining: 11m 18s
3230:	learn: 0.0029562	total: 5m 31s	remaining: 11m 35s
3008:	learn: 0.0037030	total: 5m 32s	remaining: 12m 51s
3237:	learn: 0.0035386	total: 5m 31s	remaining: 11m 33s
3145:	learn: 0.0036292	total: 5m 32s	remaining: 12m 3s
3286:	learn: 0.0032788	total: 5m 32s	remaining: 11m 18s
3231:	learn: 0.0029545	total: 5m 32s	remaining: 11m 35s
3238:	learn: 0.0035368	total: 5m 31s	remaining: 11m 32s
3146:	learn: 0.0036275	total: 5m 32s	remaining: 12m 3s
3009:	learn: 0.0037020	total: 5m 32s	remaining: 12m 51s
3287:	learn: 0.0032770	total: 5m 32s	remaining: 11m 18s
3232:	learn: 0.0029528	total: 5m 32s	remaining: 11m 35s
3239:	learn: 0.0035351	total: 5m 32s	remaining: 11m 32s
3147:	learn: 0.0036254	total: 5m 32s	remaining: 12m 3s
3010:	learn: 0.0037003	total: 5m 32s	remaining: 12m 51s
3233:	learn: 0.0029514	total: 5m 32s	remaining: 11m 35s
3288:	learn: 0.0032750	total: 5m 32s	remaining: 11m 18s
3240:	learn: 0.0035333	total: 5m 32s	remaining: 11m 32s
3148:	learn: 0.0036241	total: 5m 32s	remaining: 12m 2s
3234:	learn: 0.0029501	total: 5m 32s	remaining: 11m 34s
3011:	learn: 0.0036996	total: 5m 32s	remaining: 12m 51s
3289:	learn: 0.0032728	total: 5m 32s	remaining: 11m 17s
3241:	learn: 0.0035323	total: 5m 32s	remaining: 11m 32s
3149:	learn: 0.0036225	total: 5m 32s	remaining: 12m 2s
3290:	learn: 0.0032703	total: 5m 32s	remaining: 11m 17s
3012:	learn: 0.0036978	total: 5m 32s	remaining: 12m 50s
3235:	learn: 0.0029488	total: 5m 32s	remaining: 11m 34s
3150:	learn: 0.0036211	total: 5m 32s	remaining: 12m 2s
3242:	learn: 0.0035307	total: 5m 32s	remaining: 11m 32s
3291:	learn: 0.0032687	total: 5m 32s	remaining: 11m 17s
3236:	learn: 0.0029475	total: 5m 32s	remaining: 11m 34s
3013:	learn: 0.0036950	total: 5m 32s	remaining: 12m 50s
3151:	learn: 0.0036195	total: 5m 32s	remaining: 12m 2s
3243:	learn: 0.0035287	total: 5m 32s	remaining: 11m 32s
3292:	learn: 0.0032666	total: 5m 32s	remaining: 11m 17s
3152:	learn: 0.0036172	total: 5m 32s	remaining: 12m 2s
3237:	learn: 0.0029464	total: 5m 32s	remaining: 11m 34s
3014:	learn: 0.0036936	total: 5m 32s	remaining: 12m 50s
3293:	learn: 0.0032652	total: 5m 32s	remaining: 11m 17s
3244:	learn: 0.0035274	total: 5m 32s	remaining: 11m 32s
3238:	learn: 0.0029449	total: 5m 32s	remaining: 11m 34s
3015:	learn: 0.0036929	total: 5m 32s	remaining: 12m 50s
3153:	learn: 0.0036164	total: 5m 32s	remaining: 12m 2s
3245:	learn: 0.0035260	total: 5m 32s	remaining: 11m 32s
3294:	learn: 0.0032637	total: 5m 32s	remaining: 11m 17s
3016:	learn: 0.0036905	total: 5m 32s	remaining: 12m 50s
3239:	learn: 0.0029435	total: 5m 32s	remaining: 11m 34s
3154:	learn: 0.0036149	total: 5m 32s	remaining: 12m 2s
3246:	learn: 0.0035247	total: 5m 32s	remaining: 11m 32s
3295:	learn: 0.0032616	total: 5m 32s	remaining: 11m 17s
3240:	learn: 0.0029417	total: 5m 32s	remaining: 11m 34s
3017:	learn: 0.0036885	total: 5m 32s	remaining: 12m 50s
3155:	learn: 0.0036130	total: 5m 32s	remaining: 12m 2s
3247:	learn: 0.0035237	total: 5m 32s	remaining: 11m 31s
3241:	learn: 0.0029400	total: 5m 33s	remaining: 11m 34s
3296:	learn: 0.0032594	total: 5m 33s	remaining: 11m 17s
3018:	learn: 0.0036864	total: 5m 33s	remaining: 12m 50s
3156:	learn: 0.0036106	total: 5m 33s	remaining: 12m 1s
3248:	learn: 0.0035221	total: 5m 32s	remaining: 11m 31s
3242:	learn: 0.0029380	total: 5m 33s	remaining: 11m 34s
3297:	learn: 0.0032572	total: 5m 33s	remaining: 11m 17s
3019:	learn: 0.0036839	total: 5m 33s	remaining: 12m 50s
3249:	learn: 0.0035206	total: 5m 33s	remaining: 11m 31s
3157:	learn: 0.0036084	total: 5m 33s	remaining: 12m 1s
3243:	learn: 0.0029366	total: 5m 33s	remaining: 11m 33s
3298:	learn: 0.0032558	total: 5m 33s	remaining: 11m 16s
3020:	learn: 0.0036821	total: 5m 33s	remaining: 12m 49s
3158:	learn: 0.0036062	total: 5m 33s	remaining: 12m 1s
3250:	learn: 0.0035191	total: 5m 33s	remaining: 11m 31s
3244:	learn: 0.0029349	total: 5m 33s	remaining: 11m 33s
3299:	learn: 0.0032542	total: 5m 33s	remaining: 11m 16s
3021:	learn: 0.0036795	total: 5m 33s	remaining: 12m 49s
3159:	learn: 0.0036048	total: 5m 33s	remaining: 12m 1s
3245:	learn: 0.0029339	total: 5m 33s	remaining: 11m 33s
3251:	learn: 0.0035181	total: 5m 33s	remaining: 11m 31s
3300:	learn: 0.0032530	total: 5m 33s	remaining: 11m 16s
3022:	learn: 0.0036769	total: 5m 33s	remaining: 12m 49s
3246:	learn: 0.0029326	total: 5m 33s	remaining: 11m 33s
3160:	learn: 0.0036039	total: 5m 33s	remaining: 12m 1s
3252:	learn: 0.0035173	total: 5m 33s	remaining: 11m 31s
3301:	learn: 0.0032510	total: 5m 33s	remaining: 11m 16s
3161:	learn: 0.0036028	total: 5m 33s	remaining: 12m 1s
3023:	learn: 0.0036742	total: 5m 33s	remaining: 12m 49s
3247:	learn: 0.0029318	total: 5m 33s	remaining: 11m 33s
3302:	learn: 0.0032489	total: 5m 33s	remaining: 11m 16s
3253:	learn: 0.0035159	total: 5m 33s	remaining: 11m 31s
3162:	learn: 0.0036020	total: 5m 33s	remaining: 12m 1s
3248:	learn: 0.0029295	total: 5m 33s	remaining: 11m 33s
3303:	learn: 0.0032467	total: 5m 33s	remaining: 11m 16s
3024:	learn: 0.0036735	total: 5m 33s	remaining: 12m 49s
3254:	learn: 0.0035150	total: 5m 33s	remaining: 11m 31s
3163:	learn: 0.0035997	total: 5m 33s	remaining: 12m 1s
3304:	learn: 0.0032447	total: 5m 33s	remaining: 11m 16s
3249:	learn: 0.0029291	total: 5m 33s	remaining: 11m 33s
3255:	learn: 0.0035134	total: 5m 33s	remaining: 11m 31s
3025:	learn: 0.0036730	total: 5m 33s	remaining: 12m 49s
3256:	learn: 0.0035120	total: 5m 33s	remaining: 11m 30s
3164:	learn: 0.0035982	total: 5m 33s	remaining: 12m 1s
3305:	learn: 0.0032435	total: 5m 33s	remaining: 11m 16s
3250:	learn: 0.0029280	total: 5m 33s	remaining: 11m 33s
3026:	learn: 0.0036704	total: 5m 33s	remaining: 12m 49s
3257:	learn: 0.0035103	total: 5m 33s	remaining: 11m 30s
3306:	learn: 0.0032420	total: 5m 34s	remaining: 11m 16s
3165:	learn: 0.0035968	total: 5m 33s	remaining: 12m
3251:	learn: 0.0029267	total: 5m 34s	remaining: 11m 33s
3027:	learn: 0.0036680	total: 5m 34s	remaining: 12m 49s
3258:	learn: 0.0035083	total: 5m 33s	remaining: 11m 30s
3166:	learn: 0.0035950	total: 5m 34s	remaining: 12m
3307:	learn: 0.0032399	total: 5m 34s	remaining: 11m 15s
3028:	learn: 0.0036658	total: 5m 34s	remaining: 12m 49s
3252:	learn: 0.0029255	total: 5m 34s	remaining: 11m 33s
3259:	learn: 0.0035071	total: 5m 34s	remaining: 11m 30s
3167:	learn: 0.0035936	total: 5m 34s	remaining: 12m
0038311	total: 5m 25s	remaining: 12m 59s
:	learn: 0.00443308:	learn: 0.0032382	total: 5m 34s	remaining: 11m 15s
3029:	learn: 0.0036650	total: 5m 34s	remaining: 12m 48s
3253:	learn: 0.0029238	total: 5m 34s	remaining: 11m 32s
3260:	learn: 0.0035059	total: 5m 34s	remaining: 11m 30s
3168:	learn: 0.0035927	total: 5m 34s	remaining: 12m
3309:	learn: 0.0032361	total: 5m 34s	remaining: 11m 15s
3261:	learn: 0.0035044	total: 5m 34s	remaining: 11m 30s
3254:	learn: 0.0029225	total: 5m 34s	remaining: 11m 32s
3030:	learn: 0.0036624	total: 5m 34s	remaining: 12m 48s
3169:	learn: 0.0035912	total: 5m 34s	remaining: 12m
3310:	learn: 0.0032344	total: 5m 34s	remaining: 11m 15s
3262:	learn: 0.0035031	total: 5m 34s	remaining: 11m 30s
3255:	learn: 0.0029213	total: 5m 34s	remaining: 11m 32s
3170:	learn: 0.0035891	total: 5m 34s	remaining: 12m
3031:	learn: 0.0036608	total: 5m 34s	remaining: 12m 48s
3311:	learn: 0.0032320	total: 5m 34s	remaining: 11m 15s
3263:	learn: 0.0035023	total: 5m 34s	remaining: 11m 30s
3171:	learn: 0.0035878	total: 5m 34s	remaining: 12m
3312:	learn: 0.0032300	total: 5m 34s	remaining: 11m 15s
3256:	learn: 0.0029195	total: 5m 34s	remaining: 11m 32s
3032:	learn: 0.0036590	total: 5m 34s	remaining: 12m 48s
3264:	learn: 0.0035004	total: 5m 34s	remaining: 11m 29s
3313:	learn: 0.0032285	total: 5m 34s	remaining: 11m 15s
3257:	learn: 0.0029182	total: 5m 34s	remaining: 11m 32s
3172:	learn: 0.0035860	total: 5m 34s	remaining: 12m
3033:	learn: 0.0036562	total: 5m 34s	remaining: 12m 48s
3314:	learn: 0.0032265	total: 5m 34s	remaining: 11m 15s
3265:	learn: 0.0034991	total: 5m 34s	remaining: 11m 29s
3258:	learn: 0.0029169	total: 5m 34s	remaining: 11m 32s
3173:	learn: 0.0035840	total: 5m 34s	remaining: 11m 59s
3034:	learn: 0.0036546	total: 5m 34s	remaining: 12m 48s
3266:	learn: 0.0034978	total: 5m 34s	remaining: 11m 29s
3315:	learn: 0.0032254	total: 5m 34s	remaining: 11m 15s
3035:	learn: 0.0036524	total: 5m 34s	remaining: 12m 48s
3174:	learn: 0.0035824	total: 5m 34s	remaining: 11m 59s
3259:	learn: 0.0029157	total: 5m 34s	remaining: 11m 32s
3316:	learn: 0.0032243	total: 5m 35s	remaining: 11m 14s
3267:	learn: 0.0034970	total: 5m 34s	remaining: 11m 29s
3036:	learn: 0.0036496	total: 5m 35s	remaining: 12m 48s
3260:	learn: 0.0029144	total: 5m 34s	remaining: 11m 32s
3175:	learn: 0.0035806	total: 5m 34s	remaining: 11m 59s
3317:	learn: 0.0032226	total: 5m 35s	remaining: 11m 14s
3268:	learn: 0.0034958	total: 5m 34s	remaining: 11m 29s
3037:	learn: 0.0036481	total: 5m 35s	remaining: 12m 47s
3261:	learn: 0.0029132	total: 5m 35s	remaining: 11m 32s
3176:	learn: 0.0035786	total: 5m 35s	remaining: 11m 59s
3318:	learn: 0.0032205	total: 5m 35s	remaining: 11m 14s
3177:	learn: 0.0035764	total: 5m 35s	remaining: 11m 59s
3269:	learn: 0.0034948	total: 5m 35s	remaining: 11m 29s
3038:	learn: 0.0036467	total: 5m 35s	remaining: 12m 47s
3262:	learn: 0.0029125	total: 5m 35s	remaining: 11m 32s
3319:	learn: 0.0032186	total: 5m 35s	remaining: 11m 14s
3178:	learn: 0.0035748	total: 5m 35s	remaining: 11m 59s
3270:	learn: 0.0034927	total: 5m 35s	remaining: 11m 29s
3039:	learn: 0.0036440	total: 5m 35s	remaining: 12m 47s
3263:	learn: 0.0029112	total: 5m 35s	remaining: 11m 32s
3320:	learn: 0.0032175	total: 5m 35s	remaining: 11m 14s
3179:	learn: 0.0035737	total: 5m 35s	remaining: 11m 59s
3040:	learn: 0.0036427	total: 5m 35s	remaining: 12m 47s
3271:	learn: 0.0034912	total: 5m 35s	remaining: 11m 29s
3264:	learn: 0.0029096	total: 5m 35s	remaining: 11m 31s
3321:	learn: 0.0032161	total: 5m 35s	remaining: 11m 14s
3041:	learn: 0.0036408	total: 5m 35s	remaining: 12m 47s
3272:	learn: 0.0034892	total: 5m 35s	remaining: 11m 29s
3180:	learn: 0.0035713	total: 5m 35s	remaining: 11m 59s
3265:	learn: 0.0029084	total: 5m 35s	remaining: 11m 31s
3273:	learn: 0.0034881	total: 5m 35s	remaining: 11m 29s
3322:	learn: 0.0032148	total: 5m 35s	remaining: 11m 14s
3042:	learn: 0.0036383	total: 5m 35s	remaining: 12m 47s
3181:	learn: 0.0035700	total: 5m 35s	remaining: 11m 59s
3266:	learn: 0.0029068	total: 5m 35s	remaining: 11m 31s
3274:	learn: 0.0034861	total: 5m 35s	remaining: 11m 28s
3043:	learn: 0.0036359	total: 5m 35s	remaining: 12m 47s
3323:	learn: 0.0032129	total: 5m 35s	remaining: 11m 14s
3267:	learn: 0.0029051	total: 5m 35s	remaining: 11m 31s
3182:	learn: 0.0035683	total: 5m 35s	remaining: 11m 58s
3044:	learn: 0.0036334	total: 5m 35s	remaining: 12m 46s
3275:	learn: 0.0034844	total: 5m 35s	remaining: 11m 28s
3324:	learn: 0.0032105	total: 5m 35s	remaining: 11m 14s
3268:	learn: 0.0029039	total: 5m 35s	remaining: 11m 31s
3183:	learn: 0.0035673	total: 5m 35s	remaining: 11m 58s
3045:	learn: 0.0036330	total: 5m 35s	remaining: 12m 46s
3276:	learn: 0.0034826	total: 5m 35s	remaining: 11m 28s
3325:	learn: 0.0032091	total: 5m 35s	remaining: 11m 14s
3184:	learn: 0.0035649	total: 5m 35s	remaining: 11m 58s
3269:	learn: 0.0029027	total: 5m 35s	remaining: 11m 31s
3046:	learn: 0.0036310	total: 5m 35s	remaining: 12m 46s
3326:	learn: 0.0032073	total: 5m 36s	remaining: 11m 13s
3277:	learn: 0.0034800	total: 5m 35s	remaining: 11m 28s
3270:	learn: 0.0029011	total: 5m 36s	remaining: 11m 31s
3185:	learn: 0.0035640	total: 5m 36s	remaining: 11m 58s
3047:	learn: 0.0036291	total: 5m 36s	remaining: 12m 46s
3327:	learn: 0.0032062	total: 5m 36s	remaining: 11m 13s
3278:	learn: 0.0034781	total: 5m 35s	remaining: 11m 28s
3271:	learn: 0.0028994	total: 5m 36s	remaining: 11m 31s
3186:	learn: 0.0035627	total: 5m 36s	remaining: 11m 58s
3048:	learn: 0.0036268	total: 5m 36s	remaining: 12m 46s
3279:	learn: 0.0034764	total: 5m 36s	remaining: 11m 28s
3328:	learn: 0.0032041	total: 5m 36s	remaining: 11m 13s
3187:	learn: 0.0035606	total: 5m 36s	remaining: 11m 58s
3272:	learn: 0.0028968	total: 5m 36s	remaining: 11m 30s
3049:	learn: 0.0036261	total: 5m 36s	remaining: 12m 46s
3329:	learn: 0.0032034	total: 5m 36s	remaining: 11m 13s
3280:	learn: 0.0034752	total: 5m 36s	remaining: 11m 28s
3188:	learn: 0.0035591	total: 5m 36s	remaining: 11m 58s
3273:	learn: 0.0028949	total: 5m 36s	remaining: 11m 30s
3330:	learn: 0.0032019	total: 5m 36s	remaining: 11m 13s
3050:	learn: 0.0036238	total: 5m 36s	remaining: 12m 46s
3281:	learn: 0.0034741	total: 5m 36s	remaining: 11m 28s
3274:	learn: 0.0028937	total: 5m 36s	remaining: 11m 30s
3189:	learn: 0.0035572	total: 5m 36s	remaining: 11m 58s
3051:	learn: 0.0036221	total: 5m 36s	remaining: 12m 45s
3331:	learn: 0.0032005	total: 5m 36s	remaining: 11m 13s
3282:	learn: 0.0034731	total: 5m 36s	remaining: 11m 28s
3190:	learn: 0.0035548	total: 5m 36s	remaining: 11m 58s
3275:	learn: 0.0028920	total: 5m 36s	remaining: 11m 30s
3332:	learn: 0.0031994	total: 5m 36s	remaining: 11m 13s
3052:	learn: 0.0036206	total: 5m 36s	remaining: 12m 45s
3283:	learn: 0.0034709	total: 5m 36s	remaining: 11m 28s
3276:	learn: 0.0028907	total: 5m 36s	remaining: 11m 30s
3333:	learn: 0.0031977	total: 5m 36s	remaining: 11m 13s
3191:	learn: 0.0035533	total: 5m 36s	remaining: 11m 57s
3053:	learn: 0.0036192	total: 5m 36s	remaining: 12m 45s
3334:	learn: 0.0031960	total: 5m 36s	remaining: 11m 12s
3277:	learn: 0.0028890	total: 5m 36s	remaining: 11m 30s
3284:	learn: 0.0034689	total: 5m 36s	remaining: 11m 27s
3192:	learn: 0.0035516	total: 5m 36s	remaining: 11m 57s
3278:	learn: 0.0028873	total: 5m 36s	remaining: 11m 30s
3285:	learn: 0.0034670	total: 5m 36s	remaining: 11m 27s
3054:	learn: 0.0036185	total: 5m 36s	remaining: 12m 45s
3335:	learn: 0.0031941	total: 5m 36s	remaining: 11m 12s
3193:	learn: 0.0035494	total: 5m 36s	remaining: 11m 57s
3055:	learn: 0.0036171	total: 5m 36s	remaining: 12m 45s
3279:	learn: 0.0028856	total: 5m 36s	remaining: 11m 30s
3286:	learn: 0.0034662	total: 5m 36s	remaining: 11m 27s
3336:	learn: 0.0031929	total: 5m 36s	remaining: 11m 12s
3194:	learn: 0.0035477	total: 5m 36s	remaining: 11m 57s
3056:	learn: 0.0036145	total: 5m 36s	remaining: 12m 45s
3287:	learn: 0.0034639	total: 5m 36s	remaining: 11m 27s
3280:	learn: 0.0028840	total: 5m 36s	remaining: 11m 30s
3337:	learn: 0.0031908	total: 5m 37s	remaining: 11m 12s
3195:	learn: 0.0035458	total: 5m 37s	remaining: 11m 57s
3057:	learn: 0.0036134	total: 5m 37s	remaining: 12m 45s
3281:	learn: 0.0028822	total: 5m 37s	remaining: 11m 29s
3338:	learn: 0.0031888	total: 5m 37s	remaining: 11m 12s
3288:	learn: 0.0034626	total: 5m 36s	remaining: 11m 27s

3196:	learn: 0.0035441	total: 5m 37s	remaining: 11m 57s
3058:	learn: 0.0036121	total: 5m 37s	remaining: 12m 45s
3339:	learn: 0.0031878	total: 5m 37s	remaining: 11m 12s
3282:	learn: 0.0028809	total: 5m 37s	remaining: 11m 29s
3289:	learn: 0.0034606	total: 5m 37s	remaining: 11m 27s
3197:	learn: 0.0035428	total: 5m 37s	remaining: 11m 57s
3059:	learn: 0.0036097	total: 5m 37s	remaining: 12m 44s
3283:	learn: 0.0028794	total: 5m 37s	remaining: 11m 29s
3340:	learn: 0.0031858	total: 5m 37s	remaining: 11m 12s
3290:	learn: 0.0034589	total: 5m 37s	remaining: 11m 27s
3060:	learn: 0.0036075	total: 5m 37s	remaining: 12m 44s
3198:	learn: 0.0035416	total: 5m 37s	remaining: 11m 57s
3341:	learn: 0.0031841	total: 5m 37s	remaining: 11m 12s
3284:	learn: 0.0028782	total: 5m 37s	remaining: 11m 29s
3291:	learn: 0.0034575	total: 5m 37s	remaining: 11m 27s
3199:	learn: 0.0035401	total: 5m 37s	remaining: 11m 57s
3061:	learn: 0.0036067	total: 5m 37s	remaining: 12m 44s
3342:	learn: 0.0031827	total: 5m 37s	remaining: 11m 12s
3285:	learn: 0.0028770	total: 5m 37s	remaining: 11m 29s
3200:	learn: 0.0035383	total: 5m 37s	remaining: 11m 56s
3062:	learn: 0.0036040	total: 5m 37s	remaining: 12m 44s
3292:	learn: 0.0034556	total: 5m 37s	remaining: 11m 27s
3343:	learn: 0.0031813	total: 5m 37s	remaining: 11m 11s
3286:	learn: 0.0028752	total: 5m 37s	remaining: 11m 29s
3344:	learn: 0.0031796	total: 5m 37s	remaining: 11m 11s
3201:	learn: 0.0035369	total: 5m 37s	remaining: 11m 56s
3293:	learn: 0.0034536	total: 5m 37s	remaining: 11m 27s
3063:	learn: 0.0036021	total: 5m 37s	remaining: 12m 44s
3345:	learn: 0.0031781	total: 5m 37s	remaining: 11m 11s
3287:	learn: 0.0028740	total: 5m 37s	remaining: 11m 29s
3294:	learn: 0.0034516	total: 5m 37s	remaining: 11m 26s
3064:	learn: 0.0035995	total: 5m 37s	remaining: 12m 44s
3202:	learn: 0.0035353	total: 5m 37s	remaining: 11m 56s
3346:	learn: 0.0031768	total: 5m 37s	remaining: 11m 11s
3288:	learn: 0.0028725	total: 5m 37s	remaining: 11m 29s
3295:	learn: 0.0034505	total: 5m 37s	remaining: 11m 26s
3065:	learn: 0.0035971	total: 5m 37s	remaining: 12m 44s
3203:	learn: 0.0035337	total: 5m 37s	remaining: 11m 56s
3347:	learn: 0.0031757	total: 5m 37s	remaining: 11m 11s
3296:	learn: 0.0034494	total: 5m 37s	remaining: 11m 26s
3289:	learn: 0.0028714	total: 5m 37s	remaining: 11m 29s
3204:	learn: 0.0035317	total: 5m 37s	remaining: 11m 56s
3066:	learn: 0.0035958	total: 5m 38s	remaining: 12m 44s
3348:	learn: 0.0031736	total: 5m 38s	remaining: 11m 11s
3297:	learn: 0.0034483	total: 5m 37s	remaining: 11m 26s
3290:	learn: 0.0028697	total: 5m 38s	remaining: 11m 29s
3067:	learn: 0.0035930	total: 5m 38s	remaining: 12m 43s
3205:	learn: 0.0035284	total: 5m 38s	remaining: 11m 56s
3298:	learn: 0.0034465	total: 5m 37s	remaining: 11m 26s
3349:	learn: 0.0031720	total: 5m 38s	remaining: 11m 11s
3291:	learn: 0.0028686	total: 5m 38s	remaining: 11m 29s
3068:	learn: 0.0035906	total: 5m 38s	remaining: 12m 43s
3206:	learn: 0.0035270	total: 5m 38s	remaining: 11m 56s
3299:	learn: 0.0034449	total: 5m 38s	remaining: 11m 26s
3350:	learn: 0.0031705	total: 5m 38s	remaining: 11m 11s
3292:	learn: 0.0028672	total: 5m 38s	remaining: 11m 28s
3069:	learn: 0.0035892	total: 5m 38s	remaining: 12m 43s
3207:	learn: 0.0035263	total: 5m 38s	remaining: 11m 56s
3300:	learn: 0.0034431	total: 5m 38s	remaining: 11m 26s
3293:	learn: 0.0028660	total: 5m 38s	remaining: 11m 28s
3351:	learn: 0.0031690	total: 5m 38s	remaining: 11m 11s
3070:	learn: 0.0035877	total: 5m 38s	remaining: 12m 43s
3301:	learn: 0.0034416	total: 5m 38s	remaining: 11m 26s
3208:	learn: 0.0035246	total: 5m 38s	remaining: 11m 56s
3294:	learn: 0.0028647	total: 5m 38s	remaining: 11m 28s
3352:	learn: 0.0031665	total: 5m 38s	remaining: 11m 10s
3302:	learn: 0.0034399	total: 5m 38s	remaining: 11m 26s
3353:	learn: 0.0031652	total: 5m 38s	remaining: 11m 10s
3071:	learn: 0.0035870	total: 5m 38s	remaining: 12m 43s
3295:	learn: 0.0028634	total: 5m 38s	remaining: 11m 28s
3209:	learn: 0.0035230	total: 5m 38s	remaining: 11m 56s
3303:	learn: 0.0034379	total: 5m 38s	remaining: 11m 25s
3354:	learn: 0.0031637	total: 5m 38s	remaining: 11m 10s
3072:	learn: 0.0035855	total: 5m 38s	remaining: 12m 43s
3210:	learn: 0.0035212	total: 5m 38s	remaining: 11m 55s
3296:	learn: 0.0028622	total: 5m 38s	remaining: 11m 28s
3304:	learn: 0.0034360	total: 5m 38s	remaining: 11m 25s
3355:	learn: 0.0031623	total: 5m 38s	remaining: 11m 10s
3073:	learn: 0.0035842	total: 5m 38s	remaining: 12m 43s
3211:	learn: 0.0035199	total: 5m 38s	remaining: 11m 55s
3297:	learn: 0.0028606	total: 5m 38s	remaining: 11m 28s
3305:	learn: 0.0034346	total: 5m 38s	remaining: 11m 25s
3356:	learn: 0.0031616	total: 5m 38s	remaining: 11m 10s
3074:	learn: 0.0035836	total: 5m 38s	remaining: 12m 43s
3212:	learn: 0.0035182	total: 5m 38s	remaining: 11m 55s
3298:	learn: 0.0028594	total: 5m 38s	remaining: 11m 28s
3306:	learn: 0.0034327	total: 5m 38s	remaining: 11m 25s
3357:	learn: 0.0031600	total: 5m 38s	remaining: 11m 10s
3075:	learn: 0.0035813	total: 5m 38s	remaining: 12m 43s
3213:	learn: 0.0035167	total: 5m 38s	remaining: 11m 55s
3299:	learn: 0.0028585	total: 5m 38s	remaining: 11m 28s
3307:	learn: 0.0034310	total: 5m 38s	remaining: 11m 25s
3358:	learn: 0.0031583	total: 5m 39s	remaining: 11m 10s
3076:	learn: 0.0035801	total: 5m 39s	remaining: 12m 42s
3214:	learn: 0.0035154	total: 5m 39s	remaining: 11m 55s
3300:	learn: 0.0028569	total: 5m 39s	remaining: 11m 28s
3308:	learn: 0.0034302	total: 5m 38s	remaining: 11m 25s
3359:	learn: 0.0031568	total: 5m 39s	remaining: 11m 10s
3077:	learn: 0.0035789	total: 5m 39s	remaining: 12m 42s
3309:	learn: 0.0034281	total: 5m 39s	remaining: 11m 25s
3215:	learn: 0.0035137	total: 5m 39s	remaining: 11m 55s
3301:	learn: 0.0028557	total: 5m 39s	remaining: 11m 28s
3360:	learn: 0.0031554	total: 5m 39s	remaining: 11m 10s
3078:	learn: 0.0035770	total: 5m 39s	remaining: 12m 42s
3216:	learn: 0.0035124	total: 5m 39s	remaining: 11m 55s
3310:	learn: 0.0034264	total: 5m 39s	remaining: 11m 25s
3302:	learn: 0.0028543	total: 5m 39s	remaining: 11m 27s
3079:	learn: 0.0035755	total: 5m 39s	remaining: 12m 42s
3361:	learn: 0.0031536	total: 5m 39s	remaining: 11m 10s
3303:	learn: 0.0028527	total: 5m 39s	remaining: 11m 27s
3311:	learn: 0.0034246	total: 5m 39s	remaining: 11m 25s
3217:	learn: 0.0035109	total: 5m 39s	remaining: 11m 55s
3080:	learn: 0.0035731	total: 5m 39s	remaining: 12m 42s
3362:	learn: 0.0031521	total: 5m 39s	remaining: 11m 9s
3312:	learn: 0.0034232	total: 5m 39s	remaining: 11m 24s
3304:	learn: 0.0028512	total: 5m 39s	remaining: 11m 27s
3218:	learn: 0.0035097	total: 5m 39s	remaining: 11m 55s
3081:	learn: 0.0035715	total: 5m 39s	remaining: 12m 42s
3363:	learn: 0.0031502	total: 5m 39s	remaining: 11m 9s
3305:	learn: 0.0028497	total: 5m 39s	remaining: 11m 27s
3313:	learn: 0.0034207	total: 5m 39s	remaining: 11m 24s
3219:	learn: 0.0035083	total: 5m 39s	remaining: 11m 55s
3082:	learn: 0.0035692	total: 5m 39s	remaining: 12m 42s
3314:	learn: 0.0034192	total: 5m 39s	remaining: 11m 24s
3364:	learn: 0.0031493	total: 5m 39s	remaining: 11m 9s
3306:	learn: 0.0028485	total: 5m 39s	remaining: 11m 27s
3220:	learn: 0.0035068	total: 5m 39s	remaining: 11m 54s
3365:	learn: 0.0031484	total: 5m 39s	remaining: 11m 9s
3315:	learn: 0.0034169	total: 5m 39s	remaining: 11m 24s
3083:	learn: 0.0035675	total: 5m 39s	remaining: 12m 41s
3307:	learn: 0.0028469	total: 5m 39s	remaining: 11m 27s
3366:	learn: 0.0031463	total: 5m 39s	remaining: 11m 9s
3221:	learn: 0.0035053	total: 5m 39s	remaining: 11m 54s
3084:	learn: 0.0035663	total: 5m 39s	remaining: 12m 41s
3316:	learn: 0.0034153	total: 5m 39s	remaining: 11m 24s
3308:	learn: 0.0028449	total: 5m 39s	remaining: 11m 27s
3367:	learn: 0.0031451	total: 5m 39s	remaining: 11m 9s
3222:	learn: 0.0035039	total: 5m 39s	remaining: 11m 54s
3317:	learn: 0.0034137	total: 5m 39s	remaining: 11m 24s
3368:	learn: 0.0031439	total: 5m 40s	remaining: 11m 9s
3309:	learn: 0.0028433	total: 5m 39s	remaining: 11m 27s
3085:	learn: 0.0035647	total: 5m 40s	remaining: 12m 41s
3318:	learn: 0.0034112	total: 5m 39s	remaining: 11m 24s
3223:	learn: 0.0035025	total: 5m 40s	remaining: 11m 54s
3369:	learn: 0.0031422	total: 5m 40s	remaining: 11m 9s
3310:	learn: 0.0028420	total: 5m 40s	remaining: 11m 27s
3086:	learn: 0.0035633	total: 5m 40s	remaining: 12m 41s
3319:	learn: 0.0034102	total: 5m 39s	remaining: 11m 24s
3224:	learn: 0.0035008	total: 5m 40s	remaining: 11m 54s
3370:	learn: 0.0031410	total: 5m 40s	remaining: 11m 9s
3311:	learn: 0.0028401	total: 5m 40s	remaining: 11m 26s
3320:	learn: 0.0034092	total: 5m 40s	remaining: 11m 23s
3087:	learn: 0.0035613	total: 5m 40s	remaining: 12m 41s
3225:	learn: 0.0034993	total: 5m 40s	remaining: 11m 54s
3312:	learn: 0.0028387	total: 5m 40s	remaining: 11m 26s
3371:	learn: 0.0031398	total: 5m 40s	remaining: 11m 8s
3321:	learn: 0.0034072	total: 5m 40s	remaining: 11m 23s
3226:	learn: 0.0034978	total: 5m 40s	remaining: 11m 54s
3313:	learn: 0.0028376	total: 5m 40s	remaining: 11m 26s
3372:	learn: 0.0031381	total: 5m 40s	remaining: 11m 8s
3088:	learn: 0.0035598	total: 5m 40s	remaining: 12m 41s
3322:	learn: 0.0034059	total: 5m 40s	remaining: 11m 23s
3227:	learn: 0.0034960	total: 5m 40s	remaining: 11m 54s
3314:	learn: 0.0028366	total: 5m 40s	remaining: 11m 26s
3373:	learn: 0.0031363	total: 5m 40s	remaining: 11m 8s
3089:	learn: 0.0035585	total: 5m 40s	remaining: 12m 41s
3323:	learn: 0.0034050	total: 5m 40s	remaining: 11m 23s
3228:	learn: 0.0034939	total: 5m 40s	remaining: 11m 54s
3315:	learn: 0.0028355	total: 5m 40s	remaining: 11m 26s
3374:	learn: 0.0031357	total: 5m 40s	remaining: 11m 8s
3324:	learn: 0.0034032	total: 5m 40s	remaining: 11m 23s
3090:	learn: 0.0035571	total: 5m 40s	remaining: 12m 41s
3229:	learn: 0.0034928	total: 5m 40s	remaining: 11m 53s
3316:	learn: 0.0028341	total: 5m 40s	remaining: 11m 26s
3325:	learn: 0.0034012	total: 5m 40s	remaining: 11m 23s
3375:	learn: 0.0031344	total: 5m 40s	remaining: 11m 8s
3091:	learn: 0.0035557	total: 5m 40s	remaining: 12m 41s
3230:	learn: 0.0034908	total: 5m 40s	remaining: 11m 53s
3317:	learn: 0.0028333	total: 5m 40s	remaining: 11m 26s
3326:	learn: 0.0033997	total: 5m 40s	remaining: 11m 23s
3376:	learn: 0.0031328	total: 5m 40s	remaining: 11m 8s
3231:	learn: 0.0034891	total: 5m 40s	remaining: 11m 53s
3092:	learn: 0.0035544	total: 5m 40s	remaining: 12m 41s
3318:	learn: 0.0028317	total: 5m 40s	remaining: 11m 26s
3327:	learn: 0.0033988	total: 5m 40s	remaining: 11m 23s
3377:	learn: 0.0031318	total: 5m 40s	remaining: 11m 8s
3232:	learn: 0.0034883	total: 5m 40s	remaining: 11m 53s
3319:	learn: 0.0028302	total: 5m 40s	remaining: 11m 25s
3093:	learn: 0.0035531	total: 5m 40s	remaining: 12m 41s
3328:	learn: 0.0033979	total: 5m 40s	remaining: 11m 22s
3233:	learn: 0.0034869	total: 5m 40s	remaining: 11m 53s
3378:	learn: 0.0031307	total: 5m 41s	remaining: 11m 8s
3320:	learn: 0.0028287	total: 5m 41s	remaining: 11m 25s
3329:	learn: 0.0033964	total: 5m 40s	remaining: 11m 22s
3379:	learn: 0.0031293	total: 5m 41s	remaining: 11m 8s
3094:	learn: 0.0035513	total: 5m 41s	remaining: 12m 41s
3234:	learn: 0.0034849	total: 5m 41s	remaining: 11m 53s
3321:	learn: 0.0028271	total: 5m 41s	remaining: 11m 25s
3330:	learn: 0.0033953	total: 5m 41s	remaining: 11m 22s
3235:	learn: 0.0034841	total: 5m 41s	remaining: 11m 53s
3380:	learn: 0.0031273	total: 5m 41s	remaining: 11m 8s
3095:	learn: 0.0035488	total: 5m 41s	remaining: 12m 40s
3322:	learn: 0.0028259	total: 5m 41s	remaining: 11m 25s
3331:	learn: 0.0033934	total: 5m 41s	remaining: 11m 22s
3236:	learn: 0.0034829	total: 5m 41s	remaining: 11m 53s
3381:	learn: 0.0031256	total: 5m 41s	remaining: 11m 7s
3323:	learn: 0.0028245	total: 5m 41s	remaining: 11m 25s
3096:	learn: 0.0035470	total: 5m 41s	remaining: 12m 40s
3332:	learn: 0.0033916	total: 5m 41s	remaining: 11m 22s
3237:	learn: 0.0034812	total: 5m 41s	remaining: 11m 52s
3382:	learn: 0.0031248	total: 5m 41s	remaining: 11m 7s
3324:	learn: 0.0028231	total: 5m 41s	remaining: 11m 25s
3097:	learn: 0.0035457	total: 5m 41s	remaining: 12m 40s
3333:	learn: 0.0033905	total: 5m 41s	remaining: 11m 22s
3238:	learn: 0.0034795	total: 5m 41s	remaining: 11m 52s
3383:	learn: 0.0031231	total: 5m 41s	remaining: 11m 7s
3334:	learn: 0.0033889	total: 5m 41s	remaining: 11m 22s
3325:	learn: 0.0028219	total: 5m 41s	remaining: 11m 25s
3098:	learn: 0.0035442	total: 5m 41s	remaining: 12m 40s
3239:	learn: 0.0034781	total: 5m 41s	remaining: 11m 52s
3384:	learn: 0.0031217	total: 5m 41s	remaining: 11m 7s
3326:	learn: 0.0028206	total: 5m 41s	remaining: 11m 25s
3335:	learn: 0.0033878	total: 5m 41s	remaining: 11m 22s
3099:	learn: 0.0035429	total: 5m 41s	remaining: 12m 40s
3240:	learn: 0.0034766	total: 5m 41s	remaining: 11m 52s
3385:	learn: 0.0031200	total: 5m 41s	remaining: 11m 7s
3327:	learn: 0.0028195	total: 5m 41s	remaining: 11m 25s
3336:	learn: 0.0033868	total: 5m 41s	remaining: 11m 22s
3241:	learn: 0.0034746	total: 5m 41s	remaining: 11m 52s
3100:	learn: 0.0035414	total: 5m 41s	remaining: 12m 40s
3386:	learn: 0.0031183	total: 5m 41s	remaining: 11m 7s
3337:	learn: 0.0033853	total: 5m 41s	remaining: 11m 21s
3328:	learn: 0.0028178	total: 5m 41s	remaining: 11m 25s
3242:	learn: 0.0034723	total: 5m 41s	remaining: 11m 52s
3387:	learn: 0.0031177	total: 5m 41s	remaining: 11m 7s
3101:	learn: 0.0035391	total: 5m 41s	remaining: 12m 40s
3338:	learn: 0.0033833	total: 5m 41s	remaining: 11m 21s
3243:	learn: 0.0034707	total: 5m 41s	remaining: 11m 52s
3329:	learn: 0.0028162	total: 5m 41s	remaining: 11m 24s
3388:	learn: 0.0031170	total: 5m 42s	remaining: 11m 7s
3102:	learn: 0.0035385	total: 5m 42s	remaining: 12m 40s
3244:	learn: 0.0034687	total: 5m 41s	remaining: 11m 51s
3339:	learn: 0.0033817	total: 5m 41s	remaining: 11m 21s
3389:	learn: 0.0031152	total: 5m 42s	remaining: 11m 7s
3330:	learn: 0.0028146	total: 5m 42s	remaining: 11m 24s
3103:	learn: 0.0035373	total: 5m 42s	remaining: 12m 40s
3245:	learn: 0.0034672	total: 5m 42s	remaining: 11m 51s
3331:	learn: 0.0028130	total: 5m 42s	remaining: 11m 24s
3340:	learn: 0.0033805	total: 5m 42s	remaining: 11m 21s
3104:	learn: 0.0035360	total: 5m 42s	remaining: 12m 39s
3390:	learn: 0.0031146	total: 5m 42s	remaining: 11m 6s
3332:	learn: 0.0028120	total: 5m 42s	remaining: 11m 24s
3246:	learn: 0.0034656	total: 5m 42s	remaining: 11m 51s
3341:	learn: 0.0033787	total: 5m 42s	remaining: 11m 21s
3105:	learn: 0.0035348	total: 5m 42s	remaining: 12m 39s
3391:	learn: 0.0031140	total: 5m 42s	remaining: 11m 6s
3333:	learn: 0.0028106	total: 5m 42s	remaining: 11m 24s
3247:	learn: 0.0034644	total: 5m 42s	remaining: 11m 51s
3392:	learn: 0.0031126	total: 5m 42s	remaining: 11m 6s
3342:	learn: 0.0033777	total: 5m 42s	remaining: 11m 21s
3106:	learn: 0.0035328	total: 5m 42s	remaining: 12m 39s
3334:	learn: 0.0028096	total: 5m 42s	remaining: 11m 24s
3248:	learn: 0.0034630	total: 5m 42s	remaining: 11m 51s
3393:	learn: 0.0031120	total: 5m 42s	remaining: 11m 6s
3107:	learn: 0.0035311	total: 5m 42s	remaining: 12m 39s
3343:	learn: 0.0033770	total: 5m 42s	remaining: 11m 21s
3394:	learn: 0.0031112	total: 5m 42s	remaining: 11m 6s
3249:	learn: 0.0034614	total: 5m 42s	remaining: 11m 51s
3335:	learn: 0.0028081	total: 5m 42s	remaining: 11m 24s
3108:	learn: 0.0035289	total: 5m 42s	remaining: 12m 39s
3344:	learn: 0.0033752	total: 5m 42s	remaining: 11m 21s
3395:	learn: 0.0031098	total: 5m 42s	remaining: 11m 6s
3250:	learn: 0.0034595	total: 5m 42s	remaining: 11m 51s
3336:	learn: 0.0028070	total: 5m 42s	remaining: 11m 24s
3109:	learn: 0.0035274	total: 5m 42s	remaining: 12m 39s
3345:	learn: 0.0033740	total: 5m 42s	remaining: 11m 21s
3396:	learn: 0.0031092	total: 5m 42s	remaining: 11m 6s
3337:	learn: 0.0028059	total: 5m 42s	remaining: 11m 24s
3251:	learn: 0.0034581	total: 5m 42s	remaining: 11m 51s
3346:	learn: 0.0033724	total: 5m 42s	remaining: 11m 21s
3110:	learn: 0.0035263	total: 5m 42s	remaining: 12m 39s
3397:	learn: 0.0031086	total: 5m 42s	remaining: 11m 6s
3338:	learn: 0.0028040	total: 5m 42s	remaining: 11m 23s
3252:	learn: 0.0034565	total: 5m 42s	remaining: 11m 51s
3347:	learn: 0.0033713	total: 5m 42s	remaining: 11m 20s
3111:	learn: 0.0035240	total: 5m 42s	remaining: 12m 39s
3398:	learn: 0.0031070	total: 5m 42s	remaining: 11m 5s
3339:	learn: 0.0028029	total: 5m 42s	remaining: 11m 23s
3253:	learn: 0.0034549	total: 5m 42s	remaining: 11m 50s
3112:	learn: 0.0035229	total: 5m 43s	remaining: 12m 38s
3348:	learn: 0.0033701	total: 5m 42s	remaining: 11m 20s
3399:	learn: 0.0031054	total: 5m 43s	remaining: 11m 5s

3340:	learn: 0.0028009	total: 5m 43s	remaining: 11m 23s
3113:	learn: 0.0035213	total: 5m 43s	remaining: 12m 38s
3254:	learn: 0.0034542	total: 5m 43s	remaining: 11m 50s
3349:	learn: 0.0033690	total: 5m 42s	remaining: 11m 20s
3400:	learn: 0.0031039	total: 5m 43s	remaining: 11m 5s
3341:	learn: 0.0027999	total: 5m 43s	remaining: 11m 23s
3255:	learn: 0.0034526	total: 5m 43s	remaining: 11m 50s
3350:	learn: 0.0033676	total: 5m 43s	remaining: 11m 20s
3114:	learn: 0.0035190	total: 5m 43s	remaining: 12m 38s
3401:	learn: 0.0031027	total: 5m 43s	remaining: 11m 5s
3342:	learn: 0.0027987	total: 5m 43s	remaining: 11m 23s
3256:	learn: 0.0034518	total: 5m 43s	remaining: 11m 50s
3351:	learn: 0.0033658	total: 5m 43s	remaining: 11m 20s
3402:	learn: 0.0031014	total: 5m 43s	remaining: 11m 5s
3115:	learn: 0.0035174	total: 5m 43s	remaining: 12m 38s
3352:	learn: 0.0033647	total: 5m 43s	remaining: 11m 20s
3257:	learn: 0.0034502	total: 5m 43s	remaining: 11m 50s
3343:	learn: 0.0027974	total: 5m 43s	remaining: 11m 23s
3116:	learn: 0.0035161	total: 5m 43s	remaining: 12m 38s
3403:	learn: 0.0030998	total: 5m 43s	remaining: 11m 5s
3258:	learn: 0.0034487	total: 5m 43s	remaining: 11m 50s
3353:	learn: 0.0033627	total: 5m 43s	remaining: 11m 20s
3344:	learn: 0.0027961	total: 5m 43s	remaining: 11m 23s
3117:	learn: 0.0035141	total: 5m 43s	remaining: 12m 38s
3259:	learn: 0.0034474	total: 5m 43s	remaining: 11m 50s
3404:	learn: 0.0030980	total: 5m 43s	remaining: 11m 5s
3354:	learn: 0.0033609	total: 5m 43s	remaining: 11m 20s
3345:	learn: 0.0027952	total: 5m 43s	remaining: 11m 23s
3405:	learn: 0.0030964	total: 5m 43s	remaining: 11m 5s
3260:	learn: 0.0034460	total: 5m 43s	remaining: 11m 50s
3118:	learn: 0.0035113	total: 5m 43s	remaining: 12m 38s
3355:	learn: 0.0033591	total: 5m 43s	remaining: 11m 20s
3346:	learn: 0.0027941	total: 5m 43s	remaining: 11m 23s
3406:	learn: 0.0030954	total: 5m 43s	remaining: 11m 5s
3356:	learn: 0.0033577	total: 5m 43s	remaining: 11m 19s
3119:	learn: 0.0035107	total: 5m 43s	remaining: 12m 38s
3261:	learn: 0.0034442	total: 5m 43s	remaining: 11m 50s
3347:	learn: 0.0027930	total: 5m 43s	remaining: 11m 23s
3407:	learn: 0.0030938	total: 5m 43s	remaining: 11m 5s
3357:	learn: 0.0033565	total: 5m 43s	remaining: 11m 19s
3262:	learn: 0.0034429	total: 5m 43s	remaining: 11m 49s
3348:	learn: 0.0027915	total: 5m 43s	remaining: 11m 22s
3120:	learn: 0.0035090	total: 5m 43s	remaining: 12m 38s
3408:	learn: 0.0030921	total: 5m 43s	remaining: 11m 4s
3358:	learn: 0.0033547	total: 5m 43s	remaining: 11m 19s
3349:	learn: 0.0027901	total: 5m 43s	remaining: 11m 22s
3263:	learn: 0.0034413	total: 5m 43s	remaining: 11m 49s
3121:	learn: 0.0035068	total: 5m 44s	remaining: 12m 37s
3409:	learn: 0.0030903	total: 5m 44s	remaining: 11m 4s
3359:	learn: 0.0033529	total: 5m 43s	remaining: 11m 19s
3350:	learn: 0.0027890	total: 5m 44s	remaining: 11m 22s
3264:	learn: 0.0034400	total: 5m 44s	remaining: 11m 49s
3122:	learn: 0.0035062	total: 5m 44s	remaining: 12m 37s
3410:	learn: 0.0030887	total: 5m 44s	remaining: 11m 4s
3351:	learn: 0.0027882	total: 5m 44s	remaining: 11m 22s
3360:	learn: 0.0033514	total: 5m 43s	remaining: 11m 19s
3265:	learn: 0.0034384	total: 5m 44s	remaining: 11m 49s
3411:	learn: 0.0030870	total: 5m 44s	remaining: 11m 4s
3352:	learn: 0.0027871	total: 5m 44s	remaining: 11m 22s
3123:	learn: 0.0035044	total: 5m 44s	remaining: 12m 37s
3266:	learn: 0.0034362	total: 5m 44s	remaining: 11m 49s
3361:	learn: 0.0033503	total: 5m 44s	remaining: 11m 19s
3412:	learn: 0.0030854	total: 5m 44s	remaining: 11m 4s
3267:	learn: 0.0034346	total: 5m 44s	remaining: 11m 49s
3124:	learn: 0.0035028	total: 5m 44s	remaining: 12m 37s
3353:	learn: 0.0027856	total: 5m 44s	remaining: 11m 22s
3362:	learn: 0.0033484	total: 5m 44s	remaining: 11m 19s
3268:	learn: 0.0034330	total: 5m 44s	remaining: 11m 49s
3413:	learn: 0.0030844	total: 5m 44s	remaining: 11m 4s
3354:	learn: 0.0027845	total: 5m 44s	remaining: 11m 22s
3125:	learn: 0.0035008	total: 5m 44s	remaining: 12m 37s
3269:	learn: 0.0034311	total: 5m 44s	remaining: 11m 48s
3363:	learn: 0.0033466	total: 5m 44s	remaining: 11m 19s
3414:	learn: 0.0030833	total: 5m 44s	remaining: 11m 4s
3355:	learn: 0.0027836	total: 5m 44s	remaining: 11m 22s
3126:	learn: 0.0034994	total: 5m 44s	remaining: 12m 37s
3270:	learn: 0.0034294	total: 5m 44s	remaining: 11m 48s
3364:	learn: 0.0033455	total: 5m 44s	remaining: 11m 19s
3415:	learn: 0.0030822	total: 5m 44s	remaining: 11m 4s
3356:	learn: 0.0027821	total: 5m 44s	remaining: 11m 21s
3271:	learn: 0.0034270	total: 5m 44s	remaining: 11m 48s
3365:	learn: 0.0033446	total: 5m 44s	remaining: 11m 18s
3127:	learn: 0.0034980	total: 5m 44s	remaining: 12m 37s
3416:	learn: 0.0030807	total: 5m 44s	remaining: 11m 4s
3357:	learn: 0.0027808	total: 5m 44s	remaining: 11m 21s
3366:	learn: 0.0033434	total: 5m 44s	remaining: 11m 18s
3128:	learn: 0.0034962	total: 5m 44s	remaining: 12m 37s
3272:	learn: 0.0034257	total: 5m 44s	remaining: 11m 48s
3417:	learn: 0.0030792	total: 5m 44s	remaining: 11m 4s
3358:	learn: 0.0027795	total: 5m 44s	remaining: 11m 21s
3367:	learn: 0.0033428	total: 5m 44s	remaining: 11m 18s
3129:	learn: 0.0034947	total: 5m 44s	remaining: 12m 37s
3273:	learn: 0.0034240	total: 5m 44s	remaining: 11m 48s
3418:	learn: 0.0030782	total: 5m 44s	remaining: 11m 3s
3359:	learn: 0.0027782	total: 5m 44s	remaining: 11m 21s
3368:	learn: 0.0033419	total: 5m 44s	remaining: 11m 18s
3274:	learn: 0.0034229	total: 5m 44s	remaining: 11m 48s
3419:	learn: 0.0030772	total: 5m 45s	remaining: 11m 3s
3130:	learn: 0.0034933	total: 5m 45s	remaining: 12m 36s
3360:	learn: 0.0027772	total: 5m 45s	remaining: 11m 21s
3369:	learn: 0.0033401	total: 5m 44s	remaining: 11m 18s
3275:	learn: 0.0034213	total: 5m 45s	remaining: 11m 48s
3131:	learn: 0.0034911	total: 5m 45s	remaining: 12m 36s
3420:	learn: 0.0030757	total: 5m 45s	remaining: 11m 3s
3361:	learn: 0.0027759	total: 5m 45s	remaining: 11m 21s
3370:	learn: 0.0033389	total: 5m 44s	remaining: 11m 18s
3276:	learn: 0.0034195	total: 5m 45s	remaining: 11m 48s
3421:	learn: 0.0030744	total: 5m 45s	remaining: 11m 3s
3362:	learn: 0.0027749	total: 5m 45s	remaining: 11m 21s
3132:	learn: 0.0034902	total: 5m 45s	remaining: 12m 36s
3371:	learn: 0.0033378	total: 5m 45s	remaining: 11m 18s
3277:	learn: 0.0034172	total: 5m 45s	remaining: 11m 47s
3422:	learn: 0.0030731	total: 5m 45s	remaining: 11m 3s
3278:	learn: 0.0034153	total: 5m 45s	remaining: 11m 47s
3363:	learn: 0.0027736	total: 5m 45s	remaining: 11m 21s
3372:	learn: 0.0033361	total: 5m 45s	remaining: 11m 18s
3133:	learn: 0.0034885	total: 5m 45s	remaining: 12m 36s
3423:	learn: 0.0030722	total: 5m 45s	remaining: 11m 3s
3373:	learn: 0.0033351	total: 5m 45s	remaining: 11m 18s
3279:	learn: 0.0034132	total: 5m 45s	remaining: 11m 47s
3364:	learn: 0.0027727	total: 5m 45s	remaining: 11m 21s
3424:	learn: 0.0030705	total: 5m 45s	remaining: 11m 3s
3134:	learn: 0.0034865	total: 5m 45s	remaining: 12m 36s
3374:	learn: 0.0033340	total: 5m 45s	remaining: 11m 17s
3365:	learn: 0.0027716	total: 5m 45s	remaining: 11m 20s
3280:	learn: 0.0034110	total: 5m 45s	remaining: 11m 47s
3425:	learn: 0.0030688	total: 5m 45s	remaining: 11m 3s
3375:	learn: 0.0033329	total: 5m 45s	remaining: 11m 17s
3135:	learn: 0.0034843	total: 5m 45s	remaining: 12m 36s
3366:	learn: 0.0027703	total: 5m 45s	remaining: 11m 20s
3281:	learn: 0.0034089	total: 5m 45s	remaining: 11m 47s
3376:	learn: 0.0033312	total: 5m 45s	remaining: 11m 17s
3426:	learn: 0.0030675	total: 5m 45s	remaining: 11m 3s
3282:	learn: 0.0034081	total: 5m 45s	remaining: 11m 47s
3136:	learn: 0.0034820	total: 5m 45s	remaining: 12m 36s
3367:	learn: 0.0027692	total: 5m 45s	remaining: 11m 20s
3377:	learn: 0.0033301	total: 5m 45s	remaining: 11m 17s
3427:	learn: 0.0030662	total: 5m 45s	remaining: 11m 3s
3283:	learn: 0.0034063	total: 5m 45s	remaining: 11m 47s
3137:	learn: 0.0034801	total: 5m 45s	remaining: 12m 36s
3368:	learn: 0.0027676	total: 5m 45s	remaining: 11m 20s
3378:	learn: 0.0033282	total: 5m 45s	remaining: 11m 17s
3428:	learn: 0.0030652	total: 5m 45s	remaining: 11m 2s
3138:	learn: 0.0034794	total: 5m 45s	remaining: 12m 36s
3284:	learn: 0.0034055	total: 5m 45s	remaining: 11m 47s
3369:	learn: 0.0027663	total: 5m 45s	remaining: 11m 20s
3379:	learn: 0.0033268	total: 5m 45s	remaining: 11m 17s
3429:	learn: 0.0030640	total: 5m 46s	remaining: 11m 2s
3285:	learn: 0.0034047	total: 5m 46s	remaining: 11m 46s
3139:	learn: 0.0034780	total: 5m 46s	remaining: 12m 36s
3370:	learn: 0.0027654	total: 5m 46s	remaining: 11m 20s
3380:	learn: 0.0033249	total: 5m 45s	remaining: 11m 17s
3430:	learn: 0.0030630	total: 5m 46s	remaining: 11m 2s
3371:	learn: 0.0027642	total: 5m 46s	remaining: 11m 20s
3381:	learn: 0.0033233	total: 5m 45s	remaining: 11m 17s
3140:	learn: 0.0034772	total: 5m 46s	remaining: 12m 35s
3286:	learn: 0.0034030	total: 5m 46s	remaining: 11m 46s
3431:	learn: 0.0030610	total: 5m 46s	remaining: 11m 2s
3382:	learn: 0.0033218	total: 5m 46s	remaining: 11m 16s
3287:	learn: 0.0034010	total: 5m 46s	remaining: 11m 46s
3372:	learn: 0.0027623	total: 5m 46s	remaining: 11m 20s
3141:	learn: 0.0034756	total: 5m 46s	remaining: 12m 35s
3432:	learn: 0.0030598	total: 5m 46s	remaining: 11m 2s
3288:	learn: 0.0033990	total: 5m 46s	remaining: 11m 46s
3142:	learn: 0.0034746	total: 5m 46s	remaining: 12m 35s
3383:	learn: 0.0033207	total: 5m 46s	remaining: 11m 16s
3373:	learn: 0.0027610	total: 5m 46s	remaining: 11m 20s
3289:	learn: 0.0033982	total: 5m 46s	remaining: 11m 46s
3433:	learn: 0.0030589	total: 5m 46s	remaining: 11m 2s
3384:	learn: 0.0033188	total: 5m 46s	remaining: 11m 16s
3374:	learn: 0.0027592	total: 5m 46s	remaining: 11m 20s
3143:	learn: 0.0034727	total: 5m 46s	remaining: 12m 35s
3290:	learn: 0.0033975	total: 5m 46s	remaining: 11m 46s
3434:	learn: 0.0030574	total: 5m 46s	remaining: 11m 2s
3385:	learn: 0.0033177	total: 5m 46s	remaining: 11m 16s
3375:	learn: 0.0027578	total: 5m 46s	remaining: 11m 19s
3144:	learn: 0.0034711	total: 5m 46s	remaining: 12m 35s
3291:	learn: 0.0033967	total: 5m 46s	remaining: 11m 46s
3435:	learn: 0.0030565	total: 5m 46s	remaining: 11m 2s
3386:	learn: 0.0033153	total: 5m 46s	remaining: 11m 16s
3376:	learn: 0.0027571	total: 5m 46s	remaining: 11m 19s
3145:	learn: 0.0034692	total: 5m 46s	remaining: 12m 35s
3436:	learn: 0.0030553	total: 5m 46s	remaining: 11m 2s
3377:	learn: 0.0027561	total: 5m 46s	remaining: 11m 19s
3387:	learn: 0.0033145	total: 5m 46s	remaining: 11m 16s
3292:	learn: 0.0033951	total: 5m 46s	remaining: 11m 46s
3146:	learn: 0.0034670	total: 5m 46s	remaining: 12m 35s
3437:	learn: 0.0030533	total: 5m 46s	remaining: 11m 1s
3388:	learn: 0.0033129	total: 5m 46s	remaining: 11m 16s
3378:	learn: 0.0027546	total: 5m 46s	remaining: 11m 19s
3147:	learn: 0.0034658	total: 5m 46s	remaining: 12m 35s
3293:	learn: 0.0033935	total: 5m 46s	remaining: 11m 46s
3438:	learn: 0.0030517	total: 5m 46s	remaining: 11m 1s
3379:	learn: 0.0027535	total: 5m 46s	remaining: 11m 19s
3148:	learn: 0.0034649	total: 5m 46s	remaining: 12m 34s
3389:	learn: 0.0033114	total: 5m 46s	remaining: 11m 16s
3294:	learn: 0.0033914	total: 5m 46s	remaining: 11m 46s
3439:	learn: 0.0030497	total: 5m 47s	remaining: 11m 1s
3380:	learn: 0.0027522	total: 5m 47s	remaining: 11m 19s
3390:	learn: 0.0033097	total: 5m 46s	remaining: 11m 16s
3149:	learn: 0.0034637	total: 5m 47s	remaining: 12m 34s
3381:	learn: 0.0027506	total: 5m 47s	remaining: 11m 19s
3295:	learn: 0.0033893	total: 5m 47s	remaining: 11m 45s
3440:	learn: 0.0030483	total: 5m 47s	remaining: 11m 1s
3391:	learn: 0.0033089	total: 5m 46s	remaining: 11m 15s
3150:	learn: 0.0034623	total: 5m 47s	remaining: 12m 34s
3392:	learn: 0.0033076	total: 5m 47s	remaining: 11m 15s
3382:	learn: 0.0027493	total: 5m 47s	remaining: 11m 19s
3441:	learn: 0.0030474	total: 5m 47s	remaining: 11m 1s
3296:	learn: 0.0033885	total: 5m 47s	remaining: 11m 45s
3151:	learn: 0.0034599	total: 5m 47s	remaining: 12m 34s
3383:	learn: 0.0027482	total: 5m 47s	remaining: 11m 19s
3393:	learn: 0.0033059	total: 5m 47s	remaining: 11m 15s
3442:	learn: 0.0030452	total: 5m 47s	remaining: 11m 1s
3297:	learn: 0.0033866	total: 5m 47s	remaining: 11m 45s
3152:	learn: 0.0034586	total: 5m 47s	remaining: 12m 34s
3443:	learn: 0.0030435	total: 5m 47s	remaining: 11m 1s
3394:	learn: 0.0033045	total: 5m 47s	remaining: 11m 15s
3384:	learn: 0.0027467	total: 5m 47s	remaining: 11m 18s
3298:	learn: 0.0033850	total: 5m 47s	remaining: 11m 45s
3153:	learn: 0.0034568	total: 5m 47s	remaining: 12m 34s
3444:	learn: 0.0030427	total: 5m 47s	remaining: 11m 1s
3395:	learn: 0.0033027	total: 5m 47s	remaining: 11m 15s
3299:	learn: 0.0033838	total: 5m 47s	remaining: 11m 45s
3385:	learn: 0.0027454	total: 5m 47s	remaining: 11m 18s
3154:	learn: 0.0034555	total: 5m 47s	remaining: 12m 34s
3445:	learn: 0.0030413	total: 5m 47s	remaining: 11m 1s
3396:	learn: 0.0033013	total: 5m 47s	remaining: 11m 15s
3300:	learn: 0.0033830	total: 5m 47s	remaining: 11m 45s
3155:	learn: 0.0034536	total: 5m 47s	remaining: 12m 33s
3386:	learn: 0.0027444	total: 5m 47s	remaining: 11m 18s
3446:	learn: 0.0030398	total: 5m 47s	remaining: 11m
3397:	learn: 0.0033003	total: 5m 47s	remaining: 11m 15s
3156:	learn: 0.0034523	total: 5m 47s	remaining: 12m 33s
3387:	learn: 0.0027430	total: 5m 47s	remaining: 11m 18s
3301:	learn: 0.0033812	total: 5m 47s	remaining: 11m 45s
3447:	learn: 0.0030387	total: 5m 47s	remaining: 11m
3398:	learn: 0.0032986	total: 5m 47s	remaining: 11m 15s
3157:	learn: 0.0034513	total: 5m 47s	remaining: 12m 33s
3388:	learn: 0.0027417	total: 5m 47s	remaining: 11m 18s
3302:	learn: 0.0033797	total: 5m 47s	remaining: 11m 45s
3448:	learn: 0.0030375	total: 5m 47s	remaining: 11m
3399:	learn: 0.0032975	total: 5m 47s	remaining: 11m 15s
3158:	learn: 0.0034491	total: 5m 47s	remaining: 12m 33s
3449:	learn: 0.0030362	total: 5m 47s	remaining: 11m
3303:	learn: 0.0033787	total: 5m 47s	remaining: 11m 45s
3389:	learn: 0.0027396	total: 5m 47s	remaining: 11m 18s
3450:	learn: 0.0030347	total: 5m 48s	remaining: 11m
3400:	learn: 0.0032967	total: 5m 47s	remaining: 11m 14s
3159:	learn: 0.0034468	total: 5m 48s	remaining: 12m 33s
3304:	learn: 0.0033765	total: 5m 48s	remaining: 11m 45s
3390:	learn: 0.0027383	total: 5m 48s	remaining: 11m 18s
3451:	learn: 0.0030328	total: 5m 48s	remaining: 11m
3160:	learn: 0.0034453	total: 5m 48s	remaining: 12m 33s
3401:	learn: 0.0032947	total: 5m 47s	remaining: 11m 14s
3391:	learn: 0.0027374	total: 5m 48s	remaining: 11m 18s
3305:	learn: 0.0033747	total: 5m 48s	remaining: 11m 44s
3452:	learn: 0.0030313	total: 5m 48s	remaining: 11m
3402:	learn: 0.0032934	total: 5m 48s	remaining: 11m 14s
3161:	learn: 0.0034445	total: 5m 48s	remaining: 12m 33s
3392:	learn: 0.0027360	total: 5m 48s	remaining: 11m 18s
3306:	learn: 0.0033741	total: 5m 48s	remaining: 11m 44s
3453:	learn: 0.0030304	total: 5m 48s	remaining: 11m
3162:	learn: 0.0034438	total: 5m 48s	remaining: 12m 33s
3393:	learn: 0.0027350	total: 5m 48s	remaining: 11m 18s
3403:	learn: 0.0032917	total: 5m 48s	remaining: 11m 14s
3307:	learn: 0.0033733	total: 5m 48s	remaining: 11m 44s
3404:	learn: 0.0032902	total: 5m 48s	remaining: 11m 14s
3454:	learn: 0.0030289	total: 5m 48s	remaining: 11m
3163:	learn: 0.0034425	total: 5m 48s	remaining: 12m 32s
3394:	learn: 0.0027340	total: 5m 48s	remaining: 11m 17s
3308:	learn: 0.0033712	total: 5m 48s	remaining: 11m 44s
3405:	learn: 0.0032888	total: 5m 48s	remaining: 11m 14s
3455:	learn: 0.0030279	total: 5m 48s	remaining: 11m
3164:	learn: 0.0034404	total: 5m 48s	remaining: 12m 32s
3395:	learn: 0.0027330	total: 5m 48s	remaining: 11m 17s
3309:	learn: 0.0033697	total: 5m 48s	remaining: 11m 44s
3406:	learn: 0.0032880	total: 5m 48s	remaining: 11m 14s
3165:	learn: 0.0034386	total: 5m 48s	remaining: 12m 32s
3456:	learn: 0.0030267	total: 5m 48s	remaining: 10m 59s
3396:	learn: 0.0027317	total: 5m 48s	remaining: 11m 17s
3407:	learn: 0.0032872	total: 5m 48s	remaining: 11m 14s
3310:	learn: 0.0033677	total: 5m 48s	remaining: 11m 44s
3166:	learn: 0.0034373	total: 5m 48s	remaining: 12m 32s
3457:	learn: 0.0030247	total: 5m 48s	remaining: 10m 59s
3397:	learn: 0.0027309	total: 5m 48s	remaining: 11m 17s
3408:	learn: 0.0032853	total: 5m 48s	remaining: 11m 14s
3458:	learn: 0.0030241	total: 5m 48s	remaining: 10m 59s
3311:	learn: 0.0033657	total: 5m 48s	remaining: 11m 44s
3167:	learn: 0.0034353	total: 5m 48s	remaining: 12m 32s
3398:	learn: 0.0027297	total: 5m 48s	remaining: 11m 17s
3409:	learn: 0.0032842	total: 5m 48s	remaining: 11m 13s
3459:	learn: 0.0030234	total: 5m 48s	remaining: 10m 59s

3312:	learn: 0.0033646	total: 5m 48s	remaining: 11m 44s
3168:	learn: 0.0034338	total: 5m 48s	remaining: 12m 32s
3460:	learn: 0.0030214	total: 5m 49s	remaining: 10m 59s
3410:	learn: 0.0032827	total: 5m 48s	remaining: 11m 13s
3399:	learn: 0.0027288	total: 5m 48s	remaining: 11m 17s
3313:	learn: 0.0033638	total: 5m 49s	remaining: 11m 44s
3169:	learn: 0.0034327	total: 5m 49s	remaining: 12m 32s
3461:	learn: 0.0030199	total: 5m 49s	remaining: 10m 59s
3411:	learn: 0.0032820	total: 5m 48s	remaining: 11m 13s
3400:	learn: 0.0027280	total: 5m 49s	remaining: 11m 17s
3170:	learn: 0.0034327	total: 5m 49s	remaining: 12m 31s
3314:	learn: 0.0033618	total: 5m 49s	remaining: 11m 44s
3462:	learn: 0.0030190	total: 5m 49s	remaining: 10m 59s
3412:	learn: 0.0032796	total: 5m 49s	remaining: 11m 13s
3401:	learn: 0.0027271	total: 5m 49s	remaining: 11m 17s
3463:	learn: 0.0030178	total: 5m 49s	remaining: 10m 59s
3171:	learn: 0.0034302	total: 5m 49s	remaining: 12m 31s
3315:	learn: 0.0033599	total: 5m 49s	remaining: 11m 43s
3413:	learn: 0.0032782	total: 5m 49s	remaining: 11m 13s
3402:	learn: 0.0027258	total: 5m 49s	remaining: 11m 17s
3316:	learn: 0.0033581	total: 5m 49s	remaining: 11m 43s
3464:	learn: 0.0030163	total: 5m 49s	remaining: 10m 58s
3414:	learn: 0.0032776	total: 5m 49s	remaining: 11m 13s
3172:	learn: 0.0034290	total: 5m 49s	remaining: 12m 31s
3403:	learn: 0.0027243	total: 5m 49s	remaining: 11m 17s
3465:	learn: 0.0030152	total: 5m 49s	remaining: 10m 58s
3317:	learn: 0.0033566	total: 5m 49s	remaining: 11m 43s
3415:	learn: 0.0032753	total: 5m 49s	remaining: 11m 13s
3404:	learn: 0.0027233	total: 5m 49s	remaining: 11m 16s
3173:	learn: 0.0034279	total: 5m 49s	remaining: 12m 31s
3466:	learn: 0.0030138	total: 5m 49s	remaining: 10m 58s
3318:	learn: 0.0033552	total: 5m 49s	remaining: 11m 43s
3416:	learn: 0.0032733	total: 5m 49s	remaining: 11m 13s
3174:	learn: 0.0034272	total: 5m 49s	remaining: 12m 31s
3405:	learn: 0.0027220	total: 5m 49s	remaining: 11m 16s
3467:	learn: 0.0030123	total: 5m 49s	remaining: 10m 58s
3319:	learn: 0.0033544	total: 5m 49s	remaining: 11m 43s
3417:	learn: 0.0032722	total: 5m 49s	remaining: 11m 13s
3406:	learn: 0.0027210	total: 5m 49s	remaining: 11m 16s
3175:	learn: 0.0034260	total: 5m 49s	remaining: 12m 31s
3468:	learn: 0.0030100	total: 5m 49s	remaining: 10m 58s
3418:	learn: 0.0032716	total: 5m 49s	remaining: 11m 12s
3320:	learn: 0.0033537	total: 5m 49s	remaining: 11m 43s
3176:	learn: 0.0034244	total: 5m 49s	remaining: 12m 31s
3407:	learn: 0.0027195	total: 5m 49s	remaining: 11m 16s
3469:	learn: 0.0030081	total: 5m 49s	remaining: 10m 58s
3321:	learn: 0.0033522	total: 5m 49s	remaining: 11m 43s
3419:	learn: 0.0032697	total: 5m 49s	remaining: 11m 12s
3408:	learn: 0.0027176	total: 5m 49s	remaining: 11m 16s
3470:	learn: 0.0030067	total: 5m 49s	remaining: 10m 58s
3177:	learn: 0.0034234	total: 5m 49s	remaining: 12m 31s
3420:	learn: 0.0032686	total: 5m 49s	remaining: 11m 12s
3322:	learn: 0.0033507	total: 5m 49s	remaining: 11m 43s
3409:	learn: 0.0027157	total: 5m 49s	remaining: 11m 16s
3471:	learn: 0.0030053	total: 5m 50s	remaining: 10m 58s
3178:	learn: 0.0034214	total: 5m 50s	remaining: 12m 31s
3323:	learn: 0.0033493	total: 5m 50s	remaining: 11m 43s
3421:	learn: 0.0032678	total: 5m 49s	remaining: 11m 12s
3410:	learn: 0.0027145	total: 5m 50s	remaining: 11m 16s
3472:	learn: 0.0030041	total: 5m 50s	remaining: 10m 58s
3411:	learn: 0.0027132	total: 5m 50s	remaining: 11m 16s
3324:	learn: 0.0033479	total: 5m 50s	remaining: 11m 42s
3179:	learn: 0.0034207	total: 5m 50s	remaining: 12m 31s
3422:	learn: 0.0032655	total: 5m 50s	remaining: 11m 12s
3473:	learn: 0.0030032	total: 5m 50s	remaining: 10m 57s
3412:	learn: 0.0027117	total: 5m 50s	remaining: 11m 15s
3325:	learn: 0.0033464	total: 5m 50s	remaining: 11m 42s
3423:	learn: 0.0032641	total: 5m 50s	remaining: 11m 12s
3180:	learn: 0.0034196	total: 5m 50s	remaining: 12m 31s
3474:	learn: 0.0030014	total: 5m 50s	remaining: 10m 57s
3413:	learn: 0.0027100	total: 5m 50s	remaining: 11m 15s
3326:	learn: 0.0033447	total: 5m 50s	remaining: 11m 42s
3475:	learn: 0.0029993	total: 5m 50s	remaining: 10m 57s
3424:	learn: 0.0032634	total: 5m 50s	remaining: 11m 12s
3181:	learn: 0.0034183	total: 5m 50s	remaining: 12m 30s
3414:	learn: 0.0027093	total: 5m 50s	remaining: 11m 15s
3327:	learn: 0.0033433	total: 5m 50s	remaining: 11m 42s
3476:	learn: 0.0029986	total: 5m 50s	remaining: 10m 57s
3425:	learn: 0.0032627	total: 5m 50s	remaining: 11m 12s
3182:	learn: 0.0034163	total: 5m 50s	remaining: 12m 30s
3415:	learn: 0.0027081	total: 5m 50s	remaining: 11m 15s
3477:	learn: 0.0029974	total: 5m 50s	remaining: 10m 57s
3328:	learn: 0.0033414	total: 5m 50s	remaining: 11m 42s
3426:	learn: 0.0032618	total: 5m 50s	remaining: 11m 12s
3183:	learn: 0.0034154	total: 5m 50s	remaining: 12m 30s
3416:	learn: 0.0027069	total: 5m 50s	remaining: 11m 15s
3478:	learn: 0.0029957	total: 5m 50s	remaining: 10m 57s
3329:	learn: 0.0033404	total: 5m 50s	remaining: 11m 42s
3427:	learn: 0.0032610	total: 5m 50s	remaining: 11m 12s
3184:	learn: 0.0034140	total: 5m 50s	remaining: 12m 30s
3479:	learn: 0.0029939	total: 5m 50s	remaining: 10m 57s
3417:	learn: 0.0027057	total: 5m 50s	remaining: 11m 15s
3428:	learn: 0.0032603	total: 5m 50s	remaining: 11m 11s
3330:	learn: 0.0033389	total: 5m 50s	remaining: 11m 42s
3185:	learn: 0.0034131	total: 5m 50s	remaining: 12m 30s
3480:	learn: 0.0029923	total: 5m 50s	remaining: 10m 57s
3418:	learn: 0.0027046	total: 5m 50s	remaining: 11m 15s
3429:	learn: 0.0032586	total: 5m 50s	remaining: 11m 11s
3331:	learn: 0.0033371	total: 5m 50s	remaining: 11m 42s
3481:	learn: 0.0029905	total: 5m 50s	remaining: 10m 56s
3419:	learn: 0.0027030	total: 5m 50s	remaining: 11m 15s
3186:	learn: 0.0034115	total: 5m 51s	remaining: 12m 30s
3430:	learn: 0.0032576	total: 5m 50s	remaining: 11m 11s
3332:	learn: 0.0033358	total: 5m 50s	remaining: 11m 42s
3482:	learn: 0.0029889	total: 5m 51s	remaining: 10m 56s
3420:	learn: 0.0027018	total: 5m 51s	remaining: 11m 15s
3431:	learn: 0.0032554	total: 5m 50s	remaining: 11m 11s
3483:	learn: 0.0029875	total: 5m 51s	remaining: 10m 56s
3187:	learn: 0.0034103	total: 5m 51s	remaining: 12m 30s
3333:	learn: 0.0033344	total: 5m 51s	remaining: 11m 41s
3421:	learn: 0.0027003	total: 5m 51s	remaining: 11m 14s
3484:	learn: 0.0029864	total: 5m 51s	remaining: 10m 56s
3432:	learn: 0.0032544	total: 5m 51s	remaining: 11m 11s
3188:	learn: 0.0034091	total: 5m 51s	remaining: 12m 30s
3422:	learn: 0.0026985	total: 5m 51s	remaining: 11m 14s
3334:	learn: 0.0033328	total: 5m 51s	remaining: 11m 41s
3423:	learn: 0.0026971	total: 5m 51s	remaining: 11m 14s
3485:	learn: 0.0029850	total: 5m 51s	remaining: 10m 56s
3433:	learn: 0.0032521	total: 5m 51s	remaining: 11m 11s
3189:	learn: 0.0034079	total: 5m 51s	remaining: 12m 30s
3335:	learn: 0.0033314	total: 5m 51s	remaining: 11m 41s
3486:	learn: 0.0029837	total: 5m 51s	remaining: 10m 56s
3424:	learn: 0.0026958	total: 5m 51s	remaining: 11m 14s
3434:	learn: 0.0032502	total: 5m 51s	remaining: 11m 11s
3190:	learn: 0.0034065	total: 5m 51s	remaining: 12m 29s
3336:	learn: 0.0033298	total: 5m 51s	remaining: 11m 41s
3487:	learn: 0.0029822	total: 5m 51s	remaining: 10m 56s
3435:	learn: 0.0032489	total: 5m 51s	remaining: 11m 11s
3425:	learn: 0.0026939	total: 5m 51s	remaining: 11m 14s
3191:	learn: 0.0034054	total: 5m 51s	remaining: 12m 29s
3488:	learn: 0.0029811	total: 5m 51s	remaining: 10m 56s
3436:	learn: 0.0032466	total: 5m 51s	remaining: 11m 11s
3337:	learn: 0.0033285	total: 5m 51s	remaining: 11m 41s
3426:	learn: 0.0026930	total: 5m 51s	remaining: 11m 14s
3192:	learn: 0.0034042	total: 5m 51s	remaining: 12m 29s
3489:	learn: 0.0029797	total: 5m 51s	remaining: 10m 55s
3437:	learn: 0.0032460	total: 5m 51s	remaining: 11m 10s
3338:	learn: 0.0033276	total: 5m 51s	remaining: 11m 41s
3193:	learn: 0.0034028	total: 5m 51s	remaining: 12m 29s
3490:	learn: 0.0029786	total: 5m 51s	remaining: 10m 55s
3427:	learn: 0.0026919	total: 5m 51s	remaining: 11m 14s
3438:	learn: 0.0032453	total: 5m 51s	remaining: 11m 10s
3339:	learn: 0.0033261	total: 5m 51s	remaining: 11m 41s
3491:	learn: 0.0029774	total: 5m 51s	remaining: 10m 55s
3439:	learn: 0.0032442	total: 5m 51s	remaining: 11m 10s
3194:	learn: 0.0034013	total: 5m 51s	remaining: 12m 29s
3428:	learn: 0.0026906	total: 5m 51s	remaining: 11m 14s
3340:	learn: 0.0033239	total: 5m 51s	remaining: 11m 41s
3440:	learn: 0.0032424	total: 5m 51s	remaining: 11m 10s
3492:	learn: 0.0029762	total: 5m 51s	remaining: 10m 55s
3341:	learn: 0.0033225	total: 5m 51s	remaining: 11m 41s
3195:	learn: 0.0033999	total: 5m 52s	remaining: 12m 29s
3429:	learn: 0.0026893	total: 5m 51s	remaining: 11m 14s
3493:	learn: 0.0029748	total: 5m 52s	remaining: 10m 55s
3441:	learn: 0.0032406	total: 5m 51s	remaining: 11m 10s
3342:	learn: 0.0033219	total: 5m 52s	remaining: 11m 40s
3430:	learn: 0.0026879	total: 5m 52s	remaining: 11m 14s
3196:	learn: 0.0033979	total: 5m 52s	remaining: 12m 29s
3442:	learn: 0.0032388	total: 5m 51s	remaining: 11m 10s
3494:	learn: 0.0029735	total: 5m 52s	remaining: 10m 55s
3343:	learn: 0.0033205	total: 5m 52s	remaining: 11m 40s
3431:	learn: 0.0026869	total: 5m 52s	remaining: 11m 13s
3495:	learn: 0.0029718	total: 5m 52s	remaining: 10m 55s
3197:	learn: 0.0033957	total: 5m 52s	remaining: 12m 29s
3443:	learn: 0.0032369	total: 5m 52s	remaining: 11m 10s
3344:	learn: 0.0033188	total: 5m 52s	remaining: 11m 40s
3432:	learn: 0.0026854	total: 5m 52s	remaining: 11m 13s
3496:	learn: 0.0029706	total: 5m 52s	remaining: 10m 55s
3198:	learn: 0.0033945	total: 5m 52s	remaining: 12m 29s
3345:	learn: 0.0033173	total: 5m 52s	remaining: 11m 40s
3433:	learn: 0.0026840	total: 5m 52s	remaining: 11m 13s
3444:	learn: 0.0032358	total: 5m 52s	remaining: 11m 10s
3346:	learn: 0.0033159	total: 5m 52s	remaining: 11m 40s
3497:	learn: 0.0029694	total: 5m 52s	remaining: 10m 55s
3445:	learn: 0.0032337	total: 5m 52s	remaining: 11m 9s
3434:	learn: 0.0026832	total: 5m 52s	remaining: 11m 13s
3199:	learn: 0.0033928	total: 5m 52s	remaining: 12m 29s
3498:	learn: 0.0029680	total: 5m 52s	remaining: 10m 54s
3446:	learn: 0.0032322	total: 5m 52s	remaining: 11m 9s
3347:	learn: 0.0033141	total: 5m 52s	remaining: 11m 40s
3200:	learn: 0.0033928	total: 5m 52s	remaining: 12m 28s
3499:	learn: 0.0029660	total: 5m 52s	remaining: 10m 54s
3435:	learn: 0.0026820	total: 5m 52s	remaining: 11m 13s
3447:	learn: 0.0032304	total: 5m 52s	remaining: 11m 9s
3348:	learn: 0.0033123	total: 5m 52s	remaining: 11m 40s
3500:	learn: 0.0029641	total: 5m 52s	remaining: 10m 54s
3436:	learn: 0.0026802	total: 5m 52s	remaining: 11m 13s
3201:	learn: 0.0033918	total: 5m 52s	remaining: 12m 28s
3448:	learn: 0.0032292	total: 5m 52s	remaining: 11m 9s
3349:	learn: 0.0033113	total: 5m 52s	remaining: 11m 40s
3501:	learn: 0.0029628	total: 5m 52s	remaining: 10m 54s
3202:	learn: 0.0033906	total: 5m 52s	remaining: 12m 28s
3449:	learn: 0.0032283	total: 5m 52s	remaining: 11m 9s
3437:	learn: 0.0026789	total: 5m 52s	remaining: 11m 13s
3502:	learn: 0.0029614	total: 5m 52s	remaining: 10m 54s
3350:	learn: 0.0033097	total: 5m 52s	remaining: 11m 40s
3203:	learn: 0.0033884	total: 5m 52s	remaining: 12m 28s
3450:	learn: 0.0032272	total: 5m 52s	remaining: 11m 9s
3351:	learn: 0.0033080	total: 5m 52s	remaining: 11m 39s
3438:	learn: 0.0026778	total: 5m 52s	remaining: 11m 13s
3503:	learn: 0.0029595	total: 5m 53s	remaining: 10m 54s
3451:	learn: 0.0032251	total: 5m 52s	remaining: 11m 9s
3204:	learn: 0.0033862	total: 5m 53s	remaining: 12m 28s
3439:	learn: 0.0026766	total: 5m 53s	remaining: 11m 13s
3352:	learn: 0.0033061	total: 5m 52s	remaining: 11m 39s
3504:	learn: 0.0029582	total: 5m 53s	remaining: 10m 54s
3452:	learn: 0.0032244	total: 5m 52s	remaining: 11m 9s
3205:	learn: 0.0033850	total: 5m 53s	remaining: 12m 28s
3440:	learn: 0.0026754	total: 5m 53s	remaining: 11m 13s
3353:	learn: 0.0033046	total: 5m 53s	remaining: 11m 39s
3453:	learn: 0.0032235	total: 5m 52s	remaining: 11m 8s
3505:	learn: 0.0029567	total: 5m 53s	remaining: 10m 54s
3206:	learn: 0.0033840	total: 5m 53s	remaining: 12m 28s
3441:	learn: 0.0026739	total: 5m 53s	remaining: 11m 13s
3454:	learn: 0.0032224	total: 5m 53s	remaining: 11m 8s
3506:	learn: 0.0029552	total: 5m 53s	remaining: 10m 54s
3354:	learn: 0.0033031	total: 5m 53s	remaining: 11m 39s
3455:	learn: 0.0032209	total: 5m 53s	remaining: 11m 8s
3207:	learn: 0.0033825	total: 5m 53s	remaining: 12m 28s
3507:	learn: 0.0029530	total: 5m 53s	remaining: 10m 53s
3442:	learn: 0.0026725	total: 5m 53s	remaining: 11m 12s
3355:	learn: 0.0033015	total: 5m 53s	remaining: 11m 39s
3208:	learn: 0.0033814	total: 5m 53s	remaining: 12m 27s
3456:	learn: 0.0032199	total: 5m 53s	remaining: 11m 8s
3508:	learn: 0.0029511	total: 5m 53s	remaining: 10m 53s
3443:	learn: 0.0026711	total: 5m 53s	remaining: 11m 12s
3356:	learn: 0.0033005	total: 5m 53s	remaining: 11m 39s
3457:	learn: 0.0032190	total: 5m 53s	remaining: 11m 8s
3209:	learn: 0.0033802	total: 5m 53s	remaining: 12m 27s
3509:	learn: 0.0029495	total: 5m 53s	remaining: 10m 53s
3444:	learn: 0.0026699	total: 5m 53s	remaining: 11m 12s
3357:	learn: 0.0032991	total: 5m 53s	remaining: 11m 39s
3458:	learn: 0.0032183	total: 5m 53s	remaining: 11m 8s
3210:	learn: 0.0033783	total: 5m 53s	remaining: 12m 27s
3510:	learn: 0.0029482	total: 5m 53s	remaining: 10m 53s
3445:	learn: 0.0026689	total: 5m 53s	remaining: 11m 12s
3511:	learn: 0.0029466	total: 5m 53s	remaining: 10m 53s
3459:	learn: 0.0032169	total: 5m 53s	remaining: 11m 8s
3358:	learn: 0.0032975	total: 5m 53s	remaining: 11m 39s
3446:	learn: 0.0026680	total: 5m 53s	remaining: 11m 12s
3211:	learn: 0.0033770	total: 5m 53s	remaining: 12m 27s
3512:	learn: 0.0029457	total: 5m 53s	remaining: 10m 53s
3460:	learn: 0.0032160	total: 5m 53s	remaining: 11m 8s
3359:	learn: 0.0032962	total: 5m 53s	remaining: 11m 39s
3447:	learn: 0.0026670	total: 5m 53s	remaining: 11m 12s
3212:	learn: 0.0033761	total: 5m 53s	remaining: 12m 27s
3513:	learn: 0.0029443	total: 5m 53s	remaining: 10m 53s
3213:	learn: 0.0033751	total: 5m 53s	remaining: 12m 27s
3461:	learn: 0.0032146	total: 5m 53s	remaining: 11m 8s
3448:	learn: 0.0026658	total: 5m 53s	remaining: 11m 12s
3360:	learn: 0.0032949	total: 5m 53s	remaining: 11m 39s
3514:	learn: 0.0029435	total: 5m 54s	remaining: 10m 53s
3462:	learn: 0.0032132	total: 5m 53s	remaining: 11m 7s
3361:	learn: 0.0032934	total: 5m 54s	remaining: 11m 38s
3449:	learn: 0.0026644	total: 5m 54s	remaining: 11m 12s
3214:	learn: 0.0033741	total: 5m 54s	remaining: 12m 27s
3515:	learn: 0.0029429	total: 5m 54s	remaining: 10m 53s
3362:	learn: 0.0032915	total: 5m 54s	remaining: 11m 38s
3463:	learn: 0.0032119	total: 5m 53s	remaining: 11m 7s
3450:	learn: 0.0026630	total: 5m 54s	remaining: 11m 12s
3215:	learn: 0.0033730	total: 5m 54s	remaining: 12m 27s
3516:	learn: 0.0029423	total: 5m 54s	remaining: 10m 52s
3363:	learn: 0.0032898	total: 5m 54s	remaining: 11m 38s
3464:	learn: 0.0032106	total: 5m 54s	remaining: 11m 7s
3451:	learn: 0.0026612	total: 5m 54s	remaining: 11m 12s
3517:	learn: 0.0029418	total: 5m 54s	remaining: 10m 52s
3364:	learn: 0.0032883	total: 5m 54s	remaining: 11m 38s
3216:	learn: 0.0033711	total: 5m 54s	remaining: 12m 27s
3465:	learn: 0.0032099	total: 5m 54s	remaining: 11m 7s
3452:	learn: 0.0026599	total: 5m 54s	remaining: 11m 11s
3518:	learn: 0.0029400	total: 5m 54s	remaining: 10m 52s
3365:	learn: 0.0032867	total: 5m 54s	remaining: 11m 38s
3217:	learn: 0.0033689	total: 5m 54s	remaining: 12m 27s
3453:	learn: 0.0026590	total: 5m 54s	remaining: 11m 11s
3466:	learn: 0.0032091	total: 5m 54s	remaining: 11m 7s
3366:	learn: 0.0032852	total: 5m 54s	remaining: 11m 38s
3519:	learn: 0.0029392	total: 5m 54s	remaining: 10m 52s
3467:	learn: 0.0032069	total: 5m 54s	remaining: 11m 7s
3454:	learn: 0.0026575	total: 5m 54s	remaining: 11m 11s
3218:	learn: 0.0033674	total: 5m 54s	remaining: 12m 26s
3520:	learn: 0.0029377	total: 5m 54s	remaining: 10m 52s
3367:	learn: 0.0032839	total: 5m 54s	remaining: 11m 38s
3521:	learn: 0.0029369	total: 5m 54s	remaining: 10m 52s
3468:	learn: 0.0032051	total: 5m 54s	remaining: 11m 7s
3219:	learn: 0.0033659	total: 5m 54s	remaining: 12m 26s
3455:	learn: 0.0026558	total: 5m 54s	remaining: 11m 11s
3368:	learn: 0.0032826	total: 5m 54s	remaining: 11m 38s
3522:	learn: 0.0029355	total: 5m 54s	remaining: 10m 52s
3469:	learn: 0.0032042	total: 5m 54s	remaining: 11m 7s
3369:	learn: 0.0032812	total: 5m 54s	remaining: 11m 37s
3220:	learn: 0.0033659	total: 5m 54s	remaining: 12m 26s
3456:	learn: 0.0026545	total: 5m 54s	remaining: 11m 11s

3523:	learn: 0.0029343	total: 5m 54s	remaining: 10m 52s
3470:	learn: 0.0032032	total: 5m 54s	remaining: 11m 7s
3457:	learn: 0.0026531	total: 5m 54s	remaining: 11m 11s
3221:	learn: 0.0033659	total: 5m 54s	remaining: 12m 26s
3370:	learn: 0.0032797	total: 5m 54s	remaining: 11m 37s
3524:	learn: 0.0029330	total: 5m 54s	remaining: 10m 51s
3471:	learn: 0.0032013	total: 5m 54s	remaining: 11m 7s
3222:	learn: 0.0033644	total: 5m 54s	remaining: 12m 26s
3458:	learn: 0.0026517	total: 5m 54s	remaining: 11m 11s
3371:	learn: 0.0032790	total: 5m 54s	remaining: 11m 37s
3525:	learn: 0.0029316	total: 5m 55s	remaining: 10m 51s
3472:	learn: 0.0032000	total: 5m 54s	remaining: 11m 6s
3459:	learn: 0.0026504	total: 5m 55s	remaining: 11m 11s
3223:	learn: 0.0033628	total: 5m 55s	remaining: 12m 26s
3526:	learn: 0.0029303	total: 5m 55s	remaining: 10m 51s
3372:	learn: 0.0032775	total: 5m 55s	remaining: 11m 37s
3460:	learn: 0.0026486	total: 5m 55s	remaining: 11m 10s
3473:	learn: 0.0031982	total: 5m 54s	remaining: 11m 6s
3224:	learn: 0.0033615	total: 5m 55s	remaining: 12m 26s
3527:	learn: 0.0029290	total: 5m 55s	remaining: 10m 51s
3373:	learn: 0.0032757	total: 5m 55s	remaining: 11m 37s
3461:	learn: 0.0026475	total: 5m 55s	remaining: 11m 10s
3225:	learn: 0.0033601	total: 5m 55s	remaining: 12m 26s
3474:	learn: 0.0031966	total: 5m 55s	remaining: 11m 6s
3528:	learn: 0.0029272	total: 5m 55s	remaining: 10m 51s
3462:	learn: 0.0026462	total: 5m 55s	remaining: 11m 10s
3374:	learn: 0.0032749	total: 5m 55s	remaining: 11m 37s
3226:	learn: 0.0033589	total: 5m 55s	remaining: 12m 25s
3475:	learn: 0.0031949	total: 5m 55s	remaining: 11m 6s
3529:	learn: 0.0029258	total: 5m 55s	remaining: 10m 51s
3463:	learn: 0.0026447	total: 5m 55s	remaining: 11m 10s
3227:	learn: 0.0033576	total: 5m 55s	remaining: 12m 25s
3375:	learn: 0.0032732	total: 5m 55s	remaining: 11m 37s
3476:	learn: 0.0031928	total: 5m 55s	remaining: 11m 6s
3464:	learn: 0.0026436	total: 5m 55s	remaining: 11m 10s
3530:	learn: 0.0029243	total: 5m 55s	remaining: 10m 51s
3228:	learn: 0.0033567	total: 5m 55s	remaining: 12m 25s
3477:	learn: 0.0031910	total: 5m 55s	remaining: 11m 6s
3376:	learn: 0.0032717	total: 5m 55s	remaining: 11m 37s
3465:	learn: 0.0026423	total: 5m 55s	remaining: 11m 10s
3531:	learn: 0.0029227	total: 5m 55s	remaining: 10m 51s
3229:	learn: 0.0033557	total: 5m 55s	remaining: 12m 25s
3478:	learn: 0.0031889	total: 5m 55s	remaining: 11m 6s
3377:	learn: 0.0032696	total: 5m 55s	remaining: 11m 37s
3532:	learn: 0.0029212	total: 5m 55s	remaining: 10m 51s
3466:	learn: 0.0026406	total: 5m 55s	remaining: 11m 10s
3230:	learn: 0.0033541	total: 5m 55s	remaining: 12m 25s
3479:	learn: 0.0031874	total: 5m 55s	remaining: 11m 6s
3533:	learn: 0.0029200	total: 5m 55s	remaining: 10m 51s
3378:	learn: 0.0032681	total: 5m 55s	remaining: 11m 37s
3231:	learn: 0.0033520	total: 5m 55s	remaining: 12m 25s
3467:	learn: 0.0026397	total: 5m 55s	remaining: 11m 10s
3480:	learn: 0.0031856	total: 5m 55s	remaining: 11m 6s
3379:	learn: 0.0032662	total: 5m 55s	remaining: 11m 37s
3534:	learn: 0.0029184	total: 5m 55s	remaining: 10m 50s
3481:	learn: 0.0031842	total: 5m 55s	remaining: 11m 5s
3232:	learn: 0.0033513	total: 5m 55s	remaining: 12m 25s
3468:	learn: 0.0026385	total: 5m 55s	remaining: 11m 10s
3380:	learn: 0.0032654	total: 5m 55s	remaining: 11m 36s
3535:	learn: 0.0029178	total: 5m 56s	remaining: 10m 50s
3233:	learn: 0.0033490	total: 5m 56s	remaining: 12m 24s
3482:	learn: 0.0031832	total: 5m 55s	remaining: 11m 5s
3381:	learn: 0.0032637	total: 5m 56s	remaining: 11m 36s
3469:	learn: 0.0026377	total: 5m 56s	remaining: 11m 10s
3536:	learn: 0.0029160	total: 5m 56s	remaining: 10m 50s
3483:	learn: 0.0031817	total: 5m 55s	remaining: 11m 5s
3234:	learn: 0.0033478	total: 5m 56s	remaining: 12m 24s
3470:	learn: 0.0026363	total: 5m 56s	remaining: 11m 9s
3382:	learn: 0.0032623	total: 5m 56s	remaining: 11m 36s
3537:	learn: 0.0029145	total: 5m 56s	remaining: 10m 50s
3484:	learn: 0.0031808	total: 5m 56s	remaining: 11m 5s
3235:	learn: 0.0033478	total: 5m 56s	remaining: 12m 24s
3383:	learn: 0.0032610	total: 5m 56s	remaining: 11m 36s
3471:	learn: 0.0026349	total: 5m 56s	remaining: 11m 9s
3538:	learn: 0.0029132	total: 5m 56s	remaining: 10m 50s
3485:	learn: 0.0031795	total: 5m 56s	remaining: 11m 5s
3236:	learn: 0.0033462	total: 5m 56s	remaining: 12m 24s
3384:	learn: 0.0032604	total: 5m 56s	remaining: 11m 36s
3472:	learn: 0.0026332	total: 5m 56s	remaining: 11m 9s
3539:	learn: 0.0029119	total: 5m 56s	remaining: 10m 50s
3486:	learn: 0.0031779	total: 5m 56s	remaining: 11m 5s
3237:	learn: 0.0033443	total: 5m 56s	remaining: 12m 24s
3385:	learn: 0.0032588	total: 5m 56s	remaining: 11m 36s
3540:	learn: 0.0029108	total: 5m 56s	remaining: 10m 50s
3473:	learn: 0.0026315	total: 5m 56s	remaining: 11m 9s
3386:	learn: 0.0032578	total: 5m 56s	remaining: 11m 36s
3487:	learn: 0.0031759	total: 5m 56s	remaining: 11m 5s
3238:	learn: 0.0033428	total: 5m 56s	remaining: 12m 24s
3541:	learn: 0.0029099	total: 5m 56s	remaining: 10m 50s
3474:	learn: 0.0026303	total: 5m 56s	remaining: 11m 9s
3488:	learn: 0.0031749	total: 5m 56s	remaining: 11m 5s
3387:	learn: 0.0032571	total: 5m 56s	remaining: 11m 35s
3239:	learn: 0.0033409	total: 5m 56s	remaining: 12m 24s
3475:	learn: 0.0026281	total: 5m 56s	remaining: 11m 9s
3489:	learn: 0.0031742	total: 5m 56s	remaining: 11m 5s
3542:	learn: 0.0029087	total: 5m 56s	remaining: 10m 50s
3388:	learn: 0.0032554	total: 5m 56s	remaining: 11m 35s
3240:	learn: 0.0033398	total: 5m 56s	remaining: 12m 24s
3476:	learn: 0.0026274	total: 5m 56s	remaining: 11m 9s
3490:	learn: 0.0031728	total: 5m 56s	remaining: 11m 4s
3543:	learn: 0.0029069	total: 5m 56s	remaining: 10m 50s
3389:	learn: 0.0032545	total: 5m 56s	remaining: 11m 35s
3477:	learn: 0.0026264	total: 5m 56s	remaining: 11m 9s
3241:	learn: 0.0033377	total: 5m 56s	remaining: 12m 24s
3544:	learn: 0.0029056	total: 5m 56s	remaining: 10m 49s
3491:	learn: 0.0031720	total: 5m 56s	remaining: 11m 4s
3390:	learn: 0.0032533	total: 5m 56s	remaining: 11m 35s
3478:	learn: 0.0026251	total: 5m 56s	remaining: 11m 9s
3545:	learn: 0.0029049	total: 5m 57s	remaining: 10m 49s
3391:	learn: 0.0032524	total: 5m 56s	remaining: 11m 35s
3242:	learn: 0.0033357	total: 5m 57s	remaining: 12m 23s
3492:	learn: 0.0031708	total: 5m 56s	remaining: 11m 4s
3479:	learn: 0.0026238	total: 5m 57s	remaining: 11m 8s
3546:	learn: 0.0029036	total: 5m 57s	remaining: 10m 49s
3392:	learn: 0.0032516	total: 5m 57s	remaining: 11m 35s
3493:	learn: 0.0031700	total: 5m 56s	remaining: 11m 4s
3243:	learn: 0.0033337	total: 5m 57s	remaining: 12m 23s
3480:	learn: 0.0026227	total: 5m 57s	remaining: 11m 8s
3547:	learn: 0.0029025	total: 5m 57s	remaining: 10m 49s
3393:	learn: 0.0032500	total: 5m 57s	remaining: 11m 35s
3494:	learn: 0.0031692	total: 5m 57s	remaining: 11m 4s
3481:	learn: 0.0026217	total: 5m 57s	remaining: 11m 8s
3244:	learn: 0.0033330	total: 5m 57s	remaining: 12m 23s
3548:	learn: 0.0029009	total: 5m 57s	remaining: 10m 49s
3394:	learn: 0.0032482	total: 5m 57s	remaining: 11m 35s
3495:	learn: 0.0031686	total: 5m 57s	remaining: 11m 4s
3482:	learn: 0.0026211	total: 5m 57s	remaining: 11m 8s
3245:	learn: 0.0033313	total: 5m 57s	remaining: 12m 23s
3549:	learn: 0.0028996	total: 5m 57s	remaining: 10m 49s
3483:	learn: 0.0026194	total: 5m 57s	remaining: 11m 8s
3395:	learn: 0.0032464	total: 5m 57s	remaining: 11m 35s
3496:	learn: 0.0031670	total: 5m 57s	remaining: 11m 4s
3550:	learn: 0.0028983	total: 5m 57s	remaining: 10m 49s
3484:	learn: 0.0026183	total: 5m 57s	remaining: 11m 8s
3246:	learn: 0.0033303	total: 5m 57s	remaining: 12m 23s
3396:	learn: 0.0032456	total: 5m 57s	remaining: 11m 34s
3497:	learn: 0.0031654	total: 5m 57s	remaining: 11m 4s
3397:	learn: 0.0032436	total: 5m 57s	remaining: 11m 34s
3485:	learn: 0.0026170	total: 5m 57s	remaining: 11m 8s
3498:	learn: 0.0031645	total: 5m 57s	remaining: 11m 4s
3247:	learn: 0.0033283	total: 5m 57s	remaining: 12m 23s
3551:	learn: 0.0028967	total: 5m 57s	remaining: 10m 49s
3398:	learn: 0.0032420	total: 5m 57s	remaining: 11m 34s
3248:	learn: 0.0033269	total: 5m 57s	remaining: 12m 23s
3486:	learn: 0.0026157	total: 5m 57s	remaining: 11m 8s
3499:	learn: 0.0031624	total: 5m 57s	remaining: 11m 4s
3552:	learn: 0.0028951	total: 5m 57s	remaining: 10m 49s
3249:	learn: 0.0033260	total: 5m 57s	remaining: 12m 23s
3399:	learn: 0.0032402	total: 5m 57s	remaining: 11m 34s
3553:	learn: 0.0028938	total: 5m 57s	remaining: 10m 49s
3487:	learn: 0.0026148	total: 5m 57s	remaining: 11m 8s
3500:	learn: 0.0031603	total: 5m 57s	remaining: 11m 3s
3250:	learn: 0.0033259	total: 5m 57s	remaining: 12m 22s
3400:	learn: 0.0032387	total: 5m 57s	remaining: 11m 34s
3554:	learn: 0.0028928	total: 5m 57s	remaining: 10m 48s
3488:	learn: 0.0026138	total: 5m 57s	remaining: 11m 7s
3251:	learn: 0.0033259	total: 5m 57s	remaining: 12m 22s
3501:	learn: 0.0031596	total: 5m 57s	remaining: 11m 3s
3401:	learn: 0.0032371	total: 5m 57s	remaining: 11m 34s
3555:	learn: 0.0028914	total: 5m 58s	remaining: 10m 48s
3489:	learn: 0.0026130	total: 5m 58s	remaining: 11m 7s
3502:	learn: 0.0031580	total: 5m 57s	remaining: 11m 3s
3252:	learn: 0.0033253	total: 5m 58s	remaining: 12m 22s
3490:	learn: 0.0026121	total: 5m 58s	remaining: 11m 7s
3556:	learn: 0.0028898	total: 5m 58s	remaining: 10m 48s
3402:	learn: 0.0032364	total: 5m 58s	remaining: 11m 34s
3503:	learn: 0.0031566	total: 5m 57s	remaining: 11m 3s
3253:	learn: 0.0033253	total: 5m 58s	remaining: 12m 22s
3491:	learn: 0.0026106	total: 5m 58s	remaining: 11m 7s
3403:	learn: 0.0032357	total: 5m 58s	remaining: 11m 34s
3557:	learn: 0.0028880	total: 5m 58s	remaining: 10m 48s
3504:	learn: 0.0031559	total: 5m 58s	remaining: 11m 3s
3254:	learn: 0.0033231	total: 5m 58s	remaining: 12m 22s
3492:	learn: 0.0026096	total: 5m 58s	remaining: 11m 7s
3404:	learn: 0.0032343	total: 5m 58s	remaining: 11m 33s
3558:	learn: 0.0028868	total: 5m 58s	remaining: 10m 48s
3505:	learn: 0.0031552	total: 5m 58s	remaining: 11m 3s
3255:	learn: 0.0033211	total: 5m 58s	remaining: 12m 22s
3493:	learn: 0.0026085	total: 5m 58s	remaining: 11m 7s
3405:	learn: 0.0032323	total: 5m 58s	remaining: 11m 33s
3559:	learn: 0.0028856	total: 5m 58s	remaining: 10m 48s
3506:	learn: 0.0031536	total: 5m 58s	remaining: 11m 3s
3256:	learn: 0.0033190	total: 5m 58s	remaining: 12m 22s
3494:	learn: 0.0026072	total: 5m 58s	remaining: 11m 7s
3406:	learn: 0.0032316	total: 5m 58s	remaining: 11m 33s
3560:	learn: 0.0028844	total: 5m 58s	remaining: 10m 48s
3507:	learn: 0.0031523	total: 5m 58s	remaining: 11m 3s
3257:	learn: 0.0033190	total: 5m 58s	remaining: 12m 22s
3495:	learn: 0.0026060	total: 5m 58s	remaining: 11m 7s
3407:	learn: 0.0032309	total: 5m 58s	remaining: 11m 33s
3496:	learn: 0.0026048	total: 5m 58s	remaining: 11m 6s
3561:	learn: 0.0028833	total: 5m 58s	remaining: 10m 48s
3508:	learn: 0.0031513	total: 5m 58s	remaining: 11m 3s
3258:	learn: 0.0033179	total: 5m 58s	remaining: 12m 21s
3408:	learn: 0.0032296	total: 5m 58s	remaining: 11m 33s
3497:	learn: 0.0026036	total: 5m 58s	remaining: 11m 6s
3562:	learn: 0.0028820	total: 5m 58s	remaining: 10m 48s
3509:	learn: 0.0031503	total: 5m 58s	remaining: 11m 3s
3259:	learn: 0.0033173	total: 5m 58s	remaining: 12m 21s
3409:	learn: 0.0032280	total: 5m 58s	remaining: 11m 33s
3498:	learn: 0.0026025	total: 5m 58s	remaining: 11m 6s
3563:	learn: 0.0028808	total: 5m 58s	remaining: 10m 48s
3510:	learn: 0.0031494	total: 5m 58s	remaining: 11m 2s
3410:	learn: 0.0032261	total: 5m 58s	remaining: 11m 33s
3260:	learn: 0.0033150	total: 5m 58s	remaining: 12m 21s
3564:	learn: 0.0028797	total: 5m 58s	remaining: 10m 47s
3499:	learn: 0.0026012	total: 5m 58s	remaining: 11m 6s
3411:	learn: 0.0032253	total: 5m 58s	remaining: 11m 33s
3511:	learn: 0.0031485	total: 5m 58s	remaining: 11m 2s
3261:	learn: 0.0033133	total: 5m 59s	remaining: 12m 21s
3500:	learn: 0.0025998	total: 5m 59s	remaining: 11m 6s
3565:	learn: 0.0028781	total: 5m 59s	remaining: 10m 47s
3412:	learn: 0.0032238	total: 5m 59s	remaining: 11m 32s
3512:	learn: 0.0031476	total: 5m 58s	remaining: 11m 2s
3262:	learn: 0.0033120	total: 5m 59s	remaining: 12m 21s
3413:	learn: 0.0032220	total: 5m 59s	remaining: 11m 32s
3501:	learn: 0.0025989	total: 5m 59s	remaining: 11m 6s
3566:	learn: 0.0028765	total: 5m 59s	remaining: 10m 47s
3513:	learn: 0.0031460	total: 5m 59s	remaining: 11m 2s
3263:	learn: 0.0033100	total: 5m 59s	remaining: 12m 21s
3502:	learn: 0.0025976	total: 5m 59s	remaining: 11m 6s
3414:	learn: 0.0032204	total: 5m 59s	remaining: 11m 32s
3567:	learn: 0.0028752	total: 5m 59s	remaining: 10m 47s
3264:	learn: 0.0033094	total: 5m 59s	remaining: 12m 21s
3514:	learn: 0.0031447	total: 5m 59s	remaining: 11m 2s
3503:	learn: 0.0025967	total: 5m 59s	remaining: 11m 6s
3415:	learn: 0.0032187	total: 5m 59s	remaining: 11m 32s
3265:	learn: 0.0033077	total: 5m 59s	remaining: 12m 21s
3568:	learn: 0.0028738	total: 5m 59s	remaining: 10m 47s
3515:	learn: 0.0031432	total: 5m 59s	remaining: 11m 2s
3504:	learn: 0.0025954	total: 5m 59s	remaining: 11m 6s
3416:	learn: 0.0032172	total: 5m 59s	remaining: 11m 32s
3266:	learn: 0.0033057	total: 5m 59s	remaining: 12m 20s
3505:	learn: 0.0025942	total: 5m 59s	remaining: 11m 5s
3569:	learn: 0.0028724	total: 5m 59s	remaining: 10m 47s
3516:	learn: 0.0031415	total: 5m 59s	remaining: 11m 2s
3417:	learn: 0.0032157	total: 5m 59s	remaining: 11m 32s
3267:	learn: 0.0033057	total: 5m 59s	remaining: 12m 20s
3506:	learn: 0.0025929	total: 5m 59s	remaining: 11m 5s
3418:	learn: 0.0032148	total: 5m 59s	remaining: 11m 32s
3517:	learn: 0.0031406	total: 5m 59s	remaining: 11m 2s
3570:	learn: 0.0028708	total: 5m 59s	remaining: 10m 47s
3268:	learn: 0.0033050	total: 5m 59s	remaining: 12m 20s
3507:	learn: 0.0025916	total: 5m 59s	remaining: 11m 5s
3518:	learn: 0.0031392	total: 5m 59s	remaining: 11m 2s
3419:	learn: 0.0032134	total: 5m 59s	remaining: 11m 32s
3571:	learn: 0.0028693	total: 5m 59s	remaining: 10m 47s
3269:	learn: 0.0033037	total: 5m 59s	remaining: 12m 20s
3508:	learn: 0.0025900	total: 5m 59s	remaining: 11m 5s
3519:	learn: 0.0031383	total: 5m 59s	remaining: 11m 2s
3420:	learn: 0.0032124	total: 5m 59s	remaining: 11m 31s
3572:	learn: 0.0028679	total: 5m 59s	remaining: 10m 47s
3270:	learn: 0.0033011	total: 5m 59s	remaining: 12m 20s
3509:	learn: 0.0025891	total: 5m 59s	remaining: 11m 5s
3421:	learn: 0.0032107	total: 5m 59s	remaining: 11m 31s
3520:	learn: 0.0031370	total: 5m 59s	remaining: 11m 2s
3271:	learn: 0.0033002	total: 5m 59s	remaining: 12m 20s
3573:	learn: 0.0028667	total: 5m 59s	remaining: 10m 47s
3510:	learn: 0.0025883	total: 6m	remaining: 11m 5s
3422:	learn: 0.0032091	total: 6m	remaining: 11m 31s
3272:	learn: 0.0032989	total: 6m	remaining: 12m 20s
3521:	learn: 0.0031361	total: 5m 59s	remaining: 11m 1s
3574:	learn: 0.0028656	total: 6m	remaining: 10m 47s
3511:	learn: 0.0025869	total: 6m	remaining: 11m 5s
3273:	learn: 0.0032978	total: 6m	remaining: 12m 19s
3423:	learn: 0.0032076	total: 6m	remaining: 11m 31s
3522:	learn: 0.0031343	total: 5m 59s	remaining: 11m 1s
3575:	learn: 0.0028648	total: 6m	remaining: 10m 47s
3512:	learn: 0.0025863	total: 6m	remaining: 11m 5s
3523:	learn: 0.0031335	total: 6m	remaining: 11m 1s
3274:	learn: 0.0032978	total: 6m	remaining: 12m 19s
3424:	learn: 0.0032070	total: 6m	remaining: 11m 31s
3576:	learn: 0.0028641	total: 6m	remaining: 10m 46s
3275:	learn: 0.0032957	total: 6m	remaining: 12m 19s
3513:	learn: 0.0025849	total: 6m	remaining: 11m 5s
3425:	learn: 0.0032053	total: 6m	remaining: 11m 31s
3524:	learn: 0.0031326	total: 6m	remaining: 11m 1s
3577:	learn: 0.0028628	total: 6m	remaining: 10m 46s
3276:	learn: 0.0032949	total: 6m	remaining: 12m 19s
3514:	learn: 0.0025836	total: 6m	remaining: 11m 4s
3525:	learn: 0.0031311	total: 6m	remaining: 11m 1s
3426:	learn: 0.0032037	total: 6m	remaining: 11m 31s
3277:	learn: 0.0032940	total: 6m	remaining: 12m 19s
3578:	learn: 0.0028615	total: 6m	remaining: 10m 46s
3515:	learn: 0.0025827	total: 6m	remaining: 11m 4s
3427:	learn: 0.0032024	total: 6m	remaining: 11m 31s
3579:	learn: 0.0028602	total: 6m	remaining: 10m 46s
3526:	learn: 0.0031303	total: 6m	remaining: 11m 1s
3278:	learn: 0.0032924	total: 6m	remaining: 12m 19s
3516:	learn: 0.0025814	total: 6m	remaining: 11m 4s
3580:	learn: 0.0028588	total: 6m	remaining: 10m 46s
3428:	learn: 0.0032009	total: 6m	remaining: 11m 31s
3527:	learn: 0.0031286	total: 6m	remaining: 11m 1s
3279:	learn: 0.0032912	total: 6m	remaining: 12m 19s
3429:	learn: 0.0031995	total: 6m	remaining: 11m 30s
3517:	learn: 0.0025807	total: 6m	remaining: 11m 4s

3581:	learn: 0.0028579	total: 6m	remaining: 10m 46s
3280:	learn: 0.0032899	total: 6m	remaining: 12m 18s
3582:	learn: 0.0028565	total: 6m	remaining: 10m 46s
3518:	learn: 0.0025793	total: 6m	remaining: 11m 4s
3529:	learn: 0.0031256	total: 6m	remaining: 11m 1s
3431:	learn: 0.0031979	total: 6m	remaining: 11m 30s
3583:	learn: 0.0028549	total: 6m	remaining: 10m 46s
3281:	learn: 0.0032884	total: 6m	remaining: 12m 18s
3519:	learn: 0.0025779	total: 6m	remaining: 11m 4s
3432:	learn: 0.0031961	total: 6m	remaining: 11m 30s
3530:	learn: 0.0031242	total: 6m	remaining: 11m 1s
3584:	learn: 0.0028535	total: 6m 1s	remaining: 10m 45s
3282:	learn: 0.0032873	total: 6m 1s	remaining: 12m 18s
3520:	learn: 0.0025767	total: 6m 1s	remaining: 11m 4s
3531:	learn: 0.0031231	total: 6m	remaining: 11m
3433:	learn: 0.0031944	total: 6m 1s	remaining: 11m 30s
3585:	learn: 0.0028521	total: 6m 1s	remaining: 10m 45s
3283:	learn: 0.0032854	total: 6m 1s	remaining: 12m 18s
3586:	learn: 0.0028507	total: 6m 1s	remaining: 10m 45s
3521:	learn: 0.0025755	total: 6m 1s	remaining: 11m 4s
3434:	learn: 0.0031927	total: 6m 1s	remaining: 11m 30s
3532:	learn: 0.0031224	total: 6m 1s	remaining: 11m
3284:	learn: 0.0032833	total: 6m 1s	remaining: 12m 18s
3587:	learn: 0.0028491	total: 6m 1s	remaining: 10m 45s
3522:	learn: 0.0025742	total: 6m 1s	remaining: 11m 4s
3533:	learn: 0.0031212	total: 6m 1s	remaining: 11m
3435:	learn: 0.0031922	total: 6m 1s	remaining: 11m 30s
3285:	learn: 0.0032813	total: 6m 1s	remaining: 12m 18s
3588:	learn: 0.0028479	total: 6m 1s	remaining: 10m 45s
3523:	learn: 0.0025729	total: 6m 1s	remaining: 11m 4s
3436:	learn: 0.0031907	total: 6m 1s	remaining: 11m 30s
3534:	learn: 0.0031204	total: 6m 1s	remaining: 11m
3286:	learn: 0.0032798	total: 6m 1s	remaining: 12m 18s
3589:	learn: 0.0028464	total: 6m 1s	remaining: 10m 45s
3524:	learn: 0.0025716	total: 6m 1s	remaining: 11m 3s
3437:	learn: 0.0031891	total: 6m 1s	remaining: 11m 29s
3535:	learn: 0.0031197	total: 6m 1s	remaining: 11m
3287:	learn: 0.0032786	total: 6m 1s	remaining: 12m 18s
3590:	learn: 0.0028453	total: 6m 1s	remaining: 10m 45s
3525:	learn: 0.0025708	total: 6m 1s	remaining: 11m 3s
3536:	learn: 0.0031184	total: 6m 1s	remaining: 11m
3438:	learn: 0.0031882	total: 6m 1s	remaining: 11m 29s
3526:	learn: 0.0025698	total: 6m 1s	remaining: 11m 3s
3288:	learn: 0.0032786	total: 6m 1s	remaining: 12m 18s
3591:	learn: 0.0028441	total: 6m 1s	remaining: 10m 45s
3537:	learn: 0.0031168	total: 6m 1s	remaining: 11m
3527:	learn: 0.0025687	total: 6m 1s	remaining: 11m 3s
3439:	learn: 0.0031875	total: 6m 1s	remaining: 11m 29s
3592:	learn: 0.0028434	total: 6m 1s	remaining: 10m 45s
3538:	learn: 0.0031155	total: 6m 1s	remaining: 11m
3289:	learn: 0.0032786	total: 6m 1s	remaining: 12m 17s
3528:	learn: 0.0025676	total: 6m 1s	remaining: 11m 3s
3440:	learn: 0.0031855	total: 6m 1s	remaining: 11m 29s
3539:	learn: 0.0031135	total: 6m 1s	remaining: 11m
3593:	learn: 0.0028420	total: 6m 1s	remaining: 10m 45s
3529:	learn: 0.0025663	total: 6m 1s	remaining: 11m 3s
3441:	learn: 0.0031849	total: 6m 1s	remaining: 11m 29s
3290:	learn: 0.0032767	total: 6m 1s	remaining: 12m 17s
3540:	learn: 0.0031127	total: 6m 1s	remaining: 10m 59s
3594:	learn: 0.0028406	total: 6m 1s	remaining: 10m 44s
3530:	learn: 0.0025651	total: 6m 2s	remaining: 11m 3s
3442:	learn: 0.0031838	total: 6m 2s	remaining: 11m 29s
3291:	learn: 0.0032767	total: 6m 2s	remaining: 12m 17s
3541:	learn: 0.0031112	total: 6m 1s	remaining: 10m 59s
3595:	learn: 0.0028392	total: 6m 2s	remaining: 10m 44s
3531:	learn: 0.0025635	total: 6m 2s	remaining: 11m 3s
3596:	learn: 0.0028379	total: 6m 2s	remaining: 10m 44s
3443:	learn: 0.0031821	total: 6m 2s	remaining: 11m 29s
3292:	learn: 0.0032748	total: 6m 2s	remaining: 12m 17s
3542:	learn: 0.0031096	total: 6m 2s	remaining: 10m 59s
3532:	learn: 0.0025621	total: 6m 2s	remaining: 11m 2s
3597:	learn: 0.0028364	total: 6m 2s	remaining: 10m 44s
3444:	learn: 0.0031813	total: 6m 2s	remaining: 11m 29s
3293:	learn: 0.0032748	total: 6m 2s	remaining: 12m 17s
3543:	learn: 0.0031084	total: 6m 2s	remaining: 10m 59s
3533:	learn: 0.0025612	total: 6m 2s	remaining: 11m 2s
3598:	learn: 0.0028351	total: 6m 2s	remaining: 10m 44s
3544:	learn: 0.0031077	total: 6m 2s	remaining: 10m 59s
3445:	learn: 0.0031801	total: 6m 2s	remaining: 11m 29s
3294:	learn: 0.0032738	total: 6m 2s	remaining: 12m 17s
3534:	learn: 0.0025603	total: 6m 2s	remaining: 11m 2s
3599:	learn: 0.0028339	total: 6m 2s	remaining: 10m 44s
3545:	learn: 0.0031065	total: 6m 2s	remaining: 10m 59s
3446:	learn: 0.0031787	total: 6m 2s	remaining: 11m 29s
3535:	learn: 0.0025590	total: 6m 2s	remaining: 11m 2s
3295:	learn: 0.0032719	total: 6m 2s	remaining: 12m 17s
3600:	learn: 0.0028328	total: 6m 2s	remaining: 10m 44s
3546:	learn: 0.0031057	total: 6m 2s	remaining: 10m 59s
3447:	learn: 0.0031777	total: 6m 2s	remaining: 11m 28s
3296:	learn: 0.0032708	total: 6m 2s	remaining: 12m 17s
3601:	learn: 0.0028317	total: 6m 2s	remaining: 10m 44s
3536:	learn: 0.0025582	total: 6m 2s	remaining: 11m 2s
3448:	learn: 0.0031760	total: 6m 2s	remaining: 11m 28s
3547:	learn: 0.0031040	total: 6m 2s	remaining: 10m 59s
3602:	learn: 0.0028306	total: 6m 2s	remaining: 10m 44s
3297:	learn: 0.0032695	total: 6m 2s	remaining: 12m 17s
3537:	learn: 0.0025568	total: 6m 2s	remaining: 11m 2s
3548:	learn: 0.0031024	total: 6m 2s	remaining: 10m 59s
3449:	learn: 0.0031745	total: 6m 2s	remaining: 11m 28s
3603:	learn: 0.0028298	total: 6m 2s	remaining: 10m 43s
3538:	learn: 0.0025554	total: 6m 2s	remaining: 11m 2s
3549:	learn: 0.0031016	total: 6m 2s	remaining: 10m 58s
3450:	learn: 0.0031728	total: 6m 2s	remaining: 11m 28s
3298:	learn: 0.0032684	total: 6m 2s	remaining: 12m 17s
3539:	learn: 0.0025542	total: 6m 2s	remaining: 11m 2s
3604:	learn: 0.0028287	total: 6m 2s	remaining: 10m 43s
3451:	learn: 0.0031722	total: 6m 2s	remaining: 11m 28s
3550:	learn: 0.0030999	total: 6m 2s	remaining: 10m 58s
3299:	learn: 0.0032674	total: 6m 2s	remaining: 12m 16s
3551:	learn: 0.0030984	total: 6m 2s	remaining: 10m 58s
3605:	learn: 0.0028272	total: 6m 3s	remaining: 10m 43s
3540:	learn: 0.0025524	total: 6m 3s	remaining: 11m 2s
3452:	learn: 0.0031704	total: 6m 3s	remaining: 11m 28s
3300:	learn: 0.0032659	total: 6m 3s	remaining: 12m 16s
3552:	learn: 0.0030976	total: 6m 2s	remaining: 10m 58s
3541:	learn: 0.0025516	total: 6m 3s	remaining: 11m 2s
3606:	learn: 0.0028258	total: 6m 3s	remaining: 10m 43s
3453:	learn: 0.0031693	total: 6m 3s	remaining: 11m 28s
3301:	learn: 0.0032639	total: 6m 3s	remaining: 12m 16s
3553:	learn: 0.0030964	total: 6m 3s	remaining: 10m 58s
3542:	learn: 0.0025504	total: 6m 3s	remaining: 11m 1s
3607:	learn: 0.0028247	total: 6m 3s	remaining: 10m 43s
3454:	learn: 0.0031681	total: 6m 3s	remaining: 11m 28s
3302:	learn: 0.0032639	total: 6m 3s	remaining: 12m 16s
3554:	learn: 0.0030948	total: 6m 3s	remaining: 10m 58s
3543:	learn: 0.0025490	total: 6m 3s	remaining: 11m 1s
3608:	learn: 0.0028234	total: 6m 3s	remaining: 10m 43s
3455:	learn: 0.0031663	total: 6m 3s	remaining: 11m 27s
3544:	learn: 0.0025481	total: 6m 3s	remaining: 11m 1s
3555:	learn: 0.0030941	total: 6m 3s	remaining: 10m 58s
3303:	learn: 0.0032639	total: 6m 3s	remaining: 12m 16s
3456:	learn: 0.0031646	total: 6m 3s	remaining: 11m 27s
3609:	learn: 0.0028221	total: 6m 3s	remaining: 10m 43s
3545:	learn: 0.0025473	total: 6m 3s	remaining: 11m 1s
3556:	learn: 0.0030933	total: 6m 3s	remaining: 10m 58s
3304:	learn: 0.0032629	total: 6m 3s	remaining: 12m 16s
3457:	learn: 0.0031631	total: 6m 3s	remaining: 11m 27s
3610:	learn: 0.0028210	total: 6m 3s	remaining: 10m 43s
3546:	learn: 0.0025464	total: 6m 3s	remaining: 11m 1s
3305:	learn: 0.0032629	total: 6m 3s	remaining: 12m 16s
3557:	learn: 0.0030924	total: 6m 3s	remaining: 10m 58s
3458:	learn: 0.0031617	total: 6m 3s	remaining: 11m 27s
3611:	learn: 0.0028203	total: 6m 3s	remaining: 10m 43s
3547:	learn: 0.0025457	total: 6m 3s	remaining: 11m 1s
3306:	learn: 0.0032617	total: 6m 3s	remaining: 12m 16s
3558:	learn: 0.0030912	total: 6m 3s	remaining: 10m 57s
3459:	learn: 0.0031611	total: 6m 3s	remaining: 11m 27s
3612:	learn: 0.0028188	total: 6m 3s	remaining: 10m 43s
: 5m 51s	remaining: 10m 55s
3439:	learn: 0.0032442	total: 5m 51s	remaining: 11m 10s
3194:	learn: 0.00343548:	learn: 0.0025444	total: 6m 3s	remaining: 11m 1s
3559:	learn: 0.0030899	total: 6m 3s	remaining: 10m 57s
3307:	learn: 0.0032596	total: 6m 3s	remaining: 12m 16s
3460:	learn: 0.0031600	total: 6m 3s	remaining: 11m 27s
3549:	learn: 0.0025431	total: 6m 3s	remaining: 11m 1s
3613:	learn: 0.0028182	total: 6m 3s	remaining: 10m 42s
3308:	learn: 0.0032596	total: 6m 3s	remaining: 12m 15s
3560:	learn: 0.0030885	total: 6m 3s	remaining: 10m 57s
3550:	learn: 0.0025413	total: 6m 3s	remaining: 11m
3461:	learn: 0.0031581	total: 6m 3s	remaining: 11m 27s
3561:	learn: 0.0030869	total: 6m 3s	remaining: 10m 57s
3614:	learn: 0.0028175	total: 6m 4s	remaining: 10m 42s
3309:	learn: 0.0032596	total: 6m 4s	remaining: 12m 15s
3551:	learn: 0.0025399	total: 6m 4s	remaining: 11m
3615:	learn: 0.0028160	total: 6m 4s	remaining: 10m 42s
3562:	learn: 0.0030858	total: 6m 3s	remaining: 10m 57s
3462:	learn: 0.0031566	total: 6m 4s	remaining: 11m 27s
3310:	learn: 0.0032587	total: 6m 4s	remaining: 12m 15s
3552:	learn: 0.0025381	total: 6m 4s	remaining: 11m
3616:	learn: 0.0028146	total: 6m 4s	remaining: 10m 42s
3563:	learn: 0.0030847	total: 6m 4s	remaining: 10m 57s
3463:	learn: 0.0031538	total: 6m 4s	remaining: 11m 27s
3311:	learn: 0.0032587	total: 6m 4s	remaining: 12m 15s
3553:	learn: 0.0025369	total: 6m 4s	remaining: 11m
3617:	learn: 0.0028134	total: 6m 4s	remaining: 10m 42s
3464:	learn: 0.0031523	total: 6m 4s	remaining: 11m 26s
3312:	learn: 0.0032568	total: 6m 4s	remaining: 12m 15s
3564:	learn: 0.0030832	total: 6m 4s	remaining: 10m 57s
3554:	learn: 0.0025351	total: 6m 4s	remaining: 11m
3618:	learn: 0.0028128	total: 6m 4s	remaining: 10m 42s
3565:	learn: 0.0030825	total: 6m 4s	remaining: 10m 57s
3465:	learn: 0.0031507	total: 6m 4s	remaining: 11m 26s
3313:	learn: 0.0032556	total: 6m 4s	remaining: 12m 15s
3619:	learn: 0.0028113	total: 6m 4s	remaining: 10m 42s
3555:	learn: 0.0025346	total: 6m 4s	remaining: 11m
3566:	learn: 0.0030812	total: 6m 4s	remaining: 10m 56s
3466:	learn: 0.0031500	total: 6m 4s	remaining: 11m 26s
3314:	learn: 0.0032556	total: 6m 4s	remaining: 12m 15s
3567:	learn: 0.0030800	total: 6m 4s	remaining: 10m 56s
3620:	learn: 0.0028099	total: 6m 4s	remaining: 10m 42s
3556:	learn: 0.0025334	total: 6m 4s	remaining: 11m
3568:	learn: 0.0030784	total: 6m 4s	remaining: 10m 56s
3467:	learn: 0.0031487	total: 6m 4s	remaining: 11m 26s
3315:	learn: 0.0032545	total: 6m 4s	remaining: 12m 15s
3621:	learn: 0.0028093	total: 6m 4s	remaining: 10m 42s
3557:	learn: 0.0025325	total: 6m 4s	remaining: 11m
3569:	learn: 0.0030770	total: 6m 4s	remaining: 10m 56s
3468:	learn: 0.0031479	total: 6m 4s	remaining: 11m 26s
3316:	learn: 0.0032536	total: 6m 4s	remaining: 12m 14s
3622:	learn: 0.0028076	total: 6m 4s	remaining: 10m 42s
3570:	learn: 0.0030758	total: 6m 4s	remaining: 10m 56s
3558:	learn: 0.0025309	total: 6m 4s	remaining: 11m
3469:	learn: 0.0031473	total: 6m 4s	remaining: 11m 26s
3623:	learn: 0.0028064	total: 6m 4s	remaining: 10m 41s
3317:	learn: 0.0032536	total: 6m 4s	remaining: 12m 14s
3559:	learn: 0.0025302	total: 6m 4s	remaining: 11m
3571:	learn: 0.0030751	total: 6m 4s	remaining: 10m 56s
3470:	learn: 0.0031459	total: 6m 4s	remaining: 11m 26s
3318:	learn: 0.0032525	total: 6m 4s	remaining: 12m 14s
3624:	learn: 0.0028053	total: 6m 4s	remaining: 10m 41s
3560:	learn: 0.0025293	total: 6m 4s	remaining: 10m 59s
3572:	learn: 0.0030736	total: 6m 4s	remaining: 10m 56s
3471:	learn: 0.0031445	total: 6m 4s	remaining: 11m 26s
3561:	learn: 0.0025285	total: 6m 5s	remaining: 10m 59s
3625:	learn: 0.0028042	total: 6m 5s	remaining: 10m 41s
3319:	learn: 0.0032510	total: 6m 5s	remaining: 12m 14s
3472:	learn: 0.0031432	total: 6m 5s	remaining: 11m 26s
3573:	learn: 0.0030729	total: 6m 4s	remaining: 10m 56s
3562:	learn: 0.0025277	total: 6m 5s	remaining: 10m 59s
3320:	learn: 0.0032510	total: 6m 5s	remaining: 12m 14s
3626:	learn: 0.0028031	total: 6m 5s	remaining: 10m 41s
3574:	learn: 0.0030722	total: 6m 5s	remaining: 10m 56s
3473:	learn: 0.0031417	total: 6m 5s	remaining: 11m 25s
3563:	learn: 0.0025261	total: 6m 5s	remaining: 10m 59s
3627:	learn: 0.0028016	total: 6m 5s	remaining: 10m 41s
3321:	learn: 0.0032502	total: 6m 5s	remaining: 12m 14s
3575:	learn: 0.0030716	total: 6m 5s	remaining: 10m 55s
3564:	learn: 0.0025249	total: 6m 5s	remaining: 10m 59s
3474:	learn: 0.0031411	total: 6m 5s	remaining: 11m 25s
3576:	learn: 0.0030703	total: 6m 5s	remaining: 10m 55s
3628:	learn: 0.0028010	total: 6m 5s	remaining: 10m 41s
3322:	learn: 0.0032501	total: 6m 5s	remaining: 12m 14s
3565:	learn: 0.0025240	total: 6m 5s	remaining: 10m 59s
3475:	learn: 0.0031398	total: 6m 5s	remaining: 11m 25s
3629:	learn: 0.0028003	total: 6m 5s	remaining: 10m 41s
3577:	learn: 0.0030697	total: 6m 5s	remaining: 10m 55s
3323:	learn: 0.0032494	total: 6m 5s	remaining: 12m 14s
3566:	learn: 0.0025232	total: 6m 5s	remaining: 10m 59s
3476:	learn: 0.0031379	total: 6m 5s	remaining: 11m 25s
3630:	learn: 0.0027986	total: 6m 5s	remaining: 10m 41s
3578:	learn: 0.0030691	total: 6m 5s	remaining: 10m 55s
3324:	learn: 0.0032481	total: 6m 5s	remaining: 12m 13s
3567:	learn: 0.0025219	total: 6m 5s	remaining: 10m 59s
3477:	learn: 0.0031363	total: 6m 5s	remaining: 11m 25s
3631:	learn: 0.0027972	total: 6m 5s	remaining: 10m 41s
3325:	learn: 0.0032471	total: 6m 5s	remaining: 12m 13s
3579:	learn: 0.0030671	total: 6m 5s	remaining: 10m 55s
3478:	learn: 0.0031347	total: 6m 5s	remaining: 11m 25s
3568:	learn: 0.0025209	total: 6m 5s	remaining: 10m 59s
3632:	learn: 0.0027958	total: 6m 5s	remaining: 10m 41s
3580:	learn: 0.0030657	total: 6m 5s	remaining: 10m 55s
3326:	learn: 0.0032461	total: 6m 5s	remaining: 12m 13s
3479:	learn: 0.0031329	total: 6m 5s	remaining: 11m 25s
3569:	learn: 0.0025200	total: 6m 5s	remaining: 10m 58s
3581:	learn: 0.0030641	total: 6m 5s	remaining: 10m 55s
3633:	learn: 0.0027947	total: 6m 5s	remaining: 10m 40s
3570:	learn: 0.0025188	total: 6m 5s	remaining: 10m 58s
3480:	learn: 0.0031313	total: 6m 5s	remaining: 11m 25s
3327:	learn: 0.0032452	total: 6m 5s	remaining: 12m 13s
3582:	learn: 0.0030630	total: 6m 5s	remaining: 10m 55s
3571:	learn: 0.0025180	total: 6m 5s	remaining: 10m 58s
3634:	learn: 0.0027934	total: 6m 6s	remaining: 10m 40s
3481:	learn: 0.0031305	total: 6m 6s	remaining: 11m 25s
3328:	learn: 0.0032434	total: 6m 6s	remaining: 12m 13s
3583:	learn: 0.0030622	total: 6m 5s	remaining: 10m 54s
3572:	learn: 0.0025170	total: 6m 6s	remaining: 10m 58s
3635:	learn: 0.0027920	total: 6m 6s	remaining: 10m 40s
3482:	learn: 0.0031300	total: 6m 6s	remaining: 11m 24s
3329:	learn: 0.0032415	total: 6m 6s	remaining: 12m 13s
3584:	learn: 0.0030616	total: 6m 5s	remaining: 10m 54s
3636:	learn: 0.0027905	total: 6m 6s	remaining: 10m 40s
3573:	learn: 0.0025162	total: 6m 6s	remaining: 10m 58s
3483:	learn: 0.0031285	total: 6m 6s	remaining: 11m 24s
3330:	learn: 0.0032401	total: 6m 6s	remaining: 12m 13s
3637:	learn: 0.0027897	total: 6m 6s	remaining: 10m 40s
3585:	learn: 0.0030609	total: 6m 6s	remaining: 10m 54s
3574:	learn: 0.0025154	total: 6m 6s	remaining: 10m 58s
3484:	learn: 0.0031274	total: 6m 6s	remaining: 11m 24s
3331:	learn: 0.0032388	total: 6m 6s	remaining: 12m 13s
3638:	learn: 0.0027885	total: 6m 6s	remaining: 10m 40s
3586:	learn: 0.0030603	total: 6m 6s	remaining: 10m 54s
3575:	learn: 0.0025137	total: 6m 6s	remaining: 10m 58s
3485:	learn: 0.0031256	total: 6m 6s	remaining: 11m 24s
3332:	learn: 0.0032379	total: 6m 6s	remaining: 12m 13s
3587:	learn: 0.0030594	total: 6m 6s	remaining: 10m 54s
3639:	learn: 0.0027873	total: 6m 6s	remaining: 10m 40s
3486:	learn: 0.0031240	total: 6m 6s	remaining: 11m 24s
3576:	learn: 0.0025125	total: 6m 6s	remaining: 10m 58s
3588:	learn: 0.0030573	total: 6m 6s	remaining: 10m 54s
3333:	learn: 0.0032379	total: 6m 6s	remaining: 12m 12s
3640:	learn: 0.0027863	total: 6m 6s	remaining: 10m 40s
3487:	learn: 0.0031226	total: 6m 6s	remaining: 11m 24s
3577:	learn: 0.0025117	total: 6m 6s	remaining: 10m 58s
3334:	learn: 0.0032367	total: 6m 6s	remaining: 12m 12s
3589:	learn: 0.0030566	total: 6m 6s	remaining: 10m 54s
3488:	learn: 0.0031212	total: 6m 6s	remaining: 11m 24s
3641:	learn: 0.0027851	total: 6m 6s	remaining: 10m 40s
3578:	learn: 0.0025106	total: 6m 6s	remaining: 10m 57s
3642:	learn: 0.0027840	total: 6m 6s	remaining: 10m 40s

3335:	learn: 0.0032358	total: 6m 6s	remaining: 12m 12s
3489:	learn: 0.0031196	total: 6m 6s	remaining: 11m 24s
3590:	learn: 0.0030555	total: 6m 6s	remaining: 10m 54s
3579:	learn: 0.0025097	total: 6m 6s	remaining: 10m 57s
3490:	learn: 0.0031174	total: 6m 6s	remaining: 11m 23s
3336:	learn: 0.0032358	total: 6m 6s	remaining: 12m 12s
3643:	learn: 0.0027829	total: 6m 6s	remaining: 10m 39s
3580:	learn: 0.0025088	total: 6m 6s	remaining: 10m 57s
3591:	learn: 0.0030549	total: 6m 6s	remaining: 10m 54s
3644:	learn: 0.0027823	total: 6m 6s	remaining: 10m 39s
3581:	learn: 0.0025079	total: 6m 6s	remaining: 10m 57s
3337:	learn: 0.0032347	total: 6m 7s	remaining: 12m 12s
3592:	learn: 0.0030540	total: 6m 6s	remaining: 10m 54s
3491:	learn: 0.0031159	total: 6m 6s	remaining: 11m 23s
3582:	learn: 0.0025065	total: 6m 7s	remaining: 10m 57s
3645:	learn: 0.0027811	total: 6m 7s	remaining: 10m 39s
3338:	learn: 0.0032334	total: 6m 7s	remaining: 12m 12s
3492:	learn: 0.0031144	total: 6m 7s	remaining: 11m 23s
3593:	learn: 0.0030529	total: 6m 6s	remaining: 10m 54s
3583:	learn: 0.0025047	total: 6m 7s	remaining: 10m 57s
3646:	learn: 0.0027799	total: 6m 7s	remaining: 10m 39s
3339:	learn: 0.0032334	total: 6m 7s	remaining: 12m 12s
3493:	learn: 0.0031128	total: 6m 7s	remaining: 11m 23s
3594:	learn: 0.0030521	total: 6m 7s	remaining: 10m 53s
3584:	learn: 0.0025039	total: 6m 7s	remaining: 10m 57s
3647:	learn: 0.0027794	total: 6m 7s	remaining: 10m 39s
3340:	learn: 0.0032334	total: 6m 7s	remaining: 12m 12s
3494:	learn: 0.0031117	total: 6m 7s	remaining: 11m 23s
3595:	learn: 0.0030514	total: 6m 7s	remaining: 10m 53s
3648:	learn: 0.0027783	total: 6m 7s	remaining: 10m 39s
3585:	learn: 0.0025028	total: 6m 7s	remaining: 10m 57s
3341:	learn: 0.0032320	total: 6m 7s	remaining: 12m 11s
3495:	learn: 0.0031106	total: 6m 7s	remaining: 11m 23s
3596:	learn: 0.0030507	total: 6m 7s	remaining: 10m 53s
3649:	learn: 0.0027769	total: 6m 7s	remaining: 10m 39s
3586:	learn: 0.0025020	total: 6m 7s	remaining: 10m 56s
3342:	learn: 0.0032306	total: 6m 7s	remaining: 12m 11s
3496:	learn: 0.0031092	total: 6m 7s	remaining: 11m 23s
3597:	learn: 0.0030492	total: 6m 7s	remaining: 10m 53s
3650:	learn: 0.0027763	total: 6m 7s	remaining: 10m 39s
3587:	learn: 0.0025011	total: 6m 7s	remaining: 10m 56s
3343:	learn: 0.0032293	total: 6m 7s	remaining: 12m 11s
3497:	learn: 0.0031086	total: 6m 7s	remaining: 11m 23s
3598:	learn: 0.0030484	total: 6m 7s	remaining: 10m 53s
3651:	learn: 0.0027753	total: 6m 7s	remaining: 10m 39s
3498:	learn: 0.0031071	total: 6m 7s	remaining: 11m 23s
3344:	learn: 0.0032293	total: 6m 7s	remaining: 12m 11s
3588:	learn: 0.0025002	total: 6m 7s	remaining: 10m 56s
3599:	learn: 0.0030473	total: 6m 7s	remaining: 10m 53s
3652:	learn: 0.0027742	total: 6m 7s	remaining: 10m 38s
3499:	learn: 0.0031065	total: 6m 7s	remaining: 11m 22s
3589:	learn: 0.0024990	total: 6m 7s	remaining: 10m 56s
3345:	learn: 0.0032274	total: 6m 7s	remaining: 12m 11s
3500:	learn: 0.0031051	total: 6m 7s	remaining: 11m 22s
3600:	learn: 0.0030467	total: 6m 7s	remaining: 10m 53s
3653:	learn: 0.0027729	total: 6m 7s	remaining: 10m 38s
3590:	learn: 0.0024983	total: 6m 7s	remaining: 10m 56s
3346:	learn: 0.0032266	total: 6m 7s	remaining: 12m 11s
3654:	learn: 0.0027720	total: 6m 7s	remaining: 10m 38s
3501:	learn: 0.0031038	total: 6m 7s	remaining: 11m 22s
3601:	learn: 0.0030460	total: 6m 7s	remaining: 10m 53s
3347:	learn: 0.0032266	total: 6m 8s	remaining: 12m 11s
3591:	learn: 0.0024967	total: 6m 7s	remaining: 10m 56s
3502:	learn: 0.0031025	total: 6m 7s	remaining: 11m 22s
3655:	learn: 0.0027708	total: 6m 8s	remaining: 10m 38s
3348:	learn: 0.0032266	total: 6m 8s	remaining: 12m 11s
3602:	learn: 0.0030448	total: 6m 7s	remaining: 10m 53s
3503:	learn: 0.0031009	total: 6m 8s	remaining: 11m 22s
3592:	learn: 0.0024955	total: 6m 8s	remaining: 10m 56s
3656:	learn: 0.0027698	total: 6m 8s	remaining: 10m 38s
3349:	learn: 0.0032255	total: 6m 8s	remaining: 12m 10s
3504:	learn: 0.0031003	total: 6m 8s	remaining: 11m 22s
3603:	learn: 0.0030441	total: 6m 8s	remaining: 10m 53s
3593:	learn: 0.0024941	total: 6m 8s	remaining: 10m 56s
3657:	learn: 0.0027686	total: 6m 8s	remaining: 10m 38s
3350:	learn: 0.0032246	total: 6m 8s	remaining: 12m 10s
3505:	learn: 0.0030992	total: 6m 8s	remaining: 11m 22s
3604:	learn: 0.0030424	total: 6m 8s	remaining: 10m 53s
3351:	learn: 0.0032233	total: 6m 8s	remaining: 12m 10s
3658:	learn: 0.0027673	total: 6m 8s	remaining: 10m 38s
3594:	learn: 0.0024933	total: 6m 8s	remaining: 10m 56s
3506:	learn: 0.0030974	total: 6m 8s	remaining: 11m 21s
3605:	learn: 0.0030418	total: 6m 8s	remaining: 10m 52s
3659:	learn: 0.0027660	total: 6m 8s	remaining: 10m 38s
3352:	learn: 0.0032219	total: 6m 8s	remaining: 12m 10s
3595:	learn: 0.0024923	total: 6m 8s	remaining: 10m 56s
3507:	learn: 0.0030959	total: 6m 8s	remaining: 11m 21s
3606:	learn: 0.0030406	total: 6m 8s	remaining: 10m 52s
3508:	learn: 0.0030944	total: 6m 8s	remaining: 11m 21s
3353:	learn: 0.0032205	total: 6m 8s	remaining: 12m 10s
3660:	learn: 0.0027646	total: 6m 8s	remaining: 10m 38s
3596:	learn: 0.0024909	total: 6m 8s	remaining: 10m 56s
3607:	learn: 0.0030397	total: 6m 8s	remaining: 10m 52s
3509:	learn: 0.0030928	total: 6m 8s	remaining: 11m 21s
3608:	learn: 0.0030390	total: 6m 8s	remaining: 10m 52s
3597:	learn: 0.0024903	total: 6m 8s	remaining: 10m 55s
3661:	learn: 0.0027635	total: 6m 8s	remaining: 10m 38s
3354:	learn: 0.0032194	total: 6m 8s	remaining: 12m 10s
3510:	learn: 0.0030915	total: 6m 8s	remaining: 11m 21s
3609:	learn: 0.0030373	total: 6m 8s	remaining: 10m 52s
3662:	learn: 0.0027627	total: 6m 8s	remaining: 10m 37s
3511:	learn: 0.0030897	total: 6m 8s	remaining: 11m 21s
3598:	learn: 0.0024892	total: 6m 8s	remaining: 10m 55s
3355:	learn: 0.0032179	total: 6m 8s	remaining: 12m 10s
3610:	learn: 0.0030351	total: 6m 8s	remaining: 10m 52s
3663:	learn: 0.0027615	total: 6m 8s	remaining: 10m 37s
3599:	learn: 0.0024878	total: 6m 8s	remaining: 10m 55s
3512:	learn: 0.0030889	total: 6m 8s	remaining: 11m 21s
3356:	learn: 0.0032167	total: 6m 8s	remaining: 12m 10s
3611:	learn: 0.0030336	total: 6m 8s	remaining: 10m 52s
3664:	learn: 0.0027604	total: 6m 8s	remaining: 10m 37s
3600:	learn: 0.0024866	total: 6m 8s	remaining: 10m 55s
3513:	learn: 0.0030876	total: 6m 9s	remaining: 11m 21s
3612:	learn: 0.0030317	total: 6m 8s	remaining: 10m 52s
3357:	learn: 0.0032154	total: 6m 9s	remaining: 12m 9s
3601:	learn: 0.0024858	total: 6m 9s	remaining: 10m 55s
3665:	learn: 0.0027591	total: 6m 9s	remaining: 10m 37s
3514:	learn: 0.0030857	total: 6m 9s	remaining: 11m 20s
3358:	learn: 0.0032133	total: 6m 9s	remaining: 12m 9s
3613:	learn: 0.0030309	total: 6m 8s	remaining: 10m 51s
3666:	learn: 0.0027578	total: 6m 9s	remaining: 10m 37s
3602:	learn: 0.0024850	total: 6m 9s	remaining: 10m 55s
3515:	learn: 0.0030850	total: 6m 9s	remaining: 11m 20s
3359:	learn: 0.0032113	total: 6m 9s	remaining: 12m 9s
3614:	learn: 0.0030300	total: 6m 9s	remaining: 10m 51s
3667:	learn: 0.0027565	total: 6m 9s	remaining: 10m 37s
3603:	learn: 0.0024838	total: 6m 9s	remaining: 10m 55s
3516:	learn: 0.0030833	total: 6m 9s	remaining: 11m 20s
3360:	learn: 0.0032103	total: 6m 9s	remaining: 12m 9s
3615:	learn: 0.0030290	total: 6m 9s	remaining: 10m 51s
3668:	learn: 0.0027551	total: 6m 9s	remaining: 10m 37s
3361:	learn: 0.0032097	total: 6m 9s	remaining: 12m 9s
3604:	learn: 0.0024829	total: 6m 9s	remaining: 10m 55s
3517:	learn: 0.0030812	total: 6m 9s	remaining: 11m 20s
3616:	learn: 0.0030275	total: 6m 9s	remaining: 10m 51s
3669:	learn: 0.0027540	total: 6m 9s	remaining: 10m 37s
3362:	learn: 0.0032077	total: 6m 9s	remaining: 12m 9s
3605:	learn: 0.0024819	total: 6m 9s	remaining: 10m 55s
3670:	learn: 0.0027528	total: 6m 9s	remaining: 10m 37s
3518:	learn: 0.0030792	total: 6m 9s	remaining: 11m 20s
3617:	learn: 0.0030262	total: 6m 9s	remaining: 10m 51s
3606:	learn: 0.0024806	total: 6m 9s	remaining: 10m 54s
3363:	learn: 0.0032065	total: 6m 9s	remaining: 12m 9s
3671:	learn: 0.0027516	total: 6m 9s	remaining: 10m 37s
3618:	learn: 0.0030252	total: 6m 9s	remaining: 10m 51s
3607:	learn: 0.0024795	total: 6m 9s	remaining: 10m 54s
3519:	learn: 0.0030774	total: 6m 9s	remaining: 11m 20s
3364:	learn: 0.0032050	total: 6m 9s	remaining: 12m 9s
3619:	learn: 0.0030245	total: 6m 9s	remaining: 10m 51s
3672:	learn: 0.0027503	total: 6m 9s	remaining: 10m 36s
3608:	learn: 0.0024787	total: 6m 9s	remaining: 10m 54s
3365:	learn: 0.0032041	total: 6m 9s	remaining: 12m 8s
3520:	learn: 0.0030760	total: 6m 9s	remaining: 11m 20s
3673:	learn: 0.0027494	total: 6m 9s	remaining: 10m 36s
3620:	learn: 0.0030238	total: 6m 9s	remaining: 10m 51s
3609:	learn: 0.0024776	total: 6m 9s	remaining: 10m 54s
3366:	learn: 0.0032031	total: 6m 9s	remaining: 12m 8s
3621:	learn: 0.0030222	total: 6m 9s	remaining: 10m 51s
3610:	learn: 0.0024764	total: 6m 9s	remaining: 10m 54s
3674:	learn: 0.0027482	total: 6m 9s	remaining: 10m 36s
3521:	learn: 0.0030752	total: 6m 9s	remaining: 11m 20s
3367:	learn: 0.0032022	total: 6m 10s	remaining: 12m 8s
3611:	learn: 0.0024751	total: 6m 9s	remaining: 10m 54s
3622:	learn: 0.0030204	total: 6m 9s	remaining: 10m 51s
3522:	learn: 0.0030735	total: 6m 10s	remaining: 11m 20s
3675:	learn: 0.0027465	total: 6m 10s	remaining: 10m 36s
3612:	learn: 0.0024742	total: 6m 10s	remaining: 10m 54s
3623:	learn: 0.0030188	total: 6m 9s	remaining: 10m 50s
3368:	learn: 0.0032009	total: 6m 10s	remaining: 12m 8s
3676:	learn: 0.0027456	total: 6m 10s	remaining: 10m 36s
3523:	learn: 0.0030722	total: 6m 10s	remaining: 11m 20s
3613:	learn: 0.0024726	total: 6m 10s	remaining: 10m 54s
3624:	learn: 0.0030182	total: 6m 10s	remaining: 10m 50s
3369:	learn: 0.0031992	total: 6m 10s	remaining: 12m 8s
3614:	learn: 0.0024715	total: 6m 10s	remaining: 10m 53s
3677:	learn: 0.0027443	total: 6m 10s	remaining: 10m 36s
3524:	learn: 0.0030706	total: 6m 10s	remaining: 11m 20s
3625:	learn: 0.0030167	total: 6m 10s	remaining: 10m 50s
3370:	learn: 0.0031974	total: 6m 10s	remaining: 12m 8s
3615:	learn: 0.0024701	total: 6m 10s	remaining: 10m 53s
3678:	learn: 0.0027433	total: 6m 10s	remaining: 10m 36s
3525:	learn: 0.0030692	total: 6m 10s	remaining: 11m 19s
3626:	learn: 0.0030160	total: 6m 10s	remaining: 10m 50s
3371:	learn: 0.0031963	total: 6m 10s	remaining: 12m 8s
3679:	learn: 0.0027424	total: 6m 10s	remaining: 10m 36s
3616:	learn: 0.0024690	total: 6m 10s	remaining: 10m 53s
3526:	learn: 0.0030678	total: 6m 10s	remaining: 11m 19s
3627:	learn: 0.0030154	total: 6m 10s	remaining: 10m 50s
3680:	learn: 0.0027417	total: 6m 10s	remaining: 10m 36s
3617:	learn: 0.0024681	total: 6m 10s	remaining: 10m 53s
3372:	learn: 0.0031953	total: 6m 10s	remaining: 12m 8s
3681:	learn: 0.0027402	total: 6m 10s	remaining: 10m 35s
3527:	learn: 0.0030658	total: 6m 10s	remaining: 11m 19s
3628:	learn: 0.0030147	total: 6m 10s	remaining: 10m 50s
3618:	learn: 0.0024674	total: 6m 10s	remaining: 10m 53s
3528:	learn: 0.0030652	total: 6m 10s	remaining: 11m 19s
3682:	learn: 0.0027389	total: 6m 10s	remaining: 10m 35s
3629:	learn: 0.0030127	total: 6m 10s	remaining: 10m 50s
3619:	learn: 0.0024666	total: 6m 10s	remaining: 10m 53s
3373:	learn: 0.0031939	total: 6m 10s	remaining: 12m 8s
3529:	learn: 0.0030639	total: 6m 10s	remaining: 11m 19s
3683:	learn: 0.0027377	total: 6m 10s	remaining: 10m 35s
3630:	learn: 0.0030113	total: 6m 10s	remaining: 10m 50s
3374:	learn: 0.0031922	total: 6m 10s	remaining: 12m 8s
3620:	learn: 0.0024657	total: 6m 10s	remaining: 10m 53s
3530:	learn: 0.0030625	total: 6m 10s	remaining: 11m 19s
3684:	learn: 0.0027362	total: 6m 10s	remaining: 10m 35s
3631:	learn: 0.0030104	total: 6m 10s	remaining: 10m 50s
3531:	learn: 0.0030605	total: 6m 10s	remaining: 11m 19s
3685:	learn: 0.0027347	total: 6m 10s	remaining: 10m 35s
3621:	learn: 0.0024641	total: 6m 10s	remaining: 10m 53s
3375:	learn: 0.0031922	total: 6m 11s	remaining: 12m 7s
3622:	learn: 0.0024633	total: 6m 11s	remaining: 10m 53s
3632:	learn: 0.0030093	total: 6m 10s	remaining: 10m 49s
3532:	learn: 0.0030600	total: 6m 11s	remaining: 11m 19s
3686:	learn: 0.0027336	total: 6m 11s	remaining: 10m 35s
3623:	learn: 0.0024624	total: 6m 11s	remaining: 10m 52s
3376:	learn: 0.0031913	total: 6m 11s	remaining: 12m 7s
3633:	learn: 0.0030078	total: 6m 10s	remaining: 10m 49s
3533:	learn: 0.0030591	total: 6m 11s	remaining: 11m 19s
3687:	learn: 0.0027327	total: 6m 11s	remaining: 10m 35s
3624:	learn: 0.0024616	total: 6m 11s	remaining: 10m 52s
3377:	learn: 0.0031913	total: 6m 11s	remaining: 12m 7s
3634:	learn: 0.0030062	total: 6m 11s	remaining: 10m 49s
3688:	learn: 0.0027314	total: 6m 11s	remaining: 10m 35s
3534:	learn: 0.0030586	total: 6m 11s	remaining: 11m 19s
3635:	learn: 0.0030055	total: 6m 11s	remaining: 10m 49s
3625:	learn: 0.0024608	total: 6m 11s	remaining: 10m 52s
3378:	learn: 0.0031903	total: 6m 11s	remaining: 12m 7s
3689:	learn: 0.0027304	total: 6m 11s	remaining: 10m 35s
3535:	learn: 0.0030572	total: 6m 11s	remaining: 11m 18s
3636:	learn: 0.0030036	total: 6m 11s	remaining: 10m 49s
3626:	learn: 0.0024600	total: 6m 11s	remaining: 10m 52s
3379:	learn: 0.0031892	total: 6m 11s	remaining: 12m 7s
3690:	learn: 0.0027291	total: 6m 11s	remaining: 10m 34s
3536:	learn: 0.0030555	total: 6m 11s	remaining: 11m 18s
3637:	learn: 0.0030030	total: 6m 11s	remaining: 10m 49s
3380:	learn: 0.0031881	total: 6m 11s	remaining: 12m 7s
3627:	learn: 0.0024589	total: 6m 11s	remaining: 10m 52s
3537:	learn: 0.0030538	total: 6m 11s	remaining: 11m 18s
3691:	learn: 0.0027279	total: 6m 11s	remaining: 10m 34s
3638:	learn: 0.0030023	total: 6m 11s	remaining: 10m 49s
3628:	learn: 0.0024580	total: 6m 11s	remaining: 10m 52s
3381:	learn: 0.0031869	total: 6m 11s	remaining: 12m 7s
3692:	learn: 0.0027270	total: 6m 11s	remaining: 10m 34s
3538:	learn: 0.0030529	total: 6m 11s	remaining: 11m 18s
3639:	learn: 0.0030008	total: 6m 11s	remaining: 10m 49s
3629:	learn: 0.0024570	total: 6m 11s	remaining: 10m 52s
3382:	learn: 0.0031859	total: 6m 11s	remaining: 12m 7s
3693:	learn: 0.0027257	total: 6m 11s	remaining: 10m 34s
3539:	learn: 0.0030509	total: 6m 11s	remaining: 11m 18s
3630:	learn: 0.0024562	total: 6m 11s	remaining: 10m 52s
3640:	learn: 0.0029991	total: 6m 11s	remaining: 10m 49s
3694:	learn: 0.0027245	total: 6m 11s	remaining: 10m 34s
3383:	learn: 0.0031849	total: 6m 11s	remaining: 12m 7s
3540:	learn: 0.0030496	total: 6m 11s	remaining: 11m 18s
3631:	learn: 0.0024554	total: 6m 11s	remaining: 10m 52s
3695:	learn: 0.0027231	total: 6m 11s	remaining: 10m 34s
3641:	learn: 0.0029983	total: 6m 11s	remaining: 10m 49s
3384:	learn: 0.0031841	total: 6m 11s	remaining: 12m 6s
3632:	learn: 0.0024546	total: 6m 11s	remaining: 10m 51s
3541:	learn: 0.0030483	total: 6m 12s	remaining: 11m 18s
3642:	learn: 0.0029975	total: 6m 11s	remaining: 10m 48s
3696:	learn: 0.0027218	total: 6m 12s	remaining: 10m 34s
3385:	learn: 0.0031829	total: 6m 12s	remaining: 12m 6s
3633:	learn: 0.0024539	total: 6m 12s	remaining: 10m 51s
3386:	learn: 0.0031816	total: 6m 12s	remaining: 12m 6s
3697:	learn: 0.0027208	total: 6m 12s	remaining: 10m 34s
3643:	learn: 0.0029968	total: 6m 11s	remaining: 10m 48s
3542:	learn: 0.0030469	total: 6m 12s	remaining: 11m 18s
3698:	learn: 0.0027195	total: 6m 12s	remaining: 10m 34s
3634:	learn: 0.0024531	total: 6m 12s	remaining: 10m 51s
3644:	learn: 0.0029955	total: 6m 12s	remaining: 10m 48s
3387:	learn: 0.0031803	total: 6m 12s	remaining: 12m 6s
3543:	learn: 0.0030449	total: 6m 12s	remaining: 11m 18s
3635:	learn: 0.0024520	total: 6m 12s	remaining: 10m 51s
3645:	learn: 0.0029940	total: 6m 12s	remaining: 10m 48s
3699:	learn: 0.0027181	total: 6m 12s	remaining: 10m 33s
3388:	learn: 0.0031801	total: 6m 12s	remaining: 12m 6s
3636:	learn: 0.0024512	total: 6m 12s	remaining: 10m 51s
3544:	learn: 0.0030433	total: 6m 12s	remaining: 11m 18s
3646:	learn: 0.0029928	total: 6m 12s	remaining: 10m 48s
3700:	learn: 0.0027174	total: 6m 12s	remaining: 10m 33s
3637:	learn: 0.0024504	total: 6m 12s	remaining: 10m 51s
3545:	learn: 0.0030422	total: 6m 12s	remaining: 11m 17s
3389:	learn: 0.0031787	total: 6m 12s	remaining: 12m 6s
3647:	learn: 0.0029920	total: 6m 12s	remaining: 10m 48s
3638:	learn: 0.0024496	total: 6m 12s	remaining: 10m 51s
3701:	learn: 0.0027159	total: 6m 12s	remaining: 10m 33s
3390:	learn: 0.0031769	total: 6m 12s	remaining: 12m 6s
3546:	learn: 0.0030411	total: 6m 12s	remaining: 11m 17s
3648:	learn: 0.0029899	total: 6m 12s	remaining: 10m 48s
3702:	learn: 0.0027142	total: 6m 12s	remaining: 10m 33s
3639:	learn: 0.0024489	total: 6m 12s	remaining: 10m 51s
3649:	learn: 0.0029879	total: 6m 12s	remaining: 10m 48s
3391:	learn: 0.0031769	total: 6m 12s	remaining: 12m 6s

3547:	learn: 0.0030397	total: 6m 12s	remaining: 11m 17s
3703:	learn: 0.0027131	total: 6m 12s	remaining: 10m 33s
3392:	learn: 0.0031747	total: 6m 12s	remaining: 12m 5s
3650:	learn: 0.0029867	total: 6m 12s	remaining: 10m 47s
3548:	learn: 0.0030378	total: 6m 12s	remaining: 11m 17s
3640:	learn: 0.0024476	total: 6m 12s	remaining: 10m 51s
3393:	learn: 0.0031738	total: 6m 12s	remaining: 12m 5s
3704:	learn: 0.0027121	total: 6m 12s	remaining: 10m 33s
3651:	learn: 0.0029851	total: 6m 12s	remaining: 10m 47s
3641:	learn: 0.0024461	total: 6m 12s	remaining: 10m 50s
3549:	learn: 0.0030366	total: 6m 12s	remaining: 11m 17s
3652:	learn: 0.0029844	total: 6m 12s	remaining: 10m 47s
3705:	learn: 0.0027112	total: 6m 12s	remaining: 10m 33s
3394:	learn: 0.0031726	total: 6m 13s	remaining: 12m 5s
3642:	learn: 0.0024454	total: 6m 12s	remaining: 10m 50s
3550:	learn: 0.0030352	total: 6m 12s	remaining: 11m 17s
3706:	learn: 0.0027100	total: 6m 13s	remaining: 10m 33s
3643:	learn: 0.0024446	total: 6m 13s	remaining: 10m 50s
3653:	learn: 0.0029831	total: 6m 12s	remaining: 10m 47s
3395:	learn: 0.0031715	total: 6m 13s	remaining: 12m 5s
3551:	learn: 0.0030346	total: 6m 13s	remaining: 11m 17s
3707:	learn: 0.0027085	total: 6m 13s	remaining: 10m 33s
3552:	learn: 0.0030333	total: 6m 13s	remaining: 11m 17s
3654:	learn: 0.0029814	total: 6m 13s	remaining: 10m 47s
3644:	learn: 0.0024439	total: 6m 13s	remaining: 10m 50s
3396:	learn: 0.0031698	total: 6m 13s	remaining: 12m 5s
3708:	learn: 0.0027075	total: 6m 13s	remaining: 10m 33s
3709:	learn: 0.0027063	total: 6m 13s	remaining: 10m 32s
3553:	learn: 0.0030316	total: 6m 13s	remaining: 11m 17s
3655:	learn: 0.0029805	total: 6m 13s	remaining: 10m 47s
3645:	learn: 0.0024427	total: 6m 13s	remaining: 10m 50s
3397:	learn: 0.0031690	total: 6m 13s	remaining: 12m 5s
3710:	learn: 0.0027047	total: 6m 13s	remaining: 10m 32s
3656:	learn: 0.0029788	total: 6m 13s	remaining: 10m 47s
3646:	learn: 0.0024419	total: 6m 13s	remaining: 10m 50s
3554:	learn: 0.0030295	total: 6m 13s	remaining: 11m 16s
3398:	learn: 0.0031682	total: 6m 13s	remaining: 12m 5s
3711:	learn: 0.0027034	total: 6m 13s	remaining: 10m 32s
3657:	learn: 0.0029774	total: 6m 13s	remaining: 10m 47s
3647:	learn: 0.0024407	total: 6m 13s	remaining: 10m 50s
3555:	learn: 0.0030287	total: 6m 13s	remaining: 11m 16s
3399:	learn: 0.0031664	total: 6m 13s	remaining: 12m 5s
3712:	learn: 0.0027022	total: 6m 13s	remaining: 10m 32s
3658:	learn: 0.0029762	total: 6m 13s	remaining: 10m 47s
3648:	learn: 0.0024397	total: 6m 13s	remaining: 10m 50s
3556:	learn: 0.0030271	total: 6m 13s	remaining: 11m 16s
3400:	learn: 0.0031664	total: 6m 13s	remaining: 12m 5s
3713:	learn: 0.0027008	total: 6m 13s	remaining: 10m 32s
3659:	learn: 0.0029744	total: 6m 13s	remaining: 10m 47s
3557:	learn: 0.0030257	total: 6m 13s	remaining: 11m 16s
3649:	learn: 0.0024382	total: 6m 13s	remaining: 10m 50s
3714:	learn: 0.0026992	total: 6m 13s	remaining: 10m 32s
3401:	learn: 0.0031656	total: 6m 13s	remaining: 12m 4s
3558:	learn: 0.0030238	total: 6m 13s	remaining: 11m 16s
3660:	learn: 0.0029737	total: 6m 13s	remaining: 10m 46s
3650:	learn: 0.0024374	total: 6m 13s	remaining: 10m 50s
3715:	learn: 0.0026980	total: 6m 13s	remaining: 10m 32s
3402:	learn: 0.0031647	total: 6m 13s	remaining: 12m 4s
3661:	learn: 0.0029730	total: 6m 13s	remaining: 10m 46s
3651:	learn: 0.0024364	total: 6m 13s	remaining: 10m 49s
3559:	learn: 0.0030221	total: 6m 13s	remaining: 11m 16s
3716:	learn: 0.0026970	total: 6m 13s	remaining: 10m 32s
3662:	learn: 0.0029723	total: 6m 13s	remaining: 10m 46s
3403:	learn: 0.0031633	total: 6m 14s	remaining: 12m 4s
3652:	learn: 0.0024357	total: 6m 13s	remaining: 10m 49s
3717:	learn: 0.0026959	total: 6m 14s	remaining: 10m 31s
3560:	learn: 0.0030201	total: 6m 14s	remaining: 11m 16s
3663:	learn: 0.0029717	total: 6m 13s	remaining: 10m 46s
3404:	learn: 0.0031625	total: 6m 14s	remaining: 12m 4s
3653:	learn: 0.0024348	total: 6m 14s	remaining: 10m 49s
3718:	learn: 0.0026948	total: 6m 14s	remaining: 10m 31s
3664:	learn: 0.0029707	total: 6m 13s	remaining: 10m 46s
3405:	learn: 0.0031617	total: 6m 14s	remaining: 12m 4s
3561:	learn: 0.0030182	total: 6m 14s	remaining: 11m 16s
3654:	learn: 0.0024341	total: 6m 14s	remaining: 10m 49s
3719:	learn: 0.0026933	total: 6m 14s	remaining: 10m 31s
3406:	learn: 0.0031617	total: 6m 14s	remaining: 12m 4s
3665:	learn: 0.0029701	total: 6m 14s	remaining: 10m 46s
3655:	learn: 0.0024328	total: 6m 14s	remaining: 10m 49s
3562:	learn: 0.0030169	total: 6m 14s	remaining: 11m 16s
3720:	learn: 0.0026924	total: 6m 14s	remaining: 10m 31s
3666:	learn: 0.0029695	total: 6m 14s	remaining: 10m 46s
3407:	learn: 0.0031608	total: 6m 14s	remaining: 12m 4s
3563:	learn: 0.0030156	total: 6m 14s	remaining: 11m 16s
3656:	learn: 0.0024320	total: 6m 14s	remaining: 10m 49s
3721:	learn: 0.0026915	total: 6m 14s	remaining: 10m 31s
3667:	learn: 0.0029678	total: 6m 14s	remaining: 10m 46s
3564:	learn: 0.0030150	total: 6m 14s	remaining: 11m 15s
3657:	learn: 0.0024311	total: 6m 14s	remaining: 10m 49s
3668:	learn: 0.0029663	total: 6m 14s	remaining: 10m 45s
3408:	learn: 0.0031598	total: 6m 14s	remaining: 12m 4s
3722:	learn: 0.0026904	total: 6m 14s	remaining: 10m 31s
3669:	learn: 0.0029648	total: 6m 14s	remaining: 10m 45s
3409:	learn: 0.0031583	total: 6m 14s	remaining: 12m 3s
3565:	learn: 0.0030140	total: 6m 14s	remaining: 11m 15s
3658:	learn: 0.0024304	total: 6m 14s	remaining: 10m 49s
3723:	learn: 0.0026892	total: 6m 14s	remaining: 10m 31s
3410:	learn: 0.0031569	total: 6m 14s	remaining: 12m 3s
3670:	learn: 0.0029641	total: 6m 14s	remaining: 10m 45s
3566:	learn: 0.0030125	total: 6m 14s	remaining: 11m 15s
3724:	learn: 0.0026879	total: 6m 14s	remaining: 10m 31s
3659:	learn: 0.0024294	total: 6m 14s	remaining: 10m 49s
3411:	learn: 0.0031560	total: 6m 14s	remaining: 12m 3s
3567:	learn: 0.0030106	total: 6m 14s	remaining: 11m 15s
3725:	learn: 0.0026872	total: 6m 14s	remaining: 10m 31s
3671:	learn: 0.0029630	total: 6m 14s	remaining: 10m 45s
3660:	learn: 0.0024287	total: 6m 14s	remaining: 10m 48s
3412:	learn: 0.0031546	total: 6m 14s	remaining: 12m 3s
3726:	learn: 0.0026857	total: 6m 14s	remaining: 10m 31s
3672:	learn: 0.0029620	total: 6m 14s	remaining: 10m 45s
3568:	learn: 0.0030084	total: 6m 14s	remaining: 11m 15s
3413:	learn: 0.0031534	total: 6m 14s	remaining: 12m 3s
3661:	learn: 0.0024279	total: 6m 14s	remaining: 10m 48s
3727:	learn: 0.0026847	total: 6m 15s	remaining: 10m 30s
3569:	learn: 0.0030075	total: 6m 14s	remaining: 11m 15s
3673:	learn: 0.0029612	total: 6m 14s	remaining: 10m 45s
3414:	learn: 0.0031523	total: 6m 15s	remaining: 12m 3s
3662:	learn: 0.0024272	total: 6m 15s	remaining: 10m 48s
3728:	learn: 0.0026834	total: 6m 15s	remaining: 10m 30s
3570:	learn: 0.0030058	total: 6m 15s	remaining: 11m 15s
3674:	learn: 0.0029601	total: 6m 14s	remaining: 10m 45s
3663:	learn: 0.0024264	total: 6m 15s	remaining: 10m 48s
3415:	learn: 0.0031512	total: 6m 15s	remaining: 12m 3s
3729:	learn: 0.0026824	total: 6m 15s	remaining: 10m 30s
3571:	learn: 0.0030039	total: 6m 15s	remaining: 11m 15s
3664:	learn: 0.0024257	total: 6m 15s	remaining: 10m 48s
3675:	learn: 0.0029583	total: 6m 15s	remaining: 10m 45s
3730:	learn: 0.0026815	total: 6m 15s	remaining: 10m 30s
3416:	learn: 0.0031493	total: 6m 15s	remaining: 12m 3s
3572:	learn: 0.0030028	total: 6m 15s	remaining: 11m 15s
3731:	learn: 0.0026806	total: 6m 15s	remaining: 10m 30s
3676:	learn: 0.0029568	total: 6m 15s	remaining: 10m 45s
3665:	learn: 0.0024246	total: 6m 15s	remaining: 10m 48s
3417:	learn: 0.0031484	total: 6m 15s	remaining: 12m 2s
3573:	learn: 0.0030023	total: 6m 15s	remaining: 11m 14s
3732:	learn: 0.0026797	total: 6m 15s	remaining: 10m 30s
3677:	learn: 0.0029563	total: 6m 15s	remaining: 10m 45s
3666:	learn: 0.0024239	total: 6m 15s	remaining: 10m 48s
3418:	learn: 0.0031476	total: 6m 15s	remaining: 12m 2s
3574:	learn: 0.0030009	total: 6m 15s	remaining: 11m 14s
3733:	learn: 0.0026786	total: 6m 15s	remaining: 10m 30s
3678:	learn: 0.0029547	total: 6m 15s	remaining: 10m 44s
3667:	learn: 0.0024227	total: 6m 15s	remaining: 10m 48s
3734:	learn: 0.0026771	total: 6m 15s	remaining: 10m 30s
3575:	learn: 0.0029993	total: 6m 15s	remaining: 11m 14s
3419:	learn: 0.0031459	total: 6m 15s	remaining: 12m 2s
3679:	learn: 0.0029527	total: 6m 15s	remaining: 10m 44s
3735:	learn: 0.0026760	total: 6m 15s	remaining: 10m 29s
3668:	learn: 0.0024213	total: 6m 15s	remaining: 10m 48s
3576:	learn: 0.0029972	total: 6m 15s	remaining: 11m 14s
3669:	learn: 0.0024200	total: 6m 15s	remaining: 10m 48s
3420:	learn: 0.0031453	total: 6m 15s	remaining: 12m 2s
3680:	learn: 0.0029509	total: 6m 15s	remaining: 10m 44s
3736:	learn: 0.0026748	total: 6m 15s	remaining: 10m 29s
3577:	learn: 0.0029958	total: 6m 15s	remaining: 11m 14s
3670:	learn: 0.0024186	total: 6m 15s	remaining: 10m 47s
3681:	learn: 0.0029499	total: 6m 15s	remaining: 10m 44s
3421:	learn: 0.0031444	total: 6m 15s	remaining: 12m 2s
3737:	learn: 0.0026736	total: 6m 15s	remaining: 10m 29s
3578:	learn: 0.0029946	total: 6m 15s	remaining: 11m 14s
3671:	learn: 0.0024175	total: 6m 15s	remaining: 10m 47s
3682:	learn: 0.0029489	total: 6m 15s	remaining: 10m 44s
3738:	learn: 0.0026722	total: 6m 15s	remaining: 10m 29s
3579:	learn: 0.0029934	total: 6m 15s	remaining: 11m 14s
3422:	learn: 0.0031437	total: 6m 16s	remaining: 12m 2s
3739:	learn: 0.0026708	total: 6m 16s	remaining: 10m 29s
3672:	learn: 0.0024163	total: 6m 16s	remaining: 10m 47s
3683:	learn: 0.0029482	total: 6m 15s	remaining: 10m 44s
3580:	learn: 0.0029923	total: 6m 16s	remaining: 11m 14s
3423:	learn: 0.0031414	total: 6m 16s	remaining: 12m 2s
3740:	learn: 0.0026694	total: 6m 16s	remaining: 10m 29s
3673:	learn: 0.0024153	total: 6m 16s	remaining: 10m 47s
3581:	learn: 0.0029916	total: 6m 16s	remaining: 11m 13s
3684:	learn: 0.0029471	total: 6m 16s	remaining: 10m 44s
3424:	learn: 0.0031399	total: 6m 16s	remaining: 12m 2s
3674:	learn: 0.0024139	total: 6m 16s	remaining: 10m 47s
3741:	learn: 0.0026681	total: 6m 16s	remaining: 10m 29s
3685:	learn: 0.0029460	total: 6m 16s	remaining: 10m 44s
3582:	learn: 0.0029900	total: 6m 16s	remaining: 11m 13s
3425:	learn: 0.0031387	total: 6m 16s	remaining: 12m 2s
3675:	learn: 0.0024131	total: 6m 16s	remaining: 10m 47s
3742:	learn: 0.0026666	total: 6m 16s	remaining: 10m 29s
3686:	learn: 0.0029449	total: 6m 16s	remaining: 10m 44s
3583:	learn: 0.0029884	total: 6m 16s	remaining: 11m 13s
3676:	learn: 0.0024120	total: 6m 16s	remaining: 10m 47s
3426:	learn: 0.0031379	total: 6m 16s	remaining: 12m 2s
3743:	learn: 0.0026653	total: 6m 16s	remaining: 10m 29s
3584:	learn: 0.0029879	total: 6m 16s	remaining: 11m 13s
3687:	learn: 0.0029438	total: 6m 16s	remaining: 10m 44s
3744:	learn: 0.0026645	total: 6m 16s	remaining: 10m 28s
3677:	learn: 0.0024104	total: 6m 16s	remaining: 10m 47s
3427:	learn: 0.0031369	total: 6m 16s	remaining: 12m 1s
3585:	learn: 0.0029869	total: 6m 16s	remaining: 11m 13s
3688:	learn: 0.0029419	total: 6m 16s	remaining: 10m 43s
3745:	learn: 0.0026637	total: 6m 16s	remaining: 10m 28s
3428:	learn: 0.0031357	total: 6m 16s	remaining: 12m 1s
3678:	learn: 0.0024092	total: 6m 16s	remaining: 10m 47s
3586:	learn: 0.0029856	total: 6m 16s	remaining: 11m 13s
3689:	learn: 0.0029409	total: 6m 16s	remaining: 10m 43s
3429:	learn: 0.0031336	total: 6m 16s	remaining: 12m 1s
3746:	learn: 0.0026624	total: 6m 16s	remaining: 10m 28s
3679:	learn: 0.0024081	total: 6m 16s	remaining: 10m 46s
3587:	learn: 0.0029844	total: 6m 16s	remaining: 11m 13s
3430:	learn: 0.0031321	total: 6m 16s	remaining: 12m 1s
3690:	learn: 0.0029399	total: 6m 16s	remaining: 10m 43s
3747:	learn: 0.0026615	total: 6m 16s	remaining: 10m 28s
3680:	learn: 0.0024074	total: 6m 16s	remaining: 10m 46s
3691:	learn: 0.0029381	total: 6m 16s	remaining: 10m 43s
3588:	learn: 0.0029823	total: 6m 16s	remaining: 11m 13s
3748:	learn: 0.0026608	total: 6m 16s	remaining: 10m 28s
3431:	learn: 0.0031301	total: 6m 16s	remaining: 12m 1s
3681:	learn: 0.0024064	total: 6m 16s	remaining: 10m 46s
3749:	learn: 0.0026597	total: 6m 16s	remaining: 10m 28s
3692:	learn: 0.0029365	total: 6m 16s	remaining: 10m 43s
3589:	learn: 0.0029807	total: 6m 16s	remaining: 11m 13s
3432:	learn: 0.0031285	total: 6m 17s	remaining: 12m 1s
3750:	learn: 0.0026586	total: 6m 17s	remaining: 10m 28s
3693:	learn: 0.0029353	total: 6m 16s	remaining: 10m 43s
3682:	learn: 0.0024053	total: 6m 17s	remaining: 10m 46s
3590:	learn: 0.0029801	total: 6m 17s	remaining: 11m 12s
3433:	learn: 0.0031268	total: 6m 17s	remaining: 12m 1s
3751:	learn: 0.0026575	total: 6m 17s	remaining: 10m 28s
3694:	learn: 0.0029341	total: 6m 17s	remaining: 10m 43s
3683:	learn: 0.0024042	total: 6m 17s	remaining: 10m 46s
3591:	learn: 0.0029788	total: 6m 17s	remaining: 11m 12s
3434:	learn: 0.0031252	total: 6m 17s	remaining: 12m 1s
3695:	learn: 0.0029327	total: 6m 17s	remaining: 10m 43s
3752:	learn: 0.0026562	total: 6m 17s	remaining: 10m 28s
3435:	learn: 0.0031241	total: 6m 17s	remaining: 12m
3592:	learn: 0.0029774	total: 6m 17s	remaining: 11m 12s
3684:	learn: 0.0024031	total: 6m 17s	remaining: 10m 46s
3696:	learn: 0.0029316	total: 6m 17s	remaining: 10m 43s
3753:	learn: 0.0026554	total: 6m 17s	remaining: 10m 27s
3685:	learn: 0.0024018	total: 6m 17s	remaining: 10m 46s
3436:	learn: 0.0031219	total: 6m 17s	remaining: 12m
3697:	learn: 0.0029298	total: 6m 17s	remaining: 10m 42s
3593:	learn: 0.0029761	total: 6m 17s	remaining: 11m 12s
3754:	learn: 0.0026544	total: 6m 17s	remaining: 10m 27s
3686:	learn: 0.0024006	total: 6m 17s	remaining: 10m 46s
3437:	learn: 0.0031205	total: 6m 17s	remaining: 12m
3594:	learn: 0.0029743	total: 6m 17s	remaining: 11m 12s
3698:	learn: 0.0029288	total: 6m 17s	remaining: 10m 42s
3687:	learn: 0.0023993	total: 6m 17s	remaining: 10m 46s
3755:	learn: 0.0026531	total: 6m 17s	remaining: 10m 27s
3595:	learn: 0.0029730	total: 6m 17s	remaining: 11m 12s
3438:	learn: 0.0031185	total: 6m 17s	remaining: 12m
3699:	learn: 0.0029278	total: 6m 17s	remaining: 10m 42s
3688:	learn: 0.0023984	total: 6m 17s	remaining: 10m 46s
3756:	learn: 0.0026522	total: 6m 17s	remaining: 10m 27s
3439:	learn: 0.0031168	total: 6m 17s	remaining: 12m
3689:	learn: 0.0023975	total: 6m 17s	remaining: 10m 45s
3596:	learn: 0.0029721	total: 6m 17s	remaining: 11m 12s
3700:	learn: 0.0029264	total: 6m 17s	remaining: 10m 42s
3757:	learn: 0.0026512	total: 6m 17s	remaining: 10m 27s
3690:	learn: 0.0023967	total: 6m 17s	remaining: 10m 45s
3597:	learn: 0.0029713	total: 6m 17s	remaining: 11m 12s
3440:	learn: 0.0031158	total: 6m 17s	remaining: 12m
3701:	learn: 0.0029250	total: 6m 17s	remaining: 10m 42s
3758:	learn: 0.0026503	total: 6m 17s	remaining: 10m 27s
3691:	learn: 0.0023953	total: 6m 17s	remaining: 10m 45s
3598:	learn: 0.0029701	total: 6m 17s	remaining: 11m 12s
3702:	learn: 0.0029239	total: 6m 17s	remaining: 10m 42s
3759:	learn: 0.0026491	total: 6m 17s	remaining: 10m 27s
3441:	learn: 0.0031143	total: 6m 18s	remaining: 12m
3692:	learn: 0.0023943	total: 6m 17s	remaining: 10m 45s
3703:	learn: 0.0029231	total: 6m 17s	remaining: 10m 42s
3599:	learn: 0.0029689	total: 6m 18s	remaining: 11m 12s
3760:	learn: 0.0026476	total: 6m 18s	remaining: 10m 27s
3442:	learn: 0.0031134	total: 6m 18s	remaining: 12m
3693:	learn: 0.0023933	total: 6m 18s	remaining: 10m 45s
3704:	learn: 0.0029218	total: 6m 17s	remaining: 10m 42s
3600:	learn: 0.0029673	total: 6m 18s	remaining: 11m 11s
3443:	learn: 0.0031124	total: 6m 18s	remaining: 11m 59s
3761:	learn: 0.0026465	total: 6m 18s	remaining: 10m 27s
3705:	learn: 0.0029209	total: 6m 18s	remaining: 10m 42s
3694:	learn: 0.0023926	total: 6m 18s	remaining: 10m 45s
3601:	learn: 0.0029666	total: 6m 18s	remaining: 11m 11s
3444:	learn: 0.0031112	total: 6m 18s	remaining: 11m 59s
3762:	learn: 0.0026459	total: 6m 18s	remaining: 10m 27s
3706:	learn: 0.0029203	total: 6m 18s	remaining: 10m 41s
3695:	learn: 0.0023914	total: 6m 18s	remaining: 10m 45s
3602:	learn: 0.0029662	total: 6m 18s	remaining: 11m 11s
3763:	learn: 0.0026450	total: 6m 18s	remaining: 10m 26s
3445:	learn: 0.0031095	total: 6m 18s	remaining: 11m 59s
3707:	learn: 0.0029194	total: 6m 18s	remaining: 10m 41s
3696:	learn: 0.0023904	total: 6m 18s	remaining: 10m 45s
3603:	learn: 0.0029657	total: 6m 18s	remaining: 11m 11s
3446:	learn: 0.0031080	total: 6m 18s	remaining: 11m 59s
3764:	learn: 0.0026443	total: 6m 18s	remaining: 10m 26s
3708:	learn: 0.0029186	total: 6m 18s	remaining: 10m 41s
3604:	learn: 0.0029634	total: 6m 18s	remaining: 11m 11s
3697:	learn: 0.0023888	total: 6m 18s	remaining: 10m 45s
3765:	learn: 0.0026432	total: 6m 18s	remaining: 10m 26s

3709:	learn: 0.0029173	total: 6m 18s	remaining: 10m 41s
3698:	learn: 0.0023880	total: 6m 18s	remaining: 10m 44s
3447:	learn: 0.0031063	total: 6m 18s	remaining: 11m 59s
3605:	learn: 0.0029619	total: 6m 18s	remaining: 11m 11s
3766:	learn: 0.0026418	total: 6m 18s	remaining: 10m 26s
3699:	learn: 0.0023873	total: 6m 18s	remaining: 10m 44s
3710:	learn: 0.0029164	total: 6m 18s	remaining: 10m 41s
3606:	learn: 0.0029611	total: 6m 18s	remaining: 11m 11s
3448:	learn: 0.0031048	total: 6m 18s	remaining: 11m 59s
3767:	learn: 0.0026410	total: 6m 18s	remaining: 10m 26s
3700:	learn: 0.0023859	total: 6m 18s	remaining: 10m 44s
3711:	learn: 0.0029155	total: 6m 18s	remaining: 10m 41s
3607:	learn: 0.0029600	total: 6m 18s	remaining: 11m 11s
3768:	learn: 0.0026400	total: 6m 18s	remaining: 10m 26s
3449:	learn: 0.0031029	total: 6m 18s	remaining: 11m 59s
3701:	learn: 0.0023853	total: 6m 18s	remaining: 10m 44s
3608:	learn: 0.0029588	total: 6m 18s	remaining: 11m 10s
3712:	learn: 0.0029142	total: 6m 18s	remaining: 10m 41s
3769:	learn: 0.0026388	total: 6m 18s	remaining: 10m 26s
3702:	learn: 0.0023842	total: 6m 18s	remaining: 10m 44s
3450:	learn: 0.0031010	total: 6m 19s	remaining: 11m 59s
3713:	learn: 0.0029133	total: 6m 18s	remaining: 10m 41s
3609:	learn: 0.0029575	total: 6m 19s	remaining: 11m 10s
3770:	learn: 0.0026379	total: 6m 19s	remaining: 10m 26s
3703:	learn: 0.0023834	total: 6m 19s	remaining: 10m 44s
3451:	learn: 0.0030999	total: 6m 19s	remaining: 11m 59s
3714:	learn: 0.0029122	total: 6m 18s	remaining: 10m 41s
3771:	learn: 0.0026371	total: 6m 19s	remaining: 10m 26s
3610:	learn: 0.0029560	total: 6m 19s	remaining: 11m 10s
3704:	learn: 0.0023826	total: 6m 19s	remaining: 10m 44s
3452:	learn: 0.0030989	total: 6m 19s	remaining: 11m 59s
3715:	learn: 0.0029111	total: 6m 19s	remaining: 10m 41s
3611:	learn: 0.0029548	total: 6m 19s	remaining: 11m 10s
3772:	learn: 0.0026361	total: 6m 19s	remaining: 10m 25s
3705:	learn: 0.0023816	total: 6m 19s	remaining: 10m 44s
3716:	learn: 0.0029102	total: 6m 19s	remaining: 10m 40s
3453:	learn: 0.0030978	total: 6m 19s	remaining: 11m 58s
3612:	learn: 0.0029524	total: 6m 19s	remaining: 11m 10s
3773:	learn: 0.0026351	total: 6m 19s	remaining: 10m 25s
3706:	learn: 0.0023807	total: 6m 19s	remaining: 10m 43s
3717:	learn: 0.0029088	total: 6m 19s	remaining: 10m 40s
3454:	learn: 0.0030963	total: 6m 19s	remaining: 11m 58s
3613:	learn: 0.0029519	total: 6m 19s	remaining: 11m 10s
3774:	learn: 0.0026341	total: 6m 19s	remaining: 10m 25s
3707:	learn: 0.0023800	total: 6m 19s	remaining: 10m 43s
3718:	learn: 0.0029070	total: 6m 19s	remaining: 10m 40s
3614:	learn: 0.0029508	total: 6m 19s	remaining: 11m 10s
3775:	learn: 0.0026330	total: 6m 19s	remaining: 10m 25s
3708:	learn: 0.0023791	total: 6m 19s	remaining: 10m 43s
3455:	learn: 0.0030953	total: 6m 19s	remaining: 11m 58s
3719:	learn: 0.0029062	total: 6m 19s	remaining: 10m 40s
3615:	learn: 0.0029493	total: 6m 19s	remaining: 11m 10s
3776:	learn: 0.0026319	total: 6m 19s	remaining: 10m 25s
3709:	learn: 0.0023783	total: 6m 19s	remaining: 10m 43s
3456:	learn: 0.0030944	total: 6m 19s	remaining: 11m 58s
3720:	learn: 0.0029048	total: 6m 19s	remaining: 10m 40s
3777:	learn: 0.0026306	total: 6m 19s	remaining: 10m 25s
3616:	learn: 0.0029478	total: 6m 19s	remaining: 11m 10s
3710:	learn: 0.0023776	total: 6m 19s	remaining: 10m 43s
3457:	learn: 0.0030931	total: 6m 19s	remaining: 11m 58s
3721:	learn: 0.0029042	total: 6m 19s	remaining: 10m 40s
3778:	learn: 0.0026297	total: 6m 19s	remaining: 10m 25s
3617:	learn: 0.0029465	total: 6m 19s	remaining: 11m 9s
3711:	learn: 0.0023769	total: 6m 19s	remaining: 10m 43s
3458:	learn: 0.0030918	total: 6m 19s	remaining: 11m 58s
3779:	learn: 0.0026287	total: 6m 19s	remaining: 10m 25s
3712:	learn: 0.0023761	total: 6m 19s	remaining: 10m 43s
3722:	learn: 0.0029028	total: 6m 19s	remaining: 10m 40s
3618:	learn: 0.0029449	total: 6m 19s	remaining: 11m 9s
3459:	learn: 0.0030899	total: 6m 19s	remaining: 11m 58s
3780:	learn: 0.0026273	total: 6m 20s	remaining: 10m 25s
3713:	learn: 0.0023755	total: 6m 19s	remaining: 10m 43s
3619:	learn: 0.0029429	total: 6m 20s	remaining: 11m 9s
3723:	learn: 0.0029017	total: 6m 19s	remaining: 10m 40s
3460:	learn: 0.0030888	total: 6m 20s	remaining: 11m 58s
3620:	learn: 0.0029418	total: 6m 20s	remaining: 11m 9s
3781:	learn: 0.0026262	total: 6m 20s	remaining: 10m 24s
3714:	learn: 0.0023745	total: 6m 20s	remaining: 10m 43s
3724:	learn: 0.0029008	total: 6m 20s	remaining: 10m 40s
3461:	learn: 0.0030869	total: 6m 20s	remaining: 11m 58s
3782:	learn: 0.0026252	total: 6m 20s	remaining: 10m 24s
3621:	learn: 0.0029403	total: 6m 20s	remaining: 11m 9s
3715:	learn: 0.0023734	total: 6m 20s	remaining: 10m 42s
3725:	learn: 0.0028997	total: 6m 20s	remaining: 10m 40s
3462:	learn: 0.0030860	total: 6m 20s	remaining: 11m 57s
3783:	learn: 0.0026239	total: 6m 20s	remaining: 10m 24s
3622:	learn: 0.0029391	total: 6m 20s	remaining: 11m 9s
3463:	learn: 0.0030846	total: 6m 20s	remaining: 11m 57s
3716:	learn: 0.0023721	total: 6m 20s	remaining: 10m 42s
3726:	learn: 0.0028984	total: 6m 20s	remaining: 10m 39s
3784:	learn: 0.0026234	total: 6m 20s	remaining: 10m 24s
3623:	learn: 0.0029379	total: 6m 20s	remaining: 11m 9s
3464:	learn: 0.0030830	total: 6m 20s	remaining: 11m 57s
3717:	learn: 0.0023714	total: 6m 20s	remaining: 10m 42s
3785:	learn: 0.0026224	total: 6m 20s	remaining: 10m 24s
3727:	learn: 0.0028967	total: 6m 20s	remaining: 10m 39s
3624:	learn: 0.0029367	total: 6m 20s	remaining: 11m 9s
3718:	learn: 0.0023704	total: 6m 20s	remaining: 10m 42s
3786:	learn: 0.0026215	total: 6m 20s	remaining: 10m 24s
3465:	learn: 0.0030816	total: 6m 20s	remaining: 11m 57s
3728:	learn: 0.0028959	total: 6m 20s	remaining: 10m 39s
3719:	learn: 0.0023693	total: 6m 20s	remaining: 10m 42s
3625:	learn: 0.0029349	total: 6m 20s	remaining: 11m 9s
3787:	learn: 0.0026209	total: 6m 20s	remaining: 10m 24s
3729:	learn: 0.0028953	total: 6m 20s	remaining: 10m 39s
3466:	learn: 0.0030795	total: 6m 20s	remaining: 11m 57s
3720:	learn: 0.0023686	total: 6m 20s	remaining: 10m 42s
3788:	learn: 0.0026192	total: 6m 20s	remaining: 10m 24s
3626:	learn: 0.0029338	total: 6m 20s	remaining: 11m 8s
3730:	learn: 0.0028941	total: 6m 20s	remaining: 10m 39s
3627:	learn: 0.0029326	total: 6m 20s	remaining: 11m 8s
3721:	learn: 0.0023679	total: 6m 20s	remaining: 10m 42s
3467:	learn: 0.0030783	total: 6m 20s	remaining: 11m 57s
3789:	learn: 0.0026183	total: 6m 20s	remaining: 10m 24s
3731:	learn: 0.0028933	total: 6m 20s	remaining: 10m 39s
3628:	learn: 0.0029313	total: 6m 20s	remaining: 11m 8s
3722:	learn: 0.0023668	total: 6m 20s	remaining: 10m 42s
3732:	learn: 0.0028914	total: 6m 20s	remaining: 10m 39s
3790:	learn: 0.0026175	total: 6m 20s	remaining: 10m 23s
3468:	learn: 0.0030774	total: 6m 21s	remaining: 11m 57s
3723:	learn: 0.0023657	total: 6m 21s	remaining: 10m 42s
3629:	learn: 0.0029299	total: 6m 21s	remaining: 11m 8s
3791:	learn: 0.0026168	total: 6m 21s	remaining: 10m 23s
3733:	learn: 0.0028902	total: 6m 20s	remaining: 10m 39s
3469:	learn: 0.0030765	total: 6m 21s	remaining: 11m 57s
3734:	learn: 0.0028889	total: 6m 20s	remaining: 10m 39s
3792:	learn: 0.0026158	total: 6m 21s	remaining: 10m 23s
3470:	learn: 0.0030756	total: 6m 21s	remaining: 11m 57s
3724:	learn: 0.0023650	total: 6m 21s	remaining: 10m 42s
3630:	learn: 0.0029283	total: 6m 21s	remaining: 11m 8s
3793:	learn: 0.0026148	total: 6m 21s	remaining: 10m 23s
3735:	learn: 0.0028882	total: 6m 21s	remaining: 10m 38s
3725:	learn: 0.0023638	total: 6m 21s	remaining: 10m 41s
3471:	learn: 0.0030745	total: 6m 21s	remaining: 11m 56s
3631:	learn: 0.0029277	total: 6m 21s	remaining: 11m 8s
3736:	learn: 0.0028875	total: 6m 21s	remaining: 10m 38s
3794:	learn: 0.0026141	total: 6m 21s	remaining: 10m 23s
3726:	learn: 0.0023630	total: 6m 21s	remaining: 10m 41s
3737:	learn: 0.0028862	total: 6m 21s	remaining: 10m 38s
3632:	learn: 0.0029267	total: 6m 21s	remaining: 11m 8s
3795:	learn: 0.0026131	total: 6m 21s	remaining: 10m 23s
3472:	learn: 0.0030727	total: 6m 21s	remaining: 11m 56s
3727:	learn: 0.0023624	total: 6m 21s	remaining: 10m 41s
3738:	learn: 0.0028854	total: 6m 21s	remaining: 10m 38s
3796:	learn: 0.0026123	total: 6m 21s	remaining: 10m 23s
3633:	learn: 0.0029259	total: 6m 21s	remaining: 11m 8s
3728:	learn: 0.0023613	total: 6m 21s	remaining: 10m 41s
3473:	learn: 0.0030706	total: 6m 21s	remaining: 11m 56s
3739:	learn: 0.0028842	total: 6m 21s	remaining: 10m 38s
3797:	learn: 0.0026115	total: 6m 21s	remaining: 10m 23s
3729:	learn: 0.0023606	total: 6m 21s	remaining: 10m 41s
3474:	learn: 0.0030694	total: 6m 21s	remaining: 11m 56s
3634:	learn: 0.0029243	total: 6m 21s	remaining: 11m 8s
3740:	learn: 0.0028823	total: 6m 21s	remaining: 10m 38s
3730:	learn: 0.0023597	total: 6m 21s	remaining: 10m 41s
3798:	learn: 0.0026104	total: 6m 21s	remaining: 10m 23s
3475:	learn: 0.0030684	total: 6m 21s	remaining: 11m 56s
3635:	learn: 0.0029228	total: 6m 21s	remaining: 11m 8s
3731:	learn: 0.0023589	total: 6m 21s	remaining: 10m 41s
3741:	learn: 0.0028810	total: 6m 21s	remaining: 10m 38s
3799:	learn: 0.0026094	total: 6m 21s	remaining: 10m 22s
3476:	learn: 0.0030675	total: 6m 21s	remaining: 11m 56s
3636:	learn: 0.0029214	total: 6m 21s	remaining: 11m 8s
3742:	learn: 0.0028792	total: 6m 21s	remaining: 10m 38s
3732:	learn: 0.0023576	total: 6m 21s	remaining: 10m 41s
3637:	learn: 0.0029209	total: 6m 21s	remaining: 11m 7s
3477:	learn: 0.0030664	total: 6m 21s	remaining: 11m 56s
3800:	learn: 0.0026079	total: 6m 21s	remaining: 10m 22s
3743:	learn: 0.0028782	total: 6m 21s	remaining: 10m 38s
3733:	learn: 0.0023570	total: 6m 21s	remaining: 10m 41s
3801:	learn: 0.0026069	total: 6m 22s	remaining: 10m 22s
3638:	learn: 0.0029205	total: 6m 22s	remaining: 11m 7s
3478:	learn: 0.0030655	total: 6m 22s	remaining: 11m 56s
3802:	learn: 0.0026057	total: 6m 22s	remaining: 10m 22s
3734:	learn: 0.0023561	total: 6m 22s	remaining: 10m 40s
3744:	learn: 0.0028773	total: 6m 21s	remaining: 10m 37s
3639:	learn: 0.0029200	total: 6m 22s	remaining: 11m 7s
3479:	learn: 0.0030644	total: 6m 22s	remaining: 11m 56s
3735:	learn: 0.0023554	total: 6m 22s	remaining: 10m 40s
3803:	learn: 0.0026048	total: 6m 22s	remaining: 10m 22s
3745:	learn: 0.0028765	total: 6m 22s	remaining: 10m 37s
3640:	learn: 0.0029181	total: 6m 22s	remaining: 11m 7s
3480:	learn: 0.0030633	total: 6m 22s	remaining: 11m 55s
3804:	learn: 0.0026040	total: 6m 22s	remaining: 10m 22s
3746:	learn: 0.0028753	total: 6m 22s	remaining: 10m 37s
3736:	learn: 0.0023543	total: 6m 22s	remaining: 10m 40s
3481:	learn: 0.0030622	total: 6m 22s	remaining: 11m 55s
3641:	learn: 0.0029169	total: 6m 22s	remaining: 11m 7s
3805:	learn: 0.0026032	total: 6m 22s	remaining: 10m 22s
3642:	learn: 0.0029152	total: 6m 22s	remaining: 11m 7s
3737:	learn: 0.0023535	total: 6m 22s	remaining: 10m 40s
3747:	learn: 0.0028742	total: 6m 22s	remaining: 10m 37s
3482:	learn: 0.0030611	total: 6m 22s	remaining: 11m 55s
3806:	learn: 0.0026024	total: 6m 22s	remaining: 10m 22s
3738:	learn: 0.0023524	total: 6m 22s	remaining: 10m 40s
3643:	learn: 0.0029136	total: 6m 22s	remaining: 11m 7s
3748:	learn: 0.0028732	total: 6m 22s	remaining: 10m 37s
3483:	learn: 0.0030596	total: 6m 22s	remaining: 11m 55s
3739:	learn: 0.0023517	total: 6m 22s	remaining: 10m 40s
3807:	learn: 0.0026016	total: 6m 22s	remaining: 10m 22s
3644:	learn: 0.0029123	total: 6m 22s	remaining: 11m 7s
3484:	learn: 0.0030581	total: 6m 22s	remaining: 11m 55s
3749:	learn: 0.0028714	total: 6m 22s	remaining: 10m 37s
3808:	learn: 0.0026006	total: 6m 22s	remaining: 10m 22s
3740:	learn: 0.0023507	total: 6m 22s	remaining: 10m 40s
3485:	learn: 0.0030564	total: 6m 22s	remaining: 11m 55s
3645:	learn: 0.0029107	total: 6m 22s	remaining: 11m 6s
3750:	learn: 0.0028705	total: 6m 22s	remaining: 10m 37s
3741:	learn: 0.0023500	total: 6m 22s	remaining: 10m 40s
3809:	learn: 0.0025989	total: 6m 22s	remaining: 10m 21s
3646:	learn: 0.0029095	total: 6m 22s	remaining: 11m 6s
3751:	learn: 0.0028696	total: 6m 22s	remaining: 10m 37s
3486:	learn: 0.0030552	total: 6m 22s	remaining: 11m 55s
3742:	learn: 0.0023491	total: 6m 22s	remaining: 10m 39s
3810:	learn: 0.0025982	total: 6m 22s	remaining: 10m 21s
3647:	learn: 0.0029082	total: 6m 22s	remaining: 11m 6s
3487:	learn: 0.0030535	total: 6m 22s	remaining: 11m 55s
3743:	learn: 0.0023479	total: 6m 22s	remaining: 10m 39s
3752:	learn: 0.0028686	total: 6m 22s	remaining: 10m 37s
3811:	learn: 0.0025971	total: 6m 23s	remaining: 10m 21s
3648:	learn: 0.0029074	total: 6m 23s	remaining: 11m 6s
3744:	learn: 0.0023470	total: 6m 23s	remaining: 10m 39s
3753:	learn: 0.0028676	total: 6m 22s	remaining: 10m 37s
3488:	learn: 0.0030518	total: 6m 23s	remaining: 11m 54s
3812:	learn: 0.0025963	total: 6m 23s	remaining: 10m 21s
3745:	learn: 0.0023463	total: 6m 23s	remaining: 10m 39s
3649:	learn: 0.0029061	total: 6m 23s	remaining: 11m 6s
3754:	learn: 0.0028665	total: 6m 23s	remaining: 10m 36s
3489:	learn: 0.0030502	total: 6m 23s	remaining: 11m 54s
3813:	learn: 0.0025953	total: 6m 23s	remaining: 10m 21s
3746:	learn: 0.0023448	total: 6m 23s	remaining: 10m 39s
3650:	learn: 0.0029049	total: 6m 23s	remaining: 11m 6s
3814:	learn: 0.0025939	total: 6m 23s	remaining: 10m 21s
3490:	learn: 0.0030487	total: 6m 23s	remaining: 11m 54s
3755:	learn: 0.0028657	total: 6m 23s	remaining: 10m 36s
3747:	learn: 0.0023438	total: 6m 23s	remaining: 10m 39s
3651:	learn: 0.0029037	total: 6m 23s	remaining: 11m 6s
3815:	learn: 0.0025925	total: 6m 23s	remaining: 10m 21s
3748:	learn: 0.0023429	total: 6m 23s	remaining: 10m 39s
3756:	learn: 0.0028643	total: 6m 23s	remaining: 10m 36s
3491:	learn: 0.0030473	total: 6m 23s	remaining: 11m 54s
3652:	learn: 0.0029026	total: 6m 23s	remaining: 11m 6s
3816:	learn: 0.0025915	total: 6m 23s	remaining: 10m 21s
3492:	learn: 0.0030464	total: 6m 23s	remaining: 11m 54s
3749:	learn: 0.0023421	total: 6m 23s	remaining: 10m 39s
3757:	learn: 0.0028636	total: 6m 23s	remaining: 10m 36s
3653:	learn: 0.0029012	total: 6m 23s	remaining: 11m 6s
3817:	learn: 0.0025903	total: 6m 23s	remaining: 10m 21s
3750:	learn: 0.0023412	total: 6m 23s	remaining: 10m 39s
3493:	learn: 0.0030446	total: 6m 23s	remaining: 11m 54s
3654:	learn: 0.0029000	total: 6m 23s	remaining: 11m 5s
3758:	learn: 0.0028629	total: 6m 23s	remaining: 10m 36s
3818:	learn: 0.0025893	total: 6m 23s	remaining: 10m 20s
3655:	learn: 0.0028984	total: 6m 23s	remaining: 11m 5s
3751:	learn: 0.0023407	total: 6m 23s	remaining: 10m 38s
3494:	learn: 0.0030438	total: 6m 23s	remaining: 11m 54s
3819:	learn: 0.0025879	total: 6m 23s	remaining: 10m 20s
3759:	learn: 0.0028623	total: 6m 23s	remaining: 10m 36s
3656:	learn: 0.0028965	total: 6m 23s	remaining: 11m 5s
3752:	learn: 0.0023399	total: 6m 23s	remaining: 10m 38s
3495:	learn: 0.0030427	total: 6m 23s	remaining: 11m 54s
3760:	learn: 0.0028605	total: 6m 23s	remaining: 10m 36s
3820:	learn: 0.0025867	total: 6m 23s	remaining: 10m 20s
3753:	learn: 0.0023390	total: 6m 23s	remaining: 10m 38s
3761:	learn: 0.0028588	total: 6m 23s	remaining: 10m 36s
3496:	learn: 0.0030417	total: 6m 23s	remaining: 11m 54s
3657:	learn: 0.0028957	total: 6m 23s	remaining: 11m 5s
3821:	learn: 0.0025856	total: 6m 23s	remaining: 10m 20s
3762:	learn: 0.0028572	total: 6m 23s	remaining: 10m 36s
3754:	learn: 0.0023382	total: 6m 23s	remaining: 10m 38s
3822:	learn: 0.0025851	total: 6m 24s	remaining: 10m 20s
3658:	learn: 0.0028943	total: 6m 24s	remaining: 11m 5s
3763:	learn: 0.0028560	total: 6m 23s	remaining: 10m 36s
3497:	learn: 0.0030401	total: 6m 24s	remaining: 11m 53s
3823:	learn: 0.0025843	total: 6m 24s	remaining: 10m 20s
3755:	learn: 0.0023376	total: 6m 24s	remaining: 10m 38s
3764:	learn: 0.0028549	total: 6m 23s	remaining: 10m 35s
3498:	learn: 0.0030390	total: 6m 24s	remaining: 11m 53s
3659:	learn: 0.0028929	total: 6m 24s	remaining: 11m 5s
3824:	learn: 0.0025834	total: 6m 24s	remaining: 10m 20s
3756:	learn: 0.0023371	total: 6m 24s	remaining: 10m 38s
3765:	learn: 0.0028541	total: 6m 24s	remaining: 10m 35s
3660:	learn: 0.0028917	total: 6m 24s	remaining: 11m 5s
3499:	learn: 0.0030372	total: 6m 24s	remaining: 11m 53s
3825:	learn: 0.0025823	total: 6m 24s	remaining: 10m 20s
3766:	learn: 0.0028532	total: 6m 24s	remaining: 10m 35s
3661:	learn: 0.0028905	total: 6m 24s	remaining: 11m 5s
3757:	learn: 0.0023362	total: 6m 24s	remaining: 10m 38s
3500:	learn: 0.0030362	total: 6m 24s	remaining: 11m 53s
3826:	learn: 0.0025816	total: 6m 24s	remaining: 10m 20s
3662:	learn: 0.0028901	total: 6m 24s	remaining: 11m 5s
3758:	learn: 0.0023357	total: 6m 24s	remaining: 10m 38s

3767:	learn: 0.0028523	total: 6m 24s	remaining: 10m 35s
3501:	learn: 0.0030340	total: 6m 24s	remaining: 11m 53s
3827:	learn: 0.0025805	total: 6m 24s	remaining: 10m 19s
3759:	learn: 0.0023348	total: 6m 24s	remaining: 10m 38s
3663:	learn: 0.0028891	total: 6m 24s	remaining: 11m 4s
3768:	learn: 0.0028516	total: 6m 24s	remaining: 10m 35s
3828:	learn: 0.0025794	total: 6m 24s	remaining: 10m 19s
3760:	learn: 0.0023343	total: 6m 24s	remaining: 10m 38s
3502:	learn: 0.0030324	total: 6m 24s	remaining: 11m 53s
3829:	learn: 0.0025779	total: 6m 24s	remaining: 10m 19s
3664:	learn: 0.0028879	total: 6m 24s	remaining: 11m 4s
3769:	learn: 0.0028505	total: 6m 24s	remaining: 10m 35s
3503:	learn: 0.0030306	total: 6m 24s	remaining: 11m 53s
3761:	learn: 0.0023336	total: 6m 24s	remaining: 10m 37s
3665:	learn: 0.0028865	total: 6m 24s	remaining: 11m 4s
3830:	learn: 0.0025769	total: 6m 24s	remaining: 10m 19s
3770:	learn: 0.0028492	total: 6m 24s	remaining: 10m 35s
3504:	learn: 0.0030290	total: 6m 24s	remaining: 11m 53s
3762:	learn: 0.0023327	total: 6m 24s	remaining: 10m 37s
3666:	learn: 0.0028853	total: 6m 24s	remaining: 11m 4s
3771:	learn: 0.0028485	total: 6m 24s	remaining: 10m 35s
3505:	learn: 0.0030279	total: 6m 24s	remaining: 11m 52s
3831:	learn: 0.0025756	total: 6m 24s	remaining: 10m 19s
3763:	learn: 0.0023320	total: 6m 24s	remaining: 10m 37s
3667:	learn: 0.0028842	total: 6m 24s	remaining: 11m 4s
3772:	learn: 0.0028478	total: 6m 24s	remaining: 10m 35s
3832:	learn: 0.0025748	total: 6m 25s	remaining: 10m 19s
3506:	learn: 0.0030269	total: 6m 25s	remaining: 11m 52s
3764:	learn: 0.0023311	total: 6m 25s	remaining: 10m 37s
3668:	learn: 0.0028832	total: 6m 25s	remaining: 11m 4s
3773:	learn: 0.0028472	total: 6m 24s	remaining: 10m 34s
3507:	learn: 0.0030262	total: 6m 25s	remaining: 11m 52s
3833:	learn: 0.0025740	total: 6m 25s	remaining: 10m 19s
3669:	learn: 0.0028821	total: 6m 25s	remaining: 11m 4s
3765:	learn: 0.0023306	total: 6m 25s	remaining: 10m 37s
3834:	learn: 0.0025734	total: 6m 25s	remaining: 10m 19s
3774:	learn: 0.0028455	total: 6m 25s	remaining: 10m 34s
3508:	learn: 0.0030252	total: 6m 25s	remaining: 11m 52s
3766:	learn: 0.0023300	total: 6m 25s	remaining: 10m 37s
3670:	learn: 0.0028808	total: 6m 25s	remaining: 11m 4s
3509:	learn: 0.0030241	total: 6m 25s	remaining: 11m 52s
3835:	learn: 0.0025726	total: 6m 25s	remaining: 10m 19s
3775:	learn: 0.0028435	total: 6m 25s	remaining: 10m 34s
3767:	learn: 0.0023294	total: 6m 25s	remaining: 10m 37s
3671:	learn: 0.0028796	total: 6m 25s	remaining: 11m 4s
3768:	learn: 0.0023286	total: 6m 25s	remaining: 10m 37s
3510:	learn: 0.0030233	total: 6m 25s	remaining: 11m 52s
3836:	learn: 0.0025714	total: 6m 25s	remaining: 10m 19s
3776:	learn: 0.0028416	total: 6m 25s	remaining: 10m 34s
3672:	learn: 0.0028792	total: 6m 25s	remaining: 11m 3s
3769:	learn: 0.0023277	total: 6m 25s	remaining: 10m 36s
3837:	learn: 0.0025701	total: 6m 25s	remaining: 10m 18s
3511:	learn: 0.0030221	total: 6m 25s	remaining: 11m 52s
3777:	learn: 0.0028398	total: 6m 25s	remaining: 10m 34s
3673:	learn: 0.0028780	total: 6m 25s	remaining: 11m 3s
3838:	learn: 0.0025695	total: 6m 25s	remaining: 10m 18s
3770:	learn: 0.0023269	total: 6m 25s	remaining: 10m 36s
3512:	learn: 0.0030207	total: 6m 25s	remaining: 11m 52s
3778:	learn: 0.0028393	total: 6m 25s	remaining: 10m 34s
3839:	learn: 0.0025683	total: 6m 25s	remaining: 10m 18s
3674:	learn: 0.0028767	total: 6m 25s	remaining: 11m 3s
3771:	learn: 0.0023261	total: 6m 25s	remaining: 10m 36s
3513:	learn: 0.0030195	total: 6m 25s	remaining: 11m 51s
3840:	learn: 0.0025669	total: 6m 25s	remaining: 10m 18s
3779:	learn: 0.0028374	total: 6m 25s	remaining: 10m 34s
3675:	learn: 0.0028754	total: 6m 25s	remaining: 11m 3s
3772:	learn: 0.0023249	total: 6m 25s	remaining: 10m 36s
3841:	learn: 0.0025659	total: 6m 25s	remaining: 10m 18s
3514:	learn: 0.0030178	total: 6m 25s	remaining: 11m 51s
3780:	learn: 0.0028361	total: 6m 25s	remaining: 10m 34s
3676:	learn: 0.0028742	total: 6m 25s	remaining: 11m 3s
3842:	learn: 0.0025648	total: 6m 25s	remaining: 10m 18s
3773:	learn: 0.0023242	total: 6m 25s	remaining: 10m 36s
3515:	learn: 0.0030163	total: 6m 25s	remaining: 11m 51s
3781:	learn: 0.0028345	total: 6m 25s	remaining: 10m 34s
3677:	learn: 0.0028731	total: 6m 25s	remaining: 11m 3s
3843:	learn: 0.0025638	total: 6m 26s	remaining: 10m 18s
3774:	learn: 0.0023233	total: 6m 25s	remaining: 10m 36s
3516:	learn: 0.0030145	total: 6m 26s	remaining: 11m 51s
3782:	learn: 0.0028335	total: 6m 25s	remaining: 10m 34s
3678:	learn: 0.0028715	total: 6m 26s	remaining: 11m 3s
3844:	learn: 0.0025629	total: 6m 26s	remaining: 10m 18s
3517:	learn: 0.0030131	total: 6m 26s	remaining: 11m 51s
3775:	learn: 0.0023228	total: 6m 26s	remaining: 10m 36s
3679:	learn: 0.0028698	total: 6m 26s	remaining: 11m 3s
3783:	learn: 0.0028324	total: 6m 26s	remaining: 10m 34s
3845:	learn: 0.0025621	total: 6m 26s	remaining: 10m 17s
3680:	learn: 0.0028691	total: 6m 26s	remaining: 11m 3s
3776:	learn: 0.0023218	total: 6m 26s	remaining: 10m 36s
3518:	learn: 0.0030124	total: 6m 26s	remaining: 11m 51s
3784:	learn: 0.0028316	total: 6m 26s	remaining: 10m 34s
3846:	learn: 0.0025613	total: 6m 26s	remaining: 10m 17s
3777:	learn: 0.0023213	total: 6m 26s	remaining: 10m 36s
3681:	learn: 0.0028674	total: 6m 26s	remaining: 11m 2s
3785:	learn: 0.0028300	total: 6m 26s	remaining: 10m 33s
3847:	learn: 0.0025603	total: 6m 26s	remaining: 10m 17s
3519:	learn: 0.0030114	total: 6m 26s	remaining: 11m 51s
3778:	learn: 0.0023201	total: 6m 26s	remaining: 10m 36s
3682:	learn: 0.0028663	total: 6m 26s	remaining: 11m 2s
3848:	learn: 0.0025593	total: 6m 26s	remaining: 10m 17s
3786:	learn: 0.0028291	total: 6m 26s	remaining: 10m 33s
3520:	learn: 0.0030096	total: 6m 26s	remaining: 11m 51s
3779:	learn: 0.0023189	total: 6m 26s	remaining: 10m 36s
3849:	learn: 0.0025585	total: 6m 26s	remaining: 10m 17s
3787:	learn: 0.0028285	total: 6m 26s	remaining: 10m 33s
3683:	learn: 0.0028648	total: 6m 26s	remaining: 11m 2s
3521:	learn: 0.0030083	total: 6m 26s	remaining: 11m 51s
3780:	learn: 0.0023176	total: 6m 26s	remaining: 10m 35s
3850:	learn: 0.0025578	total: 6m 26s	remaining: 10m 17s
3788:	learn: 0.0028276	total: 6m 26s	remaining: 10m 33s
3522:	learn: 0.0030071	total: 6m 26s	remaining: 11m 51s
3781:	learn: 0.0023171	total: 6m 26s	remaining: 10m 35s
3684:	learn: 0.0028637	total: 6m 26s	remaining: 11m 2s
3851:	learn: 0.0025567	total: 6m 26s	remaining: 10m 17s
3789:	learn: 0.0028261	total: 6m 26s	remaining: 10m 33s
3782:	learn: 0.0023161	total: 6m 26s	remaining: 10m 35s
3685:	learn: 0.0028629	total: 6m 26s	remaining: 11m 2s
3523:	learn: 0.0030062	total: 6m 26s	remaining: 11m 50s
3790:	learn: 0.0028252	total: 6m 26s	remaining: 10m 33s
3852:	learn: 0.0025557	total: 6m 26s	remaining: 10m 17s
3783:	learn: 0.0023147	total: 6m 26s	remaining: 10m 35s
3686:	learn: 0.0028611	total: 6m 26s	remaining: 11m 2s
3853:	learn: 0.0025545	total: 6m 26s	remaining: 10m 17s
3524:	learn: 0.0030053	total: 6m 26s	remaining: 11m 50s
3791:	learn: 0.0028243	total: 6m 26s	remaining: 10m 33s
3784:	learn: 0.0023142	total: 6m 26s	remaining: 10m 35s
3687:	learn: 0.0028598	total: 6m 27s	remaining: 11m 2s
3854:	learn: 0.0025531	total: 6m 27s	remaining: 10m 16s
3525:	learn: 0.0030036	total: 6m 27s	remaining: 11m 50s
3792:	learn: 0.0028231	total: 6m 26s	remaining: 10m 33s
3785:	learn: 0.0023133	total: 6m 27s	remaining: 10m 35s
3688:	learn: 0.0028586	total: 6m 27s	remaining: 11m 2s
3855:	learn: 0.0025521	total: 6m 27s	remaining: 10m 16s
3526:	learn: 0.0030025	total: 6m 27s	remaining: 11m 50s
3793:	learn: 0.0028224	total: 6m 27s	remaining: 10m 33s
3786:	learn: 0.0023119	total: 6m 27s	remaining: 10m 35s
3689:	learn: 0.0028580	total: 6m 27s	remaining: 11m 2s
3856:	learn: 0.0025512	total: 6m 27s	remaining: 10m 16s
3690:	learn: 0.0028563	total: 6m 27s	remaining: 11m 1s
3527:	learn: 0.0030007	total: 6m 27s	remaining: 11m 50s
3794:	learn: 0.0028217	total: 6m 27s	remaining: 10m 32s
3787:	learn: 0.0023107	total: 6m 27s	remaining: 10m 35s
3857:	learn: 0.0025505	total: 6m 27s	remaining: 10m 16s
3691:	learn: 0.0028545	total: 6m 27s	remaining: 11m 1s
3528:	learn: 0.0029989	total: 6m 27s	remaining: 11m 50s
3795:	learn: 0.0028202	total: 6m 27s	remaining: 10m 32s
3858:	learn: 0.0025490	total: 6m 27s	remaining: 10m 16s
3788:	learn: 0.0023094	total: 6m 27s	remaining: 10m 35s
3529:	learn: 0.0029973	total: 6m 27s	remaining: 11m 50s
3692:	learn: 0.0028531	total: 6m 27s	remaining: 11m 1s
3789:	learn: 0.0023084	total: 6m 27s	remaining: 10m 34s
3796:	learn: 0.0028193	total: 6m 27s	remaining: 10m 32s
3859:	learn: 0.0025481	total: 6m 27s	remaining: 10m 16s
3530:	learn: 0.0029963	total: 6m 27s	remaining: 11m 50s
3693:	learn: 0.0028514	total: 6m 27s	remaining: 11m 1s
3790:	learn: 0.0023073	total: 6m 27s	remaining: 10m 34s
3797:	learn: 0.0028178	total: 6m 27s	remaining: 10m 32s
3791:	learn: 0.0023063	total: 6m 27s	remaining: 10m 34s
3694:	learn: 0.0028500	total: 6m 27s	remaining: 11m 1s
3860:	learn: 0.0025471	total: 6m 27s	remaining: 10m 16s
3531:	learn: 0.0029955	total: 6m 27s	remaining: 11m 50s
3798:	learn: 0.0028172	total: 6m 27s	remaining: 10m 32s
3792:	learn: 0.0023049	total: 6m 27s	remaining: 10m 34s
3861:	learn: 0.0025464	total: 6m 27s	remaining: 10m 16s
3695:	learn: 0.0028495	total: 6m 27s	remaining: 11m 1s
3799:	learn: 0.0028166	total: 6m 27s	remaining: 10m 32s
3532:	learn: 0.0029946	total: 6m 27s	remaining: 11m 49s
3793:	learn: 0.0023039	total: 6m 27s	remaining: 10m 34s
3862:	learn: 0.0025455	total: 6m 27s	remaining: 10m 16s
3794:	learn: 0.0023029	total: 6m 27s	remaining: 10m 34s
3696:	learn: 0.0028483	total: 6m 27s	remaining: 11m 1s
3800:	learn: 0.0028157	total: 6m 27s	remaining: 10m 32s
3533:	learn: 0.0029930	total: 6m 27s	remaining: 11m 49s
3795:	learn: 0.0023024	total: 6m 27s	remaining: 10m 34s
3863:	learn: 0.0025446	total: 6m 27s	remaining: 10m 16s
3534:	learn: 0.0029920	total: 6m 28s	remaining: 11m 49s
3801:	learn: 0.0028146	total: 6m 27s	remaining: 10m 32s
3697:	learn: 0.0028470	total: 6m 27s	remaining: 11m 1s
3796:	learn: 0.0023016	total: 6m 28s	remaining: 10m 33s
3864:	learn: 0.0025435	total: 6m 28s	remaining: 10m 16s
3535:	learn: 0.0029902	total: 6m 28s	remaining: 11m 49s
3698:	learn: 0.0028456	total: 6m 28s	remaining: 11m 1s
3802:	learn: 0.0028139	total: 6m 27s	remaining: 10m 32s
3797:	learn: 0.0023010	total: 6m 28s	remaining: 10m 33s
3865:	learn: 0.0025425	total: 6m 28s	remaining: 10m 15s
3803:	learn: 0.0028129	total: 6m 28s	remaining: 10m 32s
3699:	learn: 0.0028451	total: 6m 28s	remaining: 11m
3866:	learn: 0.0025414	total: 6m 28s	remaining: 10m 15s
3798:	learn: 0.0022998	total: 6m 28s	remaining: 10m 33s
3804:	learn: 0.0028117	total: 6m 28s	remaining: 10m 31s
3536:	learn: 0.0029893	total: 6m 28s	remaining: 11m 49s
3700:	learn: 0.0028444	total: 6m 28s	remaining: 11m
3799:	learn: 0.0022992	total: 6m 28s	remaining: 10m 33s
3867:	learn: 0.0025403	total: 6m 28s	remaining: 10m 15s
3537:	learn: 0.0029885	total: 6m 28s	remaining: 11m 49s
3805:	learn: 0.0028111	total: 6m 28s	remaining: 10m 31s
3800:	learn: 0.0022979	total: 6m 28s	remaining: 10m 33s
3701:	learn: 0.0028430	total: 6m 28s	remaining: 11m
3868:	learn: 0.0025391	total: 6m 28s	remaining: 10m 15s
3538:	learn: 0.0029868	total: 6m 28s	remaining: 11m 49s
3801:	learn: 0.0022968	total: 6m 28s	remaining: 10m 33s
3806:	learn: 0.0028096	total: 6m 28s	remaining: 10m 31s
3702:	learn: 0.0028424	total: 6m 28s	remaining: 11m
3539:	learn: 0.0029860	total: 6m 28s	remaining: 11m 49s
3869:	learn: 0.0025379	total: 6m 28s	remaining: 10m 15s
3802:	learn: 0.0022956	total: 6m 28s	remaining: 10m 33s
3703:	learn: 0.0028417	total: 6m 28s	remaining: 11m
3807:	learn: 0.0028084	total: 6m 28s	remaining: 10m 31s
3540:	learn: 0.0029837	total: 6m 28s	remaining: 11m 49s
3870:	learn: 0.0025369	total: 6m 28s	remaining: 10m 15s
3704:	learn: 0.0028405	total: 6m 28s	remaining: 11m
3803:	learn: 0.0022950	total: 6m 28s	remaining: 10m 33s
3808:	learn: 0.0028077	total: 6m 28s	remaining: 10m 31s
3871:	learn: 0.0025359	total: 6m 28s	remaining: 10m 15s
3541:	learn: 0.0029823	total: 6m 28s	remaining: 11m 48s
3804:	learn: 0.0022945	total: 6m 28s	remaining: 10m 32s
3809:	learn: 0.0028064	total: 6m 28s	remaining: 10m 31s
3705:	learn: 0.0028391	total: 6m 28s	remaining: 11m
3542:	learn: 0.0029807	total: 6m 28s	remaining: 11m 48s
3872:	learn: 0.0025348	total: 6m 28s	remaining: 10m 15s
3810:	learn: 0.0028055	total: 6m 28s	remaining: 10m 31s
3805:	learn: 0.0022937	total: 6m 28s	remaining: 10m 32s
3543:	learn: 0.0029799	total: 6m 28s	remaining: 11m 48s
3706:	learn: 0.0028384	total: 6m 28s	remaining: 11m
3873:	learn: 0.0025337	total: 6m 28s	remaining: 10m 15s
3811:	learn: 0.0028046	total: 6m 28s	remaining: 10m 31s
3812:	learn: 0.0028036	total: 6m 28s	remaining: 10m 31s
3874:	learn: 0.0025326	total: 6m 29s	remaining: 10m 14s
3806:	learn: 0.0022924	total: 6m 29s	remaining: 10m 32s
3544:	learn: 0.0029788	total: 6m 29s	remaining: 11m 48s
3707:	learn: 0.0028373	total: 6m 29s	remaining: 11m
3807:	learn: 0.0022917	total: 6m 29s	remaining: 10m 32s
3708:	learn: 0.0028360	total: 6m 29s	remaining: 11m
3875:	learn: 0.0025314	total: 6m 29s	remaining: 10m 14s
3813:	learn: 0.0028025	total: 6m 29s	remaining: 10m 30s
3545:	learn: 0.0029772	total: 6m 29s	remaining: 11m 48s
3876:	learn: 0.0025304	total: 6m 29s	remaining: 10m 14s
3709:	learn: 0.0028347	total: 6m 29s	remaining: 10m 59s
3808:	learn: 0.0022905	total: 6m 29s	remaining: 10m 32s
3814:	learn: 0.0028013	total: 6m 29s	remaining: 10m 30s
3546:	learn: 0.0029762	total: 6m 29s	remaining: 11m 48s
3877:	learn: 0.0025294	total: 6m 29s	remaining: 10m 14s
3710:	learn: 0.0028340	total: 6m 29s	remaining: 10m 59s
3815:	learn: 0.0028001	total: 6m 29s	remaining: 10m 30s
3809:	learn: 0.0022898	total: 6m 29s	remaining: 10m 32s
3547:	learn: 0.0029746	total: 6m 29s	remaining: 11m 48s
3878:	learn: 0.0025287	total: 6m 29s	remaining: 10m 14s
3816:	learn: 0.0027984	total: 6m 29s	remaining: 10m 30s
3711:	learn: 0.0028326	total: 6m 29s	remaining: 10m 59s
3810:	learn: 0.0022891	total: 6m 29s	remaining: 10m 32s
3548:	learn: 0.0029738	total: 6m 29s	remaining: 11m 48s
3879:	learn: 0.0025280	total: 6m 29s	remaining: 10m 14s
3817:	learn: 0.0027967	total: 6m 29s	remaining: 10m 30s
3712:	learn: 0.0028306	total: 6m 29s	remaining: 10m 59s
3549:	learn: 0.0029723	total: 6m 29s	remaining: 11m 47s
3811:	learn: 0.0022883	total: 6m 29s	remaining: 10m 32s
3818:	learn: 0.0027953	total: 6m 29s	remaining: 10m 30s
3880:	learn: 0.0025269	total: 6m 29s	remaining: 10m 14s
3713:	learn: 0.0028299	total: 6m 29s	remaining: 10m 59s
3812:	learn: 0.0022876	total: 6m 29s	remaining: 10m 32s
3550:	learn: 0.0029709	total: 6m 29s	remaining: 11m 47s
3819:	learn: 0.0027946	total: 6m 29s	remaining: 10m 30s
3881:	learn: 0.0025259	total: 6m 29s	remaining: 10m 14s
3714:	learn: 0.0028283	total: 6m 29s	remaining: 10m 59s
3820:	learn: 0.0027931	total: 6m 29s	remaining: 10m 30s
3813:	learn: 0.0022867	total: 6m 29s	remaining: 10m 32s
3551:	learn: 0.0029699	total: 6m 29s	remaining: 11m 47s
3882:	learn: 0.0025247	total: 6m 29s	remaining: 10m 14s
3821:	learn: 0.0027919	total: 6m 29s	remaining: 10m 29s
3715:	learn: 0.0028271	total: 6m 29s	remaining: 10m 59s
3814:	learn: 0.0022857	total: 6m 29s	remaining: 10m 32s
3822:	learn: 0.0027912	total: 6m 29s	remaining: 10m 29s
3883:	learn: 0.0025236	total: 6m 29s	remaining: 10m 14s
3552:	learn: 0.0029690	total: 6m 29s	remaining: 11m 47s
3716:	learn: 0.0028258	total: 6m 29s	remaining: 10m 59s
3823:	learn: 0.0027905	total: 6m 29s	remaining: 10m 29s
3815:	learn: 0.0022845	total: 6m 30s	remaining: 10m 32s
3884:	learn: 0.0025226	total: 6m 30s	remaining: 10m 13s
3553:	learn: 0.0029680	total: 6m 30s	remaining: 11m 47s
3717:	learn: 0.0028244	total: 6m 30s	remaining: 10m 59s
3824:	learn: 0.0027896	total: 6m 29s	remaining: 10m 29s
3885:	learn: 0.0025219	total: 6m 30s	remaining: 10m 13s
3554:	learn: 0.0029671	total: 6m 30s	remaining: 11m 47s
3816:	learn: 0.0022834	total: 6m 30s	remaining: 10m 31s
3825:	learn: 0.0027889	total: 6m 30s	remaining: 10m 29s
3886:	learn: 0.0025213	total: 6m 30s	remaining: 10m 13s
3718:	learn: 0.0028228	total: 6m 30s	remaining: 10m 59s
3555:	learn: 0.0029663	total: 6m 30s	remaining: 11m 47s
3817:	learn: 0.0022823	total: 6m 30s	remaining: 10m 31s
3719:	learn: 0.0028211	total: 6m 30s	remaining: 10m 58s
3826:	learn: 0.0027876	total: 6m 30s	remaining: 10m 29s
3887:	learn: 0.0025202	total: 6m 30s	remaining: 10m 13s
3556:	learn: 0.0029653	total: 6m 30s	remaining: 11m 47s

3827:	learn: 0.0027860	total: 6m 30s	remaining: 10m 29s
3557:	learn: 0.0029641	total: 6m 30s	remaining: 11m 46s
3888:	learn: 0.0025191	total: 6m 30s	remaining: 10m 13s
3819:	learn: 0.0022808	total: 6m 30s	remaining: 10m 31s
3721:	learn: 0.0028176	total: 6m 30s	remaining: 10m 58s
3828:	learn: 0.0027845	total: 6m 30s	remaining: 10m 29s
3889:	learn: 0.0025181	total: 6m 30s	remaining: 10m 13s
3558:	learn: 0.0029625	total: 6m 30s	remaining: 11m 46s
3820:	learn: 0.0022798	total: 6m 30s	remaining: 10m 31s
3829:	learn: 0.0027835	total: 6m 30s	remaining: 10m 28s
3722:	learn: 0.0028171	total: 6m 30s	remaining: 10m 58s
3890:	learn: 0.0025168	total: 6m 30s	remaining: 10m 13s
3821:	learn: 0.0022788	total: 6m 30s	remaining: 10m 31s
3830:	learn: 0.0027819	total: 6m 30s	remaining: 10m 28s
3723:	learn: 0.0028159	total: 6m 30s	remaining: 10m 58s
3559:	learn: 0.0029619	total: 6m 30s	remaining: 11m 46s
3891:	learn: 0.0025156	total: 6m 30s	remaining: 10m 13s
3831:	learn: 0.0027811	total: 6m 30s	remaining: 10m 28s
3560:	learn: 0.0029608	total: 6m 30s	remaining: 11m 46s
3724:	learn: 0.0028145	total: 6m 30s	remaining: 10m 58s
3822:	learn: 0.0022781	total: 6m 30s	remaining: 10m 31s
3892:	learn: 0.0025145	total: 6m 30s	remaining: 10m 13s
3561:	learn: 0.0029598	total: 6m 30s	remaining: 11m 46s
3832:	learn: 0.0027802	total: 6m 30s	remaining: 10m 28s
3725:	learn: 0.0028138	total: 6m 30s	remaining: 10m 58s
3823:	learn: 0.0022775	total: 6m 30s	remaining: 10m 31s
3893:	learn: 0.0025138	total: 6m 30s	remaining: 10m 12s
3562:	learn: 0.0029587	total: 6m 30s	remaining: 11m 46s
3833:	learn: 0.0027791	total: 6m 30s	remaining: 10m 28s
3726:	learn: 0.0028125	total: 6m 30s	remaining: 10m 58s
3824:	learn: 0.0022766	total: 6m 30s	remaining: 10m 31s
3894:	learn: 0.0025128	total: 6m 31s	remaining: 10m 12s
3563:	learn: 0.0029577	total: 6m 31s	remaining: 11m 46s
3834:	learn: 0.0027783	total: 6m 30s	remaining: 10m 28s
3895:	learn: 0.0025120	total: 6m 31s	remaining: 10m 12s
3727:	learn: 0.0028120	total: 6m 31s	remaining: 10m 57s
3825:	learn: 0.0022759	total: 6m 31s	remaining: 10m 31s
3564:	learn: 0.0029568	total: 6m 31s	remaining: 11m 46s
3835:	learn: 0.0027773	total: 6m 30s	remaining: 10m 28s
3896:	learn: 0.0025108	total: 6m 31s	remaining: 10m 12s
3826:	learn: 0.0022751	total: 6m 31s	remaining: 10m 31s
3728:	learn: 0.0028105	total: 6m 31s	remaining: 10m 57s
3565:	learn: 0.0029559	total: 6m 31s	remaining: 11m 45s
3836:	learn: 0.0027765	total: 6m 31s	remaining: 10m 28s
3897:	learn: 0.0025100	total: 6m 31s	remaining: 10m 12s
3827:	learn: 0.0022745	total: 6m 31s	remaining: 10m 30s
3729:	learn: 0.0028089	total: 6m 31s	remaining: 10m 57s
3566:	learn: 0.0029545	total: 6m 31s	remaining: 11m 45s
3837:	learn: 0.0027753	total: 6m 31s	remaining: 10m 28s
3730:	learn: 0.0028077	total: 6m 31s	remaining: 10m 57s
3898:	learn: 0.0025087	total: 6m 31s	remaining: 10m 12s
3828:	learn: 0.0022740	total: 6m 31s	remaining: 10m 30s
3567:	learn: 0.0029531	total: 6m 31s	remaining: 11m 45s
3838:	learn: 0.0027745	total: 6m 31s	remaining: 10m 27s
3899:	learn: 0.0025077	total: 6m 31s	remaining: 10m 12s
3731:	learn: 0.0028061	total: 6m 31s	remaining: 10m 57s
3839:	learn: 0.0027733	total: 6m 31s	remaining: 10m 27s
3829:	learn: 0.0022733	total: 6m 31s	remaining: 10m 30s
3568:	learn: 0.0029520	total: 6m 31s	remaining: 11m 45s
3900:	learn: 0.0025066	total: 6m 31s	remaining: 10m 12s
3569:	learn: 0.0029503	total: 6m 31s	remaining: 11m 45s
3732:	learn: 0.0028056	total: 6m 31s	remaining: 10m 57s
3840:	learn: 0.0027722	total: 6m 31s	remaining: 10m 27s
3830:	learn: 0.0022727	total: 6m 31s	remaining: 10m 30s
3901:	learn: 0.0025054	total: 6m 31s	remaining: 10m 12s
3570:	learn: 0.0029494	total: 6m 31s	remaining: 11m 45s
3733:	learn: 0.0028052	total: 6m 31s	remaining: 10m 57s
3841:	learn: 0.0027712	total: 6m 31s	remaining: 10m 27s
3831:	learn: 0.0022720	total: 6m 31s	remaining: 10m 30s
3902:	learn: 0.0025043	total: 6m 31s	remaining: 10m 12s
3734:	learn: 0.0028036	total: 6m 31s	remaining: 10m 57s
3571:	learn: 0.0029478	total: 6m 31s	remaining: 11m 45s
3842:	learn: 0.0027703	total: 6m 31s	remaining: 10m 27s
3832:	learn: 0.0022711	total: 6m 31s	remaining: 10m 30s
3735:	learn: 0.0028023	total: 6m 31s	remaining: 10m 57s
3903:	learn: 0.0025031	total: 6m 31s	remaining: 10m 11s
3843:	learn: 0.0027690	total: 6m 31s	remaining: 10m 27s
3572:	learn: 0.0029469	total: 6m 31s	remaining: 11m 45s
3833:	learn: 0.0022705	total: 6m 31s	remaining: 10m 30s
3904:	learn: 0.0025022	total: 6m 31s	remaining: 10m 11s
3844:	learn: 0.0027679	total: 6m 31s	remaining: 10m 27s
3736:	learn: 0.0028019	total: 6m 31s	remaining: 10m 56s
3834:	learn: 0.0022698	total: 6m 32s	remaining: 10m 30s
3573:	learn: 0.0029459	total: 6m 32s	remaining: 11m 44s
3845:	learn: 0.0027673	total: 6m 31s	remaining: 10m 27s
3905:	learn: 0.0025012	total: 6m 32s	remaining: 10m 11s
3737:	learn: 0.0028009	total: 6m 32s	remaining: 10m 56s
3835:	learn: 0.0022692	total: 6m 32s	remaining: 10m 30s
3574:	learn: 0.0029450	total: 6m 32s	remaining: 11m 44s
3846:	learn: 0.0027657	total: 6m 32s	remaining: 10m 27s
3906:	learn: 0.0025004	total: 6m 32s	remaining: 10m 11s
3738:	learn: 0.0027997	total: 6m 32s	remaining: 10m 56s
3836:	learn: 0.0022681	total: 6m 32s	remaining: 10m 29s
3575:	learn: 0.0029442	total: 6m 32s	remaining: 11m 44s
3847:	learn: 0.0027647	total: 6m 32s	remaining: 10m 26s
3837:	learn: 0.0022674	total: 6m 32s	remaining: 10m 29s
3907:	learn: 0.0024996	total: 6m 32s	remaining: 10m 11s
3739:	learn: 0.0027991	total: 6m 32s	remaining: 10m 56s
3838:	learn: 0.0022663	total: 6m 32s	remaining: 10m 29s
3848:	learn: 0.0027639	total: 6m 32s	remaining: 10m 26s
3576:	learn: 0.0029425	total: 6m 32s	remaining: 11m 44s
3908:	learn: 0.0024986	total: 6m 32s	remaining: 10m 11s
3740:	learn: 0.0027976	total: 6m 32s	remaining: 10m 56s
3839:	learn: 0.0022658	total: 6m 32s	remaining: 10m 29s
3849:	learn: 0.0027630	total: 6m 32s	remaining: 10m 26s
3909:	learn: 0.0024978	total: 6m 32s	remaining: 10m 11s
3577:	learn: 0.0029415	total: 6m 32s	remaining: 11m 44s
3840:	learn: 0.0022652	total: 6m 32s	remaining: 10m 29s
3741:	learn: 0.0027965	total: 6m 32s	remaining: 10m 56s
3850:	learn: 0.0027622	total: 6m 32s	remaining: 10m 26s
3910:	learn: 0.0024966	total: 6m 32s	remaining: 10m 11s
3578:	learn: 0.0029408	total: 6m 32s	remaining: 11m 44s
3841:	learn: 0.0022642	total: 6m 32s	remaining: 10m 29s
3851:	learn: 0.0027614	total: 6m 32s	remaining: 10m 26s
3742:	learn: 0.0027958	total: 6m 32s	remaining: 10m 56s
3911:	learn: 0.0024957	total: 6m 32s	remaining: 10m 11s
3579:	learn: 0.0029388	total: 6m 32s	remaining: 11m 44s
3842:	learn: 0.0022636	total: 6m 32s	remaining: 10m 29s
3852:	learn: 0.0027606	total: 6m 32s	remaining: 10m 26s
3743:	learn: 0.0027939	total: 6m 32s	remaining: 10m 56s
3912:	learn: 0.0024947	total: 6m 32s	remaining: 10m 11s
3580:	learn: 0.0029374	total: 6m 32s	remaining: 11m 44s
3843:	learn: 0.0022631	total: 6m 32s	remaining: 10m 29s
3853:	learn: 0.0027596	total: 6m 32s	remaining: 10m 26s
3913:	learn: 0.0024939	total: 6m 32s	remaining: 10m 10s
3744:	learn: 0.0027922	total: 6m 32s	remaining: 10m 56s
3581:	learn: 0.0029359	total: 6m 32s	remaining: 11m 44s
3844:	learn: 0.0022622	total: 6m 32s	remaining: 10m 28s
3854:	learn: 0.0027584	total: 6m 32s	remaining: 10m 26s
3914:	learn: 0.0024928	total: 6m 33s	remaining: 10m 10s
3582:	learn: 0.0029344	total: 6m 33s	remaining: 11m 43s
3845:	learn: 0.0022618	total: 6m 33s	remaining: 10m 28s
3745:	learn: 0.0027908	total: 6m 33s	remaining: 10m 56s
3855:	learn: 0.0027576	total: 6m 32s	remaining: 10m 26s
3915:	learn: 0.0024918	total: 6m 33s	remaining: 10m 10s
3583:	learn: 0.0029335	total: 6m 33s	remaining: 11m 43s
3746:	learn: 0.0027904	total: 6m 33s	remaining: 10m 56s
3846:	learn: 0.0022606	total: 6m 33s	remaining: 10m 28s
3856:	learn: 0.0027569	total: 6m 33s	remaining: 10m 25s
3916:	learn: 0.0024911	total: 6m 33s	remaining: 10m 10s
3584:	learn: 0.0029325	total: 6m 33s	remaining: 11m 43s
3847:	learn: 0.0022593	total: 6m 33s	remaining: 10m 28s
3747:	learn: 0.0027896	total: 6m 33s	remaining: 10m 55s
3917:	learn: 0.0024901	total: 6m 33s	remaining: 10m 10s
 10m 29s
3887:	learn: 0.0025202	total: 6m 30s	remaining: 10m 13s
3556:	learn: 0.0029653	total: 6m 30s	remaining:3857:	learn: 0.0027561	total: 6m 33s	remaining: 10m 25s
3585:	learn: 0.0029305	total: 6m 33s	remaining: 11m 43s
3848:	learn: 0.0022586	total: 6m 33s	remaining: 10m 28s
3858:	learn: 0.0027550	total: 6m 33s	remaining: 10m 25s
3748:	learn: 0.0027885	total: 6m 33s	remaining: 10m 55s
3918:	learn: 0.0024889	total: 6m 33s	remaining: 10m 10s
3586:	learn: 0.0029295	total: 6m 33s	remaining: 11m 43s
3859:	learn: 0.0027542	total: 6m 33s	remaining: 10m 25s
3849:	learn: 0.0022581	total: 6m 33s	remaining: 10m 28s
3749:	learn: 0.0027871	total: 6m 33s	remaining: 10m 55s
3919:	learn: 0.0024877	total: 6m 33s	remaining: 10m 10s
3587:	learn: 0.0029287	total: 6m 33s	remaining: 11m 43s
3860:	learn: 0.0027532	total: 6m 33s	remaining: 10m 25s
3750:	learn: 0.0027859	total: 6m 33s	remaining: 10m 55s
3850:	learn: 0.0022572	total: 6m 33s	remaining: 10m 28s
3920:	learn: 0.0024869	total: 6m 33s	remaining: 10m 10s
3861:	learn: 0.0027522	total: 6m 33s	remaining: 10m 25s
3588:	learn: 0.0029278	total: 6m 33s	remaining: 11m 43s
3751:	learn: 0.0027846	total: 6m 33s	remaining: 10m 55s
3921:	learn: 0.0024860	total: 6m 33s	remaining: 10m 10s
3851:	learn: 0.0022566	total: 6m 33s	remaining: 10m 28s
3862:	learn: 0.0027514	total: 6m 33s	remaining: 10m 25s
3589:	learn: 0.0029268	total: 6m 33s	remaining: 11m 43s
3752:	learn: 0.0027833	total: 6m 33s	remaining: 10m 55s
3863:	learn: 0.0027506	total: 6m 33s	remaining: 10m 25s
3922:	learn: 0.0024851	total: 6m 33s	remaining: 10m 10s
3852:	learn: 0.0022559	total: 6m 33s	remaining: 10m 28s
3590:	learn: 0.0029260	total: 6m 33s	remaining: 11m 42s
3753:	learn: 0.0027827	total: 6m 33s	remaining: 10m 55s
3864:	learn: 0.0027494	total: 6m 33s	remaining: 10m 24s
3923:	learn: 0.0024842	total: 6m 33s	remaining: 10m 9s
3754:	learn: 0.0027809	total: 6m 33s	remaining: 10m 55s
3853:	learn: 0.0022549	total: 6m 33s	remaining: 10m 28s
3591:	learn: 0.0029241	total: 6m 34s	remaining: 11m 42s
3924:	learn: 0.0024833	total: 6m 33s	remaining: 10m 9s
3865:	learn: 0.0027484	total: 6m 33s	remaining: 10m 24s
3755:	learn: 0.0027798	total: 6m 33s	remaining: 10m 54s
3854:	learn: 0.0022543	total: 6m 34s	remaining: 10m 28s
3925:	learn: 0.0024828	total: 6m 34s	remaining: 10m 9s
3592:	learn: 0.0029226	total: 6m 34s	remaining: 11m 42s
3866:	learn: 0.0027476	total: 6m 33s	remaining: 10m 24s
3756:	learn: 0.0027788	total: 6m 34s	remaining: 10m 54s
3855:	learn: 0.0022532	total: 6m 34s	remaining: 10m 27s
3926:	learn: 0.0024818	total: 6m 34s	remaining: 10m 9s
3593:	learn: 0.0029206	total: 6m 34s	remaining: 11m 42s
3867:	learn: 0.0027468	total: 6m 34s	remaining: 10m 24s
3757:	learn: 0.0027775	total: 6m 34s	remaining: 10m 54s
3927:	learn: 0.0024809	total: 6m 34s	remaining: 10m 9s
3856:	learn: 0.0022519	total: 6m 34s	remaining: 10m 27s
3594:	learn: 0.0029192	total: 6m 34s	remaining: 11m 42s
3758:	learn: 0.0027758	total: 6m 34s	remaining: 10m 54s
3868:	learn: 0.0027459	total: 6m 34s	remaining: 10m 24s
3928:	learn: 0.0024799	total: 6m 34s	remaining: 10m 9s
3857:	learn: 0.0022512	total: 6m 34s	remaining: 10m 27s
3595:	learn: 0.0029183	total: 6m 34s	remaining: 11m 42s
3759:	learn: 0.0027752	total: 6m 34s	remaining: 10m 54s
3869:	learn: 0.0027449	total: 6m 34s	remaining: 10m 24s
3929:	learn: 0.0024787	total: 6m 34s	remaining: 10m 9s
3858:	learn: 0.0022502	total: 6m 34s	remaining: 10m 27s
3596:	learn: 0.0029168	total: 6m 34s	remaining: 11m 42s
3930:	learn: 0.0024778	total: 6m 34s	remaining: 10m 9s
3760:	learn: 0.0027740	total: 6m 34s	remaining: 10m 54s
3870:	learn: 0.0027439	total: 6m 34s	remaining: 10m 24s
3859:	learn: 0.0022489	total: 6m 34s	remaining: 10m 27s
3597:	learn: 0.0029151	total: 6m 34s	remaining: 11m 42s
3931:	learn: 0.0024769	total: 6m 34s	remaining: 10m 8s
3761:	learn: 0.0027724	total: 6m 34s	remaining: 10m 54s
3932:	learn: 0.0024759	total: 6m 34s	remaining: 10m 8s
3871:	learn: 0.0027431	total: 6m 34s	remaining: 10m 24s
3598:	learn: 0.0029134	total: 6m 34s	remaining: 11m 42s
3860:	learn: 0.0022479	total: 6m 34s	remaining: 10m 27s
3872:	learn: 0.0027423	total: 6m 34s	remaining: 10m 24s
3762:	learn: 0.0027713	total: 6m 34s	remaining: 10m 54s
3933:	learn: 0.0024748	total: 6m 34s	remaining: 10m 8s
3861:	learn: 0.0022470	total: 6m 34s	remaining: 10m 27s
3599:	learn: 0.0029125	total: 6m 34s	remaining: 11m 41s
3873:	learn: 0.0027417	total: 6m 34s	remaining: 10m 24s
3763:	learn: 0.0027699	total: 6m 34s	remaining: 10m 54s
3934:	learn: 0.0024738	total: 6m 34s	remaining: 10m 8s
3862:	learn: 0.0022459	total: 6m 34s	remaining: 10m 27s
3600:	learn: 0.0029111	total: 6m 34s	remaining: 11m 41s
3764:	learn: 0.0027687	total: 6m 34s	remaining: 10m 53s
3874:	learn: 0.0027409	total: 6m 34s	remaining: 10m 23s
3935:	learn: 0.0024723	total: 6m 34s	remaining: 10m 8s
3863:	learn: 0.0022455	total: 6m 34s	remaining: 10m 27s
3765:	learn: 0.0027671	total: 6m 35s	remaining: 10m 53s
3601:	learn: 0.0029096	total: 6m 35s	remaining: 11m 41s
3875:	learn: 0.0027401	total: 6m 34s	remaining: 10m 23s
3936:	learn: 0.0024714	total: 6m 35s	remaining: 10m 8s
3864:	learn: 0.0022446	total: 6m 35s	remaining: 10m 27s
3766:	learn: 0.0027666	total: 6m 35s	remaining: 10m 53s
3876:	learn: 0.0027392	total: 6m 34s	remaining: 10m 23s
3602:	learn: 0.0029082	total: 6m 35s	remaining: 11m 41s
3937:	learn: 0.0024705	total: 6m 35s	remaining: 10m 8s
3865:	learn: 0.0022433	total: 6m 35s	remaining: 10m 27s
3877:	learn: 0.0027383	total: 6m 35s	remaining: 10m 23s
3767:	learn: 0.0027653	total: 6m 35s	remaining: 10m 53s
3938:	learn: 0.0024698	total: 6m 35s	remaining: 10m 8s
3603:	learn: 0.0029067	total: 6m 35s	remaining: 11m 41s
3866:	learn: 0.0022422	total: 6m 35s	remaining: 10m 26s
3878:	learn: 0.0027373	total: 6m 35s	remaining: 10m 23s
3768:	learn: 0.0027642	total: 6m 35s	remaining: 10m 53s
3939:	learn: 0.0024687	total: 6m 35s	remaining: 10m 8s
3604:	learn: 0.0029060	total: 6m 35s	remaining: 11m 41s
3867:	learn: 0.0022411	total: 6m 35s	remaining: 10m 26s
3879:	learn: 0.0027362	total: 6m 35s	remaining: 10m 23s
3769:	learn: 0.0027630	total: 6m 35s	remaining: 10m 53s
3940:	learn: 0.0024678	total: 6m 35s	remaining: 10m 7s
3880:	learn: 0.0027351	total: 6m 35s	remaining: 10m 23s
3868:	learn: 0.0022400	total: 6m 35s	remaining: 10m 26s
3941:	learn: 0.0024669	total: 6m 35s	remaining: 10m 7s
3605:	learn: 0.0029050	total: 6m 35s	remaining: 11m 41s
3770:	learn: 0.0027614	total: 6m 35s	remaining: 10m 53s
3881:	learn: 0.0027344	total: 6m 35s	remaining: 10m 23s
3869:	learn: 0.0022393	total: 6m 35s	remaining: 10m 26s
3942:	learn: 0.0024660	total: 6m 35s	remaining: 10m 7s
3771:	learn: 0.0027607	total: 6m 35s	remaining: 10m 53s
3606:	learn: 0.0029045	total: 6m 35s	remaining: 11m 41s
3870:	learn: 0.0022384	total: 6m 35s	remaining: 10m 26s
3882:	learn: 0.0027337	total: 6m 35s	remaining: 10m 23s
3943:	learn: 0.0024647	total: 6m 35s	remaining: 10m 7s
3607:	learn: 0.0029038	total: 6m 35s	remaining: 11m 41s
3871:	learn: 0.0022373	total: 6m 35s	remaining: 10m 26s
3772:	learn: 0.0027596	total: 6m 35s	remaining: 10m 53s
3883:	learn: 0.0027326	total: 6m 35s	remaining: 10m 22s
3944:	learn: 0.0024638	total: 6m 35s	remaining: 10m 7s
3773:	learn: 0.0027581	total: 6m 35s	remaining: 10m 52s
3945:	learn: 0.0024629	total: 6m 35s	remaining: 10m 7s
3608:	learn: 0.0029031	total: 6m 35s	remaining: 11m 41s
3872:	learn: 0.0022362	total: 6m 35s	remaining: 10m 26s
3884:	learn: 0.0027320	total: 6m 35s	remaining: 10m 22s
3774:	learn: 0.0027564	total: 6m 35s	remaining: 10m 52s
3873:	learn: 0.0022351	total: 6m 35s	remaining: 10m 26s
3609:	learn: 0.0029014	total: 6m 36s	remaining: 11m 41s
3946:	learn: 0.0024620	total: 6m 36s	remaining: 10m 7s
3885:	learn: 0.0027310	total: 6m 35s	remaining: 10m 22s
3775:	learn: 0.0027553	total: 6m 36s	remaining: 10m 52s
3874:	learn: 0.0022339	total: 6m 36s	remaining: 10m 26s
3947:	learn: 0.0024610	total: 6m 36s	remaining: 10m 7s
3610:	learn: 0.0028998	total: 6m 36s	remaining: 11m 40s
3776:	learn: 0.0027540	total: 6m 36s	remaining: 10m 52s
3886:	learn: 0.0027294	total: 6m 35s	remaining: 10m 22s
3875:	learn: 0.0022330	total: 6m 36s	remaining: 10m 25s
3611:	learn: 0.0028991	total: 6m 36s	remaining: 11m 40s
3948:	learn: 0.0024603	total: 6m 36s	remaining: 10m 7s
3887:	learn: 0.0027285	total: 6m 36s	remaining: 10m 22s

3876:	learn: 0.0022318	total: 6m 36s	remaining: 10m 25s
3949:	learn: 0.0024596	total: 6m 36s	remaining: 10m 6s
3612:	learn: 0.0028984	total: 6m 36s	remaining: 11m 40s
3888:	learn: 0.0027276	total: 6m 36s	remaining: 10m 22s
3877:	learn: 0.0022305	total: 6m 36s	remaining: 10m 25s
3778:	learn: 0.0027520	total: 6m 36s	remaining: 10m 52s
3950:	learn: 0.0024588	total: 6m 36s	remaining: 10m 6s
3613:	learn: 0.0028978	total: 6m 36s	remaining: 11m 40s
3889:	learn: 0.0027269	total: 6m 36s	remaining: 10m 22s
3878:	learn: 0.0022297	total: 6m 36s	remaining: 10m 25s
3951:	learn: 0.0024579	total: 6m 36s	remaining: 10m 6s
3614:	learn: 0.0028968	total: 6m 36s	remaining: 11m 40s
3779:	learn: 0.0027510	total: 6m 36s	remaining: 10m 52s
3879:	learn: 0.0022287	total: 6m 36s	remaining: 10m 25s
3890:	learn: 0.0027261	total: 6m 36s	remaining: 10m 22s
3952:	learn: 0.0024569	total: 6m 36s	remaining: 10m 6s
3780:	learn: 0.0027499	total: 6m 36s	remaining: 10m 52s
3880:	learn: 0.0022276	total: 6m 36s	remaining: 10m 25s
3891:	learn: 0.0027250	total: 6m 36s	remaining: 10m 22s
3615:	learn: 0.0028959	total: 6m 36s	remaining: 11m 40s
3953:	learn: 0.0024561	total: 6m 36s	remaining: 10m 6s
3892:	learn: 0.0027236	total: 6m 36s	remaining: 10m 22s
3781:	learn: 0.0027484	total: 6m 36s	remaining: 10m 52s
3881:	learn: 0.0022266	total: 6m 36s	remaining: 10m 25s
3616:	learn: 0.0028951	total: 6m 36s	remaining: 11m 40s
3782:	learn: 0.0027470	total: 6m 36s	remaining: 10m 52s
3954:	learn: 0.0024549	total: 6m 36s	remaining: 10m 6s
3893:	learn: 0.0027222	total: 6m 36s	remaining: 10m 21s
3882:	learn: 0.0022262	total: 6m 36s	remaining: 10m 25s
3617:	learn: 0.0028937	total: 6m 36s	remaining: 11m 40s
3955:	learn: 0.0024540	total: 6m 36s	remaining: 10m 6s
3783:	learn: 0.0027453	total: 6m 36s	remaining: 10m 51s
3894:	learn: 0.0027215	total: 6m 36s	remaining: 10m 21s
3883:	learn: 0.0022253	total: 6m 36s	remaining: 10m 25s
3956:	learn: 0.0024532	total: 6m 36s	remaining: 10m 6s
3618:	learn: 0.0028920	total: 6m 36s	remaining: 11m 39s
3884:	learn: 0.0022248	total: 6m 37s	remaining: 10m 24s
3784:	learn: 0.0027444	total: 6m 37s	remaining: 10m 51s
3895:	learn: 0.0027199	total: 6m 36s	remaining: 10m 21s
3619:	learn: 0.0028906	total: 6m 37s	remaining: 11m 39s
3957:	learn: 0.0024523	total: 6m 37s	remaining: 10m 6s
3885:	learn: 0.0022239	total: 6m 37s	remaining: 10m 24s
3785:	learn: 0.0027434	total: 6m 37s	remaining: 10m 51s
3896:	learn: 0.0027185	total: 6m 36s	remaining: 10m 21s
3958:	learn: 0.0024514	total: 6m 37s	remaining: 10m 6s
3620:	learn: 0.0028896	total: 6m 37s	remaining: 11m 39s
3886:	learn: 0.0022232	total: 6m 37s	remaining: 10m 24s
3786:	learn: 0.0027423	total: 6m 37s	remaining: 10m 51s
3897:	learn: 0.0027172	total: 6m 37s	remaining: 10m 21s
3959:	learn: 0.0024507	total: 6m 37s	remaining: 10m 5s
3621:	learn: 0.0028882	total: 6m 37s	remaining: 11m 39s
3887:	learn: 0.0022223	total: 6m 37s	remaining: 10m 24s
3787:	learn: 0.0027408	total: 6m 37s	remaining: 10m 51s
3898:	learn: 0.0027157	total: 6m 37s	remaining: 10m 21s
3960:	learn: 0.0024499	total: 6m 37s	remaining: 10m 5s
3888:	learn: 0.0022217	total: 6m 37s	remaining: 10m 24s
3622:	learn: 0.0028867	total: 6m 37s	remaining: 11m 39s
3788:	learn: 0.0027397	total: 6m 37s	remaining: 10m 51s
3899:	learn: 0.0027149	total: 6m 37s	remaining: 10m 21s
3961:	learn: 0.0024486	total: 6m 37s	remaining: 10m 5s
3889:	learn: 0.0022211	total: 6m 37s	remaining: 10m 24s
3623:	learn: 0.0028859	total: 6m 37s	remaining: 11m 39s
3789:	learn: 0.0027392	total: 6m 37s	remaining: 10m 51s
3900:	learn: 0.0027136	total: 6m 37s	remaining: 10m 21s
3890:	learn: 0.0022200	total: 6m 37s	remaining: 10m 24s
3962:	learn: 0.0024477	total: 6m 37s	remaining: 10m 5s
3624:	learn: 0.0028851	total: 6m 37s	remaining: 11m 39s
3891:	learn: 0.0022193	total: 6m 37s	remaining: 10m 24s
3963:	learn: 0.0024470	total: 6m 37s	remaining: 10m 5s
3790:	learn: 0.0027379	total: 6m 37s	remaining: 10m 51s
3901:	learn: 0.0027126	total: 6m 37s	remaining: 10m 21s
3625:	learn: 0.0028844	total: 6m 37s	remaining: 11m 39s
3892:	learn: 0.0022183	total: 6m 37s	remaining: 10m 23s
3791:	learn: 0.0027366	total: 6m 37s	remaining: 10m 51s
3964:	learn: 0.0024461	total: 6m 37s	remaining: 10m 5s
3902:	learn: 0.0027116	total: 6m 37s	remaining: 10m 21s
3893:	learn: 0.0022176	total: 6m 37s	remaining: 10m 23s
3626:	learn: 0.0028830	total: 6m 37s	remaining: 11m 39s
3792:	learn: 0.0027349	total: 6m 37s	remaining: 10m 51s
3965:	learn: 0.0024450	total: 6m 37s	remaining: 10m 5s
3894:	learn: 0.0022172	total: 6m 37s	remaining: 10m 23s
3903:	learn: 0.0027104	total: 6m 37s	remaining: 10m 21s
3627:	learn: 0.0028822	total: 6m 37s	remaining: 11m 38s
3895:	learn: 0.0022163	total: 6m 37s	remaining: 10m 23s
3904:	learn: 0.0027088	total: 6m 37s	remaining: 10m 20s
3966:	learn: 0.0024441	total: 6m 37s	remaining: 10m 5s
3793:	learn: 0.0027335	total: 6m 37s	remaining: 10m 50s
3628:	learn: 0.0028809	total: 6m 38s	remaining: 11m 38s
3896:	learn: 0.0022158	total: 6m 38s	remaining: 10m 23s
3905:	learn: 0.0027079	total: 6m 37s	remaining: 10m 20s
3794:	learn: 0.0027322	total: 6m 38s	remaining: 10m 50s
3967:	learn: 0.0024433	total: 6m 38s	remaining: 10m 5s
3629:	learn: 0.0028797	total: 6m 38s	remaining: 11m 38s
3906:	learn: 0.0027072	total: 6m 37s	remaining: 10m 20s
3897:	learn: 0.0022150	total: 6m 38s	remaining: 10m 23s
3795:	learn: 0.0027315	total: 6m 38s	remaining: 10m 50s
3968:	learn: 0.0024424	total: 6m 38s	remaining: 10m 5s
3630:	learn: 0.0028786	total: 6m 38s	remaining: 11m 38s
3907:	learn: 0.0027062	total: 6m 38s	remaining: 10m 20s
3898:	learn: 0.0022138	total: 6m 38s	remaining: 10m 23s
3969:	learn: 0.0024414	total: 6m 38s	remaining: 10m 4s
3908:	learn: 0.0027049	total: 6m 38s	remaining: 10m 20s
3796:	learn: 0.0027301	total: 6m 38s	remaining: 10m 50s
3631:	learn: 0.0028778	total: 6m 38s	remaining: 11m 38s
3899:	learn: 0.0022134	total: 6m 38s	remaining: 10m 22s
3909:	learn: 0.0027037	total: 6m 38s	remaining: 10m 20s
3797:	learn: 0.0027289	total: 6m 38s	remaining: 10m 50s
3632:	learn: 0.0028770	total: 6m 38s	remaining: 11m 38s
3970:	learn: 0.0024405	total: 6m 38s	remaining: 10m 4s
3900:	learn: 0.0022127	total: 6m 38s	remaining: 10m 22s
3910:	learn: 0.0027030	total: 6m 38s	remaining: 10m 20s
3798:	learn: 0.0027285	total: 6m 38s	remaining: 10m 50s
3633:	learn: 0.0028757	total: 6m 38s	remaining: 11m 38s
3971:	learn: 0.0024396	total: 6m 38s	remaining: 10m 4s
3911:	learn: 0.0027017	total: 6m 38s	remaining: 10m 19s
3901:	learn: 0.0022118	total: 6m 38s	remaining: 10m 22s
3972:	learn: 0.0024387	total: 6m 38s	remaining: 10m 4s
3912:	learn: 0.0027011	total: 6m 38s	remaining: 10m 19s
3799:	learn: 0.0027280	total: 6m 38s	remaining: 10m 50s
3634:	learn: 0.0028744	total: 6m 38s	remaining: 11m 38s
3902:	learn: 0.0022114	total: 6m 38s	remaining: 10m 22s
3913:	learn: 0.0026998	total: 6m 38s	remaining: 10m 19s
3800:	learn: 0.0027266	total: 6m 38s	remaining: 10m 50s
3973:	learn: 0.0024378	total: 6m 38s	remaining: 10m 4s
3903:	learn: 0.0022107	total: 6m 38s	remaining: 10m 22s
3635:	learn: 0.0028734	total: 6m 38s	remaining: 11m 38s
3914:	learn: 0.0026986	total: 6m 38s	remaining: 10m 19s
3974:	learn: 0.0024369	total: 6m 38s	remaining: 10m 4s
3801:	learn: 0.0027261	total: 6m 38s	remaining: 10m 50s
3904:	learn: 0.0022099	total: 6m 38s	remaining: 10m 22s
3636:	learn: 0.0028723	total: 6m 38s	remaining: 11m 37s
3802:	learn: 0.0027255	total: 6m 38s	remaining: 10m 49s
3915:	learn: 0.0026979	total: 6m 38s	remaining: 10m 19s
3975:	learn: 0.0024362	total: 6m 38s	remaining: 10m 4s
3637:	learn: 0.0028714	total: 6m 39s	remaining: 11m 37s
3905:	learn: 0.0022089	total: 6m 38s	remaining: 10m 22s
3976:	learn: 0.0024354	total: 6m 39s	remaining: 10m 4s
3803:	learn: 0.0027241	total: 6m 38s	remaining: 10m 49s
3916:	learn: 0.0026967	total: 6m 38s	remaining: 10m 19s
3906:	learn: 0.0022081	total: 6m 39s	remaining: 10m 22s
3977:	learn: 0.0024345	total: 6m 39s	remaining: 10m 4s
3638:	learn: 0.0028706	total: 6m 39s	remaining: 11m 37s
3804:	learn: 0.0027228	total: 6m 39s	remaining: 10m 49s
3917:	learn: 0.0026957	total: 6m 38s	remaining: 10m 19s
3907:	learn: 0.0022072	total: 6m 39s	remaining: 10m 22s
0m 57s
3642:	learn: 0.0027840	total: 6m 6s	remaining: 103639:	learn: 0.0028691	total: 6m 39s	remaining: 11m 37s
3978:	learn: 0.0024335	total: 6m 39s	remaining: 10m 4s
3805:	learn: 0.0027213	total: 6m 39s	remaining: 10m 49s
3918:	learn: 0.0026946	total: 6m 39s	remaining: 10m 19s
3640:	learn: 0.0028686	total: 6m 39s	remaining: 11m 37s
3908:	learn: 0.0022065	total: 6m 39s	remaining: 10m 22s
3806:	learn: 0.0027208	total: 6m 39s	remaining: 10m 49s
3979:	learn: 0.0024324	total: 6m 39s	remaining: 10m 3s
3919:	learn: 0.0026941	total: 6m 39s	remaining: 10m 19s
3980:	learn: 0.0024313	total: 6m 39s	remaining: 10m 3s
3641:	learn: 0.0028677	total: 6m 39s	remaining: 11m 37s
3909:	learn: 0.0022059	total: 6m 39s	remaining: 10m 22s
3807:	learn: 0.0027203	total: 6m 39s	remaining: 10m 49s
3920:	learn: 0.0026929	total: 6m 39s	remaining: 10m 19s
3981:	learn: 0.0024303	total: 6m 39s	remaining: 10m 3s
3808:	learn: 0.0027187	total: 6m 39s	remaining: 10m 49s
3642:	learn: 0.0028666	total: 6m 39s	remaining: 11m 37s
3910:	learn: 0.0022051	total: 6m 39s	remaining: 10m 21s
3921:	learn: 0.0026923	total: 6m 39s	remaining: 10m 18s
3982:	learn: 0.0024292	total: 6m 39s	remaining: 10m 3s
3809:	learn: 0.0027173	total: 6m 39s	remaining: 10m 49s
3922:	learn: 0.0026915	total: 6m 39s	remaining: 10m 18s
3983:	learn: 0.0024283	total: 6m 39s	remaining: 10m 3s
3911:	learn: 0.0022047	total: 6m 39s	remaining: 10m 21s
3643:	learn: 0.0028653	total: 6m 39s	remaining: 11m 37s
3810:	learn: 0.0027163	total: 6m 39s	remaining: 10m 49s
3923:	learn: 0.0026900	total: 6m 39s	remaining: 10m 18s
3912:	learn: 0.0022042	total: 6m 39s	remaining: 10m 21s
3984:	learn: 0.0024274	total: 6m 39s	remaining: 10m 3s
3644:	learn: 0.0028646	total: 6m 39s	remaining: 11m 37s
3811:	learn: 0.0027148	total: 6m 39s	remaining: 10m 48s
3924:	learn: 0.0026890	total: 6m 39s	remaining: 10m 18s
3985:	learn: 0.0024265	total: 6m 39s	remaining: 10m 3s
3913:	learn: 0.0022034	total: 6m 39s	remaining: 10m 21s
3645:	learn: 0.0028638	total: 6m 39s	remaining: 11m 36s
3925:	learn: 0.0026876	total: 6m 39s	remaining: 10m 18s
3812:	learn: 0.0027130	total: 6m 39s	remaining: 10m 48s
3986:	learn: 0.0024260	total: 6m 39s	remaining: 10m 3s
3914:	learn: 0.0022027	total: 6m 39s	remaining: 10m 21s
3926:	learn: 0.0026867	total: 6m 39s	remaining: 10m 18s
3646:	learn: 0.0028623	total: 6m 40s	remaining: 11m 36s
3813:	learn: 0.0027120	total: 6m 39s	remaining: 10m 48s
3987:	learn: 0.0024251	total: 6m 40s	remaining: 10m 3s
3915:	learn: 0.0022016	total: 6m 40s	remaining: 10m 21s
3647:	learn: 0.0028609	total: 6m 40s	remaining: 11m 36s
3814:	learn: 0.0027109	total: 6m 40s	remaining: 10m 48s
3927:	learn: 0.0026851	total: 6m 39s	remaining: 10m 18s
3916:	learn: 0.0022010	total: 6m 40s	remaining: 10m 21s
3988:	learn: 0.0024242	total: 6m 40s	remaining: 10m 2s
3648:	learn: 0.0028594	total: 6m 40s	remaining: 11m 36s
3815:	learn: 0.0027095	total: 6m 40s	remaining: 10m 48s
3928:	learn: 0.0026838	total: 6m 40s	remaining: 10m 18s
3989:	learn: 0.0024233	total: 6m 40s	remaining: 10m 2s
3917:	learn: 0.0022005	total: 6m 40s	remaining: 10m 21s
3816:	learn: 0.0027082	total: 6m 40s	remaining: 10m 48s
3649:	learn: 0.0028588	total: 6m 40s	remaining: 11m 36s
3929:	learn: 0.0026839	total: 6m 40s	remaining: 10m 17s
3990:	learn: 0.0024224	total: 6m 40s	remaining: 10m 2s
3918:	learn: 0.0022002	total: 6m 40s	remaining: 10m 21s
3817:	learn: 0.0027067	total: 6m 40s	remaining: 10m 48s
3650:	learn: 0.0028578	total: 6m 40s	remaining: 11m 36s
3930:	learn: 0.0026826	total: 6m 40s	remaining: 10m 17s
3919:	learn: 0.0021996	total: 6m 40s	remaining: 10m 21s
3991:	learn: 0.0024216	total: 6m 40s	remaining: 10m 2s
3818:	learn: 0.0027054	total: 6m 40s	remaining: 10m 48s
3931:	learn: 0.0026810	total: 6m 40s	remaining: 10m 17s
3920:	learn: 0.0021986	total: 6m 40s	remaining: 10m 20s
3651:	learn: 0.0028564	total: 6m 40s	remaining: 11m 36s
3992:	learn: 0.0024207	total: 6m 40s	remaining: 10m 2s
3819:	learn: 0.0027034	total: 6m 40s	remaining: 10m 48s
3921:	learn: 0.0021980	total: 6m 40s	remaining: 10m 20s
3932:	learn: 0.0026799	total: 6m 40s	remaining: 10m 17s
3993:	learn: 0.0024198	total: 6m 40s	remaining: 10m 2s
3652:	learn: 0.0028556	total: 6m 40s	remaining: 11m 36s
3820:	learn: 0.0027020	total: 6m 40s	remaining: 10m 47s
3933:	learn: 0.0026788	total: 6m 40s	remaining: 10m 17s
3922:	learn: 0.0021969	total: 6m 40s	remaining: 10m 20s
3994:	learn: 0.0024189	total: 6m 40s	remaining: 10m 2s
3653:	learn: 0.0028541	total: 6m 40s	remaining: 11m 36s
3923:	learn: 0.0021964	total: 6m 40s	remaining: 10m 20s
3934:	learn: 0.0026777	total: 6m 40s	remaining: 10m 17s
3995:	learn: 0.0024180	total: 6m 40s	remaining: 10m 2s
3821:	learn: 0.0027009	total: 6m 40s	remaining: 10m 47s
3654:	learn: 0.0028526	total: 6m 40s	remaining: 11m 35s
3924:	learn: 0.0021952	total: 6m 40s	remaining: 10m 20s
3935:	learn: 0.0026764	total: 6m 40s	remaining: 10m 17s
3822:	learn: 0.0027004	total: 6m 40s	remaining: 10m 47s
3996:	learn: 0.0024175	total: 6m 40s	remaining: 10m 2s
3655:	learn: 0.0028515	total: 6m 40s	remaining: 11m 35s
3936:	learn: 0.0026750	total: 6m 40s	remaining: 10m 17s
3823:	learn: 0.0026998	total: 6m 40s	remaining: 10m 47s
3925:	learn: 0.0021942	total: 6m 40s	remaining: 10m 20s
3997:	learn: 0.0024165	total: 6m 41s	remaining: 10m 2s
3656:	learn: 0.0028502	total: 6m 41s	remaining: 11m 35s
3937:	learn: 0.0026739	total: 6m 40s	remaining: 10m 17s
3824:	learn: 0.0026983	total: 6m 41s	remaining: 10m 47s
3998:	learn: 0.0024156	total: 6m 41s	remaining: 10m 1s
3926:	learn: 0.0021936	total: 6m 41s	remaining: 10m 20s
3825:	learn: 0.0026969	total: 6m 41s	remaining: 10m 47s
3657:	learn: 0.0028490	total: 6m 41s	remaining: 11m 35s
3938:	learn: 0.0026727	total: 6m 41s	remaining: 10m 17s
3999:	learn: 0.0024144	total: 6m 41s	remaining: 10m 1s
3927:	learn: 0.0021926	total: 6m 41s	remaining: 10m 20s
3658:	learn: 0.0028478	total: 6m 41s	remaining: 11m 35s
3826:	learn: 0.0026952	total: 6m 41s	remaining: 10m 47s
3939:	learn: 0.0026719	total: 6m 41s	remaining: 10m 16s
4000:	learn: 0.0024134	total: 6m 41s	remaining: 10m 1s
3928:	learn: 0.0021914	total: 6m 41s	remaining: 10m 20s
3659:	learn: 0.0028472	total: 6m 41s	remaining: 11m 35s
3827:	learn: 0.0026948	total: 6m 41s	remaining: 10m 47s
3940:	learn: 0.0026712	total: 6m 41s	remaining: 10m 16s
3929:	learn: 0.0021902	total: 6m 41s	remaining: 10m 19s
4001:	learn: 0.0024126	total: 6m 41s	remaining: 10m 1s
3660:	learn: 0.0028458	total: 6m 41s	remaining: 11m 35s
3828:	learn: 0.0026935	total: 6m 41s	remaining: 10m 47s
3941:	learn: 0.0026701	total: 6m 41s	remaining: 10m 16s
4002:	learn: 0.0024117	total: 6m 41s	remaining: 10m 1s
3930:	learn: 0.0021892	total: 6m 41s	remaining: 10m 19s
3942:	learn: 0.0026689	total: 6m 41s	remaining: 10m 16s
3829:	learn: 0.0026926	total: 6m 41s	remaining: 10m 46s
4003:	learn: 0.0024106	total: 6m 41s	remaining: 10m 1s
3661:	learn: 0.0028444	total: 6m 41s	remaining: 11m 35s
3931:	learn: 0.0021886	total: 6m 41s	remaining: 10m 19s
3830:	learn: 0.0026913	total: 6m 41s	remaining: 10m 46s
4004:	learn: 0.0024097	total: 6m 41s	remaining: 10m 1s
3943:	learn: 0.0026689	total: 6m 41s	remaining: 10m 16s
3831:	learn: 0.0026896	total: 6m 41s	remaining: 10m 46s
3662:	learn: 0.0028436	total: 6m 41s	remaining: 11m 35s
3932:	learn: 0.0021877	total: 6m 41s	remaining: 10m 19s
4005:	learn: 0.0024092	total: 6m 41s	remaining: 10m 1s
3944:	learn: 0.0026675	total: 6m 41s	remaining: 10m 16s
3832:	learn: 0.0026893	total: 6m 41s	remaining: 10m 46s
3933:	learn: 0.0021870	total: 6m 41s	remaining: 10m 19s
3663:	learn: 0.0028425	total: 6m 41s	remaining: 11m 34s
4006:	learn: 0.0024086	total: 6m 41s	remaining: 10m 1s
3945:	learn: 0.0026667	total: 6m 41s	remaining: 10m 16s
3833:	learn: 0.0026880	total: 6m 41s	remaining: 10m 46s
3934:	learn: 0.0021860	total: 6m 41s	remaining: 10m 19s
3664:	learn: 0.0028417	total: 6m 41s	remaining: 11m 34s
4007:	learn: 0.0024078	total: 6m 41s	remaining: 10m
3834:	learn: 0.0026868	total: 6m 41s	remaining: 10m 46s
3946:	learn: 0.0026657	total: 6m 41s	remaining: 10m 16s
3935:	learn: 0.0021852	total: 6m 42s	remaining: 10m 19s
3665:	learn: 0.0028402	total: 6m 42s	remaining: 11m 34s
4008:	learn: 0.0024073	total: 6m 42s	remaining: 10m
3947:	learn: 0.0026641	total: 6m 41s	remaining: 10m 16s

3835:	learn: 0.0026858	total: 6m 42s	remaining: 10m 46s
3936:	learn: 0.0021842	total: 6m 42s	remaining: 10m 19s
3948:	learn: 0.0026630	total: 6m 42s	remaining: 10m 15s
4009:	learn: 0.0024067	total: 6m 42s	remaining: 10m
3666:	learn: 0.0028394	total: 6m 42s	remaining: 11m 34s
3836:	learn: 0.0026858	total: 6m 42s	remaining: 10m 45s
3937:	learn: 0.0021836	total: 6m 42s	remaining: 10m 19s
3667:	learn: 0.0028388	total: 6m 42s	remaining: 11m 34s
3949:	learn: 0.0026617	total: 6m 42s	remaining: 10m 15s
4010:	learn: 0.0024061	total: 6m 42s	remaining: 10m
3837:	learn: 0.0026846	total: 6m 42s	remaining: 10m 45s
3938:	learn: 0.0021830	total: 6m 42s	remaining: 10m 19s
3950:	learn: 0.0026605	total: 6m 42s	remaining: 10m 15s
4011:	learn: 0.0024053	total: 6m 42s	remaining: 10m
3668:	learn: 0.0028379	total: 6m 42s	remaining: 11m 34s
3838:	learn: 0.0026828	total: 6m 42s	remaining: 10m 45s
3939:	learn: 0.0021824	total: 6m 42s	remaining: 10m 18s
4012:	learn: 0.0024046	total: 6m 42s	remaining: 10m
3951:	learn: 0.0026589	total: 6m 42s	remaining: 10m 15s
3669:	learn: 0.0028370	total: 6m 42s	remaining: 11m 34s
3839:	learn: 0.0026815	total: 6m 42s	remaining: 10m 45s
3940:	learn: 0.0021819	total: 6m 42s	remaining: 10m 18s
4013:	learn: 0.0024041	total: 6m 42s	remaining: 10m
3670:	learn: 0.0028362	total: 6m 42s	remaining: 11m 34s
3952:	learn: 0.0026579	total: 6m 42s	remaining: 10m 15s
3840:	learn: 0.0026798	total: 6m 42s	remaining: 10m 45s
3941:	learn: 0.0021814	total: 6m 42s	remaining: 10m 18s
4014:	learn: 0.0024031	total: 6m 42s	remaining: 10m
3953:	learn: 0.0026573	total: 6m 42s	remaining: 10m 15s
3841:	learn: 0.0026798	total: 6m 42s	remaining: 10m 45s
3671:	learn: 0.0028346	total: 6m 42s	remaining: 11m 34s
3942:	learn: 0.0021803	total: 6m 42s	remaining: 10m 18s
4015:	learn: 0.0024022	total: 6m 42s	remaining: 10m
3672:	learn: 0.0028335	total: 6m 42s	remaining: 11m 33s
3842:	learn: 0.0026794	total: 6m 42s	remaining: 10m 45s
3954:	learn: 0.0026573	total: 6m 42s	remaining: 10m 15s
3943:	learn: 0.0021796	total: 6m 42s	remaining: 10m 18s
3673:	learn: 0.0028318	total: 6m 42s	remaining: 11m 33s
4016:	learn: 0.0024017	total: 6m 42s	remaining: 10m
3944:	learn: 0.0021785	total: 6m 42s	remaining: 10m 18s
3955:	learn: 0.0026563	total: 6m 42s	remaining: 10m 15s
3674:	learn: 0.0028301	total: 6m 42s	remaining: 11m 33s
3843:	learn: 0.0026790	total: 6m 42s	remaining: 10m 45s
4017:	learn: 0.0024008	total: 6m 42s	remaining: 9m 59s
3945:	learn: 0.0021781	total: 6m 42s	remaining: 10m 18s
3956:	learn: 0.0026552	total: 6m 42s	remaining: 10m 15s
3844:	learn: 0.0026774	total: 6m 43s	remaining: 10m 45s
3675:	learn: 0.0028286	total: 6m 43s	remaining: 11m 33s
3946:	learn: 0.0021781	total: 6m 43s	remaining: 10m 18s
4018:	learn: 0.0024000	total: 6m 43s	remaining: 9m 59s
3957:	learn: 0.0026540	total: 6m 42s	remaining: 10m 15s
3845:	learn: 0.0026760	total: 6m 43s	remaining: 10m 45s
3676:	learn: 0.0028271	total: 6m 43s	remaining: 11m 33s
4019:	learn: 0.0023990	total: 6m 43s	remaining: 9m 59s
3947:	learn: 0.0021776	total: 6m 43s	remaining: 10m 18s
3958:	learn: 0.0026529	total: 6m 43s	remaining: 10m 14s
3846:	learn: 0.0026748	total: 6m 43s	remaining: 10m 44s
3677:	learn: 0.0028256	total: 6m 43s	remaining: 11m 33s
4020:	learn: 0.0023981	total: 6m 43s	remaining: 9m 59s
3959:	learn: 0.0026517	total: 6m 43s	remaining: 10m 14s
3948:	learn: 0.0021769	total: 6m 43s	remaining: 10m 17s
3847:	learn: 0.0026740	total: 6m 43s	remaining: 10m 44s
4021:	learn: 0.0023972	total: 6m 43s	remaining: 9m 59s
3678:	learn: 0.0028237	total: 6m 43s	remaining: 11m 33s
3960:	learn: 0.0026505	total: 6m 43s	remaining: 10m 14s
3949:	learn: 0.0021761	total: 6m 43s	remaining: 10m 17s
3848:	learn: 0.0026721	total: 6m 43s	remaining: 10m 44s
4022:	learn: 0.0023964	total: 6m 43s	remaining: 9m 59s
3679:	learn: 0.0028229	total: 6m 43s	remaining: 11m 33s
3950:	learn: 0.0021750	total: 6m 43s	remaining: 10m 17s
3849:	learn: 0.0026721	total: 6m 43s	remaining: 10m 44s
4023:	learn: 0.0023955	total: 6m 43s	remaining: 9m 59s
3961:	learn: 0.0026494	total: 6m 43s	remaining: 10m 14s
3680:	learn: 0.0028221	total: 6m 43s	remaining: 11m 32s
4024:	learn: 0.0023947	total: 6m 43s	remaining: 9m 59s
3951:	learn: 0.0021747	total: 6m 43s	remaining: 10m 17s
3850:	learn: 0.0026716	total: 6m 43s	remaining: 10m 44s
3681:	learn: 0.0028211	total: 6m 43s	remaining: 11m 32s
3962:	learn: 0.0026482	total: 6m 43s	remaining: 10m 14s
4025:	learn: 0.0023937	total: 6m 43s	remaining: 9m 59s
3851:	learn: 0.0026704	total: 6m 43s	remaining: 10m 44s
3952:	learn: 0.0021736	total: 6m 43s	remaining: 10m 17s
3963:	learn: 0.0026475	total: 6m 43s	remaining: 10m 14s
3682:	learn: 0.0028201	total: 6m 43s	remaining: 11m 32s
4026:	learn: 0.0023926	total: 6m 43s	remaining: 9m 58s
3852:	learn: 0.0026690	total: 6m 43s	remaining: 10m 44s
3953:	learn: 0.0021729	total: 6m 43s	remaining: 10m 17s
4027:	learn: 0.0023920	total: 6m 43s	remaining: 9m 58s
3683:	learn: 0.0028196	total: 6m 43s	remaining: 11m 32s
3964:	learn: 0.0026464	total: 6m 43s	remaining: 10m 14s
4028:	learn: 0.0023910	total: 6m 43s	remaining: 9m 58s
3853:	learn: 0.0026676	total: 6m 43s	remaining: 10m 44s
3954:	learn: 0.0021718	total: 6m 43s	remaining: 10m 17s
3684:	learn: 0.0028187	total: 6m 44s	remaining: 11m 32s
3965:	learn: 0.0026451	total: 6m 43s	remaining: 10m 14s
3955:	learn: 0.0021712	total: 6m 44s	remaining: 10m 17s
4029:	learn: 0.0023900	total: 6m 44s	remaining: 9m 58s
3854:	learn: 0.0026665	total: 6m 44s	remaining: 10m 44s
3685:	learn: 0.0028173	total: 6m 44s	remaining: 11m 32s
3966:	learn: 0.0026441	total: 6m 43s	remaining: 10m 14s
4030:	learn: 0.0023892	total: 6m 44s	remaining: 9m 58s
3956:	learn: 0.0021702	total: 6m 44s	remaining: 10m 17s
3855:	learn: 0.0026665	total: 6m 44s	remaining: 10m 43s
3686:	learn: 0.0028164	total: 6m 44s	remaining: 11m 32s
3967:	learn: 0.0026429	total: 6m 44s	remaining: 10m 14s
4031:	learn: 0.0023885	total: 6m 44s	remaining: 9m 58s
3957:	learn: 0.0021688	total: 6m 44s	remaining: 10m 17s
3856:	learn: 0.0026650	total: 6m 44s	remaining: 10m 43s
3968:	learn: 0.0026422	total: 6m 44s	remaining: 10m 14s
4032:	learn: 0.0023877	total: 6m 44s	remaining: 9m 58s
3687:	learn: 0.0028157	total: 6m 44s	remaining: 11m 32s
3958:	learn: 0.0021680	total: 6m 44s	remaining: 10m 16s
3857:	learn: 0.0026643	total: 6m 44s	remaining: 10m 43s
3969:	learn: 0.0026416	total: 6m 44s	remaining: 10m 13s
3688:	learn: 0.0028146	total: 6m 44s	remaining: 11m 31s
4033:	learn: 0.0023870	total: 6m 44s	remaining: 9m 58s
3959:	learn: 0.0021672	total: 6m 44s	remaining: 10m 16s
3858:	learn: 0.0026639	total: 6m 44s	remaining: 10m 43s
3970:	learn: 0.0026405	total: 6m 44s	remaining: 10m 13s
3689:	learn: 0.0028130	total: 6m 44s	remaining: 11m 31s
4034:	learn: 0.0023861	total: 6m 44s	remaining: 9m 58s
3960:	learn: 0.0021664	total: 6m 44s	remaining: 10m 16s
3859:	learn: 0.0026625	total: 6m 44s	remaining: 10m 43s
3690:	learn: 0.0028116	total: 6m 44s	remaining: 11m 31s
3971:	learn: 0.0026394	total: 6m 44s	remaining: 10m 13s
4035:	learn: 0.0023855	total: 6m 44s	remaining: 9m 57s
3961:	learn: 0.0021658	total: 6m 44s	remaining: 10m 16s
3860:	learn: 0.0026611	total: 6m 44s	remaining: 10m 43s
3972:	learn: 0.0026382	total: 6m 44s	remaining: 10m 13s
3691:	learn: 0.0028108	total: 6m 44s	remaining: 11m 31s
3861:	learn: 0.0026603	total: 6m 44s	remaining: 10m 43s
4036:	learn: 0.0023848	total: 6m 44s	remaining: 9m 57s
3962:	learn: 0.0021647	total: 6m 44s	remaining: 10m 16s
3692:	learn: 0.0028090	total: 6m 44s	remaining: 11m 31s
3973:	learn: 0.0026372	total: 6m 44s	remaining: 10m 13s
4037:	learn: 0.0023840	total: 6m 44s	remaining: 9m 57s
3862:	learn: 0.0026590	total: 6m 44s	remaining: 10m 43s
3963:	learn: 0.0021639	total: 6m 44s	remaining: 10m 16s
3693:	learn: 0.0028073	total: 6m 44s	remaining: 11m 31s
3974:	learn: 0.0026363	total: 6m 44s	remaining: 10m 13s
3863:	learn: 0.0026581	total: 6m 44s	remaining: 10m 43s
4038:	learn: 0.0023833	total: 6m 44s	remaining: 9m 57s
3964:	learn: 0.0021630	total: 6m 44s	remaining: 10m 16s
3864:	learn: 0.0026568	total: 6m 44s	remaining: 10m 42s
3975:	learn: 0.0026358	total: 6m 44s	remaining: 10m 13s
3694:	learn: 0.0028057	total: 6m 45s	remaining: 11m 31s
4039:	learn: 0.0023825	total: 6m 45s	remaining: 9m 57s
3965:	learn: 0.0021625	total: 6m 45s	remaining: 10m 16s
3865:	learn: 0.0026564	total: 6m 45s	remaining: 10m 42s
3976:	learn: 0.0026352	total: 6m 44s	remaining: 10m 13s
3695:	learn: 0.0028045	total: 6m 45s	remaining: 11m 31s
4040:	learn: 0.0023817	total: 6m 45s	remaining: 9m 57s
3966:	learn: 0.0021618	total: 6m 45s	remaining: 10m 16s
3866:	learn: 0.0026548	total: 6m 45s	remaining: 10m 42s
3977:	learn: 0.0026340	total: 6m 45s	remaining: 10m 13s
3696:	learn: 0.0028035	total: 6m 45s	remaining: 11m 30s
4041:	learn: 0.0023811	total: 6m 45s	remaining: 9m 57s
3967:	learn: 0.0021610	total: 6m 45s	remaining: 10m 16s
3978:	learn: 0.0026334	total: 6m 45s	remaining: 10m 13s
3697:	learn: 0.0028027	total: 6m 45s	remaining: 11m 30s
3867:	learn: 0.0026538	total: 6m 45s	remaining: 10m 42s
3968:	learn: 0.0021603	total: 6m 45s	remaining: 10m 15s
4042:	learn: 0.0023802	total: 6m 45s	remaining: 9m 57s
3979:	learn: 0.0026322	total: 6m 45s	remaining: 10m 12s
3969:	learn: 0.0021594	total: 6m 45s	remaining: 10m 15s
3868:	learn: 0.0026522	total: 6m 45s	remaining: 10m 42s
3698:	learn: 0.0028014	total: 6m 45s	remaining: 11m 30s
4043:	learn: 0.0023794	total: 6m 45s	remaining: 9m 57s
3980:	learn: 0.0026312	total: 6m 45s	remaining: 10m 12s
3970:	learn: 0.0021586	total: 6m 45s	remaining: 10m 15s
3699:	learn: 0.0028007	total: 6m 45s	remaining: 11m 30s
4044:	learn: 0.0023788	total: 6m 45s	remaining: 9m 57s
3869:	learn: 0.0026510	total: 6m 45s	remaining: 10m 42s
3981:	learn: 0.0026300	total: 6m 45s	remaining: 10m 12s
3971:	learn: 0.0021580	total: 6m 45s	remaining: 10m 15s
3700:	learn: 0.0027999	total: 6m 45s	remaining: 11m 30s
3870:	learn: 0.0026503	total: 6m 45s	remaining: 10m 42s
4045:	learn: 0.0023780	total: 6m 45s	remaining: 9m 56s
3972:	learn: 0.0021572	total: 6m 45s	remaining: 10m 15s
3982:	learn: 0.0026294	total: 6m 45s	remaining: 10m 12s
3701:	learn: 0.0027990	total: 6m 45s	remaining: 11m 30s
3871:	learn: 0.0026490	total: 6m 45s	remaining: 10m 42s
4046:	learn: 0.0023772	total: 6m 45s	remaining: 9m 56s
3973:	learn: 0.0021564	total: 6m 45s	remaining: 10m 15s
3983:	learn: 0.0026280	total: 6m 45s	remaining: 10m 12s
3702:	learn: 0.0027976	total: 6m 45s	remaining: 11m 30s
3872:	learn: 0.0026482	total: 6m 45s	remaining: 10m 42s
4047:	learn: 0.0023759	total: 6m 45s	remaining: 9m 56s
3974:	learn: 0.0021557	total: 6m 45s	remaining: 10m 15s
3984:	learn: 0.0026269	total: 6m 45s	remaining: 10m 12s
3703:	learn: 0.0027969	total: 6m 45s	remaining: 11m 30s
4048:	learn: 0.0023754	total: 6m 45s	remaining: 9m 56s
3873:	learn: 0.0026478	total: 6m 45s	remaining: 10m 41s
3975:	learn: 0.0021551	total: 6m 45s	remaining: 10m 15s
3985:	learn: 0.0026258	total: 6m 45s	remaining: 10m 12s
3704:	learn: 0.0027952	total: 6m 46s	remaining: 11m 29s
4049:	learn: 0.0023746	total: 6m 46s	remaining: 9m 56s
3874:	learn: 0.0026469	total: 6m 46s	remaining: 10m 41s
3976:	learn: 0.0021543	total: 6m 46s	remaining: 10m 14s
3986:	learn: 0.0026247	total: 6m 45s	remaining: 10m 12s
3705:	learn: 0.0027938	total: 6m 46s	remaining: 11m 29s
4050:	learn: 0.0023737	total: 6m 46s	remaining: 9m 56s
3977:	learn: 0.0021538	total: 6m 46s	remaining: 10m 14s
3875:	learn: 0.0026460	total: 6m 46s	remaining: 10m 41s
3978:	learn: 0.0021530	total: 6m 46s	remaining: 10m 14s
4051:	learn: 0.0023726	total: 6m 46s	remaining: 9m 56s
3987:	learn: 0.0026237	total: 6m 46s	remaining: 10m 12s
3706:	learn: 0.0027926	total: 6m 46s	remaining: 11m 29s
3876:	learn: 0.0026450	total: 6m 46s	remaining: 10m 41s
3979:	learn: 0.0021522	total: 6m 46s	remaining: 10m 14s
3988:	learn: 0.0026227	total: 6m 46s	remaining: 10m 12s
4052:	learn: 0.0023720	total: 6m 46s	remaining: 9m 56s
3707:	learn: 0.0027913	total: 6m 46s	remaining: 11m 29s
3877:	learn: 0.0026438	total: 6m 46s	remaining: 10m 41s
3980:	learn: 0.0021512	total: 6m 46s	remaining: 10m 14s
3989:	learn: 0.0026221	total: 6m 46s	remaining: 10m 11s
4053:	learn: 0.0023709	total: 6m 46s	remaining: 9m 56s
3878:	learn: 0.0026424	total: 6m 46s	remaining: 10m 41s
3708:	learn: 0.0027897	total: 6m 46s	remaining: 11m 29s
3990:	learn: 0.0026215	total: 6m 46s	remaining: 10m 11s
3981:	learn: 0.0021507	total: 6m 46s	remaining: 10m 14s
4054:	learn: 0.0023700	total: 6m 46s	remaining: 9m 56s
3879:	learn: 0.0026422	total: 6m 46s	remaining: 10m 41s
3991:	learn: 0.0026209	total: 6m 46s	remaining: 10m 11s
3709:	learn: 0.0027882	total: 6m 46s	remaining: 11m 29s
3982:	learn: 0.0021502	total: 6m 46s	remaining: 10m 14s
4055:	learn: 0.0023694	total: 6m 46s	remaining: 9m 55s
3880:	learn: 0.0026413	total: 6m 46s	remaining: 10m 41s
3992:	learn: 0.0026198	total: 6m 46s	remaining: 10m 11s
3983:	learn: 0.0021491	total: 6m 46s	remaining: 10m 14s
3710:	learn: 0.0027874	total: 6m 46s	remaining: 11m 29s
4056:	learn: 0.0023687	total: 6m 46s	remaining: 9m 55s
3881:	learn: 0.0026405	total: 6m 46s	remaining: 10m 41s
3993:	learn: 0.0026188	total: 6m 46s	remaining: 10m 11s
3984:	learn: 0.0021488	total: 6m 46s	remaining: 10m 14s
3882:	learn: 0.0026394	total: 6m 46s	remaining: 10m 40s
4057:	learn: 0.0023678	total: 6m 46s	remaining: 9m 55s
3711:	learn: 0.0027859	total: 6m 46s	remaining: 11m 29s
3985:	learn: 0.0021479	total: 6m 46s	remaining: 10m 13s
3994:	learn: 0.0026180	total: 6m 46s	remaining: 10m 11s
3883:	learn: 0.0026386	total: 6m 46s	remaining: 10m 40s
4058:	learn: 0.0023670	total: 6m 47s	remaining: 9m 55s
3995:	learn: 0.0026168	total: 6m 46s	remaining: 10m 11s
3986:	learn: 0.0021472	total: 6m 46s	remaining: 10m 13s
3884:	learn: 0.0026377	total: 6m 47s	remaining: 10m 40s
3712:	learn: 0.0027845	total: 6m 47s	remaining: 11m 29s
3996:	learn: 0.0026161	total: 6m 46s	remaining: 10m 11s
4059:	learn: 0.0023663	total: 6m 47s	remaining: 9m 55s
3987:	learn: 0.0021461	total: 6m 47s	remaining: 10m 13s
3885:	learn: 0.0026367	total: 6m 47s	remaining: 10m 40s
3997:	learn: 0.0026151	total: 6m 46s	remaining: 10m 10s
3713:	learn: 0.0027832	total: 6m 47s	remaining: 11m 29s
4060:	learn: 0.0023655	total: 6m 47s	remaining: 9m 55s
3988:	learn: 0.0021453	total: 6m 47s	remaining: 10m 13s
3886:	learn: 0.0026353	total: 6m 47s	remaining: 10m 40s
3998:	learn: 0.0026140	total: 6m 47s	remaining: 10m 10s
3714:	learn: 0.0027818	total: 6m 47s	remaining: 11m 29s
4061:	learn: 0.0023647	total: 6m 47s	remaining: 9m 55s
3989:	learn: 0.0021448	total: 6m 47s	remaining: 10m 13s
3715:	learn: 0.0027811	total: 6m 47s	remaining: 11m 28s
3887:	learn: 0.0026338	total: 6m 47s	remaining: 10m 40s
3999:	learn: 0.0026134	total: 6m 47s	remaining: 10m 10s
4062:	learn: 0.0023640	total: 6m 47s	remaining: 9m 55s
3990:	learn: 0.0021446	total: 6m 47s	remaining: 10m 13s
3888:	learn: 0.0026329	total: 6m 47s	remaining: 10m 40s
3716:	learn: 0.0027799	total: 6m 47s	remaining: 11m 28s
4000:	learn: 0.0026128	total: 6m 47s	remaining: 10m 10s
4063:	learn: 0.0023633	total: 6m 47s	remaining: 9m 55s
3991:	learn: 0.0021440	total: 6m 47s	remaining: 10m 13s
3717:	learn: 0.0027791	total: 6m 47s	remaining: 11m 28s
3889:	learn: 0.0026314	total: 6m 47s	remaining: 10m 40s
4001:	learn: 0.0026122	total: 6m 47s	remaining: 10m 10s
4064:	learn: 0.0023626	total: 6m 47s	remaining: 9m 55s
3992:	learn: 0.0021432	total: 6m 47s	remaining: 10m 13s
3890:	learn: 0.0026305	total: 6m 47s	remaining: 10m 40s
3718:	learn: 0.0027779	total: 6m 47s	remaining: 11m 28s
4065:	learn: 0.0023617	total: 6m 47s	remaining: 9m 54s
4002:	learn: 0.0026113	total: 6m 47s	remaining: 10m 10s
3993:	learn: 0.0021426	total: 6m 47s	remaining: 10m 13s
4066:	learn: 0.0023609	total: 6m 47s	remaining: 9m 54s
3891:	learn: 0.0026297	total: 6m 47s	remaining: 10m 39s
3719:	learn: 0.0027769	total: 6m 47s	remaining: 11m 28s
4003:	learn: 0.0026104	total: 6m 47s	remaining: 10m 10s
4067:	learn: 0.0023599	total: 6m 47s	remaining: 9m 54s
3994:	learn: 0.0021415	total: 6m 47s	remaining: 10m 13s
3720:	learn: 0.0027756	total: 6m 47s	remaining: 11m 28s
4068:	learn: 0.0023594	total: 6m 47s	remaining: 9m 54s
3892:	learn: 0.0026293	total: 6m 47s	remaining: 10m 39s
4004:	learn: 0.0026098	total: 6m 47s	remaining: 10m 10s
3995:	learn: 0.0021409	total: 6m 47s	remaining: 10m 12s
3721:	learn: 0.0027742	total: 6m 48s	remaining: 11m 28s
4069:	learn: 0.0023585	total: 6m 48s	remaining: 9m 54s
3893:	learn: 0.0026285	total: 6m 47s	remaining: 10m 39s

3996:	learn: 0.0021401	total: 6m 48s	remaining: 10m 12s
4005:	learn: 0.0026090	total: 6m 47s	remaining: 10m 10s
4070:	learn: 0.0023578	total: 6m 48s	remaining: 9m 54s
3722:	learn: 0.0027729	total: 6m 48s	remaining: 11m 28s
3997:	learn: 0.0021394	total: 6m 48s	remaining: 10m 12s
4006:	learn: 0.0026085	total: 6m 47s	remaining: 10m 10s
3894:	learn: 0.0026271	total: 6m 48s	remaining: 10m 39s
4071:	learn: 0.0023568	total: 6m 48s	remaining: 9m 54s
3723:	learn: 0.0027721	total: 6m 48s	remaining: 11m 27s
3998:	learn: 0.0021386	total: 6m 48s	remaining: 10m 12s
4007:	learn: 0.0026077	total: 6m 48s	remaining: 10m 10s
4072:	learn: 0.0023561	total: 6m 48s	remaining: 9m 54s
3895:	learn: 0.0026268	total: 6m 48s	remaining: 10m 39s
3724:	learn: 0.0027706	total: 6m 48s	remaining: 11m 27s
4008:	learn: 0.0026066	total: 6m 48s	remaining: 10m 9s
3999:	learn: 0.0021379	total: 6m 48s	remaining: 10m 12s
4073:	learn: 0.0023552	total: 6m 48s	remaining: 9m 53s
3896:	learn: 0.0026259	total: 6m 48s	remaining: 10m 39s
3725:	learn: 0.0027691	total: 6m 48s	remaining: 11m 27s
4009:	learn: 0.0026060	total: 6m 48s	remaining: 10m 9s
4000:	learn: 0.0021370	total: 6m 48s	remaining: 10m 12s
4074:	learn: 0.0023544	total: 6m 48s	remaining: 9m 53s
3897:	learn: 0.0026253	total: 6m 48s	remaining: 10m 39s
3726:	learn: 0.0027683	total: 6m 48s	remaining: 11m 27s
4010:	learn: 0.0026047	total: 6m 48s	remaining: 10m 9s
3898:	learn: 0.0026238	total: 6m 48s	remaining: 10m 39s
4075:	learn: 0.0023536	total: 6m 48s	remaining: 9m 53s
4001:	learn: 0.0021361	total: 6m 48s	remaining: 10m 12s
3727:	learn: 0.0027672	total: 6m 48s	remaining: 11m 27s
4011:	learn: 0.0026038	total: 6m 48s	remaining: 10m 9s
4002:	learn: 0.0021354	total: 6m 48s	remaining: 10m 12s
3899:	learn: 0.0026228	total: 6m 48s	remaining: 10m 39s
3728:	learn: 0.0027661	total: 6m 48s	remaining: 11m 27s
4076:	learn: 0.0023528	total: 6m 48s	remaining: 9m 53s
4012:	learn: 0.0026025	total: 6m 48s	remaining: 10m 9s
4003:	learn: 0.0021347	total: 6m 48s	remaining: 10m 12s
3900:	learn: 0.0026213	total: 6m 48s	remaining: 10m 39s
3729:	learn: 0.0027653	total: 6m 48s	remaining: 11m 27s
4077:	learn: 0.0023522	total: 6m 48s	remaining: 9m 53s
4013:	learn: 0.0026018	total: 6m 48s	remaining: 10m 9s
4004:	learn: 0.0021340	total: 6m 48s	remaining: 10m 11s
3901:	learn: 0.0026200	total: 6m 48s	remaining: 10m 38s
3730:	learn: 0.0027635	total: 6m 48s	remaining: 11m 27s
4078:	learn: 0.0023516	total: 6m 48s	remaining: 9m 53s
4014:	learn: 0.0026006	total: 6m 48s	remaining: 10m 9s
4005:	learn: 0.0021335	total: 6m 48s	remaining: 10m 11s
4015:	learn: 0.0025999	total: 6m 48s	remaining: 10m 9s
3902:	learn: 0.0026193	total: 6m 48s	remaining: 10m 38s
3731:	learn: 0.0027622	total: 6m 49s	remaining: 11m 26s
4079:	learn: 0.0023507	total: 6m 49s	remaining: 9m 53s
4006:	learn: 0.0021326	total: 6m 49s	remaining: 10m 11s
4016:	learn: 0.0025989	total: 6m 48s	remaining: 10m 8s
3903:	learn: 0.0026184	total: 6m 49s	remaining: 10m 38s
4007:	learn: 0.0021317	total: 6m 49s	remaining: 10m 11s
3732:	learn: 0.0027614	total: 6m 49s	remaining: 11m 26s
4080:	learn: 0.0023498	total: 6m 49s	remaining: 9m 53s
4017:	learn: 0.0025984	total: 6m 48s	remaining: 10m 8s
4008:	learn: 0.0021312	total: 6m 49s	remaining: 10m 11s
4081:	learn: 0.0023491	total: 6m 49s	remaining: 9m 53s
3733:	learn: 0.0027600	total: 6m 49s	remaining: 11m 26s
3904:	learn: 0.0026176	total: 6m 49s	remaining: 10m 38s
4018:	learn: 0.0025974	total: 6m 49s	remaining: 10m 8s
4009:	learn: 0.0021306	total: 6m 49s	remaining: 10m 11s
4082:	learn: 0.0023483	total: 6m 49s	remaining: 9m 53s
3905:	learn: 0.0026166	total: 6m 49s	remaining: 10m 38s
3734:	learn: 0.0027586	total: 6m 49s	remaining: 11m 26s
4010:	learn: 0.0021300	total: 6m 49s	remaining: 10m 11s
4083:	learn: 0.0023475	total: 6m 49s	remaining: 9m 53s
4019:	learn: 0.0025964	total: 6m 49s	remaining: 10m 8s
3906:	learn: 0.0026159	total: 6m 49s	remaining: 10m 38s
3735:	learn: 0.0027575	total: 6m 49s	remaining: 11m 26s
4084:	learn: 0.0023468	total: 6m 49s	remaining: 9m 52s
4020:	learn: 0.0025957	total: 6m 49s	remaining: 10m 8s
4011:	learn: 0.0021290	total: 6m 49s	remaining: 10m 11s
3907:	learn: 0.0026146	total: 6m 49s	remaining: 10m 38s
3736:	learn: 0.0027567	total: 6m 49s	remaining: 11m 26s
4085:	learn: 0.0023461	total: 6m 49s	remaining: 9m 52s
4021:	learn: 0.0025941	total: 6m 49s	remaining: 10m 8s
4012:	learn: 0.0021290	total: 6m 49s	remaining: 10m 11s
3737:	learn: 0.0027551	total: 6m 49s	remaining: 11m 26s
3908:	learn: 0.0026138	total: 6m 49s	remaining: 10m 38s
4086:	learn: 0.0023455	total: 6m 49s	remaining: 9m 52s
4022:	learn: 0.0025931	total: 6m 49s	remaining: 10m 8s
4013:	learn: 0.0021283	total: 6m 49s	remaining: 10m 10s
3738:	learn: 0.0027540	total: 6m 49s	remaining: 11m 26s
3909:	learn: 0.0026124	total: 6m 49s	remaining: 10m 38s
4023:	learn: 0.0025924	total: 6m 49s	remaining: 10m 8s
4014:	learn: 0.0021274	total: 6m 49s	remaining: 10m 10s
4087:	learn: 0.0023447	total: 6m 49s	remaining: 9m 52s
3739:	learn: 0.0027526	total: 6m 49s	remaining: 11m 26s
3910:	learn: 0.0026116	total: 6m 49s	remaining: 10m 38s
4024:	learn: 0.0025912	total: 6m 49s	remaining: 10m 8s
4015:	learn: 0.0021269	total: 6m 49s	remaining: 10m 10s
4088:	learn: 0.0023443	total: 6m 49s	remaining: 9m 52s
3740:	learn: 0.0027512	total: 6m 49s	remaining: 11m 25s
3911:	learn: 0.0026101	total: 6m 49s	remaining: 10m 37s
4025:	learn: 0.0025900	total: 6m 49s	remaining: 10m 8s
4016:	learn: 0.0021259	total: 6m 49s	remaining: 10m 10s
4089:	learn: 0.0023431	total: 6m 49s	remaining: 9m 52s
3741:	learn: 0.0027505	total: 6m 50s	remaining: 11m 25s
4090:	learn: 0.0023428	total: 6m 50s	remaining: 9m 52s
4026:	learn: 0.0025890	total: 6m 49s	remaining: 10m 7s
3912:	learn: 0.0026097	total: 6m 50s	remaining: 10m 37s
4017:	learn: 0.0021251	total: 6m 50s	remaining: 10m 10s
3742:	learn: 0.0027492	total: 6m 50s	remaining: 11m 25s
4027:	learn: 0.0025880	total: 6m 49s	remaining: 10m 7s
4091:	learn: 0.0023420	total: 6m 50s	remaining: 9m 52s
3913:	learn: 0.0026084	total: 6m 50s	remaining: 10m 37s
4018:	learn: 0.0021239	total: 6m 50s	remaining: 10m 10s
3743:	learn: 0.0027478	total: 6m 50s	remaining: 11m 25s
4028:	learn: 0.0025869	total: 6m 50s	remaining: 10m 7s
4092:	learn: 0.0023412	total: 6m 50s	remaining: 9m 52s
4019:	learn: 0.0021235	total: 6m 50s	remaining: 10m 10s
3744:	learn: 0.0027464	total: 6m 50s	remaining: 11m 25s
3914:	learn: 0.0026084	total: 6m 50s	remaining: 10m 37s
4029:	learn: 0.0025862	total: 6m 50s	remaining: 10m 7s
4093:	learn: 0.0023403	total: 6m 50s	remaining: 9m 51s
4020:	learn: 0.0021228	total: 6m 50s	remaining: 10m 10s
3745:	learn: 0.0027456	total: 6m 50s	remaining: 11m 25s
3915:	learn: 0.0026076	total: 6m 50s	remaining: 10m 37s
4030:	learn: 0.0025855	total: 6m 50s	remaining: 10m 7s
4094:	learn: 0.0023397	total: 6m 50s	remaining: 9m 51s
4021:	learn: 0.0021222	total: 6m 50s	remaining: 10m 10s
3916:	learn: 0.0026073	total: 6m 50s	remaining: 10m 37s
3746:	learn: 0.0027441	total: 6m 50s	remaining: 11m 25s
4031:	learn: 0.0025849	total: 6m 50s	remaining: 10m 7s
4095:	learn: 0.0023388	total: 6m 50s	remaining: 9m 51s
4022:	learn: 0.0021218	total: 6m 50s	remaining: 10m 9s
4032:	learn: 0.0025837	total: 6m 50s	remaining: 10m 7s
3917:	learn: 0.0026060	total: 6m 50s	remaining: 10m 37s
3747:	learn: 0.0027427	total: 6m 50s	remaining: 11m 25s
4096:	learn: 0.0023381	total: 6m 50s	remaining: 9m 51s
4023:	learn: 0.0021213	total: 6m 50s	remaining: 10m 9s
4033:	learn: 0.0025831	total: 6m 50s	remaining: 10m 7s
4097:	learn: 0.0023374	total: 6m 50s	remaining: 9m 51s
3918:	learn: 0.0026050	total: 6m 50s	remaining: 10m 37s
3748:	learn: 0.0027414	total: 6m 50s	remaining: 11m 24s
4024:	learn: 0.0021209	total: 6m 50s	remaining: 10m 9s
4034:	learn: 0.0025819	total: 6m 50s	remaining: 10m 6s
4098:	learn: 0.0023366	total: 6m 50s	remaining: 9m 51s
3919:	learn: 0.0026042	total: 6m 50s	remaining: 10m 37s
3749:	learn: 0.0027402	total: 6m 50s	remaining: 11m 24s
4025:	learn: 0.0021199	total: 6m 50s	remaining: 10m 9s
4035:	learn: 0.0025808	total: 6m 50s	remaining: 10m 6s
4099:	learn: 0.0023361	total: 6m 50s	remaining: 9m 51s
3920:	learn: 0.0026028	total: 6m 50s	remaining: 10m 37s
3750:	learn: 0.0027387	total: 6m 50s	remaining: 11m 24s
4026:	learn: 0.0021190	total: 6m 50s	remaining: 10m 9s
4100:	learn: 0.0023354	total: 6m 51s	remaining: 9m 51s
4036:	learn: 0.0025803	total: 6m 50s	remaining: 10m 6s
4027:	learn: 0.0021182	total: 6m 51s	remaining: 10m 9s
3751:	learn: 0.0027380	total: 6m 51s	remaining: 11m 24s
3921:	learn: 0.0026015	total: 6m 51s	remaining: 10m 37s
4101:	learn: 0.0023344	total: 6m 51s	remaining: 9m 51s
4037:	learn: 0.0025799	total: 6m 50s	remaining: 10m 6s
4028:	learn: 0.0021176	total: 6m 51s	remaining: 10m 9s
4102:	learn: 0.0023335	total: 6m 51s	remaining: 9m 50s
3922:	learn: 0.0026003	total: 6m 51s	remaining: 10m 36s
4038:	learn: 0.0025785	total: 6m 51s	remaining: 10m 6s
3752:	learn: 0.0027368	total: 6m 51s	remaining: 11m 24s
4029:	learn: 0.0021166	total: 6m 51s	remaining: 10m 9s
4103:	learn: 0.0023326	total: 6m 51s	remaining: 9m 50s
3923:	learn: 0.0025995	total: 6m 51s	remaining: 10m 36s
4039:	learn: 0.0025778	total: 6m 51s	remaining: 10m 6s
3753:	learn: 0.0027353	total: 6m 51s	remaining: 11m 24s
4104:	learn: 0.0023315	total: 6m 51s	remaining: 9m 50s
3924:	learn: 0.0025987	total: 6m 51s	remaining: 10m 36s
4040:	learn: 0.0025771	total: 6m 51s	remaining: 10m 6s
4030:	learn: 0.0021159	total: 6m 51s	remaining: 10m 9s
3754:	learn: 0.0027344	total: 6m 51s	remaining: 11m 24s
4105:	learn: 0.0023309	total: 6m 51s	remaining: 9m 50s
3925:	learn: 0.0025975	total: 6m 51s	remaining: 10m 36s
4031:	learn: 0.0021152	total: 6m 51s	remaining: 10m 9s
4041:	learn: 0.0025766	total: 6m 51s	remaining: 10m 6s
3755:	learn: 0.0027336	total: 6m 51s	remaining: 11m 24s
4106:	learn: 0.0023299	total: 6m 51s	remaining: 9m 50s
4032:	learn: 0.0021142	total: 6m 51s	remaining: 10m 8s
3926:	learn: 0.0025966	total: 6m 51s	remaining: 10m 36s
3756:	learn: 0.0027322	total: 6m 51s	remaining: 11m 23s
4042:	learn: 0.0025757	total: 6m 51s	remaining: 10m 6s
4107:	learn: 0.0023292	total: 6m 51s	remaining: 9m 50s
4033:	learn: 0.0021131	total: 6m 51s	remaining: 10m 8s
3927:	learn: 0.0025956	total: 6m 51s	remaining: 10m 36s
3757:	learn: 0.0027309	total: 6m 51s	remaining: 11m 23s
4043:	learn: 0.0025749	total: 6m 51s	remaining: 10m 6s
4034:	learn: 0.0021122	total: 6m 51s	remaining: 10m 8s
4108:	learn: 0.0023284	total: 6m 51s	remaining: 9m 50s
3928:	learn: 0.0025949	total: 6m 51s	remaining: 10m 36s
3758:	learn: 0.0027296	total: 6m 51s	remaining: 11m 23s
4044:	learn: 0.0025742	total: 6m 51s	remaining: 10m 5s
4035:	learn: 0.0021114	total: 6m 51s	remaining: 10m 8s
4109:	learn: 0.0023276	total: 6m 51s	remaining: 9m 50s
3929:	learn: 0.0025936	total: 6m 51s	remaining: 10m 36s
4045:	learn: 0.0025737	total: 6m 51s	remaining: 10m 5s
3759:	learn: 0.0027284	total: 6m 51s	remaining: 11m 23s
4036:	learn: 0.0021105	total: 6m 51s	remaining: 10m 8s
4110:	learn: 0.0023267	total: 6m 51s	remaining: 9m 50s
3930:	learn: 0.0025923	total: 6m 51s	remaining: 10m 36s
4046:	learn: 0.0025728	total: 6m 51s	remaining: 10m 5s
4111:	learn: 0.0023260	total: 6m 52s	remaining: 9m 49s
3760:	learn: 0.0027269	total: 6m 52s	remaining: 11m 23s
4037:	learn: 0.0021096	total: 6m 52s	remaining: 10m 8s
4112:	learn: 0.0023254	total: 6m 52s	remaining: 9m 49s
3931:	learn: 0.0025914	total: 6m 52s	remaining: 10m 35s
4047:	learn: 0.0025718	total: 6m 51s	remaining: 10m 5s
3761:	learn: 0.0027259	total: 6m 52s	remaining: 11m 23s
4038:	learn: 0.0021087	total: 6m 52s	remaining: 10m 8s
4113:	learn: 0.0023246	total: 6m 52s	remaining: 9m 49s
3932:	learn: 0.0025902	total: 6m 52s	remaining: 10m 35s
3762:	learn: 0.0027251	total: 6m 52s	remaining: 11m 23s
4048:	learn: 0.0025707	total: 6m 52s	remaining: 10m 5s
4039:	learn: 0.0021077	total: 6m 52s	remaining: 10m 8s
4114:	learn: 0.0023239	total: 6m 52s	remaining: 9m 49s
4049:	learn: 0.0025698	total: 6m 52s	remaining: 10m 5s
3933:	learn: 0.0025889	total: 6m 52s	remaining: 10m 35s
3763:	learn: 0.0027236	total: 6m 52s	remaining: 11m 23s
4040:	learn: 0.0021069	total: 6m 52s	remaining: 10m 8s
4115:	learn: 0.0023230	total: 6m 52s	remaining: 9m 49s
4050:	learn: 0.0025691	total: 6m 52s	remaining: 10m 5s
3934:	learn: 0.0025881	total: 6m 52s	remaining: 10m 35s
3764:	learn: 0.0027220	total: 6m 52s	remaining: 11m 23s
4041:	learn: 0.0021063	total: 6m 52s	remaining: 10m 7s
4116:	learn: 0.0023224	total: 6m 52s	remaining: 9m 49s
4051:	learn: 0.0025682	total: 6m 52s	remaining: 10m 5s
3765:	learn: 0.0027208	total: 6m 52s	remaining: 11m 22s
3935:	learn: 0.0025869	total: 6m 52s	remaining: 10m 35s
4042:	learn: 0.0021054	total: 6m 52s	remaining: 10m 7s
4117:	learn: 0.0023218	total: 6m 52s	remaining: 9m 49s
4052:	learn: 0.0025670	total: 6m 52s	remaining: 10m 5s
4043:	learn: 0.0021047	total: 6m 52s	remaining: 10m 7s
3766:	learn: 0.0027193	total: 6m 52s	remaining: 11m 22s
3936:	learn: 0.0025855	total: 6m 52s	remaining: 10m 35s
4118:	learn: 0.0023211	total: 6m 52s	remaining: 9m 49s
4053:	learn: 0.0025664	total: 6m 52s	remaining: 10m 5s
3767:	learn: 0.0027179	total: 6m 52s	remaining: 11m 22s
4044:	learn: 0.0021040	total: 6m 52s	remaining: 10m 7s
3937:	learn: 0.0025847	total: 6m 52s	remaining: 10m 35s
4119:	learn: 0.0023199	total: 6m 52s	remaining: 9m 49s
3768:	learn: 0.0027167	total: 6m 52s	remaining: 11m 22s
4054:	learn: 0.0025654	total: 6m 52s	remaining: 10m 4s
4045:	learn: 0.0021032	total: 6m 52s	remaining: 10m 7s
3938:	learn: 0.0025839	total: 6m 52s	remaining: 10m 35s
3769:	learn: 0.0027154	total: 6m 52s	remaining: 11m 22s
4055:	learn: 0.0025646	total: 6m 52s	remaining: 10m 4s
4120:	learn: 0.0023189	total: 6m 52s	remaining: 9m 49s
4046:	learn: 0.0021023	total: 6m 52s	remaining: 10m 7s
3770:	learn: 0.0027141	total: 6m 52s	remaining: 11m 22s
3939:	learn: 0.0025830	total: 6m 52s	remaining: 10m 35s
4121:	learn: 0.0023184	total: 6m 53s	remaining: 9m 48s
4056:	learn: 0.0025638	total: 6m 52s	remaining: 10m 4s
4047:	learn: 0.0021015	total: 6m 53s	remaining: 10m 7s
3771:	learn: 0.0027132	total: 6m 53s	remaining: 11m 22s
3940:	learn: 0.0025822	total: 6m 53s	remaining: 10m 35s
4122:	learn: 0.0023172	total: 6m 53s	remaining: 9m 48s
4048:	learn: 0.0021007	total: 6m 53s	remaining: 10m 7s
4057:	learn: 0.0025627	total: 6m 52s	remaining: 10m 4s
3772:	learn: 0.0027121	total: 6m 53s	remaining: 11m 21s
3941:	learn: 0.0025808	total: 6m 53s	remaining: 10m 34s
4123:	learn: 0.0023166	total: 6m 53s	remaining: 9m 48s
4049:	learn: 0.0021005	total: 6m 53s	remaining: 10m 7s
4058:	learn: 0.0025619	total: 6m 53s	remaining: 10m 4s
3942:	learn: 0.0025800	total: 6m 53s	remaining: 10m 34s
3773:	learn: 0.0027114	total: 6m 53s	remaining: 11m 21s
4124:	learn: 0.0023159	total: 6m 53s	remaining: 9m 48s
4050:	learn: 0.0021000	total: 6m 53s	remaining: 10m 6s
3943:	learn: 0.0025788	total: 6m 53s	remaining: 10m 34s
4059:	learn: 0.0025606	total: 6m 53s	remaining: 10m 4s
3774:	learn: 0.0027100	total: 6m 53s	remaining: 11m 21s
4125:	learn: 0.0023154	total: 6m 53s	remaining: 9m 48s
3944:	learn: 0.0025774	total: 6m 53s	remaining: 10m 34s
4051:	learn: 0.0020991	total: 6m 53s	remaining: 10m 6s
4060:	learn: 0.0025595	total: 6m 53s	remaining: 10m 4s
3775:	learn: 0.0027084	total: 6m 53s	remaining: 11m 21s
4126:	learn: 0.0023147	total: 6m 53s	remaining: 9m 48s
3945:	learn: 0.0025770	total: 6m 53s	remaining: 10m 34s
4052:	learn: 0.0020986	total: 6m 53s	remaining: 10m 6s
4061:	learn: 0.0025591	total: 6m 53s	remaining: 10m 4s
4127:	learn: 0.0023140	total: 6m 53s	remaining: 9m 48s
3776:	learn: 0.0027075	total: 6m 53s	remaining: 11m 21s
3946:	learn: 0.0025757	total: 6m 53s	remaining: 10m 34s
4053:	learn: 0.0020979	total: 6m 53s	remaining: 10m 6s
4062:	learn: 0.0025585	total: 6m 53s	remaining: 10m 4s
4128:	learn: 0.0023131	total: 6m 53s	remaining: 9m 48s
3777:	learn: 0.0027068	total: 6m 53s	remaining: 11m 21s
3947:	learn: 0.0025749	total: 6m 53s	remaining: 10m 34s
4054:	learn: 0.0020979	total: 6m 53s	remaining: 10m 6s
4063:	learn: 0.0025575	total: 6m 53s	remaining: 10m 4s
4129:	learn: 0.0023121	total: 6m 53s	remaining: 9m 48s
3778:	learn: 0.0027055	total: 6m 53s	remaining: 11m 21s
3948:	learn: 0.0025737	total: 6m 53s	remaining: 10m 34s
4055:	learn: 0.0020973	total: 6m 53s	remaining: 10m 6s
4064:	learn: 0.0025567	total: 6m 53s	remaining: 10m 3s
3779:	learn: 0.0027046	total: 6m 53s	remaining: 11m 21s
4130:	learn: 0.0023111	total: 6m 53s	remaining: 9m 48s

3949:	learn: 0.0025728	total: 6m 53s	remaining: 10m 33s
4056:	learn: 0.0020962	total: 6m 53s	remaining: 10m 6s
4065:	learn: 0.0025558	total: 6m 53s	remaining: 10m 3s
3780:	learn: 0.0027032	total: 6m 54s	remaining: 11m 20s
4131:	learn: 0.0023100	total: 6m 54s	remaining: 9m 47s
3950:	learn: 0.0025719	total: 6m 54s	remaining: 10m 33s
4057:	learn: 0.0020958	total: 6m 54s	remaining: 10m 6s
4066:	learn: 0.0025552	total: 6m 53s	remaining: 10m 3s
3781:	learn: 0.0027021	total: 6m 54s	remaining: 11m 20s
4132:	learn: 0.0023092	total: 6m 54s	remaining: 9m 47s
3951:	learn: 0.0025713	total: 6m 54s	remaining: 10m 33s
4058:	learn: 0.0020949	total: 6m 54s	remaining: 10m 6s
3782:	learn: 0.0027010	total: 6m 54s	remaining: 11m 20s
4133:	learn: 0.0023086	total: 6m 54s	remaining: 9m 47s
4067:	learn: 0.0025542	total: 6m 54s	remaining: 10m 3s
3783:	learn: 0.0026993	total: 6m 54s	remaining: 11m 20s
3952:	learn: 0.0025705	total: 6m 54s	remaining: 10m 33s
4059:	learn: 0.0020940	total: 6m 54s	remaining: 10m 6s
4134:	learn: 0.0023077	total: 6m 54s	remaining: 9m 47s
4060:	learn: 0.0020930	total: 6m 54s	remaining: 10m 5s
4068:	learn: 0.0025538	total: 6m 54s	remaining: 10m 3s
3953:	learn: 0.0025697	total: 6m 54s	remaining: 10m 33s
3784:	learn: 0.0026983	total: 6m 54s	remaining: 11m 20s
4135:	learn: 0.0023070	total: 6m 54s	remaining: 9m 47s
4061:	learn: 0.0020922	total: 6m 54s	remaining: 10m 5s
4069:	learn: 0.0025527	total: 6m 54s	remaining: 10m 3s
3785:	learn: 0.0026974	total: 6m 54s	remaining: 11m 20s
3954:	learn: 0.0025687	total: 6m 54s	remaining: 10m 33s
4136:	learn: 0.0023064	total: 6m 54s	remaining: 9m 47s
4062:	learn: 0.0020917	total: 6m 54s	remaining: 10m 5s
4070:	learn: 0.0025517	total: 6m 54s	remaining: 10m 3s
3786:	learn: 0.0026961	total: 6m 54s	remaining: 11m 20s
3955:	learn: 0.0025673	total: 6m 54s	remaining: 10m 33s
4071:	learn: 0.0025511	total: 6m 54s	remaining: 10m 3s
4137:	learn: 0.0023053	total: 6m 54s	remaining: 9m 47s
4063:	learn: 0.0020910	total: 6m 54s	remaining: 10m 5s
3787:	learn: 0.0026946	total: 6m 54s	remaining: 11m 20s
3956:	learn: 0.0025664	total: 6m 54s	remaining: 10m 33s
4138:	learn: 0.0023042	total: 6m 54s	remaining: 9m 47s
4072:	learn: 0.0025500	total: 6m 54s	remaining: 10m 3s
4064:	learn: 0.0020901	total: 6m 54s	remaining: 10m 5s
4139:	learn: 0.0023034	total: 6m 54s	remaining: 9m 47s
3788:	learn: 0.0026938	total: 6m 54s	remaining: 11m 19s
3957:	learn: 0.0025652	total: 6m 54s	remaining: 10m 33s
4073:	learn: 0.0025492	total: 6m 54s	remaining: 10m 3s
4065:	learn: 0.0020891	total: 6m 54s	remaining: 10m 5s
4140:	learn: 0.0023027	total: 6m 54s	remaining: 9m 47s
3958:	learn: 0.0025642	total: 6m 54s	remaining: 10m 33s
3789:	learn: 0.0026933	total: 6m 54s	remaining: 11m 19s
4074:	learn: 0.0025482	total: 6m 54s	remaining: 10m 3s
4066:	learn: 0.0020890	total: 6m 54s	remaining: 10m 5s
3790:	learn: 0.0026921	total: 6m 54s	remaining: 11m 19s
4141:	learn: 0.0023020	total: 6m 54s	remaining: 9m 46s
3959:	learn: 0.0025634	total: 6m 54s	remaining: 10m 32s
4075:	learn: 0.0025473	total: 6m 54s	remaining: 10m 2s
4067:	learn: 0.0020884	total: 6m 55s	remaining: 10m 5s
4142:	learn: 0.0023010	total: 6m 55s	remaining: 9m 46s
3791:	learn: 0.0026914	total: 6m 55s	remaining: 11m 19s
3960:	learn: 0.0025622	total: 6m 55s	remaining: 10m 32s
4076:	learn: 0.0025467	total: 6m 54s	remaining: 10m 2s
4068:	learn: 0.0020877	total: 6m 55s	remaining: 10m 5s
4143:	learn: 0.0023002	total: 6m 55s	remaining: 9m 46s
3792:	learn: 0.0026901	total: 6m 55s	remaining: 11m 19s
3961:	learn: 0.0025606	total: 6m 55s	remaining: 10m 32s
4077:	learn: 0.0025455	total: 6m 55s	remaining: 10m 2s
4144:	learn: 0.0022993	total: 6m 55s	remaining: 9m 46s
4069:	learn: 0.0020875	total: 6m 55s	remaining: 10m 4s
3793:	learn: 0.0026894	total: 6m 55s	remaining: 11m 19s
4078:	learn: 0.0025449	total: 6m 55s	remaining: 10m 2s
3962:	learn: 0.0025598	total: 6m 55s	remaining: 10m 32s
4145:	learn: 0.0022986	total: 6m 55s	remaining: 9m 46s
4070:	learn: 0.0020865	total: 6m 55s	remaining: 10m 4s
3794:	learn: 0.0026879	total: 6m 55s	remaining: 11m 19s
4079:	learn: 0.0025441	total: 6m 55s	remaining: 10m 2s
4146:	learn: 0.0022977	total: 6m 55s	remaining: 9m 46s
4071:	learn: 0.0020865	total: 6m 55s	remaining: 10m 4s
3963:	learn: 0.0025590	total: 6m 55s	remaining: 10m 32s
4080:	learn: 0.0025434	total: 6m 55s	remaining: 10m 2s
3795:	learn: 0.0026865	total: 6m 55s	remaining: 11m 19s
4072:	learn: 0.0020858	total: 6m 55s	remaining: 10m 4s
4147:	learn: 0.0022969	total: 6m 55s	remaining: 9m 46s
3964:	learn: 0.0025581	total: 6m 55s	remaining: 10m 32s
4081:	learn: 0.0025427	total: 6m 55s	remaining: 10m 2s
3796:	learn: 0.0026859	total: 6m 55s	remaining: 11m 18s
4073:	learn: 0.0020853	total: 6m 55s	remaining: 10m 4s
3965:	learn: 0.0025570	total: 6m 55s	remaining: 10m 32s
4148:	learn: 0.0022962	total: 6m 55s	remaining: 9m 46s
4082:	learn: 0.0025417	total: 6m 55s	remaining: 10m 2s
3797:	learn: 0.0026846	total: 6m 55s	remaining: 11m 18s
4074:	learn: 0.0020843	total: 6m 55s	remaining: 10m 4s
3966:	learn: 0.0025563	total: 6m 55s	remaining: 10m 32s
4149:	learn: 0.0022955	total: 6m 55s	remaining: 9m 46s
4083:	learn: 0.0025412	total: 6m 55s	remaining: 10m 1s
4075:	learn: 0.0020835	total: 6m 55s	remaining: 10m 4s
4150:	learn: 0.0022943	total: 6m 55s	remaining: 9m 45s
3798:	learn: 0.0026838	total: 6m 55s	remaining: 11m 18s
3967:	learn: 0.0025555	total: 6m 55s	remaining: 10m 32s
4084:	learn: 0.0025401	total: 6m 55s	remaining: 10m 1s
4151:	learn: 0.0022936	total: 6m 55s	remaining: 9m 45s
4076:	learn: 0.0020828	total: 6m 55s	remaining: 10m 4s
3799:	learn: 0.0026823	total: 6m 55s	remaining: 11m 18s
3968:	learn: 0.0025542	total: 6m 55s	remaining: 10m 32s
4085:	learn: 0.0025392	total: 6m 55s	remaining: 10m 1s
4152:	learn: 0.0022930	total: 6m 56s	remaining: 9m 45s
4077:	learn: 0.0020820	total: 6m 55s	remaining: 10m 4s
3800:	learn: 0.0026812	total: 6m 56s	remaining: 11m 18s
4086:	learn: 0.0025387	total: 6m 55s	remaining: 10m 1s
3969:	learn: 0.0025533	total: 6m 56s	remaining: 10m 31s
4153:	learn: 0.0022922	total: 6m 56s	remaining: 9m 45s
4078:	learn: 0.0020815	total: 6m 56s	remaining: 10m 3s
3801:	learn: 0.0026802	total: 6m 56s	remaining: 11m 18s
4154:	learn: 0.0022915	total: 6m 56s	remaining: 9m 45s
4087:	learn: 0.0025379	total: 6m 55s	remaining: 10m 1s
3970:	learn: 0.0025519	total: 6m 56s	remaining: 10m 31s
3802:	learn: 0.0026792	total: 6m 56s	remaining: 11m 18s
4155:	learn: 0.0022908	total: 6m 56s	remaining: 9m 45s
4079:	learn: 0.0020815	total: 6m 56s	remaining: 10m 3s
4088:	learn: 0.0025368	total: 6m 56s	remaining: 10m 1s
3971:	learn: 0.0025512	total: 6m 56s	remaining: 10m 31s
4080:	learn: 0.0020806	total: 6m 56s	remaining: 10m 3s
4089:	learn: 0.0025360	total: 6m 56s	remaining: 10m 1s
4156:	learn: 0.0022901	total: 6m 56s	remaining: 9m 45s
3803:	learn: 0.0026783	total: 6m 56s	remaining: 11m 18s
3972:	learn: 0.0025504	total: 6m 56s	remaining: 10m 31s
4081:	learn: 0.0020806	total: 6m 56s	remaining: 10m 3s
4157:	learn: 0.0022889	total: 6m 56s	remaining: 9m 45s
4090:	learn: 0.0025350	total: 6m 56s	remaining: 10m 1s
3804:	learn: 0.0026775	total: 6m 56s	remaining: 11m 18s
4082:	learn: 0.0020799	total: 6m 56s	remaining: 10m 3s
3973:	learn: 0.0025495	total: 6m 56s	remaining: 10m 31s
4158:	learn: 0.0022877	total: 6m 56s	remaining: 9m 45s
4083:	learn: 0.0020791	total: 6m 56s	remaining: 10m 3s
3805:	learn: 0.0026763	total: 6m 56s	remaining: 11m 17s
4091:	learn: 0.0025345	total: 6m 56s	remaining: 10m 1s
3974:	learn: 0.0025486	total: 6m 56s	remaining: 10m 31s
4159:	learn: 0.0022865	total: 6m 56s	remaining: 9m 44s
4084:	learn: 0.0020788	total: 6m 56s	remaining: 10m 3s
4092:	learn: 0.0025334	total: 6m 56s	remaining: 10m 1s
3806:	learn: 0.0026756	total: 6m 56s	remaining: 11m 17s
4085:	learn: 0.0020780	total: 6m 56s	remaining: 10m 3s
3975:	learn: 0.0025474	total: 6m 56s	remaining: 10m 31s
4093:	learn: 0.0025323	total: 6m 56s	remaining: 10m
4160:	learn: 0.0022858	total: 6m 56s	remaining: 9m 44s
3807:	learn: 0.0026746	total: 6m 56s	remaining: 11m 17s
4086:	learn: 0.0020780	total: 6m 56s	remaining: 10m 3s
4094:	learn: 0.0025319	total: 6m 56s	remaining: 10m
3976:	learn: 0.0025461	total: 6m 56s	remaining: 10m 31s
4161:	learn: 0.0022851	total: 6m 56s	remaining: 9m 44s
4095:	learn: 0.0025308	total: 6m 56s	remaining: 10m
3808:	learn: 0.0026733	total: 6m 56s	remaining: 11m 17s
4087:	learn: 0.0020771	total: 6m 56s	remaining: 10m 2s
3977:	learn: 0.0025453	total: 6m 56s	remaining: 10m 31s
4162:	learn: 0.0022844	total: 6m 56s	remaining: 9m 44s
4096:	learn: 0.0025304	total: 6m 56s	remaining: 10m
3978:	learn: 0.0025443	total: 6m 57s	remaining: 10m 31s
3809:	learn: 0.0026723	total: 6m 57s	remaining: 11m 17s
4088:	learn: 0.0020763	total: 6m 57s	remaining: 10m 2s
4163:	learn: 0.0022839	total: 6m 57s	remaining: 9m 44s
4097:	learn: 0.0025296	total: 6m 56s	remaining: 10m
4089:	learn: 0.0020755	total: 6m 57s	remaining: 10m 2s
3979:	learn: 0.0025431	total: 6m 57s	remaining: 10m 30s
3810:	learn: 0.0026710	total: 6m 57s	remaining: 11m 17s
4164:	learn: 0.0022827	total: 6m 57s	remaining: 9m 44s
4098:	learn: 0.0025285	total: 6m 57s	remaining: 10m
4090:	learn: 0.0020748	total: 6m 57s	remaining: 10m 2s
3980:	learn: 0.0025425	total: 6m 57s	remaining: 10m 30s
4099:	learn: 0.0025276	total: 6m 57s	remaining: 10m
4165:	learn: 0.0022817	total: 6m 57s	remaining: 9m 44s
3811:	learn: 0.0026703	total: 6m 57s	remaining: 11m 17s
4091:	learn: 0.0020741	total: 6m 57s	remaining: 10m 2s
4100:	learn: 0.0025268	total: 6m 57s	remaining: 10m
4166:	learn: 0.0022810	total: 6m 57s	remaining: 9m 44s
3981:	learn: 0.0025417	total: 6m 57s	remaining: 10m 30s
4092:	learn: 0.0020729	total: 6m 57s	remaining: 10m 2s
4101:	learn: 0.0025257	total: 6m 57s	remaining: 9m 59s
3812:	learn: 0.0026694	total: 6m 57s	remaining: 11m 17s
4167:	learn: 0.0022799	total: 6m 57s	remaining: 9m 44s
4093:	learn: 0.0020722	total: 6m 57s	remaining: 10m 2s
3982:	learn: 0.0025405	total: 6m 57s	remaining: 10m 30s
4102:	learn: 0.0025245	total: 6m 57s	remaining: 9m 59s
3813:	learn: 0.0026678	total: 6m 57s	remaining: 11m 17s
4168:	learn: 0.0022792	total: 6m 57s	remaining: 9m 44s
4103:	learn: 0.0025242	total: 6m 57s	remaining: 9m 59s
3983:	learn: 0.0025394	total: 6m 57s	remaining: 10m 30s
4094:	learn: 0.0020715	total: 6m 57s	remaining: 10m 2s
4169:	learn: 0.0022780	total: 6m 57s	remaining: 9m 43s
3814:	learn: 0.0026667	total: 6m 57s	remaining: 11m 17s
4104:	learn: 0.0025236	total: 6m 57s	remaining: 9m 59s
4170:	learn: 0.0022773	total: 6m 57s	remaining: 9m 43s
3984:	learn: 0.0025386	total: 6m 57s	remaining: 10m 30s
4095:	learn: 0.0020705	total: 6m 57s	remaining: 10m 2s
4105:	learn: 0.0025231	total: 6m 57s	remaining: 9m 59s
3815:	learn: 0.0026658	total: 6m 57s	remaining: 11m 17s
4171:	learn: 0.0022763	total: 6m 57s	remaining: 9m 43s
3985:	learn: 0.0025378	total: 6m 57s	remaining: 10m 30s
4096:	learn: 0.0020696	total: 6m 57s	remaining: 10m 1s
4106:	learn: 0.0025226	total: 6m 57s	remaining: 9m 59s
4172:	learn: 0.0022754	total: 6m 57s	remaining: 9m 43s
3986:	learn: 0.0025370	total: 6m 57s	remaining: 10m 30s
3816:	learn: 0.0026647	total: 6m 57s	remaining: 11m 17s
4097:	learn: 0.0020696	total: 6m 57s	remaining: 10m 1s
4107:	learn: 0.0025216	total: 6m 57s	remaining: 9m 59s
4173:	learn: 0.0022748	total: 6m 58s	remaining: 9m 43s
4098:	learn: 0.0020688	total: 6m 57s	remaining: 10m 1s
3987:	learn: 0.0025361	total: 6m 58s	remaining: 10m 30s
3817:	learn: 0.0026641	total: 6m 58s	remaining: 11m 16s
4108:	learn: 0.0025207	total: 6m 57s	remaining: 9m 59s
4174:	learn: 0.0022739	total: 6m 58s	remaining: 9m 43s
4099:	learn: 0.0020679	total: 6m 58s	remaining: 10m 1s
4175:	learn: 0.0022733	total: 6m 58s	remaining: 9m 43s
3988:	learn: 0.0025347	total: 6m 58s	remaining: 10m 30s
4109:	learn: 0.0025197	total: 6m 57s	remaining: 9m 58s
3818:	learn: 0.0026626	total: 6m 58s	remaining: 11m 16s
4176:	learn: 0.0022726	total: 6m 58s	remaining: 9m 43s
4100:	learn: 0.0020669	total: 6m 58s	remaining: 10m 1s
4110:	learn: 0.0025187	total: 6m 58s	remaining: 9m 58s
3989:	learn: 0.0025340	total: 6m 58s	remaining: 10m 29s
3819:	learn: 0.0026619	total: 6m 58s	remaining: 11m 16s
4177:	learn: 0.0022718	total: 6m 58s	remaining: 9m 42s
4101:	learn: 0.0020660	total: 6m 58s	remaining: 10m 1s
4111:	learn: 0.0025177	total: 6m 58s	remaining: 9m 58s
4178:	learn: 0.0022712	total: 6m 58s	remaining: 9m 42s
3990:	learn: 0.0025333	total: 6m 58s	remaining: 10m 29s
3820:	learn: 0.0026609	total: 6m 58s	remaining: 11m 16s
4102:	learn: 0.0020652	total: 6m 58s	remaining: 10m 1s
4112:	learn: 0.0025165	total: 6m 58s	remaining: 9m 58s
4179:	learn: 0.0022705	total: 6m 58s	remaining: 9m 42s
3991:	learn: 0.0025319	total: 6m 58s	remaining: 10m 29s
4103:	learn: 0.0020644	total: 6m 58s	remaining: 10m 1s
3821:	learn: 0.0026595	total: 6m 58s	remaining: 11m 16s
4113:	learn: 0.0025158	total: 6m 58s	remaining: 9m 58s
4180:	learn: 0.0022699	total: 6m 58s	remaining: 9m 42s
3992:	learn: 0.0025309	total: 6m 58s	remaining: 10m 29s
4104:	learn: 0.0020636	total: 6m 58s	remaining: 10m 1s
3822:	learn: 0.0026583	total: 6m 58s	remaining: 11m 16s
4181:	learn: 0.0022687	total: 6m 58s	remaining: 9m 42s
4114:	learn: 0.0025149	total: 6m 58s	remaining: 9m 58s
3993:	learn: 0.0025303	total: 6m 58s	remaining: 10m 29s
4105:	learn: 0.0020626	total: 6m 58s	remaining: 10m 1s
4182:	learn: 0.0022681	total: 6m 58s	remaining: 9m 42s
4115:	learn: 0.0025140	total: 6m 58s	remaining: 9m 58s
3823:	learn: 0.0026573	total: 6m 58s	remaining: 11m 16s
4106:	learn: 0.0020618	total: 6m 58s	remaining: 10m
3994:	learn: 0.0025289	total: 6m 58s	remaining: 10m 29s
4183:	learn: 0.0022675	total: 6m 58s	remaining: 9m 42s
4116:	learn: 0.0025127	total: 6m 58s	remaining: 9m 58s
3824:	learn: 0.0026563	total: 6m 58s	remaining: 11m 16s
3995:	learn: 0.0025282	total: 6m 58s	remaining: 10m 29s
4107:	learn: 0.0020607	total: 6m 58s	remaining: 10m
4184:	learn: 0.0022663	total: 6m 58s	remaining: 9m 42s
4117:	learn: 0.0025116	total: 6m 58s	remaining: 9m 58s
4108:	learn: 0.0020599	total: 6m 58s	remaining: 10m
3996:	learn: 0.0025268	total: 6m 58s	remaining: 10m 29s
3825:	learn: 0.0026551	total: 6m 59s	remaining: 11m 16s
4118:	learn: 0.0025106	total: 6m 58s	remaining: 9m 57s
4185:	learn: 0.0022658	total: 6m 59s	remaining: 9m 42s
3997:	learn: 0.0025256	total: 6m 59s	remaining: 10m 29s
4109:	learn: 0.0020591	total: 6m 59s	remaining: 10m
3826:	learn: 0.0026540	total: 6m 59s	remaining: 11m 16s
4119:	learn: 0.0025094	total: 6m 58s	remaining: 9m 57s
4186:	learn: 0.0022647	total: 6m 59s	remaining: 9m 41s
4110:	learn: 0.0020582	total: 6m 59s	remaining: 10m
3998:	learn: 0.0025244	total: 6m 59s	remaining: 10m 29s
4187:	learn: 0.0022635	total: 6m 59s	remaining: 9m 41s
3827:	learn: 0.0026528	total: 6m 59s	remaining: 11m 15s
4120:	learn: 0.0025085	total: 6m 59s	remaining: 9m 57s
4188:	learn: 0.0022626	total: 6m 59s	remaining: 9m 41s
4111:	learn: 0.0020575	total: 6m 59s	remaining: 10m
3999:	learn: 0.0025237	total: 6m 59s	remaining: 10m 28s
4121:	learn: 0.0025080	total: 6m 59s	remaining: 9m 57s
3828:	learn: 0.0026516	total: 6m 59s	remaining: 11m 15s
4189:	learn: 0.0022617	total: 6m 59s	remaining: 9m 41s
4112:	learn: 0.0020567	total: 6m 59s	remaining: 10m
4000:	learn: 0.0025230	total: 6m 59s	remaining: 10m 28s
4122:	learn: 0.0025069	total: 6m 59s	remaining: 9m 57s
4190:	learn: 0.0022610	total: 6m 59s	remaining: 9m 41s
3829:	learn: 0.0026504	total: 6m 59s	remaining: 11m 15s
4113:	learn: 0.0020558	total: 6m 59s	remaining: 10m
4123:	learn: 0.0025059	total: 6m 59s	remaining: 9m 57s
4001:	learn: 0.0025222	total: 6m 59s	remaining: 10m 28s
4191:	learn: 0.0022599	total: 6m 59s	remaining: 9m 41s
3830:	learn: 0.0026490	total: 6m 59s	remaining: 11m 15s
4114:	learn: 0.0020549	total: 6m 59s	remaining: 10m
4002:	learn: 0.0025214	total: 6m 59s	remaining: 10m 28s
4124:	learn: 0.0025049	total: 6m 59s	remaining: 9m 57s
4192:	learn: 0.0022588	total: 6m 59s	remaining: 9m 41s
3831:	learn: 0.0026475	total: 6m 59s	remaining: 11m 15s
4003:	learn: 0.0025207	total: 6m 59s	remaining: 10m 28s
4115:	learn: 0.0020541	total: 6m 59s	remaining: 9m 59s
4125:	learn: 0.0025039	total: 6m 59s	remaining: 9m 57s
4193:	learn: 0.0022577	total: 6m 59s	remaining: 9m 41s
3832:	learn: 0.0026467	total: 6m 59s	remaining: 11m 15s
4116:	learn: 0.0020532	total: 6m 59s	remaining: 9m 59s
4004:	learn: 0.0025199	total: 6m 59s	remaining: 10m 28s
4126:	learn: 0.0025029	total: 6m 59s	remaining: 9m 57s
4194:	learn: 0.0022568	total: 6m 59s	remaining: 9m 40s

3833:	learn: 0.0026458	total: 6m 59s	remaining: 11m 15s
4005:	learn: 0.0025187	total: 6m 59s	remaining: 10m 28s
4127:	learn: 0.0025019	total: 6m 59s	remaining: 9m 57s
4195:	learn: 0.0022558	total: 6m 59s	remaining: 9m 40s
4117:	learn: 0.0020519	total: 6m 59s	remaining: 9m 59s
4006:	learn: 0.0025178	total: 6m 59s	remaining: 10m 28s
3834:	learn: 0.0026450	total: 7m	remaining: 11m 15s
4118:	learn: 0.0020513	total: 7m	remaining: 9m 59s
4196:	learn: 0.0022547	total: 7m	remaining: 9m 40s
4128:	learn: 0.0025009	total: 6m 59s	remaining: 9m 57s
4007:	learn: 0.0025171	total: 7m	remaining: 10m 27s
3835:	learn: 0.0026441	total: 7m	remaining: 11m 15s
4119:	learn: 0.0020508	total: 7m	remaining: 9m 59s
4197:	learn: 0.0022536	total: 7m	remaining: 9m 40s
4129:	learn: 0.0025003	total: 6m 59s	remaining: 9m 56s
4008:	learn: 0.0025158	total: 7m	remaining: 10m 27s
3836:	learn: 0.0026426	total: 7m	remaining: 11m 14s
4198:	learn: 0.0022526	total: 7m	remaining: 9m 40s
4120:	learn: 0.0020498	total: 7m	remaining: 9m 59s
4130:	learn: 0.0024993	total: 7m	remaining: 9m 56s
4009:	learn: 0.0025151	total: 7m	remaining: 10m 27s
3837:	learn: 0.0026414	total: 7m	remaining: 11m 14s
4199:	learn: 0.0022520	total: 7m	remaining: 9m 40s
4010:	learn: 0.0025143	total: 7m	remaining: 10m 27s
4121:	learn: 0.0020491	total: 7m	remaining: 9m 59s
4131:	learn: 0.0024988	total: 7m	remaining: 9m 56s
3838:	learn: 0.0026406	total: 7m	remaining: 11m 14s
4122:	learn: 0.0020484	total: 7m	remaining: 9m 59s
4011:	learn: 0.0025131	total: 7m	remaining: 10m 27s
4200:	learn: 0.0022511	total: 7m	remaining: 9m 40s
3839:	learn: 0.0026396	total: 7m	remaining: 11m 14s
4132:	learn: 0.0024980	total: 7m	remaining: 9m 56s
4123:	learn: 0.0020476	total: 7m	remaining: 9m 59s
4012:	learn: 0.0025120	total: 7m	remaining: 10m 27s
4201:	learn: 0.0022502	total: 7m	remaining: 9m 40s
3840:	learn: 0.0026384	total: 7m	remaining: 11m 14s
4124:	learn: 0.0020466	total: 7m	remaining: 9m 59s
4133:	learn: 0.0024974	total: 7m	remaining: 9m 56s
4013:	learn: 0.0025112	total: 7m	remaining: 10m 27s
4202:	learn: 0.0022495	total: 7m	remaining: 9m 40s
3841:	learn: 0.0026377	total: 7m	remaining: 11m 14s
4125:	learn: 0.0020459	total: 7m	remaining: 9m 58s
4014:	learn: 0.0025100	total: 7m	remaining: 10m 27s
4203:	learn: 0.0022486	total: 7m	remaining: 9m 40s
4134:	learn: 0.0024965	total: 7m	remaining: 9m 56s
4015:	learn: 0.0025094	total: 7m	remaining: 10m 26s
3842:	learn: 0.0026366	total: 7m	remaining: 11m 14s
4204:	learn: 0.0022477	total: 7m	remaining: 9m 39s
4126:	learn: 0.0020451	total: 7m	remaining: 9m 58s
4135:	learn: 0.0024954	total: 7m	remaining: 9m 56s
4016:	learn: 0.0025086	total: 7m	remaining: 10m 26s
4205:	learn: 0.0022470	total: 7m	remaining: 9m 39s
3843:	learn: 0.0026366	total: 7m	remaining: 11m 14s
4136:	learn: 0.0024948	total: 7m	remaining: 9m 56s
4127:	learn: 0.0020442	total: 7m	remaining: 9m 58s
4017:	learn: 0.0025079	total: 7m	remaining: 10m 26s
4206:	learn: 0.0022465	total: 7m 1s	remaining: 9m 39s
3844:	learn: 0.0026357	total: 7m 1s	remaining: 11m 14s
4137:	learn: 0.0024937	total: 7m	remaining: 9m 56s
4018:	learn: 0.0025067	total: 7m 1s	remaining: 10m 26s
4128:	learn: 0.0020433	total: 7m 1s	remaining: 9m 58s
4207:	learn: 0.0022457	total: 7m 1s	remaining: 9m 39s
4138:	learn: 0.0024924	total: 7m	remaining: 9m 56s
4019:	learn: 0.0025051	total: 7m 1s	remaining: 10m 26s
3845:	learn: 0.0026350	total: 7m 1s	remaining: 11m 13s
4208:	learn: 0.0022451	total: 7m 1s	remaining: 9m 39s
4129:	learn: 0.0020425	total: 7m 1s	remaining: 9m 58s
4139:	learn: 0.0024915	total: 7m 1s	remaining: 9m 55s
4020:	learn: 0.0025043	total: 7m 1s	remaining: 10m 26s
4209:	learn: 0.0022444	total: 7m 1s	remaining: 9m 39s
3846:	learn: 0.0026342	total: 7m 1s	remaining: 11m 13s
4130:	learn: 0.0020415	total: 7m 1s	remaining: 9m 58s
4140:	learn: 0.0024907	total: 7m 1s	remaining: 9m 55s
4210:	learn: 0.0022433	total: 7m 1s	remaining: 9m 39s
4021:	learn: 0.0025035	total: 7m 1s	remaining: 10m 26s
4131:	learn: 0.0020407	total: 7m 1s	remaining: 9m 58s
3847:	learn: 0.0026330	total: 7m 1s	remaining: 11m 13s
4211:	learn: 0.0022425	total: 7m 1s	remaining: 9m 39s
4141:	learn: 0.0024897	total: 7m 1s	remaining: 9m 55s
3848:	learn: 0.0026323	total: 7m 1s	remaining: 11m 13s
4132:	learn: 0.0020403	total: 7m 1s	remaining: 9m 58s
4022:	learn: 0.0025027	total: 7m 1s	remaining: 10m 26s
4212:	learn: 0.0022414	total: 7m 1s	remaining: 9m 39s
4142:	learn: 0.0024886	total: 7m 1s	remaining: 9m 55s
3849:	learn: 0.0026312	total: 7m 1s	remaining: 11m 13s
4133:	learn: 0.0020403	total: 7m 1s	remaining: 9m 58s
4023:	learn: 0.0025015	total: 7m 1s	remaining: 10m 26s
4143:	learn: 0.0024876	total: 7m 1s	remaining: 9m 55s
4213:	learn: 0.0022405	total: 7m 1s	remaining: 9m 38s
3850:	learn: 0.0026305	total: 7m 1s	remaining: 11m 13s
4134:	learn: 0.0020400	total: 7m 1s	remaining: 9m 58s
4024:	learn: 0.0025006	total: 7m 1s	remaining: 10m 25s
4214:	learn: 0.0022399	total: 7m 1s	remaining: 9m 38s
4144:	learn: 0.0024869	total: 7m 1s	remaining: 9m 55s
4145:	learn: 0.0024856	total: 7m 1s	remaining: 9m 55s
4215:	learn: 0.0022388	total: 7m 1s	remaining: 9m 38s
3851:	learn: 0.0026294	total: 7m 1s	remaining: 11m 13s
4025:	learn: 0.0024999	total: 7m 1s	remaining: 10m 25s
4135:	learn: 0.0020394	total: 7m 1s	remaining: 9m 58s
4146:	learn: 0.0024851	total: 7m 1s	remaining: 9m 55s
4026:	learn: 0.0024989	total: 7m 1s	remaining: 10m 25s
3852:	learn: 0.0026279	total: 7m 1s	remaining: 11m 13s
4216:	learn: 0.0022381	total: 7m 1s	remaining: 9m 38s
4136:	learn: 0.0020389	total: 7m 1s	remaining: 9m 57s
4027:	learn: 0.0024976	total: 7m 1s	remaining: 10m 25s
4217:	learn: 0.0022373	total: 7m 2s	remaining: 9m 38s
3853:	learn: 0.0026264	total: 7m 2s	remaining: 11m 13s
4147:	learn: 0.0024844	total: 7m 1s	remaining: 9m 55s
4137:	learn: 0.0020378	total: 7m 2s	remaining: 9m 57s
4028:	learn: 0.0024968	total: 7m 2s	remaining: 10m 25s
4218:	learn: 0.0022367	total: 7m 2s	remaining: 9m 38s
3854:	learn: 0.0026256	total: 7m 2s	remaining: 11m 12s
4148:	learn: 0.0024837	total: 7m 1s	remaining: 9m 55s
4138:	learn: 0.0020368	total: 7m 2s	remaining: 9m 57s
4029:	learn: 0.0024954	total: 7m 2s	remaining: 10m 25s
4219:	learn: 0.0022359	total: 7m 2s	remaining: 9m 38s
3855:	learn: 0.0026245	total: 7m 2s	remaining: 11m 12s
4139:	learn: 0.0020362	total: 7m 2s	remaining: 9m 57s
4030:	learn: 0.0024944	total: 7m 2s	remaining: 10m 25s
4149:	learn: 0.0024826	total: 7m 2s	remaining: 9m 54s
3856:	learn: 0.0026233	total: 7m 2s	remaining: 11m 12s
4220:	learn: 0.0022350	total: 7m 2s	remaining: 9m 38s
4031:	learn: 0.0024937	total: 7m 2s	remaining: 10m 25s
4150:	learn: 0.0024814	total: 7m 2s	remaining: 9m 54s
4140:	learn: 0.0020353	total: 7m 2s	remaining: 9m 57s
4221:	learn: 0.0022343	total: 7m 2s	remaining: 9m 38s
4141:	learn: 0.0020347	total: 7m 2s	remaining: 9m 57s
3857:	learn: 0.0026222	total: 7m 2s	remaining: 11m 12s
4032:	learn: 0.0024927	total: 7m 2s	remaining: 10m 25s
4151:	learn: 0.0024805	total: 7m 2s	remaining: 9m 54s
4222:	learn: 0.0022332	total: 7m 2s	remaining: 9m 38s
4142:	learn: 0.0020339	total: 7m 2s	remaining: 9m 57s
3858:	learn: 0.0026213	total: 7m 2s	remaining: 11m 12s
4033:	learn: 0.0024909	total: 7m 2s	remaining: 10m 24s
4152:	learn: 0.0024794	total: 7m 2s	remaining: 9m 54s
4143:	learn: 0.0020335	total: 7m 2s	remaining: 9m 57s
4223:	learn: 0.0022325	total: 7m 2s	remaining: 9m 37s
4153:	learn: 0.0024786	total: 7m 2s	remaining: 9m 54s
4034:	learn: 0.0024902	total: 7m 2s	remaining: 10m 24s
3859:	learn: 0.0026203	total: 7m 2s	remaining: 11m 12s
4154:	learn: 0.0024775	total: 7m 2s	remaining: 9m 54s
4144:	learn: 0.0020331	total: 7m 2s	remaining: 9m 57s
4224:	learn: 0.0022318	total: 7m 2s	remaining: 9m 37s
4035:	learn: 0.0024892	total: 7m 2s	remaining: 10m 24s
3860:	learn: 0.0026192	total: 7m 2s	remaining: 11m 12s
4145:	learn: 0.0020324	total: 7m 2s	remaining: 9m 56s
4155:	learn: 0.0024766	total: 7m 2s	remaining: 9m 54s
4225:	learn: 0.0022310	total: 7m 2s	remaining: 9m 37s
4036:	learn: 0.0024880	total: 7m 2s	remaining: 10m 24s
3861:	learn: 0.0026185	total: 7m 2s	remaining: 11m 12s
4146:	learn: 0.0020317	total: 7m 2s	remaining: 9m 56s
4156:	learn: 0.0024757	total: 7m 2s	remaining: 9m 54s
4226:	learn: 0.0022303	total: 7m 2s	remaining: 9m 37s
4037:	learn: 0.0024869	total: 7m 2s	remaining: 10m 24s
3862:	learn: 0.0026176	total: 7m 3s	remaining: 11m 12s
4147:	learn: 0.0020313	total: 7m 2s	remaining: 9m 56s
4157:	learn: 0.0024748	total: 7m 2s	remaining: 9m 54s
4227:	learn: 0.0022294	total: 7m 3s	remaining: 9m 37s
4038:	learn: 0.0024858	total: 7m 3s	remaining: 10m 24s
3863:	learn: 0.0026168	total: 7m 3s	remaining: 11m 11s
4148:	learn: 0.0020305	total: 7m 3s	remaining: 9m 56s
4039:	learn: 0.0024852	total: 7m 3s	remaining: 10m 24s
4228:	learn: 0.0022286	total: 7m 3s	remaining: 9m 37s
4158:	learn: 0.0024735	total: 7m 2s	remaining: 9m 54s
3864:	learn: 0.0026161	total: 7m 3s	remaining: 11m 11s
4149:	learn: 0.0020299	total: 7m 3s	remaining: 9m 56s
4040:	learn: 0.0024839	total: 7m 3s	remaining: 10m 24s
4229:	learn: 0.0022278	total: 7m 3s	remaining: 9m 37s
4159:	learn: 0.0024725	total: 7m 3s	remaining: 9m 53s
3865:	learn: 0.0026150	total: 7m 3s	remaining: 11m 11s
4150:	learn: 0.0020291	total: 7m 3s	remaining: 9m 56s
4041:	learn: 0.0024830	total: 7m 3s	remaining: 10m 23s
4230:	learn: 0.0022270	total: 7m 3s	remaining: 9m 37s
4151:	learn: 0.0020282	total: 7m 3s	remaining: 9m 56s
3866:	learn: 0.0026138	total: 7m 3s	remaining: 11m 11s
4160:	learn: 0.0024720	total: 7m 3s	remaining: 9m 53s
4042:	learn: 0.0024819	total: 7m 3s	remaining: 10m 23s
4231:	learn: 0.0022263	total: 7m 3s	remaining: 9m 37s
3867:	learn: 0.0026127	total: 7m 3s	remaining: 11m 11s
4152:	learn: 0.0020282	total: 7m 3s	remaining: 9m 56s
4161:	learn: 0.0024708	total: 7m 3s	remaining: 9m 53s
4043:	learn: 0.0024812	total: 7m 3s	remaining: 10m 23s
4232:	learn: 0.0022255	total: 7m 3s	remaining: 9m 37s
4153:	learn: 0.0020273	total: 7m 3s	remaining: 9m 56s
3868:	learn: 0.0026114	total: 7m 3s	remaining: 11m 11s
4162:	learn: 0.0024700	total: 7m 3s	remaining: 9m 53s
4044:	learn: 0.0024799	total: 7m 3s	remaining: 10m 23s
4154:	learn: 0.0020264	total: 7m 3s	remaining: 9m 55s
4233:	learn: 0.0022244	total: 7m 3s	remaining: 9m 37s
3869:	learn: 0.0026100	total: 7m 3s	remaining: 11m 11s
4163:	learn: 0.0024689	total: 7m 3s	remaining: 9m 53s
4045:	learn: 0.0024788	total: 7m 3s	remaining: 10m 23s
4155:	learn: 0.0020254	total: 7m 3s	remaining: 9m 55s
4234:	learn: 0.0022238	total: 7m 3s	remaining: 9m 36s
3870:	learn: 0.0026090	total: 7m 3s	remaining: 11m 11s
4046:	learn: 0.0024781	total: 7m 3s	remaining: 10m 23s
4164:	learn: 0.0024682	total: 7m 3s	remaining: 9m 53s
4156:	learn: 0.0020245	total: 7m 3s	remaining: 9m 55s
4235:	learn: 0.0022232	total: 7m 3s	remaining: 9m 36s
4165:	learn: 0.0024674	total: 7m 3s	remaining: 9m 53s
3871:	learn: 0.0026076	total: 7m 3s	remaining: 11m 10s
4047:	learn: 0.0024774	total: 7m 3s	remaining: 10m 23s
4157:	learn: 0.0020243	total: 7m 3s	remaining: 9m 55s
4236:	learn: 0.0022226	total: 7m 4s	remaining: 9m 36s
4048:	learn: 0.0024767	total: 7m 4s	remaining: 10m 23s
3872:	learn: 0.0026066	total: 7m 4s	remaining: 11m 10s
4166:	learn: 0.0024662	total: 7m 3s	remaining: 9m 53s
4158:	learn: 0.0020234	total: 7m 4s	remaining: 9m 55s
4237:	learn: 0.0022218	total: 7m 4s	remaining: 9m 36s
4049:	learn: 0.0024762	total: 7m 4s	remaining: 10m 23s
4167:	learn: 0.0024655	total: 7m 3s	remaining: 9m 53s
3873:	learn: 0.0026053	total: 7m 4s	remaining: 11m 10s
4159:	learn: 0.0020225	total: 7m 4s	remaining: 9m 55s
4238:	learn: 0.0022210	total: 7m 4s	remaining: 9m 36s
3874:	learn: 0.0026041	total: 7m 4s	remaining: 11m 10s
4168:	learn: 0.0024645	total: 7m 4s	remaining: 9m 53s
4050:	learn: 0.0024756	total: 7m 4s	remaining: 10m 23s
4160:	learn: 0.0020220	total: 7m 4s	remaining: 9m 55s
4239:	learn: 0.0022199	total: 7m 4s	remaining: 9m 36s
3875:	learn: 0.0026032	total: 7m 4s	remaining: 11m 10s
4169:	learn: 0.0024638	total: 7m 4s	remaining: 9m 53s
4161:	learn: 0.0020212	total: 7m 4s	remaining: 9m 55s
4051:	learn: 0.0024749	total: 7m 4s	remaining: 10m 22s
4240:	learn: 0.0022189	total: 7m 4s	remaining: 9m 36s
3876:	learn: 0.0026021	total: 7m 4s	remaining: 11m 10s
4170:	learn: 0.0024627	total: 7m 4s	remaining: 9m 52s
4052:	learn: 0.0024738	total: 7m 4s	remaining: 10m 22s
4241:	learn: 0.0022184	total: 7m 4s	remaining: 9m 36s
4162:	learn: 0.0020206	total: 7m 4s	remaining: 9m 55s
3877:	learn: 0.0026006	total: 7m 4s	remaining: 11m 10s
4171:	learn: 0.0024621	total: 7m 4s	remaining: 9m 52s
4053:	learn: 0.0024725	total: 7m 4s	remaining: 10m 22s
4242:	learn: 0.0022179	total: 7m 4s	remaining: 9m 36s
3878:	learn: 0.0025997	total: 7m 4s	remaining: 11m 10s
4163:	learn: 0.0020202	total: 7m 4s	remaining: 9m 55s
4172:	learn: 0.0024612	total: 7m 4s	remaining: 9m 52s
4054:	learn: 0.0024715	total: 7m 4s	remaining: 10m 22s
4164:	learn: 0.0020194	total: 7m 4s	remaining: 9m 54s
4173:	learn: 0.0024606	total: 7m 4s	remaining: 9m 52s
3879:	learn: 0.0025989	total: 7m 4s	remaining: 11m 9s
4243:	learn: 0.0022172	total: 7m 4s	remaining: 9m 36s
4055:	learn: 0.0024703	total: 7m 4s	remaining: 10m 22s
4165:	learn: 0.0020185	total: 7m 4s	remaining: 9m 54s
4174:	learn: 0.0024596	total: 7m 4s	remaining: 9m 52s
4244:	learn: 0.0022167	total: 7m 4s	remaining: 9m 35s
4056:	learn: 0.0024693	total: 7m 4s	remaining: 10m 22s
3880:	learn: 0.0025976	total: 7m 4s	remaining: 11m 9s
4166:	learn: 0.0020180	total: 7m 4s	remaining: 9m 54s
4175:	learn: 0.0024585	total: 7m 4s	remaining: 9m 52s
4245:	learn: 0.0022160	total: 7m 4s	remaining: 9m 35s
4057:	learn: 0.0024683	total: 7m 4s	remaining: 10m 22s
4167:	learn: 0.0020172	total: 7m 4s	remaining: 9m 54s
3881:	learn: 0.0025962	total: 7m 4s	remaining: 11m 9s
4176:	learn: 0.0024575	total: 7m 4s	remaining: 9m 52s
4246:	learn: 0.0022154	total: 7m 5s	remaining: 9m 35s
4168:	learn: 0.0020164	total: 7m 5s	remaining: 9m 54s
3882:	learn: 0.0025947	total: 7m 5s	remaining: 11m 9s
4058:	learn: 0.0024682	total: 7m 5s	remaining: 10m 22s
4177:	learn: 0.0024565	total: 7m 4s	remaining: 9m 52s
4169:	learn: 0.0020159	total: 7m 5s	remaining: 9m 54s
4247:	learn: 0.0022147	total: 7m 5s	remaining: 9m 35s
3883:	learn: 0.0025938	total: 7m 5s	remaining: 11m 9s
4178:	learn: 0.0024558	total: 7m 4s	remaining: 9m 51s
4059:	learn: 0.0024677	total: 7m 5s	remaining: 10m 22s
4248:	learn: 0.0022138	total: 7m 5s	remaining: 9m 35s
4170:	learn: 0.0020150	total: 7m 5s	remaining: 9m 54s
3884:	learn: 0.0025930	total: 7m 5s	remaining: 11m 9s
4179:	learn: 0.0024549	total: 7m 5s	remaining: 9m 51s
4249:	learn: 0.0022132	total: 7m 5s	remaining: 9m 35s
4060:	learn: 0.0024669	total: 7m 5s	remaining: 10m 21s
4171:	learn: 0.0020146	total: 7m 5s	remaining: 9m 54s
3885:	learn: 0.0025923	total: 7m 5s	remaining: 11m 9s
4172:	learn: 0.0020139	total: 7m 5s	remaining: 9m 53s
4180:	learn: 0.0024543	total: 7m 5s	remaining: 9m 51s
4250:	learn: 0.0022122	total: 7m 5s	remaining: 9m 35s
4061:	learn: 0.0024657	total: 7m 5s	remaining: 10m 21s
4251:	learn: 0.0022115	total: 7m 5s	remaining: 9m 35s
4181:	learn: 0.0024535	total: 7m 5s	remaining: 9m 51s
4173:	learn: 0.0020131	total: 7m 5s	remaining: 9m 53s
3886:	learn: 0.0025917	total: 7m 5s	remaining: 11m 9s
4062:	learn: 0.0024644	total: 7m 5s	remaining: 10m 21s
4182:	learn: 0.0024525	total: 7m 5s	remaining: 9m 51s
4252:	learn: 0.0022108	total: 7m 5s	remaining: 9m 35s
4174:	learn: 0.0020127	total: 7m 5s	remaining: 9m 53s
4063:	learn: 0.0024633	total: 7m 5s	remaining: 10m 21s
3887:	learn: 0.0025906	total: 7m 5s	remaining: 11m 9s
4183:	learn: 0.0024516	total: 7m 5s	remaining: 9m 51s
4175:	learn: 0.0020116	total: 7m 5s	remaining: 9m 53s
4253:	learn: 0.0022101	total: 7m 5s	remaining: 9m 35s
4064:	learn: 0.0024631	total: 7m 5s	remaining: 10m 21s
4184:	learn: 0.0024509	total: 7m 5s	remaining: 9m 51s
3888:	learn: 0.0025900	total: 7m 5s	remaining: 11m 9s
4176:	learn: 0.0020109	total: 7m 5s	remaining: 9m 53s
4254:	learn: 0.0022093	total: 7m 5s	remaining: 9m 34s
3889:	learn: 0.0025896	total: 7m 5s	remaining: 11m 8s
4185:	learn: 0.0024499	total: 7m 5s	remaining: 9m 51s
4065:	learn: 0.0024618	total: 7m 5s	remaining: 10m 21s
4255:	learn: 0.0022082	total: 7m 5s	remaining: 9m 34s
4177:	learn: 0.0020101	total: 7m 5s	remaining: 9m 53s
3890:	learn: 0.0025888	total: 7m 5s	remaining: 11m 8s
4186:	learn: 0.0024489	total: 7m 5s	remaining: 9m 51s
4256:	learn: 0.0022077	total: 7m 6s	remaining: 9m 34s
4066:	learn: 0.0024606	total: 7m 5s	remaining: 10m 21s

4178:	learn: 0.0020094	total: 7m 5s	remaining: 9m 53s
4187:	learn: 0.0024481	total: 7m 5s	remaining: 9m 50s
3891:	learn: 0.0025879	total: 7m 6s	remaining: 11m 8s
4179:	learn: 0.0020087	total: 7m 6s	remaining: 9m 53s
4067:	learn: 0.0024598	total: 7m 6s	remaining: 10m 21s
4257:	learn: 0.0022070	total: 7m 6s	remaining: 9m 34s
4188:	learn: 0.0024471	total: 7m 5s	remaining: 9m 50s
4068:	learn: 0.0024597	total: 7m 6s	remaining: 10m 21s
4180:	learn: 0.0020078	total: 7m 6s	remaining: 9m 53s
3892:	learn: 0.0025873	total: 7m 6s	remaining: 11m 8s
4258:	learn: 0.0022062	total: 7m 6s	remaining: 9m 34s
4189:	learn: 0.0024462	total: 7m 6s	remaining: 9m 50s
4069:	learn: 0.0024587	total: 7m 6s	remaining: 10m 21s
4181:	learn: 0.0020070	total: 7m 6s	remaining: 9m 52s
3893:	learn: 0.0025867	total: 7m 6s	remaining: 11m 8s
4259:	learn: 0.0022053	total: 7m 6s	remaining: 9m 34s
4190:	learn: 0.0024455	total: 7m 6s	remaining: 9m 50s
4070:	learn: 0.0024580	total: 7m 6s	remaining: 10m 20s
4182:	learn: 0.0020062	total: 7m 6s	remaining: 9m 52s
3894:	learn: 0.0025856	total: 7m 6s	remaining: 11m 8s
4260:	learn: 0.0022052	total: 7m 6s	remaining: 9m 34s
4191:	learn: 0.0024447	total: 7m 6s	remaining: 9m 50s
4071:	learn: 0.0024571	total: 7m 6s	remaining: 10m 20s
4183:	learn: 0.0020056	total: 7m 6s	remaining: 9m 52s
3895:	learn: 0.0025848	total: 7m 6s	remaining: 11m 8s
4261:	learn: 0.0022047	total: 7m 6s	remaining: 9m 34s
4192:	learn: 0.0024438	total: 7m 6s	remaining: 9m 50s
4072:	learn: 0.0024565	total: 7m 6s	remaining: 10m 20s
4184:	learn: 0.0020047	total: 7m 6s	remaining: 9m 52s
4193:	learn: 0.0024430	total: 7m 6s	remaining: 9m 50s
3896:	learn: 0.0025834	total: 7m 6s	remaining: 11m 8s
4262:	learn: 0.0022038	total: 7m 6s	remaining: 9m 34s
4073:	learn: 0.0024562	total: 7m 6s	remaining: 10m 20s
4185:	learn: 0.0020038	total: 7m 6s	remaining: 9m 52s
4194:	learn: 0.0024420	total: 7m 6s	remaining: 9m 50s
4074:	learn: 0.0024555	total: 7m 6s	remaining: 10m 20s
4263:	learn: 0.0022030	total: 7m 6s	remaining: 9m 34s
3897:	learn: 0.0025830	total: 7m 6s	remaining: 11m 8s
4186:	learn: 0.0020034	total: 7m 6s	remaining: 9m 52s
4195:	learn: 0.0024404	total: 7m 6s	remaining: 9m 50s
4264:	learn: 0.0022020	total: 7m 6s	remaining: 9m 33s
4187:	learn: 0.0020030	total: 7m 6s	remaining: 9m 52s
4075:	learn: 0.0024544	total: 7m 6s	remaining: 10m 20s
3898:	learn: 0.0025815	total: 7m 6s	remaining: 11m 8s
4196:	learn: 0.0024398	total: 7m 6s	remaining: 9m 50s
4265:	learn: 0.0022013	total: 7m 6s	remaining: 9m 33s
4188:	learn: 0.0020023	total: 7m 6s	remaining: 9m 52s
4076:	learn: 0.0024531	total: 7m 6s	remaining: 10m 20s
4197:	learn: 0.0024389	total: 7m 6s	remaining: 9m 49s
4266:	learn: 0.0022003	total: 7m 7s	remaining: 9m 33s
3899:	learn: 0.0025804	total: 7m 7s	remaining: 11m 7s
4189:	learn: 0.0020017	total: 7m 6s	remaining: 9m 52s
4198:	learn: 0.0024384	total: 7m 6s	remaining: 9m 49s
4267:	learn: 0.0021997	total: 7m 7s	remaining: 9m 33s
3900:	learn: 0.0025793	total: 7m 7s	remaining: 11m 7s
4077:	learn: 0.0024519	total: 7m 7s	remaining: 10m 20s
4190:	learn: 0.0020012	total: 7m 7s	remaining: 9m 51s
4268:	learn: 0.0021991	total: 7m 7s	remaining: 9m 33s
4199:	learn: 0.0024377	total: 7m 7s	remaining: 9m 49s
3901:	learn: 0.0025781	total: 7m 7s	remaining: 11m 7s
4078:	learn: 0.0024508	total: 7m 7s	remaining: 10m 20s
4191:	learn: 0.0020007	total: 7m 7s	remaining: 9m 51s
4200:	learn: 0.0024371	total: 7m 7s	remaining: 9m 49s
4269:	learn: 0.0021984	total: 7m 7s	remaining: 9m 33s
3902:	learn: 0.0025767	total: 7m 7s	remaining: 11m 7s
4192:	learn: 0.0020001	total: 7m 7s	remaining: 9m 51s
4201:	learn: 0.0024359	total: 7m 7s	remaining: 9m 49s
4079:	learn: 0.0024501	total: 7m 7s	remaining: 10m 20s
4270:	learn: 0.0021976	total: 7m 7s	remaining: 9m 33s
4193:	learn: 0.0019993	total: 7m 7s	remaining: 9m 51s
3903:	learn: 0.0025761	total: 7m 7s	remaining: 11m 7s
4271:	learn: 0.0021972	total: 7m 7s	remaining: 9m 33s
4080:	learn: 0.0024501	total: 7m 7s	remaining: 10m 19s
4202:	learn: 0.0024354	total: 7m 7s	remaining: 9m 49s
4194:	learn: 0.0019987	total: 7m 7s	remaining: 9m 51s
3904:	learn: 0.0025751	total: 7m 7s	remaining: 11m 7s
4272:	learn: 0.0021972	total: 7m 7s	remaining: 9m 33s
4081:	learn: 0.0024493	total: 7m 7s	remaining: 10m 19s
4203:	learn: 0.0024343	total: 7m 7s	remaining: 9m 49s
4195:	learn: 0.0019981	total: 7m 7s	remaining: 9m 51s
3905:	learn: 0.0025739	total: 7m 7s	remaining: 11m 7s
4273:	learn: 0.0021964	total: 7m 7s	remaining: 9m 32s
4196:	learn: 0.0019977	total: 7m 7s	remaining: 9m 51s
4082:	learn: 0.0024481	total: 7m 7s	remaining: 10m 19s
4204:	learn: 0.0024332	total: 7m 7s	remaining: 9m 49s
3906:	learn: 0.0025731	total: 7m 7s	remaining: 11m 7s
4274:	learn: 0.0021964	total: 7m 7s	remaining: 9m 32s
4083:	learn: 0.0024469	total: 7m 7s	remaining: 10m 19s
4205:	learn: 0.0024324	total: 7m 7s	remaining: 9m 49s
4197:	learn: 0.0019970	total: 7m 7s	remaining: 9m 51s
3907:	learn: 0.0025723	total: 7m 7s	remaining: 11m 6s
4275:	learn: 0.0021954	total: 7m 7s	remaining: 9m 32s
4084:	learn: 0.0024456	total: 7m 7s	remaining: 10m 19s
4206:	learn: 0.0024316	total: 7m 7s	remaining: 9m 48s
4198:	learn: 0.0019965	total: 7m 7s	remaining: 9m 51s
3908:	learn: 0.0025715	total: 7m 7s	remaining: 11m 6s
4276:	learn: 0.0021946	total: 7m 7s	remaining: 9m 32s
4207:	learn: 0.0024307	total: 7m 7s	remaining: 9m 48s
4199:	learn: 0.0019957	total: 7m 7s	remaining: 9m 50s
4085:	learn: 0.0024454	total: 7m 7s	remaining: 10m 19s
4277:	learn: 0.0021934	total: 7m 8s	remaining: 9m 32s
3909:	learn: 0.0025707	total: 7m 8s	remaining: 11m 6s
4200:	learn: 0.0019948	total: 7m 8s	remaining: 9m 50s
4208:	learn: 0.0024298	total: 7m 7s	remaining: 9m 48s
4086:	learn: 0.0024442	total: 7m 8s	remaining: 10m 19s
4278:	learn: 0.0021924	total: 7m 8s	remaining: 9m 32s
3910:	learn: 0.0025701	total: 7m 8s	remaining: 11m 6s
4201:	learn: 0.0019943	total: 7m 8s	remaining: 9m 50s
4087:	learn: 0.0024431	total: 7m 8s	remaining: 10m 19s
4209:	learn: 0.0024290	total: 7m 8s	remaining: 9m 48s
4279:	learn: 0.0021919	total: 7m 8s	remaining: 9m 32s
3911:	learn: 0.0025698	total: 7m 8s	remaining: 11m 6s
4202:	learn: 0.0019935	total: 7m 8s	remaining: 9m 50s
4088:	learn: 0.0024419	total: 7m 8s	remaining: 10m 19s
4210:	learn: 0.0024282	total: 7m 8s	remaining: 9m 48s
4280:	learn: 0.0021912	total: 7m 8s	remaining: 9m 32s
3912:	learn: 0.0025689	total: 7m 8s	remaining: 11m 6s
4203:	learn: 0.0019931	total: 7m 8s	remaining: 9m 50s
4089:	learn: 0.0024411	total: 7m 8s	remaining: 10m 18s
4281:	learn: 0.0021903	total: 7m 8s	remaining: 9m 32s
4211:	learn: 0.0024273	total: 7m 8s	remaining: 9m 48s
3913:	learn: 0.0025680	total: 7m 8s	remaining: 11m 6s
4204:	learn: 0.0019923	total: 7m 8s	remaining: 9m 50s
4090:	learn: 0.0024405	total: 7m 8s	remaining: 10m 18s
4282:	learn: 0.0021890	total: 7m 8s	remaining: 9m 31s
4212:	learn: 0.0024264	total: 7m 8s	remaining: 9m 48s
4283:	learn: 0.0021888	total: 7m 8s	remaining: 9m 31s
3914:	learn: 0.0025673	total: 7m 8s	remaining: 11m 6s
4205:	learn: 0.0019923	total: 7m 8s	remaining: 9m 50s
4091:	learn: 0.0024398	total: 7m 8s	remaining: 10m 18s
4213:	learn: 0.0024253	total: 7m 8s	remaining: 9m 48s
4284:	learn: 0.0021882	total: 7m 8s	remaining: 9m 31s
4206:	learn: 0.0019914	total: 7m 8s	remaining: 9m 50s
3915:	learn: 0.0025660	total: 7m 8s	remaining: 11m 6s
4092:	learn: 0.0024390	total: 7m 8s	remaining: 10m 18s
4214:	learn: 0.0024247	total: 7m 8s	remaining: 9m 48s
4285:	learn: 0.0021873	total: 7m 8s	remaining: 9m 31s
4207:	learn: 0.0019910	total: 7m 8s	remaining: 9m 50s
3916:	learn: 0.0025650	total: 7m 8s	remaining: 11m 5s
4093:	learn: 0.0024379	total: 7m 8s	remaining: 10m 18s
4286:	learn: 0.0021865	total: 7m 8s	remaining: 9m 31s
4215:	learn: 0.0024236	total: 7m 8s	remaining: 9m 48s
3917:	learn: 0.0025637	total: 7m 8s	remaining: 11m 5s
4094:	learn: 0.0024372	total: 7m 8s	remaining: 10m 18s
4208:	learn: 0.0019906	total: 7m 8s	remaining: 9m 50s
4287:	learn: 0.0021856	total: 7m 8s	remaining: 9m 31s
4095:	learn: 0.0024360	total: 7m 8s	remaining: 10m 18s
3918:	learn: 0.0025626	total: 7m 9s	remaining: 11m 5s
4216:	learn: 0.0024229	total: 7m 8s	remaining: 9m 48s
4288:	learn: 0.0021846	total: 7m 9s	remaining: 9m 31s
4209:	learn: 0.0019897	total: 7m 8s	remaining: 9m 49s
4096:	learn: 0.0024353	total: 7m 9s	remaining: 10m 18s
3919:	learn: 0.0025620	total: 7m 9s	remaining: 11m 5s
4289:	learn: 0.0021839	total: 7m 9s	remaining: 9m 31s
4217:	learn: 0.0024222	total: 7m 8s	remaining: 9m 47s
4210:	learn: 0.0019889	total: 7m 9s	remaining: 9m 49s
4097:	learn: 0.0024343	total: 7m 9s	remaining: 10m 18s
4218:	learn: 0.0024213	total: 7m 8s	remaining: 9m 47s
3920:	learn: 0.0025606	total: 7m 9s	remaining: 11m 5s
4290:	learn: 0.0021829	total: 7m 9s	remaining: 9m 31s
4211:	learn: 0.0019882	total: 7m 9s	remaining: 9m 49s
4098:	learn: 0.0024335	total: 7m 9s	remaining: 10m 17s
4219:	learn: 0.0024204	total: 7m 9s	remaining: 9m 47s
3921:	learn: 0.0025596	total: 7m 9s	remaining: 11m 5s
4212:	learn: 0.0019874	total: 7m 9s	remaining: 9m 49s
4291:	learn: 0.0021822	total: 7m 9s	remaining: 9m 31s
4099:	learn: 0.0024329	total: 7m 9s	remaining: 10m 17s
4213:	learn: 0.0019867	total: 7m 9s	remaining: 9m 49s
4220:	learn: 0.0024200	total: 7m 9s	remaining: 9m 47s
3922:	learn: 0.0025588	total: 7m 9s	remaining: 11m 5s
4292:	learn: 0.0021812	total: 7m 9s	remaining: 9m 30s
4100:	learn: 0.0024325	total: 7m 9s	remaining: 10m 17s
4221:	learn: 0.0024192	total: 7m 9s	remaining: 9m 47s
4214:	learn: 0.0019859	total: 7m 9s	remaining: 9m 49s
4293:	learn: 0.0021806	total: 7m 9s	remaining: 9m 30s
3923:	learn: 0.0025581	total: 7m 9s	remaining: 11m 5s
4101:	learn: 0.0024319	total: 7m 9s	remaining: 10m 17s
4222:	learn: 0.0024186	total: 7m 9s	remaining: 9m 47s
4215:	learn: 0.0019850	total: 7m 9s	remaining: 9m 49s
4294:	learn: 0.0021806	total: 7m 9s	remaining: 9m 30s
4102:	learn: 0.0024319	total: 7m 9s	remaining: 10m 17s
4223:	learn: 0.0024179	total: 7m 9s	remaining: 9m 47s
3924:	learn: 0.0025573	total: 7m 9s	remaining: 11m 5s
4216:	learn: 0.0019845	total: 7m 9s	remaining: 9m 49s
4295:	learn: 0.0021799	total: 7m 9s	remaining: 9m 30s
3925:	learn: 0.0025563	total: 7m 9s	remaining: 11m 4s
4224:	learn: 0.0024171	total: 7m 9s	remaining: 9m 47s
4103:	learn: 0.0024311	total: 7m 9s	remaining: 10m 17s
4217:	learn: 0.0019841	total: 7m 9s	remaining: 9m 49s
4296:	learn: 0.0021799	total: 7m 9s	remaining: 9m 30s
4104:	learn: 0.0024304	total: 7m 9s	remaining: 10m 17s
3926:	learn: 0.0025557	total: 7m 9s	remaining: 11m 4s
4225:	learn: 0.0024163	total: 7m 9s	remaining: 9m 47s
4218:	learn: 0.0019834	total: 7m 9s	remaining: 9m 48s
4297:	learn: 0.0021792	total: 7m 9s	remaining: 9m 30s
4105:	learn: 0.0024294	total: 7m 9s	remaining: 10m 17s
4226:	learn: 0.0024157	total: 7m 9s	remaining: 9m 46s
3927:	learn: 0.0025550	total: 7m 10s	remaining: 11m 4s
4219:	learn: 0.0019827	total: 7m 9s	remaining: 9m 48s
4298:	learn: 0.0021784	total: 7m 10s	remaining: 9m 30s
4106:	learn: 0.0024288	total: 7m 10s	remaining: 10m 17s
3928:	learn: 0.0025544	total: 7m 10s	remaining: 11m 4s
4227:	learn: 0.0024149	total: 7m 9s	remaining: 9m 46s
4220:	learn: 0.0019814	total: 7m 10s	remaining: 9m 48s
4299:	learn: 0.0021778	total: 7m 10s	remaining: 9m 30s
3929:	learn: 0.0025539	total: 7m 10s	remaining: 11m 4s
4107:	learn: 0.0024283	total: 7m 10s	remaining: 10m 16s
4221:	learn: 0.0019808	total: 7m 10s	remaining: 9m 48s
4300:	learn: 0.0021767	total: 7m 10s	remaining: 9m 30s
4228:	learn: 0.0024141	total: 7m 10s	remaining: 9m 46s
3930:	learn: 0.0025530	total: 7m 10s	remaining: 11m 4s
4301:	learn: 0.0021759	total: 7m 10s	remaining: 9m 29s
4108:	learn: 0.0024275	total: 7m 10s	remaining: 10m 16s
4222:	learn: 0.0019805	total: 7m 10s	remaining: 9m 48s
4229:	learn: 0.0024130	total: 7m 10s	remaining: 9m 46s
3931:	learn: 0.0025518	total: 7m 10s	remaining: 11m 4s
4302:	learn: 0.0021752	total: 7m 10s	remaining: 9m 29s
4223:	learn: 0.0019805	total: 7m 10s	remaining: 9m 48s
4230:	learn: 0.0024123	total: 7m 10s	remaining: 9m 46s
4109:	learn: 0.0024267	total: 7m 10s	remaining: 10m 16s
3932:	learn: 0.0025506	total: 7m 10s	remaining: 11m 4s
4303:	learn: 0.0021745	total: 7m 10s	remaining: 9m 29s
4224:	learn: 0.0019796	total: 7m 10s	remaining: 9m 48s
4110:	learn: 0.0024259	total: 7m 10s	remaining: 10m 16s
3933:	learn: 0.0025494	total: 7m 10s	remaining: 11m 3s
4231:	learn: 0.0024115	total: 7m 10s	remaining: 9m 46s
4304:	learn: 0.0021741	total: 7m 10s	remaining: 9m 29s
4225:	learn: 0.0019790	total: 7m 10s	remaining: 9m 48s
4111:	learn: 0.0024251	total: 7m 10s	remaining: 10m 16s
3934:	learn: 0.0025485	total: 7m 10s	remaining: 11m 3s
4232:	learn: 0.0024108	total: 7m 10s	remaining: 9m 46s
4305:	learn: 0.0021735	total: 7m 10s	remaining: 9m 29s
4226:	learn: 0.0019783	total: 7m 10s	remaining: 9m 48s
4112:	learn: 0.0024243	total: 7m 10s	remaining: 10m 16s
3935:	learn: 0.0025472	total: 7m 10s	remaining: 11m 3s
4233:	learn: 0.0024101	total: 7m 10s	remaining: 9m 46s
4306:	learn: 0.0021725	total: 7m 10s	remaining: 9m 29s
4227:	learn: 0.0019778	total: 7m 10s	remaining: 9m 48s
4234:	learn: 0.0024096	total: 7m 10s	remaining: 9m 46s
3936:	learn: 0.0025464	total: 7m 10s	remaining: 11m 3s
4113:	learn: 0.0024236	total: 7m 10s	remaining: 10m 16s
4307:	learn: 0.0021721	total: 7m 10s	remaining: 9m 29s
4228:	learn: 0.0019774	total: 7m 10s	remaining: 9m 47s
4235:	learn: 0.0024088	total: 7m 10s	remaining: 9m 46s
3937:	learn: 0.0025456	total: 7m 10s	remaining: 11m 3s
4308:	learn: 0.0021715	total: 7m 10s	remaining: 9m 29s
4114:	learn: 0.0024229	total: 7m 10s	remaining: 10m 16s
4229:	learn: 0.0019770	total: 7m 10s	remaining: 9m 47s
4236:	learn: 0.0024081	total: 7m 10s	remaining: 9m 45s
3938:	learn: 0.0025447	total: 7m 11s	remaining: 11m 3s
4309:	learn: 0.0021709	total: 7m 11s	remaining: 9m 29s
4115:	learn: 0.0024229	total: 7m 11s	remaining: 10m 16s
4230:	learn: 0.0019766	total: 7m 11s	remaining: 9m 47s
4310:	learn: 0.0021702	total: 7m 11s	remaining: 9m 28s
4237:	learn: 0.0024072	total: 7m 10s	remaining: 9m 45s
3939:	learn: 0.0025439	total: 7m 11s	remaining: 11m 3s
4116:	learn: 0.0024222	total: 7m 11s	remaining: 10m 16s
4231:	learn: 0.0019759	total: 7m 11s	remaining: 9m 47s
4311:	learn: 0.0021693	total: 7m 11s	remaining: 9m 28s
4238:	learn: 0.0024064	total: 7m 11s	remaining: 9m 45s
4117:	learn: 0.0024214	total: 7m 11s	remaining: 10m 15s
4312:	learn: 0.0021688	total: 7m 11s	remaining: 9m 28s
3940:	learn: 0.0025430	total: 7m 11s	remaining: 11m 3s
4232:	learn: 0.0019759	total: 7m 11s	remaining: 9m 47s
4239:	learn: 0.0024054	total: 7m 11s	remaining: 9m 45s
4118:	learn: 0.0024209	total: 7m 11s	remaining: 10m 15s
3941:	learn: 0.0025425	total: 7m 11s	remaining: 11m 2s
4313:	learn: 0.0021682	total: 7m 11s	remaining: 9m 28s
4119:	learn: 0.0024209	total: 7m 11s	remaining: 10m 15s
4233:	learn: 0.0019751	total: 7m 11s	remaining: 9m 47s
4240:	learn: 0.0024046	total: 7m 11s	remaining: 9m 45s
3942:	learn: 0.0025420	total: 7m 11s	remaining: 11m 2s
4314:	learn: 0.0021674	total: 7m 11s	remaining: 9m 28s
4120:	learn: 0.0024202	total: 7m 11s	remaining: 10m 15s
4234:	learn: 0.0019748	total: 7m 11s	remaining: 9m 47s
4315:	learn: 0.0021669	total: 7m 11s	remaining: 9m 28s
3943:	learn: 0.0025412	total: 7m 11s	remaining: 11m 2s
4241:	learn: 0.0024041	total: 7m 11s	remaining: 9m 45s
4235:	learn: 0.0019739	total: 7m 11s	remaining: 9m 47s
4121:	learn: 0.0024194	total: 7m 11s	remaining: 10m 15s
4316:	learn: 0.0021663	total: 7m 11s	remaining: 9m 28s
4242:	learn: 0.0024035	total: 7m 11s	remaining: 9m 45s
4236:	learn: 0.0019735	total: 7m 11s	remaining: 9m 47s
3944:	learn: 0.0025404	total: 7m 11s	remaining: 11m 2s
4122:	learn: 0.0024181	total: 7m 11s	remaining: 10m 15s
4317:	learn: 0.0021653	total: 7m 11s	remaining: 9m 28s
4243:	learn: 0.0024026	total: 7m 11s	remaining: 9m 45s
4237:	learn: 0.0019727	total: 7m 11s	remaining: 9m 46s
3945:	learn: 0.0025391	total: 7m 11s	remaining: 11m 2s
4123:	learn: 0.0024174	total: 7m 11s	remaining: 10m 15s
4244:	learn: 0.0024019	total: 7m 11s	remaining: 9m 45s
4318:	learn: 0.0021647	total: 7m 11s	remaining: 9m 28s
4238:	learn: 0.0019719	total: 7m 11s	remaining: 9m 46s
3946:	learn: 0.0025380	total: 7m 11s	remaining: 11m 2s
4245:	learn: 0.0024013	total: 7m 11s	remaining: 9m 45s
4124:	learn: 0.0024170	total: 7m 11s	remaining: 10m 15s
4319:	learn: 0.0021639	total: 7m 11s	remaining: 9m 27s
4239:	learn: 0.0019719	total: 7m 11s	remaining: 9m 46s
4125:	learn: 0.0024160	total: 7m 11s	remaining: 10m 15s
4246:	learn: 0.0024013	total: 7m 11s	remaining: 9m 44s

4320:	learn: 0.0021631	total: 7m 12s	remaining: 9m 27s
3947:	learn: 0.0025373	total: 7m 12s	remaining: 11m 2s
4240:	learn: 0.0019712	total: 7m 12s	remaining: 9m 46s
4126:	learn: 0.0024152	total: 7m 12s	remaining: 10m 14s
4247:	learn: 0.0024007	total: 7m 11s	remaining: 9m 44s
4321:	learn: 0.0021621	total: 7m 12s	remaining: 9m 27s
3948:	learn: 0.0025364	total: 7m 12s	remaining: 11m 2s
4241:	learn: 0.0019704	total: 7m 12s	remaining: 9m 46s
4127:	learn: 0.0024147	total: 7m 12s	remaining: 10m 14s
4322:	learn: 0.0021611	total: 7m 12s	remaining: 9m 27s
4248:	learn: 0.0024002	total: 7m 12s	remaining: 9m 44s
3949:	learn: 0.0025350	total: 7m 12s	remaining: 11m 2s
4242:	learn: 0.0019694	total: 7m 12s	remaining: 9m 46s
4323:	learn: 0.0021602	total: 7m 12s	remaining: 9m 27s
4128:	learn: 0.0024142	total: 7m 12s	remaining: 10m 14s
3950:	learn: 0.0025343	total: 7m 12s	remaining: 11m 1s
4249:	learn: 0.0023993	total: 7m 12s	remaining: 9m 44s
4243:	learn: 0.0019687	total: 7m 12s	remaining: 9m 46s
4324:	learn: 0.0021594	total: 7m 12s	remaining: 9m 27s
3951:	learn: 0.0025331	total: 7m 12s	remaining: 11m 1s
4250:	learn: 0.0023985	total: 7m 12s	remaining: 9m 44s
4129:	learn: 0.0024126	total: 7m 12s	remaining: 10m 14s
4244:	learn: 0.0019687	total: 7m 12s	remaining: 9m 46s
4325:	learn: 0.0021585	total: 7m 12s	remaining: 9m 27s
3952:	learn: 0.0025326	total: 7m 12s	remaining: 11m 1s
4130:	learn: 0.0024119	total: 7m 12s	remaining: 10m 14s
4251:	learn: 0.0023976	total: 7m 12s	remaining: 9m 44s
4245:	learn: 0.0019683	total: 7m 12s	remaining: 9m 46s
4326:	learn: 0.0021579	total: 7m 12s	remaining: 9m 27s
4131:	learn: 0.0024112	total: 7m 12s	remaining: 10m 14s
3953:	learn: 0.0025310	total: 7m 12s	remaining: 11m 1s
4252:	learn: 0.0023968	total: 7m 12s	remaining: 9m 44s
4246:	learn: 0.0019676	total: 7m 12s	remaining: 9m 46s
4132:	learn: 0.0024105	total: 7m 12s	remaining: 10m 14s
3954:	learn: 0.0025301	total: 7m 12s	remaining: 11m 1s
4327:	learn: 0.0021573	total: 7m 12s	remaining: 9m 27s
4253:	learn: 0.0023962	total: 7m 12s	remaining: 9m 44s
4247:	learn: 0.0019665	total: 7m 12s	remaining: 9m 45s
4328:	learn: 0.0021567	total: 7m 12s	remaining: 9m 26s
4133:	learn: 0.0024097	total: 7m 12s	remaining: 10m 14s
3955:	learn: 0.0025289	total: 7m 12s	remaining: 11m 1s
4254:	learn: 0.0023953	total: 7m 12s	remaining: 9m 44s
4329:	learn: 0.0021561	total: 7m 12s	remaining: 9m 26s
4248:	learn: 0.0019658	total: 7m 12s	remaining: 9m 45s
3956:	learn: 0.0025278	total: 7m 12s	remaining: 11m 1s
4134:	learn: 0.0024086	total: 7m 12s	remaining: 10m 14s
4255:	learn: 0.0023946	total: 7m 12s	remaining: 9m 44s
4330:	learn: 0.0021554	total: 7m 13s	remaining: 9m 26s
4249:	learn: 0.0019655	total: 7m 12s	remaining: 9m 45s
4135:	learn: 0.0024077	total: 7m 12s	remaining: 10m 13s
3957:	learn: 0.0025265	total: 7m 13s	remaining: 11m 1s
4256:	learn: 0.0023939	total: 7m 12s	remaining: 9m 43s
4331:	learn: 0.0021546	total: 7m 13s	remaining: 9m 26s
4250:	learn: 0.0019647	total: 7m 13s	remaining: 9m 45s
4136:	learn: 0.0024070	total: 7m 13s	remaining: 10m 13s
4332:	learn: 0.0021540	total: 7m 13s	remaining: 9m 26s
4257:	learn: 0.0023930	total: 7m 12s	remaining: 9m 43s
3958:	learn: 0.0025256	total: 7m 13s	remaining: 11m 1s
4251:	learn: 0.0019645	total: 7m 13s	remaining: 9m 45s
4137:	learn: 0.0024059	total: 7m 13s	remaining: 10m 13s
4258:	learn: 0.0023923	total: 7m 13s	remaining: 9m 43s
4333:	learn: 0.0021530	total: 7m 13s	remaining: 9m 26s
3959:	learn: 0.0025252	total: 7m 13s	remaining: 11m
4252:	learn: 0.0019645	total: 7m 13s	remaining: 9m 45s
4138:	learn: 0.0024052	total: 7m 13s	remaining: 10m 13s
4259:	learn: 0.0023918	total: 7m 13s	remaining: 9m 43s
3960:	learn: 0.0025241	total: 7m 13s	remaining: 11m
4334:	learn: 0.0021521	total: 7m 13s	remaining: 9m 26s
4253:	learn: 0.0019645	total: 7m 13s	remaining: 9m 45s
4260:	learn: 0.0023912	total: 7m 13s	remaining: 9m 43s
3961:	learn: 0.0025236	total: 7m 13s	remaining: 11m
4139:	learn: 0.0024047	total: 7m 13s	remaining: 10m 13s
4335:	learn: 0.0021515	total: 7m 13s	remaining: 9m 26s
4254:	learn: 0.0019637	total: 7m 13s	remaining: 9m 45s
4261:	learn: 0.0023905	total: 7m 13s	remaining: 9m 43s
4140:	learn: 0.0024031	total: 7m 13s	remaining: 10m 13s
4336:	learn: 0.0021509	total: 7m 13s	remaining: 9m 26s
3962:	learn: 0.0025228	total: 7m 13s	remaining: 11m
4255:	learn: 0.0019637	total: 7m 13s	remaining: 9m 45s
4262:	learn: 0.0023897	total: 7m 13s	remaining: 9m 43s
4141:	learn: 0.0024024	total: 7m 13s	remaining: 10m 13s
3963:	learn: 0.0025217	total: 7m 13s	remaining: 11m
4337:	learn: 0.0021504	total: 7m 13s	remaining: 9m 26s
4263:	learn: 0.0023891	total: 7m 13s	remaining: 9m 43s
4142:	learn: 0.0024017	total: 7m 13s	remaining: 10m 13s
4256:	learn: 0.0019629	total: 7m 13s	remaining: 9m 45s
4338:	learn: 0.0021499	total: 7m 13s	remaining: 9m 25s
3964:	learn: 0.0025210	total: 7m 13s	remaining: 11m
4264:	learn: 0.0023884	total: 7m 13s	remaining: 9m 43s
4143:	learn: 0.0024017	total: 7m 13s	remaining: 10m 13s
4257:	learn: 0.0019629	total: 7m 13s	remaining: 9m 44s
4339:	learn: 0.0021495	total: 7m 13s	remaining: 9m 25s
3965:	learn: 0.0025201	total: 7m 13s	remaining: 11m
4265:	learn: 0.0023876	total: 7m 13s	remaining: 9m 42s
4258:	learn: 0.0019622	total: 7m 13s	remaining: 9m 44s
4144:	learn: 0.0024009	total: 7m 13s	remaining: 10m 12s
4340:	learn: 0.0021490	total: 7m 13s	remaining: 9m 25s
4266:	learn: 0.0023869	total: 7m 13s	remaining: 9m 42s
3966:	learn: 0.0025196	total: 7m 14s	remaining: 11m
4259:	learn: 0.0019614	total: 7m 13s	remaining: 9m 44s
4145:	learn: 0.0023998	total: 7m 14s	remaining: 10m 12s
4267:	learn: 0.0023862	total: 7m 13s	remaining: 9m 42s
4341:	learn: 0.0021485	total: 7m 14s	remaining: 9m 25s
3967:	learn: 0.0025190	total: 7m 14s	remaining: 10m 59s
4260:	learn: 0.0019614	total: 7m 14s	remaining: 9m 44s
4268:	learn: 0.0023856	total: 7m 13s	remaining: 9m 42s
4146:	learn: 0.0023987	total: 7m 14s	remaining: 10m 12s
3968:	learn: 0.0025179	total: 7m 14s	remaining: 10m 59s
4342:	learn: 0.0021478	total: 7m 14s	remaining: 9m 25s
4261:	learn: 0.0019606	total: 7m 14s	remaining: 9m 44s
4147:	learn: 0.0023976	total: 7m 14s	remaining: 10m 12s
4269:	learn: 0.0023847	total: 7m 14s	remaining: 9m 42s
3969:	learn: 0.0025173	total: 7m 14s	remaining: 10m 59s
4343:	learn: 0.0021472	total: 7m 14s	remaining: 9m 25s
4262:	learn: 0.0019599	total: 7m 14s	remaining: 9m 44s
4148:	learn: 0.0023966	total: 7m 14s	remaining: 10m 12s
4270:	learn: 0.0023838	total: 7m 14s	remaining: 9m 42s
4344:	learn: 0.0021468	total: 7m 14s	remaining: 9m 25s
3970:	learn: 0.0025165	total: 7m 14s	remaining: 10m 59s
4263:	learn: 0.0019599	total: 7m 14s	remaining: 9m 44s
4149:	learn: 0.0023956	total: 7m 14s	remaining: 10m 12s
4271:	learn: 0.0023829	total: 7m 14s	remaining: 9m 42s
3971:	learn: 0.0025153	total: 7m 14s	remaining: 10m 59s
4345:	learn: 0.0021461	total: 7m 14s	remaining: 9m 25s
4150:	learn: 0.0023950	total: 7m 14s	remaining: 10m 12s
4264:	learn: 0.0019599	total: 7m 14s	remaining: 9m 44s
4272:	learn: 0.0023823	total: 7m 14s	remaining: 9m 42s
4346:	learn: 0.0021454	total: 7m 14s	remaining: 9m 25s
3972:	learn: 0.0025145	total: 7m 14s	remaining: 10m 59s
4265:	learn: 0.0019596	total: 7m 14s	remaining: 9m 44s
4273:	learn: 0.0023815	total: 7m 14s	remaining: 9m 42s
4151:	learn: 0.0023950	total: 7m 14s	remaining: 10m 12s
3973:	learn: 0.0025139	total: 7m 14s	remaining: 10m 59s
4347:	learn: 0.0021446	total: 7m 14s	remaining: 9m 25s
4266:	learn: 0.0019596	total: 7m 14s	remaining: 9m 44s
4152:	learn: 0.0023946	total: 7m 14s	remaining: 10m 12s
4274:	learn: 0.0023809	total: 7m 14s	remaining: 9m 41s
3974:	learn: 0.0025128	total: 7m 14s	remaining: 10m 59s
4348:	learn: 0.0021440	total: 7m 14s	remaining: 9m 25s
4267:	learn: 0.0019588	total: 7m 14s	remaining: 9m 43s
4153:	learn: 0.0023937	total: 7m 14s	remaining: 10m 11s
4275:	learn: 0.0023801	total: 7m 14s	remaining: 9m 41s
3975:	learn: 0.0025123	total: 7m 14s	remaining: 10m 58s
4349:	learn: 0.0021437	total: 7m 14s	remaining: 9m 24s
4154:	learn: 0.0023927	total: 7m 14s	remaining: 10m 11s
4268:	learn: 0.0019579	total: 7m 14s	remaining: 9m 43s
4276:	learn: 0.0023793	total: 7m 14s	remaining: 9m 41s
3976:	learn: 0.0025113	total: 7m 15s	remaining: 10m 58s
4155:	learn: 0.0023916	total: 7m 14s	remaining: 10m 11s
4277:	learn: 0.0023785	total: 7m 14s	remaining: 9m 41s
4350:	learn: 0.0021428	total: 7m 15s	remaining: 9m 24s
4269:	learn: 0.0019579	total: 7m 15s	remaining: 9m 43s
4156:	learn: 0.0023913	total: 7m 15s	remaining: 10m 11s
3977:	learn: 0.0025105	total: 7m 15s	remaining: 10m 58s
4351:	learn: 0.0021419	total: 7m 15s	remaining: 9m 24s
4270:	learn: 0.0019572	total: 7m 15s	remaining: 9m 43s
4278:	learn: 0.0023778	total: 7m 15s	remaining: 9m 41s
3978:	learn: 0.0025098	total: 7m 15s	remaining: 10m 58s
4157:	learn: 0.0023905	total: 7m 15s	remaining: 10m 11s
4352:	learn: 0.0021410	total: 7m 15s	remaining: 9m 24s
4271:	learn: 0.0019572	total: 7m 15s	remaining: 9m 43s
4279:	learn: 0.0023768	total: 7m 15s	remaining: 9m 41s
3979:	learn: 0.0025097	total: 7m 15s	remaining: 10m 58s
4158:	learn: 0.0023896	total: 7m 15s	remaining: 10m 11s
3980:	learn: 0.0025085	total: 7m 15s	remaining: 10m 58s
4353:	learn: 0.0021410	total: 7m 15s	remaining: 9m 24s
4272:	learn: 0.0019563	total: 7m 15s	remaining: 9m 43s
4159:	learn: 0.0023887	total: 7m 15s	remaining: 10m 11s
4280:	learn: 0.0023762	total: 7m 15s	remaining: 9m 41s
4354:	learn: 0.0021404	total: 7m 15s	remaining: 9m 24s
4160:	learn: 0.0023876	total: 7m 15s	remaining: 10m 11s
3981:	learn: 0.0025077	total: 7m 15s	remaining: 10m 58s
4273:	learn: 0.0019556	total: 7m 15s	remaining: 9m 43s
4281:	learn: 0.0023762	total: 7m 15s	remaining: 9m 41s
4355:	learn: 0.0021396	total: 7m 15s	remaining: 9m 24s
4274:	learn: 0.0019556	total: 7m 15s	remaining: 9m 43s
4161:	learn: 0.0023872	total: 7m 15s	remaining: 10m 10s
3982:	learn: 0.0025069	total: 7m 15s	remaining: 10m 58s
4282:	learn: 0.0023755	total: 7m 15s	remaining: 9m 41s
4356:	learn: 0.0021387	total: 7m 15s	remaining: 9m 24s
4275:	learn: 0.0019556	total: 7m 15s	remaining: 9m 43s
4162:	learn: 0.0023864	total: 7m 15s	remaining: 10m 10s
3983:	learn: 0.0025060	total: 7m 15s	remaining: 10m 58s
4276:	learn: 0.0019556	total: 7m 15s	remaining: 9m 42s
4357:	learn: 0.0021381	total: 7m 15s	remaining: 9m 24s
4283:	learn: 0.0023747	total: 7m 15s	remaining: 9m 41s
4163:	learn: 0.0023856	total: 7m 15s	remaining: 10m 10s
3984:	learn: 0.0025054	total: 7m 15s	remaining: 10m 57s
4277:	learn: 0.0019552	total: 7m 15s	remaining: 9m 42s
4284:	learn: 0.0023739	total: 7m 15s	remaining: 9m 41s
4358:	learn: 0.0021376	total: 7m 15s	remaining: 9m 24s
4164:	learn: 0.0023848	total: 7m 15s	remaining: 10m 10s
3985:	learn: 0.0025049	total: 7m 15s	remaining: 10m 57s
4278:	learn: 0.0019552	total: 7m 15s	remaining: 9m 42s
4285:	learn: 0.0023732	total: 7m 15s	remaining: 9m 40s
4359:	learn: 0.0021369	total: 7m 15s	remaining: 9m 23s
4165:	learn: 0.0023838	total: 7m 15s	remaining: 10m 10s
4286:	learn: 0.0023723	total: 7m 15s	remaining: 9m 40s
3986:	learn: 0.0025043	total: 7m 16s	remaining: 10m 57s
4360:	learn: 0.0021360	total: 7m 16s	remaining: 9m 23s
4279:	learn: 0.0019548	total: 7m 15s	remaining: 9m 42s
4166:	learn: 0.0023827	total: 7m 16s	remaining: 10m 10s
3987:	learn: 0.0025039	total: 7m 16s	remaining: 10m 57s
4287:	learn: 0.0023715	total: 7m 15s	remaining: 9m 40s
4280:	learn: 0.0019548	total: 7m 16s	remaining: 9m 42s
4361:	learn: 0.0021354	total: 7m 16s	remaining: 9m 23s
4167:	learn: 0.0023813	total: 7m 16s	remaining: 10m 10s
3988:	learn: 0.0025034	total: 7m 16s	remaining: 10m 57s
4288:	learn: 0.0023707	total: 7m 16s	remaining: 9m 40s
4281:	learn: 0.0019541	total: 7m 16s	remaining: 9m 42s
4362:	learn: 0.0021348	total: 7m 16s	remaining: 9m 23s
4168:	learn: 0.0023807	total: 7m 16s	remaining: 10m 10s
4363:	learn: 0.0021341	total: 7m 16s	remaining: 9m 23s
4282:	learn: 0.0019541	total: 7m 16s	remaining: 9m 42s
4289:	learn: 0.0023698	total: 7m 16s	remaining: 9m 40s
3989:	learn: 0.0025029	total: 7m 16s	remaining: 10m 57s
4169:	learn: 0.0023807	total: 7m 16s	remaining: 10m 10s
4364:	learn: 0.0021336	total: 7m 16s	remaining: 9m 23s
4283:	learn: 0.0019541	total: 7m 16s	remaining: 9m 42s
4290:	learn: 0.0023693	total: 7m 16s	remaining: 9m 40s
4170:	learn: 0.0023800	total: 7m 16s	remaining: 10m 9s
3990:	learn: 0.0025018	total: 7m 16s	remaining: 10m 57s
4284:	learn: 0.0019541	total: 7m 16s	remaining: 9m 42s
4365:	learn: 0.0021328	total: 7m 16s	remaining: 9m 23s
4291:	learn: 0.0023685	total: 7m 16s	remaining: 9m 40s
4171:	learn: 0.0023785	total: 7m 16s	remaining: 10m 9s
3991:	learn: 0.0025013	total: 7m 16s	remaining: 10m 57s
4285:	learn: 0.0019538	total: 7m 16s	remaining: 9m 42s
4366:	learn: 0.0021321	total: 7m 16s	remaining: 9m 23s
4292:	learn: 0.0023677	total: 7m 16s	remaining: 9m 40s
4172:	learn: 0.0023779	total: 7m 16s	remaining: 10m 9s
3992:	learn: 0.0025004	total: 7m 16s	remaining: 10m 56s
4293:	learn: 0.0023672	total: 7m 16s	remaining: 9m 40s
4286:	learn: 0.0019538	total: 7m 16s	remaining: 9m 41s
4367:	learn: 0.0021313	total: 7m 16s	remaining: 9m 23s
4173:	learn: 0.0023771	total: 7m 16s	remaining: 10m 9s
4294:	learn: 0.0023667	total: 7m 16s	remaining: 9m 39s
3993:	learn: 0.0024994	total: 7m 16s	remaining: 10m 56s
4174:	learn: 0.0023771	total: 7m 16s	remaining: 10m 9s
4287:	learn: 0.0019530	total: 7m 16s	remaining: 9m 41s
4368:	learn: 0.0021304	total: 7m 16s	remaining: 9m 23s
4295:	learn: 0.0023660	total: 7m 16s	remaining: 9m 39s
3994:	learn: 0.0024986	total: 7m 16s	remaining: 10m 56s
4288:	learn: 0.0019521	total: 7m 16s	remaining: 9m 41s
4175:	learn: 0.0023761	total: 7m 16s	remaining: 10m 9s
4296:	learn: 0.0023654	total: 7m 16s	remaining: 9m 39s
4369:	learn: 0.0021303	total: 7m 16s	remaining: 9m 22s
3995:	learn: 0.0024981	total: 7m 17s	remaining: 10m 56s
4289:	learn: 0.0019521	total: 7m 16s	remaining: 9m 41s
4176:	learn: 0.0023751	total: 7m 17s	remaining: 10m 9s
4297:	learn: 0.0023645	total: 7m 16s	remaining: 9m 39s
4370:	learn: 0.0021297	total: 7m 17s	remaining: 9m 22s
4290:	learn: 0.0019521	total: 7m 17s	remaining: 9m 41s
3996:	learn: 0.0024977	total: 7m 17s	remaining: 10m 56s
4298:	learn: 0.0023639	total: 7m 16s	remaining: 9m 39s
4177:	learn: 0.0023747	total: 7m 17s	remaining: 10m 9s
4371:	learn: 0.0021293	total: 7m 17s	remaining: 9m 22s
3997:	learn: 0.0024964	total: 7m 17s	remaining: 10m 56s
4291:	learn: 0.0019521	total: 7m 17s	remaining: 9m 41s
4299:	learn: 0.0023632	total: 7m 17s	remaining: 9m 39s
4178:	learn: 0.0023736	total: 7m 17s	remaining: 10m 9s
4372:	learn: 0.0021289	total: 7m 17s	remaining: 9m 22s
4292:	learn: 0.0019520	total: 7m 17s	remaining: 9m 41s
3998:	learn: 0.0024960	total: 7m 17s	remaining: 10m 56s
4373:	learn: 0.0021289	total: 7m 17s	remaining: 9m 22s
4179:	learn: 0.0023729	total: 7m 17s	remaining: 10m 8s
4300:	learn: 0.0023624	total: 7m 17s	remaining: 9m 39s
3999:	learn: 0.0024952	total: 7m 17s	remaining: 10m 56s
4293:	learn: 0.0019520	total: 7m 17s	remaining: 9m 41s
4180:	learn: 0.0023726	total: 7m 17s	remaining: 10m 8s
4374:	learn: 0.0021281	total: 7m 17s	remaining: 9m 22s
4301:	learn: 0.0023617	total: 7m 17s	remaining: 9m 39s
4000:	learn: 0.0024944	total: 7m 17s	remaining: 10m 56s
4294:	learn: 0.0019516	total: 7m 17s	remaining: 9m 41s
4375:	learn: 0.0021276	total: 7m 17s	remaining: 9m 22s
4181:	learn: 0.0023718	total: 7m 17s	remaining: 10m 8s
4302:	learn: 0.0023611	total: 7m 17s	remaining: 9m 39s
4001:	learn: 0.0024936	total: 7m 17s	remaining: 10m 55s
4376:	learn: 0.0021269	total: 7m 17s	remaining: 9m 22s
4295:	learn: 0.0019507	total: 7m 17s	remaining: 9m 41s
4303:	learn: 0.0023605	total: 7m 17s	remaining: 9m 38s
4182:	learn: 0.0023710	total: 7m 17s	remaining: 10m 8s
4377:	learn: 0.0021263	total: 7m 17s	remaining: 9m 22s
4002:	learn: 0.0024931	total: 7m 17s	remaining: 10m 55s
4296:	learn: 0.0019499	total: 7m 17s	remaining: 9m 40s
4304:	learn: 0.0023598	total: 7m 17s	remaining: 9m 38s
4183:	learn: 0.0023704	total: 7m 17s	remaining: 10m 8s
4378:	learn: 0.0021257	total: 7m 17s	remaining: 9m 21s
4003:	learn: 0.0024922	total: 7m 17s	remaining: 10m 55s
4305:	learn: 0.0023587	total: 7m 17s	remaining: 9m 38s
4297:	learn: 0.0019495	total: 7m 17s	remaining: 9m 40s
4379:	learn: 0.0021257	total: 7m 17s	remaining: 9m 21s
4184:	learn: 0.0023695	total: 7m 17s	remaining: 10m 8s
4004:	learn: 0.0024913	total: 7m 17s	remaining: 10m 55s
4306:	learn: 0.0023581	total: 7m 17s	remaining: 9m 38s
4380:	learn: 0.0021257	total: 7m 17s	remaining: 9m 21s

4298:	learn: 0.0019488	total: 7m 17s	remaining: 9m 40s
4185:	learn: 0.0023684	total: 7m 17s	remaining: 10m 8s
4005:	learn: 0.0024908	total: 7m 18s	remaining: 10m 55s
4381:	learn: 0.0021251	total: 7m 18s	remaining: 9m 21s
4307:	learn: 0.0023570	total: 7m 17s	remaining: 9m 38s
4299:	learn: 0.0019485	total: 7m 18s	remaining: 9m 40s
4006:	learn: 0.0024899	total: 7m 18s	remaining: 10m 55s
4186:	learn: 0.0023677	total: 7m 18s	remaining: 10m 8s
4382:	learn: 0.0021246	total: 7m 18s	remaining: 9m 21s
4308:	learn: 0.0023563	total: 7m 17s	remaining: 9m 38s
4300:	learn: 0.0019477	total: 7m 18s	remaining: 9m 40s
4007:	learn: 0.0024887	total: 7m 18s	remaining: 10m 55s
4187:	learn: 0.0023668	total: 7m 18s	remaining: 10m 8s
4383:	learn: 0.0021239	total: 7m 18s	remaining: 9m 21s
4301:	learn: 0.0019469	total: 7m 18s	remaining: 9m 40s
4309:	learn: 0.0023555	total: 7m 18s	remaining: 9m 38s
4008:	learn: 0.0024874	total: 7m 18s	remaining: 10m 55s
4188:	learn: 0.0023659	total: 7m 18s	remaining: 10m 8s
4384:	learn: 0.0021231	total: 7m 18s	remaining: 9m 21s
4302:	learn: 0.0019462	total: 7m 18s	remaining: 9m 40s
4189:	learn: 0.0023652	total: 7m 18s	remaining: 10m 7s
4310:	learn: 0.0023549	total: 7m 18s	remaining: 9m 38s
4009:	learn: 0.0024869	total: 7m 18s	remaining: 10m 54s
4385:	learn: 0.0021225	total: 7m 18s	remaining: 9m 21s
4303:	learn: 0.0019456	total: 7m 18s	remaining: 9m 40s
4010:	learn: 0.0024859	total: 7m 18s	remaining: 10m 54s
4311:	learn: 0.0023543	total: 7m 18s	remaining: 9m 38s
4386:	learn: 0.0021218	total: 7m 18s	remaining: 9m 21s
4190:	learn: 0.0023645	total: 7m 18s	remaining: 10m 7s
4304:	learn: 0.0019456	total: 7m 18s	remaining: 9m 40s
4312:	learn: 0.0023536	total: 7m 18s	remaining: 9m 38s
4011:	learn: 0.0024851	total: 7m 18s	remaining: 10m 54s
4387:	learn: 0.0021213	total: 7m 18s	remaining: 9m 21s
4191:	learn: 0.0023637	total: 7m 18s	remaining: 10m 7s
4305:	learn: 0.0019452	total: 7m 18s	remaining: 9m 39s
4012:	learn: 0.0024839	total: 7m 18s	remaining: 10m 54s
4313:	learn: 0.0023529	total: 7m 18s	remaining: 9m 37s
4388:	learn: 0.0021213	total: 7m 18s	remaining: 9m 20s
4192:	learn: 0.0023631	total: 7m 18s	remaining: 10m 7s
4306:	learn: 0.0019449	total: 7m 18s	remaining: 9m 39s
4013:	learn: 0.0024833	total: 7m 18s	remaining: 10m 54s
4389:	learn: 0.0021205	total: 7m 18s	remaining: 9m 20s
4314:	learn: 0.0023521	total: 7m 18s	remaining: 9m 37s
4307:	learn: 0.0019449	total: 7m 18s	remaining: 9m 39s
4193:	learn: 0.0023625	total: 7m 18s	remaining: 10m 7s
4014:	learn: 0.0024826	total: 7m 18s	remaining: 10m 54s
4390:	learn: 0.0021199	total: 7m 18s	remaining: 9m 20s
4308:	learn: 0.0019449	total: 7m 18s	remaining: 9m 39s
4315:	learn: 0.0023509	total: 7m 18s	remaining: 9m 37s
4194:	learn: 0.0023617	total: 7m 18s	remaining: 10m 7s
4015:	learn: 0.0024817	total: 7m 19s	remaining: 10m 54s
4391:	learn: 0.0021198	total: 7m 19s	remaining: 9m 20s
4309:	learn: 0.0019445	total: 7m 18s	remaining: 9m 39s
4316:	learn: 0.0023501	total: 7m 18s	remaining: 9m 37s
4195:	learn: 0.0023611	total: 7m 19s	remaining: 10m 7s
4016:	learn: 0.0024806	total: 7m 19s	remaining: 10m 54s
4392:	learn: 0.0021191	total: 7m 19s	remaining: 9m 20s
4317:	learn: 0.0023491	total: 7m 18s	remaining: 9m 37s
4310:	learn: 0.0019440	total: 7m 19s	remaining: 9m 39s
4017:	learn: 0.0024797	total: 7m 19s	remaining: 10m 53s
4196:	learn: 0.0023603	total: 7m 19s	remaining: 10m 7s
4393:	learn: 0.0021185	total: 7m 19s	remaining: 9m 20s
4018:	learn: 0.0024790	total: 7m 19s	remaining: 10m 53s
4311:	learn: 0.0019437	total: 7m 19s	remaining: 9m 39s
4318:	learn: 0.0023479	total: 7m 19s	remaining: 9m 37s
4197:	learn: 0.0023596	total: 7m 19s	remaining: 10m 7s
4394:	learn: 0.0021179	total: 7m 19s	remaining: 9m 20s
4312:	learn: 0.0019429	total: 7m 19s	remaining: 9m 39s
4198:	learn: 0.0023587	total: 7m 19s	remaining: 10m 6s
4019:	learn: 0.0024783	total: 7m 19s	remaining: 10m 53s
4319:	learn: 0.0023475	total: 7m 19s	remaining: 9m 37s
4313:	learn: 0.0019429	total: 7m 19s	remaining: 9m 39s
4395:	learn: 0.0021177	total: 7m 19s	remaining: 9m 20s
4199:	learn: 0.0023578	total: 7m 19s	remaining: 10m 6s
4320:	learn: 0.0023470	total: 7m 19s	remaining: 9m 37s
4020:	learn: 0.0024777	total: 7m 19s	remaining: 10m 53s
4314:	learn: 0.0019429	total: 7m 19s	remaining: 9m 38s
4321:	learn: 0.0023460	total: 7m 19s	remaining: 9m 37s
4396:	learn: 0.0021170	total: 7m 19s	remaining: 9m 20s
4200:	learn: 0.0023571	total: 7m 19s	remaining: 10m 6s
4021:	learn: 0.0024771	total: 7m 19s	remaining: 10m 53s
4315:	learn: 0.0019429	total: 7m 19s	remaining: 9m 38s
4397:	learn: 0.0021170	total: 7m 19s	remaining: 9m 20s
4322:	learn: 0.0023453	total: 7m 19s	remaining: 9m 37s
4022:	learn: 0.0024763	total: 7m 19s	remaining: 10m 53s
4201:	learn: 0.0023565	total: 7m 19s	remaining: 10m 6s
4323:	learn: 0.0023443	total: 7m 19s	remaining: 9m 36s
4316:	learn: 0.0019429	total: 7m 19s	remaining: 9m 38s
4398:	learn: 0.0021170	total: 7m 19s	remaining: 9m 19s
4202:	learn: 0.0023557	total: 7m 19s	remaining: 10m 6s
4023:	learn: 0.0024754	total: 7m 19s	remaining: 10m 53s
4324:	learn: 0.0023438	total: 7m 19s	remaining: 9m 36s
4317:	learn: 0.0019422	total: 7m 19s	remaining: 9m 38s
4399:	learn: 0.0021166	total: 7m 19s	remaining: 9m 19s
4203:	learn: 0.0023547	total: 7m 19s	remaining: 10m 6s
4318:	learn: 0.0019413	total: 7m 19s	remaining: 9m 38s
4024:	learn: 0.0024750	total: 7m 19s	remaining: 10m 53s
4325:	learn: 0.0023429	total: 7m 19s	remaining: 9m 36s
4400:	learn: 0.0021164	total: 7m 19s	remaining: 9m 19s
4319:	learn: 0.0019413	total: 7m 19s	remaining: 9m 38s
4204:	learn: 0.0023537	total: 7m 19s	remaining: 10m 6s
4401:	learn: 0.0021164	total: 7m 20s	remaining: 9m 19s
4326:	learn: 0.0023424	total: 7m 19s	remaining: 9m 36s
4025:	learn: 0.0024742	total: 7m 20s	remaining: 10m 53s
4205:	learn: 0.0023526	total: 7m 20s	remaining: 10m 6s
4320:	learn: 0.0019413	total: 7m 20s	remaining: 9m 38s
4402:	learn: 0.0021158	total: 7m 20s	remaining: 9m 19s
4327:	learn: 0.0023415	total: 7m 19s	remaining: 9m 36s
4026:	learn: 0.0024730	total: 7m 20s	remaining: 10m 52s
4403:	learn: 0.0021149	total: 7m 20s	remaining: 9m 19s
4321:	learn: 0.0019406	total: 7m 20s	remaining: 9m 38s
4206:	learn: 0.0023517	total: 7m 20s	remaining: 10m 6s
4328:	learn: 0.0023408	total: 7m 20s	remaining: 9m 36s
4027:	learn: 0.0024720	total: 7m 20s	remaining: 10m 52s
4404:	learn: 0.0021144	total: 7m 20s	remaining: 9m 19s
4322:	learn: 0.0019405	total: 7m 20s	remaining: 9m 38s
4329:	learn: 0.0023402	total: 7m 20s	remaining: 9m 36s
4207:	learn: 0.0023508	total: 7m 20s	remaining: 10m 6s
4405:	learn: 0.0021134	total: 7m 20s	remaining: 9m 19s
4028:	learn: 0.0024715	total: 7m 20s	remaining: 10m 52s
4330:	learn: 0.0023395	total: 7m 20s	remaining: 9m 36s
4208:	learn: 0.0023500	total: 7m 20s	remaining: 10m 5s
4323:	learn: 0.0019405	total: 7m 20s	remaining: 9m 38s
4406:	learn: 0.0021128	total: 7m 20s	remaining: 9m 18s
4029:	learn: 0.0024706	total: 7m 20s	remaining: 10m 52s
4209:	learn: 0.0023491	total: 7m 20s	remaining: 10m 5s
4331:	learn: 0.0023390	total: 7m 20s	remaining: 9m 36s
4407:	learn: 0.0021124	total: 7m 20s	remaining: 9m 18s
4324:	learn: 0.0019405	total: 7m 20s	remaining: 9m 37s
4030:	learn: 0.0024700	total: 7m 20s	remaining: 10m 52s
4210:	learn: 0.0023485	total: 7m 20s	remaining: 10m 5s
4332:	learn: 0.0023384	total: 7m 20s	remaining: 9m 36s
4408:	learn: 0.0021116	total: 7m 20s	remaining: 9m 18s
4325:	learn: 0.0019406	total: 7m 20s	remaining: 9m 37s
4211:	learn: 0.0023479	total: 7m 20s	remaining: 10m 5s
4333:	learn: 0.0023377	total: 7m 20s	remaining: 9m 35s
4409:	learn: 0.0021110	total: 7m 20s	remaining: 9m 18s
4031:	learn: 0.0024695	total: 7m 20s	remaining: 10m 52s
4326:	learn: 0.0019405	total: 7m 20s	remaining: 9m 37s
4334:	learn: 0.0023370	total: 7m 20s	remaining: 9m 35s
4212:	learn: 0.0023468	total: 7m 20s	remaining: 10m 5s
4410:	learn: 0.0021101	total: 7m 20s	remaining: 9m 18s
4032:	learn: 0.0024683	total: 7m 20s	remaining: 10m 52s
4327:	learn: 0.0019405	total: 7m 20s	remaining: 9m 37s
4335:	learn: 0.0023361	total: 7m 20s	remaining: 9m 35s
4213:	learn: 0.0023458	total: 7m 20s	remaining: 10m 5s
4411:	learn: 0.0021097	total: 7m 20s	remaining: 9m 18s
4033:	learn: 0.0024678	total: 7m 20s	remaining: 10m 52s
4328:	learn: 0.0019398	total: 7m 20s	remaining: 9m 37s
4336:	learn: 0.0023355	total: 7m 20s	remaining: 9m 35s
4214:	learn: 0.0023452	total: 7m 20s	remaining: 10m 5s
4412:	learn: 0.0021095	total: 7m 21s	remaining: 9m 18s
4034:	learn: 0.0024670	total: 7m 21s	remaining: 10m 52s
4215:	learn: 0.0023444	total: 7m 21s	remaining: 10m 5s
4337:	learn: 0.0023349	total: 7m 20s	remaining: 9m 35s
4329:	learn: 0.0019390	total: 7m 21s	remaining: 9m 37s
4413:	learn: 0.0021095	total: 7m 21s	remaining: 9m 18s
4035:	learn: 0.0024658	total: 7m 21s	remaining: 10m 51s
4216:	learn: 0.0023436	total: 7m 21s	remaining: 10m 4s
4338:	learn: 0.0023341	total: 7m 21s	remaining: 9m 35s
4414:	learn: 0.0021094	total: 7m 21s	remaining: 9m 18s
4330:	learn: 0.0019388	total: 7m 21s	remaining: 9m 37s
4036:	learn: 0.0024646	total: 7m 21s	remaining: 10m 51s
4217:	learn: 0.0023429	total: 7m 21s	remaining: 10m 4s
4415:	learn: 0.0021091	total: 7m 21s	remaining: 9m 18s
4339:	learn: 0.0023336	total: 7m 21s	remaining: 9m 35s
4331:	learn: 0.0019388	total: 7m 21s	remaining: 9m 37s
4037:	learn: 0.0024635	total: 7m 21s	remaining: 10m 51s
4218:	learn: 0.0023423	total: 7m 21s	remaining: 10m 4s
4416:	learn: 0.0021086	total: 7m 21s	remaining: 9m 17s
4340:	learn: 0.0023330	total: 7m 21s	remaining: 9m 35s
4332:	learn: 0.0019381	total: 7m 21s	remaining: 9m 37s
4038:	learn: 0.0024623	total: 7m 21s	remaining: 10m 51s
4219:	learn: 0.0023413	total: 7m 21s	remaining: 10m 4s
4417:	learn: 0.0021086	total: 7m 21s	remaining: 9m 17s
4333:	learn: 0.0019374	total: 7m 21s	remaining: 9m 37s
4341:	learn: 0.0023325	total: 7m 21s	remaining: 9m 35s
4039:	learn: 0.0024616	total: 7m 21s	remaining: 10m 51s
4220:	learn: 0.0023403	total: 7m 21s	remaining: 10m 4s
4418:	learn: 0.0021080	total: 7m 21s	remaining: 9m 17s
4342:	learn: 0.0023317	total: 7m 21s	remaining: 9m 34s
4334:	learn: 0.0019369	total: 7m 21s	remaining: 9m 37s
4221:	learn: 0.0023393	total: 7m 21s	remaining: 10m 4s
4040:	learn: 0.0024611	total: 7m 21s	remaining: 10m 51s
4419:	learn: 0.0021075	total: 7m 21s	remaining: 9m 17s
4343:	learn: 0.0023310	total: 7m 21s	remaining: 9m 34s
4335:	learn: 0.0019362	total: 7m 21s	remaining: 9m 36s
4222:	learn: 0.0023385	total: 7m 21s	remaining: 10m 4s
4041:	learn: 0.0024602	total: 7m 21s	remaining: 10m 51s
4420:	learn: 0.0021070	total: 7m 21s	remaining: 9m 17s
4344:	learn: 0.0023301	total: 7m 21s	remaining: 9m 34s
4223:	learn: 0.0023376	total: 7m 21s	remaining: 10m 4s
4336:	learn: 0.0019362	total: 7m 21s	remaining: 9m 36s
4421:	learn: 0.0021069	total: 7m 21s	remaining: 9m 17s
4042:	learn: 0.0024594	total: 7m 21s	remaining: 10m 51s
4337:	learn: 0.0019362	total: 7m 21s	remaining: 9m 36s
4224:	learn: 0.0023366	total: 7m 21s	remaining: 10m 4s
4345:	learn: 0.0023292	total: 7m 21s	remaining: 9m 34s
4422:	learn: 0.0021069	total: 7m 21s	remaining: 9m 17s
4225:	learn: 0.0023358	total: 7m 21s	remaining: 10m 3s
4043:	learn: 0.0024589	total: 7m 22s	remaining: 10m 51s
4423:	learn: 0.0021064	total: 7m 22s	remaining: 9m 17s
4338:	learn: 0.0019362	total: 7m 21s	remaining: 9m 36s
4346:	learn: 0.0023287	total: 7m 21s	remaining: 9m 34s
4226:	learn: 0.0023350	total: 7m 22s	remaining: 10m 3s
4044:	learn: 0.0024583	total: 7m 22s	remaining: 10m 50s
4424:	learn: 0.0021064	total: 7m 22s	remaining: 9m 17s
4339:	learn: 0.0019354	total: 7m 22s	remaining: 9m 36s
4347:	learn: 0.0023282	total: 7m 21s	remaining: 9m 34s
4045:	learn: 0.0024577	total: 7m 22s	remaining: 10m 50s
4425:	learn: 0.0021063	total: 7m 22s	remaining: 9m 16s
4227:	learn: 0.0023339	total: 7m 22s	remaining: 10m 3s
4340:	learn: 0.0019346	total: 7m 22s	remaining: 9m 36s
4348:	learn: 0.0023270	total: 7m 22s	remaining: 9m 34s
4046:	learn: 0.0024570	total: 7m 22s	remaining: 10m 50s
4426:	learn: 0.0021063	total: 7m 22s	remaining: 9m 16s
4228:	learn: 0.0023332	total: 7m 22s	remaining: 10m 3s
4341:	learn: 0.0019342	total: 7m 22s	remaining: 9m 36s
4349:	learn: 0.0023263	total: 7m 22s	remaining: 9m 34s
4427:	learn: 0.0021056	total: 7m 22s	remaining: 9m 16s
4047:	learn: 0.0024565	total: 7m 22s	remaining: 10m 50s
4229:	learn: 0.0023317	total: 7m 22s	remaining: 10m 3s
4342:	learn: 0.0019342	total: 7m 22s	remaining: 9m 36s
4428:	learn: 0.0021052	total: 7m 22s	remaining: 9m 16s
4350:	learn: 0.0023257	total: 7m 22s	remaining: 9m 34s
4048:	learn: 0.0024560	total: 7m 22s	remaining: 10m 50s
4429:	learn: 0.0021047	total: 7m 22s	remaining: 9m 16s
4343:	learn: 0.0019342	total: 7m 22s	remaining: 9m 36s
4230:	learn: 0.0023309	total: 7m 22s	remaining: 10m 3s
4351:	learn: 0.0023251	total: 7m 22s	remaining: 9m 34s
4049:	learn: 0.0024551	total: 7m 22s	remaining: 10m 50s
4344:	learn: 0.0019334	total: 7m 22s	remaining: 9m 36s
4430:	learn: 0.0021039	total: 7m 22s	remaining: 9m 16s
4231:	learn: 0.0023302	total: 7m 22s	remaining: 10m 3s
4050:	learn: 0.0024541	total: 7m 22s	remaining: 10m 50s
4345:	learn: 0.0019334	total: 7m 22s	remaining: 9m 35s
4352:	learn: 0.0023246	total: 7m 22s	remaining: 9m 34s
4431:	learn: 0.0021035	total: 7m 22s	remaining: 9m 16s
4232:	learn: 0.0023294	total: 7m 22s	remaining: 10m 3s
4051:	learn: 0.0024532	total: 7m 22s	remaining: 10m 50s
4353:	learn: 0.0023237	total: 7m 22s	remaining: 9m 33s
4346:	learn: 0.0019334	total: 7m 22s	remaining: 9m 35s
4432:	learn: 0.0021032	total: 7m 22s	remaining: 9m 16s
4233:	learn: 0.0023284	total: 7m 22s	remaining: 10m 3s
4354:	learn: 0.0023230	total: 7m 22s	remaining: 9m 33s
4433:	learn: 0.0021029	total: 7m 22s	remaining: 9m 16s
4052:	learn: 0.0024524	total: 7m 22s	remaining: 10m 49s
4347:	learn: 0.0019334	total: 7m 22s	remaining: 9m 35s
4355:	learn: 0.0023223	total: 7m 22s	remaining: 9m 33s
4053:	learn: 0.0024519	total: 7m 23s	remaining: 10m 49s
4234:	learn: 0.0023274	total: 7m 22s	remaining: 10m 3s
4434:	learn: 0.0021022	total: 7m 23s	remaining: 9m 15s
4348:	learn: 0.0019334	total: 7m 22s	remaining: 9m 35s
4356:	learn: 0.0023213	total: 7m 22s	remaining: 9m 33s
4435:	learn: 0.0021021	total: 7m 23s	remaining: 9m 15s
4054:	learn: 0.0024509	total: 7m 23s	remaining: 10m 49s
4349:	learn: 0.0019334	total: 7m 23s	remaining: 9m 35s
4235:	learn: 0.0023264	total: 7m 23s	remaining: 10m 2s
4357:	learn: 0.0023213	total: 7m 22s	remaining: 9m 33s
4436:	learn: 0.0021016	total: 7m 23s	remaining: 9m 15s
4055:	learn: 0.0024501	total: 7m 23s	remaining: 10m 49s
4350:	learn: 0.0019330	total: 7m 23s	remaining: 9m 35s
4056:	learn: 0.0024485	total: 7m 23s	remaining: 10m 49s
4358:	learn: 0.0023207	total: 7m 23s	remaining: 9m 33s
4437:	learn: 0.0021010	total: 7m 23s	remaining: 9m 15s
4236:	learn: 0.0023250	total: 7m 23s	remaining: 10m 2s
4351:	learn: 0.0019327	total: 7m 23s	remaining: 9m 35s
4057:	learn: 0.0024475	total: 7m 23s	remaining: 10m 49s
4359:	learn: 0.0023199	total: 7m 23s	remaining: 9m 33s
4438:	learn: 0.0021006	total: 7m 23s	remaining: 9m 15s
4352:	learn: 0.0019323	total: 7m 23s	remaining: 9m 35s
4237:	learn: 0.0023243	total: 7m 23s	remaining: 10m 2s
4058:	learn: 0.0024463	total: 7m 23s	remaining: 10m 49s
4360:	learn: 0.0023194	total: 7m 23s	remaining: 9m 33s
4439:	learn: 0.0020997	total: 7m 23s	remaining: 9m 15s
4353:	learn: 0.0019323	total: 7m 23s	remaining: 9m 35s
4238:	learn: 0.0023236	total: 7m 23s	remaining: 10m 2s
4361:	learn: 0.0023188	total: 7m 23s	remaining: 9m 33s
4059:	learn: 0.0024458	total: 7m 23s	remaining: 10m 48s
4440:	learn: 0.0020992	total: 7m 23s	remaining: 9m 15s
4354:	learn: 0.0019323	total: 7m 23s	remaining: 9m 34s
4239:	learn: 0.0023226	total: 7m 23s	remaining: 10m 2s
4060:	learn: 0.0024449	total: 7m 23s	remaining: 10m 48s
4362:	learn: 0.0023181	total: 7m 23s	remaining: 9m 32s
4355:	learn: 0.0019323	total: 7m 23s	remaining: 9m 34s
4441:	learn: 0.0020985	total: 7m 23s	remaining: 9m 15s
4240:	learn: 0.0023211	total: 7m 23s	remaining: 10m 2s
4061:	learn: 0.0024442	total: 7m 23s	remaining: 10m 48s
4363:	learn: 0.0023175	total: 7m 23s	remaining: 9m 32s
4356:	learn: 0.0019321	total: 7m 23s	remaining: 9m 34s
4442:	learn: 0.0020981	total: 7m 23s	remaining: 9m 15s
4241:	learn: 0.0023204	total: 7m 23s	remaining: 10m 2s
4062:	learn: 0.0024432	total: 7m 23s	remaining: 10m 48s
4357:	learn: 0.0019321	total: 7m 23s	remaining: 9m 34s
4364:	learn: 0.0023169	total: 7m 23s	remaining: 9m 32s
4443:	learn: 0.0020976	total: 7m 23s	remaining: 9m 14s

4242:	learn: 0.0023196	total: 7m 23s	remaining: 10m 2s
4358:	learn: 0.0019321	total: 7m 23s	remaining: 9m 34s
4063:	learn: 0.0024424	total: 7m 24s	remaining: 10m 48s
4444:	learn: 0.0020976	total: 7m 24s	remaining: 9m 14s
4365:	learn: 0.0023163	total: 7m 23s	remaining: 9m 32s
4359:	learn: 0.0019317	total: 7m 23s	remaining: 9m 34s
4243:	learn: 0.0023189	total: 7m 24s	remaining: 10m 2s
4064:	learn: 0.0024414	total: 7m 24s	remaining: 10m 48s
4366:	learn: 0.0023156	total: 7m 23s	remaining: 9m 32s
4445:	learn: 0.0020971	total: 7m 24s	remaining: 9m 14s
4360:	learn: 0.0019317	total: 7m 24s	remaining: 9m 34s
4244:	learn: 0.0023182	total: 7m 24s	remaining: 10m 2s
4065:	learn: 0.0024408	total: 7m 24s	remaining: 10m 48s
4367:	learn: 0.0023150	total: 7m 24s	remaining: 9m 32s
4361:	learn: 0.0019310	total: 7m 24s	remaining: 9m 34s
4446:	learn: 0.0020966	total: 7m 24s	remaining: 9m 14s
4245:	learn: 0.0023171	total: 7m 24s	remaining: 10m 1s
4447:	learn: 0.0020961	total: 7m 24s	remaining: 9m 14s
4362:	learn: 0.0019302	total: 7m 24s	remaining: 9m 33s
4368:	learn: 0.0023142	total: 7m 24s	remaining: 9m 32s
4066:	learn: 0.0024399	total: 7m 24s	remaining: 10m 48s
4448:	learn: 0.0020952	total: 7m 24s	remaining: 9m 14s
4369:	learn: 0.0023133	total: 7m 24s	remaining: 9m 32s
4246:	learn: 0.0023164	total: 7m 24s	remaining: 10m 1s
4363:	learn: 0.0019301	total: 7m 24s	remaining: 9m 33s
4067:	learn: 0.0024388	total: 7m 24s	remaining: 10m 48s
4247:	learn: 0.0023155	total: 7m 24s	remaining: 10m 1s
4449:	learn: 0.0020947	total: 7m 24s	remaining: 9m 14s
4370:	learn: 0.0023129	total: 7m 24s	remaining: 9m 32s
4364:	learn: 0.0019301	total: 7m 24s	remaining: 9m 33s
4068:	learn: 0.0024378	total: 7m 24s	remaining: 10m 48s
4248:	learn: 0.0023146	total: 7m 24s	remaining: 10m 1s
4371:	learn: 0.0023119	total: 7m 24s	remaining: 9m 32s
4450:	learn: 0.0020940	total: 7m 24s	remaining: 9m 14s
4365:	learn: 0.0019294	total: 7m 24s	remaining: 9m 33s
4069:	learn: 0.0024372	total: 7m 24s	remaining: 10m 47s
4249:	learn: 0.0023139	total: 7m 24s	remaining: 10m 1s
4372:	learn: 0.0023114	total: 7m 24s	remaining: 9m 31s
4451:	learn: 0.0020935	total: 7m 24s	remaining: 9m 14s
4366:	learn: 0.0019288	total: 7m 24s	remaining: 9m 33s
4070:	learn: 0.0024367	total: 7m 24s	remaining: 10m 47s
4373:	learn: 0.0023110	total: 7m 24s	remaining: 9m 31s
4250:	learn: 0.0023132	total: 7m 24s	remaining: 10m 1s
4452:	learn: 0.0020930	total: 7m 24s	remaining: 9m 14s
4367:	learn: 0.0019280	total: 7m 24s	remaining: 9m 33s
4071:	learn: 0.0024362	total: 7m 24s	remaining: 10m 47s
4453:	learn: 0.0020924	total: 7m 24s	remaining: 9m 13s
4374:	learn: 0.0023103	total: 7m 24s	remaining: 9m 31s
4368:	learn: 0.0019280	total: 7m 24s	remaining: 9m 33s
4251:	learn: 0.0023125	total: 7m 24s	remaining: 10m 1s
4454:	learn: 0.0020918	total: 7m 24s	remaining: 9m 13s
4072:	learn: 0.0024357	total: 7m 24s	remaining: 10m 47s
4375:	learn: 0.0023098	total: 7m 24s	remaining: 9m 31s
4369:	learn: 0.0019280	total: 7m 24s	remaining: 9m 33s
4252:	learn: 0.0023115	total: 7m 24s	remaining: 10m 1s
4455:	learn: 0.0020912	total: 7m 25s	remaining: 9m 13s
4073:	learn: 0.0024346	total: 7m 25s	remaining: 10m 47s
4370:	learn: 0.0019273	total: 7m 25s	remaining: 9m 33s
4376:	learn: 0.0023087	total: 7m 24s	remaining: 9m 31s
4253:	learn: 0.0023106	total: 7m 25s	remaining: 10m 1s
4456:	learn: 0.0020907	total: 7m 25s	remaining: 9m 13s
4074:	learn: 0.0024336	total: 7m 25s	remaining: 10m 47s
4371:	learn: 0.0019267	total: 7m 25s	remaining: 9m 32s
4254:	learn: 0.0023094	total: 7m 25s	remaining: 10m 1s
4377:	learn: 0.0023078	total: 7m 25s	remaining: 9m 31s
4457:	learn: 0.0020899	total: 7m 25s	remaining: 9m 13s
4075:	learn: 0.0024327	total: 7m 25s	remaining: 10m 47s
4372:	learn: 0.0019259	total: 7m 25s	remaining: 9m 32s
4378:	learn: 0.0023074	total: 7m 25s	remaining: 9m 31s
4255:	learn: 0.0023084	total: 7m 25s	remaining: 10m
4076:	learn: 0.0024324	total: 7m 25s	remaining: 10m 47s
4458:	learn: 0.0020892	total: 7m 25s	remaining: 9m 13s
4373:	learn: 0.0019251	total: 7m 25s	remaining: 9m 32s
4256:	learn: 0.0023077	total: 7m 25s	remaining: 10m
4379:	learn: 0.0023068	total: 7m 25s	remaining: 9m 31s
4459:	learn: 0.0020884	total: 7m 25s	remaining: 9m 13s
4077:	learn: 0.0024318	total: 7m 25s	remaining: 10m 46s
4374:	learn: 0.0019251	total: 7m 25s	remaining: 9m 32s
4380:	learn: 0.0023058	total: 7m 25s	remaining: 9m 31s
4257:	learn: 0.0023068	total: 7m 25s	remaining: 10m
4460:	learn: 0.0020875	total: 7m 25s	remaining: 9m 13s
4375:	learn: 0.0019247	total: 7m 25s	remaining: 9m 32s
4078:	learn: 0.0024308	total: 7m 25s	remaining: 10m 46s
4381:	learn: 0.0023052	total: 7m 25s	remaining: 9m 31s
4461:	learn: 0.0020870	total: 7m 25s	remaining: 9m 13s
4258:	learn: 0.0023061	total: 7m 25s	remaining: 10m
4376:	learn: 0.0019247	total: 7m 25s	remaining: 9m 32s
4462:	learn: 0.0020862	total: 7m 25s	remaining: 9m 12s
4079:	learn: 0.0024298	total: 7m 25s	remaining: 10m 46s
4382:	learn: 0.0023045	total: 7m 25s	remaining: 9m 30s
4259:	learn: 0.0023051	total: 7m 25s	remaining: 10m
4463:	learn: 0.0020861	total: 7m 25s	remaining: 9m 12s
4377:	learn: 0.0019240	total: 7m 25s	remaining: 9m 32s
4383:	learn: 0.0023039	total: 7m 25s	remaining: 9m 30s
4080:	learn: 0.0024290	total: 7m 25s	remaining: 10m 46s
4464:	learn: 0.0020856	total: 7m 25s	remaining: 9m 12s
4260:	learn: 0.0023041	total: 7m 25s	remaining: 10m
4378:	learn: 0.0019233	total: 7m 25s	remaining: 9m 32s
4384:	learn: 0.0023029	total: 7m 25s	remaining: 9m 30s
4081:	learn: 0.0024282	total: 7m 25s	remaining: 10m 46s
4465:	learn: 0.0020846	total: 7m 25s	remaining: 9m 12s
4379:	learn: 0.0019224	total: 7m 25s	remaining: 9m 32s
4261:	learn: 0.0023027	total: 7m 25s	remaining: 10m
4082:	learn: 0.0024277	total: 7m 26s	remaining: 10m 46s
4385:	learn: 0.0023024	total: 7m 25s	remaining: 9m 30s
4466:	learn: 0.0020841	total: 7m 26s	remaining: 9m 12s
4380:	learn: 0.0019221	total: 7m 25s	remaining: 9m 32s
4262:	learn: 0.0023018	total: 7m 26s	remaining: 10m
4083:	learn: 0.0024264	total: 7m 26s	remaining: 10m 46s
4381:	learn: 0.0019214	total: 7m 26s	remaining: 9m 31s
4386:	learn: 0.0023018	total: 7m 25s	remaining: 9m 30s
4263:	learn: 0.0023010	total: 7m 26s	remaining: 10m
4467:	learn: 0.0020835	total: 7m 26s	remaining: 9m 12s
4084:	learn: 0.0024254	total: 7m 26s	remaining: 10m 46s
4382:	learn: 0.0019210	total: 7m 26s	remaining: 9m 31s
4264:	learn: 0.0022999	total: 7m 26s	remaining: 10m
4387:	learn: 0.0023013	total: 7m 26s	remaining: 9m 30s
4468:	learn: 0.0020828	total: 7m 26s	remaining: 9m 12s
4085:	learn: 0.0024250	total: 7m 26s	remaining: 10m 46s
4265:	learn: 0.0022992	total: 7m 26s	remaining: 9m 59s
4383:	learn: 0.0019210	total: 7m 26s	remaining: 9m 31s
4388:	learn: 0.0023006	total: 7m 26s	remaining: 9m 30s
4469:	learn: 0.0020822	total: 7m 26s	remaining: 9m 12s
4086:	learn: 0.0024240	total: 7m 26s	remaining: 10m 45s
4266:	learn: 0.0022978	total: 7m 26s	remaining: 9m 59s
4389:	learn: 0.0022998	total: 7m 26s	remaining: 9m 30s
4470:	learn: 0.0020818	total: 7m 26s	remaining: 9m 12s
4384:	learn: 0.0019210	total: 7m 26s	remaining: 9m 31s
4087:	learn: 0.0024229	total: 7m 26s	remaining: 10m 45s
4267:	learn: 0.0022967	total: 7m 26s	remaining: 9m 59s
4471:	learn: 0.0020808	total: 7m 26s	remaining: 9m 12s
4385:	learn: 0.0019203	total: 7m 26s	remaining: 9m 31s
4390:	learn: 0.0022992	total: 7m 26s	remaining: 9m 30s
4088:	learn: 0.0024221	total: 7m 26s	remaining: 10m 45s
4268:	learn: 0.0022965	total: 7m 26s	remaining: 9m 59s
4472:	learn: 0.0020801	total: 7m 26s	remaining: 9m 11s
4089:	learn: 0.0024211	total: 7m 26s	remaining: 10m 45s
4386:	learn: 0.0019203	total: 7m 26s	remaining: 9m 31s
4391:	learn: 0.0022982	total: 7m 26s	remaining: 9m 30s
4269:	learn: 0.0022958	total: 7m 26s	remaining: 9m 59s
4473:	learn: 0.0020794	total: 7m 26s	remaining: 9m 11s
4090:	learn: 0.0024201	total: 7m 26s	remaining: 10m 45s
4387:	learn: 0.0019203	total: 7m 26s	remaining: 9m 31s
4392:	learn: 0.0022973	total: 7m 26s	remaining: 9m 30s
4270:	learn: 0.0022944	total: 7m 26s	remaining: 9m 59s
4091:	learn: 0.0024193	total: 7m 26s	remaining: 10m 45s
4474:	learn: 0.0020788	total: 7m 26s	remaining: 9m 11s
4388:	learn: 0.0019203	total: 7m 26s	remaining: 9m 31s
4393:	learn: 0.0022966	total: 7m 26s	remaining: 9m 30s
4389:	learn: 0.0019195	total: 7m 26s	remaining: 9m 31s
4271:	learn: 0.0022936	total: 7m 26s	remaining: 9m 59s
4475:	learn: 0.0020784	total: 7m 26s	remaining: 9m 11s
4092:	learn: 0.0024183	total: 7m 27s	remaining: 10m 45s
4394:	learn: 0.0022959	total: 7m 26s	remaining: 9m 29s
4390:	learn: 0.0019195	total: 7m 26s	remaining: 9m 30s
4476:	learn: 0.0020776	total: 7m 27s	remaining: 9m 11s
4093:	learn: 0.0024171	total: 7m 27s	remaining: 10m 44s
4272:	learn: 0.0022933	total: 7m 27s	remaining: 9m 59s
4395:	learn: 0.0022954	total: 7m 26s	remaining: 9m 29s
4391:	learn: 0.0019191	total: 7m 27s	remaining: 9m 30s
4094:	learn: 0.0024159	total: 7m 27s	remaining: 10m 44s
4273:	learn: 0.0022926	total: 7m 27s	remaining: 9m 59s
4477:	learn: 0.0020769	total: 7m 27s	remaining: 9m 11s
4095:	learn: 0.0024154	total: 7m 27s	remaining: 10m 44s
4392:	learn: 0.0019183	total: 7m 27s	remaining: 9m 30s
4396:	learn: 0.0022945	total: 7m 27s	remaining: 9m 29s
4274:	learn: 0.0022920	total: 7m 27s	remaining: 9m 58s
4478:	learn: 0.0020762	total: 7m 27s	remaining: 9m 11s
4096:	learn: 0.0024147	total: 7m 27s	remaining: 10m 44s
4393:	learn: 0.0019176	total: 7m 27s	remaining: 9m 30s
4275:	learn: 0.0022914	total: 7m 27s	remaining: 9m 58s
4397:	learn: 0.0022939	total: 7m 27s	remaining: 9m 29s
4097:	learn: 0.0024141	total: 7m 27s	remaining: 10m 44s
4479:	learn: 0.0020757	total: 7m 27s	remaining: 9m 11s
4394:	learn: 0.0019176	total: 7m 27s	remaining: 9m 30s
4480:	learn: 0.0020752	total: 7m 27s	remaining: 9m 11s
4276:	learn: 0.0022913	total: 7m 27s	remaining: 9m 58s
4098:	learn: 0.0024131	total: 7m 27s	remaining: 10m 44s
4395:	learn: 0.0019173	total: 7m 27s	remaining: 9m 30s
4398:	learn: 0.0022929	total: 7m 27s	remaining: 9m 29s
4099:	learn: 0.0024123	total: 7m 27s	remaining: 10m 44s
4277:	learn: 0.0022902	total: 7m 27s	remaining: 9m 58s
4481:	learn: 0.0020745	total: 7m 27s	remaining: 9m 11s
4396:	learn: 0.0019166	total: 7m 27s	remaining: 9m 30s
4399:	learn: 0.0022923	total: 7m 27s	remaining: 9m 29s
4100:	learn: 0.0024117	total: 7m 27s	remaining: 10m 43s
4397:	learn: 0.0019166	total: 7m 27s	remaining: 9m 30s
4482:	learn: 0.0020739	total: 7m 27s	remaining: 9m 10s
4278:	learn: 0.0022895	total: 7m 27s	remaining: 9m 58s
4400:	learn: 0.0022915	total: 7m 27s	remaining: 9m 29s
4101:	learn: 0.0024114	total: 7m 27s	remaining: 10m 43s
4398:	learn: 0.0019166	total: 7m 27s	remaining: 9m 30s
4483:	learn: 0.0020734	total: 7m 27s	remaining: 9m 10s
4279:	learn: 0.0022885	total: 7m 27s	remaining: 9m 58s
4401:	learn: 0.0022908	total: 7m 27s	remaining: 9m 29s
4399:	learn: 0.0019157	total: 7m 27s	remaining: 9m 29s
4484:	learn: 0.0020727	total: 7m 27s	remaining: 9m 10s
4102:	learn: 0.0024102	total: 7m 27s	remaining: 10m 43s
4280:	learn: 0.0022878	total: 7m 27s	remaining: 9m 58s
4400:	learn: 0.0019150	total: 7m 27s	remaining: 9m 29s
4485:	learn: 0.0020722	total: 7m 27s	remaining: 9m 10s
4402:	learn: 0.0022899	total: 7m 27s	remaining: 9m 29s
4103:	learn: 0.0024093	total: 7m 28s	remaining: 10m 43s
4281:	learn: 0.0022871	total: 7m 27s	remaining: 9m 58s
4401:	learn: 0.0019142	total: 7m 27s	remaining: 9m 29s
4403:	learn: 0.0022892	total: 7m 27s	remaining: 9m 29s
4486:	learn: 0.0020715	total: 7m 28s	remaining: 9m 10s
4104:	learn: 0.0024084	total: 7m 28s	remaining: 10m 43s
4282:	learn: 0.0022863	total: 7m 28s	remaining: 9m 58s
4402:	learn: 0.0019135	total: 7m 28s	remaining: 9m 29s
4404:	learn: 0.0022886	total: 7m 27s	remaining: 9m 29s
4487:	learn: 0.0020708	total: 7m 28s	remaining: 9m 10s
4403:	learn: 0.0019135	total: 7m 28s	remaining: 9m 29s
4105:	learn: 0.0024077	total: 7m 28s	remaining: 10m 43s
4405:	learn: 0.0022882	total: 7m 28s	remaining: 9m 28s
4283:	learn: 0.0022862	total: 7m 28s	remaining: 9m 58s
4488:	learn: 0.0020702	total: 7m 28s	remaining: 9m 10s
4404:	learn: 0.0019128	total: 7m 28s	remaining: 9m 29s
4284:	learn: 0.0022850	total: 7m 28s	remaining: 9m 57s
4106:	learn: 0.0024070	total: 7m 28s	remaining: 10m 43s
4406:	learn: 0.0022876	total: 7m 28s	remaining: 9m 28s
4489:	learn: 0.0020695	total: 7m 28s	remaining: 9m 10s
4405:	learn: 0.0019122	total: 7m 28s	remaining: 9m 29s
4285:	learn: 0.0022839	total: 7m 28s	remaining: 9m 57s
4407:	learn: 0.0022871	total: 7m 28s	remaining: 9m 28s
4490:	learn: 0.0020688	total: 7m 28s	remaining: 9m 10s
4107:	learn: 0.0024066	total: 7m 28s	remaining: 10m 43s
4286:	learn: 0.0022832	total: 7m 28s	remaining: 9m 57s
4406:	learn: 0.0019122	total: 7m 28s	remaining: 9m 29s
4491:	learn: 0.0020688	total: 7m 28s	remaining: 9m 10s
4408:	learn: 0.0022867	total: 7m 28s	remaining: 9m 28s
4108:	learn: 0.0024066	total: 7m 28s	remaining: 10m 43s
4407:	learn: 0.0019116	total: 7m 28s	remaining: 9m 29s
4287:	learn: 0.0022832	total: 7m 28s	remaining: 9m 57s
4492:	learn: 0.0020683	total: 7m 28s	remaining: 9m 9s
4409:	learn: 0.0022860	total: 7m 28s	remaining: 9m 28s
4109:	learn: 0.0024057	total: 7m 28s	remaining: 10m 43s
4408:	learn: 0.0019108	total: 7m 28s	remaining: 9m 28s
4410:	learn: 0.0022850	total: 7m 28s	remaining: 9m 28s
4288:	learn: 0.0022832	total: 7m 28s	remaining: 9m 57s
4493:	learn: 0.0020677	total: 7m 28s	remaining: 9m 9s
4110:	learn: 0.0024046	total: 7m 28s	remaining: 10m 42s
4289:	learn: 0.0022832	total: 7m 28s	remaining: 9m 57s
4409:	learn: 0.0019108	total: 7m 28s	remaining: 9m 28s
4411:	learn: 0.0022845	total: 7m 28s	remaining: 9m 28s
4494:	learn: 0.0020673	total: 7m 28s	remaining: 9m 9s
4111:	learn: 0.0024035	total: 7m 28s	remaining: 10m 42s
4412:	learn: 0.0022840	total: 7m 28s	remaining: 9m 28s
4290:	learn: 0.0022825	total: 7m 28s	remaining: 9m 57s
4410:	learn: 0.0019108	total: 7m 28s	remaining: 9m 28s
4495:	learn: 0.0020673	total: 7m 28s	remaining: 9m 9s
4291:	learn: 0.0022811	total: 7m 28s	remaining: 9m 57s
4112:	learn: 0.0024025	total: 7m 29s	remaining: 10m 42s
4413:	learn: 0.0022833	total: 7m 28s	remaining: 9m 28s
4411:	learn: 0.0019108	total: 7m 29s	remaining: 9m 28s
4496:	learn: 0.0020666	total: 7m 29s	remaining: 9m 9s
4292:	learn: 0.0022804	total: 7m 29s	remaining: 9m 56s
4414:	learn: 0.0022827	total: 7m 28s	remaining: 9m 27s
4113:	learn: 0.0024016	total: 7m 29s	remaining: 10m 42s
4497:	learn: 0.0020661	total: 7m 29s	remaining: 9m 9s
4412:	learn: 0.0019108	total: 7m 29s	remaining: 9m 28s
4293:	learn: 0.0022797	total: 7m 29s	remaining: 9m 56s
4498:	learn: 0.0020657	total: 7m 29s	remaining: 9m 9s
4415:	learn: 0.0022818	total: 7m 29s	remaining: 9m 27s
4114:	learn: 0.0024007	total: 7m 29s	remaining: 10m 42s
4413:	learn: 0.0019101	total: 7m 29s	remaining: 9m 28s
4294:	learn: 0.0022790	total: 7m 29s	remaining: 9m 56s
4499:	learn: 0.0020649	total: 7m 29s	remaining: 9m 9s
4416:	learn: 0.0022813	total: 7m 29s	remaining: 9m 27s
4414:	learn: 0.0019100	total: 7m 29s	remaining: 9m 28s
4115:	learn: 0.0024002	total: 7m 29s	remaining: 10m 42s
4500:	learn: 0.0020649	total: 7m 29s	remaining: 9m 9s
4295:	learn: 0.0022788	total: 7m 29s	remaining: 9m 56s
4417:	learn: 0.0022808	total: 7m 29s	remaining: 9m 27s
4116:	learn: 0.0023993	total: 7m 29s	remaining: 10m 42s
4415:	learn: 0.0019100	total: 7m 29s	remaining: 9m 28s
4501:	learn: 0.0020643	total: 7m 29s	remaining: 9m 8s
4296:	learn: 0.0022774	total: 7m 29s	remaining: 9m 56s
4418:	learn: 0.0022801	total: 7m 29s	remaining: 9m 27s
4502:	learn: 0.0020638	total: 7m 29s	remaining: 9m 8s
4416:	learn: 0.0019100	total: 7m 29s	remaining: 9m 28s
4117:	learn: 0.0023983	total: 7m 29s	remaining: 10m 42s
4297:	learn: 0.0022761	total: 7m 29s	remaining: 9m 56s
4503:	learn: 0.0020632	total: 7m 29s	remaining: 9m 8s
4419:	learn: 0.0022794	total: 7m 29s	remaining: 9m 27s
4118:	learn: 0.0023970	total: 7m 29s	remaining: 10m 42s
4417:	learn: 0.0019094	total: 7m 29s	remaining: 9m 28s
4298:	learn: 0.0022751	total: 7m 29s	remaining: 9m 56s
4504:	learn: 0.0020625	total: 7m 29s	remaining: 9m 8s
4420:	learn: 0.0022793	total: 7m 29s	remaining: 9m 27s
4119:	learn: 0.0023962	total: 7m 29s	remaining: 10m 41s
4418:	learn: 0.0019094	total: 7m 29s	remaining: 9m 27s
4299:	learn: 0.0022742	total: 7m 29s	remaining: 9m 56s
4505:	learn: 0.0020615	total: 7m 29s	remaining: 9m 8s
4419:	learn: 0.0019093	total: 7m 29s	remaining: 9m 27s
4120:	learn: 0.0023952	total: 7m 29s	remaining: 10m 41s

4421:	learn: 0.0022787	total: 7m 29s	remaining: 9m 27s
4300:	learn: 0.0022731	total: 7m 29s	remaining: 9m 56s
4506:	learn: 0.0020610	total: 7m 29s	remaining: 9m 8s
4420:	learn: 0.0019087	total: 7m 29s	remaining: 9m 27s
4121:	learn: 0.0023940	total: 7m 30s	remaining: 10m 41s
4422:	learn: 0.0022781	total: 7m 29s	remaining: 9m 27s
4507:	learn: 0.0020605	total: 7m 30s	remaining: 9m 8s
4301:	learn: 0.0022726	total: 7m 29s	remaining: 9m 55s
4421:	learn: 0.0019087	total: 7m 30s	remaining: 9m 27s
4508:	learn: 0.0020598	total: 7m 30s	remaining: 9m 8s
4302:	learn: 0.0022716	total: 7m 30s	remaining: 9m 55s
4423:	learn: 0.0022774	total: 7m 29s	remaining: 9m 27s
4122:	learn: 0.0023931	total: 7m 30s	remaining: 10m 41s
4422:	learn: 0.0019087	total: 7m 30s	remaining: 9m 27s
4509:	learn: 0.0020590	total: 7m 30s	remaining: 9m 8s
4303:	learn: 0.0022716	total: 7m 30s	remaining: 9m 55s
4424:	learn: 0.0022769	total: 7m 30s	remaining: 9m 27s
4123:	learn: 0.0023921	total: 7m 30s	remaining: 10m 41s
4423:	learn: 0.0019087	total: 7m 30s	remaining: 9m 27s
4510:	learn: 0.0020585	total: 7m 30s	remaining: 9m 7s
4425:	learn: 0.0022762	total: 7m 30s	remaining: 9m 26s
4304:	learn: 0.0022711	total: 7m 30s	remaining: 9m 55s
4424:	learn: 0.0019087	total: 7m 30s	remaining: 9m 27s
4124:	learn: 0.0023911	total: 7m 30s	remaining: 10m 41s
4511:	learn: 0.0020580	total: 7m 30s	remaining: 9m 7s
4426:	learn: 0.0022756	total: 7m 30s	remaining: 9m 26s
4305:	learn: 0.0022706	total: 7m 30s	remaining: 9m 55s
4425:	learn: 0.0019087	total: 7m 30s	remaining: 9m 27s
4125:	learn: 0.0023901	total: 7m 30s	remaining: 10m 41s
4306:	learn: 0.0022692	total: 7m 30s	remaining: 9m 55s
4512:	learn: 0.0020578	total: 7m 30s	remaining: 9m 7s
4427:	learn: 0.0022750	total: 7m 30s	remaining: 9m 26s
4426:	learn: 0.0019087	total: 7m 30s	remaining: 9m 27s
4307:	learn: 0.0022683	total: 7m 30s	remaining: 9m 55s
4126:	learn: 0.0023892	total: 7m 30s	remaining: 10m 41s
4428:	learn: 0.0022744	total: 7m 30s	remaining: 9m 26s
4427:	learn: 0.0019080	total: 7m 30s	remaining: 9m 26s
4513:	learn: 0.0020571	total: 7m 30s	remaining: 9m 7s
4308:	learn: 0.0022683	total: 7m 30s	remaining: 9m 55s
4428:	learn: 0.0019080	total: 7m 30s	remaining: 9m 26s
4429:	learn: 0.0022736	total: 7m 30s	remaining: 9m 26s
4127:	learn: 0.0023882	total: 7m 30s	remaining: 10m 41s
4514:	learn: 0.0020563	total: 7m 30s	remaining: 9m 7s
4429:	learn: 0.0019080	total: 7m 30s	remaining: 9m 26s
4309:	learn: 0.0022676	total: 7m 30s	remaining: 9m 55s
4430:	learn: 0.0022729	total: 7m 30s	remaining: 9m 26s
4515:	learn: 0.0020556	total: 7m 30s	remaining: 9m 7s
4128:	learn: 0.0023870	total: 7m 30s	remaining: 10m 41s
4310:	learn: 0.0022667	total: 7m 30s	remaining: 9m 54s
4430:	learn: 0.0019080	total: 7m 30s	remaining: 9m 26s
4431:	learn: 0.0022723	total: 7m 30s	remaining: 9m 26s
4516:	learn: 0.0020549	total: 7m 30s	remaining: 9m 7s
4311:	learn: 0.0022667	total: 7m 30s	remaining: 9m 54s
4431:	learn: 0.0019080	total: 7m 30s	remaining: 9m 26s
4129:	learn: 0.0023860	total: 7m 31s	remaining: 10m 41s
4517:	learn: 0.0020541	total: 7m 31s	remaining: 9m 7s
4432:	learn: 0.0022718	total: 7m 30s	remaining: 9m 26s
4312:	learn: 0.0022667	total: 7m 31s	remaining: 9m 54s
4432:	learn: 0.0019080	total: 7m 31s	remaining: 9m 26s
4130:	learn: 0.0023851	total: 7m 31s	remaining: 10m 40s
4518:	learn: 0.0020535	total: 7m 31s	remaining: 9m 7s
4313:	learn: 0.0022660	total: 7m 31s	remaining: 9m 54s
4433:	learn: 0.0022713	total: 7m 30s	remaining: 9m 26s
4433:	learn: 0.0019073	total: 7m 31s	remaining: 9m 26s
4519:	learn: 0.0020534	total: 7m 31s	remaining: 9m 7s
4131:	learn: 0.0023846	total: 7m 31s	remaining: 10m 40s
4434:	learn: 0.0019065	total: 7m 31s	remaining: 9m 26s
4314:	learn: 0.0022654	total: 7m 31s	remaining: 9m 54s
4434:	learn: 0.0022712	total: 7m 31s	remaining: 9m 25s
4132:	learn: 0.0023835	total: 7m 31s	remaining: 10m 40s
4435:	learn: 0.0022708	total: 7m 31s	remaining: 9m 25s
4520:	learn: 0.0020524	total: 7m 31s	remaining: 9m 6s
4435:	learn: 0.0019065	total: 7m 31s	remaining: 9m 26s
4315:	learn: 0.0022646	total: 7m 31s	remaining: 9m 54s
4133:	learn: 0.0023825	total: 7m 31s	remaining: 10m 40s
4521:	learn: 0.0020516	total: 7m 31s	remaining: 9m 6s
4436:	learn: 0.0022702	total: 7m 31s	remaining: 9m 25s
4436:	learn: 0.0019065	total: 7m 31s	remaining: 9m 25s
4316:	learn: 0.0022646	total: 7m 31s	remaining: 9m 54s
4134:	learn: 0.0023821	total: 7m 31s	remaining: 10m 40s
4522:	learn: 0.0020513	total: 7m 31s	remaining: 9m 6s
4437:	learn: 0.0019059	total: 7m 31s	remaining: 9m 25s
4437:	learn: 0.0022693	total: 7m 31s	remaining: 9m 25s
4317:	learn: 0.0022641	total: 7m 31s	remaining: 9m 54s
4523:	learn: 0.0020507	total: 7m 31s	remaining: 9m 6s
4438:	learn: 0.0019059	total: 7m 31s	remaining: 9m 25s
4438:	learn: 0.0022684	total: 7m 31s	remaining: 9m 25s
4135:	learn: 0.0023812	total: 7m 31s	remaining: 10m 40s
4318:	learn: 0.0022631	total: 7m 31s	remaining: 9m 54s
4524:	learn: 0.0020501	total: 7m 31s	remaining: 9m 6s
4439:	learn: 0.0019052	total: 7m 31s	remaining: 9m 25s
4439:	learn: 0.0022679	total: 7m 31s	remaining: 9m 25s
4136:	learn: 0.0023805	total: 7m 31s	remaining: 10m 40s
4525:	learn: 0.0020496	total: 7m 31s	remaining: 9m 6s
4319:	learn: 0.0022622	total: 7m 31s	remaining: 9m 53s
4440:	learn: 0.0019052	total: 7m 31s	remaining: 9m 25s
4440:	learn: 0.0022672	total: 7m 31s	remaining: 9m 25s
4137:	learn: 0.0023796	total: 7m 31s	remaining: 10m 40s
4320:	learn: 0.0022622	total: 7m 31s	remaining: 9m 53s
4526:	learn: 0.0020489	total: 7m 31s	remaining: 9m 6s
4441:	learn: 0.0022663	total: 7m 31s	remaining: 9m 25s
4441:	learn: 0.0019046	total: 7m 31s	remaining: 9m 25s
4138:	learn: 0.0023784	total: 7m 32s	remaining: 10m 40s
4321:	learn: 0.0022612	total: 7m 31s	remaining: 9m 53s
4442:	learn: 0.0022657	total: 7m 31s	remaining: 9m 25s
4527:	learn: 0.0020482	total: 7m 32s	remaining: 9m 6s
4442:	learn: 0.0019046	total: 7m 31s	remaining: 9m 25s
4139:	learn: 0.0023773	total: 7m 32s	remaining: 10m 39s
4443:	learn: 0.0022650	total: 7m 31s	remaining: 9m 24s
4322:	learn: 0.0022606	total: 7m 32s	remaining: 9m 53s
4528:	learn: 0.0020476	total: 7m 32s	remaining: 9m 6s
4443:	learn: 0.0019046	total: 7m 32s	remaining: 9m 25s
4140:	learn: 0.0023767	total: 7m 32s	remaining: 10m 39s
4444:	learn: 0.0022642	total: 7m 31s	remaining: 9m 24s
4529:	learn: 0.0020469	total: 7m 32s	remaining: 9m 6s
4323:	learn: 0.0022595	total: 7m 32s	remaining: 9m 53s
4444:	learn: 0.0019046	total: 7m 32s	remaining: 9m 25s
4141:	learn: 0.0023762	total: 7m 32s	remaining: 10m 39s
4445:	learn: 0.0022632	total: 7m 32s	remaining: 9m 24s
4530:	learn: 0.0020462	total: 7m 32s	remaining: 9m 5s
4324:	learn: 0.0022585	total: 7m 32s	remaining: 9m 53s
4445:	learn: 0.0019046	total: 7m 32s	remaining: 9m 24s
4142:	learn: 0.0023751	total: 7m 32s	remaining: 10m 39s
4446:	learn: 0.0022626	total: 7m 32s	remaining: 9m 24s
4325:	learn: 0.0022585	total: 7m 32s	remaining: 9m 53s
4531:	learn: 0.0020452	total: 7m 32s	remaining: 9m 5s
4446:	learn: 0.0019046	total: 7m 32s	remaining: 9m 24s
4143:	learn: 0.0023746	total: 7m 32s	remaining: 10m 39s
4447:	learn: 0.0022619	total: 7m 32s	remaining: 9m 24s
4326:	learn: 0.0022575	total: 7m 32s	remaining: 9m 53s
4447:	learn: 0.0019045	total: 7m 32s	remaining: 9m 24s
4532:	learn: 0.0020452	total: 7m 32s	remaining: 9m 5s
4448:	learn: 0.0022610	total: 7m 32s	remaining: 9m 24s
4144:	learn: 0.0023737	total: 7m 32s	remaining: 10m 39s
4448:	learn: 0.0019045	total: 7m 32s	remaining: 9m 24s
4327:	learn: 0.0022575	total: 7m 32s	remaining: 9m 53s
4533:	learn: 0.0020443	total: 7m 32s	remaining: 9m 5s
4449:	learn: 0.0022604	total: 7m 32s	remaining: 9m 24s
4145:	learn: 0.0023726	total: 7m 32s	remaining: 10m 39s
4449:	learn: 0.0019038	total: 7m 32s	remaining: 9m 24s
4450:	learn: 0.0022597	total: 7m 32s	remaining: 9m 24s
4534:	learn: 0.0020438	total: 7m 32s	remaining: 9m 5s
4328:	learn: 0.0022575	total: 7m 32s	remaining: 9m 53s
4451:	learn: 0.0022591	total: 7m 32s	remaining: 9m 24s
4450:	learn: 0.0019038	total: 7m 32s	remaining: 9m 24s
4146:	learn: 0.0023719	total: 7m 32s	remaining: 10m 39s
4535:	learn: 0.0020435	total: 7m 32s	remaining: 9m 5s
4329:	learn: 0.0022572	total: 7m 32s	remaining: 9m 52s
4452:	learn: 0.0022584	total: 7m 32s	remaining: 9m 23s
4147:	learn: 0.0023715	total: 7m 32s	remaining: 10m 39s
4451:	learn: 0.0019030	total: 7m 32s	remaining: 9m 24s
4536:	learn: 0.0020426	total: 7m 32s	remaining: 9m 5s
4330:	learn: 0.0022566	total: 7m 32s	remaining: 9m 52s
4453:	learn: 0.0022574	total: 7m 32s	remaining: 9m 23s
4452:	learn: 0.0019030	total: 7m 32s	remaining: 9m 24s
4148:	learn: 0.0023708	total: 7m 33s	remaining: 10m 38s
4537:	learn: 0.0020419	total: 7m 33s	remaining: 9m 5s
4331:	learn: 0.0022559	total: 7m 33s	remaining: 9m 52s
4453:	learn: 0.0019024	total: 7m 33s	remaining: 9m 24s
4454:	learn: 0.0022569	total: 7m 32s	remaining: 9m 23s
4149:	learn: 0.0023698	total: 7m 33s	remaining: 10m 38s
4538:	learn: 0.0020413	total: 7m 33s	remaining: 9m 5s
4454:	learn: 0.0019017	total: 7m 33s	remaining: 9m 23s
4455:	learn: 0.0022562	total: 7m 32s	remaining: 9m 23s
4150:	learn: 0.0023688	total: 7m 33s	remaining: 10m 38s
4332:	learn: 0.0022552	total: 7m 33s	remaining: 9m 52s
4455:	learn: 0.0019017	total: 7m 33s	remaining: 9m 23s
4539:	learn: 0.0020407	total: 7m 33s	remaining: 9m 5s
4151:	learn: 0.0023684	total: 7m 33s	remaining: 10m 38s
4456:	learn: 0.0022553	total: 7m 33s	remaining: 9m 23s
4333:	learn: 0.0022544	total: 7m 33s	remaining: 9m 52s
4456:	learn: 0.0019013	total: 7m 33s	remaining: 9m 23s
4540:	learn: 0.0020400	total: 7m 33s	remaining: 9m 4s
4457:	learn: 0.0022547	total: 7m 33s	remaining: 9m 23s
4152:	learn: 0.0023676	total: 7m 33s	remaining: 10m 38s
4457:	learn: 0.0019013	total: 7m 33s	remaining: 9m 23s
4541:	learn: 0.0020392	total: 7m 33s	remaining: 9m 4s
4334:	learn: 0.0022531	total: 7m 33s	remaining: 9m 52s
4458:	learn: 0.0022542	total: 7m 33s	remaining: 9m 23s
4542:	learn: 0.0020385	total: 7m 33s	remaining: 9m 4s
4458:	learn: 0.0019006	total: 7m 33s	remaining: 9m 23s
4153:	learn: 0.0023669	total: 7m 33s	remaining: 10m 38s
4459:	learn: 0.0022536	total: 7m 33s	remaining: 9m 23s
4335:	learn: 0.0022523	total: 7m 33s	remaining: 9m 52s
4543:	learn: 0.0020378	total: 7m 33s	remaining: 9m 4s
4459:	learn: 0.0019006	total: 7m 33s	remaining: 9m 23s
4154:	learn: 0.0023662	total: 7m 33s	remaining: 10m 38s
4544:	learn: 0.0020374	total: 7m 33s	remaining: 9m 4s
4336:	learn: 0.0022518	total: 7m 33s	remaining: 9m 52s
4460:	learn: 0.0022523	total: 7m 33s	remaining: 9m 23s
4460:	learn: 0.0019006	total: 7m 33s	remaining: 9m 23s
4545:	learn: 0.0020369	total: 7m 33s	remaining: 9m 4s
4337:	learn: 0.0022509	total: 7m 33s	remaining: 9m 52s
4155:	learn: 0.0023656	total: 7m 33s	remaining: 10m 38s
4461:	learn: 0.0022518	total: 7m 33s	remaining: 9m 22s
4461:	learn: 0.0018998	total: 7m 33s	remaining: 9m 23s
4546:	learn: 0.0020363	total: 7m 33s	remaining: 9m 4s
4338:	learn: 0.0022503	total: 7m 33s	remaining: 9m 52s
4156:	learn: 0.0023646	total: 7m 33s	remaining: 10m 38s
4462:	learn: 0.0022508	total: 7m 33s	remaining: 9m 22s
4462:	learn: 0.0018990	total: 7m 33s	remaining: 9m 23s
4339:	learn: 0.0022498	total: 7m 33s	remaining: 9m 51s
4547:	learn: 0.0020356	total: 7m 33s	remaining: 9m 4s
4463:	learn: 0.0022501	total: 7m 33s	remaining: 9m 22s
4157:	learn: 0.0023641	total: 7m 34s	remaining: 10m 37s
4463:	learn: 0.0018990	total: 7m 33s	remaining: 9m 23s
4340:	learn: 0.0022498	total: 7m 34s	remaining: 9m 51s
4464:	learn: 0.0022490	total: 7m 33s	remaining: 9m 22s
4548:	learn: 0.0020349	total: 7m 34s	remaining: 9m 4s
4158:	learn: 0.0023637	total: 7m 34s	remaining: 10m 37s
4464:	learn: 0.0018988	total: 7m 34s	remaining: 9m 22s
4341:	learn: 0.0022491	total: 7m 34s	remaining: 9m 51s
4549:	learn: 0.0020340	total: 7m 34s	remaining: 9m 4s
4465:	learn: 0.0022482	total: 7m 33s	remaining: 9m 22s
4159:	learn: 0.0023625	total: 7m 34s	remaining: 10m 37s
4465:	learn: 0.0018985	total: 7m 34s	remaining: 9m 22s
4550:	learn: 0.0020335	total: 7m 34s	remaining: 9m 3s
4342:	learn: 0.0022485	total: 7m 34s	remaining: 9m 51s
4466:	learn: 0.0022473	total: 7m 34s	remaining: 9m 22s
4160:	learn: 0.0023615	total: 7m 34s	remaining: 10m 37s
4467:	learn: 0.0022467	total: 7m 34s	remaining: 9m 22s
4551:	learn: 0.0020327	total: 7m 34s	remaining: 9m 3s
4466:	learn: 0.0018983	total: 7m 34s	remaining: 9m 22s
4343:	learn: 0.0022475	total: 7m 34s	remaining: 9m 51s
4161:	learn: 0.0023606	total: 7m 34s	remaining: 10m 37s
4468:	learn: 0.0022456	total: 7m 34s	remaining: 9m 22s
4552:	learn: 0.0020320	total: 7m 34s	remaining: 9m 3s
4467:	learn: 0.0018980	total: 7m 34s	remaining: 9m 22s
4553:	learn: 0.0020320	total: 7m 34s	remaining: 9m 3s
4162:	learn: 0.0023595	total: 7m 34s	remaining: 10m 37s
4344:	learn: 0.0022469	total: 7m 34s	remaining: 9m 51s
4469:	learn: 0.0022446	total: 7m 34s	remaining: 9m 22s
4468:	learn: 0.0018971	total: 7m 34s	remaining: 9m 22s
4554:	learn: 0.0020313	total: 7m 34s	remaining: 9m 3s
4470:	learn: 0.0022446	total: 7m 34s	remaining: 9m 21s
4163:	learn: 0.0023586	total: 7m 34s	remaining: 10m 37s
4345:	learn: 0.0022463	total: 7m 34s	remaining: 9m 51s
4469:	learn: 0.0018971	total: 7m 34s	remaining: 9m 22s
4555:	learn: 0.0020310	total: 7m 34s	remaining: 9m 3s
4471:	learn: 0.0022440	total: 7m 34s	remaining: 9m 21s
4346:	learn: 0.0022456	total: 7m 34s	remaining: 9m 51s
4164:	learn: 0.0023578	total: 7m 34s	remaining: 10m 37s
4470:	learn: 0.0018971	total: 7m 34s	remaining: 9m 22s
4472:	learn: 0.0022431	total: 7m 34s	remaining: 9m 21s
4556:	learn: 0.0020303	total: 7m 34s	remaining: 9m 3s
4471:	learn: 0.0018971	total: 7m 34s	remaining: 9m 22s
4347:	learn: 0.0022445	total: 7m 34s	remaining: 9m 51s
4165:	learn: 0.0023567	total: 7m 34s	remaining: 10m 37s
4473:	learn: 0.0022425	total: 7m 34s	remaining: 9m 21s
4557:	learn: 0.0020299	total: 7m 34s	remaining: 9m 3s
4472:	learn: 0.0018968	total: 7m 34s	remaining: 9m 22s
4166:	learn: 0.0023555	total: 7m 34s	remaining: 10m 36s
4348:	learn: 0.0022437	total: 7m 34s	remaining: 9m 51s
4474:	learn: 0.0022418	total: 7m 34s	remaining: 9m 21s
4558:	learn: 0.0020299	total: 7m 34s	remaining: 9m 3s
4473:	learn: 0.0018968	total: 7m 34s	remaining: 9m 21s
4167:	learn: 0.0023546	total: 7m 35s	remaining: 10m 36s
4475:	learn: 0.0022407	total: 7m 34s	remaining: 9m 21s
4559:	learn: 0.0020299	total: 7m 35s	remaining: 9m 2s
4349:	learn: 0.0022430	total: 7m 35s	remaining: 9m 51s
4168:	learn: 0.0023539	total: 7m 35s	remaining: 10m 36s
4476:	learn: 0.0022399	total: 7m 34s	remaining: 9m 21s
4474:	learn: 0.0018968	total: 7m 35s	remaining: 9m 21s
4350:	learn: 0.0022419	total: 7m 35s	remaining: 9m 50s
4560:	learn: 0.0020298	total: 7m 35s	remaining: 9m 2s
4169:	learn: 0.0023531	total: 7m 35s	remaining: 10m 36s
4475:	learn: 0.0018968	total: 7m 35s	remaining: 9m 21s
4477:	learn: 0.0022389	total: 7m 35s	remaining: 9m 21s
4351:	learn: 0.0022407	total: 7m 35s	remaining: 9m 50s
4561:	learn: 0.0020291	total: 7m 35s	remaining: 9m 2s
4476:	learn: 0.0018965	total: 7m 35s	remaining: 9m 21s
4170:	learn: 0.0023520	total: 7m 35s	remaining: 10m 36s
4478:	learn: 0.0022378	total: 7m 35s	remaining: 9m 21s
4562:	learn: 0.0020283	total: 7m 35s	remaining: 9m 2s
4352:	learn: 0.0022398	total: 7m 35s	remaining: 9m 50s
4477:	learn: 0.0018964	total: 7m 35s	remaining: 9m 21s
4171:	learn: 0.0023509	total: 7m 35s	remaining: 10m 36s
4563:	learn: 0.0020278	total: 7m 35s	remaining: 9m 2s
4479:	learn: 0.0022369	total: 7m 35s	remaining: 9m 21s
4353:	learn: 0.0022398	total: 7m 35s	remaining: 9m 50s
4478:	learn: 0.0018958	total: 7m 35s	remaining: 9m 21s
4564:	learn: 0.0020271	total: 7m 35s	remaining: 9m 2s
4172:	learn: 0.0023500	total: 7m 35s	remaining: 10m 36s
4480:	learn: 0.0022363	total: 7m 35s	remaining: 9m 20s
4354:	learn: 0.0022386	total: 7m 35s	remaining: 9m 50s
4479:	learn: 0.0018958	total: 7m 35s	remaining: 9m 21s
4565:	learn: 0.0020265	total: 7m 35s	remaining: 9m 2s
4173:	learn: 0.0023490	total: 7m 35s	remaining: 10m 36s
4481:	learn: 0.0022353	total: 7m 35s	remaining: 9m 20s
4355:	learn: 0.0022374	total: 7m 35s	remaining: 9m 50s
4480:	learn: 0.0018958	total: 7m 35s	remaining: 9m 21s
4566:	learn: 0.0020257	total: 7m 35s	remaining: 9m 2s
4482:	learn: 0.0022345	total: 7m 35s	remaining: 9m 20s
4174:	learn: 0.0023481	total: 7m 35s	remaining: 10m 35s
4356:	learn: 0.0022373	total: 7m 35s	remaining: 9m 50s
4481:	learn: 0.0018954	total: 7m 35s	remaining: 9m 21s
4483:	learn: 0.0022334	total: 7m 35s	remaining: 9m 20s
4567:	learn: 0.0020257	total: 7m 35s	remaining: 9m 2s

4482:	learn: 0.0018950	total: 7m 35s	remaining: 9m 20s
4357:	learn: 0.0022373	total: 7m 35s	remaining: 9m 50s
4484:	learn: 0.0022324	total: 7m 35s	remaining: 9m 20s
4483:	learn: 0.0018947	total: 7m 35s	remaining: 9m 20s
4175:	learn: 0.0023475	total: 7m 36s	remaining: 10m 35s
4568:	learn: 0.0020250	total: 7m 35s	remaining: 9m 2s
4358:	learn: 0.0022362	total: 7m 35s	remaining: 9m 50s
4484:	learn: 0.0018947	total: 7m 35s	remaining: 9m 20s
4569:	learn: 0.0020248	total: 7m 36s	remaining: 9m 1s
4485:	learn: 0.0022313	total: 7m 35s	remaining: 9m 20s
4176:	learn: 0.0023463	total: 7m 36s	remaining: 10m 35s
4359:	learn: 0.0022362	total: 7m 36s	remaining: 9m 49s
4485:	learn: 0.0018947	total: 7m 36s	remaining: 9m 20s
4570:	learn: 0.0020248	total: 7m 36s	remaining: 9m 1s
4177:	learn: 0.0023455	total: 7m 36s	remaining: 10m 35s
4486:	learn: 0.0022305	total: 7m 36s	remaining: 9m 20s
4486:	learn: 0.0018947	total: 7m 36s	remaining: 9m 20s
4360:	learn: 0.0022350	total: 7m 36s	remaining: 9m 49s
4571:	learn: 0.0020243	total: 7m 36s	remaining: 9m 1s
4178:	learn: 0.0023445	total: 7m 36s	remaining: 10m 35s
4487:	learn: 0.0022296	total: 7m 36s	remaining: 9m 20s
4361:	learn: 0.0022347	total: 7m 36s	remaining: 9m 49s
4487:	learn: 0.0018947	total: 7m 36s	remaining: 9m 20s
4572:	learn: 0.0020236	total: 7m 36s	remaining: 9m 1s
4179:	learn: 0.0023440	total: 7m 36s	remaining: 10m 35s
4488:	learn: 0.0022285	total: 7m 36s	remaining: 9m 20s
4488:	learn: 0.0018947	total: 7m 36s	remaining: 9m 20s
4362:	learn: 0.0022337	total: 7m 36s	remaining: 9m 49s
4573:	learn: 0.0020234	total: 7m 36s	remaining: 9m 1s
4489:	learn: 0.0018947	total: 7m 36s	remaining: 9m 20s
4180:	learn: 0.0023430	total: 7m 36s	remaining: 10m 35s
4489:	learn: 0.0022278	total: 7m 36s	remaining: 9m 19s
4574:	learn: 0.0020227	total: 7m 36s	remaining: 9m 1s
4363:	learn: 0.0022331	total: 7m 36s	remaining: 9m 49s
4181:	learn: 0.0023419	total: 7m 36s	remaining: 10m 35s
4490:	learn: 0.0018939	total: 7m 36s	remaining: 9m 20s
4490:	learn: 0.0022272	total: 7m 36s	remaining: 9m 19s
4575:	learn: 0.0020224	total: 7m 36s	remaining: 9m 1s
4364:	learn: 0.0022325	total: 7m 36s	remaining: 9m 49s
4491:	learn: 0.0018932	total: 7m 36s	remaining: 9m 19s
4182:	learn: 0.0023410	total: 7m 36s	remaining: 10m 35s
4491:	learn: 0.0022261	total: 7m 36s	remaining: 9m 19s
4576:	learn: 0.0020224	total: 7m 36s	remaining: 9m 1s
4183:	learn: 0.0023399	total: 7m 36s	remaining: 10m 34s
4492:	learn: 0.0022255	total: 7m 36s	remaining: 9m 19s
4365:	learn: 0.0022325	total: 7m 36s	remaining: 9m 49s
4492:	learn: 0.0018932	total: 7m 36s	remaining: 9m 19s
4577:	learn: 0.0020219	total: 7m 36s	remaining: 9m 1s
4493:	learn: 0.0022245	total: 7m 36s	remaining: 9m 19s
4493:	learn: 0.0018932	total: 7m 36s	remaining: 9m 19s
4366:	learn: 0.0022315	total: 7m 36s	remaining: 9m 49s
4184:	learn: 0.0023392	total: 7m 36s	remaining: 10m 34s
4578:	learn: 0.0020214	total: 7m 36s	remaining: 9m
4494:	learn: 0.0022245	total: 7m 36s	remaining: 9m 19s
4494:	learn: 0.0018932	total: 7m 36s	remaining: 9m 19s
4495:	learn: 0.0022238	total: 7m 36s	remaining: 9m 19s
4367:	learn: 0.0022308	total: 7m 36s	remaining: 9m 49s
4185:	learn: 0.0023383	total: 7m 37s	remaining: 10m 34s
4579:	learn: 0.0020208	total: 7m 37s	remaining: 9m
4580:	learn: 0.0020206	total: 7m 37s	remaining: 9m
4495:	learn: 0.0018932	total: 7m 37s	remaining: 9m 19s
4368:	learn: 0.0022298	total: 7m 37s	remaining: 9m 49s
4496:	learn: 0.0022229	total: 7m 36s	remaining: 9m 19s
4186:	learn: 0.0023373	total: 7m 37s	remaining: 10m 34s
4581:	learn: 0.0020206	total: 7m 37s	remaining: 9m
4369:	learn: 0.0022288	total: 7m 37s	remaining: 9m 48s
4496:	learn: 0.0018932	total: 7m 37s	remaining: 9m 19s
4497:	learn: 0.0022218	total: 7m 37s	remaining: 9m 19s
4187:	learn: 0.0023366	total: 7m 37s	remaining: 10m 34s
4582:	learn: 0.0020200	total: 7m 37s	remaining: 9m
4370:	learn: 0.0022275	total: 7m 37s	remaining: 9m 48s
4497:	learn: 0.0018932	total: 7m 37s	remaining: 9m 19s
4583:	learn: 0.0020200	total: 7m 37s	remaining: 9m
4498:	learn: 0.0022209	total: 7m 37s	remaining: 9m 19s
4188:	learn: 0.0023357	total: 7m 37s	remaining: 10m 34s
4371:	learn: 0.0022267	total: 7m 37s	remaining: 9m 48s
4498:	learn: 0.0018932	total: 7m 37s	remaining: 9m 19s
4584:	learn: 0.0020192	total: 7m 37s	remaining: 9m
4499:	learn: 0.0022204	total: 7m 37s	remaining: 9m 18s
4189:	learn: 0.0023352	total: 7m 37s	remaining: 10m 34s
4499:	learn: 0.0018932	total: 7m 37s	remaining: 9m 19s
4372:	learn: 0.0022260	total: 7m 37s	remaining: 9m 48s
4585:	learn: 0.0020192	total: 7m 37s	remaining: 9m
4190:	learn: 0.0023346	total: 7m 37s	remaining: 10m 34s
4500:	learn: 0.0018925	total: 7m 37s	remaining: 9m 18s
4500:	learn: 0.0022199	total: 7m 37s	remaining: 9m 18s
4373:	learn: 0.0022249	total: 7m 37s	remaining: 9m 48s
4586:	learn: 0.0020184	total: 7m 37s	remaining: 9m
4191:	learn: 0.0023340	total: 7m 37s	remaining: 10m 34s
4501:	learn: 0.0018924	total: 7m 37s	remaining: 9m 18s
4501:	learn: 0.0022187	total: 7m 37s	remaining: 9m 18s
4587:	learn: 0.0020177	total: 7m 37s	remaining: 8m 59s
4374:	learn: 0.0022242	total: 7m 37s	remaining: 9m 48s
4192:	learn: 0.0023332	total: 7m 37s	remaining: 10m 34s
4502:	learn: 0.0018915	total: 7m 37s	remaining: 9m 18s
4502:	learn: 0.0022178	total: 7m 37s	remaining: 9m 18s
4588:	learn: 0.0020177	total: 7m 37s	remaining: 8m 59s
4375:	learn: 0.0022242	total: 7m 37s	remaining: 9m 48s
4503:	learn: 0.0022169	total: 7m 37s	remaining: 9m 18s
4503:	learn: 0.0018915	total: 7m 37s	remaining: 9m 18s
4589:	learn: 0.0020173	total: 7m 37s	remaining: 8m 59s
4193:	learn: 0.0023322	total: 7m 37s	remaining: 10m 33s
4504:	learn: 0.0022159	total: 7m 37s	remaining: 9m 18s
4590:	learn: 0.0020171	total: 7m 37s	remaining: 8m 59s
4504:	learn: 0.0018915	total: 7m 37s	remaining: 9m 18s
4376:	learn: 0.0022235	total: 7m 37s	remaining: 9m 48s
4194:	learn: 0.0023316	total: 7m 38s	remaining: 10m 33s
4505:	learn: 0.0022150	total: 7m 37s	remaining: 9m 18s
4505:	learn: 0.0018915	total: 7m 38s	remaining: 9m 18s
4591:	learn: 0.0020164	total: 7m 38s	remaining: 8m 59s
4377:	learn: 0.0022235	total: 7m 38s	remaining: 9m 48s
4506:	learn: 0.0022140	total: 7m 37s	remaining: 9m 18s
4195:	learn: 0.0023309	total: 7m 38s	remaining: 10m 33s
4592:	learn: 0.0020156	total: 7m 38s	remaining: 8m 59s
4378:	learn: 0.0022227	total: 7m 38s	remaining: 9m 48s
4506:	learn: 0.0018915	total: 7m 38s	remaining: 9m 18s
4507:	learn: 0.0022130	total: 7m 38s	remaining: 9m 18s
4196:	learn: 0.0023298	total: 7m 38s	remaining: 10m 33s
4593:	learn: 0.0020156	total: 7m 38s	remaining: 8m 59s
4379:	learn: 0.0022214	total: 7m 38s	remaining: 9m 47s
4507:	learn: 0.0018915	total: 7m 38s	remaining: 9m 18s
4197:	learn: 0.0023287	total: 7m 38s	remaining: 10m 33s
4594:	learn: 0.0020154	total: 7m 38s	remaining: 8m 59s
4508:	learn: 0.0022119	total: 7m 38s	remaining: 9m 17s
4380:	learn: 0.0022212	total: 7m 38s	remaining: 9m 47s
4508:	learn: 0.0018915	total: 7m 38s	remaining: 9m 18s
4198:	learn: 0.0023280	total: 7m 38s	remaining: 10m 33s
4595:	learn: 0.0020154	total: 7m 38s	remaining: 8m 59s
4509:	learn: 0.0022109	total: 7m 38s	remaining: 9m 17s
4381:	learn: 0.0022212	total: 7m 38s	remaining: 9m 47s
4509:	learn: 0.0018915	total: 7m 38s	remaining: 9m 18s
4199:	learn: 0.0023268	total: 7m 38s	remaining: 10m 33s
4510:	learn: 0.0022099	total: 7m 38s	remaining: 9m 17s
4596:	learn: 0.0020147	total: 7m 38s	remaining: 8m 58s
4382:	learn: 0.0022202	total: 7m 38s	remaining: 9m 47s
4200:	learn: 0.0023258	total: 7m 38s	remaining: 10m 33s
4510:	learn: 0.0018915	total: 7m 38s	remaining: 9m 17s
4511:	learn: 0.0022091	total: 7m 38s	remaining: 9m 17s
4383:	learn: 0.0022191	total: 7m 38s	remaining: 9m 47s
4511:	learn: 0.0018915	total: 7m 38s	remaining: 9m 17s
4597:	learn: 0.0020139	total: 7m 38s	remaining: 8m 58s
4201:	learn: 0.0023249	total: 7m 38s	remaining: 10m 32s
4512:	learn: 0.0022084	total: 7m 38s	remaining: 9m 17s
4384:	learn: 0.0022185	total: 7m 38s	remaining: 9m 47s
4598:	learn: 0.0020133	total: 7m 38s	remaining: 8m 58s
4512:	learn: 0.0018915	total: 7m 38s	remaining: 9m 17s
4202:	learn: 0.0023241	total: 7m 38s	remaining: 10m 32s
4513:	learn: 0.0022077	total: 7m 38s	remaining: 9m 17s
4385:	learn: 0.0022180	total: 7m 38s	remaining: 9m 47s
4599:	learn: 0.0020133	total: 7m 38s	remaining: 8m 58s
4203:	learn: 0.0023230	total: 7m 38s	remaining: 10m 32s
4513:	learn: 0.0018916	total: 7m 38s	remaining: 9m 17s
4386:	learn: 0.0022178	total: 7m 38s	remaining: 9m 47s
4514:	learn: 0.0022068	total: 7m 38s	remaining: 9m 17s
4600:	learn: 0.0020133	total: 7m 38s	remaining: 8m 58s
4204:	learn: 0.0023221	total: 7m 39s	remaining: 10m 32s
4387:	learn: 0.0022178	total: 7m 39s	remaining: 9m 47s
4515:	learn: 0.0022060	total: 7m 38s	remaining: 9m 17s
4514:	learn: 0.0018915	total: 7m 39s	remaining: 9m 17s
4601:	learn: 0.0020125	total: 7m 39s	remaining: 8m 58s
4516:	learn: 0.0022056	total: 7m 38s	remaining: 9m 17s
4388:	learn: 0.0022171	total: 7m 39s	remaining: 9m 46s
4205:	learn: 0.0023213	total: 7m 39s	remaining: 10m 32s
4515:	learn: 0.0018915	total: 7m 39s	remaining: 9m 17s
4602:	learn: 0.0020126	total: 7m 39s	remaining: 8m 58s
4206:	learn: 0.0023204	total: 7m 39s	remaining: 10m 32s
4516:	learn: 0.0018915	total: 7m 39s	remaining: 9m 17s
4517:	learn: 0.0022048	total: 7m 39s	remaining: 9m 17s
4603:	learn: 0.0020119	total: 7m 39s	remaining: 8m 58s
4389:	learn: 0.0022164	total: 7m 39s	remaining: 9m 46s
4207:	learn: 0.0023198	total: 7m 39s	remaining: 10m 32s
4517:	learn: 0.0018909	total: 7m 39s	remaining: 9m 17s
4604:	learn: 0.0020119	total: 7m 39s	remaining: 8m 58s
4518:	learn: 0.0022038	total: 7m 39s	remaining: 9m 16s
4390:	learn: 0.0022157	total: 7m 39s	remaining: 9m 46s
4208:	learn: 0.0023198	total: 7m 39s	remaining: 10m 32s
4605:	learn: 0.0020112	total: 7m 39s	remaining: 8m 58s
4519:	learn: 0.0022033	total: 7m 39s	remaining: 9m 16s
4391:	learn: 0.0022151	total: 7m 39s	remaining: 9m 46s
4518:	learn: 0.0018909	total: 7m 39s	remaining: 9m 17s
4209:	learn: 0.0023191	total: 7m 39s	remaining: 10m 31s
4520:	learn: 0.0022025	total: 7m 39s	remaining: 9m 16s
4606:	learn: 0.0020102	total: 7m 39s	remaining: 8m 57s
4392:	learn: 0.0022143	total: 7m 39s	remaining: 9m 46s
4519:	learn: 0.0018909	total: 7m 39s	remaining: 9m 17s
4210:	learn: 0.0023180	total: 7m 39s	remaining: 10m 31s
4607:	learn: 0.0020095	total: 7m 39s	remaining: 8m 57s
4521:	learn: 0.0022019	total: 7m 39s	remaining: 9m 16s
4393:	learn: 0.0022130	total: 7m 39s	remaining: 9m 46s
4520:	learn: 0.0018909	total: 7m 39s	remaining: 9m 17s
4211:	learn: 0.0023170	total: 7m 39s	remaining: 10m 31s
4522:	learn: 0.0022009	total: 7m 39s	remaining: 9m 16s
4608:	learn: 0.0020095	total: 7m 39s	remaining: 8m 57s
4394:	learn: 0.0022122	total: 7m 39s	remaining: 9m 46s
4521:	learn: 0.0018909	total: 7m 39s	remaining: 9m 16s
4212:	learn: 0.0023159	total: 7m 39s	remaining: 10m 31s
4523:	learn: 0.0022002	total: 7m 39s	remaining: 9m 16s
4609:	learn: 0.0020086	total: 7m 39s	remaining: 8m 57s
4522:	learn: 0.0018909	total: 7m 39s	remaining: 9m 16s
4395:	learn: 0.0022116	total: 7m 39s	remaining: 9m 46s
4524:	learn: 0.0021996	total: 7m 39s	remaining: 9m 16s
4213:	learn: 0.0023152	total: 7m 39s	remaining: 10m 31s
4610:	learn: 0.0020086	total: 7m 39s	remaining: 8m 57s
4523:	learn: 0.0018909	total: 7m 39s	remaining: 9m 16s
4396:	learn: 0.0022106	total: 7m 39s	remaining: 9m 46s
4525:	learn: 0.0021986	total: 7m 39s	remaining: 9m 16s
4214:	learn: 0.0023145	total: 7m 40s	remaining: 10m 31s
4611:	learn: 0.0020086	total: 7m 40s	remaining: 8m 57s
4397:	learn: 0.0022095	total: 7m 40s	remaining: 9m 45s
4524:	learn: 0.0018909	total: 7m 40s	remaining: 9m 16s
4526:	learn: 0.0021980	total: 7m 39s	remaining: 9m 16s
4215:	learn: 0.0023137	total: 7m 40s	remaining: 10m 31s
4612:	learn: 0.0020080	total: 7m 40s	remaining: 8m 57s
4398:	learn: 0.0022095	total: 7m 40s	remaining: 9m 45s
4525:	learn: 0.0018909	total: 7m 40s	remaining: 9m 16s
4527:	learn: 0.0021970	total: 7m 40s	remaining: 9m 15s
4216:	learn: 0.0023132	total: 7m 40s	remaining: 10m 31s
4399:	learn: 0.0022086	total: 7m 40s	remaining: 9m 45s
4613:	learn: 0.0020080	total: 7m 40s	remaining: 8m 57s
4526:	learn: 0.0018909	total: 7m 40s	remaining: 9m 16s
4528:	learn: 0.0021965	total: 7m 40s	remaining: 9m 15s
4400:	learn: 0.0022077	total: 7m 40s	remaining: 9m 45s
4217:	learn: 0.0023123	total: 7m 40s	remaining: 10m 31s
4614:	learn: 0.0020078	total: 7m 40s	remaining: 8m 57s
4527:	learn: 0.0018909	total: 7m 40s	remaining: 9m 16s
4401:	learn: 0.0022077	total: 7m 40s	remaining: 9m 45s
4615:	learn: 0.0020071	total: 7m 40s	remaining: 8m 57s
4529:	learn: 0.0021954	total: 7m 40s	remaining: 9m 15s
4218:	learn: 0.0023112	total: 7m 40s	remaining: 10m 30s
4528:	learn: 0.0018909	total: 7m 40s	remaining: 9m 16s
4402:	learn: 0.0022077	total: 7m 40s	remaining: 9m 45s
4530:	learn: 0.0021945	total: 7m 40s	remaining: 9m 15s
4616:	learn: 0.0020066	total: 7m 40s	remaining: 8m 56s
4219:	learn: 0.0023104	total: 7m 40s	remaining: 10m 30s
4531:	learn: 0.0021935	total: 7m 40s	remaining: 9m 15s
4529:	learn: 0.0018909	total: 7m 40s	remaining: 9m 16s
4403:	learn: 0.0022068	total: 7m 40s	remaining: 9m 45s
4617:	learn: 0.0020066	total: 7m 40s	remaining: 8m 56s
4532:	learn: 0.0021928	total: 7m 40s	remaining: 9m 15s
4220:	learn: 0.0023099	total: 7m 40s	remaining: 10m 30s
4404:	learn: 0.0022059	total: 7m 40s	remaining: 9m 45s
4530:	learn: 0.0018906	total: 7m 40s	remaining: 9m 16s
4618:	learn: 0.0020066	total: 7m 40s	remaining: 8m 56s
4533:	learn: 0.0021917	total: 7m 40s	remaining: 9m 15s
4405:	learn: 0.0022053	total: 7m 40s	remaining: 9m 45s
4531:	learn: 0.0018906	total: 7m 40s	remaining: 9m 15s
4221:	learn: 0.0023092	total: 7m 40s	remaining: 10m 30s
4619:	learn: 0.0020066	total: 7m 40s	remaining: 8m 56s
4534:	learn: 0.0021907	total: 7m 40s	remaining: 9m 15s
4406:	learn: 0.0022048	total: 7m 40s	remaining: 9m 44s
4532:	learn: 0.0018906	total: 7m 40s	remaining: 9m 15s
4222:	learn: 0.0023083	total: 7m 40s	remaining: 10m 30s
4620:	learn: 0.0020065	total: 7m 40s	remaining: 8m 56s
4535:	learn: 0.0021900	total: 7m 40s	remaining: 9m 15s
4223:	learn: 0.0023076	total: 7m 41s	remaining: 10m 30s
4407:	learn: 0.0022042	total: 7m 40s	remaining: 9m 44s
4533:	learn: 0.0018906	total: 7m 40s	remaining: 9m 15s
4536:	learn: 0.0021888	total: 7m 40s	remaining: 9m 14s
4621:	learn: 0.0020065	total: 7m 41s	remaining: 8m 56s
4622:	learn: 0.0020059	total: 7m 41s	remaining: 8m 56s
4408:	learn: 0.0022033	total: 7m 41s	remaining: 9m 44s
4224:	learn: 0.0023065	total: 7m 41s	remaining: 10m 30s
4534:	learn: 0.0018906	total: 7m 41s	remaining: 9m 15s
4537:	learn: 0.0021880	total: 7m 40s	remaining: 9m 14s
4623:	learn: 0.0020051	total: 7m 41s	remaining: 8m 56s
4409:	learn: 0.0022028	total: 7m 41s	remaining: 9m 44s
4225:	learn: 0.0023059	total: 7m 41s	remaining: 10m 30s
4535:	learn: 0.0018906	total: 7m 41s	remaining: 9m 15s
4538:	learn: 0.0021871	total: 7m 41s	remaining: 9m 14s
4624:	learn: 0.0020042	total: 7m 41s	remaining: 8m 56s
4410:	learn: 0.0022020	total: 7m 41s	remaining: 9m 44s
4226:	learn: 0.0023050	total: 7m 41s	remaining: 10m 30s
4625:	learn: 0.0020036	total: 7m 41s	remaining: 8m 55s
4536:	learn: 0.0018906	total: 7m 41s	remaining: 9m 15s
4539:	learn: 0.0021869	total: 7m 41s	remaining: 9m 14s
4411:	learn: 0.0022011	total: 7m 41s	remaining: 9m 44s
4227:	learn: 0.0023043	total: 7m 41s	remaining: 10m 29s
4626:	learn: 0.0020034	total: 7m 41s	remaining: 8m 55s
4537:	learn: 0.0018906	total: 7m 41s	remaining: 9m 15s
4540:	learn: 0.0021863	total: 7m 41s	remaining: 9m 14s
4228:	learn: 0.0023034	total: 7m 41s	remaining: 10m 29s
4412:	learn: 0.0022003	total: 7m 41s	remaining: 9m 44s
4627:	learn: 0.0020030	total: 7m 41s	remaining: 8m 55s
4538:	learn: 0.0018906	total: 7m 41s	remaining: 9m 15s
4541:	learn: 0.0021856	total: 7m 41s	remaining: 9m 14s
4413:	learn: 0.0021990	total: 7m 41s	remaining: 9m 44s
4229:	learn: 0.0023023	total: 7m 41s	remaining: 10m 29s
4539:	learn: 0.0018902	total: 7m 41s	remaining: 9m 15s
4628:	learn: 0.0020022	total: 7m 41s	remaining: 8m 55s
4542:	learn: 0.0021845	total: 7m 41s	remaining: 9m 14s
4414:	learn: 0.0021982	total: 7m 41s	remaining: 9m 44s
4230:	learn: 0.0023015	total: 7m 41s	remaining: 10m 29s
4629:	learn: 0.0020022	total: 7m 41s	remaining: 8m 55s
4540:	learn: 0.0018902	total: 7m 41s	remaining: 9m 15s
4543:	learn: 0.0021833	total: 7m 41s	remaining: 9m 14s
4415:	learn: 0.0021975	total: 7m 41s	remaining: 9m 43s
4541:	learn: 0.0018902	total: 7m 41s	remaining: 9m 14s

4630:	learn: 0.0020018	total: 7m 41s	remaining: 8m 55s
4231:	learn: 0.0023009	total: 7m 41s	remaining: 10m 29s
4544:	learn: 0.0021825	total: 7m 41s	remaining: 9m 14s
4416:	learn: 0.0021969	total: 7m 41s	remaining: 9m 43s
4542:	learn: 0.0018895	total: 7m 41s	remaining: 9m 14s
4631:	learn: 0.0020011	total: 7m 41s	remaining: 8m 55s
4232:	learn: 0.0022999	total: 7m 42s	remaining: 10m 29s
4545:	learn: 0.0021816	total: 7m 41s	remaining: 9m 14s
4543:	learn: 0.0018895	total: 7m 41s	remaining: 9m 14s
4417:	learn: 0.0021962	total: 7m 42s	remaining: 9m 43s
4632:	learn: 0.0020004	total: 7m 42s	remaining: 8m 55s
4546:	learn: 0.0021808	total: 7m 41s	remaining: 9m 13s
4233:	learn: 0.0022993	total: 7m 42s	remaining: 10m 29s
4544:	learn: 0.0018895	total: 7m 42s	remaining: 9m 14s
4418:	learn: 0.0021949	total: 7m 42s	remaining: 9m 43s
4633:	learn: 0.0020000	total: 7m 42s	remaining: 8m 55s
4547:	learn: 0.0021802	total: 7m 42s	remaining: 9m 13s
4545:	learn: 0.0018895	total: 7m 42s	remaining: 9m 14s
4234:	learn: 0.0022983	total: 7m 42s	remaining: 10m 29s
4634:	learn: 0.0020000	total: 7m 42s	remaining: 8m 55s
4419:	learn: 0.0021940	total: 7m 42s	remaining: 9m 43s
4635:	learn: 0.0020000	total: 7m 42s	remaining: 8m 54s
4548:	learn: 0.0021793	total: 7m 42s	remaining: 9m 13s
4420:	learn: 0.0021932	total: 7m 42s	remaining: 9m 43s
4546:	learn: 0.0018895	total: 7m 42s	remaining: 9m 14s
4235:	learn: 0.0022972	total: 7m 42s	remaining: 10m 29s
4421:	learn: 0.0021923	total: 7m 42s	remaining: 9m 43s
4547:	learn: 0.0018895	total: 7m 42s	remaining: 9m 14s
4636:	learn: 0.0019998	total: 7m 42s	remaining: 8m 54s
4549:	learn: 0.0021784	total: 7m 42s	remaining: 9m 13s
4236:	learn: 0.0022963	total: 7m 42s	remaining: 10m 29s
4548:	learn: 0.0018895	total: 7m 42s	remaining: 9m 14s
4422:	learn: 0.0021914	total: 7m 42s	remaining: 9m 43s
4637:	learn: 0.0019992	total: 7m 42s	remaining: 8m 54s
4550:	learn: 0.0021774	total: 7m 42s	remaining: 9m 13s
4549:	learn: 0.0018895	total: 7m 42s	remaining: 9m 14s
4237:	learn: 0.0022952	total: 7m 42s	remaining: 10m 28s
4423:	learn: 0.0021906	total: 7m 42s	remaining: 9m 43s
4638:	learn: 0.0019985	total: 7m 42s	remaining: 8m 54s
4551:	learn: 0.0021765	total: 7m 42s	remaining: 9m 13s
4550:	learn: 0.0018895	total: 7m 42s	remaining: 9m 13s
4238:	learn: 0.0022946	total: 7m 42s	remaining: 10m 28s
4424:	learn: 0.0021895	total: 7m 42s	remaining: 9m 42s
4639:	learn: 0.0019984	total: 7m 42s	remaining: 8m 54s
4552:	learn: 0.0021755	total: 7m 42s	remaining: 9m 13s
4239:	learn: 0.0022940	total: 7m 42s	remaining: 10m 28s
4551:	learn: 0.0018895	total: 7m 42s	remaining: 9m 13s
4425:	learn: 0.0021890	total: 7m 42s	remaining: 9m 42s
4640:	learn: 0.0019978	total: 7m 42s	remaining: 8m 54s
4553:	learn: 0.0021747	total: 7m 42s	remaining: 9m 13s
4240:	learn: 0.0022931	total: 7m 42s	remaining: 10m 28s
4426:	learn: 0.0021890	total: 7m 42s	remaining: 9m 42s
4552:	learn: 0.0018895	total: 7m 42s	remaining: 9m 13s
4641:	learn: 0.0019978	total: 7m 42s	remaining: 8m 54s
4427:	learn: 0.0021890	total: 7m 42s	remaining: 9m 42s
4554:	learn: 0.0021738	total: 7m 42s	remaining: 9m 13s
4642:	learn: 0.0019978	total: 7m 42s	remaining: 8m 54s
4553:	learn: 0.0018895	total: 7m 42s	remaining: 9m 13s
4241:	learn: 0.0022920	total: 7m 43s	remaining: 10m 28s
4555:	learn: 0.0021732	total: 7m 42s	remaining: 9m 13s
4428:	learn: 0.0021882	total: 7m 43s	remaining: 9m 42s
4643:	learn: 0.0019971	total: 7m 43s	remaining: 8m 54s
4554:	learn: 0.0018895	total: 7m 43s	remaining: 9m 13s
4242:	learn: 0.0022910	total: 7m 43s	remaining: 10m 28s
4556:	learn: 0.0021723	total: 7m 42s	remaining: 9m 13s
4644:	learn: 0.0019966	total: 7m 43s	remaining: 8m 53s
4429:	learn: 0.0021873	total: 7m 43s	remaining: 9m 42s
4555:	learn: 0.0018888	total: 7m 43s	remaining: 9m 13s
4557:	learn: 0.0021718	total: 7m 43s	remaining: 9m 12s
4243:	learn: 0.0022903	total: 7m 43s	remaining: 10m 28s
4645:	learn: 0.0019958	total: 7m 43s	remaining: 8m 53s
4556:	learn: 0.0018882	total: 7m 43s	remaining: 9m 13s
4430:	learn: 0.0021863	total: 7m 43s	remaining: 9m 42s
4244:	learn: 0.0022891	total: 7m 43s	remaining: 10m 28s
4558:	learn: 0.0021711	total: 7m 43s	remaining: 9m 12s
4646:	learn: 0.0019958	total: 7m 43s	remaining: 8m 53s
4557:	learn: 0.0018875	total: 7m 43s	remaining: 9m 13s
4431:	learn: 0.0021857	total: 7m 43s	remaining: 9m 42s
4245:	learn: 0.0022880	total: 7m 43s	remaining: 10m 28s
4559:	learn: 0.0021711	total: 7m 43s	remaining: 9m 12s
4558:	learn: 0.0018875	total: 7m 43s	remaining: 9m 13s
4647:	learn: 0.0019951	total: 7m 43s	remaining: 8m 53s
4432:	learn: 0.0021849	total: 7m 43s	remaining: 9m 42s
4246:	learn: 0.0022870	total: 7m 43s	remaining: 10m 27s
4560:	learn: 0.0021705	total: 7m 43s	remaining: 9m 12s
4648:	learn: 0.0019945	total: 7m 43s	remaining: 8m 53s
4433:	learn: 0.0021843	total: 7m 43s	remaining: 9m 41s
4559:	learn: 0.0018875	total: 7m 43s	remaining: 9m 13s
4247:	learn: 0.0022865	total: 7m 43s	remaining: 10m 27s
4561:	learn: 0.0021696	total: 7m 43s	remaining: 9m 12s
4649:	learn: 0.0019942	total: 7m 43s	remaining: 8m 53s
4434:	learn: 0.0021843	total: 7m 43s	remaining: 9m 41s
4248:	learn: 0.0022858	total: 7m 43s	remaining: 10m 27s
4560:	learn: 0.0018875	total: 7m 43s	remaining: 9m 12s
4562:	learn: 0.0021688	total: 7m 43s	remaining: 9m 12s
4650:	learn: 0.0019938	total: 7m 43s	remaining: 8m 53s
4435:	learn: 0.0021842	total: 7m 43s	remaining: 9m 41s
4249:	learn: 0.0022849	total: 7m 43s	remaining: 10m 27s
4561:	learn: 0.0018875	total: 7m 43s	remaining: 9m 12s
4563:	learn: 0.0021678	total: 7m 43s	remaining: 9m 12s
4436:	learn: 0.0021833	total: 7m 43s	remaining: 9m 41s
4651:	learn: 0.0019932	total: 7m 43s	remaining: 8m 53s
4250:	learn: 0.0022838	total: 7m 43s	remaining: 10m 27s
4562:	learn: 0.0018875	total: 7m 43s	remaining: 9m 12s
4564:	learn: 0.0021673	total: 7m 43s	remaining: 9m 12s
4437:	learn: 0.0021833	total: 7m 43s	remaining: 9m 41s
4652:	learn: 0.0019931	total: 7m 43s	remaining: 8m 53s
4563:	learn: 0.0018875	total: 7m 43s	remaining: 9m 12s
4251:	learn: 0.0022829	total: 7m 44s	remaining: 10m 27s
4565:	learn: 0.0021668	total: 7m 43s	remaining: 9m 12s
4653:	learn: 0.0019925	total: 7m 44s	remaining: 8m 53s
4438:	learn: 0.0021833	total: 7m 44s	remaining: 9m 41s
4564:	learn: 0.0018867	total: 7m 44s	remaining: 9m 12s
4252:	learn: 0.0022818	total: 7m 44s	remaining: 10m 27s
4566:	learn: 0.0021663	total: 7m 43s	remaining: 9m 11s
4654:	learn: 0.0019925	total: 7m 44s	remaining: 8m 52s
4439:	learn: 0.0021833	total: 7m 44s	remaining: 9m 41s
4565:	learn: 0.0018867	total: 7m 44s	remaining: 9m 12s
4655:	learn: 0.0019925	total: 7m 44s	remaining: 8m 52s
4567:	learn: 0.0021655	total: 7m 44s	remaining: 9m 11s
4253:	learn: 0.0022810	total: 7m 44s	remaining: 10m 27s
4440:	learn: 0.0021826	total: 7m 44s	remaining: 9m 41s
4566:	learn: 0.0018867	total: 7m 44s	remaining: 9m 12s
4656:	learn: 0.0019919	total: 7m 44s	remaining: 8m 52s
4568:	learn: 0.0021650	total: 7m 44s	remaining: 9m 11s
4254:	learn: 0.0022801	total: 7m 44s	remaining: 10m 27s
4441:	learn: 0.0021821	total: 7m 44s	remaining: 9m 41s
4567:	learn: 0.0018864	total: 7m 44s	remaining: 9m 12s
4569:	learn: 0.0021645	total: 7m 44s	remaining: 9m 11s
4657:	learn: 0.0019913	total: 7m 44s	remaining: 8m 52s
4442:	learn: 0.0021816	total: 7m 44s	remaining: 9m 40s
4255:	learn: 0.0022795	total: 7m 44s	remaining: 10m 26s
4568:	learn: 0.0018864	total: 7m 44s	remaining: 9m 12s
4443:	learn: 0.0021810	total: 7m 44s	remaining: 9m 40s
4658:	learn: 0.0019910	total: 7m 44s	remaining: 8m 52s
4570:	learn: 0.0021641	total: 7m 44s	remaining: 9m 11s
4569:	learn: 0.0018864	total: 7m 44s	remaining: 9m 11s
4256:	learn: 0.0022784	total: 7m 44s	remaining: 10m 26s
4444:	learn: 0.0021802	total: 7m 44s	remaining: 9m 40s
4659:	learn: 0.0019906	total: 7m 44s	remaining: 8m 52s
4571:	learn: 0.0021636	total: 7m 44s	remaining: 9m 11s
4570:	learn: 0.0018864	total: 7m 44s	remaining: 9m 11s
4572:	learn: 0.0021628	total: 7m 44s	remaining: 9m 11s
4257:	learn: 0.0022773	total: 7m 44s	remaining: 10m 26s
4445:	learn: 0.0021793	total: 7m 44s	remaining: 9m 40s
4571:	learn: 0.0018864	total: 7m 44s	remaining: 9m 11s
4660:	learn: 0.0019900	total: 7m 44s	remaining: 8m 52s
4573:	learn: 0.0021621	total: 7m 44s	remaining: 9m 11s
4446:	learn: 0.0021783	total: 7m 44s	remaining: 9m 40s
4572:	learn: 0.0018858	total: 7m 44s	remaining: 9m 11s
4661:	learn: 0.0019892	total: 7m 44s	remaining: 8m 52s
4258:	learn: 0.0022761	total: 7m 44s	remaining: 10m 26s
4573:	learn: 0.0018858	total: 7m 44s	remaining: 9m 11s
4574:	learn: 0.0021615	total: 7m 44s	remaining: 9m 11s
4447:	learn: 0.0021775	total: 7m 44s	remaining: 9m 40s
4662:	learn: 0.0019885	total: 7m 44s	remaining: 8m 52s
4259:	learn: 0.0022755	total: 7m 45s	remaining: 10m 26s
4575:	learn: 0.0021605	total: 7m 44s	remaining: 9m 10s
4574:	learn: 0.0018858	total: 7m 44s	remaining: 9m 11s
4448:	learn: 0.0021769	total: 7m 45s	remaining: 9m 40s
4663:	learn: 0.0019881	total: 7m 45s	remaining: 8m 52s
4576:	learn: 0.0021598	total: 7m 44s	remaining: 9m 10s
4575:	learn: 0.0018858	total: 7m 45s	remaining: 9m 11s
4260:	learn: 0.0022744	total: 7m 45s	remaining: 10m 26s
4664:	learn: 0.0019874	total: 7m 45s	remaining: 8m 51s
4449:	learn: 0.0021761	total: 7m 45s	remaining: 9m 40s
4576:	learn: 0.0018858	total: 7m 45s	remaining: 9m 11s
4577:	learn: 0.0021587	total: 7m 45s	remaining: 9m 10s
4665:	learn: 0.0019874	total: 7m 45s	remaining: 8m 51s
4261:	learn: 0.0022739	total: 7m 45s	remaining: 10m 26s
4450:	learn: 0.0021754	total: 7m 45s	remaining: 9m 40s
4577:	learn: 0.0018858	total: 7m 45s	remaining: 9m 11s
4578:	learn: 0.0021581	total: 7m 45s	remaining: 9m 10s
4666:	learn: 0.0019874	total: 7m 45s	remaining: 8m 51s
4262:	learn: 0.0022733	total: 7m 45s	remaining: 10m 26s
4578:	learn: 0.0018858	total: 7m 45s	remaining: 9m 10s
4451:	learn: 0.0021746	total: 7m 45s	remaining: 9m 39s
4579:	learn: 0.0021572	total: 7m 45s	remaining: 9m 10s
4263:	learn: 0.0022723	total: 7m 45s	remaining: 10m 26s
4667:	learn: 0.0019874	total: 7m 45s	remaining: 8m 51s
4579:	learn: 0.0018858	total: 7m 45s	remaining: 9m 10s
4452:	learn: 0.0021746	total: 7m 45s	remaining: 9m 39s
4580:	learn: 0.0021563	total: 7m 45s	remaining: 9m 10s
4668:	learn: 0.0019874	total: 7m 45s	remaining: 8m 51s
4453:	learn: 0.0021736	total: 7m 45s	remaining: 9m 39s
4264:	learn: 0.0022714	total: 7m 45s	remaining: 10m 26s
4580:	learn: 0.0018858	total: 7m 45s	remaining: 9m 10s
4581:	learn: 0.0021553	total: 7m 45s	remaining: 9m 10s
4669:	learn: 0.0019874	total: 7m 45s	remaining: 8m 51s
4581:	learn: 0.0018858	total: 7m 45s	remaining: 9m 10s
4454:	learn: 0.0021736	total: 7m 45s	remaining: 9m 39s
4265:	learn: 0.0022703	total: 7m 45s	remaining: 10m 25s
4582:	learn: 0.0021554	total: 7m 45s	remaining: 9m 10s
4670:	learn: 0.0019868	total: 7m 45s	remaining: 8m 51s
4455:	learn: 0.0021736	total: 7m 45s	remaining: 9m 39s
4582:	learn: 0.0018853	total: 7m 45s	remaining: 9m 10s
4266:	learn: 0.0022692	total: 7m 45s	remaining: 10m 25s
4671:	learn: 0.0019868	total: 7m 45s	remaining: 8m 51s
4583:	learn: 0.0021549	total: 7m 45s	remaining: 9m 10s
4456:	learn: 0.0021736	total: 7m 45s	remaining: 9m 39s
4672:	learn: 0.0019868	total: 7m 45s	remaining: 8m 51s
4583:	learn: 0.0018852	total: 7m 45s	remaining: 9m 10s
4267:	learn: 0.0022682	total: 7m 45s	remaining: 10m 25s
4584:	learn: 0.0021549	total: 7m 45s	remaining: 9m 10s
4673:	learn: 0.0019863	total: 7m 45s	remaining: 8m 50s
4457:	learn: 0.0021736	total: 7m 45s	remaining: 9m 39s
4584:	learn: 0.0018852	total: 7m 45s	remaining: 9m 10s
4585:	learn: 0.0021539	total: 7m 45s	remaining: 9m 9s
4268:	learn: 0.0022682	total: 7m 46s	remaining: 10m 25s
4674:	learn: 0.0019858	total: 7m 46s	remaining: 8m 50s
4586:	learn: 0.0021538	total: 7m 45s	remaining: 9m 9s
4585:	learn: 0.0018852	total: 7m 46s	remaining: 9m 10s
4458:	learn: 0.0021729	total: 7m 46s	remaining: 9m 39s
4675:	learn: 0.0019851	total: 7m 46s	remaining: 8m 50s
4269:	learn: 0.0022671	total: 7m 46s	remaining: 10m 25s
4586:	learn: 0.0018852	total: 7m 46s	remaining: 9m 10s
4587:	learn: 0.0021532	total: 7m 46s	remaining: 9m 9s
4459:	learn: 0.0021729	total: 7m 46s	remaining: 9m 39s
4270:	learn: 0.0022669	total: 7m 46s	remaining: 10m 25s
4676:	learn: 0.0019844	total: 7m 46s	remaining: 8m 50s
4587:	learn: 0.0018853	total: 7m 46s	remaining: 9m 9s
4588:	learn: 0.0021527	total: 7m 46s	remaining: 9m 9s
4271:	learn: 0.0022665	total: 7m 46s	remaining: 10m 25s
4677:	learn: 0.0019844	total: 7m 46s	remaining: 8m 50s
4460:	learn: 0.0021723	total: 7m 46s	remaining: 9m 39s
4588:	learn: 0.0018846	total: 7m 46s	remaining: 9m 9s
4589:	learn: 0.0021518	total: 7m 46s	remaining: 9m 9s
4272:	learn: 0.0022660	total: 7m 46s	remaining: 10m 25s
4678:	learn: 0.0019844	total: 7m 46s	remaining: 8m 50s
4461:	learn: 0.0021723	total: 7m 46s	remaining: 9m 38s
4589:	learn: 0.0018840	total: 7m 46s	remaining: 9m 9s
4590:	learn: 0.0021508	total: 7m 46s	remaining: 9m 9s
4273:	learn: 0.0022654	total: 7m 46s	remaining: 10m 25s
4679:	learn: 0.0019838	total: 7m 46s	remaining: 8m 50s
4462:	learn: 0.0021715	total: 7m 46s	remaining: 9m 38s
4590:	learn: 0.0018840	total: 7m 46s	remaining: 9m 9s
4591:	learn: 0.0021503	total: 7m 46s	remaining: 9m 9s
4274:	learn: 0.0022645	total: 7m 46s	remaining: 10m 24s
4680:	learn: 0.0019833	total: 7m 46s	remaining: 8m 50s
4463:	learn: 0.0021708	total: 7m 46s	remaining: 9m 38s
4591:	learn: 0.0018840	total: 7m 46s	remaining: 9m 9s
4681:	learn: 0.0019832	total: 7m 46s	remaining: 8m 50s
4592:	learn: 0.0021498	total: 7m 46s	remaining: 9m 9s
4275:	learn: 0.0022636	total: 7m 46s	remaining: 10m 24s
4592:	learn: 0.0018840	total: 7m 46s	remaining: 9m 9s
4464:	learn: 0.0021707	total: 7m 46s	remaining: 9m 38s
4682:	learn: 0.0019830	total: 7m 46s	remaining: 8m 49s
4593:	learn: 0.0021489	total: 7m 46s	remaining: 9m 9s
4276:	learn: 0.0022626	total: 7m 46s	remaining: 10m 24s
4593:	learn: 0.0018840	total: 7m 46s	remaining: 9m 9s
4277:	learn: 0.0022615	total: 7m 46s	remaining: 10m 24s
4465:	learn: 0.0021700	total: 7m 46s	remaining: 9m 38s
4683:	learn: 0.0019830	total: 7m 46s	remaining: 8m 49s
4594:	learn: 0.0018840	total: 7m 46s	remaining: 9m 9s
4594:	learn: 0.0021479	total: 7m 46s	remaining: 9m 9s
4278:	learn: 0.0022609	total: 7m 47s	remaining: 10m 24s
4595:	learn: 0.0021474	total: 7m 46s	remaining: 9m 8s
4684:	learn: 0.0019827	total: 7m 46s	remaining: 8m 49s
4466:	learn: 0.0021698	total: 7m 46s	remaining: 9m 38s
4595:	learn: 0.0018840	total: 7m 46s	remaining: 9m 9s
4685:	learn: 0.0019821	total: 7m 47s	remaining: 8m 49s
4279:	learn: 0.0022602	total: 7m 47s	remaining: 10m 24s
4596:	learn: 0.0021466	total: 7m 46s	remaining: 9m 8s
4596:	learn: 0.0018840	total: 7m 47s	remaining: 9m 8s
4467:	learn: 0.0021693	total: 7m 47s	remaining: 9m 38s
4597:	learn: 0.0021460	total: 7m 47s	remaining: 9m 8s
4686:	learn: 0.0019815	total: 7m 47s	remaining: 8m 49s
4597:	learn: 0.0018840	total: 7m 47s	remaining: 9m 8s
4280:	learn: 0.0022593	total: 7m 47s	remaining: 10m 24s
4468:	learn: 0.0021692	total: 7m 47s	remaining: 9m 38s
4598:	learn: 0.0021454	total: 7m 47s	remaining: 9m 8s
4687:	learn: 0.0019809	total: 7m 47s	remaining: 8m 49s
4598:	learn: 0.0018840	total: 7m 47s	remaining: 9m 8s
4281:	learn: 0.0022588	total: 7m 47s	remaining: 10m 24s
4469:	learn: 0.0021692	total: 7m 47s	remaining: 9m 38s
4599:	learn: 0.0021450	total: 7m 47s	remaining: 9m 8s
4688:	learn: 0.0019806	total: 7m 47s	remaining: 8m 49s
4599:	learn: 0.0018840	total: 7m 47s	remaining: 9m 8s
4282:	learn: 0.0022584	total: 7m 47s	remaining: 10m 23s
4470:	learn: 0.0021680	total: 7m 47s	remaining: 9m 38s
4600:	learn: 0.0021441	total: 7m 47s	remaining: 9m 8s
4689:	learn: 0.0019801	total: 7m 47s	remaining: 8m 49s
4600:	learn: 0.0018840	total: 7m 47s	remaining: 9m 8s
4283:	learn: 0.0022574	total: 7m 47s	remaining: 10m 23s
4601:	learn: 0.0021435	total: 7m 47s	remaining: 9m 8s
4471:	learn: 0.0021675	total: 7m 47s	remaining: 9m 37s
4690:	learn: 0.0019796	total: 7m 47s	remaining: 8m 49s
4602:	learn: 0.0021430	total: 7m 47s	remaining: 9m 8s
4284:	learn: 0.0022560	total: 7m 47s	remaining: 10m 23s
4601:	learn: 0.0018840	total: 7m 47s	remaining: 9m 8s
4691:	learn: 0.0019794	total: 7m 47s	remaining: 8m 49s
4472:	learn: 0.0021667	total: 7m 47s	remaining: 9m 37s
4285:	learn: 0.0022555	total: 7m 47s	remaining: 10m 23s
4603:	learn: 0.0021425	total: 7m 47s	remaining: 9m 8s
4602:	learn: 0.0018840	total: 7m 47s	remaining: 9m 8s
4692:	learn: 0.0019791	total: 7m 47s	remaining: 8m 48s
4473:	learn: 0.0021659	total: 7m 47s	remaining: 9m 37s

4286:	learn: 0.0022542	total: 7m 47s	remaining: 10m 23s
4693:	learn: 0.0019786	total: 7m 47s	remaining: 8m 48s
4603:	learn: 0.0018840	total: 7m 47s	remaining: 9m 8s
4604:	learn: 0.0021416	total: 7m 47s	remaining: 9m 7s
4474:	learn: 0.0021651	total: 7m 47s	remaining: 9m 37s
4287:	learn: 0.0022532	total: 7m 47s	remaining: 10m 23s
4694:	learn: 0.0019781	total: 7m 47s	remaining: 8m 48s
4604:	learn: 0.0018840	total: 7m 47s	remaining: 9m 8s
4475:	learn: 0.0021649	total: 7m 47s	remaining: 9m 37s
4605:	learn: 0.0021409	total: 7m 47s	remaining: 9m 7s
4288:	learn: 0.0022523	total: 7m 48s	remaining: 10m 23s
4695:	learn: 0.0019775	total: 7m 48s	remaining: 8m 48s
4605:	learn: 0.0018840	total: 7m 48s	remaining: 9m 8s
4476:	learn: 0.0021643	total: 7m 48s	remaining: 9m 37s
4606:	learn: 0.0021399	total: 7m 47s	remaining: 9m 7s
4696:	learn: 0.0019770	total: 7m 48s	remaining: 8m 48s
4289:	learn: 0.0022512	total: 7m 48s	remaining: 10m 23s
4477:	learn: 0.0021643	total: 7m 48s	remaining: 9m 37s
4607:	learn: 0.0021393	total: 7m 48s	remaining: 9m 7s
4606:	learn: 0.0018840	total: 7m 48s	remaining: 9m 8s
4290:	learn: 0.0022499	total: 7m 48s	remaining: 10m 22s
4697:	learn: 0.0019763	total: 7m 48s	remaining: 8m 48s
4608:	learn: 0.0021388	total: 7m 48s	remaining: 9m 7s
4478:	learn: 0.0021633	total: 7m 48s	remaining: 9m 37s
4607:	learn: 0.0018840	total: 7m 48s	remaining: 9m 7s
4291:	learn: 0.0022489	total: 7m 48s	remaining: 10m 22s
4698:	learn: 0.0019757	total: 7m 48s	remaining: 8m 48s
4609:	learn: 0.0021379	total: 7m 48s	remaining: 9m 7s
4608:	learn: 0.0018840	total: 7m 48s	remaining: 9m 7s
4479:	learn: 0.0021624	total: 7m 48s	remaining: 9m 37s
4699:	learn: 0.0019753	total: 7m 48s	remaining: 8m 48s
4292:	learn: 0.0022481	total: 7m 48s	remaining: 10m 22s
4610:	learn: 0.0021379	total: 7m 48s	remaining: 9m 7s
4609:	learn: 0.0018840	total: 7m 48s	remaining: 9m 7s
4480:	learn: 0.0021623	total: 7m 48s	remaining: 9m 37s
4293:	learn: 0.0022475	total: 7m 48s	remaining: 10m 22s
4700:	learn: 0.0019750	total: 7m 48s	remaining: 8m 48s
4610:	learn: 0.0018840	total: 7m 48s	remaining: 9m 7s
4611:	learn: 0.0021379	total: 7m 48s	remaining: 9m 7s
4481:	learn: 0.0021616	total: 7m 48s	remaining: 9m 36s
4294:	learn: 0.0022466	total: 7m 48s	remaining: 10m 22s
4701:	learn: 0.0019744	total: 7m 48s	remaining: 8m 48s
4611:	learn: 0.0018840	total: 7m 48s	remaining: 9m 7s
4482:	learn: 0.0021608	total: 7m 48s	remaining: 9m 36s
4612:	learn: 0.0021374	total: 7m 48s	remaining: 9m 7s
4702:	learn: 0.0019739	total: 7m 48s	remaining: 8m 47s
4295:	learn: 0.0022455	total: 7m 48s	remaining: 10m 22s
4612:	learn: 0.0018840	total: 7m 48s	remaining: 9m 7s
4613:	learn: 0.0021368	total: 7m 48s	remaining: 9m 7s
4483:	learn: 0.0021608	total: 7m 48s	remaining: 9m 36s
4703:	learn: 0.0019733	total: 7m 48s	remaining: 8m 47s
4614:	learn: 0.0021364	total: 7m 48s	remaining: 9m 6s
4613:	learn: 0.0018840	total: 7m 48s	remaining: 9m 7s
4484:	learn: 0.0021608	total: 7m 48s	remaining: 9m 36s
4296:	learn: 0.0022445	total: 7m 48s	remaining: 10m 22s
4704:	learn: 0.0019727	total: 7m 48s	remaining: 8m 47s
4485:	learn: 0.0021608	total: 7m 48s	remaining: 9m 36s
4615:	learn: 0.0021353	total: 7m 48s	remaining: 9m 6s
4614:	learn: 0.0018840	total: 7m 48s	remaining: 9m 7s
4297:	learn: 0.0022437	total: 7m 49s	remaining: 10m 22s
4486:	learn: 0.0021603	total: 7m 49s	remaining: 9m 36s
4705:	learn: 0.0019720	total: 7m 49s	remaining: 8m 47s
4616:	learn: 0.0021353	total: 7m 48s	remaining: 9m 6s
4615:	learn: 0.0018840	total: 7m 49s	remaining: 9m 7s
4298:	learn: 0.0022429	total: 7m 49s	remaining: 10m 22s
4706:	learn: 0.0019714	total: 7m 49s	remaining: 8m 47s
4616:	learn: 0.0018840	total: 7m 49s	remaining: 9m 6s
4487:	learn: 0.0021593	total: 7m 49s	remaining: 9m 36s
4617:	learn: 0.0021348	total: 7m 49s	remaining: 9m 6s
4299:	learn: 0.0022420	total: 7m 49s	remaining: 10m 22s
4707:	learn: 0.0019714	total: 7m 49s	remaining: 8m 47s
4488:	learn: 0.0021585	total: 7m 49s	remaining: 9m 36s
4617:	learn: 0.0018840	total: 7m 49s	remaining: 9m 6s
4618:	learn: 0.0021338	total: 7m 49s	remaining: 9m 6s
4300:	learn: 0.0022413	total: 7m 49s	remaining: 10m 21s
4708:	learn: 0.0019709	total: 7m 49s	remaining: 8m 47s
4618:	learn: 0.0018840	total: 7m 49s	remaining: 9m 6s
4489:	learn: 0.0021585	total: 7m 49s	remaining: 9m 35s
4301:	learn: 0.0022403	total: 7m 49s	remaining: 10m 21s
4619:	learn: 0.0021333	total: 7m 49s	remaining: 9m 6s
4709:	learn: 0.0019704	total: 7m 49s	remaining: 8m 47s
4619:	learn: 0.0018840	total: 7m 49s	remaining: 9m 6s
4490:	learn: 0.0021579	total: 7m 49s	remaining: 9m 35s
4620:	learn: 0.0021329	total: 7m 49s	remaining: 9m 6s
4302:	learn: 0.0022396	total: 7m 49s	remaining: 10m 21s
4710:	learn: 0.0019697	total: 7m 49s	remaining: 8m 47s
4620:	learn: 0.0018840	total: 7m 49s	remaining: 9m 6s
4621:	learn: 0.0021318	total: 7m 49s	remaining: 9m 6s
4491:	learn: 0.0021574	total: 7m 49s	remaining: 9m 35s
4303:	learn: 0.0022387	total: 7m 49s	remaining: 10m 21s
4711:	learn: 0.0019691	total: 7m 49s	remaining: 8m 47s
4621:	learn: 0.0018840	total: 7m 49s	remaining: 9m 6s
4622:	learn: 0.0021318	total: 7m 49s	remaining: 9m 6s
4492:	learn: 0.0021566	total: 7m 49s	remaining: 9m 35s
4623:	learn: 0.0021307	total: 7m 49s	remaining: 9m 5s
4622:	learn: 0.0018840	total: 7m 49s	remaining: 9m 6s
4304:	learn: 0.0022376	total: 7m 49s	remaining: 10m 21s
4712:	learn: 0.0019687	total: 7m 49s	remaining: 8m 46s
4493:	learn: 0.0021557	total: 7m 49s	remaining: 9m 35s
4624:	learn: 0.0021300	total: 7m 49s	remaining: 9m 5s
4713:	learn: 0.0019684	total: 7m 49s	remaining: 8m 46s
4305:	learn: 0.0022370	total: 7m 49s	remaining: 10m 21s
4623:	learn: 0.0018840	total: 7m 49s	remaining: 9m 6s
4494:	learn: 0.0021547	total: 7m 49s	remaining: 9m 35s
4625:	learn: 0.0021292	total: 7m 49s	remaining: 9m 5s
4714:	learn: 0.0019677	total: 7m 49s	remaining: 8m 46s
4624:	learn: 0.0018840	total: 7m 49s	remaining: 9m 6s
4306:	learn: 0.0022359	total: 7m 49s	remaining: 10m 21s
4495:	learn: 0.0021537	total: 7m 49s	remaining: 9m 35s
4626:	learn: 0.0021282	total: 7m 49s	remaining: 9m 5s
4715:	learn: 0.0019677	total: 7m 50s	remaining: 8m 46s
4307:	learn: 0.0022353	total: 7m 50s	remaining: 10m 21s
4496:	learn: 0.0021528	total: 7m 50s	remaining: 9m 35s
4625:	learn: 0.0018840	total: 7m 50s	remaining: 9m 6s
4627:	learn: 0.0021273	total: 7m 49s	remaining: 9m 5s
4497:	learn: 0.0021522	total: 7m 50s	remaining: 9m 35s
4716:	learn: 0.0019672	total: 7m 50s	remaining: 8m 46s
4308:	learn: 0.0022345	total: 7m 50s	remaining: 10m 21s
4626:	learn: 0.0018840	total: 7m 50s	remaining: 9m 5s
4628:	learn: 0.0021270	total: 7m 50s	remaining: 9m 5s
4309:	learn: 0.0022336	total: 7m 50s	remaining: 10m 20s
4498:	learn: 0.0021522	total: 7m 50s	remaining: 9m 34s
4717:	learn: 0.0019666	total: 7m 50s	remaining: 8m 46s
4629:	learn: 0.0021261	total: 7m 50s	remaining: 9m 5s
4627:	learn: 0.0018832	total: 7m 50s	remaining: 9m 5s
4310:	learn: 0.0022329	total: 7m 50s	remaining: 10m 20s
4499:	learn: 0.0021522	total: 7m 50s	remaining: 9m 34s
4718:	learn: 0.0019657	total: 7m 50s	remaining: 8m 46s
4630:	learn: 0.0021257	total: 7m 50s	remaining: 9m 5s
4628:	learn: 0.0018832	total: 7m 50s	remaining: 9m 5s
4311:	learn: 0.0022329	total: 7m 50s	remaining: 10m 20s
4719:	learn: 0.0019650	total: 7m 50s	remaining: 8m 46s
4629:	learn: 0.0018832	total: 7m 50s	remaining: 9m 5s
4500:	learn: 0.0021522	total: 7m 50s	remaining: 9m 34s
4631:	learn: 0.0021249	total: 7m 50s	remaining: 9m 5s
4312:	learn: 0.0022318	total: 7m 50s	remaining: 10m 20s
4720:	learn: 0.0019644	total: 7m 50s	remaining: 8m 46s
4630:	learn: 0.0018832	total: 7m 50s	remaining: 9m 5s
4501:	learn: 0.0021522	total: 7m 50s	remaining: 9m 34s
4313:	learn: 0.0022311	total: 7m 50s	remaining: 10m 20s
4632:	learn: 0.0021240	total: 7m 50s	remaining: 9m 5s
4631:	learn: 0.0018832	total: 7m 50s	remaining: 9m 5s
4721:	learn: 0.0019640	total: 7m 50s	remaining: 8m 46s
4633:	learn: 0.0021231	total: 7m 50s	remaining: 9m 4s
4314:	learn: 0.0022300	total: 7m 50s	remaining: 10m 20s
4502:	learn: 0.0021522	total: 7m 50s	remaining: 9m 34s
4632:	learn: 0.0018832	total: 7m 50s	remaining: 9m 5s
4722:	learn: 0.0019635	total: 7m 50s	remaining: 8m 45s
4634:	learn: 0.0021222	total: 7m 50s	remaining: 9m 4s
4503:	learn: 0.0021513	total: 7m 50s	remaining: 9m 34s
4315:	learn: 0.0022292	total: 7m 50s	remaining: 10m 20s
4723:	learn: 0.0019628	total: 7m 50s	remaining: 8m 45s
4633:	learn: 0.0018832	total: 7m 50s	remaining: 9m 5s
4635:	learn: 0.0021222	total: 7m 50s	remaining: 9m 4s
4724:	learn: 0.0019628	total: 7m 50s	remaining: 8m 45s
4504:	learn: 0.0021513	total: 7m 50s	remaining: 9m 34s
4316:	learn: 0.0022282	total: 7m 50s	remaining: 10m 20s
4634:	learn: 0.0018832	total: 7m 50s	remaining: 9m 5s
4636:	learn: 0.0021217	total: 7m 50s	remaining: 9m 4s
4725:	learn: 0.0019621	total: 7m 50s	remaining: 8m 45s
4317:	learn: 0.0022273	total: 7m 51s	remaining: 10m 19s
4505:	learn: 0.0021513	total: 7m 51s	remaining: 9m 34s
4637:	learn: 0.0021212	total: 7m 50s	remaining: 9m 4s
4635:	learn: 0.0018832	total: 7m 51s	remaining: 9m 5s
4726:	learn: 0.0019621	total: 7m 51s	remaining: 8m 45s
4318:	learn: 0.0022264	total: 7m 51s	remaining: 10m 19s
4638:	learn: 0.0021202	total: 7m 51s	remaining: 9m 4s
4506:	learn: 0.0021508	total: 7m 51s	remaining: 9m 34s
4727:	learn: 0.0019614	total: 7m 51s	remaining: 8m 45s
4636:	learn: 0.0018832	total: 7m 51s	remaining: 9m 4s
4639:	learn: 0.0021193	total: 7m 51s	remaining: 9m 4s
4319:	learn: 0.0022256	total: 7m 51s	remaining: 10m 19s
4507:	learn: 0.0021508	total: 7m 51s	remaining: 9m 34s
4728:	learn: 0.0019608	total: 7m 51s	remaining: 8m 45s
4637:	learn: 0.0018832	total: 7m 51s	remaining: 9m 4s
4640:	learn: 0.0021188	total: 7m 51s	remaining: 9m 4s
4508:	learn: 0.0021508	total: 7m 51s	remaining: 9m 34s
4320:	learn: 0.0022252	total: 7m 51s	remaining: 10m 19s
4729:	learn: 0.0019600	total: 7m 51s	remaining: 8m 45s
4638:	learn: 0.0018832	total: 7m 51s	remaining: 9m 4s
4641:	learn: 0.0021181	total: 7m 51s	remaining: 9m 3s
4509:	learn: 0.0021508	total: 7m 51s	remaining: 9m 33s
4321:	learn: 0.0022242	total: 7m 51s	remaining: 10m 19s
4639:	learn: 0.0018832	total: 7m 51s	remaining: 9m 4s
4730:	learn: 0.0019595	total: 7m 51s	remaining: 8m 45s
4642:	learn: 0.0021174	total: 7m 51s	remaining: 9m 3s
4322:	learn: 0.0022234	total: 7m 51s	remaining: 10m 19s
4510:	learn: 0.0021508	total: 7m 51s	remaining: 9m 33s
4640:	learn: 0.0018832	total: 7m 51s	remaining: 9m 4s
4731:	learn: 0.0019588	total: 7m 51s	remaining: 8m 45s
4643:	learn: 0.0021165	total: 7m 51s	remaining: 9m 3s
4511:	learn: 0.0021497	total: 7m 51s	remaining: 9m 33s
4323:	learn: 0.0022225	total: 7m 51s	remaining: 10m 19s
4732:	learn: 0.0019583	total: 7m 51s	remaining: 8m 44s
4641:	learn: 0.0018832	total: 7m 51s	remaining: 9m 4s
4644:	learn: 0.0021157	total: 7m 51s	remaining: 9m 3s
4733:	learn: 0.0019577	total: 7m 51s	remaining: 8m 44s
4512:	learn: 0.0021497	total: 7m 51s	remaining: 9m 33s
4642:	learn: 0.0018832	total: 7m 51s	remaining: 9m 4s
4324:	learn: 0.0022218	total: 7m 51s	remaining: 10m 19s
4645:	learn: 0.0021150	total: 7m 51s	remaining: 9m 3s
4513:	learn: 0.0021497	total: 7m 51s	remaining: 9m 33s
4734:	learn: 0.0019571	total: 7m 51s	remaining: 8m 44s
4643:	learn: 0.0018832	total: 7m 51s	remaining: 9m 4s
4325:	learn: 0.0022210	total: 7m 51s	remaining: 10m 19s
4646:	learn: 0.0021140	total: 7m 51s	remaining: 9m 3s
4735:	learn: 0.0019565	total: 7m 51s	remaining: 8m 44s
4514:	learn: 0.0021497	total: 7m 51s	remaining: 9m 33s
4644:	learn: 0.0018832	total: 7m 51s	remaining: 9m 4s
4326:	learn: 0.0022206	total: 7m 52s	remaining: 10m 18s
4647:	learn: 0.0021133	total: 7m 51s	remaining: 9m 3s
4736:	learn: 0.0019561	total: 7m 52s	remaining: 8m 44s
4515:	learn: 0.0021497	total: 7m 52s	remaining: 9m 33s
4327:	learn: 0.0022197	total: 7m 52s	remaining: 10m 18s
4645:	learn: 0.0018832	total: 7m 52s	remaining: 9m 4s
4648:	learn: 0.0021125	total: 7m 52s	remaining: 9m 3s
4737:	learn: 0.0019555	total: 7m 52s	remaining: 8m 44s
4328:	learn: 0.0022188	total: 7m 52s	remaining: 10m 18s
4516:	learn: 0.0021497	total: 7m 52s	remaining: 9m 33s
4649:	learn: 0.0021117	total: 7m 52s	remaining: 9m 3s
4646:	learn: 0.0018832	total: 7m 52s	remaining: 9m 3s
4738:	learn: 0.0019550	total: 7m 52s	remaining: 8m 44s
4517:	learn: 0.0021497	total: 7m 52s	remaining: 9m 33s
4647:	learn: 0.0018832	total: 7m 52s	remaining: 9m 3s
4329:	learn: 0.0022182	total: 7m 52s	remaining: 10m 18s
4650:	learn: 0.0021112	total: 7m 52s	remaining: 9m 3s
4518:	learn: 0.0021497	total: 7m 52s	remaining: 9m 32s
4739:	learn: 0.0019542	total: 7m 52s	remaining: 8m 44s
4648:	learn: 0.0018832	total: 7m 52s	remaining: 9m 3s
4330:	learn: 0.0022182	total: 7m 52s	remaining: 10m 18s
4651:	learn: 0.0021104	total: 7m 52s	remaining: 9m 2s
4519:	learn: 0.0021497	total: 7m 52s	remaining: 9m 32s
4740:	learn: 0.0019535	total: 7m 52s	remaining: 8m 44s
4649:	learn: 0.0018832	total: 7m 52s	remaining: 9m 3s
4331:	learn: 0.0022173	total: 7m 52s	remaining: 10m 18s
4520:	learn: 0.0021497	total: 7m 52s	remaining: 9m 32s
4652:	learn: 0.0021098	total: 7m 52s	remaining: 9m 2s
4741:	learn: 0.0019528	total: 7m 52s	remaining: 8m 44s
4650:	learn: 0.0018832	total: 7m 52s	remaining: 9m 3s
4332:	learn: 0.0022163	total: 7m 52s	remaining: 10m 18s
4521:	learn: 0.0021497	total: 7m 52s	remaining: 9m 32s
4653:	learn: 0.0021093	total: 7m 52s	remaining: 9m 2s
4651:	learn: 0.0018832	total: 7m 52s	remaining: 9m 3s
4742:	learn: 0.0019520	total: 7m 52s	remaining: 8m 43s
4654:	learn: 0.0021088	total: 7m 52s	remaining: 9m 2s
4333:	learn: 0.0022155	total: 7m 52s	remaining: 10m 18s
4522:	learn: 0.0021497	total: 7m 52s	remaining: 9m 32s
4652:	learn: 0.0018832	total: 7m 52s	remaining: 9m 3s
4743:	learn: 0.0019520	total: 7m 52s	remaining: 8m 43s
4523:	learn: 0.0021497	total: 7m 52s	remaining: 9m 32s
4655:	learn: 0.0021080	total: 7m 52s	remaining: 9m 2s
4334:	learn: 0.0022148	total: 7m 52s	remaining: 10m 18s
4653:	learn: 0.0018832	total: 7m 52s	remaining: 9m 3s
4744:	learn: 0.0019520	total: 7m 52s	remaining: 8m 43s
4524:	learn: 0.0021497	total: 7m 52s	remaining: 9m 32s
4656:	learn: 0.0021073	total: 7m 52s	remaining: 9m 2s
4654:	learn: 0.0018825	total: 7m 52s	remaining: 9m 3s
4335:	learn: 0.0022141	total: 7m 53s	remaining: 10m 17s
4745:	learn: 0.0019520	total: 7m 52s	remaining: 8m 43s
4525:	learn: 0.0021497	total: 7m 53s	remaining: 9m 32s
4657:	learn: 0.0021064	total: 7m 52s	remaining: 9m 2s
4655:	learn: 0.0018818	total: 7m 53s	remaining: 9m 2s
4336:	learn: 0.0022132	total: 7m 53s	remaining: 10m 17s
4526:	learn: 0.0021497	total: 7m 53s	remaining: 9m 31s
4746:	learn: 0.0019520	total: 7m 53s	remaining: 8m 43s
4658:	learn: 0.0021060	total: 7m 52s	remaining: 9m 2s
4656:	learn: 0.0018818	total: 7m 53s	remaining: 9m 2s
4527:	learn: 0.0021497	total: 7m 53s	remaining: 9m 31s
4337:	learn: 0.0022122	total: 7m 53s	remaining: 10m 17s
4659:	learn: 0.0021051	total: 7m 53s	remaining: 9m 2s
4747:	learn: 0.0019515	total: 7m 53s	remaining: 8m 43s
4657:	learn: 0.0018818	total: 7m 53s	remaining: 9m 2s
4660:	learn: 0.0021043	total: 7m 53s	remaining: 9m 1s
4748:	learn: 0.0019507	total: 7m 53s	remaining: 8m 43s
4338:	learn: 0.0022111	total: 7m 53s	remaining: 10m 17s
4528:	learn: 0.0021497	total: 7m 53s	remaining: 9m 31s
4661:	learn: 0.0021034	total: 7m 53s	remaining: 9m 1s
4658:	learn: 0.0018818	total: 7m 53s	remaining: 9m 2s
4749:	learn: 0.0019507	total: 7m 53s	remaining: 8m 43s
4529:	learn: 0.0021497	total: 7m 53s	remaining: 9m 31s
4339:	learn: 0.0022105	total: 7m 53s	remaining: 10m 17s
4662:	learn: 0.0021027	total: 7m 53s	remaining: 9m 1s
4659:	learn: 0.0018818	total: 7m 53s	remaining: 9m 2s
4750:	learn: 0.0019507	total: 7m 53s	remaining: 8m 43s
4530:	learn: 0.0021493	total: 7m 53s	remaining: 9m 31s
4660:	learn: 0.0018818	total: 7m 53s	remaining: 9m 2s
4340:	learn: 0.0022099	total: 7m 53s	remaining: 10m 17s
4663:	learn: 0.0021021	total: 7m 53s	remaining: 9m 1s
4751:	learn: 0.0019501	total: 7m 53s	remaining: 8m 43s
4531:	learn: 0.0021493	total: 7m 53s	remaining: 9m 31s
4752:	learn: 0.0019501	total: 7m 53s	remaining: 8m 42s
4664:	learn: 0.0021017	total: 7m 53s	remaining: 9m 1s
4341:	learn: 0.0022090	total: 7m 53s	remaining: 10m 17s
4661:	learn: 0.0018818	total: 7m 53s	remaining: 9m 2s
4532:	learn: 0.0021493	total: 7m 53s	remaining: 9m 31s
4662:	learn: 0.0018818	total: 7m 53s	remaining: 9m 2s
4753:	learn: 0.0019501	total: 7m 53s	remaining: 8m 42s
4665:	learn: 0.0021009	total: 7m 53s	remaining: 9m 1s

4342:	learn: 0.0022080	total: 7m 53s	remaining: 10m 17s
4533:	learn: 0.0021493	total: 7m 53s	remaining: 9m 31s
4754:	learn: 0.0019494	total: 7m 53s	remaining: 8m 42s
4663:	learn: 0.0018816	total: 7m 53s	remaining: 9m 2s
4666:	learn: 0.0021001	total: 7m 53s	remaining: 9m 1s
4534:	learn: 0.0021493	total: 7m 53s	remaining: 9m 31s
4343:	learn: 0.0022075	total: 7m 53s	remaining: 10m 17s
4755:	learn: 0.0019488	total: 7m 53s	remaining: 8m 42s
4664:	learn: 0.0018816	total: 7m 53s	remaining: 9m 2s
4667:	learn: 0.0020995	total: 7m 53s	remaining: 9m 1s
4535:	learn: 0.0021488	total: 7m 54s	remaining: 9m 30s
4344:	learn: 0.0022066	total: 7m 54s	remaining: 10m 16s
4756:	learn: 0.0019481	total: 7m 54s	remaining: 8m 42s
4665:	learn: 0.0018816	total: 7m 54s	remaining: 9m 1s
4668:	learn: 0.0020988	total: 7m 53s	remaining: 9m 1s
4536:	learn: 0.0021482	total: 7m 54s	remaining: 9m 30s
4345:	learn: 0.0022058	total: 7m 54s	remaining: 10m 16s
4757:	learn: 0.0019481	total: 7m 54s	remaining: 8m 42s
4666:	learn: 0.0018816	total: 7m 54s	remaining: 9m 1s
4669:	learn: 0.0020979	total: 7m 54s	remaining: 9m 1s
4537:	learn: 0.0021482	total: 7m 54s	remaining: 9m 30s
4667:	learn: 0.0018816	total: 7m 54s	remaining: 9m 1s
4758:	learn: 0.0019481	total: 7m 54s	remaining: 8m 42s
4346:	learn: 0.0022049	total: 7m 54s	remaining: 10m 16s
4670:	learn: 0.0020972	total: 7m 54s	remaining: 9m
4668:	learn: 0.0018816	total: 7m 54s	remaining: 9m 1s
4538:	learn: 0.0021482	total: 7m 54s	remaining: 9m 30s
4347:	learn: 0.0022038	total: 7m 54s	remaining: 10m 16s
4759:	learn: 0.0019475	total: 7m 54s	remaining: 8m 42s
4671:	learn: 0.0020965	total: 7m 54s	remaining: 9m
4348:	learn: 0.0022029	total: 7m 54s	remaining: 10m 16s
4539:	learn: 0.0021482	total: 7m 54s	remaining: 9m 30s
4669:	learn: 0.0018816	total: 7m 54s	remaining: 9m 1s
4760:	learn: 0.0019470	total: 7m 54s	remaining: 8m 42s
4672:	learn: 0.0020955	total: 7m 54s	remaining: 9m
4349:	learn: 0.0022022	total: 7m 54s	remaining: 10m 16s
4670:	learn: 0.0018816	total: 7m 54s	remaining: 9m 1s
4540:	learn: 0.0021482	total: 7m 54s	remaining: 9m 30s
4761:	learn: 0.0019463	total: 7m 54s	remaining: 8m 41s
4673:	learn: 0.0020951	total: 7m 54s	remaining: 9m
4350:	learn: 0.0022022	total: 7m 54s	remaining: 10m 16s
4671:	learn: 0.0018816	total: 7m 54s	remaining: 9m 1s
4762:	learn: 0.0019463	total: 7m 54s	remaining: 8m 41s
4541:	learn: 0.0021482	total: 7m 54s	remaining: 9m 30s
4674:	learn: 0.0020943	total: 7m 54s	remaining: 9m
4351:	learn: 0.0022018	total: 7m 54s	remaining: 10m 16s
4672:	learn: 0.0018816	total: 7m 54s	remaining: 9m 1s
4763:	learn: 0.0019456	total: 7m 54s	remaining: 8m 41s
4675:	learn: 0.0020943	total: 7m 54s	remaining: 9m
4542:	learn: 0.0021481	total: 7m 54s	remaining: 9m 30s
4352:	learn: 0.0022008	total: 7m 54s	remaining: 10m 16s
4673:	learn: 0.0018816	total: 7m 54s	remaining: 9m 1s
4676:	learn: 0.0020943	total: 7m 54s	remaining: 9m
4764:	learn: 0.0019450	total: 7m 54s	remaining: 8m 41s
4543:	learn: 0.0021477	total: 7m 54s	remaining: 9m 30s
4674:	learn: 0.0018816	total: 7m 54s	remaining: 9m
4353:	learn: 0.0022000	total: 7m 54s	remaining: 10m 15s
4677:	learn: 0.0020932	total: 7m 54s	remaining: 9m
4765:	learn: 0.0019450	total: 7m 54s	remaining: 8m 41s
4544:	learn: 0.0021471	total: 7m 55s	remaining: 9m 30s
4675:	learn: 0.0018816	total: 7m 55s	remaining: 9m
4354:	learn: 0.0021994	total: 7m 55s	remaining: 10m 15s
4678:	learn: 0.0020923	total: 7m 54s	remaining: 9m
4766:	learn: 0.0019443	total: 7m 55s	remaining: 8m 41s
4676:	learn: 0.0018816	total: 7m 55s	remaining: 9m
4355:	learn: 0.0021985	total: 7m 55s	remaining: 10m 15s
4679:	learn: 0.0020917	total: 7m 55s	remaining: 8m 59s
4545:	learn: 0.0021462	total: 7m 55s	remaining: 9m 30s
4767:	learn: 0.0019438	total: 7m 55s	remaining: 8m 41s
4677:	learn: 0.0018815	total: 7m 55s	remaining: 9m
4356:	learn: 0.0021977	total: 7m 55s	remaining: 10m 15s
4680:	learn: 0.0020908	total: 7m 55s	remaining: 8m 59s
4546:	learn: 0.0021462	total: 7m 55s	remaining: 9m 29s
4768:	learn: 0.0019431	total: 7m 55s	remaining: 8m 41s
4678:	learn: 0.0018816	total: 7m 55s	remaining: 9m
4681:	learn: 0.0020902	total: 7m 55s	remaining: 8m 59s
4357:	learn: 0.0021970	total: 7m 55s	remaining: 10m 15s
4547:	learn: 0.0021462	total: 7m 55s	remaining: 9m 29s
4769:	learn: 0.0019426	total: 7m 55s	remaining: 8m 41s
4679:	learn: 0.0018816	total: 7m 55s	remaining: 9m
4682:	learn: 0.0020894	total: 7m 55s	remaining: 8m 59s
4548:	learn: 0.0021462	total: 7m 55s	remaining: 9m 29s
4770:	learn: 0.0019423	total: 7m 55s	remaining: 8m 41s
4358:	learn: 0.0021964	total: 7m 55s	remaining: 10m 15s
4680:	learn: 0.0018816	total: 7m 55s	remaining: 9m
4683:	learn: 0.0020886	total: 7m 55s	remaining: 8m 59s
4549:	learn: 0.0021462	total: 7m 55s	remaining: 9m 29s
4359:	learn: 0.0021957	total: 7m 55s	remaining: 10m 15s
4771:	learn: 0.0019416	total: 7m 55s	remaining: 8m 41s
4681:	learn: 0.0018816	total: 7m 55s	remaining: 9m
4684:	learn: 0.0020878	total: 7m 55s	remaining: 8m 59s
4772:	learn: 0.0019410	total: 7m 55s	remaining: 8m 40s
4550:	learn: 0.0021462	total: 7m 55s	remaining: 9m 29s
4360:	learn: 0.0021947	total: 7m 55s	remaining: 10m 15s
4682:	learn: 0.0018814	total: 7m 55s	remaining: 9m
4685:	learn: 0.0020870	total: 7m 55s	remaining: 8m 59s
4773:	learn: 0.0019403	total: 7m 55s	remaining: 8m 40s
4551:	learn: 0.0021454	total: 7m 55s	remaining: 9m 29s
4686:	learn: 0.0020861	total: 7m 55s	remaining: 8m 59s
4683:	learn: 0.0018814	total: 7m 55s	remaining: 8m 59s
4361:	learn: 0.0021937	total: 7m 55s	remaining: 10m 15s
4774:	learn: 0.0019403	total: 7m 55s	remaining: 8m 40s
4687:	learn: 0.0020853	total: 7m 55s	remaining: 8m 59s
4684:	learn: 0.0018814	total: 7m 55s	remaining: 8m 59s
4552:	learn: 0.0021450	total: 7m 55s	remaining: 9m 29s
4362:	learn: 0.0021927	total: 7m 55s	remaining: 10m 14s
4775:	learn: 0.0019403	total: 7m 55s	remaining: 8m 40s
4685:	learn: 0.0018814	total: 7m 55s	remaining: 8m 59s
4688:	learn: 0.0020846	total: 7m 55s	remaining: 8m 58s
4553:	learn: 0.0021450	total: 7m 56s	remaining: 9m 29s
4776:	learn: 0.0019397	total: 7m 56s	remaining: 8m 40s
4686:	learn: 0.0018814	total: 7m 56s	remaining: 8m 59s
4363:	learn: 0.0021924	total: 7m 56s	remaining: 10m 14s
4689:	learn: 0.0020838	total: 7m 55s	remaining: 8m 58s
4777:	learn: 0.0019394	total: 7m 56s	remaining: 8m 40s
4687:	learn: 0.0018814	total: 7m 56s	remaining: 8m 59s
4554:	learn: 0.0021444	total: 7m 56s	remaining: 9m 29s
4364:	learn: 0.0021916	total: 7m 56s	remaining: 10m 14s
4690:	learn: 0.0020833	total: 7m 56s	remaining: 8m 58s
4778:	learn: 0.0019393	total: 7m 56s	remaining: 8m 40s
4688:	learn: 0.0018814	total: 7m 56s	remaining: 8m 59s
4555:	learn: 0.0021444	total: 7m 56s	remaining: 9m 29s
4779:	learn: 0.0019387	total: 7m 56s	remaining: 8m 40s
4691:	learn: 0.0020826	total: 7m 56s	remaining: 8m 58s
4365:	learn: 0.0021904	total: 7m 56s	remaining: 10m 14s
4689:	learn: 0.0018814	total: 7m 56s	remaining: 8m 59s
4556:	learn: 0.0021444	total: 7m 56s	remaining: 9m 28s
4780:	learn: 0.0019381	total: 7m 56s	remaining: 8m 40s
4692:	learn: 0.0020817	total: 7m 56s	remaining: 8m 58s
4366:	learn: 0.0021898	total: 7m 56s	remaining: 10m 14s
4690:	learn: 0.0018814	total: 7m 56s	remaining: 8m 59s
4781:	learn: 0.0019375	total: 7m 56s	remaining: 8m 39s
4557:	learn: 0.0021444	total: 7m 56s	remaining: 9m 28s
4693:	learn: 0.0020809	total: 7m 56s	remaining: 8m 58s
4782:	learn: 0.0019375	total: 7m 56s	remaining: 8m 39s
4691:	learn: 0.0018814	total: 7m 56s	remaining: 8m 59s
4367:	learn: 0.0021893	total: 7m 56s	remaining: 10m 14s
4558:	learn: 0.0021444	total: 7m 56s	remaining: 9m 28s
4694:	learn: 0.0020802	total: 7m 56s	remaining: 8m 58s
4783:	learn: 0.0019368	total: 7m 56s	remaining: 8m 39s
4692:	learn: 0.0018814	total: 7m 56s	remaining: 8m 58s
4368:	learn: 0.0021889	total: 7m 56s	remaining: 10m 14s
4559:	learn: 0.0021444	total: 7m 56s	remaining: 9m 28s
4695:	learn: 0.0020794	total: 7m 56s	remaining: 8m 58s
4784:	learn: 0.0019362	total: 7m 56s	remaining: 8m 39s
4693:	learn: 0.0018814	total: 7m 56s	remaining: 8m 58s
4560:	learn: 0.0021444	total: 7m 56s	remaining: 9m 28s
4369:	learn: 0.0021881	total: 7m 56s	remaining: 10m 14s
4696:	learn: 0.0020786	total: 7m 56s	remaining: 8m 58s
4785:	learn: 0.0019354	total: 7m 56s	remaining: 8m 39s
4694:	learn: 0.0018814	total: 7m 56s	remaining: 8m 58s
4561:	learn: 0.0021444	total: 7m 56s	remaining: 9m 28s
4786:	learn: 0.0019355	total: 7m 56s	remaining: 8m 39s
4370:	learn: 0.0021873	total: 7m 56s	remaining: 10m 14s
4697:	learn: 0.0020779	total: 7m 56s	remaining: 8m 58s
4695:	learn: 0.0018812	total: 7m 56s	remaining: 8m 58s
4562:	learn: 0.0021444	total: 7m 56s	remaining: 9m 28s
4698:	learn: 0.0020770	total: 7m 56s	remaining: 8m 57s
4787:	learn: 0.0019348	total: 7m 56s	remaining: 8m 39s
4696:	learn: 0.0018812	total: 7m 57s	remaining: 8m 58s
4563:	learn: 0.0021444	total: 7m 57s	remaining: 9m 28s
4371:	learn: 0.0021865	total: 7m 57s	remaining: 10m 14s
4699:	learn: 0.0020770	total: 7m 56s	remaining: 8m 57s
4697:	learn: 0.0018812	total: 7m 57s	remaining: 8m 58s
4788:	learn: 0.0019348	total: 7m 57s	remaining: 8m 39s
4372:	learn: 0.0021857	total: 7m 57s	remaining: 10m 14s
4564:	learn: 0.0021444	total: 7m 57s	remaining: 9m 28s
4698:	learn: 0.0018812	total: 7m 57s	remaining: 8m 58s
4700:	learn: 0.0020762	total: 7m 57s	remaining: 8m 57s
4789:	learn: 0.0019340	total: 7m 57s	remaining: 8m 39s
4373:	learn: 0.0021847	total: 7m 57s	remaining: 10m 13s
4699:	learn: 0.0018812	total: 7m 57s	remaining: 8m 58s
4565:	learn: 0.0021435	total: 7m 57s	remaining: 9m 28s
4790:	learn: 0.0019335	total: 7m 57s	remaining: 8m 38s
4701:	learn: 0.0020755	total: 7m 57s	remaining: 8m 57s
4374:	learn: 0.0021848	total: 7m 57s	remaining: 10m 13s
4700:	learn: 0.0018812	total: 7m 57s	remaining: 8m 58s
4702:	learn: 0.0020751	total: 7m 57s	remaining: 8m 57s
4566:	learn: 0.0021435	total: 7m 57s	remaining: 9m 27s
4791:	learn: 0.0019328	total: 7m 57s	remaining: 8m 38s
4701:	learn: 0.0018812	total: 7m 57s	remaining: 8m 57s
4375:	learn: 0.0021840	total: 7m 57s	remaining: 10m 13s
4703:	learn: 0.0020744	total: 7m 57s	remaining: 8m 57s
4567:	learn: 0.0021435	total: 7m 57s	remaining: 9m 27s
4702:	learn: 0.0018812	total: 7m 57s	remaining: 8m 57s
4792:	learn: 0.0019327	total: 7m 57s	remaining: 8m 38s
4376:	learn: 0.0021833	total: 7m 57s	remaining: 10m 13s
4704:	learn: 0.0020737	total: 7m 57s	remaining: 8m 57s
4793:	learn: 0.0019327	total: 7m 57s	remaining: 8m 38s
4703:	learn: 0.0018803	total: 7m 57s	remaining: 8m 57s
4568:	learn: 0.0021435	total: 7m 57s	remaining: 9m 27s
4377:	learn: 0.0021824	total: 7m 57s	remaining: 10m 13s
4704:	learn: 0.0018799	total: 7m 57s	remaining: 8m 57s
4705:	learn: 0.0020730	total: 7m 57s	remaining: 8m 57s
4794:	learn: 0.0019320	total: 7m 57s	remaining: 8m 38s
4705:	learn: 0.0018790	total: 7m 57s	remaining: 8m 57s
4569:	learn: 0.0021435	total: 7m 57s	remaining: 9m 27s
4706:	learn: 0.0020726	total: 7m 57s	remaining: 8m 57s
4378:	learn: 0.0021821	total: 7m 57s	remaining: 10m 13s
4795:	learn: 0.0019320	total: 7m 57s	remaining: 8m 38s
4706:	learn: 0.0018790	total: 7m 57s	remaining: 8m 57s
4570:	learn: 0.0021430	total: 7m 57s	remaining: 9m 27s
4707:	learn: 0.0020726	total: 7m 57s	remaining: 8m 57s
4379:	learn: 0.0021816	total: 7m 57s	remaining: 10m 13s
4796:	learn: 0.0019314	total: 7m 57s	remaining: 8m 38s
4707:	learn: 0.0018790	total: 7m 57s	remaining: 8m 57s
4571:	learn: 0.0021430	total: 7m 57s	remaining: 9m 27s
4708:	learn: 0.0020719	total: 7m 57s	remaining: 8m 56s
4380:	learn: 0.0021811	total: 7m 58s	remaining: 10m 13s
4708:	learn: 0.0018790	total: 7m 58s	remaining: 8m 57s
4797:	learn: 0.0019314	total: 7m 58s	remaining: 8m 38s
4572:	learn: 0.0021423	total: 7m 58s	remaining: 9m 27s
4709:	learn: 0.0020712	total: 7m 57s	remaining: 8m 56s
4381:	learn: 0.0021811	total: 7m 58s	remaining: 10m 12s
4709:	learn: 0.0018790	total: 7m 58s	remaining: 8m 56s
4798:	learn: 0.0019308	total: 7m 58s	remaining: 8m 38s
4573:	learn: 0.0021423	total: 7m 58s	remaining: 9m 27s
4710:	learn: 0.0020702	total: 7m 58s	remaining: 8m 56s
4710:	learn: 0.0018790	total: 7m 58s	remaining: 8m 56s
4799:	learn: 0.0019308	total: 7m 58s	remaining: 8m 38s
4382:	learn: 0.0021803	total: 7m 58s	remaining: 10m 12s
4574:	learn: 0.0021418	total: 7m 58s	remaining: 9m 27s
4711:	learn: 0.0020696	total: 7m 58s	remaining: 8m 56s
4711:	learn: 0.0018790	total: 7m 58s	remaining: 8m 56s
4800:	learn: 0.0019301	total: 7m 58s	remaining: 8m 37s
4383:	learn: 0.0021793	total: 7m 58s	remaining: 10m 12s
4575:	learn: 0.0021418	total: 7m 58s	remaining: 9m 27s
4712:	learn: 0.0018790	total: 7m 58s	remaining: 8m 56s
4712:	learn: 0.0020686	total: 7m 58s	remaining: 8m 56s
4384:	learn: 0.0021787	total: 7m 58s	remaining: 10m 12s
4801:	learn: 0.0019296	total: 7m 58s	remaining: 8m 37s
4576:	learn: 0.0021418	total: 7m 58s	remaining: 9m 26s
4713:	learn: 0.0018790	total: 7m 58s	remaining: 8m 56s
4713:	learn: 0.0020679	total: 7m 58s	remaining: 8m 56s
4802:	learn: 0.0019296	total: 7m 58s	remaining: 8m 37s
4385:	learn: 0.0021781	total: 7m 58s	remaining: 10m 12s
4577:	learn: 0.0021418	total: 7m 58s	remaining: 9m 26s
4714:	learn: 0.0020672	total: 7m 58s	remaining: 8m 56s
4714:	learn: 0.0018790	total: 7m 58s	remaining: 8m 56s
4803:	learn: 0.0019294	total: 7m 58s	remaining: 8m 37s
4578:	learn: 0.0021418	total: 7m 58s	remaining: 9m 26s
4386:	learn: 0.0021776	total: 7m 58s	remaining: 10m 12s
4715:	learn: 0.0020667	total: 7m 58s	remaining: 8m 56s
4804:	learn: 0.0019294	total: 7m 58s	remaining: 8m 37s
4715:	learn: 0.0018790	total: 7m 58s	remaining: 8m 56s
4387:	learn: 0.0021769	total: 7m 58s	remaining: 10m 12s
4716:	learn: 0.0020663	total: 7m 58s	remaining: 8m 56s
4579:	learn: 0.0021418	total: 7m 58s	remaining: 9m 26s
4805:	learn: 0.0019287	total: 7m 58s	remaining: 8m 37s
4388:	learn: 0.0021760	total: 7m 58s	remaining: 10m 12s
4717:	learn: 0.0020658	total: 7m 58s	remaining: 8m 55s
4716:	learn: 0.0018790	total: 7m 58s	remaining: 8m 56s
4580:	learn: 0.0021413	total: 7m 58s	remaining: 9m 26s
4806:	learn: 0.0019286	total: 7m 58s	remaining: 8m 37s
4389:	learn: 0.0021753	total: 7m 58s	remaining: 10m 12s
4718:	learn: 0.0020653	total: 7m 58s	remaining: 8m 55s
4581:	learn: 0.0021413	total: 7m 58s	remaining: 9m 26s
4717:	learn: 0.0018790	total: 7m 58s	remaining: 8m 56s
4807:	learn: 0.0019281	total: 7m 58s	remaining: 8m 37s
4390:	learn: 0.0021745	total: 7m 59s	remaining: 10m 11s
4582:	learn: 0.0021413	total: 7m 59s	remaining: 9m 26s
4719:	learn: 0.0020647	total: 7m 58s	remaining: 8m 55s
4718:	learn: 0.0018790	total: 7m 59s	remaining: 8m 56s
4808:	learn: 0.0019274	total: 7m 59s	remaining: 8m 37s
4720:	learn: 0.0020644	total: 7m 59s	remaining: 8m 55s
4719:	learn: 0.0018790	total: 7m 59s	remaining: 8m 55s
4583:	learn: 0.0021413	total: 7m 59s	remaining: 9m 26s
4391:	learn: 0.0021741	total: 7m 59s	remaining: 10m 11s
4809:	learn: 0.0019269	total: 7m 59s	remaining: 8m 37s
4721:	learn: 0.0020639	total: 7m 59s	remaining: 8m 55s
4720:	learn: 0.0018790	total: 7m 59s	remaining: 8m 55s
4392:	learn: 0.0021731	total: 7m 59s	remaining: 10m 11s
4584:	learn: 0.0021408	total: 7m 59s	remaining: 9m 26s
4721:	learn: 0.0018790	total: 7m 59s	remaining: 8m 55s
4810:	learn: 0.0019264	total: 7m 59s	remaining: 8m 36s
4722:	learn: 0.0020631	total: 7m 59s	remaining: 8m 55s
4722:	learn: 0.0018790	total: 7m 59s	remaining: 8m 55s
4393:	learn: 0.0021721	total: 7m 59s	remaining: 10m 11s
4585:	learn: 0.0021400	total: 7m 59s	remaining: 9m 25s
4723:	learn: 0.0020624	total: 7m 59s	remaining: 8m 55s
4811:	learn: 0.0019259	total: 7m 59s	remaining: 8m 36s
4394:	learn: 0.0021714	total: 7m 59s	remaining: 10m 11s
4723:	learn: 0.0018790	total: 7m 59s	remaining: 8m 55s
4724:	learn: 0.0020617	total: 7m 59s	remaining: 8m 55s
4586:	learn: 0.0021391	total: 7m 59s	remaining: 9m 25s
4812:	learn: 0.0019258	total: 7m 59s	remaining: 8m 36s
4395:	learn: 0.0021714	total: 7m 59s	remaining: 10m 11s
4724:	learn: 0.0018790	total: 7m 59s	remaining: 8m 55s
4725:	learn: 0.0020611	total: 7m 59s	remaining: 8m 55s
4587:	learn: 0.0021391	total: 7m 59s	remaining: 9m 25s
4725:	learn: 0.0018790	total: 7m 59s	remaining: 8m 55s
4396:	learn: 0.0021708	total: 7m 59s	remaining: 10m 11s
4813:	learn: 0.0019254	total: 7m 59s	remaining: 8m 36s
4726:	learn: 0.0020604	total: 7m 59s	remaining: 8m 54s
4726:	learn: 0.0018790	total: 7m 59s	remaining: 8m 55s
4588:	learn: 0.0021391	total: 7m 59s	remaining: 9m 25s
4814:	learn: 0.0019252	total: 7m 59s	remaining: 8m 36s
4397:	learn: 0.0021699	total: 7m 59s	remaining: 10m 11s

4727:	learn: 0.0020596	total: 7m 59s	remaining: 8m 54s
4589:	learn: 0.0021391	total: 7m 59s	remaining: 9m 25s
4815:	learn: 0.0019245	total: 7m 59s	remaining: 8m 36s
4398:	learn: 0.0021691	total: 7m 59s	remaining: 10m 11s
4728:	learn: 0.0018790	total: 7m 59s	remaining: 8m 54s
4590:	learn: 0.0021382	total: 7m 59s	remaining: 9m 25s
4399:	learn: 0.0021683	total: 7m 59s	remaining: 10m 10s
4728:	learn: 0.0020596	total: 7m 59s	remaining: 8m 54s
4816:	learn: 0.0019240	total: 7m 59s	remaining: 8m 36s
4729:	learn: 0.0018790	total: 7m 59s	remaining: 8m 54s
4591:	learn: 0.0021382	total: 8m	remaining: 9m 25s
4400:	learn: 0.0021675	total: 8m	remaining: 10m 10s
4729:	learn: 0.0020589	total: 7m 59s	remaining: 8m 54s
4730:	learn: 0.0018790	total: 8m	remaining: 8m 54s
4817:	learn: 0.0019233	total: 8m	remaining: 8m 36s
4401:	learn: 0.0021668	total: 8m	remaining: 10m 10s
4592:	learn: 0.0021382	total: 8m	remaining: 9m 25s
4818:	learn: 0.0019227	total: 8m	remaining: 8m 36s
4731:	learn: 0.0018781	total: 8m	remaining: 8m 54s
4730:	learn: 0.0020587	total: 8m	remaining: 8m 54s
4402:	learn: 0.0021664	total: 8m	remaining: 10m 10s
4593:	learn: 0.0021382	total: 8m	remaining: 9m 25s
4819:	learn: 0.0019227	total: 8m	remaining: 8m 36s
4732:	learn: 0.0018774	total: 8m	remaining: 8m 54s
4731:	learn: 0.0020583	total: 8m	remaining: 8m 54s
4594:	learn: 0.0021377	total: 8m	remaining: 9m 25s
4733:	learn: 0.0018771	total: 8m	remaining: 8m 54s
4732:	learn: 0.0020574	total: 8m	remaining: 8m 54s
4403:	learn: 0.0021659	total: 8m	remaining: 10m 10s
4820:	learn: 0.0019227	total: 8m	remaining: 8m 36s
4595:	learn: 0.0021377	total: 8m	remaining: 9m 24s
4734:	learn: 0.0018770	total: 8m	remaining: 8m 54s
4733:	learn: 0.0020565	total: 8m	remaining: 8m 54s
4404:	learn: 0.0021653	total: 8m	remaining: 10m 10s
4821:	learn: 0.0019222	total: 8m	remaining: 8m 35s
4596:	learn: 0.0021377	total: 8m	remaining: 9m 24s
4734:	learn: 0.0020565	total: 8m	remaining: 8m 54s
4735:	learn: 0.0018767	total: 8m	remaining: 8m 54s
4822:	learn: 0.0019222	total: 8m	remaining: 8m 35s
4405:	learn: 0.0021653	total: 8m	remaining: 10m 10s
4735:	learn: 0.0020556	total: 8m	remaining: 8m 54s
4597:	learn: 0.0021370	total: 8m	remaining: 9m 24s
4736:	learn: 0.0018767	total: 8m	remaining: 8m 54s
4823:	learn: 0.0019222	total: 8m	remaining: 8m 35s
4406:	learn: 0.0021646	total: 8m	remaining: 10m 10s
4736:	learn: 0.0020548	total: 8m	remaining: 8m 53s
4737:	learn: 0.0018767	total: 8m	remaining: 8m 53s
4598:	learn: 0.0021370	total: 8m	remaining: 9m 24s
4824:	learn: 0.0019215	total: 8m	remaining: 8m 35s
4407:	learn: 0.0021639	total: 8m	remaining: 10m 9s
4737:	learn: 0.0020542	total: 8m	remaining: 8m 53s
4738:	learn: 0.0018767	total: 8m	remaining: 8m 53s
4599:	learn: 0.0021370	total: 8m	remaining: 9m 24s
4825:	learn: 0.0019215	total: 8m	remaining: 8m 35s
4408:	learn: 0.0021635	total: 8m	remaining: 10m 9s
4739:	learn: 0.0018767	total: 8m	remaining: 8m 53s
4600:	learn: 0.0021370	total: 8m	remaining: 9m 24s
4826:	learn: 0.0019208	total: 8m	remaining: 8m 35s
4738:	learn: 0.0020535	total: 8m	remaining: 8m 53s
4409:	learn: 0.0021629	total: 8m 1s	remaining: 10m 9s
4740:	learn: 0.0018767	total: 8m 1s	remaining: 8m 53s
4827:	learn: 0.0019201	total: 8m 1s	remaining: 8m 35s
4601:	learn: 0.0021370	total: 8m 1s	remaining: 9m 24s
4741:	learn: 0.0018767	total: 8m 1s	remaining: 8m 53s
4739:	learn: 0.0020530	total: 8m	remaining: 8m 53s
4410:	learn: 0.0021620	total: 8m 1s	remaining: 10m 9s
4828:	learn: 0.0019201	total: 8m 1s	remaining: 8m 35s
4602:	learn: 0.0021370	total: 8m 1s	remaining: 9m 24s
4740:	learn: 0.0020524	total: 8m 1s	remaining: 8m 53s
4742:	learn: 0.0018767	total: 8m 1s	remaining: 8m 53s
4411:	learn: 0.0021615	total: 8m 1s	remaining: 10m 9s
4829:	learn: 0.0019194	total: 8m 1s	remaining: 8m 35s
4743:	learn: 0.0018767	total: 8m 1s	remaining: 8m 53s
4741:	learn: 0.0020524	total: 8m 1s	remaining: 8m 53s
4603:	learn: 0.0021370	total: 8m 1s	remaining: 9m 24s
4412:	learn: 0.0021607	total: 8m 1s	remaining: 10m 9s
4830:	learn: 0.0019194	total: 8m 1s	remaining: 8m 35s
4742:	learn: 0.0020517	total: 8m 1s	remaining: 8m 53s
4744:	learn: 0.0018767	total: 8m 1s	remaining: 8m 53s
4604:	learn: 0.0021370	total: 8m 1s	remaining: 9m 23s
4831:	learn: 0.0019194	total: 8m 1s	remaining: 8m 34s
4413:	learn: 0.0021607	total: 8m 1s	remaining: 10m 9s
4743:	learn: 0.0020506	total: 8m 1s	remaining: 8m 53s
4605:	learn: 0.0021370	total: 8m 1s	remaining: 9m 23s
4745:	learn: 0.0018767	total: 8m 1s	remaining: 8m 53s
4832:	learn: 0.0019194	total: 8m 1s	remaining: 8m 34s
4414:	learn: 0.0021603	total: 8m 1s	remaining: 10m 9s
4744:	learn: 0.0020499	total: 8m 1s	remaining: 8m 53s
4606:	learn: 0.0021362	total: 8m 1s	remaining: 9m 23s
4746:	learn: 0.0018761	total: 8m 1s	remaining: 8m 52s
4833:	learn: 0.0019187	total: 8m 1s	remaining: 8m 34s
4415:	learn: 0.0021594	total: 8m 1s	remaining: 10m 9s
4745:	learn: 0.0020499	total: 8m 1s	remaining: 8m 53s
4834:	learn: 0.0019180	total: 8m 1s	remaining: 8m 34s
4607:	learn: 0.0021362	total: 8m 1s	remaining: 9m 23s
4747:	learn: 0.0018756	total: 8m 1s	remaining: 8m 52s
4416:	learn: 0.0021585	total: 8m 1s	remaining: 10m 8s
4746:	learn: 0.0020499	total: 8m 1s	remaining: 8m 52s
4835:	learn: 0.0019174	total: 8m 1s	remaining: 8m 34s
4608:	learn: 0.0021357	total: 8m 1s	remaining: 9m 23s
4748:	learn: 0.0018752	total: 8m 1s	remaining: 8m 52s
4417:	learn: 0.0021577	total: 8m 1s	remaining: 10m 8s
4747:	learn: 0.0020492	total: 8m 1s	remaining: 8m 52s
4609:	learn: 0.0021357	total: 8m 1s	remaining: 9m 23s
4836:	learn: 0.0019168	total: 8m 1s	remaining: 8m 34s
4418:	learn: 0.0021569	total: 8m 1s	remaining: 10m 8s
4749:	learn: 0.0018752	total: 8m 1s	remaining: 8m 52s
4610:	learn: 0.0021357	total: 8m 1s	remaining: 9m 23s
4837:	learn: 0.0019168	total: 8m 1s	remaining: 8m 34s
4748:	learn: 0.0020484	total: 8m 1s	remaining: 8m 52s
4419:	learn: 0.0021563	total: 8m 2s	remaining: 10m 8s
4750:	learn: 0.0018752	total: 8m 2s	remaining: 8m 52s
4749:	learn: 0.0020479	total: 8m 1s	remaining: 8m 52s
4611:	learn: 0.0021357	total: 8m 2s	remaining: 9m 23s
4838:	learn: 0.0019168	total: 8m 2s	remaining: 8m 34s
4750:	learn: 0.0020474	total: 8m 2s	remaining: 8m 52s
4420:	learn: 0.0021554	total: 8m 2s	remaining: 10m 8s
4839:	learn: 0.0019166	total: 8m 2s	remaining: 8m 34s
4751:	learn: 0.0018752	total: 8m 2s	remaining: 8m 52s
4612:	learn: 0.0021357	total: 8m 2s	remaining: 9m 23s
4751:	learn: 0.0020468	total: 8m 2s	remaining: 8m 52s
4421:	learn: 0.0021547	total: 8m 2s	remaining: 10m 8s
4752:	learn: 0.0018752	total: 8m 2s	remaining: 8m 52s
4840:	learn: 0.0019166	total: 8m 2s	remaining: 8m 33s
4613:	learn: 0.0021351	total: 8m 2s	remaining: 9m 23s
4752:	learn: 0.0020461	total: 8m 2s	remaining: 8m 52s
4422:	learn: 0.0021539	total: 8m 2s	remaining: 10m 8s
4753:	learn: 0.0018752	total: 8m 2s	remaining: 8m 52s
4841:	learn: 0.0019159	total: 8m 2s	remaining: 8m 33s
4753:	learn: 0.0020456	total: 8m 2s	remaining: 8m 52s
4614:	learn: 0.0021351	total: 8m 2s	remaining: 9m 22s
4754:	learn: 0.0020451	total: 8m 2s	remaining: 8m 52s
4423:	learn: 0.0021528	total: 8m 2s	remaining: 10m 8s
4754:	learn: 0.0018752	total: 8m 2s	remaining: 8m 52s
4842:	learn: 0.0019152	total: 8m 2s	remaining: 8m 33s
4843:	learn: 0.0019152	total: 8m 2s	remaining: 8m 33s
4615:	learn: 0.0021343	total: 8m 2s	remaining: 9m 22s
4755:	learn: 0.0020447	total: 8m 2s	remaining: 8m 51s
4755:	learn: 0.0018752	total: 8m 2s	remaining: 8m 52s
4424:	learn: 0.0021520	total: 8m 2s	remaining: 10m 8s
4756:	learn: 0.0018752	total: 8m 2s	remaining: 8m 51s
4616:	learn: 0.0021343	total: 8m 2s	remaining: 9m 22s
4844:	learn: 0.0019146	total: 8m 2s	remaining: 8m 33s
4756:	learn: 0.0020443	total: 8m 2s	remaining: 8m 51s
4425:	learn: 0.0021514	total: 8m 2s	remaining: 10m 7s
4757:	learn: 0.0018752	total: 8m 2s	remaining: 8m 51s
4757:	learn: 0.0020440	total: 8m 2s	remaining: 8m 51s
4617:	learn: 0.0021343	total: 8m 2s	remaining: 9m 22s
4845:	learn: 0.0019140	total: 8m 2s	remaining: 8m 33s
4426:	learn: 0.0021505	total: 8m 2s	remaining: 10m 7s
4758:	learn: 0.0020437	total: 8m 2s	remaining: 8m 51s
4758:	learn: 0.0018752	total: 8m 2s	remaining: 8m 51s
4846:	learn: 0.0019140	total: 8m 2s	remaining: 8m 33s
al: 7m 50s	remaining: 9m 4s
 1s
 �      aining: �    4618:	learn: 0.0021343	total: 8m 2s	remaining: 9m 22s
4427:	learn: 0.0021497	total: 8m 2s	remaining: 10m 7s
4759:	learn: 0.0020435	total: 8m 2s	remaining: 8m 51s
4759:	learn: 0.0018747	total: 8m 2s	remaining: 8m 51s
4428:	learn: 0.0021491	total: 8m 3s	remaining: 10m 7s
4847:	learn: 0.0019135	total: 8m 3s	remaining: 8m 33s
4619:	learn: 0.0021343	total: 8m 3s	remaining: 9m 22s
4760:	learn: 0.0020432	total: 8m 2s	remaining: 8m 51s
4760:	learn: 0.0018739	total: 8m 3s	remaining: 8m 51s
4620:	learn: 0.0021343	total: 8m 3s	remaining: 9m 22s
4429:	learn: 0.0021483	total: 8m 3s	remaining: 10m 7s
4848:	learn: 0.0019134	total: 8m 3s	remaining: 8m 33s
4761:	learn: 0.0018739	total: 8m 3s	remaining: 8m 51s
4761:	learn: 0.0020426	total: 8m 3s	remaining: 8m 51s
4762:	learn: 0.0018739	total: 8m 3s	remaining: 8m 51s
4621:	learn: 0.0021343	total: 8m 3s	remaining: 9m 22s
4849:	learn: 0.0019129	total: 8m 3s	remaining: 8m 33s
4430:	learn: 0.0021479	total: 8m 3s	remaining: 10m 7s
4762:	learn: 0.0020417	total: 8m 3s	remaining: 8m 51s
4763:	learn: 0.0018730	total: 8m 3s	remaining: 8m 51s
4622:	learn: 0.0021337	total: 8m 3s	remaining: 9m 22s
4850:	learn: 0.0019123	total: 8m 3s	remaining: 8m 33s
4431:	learn: 0.0021474	total: 8m 3s	remaining: 10m 7s
4764:	learn: 0.0018727	total: 8m 3s	remaining: 8m 51s
4763:	learn: 0.0020408	total: 8m 3s	remaining: 8m 51s
4623:	learn: 0.0021337	total: 8m 3s	remaining: 9m 22s
4851:	learn: 0.0019120	total: 8m 3s	remaining: 8m 32s
4432:	learn: 0.0021465	total: 8m 3s	remaining: 10m 7s
4765:	learn: 0.0018727	total: 8m 3s	remaining: 8m 50s
4852:	learn: 0.0019114	total: 8m 3s	remaining: 8m 32s
4624:	learn: 0.0021337	total: 8m 3s	remaining: 9m 21s
4764:	learn: 0.0020399	total: 8m 3s	remaining: 8m 51s
4853:	learn: 0.0019109	total: 8m 3s	remaining: 8m 32s
4433:	learn: 0.0021457	total: 8m 3s	remaining: 10m 7s
4766:	learn: 0.0018717	total: 8m 3s	remaining: 8m 50s
4625:	learn: 0.0021337	total: 8m 3s	remaining: 9m 21s
4765:	learn: 0.0020392	total: 8m 3s	remaining: 8m 50s
4854:	learn: 0.0019108	total: 8m 3s	remaining: 8m 32s
4626:	learn: 0.0021336	total: 8m 3s	remaining: 9m 21s
4434:	learn: 0.0021448	total: 8m 3s	remaining: 10m 6s
4767:	learn: 0.0018707	total: 8m 3s	remaining: 8m 50s
4766:	learn: 0.0020387	total: 8m 3s	remaining: 8m 50s
4855:	learn: 0.0019101	total: 8m 3s	remaining: 8m 32s
4627:	learn: 0.0021336	total: 8m 3s	remaining: 9m 21s
4768:	learn: 0.0018707	total: 8m 3s	remaining: 8m 50s
4435:	learn: 0.0021440	total: 8m 3s	remaining: 10m 6s
4767:	learn: 0.0020379	total: 8m 3s	remaining: 8m 50s
4628:	learn: 0.0021336	total: 8m 3s	remaining: 9m 21s
4856:	learn: 0.0019095	total: 8m 3s	remaining: 8m 32s
4769:	learn: 0.0018699	total: 8m 3s	remaining: 8m 50s
4436:	learn: 0.0021431	total: 8m 3s	remaining: 10m 6s
4629:	learn: 0.0021336	total: 8m 3s	remaining: 9m 21s
4857:	learn: 0.0019095	total: 8m 3s	remaining: 8m 32s
4768:	learn: 0.0020372	total: 8m 3s	remaining: 8m 50s
4770:	learn: 0.0018699	total: 8m 3s	remaining: 8m 50s
4630:	learn: 0.0021336	total: 8m 4s	remaining: 9m 21s
4858:	learn: 0.0019090	total: 8m 4s	remaining: 8m 32s
4437:	learn: 0.0021423	total: 8m 4s	remaining: 10m 6s
4769:	learn: 0.0020367	total: 8m 3s	remaining: 8m 50s
4771:	learn: 0.0018699	total: 8m 4s	remaining: 8m 50s
4859:	learn: 0.0019089	total: 8m 4s	remaining: 8m 31s
4631:	learn: 0.0021337	total: 8m 4s	remaining: 9m 21s
4770:	learn: 0.0020362	total: 8m 4s	remaining: 8m 50s
4860:	learn: 0.0019089	total: 8m 4s	remaining: 8m 31s
4772:	learn: 0.0018699	total: 8m 4s	remaining: 8m 50s
4438:	learn: 0.0021416	total: 8m 4s	remaining: 10m 6s
4861:	learn: 0.0019082	total: 8m 4s	remaining: 8m 31s
4771:	learn: 0.0020354	total: 8m 4s	remaining: 8m 50s
4632:	learn: 0.0021337	total: 8m 4s	remaining: 9m 21s
4773:	learn: 0.0018699	total: 8m 4s	remaining: 8m 50s
4439:	learn: 0.0021410	total: 8m 4s	remaining: 10m 6s
4862:	learn: 0.0019073	total: 8m 4s	remaining: 8m 31s
4774:	learn: 0.0018699	total: 8m 4s	remaining: 8m 50s
4772:	learn: 0.0020348	total: 8m 4s	remaining: 8m 50s
4633:	learn: 0.0021328	total: 8m 4s	remaining: 9m 20s
4863:	learn: 0.0019067	total: 8m 4s	remaining: 8m 31s
4440:	learn: 0.0021410	total: 8m 4s	remaining: 10m 6s
4773:	learn: 0.0020341	total: 8m 4s	remaining: 8m 50s
4775:	learn: 0.0018699	total: 8m 4s	remaining: 8m 49s
4634:	learn: 0.0021319	total: 8m 4s	remaining: 9m 20s
4864:	learn: 0.0019067	total: 8m 4s	remaining: 8m 31s
4774:	learn: 0.0020331	total: 8m 4s	remaining: 8m 50s
4441:	learn: 0.0021404	total: 8m 4s	remaining: 10m 6s
4635:	learn: 0.0021319	total: 8m 4s	remaining: 9m 20s
4776:	learn: 0.0018699	total: 8m 4s	remaining: 8m 49s
4865:	learn: 0.0019067	total: 8m 4s	remaining: 8m 31s
4442:	learn: 0.0021404	total: 8m 4s	remaining: 10m 6s
4775:	learn: 0.0020325	total: 8m 4s	remaining: 8m 49s
4777:	learn: 0.0018699	total: 8m 4s	remaining: 8m 49s
4636:	learn: 0.0021319	total: 8m 4s	remaining: 9m 20s
4866:	learn: 0.0019066	total: 8m 4s	remaining: 8m 31s
4776:	learn: 0.0020320	total: 8m 4s	remaining: 8m 49s
4443:	learn: 0.0021397	total: 8m 4s	remaining: 10m 6s
4778:	learn: 0.0018699	total: 8m 4s	remaining: 8m 49s
4637:	learn: 0.0021314	total: 8m 4s	remaining: 9m 20s
4867:	learn: 0.0019062	total: 8m 4s	remaining: 8m 31s
4777:	learn: 0.0020312	total: 8m 4s	remaining: 8m 49s
4444:	learn: 0.0021388	total: 8m 4s	remaining: 10m 5s
4779:	learn: 0.0018699	total: 8m 4s	remaining: 8m 49s
4638:	learn: 0.0021312	total: 8m 4s	remaining: 9m 20s
4868:	learn: 0.0019062	total: 8m 4s	remaining: 8m 31s
4778:	learn: 0.0020309	total: 8m 4s	remaining: 8m 49s
4639:	learn: 0.0021303	total: 8m 4s	remaining: 9m 20s
4445:	learn: 0.0021380	total: 8m 5s	remaining: 10m 5s
4780:	learn: 0.0018699	total: 8m 4s	remaining: 8m 49s
4869:	learn: 0.0019056	total: 8m 5s	remaining: 8m 30s
4779:	learn: 0.0020304	total: 8m 4s	remaining: 8m 49s
4640:	learn: 0.0021303	total: 8m 5s	remaining: 9m 20s
4446:	learn: 0.0021373	total: 8m 5s	remaining: 10m 5s
4781:	learn: 0.0018699	total: 8m 5s	remaining: 8m 49s
4870:	learn: 0.0019056	total: 8m 5s	remaining: 8m 30s
4780:	learn: 0.0020297	total: 8m 4s	remaining: 8m 49s
4447:	learn: 0.0021364	total: 8m 5s	remaining: 10m 5s
4641:	learn: 0.0021303	total: 8m 5s	remaining: 9m 20s
4782:	learn: 0.0018699	total: 8m 5s	remaining: 8m 49s
4781:	learn: 0.0020289	total: 8m 5s	remaining: 8m 49s
4871:	learn: 0.0019051	total: 8m 5s	remaining: 8m 30s
4448:	learn: 0.0021355	total: 8m 5s	remaining: 10m 5s
4642:	learn: 0.0021303	total: 8m 5s	remaining: 9m 19s
4783:	learn: 0.0018699	total: 8m 5s	remaining: 8m 49s
4872:	learn: 0.0019051	total: 8m 5s	remaining: 8m 30s
4782:	learn: 0.0020283	total: 8m 5s	remaining: 8m 49s
4643:	learn: 0.0021294	total: 8m 5s	remaining: 9m 19s
4449:	learn: 0.0021355	total: 8m 5s	remaining: 10m 5s
4873:	learn: 0.0019044	total: 8m 5s	remaining: 8m 30s
4784:	learn: 0.0018699	total: 8m 5s	remaining: 8m 49s
4644:	learn: 0.0021294	total: 8m 5s	remaining: 9m 19s
4783:	learn: 0.0020275	total: 8m 5s	remaining: 8m 49s
4450:	learn: 0.0021349	total: 8m 5s	remaining: 10m 5s
4874:	learn: 0.0019039	total: 8m 5s	remaining: 8m 30s
4785:	learn: 0.0018699	total: 8m 5s	remaining: 8m 48s
4784:	learn: 0.0020269	total: 8m 5s	remaining: 8m 49s
4875:	learn: 0.0019030	total: 8m 5s	remaining: 8m 30s
4645:	learn: 0.0021294	total: 8m 5s	remaining: 9m 19s
4451:	learn: 0.0021345	total: 8m 5s	remaining: 10m 5s
4786:	learn: 0.0018699	total: 8m 5s	remaining: 8m 48s
4646:	learn: 0.0021294	total: 8m 5s	remaining: 9m 19s
4876:	learn: 0.0019028	total: 8m 5s	remaining: 8m 30s
4452:	learn: 0.0021345	total: 8m 5s	remaining: 10m 5s
4785:	learn: 0.0020269	total: 8m 5s	remaining: 8m 48s
4787:	learn: 0.0018699	total: 8m 5s	remaining: 8m 48s
4647:	learn: 0.0021294	total: 8m 5s	remaining: 9m 19s
4877:	learn: 0.0019028	total: 8m 5s	remaining: 8m 30s
4453:	learn: 0.0021338	total: 8m 5s	remaining: 10m 4s
4788:	learn: 0.0018699	total: 8m 5s	remaining: 8m 48s
4786:	learn: 0.0020264	total: 8m 5s	remaining: 8m 48s
4648:	learn: 0.0021294	total: 8m 5s	remaining: 9m 19s
4787:	learn: 0.0020264	total: 8m 5s	remaining: 8m 48s
4454:	learn: 0.0021329	total: 8m 5s	remaining: 10m 4s
4878:	learn: 0.0019027	total: 8m 5s	remaining: 8m 29s
4789:	learn: 0.0018699	total: 8m 5s	remaining: 8m 48s

4649:	learn: 0.0021294	total: 8m 5s	remaining: 9m 19s
4788:	learn: 0.0020256	total: 8m 5s	remaining: 8m 48s
4455:	learn: 0.0021324	total: 8m 6s	remaining: 10m 4s
4879:	learn: 0.0019027	total: 8m 5s	remaining: 8m 29s
4790:	learn: 0.0018693	total: 8m 6s	remaining: 8m 48s
4880:	learn: 0.0019027	total: 8m 6s	remaining: 8m 29s
4650:	learn: 0.0021294	total: 8m 6s	remaining: 9m 19s
4789:	learn: 0.0020249	total: 8m 5s	remaining: 8m 48s
4456:	learn: 0.0021318	total: 8m 6s	remaining: 10m 4s
4791:	learn: 0.0018693	total: 8m 6s	remaining: 8m 48s
4881:	learn: 0.0019020	total: 8m 6s	remaining: 8m 29s
4651:	learn: 0.0021294	total: 8m 6s	remaining: 9m 18s
4790:	learn: 0.0020241	total: 8m 6s	remaining: 8m 48s
4457:	learn: 0.0021312	total: 8m 6s	remaining: 10m 4s
4792:	learn: 0.0018693	total: 8m 6s	remaining: 8m 48s
4882:	learn: 0.0019020	total: 8m 6s	remaining: 8m 29s
4652:	learn: 0.0021294	total: 8m 6s	remaining: 9m 18s
4458:	learn: 0.0021311	total: 8m 6s	remaining: 10m 4s
4791:	learn: 0.0020235	total: 8m 6s	remaining: 8m 48s
4793:	learn: 0.0018693	total: 8m 6s	remaining: 8m 48s
4883:	learn: 0.0019014	total: 8m 6s	remaining: 8m 29s
4653:	learn: 0.0021286	total: 8m 6s	remaining: 9m 18s
4459:	learn: 0.0021307	total: 8m 6s	remaining: 10m 4s
4792:	learn: 0.0020229	total: 8m 6s	remaining: 8m 48s
4794:	learn: 0.0018688	total: 8m 6s	remaining: 8m 47s
4884:	learn: 0.0019014	total: 8m 6s	remaining: 8m 29s
4654:	learn: 0.0021279	total: 8m 6s	remaining: 9m 18s
4460:	learn: 0.0021306	total: 8m 6s	remaining: 10m 4s
4793:	learn: 0.0020224	total: 8m 6s	remaining: 8m 48s
4795:	learn: 0.0018688	total: 8m 6s	remaining: 8m 47s
4885:	learn: 0.0019009	total: 8m 6s	remaining: 8m 29s
4655:	learn: 0.0021269	total: 8m 6s	remaining: 9m 18s
4886:	learn: 0.0019004	total: 8m 6s	remaining: 8m 29s
4796:	learn: 0.0018688	total: 8m 6s	remaining: 8m 47s
4461:	learn: 0.0021299	total: 8m 6s	remaining: 10m 4s
4794:	learn: 0.0020218	total: 8m 6s	remaining: 8m 48s
4887:	learn: 0.0019003	total: 8m 6s	remaining: 8m 28s
4656:	learn: 0.0021269	total: 8m 6s	remaining: 9m 18s
4797:	learn: 0.0018688	total: 8m 6s	remaining: 8m 47s
4462:	learn: 0.0021299	total: 8m 6s	remaining: 10m 3s
4795:	learn: 0.0020212	total: 8m 6s	remaining: 8m 47s
4657:	learn: 0.0021269	total: 8m 6s	remaining: 9m 18s
4888:	learn: 0.0019003	total: 8m 6s	remaining: 8m 28s
4798:	learn: 0.0018688	total: 8m 6s	remaining: 8m 47s
4796:	learn: 0.0020205	total: 8m 6s	remaining: 8m 47s
4658:	learn: 0.0021269	total: 8m 6s	remaining: 9m 18s
4889:	learn: 0.0018997	total: 8m 6s	remaining: 8m 28s
4463:	learn: 0.0021292	total: 8m 6s	remaining: 10m 3s
4799:	learn: 0.0018687	total: 8m 6s	remaining: 8m 47s
4659:	learn: 0.0021263	total: 8m 6s	remaining: 9m 17s
4797:	learn: 0.0020199	total: 8m 6s	remaining: 8m 47s
4890:	learn: 0.0018991	total: 8m 6s	remaining: 8m 28s
4800:	learn: 0.0018687	total: 8m 6s	remaining: 8m 47s
4464:	learn: 0.0021286	total: 8m 7s	remaining: 10m 3s
4660:	learn: 0.0021263	total: 8m 7s	remaining: 9m 17s
4798:	learn: 0.0020193	total: 8m 6s	remaining: 8m 47s
4891:	learn: 0.0018986	total: 8m 7s	remaining: 8m 28s
4801:	learn: 0.0018688	total: 8m 7s	remaining: 8m 47s
4799:	learn: 0.0020191	total: 8m 6s	remaining: 8m 47s
4465:	learn: 0.0021282	total: 8m 7s	remaining: 10m 3s
4661:	learn: 0.0021263	total: 8m 7s	remaining: 9m 17s
4892:	learn: 0.0018980	total: 8m 7s	remaining: 8m 28s
4800:	learn: 0.0020185	total: 8m 7s	remaining: 8m 47s
4802:	learn: 0.0018687	total: 8m 7s	remaining: 8m 47s
4466:	learn: 0.0021275	total: 8m 7s	remaining: 10m 3s
4662:	learn: 0.0021255	total: 8m 7s	remaining: 9m 17s
4893:	learn: 0.0018980	total: 8m 7s	remaining: 8m 28s
4801:	learn: 0.0020180	total: 8m 7s	remaining: 8m 47s
4803:	learn: 0.0018688	total: 8m 7s	remaining: 8m 47s
4894:	learn: 0.0018974	total: 8m 7s	remaining: 8m 28s
4467:	learn: 0.0021271	total: 8m 7s	remaining: 10m 3s
4663:	learn: 0.0021255	total: 8m 7s	remaining: 9m 17s
4802:	learn: 0.0020174	total: 8m 7s	remaining: 8m 47s
4804:	learn: 0.0018688	total: 8m 7s	remaining: 8m 46s
4895:	learn: 0.0018974	total: 8m 7s	remaining: 8m 28s
4664:	learn: 0.0021255	total: 8m 7s	remaining: 9m 17s
4803:	learn: 0.0020163	total: 8m 7s	remaining: 8m 47s
4468:	learn: 0.0021271	total: 8m 7s	remaining: 10m 3s
4805:	learn: 0.0018680	total: 8m 7s	remaining: 8m 46s
4896:	learn: 0.0018974	total: 8m 7s	remaining: 8m 28s
4665:	learn: 0.0021255	total: 8m 7s	remaining: 9m 17s
4804:	learn: 0.0020157	total: 8m 7s	remaining: 8m 46s
4469:	learn: 0.0021271	total: 8m 7s	remaining: 10m 3s
4806:	learn: 0.0018680	total: 8m 7s	remaining: 8m 46s
4897:	learn: 0.0018969	total: 8m 7s	remaining: 8m 27s
4666:	learn: 0.0021255	total: 8m 7s	remaining: 9m 17s
4898:	learn: 0.0018964	total: 8m 7s	remaining: 8m 27s
4807:	learn: 0.0018680	total: 8m 7s	remaining: 8m 46s
4470:	learn: 0.0021268	total: 8m 7s	remaining: 10m 3s
4805:	learn: 0.0020152	total: 8m 7s	remaining: 8m 46s
4667:	learn: 0.0021255	total: 8m 7s	remaining: 9m 17s
4808:	learn: 0.0018680	total: 8m 7s	remaining: 8m 46s
4899:	learn: 0.0018965	total: 8m 7s	remaining: 8m 27s
4806:	learn: 0.0020146	total: 8m 7s	remaining: 8m 46s
4668:	learn: 0.0021255	total: 8m 7s	remaining: 9m 17s
4471:	learn: 0.0021260	total: 8m 7s	remaining: 10m 3s
4809:	learn: 0.0018680	total: 8m 7s	remaining: 8m 46s
4900:	learn: 0.0018959	total: 8m 7s	remaining: 8m 27s
4807:	learn: 0.0020141	total: 8m 7s	remaining: 8m 46s
4669:	learn: 0.0021248	total: 8m 7s	remaining: 9m 16s
4810:	learn: 0.0018680	total: 8m 7s	remaining: 8m 46s
4472:	learn: 0.0021251	total: 8m 7s	remaining: 10m 2s
4901:	learn: 0.0018959	total: 8m 7s	remaining: 8m 27s
4670:	learn: 0.0021248	total: 8m 7s	remaining: 9m 16s
4473:	learn: 0.0021242	total: 8m 8s	remaining: 10m 2s
4808:	learn: 0.0020133	total: 8m 7s	remaining: 8m 46s
4811:	learn: 0.0018680	total: 8m 8s	remaining: 8m 46s
4671:	learn: 0.0021248	total: 8m 8s	remaining: 9m 16s
4902:	learn: 0.0018954	total: 8m 8s	remaining: 8m 27s
4812:	learn: 0.0018680	total: 8m 8s	remaining: 8m 46s
4474:	learn: 0.0021233	total: 8m 8s	remaining: 10m 2s
4672:	learn: 0.0021248	total: 8m 8s	remaining: 9m 16s
4809:	learn: 0.0020126	total: 8m 8s	remaining: 8m 46s
4903:	learn: 0.0018954	total: 8m 8s	remaining: 8m 27s
4813:	learn: 0.0018680	total: 8m 8s	remaining: 8m 45s
4673:	learn: 0.0021248	total: 8m 8s	remaining: 9m 16s
4475:	learn: 0.0021227	total: 8m 8s	remaining: 10m 2s
4810:	learn: 0.0020118	total: 8m 8s	remaining: 8m 46s
4814:	learn: 0.0018680	total: 8m 8s	remaining: 8m 45s
4904:	learn: 0.0018949	total: 8m 8s	remaining: 8m 27s
4674:	learn: 0.0021248	total: 8m 8s	remaining: 9m 16s
4905:	learn: 0.0018946	total: 8m 8s	remaining: 8m 27s
4811:	learn: 0.0020113	total: 8m 8s	remaining: 8m 46s
4476:	learn: 0.0021224	total: 8m 8s	remaining: 10m 2s
4815:	learn: 0.0018680	total: 8m 8s	remaining: 8m 45s
4675:	learn: 0.0021248	total: 8m 8s	remaining: 9m 16s
4906:	learn: 0.0018941	total: 8m 8s	remaining: 8m 26s
4812:	learn: 0.0020102	total: 8m 8s	remaining: 8m 46s
4816:	learn: 0.0018676	total: 8m 8s	remaining: 8m 45s
4477:	learn: 0.0021220	total: 8m 8s	remaining: 10m 2s
4676:	learn: 0.0021248	total: 8m 8s	remaining: 9m 16s
4907:	learn: 0.0018941	total: 8m 8s	remaining: 8m 26s
4813:	learn: 0.0020102	total: 8m 8s	remaining: 8m 46s
4817:	learn: 0.0018676	total: 8m 8s	remaining: 8m 45s
4908:	learn: 0.0018940	total: 8m 8s	remaining: 8m 26s
4478:	learn: 0.0021214	total: 8m 8s	remaining: 10m 2s
4677:	learn: 0.0021248	total: 8m 8s	remaining: 9m 15s
4814:	learn: 0.0020097	total: 8m 8s	remaining: 8m 46s
4818:	learn: 0.0018672	total: 8m 8s	remaining: 8m 45s
4909:	learn: 0.0018940	total: 8m 8s	remaining: 8m 26s
4678:	learn: 0.0021248	total: 8m 8s	remaining: 9m 15s
4815:	learn: 0.0020092	total: 8m 8s	remaining: 8m 45s
4479:	learn: 0.0021207	total: 8m 8s	remaining: 10m 2s
4819:	learn: 0.0018672	total: 8m 8s	remaining: 8m 45s
4910:	learn: 0.0018934	total: 8m 8s	remaining: 8m 26s
4816:	learn: 0.0020086	total: 8m 8s	remaining: 8m 45s
4679:	learn: 0.0021248	total: 8m 8s	remaining: 9m 15s
4480:	learn: 0.0021201	total: 8m 8s	remaining: 10m 2s
4820:	learn: 0.0018672	total: 8m 8s	remaining: 8m 45s
4911:	learn: 0.0018934	total: 8m 8s	remaining: 8m 26s
4817:	learn: 0.0020080	total: 8m 8s	remaining: 8m 45s
4481:	learn: 0.0021195	total: 8m 9s	remaining: 10m 2s
4680:	learn: 0.0021248	total: 8m 8s	remaining: 9m 15s
4912:	learn: 0.0018934	total: 8m 9s	remaining: 8m 26s
4821:	learn: 0.0018671	total: 8m 9s	remaining: 8m 45s
4818:	learn: 0.0020072	total: 8m 8s	remaining: 8m 45s
4681:	learn: 0.0021248	total: 8m 9s	remaining: 9m 15s
4482:	learn: 0.0021192	total: 8m 9s	remaining: 10m 1s
4913:	learn: 0.0018933	total: 8m 9s	remaining: 8m 26s
4822:	learn: 0.0018672	total: 8m 9s	remaining: 8m 45s
4819:	learn: 0.0020066	total: 8m 8s	remaining: 8m 45s
4682:	learn: 0.0021248	total: 8m 9s	remaining: 9m 15s
4483:	learn: 0.0021184	total: 8m 9s	remaining: 10m 1s
4914:	learn: 0.0018927	total: 8m 9s	remaining: 8m 26s
4823:	learn: 0.0018671	total: 8m 9s	remaining: 8m 44s
4820:	learn: 0.0020057	total: 8m 9s	remaining: 8m 45s
4683:	learn: 0.0021248	total: 8m 9s	remaining: 9m 15s
4915:	learn: 0.0018922	total: 8m 9s	remaining: 8m 26s
4484:	learn: 0.0021176	total: 8m 9s	remaining: 10m 1s
4824:	learn: 0.0018664	total: 8m 9s	remaining: 8m 44s
4821:	learn: 0.0020052	total: 8m 9s	remaining: 8m 45s
4684:	learn: 0.0021248	total: 8m 9s	remaining: 9m 15s
4916:	learn: 0.0018918	total: 8m 9s	remaining: 8m 25s
4822:	learn: 0.0020047	total: 8m 9s	remaining: 8m 45s
4825:	learn: 0.0018664	total: 8m 9s	remaining: 8m 44s
4485:	learn: 0.0021166	total: 8m 9s	remaining: 10m 1s
4917:	learn: 0.0018918	total: 8m 9s	remaining: 8m 25s
4685:	learn: 0.0021248	total: 8m 9s	remaining: 9m 15s
4823:	learn: 0.0020041	total: 8m 9s	remaining: 8m 45s
4826:	learn: 0.0018664	total: 8m 9s	remaining: 8m 44s
4918:	learn: 0.0018913	total: 8m 9s	remaining: 8m 25s
4486:	learn: 0.0021162	total: 8m 9s	remaining: 10m 1s
4686:	learn: 0.0021248	total: 8m 9s	remaining: 9m 14s
4827:	learn: 0.0018664	total: 8m 9s	remaining: 8m 44s
4824:	learn: 0.0020036	total: 8m 9s	remaining: 8m 45s
4919:	learn: 0.0018908	total: 8m 9s	remaining: 8m 25s
4487:	learn: 0.0021156	total: 8m 9s	remaining: 10m 1s
4828:	learn: 0.0018664	total: 8m 9s	remaining: 8m 44s
4687:	learn: 0.0021242	total: 8m 9s	remaining: 9m 14s
4920:	learn: 0.0018902	total: 8m 9s	remaining: 8m 25s
4488:	learn: 0.0021149	total: 8m 9s	remaining: 10m 1s
4825:	learn: 0.0020031	total: 8m 9s	remaining: 8m 44s
4688:	learn: 0.0021242	total: 8m 9s	remaining: 9m 14s
4829:	learn: 0.0018664	total: 8m 9s	remaining: 8m 44s
4921:	learn: 0.0018902	total: 8m 9s	remaining: 8m 25s
4489:	learn: 0.0021143	total: 8m 9s	remaining: 10m 1s
4826:	learn: 0.0020025	total: 8m 9s	remaining: 8m 44s
4830:	learn: 0.0018664	total: 8m 9s	remaining: 8m 44s
4689:	learn: 0.0021242	total: 8m 9s	remaining: 9m 14s
4922:	learn: 0.0018902	total: 8m 9s	remaining: 8m 25s
4827:	learn: 0.0020019	total: 8m 9s	remaining: 8m 44s
4490:	learn: 0.0021138	total: 8m 10s	remaining: 10m 1s
4831:	learn: 0.0018664	total: 8m 9s	remaining: 8m 44s
4690:	learn: 0.0021236	total: 8m 10s	remaining: 9m 14s
4923:	learn: 0.0018902	total: 8m 10s	remaining: 8m 25s
4828:	learn: 0.0020014	total: 8m 9s	remaining: 8m 44s
4491:	learn: 0.0021132	total: 8m 10s	remaining: 10m
4832:	learn: 0.0018663	total: 8m 10s	remaining: 8m 43s
4924:	learn: 0.0018895	total: 8m 10s	remaining: 8m 25s
4691:	learn: 0.0021236	total: 8m 10s	remaining: 9m 14s
4829:	learn: 0.0020006	total: 8m 10s	remaining: 8m 44s
4833:	learn: 0.0018664	total: 8m 10s	remaining: 8m 43s
4492:	learn: 0.0021124	total: 8m 10s	remaining: 10m
4925:	learn: 0.0018893	total: 8m 10s	remaining: 8m 24s
4692:	learn: 0.0021236	total: 8m 10s	remaining: 9m 14s
4830:	learn: 0.0020002	total: 8m 10s	remaining: 8m 44s
4834:	learn: 0.0018664	total: 8m 10s	remaining: 8m 43s
4926:	learn: 0.0018893	total: 8m 10s	remaining: 8m 24s
4493:	learn: 0.0021116	total: 8m 10s	remaining: 10m
4831:	learn: 0.0019995	total: 8m 10s	remaining: 8m 44s
4693:	learn: 0.0021236	total: 8m 10s	remaining: 9m 14s
4835:	learn: 0.0018663	total: 8m 10s	remaining: 8m 43s
4927:	learn: 0.0018889	total: 8m 10s	remaining: 8m 24s
4694:	learn: 0.0021236	total: 8m 10s	remaining: 9m 14s
4832:	learn: 0.0019988	total: 8m 10s	remaining: 8m 44s
4494:	learn: 0.0021109	total: 8m 10s	remaining: 10m
4836:	learn: 0.0018663	total: 8m 10s	remaining: 8m 43s
4695:	learn: 0.0021236	total: 8m 10s	remaining: 9m 14s
4928:	learn: 0.0018883	total: 8m 10s	remaining: 8m 24s
4833:	learn: 0.0019983	total: 8m 10s	remaining: 8m 44s
4495:	learn: 0.0021104	total: 8m 10s	remaining: 10m
4837:	learn: 0.0018663	total: 8m 10s	remaining: 8m 43s
4696:	learn: 0.0021236	total: 8m 10s	remaining: 9m 13s
4929:	learn: 0.0018883	total: 8m 10s	remaining: 8m 24s
4496:	learn: 0.0021094	total: 8m 10s	remaining: 10m
4834:	learn: 0.0019978	total: 8m 10s	remaining: 8m 44s
4838:	learn: 0.0018663	total: 8m 10s	remaining: 8m 43s
4930:	learn: 0.0018877	total: 8m 10s	remaining: 8m 24s
4697:	learn: 0.0021236	total: 8m 10s	remaining: 9m 13s
4497:	learn: 0.0021087	total: 8m 10s	remaining: 10m
4835:	learn: 0.0019972	total: 8m 10s	remaining: 8m 43s
4839:	learn: 0.0018663	total: 8m 10s	remaining: 8m 43s
4931:	learn: 0.0018877	total: 8m 10s	remaining: 8m 24s
4698:	learn: 0.0021235	total: 8m 10s	remaining: 9m 13s
4498:	learn: 0.0021080	total: 8m 10s	remaining: 10m
4932:	learn: 0.0018877	total: 8m 10s	remaining: 8m 24s
4840:	learn: 0.0018663	total: 8m 10s	remaining: 8m 43s
4836:	learn: 0.0019967	total: 8m 10s	remaining: 8m 43s
4699:	learn: 0.0021236	total: 8m 10s	remaining: 9m 13s
4841:	learn: 0.0018663	total: 8m 10s	remaining: 8m 42s
4933:	learn: 0.0018877	total: 8m 10s	remaining: 8m 24s
4499:	learn: 0.0021074	total: 8m 11s	remaining: 10m
4837:	learn: 0.0019960	total: 8m 10s	remaining: 8m 43s
4842:	learn: 0.0018663	total: 8m 11s	remaining: 8m 42s
4934:	learn: 0.0018877	total: 8m 11s	remaining: 8m 23s
4500:	learn: 0.0021066	total: 8m 11s	remaining: 9m 59s
4700:	learn: 0.0021235	total: 8m 11s	remaining: 9m 13s
4838:	learn: 0.0019953	total: 8m 10s	remaining: 8m 43s
4843:	learn: 0.0018663	total: 8m 11s	remaining: 8m 42s
4935:	learn: 0.0018871	total: 8m 11s	remaining: 8m 23s
4501:	learn: 0.0021061	total: 8m 11s	remaining: 9m 59s
4701:	learn: 0.0021236	total: 8m 11s	remaining: 9m 13s
4839:	learn: 0.0019946	total: 8m 11s	remaining: 8m 43s
4936:	learn: 0.0018866	total: 8m 11s	remaining: 8m 23s
4844:	learn: 0.0018663	total: 8m 11s	remaining: 8m 42s
4502:	learn: 0.0021056	total: 8m 11s	remaining: 9m 59s
4702:	learn: 0.0021236	total: 8m 11s	remaining: 9m 13s
4840:	learn: 0.0019936	total: 8m 11s	remaining: 8m 43s
4937:	learn: 0.0018860	total: 8m 11s	remaining: 8m 23s
4845:	learn: 0.0018663	total: 8m 11s	remaining: 8m 42s
4703:	learn: 0.0021229	total: 8m 11s	remaining: 9m 13s
4503:	learn: 0.0021049	total: 8m 11s	remaining: 9m 59s
4841:	learn: 0.0019930	total: 8m 11s	remaining: 8m 43s
4938:	learn: 0.0018860	total: 8m 11s	remaining: 8m 23s
4504:	learn: 0.0021044	total: 8m 11s	remaining: 9m 59s
4704:	learn: 0.0021229	total: 8m 11s	remaining: 9m 13s
4846:	learn: 0.0018663	total: 8m 11s	remaining: 8m 42s
4842:	learn: 0.0019926	total: 8m 11s	remaining: 8m 43s
4939:	learn: 0.0018855	total: 8m 11s	remaining: 8m 23s
4505:	learn: 0.0021037	total: 8m 11s	remaining: 9m 59s
4705:	learn: 0.0021229	total: 8m 11s	remaining: 9m 12s
4847:	learn: 0.0018657	total: 8m 11s	remaining: 8m 42s
4843:	learn: 0.0019917	total: 8m 11s	remaining: 8m 43s
4940:	learn: 0.0018855	total: 8m 11s	remaining: 8m 23s
4506:	learn: 0.0021031	total: 8m 11s	remaining: 9m 59s
4706:	learn: 0.0021229	total: 8m 11s	remaining: 9m 12s
4848:	learn: 0.0018657	total: 8m 11s	remaining: 8m 42s
4844:	learn: 0.0019912	total: 8m 11s	remaining: 8m 42s
4941:	learn: 0.0018850	total: 8m 11s	remaining: 8m 23s
4507:	learn: 0.0021023	total: 8m 11s	remaining: 9m 59s
4845:	learn: 0.0019907	total: 8m 11s	remaining: 8m 42s
4707:	learn: 0.0021228	total: 8m 11s	remaining: 9m 12s
4849:	learn: 0.0018657	total: 8m 11s	remaining: 8m 42s
4942:	learn: 0.0018850	total: 8m 11s	remaining: 8m 23s
4850:	learn: 0.0018657	total: 8m 11s	remaining: 8m 42s
4508:	learn: 0.0021022	total: 8m 11s	remaining: 9m 59s
4846:	learn: 0.0019901	total: 8m 11s	remaining: 8m 42s
4708:	learn: 0.0021220	total: 8m 11s	remaining: 9m 12s
4943:	learn: 0.0018850	total: 8m 11s	remaining: 8m 23s
4851:	learn: 0.0018655	total: 8m 11s	remaining: 8m 41s
4509:	learn: 0.0021022	total: 8m 12s	remaining: 9m 58s

4944:	learn: 0.0018842	total: 8m 11s	remaining: 8m 22s
4709:	learn: 0.0021220	total: 8m 12s	remaining: 9m 12s
4847:	learn: 0.0019894	total: 8m 11s	remaining: 8m 42s
4852:	learn: 0.0018655	total: 8m 12s	remaining: 8m 41s
4510:	learn: 0.0021019	total: 8m 12s	remaining: 9m 58s
4853:	learn: 0.0018655	total: 8m 12s	remaining: 8m 41s
4848:	learn: 0.0019889	total: 8m 11s	remaining: 8m 42s
4945:	learn: 0.0018841	total: 8m 12s	remaining: 8m 22s
4710:	learn: 0.0021220	total: 8m 12s	remaining: 9m 12s
4854:	learn: 0.0018655	total: 8m 12s	remaining: 8m 41s
4511:	learn: 0.0021019	total: 8m 12s	remaining: 9m 58s
4946:	learn: 0.0018841	total: 8m 12s	remaining: 8m 22s
4849:	learn: 0.0019882	total: 8m 12s	remaining: 8m 42s
4711:	learn: 0.0021220	total: 8m 12s	remaining: 9m 12s
4855:	learn: 0.0018649	total: 8m 12s	remaining: 8m 41s
4947:	learn: 0.0018841	total: 8m 12s	remaining: 8m 22s
4512:	learn: 0.0021013	total: 8m 12s	remaining: 9m 58s
4850:	learn: 0.0019876	total: 8m 12s	remaining: 8m 42s
4712:	learn: 0.0021220	total: 8m 12s	remaining: 9m 12s
4856:	learn: 0.0018639	total: 8m 12s	remaining: 8m 41s
4948:	learn: 0.0018836	total: 8m 12s	remaining: 8m 22s
4513:	learn: 0.0020999	total: 8m 12s	remaining: 9m 58s
4851:	learn: 0.0019870	total: 8m 12s	remaining: 8m 42s
4857:	learn: 0.0018632	total: 8m 12s	remaining: 8m 41s
4713:	learn: 0.0021212	total: 8m 12s	remaining: 9m 12s
4514:	learn: 0.0020995	total: 8m 12s	remaining: 9m 58s
4852:	learn: 0.0019864	total: 8m 12s	remaining: 8m 42s
4858:	learn: 0.0018629	total: 8m 12s	remaining: 8m 41s
4949:	learn: 0.0018836	total: 8m 12s	remaining: 8m 22s
4714:	learn: 0.0021205	total: 8m 12s	remaining: 9m 12s
4515:	learn: 0.0020988	total: 8m 12s	remaining: 9m 58s
4950:	learn: 0.0018831	total: 8m 12s	remaining: 8m 22s
4853:	learn: 0.0019858	total: 8m 12s	remaining: 8m 42s
4859:	learn: 0.0018629	total: 8m 12s	remaining: 8m 41s
4516:	learn: 0.0020979	total: 8m 12s	remaining: 9m 58s
4715:	learn: 0.0021204	total: 8m 12s	remaining: 9m 12s
4854:	learn: 0.0019853	total: 8m 12s	remaining: 8m 41s
4951:	learn: 0.0018825	total: 8m 12s	remaining: 8m 22s
4716:	learn: 0.0021196	total: 8m 12s	remaining: 9m 11s
4860:	learn: 0.0018629	total: 8m 12s	remaining: 8m 40s
4855:	learn: 0.0019846	total: 8m 12s	remaining: 8m 41s
4517:	learn: 0.0020976	total: 8m 12s	remaining: 9m 57s
4952:	learn: 0.0018825	total: 8m 12s	remaining: 8m 22s
4717:	learn: 0.0021196	total: 8m 12s	remaining: 9m 11s
4856:	learn: 0.0019840	total: 8m 12s	remaining: 8m 41s
4861:	learn: 0.0018629	total: 8m 12s	remaining: 8m 40s
4518:	learn: 0.0020963	total: 8m 12s	remaining: 9m 57s
4718:	learn: 0.0021196	total: 8m 12s	remaining: 9m 11s
4953:	learn: 0.0018825	total: 8m 12s	remaining: 8m 22s
4857:	learn: 0.0019834	total: 8m 12s	remaining: 8m 41s
4862:	learn: 0.0018629	total: 8m 12s	remaining: 8m 40s
4719:	learn: 0.0021196	total: 8m 13s	remaining: 9m 11s
4519:	learn: 0.0020956	total: 8m 13s	remaining: 9m 57s
4954:	learn: 0.0018824	total: 8m 13s	remaining: 8m 21s
4858:	learn: 0.0019828	total: 8m 12s	remaining: 8m 41s
4863:	learn: 0.0018629	total: 8m 13s	remaining: 8m 40s
4720:	learn: 0.0021196	total: 8m 13s	remaining: 9m 11s
4520:	learn: 0.0020951	total: 8m 13s	remaining: 9m 57s
4859:	learn: 0.0019822	total: 8m 12s	remaining: 8m 41s
4955:	learn: 0.0018819	total: 8m 13s	remaining: 8m 21s
4721:	learn: 0.0021196	total: 8m 13s	remaining: 9m 11s
4864:	learn: 0.0018629	total: 8m 13s	remaining: 8m 40s
4521:	learn: 0.0020951	total: 8m 13s	remaining: 9m 57s
4860:	learn: 0.0019813	total: 8m 13s	remaining: 8m 41s
4956:	learn: 0.0018819	total: 8m 13s	remaining: 8m 21s
4722:	learn: 0.0021196	total: 8m 13s	remaining: 9m 11s
4865:	learn: 0.0018622	total: 8m 13s	remaining: 8m 40s
4522:	learn: 0.0020941	total: 8m 13s	remaining: 9m 57s
4861:	learn: 0.0019806	total: 8m 13s	remaining: 8m 41s
4957:	learn: 0.0018819	total: 8m 13s	remaining: 8m 21s
4866:	learn: 0.0018622	total: 8m 13s	remaining: 8m 40s
4723:	learn: 0.0021196	total: 8m 13s	remaining: 9m 11s
4862:	learn: 0.0019797	total: 8m 13s	remaining: 8m 41s
4523:	learn: 0.0020936	total: 8m 13s	remaining: 9m 57s
4958:	learn: 0.0018819	total: 8m 13s	remaining: 8m 21s
4867:	learn: 0.0018622	total: 8m 13s	remaining: 8m 40s
4724:	learn: 0.0021196	total: 8m 13s	remaining: 9m 10s
4863:	learn: 0.0019791	total: 8m 13s	remaining: 8m 40s
4524:	learn: 0.0020930	total: 8m 13s	remaining: 9m 57s
4959:	learn: 0.0018812	total: 8m 13s	remaining: 8m 21s
4868:	learn: 0.0018616	total: 8m 13s	remaining: 8m 40s
4525:	learn: 0.0020921	total: 8m 13s	remaining: 9m 57s
4725:	learn: 0.0021196	total: 8m 13s	remaining: 9m 10s
4864:	learn: 0.0019786	total: 8m 13s	remaining: 8m 40s
4960:	learn: 0.0018812	total: 8m 13s	remaining: 8m 21s
4869:	learn: 0.0018615	total: 8m 13s	remaining: 8m 40s
4526:	learn: 0.0020915	total: 8m 13s	remaining: 9m 56s
4865:	learn: 0.0019777	total: 8m 13s	remaining: 8m 40s
4726:	learn: 0.0021196	total: 8m 13s	remaining: 9m 10s
4870:	learn: 0.0018615	total: 8m 13s	remaining: 8m 39s
4961:	learn: 0.0018812	total: 8m 13s	remaining: 8m 21s
4527:	learn: 0.0020906	total: 8m 13s	remaining: 9m 56s
4727:	learn: 0.0021196	total: 8m 13s	remaining: 9m 10s
4871:	learn: 0.0018615	total: 8m 13s	remaining: 8m 39s
4866:	learn: 0.0019771	total: 8m 13s	remaining: 8m 40s
4962:	learn: 0.0018808	total: 8m 13s	remaining: 8m 21s
4528:	learn: 0.0020897	total: 8m 13s	remaining: 9m 56s
4872:	learn: 0.0018613	total: 8m 13s	remaining: 8m 39s
4728:	learn: 0.0021196	total: 8m 13s	remaining: 9m 10s
4867:	learn: 0.0019765	total: 8m 13s	remaining: 8m 40s
4963:	learn: 0.0018804	total: 8m 13s	remaining: 8m 21s
4873:	learn: 0.0018613	total: 8m 14s	remaining: 8m 39s
4529:	learn: 0.0020897	total: 8m 14s	remaining: 9m 56s
4729:	learn: 0.0021196	total: 8m 14s	remaining: 9m 10s
4868:	learn: 0.0019755	total: 8m 13s	remaining: 8m 40s
4874:	learn: 0.0018605	total: 8m 14s	remaining: 8m 39s
4964:	learn: 0.0018798	total: 8m 14s	remaining: 8m 21s
4730:	learn: 0.0021196	total: 8m 14s	remaining: 9m 10s
4875:	learn: 0.0018598	total: 8m 14s	remaining: 8m 39s
4869:	learn: 0.0019748	total: 8m 14s	remaining: 8m 40s
4530:	learn: 0.0020889	total: 8m 14s	remaining: 9m 56s
4965:	learn: 0.0018792	total: 8m 14s	remaining: 8m 20s
4531:	learn: 0.0020880	total: 8m 14s	remaining: 9m 56s
4731:	learn: 0.0021196	total: 8m 14s	remaining: 9m 10s
4870:	learn: 0.0019743	total: 8m 14s	remaining: 8m 40s
4876:	learn: 0.0018591	total: 8m 14s	remaining: 8m 39s
4966:	learn: 0.0018792	total: 8m 14s	remaining: 8m 20s
4532:	learn: 0.0020871	total: 8m 14s	remaining: 9m 56s
4732:	learn: 0.0021196	total: 8m 14s	remaining: 9m 10s
4967:	learn: 0.0018792	total: 8m 14s	remaining: 8m 20s
4871:	learn: 0.0019736	total: 8m 14s	remaining: 8m 40s
4877:	learn: 0.0018591	total: 8m 14s	remaining: 8m 39s
4533:	learn: 0.0020864	total: 8m 14s	remaining: 9m 56s
4733:	learn: 0.0021196	total: 8m 14s	remaining: 9m 10s
4968:	learn: 0.0018792	total: 8m 14s	remaining: 8m 20s
4872:	learn: 0.0019728	total: 8m 14s	remaining: 8m 40s
4878:	learn: 0.0018591	total: 8m 14s	remaining: 8m 39s
4734:	learn: 0.0021196	total: 8m 14s	remaining: 9m 9s
4534:	learn: 0.0020852	total: 8m 14s	remaining: 9m 56s
4879:	learn: 0.0018580	total: 8m 14s	remaining: 8m 38s
4969:	learn: 0.0018792	total: 8m 14s	remaining: 8m 20s
4873:	learn: 0.0019723	total: 8m 14s	remaining: 8m 40s
4735:	learn: 0.0021188	total: 8m 14s	remaining: 9m 9s
4535:	learn: 0.0020852	total: 8m 14s	remaining: 9m 55s
4874:	learn: 0.0019715	total: 8m 14s	remaining: 8m 39s
4880:	learn: 0.0018577	total: 8m 14s	remaining: 8m 38s
4970:	learn: 0.0018792	total: 8m 14s	remaining: 8m 20s
4736:	learn: 0.0021180	total: 8m 14s	remaining: 9m 9s
4536:	learn: 0.0020845	total: 8m 14s	remaining: 9m 55s
4875:	learn: 0.0019710	total: 8m 14s	remaining: 8m 39s
4881:	learn: 0.0018569	total: 8m 14s	remaining: 8m 38s
4971:	learn: 0.0018792	total: 8m 14s	remaining: 8m 20s
4876:	learn: 0.0019704	total: 8m 14s	remaining: 8m 39s
4737:	learn: 0.0021180	total: 8m 14s	remaining: 9m 9s
4537:	learn: 0.0020841	total: 8m 14s	remaining: 9m 55s
4882:	learn: 0.0018566	total: 8m 14s	remaining: 8m 38s
4972:	learn: 0.0018788	total: 8m 14s	remaining: 8m 20s
4738:	learn: 0.0021180	total: 8m 14s	remaining: 9m 9s
4877:	learn: 0.0019699	total: 8m 14s	remaining: 8m 39s
4883:	learn: 0.0018566	total: 8m 14s	remaining: 8m 38s
4538:	learn: 0.0020841	total: 8m 15s	remaining: 9m 55s
4973:	learn: 0.0018788	total: 8m 15s	remaining: 8m 20s
4884:	learn: 0.0018566	total: 8m 15s	remaining: 8m 38s
4878:	learn: 0.0019692	total: 8m 14s	remaining: 8m 39s
4739:	learn: 0.0021180	total: 8m 15s	remaining: 9m 9s
4539:	learn: 0.0020833	total: 8m 15s	remaining: 9m 55s
4974:	learn: 0.0018782	total: 8m 15s	remaining: 8m 20s
4879:	learn: 0.0019686	total: 8m 15s	remaining: 8m 39s
4885:	learn: 0.0018566	total: 8m 15s	remaining: 8m 38s
4740:	learn: 0.0021180	total: 8m 15s	remaining: 9m 9s
4540:	learn: 0.0020828	total: 8m 15s	remaining: 9m 55s
4975:	learn: 0.0018778	total: 8m 15s	remaining: 8m 19s
4880:	learn: 0.0019681	total: 8m 15s	remaining: 8m 39s
4741:	learn: 0.0021180	total: 8m 15s	remaining: 9m 9s
4886:	learn: 0.0018560	total: 8m 15s	remaining: 8m 38s
4976:	learn: 0.0018771	total: 8m 15s	remaining: 8m 19s
4541:	learn: 0.0020821	total: 8m 15s	remaining: 9m 55s
4881:	learn: 0.0019677	total: 8m 15s	remaining: 8m 39s
4887:	learn: 0.0018560	total: 8m 15s	remaining: 8m 38s
4977:	learn: 0.0018767	total: 8m 15s	remaining: 8m 19s
4742:	learn: 0.0021180	total: 8m 15s	remaining: 9m 9s
4542:	learn: 0.0020814	total: 8m 15s	remaining: 9m 55s
4882:	learn: 0.0019669	total: 8m 15s	remaining: 8m 39s
4888:	learn: 0.0018554	total: 8m 15s	remaining: 8m 37s
4743:	learn: 0.0021175	total: 8m 15s	remaining: 9m 8s
4978:	learn: 0.0018762	total: 8m 15s	remaining: 8m 19s
4883:	learn: 0.0019663	total: 8m 15s	remaining: 8m 38s
4543:	learn: 0.0020807	total: 8m 15s	remaining: 9m 55s
4889:	learn: 0.0018551	total: 8m 15s	remaining: 8m 37s
4884:	learn: 0.0019658	total: 8m 15s	remaining: 8m 38s
4744:	learn: 0.0021175	total: 8m 15s	remaining: 9m 8s
4979:	learn: 0.0018762	total: 8m 15s	remaining: 8m 19s
4544:	learn: 0.0020803	total: 8m 15s	remaining: 9m 54s
4885:	learn: 0.0019652	total: 8m 15s	remaining: 8m 38s
4745:	learn: 0.0021175	total: 8m 15s	remaining: 9m 8s
4890:	learn: 0.0018551	total: 8m 15s	remaining: 8m 37s
4980:	learn: 0.0018757	total: 8m 15s	remaining: 8m 19s
4545:	learn: 0.0020803	total: 8m 15s	remaining: 9m 54s
4891:	learn: 0.0018551	total: 8m 15s	remaining: 8m 37s
4886:	learn: 0.0019648	total: 8m 15s	remaining: 8m 38s
4746:	learn: 0.0021174	total: 8m 15s	remaining: 9m 8s
4981:	learn: 0.0018757	total: 8m 15s	remaining: 8m 19s
4892:	learn: 0.0018551	total: 8m 15s	remaining: 8m 37s
4887:	learn: 0.0019643	total: 8m 15s	remaining: 8m 38s
4546:	learn: 0.0020799	total: 8m 15s	remaining: 9m 54s
4747:	learn: 0.0021174	total: 8m 15s	remaining: 9m 8s
4893:	learn: 0.0018551	total: 8m 15s	remaining: 8m 37s
4982:	learn: 0.0018757	total: 8m 15s	remaining: 8m 19s
4888:	learn: 0.0019637	total: 8m 15s	remaining: 8m 38s
4547:	learn: 0.0020799	total: 8m 16s	remaining: 9m 54s
4748:	learn: 0.0021174	total: 8m 16s	remaining: 9m 8s
4983:	learn: 0.0018757	total: 8m 16s	remaining: 8m 19s
4894:	learn: 0.0018551	total: 8m 16s	remaining: 8m 37s
4889:	learn: 0.0019632	total: 8m 15s	remaining: 8m 38s
4749:	learn: 0.0021174	total: 8m 16s	remaining: 9m 8s
4548:	learn: 0.0020799	total: 8m 16s	remaining: 9m 54s
4984:	learn: 0.0018755	total: 8m 16s	remaining: 8m 19s
4895:	learn: 0.0018551	total: 8m 16s	remaining: 8m 37s
4890:	learn: 0.0019626	total: 8m 16s	remaining: 8m 38s
4750:	learn: 0.0021175	total: 8m 16s	remaining: 9m 8s
4985:	learn: 0.0018755	total: 8m 16s	remaining: 8m 18s
4896:	learn: 0.0018551	total: 8m 16s	remaining: 8m 37s
4549:	learn: 0.0020796	total: 8m 16s	remaining: 9m 54s
4986:	learn: 0.0018748	total: 8m 16s	remaining: 8m 18s
4891:	learn: 0.0019620	total: 8m 16s	remaining: 8m 38s
4751:	learn: 0.0021175	total: 8m 16s	remaining: 9m 8s
4897:	learn: 0.0018551	total: 8m 16s	remaining: 8m 36s
4987:	learn: 0.0018748	total: 8m 16s	remaining: 8m 18s
4550:	learn: 0.0020790	total: 8m 16s	remaining: 9m 54s
4898:	learn: 0.0018551	total: 8m 16s	remaining: 8m 36s
4892:	learn: 0.0019618	total: 8m 16s	remaining: 8m 37s
4752:	learn: 0.0021174	total: 8m 16s	remaining: 9m 8s
4988:	learn: 0.0018743	total: 8m 16s	remaining: 8m 18s
4551:	learn: 0.0020784	total: 8m 16s	remaining: 9m 54s
4899:	learn: 0.0018544	total: 8m 16s	remaining: 8m 36s
4893:	learn: 0.0019612	total: 8m 16s	remaining: 8m 37s
4753:	learn: 0.0021174	total: 8m 16s	remaining: 9m 7s
4989:	learn: 0.0018738	total: 8m 16s	remaining: 8m 18s
4552:	learn: 0.0020784	total: 8m 16s	remaining: 9m 54s
4900:	learn: 0.0018538	total: 8m 16s	remaining: 8m 36s
4894:	learn: 0.0019608	total: 8m 16s	remaining: 8m 37s
4754:	learn: 0.0021175	total: 8m 16s	remaining: 9m 7s
4990:	learn: 0.0018738	total: 8m 16s	remaining: 8m 18s
4553:	learn: 0.0020775	total: 8m 16s	remaining: 9m 54s
4901:	learn: 0.0018538	total: 8m 16s	remaining: 8m 36s
4895:	learn: 0.0019604	total: 8m 16s	remaining: 8m 37s
4755:	learn: 0.0021175	total: 8m 16s	remaining: 9m 7s
4991:	learn: 0.0018738	total: 8m 16s	remaining: 8m 18s
4554:	learn: 0.0020768	total: 8m 16s	remaining: 9m 53s
4902:	learn: 0.0018538	total: 8m 16s	remaining: 8m 36s
4756:	learn: 0.0021175	total: 8m 16s	remaining: 9m 7s
4896:	learn: 0.0019599	total: 8m 16s	remaining: 8m 37s
4992:	learn: 0.0018738	total: 8m 16s	remaining: 8m 18s
4555:	learn: 0.0020761	total: 8m 16s	remaining: 9m 53s
4757:	learn: 0.0021175	total: 8m 16s	remaining: 9m 7s
4903:	learn: 0.0018530	total: 8m 16s	remaining: 8m 36s
4897:	learn: 0.0019591	total: 8m 16s	remaining: 8m 37s
4556:	learn: 0.0020757	total: 8m 17s	remaining: 9m 53s
4993:	learn: 0.0018733	total: 8m 16s	remaining: 8m 18s
4758:	learn: 0.0021174	total: 8m 16s	remaining: 9m 7s
4898:	learn: 0.0019585	total: 8m 16s	remaining: 8m 37s
4904:	learn: 0.0018524	total: 8m 17s	remaining: 8m 36s
4557:	learn: 0.0020751	total: 8m 17s	remaining: 9m 53s
4759:	learn: 0.0021174	total: 8m 17s	remaining: 9m 7s
4994:	learn: 0.0018725	total: 8m 17s	remaining: 8m 18s
4899:	learn: 0.0019580	total: 8m 16s	remaining: 8m 37s
4558:	learn: 0.0020747	total: 8m 17s	remaining: 9m 53s
4905:	learn: 0.0018524	total: 8m 17s	remaining: 8m 36s
4760:	learn: 0.0021174	total: 8m 17s	remaining: 9m 7s
4900:	learn: 0.0019575	total: 8m 17s	remaining: 8m 37s
4995:	learn: 0.0018718	total: 8m 17s	remaining: 8m 17s
4559:	learn: 0.0020739	total: 8m 17s	remaining: 9m 53s
4906:	learn: 0.0018524	total: 8m 17s	remaining: 8m 36s
4901:	learn: 0.0019568	total: 8m 17s	remaining: 8m 37s
4996:	learn: 0.0018718	total: 8m 17s	remaining: 8m 17s
4761:	learn: 0.0021165	total: 8m 17s	remaining: 9m 7s
4560:	learn: 0.0020731	total: 8m 17s	remaining: 9m 53s
4997:	learn: 0.0018718	total: 8m 17s	remaining: 8m 17s
4907:	learn: 0.0018524	total: 8m 17s	remaining: 8m 36s
4902:	learn: 0.0019563	total: 8m 17s	remaining: 8m 36s
4762:	learn: 0.0021161	total: 8m 17s	remaining: 9m 6s
4561:	learn: 0.0020731	total: 8m 17s	remaining: 9m 53s
4998:	learn: 0.0018718	total: 8m 17s	remaining: 8m 17s
4908:	learn: 0.0018524	total: 8m 17s	remaining: 8m 35s
4903:	learn: 0.0019556	total: 8m 17s	remaining: 8m 36s
4763:	learn: 0.0021161	total: 8m 17s	remaining: 9m 6s
4909:	learn: 0.0018524	total: 8m 17s	remaining: 8m 35s
4999:	learn: 0.0018718	total: 8m 17s	remaining: 8m 17s
4904:	learn: 0.0019550	total: 8m 17s	remaining: 8m 36s
4562:	learn: 0.0020731	total: 8m 17s	remaining: 9m 52s
4764:	learn: 0.0021161	total: 8m 17s	remaining: 9m 6s
4905:	learn: 0.0019541	total: 8m 17s	remaining: 8m 36s
5000:	learn: 0.0018713	total: 8m 17s	remaining: 8m 17s
4910:	learn: 0.0018524	total: 8m 17s	remaining: 8m 35s
4765:	learn: 0.0021161	total: 8m 17s	remaining: 9m 6s
4906:	learn: 0.0019536	total: 8m 17s	remaining: 8m 36s
4563:	learn: 0.0020731	total: 8m 17s	remaining: 9m 52s
5001:	learn: 0.0018708	total: 8m 17s	remaining: 8m 17s
4911:	learn: 0.0018524	total: 8m 17s	remaining: 8m 35s
4907:	learn: 0.0019527	total: 8m 17s	remaining: 8m 36s
4766:	learn: 0.0021161	total: 8m 17s	remaining: 9m 6s
4564:	learn: 0.0020731	total: 8m 17s	remaining: 9m 52s
4908:	learn: 0.0019520	total: 8m 17s	remaining: 8m 36s
5002:	learn: 0.0018703	total: 8m 17s	remaining: 8m 17s
4767:	learn: 0.0021161	total: 8m 17s	remaining: 9m 6s
4912:	learn: 0.0018517	total: 8m 17s	remaining: 8m 35s
4565:	learn: 0.0020720	total: 8m 17s	remaining: 9m 52s
4909:	learn: 0.0019515	total: 8m 17s	remaining: 8m 36s

4768:	learn: 0.0021161	total: 8m 18s	remaining: 9m 6s
4913:	learn: 0.0018517	total: 8m 18s	remaining: 8m 35s
5003:	learn: 0.0018703	total: 8m 18s	remaining: 8m 17s
4566:	learn: 0.0020713	total: 8m 18s	remaining: 9m 52s
4910:	learn: 0.0019511	total: 8m 17s	remaining: 8m 35s
4769:	learn: 0.0021161	total: 8m 18s	remaining: 9m 6s
5004:	learn: 0.0018703	total: 8m 18s	remaining: 8m 17s
4567:	learn: 0.0020706	total: 8m 18s	remaining: 9m 52s
4914:	learn: 0.0018517	total: 8m 18s	remaining: 8m 35s
4911:	learn: 0.0019503	total: 8m 18s	remaining: 8m 35s
4770:	learn: 0.0021161	total: 8m 18s	remaining: 9m 6s
5005:	learn: 0.0018697	total: 8m 18s	remaining: 8m 16s
4568:	learn: 0.0020699	total: 8m 18s	remaining: 9m 52s
4915:	learn: 0.0018511	total: 8m 18s	remaining: 8m 35s
4912:	learn: 0.0019498	total: 8m 18s	remaining: 8m 35s
5006:	learn: 0.0018691	total: 8m 18s	remaining: 8m 16s
4771:	learn: 0.0021161	total: 8m 18s	remaining: 9m 5s
4569:	learn: 0.0020692	total: 8m 18s	remaining: 9m 52s
4916:	learn: 0.0018511	total: 8m 18s	remaining: 8m 35s
5007:	learn: 0.0018686	total: 8m 18s	remaining: 8m 16s
4772:	learn: 0.0021161	total: 8m 18s	remaining: 9m 5s
4913:	learn: 0.0019492	total: 8m 18s	remaining: 8m 35s
4917:	learn: 0.0018508	total: 8m 18s	remaining: 8m 35s
4570:	learn: 0.0020681	total: 8m 18s	remaining: 9m 52s
5008:	learn: 0.0018686	total: 8m 18s	remaining: 8m 16s
4914:	learn: 0.0019485	total: 8m 18s	remaining: 8m 35s
4918:	learn: 0.0018501	total: 8m 18s	remaining: 8m 34s
4773:	learn: 0.0021161	total: 8m 18s	remaining: 9m 5s
4571:	learn: 0.0020674	total: 8m 18s	remaining: 9m 51s
5009:	learn: 0.0018682	total: 8m 18s	remaining: 8m 16s
4915:	learn: 0.0019479	total: 8m 18s	remaining: 8m 35s
4774:	learn: 0.0021161	total: 8m 18s	remaining: 9m 5s
4572:	learn: 0.0020667	total: 8m 18s	remaining: 9m 51s
4919:	learn: 0.0018501	total: 8m 18s	remaining: 8m 34s
5010:	learn: 0.0018675	total: 8m 18s	remaining: 8m 16s
4916:	learn: 0.0019473	total: 8m 18s	remaining: 8m 35s
4775:	learn: 0.0021161	total: 8m 18s	remaining: 9m 5s
4920:	learn: 0.0018501	total: 8m 18s	remaining: 8m 34s
4573:	learn: 0.0020667	total: 8m 18s	remaining: 9m 51s
4917:	learn: 0.0019465	total: 8m 18s	remaining: 8m 35s
5011:	learn: 0.0018669	total: 8m 18s	remaining: 8m 16s
4776:	learn: 0.0021161	total: 8m 18s	remaining: 9m 5s
5012:	learn: 0.0018669	total: 8m 18s	remaining: 8m 16s
4921:	learn: 0.0018501	total: 8m 18s	remaining: 8m 34s
4918:	learn: 0.0019458	total: 8m 18s	remaining: 8m 35s
4574:	learn: 0.0020653	total: 8m 18s	remaining: 9m 51s
4777:	learn: 0.0021161	total: 8m 18s	remaining: 9m 5s
4922:	learn: 0.0018501	total: 8m 18s	remaining: 8m 34s
5013:	learn: 0.0018665	total: 8m 18s	remaining: 8m 16s
4778:	learn: 0.0021161	total: 8m 19s	remaining: 9m 5s
4919:	learn: 0.0019457	total: 8m 18s	remaining: 8m 35s
4575:	learn: 0.0020648	total: 8m 19s	remaining: 9m 51s
5014:	learn: 0.0018660	total: 8m 19s	remaining: 8m 16s
4779:	learn: 0.0021161	total: 8m 19s	remaining: 9m 5s
4576:	learn: 0.0020646	total: 8m 19s	remaining: 9m 51s
4923:	learn: 0.0018501	total: 8m 19s	remaining: 8m 34s
4920:	learn: 0.0019451	total: 8m 18s	remaining: 8m 35s
5015:	learn: 0.0018654	total: 8m 19s	remaining: 8m 15s
4780:	learn: 0.0021153	total: 8m 19s	remaining: 9m 4s
4577:	learn: 0.0020646	total: 8m 19s	remaining: 9m 51s
4921:	learn: 0.0019441	total: 8m 19s	remaining: 8m 34s
4924:	learn: 0.0018498	total: 8m 19s	remaining: 8m 34s
5016:	learn: 0.0018646	total: 8m 19s	remaining: 8m 15s
4578:	learn: 0.0020640	total: 8m 19s	remaining: 9m 51s
4781:	learn: 0.0021153	total: 8m 19s	remaining: 9m 4s
4925:	learn: 0.0018498	total: 8m 19s	remaining: 8m 34s
4922:	learn: 0.0019436	total: 8m 19s	remaining: 8m 34s
5017:	learn: 0.0018639	total: 8m 19s	remaining: 8m 15s
4579:	learn: 0.0020633	total: 8m 19s	remaining: 9m 51s
4782:	learn: 0.0021153	total: 8m 19s	remaining: 9m 4s
4923:	learn: 0.0019432	total: 8m 19s	remaining: 8m 34s
4926:	learn: 0.0018498	total: 8m 19s	remaining: 8m 34s
5018:	learn: 0.0018639	total: 8m 19s	remaining: 8m 15s
4783:	learn: 0.0021153	total: 8m 19s	remaining: 9m 4s
4580:	learn: 0.0020624	total: 8m 19s	remaining: 9m 50s
4924:	learn: 0.0019426	total: 8m 19s	remaining: 8m 34s
5019:	learn: 0.0018634	total: 8m 19s	remaining: 8m 15s
4927:	learn: 0.0018498	total: 8m 19s	remaining: 8m 34s
4784:	learn: 0.0021151	total: 8m 19s	remaining: 9m 4s
4581:	learn: 0.0020619	total: 8m 19s	remaining: 9m 50s
4925:	learn: 0.0019417	total: 8m 19s	remaining: 8m 34s
4928:	learn: 0.0018498	total: 8m 19s	remaining: 8m 34s
5020:	learn: 0.0018634	total: 8m 19s	remaining: 8m 15s
4785:	learn: 0.0021143	total: 8m 19s	remaining: 9m 4s
4926:	learn: 0.0019417	total: 8m 19s	remaining: 8m 34s
4929:	learn: 0.0018491	total: 8m 19s	remaining: 8m 33s
4582:	learn: 0.0020610	total: 8m 19s	remaining: 9m 50s
4786:	learn: 0.0021143	total: 8m 19s	remaining: 9m 4s
5021:	learn: 0.0018634	total: 8m 19s	remaining: 8m 15s
4583:	learn: 0.0020602	total: 8m 19s	remaining: 9m 50s
4927:	learn: 0.0019413	total: 8m 19s	remaining: 8m 34s
4930:	learn: 0.0018489	total: 8m 19s	remaining: 8m 33s
5022:	learn: 0.0018631	total: 8m 19s	remaining: 8m 15s
4787:	learn: 0.0021143	total: 8m 19s	remaining: 9m 4s
4928:	learn: 0.0019408	total: 8m 19s	remaining: 8m 34s
4931:	learn: 0.0018489	total: 8m 19s	remaining: 8m 33s
4584:	learn: 0.0020595	total: 8m 19s	remaining: 9m 50s
5023:	learn: 0.0018623	total: 8m 19s	remaining: 8m 15s
4788:	learn: 0.0021143	total: 8m 19s	remaining: 9m 4s
4929:	learn: 0.0019403	total: 8m 19s	remaining: 8m 34s
4932:	learn: 0.0018489	total: 8m 20s	remaining: 8m 33s
5024:	learn: 0.0018623	total: 8m 20s	remaining: 8m 15s
4789:	learn: 0.0021135	total: 8m 20s	remaining: 9m 3s
4585:	learn: 0.0020595	total: 8m 20s	remaining: 9m 50s
4933:	learn: 0.0018489	total: 8m 20s	remaining: 8m 33s
4930:	learn: 0.0019398	total: 8m 19s	remaining: 8m 33s
4790:	learn: 0.0021135	total: 8m 20s	remaining: 9m 3s
5025:	learn: 0.0018619	total: 8m 20s	remaining: 8m 14s
4586:	learn: 0.0020586	total: 8m 20s	remaining: 9m 50s
4934:	learn: 0.0018489	total: 8m 20s	remaining: 8m 33s
4931:	learn: 0.0019393	total: 8m 20s	remaining: 8m 33s
5026:	learn: 0.0018613	total: 8m 20s	remaining: 8m 14s
4791:	learn: 0.0021135	total: 8m 20s	remaining: 9m 3s
4587:	learn: 0.0020578	total: 8m 20s	remaining: 9m 50s
4932:	learn: 0.0019389	total: 8m 20s	remaining: 8m 33s
5027:	learn: 0.0018611	total: 8m 20s	remaining: 8m 14s
4935:	learn: 0.0018489	total: 8m 20s	remaining: 8m 33s
4792:	learn: 0.0021135	total: 8m 20s	remaining: 9m 3s
4588:	learn: 0.0020569	total: 8m 20s	remaining: 9m 50s
4933:	learn: 0.0019385	total: 8m 20s	remaining: 8m 33s
5028:	learn: 0.0018611	total: 8m 20s	remaining: 8m 14s
4936:	learn: 0.0018489	total: 8m 20s	remaining: 8m 33s
4589:	learn: 0.0020564	total: 8m 20s	remaining: 9m 49s
4793:	learn: 0.0021126	total: 8m 20s	remaining: 9m 3s
4934:	learn: 0.0019378	total: 8m 20s	remaining: 8m 33s
5029:	learn: 0.0018611	total: 8m 20s	remaining: 8m 14s
4937:	learn: 0.0018481	total: 8m 20s	remaining: 8m 33s
4590:	learn: 0.0020564	total: 8m 20s	remaining: 9m 49s
4935:	learn: 0.0019370	total: 8m 20s	remaining: 8m 33s
5030:	learn: 0.0018608	total: 8m 20s	remaining: 8m 14s
4794:	learn: 0.0021118	total: 8m 20s	remaining: 9m 3s
4938:	learn: 0.0018476	total: 8m 20s	remaining: 8m 33s
4591:	learn: 0.0020558	total: 8m 20s	remaining: 9m 49s
5031:	learn: 0.0018608	total: 8m 20s	remaining: 8m 14s
4936:	learn: 0.0019366	total: 8m 20s	remaining: 8m 33s
4592:	learn: 0.0020550	total: 8m 20s	remaining: 9m 49s
4939:	learn: 0.0018476	total: 8m 20s	remaining: 8m 32s
4795:	learn: 0.0021118	total: 8m 20s	remaining: 9m 3s
4937:	learn: 0.0019360	total: 8m 20s	remaining: 8m 33s
5032:	learn: 0.0018608	total: 8m 20s	remaining: 8m 14s
4593:	learn: 0.0020538	total: 8m 20s	remaining: 9m 49s
4940:	learn: 0.0018476	total: 8m 20s	remaining: 8m 32s
4796:	learn: 0.0021118	total: 8m 20s	remaining: 9m 3s
4938:	learn: 0.0019355	total: 8m 20s	remaining: 8m 33s
5033:	learn: 0.0018608	total: 8m 20s	remaining: 8m 14s
4594:	learn: 0.0020538	total: 8m 20s	remaining: 9m 49s
4941:	learn: 0.0018470	total: 8m 20s	remaining: 8m 32s
4797:	learn: 0.0021118	total: 8m 20s	remaining: 9m 3s
4939:	learn: 0.0019350	total: 8m 20s	remaining: 8m 33s
5034:	learn: 0.0018608	total: 8m 20s	remaining: 8m 14s
4595:	learn: 0.0020531	total: 8m 21s	remaining: 9m 49s
4942:	learn: 0.0018470	total: 8m 21s	remaining: 8m 32s
4940:	learn: 0.0019346	total: 8m 20s	remaining: 8m 32s
4798:	learn: 0.0021118	total: 8m 21s	remaining: 9m 3s
5035:	learn: 0.0018608	total: 8m 21s	remaining: 8m 13s
4596:	learn: 0.0020524	total: 8m 21s	remaining: 9m 49s
4943:	learn: 0.0018463	total: 8m 21s	remaining: 8m 32s
4941:	learn: 0.0019342	total: 8m 21s	remaining: 8m 32s
5036:	learn: 0.0018608	total: 8m 21s	remaining: 8m 13s
4799:	learn: 0.0021118	total: 8m 21s	remaining: 9m 2s
4944:	learn: 0.0018457	total: 8m 21s	remaining: 8m 32s
4597:	learn: 0.0020524	total: 8m 21s	remaining: 9m 48s
5037:	learn: 0.0018607	total: 8m 21s	remaining: 8m 13s
4942:	learn: 0.0019337	total: 8m 21s	remaining: 8m 32s
4598:	learn: 0.0020521	total: 8m 21s	remaining: 9m 48s
4945:	learn: 0.0018457	total: 8m 21s	remaining: 8m 32s
4800:	learn: 0.0021118	total: 8m 21s	remaining: 9m 2s
4943:	learn: 0.0019330	total: 8m 21s	remaining: 8m 32s
5038:	learn: 0.0018601	total: 8m 21s	remaining: 8m 13s
4946:	learn: 0.0018457	total: 8m 21s	remaining: 8m 32s
4599:	learn: 0.0020513	total: 8m 21s	remaining: 9m 48s
4801:	learn: 0.0021118	total: 8m 21s	remaining: 9m 2s
4944:	learn: 0.0019324	total: 8m 21s	remaining: 8m 32s
5039:	learn: 0.0018596	total: 8m 21s	remaining: 8m 13s
4947:	learn: 0.0018457	total: 8m 21s	remaining: 8m 32s
4802:	learn: 0.0021118	total: 8m 21s	remaining: 9m 2s
4600:	learn: 0.0020513	total: 8m 21s	remaining: 9m 48s
4945:	learn: 0.0019319	total: 8m 21s	remaining: 8m 32s
4948:	learn: 0.0018457	total: 8m 21s	remaining: 8m 31s
5040:	learn: 0.0018591	total: 8m 21s	remaining: 8m 13s
4803:	learn: 0.0021116	total: 8m 21s	remaining: 9m 2s
4601:	learn: 0.0020506	total: 8m 21s	remaining: 9m 48s
5041:	learn: 0.0018585	total: 8m 21s	remaining: 8m 13s
4946:	learn: 0.0019319	total: 8m 21s	remaining: 8m 32s
4949:	learn: 0.0018457	total: 8m 21s	remaining: 8m 31s
4804:	learn: 0.0021116	total: 8m 21s	remaining: 9m 2s
5042:	learn: 0.0018586	total: 8m 21s	remaining: 8m 13s
4602:	learn: 0.0020499	total: 8m 21s	remaining: 9m 48s
4947:	learn: 0.0019315	total: 8m 21s	remaining: 8m 32s
4950:	learn: 0.0018450	total: 8m 21s	remaining: 8m 31s
5043:	learn: 0.0018585	total: 8m 21s	remaining: 8m 13s
4805:	learn: 0.0021116	total: 8m 21s	remaining: 9m 2s
4948:	learn: 0.0019315	total: 8m 21s	remaining: 8m 32s
4603:	learn: 0.0020495	total: 8m 21s	remaining: 9m 48s
4951:	learn: 0.0018450	total: 8m 21s	remaining: 8m 31s
5044:	learn: 0.0018579	total: 8m 21s	remaining: 8m 12s
4806:	learn: 0.0021116	total: 8m 21s	remaining: 9m 2s
4949:	learn: 0.0019310	total: 8m 21s	remaining: 8m 32s
4952:	learn: 0.0018451	total: 8m 22s	remaining: 8m 31s
4604:	learn: 0.0020489	total: 8m 22s	remaining: 9m 48s
5045:	learn: 0.0018577	total: 8m 21s	remaining: 8m 12s
4807:	learn: 0.0021116	total: 8m 22s	remaining: 9m 2s
4605:	learn: 0.0020489	total: 8m 22s	remaining: 9m 48s
4950:	learn: 0.0019306	total: 8m 21s	remaining: 8m 31s
4953:	learn: 0.0018450	total: 8m 22s	remaining: 8m 31s
4808:	learn: 0.0021116	total: 8m 22s	remaining: 9m 2s
5046:	learn: 0.0018577	total: 8m 22s	remaining: 8m 12s
4606:	learn: 0.0020485	total: 8m 22s	remaining: 9m 47s
4954:	learn: 0.0018444	total: 8m 22s	remaining: 8m 31s
4951:	learn: 0.0019300	total: 8m 22s	remaining: 8m 31s
4607:	learn: 0.0020483	total: 8m 22s	remaining: 9m 47s
4809:	learn: 0.0021109	total: 8m 22s	remaining: 9m 1s
5047:	learn: 0.0018569	total: 8m 22s	remaining: 8m 12s
4952:	learn: 0.0019294	total: 8m 22s	remaining: 8m 31s
4955:	learn: 0.0018444	total: 8m 22s	remaining: 8m 31s
4810:	learn: 0.0021109	total: 8m 22s	remaining: 9m 1s
4608:	learn: 0.0020476	total: 8m 22s	remaining: 9m 47s
5048:	learn: 0.0018569	total: 8m 22s	remaining: 8m 12s
4811:	learn: 0.0021109	total: 8m 22s	remaining: 9m 1s
4953:	learn: 0.0019289	total: 8m 22s	remaining: 8m 31s
4956:	learn: 0.0018437	total: 8m 22s	remaining: 8m 31s
4954:	learn: 0.0019283	total: 8m 22s	remaining: 8m 31s
4609:	learn: 0.0020473	total: 8m 22s	remaining: 9m 47s
5049:	learn: 0.0018564	total: 8m 22s	remaining: 8m 12s
4812:	learn: 0.0021109	total: 8m 22s	remaining: 9m 1s
4957:	learn: 0.0018437	total: 8m 22s	remaining: 8m 31s
4955:	learn: 0.0019279	total: 8m 22s	remaining: 8m 31s
4610:	learn: 0.0020473	total: 8m 22s	remaining: 9m 47s
5050:	learn: 0.0018564	total: 8m 22s	remaining: 8m 12s
4813:	learn: 0.0021108	total: 8m 22s	remaining: 9m 1s
4958:	learn: 0.0018437	total: 8m 22s	remaining: 8m 30s
4611:	learn: 0.0020467	total: 8m 22s	remaining: 9m 47s
4956:	learn: 0.0019274	total: 8m 22s	remaining: 8m 31s
5051:	learn: 0.0018564	total: 8m 22s	remaining: 8m 12s
4814:	learn: 0.0021100	total: 8m 22s	remaining: 9m 1s
4959:	learn: 0.0018437	total: 8m 22s	remaining: 8m 30s
4815:	learn: 0.0021095	total: 8m 22s	remaining: 9m 1s
5052:	learn: 0.0018559	total: 8m 22s	remaining: 8m 12s
4612:	learn: 0.0020461	total: 8m 22s	remaining: 9m 47s
4960:	learn: 0.0018437	total: 8m 22s	remaining: 8m 30s
4957:	learn: 0.0019268	total: 8m 22s	remaining: 8m 31s
5053:	learn: 0.0018553	total: 8m 22s	remaining: 8m 12s
4816:	learn: 0.0021095	total: 8m 22s	remaining: 9m 1s
4958:	learn: 0.0019265	total: 8m 22s	remaining: 8m 31s
4961:	learn: 0.0018437	total: 8m 22s	remaining: 8m 30s
4613:	learn: 0.0020453	total: 8m 22s	remaining: 9m 47s
5054:	learn: 0.0018547	total: 8m 22s	remaining: 8m 12s
4959:	learn: 0.0019261	total: 8m 22s	remaining: 8m 30s
4962:	learn: 0.0018437	total: 8m 23s	remaining: 8m 30s
4817:	learn: 0.0021095	total: 8m 23s	remaining: 9m 1s
4614:	learn: 0.0020447	total: 8m 23s	remaining: 9m 46s
4963:	learn: 0.0018437	total: 8m 23s	remaining: 8m 30s
4818:	learn: 0.0021095	total: 8m 23s	remaining: 9m
5055:	learn: 0.0018547	total: 8m 23s	remaining: 8m 11s
4960:	learn: 0.0019256	total: 8m 22s	remaining: 8m 30s
4615:	learn: 0.0020442	total: 8m 23s	remaining: 9m 46s
4819:	learn: 0.0021095	total: 8m 23s	remaining: 9m
4964:	learn: 0.0018437	total: 8m 23s	remaining: 8m 30s
5056:	learn: 0.0018542	total: 8m 23s	remaining: 8m 11s
4961:	learn: 0.0019251	total: 8m 23s	remaining: 8m 30s
4616:	learn: 0.0020437	total: 8m 23s	remaining: 9m 46s
4820:	learn: 0.0021095	total: 8m 23s	remaining: 9m
4965:	learn: 0.0018437	total: 8m 23s	remaining: 8m 30s
5057:	learn: 0.0018542	total: 8m 23s	remaining: 8m 11s
4962:	learn: 0.0019251	total: 8m 23s	remaining: 8m 30s
4617:	learn: 0.0020431	total: 8m 23s	remaining: 9m 46s
4966:	learn: 0.0018437	total: 8m 23s	remaining: 8m 30s
4821:	learn: 0.0021095	total: 8m 23s	remaining: 9m
4963:	learn: 0.0019251	total: 8m 23s	remaining: 8m 30s
5058:	learn: 0.0018542	total: 8m 23s	remaining: 8m 11s
4967:	learn: 0.0018431	total: 8m 23s	remaining: 8m 29s
4822:	learn: 0.0021095	total: 8m 23s	remaining: 9m
4964:	learn: 0.0019245	total: 8m 23s	remaining: 8m 30s
5059:	learn: 0.0018542	total: 8m 23s	remaining: 8m 11s
4618:	learn: 0.0020424	total: 8m 23s	remaining: 9m 46s
4968:	learn: 0.0018431	total: 8m 23s	remaining: 8m 29s
4965:	learn: 0.0019242	total: 8m 23s	remaining: 8m 30s
4823:	learn: 0.0021095	total: 8m 23s	remaining: 9m
5060:	learn: 0.0018537	total: 8m 23s	remaining: 8m 11s
4969:	learn: 0.0018431	total: 8m 23s	remaining: 8m 29s
4619:	learn: 0.0020410	total: 8m 23s	remaining: 9m 46s
4824:	learn: 0.0021095	total: 8m 23s	remaining: 9m
4966:	learn: 0.0019238	total: 8m 23s	remaining: 8m 30s
5061:	learn: 0.0018537	total: 8m 23s	remaining: 8m 11s
4970:	learn: 0.0018431	total: 8m 23s	remaining: 8m 29s
4620:	learn: 0.0020410	total: 8m 23s	remaining: 9m 46s
4825:	learn: 0.0021095	total: 8m 23s	remaining: 9m
4971:	learn: 0.0018431	total: 8m 23s	remaining: 8m 29s
4967:	learn: 0.0019234	total: 8m 23s	remaining: 8m 30s
5062:	learn: 0.0018531	total: 8m 23s	remaining: 8m 11s
4621:	learn: 0.0020407	total: 8m 23s	remaining: 9m 46s
4972:	learn: 0.0018425	total: 8m 23s	remaining: 8m 29s
4826:	learn: 0.0021085	total: 8m 23s	remaining: 9m
5063:	learn: 0.0018531	total: 8m 23s	remaining: 8m 11s
4968:	learn: 0.0019227	total: 8m 23s	remaining: 8m 30s
4973:	learn: 0.0018425	total: 8m 23s	remaining: 8m 29s
4622:	learn: 0.0020399	total: 8m 23s	remaining: 9m 46s
4827:	learn: 0.0021085	total: 8m 23s	remaining: 8m 59s

4969:	learn: 0.0019221	total: 8m 23s	remaining: 8m 29s
4974:	learn: 0.0018425	total: 8m 24s	remaining: 8m 29s
5064:	learn: 0.0018529	total: 8m 24s	remaining: 8m 11s
4623:	learn: 0.0020395	total: 8m 24s	remaining: 9m 46s
4828:	learn: 0.0021085	total: 8m 24s	remaining: 8m 59s
4970:	learn: 0.0019216	total: 8m 23s	remaining: 8m 29s
4975:	learn: 0.0018425	total: 8m 24s	remaining: 8m 28s
5065:	learn: 0.0018524	total: 8m 24s	remaining: 8m 10s
4624:	learn: 0.0020389	total: 8m 24s	remaining: 9m 45s
4829:	learn: 0.0021085	total: 8m 24s	remaining: 8m 59s
4971:	learn: 0.0019211	total: 8m 24s	remaining: 8m 29s
5066:	learn: 0.0018524	total: 8m 24s	remaining: 8m 10s
4976:	learn: 0.0018422	total: 8m 24s	remaining: 8m 28s
4625:	learn: 0.0020383	total: 8m 24s	remaining: 9m 45s
4830:	learn: 0.0021085	total: 8m 24s	remaining: 8m 59s
5067:	learn: 0.0018524	total: 8m 24s	remaining: 8m 10s
4831:	learn: 0.0021085	total: 8m 24s	remaining: 8m 59s
4977:	learn: 0.0018422	total: 8m 24s	remaining: 8m 28s
4972:	learn: 0.0019204	total: 8m 24s	remaining: 8m 29s
4626:	learn: 0.0020383	total: 8m 24s	remaining: 9m 45s
5068:	learn: 0.0018519	total: 8m 24s	remaining: 8m 10s
4973:	learn: 0.0019200	total: 8m 24s	remaining: 8m 29s
4978:	learn: 0.0018422	total: 8m 24s	remaining: 8m 28s
4832:	learn: 0.0021085	total: 8m 24s	remaining: 8m 59s
4627:	learn: 0.0020383	total: 8m 24s	remaining: 9m 45s
5069:	learn: 0.0018513	total: 8m 24s	remaining: 8m 10s
4979:	learn: 0.0018422	total: 8m 24s	remaining: 8m 28s
4974:	learn: 0.0019197	total: 8m 24s	remaining: 8m 29s
4833:	learn: 0.0021085	total: 8m 24s	remaining: 8m 59s
4628:	learn: 0.0020376	total: 8m 24s	remaining: 9m 45s
5070:	learn: 0.0018513	total: 8m 24s	remaining: 8m 10s
4980:	learn: 0.0018422	total: 8m 24s	remaining: 8m 28s
4975:	learn: 0.0019193	total: 8m 24s	remaining: 8m 29s
4834:	learn: 0.0021085	total: 8m 24s	remaining: 8m 59s
4629:	learn: 0.0020370	total: 8m 24s	remaining: 9m 45s
4976:	learn: 0.0019193	total: 8m 24s	remaining: 8m 29s
4981:	learn: 0.0018415	total: 8m 24s	remaining: 8m 28s
5071:	learn: 0.0018508	total: 8m 24s	remaining: 8m 10s
4630:	learn: 0.0020369	total: 8m 24s	remaining: 9m 45s
4835:	learn: 0.0021085	total: 8m 24s	remaining: 8m 59s
4982:	learn: 0.0018415	total: 8m 24s	remaining: 8m 28s
4977:	learn: 0.0019193	total: 8m 24s	remaining: 8m 29s
5072:	learn: 0.0018504	total: 8m 24s	remaining: 8m 10s
4836:	learn: 0.0021085	total: 8m 24s	remaining: 8m 58s
4978:	learn: 0.0019189	total: 8m 24s	remaining: 8m 29s
4631:	learn: 0.0020359	total: 8m 24s	remaining: 9m 45s
4983:	learn: 0.0018415	total: 8m 24s	remaining: 8m 28s
5073:	learn: 0.0018498	total: 8m 24s	remaining: 8m 10s
4837:	learn: 0.0021085	total: 8m 24s	remaining: 8m 58s
4979:	learn: 0.0019182	total: 8m 24s	remaining: 8m 28s
4632:	learn: 0.0020359	total: 8m 25s	remaining: 9m 45s
4984:	learn: 0.0018415	total: 8m 25s	remaining: 8m 28s
5074:	learn: 0.0018494	total: 8m 25s	remaining: 8m 10s
4980:	learn: 0.0019178	total: 8m 24s	remaining: 8m 28s
4838:	learn: 0.0021085	total: 8m 25s	remaining: 8m 58s
4633:	learn: 0.0020356	total: 8m 25s	remaining: 9m 44s
4985:	learn: 0.0018415	total: 8m 25s	remaining: 8m 27s
5075:	learn: 0.0018494	total: 8m 25s	remaining: 8m 10s
4981:	learn: 0.0019172	total: 8m 25s	remaining: 8m 28s
4839:	learn: 0.0021085	total: 8m 25s	remaining: 8m 58s
4634:	learn: 0.0020349	total: 8m 25s	remaining: 9m 44s
4986:	learn: 0.0018411	total: 8m 25s	remaining: 8m 27s
4982:	learn: 0.0019167	total: 8m 25s	remaining: 8m 28s
5076:	learn: 0.0018489	total: 8m 25s	remaining: 8m 9s
4840:	learn: 0.0021085	total: 8m 25s	remaining: 8m 58s
4635:	learn: 0.0020343	total: 8m 25s	remaining: 9m 44s
4987:	learn: 0.0018411	total: 8m 25s	remaining: 8m 27s
5077:	learn: 0.0018488	total: 8m 25s	remaining: 8m 9s
4983:	learn: 0.0019161	total: 8m 25s	remaining: 8m 28s
4841:	learn: 0.0021077	total: 8m 25s	remaining: 8m 58s
4636:	learn: 0.0020337	total: 8m 25s	remaining: 9m 44s
4988:	learn: 0.0018411	total: 8m 25s	remaining: 8m 27s
4984:	learn: 0.0019154	total: 8m 25s	remaining: 8m 28s
5078:	learn: 0.0018488	total: 8m 25s	remaining: 8m 9s
4842:	learn: 0.0021077	total: 8m 25s	remaining: 8m 58s
4989:	learn: 0.0018405	total: 8m 25s	remaining: 8m 27s
4637:	learn: 0.0020330	total: 8m 25s	remaining: 9m 44s
4985:	learn: 0.0019148	total: 8m 25s	remaining: 8m 28s
5079:	learn: 0.0018482	total: 8m 25s	remaining: 8m 9s
4990:	learn: 0.0018402	total: 8m 25s	remaining: 8m 27s
4843:	learn: 0.0021077	total: 8m 25s	remaining: 8m 58s
4638:	learn: 0.0020322	total: 8m 25s	remaining: 9m 44s
5080:	learn: 0.0018482	total: 8m 25s	remaining: 8m 9s
4986:	learn: 0.0019143	total: 8m 25s	remaining: 8m 28s
4844:	learn: 0.0021077	total: 8m 25s	remaining: 8m 58s
4639:	learn: 0.0020315	total: 8m 25s	remaining: 9m 44s
4991:	learn: 0.0018399	total: 8m 25s	remaining: 8m 27s
4987:	learn: 0.0019140	total: 8m 25s	remaining: 8m 28s
5081:	learn: 0.0018482	total: 8m 25s	remaining: 8m 9s
4845:	learn: 0.0021077	total: 8m 25s	remaining: 8m 57s
4640:	learn: 0.0020309	total: 8m 25s	remaining: 9m 44s
4992:	learn: 0.0018391	total: 8m 25s	remaining: 8m 27s
4988:	learn: 0.0019134	total: 8m 25s	remaining: 8m 27s
5082:	learn: 0.0018482	total: 8m 25s	remaining: 8m 9s
4641:	learn: 0.0020302	total: 8m 25s	remaining: 9m 43s
4993:	learn: 0.0018391	total: 8m 25s	remaining: 8m 27s
4846:	learn: 0.0021077	total: 8m 25s	remaining: 8m 57s
5083:	learn: 0.0018477	total: 8m 25s	remaining: 8m 9s
4989:	learn: 0.0019129	total: 8m 25s	remaining: 8m 27s
4642:	learn: 0.0020296	total: 8m 26s	remaining: 9m 43s
4994:	learn: 0.0018391	total: 8m 26s	remaining: 8m 27s
4847:	learn: 0.0021077	total: 8m 26s	remaining: 8m 57s
5084:	learn: 0.0018477	total: 8m 26s	remaining: 8m 9s
4990:	learn: 0.0019124	total: 8m 25s	remaining: 8m 27s
4643:	learn: 0.0020286	total: 8m 26s	remaining: 9m 43s
4995:	learn: 0.0018383	total: 8m 26s	remaining: 8m 26s
5085:	learn: 0.0018473	total: 8m 26s	remaining: 8m 9s
4848:	learn: 0.0021077	total: 8m 26s	remaining: 8m 57s
4644:	learn: 0.0020274	total: 8m 26s	remaining: 9m 43s
4991:	learn: 0.0019118	total: 8m 26s	remaining: 8m 27s
4996:	learn: 0.0018384	total: 8m 26s	remaining: 8m 26s
5086:	learn: 0.0018468	total: 8m 26s	remaining: 8m 8s
4849:	learn: 0.0021077	total: 8m 26s	remaining: 8m 57s
4645:	learn: 0.0020274	total: 8m 26s	remaining: 9m 43s
4992:	learn: 0.0019118	total: 8m 26s	remaining: 8m 27s
5087:	learn: 0.0018463	total: 8m 26s	remaining: 8m 8s
4997:	learn: 0.0018384	total: 8m 26s	remaining: 8m 26s
4646:	learn: 0.0020274	total: 8m 26s	remaining: 9m 43s
4993:	learn: 0.0019112	total: 8m 26s	remaining: 8m 27s
4850:	learn: 0.0021077	total: 8m 26s	remaining: 8m 57s
4998:	learn: 0.0018384	total: 8m 26s	remaining: 8m 26s
5088:	learn: 0.0018458	total: 8m 26s	remaining: 8m 8s
4647:	learn: 0.0020268	total: 8m 26s	remaining: 9m 43s
4994:	learn: 0.0019106	total: 8m 26s	remaining: 8m 27s
4851:	learn: 0.0021077	total: 8m 26s	remaining: 8m 57s
4999:	learn: 0.0018377	total: 8m 26s	remaining: 8m 26s
4648:	learn: 0.0020268	total: 8m 26s	remaining: 9m 43s
5089:	learn: 0.0018457	total: 8m 26s	remaining: 8m 8s
4649:	learn: 0.0020268	total: 8m 26s	remaining: 9m 42s
5000:	learn: 0.0018370	total: 8m 26s	remaining: 8m 26s
4995:	learn: 0.0019102	total: 8m 26s	remaining: 8m 27s
4852:	learn: 0.0021077	total: 8m 26s	remaining: 8m 57s
5090:	learn: 0.0018458	total: 8m 26s	remaining: 8m 8s
4996:	learn: 0.0019098	total: 8m 26s	remaining: 8m 27s
5001:	learn: 0.0018370	total: 8m 26s	remaining: 8m 26s
4650:	learn: 0.0020267	total: 8m 26s	remaining: 9m 42s
4853:	learn: 0.0021077	total: 8m 26s	remaining: 8m 57s
5002:	learn: 0.0018363	total: 8m 26s	remaining: 8m 26s
5091:	learn: 0.0018458	total: 8m 26s	remaining: 8m 8s
4997:	learn: 0.0019093	total: 8m 26s	remaining: 8m 27s
5003:	learn: 0.0018363	total: 8m 26s	remaining: 8m 26s
4651:	learn: 0.0020266	total: 8m 26s	remaining: 9m 42s
4854:	learn: 0.0021077	total: 8m 26s	remaining: 8m 57s
4998:	learn: 0.0019089	total: 8m 26s	remaining: 8m 26s
5092:	learn: 0.0018454	total: 8m 26s	remaining: 8m 8s
4855:	learn: 0.0021077	total: 8m 26s	remaining: 8m 56s
5004:	learn: 0.0018363	total: 8m 26s	remaining: 8m 25s
4652:	learn: 0.0020263	total: 8m 26s	remaining: 9m 42s
4999:	learn: 0.0019084	total: 8m 26s	remaining: 8m 26s
4856:	learn: 0.0021077	total: 8m 27s	remaining: 8m 56s
5005:	learn: 0.0018356	total: 8m 27s	remaining: 8m 25s
5093:	learn: 0.0018451	total: 8m 27s	remaining: 8m 8s
4653:	learn: 0.0020260	total: 8m 27s	remaining: 9m 42s
5000:	learn: 0.0019079	total: 8m 26s	remaining: 8m 26s
5094:	learn: 0.0018451	total: 8m 27s	remaining: 8m 8s
5006:	learn: 0.0018356	total: 8m 27s	remaining: 8m 25s
4857:	learn: 0.0021077	total: 8m 27s	remaining: 8m 56s
4654:	learn: 0.0020253	total: 8m 27s	remaining: 9m 42s
5001:	learn: 0.0019075	total: 8m 27s	remaining: 8m 26s
5007:	learn: 0.0018356	total: 8m 27s	remaining: 8m 25s
5095:	learn: 0.0018446	total: 8m 27s	remaining: 8m 8s
4858:	learn: 0.0021077	total: 8m 27s	remaining: 8m 56s
5008:	learn: 0.0018356	total: 8m 27s	remaining: 8m 25s
5002:	learn: 0.0019069	total: 8m 27s	remaining: 8m 26s
4655:	learn: 0.0020247	total: 8m 27s	remaining: 9m 42s
5096:	learn: 0.0018442	total: 8m 27s	remaining: 8m 7s
4859:	learn: 0.0021069	total: 8m 27s	remaining: 8m 56s
5097:	learn: 0.0018436	total: 8m 27s	remaining: 8m 7s
5009:	learn: 0.0018356	total: 8m 27s	remaining: 8m 25s
4656:	learn: 0.0020240	total: 8m 27s	remaining: 9m 42s
5003:	learn: 0.0019064	total: 8m 27s	remaining: 8m 26s
4860:	learn: 0.0021069	total: 8m 27s	remaining: 8m 56s
5098:	learn: 0.0018431	total: 8m 27s	remaining: 8m 7s
5010:	learn: 0.0018356	total: 8m 27s	remaining: 8m 25s
4657:	learn: 0.0020230	total: 8m 27s	remaining: 9m 42s
5004:	learn: 0.0019058	total: 8m 27s	remaining: 8m 26s
4861:	learn: 0.0021069	total: 8m 27s	remaining: 8m 56s
5099:	learn: 0.0018426	total: 8m 27s	remaining: 8m 7s
5011:	learn: 0.0018355	total: 8m 27s	remaining: 8m 25s
5005:	learn: 0.0019058	total: 8m 27s	remaining: 8m 26s
4862:	learn: 0.0021069	total: 8m 27s	remaining: 8m 56s
4658:	learn: 0.0020225	total: 8m 27s	remaining: 9m 42s
5100:	learn: 0.0018420	total: 8m 27s	remaining: 8m 7s
5006:	learn: 0.0019053	total: 8m 27s	remaining: 8m 26s
5012:	learn: 0.0018355	total: 8m 27s	remaining: 8m 25s
4863:	learn: 0.0021069	total: 8m 27s	remaining: 8m 56s
5101:	learn: 0.0018420	total: 8m 27s	remaining: 8m 7s
5007:	learn: 0.0019048	total: 8m 27s	remaining: 8m 26s
4659:	learn: 0.0020217	total: 8m 27s	remaining: 9m 41s
4864:	learn: 0.0021069	total: 8m 27s	remaining: 8m 55s
5013:	learn: 0.0018349	total: 8m 27s	remaining: 8m 24s
5102:	learn: 0.0018415	total: 8m 27s	remaining: 8m 7s
5008:	learn: 0.0019044	total: 8m 27s	remaining: 8m 25s
4865:	learn: 0.0021069	total: 8m 27s	remaining: 8m 55s
5014:	learn: 0.0018346	total: 8m 27s	remaining: 8m 24s
5009:	learn: 0.0019039	total: 8m 27s	remaining: 8m 25s
4660:	learn: 0.0020207	total: 8m 27s	remaining: 9m 41s
5103:	learn: 0.0018415	total: 8m 27s	remaining: 8m 7s
4866:	learn: 0.0021069	total: 8m 27s	remaining: 8m 55s
5015:	learn: 0.0018346	total: 8m 28s	remaining: 8m 24s
5010:	learn: 0.0019032	total: 8m 27s	remaining: 8m 25s
4867:	learn: 0.0021069	total: 8m 28s	remaining: 8m 55s
4661:	learn: 0.0020208	total: 8m 28s	remaining: 9m 41s
5104:	learn: 0.0018410	total: 8m 28s	remaining: 8m 7s
5016:	learn: 0.0018346	total: 8m 28s	remaining: 8m 24s
5011:	learn: 0.0019029	total: 8m 27s	remaining: 8m 25s
4868:	learn: 0.0021069	total: 8m 28s	remaining: 8m 55s
5105:	learn: 0.0018410	total: 8m 28s	remaining: 8m 7s
4662:	learn: 0.0020208	total: 8m 28s	remaining: 9m 41s
5012:	learn: 0.0019024	total: 8m 28s	remaining: 8m 25s
5017:	learn: 0.0018346	total: 8m 28s	remaining: 8m 24s
4869:	learn: 0.0021069	total: 8m 28s	remaining: 8m 55s
5106:	learn: 0.0018410	total: 8m 28s	remaining: 8m 6s
4663:	learn: 0.0020207	total: 8m 28s	remaining: 9m 41s
5018:	learn: 0.0018340	total: 8m 28s	remaining: 8m 24s
5013:	learn: 0.0019018	total: 8m 28s	remaining: 8m 25s
5107:	learn: 0.0018405	total: 8m 28s	remaining: 8m 6s
4870:	learn: 0.0021069	total: 8m 28s	remaining: 8m 55s
5019:	learn: 0.0018340	total: 8m 28s	remaining: 8m 24s
5108:	learn: 0.0018404	total: 8m 28s	remaining: 8m 6s
4664:	learn: 0.0020200	total: 8m 28s	remaining: 9m 41s
4871:	learn: 0.0021069	total: 8m 28s	remaining: 8m 55s
5014:	learn: 0.0019011	total: 8m 28s	remaining: 8m 25s
5020:	learn: 0.0018340	total: 8m 28s	remaining: 8m 24s
4872:	learn: 0.0021069	total: 8m 28s	remaining: 8m 55s
5109:	learn: 0.0018400	total: 8m 28s	remaining: 8m 6s
4665:	learn: 0.0020192	total: 8m 28s	remaining: 9m 41s
5015:	learn: 0.0019011	total: 8m 28s	remaining: 8m 25s
4873:	learn: 0.0021069	total: 8m 28s	remaining: 8m 54s
5021:	learn: 0.0018340	total: 8m 28s	remaining: 8m 24s
5110:	learn: 0.0018394	total: 8m 28s	remaining: 8m 6s
5022:	learn: 0.0018340	total: 8m 28s	remaining: 8m 24s
5016:	learn: 0.0019004	total: 8m 28s	remaining: 8m 25s
4666:	learn: 0.0020184	total: 8m 28s	remaining: 9m 41s
4874:	learn: 0.0021069	total: 8m 28s	remaining: 8m 54s
5111:	learn: 0.0018394	total: 8m 28s	remaining: 8m 6s
4875:	learn: 0.0021069	total: 8m 28s	remaining: 8m 54s
5023:	learn: 0.0018340	total: 8m 28s	remaining: 8m 23s
5017:	learn: 0.0018999	total: 8m 28s	remaining: 8m 25s
5112:	learn: 0.0018388	total: 8m 28s	remaining: 8m 6s
4667:	learn: 0.0020177	total: 8m 28s	remaining: 9m 41s
4876:	learn: 0.0021069	total: 8m 28s	remaining: 8m 54s
5024:	learn: 0.0018333	total: 8m 28s	remaining: 8m 23s
5113:	learn: 0.0018388	total: 8m 28s	remaining: 8m 6s
5018:	learn: 0.0018999	total: 8m 28s	remaining: 8m 24s
4877:	learn: 0.0021069	total: 8m 28s	remaining: 8m 54s
4668:	learn: 0.0020177	total: 8m 29s	remaining: 9m 41s
5025:	learn: 0.0018325	total: 8m 28s	remaining: 8m 23s
5114:	learn: 0.0018388	total: 8m 28s	remaining: 8m 6s
5019:	learn: 0.0018995	total: 8m 28s	remaining: 8m 24s
4878:	learn: 0.0021069	total: 8m 29s	remaining: 8m 54s
5115:	learn: 0.0018382	total: 8m 29s	remaining: 8m 5s
5026:	learn: 0.0018318	total: 8m 29s	remaining: 8m 23s
4879:	learn: 0.0021069	total: 8m 29s	remaining: 8m 54s
4669:	learn: 0.0020175	total: 8m 29s	remaining: 9m 41s
5020:	learn: 0.0018989	total: 8m 28s	remaining: 8m 24s
5116:	learn: 0.0018382	total: 8m 29s	remaining: 8m 5s
5027:	learn: 0.0018310	total: 8m 29s	remaining: 8m 23s
4880:	learn: 0.0021069	total: 8m 29s	remaining: 8m 54s
5021:	learn: 0.0018983	total: 8m 29s	remaining: 8m 24s
4670:	learn: 0.0020166	total: 8m 29s	remaining: 9m 40s
5117:	learn: 0.0018380	total: 8m 29s	remaining: 8m 5s
4881:	learn: 0.0021069	total: 8m 29s	remaining: 8m 53s
5028:	learn: 0.0018310	total: 8m 29s	remaining: 8m 23s
5022:	learn: 0.0018978	total: 8m 29s	remaining: 8m 24s
4671:	learn: 0.0020159	total: 8m 29s	remaining: 9m 40s
5118:	learn: 0.0018375	total: 8m 29s	remaining: 8m 5s
4882:	learn: 0.0021069	total: 8m 29s	remaining: 8m 53s
5029:	learn: 0.0018304	total: 8m 29s	remaining: 8m 23s
5023:	learn: 0.0018971	total: 8m 29s	remaining: 8m 24s
4672:	learn: 0.0020153	total: 8m 29s	remaining: 9m 40s
5024:	learn: 0.0018964	total: 8m 29s	remaining: 8m 24s
5119:	learn: 0.0018375	total: 8m 29s	remaining: 8m 5s
4883:	learn: 0.0021069	total: 8m 29s	remaining: 8m 53s
5030:	learn: 0.0018299	total: 8m 29s	remaining: 8m 23s
5120:	learn: 0.0018373	total: 8m 29s	remaining: 8m 5s
5025:	learn: 0.0018959	total: 8m 29s	remaining: 8m 24s
4673:	learn: 0.0020153	total: 8m 29s	remaining: 9m 40s
5031:	learn: 0.0018299	total: 8m 29s	remaining: 8m 23s
4884:	learn: 0.0021069	total: 8m 29s	remaining: 8m 53s
5121:	learn: 0.0018367	total: 8m 29s	remaining: 8m 5s
5032:	learn: 0.0018299	total: 8m 29s	remaining: 8m 22s
5026:	learn: 0.0018954	total: 8m 29s	remaining: 8m 24s
4885:	learn: 0.0021069	total: 8m 29s	remaining: 8m 53s
4674:	learn: 0.0020145	total: 8m 29s	remaining: 9m 40s
5122:	learn: 0.0018367	total: 8m 29s	remaining: 8m 5s
5033:	learn: 0.0018299	total: 8m 29s	remaining: 8m 22s
5027:	learn: 0.0018954	total: 8m 29s	remaining: 8m 23s
4675:	learn: 0.0020139	total: 8m 29s	remaining: 9m 40s
5123:	learn: 0.0018367	total: 8m 29s	remaining: 8m 5s
4886:	learn: 0.0021069	total: 8m 29s	remaining: 8m 53s
5028:	learn: 0.0018949	total: 8m 29s	remaining: 8m 23s
5034:	learn: 0.0018299	total: 8m 29s	remaining: 8m 22s
5124:	learn: 0.0018367	total: 8m 29s	remaining: 8m 4s
4676:	learn: 0.0020131	total: 8m 29s	remaining: 9m 40s
4887:	learn: 0.0021069	total: 8m 29s	remaining: 8m 53s
5029:	learn: 0.0018944	total: 8m 29s	remaining: 8m 23s
5035:	learn: 0.0018299	total: 8m 29s	remaining: 8m 22s

4677:	learn: 0.0020129	total: 8m 30s	remaining: 9m 40s
5125:	learn: 0.0018363	total: 8m 29s	remaining: 8m 4s
4888:	learn: 0.0021069	total: 8m 30s	remaining: 8m 53s
5030:	learn: 0.0018943	total: 8m 29s	remaining: 8m 23s
5036:	learn: 0.0018296	total: 8m 30s	remaining: 8m 22s
4678:	learn: 0.0020122	total: 8m 30s	remaining: 9m 40s
5126:	learn: 0.0018363	total: 8m 30s	remaining: 8m 4s
5031:	learn: 0.0018935	total: 8m 30s	remaining: 8m 23s
4889:	learn: 0.0021069	total: 8m 30s	remaining: 8m 53s
5037:	learn: 0.0018293	total: 8m 30s	remaining: 8m 22s
4679:	learn: 0.0020115	total: 8m 30s	remaining: 9m 40s
5127:	learn: 0.0018363	total: 8m 30s	remaining: 8m 4s
5032:	learn: 0.0018931	total: 8m 30s	remaining: 8m 23s
5038:	learn: 0.0018293	total: 8m 30s	remaining: 8m 22s
4890:	learn: 0.0021069	total: 8m 30s	remaining: 8m 53s
5128:	learn: 0.0018357	total: 8m 30s	remaining: 8m 4s
4680:	learn: 0.0020108	total: 8m 30s	remaining: 9m 39s
5033:	learn: 0.0018926	total: 8m 30s	remaining: 8m 23s
5039:	learn: 0.0018290	total: 8m 30s	remaining: 8m 22s
4891:	learn: 0.0021069	total: 8m 30s	remaining: 8m 52s
5129:	learn: 0.0018355	total: 8m 30s	remaining: 8m 4s
4681:	learn: 0.0020102	total: 8m 30s	remaining: 9m 39s
5034:	learn: 0.0018920	total: 8m 30s	remaining: 8m 23s
5130:	learn: 0.0018355	total: 8m 30s	remaining: 8m 4s
5040:	learn: 0.0018290	total: 8m 30s	remaining: 8m 22s
4892:	learn: 0.0021069	total: 8m 30s	remaining: 8m 52s
4682:	learn: 0.0020094	total: 8m 30s	remaining: 9m 39s
5035:	learn: 0.0018915	total: 8m 30s	remaining: 8m 23s
5131:	learn: 0.0018351	total: 8m 30s	remaining: 8m 4s
5041:	learn: 0.0018290	total: 8m 30s	remaining: 8m 22s
4683:	learn: 0.0020088	total: 8m 30s	remaining: 9m 39s
4893:	learn: 0.0021069	total: 8m 30s	remaining: 8m 52s
5132:	learn: 0.0018351	total: 8m 30s	remaining: 8m 4s
5036:	learn: 0.0018908	total: 8m 30s	remaining: 8m 23s
5042:	learn: 0.0018284	total: 8m 30s	remaining: 8m 21s
4684:	learn: 0.0020082	total: 8m 30s	remaining: 9m 39s
5133:	learn: 0.0018351	total: 8m 30s	remaining: 8m 4s
4894:	learn: 0.0021069	total: 8m 30s	remaining: 8m 52s
5037:	learn: 0.0018908	total: 8m 30s	remaining: 8m 22s
5043:	learn: 0.0018278	total: 8m 30s	remaining: 8m 21s
4685:	learn: 0.0020075	total: 8m 30s	remaining: 9m 39s
4895:	learn: 0.0021069	total: 8m 30s	remaining: 8m 52s
5134:	learn: 0.0018345	total: 8m 30s	remaining: 8m 3s
5038:	learn: 0.0018903	total: 8m 30s	remaining: 8m 22s
5044:	learn: 0.0018278	total: 8m 30s	remaining: 8m 21s
5135:	learn: 0.0018339	total: 8m 30s	remaining: 8m 3s
4896:	learn: 0.0021069	total: 8m 30s	remaining: 8m 52s
4686:	learn: 0.0020074	total: 8m 30s	remaining: 9m 39s
5039:	learn: 0.0018899	total: 8m 30s	remaining: 8m 22s
5136:	learn: 0.0018336	total: 8m 30s	remaining: 8m 3s
5045:	learn: 0.0018278	total: 8m 30s	remaining: 8m 21s
4897:	learn: 0.0021069	total: 8m 30s	remaining: 8m 52s
5040:	learn: 0.0018896	total: 8m 30s	remaining: 8m 22s
4687:	learn: 0.0020066	total: 8m 31s	remaining: 9m 39s
5137:	learn: 0.0018336	total: 8m 31s	remaining: 8m 3s
5046:	learn: 0.0018278	total: 8m 31s	remaining: 8m 21s
5138:	learn: 0.0018330	total: 8m 31s	remaining: 8m 3s
5041:	learn: 0.0018892	total: 8m 31s	remaining: 8m 22s
4898:	learn: 0.0021069	total: 8m 31s	remaining: 8m 52s
4688:	learn: 0.0020056	total: 8m 31s	remaining: 9m 39s
5047:	learn: 0.0018271	total: 8m 31s	remaining: 8m 21s
5139:	learn: 0.0018330	total: 8m 31s	remaining: 8m 3s
5042:	learn: 0.0018891	total: 8m 31s	remaining: 8m 22s
4899:	learn: 0.0021069	total: 8m 31s	remaining: 8m 52s
5048:	learn: 0.0018265	total: 8m 31s	remaining: 8m 21s
4689:	learn: 0.0020050	total: 8m 31s	remaining: 9m 38s
5140:	learn: 0.0018325	total: 8m 31s	remaining: 8m 3s
4900:	learn: 0.0021069	total: 8m 31s	remaining: 8m 51s
5043:	learn: 0.0018887	total: 8m 31s	remaining: 8m 22s
4690:	learn: 0.0020046	total: 8m 31s	remaining: 9m 38s
5049:	learn: 0.0018258	total: 8m 31s	remaining: 8m 21s
5141:	learn: 0.0018321	total: 8m 31s	remaining: 8m 3s
5044:	learn: 0.0018884	total: 8m 31s	remaining: 8m 22s
4901:	learn: 0.0021069	total: 8m 31s	remaining: 8m 51s
5142:	learn: 0.0018314	total: 8m 31s	remaining: 8m 3s
5050:	learn: 0.0018247	total: 8m 31s	remaining: 8m 21s
4691:	learn: 0.0020046	total: 8m 31s	remaining: 9m 38s
4902:	learn: 0.0021069	total: 8m 31s	remaining: 8m 51s
5143:	learn: 0.0018309	total: 8m 31s	remaining: 8m 2s
5045:	learn: 0.0018881	total: 8m 31s	remaining: 8m 22s
4692:	learn: 0.0020039	total: 8m 31s	remaining: 9m 38s
5051:	learn: 0.0018247	total: 8m 31s	remaining: 8m 21s
4903:	learn: 0.0021069	total: 8m 31s	remaining: 8m 51s
5046:	learn: 0.0018873	total: 8m 31s	remaining: 8m 21s
5144:	learn: 0.0018309	total: 8m 31s	remaining: 8m 2s
4693:	learn: 0.0020031	total: 8m 31s	remaining: 9m 38s
5052:	learn: 0.0018247	total: 8m 31s	remaining: 8m 20s
4904:	learn: 0.0021069	total: 8m 31s	remaining: 8m 51s
5047:	learn: 0.0018868	total: 8m 31s	remaining: 8m 21s
5145:	learn: 0.0018302	total: 8m 31s	remaining: 8m 2s
4694:	learn: 0.0020031	total: 8m 31s	remaining: 9m 38s
4905:	learn: 0.0021069	total: 8m 31s	remaining: 8m 51s
5053:	learn: 0.0018242	total: 8m 31s	remaining: 8m 20s
5146:	learn: 0.0018298	total: 8m 31s	remaining: 8m 2s
5048:	learn: 0.0018861	total: 8m 31s	remaining: 8m 21s
4695:	learn: 0.0020031	total: 8m 31s	remaining: 9m 38s
5054:	learn: 0.0018238	total: 8m 31s	remaining: 8m 20s
5147:	learn: 0.0018297	total: 8m 31s	remaining: 8m 2s
5049:	learn: 0.0018853	total: 8m 31s	remaining: 8m 21s
4906:	learn: 0.0021069	total: 8m 31s	remaining: 8m 51s
4696:	learn: 0.0020024	total: 8m 32s	remaining: 9m 38s
5050:	learn: 0.0018847	total: 8m 31s	remaining: 8m 21s
5055:	learn: 0.0018233	total: 8m 32s	remaining: 8m 20s
4907:	learn: 0.0021069	total: 8m 32s	remaining: 8m 51s
5148:	learn: 0.0018293	total: 8m 32s	remaining: 8m 2s
5051:	learn: 0.0018847	total: 8m 31s	remaining: 8m 21s
4697:	learn: 0.0020018	total: 8m 32s	remaining: 9m 38s
5056:	learn: 0.0018227	total: 8m 32s	remaining: 8m 20s
5052:	learn: 0.0018841	total: 8m 32s	remaining: 8m 21s
4908:	learn: 0.0021069	total: 8m 32s	remaining: 8m 51s
5149:	learn: 0.0018287	total: 8m 32s	remaining: 8m 2s
5057:	learn: 0.0018219	total: 8m 32s	remaining: 8m 20s
4698:	learn: 0.0020010	total: 8m 32s	remaining: 9m 37s
5053:	learn: 0.0018835	total: 8m 32s	remaining: 8m 21s
5150:	learn: 0.0018281	total: 8m 32s	remaining: 8m 2s
4909:	learn: 0.0021069	total: 8m 32s	remaining: 8m 51s
5058:	learn: 0.0018219	total: 8m 32s	remaining: 8m 20s
4699:	learn: 0.0020004	total: 8m 32s	remaining: 9m 37s
5151:	learn: 0.0018276	total: 8m 32s	remaining: 8m 2s
5054:	learn: 0.0018830	total: 8m 32s	remaining: 8m 21s
4910:	learn: 0.0021069	total: 8m 32s	remaining: 8m 50s
5059:	learn: 0.0018219	total: 8m 32s	remaining: 8m 20s
4700:	learn: 0.0019997	total: 8m 32s	remaining: 9m 37s
5055:	learn: 0.0018830	total: 8m 32s	remaining: 8m 20s
5060:	learn: 0.0018219	total: 8m 32s	remaining: 8m 20s
5152:	learn: 0.0018270	total: 8m 32s	remaining: 8m 2s
4911:	learn: 0.0021069	total: 8m 32s	remaining: 8m 50s
4701:	learn: 0.0019989	total: 8m 32s	remaining: 9m 37s
5061:	learn: 0.0018212	total: 8m 32s	remaining: 8m 20s
5056:	learn: 0.0018827	total: 8m 32s	remaining: 8m 20s
5153:	learn: 0.0018263	total: 8m 32s	remaining: 8m 1s
4912:	learn: 0.0021069	total: 8m 32s	remaining: 8m 50s
4702:	learn: 0.0019981	total: 8m 32s	remaining: 9m 37s
5057:	learn: 0.0018821	total: 8m 32s	remaining: 8m 20s
5062:	learn: 0.0018212	total: 8m 32s	remaining: 8m 19s
5154:	learn: 0.0018258	total: 8m 32s	remaining: 8m 1s
4913:	learn: 0.0021069	total: 8m 32s	remaining: 8m 50s
4703:	learn: 0.0019972	total: 8m 32s	remaining: 9m 37s
5058:	learn: 0.0018815	total: 8m 32s	remaining: 8m 20s
5063:	learn: 0.0018212	total: 8m 32s	remaining: 8m 19s
5155:	learn: 0.0018253	total: 8m 32s	remaining: 8m 1s
4914:	learn: 0.0021061	total: 8m 32s	remaining: 8m 50s
5059:	learn: 0.0018808	total: 8m 32s	remaining: 8m 20s
4704:	learn: 0.0019964	total: 8m 32s	remaining: 9m 37s
5156:	learn: 0.0018253	total: 8m 32s	remaining: 8m 1s
5064:	learn: 0.0018212	total: 8m 32s	remaining: 8m 19s
4915:	learn: 0.0021061	total: 8m 32s	remaining: 8m 50s
5060:	learn: 0.0018804	total: 8m 32s	remaining: 8m 20s
4705:	learn: 0.0019963	total: 8m 32s	remaining: 9m 37s
5157:	learn: 0.0018247	total: 8m 32s	remaining: 8m 1s
5065:	learn: 0.0018212	total: 8m 33s	remaining: 8m 19s
5061:	learn: 0.0018799	total: 8m 32s	remaining: 8m 20s
4916:	learn: 0.0021061	total: 8m 32s	remaining: 8m 50s
4706:	learn: 0.0019958	total: 8m 33s	remaining: 9m 36s
5158:	learn: 0.0018247	total: 8m 33s	remaining: 8m 1s
4917:	learn: 0.0021061	total: 8m 33s	remaining: 8m 50s
5066:	learn: 0.0018212	total: 8m 33s	remaining: 8m 19s
5062:	learn: 0.0018792	total: 8m 32s	remaining: 8m 20s
5159:	learn: 0.0018247	total: 8m 33s	remaining: 8m 1s
4707:	learn: 0.0019953	total: 8m 33s	remaining: 9m 36s
5067:	learn: 0.0018213	total: 8m 33s	remaining: 8m 19s
4918:	learn: 0.0021061	total: 8m 33s	remaining: 8m 50s
5063:	learn: 0.0018786	total: 8m 33s	remaining: 8m 20s
4708:	learn: 0.0019953	total: 8m 33s	remaining: 9m 36s
5160:	learn: 0.0018242	total: 8m 33s	remaining: 8m 1s
5068:	learn: 0.0018212	total: 8m 33s	remaining: 8m 19s
4919:	learn: 0.0021061	total: 8m 33s	remaining: 8m 49s
5064:	learn: 0.0018779	total: 8m 33s	remaining: 8m 20s
4709:	learn: 0.0019947	total: 8m 33s	remaining: 9m 36s
5161:	learn: 0.0018235	total: 8m 33s	remaining: 8m 1s
5069:	learn: 0.0018212	total: 8m 33s	remaining: 8m 19s
4920:	learn: 0.0021061	total: 8m 33s	remaining: 8m 49s
5065:	learn: 0.0018774	total: 8m 33s	remaining: 8m 19s
4710:	learn: 0.0019941	total: 8m 33s	remaining: 9m 36s
5162:	learn: 0.0018232	total: 8m 33s	remaining: 8m 1s
4921:	learn: 0.0021061	total: 8m 33s	remaining: 8m 49s
5066:	learn: 0.0018768	total: 8m 33s	remaining: 8m 19s
5070:	learn: 0.0018212	total: 8m 33s	remaining: 8m 19s
4711:	learn: 0.0019934	total: 8m 33s	remaining: 9m 36s
5163:	learn: 0.0018232	total: 8m 33s	remaining: 8m
4922:	learn: 0.0021061	total: 8m 33s	remaining: 8m 49s
5067:	learn: 0.0018763	total: 8m 33s	remaining: 8m 19s
4712:	learn: 0.0019927	total: 8m 33s	remaining: 9m 36s
5164:	learn: 0.0018232	total: 8m 33s	remaining: 8m
5071:	learn: 0.0018212	total: 8m 33s	remaining: 8m 19s
4923:	learn: 0.0021061	total: 8m 33s	remaining: 8m 49s
5068:	learn: 0.0018763	total: 8m 33s	remaining: 8m 19s
5165:	learn: 0.0018232	total: 8m 33s	remaining: 8m
4713:	learn: 0.0019920	total: 8m 33s	remaining: 9m 36s
5072:	learn: 0.0018205	total: 8m 33s	remaining: 8m 18s
5069:	learn: 0.0018758	total: 8m 33s	remaining: 8m 19s
4924:	learn: 0.0021061	total: 8m 33s	remaining: 8m 49s
4714:	learn: 0.0019914	total: 8m 33s	remaining: 9m 36s
5166:	learn: 0.0018232	total: 8m 33s	remaining: 8m
4925:	learn: 0.0021061	total: 8m 33s	remaining: 8m 49s
5073:	learn: 0.0018205	total: 8m 33s	remaining: 8m 18s
5070:	learn: 0.0018751	total: 8m 33s	remaining: 8m 19s
4715:	learn: 0.0019914	total: 8m 34s	remaining: 9m 35s
5167:	learn: 0.0018226	total: 8m 33s	remaining: 8m
4926:	learn: 0.0021061	total: 8m 33s	remaining: 8m 49s
5071:	learn: 0.0018745	total: 8m 33s	remaining: 8m 19s
5074:	learn: 0.0018204	total: 8m 33s	remaining: 8m 18s
4716:	learn: 0.0019907	total: 8m 34s	remaining: 9m 35s
5168:	learn: 0.0018226	total: 8m 34s	remaining: 8m
4927:	learn: 0.0021061	total: 8m 34s	remaining: 8m 49s
5075:	learn: 0.0018204	total: 8m 34s	remaining: 8m 18s
5072:	learn: 0.0018745	total: 8m 33s	remaining: 8m 19s
5169:	learn: 0.0018226	total: 8m 34s	remaining: 8m
4717:	learn: 0.0019904	total: 8m 34s	remaining: 9m 35s
4928:	learn: 0.0021061	total: 8m 34s	remaining: 8m 48s
5076:	learn: 0.0018198	total: 8m 34s	remaining: 8m 18s
5073:	learn: 0.0018741	total: 8m 34s	remaining: 8m 19s
5170:	learn: 0.0018221	total: 8m 34s	remaining: 8m
4929:	learn: 0.0021061	total: 8m 34s	remaining: 8m 48s
4718:	learn: 0.0019899	total: 8m 34s	remaining: 9m 35s
5077:	learn: 0.0018192	total: 8m 34s	remaining: 8m 18s
5074:	learn: 0.0018734	total: 8m 34s	remaining: 8m 18s
5171:	learn: 0.0018221	total: 8m 34s	remaining: 8m
4930:	learn: 0.0021052	total: 8m 34s	remaining: 8m 48s
4719:	learn: 0.0019893	total: 8m 34s	remaining: 9m 35s
5172:	learn: 0.0018216	total: 8m 34s	remaining: 7m 59s
5078:	learn: 0.0018189	total: 8m 34s	remaining: 8m 18s
5075:	learn: 0.0018729	total: 8m 34s	remaining: 8m 18s
5173:	learn: 0.0018213	total: 8m 34s	remaining: 7m 59s
5079:	learn: 0.0018189	total: 8m 34s	remaining: 8m 18s
4931:	learn: 0.0021052	total: 8m 34s	remaining: 8m 48s
4720:	learn: 0.0019887	total: 8m 34s	remaining: 9m 35s
5076:	learn: 0.0018726	total: 8m 34s	remaining: 8m 18s
5174:	learn: 0.0018208	total: 8m 34s	remaining: 7m 59s
4932:	learn: 0.0021052	total: 8m 34s	remaining: 8m 48s
5080:	learn: 0.0018189	total: 8m 34s	remaining: 8m 18s
4721:	learn: 0.0019884	total: 8m 34s	remaining: 9m 35s
5077:	learn: 0.0018721	total: 8m 34s	remaining: 8m 18s
5175:	learn: 0.0018203	total: 8m 34s	remaining: 7m 59s
4933:	learn: 0.0021052	total: 8m 34s	remaining: 8m 48s
5078:	learn: 0.0018716	total: 8m 34s	remaining: 8m 18s
4722:	learn: 0.0019879	total: 8m 34s	remaining: 9m 35s
5081:	learn: 0.0018189	total: 8m 34s	remaining: 8m 18s
5176:	learn: 0.0018203	total: 8m 34s	remaining: 7m 59s
5079:	learn: 0.0018709	total: 8m 34s	remaining: 8m 18s
5082:	learn: 0.0018186	total: 8m 34s	remaining: 8m 17s
4934:	learn: 0.0021053	total: 8m 34s	remaining: 8m 48s
5177:	learn: 0.0018203	total: 8m 34s	remaining: 7m 59s
4723:	learn: 0.0019872	total: 8m 34s	remaining: 9m 35s
5080:	learn: 0.0018705	total: 8m 34s	remaining: 8m 18s
5083:	learn: 0.0018179	total: 8m 34s	remaining: 8m 17s
4935:	learn: 0.0021052	total: 8m 34s	remaining: 8m 48s
5081:	learn: 0.0018700	total: 8m 34s	remaining: 8m 18s
5178:	learn: 0.0018198	total: 8m 34s	remaining: 7m 59s
4724:	learn: 0.0019865	total: 8m 35s	remaining: 9m 34s
5084:	learn: 0.0018176	total: 8m 34s	remaining: 8m 17s
4936:	learn: 0.0021052	total: 8m 34s	remaining: 8m 48s
5082:	learn: 0.0018694	total: 8m 34s	remaining: 8m 18s
5179:	learn: 0.0018194	total: 8m 35s	remaining: 7m 59s
5085:	learn: 0.0018176	total: 8m 35s	remaining: 8m 17s
4725:	learn: 0.0019859	total: 8m 35s	remaining: 9m 34s
5180:	learn: 0.0018188	total: 8m 35s	remaining: 7m 59s
4937:	learn: 0.0021052	total: 8m 35s	remaining: 8m 48s
5083:	learn: 0.0018694	total: 8m 35s	remaining: 8m 17s
5086:	learn: 0.0018176	total: 8m 35s	remaining: 8m 17s
5084:	learn: 0.0018689	total: 8m 35s	remaining: 8m 17s
4938:	learn: 0.0021052	total: 8m 35s	remaining: 8m 47s
5181:	learn: 0.0018183	total: 8m 35s	remaining: 7m 59s
4726:	learn: 0.0019853	total: 8m 35s	remaining: 9m 34s
5087:	learn: 0.0018171	total: 8m 35s	remaining: 8m 17s
5182:	learn: 0.0018183	total: 8m 35s	remaining: 7m 58s
5085:	learn: 0.0018685	total: 8m 35s	remaining: 8m 17s
4727:	learn: 0.0019846	total: 8m 35s	remaining: 9m 34s
4939:	learn: 0.0021052	total: 8m 35s	remaining: 8m 47s
5088:	learn: 0.0018171	total: 8m 35s	remaining: 8m 17s
5183:	learn: 0.0018177	total: 8m 35s	remaining: 7m 58s
5086:	learn: 0.0018681	total: 8m 35s	remaining: 8m 17s
4728:	learn: 0.0019839	total: 8m 35s	remaining: 9m 34s
4940:	learn: 0.0021052	total: 8m 35s	remaining: 8m 47s
5089:	learn: 0.0018171	total: 8m 35s	remaining: 8m 17s
5184:	learn: 0.0018171	total: 8m 35s	remaining: 7m 58s
5087:	learn: 0.0018676	total: 8m 35s	remaining: 8m 17s
4941:	learn: 0.0021052	total: 8m 35s	remaining: 8m 47s
5090:	learn: 0.0018171	total: 8m 35s	remaining: 8m 17s
4729:	learn: 0.0019833	total: 8m 35s	remaining: 9m 34s
5088:	learn: 0.0018670	total: 8m 35s	remaining: 8m 17s
5185:	learn: 0.0018167	total: 8m 35s	remaining: 7m 58s
5091:	learn: 0.0018171	total: 8m 35s	remaining: 8m 17s
4942:	learn: 0.0021052	total: 8m 35s	remaining: 8m 47s
4730:	learn: 0.0019826	total: 8m 35s	remaining: 9m 34s
5089:	learn: 0.0018671	total: 8m 35s	remaining: 8m 17s
5186:	learn: 0.0018163	total: 8m 35s	remaining: 7m 58s
4943:	learn: 0.0021052	total: 8m 35s	remaining: 8m 47s
5092:	learn: 0.0018165	total: 8m 35s	remaining: 8m 16s
5090:	learn: 0.0018667	total: 8m 35s	remaining: 8m 17s
4731:	learn: 0.0019820	total: 8m 35s	remaining: 9m 34s
4944:	learn: 0.0021052	total: 8m 35s	remaining: 8m 47s
5187:	learn: 0.0018158	total: 8m 35s	remaining: 7m 58s
5093:	learn: 0.0018161	total: 8m 35s	remaining: 8m 16s
4945:	learn: 0.0021044	total: 8m 35s	remaining: 8m 47s
5091:	learn: 0.0018661	total: 8m 35s	remaining: 8m 17s
4732:	learn: 0.0019813	total: 8m 35s	remaining: 9m 34s
5188:	learn: 0.0018158	total: 8m 35s	remaining: 7m 58s

5094:	learn: 0.0018160	total: 8m 35s	remaining: 8m 16s
4946:	learn: 0.0021044	total: 8m 35s	remaining: 8m 47s
5092:	learn: 0.0018655	total: 8m 35s	remaining: 8m 17s
5189:	learn: 0.0018158	total: 8m 35s	remaining: 7m 58s
4733:	learn: 0.0019806	total: 8m 36s	remaining: 9m 34s
5095:	learn: 0.0018160	total: 8m 36s	remaining: 8m 16s
4947:	learn: 0.0021044	total: 8m 36s	remaining: 8m 46s
5093:	learn: 0.0018649	total: 8m 35s	remaining: 8m 16s
5190:	learn: 0.0018158	total: 8m 36s	remaining: 7m 58s
5096:	learn: 0.0018159	total: 8m 36s	remaining: 8m 16s
4948:	learn: 0.0021044	total: 8m 36s	remaining: 8m 46s
4734:	learn: 0.0019801	total: 8m 36s	remaining: 9m 34s
5094:	learn: 0.0018644	total: 8m 36s	remaining: 8m 16s
5191:	learn: 0.0018153	total: 8m 36s	remaining: 7m 58s
5097:	learn: 0.0018157	total: 8m 36s	remaining: 8m 16s
4949:	learn: 0.0021044	total: 8m 36s	remaining: 8m 46s
4735:	learn: 0.0019795	total: 8m 36s	remaining: 9m 33s
5098:	learn: 0.0018150	total: 8m 36s	remaining: 8m 16s
5095:	learn: 0.0018640	total: 8m 36s	remaining: 8m 16s
5192:	learn: 0.0018144	total: 8m 36s	remaining: 7m 57s
4950:	learn: 0.0021044	total: 8m 36s	remaining: 8m 46s
5096:	learn: 0.0018634	total: 8m 36s	remaining: 8m 16s
5193:	learn: 0.0018138	total: 8m 36s	remaining: 7m 57s
4736:	learn: 0.0019790	total: 8m 36s	remaining: 9m 33s
4951:	learn: 0.0021044	total: 8m 36s	remaining: 8m 46s
5099:	learn: 0.0018150	total: 8m 36s	remaining: 8m 16s
5097:	learn: 0.0018628	total: 8m 36s	remaining: 8m 16s
5194:	learn: 0.0018138	total: 8m 36s	remaining: 7m 57s
4737:	learn: 0.0019782	total: 8m 36s	remaining: 9m 33s
4952:	learn: 0.0021044	total: 8m 36s	remaining: 8m 46s
5100:	learn: 0.0018150	total: 8m 36s	remaining: 8m 16s
5195:	learn: 0.0018138	total: 8m 36s	remaining: 7m 57s
4738:	learn: 0.0019775	total: 8m 36s	remaining: 9m 33s
5098:	learn: 0.0018622	total: 8m 36s	remaining: 8m 16s
5101:	learn: 0.0018148	total: 8m 36s	remaining: 8m 15s
4953:	learn: 0.0021044	total: 8m 36s	remaining: 8m 46s
5196:	learn: 0.0018138	total: 8m 36s	remaining: 7m 57s
5099:	learn: 0.0018618	total: 8m 36s	remaining: 8m 16s
5102:	learn: 0.0018146	total: 8m 36s	remaining: 8m 15s
4739:	learn: 0.0019768	total: 8m 36s	remaining: 9m 33s
4954:	learn: 0.0021044	total: 8m 36s	remaining: 8m 46s
5100:	learn: 0.0018609	total: 8m 36s	remaining: 8m 16s
5103:	learn: 0.0018139	total: 8m 36s	remaining: 8m 15s
5197:	learn: 0.0018134	total: 8m 36s	remaining: 7m 57s
4740:	learn: 0.0019762	total: 8m 36s	remaining: 9m 33s
4955:	learn: 0.0021044	total: 8m 36s	remaining: 8m 46s
5104:	learn: 0.0018134	total: 8m 36s	remaining: 8m 15s
5101:	learn: 0.0018605	total: 8m 36s	remaining: 8m 16s
5198:	learn: 0.0018129	total: 8m 36s	remaining: 7m 57s
4741:	learn: 0.0019758	total: 8m 36s	remaining: 9m 33s
4956:	learn: 0.0021044	total: 8m 36s	remaining: 8m 45s
5105:	learn: 0.0018134	total: 8m 36s	remaining: 8m 15s
5199:	learn: 0.0018124	total: 8m 36s	remaining: 7m 57s
5102:	learn: 0.0018602	total: 8m 36s	remaining: 8m 16s
4742:	learn: 0.0019758	total: 8m 37s	remaining: 9m 33s
4957:	learn: 0.0021044	total: 8m 37s	remaining: 8m 45s
5106:	learn: 0.0018134	total: 8m 37s	remaining: 8m 15s
5103:	learn: 0.0018599	total: 8m 36s	remaining: 8m 15s
4743:	learn: 0.0019752	total: 8m 37s	remaining: 9m 32s
5200:	learn: 0.0018117	total: 8m 37s	remaining: 7m 57s
4958:	learn: 0.0021044	total: 8m 37s	remaining: 8m 45s
5104:	learn: 0.0018594	total: 8m 37s	remaining: 8m 15s
5201:	learn: 0.0018111	total: 8m 37s	remaining: 7m 57s
4744:	learn: 0.0019746	total: 8m 37s	remaining: 9m 32s
5107:	learn: 0.0018134	total: 8m 37s	remaining: 8m 15s
4959:	learn: 0.0021044	total: 8m 37s	remaining: 8m 45s
5105:	learn: 0.0018590	total: 8m 37s	remaining: 8m 15s
4745:	learn: 0.0019740	total: 8m 37s	remaining: 9m 32s
5202:	learn: 0.0018104	total: 8m 37s	remaining: 7m 56s
5108:	learn: 0.0018134	total: 8m 37s	remaining: 8m 15s
4960:	learn: 0.0021042	total: 8m 37s	remaining: 8m 45s
5106:	learn: 0.0018584	total: 8m 37s	remaining: 8m 15s
4746:	learn: 0.0019731	total: 8m 37s	remaining: 9m 32s
5109:	learn: 0.0018134	total: 8m 37s	remaining: 8m 15s
5203:	learn: 0.0018098	total: 8m 37s	remaining: 7m 56s
4961:	learn: 0.0021034	total: 8m 37s	remaining: 8m 45s
5107:	learn: 0.0018579	total: 8m 37s	remaining: 8m 15s
4747:	learn: 0.0019724	total: 8m 37s	remaining: 9m 32s
5204:	learn: 0.0018093	total: 8m 37s	remaining: 7m 56s
5110:	learn: 0.0018134	total: 8m 37s	remaining: 8m 15s
4962:	learn: 0.0021034	total: 8m 37s	remaining: 8m 45s
5108:	learn: 0.0018575	total: 8m 37s	remaining: 8m 15s
4963:	learn: 0.0021034	total: 8m 37s	remaining: 8m 45s
4748:	learn: 0.0019719	total: 8m 37s	remaining: 9m 32s
5111:	learn: 0.0018134	total: 8m 37s	remaining: 8m 14s
5205:	learn: 0.0018093	total: 8m 37s	remaining: 7m 56s
5109:	learn: 0.0018570	total: 8m 37s	remaining: 8m 15s
4964:	learn: 0.0021034	total: 8m 37s	remaining: 8m 45s
5206:	learn: 0.0018093	total: 8m 37s	remaining: 7m 56s
4749:	learn: 0.0019711	total: 8m 37s	remaining: 9m 32s
5112:	learn: 0.0018134	total: 8m 37s	remaining: 8m 14s
5110:	learn: 0.0018564	total: 8m 37s	remaining: 8m 15s
4965:	learn: 0.0021034	total: 8m 37s	remaining: 8m 44s
5207:	learn: 0.0018093	total: 8m 37s	remaining: 7m 56s
5113:	learn: 0.0018134	total: 8m 37s	remaining: 8m 14s
4750:	learn: 0.0019711	total: 8m 37s	remaining: 9m 32s
5111:	learn: 0.0018560	total: 8m 37s	remaining: 8m 15s
4966:	learn: 0.0021033	total: 8m 37s	remaining: 8m 44s
5114:	learn: 0.0018134	total: 8m 37s	remaining: 8m 14s
5208:	learn: 0.0018093	total: 8m 37s	remaining: 7m 56s
4751:	learn: 0.0019709	total: 8m 38s	remaining: 9m 32s
5112:	learn: 0.0018556	total: 8m 37s	remaining: 8m 14s
4967:	learn: 0.0021034	total: 8m 37s	remaining: 8m 44s
5115:	learn: 0.0018133	total: 8m 38s	remaining: 8m 14s
5209:	learn: 0.0018088	total: 8m 38s	remaining: 7m 56s
4752:	learn: 0.0019703	total: 8m 38s	remaining: 9m 31s
5113:	learn: 0.0018551	total: 8m 37s	remaining: 8m 14s
4968:	learn: 0.0021034	total: 8m 38s	remaining: 8m 44s
5116:	learn: 0.0018134	total: 8m 38s	remaining: 8m 14s
5210:	learn: 0.0018088	total: 8m 38s	remaining: 7m 56s
5114:	learn: 0.0018546	total: 8m 38s	remaining: 8m 14s
4753:	learn: 0.0019699	total: 8m 38s	remaining: 9m 31s
4969:	learn: 0.0021034	total: 8m 38s	remaining: 8m 44s
5117:	learn: 0.0018134	total: 8m 38s	remaining: 8m 14s
5211:	learn: 0.0018088	total: 8m 38s	remaining: 7m 56s
4754:	learn: 0.0019698	total: 8m 38s	remaining: 9m 31s
5115:	learn: 0.0018543	total: 8m 38s	remaining: 8m 14s
4970:	learn: 0.0021034	total: 8m 38s	remaining: 8m 44s
5118:	learn: 0.0018133	total: 8m 38s	remaining: 8m 14s
5212:	learn: 0.0018086	total: 8m 38s	remaining: 7m 55s
5116:	learn: 0.0018539	total: 8m 38s	remaining: 8m 14s
4971:	learn: 0.0021034	total: 8m 38s	remaining: 8m 44s
4755:	learn: 0.0019693	total: 8m 38s	remaining: 9m 31s
5213:	learn: 0.0018086	total: 8m 38s	remaining: 7m 55s
5119:	learn: 0.0018130	total: 8m 38s	remaining: 8m 14s
5117:	learn: 0.0018534	total: 8m 38s	remaining: 8m 14s
4756:	learn: 0.0019693	total: 8m 38s	remaining: 9m 31s
4972:	learn: 0.0021034	total: 8m 38s	remaining: 8m 44s
5120:	learn: 0.0018130	total: 8m 38s	remaining: 8m 14s
5214:	learn: 0.0018086	total: 8m 38s	remaining: 7m 55s
5118:	learn: 0.0018531	total: 8m 38s	remaining: 8m 14s
4757:	learn: 0.0019687	total: 8m 38s	remaining: 9m 31s
5121:	learn: 0.0018130	total: 8m 38s	remaining: 8m 13s
4973:	learn: 0.0021034	total: 8m 38s	remaining: 8m 44s
5215:	learn: 0.0018080	total: 8m 38s	remaining: 7m 55s
5119:	learn: 0.0018528	total: 8m 38s	remaining: 8m 14s
4758:	learn: 0.0019687	total: 8m 38s	remaining: 9m 31s
5122:	learn: 0.0018130	total: 8m 38s	remaining: 8m 13s
5216:	learn: 0.0018080	total: 8m 38s	remaining: 7m 55s
4974:	learn: 0.0021034	total: 8m 38s	remaining: 8m 43s
5120:	learn: 0.0018524	total: 8m 38s	remaining: 8m 14s
4759:	learn: 0.0019681	total: 8m 38s	remaining: 9m 31s
5123:	learn: 0.0018123	total: 8m 38s	remaining: 8m 13s
5217:	learn: 0.0018080	total: 8m 38s	remaining: 7m 55s
4975:	learn: 0.0021034	total: 8m 38s	remaining: 8m 43s
4760:	learn: 0.0019675	total: 8m 38s	remaining: 9m 31s
5121:	learn: 0.0018523	total: 8m 38s	remaining: 8m 14s
5124:	learn: 0.0018116	total: 8m 38s	remaining: 8m 13s
5218:	learn: 0.0018080	total: 8m 38s	remaining: 7m 55s
4976:	learn: 0.0021034	total: 8m 38s	remaining: 8m 43s
5122:	learn: 0.0018517	total: 8m 38s	remaining: 8m 13s
4761:	learn: 0.0019668	total: 8m 39s	remaining: 9m 30s
5125:	learn: 0.0018116	total: 8m 39s	remaining: 8m 13s
5219:	learn: 0.0018073	total: 8m 38s	remaining: 7m 55s
4977:	learn: 0.0021034	total: 8m 39s	remaining: 8m 43s
5123:	learn: 0.0018513	total: 8m 38s	remaining: 8m 13s
5126:	learn: 0.0018116	total: 8m 39s	remaining: 8m 13s
4762:	learn: 0.0019662	total: 8m 39s	remaining: 9m 30s
5220:	learn: 0.0018073	total: 8m 39s	remaining: 7m 55s
5124:	learn: 0.0018504	total: 8m 39s	remaining: 8m 13s
4978:	learn: 0.0021034	total: 8m 39s	remaining: 8m 43s
5127:	learn: 0.0018116	total: 8m 39s	remaining: 8m 13s
4763:	learn: 0.0019656	total: 8m 39s	remaining: 9m 30s
5125:	learn: 0.0018504	total: 8m 39s	remaining: 8m 13s
5221:	learn: 0.0018067	total: 8m 39s	remaining: 7m 55s
4979:	learn: 0.0021033	total: 8m 39s	remaining: 8m 43s
5128:	learn: 0.0018116	total: 8m 39s	remaining: 8m 13s
5126:	learn: 0.0018499	total: 8m 39s	remaining: 8m 13s
4764:	learn: 0.0019653	total: 8m 39s	remaining: 9m 30s
4980:	learn: 0.0021033	total: 8m 39s	remaining: 8m 43s
5129:	learn: 0.0018116	total: 8m 39s	remaining: 8m 13s
5222:	learn: 0.0018064	total: 8m 39s	remaining: 7m 54s
5127:	learn: 0.0018493	total: 8m 39s	remaining: 8m 13s
5223:	learn: 0.0018062	total: 8m 39s	remaining: 7m 54s
5130:	learn: 0.0018116	total: 8m 39s	remaining: 8m 12s
4765:	learn: 0.0019647	total: 8m 39s	remaining: 9m 30s
4981:	learn: 0.0021033	total: 8m 39s	remaining: 8m 43s
5128:	learn: 0.0018486	total: 8m 39s	remaining: 8m 13s
5131:	learn: 0.0018116	total: 8m 39s	remaining: 8m 12s
4766:	learn: 0.0019642	total: 8m 39s	remaining: 9m 30s
5224:	learn: 0.0018057	total: 8m 39s	remaining: 7m 54s
4982:	learn: 0.0021033	total: 8m 39s	remaining: 8m 43s
5129:	learn: 0.0018486	total: 8m 39s	remaining: 8m 13s
5132:	learn: 0.0018113	total: 8m 39s	remaining: 8m 12s
4767:	learn: 0.0019642	total: 8m 39s	remaining: 9m 30s
5225:	learn: 0.0018057	total: 8m 39s	remaining: 7m 54s
4983:	learn: 0.0021034	total: 8m 39s	remaining: 8m 43s
5133:	learn: 0.0018113	total: 8m 39s	remaining: 8m 12s
5130:	learn: 0.0018486	total: 8m 39s	remaining: 8m 13s
4768:	learn: 0.0019637	total: 8m 39s	remaining: 9m 30s
5226:	learn: 0.0018057	total: 8m 39s	remaining: 7m 54s
4984:	learn: 0.0021034	total: 8m 39s	remaining: 8m 42s
5134:	learn: 0.0018113	total: 8m 39s	remaining: 8m 12s
5227:	learn: 0.0018057	total: 8m 39s	remaining: 7m 54s
5131:	learn: 0.0018481	total: 8m 39s	remaining: 8m 12s
4769:	learn: 0.0019630	total: 8m 39s	remaining: 9m 30s
4985:	learn: 0.0021034	total: 8m 39s	remaining: 8m 42s
5132:	learn: 0.0018480	total: 8m 39s	remaining: 8m 12s
5135:	learn: 0.0018113	total: 8m 39s	remaining: 8m 12s
5228:	learn: 0.0018052	total: 8m 39s	remaining: 7m 54s
4770:	learn: 0.0019624	total: 8m 40s	remaining: 9m 29s
4986:	learn: 0.0021034	total: 8m 39s	remaining: 8m 42s
5136:	learn: 0.0018113	total: 8m 40s	remaining: 8m 12s
5133:	learn: 0.0018474	total: 8m 39s	remaining: 8m 12s
5229:	learn: 0.0018052	total: 8m 40s	remaining: 7m 54s
5137:	learn: 0.0018109	total: 8m 40s	remaining: 8m 12s
5134:	learn: 0.0018469	total: 8m 39s	remaining: 8m 12s
4771:	learn: 0.0019618	total: 8m 40s	remaining: 9m 29s
5230:	learn: 0.0018052	total: 8m 40s	remaining: 7m 54s
4987:	learn: 0.0021034	total: 8m 40s	remaining: 8m 42s
5138:	learn: 0.0018109	total: 8m 40s	remaining: 8m 12s
5135:	learn: 0.0018464	total: 8m 40s	remaining: 8m 12s
4772:	learn: 0.0019612	total: 8m 40s	remaining: 9m 29s
5231:	learn: 0.0018047	total: 8m 40s	remaining: 7m 54s
5139:	learn: 0.0018102	total: 8m 40s	remaining: 8m 11s
4988:	learn: 0.0021034	total: 8m 40s	remaining: 8m 42s
5136:	learn: 0.0018459	total: 8m 40s	remaining: 8m 12s
4773:	learn: 0.0019605	total: 8m 40s	remaining: 9m 29s
5232:	learn: 0.0018042	total: 8m 40s	remaining: 7m 53s
5137:	learn: 0.0018459	total: 8m 40s	remaining: 8m 12s
4989:	learn: 0.0021034	total: 8m 40s	remaining: 8m 42s
5140:	learn: 0.0018098	total: 8m 40s	remaining: 8m 11s
4774:	learn: 0.0019600	total: 8m 40s	remaining: 9m 29s
5138:	learn: 0.0018452	total: 8m 40s	remaining: 8m 12s
5233:	learn: 0.0018037	total: 8m 40s	remaining: 7m 53s
4990:	learn: 0.0021034	total: 8m 40s	remaining: 8m 42s
5141:	learn: 0.0018098	total: 8m 40s	remaining: 8m 11s
4775:	learn: 0.0019595	total: 8m 40s	remaining: 9m 29s
5234:	learn: 0.0018037	total: 8m 40s	remaining: 7m 53s
4991:	learn: 0.0021034	total: 8m 40s	remaining: 8m 42s
5139:	learn: 0.0018449	total: 8m 40s	remaining: 8m 12s
5142:	learn: 0.0018098	total: 8m 40s	remaining: 8m 11s
5235:	learn: 0.0018035	total: 8m 40s	remaining: 7m 53s
4776:	learn: 0.0019594	total: 8m 40s	remaining: 9m 29s
5140:	learn: 0.0018449	total: 8m 40s	remaining: 8m 11s
5143:	learn: 0.0018098	total: 8m 40s	remaining: 8m 11s
5236:	learn: 0.0018035	total: 8m 40s	remaining: 7m 53s
4992:	learn: 0.0021034	total: 8m 40s	remaining: 8m 42s
4777:	learn: 0.0019588	total: 8m 40s	remaining: 9m 29s
5141:	learn: 0.0018443	total: 8m 40s	remaining: 8m 11s
5144:	learn: 0.0018098	total: 8m 40s	remaining: 8m 11s
5237:	learn: 0.0018035	total: 8m 40s	remaining: 7m 53s
4993:	learn: 0.0021034	total: 8m 40s	remaining: 8m 42s
5142:	learn: 0.0018439	total: 8m 40s	remaining: 8m 11s
5238:	learn: 0.0018035	total: 8m 40s	remaining: 7m 53s
4778:	learn: 0.0019587	total: 8m 40s	remaining: 9m 29s
5145:	learn: 0.0018098	total: 8m 40s	remaining: 8m 11s
4994:	learn: 0.0021033	total: 8m 40s	remaining: 8m 41s
5239:	learn: 0.0018035	total: 8m 40s	remaining: 7m 53s
5143:	learn: 0.0018433	total: 8m 40s	remaining: 8m 11s
5146:	learn: 0.0018098	total: 8m 40s	remaining: 8m 11s
4779:	learn: 0.0019581	total: 8m 41s	remaining: 9m 29s
4995:	learn: 0.0021033	total: 8m 41s	remaining: 8m 41s
5144:	learn: 0.0018433	total: 8m 40s	remaining: 8m 11s
5240:	learn: 0.0018030	total: 8m 41s	remaining: 7m 53s
5147:	learn: 0.0018098	total: 8m 41s	remaining: 8m 11s
4996:	learn: 0.0021033	total: 8m 41s	remaining: 8m 41s
4780:	learn: 0.0019574	total: 8m 41s	remaining: 9m 28s
5241:	learn: 0.0018025	total: 8m 41s	remaining: 7m 52s
5148:	learn: 0.0018098	total: 8m 41s	remaining: 8m 11s
5145:	learn: 0.0018427	total: 8m 41s	remaining: 8m 11s
4997:	learn: 0.0021033	total: 8m 41s	remaining: 8m 41s
5242:	learn: 0.0018025	total: 8m 41s	remaining: 7m 52s
4781:	learn: 0.0019568	total: 8m 41s	remaining: 9m 28s
5149:	learn: 0.0018098	total: 8m 41s	remaining: 8m 10s
5146:	learn: 0.0018423	total: 8m 41s	remaining: 8m 11s
4998:	learn: 0.0021033	total: 8m 41s	remaining: 8m 41s
5243:	learn: 0.0018025	total: 8m 41s	remaining: 7m 52s
5147:	learn: 0.0018423	total: 8m 41s	remaining: 8m 11s
4999:	learn: 0.0021026	total: 8m 41s	remaining: 8m 41s
4782:	learn: 0.0019562	total: 8m 41s	remaining: 9m 28s
5150:	learn: 0.0018092	total: 8m 41s	remaining: 8m 10s
5244:	learn: 0.0018020	total: 8m 41s	remaining: 7m 52s
5148:	learn: 0.0018419	total: 8m 41s	remaining: 8m 11s
5151:	learn: 0.0018086	total: 8m 41s	remaining: 8m 10s
4783:	learn: 0.0019557	total: 8m 41s	remaining: 9m 28s
5000:	learn: 0.0021026	total: 8m 41s	remaining: 8m 41s
5149:	learn: 0.0018419	total: 8m 41s	remaining: 8m 11s
5245:	learn: 0.0018016	total: 8m 41s	remaining: 7m 52s
5152:	learn: 0.0018080	total: 8m 41s	remaining: 8m 10s
5246:	learn: 0.0018011	total: 8m 41s	remaining: 7m 52s
4784:	learn: 0.0019551	total: 8m 41s	remaining: 9m 28s
5150:	learn: 0.0018415	total: 8m 41s	remaining: 8m 10s
5001:	learn: 0.0021026	total: 8m 41s	remaining: 8m 41s
5247:	learn: 0.0018003	total: 8m 41s	remaining: 7m 52s
5151:	learn: 0.0018409	total: 8m 41s	remaining: 8m 10s
4785:	learn: 0.0019543	total: 8m 41s	remaining: 9m 28s
5153:	learn: 0.0018071	total: 8m 41s	remaining: 8m 10s
5002:	learn: 0.0021026	total: 8m 41s	remaining: 8m 41s
5248:	learn: 0.0017998	total: 8m 41s	remaining: 7m 52s
5152:	learn: 0.0018409	total: 8m 41s	remaining: 8m 10s
4786:	learn: 0.0019537	total: 8m 41s	remaining: 9m 28s
5154:	learn: 0.0018071	total: 8m 41s	remaining: 8m 10s
5003:	learn: 0.0021026	total: 8m 41s	remaining: 8m 40s
5153:	learn: 0.0018404	total: 8m 41s	remaining: 8m 10s
5249:	learn: 0.0017991	total: 8m 41s	remaining: 7m 52s

5155:	learn: 0.0018071	total: 8m 41s	remaining: 8m 10s
4787:	learn: 0.0019531	total: 8m 41s	remaining: 9m 28s
5004:	learn: 0.0021026	total: 8m 41s	remaining: 8m 40s
5250:	learn: 0.0017986	total: 8m 41s	remaining: 7m 52s
5154:	learn: 0.0018396	total: 8m 41s	remaining: 8m 10s
5156:	learn: 0.0018071	total: 8m 41s	remaining: 8m 10s
5005:	learn: 0.0021026	total: 8m 42s	remaining: 8m 40s
4788:	learn: 0.0019524	total: 8m 42s	remaining: 9m 28s
5155:	learn: 0.0018390	total: 8m 41s	remaining: 8m 10s
5157:	learn: 0.0018071	total: 8m 42s	remaining: 8m 10s
5251:	learn: 0.0017981	total: 8m 42s	remaining: 7m 51s
5006:	learn: 0.0021026	total: 8m 42s	remaining: 8m 40s
5158:	learn: 0.0018071	total: 8m 42s	remaining: 8m 9s
5252:	learn: 0.0017981	total: 8m 42s	remaining: 7m 51s
5156:	learn: 0.0018384	total: 8m 42s	remaining: 8m 10s
4789:	learn: 0.0019524	total: 8m 42s	remaining: 9m 28s
5159:	learn: 0.0018065	total: 8m 42s	remaining: 8m 9s
5007:	learn: 0.0021026	total: 8m 42s	remaining: 8m 40s
4790:	learn: 0.0019517	total: 8m 42s	remaining: 9m 27s
5157:	learn: 0.0018378	total: 8m 42s	remaining: 8m 10s
5253:	learn: 0.0017981	total: 8m 42s	remaining: 7m 51s
5160:	learn: 0.0018059	total: 8m 42s	remaining: 8m 9s
5008:	learn: 0.0021026	total: 8m 42s	remaining: 8m 40s
4791:	learn: 0.0019511	total: 8m 42s	remaining: 9m 27s
5158:	learn: 0.0018372	total: 8m 42s	remaining: 8m 10s
5254:	learn: 0.0017981	total: 8m 42s	remaining: 7m 51s
5161:	learn: 0.0018059	total: 8m 42s	remaining: 8m 9s
5009:	learn: 0.0021026	total: 8m 42s	remaining: 8m 40s
4792:	learn: 0.0019505	total: 8m 42s	remaining: 9m 27s
5159:	learn: 0.0018372	total: 8m 42s	remaining: 8m 9s
5255:	learn: 0.0017975	total: 8m 42s	remaining: 7m 51s
5010:	learn: 0.0021026	total: 8m 42s	remaining: 8m 40s
5162:	learn: 0.0018052	total: 8m 42s	remaining: 8m 9s
4793:	learn: 0.0019500	total: 8m 42s	remaining: 9m 27s
5160:	learn: 0.0018368	total: 8m 42s	remaining: 8m 9s
5256:	learn: 0.0017969	total: 8m 42s	remaining: 7m 51s
5163:	learn: 0.0018052	total: 8m 42s	remaining: 8m 9s
5011:	learn: 0.0021026	total: 8m 42s	remaining: 8m 40s
5161:	learn: 0.0018368	total: 8m 42s	remaining: 8m 9s
4794:	learn: 0.0019493	total: 8m 42s	remaining: 9m 27s
5257:	learn: 0.0017969	total: 8m 42s	remaining: 7m 51s
5164:	learn: 0.0018052	total: 8m 42s	remaining: 8m 9s
5162:	learn: 0.0018365	total: 8m 42s	remaining: 8m 9s
5012:	learn: 0.0021026	total: 8m 42s	remaining: 8m 40s
5258:	learn: 0.0017969	total: 8m 42s	remaining: 7m 51s
4795:	learn: 0.0019488	total: 8m 42s	remaining: 9m 27s
5013:	learn: 0.0021026	total: 8m 42s	remaining: 8m 39s
5163:	learn: 0.0018360	total: 8m 42s	remaining: 8m 9s
5165:	learn: 0.0018052	total: 8m 42s	remaining: 8m 9s
4796:	learn: 0.0019488	total: 8m 42s	remaining: 9m 27s
5164:	learn: 0.0018355	total: 8m 42s	remaining: 8m 9s
5259:	learn: 0.0017969	total: 8m 42s	remaining: 7m 51s
5166:	learn: 0.0018052	total: 8m 42s	remaining: 8m 9s
5014:	learn: 0.0021019	total: 8m 42s	remaining: 8m 39s
5165:	learn: 0.0018355	total: 8m 42s	remaining: 8m 9s
4797:	learn: 0.0019480	total: 8m 43s	remaining: 9m 27s
5260:	learn: 0.0017969	total: 8m 43s	remaining: 7m 51s
5015:	learn: 0.0021019	total: 8m 43s	remaining: 8m 39s
5167:	learn: 0.0018052	total: 8m 43s	remaining: 8m 9s
5166:	learn: 0.0018349	total: 8m 42s	remaining: 8m 9s
5261:	learn: 0.0017969	total: 8m 43s	remaining: 7m 51s
4798:	learn: 0.0019474	total: 8m 43s	remaining: 9m 27s
5016:	learn: 0.0021019	total: 8m 43s	remaining: 8m 39s
5168:	learn: 0.0018049	total: 8m 43s	remaining: 8m 8s
5167:	learn: 0.0018344	total: 8m 43s	remaining: 8m 9s
5262:	learn: 0.0017969	total: 8m 43s	remaining: 7m 50s
4799:	learn: 0.0019468	total: 8m 43s	remaining: 9m 26s
5017:	learn: 0.0021019	total: 8m 43s	remaining: 8m 39s
5169:	learn: 0.0018049	total: 8m 43s	remaining: 8m 8s
5168:	learn: 0.0018344	total: 8m 43s	remaining: 8m 8s
5263:	learn: 0.0017965	total: 8m 43s	remaining: 7m 50s
4800:	learn: 0.0019466	total: 8m 43s	remaining: 9m 26s
5170:	learn: 0.0018049	total: 8m 43s	remaining: 8m 8s
5018:	learn: 0.0021019	total: 8m 43s	remaining: 8m 39s
5169:	learn: 0.0018344	total: 8m 43s	remaining: 8m 8s
5264:	learn: 0.0017965	total: 8m 43s	remaining: 7m 50s
4801:	learn: 0.0019462	total: 8m 43s	remaining: 9m 26s
5171:	learn: 0.0018049	total: 8m 43s	remaining: 8m 8s
5019:	learn: 0.0021019	total: 8m 43s	remaining: 8m 39s
5170:	learn: 0.0018339	total: 8m 43s	remaining: 8m 8s
5265:	learn: 0.0017965	total: 8m 43s	remaining: 7m 50s
4802:	learn: 0.0019451	total: 8m 43s	remaining: 9m 26s
5020:	learn: 0.0021019	total: 8m 43s	remaining: 8m 39s
5172:	learn: 0.0018049	total: 8m 43s	remaining: 8m 8s
5171:	learn: 0.0018339	total: 8m 43s	remaining: 8m 8s
5021:	learn: 0.0021014	total: 8m 43s	remaining: 8m 39s
5266:	learn: 0.0017965	total: 8m 43s	remaining: 7m 50s
4803:	learn: 0.0019445	total: 8m 43s	remaining: 9m 26s
5173:	learn: 0.0018045	total: 8m 43s	remaining: 8m 8s
5022:	learn: 0.0021014	total: 8m 43s	remaining: 8m 38s
5172:	learn: 0.0018339	total: 8m 43s	remaining: 8m 8s
5174:	learn: 0.0018045	total: 8m 43s	remaining: 8m 8s
5267:	learn: 0.0017965	total: 8m 43s	remaining: 7m 50s
4804:	learn: 0.0019445	total: 8m 43s	remaining: 9m 26s
5023:	learn: 0.0021014	total: 8m 43s	remaining: 8m 38s
5173:	learn: 0.0018333	total: 8m 43s	remaining: 8m 8s
5175:	learn: 0.0018045	total: 8m 43s	remaining: 8m 8s
5268:	learn: 0.0017960	total: 8m 43s	remaining: 7m 50s
5024:	learn: 0.0021014	total: 8m 43s	remaining: 8m 38s
4805:	learn: 0.0019439	total: 8m 43s	remaining: 9m 26s
5176:	learn: 0.0018045	total: 8m 43s	remaining: 8m 8s
5174:	learn: 0.0018328	total: 8m 43s	remaining: 8m 8s
5269:	learn: 0.0017960	total: 8m 43s	remaining: 7m 50s
5025:	learn: 0.0021014	total: 8m 43s	remaining: 8m 38s
5177:	learn: 0.0018045	total: 8m 43s	remaining: 8m 7s
4806:	learn: 0.0019433	total: 8m 44s	remaining: 9m 26s
5175:	learn: 0.0018322	total: 8m 43s	remaining: 8m 8s
5270:	learn: 0.0017960	total: 8m 44s	remaining: 7m 50s
5178:	learn: 0.0018046	total: 8m 44s	remaining: 8m 7s
5026:	learn: 0.0021005	total: 8m 44s	remaining: 8m 38s
5176:	learn: 0.0018319	total: 8m 43s	remaining: 8m 8s
5271:	learn: 0.0017960	total: 8m 44s	remaining: 7m 50s
4807:	learn: 0.0019427	total: 8m 44s	remaining: 9m 26s
5179:	learn: 0.0018039	total: 8m 44s	remaining: 8m 7s
5177:	learn: 0.0018319	total: 8m 44s	remaining: 8m 8s
5027:	learn: 0.0021005	total: 8m 44s	remaining: 8m 38s
5272:	learn: 0.0017955	total: 8m 44s	remaining: 7m 49s
4808:	learn: 0.0019421	total: 8m 44s	remaining: 9m 25s
5180:	learn: 0.0018032	total: 8m 44s	remaining: 8m 7s
5178:	learn: 0.0018319	total: 8m 44s	remaining: 8m 7s
5028:	learn: 0.0021005	total: 8m 44s	remaining: 8m 38s
5273:	learn: 0.0017955	total: 8m 44s	remaining: 7m 49s
4809:	learn: 0.0019413	total: 8m 44s	remaining: 9m 25s
5181:	learn: 0.0018032	total: 8m 44s	remaining: 8m 7s
5179:	learn: 0.0018317	total: 8m 44s	remaining: 8m 7s
5274:	learn: 0.0017953	total: 8m 44s	remaining: 7m 49s
5029:	learn: 0.0020996	total: 8m 44s	remaining: 8m 38s
4810:	learn: 0.0019407	total: 8m 44s	remaining: 9m 25s
5180:	learn: 0.0018317	total: 8m 44s	remaining: 8m 7s
5182:	learn: 0.0018029	total: 8m 44s	remaining: 8m 7s
5275:	learn: 0.0017953	total: 8m 44s	remaining: 7m 49s
5030:	learn: 0.0020989	total: 8m 44s	remaining: 8m 38s
5181:	learn: 0.0018317	total: 8m 44s	remaining: 8m 7s
4811:	learn: 0.0019402	total: 8m 44s	remaining: 9m 25s
5183:	learn: 0.0018029	total: 8m 44s	remaining: 8m 7s
5031:	learn: 0.0020989	total: 8m 44s	remaining: 8m 37s
5276:	learn: 0.0017953	total: 8m 44s	remaining: 7m 49s
5182:	learn: 0.0018317	total: 8m 44s	remaining: 8m 7s
4812:	learn: 0.0019392	total: 8m 44s	remaining: 9m 25s
5184:	learn: 0.0018029	total: 8m 44s	remaining: 8m 7s
5277:	learn: 0.0017953	total: 8m 44s	remaining: 7m 49s
5032:	learn: 0.0020989	total: 8m 44s	remaining: 8m 37s
5183:	learn: 0.0018312	total: 8m 44s	remaining: 8m 7s
5033:	learn: 0.0020989	total: 8m 44s	remaining: 8m 37s
4813:	learn: 0.0019385	total: 8m 44s	remaining: 9m 25s
5185:	learn: 0.0018024	total: 8m 44s	remaining: 8m 7s
5278:	learn: 0.0017953	total: 8m 44s	remaining: 7m 49s
5184:	learn: 0.0018308	total: 8m 44s	remaining: 8m 7s
5034:	learn: 0.0020989	total: 8m 44s	remaining: 8m 37s
4814:	learn: 0.0019385	total: 8m 44s	remaining: 9m 25s
5186:	learn: 0.0018024	total: 8m 44s	remaining: 8m 7s
5279:	learn: 0.0017953	total: 8m 44s	remaining: 7m 49s
5185:	learn: 0.0018308	total: 8m 44s	remaining: 8m 7s
5035:	learn: 0.0020989	total: 8m 44s	remaining: 8m 37s
4815:	learn: 0.0019380	total: 8m 45s	remaining: 9m 25s
5280:	learn: 0.0017953	total: 8m 44s	remaining: 7m 49s
5187:	learn: 0.0018021	total: 8m 45s	remaining: 8m 6s
5186:	learn: 0.0018308	total: 8m 44s	remaining: 8m 7s
5036:	learn: 0.0020989	total: 8m 45s	remaining: 8m 37s
5281:	learn: 0.0017952	total: 8m 45s	remaining: 7m 48s
4816:	learn: 0.0019380	total: 8m 45s	remaining: 9m 25s
5188:	learn: 0.0018016	total: 8m 45s	remaining: 8m 6s
5187:	learn: 0.0018307	total: 8m 45s	remaining: 8m 6s
4817:	learn: 0.0019380	total: 8m 45s	remaining: 9m 24s
5037:	learn: 0.0020989	total: 8m 45s	remaining: 8m 37s
5282:	learn: 0.0017949	total: 8m 45s	remaining: 7m 48s
5189:	learn: 0.0018016	total: 8m 45s	remaining: 8m 6s
5188:	learn: 0.0018303	total: 8m 45s	remaining: 8m 6s
4818:	learn: 0.0019376	total: 8m 45s	remaining: 9m 24s
5038:	learn: 0.0020989	total: 8m 45s	remaining: 8m 37s
5190:	learn: 0.0018008	total: 8m 45s	remaining: 8m 6s
5283:	learn: 0.0017949	total: 8m 45s	remaining: 7m 48s
4819:	learn: 0.0019368	total: 8m 45s	remaining: 9m 24s
5189:	learn: 0.0018298	total: 8m 45s	remaining: 8m 6s
5191:	learn: 0.0018005	total: 8m 45s	remaining: 8m 6s
5039:	learn: 0.0020989	total: 8m 45s	remaining: 8m 37s
5284:	learn: 0.0017949	total: 8m 45s	remaining: 7m 48s
4820:	learn: 0.0019363	total: 8m 45s	remaining: 9m 24s
5190:	learn: 0.0018298	total: 8m 45s	remaining: 8m 6s
5192:	learn: 0.0017998	total: 8m 45s	remaining: 8m 6s
5040:	learn: 0.0020989	total: 8m 45s	remaining: 8m 36s
5285:	learn: 0.0017949	total: 8m 45s	remaining: 7m 48s
5191:	learn: 0.0018298	total: 8m 45s	remaining: 8m 6s
5041:	learn: 0.0020989	total: 8m 45s	remaining: 8m 36s
4821:	learn: 0.0019357	total: 8m 45s	remaining: 9m 24s
5193:	learn: 0.0017998	total: 8m 45s	remaining: 8m 6s
5286:	learn: 0.0017949	total: 8m 45s	remaining: 7m 48s
4822:	learn: 0.0019351	total: 8m 45s	remaining: 9m 24s
5042:	learn: 0.0020989	total: 8m 45s	remaining: 8m 36s
5192:	learn: 0.0018293	total: 8m 45s	remaining: 8m 6s
5194:	learn: 0.0017998	total: 8m 45s	remaining: 8m 6s
5287:	learn: 0.0017942	total: 8m 45s	remaining: 7m 48s
4823:	learn: 0.0019345	total: 8m 45s	remaining: 9m 24s
5193:	learn: 0.0018289	total: 8m 45s	remaining: 8m 6s
5043:	learn: 0.0020989	total: 8m 45s	remaining: 8m 36s
5288:	learn: 0.0017937	total: 8m 45s	remaining: 7m 48s
5195:	learn: 0.0017995	total: 8m 45s	remaining: 8m 6s
4824:	learn: 0.0019340	total: 8m 45s	remaining: 9m 24s
5044:	learn: 0.0020989	total: 8m 45s	remaining: 8m 36s
5194:	learn: 0.0018289	total: 8m 45s	remaining: 8m 6s
5289:	learn: 0.0017937	total: 8m 45s	remaining: 7m 48s
5196:	learn: 0.0017990	total: 8m 45s	remaining: 8m 6s
4825:	learn: 0.0019334	total: 8m 46s	remaining: 9m 23s
5197:	learn: 0.0017990	total: 8m 45s	remaining: 8m 5s
5290:	learn: 0.0017937	total: 8m 45s	remaining: 7m 48s
5195:	learn: 0.0018284	total: 8m 45s	remaining: 8m 6s
5045:	learn: 0.0020989	total: 8m 46s	remaining: 8m 36s
4826:	learn: 0.0019331	total: 8m 46s	remaining: 9m 23s
5198:	learn: 0.0017990	total: 8m 46s	remaining: 8m 5s
5291:	learn: 0.0017932	total: 8m 46s	remaining: 7m 48s
5196:	learn: 0.0018279	total: 8m 45s	remaining: 8m 6s
5199:	learn: 0.0017983	total: 8m 46s	remaining: 8m 5s
5046:	learn: 0.0020989	total: 8m 46s	remaining: 8m 36s
4827:	learn: 0.0019331	total: 8m 46s	remaining: 9m 23s
5292:	learn: 0.0017932	total: 8m 46s	remaining: 7m 47s
5197:	learn: 0.0018275	total: 8m 46s	remaining: 8m 6s
5200:	learn: 0.0017984	total: 8m 46s	remaining: 8m 5s
5047:	learn: 0.0020989	total: 8m 46s	remaining: 8m 36s
4828:	learn: 0.0019331	total: 8m 46s	remaining: 9m 23s
5293:	learn: 0.0017932	total: 8m 46s	remaining: 7m 47s
5198:	learn: 0.0018271	total: 8m 46s	remaining: 8m 5s
5201:	learn: 0.0017983	total: 8m 46s	remaining: 8m 5s
5048:	learn: 0.0020989	total: 8m 46s	remaining: 8m 36s
5199:	learn: 0.0018271	total: 8m 46s	remaining: 8m 5s
4829:	learn: 0.0019325	total: 8m 46s	remaining: 9m 23s
5294:	learn: 0.0017927	total: 8m 46s	remaining: 7m 47s
5202:	learn: 0.0017983	total: 8m 46s	remaining: 8m 5s
5049:	learn: 0.0020980	total: 8m 46s	remaining: 8m 36s
5295:	learn: 0.0017922	total: 8m 46s	remaining: 7m 47s
4830:	learn: 0.0019325	total: 8m 46s	remaining: 9m 23s
5200:	learn: 0.0018271	total: 8m 46s	remaining: 8m 5s
5203:	learn: 0.0017983	total: 8m 46s	remaining: 8m 5s
5050:	learn: 0.0020980	total: 8m 46s	remaining: 8m 35s
5296:	learn: 0.0017918	total: 8m 46s	remaining: 7m 47s
5201:	learn: 0.0018271	total: 8m 46s	remaining: 8m 5s
4831:	learn: 0.0019320	total: 8m 46s	remaining: 9m 23s
5051:	learn: 0.0020980	total: 8m 46s	remaining: 8m 35s
5204:	learn: 0.0017984	total: 8m 46s	remaining: 8m 5s
5297:	learn: 0.0017918	total: 8m 46s	remaining: 7m 47s
5202:	learn: 0.0018266	total: 8m 46s	remaining: 8m 5s
5052:	learn: 0.0020981	total: 8m 46s	remaining: 8m 35s
5298:	learn: 0.0017912	total: 8m 46s	remaining: 7m 47s
5205:	learn: 0.0017983	total: 8m 46s	remaining: 8m 5s
4832:	learn: 0.0019313	total: 8m 46s	remaining: 9m 23s
5203:	learn: 0.0018266	total: 8m 46s	remaining: 8m 5s
5053:	learn: 0.0020981	total: 8m 46s	remaining: 8m 35s
4833:	learn: 0.0019306	total: 8m 46s	remaining: 9m 23s
5206:	learn: 0.0017983	total: 8m 46s	remaining: 8m 4s
5299:	learn: 0.0017907	total: 8m 46s	remaining: 7m 47s
5204:	learn: 0.0018261	total: 8m 46s	remaining: 8m 5s
4834:	learn: 0.0019306	total: 8m 46s	remaining: 9m 22s
5054:	learn: 0.0020981	total: 8m 46s	remaining: 8m 35s
5207:	learn: 0.0017983	total: 8m 46s	remaining: 8m 4s
5205:	learn: 0.0018257	total: 8m 46s	remaining: 8m 5s
5300:	learn: 0.0017899	total: 8m 46s	remaining: 7m 47s
4835:	learn: 0.0019299	total: 8m 47s	remaining: 9m 22s
5055:	learn: 0.0020981	total: 8m 47s	remaining: 8m 35s
5208:	learn: 0.0017983	total: 8m 47s	remaining: 8m 4s
5206:	learn: 0.0018252	total: 8m 46s	remaining: 8m 5s
5301:	learn: 0.0017899	total: 8m 47s	remaining: 7m 47s
4836:	learn: 0.0019293	total: 8m 47s	remaining: 9m 22s
5056:	learn: 0.0020981	total: 8m 47s	remaining: 8m 35s
5209:	learn: 0.0017983	total: 8m 47s	remaining: 8m 4s
5207:	learn: 0.0018252	total: 8m 47s	remaining: 8m 4s
5302:	learn: 0.0017899	total: 8m 47s	remaining: 7m 46s
5057:	learn: 0.0020980	total: 8m 47s	remaining: 8m 35s
4837:	learn: 0.0019289	total: 8m 47s	remaining: 9m 22s
5210:	learn: 0.0017983	total: 8m 47s	remaining: 8m 4s
5208:	learn: 0.0018252	total: 8m 47s	remaining: 8m 4s
5058:	learn: 0.0020980	total: 8m 47s	remaining: 8m 34s
5211:	learn: 0.0017983	total: 8m 47s	remaining: 8m 4s
5303:	learn: 0.0017899	total: 8m 47s	remaining: 7m 46s
4838:	learn: 0.0019284	total: 8m 47s	remaining: 9m 22s
5059:	learn: 0.0020980	total: 8m 47s	remaining: 8m 34s
5209:	learn: 0.0018246	total: 8m 47s	remaining: 8m 4s
5304:	learn: 0.0017899	total: 8m 47s	remaining: 7m 46s
5212:	learn: 0.0017983	total: 8m 47s	remaining: 8m 4s
4839:	learn: 0.0019276	total: 8m 47s	remaining: 9m 22s
5060:	learn: 0.0020981	total: 8m 47s	remaining: 8m 34s
5210:	learn: 0.0018246	total: 8m 47s	remaining: 8m 4s
5305:	learn: 0.0017899	total: 8m 47s	remaining: 7m 46s
5213:	learn: 0.0017983	total: 8m 47s	remaining: 8m 4s
4840:	learn: 0.0019269	total: 8m 47s	remaining: 9m 22s
5061:	learn: 0.0020980	total: 8m 47s	remaining: 8m 34s
5214:	learn: 0.0017983	total: 8m 47s	remaining: 8m 4s
5211:	learn: 0.0018246	total: 8m 47s	remaining: 8m 4s
5306:	learn: 0.0017899	total: 8m 47s	remaining: 7m 46s
4841:	learn: 0.0019264	total: 8m 47s	remaining: 9m 22s
5307:	learn: 0.0017899	total: 8m 47s	remaining: 7m 46s
5062:	learn: 0.0020980	total: 8m 47s	remaining: 8m 34s
5215:	learn: 0.0017980	total: 8m 47s	remaining: 8m 4s
5212:	learn: 0.0018246	total: 8m 47s	remaining: 8m 4s
4842:	learn: 0.0019257	total: 8m 47s	remaining: 9m 22s
5063:	learn: 0.0020980	total: 8m 47s	remaining: 8m 34s
5216:	learn: 0.0017980	total: 8m 47s	remaining: 8m 3s
5213:	learn: 0.0018242	total: 8m 47s	remaining: 8m 4s
5308:	learn: 0.0017899	total: 8m 47s	remaining: 7m 46s
4843:	learn: 0.0019252	total: 8m 47s	remaining: 9m 21s
5214:	learn: 0.0018239	total: 8m 47s	remaining: 8m 4s

5064:	learn: 0.0020980	total: 8m 47s	remaining: 8m 34s
5217:	learn: 0.0017980	total: 8m 47s	remaining: 8m 3s
5309:	learn: 0.0017899	total: 8m 47s	remaining: 7m 46s
4844:	learn: 0.0019245	total: 8m 48s	remaining: 9m 21s
5215:	learn: 0.0018239	total: 8m 47s	remaining: 8m 4s
5218:	learn: 0.0017974	total: 8m 48s	remaining: 8m 3s
5065:	learn: 0.0020980	total: 8m 48s	remaining: 8m 34s
4845:	learn: 0.0019239	total: 8m 48s	remaining: 9m 21s
5310:	learn: 0.0017899	total: 8m 48s	remaining: 7m 46s
5216:	learn: 0.0018238	total: 8m 47s	remaining: 8m 4s
5219:	learn: 0.0017974	total: 8m 48s	remaining: 8m 3s
5066:	learn: 0.0020981	total: 8m 48s	remaining: 8m 34s
4846:	learn: 0.0019232	total: 8m 48s	remaining: 9m 21s
5311:	learn: 0.0017898	total: 8m 48s	remaining: 7m 46s
5217:	learn: 0.0018238	total: 8m 48s	remaining: 8m 3s
5220:	learn: 0.0017974	total: 8m 48s	remaining: 8m 3s
5067:	learn: 0.0020981	total: 8m 48s	remaining: 8m 34s
4847:	learn: 0.0019226	total: 8m 48s	remaining: 9m 21s
5312:	learn: 0.0017889	total: 8m 48s	remaining: 7m 45s
5218:	learn: 0.0018235	total: 8m 48s	remaining: 8m 3s
5221:	learn: 0.0017974	total: 8m 48s	remaining: 8m 3s
5068:	learn: 0.0020980	total: 8m 48s	remaining: 8m 33s
5313:	learn: 0.0017888	total: 8m 48s	remaining: 7m 45s
4848:	learn: 0.0019220	total: 8m 48s	remaining: 9m 21s
5219:	learn: 0.0018231	total: 8m 48s	remaining: 8m 3s
5222:	learn: 0.0017974	total: 8m 48s	remaining: 8m 3s
5069:	learn: 0.0020980	total: 8m 48s	remaining: 8m 33s
4849:	learn: 0.0019213	total: 8m 48s	remaining: 9m 21s
5314:	learn: 0.0017888	total: 8m 48s	remaining: 7m 45s
5220:	learn: 0.0018227	total: 8m 48s	remaining: 8m 3s
5223:	learn: 0.0017974	total: 8m 48s	remaining: 8m 3s
5070:	learn: 0.0020980	total: 8m 48s	remaining: 8m 33s
5315:	learn: 0.0017884	total: 8m 48s	remaining: 7m 45s
4850:	learn: 0.0019208	total: 8m 48s	remaining: 9m 21s
5221:	learn: 0.0018227	total: 8m 48s	remaining: 8m 3s
5316:	learn: 0.0017879	total: 8m 48s	remaining: 7m 45s
5224:	learn: 0.0017974	total: 8m 48s	remaining: 8m 3s
5071:	learn: 0.0020980	total: 8m 48s	remaining: 8m 33s
4851:	learn: 0.0019203	total: 8m 48s	remaining: 9m 21s
5222:	learn: 0.0018221	total: 8m 48s	remaining: 8m 3s
5317:	learn: 0.0017874	total: 8m 48s	remaining: 7m 45s
5072:	learn: 0.0020981	total: 8m 48s	remaining: 8m 33s
5225:	learn: 0.0017974	total: 8m 48s	remaining: 8m 3s
5223:	learn: 0.0018217	total: 8m 48s	remaining: 8m 3s
5318:	learn: 0.0017874	total: 8m 48s	remaining: 7m 45s
4852:	learn: 0.0019203	total: 8m 48s	remaining: 9m 20s
5073:	learn: 0.0020980	total: 8m 48s	remaining: 8m 33s
5226:	learn: 0.0017971	total: 8m 48s	remaining: 8m 2s
5224:	learn: 0.0018217	total: 8m 48s	remaining: 8m 3s
5319:	learn: 0.0017871	total: 8m 48s	remaining: 7m 45s
4853:	learn: 0.0019198	total: 8m 48s	remaining: 9m 20s
5074:	learn: 0.0020980	total: 8m 48s	remaining: 8m 33s
5320:	learn: 0.0017867	total: 8m 48s	remaining: 7m 45s
5225:	learn: 0.0018212	total: 8m 48s	remaining: 8m 3s
5227:	learn: 0.0017971	total: 8m 48s	remaining: 8m 2s
4854:	learn: 0.0019190	total: 8m 49s	remaining: 9m 20s
5226:	learn: 0.0018212	total: 8m 48s	remaining: 8m 2s
5075:	learn: 0.0020980	total: 8m 49s	remaining: 8m 33s
5321:	learn: 0.0017867	total: 8m 49s	remaining: 7m 45s
5228:	learn: 0.0017971	total: 8m 49s	remaining: 8m 2s
4855:	learn: 0.0019189	total: 8m 49s	remaining: 9m 20s
5227:	learn: 0.0018212	total: 8m 48s	remaining: 8m 2s
5076:	learn: 0.0020980	total: 8m 49s	remaining: 8m 33s
5322:	learn: 0.0017867	total: 8m 49s	remaining: 7m 44s
5228:	learn: 0.0018206	total: 8m 49s	remaining: 8m 2s
5229:	learn: 0.0017971	total: 8m 49s	remaining: 8m 2s
4856:	learn: 0.0019181	total: 8m 49s	remaining: 9m 20s
5323:	learn: 0.0017858	total: 8m 49s	remaining: 7m 44s
5229:	learn: 0.0018201	total: 8m 49s	remaining: 8m 2s
5077:	learn: 0.0020980	total: 8m 49s	remaining: 8m 33s
4857:	learn: 0.0019173	total: 8m 49s	remaining: 9m 20s
5230:	learn: 0.0017971	total: 8m 49s	remaining: 8m 2s
5324:	learn: 0.0017858	total: 8m 49s	remaining: 7m 44s
4858:	learn: 0.0019168	total: 8m 49s	remaining: 9m 20s
5230:	learn: 0.0018194	total: 8m 49s	remaining: 8m 2s
5078:	learn: 0.0020980	total: 8m 49s	remaining: 8m 32s
5231:	learn: 0.0017971	total: 8m 49s	remaining: 8m 2s
5325:	learn: 0.0017858	total: 8m 49s	remaining: 7m 44s
4859:	learn: 0.0019162	total: 8m 49s	remaining: 9m 20s
5231:	learn: 0.0018191	total: 8m 49s	remaining: 8m 2s
5079:	learn: 0.0020980	total: 8m 49s	remaining: 8m 32s
5232:	learn: 0.0017965	total: 8m 49s	remaining: 8m 2s
5326:	learn: 0.0017858	total: 8m 49s	remaining: 7m 44s
4860:	learn: 0.0019155	total: 8m 49s	remaining: 9m 19s
5080:	learn: 0.0020980	total: 8m 49s	remaining: 8m 32s
5232:	learn: 0.0018191	total: 8m 49s	remaining: 8m 2s
5327:	learn: 0.0017851	total: 8m 49s	remaining: 7m 44s
5233:	learn: 0.0017965	total: 8m 49s	remaining: 8m 2s
4861:	learn: 0.0019149	total: 8m 49s	remaining: 9m 19s
5081:	learn: 0.0020980	total: 8m 49s	remaining: 8m 32s
5328:	learn: 0.0017844	total: 8m 49s	remaining: 7m 44s
5233:	learn: 0.0018186	total: 8m 49s	remaining: 8m 2s
5082:	learn: 0.0020980	total: 8m 49s	remaining: 8m 32s
5234:	learn: 0.0017963	total: 8m 49s	remaining: 8m 2s
4862:	learn: 0.0019143	total: 8m 49s	remaining: 9m 19s
5329:	learn: 0.0017844	total: 8m 49s	remaining: 7m 44s
5083:	learn: 0.0020980	total: 8m 49s	remaining: 8m 32s
4863:	learn: 0.0019136	total: 8m 49s	remaining: 9m 19s
5234:	learn: 0.0018181	total: 8m 49s	remaining: 8m 2s
5235:	learn: 0.0017963	total: 8m 49s	remaining: 8m 2s
5330:	learn: 0.0017839	total: 8m 49s	remaining: 7m 44s
5084:	learn: 0.0020980	total: 8m 49s	remaining: 8m 32s
4864:	learn: 0.0019131	total: 8m 50s	remaining: 9m 19s
5236:	learn: 0.0017963	total: 8m 49s	remaining: 8m 2s
5235:	learn: 0.0018176	total: 8m 49s	remaining: 8m 2s
5331:	learn: 0.0017837	total: 8m 49s	remaining: 7m 43s
5085:	learn: 0.0020980	total: 8m 50s	remaining: 8m 32s
5237:	learn: 0.0017963	total: 8m 50s	remaining: 8m 1s
4865:	learn: 0.0019126	total: 8m 50s	remaining: 9m 19s
5236:	learn: 0.0018172	total: 8m 49s	remaining: 8m 2s
5332:	learn: 0.0017837	total: 8m 50s	remaining: 7m 43s
5238:	learn: 0.0017963	total: 8m 50s	remaining: 8m 1s
5086:	learn: 0.0020980	total: 8m 50s	remaining: 8m 32s
5333:	learn: 0.0017837	total: 8m 50s	remaining: 7m 43s
4866:	learn: 0.0019120	total: 8m 50s	remaining: 9m 19s
5237:	learn: 0.0018168	total: 8m 50s	remaining: 8m 1s
5239:	learn: 0.0017957	total: 8m 50s	remaining: 8m 1s
5087:	learn: 0.0020980	total: 8m 50s	remaining: 8m 31s
5334:	learn: 0.0017837	total: 8m 50s	remaining: 7m 43s
4867:	learn: 0.0019114	total: 8m 50s	remaining: 9m 19s
5238:	learn: 0.0018168	total: 8m 50s	remaining: 8m 1s
5240:	learn: 0.0017957	total: 8m 50s	remaining: 8m 1s
5088:	learn: 0.0020980	total: 8m 50s	remaining: 8m 31s
5335:	learn: 0.0017832	total: 8m 50s	remaining: 7m 43s
5239:	learn: 0.0018164	total: 8m 50s	remaining: 8m 1s
4868:	learn: 0.0019105	total: 8m 50s	remaining: 9m 19s
5089:	learn: 0.0020980	total: 8m 50s	remaining: 8m 31s
5336:	learn: 0.0017830	total: 8m 50s	remaining: 7m 43s
5241:	learn: 0.0017957	total: 8m 50s	remaining: 8m 1s
5240:	learn: 0.0018159	total: 8m 50s	remaining: 8m 1s
4869:	learn: 0.0019098	total: 8m 50s	remaining: 9m 18s
5090:	learn: 0.0020980	total: 8m 50s	remaining: 8m 31s
5337:	learn: 0.0017830	total: 8m 50s	remaining: 7m 43s
5241:	learn: 0.0018153	total: 8m 50s	remaining: 8m 1s
5242:	learn: 0.0017951	total: 8m 50s	remaining: 8m 1s
4870:	learn: 0.0019093	total: 8m 50s	remaining: 9m 18s
5091:	learn: 0.0020980	total: 8m 50s	remaining: 8m 31s
5242:	learn: 0.0018149	total: 8m 50s	remaining: 8m 1s
5338:	learn: 0.0017830	total: 8m 50s	remaining: 7m 43s
5243:	learn: 0.0017951	total: 8m 50s	remaining: 8m 1s
4871:	learn: 0.0019088	total: 8m 50s	remaining: 9m 18s
5243:	learn: 0.0018145	total: 8m 50s	remaining: 8m 1s
5092:	learn: 0.0020980	total: 8m 50s	remaining: 8m 31s
5339:	learn: 0.0017828	total: 8m 50s	remaining: 7m 43s
5244:	learn: 0.0017951	total: 8m 50s	remaining: 8m 1s
4872:	learn: 0.0019082	total: 8m 50s	remaining: 9m 18s
5244:	learn: 0.0018142	total: 8m 50s	remaining: 8m 1s
5245:	learn: 0.0017944	total: 8m 50s	remaining: 8m 1s
5340:	learn: 0.0017823	total: 8m 50s	remaining: 7m 43s
5093:	learn: 0.0020980	total: 8m 50s	remaining: 8m 31s
4873:	learn: 0.0019076	total: 8m 50s	remaining: 9m 18s
5245:	learn: 0.0018137	total: 8m 50s	remaining: 8m 1s
5094:	learn: 0.0020980	total: 8m 50s	remaining: 8m 31s
5341:	learn: 0.0017818	total: 8m 50s	remaining: 7m 42s
5246:	learn: 0.0017944	total: 8m 50s	remaining: 8m
4874:	learn: 0.0019069	total: 8m 51s	remaining: 9m 18s
5246:	learn: 0.0018133	total: 8m 50s	remaining: 8m
5342:	learn: 0.0017818	total: 8m 51s	remaining: 7m 42s
5095:	learn: 0.0020980	total: 8m 51s	remaining: 8m 31s
5247:	learn: 0.0017941	total: 8m 51s	remaining: 8m
4875:	learn: 0.0019063	total: 8m 51s	remaining: 9m 18s
5343:	learn: 0.0017816	total: 8m 51s	remaining: 7m 42s
5247:	learn: 0.0018126	total: 8m 51s	remaining: 8m
5248:	learn: 0.0017936	total: 8m 51s	remaining: 8m
5096:	learn: 0.0020980	total: 8m 51s	remaining: 8m 30s
4876:	learn: 0.0019055	total: 8m 51s	remaining: 9m 18s
5248:	learn: 0.0018123	total: 8m 51s	remaining: 8m
5344:	learn: 0.0017815	total: 8m 51s	remaining: 7m 42s
5249:	learn: 0.0017931	total: 8m 51s	remaining: 8m
5097:	learn: 0.0020980	total: 8m 51s	remaining: 8m 30s
4877:	learn: 0.0019049	total: 8m 51s	remaining: 9m 17s
5250:	learn: 0.0017931	total: 8m 51s	remaining: 8m
5249:	learn: 0.0018123	total: 8m 51s	remaining: 8m
5345:	learn: 0.0017809	total: 8m 51s	remaining: 7m 42s
5098:	learn: 0.0020980	total: 8m 51s	remaining: 8m 30s
5251:	learn: 0.0017930	total: 8m 51s	remaining: 8m
4878:	learn: 0.0019041	total: 8m 51s	remaining: 9m 17s
5250:	learn: 0.0018117	total: 8m 51s	remaining: 8m
5252:	learn: 0.0017930	total: 8m 51s	remaining: 8m
5346:	learn: 0.0017802	total: 8m 51s	remaining: 7m 42s
5099:	learn: 0.0020980	total: 8m 51s	remaining: 8m 30s
4879:	learn: 0.0019037	total: 8m 51s	remaining: 9m 17s
5253:	learn: 0.0017929	total: 8m 51s	remaining: 8m
5251:	learn: 0.0018117	total: 8m 51s	remaining: 8m
5100:	learn: 0.0020980	total: 8m 51s	remaining: 8m 30s
5347:	learn: 0.0017802	total: 8m 51s	remaining: 7m 42s
4880:	learn: 0.0019029	total: 8m 51s	remaining: 9m 17s
5254:	learn: 0.0017923	total: 8m 51s	remaining: 8m
5348:	learn: 0.0017798	total: 8m 51s	remaining: 7m 42s
5252:	learn: 0.0018117	total: 8m 51s	remaining: 8m
5101:	learn: 0.0020980	total: 8m 51s	remaining: 8m 30s
4881:	learn: 0.0019024	total: 8m 51s	remaining: 9m 17s
5255:	learn: 0.0017917	total: 8m 51s	remaining: 7m 59s
5349:	learn: 0.0017793	total: 8m 51s	remaining: 7m 42s
5253:	learn: 0.0018113	total: 8m 51s	remaining: 8m
4882:	learn: 0.0019017	total: 8m 51s	remaining: 9m 17s
5102:	learn: 0.0020980	total: 8m 51s	remaining: 8m 30s
5256:	learn: 0.0017910	total: 8m 51s	remaining: 7m 59s
5350:	learn: 0.0017788	total: 8m 51s	remaining: 7m 42s
5254:	learn: 0.0018109	total: 8m 51s	remaining: 8m
5103:	learn: 0.0020980	total: 8m 51s	remaining: 8m 30s
4883:	learn: 0.0019012	total: 8m 51s	remaining: 9m 17s
5257:	learn: 0.0017905	total: 8m 51s	remaining: 7m 59s
5255:	learn: 0.0018102	total: 8m 51s	remaining: 8m
5351:	learn: 0.0017787	total: 8m 51s	remaining: 7m 41s
4884:	learn: 0.0019003	total: 8m 52s	remaining: 9m 17s
5104:	learn: 0.0020980	total: 8m 52s	remaining: 8m 30s
5258:	learn: 0.0017905	total: 8m 52s	remaining: 7m 59s
5256:	learn: 0.0018098	total: 8m 51s	remaining: 7m 59s
5352:	learn: 0.0017786	total: 8m 52s	remaining: 7m 41s
5105:	learn: 0.0020980	total: 8m 52s	remaining: 8m 30s
4885:	learn: 0.0018995	total: 8m 52s	remaining: 9m 17s
5259:	learn: 0.0017898	total: 8m 52s	remaining: 7m 59s
5257:	learn: 0.0018098	total: 8m 52s	remaining: 7m 59s
5353:	learn: 0.0017783	total: 8m 52s	remaining: 7m 41s
5260:	learn: 0.0017892	total: 8m 52s	remaining: 7m 59s
5258:	learn: 0.0018098	total: 8m 52s	remaining: 7m 59s
5106:	learn: 0.0020980	total: 8m 52s	remaining: 8m 29s
4886:	learn: 0.0018987	total: 8m 52s	remaining: 9m 16s
5354:	learn: 0.0017783	total: 8m 52s	remaining: 7m 41s
5107:	learn: 0.0020970	total: 8m 52s	remaining: 8m 29s
5261:	learn: 0.0017889	total: 8m 52s	remaining: 7m 59s
5259:	learn: 0.0018095	total: 8m 52s	remaining: 7m 59s
4887:	learn: 0.0018980	total: 8m 52s	remaining: 9m 16s
5355:	learn: 0.0017783	total: 8m 52s	remaining: 7m 41s
5262:	learn: 0.0017882	total: 8m 52s	remaining: 7m 59s
4888:	learn: 0.0018980	total: 8m 52s	remaining: 9m 16s
5108:	learn: 0.0020970	total: 8m 52s	remaining: 8m 29s
5260:	learn: 0.0018090	total: 8m 52s	remaining: 7m 59s
5356:	learn: 0.0017779	total: 8m 52s	remaining: 7m 41s
5263:	learn: 0.0017873	total: 8m 52s	remaining: 7m 59s
5261:	learn: 0.0018086	total: 8m 52s	remaining: 7m 59s
5357:	learn: 0.0017779	total: 8m 52s	remaining: 7m 41s
5109:	learn: 0.0020970	total: 8m 52s	remaining: 8m 29s
4889:	learn: 0.0018974	total: 8m 52s	remaining: 9m 16s
5264:	learn: 0.0017873	total: 8m 52s	remaining: 7m 59s
5262:	learn: 0.0018082	total: 8m 52s	remaining: 7m 59s
5358:	learn: 0.0017779	total: 8m 52s	remaining: 7m 41s
5110:	learn: 0.0020970	total: 8m 52s	remaining: 8m 29s
5265:	learn: 0.0017870	total: 8m 52s	remaining: 7m 58s
4890:	learn: 0.0018972	total: 8m 52s	remaining: 9m 16s
5263:	learn: 0.0018077	total: 8m 52s	remaining: 7m 59s
5359:	learn: 0.0017779	total: 8m 52s	remaining: 7m 41s
5266:	learn: 0.0017864	total: 8m 52s	remaining: 7m 58s
5111:	learn: 0.0020970	total: 8m 52s	remaining: 8m 29s
4891:	learn: 0.0018968	total: 8m 52s	remaining: 9m 16s
5264:	learn: 0.0018072	total: 8m 52s	remaining: 7m 59s
5267:	learn: 0.0017858	total: 8m 52s	remaining: 7m 58s
5360:	learn: 0.0017779	total: 8m 52s	remaining: 7m 41s
5112:	learn: 0.0020970	total: 8m 52s	remaining: 8m 29s
5265:	learn: 0.0018067	total: 8m 52s	remaining: 7m 58s
5268:	learn: 0.0017850	total: 8m 52s	remaining: 7m 58s
4892:	learn: 0.0018962	total: 8m 52s	remaining: 9m 16s
5361:	learn: 0.0017779	total: 8m 52s	remaining: 7m 40s
4893:	learn: 0.0018953	total: 8m 53s	remaining: 9m 16s
5113:	learn: 0.0020970	total: 8m 53s	remaining: 8m 29s
5266:	learn: 0.0018063	total: 8m 52s	remaining: 7m 58s
5269:	learn: 0.0017846	total: 8m 53s	remaining: 7m 58s
5362:	learn: 0.0017778	total: 8m 53s	remaining: 7m 40s
5114:	learn: 0.0020970	total: 8m 53s	remaining: 8m 29s
5267:	learn: 0.0018057	total: 8m 53s	remaining: 7m 58s
4894:	learn: 0.0018948	total: 8m 53s	remaining: 9m 16s
5270:	learn: 0.0017839	total: 8m 53s	remaining: 7m 58s
5363:	learn: 0.0017779	total: 8m 53s	remaining: 7m 40s
5115:	learn: 0.0020970	total: 8m 53s	remaining: 8m 29s
5268:	learn: 0.0018057	total: 8m 53s	remaining: 7m 58s
4895:	learn: 0.0018943	total: 8m 53s	remaining: 9m 15s
5271:	learn: 0.0017839	total: 8m 53s	remaining: 7m 58s
5364:	learn: 0.0017779	total: 8m 53s	remaining: 7m 40s
5116:	learn: 0.0020970	total: 8m 53s	remaining: 8m 28s
4896:	learn: 0.0018935	total: 8m 53s	remaining: 9m 15s
5272:	learn: 0.0017836	total: 8m 53s	remaining: 7m 58s
5269:	learn: 0.0018052	total: 8m 53s	remaining: 7m 58s
5117:	learn: 0.0020970	total: 8m 53s	remaining: 8m 28s
5365:	learn: 0.0017779	total: 8m 53s	remaining: 7m 40s
5270:	learn: 0.0018046	total: 8m 53s	remaining: 7m 58s
4897:	learn: 0.0018928	total: 8m 53s	remaining: 9m 15s
5118:	learn: 0.0020970	total: 8m 53s	remaining: 8m 28s
5273:	learn: 0.0017834	total: 8m 53s	remaining: 7m 58s
5366:	learn: 0.0017773	total: 8m 53s	remaining: 7m 40s
5271:	learn: 0.0018045	total: 8m 53s	remaining: 7m 58s
5367:	learn: 0.0017773	total: 8m 53s	remaining: 7m 40s
4898:	learn: 0.0018922	total: 8m 53s	remaining: 9m 15s
5119:	learn: 0.0020970	total: 8m 53s	remaining: 8m 28s
5274:	learn: 0.0017834	total: 8m 53s	remaining: 7m 57s
5272:	learn: 0.0018040	total: 8m 53s	remaining: 7m 58s
5120:	learn: 0.0020970	total: 8m 53s	remaining: 8m 28s
5368:	learn: 0.0017773	total: 8m 53s	remaining: 7m 40s
4899:	learn: 0.0018917	total: 8m 53s	remaining: 9m 15s
5275:	learn: 0.0017834	total: 8m 53s	remaining: 7m 57s
5273:	learn: 0.0018034	total: 8m 53s	remaining: 7m 58s
5121:	learn: 0.0020970	total: 8m 53s	remaining: 8m 28s
5369:	learn: 0.0017773	total: 8m 53s	remaining: 7m 40s
4900:	learn: 0.0018911	total: 8m 53s	remaining: 9m 15s
5276:	learn: 0.0017831	total: 8m 53s	remaining: 7m 57s
5274:	learn: 0.0018034	total: 8m 53s	remaining: 7m 58s
5122:	learn: 0.0020970	total: 8m 53s	remaining: 8m 28s
5370:	learn: 0.0017773	total: 8m 53s	remaining: 7m 40s
4901:	learn: 0.0018906	total: 8m 53s	remaining: 9m 15s
5275:	learn: 0.0018032	total: 8m 53s	remaining: 7m 57s

5277:	learn: 0.0017824	total: 8m 53s	remaining: 7m 57s
5123:	learn: 0.0020967	total: 8m 53s	remaining: 8m 28s
4902:	learn: 0.0018906	total: 8m 54s	remaining: 9m 15s
5371:	learn: 0.0017773	total: 8m 53s	remaining: 7m 39s
5278:	learn: 0.0017824	total: 8m 54s	remaining: 7m 57s
5276:	learn: 0.0018032	total: 8m 53s	remaining: 7m 57s
5124:	learn: 0.0020967	total: 8m 54s	remaining: 8m 27s
5372:	learn: 0.0017768	total: 8m 54s	remaining: 7m 39s
4903:	learn: 0.0018900	total: 8m 54s	remaining: 9m 15s
5277:	learn: 0.0018032	total: 8m 53s	remaining: 7m 57s
5279:	learn: 0.0017814	total: 8m 54s	remaining: 7m 57s
5125:	learn: 0.0020967	total: 8m 54s	remaining: 8m 27s
5373:	learn: 0.0017763	total: 8m 54s	remaining: 7m 39s
5278:	learn: 0.0018026	total: 8m 54s	remaining: 7m 57s
4904:	learn: 0.0018897	total: 8m 54s	remaining: 9m 14s
5280:	learn: 0.0017814	total: 8m 54s	remaining: 7m 57s
5374:	learn: 0.0017763	total: 8m 54s	remaining: 7m 39s
5126:	learn: 0.0020967	total: 8m 54s	remaining: 8m 27s
5279:	learn: 0.0018021	total: 8m 54s	remaining: 7m 57s
4905:	learn: 0.0018892	total: 8m 54s	remaining: 9m 14s
5375:	learn: 0.0017763	total: 8m 54s	remaining: 7m 39s
5127:	learn: 0.0020967	total: 8m 54s	remaining: 8m 27s
5281:	learn: 0.0017809	total: 8m 54s	remaining: 7m 57s
5280:	learn: 0.0018015	total: 8m 54s	remaining: 7m 57s
5376:	learn: 0.0017762	total: 8m 54s	remaining: 7m 39s
5128:	learn: 0.0020967	total: 8m 54s	remaining: 8m 27s
4906:	learn: 0.0018888	total: 8m 54s	remaining: 9m 14s
5282:	learn: 0.0017809	total: 8m 54s	remaining: 7m 57s
5377:	learn: 0.0017758	total: 8m 54s	remaining: 7m 39s
5281:	learn: 0.0018010	total: 8m 54s	remaining: 7m 57s
5129:	learn: 0.0020967	total: 8m 54s	remaining: 8m 27s
4907:	learn: 0.0018883	total: 8m 54s	remaining: 9m 14s
5283:	learn: 0.0017809	total: 8m 54s	remaining: 7m 57s
5130:	learn: 0.0020967	total: 8m 54s	remaining: 8m 27s
5282:	learn: 0.0018005	total: 8m 54s	remaining: 7m 57s
5378:	learn: 0.0017758	total: 8m 54s	remaining: 7m 39s
4908:	learn: 0.0018879	total: 8m 54s	remaining: 9m 14s
5284:	learn: 0.0017801	total: 8m 54s	remaining: 7m 56s
4909:	learn: 0.0018874	total: 8m 54s	remaining: 9m 14s
5379:	learn: 0.0017758	total: 8m 54s	remaining: 7m 39s
5283:	learn: 0.0017999	total: 8m 54s	remaining: 7m 57s
5131:	learn: 0.0020957	total: 8m 54s	remaining: 8m 27s
5285:	learn: 0.0017797	total: 8m 54s	remaining: 7m 56s
4910:	learn: 0.0018868	total: 8m 54s	remaining: 9m 14s
5284:	learn: 0.0017995	total: 8m 54s	remaining: 7m 57s
5380:	learn: 0.0017758	total: 8m 54s	remaining: 7m 39s
5286:	learn: 0.0017797	total: 8m 54s	remaining: 7m 56s
5132:	learn: 0.0020957	total: 8m 54s	remaining: 8m 27s
5285:	learn: 0.0017995	total: 8m 54s	remaining: 7m 56s
4911:	learn: 0.0018860	total: 8m 54s	remaining: 9m 14s
5381:	learn: 0.0017758	total: 8m 54s	remaining: 7m 38s
5287:	learn: 0.0017797	total: 8m 54s	remaining: 7m 56s
5133:	learn: 0.0020957	total: 8m 54s	remaining: 8m 27s
4912:	learn: 0.0018853	total: 8m 55s	remaining: 9m 13s
5286:	learn: 0.0017990	total: 8m 54s	remaining: 7m 56s
5382:	learn: 0.0017758	total: 8m 54s	remaining: 7m 38s
5134:	learn: 0.0020957	total: 8m 55s	remaining: 8m 26s
5288:	learn: 0.0017797	total: 8m 55s	remaining: 7m 56s
4913:	learn: 0.0018853	total: 8m 55s	remaining: 9m 13s
5287:	learn: 0.0017987	total: 8m 54s	remaining: 7m 56s
5383:	learn: 0.0017758	total: 8m 55s	remaining: 7m 38s
5135:	learn: 0.0020957	total: 8m 55s	remaining: 8m 26s
5289:	learn: 0.0017797	total: 8m 55s	remaining: 7m 56s
5288:	learn: 0.0017983	total: 8m 55s	remaining: 7m 56s
5384:	learn: 0.0017758	total: 8m 55s	remaining: 7m 38s
5136:	learn: 0.0020957	total: 8m 55s	remaining: 8m 26s
4914:	learn: 0.0018853	total: 8m 55s	remaining: 9m 13s
5290:	learn: 0.0017797	total: 8m 55s	remaining: 7m 56s
5289:	learn: 0.0017980	total: 8m 55s	remaining: 7m 56s
5385:	learn: 0.0017753	total: 8m 55s	remaining: 7m 38s
4915:	learn: 0.0018849	total: 8m 55s	remaining: 9m 13s
5137:	learn: 0.0020957	total: 8m 55s	remaining: 8m 26s
5290:	learn: 0.0017974	total: 8m 55s	remaining: 7m 56s
5291:	learn: 0.0017797	total: 8m 55s	remaining: 7m 56s
5386:	learn: 0.0017753	total: 8m 55s	remaining: 7m 38s
5138:	learn: 0.0020957	total: 8m 55s	remaining: 8m 26s
5291:	learn: 0.0017968	total: 8m 55s	remaining: 7m 56s
4916:	learn: 0.0018841	total: 8m 55s	remaining: 9m 13s
5292:	learn: 0.0017797	total: 8m 55s	remaining: 7m 56s
5387:	learn: 0.0017753	total: 8m 55s	remaining: 7m 38s
5139:	learn: 0.0020957	total: 8m 55s	remaining: 8m 26s
5292:	learn: 0.0017964	total: 8m 55s	remaining: 7m 56s
5388:	learn: 0.0017748	total: 8m 55s	remaining: 7m 38s
4917:	learn: 0.0018841	total: 8m 55s	remaining: 9m 13s
5293:	learn: 0.0017797	total: 8m 55s	remaining: 7m 56s
5140:	learn: 0.0020957	total: 8m 55s	remaining: 8m 26s
5293:	learn: 0.0017964	total: 8m 55s	remaining: 7m 56s
5389:	learn: 0.0017744	total: 8m 55s	remaining: 7m 38s
5141:	learn: 0.0020957	total: 8m 55s	remaining: 8m 26s
5294:	learn: 0.0017792	total: 8m 55s	remaining: 7m 56s
4918:	learn: 0.0018834	total: 8m 55s	remaining: 9m 13s
5390:	learn: 0.0017744	total: 8m 55s	remaining: 7m 38s
5294:	learn: 0.0017960	total: 8m 55s	remaining: 7m 55s
5142:	learn: 0.0020948	total: 8m 55s	remaining: 8m 25s
5295:	learn: 0.0017790	total: 8m 55s	remaining: 7m 55s
4919:	learn: 0.0018826	total: 8m 55s	remaining: 9m 13s
5391:	learn: 0.0017739	total: 8m 55s	remaining: 7m 37s
5143:	learn: 0.0020948	total: 8m 55s	remaining: 8m 25s
5295:	learn: 0.0017960	total: 8m 55s	remaining: 7m 55s
4920:	learn: 0.0018826	total: 8m 55s	remaining: 9m 13s
5296:	learn: 0.0017790	total: 8m 55s	remaining: 7m 55s
5392:	learn: 0.0017734	total: 8m 55s	remaining: 7m 37s
5144:	learn: 0.0020948	total: 8m 55s	remaining: 8m 25s
5296:	learn: 0.0017958	total: 8m 55s	remaining: 7m 55s
4921:	learn: 0.0018821	total: 8m 56s	remaining: 9m 13s
5393:	learn: 0.0017729	total: 8m 55s	remaining: 7m 37s
5297:	learn: 0.0017790	total: 8m 56s	remaining: 7m 55s
5297:	learn: 0.0017958	total: 8m 55s	remaining: 7m 55s
5145:	learn: 0.0020948	total: 8m 56s	remaining: 8m 25s
5298:	learn: 0.0017790	total: 8m 56s	remaining: 7m 55s
4922:	learn: 0.0018813	total: 8m 56s	remaining: 9m 12s
5394:	learn: 0.0017729	total: 8m 56s	remaining: 7m 37s
5146:	learn: 0.0020948	total: 8m 56s	remaining: 8m 25s
5298:	learn: 0.0017955	total: 8m 56s	remaining: 7m 55s
5299:	learn: 0.0017790	total: 8m 56s	remaining: 7m 55s
5395:	learn: 0.0017729	total: 8m 56s	remaining: 7m 37s
4923:	learn: 0.0018807	total: 8m 56s	remaining: 9m 12s
5299:	learn: 0.0017955	total: 8m 56s	remaining: 7m 55s
5147:	learn: 0.0020948	total: 8m 56s	remaining: 8m 25s
5300:	learn: 0.0017790	total: 8m 56s	remaining: 7m 55s
5396:	learn: 0.0017724	total: 8m 56s	remaining: 7m 37s
4924:	learn: 0.0018807	total: 8m 56s	remaining: 9m 12s
5300:	learn: 0.0017950	total: 8m 56s	remaining: 7m 55s
5148:	learn: 0.0020948	total: 8m 56s	remaining: 8m 25s
5397:	learn: 0.0017724	total: 8m 56s	remaining: 7m 37s
5301:	learn: 0.0017787	total: 8m 56s	remaining: 7m 55s
4925:	learn: 0.0018801	total: 8m 56s	remaining: 9m 12s
5301:	learn: 0.0017950	total: 8m 56s	remaining: 7m 55s
5149:	learn: 0.0020948	total: 8m 56s	remaining: 8m 25s
5398:	learn: 0.0017724	total: 8m 56s	remaining: 7m 37s
5302:	learn: 0.0017787	total: 8m 56s	remaining: 7m 55s
5302:	learn: 0.0017949	total: 8m 56s	remaining: 7m 55s
4926:	learn: 0.0018796	total: 8m 56s	remaining: 9m 12s
5399:	learn: 0.0017724	total: 8m 56s	remaining: 7m 37s
5150:	learn: 0.0020948	total: 8m 56s	remaining: 8m 25s
5303:	learn: 0.0017784	total: 8m 56s	remaining: 7m 55s
5303:	learn: 0.0017944	total: 8m 56s	remaining: 7m 55s
4927:	learn: 0.0018796	total: 8m 56s	remaining: 9m 12s
5400:	learn: 0.0017724	total: 8m 56s	remaining: 7m 36s
5151:	learn: 0.0020948	total: 8m 56s	remaining: 8m 25s
5304:	learn: 0.0017784	total: 8m 56s	remaining: 7m 55s
4928:	learn: 0.0018791	total: 8m 56s	remaining: 9m 12s
5304:	learn: 0.0017944	total: 8m 56s	remaining: 7m 54s
5401:	learn: 0.0017724	total: 8m 56s	remaining: 7m 36s
5152:	learn: 0.0020948	total: 8m 56s	remaining: 8m 24s
5305:	learn: 0.0017784	total: 8m 56s	remaining: 7m 54s
5305:	learn: 0.0017939	total: 8m 56s	remaining: 7m 54s
5402:	learn: 0.0017724	total: 8m 56s	remaining: 7m 36s
4929:	learn: 0.0018784	total: 8m 56s	remaining: 9m 12s
5153:	learn: 0.0020948	total: 8m 56s	remaining: 8m 24s
5306:	learn: 0.0017934	total: 8m 56s	remaining: 7m 54s
5306:	learn: 0.0017784	total: 8m 56s	remaining: 7m 54s
5403:	learn: 0.0017724	total: 8m 56s	remaining: 7m 36s
4930:	learn: 0.0018779	total: 8m 57s	remaining: 9m 12s
5154:	learn: 0.0020948	total: 8m 57s	remaining: 8m 24s
5307:	learn: 0.0017784	total: 8m 57s	remaining: 7m 54s
5307:	learn: 0.0017932	total: 8m 56s	remaining: 7m 54s
4931:	learn: 0.0018772	total: 8m 57s	remaining: 9m 11s
5404:	learn: 0.0017724	total: 8m 57s	remaining: 7m 36s
5308:	learn: 0.0017784	total: 8m 57s	remaining: 7m 54s
5155:	learn: 0.0020948	total: 8m 57s	remaining: 8m 24s
5308:	learn: 0.0017932	total: 8m 57s	remaining: 7m 54s
5405:	learn: 0.0017719	total: 8m 57s	remaining: 7m 36s
5309:	learn: 0.0017781	total: 8m 57s	remaining: 7m 54s
4932:	learn: 0.0018765	total: 8m 57s	remaining: 9m 11s
5156:	learn: 0.0020948	total: 8m 57s	remaining: 8m 24s
5309:	learn: 0.0017927	total: 8m 57s	remaining: 7m 54s
5406:	learn: 0.0017719	total: 8m 57s	remaining: 7m 36s
5157:	learn: 0.0020948	total: 8m 57s	remaining: 8m 24s
5310:	learn: 0.0017781	total: 8m 57s	remaining: 7m 54s
4933:	learn: 0.0018755	total: 8m 57s	remaining: 9m 11s
5310:	learn: 0.0017927	total: 8m 57s	remaining: 7m 54s
5158:	learn: 0.0020948	total: 8m 57s	remaining: 8m 24s
5407:	learn: 0.0017719	total: 8m 57s	remaining: 7m 36s
5311:	learn: 0.0017778	total: 8m 57s	remaining: 7m 54s
4934:	learn: 0.0018750	total: 8m 57s	remaining: 9m 11s
5159:	learn: 0.0020948	total: 8m 57s	remaining: 8m 24s
5408:	learn: 0.0017713	total: 8m 57s	remaining: 7m 36s
5311:	learn: 0.0017926	total: 8m 57s	remaining: 7m 54s
5312:	learn: 0.0017778	total: 8m 57s	remaining: 7m 54s
4935:	learn: 0.0018746	total: 8m 57s	remaining: 9m 11s
5409:	learn: 0.0017709	total: 8m 57s	remaining: 7m 36s
5160:	learn: 0.0020948	total: 8m 57s	remaining: 8m 24s
5312:	learn: 0.0017926	total: 8m 57s	remaining: 7m 54s
5313:	learn: 0.0017778	total: 8m 57s	remaining: 7m 54s
5410:	learn: 0.0017709	total: 8m 57s	remaining: 7m 35s
4936:	learn: 0.0018740	total: 8m 57s	remaining: 9m 11s
5161:	learn: 0.0020948	total: 8m 57s	remaining: 8m 23s
5411:	learn: 0.0017709	total: 8m 57s	remaining: 7m 35s
5314:	learn: 0.0017778	total: 8m 57s	remaining: 7m 53s
5313:	learn: 0.0017921	total: 8m 57s	remaining: 7m 54s
4937:	learn: 0.0018735	total: 8m 57s	remaining: 9m 11s
5412:	learn: 0.0017709	total: 8m 57s	remaining: 7m 35s
5162:	learn: 0.0020939	total: 8m 57s	remaining: 8m 23s
5315:	learn: 0.0017778	total: 8m 57s	remaining: 7m 53s
5314:	learn: 0.0017921	total: 8m 57s	remaining: 7m 53s
5413:	learn: 0.0017708	total: 8m 57s	remaining: 7m 35s
4938:	learn: 0.0018729	total: 8m 57s	remaining: 9m 11s
5316:	learn: 0.0017778	total: 8m 57s	remaining: 7m 53s
5163:	learn: 0.0020939	total: 8m 57s	remaining: 8m 23s
5315:	learn: 0.0017921	total: 8m 57s	remaining: 7m 53s
5414:	learn: 0.0017708	total: 8m 57s	remaining: 7m 35s
5164:	learn: 0.0020939	total: 8m 57s	remaining: 8m 23s
5317:	learn: 0.0017778	total: 8m 58s	remaining: 7m 53s
5415:	learn: 0.0017708	total: 8m 57s	remaining: 7m 35s
5316:	learn: 0.0017918	total: 8m 57s	remaining: 7m 53s
4939:	learn: 0.0018723	total: 8m 58s	remaining: 9m 11s
5165:	learn: 0.0020939	total: 8m 58s	remaining: 8m 23s
5318:	learn: 0.0017778	total: 8m 58s	remaining: 7m 53s
5317:	learn: 0.0017914	total: 8m 57s	remaining: 7m 53s
5416:	learn: 0.0017708	total: 8m 58s	remaining: 7m 35s
4940:	learn: 0.0018723	total: 8m 58s	remaining: 9m 11s
5319:	learn: 0.0017778	total: 8m 58s	remaining: 7m 53s
5318:	learn: 0.0017910	total: 8m 58s	remaining: 7m 53s
5166:	learn: 0.0020939	total: 8m 58s	remaining: 8m 23s
5417:	learn: 0.0017704	total: 8m 58s	remaining: 7m 35s
5167:	learn: 0.0020939	total: 8m 58s	remaining: 8m 23s
5320:	learn: 0.0017778	total: 8m 58s	remaining: 7m 53s
4941:	learn: 0.0018717	total: 8m 58s	remaining: 9m 10s
5319:	learn: 0.0017904	total: 8m 58s	remaining: 7m 53s
5418:	learn: 0.0017699	total: 8m 58s	remaining: 7m 35s
5168:	learn: 0.0020939	total: 8m 58s	remaining: 8m 23s
5321:	learn: 0.0017773	total: 8m 58s	remaining: 7m 53s
4942:	learn: 0.0018712	total: 8m 58s	remaining: 9m 10s
5320:	learn: 0.0017899	total: 8m 58s	remaining: 7m 53s
5169:	learn: 0.0020930	total: 8m 58s	remaining: 8m 23s
5419:	learn: 0.0017699	total: 8m 58s	remaining: 7m 34s
5322:	learn: 0.0017773	total: 8m 58s	remaining: 7m 53s
5321:	learn: 0.0017895	total: 8m 58s	remaining: 7m 53s
4943:	learn: 0.0018703	total: 8m 58s	remaining: 9m 10s
5170:	learn: 0.0020930	total: 8m 58s	remaining: 8m 22s
5420:	learn: 0.0017694	total: 8m 58s	remaining: 7m 34s
5323:	learn: 0.0017773	total: 8m 58s	remaining: 7m 53s
5322:	learn: 0.0017891	total: 8m 58s	remaining: 7m 53s
5171:	learn: 0.0020930	total: 8m 58s	remaining: 8m 22s
4944:	learn: 0.0018697	total: 8m 58s	remaining: 9m 10s
5324:	learn: 0.0017773	total: 8m 58s	remaining: 7m 52s
5421:	learn: 0.0017690	total: 8m 58s	remaining: 7m 34s
5323:	learn: 0.0017887	total: 8m 58s	remaining: 7m 53s
5325:	learn: 0.0017769	total: 8m 58s	remaining: 7m 52s
5172:	learn: 0.0020930	total: 8m 58s	remaining: 8m 22s
4945:	learn: 0.0018688	total: 8m 58s	remaining: 9m 10s
5422:	learn: 0.0017685	total: 8m 58s	remaining: 7m 34s
5324:	learn: 0.0017887	total: 8m 58s	remaining: 7m 52s
5326:	learn: 0.0017769	total: 8m 58s	remaining: 7m 52s
4946:	learn: 0.0018681	total: 8m 58s	remaining: 9m 10s
5173:	learn: 0.0020930	total: 8m 58s	remaining: 8m 22s
5423:	learn: 0.0017678	total: 8m 58s	remaining: 7m 34s
5327:	learn: 0.0017769	total: 8m 58s	remaining: 7m 52s
5325:	learn: 0.0017887	total: 8m 58s	remaining: 7m 52s
5174:	learn: 0.0020930	total: 8m 58s	remaining: 8m 22s
4947:	learn: 0.0018681	total: 8m 58s	remaining: 9m 10s
5328:	learn: 0.0017769	total: 8m 58s	remaining: 7m 52s
5424:	learn: 0.0017672	total: 8m 58s	remaining: 7m 34s
5326:	learn: 0.0017883	total: 8m 58s	remaining: 7m 52s
5175:	learn: 0.0020930	total: 8m 58s	remaining: 8m 22s
5425:	learn: 0.0017672	total: 8m 59s	remaining: 7m 34s
5329:	learn: 0.0017769	total: 8m 59s	remaining: 7m 52s
4948:	learn: 0.0018676	total: 8m 59s	remaining: 9m 10s
5327:	learn: 0.0017878	total: 8m 58s	remaining: 7m 52s
5176:	learn: 0.0020930	total: 8m 59s	remaining: 8m 22s
5426:	learn: 0.0017672	total: 8m 59s	remaining: 7m 34s
5330:	learn: 0.0017769	total: 8m 59s	remaining: 7m 52s
5328:	learn: 0.0017878	total: 8m 59s	remaining: 7m 52s
4949:	learn: 0.0018668	total: 8m 59s	remaining: 9m 10s
5177:	learn: 0.0020930	total: 8m 59s	remaining: 8m 22s
5427:	learn: 0.0017672	total: 8m 59s	remaining: 7m 34s
5331:	learn: 0.0017769	total: 8m 59s	remaining: 7m 52s
5329:	learn: 0.0017874	total: 8m 59s	remaining: 7m 52s
5428:	learn: 0.0017672	total: 8m 59s	remaining: 7m 34s
4950:	learn: 0.0018662	total: 8m 59s	remaining: 9m 10s
5178:	learn: 0.0020930	total: 8m 59s	remaining: 8m 22s
5330:	learn: 0.0017870	total: 8m 59s	remaining: 7m 52s
5332:	learn: 0.0017769	total: 8m 59s	remaining: 7m 52s
5429:	learn: 0.0017672	total: 8m 59s	remaining: 7m 33s
4951:	learn: 0.0018658	total: 8m 59s	remaining: 9m 9s
5179:	learn: 0.0020928	total: 8m 59s	remaining: 8m 21s
5331:	learn: 0.0017866	total: 8m 59s	remaining: 7m 52s
5333:	learn: 0.0017769	total: 8m 59s	remaining: 7m 51s
5430:	learn: 0.0017672	total: 8m 59s	remaining: 7m 33s
4952:	learn: 0.0018651	total: 8m 59s	remaining: 9m 9s
5334:	learn: 0.0017769	total: 8m 59s	remaining: 7m 51s
5332:	learn: 0.0017861	total: 8m 59s	remaining: 7m 52s
5180:	learn: 0.0020928	total: 8m 59s	remaining: 8m 21s
5431:	learn: 0.0017672	total: 8m 59s	remaining: 7m 33s
4953:	learn: 0.0018646	total: 8m 59s	remaining: 9m 9s
5333:	learn: 0.0017859	total: 8m 59s	remaining: 7m 51s
5335:	learn: 0.0017769	total: 8m 59s	remaining: 7m 51s
5432:	learn: 0.0017672	total: 8m 59s	remaining: 7m 33s
5181:	learn: 0.0020928	total: 8m 59s	remaining: 8m 21s
5334:	learn: 0.0017854	total: 8m 59s	remaining: 7m 51s
4954:	learn: 0.0018640	total: 8m 59s	remaining: 9m 9s
5336:	learn: 0.0017763	total: 8m 59s	remaining: 7m 51s
5433:	learn: 0.0017672	total: 8m 59s	remaining: 7m 33s
5182:	learn: 0.0020928	total: 8m 59s	remaining: 8m 21s
5337:	learn: 0.0017763	total: 8m 59s	remaining: 7m 51s
5335:	learn: 0.0017850	total: 8m 59s	remaining: 7m 51s

4955:	learn: 0.0018634	total: 8m 59s	remaining: 9m 9s
5434:	learn: 0.0017672	total: 8m 59s	remaining: 7m 33s
5183:	learn: 0.0020928	total: 8m 59s	remaining: 8m 21s
5338:	learn: 0.0017763	total: 8m 59s	remaining: 7m 51s
5435:	learn: 0.0017672	total: 8m 59s	remaining: 7m 33s
4956:	learn: 0.0018632	total: 8m 59s	remaining: 9m 9s
5336:	learn: 0.0017846	total: 8m 59s	remaining: 7m 51s
5184:	learn: 0.0020928	total: 9m	remaining: 8m 21s
5339:	learn: 0.0017763	total: 9m	remaining: 7m 51s
5436:	learn: 0.0017667	total: 9m	remaining: 7m 33s
5337:	learn: 0.0017846	total: 8m 59s	remaining: 7m 51s
4957:	learn: 0.0018626	total: 9m	remaining: 9m 9s
5185:	learn: 0.0020928	total: 9m	remaining: 8m 21s
5340:	learn: 0.0017758	total: 9m	remaining: 7m 51s
5338:	learn: 0.0017846	total: 9m	remaining: 7m 51s
5437:	learn: 0.0017666	total: 9m	remaining: 7m 33s
4958:	learn: 0.0018620	total: 9m	remaining: 9m 9s
5339:	learn: 0.0017841	total: 9m	remaining: 7m 51s
5186:	learn: 0.0020928	total: 9m	remaining: 8m 21s
5341:	learn: 0.0017757	total: 9m	remaining: 7m 51s
5438:	learn: 0.0017666	total: 9m	remaining: 7m 33s
4959:	learn: 0.0018614	total: 9m	remaining: 9m 9s
5340:	learn: 0.0017841	total: 9m	remaining: 7m 51s
5187:	learn: 0.0020928	total: 9m	remaining: 8m 21s
5342:	learn: 0.0017757	total: 9m	remaining: 7m 50s
5341:	learn: 0.0017837	total: 9m	remaining: 7m 51s
5439:	learn: 0.0017666	total: 9m	remaining: 7m 32s
5188:	learn: 0.0020928	total: 9m	remaining: 8m 21s
4960:	learn: 0.0018608	total: 9m	remaining: 9m 8s
5343:	learn: 0.0017757	total: 9m	remaining: 7m 50s
5440:	learn: 0.0017662	total: 9m	remaining: 7m 32s
5342:	learn: 0.0017832	total: 9m	remaining: 7m 50s
5189:	learn: 0.0020928	total: 9m	remaining: 8m 20s
5343:	learn: 0.0017828	total: 9m	remaining: 7m 50s
5344:	learn: 0.0017757	total: 9m	remaining: 7m 50s
4961:	learn: 0.0018603	total: 9m	remaining: 9m 8s
5441:	learn: 0.0017662	total: 9m	remaining: 7m 32s
5190:	learn: 0.0020928	total: 9m	remaining: 8m 20s
5344:	learn: 0.0017824	total: 9m	remaining: 7m 50s
5345:	learn: 0.0017757	total: 9m	remaining: 7m 50s
4962:	learn: 0.0018598	total: 9m	remaining: 9m 8s
5442:	learn: 0.0017662	total: 9m	remaining: 7m 32s
5345:	learn: 0.0017823	total: 9m	remaining: 7m 50s
5191:	learn: 0.0020928	total: 9m	remaining: 8m 20s
5346:	learn: 0.0017757	total: 9m	remaining: 7m 50s
5443:	learn: 0.0017662	total: 9m	remaining: 7m 32s
4963:	learn: 0.0018590	total: 9m	remaining: 9m 8s
5346:	learn: 0.0017819	total: 9m	remaining: 7m 50s
5192:	learn: 0.0020928	total: 9m	remaining: 8m 20s
5347:	learn: 0.0017754	total: 9m	remaining: 7m 50s
5444:	learn: 0.0017662	total: 9m	remaining: 7m 32s
4964:	learn: 0.0018590	total: 9m	remaining: 9m 8s
5347:	learn: 0.0017815	total: 9m	remaining: 7m 50s
5193:	learn: 0.0020928	total: 9m	remaining: 8m 20s
5348:	learn: 0.0017754	total: 9m	remaining: 7m 50s
5445:	learn: 0.0017658	total: 9m	remaining: 7m 32s
5348:	learn: 0.0017810	total: 9m	remaining: 7m 50s
4965:	learn: 0.0018585	total: 9m 1s	remaining: 9m 8s
5349:	learn: 0.0017748	total: 9m 1s	remaining: 7m 50s
5446:	learn: 0.0017658	total: 9m 1s	remaining: 7m 32s
5194:	learn: 0.0020928	total: 9m 1s	remaining: 8m 20s
5349:	learn: 0.0017808	total: 9m	remaining: 7m 50s
4966:	learn: 0.0018580	total: 9m 1s	remaining: 9m 8s
5350:	learn: 0.0017748	total: 9m 1s	remaining: 7m 50s
5447:	learn: 0.0017658	total: 9m 1s	remaining: 7m 32s
5195:	learn: 0.0020928	total: 9m 1s	remaining: 8m 20s
5350:	learn: 0.0017803	total: 9m 1s	remaining: 7m 50s
5351:	learn: 0.0017748	total: 9m 1s	remaining: 7m 50s
4967:	learn: 0.0018575	total: 9m 1s	remaining: 9m 8s
5351:	learn: 0.0017800	total: 9m 1s	remaining: 7m 49s
5196:	learn: 0.0020928	total: 9m 1s	remaining: 8m 20s
5448:	learn: 0.0017658	total: 9m 1s	remaining: 7m 32s
5352:	learn: 0.0017748	total: 9m 1s	remaining: 7m 49s
4968:	learn: 0.0018575	total: 9m 1s	remaining: 9m 8s
5197:	learn: 0.0020928	total: 9m 1s	remaining: 8m 20s
5449:	learn: 0.0017658	total: 9m 1s	remaining: 7m 31s
5352:	learn: 0.0017793	total: 9m 1s	remaining: 7m 49s
4969:	learn: 0.0018575	total: 9m 1s	remaining: 9m 7s
5353:	learn: 0.0017748	total: 9m 1s	remaining: 7m 49s
5198:	learn: 0.0020928	total: 9m 1s	remaining: 8m 19s
5450:	learn: 0.0017658	total: 9m 1s	remaining: 7m 31s
5353:	learn: 0.0017787	total: 9m 1s	remaining: 7m 49s
5354:	learn: 0.0017748	total: 9m 1s	remaining: 7m 49s
4970:	learn: 0.0018568	total: 9m 1s	remaining: 9m 7s
5199:	learn: 0.0020928	total: 9m 1s	remaining: 8m 19s
5451:	learn: 0.0017652	total: 9m 1s	remaining: 7m 31s
5354:	learn: 0.0017787	total: 9m 1s	remaining: 7m 49s
4971:	learn: 0.0018563	total: 9m 1s	remaining: 9m 7s
5355:	learn: 0.0017747	total: 9m 1s	remaining: 7m 49s
5200:	learn: 0.0020926	total: 9m 1s	remaining: 8m 19s
5452:	learn: 0.0017652	total: 9m 1s	remaining: 7m 31s
5355:	learn: 0.0017781	total: 9m 1s	remaining: 7m 49s
4972:	learn: 0.0018556	total: 9m 1s	remaining: 9m 7s
5201:	learn: 0.0020926	total: 9m 1s	remaining: 8m 19s
5356:	learn: 0.0017747	total: 9m 1s	remaining: 7m 49s
5453:	learn: 0.0017652	total: 9m 1s	remaining: 7m 31s
5356:	learn: 0.0017776	total: 9m 1s	remaining: 7m 49s
4973:	learn: 0.0018548	total: 9m 1s	remaining: 9m 7s
5202:	learn: 0.0020919	total: 9m 1s	remaining: 8m 19s
5357:	learn: 0.0017747	total: 9m 1s	remaining: 7m 49s
5357:	learn: 0.0017771	total: 9m 1s	remaining: 7m 49s
5454:	learn: 0.0017647	total: 9m 1s	remaining: 7m 31s
5203:	learn: 0.0020919	total: 9m 1s	remaining: 8m 19s
4974:	learn: 0.0018543	total: 9m 1s	remaining: 9m 7s
5358:	learn: 0.0017764	total: 9m 1s	remaining: 7m 49s
5358:	learn: 0.0017748	total: 9m 1s	remaining: 7m 49s
5455:	learn: 0.0017642	total: 9m 1s	remaining: 7m 31s
5204:	learn: 0.0020919	total: 9m 1s	remaining: 8m 19s
4975:	learn: 0.0018536	total: 9m 2s	remaining: 9m 7s
5359:	learn: 0.0017760	total: 9m 1s	remaining: 7m 49s
5359:	learn: 0.0017745	total: 9m 2s	remaining: 7m 49s
5205:	learn: 0.0020919	total: 9m 2s	remaining: 8m 19s
5456:	learn: 0.0017638	total: 9m 2s	remaining: 7m 31s
5360:	learn: 0.0017745	total: 9m 2s	remaining: 7m 49s
5360:	learn: 0.0017757	total: 9m 2s	remaining: 7m 49s
5457:	learn: 0.0017638	total: 9m 2s	remaining: 7m 31s
4976:	learn: 0.0018529	total: 9m 2s	remaining: 9m 7s
5361:	learn: 0.0017742	total: 9m 2s	remaining: 7m 49s
5206:	learn: 0.0020909	total: 9m 2s	remaining: 8m 19s
5361:	learn: 0.0017751	total: 9m 2s	remaining: 7m 48s
4977:	learn: 0.0018524	total: 9m 2s	remaining: 9m 7s
5458:	learn: 0.0017638	total: 9m 2s	remaining: 7m 31s
5362:	learn: 0.0017735	total: 9m 2s	remaining: 7m 48s
5207:	learn: 0.0020909	total: 9m 2s	remaining: 8m 18s
5362:	learn: 0.0017748	total: 9m 2s	remaining: 7m 48s
5363:	learn: 0.0017728	total: 9m 2s	remaining: 7m 48s
4978:	learn: 0.0018518	total: 9m 2s	remaining: 9m 7s
5459:	learn: 0.0017633	total: 9m 2s	remaining: 7m 30s
5208:	learn: 0.0020909	total: 9m 2s	remaining: 8m 18s
5363:	learn: 0.0017742	total: 9m 2s	remaining: 7m 48s
5364:	learn: 0.0017721	total: 9m 2s	remaining: 7m 48s
4979:	learn: 0.0018513	total: 9m 2s	remaining: 9m 6s
5460:	learn: 0.0017633	total: 9m 2s	remaining: 7m 30s
5364:	learn: 0.0017736	total: 9m 2s	remaining: 7m 48s
5209:	learn: 0.0020910	total: 9m 2s	remaining: 8m 18s
5365:	learn: 0.0017715	total: 9m 2s	remaining: 7m 48s
4980:	learn: 0.0018507	total: 9m 2s	remaining: 9m 6s
5461:	learn: 0.0017633	total: 9m 2s	remaining: 7m 30s
5365:	learn: 0.0017731	total: 9m 2s	remaining: 7m 48s
5210:	learn: 0.0020909	total: 9m 2s	remaining: 8m 18s
5366:	learn: 0.0017715	total: 9m 2s	remaining: 7m 48s
5366:	learn: 0.0017727	total: 9m 2s	remaining: 7m 48s
5462:	learn: 0.0017628	total: 9m 2s	remaining: 7m 30s
4981:	learn: 0.0018507	total: 9m 2s	remaining: 9m 6s
5367:	learn: 0.0017715	total: 9m 2s	remaining: 7m 48s
5211:	learn: 0.0020907	total: 9m 2s	remaining: 8m 18s
5463:	learn: 0.0017628	total: 9m 2s	remaining: 7m 30s
5367:	learn: 0.0017726	total: 9m 2s	remaining: 7m 48s
4982:	learn: 0.0018502	total: 9m 2s	remaining: 9m 6s
5464:	learn: 0.0017624	total: 9m 2s	remaining: 7m 30s
5368:	learn: 0.0017708	total: 9m 2s	remaining: 7m 48s
5212:	learn: 0.0020897	total: 9m 2s	remaining: 8m 18s
5368:	learn: 0.0017722	total: 9m 2s	remaining: 7m 48s
4983:	learn: 0.0018502	total: 9m 2s	remaining: 9m 6s
5465:	learn: 0.0017620	total: 9m 2s	remaining: 7m 30s
5369:	learn: 0.0017702	total: 9m 2s	remaining: 7m 48s
5213:	learn: 0.0020897	total: 9m 2s	remaining: 8m 18s
5369:	learn: 0.0017718	total: 9m 2s	remaining: 7m 48s
4984:	learn: 0.0018495	total: 9m 3s	remaining: 9m 6s
5466:	learn: 0.0017619	total: 9m 3s	remaining: 7m 30s
5370:	learn: 0.0017702	total: 9m 3s	remaining: 7m 48s
4985:	learn: 0.0018487	total: 9m 3s	remaining: 9m 6s
5214:	learn: 0.0020897	total: 9m 3s	remaining: 8m 18s
5370:	learn: 0.0017718	total: 9m 3s	remaining: 7m 47s
5467:	learn: 0.0017619	total: 9m 3s	remaining: 7m 30s
5371:	learn: 0.0017702	total: 9m 3s	remaining: 7m 47s
5371:	learn: 0.0017712	total: 9m 3s	remaining: 7m 47s
5215:	learn: 0.0020897	total: 9m 3s	remaining: 8m 18s
5468:	learn: 0.0017619	total: 9m 3s	remaining: 7m 30s
4986:	learn: 0.0018483	total: 9m 3s	remaining: 9m 6s
5372:	learn: 0.0017698	total: 9m 3s	remaining: 7m 47s
5216:	learn: 0.0020897	total: 9m 3s	remaining: 8m 18s
5372:	learn: 0.0017708	total: 9m 3s	remaining: 7m 47s
5469:	learn: 0.0017619	total: 9m 3s	remaining: 7m 29s
4987:	learn: 0.0018482	total: 9m 3s	remaining: 9m 6s
5373:	learn: 0.0017697	total: 9m 3s	remaining: 7m 47s
5217:	learn: 0.0020897	total: 9m 3s	remaining: 8m 17s
5373:	learn: 0.0017708	total: 9m 3s	remaining: 7m 47s
5470:	learn: 0.0017619	total: 9m 3s	remaining: 7m 29s
5374:	learn: 0.0017694	total: 9m 3s	remaining: 7m 47s
4988:	learn: 0.0018477	total: 9m 3s	remaining: 9m 5s
5218:	learn: 0.0020897	total: 9m 3s	remaining: 8m 17s
5374:	learn: 0.0017702	total: 9m 3s	remaining: 7m 47s
5471:	learn: 0.0017619	total: 9m 3s	remaining: 7m 29s
4989:	learn: 0.0018472	total: 9m 3s	remaining: 9m 5s
5375:	learn: 0.0017694	total: 9m 3s	remaining: 7m 47s
5219:	learn: 0.0020897	total: 9m 3s	remaining: 8m 17s
5375:	learn: 0.0017697	total: 9m 3s	remaining: 7m 47s
5472:	learn: 0.0017614	total: 9m 3s	remaining: 7m 29s
5220:	learn: 0.0020896	total: 9m 3s	remaining: 8m 17s
5376:	learn: 0.0017694	total: 9m 3s	remaining: 7m 47s
4990:	learn: 0.0018466	total: 9m 3s	remaining: 9m 5s
5376:	learn: 0.0017697	total: 9m 3s	remaining: 7m 47s
5377:	learn: 0.0017694	total: 9m 3s	remaining: 7m 47s
5473:	learn: 0.0017613	total: 9m 3s	remaining: 7m 29s
5221:	learn: 0.0020889	total: 9m 3s	remaining: 8m 17s
4991:	learn: 0.0018460	total: 9m 3s	remaining: 9m 5s
5377:	learn: 0.0017692	total: 9m 3s	remaining: 7m 47s
5378:	learn: 0.0017689	total: 9m 3s	remaining: 7m 47s
5222:	learn: 0.0020889	total: 9m 3s	remaining: 8m 17s
5474:	learn: 0.0017612	total: 9m 3s	remaining: 7m 29s
4992:	learn: 0.0018454	total: 9m 3s	remaining: 9m 5s
5378:	learn: 0.0017692	total: 9m 3s	remaining: 7m 47s
5379:	learn: 0.0017684	total: 9m 3s	remaining: 7m 47s
5223:	learn: 0.0020889	total: 9m 3s	remaining: 8m 17s
5475:	learn: 0.0017608	total: 9m 3s	remaining: 7m 29s
4993:	learn: 0.0018450	total: 9m 4s	remaining: 9m 5s
5379:	learn: 0.0017691	total: 9m 3s	remaining: 7m 47s
5224:	learn: 0.0020889	total: 9m 4s	remaining: 8m 17s
5380:	learn: 0.0017680	total: 9m 4s	remaining: 7m 47s
5476:	learn: 0.0017602	total: 9m 4s	remaining: 7m 29s
4994:	learn: 0.0018446	total: 9m 4s	remaining: 9m 5s
5225:	learn: 0.0020881	total: 9m 4s	remaining: 8m 17s
5380:	learn: 0.0017688	total: 9m 4s	remaining: 7m 46s
5381:	learn: 0.0017680	total: 9m 4s	remaining: 7m 46s
5477:	learn: 0.0017596	total: 9m 4s	remaining: 7m 29s
4995:	learn: 0.0018440	total: 9m 4s	remaining: 9m 5s
5226:	learn: 0.0020881	total: 9m 4s	remaining: 8m 16s
5382:	learn: 0.0017680	total: 9m 4s	remaining: 7m 46s
5381:	learn: 0.0017685	total: 9m 4s	remaining: 7m 46s
5478:	learn: 0.0017596	total: 9m 4s	remaining: 7m 29s
5383:	learn: 0.0017677	total: 9m 4s	remaining: 7m 46s
4996:	learn: 0.0018440	total: 9m 4s	remaining: 9m 5s
5227:	learn: 0.0020881	total: 9m 4s	remaining: 8m 16s
5382:	learn: 0.0017681	total: 9m 4s	remaining: 7m 46s
5479:	learn: 0.0017590	total: 9m 4s	remaining: 7m 28s
4997:	learn: 0.0018435	total: 9m 4s	remaining: 9m 4s
5228:	learn: 0.0020881	total: 9m 4s	remaining: 8m 16s
5384:	learn: 0.0017677	total: 9m 4s	remaining: 7m 46s
5383:	learn: 0.0017677	total: 9m 4s	remaining: 7m 46s
4998:	learn: 0.0018430	total: 9m 4s	remaining: 9m 4s
5480:	learn: 0.0017584	total: 9m 4s	remaining: 7m 28s
5229:	learn: 0.0020881	total: 9m 4s	remaining: 8m 16s
5385:	learn: 0.0017677	total: 9m 4s	remaining: 7m 46s
5384:	learn: 0.0017677	total: 9m 4s	remaining: 7m 46s
5481:	learn: 0.0017580	total: 9m 4s	remaining: 7m 28s
4999:	learn: 0.0018426	total: 9m 4s	remaining: 9m 4s
5385:	learn: 0.0017675	total: 9m 4s	remaining: 7m 46s
5230:	learn: 0.0020881	total: 9m 4s	remaining: 8m 16s
5386:	learn: 0.0017672	total: 9m 4s	remaining: 7m 46s
5482:	learn: 0.0017573	total: 9m 4s	remaining: 7m 28s
5386:	learn: 0.0017671	total: 9m 4s	remaining: 7m 46s
5000:	learn: 0.0018420	total: 9m 4s	remaining: 9m 4s
5231:	learn: 0.0020874	total: 9m 4s	remaining: 8m 16s
5483:	learn: 0.0017573	total: 9m 4s	remaining: 7m 28s
5387:	learn: 0.0017667	total: 9m 4s	remaining: 7m 46s
5387:	learn: 0.0017669	total: 9m 4s	remaining: 7m 46s
5484:	learn: 0.0017573	total: 9m 4s	remaining: 7m 28s
5001:	learn: 0.0018413	total: 9m 4s	remaining: 9m 4s
5232:	learn: 0.0020873	total: 9m 4s	remaining: 8m 16s
5388:	learn: 0.0017667	total: 9m 4s	remaining: 7m 46s
5388:	learn: 0.0017666	total: 9m 4s	remaining: 7m 46s
5485:	learn: 0.0017573	total: 9m 4s	remaining: 7m 28s
5233:	learn: 0.0020869	total: 9m 4s	remaining: 8m 16s
5002:	learn: 0.0018408	total: 9m 5s	remaining: 9m 4s
5389:	learn: 0.0017664	total: 9m 5s	remaining: 7m 46s
5389:	learn: 0.0017663	total: 9m 4s	remaining: 7m 46s
5486:	learn: 0.0017573	total: 9m 5s	remaining: 7m 28s
5234:	learn: 0.0020864	total: 9m 5s	remaining: 8m 16s
5003:	learn: 0.0018408	total: 9m 5s	remaining: 9m 4s
5390:	learn: 0.0017664	total: 9m 5s	remaining: 7m 46s
5390:	learn: 0.0017663	total: 9m 4s	remaining: 7m 45s
5235:	learn: 0.0020864	total: 9m 5s	remaining: 8m 15s
5487:	learn: 0.0017573	total: 9m 5s	remaining: 7m 28s
5004:	learn: 0.0018401	total: 9m 5s	remaining: 9m 4s
5391:	learn: 0.0017657	total: 9m 5s	remaining: 7m 45s
5391:	learn: 0.0017660	total: 9m 5s	remaining: 7m 45s
5488:	learn: 0.0017573	total: 9m 5s	remaining: 7m 28s
5236:	learn: 0.0020864	total: 9m 5s	remaining: 8m 15s
5005:	learn: 0.0018392	total: 9m 5s	remaining: 9m 3s
5392:	learn: 0.0017650	total: 9m 5s	remaining: 7m 45s
5392:	learn: 0.0017654	total: 9m 5s	remaining: 7m 45s
5489:	learn: 0.0017573	total: 9m 5s	remaining: 7m 27s
5237:	learn: 0.0020864	total: 9m 5s	remaining: 8m 15s
5393:	learn: 0.0017650	total: 9m 5s	remaining: 7m 45s
5393:	learn: 0.0017650	total: 9m 5s	remaining: 7m 45s
5006:	learn: 0.0018386	total: 9m 5s	remaining: 9m 3s
5238:	learn: 0.0020864	total: 9m 5s	remaining: 8m 15s
5490:	learn: 0.0017572	total: 9m 5s	remaining: 7m 27s
5394:	learn: 0.0017646	total: 9m 5s	remaining: 7m 45s
5239:	learn: 0.0020864	total: 9m 5s	remaining: 8m 15s
5394:	learn: 0.0017651	total: 9m 5s	remaining: 7m 45s
5491:	learn: 0.0017572	total: 9m 5s	remaining: 7m 27s
5007:	learn: 0.0018381	total: 9m 5s	remaining: 9m 3s
5395:	learn: 0.0017640	total: 9m 5s	remaining: 7m 45s
5395:	learn: 0.0017647	total: 9m 5s	remaining: 7m 45s
5240:	learn: 0.0020864	total: 9m 5s	remaining: 8m 15s
5492:	learn: 0.0017572	total: 9m 5s	remaining: 7m 27s
5396:	learn: 0.0017640	total: 9m 5s	remaining: 7m 45s
5008:	learn: 0.0018375	total: 9m 5s	remaining: 9m 3s
5241:	learn: 0.0020864	total: 9m 5s	remaining: 8m 15s
5493:	learn: 0.0017572	total: 9m 5s	remaining: 7m 27s
5009:	learn: 0.0018366	total: 9m 5s	remaining: 9m 3s
5396:	learn: 0.0017647	total: 9m 5s	remaining: 7m 45s
5397:	learn: 0.0017636	total: 9m 5s	remaining: 7m 45s
5494:	learn: 0.0017566	total: 9m 5s	remaining: 7m 27s
5242:	learn: 0.0020864	total: 9m 5s	remaining: 8m 15s
5010:	learn: 0.0018358	total: 9m 5s	remaining: 9m 3s
5398:	learn: 0.0017632	total: 9m 5s	remaining: 7m 45s
5397:	learn: 0.0017647	total: 9m 5s	remaining: 7m 45s
5495:	learn: 0.0017561	total: 9m 5s	remaining: 7m 27s
5243:	learn: 0.0020864	total: 9m 5s	remaining: 8m 15s
5399:	learn: 0.0017631	total: 9m 5s	remaining: 7m 44s
5011:	learn: 0.0018352	total: 9m 5s	remaining: 9m 3s
5398:	learn: 0.0017647	total: 9m 5s	remaining: 7m 45s
5496:	learn: 0.0017556	total: 9m 5s	remaining: 7m 27s

5244:	learn: 0.0020864	total: 9m 6s	remaining: 8m 15s
5400:	learn: 0.0017631	total: 9m 5s	remaining: 7m 44s
5399:	learn: 0.0017647	total: 9m 6s	remaining: 7m 45s
5497:	learn: 0.0017550	total: 9m 6s	remaining: 7m 27s
5012:	learn: 0.0018344	total: 9m 6s	remaining: 9m 3s
5400:	learn: 0.0017647	total: 9m 6s	remaining: 7m 45s
5401:	learn: 0.0017631	total: 9m 6s	remaining: 7m 44s
5245:	learn: 0.0020864	total: 9m 6s	remaining: 8m 14s
5498:	learn: 0.0017545	total: 9m 6s	remaining: 7m 27s
5013:	learn: 0.0018338	total: 9m 6s	remaining: 9m 3s
5402:	learn: 0.0017631	total: 9m 6s	remaining: 7m 44s
5401:	learn: 0.0017640	total: 9m 6s	remaining: 7m 44s
5499:	learn: 0.0017540	total: 9m 6s	remaining: 7m 26s
5246:	learn: 0.0020863	total: 9m 6s	remaining: 8m 14s
5014:	learn: 0.0018333	total: 9m 6s	remaining: 9m 3s
5402:	learn: 0.0017640	total: 9m 6s	remaining: 7m 44s
5403:	learn: 0.0017630	total: 9m 6s	remaining: 7m 44s
5247:	learn: 0.0020863	total: 9m 6s	remaining: 8m 14s
5500:	learn: 0.0017535	total: 9m 6s	remaining: 7m 26s
5015:	learn: 0.0018328	total: 9m 6s	remaining: 9m 2s
5403:	learn: 0.0017640	total: 9m 6s	remaining: 7m 44s
5404:	learn: 0.0017626	total: 9m 6s	remaining: 7m 44s
5016:	learn: 0.0018321	total: 9m 6s	remaining: 9m 2s
5248:	learn: 0.0020863	total: 9m 6s	remaining: 8m 14s
5501:	learn: 0.0017535	total: 9m 6s	remaining: 7m 26s
5017:	learn: 0.0018316	total: 9m 6s	remaining: 9m 2s
5404:	learn: 0.0017640	total: 9m 6s	remaining: 7m 44s
5249:	learn: 0.0020864	total: 9m 6s	remaining: 8m 14s
5405:	learn: 0.0017621	total: 9m 6s	remaining: 7m 44s
5502:	learn: 0.0017535	total: 9m 6s	remaining: 7m 26s
5018:	learn: 0.0018309	total: 9m 6s	remaining: 9m 2s
5250:	learn: 0.0020864	total: 9m 6s	remaining: 8m 14s
5405:	learn: 0.0017640	total: 9m 6s	remaining: 7m 44s
5406:	learn: 0.0017617	total: 9m 6s	remaining: 7m 44s
5503:	learn: 0.0017528	total: 9m 6s	remaining: 7m 26s
5251:	learn: 0.0020864	total: 9m 6s	remaining: 8m 14s
5019:	learn: 0.0018304	total: 9m 6s	remaining: 9m 2s
5406:	learn: 0.0017640	total: 9m 6s	remaining: 7m 44s
5504:	learn: 0.0017526	total: 9m 6s	remaining: 7m 26s
5407:	learn: 0.0017613	total: 9m 6s	remaining: 7m 44s
5020:	learn: 0.0018299	total: 9m 6s	remaining: 9m 2s
5252:	learn: 0.0020863	total: 9m 6s	remaining: 8m 14s
5407:	learn: 0.0017640	total: 9m 6s	remaining: 7m 44s
5505:	learn: 0.0017526	total: 9m 6s	remaining: 7m 26s
5408:	learn: 0.0017608	total: 9m 6s	remaining: 7m 44s
5253:	learn: 0.0020863	total: 9m 6s	remaining: 8m 14s
5408:	learn: 0.0017641	total: 9m 6s	remaining: 7m 44s
5506:	learn: 0.0017517	total: 9m 6s	remaining: 7m 26s
5021:	learn: 0.0018291	total: 9m 7s	remaining: 9m 2s
5409:	learn: 0.0017608	total: 9m 6s	remaining: 7m 43s
5507:	learn: 0.0017511	total: 9m 7s	remaining: 7m 26s
5254:	learn: 0.0020864	total: 9m 7s	remaining: 8m 13s
5022:	learn: 0.0018286	total: 9m 7s	remaining: 9m 2s
5409:	learn: 0.0017641	total: 9m 7s	remaining: 7m 44s
5508:	learn: 0.0017511	total: 9m 7s	remaining: 7m 25s
5410:	learn: 0.0017606	total: 9m 7s	remaining: 7m 43s
5255:	learn: 0.0020863	total: 9m 7s	remaining: 8m 13s
5410:	learn: 0.0017640	total: 9m 7s	remaining: 7m 44s
5509:	learn: 0.0017505	total: 9m 7s	remaining: 7m 25s
5023:	learn: 0.0018281	total: 9m 7s	remaining: 9m 1s
5411:	learn: 0.0017605	total: 9m 7s	remaining: 7m 43s
5256:	learn: 0.0020863	total: 9m 7s	remaining: 8m 13s
5411:	learn: 0.0017640	total: 9m 7s	remaining: 7m 43s
5510:	learn: 0.0017505	total: 9m 7s	remaining: 7m 25s
5024:	learn: 0.0018275	total: 9m 7s	remaining: 9m 1s
5412:	learn: 0.0017605	total: 9m 7s	remaining: 7m 43s
5412:	learn: 0.0017638	total: 9m 7s	remaining: 7m 43s
5511:	learn: 0.0017498	total: 9m 7s	remaining: 7m 25s
5257:	learn: 0.0020863	total: 9m 7s	remaining: 8m 13s
5025:	learn: 0.0018268	total: 9m 7s	remaining: 9m 1s
5413:	learn: 0.0017604	total: 9m 7s	remaining: 7m 43s
5413:	learn: 0.0017634	total: 9m 7s	remaining: 7m 43s
5512:	learn: 0.0017494	total: 9m 7s	remaining: 7m 25s
5258:	learn: 0.0020863	total: 9m 7s	remaining: 8m 13s
5026:	learn: 0.0018262	total: 9m 7s	remaining: 9m 1s
5414:	learn: 0.0017598	total: 9m 7s	remaining: 7m 43s
5414:	learn: 0.0017634	total: 9m 7s	remaining: 7m 43s
5513:	learn: 0.0017494	total: 9m 7s	remaining: 7m 25s
5259:	learn: 0.0020863	total: 9m 7s	remaining: 8m 13s
5027:	learn: 0.0018257	total: 9m 7s	remaining: 9m 1s
5415:	learn: 0.0017592	total: 9m 7s	remaining: 7m 43s
5514:	learn: 0.0017490	total: 9m 7s	remaining: 7m 25s
5415:	learn: 0.0017630	total: 9m 7s	remaining: 7m 43s
5260:	learn: 0.0020856	total: 9m 7s	remaining: 8m 13s
5028:	learn: 0.0018252	total: 9m 7s	remaining: 9m 1s
5416:	learn: 0.0017587	total: 9m 7s	remaining: 7m 43s
5261:	learn: 0.0020856	total: 9m 7s	remaining: 8m 13s
5416:	learn: 0.0017630	total: 9m 7s	remaining: 7m 43s
5515:	learn: 0.0017483	total: 9m 7s	remaining: 7m 25s
5029:	learn: 0.0018252	total: 9m 7s	remaining: 9m 1s
5417:	learn: 0.0017630	total: 9m 7s	remaining: 7m 43s
5417:	learn: 0.0017580	total: 9m 7s	remaining: 7m 43s
5516:	learn: 0.0017478	total: 9m 7s	remaining: 7m 25s
5262:	learn: 0.0020856	total: 9m 7s	remaining: 8m 13s
5418:	learn: 0.0017630	total: 9m 7s	remaining: 7m 43s
5030:	learn: 0.0018247	total: 9m 7s	remaining: 9m 1s
5263:	learn: 0.0020856	total: 9m 7s	remaining: 8m 12s
5517:	learn: 0.0017472	total: 9m 7s	remaining: 7m 25s
5418:	learn: 0.0017574	total: 9m 7s	remaining: 7m 43s
5419:	learn: 0.0017630	total: 9m 8s	remaining: 7m 43s
5031:	learn: 0.0018241	total: 9m 8s	remaining: 9m 1s
5518:	learn: 0.0017472	total: 9m 8s	remaining: 7m 24s
5264:	learn: 0.0020856	total: 9m 8s	remaining: 8m 12s
5419:	learn: 0.0017574	total: 9m 7s	remaining: 7m 43s
5032:	learn: 0.0018235	total: 9m 8s	remaining: 9m
5420:	learn: 0.0017628	total: 9m 8s	remaining: 7m 42s
5519:	learn: 0.0017472	total: 9m 8s	remaining: 7m 24s
5265:	learn: 0.0020856	total: 9m 8s	remaining: 8m 12s
5420:	learn: 0.0017574	total: 9m 8s	remaining: 7m 42s
5033:	learn: 0.0018230	total: 9m 8s	remaining: 9m
5421:	learn: 0.0017628	total: 9m 8s	remaining: 7m 42s
5266:	learn: 0.0020856	total: 9m 8s	remaining: 8m 12s
5421:	learn: 0.0017574	total: 9m 8s	remaining: 7m 42s
5520:	learn: 0.0017468	total: 9m 8s	remaining: 7m 24s
5267:	learn: 0.0020856	total: 9m 8s	remaining: 8m 12s
5422:	learn: 0.0017574	total: 9m 8s	remaining: 7m 42s
5034:	learn: 0.0018224	total: 9m 8s	remaining: 9m
5422:	learn: 0.0017628	total: 9m 8s	remaining: 7m 42s
5521:	learn: 0.0017464	total: 9m 8s	remaining: 7m 24s
5268:	learn: 0.0020856	total: 9m 8s	remaining: 8m 12s
5035:	learn: 0.0018221	total: 9m 8s	remaining: 9m
5423:	learn: 0.0017574	total: 9m 8s	remaining: 7m 42s
5423:	learn: 0.0017628	total: 9m 8s	remaining: 7m 42s
5522:	learn: 0.0017464	total: 9m 8s	remaining: 7m 24s
5269:	learn: 0.0020856	total: 9m 8s	remaining: 8m 12s
5424:	learn: 0.0017628	total: 9m 8s	remaining: 7m 42s
5523:	learn: 0.0017464	total: 9m 8s	remaining: 7m 24s
5424:	learn: 0.0017574	total: 9m 8s	remaining: 7m 42s
5036:	learn: 0.0018214	total: 9m 8s	remaining: 9m
5524:	learn: 0.0017464	total: 9m 8s	remaining: 7m 24s
5425:	learn: 0.0017625	total: 9m 8s	remaining: 7m 42s
5425:	learn: 0.0017574	total: 9m 8s	remaining: 7m 42s
5270:	learn: 0.0020856	total: 9m 8s	remaining: 8m 12s
5037:	learn: 0.0018206	total: 9m 8s	remaining: 9m
5426:	learn: 0.0017574	total: 9m 8s	remaining: 7m 42s
5426:	learn: 0.0017622	total: 9m 8s	remaining: 7m 42s
5525:	learn: 0.0017457	total: 9m 8s	remaining: 7m 24s
5271:	learn: 0.0020856	total: 9m 8s	remaining: 8m 12s
5038:	learn: 0.0018201	total: 9m 8s	remaining: 9m
5272:	learn: 0.0020856	total: 9m 8s	remaining: 8m 12s
5427:	learn: 0.0017622	total: 9m 8s	remaining: 7m 42s
5427:	learn: 0.0017571	total: 9m 8s	remaining: 7m 42s
5526:	learn: 0.0017456	total: 9m 8s	remaining: 7m 24s
5039:	learn: 0.0018194	total: 9m 8s	remaining: 9m
5428:	learn: 0.0017622	total: 9m 8s	remaining: 7m 42s
5273:	learn: 0.0020856	total: 9m 8s	remaining: 8m 11s
5527:	learn: 0.0017456	total: 9m 8s	remaining: 7m 24s
5428:	learn: 0.0017565	total: 9m 8s	remaining: 7m 42s
5429:	learn: 0.0017619	total: 9m 8s	remaining: 7m 42s
5040:	learn: 0.0018190	total: 9m 9s	remaining: 9m
5274:	learn: 0.0020856	total: 9m 9s	remaining: 8m 11s
5528:	learn: 0.0017453	total: 9m 9s	remaining: 7m 23s
5429:	learn: 0.0017562	total: 9m 8s	remaining: 7m 42s
5430:	learn: 0.0017619	total: 9m 9s	remaining: 7m 41s
5275:	learn: 0.0020856	total: 9m 9s	remaining: 8m 11s
5041:	learn: 0.0018184	total: 9m 9s	remaining: 8m 59s
5431:	learn: 0.0017616	total: 9m 9s	remaining: 7m 41s
5529:	learn: 0.0017446	total: 9m 9s	remaining: 7m 23s
5430:	learn: 0.0017558	total: 9m 9s	remaining: 7m 41s
5276:	learn: 0.0020856	total: 9m 9s	remaining: 8m 11s
5432:	learn: 0.0017613	total: 9m 9s	remaining: 7m 41s
5042:	learn: 0.0018178	total: 9m 9s	remaining: 8m 59s
5530:	learn: 0.0017440	total: 9m 9s	remaining: 7m 23s
5431:	learn: 0.0017558	total: 9m 9s	remaining: 7m 41s
5277:	learn: 0.0020856	total: 9m 9s	remaining: 8m 11s
5531:	learn: 0.0017436	total: 9m 9s	remaining: 7m 23s
5043:	learn: 0.0018172	total: 9m 9s	remaining: 8m 59s
5433:	learn: 0.0017612	total: 9m 9s	remaining: 7m 41s
5432:	learn: 0.0017558	total: 9m 9s	remaining: 7m 41s
5278:	learn: 0.0020856	total: 9m 9s	remaining: 8m 11s
5532:	learn: 0.0017433	total: 9m 9s	remaining: 7m 23s
5044:	learn: 0.0018166	total: 9m 9s	remaining: 8m 59s
5434:	learn: 0.0017609	total: 9m 9s	remaining: 7m 41s
5433:	learn: 0.0017555	total: 9m 9s	remaining: 7m 41s
5533:	learn: 0.0017434	total: 9m 9s	remaining: 7m 23s
5279:	learn: 0.0020856	total: 9m 9s	remaining: 8m 11s
5045:	learn: 0.0018166	total: 9m 9s	remaining: 8m 59s
5435:	learn: 0.0017606	total: 9m 9s	remaining: 7m 41s
5434:	learn: 0.0017555	total: 9m 9s	remaining: 7m 41s
5534:	learn: 0.0017429	total: 9m 9s	remaining: 7m 23s
5436:	learn: 0.0017606	total: 9m 9s	remaining: 7m 41s
5046:	learn: 0.0018166	total: 9m 9s	remaining: 8m 59s
5280:	learn: 0.0020856	total: 9m 9s	remaining: 8m 11s
5535:	learn: 0.0017428	total: 9m 9s	remaining: 7m 23s
5435:	learn: 0.0017554	total: 9m 9s	remaining: 7m 41s
5047:	learn: 0.0018166	total: 9m 9s	remaining: 8m 59s
5437:	learn: 0.0017606	total: 9m 9s	remaining: 7m 41s
5281:	learn: 0.0020856	total: 9m 9s	remaining: 8m 11s
5536:	learn: 0.0017428	total: 9m 9s	remaining: 7m 23s
5436:	learn: 0.0017554	total: 9m 9s	remaining: 7m 41s
5048:	learn: 0.0018161	total: 9m 9s	remaining: 8m 59s
5282:	learn: 0.0020855	total: 9m 9s	remaining: 8m 10s
5537:	learn: 0.0017422	total: 9m 9s	remaining: 7m 23s
5437:	learn: 0.0017552	total: 9m 9s	remaining: 7m 41s
5438:	learn: 0.0017606	total: 9m 9s	remaining: 7m 41s
5538:	learn: 0.0017416	total: 9m 9s	remaining: 7m 22s
5049:	learn: 0.0018156	total: 9m 9s	remaining: 8m 59s
5438:	learn: 0.0017546	total: 9m 9s	remaining: 7m 41s
5283:	learn: 0.0020855	total: 9m 9s	remaining: 8m 10s
5439:	learn: 0.0017602	total: 9m 10s	remaining: 7m 41s
5439:	learn: 0.0017546	total: 9m 9s	remaining: 7m 40s
5284:	learn: 0.0020855	total: 9m 10s	remaining: 8m 10s
5539:	learn: 0.0017416	total: 9m 10s	remaining: 7m 22s
5440:	learn: 0.0017602	total: 9m 10s	remaining: 7m 40s
5050:	learn: 0.0018148	total: 9m 10s	remaining: 8m 59s
5540:	learn: 0.0017411	total: 9m 10s	remaining: 7m 22s
5441:	learn: 0.0017602	total: 9m 10s	remaining: 7m 40s
5440:	learn: 0.0017540	total: 9m 10s	remaining: 7m 40s
5285:	learn: 0.0020855	total: 9m 10s	remaining: 8m 10s
5051:	learn: 0.0018141	total: 9m 10s	remaining: 8m 58s
5442:	learn: 0.0017600	total: 9m 10s	remaining: 7m 40s
5541:	learn: 0.0017411	total: 9m 10s	remaining: 7m 22s
5441:	learn: 0.0017534	total: 9m 10s	remaining: 7m 40s
5286:	learn: 0.0020854	total: 9m 10s	remaining: 8m 10s
5052:	learn: 0.0018135	total: 9m 10s	remaining: 8m 58s
5443:	learn: 0.0017600	total: 9m 10s	remaining: 7m 40s
5442:	learn: 0.0017527	total: 9m 10s	remaining: 7m 40s
5542:	learn: 0.0017406	total: 9m 10s	remaining: 7m 22s
5287:	learn: 0.0020854	total: 9m 10s	remaining: 8m 10s
5053:	learn: 0.0018129	total: 9m 10s	remaining: 8m 58s
5543:	learn: 0.0017402	total: 9m 10s	remaining: 7m 22s
5444:	learn: 0.0017600	total: 9m 10s	remaining: 7m 40s
5443:	learn: 0.0017527	total: 9m 10s	remaining: 7m 40s
5288:	learn: 0.0020854	total: 9m 10s	remaining: 8m 10s
5054:	learn: 0.0018125	total: 9m 10s	remaining: 8m 58s
5544:	learn: 0.0017397	total: 9m 10s	remaining: 7m 22s
5444:	learn: 0.0017521	total: 9m 10s	remaining: 7m 40s
5445:	learn: 0.0017600	total: 9m 10s	remaining: 7m 40s
5055:	learn: 0.0018119	total: 9m 10s	remaining: 8m 58s
5545:	learn: 0.0017392	total: 9m 10s	remaining: 7m 22s
5445:	learn: 0.0017514	total: 9m 10s	remaining: 7m 40s
5289:	learn: 0.0020854	total: 9m 10s	remaining: 8m 10s
5446:	learn: 0.0017600	total: 9m 10s	remaining: 7m 40s
5056:	learn: 0.0018115	total: 9m 10s	remaining: 8m 58s
5546:	learn: 0.0017392	total: 9m 10s	remaining: 7m 22s
5290:	learn: 0.0020849	total: 9m 10s	remaining: 8m 10s
5446:	learn: 0.0017508	total: 9m 10s	remaining: 7m 40s
5447:	learn: 0.0017596	total: 9m 10s	remaining: 7m 40s
5057:	learn: 0.0018115	total: 9m 10s	remaining: 8m 58s
5547:	learn: 0.0017390	total: 9m 10s	remaining: 7m 21s
5291:	learn: 0.0020849	total: 9m 10s	remaining: 8m 10s
5447:	learn: 0.0017502	total: 9m 10s	remaining: 7m 40s
5548:	learn: 0.0017387	total: 9m 10s	remaining: 7m 21s
5448:	learn: 0.0017592	total: 9m 10s	remaining: 7m 40s
5058:	learn: 0.0018109	total: 9m 10s	remaining: 8m 58s
5448:	learn: 0.0017497	total: 9m 10s	remaining: 7m 40s
5292:	learn: 0.0020849	total: 9m 10s	remaining: 8m 9s
5549:	learn: 0.0017383	total: 9m 10s	remaining: 7m 21s
5293:	learn: 0.0020849	total: 9m 11s	remaining: 8m 9s
5449:	learn: 0.0017593	total: 9m 11s	remaining: 7m 40s
5449:	learn: 0.0017491	total: 9m 10s	remaining: 7m 39s
5059:	learn: 0.0018105	total: 9m 11s	remaining: 8m 57s
5550:	learn: 0.0017377	total: 9m 11s	remaining: 7m 21s
5294:	learn: 0.0020849	total: 9m 11s	remaining: 8m 9s
5450:	learn: 0.0017592	total: 9m 11s	remaining: 7m 39s
5450:	learn: 0.0017491	total: 9m 11s	remaining: 7m 39s
5060:	learn: 0.0018099	total: 9m 11s	remaining: 8m 57s
5551:	learn: 0.0017370	total: 9m 11s	remaining: 7m 21s
5451:	learn: 0.0017592	total: 9m 11s	remaining: 7m 39s
5295:	learn: 0.0020849	total: 9m 11s	remaining: 8m 9s
5451:	learn: 0.0017486	total: 9m 11s	remaining: 7m 39s
5061:	learn: 0.0018099	total: 9m 11s	remaining: 8m 57s
5552:	learn: 0.0017370	total: 9m 11s	remaining: 7m 21s
5296:	learn: 0.0020849	total: 9m 11s	remaining: 8m 9s
5452:	learn: 0.0017486	total: 9m 11s	remaining: 7m 39s
5452:	learn: 0.0017590	total: 9m 11s	remaining: 7m 39s
5553:	learn: 0.0017370	total: 9m 11s	remaining: 7m 21s
5297:	learn: 0.0020841	total: 9m 11s	remaining: 8m 9s
5062:	learn: 0.0018094	total: 9m 11s	remaining: 8m 57s
5453:	learn: 0.0017480	total: 9m 11s	remaining: 7m 39s
5298:	learn: 0.0020841	total: 9m 11s	remaining: 8m 9s
5453:	learn: 0.0017585	total: 9m 11s	remaining: 7m 39s
5554:	learn: 0.0017370	total: 9m 11s	remaining: 7m 21s
5063:	learn: 0.0018088	total: 9m 11s	remaining: 8m 57s
5454:	learn: 0.0017476	total: 9m 11s	remaining: 7m 39s
5299:	learn: 0.0020835	total: 9m 11s	remaining: 8m 9s
5555:	learn: 0.0017370	total: 9m 11s	remaining: 7m 21s
5454:	learn: 0.0017585	total: 9m 11s	remaining: 7m 39s
5455:	learn: 0.0017470	total: 9m 11s	remaining: 7m 39s
5064:	learn: 0.0018082	total: 9m 11s	remaining: 8m 57s
5556:	learn: 0.0017365	total: 9m 11s	remaining: 7m 21s
5456:	learn: 0.0017465	total: 9m 11s	remaining: 7m 39s
5300:	learn: 0.0020836	total: 9m 11s	remaining: 8m 9s
5455:	learn: 0.0017585	total: 9m 11s	remaining: 7m 39s
5065:	learn: 0.0018077	total: 9m 11s	remaining: 8m 57s
5557:	learn: 0.0017360	total: 9m 11s	remaining: 7m 20s
5457:	learn: 0.0017457	total: 9m 11s	remaining: 7m 39s
5456:	learn: 0.0017582	total: 9m 11s	remaining: 7m 39s
5301:	learn: 0.0020835	total: 9m 11s	remaining: 8m 8s
5558:	learn: 0.0017358	total: 9m 11s	remaining: 7m 20s
5066:	learn: 0.0018072	total: 9m 11s	remaining: 8m 57s
5458:	learn: 0.0017457	total: 9m 11s	remaining: 7m 38s
5302:	learn: 0.0020835	total: 9m 11s	remaining: 8m 8s
5457:	learn: 0.0017576	total: 9m 11s	remaining: 7m 39s
5559:	learn: 0.0017354	total: 9m 11s	remaining: 7m 20s
5067:	learn: 0.0018067	total: 9m 11s	remaining: 8m 57s
5459:	learn: 0.0017457	total: 9m 11s	remaining: 7m 38s
5458:	learn: 0.0017571	total: 9m 11s	remaining: 7m 39s
5303:	learn: 0.0020835	total: 9m 12s	remaining: 8m 8s
5560:	learn: 0.0017348	total: 9m 12s	remaining: 7m 20s
5068:	learn: 0.0018063	total: 9m 12s	remaining: 8m 57s
5460:	learn: 0.0017454	total: 9m 11s	remaining: 7m 38s

5304:	learn: 0.0020835	total: 9m 12s	remaining: 8m 8s
5561:	learn: 0.0017347	total: 9m 12s	remaining: 7m 20s
5461:	learn: 0.0017452	total: 9m 12s	remaining: 7m 38s
5069:	learn: 0.0018059	total: 9m 12s	remaining: 8m 56s
5460:	learn: 0.0017563	total: 9m 12s	remaining: 7m 38s
5305:	learn: 0.0020835	total: 9m 12s	remaining: 8m 8s
5462:	learn: 0.0017451	total: 9m 12s	remaining: 7m 38s
5562:	learn: 0.0017341	total: 9m 12s	remaining: 7m 20s
5461:	learn: 0.0017560	total: 9m 12s	remaining: 7m 38s
5070:	learn: 0.0018053	total: 9m 12s	remaining: 8m 56s
5306:	learn: 0.0020835	total: 9m 12s	remaining: 8m 8s
5463:	learn: 0.0017451	total: 9m 12s	remaining: 7m 38s
5563:	learn: 0.0017341	total: 9m 12s	remaining: 7m 20s
5462:	learn: 0.0017557	total: 9m 12s	remaining: 7m 38s
5071:	learn: 0.0018047	total: 9m 12s	remaining: 8m 56s
5464:	learn: 0.0017446	total: 9m 12s	remaining: 7m 38s
5307:	learn: 0.0020835	total: 9m 12s	remaining: 8m 8s
5564:	learn: 0.0017341	total: 9m 12s	remaining: 7m 20s
5463:	learn: 0.0017557	total: 9m 12s	remaining: 7m 38s
5465:	learn: 0.0017441	total: 9m 12s	remaining: 7m 38s
5072:	learn: 0.0018041	total: 9m 12s	remaining: 8m 56s
5308:	learn: 0.0020835	total: 9m 12s	remaining: 8m 8s
5464:	learn: 0.0017555	total: 9m 12s	remaining: 7m 38s
5565:	learn: 0.0017341	total: 9m 12s	remaining: 7m 20s
5466:	learn: 0.0017435	total: 9m 12s	remaining: 7m 38s
5465:	learn: 0.0017555	total: 9m 12s	remaining: 7m 38s
5073:	learn: 0.0018036	total: 9m 12s	remaining: 8m 56s
5309:	learn: 0.0020835	total: 9m 12s	remaining: 8m 8s
5566:	learn: 0.0017337	total: 9m 12s	remaining: 7m 20s
5466:	learn: 0.0017555	total: 9m 12s	remaining: 7m 38s
5467:	learn: 0.0017435	total: 9m 12s	remaining: 7m 38s
5074:	learn: 0.0018031	total: 9m 12s	remaining: 8m 56s
5567:	learn: 0.0017337	total: 9m 12s	remaining: 7m 19s
5310:	learn: 0.0020826	total: 9m 12s	remaining: 8m 8s
5467:	learn: 0.0017551	total: 9m 12s	remaining: 7m 38s
5568:	learn: 0.0017333	total: 9m 12s	remaining: 7m 19s
5468:	learn: 0.0017428	total: 9m 12s	remaining: 7m 37s
5075:	learn: 0.0018031	total: 9m 12s	remaining: 8m 56s
5468:	learn: 0.0017551	total: 9m 12s	remaining: 7m 38s
5311:	learn: 0.0020817	total: 9m 12s	remaining: 8m 7s
5469:	learn: 0.0017423	total: 9m 12s	remaining: 7m 37s
5569:	learn: 0.0017327	total: 9m 12s	remaining: 7m 19s
5312:	learn: 0.0020817	total: 9m 12s	remaining: 8m 7s
5076:	learn: 0.0018026	total: 9m 13s	remaining: 8m 56s
5469:	learn: 0.0017551	total: 9m 13s	remaining: 7m 37s
5470:	learn: 0.0017423	total: 9m 12s	remaining: 7m 37s
5570:	learn: 0.0017321	total: 9m 12s	remaining: 7m 19s
5077:	learn: 0.0018020	total: 9m 13s	remaining: 8m 56s
5313:	learn: 0.0020817	total: 9m 13s	remaining: 8m 7s
5470:	learn: 0.0017551	total: 9m 13s	remaining: 7m 37s
5571:	learn: 0.0017318	total: 9m 13s	remaining: 7m 19s
5471:	learn: 0.0017417	total: 9m 12s	remaining: 7m 37s
5471:	learn: 0.0017546	total: 9m 13s	remaining: 7m 37s
5572:	learn: 0.0017311	total: 9m 13s	remaining: 7m 19s
5078:	learn: 0.0018015	total: 9m 13s	remaining: 8m 56s
5472:	learn: 0.0017417	total: 9m 13s	remaining: 7m 37s
5314:	learn: 0.0020817	total: 9m 13s	remaining: 8m 7s
5472:	learn: 0.0017546	total: 9m 13s	remaining: 7m 37s
5573:	learn: 0.0017306	total: 9m 13s	remaining: 7m 19s
5315:	learn: 0.0020817	total: 9m 13s	remaining: 8m 7s
5473:	learn: 0.0017417	total: 9m 13s	remaining: 7m 37s
5079:	learn: 0.0018009	total: 9m 13s	remaining: 8m 55s
5473:	learn: 0.0017540	total: 9m 13s	remaining: 7m 37s
5574:	learn: 0.0017301	total: 9m 13s	remaining: 7m 19s
5316:	learn: 0.0020817	total: 9m 13s	remaining: 8m 7s
5474:	learn: 0.0017411	total: 9m 13s	remaining: 7m 37s
5474:	learn: 0.0017540	total: 9m 13s	remaining: 7m 37s
5080:	learn: 0.0018004	total: 9m 13s	remaining: 8m 55s
5575:	learn: 0.0017294	total: 9m 13s	remaining: 7m 19s
5475:	learn: 0.0017407	total: 9m 13s	remaining: 7m 37s
5317:	learn: 0.0020817	total: 9m 13s	remaining: 8m 7s
5475:	learn: 0.0017540	total: 9m 13s	remaining: 7m 37s
5576:	learn: 0.0017294	total: 9m 13s	remaining: 7m 19s
5081:	learn: 0.0017999	total: 9m 13s	remaining: 8m 55s
5476:	learn: 0.0017402	total: 9m 13s	remaining: 7m 37s
5318:	learn: 0.0020817	total: 9m 13s	remaining: 8m 7s
5476:	learn: 0.0017534	total: 9m 13s	remaining: 7m 37s
5577:	learn: 0.0017294	total: 9m 13s	remaining: 7m 18s
5082:	learn: 0.0017993	total: 9m 13s	remaining: 8m 55s
5477:	learn: 0.0017402	total: 9m 13s	remaining: 7m 36s
5477:	learn: 0.0017534	total: 9m 13s	remaining: 7m 37s
5319:	learn: 0.0020817	total: 9m 13s	remaining: 8m 7s
5578:	learn: 0.0017294	total: 9m 13s	remaining: 7m 18s
5478:	learn: 0.0017534	total: 9m 13s	remaining: 7m 36s
5083:	learn: 0.0017988	total: 9m 13s	remaining: 8m 55s
5478:	learn: 0.0017399	total: 9m 13s	remaining: 7m 36s
5320:	learn: 0.0020817	total: 9m 13s	remaining: 8m 7s
5579:	learn: 0.0017294	total: 9m 13s	remaining: 7m 18s
5479:	learn: 0.0017534	total: 9m 13s	remaining: 7m 36s
5321:	learn: 0.0020809	total: 9m 13s	remaining: 8m 6s
5479:	learn: 0.0017399	total: 9m 13s	remaining: 7m 36s
5580:	learn: 0.0017294	total: 9m 13s	remaining: 7m 18s
5084:	learn: 0.0017983	total: 9m 13s	remaining: 8m 55s
5480:	learn: 0.0017534	total: 9m 13s	remaining: 7m 36s
5322:	learn: 0.0020809	total: 9m 13s	remaining: 8m 6s
5581:	learn: 0.0017294	total: 9m 13s	remaining: 7m 18s
5480:	learn: 0.0017395	total: 9m 13s	remaining: 7m 36s
5085:	learn: 0.0017983	total: 9m 14s	remaining: 8m 55s
5481:	learn: 0.0017534	total: 9m 14s	remaining: 7m 36s
5481:	learn: 0.0017395	total: 9m 13s	remaining: 7m 36s
5582:	learn: 0.0017293	total: 9m 14s	remaining: 7m 18s
5323:	learn: 0.0020809	total: 9m 14s	remaining: 8m 6s
5482:	learn: 0.0017533	total: 9m 14s	remaining: 7m 36s
5583:	learn: 0.0017294	total: 9m 14s	remaining: 7m 18s
5482:	learn: 0.0017391	total: 9m 14s	remaining: 7m 36s
5086:	learn: 0.0017979	total: 9m 14s	remaining: 8m 55s
5324:	learn: 0.0020808	total: 9m 14s	remaining: 8m 6s
5087:	learn: 0.0017971	total: 9m 14s	remaining: 8m 55s
5483:	learn: 0.0017385	total: 9m 14s	remaining: 7m 36s
5483:	learn: 0.0017532	total: 9m 14s	remaining: 7m 36s
5584:	learn: 0.0017294	total: 9m 14s	remaining: 7m 18s
5325:	learn: 0.0020808	total: 9m 14s	remaining: 8m 6s
5484:	learn: 0.0017532	total: 9m 14s	remaining: 7m 36s
5484:	learn: 0.0017381	total: 9m 14s	remaining: 7m 36s
5088:	learn: 0.0017964	total: 9m 14s	remaining: 8m 55s
5585:	learn: 0.0017289	total: 9m 14s	remaining: 7m 18s
5326:	learn: 0.0020808	total: 9m 14s	remaining: 8m 6s
5485:	learn: 0.0017532	total: 9m 14s	remaining: 7m 36s
5485:	learn: 0.0017375	total: 9m 14s	remaining: 7m 36s
5089:	learn: 0.0017957	total: 9m 14s	remaining: 8m 54s
5327:	learn: 0.0020807	total: 9m 14s	remaining: 8m 6s
5586:	learn: 0.0017289	total: 9m 14s	remaining: 7m 17s
5486:	learn: 0.0017532	total: 9m 14s	remaining: 7m 36s
5328:	learn: 0.0020808	total: 9m 14s	remaining: 8m 6s
5486:	learn: 0.0017370	total: 9m 14s	remaining: 7m 36s
5587:	learn: 0.0017289	total: 9m 14s	remaining: 7m 17s
5090:	learn: 0.0017950	total: 9m 14s	remaining: 8m 54s
5329:	learn: 0.0020807	total: 9m 14s	remaining: 8m 5s
5487:	learn: 0.0017531	total: 9m 14s	remaining: 7m 36s
5487:	learn: 0.0017364	total: 9m 14s	remaining: 7m 35s
5588:	learn: 0.0017289	total: 9m 14s	remaining: 7m 17s
5091:	learn: 0.0017944	total: 9m 14s	remaining: 8m 54s
5488:	learn: 0.0017531	total: 9m 14s	remaining: 7m 35s
5330:	learn: 0.0020808	total: 9m 14s	remaining: 8m 5s
5488:	learn: 0.0017362	total: 9m 14s	remaining: 7m 35s
5092:	learn: 0.0017939	total: 9m 14s	remaining: 8m 54s
5589:	learn: 0.0017288	total: 9m 14s	remaining: 7m 17s
5331:	learn: 0.0020808	total: 9m 14s	remaining: 8m 5s
5489:	learn: 0.0017531	total: 9m 14s	remaining: 7m 35s
5489:	learn: 0.0017362	total: 9m 14s	remaining: 7m 35s
5093:	learn: 0.0017934	total: 9m 14s	remaining: 8m 54s
5590:	learn: 0.0017288	total: 9m 14s	remaining: 7m 17s
5332:	learn: 0.0020807	total: 9m 14s	remaining: 8m 5s
5490:	learn: 0.0017528	total: 9m 14s	remaining: 7m 35s
5490:	learn: 0.0017358	total: 9m 14s	remaining: 7m 35s
5591:	learn: 0.0017288	total: 9m 15s	remaining: 7m 17s
5094:	learn: 0.0017929	total: 9m 15s	remaining: 8m 54s
5491:	learn: 0.0017523	total: 9m 15s	remaining: 7m 35s
0018454	total: 8m 26s	remaining: 8m 8s
4855:	learn: 0.05333:	learn: 0.0020808	total: 9m 15s	remaining: 8m 5s
5491:	learn: 0.0017358	total: 9m 14s	remaining: 7m 35s
5095:	learn: 0.0017925	total: 9m 15s	remaining: 8m 54s
5592:	learn: 0.0017288	total: 9m 15s	remaining: 7m 17s
5492:	learn: 0.0017516	total: 9m 15s	remaining: 7m 35s
5334:	learn: 0.0020808	total: 9m 15s	remaining: 8m 5s
5492:	learn: 0.0017351	total: 9m 15s	remaining: 7m 35s
5593:	learn: 0.0017286	total: 9m 15s	remaining: 7m 17s
5493:	learn: 0.0017516	total: 9m 15s	remaining: 7m 35s
5096:	learn: 0.0017920	total: 9m 15s	remaining: 8m 54s
5493:	learn: 0.0017351	total: 9m 15s	remaining: 7m 35s
5335:	learn: 0.0020808	total: 9m 15s	remaining: 8m 5s
5494:	learn: 0.0017513	total: 9m 15s	remaining: 7m 35s
5594:	learn: 0.0017286	total: 9m 15s	remaining: 7m 17s
5494:	learn: 0.0017346	total: 9m 15s	remaining: 7m 35s
5097:	learn: 0.0017916	total: 9m 15s	remaining: 8m 54s
5336:	learn: 0.0020808	total: 9m 15s	remaining: 8m 5s
5595:	learn: 0.0017286	total: 9m 15s	remaining: 7m 17s
5495:	learn: 0.0017513	total: 9m 15s	remaining: 7m 35s
5495:	learn: 0.0017346	total: 9m 15s	remaining: 7m 35s
5337:	learn: 0.0020801	total: 9m 15s	remaining: 8m 5s
5098:	learn: 0.0017909	total: 9m 15s	remaining: 8m 53s
5596:	learn: 0.0017284	total: 9m 15s	remaining: 7m 17s
5496:	learn: 0.0017513	total: 9m 15s	remaining: 7m 35s
5496:	learn: 0.0017341	total: 9m 15s	remaining: 7m 35s
5338:	learn: 0.0020793	total: 9m 15s	remaining: 8m 5s
5099:	learn: 0.0017904	total: 9m 15s	remaining: 8m 53s
5597:	learn: 0.0017279	total: 9m 15s	remaining: 7m 16s
5497:	learn: 0.0017512	total: 9m 15s	remaining: 7m 35s
5497:	learn: 0.0017337	total: 9m 15s	remaining: 7m 34s
5598:	learn: 0.0017274	total: 9m 15s	remaining: 7m 16s
5339:	learn: 0.0020793	total: 9m 15s	remaining: 8m 4s
5100:	learn: 0.0017899	total: 9m 15s	remaining: 8m 53s
5599:	learn: 0.0017274	total: 9m 15s	remaining: 7m 16s
5498:	learn: 0.0017512	total: 9m 15s	remaining: 7m 34s
5340:	learn: 0.0020793	total: 9m 15s	remaining: 8m 4s
5498:	learn: 0.0017332	total: 9m 15s	remaining: 7m 34s
5101:	learn: 0.0017894	total: 9m 15s	remaining: 8m 53s
5600:	learn: 0.0017269	total: 9m 15s	remaining: 7m 16s
5499:	learn: 0.0017512	total: 9m 15s	remaining: 7m 34s
5499:	learn: 0.0017326	total: 9m 15s	remaining: 7m 34s
5341:	learn: 0.0020793	total: 9m 15s	remaining: 8m 4s
5500:	learn: 0.0017507	total: 9m 15s	remaining: 7m 34s
5102:	learn: 0.0017888	total: 9m 15s	remaining: 8m 53s
5601:	learn: 0.0017269	total: 9m 15s	remaining: 7m 16s
5500:	learn: 0.0017320	total: 9m 15s	remaining: 7m 34s
5342:	learn: 0.0020793	total: 9m 16s	remaining: 8m 4s
5501:	learn: 0.0017507	total: 9m 16s	remaining: 7m 34s
5103:	learn: 0.0017883	total: 9m 16s	remaining: 8m 53s
5501:	learn: 0.0017320	total: 9m 15s	remaining: 7m 34s
5602:	learn: 0.0017269	total: 9m 16s	remaining: 7m 16s
5343:	learn: 0.0020793	total: 9m 16s	remaining: 8m 4s
5502:	learn: 0.0017503	total: 9m 16s	remaining: 7m 34s
5502:	learn: 0.0017316	total: 9m 16s	remaining: 7m 34s
5104:	learn: 0.0017877	total: 9m 16s	remaining: 8m 53s
5603:	learn: 0.0017269	total: 9m 16s	remaining: 7m 16s
5344:	learn: 0.0020793	total: 9m 16s	remaining: 8m 4s
5503:	learn: 0.0017503	total: 9m 16s	remaining: 7m 34s
5503:	learn: 0.0017316	total: 9m 16s	remaining: 7m 34s
5604:	learn: 0.0017269	total: 9m 16s	remaining: 7m 16s
5345:	learn: 0.0020793	total: 9m 16s	remaining: 8m 4s
5504:	learn: 0.0017503	total: 9m 16s	remaining: 7m 34s
5105:	learn: 0.0017871	total: 9m 16s	remaining: 8m 53s
5504:	learn: 0.0017316	total: 9m 16s	remaining: 7m 34s
5605:	learn: 0.0017266	total: 9m 16s	remaining: 7m 16s
5346:	learn: 0.0020793	total: 9m 16s	remaining: 8m 4s
5106:	learn: 0.0017866	total: 9m 16s	remaining: 8m 53s
5505:	learn: 0.0017503	total: 9m 16s	remaining: 7m 34s
5606:	learn: 0.0017261	total: 9m 16s	remaining: 7m 15s
5347:	learn: 0.0020793	total: 9m 16s	remaining: 8m 4s
5505:	learn: 0.0017316	total: 9m 16s	remaining: 7m 34s
5107:	learn: 0.0017859	total: 9m 16s	remaining: 8m 53s
5506:	learn: 0.0017502	total: 9m 16s	remaining: 7m 34s
5348:	learn: 0.0020793	total: 9m 16s	remaining: 8m 3s
5607:	learn: 0.0017257	total: 9m 16s	remaining: 7m 15s
5506:	learn: 0.0017316	total: 9m 16s	remaining: 7m 34s
5507:	learn: 0.0017502	total: 9m 16s	remaining: 7m 33s
5108:	learn: 0.0017854	total: 9m 16s	remaining: 8m 52s
5608:	learn: 0.0017250	total: 9m 16s	remaining: 7m 15s
5349:	learn: 0.0020793	total: 9m 16s	remaining: 8m 3s
5507:	learn: 0.0017311	total: 9m 16s	remaining: 7m 33s
5508:	learn: 0.0017502	total: 9m 16s	remaining: 7m 33s
5350:	learn: 0.0020793	total: 9m 16s	remaining: 8m 3s
5508:	learn: 0.0017311	total: 9m 16s	remaining: 7m 33s
5109:	learn: 0.0017850	total: 9m 16s	remaining: 8m 52s
5609:	learn: 0.0017250	total: 9m 16s	remaining: 7m 15s
5509:	learn: 0.0017502	total: 9m 16s	remaining: 7m 33s
5351:	learn: 0.0020793	total: 9m 16s	remaining: 8m 3s
5610:	learn: 0.0017245	total: 9m 16s	remaining: 7m 15s
5110:	learn: 0.0017851	total: 9m 16s	remaining: 8m 52s
5510:	learn: 0.0017502	total: 9m 16s	remaining: 7m 33s
5509:	learn: 0.0017311	total: 9m 16s	remaining: 7m 33s
5352:	learn: 0.0020793	total: 9m 16s	remaining: 8m 3s
5111:	learn: 0.0017851	total: 9m 17s	remaining: 8m 52s
5611:	learn: 0.0017245	total: 9m 16s	remaining: 7m 15s
5510:	learn: 0.0017311	total: 9m 16s	remaining: 7m 33s
5511:	learn: 0.0017499	total: 9m 17s	remaining: 7m 33s
5112:	learn: 0.0017845	total: 9m 17s	remaining: 8m 52s
5353:	learn: 0.0020793	total: 9m 17s	remaining: 8m 3s
5612:	learn: 0.0017244	total: 9m 17s	remaining: 7m 15s
5511:	learn: 0.0017311	total: 9m 16s	remaining: 7m 33s
5512:	learn: 0.0017493	total: 9m 17s	remaining: 7m 33s
5613:	learn: 0.0017240	total: 9m 17s	remaining: 7m 15s
5354:	learn: 0.0020793	total: 9m 17s	remaining: 8m 3s
5113:	learn: 0.0017840	total: 9m 17s	remaining: 8m 52s
5512:	learn: 0.0017306	total: 9m 17s	remaining: 7m 33s
5513:	learn: 0.0017490	total: 9m 17s	remaining: 7m 33s
5614:	learn: 0.0017240	total: 9m 17s	remaining: 7m 15s
5355:	learn: 0.0020793	total: 9m 17s	remaining: 8m 3s
5114:	learn: 0.0017833	total: 9m 17s	remaining: 8m 52s
5513:	learn: 0.0017306	total: 9m 17s	remaining: 7m 33s
5514:	learn: 0.0017490	total: 9m 17s	remaining: 7m 33s
5615:	learn: 0.0017240	total: 9m 17s	remaining: 7m 15s
5514:	learn: 0.0017301	total: 9m 17s	remaining: 7m 33s
5616:	learn: 0.0017240	total: 9m 17s	remaining: 7m 14s
5115:	learn: 0.0017827	total: 9m 17s	remaining: 8m 52s
5356:	learn: 0.0020793	total: 9m 17s	remaining: 8m 3s
5515:	learn: 0.0017488	total: 9m 17s	remaining: 7m 33s
5617:	learn: 0.0017236	total: 9m 17s	remaining: 7m 14s
5515:	learn: 0.0017295	total: 9m 17s	remaining: 7m 33s
5116:	learn: 0.0017821	total: 9m 17s	remaining: 8m 52s
5516:	learn: 0.0017488	total: 9m 17s	remaining: 7m 33s
5357:	learn: 0.0020793	total: 9m 17s	remaining: 8m 3s
5618:	learn: 0.0017236	total: 9m 17s	remaining: 7m 14s
5516:	learn: 0.0017289	total: 9m 17s	remaining: 7m 32s
5517:	learn: 0.0017488	total: 9m 17s	remaining: 7m 32s
5117:	learn: 0.0017816	total: 9m 17s	remaining: 8m 51s
5358:	learn: 0.0020793	total: 9m 17s	remaining: 8m 2s
5619:	learn: 0.0017236	total: 9m 17s	remaining: 7m 14s
5518:	learn: 0.0017487	total: 9m 17s	remaining: 7m 32s
5517:	learn: 0.0017285	total: 9m 17s	remaining: 7m 32s
5118:	learn: 0.0017812	total: 9m 17s	remaining: 8m 51s
5620:	learn: 0.0017236	total: 9m 17s	remaining: 7m 14s
5359:	learn: 0.0020793	total: 9m 17s	remaining: 8m 2s
5519:	learn: 0.0017487	total: 9m 17s	remaining: 7m 32s
5518:	learn: 0.0017285	total: 9m 17s	remaining: 7m 32s
5119:	learn: 0.0017806	total: 9m 17s	remaining: 8m 51s
5621:	learn: 0.0017231	total: 9m 17s	remaining: 7m 14s
5360:	learn: 0.0020793	total: 9m 17s	remaining: 8m 2s
5520:	learn: 0.0017487	total: 9m 17s	remaining: 7m 32s
5519:	learn: 0.0017285	total: 9m 17s	remaining: 7m 32s
5120:	learn: 0.0017798	total: 9m 17s	remaining: 8m 51s
5361:	learn: 0.0020793	total: 9m 17s	remaining: 8m 2s
5622:	learn: 0.0017231	total: 9m 17s	remaining: 7m 14s
5521:	learn: 0.0017488	total: 9m 18s	remaining: 7m 32s
5520:	learn: 0.0017281	total: 9m 17s	remaining: 7m 32s
5121:	learn: 0.0017793	total: 9m 18s	remaining: 8m 51s
5522:	learn: 0.0017487	total: 9m 18s	remaining: 7m 32s
5623:	learn: 0.0017232	total: 9m 18s	remaining: 7m 14s

5362:	learn: 0.0020793	total: 9m 18s	remaining: 8m 2s
5122:	learn: 0.0017784	total: 9m 18s	remaining: 8m 51s
5521:	learn: 0.0017281	total: 9m 18s	remaining: 7m 32s
5523:	learn: 0.0017488	total: 9m 18s	remaining: 7m 32s
5624:	learn: 0.0017231	total: 9m 18s	remaining: 7m 14s
5363:	learn: 0.0020792	total: 9m 18s	remaining: 8m 2s
5123:	learn: 0.0017780	total: 9m 18s	remaining: 8m 51s
5625:	learn: 0.0017227	total: 9m 18s	remaining: 7m 14s
5524:	learn: 0.0017487	total: 9m 18s	remaining: 7m 32s
5522:	learn: 0.0017281	total: 9m 18s	remaining: 7m 32s
5364:	learn: 0.0020792	total: 9m 18s	remaining: 8m 2s
5124:	learn: 0.0017774	total: 9m 18s	remaining: 8m 51s
5626:	learn: 0.0017223	total: 9m 18s	remaining: 7m 13s
5525:	learn: 0.0017485	total: 9m 18s	remaining: 7m 32s
5523:	learn: 0.0017277	total: 9m 18s	remaining: 7m 32s
5125:	learn: 0.0017768	total: 9m 18s	remaining: 8m 50s
5365:	learn: 0.0020792	total: 9m 18s	remaining: 8m 2s
5526:	learn: 0.0017483	total: 9m 18s	remaining: 7m 31s
5627:	learn: 0.0017223	total: 9m 18s	remaining: 7m 13s
5524:	learn: 0.0017276	total: 9m 18s	remaining: 7m 32s
5126:	learn: 0.0017763	total: 9m 18s	remaining: 8m 50s
5366:	learn: 0.0020792	total: 9m 18s	remaining: 8m 2s
5527:	learn: 0.0017483	total: 9m 18s	remaining: 7m 31s
5628:	learn: 0.0017223	total: 9m 18s	remaining: 7m 13s
5525:	learn: 0.0017276	total: 9m 18s	remaining: 7m 32s
5127:	learn: 0.0017763	total: 9m 18s	remaining: 8m 50s
5367:	learn: 0.0020792	total: 9m 18s	remaining: 8m 2s
5528:	learn: 0.0017483	total: 9m 18s	remaining: 7m 31s
5629:	learn: 0.0017218	total: 9m 18s	remaining: 7m 13s
5526:	learn: 0.0017275	total: 9m 18s	remaining: 7m 32s
5128:	learn: 0.0017763	total: 9m 18s	remaining: 8m 50s
5368:	learn: 0.0020792	total: 9m 18s	remaining: 8m 1s
5630:	learn: 0.0017218	total: 9m 18s	remaining: 7m 13s
5529:	learn: 0.0017476	total: 9m 18s	remaining: 7m 31s
5527:	learn: 0.0017275	total: 9m 18s	remaining: 7m 31s
5129:	learn: 0.0017759	total: 9m 18s	remaining: 8m 50s
5631:	learn: 0.0017218	total: 9m 18s	remaining: 7m 13s
5369:	learn: 0.0020787	total: 9m 18s	remaining: 8m 1s
5528:	learn: 0.0017275	total: 9m 18s	remaining: 7m 31s
5632:	learn: 0.0017213	total: 9m 18s	remaining: 7m 13s
5530:	learn: 0.0017470	total: 9m 18s	remaining: 7m 31s
5370:	learn: 0.0020787	total: 9m 18s	remaining: 8m 1s
5130:	learn: 0.0017753	total: 9m 18s	remaining: 8m 50s
5529:	learn: 0.0017274	total: 9m 18s	remaining: 7m 31s
5633:	learn: 0.0017212	total: 9m 18s	remaining: 7m 13s
5531:	learn: 0.0017469	total: 9m 19s	remaining: 7m 31s
5131:	learn: 0.0017748	total: 9m 19s	remaining: 8m 50s
5371:	learn: 0.0020787	total: 9m 19s	remaining: 8m 1s
5530:	learn: 0.0017268	total: 9m 18s	remaining: 7m 31s
5634:	learn: 0.0017212	total: 9m 19s	remaining: 7m 13s
5532:	learn: 0.0017469	total: 9m 19s	remaining: 7m 31s
5635:	learn: 0.0017212	total: 9m 19s	remaining: 7m 12s
5372:	learn: 0.0020787	total: 9m 19s	remaining: 8m 1s
5531:	learn: 0.0017263	total: 9m 19s	remaining: 7m 31s
5132:	learn: 0.0017743	total: 9m 19s	remaining: 8m 50s
5373:	learn: 0.0020787	total: 9m 19s	remaining: 8m 1s
5533:	learn: 0.0017468	total: 9m 19s	remaining: 7m 31s
5636:	learn: 0.0017212	total: 9m 19s	remaining: 7m 12s
5532:	learn: 0.0017263	total: 9m 19s	remaining: 7m 31s
5534:	learn: 0.0017468	total: 9m 19s	remaining: 7m 31s
5133:	learn: 0.0017738	total: 9m 19s	remaining: 8m 50s
5374:	learn: 0.0020787	total: 9m 19s	remaining: 8m 1s
5533:	learn: 0.0017259	total: 9m 19s	remaining: 7m 31s
5637:	learn: 0.0017212	total: 9m 19s	remaining: 7m 12s
5535:	learn: 0.0017463	total: 9m 19s	remaining: 7m 31s
5375:	learn: 0.0020787	total: 9m 19s	remaining: 8m 1s
5534:	learn: 0.0017258	total: 9m 19s	remaining: 7m 31s
5134:	learn: 0.0017732	total: 9m 19s	remaining: 8m 50s
5638:	learn: 0.0017212	total: 9m 19s	remaining: 7m 12s
5536:	learn: 0.0017460	total: 9m 19s	remaining: 7m 30s
5376:	learn: 0.0020787	total: 9m 19s	remaining: 8m 1s
5535:	learn: 0.0017258	total: 9m 19s	remaining: 7m 31s
5639:	learn: 0.0017212	total: 9m 19s	remaining: 7m 12s
5135:	learn: 0.0017726	total: 9m 19s	remaining: 8m 49s
5537:	learn: 0.0017456	total: 9m 19s	remaining: 7m 30s
5377:	learn: 0.0020787	total: 9m 19s	remaining: 8m
5536:	learn: 0.0017255	total: 9m 19s	remaining: 7m 30s
5640:	learn: 0.0017212	total: 9m 19s	remaining: 7m 12s
5136:	learn: 0.0017723	total: 9m 19s	remaining: 8m 49s
5538:	learn: 0.0017451	total: 9m 19s	remaining: 7m 30s
5378:	learn: 0.0020787	total: 9m 19s	remaining: 8m
5537:	learn: 0.0017253	total: 9m 19s	remaining: 7m 30s
5641:	learn: 0.0017211	total: 9m 19s	remaining: 7m 12s
5137:	learn: 0.0017716	total: 9m 19s	remaining: 8m 49s
5539:	learn: 0.0017451	total: 9m 19s	remaining: 7m 30s
5642:	learn: 0.0017211	total: 9m 19s	remaining: 7m 12s
5379:	learn: 0.0020787	total: 9m 19s	remaining: 8m
5538:	learn: 0.0017253	total: 9m 19s	remaining: 7m 30s
5540:	learn: 0.0017451	total: 9m 19s	remaining: 7m 30s
5643:	learn: 0.0017211	total: 9m 19s	remaining: 7m 12s
5138:	learn: 0.0017711	total: 9m 19s	remaining: 8m 49s
5380:	learn: 0.0020787	total: 9m 19s	remaining: 8m
5539:	learn: 0.0017253	total: 9m 19s	remaining: 7m 30s
5541:	learn: 0.0017451	total: 9m 19s	remaining: 7m 30s
5139:	learn: 0.0017705	total: 9m 20s	remaining: 8m 49s
5644:	learn: 0.0017211	total: 9m 19s	remaining: 7m 12s
5381:	learn: 0.0020787	total: 9m 20s	remaining: 8m
5540:	learn: 0.0017253	total: 9m 19s	remaining: 7m 30s
5140:	learn: 0.0017700	total: 9m 20s	remaining: 8m 49s
5645:	learn: 0.0017208	total: 9m 20s	remaining: 7m 11s
5542:	learn: 0.0017451	total: 9m 20s	remaining: 7m 30s
5382:	learn: 0.0020787	total: 9m 20s	remaining: 8m
5541:	learn: 0.0017248	total: 9m 20s	remaining: 7m 30s
5646:	learn: 0.0017208	total: 9m 20s	remaining: 7m 11s
5141:	learn: 0.0017693	total: 9m 20s	remaining: 8m 49s
5543:	learn: 0.0017451	total: 9m 20s	remaining: 7m 30s
5647:	learn: 0.0017208	total: 9m 20s	remaining: 7m 11s
5383:	learn: 0.0020787	total: 9m 20s	remaining: 8m
5542:	learn: 0.0017245	total: 9m 20s	remaining: 7m 30s
5142:	learn: 0.0017691	total: 9m 20s	remaining: 8m 49s
5543:	learn: 0.0017239	total: 9m 20s	remaining: 7m 30s
5384:	learn: 0.0020787	total: 9m 20s	remaining: 8m
5648:	learn: 0.0017200	total: 9m 20s	remaining: 7m 11s
5544:	learn: 0.0017451	total: 9m 20s	remaining: 7m 30s
5143:	learn: 0.0017686	total: 9m 20s	remaining: 8m 49s
5544:	learn: 0.0017234	total: 9m 20s	remaining: 7m 30s
5385:	learn: 0.0020787	total: 9m 20s	remaining: 8m
5545:	learn: 0.0017448	total: 9m 20s	remaining: 7m 30s
5649:	learn: 0.0017200	total: 9m 20s	remaining: 7m 11s
5545:	learn: 0.0017231	total: 9m 20s	remaining: 7m 30s
5386:	learn: 0.0020787	total: 9m 20s	remaining: 7m 59s
5546:	learn: 0.0017448	total: 9m 20s	remaining: 7m 29s
5650:	learn: 0.0017195	total: 9m 20s	remaining: 7m 11s
5144:	learn: 0.0017681	total: 9m 20s	remaining: 8m 48s
5546:	learn: 0.0017227	total: 9m 20s	remaining: 7m 29s
5547:	learn: 0.0017448	total: 9m 20s	remaining: 7m 29s
5651:	learn: 0.0017191	total: 9m 20s	remaining: 7m 11s
5387:	learn: 0.0020787	total: 9m 20s	remaining: 7m 59s
5145:	learn: 0.0017676	total: 9m 20s	remaining: 8m 48s
5547:	learn: 0.0017224	total: 9m 20s	remaining: 7m 29s
5548:	learn: 0.0017448	total: 9m 20s	remaining: 7m 29s
5652:	learn: 0.0017191	total: 9m 20s	remaining: 7m 11s
5388:	learn: 0.0020780	total: 9m 20s	remaining: 7m 59s
5548:	learn: 0.0017224	total: 9m 20s	remaining: 7m 29s
5549:	learn: 0.0017441	total: 9m 20s	remaining: 7m 29s
5146:	learn: 0.0017669	total: 9m 20s	remaining: 8m 48s
5653:	learn: 0.0017191	total: 9m 20s	remaining: 7m 11s
5389:	learn: 0.0020780	total: 9m 20s	remaining: 7m 59s
5550:	learn: 0.0017441	total: 9m 20s	remaining: 7m 29s
5654:	learn: 0.0017186	total: 9m 20s	remaining: 7m 10s
5549:	learn: 0.0017219	total: 9m 20s	remaining: 7m 29s
5390:	learn: 0.0020780	total: 9m 20s	remaining: 7m 59s
5147:	learn: 0.0017663	total: 9m 20s	remaining: 8m 48s
5551:	learn: 0.0017441	total: 9m 20s	remaining: 7m 29s
5550:	learn: 0.0017214	total: 9m 20s	remaining: 7m 29s
5655:	learn: 0.0017186	total: 9m 21s	remaining: 7m 10s
5391:	learn: 0.0020780	total: 9m 21s	remaining: 7m 59s
5148:	learn: 0.0017659	total: 9m 21s	remaining: 8m 48s
5551:	learn: 0.0017208	total: 9m 20s	remaining: 7m 29s
5552:	learn: 0.0017439	total: 9m 21s	remaining: 7m 29s
5656:	learn: 0.0017187	total: 9m 21s	remaining: 7m 10s
5392:	learn: 0.0020780	total: 9m 21s	remaining: 7m 59s
5149:	learn: 0.0017654	total: 9m 21s	remaining: 8m 48s
5552:	learn: 0.0017208	total: 9m 21s	remaining: 7m 29s
5553:	learn: 0.0017439	total: 9m 21s	remaining: 7m 29s
5657:	learn: 0.0017182	total: 9m 21s	remaining: 7m 10s
5150:	learn: 0.0017648	total: 9m 21s	remaining: 8m 48s
5393:	learn: 0.0020780	total: 9m 21s	remaining: 7m 59s
5554:	learn: 0.0017439	total: 9m 21s	remaining: 7m 29s
5553:	learn: 0.0017205	total: 9m 21s	remaining: 7m 29s
5658:	learn: 0.0017177	total: 9m 21s	remaining: 7m 10s
5394:	learn: 0.0020780	total: 9m 21s	remaining: 7m 59s
5151:	learn: 0.0017641	total: 9m 21s	remaining: 8m 48s
5554:	learn: 0.0017200	total: 9m 21s	remaining: 7m 29s
5555:	learn: 0.0017439	total: 9m 21s	remaining: 7m 29s
5659:	learn: 0.0017172	total: 9m 21s	remaining: 7m 10s
5395:	learn: 0.0020780	total: 9m 21s	remaining: 7m 59s
5152:	learn: 0.0017636	total: 9m 21s	remaining: 8m 48s
5555:	learn: 0.0017199	total: 9m 21s	remaining: 7m 28s
5556:	learn: 0.0017439	total: 9m 21s	remaining: 7m 28s
5660:	learn: 0.0017165	total: 9m 21s	remaining: 7m 10s
5557:	learn: 0.0017439	total: 9m 21s	remaining: 7m 28s
5153:	learn: 0.0017632	total: 9m 21s	remaining: 8m 48s
5396:	learn: 0.0020780	total: 9m 21s	remaining: 7m 58s
5556:	learn: 0.0017196	total: 9m 21s	remaining: 7m 28s
5558:	learn: 0.0017438	total: 9m 21s	remaining: 7m 28s
5557:	learn: 0.0017191	total: 9m 21s	remaining: 7m 28s
5661:	learn: 0.0017161	total: 9m 21s	remaining: 7m 10s
5397:	learn: 0.0020780	total: 9m 21s	remaining: 7m 58s
5154:	learn: 0.0017627	total: 9m 21s	remaining: 8m 47s
5558:	learn: 0.0017190	total: 9m 21s	remaining: 7m 28s
5559:	learn: 0.0017438	total: 9m 21s	remaining: 7m 28s
5662:	learn: 0.0017161	total: 9m 21s	remaining: 7m 10s
5398:	learn: 0.0020780	total: 9m 21s	remaining: 7m 58s
5559:	learn: 0.0017190	total: 9m 21s	remaining: 7m 28s
5155:	learn: 0.0017621	total: 9m 21s	remaining: 8m 47s
5560:	learn: 0.0017438	total: 9m 21s	remaining: 7m 28s
5663:	learn: 0.0017159	total: 9m 21s	remaining: 7m 10s
5399:	learn: 0.0020780	total: 9m 21s	remaining: 7m 58s
5156:	learn: 0.0017615	total: 9m 21s	remaining: 8m 47s
5561:	learn: 0.0017438	total: 9m 21s	remaining: 7m 28s
5560:	learn: 0.0017186	total: 9m 21s	remaining: 7m 28s
5400:	learn: 0.0020780	total: 9m 21s	remaining: 7m 58s
5664:	learn: 0.0017159	total: 9m 21s	remaining: 7m 10s
5562:	learn: 0.0017438	total: 9m 22s	remaining: 7m 28s
5157:	learn: 0.0017611	total: 9m 22s	remaining: 8m 47s
5561:	learn: 0.0017186	total: 9m 21s	remaining: 7m 28s
5665:	learn: 0.0017159	total: 9m 22s	remaining: 7m 9s
5401:	learn: 0.0020780	total: 9m 22s	remaining: 7m 58s
5563:	learn: 0.0017438	total: 9m 22s	remaining: 7m 28s
5666:	learn: 0.0017159	total: 9m 22s	remaining: 7m 9s
5562:	learn: 0.0017180	total: 9m 22s	remaining: 7m 28s
5158:	learn: 0.0017606	total: 9m 22s	remaining: 8m 47s
5402:	learn: 0.0020780	total: 9m 22s	remaining: 7m 58s
5564:	learn: 0.0017438	total: 9m 22s	remaining: 7m 28s
5667:	learn: 0.0017159	total: 9m 22s	remaining: 7m 9s
5403:	learn: 0.0020780	total: 9m 22s	remaining: 7m 58s
5563:	learn: 0.0017176	total: 9m 22s	remaining: 7m 28s
5159:	learn: 0.0017601	total: 9m 22s	remaining: 8m 47s
5565:	learn: 0.0017438	total: 9m 22s	remaining: 7m 27s
5404:	learn: 0.0020780	total: 9m 22s	remaining: 7m 58s
5668:	learn: 0.0017154	total: 9m 22s	remaining: 7m 9s
5564:	learn: 0.0017176	total: 9m 22s	remaining: 7m 28s
5160:	learn: 0.0017596	total: 9m 22s	remaining: 8m 47s
5405:	learn: 0.0020780	total: 9m 22s	remaining: 7m 57s
5566:	learn: 0.0017438	total: 9m 22s	remaining: 7m 27s
5669:	learn: 0.0017148	total: 9m 22s	remaining: 7m 9s
5565:	learn: 0.0017169	total: 9m 22s	remaining: 7m 27s
5406:	learn: 0.0020780	total: 9m 22s	remaining: 7m 57s
5161:	learn: 0.0017590	total: 9m 22s	remaining: 8m 47s
5567:	learn: 0.0017438	total: 9m 22s	remaining: 7m 27s
5670:	learn: 0.0017143	total: 9m 22s	remaining: 7m 9s
5566:	learn: 0.0017169	total: 9m 22s	remaining: 7m 27s
5407:	learn: 0.0020780	total: 9m 22s	remaining: 7m 57s
5162:	learn: 0.0017585	total: 9m 22s	remaining: 8m 47s
5568:	learn: 0.0017438	total: 9m 22s	remaining: 7m 27s
5671:	learn: 0.0017143	total: 9m 22s	remaining: 7m 9s
5567:	learn: 0.0017165	total: 9m 22s	remaining: 7m 27s
5163:	learn: 0.0017581	total: 9m 22s	remaining: 8m 46s
5408:	learn: 0.0020780	total: 9m 22s	remaining: 7m 57s
5569:	learn: 0.0017438	total: 9m 22s	remaining: 7m 27s
5672:	learn: 0.0017143	total: 9m 22s	remaining: 7m 9s
5568:	learn: 0.0017160	total: 9m 22s	remaining: 7m 27s
5409:	learn: 0.0020780	total: 9m 22s	remaining: 7m 57s
5570:	learn: 0.0017438	total: 9m 22s	remaining: 7m 27s
5164:	learn: 0.0017576	total: 9m 22s	remaining: 8m 46s
5673:	learn: 0.0017143	total: 9m 22s	remaining: 7m 9s
5569:	learn: 0.0017160	total: 9m 22s	remaining: 7m 27s
5571:	learn: 0.0017438	total: 9m 22s	remaining: 7m 27s
5165:	learn: 0.0017571	total: 9m 22s	remaining: 8m 46s
5410:	learn: 0.0020780	total: 9m 22s	remaining: 7m 57s
5674:	learn: 0.0017138	total: 9m 22s	remaining: 7m 8s
5570:	learn: 0.0017160	total: 9m 22s	remaining: 7m 27s
5572:	learn: 0.0017434	total: 9m 22s	remaining: 7m 27s
5166:	learn: 0.0017566	total: 9m 23s	remaining: 8m 46s
5411:	learn: 0.0020780	total: 9m 23s	remaining: 7m 57s
5675:	learn: 0.0017138	total: 9m 23s	remaining: 7m 8s
5571:	learn: 0.0017160	total: 9m 22s	remaining: 7m 27s
5573:	learn: 0.0017434	total: 9m 23s	remaining: 7m 27s
5167:	learn: 0.0017561	total: 9m 23s	remaining: 8m 46s
5412:	learn: 0.0020780	total: 9m 23s	remaining: 7m 57s
5676:	learn: 0.0017138	total: 9m 23s	remaining: 7m 8s
5572:	learn: 0.0017156	total: 9m 23s	remaining: 7m 27s
5574:	learn: 0.0017434	total: 9m 23s	remaining: 7m 27s
5677:	learn: 0.0017135	total: 9m 23s	remaining: 7m 8s
5168:	learn: 0.0017555	total: 9m 23s	remaining: 8m 46s
5413:	learn: 0.0020780	total: 9m 23s	remaining: 7m 57s
5573:	learn: 0.0017154	total: 9m 23s	remaining: 7m 27s
5575:	learn: 0.0017434	total: 9m 23s	remaining: 7m 26s
5169:	learn: 0.0017555	total: 9m 23s	remaining: 8m 46s
5678:	learn: 0.0017129	total: 9m 23s	remaining: 7m 8s
5574:	learn: 0.0017151	total: 9m 23s	remaining: 7m 27s
5576:	learn: 0.0017434	total: 9m 23s	remaining: 7m 26s
5414:	learn: 0.0020780	total: 9m 23s	remaining: 7m 57s
5170:	learn: 0.0017550	total: 9m 23s	remaining: 8m 46s
5575:	learn: 0.0017147	total: 9m 23s	remaining: 7m 26s
5577:	learn: 0.0017434	total: 9m 23s	remaining: 7m 26s
5679:	learn: 0.0017125	total: 9m 23s	remaining: 7m 8s
5415:	learn: 0.0020780	total: 9m 23s	remaining: 7m 56s
5171:	learn: 0.0017550	total: 9m 23s	remaining: 8m 46s
5576:	learn: 0.0017142	total: 9m 23s	remaining: 7m 26s
5578:	learn: 0.0017434	total: 9m 23s	remaining: 7m 26s
5680:	learn: 0.0017120	total: 9m 23s	remaining: 7m 8s
5416:	learn: 0.0020780	total: 9m 23s	remaining: 7m 56s
5172:	learn: 0.0017544	total: 9m 23s	remaining: 8m 45s
5681:	learn: 0.0017120	total: 9m 23s	remaining: 7m 8s
5579:	learn: 0.0017434	total: 9m 23s	remaining: 7m 26s
5577:	learn: 0.0017141	total: 9m 23s	remaining: 7m 26s
5173:	learn: 0.0017539	total: 9m 23s	remaining: 8m 45s
5417:	learn: 0.0020780	total: 9m 23s	remaining: 7m 56s
5682:	learn: 0.0017120	total: 9m 23s	remaining: 7m 8s
5580:	learn: 0.0017434	total: 9m 23s	remaining: 7m 26s
5418:	learn: 0.0020780	total: 9m 23s	remaining: 7m 56s
5578:	learn: 0.0017136	total: 9m 23s	remaining: 7m 26s
5581:	learn: 0.0017434	total: 9m 23s	remaining: 7m 26s
5174:	learn: 0.0017533	total: 9m 23s	remaining: 8m 45s
5683:	learn: 0.0017120	total: 9m 23s	remaining: 7m 8s
5579:	learn: 0.0017136	total: 9m 23s	remaining: 7m 26s
5419:	learn: 0.0020780	total: 9m 23s	remaining: 7m 56s
5582:	learn: 0.0017429	total: 9m 23s	remaining: 7m 26s
5175:	learn: 0.0017528	total: 9m 23s	remaining: 8m 45s
5684:	learn: 0.0017120	total: 9m 23s	remaining: 7m 8s
5580:	learn: 0.0017131	total: 9m 23s	remaining: 7m 26s
5583:	learn: 0.0017429	total: 9m 24s	remaining: 7m 26s
5176:	learn: 0.0017523	total: 9m 24s	remaining: 8m 45s
5420:	learn: 0.0020780	total: 9m 24s	remaining: 7m 56s
5685:	learn: 0.0017120	total: 9m 24s	remaining: 7m 7s
5581:	learn: 0.0017128	total: 9m 23s	remaining: 7m 26s

5584:	learn: 0.0017429	total: 9m 24s	remaining: 7m 25s
5177:	learn: 0.0017517	total: 9m 24s	remaining: 8m 45s
5686:	learn: 0.0017120	total: 9m 24s	remaining: 7m 7s
5421:	learn: 0.0020780	total: 9m 24s	remaining: 7m 56s
5582:	learn: 0.0017123	total: 9m 24s	remaining: 7m 26s
5687:	learn: 0.0017116	total: 9m 24s	remaining: 7m 7s
5585:	learn: 0.0017429	total: 9m 24s	remaining: 7m 25s
5422:	learn: 0.0020780	total: 9m 24s	remaining: 7m 56s
5178:	learn: 0.0017512	total: 9m 24s	remaining: 8m 45s
5688:	learn: 0.0017116	total: 9m 24s	remaining: 7m 7s
5583:	learn: 0.0017123	total: 9m 24s	remaining: 7m 26s
5586:	learn: 0.0017429	total: 9m 24s	remaining: 7m 25s
5179:	learn: 0.0017507	total: 9m 24s	remaining: 8m 45s
5423:	learn: 0.0020780	total: 9m 24s	remaining: 7m 56s
5689:	learn: 0.0017116	total: 9m 24s	remaining: 7m 7s
5584:	learn: 0.0017118	total: 9m 24s	remaining: 7m 26s
5180:	learn: 0.0017500	total: 9m 24s	remaining: 8m 44s
5587:	learn: 0.0017429	total: 9m 24s	remaining: 7m 25s
5424:	learn: 0.0020780	total: 9m 24s	remaining: 7m 56s
5690:	learn: 0.0017111	total: 9m 24s	remaining: 7m 7s
5585:	learn: 0.0017113	total: 9m 24s	remaining: 7m 25s
5181:	learn: 0.0017494	total: 9m 24s	remaining: 8m 44s
5588:	learn: 0.0017429	total: 9m 24s	remaining: 7m 25s
5586:	learn: 0.0017110	total: 9m 24s	remaining: 7m 25s
5691:	learn: 0.0017106	total: 9m 24s	remaining: 7m 7s
5425:	learn: 0.0020780	total: 9m 24s	remaining: 7m 55s
5182:	learn: 0.0017490	total: 9m 24s	remaining: 8m 44s
5589:	learn: 0.0017429	total: 9m 24s	remaining: 7m 25s
5587:	learn: 0.0017106	total: 9m 24s	remaining: 7m 25s
5692:	learn: 0.0017101	total: 9m 24s	remaining: 7m 7s
5183:	learn: 0.0017487	total: 9m 24s	remaining: 8m 44s
5426:	learn: 0.0020780	total: 9m 24s	remaining: 7m 55s
5590:	learn: 0.0017429	total: 9m 24s	remaining: 7m 25s
5588:	learn: 0.0017100	total: 9m 24s	remaining: 7m 25s
5693:	learn: 0.0017101	total: 9m 24s	remaining: 7m 7s
5591:	learn: 0.0017429	total: 9m 24s	remaining: 7m 25s
5184:	learn: 0.0017482	total: 9m 24s	remaining: 8m 44s
5427:	learn: 0.0020780	total: 9m 24s	remaining: 7m 55s
5589:	learn: 0.0017094	total: 9m 24s	remaining: 7m 25s
5694:	learn: 0.0017101	total: 9m 24s	remaining: 7m 6s
5592:	learn: 0.0017427	total: 9m 24s	remaining: 7m 25s
5185:	learn: 0.0017477	total: 9m 24s	remaining: 8m 44s
5695:	learn: 0.0017096	total: 9m 24s	remaining: 7m 6s
5590:	learn: 0.0017090	total: 9m 24s	remaining: 7m 25s
5428:	learn: 0.0020780	total: 9m 24s	remaining: 7m 55s
5593:	learn: 0.0017427	total: 9m 25s	remaining: 7m 25s
5186:	learn: 0.0017471	total: 9m 25s	remaining: 8m 44s
5696:	learn: 0.0017091	total: 9m 25s	remaining: 7m 6s
5591:	learn: 0.0017085	total: 9m 24s	remaining: 7m 25s
5594:	learn: 0.0017427	total: 9m 25s	remaining: 7m 24s
5429:	learn: 0.0020780	total: 9m 25s	remaining: 7m 55s
5187:	learn: 0.0017466	total: 9m 25s	remaining: 8m 44s
5697:	learn: 0.0017091	total: 9m 25s	remaining: 7m 6s
5592:	learn: 0.0017079	total: 9m 24s	remaining: 7m 25s
5595:	learn: 0.0017422	total: 9m 25s	remaining: 7m 24s
5188:	learn: 0.0017459	total: 9m 25s	remaining: 8m 44s
5430:	learn: 0.0020780	total: 9m 25s	remaining: 7m 55s
5698:	learn: 0.0017091	total: 9m 25s	remaining: 7m 6s
5596:	learn: 0.0017416	total: 9m 25s	remaining: 7m 24s
5593:	learn: 0.0017079	total: 9m 25s	remaining: 7m 25s
5189:	learn: 0.0017455	total: 9m 25s	remaining: 8m 43s
5431:	learn: 0.0020780	total: 9m 25s	remaining: 7m 55s
5597:	learn: 0.0017412	total: 9m 25s	remaining: 7m 24s
5594:	learn: 0.0017073	total: 9m 25s	remaining: 7m 24s
5699:	learn: 0.0017091	total: 9m 25s	remaining: 7m 6s
5190:	learn: 0.0017451	total: 9m 25s	remaining: 8m 43s
5432:	learn: 0.0020780	total: 9m 25s	remaining: 7m 55s
5700:	learn: 0.0017085	total: 9m 25s	remaining: 7m 6s
5595:	learn: 0.0017069	total: 9m 25s	remaining: 7m 24s
5598:	learn: 0.0017412	total: 9m 25s	remaining: 7m 24s
5191:	learn: 0.0017444	total: 9m 25s	remaining: 8m 43s
5701:	learn: 0.0017085	total: 9m 25s	remaining: 7m 6s
5596:	learn: 0.0017064	total: 9m 25s	remaining: 7m 24s
5433:	learn: 0.0020780	total: 9m 25s	remaining: 7m 55s
5599:	learn: 0.0017412	total: 9m 25s	remaining: 7m 24s
5702:	learn: 0.0017081	total: 9m 25s	remaining: 7m 6s
5192:	learn: 0.0017435	total: 9m 25s	remaining: 8m 43s
5597:	learn: 0.0017059	total: 9m 25s	remaining: 7m 24s
5600:	learn: 0.0017412	total: 9m 25s	remaining: 7m 24s
5434:	learn: 0.0020780	total: 9m 25s	remaining: 7m 55s
5598:	learn: 0.0017054	total: 9m 25s	remaining: 7m 24s
5703:	learn: 0.0017076	total: 9m 25s	remaining: 7m 6s
5601:	learn: 0.0017410	total: 9m 25s	remaining: 7m 24s
5193:	learn: 0.0017430	total: 9m 25s	remaining: 8m 43s
5599:	learn: 0.0017054	total: 9m 25s	remaining: 7m 24s
5704:	learn: 0.0017069	total: 9m 25s	remaining: 7m 5s
5435:	learn: 0.0020780	total: 9m 25s	remaining: 7m 55s
5602:	learn: 0.0017403	total: 9m 25s	remaining: 7m 24s
5600:	learn: 0.0017054	total: 9m 25s	remaining: 7m 24s
5194:	learn: 0.0017425	total: 9m 25s	remaining: 8m 43s
5705:	learn: 0.0017065	total: 9m 25s	remaining: 7m 5s
5603:	learn: 0.0017396	total: 9m 25s	remaining: 7m 23s
5436:	learn: 0.0020780	total: 9m 25s	remaining: 7m 54s
5706:	learn: 0.0017060	total: 9m 25s	remaining: 7m 5s
5601:	learn: 0.0017054	total: 9m 25s	remaining: 7m 24s
5195:	learn: 0.0017418	total: 9m 26s	remaining: 8m 43s
5604:	learn: 0.0017393	total: 9m 26s	remaining: 7m 23s
5437:	learn: 0.0020780	total: 9m 26s	remaining: 7m 54s
5707:	learn: 0.0017060	total: 9m 26s	remaining: 7m 5s
5602:	learn: 0.0017048	total: 9m 25s	remaining: 7m 24s
5605:	learn: 0.0017389	total: 9m 26s	remaining: 7m 23s
5196:	learn: 0.0017414	total: 9m 26s	remaining: 8m 43s
5438:	learn: 0.0020780	total: 9m 26s	remaining: 7m 54s
5708:	learn: 0.0017059	total: 9m 26s	remaining: 7m 5s
5603:	learn: 0.0017042	total: 9m 26s	remaining: 7m 23s
5606:	learn: 0.0017386	total: 9m 26s	remaining: 7m 23s
5439:	learn: 0.0020780	total: 9m 26s	remaining: 7m 54s
5709:	learn: 0.0017059	total: 9m 26s	remaining: 7m 5s
5197:	learn: 0.0017408	total: 9m 26s	remaining: 8m 43s
5607:	learn: 0.0017386	total: 9m 26s	remaining: 7m 23s
5604:	learn: 0.0017042	total: 9m 26s	remaining: 7m 23s
5710:	learn: 0.0017058	total: 9m 26s	remaining: 7m 5s
5440:	learn: 0.0020780	total: 9m 26s	remaining: 7m 54s
5198:	learn: 0.0017402	total: 9m 26s	remaining: 8m 43s
5605:	learn: 0.0017043	total: 9m 26s	remaining: 7m 23s
5608:	learn: 0.0017386	total: 9m 26s	remaining: 7m 23s
5711:	learn: 0.0017052	total: 9m 26s	remaining: 7m 5s
5441:	learn: 0.0020780	total: 9m 26s	remaining: 7m 54s
5609:	learn: 0.0017383	total: 9m 26s	remaining: 7m 23s
5199:	learn: 0.0017398	total: 9m 26s	remaining: 8m 42s
5606:	learn: 0.0017038	total: 9m 26s	remaining: 7m 23s
5712:	learn: 0.0017047	total: 9m 26s	remaining: 7m 5s
5442:	learn: 0.0020780	total: 9m 26s	remaining: 7m 54s
5610:	learn: 0.0017383	total: 9m 26s	remaining: 7m 23s
5200:	learn: 0.0017393	total: 9m 26s	remaining: 8m 42s
5607:	learn: 0.0017033	total: 9m 26s	remaining: 7m 23s
5713:	learn: 0.0017047	total: 9m 26s	remaining: 7m 4s
5611:	learn: 0.0017377	total: 9m 26s	remaining: 7m 23s
5443:	learn: 0.0020771	total: 9m 26s	remaining: 7m 54s
5714:	learn: 0.0017047	total: 9m 26s	remaining: 7m 4s
5608:	learn: 0.0017028	total: 9m 26s	remaining: 7m 23s
5201:	learn: 0.0017388	total: 9m 26s	remaining: 8m 42s
5612:	learn: 0.0017371	total: 9m 26s	remaining: 7m 22s
5715:	learn: 0.0017043	total: 9m 26s	remaining: 7m 4s
5609:	learn: 0.0017023	total: 9m 26s	remaining: 7m 23s
5444:	learn: 0.0020762	total: 9m 26s	remaining: 7m 54s
5613:	learn: 0.0017370	total: 9m 26s	remaining: 7m 22s
5202:	learn: 0.0017384	total: 9m 26s	remaining: 8m 42s
5614:	learn: 0.0017370	total: 9m 26s	remaining: 7m 22s
5716:	learn: 0.0017043	total: 9m 26s	remaining: 7m 4s
5445:	learn: 0.0020762	total: 9m 26s	remaining: 7m 54s
5610:	learn: 0.0017018	total: 9m 26s	remaining: 7m 23s
5203:	learn: 0.0017377	total: 9m 26s	remaining: 8m 42s
5615:	learn: 0.0017370	total: 9m 26s	remaining: 7m 22s
5446:	learn: 0.0020754	total: 9m 26s	remaining: 7m 53s
5717:	learn: 0.0017038	total: 9m 26s	remaining: 7m 4s
5611:	learn: 0.0017013	total: 9m 26s	remaining: 7m 23s
5204:	learn: 0.0017372	total: 9m 27s	remaining: 8m 42s
5616:	learn: 0.0017370	total: 9m 27s	remaining: 7m 22s
5447:	learn: 0.0020754	total: 9m 27s	remaining: 7m 53s
5718:	learn: 0.0017034	total: 9m 27s	remaining: 7m 4s
5612:	learn: 0.0017009	total: 9m 26s	remaining: 7m 23s
5205:	learn: 0.0017365	total: 9m 27s	remaining: 8m 42s
5617:	learn: 0.0017370	total: 9m 27s	remaining: 7m 22s
5448:	learn: 0.0020754	total: 9m 27s	remaining: 7m 53s
5719:	learn: 0.0017034	total: 9m 27s	remaining: 7m 4s
5613:	learn: 0.0017006	total: 9m 27s	remaining: 7m 23s
5206:	learn: 0.0017361	total: 9m 27s	remaining: 8m 42s
5449:	learn: 0.0020754	total: 9m 27s	remaining: 7m 53s
5618:	learn: 0.0017370	total: 9m 27s	remaining: 7m 22s
5720:	learn: 0.0017028	total: 9m 27s	remaining: 7m 4s
5207:	learn: 0.0017355	total: 9m 27s	remaining: 8m 42s
5614:	learn: 0.0017001	total: 9m 27s	remaining: 7m 22s
5619:	learn: 0.0017370	total: 9m 27s	remaining: 7m 22s
5721:	learn: 0.0017028	total: 9m 27s	remaining: 7m 4s
5450:	learn: 0.0020754	total: 9m 27s	remaining: 7m 53s
5208:	learn: 0.0017350	total: 9m 27s	remaining: 8m 41s
5615:	learn: 0.0016996	total: 9m 27s	remaining: 7m 22s
5620:	learn: 0.0017367	total: 9m 27s	remaining: 7m 22s
5451:	learn: 0.0020754	total: 9m 27s	remaining: 7m 53s
5722:	learn: 0.0017023	total: 9m 27s	remaining: 7m 4s
5209:	learn: 0.0017344	total: 9m 27s	remaining: 8m 41s
5616:	learn: 0.0016991	total: 9m 27s	remaining: 7m 22s
5621:	learn: 0.0017367	total: 9m 27s	remaining: 7m 21s
5723:	learn: 0.0017017	total: 9m 27s	remaining: 7m 3s
5452:	learn: 0.0020754	total: 9m 27s	remaining: 7m 53s
5617:	learn: 0.0016985	total: 9m 27s	remaining: 7m 22s
5210:	learn: 0.0017339	total: 9m 27s	remaining: 8m 41s
5622:	learn: 0.0017366	total: 9m 27s	remaining: 7m 21s
5724:	learn: 0.0017013	total: 9m 27s	remaining: 7m 3s
5453:	learn: 0.0020751	total: 9m 27s	remaining: 7m 53s
5211:	learn: 0.0017333	total: 9m 27s	remaining: 8m 41s
5618:	learn: 0.0016980	total: 9m 27s	remaining: 7m 22s
5623:	learn: 0.0017366	total: 9m 27s	remaining: 7m 21s
5725:	learn: 0.0017013	total: 9m 27s	remaining: 7m 3s
5454:	learn: 0.0020745	total: 9m 27s	remaining: 7m 53s
5212:	learn: 0.0017328	total: 9m 27s	remaining: 8m 41s
5619:	learn: 0.0016977	total: 9m 27s	remaining: 7m 22s
5624:	learn: 0.0017366	total: 9m 27s	remaining: 7m 21s
5213:	learn: 0.0017321	total: 9m 27s	remaining: 8m 41s
5726:	learn: 0.0017013	total: 9m 27s	remaining: 7m 3s
5620:	learn: 0.0016973	total: 9m 27s	remaining: 7m 22s
5455:	learn: 0.0020745	total: 9m 27s	remaining: 7m 53s
5625:	learn: 0.0017366	total: 9m 27s	remaining: 7m 21s
5727:	learn: 0.0017007	total: 9m 27s	remaining: 7m 3s
5214:	learn: 0.0017316	total: 9m 27s	remaining: 8m 41s
5728:	learn: 0.0017007	total: 9m 28s	remaining: 7m 3s
5626:	learn: 0.0017366	total: 9m 28s	remaining: 7m 21s
5621:	learn: 0.0016967	total: 9m 27s	remaining: 7m 22s
5456:	learn: 0.0020745	total: 9m 28s	remaining: 7m 52s
5215:	learn: 0.0017311	total: 9m 28s	remaining: 8m 41s
5729:	learn: 0.0017007	total: 9m 28s	remaining: 7m 3s
5627:	learn: 0.0017366	total: 9m 28s	remaining: 7m 21s
5457:	learn: 0.0020745	total: 9m 28s	remaining: 7m 52s
5622:	learn: 0.0016964	total: 9m 28s	remaining: 7m 22s
5216:	learn: 0.0017306	total: 9m 28s	remaining: 8m 40s
5730:	learn: 0.0017002	total: 9m 28s	remaining: 7m 3s
5628:	learn: 0.0017366	total: 9m 28s	remaining: 7m 21s
5623:	learn: 0.0016959	total: 9m 28s	remaining: 7m 22s
5458:	learn: 0.0020745	total: 9m 28s	remaining: 7m 52s
5731:	learn: 0.0017002	total: 9m 28s	remaining: 7m 3s
5217:	learn: 0.0017306	total: 9m 28s	remaining: 8m 40s
5629:	learn: 0.0017363	total: 9m 28s	remaining: 7m 21s
5624:	learn: 0.0016955	total: 9m 28s	remaining: 7m 21s
5732:	learn: 0.0016997	total: 9m 28s	remaining: 7m 3s
5459:	learn: 0.0020745	total: 9m 28s	remaining: 7m 52s
5218:	learn: 0.0017301	total: 9m 28s	remaining: 8m 40s
5630:	learn: 0.0017361	total: 9m 28s	remaining: 7m 21s
5733:	learn: 0.0016997	total: 9m 28s	remaining: 7m 2s
5625:	learn: 0.0016949	total: 9m 28s	remaining: 7m 21s
5460:	learn: 0.0020745	total: 9m 28s	remaining: 7m 52s
5631:	learn: 0.0017361	total: 9m 28s	remaining: 7m 20s
5219:	learn: 0.0017301	total: 9m 28s	remaining: 8m 40s
5461:	learn: 0.0020744	total: 9m 28s	remaining: 7m 52s
5734:	learn: 0.0016997	total: 9m 28s	remaining: 7m 2s
5626:	learn: 0.0016945	total: 9m 28s	remaining: 7m 21s
5220:	learn: 0.0017295	total: 9m 28s	remaining: 8m 40s
5632:	learn: 0.0017361	total: 9m 28s	remaining: 7m 20s
5462:	learn: 0.0020737	total: 9m 28s	remaining: 7m 52s
5735:	learn: 0.0016997	total: 9m 28s	remaining: 7m 2s
5627:	learn: 0.0016939	total: 9m 28s	remaining: 7m 21s
5221:	learn: 0.0017295	total: 9m 28s	remaining: 8m 40s
5633:	learn: 0.0017355	total: 9m 28s	remaining: 7m 20s
5736:	learn: 0.0016993	total: 9m 28s	remaining: 7m 2s
5463:	learn: 0.0020737	total: 9m 28s	remaining: 7m 52s
5222:	learn: 0.0017291	total: 9m 28s	remaining: 8m 40s
5628:	learn: 0.0016939	total: 9m 28s	remaining: 7m 21s
5634:	learn: 0.0017349	total: 9m 28s	remaining: 7m 20s
5737:	learn: 0.0016993	total: 9m 28s	remaining: 7m 2s
5223:	learn: 0.0017286	total: 9m 28s	remaining: 8m 40s
5629:	learn: 0.0016935	total: 9m 28s	remaining: 7m 21s
5464:	learn: 0.0020737	total: 9m 28s	remaining: 7m 52s
5635:	learn: 0.0017349	total: 9m 28s	remaining: 7m 20s
5738:	learn: 0.0016993	total: 9m 28s	remaining: 7m 2s
5630:	learn: 0.0016930	total: 9m 28s	remaining: 7m 21s
5224:	learn: 0.0017282	total: 9m 29s	remaining: 8m 40s
5636:	learn: 0.0017347	total: 9m 29s	remaining: 7m 20s
5465:	learn: 0.0020737	total: 9m 29s	remaining: 7m 52s
5739:	learn: 0.0016993	total: 9m 29s	remaining: 7m 2s
5225:	learn: 0.0017279	total: 9m 29s	remaining: 8m 39s
5631:	learn: 0.0016925	total: 9m 28s	remaining: 7m 21s
5637:	learn: 0.0017345	total: 9m 29s	remaining: 7m 20s
5740:	learn: 0.0016993	total: 9m 29s	remaining: 7m 2s
5466:	learn: 0.0020737	total: 9m 29s	remaining: 7m 51s
5632:	learn: 0.0016925	total: 9m 29s	remaining: 7m 21s
5226:	learn: 0.0017274	total: 9m 29s	remaining: 8m 39s
5638:	learn: 0.0017338	total: 9m 29s	remaining: 7m 20s
5741:	learn: 0.0016989	total: 9m 29s	remaining: 7m 2s
5633:	learn: 0.0016919	total: 9m 29s	remaining: 7m 21s
5467:	learn: 0.0020737	total: 9m 29s	remaining: 7m 51s
5227:	learn: 0.0017268	total: 9m 29s	remaining: 8m 39s
5639:	learn: 0.0017338	total: 9m 29s	remaining: 7m 20s
5742:	learn: 0.0016985	total: 9m 29s	remaining: 7m 1s
5634:	learn: 0.0016914	total: 9m 29s	remaining: 7m 20s
5468:	learn: 0.0020737	total: 9m 29s	remaining: 7m 51s
5640:	learn: 0.0017338	total: 9m 29s	remaining: 7m 20s
5228:	learn: 0.0017264	total: 9m 29s	remaining: 8m 39s
5635:	learn: 0.0016910	total: 9m 29s	remaining: 7m 20s
5743:	learn: 0.0016977	total: 9m 29s	remaining: 7m 1s
5469:	learn: 0.0020730	total: 9m 29s	remaining: 7m 51s
5641:	learn: 0.0017332	total: 9m 29s	remaining: 7m 19s
5636:	learn: 0.0016905	total: 9m 29s	remaining: 7m 20s
5229:	learn: 0.0017259	total: 9m 29s	remaining: 8m 39s
5744:	learn: 0.0016972	total: 9m 29s	remaining: 7m 1s
5470:	learn: 0.0020730	total: 9m 29s	remaining: 7m 51s
5642:	learn: 0.0017331	total: 9m 29s	remaining: 7m 19s
5230:	learn: 0.0017254	total: 9m 29s	remaining: 8m 39s
5637:	learn: 0.0016901	total: 9m 29s	remaining: 7m 20s
5745:	learn: 0.0016972	total: 9m 29s	remaining: 7m 1s
5471:	learn: 0.0020730	total: 9m 29s	remaining: 7m 51s
5643:	learn: 0.0017324	total: 9m 29s	remaining: 7m 19s
5638:	learn: 0.0016896	total: 9m 29s	remaining: 7m 20s
5746:	learn: 0.0016972	total: 9m 29s	remaining: 7m 1s
5231:	learn: 0.0017249	total: 9m 29s	remaining: 8m 39s
5472:	learn: 0.0020730	total: 9m 29s	remaining: 7m 51s
5639:	learn: 0.0016893	total: 9m 29s	remaining: 7m 20s
5644:	learn: 0.0017324	total: 9m 29s	remaining: 7m 19s
5747:	learn: 0.0016972	total: 9m 29s	remaining: 7m 1s
5473:	learn: 0.0020724	total: 9m 29s	remaining: 7m 51s
5232:	learn: 0.0017243	total: 9m 29s	remaining: 8m 39s
5640:	learn: 0.0016889	total: 9m 29s	remaining: 7m 20s
5748:	learn: 0.0016972	total: 9m 29s	remaining: 7m 1s
5645:	learn: 0.0017320	total: 9m 29s	remaining: 7m 19s
5233:	learn: 0.0017240	total: 9m 29s	remaining: 8m 39s
5474:	learn: 0.0020724	total: 9m 29s	remaining: 7m 51s
5641:	learn: 0.0016889	total: 9m 29s	remaining: 7m 20s
5749:	learn: 0.0016972	total: 9m 29s	remaining: 7m 1s
5646:	learn: 0.0017315	total: 9m 30s	remaining: 7m 19s

5475:	learn: 0.0020724	total: 9m 30s	remaining: 7m 50s
5642:	learn: 0.0016885	total: 9m 29s	remaining: 7m 20s
5234:	learn: 0.0017235	total: 9m 30s	remaining: 8m 38s
5750:	learn: 0.0016972	total: 9m 30s	remaining: 7m 1s
5476:	learn: 0.0020724	total: 9m 30s	remaining: 7m 50s
5647:	learn: 0.0017310	total: 9m 30s	remaining: 7m 19s
5643:	learn: 0.0016880	total: 9m 30s	remaining: 7m 19s
5235:	learn: 0.0017230	total: 9m 30s	remaining: 8m 38s
5751:	learn: 0.0016972	total: 9m 30s	remaining: 7m 1s
5477:	learn: 0.0020724	total: 9m 30s	remaining: 7m 50s
5648:	learn: 0.0017310	total: 9m 30s	remaining: 7m 19s
5752:	learn: 0.0016968	total: 9m 30s	remaining: 7m 1s
5644:	learn: 0.0016875	total: 9m 30s	remaining: 7m 19s
5649:	learn: 0.0017308	total: 9m 30s	remaining: 7m 19s
5478:	learn: 0.0020724	total: 9m 30s	remaining: 7m 50s
5236:	learn: 0.0017225	total: 9m 30s	remaining: 8m 38s
5650:	learn: 0.0017308	total: 9m 30s	remaining: 7m 18s
5645:	learn: 0.0016870	total: 9m 30s	remaining: 7m 19s
5479:	learn: 0.0020724	total: 9m 30s	remaining: 7m 50s
5753:	learn: 0.0016968	total: 9m 30s	remaining: 7m
5651:	learn: 0.0017308	total: 9m 30s	remaining: 7m 18s
5237:	learn: 0.0017222	total: 9m 30s	remaining: 8m 38s
5646:	learn: 0.0016866	total: 9m 30s	remaining: 7m 19s
5754:	learn: 0.0016968	total: 9m 30s	remaining: 7m
5480:	learn: 0.0020724	total: 9m 30s	remaining: 7m 50s
5652:	learn: 0.0017308	total: 9m 30s	remaining: 7m 18s
5647:	learn: 0.0016861	total: 9m 30s	remaining: 7m 19s
5238:	learn: 0.0017217	total: 9m 30s	remaining: 8m 38s
5755:	learn: 0.0016967	total: 9m 30s	remaining: 7m
5481:	learn: 0.0020724	total: 9m 30s	remaining: 7m 50s
5653:	learn: 0.0017302	total: 9m 30s	remaining: 7m 18s
5648:	learn: 0.0016856	total: 9m 30s	remaining: 7m 19s
5239:	learn: 0.0017213	total: 9m 30s	remaining: 8m 38s
5756:	learn: 0.0016961	total: 9m 30s	remaining: 7m
5482:	learn: 0.0020724	total: 9m 30s	remaining: 7m 50s
5649:	learn: 0.0016856	total: 9m 30s	remaining: 7m 19s
5654:	learn: 0.0017302	total: 9m 30s	remaining: 7m 18s
5757:	learn: 0.0016961	total: 9m 30s	remaining: 7m
5240:	learn: 0.0017208	total: 9m 30s	remaining: 8m 38s
5650:	learn: 0.0016851	total: 9m 30s	remaining: 7m 19s
5483:	learn: 0.0020716	total: 9m 30s	remaining: 7m 50s
5655:	learn: 0.0017302	total: 9m 30s	remaining: 7m 18s
5758:	learn: 0.0016961	total: 9m 30s	remaining: 7m
5656:	learn: 0.0017302	total: 9m 30s	remaining: 7m 18s
5241:	learn: 0.0017208	total: 9m 30s	remaining: 8m 38s
5651:	learn: 0.0016846	total: 9m 30s	remaining: 7m 19s
5484:	learn: 0.0020716	total: 9m 30s	remaining: 7m 50s
5657:	learn: 0.0017297	total: 9m 31s	remaining: 7m 18s
5759:	learn: 0.0016961	total: 9m 31s	remaining: 7m
5242:	learn: 0.0017208	total: 9m 31s	remaining: 8m 38s
5652:	learn: 0.0016842	total: 9m 30s	remaining: 7m 19s
5658:	learn: 0.0017291	total: 9m 31s	remaining: 7m 18s
5485:	learn: 0.0020716	total: 9m 31s	remaining: 7m 49s
5243:	learn: 0.0017203	total: 9m 31s	remaining: 8m 37s
5760:	learn: 0.0016961	total: 9m 31s	remaining: 7m
5653:	learn: 0.0016842	total: 9m 31s	remaining: 7m 18s
5659:	learn: 0.0017288	total: 9m 31s	remaining: 7m 17s
5244:	learn: 0.0017199	total: 9m 31s	remaining: 8m 37s
5761:	learn: 0.0016961	total: 9m 31s	remaining: 7m
5486:	learn: 0.0020716	total: 9m 31s	remaining: 7m 49s
5654:	learn: 0.0016837	total: 9m 31s	remaining: 7m 18s
5660:	learn: 0.0017285	total: 9m 31s	remaining: 7m 17s
5245:	learn: 0.0017194	total: 9m 31s	remaining: 8m 37s
5762:	learn: 0.0016961	total: 9m 31s	remaining: 7m
5655:	learn: 0.0016832	total: 9m 31s	remaining: 7m 18s
5661:	learn: 0.0017285	total: 9m 31s	remaining: 7m 17s
5487:	learn: 0.0020716	total: 9m 31s	remaining: 7m 49s
5246:	learn: 0.0017190	total: 9m 31s	remaining: 8m 37s
5763:	learn: 0.0016961	total: 9m 31s	remaining: 6m 59s
5488:	learn: 0.0020716	total: 9m 31s	remaining: 7m 49s
5662:	learn: 0.0017286	total: 9m 31s	remaining: 7m 17s
5656:	learn: 0.0016828	total: 9m 31s	remaining: 7m 18s
5764:	learn: 0.0016954	total: 9m 31s	remaining: 6m 59s
5247:	learn: 0.0017190	total: 9m 31s	remaining: 8m 37s
5663:	learn: 0.0017285	total: 9m 31s	remaining: 7m 17s
5765:	learn: 0.0016954	total: 9m 31s	remaining: 6m 59s
5657:	learn: 0.0016824	total: 9m 31s	remaining: 7m 18s
5489:	learn: 0.0020716	total: 9m 31s	remaining: 7m 49s
5248:	learn: 0.0017185	total: 9m 31s	remaining: 8m 37s
5664:	learn: 0.0017285	total: 9m 31s	remaining: 7m 17s
5658:	learn: 0.0016819	total: 9m 31s	remaining: 7m 18s
5766:	learn: 0.0016950	total: 9m 31s	remaining: 6m 59s
5490:	learn: 0.0020716	total: 9m 31s	remaining: 7m 49s
5249:	learn: 0.0017180	total: 9m 31s	remaining: 8m 37s
5665:	learn: 0.0017280	total: 9m 31s	remaining: 7m 17s
5767:	learn: 0.0016944	total: 9m 31s	remaining: 6m 59s
5659:	learn: 0.0016815	total: 9m 31s	remaining: 7m 18s
5491:	learn: 0.0020716	total: 9m 31s	remaining: 7m 49s
5250:	learn: 0.0017174	total: 9m 31s	remaining: 8m 37s
5666:	learn: 0.0017280	total: 9m 31s	remaining: 7m 17s
5768:	learn: 0.0016938	total: 9m 31s	remaining: 6m 59s
5660:	learn: 0.0016811	total: 9m 31s	remaining: 7m 18s
5251:	learn: 0.0017168	total: 9m 31s	remaining: 8m 37s
5492:	learn: 0.0020717	total: 9m 31s	remaining: 7m 49s
5769:	learn: 0.0016932	total: 9m 31s	remaining: 6m 59s
5667:	learn: 0.0017280	total: 9m 31s	remaining: 7m 17s
5661:	learn: 0.0016807	total: 9m 31s	remaining: 7m 18s
5252:	learn: 0.0017163	total: 9m 32s	remaining: 8m 36s
5770:	learn: 0.0016932	total: 9m 32s	remaining: 6m 59s
5662:	learn: 0.0016803	total: 9m 31s	remaining: 7m 18s
5493:	learn: 0.0020716	total: 9m 32s	remaining: 7m 49s
5668:	learn: 0.0017280	total: 9m 32s	remaining: 7m 17s
5669:	learn: 0.0017274	total: 9m 32s	remaining: 7m 16s
5253:	learn: 0.0017157	total: 9m 32s	remaining: 8m 36s
5771:	learn: 0.0016932	total: 9m 32s	remaining: 6m 59s
5663:	learn: 0.0016798	total: 9m 32s	remaining: 7m 17s
5494:	learn: 0.0020704	total: 9m 32s	remaining: 7m 49s
5772:	learn: 0.0016928	total: 9m 32s	remaining: 6m 58s
5495:	learn: 0.0020704	total: 9m 32s	remaining: 7m 48s
5670:	learn: 0.0017272	total: 9m 32s	remaining: 7m 16s
5254:	learn: 0.0017152	total: 9m 32s	remaining: 8m 36s
5664:	learn: 0.0016792	total: 9m 32s	remaining: 7m 17s
5773:	learn: 0.0016923	total: 9m 32s	remaining: 6m 58s
5496:	learn: 0.0020704	total: 9m 32s	remaining: 7m 48s
5671:	learn: 0.0017271	total: 9m 32s	remaining: 7m 16s
5665:	learn: 0.0016792	total: 9m 32s	remaining: 7m 17s
5255:	learn: 0.0017146	total: 9m 32s	remaining: 8m 36s
5774:	learn: 0.0016923	total: 9m 32s	remaining: 6m 58s
5672:	learn: 0.0017271	total: 9m 32s	remaining: 7m 16s
5666:	learn: 0.0016788	total: 9m 32s	remaining: 7m 17s
5497:	learn: 0.0020704	total: 9m 32s	remaining: 7m 48s
5256:	learn: 0.0017142	total: 9m 32s	remaining: 8m 36s
5775:	learn: 0.0016918	total: 9m 32s	remaining: 6m 58s
5667:	learn: 0.0016787	total: 9m 32s	remaining: 7m 17s
5673:	learn: 0.0017271	total: 9m 32s	remaining: 7m 16s
5498:	learn: 0.0020704	total: 9m 32s	remaining: 7m 48s
5257:	learn: 0.0017139	total: 9m 32s	remaining: 8m 36s
5776:	learn: 0.0016918	total: 9m 32s	remaining: 6m 58s
5674:	learn: 0.0017271	total: 9m 32s	remaining: 7m 16s
5668:	learn: 0.0016784	total: 9m 32s	remaining: 7m 17s
5499:	learn: 0.0020696	total: 9m 32s	remaining: 7m 48s
5258:	learn: 0.0017135	total: 9m 32s	remaining: 8m 36s
5777:	learn: 0.0016914	total: 9m 32s	remaining: 6m 58s
5675:	learn: 0.0017265	total: 9m 32s	remaining: 7m 16s
5669:	learn: 0.0016780	total: 9m 32s	remaining: 7m 17s
5500:	learn: 0.0020696	total: 9m 32s	remaining: 7m 48s
5670:	learn: 0.0016780	total: 9m 32s	remaining: 7m 17s
5778:	learn: 0.0016909	total: 9m 32s	remaining: 6m 58s
5676:	learn: 0.0017256	total: 9m 32s	remaining: 7m 16s
5259:	learn: 0.0017135	total: 9m 32s	remaining: 8m 36s
5501:	learn: 0.0020696	total: 9m 32s	remaining: 7m 48s
5671:	learn: 0.0016776	total: 9m 32s	remaining: 7m 17s
5779:	learn: 0.0016903	total: 9m 32s	remaining: 6m 58s
5260:	learn: 0.0017129	total: 9m 32s	remaining: 8m 36s
5677:	learn: 0.0017256	total: 9m 32s	remaining: 7m 16s
5502:	learn: 0.0020696	total: 9m 32s	remaining: 7m 48s
5672:	learn: 0.0016769	total: 9m 32s	remaining: 7m 16s
5261:	learn: 0.0017123	total: 9m 33s	remaining: 8m 35s
5678:	learn: 0.0017256	total: 9m 33s	remaining: 7m 16s
5780:	learn: 0.0016903	total: 9m 33s	remaining: 6m 58s
5503:	learn: 0.0020688	total: 9m 33s	remaining: 7m 48s
5673:	learn: 0.0016765	total: 9m 32s	remaining: 7m 16s
5262:	learn: 0.0017118	total: 9m 33s	remaining: 8m 35s
5679:	learn: 0.0017256	total: 9m 33s	remaining: 7m 15s
5504:	learn: 0.0020688	total: 9m 33s	remaining: 7m 48s
5781:	learn: 0.0016899	total: 9m 33s	remaining: 6m 58s
5674:	learn: 0.0016765	total: 9m 33s	remaining: 7m 16s
5680:	learn: 0.0017251	total: 9m 33s	remaining: 7m 15s
5263:	learn: 0.0017114	total: 9m 33s	remaining: 8m 35s
5782:	learn: 0.0016899	total: 9m 33s	remaining: 6m 58s
5505:	learn: 0.0020688	total: 9m 33s	remaining: 7m 47s
5675:	learn: 0.0016761	total: 9m 33s	remaining: 7m 16s
5681:	learn: 0.0017247	total: 9m 33s	remaining: 7m 15s
5264:	learn: 0.0017109	total: 9m 33s	remaining: 8m 35s
5783:	learn: 0.0016899	total: 9m 33s	remaining: 6m 57s
5506:	learn: 0.0020688	total: 9m 33s	remaining: 7m 47s
5676:	learn: 0.0016756	total: 9m 33s	remaining: 7m 16s
5682:	learn: 0.0017247	total: 9m 33s	remaining: 7m 15s
5784:	learn: 0.0016899	total: 9m 33s	remaining: 6m 57s
5265:	learn: 0.0017105	total: 9m 33s	remaining: 8m 35s
5507:	learn: 0.0020688	total: 9m 33s	remaining: 7m 47s
5683:	learn: 0.0017247	total: 9m 33s	remaining: 7m 15s
5785:	learn: 0.0016894	total: 9m 33s	remaining: 6m 57s
5677:	learn: 0.0016750	total: 9m 33s	remaining: 7m 16s
5266:	learn: 0.0017099	total: 9m 33s	remaining: 8m 35s
5508:	learn: 0.0020688	total: 9m 33s	remaining: 7m 47s
5678:	learn: 0.0016746	total: 9m 33s	remaining: 7m 16s
5684:	learn: 0.0017247	total: 9m 33s	remaining: 7m 15s
5786:	learn: 0.0016895	total: 9m 33s	remaining: 6m 57s
5267:	learn: 0.0017099	total: 9m 33s	remaining: 8m 35s
5679:	learn: 0.0016742	total: 9m 33s	remaining: 7m 16s
5787:	learn: 0.0016891	total: 9m 33s	remaining: 6m 57s
5509:	learn: 0.0020688	total: 9m 33s	remaining: 7m 47s
5685:	learn: 0.0017247	total: 9m 33s	remaining: 7m 15s
5680:	learn: 0.0016737	total: 9m 33s	remaining: 7m 16s
5268:	learn: 0.0017094	total: 9m 33s	remaining: 8m 35s
5788:	learn: 0.0016891	total: 9m 33s	remaining: 6m 57s
5510:	learn: 0.0020688	total: 9m 33s	remaining: 7m 47s
5686:	learn: 0.0017247	total: 9m 33s	remaining: 7m 15s
5681:	learn: 0.0016733	total: 9m 33s	remaining: 7m 15s
5789:	learn: 0.0016886	total: 9m 33s	remaining: 6m 57s
5269:	learn: 0.0017090	total: 9m 33s	remaining: 8m 35s
5687:	learn: 0.0017241	total: 9m 33s	remaining: 7m 15s
5511:	learn: 0.0020688	total: 9m 33s	remaining: 7m 47s
5790:	learn: 0.0016884	total: 9m 33s	remaining: 6m 57s
5682:	learn: 0.0016729	total: 9m 33s	remaining: 7m 15s
5270:	learn: 0.0017085	total: 9m 34s	remaining: 8m 34s
5688:	learn: 0.0017234	total: 9m 34s	remaining: 7m 14s
5512:	learn: 0.0020688	total: 9m 34s	remaining: 7m 47s
5683:	learn: 0.0016725	total: 9m 33s	remaining: 7m 15s
5791:	learn: 0.0016884	total: 9m 34s	remaining: 6m 57s
5271:	learn: 0.0017085	total: 9m 34s	remaining: 8m 34s
5689:	learn: 0.0017228	total: 9m 34s	remaining: 7m 14s
5513:	learn: 0.0020688	total: 9m 34s	remaining: 7m 47s
5684:	learn: 0.0016720	total: 9m 34s	remaining: 7m 15s
5792:	learn: 0.0016881	total: 9m 34s	remaining: 6m 56s
5272:	learn: 0.0017079	total: 9m 34s	remaining: 8m 34s
5690:	learn: 0.0017221	total: 9m 34s	remaining: 7m 14s
5685:	learn: 0.0016715	total: 9m 34s	remaining: 7m 15s
5793:	learn: 0.0016881	total: 9m 34s	remaining: 6m 56s
5514:	learn: 0.0020688	total: 9m 34s	remaining: 7m 47s
5691:	learn: 0.0017221	total: 9m 34s	remaining: 7m 14s
5273:	learn: 0.0017075	total: 9m 34s	remaining: 8m 34s
5686:	learn: 0.0016711	total: 9m 34s	remaining: 7m 15s
5794:	learn: 0.0016877	total: 9m 34s	remaining: 6m 56s
5515:	learn: 0.0020688	total: 9m 34s	remaining: 7m 46s
5692:	learn: 0.0017218	total: 9m 34s	remaining: 7m 14s
5274:	learn: 0.0017070	total: 9m 34s	remaining: 8m 34s
5687:	learn: 0.0016707	total: 9m 34s	remaining: 7m 15s
5795:	learn: 0.0016872	total: 9m 34s	remaining: 6m 56s
5693:	learn: 0.0017211	total: 9m 34s	remaining: 7m 14s
5516:	learn: 0.0020688	total: 9m 34s	remaining: 7m 46s
5275:	learn: 0.0017065	total: 9m 34s	remaining: 8m 34s
5796:	learn: 0.0016867	total: 9m 34s	remaining: 6m 56s
5694:	learn: 0.0017212	total: 9m 34s	remaining: 7m 14s
5688:	learn: 0.0016703	total: 9m 34s	remaining: 7m 15s
5797:	learn: 0.0016862	total: 9m 34s	remaining: 6m 56s
5517:	learn: 0.0020688	total: 9m 34s	remaining: 7m 46s
5689:	learn: 0.0016699	total: 9m 34s	remaining: 7m 15s
5695:	learn: 0.0017208	total: 9m 34s	remaining: 7m 14s
5276:	learn: 0.0017060	total: 9m 34s	remaining: 8m 34s
5798:	learn: 0.0016862	total: 9m 34s	remaining: 6m 56s
5518:	learn: 0.0020687	total: 9m 34s	remaining: 7m 46s
5696:	learn: 0.0017208	total: 9m 34s	remaining: 7m 14s
5690:	learn: 0.0016694	total: 9m 34s	remaining: 7m 15s
5277:	learn: 0.0017060	total: 9m 34s	remaining: 8m 34s
5799:	learn: 0.0016859	total: 9m 34s	remaining: 6m 56s
5519:	learn: 0.0020688	total: 9m 34s	remaining: 7m 46s
5691:	learn: 0.0016690	total: 9m 34s	remaining: 7m 14s
5697:	learn: 0.0017207	total: 9m 34s	remaining: 7m 14s
5800:	learn: 0.0016859	total: 9m 34s	remaining: 6m 56s
5278:	learn: 0.0017056	total: 9m 34s	remaining: 8m 34s
5520:	learn: 0.0020687	total: 9m 34s	remaining: 7m 46s
5692:	learn: 0.0016685	total: 9m 34s	remaining: 7m 14s
5698:	learn: 0.0017207	total: 9m 34s	remaining: 7m 13s
5801:	learn: 0.0016858	total: 9m 34s	remaining: 6m 56s
5521:	learn: 0.0020687	total: 9m 35s	remaining: 7m 46s
5693:	learn: 0.0016681	total: 9m 34s	remaining: 7m 14s
5279:	learn: 0.0017051	total: 9m 35s	remaining: 8m 34s
5802:	learn: 0.0016854	total: 9m 35s	remaining: 6m 55s
5699:	learn: 0.0017204	total: 9m 35s	remaining: 7m 13s
5522:	learn: 0.0020687	total: 9m 35s	remaining: 7m 46s
5694:	learn: 0.0016676	total: 9m 34s	remaining: 7m 14s
5280:	learn: 0.0017045	total: 9m 35s	remaining: 8m 33s
5700:	learn: 0.0017199	total: 9m 35s	remaining: 7m 13s
5803:	learn: 0.0016849	total: 9m 35s	remaining: 6m 55s
5695:	learn: 0.0016672	total: 9m 35s	remaining: 7m 14s
5523:	learn: 0.0020687	total: 9m 35s	remaining: 7m 46s
5701:	learn: 0.0017199	total: 9m 35s	remaining: 7m 13s
5804:	learn: 0.0016846	total: 9m 35s	remaining: 6m 55s
5281:	learn: 0.0017040	total: 9m 35s	remaining: 8m 33s
5696:	learn: 0.0016668	total: 9m 35s	remaining: 7m 14s
5524:	learn: 0.0020688	total: 9m 35s	remaining: 7m 45s
5697:	learn: 0.0016664	total: 9m 35s	remaining: 7m 14s
5805:	learn: 0.0016846	total: 9m 35s	remaining: 6m 55s
5525:	learn: 0.0020687	total: 9m 35s	remaining: 7m 45s
5702:	learn: 0.0017199	total: 9m 35s	remaining: 7m 13s
5282:	learn: 0.0017033	total: 9m 35s	remaining: 8m 33s
5698:	learn: 0.0016659	total: 9m 35s	remaining: 7m 14s
5806:	learn: 0.0016846	total: 9m 35s	remaining: 6m 55s
5526:	learn: 0.0020688	total: 9m 35s	remaining: 7m 45s
5283:	learn: 0.0017029	total: 9m 35s	remaining: 8m 33s
5703:	learn: 0.0017195	total: 9m 35s	remaining: 7m 13s
5807:	learn: 0.0016846	total: 9m 35s	remaining: 6m 55s
5699:	learn: 0.0016655	total: 9m 35s	remaining: 7m 14s
5527:	learn: 0.0020687	total: 9m 35s	remaining: 7m 45s
5284:	learn: 0.0017022	total: 9m 35s	remaining: 8m 33s
5704:	learn: 0.0017188	total: 9m 35s	remaining: 7m 13s
5808:	learn: 0.0016840	total: 9m 35s	remaining: 6m 55s
5700:	learn: 0.0016649	total: 9m 35s	remaining: 7m 13s
5285:	learn: 0.0017022	total: 9m 35s	remaining: 8m 33s
5528:	learn: 0.0020687	total: 9m 35s	remaining: 7m 45s
5705:	learn: 0.0017188	total: 9m 35s	remaining: 7m 13s
5701:	learn: 0.0016645	total: 9m 35s	remaining: 7m 13s
5286:	learn: 0.0017016	total: 9m 35s	remaining: 8m 33s
5809:	learn: 0.0016840	total: 9m 35s	remaining: 6m 55s
5529:	learn: 0.0020687	total: 9m 35s	remaining: 7m 45s
5702:	learn: 0.0016645	total: 9m 35s	remaining: 7m 13s
5706:	learn: 0.0017188	total: 9m 35s	remaining: 7m 13s
5530:	learn: 0.0020687	total: 9m 35s	remaining: 7m 45s
5287:	learn: 0.0017016	total: 9m 35s	remaining: 8m 33s
5810:	learn: 0.0016835	total: 9m 35s	remaining: 6m 55s
5531:	learn: 0.0020687	total: 9m 35s	remaining: 7m 45s
5703:	learn: 0.0016641	total: 9m 35s	remaining: 7m 13s
5288:	learn: 0.0017010	total: 9m 36s	remaining: 8m 33s
5707:	learn: 0.0017188	total: 9m 36s	remaining: 7m 13s
5811:	learn: 0.0016832	total: 9m 36s	remaining: 6m 55s

5708:	learn: 0.0017188	total: 9m 36s	remaining: 7m 12s
5289:	learn: 0.0017010	total: 9m 36s	remaining: 8m 32s
5704:	learn: 0.0016637	total: 9m 35s	remaining: 7m 13s
5532:	learn: 0.0020687	total: 9m 36s	remaining: 7m 45s
5812:	learn: 0.0016826	total: 9m 36s	remaining: 6m 54s
5709:	learn: 0.0017187	total: 9m 36s	remaining: 7m 12s
5290:	learn: 0.0017010	total: 9m 36s	remaining: 8m 32s
5705:	learn: 0.0016633	total: 9m 36s	remaining: 7m 13s
5813:	learn: 0.0016821	total: 9m 36s	remaining: 6m 54s
5533:	learn: 0.0020681	total: 9m 36s	remaining: 7m 44s
5706:	learn: 0.0016627	total: 9m 36s	remaining: 7m 13s
5814:	learn: 0.0016816	total: 9m 36s	remaining: 6m 54s
5710:	learn: 0.0017187	total: 9m 36s	remaining: 7m 12s
5291:	learn: 0.0017007	total: 9m 36s	remaining: 8m 32s
5534:	learn: 0.0020680	total: 9m 36s	remaining: 7m 44s
5707:	learn: 0.0016621	total: 9m 36s	remaining: 7m 13s
5711:	learn: 0.0017181	total: 9m 36s	remaining: 7m 12s
5815:	learn: 0.0016813	total: 9m 36s	remaining: 6m 54s
5292:	learn: 0.0017002	total: 9m 36s	remaining: 8m 32s
5535:	learn: 0.0020680	total: 9m 36s	remaining: 7m 44s
5712:	learn: 0.0017181	total: 9m 36s	remaining: 7m 12s
5708:	learn: 0.0016618	total: 9m 36s	remaining: 7m 13s
5816:	learn: 0.0016813	total: 9m 36s	remaining: 6m 54s
5536:	learn: 0.0020681	total: 9m 36s	remaining: 7m 44s
5293:	learn: 0.0016995	total: 9m 36s	remaining: 8m 32s
5709:	learn: 0.0016612	total: 9m 36s	remaining: 7m 13s
5817:	learn: 0.0016813	total: 9m 36s	remaining: 6m 54s
5713:	learn: 0.0017180	total: 9m 36s	remaining: 7m 12s
5537:	learn: 0.0020681	total: 9m 36s	remaining: 7m 44s
5294:	learn: 0.0016995	total: 9m 36s	remaining: 8m 32s
5818:	learn: 0.0016812	total: 9m 36s	remaining: 6m 54s
5710:	learn: 0.0016607	total: 9m 36s	remaining: 7m 12s
5714:	learn: 0.0017175	total: 9m 36s	remaining: 7m 12s
5538:	learn: 0.0020680	total: 9m 36s	remaining: 7m 44s
5295:	learn: 0.0016991	total: 9m 36s	remaining: 8m 32s
5819:	learn: 0.0016810	total: 9m 36s	remaining: 6m 54s
5711:	learn: 0.0016603	total: 9m 36s	remaining: 7m 12s
5715:	learn: 0.0017175	total: 9m 36s	remaining: 7m 12s
5539:	learn: 0.0020680	total: 9m 36s	remaining: 7m 44s
5296:	learn: 0.0016985	total: 9m 36s	remaining: 8m 32s
5712:	learn: 0.0016598	total: 9m 36s	remaining: 7m 12s
5820:	learn: 0.0016804	total: 9m 36s	remaining: 6m 54s
5716:	learn: 0.0017171	total: 9m 36s	remaining: 7m 12s
5540:	learn: 0.0020681	total: 9m 36s	remaining: 7m 44s
5713:	learn: 0.0016598	total: 9m 36s	remaining: 7m 12s
5297:	learn: 0.0016985	total: 9m 36s	remaining: 8m 32s
5717:	learn: 0.0017171	total: 9m 36s	remaining: 7m 12s
5821:	learn: 0.0016804	total: 9m 36s	remaining: 6m 54s
5541:	learn: 0.0020675	total: 9m 36s	remaining: 7m 44s
5714:	learn: 0.0016594	total: 9m 36s	remaining: 7m 12s
5718:	learn: 0.0017171	total: 9m 37s	remaining: 7m 11s
5298:	learn: 0.0016985	total: 9m 37s	remaining: 8m 31s
5822:	learn: 0.0016799	total: 9m 37s	remaining: 6m 53s
5715:	learn: 0.0016590	total: 9m 36s	remaining: 7m 12s
5542:	learn: 0.0020675	total: 9m 37s	remaining: 7m 44s
5719:	learn: 0.0017170	total: 9m 37s	remaining: 7m 11s
5299:	learn: 0.0016981	total: 9m 37s	remaining: 8m 31s
5823:	learn: 0.0016794	total: 9m 37s	remaining: 6m 53s
5543:	learn: 0.0020676	total: 9m 37s	remaining: 7m 43s
5716:	learn: 0.0016588	total: 9m 37s	remaining: 7m 12s
5300:	learn: 0.0016981	total: 9m 37s	remaining: 8m 31s
5720:	learn: 0.0017170	total: 9m 37s	remaining: 7m 11s
5824:	learn: 0.0016788	total: 9m 37s	remaining: 6m 53s
5544:	learn: 0.0020675	total: 9m 37s	remaining: 7m 43s
5717:	learn: 0.0016586	total: 9m 37s	remaining: 7m 12s
5721:	learn: 0.0017170	total: 9m 37s	remaining: 7m 11s
5825:	learn: 0.0016788	total: 9m 37s	remaining: 6m 53s
5545:	learn: 0.0020676	total: 9m 37s	remaining: 7m 43s
5301:	learn: 0.0016978	total: 9m 37s	remaining: 8m 31s
5718:	learn: 0.0016586	total: 9m 37s	remaining: 7m 12s
5722:	learn: 0.0017168	total: 9m 37s	remaining: 7m 11s
5826:	learn: 0.0016788	total: 9m 37s	remaining: 6m 53s
5546:	learn: 0.0020676	total: 9m 37s	remaining: 7m 43s
5302:	learn: 0.0016978	total: 9m 37s	remaining: 8m 31s
5719:	learn: 0.0016586	total: 9m 37s	remaining: 7m 12s
5723:	learn: 0.0017164	total: 9m 37s	remaining: 7m 11s
5547:	learn: 0.0020675	total: 9m 37s	remaining: 7m 43s
5827:	learn: 0.0016784	total: 9m 37s	remaining: 6m 53s
5720:	learn: 0.0016586	total: 9m 37s	remaining: 7m 11s
5303:	learn: 0.0016972	total: 9m 37s	remaining: 8m 31s
5724:	learn: 0.0017164	total: 9m 37s	remaining: 7m 11s
5828:	learn: 0.0016778	total: 9m 37s	remaining: 6m 53s
5721:	learn: 0.0016582	total: 9m 37s	remaining: 7m 11s
5548:	learn: 0.0020675	total: 9m 37s	remaining: 7m 43s
5304:	learn: 0.0016969	total: 9m 37s	remaining: 8m 31s
5725:	learn: 0.0017163	total: 9m 37s	remaining: 7m 11s
5722:	learn: 0.0016579	total: 9m 37s	remaining: 7m 11s
5829:	learn: 0.0016778	total: 9m 37s	remaining: 6m 53s
5549:	learn: 0.0020675	total: 9m 37s	remaining: 7m 43s
5305:	learn: 0.0016969	total: 9m 37s	remaining: 8m 31s
5723:	learn: 0.0016579	total: 9m 37s	remaining: 7m 11s
5726:	learn: 0.0017163	total: 9m 37s	remaining: 7m 11s
5830:	learn: 0.0016773	total: 9m 37s	remaining: 6m 53s
5550:	learn: 0.0020675	total: 9m 37s	remaining: 7m 43s
5727:	learn: 0.0017164	total: 9m 37s	remaining: 7m 11s
5724:	learn: 0.0016577	total: 9m 37s	remaining: 7m 11s
5306:	learn: 0.0016962	total: 9m 38s	remaining: 8m 31s
5831:	learn: 0.0016768	total: 9m 37s	remaining: 6m 53s
5551:	learn: 0.0020675	total: 9m 37s	remaining: 7m 43s
5728:	learn: 0.0017158	total: 9m 38s	remaining: 7m 10s
5725:	learn: 0.0016577	total: 9m 37s	remaining: 7m 11s
5307:	learn: 0.0016958	total: 9m 38s	remaining: 8m 31s
5832:	learn: 0.0016768	total: 9m 38s	remaining: 6m 52s
5552:	learn: 0.0020675	total: 9m 38s	remaining: 7m 42s
5729:	learn: 0.0017151	total: 9m 38s	remaining: 7m 10s
5726:	learn: 0.0016577	total: 9m 38s	remaining: 7m 11s
5308:	learn: 0.0016958	total: 9m 38s	remaining: 8m 30s
5833:	learn: 0.0016766	total: 9m 38s	remaining: 6m 52s
5553:	learn: 0.0020675	total: 9m 38s	remaining: 7m 42s
5730:	learn: 0.0017151	total: 9m 38s	remaining: 7m 10s
5727:	learn: 0.0016577	total: 9m 38s	remaining: 7m 11s
5309:	learn: 0.0016958	total: 9m 38s	remaining: 8m 30s
5834:	learn: 0.0016766	total: 9m 38s	remaining: 6m 52s
5728:	learn: 0.0016571	total: 9m 38s	remaining: 7m 11s
5731:	learn: 0.0017148	total: 9m 38s	remaining: 7m 10s
5554:	learn: 0.0020675	total: 9m 38s	remaining: 7m 42s
5835:	learn: 0.0016766	total: 9m 38s	remaining: 6m 52s
5310:	learn: 0.0016958	total: 9m 38s	remaining: 8m 30s
5729:	learn: 0.0016569	total: 9m 38s	remaining: 7m 10s
5555:	learn: 0.0020675	total: 9m 38s	remaining: 7m 42s
5732:	learn: 0.0017141	total: 9m 38s	remaining: 7m 10s
5311:	learn: 0.0016958	total: 9m 38s	remaining: 8m 30s
5836:	learn: 0.0016762	total: 9m 38s	remaining: 6m 52s
5730:	learn: 0.0016569	total: 9m 38s	remaining: 7m 10s
5556:	learn: 0.0020675	total: 9m 38s	remaining: 7m 42s
5312:	learn: 0.0016958	total: 9m 38s	remaining: 8m 30s
5733:	learn: 0.0017135	total: 9m 38s	remaining: 7m 10s
5837:	learn: 0.0016757	total: 9m 38s	remaining: 6m 52s
5731:	learn: 0.0016563	total: 9m 38s	remaining: 7m 10s
5557:	learn: 0.0020675	total: 9m 38s	remaining: 7m 42s
5313:	learn: 0.0016954	total: 9m 38s	remaining: 8m 30s
5734:	learn: 0.0017135	total: 9m 38s	remaining: 7m 10s
5838:	learn: 0.0016757	total: 9m 38s	remaining: 6m 52s
5732:	learn: 0.0016562	total: 9m 38s	remaining: 7m 10s
5558:	learn: 0.0020676	total: 9m 38s	remaining: 7m 42s
5735:	learn: 0.0017127	total: 9m 38s	remaining: 7m 10s
5314:	learn: 0.0016951	total: 9m 38s	remaining: 8m 30s
5733:	learn: 0.0016562	total: 9m 38s	remaining: 7m 10s
5839:	learn: 0.0016757	total: 9m 38s	remaining: 6m 52s
5559:	learn: 0.0020676	total: 9m 38s	remaining: 7m 42s
5736:	learn: 0.0017127	total: 9m 38s	remaining: 7m 10s
5734:	learn: 0.0016556	total: 9m 38s	remaining: 7m 10s
5315:	learn: 0.0016946	total: 9m 38s	remaining: 8m 30s
5840:	learn: 0.0016757	total: 9m 38s	remaining: 6m 52s
5737:	learn: 0.0017122	total: 9m 38s	remaining: 7m 10s
5560:	learn: 0.0020676	total: 9m 38s	remaining: 7m 42s
5735:	learn: 0.0016552	total: 9m 38s	remaining: 7m 10s
5738:	learn: 0.0017122	total: 9m 39s	remaining: 7m 9s
5841:	learn: 0.0016757	total: 9m 38s	remaining: 6m 52s
5316:	learn: 0.0016941	total: 9m 39s	remaining: 8m 30s
5561:	learn: 0.0020676	total: 9m 39s	remaining: 7m 42s
5739:	learn: 0.0017122	total: 9m 39s	remaining: 7m 9s
5736:	learn: 0.0016548	total: 9m 38s	remaining: 7m 10s
5842:	learn: 0.0016757	total: 9m 39s	remaining: 6m 51s
5317:	learn: 0.0016936	total: 9m 39s	remaining: 8m 29s
5562:	learn: 0.0020675	total: 9m 39s	remaining: 7m 41s
5737:	learn: 0.0016544	total: 9m 39s	remaining: 7m 10s
5843:	learn: 0.0016757	total: 9m 39s	remaining: 6m 51s
5740:	learn: 0.0017119	total: 9m 39s	remaining: 7m 9s
5563:	learn: 0.0020675	total: 9m 39s	remaining: 7m 41s
5318:	learn: 0.0016930	total: 9m 39s	remaining: 8m 29s
5738:	learn: 0.0016540	total: 9m 39s	remaining: 7m 9s
5844:	learn: 0.0016752	total: 9m 39s	remaining: 6m 51s
5741:	learn: 0.0017119	total: 9m 39s	remaining: 7m 9s
5564:	learn: 0.0020675	total: 9m 39s	remaining: 7m 41s
5739:	learn: 0.0016535	total: 9m 39s	remaining: 7m 9s
5319:	learn: 0.0016930	total: 9m 39s	remaining: 8m 29s
5845:	learn: 0.0016751	total: 9m 39s	remaining: 6m 51s
5742:	learn: 0.0017119	total: 9m 39s	remaining: 7m 9s
5740:	learn: 0.0016535	total: 9m 39s	remaining: 7m 9s
5565:	learn: 0.0020675	total: 9m 39s	remaining: 7m 41s
5743:	learn: 0.0017111	total: 9m 39s	remaining: 7m 9s
5320:	learn: 0.0016930	total: 9m 39s	remaining: 8m 29s
5566:	learn: 0.0020675	total: 9m 39s	remaining: 7m 41s
5846:	learn: 0.0016751	total: 9m 39s	remaining: 6m 51s
5741:	learn: 0.0016531	total: 9m 39s	remaining: 7m 9s
5744:	learn: 0.0017111	total: 9m 39s	remaining: 7m 9s
5567:	learn: 0.0020675	total: 9m 39s	remaining: 7m 41s
5321:	learn: 0.0016923	total: 9m 39s	remaining: 8m 29s
5847:	learn: 0.0016751	total: 9m 39s	remaining: 6m 51s
5742:	learn: 0.0016531	total: 9m 39s	remaining: 7m 9s
5322:	learn: 0.0016918	total: 9m 39s	remaining: 8m 29s
5745:	learn: 0.0017111	total: 9m 39s	remaining: 7m 9s
5568:	learn: 0.0020675	total: 9m 39s	remaining: 7m 41s
5848:	learn: 0.0016751	total: 9m 39s	remaining: 6m 51s
5743:	learn: 0.0016531	total: 9m 39s	remaining: 7m 9s
5323:	learn: 0.0016914	total: 9m 39s	remaining: 8m 29s
5746:	learn: 0.0017111	total: 9m 39s	remaining: 7m 9s
5569:	learn: 0.0020675	total: 9m 39s	remaining: 7m 41s
5744:	learn: 0.0016524	total: 9m 39s	remaining: 7m 9s
5747:	learn: 0.0017105	total: 9m 39s	remaining: 7m 8s
5849:	learn: 0.0016751	total: 9m 39s	remaining: 6m 51s
5324:	learn: 0.0016914	total: 9m 39s	remaining: 8m 29s
5745:	learn: 0.0016524	total: 9m 39s	remaining: 7m 9s
5570:	learn: 0.0020675	total: 9m 39s	remaining: 7m 41s
5748:	learn: 0.0017105	total: 9m 39s	remaining: 7m 8s
5850:	learn: 0.0016751	total: 9m 39s	remaining: 6m 51s
5746:	learn: 0.0016519	total: 9m 39s	remaining: 7m 9s
5325:	learn: 0.0016910	total: 9m 40s	remaining: 8m 29s
5749:	learn: 0.0017105	total: 9m 40s	remaining: 7m 8s
5571:	learn: 0.0020666	total: 9m 40s	remaining: 7m 40s
5851:	learn: 0.0016751	total: 9m 40s	remaining: 6m 51s
5747:	learn: 0.0016514	total: 9m 39s	remaining: 7m 9s
5326:	learn: 0.0016910	total: 9m 40s	remaining: 8m 28s
5750:	learn: 0.0017105	total: 9m 40s	remaining: 7m 8s
5572:	learn: 0.0020666	total: 9m 40s	remaining: 7m 40s
5852:	learn: 0.0016746	total: 9m 40s	remaining: 6m 51s
5748:	learn: 0.0016510	total: 9m 40s	remaining: 7m 8s
5327:	learn: 0.0016905	total: 9m 40s	remaining: 8m 28s
5853:	learn: 0.0016740	total: 9m 40s	remaining: 6m 50s
5751:	learn: 0.0017105	total: 9m 40s	remaining: 7m 8s
5573:	learn: 0.0020666	total: 9m 40s	remaining: 7m 40s
5749:	learn: 0.0016505	total: 9m 40s	remaining: 7m 8s
5328:	learn: 0.0016899	total: 9m 40s	remaining: 8m 28s
5854:	learn: 0.0016733	total: 9m 40s	remaining: 6m 50s
5752:	learn: 0.0017102	total: 9m 40s	remaining: 7m 8s
5574:	learn: 0.0020666	total: 9m 40s	remaining: 7m 40s
5750:	learn: 0.0016505	total: 9m 40s	remaining: 7m 8s
5329:	learn: 0.0016893	total: 9m 40s	remaining: 8m 28s
5753:	learn: 0.0017101	total: 9m 40s	remaining: 7m 8s
5855:	learn: 0.0016731	total: 9m 40s	remaining: 6m 50s
5575:	learn: 0.0020666	total: 9m 40s	remaining: 7m 40s
5751:	learn: 0.0016505	total: 9m 40s	remaining: 7m 8s
5330:	learn: 0.0016888	total: 9m 40s	remaining: 8m 28s
5754:	learn: 0.0017101	total: 9m 40s	remaining: 7m 8s
5752:	learn: 0.0016505	total: 9m 40s	remaining: 7m 8s
5856:	learn: 0.0016729	total: 9m 40s	remaining: 6m 50s
5576:	learn: 0.0020666	total: 9m 40s	remaining: 7m 40s
5755:	learn: 0.0017095	total: 9m 40s	remaining: 7m 8s
5331:	learn: 0.0016880	total: 9m 40s	remaining: 8m 28s
5753:	learn: 0.0016501	total: 9m 40s	remaining: 7m 8s
5756:	learn: 0.0017095	total: 9m 40s	remaining: 7m 7s
5577:	learn: 0.0020666	total: 9m 40s	remaining: 7m 40s
5857:	learn: 0.0016724	total: 9m 40s	remaining: 6m 50s
5754:	learn: 0.0016497	total: 9m 40s	remaining: 7m 8s
5332:	learn: 0.0016876	total: 9m 40s	remaining: 8m 28s
5757:	learn: 0.0017091	total: 9m 40s	remaining: 7m 7s
5578:	learn: 0.0020666	total: 9m 40s	remaining: 7m 40s
5858:	learn: 0.0016719	total: 9m 40s	remaining: 6m 50s
5758:	learn: 0.0017091	total: 9m 40s	remaining: 7m 7s
5755:	learn: 0.0016494	total: 9m 40s	remaining: 7m 8s
5333:	learn: 0.0016870	total: 9m 40s	remaining: 8m 28s
5579:	learn: 0.0020666	total: 9m 40s	remaining: 7m 40s
5759:	learn: 0.0017091	total: 9m 40s	remaining: 7m 7s
5756:	learn: 0.0016493	total: 9m 40s	remaining: 7m 8s
5859:	learn: 0.0016713	total: 9m 40s	remaining: 6m 50s
5334:	learn: 0.0016864	total: 9m 41s	remaining: 8m 28s
5580:	learn: 0.0020666	total: 9m 40s	remaining: 7m 40s
5760:	learn: 0.0017090	total: 9m 41s	remaining: 7m 7s
5860:	learn: 0.0016711	total: 9m 41s	remaining: 6m 50s
5757:	learn: 0.0016489	total: 9m 40s	remaining: 7m 7s
5335:	learn: 0.0016864	total: 9m 41s	remaining: 8m 27s
5581:	learn: 0.0020666	total: 9m 41s	remaining: 7m 39s
5761:	learn: 0.0017090	total: 9m 41s	remaining: 7m 7s
5861:	learn: 0.0016707	total: 9m 41s	remaining: 6m 50s
5758:	learn: 0.0016484	total: 9m 41s	remaining: 7m 7s
5582:	learn: 0.0020666	total: 9m 41s	remaining: 7m 39s
5762:	learn: 0.0017089	total: 9m 41s	remaining: 7m 7s
5336:	learn: 0.0016859	total: 9m 41s	remaining: 8m 27s
5862:	learn: 0.0016707	total: 9m 41s	remaining: 6m 50s
5583:	learn: 0.0020666	total: 9m 41s	remaining: 7m 39s
5759:	learn: 0.0016484	total: 9m 41s	remaining: 7m 7s
5863:	learn: 0.0016702	total: 9m 41s	remaining: 6m 49s
5763:	learn: 0.0017089	total: 9m 41s	remaining: 7m 7s
5337:	learn: 0.0016859	total: 9m 41s	remaining: 8m 27s
5864:	learn: 0.0016702	total: 9m 41s	remaining: 6m 49s
5760:	learn: 0.0016479	total: 9m 41s	remaining: 7m 7s
5584:	learn: 0.0020659	total: 9m 41s	remaining: 7m 39s
5764:	learn: 0.0017089	total: 9m 41s	remaining: 7m 7s
5338:	learn: 0.0016858	total: 9m 41s	remaining: 8m 27s
5761:	learn: 0.0016479	total: 9m 41s	remaining: 7m 7s
5765:	learn: 0.0017089	total: 9m 41s	remaining: 7m 6s
5865:	learn: 0.0016700	total: 9m 41s	remaining: 6m 49s
5585:	learn: 0.0020659	total: 9m 41s	remaining: 7m 39s
5762:	learn: 0.0016476	total: 9m 41s	remaining: 7m 7s
5339:	learn: 0.0016857	total: 9m 41s	remaining: 8m 27s
5766:	learn: 0.0017088	total: 9m 41s	remaining: 7m 6s
5866:	learn: 0.0016694	total: 9m 41s	remaining: 6m 49s
5586:	learn: 0.0020659	total: 9m 41s	remaining: 7m 39s
5763:	learn: 0.0016472	total: 9m 41s	remaining: 7m 7s
5340:	learn: 0.0016857	total: 9m 41s	remaining: 8m 27s
5867:	learn: 0.0016692	total: 9m 41s	remaining: 6m 49s
5767:	learn: 0.0017088	total: 9m 41s	remaining: 7m 6s
5587:	learn: 0.0020658	total: 9m 41s	remaining: 7m 39s
5868:	learn: 0.0016692	total: 9m 41s	remaining: 6m 49s
5341:	learn: 0.0016853	total: 9m 41s	remaining: 8m 27s
5768:	learn: 0.0017088	total: 9m 41s	remaining: 7m 6s
5764:	learn: 0.0016468	total: 9m 41s	remaining: 7m 7s
5588:	learn: 0.0020658	total: 9m 41s	remaining: 7m 39s
5869:	learn: 0.0016692	total: 9m 41s	remaining: 6m 49s
5342:	learn: 0.0016849	total: 9m 41s	remaining: 8m 27s
5769:	learn: 0.0017086	total: 9m 41s	remaining: 7m 6s
5765:	learn: 0.0016464	total: 9m 41s	remaining: 7m 7s
5589:	learn: 0.0020658	total: 9m 41s	remaining: 7m 39s
5870:	learn: 0.0016685	total: 9m 41s	remaining: 6m 49s
5343:	learn: 0.0016844	total: 9m 41s	remaining: 8m 27s
5770:	learn: 0.0017086	total: 9m 42s	remaining: 7m 6s
5766:	learn: 0.0016464	total: 9m 41s	remaining: 7m 7s

5590:	learn: 0.0020658	total: 9m 42s	remaining: 7m 38s
5344:	learn: 0.0016839	total: 9m 42s	remaining: 8m 26s
5871:	learn: 0.0016680	total: 9m 42s	remaining: 6m 49s
5771:	learn: 0.0017084	total: 9m 42s	remaining: 7m 6s
5591:	learn: 0.0020658	total: 9m 42s	remaining: 7m 38s
5767:	learn: 0.0016464	total: 9m 41s	remaining: 7m 6s
5345:	learn: 0.0016836	total: 9m 42s	remaining: 8m 26s
5872:	learn: 0.0016675	total: 9m 42s	remaining: 6m 49s
5592:	learn: 0.0020658	total: 9m 42s	remaining: 7m 38s
5772:	learn: 0.0017084	total: 9m 42s	remaining: 7m 6s
5346:	learn: 0.0016831	total: 9m 42s	remaining: 8m 26s
5768:	learn: 0.0016460	total: 9m 42s	remaining: 7m 6s
5873:	learn: 0.0016671	total: 9m 42s	remaining: 6m 48s
5773:	learn: 0.0017082	total: 9m 42s	remaining: 7m 6s
5593:	learn: 0.0020658	total: 9m 42s	remaining: 7m 38s
5347:	learn: 0.0016826	total: 9m 42s	remaining: 8m 26s
5769:	learn: 0.0016455	total: 9m 42s	remaining: 7m 6s
5874:	learn: 0.0016665	total: 9m 42s	remaining: 6m 48s
5774:	learn: 0.0017082	total: 9m 42s	remaining: 7m 6s
5594:	learn: 0.0020658	total: 9m 42s	remaining: 7m 38s
5348:	learn: 0.0016820	total: 9m 42s	remaining: 8m 26s
5770:	learn: 0.0016451	total: 9m 42s	remaining: 7m 6s
5875:	learn: 0.0016660	total: 9m 42s	remaining: 6m 48s
5595:	learn: 0.0020658	total: 9m 42s	remaining: 7m 38s
5349:	learn: 0.0016816	total: 9m 42s	remaining: 8m 26s
5775:	learn: 0.0017076	total: 9m 42s	remaining: 7m 6s
5876:	learn: 0.0016660	total: 9m 42s	remaining: 6m 48s
5771:	learn: 0.0016447	total: 9m 42s	remaining: 7m 6s
5596:	learn: 0.0020658	total: 9m 42s	remaining: 7m 38s
5350:	learn: 0.0016810	total: 9m 42s	remaining: 8m 26s
5776:	learn: 0.0017074	total: 9m 42s	remaining: 7m 5s
5877:	learn: 0.0016656	total: 9m 42s	remaining: 6m 48s
5772:	learn: 0.0016446	total: 9m 42s	remaining: 7m 6s
5597:	learn: 0.0020659	total: 9m 42s	remaining: 7m 38s
5351:	learn: 0.0016806	total: 9m 42s	remaining: 8m 26s
5777:	learn: 0.0017069	total: 9m 42s	remaining: 7m 5s
5878:	learn: 0.0016652	total: 9m 42s	remaining: 6m 48s
5773:	learn: 0.0016446	total: 9m 42s	remaining: 7m 6s
5598:	learn: 0.0020659	total: 9m 42s	remaining: 7m 38s
5879:	learn: 0.0016647	total: 9m 42s	remaining: 6m 48s
5774:	learn: 0.0016442	total: 9m 42s	remaining: 7m 6s
5778:	learn: 0.0017063	total: 9m 42s	remaining: 7m 5s
5352:	learn: 0.0016801	total: 9m 42s	remaining: 8m 26s
5880:	learn: 0.0016647	total: 9m 42s	remaining: 6m 48s
5599:	learn: 0.0020658	total: 9m 42s	remaining: 7m 37s
5775:	learn: 0.0016441	total: 9m 42s	remaining: 7m 6s
5779:	learn: 0.0017063	total: 9m 42s	remaining: 7m 5s
5353:	learn: 0.0016796	total: 9m 42s	remaining: 8m 25s
5881:	learn: 0.0016647	total: 9m 42s	remaining: 6m 48s
5600:	learn: 0.0020659	total: 9m 43s	remaining: 7m 37s
5780:	learn: 0.0017056	total: 9m 43s	remaining: 7m 5s
5776:	learn: 0.0016435	total: 9m 42s	remaining: 7m 6s
5354:	learn: 0.0016792	total: 9m 43s	remaining: 8m 25s
5882:	learn: 0.0016647	total: 9m 43s	remaining: 6m 48s
5781:	learn: 0.0017053	total: 9m 43s	remaining: 7m 5s
5601:	learn: 0.0020659	total: 9m 43s	remaining: 7m 37s
5777:	learn: 0.0016435	total: 9m 42s	remaining: 7m 5s
5355:	learn: 0.0016786	total: 9m 43s	remaining: 8m 25s
5883:	learn: 0.0016646	total: 9m 43s	remaining: 6m 47s
5782:	learn: 0.0017053	total: 9m 43s	remaining: 7m 5s
5602:	learn: 0.0020655	total: 9m 43s	remaining: 7m 37s
5778:	learn: 0.0016431	total: 9m 43s	remaining: 7m 5s
5356:	learn: 0.0016786	total: 9m 43s	remaining: 8m 25s
5783:	learn: 0.0017048	total: 9m 43s	remaining: 7m 5s
5884:	learn: 0.0016646	total: 9m 43s	remaining: 6m 47s
5603:	learn: 0.0020647	total: 9m 43s	remaining: 7m 37s
5784:	learn: 0.0017042	total: 9m 43s	remaining: 7m 5s
5779:	learn: 0.0016430	total: 9m 43s	remaining: 7m 5s
5357:	learn: 0.0016781	total: 9m 43s	remaining: 8m 25s
5885:	learn: 0.0016644	total: 9m 43s	remaining: 6m 47s
5604:	learn: 0.0020647	total: 9m 43s	remaining: 7m 37s
5785:	learn: 0.0017036	total: 9m 43s	remaining: 7m 4s
5358:	learn: 0.0016781	total: 9m 43s	remaining: 8m 25s
5780:	learn: 0.0016430	total: 9m 43s	remaining: 7m 5s
5886:	learn: 0.0016644	total: 9m 43s	remaining: 6m 47s
5605:	learn: 0.0020647	total: 9m 43s	remaining: 7m 37s
5786:	learn: 0.0017032	total: 9m 43s	remaining: 7m 4s
5781:	learn: 0.0016425	total: 9m 43s	remaining: 7m 5s
5359:	learn: 0.0016780	total: 9m 43s	remaining: 8m 25s
5887:	learn: 0.0016644	total: 9m 43s	remaining: 6m 47s
5606:	learn: 0.0020647	total: 9m 43s	remaining: 7m 37s
5787:	learn: 0.0017030	total: 9m 43s	remaining: 7m 4s
5888:	learn: 0.0016644	total: 9m 43s	remaining: 6m 47s
5782:	learn: 0.0016425	total: 9m 43s	remaining: 7m 5s
5360:	learn: 0.0016779	total: 9m 43s	remaining: 8m 25s
5607:	learn: 0.0020647	total: 9m 43s	remaining: 7m 37s
5889:	learn: 0.0016644	total: 9m 43s	remaining: 6m 47s
5788:	learn: 0.0017027	total: 9m 43s	remaining: 7m 4s
5783:	learn: 0.0016424	total: 9m 43s	remaining: 7m 5s
5789:	learn: 0.0017027	total: 9m 43s	remaining: 7m 4s
5361:	learn: 0.0016779	total: 9m 43s	remaining: 8m 25s
5890:	learn: 0.0016644	total: 9m 43s	remaining: 6m 47s
5608:	learn: 0.0020647	total: 9m 43s	remaining: 7m 37s
5784:	learn: 0.0016420	total: 9m 43s	remaining: 7m 5s
5891:	learn: 0.0016639	total: 9m 43s	remaining: 6m 47s
5790:	learn: 0.0017027	total: 9m 43s	remaining: 7m 4s
5362:	learn: 0.0016779	total: 9m 43s	remaining: 8m 24s
5609:	learn: 0.0020647	total: 9m 43s	remaining: 7m 36s
5785:	learn: 0.0016416	total: 9m 43s	remaining: 7m 5s
5892:	learn: 0.0016634	total: 9m 43s	remaining: 6m 46s
5791:	learn: 0.0017027	total: 9m 44s	remaining: 7m 4s
5363:	learn: 0.0016775	total: 9m 44s	remaining: 8m 24s
5610:	learn: 0.0020647	total: 9m 44s	remaining: 7m 36s
5786:	learn: 0.0016411	total: 9m 43s	remaining: 7m 5s
5893:	learn: 0.0016632	total: 9m 44s	remaining: 6m 46s
5792:	learn: 0.0017022	total: 9m 44s	remaining: 7m 4s
5364:	learn: 0.0016770	total: 9m 44s	remaining: 8m 24s
5611:	learn: 0.0020647	total: 9m 44s	remaining: 7m 36s
5793:	learn: 0.0017016	total: 9m 44s	remaining: 7m 4s
5787:	learn: 0.0016405	total: 9m 44s	remaining: 7m 5s
5894:	learn: 0.0016629	total: 9m 44s	remaining: 6m 46s
5365:	learn: 0.0016770	total: 9m 44s	remaining: 8m 24s
5794:	learn: 0.0017011	total: 9m 44s	remaining: 7m 3s
5612:	learn: 0.0020647	total: 9m 44s	remaining: 7m 36s
5366:	learn: 0.0016764	total: 9m 44s	remaining: 8m 24s
5788:	learn: 0.0016400	total: 9m 44s	remaining: 7m 4s
5895:	learn: 0.0016626	total: 9m 44s	remaining: 6m 46s
5795:	learn: 0.0017006	total: 9m 44s	remaining: 7m 3s
5613:	learn: 0.0020646	total: 9m 44s	remaining: 7m 36s
5789:	learn: 0.0016396	total: 9m 44s	remaining: 7m 4s
5896:	learn: 0.0016621	total: 9m 44s	remaining: 6m 46s
5796:	learn: 0.0017007	total: 9m 44s	remaining: 7m 3s
5367:	learn: 0.0016764	total: 9m 44s	remaining: 8m 24s
5614:	learn: 0.0020647	total: 9m 44s	remaining: 7m 36s
5897:	learn: 0.0016621	total: 9m 44s	remaining: 6m 46s
5790:	learn: 0.0016396	total: 9m 44s	remaining: 7m 4s
5797:	learn: 0.0017005	total: 9m 44s	remaining: 7m 3s
5368:	learn: 0.0016764	total: 9m 44s	remaining: 8m 24s
5615:	learn: 0.0020647	total: 9m 44s	remaining: 7m 36s
5791:	learn: 0.0016396	total: 9m 44s	remaining: 7m 4s
5898:	learn: 0.0016615	total: 9m 44s	remaining: 6m 46s
5798:	learn: 0.0017005	total: 9m 44s	remaining: 7m 3s
5369:	learn: 0.0016758	total: 9m 44s	remaining: 8m 24s
5792:	learn: 0.0016390	total: 9m 44s	remaining: 7m 4s
5616:	learn: 0.0020647	total: 9m 44s	remaining: 7m 36s
5899:	learn: 0.0016615	total: 9m 44s	remaining: 6m 46s
5799:	learn: 0.0017004	total: 9m 44s	remaining: 7m 3s
5370:	learn: 0.0016758	total: 9m 44s	remaining: 8m 24s
5793:	learn: 0.0016385	total: 9m 44s	remaining: 7m 4s
5617:	learn: 0.0020646	total: 9m 44s	remaining: 7m 36s
5900:	learn: 0.0016607	total: 9m 44s	remaining: 6m 46s
5371:	learn: 0.0016758	total: 9m 44s	remaining: 8m 23s
5800:	learn: 0.0016998	total: 9m 44s	remaining: 7m 3s
5618:	learn: 0.0020647	total: 9m 44s	remaining: 7m 36s
5901:	learn: 0.0016602	total: 9m 44s	remaining: 6m 46s
5794:	learn: 0.0016380	total: 9m 44s	remaining: 7m 4s
5801:	learn: 0.0016998	total: 9m 44s	remaining: 7m 3s
5372:	learn: 0.0016758	total: 9m 45s	remaining: 8m 23s
5619:	learn: 0.0020647	total: 9m 44s	remaining: 7m 35s
5902:	learn: 0.0016598	total: 9m 44s	remaining: 6m 46s
5802:	learn: 0.0016998	total: 9m 45s	remaining: 7m 3s
5620:	learn: 0.0020646	total: 9m 45s	remaining: 7m 35s
5903:	learn: 0.0016592	total: 9m 45s	remaining: 6m 45s
5373:	learn: 0.0016752	total: 9m 45s	remaining: 8m 23s
5803:	learn: 0.0016998	total: 9m 45s	remaining: 7m 2s
5796:	learn: 0.0016379	total: 9m 45s	remaining: 7m 4s
5621:	learn: 0.0020646	total: 9m 45s	remaining: 7m 35s
5804:	learn: 0.0016998	total: 9m 45s	remaining: 7m 2s
5904:	learn: 0.0016586	total: 9m 45s	remaining: 6m 45s
5374:	learn: 0.0016745	total: 9m 45s	remaining: 8m 23s
5797:	learn: 0.0016379	total: 9m 45s	remaining: 7m 4s
5622:	learn: 0.0020646	total: 9m 45s	remaining: 7m 35s
5805:	learn: 0.0016995	total: 9m 45s	remaining: 7m 2s
5375:	learn: 0.0016746	total: 9m 45s	remaining: 8m 23s
5905:	learn: 0.0016586	total: 9m 45s	remaining: 6m 45s
5798:	learn: 0.0016379	total: 9m 45s	remaining: 7m 3s
5623:	learn: 0.0020646	total: 9m 45s	remaining: 7m 35s
5376:	learn: 0.0016745	total: 9m 45s	remaining: 8m 23s
5806:	learn: 0.0016990	total: 9m 45s	remaining: 7m 2s
5906:	learn: 0.0016584	total: 9m 45s	remaining: 6m 45s
5624:	learn: 0.0020646	total: 9m 45s	remaining: 7m 35s
5799:	learn: 0.0016379	total: 9m 45s	remaining: 7m 3s
5377:	learn: 0.0016745	total: 9m 45s	remaining: 8m 23s
5807:	learn: 0.0016990	total: 9m 45s	remaining: 7m 2s
5907:	learn: 0.0016579	total: 9m 45s	remaining: 6m 45s
5625:	learn: 0.0020646	total: 9m 45s	remaining: 7m 35s
5800:	learn: 0.0016373	total: 9m 45s	remaining: 7m 3s
5626:	learn: 0.0020646	total: 9m 45s	remaining: 7m 35s
5808:	learn: 0.0016990	total: 9m 45s	remaining: 7m 2s
5378:	learn: 0.0016740	total: 9m 45s	remaining: 8m 23s
5908:	learn: 0.0016571	total: 9m 45s	remaining: 6m 45s
5801:	learn: 0.0016369	total: 9m 45s	remaining: 7m 3s
5809:	learn: 0.0016987	total: 9m 45s	remaining: 7m 2s
5627:	learn: 0.0020646	total: 9m 45s	remaining: 7m 34s
5379:	learn: 0.0016735	total: 9m 45s	remaining: 8m 23s
5909:	learn: 0.0016566	total: 9m 45s	remaining: 6m 45s
5810:	learn: 0.0016987	total: 9m 45s	remaining: 7m 2s
5802:	learn: 0.0016369	total: 9m 45s	remaining: 7m 3s
5628:	learn: 0.0020646	total: 9m 45s	remaining: 7m 34s
5380:	learn: 0.0016731	total: 9m 45s	remaining: 8m 22s
5910:	learn: 0.0016566	total: 9m 45s	remaining: 6m 45s
5803:	learn: 0.0016365	total: 9m 45s	remaining: 7m 3s
5629:	learn: 0.0020646	total: 9m 45s	remaining: 7m 34s
5811:	learn: 0.0016987	total: 9m 45s	remaining: 7m 2s
5911:	learn: 0.0016561	total: 9m 45s	remaining: 6m 45s
5804:	learn: 0.0016362	total: 9m 45s	remaining: 7m 3s
5381:	learn: 0.0016731	total: 9m 46s	remaining: 8m 22s
5812:	learn: 0.0016987	total: 9m 45s	remaining: 7m 2s
5630:	learn: 0.0020646	total: 9m 46s	remaining: 7m 34s
5912:	learn: 0.0016557	total: 9m 46s	remaining: 6m 45s
5805:	learn: 0.0016362	total: 9m 45s	remaining: 7m 3s
5382:	learn: 0.0016731	total: 9m 46s	remaining: 8m 22s
5813:	learn: 0.0016981	total: 9m 46s	remaining: 7m 1s
5631:	learn: 0.0020646	total: 9m 46s	remaining: 7m 34s
5913:	learn: 0.0016557	total: 9m 46s	remaining: 6m 44s
5806:	learn: 0.0016362	total: 9m 46s	remaining: 7m 3s
5814:	learn: 0.0016981	total: 9m 46s	remaining: 7m 1s
5383:	learn: 0.0016731	total: 9m 46s	remaining: 8m 22s
5632:	learn: 0.0020646	total: 9m 46s	remaining: 7m 34s
5914:	learn: 0.0016557	total: 9m 46s	remaining: 6m 44s
5815:	learn: 0.0016982	total: 9m 46s	remaining: 7m 1s
5807:	learn: 0.0016362	total: 9m 46s	remaining: 7m 3s
5384:	learn: 0.0016731	total: 9m 46s	remaining: 8m 22s
5633:	learn: 0.0020646	total: 9m 46s	remaining: 7m 34s
5915:	learn: 0.0016557	total: 9m 46s	remaining: 6m 44s
5816:	learn: 0.0016976	total: 9m 46s	remaining: 7m 1s
5808:	learn: 0.0016361	total: 9m 46s	remaining: 7m 2s
5634:	learn: 0.0020646	total: 9m 46s	remaining: 7m 34s
5916:	learn: 0.0016556	total: 9m 46s	remaining: 6m 44s
5385:	learn: 0.0016731	total: 9m 46s	remaining: 8m 22s
5817:	learn: 0.0016976	total: 9m 46s	remaining: 7m 1s
5635:	learn: 0.0020646	total: 9m 46s	remaining: 7m 34s
5917:	learn: 0.0016556	total: 9m 46s	remaining: 6m 44s
5809:	learn: 0.0016357	total: 9m 46s	remaining: 7m 2s
5818:	learn: 0.0016974	total: 9m 46s	remaining: 7m 1s
5386:	learn: 0.0016726	total: 9m 46s	remaining: 8m 22s
5636:	learn: 0.0020646	total: 9m 46s	remaining: 7m 33s
5918:	learn: 0.0016553	total: 9m 46s	remaining: 6m 44s
5819:	learn: 0.0016974	total: 9m 46s	remaining: 7m 1s
5810:	learn: 0.0016357	total: 9m 46s	remaining: 7m 2s
5387:	learn: 0.0016726	total: 9m 46s	remaining: 8m 22s
5637:	learn: 0.0020646	total: 9m 46s	remaining: 7m 33s
5919:	learn: 0.0016548	total: 9m 46s	remaining: 6m 44s
5820:	learn: 0.0016969	total: 9m 46s	remaining: 7m 1s
5638:	learn: 0.0020646	total: 9m 46s	remaining: 7m 33s
5811:	learn: 0.0016357	total: 9m 46s	remaining: 7m 2s
5388:	learn: 0.0016723	total: 9m 46s	remaining: 8m 22s
5920:	learn: 0.0016548	total: 9m 46s	remaining: 6m 44s
5821:	learn: 0.0016965	total: 9m 46s	remaining: 7m 1s
5639:	learn: 0.0020646	total: 9m 46s	remaining: 7m 33s
5812:	learn: 0.0016357	total: 9m 46s	remaining: 7m 2s
5822:	learn: 0.0016965	total: 9m 46s	remaining: 7m
5389:	learn: 0.0016717	total: 9m 46s	remaining: 8m 22s
5921:	learn: 0.0016548	total: 9m 46s	remaining: 6m 44s
5640:	learn: 0.0020646	total: 9m 46s	remaining: 7m 33s
5813:	learn: 0.0016355	total: 9m 46s	remaining: 7m 2s
5823:	learn: 0.0016960	total: 9m 46s	remaining: 7m
5641:	learn: 0.0020646	total: 9m 47s	remaining: 7m 33s
5814:	learn: 0.0016349	total: 9m 46s	remaining: 7m 2s
5922:	learn: 0.0016547	total: 9m 47s	remaining: 6m 44s
5390:	learn: 0.0016717	total: 9m 47s	remaining: 8m 21s
5824:	learn: 0.0016960	total: 9m 47s	remaining: 7m
5642:	learn: 0.0020646	total: 9m 47s	remaining: 7m 33s
5923:	learn: 0.0016544	total: 9m 47s	remaining: 6m 43s
5815:	learn: 0.0016349	total: 9m 46s	remaining: 7m 2s
5825:	learn: 0.0016960	total: 9m 47s	remaining: 7m
5391:	learn: 0.0016713	total: 9m 47s	remaining: 8m 21s
5643:	learn: 0.0020639	total: 9m 47s	remaining: 7m 33s
5924:	learn: 0.0016544	total: 9m 47s	remaining: 6m 43s
5826:	learn: 0.0016960	total: 9m 47s	remaining: 7m
5816:	learn: 0.0016345	total: 9m 47s	remaining: 7m 2s
5644:	learn: 0.0020639	total: 9m 47s	remaining: 7m 33s
5925:	learn: 0.0016544	total: 9m 47s	remaining: 6m 43s
5392:	learn: 0.0016708	total: 9m 47s	remaining: 8m 21s
5827:	learn: 0.0016955	total: 9m 47s	remaining: 7m
5817:	learn: 0.0016340	total: 9m 47s	remaining: 7m 2s
5645:	learn: 0.0020639	total: 9m 47s	remaining: 7m 32s
5926:	learn: 0.0016540	total: 9m 47s	remaining: 6m 43s
5393:	learn: 0.0016704	total: 9m 47s	remaining: 8m 21s
5818:	learn: 0.0016336	total: 9m 47s	remaining: 7m 1s
5828:	learn: 0.0016955	total: 9m 47s	remaining: 7m
5646:	learn: 0.0020639	total: 9m 47s	remaining: 7m 32s
5819:	learn: 0.0016332	total: 9m 47s	remaining: 7m 1s
5927:	learn: 0.0016540	total: 9m 47s	remaining: 6m 43s
5829:	learn: 0.0016950	total: 9m 47s	remaining: 7m
5394:	learn: 0.0016704	total: 9m 47s	remaining: 8m 21s
5647:	learn: 0.0020639	total: 9m 47s	remaining: 7m 32s
5820:	learn: 0.0016328	total: 9m 47s	remaining: 7m 1s
5928:	learn: 0.0016540	total: 9m 47s	remaining: 6m 43s
5830:	learn: 0.0016950	total: 9m 47s	remaining: 7m
5395:	learn: 0.0016704	total: 9m 47s	remaining: 8m 21s
5648:	learn: 0.0020638	total: 9m 47s	remaining: 7m 32s
5821:	learn: 0.0016324	total: 9m 47s	remaining: 7m 1s
5929:	learn: 0.0016540	total: 9m 47s	remaining: 6m 43s
5831:	learn: 0.0016950	total: 9m 47s	remaining: 7m
5822:	learn: 0.0016324	total: 9m 47s	remaining: 7m 1s
5649:	learn: 0.0020638	total: 9m 47s	remaining: 7m 32s
5396:	learn: 0.0016701	total: 9m 47s	remaining: 8m 21s
5832:	learn: 0.0016948	total: 9m 47s	remaining: 6m 59s
5930:	learn: 0.0016538	total: 9m 47s	remaining: 6m 43s
5650:	learn: 0.0020638	total: 9m 47s	remaining: 7m 32s
5833:	learn: 0.0016946	total: 9m 47s	remaining: 6m 59s
5823:	learn: 0.0016319	total: 9m 47s	remaining: 7m 1s
5397:	learn: 0.0016699	total: 9m 47s	remaining: 8m 21s
5931:	learn: 0.0016532	total: 9m 47s	remaining: 6m 43s
5834:	learn: 0.0016946	total: 9m 47s	remaining: 6m 59s
5651:	learn: 0.0020638	total: 9m 47s	remaining: 7m 32s
5824:	learn: 0.0016314	total: 9m 47s	remaining: 7m 1s
5398:	learn: 0.0016695	total: 9m 48s	remaining: 8m 21s
.0018502	total: 9m 2s	remaining: 9m 6s
 otal: �

      5932:	learn: 0.0016528	total: 9m 47s	remaining: 6m 43s
5835:	learn: 0.0016946	total: 9m 48s	remaining: 6m 59s
5825:	learn: 0.0016311	total: 9m 47s	remaining: 7m 1s
5652:	learn: 0.0020638	total: 9m 48s	remaining: 7m 32s
5933:	learn: 0.0016528	total: 9m 48s	remaining: 6m 42s
5399:	learn: 0.0016688	total: 9m 48s	remaining: 8m 21s
5836:	learn: 0.0016944	total: 9m 48s	remaining: 6m 59s
5826:	learn: 0.0016306	total: 9m 48s	remaining: 7m 1s
5653:	learn: 0.0020639	total: 9m 48s	remaining: 7m 32s
5934:	learn: 0.0016528	total: 9m 48s	remaining: 6m 42s
5837:	learn: 0.0016944	total: 9m 48s	remaining: 6m 59s
5400:	learn: 0.0016688	total: 9m 48s	remaining: 8m 20s
5654:	learn: 0.0020638	total: 9m 48s	remaining: 7m 32s
5827:	learn: 0.0016306	total: 9m 48s	remaining: 7m 1s
5935:	learn: 0.0016526	total: 9m 48s	remaining: 6m 42s
5838:	learn: 0.0016941	total: 9m 48s	remaining: 6m 59s
5401:	learn: 0.0016688	total: 9m 48s	remaining: 8m 20s
5655:	learn: 0.0020638	total: 9m 48s	remaining: 7m 31s
5936:	learn: 0.0016522	total: 9m 48s	remaining: 6m 42s
5828:	learn: 0.0016306	total: 9m 48s	remaining: 7m
5839:	learn: 0.0016938	total: 9m 48s	remaining: 6m 59s
5840:	learn: 0.0016931	total: 9m 48s	remaining: 6m 59s
5656:	learn: 0.0020638	total: 9m 48s	remaining: 7m 31s
5402:	learn: 0.0016688	total: 9m 48s	remaining: 8m 20s
5829:	learn: 0.0016306	total: 9m 48s	remaining: 7m
5937:	learn: 0.0016516	total: 9m 48s	remaining: 6m 42s
5657:	learn: 0.0020638	total: 9m 48s	remaining: 7m 31s
5841:	learn: 0.0016924	total: 9m 48s	remaining: 6m 58s
5830:	learn: 0.0016301	total: 9m 48s	remaining: 7m
5403:	learn: 0.0016688	total: 9m 48s	remaining: 8m 20s
5938:	learn: 0.0016510	total: 9m 48s	remaining: 6m 42s
5658:	learn: 0.0020638	total: 9m 48s	remaining: 7m 31s
5842:	learn: 0.0016925	total: 9m 48s	remaining: 6m 58s
5831:	learn: 0.0016301	total: 9m 48s	remaining: 7m
5404:	learn: 0.0016688	total: 9m 48s	remaining: 8m 20s
5939:	learn: 0.0016503	total: 9m 48s	remaining: 6m 42s
5843:	learn: 0.0016919	total: 9m 48s	remaining: 6m 58s
5659:	learn: 0.0020638	total: 9m 48s	remaining: 7m 31s
5832:	learn: 0.0016298	total: 9m 48s	remaining: 7m
5405:	learn: 0.0016688	total: 9m 48s	remaining: 8m 20s
5940:	learn: 0.0016503	total: 9m 48s	remaining: 6m 42s
5844:	learn: 0.0016918	total: 9m 48s	remaining: 6m 58s
5833:	learn: 0.0016292	total: 9m 48s	remaining: 7m
5660:	learn: 0.0020638	total: 9m 48s	remaining: 7m 31s
5406:	learn: 0.0016688	total: 9m 48s	remaining: 8m 20s
5845:	learn: 0.0016917	total: 9m 48s	remaining: 6m 58s
5941:	learn: 0.0016502	total: 9m 48s	remaining: 6m 42s
5834:	learn: 0.0016287	total: 9m 48s	remaining: 7m
5661:	learn: 0.0020638	total: 9m 49s	remaining: 7m 31s
5407:	learn: 0.0016683	total: 9m 49s	remaining: 8m 20s
5942:	learn: 0.0016502	total: 9m 49s	remaining: 6m 42s
5846:	learn: 0.0016912	total: 9m 49s	remaining: 6m 58s
5835:	learn: 0.0016287	total: 9m 48s	remaining: 7m
5662:	learn: 0.0020638	total: 9m 49s	remaining: 7m 31s
5847:	learn: 0.0016912	total: 9m 49s	remaining: 6m 58s
5408:	learn: 0.0016683	total: 9m 49s	remaining: 8m 20s
5943:	learn: 0.0016498	total: 9m 49s	remaining: 6m 41s
5836:	learn: 0.0016287	total: 9m 49s	remaining: 7m
5663:	learn: 0.0020638	total: 9m 49s	remaining: 7m 31s
5848:	learn: 0.0016905	total: 9m 49s	remaining: 6m 58s
5409:	learn: 0.0016683	total: 9m 49s	remaining: 8m 19s
5944:	learn: 0.0016498	total: 9m 49s	remaining: 6m 41s
5837:	learn: 0.0016287	total: 9m 49s	remaining: 7m
5664:	learn: 0.0020638	total: 9m 49s	remaining: 7m 30s
5945:	learn: 0.0016498	total: 9m 49s	remaining: 6m 41s
5410:	learn: 0.0016683	total: 9m 49s	remaining: 8m 19s
5849:	learn: 0.0016902	total: 9m 49s	remaining: 6m 58s
5838:	learn: 0.0016287	total: 9m 49s	remaining: 6m 59s
5946:	learn: 0.0016494	total: 9m 49s	remaining: 6m 41s
5665:	learn: 0.0020638	total: 9m 49s	remaining: 7m 30s
5839:	learn: 0.0016287	total: 9m 49s	remaining: 6m 59s
5411:	learn: 0.0016680	total: 9m 49s	remaining: 8m 19s
5850:	learn: 0.0016901	total: 9m 49s	remaining: 6m 58s
5947:	learn: 0.0016494	total: 9m 49s	remaining: 6m 41s
5666:	learn: 0.0020638	total: 9m 49s	remaining: 7m 30s
5948:	learn: 0.0016492	total: 9m 49s	remaining: 6m 41s
5412:	learn: 0.0016680	total: 9m 49s	remaining: 8m 19s
5851:	learn: 0.0016901	total: 9m 49s	remaining: 6m 57s
5840:	learn: 0.0016287	total: 9m 49s	remaining: 6m 59s
5667:	learn: 0.0020638	total: 9m 49s	remaining: 7m 30s
5949:	learn: 0.0016492	total: 9m 49s	remaining: 6m 41s
5852:	learn: 0.0016900	total: 9m 49s	remaining: 6m 57s
5413:	learn: 0.0016680	total: 9m 49s	remaining: 8m 19s
5668:	learn: 0.0020638	total: 9m 49s	remaining: 7m 30s
5841:	learn: 0.0016283	total: 9m 49s	remaining: 6m 59s
5950:	learn: 0.0016488	total: 9m 49s	remaining: 6m 41s
5853:	learn: 0.0016894	total: 9m 49s	remaining: 6m 57s
5669:	learn: 0.0020638	total: 9m 49s	remaining: 7m 30s
5414:	learn: 0.0016680	total: 9m 49s	remaining: 8m 19s
5842:	learn: 0.0016283	total: 9m 49s	remaining: 6m 59s
5951:	learn: 0.0016488	total: 9m 49s	remaining: 6m 41s
5854:	learn: 0.0016887	total: 9m 49s	remaining: 6m 57s
5670:	learn: 0.0020638	total: 9m 49s	remaining: 7m 30s
5843:	learn: 0.0016278	total: 9m 49s	remaining: 6m 59s
5415:	learn: 0.0016676	total: 9m 49s	remaining: 8m 19s
5952:	learn: 0.0016488	total: 9m 49s	remaining: 6m 41s
5855:	learn: 0.0016885	total: 9m 49s	remaining: 6m 57s
5844:	learn: 0.0016278	total: 9m 49s	remaining: 6m 59s
5671:	learn: 0.0020638	total: 9m 50s	remaining: 7m 30s
5953:	learn: 0.0016485	total: 9m 49s	remaining: 6m 40s
5416:	learn: 0.0016671	total: 9m 50s	remaining: 8m 19s
5856:	learn: 0.0016881	total: 9m 50s	remaining: 6m 57s
5672:	learn: 0.0020638	total: 9m 50s	remaining: 7m 30s
5954:	learn: 0.0016480	total: 9m 50s	remaining: 6m 40s
5845:	learn: 0.0016278	total: 9m 49s	remaining: 6m 59s
5417:	learn: 0.0016667	total: 9m 50s	remaining: 8m 19s
5857:	learn: 0.0016880	total: 9m 50s	remaining: 6m 57s
5673:	learn: 0.0020638	total: 9m 50s	remaining: 7m 29s
5955:	learn: 0.0016477	total: 9m 50s	remaining: 6m 40s
5846:	learn: 0.0016273	total: 9m 50s	remaining: 6m 59s
5674:	learn: 0.0020638	total: 9m 50s	remaining: 7m 29s
5956:	learn: 0.0016473	total: 9m 50s	remaining: 6m 40s
5418:	learn: 0.0016667	total: 9m 50s	remaining: 8m 19s
5858:	learn: 0.0016874	total: 9m 50s	remaining: 6m 57s
5675:	learn: 0.0020638	total: 9m 50s	remaining: 7m 29s
5847:	learn: 0.0016273	total: 9m 50s	remaining: 6m 59s
5957:	learn: 0.0016468	total: 9m 50s	remaining: 6m 40s
5419:	learn: 0.0016663	total: 9m 50s	remaining: 8m 18s
5859:	learn: 0.0016874	total: 9m 50s	remaining: 6m 57s
5676:	learn: 0.0020638	total: 9m 50s	remaining: 7m 29s
5848:	learn: 0.0016268	total: 9m 50s	remaining: 6m 58s
5958:	learn: 0.0016463	total: 9m 50s	remaining: 6m 40s
5420:	learn: 0.0016659	total: 9m 50s	remaining: 8m 18s
5677:	learn: 0.0020638	total: 9m 50s	remaining: 7m 29s
5860:	learn: 0.0016874	total: 9m 50s	remaining: 6m 57s
5849:	learn: 0.0016263	total: 9m 50s	remaining: 6m 58s
5959:	learn: 0.0016460	total: 9m 50s	remaining: 6m 40s
5421:	learn: 0.0016659	total: 9m 50s	remaining: 8m 18s
5678:	learn: 0.0020638	total: 9m 50s	remaining: 7m 29s
5861:	learn: 0.0016868	total: 9m 50s	remaining: 6m 56s
5850:	learn: 0.0016263	total: 9m 50s	remaining: 6m 58s
5960:	learn: 0.0016456	total: 9m 50s	remaining: 6m 40s
5862:	learn: 0.0016865	total: 9m 50s	remaining: 6m 56s
5422:	learn: 0.0016659	total: 9m 50s	remaining: 8m 18s
5679:	learn: 0.0020638	total: 9m 50s	remaining: 7m 29s
5851:	learn: 0.0016263	total: 9m 50s	remaining: 6m 58s
5961:	learn: 0.0016452	total: 9m 50s	remaining: 6m 40s
5863:	learn: 0.0016865	total: 9m 50s	remaining: 6m 56s
5423:	learn: 0.0016659	total: 9m 50s	remaining: 8m 18s
5680:	learn: 0.0020638	total: 9m 50s	remaining: 7m 29s
5852:	learn: 0.0016259	total: 9m 50s	remaining: 6m 58s
5424:	learn: 0.0016659	total: 9m 50s	remaining: 8m 18s
5962:	learn: 0.0016452	total: 9m 50s	remaining: 6m 40s
5864:	learn: 0.0016861	total: 9m 50s	remaining: 6m 56s
5681:	learn: 0.0020638	total: 9m 50s	remaining: 7m 29s
5853:	learn: 0.0016259	total: 9m 50s	remaining: 6m 58s
5865:	learn: 0.0016861	total: 9m 50s	remaining: 6m 56s
5425:	learn: 0.0016654	total: 9m 51s	remaining: 8m 18s
5963:	learn: 0.0016452	total: 9m 50s	remaining: 6m 39s
5682:	learn: 0.0020638	total: 9m 51s	remaining: 7m 28s
5854:	learn: 0.0016255	total: 9m 50s	remaining: 6m 58s
5866:	learn: 0.0016861	total: 9m 51s	remaining: 6m 56s
5683:	learn: 0.0020638	total: 9m 51s	remaining: 7m 28s
5426:	learn: 0.0016654	total: 9m 51s	remaining: 8m 18s
5964:	learn: 0.0016446	total: 9m 51s	remaining: 6m 39s
5855:	learn: 0.0016255	total: 9m 50s	remaining: 6m 58s
5867:	learn: 0.0016857	total: 9m 51s	remaining: 6m 56s
5965:	learn: 0.0016444	total: 9m 51s	remaining: 6m 39s
5427:	learn: 0.0016650	total: 9m 51s	remaining: 8m 17s
5684:	learn: 0.0020638	total: 9m 51s	remaining: 7m 28s
5868:	learn: 0.0016857	total: 9m 51s	remaining: 6m 56s
5856:	learn: 0.0016250	total: 9m 51s	remaining: 6m 58s
5966:	learn: 0.0016444	total: 9m 51s	remaining: 6m 39s
5428:	learn: 0.0016645	total: 9m 51s	remaining: 8m 17s
5869:	learn: 0.0016856	total: 9m 51s	remaining: 6m 56s
5685:	learn: 0.0020638	total: 9m 51s	remaining: 7m 28s
5857:	learn: 0.0016246	total: 9m 51s	remaining: 6m 58s
5967:	learn: 0.0016444	total: 9m 51s	remaining: 6m 39s
5429:	learn: 0.0016645	total: 9m 51s	remaining: 8m 17s
5870:	learn: 0.0016856	total: 9m 51s	remaining: 6m 55s
5968:	learn: 0.0016444	total: 9m 51s	remaining: 6m 39s
5686:	learn: 0.0020638	total: 9m 51s	remaining: 7m 28s
5858:	learn: 0.0016241	total: 9m 51s	remaining: 6m 57s
5871:	learn: 0.0016856	total: 9m 51s	remaining: 6m 55s
5430:	learn: 0.0016645	total: 9m 51s	remaining: 8m 17s
5687:	learn: 0.0020638	total: 9m 51s	remaining: 7m 28s
5969:	learn: 0.0016439	total: 9m 51s	remaining: 6m 39s
5859:	learn: 0.0016236	total: 9m 51s	remaining: 6m 57s
5872:	learn: 0.0016856	total: 9m 51s	remaining: 6m 55s
5431:	learn: 0.0016645	total: 9m 51s	remaining: 8m 17s
5688:	learn: 0.0020638	total: 9m 51s	remaining: 7m 28s
5970:	learn: 0.0016436	total: 9m 51s	remaining: 6m 39s
5860:	learn: 0.0016236	total: 9m 51s	remaining: 6m 57s
5432:	learn: 0.0016637	total: 9m 51s	remaining: 8m 17s
5689:	learn: 0.0020638	total: 9m 51s	remaining: 7m 28s
5873:	learn: 0.0016856	total: 9m 51s	remaining: 6m 55s
5971:	learn: 0.0016431	total: 9m 51s	remaining: 6m 39s
5861:	learn: 0.0016233	total: 9m 51s	remaining: 6m 57s
5433:	learn: 0.0016634	total: 9m 51s	remaining: 8m 17s
5874:	learn: 0.0016854	total: 9m 51s	remaining: 6m 55s
5972:	learn: 0.0016427	total: 9m 51s	remaining: 6m 38s
5862:	learn: 0.0016228	total: 9m 51s	remaining: 6m 57s
5690:	learn: 0.0020638	total: 9m 51s	remaining: 7m 28s
5875:	learn: 0.0016849	total: 9m 51s	remaining: 6m 55s
5434:	learn: 0.0016629	total: 9m 51s	remaining: 8m 17s
5973:	learn: 0.0016427	total: 9m 51s	remaining: 6m 38s
5863:	learn: 0.0016222	total: 9m 51s	remaining: 6m 57s
5691:	learn: 0.0020638	total: 9m 51s	remaining: 7m 28s
5876:	learn: 0.0016849	total: 9m 51s	remaining: 6m 55s
5974:	learn: 0.0016424	total: 9m 52s	remaining: 6m 38s
5692:	learn: 0.0020638	total: 9m 52s	remaining: 7m 27s
5435:	learn: 0.0016624	total: 9m 52s	remaining: 8m 17s
5877:	learn: 0.0016848	total: 9m 52s	remaining: 6m 55s
5864:	learn: 0.0016222	total: 9m 51s	remaining: 6m 57s
5693:	learn: 0.0020638	total: 9m 52s	remaining: 7m 27s
5975:	learn: 0.0016423	total: 9m 52s	remaining: 6m 38s
5436:	learn: 0.0016623	total: 9m 52s	remaining: 8m 16s
5865:	learn: 0.0016218	total: 9m 52s	remaining: 6m 57s
5878:	learn: 0.0016841	total: 9m 52s	remaining: 6m 55s
5694:	learn: 0.0020629	total: 9m 52s	remaining: 7m 27s
5976:	learn: 0.0016423	total: 9m 52s	remaining: 6m 38s
5437:	learn: 0.0016620	total: 9m 52s	remaining: 8m 16s
5866:	learn: 0.0016218	total: 9m 52s	remaining: 6m 57s
5879:	learn: 0.0016837	total: 9m 52s	remaining: 6m 55s
5695:	learn: 0.0020623	total: 9m 52s	remaining: 7m 27s
5438:	learn: 0.0016614	total: 9m 52s	remaining: 8m 16s
5977:	learn: 0.0016423	total: 9m 52s	remaining: 6m 38s
5867:	learn: 0.0016214	total: 9m 52s	remaining: 6m 57s
5880:	learn: 0.0016831	total: 9m 52s	remaining: 6m 54s
5696:	learn: 0.0020623	total: 9m 52s	remaining: 7m 27s
5978:	learn: 0.0016423	total: 9m 52s	remaining: 6m 38s
5881:	learn: 0.0016826	total: 9m 52s	remaining: 6m 54s
5697:	learn: 0.0020623	total: 9m 52s	remaining: 7m 27s
5439:	learn: 0.0016607	total: 9m 52s	remaining: 8m 16s
5868:	learn: 0.0016210	total: 9m 52s	remaining: 6m 56s
5882:	learn: 0.0016826	total: 9m 52s	remaining: 6m 54s
5979:	learn: 0.0016420	total: 9m 52s	remaining: 6m 38s
5698:	learn: 0.0020623	total: 9m 52s	remaining: 7m 27s
5440:	learn: 0.0016601	total: 9m 52s	remaining: 8m 16s
5869:	learn: 0.0016205	total: 9m 52s	remaining: 6m 56s
5699:	learn: 0.0020623	total: 9m 52s	remaining: 7m 27s
5883:	learn: 0.0016826	total: 9m 52s	remaining: 6m 54s
5980:	learn: 0.0016414	total: 9m 52s	remaining: 6m 38s
5870:	learn: 0.0016205	total: 9m 52s	remaining: 6m 56s
5441:	learn: 0.0016601	total: 9m 52s	remaining: 8m 16s
5700:	learn: 0.0020623	total: 9m 52s	remaining: 7m 26s
5871:	learn: 0.0016205	total: 9m 52s	remaining: 6m 56s
5981:	learn: 0.0016409	total: 9m 52s	remaining: 6m 38s
5884:	learn: 0.0016826	total: 9m 52s	remaining: 6m 54s
5442:	learn: 0.0016596	total: 9m 52s	remaining: 8m 16s
5872:	learn: 0.0016198	total: 9m 52s	remaining: 6m 56s
5982:	learn: 0.0016409	total: 9m 52s	remaining: 6m 38s
5701:	learn: 0.0020623	total: 9m 52s	remaining: 7m 26s
5885:	learn: 0.0016826	total: 9m 52s	remaining: 6m 54s
5702:	learn: 0.0020623	total: 9m 52s	remaining: 7m 26s
5443:	learn: 0.0016592	total: 9m 52s	remaining: 8m 16s
5873:	learn: 0.0016194	total: 9m 52s	remaining: 6m 56s
5983:	learn: 0.0016405	total: 9m 52s	remaining: 6m 37s
5886:	learn: 0.0016826	total: 9m 52s	remaining: 6m 54s
5703:	learn: 0.0020623	total: 9m 53s	remaining: 7m 26s
5874:	learn: 0.0016189	total: 9m 52s	remaining: 6m 56s
5444:	learn: 0.0016592	total: 9m 53s	remaining: 8m 16s
5984:	learn: 0.0016400	total: 9m 53s	remaining: 6m 37s
5887:	learn: 0.0016826	total: 9m 53s	remaining: 6m 54s
5704:	learn: 0.0020623	total: 9m 53s	remaining: 7m 26s
5875:	learn: 0.0016185	total: 9m 52s	remaining: 6m 56s
5445:	learn: 0.0016587	total: 9m 53s	remaining: 8m 16s
5876:	learn: 0.0016186	total: 9m 53s	remaining: 6m 56s
5985:	learn: 0.0016400	total: 9m 53s	remaining: 6m 37s
5705:	learn: 0.0020623	total: 9m 53s	remaining: 7m 26s
5888:	learn: 0.0016819	total: 9m 53s	remaining: 6m 54s
5877:	learn: 0.0016185	total: 9m 53s	remaining: 6m 55s
5446:	learn: 0.0016583	total: 9m 53s	remaining: 8m 15s
5986:	learn: 0.0016398	total: 9m 53s	remaining: 6m 37s
5889:	learn: 0.0016819	total: 9m 53s	remaining: 6m 54s
5706:	learn: 0.0020623	total: 9m 53s	remaining: 7m 26s
5878:	learn: 0.0016185	total: 9m 53s	remaining: 6m 55s
5447:	learn: 0.0016578	total: 9m 53s	remaining: 8m 15s
5987:	learn: 0.0016394	total: 9m 53s	remaining: 6m 37s
5890:	learn: 0.0016819	total: 9m 53s	remaining: 6m 53s
5707:	learn: 0.0020623	total: 9m 53s	remaining: 7m 26s
5879:	learn: 0.0016179	total: 9m 53s	remaining: 6m 55s
5448:	learn: 0.0016573	total: 9m 53s	remaining: 8m 15s
5988:	learn: 0.0016393	total: 9m 53s	remaining: 6m 37s
5708:	learn: 0.0020623	total: 9m 53s	remaining: 7m 26s
5891:	learn: 0.0016814	total: 9m 53s	remaining: 6m 53s
5880:	learn: 0.0016174	total: 9m 53s	remaining: 6m 55s
5989:	learn: 0.0016391	total: 9m 53s	remaining: 6m 37s
5709:	learn: 0.0020623	total: 9m 53s	remaining: 7m 25s
5449:	learn: 0.0016573	total: 9m 53s	remaining: 8m 15s
5892:	learn: 0.0016807	total: 9m 53s	remaining: 6m 53s
5881:	learn: 0.0016169	total: 9m 53s	remaining: 6m 55s
5710:	learn: 0.0020623	total: 9m 53s	remaining: 7m 25s
5893:	learn: 0.0016807	total: 9m 53s	remaining: 6m 53s
5450:	learn: 0.0016573	total: 9m 53s	remaining: 8m 15s
5990:	learn: 0.0016391	total: 9m 53s	remaining: 6m 37s
5711:	learn: 0.0020623	total: 9m 53s	remaining: 7m 25s
5882:	learn: 0.0016169	total: 9m 53s	remaining: 6m 55s
5894:	learn: 0.0016807	total: 9m 53s	remaining: 6m 53s
5991:	learn: 0.0016388	total: 9m 53s	remaining: 6m 37s
5451:	learn: 0.0016573	total: 9m 53s	remaining: 8m 15s
5895:	learn: 0.0016806	total: 9m 53s	remaining: 6m 53s
5712:	learn: 0.0020623	total: 9m 53s	remaining: 7m 25s
5883:	learn: 0.0016168	total: 9m 53s	remaining: 6m 55s
5992:	learn: 0.0016388	total: 9m 53s	remaining: 6m 37s
5452:	learn: 0.0016573	total: 9m 53s	remaining: 8m 15s
5896:	learn: 0.0016806	total: 9m 53s	remaining: 6m 53s

5713:	learn: 0.0020623	total: 9m 53s	remaining: 7m 25s
5993:	learn: 0.0016388	total: 9m 53s	remaining: 6m 36s
5884:	learn: 0.0016168	total: 9m 53s	remaining: 6m 55s
5453:	learn: 0.0016565	total: 9m 54s	remaining: 8m 15s
5897:	learn: 0.0016806	total: 9m 54s	remaining: 6m 53s
5994:	learn: 0.0016388	total: 9m 54s	remaining: 6m 36s
5714:	learn: 0.0020623	total: 9m 54s	remaining: 7m 25s
5885:	learn: 0.0016168	total: 9m 53s	remaining: 6m 55s
5454:	learn: 0.0016561	total: 9m 54s	remaining: 8m 15s
5898:	learn: 0.0016806	total: 9m 54s	remaining: 6m 53s
5995:	learn: 0.0016388	total: 9m 54s	remaining: 6m 36s
5886:	learn: 0.0016164	total: 9m 54s	remaining: 6m 55s
5455:	learn: 0.0016557	total: 9m 54s	remaining: 8m 14s
5715:	learn: 0.0020623	total: 9m 54s	remaining: 7m 25s
5899:	learn: 0.0016806	total: 9m 54s	remaining: 6m 52s
5887:	learn: 0.0016164	total: 9m 54s	remaining: 6m 54s
5996:	learn: 0.0016383	total: 9m 54s	remaining: 6m 36s
5456:	learn: 0.0016555	total: 9m 54s	remaining: 8m 14s
5716:	learn: 0.0020623	total: 9m 54s	remaining: 7m 25s
5900:	learn: 0.0016806	total: 9m 54s	remaining: 6m 52s
5997:	learn: 0.0016382	total: 9m 54s	remaining: 6m 36s
5457:	learn: 0.0016555	total: 9m 54s	remaining: 8m 14s
5888:	learn: 0.0016160	total: 9m 54s	remaining: 6m 54s
5717:	learn: 0.0020622	total: 9m 54s	remaining: 7m 25s
5901:	learn: 0.0016802	total: 9m 54s	remaining: 6m 52s
5889:	learn: 0.0016160	total: 9m 54s	remaining: 6m 54s
5998:	learn: 0.0016381	total: 9m 54s	remaining: 6m 36s
5458:	learn: 0.0016551	total: 9m 54s	remaining: 8m 14s
5718:	learn: 0.0020622	total: 9m 54s	remaining: 7m 25s
5999:	learn: 0.0016377	total: 9m 54s	remaining: 6m 36s
5890:	learn: 0.0016159	total: 9m 54s	remaining: 6m 54s
5902:	learn: 0.0016802	total: 9m 54s	remaining: 6m 52s
5459:	learn: 0.0016551	total: 9m 54s	remaining: 8m 14s
5719:	learn: 0.0020622	total: 9m 54s	remaining: 7m 24s
5903:	learn: 0.0016802	total: 9m 54s	remaining: 6m 52s
6000:	learn: 0.0016372	total: 9m 54s	remaining: 6m 36s
5460:	learn: 0.0016545	total: 9m 54s	remaining: 8m 14s
5891:	learn: 0.0016153	total: 9m 54s	remaining: 6m 54s
5720:	learn: 0.0020622	total: 9m 54s	remaining: 7m 24s
6001:	learn: 0.0016367	total: 9m 54s	remaining: 6m 36s
5904:	learn: 0.0016802	total: 9m 54s	remaining: 6m 52s
5892:	learn: 0.0016153	total: 9m 54s	remaining: 6m 54s
5461:	learn: 0.0016545	total: 9m 54s	remaining: 8m 14s
5721:	learn: 0.0020622	total: 9m 54s	remaining: 7m 24s
5905:	learn: 0.0016802	total: 9m 54s	remaining: 6m 52s
5893:	learn: 0.0016153	total: 9m 54s	remaining: 6m 54s
6002:	learn: 0.0016359	total: 9m 54s	remaining: 6m 36s
5462:	learn: 0.0016545	total: 9m 54s	remaining: 8m 14s
5722:	learn: 0.0020622	total: 9m 54s	remaining: 7m 24s
5894:	learn: 0.0016147	total: 9m 54s	remaining: 6m 54s
5906:	learn: 0.0016801	total: 9m 54s	remaining: 6m 52s
5463:	learn: 0.0016541	total: 9m 55s	remaining: 8m 13s
6003:	learn: 0.0016353	total: 9m 54s	remaining: 6m 35s
5723:	learn: 0.0020622	total: 9m 55s	remaining: 7m 24s
5907:	learn: 0.0016801	total: 9m 55s	remaining: 6m 52s
5895:	learn: 0.0016147	total: 9m 54s	remaining: 6m 54s
6004:	learn: 0.0016349	total: 9m 55s	remaining: 6m 35s
5464:	learn: 0.0016536	total: 9m 55s	remaining: 8m 13s
5724:	learn: 0.0020622	total: 9m 55s	remaining: 7m 24s
5908:	learn: 0.0016801	total: 9m 55s	remaining: 6m 52s
5896:	learn: 0.0016147	total: 9m 55s	remaining: 6m 54s
6005:	learn: 0.0016345	total: 9m 55s	remaining: 6m 35s
5465:	learn: 0.0016530	total: 9m 55s	remaining: 8m 13s
5725:	learn: 0.0020622	total: 9m 55s	remaining: 7m 24s
5897:	learn: 0.0016147	total: 9m 55s	remaining: 6m 53s
5909:	learn: 0.0016801	total: 9m 55s	remaining: 6m 51s
6006:	learn: 0.0016339	total: 9m 55s	remaining: 6m 35s
5466:	learn: 0.0016530	total: 9m 55s	remaining: 8m 13s
5910:	learn: 0.0016801	total: 9m 55s	remaining: 6m 51s
5898:	learn: 0.0016143	total: 9m 55s	remaining: 6m 53s
5726:	learn: 0.0020622	total: 9m 55s	remaining: 7m 24s
6007:	learn: 0.0016335	total: 9m 55s	remaining: 6m 35s
5467:	learn: 0.0016525	total: 9m 55s	remaining: 8m 13s
5911:	learn: 0.0016801	total: 9m 55s	remaining: 6m 51s
5899:	learn: 0.0016137	total: 9m 55s	remaining: 6m 53s
5727:	learn: 0.0020622	total: 9m 55s	remaining: 7m 24s
6008:	learn: 0.0016335	total: 9m 55s	remaining: 6m 35s
5912:	learn: 0.0016801	total: 9m 55s	remaining: 6m 51s
5900:	learn: 0.0016133	total: 9m 55s	remaining: 6m 53s
5468:	learn: 0.0016525	total: 9m 55s	remaining: 8m 13s
5728:	learn: 0.0020622	total: 9m 55s	remaining: 7m 24s
6009:	learn: 0.0016335	total: 9m 55s	remaining: 6m 35s
5469:	learn: 0.0016520	total: 9m 55s	remaining: 8m 13s
5901:	learn: 0.0016129	total: 9m 55s	remaining: 6m 53s
5913:	learn: 0.0016801	total: 9m 55s	remaining: 6m 51s
5729:	learn: 0.0020622	total: 9m 55s	remaining: 7m 23s
6010:	learn: 0.0016330	total: 9m 55s	remaining: 6m 35s
5902:	learn: 0.0016126	total: 9m 55s	remaining: 6m 53s
5470:	learn: 0.0016520	total: 9m 55s	remaining: 8m 13s
5914:	learn: 0.0016801	total: 9m 55s	remaining: 6m 51s
5730:	learn: 0.0020622	total: 9m 55s	remaining: 7m 23s
6011:	learn: 0.0016330	total: 9m 55s	remaining: 6m 35s
5903:	learn: 0.0016126	total: 9m 55s	remaining: 6m 53s
5471:	learn: 0.0016520	total: 9m 55s	remaining: 8m 13s
5731:	learn: 0.0020622	total: 9m 55s	remaining: 7m 23s
6012:	learn: 0.0016330	total: 9m 55s	remaining: 6m 35s
5915:	learn: 0.0016801	total: 9m 55s	remaining: 6m 51s
5472:	learn: 0.0016520	total: 9m 55s	remaining: 8m 12s
5904:	learn: 0.0016122	total: 9m 55s	remaining: 6m 53s
5732:	learn: 0.0020622	total: 9m 55s	remaining: 7m 23s
5916:	learn: 0.0016799	total: 9m 55s	remaining: 6m 51s
6013:	learn: 0.0016328	total: 9m 55s	remaining: 6m 35s
5473:	learn: 0.0016516	total: 9m 56s	remaining: 8m 12s
5733:	learn: 0.0020621	total: 9m 56s	remaining: 7m 23s
5905:	learn: 0.0016118	total: 9m 55s	remaining: 6m 53s
5917:	learn: 0.0016799	total: 9m 56s	remaining: 6m 51s
5474:	learn: 0.0016511	total: 9m 56s	remaining: 8m 12s
6014:	learn: 0.0016328	total: 9m 56s	remaining: 6m 34s
5906:	learn: 0.0016118	total: 9m 56s	remaining: 6m 52s
5734:	learn: 0.0020622	total: 9m 56s	remaining: 7m 23s
5918:	learn: 0.0016799	total: 9m 56s	remaining: 6m 51s
6015:	learn: 0.0016328	total: 9m 56s	remaining: 6m 34s
5475:	learn: 0.0016511	total: 9m 56s	remaining: 8m 12s
5919:	learn: 0.0016799	total: 9m 56s	remaining: 6m 50s
5735:	learn: 0.0020622	total: 9m 56s	remaining: 7m 23s
5907:	learn: 0.0016114	total: 9m 56s	remaining: 6m 52s
6016:	learn: 0.0016328	total: 9m 56s	remaining: 6m 34s
5476:	learn: 0.0016511	total: 9m 56s	remaining: 8m 12s
5736:	learn: 0.0020622	total: 9m 56s	remaining: 7m 23s
5920:	learn: 0.0016799	total: 9m 56s	remaining: 6m 50s
5908:	learn: 0.0016110	total: 9m 56s	remaining: 6m 52s
5477:	learn: 0.0016507	total: 9m 56s	remaining: 8m 12s
5737:	learn: 0.0020622	total: 9m 56s	remaining: 7m 23s
6017:	learn: 0.0016328	total: 9m 56s	remaining: 6m 34s
5909:	learn: 0.0016110	total: 9m 56s	remaining: 6m 52s
5921:	learn: 0.0016799	total: 9m 56s	remaining: 6m 50s
5910:	learn: 0.0016110	total: 9m 56s	remaining: 6m 52s
6018:	learn: 0.0016323	total: 9m 56s	remaining: 6m 34s
5478:	learn: 0.0016507	total: 9m 56s	remaining: 8m 12s
5738:	learn: 0.0020622	total: 9m 56s	remaining: 7m 22s
5922:	learn: 0.0016799	total: 9m 56s	remaining: 6m 50s
5911:	learn: 0.0016106	total: 9m 56s	remaining: 6m 52s
6019:	learn: 0.0016323	total: 9m 56s	remaining: 6m 34s
5923:	learn: 0.0016799	total: 9m 56s	remaining: 6m 50s
5479:	learn: 0.0016507	total: 9m 56s	remaining: 8m 12s
5739:	learn: 0.0020621	total: 9m 56s	remaining: 7m 22s
5912:	learn: 0.0016101	total: 9m 56s	remaining: 6m 52s
5924:	learn: 0.0016797	total: 9m 56s	remaining: 6m 50s
6020:	learn: 0.0016319	total: 9m 56s	remaining: 6m 34s
5480:	learn: 0.0016503	total: 9m 56s	remaining: 8m 12s
5740:	learn: 0.0020622	total: 9m 56s	remaining: 7m 22s
5925:	learn: 0.0016797	total: 9m 56s	remaining: 6m 50s
5913:	learn: 0.0016101	total: 9m 56s	remaining: 6m 52s
6021:	learn: 0.0016313	total: 9m 56s	remaining: 6m 34s
5481:	learn: 0.0016498	total: 9m 56s	remaining: 8m 11s
5741:	learn: 0.0020622	total: 9m 56s	remaining: 7m 22s
5926:	learn: 0.0016797	total: 9m 56s	remaining: 6m 50s
5914:	learn: 0.0016101	total: 9m 56s	remaining: 6m 52s
6022:	learn: 0.0016308	total: 9m 56s	remaining: 6m 34s
5482:	learn: 0.0016494	total: 9m 57s	remaining: 8m 11s
5927:	learn: 0.0016798	total: 9m 57s	remaining: 6m 50s
5915:	learn: 0.0016101	total: 9m 56s	remaining: 6m 52s
5742:	learn: 0.0020622	total: 9m 57s	remaining: 7m 22s
6023:	learn: 0.0016308	total: 9m 57s	remaining: 6m 34s
5743:	learn: 0.0020622	total: 9m 57s	remaining: 7m 22s
5916:	learn: 0.0016101	total: 9m 56s	remaining: 6m 51s
5928:	learn: 0.0016797	total: 9m 57s	remaining: 6m 50s
5483:	learn: 0.0016494	total: 9m 57s	remaining: 8m 11s
6024:	learn: 0.0016303	total: 9m 57s	remaining: 6m 33s
5917:	learn: 0.0016101	total: 9m 57s	remaining: 6m 51s
5744:	learn: 0.0020621	total: 9m 57s	remaining: 7m 22s
5484:	learn: 0.0016494	total: 9m 57s	remaining: 8m 11s
5929:	learn: 0.0016797	total: 9m 57s	remaining: 6m 49s
6025:	learn: 0.0016303	total: 9m 57s	remaining: 6m 33s
5918:	learn: 0.0016098	total: 9m 57s	remaining: 6m 51s
6026:	learn: 0.0016303	total: 9m 57s	remaining: 6m 33s
5745:	learn: 0.0020621	total: 9m 57s	remaining: 7m 22s
5930:	learn: 0.0016797	total: 9m 57s	remaining: 6m 49s
5485:	learn: 0.0016490	total: 9m 57s	remaining: 8m 11s
5919:	learn: 0.0016098	total: 9m 57s	remaining: 6m 51s
5931:	learn: 0.0016797	total: 9m 57s	remaining: 6m 49s
5746:	learn: 0.0020612	total: 9m 57s	remaining: 7m 22s
6027:	learn: 0.0016303	total: 9m 57s	remaining: 6m 33s
5486:	learn: 0.0016484	total: 9m 57s	remaining: 8m 11s
5932:	learn: 0.0016797	total: 9m 57s	remaining: 6m 49s
5920:	learn: 0.0016092	total: 9m 57s	remaining: 6m 51s
5747:	learn: 0.0020612	total: 9m 57s	remaining: 7m 22s
6028:	learn: 0.0016299	total: 9m 57s	remaining: 6m 33s
5487:	learn: 0.0016480	total: 9m 57s	remaining: 8m 11s
5933:	learn: 0.0016797	total: 9m 57s	remaining: 6m 49s
5921:	learn: 0.0016092	total: 9m 57s	remaining: 6m 51s
5748:	learn: 0.0020612	total: 9m 57s	remaining: 7m 21s
5488:	learn: 0.0016476	total: 9m 57s	remaining: 8m 11s
6029:	learn: 0.0016292	total: 9m 57s	remaining: 6m 33s
5934:	learn: 0.0016797	total: 9m 57s	remaining: 6m 49s
5922:	learn: 0.0016088	total: 9m 57s	remaining: 6m 51s
5749:	learn: 0.0020612	total: 9m 57s	remaining: 7m 21s
5489:	learn: 0.0016471	total: 9m 57s	remaining: 8m 11s
6030:	learn: 0.0016292	total: 9m 57s	remaining: 6m 33s
5935:	learn: 0.0016797	total: 9m 57s	remaining: 6m 49s
5923:	learn: 0.0016085	total: 9m 57s	remaining: 6m 51s
6031:	learn: 0.0016291	total: 9m 57s	remaining: 6m 33s
5750:	learn: 0.0020612	total: 9m 57s	remaining: 7m 21s
5936:	learn: 0.0016797	total: 9m 57s	remaining: 6m 49s
5490:	learn: 0.0016467	total: 9m 57s	remaining: 8m 10s
5924:	learn: 0.0016082	total: 9m 57s	remaining: 6m 51s
6032:	learn: 0.0016291	total: 9m 57s	remaining: 6m 33s
5751:	learn: 0.0020612	total: 9m 57s	remaining: 7m 21s
5937:	learn: 0.0016797	total: 9m 57s	remaining: 6m 49s
5925:	learn: 0.0016078	total: 9m 57s	remaining: 6m 51s
5491:	learn: 0.0016462	total: 9m 58s	remaining: 8m 10s
6033:	learn: 0.0016287	total: 9m 57s	remaining: 6m 33s
5938:	learn: 0.0016797	total: 9m 58s	remaining: 6m 48s
5926:	learn: 0.0016078	total: 9m 57s	remaining: 6m 50s
5492:	learn: 0.0016462	total: 9m 58s	remaining: 8m 10s
5752:	learn: 0.0020612	total: 9m 58s	remaining: 7m 21s
5939:	learn: 0.0016797	total: 9m 58s	remaining: 6m 48s
6034:	learn: 0.0016283	total: 9m 58s	remaining: 6m 32s
5927:	learn: 0.0016078	total: 9m 58s	remaining: 6m 50s
5753:	learn: 0.0020612	total: 9m 58s	remaining: 7m 21s
5493:	learn: 0.0016462	total: 9m 58s	remaining: 8m 10s
6035:	learn: 0.0016283	total: 9m 58s	remaining: 6m 32s
5940:	learn: 0.0016797	total: 9m 58s	remaining: 6m 48s
5754:	learn: 0.0020611	total: 9m 58s	remaining: 7m 21s
5928:	learn: 0.0016074	total: 9m 58s	remaining: 6m 50s
6036:	learn: 0.0016279	total: 9m 58s	remaining: 6m 32s
5494:	learn: 0.0016462	total: 9m 58s	remaining: 8m 10s
5941:	learn: 0.0016797	total: 9m 58s	remaining: 6m 48s
5755:	learn: 0.0020611	total: 9m 58s	remaining: 7m 21s
5929:	learn: 0.0016073	total: 9m 58s	remaining: 6m 50s
6037:	learn: 0.0016279	total: 9m 58s	remaining: 6m 32s
5942:	learn: 0.0016797	total: 9m 58s	remaining: 6m 48s
5495:	learn: 0.0016458	total: 9m 58s	remaining: 8m 10s
5930:	learn: 0.0016068	total: 9m 58s	remaining: 6m 50s
5756:	learn: 0.0020611	total: 9m 58s	remaining: 7m 21s
5943:	learn: 0.0016797	total: 9m 58s	remaining: 6m 48s
5931:	learn: 0.0016068	total: 9m 58s	remaining: 6m 50s
5496:	learn: 0.0016453	total: 9m 58s	remaining: 8m 10s
6038:	learn: 0.0016279	total: 9m 58s	remaining: 6m 32s
5757:	learn: 0.0020611	total: 9m 58s	remaining: 7m 20s
5944:	learn: 0.0016797	total: 9m 58s	remaining: 6m 48s
5932:	learn: 0.0016068	total: 9m 58s	remaining: 6m 50s
6039:	learn: 0.0016279	total: 9m 58s	remaining: 6m 32s
5497:	learn: 0.0016448	total: 9m 58s	remaining: 8m 10s
5758:	learn: 0.0020611	total: 9m 58s	remaining: 7m 20s
5933:	learn: 0.0016068	total: 9m 58s	remaining: 6m 50s
5945:	learn: 0.0016797	total: 9m 58s	remaining: 6m 48s
6040:	learn: 0.0016279	total: 9m 58s	remaining: 6m 32s
5498:	learn: 0.0016445	total: 9m 58s	remaining: 8m 10s
5759:	learn: 0.0020611	total: 9m 58s	remaining: 7m 20s
5934:	learn: 0.0016067	total: 9m 58s	remaining: 6m 50s
5946:	learn: 0.0016797	total: 9m 58s	remaining: 6m 48s
5760:	learn: 0.0020611	total: 9m 58s	remaining: 7m 20s
6041:	learn: 0.0016274	total: 9m 58s	remaining: 6m 32s
5935:	learn: 0.0016066	total: 9m 58s	remaining: 6m 49s
5499:	learn: 0.0016445	total: 9m 58s	remaining: 8m 10s
6042:	learn: 0.0016268	total: 9m 58s	remaining: 6m 32s
5936:	learn: 0.0016061	total: 9m 58s	remaining: 6m 49s
5947:	learn: 0.0016793	total: 9m 58s	remaining: 6m 48s
5761:	learn: 0.0020602	total: 9m 58s	remaining: 7m 20s
5500:	learn: 0.0016440	total: 9m 59s	remaining: 8m 9s
6043:	learn: 0.0016264	total: 9m 59s	remaining: 6m 32s
5501:	learn: 0.0016435	total: 9m 59s	remaining: 8m 9s
5948:	learn: 0.0016793	total: 9m 59s	remaining: 6m 47s
5937:	learn: 0.0016055	total: 9m 58s	remaining: 6m 49s
5762:	learn: 0.0020602	total: 9m 59s	remaining: 7m 20s
6044:	learn: 0.0016264	total: 9m 59s	remaining: 6m 31s
5949:	learn: 0.0016792	total: 9m 59s	remaining: 6m 47s
5502:	learn: 0.0016431	total: 9m 59s	remaining: 8m 9s
5763:	learn: 0.0020602	total: 9m 59s	remaining: 7m 20s
6045:	learn: 0.0016264	total: 9m 59s	remaining: 6m 31s
5938:	learn: 0.0016055	total: 9m 59s	remaining: 6m 49s
5950:	learn: 0.0016787	total: 9m 59s	remaining: 6m 47s
5503:	learn: 0.0016427	total: 9m 59s	remaining: 8m 9s
6046:	learn: 0.0016264	total: 9m 59s	remaining: 6m 31s
5764:	learn: 0.0020602	total: 9m 59s	remaining: 7m 20s
5939:	learn: 0.0016056	total: 9m 59s	remaining: 6m 49s
5951:	learn: 0.0016787	total: 9m 59s	remaining: 6m 47s
5765:	learn: 0.0020593	total: 9m 59s	remaining: 7m 20s
5504:	learn: 0.0016423	total: 9m 59s	remaining: 8m 9s
6047:	learn: 0.0016259	total: 9m 59s	remaining: 6m 31s
5940:	learn: 0.0016050	total: 9m 59s	remaining: 6m 49s
5766:	learn: 0.0020593	total: 9m 59s	remaining: 7m 20s
5952:	learn: 0.0016781	total: 9m 59s	remaining: 6m 47s
5505:	learn: 0.0016420	total: 9m 59s	remaining: 8m 9s
6048:	learn: 0.0016255	total: 9m 59s	remaining: 6m 31s
5941:	learn: 0.0016047	total: 9m 59s	remaining: 6m 49s
5767:	learn: 0.0020593	total: 9m 59s	remaining: 7m 19s
5506:	learn: 0.0016420	total: 9m 59s	remaining: 8m 9s
5953:	learn: 0.0016774	total: 9m 59s	remaining: 6m 47s
6049:	learn: 0.0016250	total: 9m 59s	remaining: 6m 31s
5942:	learn: 0.0016047	total: 9m 59s	remaining: 6m 49s
5768:	learn: 0.0020593	total: 9m 59s	remaining: 7m 19s
5954:	learn: 0.0016769	total: 9m 59s	remaining: 6m 47s
5507:	learn: 0.0016420	total: 9m 59s	remaining: 8m 9s
5943:	learn: 0.0016047	total: 9m 59s	remaining: 6m 49s
6050:	learn: 0.0016247	total: 9m 59s	remaining: 6m 31s
5769:	learn: 0.0020593	total: 9m 59s	remaining: 7m 19s
5508:	learn: 0.0016417	total: 9m 59s	remaining: 8m 8s
5955:	learn: 0.0016769	total: 9m 59s	remaining: 6m 47s
6051:	learn: 0.0016247	total: 9m 59s	remaining: 6m 31s
5944:	learn: 0.0016047	total: 9m 59s	remaining: 6m 49s
5770:	learn: 0.0020593	total: 9m 59s	remaining: 7m 19s
5956:	learn: 0.0016769	total: 9m 59s	remaining: 6m 47s
5945:	learn: 0.0016042	total: 9m 59s	remaining: 6m 48s
5509:	learn: 0.0016412	total: 9m 59s	remaining: 8m 8s
6052:	learn: 0.0016246	total: 9m 59s	remaining: 6m 31s

5771:	learn: 0.0020593	total: 9m 59s	remaining: 7m 19s
5957:	learn: 0.0016762	total: 9m 59s	remaining: 6m 47s
5946:	learn: 0.0016042	total: 9m 59s	remaining: 6m 48s
5510:	learn: 0.0016407	total: 10m	remaining: 8m 8s
6053:	learn: 0.0016246	total: 9m 59s	remaining: 6m 31s
5772:	learn: 0.0020593	total: 10m	remaining: 7m 19s
5958:	learn: 0.0016756	total: 10m	remaining: 6m 46s
5947:	learn: 0.0016035	total: 9m 59s	remaining: 6m 48s
5511:	learn: 0.0016407	total: 10m	remaining: 8m 8s
5773:	learn: 0.0020593	total: 10m	remaining: 7m 19s
6054:	learn: 0.0016243	total: 10m	remaining: 6m 30s
5959:	learn: 0.0016756	total: 10m	remaining: 6m 46s
5512:	learn: 0.0016403	total: 10m	remaining: 8m 8s
5948:	learn: 0.0016035	total: 10m	remaining: 6m 48s
6055:	learn: 0.0016243	total: 10m	remaining: 6m 30s
5774:	learn: 0.0020593	total: 10m	remaining: 7m 19s
5960:	learn: 0.0016756	total: 10m	remaining: 6m 46s
5513:	learn: 0.0016400	total: 10m	remaining: 8m 8s
6056:	learn: 0.0016243	total: 10m	remaining: 6m 30s
5949:	learn: 0.0016035	total: 10m	remaining: 6m 48s
5961:	learn: 0.0016756	total: 10m	remaining: 6m 46s
5775:	learn: 0.0020593	total: 10m	remaining: 7m 19s
5514:	learn: 0.0016396	total: 10m	remaining: 8m 8s
5950:	learn: 0.0016030	total: 10m	remaining: 6m 48s
6057:	learn: 0.0016243	total: 10m	remaining: 6m 30s
5962:	learn: 0.0016756	total: 10m	remaining: 6m 46s
5776:	learn: 0.0020593	total: 10m	remaining: 7m 18s
5951:	learn: 0.0016030	total: 10m	remaining: 6m 48s
5515:	learn: 0.0016391	total: 10m	remaining: 8m 8s
6058:	learn: 0.0016239	total: 10m	remaining: 6m 30s
5963:	learn: 0.0016756	total: 10m	remaining: 6m 46s
5952:	learn: 0.0016030	total: 10m	remaining: 6m 48s
6059:	learn: 0.0016238	total: 10m	remaining: 6m 30s
5777:	learn: 0.0020593	total: 10m	remaining: 7m 18s
5516:	learn: 0.0016388	total: 10m	remaining: 8m 8s
5964:	learn: 0.0016756	total: 10m	remaining: 6m 46s
6060:	learn: 0.0016233	total: 10m	remaining: 6m 30s
5953:	learn: 0.0016026	total: 10m	remaining: 6m 48s
5778:	learn: 0.0020593	total: 10m	remaining: 7m 18s
5517:	learn: 0.0016388	total: 10m	remaining: 8m 7s
6061:	learn: 0.0016228	total: 10m	remaining: 6m 30s
5965:	learn: 0.0016756	total: 10m	remaining: 6m 46s
5954:	learn: 0.0016026	total: 10m	remaining: 6m 47s
5779:	learn: 0.0020593	total: 10m	remaining: 7m 18s
6062:	learn: 0.0016223	total: 10m	remaining: 6m 30s
5518:	learn: 0.0016387	total: 10m	remaining: 8m 7s
5966:	learn: 0.0016752	total: 10m	remaining: 6m 46s
5780:	learn: 0.0020593	total: 10m	remaining: 7m 18s
6063:	learn: 0.0016223	total: 10m	remaining: 6m 30s
5955:	learn: 0.0016022	total: 10m	remaining: 6m 47s
5967:	learn: 0.0016751	total: 10m	remaining: 6m 46s
5519:	learn: 0.0016383	total: 10m	remaining: 8m 7s
6064:	learn: 0.0016222	total: 10m	remaining: 6m 29s
5781:	learn: 0.0020593	total: 10m 1s	remaining: 7m 18s
5520:	learn: 0.0016377	total: 10m 1s	remaining: 8m 7s
5956:	learn: 0.0016022	total: 10m	remaining: 6m 47s
5968:	learn: 0.0016751	total: 10m 1s	remaining: 6m 45s
6065:	learn: 0.0016222	total: 10m 1s	remaining: 6m 29s
5782:	learn: 0.0020593	total: 10m 1s	remaining: 7m 18s
5521:	learn: 0.0016377	total: 10m 1s	remaining: 8m 7s
5957:	learn: 0.0016017	total: 10m 1s	remaining: 6m 47s
6066:	learn: 0.0016218	total: 10m 1s	remaining: 6m 29s
5969:	learn: 0.0016751	total: 10m 1s	remaining: 6m 45s
5783:	learn: 0.0020593	total: 10m 1s	remaining: 7m 18s
5522:	learn: 0.0016377	total: 10m 1s	remaining: 8m 7s
5958:	learn: 0.0016013	total: 10m 1s	remaining: 6m 47s
6067:	learn: 0.0016216	total: 10m 1s	remaining: 6m 29s
5970:	learn: 0.0016751	total: 10m 1s	remaining: 6m 45s
5784:	learn: 0.0020593	total: 10m 1s	remaining: 7m 18s
5959:	learn: 0.0016013	total: 10m 1s	remaining: 6m 47s
5523:	learn: 0.0016373	total: 10m 1s	remaining: 8m 7s
6068:	learn: 0.0016216	total: 10m 1s	remaining: 6m 29s
5785:	learn: 0.0020593	total: 10m 1s	remaining: 7m 18s
5971:	learn: 0.0016750	total: 10m 1s	remaining: 6m 45s
5524:	learn: 0.0016369	total: 10m 1s	remaining: 8m 7s
6069:	learn: 0.0016216	total: 10m 1s	remaining: 6m 29s
5960:	learn: 0.0016007	total: 10m 1s	remaining: 6m 47s
5786:	learn: 0.0020593	total: 10m 1s	remaining: 7m 17s
5972:	learn: 0.0016750	total: 10m 1s	remaining: 6m 45s
5525:	learn: 0.0016364	total: 10m 1s	remaining: 8m 7s
5961:	learn: 0.0016007	total: 10m 1s	remaining: 6m 47s
6070:	learn: 0.0016216	total: 10m 1s	remaining: 6m 29s
5973:	learn: 0.0016747	total: 10m 1s	remaining: 6m 45s
5787:	learn: 0.0020593	total: 10m 1s	remaining: 7m 17s
5526:	learn: 0.0016361	total: 10m 1s	remaining: 8m 6s
5962:	learn: 0.0016006	total: 10m 1s	remaining: 6m 47s
6071:	learn: 0.0016211	total: 10m 1s	remaining: 6m 29s
5788:	learn: 0.0020593	total: 10m 1s	remaining: 7m 17s
5974:	learn: 0.0016747	total: 10m 1s	remaining: 6m 45s
5527:	learn: 0.0016361	total: 10m 1s	remaining: 8m 6s
6072:	learn: 0.0016206	total: 10m 1s	remaining: 6m 29s
5963:	learn: 0.0016006	total: 10m 1s	remaining: 6m 47s
5789:	learn: 0.0020593	total: 10m 1s	remaining: 7m 17s
5528:	learn: 0.0016356	total: 10m 1s	remaining: 8m 6s
5975:	learn: 0.0016747	total: 10m 1s	remaining: 6m 45s
6073:	learn: 0.0016206	total: 10m 1s	remaining: 6m 28s
5790:	learn: 0.0020593	total: 10m 1s	remaining: 7m 17s
5529:	learn: 0.0016350	total: 10m 1s	remaining: 8m 6s
5964:	learn: 0.0016005	total: 10m 1s	remaining: 6m 47s
5976:	learn: 0.0016747	total: 10m 1s	remaining: 6m 45s
6074:	learn: 0.0016205	total: 10m 1s	remaining: 6m 28s
5791:	learn: 0.0020593	total: 10m 1s	remaining: 7m 17s
5965:	learn: 0.0016005	total: 10m 1s	remaining: 6m 46s
5530:	learn: 0.0016346	total: 10m 2s	remaining: 8m 6s
6075:	learn: 0.0016205	total: 10m 2s	remaining: 6m 28s
5977:	learn: 0.0016742	total: 10m 2s	remaining: 6m 45s
5792:	learn: 0.0020593	total: 10m 2s	remaining: 7m 17s
5966:	learn: 0.0016001	total: 10m 1s	remaining: 6m 46s
6076:	learn: 0.0016200	total: 10m 2s	remaining: 6m 28s
5978:	learn: 0.0016742	total: 10m 2s	remaining: 6m 44s
5793:	learn: 0.0020593	total: 10m 2s	remaining: 7m 17s
5531:	learn: 0.0016346	total: 10m 2s	remaining: 8m 6s
5967:	learn: 0.0015998	total: 10m 2s	remaining: 6m 46s
5979:	learn: 0.0016742	total: 10m 2s	remaining: 6m 44s
5794:	learn: 0.0020593	total: 10m 2s	remaining: 7m 17s
6077:	learn: 0.0016200	total: 10m 2s	remaining: 6m 28s
5532:	learn: 0.0016342	total: 10m 2s	remaining: 8m 6s
5795:	learn: 0.0020593	total: 10m 2s	remaining: 7m 16s
5968:	learn: 0.0015998	total: 10m 2s	remaining: 6m 46s
5980:	learn: 0.0016742	total: 10m 2s	remaining: 6m 44s
6078:	learn: 0.0016192	total: 10m 2s	remaining: 6m 28s
5969:	learn: 0.0015997	total: 10m 2s	remaining: 6m 46s
5533:	learn: 0.0016338	total: 10m 2s	remaining: 8m 6s
5796:	learn: 0.0020593	total: 10m 2s	remaining: 7m 16s
5981:	learn: 0.0016737	total: 10m 2s	remaining: 6m 44s
6079:	learn: 0.0016188	total: 10m 2s	remaining: 6m 28s
5534:	learn: 0.0016338	total: 10m 2s	remaining: 8m 6s
5797:	learn: 0.0020593	total: 10m 2s	remaining: 7m 16s
5970:	learn: 0.0015997	total: 10m 2s	remaining: 6m 46s
5982:	learn: 0.0016731	total: 10m 2s	remaining: 6m 44s
6080:	learn: 0.0016188	total: 10m 2s	remaining: 6m 28s
5535:	learn: 0.0016338	total: 10m 2s	remaining: 8m 5s
5971:	learn: 0.0015994	total: 10m 2s	remaining: 6m 46s
5983:	learn: 0.0016731	total: 10m 2s	remaining: 6m 44s
5798:	learn: 0.0020593	total: 10m 2s	remaining: 7m 16s
5536:	learn: 0.0016338	total: 10m 2s	remaining: 8m 5s
5972:	learn: 0.0015991	total: 10m 2s	remaining: 6m 46s
6081:	learn: 0.0016184	total: 10m 2s	remaining: 6m 28s
5984:	learn: 0.0016731	total: 10m 2s	remaining: 6m 44s
5973:	learn: 0.0015991	total: 10m 2s	remaining: 6m 46s
5799:	learn: 0.0020593	total: 10m 2s	remaining: 7m 16s
5537:	learn: 0.0016338	total: 10m 2s	remaining: 8m 5s
6082:	learn: 0.0016184	total: 10m 2s	remaining: 6m 28s
5985:	learn: 0.0016728	total: 10m 2s	remaining: 6m 44s
5800:	learn: 0.0020593	total: 10m 2s	remaining: 7m 16s
5974:	learn: 0.0015989	total: 10m 2s	remaining: 6m 46s
6083:	learn: 0.0016184	total: 10m 2s	remaining: 6m 28s
5538:	learn: 0.0016334	total: 10m 2s	remaining: 8m 5s
5975:	learn: 0.0015984	total: 10m 2s	remaining: 6m 45s
5801:	learn: 0.0020593	total: 10m 2s	remaining: 7m 16s
5986:	learn: 0.0016726	total: 10m 2s	remaining: 6m 44s
6084:	learn: 0.0016181	total: 10m 2s	remaining: 6m 27s
5539:	learn: 0.0016329	total: 10m 3s	remaining: 8m 5s
5802:	learn: 0.0020593	total: 10m 3s	remaining: 7m 16s
5976:	learn: 0.0015980	total: 10m 2s	remaining: 6m 45s
5987:	learn: 0.0016721	total: 10m 3s	remaining: 6m 44s
6085:	learn: 0.0016179	total: 10m 3s	remaining: 6m 27s
5540:	learn: 0.0016329	total: 10m 3s	remaining: 8m 5s
5803:	learn: 0.0020593	total: 10m 3s	remaining: 7m 16s
5988:	learn: 0.0016717	total: 10m 3s	remaining: 6m 43s
5977:	learn: 0.0015974	total: 10m 3s	remaining: 6m 45s
6086:	learn: 0.0016179	total: 10m 3s	remaining: 6m 27s
5541:	learn: 0.0016323	total: 10m 3s	remaining: 8m 5s
5804:	learn: 0.0020593	total: 10m 3s	remaining: 7m 15s
5989:	learn: 0.0016717	total: 10m 3s	remaining: 6m 43s
5978:	learn: 0.0015973	total: 10m 3s	remaining: 6m 45s
6087:	learn: 0.0016177	total: 10m 3s	remaining: 6m 27s
5805:	learn: 0.0020593	total: 10m 3s	remaining: 7m 15s
5542:	learn: 0.0016318	total: 10m 3s	remaining: 8m 5s
5990:	learn: 0.0016717	total: 10m 3s	remaining: 6m 43s
6088:	learn: 0.0016172	total: 10m 3s	remaining: 6m 27s
5979:	learn: 0.0015973	total: 10m 3s	remaining: 6m 45s
5806:	learn: 0.0020593	total: 10m 3s	remaining: 7m 15s
5543:	learn: 0.0016315	total: 10m 3s	remaining: 8m 5s
6089:	learn: 0.0016166	total: 10m 3s	remaining: 6m 27s
5991:	learn: 0.0016717	total: 10m 3s	remaining: 6m 43s
5980:	learn: 0.0015973	total: 10m 3s	remaining: 6m 45s
5807:	learn: 0.0020593	total: 10m 3s	remaining: 7m 15s
6090:	learn: 0.0016166	total: 10m 3s	remaining: 6m 27s
5544:	learn: 0.0016315	total: 10m 3s	remaining: 8m 4s
5992:	learn: 0.0016718	total: 10m 3s	remaining: 6m 43s
5981:	learn: 0.0015972	total: 10m 3s	remaining: 6m 45s
5808:	learn: 0.0020593	total: 10m 3s	remaining: 7m 15s
6091:	learn: 0.0016164	total: 10m 3s	remaining: 6m 27s
5545:	learn: 0.0016315	total: 10m 3s	remaining: 8m 4s
5993:	learn: 0.0016717	total: 10m 3s	remaining: 6m 43s
5982:	learn: 0.0015972	total: 10m 3s	remaining: 6m 45s
6092:	learn: 0.0016158	total: 10m 3s	remaining: 6m 27s
5809:	learn: 0.0020593	total: 10m 3s	remaining: 7m 15s
5994:	learn: 0.0016717	total: 10m 3s	remaining: 6m 43s
5546:	learn: 0.0016311	total: 10m 3s	remaining: 8m 4s
5983:	learn: 0.0015972	total: 10m 3s	remaining: 6m 45s
6093:	learn: 0.0016151	total: 10m 3s	remaining: 6m 26s
5995:	learn: 0.0016717	total: 10m 3s	remaining: 6m 43s
5810:	learn: 0.0020593	total: 10m 3s	remaining: 7m 15s
5547:	learn: 0.0016307	total: 10m 3s	remaining: 8m 4s
6094:	learn: 0.0016149	total: 10m 3s	remaining: 6m 26s
5996:	learn: 0.0016718	total: 10m 3s	remaining: 6m 43s
5984:	learn: 0.0015972	total: 10m 3s	remaining: 6m 45s
5811:	learn: 0.0020593	total: 10m 3s	remaining: 7m 15s
6095:	learn: 0.0016145	total: 10m 3s	remaining: 6m 26s
5997:	learn: 0.0016717	total: 10m 4s	remaining: 6m 43s
5548:	learn: 0.0016303	total: 10m 4s	remaining: 8m 4s
5985:	learn: 0.0015968	total: 10m 3s	remaining: 6m 44s
6096:	learn: 0.0016141	total: 10m 4s	remaining: 6m 26s
5812:	learn: 0.0020593	total: 10m 4s	remaining: 7m 15s
5998:	learn: 0.0016713	total: 10m 4s	remaining: 6m 42s
5549:	learn: 0.0016303	total: 10m 4s	remaining: 8m 4s
5986:	learn: 0.0015968	total: 10m 3s	remaining: 6m 44s
6097:	learn: 0.0016141	total: 10m 4s	remaining: 6m 26s
5813:	learn: 0.0020593	total: 10m 4s	remaining: 7m 15s
5550:	learn: 0.0016300	total: 10m 4s	remaining: 8m 4s
5999:	learn: 0.0016711	total: 10m 4s	remaining: 6m 42s
5987:	learn: 0.0015964	total: 10m 4s	remaining: 6m 44s
6098:	learn: 0.0016141	total: 10m 4s	remaining: 6m 26s
5551:	learn: 0.0016295	total: 10m 4s	remaining: 8m 4s
5814:	learn: 0.0020593	total: 10m 4s	remaining: 7m 14s
5988:	learn: 0.0015964	total: 10m 4s	remaining: 6m 44s
6000:	learn: 0.0016708	total: 10m 4s	remaining: 6m 42s
5552:	learn: 0.0016295	total: 10m 4s	remaining: 8m 4s
6099:	learn: 0.0016141	total: 10m 4s	remaining: 6m 26s
5815:	learn: 0.0020593	total: 10m 4s	remaining: 7m 14s
5989:	learn: 0.0015964	total: 10m 4s	remaining: 6m 44s
5553:	learn: 0.0016291	total: 10m 4s	remaining: 8m 3s
5816:	learn: 0.0020593	total: 10m 4s	remaining: 7m 14s
6001:	learn: 0.0016708	total: 10m 4s	remaining: 6m 42s
6100:	learn: 0.0016141	total: 10m 4s	remaining: 6m 26s
5990:	learn: 0.0015964	total: 10m 4s	remaining: 6m 44s
5554:	learn: 0.0016286	total: 10m 4s	remaining: 8m 3s
5817:	learn: 0.0020593	total: 10m 4s	remaining: 7m 14s
6002:	learn: 0.0016707	total: 10m 4s	remaining: 6m 42s
6101:	learn: 0.0016141	total: 10m 4s	remaining: 6m 26s
5818:	learn: 0.0020593	total: 10m 4s	remaining: 7m 14s
5991:	learn: 0.0015964	total: 10m 4s	remaining: 6m 44s
5555:	learn: 0.0016286	total: 10m 4s	remaining: 8m 3s
6003:	learn: 0.0016707	total: 10m 4s	remaining: 6m 42s
6102:	learn: 0.0016137	total: 10m 4s	remaining: 6m 26s
5819:	learn: 0.0020593	total: 10m 4s	remaining: 7m 14s
6004:	learn: 0.0016706	total: 10m 4s	remaining: 6m 42s
5992:	learn: 0.0015964	total: 10m 4s	remaining: 6m 44s
5556:	learn: 0.0016282	total: 10m 4s	remaining: 8m 3s
6103:	learn: 0.0016135	total: 10m 4s	remaining: 6m 25s
5820:	learn: 0.0020593	total: 10m 4s	remaining: 7m 14s
6005:	learn: 0.0016706	total: 10m 4s	remaining: 6m 42s
5993:	learn: 0.0015958	total: 10m 4s	remaining: 6m 44s
5821:	learn: 0.0020593	total: 10m 4s	remaining: 7m 14s
5557:	learn: 0.0016282	total: 10m 4s	remaining: 8m 3s
6104:	learn: 0.0016130	total: 10m 4s	remaining: 6m 25s
6006:	learn: 0.0016706	total: 10m 4s	remaining: 6m 42s
5994:	learn: 0.0015958	total: 10m 4s	remaining: 6m 44s
5558:	learn: 0.0016282	total: 10m 5s	remaining: 8m 3s
5822:	learn: 0.0020593	total: 10m 5s	remaining: 7m 13s
6105:	learn: 0.0016130	total: 10m 4s	remaining: 6m 25s
6007:	learn: 0.0016703	total: 10m 5s	remaining: 6m 42s
5995:	learn: 0.0015952	total: 10m 4s	remaining: 6m 43s
5559:	learn: 0.0016282	total: 10m 5s	remaining: 8m 3s
5823:	learn: 0.0020593	total: 10m 5s	remaining: 7m 13s
6106:	learn: 0.0016130	total: 10m 5s	remaining: 6m 25s
6008:	learn: 0.0016699	total: 10m 5s	remaining: 6m 41s
5560:	learn: 0.0016282	total: 10m 5s	remaining: 8m 3s
5996:	learn: 0.0015947	total: 10m 5s	remaining: 6m 43s
5824:	learn: 0.0020593	total: 10m 5s	remaining: 7m 13s
6107:	learn: 0.0016130	total: 10m 5s	remaining: 6m 25s
6009:	learn: 0.0016699	total: 10m 5s	remaining: 6m 41s
5997:	learn: 0.0015947	total: 10m 5s	remaining: 6m 43s
5561:	learn: 0.0016278	total: 10m 5s	remaining: 8m 2s
6108:	learn: 0.0016130	total: 10m 5s	remaining: 6m 25s
5825:	learn: 0.0020593	total: 10m 5s	remaining: 7m 13s
6010:	learn: 0.0016699	total: 10m 5s	remaining: 6m 41s
5998:	learn: 0.0015943	total: 10m 5s	remaining: 6m 43s
6109:	learn: 0.0016127	total: 10m 5s	remaining: 6m 25s
5826:	learn: 0.0020593	total: 10m 5s	remaining: 7m 13s
5562:	learn: 0.0016278	total: 10m 5s	remaining: 8m 2s
5999:	learn: 0.0015939	total: 10m 5s	remaining: 6m 43s
6011:	learn: 0.0016697	total: 10m 5s	remaining: 6m 41s
6110:	learn: 0.0016127	total: 10m 5s	remaining: 6m 25s
6000:	learn: 0.0015936	total: 10m 5s	remaining: 6m 43s
5827:	learn: 0.0020593	total: 10m 5s	remaining: 7m 13s
5563:	learn: 0.0016274	total: 10m 5s	remaining: 8m 2s
6012:	learn: 0.0016692	total: 10m 5s	remaining: 6m 41s
6111:	learn: 0.0016124	total: 10m 5s	remaining: 6m 25s
6001:	learn: 0.0015936	total: 10m 5s	remaining: 6m 43s
5564:	learn: 0.0016268	total: 10m 5s	remaining: 8m 2s
6013:	learn: 0.0016685	total: 10m 5s	remaining: 6m 41s
5828:	learn: 0.0020593	total: 10m 5s	remaining: 7m 13s
6112:	learn: 0.0016124	total: 10m 5s	remaining: 6m 25s
6002:	learn: 0.0015935	total: 10m 5s	remaining: 6m 43s
6014:	learn: 0.0016685	total: 10m 5s	remaining: 6m 41s
5565:	learn: 0.0016268	total: 10m 5s	remaining: 8m 2s
6113:	learn: 0.0016124	total: 10m 5s	remaining: 6m 24s
5829:	learn: 0.0020593	total: 10m 5s	remaining: 7m 13s
6015:	learn: 0.0016685	total: 10m 5s	remaining: 6m 41s
6003:	learn: 0.0015935	total: 10m 5s	remaining: 6m 43s
5566:	learn: 0.0016265	total: 10m 5s	remaining: 8m 2s
6114:	learn: 0.0016121	total: 10m 5s	remaining: 6m 24s
5830:	learn: 0.0020593	total: 10m 5s	remaining: 7m 13s
6004:	learn: 0.0015931	total: 10m 5s	remaining: 6m 42s
6016:	learn: 0.0016685	total: 10m 5s	remaining: 6m 41s
5567:	learn: 0.0016265	total: 10m 5s	remaining: 8m 2s
6115:	learn: 0.0016117	total: 10m 5s	remaining: 6m 24s
6005:	learn: 0.0015931	total: 10m 5s	remaining: 6m 42s

6017:	learn: 0.0016681	total: 10m 6s	remaining: 6m 40s
5831:	learn: 0.0020593	total: 10m 6s	remaining: 7m 13s
5568:	learn: 0.0016265	total: 10m 6s	remaining: 8m 2s
6006:	learn: 0.0015925	total: 10m 5s	remaining: 6m 42s
6116:	learn: 0.0016112	total: 10m 6s	remaining: 6m 24s
6007:	learn: 0.0015925	total: 10m 5s	remaining: 6m 42s
5832:	learn: 0.0020593	total: 10m 6s	remaining: 7m 13s
6018:	learn: 0.0016681	total: 10m 6s	remaining: 6m 40s
5569:	learn: 0.0016265	total: 10m 6s	remaining: 8m 2s
6117:	learn: 0.0016112	total: 10m 6s	remaining: 6m 24s
6019:	learn: 0.0016676	total: 10m 6s	remaining: 6m 40s
5833:	learn: 0.0020593	total: 10m 6s	remaining: 7m 12s
6008:	learn: 0.0015924	total: 10m 6s	remaining: 6m 42s
6118:	learn: 0.0016112	total: 10m 6s	remaining: 6m 24s
5570:	learn: 0.0016260	total: 10m 6s	remaining: 8m 2s
6020:	learn: 0.0016676	total: 10m 6s	remaining: 6m 40s
6119:	learn: 0.0016112	total: 10m 6s	remaining: 6m 24s
5834:	learn: 0.0020593	total: 10m 6s	remaining: 7m 12s
6009:	learn: 0.0015924	total: 10m 6s	remaining: 6m 42s
5571:	learn: 0.0016260	total: 10m 6s	remaining: 8m 1s
6120:	learn: 0.0016106	total: 10m 6s	remaining: 6m 24s
6021:	learn: 0.0016676	total: 10m 6s	remaining: 6m 40s
5835:	learn: 0.0020593	total: 10m 6s	remaining: 7m 12s
6121:	learn: 0.0016103	total: 10m 6s	remaining: 6m 24s
6010:	learn: 0.0015919	total: 10m 6s	remaining: 6m 42s
5572:	learn: 0.0016260	total: 10m 6s	remaining: 8m 1s
6022:	learn: 0.0016675	total: 10m 6s	remaining: 6m 40s
5836:	learn: 0.0020593	total: 10m 6s	remaining: 7m 12s
6122:	learn: 0.0016099	total: 10m 6s	remaining: 6m 24s
5573:	learn: 0.0016260	total: 10m 6s	remaining: 8m 1s
6011:	learn: 0.0015919	total: 10m 6s	remaining: 6m 42s
5837:	learn: 0.0020593	total: 10m 6s	remaining: 7m 12s
6023:	learn: 0.0016669	total: 10m 6s	remaining: 6m 40s
6123:	learn: 0.0016099	total: 10m 6s	remaining: 6m 23s
5838:	learn: 0.0020586	total: 10m 6s	remaining: 7m 12s
6012:	learn: 0.0015919	total: 10m 6s	remaining: 6m 42s
5574:	learn: 0.0016254	total: 10m 6s	remaining: 8m 1s
6124:	learn: 0.0016097	total: 10m 6s	remaining: 6m 23s
6024:	learn: 0.0016669	total: 10m 6s	remaining: 6m 40s
6013:	learn: 0.0015919	total: 10m 6s	remaining: 6m 42s
5839:	learn: 0.0020586	total: 10m 6s	remaining: 7m 12s
6125:	learn: 0.0016097	total: 10m 6s	remaining: 6m 23s
5575:	learn: 0.0016254	total: 10m 6s	remaining: 8m 1s
6126:	learn: 0.0016097	total: 10m 6s	remaining: 6m 23s
6014:	learn: 0.0015919	total: 10m 6s	remaining: 6m 41s
6025:	learn: 0.0016663	total: 10m 6s	remaining: 6m 40s
5840:	learn: 0.0020586	total: 10m 6s	remaining: 7m 12s
5576:	learn: 0.0016254	total: 10m 6s	remaining: 8m 1s
6026:	learn: 0.0016659	total: 10m 6s	remaining: 6m 40s
6015:	learn: 0.0015919	total: 10m 6s	remaining: 6m 41s
6127:	learn: 0.0016096	total: 10m 6s	remaining: 6m 23s
5841:	learn: 0.0020586	total: 10m 7s	remaining: 7m 12s
5577:	learn: 0.0016254	total: 10m 7s	remaining: 8m 1s
6027:	learn: 0.0016655	total: 10m 7s	remaining: 6m 40s
6128:	learn: 0.0016096	total: 10m 7s	remaining: 6m 23s
6016:	learn: 0.0015918	total: 10m 6s	remaining: 6m 41s
5842:	learn: 0.0020586	total: 10m 7s	remaining: 7m 11s
5578:	learn: 0.0016254	total: 10m 7s	remaining: 8m 1s
6028:	learn: 0.0016654	total: 10m 7s	remaining: 6m 39s
6129:	learn: 0.0016096	total: 10m 7s	remaining: 6m 23s
5843:	learn: 0.0020586	total: 10m 7s	remaining: 7m 11s
6017:	learn: 0.0015918	total: 10m 7s	remaining: 6m 41s
5579:	learn: 0.0016254	total: 10m 7s	remaining: 8m 1s
5844:	learn: 0.0020587	total: 10m 7s	remaining: 7m 11s
6029:	learn: 0.0016647	total: 10m 7s	remaining: 6m 39s
6130:	learn: 0.0016096	total: 10m 7s	remaining: 6m 23s
5580:	learn: 0.0016254	total: 10m 7s	remaining: 8m
6018:	learn: 0.0015918	total: 10m 7s	remaining: 6m 41s
6030:	learn: 0.0016644	total: 10m 7s	remaining: 6m 39s
5845:	learn: 0.0020587	total: 10m 7s	remaining: 7m 11s
6131:	learn: 0.0016093	total: 10m 7s	remaining: 6m 23s
6019:	learn: 0.0015916	total: 10m 7s	remaining: 6m 41s
5581:	learn: 0.0016250	total: 10m 7s	remaining: 8m
6031:	learn: 0.0016641	total: 10m 7s	remaining: 6m 39s
6132:	learn: 0.0016093	total: 10m 7s	remaining: 6m 23s
5846:	learn: 0.0020586	total: 10m 7s	remaining: 7m 11s
6020:	learn: 0.0015916	total: 10m 7s	remaining: 6m 41s
5582:	learn: 0.0016249	total: 10m 7s	remaining: 8m
6032:	learn: 0.0016641	total: 10m 7s	remaining: 6m 39s
6021:	learn: 0.0015915	total: 10m 7s	remaining: 6m 41s
5847:	learn: 0.0020586	total: 10m 7s	remaining: 7m 11s
6133:	learn: 0.0016086	total: 10m 7s	remaining: 6m 22s
5583:	learn: 0.0016246	total: 10m 7s	remaining: 8m
6022:	learn: 0.0015915	total: 10m 7s	remaining: 6m 41s
6033:	learn: 0.0016635	total: 10m 7s	remaining: 6m 39s
5848:	learn: 0.0020586	total: 10m 7s	remaining: 7m 11s
6134:	learn: 0.0016079	total: 10m 7s	remaining: 6m 22s
6034:	learn: 0.0016635	total: 10m 7s	remaining: 6m 39s
5584:	learn: 0.0016243	total: 10m 7s	remaining: 8m
6023:	learn: 0.0015915	total: 10m 7s	remaining: 6m 41s
5849:	learn: 0.0020586	total: 10m 7s	remaining: 7m 11s
6035:	learn: 0.0016630	total: 10m 7s	remaining: 6m 39s
6135:	learn: 0.0016075	total: 10m 7s	remaining: 6m 22s
5585:	learn: 0.0016243	total: 10m 7s	remaining: 8m
6024:	learn: 0.0015915	total: 10m 7s	remaining: 6m 40s
5850:	learn: 0.0020586	total: 10m 7s	remaining: 7m 11s
6036:	learn: 0.0016630	total: 10m 7s	remaining: 6m 39s
5586:	learn: 0.0016243	total: 10m 7s	remaining: 8m
6136:	learn: 0.0016074	total: 10m 7s	remaining: 6m 22s
6025:	learn: 0.0015914	total: 10m 7s	remaining: 6m 40s
5851:	learn: 0.0020586	total: 10m 7s	remaining: 7m 10s
6037:	learn: 0.0016630	total: 10m 8s	remaining: 6m 38s
6137:	learn: 0.0016068	total: 10m 8s	remaining: 6m 22s
6026:	learn: 0.0015909	total: 10m 7s	remaining: 6m 40s
5587:	learn: 0.0016243	total: 10m 8s	remaining: 8m
5852:	learn: 0.0020586	total: 10m 8s	remaining: 7m 10s
6027:	learn: 0.0015904	total: 10m 7s	remaining: 6m 40s
6038:	learn: 0.0016623	total: 10m 8s	remaining: 6m 38s
6138:	learn: 0.0016063	total: 10m 8s	remaining: 6m 22s
5588:	learn: 0.0016243	total: 10m 8s	remaining: 8m
5853:	learn: 0.0020586	total: 10m 8s	remaining: 7m 10s
6028:	learn: 0.0015899	total: 10m 8s	remaining: 6m 40s
6139:	learn: 0.0016063	total: 10m 8s	remaining: 6m 22s
6039:	learn: 0.0016618	total: 10m 8s	remaining: 6m 38s
5589:	learn: 0.0016239	total: 10m 8s	remaining: 7m 59s
5854:	learn: 0.0020586	total: 10m 8s	remaining: 7m 10s
6140:	learn: 0.0016059	total: 10m 8s	remaining: 6m 22s
6029:	learn: 0.0015898	total: 10m 8s	remaining: 6m 40s
6040:	learn: 0.0016618	total: 10m 8s	remaining: 6m 38s
5590:	learn: 0.0016239	total: 10m 8s	remaining: 7m 59s
6141:	learn: 0.0016054	total: 10m 8s	remaining: 6m 22s
5855:	learn: 0.0020586	total: 10m 8s	remaining: 7m 10s
6030:	learn: 0.0015899	total: 10m 8s	remaining: 6m 40s
6041:	learn: 0.0016612	total: 10m 8s	remaining: 6m 38s
5591:	learn: 0.0016239	total: 10m 8s	remaining: 7m 59s
6142:	learn: 0.0016049	total: 10m 8s	remaining: 6m 22s
5856:	learn: 0.0020586	total: 10m 8s	remaining: 7m 10s
6031:	learn: 0.0015899	total: 10m 8s	remaining: 6m 40s
6042:	learn: 0.0016609	total: 10m 8s	remaining: 6m 38s
5592:	learn: 0.0016239	total: 10m 8s	remaining: 7m 59s
5857:	learn: 0.0020586	total: 10m 8s	remaining: 7m 10s
6143:	learn: 0.0016049	total: 10m 8s	remaining: 6m 21s
6043:	learn: 0.0016606	total: 10m 8s	remaining: 6m 38s
6032:	learn: 0.0015894	total: 10m 8s	remaining: 6m 40s
5593:	learn: 0.0016239	total: 10m 8s	remaining: 7m 59s
5858:	learn: 0.0020586	total: 10m 8s	remaining: 7m 10s
6044:	learn: 0.0016605	total: 10m 8s	remaining: 6m 38s
6144:	learn: 0.0016049	total: 10m 8s	remaining: 6m 21s
6033:	learn: 0.0015891	total: 10m 8s	remaining: 6m 40s
5859:	learn: 0.0020586	total: 10m 8s	remaining: 7m 10s
5594:	learn: 0.0016239	total: 10m 8s	remaining: 7m 59s
6034:	learn: 0.0015891	total: 10m 8s	remaining: 6m 39s
6145:	learn: 0.0016049	total: 10m 8s	remaining: 6m 21s
6045:	learn: 0.0016605	total: 10m 8s	remaining: 6m 38s
5595:	learn: 0.0016239	total: 10m 8s	remaining: 7m 59s
5860:	learn: 0.0020586	total: 10m 8s	remaining: 7m 10s
6146:	learn: 0.0016049	total: 10m 8s	remaining: 6m 21s
6035:	learn: 0.0015886	total: 10m 8s	remaining: 6m 39s
6046:	learn: 0.0016605	total: 10m 8s	remaining: 6m 38s
5596:	learn: 0.0016239	total: 10m 9s	remaining: 7m 59s
5861:	learn: 0.0020586	total: 10m 9s	remaining: 7m 9s
6147:	learn: 0.0016049	total: 10m 8s	remaining: 6m 21s
6036:	learn: 0.0015883	total: 10m 8s	remaining: 6m 39s
6047:	learn: 0.0016601	total: 10m 9s	remaining: 6m 37s
5597:	learn: 0.0016238	total: 10m 9s	remaining: 7m 58s
5862:	learn: 0.0020586	total: 10m 9s	remaining: 7m 9s
6148:	learn: 0.0016049	total: 10m 9s	remaining: 6m 21s
6037:	learn: 0.0015883	total: 10m 8s	remaining: 6m 39s
6048:	learn: 0.0016597	total: 10m 9s	remaining: 6m 37s
6149:	learn: 0.0016049	total: 10m 9s	remaining: 6m 21s
5598:	learn: 0.0016230	total: 10m 9s	remaining: 7m 58s
6038:	learn: 0.0015883	total: 10m 9s	remaining: 6m 39s
5863:	learn: 0.0020586	total: 10m 9s	remaining: 7m 9s
6049:	learn: 0.0016597	total: 10m 9s	remaining: 6m 37s
6039:	learn: 0.0015883	total: 10m 9s	remaining: 6m 39s
6150:	learn: 0.0016046	total: 10m 9s	remaining: 6m 21s
5599:	learn: 0.0016224	total: 10m 9s	remaining: 7m 58s
5864:	learn: 0.0020586	total: 10m 9s	remaining: 7m 9s
6050:	learn: 0.0016595	total: 10m 9s	remaining: 6m 37s
6151:	learn: 0.0016044	total: 10m 9s	remaining: 6m 21s
6040:	learn: 0.0015883	total: 10m 9s	remaining: 6m 39s
6051:	learn: 0.0016588	total: 10m 9s	remaining: 6m 37s
5600:	learn: 0.0016224	total: 10m 9s	remaining: 7m 58s
5865:	learn: 0.0020586	total: 10m 9s	remaining: 7m 9s
6152:	learn: 0.0016039	total: 10m 9s	remaining: 6m 21s
6041:	learn: 0.0015883	total: 10m 9s	remaining: 6m 39s
5866:	learn: 0.0020586	total: 10m 9s	remaining: 7m 9s
6153:	learn: 0.0016034	total: 10m 9s	remaining: 6m 20s
5601:	learn: 0.0016224	total: 10m 9s	remaining: 7m 58s
6052:	learn: 0.0016588	total: 10m 9s	remaining: 6m 37s
6042:	learn: 0.0015882	total: 10m 9s	remaining: 6m 39s
5867:	learn: 0.0020586	total: 10m 9s	remaining: 7m 9s
6154:	learn: 0.0016030	total: 10m 9s	remaining: 6m 20s
6053:	learn: 0.0016588	total: 10m 9s	remaining: 6m 37s
5602:	learn: 0.0016220	total: 10m 9s	remaining: 7m 58s
6043:	learn: 0.0015882	total: 10m 9s	remaining: 6m 38s
6155:	learn: 0.0016025	total: 10m 9s	remaining: 6m 20s
5868:	learn: 0.0020586	total: 10m 9s	remaining: 7m 9s
6054:	learn: 0.0016588	total: 10m 9s	remaining: 6m 37s
5603:	learn: 0.0016216	total: 10m 9s	remaining: 7m 58s
6044:	learn: 0.0015880	total: 10m 9s	remaining: 6m 38s
5869:	learn: 0.0020586	total: 10m 9s	remaining: 7m 9s
6156:	learn: 0.0016021	total: 10m 9s	remaining: 6m 20s
6055:	learn: 0.0016584	total: 10m 9s	remaining: 6m 37s
6045:	learn: 0.0015880	total: 10m 9s	remaining: 6m 38s
5870:	learn: 0.0020586	total: 10m 9s	remaining: 7m 8s
5604:	learn: 0.0016216	total: 10m 9s	remaining: 7m 58s
6157:	learn: 0.0016016	total: 10m 9s	remaining: 6m 20s
6056:	learn: 0.0016581	total: 10m 9s	remaining: 6m 37s
5871:	learn: 0.0020586	total: 10m 10s	remaining: 7m 8s
5605:	learn: 0.0016212	total: 10m 10s	remaining: 7m 58s
6046:	learn: 0.0015880	total: 10m 9s	remaining: 6m 38s
6158:	learn: 0.0016016	total: 10m 9s	remaining: 6m 20s
5872:	learn: 0.0020586	total: 10m 10s	remaining: 7m 8s
6057:	learn: 0.0016581	total: 10m 10s	remaining: 6m 36s
6047:	learn: 0.0015880	total: 10m 9s	remaining: 6m 38s
6159:	learn: 0.0016011	total: 10m 10s	remaining: 6m 20s
5606:	learn: 0.0016212	total: 10m 10s	remaining: 7m 58s
5873:	learn: 0.0020586	total: 10m 10s	remaining: 7m 8s
6058:	learn: 0.0016576	total: 10m 10s	remaining: 6m 36s
6048:	learn: 0.0015876	total: 10m 10s	remaining: 6m 38s
5607:	learn: 0.0016212	total: 10m 10s	remaining: 7m 57s
6160:	learn: 0.0016011	total: 10m 10s	remaining: 6m 20s
5874:	learn: 0.0020586	total: 10m 10s	remaining: 7m 8s
6059:	learn: 0.0016576	total: 10m 10s	remaining: 6m 36s
6049:	learn: 0.0015870	total: 10m 10s	remaining: 6m 38s
6161:	learn: 0.0016011	total: 10m 10s	remaining: 6m 20s
5608:	learn: 0.0016212	total: 10m 10s	remaining: 7m 57s
5875:	learn: 0.0020586	total: 10m 10s	remaining: 7m 8s
6060:	learn: 0.0016576	total: 10m 10s	remaining: 6m 36s
6050:	learn: 0.0015870	total: 10m 10s	remaining: 6m 38s
6162:	learn: 0.0016009	total: 10m 10s	remaining: 6m 20s
5609:	learn: 0.0016212	total: 10m 10s	remaining: 7m 57s
5876:	learn: 0.0020586	total: 10m 10s	remaining: 7m 8s
6061:	learn: 0.0016571	total: 10m 10s	remaining: 6m 36s
6163:	learn: 0.0016003	total: 10m 10s	remaining: 6m 19s
6051:	learn: 0.0015870	total: 10m 10s	remaining: 6m 38s
5610:	learn: 0.0016208	total: 10m 10s	remaining: 7m 57s
5877:	learn: 0.0020586	total: 10m 10s	remaining: 7m 8s
6062:	learn: 0.0016566	total: 10m 10s	remaining: 6m 36s
6164:	learn: 0.0015999	total: 10m 10s	remaining: 6m 19s
5611:	learn: 0.0016204	total: 10m 10s	remaining: 7m 57s
6052:	learn: 0.0015870	total: 10m 10s	remaining: 6m 38s
5878:	learn: 0.0020585	total: 10m 10s	remaining: 7m 8s
6063:	learn: 0.0016560	total: 10m 10s	remaining: 6m 36s
5612:	learn: 0.0016205	total: 10m 10s	remaining: 7m 57s
6165:	learn: 0.0015995	total: 10m 10s	remaining: 6m 19s
6053:	learn: 0.0015869	total: 10m 10s	remaining: 6m 37s
6064:	learn: 0.0016560	total: 10m 10s	remaining: 6m 36s
5613:	learn: 0.0016201	total: 10m 10s	remaining: 7m 57s
5879:	learn: 0.0020585	total: 10m 10s	remaining: 7m 7s
6054:	learn: 0.0015869	total: 10m 10s	remaining: 6m 37s
6166:	learn: 0.0015990	total: 10m 10s	remaining: 6m 19s
6065:	learn: 0.0016556	total: 10m 10s	remaining: 6m 36s
5614:	learn: 0.0016196	total: 10m 10s	remaining: 7m 57s
5880:	learn: 0.0020585	total: 10m 10s	remaining: 7m 7s
6167:	learn: 0.0015990	total: 10m 10s	remaining: 6m 19s
6055:	learn: 0.0015863	total: 10m 10s	remaining: 6m 37s
5615:	learn: 0.0016193	total: 10m 11s	remaining: 7m 56s
6066:	learn: 0.0016556	total: 10m 10s	remaining: 6m 36s
5881:	learn: 0.0020585	total: 10m 11s	remaining: 7m 7s
6056:	learn: 0.0015863	total: 10m 10s	remaining: 6m 37s
6168:	learn: 0.0015990	total: 10m 10s	remaining: 6m 19s
5616:	learn: 0.0016187	total: 10m 11s	remaining: 7m 56s
6067:	learn: 0.0016555	total: 10m 11s	remaining: 6m 35s
5882:	learn: 0.0020585	total: 10m 11s	remaining: 7m 7s
6057:	learn: 0.0015858	total: 10m 10s	remaining: 6m 37s
6169:	learn: 0.0015990	total: 10m 11s	remaining: 6m 19s
5617:	learn: 0.0016187	total: 10m 11s	remaining: 7m 56s
6068:	learn: 0.0016556	total: 10m 11s	remaining: 6m 35s
5883:	learn: 0.0020585	total: 10m 11s	remaining: 7m 7s
6058:	learn: 0.0015858	total: 10m 11s	remaining: 6m 37s
6170:	learn: 0.0015990	total: 10m 11s	remaining: 6m 19s
5618:	learn: 0.0016187	total: 10m 11s	remaining: 7m 56s
6069:	learn: 0.0016556	total: 10m 11s	remaining: 6m 35s
5884:	learn: 0.0020585	total: 10m 11s	remaining: 7m 7s
6059:	learn: 0.0015854	total: 10m 11s	remaining: 6m 37s
6171:	learn: 0.0015989	total: 10m 11s	remaining: 6m 19s
5619:	learn: 0.0016187	total: 10m 11s	remaining: 7m 56s
6070:	learn: 0.0016551	total: 10m 11s	remaining: 6m 35s
6060:	learn: 0.0015854	total: 10m 11s	remaining: 6m 37s
5885:	learn: 0.0020585	total: 10m 11s	remaining: 7m 7s
6172:	learn: 0.0015990	total: 10m 11s	remaining: 6m 19s
5620:	learn: 0.0016183	total: 10m 11s	remaining: 7m 56s
6071:	learn: 0.0016545	total: 10m 11s	remaining: 6m 35s
6061:	learn: 0.0015854	total: 10m 11s	remaining: 6m 37s
6173:	learn: 0.0015990	total: 10m 11s	remaining: 6m 18s
5886:	learn: 0.0020585	total: 10m 11s	remaining: 7m 7s
5621:	learn: 0.0016183	total: 10m 11s	remaining: 7m 56s
6062:	learn: 0.0015851	total: 10m 11s	remaining: 6m 37s
6174:	learn: 0.0015986	total: 10m 11s	remaining: 6m 18s
6072:	learn: 0.0016545	total: 10m 11s	remaining: 6m 35s
5622:	learn: 0.0016180	total: 10m 11s	remaining: 7m 56s
5887:	learn: 0.0020585	total: 10m 11s	remaining: 7m 7s
6063:	learn: 0.0015845	total: 10m 11s	remaining: 6m 36s
6175:	learn: 0.0015986	total: 10m 11s	remaining: 6m 18s
6073:	learn: 0.0016540	total: 10m 11s	remaining: 6m 35s
6176:	learn: 0.0015982	total: 10m 11s	remaining: 6m 18s
5623:	learn: 0.0016175	total: 10m 11s	remaining: 7m 56s
6064:	learn: 0.0015845	total: 10m 11s	remaining: 6m 36s
5888:	learn: 0.0020585	total: 10m 11s	remaining: 7m 7s
6074:	learn: 0.0016534	total: 10m 11s	remaining: 6m 35s
5624:	learn: 0.0016174	total: 10m 11s	remaining: 7m 55s
6177:	learn: 0.0015982	total: 10m 11s	remaining: 6m 18s
5889:	learn: 0.0020585	total: 10m 11s	remaining: 7m 6s
6065:	learn: 0.0015841	total: 10m 11s	remaining: 6m 36s

6075:	learn: 0.0016534	total: 10m 11s	remaining: 6m 35s
5625:	learn: 0.0016169	total: 10m 11s	remaining: 7m 55s
6178:	learn: 0.0015978	total: 10m 11s	remaining: 6m 18s
6066:	learn: 0.0015841	total: 10m 11s	remaining: 6m 36s
6076:	learn: 0.0016534	total: 10m 12s	remaining: 6m 35s
5890:	learn: 0.0020585	total: 10m 12s	remaining: 7m 6s
6179:	learn: 0.0015977	total: 10m 12s	remaining: 6m 18s
5626:	learn: 0.0016169	total: 10m 12s	remaining: 7m 55s
6077:	learn: 0.0016534	total: 10m 12s	remaining: 6m 34s
5891:	learn: 0.0020585	total: 10m 12s	remaining: 7m 6s
6067:	learn: 0.0015841	total: 10m 11s	remaining: 6m 36s
6180:	learn: 0.0015978	total: 10m 12s	remaining: 6m 18s
5627:	learn: 0.0016165	total: 10m 12s	remaining: 7m 55s
6078:	learn: 0.0016534	total: 10m 12s	remaining: 6m 34s
5892:	learn: 0.0020585	total: 10m 12s	remaining: 7m 6s
6068:	learn: 0.0015841	total: 10m 12s	remaining: 6m 36s
6181:	learn: 0.0015977	total: 10m 12s	remaining: 6m 18s
6079:	learn: 0.0016534	total: 10m 12s	remaining: 6m 34s
5628:	learn: 0.0016165	total: 10m 12s	remaining: 7m 55s
6069:	learn: 0.0015841	total: 10m 12s	remaining: 6m 36s
5893:	learn: 0.0020585	total: 10m 12s	remaining: 7m 6s
6182:	learn: 0.0015975	total: 10m 12s	remaining: 6m 17s
6080:	learn: 0.0016534	total: 10m 12s	remaining: 6m 34s
5629:	learn: 0.0016165	total: 10m 12s	remaining: 7m 55s
5894:	learn: 0.0020585	total: 10m 12s	remaining: 7m 6s
6070:	learn: 0.0015841	total: 10m 12s	remaining: 6m 36s
6183:	learn: 0.0015972	total: 10m 12s	remaining: 6m 17s
6081:	learn: 0.0016534	total: 10m 12s	remaining: 6m 34s
5895:	learn: 0.0020585	total: 10m 12s	remaining: 7m 6s
6184:	learn: 0.0015968	total: 10m 12s	remaining: 6m 17s
6071:	learn: 0.0015841	total: 10m 12s	remaining: 6m 36s
5630:	learn: 0.0016161	total: 10m 12s	remaining: 7m 55s
5896:	learn: 0.0020578	total: 10m 12s	remaining: 7m 6s
6185:	learn: 0.0015962	total: 10m 12s	remaining: 6m 17s
6072:	learn: 0.0015841	total: 10m 12s	remaining: 6m 36s
6082:	learn: 0.0016534	total: 10m 12s	remaining: 6m 34s
5631:	learn: 0.0016161	total: 10m 12s	remaining: 7m 55s
5897:	learn: 0.0020578	total: 10m 12s	remaining: 7m 6s
6073:	learn: 0.0015836	total: 10m 12s	remaining: 6m 35s
6186:	learn: 0.0015962	total: 10m 12s	remaining: 6m 17s
6083:	learn: 0.0016534	total: 10m 12s	remaining: 6m 34s
6074:	learn: 0.0015836	total: 10m 12s	remaining: 6m 35s
6187:	learn: 0.0015962	total: 10m 12s	remaining: 6m 17s
5898:	learn: 0.0020578	total: 10m 12s	remaining: 7m 6s
5632:	learn: 0.0016161	total: 10m 12s	remaining: 7m 55s
6084:	learn: 0.0016534	total: 10m 12s	remaining: 6m 34s
6075:	learn: 0.0015832	total: 10m 12s	remaining: 6m 35s
5899:	learn: 0.0020578	total: 10m 12s	remaining: 7m 5s
6188:	learn: 0.0015958	total: 10m 12s	remaining: 6m 17s
5633:	learn: 0.0016161	total: 10m 12s	remaining: 7m 54s
6085:	learn: 0.0016534	total: 10m 12s	remaining: 6m 34s
6189:	learn: 0.0015954	total: 10m 12s	remaining: 6m 17s
6076:	learn: 0.0015832	total: 10m 12s	remaining: 6m 35s
5900:	learn: 0.0020578	total: 10m 12s	remaining: 7m 5s
5634:	learn: 0.0016157	total: 10m 13s	remaining: 7m 54s
6086:	learn: 0.0016534	total: 10m 13s	remaining: 6m 34s
6190:	learn: 0.0015949	total: 10m 13s	remaining: 6m 17s
5901:	learn: 0.0020578	total: 10m 13s	remaining: 7m 5s
6077:	learn: 0.0015832	total: 10m 12s	remaining: 6m 35s
5635:	learn: 0.0016157	total: 10m 13s	remaining: 7m 54s
6191:	learn: 0.0015949	total: 10m 13s	remaining: 6m 17s
6087:	learn: 0.0016534	total: 10m 13s	remaining: 6m 33s
5902:	learn: 0.0020578	total: 10m 13s	remaining: 7m 5s
6078:	learn: 0.0015832	total: 10m 13s	remaining: 6m 35s
6088:	learn: 0.0016534	total: 10m 13s	remaining: 6m 33s
6192:	learn: 0.0015946	total: 10m 13s	remaining: 6m 16s
5636:	learn: 0.0016157	total: 10m 13s	remaining: 7m 54s
5903:	learn: 0.0020578	total: 10m 13s	remaining: 7m 5s
6089:	learn: 0.0016534	total: 10m 13s	remaining: 6m 33s
6193:	learn: 0.0015946	total: 10m 13s	remaining: 6m 16s
6079:	learn: 0.0015832	total: 10m 13s	remaining: 6m 35s
5637:	learn: 0.0016158	total: 10m 13s	remaining: 7m 54s
6090:	learn: 0.0016534	total: 10m 13s	remaining: 6m 33s
6194:	learn: 0.0015946	total: 10m 13s	remaining: 6m 16s
5904:	learn: 0.0020578	total: 10m 13s	remaining: 7m 5s
6080:	learn: 0.0015832	total: 10m 13s	remaining: 6m 35s
5638:	learn: 0.0016158	total: 10m 13s	remaining: 7m 54s
6091:	learn: 0.0016534	total: 10m 13s	remaining: 6m 33s
6195:	learn: 0.0015940	total: 10m 13s	remaining: 6m 16s
5905:	learn: 0.0020571	total: 10m 13s	remaining: 7m 5s
6092:	learn: 0.0016534	total: 10m 13s	remaining: 6m 33s
6081:	learn: 0.0015832	total: 10m 13s	remaining: 6m 35s
5639:	learn: 0.0016157	total: 10m 13s	remaining: 7m 54s
6196:	learn: 0.0015940	total: 10m 13s	remaining: 6m 16s
5906:	learn: 0.0020571	total: 10m 13s	remaining: 7m 5s
6093:	learn: 0.0016534	total: 10m 13s	remaining: 6m 33s
6082:	learn: 0.0015827	total: 10m 13s	remaining: 6m 35s
6197:	learn: 0.0015940	total: 10m 13s	remaining: 6m 16s
5640:	learn: 0.0016157	total: 10m 13s	remaining: 7m 54s
5907:	learn: 0.0020571	total: 10m 13s	remaining: 7m 5s
6094:	learn: 0.0016534	total: 10m 13s	remaining: 6m 33s
6198:	learn: 0.0015940	total: 10m 13s	remaining: 6m 16s
5641:	learn: 0.0016157	total: 10m 13s	remaining: 7m 54s
6083:	learn: 0.0015827	total: 10m 13s	remaining: 6m 34s
5908:	learn: 0.0020571	total: 10m 13s	remaining: 7m 4s
6095:	learn: 0.0016534	total: 10m 13s	remaining: 6m 33s
6199:	learn: 0.0015940	total: 10m 13s	remaining: 6m 16s
5642:	learn: 0.0016157	total: 10m 13s	remaining: 7m 53s
6084:	learn: 0.0015822	total: 10m 13s	remaining: 6m 34s
6096:	learn: 0.0016534	total: 10m 13s	remaining: 6m 32s
5909:	learn: 0.0020570	total: 10m 13s	remaining: 7m 4s
6200:	learn: 0.0015940	total: 10m 13s	remaining: 6m 16s
6085:	learn: 0.0015822	total: 10m 13s	remaining: 6m 34s
5643:	learn: 0.0016158	total: 10m 14s	remaining: 7m 53s
6097:	learn: 0.0016534	total: 10m 14s	remaining: 6m 32s
5910:	learn: 0.0020570	total: 10m 14s	remaining: 7m 4s
6201:	learn: 0.0015940	total: 10m 13s	remaining: 6m 15s
6086:	learn: 0.0015822	total: 10m 13s	remaining: 6m 34s
5644:	learn: 0.0016158	total: 10m 14s	remaining: 7m 53s
6098:	learn: 0.0016534	total: 10m 14s	remaining: 6m 32s
6202:	learn: 0.0015940	total: 10m 14s	remaining: 6m 15s
5911:	learn: 0.0020570	total: 10m 14s	remaining: 7m 4s
6099:	learn: 0.0016534	total: 10m 14s	remaining: 6m 32s
6087:	learn: 0.0015822	total: 10m 14s	remaining: 6m 34s
6203:	learn: 0.0015936	total: 10m 14s	remaining: 6m 15s
5645:	learn: 0.0016157	total: 10m 14s	remaining: 7m 53s
5912:	learn: 0.0020570	total: 10m 14s	remaining: 7m 4s
6100:	learn: 0.0016534	total: 10m 14s	remaining: 6m 32s
6088:	learn: 0.0015822	total: 10m 14s	remaining: 6m 34s
6204:	learn: 0.0015930	total: 10m 14s	remaining: 6m 15s
5646:	learn: 0.0016153	total: 10m 14s	remaining: 7m 53s
5913:	learn: 0.0020570	total: 10m 14s	remaining: 7m 4s
6101:	learn: 0.0016534	total: 10m 14s	remaining: 6m 32s
6089:	learn: 0.0015821	total: 10m 14s	remaining: 6m 34s
5914:	learn: 0.0020570	total: 10m 14s	remaining: 7m 4s
6102:	learn: 0.0016532	total: 10m 14s	remaining: 6m 32s
6205:	learn: 0.0015930	total: 10m 14s	remaining: 6m 15s
5647:	learn: 0.0016153	total: 10m 14s	remaining: 7m 53s
6090:	learn: 0.0015820	total: 10m 14s	remaining: 6m 34s
6206:	learn: 0.0015930	total: 10m 14s	remaining: 6m 15s
5915:	learn: 0.0020570	total: 10m 14s	remaining: 7m 4s
5648:	learn: 0.0016149	total: 10m 14s	remaining: 7m 53s
6103:	learn: 0.0016532	total: 10m 14s	remaining: 6m 32s
6091:	learn: 0.0015820	total: 10m 14s	remaining: 6m 34s
5916:	learn: 0.0020570	total: 10m 14s	remaining: 7m 4s
6207:	learn: 0.0015928	total: 10m 14s	remaining: 6m 15s
6104:	learn: 0.0016531	total: 10m 14s	remaining: 6m 32s
5649:	learn: 0.0016149	total: 10m 14s	remaining: 7m 53s
6092:	learn: 0.0015819	total: 10m 14s	remaining: 6m 34s
5917:	learn: 0.0020570	total: 10m 14s	remaining: 7m 3s
6208:	learn: 0.0015928	total: 10m 14s	remaining: 6m 15s
6105:	learn: 0.0016526	total: 10m 14s	remaining: 6m 32s
6093:	learn: 0.0015815	total: 10m 14s	remaining: 6m 33s
5650:	learn: 0.0016149	total: 10m 14s	remaining: 7m 53s
6209:	learn: 0.0015928	total: 10m 14s	remaining: 6m 15s
5918:	learn: 0.0020570	total: 10m 14s	remaining: 7m 3s
6094:	learn: 0.0015815	total: 10m 14s	remaining: 6m 33s
5651:	learn: 0.0016149	total: 10m 14s	remaining: 7m 53s
6210:	learn: 0.0015924	total: 10m 14s	remaining: 6m 15s
5919:	learn: 0.0020570	total: 10m 14s	remaining: 7m 3s
6095:	learn: 0.0015810	total: 10m 14s	remaining: 6m 33s
6107:	learn: 0.0016526	total: 10m 14s	remaining: 6m 31s
5652:	learn: 0.0016149	total: 10m 15s	remaining: 7m 52s
6211:	learn: 0.0015924	total: 10m 14s	remaining: 6m 14s
6108:	learn: 0.0016526	total: 10m 15s	remaining: 6m 31s
5920:	learn: 0.0020570	total: 10m 15s	remaining: 7m 3s
6096:	learn: 0.0015810	total: 10m 14s	remaining: 6m 33s
6212:	learn: 0.0015920	total: 10m 15s	remaining: 6m 14s
5653:	learn: 0.0016149	total: 10m 15s	remaining: 7m 52s
5921:	learn: 0.0020570	total: 10m 15s	remaining: 7m 3s
6109:	learn: 0.0016522	total: 10m 15s	remaining: 6m 31s
6097:	learn: 0.0015805	total: 10m 14s	remaining: 6m 33s
6213:	learn: 0.0015920	total: 10m 15s	remaining: 6m 14s
5922:	learn: 0.0020570	total: 10m 15s	remaining: 7m 3s
6110:	learn: 0.0016521	total: 10m 15s	remaining: 6m 31s
5654:	learn: 0.0016149	total: 10m 15s	remaining: 7m 52s
6098:	learn: 0.0015805	total: 10m 15s	remaining: 6m 33s
6214:	learn: 0.0015920	total: 10m 15s	remaining: 6m 14s
5655:	learn: 0.0016149	total: 10m 15s	remaining: 7m 52s
5923:	learn: 0.0020570	total: 10m 15s	remaining: 7m 3s
6111:	learn: 0.0016521	total: 10m 15s	remaining: 6m 31s
6099:	learn: 0.0015800	total: 10m 15s	remaining: 6m 33s
6215:	learn: 0.0015920	total: 10m 15s	remaining: 6m 14s
5656:	learn: 0.0016149	total: 10m 15s	remaining: 7m 52s
6112:	learn: 0.0016521	total: 10m 15s	remaining: 6m 31s
5924:	learn: 0.0020570	total: 10m 15s	remaining: 7m 3s
6100:	learn: 0.0015800	total: 10m 15s	remaining: 6m 33s
6113:	learn: 0.0016521	total: 10m 15s	remaining: 6m 31s
6216:	learn: 0.0015920	total: 10m 15s	remaining: 6m 14s
5657:	learn: 0.0016149	total: 10m 15s	remaining: 7m 52s
5925:	learn: 0.0020570	total: 10m 15s	remaining: 7m 3s
6101:	learn: 0.0015800	total: 10m 15s	remaining: 6m 33s
6217:	learn: 0.0015920	total: 10m 15s	remaining: 6m 14s
6114:	learn: 0.0016521	total: 10m 15s	remaining: 6m 31s
5926:	learn: 0.0020570	total: 10m 15s	remaining: 7m 3s
5658:	learn: 0.0016148	total: 10m 15s	remaining: 7m 52s
6102:	learn: 0.0015800	total: 10m 15s	remaining: 6m 33s
6218:	learn: 0.0015916	total: 10m 15s	remaining: 6m 14s
5927:	learn: 0.0020570	total: 10m 15s	remaining: 7m 2s
6115:	learn: 0.0016521	total: 10m 15s	remaining: 6m 31s
5659:	learn: 0.0016148	total: 10m 15s	remaining: 7m 52s
6103:	learn: 0.0015800	total: 10m 15s	remaining: 6m 32s
5928:	learn: 0.0020570	total: 10m 15s	remaining: 7m 2s
6219:	learn: 0.0015916	total: 10m 15s	remaining: 6m 14s
5660:	learn: 0.0016143	total: 10m 15s	remaining: 7m 52s
6116:	learn: 0.0016520	total: 10m 15s	remaining: 6m 30s
6104:	learn: 0.0015799	total: 10m 15s	remaining: 6m 32s
5929:	learn: 0.0020570	total: 10m 15s	remaining: 7m 2s
5661:	learn: 0.0016143	total: 10m 15s	remaining: 7m 51s
6220:	learn: 0.0015913	total: 10m 15s	remaining: 6m 14s
5930:	learn: 0.0020570	total: 10m 15s	remaining: 7m 2s
6105:	learn: 0.0015793	total: 10m 15s	remaining: 6m 32s
6117:	learn: 0.0016521	total: 10m 15s	remaining: 6m 30s
5662:	learn: 0.0016143	total: 10m 16s	remaining: 7m 51s
6221:	learn: 0.0015907	total: 10m 15s	remaining: 6m 14s
5931:	learn: 0.0020570	total: 10m 16s	remaining: 7m 2s
6106:	learn: 0.0015794	total: 10m 15s	remaining: 6m 32s
6118:	learn: 0.0016521	total: 10m 16s	remaining: 6m 30s
5663:	learn: 0.0016143	total: 10m 16s	remaining: 7m 51s
6222:	learn: 0.0015907	total: 10m 16s	remaining: 6m 13s
5932:	learn: 0.0020570	total: 10m 16s	remaining: 7m 2s
6107:	learn: 0.0015794	total: 10m 15s	remaining: 6m 32s
5664:	learn: 0.0016139	total: 10m 16s	remaining: 7m 51s
6119:	learn: 0.0016521	total: 10m 16s	remaining: 6m 30s
6223:	learn: 0.0015907	total: 10m 16s	remaining: 6m 13s
6108:	learn: 0.0015793	total: 10m 16s	remaining: 6m 32s
5933:	learn: 0.0020569	total: 10m 16s	remaining: 7m 2s
5665:	learn: 0.0016134	total: 10m 16s	remaining: 7m 51s
6120:	learn: 0.0016520	total: 10m 16s	remaining: 6m 30s
6224:	learn: 0.0015907	total: 10m 16s	remaining: 6m 13s
6109:	learn: 0.0015793	total: 10m 16s	remaining: 6m 32s
5934:	learn: 0.0020562	total: 10m 16s	remaining: 7m 2s
6121:	learn: 0.0016520	total: 10m 16s	remaining: 6m 30s
5666:	learn: 0.0016134	total: 10m 16s	remaining: 7m 51s
6110:	learn: 0.0015793	total: 10m 16s	remaining: 6m 32s
6225:	learn: 0.0015903	total: 10m 16s	remaining: 6m 13s
5935:	learn: 0.0020562	total: 10m 16s	remaining: 7m 2s
6122:	learn: 0.0016520	total: 10m 16s	remaining: 6m 30s
5667:	learn: 0.0016134	total: 10m 16s	remaining: 7m 51s
6111:	learn: 0.0015789	total: 10m 16s	remaining: 6m 32s
5936:	learn: 0.0020562	total: 10m 16s	remaining: 7m 1s
6226:	learn: 0.0015899	total: 10m 16s	remaining: 6m 13s
6123:	learn: 0.0016520	total: 10m 16s	remaining: 6m 30s
6112:	learn: 0.0015789	total: 10m 16s	remaining: 6m 31s
5668:	learn: 0.0016134	total: 10m 16s	remaining: 7m 51s
6227:	learn: 0.0015899	total: 10m 16s	remaining: 6m 13s
5937:	learn: 0.0020554	total: 10m 16s	remaining: 7m 1s
6124:	learn: 0.0016520	total: 10m 16s	remaining: 6m 30s
6113:	learn: 0.0015789	total: 10m 16s	remaining: 6m 31s
5669:	learn: 0.0016134	total: 10m 16s	remaining: 7m 50s
6228:	learn: 0.0015899	total: 10m 16s	remaining: 6m 13s
6125:	learn: 0.0016520	total: 10m 16s	remaining: 6m 30s
5938:	learn: 0.0020554	total: 10m 16s	remaining: 7m 1s
6114:	learn: 0.0015789	total: 10m 16s	remaining: 6m 31s
5670:	learn: 0.0016134	total: 10m 16s	remaining: 7m 50s
6126:	learn: 0.0016513	total: 10m 16s	remaining: 6m 29s
6229:	learn: 0.0015899	total: 10m 16s	remaining: 6m 13s
5939:	learn: 0.0020554	total: 10m 16s	remaining: 7m 1s
6115:	learn: 0.0015789	total: 10m 16s	remaining: 6m 31s
5671:	learn: 0.0016134	total: 10m 16s	remaining: 7m 50s
6230:	learn: 0.0015899	total: 10m 16s	remaining: 6m 13s
6127:	learn: 0.0016513	total: 10m 16s	remaining: 6m 29s
6116:	learn: 0.0015788	total: 10m 16s	remaining: 6m 31s
5940:	learn: 0.0020554	total: 10m 16s	remaining: 7m 1s
6231:	learn: 0.0015899	total: 10m 16s	remaining: 6m 13s
5672:	learn: 0.0016134	total: 10m 17s	remaining: 7m 50s
6128:	learn: 0.0016508	total: 10m 17s	remaining: 6m 29s
5941:	learn: 0.0020554	total: 10m 17s	remaining: 7m 1s
6232:	learn: 0.0015899	total: 10m 17s	remaining: 6m 12s
6117:	learn: 0.0015788	total: 10m 16s	remaining: 6m 31s
5673:	learn: 0.0016128	total: 10m 17s	remaining: 7m 50s
6118:	learn: 0.0015788	total: 10m 16s	remaining: 6m 31s
6233:	learn: 0.0015896	total: 10m 17s	remaining: 6m 12s
6129:	learn: 0.0016509	total: 10m 17s	remaining: 6m 29s
5942:	learn: 0.0020554	total: 10m 17s	remaining: 7m 1s
5674:	learn: 0.0016128	total: 10m 17s	remaining: 7m 50s
6119:	learn: 0.0015785	total: 10m 17s	remaining: 6m 31s
6234:	learn: 0.0015892	total: 10m 17s	remaining: 6m 12s
6130:	learn: 0.0016509	total: 10m 17s	remaining: 6m 29s
5943:	learn: 0.0020554	total: 10m 17s	remaining: 7m 1s
5675:	learn: 0.0016123	total: 10m 17s	remaining: 7m 50s
6120:	learn: 0.0015782	total: 10m 17s	remaining: 6m 31s
6235:	learn: 0.0015892	total: 10m 17s	remaining: 6m 12s
6131:	learn: 0.0016509	total: 10m 17s	remaining: 6m 29s
5676:	learn: 0.0016123	total: 10m 17s	remaining: 7m 50s
5944:	learn: 0.0020554	total: 10m 17s	remaining: 7m 1s
6132:	learn: 0.0016503	total: 10m 17s	remaining: 6m 29s
6121:	learn: 0.0015782	total: 10m 17s	remaining: 6m 31s
6236:	learn: 0.0015892	total: 10m 17s	remaining: 6m 12s
5677:	learn: 0.0016123	total: 10m 17s	remaining: 7m 50s
5945:	learn: 0.0020554	total: 10m 17s	remaining: 7m 1s
6122:	learn: 0.0015776	total: 10m 17s	remaining: 6m 30s
6237:	learn: 0.0015892	total: 10m 17s	remaining: 6m 12s
6133:	learn: 0.0016503	total: 10m 17s	remaining: 6m 29s
5678:	learn: 0.0016123	total: 10m 17s	remaining: 7m 49s
6123:	learn: 0.0015776	total: 10m 17s	remaining: 6m 30s
6238:	learn: 0.0015892	total: 10m 17s	remaining: 6m 12s
5946:	learn: 0.0020554	total: 10m 17s	remaining: 7m
6134:	learn: 0.0016497	total: 10m 17s	remaining: 6m 29s
5679:	learn: 0.0016123	total: 10m 17s	remaining: 7m 49s
6239:	learn: 0.0015892	total: 10m 17s	remaining: 6m 12s
5s

5918:	learn: 0.0020570	total: 10m 14s	remaining: 7m 36124:	learn: 0.0015776	total: 10m 17s	remaining: 6m 30s
6135:	learn: 0.0016497	total: 10m 17s	remaining: 6m 29s
5947:	learn: 0.0020554	total: 10m 17s	remaining: 7m
6240:	learn: 0.0015892	total: 10m 17s	remaining: 6m 12s
5680:	learn: 0.0016119	total: 10m 17s	remaining: 7m 49s
5948:	learn: 0.0020554	total: 10m 17s	remaining: 7m
6125:	learn: 0.0015776	total: 10m 17s	remaining: 6m 30s
6136:	learn: 0.0016491	total: 10m 17s	remaining: 6m 28s
6241:	learn: 0.0015892	total: 10m 17s	remaining: 6m 11s
5681:	learn: 0.0016114	total: 10m 17s	remaining: 7m 49s
6137:	learn: 0.0016486	total: 10m 17s	remaining: 6m 28s
6126:	learn: 0.0015776	total: 10m 17s	remaining: 6m 30s
5949:	learn: 0.0020554	total: 10m 18s	remaining: 7m
6242:	learn: 0.0015889	total: 10m 17s	remaining: 6m 11s
5682:	learn: 0.0016114	total: 10m 18s	remaining: 7m 49s
6138:	learn: 0.0016481	total: 10m 18s	remaining: 6m 28s
6127:	learn: 0.0015776	total: 10m 17s	remaining: 6m 30s
5950:	learn: 0.0020554	total: 10m 18s	remaining: 7m
6243:	learn: 0.0015889	total: 10m 18s	remaining: 6m 11s
6139:	learn: 0.0016476	total: 10m 18s	remaining: 6m 28s
5683:	learn: 0.0016114	total: 10m 18s	remaining: 7m 49s
6128:	learn: 0.0015776	total: 10m 18s	remaining: 6m 30s
6244:	learn: 0.0015886	total: 10m 18s	remaining: 6m 11s
5951:	learn: 0.0020554	total: 10m 18s	remaining: 7m
6140:	learn: 0.0016476	total: 10m 18s	remaining: 6m 28s
6245:	learn: 0.0015886	total: 10m 18s	remaining: 6m 11s
5684:	learn: 0.0016114	total: 10m 18s	remaining: 7m 49s
6129:	learn: 0.0015770	total: 10m 18s	remaining: 6m 30s
5952:	learn: 0.0020554	total: 10m 18s	remaining: 7m
6141:	learn: 0.0016476	total: 10m 18s	remaining: 6m 28s
5685:	learn: 0.0016114	total: 10m 18s	remaining: 7m 49s
6130:	learn: 0.0015770	total: 10m 18s	remaining: 6m 30s
6246:	learn: 0.0015882	total: 10m 18s	remaining: 6m 11s
5953:	learn: 0.0020554	total: 10m 18s	remaining: 7m
6142:	learn: 0.0016471	total: 10m 18s	remaining: 6m 28s
6247:	learn: 0.0015877	total: 10m 18s	remaining: 6m 11s
5686:	learn: 0.0016109	total: 10m 18s	remaining: 7m 49s
6131:	learn: 0.0015770	total: 10m 18s	remaining: 6m 30s
5954:	learn: 0.0020554	total: 10m 18s	remaining: 7m
6143:	learn: 0.0016470	total: 10m 18s	remaining: 6m 28s
5687:	learn: 0.0016110	total: 10m 18s	remaining: 7m 48s
6248:	learn: 0.0015871	total: 10m 18s	remaining: 6m 11s
6132:	learn: 0.0015770	total: 10m 18s	remaining: 6m 29s
5955:	learn: 0.0020554	total: 10m 18s	remaining: 7m
6249:	learn: 0.0015871	total: 10m 18s	remaining: 6m 11s
6144:	learn: 0.0016470	total: 10m 18s	remaining: 6m 28s
5688:	learn: 0.0016110	total: 10m 18s	remaining: 7m 48s
6133:	learn: 0.0015770	total: 10m 18s	remaining: 6m 29s
5956:	learn: 0.0020554	total: 10m 18s	remaining: 6m 59s
6250:	learn: 0.0015866	total: 10m 18s	remaining: 6m 11s
6145:	learn: 0.0016470	total: 10m 18s	remaining: 6m 28s
6134:	learn: 0.0015767	total: 10m 18s	remaining: 6m 29s
5689:	learn: 0.0016110	total: 10m 18s	remaining: 7m 48s
6251:	learn: 0.0015861	total: 10m 18s	remaining: 6m 10s
6135:	learn: 0.0015767	total: 10m 18s	remaining: 6m 29s
6146:	learn: 0.0016463	total: 10m 18s	remaining: 6m 27s
5957:	learn: 0.0020554	total: 10m 18s	remaining: 6m 59s
5690:	learn: 0.0016106	total: 10m 18s	remaining: 7m 48s
6252:	learn: 0.0015861	total: 10m 18s	remaining: 6m 10s
5691:	learn: 0.0016106	total: 10m 18s	remaining: 7m 48s
6136:	learn: 0.0015767	total: 10m 18s	remaining: 6m 29s
5958:	learn: 0.0020554	total: 10m 18s	remaining: 6m 59s
6147:	learn: 0.0016463	total: 10m 18s	remaining: 6m 27s
6253:	learn: 0.0015855	total: 10m 18s	remaining: 6m 10s
6137:	learn: 0.0015767	total: 10m 18s	remaining: 6m 29s
5959:	learn: 0.0020554	total: 10m 19s	remaining: 6m 59s
6148:	learn: 0.0016463	total: 10m 19s	remaining: 6m 27s
5692:	learn: 0.0016106	total: 10m 19s	remaining: 7m 48s
6254:	learn: 0.0015855	total: 10m 19s	remaining: 6m 10s
5960:	learn: 0.0020554	total: 10m 19s	remaining: 6m 59s
5693:	learn: 0.0016106	total: 10m 19s	remaining: 7m 48s
6138:	learn: 0.0015767	total: 10m 19s	remaining: 6m 29s
6149:	learn: 0.0016463	total: 10m 19s	remaining: 6m 27s
6255:	learn: 0.0015855	total: 10m 19s	remaining: 6m 10s
5961:	learn: 0.0020554	total: 10m 19s	remaining: 6m 59s
6139:	learn: 0.0015766	total: 10m 19s	remaining: 6m 29s
5694:	learn: 0.0016106	total: 10m 19s	remaining: 7m 48s
6150:	learn: 0.0016458	total: 10m 19s	remaining: 6m 27s
6256:	learn: 0.0015851	total: 10m 19s	remaining: 6m 10s
5962:	learn: 0.0020554	total: 10m 19s	remaining: 6m 59s
6140:	learn: 0.0015763	total: 10m 19s	remaining: 6m 29s
5695:	learn: 0.0016106	total: 10m 19s	remaining: 7m 48s
6151:	learn: 0.0016458	total: 10m 19s	remaining: 6m 27s
6257:	learn: 0.0015851	total: 10m 19s	remaining: 6m 10s
5963:	learn: 0.0020554	total: 10m 19s	remaining: 6m 59s
6141:	learn: 0.0015763	total: 10m 19s	remaining: 6m 28s
5696:	learn: 0.0016101	total: 10m 19s	remaining: 7m 47s
6258:	learn: 0.0015845	total: 10m 19s	remaining: 6m 10s
6152:	learn: 0.0016457	total: 10m 19s	remaining: 6m 27s
6142:	learn: 0.0015763	total: 10m 19s	remaining: 6m 28s
5964:	learn: 0.0020554	total: 10m 19s	remaining: 6m 59s
5697:	learn: 0.0016101	total: 10m 19s	remaining: 7m 47s
6153:	learn: 0.0016457	total: 10m 19s	remaining: 6m 27s
6259:	learn: 0.0015845	total: 10m 19s	remaining: 6m 10s
5965:	learn: 0.0020554	total: 10m 19s	remaining: 6m 58s
6143:	learn: 0.0015763	total: 10m 19s	remaining: 6m 28s
6154:	learn: 0.0016457	total: 10m 19s	remaining: 6m 27s
5698:	learn: 0.0016097	total: 10m 19s	remaining: 7m 47s
6144:	learn: 0.0015760	total: 10m 19s	remaining: 6m 28s
6260:	learn: 0.0015841	total: 10m 19s	remaining: 6m 10s
5966:	learn: 0.0020554	total: 10m 19s	remaining: 6m 58s
6155:	learn: 0.0016457	total: 10m 19s	remaining: 6m 27s
6145:	learn: 0.0015759	total: 10m 19s	remaining: 6m 28s
6261:	learn: 0.0015835	total: 10m 19s	remaining: 6m 9s
5699:	learn: 0.0016097	total: 10m 19s	remaining: 7m 47s
6156:	learn: 0.0016457	total: 10m 19s	remaining: 6m 26s
5967:	learn: 0.0020554	total: 10m 19s	remaining: 6m 58s
6146:	learn: 0.0015759	total: 10m 19s	remaining: 6m 28s
6262:	learn: 0.0015835	total: 10m 19s	remaining: 6m 9s
5700:	learn: 0.0016094	total: 10m 20s	remaining: 7m 47s
6157:	learn: 0.0016457	total: 10m 19s	remaining: 6m 26s
6147:	learn: 0.0015759	total: 10m 19s	remaining: 6m 28s
5968:	learn: 0.0020554	total: 10m 20s	remaining: 6m 58s
6263:	learn: 0.0015835	total: 10m 19s	remaining: 6m 9s
6148:	learn: 0.0015755	total: 10m 19s	remaining: 6m 28s
6158:	learn: 0.0016457	total: 10m 20s	remaining: 6m 26s
5701:	learn: 0.0016094	total: 10m 20s	remaining: 7m 47s
6264:	learn: 0.0015835	total: 10m 20s	remaining: 6m 9s
5969:	learn: 0.0020554	total: 10m 20s	remaining: 6m 58s
6149:	learn: 0.0015752	total: 10m 19s	remaining: 6m 28s
6159:	learn: 0.0016457	total: 10m 20s	remaining: 6m 26s
6265:	learn: 0.0015835	total: 10m 20s	remaining: 6m 9s
5702:	learn: 0.0016088	total: 10m 20s	remaining: 7m 47s
6150:	learn: 0.0015752	total: 10m 20s	remaining: 6m 28s
5970:	learn: 0.0020554	total: 10m 20s	remaining: 6m 58s
6160:	learn: 0.0016457	total: 10m 20s	remaining: 6m 26s
6266:	learn: 0.0015835	total: 10m 20s	remaining: 6m 9s
6151:	learn: 0.0015752	total: 10m 20s	remaining: 6m 27s
5703:	learn: 0.0016088	total: 10m 20s	remaining: 7m 47s
6161:	learn: 0.0016455	total: 10m 20s	remaining: 6m 26s
6267:	learn: 0.0015835	total: 10m 20s	remaining: 6m 9s
5971:	learn: 0.0020554	total: 10m 20s	remaining: 6m 58s
6162:	learn: 0.0016455	total: 10m 20s	remaining: 6m 26s
5704:	learn: 0.0016084	total: 10m 20s	remaining: 7m 47s
6152:	learn: 0.0015750	total: 10m 20s	remaining: 6m 27s
6268:	learn: 0.0015835	total: 10m 20s	remaining: 6m 9s
5972:	learn: 0.0020554	total: 10m 20s	remaining: 6m 58s
6153:	learn: 0.0015750	total: 10m 20s	remaining: 6m 27s
6163:	learn: 0.0016455	total: 10m 20s	remaining: 6m 26s
5705:	learn: 0.0016081	total: 10m 20s	remaining: 7m 47s
5973:	learn: 0.0020554	total: 10m 20s	remaining: 6m 58s
6269:	learn: 0.0015830	total: 10m 20s	remaining: 6m 9s
6154:	learn: 0.0015750	total: 10m 20s	remaining: 6m 27s
6164:	learn: 0.0016455	total: 10m 20s	remaining: 6m 26s
5706:	learn: 0.0016081	total: 10m 20s	remaining: 7m 46s
6270:	learn: 0.0015830	total: 10m 20s	remaining: 6m 9s
6155:	learn: 0.0015750	total: 10m 20s	remaining: 6m 27s

5974:	learn: 0.0020554	total: 10m 20s	remaining: 6m 58s
6165:	learn: 0.0016455	total: 10m 20s	remaining: 6m 25s
5707:	learn: 0.0016081	total: 10m 20s	remaining: 7m 46s
6271:	learn: 0.0015830	total: 10m 20s	remaining: 6m 8s
5975:	learn: 0.0020554	total: 10m 20s	remaining: 6m 58s
6156:	learn: 0.0015750	total: 10m 20s	remaining: 6m 27s
6166:	learn: 0.0016455	total: 10m 20s	remaining: 6m 25s
5708:	learn: 0.0016081	total: 10m 20s	remaining: 7m 46s
6272:	learn: 0.0015830	total: 10m 20s	remaining: 6m 8s
5709:	learn: 0.0016076	total: 10m 20s	remaining: 7m 46s
5976:	learn: 0.0020554	total: 10m 20s	remaining: 6m 57s
6167:	learn: 0.0016451	total: 10m 20s	remaining: 6m 25s
6157:	learn: 0.0015749	total: 10m 20s	remaining: 6m 27s
6273:	learn: 0.0015830	total: 10m 20s	remaining: 6m 8s
5710:	learn: 0.0016076	total: 10m 21s	remaining: 7m 46s
5977:	learn: 0.0020554	total: 10m 21s	remaining: 6m 57s
6158:	learn: 0.0015749	total: 10m 20s	remaining: 6m 27s
6168:	learn: 0.0016451	total: 10m 21s	remaining: 6m 25s
6274:	learn: 0.0015830	total: 10m 20s	remaining: 6m 8s
5978:	learn: 0.0020554	total: 10m 21s	remaining: 6m 57s
5711:	learn: 0.0016076	total: 10m 21s	remaining: 7m 46s
6159:	learn: 0.0015750	total: 10m 20s	remaining: 6m 27s
6169:	learn: 0.0016451	total: 10m 21s	remaining: 6m 25s
6275:	learn: 0.0015829	total: 10m 21s	remaining: 6m 8s
5979:	learn: 0.0020554	total: 10m 21s	remaining: 6m 57s
6170:	learn: 0.0016451	total: 10m 21s	remaining: 6m 25s
6276:	learn: 0.0015829	total: 10m 21s	remaining: 6m 8s
6160:	learn: 0.0015750	total: 10m 21s	remaining: 6m 26s
5712:	learn: 0.0016076	total: 10m 21s	remaining: 7m 46s
5980:	learn: 0.0020554	total: 10m 21s	remaining: 6m 57s
6277:	learn: 0.0015828	total: 10m 21s	remaining: 6m 8s
6161:	learn: 0.0015749	total: 10m 21s	remaining: 6m 26s
6171:	learn: 0.0016451	total: 10m 21s	remaining: 6m 25s
5981:	learn: 0.0020554	total: 10m 21s	remaining: 6m 57s
6278:	learn: 0.0015828	total: 10m 21s	remaining: 6m 8s
5713:	learn: 0.0016070	total: 10m 21s	remaining: 7m 46s
6162:	learn: 0.0015749	total: 10m 21s	remaining: 6m 26s
6172:	learn: 0.0016448	total: 10m 21s	remaining: 6m 25s
5982:	learn: 0.0020554	total: 10m 21s	remaining: 6m 57s
6163:	learn: 0.0015744	total: 10m 21s	remaining: 6m 26s
5714:	learn: 0.0016070	total: 10m 21s	remaining: 7m 46s
6279:	learn: 0.0015823	total: 10m 21s	remaining: 6m 8s
6173:	learn: 0.0016441	total: 10m 21s	remaining: 6m 25s
5983:	learn: 0.0020554	total: 10m 21s	remaining: 6m 57s
5715:	learn: 0.0016070	total: 10m 21s	remaining: 7m 45s
6164:	learn: 0.0015744	total: 10m 21s	remaining: 6m 26s
6280:	learn: 0.0015818	total: 10m 21s	remaining: 6m 8s
6174:	learn: 0.0016439	total: 10m 21s	remaining: 6m 25s
5984:	learn: 0.0020554	total: 10m 21s	remaining: 6m 57s
5716:	learn: 0.0016069	total: 10m 21s	remaining: 7m 45s
6165:	learn: 0.0015739	total: 10m 21s	remaining: 6m 26s
6281:	learn: 0.0015812	total: 10m 21s	remaining: 6m 7s
6175:	learn: 0.0016439	total: 10m 21s	remaining: 6m 24s
5985:	learn: 0.0020554	total: 10m 21s	remaining: 6m 56s
5986:	learn: 0.0020554	total: 10m 21s	remaining: 6m 56s
5717:	learn: 0.0016070	total: 10m 21s	remaining: 7m 45s
6166:	learn: 0.0015739	total: 10m 21s	remaining: 6m 26s
6282:	learn: 0.0015807	total: 10m 21s	remaining: 6m 7s
6176:	learn: 0.0016439	total: 10m 21s	remaining: 6m 24s
6283:	learn: 0.0015802	total: 10m 21s	remaining: 6m 7s
5987:	learn: 0.0020554	total: 10m 21s	remaining: 6m 56s
6167:	learn: 0.0015739	total: 10m 21s	remaining: 6m 26s
5718:	learn: 0.0016069	total: 10m 21s	remaining: 7m 45s
6177:	learn: 0.0016434	total: 10m 21s	remaining: 6m 24s
6284:	learn: 0.0015796	total: 10m 21s	remaining: 6m 7s
5988:	learn: 0.0020554	total: 10m 22s	remaining: 6m 56s
6178:	learn: 0.0016434	total: 10m 22s	remaining: 6m 24s
6168:	learn: 0.0015735	total: 10m 21s	remaining: 6m 26s
6285:	learn: 0.0015796	total: 10m 22s	remaining: 6m 7s
5719:	learn: 0.0016070	total: 10m 22s	remaining: 7m 45s
5989:	learn: 0.0020554	total: 10m 22s	remaining: 6m 56s
6179:	learn: 0.0016434	total: 10m 22s	remaining: 6m 24s
6169:	learn: 0.0015735	total: 10m 21s	remaining: 6m 26s
6286:	learn: 0.0015793	total: 10m 22s	remaining: 6m 7s
5990:	learn: 0.0020554	total: 10m 22s	remaining: 6m 56s
5720:	learn: 0.0016070	total: 10m 22s	remaining: 7m 45s
6170:	learn: 0.0015734	total: 10m 22s	remaining: 6m 25s
6180:	learn: 0.0016434	total: 10m 22s	remaining: 6m 24s
5991:	learn: 0.0020554	total: 10m 22s	remaining: 6m 56s
6287:	learn: 0.0015792	total: 10m 22s	remaining: 6m 7s
5721:	learn: 0.0016065	total: 10m 22s	remaining: 7m 45s
6181:	learn: 0.0016434	total: 10m 22s	remaining: 6m 24s
5992:	learn: 0.0020554	total: 10m 22s	remaining: 6m 56s
6171:	learn: 0.0015731	total: 10m 22s	remaining: 6m 25s
6288:	learn: 0.0015787	total: 10m 22s	remaining: 6m 7s
5722:	learn: 0.0016060	total: 10m 22s	remaining: 7m 45s
6182:	learn: 0.0016434	total: 10m 22s	remaining: 6m 24s
5993:	learn: 0.0020554	total: 10m 22s	remaining: 6m 56s
6172:	learn: 0.0015731	total: 10m 22s	remaining: 6m 25s
6289:	learn: 0.0015782	total: 10m 22s	remaining: 6m 7s
6183:	learn: 0.0016434	total: 10m 22s	remaining: 6m 24s
5723:	learn: 0.0016060	total: 10m 22s	remaining: 7m 45s
5994:	learn: 0.0020554	total: 10m 22s	remaining: 6m 55s
6173:	learn: 0.0015730	total: 10m 22s	remaining: 6m 25s
6290:	learn: 0.0015775	total: 10m 22s	remaining: 6m 7s
6184:	learn: 0.0016434	total: 10m 22s	remaining: 6m 24s
5995:	learn: 0.0020554	total: 10m 22s	remaining: 6m 55s
5724:	learn: 0.0016060	total: 10m 22s	remaining: 7m 44s
6174:	learn: 0.0015730	total: 10m 22s	remaining: 6m 25s
6291:	learn: 0.0015775	total: 10m 22s	remaining: 6m 6s
6185:	learn: 0.0016434	total: 10m 22s	remaining: 6m 23s
5996:	learn: 0.0020554	total: 10m 22s	remaining: 6m 55s
5725:	learn: 0.0016060	total: 10m 22s	remaining: 7m 44s
6175:	learn: 0.0015730	total: 10m 22s	remaining: 6m 25s
6292:	learn: 0.0015774	total: 10m 22s	remaining: 6m 6s
6186:	learn: 0.0016434	total: 10m 22s	remaining: 6m 23s
5997:	learn: 0.0020554	total: 10m 22s	remaining: 6m 55s
6176:	learn: 0.0015730	total: 10m 22s	remaining: 6m 25s
6187:	learn: 0.0016432	total: 10m 22s	remaining: 6m 23s
6293:	learn: 0.0015767	total: 10m 22s	remaining: 6m 6s
5726:	learn: 0.0016060	total: 10m 22s	remaining: 7m 44s
5998:	learn: 0.0020554	total: 10m 22s	remaining: 6m 55s
6177:	learn: 0.0015730	total: 10m 22s	remaining: 6m 25s
6188:	learn: 0.0016432	total: 10m 22s	remaining: 6m 23s
6294:	learn: 0.0015767	total: 10m 22s	remaining: 6m 6s
5727:	learn: 0.0016060	total: 10m 23s	remaining: 7m 44s
5999:	learn: 0.0020554	total: 10m 23s	remaining: 6m 55s
6178:	learn: 0.0015725	total: 10m 22s	remaining: 6m 25s
6295:	learn: 0.0015767	total: 10m 23s	remaining: 6m 6s
6189:	learn: 0.0016432	total: 10m 23s	remaining: 6m 23s
5728:	learn: 0.0016057	total: 10m 23s	remaining: 7m 44s
6000:	learn: 0.0020554	total: 10m 23s	remaining: 6m 55s
6179:	learn: 0.0015725	total: 10m 22s	remaining: 6m 25s
6296:	learn: 0.0015767	total: 10m 23s	remaining: 6m 6s
6190:	learn: 0.0016432	total: 10m 23s	remaining: 6m 23s
5729:	learn: 0.0016051	total: 10m 23s	remaining: 7m 44s
6297:	learn: 0.0015767	total: 10m 23s	remaining: 6m 6s
6001:	learn: 0.0020545	total: 10m 23s	remaining: 6m 55s
6180:	learn: 0.0015721	total: 10m 23s	remaining: 6m 24s
6191:	learn: 0.0016432	total: 10m 23s	remaining: 6m 23s
5730:	learn: 0.0016052	total: 10m 23s	remaining: 7m 44s
6002:	learn: 0.0020545	total: 10m 23s	remaining: 6m 55s
6181:	learn: 0.0015721	total: 10m 23s	remaining: 6m 24s
6298:	learn: 0.0015767	total: 10m 23s	remaining: 6m 6s
6192:	learn: 0.0016428	total: 10m 23s	remaining: 6m 23s
6003:	learn: 0.0020545	total: 10m 23s	remaining: 6m 54s
5731:	learn: 0.0016052	total: 10m 23s	remaining: 7m 44s
6182:	learn: 0.0015721	total: 10m 23s	remaining: 6m 24s
6193:	learn: 0.0016428	total: 10m 23s	remaining: 6m 23s
6004:	learn: 0.0020545	total: 10m 23s	remaining: 6m 54s
6299:	learn: 0.0015767	total: 10m 23s	remaining: 6m 6s
5732:	learn: 0.0016052	total: 10m 23s	remaining: 7m 44s
6194:	learn: 0.0016428	total: 10m 23s	remaining: 6m 22s
6183:	learn: 0.0015716	total: 10m 23s	remaining: 6m 24s
6005:	learn: 0.0020545	total: 10m 23s	remaining: 6m 54s
6300:	learn: 0.0015761	total: 10m 23s	remaining: 6m 6s
5733:	learn: 0.0016051	total: 10m 23s	remaining: 7m 43s
6195:	learn: 0.0016428	total: 10m 23s	remaining: 6m 22s
6184:	learn: 0.0015716	total: 10m 23s	remaining: 6m 24s
6006:	learn: 0.0020545	total: 10m 23s	remaining: 6m 54s
6301:	learn: 0.0015762	total: 10m 23s	remaining: 6m 5s
6196:	learn: 0.0016422	total: 10m 23s	remaining: 6m 22s
6185:	learn: 0.0015716	total: 10m 23s	remaining: 6m 24s
5734:	learn: 0.0016051	total: 10m 23s	remaining: 7m 43s
6007:	learn: 0.0020545	total: 10m 23s	remaining: 6m 54s
6302:	learn: 0.0015762	total: 10m 23s	remaining: 6m 5s
6197:	learn: 0.0016418	total: 10m 23s	remaining: 6m 22s
6186:	learn: 0.0015712	total: 10m 23s	remaining: 6m 24s
5735:	learn: 0.0016051	total: 10m 23s	remaining: 7m 43s
6303:	learn: 0.0015758	total: 10m 23s	remaining: 6m 5s
6198:	learn: 0.0016418	total: 10m 23s	remaining: 6m 22s
6008:	learn: 0.0020545	total: 10m 23s	remaining: 6m 54s
6187:	learn: 0.0015712	total: 10m 23s	remaining: 6m 24s
6304:	learn: 0.0015757	total: 10m 23s	remaining: 6m 5s
5736:	learn: 0.0016052	total: 10m 24s	remaining: 7m 43s
6199:	learn: 0.0016418	total: 10m 24s	remaining: 6m 22s
6009:	learn: 0.0020545	total: 10m 24s	remaining: 6m 54s
6188:	learn: 0.0015712	total: 10m 23s	remaining: 6m 24s
6200:	learn: 0.0016418	total: 10m 24s	remaining: 6m 22s
6305:	learn: 0.0015758	total: 10m 24s	remaining: 6m 5s
5737:	learn: 0.0016051	total: 10m 24s	remaining: 7m 43s
6189:	learn: 0.0015712	total: 10m 23s	remaining: 6m 24s
6201:	learn: 0.0016418	total: 10m 24s	remaining: 6m 22s
6306:	learn: 0.0015757	total: 10m 24s	remaining: 6m 5s
6010:	learn: 0.0020545	total: 10m 24s	remaining: 6m 54s
5738:	learn: 0.0016052	total: 10m 24s	remaining: 7m 43s
6190:	learn: 0.0015712	total: 10m 24s	remaining: 6m 23s
6307:	learn: 0.0015751	total: 10m 24s	remaining: 6m 5s
6202:	learn: 0.0016418	total: 10m 24s	remaining: 6m 22s
6011:	learn: 0.0020539	total: 10m 24s	remaining: 6m 54s
5739:	learn: 0.0016051	total: 10m 24s	remaining: 7m 43s
6191:	learn: 0.0015707	total: 10m 24s	remaining: 6m 23s
6308:	learn: 0.0015745	total: 10m 24s	remaining: 6m 5s
6203:	learn: 0.0016415	total: 10m 24s	remaining: 6m 22s
5740:	learn: 0.0016048	total: 10m 24s	remaining: 7m 43s
6012:	learn: 0.0020533	total: 10m 24s	remaining: 6m 54s
6192:	learn: 0.0015707	total: 10m 24s	remaining: 6m 23s
6309:	learn: 0.0015739	total: 10m 24s	remaining: 6m 5s
5741:	learn: 0.0016046	total: 10m 24s	remaining: 7m 43s
6204:	learn: 0.0016415	total: 10m 24s	remaining: 6m 21s
6013:	learn: 0.0020533	total: 10m 24s	remaining: 6m 53s
6193:	learn: 0.0015707	total: 10m 24s	remaining: 6m 23s
6310:	learn: 0.0015736	total: 10m 24s	remaining: 6m 5s
5742:	learn: 0.0016046	total: 10m 24s	remaining: 7m 42s
6205:	learn: 0.0016413	total: 10m 24s	remaining: 6m 21s
6311:	learn: 0.0015733	total: 10m 24s	remaining: 6m 4s
6014:	learn: 0.0020533	total: 10m 24s	remaining: 6m 53s
6194:	learn: 0.0015703	total: 10m 24s	remaining: 6m 23s
5743:	learn: 0.0016042	total: 10m 24s	remaining: 7m 42s
6206:	learn: 0.0016413	total: 10m 24s	remaining: 6m 21s
6015:	learn: 0.0020533	total: 10m 24s	remaining: 6m 53s
6312:	learn: 0.0015728	total: 10m 24s	remaining: 6m 4s
6195:	learn: 0.0015698	total: 10m 24s	remaining: 6m 23s
5744:	learn: 0.0016042	total: 10m 24s	remaining: 7m 42s
6207:	learn: 0.0016412	total: 10m 24s	remaining: 6m 21s
6016:	learn: 0.0020533	total: 10m 24s	remaining: 6m 53s
6313:	learn: 0.0015728	total: 10m 24s	remaining: 6m 4s
6196:	learn: 0.0015698	total: 10m 24s	remaining: 6m 23s
5745:	learn: 0.0016038	total: 10m 24s	remaining: 7m 42s
6208:	learn: 0.0016412	total: 10m 24s	remaining: 6m 21s
6314:	learn: 0.0015728	total: 10m 24s	remaining: 6m 4s
6017:	learn: 0.0020533	total: 10m 24s	remaining: 6m 53s
6197:	learn: 0.0015697	total: 10m 24s	remaining: 6m 23s
5746:	learn: 0.0016034	total: 10m 25s	remaining: 7m 42s
6315:	learn: 0.0015728	total: 10m 24s	remaining: 6m 4s
6209:	learn: 0.0016412	total: 10m 25s	remaining: 6m 21s
6018:	learn: 0.0020533	total: 10m 25s	remaining: 6m 53s
6198:	learn: 0.0015697	total: 10m 24s	remaining: 6m 23s
6316:	learn: 0.0015725	total: 10m 25s	remaining: 6m 4s
5747:	learn: 0.0016030	total: 10m 25s	remaining: 7m 42s
6210:	learn: 0.0016409	total: 10m 25s	remaining: 6m 21s
6019:	learn: 0.0020533	total: 10m 25s	remaining: 6m 53s
6199:	learn: 0.0015695	total: 10m 24s	remaining: 6m 23s
6317:	learn: 0.0015725	total: 10m 25s	remaining: 6m 4s
6020:	learn: 0.0020533	total: 10m 25s	remaining: 6m 53s
5748:	learn: 0.0016024	total: 10m 25s	remaining: 7m 42s
6211:	learn: 0.0016409	total: 10m 25s	remaining: 6m 21s
6200:	learn: 0.0015694	total: 10m 25s	remaining: 6m 22s
6318:	learn: 0.0015725	total: 10m 25s	remaining: 6m 4s
6021:	learn: 0.0020533	total: 10m 25s	remaining: 6m 53s
5749:	learn: 0.0016019	total: 10m 25s	remaining: 7m 42s
6212:	learn: 0.0016405	total: 10m 25s	remaining: 6m 21s
6201:	learn: 0.0015694	total: 10m 25s	remaining: 6m 22s
6319:	learn: 0.0015725	total: 10m 25s	remaining: 6m 4s
6022:	learn: 0.0020533	total: 10m 25s	remaining: 6m 52s
5750:	learn: 0.0016019	total: 10m 25s	remaining: 7m 42s
6213:	learn: 0.0016405	total: 10m 25s	remaining: 6m 21s
6202:	learn: 0.0015694	total: 10m 25s	remaining: 6m 22s
6320:	learn: 0.0015720	total: 10m 25s	remaining: 6m 4s
6023:	learn: 0.0020526	total: 10m 25s	remaining: 6m 52s
6214:	learn: 0.0016400	total: 10m 25s	remaining: 6m 20s
5751:	learn: 0.0016019	total: 10m 25s	remaining: 7m 41s
6203:	learn: 0.0015694	total: 10m 25s	remaining: 6m 22s
6321:	learn: 0.0015721	total: 10m 25s	remaining: 6m 3s
6215:	learn: 0.0016400	total: 10m 25s	remaining: 6m 20s
6204:	learn: 0.0015690	total: 10m 25s	remaining: 6m 22s
6024:	learn: 0.0020526	total: 10m 25s	remaining: 6m 52s
5752:	learn: 0.0016016	total: 10m 25s	remaining: 7m 41s
6216:	learn: 0.0016397	total: 10m 25s	remaining: 6m 20s
6205:	learn: 0.0015689	total: 10m 25s	remaining: 6m 22s
6322:	learn: 0.0015720	total: 10m 25s	remaining: 6m 3s
6025:	learn: 0.0020526	total: 10m 25s	remaining: 6m 52s
5753:	learn: 0.0016011	total: 10m 25s	remaining: 7m 41s
6217:	learn: 0.0016397	total: 10m 25s	remaining: 6m 20s
6206:	learn: 0.0015689	total: 10m 25s	remaining: 6m 22s
6323:	learn: 0.0015720	total: 10m 25s	remaining: 6m 3s
6026:	learn: 0.0020526	total: 10m 25s	remaining: 6m 52s
6218:	learn: 0.0016397	total: 10m 25s	remaining: 6m 20s
5754:	learn: 0.0016005	total: 10m 25s	remaining: 7m 41s
6207:	learn: 0.0015689	total: 10m 25s	remaining: 6m 22s
6324:	learn: 0.0015720	total: 10m 25s	remaining: 6m 3s
6219:	learn: 0.0016392	total: 10m 25s	remaining: 6m 20s
6027:	learn: 0.0020526	total: 10m 25s	remaining: 6m 52s
6208:	learn: 0.0015689	total: 10m 25s	remaining: 6m 22s
6325:	learn: 0.0015715	total: 10m 25s	remaining: 6m 3s
5755:	learn: 0.0016005	total: 10m 26s	remaining: 7m 41s
6220:	learn: 0.0016392	total: 10m 26s	remaining: 6m 20s
6028:	learn: 0.0020526	total: 10m 26s	remaining: 6m 52s
6326:	learn: 0.0015710	total: 10m 25s	remaining: 6m 3s
6209:	learn: 0.0015685	total: 10m 25s	remaining: 6m 21s
5756:	learn: 0.0016005	total: 10m 26s	remaining: 7m 41s
6327:	learn: 0.0015710	total: 10m 26s	remaining: 6m 3s
6221:	learn: 0.0016392	total: 10m 26s	remaining: 6m 20s
6029:	learn: 0.0020526	total: 10m 26s	remaining: 6m 52s
6210:	learn: 0.0015685	total: 10m 26s	remaining: 6m 21s
6328:	learn: 0.0015710	total: 10m 26s	remaining: 6m 3s
5757:	learn: 0.0016005	total: 10m 26s	remaining: 7m 41s
6222:	learn: 0.0016392	total: 10m 26s	remaining: 6m 20s
6030:	learn: 0.0020526	total: 10m 26s	remaining: 6m 52s
6211:	learn: 0.0015685	total: 10m 26s	remaining: 6m 21s
6329:	learn: 0.0015711	total: 10m 26s	remaining: 6m 3s
5758:	learn: 0.0016005	total: 10m 26s	remaining: 7m 41s
6212:	learn: 0.0015682	total: 10m 26s	remaining: 6m 21s
6223:	learn: 0.0016388	total: 10m 26s	remaining: 6m 20s
6031:	learn: 0.0020526	total: 10m 26s	remaining: 6m 52s
6330:	learn: 0.0015711	total: 10m 26s	remaining: 6m 2s
6213:	learn: 0.0015682	total: 10m 26s	remaining: 6m 21s
6224:	learn: 0.0016388	total: 10m 26s	remaining: 6m 19s
5759:	learn: 0.0016005	total: 10m 26s	remaining: 7m 41s
6032:	learn: 0.0020526	total: 10m 26s	remaining: 6m 51s
6331:	learn: 0.0015705	total: 10m 26s	remaining: 6m 2s
6214:	learn: 0.0015678	total: 10m 26s	remaining: 6m 21s

6225:	learn: 0.0016388	total: 10m 26s	remaining: 6m 19s
5760:	learn: 0.0016002	total: 10m 26s	remaining: 7m 41s
6033:	learn: 0.0020526	total: 10m 26s	remaining: 6m 51s
6215:	learn: 0.0015677	total: 10m 26s	remaining: 6m 21s
6332:	learn: 0.0015702	total: 10m 26s	remaining: 6m 2s
6226:	learn: 0.0016388	total: 10m 26s	remaining: 6m 19s
6034:	learn: 0.0020526	total: 10m 26s	remaining: 6m 51s
5761:	learn: 0.0015998	total: 10m 26s	remaining: 7m 40s
6216:	learn: 0.0015677	total: 10m 26s	remaining: 6m 21s
6333:	learn: 0.0015702	total: 10m 26s	remaining: 6m 2s
6227:	learn: 0.0016388	total: 10m 26s	remaining: 6m 19s
6035:	learn: 0.0020526	total: 10m 26s	remaining: 6m 51s
5762:	learn: 0.0015993	total: 10m 26s	remaining: 7m 40s
6334:	learn: 0.0015702	total: 10m 26s	remaining: 6m 2s
6217:	learn: 0.0015673	total: 10m 26s	remaining: 6m 21s
6228:	learn: 0.0016388	total: 10m 26s	remaining: 6m 19s
5763:	learn: 0.0015993	total: 10m 26s	remaining: 7m 40s
6036:	learn: 0.0020526	total: 10m 26s	remaining: 6m 51s
6335:	learn: 0.0015702	total: 10m 26s	remaining: 6m 2s
6229:	learn: 0.0016388	total: 10m 26s	remaining: 6m 19s
6218:	learn: 0.0015671	total: 10m 26s	remaining: 6m 21s
5764:	learn: 0.0015990	total: 10m 27s	remaining: 7m 40s
6037:	learn: 0.0020526	total: 10m 26s	remaining: 6m 51s
6336:	learn: 0.0015702	total: 10m 26s	remaining: 6m 2s
6230:	learn: 0.0016386	total: 10m 27s	remaining: 6m 19s
6219:	learn: 0.0015667	total: 10m 26s	remaining: 6m 20s
6038:	learn: 0.0020526	total: 10m 27s	remaining: 6m 51s
5765:	learn: 0.0015986	total: 10m 27s	remaining: 7m 40s
6337:	learn: 0.0015702	total: 10m 27s	remaining: 6m 2s
6220:	learn: 0.0015667	total: 10m 26s	remaining: 6m 20s
6231:	learn: 0.0016381	total: 10m 27s	remaining: 6m 19s
6338:	learn: 0.0015702	total: 10m 27s	remaining: 6m 2s
5766:	learn: 0.0015986	total: 10m 27s	remaining: 7m 40s
6039:	learn: 0.0020526	total: 10m 27s	remaining: 6m 51s
6221:	learn: 0.0015663	total: 10m 27s	remaining: 6m 20s
6232:	learn: 0.0016381	total: 10m 27s	remaining: 6m 19s
6339:	learn: 0.0015701	total: 10m 27s	remaining: 6m 2s
6040:	learn: 0.0020526	total: 10m 27s	remaining: 6m 51s
5767:	learn: 0.0015981	total: 10m 27s	remaining: 7m 40s
6233:	learn: 0.0016381	total: 10m 27s	remaining: 6m 18s
6222:	learn: 0.0015663	total: 10m 27s	remaining: 6m 20s
6340:	learn: 0.0015695	total: 10m 27s	remaining: 6m 1s
6041:	learn: 0.0020526	total: 10m 27s	remaining: 6m 51s
5768:	learn: 0.0015981	total: 10m 27s	remaining: 7m 40s
6234:	learn: 0.0016381	total: 10m 27s	remaining: 6m 18s
6223:	learn: 0.0015663	total: 10m 27s	remaining: 6m 20s
6341:	learn: 0.0015695	total: 10m 27s	remaining: 6m 1s
6042:	learn: 0.0020526	total: 10m 27s	remaining: 6m 50s
6235:	learn: 0.0016381	total: 10m 27s	remaining: 6m 18s
5769:	learn: 0.0015981	total: 10m 27s	remaining: 7m 40s
6224:	learn: 0.0015663	total: 10m 27s	remaining: 6m 20s
6342:	learn: 0.0015695	total: 10m 27s	remaining: 6m 1s
6043:	learn: 0.0020526	total: 10m 27s	remaining: 6m 50s
6236:	learn: 0.0016381	total: 10m 27s	remaining: 6m 18s
5770:	learn: 0.0015981	total: 10m 27s	remaining: 7m 39s
6225:	learn: 0.0015663	total: 10m 27s	remaining: 6m 20s
6343:	learn: 0.0015695	total: 10m 27s	remaining: 6m 1s
6044:	learn: 0.0020526	total: 10m 27s	remaining: 6m 50s
5771:	learn: 0.0015978	total: 10m 27s	remaining: 7m 39s
6237:	learn: 0.0016375	total: 10m 27s	remaining: 6m 18s
6226:	learn: 0.0015663	total: 10m 27s	remaining: 6m 20s
6344:	learn: 0.0015690	total: 10m 27s	remaining: 6m 1s
5772:	learn: 0.0015973	total: 10m 27s	remaining: 7m 39s
6045:	learn: 0.0020526	total: 10m 27s	remaining: 6m 50s
6238:	learn: 0.0016369	total: 10m 27s	remaining: 6m 18s
6227:	learn: 0.0015663	total: 10m 27s	remaining: 6m 20s
6345:	learn: 0.0015684	total: 10m 27s	remaining: 6m 1s
6046:	learn: 0.0020526	total: 10m 27s	remaining: 6m 50s
5773:	learn: 0.0015968	total: 10m 27s	remaining: 7m 39s
6239:	learn: 0.0016364	total: 10m 27s	remaining: 6m 18s
6228:	learn: 0.0015663	total: 10m 27s	remaining: 6m 20s
6346:	learn: 0.0015681	total: 10m 27s	remaining: 6m 1s
6047:	learn: 0.0020526	total: 10m 28s	remaining: 6m 50s
6240:	learn: 0.0016364	total: 10m 28s	remaining: 6m 18s
5774:	learn: 0.0015962	total: 10m 28s	remaining: 7m 39s
6347:	learn: 0.0015682	total: 10m 27s	remaining: 6m 1s
6048:	learn: 0.0020526	total: 10m 28s	remaining: 6m 50s
6229:	learn: 0.0015659	total: 10m 27s	remaining: 6m 19s
6241:	learn: 0.0016364	total: 10m 28s	remaining: 6m 18s
6348:	learn: 0.0015681	total: 10m 28s	remaining: 6m 1s
5775:	learn: 0.0015958	total: 10m 28s	remaining: 7m 39s
6049:	learn: 0.0020526	total: 10m 28s	remaining: 6m 50s
6230:	learn: 0.0015658	total: 10m 28s	remaining: 6m 19s
6349:	learn: 0.0015682	total: 10m 28s	remaining: 6m 1s
6050:	learn: 0.0020526	total: 10m 28s	remaining: 6m 50s
5776:	learn: 0.0015952	total: 10m 28s	remaining: 7m 39s
6242:	learn: 0.0016364	total: 10m 28s	remaining: 6m 18s
6231:	learn: 0.0015658	total: 10m 28s	remaining: 6m 19s
5777:	learn: 0.0015948	total: 10m 28s	remaining: 7m 39s
6232:	learn: 0.0015659	total: 10m 28s	remaining: 6m 19s
6243:	learn: 0.0016364	total: 10m 28s	remaining: 6m 17s
6051:	learn: 0.0020520	total: 10m 28s	remaining: 6m 49s
6350:	learn: 0.0015681	total: 10m 28s	remaining: 6m
5778:	learn: 0.0015948	total: 10m 28s	remaining: 7m 39s
6233:	learn: 0.0015659	total: 10m 28s	remaining: 6m 19s
6351:	learn: 0.0015675	total: 10m 28s	remaining: 6m
6244:	learn: 0.0016364	total: 10m 28s	remaining: 6m 17s
6052:	learn: 0.0020520	total: 10m 28s	remaining: 6m 49s
6234:	learn: 0.0015658	total: 10m 28s	remaining: 6m 19s
5779:	learn: 0.0015948	total: 10m 28s	remaining: 7m 38s
6053:	learn: 0.0020520	total: 10m 28s	remaining: 6m 49s
6235:	learn: 0.0015658	total: 10m 28s	remaining: 6m 19s
6245:	learn: 0.0016364	total: 10m 28s	remaining: 6m 17s
6352:	learn: 0.0015670	total: 10m 28s	remaining: 6m
6236:	learn: 0.0015659	total: 10m 28s	remaining: 6m 19s
5780:	learn: 0.0015945	total: 10m 28s	remaining: 7m 38s
6054:	learn: 0.0020520	total: 10m 28s	remaining: 6m 49s
6246:	learn: 0.0016360	total: 10m 28s	remaining: 6m 17s
6353:	learn: 0.0015670	total: 10m 28s	remaining: 6m
6237:	learn: 0.0015659	total: 10m 28s	remaining: 6m 19s
5781:	learn: 0.0015941	total: 10m 28s	remaining: 7m 38s
6055:	learn: 0.0020520	total: 10m 28s	remaining: 6m 49s
6354:	learn: 0.0015669	total: 10m 28s	remaining: 6m
6247:	learn: 0.0016360	total: 10m 28s	remaining: 6m 17s
6238:	learn: 0.0015659	total: 10m 28s	remaining: 6m 18s
6056:	learn: 0.0020520	total: 10m 28s	remaining: 6m 49s
5782:	learn: 0.0015941	total: 10m 28s	remaining: 7m 38s
6355:	learn: 0.0015664	total: 10m 28s	remaining: 6m
6248:	learn: 0.0016357	total: 10m 28s	remaining: 6m 17s
6239:	learn: 0.0015659	total: 10m 28s	remaining: 6m 18s
5783:	learn: 0.0015941	total: 10m 28s	remaining: 7m 38s
6057:	learn: 0.0020520	total: 10m 28s	remaining: 6m 49s
6356:	learn: 0.0015658	total: 10m 28s	remaining: 6m
6240:	learn: 0.0015655	total: 10m 28s	remaining: 6m 18s
6249:	learn: 0.0016351	total: 10m 29s	remaining: 6m 17s
5784:	learn: 0.0015941	total: 10m 29s	remaining: 7m 38s
6357:	learn: 0.0015658	total: 10m 28s	remaining: 6m
6058:	learn: 0.0020520	total: 10m 29s	remaining: 6m 49s
6241:	learn: 0.0015655	total: 10m 28s	remaining: 6m 18s
6250:	learn: 0.0016351	total: 10m 29s	remaining: 6m 17s
6358:	learn: 0.0015654	total: 10m 29s	remaining: 6m
5785:	learn: 0.0015936	total: 10m 29s	remaining: 7m 38s
6059:	learn: 0.0020520	total: 10m 29s	remaining: 6m 49s
6242:	learn: 0.0015655	total: 10m 29s	remaining: 6m 18s
6251:	learn: 0.0016351	total: 10m 29s	remaining: 6m 17s
6060:	learn: 0.0020520	total: 10m 29s	remaining: 6m 48s
6359:	learn: 0.0015654	total: 10m 29s	remaining: 6m
5786:	learn: 0.0015936	total: 10m 29s	remaining: 7m 38s
6243:	learn: 0.0015655	total: 10m 29s	remaining: 6m 18s
6252:	learn: 0.0016351	total: 10m 29s	remaining: 6m 17s
6360:	learn: 0.0015654	total: 10m 29s	remaining: 6m
6061:	learn: 0.0020514	total: 10m 29s	remaining: 6m 48s
5787:	learn: 0.0015936	total: 10m 29s	remaining: 7m 38s
6244:	learn: 0.0015655	total: 10m 29s	remaining: 6m 18s
6253:	learn: 0.0016351	total: 10m 29s	remaining: 6m 17s
6361:	learn: 0.0015649	total: 10m 29s	remaining: 5m 59s
6062:	learn: 0.0020509	total: 10m 29s	remaining: 6m 48s
6245:	learn: 0.0015655	total: 10m 29s	remaining: 6m 18s
6254:	learn: 0.0016344	total: 10m 29s	remaining: 6m 16s
6362:	learn: 0.0015643	total: 10m 29s	remaining: 5m 59s
6063:	learn: 0.0020509	total: 10m 29s	remaining: 6m 48s
6246:	learn: 0.0015654	total: 10m 29s	remaining: 6m 18s
6255:	learn: 0.0016344	total: 10m 29s	remaining: 6m 16s
5789:	learn: 0.0015926	total: 10m 29s	remaining: 7m 37s
6064:	learn: 0.0020509	total: 10m 29s	remaining: 6m 48s
6363:	learn: 0.0015639	total: 10m 29s	remaining: 5m 59s
6256:	learn: 0.0016344	total: 10m 29s	remaining: 6m 16s
6247:	learn: 0.0015654	total: 10m 29s	remaining: 6m 18s
5790:	learn: 0.0015921	total: 10m 29s	remaining: 7m 37s
6065:	learn: 0.0020509	total: 10m 29s	remaining: 6m 48s
6364:	learn: 0.0015639	total: 10m 29s	remaining: 5m 59s
6257:	learn: 0.0016344	total: 10m 29s	remaining: 6m 16s
6248:	learn: 0.0015654	total: 10m 29s	remaining: 6m 17s
5791:	learn: 0.0015921	total: 10m 29s	remaining: 7m 37s
6258:	learn: 0.0016344	total: 10m 29s	remaining: 6m 16s
6365:	learn: 0.0015639	total: 10m 29s	remaining: 5m 59s
6066:	learn: 0.0020509	total: 10m 29s	remaining: 6m 48s
6249:	learn: 0.0015654	total: 10m 29s	remaining: 6m 17s
5792:	learn: 0.0015921	total: 10m 29s	remaining: 7m 37s
6067:	learn: 0.0020509	total: 10m 29s	remaining: 6m 48s
6259:	learn: 0.0016344	total: 10m 29s	remaining: 6m 16s
6366:	learn: 0.0015639	total: 10m 29s	remaining: 5m 59s
6250:	learn: 0.0015654	total: 10m 29s	remaining: 6m 17s
6260:	learn: 0.0016344	total: 10m 30s	remaining: 6m 16s
6068:	learn: 0.0020509	total: 10m 30s	remaining: 6m 48s
5793:	learn: 0.0015921	total: 10m 30s	remaining: 7m 37s
6367:	learn: 0.0015639	total: 10m 30s	remaining: 5m 59s
6251:	learn: 0.0015654	total: 10m 29s	remaining: 6m 17s
6261:	learn: 0.0016344	total: 10m 30s	remaining: 6m 16s
6069:	learn: 0.0020509	total: 10m 30s	remaining: 6m 48s
5794:	learn: 0.0015916	total: 10m 30s	remaining: 7m 37s
6368:	learn: 0.0015639	total: 10m 30s	remaining: 5m 59s
6252:	learn: 0.0015650	total: 10m 30s	remaining: 6m 17s
6262:	learn: 0.0016338	total: 10m 30s	remaining: 6m 16s
6070:	learn: 0.0020509	total: 10m 30s	remaining: 6m 47s
6263:	learn: 0.0016338	total: 10m 30s	remaining: 6m 15s
5795:	learn: 0.0015916	total: 10m 30s	remaining: 7m 37s
6253:	learn: 0.0015650	total: 10m 30s	remaining: 6m 17s
6369:	learn: 0.0015633	total: 10m 30s	remaining: 5m 59s
6254:	learn: 0.0015650	total: 10m 30s	remaining: 6m 17s
6264:	learn: 0.0016338	total: 10m 30s	remaining: 6m 15s
6370:	learn: 0.0015627	total: 10m 30s	remaining: 5m 59s
5796:	learn: 0.0015916	total: 10m 30s	remaining: 7m 37s
6071:	learn: 0.0020509	total: 10m 30s	remaining: 6m 47s
6255:	learn: 0.0015650	total: 10m 30s	remaining: 6m 17s
6265:	learn: 0.0016338	total: 10m 30s	remaining: 6m 15s
6371:	learn: 0.0015623	total: 10m 30s	remaining: 5m 58s
5797:	learn: 0.0015916	total: 10m 30s	remaining: 7m 36s
6072:	learn: 0.0020509	total: 10m 30s	remaining: 6m 47s
6256:	learn: 0.0015650	total: 10m 30s	remaining: 6m 17s
6266:	learn: 0.0016332	total: 10m 30s	remaining: 6m 15s
6372:	learn: 0.0015623	total: 10m 30s	remaining: 5m 58s
5798:	learn: 0.0015916	total: 10m 30s	remaining: 7m 36s
6257:	learn: 0.0015650	total: 10m 30s	remaining: 6m 16s
6073:	learn: 0.0020509	total: 10m 30s	remaining: 6m 47s
6267:	learn: 0.0016325	total: 10m 30s	remaining: 6m 15s
6373:	learn: 0.0015617	total: 10m 30s	remaining: 5m 58s
5799:	learn: 0.0015916	total: 10m 30s	remaining: 7m 36s
6258:	learn: 0.0015646	total: 10m 30s	remaining: 6m 16s
6074:	learn: 0.0020509	total: 10m 30s	remaining: 6m 47s
6268:	learn: 0.0016321	total: 10m 30s	remaining: 6m 15s
6374:	learn: 0.0015617	total: 10m 30s	remaining: 5m 58s
5800:	learn: 0.0015916	total: 10m 30s	remaining: 7m 36s
6075:	learn: 0.0020509	total: 10m 30s	remaining: 6m 47s
6259:	learn: 0.0015646	total: 10m 30s	remaining: 6m 16s
6375:	learn: 0.0015617	total: 10m 30s	remaining: 5m 58s
6269:	learn: 0.0016315	total: 10m 30s	remaining: 6m 15s
6076:	learn: 0.0020509	total: 10m 30s	remaining: 6m 47s
5801:	learn: 0.0015911	total: 10m 30s	remaining: 7m 36s
6260:	learn: 0.0015646	total: 10m 30s	remaining: 6m 16s
6376:	learn: 0.0015617	total: 10m 30s	remaining: 5m 58s
6077:	learn: 0.0020500	total: 10m 31s	remaining: 6m 47s
6270:	learn: 0.0016315	total: 10m 31s	remaining: 6m 15s
6261:	learn: 0.0015646	total: 10m 30s	remaining: 6m 16s
5802:	learn: 0.0015906	total: 10m 31s	remaining: 7m 36s
6377:	learn: 0.0015612	total: 10m 30s	remaining: 5m 58s
6078:	learn: 0.0020501	total: 10m 31s	remaining: 6m 47s
6271:	learn: 0.0016312	total: 10m 31s	remaining: 6m 15s
5803:	learn: 0.0015902	total: 10m 31s	remaining: 7m 36s
6378:	learn: 0.0015612	total: 10m 31s	remaining: 5m 58s
6262:	learn: 0.0015646	total: 10m 30s	remaining: 6m 16s
6079:	learn: 0.0020500	total: 10m 31s	remaining: 6m 46s
6272:	learn: 0.0016309	total: 10m 31s	remaining: 6m 15s
5804:	learn: 0.0015898	total: 10m 31s	remaining: 7m 36s
6379:	learn: 0.0015612	total: 10m 31s	remaining: 5m 58s
6263:	learn: 0.0015641	total: 10m 31s	remaining: 6m 16s
6080:	learn: 0.0020500	total: 10m 31s	remaining: 6m 46s
5805:	learn: 0.0015894	total: 10m 31s	remaining: 7m 36s
6380:	learn: 0.0015611	total: 10m 31s	remaining: 5m 58s
6273:	learn: 0.0016309	total: 10m 31s	remaining: 6m 14s
6264:	learn: 0.0015639	total: 10m 31s	remaining: 6m 16s
6081:	learn: 0.0020500	total: 10m 31s	remaining: 6m 46s
6381:	learn: 0.0015608	total: 10m 31s	remaining: 5m 57s
5806:	learn: 0.0015890	total: 10m 31s	remaining: 7m 35s
6265:	learn: 0.0015639	total: 10m 31s	remaining: 6m 16s
6274:	learn: 0.0016309	total: 10m 31s	remaining: 6m 14s
6082:	learn: 0.0020500	total: 10m 31s	remaining: 6m 46s
6382:	learn: 0.0015608	total: 10m 31s	remaining: 5m 57s
5807:	learn: 0.0015884	total: 10m 31s	remaining: 7m 35s
6266:	learn: 0.0015639	total: 10m 31s	remaining: 6m 16s
6275:	learn: 0.0016309	total: 10m 31s	remaining: 6m 14s
6083:	learn: 0.0020501	total: 10m 31s	remaining: 6m 46s
6383:	learn: 0.0015608	total: 10m 31s	remaining: 5m 57s
5808:	learn: 0.0015879	total: 10m 31s	remaining: 7m 35s
6267:	learn: 0.0015636	total: 10m 31s	remaining: 6m 15s
6276:	learn: 0.0016309	total: 10m 31s	remaining: 6m 14s
6084:	learn: 0.0020499	total: 10m 31s	remaining: 6m 46s
5809:	learn: 0.0015873	total: 10m 31s	remaining: 7m 35s
6384:	learn: 0.0015608	total: 10m 31s	remaining: 5m 57s
6268:	learn: 0.0015636	total: 10m 31s	remaining: 6m 15s
6085:	learn: 0.0020499	total: 10m 31s	remaining: 6m 46s
6277:	learn: 0.0016309	total: 10m 31s	remaining: 6m 14s
5810:	learn: 0.0015873	total: 10m 31s	remaining: 7m 35s
6385:	learn: 0.0015608	total: 10m 31s	remaining: 5m 57s
6269:	learn: 0.0015636	total: 10m 31s	remaining: 6m 15s
6086:	learn: 0.0020499	total: 10m 31s	remaining: 6m 46s
6278:	learn: 0.0016303	total: 10m 31s	remaining: 6m 14s
6386:	learn: 0.0015608	total: 10m 31s	remaining: 5m 57s
5811:	learn: 0.0015873	total: 10m 31s	remaining: 7m 35s
6270:	learn: 0.0015636	total: 10m 31s	remaining: 6m 15s
6087:	learn: 0.0020499	total: 10m 31s	remaining: 6m 46s
6279:	learn: 0.0016303	total: 10m 31s	remaining: 6m 14s
6387:	learn: 0.0015608	total: 10m 31s	remaining: 5m 57s
5812:	learn: 0.0015873	total: 10m 32s	remaining: 7m 35s
6271:	learn: 0.0015632	total: 10m 31s	remaining: 6m 15s
6088:	learn: 0.0020499	total: 10m 32s	remaining: 6m 45s
6388:	learn: 0.0015608	total: 10m 32s	remaining: 5m 57s
6280:	learn: 0.0016303	total: 10m 32s	remaining: 6m 14s
5813:	learn: 0.0015870	total: 10m 32s	remaining: 7m 35s
6272:	learn: 0.0015632	total: 10m 31s	remaining: 6m 15s
6389:	learn: 0.0015608	total: 10m 32s	remaining: 5m 57s
6089:	learn: 0.0020499	total: 10m 32s	remaining: 6m 45s
5814:	learn: 0.0015867	total: 10m 32s	remaining: 7m 35s
6281:	learn: 0.0016303	total: 10m 32s	remaining: 6m 14s
6390:	learn: 0.0015608	total: 10m 32s	remaining: 5m 57s
6273:	learn: 0.0015632	total: 10m 32s	remaining: 6m 15s
6090:	learn: 0.0020499	total: 10m 32s	remaining: 6m 45s
6282:	learn: 0.0016303	total: 10m 32s	remaining: 6m 14s
5815:	learn: 0.0015862	total: 10m 32s	remaining: 7m 34s
6274:	learn: 0.0015632	total: 10m 32s	remaining: 6m 15s
6391:	learn: 0.0015608	total: 10m 32s	remaining: 5m 56s
6091:	learn: 0.0020499	total: 10m 32s	remaining: 6m 45s
0m 26s	remaining: 6m 21s
 36s
 aq      m 42s

 ma      6283:	learn: 0.0016303	total: 10m 32s	remaining: 6m 13s
5816:	learn: 0.0015858	total: 10m 32s	remaining: 7m 34s
6275:	learn: 0.0015632	total: 10m 32s	remaining: 6m 15s
6392:	learn: 0.0015608	total: 10m 32s	remaining: 5m 56s
6092:	learn: 0.0020499	total: 10m 32s	remaining: 6m 45s
5817:	learn: 0.0015858	total: 10m 32s	remaining: 7m 34s
6284:	learn: 0.0016303	total: 10m 32s	remaining: 6m 13s
6393:	learn: 0.0015608	total: 10m 32s	remaining: 5m 56s
6276:	learn: 0.0015629	total: 10m 32s	remaining: 6m 15s
6093:	learn: 0.0020499	total: 10m 32s	remaining: 6m 45s
5818:	learn: 0.0015854	total: 10m 32s	remaining: 7m 34s
6285:	learn: 0.0016303	total: 10m 32s	remaining: 6m 13s
6394:	learn: 0.0015604	total: 10m 32s	remaining: 5m 56s
6277:	learn: 0.0015629	total: 10m 32s	remaining: 6m 14s
5819:	learn: 0.0015848	total: 10m 32s	remaining: 7m 34s
6094:	learn: 0.0020499	total: 10m 32s	remaining: 6m 45s
6395:	learn: 0.0015604	total: 10m 32s	remaining: 5m 56s
6286:	learn: 0.0016303	total: 10m 32s	remaining: 6m 13s
6278:	learn: 0.0015627	total: 10m 32s	remaining: 6m 14s
6095:	learn: 0.0020499	total: 10m 32s	remaining: 6m 45s
5820:	learn: 0.0015845	total: 10m 32s	remaining: 7m 34s
6396:	learn: 0.0015599	total: 10m 32s	remaining: 5m 56s
6287:	learn: 0.0016303	total: 10m 32s	remaining: 6m 13s
6279:	learn: 0.0015621	total: 10m 32s	remaining: 6m 14s
6096:	learn: 0.0020499	total: 10m 32s	remaining: 6m 45s
5821:	learn: 0.0015845	total: 10m 32s	remaining: 7m 34s
6397:	learn: 0.0015599	total: 10m 32s	remaining: 5m 56s
6288:	learn: 0.0016298	total: 10m 32s	remaining: 6m 13s
6097:	learn: 0.0020499	total: 10m 32s	remaining: 6m 45s
6280:	learn: 0.0015620	total: 10m 32s	remaining: 6m 14s
6398:	learn: 0.0015595	total: 10m 32s	remaining: 5m 56s
5822:	learn: 0.0015845	total: 10m 33s	remaining: 7m 34s
6289:	learn: 0.0016297	total: 10m 33s	remaining: 6m 13s
6281:	learn: 0.0015620	total: 10m 32s	remaining: 6m 14s
6098:	learn: 0.0020499	total: 10m 33s	remaining: 6m 44s
6399:	learn: 0.0015595	total: 10m 33s	remaining: 5m 56s
5823:	learn: 0.0015841	total: 10m 33s	remaining: 7m 33s
6290:	learn: 0.0016297	total: 10m 33s	remaining: 6m 13s
6282:	learn: 0.0015616	total: 10m 32s	remaining: 6m 14s
6099:	learn: 0.0020499	total: 10m 33s	remaining: 6m 44s
6400:	learn: 0.0015595	total: 10m 33s	remaining: 5m 55s
5824:	learn: 0.0015837	total: 10m 33s	remaining: 7m 33s
6291:	learn: 0.0016297	total: 10m 33s	remaining: 6m 13s
6283:	learn: 0.0015612	total: 10m 33s	remaining: 6m 14s
6401:	learn: 0.0015591	total: 10m 33s	remaining: 5m 55s
6100:	learn: 0.0020499	total: 10m 33s	remaining: 6m 44s
6284:	learn: 0.0015612	total: 10m 33s	remaining: 6m 14s
6292:	learn: 0.0016297	total: 10m 33s	remaining: 6m 13s
5825:	learn: 0.0015837	total: 10m 33s	remaining: 7m 33s
6402:	learn: 0.0015587	total: 10m 33s	remaining: 5m 55s
6285:	learn: 0.0015612	total: 10m 33s	remaining: 6m 14s
6101:	learn: 0.0020499	total: 10m 33s	remaining: 6m 44s
6403:	learn: 0.0015583	total: 10m 33s	remaining: 5m 55s
6293:	learn: 0.0016297	total: 10m 33s	remaining: 6m 13s
6286:	learn: 0.0015612	total: 10m 33s	remaining: 6m 14s
5826:	learn: 0.0015832	total: 10m 33s	remaining: 7m 33s
6102:	learn: 0.0020499	total: 10m 33s	remaining: 6m 44s
6404:	learn: 0.0015579	total: 10m 33s	remaining: 5m 55s
6287:	learn: 0.0015612	total: 10m 33s	remaining: 6m 13s
6294:	learn: 0.0016297	total: 10m 33s	remaining: 6m 12s
5827:	learn: 0.0015832	total: 10m 33s	remaining: 7m 33s
6405:	learn: 0.0015576	total: 10m 33s	remaining: 5m 55s
6103:	learn: 0.0020499	total: 10m 33s	remaining: 6m 44s
6295:	learn: 0.0016297	total: 10m 33s	remaining: 6m 12s
5828:	learn: 0.0015832	total: 10m 33s	remaining: 7m 33s
6288:	learn: 0.0015611	total: 10m 33s	remaining: 6m 13s
6406:	learn: 0.0015576	total: 10m 33s	remaining: 5m 55s
6296:	learn: 0.0016297	total: 10m 33s	remaining: 6m 12s
6104:	learn: 0.0020499	total: 10m 33s	remaining: 6m 44s
6289:	learn: 0.0015611	total: 10m 33s	remaining: 6m 13s
5829:	learn: 0.0015828	total: 10m 33s	remaining: 7m 33s
6407:	learn: 0.0015576	total: 10m 33s	remaining: 5m 55s
6297:	learn: 0.0016297	total: 10m 33s	remaining: 6m 12s
6290:	learn: 0.0015611	total: 10m 33s	remaining: 6m 13s
6105:	learn: 0.0020491	total: 10m 33s	remaining: 6m 44s
6408:	learn: 0.0015571	total: 10m 33s	remaining: 5m 55s
6298:	learn: 0.0016290	total: 10m 33s	remaining: 6m 12s
5830:	learn: 0.0015822	total: 10m 33s	remaining: 7m 33s
6291:	learn: 0.0015611	total: 10m 33s	remaining: 6m 13s
6106:	learn: 0.0020491	total: 10m 34s	remaining: 6m 44s
6299:	learn: 0.0016284	total: 10m 34s	remaining: 6m 12s
6409:	learn: 0.0015571	total: 10m 33s	remaining: 5m 55s
5831:	learn: 0.0015819	total: 10m 34s	remaining: 7m 33s
6292:	learn: 0.0015611	total: 10m 33s	remaining: 6m 13s
6107:	learn: 0.0020491	total: 10m 34s	remaining: 6m 44s
6300:	learn: 0.0016284	total: 10m 34s	remaining: 6m 12s
6410:	learn: 0.0015571	total: 10m 34s	remaining: 5m 54s
5832:	learn: 0.0015814	total: 10m 34s	remaining: 7m 33s
6108:	learn: 0.0020491	total: 10m 34s	remaining: 6m 43s
6293:	learn: 0.0015611	total: 10m 33s	remaining: 6m 13s
6301:	learn: 0.0016284	total: 10m 34s	remaining: 6m 12s
6411:	learn: 0.0015571	total: 10m 34s	remaining: 5m 54s
5833:	learn: 0.0015810	total: 10m 34s	remaining: 7m 32s
6109:	learn: 0.0020491	total: 10m 34s	remaining: 6m 43s
6294:	learn: 0.0015607	total: 10m 34s	remaining: 6m 13s
6302:	learn: 0.0016280	total: 10m 34s	remaining: 6m 12s
6412:	learn: 0.0015571	total: 10m 34s	remaining: 5m 54s
6295:	learn: 0.0015607	total: 10m 34s	remaining: 6m 13s
6110:	learn: 0.0020491	total: 10m 34s	remaining: 6m 43s
5834:	learn: 0.0015806	total: 10m 34s	remaining: 7m 32s
6296:	learn: 0.0015607	total: 10m 34s	remaining: 6m 12s
6413:	learn: 0.0015571	total: 10m 34s	remaining: 5m 54s
6303:	learn: 0.0016280	total: 10m 34s	remaining: 6m 11s
6111:	learn: 0.0020491	total: 10m 34s	remaining: 6m 43s
5835:	learn: 0.0015802	total: 10m 34s	remaining: 7m 32s
6297:	learn: 0.0015607	total: 10m 34s	remaining: 6m 12s
6414:	learn: 0.0015571	total: 10m 34s	remaining: 5m 54s
5836:	learn: 0.0015798	total: 10m 34s	remaining: 7m 32s
6304:	learn: 0.0016278	total: 10m 34s	remaining: 6m 11s
6112:	learn: 0.0020491	total: 10m 34s	remaining: 6m 43s
6298:	learn: 0.0015607	total: 10m 34s	remaining: 6m 12s
6415:	learn: 0.0015568	total: 10m 34s	remaining: 5m 54s
6305:	learn: 0.0016278	total: 10m 34s	remaining: 6m 11s
5837:	learn: 0.0015792	total: 10m 34s	remaining: 7m 32s
6299:	learn: 0.0015602	total: 10m 34s	remaining: 6m 12s
6113:	learn: 0.0020491	total: 10m 34s	remaining: 6m 43s
6306:	learn: 0.0016278	total: 10m 34s	remaining: 6m 11s
6416:	learn: 0.0015564	total: 10m 34s	remaining: 5m 54s
5838:	learn: 0.0015789	total: 10m 34s	remaining: 7m 32s
6114:	learn: 0.0020491	total: 10m 34s	remaining: 6m 43s
6300:	learn: 0.0015602	total: 10m 34s	remaining: 6m 12s
6417:	learn: 0.0015564	total: 10m 34s	remaining: 5m 54s
6115:	learn: 0.0020491	total: 10m 34s	remaining: 6m 43s
6307:	learn: 0.0016278	total: 10m 34s	remaining: 6m 11s
5839:	learn: 0.0015784	total: 10m 34s	remaining: 7m 32s
6301:	learn: 0.0015602	total: 10m 34s	remaining: 6m 12s
6116:	learn: 0.0020482	total: 10m 34s	remaining: 6m 43s
6418:	learn: 0.0015564	total: 10m 34s	remaining: 5m 54s
6308:	learn: 0.0016277	total: 10m 34s	remaining: 6m 11s
5840:	learn: 0.0015780	total: 10m 35s	remaining: 7m 32s
6302:	learn: 0.0015602	total: 10m 34s	remaining: 6m 12s
6117:	learn: 0.0020482	total: 10m 35s	remaining: 6m 42s
6419:	learn: 0.0015560	total: 10m 34s	remaining: 5m 54s
6303:	learn: 0.0015602	total: 10m 34s	remaining: 6m 12s
6309:	learn: 0.0016273	total: 10m 35s	remaining: 6m 11s
5841:	learn: 0.0015776	total: 10m 35s	remaining: 7m 32s
6118:	learn: 0.0020482	total: 10m 35s	remaining: 6m 42s
6420:	learn: 0.0015560	total: 10m 35s	remaining: 5m 54s
6310:	learn: 0.0016267	total: 10m 35s	remaining: 6m 11s
6119:	learn: 0.0020482	total: 10m 35s	remaining: 6m 42s
6304:	learn: 0.0015602	total: 10m 35s	remaining: 6m 12s
5842:	learn: 0.0015776	total: 10m 35s	remaining: 7m 31s
6421:	learn: 0.0015560	total: 10m 35s	remaining: 5m 53s
6311:	learn: 0.0016267	total: 10m 35s	remaining: 6m 11s
6120:	learn: 0.0020482	total: 10m 35s	remaining: 6m 42s
6305:	learn: 0.0015602	total: 10m 35s	remaining: 6m 12s
5843:	learn: 0.0015776	total: 10m 35s	remaining: 7m 31s
6422:	learn: 0.0015560	total: 10m 35s	remaining: 5m 53s
6312:	learn: 0.0016267	total: 10m 35s	remaining: 6m 11s
6306:	learn: 0.0015602	total: 10m 35s	remaining: 6m 11s
6121:	learn: 0.0020482	total: 10m 35s	remaining: 6m 42s
5844:	learn: 0.0015771	total: 10m 35s	remaining: 7m 31s
6423:	learn: 0.0015560	total: 10m 35s	remaining: 5m 53s
6307:	learn: 0.0015598	total: 10m 35s	remaining: 6m 11s
6122:	learn: 0.0020482	total: 10m 35s	remaining: 6m 42s
6313:	learn: 0.0016263	total: 10m 35s	remaining: 6m 11s
5845:	learn: 0.0015767	total: 10m 35s	remaining: 7m 31s
6424:	learn: 0.0015560	total: 10m 35s	remaining: 5m 53s
6308:	learn: 0.0015597	total: 10m 35s	remaining: 6m 11s
6123:	learn: 0.0020482	total: 10m 35s	remaining: 6m 42s
6314:	learn: 0.0016263	total: 10m 35s	remaining: 6m 10s
5846:	learn: 0.0015767	total: 10m 35s	remaining: 7m 31s
6309:	learn: 0.0015597	total: 10m 35s	remaining: 6m 11s
6425:	learn: 0.0015555	total: 10m 35s	remaining: 5m 53s
6315:	learn: 0.0016263	total: 10m 35s	remaining: 6m 10s
6124:	learn: 0.0020481	total: 10m 35s	remaining: 6m 42s
5847:	learn: 0.0015767	total: 10m 35s	remaining: 7m 31s
6310:	learn: 0.0015597	total: 10m 35s	remaining: 6m 11s
6426:	learn: 0.0015550	total: 10m 35s	remaining: 5m 53s
6316:	learn: 0.0016263	total: 10m 35s	remaining: 6m 10s
6311:	learn: 0.0015597	total: 10m 35s	remaining: 6m 11s
6125:	learn: 0.0020482	total: 10m 35s	remaining: 6m 42s
5848:	learn: 0.0015762	total: 10m 35s	remaining: 7m 31s
6427:	learn: 0.0015545	total: 10m 35s	remaining: 5m 53s
6312:	learn: 0.0015597	total: 10m 35s	remaining: 6m 11s
6317:	learn: 0.0016263	total: 10m 35s	remaining: 6m 10s
6428:	learn: 0.0015540	total: 10m 35s	remaining: 5m 53s
5849:	learn: 0.0015762	total: 10m 35s	remaining: 7m 31s
6126:	learn: 0.0020482	total: 10m 35s	remaining: 6m 42s
6313:	learn: 0.0015597	total: 10m 35s	remaining: 6m 11s
6318:	learn: 0.0016263	total: 10m 36s	remaining: 6m 10s
5850:	learn: 0.0015762	total: 10m 36s	remaining: 7m 31s
6429:	learn: 0.0015540	total: 10m 35s	remaining: 5m 53s
6314:	learn: 0.0015597	total: 10m 35s	remaining: 6m 11s
6127:	learn: 0.0020482	total: 10m 36s	remaining: 6m 41s
6319:	learn: 0.0016263	total: 10m 36s	remaining: 6m 10s
5851:	learn: 0.0015759	total: 10m 36s	remaining: 7m 30s
6430:	learn: 0.0015535	total: 10m 36s	remaining: 5m 53s
6315:	learn: 0.0015597	total: 10m 35s	remaining: 6m 10s
6128:	learn: 0.0020482	total: 10m 36s	remaining: 6m 41s
6320:	learn: 0.0016259	total: 10m 36s	remaining: 6m 10s
6431:	learn: 0.0015530	total: 10m 36s	remaining: 5m 52s
5852:	learn: 0.0015755	total: 10m 36s	remaining: 7m 30s
6316:	learn: 0.0015598	total: 10m 36s	remaining: 6m 10s
6321:	learn: 0.0016259	total: 10m 36s	remaining: 6m 10s
6129:	learn: 0.0020482	total: 10m 36s	remaining: 6m 41s
6432:	learn: 0.0015530	total: 10m 36s	remaining: 5m 52s
6317:	learn: 0.0015598	total: 10m 36s	remaining: 6m 10s
6322:	learn: 0.0016256	total: 10m 36s	remaining: 6m 10s
5853:	learn: 0.0015755	total: 10m 36s	remaining: 7m 30s
6130:	learn: 0.0020482	total: 10m 36s	remaining: 6m 41s
6433:	learn: 0.0015526	total: 10m 36s	remaining: 5m 52s
6318:	learn: 0.0015598	total: 10m 36s	remaining: 6m 10s
5854:	learn: 0.0015751	total: 10m 36s	remaining: 7m 30s
6131:	learn: 0.0020482	total: 10m 36s	remaining: 6m 41s
6323:	learn: 0.0016253	total: 10m 36s	remaining: 6m 10s
6434:	learn: 0.0015523	total: 10m 36s	remaining: 5m 52s
6132:	learn: 0.0020482	total: 10m 36s	remaining: 6m 41s
5855:	learn: 0.0015747	total: 10m 36s	remaining: 7m 30s
6319:	learn: 0.0015598	total: 10m 36s	remaining: 6m 10s
6435:	learn: 0.0015523	total: 10m 36s	remaining: 5m 52s
6324:	learn: 0.0016253	total: 10m 36s	remaining: 6m 9s
6320:	learn: 0.0015598	total: 10m 36s	remaining: 6m 10s
6133:	learn: 0.0020482	total: 10m 36s	remaining: 6m 41s
5856:	learn: 0.0015742	total: 10m 36s	remaining: 7m 30s
6436:	learn: 0.0015523	total: 10m 36s	remaining: 5m 52s
6134:	learn: 0.0020482	total: 10m 36s	remaining: 6m 41s
6325:	learn: 0.0016251	total: 10m 36s	remaining: 6m 9s
5857:	learn: 0.0015742	total: 10m 36s	remaining: 7m 30s
6437:	learn: 0.0015518	total: 10m 36s	remaining: 5m 52s
6321:	learn: 0.0015597	total: 10m 36s	remaining: 6m 10s
6135:	learn: 0.0020482	total: 10m 36s	remaining: 6m 41s
6438:	learn: 0.0015518	total: 10m 36s	remaining: 5m 52s
5858:	learn: 0.0015739	total: 10m 36s	remaining: 7m 30s
6326:	learn: 0.0016248	total: 10m 36s	remaining: 6m 9s
6136:	learn: 0.0020482	total: 10m 36s	remaining: 6m 40s
6322:	learn: 0.0015594	total: 10m 36s	remaining: 6m 10s
6439:	learn: 0.0015517	total: 10m 36s	remaining: 5m 52s
6327:	learn: 0.0016248	total: 10m 36s	remaining: 6m 9s
5859:	learn: 0.0015733	total: 10m 37s	remaining: 7m 30s
6323:	learn: 0.0015594	total: 10m 36s	remaining: 6m 10s
6137:	learn: 0.0020482	total: 10m 37s	remaining: 6m 40s
6440:	learn: 0.0015516	total: 10m 36s	remaining: 5m 51s
5860:	learn: 0.0015728	total: 10m 37s	remaining: 7m 29s
6328:	learn: 0.0016246	total: 10m 37s	remaining: 6m 9s
6324:	learn: 0.0015594	total: 10m 36s	remaining: 6m 10s
6138:	learn: 0.0020482	total: 10m 37s	remaining: 6m 40s
6441:	learn: 0.0015512	total: 10m 37s	remaining: 5m 51s
5861:	learn: 0.0015723	total: 10m 37s	remaining: 7m 29s
6325:	learn: 0.0015594	total: 10m 37s	remaining: 6m 9s
6329:	learn: 0.0016242	total: 10m 37s	remaining: 6m 9s
6442:	learn: 0.0015512	total: 10m 37s	remaining: 5m 51s
6139:	learn: 0.0020482	total: 10m 37s	remaining: 6m 40s
5862:	learn: 0.0015723	total: 10m 37s	remaining: 7m 29s
6326:	learn: 0.0015594	total: 10m 37s	remaining: 6m 9s
6330:	learn: 0.0016237	total: 10m 37s	remaining: 6m 9s
6443:	learn: 0.0015512	total: 10m 37s	remaining: 5m 51s
6140:	learn: 0.0020482	total: 10m 37s	remaining: 6m 40s
6327:	learn: 0.0015594	total: 10m 37s	remaining: 6m 9s
5863:	learn: 0.0015720	total: 10m 37s	remaining: 7m 29s
6331:	learn: 0.0016234	total: 10m 37s	remaining: 6m 9s
6444:	learn: 0.0015508	total: 10m 37s	remaining: 5m 51s
6141:	learn: 0.0020482	total: 10m 37s	remaining: 6m 40s
6328:	learn: 0.0015594	total: 10m 37s	remaining: 6m 9s
5864:	learn: 0.0015720	total: 10m 37s	remaining: 7m 29s
6445:	learn: 0.0015508	total: 10m 37s	remaining: 5m 51s
6332:	learn: 0.0016234	total: 10m 37s	remaining: 6m 9s
6142:	learn: 0.0020481	total: 10m 37s	remaining: 6m 40s
5865:	learn: 0.0015715	total: 10m 37s	remaining: 7m 29s
6329:	learn: 0.0015594	total: 10m 37s	remaining: 6m 9s
6333:	learn: 0.0016231	total: 10m 37s	remaining: 6m 9s
6446:	learn: 0.0015508	total: 10m 37s	remaining: 5m 51s
6143:	learn: 0.0020482	total: 10m 37s	remaining: 6m 40s
6330:	learn: 0.0015594	total: 10m 37s	remaining: 6m 9s
5866:	learn: 0.0015715	total: 10m 37s	remaining: 7m 29s
6334:	learn: 0.0016230	total: 10m 37s	remaining: 6m 8s
6447:	learn: 0.0015508	total: 10m 37s	remaining: 5m 51s
6144:	learn: 0.0020482	total: 10m 37s	remaining: 6m 40s
6331:	learn: 0.0015594	total: 10m 37s	remaining: 6m 9s
6335:	learn: 0.0016224	total: 10m 37s	remaining: 6m 8s
5867:	learn: 0.0015713	total: 10m 37s	remaining: 7m 29s
6448:	learn: 0.0015508	total: 10m 37s	remaining: 5m 51s
6145:	learn: 0.0020481	total: 10m 37s	remaining: 6m 40s
6332:	learn: 0.0015590	total: 10m 37s	remaining: 6m 9s
6336:	learn: 0.0016224	total: 10m 37s	remaining: 6m 8s
6449:	learn: 0.0015508	total: 10m 37s	remaining: 5m 51s
5868:	learn: 0.0015713	total: 10m 37s	remaining: 7m 29s
6146:	learn: 0.0020481	total: 10m 37s	remaining: 6m 39s
6337:	learn: 0.0016225	total: 10m 37s	remaining: 6m 8s
6333:	learn: 0.0015590	total: 10m 37s	remaining: 6m 9s
5869:	learn: 0.0015708	total: 10m 38s	remaining: 7m 28s
6147:	learn: 0.0020481	total: 10m 38s	remaining: 6m 39s
6338:	learn: 0.0016224	total: 10m 38s	remaining: 6m 8s
6450:	learn: 0.0015508	total: 10m 38s	remaining: 5m 50s
6334:	learn: 0.0015590	total: 10m 37s	remaining: 6m 9s
5870:	learn: 0.0015703	total: 10m 38s	remaining: 7m 28s
6148:	learn: 0.0020482	total: 10m 38s	remaining: 6m 39s
6339:	learn: 0.0016224	total: 10m 38s	remaining: 6m 8s
6451:	learn: 0.0015509	total: 10m 38s	remaining: 5m 50s
6335:	learn: 0.0015590	total: 10m 38s	remaining: 6m 8s
5871:	learn: 0.0015699	total: 10m 38s	remaining: 7m 28s
6149:	learn: 0.0020482	total: 10m 38s	remaining: 6m 39s

6340:	learn: 0.0016221	total: 10m 38s	remaining: 6m 8s
6452:	learn: 0.0015508	total: 10m 38s	remaining: 5m 50s
5872:	learn: 0.0015695	total: 10m 38s	remaining: 7m 28s
6336:	learn: 0.0015585	total: 10m 38s	remaining: 6m 8s
6341:	learn: 0.0016222	total: 10m 38s	remaining: 6m 8s
6150:	learn: 0.0020481	total: 10m 38s	remaining: 6m 39s
6453:	learn: 0.0015508	total: 10m 38s	remaining: 5m 50s
5873:	learn: 0.0015687	total: 10m 38s	remaining: 7m 28s
6342:	learn: 0.0016222	total: 10m 38s	remaining: 6m 8s
6337:	learn: 0.0015586	total: 10m 38s	remaining: 6m 8s
6151:	learn: 0.0020481	total: 10m 38s	remaining: 6m 39s
6338:	learn: 0.0015586	total: 10m 38s	remaining: 6m 8s
6454:	learn: 0.0015503	total: 10m 38s	remaining: 5m 50s
5874:	learn: 0.0015682	total: 10m 38s	remaining: 7m 28s
6343:	learn: 0.0016222	total: 10m 38s	remaining: 6m 7s
6152:	learn: 0.0020481	total: 10m 38s	remaining: 6m 39s
6455:	learn: 0.0015499	total: 10m 38s	remaining: 5m 50s
6153:	learn: 0.0020481	total: 10m 38s	remaining: 6m 39s
6339:	learn: 0.0015586	total: 10m 38s	remaining: 6m 8s
5875:	learn: 0.0015682	total: 10m 38s	remaining: 7m 28s
6344:	learn: 0.0016222	total: 10m 38s	remaining: 6m 7s
6456:	learn: 0.0015499	total: 10m 38s	remaining: 5m 50s
6154:	learn: 0.0020481	total: 10m 38s	remaining: 6m 39s
6345:	learn: 0.0016221	total: 10m 38s	remaining: 6m 7s
5876:	learn: 0.0015682	total: 10m 38s	remaining: 7m 28s
6340:	learn: 0.0015585	total: 10m 38s	remaining: 6m 8s
6457:	learn: 0.0015499	total: 10m 38s	remaining: 5m 50s
6155:	learn: 0.0020481	total: 10m 38s	remaining: 6m 38s
6341:	learn: 0.0015585	total: 10m 38s	remaining: 6m 8s
6458:	learn: 0.0015499	total: 10m 38s	remaining: 5m 50s
6346:	learn: 0.0016218	total: 10m 38s	remaining: 6m 7s
5877:	learn: 0.0015682	total: 10m 38s	remaining: 7m 28s
6156:	learn: 0.0020481	total: 10m 38s	remaining: 6m 38s
6342:	learn: 0.0015585	total: 10m 38s	remaining: 6m 8s
6347:	learn: 0.0016218	total: 10m 38s	remaining: 6m 7s
6459:	learn: 0.0015499	total: 10m 38s	remaining: 5m 50s
5878:	learn: 0.0015679	total: 10m 39s	remaining: 7m 27s
6157:	learn: 0.0020481	total: 10m 39s	remaining: 6m 38s
6343:	learn: 0.0015585	total: 10m 38s	remaining: 6m 8s
6460:	learn: 0.0015499	total: 10m 38s	remaining: 5m 50s
6348:	learn: 0.0016218	total: 10m 39s	remaining: 6m 7s
5879:	learn: 0.0015679	total: 10m 39s	remaining: 7m 27s
6158:	learn: 0.0020481	total: 10m 39s	remaining: 6m 38s
6461:	learn: 0.0015499	total: 10m 39s	remaining: 5m 49s
6344:	learn: 0.0015584	total: 10m 38s	remaining: 6m 8s
6349:	learn: 0.0016218	total: 10m 39s	remaining: 6m 7s
6159:	learn: 0.0020481	total: 10m 39s	remaining: 6m 38s
5880:	learn: 0.0015677	total: 10m 39s	remaining: 7m 27s
6345:	learn: 0.0015584	total: 10m 39s	remaining: 6m 7s
6462:	learn: 0.0015498	total: 10m 39s	remaining: 5m 49s
6350:	learn: 0.0016218	total: 10m 39s	remaining: 6m 7s
6160:	learn: 0.0020473	total: 10m 39s	remaining: 6m 38s
5881:	learn: 0.0015677	total: 10m 39s	remaining: 7m 27s
6346:	learn: 0.0015584	total: 10m 39s	remaining: 6m 7s
6351:	learn: 0.0016213	total: 10m 39s	remaining: 6m 7s
6463:	learn: 0.0015499	total: 10m 39s	remaining: 5m 49s
5882:	learn: 0.0015670	total: 10m 39s	remaining: 7m 27s
6161:	learn: 0.0020473	total: 10m 39s	remaining: 6m 38s
6464:	learn: 0.0015499	total: 10m 39s	remaining: 5m 49s
6347:	learn: 0.0015584	total: 10m 39s	remaining: 6m 7s
6352:	learn: 0.0016213	total: 10m 39s	remaining: 6m 7s
6162:	learn: 0.0020473	total: 10m 39s	remaining: 6m 38s
5883:	learn: 0.0015666	total: 10m 39s	remaining: 7m 27s
6353:	learn: 0.0016213	total: 10m 39s	remaining: 6m 6s
6348:	learn: 0.0015580	total: 10m 39s	remaining: 6m 7s
6465:	learn: 0.0015498	total: 10m 39s	remaining: 5m 49s
6163:	learn: 0.0020473	total: 10m 39s	remaining: 6m 38s
6354:	learn: 0.0016213	total: 10m 39s	remaining: 6m 6s
5884:	learn: 0.0015661	total: 10m 39s	remaining: 7m 27s
6466:	learn: 0.0015498	total: 10m 39s	remaining: 5m 49s
6349:	learn: 0.0015580	total: 10m 39s	remaining: 6m 7s
6164:	learn: 0.0020473	total: 10m 39s	remaining: 6m 37s
6355:	learn: 0.0016213	total: 10m 39s	remaining: 6m 6s
5885:	learn: 0.0015657	total: 10m 39s	remaining: 7m 27s
6467:	learn: 0.0015498	total: 10m 39s	remaining: 5m 49s
6350:	learn: 0.0015580	total: 10m 39s	remaining: 6m 7s
6165:	learn: 0.0020473	total: 10m 39s	remaining: 6m 37s
6356:	learn: 0.0016213	total: 10m 39s	remaining: 6m 6s
5886:	learn: 0.0015657	total: 10m 39s	remaining: 7m 27s
6351:	learn: 0.0015580	total: 10m 39s	remaining: 6m 7s
6468:	learn: 0.0015497	total: 10m 39s	remaining: 5m 49s
6357:	learn: 0.0016212	total: 10m 39s	remaining: 6m 6s
6166:	learn: 0.0020472	total: 10m 39s	remaining: 6m 37s
6352:	learn: 0.0015580	total: 10m 39s	remaining: 6m 7s
5887:	learn: 0.0015654	total: 10m 39s	remaining: 7m 26s
6469:	learn: 0.0015493	total: 10m 39s	remaining: 5m 49s
6358:	learn: 0.0016209	total: 10m 39s	remaining: 6m 6s
6353:	learn: 0.0015580	total: 10m 39s	remaining: 6m 7s
5888:	learn: 0.0015650	total: 10m 40s	remaining: 7m 26s
6470:	learn: 0.0015493	total: 10m 39s	remaining: 5m 49s
6167:	learn: 0.0020472	total: 10m 40s	remaining: 6m 37s
6359:	learn: 0.0016209	total: 10m 40s	remaining: 6m 6s
6354:	learn: 0.0015580	total: 10m 39s	remaining: 6m 7s
5889:	learn: 0.0015646	total: 10m 40s	remaining: 7m 26s
6471:	learn: 0.0015493	total: 10m 40s	remaining: 5m 48s
6168:	learn: 0.0020472	total: 10m 40s	remaining: 6m 37s
6355:	learn: 0.0015580	total: 10m 39s	remaining: 6m 6s
6360:	learn: 0.0016209	total: 10m 40s	remaining: 6m 6s
6472:	learn: 0.0015493	total: 10m 40s	remaining: 5m 48s
6356:	learn: 0.0015580	total: 10m 40s	remaining: 6m 6s
5890:	learn: 0.0015642	total: 10m 40s	remaining: 7m 26s
6169:	learn: 0.0020473	total: 10m 40s	remaining: 6m 37s
6361:	learn: 0.0016209	total: 10m 40s	remaining: 6m 6s
6473:	learn: 0.0015493	total: 10m 40s	remaining: 5m 48s
6170:	learn: 0.0020472	total: 10m 40s	remaining: 6m 37s
6362:	learn: 0.0016209	total: 10m 40s	remaining: 6m 6s
5891:	learn: 0.0015637	total: 10m 40s	remaining: 7m 26s
6357:	learn: 0.0015577	total: 10m 40s	remaining: 6m 6s
6171:	learn: 0.0020472	total: 10m 40s	remaining: 6m 37s
6474:	learn: 0.0015493	total: 10m 40s	remaining: 5m 48s
6363:	learn: 0.0016209	total: 10m 40s	remaining: 6m 5s
6358:	learn: 0.0015577	total: 10m 40s	remaining: 6m 6s
5892:	learn: 0.0015633	total: 10m 40s	remaining: 7m 26s
6172:	learn: 0.0020472	total: 10m 40s	remaining: 6m 37s
6475:	learn: 0.0015493	total: 10m 40s	remaining: 5m 48s
6364:	learn: 0.0016209	total: 10m 40s	remaining: 6m 5s
5893:	learn: 0.0015633	total: 10m 40s	remaining: 7m 26s
6359:	learn: 0.0015576	total: 10m 40s	remaining: 6m 6s
6476:	learn: 0.0015493	total: 10m 40s	remaining: 5m 48s
6173:	learn: 0.0020472	total: 10m 40s	remaining: 6m 37s
6365:	learn: 0.0016204	total: 10m 40s	remaining: 6m 5s
5894:	learn: 0.0015633	total: 10m 40s	remaining: 7m 26s
6360:	learn: 0.0015575	total: 10m 40s	remaining: 6m 6s
6477:	learn: 0.0015493	total: 10m 40s	remaining: 5m 48s
6366:	learn: 0.0016197	total: 10m 40s	remaining: 6m 5s
6174:	learn: 0.0020473	total: 10m 40s	remaining: 6m 36s
6361:	learn: 0.0015575	total: 10m 40s	remaining: 6m 6s
5895:	learn: 0.0015633	total: 10m 40s	remaining: 7m 26s
6478:	learn: 0.0015491	total: 10m 40s	remaining: 5m 48s
6367:	learn: 0.0016194	total: 10m 40s	remaining: 6m 5s
6175:	learn: 0.0020473	total: 10m 40s	remaining: 6m 36s
6362:	learn: 0.0015570	total: 10m 40s	remaining: 6m 6s
6479:	learn: 0.0015487	total: 10m 40s	remaining: 5m 48s
5896:	learn: 0.0015629	total: 10m 40s	remaining: 7m 25s
6368:	learn: 0.0016194	total: 10m 40s	remaining: 6m 5s
6363:	learn: 0.0015570	total: 10m 40s	remaining: 6m 6s
6176:	learn: 0.0020472	total: 10m 41s	remaining: 6m 36s
6480:	learn: 0.0015487	total: 10m 40s	remaining: 5m 48s
5897:	learn: 0.0015624	total: 10m 41s	remaining: 7m 25s
6369:	learn: 0.0016194	total: 10m 41s	remaining: 6m 5s
6364:	learn: 0.0015571	total: 10m 40s	remaining: 6m 6s
6177:	learn: 0.0020472	total: 10m 41s	remaining: 6m 36s
6481:	learn: 0.0015484	total: 10m 41s	remaining: 5m 47s
6365:	learn: 0.0015571	total: 10m 40s	remaining: 6m 5s
5898:	learn: 0.0015624	total: 10m 41s	remaining: 7m 25s
6370:	learn: 0.0016194	total: 10m 41s	remaining: 6m 5s
6178:	learn: 0.0020473	total: 10m 41s	remaining: 6m 36s
6482:	learn: 0.0015484	total: 10m 41s	remaining: 5m 47s
6366:	learn: 0.0015571	total: 10m 41s	remaining: 6m 5s
6371:	learn: 0.0016194	total: 10m 41s	remaining: 6m 5s
5899:	learn: 0.0015624	total: 10m 41s	remaining: 7m 25s
6367:	learn: 0.0015570	total: 10m 41s	remaining: 6m 5s
6179:	learn: 0.0020472	total: 10m 41s	remaining: 6m 36s
6483:	learn: 0.0015484	total: 10m 41s	remaining: 5m 47s
6372:	learn: 0.0016194	total: 10m 41s	remaining: 6m 5s
5900:	learn: 0.0015624	total: 10m 41s	remaining: 7m 25s
6484:	learn: 0.0015483	total: 10m 41s	remaining: 5m 47s
6368:	learn: 0.0015566	total: 10m 41s	remaining: 6m 5s
6180:	learn: 0.0020472	total: 10m 41s	remaining: 6m 36s
6485:	learn: 0.0015483	total: 10m 41s	remaining: 5m 47s
6373:	learn: 0.0016194	total: 10m 41s	remaining: 6m 4s
5901:	learn: 0.0015621	total: 10m 41s	remaining: 7m 25s
6369:	learn: 0.0015566	total: 10m 41s	remaining: 6m 5s
6181:	learn: 0.0020473	total: 10m 41s	remaining: 6m 36s
6486:	learn: 0.0015483	total: 10m 41s	remaining: 5m 47s
6374:	learn: 0.0016194	total: 10m 41s	remaining: 6m 4s
5902:	learn: 0.0015616	total: 10m 41s	remaining: 7m 25s
6487:	learn: 0.0015483	total: 10m 41s	remaining: 5m 47s
6370:	learn: 0.0015566	total: 10m 41s	remaining: 6m 5s
6182:	learn: 0.0020472	total: 10m 41s	remaining: 6m 36s
6375:	learn: 0.0016194	total: 10m 41s	remaining: 6m 4s
5903:	learn: 0.0015615	total: 10m 41s	remaining: 7m 25s
6183:	learn: 0.0020472	total: 10m 41s	remaining: 6m 36s
6371:	learn: 0.0015566	total: 10m 41s	remaining: 6m 5s
6488:	learn: 0.0015483	total: 10m 41s	remaining: 5m 47s
6376:	learn: 0.0016194	total: 10m 41s	remaining: 6m 4s
6184:	learn: 0.0020472	total: 10m 41s	remaining: 6m 35s
6489:	learn: 0.0015483	total: 10m 41s	remaining: 5m 47s
6372:	learn: 0.0015562	total: 10m 41s	remaining: 6m 5s
5904:	learn: 0.0015615	total: 10m 41s	remaining: 7m 25s
6377:	learn: 0.0016194	total: 10m 41s	remaining: 6m 4s
6185:	learn: 0.0020472	total: 10m 41s	remaining: 6m 35s
6373:	learn: 0.0015562	total: 10m 41s	remaining: 6m 5s
6490:	learn: 0.0015483	total: 10m 41s	remaining: 5m 46s
5905:	learn: 0.0015612	total: 10m 41s	remaining: 7m 25s
6378:	learn: 0.0016193	total: 10m 42s	remaining: 6m 4s
6491:	learn: 0.0015483	total: 10m 41s	remaining: 5m 46s
6186:	learn: 0.0020472	total: 10m 42s	remaining: 6m 35s
5906:	learn: 0.0015612	total: 10m 42s	remaining: 7m 24s
6374:	learn: 0.0015562	total: 10m 41s	remaining: 6m 4s
6492:	learn: 0.0015482	total: 10m 42s	remaining: 5m 46s
6187:	learn: 0.0020472	total: 10m 42s	remaining: 6m 35s
6375:	learn: 0.0015562	total: 10m 41s	remaining: 6m 4s
6379:	learn: 0.0016193	total: 10m 42s	remaining: 6m 4s
5907:	learn: 0.0015608	total: 10m 42s	remaining: 7m 24s
6493:	learn: 0.0015482	total: 10m 42s	remaining: 5m 46s
6188:	learn: 0.0020472	total: 10m 42s	remaining: 6m 35s
6376:	learn: 0.0015562	total: 10m 42s	remaining: 6m 4s
6380:	learn: 0.0016193	total: 10m 42s	remaining: 6m 4s
5908:	learn: 0.0015603	total: 10m 42s	remaining: 7m 24s
6494:	learn: 0.0015482	total: 10m 42s	remaining: 5m 46s
6377:	learn: 0.0015562	total: 10m 42s	remaining: 6m 4s
6189:	learn: 0.0020472	total: 10m 42s	remaining: 6m 35s
5909:	learn: 0.0015600	total: 10m 42s	remaining: 7m 24s
6381:	learn: 0.0016193	total: 10m 42s	remaining: 6m 4s
6378:	learn: 0.0015562	total: 10m 42s	remaining: 6m 4s
6495:	learn: 0.0015482	total: 10m 42s	remaining: 5m 46s
6190:	learn: 0.0020472	total: 10m 42s	remaining: 6m 35s
5910:	learn: 0.0015598	total: 10m 42s	remaining: 7m 24s
6496:	learn: 0.0015482	total: 10m 42s	remaining: 5m 46s
6382:	learn: 0.0016193	total: 10m 42s	remaining: 6m 4s
6379:	learn: 0.0015561	total: 10m 42s	remaining: 6m 4s
6191:	learn: 0.0020472	total: 10m 42s	remaining: 6m 35s
6383:	learn: 0.0016193	total: 10m 42s	remaining: 6m 3s
6497:	learn: 0.0015482	total: 10m 42s	remaining: 5m 46s
5911:	learn: 0.0015598	total: 10m 42s	remaining: 7m 24s
6380:	learn: 0.0015561	total: 10m 42s	remaining: 6m 4s
6192:	learn: 0.0020472	total: 10m 42s	remaining: 6m 35s
6498:	learn: 0.0015479	total: 10m 42s	remaining: 5m 46s
6384:	learn: 0.0016192	total: 10m 42s	remaining: 6m 3s
5912:	learn: 0.0015598	total: 10m 42s	remaining: 7m 24s
6193:	learn: 0.0020472	total: 10m 42s	remaining: 6m 34s
6381:	learn: 0.0015561	total: 10m 42s	remaining: 6m 4s
6499:	learn: 0.0015479	total: 10m 42s	remaining: 5m 46s
6385:	learn: 0.0016192	total: 10m 42s	remaining: 6m 3s
6194:	learn: 0.0020472	total: 10m 42s	remaining: 6m 34s
6382:	learn: 0.0015561	total: 10m 42s	remaining: 6m 4s
5913:	learn: 0.0015595	total: 10m 42s	remaining: 7m 24s
6386:	learn: 0.0016190	total: 10m 42s	remaining: 6m 3s
6500:	learn: 0.0015476	total: 10m 42s	remaining: 5m 45s
5914:	learn: 0.0015595	total: 10m 42s	remaining: 7m 24s
6195:	learn: 0.0020472	total: 10m 42s	remaining: 6m 34s
6383:	learn: 0.0015561	total: 10m 42s	remaining: 6m 4s
6387:	learn: 0.0016190	total: 10m 42s	remaining: 6m 3s
6501:	learn: 0.0015476	total: 10m 42s	remaining: 5m 45s
6196:	learn: 0.0020472	total: 10m 43s	remaining: 6m 34s
6384:	learn: 0.0015561	total: 10m 42s	remaining: 6m 3s
5915:	learn: 0.0015595	total: 10m 43s	remaining: 7m 23s
6388:	learn: 0.0016185	total: 10m 43s	remaining: 6m 3s
6502:	learn: 0.0015472	total: 10m 43s	remaining: 5m 45s
6197:	learn: 0.0020472	total: 10m 43s	remaining: 6m 34s
6385:	learn: 0.0015561	total: 10m 42s	remaining: 6m 3s
6389:	learn: 0.0016185	total: 10m 43s	remaining: 6m 3s
5916:	learn: 0.0015591	total: 10m 43s	remaining: 7m 23s
6198:	learn: 0.0020472	total: 10m 43s	remaining: 6m 34s
6503:	learn: 0.0015472	total: 10m 43s	remaining: 5m 45s
6390:	learn: 0.0016185	total: 10m 43s	remaining: 6m 3s
6386:	learn: 0.0015561	total: 10m 43s	remaining: 6m 3s
6504:	learn: 0.0015472	total: 10m 43s	remaining: 5m 45s
5917:	learn: 0.0015591	total: 10m 43s	remaining: 7m 23s
6199:	learn: 0.0020472	total: 10m 43s	remaining: 6m 34s
6505:	learn: 0.0015472	total: 10m 43s	remaining: 5m 45s
6391:	learn: 0.0016185	total: 10m 43s	remaining: 6m 3s
6387:	learn: 0.0015561	total: 10m 43s	remaining: 6m 3s
5918:	learn: 0.0015586	total: 10m 43s	remaining: 7m 23s
6200:	learn: 0.0020472	total: 10m 43s	remaining: 6m 34s
6506:	learn: 0.0015472	total: 10m 43s	remaining: 5m 45s
6392:	learn: 0.0016183	total: 10m 43s	remaining: 6m 3s
6388:	learn: 0.0015561	total: 10m 43s	remaining: 6m 3s
5919:	learn: 0.0015586	total: 10m 43s	remaining: 7m 23s
6201:	learn: 0.0020472	total: 10m 43s	remaining: 6m 34s
6389:	learn: 0.0015561	total: 10m 43s	remaining: 6m 3s
6507:	learn: 0.0015472	total: 10m 43s	remaining: 5m 45s
6393:	learn: 0.0016183	total: 10m 43s	remaining: 6m 2s
6202:	learn: 0.0020472	total: 10m 43s	remaining: 6m 33s
5920:	learn: 0.0015584	total: 10m 43s	remaining: 7m 23s
6390:	learn: 0.0015557	total: 10m 43s	remaining: 6m 3s
6508:	learn: 0.0015472	total: 10m 43s	remaining: 5m 45s
6203:	learn: 0.0020472	total: 10m 43s	remaining: 6m 33s
6394:	learn: 0.0016183	total: 10m 43s	remaining: 6m 2s
6509:	learn: 0.0015472	total: 10m 43s	remaining: 5m 45s
5921:	learn: 0.0015584	total: 10m 43s	remaining: 7m 23s
6391:	learn: 0.0015557	total: 10m 43s	remaining: 6m 3s
6510:	learn: 0.0015472	total: 10m 43s	remaining: 5m 44s
6204:	learn: 0.0020472	total: 10m 43s	remaining: 6m 33s
5922:	learn: 0.0015579	total: 10m 43s	remaining: 7m 23s
6395:	learn: 0.0016183	total: 10m 43s	remaining: 6m 2s
6392:	learn: 0.0015557	total: 10m 43s	remaining: 6m 3s
6511:	learn: 0.0015472	total: 10m 43s	remaining: 5m 44s
6205:	learn: 0.0020472	total: 10m 43s	remaining: 6m 33s
6396:	learn: 0.0016180	total: 10m 43s	remaining: 6m 2s
5923:	learn: 0.0015575	total: 10m 43s	remaining: 7m 23s
6393:	learn: 0.0015557	total: 10m 43s	remaining: 6m 3s
6512:	learn: 0.0015472	total: 10m 43s	remaining: 5m 44s
5924:	learn: 0.0015575	total: 10m 44s	remaining: 7m 22s
6206:	learn: 0.0020472	total: 10m 44s	remaining: 6m 33s
6397:	learn: 0.0016180	total: 10m 43s	remaining: 6m 2s
6394:	learn: 0.0015557	total: 10m 43s	remaining: 6m 2s
6513:	learn: 0.0015472	total: 10m 43s	remaining: 5m 44s
5925:	learn: 0.0015569	total: 10m 44s	remaining: 7m 22s
6207:	learn: 0.0020472	total: 10m 44s	remaining: 6m 33s
6395:	learn: 0.0015557	total: 10m 43s	remaining: 6m 2s
6398:	learn: 0.0016180	total: 10m 44s	remaining: 6m 2s
6514:	learn: 0.0015472	total: 10m 44s	remaining: 5m 44s

5926:	learn: 0.0015569	total: 10m 44s	remaining: 7m 22s
6515:	learn: 0.0015472	total: 10m 44s	remaining: 5m 44s
6396:	learn: 0.0015557	total: 10m 44s	remaining: 6m 2s
6208:	learn: 0.0020472	total: 10m 44s	remaining: 6m 33s
6399:	learn: 0.0016180	total: 10m 44s	remaining: 6m 2s
5927:	learn: 0.0015569	total: 10m 44s	remaining: 7m 22s
6397:	learn: 0.0015554	total: 10m 44s	remaining: 6m 2s
6516:	learn: 0.0015472	total: 10m 44s	remaining: 5m 44s
6209:	learn: 0.0020472	total: 10m 44s	remaining: 6m 33s
6400:	learn: 0.0016180	total: 10m 44s	remaining: 6m 2s
6398:	learn: 0.0015554	total: 10m 44s	remaining: 6m 2s
5928:	learn: 0.0015564	total: 10m 44s	remaining: 7m 22s
6517:	learn: 0.0015472	total: 10m 44s	remaining: 5m 44s
6401:	learn: 0.0016180	total: 10m 44s	remaining: 6m 2s
6210:	learn: 0.0020472	total: 10m 44s	remaining: 6m 33s
6399:	learn: 0.0015554	total: 10m 44s	remaining: 6m 2s
6518:	learn: 0.0015468	total: 10m 44s	remaining: 5m 44s
5929:	learn: 0.0015559	total: 10m 44s	remaining: 7m 22s
6211:	learn: 0.0020472	total: 10m 44s	remaining: 6m 33s
6402:	learn: 0.0016180	total: 10m 44s	remaining: 6m 2s
6519:	learn: 0.0015468	total: 10m 44s	remaining: 5m 43s
6400:	learn: 0.0015554	total: 10m 44s	remaining: 6m 2s
6212:	learn: 0.0020472	total: 10m 44s	remaining: 6m 32s
6520:	learn: 0.0015468	total: 10m 44s	remaining: 5m 43s
5930:	learn: 0.0015554	total: 10m 44s	remaining: 7m 22s
6403:	learn: 0.0016180	total: 10m 44s	remaining: 6m 1s
6401:	learn: 0.0015549	total: 10m 44s	remaining: 6m 2s
6521:	learn: 0.0015468	total: 10m 44s	remaining: 5m 43s
6213:	learn: 0.0020472	total: 10m 44s	remaining: 6m 32s
5931:	learn: 0.0015552	total: 10m 44s	remaining: 7m 22s
6404:	learn: 0.0016180	total: 10m 44s	remaining: 6m 1s
6214:	learn: 0.0020472	total: 10m 44s	remaining: 6m 32s
6522:	learn: 0.0015468	total: 10m 44s	remaining: 5m 43s
6402:	learn: 0.0015549	total: 10m 44s	remaining: 6m 2s
5932:	learn: 0.0015549	total: 10m 44s	remaining: 7m 22s
6405:	learn: 0.0016180	total: 10m 44s	remaining: 6m 1s
6215:	learn: 0.0020472	total: 10m 44s	remaining: 6m 32s
6523:	learn: 0.0015468	total: 10m 44s	remaining: 5m 43s
6403:	learn: 0.0015549	total: 10m 44s	remaining: 6m 2s
6406:	learn: 0.0016180	total: 10m 44s	remaining: 6m 1s
5933:	learn: 0.0015545	total: 10m 45s	remaining: 7m 21s
6216:	learn: 0.0020472	total: 10m 44s	remaining: 6m 32s
6524:	learn: 0.0015468	total: 10m 44s	remaining: 5m 43s
6404:	learn: 0.0015549	total: 10m 44s	remaining: 6m 1s
6407:	learn: 0.0016175	total: 10m 45s	remaining: 6m 1s
6217:	learn: 0.0020472	total: 10m 45s	remaining: 6m 32s
6525:	learn: 0.0015468	total: 10m 45s	remaining: 5m 43s
5934:	learn: 0.0015541	total: 10m 45s	remaining: 7m 21s
6405:	learn: 0.0015549	total: 10m 44s	remaining: 6m 1s
6408:	learn: 0.0016173	total: 10m 45s	remaining: 6m 1s
6526:	learn: 0.0015468	total: 10m 45s	remaining: 5m 43s
6218:	learn: 0.0020472	total: 10m 45s	remaining: 6m 32s
6406:	learn: 0.0015549	total: 10m 45s	remaining: 6m 1s
6409:	learn: 0.0016171	total: 10m 45s	remaining: 6m 1s
5935:	learn: 0.0015537	total: 10m 45s	remaining: 7m 21s
6527:	learn: 0.0015468	total: 10m 45s	remaining: 5m 43s
6219:	learn: 0.0020472	total: 10m 45s	remaining: 6m 32s
6410:	learn: 0.0016172	total: 10m 45s	remaining: 6m 1s
5936:	learn: 0.0015537	total: 10m 45s	remaining: 7m 21s
6407:	learn: 0.0015549	total: 10m 45s	remaining: 6m 1s
6528:	learn: 0.0015468	total: 10m 45s	remaining: 5m 43s
5937:	learn: 0.0015532	total: 10m 45s	remaining: 7m 21s
6408:	learn: 0.0015549	total: 10m 45s	remaining: 6m 1s
6220:	learn: 0.0020472	total: 10m 45s	remaining: 6m 32s
6411:	learn: 0.0016167	total: 10m 45s	remaining: 6m 1s
5938:	learn: 0.0015532	total: 10m 45s	remaining: 7m 21s
6529:	learn: 0.0015468	total: 10m 45s	remaining: 5m 42s
6409:	learn: 0.0015549	total: 10m 45s	remaining: 6m 1s
6221:	learn: 0.0020472	total: 10m 45s	remaining: 6m 31s
6412:	learn: 0.0016167	total: 10m 45s	remaining: 6m 1s
6530:	learn: 0.0015468	total: 10m 45s	remaining: 5m 42s
5939:	learn: 0.0015527	total: 10m 45s	remaining: 7m 21s
6222:	learn: 0.0020472	total: 10m 45s	remaining: 6m 31s
6413:	learn: 0.0016167	total: 10m 45s	remaining: 6m
6410:	learn: 0.0015549	total: 10m 45s	remaining: 6m 1s
6531:	learn: 0.0015466	total: 10m 45s	remaining: 5m 42s
6414:	learn: 0.0016164	total: 10m 45s	remaining: 6m
5940:	learn: 0.0015522	total: 10m 45s	remaining: 7m 21s
6223:	learn: 0.0020472	total: 10m 45s	remaining: 6m 31s
6411:	learn: 0.0015549	total: 10m 45s	remaining: 6m 1s
6532:	learn: 0.0015466	total: 10m 45s	remaining: 5m 42s
6412:	learn: 0.0015548	total: 10m 45s	remaining: 6m 1s
5941:	learn: 0.0015517	total: 10m 45s	remaining: 7m 21s
6415:	learn: 0.0016164	total: 10m 45s	remaining: 6m
6224:	learn: 0.0020472	total: 10m 45s	remaining: 6m 31s
6533:	learn: 0.0015466	total: 10m 45s	remaining: 5m 42s
6413:	learn: 0.0015548	total: 10m 45s	remaining: 6m
6416:	learn: 0.0016161	total: 10m 45s	remaining: 6m
5942:	learn: 0.0015512	total: 10m 45s	remaining: 7m 20s
6225:	learn: 0.0020472	total: 10m 45s	remaining: 6m 31s
6534:	learn: 0.0015466	total: 10m 45s	remaining: 5m 42s
6414:	learn: 0.0015548	total: 10m 45s	remaining: 6m
5943:	learn: 0.0015512	total: 10m 46s	remaining: 7m 20s
6226:	learn: 0.0020472	total: 10m 46s	remaining: 6m 31s
6417:	learn: 0.0016161	total: 10m 46s	remaining: 6m
6535:	learn: 0.0015466	total: 10m 45s	remaining: 5m 42s
6415:	learn: 0.0015548	total: 10m 45s	remaining: 6m
6418:	learn: 0.0016161	total: 10m 46s	remaining: 6m
5944:	learn: 0.0015508	total: 10m 46s	remaining: 7m 20s
6536:	learn: 0.0015466	total: 10m 46s	remaining: 5m 42s
6227:	learn: 0.0020472	total: 10m 46s	remaining: 6m 31s
6416:	learn: 0.0015548	total: 10m 46s	remaining: 6m
6537:	learn: 0.0015466	total: 10m 46s	remaining: 5m 42s
6419:	learn: 0.0016161	total: 10m 46s	remaining: 6m
6228:	learn: 0.0020472	total: 10m 46s	remaining: 6m 31s
5945:	learn: 0.0015508	total: 10m 46s	remaining: 7m 20s
6538:	learn: 0.0015466	total: 10m 46s	remaining: 5m 42s
6417:	learn: 0.0015548	total: 10m 46s	remaining: 6m
6420:	learn: 0.0016161	total: 10m 46s	remaining: 6m
6229:	learn: 0.0020472	total: 10m 46s	remaining: 6m 31s
5946:	learn: 0.0015504	total: 10m 46s	remaining: 7m 20s
6539:	learn: 0.0015465	total: 10m 46s	remaining: 5m 41s
6418:	learn: 0.0015547	total: 10m 46s	remaining: 6m
6230:	learn: 0.0020472	total: 10m 46s	remaining: 6m 31s
6421:	learn: 0.0016161	total: 10m 46s	remaining: 6m
5947:	learn: 0.0015504	total: 10m 46s	remaining: 7m 20s
6540:	learn: 0.0015465	total: 10m 46s	remaining: 5m 41s
6419:	learn: 0.0015543	total: 10m 46s	remaining: 6m
6422:	learn: 0.0016161	total: 10m 46s	remaining: 6m
6231:	learn: 0.0020472	total: 10m 46s	remaining: 6m 30s
5948:	learn: 0.0015499	total: 10m 46s	remaining: 7m 20s
6541:	learn: 0.0015465	total: 10m 46s	remaining: 5m 41s
6420:	learn: 0.0015543	total: 10m 46s	remaining: 6m
6423:	learn: 0.0016161	total: 10m 46s	remaining: 5m 59s
6232:	learn: 0.0020472	total: 10m 46s	remaining: 6m 30s
6542:	learn: 0.0015466	total: 10m 46s	remaining: 5m 41s
5949:	learn: 0.0015494	total: 10m 46s	remaining: 7m 20s
6424:	learn: 0.0016161	total: 10m 46s	remaining: 5m 59s
6421:	learn: 0.0015542	total: 10m 46s	remaining: 6m
6233:	learn: 0.0020472	total: 10m 46s	remaining: 6m 30s
6543:	learn: 0.0015466	total: 10m 46s	remaining: 5m 41s
6422:	learn: 0.0015542	total: 10m 46s	remaining: 6m
6425:	learn: 0.0016161	total: 10m 46s	remaining: 5m 59s
5950:	learn: 0.0015490	total: 10m 46s	remaining: 7m 20s
6234:	learn: 0.0020472	total: 10m 46s	remaining: 6m 30s
6544:	learn: 0.0015465	total: 10m 46s	remaining: 5m 41s
6423:	learn: 0.0015542	total: 10m 46s	remaining: 5m 59s
5951:	learn: 0.0015486	total: 10m 46s	remaining: 7m 19s
6426:	learn: 0.0016161	total: 10m 46s	remaining: 5m 59s
6235:	learn: 0.0020472	total: 10m 46s	remaining: 6m 30s
6545:	learn: 0.0015466	total: 10m 46s	remaining: 5m 41s
6424:	learn: 0.0015542	total: 10m 46s	remaining: 5m 59s
6236:	learn: 0.0020472	total: 10m 47s	remaining: 6m 30s
5952:	learn: 0.0015483	total: 10m 47s	remaining: 7m 19s
6427:	learn: 0.0016161	total: 10m 47s	remaining: 5m 59s
6546:	learn: 0.0015466	total: 10m 46s	remaining: 5m 41s
6425:	learn: 0.0015542	total: 10m 46s	remaining: 5m 59s
6237:	learn: 0.0020472	total: 10m 47s	remaining: 6m 30s
5953:	learn: 0.0015479	total: 10m 47s	remaining: 7m 19s
6428:	learn: 0.0016161	total: 10m 47s	remaining: 5m 59s
6547:	learn: 0.0015462	total: 10m 47s	remaining: 5m 41s
6429:	learn: 0.0016161	total: 10m 47s	remaining: 5m 59s
6426:	learn: 0.0015542	total: 10m 47s	remaining: 5m 59s
6238:	learn: 0.0020472	total: 10m 47s	remaining: 6m 30s
5954:	learn: 0.0015479	total: 10m 47s	remaining: 7m 19s
6548:	learn: 0.0015462	total: 10m 47s	remaining: 5m 41s
6430:	learn: 0.0016161	total: 10m 47s	remaining: 5m 59s
6427:	learn: 0.0015542	total: 10m 47s	remaining: 5m 59s
6239:	learn: 0.0020472	total: 10m 47s	remaining: 6m 30s
6549:	learn: 0.0015462	total: 10m 47s	remaining: 5m 40s
5955:	learn: 0.0015475	total: 10m 47s	remaining: 7m 19s
6431:	learn: 0.0016161	total: 10m 47s	remaining: 5m 59s
6428:	learn: 0.0015542	total: 10m 47s	remaining: 5m 59s
6240:	learn: 0.0020472	total: 10m 47s	remaining: 6m 29s
6550:	learn: 0.0015458	total: 10m 47s	remaining: 5m 40s
5956:	learn: 0.0015475	total: 10m 47s	remaining: 7m 19s
6432:	learn: 0.0016161	total: 10m 47s	remaining: 5m 59s
6241:	learn: 0.0020472	total: 10m 47s	remaining: 6m 29s
6429:	learn: 0.0015542	total: 10m 47s	remaining: 5m 59s
6551:	learn: 0.0015458	total: 10m 47s	remaining: 5m 40s
5957:	learn: 0.0015475	total: 10m 47s	remaining: 7m 19s
6433:	learn: 0.0016161	total: 10m 47s	remaining: 5m 58s
6242:	learn: 0.0020472	total: 10m 47s	remaining: 6m 29s
6430:	learn: 0.0015542	total: 10m 47s	remaining: 5m 59s
6434:	learn: 0.0016161	total: 10m 47s	remaining: 5m 58s
6552:	learn: 0.0015458	total: 10m 47s	remaining: 5m 40s
5958:	learn: 0.0015474	total: 10m 47s	remaining: 7m 19s
6431:	learn: 0.0015542	total: 10m 47s	remaining: 5m 59s
6243:	learn: 0.0020472	total: 10m 47s	remaining: 6m 29s
6435:	learn: 0.0016161	total: 10m 47s	remaining: 5m 58s
6553:	learn: 0.0015454	total: 10m 47s	remaining: 5m 40s
6432:	learn: 0.0015539	total: 10m 47s	remaining: 5m 59s
5959:	learn: 0.0015470	total: 10m 47s	remaining: 7m 19s
6244:	learn: 0.0020472	total: 10m 47s	remaining: 6m 29s
6554:	learn: 0.0015454	total: 10m 47s	remaining: 5m 40s
6436:	learn: 0.0016161	total: 10m 47s	remaining: 5m 58s
6433:	learn: 0.0015538	total: 10m 47s	remaining: 5m 58s
5960:	learn: 0.0015469	total: 10m 47s	remaining: 7m 19s
6245:	learn: 0.0020472	total: 10m 47s	remaining: 6m 29s
6555:	learn: 0.0015454	total: 10m 47s	remaining: 5m 40s
6437:	learn: 0.0016161	total: 10m 47s	remaining: 5m 58s
6434:	learn: 0.0015538	total: 10m 47s	remaining: 5m 58s
6246:	learn: 0.0020472	total: 10m 48s	remaining: 6m 29s
5961:	learn: 0.0015466	total: 10m 48s	remaining: 7m 18s
6556:	learn: 0.0015454	total: 10m 47s	remaining: 5m 40s
6438:	learn: 0.0016161	total: 10m 48s	remaining: 5m 58s
6435:	learn: 0.0015538	total: 10m 47s	remaining: 5m 58s
6247:	learn: 0.0020472	total: 10m 48s	remaining: 6m 29s
6557:	learn: 0.0015454	total: 10m 48s	remaining: 5m 40s
5962:	learn: 0.0015466	total: 10m 48s	remaining: 7m 18s
6439:	learn: 0.0016161	total: 10m 48s	remaining: 5m 58s
6436:	learn: 0.0015538	total: 10m 47s	remaining: 5m 58s
6558:	learn: 0.0015454	total: 10m 48s	remaining: 5m 40s
5963:	learn: 0.0015461	total: 10m 48s	remaining: 7m 18s
6248:	learn: 0.0020472	total: 10m 48s	remaining: 6m 29s
6440:	learn: 0.0016161	total: 10m 48s	remaining: 5m 58s
6437:	learn: 0.0015538	total: 10m 48s	remaining: 5m 58s
6559:	learn: 0.0015454	total: 10m 48s	remaining: 5m 39s
6441:	learn: 0.0016161	total: 10m 48s	remaining: 5m 58s
5964:	learn: 0.0015461	total: 10m 48s	remaining: 7m 18s
6438:	learn: 0.0015538	total: 10m 48s	remaining: 5m 58s
6249:	learn: 0.0020472	total: 10m 48s	remaining: 6m 29s
6560:	learn: 0.0015454	total: 10m 48s	remaining: 5m 39s
5965:	learn: 0.0015458	total: 10m 48s	remaining: 7m 18s
6442:	learn: 0.0016161	total: 10m 48s	remaining: 5m 57s
6250:	learn: 0.0020472	total: 10m 48s	remaining: 6m 28s
6439:	learn: 0.0015538	total: 10m 48s	remaining: 5m 58s
6561:	learn: 0.0015454	total: 10m 48s	remaining: 5m 39s
5966:	learn: 0.0015458	total: 10m 48s	remaining: 7m 18s
6443:	learn: 0.0016157	total: 10m 48s	remaining: 5m 57s
6251:	learn: 0.0020472	total: 10m 48s	remaining: 6m 28s
6440:	learn: 0.0015538	total: 10m 48s	remaining: 5m 58s
5967:	learn: 0.0015458	total: 10m 48s	remaining: 7m 18s
6562:	learn: 0.0015454	total: 10m 48s	remaining: 5m 39s
6444:	learn: 0.0016153	total: 10m 48s	remaining: 5m 57s
6252:	learn: 0.0020472	total: 10m 48s	remaining: 6m 28s
6441:	learn: 0.0015538	total: 10m 48s	remaining: 5m 58s
6563:	learn: 0.0015451	total: 10m 48s	remaining: 5m 39s
5968:	learn: 0.0015455	total: 10m 48s	remaining: 7m 18s
6445:	learn: 0.0016153	total: 10m 48s	remaining: 5m 57s
6442:	learn: 0.0015538	total: 10m 48s	remaining: 5m 58s
6253:	learn: 0.0020472	total: 10m 48s	remaining: 6m 28s
6564:	learn: 0.0015446	total: 10m 48s	remaining: 5m 39s
6446:	learn: 0.0016148	total: 10m 48s	remaining: 5m 57s
5969:	learn: 0.0015451	total: 10m 48s	remaining: 7m 18s
6443:	learn: 0.0015536	total: 10m 48s	remaining: 5m 57s
6254:	learn: 0.0020472	total: 10m 48s	remaining: 6m 28s
6565:	learn: 0.0015440	total: 10m 48s	remaining: 5m 39s
6447:	learn: 0.0016143	total: 10m 48s	remaining: 5m 57s
6444:	learn: 0.0015536	total: 10m 48s	remaining: 5m 57s
5970:	learn: 0.0015449	total: 10m 48s	remaining: 7m 17s
6255:	learn: 0.0020472	total: 10m 49s	remaining: 6m 28s
6566:	learn: 0.0015440	total: 10m 48s	remaining: 5m 39s
6448:	learn: 0.0016143	total: 10m 49s	remaining: 5m 57s
5971:	learn: 0.0015449	total: 10m 49s	remaining: 7m 17s
6445:	learn: 0.0015536	total: 10m 48s	remaining: 5m 57s
6256:	learn: 0.0020472	total: 10m 49s	remaining: 6m 28s
6567:	learn: 0.0015440	total: 10m 49s	remaining: 5m 39s
6449:	learn: 0.0016143	total: 10m 49s	remaining: 5m 57s
6446:	learn: 0.0015536	total: 10m 48s	remaining: 5m 57s
5972:	learn: 0.0015444	total: 10m 49s	remaining: 7m 17s
6257:	learn: 0.0020472	total: 10m 49s	remaining: 6m 28s
6568:	learn: 0.0015440	total: 10m 49s	remaining: 5m 39s
6450:	learn: 0.0016143	total: 10m 49s	remaining: 5m 57s
6447:	learn: 0.0015536	total: 10m 49s	remaining: 5m 57s
5973:	learn: 0.0015441	total: 10m 49s	remaining: 7m 17s
6569:	learn: 0.0015440	total: 10m 49s	remaining: 5m 38s
6258:	learn: 0.0020472	total: 10m 49s	remaining: 6m 28s
6451:	learn: 0.0016143	total: 10m 49s	remaining: 5m 57s
6448:	learn: 0.0015536	total: 10m 49s	remaining: 5m 57s
5974:	learn: 0.0015438	total: 10m 49s	remaining: 7m 17s
6570:	learn: 0.0015440	total: 10m 49s	remaining: 5m 38s
6259:	learn: 0.0020472	total: 10m 49s	remaining: 6m 27s
6452:	learn: 0.0016143	total: 10m 49s	remaining: 5m 56s
6449:	learn: 0.0015536	total: 10m 49s	remaining: 5m 57s
6571:	learn: 0.0015440	total: 10m 49s	remaining: 5m 38s
5975:	learn: 0.0015434	total: 10m 49s	remaining: 7m 17s
6260:	learn: 0.0020472	total: 10m 49s	remaining: 6m 27s
6453:	learn: 0.0016140	total: 10m 49s	remaining: 5m 56s
6450:	learn: 0.0015536	total: 10m 49s	remaining: 5m 57s
6572:	learn: 0.0015440	total: 10m 49s	remaining: 5m 38s
5976:	learn: 0.0015429	total: 10m 49s	remaining: 7m 17s
6261:	learn: 0.0020472	total: 10m 49s	remaining: 6m 27s
6454:	learn: 0.0016140	total: 10m 49s	remaining: 5m 56s
6451:	learn: 0.0015536	total: 10m 49s	remaining: 5m 57s
6573:	learn: 0.0015440	total: 10m 49s	remaining: 5m 38s
6452:	learn: 0.0015536	total: 10m 49s	remaining: 5m 57s
5977:	learn: 0.0015425	total: 10m 49s	remaining: 7m 17s
6262:	learn: 0.0020472	total: 10m 49s	remaining: 6m 27s
6455:	learn: 0.0016140	total: 10m 49s	remaining: 5m 56s
6574:	learn: 0.0015440	total: 10m 49s	remaining: 5m 38s
5978:	learn: 0.0015420	total: 10m 49s	remaining: 7m 17s
6453:	learn: 0.0015536	total: 10m 49s	remaining: 5m 56s
6456:	learn: 0.0016140	total: 10m 49s	remaining: 5m 56s
6263:	learn: 0.0020472	total: 10m 49s	remaining: 6m 27s
6575:	learn: 0.0015440	total: 10m 49s	remaining: 5m 38s
5979:	learn: 0.0015417	total: 10m 49s	remaining: 7m 16s
6454:	learn: 0.0015536	total: 10m 49s	remaining: 5m 56s
6457:	learn: 0.0016140	total: 10m 49s	remaining: 5m 56s
6264:	learn: 0.0020472	total: 10m 49s	remaining: 6m 27s
6576:	learn: 0.0015440	total: 10m 49s	remaining: 5m 38s
6455:	learn: 0.0015532	total: 10m 49s	remaining: 5m 56s
6577:	learn: 0.0015440	total: 10m 49s	remaining: 5m 38s
5980:	learn: 0.0015411	total: 10m 50s	remaining: 7m 16s

6265:	learn: 0.0020472	total: 10m 50s	remaining: 6m 27s
6458:	learn: 0.0016140	total: 10m 50s	remaining: 5m 56s
6456:	learn: 0.0015529	total: 10m 49s	remaining: 5m 56s
6578:	learn: 0.0015436	total: 10m 50s	remaining: 5m 38s
6266:	learn: 0.0020472	total: 10m 50s	remaining: 6m 27s
5981:	learn: 0.0015407	total: 10m 50s	remaining: 7m 16s
6459:	learn: 0.0016140	total: 10m 50s	remaining: 5m 56s
6457:	learn: 0.0015529	total: 10m 49s	remaining: 5m 56s
6579:	learn: 0.0015431	total: 10m 50s	remaining: 5m 37s
6460:	learn: 0.0016137	total: 10m 50s	remaining: 5m 56s
6267:	learn: 0.0020472	total: 10m 50s	remaining: 6m 27s
6580:	learn: 0.0015426	total: 10m 50s	remaining: 5m 37s
5982:	learn: 0.0015407	total: 10m 50s	remaining: 7m 16s
6458:	learn: 0.0015529	total: 10m 50s	remaining: 5m 56s
6268:	learn: 0.0020472	total: 10m 50s	remaining: 6m 27s
6461:	learn: 0.0016136	total: 10m 50s	remaining: 5m 56s
6581:	learn: 0.0015427	total: 10m 50s	remaining: 5m 37s
6459:	learn: 0.0015529	total: 10m 50s	remaining: 5m 56s
5983:	learn: 0.0015402	total: 10m 50s	remaining: 7m 16s
6269:	learn: 0.0020472	total: 10m 50s	remaining: 6m 26s
6462:	learn: 0.0016137	total: 10m 50s	remaining: 5m 55s
6582:	learn: 0.0015427	total: 10m 50s	remaining: 5m 37s
5984:	learn: 0.0015398	total: 10m 50s	remaining: 7m 16s
6460:	learn: 0.0015529	total: 10m 50s	remaining: 5m 56s
6270:	learn: 0.0020471	total: 10m 50s	remaining: 6m 26s
6583:	learn: 0.0015426	total: 10m 50s	remaining: 5m 37s
5985:	learn: 0.0015394	total: 10m 50s	remaining: 7m 16s
6463:	learn: 0.0016136	total: 10m 50s	remaining: 5m 55s
6461:	learn: 0.0015525	total: 10m 50s	remaining: 5m 56s
6584:	learn: 0.0015427	total: 10m 50s	remaining: 5m 37s
5986:	learn: 0.0015388	total: 10m 50s	remaining: 7m 16s
6271:	learn: 0.0020471	total: 10m 50s	remaining: 6m 26s
6464:	learn: 0.0016136	total: 10m 50s	remaining: 5m 55s
6585:	learn: 0.0015427	total: 10m 50s	remaining: 5m 37s
5987:	learn: 0.0015384	total: 10m 50s	remaining: 7m 16s
6462:	learn: 0.0015525	total: 10m 50s	remaining: 5m 56s
6272:	learn: 0.0020471	total: 10m 50s	remaining: 6m 26s
6586:	learn: 0.0015427	total: 10m 50s	remaining: 5m 37s
6465:	learn: 0.0016136	total: 10m 50s	remaining: 5m 55s
5988:	learn: 0.0015380	total: 10m 50s	remaining: 7m 15s
6273:	learn: 0.0020471	total: 10m 50s	remaining: 6m 26s
6463:	learn: 0.0015525	total: 10m 50s	remaining: 5m 55s
6587:	learn: 0.0015427	total: 10m 50s	remaining: 5m 37s
6466:	learn: 0.0016137	total: 10m 50s	remaining: 5m 55s
5989:	learn: 0.0015376	total: 10m 50s	remaining: 7m 15s
6274:	learn: 0.0020471	total: 10m 50s	remaining: 6m 26s
6464:	learn: 0.0015525	total: 10m 50s	remaining: 5m 55s
6588:	learn: 0.0015427	total: 10m 50s	remaining: 5m 36s
6467:	learn: 0.0016136	total: 10m 50s	remaining: 5m 55s
5990:	learn: 0.0015372	total: 10m 51s	remaining: 7m 15s
6275:	learn: 0.0020471	total: 10m 51s	remaining: 6m 26s
6468:	learn: 0.0016133	total: 10m 51s	remaining: 5m 55s
6589:	learn: 0.0015426	total: 10m 51s	remaining: 5m 36s
6465:	learn: 0.0015525	total: 10m 50s	remaining: 5m 55s
5991:	learn: 0.0015368	total: 10m 51s	remaining: 7m 15s
6276:	learn: 0.0020471	total: 10m 51s	remaining: 6m 26s
6590:	learn: 0.0015426	total: 10m 51s	remaining: 5m 36s
6469:	learn: 0.0016133	total: 10m 51s	remaining: 5m 55s
6466:	learn: 0.0015525	total: 10m 51s	remaining: 5m 55s
5992:	learn: 0.0015363	total: 10m 51s	remaining: 7m 15s
6470:	learn: 0.0016129	total: 10m 51s	remaining: 5m 55s
6591:	learn: 0.0015426	total: 10m 51s	remaining: 5m 36s
6467:	learn: 0.0015525	total: 10m 51s	remaining: 5m 55s
6277:	learn: 0.0020471	total: 10m 51s	remaining: 6m 26s
5993:	learn: 0.0015363	total: 10m 51s	remaining: 7m 15s
6468:	learn: 0.0015525	total: 10m 51s	remaining: 5m 55s
6592:	learn: 0.0015426	total: 10m 51s	remaining: 5m 36s
6471:	learn: 0.0016129	total: 10m 51s	remaining: 5m 55s
5994:	learn: 0.0015362	total: 10m 51s	remaining: 7m 15s
6278:	learn: 0.0020471	total: 10m 51s	remaining: 6m 26s
6469:	learn: 0.0015525	total: 10m 51s	remaining: 5m 55s
6472:	learn: 0.0016129	total: 10m 51s	remaining: 5m 54s
6593:	learn: 0.0015426	total: 10m 51s	remaining: 5m 36s
6470:	learn: 0.0015525	total: 10m 51s	remaining: 5m 55s
5995:	learn: 0.0015358	total: 10m 51s	remaining: 7m 15s
6279:	learn: 0.0020471	total: 10m 51s	remaining: 6m 25s
6473:	learn: 0.0016130	total: 10m 51s	remaining: 5m 54s
6594:	learn: 0.0015426	total: 10m 51s	remaining: 5m 36s
6471:	learn: 0.0015525	total: 10m 51s	remaining: 5m 55s
5996:	learn: 0.0015358	total: 10m 51s	remaining: 7m 14s
6280:	learn: 0.0020471	total: 10m 51s	remaining: 6m 25s
6474:	learn: 0.0016126	total: 10m 51s	remaining: 5m 54s
6595:	learn: 0.0015426	total: 10m 51s	remaining: 5m 36s
6472:	learn: 0.0015525	total: 10m 51s	remaining: 5m 54s
6281:	learn: 0.0020471	total: 10m 51s	remaining: 6m 25s
5997:	learn: 0.0015352	total: 10m 51s	remaining: 7m 14s
6475:	learn: 0.0016125	total: 10m 51s	remaining: 5m 54s
6596:	learn: 0.0015426	total: 10m 51s	remaining: 5m 36s
6473:	learn: 0.0015525	total: 10m 51s	remaining: 5m 54s
6282:	learn: 0.0020471	total: 10m 51s	remaining: 6m 25s
6597:	learn: 0.0015426	total: 10m 51s	remaining: 5m 36s
6476:	learn: 0.0016125	total: 10m 51s	remaining: 5m 54s
5998:	learn: 0.0015351	total: 10m 51s	remaining: 7m 14s
6474:	learn: 0.0015525	total: 10m 51s	remaining: 5m 54s
6598:	learn: 0.0015426	total: 10m 51s	remaining: 5m 35s
6283:	learn: 0.0020471	total: 10m 51s	remaining: 6m 25s
6477:	learn: 0.0016125	total: 10m 51s	remaining: 5m 54s
5999:	learn: 0.0015351	total: 10m 52s	remaining: 7m 14s
6475:	learn: 0.0015525	total: 10m 51s	remaining: 5m 54s
6599:	learn: 0.0015425	total: 10m 51s	remaining: 5m 35s
6284:	learn: 0.0020471	total: 10m 52s	remaining: 6m 25s
6478:	learn: 0.0016122	total: 10m 52s	remaining: 5m 54s
6476:	learn: 0.0015525	total: 10m 51s	remaining: 5m 54s
6285:	learn: 0.0020471	total: 10m 52s	remaining: 6m 25s
6000:	learn: 0.0015346	total: 10m 52s	remaining: 7m 14s
6600:	learn: 0.0015425	total: 10m 52s	remaining: 5m 35s
6477:	learn: 0.0015525	total: 10m 51s	remaining: 5m 54s
6286:	learn: 0.0020471	total: 10m 52s	remaining: 6m 25s
6479:	learn: 0.0016122	total: 10m 52s	remaining: 5m 54s
6601:	learn: 0.0015425	total: 10m 52s	remaining: 5m 35s
6001:	learn: 0.0015341	total: 10m 52s	remaining: 7m 14s
6287:	learn: 0.0020471	total: 10m 52s	remaining: 6m 25s
6480:	learn: 0.0016120	total: 10m 52s	remaining: 5m 54s
6478:	learn: 0.0015525	total: 10m 52s	remaining: 5m 54s
6602:	learn: 0.0015425	total: 10m 52s	remaining: 5m 35s
6002:	learn: 0.0015336	total: 10m 52s	remaining: 7m 14s
6481:	learn: 0.0016119	total: 10m 52s	remaining: 5m 54s
6479:	learn: 0.0015525	total: 10m 52s	remaining: 5m 54s
6288:	learn: 0.0020471	total: 10m 52s	remaining: 6m 24s
6603:	learn: 0.0015425	total: 10m 52s	remaining: 5m 35s
6480:	learn: 0.0015525	total: 10m 52s	remaining: 5m 54s
6003:	learn: 0.0015333	total: 10m 52s	remaining: 7m 14s
6482:	learn: 0.0016119	total: 10m 52s	remaining: 5m 53s
6289:	learn: 0.0020471	total: 10m 52s	remaining: 6m 24s
6604:	learn: 0.0015421	total: 10m 52s	remaining: 5m 35s
6481:	learn: 0.0015525	total: 10m 52s	remaining: 5m 54s
6483:	learn: 0.0016116	total: 10m 52s	remaining: 5m 53s
6290:	learn: 0.0020471	total: 10m 52s	remaining: 6m 24s
6004:	learn: 0.0015329	total: 10m 52s	remaining: 7m 14s
6605:	learn: 0.0015417	total: 10m 52s	remaining: 5m 35s
6482:	learn: 0.0015525	total: 10m 52s	remaining: 5m 53s
6291:	learn: 0.0020471	total: 10m 52s	remaining: 6m 24s
6484:	learn: 0.0016116	total: 10m 52s	remaining: 5m 53s
6005:	learn: 0.0015324	total: 10m 52s	remaining: 7m 14s
6483:	learn: 0.0015521	total: 10m 52s	remaining: 5m 53s
6606:	learn: 0.0015417	total: 10m 52s	remaining: 5m 35s
6292:	learn: 0.0020467	total: 10m 52s	remaining: 6m 24s
6485:	learn: 0.0016112	total: 10m 52s	remaining: 5m 53s
6484:	learn: 0.0015521	total: 10m 52s	remaining: 5m 53s
6006:	learn: 0.0015324	total: 10m 52s	remaining: 7m 13s
6607:	learn: 0.0015417	total: 10m 52s	remaining: 5m 35s
6293:	learn: 0.0020467	total: 10m 52s	remaining: 6m 24s
6485:	learn: 0.0015521	total: 10m 52s	remaining: 5m 53s
6486:	learn: 0.0016108	total: 10m 52s	remaining: 5m 53s
6608:	learn: 0.0015417	total: 10m 52s	remaining: 5m 34s
6007:	learn: 0.0015320	total: 10m 52s	remaining: 7m 13s
6294:	learn: 0.0020467	total: 10m 53s	remaining: 6m 24s
6609:	learn: 0.0015417	total: 10m 52s	remaining: 5m 34s
6486:	learn: 0.0015521	total: 10m 52s	remaining: 5m 53s
6487:	learn: 0.0016104	total: 10m 53s	remaining: 5m 53s
6008:	learn: 0.0015317	total: 10m 53s	remaining: 7m 13s
6610:	learn: 0.0015417	total: 10m 52s	remaining: 5m 34s
6295:	learn: 0.0020467	total: 10m 53s	remaining: 6m 24s
6487:	learn: 0.0015521	total: 10m 52s	remaining: 5m 53s
6488:	learn: 0.0016101	total: 10m 53s	remaining: 5m 53s
6611:	learn: 0.0015417	total: 10m 53s	remaining: 5m 34s
6009:	learn: 0.0015317	total: 10m 53s	remaining: 7m 13s
6488:	learn: 0.0015517	total: 10m 52s	remaining: 5m 53s
6296:	learn: 0.0020467	total: 10m 53s	remaining: 6m 24s
6489:	learn: 0.0016101	total: 10m 53s	remaining: 5m 53s
6612:	learn: 0.0015417	total: 10m 53s	remaining: 5m 34s
6010:	learn: 0.0015312	total: 10m 53s	remaining: 7m 13s
6489:	learn: 0.0015517	total: 10m 53s	remaining: 5m 53s
6297:	learn: 0.0020467	total: 10m 53s	remaining: 6m 24s
6490:	learn: 0.0016101	total: 10m 53s	remaining: 5m 53s
6613:	learn: 0.0015417	total: 10m 53s	remaining: 5m 34s
6490:	learn: 0.0015514	total: 10m 53s	remaining: 5m 53s
6011:	learn: 0.0015310	total: 10m 53s	remaining: 7m 13s
6298:	learn: 0.0020467	total: 10m 53s	remaining: 6m 23s
6491:	learn: 0.0016101	total: 10m 53s	remaining: 5m 53s
6614:	learn: 0.0015417	total: 10m 53s	remaining: 5m 34s
6491:	learn: 0.0015514	total: 10m 53s	remaining: 5m 53s
6012:	learn: 0.0015310	total: 10m 53s	remaining: 7m 13s
6299:	learn: 0.0020467	total: 10m 53s	remaining: 6m 23s
6492:	learn: 0.0016101	total: 10m 53s	remaining: 5m 52s
6013:	learn: 0.0015310	total: 10m 53s	remaining: 7m 13s
6615:	learn: 0.0015412	total: 10m 53s	remaining: 5m 34s
6492:	learn: 0.0015514	total: 10m 53s	remaining: 5m 52s
6300:	learn: 0.0020467	total: 10m 53s	remaining: 6m 23s
6014:	learn: 0.0015310	total: 10m 53s	remaining: 7m 13s
6616:	learn: 0.0015412	total: 10m 53s	remaining: 5m 34s
6493:	learn: 0.0016101	total: 10m 53s	remaining: 5m 52s
6493:	learn: 0.0015514	total: 10m 53s	remaining: 5m 52s
6301:	learn: 0.0020462	total: 10m 53s	remaining: 6m 23s
6617:	learn: 0.0015412	total: 10m 53s	remaining: 5m 34s
6015:	learn: 0.0015310	total: 10m 53s	remaining: 7m 12s
6494:	learn: 0.0015514	total: 10m 53s	remaining: 5m 52s
6494:	learn: 0.0016099	total: 10m 53s	remaining: 5m 52s
6302:	learn: 0.0020462	total: 10m 53s	remaining: 6m 23s
6618:	learn: 0.0015412	total: 10m 53s	remaining: 5m 33s
6016:	learn: 0.0015306	total: 10m 53s	remaining: 7m 12s
6495:	learn: 0.0016099	total: 10m 53s	remaining: 5m 52s
6495:	learn: 0.0015514	total: 10m 53s	remaining: 5m 52s
6303:	learn: 0.0020462	total: 10m 53s	remaining: 6m 23s
6017:	learn: 0.0015302	total: 10m 53s	remaining: 7m 12s
6619:	learn: 0.0015409	total: 10m 53s	remaining: 5m 33s
6496:	learn: 0.0016099	total: 10m 53s	remaining: 5m 52s
6496:	learn: 0.0015514	total: 10m 53s	remaining: 5m 52s
6304:	learn: 0.0020462	total: 10m 54s	remaining: 6m 23s
6018:	learn: 0.0015298	total: 10m 54s	remaining: 7m 12s
6620:	learn: 0.0015409	total: 10m 53s	remaining: 5m 33s
6497:	learn: 0.0015514	total: 10m 53s	remaining: 5m 52s
6497:	learn: 0.0016099	total: 10m 54s	remaining: 5m 52s
6621:	learn: 0.0015409	total: 10m 54s	remaining: 5m 33s
6305:	learn: 0.0020462	total: 10m 54s	remaining: 6m 23s
6019:	learn: 0.0015295	total: 10m 54s	remaining: 7m 12s
6498:	learn: 0.0015514	total: 10m 53s	remaining: 5m 52s
6498:	learn: 0.0016099	total: 10m 54s	remaining: 5m 52s
6622:	learn: 0.0015409	total: 10m 54s	remaining: 5m 33s
6306:	learn: 0.0020462	total: 10m 54s	remaining: 6m 23s
6020:	learn: 0.0015295	total: 10m 54s	remaining: 7m 12s
6499:	learn: 0.0016099	total: 10m 54s	remaining: 5m 52s
6499:	learn: 0.0015514	total: 10m 54s	remaining: 5m 52s
6307:	learn: 0.0020462	total: 10m 54s	remaining: 6m 22s
6623:	learn: 0.0015409	total: 10m 54s	remaining: 5m 33s
6021:	learn: 0.0015291	total: 10m 54s	remaining: 7m 12s
6500:	learn: 0.0016099	total: 10m 54s	remaining: 5m 52s
6500:	learn: 0.0015514	total: 10m 54s	remaining: 5m 52s
6624:	learn: 0.0015403	total: 10m 54s	remaining: 5m 33s
6501:	learn: 0.0016098	total: 10m 54s	remaining: 5m 52s
6308:	learn: 0.0020462	total: 10m 54s	remaining: 6m 22s
6022:	learn: 0.0015287	total: 10m 54s	remaining: 7m 12s
6501:	learn: 0.0015514	total: 10m 54s	remaining: 5m 51s
6625:	learn: 0.0015399	total: 10m 54s	remaining: 5m 33s
6502:	learn: 0.0016098	total: 10m 54s	remaining: 5m 51s
6309:	learn: 0.0020462	total: 10m 54s	remaining: 6m 22s
6502:	learn: 0.0015514	total: 10m 54s	remaining: 5m 51s
6023:	learn: 0.0015283	total: 10m 54s	remaining: 7m 12s
6503:	learn: 0.0016098	total: 10m 54s	remaining: 5m 51s
6626:	learn: 0.0015394	total: 10m 54s	remaining: 5m 33s
6503:	learn: 0.0015514	total: 10m 54s	remaining: 5m 51s
6310:	learn: 0.0020462	total: 10m 54s	remaining: 6m 22s
6504:	learn: 0.0016098	total: 10m 54s	remaining: 5m 51s
6024:	learn: 0.0015279	total: 10m 54s	remaining: 7m 11s
6627:	learn: 0.0015388	total: 10m 54s	remaining: 5m 33s
6504:	learn: 0.0015514	total: 10m 54s	remaining: 5m 51s
6311:	learn: 0.0020462	total: 10m 54s	remaining: 6m 22s
6505:	learn: 0.0016097	total: 10m 54s	remaining: 5m 51s
6025:	learn: 0.0015276	total: 10m 54s	remaining: 7m 11s
6505:	learn: 0.0015514	total: 10m 54s	remaining: 5m 51s
6628:	learn: 0.0015384	total: 10m 54s	remaining: 5m 32s
6506:	learn: 0.0016091	total: 10m 54s	remaining: 5m 51s
6312:	learn: 0.0020462	total: 10m 54s	remaining: 6m 22s
6629:	learn: 0.0015379	total: 10m 54s	remaining: 5m 32s
6506:	learn: 0.0015514	total: 10m 54s	remaining: 5m 51s
6507:	learn: 0.0016085	total: 10m 54s	remaining: 5m 51s
6026:	learn: 0.0015273	total: 10m 54s	remaining: 7m 11s
6313:	learn: 0.0020462	total: 10m 54s	remaining: 6m 22s
6630:	learn: 0.0015378	total: 10m 54s	remaining: 5m 32s
6508:	learn: 0.0016085	total: 10m 55s	remaining: 5m 51s
6507:	learn: 0.0015514	total: 10m 54s	remaining: 5m 51s
6314:	learn: 0.0020462	total: 10m 55s	remaining: 6m 22s
6027:	learn: 0.0015268	total: 10m 55s	remaining: 7m 11s
6509:	learn: 0.0016085	total: 10m 55s	remaining: 5m 51s
6631:	learn: 0.0015372	total: 10m 55s	remaining: 5m 32s
6508:	learn: 0.0015514	total: 10m 54s	remaining: 5m 51s
6028:	learn: 0.0015264	total: 10m 55s	remaining: 7m 11s
6509:	learn: 0.0015514	total: 10m 55s	remaining: 5m 51s
6315:	learn: 0.0020462	total: 10m 55s	remaining: 6m 22s
6632:	learn: 0.0015372	total: 10m 55s	remaining: 5m 32s
6510:	learn: 0.0016085	total: 10m 55s	remaining: 5m 51s
6029:	learn: 0.0015264	total: 10m 55s	remaining: 7m 11s
6316:	learn: 0.0020462	total: 10m 55s	remaining: 6m 22s
6510:	learn: 0.0015514	total: 10m 55s	remaining: 5m 51s
6633:	learn: 0.0015367	total: 10m 55s	remaining: 5m 32s
6511:	learn: 0.0016082	total: 10m 55s	remaining: 5m 51s
6030:	learn: 0.0015264	total: 10m 55s	remaining: 7m 11s
6317:	learn: 0.0020462	total: 10m 55s	remaining: 6m 21s
6511:	learn: 0.0015514	total: 10m 55s	remaining: 5m 50s
6634:	learn: 0.0015362	total: 10m 55s	remaining: 5m 32s
6512:	learn: 0.0016082	total: 10m 55s	remaining: 5m 50s
6031:	learn: 0.0015260	total: 10m 55s	remaining: 7m 11s
6318:	learn: 0.0020462	total: 10m 55s	remaining: 6m 21s
6635:	learn: 0.0015362	total: 10m 55s	remaining: 5m 32s
6512:	learn: 0.0015514	total: 10m 55s	remaining: 5m 50s
6513:	learn: 0.0016078	total: 10m 55s	remaining: 5m 50s
6032:	learn: 0.0015256	total: 10m 55s	remaining: 7m 11s
6636:	learn: 0.0015362	total: 10m 55s	remaining: 5m 32s
6319:	learn: 0.0020462	total: 10m 55s	remaining: 6m 21s
6514:	learn: 0.0016078	total: 10m 55s	remaining: 5m 50s
6513:	learn: 0.0015514	total: 10m 55s	remaining: 5m 50s
6637:	learn: 0.0015362	total: 10m 55s	remaining: 5m 32s
6033:	learn: 0.0015252	total: 10m 55s	remaining: 7m 10s
6515:	learn: 0.0016078	total: 10m 55s	remaining: 5m 50s
6514:	learn: 0.0015514	total: 10m 55s	remaining: 5m 50s
6320:	learn: 0.0020462	total: 10m 55s	remaining: 6m 21s
6638:	learn: 0.0015362	total: 10m 55s	remaining: 5m 31s
6034:	learn: 0.0015252	total: 10m 55s	remaining: 7m 10s
6516:	learn: 0.0016078	total: 10m 55s	remaining: 5m 50s
6515:	learn: 0.0015509	total: 10m 55s	remaining: 5m 50s
6639:	learn: 0.0015362	total: 10m 55s	remaining: 5m 31s
6321:	learn: 0.0020462	total: 10m 55s	remaining: 6m 21s

6516:	learn: 0.0015509	total: 10m 55s	remaining: 5m 50s
6035:	learn: 0.0015252	total: 10m 55s	remaining: 7m 10s
6517:	learn: 0.0016078	total: 10m 55s	remaining: 5m 50s
6640:	learn: 0.0015362	total: 10m 55s	remaining: 5m 31s
6322:	learn: 0.0020462	total: 10m 55s	remaining: 6m 21s
6518:	learn: 0.0016078	total: 10m 55s	remaining: 5m 50s
6517:	learn: 0.0015509	total: 10m 55s	remaining: 5m 50s
6036:	learn: 0.0015252	total: 10m 56s	remaining: 7m 10s
6641:	learn: 0.0015362	total: 10m 55s	remaining: 5m 31s
6323:	learn: 0.0020462	total: 10m 56s	remaining: 6m 21s
6519:	learn: 0.0016078	total: 10m 56s	remaining: 5m 50s
6518:	learn: 0.0015509	total: 10m 55s	remaining: 5m 50s
6642:	learn: 0.0015357	total: 10m 56s	remaining: 5m 31s
6520:	learn: 0.0016077	total: 10m 56s	remaining: 5m 50s
6324:	learn: 0.0020462	total: 10m 56s	remaining: 6m 21s
6037:	learn: 0.0015252	total: 10m 56s	remaining: 7m 10s
6519:	learn: 0.0015509	total: 10m 56s	remaining: 5m 50s
6521:	learn: 0.0016075	total: 10m 56s	remaining: 5m 49s
6643:	learn: 0.0015355	total: 10m 56s	remaining: 5m 31s
6325:	learn: 0.0020462	total: 10m 56s	remaining: 6m 21s
6520:	learn: 0.0015509	total: 10m 56s	remaining: 5m 50s
6038:	learn: 0.0015248	total: 10m 56s	remaining: 7m 10s
6644:	learn: 0.0015355	total: 10m 56s	remaining: 5m 31s
6326:	learn: 0.0020462	total: 10m 56s	remaining: 6m 21s
6039:	learn: 0.0015248	total: 10m 56s	remaining: 7m 10s
6522:	learn: 0.0016075	total: 10m 56s	remaining: 5m 49s
6521:	learn: 0.0015510	total: 10m 56s	remaining: 5m 49s
6645:	learn: 0.0015355	total: 10m 56s	remaining: 5m 31s
6040:	learn: 0.0015248	total: 10m 56s	remaining: 7m 10s
6327:	learn: 0.0020462	total: 10m 56s	remaining: 6m 20s
6523:	learn: 0.0016075	total: 10m 56s	remaining: 5m 49s
6522:	learn: 0.0015509	total: 10m 56s	remaining: 5m 49s
6041:	learn: 0.0015248	total: 10m 56s	remaining: 7m 10s
6646:	learn: 0.0015352	total: 10m 56s	remaining: 5m 31s
6328:	learn: 0.0020462	total: 10m 56s	remaining: 6m 20s
6524:	learn: 0.0016075	total: 10m 56s	remaining: 5m 49s
6523:	learn: 0.0015509	total: 10m 56s	remaining: 5m 49s
6525:	learn: 0.0016072	total: 10m 56s	remaining: 5m 49s
6647:	learn: 0.0015352	total: 10m 56s	remaining: 5m 31s
6329:	learn: 0.0020462	total: 10m 56s	remaining: 6m 20s
6042:	learn: 0.0015248	total: 10m 56s	remaining: 7m 10s
6524:	learn: 0.0015507	total: 10m 56s	remaining: 5m 49s
6526:	learn: 0.0016072	total: 10m 56s	remaining: 5m 49s
6330:	learn: 0.0020462	total: 10m 56s	remaining: 6m 20s
6648:	learn: 0.0015349	total: 10m 56s	remaining: 5m 30s
6525:	learn: 0.0015507	total: 10m 56s	remaining: 5m 49s
6043:	learn: 0.0015245	total: 10m 56s	remaining: 7m 9s
6527:	learn: 0.0016068	total: 10m 56s	remaining: 5m 49s
6649:	learn: 0.0015344	total: 10m 56s	remaining: 5m 30s
6331:	learn: 0.0020462	total: 10m 56s	remaining: 6m 20s
6526:	learn: 0.0015507	total: 10m 56s	remaining: 5m 49s
6044:	learn: 0.0015240	total: 10m 56s	remaining: 7m 9s
6528:	learn: 0.0016068	total: 10m 56s	remaining: 5m 49s
6650:	learn: 0.0015344	total: 10m 56s	remaining: 5m 30s
6527:	learn: 0.0015507	total: 10m 56s	remaining: 5m 49s
6332:	learn: 0.0020462	total: 10m 57s	remaining: 6m 20s
6045:	learn: 0.0015237	total: 10m 57s	remaining: 7m 9s
6651:	learn: 0.0015343	total: 10m 56s	remaining: 5m 30s
6529:	learn: 0.0016068	total: 10m 57s	remaining: 5m 49s
6528:	learn: 0.0015507	total: 10m 56s	remaining: 5m 49s
6046:	learn: 0.0015237	total: 10m 57s	remaining: 7m 9s
6333:	learn: 0.0020462	total: 10m 57s	remaining: 6m 20s
6652:	learn: 0.0015343	total: 10m 57s	remaining: 5m 30s
6530:	learn: 0.0016068	total: 10m 57s	remaining: 5m 49s
6529:	learn: 0.0015507	total: 10m 57s	remaining: 5m 49s
6047:	learn: 0.0015232	total: 10m 57s	remaining: 7m 9s
6334:	learn: 0.0020462	total: 10m 57s	remaining: 6m 20s
6653:	learn: 0.0015340	total: 10m 57s	remaining: 5m 30s
6531:	learn: 0.0016067	total: 10m 57s	remaining: 5m 48s
6335:	learn: 0.0020462	total: 10m 57s	remaining: 6m 20s
6530:	learn: 0.0015507	total: 10m 57s	remaining: 5m 49s
6048:	learn: 0.0015232	total: 10m 57s	remaining: 7m 9s
6654:	learn: 0.0015337	total: 10m 57s	remaining: 5m 30s
6532:	learn: 0.0016066	total: 10m 57s	remaining: 5m 48s
6336:	learn: 0.0020462	total: 10m 57s	remaining: 6m 19s
6531:	learn: 0.0015507	total: 10m 57s	remaining: 5m 48s
6655:	learn: 0.0015337	total: 10m 57s	remaining: 5m 30s
6049:	learn: 0.0015230	total: 10m 57s	remaining: 7m 9s
6533:	learn: 0.0016066	total: 10m 57s	remaining: 5m 48s
6337:	learn: 0.0020462	total: 10m 57s	remaining: 6m 19s
6532:	learn: 0.0015507	total: 10m 57s	remaining: 5m 48s
6656:	learn: 0.0015337	total: 10m 57s	remaining: 5m 30s
6534:	learn: 0.0016066	total: 10m 57s	remaining: 5m 48s
6050:	learn: 0.0015230	total: 10m 57s	remaining: 7m 9s
6533:	learn: 0.0015507	total: 10m 57s	remaining: 5m 48s
6657:	learn: 0.0015333	total: 10m 57s	remaining: 5m 30s
6338:	learn: 0.0020462	total: 10m 57s	remaining: 6m 19s
6535:	learn: 0.0016064	total: 10m 57s	remaining: 5m 48s
6051:	learn: 0.0015230	total: 10m 57s	remaining: 7m 9s
6658:	learn: 0.0015329	total: 10m 57s	remaining: 5m 29s
6339:	learn: 0.0020453	total: 10m 57s	remaining: 6m 19s
6534:	learn: 0.0015507	total: 10m 57s	remaining: 5m 48s
6536:	learn: 0.0016059	total: 10m 57s	remaining: 5m 48s
6052:	learn: 0.0015225	total: 10m 57s	remaining: 7m 8s
6659:	learn: 0.0015323	total: 10m 57s	remaining: 5m 29s
6340:	learn: 0.0020453	total: 10m 57s	remaining: 6m 19s
6537:	learn: 0.0016058	total: 10m 57s	remaining: 5m 48s
6535:	learn: 0.0015507	total: 10m 57s	remaining: 5m 48s
6053:	learn: 0.0015225	total: 10m 57s	remaining: 7m 8s
6660:	learn: 0.0015317	total: 10m 57s	remaining: 5m 29s
6536:	learn: 0.0015507	total: 10m 57s	remaining: 5m 48s
6341:	learn: 0.0020453	total: 10m 57s	remaining: 6m 19s
6538:	learn: 0.0016052	total: 10m 57s	remaining: 5m 48s
6661:	learn: 0.0015316	total: 10m 57s	remaining: 5m 29s
6342:	learn: 0.0020453	total: 10m 57s	remaining: 6m 19s
6537:	learn: 0.0015505	total: 10m 57s	remaining: 5m 48s
6054:	learn: 0.0015225	total: 10m 58s	remaining: 7m 8s
6539:	learn: 0.0016052	total: 10m 58s	remaining: 5m 48s
6343:	learn: 0.0020453	total: 10m 58s	remaining: 6m 19s
6538:	learn: 0.0015505	total: 10m 57s	remaining: 5m 48s
6662:	learn: 0.0015316	total: 10m 58s	remaining: 5m 29s
6055:	learn: 0.0015222	total: 10m 58s	remaining: 7m 8s
6344:	learn: 0.0020453	total: 10m 58s	remaining: 6m 19s
6539:	learn: 0.0015505	total: 10m 57s	remaining: 5m 48s
6540:	learn: 0.0016048	total: 10m 58s	remaining: 5m 48s
6663:	learn: 0.0015312	total: 10m 58s	remaining: 5m 29s
6056:	learn: 0.0015222	total: 10m 58s	remaining: 7m 8s
6540:	learn: 0.0015505	total: 10m 58s	remaining: 5m 47s
6541:	learn: 0.0016045	total: 10m 58s	remaining: 5m 47s
6345:	learn: 0.0020453	total: 10m 58s	remaining: 6m 19s
6664:	learn: 0.0015308	total: 10m 58s	remaining: 5m 29s
6057:	learn: 0.0015216	total: 10m 58s	remaining: 7m 8s
6541:	learn: 0.0015505	total: 10m 58s	remaining: 5m 47s
6346:	learn: 0.0020453	total: 10m 58s	remaining: 6m 18s
6542:	learn: 0.0016040	total: 10m 58s	remaining: 5m 47s
6665:	learn: 0.0015303	total: 10m 58s	remaining: 5m 29s
6058:	learn: 0.0015212	total: 10m 58s	remaining: 7m 8s
6542:	learn: 0.0015505	total: 10m 58s	remaining: 5m 47s
6543:	learn: 0.0016035	total: 10m 58s	remaining: 5m 47s
6666:	learn: 0.0015302	total: 10m 58s	remaining: 5m 29s
6347:	learn: 0.0020453	total: 10m 58s	remaining: 6m 18s
6543:	learn: 0.0015505	total: 10m 58s	remaining: 5m 47s
6059:	learn: 0.0015212	total: 10m 58s	remaining: 7m 8s
6667:	learn: 0.0015297	total: 10m 58s	remaining: 5m 29s
6544:	learn: 0.0016035	total: 10m 58s	remaining: 5m 47s
6348:	learn: 0.0020453	total: 10m 58s	remaining: 6m 18s
6544:	learn: 0.0015504	total: 10m 58s	remaining: 5m 47s
6668:	learn: 0.0015298	total: 10m 58s	remaining: 5m 28s
6545:	learn: 0.0016031	total: 10m 58s	remaining: 5m 47s
6060:	learn: 0.0015212	total: 10m 58s	remaining: 7m 8s
6349:	learn: 0.0020453	total: 10m 58s	remaining: 6m 18s
6545:	learn: 0.0015504	total: 10m 58s	remaining: 5m 47s
6669:	learn: 0.0015297	total: 10m 58s	remaining: 5m 28s
6546:	learn: 0.0016031	total: 10m 58s	remaining: 5m 47s
6061:	learn: 0.0015208	total: 10m 58s	remaining: 7m 7s
6350:	learn: 0.0020453	total: 10m 58s	remaining: 6m 18s
6546:	learn: 0.0015504	total: 10m 58s	remaining: 5m 47s
6670:	learn: 0.0015297	total: 10m 58s	remaining: 5m 28s
6547:	learn: 0.0016031	total: 10m 58s	remaining: 5m 47s
6671:	learn: 0.0015297	total: 10m 58s	remaining: 5m 28s
6547:	learn: 0.0015504	total: 10m 58s	remaining: 5m 47s
6351:	learn: 0.0020453	total: 10m 58s	remaining: 6m 18s
6548:	learn: 0.0016031	total: 10m 58s	remaining: 5m 47s
6062:	learn: 0.0015204	total: 10m 58s	remaining: 7m 7s
6672:	learn: 0.0015297	total: 10m 58s	remaining: 5m 28s
6548:	learn: 0.0015504	total: 10m 58s	remaining: 5m 47s
6352:	learn: 0.0020453	total: 10m 59s	remaining: 6m 18s
6063:	learn: 0.0015200	total: 10m 59s	remaining: 7m 7s
6549:	learn: 0.0016031	total: 10m 59s	remaining: 5m 47s
6673:	learn: 0.0015297	total: 10m 59s	remaining: 5m 28s
6549:	learn: 0.0015504	total: 10m 58s	remaining: 5m 47s
6353:	learn: 0.0020453	total: 10m 59s	remaining: 6m 18s
6064:	learn: 0.0015200	total: 10m 59s	remaining: 7m 7s
6550:	learn: 0.0016031	total: 10m 59s	remaining: 5m 47s
6550:	learn: 0.0015504	total: 10m 59s	remaining: 5m 46s
6674:	learn: 0.0015296	total: 10m 59s	remaining: 5m 28s
6551:	learn: 0.0016031	total: 10m 59s	remaining: 5m 46s
6065:	learn: 0.0015200	total: 10m 59s	remaining: 7m 7s
6354:	learn: 0.0020453	total: 10m 59s	remaining: 6m 18s
6551:	learn: 0.0015504	total: 10m 59s	remaining: 5m 46s
6552:	learn: 0.0016030	total: 10m 59s	remaining: 5m 46s
6675:	learn: 0.0015293	total: 10m 59s	remaining: 5m 28s
6355:	learn: 0.0020453	total: 10m 59s	remaining: 6m 18s
6066:	learn: 0.0015197	total: 10m 59s	remaining: 7m 7s
6553:	learn: 0.0016027	total: 10m 59s	remaining: 5m 46s
6552:	learn: 0.0015504	total: 10m 59s	remaining: 5m 46s
6356:	learn: 0.0020453	total: 10m 59s	remaining: 6m 17s
6676:	learn: 0.0015290	total: 10m 59s	remaining: 5m 28s
6067:	learn: 0.0015192	total: 10m 59s	remaining: 7m 7s
6554:	learn: 0.0016026	total: 10m 59s	remaining: 5m 46s
6553:	learn: 0.0015504	total: 10m 59s	remaining: 5m 46s
6357:	learn: 0.0020453	total: 10m 59s	remaining: 6m 17s
6677:	learn: 0.0015286	total: 10m 59s	remaining: 5m 28s
6068:	learn: 0.0015188	total: 10m 59s	remaining: 7m 7s
6555:	learn: 0.0016026	total: 10m 59s	remaining: 5m 46s
6358:	learn: 0.0020453	total: 10m 59s	remaining: 6m 17s
6554:	learn: 0.0015504	total: 10m 59s	remaining: 5m 46s
6359:	learn: 0.0020453	total: 10m 59s	remaining: 6m 17s
6678:	learn: 0.0015282	total: 10m 59s	remaining: 5m 27s
6069:	learn: 0.0015182	total: 10m 59s	remaining: 7m 7s
6556:	learn: 0.0016023	total: 10m 59s	remaining: 5m 46s
6360:	learn: 0.0020453	total: 10m 59s	remaining: 6m 17s
6555:	learn: 0.0015504	total: 10m 59s	remaining: 5m 46s
6679:	learn: 0.0015278	total: 10m 59s	remaining: 5m 27s
6557:	learn: 0.0016023	total: 10m 59s	remaining: 5m 46s
6556:	learn: 0.0015504	total: 10m 59s	remaining: 5m 46s
6070:	learn: 0.0015181	total: 10m 59s	remaining: 7m 7s
6361:	learn: 0.0020453	total: 10m 59s	remaining: 6m 17s
6558:	learn: 0.0016023	total: 10m 59s	remaining: 5m 46s
6680:	learn: 0.0015278	total: 10m 59s	remaining: 5m 27s
6071:	learn: 0.0015181	total: 10m 59s	remaining: 7m 6s
6557:	learn: 0.0015504	total: 10m 59s	remaining: 5m 46s
6559:	learn: 0.0016023	total: 10m 59s	remaining: 5m 46s
6681:	learn: 0.0015278	total: 10m 59s	remaining: 5m 27s
6362:	learn: 0.0020453	total: 10m 59s	remaining: 6m 17s
6558:	learn: 0.0015504	total: 10m 59s	remaining: 5m 46s
6072:	learn: 0.0015178	total: 11m	remaining: 7m 6s
6682:	learn: 0.0015278	total: 10m 59s	remaining: 5m 27s
6560:	learn: 0.0016020	total: 11m	remaining: 5m 45s
6363:	learn: 0.0020452	total: 11m	remaining: 6m 17s
6364:	learn: 0.0020453	total: 11m	remaining: 6m 17s
6561:	learn: 0.0016019	total: 11m	remaining: 5m 45s
6559:	learn: 0.0015502	total: 10m 59s	remaining: 5m 46s
6683:	learn: 0.0015278	total: 11m	remaining: 5m 27s
6073:	learn: 0.0015175	total: 11m	remaining: 7m 6s
6365:	learn: 0.0020453	total: 11m	remaining: 6m 16s
6562:	learn: 0.0016019	total: 11m	remaining: 5m 45s
6684:	learn: 0.0015277	total: 11m	remaining: 5m 27s
6560:	learn: 0.0015502	total: 11m	remaining: 5m 45s
6074:	learn: 0.0015171	total: 11m	remaining: 7m 6s
6366:	learn: 0.0020452	total: 11m	remaining: 6m 16s
6563:	learn: 0.0016019	total: 11m	remaining: 5m 45s
6685:	learn: 0.0015278	total: 11m	remaining: 5m 27s
6561:	learn: 0.0015502	total: 11m	remaining: 5m 45s
6367:	learn: 0.0020453	total: 11m	remaining: 6m 16s
6564:	learn: 0.0016019	total: 11m	remaining: 5m 45s
6075:	learn: 0.0015166	total: 11m	remaining: 7m 6s
6562:	learn: 0.0015502	total: 11m	remaining: 5m 45s
6686:	learn: 0.0015278	total: 11m	remaining: 5m 27s
6565:	learn: 0.0016020	total: 11m	remaining: 5m 45s
6076:	learn: 0.0015166	total: 11m	remaining: 7m 6s
6368:	learn: 0.0020453	total: 11m	remaining: 6m 16s
6563:	learn: 0.0015502	total: 11m	remaining: 5m 45s
6687:	learn: 0.0015278	total: 11m	remaining: 5m 27s
6566:	learn: 0.0016019	total: 11m	remaining: 5m 45s
6369:	learn: 0.0020453	total: 11m	remaining: 6m 16s
6077:	learn: 0.0015165	total: 11m	remaining: 7m 6s
6564:	learn: 0.0015502	total: 11m	remaining: 5m 45s
6688:	learn: 0.0015278	total: 11m	remaining: 5m 26s
6567:	learn: 0.0016019	total: 11m	remaining: 5m 45s
6370:	learn: 0.0020452	total: 11m	remaining: 6m 16s
6078:	learn: 0.0015164	total: 11m	remaining: 7m 6s
6689:	learn: 0.0015278	total: 11m	remaining: 5m 26s
6565:	learn: 0.0015502	total: 11m	remaining: 5m 45s
6079:	learn: 0.0015165	total: 11m	remaining: 7m 6s
6371:	learn: 0.0020448	total: 11m	remaining: 6m 16s
6568:	learn: 0.0016020	total: 11m	remaining: 5m 45s
6566:	learn: 0.0015502	total: 11m	remaining: 5m 45s
6690:	learn: 0.0015278	total: 11m	remaining: 5m 26s
6569:	learn: 0.0016019	total: 11m	remaining: 5m 45s
6567:	learn: 0.0015502	total: 11m	remaining: 5m 45s
6080:	learn: 0.0015161	total: 11m	remaining: 7m 5s
6691:	learn: 0.0015278	total: 11m	remaining: 5m 26s
6372:	learn: 0.0020448	total: 11m	remaining: 6m 16s
6570:	learn: 0.0016020	total: 11m 1s	remaining: 5m 44s
6692:	learn: 0.0015278	total: 11m	remaining: 5m 26s
6568:	learn: 0.0015501	total: 11m	remaining: 5m 45s
6373:	learn: 0.0020447	total: 11m 1s	remaining: 6m 16s
6081:	learn: 0.0015156	total: 11m 1s	remaining: 7m 5s
6693:	learn: 0.0015278	total: 11m 1s	remaining: 5m 26s
6571:	learn: 0.0016019	total: 11m 1s	remaining: 5m 44s
6569:	learn: 0.0015501	total: 11m	remaining: 5m 45s
6374:	learn: 0.0020447	total: 11m 1s	remaining: 6m 15s
6082:	learn: 0.0015156	total: 11m 1s	remaining: 7m 5s
6694:	learn: 0.0015278	total: 11m 1s	remaining: 5m 26s
6572:	learn: 0.0016019	total: 11m 1s	remaining: 5m 44s
6570:	learn: 0.0015501	total: 11m 1s	remaining: 5m 44s
6375:	learn: 0.0020447	total: 11m 1s	remaining: 6m 15s
6573:	learn: 0.0016019	total: 11m 1s	remaining: 5m 44s
6083:	learn: 0.0015156	total: 11m 1s	remaining: 7m 5s
6695:	learn: 0.0015278	total: 11m 1s	remaining: 5m 26s
6571:	learn: 0.0015501	total: 11m 1s	remaining: 5m 44s
6574:	learn: 0.0016019	total: 11m 1s	remaining: 5m 44s
6084:	learn: 0.0015152	total: 11m 1s	remaining: 7m 5s
6376:	learn: 0.0020447	total: 11m 1s	remaining: 6m 15s
6572:	learn: 0.0015501	total: 11m 1s	remaining: 5m 44s
6696:	learn: 0.0015277	total: 11m 1s	remaining: 5m 26s
6377:	learn: 0.0020447	total: 11m 1s	remaining: 6m 15s
6085:	learn: 0.0015152	total: 11m 1s	remaining: 7m 5s
6575:	learn: 0.0016019	total: 11m 1s	remaining: 5m 44s
6573:	learn: 0.0015501	total: 11m 1s	remaining: 5m 44s
6697:	learn: 0.0015277	total: 11m 1s	remaining: 5m 26s
6574:	learn: 0.0015501	total: 11m 1s	remaining: 5m 44s
6378:	learn: 0.0020447	total: 11m 1s	remaining: 6m 15s
6576:	learn: 0.0016019	total: 11m 1s	remaining: 5m 44s
6086:	learn: 0.0015152	total: 11m 1s	remaining: 7m 5s
6698:	learn: 0.0015277	total: 11m 1s	remaining: 5m 25s
6379:	learn: 0.0020447	total: 11m 1s	remaining: 6m 15s
6087:	learn: 0.0015148	total: 11m 1s	remaining: 7m 5s
6575:	learn: 0.0015501	total: 11m 1s	remaining: 5m 44s
6577:	learn: 0.0016019	total: 11m 1s	remaining: 5m 44s
6699:	learn: 0.0015277	total: 11m 1s	remaining: 5m 25s
6380:	learn: 0.0020447	total: 11m 1s	remaining: 6m 15s
6576:	learn: 0.0015501	total: 11m 1s	remaining: 5m 44s
6088:	learn: 0.0015144	total: 11m 1s	remaining: 7m 5s
6700:	learn: 0.0015274	total: 11m 1s	remaining: 5m 25s

6578:	learn: 0.0016019	total: 11m 1s	remaining: 5m 44s
6381:	learn: 0.0020447	total: 11m 1s	remaining: 6m 15s
6577:	learn: 0.0015501	total: 11m 1s	remaining: 5m 44s
6089:	learn: 0.0015140	total: 11m 1s	remaining: 7m 4s
6701:	learn: 0.0015274	total: 11m 1s	remaining: 5m 25s
6579:	learn: 0.0016019	total: 11m 1s	remaining: 5m 44s
6382:	learn: 0.0020447	total: 11m 1s	remaining: 6m 15s
6578:	learn: 0.0015501	total: 11m 1s	remaining: 5m 44s
6090:	learn: 0.0015140	total: 11m 2s	remaining: 7m 4s
6702:	learn: 0.0015274	total: 11m 1s	remaining: 5m 25s
6580:	learn: 0.0016019	total: 11m 2s	remaining: 5m 43s
6579:	learn: 0.0015501	total: 11m 1s	remaining: 5m 44s
6091:	learn: 0.0015135	total: 11m 2s	remaining: 7m 4s
6703:	learn: 0.0015274	total: 11m 2s	remaining: 5m 25s
6383:	learn: 0.0020447	total: 11m 2s	remaining: 6m 15s
6580:	learn: 0.0015501	total: 11m 1s	remaining: 5m 43s
6581:	learn: 0.0016019	total: 11m 2s	remaining: 5m 43s
6704:	learn: 0.0015274	total: 11m 2s	remaining: 5m 25s
6092:	learn: 0.0015131	total: 11m 2s	remaining: 7m 4s
6384:	learn: 0.0020447	total: 11m 2s	remaining: 6m 14s
6581:	learn: 0.0015501	total: 11m 2s	remaining: 5m 43s
6582:	learn: 0.0016019	total: 11m 2s	remaining: 5m 43s
6705:	learn: 0.0015274	total: 11m 2s	remaining: 5m 25s
6385:	learn: 0.0020447	total: 11m 2s	remaining: 6m 14s
6093:	learn: 0.0015127	total: 11m 2s	remaining: 7m 4s
6582:	learn: 0.0015500	total: 11m 2s	remaining: 5m 43s
6583:	learn: 0.0016019	total: 11m 2s	remaining: 5m 43s
6386:	learn: 0.0020447	total: 11m 2s	remaining: 6m 14s
6706:	learn: 0.0015274	total: 11m 2s	remaining: 5m 25s
6583:	learn: 0.0015500	total: 11m 2s	remaining: 5m 43s
6094:	learn: 0.0015123	total: 11m 2s	remaining: 7m 4s
6584:	learn: 0.0016019	total: 11m 2s	remaining: 5m 43s
6707:	learn: 0.0015274	total: 11m 2s	remaining: 5m 25s
6387:	learn: 0.0020447	total: 11m 2s	remaining: 6m 14s
6584:	learn: 0.0015500	total: 11m 2s	remaining: 5m 43s
6095:	learn: 0.0015120	total: 11m 2s	remaining: 7m 4s
6585:	learn: 0.0016019	total: 11m 2s	remaining: 5m 43s
6708:	learn: 0.0015274	total: 11m 2s	remaining: 5m 24s
6585:	learn: 0.0015500	total: 11m 2s	remaining: 5m 43s
6388:	learn: 0.0020447	total: 11m 2s	remaining: 6m 14s
6096:	learn: 0.0015116	total: 11m 2s	remaining: 7m 4s
6586:	learn: 0.0016020	total: 11m 2s	remaining: 5m 43s
6709:	learn: 0.0015274	total: 11m 2s	remaining: 5m 24s
6586:	learn: 0.0015500	total: 11m 2s	remaining: 5m 43s
6389:	learn: 0.0020447	total: 11m 2s	remaining: 6m 14s
6097:	learn: 0.0015116	total: 11m 2s	remaining: 7m 4s
6587:	learn: 0.0016019	total: 11m 2s	remaining: 5m 43s
6710:	learn: 0.0015274	total: 11m 2s	remaining: 5m 24s
6587:	learn: 0.0015500	total: 11m 2s	remaining: 5m 43s
6390:	learn: 0.0020447	total: 11m 2s	remaining: 6m 14s
6588:	learn: 0.0016019	total: 11m 2s	remaining: 5m 43s
6098:	learn: 0.0015112	total: 11m 2s	remaining: 7m 4s
6588:	learn: 0.0015500	total: 11m 2s	remaining: 5m 43s
6711:	learn: 0.0015274	total: 11m 2s	remaining: 5m 24s
6391:	learn: 0.0020447	total: 11m 2s	remaining: 6m 14s
6589:	learn: 0.0016019	total: 11m 2s	remaining: 5m 43s
6589:	learn: 0.0015500	total: 11m 2s	remaining: 5m 42s
6099:	learn: 0.0015108	total: 11m 3s	remaining: 7m 3s
6712:	learn: 0.0015274	total: 11m 2s	remaining: 5m 24s
6392:	learn: 0.0020447	total: 11m 3s	remaining: 6m 14s
6590:	learn: 0.0015499	total: 11m 2s	remaining: 5m 42s
6590:	learn: 0.0016019	total: 11m 3s	remaining: 5m 42s
6393:	learn: 0.0020447	total: 11m 3s	remaining: 6m 13s
6713:	learn: 0.0015274	total: 11m 3s	remaining: 5m 24s
6100:	learn: 0.0015103	total: 11m 3s	remaining: 7m 3s
6591:	learn: 0.0015499	total: 11m 2s	remaining: 5m 42s
6591:	learn: 0.0016019	total: 11m 3s	remaining: 5m 42s
6394:	learn: 0.0020447	total: 11m 3s	remaining: 6m 13s
6714:	learn: 0.0015274	total: 11m 3s	remaining: 5m 24s
6101:	learn: 0.0015099	total: 11m 3s	remaining: 7m 3s
6592:	learn: 0.0015499	total: 11m 3s	remaining: 5m 42s
6592:	learn: 0.0016019	total: 11m 3s	remaining: 5m 42s
6395:	learn: 0.0020447	total: 11m 3s	remaining: 6m 13s
6715:	learn: 0.0015274	total: 11m 3s	remaining: 5m 24s
6593:	learn: 0.0016019	total: 11m 3s	remaining: 5m 42s
6593:	learn: 0.0015499	total: 11m 3s	remaining: 5m 42s
6102:	learn: 0.0015095	total: 11m 3s	remaining: 7m 3s
6396:	learn: 0.0020447	total: 11m 3s	remaining: 6m 13s
6716:	learn: 0.0015274	total: 11m 3s	remaining: 5m 24s
6397:	learn: 0.0020441	total: 11m 3s	remaining: 6m 13s
6103:	learn: 0.0015090	total: 11m 3s	remaining: 7m 3s
6594:	learn: 0.0015499	total: 11m 3s	remaining: 5m 42s
6594:	learn: 0.0016019	total: 11m 3s	remaining: 5m 42s
6717:	learn: 0.0015269	total: 11m 3s	remaining: 5m 24s
6398:	learn: 0.0020441	total: 11m 3s	remaining: 6m 13s
6595:	learn: 0.0015499	total: 11m 3s	remaining: 5m 42s
6104:	learn: 0.0015085	total: 11m 3s	remaining: 7m 3s
6595:	learn: 0.0016019	total: 11m 3s	remaining: 5m 42s
6718:	learn: 0.0015265	total: 11m 3s	remaining: 5m 24s
6596:	learn: 0.0015499	total: 11m 3s	remaining: 5m 42s
6399:	learn: 0.0020441	total: 11m 3s	remaining: 6m 13s
6105:	learn: 0.0015081	total: 11m 3s	remaining: 7m 3s
6596:	learn: 0.0016019	total: 11m 3s	remaining: 5m 42s
6719:	learn: 0.0015265	total: 11m 3s	remaining: 5m 23s
6597:	learn: 0.0015499	total: 11m 3s	remaining: 5m 42s
6400:	learn: 0.0020441	total: 11m 3s	remaining: 6m 13s
6597:	learn: 0.0016019	total: 11m 3s	remaining: 5m 42s
6720:	learn: 0.0015265	total: 11m 3s	remaining: 5m 23s
6106:	learn: 0.0015081	total: 11m 3s	remaining: 7m 3s
6401:	learn: 0.0020441	total: 11m 3s	remaining: 6m 13s
6598:	learn: 0.0015499	total: 11m 3s	remaining: 5m 42s
6721:	learn: 0.0015265	total: 11m 3s	remaining: 5m 23s
6598:	learn: 0.0016019	total: 11m 3s	remaining: 5m 42s
6107:	learn: 0.0015081	total: 11m 3s	remaining: 7m 3s
6402:	learn: 0.0020440	total: 11m 3s	remaining: 6m 13s
6599:	learn: 0.0016016	total: 11m 3s	remaining: 5m 42s
6722:	learn: 0.0015265	total: 11m 3s	remaining: 5m 23s
6599:	learn: 0.0015499	total: 11m 3s	remaining: 5m 41s
6108:	learn: 0.0015078	total: 11m 4s	remaining: 7m 2s
6600:	learn: 0.0016013	total: 11m 4s	remaining: 5m 41s
6403:	learn: 0.0020441	total: 11m 4s	remaining: 6m 12s
6600:	learn: 0.0015498	total: 11m 3s	remaining: 5m 41s
6723:	learn: 0.0015262	total: 11m 4s	remaining: 5m 23s
6109:	learn: 0.0015078	total: 11m 4s	remaining: 7m 2s
6404:	learn: 0.0020440	total: 11m 4s	remaining: 6m 12s
6601:	learn: 0.0016013	total: 11m 4s	remaining: 5m 41s
6724:	learn: 0.0015262	total: 11m 4s	remaining: 5m 23s
6601:	learn: 0.0015498	total: 11m 4s	remaining: 5m 41s
6110:	learn: 0.0015076	total: 11m 4s	remaining: 7m 2s
6405:	learn: 0.0020440	total: 11m 4s	remaining: 6m 12s
6602:	learn: 0.0016013	total: 11m 4s	remaining: 5m 41s
6725:	learn: 0.0015262	total: 11m 4s	remaining: 5m 23s
6602:	learn: 0.0015498	total: 11m 4s	remaining: 5m 41s
6406:	learn: 0.0020440	total: 11m 4s	remaining: 6m 12s
6603:	learn: 0.0016010	total: 11m 4s	remaining: 5m 41s
6111:	learn: 0.0015076	total: 11m 4s	remaining: 7m 2s
6726:	learn: 0.0015262	total: 11m 4s	remaining: 5m 23s
6603:	learn: 0.0015493	total: 11m 4s	remaining: 5m 41s
6407:	learn: 0.0020440	total: 11m 4s	remaining: 6m 12s
6604:	learn: 0.0016004	total: 11m 4s	remaining: 5m 41s
6727:	learn: 0.0015262	total: 11m 4s	remaining: 5m 23s
6112:	learn: 0.0015072	total: 11m 4s	remaining: 7m 2s
6604:	learn: 0.0015493	total: 11m 4s	remaining: 5m 41s
6408:	learn: 0.0020440	total: 11m 4s	remaining: 6m 12s
6605:	learn: 0.0016004	total: 11m 4s	remaining: 5m 41s
6728:	learn: 0.0015255	total: 11m 4s	remaining: 5m 23s
6113:	learn: 0.0015068	total: 11m 4s	remaining: 7m 2s
6409:	learn: 0.0020440	total: 11m 4s	remaining: 6m 12s
6605:	learn: 0.0015489	total: 11m 4s	remaining: 5m 41s
6729:	learn: 0.0015255	total: 11m 4s	remaining: 5m 22s
6606:	learn: 0.0016004	total: 11m 4s	remaining: 5m 41s
6114:	learn: 0.0015063	total: 11m 4s	remaining: 7m 2s
6410:	learn: 0.0020440	total: 11m 4s	remaining: 6m 12s
6606:	learn: 0.0015489	total: 11m 4s	remaining: 5m 41s
6730:	learn: 0.0015255	total: 11m 4s	remaining: 5m 22s
6115:	learn: 0.0015059	total: 11m 4s	remaining: 7m 2s
6607:	learn: 0.0016003	total: 11m 4s	remaining: 5m 41s
6607:	learn: 0.0015489	total: 11m 4s	remaining: 5m 41s
6411:	learn: 0.0020441	total: 11m 4s	remaining: 6m 12s
6731:	learn: 0.0015250	total: 11m 4s	remaining: 5m 22s
6116:	learn: 0.0015056	total: 11m 4s	remaining: 7m 2s
6608:	learn: 0.0016004	total: 11m 4s	remaining: 5m 41s
6117:	learn: 0.0015056	total: 11m 4s	remaining: 7m 1s
6608:	learn: 0.0015489	total: 11m 4s	remaining: 5m 41s
6412:	learn: 0.0020441	total: 11m 4s	remaining: 6m 11s
6732:	learn: 0.0015250	total: 11m 4s	remaining: 5m 22s
6609:	learn: 0.0016003	total: 11m 4s	remaining: 5m 41s
6609:	learn: 0.0015489	total: 11m 4s	remaining: 5m 40s
6733:	learn: 0.0015250	total: 11m 4s	remaining: 5m 22s
6413:	learn: 0.0020441	total: 11m 5s	remaining: 6m 11s
6118:	learn: 0.0015056	total: 11m 5s	remaining: 7m 1s
6610:	learn: 0.0016003	total: 11m 5s	remaining: 5m 40s
6734:	learn: 0.0015250	total: 11m 5s	remaining: 5m 22s
6610:	learn: 0.0015489	total: 11m 4s	remaining: 5m 40s
6414:	learn: 0.0020440	total: 11m 5s	remaining: 6m 11s
6119:	learn: 0.0015056	total: 11m 5s	remaining: 7m 1s
6611:	learn: 0.0016003	total: 11m 5s	remaining: 5m 40s
6735:	learn: 0.0015250	total: 11m 5s	remaining: 5m 22s
6415:	learn: 0.0020441	total: 11m 5s	remaining: 6m 11s
6120:	learn: 0.0015051	total: 11m 5s	remaining: 7m 1s
6611:	learn: 0.0015489	total: 11m 5s	remaining: 5m 40s
6736:	learn: 0.0015250	total: 11m 5s	remaining: 5m 22s
6612:	learn: 0.0016003	total: 11m 5s	remaining: 5m 40s
6416:	learn: 0.0020440	total: 11m 5s	remaining: 6m 11s
6121:	learn: 0.0015047	total: 11m 5s	remaining: 7m 1s
6613:	learn: 0.0016003	total: 11m 5s	remaining: 5m 40s
6612:	learn: 0.0015489	total: 11m 5s	remaining: 5m 40s
6737:	learn: 0.0015250	total: 11m 5s	remaining: 5m 22s
6417:	learn: 0.0020440	total: 11m 5s	remaining: 6m 11s
6122:	learn: 0.0015043	total: 11m 5s	remaining: 7m 1s
6614:	learn: 0.0016004	total: 11m 5s	remaining: 5m 40s
6613:	learn: 0.0015489	total: 11m 5s	remaining: 5m 40s
6738:	learn: 0.0015250	total: 11m 5s	remaining: 5m 22s
6418:	learn: 0.0020440	total: 11m 5s	remaining: 6m 11s
6615:	learn: 0.0016003	total: 11m 5s	remaining: 5m 40s
6614:	learn: 0.0015489	total: 11m 5s	remaining: 5m 40s
6123:	learn: 0.0015040	total: 11m 5s	remaining: 7m 1s
6419:	learn: 0.0020440	total: 11m 5s	remaining: 6m 11s
6739:	learn: 0.0015250	total: 11m 5s	remaining: 5m 21s
6615:	learn: 0.0015488	total: 11m 5s	remaining: 5m 40s
6420:	learn: 0.0020440	total: 11m 5s	remaining: 6m 11s
6616:	learn: 0.0016003	total: 11m 5s	remaining: 5m 40s
6124:	learn: 0.0015035	total: 11m 5s	remaining: 7m 1s
6616:	learn: 0.0015488	total: 11m 5s	remaining: 5m 40s
6740:	learn: 0.0015250	total: 11m 5s	remaining: 5m 21s
6617:	learn: 0.0016003	total: 11m 5s	remaining: 5m 40s
6421:	learn: 0.0020440	total: 11m 5s	remaining: 6m 10s
6617:	learn: 0.0015488	total: 11m 5s	remaining: 5m 40s
6741:	learn: 0.0015250	total: 11m 5s	remaining: 5m 21s
6125:	learn: 0.0015031	total: 11m 5s	remaining: 7m 1s
6618:	learn: 0.0015488	total: 11m 5s	remaining: 5m 40s
6422:	learn: 0.0020440	total: 11m 5s	remaining: 6m 10s
6618:	learn: 0.0016003	total: 11m 5s	remaining: 5m 40s
6742:	learn: 0.0015250	total: 11m 5s	remaining: 5m 21s
6126:	learn: 0.0015027	total: 11m 5s	remaining: 7m
6619:	learn: 0.0015484	total: 11m 5s	remaining: 5m 39s
6619:	learn: 0.0016003	total: 11m 5s	remaining: 5m 40s
6423:	learn: 0.0020440	total: 11m 6s	remaining: 6m 10s
6743:	learn: 0.0015250	total: 11m 5s	remaining: 5m 21s
6620:	learn: 0.0015484	total: 11m 5s	remaining: 5m 39s
6127:	learn: 0.0015027	total: 11m 6s	remaining: 7m
6424:	learn: 0.0020432	total: 11m 6s	remaining: 6m 10s
6744:	learn: 0.0015250	total: 11m 6s	remaining: 5m 21s
6620:	learn: 0.0016003	total: 11m 6s	remaining: 5m 39s
6621:	learn: 0.0015484	total: 11m 5s	remaining: 5m 39s
6128:	learn: 0.0015027	total: 11m 6s	remaining: 7m
6745:	learn: 0.0015250	total: 11m 6s	remaining: 5m 21s
6425:	learn: 0.0020432	total: 11m 6s	remaining: 6m 10s
6621:	learn: 0.0016003	total: 11m 6s	remaining: 5m 39s
6622:	learn: 0.0015484	total: 11m 6s	remaining: 5m 39s
6129:	learn: 0.0015027	total: 11m 6s	remaining: 7m
6746:	learn: 0.0015250	total: 11m 6s	remaining: 5m 21s
6622:	learn: 0.0016001	total: 11m 6s	remaining: 5m 39s
6426:	learn: 0.0020432	total: 11m 6s	remaining: 6m 10s
6623:	learn: 0.0015484	total: 11m 6s	remaining: 5m 39s
6747:	learn: 0.0015245	total: 11m 6s	remaining: 5m 21s
6130:	learn: 0.0015027	total: 11m 6s	remaining: 7m
6427:	learn: 0.0020432	total: 11m 6s	remaining: 6m 10s
6623:	learn: 0.0016001	total: 11m 6s	remaining: 5m 39s
6624:	learn: 0.0015484	total: 11m 6s	remaining: 5m 39s
6748:	learn: 0.0015242	total: 11m 6s	remaining: 5m 20s
6131:	learn: 0.0015023	total: 11m 6s	remaining: 7m
6428:	learn: 0.0020432	total: 11m 6s	remaining: 6m 10s
6625:	learn: 0.0015484	total: 11m 6s	remaining: 5m 39s
6624:	learn: 0.0016001	total: 11m 6s	remaining: 5m 39s
6749:	learn: 0.0015240	total: 11m 6s	remaining: 5m 20s
6429:	learn: 0.0020432	total: 11m 6s	remaining: 6m 10s
6625:	learn: 0.0016001	total: 11m 6s	remaining: 5m 39s
6626:	learn: 0.0015484	total: 11m 6s	remaining: 5m 39s
6132:	learn: 0.0015023	total: 11m 6s	remaining: 7m
6750:	learn: 0.0015236	total: 11m 6s	remaining: 5m 20s
6430:	learn: 0.0020432	total: 11m 6s	remaining: 6m 10s
6626:	learn: 0.0016001	total: 11m 6s	remaining: 5m 39s
6751:	learn: 0.0015232	total: 11m 6s	remaining: 5m 20s
6627:	learn: 0.0015484	total: 11m 6s	remaining: 5m 39s
6133:	learn: 0.0015021	total: 11m 6s	remaining: 7m
6431:	learn: 0.0020432	total: 11m 6s	remaining: 6m 9s
6627:	learn: 0.0016001	total: 11m 6s	remaining: 5m 39s
6628:	learn: 0.0015484	total: 11m 6s	remaining: 5m 39s
6432:	learn: 0.0020432	total: 11m 6s	remaining: 6m 9s
6752:	learn: 0.0015232	total: 11m 6s	remaining: 5m 20s
6134:	learn: 0.0015017	total: 11m 6s	remaining: 7m
6628:	learn: 0.0016001	total: 11m 6s	remaining: 5m 39s
6629:	learn: 0.0015484	total: 11m 6s	remaining: 5m 38s
6433:	learn: 0.0020432	total: 11m 6s	remaining: 6m 9s
6135:	learn: 0.0015013	total: 11m 6s	remaining: 7m
6753:	learn: 0.0015232	total: 11m 6s	remaining: 5m 20s
6629:	learn: 0.0016001	total: 11m 6s	remaining: 5m 39s
6630:	learn: 0.0015484	total: 11m 6s	remaining: 5m 38s
6434:	learn: 0.0020432	total: 11m 7s	remaining: 6m 9s
6136:	learn: 0.0015010	total: 11m 7s	remaining: 6m 59s
6754:	learn: 0.0015232	total: 11m 7s	remaining: 5m 20s
6630:	learn: 0.0015998	total: 11m 7s	remaining: 5m 38s
6435:	learn: 0.0020432	total: 11m 7s	remaining: 6m 9s
6631:	learn: 0.0015484	total: 11m 6s	remaining: 5m 38s
6755:	learn: 0.0015232	total: 11m 7s	remaining: 5m 20s
6137:	learn: 0.0015010	total: 11m 7s	remaining: 6m 59s
6631:	learn: 0.0015994	total: 11m 7s	remaining: 5m 38s
6632:	learn: 0.0015484	total: 11m 7s	remaining: 5m 38s
6436:	learn: 0.0020432	total: 11m 7s	remaining: 6m 9s
6756:	learn: 0.0015232	total: 11m 7s	remaining: 5m 20s
6138:	learn: 0.0015006	total: 11m 7s	remaining: 6m 59s
6633:	learn: 0.0015484	total: 11m 7s	remaining: 5m 38s
6632:	learn: 0.0015991	total: 11m 7s	remaining: 5m 38s
6437:	learn: 0.0020432	total: 11m 7s	remaining: 6m 9s
6757:	learn: 0.0015232	total: 11m 7s	remaining: 5m 20s
6139:	learn: 0.0015002	total: 11m 7s	remaining: 6m 59s
6634:	learn: 0.0015484	total: 11m 7s	remaining: 5m 38s
6633:	learn: 0.0015991	total: 11m 7s	remaining: 5m 38s
6438:	learn: 0.0020432	total: 11m 7s	remaining: 6m 9s
6140:	learn: 0.0015002	total: 11m 7s	remaining: 6m 59s
6758:	learn: 0.0015232	total: 11m 7s	remaining: 5m 20s
6635:	learn: 0.0015484	total: 11m 7s	remaining: 5m 38s
6439:	learn: 0.0020432	total: 11m 7s	remaining: 6m 9s
6634:	learn: 0.0015991	total: 11m 7s	remaining: 5m 38s
6759:	learn: 0.0015232	total: 11m 7s	remaining: 5m 19s
6141:	learn: 0.0014999	total: 11m 7s	remaining: 6m 59s
6635:	learn: 0.0015991	total: 11m 7s	remaining: 5m 38s
6440:	learn: 0.0020432	total: 11m 7s	remaining: 6m 8s
6636:	learn: 0.0015484	total: 11m 7s	remaining: 5m 38s
6760:	learn: 0.0015232	total: 11m 7s	remaining: 5m 19s
6142:	learn: 0.0014999	total: 11m 7s	remaining: 6m 59s
6441:	learn: 0.0020432	total: 11m 7s	remaining: 6m 8s
6636:	learn: 0.0015988	total: 11m 7s	remaining: 5m 38s
6143:	learn: 0.0014995	total: 11m 7s	remaining: 6m 59s
6761:	learn: 0.0015232	total: 11m 7s	remaining: 5m 19s
6637:	learn: 0.0015484	total: 11m 7s	remaining: 5m 38s
6442:	learn: 0.0020432	total: 11m 7s	remaining: 6m 8s
6637:	learn: 0.0015988	total: 11m 7s	remaining: 5m 38s

6144:	learn: 0.0014991	total: 11m 7s	remaining: 6m 58s
6638:	learn: 0.0015484	total: 11m 7s	remaining: 5m 38s
6762:	learn: 0.0015232	total: 11m 7s	remaining: 5m 19s
6443:	learn: 0.0020432	total: 11m 7s	remaining: 6m 8s
6638:	learn: 0.0015983	total: 11m 7s	remaining: 5m 38s
6145:	learn: 0.0014991	total: 11m 8s	remaining: 6m 58s
6639:	learn: 0.0015484	total: 11m 7s	remaining: 5m 37s
6763:	learn: 0.0015232	total: 11m 7s	remaining: 5m 19s
6444:	learn: 0.0020432	total: 11m 8s	remaining: 6m 8s
6639:	learn: 0.0015977	total: 11m 8s	remaining: 5m 38s
6146:	learn: 0.0014991	total: 11m 8s	remaining: 6m 58s
6640:	learn: 0.0015484	total: 11m 7s	remaining: 5m 37s
6764:	learn: 0.0015232	total: 11m 8s	remaining: 5m 19s
6445:	learn: 0.0020432	total: 11m 8s	remaining: 6m 8s
6640:	learn: 0.0015975	total: 11m 8s	remaining: 5m 37s
6147:	learn: 0.0014987	total: 11m 8s	remaining: 6m 58s
6446:	learn: 0.0020433	total: 11m 8s	remaining: 6m 8s
6765:	learn: 0.0015232	total: 11m 8s	remaining: 5m 19s
6641:	learn: 0.0015484	total: 11m 8s	remaining: 5m 37s
6641:	learn: 0.0015975	total: 11m 8s	remaining: 5m 37s
6148:	learn: 0.0014987	total: 11m 8s	remaining: 6m 58s
6766:	learn: 0.0015232	total: 11m 8s	remaining: 5m 19s
6447:	learn: 0.0020433	total: 11m 8s	remaining: 6m 8s
6642:	learn: 0.0015484	total: 11m 8s	remaining: 5m 37s
6149:	learn: 0.0014987	total: 11m 8s	remaining: 6m 58s
6642:	learn: 0.0015975	total: 11m 8s	remaining: 5m 37s
6767:	learn: 0.0015232	total: 11m 8s	remaining: 5m 19s
6643:	learn: 0.0015484	total: 11m 8s	remaining: 5m 37s
6448:	learn: 0.0020433	total: 11m 8s	remaining: 6m 8s
6150:	learn: 0.0014987	total: 11m 8s	remaining: 6m 58s
6643:	learn: 0.0015975	total: 11m 8s	remaining: 5m 37s
6644:	learn: 0.0015481	total: 11m 8s	remaining: 5m 37s
6449:	learn: 0.0020433	total: 11m 8s	remaining: 6m 7s
6768:	learn: 0.0015232	total: 11m 8s	remaining: 5m 19s
6151:	learn: 0.0014983	total: 11m 8s	remaining: 6m 58s
6644:	learn: 0.0015975	total: 11m 8s	remaining: 5m 37s
6645:	learn: 0.0015480	total: 11m 8s	remaining: 5m 37s
6769:	learn: 0.0015232	total: 11m 8s	remaining: 5m 18s
6450:	learn: 0.0020432	total: 11m 8s	remaining: 6m 7s
6152:	learn: 0.0014979	total: 11m 8s	remaining: 6m 58s
6645:	learn: 0.0015975	total: 11m 8s	remaining: 5m 37s
6646:	learn: 0.0015480	total: 11m 8s	remaining: 5m 37s
6770:	learn: 0.0015232	total: 11m 8s	remaining: 5m 18s
6451:	learn: 0.0020432	total: 11m 8s	remaining: 6m 7s
6153:	learn: 0.0014978	total: 11m 8s	remaining: 6m 57s
6646:	learn: 0.0015975	total: 11m 8s	remaining: 5m 37s
6771:	learn: 0.0015232	total: 11m 8s	remaining: 5m 18s
6647:	learn: 0.0015480	total: 11m 8s	remaining: 5m 37s
6452:	learn: 0.0020432	total: 11m 8s	remaining: 6m 7s
6647:	learn: 0.0015975	total: 11m 8s	remaining: 5m 37s
6154:	learn: 0.0014975	total: 11m 8s	remaining: 6m 57s
6772:	learn: 0.0015232	total: 11m 8s	remaining: 5m 18s
6648:	learn: 0.0015480	total: 11m 8s	remaining: 5m 37s
6648:	learn: 0.0015975	total: 11m 8s	remaining: 5m 37s
6453:	learn: 0.0020432	total: 11m 8s	remaining: 6m 7s
6155:	learn: 0.0014975	total: 11m 9s	remaining: 6m 57s
6773:	learn: 0.0015232	total: 11m 8s	remaining: 5m 18s
6649:	learn: 0.0015480	total: 11m 8s	remaining: 5m 36s
6649:	learn: 0.0015975	total: 11m 9s	remaining: 5m 37s
6454:	learn: 0.0020432	total: 11m 9s	remaining: 6m 7s
6156:	learn: 0.0014971	total: 11m 9s	remaining: 6m 57s
6774:	learn: 0.0015229	total: 11m 9s	remaining: 5m 18s
6650:	learn: 0.0015480	total: 11m 8s	remaining: 5m 36s
6650:	learn: 0.0015975	total: 11m 9s	remaining: 5m 36s
6455:	learn: 0.0020432	total: 11m 9s	remaining: 6m 7s
6157:	learn: 0.0014967	total: 11m 9s	remaining: 6m 57s
6775:	learn: 0.0015229	total: 11m 9s	remaining: 5m 18s
6651:	learn: 0.0015975	total: 11m 9s	remaining: 5m 36s
6651:	learn: 0.0015480	total: 11m 9s	remaining: 5m 36s
6456:	learn: 0.0020432	total: 11m 9s	remaining: 6m 7s
6776:	learn: 0.0015229	total: 11m 9s	remaining: 5m 18s
6158:	learn: 0.0014964	total: 11m 9s	remaining: 6m 57s
6652:	learn: 0.0015975	total: 11m 9s	remaining: 5m 36s
6457:	learn: 0.0020432	total: 11m 9s	remaining: 6m 7s
6652:	learn: 0.0015477	total: 11m 9s	remaining: 5m 36s
6777:	learn: 0.0015229	total: 11m 9s	remaining: 5m 18s
6653:	learn: 0.0015473	total: 11m 9s	remaining: 5m 36s
6653:	learn: 0.0015975	total: 11m 9s	remaining: 5m 36s
6458:	learn: 0.0020432	total: 11m 9s	remaining: 6m 7s
6159:	learn: 0.0014961	total: 11m 9s	remaining: 6m 57s
6778:	learn: 0.0015229	total: 11m 9s	remaining: 5m 18s
6654:	learn: 0.0015472	total: 11m 9s	remaining: 5m 36s
6654:	learn: 0.0015969	total: 11m 9s	remaining: 5m 36s
6459:	learn: 0.0020432	total: 11m 9s	remaining: 6m 6s
6779:	learn: 0.0015229	total: 11m 9s	remaining: 5m 17s
6160:	learn: 0.0014957	total: 11m 9s	remaining: 6m 57s
6655:	learn: 0.0015472	total: 11m 9s	remaining: 5m 36s
6655:	learn: 0.0015969	total: 11m 9s	remaining: 5m 36s
6780:	learn: 0.0015229	total: 11m 9s	remaining: 5m 17s
6460:	learn: 0.0020432	total: 11m 9s	remaining: 6m 6s
6161:	learn: 0.0014954	total: 11m 9s	remaining: 6m 57s
6656:	learn: 0.0015472	total: 11m 9s	remaining: 5m 36s
6656:	learn: 0.0015969	total: 11m 9s	remaining: 5m 36s
6781:	learn: 0.0015229	total: 11m 9s	remaining: 5m 17s
6461:	learn: 0.0020432	total: 11m 9s	remaining: 6m 6s
6162:	learn: 0.0014949	total: 11m 9s	remaining: 6m 57s
6657:	learn: 0.0015472	total: 11m 9s	remaining: 5m 36s
6657:	learn: 0.0015965	total: 11m 9s	remaining: 5m 36s
6462:	learn: 0.0020432	total: 11m 9s	remaining: 6m 6s
6782:	learn: 0.0015229	total: 11m 9s	remaining: 5m 17s
6163:	learn: 0.0014949	total: 11m 9s	remaining: 6m 56s
6658:	learn: 0.0015469	total: 11m 9s	remaining: 5m 36s
6463:	learn: 0.0020432	total: 11m 9s	remaining: 6m 6s
6658:	learn: 0.0015965	total: 11m 9s	remaining: 5m 36s
6164:	learn: 0.0014949	total: 11m 9s	remaining: 6m 56s
6783:	learn: 0.0015229	total: 11m 9s	remaining: 5m 17s
6659:	learn: 0.0015469	total: 11m 9s	remaining: 5m 35s
6464:	learn: 0.0020432	total: 11m 10s	remaining: 6m 6s
6659:	learn: 0.0015965	total: 11m 10s	remaining: 5m 36s
6165:	learn: 0.0014946	total: 11m 10s	remaining: 6m 56s
6784:	learn: 0.0015229	total: 11m 9s	remaining: 5m 17s
6660:	learn: 0.0015469	total: 11m 9s	remaining: 5m 35s
6660:	learn: 0.0015961	total: 11m 10s	remaining: 5m 35s
6465:	learn: 0.0020432	total: 11m 10s	remaining: 6m 6s
6785:	learn: 0.0015229	total: 11m 10s	remaining: 5m 17s
6166:	learn: 0.0014946	total: 11m 10s	remaining: 6m 56s
6661:	learn: 0.0015469	total: 11m 9s	remaining: 5m 35s
6466:	learn: 0.0020432	total: 11m 10s	remaining: 6m 6s
6661:	learn: 0.0015961	total: 11m 10s	remaining: 5m 35s
6786:	learn: 0.0015229	total: 11m 10s	remaining: 5m 17s
6167:	learn: 0.0014946	total: 11m 10s	remaining: 6m 56s
6467:	learn: 0.0020432	total: 11m 10s	remaining: 6m 6s
6662:	learn: 0.0015469	total: 11m 10s	remaining: 5m 35s
6662:	learn: 0.0015961	total: 11m 10s	remaining: 5m 35s
6787:	learn: 0.0015229	total: 11m 10s	remaining: 5m 17s
6663:	learn: 0.0015469	total: 11m 10s	remaining: 5m 35s
6168:	learn: 0.0014942	total: 11m 10s	remaining: 6m 56s
6468:	learn: 0.0020432	total: 11m 10s	remaining: 6m 5s
6169:	learn: 0.0014942	total: 11m 10s	remaining: 6m 56s
6663:	learn: 0.0015961	total: 11m 10s	remaining: 5m 35s
6788:	learn: 0.0015228	total: 11m 10s	remaining: 5m 17s
6664:	learn: 0.0015469	total: 11m 10s	remaining: 5m 35s
6469:	learn: 0.0020432	total: 11m 10s	remaining: 6m 5s
6170:	learn: 0.0014939	total: 11m 10s	remaining: 6m 56s
6470:	learn: 0.0020432	total: 11m 10s	remaining: 6m 5s
6664:	learn: 0.0015961	total: 11m 10s	remaining: 5m 35s
6789:	learn: 0.0015229	total: 11m 10s	remaining: 5m 16s
6665:	learn: 0.0015469	total: 11m 10s	remaining: 5m 35s
6471:	learn: 0.0020432	total: 11m 10s	remaining: 6m 5s
6665:	learn: 0.0015961	total: 11m 10s	remaining: 5m 35s
6790:	learn: 0.0015223	total: 11m 10s	remaining: 5m 16s
6171:	learn: 0.0014937	total: 11m 10s	remaining: 6m 55s
6666:	learn: 0.0015469	total: 11m 10s	remaining: 5m 35s
6472:	learn: 0.0020432	total: 11m 10s	remaining: 6m 5s
6791:	learn: 0.0015218	total: 11m 10s	remaining: 5m 16s
6666:	learn: 0.0015961	total: 11m 10s	remaining: 5m 35s
6172:	learn: 0.0014937	total: 11m 10s	remaining: 6m 55s
6792:	learn: 0.0015219	total: 11m 10s	remaining: 5m 16s
6667:	learn: 0.0015469	total: 11m 10s	remaining: 5m 35s
6473:	learn: 0.0020432	total: 11m 10s	remaining: 6m 5s
6667:	learn: 0.0015961	total: 11m 10s	remaining: 5m 35s
6173:	learn: 0.0014937	total: 11m 10s	remaining: 6m 55s
6668:	learn: 0.0015469	total: 11m 10s	remaining: 5m 35s
6793:	learn: 0.0015219	total: 11m 10s	remaining: 5m 16s
6474:	learn: 0.0020432	total: 11m 10s	remaining: 6m 5s
6668:	learn: 0.0015961	total: 11m 10s	remaining: 5m 35s
6669:	learn: 0.0015469	total: 11m 10s	remaining: 5m 34s
6174:	learn: 0.0014932	total: 11m 11s	remaining: 6m 55s
6475:	learn: 0.0020432	total: 11m 11s	remaining: 6m 5s
6794:	learn: 0.0015214	total: 11m 10s	remaining: 5m 16s
6670:	learn: 0.0015469	total: 11m 10s	remaining: 5m 34s
6669:	learn: 0.0015956	total: 11m 11s	remaining: 5m 35s
6671:	learn: 0.0015469	total: 11m 10s	remaining: 5m 34s
6476:	learn: 0.0020432	total: 11m 11s	remaining: 6m 5s
6175:	learn: 0.0014929	total: 11m 11s	remaining: 6m 55s
6795:	learn: 0.0015214	total: 11m 11s	remaining: 5m 16s
6670:	learn: 0.0015956	total: 11m 11s	remaining: 5m 34s
6477:	learn: 0.0020432	total: 11m 11s	remaining: 6m 4s
6672:	learn: 0.0015469	total: 11m 11s	remaining: 5m 34s
6671:	learn: 0.0015956	total: 11m 11s	remaining: 5m 34s
6176:	learn: 0.0014929	total: 11m 11s	remaining: 6m 55s
6796:	learn: 0.0015214	total: 11m 11s	remaining: 5m 16s
6673:	learn: 0.0015469	total: 11m 11s	remaining: 5m 34s
6478:	learn: 0.0020432	total: 11m 11s	remaining: 6m 4s
6672:	learn: 0.0015956	total: 11m 11s	remaining: 5m 34s
6797:	learn: 0.0015214	total: 11m 11s	remaining: 5m 16s
6177:	learn: 0.0014929	total: 11m 11s	remaining: 6m 55s
6674:	learn: 0.0015468	total: 11m 11s	remaining: 5m 34s
6479:	learn: 0.0020432	total: 11m 11s	remaining: 6m 4s
6178:	learn: 0.0014925	total: 11m 11s	remaining: 6m 55s
6673:	learn: 0.0015956	total: 11m 11s	remaining: 5m 34s
6798:	learn: 0.0015211	total: 11m 11s	remaining: 5m 16s
6675:	learn: 0.0015468	total: 11m 11s	remaining: 5m 34s
6480:	learn: 0.0020432	total: 11m 11s	remaining: 6m 4s
6179:	learn: 0.0014925	total: 11m 11s	remaining: 6m 55s
6674:	learn: 0.0015956	total: 11m 11s	remaining: 5m 34s
6676:	learn: 0.0015468	total: 11m 11s	remaining: 5m 34s
6799:	learn: 0.0015211	total: 11m 11s	remaining: 5m 16s
6180:	learn: 0.0014925	total: 11m 11s	remaining: 6m 55s
6481:	learn: 0.0020432	total: 11m 11s	remaining: 6m 4s
6677:	learn: 0.0015468	total: 11m 11s	remaining: 5m 34s
6800:	learn: 0.0015211	total: 11m 11s	remaining: 5m 15s
6675:	learn: 0.0015956	total: 11m 11s	remaining: 5m 34s
6181:	learn: 0.0014922	total: 11m 11s	remaining: 6m 54s
6482:	learn: 0.0020432	total: 11m 11s	remaining: 6m 4s
6678:	learn: 0.0015464	total: 11m 11s	remaining: 5m 33s
6801:	learn: 0.0015211	total: 11m 11s	remaining: 5m 15s
6676:	learn: 0.0015956	total: 11m 11s	remaining: 5m 34s
6483:	learn: 0.0020432	total: 11m 11s	remaining: 6m 4s
6679:	learn: 0.0015464	total: 11m 11s	remaining: 5m 33s
6802:	learn: 0.0015211	total: 11m 11s	remaining: 5m 15s
6182:	learn: 0.0014918	total: 11m 11s	remaining: 6m 54s
6680:	learn: 0.0015464	total: 11m 11s	remaining: 5m 33s
6677:	learn: 0.0015956	total: 11m 11s	remaining: 5m 34s
6484:	learn: 0.0020432	total: 11m 11s	remaining: 6m 4s
6803:	learn: 0.0015211	total: 11m 11s	remaining: 5m 15s
6183:	learn: 0.0014918	total: 11m 12s	remaining: 6m 54s
6681:	learn: 0.0015464	total: 11m 11s	remaining: 5m 33s
6678:	learn: 0.0015956	total: 11m 12s	remaining: 5m 34s
6485:	learn: 0.0020432	total: 11m 12s	remaining: 6m 4s
6184:	learn: 0.0014918	total: 11m 12s	remaining: 6m 54s
6804:	learn: 0.0015211	total: 11m 12s	remaining: 5m 15s
6682:	learn: 0.0015464	total: 11m 11s	remaining: 5m 33s
6679:	learn: 0.0015956	total: 11m 12s	remaining: 5m 34s
6486:	learn: 0.0020432	total: 11m 12s	remaining: 6m 4s
6805:	learn: 0.0015211	total: 11m 12s	remaining: 5m 15s
6185:	learn: 0.0014913	total: 11m 12s	remaining: 6m 54s
6683:	learn: 0.0015464	total: 11m 11s	remaining: 5m 33s
6680:	learn: 0.0015956	total: 11m 12s	remaining: 5m 33s
6684:	learn: 0.0015464	total: 11m 12s	remaining: 5m 33s
6487:	learn: 0.0020432	total: 11m 12s	remaining: 6m 3s
6806:	learn: 0.0015207	total: 11m 12s	remaining: 5m 15s
6186:	learn: 0.0014910	total: 11m 12s	remaining: 6m 54s
6681:	learn: 0.0015954	total: 11m 12s	remaining: 5m 33s
6488:	learn: 0.0020427	total: 11m 12s	remaining: 6m 3s
6685:	learn: 0.0015464	total: 11m 12s	remaining: 5m 33s
6807:	learn: 0.0015207	total: 11m 12s	remaining: 5m 15s
6187:	learn: 0.0014907	total: 11m 12s	remaining: 6m 54s
6682:	learn: 0.0015954	total: 11m 12s	remaining: 5m 33s
6489:	learn: 0.0020422	total: 11m 12s	remaining: 6m 3s
6808:	learn: 0.0015205	total: 11m 12s	remaining: 5m 15s
6686:	learn: 0.0015464	total: 11m 12s	remaining: 5m 33s
6188:	learn: 0.0014902	total: 11m 12s	remaining: 6m 54s
6683:	learn: 0.0015954	total: 11m 12s	remaining: 5m 33s
6687:	learn: 0.0015464	total: 11m 12s	remaining: 5m 32s
6809:	learn: 0.0015206	total: 11m 12s	remaining: 5m 15s
6490:	learn: 0.0020422	total: 11m 12s	remaining: 6m 3s
6684:	learn: 0.0015954	total: 11m 12s	remaining: 5m 33s
6189:	learn: 0.0014897	total: 11m 12s	remaining: 6m 54s
6810:	learn: 0.0015206	total: 11m 12s	remaining: 5m 14s
6491:	learn: 0.0020422	total: 11m 12s	remaining: 6m 3s
6688:	learn: 0.0015464	total: 11m 12s	remaining: 5m 32s
6685:	learn: 0.0015954	total: 11m 12s	remaining: 5m 33s
6190:	learn: 0.0014894	total: 11m 12s	remaining: 6m 53s
6811:	learn: 0.0015206	total: 11m 12s	remaining: 5m 14s
6686:	learn: 0.0015954	total: 11m 12s	remaining: 5m 33s
6492:	learn: 0.0020421	total: 11m 12s	remaining: 6m 3s
6689:	learn: 0.0015464	total: 11m 12s	remaining: 5m 32s
6191:	learn: 0.0014894	total: 11m 12s	remaining: 6m 53s
6493:	learn: 0.0020421	total: 11m 12s	remaining: 6m 3s
6687:	learn: 0.0015954	total: 11m 12s	remaining: 5m 33s
6812:	learn: 0.0015206	total: 11m 12s	remaining: 5m 14s
6690:	learn: 0.0015464	total: 11m 12s	remaining: 5m 32s
6688:	learn: 0.0015954	total: 11m 12s	remaining: 5m 33s
6494:	learn: 0.0020421	total: 11m 12s	remaining: 6m 3s
6192:	learn: 0.0014892	total: 11m 12s	remaining: 6m 53s
6813:	learn: 0.0015204	total: 11m 12s	remaining: 5m 14s
6691:	learn: 0.0015464	total: 11m 12s	remaining: 5m 32s
6495:	learn: 0.0020421	total: 11m 13s	remaining: 6m 3s
6689:	learn: 0.0015949	total: 11m 13s	remaining: 5m 33s
6193:	learn: 0.0014888	total: 11m 13s	remaining: 6m 53s
6692:	learn: 0.0015464	total: 11m 12s	remaining: 5m 32s
6814:	learn: 0.0015200	total: 11m 13s	remaining: 5m 14s
6496:	learn: 0.0020420	total: 11m 13s	remaining: 6m 2s
6690:	learn: 0.0015949	total: 11m 13s	remaining: 5m 32s
6693:	learn: 0.0015464	total: 11m 12s	remaining: 5m 32s
6194:	learn: 0.0014884	total: 11m 13s	remaining: 6m 53s
6815:	learn: 0.0015200	total: 11m 13s	remaining: 5m 14s
6497:	learn: 0.0020421	total: 11m 13s	remaining: 6m 2s
6691:	learn: 0.0015949	total: 11m 13s	remaining: 5m 32s
6694:	learn: 0.0015464	total: 11m 13s	remaining: 5m 32s
6195:	learn: 0.0014881	total: 11m 13s	remaining: 6m 53s
6816:	learn: 0.0015195	total: 11m 13s	remaining: 5m 14s
6498:	learn: 0.0020421	total: 11m 13s	remaining: 6m 2s
6692:	learn: 0.0015946	total: 11m 13s	remaining: 5m 32s
6196:	learn: 0.0014881	total: 11m 13s	remaining: 6m 53s
6695:	learn: 0.0015464	total: 11m 13s	remaining: 5m 32s
6817:	learn: 0.0015191	total: 11m 13s	remaining: 5m 14s
6693:	learn: 0.0015939	total: 11m 13s	remaining: 5m 32s
6499:	learn: 0.0020421	total: 11m 13s	remaining: 6m 2s
6696:	learn: 0.0015462	total: 11m 13s	remaining: 5m 32s
6197:	learn: 0.0014881	total: 11m 13s	remaining: 6m 53s
6818:	learn: 0.0015191	total: 11m 13s	remaining: 5m 14s
6694:	learn: 0.0015939	total: 11m 13s	remaining: 5m 32s
6500:	learn: 0.0020421	total: 11m 13s	remaining: 6m 2s
6697:	learn: 0.0015462	total: 11m 13s	remaining: 5m 31s
6198:	learn: 0.0014876	total: 11m 13s	remaining: 6m 53s
6695:	learn: 0.0015935	total: 11m 13s	remaining: 5m 32s
6819:	learn: 0.0015191	total: 11m 13s	remaining: 5m 14s
6501:	learn: 0.0020421	total: 11m 13s	remaining: 6m 2s
6698:	learn: 0.0015462	total: 11m 13s	remaining: 5m 31s
6199:	learn: 0.0014876	total: 11m 13s	remaining: 6m 52s
6820:	learn: 0.0015191	total: 11m 13s	remaining: 5m 13s
6696:	learn: 0.0015930	total: 11m 13s	remaining: 5m 32s

6502:	learn: 0.0020421	total: 11m 13s	remaining: 6m 2s
6699:	learn: 0.0015462	total: 11m 13s	remaining: 5m 31s
6200:	learn: 0.0014876	total: 11m 13s	remaining: 6m 52s
6821:	learn: 0.0015191	total: 11m 13s	remaining: 5m 13s
6697:	learn: 0.0015930	total: 11m 13s	remaining: 5m 32s
6700:	learn: 0.0015462	total: 11m 13s	remaining: 5m 31s
6503:	learn: 0.0020421	total: 11m 13s	remaining: 6m 2s
6201:	learn: 0.0014872	total: 11m 13s	remaining: 6m 52s
6822:	learn: 0.0015187	total: 11m 13s	remaining: 5m 13s
6701:	learn: 0.0015462	total: 11m 13s	remaining: 5m 31s
6698:	learn: 0.0015930	total: 11m 13s	remaining: 5m 32s
6202:	learn: 0.0014872	total: 11m 14s	remaining: 6m 52s
6504:	learn: 0.0020421	total: 11m 14s	remaining: 6m 2s
6823:	learn: 0.0015187	total: 11m 13s	remaining: 5m 13s
6699:	learn: 0.0015930	total: 11m 14s	remaining: 5m 31s
6505:	learn: 0.0020421	total: 11m 14s	remaining: 6m 2s
6702:	learn: 0.0015462	total: 11m 13s	remaining: 5m 31s
6203:	learn: 0.0014868	total: 11m 14s	remaining: 6m 52s
6700:	learn: 0.0015930	total: 11m 14s	remaining: 5m 31s
6824:	learn: 0.0015187	total: 11m 14s	remaining: 5m 13s
6506:	learn: 0.0020421	total: 11m 14s	remaining: 6m 1s
6703:	learn: 0.0015462	total: 11m 13s	remaining: 5m 31s
6204:	learn: 0.0014864	total: 11m 14s	remaining: 6m 52s
6701:	learn: 0.0015930	total: 11m 14s	remaining: 5m 31s
6825:	learn: 0.0015187	total: 11m 14s	remaining: 5m 13s
6507:	learn: 0.0020421	total: 11m 14s	remaining: 6m 1s
6205:	learn: 0.0014860	total: 11m 14s	remaining: 6m 52s
6704:	learn: 0.0015462	total: 11m 14s	remaining: 5m 31s
6702:	learn: 0.0015930	total: 11m 14s	remaining: 5m 31s
6826:	learn: 0.0015187	total: 11m 14s	remaining: 5m 13s
6508:	learn: 0.0020421	total: 11m 14s	remaining: 6m 1s
6703:	learn: 0.0015926	total: 11m 14s	remaining: 5m 31s
6705:	learn: 0.0015462	total: 11m 14s	remaining: 5m 31s
6206:	learn: 0.0014856	total: 11m 14s	remaining: 6m 52s
6827:	learn: 0.0015187	total: 11m 14s	remaining: 5m 13s
6509:	learn: 0.0020421	total: 11m 14s	remaining: 6m 1s
6207:	learn: 0.0014852	total: 11m 14s	remaining: 6m 52s
6706:	learn: 0.0015462	total: 11m 14s	remaining: 5m 31s
6704:	learn: 0.0015926	total: 11m 14s	remaining: 5m 31s
6828:	learn: 0.0015187	total: 11m 14s	remaining: 5m 13s
6208:	learn: 0.0014852	total: 11m 14s	remaining: 6m 51s
6510:	learn: 0.0020421	total: 11m 14s	remaining: 6m 1s
6707:	learn: 0.0015462	total: 11m 14s	remaining: 5m 30s
6705:	learn: 0.0015926	total: 11m 14s	remaining: 5m 31s
6829:	learn: 0.0015187	total: 11m 14s	remaining: 5m 13s
6708:	learn: 0.0015462	total: 11m 14s	remaining: 5m 30s
6209:	learn: 0.0014852	total: 11m 14s	remaining: 6m 51s
6706:	learn: 0.0015923	total: 11m 14s	remaining: 5m 31s
6511:	learn: 0.0020421	total: 11m 14s	remaining: 6m 1s
6830:	learn: 0.0015187	total: 11m 14s	remaining: 5m 12s
6210:	learn: 0.0014847	total: 11m 14s	remaining: 6m 51s
6709:	learn: 0.0015462	total: 11m 14s	remaining: 5m 30s
6707:	learn: 0.0015921	total: 11m 14s	remaining: 5m 31s
6831:	learn: 0.0015183	total: 11m 14s	remaining: 5m 12s
6512:	learn: 0.0020421	total: 11m 14s	remaining: 6m 1s
6211:	learn: 0.0014847	total: 11m 14s	remaining: 6m 51s
6708:	learn: 0.0015921	total: 11m 14s	remaining: 5m 31s
6710:	learn: 0.0015462	total: 11m 14s	remaining: 5m 30s
6832:	learn: 0.0015181	total: 11m 14s	remaining: 5m 12s
6513:	learn: 0.0020421	total: 11m 14s	remaining: 6m 1s
6212:	learn: 0.0014847	total: 11m 15s	remaining: 6m 51s
6711:	learn: 0.0015462	total: 11m 14s	remaining: 5m 30s
6709:	learn: 0.0015921	total: 11m 15s	remaining: 5m 30s
6833:	learn: 0.0015181	total: 11m 14s	remaining: 5m 12s
6514:	learn: 0.0020410	total: 11m 15s	remaining: 6m 1s
6712:	learn: 0.0015458	total: 11m 14s	remaining: 5m 30s
6213:	learn: 0.0014847	total: 11m 15s	remaining: 6m 51s
6710:	learn: 0.0015921	total: 11m 15s	remaining: 5m 30s
6834:	learn: 0.0015182	total: 11m 15s	remaining: 5m 12s
6713:	learn: 0.0015458	total: 11m 14s	remaining: 5m 30s
6515:	learn: 0.0020410	total: 11m 15s	remaining: 6m 1s
6214:	learn: 0.0014847	total: 11m 15s	remaining: 6m 51s
6711:	learn: 0.0015921	total: 11m 15s	remaining: 5m 30s
6835:	learn: 0.0015182	total: 11m 15s	remaining: 5m 12s
6714:	learn: 0.0015458	total: 11m 15s	remaining: 5m 30s
6215:	learn: 0.0014847	total: 11m 15s	remaining: 6m 51s
6516:	learn: 0.0020410	total: 11m 15s	remaining: 6m
6836:	learn: 0.0015182	total: 11m 15s	remaining: 5m 12s
6715:	learn: 0.0015458	total: 11m 15s	remaining: 5m 30s
6712:	learn: 0.0015921	total: 11m 15s	remaining: 5m 30s
6216:	learn: 0.0014844	total: 11m 15s	remaining: 6m 50s
6517:	learn: 0.0020410	total: 11m 15s	remaining: 6m
6837:	learn: 0.0015182	total: 11m 15s	remaining: 5m 12s
6713:	learn: 0.0015921	total: 11m 15s	remaining: 5m 30s
6716:	learn: 0.0015457	total: 11m 15s	remaining: 5m 30s
6217:	learn: 0.0014840	total: 11m 15s	remaining: 6m 50s
6518:	learn: 0.0020410	total: 11m 15s	remaining: 6m
6714:	learn: 0.0015921	total: 11m 15s	remaining: 5m 30s
6717:	learn: 0.0015457	total: 11m 15s	remaining: 5m 29s
6838:	learn: 0.0015182	total: 11m 15s	remaining: 5m 12s
6519:	learn: 0.0020410	total: 11m 15s	remaining: 6m
6218:	learn: 0.0014835	total: 11m 15s	remaining: 6m 50s
6718:	learn: 0.0015457	total: 11m 15s	remaining: 5m 29s
6715:	learn: 0.0015921	total: 11m 15s	remaining: 5m 30s
6839:	learn: 0.0015181	total: 11m 15s	remaining: 5m 12s
6520:	learn: 0.0020410	total: 11m 15s	remaining: 6m
6219:	learn: 0.0014835	total: 11m 15s	remaining: 6m 50s
6719:	learn: 0.0015457	total: 11m 15s	remaining: 5m 29s
6521:	learn: 0.0020410	total: 11m 15s	remaining: 6m
6840:	learn: 0.0015181	total: 11m 15s	remaining: 5m 12s
6716:	learn: 0.0015921	total: 11m 15s	remaining: 5m 30s
6220:	learn: 0.0014835	total: 11m 15s	remaining: 6m 50s
6720:	learn: 0.0015457	total: 11m 15s	remaining: 5m 29s
6522:	learn: 0.0020410	total: 11m 15s	remaining: 6m
6841:	learn: 0.0015181	total: 11m 15s	remaining: 5m 11s
6717:	learn: 0.0015921	total: 11m 15s	remaining: 5m 30s
6721:	learn: 0.0015457	total: 11m 15s	remaining: 5m 29s
6523:	learn: 0.0020410	total: 11m 15s	remaining: 6m
6221:	learn: 0.0014834	total: 11m 15s	remaining: 6m 50s
6842:	learn: 0.0015181	total: 11m 15s	remaining: 5m 11s
6718:	learn: 0.0015921	total: 11m 15s	remaining: 5m 30s
6722:	learn: 0.0015457	total: 11m 15s	remaining: 5m 29s
6524:	learn: 0.0020410	total: 11m 16s	remaining: 6m
6843:	learn: 0.0015178	total: 11m 15s	remaining: 5m 11s
6222:	learn: 0.0014834	total: 11m 16s	remaining: 6m 50s
6719:	learn: 0.0015921	total: 11m 16s	remaining: 5m 29s
6723:	learn: 0.0015457	total: 11m 15s	remaining: 5m 29s
6844:	learn: 0.0015174	total: 11m 16s	remaining: 5m 11s
6525:	learn: 0.0020410	total: 11m 16s	remaining: 5m 59s
6720:	learn: 0.0015916	total: 11m 16s	remaining: 5m 29s
6724:	learn: 0.0015457	total: 11m 15s	remaining: 5m 29s
6223:	learn: 0.0014830	total: 11m 16s	remaining: 6m 50s
6845:	learn: 0.0015174	total: 11m 16s	remaining: 5m 11s
6526:	learn: 0.0020404	total: 11m 16s	remaining: 5m 59s
6721:	learn: 0.0015916	total: 11m 16s	remaining: 5m 29s
6725:	learn: 0.0015457	total: 11m 16s	remaining: 5m 29s
6846:	learn: 0.0015174	total: 11m 16s	remaining: 5m 11s
6224:	learn: 0.0014830	total: 11m 16s	remaining: 6m 50s
6722:	learn: 0.0015914	total: 11m 16s	remaining: 5m 29s
6527:	learn: 0.0020404	total: 11m 16s	remaining: 5m 59s
6726:	learn: 0.0015457	total: 11m 16s	remaining: 5m 28s
6847:	learn: 0.0015173	total: 11m 16s	remaining: 5m 11s
6723:	learn: 0.0015914	total: 11m 16s	remaining: 5m 29s
6225:	learn: 0.0014826	total: 11m 16s	remaining: 6m 50s
6727:	learn: 0.0015457	total: 11m 16s	remaining: 5m 28s
6528:	learn: 0.0020404	total: 11m 16s	remaining: 5m 59s
6226:	learn: 0.0014823	total: 11m 16s	remaining: 6m 49s
6848:	learn: 0.0015173	total: 11m 16s	remaining: 5m 11s
6529:	learn: 0.0020404	total: 11m 16s	remaining: 5m 59s
6724:	learn: 0.0015914	total: 11m 16s	remaining: 5m 29s
6728:	learn: 0.0015457	total: 11m 16s	remaining: 5m 28s
6530:	learn: 0.0020404	total: 11m 16s	remaining: 5m 59s
6849:	learn: 0.0015173	total: 11m 16s	remaining: 5m 11s
6227:	learn: 0.0014818	total: 11m 16s	remaining: 6m 49s
6725:	learn: 0.0015914	total: 11m 16s	remaining: 5m 29s
6729:	learn: 0.0015457	total: 11m 16s	remaining: 5m 28s
6531:	learn: 0.0020404	total: 11m 16s	remaining: 5m 59s
6850:	learn: 0.0015173	total: 11m 16s	remaining: 5m 11s
6726:	learn: 0.0015914	total: 11m 16s	remaining: 5m 29s
6228:	learn: 0.0014815	total: 11m 16s	remaining: 6m 49s
6532:	learn: 0.0020399	total: 11m 16s	remaining: 5m 59s
6730:	learn: 0.0015457	total: 11m 16s	remaining: 5m 28s
6851:	learn: 0.0015173	total: 11m 16s	remaining: 5m 10s
6727:	learn: 0.0015909	total: 11m 16s	remaining: 5m 29s
6533:	learn: 0.0020399	total: 11m 16s	remaining: 5m 59s
6852:	learn: 0.0015173	total: 11m 16s	remaining: 5m 10s
6229:	learn: 0.0014812	total: 11m 16s	remaining: 6m 49s
6731:	learn: 0.0015457	total: 11m 16s	remaining: 5m 28s
6534:	learn: 0.0020399	total: 11m 16s	remaining: 5m 58s
6728:	learn: 0.0015907	total: 11m 16s	remaining: 5m 29s
6732:	learn: 0.0015457	total: 11m 16s	remaining: 5m 28s
6853:	learn: 0.0015173	total: 11m 16s	remaining: 5m 10s
6230:	learn: 0.0014812	total: 11m 17s	remaining: 6m 49s
6729:	learn: 0.0015907	total: 11m 17s	remaining: 5m 28s
6535:	learn: 0.0020399	total: 11m 17s	remaining: 5m 58s
6733:	learn: 0.0015454	total: 11m 16s	remaining: 5m 28s
6854:	learn: 0.0015173	total: 11m 17s	remaining: 5m 10s
6231:	learn: 0.0014812	total: 11m 17s	remaining: 6m 49s
6730:	learn: 0.0015903	total: 11m 17s	remaining: 5m 28s
6536:	learn: 0.0020399	total: 11m 17s	remaining: 5m 58s
6855:	learn: 0.0015173	total: 11m 17s	remaining: 5m 10s
6734:	learn: 0.0015454	total: 11m 16s	remaining: 5m 28s
6232:	learn: 0.0014812	total: 11m 17s	remaining: 6m 49s
6856:	learn: 0.0015173	total: 11m 17s	remaining: 5m 10s
6731:	learn: 0.0015903	total: 11m 17s	remaining: 5m 28s
6537:	learn: 0.0020399	total: 11m 17s	remaining: 5m 58s
6735:	learn: 0.0015454	total: 11m 17s	remaining: 5m 28s
6233:	learn: 0.0014808	total: 11m 17s	remaining: 6m 49s
6857:	learn: 0.0015173	total: 11m 17s	remaining: 5m 10s
6732:	learn: 0.0015899	total: 11m 17s	remaining: 5m 28s
6538:	learn: 0.0020399	total: 11m 17s	remaining: 5m 58s
6736:	learn: 0.0015454	total: 11m 17s	remaining: 5m 27s
6234:	learn: 0.0014808	total: 11m 17s	remaining: 6m 49s
6858:	learn: 0.0015173	total: 11m 17s	remaining: 5m 10s
6733:	learn: 0.0015897	total: 11m 17s	remaining: 5m 28s
6539:	learn: 0.0020399	total: 11m 17s	remaining: 5m 58s
6737:	learn: 0.0015454	total: 11m 17s	remaining: 5m 27s
6235:	learn: 0.0014804	total: 11m 17s	remaining: 6m 48s
6859:	learn: 0.0015170	total: 11m 17s	remaining: 5m 10s
6734:	learn: 0.0015897	total: 11m 17s	remaining: 5m 28s
6738:	learn: 0.0015452	total: 11m 17s	remaining: 5m 27s
6540:	learn: 0.0020399	total: 11m 17s	remaining: 5m 58s
6236:	learn: 0.0014804	total: 11m 17s	remaining: 6m 48s
6735:	learn: 0.0015897	total: 11m 17s	remaining: 5m 28s
6860:	learn: 0.0015166	total: 11m 17s	remaining: 5m 10s
6237:	learn: 0.0014803	total: 11m 17s	remaining: 6m 48s
6739:	learn: 0.0015452	total: 11m 17s	remaining: 5m 27s
6541:	learn: 0.0020399	total: 11m 17s	remaining: 5m 58s
6736:	learn: 0.0015897	total: 11m 17s	remaining: 5m 28s
6740:	learn: 0.0015452	total: 11m 17s	remaining: 5m 27s
6861:	learn: 0.0015166	total: 11m 17s	remaining: 5m 9s
6542:	learn: 0.0020399	total: 11m 17s	remaining: 5m 58s
6238:	learn: 0.0014800	total: 11m 17s	remaining: 6m 48s
6737:	learn: 0.0015891	total: 11m 17s	remaining: 5m 28s
6741:	learn: 0.0015452	total: 11m 17s	remaining: 5m 27s
6862:	learn: 0.0015166	total: 11m 17s	remaining: 5m 9s
6543:	learn: 0.0020399	total: 11m 17s	remaining: 5m 58s
6742:	learn: 0.0015452	total: 11m 17s	remaining: 5m 27s
6239:	learn: 0.0014800	total: 11m 17s	remaining: 6m 48s
6738:	learn: 0.0015891	total: 11m 17s	remaining: 5m 28s
6863:	learn: 0.0015166	total: 11m 17s	remaining: 5m 9s
6743:	learn: 0.0015452	total: 11m 17s	remaining: 5m 27s
6739:	learn: 0.0015891	total: 11m 18s	remaining: 5m 27s
6544:	learn: 0.0020392	total: 11m 18s	remaining: 5m 57s
6240:	learn: 0.0014800	total: 11m 18s	remaining: 6m 48s
6864:	learn: 0.0015166	total: 11m 17s	remaining: 5m 9s
6744:	learn: 0.0015449	total: 11m 17s	remaining: 5m 27s
6740:	learn: 0.0015887	total: 11m 18s	remaining: 5m 27s
6545:	learn: 0.0020392	total: 11m 18s	remaining: 5m 57s
6865:	learn: 0.0015166	total: 11m 18s	remaining: 5m 9s
6241:	learn: 0.0014796	total: 11m 18s	remaining: 6m 48s
6745:	learn: 0.0015449	total: 11m 18s	remaining: 5m 27s
6546:	learn: 0.0020384	total: 11m 18s	remaining: 5m 57s
6741:	learn: 0.0015887	total: 11m 18s	remaining: 5m 27s
6866:	learn: 0.0015166	total: 11m 18s	remaining: 5m 9s
6242:	learn: 0.0014796	total: 11m 18s	remaining: 6m 48s
6746:	learn: 0.0015449	total: 11m 18s	remaining: 5m 26s
6547:	learn: 0.0020384	total: 11m 18s	remaining: 5m 57s
6742:	learn: 0.0015887	total: 11m 18s	remaining: 5m 27s
6867:	learn: 0.0015166	total: 11m 18s	remaining: 5m 9s
6747:	learn: 0.0015448	total: 11m 18s	remaining: 5m 26s
6743:	learn: 0.0015886	total: 11m 18s	remaining: 5m 27s
6243:	learn: 0.0014792	total: 11m 18s	remaining: 6m 48s
6548:	learn: 0.0020384	total: 11m 18s	remaining: 5m 57s
6868:	learn: 0.0015166	total: 11m 18s	remaining: 5m 9s
6744:	learn: 0.0015886	total: 11m 18s	remaining: 5m 27s
6748:	learn: 0.0015448	total: 11m 18s	remaining: 5m 26s
6244:	learn: 0.0014792	total: 11m 18s	remaining: 6m 48s
6549:	learn: 0.0020384	total: 11m 18s	remaining: 5m 57s
6869:	learn: 0.0015162	total: 11m 18s	remaining: 5m 9s
6749:	learn: 0.0015448	total: 11m 18s	remaining: 5m 26s
6745:	learn: 0.0015882	total: 11m 18s	remaining: 5m 27s
6550:	learn: 0.0020383	total: 11m 18s	remaining: 5m 57s
6870:	learn: 0.0015162	total: 11m 18s	remaining: 5m 9s
6245:	learn: 0.0014789	total: 11m 18s	remaining: 6m 47s
6746:	learn: 0.0015877	total: 11m 18s	remaining: 5m 27s
6750:	learn: 0.0015448	total: 11m 18s	remaining: 5m 26s
6551:	learn: 0.0020383	total: 11m 18s	remaining: 5m 57s
6871:	learn: 0.0015162	total: 11m 18s	remaining: 5m 8s
6246:	learn: 0.0014785	total: 11m 18s	remaining: 6m 47s
6747:	learn: 0.0015871	total: 11m 18s	remaining: 5m 27s
6751:	learn: 0.0015448	total: 11m 18s	remaining: 5m 26s
6872:	learn: 0.0015162	total: 11m 18s	remaining: 5m 8s
6552:	learn: 0.0020383	total: 11m 18s	remaining: 5m 57s
6748:	learn: 0.0015867	total: 11m 18s	remaining: 5m 26s
6247:	learn: 0.0014785	total: 11m 18s	remaining: 6m 47s
6749:	learn: 0.0015861	total: 11m 18s	remaining: 5m 26s
6873:	learn: 0.0015162	total: 11m 18s	remaining: 5m 8s
6752:	learn: 0.0015448	total: 11m 18s	remaining: 5m 26s
6248:	learn: 0.0014780	total: 11m 18s	remaining: 6m 47s
6553:	learn: 0.0020384	total: 11m 18s	remaining: 5m 57s
6874:	learn: 0.0015162	total: 11m 18s	remaining: 5m 8s
6750:	learn: 0.0015855	total: 11m 19s	remaining: 5m 26s
6753:	learn: 0.0015448	total: 11m 18s	remaining: 5m 26s
6554:	learn: 0.0020384	total: 11m 19s	remaining: 5m 56s
6249:	learn: 0.0014776	total: 11m 19s	remaining: 6m 47s
6875:	learn: 0.0015162	total: 11m 19s	remaining: 5m 8s
6751:	learn: 0.0015855	total: 11m 19s	remaining: 5m 26s
6754:	learn: 0.0015444	total: 11m 18s	remaining: 5m 26s
6250:	learn: 0.0014772	total: 11m 19s	remaining: 6m 47s
6555:	learn: 0.0020384	total: 11m 19s	remaining: 5m 56s
6752:	learn: 0.0015855	total: 11m 19s	remaining: 5m 26s
6876:	learn: 0.0015162	total: 11m 19s	remaining: 5m 8s
6755:	learn: 0.0015444	total: 11m 19s	remaining: 5m 26s
6251:	learn: 0.0014772	total: 11m 19s	remaining: 6m 47s
6556:	learn: 0.0020384	total: 11m 19s	remaining: 5m 56s
6753:	learn: 0.0015855	total: 11m 19s	remaining: 5m 26s
6877:	learn: 0.0015162	total: 11m 19s	remaining: 5m 8s
6756:	learn: 0.0015444	total: 11m 19s	remaining: 5m 25s
6252:	learn: 0.0014772	total: 11m 19s	remaining: 6m 47s
6557:	learn: 0.0020384	total: 11m 19s	remaining: 5m 56s
6754:	learn: 0.0015855	total: 11m 19s	remaining: 5m 26s
6878:	learn: 0.0015162	total: 11m 19s	remaining: 5m 8s
6757:	learn: 0.0015444	total: 11m 19s	remaining: 5m 25s
6558:	learn: 0.0020384	total: 11m 19s	remaining: 5m 56s
6253:	learn: 0.0014769	total: 11m 19s	remaining: 6m 47s
6755:	learn: 0.0015855	total: 11m 19s	remaining: 5m 26s
6879:	learn: 0.0015162	total: 11m 19s	remaining: 5m 8s
6254:	learn: 0.0014767	total: 11m 19s	remaining: 6m 46s
6758:	learn: 0.0015444	total: 11m 19s	remaining: 5m 25s
6880:	learn: 0.0015162	total: 11m 19s	remaining: 5m 8s
6559:	learn: 0.0020384	total: 11m 19s	remaining: 5m 56s
6756:	learn: 0.0015855	total: 11m 19s	remaining: 5m 26s

6255:	learn: 0.0014767	total: 11m 19s	remaining: 6m 46s
6759:	learn: 0.0015444	total: 11m 19s	remaining: 5m 25s
6560:	learn: 0.0020384	total: 11m 19s	remaining: 5m 56s
6881:	learn: 0.0015162	total: 11m 19s	remaining: 5m 7s
6757:	learn: 0.0015855	total: 11m 19s	remaining: 5m 26s
6256:	learn: 0.0014764	total: 11m 19s	remaining: 6m 46s
6882:	learn: 0.0015161	total: 11m 19s	remaining: 5m 7s
6760:	learn: 0.0015444	total: 11m 19s	remaining: 5m 25s
6561:	learn: 0.0020384	total: 11m 19s	remaining: 5m 56s
6758:	learn: 0.0015851	total: 11m 19s	remaining: 5m 25s
6257:	learn: 0.0014764	total: 11m 19s	remaining: 6m 46s
6883:	learn: 0.0015161	total: 11m 19s	remaining: 5m 7s
6761:	learn: 0.0015444	total: 11m 19s	remaining: 5m 25s
6258:	learn: 0.0014759	total: 11m 19s	remaining: 6m 46s
6759:	learn: 0.0015847	total: 11m 19s	remaining: 5m 25s
6562:	learn: 0.0020384	total: 11m 19s	remaining: 5m 56s
6884:	learn: 0.0015161	total: 11m 19s	remaining: 5m 7s
6762:	learn: 0.0015444	total: 11m 19s	remaining: 5m 25s
6760:	learn: 0.0015847	total: 11m 19s	remaining: 5m 25s
6259:	learn: 0.0014759	total: 11m 20s	remaining: 6m 46s
6563:	learn: 0.0020383	total: 11m 20s	remaining: 5m 55s
6885:	learn: 0.0015155	total: 11m 19s	remaining: 5m 7s
6763:	learn: 0.0015444	total: 11m 19s	remaining: 5m 25s
6761:	learn: 0.0015847	total: 11m 20s	remaining: 5m 25s
6260:	learn: 0.0014759	total: 11m 20s	remaining: 6m 46s
6764:	learn: 0.0015444	total: 11m 19s	remaining: 5m 25s
6886:	learn: 0.0015155	total: 11m 20s	remaining: 5m 7s
6762:	learn: 0.0015847	total: 11m 20s	remaining: 5m 25s
6564:	learn: 0.0020384	total: 11m 20s	remaining: 5m 55s
6765:	learn: 0.0015444	total: 11m 20s	remaining: 5m 25s
6887:	learn: 0.0015155	total: 11m 20s	remaining: 5m 7s
6261:	learn: 0.0014755	total: 11m 20s	remaining: 6m 46s
6763:	learn: 0.0015847	total: 11m 20s	remaining: 5m 25s
6888:	learn: 0.0015155	total: 11m 20s	remaining: 5m 7s
6565:	learn: 0.0020383	total: 11m 20s	remaining: 5m 55s
6262:	learn: 0.0014755	total: 11m 20s	remaining: 6m 45s
6766:	learn: 0.0015444	total: 11m 20s	remaining: 5m 24s
6889:	learn: 0.0015155	total: 11m 20s	remaining: 5m 7s
6566:	learn: 0.0020384	total: 11m 20s	remaining: 5m 55s
6764:	learn: 0.0015847	total: 11m 20s	remaining: 5m 25s
6767:	learn: 0.0015444	total: 11m 20s	remaining: 5m 24s
6890:	learn: 0.0015152	total: 11m 20s	remaining: 5m 6s
6263:	learn: 0.0014751	total: 11m 20s	remaining: 6m 45s
6567:	learn: 0.0020383	total: 11m 20s	remaining: 5m 55s
6765:	learn: 0.0015847	total: 11m 20s	remaining: 5m 25s
6768:	learn: 0.0015444	total: 11m 20s	remaining: 5m 24s
6264:	learn: 0.0014751	total: 11m 20s	remaining: 6m 45s
6891:	learn: 0.0015147	total: 11m 20s	remaining: 5m 6s
6568:	learn: 0.0020383	total: 11m 20s	remaining: 5m 55s
6766:	learn: 0.0015847	total: 11m 20s	remaining: 5m 25s
6769:	learn: 0.0015440	total: 11m 20s	remaining: 5m 24s
6265:	learn: 0.0014747	total: 11m 20s	remaining: 6m 45s
6892:	learn: 0.0015143	total: 11m 20s	remaining: 5m 6s
6569:	learn: 0.0020383	total: 11m 20s	remaining: 5m 55s
6767:	learn: 0.0015847	total: 11m 20s	remaining: 5m 25s
6770:	learn: 0.0015438	total: 11m 20s	remaining: 5m 24s
6570:	learn: 0.0020383	total: 11m 20s	remaining: 5m 55s
6266:	learn: 0.0014747	total: 11m 20s	remaining: 6m 45s
6893:	learn: 0.0015139	total: 11m 20s	remaining: 5m 6s
6768:	learn: 0.0015847	total: 11m 20s	remaining: 5m 24s
6771:	learn: 0.0015438	total: 11m 20s	remaining: 5m 24s
6894:	learn: 0.0015139	total: 11m 20s	remaining: 5m 6s
6571:	learn: 0.0020383	total: 11m 20s	remaining: 5m 55s
6267:	learn: 0.0014747	total: 11m 20s	remaining: 6m 45s
6895:	learn: 0.0015139	total: 11m 20s	remaining: 5m 6s
6772:	learn: 0.0015438	total: 11m 20s	remaining: 5m 24s
6268:	learn: 0.0014747	total: 11m 20s	remaining: 6m 45s
6769:	learn: 0.0015847	total: 11m 20s	remaining: 5m 24s
6572:	learn: 0.0020383	total: 11m 21s	remaining: 5m 55s
6896:	learn: 0.0015139	total: 11m 20s	remaining: 5m 6s
6770:	learn: 0.0015847	total: 11m 21s	remaining: 5m 24s
6773:	learn: 0.0015438	total: 11m 20s	remaining: 5m 24s
6269:	learn: 0.0014744	total: 11m 21s	remaining: 6m 45s
6573:	learn: 0.0020383	total: 11m 21s	remaining: 5m 54s
6774:	learn: 0.0015438	total: 11m 20s	remaining: 5m 24s
6897:	learn: 0.0015139	total: 11m 21s	remaining: 5m 6s
6771:	learn: 0.0015847	total: 11m 21s	remaining: 5m 24s
6270:	learn: 0.0014742	total: 11m 21s	remaining: 6m 45s
6775:	learn: 0.0015438	total: 11m 21s	remaining: 5m 24s
6574:	learn: 0.0020383	total: 11m 21s	remaining: 5m 54s
6772:	learn: 0.0015847	total: 11m 21s	remaining: 5m 24s
6898:	learn: 0.0015139	total: 11m 21s	remaining: 5m 6s
6271:	learn: 0.0014742	total: 11m 21s	remaining: 6m 44s
6575:	learn: 0.0020373	total: 11m 21s	remaining: 5m 54s
6776:	learn: 0.0015438	total: 11m 21s	remaining: 5m 23s
6899:	learn: 0.0015139	total: 11m 21s	remaining: 5m 6s
6773:	learn: 0.0015847	total: 11m 21s	remaining: 5m 24s
6777:	learn: 0.0015435	total: 11m 21s	remaining: 5m 23s
6272:	learn: 0.0014742	total: 11m 21s	remaining: 6m 44s
6576:	learn: 0.0020373	total: 11m 21s	remaining: 5m 54s
6900:	learn: 0.0015139	total: 11m 21s	remaining: 5m 5s
6774:	learn: 0.0015847	total: 11m 21s	remaining: 5m 24s
6778:	learn: 0.0015435	total: 11m 21s	remaining: 5m 23s
6273:	learn: 0.0014742	total: 11m 21s	remaining: 6m 44s
6577:	learn: 0.0020373	total: 11m 21s	remaining: 5m 54s
6901:	learn: 0.0015139	total: 11m 21s	remaining: 5m 5s
6775:	learn: 0.0015847	total: 11m 21s	remaining: 5m 24s
6779:	learn: 0.0015432	total: 11m 21s	remaining: 5m 23s
6578:	learn: 0.0020373	total: 11m 21s	remaining: 5m 54s
6274:	learn: 0.0014742	total: 11m 21s	remaining: 6m 44s
6776:	learn: 0.0015847	total: 11m 21s	remaining: 5m 24s
6780:	learn: 0.0015432	total: 11m 21s	remaining: 5m 23s
6902:	learn: 0.0015135	total: 11m 21s	remaining: 5m 5s
6579:	learn: 0.0020373	total: 11m 21s	remaining: 5m 54s
6275:	learn: 0.0014742	total: 11m 21s	remaining: 6m 44s
6777:	learn: 0.0015843	total: 11m 21s	remaining: 5m 24s
6903:	learn: 0.0015128	total: 11m 21s	remaining: 5m 5s
6781:	learn: 0.0015428	total: 11m 21s	remaining: 5m 23s
6580:	learn: 0.0020373	total: 11m 21s	remaining: 5m 54s
6276:	learn: 0.0014742	total: 11m 21s	remaining: 6m 44s
6778:	learn: 0.0015843	total: 11m 21s	remaining: 5m 23s
6782:	learn: 0.0015428	total: 11m 21s	remaining: 5m 23s
6904:	learn: 0.0015128	total: 11m 21s	remaining: 5m 5s
6581:	learn: 0.0020373	total: 11m 21s	remaining: 5m 54s
6779:	learn: 0.0015843	total: 11m 21s	remaining: 5m 23s
6277:	learn: 0.0014738	total: 11m 21s	remaining: 6m 44s
6783:	learn: 0.0015426	total: 11m 21s	remaining: 5m 23s
6905:	learn: 0.0015128	total: 11m 21s	remaining: 5m 5s
6582:	learn: 0.0020373	total: 11m 22s	remaining: 5m 54s
6780:	learn: 0.0015843	total: 11m 22s	remaining: 5m 23s
6784:	learn: 0.0015426	total: 11m 21s	remaining: 5m 23s
6278:	learn: 0.0014734	total: 11m 22s	remaining: 6m 44s
6906:	learn: 0.0015128	total: 11m 21s	remaining: 5m 5s
6583:	learn: 0.0020373	total: 11m 22s	remaining: 5m 53s
6785:	learn: 0.0015426	total: 11m 21s	remaining: 5m 22s
6781:	learn: 0.0015839	total: 11m 22s	remaining: 5m 23s
6279:	learn: 0.0014731	total: 11m 22s	remaining: 6m 44s
6907:	learn: 0.0015128	total: 11m 22s	remaining: 5m 5s
6584:	learn: 0.0020373	total: 11m 22s	remaining: 5m 53s
6786:	learn: 0.0015426	total: 11m 22s	remaining: 5m 22s
6782:	learn: 0.0015832	total: 11m 22s	remaining: 5m 23s
6908:	learn: 0.0015128	total: 11m 22s	remaining: 5m 5s
6280:	learn: 0.0014727	total: 11m 22s	remaining: 6m 43s
6787:	learn: 0.0015426	total: 11m 22s	remaining: 5m 22s
6585:	learn: 0.0020373	total: 11m 22s	remaining: 5m 53s
6909:	learn: 0.0015128	total: 11m 22s	remaining: 5m 5s
6783:	learn: 0.0015826	total: 11m 22s	remaining: 5m 23s
6586:	learn: 0.0020373	total: 11m 22s	remaining: 5m 53s
6788:	learn: 0.0015426	total: 11m 22s	remaining: 5m 22s
6281:	learn: 0.0014722	total: 11m 22s	remaining: 6m 43s
6910:	learn: 0.0015128	total: 11m 22s	remaining: 5m 4s
6587:	learn: 0.0020373	total: 11m 22s	remaining: 5m 53s
6784:	learn: 0.0015826	total: 11m 22s	remaining: 5m 23s
6789:	learn: 0.0015426	total: 11m 22s	remaining: 5m 22s
6282:	learn: 0.0014719	total: 11m 22s	remaining: 6m 43s
6911:	learn: 0.0015127	total: 11m 22s	remaining: 5m 4s
6588:	learn: 0.0020373	total: 11m 22s	remaining: 5m 53s
6790:	learn: 0.0015426	total: 11m 22s	remaining: 5m 22s
6785:	learn: 0.0015826	total: 11m 22s	remaining: 5m 23s
6283:	learn: 0.0014719	total: 11m 22s	remaining: 6m 43s
6589:	learn: 0.0020373	total: 11m 22s	remaining: 5m 53s
6912:	learn: 0.0015127	total: 11m 22s	remaining: 5m 4s
6791:	learn: 0.0015425	total: 11m 22s	remaining: 5m 22s
6786:	learn: 0.0015820	total: 11m 22s	remaining: 5m 23s
6284:	learn: 0.0014719	total: 11m 22s	remaining: 6m 43s
6913:	learn: 0.0015127	total: 11m 22s	remaining: 5m 4s
6792:	learn: 0.0015426	total: 11m 22s	remaining: 5m 22s
6590:	learn: 0.0020366	total: 11m 22s	remaining: 5m 53s
6787:	learn: 0.0015820	total: 11m 22s	remaining: 5m 23s
6285:	learn: 0.0014716	total: 11m 22s	remaining: 6m 43s
6793:	learn: 0.0015426	total: 11m 22s	remaining: 5m 22s
6591:	learn: 0.0020366	total: 11m 22s	remaining: 5m 53s
6914:	learn: 0.0015127	total: 11m 22s	remaining: 5m 4s
6788:	learn: 0.0015820	total: 11m 22s	remaining: 5m 22s
6286:	learn: 0.0014712	total: 11m 22s	remaining: 6m 43s
6915:	learn: 0.0015127	total: 11m 22s	remaining: 5m 4s
6592:	learn: 0.0020366	total: 11m 22s	remaining: 5m 52s
6794:	learn: 0.0015425	total: 11m 22s	remaining: 5m 22s
6789:	learn: 0.0015820	total: 11m 22s	remaining: 5m 22s
6287:	learn: 0.0014708	total: 11m 23s	remaining: 6m 43s
6790:	learn: 0.0015820	total: 11m 23s	remaining: 5m 22s
6916:	learn: 0.0015127	total: 11m 22s	remaining: 5m 4s
6593:	learn: 0.0020366	total: 11m 23s	remaining: 5m 52s
6795:	learn: 0.0015426	total: 11m 22s	remaining: 5m 21s
6288:	learn: 0.0014703	total: 11m 23s	remaining: 6m 43s
6917:	learn: 0.0015127	total: 11m 23s	remaining: 5m 4s
6791:	learn: 0.0015820	total: 11m 23s	remaining: 5m 22s
6594:	learn: 0.0020366	total: 11m 23s	remaining: 5m 52s
6289:	learn: 0.0014703	total: 11m 23s	remaining: 6m 42s
6796:	learn: 0.0015423	total: 11m 23s	remaining: 5m 21s
6792:	learn: 0.0015820	total: 11m 23s	remaining: 5m 22s
6918:	learn: 0.0015127	total: 11m 23s	remaining: 5m 4s
6595:	learn: 0.0020366	total: 11m 23s	remaining: 5m 52s
6290:	learn: 0.0014700	total: 11m 23s	remaining: 6m 42s
6797:	learn: 0.0015423	total: 11m 23s	remaining: 5m 21s
6793:	learn: 0.0015820	total: 11m 23s	remaining: 5m 22s
6919:	learn: 0.0015127	total: 11m 23s	remaining: 5m 4s
6291:	learn: 0.0014696	total: 11m 23s	remaining: 6m 42s
6596:	learn: 0.0020366	total: 11m 23s	remaining: 5m 52s
6798:	learn: 0.0015423	total: 11m 23s	remaining: 5m 21s
6794:	learn: 0.0015820	total: 11m 23s	remaining: 5m 22s
6597:	learn: 0.0020366	total: 11m 23s	remaining: 5m 52s
6920:	learn: 0.0015127	total: 11m 23s	remaining: 5m 4s
6292:	learn: 0.0014696	total: 11m 23s	remaining: 6m 42s
6799:	learn: 0.0015423	total: 11m 23s	remaining: 5m 21s
6598:	learn: 0.0020366	total: 11m 23s	remaining: 5m 52s
6795:	learn: 0.0015820	total: 11m 23s	remaining: 5m 22s
6921:	learn: 0.0015127	total: 11m 23s	remaining: 5m 3s
6293:	learn: 0.0014693	total: 11m 23s	remaining: 6m 42s
6796:	learn: 0.0015820	total: 11m 23s	remaining: 5m 22s
6800:	learn: 0.0015423	total: 11m 23s	remaining: 5m 21s
6599:	learn: 0.0020360	total: 11m 23s	remaining: 5m 52s
6922:	learn: 0.0015127	total: 11m 23s	remaining: 5m 3s
6294:	learn: 0.0014693	total: 11m 23s	remaining: 6m 42s
6600:	learn: 0.0020360	total: 11m 23s	remaining: 5m 52s
6801:	learn: 0.0015423	total: 11m 23s	remaining: 5m 21s
6797:	learn: 0.0015820	total: 11m 23s	remaining: 5m 22s
6295:	learn: 0.0014693	total: 11m 23s	remaining: 6m 42s
6923:	learn: 0.0015123	total: 11m 23s	remaining: 5m 3s
6601:	learn: 0.0020360	total: 11m 23s	remaining: 5m 51s
6802:	learn: 0.0015423	total: 11m 23s	remaining: 5m 21s
6798:	learn: 0.0015820	total: 11m 23s	remaining: 5m 21s
6924:	learn: 0.0015123	total: 11m 23s	remaining: 5m 3s
6296:	learn: 0.0014689	total: 11m 23s	remaining: 6m 42s
6602:	learn: 0.0020360	total: 11m 23s	remaining: 5m 51s
6799:	learn: 0.0015820	total: 11m 23s	remaining: 5m 21s
6803:	learn: 0.0015423	total: 11m 23s	remaining: 5m 21s
6297:	learn: 0.0014684	total: 11m 23s	remaining: 6m 42s
6603:	learn: 0.0020360	total: 11m 24s	remaining: 5m 51s
6925:	learn: 0.0015123	total: 11m 23s	remaining: 5m 3s
6800:	learn: 0.0015820	total: 11m 24s	remaining: 5m 21s
6804:	learn: 0.0015423	total: 11m 23s	remaining: 5m 21s
6298:	learn: 0.0014684	total: 11m 24s	remaining: 6m 41s
6604:	learn: 0.0020360	total: 11m 24s	remaining: 5m 51s
6926:	learn: 0.0015123	total: 11m 24s	remaining: 5m 3s
6801:	learn: 0.0015820	total: 11m 24s	remaining: 5m 21s
6805:	learn: 0.0015423	total: 11m 23s	remaining: 5m 20s
6605:	learn: 0.0020360	total: 11m 24s	remaining: 5m 51s
6299:	learn: 0.0014680	total: 11m 24s	remaining: 6m 41s
6927:	learn: 0.0015123	total: 11m 24s	remaining: 5m 3s
6802:	learn: 0.0015820	total: 11m 24s	remaining: 5m 21s
6806:	learn: 0.0015422	total: 11m 24s	remaining: 5m 20s
6606:	learn: 0.0020360	total: 11m 24s	remaining: 5m 51s
6928:	learn: 0.0015123	total: 11m 24s	remaining: 5m 3s
6803:	learn: 0.0015820	total: 11m 24s	remaining: 5m 21s
6300:	learn: 0.0014681	total: 11m 24s	remaining: 6m 41s
6807:	learn: 0.0015423	total: 11m 24s	remaining: 5m 20s
6607:	learn: 0.0020360	total: 11m 24s	remaining: 5m 51s
6929:	learn: 0.0015123	total: 11m 24s	remaining: 5m 3s
6804:	learn: 0.0015820	total: 11m 24s	remaining: 5m 21s
6301:	learn: 0.0014677	total: 11m 24s	remaining: 6m 41s
6608:	learn: 0.0020352	total: 11m 24s	remaining: 5m 51s
6808:	learn: 0.0015422	total: 11m 24s	remaining: 5m 20s
6805:	learn: 0.0015820	total: 11m 24s	remaining: 5m 21s
6930:	learn: 0.0015123	total: 11m 24s	remaining: 5m 3s
6609:	learn: 0.0020352	total: 11m 24s	remaining: 5m 51s
6302:	learn: 0.0014677	total: 11m 24s	remaining: 6m 41s
6809:	learn: 0.0015422	total: 11m 24s	remaining: 5m 20s
6806:	learn: 0.0015820	total: 11m 24s	remaining: 5m 21s
6610:	learn: 0.0020352	total: 11m 24s	remaining: 5m 50s
6931:	learn: 0.0015123	total: 11m 24s	remaining: 5m 2s
6303:	learn: 0.0014673	total: 11m 24s	remaining: 6m 41s
6810:	learn: 0.0015422	total: 11m 24s	remaining: 5m 20s
6807:	learn: 0.0015820	total: 11m 24s	remaining: 5m 21s
6932:	learn: 0.0015119	total: 11m 24s	remaining: 5m 2s
6611:	learn: 0.0020352	total: 11m 24s	remaining: 5m 50s
6811:	learn: 0.0015418	total: 11m 24s	remaining: 5m 20s
6304:	learn: 0.0014670	total: 11m 24s	remaining: 6m 41s
6808:	learn: 0.0015820	total: 11m 24s	remaining: 5m 20s
6933:	learn: 0.0015119	total: 11m 24s	remaining: 5m 2s
6612:	learn: 0.0020352	total: 11m 24s	remaining: 5m 50s
6812:	learn: 0.0015415	total: 11m 24s	remaining: 5m 20s
6809:	learn: 0.0015820	total: 11m 24s	remaining: 5m 20s
6305:	learn: 0.0014670	total: 11m 24s	remaining: 6m 41s
6934:	learn: 0.0015115	total: 11m 24s	remaining: 5m 2s
6613:	learn: 0.0020352	total: 11m 24s	remaining: 5m 50s
6813:	learn: 0.0015415	total: 11m 24s	remaining: 5m 20s
6935:	learn: 0.0015114	total: 11m 24s	remaining: 5m 2s
6810:	learn: 0.0015820	total: 11m 24s	remaining: 5m 20s
6306:	learn: 0.0014667	total: 11m 25s	remaining: 6m 41s
6614:	learn: 0.0020352	total: 11m 25s	remaining: 5m 50s
6936:	learn: 0.0015114	total: 11m 24s	remaining: 5m 2s
6814:	learn: 0.0015415	total: 11m 24s	remaining: 5m 20s
6811:	learn: 0.0015820	total: 11m 25s	remaining: 5m 20s
6937:	learn: 0.0015111	total: 11m 25s	remaining: 5m 2s
6307:	learn: 0.0014666	total: 11m 25s	remaining: 6m 41s
6615:	learn: 0.0020352	total: 11m 25s	remaining: 5m 50s
6815:	learn: 0.0015415	total: 11m 24s	remaining: 5m 19s
6812:	learn: 0.0015820	total: 11m 25s	remaining: 5m 20s
6938:	learn: 0.0015108	total: 11m 25s	remaining: 5m 2s
6616:	learn: 0.0020352	total: 11m 25s	remaining: 5m 50s
6308:	learn: 0.0014661	total: 11m 25s	remaining: 6m 40s
6816:	learn: 0.0015415	total: 11m 25s	remaining: 5m 19s
6813:	learn: 0.0015820	total: 11m 25s	remaining: 5m 20s
6939:	learn: 0.0015108	total: 11m 25s	remaining: 5m 2s
6309:	learn: 0.0014659	total: 11m 25s	remaining: 6m 40s
6617:	learn: 0.0020352	total: 11m 25s	remaining: 5m 50s
6817:	learn: 0.0015415	total: 11m 25s	remaining: 5m 19s
6940:	learn: 0.0015108	total: 11m 25s	remaining: 5m 2s
6814:	learn: 0.0015820	total: 11m 25s	remaining: 5m 20s
6310:	learn: 0.0014658	total: 11m 25s	remaining: 6m 40s
6618:	learn: 0.0020352	total: 11m 25s	remaining: 5m 50s

6818:	learn: 0.0015415	total: 11m 25s	remaining: 5m 19s
6311:	learn: 0.0014658	total: 11m 25s	remaining: 6m 40s
6619:	learn: 0.0020352	total: 11m 25s	remaining: 5m 50s
6942:	learn: 0.0015108	total: 11m 25s	remaining: 5m 1s
6816:	learn: 0.0015820	total: 11m 25s	remaining: 5m 20s
6819:	learn: 0.0015415	total: 11m 25s	remaining: 5m 19s
6312:	learn: 0.0014656	total: 11m 25s	remaining: 6m 40s
6620:	learn: 0.0020352	total: 11m 25s	remaining: 5m 49s
6943:	learn: 0.0015103	total: 11m 25s	remaining: 5m 1s
6820:	learn: 0.0015415	total: 11m 25s	remaining: 5m 19s
6817:	learn: 0.0015820	total: 11m 25s	remaining: 5m 20s
6313:	learn: 0.0014653	total: 11m 25s	remaining: 6m 40s
6621:	learn: 0.0020352	total: 11m 25s	remaining: 5m 49s
6944:	learn: 0.0015098	total: 11m 25s	remaining: 5m 1s
6818:	learn: 0.0015820	total: 11m 25s	remaining: 5m 19s
6821:	learn: 0.0015410	total: 11m 25s	remaining: 5m 19s
6314:	learn: 0.0014648	total: 11m 25s	remaining: 6m 40s
6622:	learn: 0.0020352	total: 11m 25s	remaining: 5m 49s
6819:	learn: 0.0015815	total: 11m 25s	remaining: 5m 19s
6945:	learn: 0.0015097	total: 11m 25s	remaining: 5m 1s
6822:	learn: 0.0015410	total: 11m 25s	remaining: 5m 19s
6315:	learn: 0.0014644	total: 11m 25s	remaining: 6m 40s
6623:	learn: 0.0020352	total: 11m 25s	remaining: 5m 49s
6820:	learn: 0.0015811	total: 11m 25s	remaining: 5m 19s
6946:	learn: 0.0015097	total: 11m 25s	remaining: 5m 1s
6823:	learn: 0.0015410	total: 11m 25s	remaining: 5m 19s
6316:	learn: 0.0014640	total: 11m 26s	remaining: 6m 39s
6624:	learn: 0.0020352	total: 11m 26s	remaining: 5m 49s
6821:	learn: 0.0015811	total: 11m 26s	remaining: 5m 19s
6625:	learn: 0.0020352	total: 11m 26s	remaining: 5m 49s
6947:	learn: 0.0015097	total: 11m 26s	remaining: 5m 1s
6824:	learn: 0.0015410	total: 11m 25s	remaining: 5m 19s
6317:	learn: 0.0014640	total: 11m 26s	remaining: 6m 39s
6626:	learn: 0.0020352	total: 11m 26s	remaining: 5m 49s
6822:	learn: 0.0015806	total: 11m 26s	remaining: 5m 19s
6948:	learn: 0.0015097	total: 11m 26s	remaining: 5m 1s
6318:	learn: 0.0014637	total: 11m 26s	remaining: 6m 39s
6825:	learn: 0.0015410	total: 11m 26s	remaining: 5m 18s
6627:	learn: 0.0020352	total: 11m 26s	remaining: 5m 49s
6823:	learn: 0.0015800	total: 11m 26s	remaining: 5m 19s
6949:	learn: 0.0015093	total: 11m 26s	remaining: 5m 1s
6826:	learn: 0.0015410	total: 11m 26s	remaining: 5m 18s
6319:	learn: 0.0014637	total: 11m 26s	remaining: 6m 39s
6628:	learn: 0.0020352	total: 11m 26s	remaining: 5m 49s
6824:	learn: 0.0015800	total: 11m 26s	remaining: 5m 19s
6950:	learn: 0.0015093	total: 11m 26s	remaining: 5m 1s
6320:	learn: 0.0014633	total: 11m 26s	remaining: 6m 39s
6827:	learn: 0.0015410	total: 11m 26s	remaining: 5m 18s
6629:	learn: 0.0020352	total: 11m 26s	remaining: 5m 48s
6825:	learn: 0.0015800	total: 11m 26s	remaining: 5m 19s
6951:	learn: 0.0015093	total: 11m 26s	remaining: 5m
6321:	learn: 0.0014633	total: 11m 26s	remaining: 6m 39s
6630:	learn: 0.0020352	total: 11m 26s	remaining: 5m 48s
6828:	learn: 0.0015410	total: 11m 26s	remaining: 5m 18s
6952:	learn: 0.0015093	total: 11m 26s	remaining: 5m
6826:	learn: 0.0015800	total: 11m 26s	remaining: 5m 19s
6322:	learn: 0.0014633	total: 11m 26s	remaining: 6m 39s
6829:	learn: 0.0015410	total: 11m 26s	remaining: 5m 18s
6953:	learn: 0.0015093	total: 11m 26s	remaining: 5m
6827:	learn: 0.0015800	total: 11m 26s	remaining: 5m 19s
6631:	learn: 0.0020352	total: 11m 26s	remaining: 5m 48s
6323:	learn: 0.0014630	total: 11m 26s	remaining: 6m 39s
6828:	learn: 0.0015797	total: 11m 26s	remaining: 5m 18s
6954:	learn: 0.0015093	total: 11m 26s	remaining: 5m
6830:	learn: 0.0015410	total: 11m 26s	remaining: 5m 18s
6632:	learn: 0.0020352	total: 11m 26s	remaining: 5m 48s
6324:	learn: 0.0014630	total: 11m 26s	remaining: 6m 39s
6829:	learn: 0.0015792	total: 11m 26s	remaining: 5m 18s
6955:	learn: 0.0015093	total: 11m 26s	remaining: 5m
6633:	learn: 0.0020351	total: 11m 26s	remaining: 5m 48s
6325:	learn: 0.0014626	total: 11m 26s	remaining: 6m 38s
6831:	learn: 0.0015410	total: 11m 26s	remaining: 5m 18s
6956:	learn: 0.0015093	total: 11m 26s	remaining: 5m
6830:	learn: 0.0015788	total: 11m 26s	remaining: 5m 18s
6634:	learn: 0.0020351	total: 11m 27s	remaining: 5m 48s
6326:	learn: 0.0014626	total: 11m 27s	remaining: 6m 38s
6832:	learn: 0.0015410	total: 11m 26s	remaining: 5m 18s
6957:	learn: 0.0015093	total: 11m 26s	remaining: 5m
6635:	learn: 0.0020352	total: 11m 27s	remaining: 5m 48s
6831:	learn: 0.0015787	total: 11m 27s	remaining: 5m 18s
6327:	learn: 0.0014625	total: 11m 27s	remaining: 6m 38s
6833:	learn: 0.0015410	total: 11m 26s	remaining: 5m 18s
6636:	learn: 0.0020352	total: 11m 27s	remaining: 5m 48s
6958:	learn: 0.0015088	total: 11m 27s	remaining: 5m
6832:	learn: 0.0015782	total: 11m 27s	remaining: 5m 18s
6834:	learn: 0.0015410	total: 11m 26s	remaining: 5m 18s
6328:	learn: 0.0014623	total: 11m 27s	remaining: 6m 38s
6637:	learn: 0.0020352	total: 11m 27s	remaining: 5m 48s
6959:	learn: 0.0015088	total: 11m 27s	remaining: 5m
6833:	learn: 0.0015776	total: 11m 27s	remaining: 5m 18s
6835:	learn: 0.0015410	total: 11m 27s	remaining: 5m 18s
6960:	learn: 0.0015087	total: 11m 27s	remaining: 5m
6638:	learn: 0.0020352	total: 11m 27s	remaining: 5m 48s
6834:	learn: 0.0015771	total: 11m 27s	remaining: 5m 18s
6329:	learn: 0.0014619	total: 11m 27s	remaining: 6m 38s
6836:	learn: 0.0015410	total: 11m 27s	remaining: 5m 17s
6835:	learn: 0.0015772	total: 11m 27s	remaining: 5m 18s
6961:	learn: 0.0015087	total: 11m 27s	remaining: 4m 59s
6639:	learn: 0.0020352	total: 11m 27s	remaining: 5m 47s
6330:	learn: 0.0014619	total: 11m 27s	remaining: 6m 38s
6837:	learn: 0.0015410	total: 11m 27s	remaining: 5m 17s
6962:	learn: 0.0015087	total: 11m 27s	remaining: 4m 59s
6836:	learn: 0.0015767	total: 11m 27s	remaining: 5m 18s
6640:	learn: 0.0020352	total: 11m 27s	remaining: 5m 47s
6331:	learn: 0.0014619	total: 11m 27s	remaining: 6m 38s
6838:	learn: 0.0015406	total: 11m 27s	remaining: 5m 17s
6641:	learn: 0.0020352	total: 11m 27s	remaining: 5m 47s
6963:	learn: 0.0015087	total: 11m 27s	remaining: 4m 59s
6332:	learn: 0.0014615	total: 11m 27s	remaining: 6m 38s
6837:	learn: 0.0015767	total: 11m 27s	remaining: 5m 17s
6839:	learn: 0.0015406	total: 11m 27s	remaining: 5m 17s
6642:	learn: 0.0020352	total: 11m 27s	remaining: 5m 47s
6333:	learn: 0.0014612	total: 11m 27s	remaining: 6m 38s
6838:	learn: 0.0015767	total: 11m 27s	remaining: 5m 17s
6964:	learn: 0.0015085	total: 11m 27s	remaining: 4m 59s
6840:	learn: 0.0015406	total: 11m 27s	remaining: 5m 17s
6643:	learn: 0.0020352	total: 11m 27s	remaining: 5m 47s
6839:	learn: 0.0015767	total: 11m 27s	remaining: 5m 17s
6965:	learn: 0.0015085	total: 11m 27s	remaining: 4m 59s
6841:	learn: 0.0015403	total: 11m 27s	remaining: 5m 17s
6334:	learn: 0.0014612	total: 11m 27s	remaining: 6m 37s
6644:	learn: 0.0020351	total: 11m 27s	remaining: 5m 47s
6842:	learn: 0.0015402	total: 11m 27s	remaining: 5m 17s
6966:	learn: 0.0015082	total: 11m 27s	remaining: 4m 59s
6840:	learn: 0.0015767	total: 11m 27s	remaining: 5m 17s
6335:	learn: 0.0014608	total: 11m 28s	remaining: 6m 37s
6645:	learn: 0.0020351	total: 11m 28s	remaining: 5m 47s
6336:	learn: 0.0014609	total: 11m 28s	remaining: 6m 37s
6841:	learn: 0.0015765	total: 11m 28s	remaining: 5m 17s
6843:	learn: 0.0015402	total: 11m 27s	remaining: 5m 17s
6967:	learn: 0.0015078	total: 11m 28s	remaining: 4m 59s
6646:	learn: 0.0020351	total: 11m 28s	remaining: 5m 47s
6842:	learn: 0.0015765	total: 11m 28s	remaining: 5m 17s
6844:	learn: 0.0015402	total: 11m 27s	remaining: 5m 17s
6647:	learn: 0.0020351	total: 11m 28s	remaining: 5m 47s
6337:	learn: 0.0014604	total: 11m 28s	remaining: 6m 37s
6968:	learn: 0.0015073	total: 11m 28s	remaining: 4m 59s
6843:	learn: 0.0015764	total: 11m 28s	remaining: 5m 17s
6845:	learn: 0.0015399	total: 11m 28s	remaining: 5m 17s
6969:	learn: 0.0015073	total: 11m 28s	remaining: 4m 59s
6648:	learn: 0.0020351	total: 11m 28s	remaining: 5m 46s
6338:	learn: 0.0014601	total: 11m 28s	remaining: 6m 37s
6844:	learn: 0.0015761	total: 11m 28s	remaining: 5m 17s
6846:	learn: 0.0015399	total: 11m 28s	remaining: 5m 16s
6970:	learn: 0.0015069	total: 11m 28s	remaining: 4m 59s
l: 11m 19s	remaining: 5m 56s
6756:	learn: 0.0015855	total: 11m 19s	remaining: 5m 26s
 otal: 11m 7!      ing: 56339:	learn: 0.0014601	total: 11m 28s	remaining: 6m 37s
6649:	learn: 0.0020352	total: 11m 28s	remaining: 5m 46s
6847:	learn: 0.0015399	total: 11m 28s	remaining: 5m 16s
6845:	learn: 0.0015759	total: 11m 28s	remaining: 5m 17s
6971:	learn: 0.0015069	total: 11m 28s	remaining: 4m 58s
6650:	learn: 0.0020351	total: 11m 28s	remaining: 5m 46s
6340:	learn: 0.0014601	total: 11m 28s	remaining: 6m 37s
6848:	learn: 0.0015399	total: 11m 28s	remaining: 5m 16s
6846:	learn: 0.0015759	total: 11m 28s	remaining: 5m 17s
6972:	learn: 0.0015065	total: 11m 28s	remaining: 4m 58s
6651:	learn: 0.0020352	total: 11m 28s	remaining: 5m 46s
6341:	learn: 0.0014598	total: 11m 28s	remaining: 6m 37s
6973:	learn: 0.0015060	total: 11m 28s	remaining: 4m 58s
6849:	learn: 0.0015399	total: 11m 28s	remaining: 5m 16s
6847:	learn: 0.0015759	total: 11m 28s	remaining: 5m 16s
6652:	learn: 0.0020351	total: 11m 28s	remaining: 5m 46s
6342:	learn: 0.0014594	total: 11m 28s	remaining: 6m 37s
6848:	learn: 0.0015759	total: 11m 28s	remaining: 5m 16s
6974:	learn: 0.0015055	total: 11m 28s	remaining: 4m 58s
6850:	learn: 0.0015393	total: 11m 28s	remaining: 5m 16s
6343:	learn: 0.0014594	total: 11m 28s	remaining: 6m 36s
6653:	learn: 0.0020351	total: 11m 28s	remaining: 5m 46s
6849:	learn: 0.0015759	total: 11m 28s	remaining: 5m 16s
6975:	learn: 0.0015051	total: 11m 28s	remaining: 4m 58s
6851:	learn: 0.0015389	total: 11m 28s	remaining: 5m 16s
6850:	learn: 0.0015754	total: 11m 28s	remaining: 5m 16s
6344:	learn: 0.0014590	total: 11m 28s	remaining: 6m 36s
6654:	learn: 0.0020351	total: 11m 29s	remaining: 5m 46s
6976:	learn: 0.0015051	total: 11m 28s	remaining: 4m 58s
6852:	learn: 0.0015389	total: 11m 28s	remaining: 5m 16s
6851:	learn: 0.0015752	total: 11m 29s	remaining: 5m 16s
6977:	learn: 0.0015051	total: 11m 28s	remaining: 4m 58s
6345:	learn: 0.0014587	total: 11m 29s	remaining: 6m 36s
6655:	learn: 0.0020351	total: 11m 29s	remaining: 5m 46s
6853:	learn: 0.0015389	total: 11m 28s	remaining: 5m 16s
6852:	learn: 0.0015750	total: 11m 29s	remaining: 5m 16s
6978:	learn: 0.0015050	total: 11m 29s	remaining: 4m 58s
6656:	learn: 0.0020351	total: 11m 29s	remaining: 5m 46s
6346:	learn: 0.0014583	total: 11m 29s	remaining: 6m 36s
6854:	learn: 0.0015388	total: 11m 28s	remaining: 5m 16s
6853:	learn: 0.0015750	total: 11m 29s	remaining: 5m 16s
6347:	learn: 0.0014583	total: 11m 29s	remaining: 6m 36s
6979:	learn: 0.0015051	total: 11m 29s	remaining: 4m 58s
6657:	learn: 0.0020351	total: 11m 29s	remaining: 5m 46s
6855:	learn: 0.0015388	total: 11m 29s	remaining: 5m 15s
6854:	learn: 0.0015749	total: 11m 29s	remaining: 5m 16s
6980:	learn: 0.0015050	total: 11m 29s	remaining: 4m 58s
6658:	learn: 0.0020351	total: 11m 29s	remaining: 5m 45s
6856:	learn: 0.0015388	total: 11m 29s	remaining: 5m 15s
6348:	learn: 0.0014579	total: 11m 29s	remaining: 6m 36s
6855:	learn: 0.0015749	total: 11m 29s	remaining: 5m 16s
6981:	learn: 0.0015050	total: 11m 29s	remaining: 4m 57s
6659:	learn: 0.0020351	total: 11m 29s	remaining: 5m 45s
6349:	learn: 0.0014575	total: 11m 29s	remaining: 6m 36s
6857:	learn: 0.0015387	total: 11m 29s	remaining: 5m 15s
6982:	learn: 0.0015047	total: 11m 29s	remaining: 4m 57s
6856:	learn: 0.0015749	total: 11m 29s	remaining: 5m 16s
6660:	learn: 0.0020351	total: 11m 29s	remaining: 5m 45s
6350:	learn: 0.0014573	total: 11m 29s	remaining: 6m 36s
6983:	learn: 0.0015042	total: 11m 29s	remaining: 4m 57s
6858:	learn: 0.0015387	total: 11m 29s	remaining: 5m 15s
6857:	learn: 0.0015749	total: 11m 29s	remaining: 5m 15s
6351:	learn: 0.0014569	total: 11m 29s	remaining: 6m 36s
6661:	learn: 0.0020351	total: 11m 29s	remaining: 5m 45s
6984:	learn: 0.0015038	total: 11m 29s	remaining: 4m 57s
6859:	learn: 0.0015387	total: 11m 29s	remaining: 5m 15s
6858:	learn: 0.0015749	total: 11m 29s	remaining: 5m 15s
6662:	learn: 0.0020351	total: 11m 29s	remaining: 5m 45s
6985:	learn: 0.0015038	total: 11m 29s	remaining: 4m 57s
6860:	learn: 0.0015387	total: 11m 29s	remaining: 5m 15s
6352:	learn: 0.0014566	total: 11m 29s	remaining: 6m 36s
6859:	learn: 0.0015749	total: 11m 29s	remaining: 5m 15s
6986:	learn: 0.0015034	total: 11m 29s	remaining: 4m 57s
6663:	learn: 0.0020351	total: 11m 29s	remaining: 5m 45s
6861:	learn: 0.0015383	total: 11m 29s	remaining: 5m 15s
6353:	learn: 0.0014564	total: 11m 29s	remaining: 6m 35s
6860:	learn: 0.0015749	total: 11m 29s	remaining: 5m 15s
6987:	learn: 0.0015034	total: 11m 29s	remaining: 4m 57s
6664:	learn: 0.0020351	total: 11m 30s	remaining: 5m 45s
6862:	learn: 0.0015379	total: 11m 29s	remaining: 5m 15s
6988:	learn: 0.0015034	total: 11m 29s	remaining: 4m 57s
6861:	learn: 0.0015749	total: 11m 30s	remaining: 5m 15s
6354:	learn: 0.0014564	total: 11m 30s	remaining: 6m 35s
6863:	learn: 0.0015379	total: 11m 29s	remaining: 5m 15s
6665:	learn: 0.0020351	total: 11m 30s	remaining: 5m 45s
6862:	learn: 0.0015745	total: 11m 30s	remaining: 5m 15s
6989:	learn: 0.0015034	total: 11m 30s	remaining: 4m 57s
6864:	learn: 0.0015379	total: 11m 29s	remaining: 5m 15s
6666:	learn: 0.0020351	total: 11m 30s	remaining: 5m 45s
6355:	learn: 0.0014561	total: 11m 30s	remaining: 6m 35s
6863:	learn: 0.0015745	total: 11m 30s	remaining: 5m 15s
6990:	learn: 0.0015034	total: 11m 30s	remaining: 4m 57s
6865:	learn: 0.0015379	total: 11m 30s	remaining: 5m 14s
6667:	learn: 0.0020351	total: 11m 30s	remaining: 5m 44s
6356:	learn: 0.0014558	total: 11m 30s	remaining: 6m 35s
6864:	learn: 0.0015745	total: 11m 30s	remaining: 5m 15s
6866:	learn: 0.0015379	total: 11m 30s	remaining: 5m 14s
6991:	learn: 0.0015034	total: 11m 30s	remaining: 4m 56s
6668:	learn: 0.0020351	total: 11m 30s	remaining: 5m 44s
6357:	learn: 0.0014558	total: 11m 30s	remaining: 6m 35s
6992:	learn: 0.0015034	total: 11m 30s	remaining: 4m 56s
6865:	learn: 0.0015745	total: 11m 30s	remaining: 5m 15s
6867:	learn: 0.0015379	total: 11m 30s	remaining: 5m 14s
6669:	learn: 0.0020351	total: 11m 30s	remaining: 5m 44s
6358:	learn: 0.0014554	total: 11m 30s	remaining: 6m 35s
6993:	learn: 0.0015034	total: 11m 30s	remaining: 4m 56s
6866:	learn: 0.0015740	total: 11m 30s	remaining: 5m 15s
6670:	learn: 0.0020351	total: 11m 30s	remaining: 5m 44s
6868:	learn: 0.0015379	total: 11m 30s	remaining: 5m 14s
6994:	learn: 0.0015034	total: 11m 30s	remaining: 4m 56s
6359:	learn: 0.0014551	total: 11m 30s	remaining: 6m 35s
6867:	learn: 0.0015740	total: 11m 30s	remaining: 5m 14s
6671:	learn: 0.0020351	total: 11m 30s	remaining: 5m 44s
6869:	learn: 0.0015375	total: 11m 30s	remaining: 5m 14s
6995:	learn: 0.0015034	total: 11m 30s	remaining: 4m 56s
6868:	learn: 0.0015740	total: 11m 30s	remaining: 5m 14s
6360:	learn: 0.0014551	total: 11m 30s	remaining: 6m 35s
6672:	learn: 0.0020351	total: 11m 30s	remaining: 5m 44s
6996:	learn: 0.0015034	total: 11m 30s	remaining: 4m 56s
6870:	learn: 0.0015371	total: 11m 30s	remaining: 5m 14s
6361:	learn: 0.0014549	total: 11m 30s	remaining: 6m 35s
6673:	learn: 0.0020351	total: 11m 30s	remaining: 5m 44s
6869:	learn: 0.0015734	total: 11m 30s	remaining: 5m 14s
6997:	learn: 0.0015034	total: 11m 30s	remaining: 4m 56s
6871:	learn: 0.0015371	total: 11m 30s	remaining: 5m 14s
6674:	learn: 0.0020351	total: 11m 30s	remaining: 5m 44s
6362:	learn: 0.0014549	total: 11m 30s	remaining: 6m 34s
6998:	learn: 0.0015032	total: 11m 30s	remaining: 4m 56s
6870:	learn: 0.0015728	total: 11m 30s	remaining: 5m 14s
6872:	learn: 0.0015369	total: 11m 30s	remaining: 5m 14s
6675:	learn: 0.0020351	total: 11m 31s	remaining: 5m 44s
6871:	learn: 0.0015723	total: 11m 31s	remaining: 5m 14s
6999:	learn: 0.0015032	total: 11m 31s	remaining: 4m 56s
6363:	learn: 0.0014546	total: 11m 31s	remaining: 6m 34s
6676:	learn: 0.0020351	total: 11m 31s	remaining: 5m 43s
6873:	learn: 0.0015369	total: 11m 30s	remaining: 5m 14s
7000:	learn: 0.0015032	total: 11m 31s	remaining: 4m 56s
6677:	learn: 0.0020351	total: 11m 31s	remaining: 5m 43s
6364:	learn: 0.0014543	total: 11m 31s	remaining: 6m 34s
6872:	learn: 0.0015717	total: 11m 31s	remaining: 5m 14s
6874:	learn: 0.0015369	total: 11m 31s	remaining: 5m 14s
7001:	learn: 0.0015032	total: 11m 31s	remaining: 4m 55s
6365:	learn: 0.0014540	total: 11m 31s	remaining: 6m 34s
6873:	learn: 0.0015713	total: 11m 31s	remaining: 5m 14s
6678:	learn: 0.0020344	total: 11m 31s	remaining: 5m 43s
6875:	learn: 0.0015369	total: 11m 31s	remaining: 5m 14s

6366:	learn: 0.0014536	total: 11m 31s	remaining: 6m 34s
6679:	learn: 0.0020344	total: 11m 31s	remaining: 5m 43s
6876:	learn: 0.0015369	total: 11m 31s	remaining: 5m 13s
6875:	learn: 0.0015705	total: 11m 31s	remaining: 5m 14s
6367:	learn: 0.0014533	total: 11m 31s	remaining: 6m 34s
7003:	learn: 0.0015032	total: 11m 31s	remaining: 4m 55s
6877:	learn: 0.0015369	total: 11m 31s	remaining: 5m 13s
6680:	learn: 0.0020344	total: 11m 31s	remaining: 5m 43s
6368:	learn: 0.0014533	total: 11m 31s	remaining: 6m 34s
6876:	learn: 0.0015705	total: 11m 31s	remaining: 5m 14s
6878:	learn: 0.0015369	total: 11m 31s	remaining: 5m 13s
7004:	learn: 0.0015032	total: 11m 31s	remaining: 4m 55s
6681:	learn: 0.0020344	total: 11m 31s	remaining: 5m 43s
6369:	learn: 0.0014529	total: 11m 31s	remaining: 6m 34s
6877:	learn: 0.0015705	total: 11m 31s	remaining: 5m 13s
6879:	learn: 0.0015369	total: 11m 31s	remaining: 5m 13s
7005:	learn: 0.0015032	total: 11m 31s	remaining: 4m 55s
6682:	learn: 0.0020344	total: 11m 31s	remaining: 5m 43s
6370:	learn: 0.0014525	total: 11m 31s	remaining: 6m 34s
6878:	learn: 0.0015702	total: 11m 31s	remaining: 5m 13s
6880:	learn: 0.0015369	total: 11m 31s	remaining: 5m 13s
7006:	learn: 0.0015032	total: 11m 31s	remaining: 4m 55s
6683:	learn: 0.0020344	total: 11m 31s	remaining: 5m 43s
6371:	learn: 0.0014522	total: 11m 31s	remaining: 6m 33s
6879:	learn: 0.0015702	total: 11m 31s	remaining: 5m 13s
7007:	learn: 0.0015032	total: 11m 31s	remaining: 4m 55s
6881:	learn: 0.0015369	total: 11m 31s	remaining: 5m 13s
6684:	learn: 0.0020344	total: 11m 31s	remaining: 5m 43s
6372:	learn: 0.0014519	total: 11m 31s	remaining: 6m 33s
6880:	learn: 0.0015697	total: 11m 31s	remaining: 5m 13s
7008:	learn: 0.0015032	total: 11m 31s	remaining: 4m 55s
6882:	learn: 0.0015369	total: 11m 31s	remaining: 5m 13s
6373:	learn: 0.0014516	total: 11m 32s	remaining: 6m 33s
6881:	learn: 0.0015692	total: 11m 32s	remaining: 5m 13s
7009:	learn: 0.0015029	total: 11m 32s	remaining: 4m 55s
6883:	learn: 0.0015369	total: 11m 31s	remaining: 5m 13s
6685:	learn: 0.0020344	total: 11m 32s	remaining: 5m 43s
6882:	learn: 0.0015688	total: 11m 32s	remaining: 5m 13s
7010:	learn: 0.0015029	total: 11m 32s	remaining: 4m 55s
6374:	learn: 0.0014515	total: 11m 32s	remaining: 6m 33s
6884:	learn: 0.0015369	total: 11m 31s	remaining: 5m 13s
6686:	learn: 0.0020344	total: 11m 32s	remaining: 5m 42s
6883:	learn: 0.0015683	total: 11m 32s	remaining: 5m 13s
7011:	learn: 0.0015029	total: 11m 32s	remaining: 4m 54s
6884:	learn: 0.0015682	total: 11m 32s	remaining: 5m 13s
6885:	learn: 0.0015369	total: 11m 32s	remaining: 5m 12s
6375:	learn: 0.0014514	total: 11m 32s	remaining: 6m 33s
6687:	learn: 0.0020344	total: 11m 32s	remaining: 5m 42s
7012:	learn: 0.0015029	total: 11m 32s	remaining: 4m 54s
6885:	learn: 0.0015682	total: 11m 32s	remaining: 5m 13s
6886:	learn: 0.0015366	total: 11m 32s	remaining: 5m 12s
6376:	learn: 0.0014511	total: 11m 32s	remaining: 6m 33s
6688:	learn: 0.0020344	total: 11m 32s	remaining: 5m 42s
7013:	learn: 0.0015029	total: 11m 32s	remaining: 4m 54s
6886:	learn: 0.0015682	total: 11m 32s	remaining: 5m 13s
6887:	learn: 0.0015366	total: 11m 32s	remaining: 5m 12s
6377:	learn: 0.0014510	total: 11m 32s	remaining: 6m 33s
6689:	learn: 0.0020344	total: 11m 32s	remaining: 5m 42s
6887:	learn: 0.0015681	total: 11m 32s	remaining: 5m 12s
7014:	learn: 0.0015025	total: 11m 32s	remaining: 4m 54s
6888:	learn: 0.0015366	total: 11m 32s	remaining: 5m 12s
6378:	learn: 0.0014507	total: 11m 32s	remaining: 6m 33s
6888:	learn: 0.0015675	total: 11m 32s	remaining: 5m 12s
6889:	learn: 0.0015366	total: 11m 32s	remaining: 5m 12s
6690:	learn: 0.0020344	total: 11m 32s	remaining: 5m 42s
7015:	learn: 0.0015019	total: 11m 32s	remaining: 4m 54s
6889:	learn: 0.0015671	total: 11m 32s	remaining: 5m 12s
6379:	learn: 0.0014504	total: 11m 32s	remaining: 6m 33s
6890:	learn: 0.0015366	total: 11m 32s	remaining: 5m 12s
6691:	learn: 0.0020344	total: 11m 32s	remaining: 5m 42s
7016:	learn: 0.0015014	total: 11m 32s	remaining: 4m 54s
6692:	learn: 0.0020344	total: 11m 32s	remaining: 5m 42s
6890:	learn: 0.0015666	total: 11m 32s	remaining: 5m 12s
6380:	learn: 0.0014501	total: 11m 32s	remaining: 6m 32s
6891:	learn: 0.0015366	total: 11m 32s	remaining: 5m 12s
7017:	learn: 0.0015014	total: 11m 32s	remaining: 4m 54s
6891:	learn: 0.0015663	total: 11m 32s	remaining: 5m 12s
6693:	learn: 0.0020344	total: 11m 32s	remaining: 5m 42s
6892:	learn: 0.0015366	total: 11m 32s	remaining: 5m 12s
6381:	learn: 0.0014495	total: 11m 32s	remaining: 6m 32s
7018:	learn: 0.0015014	total: 11m 32s	remaining: 4m 54s
6892:	learn: 0.0015658	total: 11m 33s	remaining: 5m 12s
6893:	learn: 0.0015366	total: 11m 32s	remaining: 5m 12s
7019:	learn: 0.0015014	total: 11m 33s	remaining: 4m 54s
6694:	learn: 0.0020344	total: 11m 33s	remaining: 5m 42s
6382:	learn: 0.0014492	total: 11m 33s	remaining: 6m 32s
6893:	learn: 0.0015652	total: 11m 33s	remaining: 5m 12s
6894:	learn: 0.0015366	total: 11m 32s	remaining: 5m 12s
7020:	learn: 0.0015010	total: 11m 33s	remaining: 4m 54s
6695:	learn: 0.0020344	total: 11m 33s	remaining: 5m 42s
6383:	learn: 0.0014488	total: 11m 33s	remaining: 6m 32s
6895:	learn: 0.0015366	total: 11m 33s	remaining: 5m 11s
6894:	learn: 0.0015647	total: 11m 33s	remaining: 5m 12s
7021:	learn: 0.0015006	total: 11m 33s	remaining: 4m 53s
6696:	learn: 0.0020344	total: 11m 33s	remaining: 5m 41s
6896:	learn: 0.0015366	total: 11m 33s	remaining: 5m 11s
6384:	learn: 0.0014488	total: 11m 33s	remaining: 6m 32s
6895:	learn: 0.0015643	total: 11m 33s	remaining: 5m 12s
7022:	learn: 0.0015003	total: 11m 33s	remaining: 4m 53s
6697:	learn: 0.0020344	total: 11m 33s	remaining: 5m 41s
6385:	learn: 0.0014488	total: 11m 33s	remaining: 6m 32s
7023:	learn: 0.0014999	total: 11m 33s	remaining: 4m 53s
6896:	learn: 0.0015641	total: 11m 33s	remaining: 5m 11s
6897:	learn: 0.0015366	total: 11m 33s	remaining: 5m 11s
6698:	learn: 0.0020344	total: 11m 33s	remaining: 5m 41s
6386:	learn: 0.0014485	total: 11m 33s	remaining: 6m 32s
7024:	learn: 0.0014999	total: 11m 33s	remaining: 4m 53s
6897:	learn: 0.0015637	total: 11m 33s	remaining: 5m 11s
6898:	learn: 0.0015366	total: 11m 33s	remaining: 5m 11s
7025:	learn: 0.0014999	total: 11m 33s	remaining: 4m 53s
6699:	learn: 0.0020344	total: 11m 33s	remaining: 5m 41s
6898:	learn: 0.0015637	total: 11m 33s	remaining: 5m 11s
6899:	learn: 0.0015366	total: 11m 33s	remaining: 5m 11s
6387:	learn: 0.0014480	total: 11m 33s	remaining: 6m 32s
6700:	learn: 0.0020344	total: 11m 33s	remaining: 5m 41s
7026:	learn: 0.0014999	total: 11m 33s	remaining: 4m 53s
6900:	learn: 0.0015366	total: 11m 33s	remaining: 5m 11s
6899:	learn: 0.0015633	total: 11m 33s	remaining: 5m 11s
6701:	learn: 0.0020344	total: 11m 33s	remaining: 5m 41s
6388:	learn: 0.0014480	total: 11m 33s	remaining: 6m 32s
7027:	learn: 0.0014999	total: 11m 33s	remaining: 4m 53s
6900:	learn: 0.0015627	total: 11m 33s	remaining: 5m 11s
6901:	learn: 0.0015366	total: 11m 33s	remaining: 5m 11s
6702:	learn: 0.0020344	total: 11m 33s	remaining: 5m 41s
6389:	learn: 0.0014476	total: 11m 33s	remaining: 6m 31s
7028:	learn: 0.0014999	total: 11m 33s	remaining: 4m 53s
6901:	learn: 0.0015627	total: 11m 33s	remaining: 5m 11s
6902:	learn: 0.0015366	total: 11m 33s	remaining: 5m 11s
7029:	learn: 0.0014999	total: 11m 33s	remaining: 4m 53s
6703:	learn: 0.0020344	total: 11m 34s	remaining: 5m 41s
6390:	learn: 0.0014476	total: 11m 33s	remaining: 6m 31s
6902:	learn: 0.0015627	total: 11m 33s	remaining: 5m 11s
6704:	learn: 0.0020344	total: 11m 34s	remaining: 5m 41s
6903:	learn: 0.0015365	total: 11m 33s	remaining: 5m 11s
7030:	learn: 0.0014999	total: 11m 34s	remaining: 4m 53s
6391:	learn: 0.0014476	total: 11m 34s	remaining: 6m 31s
6903:	learn: 0.0015624	total: 11m 34s	remaining: 5m 11s
7031:	learn: 0.0014999	total: 11m 34s	remaining: 4m 52s
6705:	learn: 0.0020344	total: 11m 34s	remaining: 5m 40s
6904:	learn: 0.0015363	total: 11m 33s	remaining: 5m 11s
6392:	learn: 0.0014473	total: 11m 34s	remaining: 6m 31s
6904:	learn: 0.0015621	total: 11m 34s	remaining: 5m 11s
7032:	learn: 0.0014999	total: 11m 34s	remaining: 4m 52s
6706:	learn: 0.0020344	total: 11m 34s	remaining: 5m 40s
6306:	learn: 0.0014667	total: 11m 25s	remaining: 6m 41s
6614:	learn: 0.0020352	total: 11m 25s	remaining: 5m 50s
6905:	learn: 0.0015363	total: 11m 34s	remaining: 5m 10s
6393:	learn: 0.0014473	total: 11m 34s	remaining: 6m 31s
7033:	learn: 0.0014999	total: 11m 34s	remaining: 4m 52s
6905:	learn: 0.0015617	total: 11m 34s	remaining: 5m 11s
6707:	learn: 0.0020344	total: 11m 34s	remaining: 5m 40s
7034:	learn: 0.0014995	total: 11m 34s	remaining: 4m 52s
6906:	learn: 0.0015363	total: 11m 34s	remaining: 5m 10s
6394:	learn: 0.0014473	total: 11m 34s	remaining: 6m 31s
6906:	learn: 0.0015611	total: 11m 34s	remaining: 5m 10s
6708:	learn: 0.0020344	total: 11m 34s	remaining: 5m 40s
6395:	learn: 0.0014473	total: 11m 34s	remaining: 6m 31s
7035:	learn: 0.0014995	total: 11m 34s	remaining: 4m 52s
6907:	learn: 0.0015363	total: 11m 34s	remaining: 5m 10s
6907:	learn: 0.0015609	total: 11m 34s	remaining: 5m 10s
6396:	learn: 0.0014473	total: 11m 34s	remaining: 6m 31s
6709:	learn: 0.0020344	total: 11m 34s	remaining: 5m 40s
7036:	learn: 0.0014992	total: 11m 34s	remaining: 4m 52s
6908:	learn: 0.0015603	total: 11m 34s	remaining: 5m 10s
6908:	learn: 0.0015363	total: 11m 34s	remaining: 5m 10s
6710:	learn: 0.0020344	total: 11m 34s	remaining: 5m 40s
7037:	learn: 0.0014992	total: 11m 34s	remaining: 4m 52s
6397:	learn: 0.0014473	total: 11m 34s	remaining: 6m 31s
6909:	learn: 0.0015363	total: 11m 34s	remaining: 5m 10s
6909:	learn: 0.0015602	total: 11m 34s	remaining: 5m 10s
6711:	learn: 0.0020344	total: 11m 34s	remaining: 5m 40s
6910:	learn: 0.0015363	total: 11m 34s	remaining: 5m 10s
7038:	learn: 0.0014992	total: 11m 34s	remaining: 4m 52s
6910:	learn: 0.0015598	total: 11m 34s	remaining: 5m 10s
6911:	learn: 0.0015363	total: 11m 34s	remaining: 5m 10s
6398:	learn: 0.0014469	total: 11m 34s	remaining: 6m 31s
6712:	learn: 0.0020344	total: 11m 34s	remaining: 5m 40s
7039:	learn: 0.0014987	total: 11m 34s	remaining: 4m 52s
6912:	learn: 0.0015363	total: 11m 34s	remaining: 5m 10s
6399:	learn: 0.0014468	total: 11m 34s	remaining: 6m 30s
6911:	learn: 0.0015598	total: 11m 34s	remaining: 5m 10s
6713:	learn: 0.0020344	total: 11m 35s	remaining: 5m 40s
7040:	learn: 0.0014987	total: 11m 34s	remaining: 4m 52s
6913:	learn: 0.0015363	total: 11m 34s	remaining: 5m 10s
6400:	learn: 0.0014465	total: 11m 35s	remaining: 6m 30s
6714:	learn: 0.0020344	total: 11m 35s	remaining: 5m 40s
6912:	learn: 0.0015599	total: 11m 35s	remaining: 5m 10s
7041:	learn: 0.0014987	total: 11m 35s	remaining: 4m 51s
6914:	learn: 0.0015363	total: 11m 34s	remaining: 5m 10s
6715:	learn: 0.0020344	total: 11m 35s	remaining: 5m 39s
6401:	learn: 0.0014465	total: 11m 35s	remaining: 6m 30s
6913:	learn: 0.0015594	total: 11m 35s	remaining: 5m 10s
7042:	learn: 0.0014987	total: 11m 35s	remaining: 4m 51s
6915:	learn: 0.0015363	total: 11m 35s	remaining: 5m 9s
6716:	learn: 0.0020344	total: 11m 35s	remaining: 5m 39s
6402:	learn: 0.0014465	total: 11m 35s	remaining: 6m 30s
6914:	learn: 0.0015591	total: 11m 35s	remaining: 5m 10s
6916:	learn: 0.0015363	total: 11m 35s	remaining: 5m 9s
7043:	learn: 0.0014987	total: 11m 35s	remaining: 4m 51s
6717:	learn: 0.0020344	total: 11m 35s	remaining: 5m 39s
6403:	learn: 0.0014465	total: 11m 35s	remaining: 6m 30s
6917:	learn: 0.0015359	total: 11m 35s	remaining: 5m 9s
6915:	learn: 0.0015586	total: 11m 35s	remaining: 5m 10s
7044:	learn: 0.0014987	total: 11m 35s	remaining: 4m 51s
6718:	learn: 0.0020344	total: 11m 35s	remaining: 5m 39s
6918:	learn: 0.0015359	total: 11m 35s	remaining: 5m 9s
6404:	learn: 0.0014460	total: 11m 35s	remaining: 6m 30s
7045:	learn: 0.0014982	total: 11m 35s	remaining: 4m 51s
6916:	learn: 0.0015586	total: 11m 35s	remaining: 5m 9s
6919:	learn: 0.0015359	total: 11m 35s	remaining: 5m 9s
6719:	learn: 0.0020344	total: 11m 35s	remaining: 5m 39s
7046:	learn: 0.0014982	total: 11m 35s	remaining: 4m 51s
6405:	learn: 0.0014456	total: 11m 35s	remaining: 6m 30s
6920:	learn: 0.0015359	total: 11m 35s	remaining: 5m 9s
6917:	learn: 0.0015586	total: 11m 35s	remaining: 5m 9s
7047:	learn: 0.0014982	total: 11m 35s	remaining: 4m 51s
6720:	learn: 0.0020344	total: 11m 35s	remaining: 5m 39s
6406:	learn: 0.0014453	total: 11m 35s	remaining: 6m 30s
6921:	learn: 0.0015359	total: 11m 35s	remaining: 5m 9s
6918:	learn: 0.0015586	total: 11m 35s	remaining: 5m 9s
7048:	learn: 0.0014982	total: 11m 35s	remaining: 4m 51s
6721:	learn: 0.0020344	total: 11m 35s	remaining: 5m 39s
6407:	learn: 0.0014449	total: 11m 35s	remaining: 6m 30s
6922:	learn: 0.0015359	total: 11m 35s	remaining: 5m 9s
7049:	learn: 0.0014982	total: 11m 35s	remaining: 4m 51s
6919:	learn: 0.0015586	total: 11m 35s	remaining: 5m 9s
6722:	learn: 0.0020344	total: 11m 35s	remaining: 5m 39s
6923:	learn: 0.0015359	total: 11m 35s	remaining: 5m 9s
6408:	learn: 0.0014449	total: 11m 35s	remaining: 6m 29s
6920:	learn: 0.0015583	total: 11m 35s	remaining: 5m 9s
7050:	learn: 0.0014982	total: 11m 35s	remaining: 4m 51s
6723:	learn: 0.0020344	total: 11m 36s	remaining: 5m 39s
6924:	learn: 0.0015359	total: 11m 35s	remaining: 5m 8s
7051:	learn: 0.0014977	total: 11m 35s	remaining: 4m 50s
6409:	learn: 0.0014445	total: 11m 36s	remaining: 6m 29s
6921:	learn: 0.0015578	total: 11m 36s	remaining: 5m 9s
6724:	learn: 0.0020344	total: 11m 36s	remaining: 5m 38s
6925:	learn: 0.0015359	total: 11m 35s	remaining: 5m 8s
7052:	learn: 0.0014976	total: 11m 36s	remaining: 4m 50s
6410:	learn: 0.0014445	total: 11m 36s	remaining: 6m 29s
6922:	learn: 0.0015578	total: 11m 36s	remaining: 5m 9s
6725:	learn: 0.0020344	total: 11m 36s	remaining: 5m 38s
6926:	learn: 0.0015359	total: 11m 35s	remaining: 5m 8s
7053:	learn: 0.0014976	total: 11m 36s	remaining: 4m 50s
6726:	learn: 0.0020344	total: 11m 36s	remaining: 5m 38s
6411:	learn: 0.0014445	total: 11m 36s	remaining: 6m 29s
6923:	learn: 0.0015578	total: 11m 36s	remaining: 5m 9s
6927:	learn: 0.0015359	total: 11m 36s	remaining: 5m 8s
7054:	learn: 0.0014976	total: 11m 36s	remaining: 4m 50s
6727:	learn: 0.0020344	total: 11m 36s	remaining: 5m 38s
6412:	learn: 0.0014445	total: 11m 36s	remaining: 6m 29s
6924:	learn: 0.0015578	total: 11m 36s	remaining: 5m 9s
6928:	learn: 0.0015359	total: 11m 36s	remaining: 5m 8s
7055:	learn: 0.0014976	total: 11m 36s	remaining: 4m 50s
6728:	learn: 0.0020344	total: 11m 36s	remaining: 5m 38s
6929:	learn: 0.0015359	total: 11m 36s	remaining: 5m 8s
6925:	learn: 0.0015574	total: 11m 36s	remaining: 5m 9s
7056:	learn: 0.0014976	total: 11m 36s	remaining: 4m 50s
6413:	learn: 0.0014445	total: 11m 36s	remaining: 6m 29s
6729:	learn: 0.0020344	total: 11m 36s	remaining: 5m 38s
6930:	learn: 0.0015359	total: 11m 36s	remaining: 5m 8s
6926:	learn: 0.0015574	total: 11m 36s	remaining: 5m 9s
7057:	learn: 0.0014977	total: 11m 36s	remaining: 4m 50s
6414:	learn: 0.0014445	total: 11m 36s	remaining: 6m 29s
6730:	learn: 0.0020344	total: 11m 36s	remaining: 5m 38s
6931:	learn: 0.0015356	total: 11m 36s	remaining: 5m 8s
7058:	learn: 0.0014973	total: 11m 36s	remaining: 4m 50s
6927:	learn: 0.0015569	total: 11m 36s	remaining: 5m 8s
6415:	learn: 0.0014445	total: 11m 36s	remaining: 6m 29s
6731:	learn: 0.0020344	total: 11m 36s	remaining: 5m 38s
6932:	learn: 0.0015356	total: 11m 36s	remaining: 5m 8s
7059:	learn: 0.0014973	total: 11m 36s	remaining: 4m 50s
6732:	learn: 0.0020344	total: 11m 36s	remaining: 5m 38s
6416:	learn: 0.0014445	total: 11m 36s	remaining: 6m 29s
6928:	learn: 0.0015566	total: 11m 36s	remaining: 5m 8s
6933:	learn: 0.0015354	total: 11m 36s	remaining: 5m 8s
7060:	learn: 0.0014969	total: 11m 36s	remaining: 4m 50s
6733:	learn: 0.0020344	total: 11m 36s	remaining: 5m 38s
6417:	learn: 0.0014445	total: 11m 36s	remaining: 6m 28s
6929:	learn: 0.0015564	total: 11m 36s	remaining: 5m 8s
6934:	learn: 0.0015353	total: 11m 36s	remaining: 5m 7s
7061:	learn: 0.0014969	total: 11m 36s	remaining: 4m 49s
6734:	learn: 0.0020344	total: 11m 37s	remaining: 5m 37s
6935:	learn: 0.0015353	total: 11m 36s	remaining: 5m 7s
6930:	learn: 0.0015559	total: 11m 37s	remaining: 5m 8s
6418:	learn: 0.0014443	total: 11m 37s	remaining: 6m 28s
7062:	learn: 0.0014969	total: 11m 36s	remaining: 4m 49s
6735:	learn: 0.0020344	total: 11m 37s	remaining: 5m 37s
6936:	learn: 0.0015353	total: 11m 36s	remaining: 5m 7s
6931:	learn: 0.0015555	total: 11m 37s	remaining: 5m 8s
6419:	learn: 0.0014440	total: 11m 37s	remaining: 6m 28s
7063:	learn: 0.0014969	total: 11m 37s	remaining: 4m 49s

6932:	learn: 0.0015555	total: 11m 37s	remaining: 5m 8s
6937:	learn: 0.0015353	total: 11m 36s	remaining: 5m 7s
6736:	learn: 0.0020344	total: 11m 37s	remaining: 5m 37s
7064:	learn: 0.0014969	total: 11m 37s	remaining: 4m 49s
6420:	learn: 0.0014439	total: 11m 37s	remaining: 6m 28s
6938:	learn: 0.0015353	total: 11m 37s	remaining: 5m 7s
6933:	learn: 0.0015552	total: 11m 37s	remaining: 5m 8s
6421:	learn: 0.0014439	total: 11m 37s	remaining: 6m 28s
7065:	learn: 0.0014969	total: 11m 37s	remaining: 4m 49s
6737:	learn: 0.0020344	total: 11m 37s	remaining: 5m 37s
6934:	learn: 0.0015550	total: 11m 37s	remaining: 5m 8s
6939:	learn: 0.0015353	total: 11m 37s	remaining: 5m 7s
6422:	learn: 0.0014435	total: 11m 37s	remaining: 6m 28s
6738:	learn: 0.0020344	total: 11m 37s	remaining: 5m 37s
7066:	learn: 0.0014969	total: 11m 37s	remaining: 4m 49s
6940:	learn: 0.0015353	total: 11m 37s	remaining: 5m 7s
6935:	learn: 0.0015550	total: 11m 37s	remaining: 5m 8s
6739:	learn: 0.0020344	total: 11m 37s	remaining: 5m 37s
6423:	learn: 0.0014432	total: 11m 37s	remaining: 6m 28s
7067:	learn: 0.0014969	total: 11m 37s	remaining: 4m 49s
6936:	learn: 0.0015550	total: 11m 37s	remaining: 5m 8s
6941:	learn: 0.0015353	total: 11m 37s	remaining: 5m 7s
6424:	learn: 0.0014428	total: 11m 37s	remaining: 6m 28s
6740:	learn: 0.0020344	total: 11m 37s	remaining: 5m 37s
6942:	learn: 0.0015353	total: 11m 37s	remaining: 5m 7s
7068:	learn: 0.0014969	total: 11m 37s	remaining: 4m 49s
6937:	learn: 0.0015550	total: 11m 37s	remaining: 5m 7s
6425:	learn: 0.0014425	total: 11m 37s	remaining: 6m 28s
6943:	learn: 0.0015353	total: 11m 37s	remaining: 5m 6s
6741:	learn: 0.0020344	total: 11m 37s	remaining: 5m 37s
7069:	learn: 0.0014969	total: 11m 37s	remaining: 4m 49s
6938:	learn: 0.0015550	total: 11m 37s	remaining: 5m 7s
6944:	learn: 0.0015353	total: 11m 37s	remaining: 5m 6s
7070:	learn: 0.0014969	total: 11m 37s	remaining: 4m 49s
6426:	learn: 0.0014425	total: 11m 37s	remaining: 6m 27s
6742:	learn: 0.0020344	total: 11m 37s	remaining: 5m 37s
6945:	learn: 0.0015352	total: 11m 37s	remaining: 5m 6s
7071:	learn: 0.0014969	total: 11m 37s	remaining: 4m 48s
6939:	learn: 0.0015550	total: 11m 37s	remaining: 5m 7s
6743:	learn: 0.0020344	total: 11m 38s	remaining: 5m 36s
6427:	learn: 0.0014422	total: 11m 37s	remaining: 6m 27s
6946:	learn: 0.0015351	total: 11m 37s	remaining: 5m 6s
7072:	learn: 0.0014969	total: 11m 38s	remaining: 4m 48s
6940:	learn: 0.0015545	total: 11m 38s	remaining: 5m 7s
6744:	learn: 0.0020344	total: 11m 38s	remaining: 5m 36s
6428:	learn: 0.0014422	total: 11m 38s	remaining: 6m 27s
6947:	learn: 0.0015351	total: 11m 37s	remaining: 5m 6s
7073:	learn: 0.0014969	total: 11m 38s	remaining: 4m 48s
6745:	learn: 0.0020344	total: 11m 38s	remaining: 5m 36s
6941:	learn: 0.0015545	total: 11m 38s	remaining: 5m 7s
6429:	learn: 0.0014419	total: 11m 38s	remaining: 6m 27s
6948:	learn: 0.0015351	total: 11m 38s	remaining: 5m 6s
6942:	learn: 0.0015545	total: 11m 38s	remaining: 5m 7s
7074:	learn: 0.0014969	total: 11m 38s	remaining: 4m 48s
6746:	learn: 0.0020344	total: 11m 38s	remaining: 5m 36s
6430:	learn: 0.0014419	total: 11m 38s	remaining: 6m 27s
6949:	learn: 0.0015351	total: 11m 38s	remaining: 5m 6s
6747:	learn: 0.0020344	total: 11m 38s	remaining: 5m 36s
7075:	learn: 0.0014969	total: 11m 38s	remaining: 4m 48s
6943:	learn: 0.0015540	total: 11m 38s	remaining: 5m 7s
6431:	learn: 0.0014415	total: 11m 38s	remaining: 6m 27s
6950:	learn: 0.0015347	total: 11m 38s	remaining: 5m 6s
6944:	learn: 0.0015540	total: 11m 38s	remaining: 5m 7s
6748:	learn: 0.0020344	total: 11m 38s	remaining: 5m 36s
7076:	learn: 0.0014969	total: 11m 38s	remaining: 4m 48s
6951:	learn: 0.0015347	total: 11m 38s	remaining: 5m 6s
6945:	learn: 0.0015540	total: 11m 38s	remaining: 5m 7s
6749:	learn: 0.0020344	total: 11m 38s	remaining: 5m 36s
6432:	learn: 0.0014415	total: 11m 38s	remaining: 6m 27s
7077:	learn: 0.0014966	total: 11m 38s	remaining: 4m 48s
6952:	learn: 0.0015347	total: 11m 38s	remaining: 5m 6s
6946:	learn: 0.0015540	total: 11m 38s	remaining: 5m 7s
6750:	learn: 0.0020344	total: 11m 38s	remaining: 5m 36s
6433:	learn: 0.0014415	total: 11m 38s	remaining: 6m 27s
6953:	learn: 0.0015347	total: 11m 38s	remaining: 5m 5s
7078:	learn: 0.0014966	total: 11m 38s	remaining: 4m 48s
6947:	learn: 0.0015540	total: 11m 38s	remaining: 5m 6s
6751:	learn: 0.0020344	total: 11m 38s	remaining: 5m 36s
6948:	learn: 0.0015540	total: 11m 38s	remaining: 5m 6s
6434:	learn: 0.0014413	total: 11m 38s	remaining: 6m 27s
7079:	learn: 0.0014966	total: 11m 38s	remaining: 4m 48s
6954:	learn: 0.0015347	total: 11m 38s	remaining: 5m 5s
6752:	learn: 0.0020344	total: 11m 38s	remaining: 5m 36s
6949:	learn: 0.0015540	total: 11m 38s	remaining: 5m 6s
6435:	learn: 0.0014410	total: 11m 38s	remaining: 6m 27s
7080:	learn: 0.0014966	total: 11m 38s	remaining: 4m 48s
6955:	learn: 0.0015347	total: 11m 38s	remaining: 5m 5s
6753:	learn: 0.0020344	total: 11m 38s	remaining: 5m 35s
6950:	learn: 0.0015540	total: 11m 38s	remaining: 5m 6s
6436:	learn: 0.0014405	total: 11m 38s	remaining: 6m 26s
7081:	learn: 0.0014966	total: 11m 38s	remaining: 4m 47s
6951:	learn: 0.0015540	total: 11m 39s	remaining: 5m 6s
6956:	learn: 0.0015344	total: 11m 38s	remaining: 5m 5s
6754:	learn: 0.0020344	total: 11m 39s	remaining: 5m 35s
7082:	learn: 0.0014962	total: 11m 39s	remaining: 4m 47s
6952:	learn: 0.0015540	total: 11m 39s	remaining: 5m 6s
6437:	learn: 0.0014403	total: 11m 39s	remaining: 6m 26s
6957:	learn: 0.0015338	total: 11m 38s	remaining: 5m 5s
7083:	learn: 0.0014958	total: 11m 39s	remaining: 4m 47s
6755:	learn: 0.0020344	total: 11m 39s	remaining: 5m 35s
6953:	learn: 0.0015540	total: 11m 39s	remaining: 5m 6s
6438:	learn: 0.0014400	total: 11m 39s	remaining: 6m 26s
7084:	learn: 0.0014957	total: 11m 39s	remaining: 4m 47s
6958:	learn: 0.0015338	total: 11m 39s	remaining: 5m 5s
6756:	learn: 0.0020344	total: 11m 39s	remaining: 5m 35s
6954:	learn: 0.0015540	total: 11m 39s	remaining: 5m 6s
6439:	learn: 0.0014395	total: 11m 39s	remaining: 6m 26s
7085:	learn: 0.0014957	total: 11m 39s	remaining: 4m 47s
6757:	learn: 0.0020344	total: 11m 39s	remaining: 5m 35s
6959:	learn: 0.0015338	total: 11m 39s	remaining: 5m 5s
6955:	learn: 0.0015540	total: 11m 39s	remaining: 5m 6s
6440:	learn: 0.0014395	total: 11m 39s	remaining: 6m 26s
7086:	learn: 0.0014958	total: 11m 39s	remaining: 4m 47s
6960:	learn: 0.0015338	total: 11m 39s	remaining: 5m 5s
6758:	learn: 0.0020344	total: 11m 39s	remaining: 5m 35s
6956:	learn: 0.0015538	total: 11m 39s	remaining: 5m 5s
6441:	learn: 0.0014392	total: 11m 39s	remaining: 6m 26s
7087:	learn: 0.0014957	total: 11m 39s	remaining: 4m 47s
6961:	learn: 0.0015338	total: 11m 39s	remaining: 5m 5s
6759:	learn: 0.0020344	total: 11m 39s	remaining: 5m 35s
6957:	learn: 0.0015534	total: 11m 39s	remaining: 5m 5s
6442:	learn: 0.0014388	total: 11m 39s	remaining: 6m 26s
7088:	learn: 0.0014958	total: 11m 39s	remaining: 4m 47s
6962:	learn: 0.0015338	total: 11m 39s	remaining: 5m 5s
6760:	learn: 0.0020344	total: 11m 39s	remaining: 5m 35s
6958:	learn: 0.0015529	total: 11m 39s	remaining: 5m 5s
6443:	learn: 0.0014386	total: 11m 39s	remaining: 6m 26s
7089:	learn: 0.0014958	total: 11m 39s	remaining: 4m 47s
6963:	learn: 0.0015338	total: 11m 39s	remaining: 5m 4s
6761:	learn: 0.0020344	total: 11m 39s	remaining: 5m 35s
6959:	learn: 0.0015527	total: 11m 39s	remaining: 5m 5s
7090:	learn: 0.0014958	total: 11m 39s	remaining: 4m 47s
6444:	learn: 0.0014381	total: 11m 39s	remaining: 6m 26s
6964:	learn: 0.0015338	total: 11m 39s	remaining: 5m 4s
6762:	learn: 0.0020344	total: 11m 39s	remaining: 5m 35s
6960:	learn: 0.0015522	total: 11m 39s	remaining: 5m 5s
7091:	learn: 0.0014957	total: 11m 39s	remaining: 4m 46s
6965:	learn: 0.0015338	total: 11m 39s	remaining: 5m 4s
6763:	learn: 0.0020344	total: 11m 39s	remaining: 5m 34s
6445:	learn: 0.0014378	total: 11m 39s	remaining: 6m 25s
6961:	learn: 0.0015517	total: 11m 39s	remaining: 5m 5s
7092:	learn: 0.0014957	total: 11m 39s	remaining: 4m 46s
6764:	learn: 0.0020344	total: 11m 40s	remaining: 5m 34s
6446:	learn: 0.0014374	total: 11m 40s	remaining: 6m 25s
6966:	learn: 0.0015338	total: 11m 39s	remaining: 5m 4s
6962:	learn: 0.0015517	total: 11m 40s	remaining: 5m 5s
7093:	learn: 0.0014957	total: 11m 40s	remaining: 4m 46s
6447:	learn: 0.0014371	total: 11m 40s	remaining: 6m 25s
6963:	learn: 0.0015511	total: 11m 40s	remaining: 5m 5s
6765:	learn: 0.0020344	total: 11m 40s	remaining: 5m 34s
6967:	learn: 0.0015338	total: 11m 39s	remaining: 5m 4s
7094:	learn: 0.0014957	total: 11m 40s	remaining: 4m 46s
6448:	learn: 0.0014369	total: 11m 40s	remaining: 6m 25s
6964:	learn: 0.0015511	total: 11m 40s	remaining: 5m 5s
6766:	learn: 0.0020344	total: 11m 40s	remaining: 5m 34s
7095:	learn: 0.0014957	total: 11m 40s	remaining: 4m 46s
6968:	learn: 0.0015338	total: 11m 40s	remaining: 5m 4s
6449:	learn: 0.0014369	total: 11m 40s	remaining: 6m 25s
6767:	learn: 0.0020344	total: 11m 40s	remaining: 5m 34s
7096:	learn: 0.0014952	total: 11m 40s	remaining: 4m 46s
6969:	learn: 0.0015338	total: 11m 40s	remaining: 5m 4s
6965:	learn: 0.0015508	total: 11m 40s	remaining: 5m 5s
6450:	learn: 0.0014365	total: 11m 40s	remaining: 6m 25s
7097:	learn: 0.0014952	total: 11m 40s	remaining: 4m 46s
6768:	learn: 0.0020344	total: 11m 40s	remaining: 5m 34s
6970:	learn: 0.0015333	total: 11m 40s	remaining: 5m 4s
6966:	learn: 0.0015504	total: 11m 40s	remaining: 5m 4s
6451:	learn: 0.0014365	total: 11m 40s	remaining: 6m 25s
7098:	learn: 0.0014952	total: 11m 40s	remaining: 4m 46s
6769:	learn: 0.0020344	total: 11m 40s	remaining: 5m 34s
6971:	learn: 0.0015333	total: 11m 40s	remaining: 5m 4s
6967:	learn: 0.0015499	total: 11m 40s	remaining: 5m 4s
7099:	learn: 0.0014952	total: 11m 40s	remaining: 4m 46s
6452:	learn: 0.0014361	total: 11m 40s	remaining: 6m 25s
6770:	learn: 0.0020344	total: 11m 40s	remaining: 5m 34s
6972:	learn: 0.0015333	total: 11m 40s	remaining: 5m 4s
7100:	learn: 0.0014952	total: 11m 40s	remaining: 4m 46s
6968:	learn: 0.0015494	total: 11m 40s	remaining: 5m 4s
6453:	learn: 0.0014361	total: 11m 40s	remaining: 6m 25s
6771:	learn: 0.0020344	total: 11m 40s	remaining: 5m 34s
6973:	learn: 0.0015333	total: 11m 40s	remaining: 5m 3s
7101:	learn: 0.0014952	total: 11m 40s	remaining: 4m 45s
6969:	learn: 0.0015491	total: 11m 40s	remaining: 5m 4s
6454:	learn: 0.0014357	total: 11m 40s	remaining: 6m 24s
6974:	learn: 0.0015333	total: 11m 40s	remaining: 5m 3s
6772:	learn: 0.0020343	total: 11m 40s	remaining: 5m 33s
7102:	learn: 0.0014952	total: 11m 40s	remaining: 4m 45s
6970:	learn: 0.0015487	total: 11m 40s	remaining: 5m 4s
6455:	learn: 0.0014357	total: 11m 40s	remaining: 6m 24s
6975:	learn: 0.0015333	total: 11m 40s	remaining: 5m 3s
6773:	learn: 0.0020343	total: 11m 41s	remaining: 5m 33s
7103:	learn: 0.0014952	total: 11m 40s	remaining: 4m 45s
6971:	learn: 0.0015482	total: 11m 41s	remaining: 5m 4s
6456:	learn: 0.0014354	total: 11m 41s	remaining: 6m 24s
6774:	learn: 0.0020344	total: 11m 41s	remaining: 5m 33s
6976:	learn: 0.0015333	total: 11m 40s	remaining: 5m 3s
7104:	learn: 0.0014952	total: 11m 41s	remaining: 4m 45s
6972:	learn: 0.0015476	total: 11m 41s	remaining: 5m 4s
6775:	learn: 0.0020336	total: 11m 41s	remaining: 5m 33s
6457:	learn: 0.0014352	total: 11m 41s	remaining: 6m 24s
6977:	learn: 0.0015333	total: 11m 41s	remaining: 5m 3s
6973:	learn: 0.0015472	total: 11m 41s	remaining: 5m 4s
7105:	learn: 0.0014952	total: 11m 41s	remaining: 4m 45s
6776:	learn: 0.0020327	total: 11m 41s	remaining: 5m 33s
6458:	learn: 0.0014352	total: 11m 41s	remaining: 6m 24s
6978:	learn: 0.0015333	total: 11m 41s	remaining: 5m 3s
6974:	learn: 0.0015472	total: 11m 41s	remaining: 5m 4s
6777:	learn: 0.0020322	total: 11m 41s	remaining: 5m 33s
7106:	learn: 0.0014952	total: 11m 41s	remaining: 4m 45s
6979:	learn: 0.0015330	total: 11m 41s	remaining: 5m 3s
6459:	learn: 0.0014352	total: 11m 41s	remaining: 6m 24s
6975:	learn: 0.0015469	total: 11m 41s	remaining: 5m 4s
7107:	learn: 0.0014952	total: 11m 41s	remaining: 4m 45s
6778:	learn: 0.0020322	total: 11m 41s	remaining: 5m 33s
6980:	learn: 0.0015329	total: 11m 41s	remaining: 5m 3s
6460:	learn: 0.0014352	total: 11m 41s	remaining: 6m 24s
6976:	learn: 0.0015464	total: 11m 41s	remaining: 5m 3s
6779:	learn: 0.0020322	total: 11m 41s	remaining: 5m 33s
7108:	learn: 0.0014952	total: 11m 41s	remaining: 4m 45s
6981:	learn: 0.0015329	total: 11m 41s	remaining: 5m 3s
6461:	learn: 0.0014352	total: 11m 41s	remaining: 6m 24s
6977:	learn: 0.0015459	total: 11m 41s	remaining: 5m 3s
7109:	learn: 0.0014952	total: 11m 41s	remaining: 4m 45s
6780:	learn: 0.0020322	total: 11m 41s	remaining: 5m 33s
6982:	learn: 0.0015329	total: 11m 41s	remaining: 5m 3s
6462:	learn: 0.0014349	total: 11m 41s	remaining: 6m 24s
6978:	learn: 0.0015455	total: 11m 41s	remaining: 5m 3s
7110:	learn: 0.0014952	total: 11m 41s	remaining: 4m 45s
6781:	learn: 0.0020322	total: 11m 41s	remaining: 5m 33s
6979:	learn: 0.0015446	total: 11m 41s	remaining: 5m 3s
6983:	learn: 0.0015329	total: 11m 41s	remaining: 5m 2s
6463:	learn: 0.0014346	total: 11m 41s	remaining: 6m 23s
6782:	learn: 0.0020322	total: 11m 41s	remaining: 5m 32s
7111:	learn: 0.0014949	total: 11m 41s	remaining: 4m 44s
6984:	learn: 0.0015329	total: 11m 41s	remaining: 5m 2s
6980:	learn: 0.0015443	total: 11m 41s	remaining: 5m 3s
6464:	learn: 0.0014343	total: 11m 41s	remaining: 6m 23s
6783:	learn: 0.0020322	total: 11m 41s	remaining: 5m 32s
7112:	learn: 0.0014949	total: 11m 41s	remaining: 4m 44s
6985:	learn: 0.0015329	total: 11m 41s	remaining: 5m 2s
6784:	learn: 0.0020322	total: 11m 42s	remaining: 5m 32s
6981:	learn: 0.0015439	total: 11m 42s	remaining: 5m 3s
6465:	learn: 0.0014339	total: 11m 42s	remaining: 6m 23s
7113:	learn: 0.0014949	total: 11m 42s	remaining: 4m 44s
6986:	learn: 0.0015329	total: 11m 41s	remaining: 5m 2s
6785:	learn: 0.0020322	total: 11m 42s	remaining: 5m 32s
6982:	learn: 0.0015433	total: 11m 42s	remaining: 5m 3s
7114:	learn: 0.0014949	total: 11m 42s	remaining: 4m 44s
6987:	learn: 0.0015329	total: 11m 41s	remaining: 5m 2s
6466:	learn: 0.0014338	total: 11m 42s	remaining: 6m 23s
6983:	learn: 0.0015433	total: 11m 42s	remaining: 5m 3s
6786:	learn: 0.0020322	total: 11m 42s	remaining: 5m 32s
7115:	learn: 0.0014949	total: 11m 42s	remaining: 4m 44s
6988:	learn: 0.0015326	total: 11m 42s	remaining: 5m 2s
6984:	learn: 0.0015428	total: 11m 42s	remaining: 5m 3s
7116:	learn: 0.0014949	total: 11m 42s	remaining: 4m 44s
6467:	learn: 0.0014334	total: 11m 42s	remaining: 6m 23s
6787:	learn: 0.0020322	total: 11m 42s	remaining: 5m 32s
6989:	learn: 0.0015326	total: 11m 42s	remaining: 5m 2s
6985:	learn: 0.0015425	total: 11m 42s	remaining: 5m 3s
7117:	learn: 0.0014944	total: 11m 42s	remaining: 4m 44s
6468:	learn: 0.0014330	total: 11m 42s	remaining: 6m 23s
6788:	learn: 0.0020322	total: 11m 42s	remaining: 5m 32s
6986:	learn: 0.0015421	total: 11m 42s	remaining: 5m 2s
6990:	learn: 0.0015325	total: 11m 42s	remaining: 5m 2s
7118:	learn: 0.0014941	total: 11m 42s	remaining: 4m 44s
6469:	learn: 0.0014330	total: 11m 42s	remaining: 6m 23s
6789:	learn: 0.0020322	total: 11m 42s	remaining: 5m 32s
6991:	learn: 0.0015325	total: 11m 42s	remaining: 5m 2s
6987:	learn: 0.0015417	total: 11m 42s	remaining: 5m 2s
7119:	learn: 0.0014941	total: 11m 42s	remaining: 4m 44s
6790:	learn: 0.0020322	total: 11m 42s	remaining: 5m 32s
6470:	learn: 0.0014330	total: 11m 42s	remaining: 6m 23s
6988:	learn: 0.0015412	total: 11m 42s	remaining: 5m 2s
6992:	learn: 0.0015325	total: 11m 42s	remaining: 5m 2s
7120:	learn: 0.0014941	total: 11m 42s	remaining: 4m 44s
6471:	learn: 0.0014327	total: 11m 42s	remaining: 6m 23s
6791:	learn: 0.0020322	total: 11m 42s	remaining: 5m 31s
6989:	learn: 0.0015407	total: 11m 42s	remaining: 5m 2s
7121:	learn: 0.0014941	total: 11m 42s	remaining: 4m 43s
6993:	learn: 0.0015325	total: 11m 42s	remaining: 5m 1s
6472:	learn: 0.0014327	total: 11m 42s	remaining: 6m 22s
6792:	learn: 0.0020322	total: 11m 42s	remaining: 5m 31s
7122:	learn: 0.0014941	total: 11m 42s	remaining: 4m 43s
6994:	learn: 0.0015325	total: 11m 42s	remaining: 5m 1s
6990:	learn: 0.0015403	total: 11m 42s	remaining: 5m 2s
7123:	learn: 0.0014941	total: 11m 42s	remaining: 4m 43s
6793:	learn: 0.0020322	total: 11m 42s	remaining: 5m 31s
6473:	learn: 0.0014324	total: 11m 42s	remaining: 6m 22s
6995:	learn: 0.0015325	total: 11m 42s	remaining: 5m 1s
6794:	learn: 0.0020322	total: 11m 43s	remaining: 5m 31s
6991:	learn: 0.0015401	total: 11m 43s	remaining: 5m 2s
7124:	learn: 0.0014941	total: 11m 42s	remaining: 4m 43s
6474:	learn: 0.0014324	total: 11m 43s	remaining: 6m 22s

6996:	learn: 0.0015320	total: 11m 42s	remaining: 5m 1s
7125:	learn: 0.0014941	total: 11m 43s	remaining: 4m 43s
6795:	learn: 0.0020322	total: 11m 43s	remaining: 5m 31s
6992:	learn: 0.0015396	total: 11m 43s	remaining: 5m 2s
6997:	learn: 0.0015320	total: 11m 42s	remaining: 5m 1s
6475:	learn: 0.0014321	total: 11m 43s	remaining: 6m 22s
7126:	learn: 0.0014940	total: 11m 43s	remaining: 4m 43s
6993:	learn: 0.0015392	total: 11m 43s	remaining: 5m 2s
6998:	learn: 0.0015320	total: 11m 43s	remaining: 5m 1s
6796:	learn: 0.0020322	total: 11m 43s	remaining: 5m 31s
6476:	learn: 0.0014321	total: 11m 43s	remaining: 6m 22s
7127:	learn: 0.0014940	total: 11m 43s	remaining: 4m 43s
6994:	learn: 0.0015390	total: 11m 43s	remaining: 5m 2s
6797:	learn: 0.0020322	total: 11m 43s	remaining: 5m 31s
6999:	learn: 0.0015320	total: 11m 43s	remaining: 5m 1s
6477:	learn: 0.0014321	total: 11m 43s	remaining: 6m 22s
7128:	learn: 0.0014940	total: 11m 43s	remaining: 4m 43s
6995:	learn: 0.0015385	total: 11m 43s	remaining: 5m 2s
7000:	learn: 0.0015320	total: 11m 43s	remaining: 5m 1s
6798:	learn: 0.0020322	total: 11m 43s	remaining: 5m 31s
7129:	learn: 0.0014939	total: 11m 43s	remaining: 4m 43s
6478:	learn: 0.0014321	total: 11m 43s	remaining: 6m 22s
6799:	learn: 0.0020322	total: 11m 43s	remaining: 5m 31s
6996:	learn: 0.0015381	total: 11m 43s	remaining: 5m 1s
7130:	learn: 0.0014939	total: 11m 43s	remaining: 4m 43s
7001:	learn: 0.0015320	total: 11m 43s	remaining: 5m 1s
6997:	learn: 0.0015378	total: 11m 43s	remaining: 5m 1s
6800:	learn: 0.0020322	total: 11m 43s	remaining: 5m 30s
6479:	learn: 0.0014318	total: 11m 43s	remaining: 6m 22s
7131:	learn: 0.0014935	total: 11m 43s	remaining: 4m 42s
7002:	learn: 0.0015320	total: 11m 43s	remaining: 5m 1s
6801:	learn: 0.0020322	total: 11m 43s	remaining: 5m 30s
6998:	learn: 0.0015373	total: 11m 43s	remaining: 5m 1s
7003:	learn: 0.0015320	total: 11m 43s	remaining: 5m
7132:	learn: 0.0014935	total: 11m 43s	remaining: 4m 42s
6480:	learn: 0.0014318	total: 11m 43s	remaining: 6m 22s
6802:	learn: 0.0020322	total: 11m 43s	remaining: 5m 30s
6999:	learn: 0.0015368	total: 11m 43s	remaining: 5m 1s
7004:	learn: 0.0015320	total: 11m 43s	remaining: 5m
7133:	learn: 0.0014935	total: 11m 43s	remaining: 4m 42s
6803:	learn: 0.0020322	total: 11m 43s	remaining: 5m 30s
6481:	learn: 0.0014315	total: 11m 43s	remaining: 6m 22s
7000:	learn: 0.0015365	total: 11m 43s	remaining: 5m 1s
7005:	learn: 0.0015320	total: 11m 43s	remaining: 5m
7134:	learn: 0.0014935	total: 11m 43s	remaining: 4m 42s
6804:	learn: 0.0020322	total: 11m 44s	remaining: 5m 30s
7001:	learn: 0.0015365	total: 11m 43s	remaining: 5m 1s
6482:	learn: 0.0014315	total: 11m 44s	remaining: 6m 21s
7006:	learn: 0.0015320	total: 11m 43s	remaining: 5m
6483:	learn: 0.0014315	total: 11m 44s	remaining: 6m 21s
7002:	learn: 0.0015360	total: 11m 44s	remaining: 5m 1s
7135:	learn: 0.0014935	total: 11m 44s	remaining: 4m 42s
6805:	learn: 0.0020322	total: 11m 44s	remaining: 5m 30s
7007:	learn: 0.0015320	total: 11m 43s	remaining: 5m
6806:	learn: 0.0020322	total: 11m 44s	remaining: 5m 30s
7003:	learn: 0.0015359	total: 11m 44s	remaining: 5m 1s
6484:	learn: 0.0014315	total: 11m 44s	remaining: 6m 21s
7008:	learn: 0.0015320	total: 11m 44s	remaining: 5m
7136:	learn: 0.0014935	total: 11m 44s	remaining: 4m 42s
6807:	learn: 0.0020322	total: 11m 44s	remaining: 5m 30s
7009:	learn: 0.0015320	total: 11m 44s	remaining: 5m
7004:	learn: 0.0015353	total: 11m 44s	remaining: 5m 1s
7137:	learn: 0.0014935	total: 11m 44s	remaining: 4m 42s
6485:	learn: 0.0014311	total: 11m 44s	remaining: 6m 21s
6808:	learn: 0.0020322	total: 11m 44s	remaining: 5m 30s
7010:	learn: 0.0015320	total: 11m 44s	remaining: 5m
7005:	learn: 0.0015353	total: 11m 44s	remaining: 5m 1s
7138:	learn: 0.0014935	total: 11m 44s	remaining: 4m 42s
6486:	learn: 0.0014311	total: 11m 44s	remaining: 6m 21s
6809:	learn: 0.0020322	total: 11m 44s	remaining: 5m 30s
7011:	learn: 0.0015320	total: 11m 44s	remaining: 5m
7006:	learn: 0.0015353	total: 11m 44s	remaining: 5m
7139:	learn: 0.0014935	total: 11m 44s	remaining: 4m 42s
6810:	learn: 0.0020322	total: 11m 44s	remaining: 5m 29s
6487:	learn: 0.0014308	total: 11m 44s	remaining: 6m 21s
7007:	learn: 0.0015353	total: 11m 44s	remaining: 5m
7140:	learn: 0.0014935	total: 11m 44s	remaining: 4m 42s
7012:	learn: 0.0015316	total: 11m 44s	remaining: 5m
6811:	learn: 0.0020322	total: 11m 44s	remaining: 5m 29s
7008:	learn: 0.0015348	total: 11m 44s	remaining: 5m
6488:	learn: 0.0014305	total: 11m 44s	remaining: 6m 21s
7141:	learn: 0.0014935	total: 11m 44s	remaining: 4m 41s
7013:	learn: 0.0015316	total: 11m 44s	remaining: 4m 59s
6812:	learn: 0.0020322	total: 11m 44s	remaining: 5m 29s
7142:	learn: 0.0014935	total: 11m 44s	remaining: 4m 41s
7009:	learn: 0.0015347	total: 11m 44s	remaining: 5m
6489:	learn: 0.0014302	total: 11m 44s	remaining: 6m 21s
7014:	learn: 0.0015316	total: 11m 44s	remaining: 4m 59s
6813:	learn: 0.0020322	total: 11m 44s	remaining: 5m 29s
7143:	learn: 0.0014935	total: 11m 44s	remaining: 4m 41s
7015:	learn: 0.0015316	total: 11m 44s	remaining: 4m 59s
7010:	learn: 0.0015342	total: 11m 44s	remaining: 5m
6490:	learn: 0.0014299	total: 11m 44s	remaining: 6m 21s
7144:	learn: 0.0014930	total: 11m 44s	remaining: 4m 41s
6814:	learn: 0.0020322	total: 11m 45s	remaining: 5m 29s
7011:	learn: 0.0015336	total: 11m 44s	remaining: 5m
6491:	learn: 0.0014296	total: 11m 45s	remaining: 6m 20s
7016:	learn: 0.0015316	total: 11m 44s	remaining: 4m 59s
7145:	learn: 0.0014930	total: 11m 45s	remaining: 4m 41s
6815:	learn: 0.0020322	total: 11m 45s	remaining: 5m 29s
7012:	learn: 0.0015332	total: 11m 45s	remaining: 5m
7017:	learn: 0.0015316	total: 11m 44s	remaining: 4m 59s
6492:	learn: 0.0014293	total: 11m 45s	remaining: 6m 20s
7146:	learn: 0.0014930	total: 11m 45s	remaining: 4m 41s
6816:	learn: 0.0020322	total: 11m 45s	remaining: 5m 29s
7013:	learn: 0.0015328	total: 11m 45s	remaining: 5m
7018:	learn: 0.0015316	total: 11m 44s	remaining: 4m 59s
6493:	learn: 0.0014293	total: 11m 45s	remaining: 6m 20s
7147:	learn: 0.0014930	total: 11m 45s	remaining: 4m 41s
6817:	learn: 0.0020322	total: 11m 45s	remaining: 5m 29s
7019:	learn: 0.0015316	total: 11m 45s	remaining: 4m 59s
6494:	learn: 0.0014289	total: 11m 45s	remaining: 6m 20s
7148:	learn: 0.0014930	total: 11m 45s	remaining: 4m 41s
7014:	learn: 0.0015324	total: 11m 45s	remaining: 5m
6818:	learn: 0.0020322	total: 11m 45s	remaining: 5m 29s
7020:	learn: 0.0015316	total: 11m 45s	remaining: 4m 59s
7149:	learn: 0.0014930	total: 11m 45s	remaining: 4m 41s
6495:	learn: 0.0014289	total: 11m 45s	remaining: 6m 20s
7015:	learn: 0.0015320	total: 11m 45s	remaining: 5m
7021:	learn: 0.0015316	total: 11m 45s	remaining: 4m 59s
7150:	learn: 0.0014930	total: 11m 45s	remaining: 4m 41s
6819:	learn: 0.0020321	total: 11m 45s	remaining: 5m 28s
6496:	learn: 0.0014283	total: 11m 45s	remaining: 6m 20s
7022:	learn: 0.0015316	total: 11m 45s	remaining: 4m 58s
7016:	learn: 0.0015316	total: 11m 45s	remaining: 4m 59s
7151:	learn: 0.0014930	total: 11m 45s	remaining: 4m 40s
7023:	learn: 0.0015316	total: 11m 45s	remaining: 4m 58s
6497:	learn: 0.0014281	total: 11m 45s	remaining: 6m 20s
6820:	learn: 0.0020321	total: 11m 45s	remaining: 5m 28s
7017:	learn: 0.0015310	total: 11m 45s	remaining: 4m 59s
7024:	learn: 0.0015312	total: 11m 45s	remaining: 4m 58s
7152:	learn: 0.0014930	total: 11m 45s	remaining: 4m 40s
6498:	learn: 0.0014276	total: 11m 45s	remaining: 6m 20s
6821:	learn: 0.0020321	total: 11m 45s	remaining: 5m 28s
7025:	learn: 0.0015312	total: 11m 45s	remaining: 4m 58s
7018:	learn: 0.0015305	total: 11m 45s	remaining: 4m 59s
7153:	learn: 0.0014930	total: 11m 45s	remaining: 4m 40s
6499:	learn: 0.0014271	total: 11m 45s	remaining: 6m 20s
6822:	learn: 0.0020321	total: 11m 45s	remaining: 5m 28s
7019:	learn: 0.0015301	total: 11m 45s	remaining: 4m 59s
7026:	learn: 0.0015312	total: 11m 45s	remaining: 4m 58s
6500:	learn: 0.0014271	total: 11m 45s	remaining: 6m 19s
7154:	learn: 0.0014930	total: 11m 45s	remaining: 4m 40s
7020:	learn: 0.0015297	total: 11m 45s	remaining: 4m 59s
7027:	learn: 0.0015312	total: 11m 45s	remaining: 4m 58s
6823:	learn: 0.0020321	total: 11m 46s	remaining: 5m 28s
7021:	learn: 0.0015294	total: 11m 46s	remaining: 4m 59s
6501:	learn: 0.0014268	total: 11m 46s	remaining: 6m 19s
7028:	learn: 0.0015312	total: 11m 45s	remaining: 4m 58s
7155:	learn: 0.0014925	total: 11m 46s	remaining: 4m 40s
6824:	learn: 0.0020321	total: 11m 46s	remaining: 5m 28s
7022:	learn: 0.0015287	total: 11m 46s	remaining: 4m 59s
6502:	learn: 0.0014268	total: 11m 46s	remaining: 6m 19s
7156:	learn: 0.0014925	total: 11m 46s	remaining: 4m 40s
7029:	learn: 0.0015309	total: 11m 45s	remaining: 4m 58s
6825:	learn: 0.0020321	total: 11m 46s	remaining: 5m 28s
7023:	learn: 0.0015281	total: 11m 46s	remaining: 4m 59s
6503:	learn: 0.0014265	total: 11m 46s	remaining: 6m 19s
7030:	learn: 0.0015309	total: 11m 46s	remaining: 4m 58s
7157:	learn: 0.0014925	total: 11m 46s	remaining: 4m 40s
7024:	learn: 0.0015276	total: 11m 46s	remaining: 4m 59s
6826:	learn: 0.0020321	total: 11m 46s	remaining: 5m 28s
6504:	learn: 0.0014261	total: 11m 46s	remaining: 6m 19s
7031:	learn: 0.0015309	total: 11m 46s	remaining: 4m 58s
7158:	learn: 0.0014922	total: 11m 46s	remaining: 4m 40s
7025:	learn: 0.0015270	total: 11m 46s	remaining: 4m 59s
6827:	learn: 0.0020321	total: 11m 46s	remaining: 5m 28s
6505:	learn: 0.0014260	total: 11m 46s	remaining: 6m 19s
7032:	learn: 0.0015308	total: 11m 46s	remaining: 4m 57s
7159:	learn: 0.0014921	total: 11m 46s	remaining: 4m 40s
6828:	learn: 0.0020321	total: 11m 46s	remaining: 5m 28s
7026:	learn: 0.0015266	total: 11m 46s	remaining: 4m 58s
7160:	learn: 0.0014921	total: 11m 46s	remaining: 4m 40s
7033:	learn: 0.0015308	total: 11m 46s	remaining: 4m 57s
6506:	learn: 0.0014260	total: 11m 46s	remaining: 6m 19s
6829:	learn: 0.0020321	total: 11m 46s	remaining: 5m 27s
7027:	learn: 0.0015262	total: 11m 46s	remaining: 4m 58s
7161:	learn: 0.0014921	total: 11m 46s	remaining: 4m 39s
7034:	learn: 0.0015308	total: 11m 46s	remaining: 4m 57s
6830:	learn: 0.0020321	total: 11m 46s	remaining: 5m 27s
6507:	learn: 0.0014256	total: 11m 46s	remaining: 6m 19s
7028:	learn: 0.0015257	total: 11m 46s	remaining: 4m 58s
7162:	learn: 0.0014921	total: 11m 46s	remaining: 4m 39s
7035:	learn: 0.0015308	total: 11m 46s	remaining: 4m 57s
6831:	learn: 0.0020321	total: 11m 46s	remaining: 5m 27s
6508:	learn: 0.0014256	total: 11m 46s	remaining: 6m 19s
7029:	learn: 0.0015253	total: 11m 46s	remaining: 4m 58s
7163:	learn: 0.0014921	total: 11m 46s	remaining: 4m 39s
7036:	learn: 0.0015308	total: 11m 46s	remaining: 4m 57s
6832:	learn: 0.0020321	total: 11m 46s	remaining: 5m 27s
6509:	learn: 0.0014256	total: 11m 46s	remaining: 6m 18s
7030:	learn: 0.0015247	total: 11m 46s	remaining: 4m 58s
7037:	learn: 0.0015308	total: 11m 46s	remaining: 4m 57s
7164:	learn: 0.0014921	total: 11m 46s	remaining: 4m 39s
6833:	learn: 0.0020321	total: 11m 47s	remaining: 5m 27s
6510:	learn: 0.0014256	total: 11m 46s	remaining: 6m 18s
7031:	learn: 0.0015242	total: 11m 46s	remaining: 4m 58s
7038:	learn: 0.0015308	total: 11m 46s	remaining: 4m 57s
7165:	learn: 0.0014921	total: 11m 47s	remaining: 4m 39s
6511:	learn: 0.0014256	total: 11m 47s	remaining: 6m 18s
6834:	learn: 0.0020321	total: 11m 47s	remaining: 5m 27s
7032:	learn: 0.0015236	total: 11m 47s	remaining: 4m 58s
7039:	learn: 0.0015308	total: 11m 46s	remaining: 4m 57s
6512:	learn: 0.0014256	total: 11m 47s	remaining: 6m 18s
7166:	learn: 0.0014921	total: 11m 47s	remaining: 4m 39s
7040:	learn: 0.0015308	total: 11m 46s	remaining: 4m 57s
7033:	learn: 0.0015232	total: 11m 47s	remaining: 4m 58s
6835:	learn: 0.0020321	total: 11m 47s	remaining: 5m 27s
6513:	learn: 0.0014253	total: 11m 47s	remaining: 6m 18s
7167:	learn: 0.0014921	total: 11m 47s	remaining: 4m 39s
7041:	learn: 0.0015308	total: 11m 47s	remaining: 4m 57s
7034:	learn: 0.0015226	total: 11m 47s	remaining: 4m 58s
6836:	learn: 0.0020321	total: 11m 47s	remaining: 5m 27s
6514:	learn: 0.0014252	total: 11m 47s	remaining: 6m 18s
7042:	learn: 0.0015308	total: 11m 47s	remaining: 4m 56s
6837:	learn: 0.0020321	total: 11m 47s	remaining: 5m 27s
7168:	learn: 0.0014921	total: 11m 47s	remaining: 4m 39s
7035:	learn: 0.0015226	total: 11m 47s	remaining: 4m 58s
6515:	learn: 0.0014250	total: 11m 47s	remaining: 6m 18s
6838:	learn: 0.0020321	total: 11m 47s	remaining: 5m 27s
7043:	learn: 0.0015308	total: 11m 47s	remaining: 4m 56s
7169:	learn: 0.0014921	total: 11m 47s	remaining: 4m 39s
6516:	learn: 0.0014247	total: 11m 47s	remaining: 6m 18s
7036:	learn: 0.0015223	total: 11m 47s	remaining: 4m 57s
7044:	learn: 0.0015308	total: 11m 47s	remaining: 4m 56s
6839:	learn: 0.0020321	total: 11m 47s	remaining: 5m 26s
7170:	learn: 0.0014921	total: 11m 47s	remaining: 4m 39s
6517:	learn: 0.0014244	total: 11m 47s	remaining: 6m 18s
7045:	learn: 0.0015305	total: 11m 47s	remaining: 4m 56s
7037:	learn: 0.0015218	total: 11m 47s	remaining: 4m 57s
6840:	learn: 0.0020321	total: 11m 47s	remaining: 5m 26s
7171:	learn: 0.0014921	total: 11m 47s	remaining: 4m 39s
6518:	learn: 0.0014241	total: 11m 47s	remaining: 6m 17s
7046:	learn: 0.0015304	total: 11m 47s	remaining: 4m 56s
7038:	learn: 0.0015214	total: 11m 47s	remaining: 4m 57s
7172:	learn: 0.0014921	total: 11m 47s	remaining: 4m 38s
6841:	learn: 0.0020321	total: 11m 47s	remaining: 5m 26s
7047:	learn: 0.0015304	total: 11m 47s	remaining: 4m 56s
6519:	learn: 0.0014241	total: 11m 47s	remaining: 6m 17s
7039:	learn: 0.0015208	total: 11m 47s	remaining: 4m 57s
7173:	learn: 0.0014921	total: 11m 47s	remaining: 4m 38s
6842:	learn: 0.0020321	total: 11m 47s	remaining: 5m 26s
7048:	learn: 0.0015304	total: 11m 47s	remaining: 4m 56s
7040:	learn: 0.0015204	total: 11m 47s	remaining: 4m 57s
6520:	learn: 0.0014241	total: 11m 47s	remaining: 6m 17s
7174:	learn: 0.0014921	total: 11m 47s	remaining: 4m 38s
7049:	learn: 0.0015304	total: 11m 47s	remaining: 4m 56s
6843:	learn: 0.0020321	total: 11m 48s	remaining: 5m 26s
6521:	learn: 0.0014240	total: 11m 48s	remaining: 6m 17s
7041:	learn: 0.0015198	total: 11m 48s	remaining: 4m 57s
7175:	learn: 0.0014921	total: 11m 48s	remaining: 4m 38s
6844:	learn: 0.0020321	total: 11m 48s	remaining: 5m 26s
6522:	learn: 0.0014239	total: 11m 48s	remaining: 6m 17s
7176:	learn: 0.0014921	total: 11m 48s	remaining: 4m 38s
7042:	learn: 0.0015195	total: 11m 48s	remaining: 4m 57s
7050:	learn: 0.0015304	total: 11m 47s	remaining: 4m 56s
6845:	learn: 0.0020321	total: 11m 48s	remaining: 5m 26s
6523:	learn: 0.0014240	total: 11m 48s	remaining: 6m 17s
7177:	learn: 0.0014918	total: 11m 48s	remaining: 4m 38s
7043:	learn: 0.0015192	total: 11m 48s	remaining: 4m 57s
7051:	learn: 0.0015304	total: 11m 48s	remaining: 4m 56s
6846:	learn: 0.0020321	total: 11m 48s	remaining: 5m 26s
6524:	learn: 0.0014237	total: 11m 48s	remaining: 6m 17s
7044:	learn: 0.0015187	total: 11m 48s	remaining: 4m 57s
7178:	learn: 0.0014918	total: 11m 48s	remaining: 4m 38s
7052:	learn: 0.0015304	total: 11m 48s	remaining: 4m 55s
6525:	learn: 0.0014237	total: 11m 48s	remaining: 6m 17s
6847:	learn: 0.0020321	total: 11m 48s	remaining: 5m 26s
7179:	learn: 0.0014917	total: 11m 48s	remaining: 4m 38s
7045:	learn: 0.0015181	total: 11m 48s	remaining: 4m 57s
7053:	learn: 0.0015304	total: 11m 48s	remaining: 4m 55s
6848:	learn: 0.0020321	total: 11m 48s	remaining: 5m 25s
7180:	learn: 0.0014917	total: 11m 48s	remaining: 4m 38s
6526:	learn: 0.0014234	total: 11m 48s	remaining: 6m 17s
7046:	learn: 0.0015177	total: 11m 48s	remaining: 4m 56s
7054:	learn: 0.0015304	total: 11m 48s	remaining: 4m 55s
6849:	learn: 0.0020321	total: 11m 48s	remaining: 5m 25s
7181:	learn: 0.0014917	total: 11m 48s	remaining: 4m 38s
6527:	learn: 0.0014234	total: 11m 48s	remaining: 6m 16s
7055:	learn: 0.0015304	total: 11m 48s	remaining: 4m 55s
7047:	learn: 0.0015173	total: 11m 48s	remaining: 4m 56s
6850:	learn: 0.0020321	total: 11m 48s	remaining: 5m 25s
7182:	learn: 0.0014917	total: 11m 48s	remaining: 4m 37s
7056:	learn: 0.0015300	total: 11m 48s	remaining: 4m 55s
7048:	learn: 0.0015168	total: 11m 48s	remaining: 4m 56s
6851:	learn: 0.0020321	total: 11m 48s	remaining: 5m 25s
6528:	learn: 0.0014230	total: 11m 48s	remaining: 6m 16s
7183:	learn: 0.0014917	total: 11m 48s	remaining: 4m 37s
7184:	learn: 0.0014917	total: 11m 48s	remaining: 4m 37s
7057:	learn: 0.0015296	total: 11m 48s	remaining: 4m 55s
7049:	learn: 0.0015164	total: 11m 48s	remaining: 4m 56s
6852:	learn: 0.0020321	total: 11m 48s	remaining: 5m 25s
6529:	learn: 0.0014229	total: 11m 48s	remaining: 6m 16s
7185:	learn: 0.0014917	total: 11m 48s	remaining: 4m 37s

7058:	learn: 0.0015296	total: 11m 48s	remaining: 4m 55s
7050:	learn: 0.0015158	total: 11m 49s	remaining: 4m 56s
6853:	learn: 0.0020321	total: 11m 49s	remaining: 5m 25s
7186:	learn: 0.0014917	total: 11m 48s	remaining: 4m 37s
7059:	learn: 0.0015296	total: 11m 48s	remaining: 4m 55s
6530:	learn: 0.0014229	total: 11m 49s	remaining: 6m 16s
6854:	learn: 0.0020321	total: 11m 49s	remaining: 5m 25s
7051:	learn: 0.0015158	total: 11m 49s	remaining: 4m 56s
7187:	learn: 0.0014917	total: 11m 49s	remaining: 4m 37s
7060:	learn: 0.0015296	total: 11m 48s	remaining: 4m 55s
6531:	learn: 0.0014226	total: 11m 49s	remaining: 6m 16s
6855:	learn: 0.0020321	total: 11m 49s	remaining: 5m 25s
7052:	learn: 0.0015155	total: 11m 49s	remaining: 4m 56s
7188:	learn: 0.0014917	total: 11m 49s	remaining: 4m 37s
7061:	learn: 0.0015296	total: 11m 49s	remaining: 4m 54s
6856:	learn: 0.0020321	total: 11m 49s	remaining: 5m 25s
6532:	learn: 0.0014226	total: 11m 49s	remaining: 6m 16s
7053:	learn: 0.0015151	total: 11m 49s	remaining: 4m 56s
7189:	learn: 0.0014917	total: 11m 49s	remaining: 4m 37s
7062:	learn: 0.0015296	total: 11m 49s	remaining: 4m 54s
6533:	learn: 0.0014226	total: 11m 49s	remaining: 6m 16s
7190:	learn: 0.0014917	total: 11m 49s	remaining: 4m 37s
6857:	learn: 0.0020321	total: 11m 49s	remaining: 5m 25s
7054:	learn: 0.0015148	total: 11m 49s	remaining: 4m 56s
7063:	learn: 0.0015296	total: 11m 49s	remaining: 4m 54s
6534:	learn: 0.0014226	total: 11m 49s	remaining: 6m 16s
7191:	learn: 0.0014917	total: 11m 49s	remaining: 4m 36s
7055:	learn: 0.0015142	total: 11m 49s	remaining: 4m 56s
7064:	learn: 0.0015296	total: 11m 49s	remaining: 4m 54s
6858:	learn: 0.0020321	total: 11m 49s	remaining: 5m 24s
6535:	learn: 0.0014221	total: 11m 49s	remaining: 6m 16s
7192:	learn: 0.0014917	total: 11m 49s	remaining: 4m 36s
7056:	learn: 0.0015139	total: 11m 49s	remaining: 4m 55s
7065:	learn: 0.0015296	total: 11m 49s	remaining: 4m 54s
6859:	learn: 0.0020321	total: 11m 49s	remaining: 5m 24s
7193:	learn: 0.0014917	total: 11m 49s	remaining: 4m 36s
7057:	learn: 0.0015134	total: 11m 49s	remaining: 4m 55s
6536:	learn: 0.0014221	total: 11m 49s	remaining: 6m 15s
7066:	learn: 0.0015296	total: 11m 49s	remaining: 4m 54s
7194:	learn: 0.0014914	total: 11m 49s	remaining: 4m 36s
6860:	learn: 0.0020321	total: 11m 49s	remaining: 5m 24s
7058:	learn: 0.0015129	total: 11m 49s	remaining: 4m 55s
6537:	learn: 0.0014220	total: 11m 49s	remaining: 6m 15s
7067:	learn: 0.0015296	total: 11m 49s	remaining: 4m 54s
6861:	learn: 0.0020321	total: 11m 49s	remaining: 5m 24s
7195:	learn: 0.0014913	total: 11m 49s	remaining: 4m 36s
7059:	learn: 0.0015125	total: 11m 49s	remaining: 4m 55s
6538:	learn: 0.0014220	total: 11m 49s	remaining: 6m 15s
6862:	learn: 0.0020321	total: 11m 49s	remaining: 5m 24s
7068:	learn: 0.0015296	total: 11m 49s	remaining: 4m 54s
7196:	learn: 0.0014912	total: 11m 49s	remaining: 4m 36s
7060:	learn: 0.0015119	total: 11m 49s	remaining: 4m 55s
6539:	learn: 0.0014216	total: 11m 50s	remaining: 6m 15s
6863:	learn: 0.0020321	total: 11m 50s	remaining: 5m 24s
7197:	learn: 0.0014912	total: 11m 49s	remaining: 4m 36s
7069:	learn: 0.0015296	total: 11m 49s	remaining: 4m 54s
7061:	learn: 0.0015115	total: 11m 50s	remaining: 4m 55s
7198:	learn: 0.0014912	total: 11m 50s	remaining: 4m 36s
6864:	learn: 0.0020321	total: 11m 50s	remaining: 5m 24s
6540:	learn: 0.0014216	total: 11m 50s	remaining: 6m 15s
7070:	learn: 0.0015296	total: 11m 49s	remaining: 4m 54s
7062:	learn: 0.0015110	total: 11m 50s	remaining: 4m 55s
6865:	learn: 0.0020321	total: 11m 50s	remaining: 5m 24s
6541:	learn: 0.0014216	total: 11m 50s	remaining: 6m 15s
7199:	learn: 0.0014911	total: 11m 50s	remaining: 4m 36s
7071:	learn: 0.0015296	total: 11m 50s	remaining: 4m 53s
6542:	learn: 0.0014216	total: 11m 50s	remaining: 6m 15s
7063:	learn: 0.0015106	total: 11m 50s	remaining: 4m 55s
6866:	learn: 0.0020321	total: 11m 50s	remaining: 5m 24s
7200:	learn: 0.0014911	total: 11m 50s	remaining: 4m 36s
7072:	learn: 0.0015296	total: 11m 50s	remaining: 4m 53s
6543:	learn: 0.0014216	total: 11m 50s	remaining: 6m 15s
7064:	learn: 0.0015101	total: 11m 50s	remaining: 4m 55s
6867:	learn: 0.0020321	total: 11m 50s	remaining: 5m 24s
7073:	learn: 0.0015296	total: 11m 50s	remaining: 4m 53s
7201:	learn: 0.0014911	total: 11m 50s	remaining: 4m 35s
6544:	learn: 0.0014216	total: 11m 50s	remaining: 6m 15s
6868:	learn: 0.0020321	total: 11m 50s	remaining: 5m 23s
7065:	learn: 0.0015097	total: 11m 50s	remaining: 4m 55s
7074:	learn: 0.0015296	total: 11m 50s	remaining: 4m 53s
7202:	learn: 0.0014911	total: 11m 50s	remaining: 4m 35s
6545:	learn: 0.0014216	total: 11m 50s	remaining: 6m 14s
6869:	learn: 0.0020321	total: 11m 50s	remaining: 5m 23s
7066:	learn: 0.0015093	total: 11m 50s	remaining: 4m 54s
7075:	learn: 0.0015296	total: 11m 50s	remaining: 4m 53s
7203:	learn: 0.0014911	total: 11m 50s	remaining: 4m 35s
6870:	learn: 0.0020321	total: 11m 50s	remaining: 5m 23s
6546:	learn: 0.0014213	total: 11m 50s	remaining: 6m 14s
7067:	learn: 0.0015088	total: 11m 50s	remaining: 4m 54s
7204:	learn: 0.0014911	total: 11m 50s	remaining: 4m 35s
7076:	learn: 0.0015296	total: 11m 50s	remaining: 4m 53s
6871:	learn: 0.0020321	total: 11m 50s	remaining: 5m 23s
6547:	learn: 0.0014213	total: 11m 50s	remaining: 6m 14s
7068:	learn: 0.0015088	total: 11m 50s	remaining: 4m 54s
7205:	learn: 0.0014911	total: 11m 50s	remaining: 4m 35s
7077:	learn: 0.0015293	total: 11m 50s	remaining: 4m 53s
6872:	learn: 0.0020321	total: 11m 50s	remaining: 5m 23s
7069:	learn: 0.0015088	total: 11m 50s	remaining: 4m 54s
6548:	learn: 0.0014213	total: 11m 50s	remaining: 6m 14s
7206:	learn: 0.0014911	total: 11m 50s	remaining: 4m 35s
7078:	learn: 0.0015293	total: 11m 50s	remaining: 4m 53s
6873:	learn: 0.0020321	total: 11m 51s	remaining: 5m 23s
6549:	learn: 0.0014211	total: 11m 51s	remaining: 6m 14s
7070:	learn: 0.0015088	total: 11m 51s	remaining: 4m 54s
7207:	learn: 0.0014911	total: 11m 51s	remaining: 4m 35s
7079:	learn: 0.0015293	total: 11m 50s	remaining: 4m 53s
6874:	learn: 0.0020321	total: 11m 51s	remaining: 5m 23s
7071:	learn: 0.0015088	total: 11m 51s	remaining: 4m 54s
6550:	learn: 0.0014207	total: 11m 51s	remaining: 6m 14s
7080:	learn: 0.0015293	total: 11m 50s	remaining: 4m 53s
7208:	learn: 0.0014911	total: 11m 51s	remaining: 4m 35s
6875:	learn: 0.0020321	total: 11m 51s	remaining: 5m 23s
7072:	learn: 0.0015085	total: 11m 51s	remaining: 4m 54s
6551:	learn: 0.0014205	total: 11m 51s	remaining: 6m 14s
7081:	learn: 0.0015293	total: 11m 51s	remaining: 4m 52s
7209:	learn: 0.0014911	total: 11m 51s	remaining: 4m 35s
6876:	learn: 0.0020321	total: 11m 51s	remaining: 5m 23s
7073:	learn: 0.0015079	total: 11m 51s	remaining: 4m 54s
7082:	learn: 0.0015289	total: 11m 51s	remaining: 4m 52s
7210:	learn: 0.0014911	total: 11m 51s	remaining: 4m 35s
6552:	learn: 0.0014205	total: 11m 51s	remaining: 6m 14s
6877:	learn: 0.0020321	total: 11m 51s	remaining: 5m 22s
7074:	learn: 0.0015075	total: 11m 51s	remaining: 4m 54s
7083:	learn: 0.0015285	total: 11m 51s	remaining: 4m 52s
6553:	learn: 0.0014205	total: 11m 51s	remaining: 6m 14s
7211:	learn: 0.0014911	total: 11m 51s	remaining: 4m 35s
6878:	learn: 0.0020321	total: 11m 51s	remaining: 5m 22s
7075:	learn: 0.0015071	total: 11m 51s	remaining: 4m 54s
7084:	learn: 0.0015285	total: 11m 51s	remaining: 4m 52s
7212:	learn: 0.0014911	total: 11m 51s	remaining: 4m 34s
6554:	learn: 0.0014205	total: 11m 51s	remaining: 6m 13s
7076:	learn: 0.0015064	total: 11m 51s	remaining: 4m 53s
6879:	learn: 0.0020321	total: 11m 51s	remaining: 5m 22s
7085:	learn: 0.0015285	total: 11m 51s	remaining: 4m 52s
6880:	learn: 0.0020321	total: 11m 51s	remaining: 5m 22s
7213:	learn: 0.0014910	total: 11m 51s	remaining: 4m 34s
6555:	learn: 0.0014200	total: 11m 51s	remaining: 6m 13s
7077:	learn: 0.0015060	total: 11m 51s	remaining: 4m 53s
7086:	learn: 0.0015285	total: 11m 51s	remaining: 4m 52s
6881:	learn: 0.0020321	total: 11m 51s	remaining: 5m 22s
7214:	learn: 0.0014910	total: 11m 51s	remaining: 4m 34s
7078:	learn: 0.0015057	total: 11m 51s	remaining: 4m 53s
6556:	learn: 0.0014200	total: 11m 51s	remaining: 6m 13s
7215:	learn: 0.0014910	total: 11m 51s	remaining: 4m 34s
7087:	learn: 0.0015285	total: 11m 51s	remaining: 4m 52s
6882:	learn: 0.0020321	total: 11m 51s	remaining: 5m 22s
7079:	learn: 0.0015057	total: 11m 51s	remaining: 4m 53s
6557:	learn: 0.0014200	total: 11m 51s	remaining: 6m 13s
7216:	learn: 0.0014910	total: 11m 51s	remaining: 4m 34s
6883:	learn: 0.0020320	total: 11m 51s	remaining: 5m 22s
7088:	learn: 0.0015285	total: 11m 51s	remaining: 4m 52s
7080:	learn: 0.0015057	total: 11m 52s	remaining: 4m 53s
7217:	learn: 0.0014910	total: 11m 51s	remaining: 4m 34s
6558:	learn: 0.0014200	total: 11m 52s	remaining: 6m 13s
6884:	learn: 0.0020320	total: 11m 52s	remaining: 5m 22s
7081:	learn: 0.0015057	total: 11m 52s	remaining: 4m 53s
7218:	learn: 0.0014910	total: 11m 52s	remaining: 4m 34s
7089:	learn: 0.0015285	total: 11m 51s	remaining: 4m 52s
6559:	learn: 0.0014199	total: 11m 52s	remaining: 6m 13s
6885:	learn: 0.0020320	total: 11m 52s	remaining: 5m 22s
7082:	learn: 0.0015057	total: 11m 52s	remaining: 4m 53s
7219:	learn: 0.0014910	total: 11m 52s	remaining: 4m 34s
7090:	learn: 0.0015283	total: 11m 52s	remaining: 4m 52s
6886:	learn: 0.0020320	total: 11m 52s	remaining: 5m 21s
6560:	learn: 0.0014199	total: 11m 52s	remaining: 6m 13s
7083:	learn: 0.0015057	total: 11m 52s	remaining: 4m 53s
7220:	learn: 0.0014906	total: 11m 52s	remaining: 4m 34s
7091:	learn: 0.0015283	total: 11m 52s	remaining: 4m 51s
6887:	learn: 0.0020320	total: 11m 52s	remaining: 5m 21s
6561:	learn: 0.0014198	total: 11m 52s	remaining: 6m 13s
7221:	learn: 0.0014906	total: 11m 52s	remaining: 4m 34s
7084:	learn: 0.0015057	total: 11m 52s	remaining: 4m 53s
7092:	learn: 0.0015283	total: 11m 52s	remaining: 4m 51s
6562:	learn: 0.0014196	total: 11m 52s	remaining: 6m 13s
6888:	learn: 0.0020320	total: 11m 52s	remaining: 5m 21s
7222:	learn: 0.0014906	total: 11m 52s	remaining: 4m 33s
7085:	learn: 0.0015057	total: 11m 52s	remaining: 4m 52s
7093:	learn: 0.0015283	total: 11m 52s	remaining: 4m 51s
6563:	learn: 0.0014194	total: 11m 52s	remaining: 6m 12s
7094:	learn: 0.0015283	total: 11m 52s	remaining: 4m 51s
6889:	learn: 0.0020320	total: 11m 52s	remaining: 5m 21s
7223:	learn: 0.0014906	total: 11m 52s	remaining: 4m 33s
7086:	learn: 0.0015057	total: 11m 52s	remaining: 4m 52s
6564:	learn: 0.0014194	total: 11m 52s	remaining: 6m 12s
7095:	learn: 0.0015283	total: 11m 52s	remaining: 4m 51s
7224:	learn: 0.0014906	total: 11m 52s	remaining: 4m 33s
6890:	learn: 0.0020320	total: 11m 52s	remaining: 5m 21s
7096:	learn: 0.0015280	total: 11m 52s	remaining: 4m 51s
6565:	learn: 0.0014194	total: 11m 52s	remaining: 6m 12s
7087:	learn: 0.0015057	total: 11m 52s	remaining: 4m 52s
7225:	learn: 0.0014906	total: 11m 52s	remaining: 4m 33s
7097:	learn: 0.0015274	total: 11m 52s	remaining: 4m 51s
6891:	learn: 0.0020320	total: 11m 52s	remaining: 5m 21s
7088:	learn: 0.0015057	total: 11m 52s	remaining: 4m 52s
6566:	learn: 0.0014191	total: 11m 52s	remaining: 6m 12s
7226:	learn: 0.0014906	total: 11m 52s	remaining: 4m 33s
6892:	learn: 0.0020320	total: 11m 52s	remaining: 5m 21s
7089:	learn: 0.0015057	total: 11m 52s	remaining: 4m 52s
7098:	learn: 0.0015274	total: 11m 52s	remaining: 4m 51s
6567:	learn: 0.0014187	total: 11m 52s	remaining: 6m 12s
6893:	learn: 0.0020320	total: 11m 53s	remaining: 5m 21s
7227:	learn: 0.0014906	total: 11m 52s	remaining: 4m 33s
7099:	learn: 0.0015274	total: 11m 52s	remaining: 4m 51s
7090:	learn: 0.0015057	total: 11m 53s	remaining: 4m 52s
6568:	learn: 0.0014185	total: 11m 53s	remaining: 6m 12s
6894:	learn: 0.0020318	total: 11m 53s	remaining: 5m 21s
7228:	learn: 0.0014906	total: 11m 53s	remaining: 4m 33s
7091:	learn: 0.0015057	total: 11m 53s	remaining: 4m 52s
6569:	learn: 0.0014185	total: 11m 53s	remaining: 6m 12s
7100:	learn: 0.0015274	total: 11m 52s	remaining: 4m 51s
6895:	learn: 0.0020319	total: 11m 53s	remaining: 5m 21s
7229:	learn: 0.0014906	total: 11m 53s	remaining: 4m 33s
7092:	learn: 0.0015053	total: 11m 53s	remaining: 4m 52s
6896:	learn: 0.0020319	total: 11m 53s	remaining: 5m 20s
7101:	learn: 0.0015273	total: 11m 53s	remaining: 4m 50s
6570:	learn: 0.0014185	total: 11m 53s	remaining: 6m 12s
7230:	learn: 0.0014906	total: 11m 53s	remaining: 4m 33s
6897:	learn: 0.0020319	total: 11m 53s	remaining: 5m 20s
7093:	learn: 0.0015049	total: 11m 53s	remaining: 4m 52s
7102:	learn: 0.0015273	total: 11m 53s	remaining: 4m 50s
7231:	learn: 0.0014905	total: 11m 53s	remaining: 4m 33s
6571:	learn: 0.0014185	total: 11m 53s	remaining: 6m 12s
6898:	learn: 0.0020319	total: 11m 53s	remaining: 5m 20s
7094:	learn: 0.0015044	total: 11m 53s	remaining: 4m 52s
7103:	learn: 0.0015272	total: 11m 53s	remaining: 4m 50s
6572:	learn: 0.0014185	total: 11m 53s	remaining: 6m 12s
7232:	learn: 0.0014905	total: 11m 53s	remaining: 4m 32s
7095:	learn: 0.0015040	total: 11m 53s	remaining: 4m 52s
7104:	learn: 0.0015272	total: 11m 53s	remaining: 4m 50s
6899:	learn: 0.0020318	total: 11m 53s	remaining: 5m 20s
7096:	learn: 0.0015035	total: 11m 53s	remaining: 4m 51s
7233:	learn: 0.0014905	total: 11m 53s	remaining: 4m 32s
6573:	learn: 0.0014183	total: 11m 53s	remaining: 6m 11s
7105:	learn: 0.0015272	total: 11m 53s	remaining: 4m 50s
7234:	learn: 0.0014905	total: 11m 53s	remaining: 4m 32s
7097:	learn: 0.0015031	total: 11m 53s	remaining: 4m 51s
6900:	learn: 0.0020318	total: 11m 53s	remaining: 5m 20s
6574:	learn: 0.0014181	total: 11m 53s	remaining: 6m 11s
7106:	learn: 0.0015272	total: 11m 53s	remaining: 4m 50s
7098:	learn: 0.0015027	total: 11m 53s	remaining: 4m 51s
7235:	learn: 0.0014905	total: 11m 53s	remaining: 4m 32s
6901:	learn: 0.0020319	total: 11m 53s	remaining: 5m 20s
6575:	learn: 0.0014177	total: 11m 53s	remaining: 6m 11s
7107:	learn: 0.0015272	total: 11m 53s	remaining: 4m 50s
7236:	learn: 0.0014905	total: 11m 53s	remaining: 4m 32s
7099:	learn: 0.0015022	total: 11m 53s	remaining: 4m 51s
6576:	learn: 0.0014175	total: 11m 53s	remaining: 6m 11s
6902:	learn: 0.0020318	total: 11m 53s	remaining: 5m 20s
7108:	learn: 0.0015272	total: 11m 53s	remaining: 4m 50s
7237:	learn: 0.0014905	total: 11m 53s	remaining: 4m 32s
7100:	learn: 0.0015022	total: 11m 53s	remaining: 4m 51s
6577:	learn: 0.0014175	total: 11m 54s	remaining: 6m 11s
6903:	learn: 0.0020318	total: 11m 54s	remaining: 5m 20s
7238:	learn: 0.0014905	total: 11m 53s	remaining: 4m 32s
7101:	learn: 0.0015022	total: 11m 54s	remaining: 4m 51s
7109:	learn: 0.0015272	total: 11m 53s	remaining: 4m 50s
6578:	learn: 0.0014174	total: 11m 54s	remaining: 6m 11s
6904:	learn: 0.0020318	total: 11m 54s	remaining: 5m 20s
7239:	learn: 0.0014905	total: 11m 54s	remaining: 4m 32s
7102:	learn: 0.0015022	total: 11m 54s	remaining: 4m 51s
6905:	learn: 0.0020318	total: 11m 54s	remaining: 5m 19s
6579:	learn: 0.0014174	total: 11m 54s	remaining: 6m 11s
7110:	learn: 0.0015272	total: 11m 53s	remaining: 4m 50s
7240:	learn: 0.0014904	total: 11m 54s	remaining: 4m 32s
7103:	learn: 0.0015022	total: 11m 54s	remaining: 4m 51s
6906:	learn: 0.0020318	total: 11m 54s	remaining: 5m 19s
7111:	learn: 0.0015272	total: 11m 54s	remaining: 4m 49s
6580:	learn: 0.0014174	total: 11m 54s	remaining: 6m 11s
7241:	learn: 0.0014905	total: 11m 54s	remaining: 4m 32s
6907:	learn: 0.0020318	total: 11m 54s	remaining: 5m 19s
7104:	learn: 0.0015016	total: 11m 54s	remaining: 4m 51s
6908:	learn: 0.0020318	total: 11m 54s	remaining: 5m 19s
7242:	learn: 0.0014904	total: 11m 54s	remaining: 4m 31s
6581:	learn: 0.0014174	total: 11m 54s	remaining: 6m 11s
7112:	learn: 0.0015272	total: 11m 54s	remaining: 4m 49s
7105:	learn: 0.0015015	total: 11m 54s	remaining: 4m 50s
7243:	learn: 0.0014904	total: 11m 54s	remaining: 4m 31s
6909:	learn: 0.0020318	total: 11m 54s	remaining: 5m 19s
7106:	learn: 0.0015015	total: 11m 54s	remaining: 4m 50s
6582:	learn: 0.0014171	total: 11m 54s	remaining: 6m 10s
7113:	learn: 0.0015272	total: 11m 54s	remaining: 4m 49s
7244:	learn: 0.0014904	total: 11m 54s	remaining: 4m 31s
6910:	learn: 0.0020318	total: 11m 54s	remaining: 5m 19s
7107:	learn: 0.0015015	total: 11m 54s	remaining: 4m 50s
7114:	learn: 0.0015272	total: 11m 54s	remaining: 4m 49s
7245:	learn: 0.0014902	total: 11m 54s	remaining: 4m 31s
6583:	learn: 0.0014171	total: 11m 54s	remaining: 6m 10s
7108:	learn: 0.0015015	total: 11m 54s	remaining: 4m 50s
6911:	learn: 0.0020318	total: 11m 54s	remaining: 5m 19s
7115:	learn: 0.0015272	total: 11m 54s	remaining: 4m 49s
6584:	learn: 0.0014171	total: 11m 54s	remaining: 6m 10s
7246:	learn: 0.0014898	total: 11m 54s	remaining: 4m 31s

7109:	learn: 0.0015015	total: 11m 54s	remaining: 4m 50s
6912:	learn: 0.0020318	total: 11m 54s	remaining: 5m 19s
7247:	learn: 0.0014898	total: 11m 54s	remaining: 4m 31s
7110:	learn: 0.0015010	total: 11m 54s	remaining: 4m 50s
7116:	learn: 0.0015272	total: 11m 54s	remaining: 4m 49s
6585:	learn: 0.0014171	total: 11m 54s	remaining: 6m 10s
7248:	learn: 0.0014898	total: 11m 54s	remaining: 4m 31s
6913:	learn: 0.0020318	total: 11m 55s	remaining: 5m 19s
7111:	learn: 0.0015007	total: 11m 54s	remaining: 4m 50s
7117:	learn: 0.0015272	total: 11m 54s	remaining: 4m 49s
6586:	learn: 0.0014171	total: 11m 55s	remaining: 6m 10s
6914:	learn: 0.0020318	total: 11m 55s	remaining: 5m 19s
7112:	learn: 0.0015007	total: 11m 55s	remaining: 4m 50s
7118:	learn: 0.0015272	total: 11m 54s	remaining: 4m 49s
7249:	learn: 0.0014898	total: 11m 55s	remaining: 4m 31s
6587:	learn: 0.0014171	total: 11m 55s	remaining: 6m 10s
6915:	learn: 0.0020318	total: 11m 55s	remaining: 5m 18s
7119:	learn: 0.0015272	total: 11m 54s	remaining: 4m 49s
7113:	learn: 0.0015002	total: 11m 55s	remaining: 4m 50s
6588:	learn: 0.0014167	total: 11m 55s	remaining: 6m 10s
7250:	learn: 0.0014898	total: 11m 55s	remaining: 4m 31s
6916:	learn: 0.0020318	total: 11m 55s	remaining: 5m 18s
7120:	learn: 0.0015272	total: 11m 55s	remaining: 4m 49s
6589:	learn: 0.0014167	total: 11m 55s	remaining: 6m 10s
7251:	learn: 0.0014898	total: 11m 55s	remaining: 4m 31s
7114:	learn: 0.0015002	total: 11m 55s	remaining: 4m 50s
7121:	learn: 0.0015272	total: 11m 55s	remaining: 4m 48s
6917:	learn: 0.0020318	total: 11m 55s	remaining: 5m 18s
7252:	learn: 0.0014895	total: 11m 55s	remaining: 4m 30s
7115:	learn: 0.0015002	total: 11m 55s	remaining: 4m 49s
6590:	learn: 0.0014167	total: 11m 55s	remaining: 6m 10s
7122:	learn: 0.0015271	total: 11m 55s	remaining: 4m 48s
6918:	learn: 0.0020318	total: 11m 55s	remaining: 5m 18s
7253:	learn: 0.0014895	total: 11m 55s	remaining: 4m 30s
7116:	learn: 0.0015002	total: 11m 55s	remaining: 4m 49s
6919:	learn: 0.0020318	total: 11m 55s	remaining: 5m 18s
6591:	learn: 0.0014166	total: 11m 55s	remaining: 6m 9s
7123:	learn: 0.0015271	total: 11m 55s	remaining: 4m 48s
7254:	learn: 0.0014895	total: 11m 55s	remaining: 4m 30s
7117:	learn: 0.0015002	total: 11m 55s	remaining: 4m 49s
6920:	learn: 0.0020318	total: 11m 55s	remaining: 5m 18s
7124:	learn: 0.0015267	total: 11m 55s	remaining: 4m 48s
7255:	learn: 0.0014895	total: 11m 55s	remaining: 4m 30s
6592:	learn: 0.0014164	total: 11m 55s	remaining: 6m 9s
7118:	learn: 0.0015001	total: 11m 55s	remaining: 4m 49s
6921:	learn: 0.0020318	total: 11m 55s	remaining: 5m 18s
7125:	learn: 0.0015267	total: 11m 55s	remaining: 4m 48s
7256:	learn: 0.0014895	total: 11m 55s	remaining: 4m 30s
6593:	learn: 0.0014164	total: 11m 55s	remaining: 6m 9s
7119:	learn: 0.0015001	total: 11m 55s	remaining: 4m 49s
6922:	learn: 0.0020318	total: 11m 55s	remaining: 5m 18s
7126:	learn: 0.0015267	total: 11m 55s	remaining: 4m 48s
7257:	learn: 0.0014890	total: 11m 55s	remaining: 4m 30s
7120:	learn: 0.0015001	total: 11m 55s	remaining: 4m 49s
6594:	learn: 0.0014164	total: 11m 55s	remaining: 6m 9s
6923:	learn: 0.0020318	total: 11m 55s	remaining: 5m 18s
7127:	learn: 0.0015263	total: 11m 55s	remaining: 4m 48s
7258:	learn: 0.0014887	total: 11m 55s	remaining: 4m 30s
7121:	learn: 0.0014997	total: 11m 55s	remaining: 4m 49s
6595:	learn: 0.0014161	total: 11m 56s	remaining: 6m 9s
6924:	learn: 0.0020318	total: 11m 56s	remaining: 5m 17s
7128:	learn: 0.0015263	total: 11m 55s	remaining: 4m 48s
7122:	learn: 0.0014997	total: 11m 56s	remaining: 4m 49s
7259:	learn: 0.0014887	total: 11m 55s	remaining: 4m 30s
6925:	learn: 0.0020318	total: 11m 56s	remaining: 5m 17s
6596:	learn: 0.0014161	total: 11m 56s	remaining: 6m 9s
7260:	learn: 0.0014887	total: 11m 56s	remaining: 4m 30s
7123:	learn: 0.0014997	total: 11m 56s	remaining: 4m 49s
7129:	learn: 0.0015262	total: 11m 55s	remaining: 4m 48s
6926:	learn: 0.0020318	total: 11m 56s	remaining: 5m 17s
6597:	learn: 0.0014161	total: 11m 56s	remaining: 6m 9s
6927:	learn: 0.0020318	total: 11m 56s	remaining: 5m 17s
7124:	learn: 0.0014997	total: 11m 56s	remaining: 4m 49s
7261:	learn: 0.0014884	total: 11m 56s	remaining: 4m 30s
7130:	learn: 0.0015262	total: 11m 56s	remaining: 4m 48s
6598:	learn: 0.0014156	total: 11m 56s	remaining: 6m 9s
6928:	learn: 0.0020318	total: 11m 56s	remaining: 5m 17s
7125:	learn: 0.0014997	total: 11m 56s	remaining: 4m 48s
7262:	learn: 0.0014881	total: 11m 56s	remaining: 4m 29s
7131:	learn: 0.0015262	total: 11m 56s	remaining: 4m 48s
6929:	learn: 0.0020318	total: 11m 56s	remaining: 5m 17s
6599:	learn: 0.0014156	total: 11m 56s	remaining: 6m 9s
7126:	learn: 0.0014997	total: 11m 56s	remaining: 4m 48s
7263:	learn: 0.0014881	total: 11m 56s	remaining: 4m 29s
6930:	learn: 0.0020318	total: 11m 56s	remaining: 5m 17s
7132:	learn: 0.0015262	total: 11m 56s	remaining: 4m 47s
6600:	learn: 0.0014152	total: 11m 56s	remaining: 6m 8s
7127:	learn: 0.0014997	total: 11m 56s	remaining: 4m 48s
7264:	learn: 0.0014881	total: 11m 56s	remaining: 4m 29s
6931:	learn: 0.0020318	total: 11m 56s	remaining: 5m 17s
7133:	learn: 0.0015262	total: 11m 56s	remaining: 4m 47s
6601:	learn: 0.0014150	total: 11m 56s	remaining: 6m 8s
7128:	learn: 0.0014992	total: 11m 56s	remaining: 4m 48s
6932:	learn: 0.0020318	total: 11m 56s	remaining: 5m 17s
7265:	learn: 0.0014881	total: 11m 56s	remaining: 4m 29s
7134:	learn: 0.0015262	total: 11m 56s	remaining: 4m 47s
6602:	learn: 0.0014150	total: 11m 56s	remaining: 6m 8s
7129:	learn: 0.0014992	total: 11m 56s	remaining: 4m 48s
6933:	learn: 0.0020312	total: 11m 56s	remaining: 5m 16s
7266:	learn: 0.0014881	total: 11m 56s	remaining: 4m 29s
7130:	learn: 0.0014992	total: 11m 56s	remaining: 4m 48s
7135:	learn: 0.0015262	total: 11m 56s	remaining: 4m 47s
6603:	learn: 0.0014148	total: 11m 56s	remaining: 6m 8s
6934:	learn: 0.0020312	total: 11m 56s	remaining: 5m 16s
7267:	learn: 0.0014881	total: 11m 56s	remaining: 4m 29s
7131:	learn: 0.0014992	total: 11m 56s	remaining: 4m 48s
6604:	learn: 0.0014148	total: 11m 56s	remaining: 6m 8s
6935:	learn: 0.0020312	total: 11m 57s	remaining: 5m 16s
7136:	learn: 0.0015262	total: 11m 56s	remaining: 4m 47s
7268:	learn: 0.0014881	total: 11m 56s	remaining: 4m 29s
6936:	learn: 0.0020312	total: 11m 57s	remaining: 5m 16s
7132:	learn: 0.0014988	total: 11m 57s	remaining: 4m 48s
7269:	learn: 0.0014881	total: 11m 56s	remaining: 4m 29s
7137:	learn: 0.0015262	total: 11m 56s	remaining: 4m 47s
6605:	learn: 0.0014147	total: 11m 57s	remaining: 6m 8s
6937:	learn: 0.0020312	total: 11m 57s	remaining: 5m 16s
7133:	learn: 0.0014988	total: 11m 57s	remaining: 4m 48s
7270:	learn: 0.0014881	total: 11m 57s	remaining: 4m 29s
6606:	learn: 0.0014147	total: 11m 57s	remaining: 6m 8s
7138:	learn: 0.0015262	total: 11m 56s	remaining: 4m 47s
7134:	learn: 0.0014988	total: 11m 57s	remaining: 4m 48s
7271:	learn: 0.0014875	total: 11m 57s	remaining: 4m 29s
6938:	learn: 0.0020312	total: 11m 57s	remaining: 5m 16s
7139:	learn: 0.0015262	total: 11m 57s	remaining: 4m 47s
6607:	learn: 0.0014147	total: 11m 57s	remaining: 6m 8s
7140:	learn: 0.0015262	total: 11m 57s	remaining: 4m 47s
7272:	learn: 0.0014871	total: 11m 57s	remaining: 4m 28s
6939:	learn: 0.0020312	total: 11m 57s	remaining: 5m 16s
7135:	learn: 0.0014988	total: 11m 57s	remaining: 4m 47s
7141:	learn: 0.0015262	total: 11m 57s	remaining: 4m 46s
6608:	learn: 0.0014147	total: 11m 57s	remaining: 6m 8s
7273:	learn: 0.0014867	total: 11m 57s	remaining: 4m 28s
6940:	learn: 0.0020312	total: 11m 57s	remaining: 5m 16s
7136:	learn: 0.0014988	total: 11m 57s	remaining: 4m 47s
7142:	learn: 0.0015262	total: 11m 57s	remaining: 4m 46s
6609:	learn: 0.0014147	total: 11m 57s	remaining: 6m 8s
6941:	learn: 0.0020313	total: 11m 57s	remaining: 5m 16s
7274:	learn: 0.0014866	total: 11m 57s	remaining: 4m 28s
7137:	learn: 0.0014988	total: 11m 57s	remaining: 4m 47s
7143:	learn: 0.0015262	total: 11m 57s	remaining: 4m 46s
6942:	learn: 0.0020312	total: 11m 57s	remaining: 5m 15s
7275:	learn: 0.0014866	total: 11m 57s	remaining: 4m 28s
6610:	learn: 0.0014147	total: 11m 57s	remaining: 6m 7s
7138:	learn: 0.0014988	total: 11m 57s	remaining: 4m 47s
7144:	learn: 0.0015262	total: 11m 57s	remaining: 4m 46s
7276:	learn: 0.0014866	total: 11m 57s	remaining: 4m 28s
6943:	learn: 0.0020312	total: 11m 57s	remaining: 5m 15s
7139:	learn: 0.0014982	total: 11m 57s	remaining: 4m 47s
6611:	learn: 0.0014143	total: 11m 57s	remaining: 6m 7s
7145:	learn: 0.0015262	total: 11m 57s	remaining: 4m 46s
7277:	learn: 0.0014862	total: 11m 57s	remaining: 4m 28s
6944:	learn: 0.0020312	total: 11m 57s	remaining: 5m 15s
7140:	learn: 0.0014980	total: 11m 57s	remaining: 4m 47s
7146:	learn: 0.0015262	total: 11m 57s	remaining: 4m 46s
7278:	learn: 0.0014862	total: 11m 57s	remaining: 4m 28s
6612:	learn: 0.0014143	total: 11m 57s	remaining: 6m 7s
7141:	learn: 0.0014980	total: 11m 57s	remaining: 4m 47s
6945:	learn: 0.0020312	total: 11m 57s	remaining: 5m 15s
7147:	learn: 0.0015260	total: 11m 57s	remaining: 4m 46s
6613:	learn: 0.0014143	total: 11m 58s	remaining: 6m 7s
7279:	learn: 0.0014862	total: 11m 57s	remaining: 4m 28s
7142:	learn: 0.0014980	total: 11m 58s	remaining: 4m 47s
6946:	learn: 0.0020312	total: 11m 58s	remaining: 5m 15s
7148:	learn: 0.0015256	total: 11m 57s	remaining: 4m 46s
6614:	learn: 0.0014140	total: 11m 58s	remaining: 6m 7s
7280:	learn: 0.0014862	total: 11m 58s	remaining: 4m 28s
7143:	learn: 0.0014975	total: 11m 58s	remaining: 4m 47s
6947:	learn: 0.0020313	total: 11m 58s	remaining: 5m 15s
7149:	learn: 0.0015256	total: 11m 57s	remaining: 4m 46s
7281:	learn: 0.0014862	total: 11m 58s	remaining: 4m 28s
6615:	learn: 0.0014140	total: 11m 58s	remaining: 6m 7s
6948:	learn: 0.0020312	total: 11m 58s	remaining: 5m 15s
7150:	learn: 0.0015256	total: 11m 58s	remaining: 4m 46s
7144:	learn: 0.0014971	total: 11m 58s	remaining: 4m 47s
7151:	learn: 0.0015256	total: 11m 58s	remaining: 4m 45s
6949:	learn: 0.0020312	total: 11m 58s	remaining: 5m 15s
7282:	learn: 0.0014862	total: 11m 58s	remaining: 4m 27s
6616:	learn: 0.0014138	total: 11m 58s	remaining: 6m 7s
7145:	learn: 0.0014968	total: 11m 58s	remaining: 4m 46s
7152:	learn: 0.0015256	total: 11m 58s	remaining: 4m 45s
6950:	learn: 0.0020312	total: 11m 58s	remaining: 5m 15s
7283:	learn: 0.0014858	total: 11m 58s	remaining: 4m 27s
7146:	learn: 0.0014968	total: 11m 58s	remaining: 4m 46s
6617:	learn: 0.0014136	total: 11m 58s	remaining: 6m 7s
7153:	learn: 0.0015256	total: 11m 58s	remaining: 4m 45s
7284:	learn: 0.0014854	total: 11m 58s	remaining: 4m 27s
6951:	learn: 0.0020312	total: 11m 58s	remaining: 5m 15s
7147:	learn: 0.0014968	total: 11m 58s	remaining: 4m 46s
7154:	learn: 0.0015256	total: 11m 58s	remaining: 4m 45s
6618:	learn: 0.0014134	total: 11m 58s	remaining: 6m 7s
6952:	learn: 0.0020312	total: 11m 58s	remaining: 5m 14s
7285:	learn: 0.0014849	total: 11m 58s	remaining: 4m 27s
7155:	learn: 0.0015256	total: 11m 58s	remaining: 4m 45s
7148:	learn: 0.0014968	total: 11m 58s	remaining: 4m 46s
7286:	learn: 0.0014848	total: 11m 58s	remaining: 4m 27s
6953:	learn: 0.0020312	total: 11m 58s	remaining: 5m 14s
7156:	learn: 0.0015256	total: 11m 58s	remaining: 4m 45s
6619:	learn: 0.0014134	total: 11m 58s	remaining: 6m 6s
7149:	learn: 0.0014968	total: 11m 58s	remaining: 4m 46s
6954:	learn: 0.0020312	total: 11m 58s	remaining: 5m 14s
7287:	learn: 0.0014844	total: 11m 58s	remaining: 4m 27s
6620:	learn: 0.0014134	total: 11m 58s	remaining: 6m 6s
7157:	learn: 0.0015256	total: 11m 58s	remaining: 4m 45s
7150:	learn: 0.0014968	total: 11m 58s	remaining: 4m 46s
6955:	learn: 0.0020312	total: 11m 58s	remaining: 5m 14s
7288:	learn: 0.0014840	total: 11m 58s	remaining: 4m 27s
7158:	learn: 0.0015256	total: 11m 58s	remaining: 4m 45s
7151:	learn: 0.0014968	total: 11m 58s	remaining: 4m 46s
6621:	learn: 0.0014131	total: 11m 58s	remaining: 6m 6s
6956:	learn: 0.0020312	total: 11m 59s	remaining: 5m 14s
7159:	learn: 0.0015256	total: 11m 58s	remaining: 4m 45s
7289:	learn: 0.0014834	total: 11m 58s	remaining: 4m 27s
7152:	learn: 0.0014968	total: 11m 59s	remaining: 4m 46s
6622:	learn: 0.0014128	total: 11m 59s	remaining: 6m 6s
6957:	learn: 0.0020312	total: 11m 59s	remaining: 5m 14s
7290:	learn: 0.0014834	total: 11m 59s	remaining: 4m 27s
7153:	learn: 0.0014968	total: 11m 59s	remaining: 4m 46s
7160:	learn: 0.0015256	total: 11m 58s	remaining: 4m 45s
6623:	learn: 0.0014129	total: 11m 59s	remaining: 6m 6s
6958:	learn: 0.0020312	total: 11m 59s	remaining: 5m 14s
7291:	learn: 0.0014834	total: 11m 59s	remaining: 4m 27s
7154:	learn: 0.0014967	total: 11m 59s	remaining: 4m 45s
7161:	learn: 0.0015256	total: 11m 59s	remaining: 4m 44s
6624:	learn: 0.0014126	total: 11m 59s	remaining: 6m 6s
6959:	learn: 0.0020312	total: 11m 59s	remaining: 5m 14s
7155:	learn: 0.0014965	total: 11m 59s	remaining: 4m 45s
7292:	learn: 0.0014834	total: 11m 59s	remaining: 4m 26s
7162:	learn: 0.0015256	total: 11m 59s	remaining: 4m 44s
6625:	learn: 0.0014126	total: 11m 59s	remaining: 6m 6s
6960:	learn: 0.0020312	total: 11m 59s	remaining: 5m 14s
7293:	learn: 0.0014834	total: 11m 59s	remaining: 4m 26s
7156:	learn: 0.0014965	total: 11m 59s	remaining: 4m 45s
7163:	learn: 0.0015256	total: 11m 59s	remaining: 4m 44s
6626:	learn: 0.0014123	total: 11m 59s	remaining: 6m 6s
6961:	learn: 0.0020312	total: 11m 59s	remaining: 5m 13s
7157:	learn: 0.0014964	total: 11m 59s	remaining: 4m 45s
7294:	learn: 0.0014834	total: 11m 59s	remaining: 4m 26s
7164:	learn: 0.0015256	total: 11m 59s	remaining: 4m 44s
6962:	learn: 0.0020307	total: 11m 59s	remaining: 5m 13s
7158:	learn: 0.0014964	total: 11m 59s	remaining: 4m 45s
6627:	learn: 0.0014123	total: 11m 59s	remaining: 6m 6s
7295:	learn: 0.0014834	total: 11m 59s	remaining: 4m 26s
6963:	learn: 0.0020307	total: 11m 59s	remaining: 5m 13s
7165:	learn: 0.0015256	total: 11m 59s	remaining: 4m 44s
7159:	learn: 0.0014964	total: 11m 59s	remaining: 4m 45s
6628:	learn: 0.0014123	total: 11m 59s	remaining: 6m 5s
7296:	learn: 0.0014829	total: 11m 59s	remaining: 4m 26s
7166:	learn: 0.0015252	total: 11m 59s	remaining: 4m 44s
6964:	learn: 0.0020307	total: 11m 59s	remaining: 5m 13s
7160:	learn: 0.0014964	total: 11m 59s	remaining: 4m 45s
7297:	learn: 0.0014824	total: 11m 59s	remaining: 4m 26s
6629:	learn: 0.0014123	total: 11m 59s	remaining: 6m 5s
7167:	learn: 0.0015252	total: 11m 59s	remaining: 4m 44s
6965:	learn: 0.0020307	total: 11m 59s	remaining: 5m 13s
7161:	learn: 0.0014964	total: 11m 59s	remaining: 4m 45s
7298:	learn: 0.0014824	total: 11m 59s	remaining: 4m 26s
6630:	learn: 0.0014122	total: 11m 59s	remaining: 6m 5s
7162:	learn: 0.0014964	total: 11m 59s	remaining: 4m 45s
7168:	learn: 0.0015252	total: 11m 59s	remaining: 4m 44s
6966:	learn: 0.0020307	total: 12m	remaining: 5m 13s
7299:	learn: 0.0014824	total: 11m 59s	remaining: 4m 26s
7163:	learn: 0.0014964	total: 12m	remaining: 4m 45s
6631:	learn: 0.0014122	total: 12m	remaining: 6m 5s
6967:	learn: 0.0020307	total: 12m	remaining: 5m 13s
7169:	learn: 0.0015252	total: 11m 59s	remaining: 4m 44s
7164:	learn: 0.0014964	total: 12m	remaining: 4m 44s
7300:	learn: 0.0014824	total: 12m	remaining: 4m 26s
6968:	learn: 0.0020307	total: 12m	remaining: 5m 13s
6632:	learn: 0.0014119	total: 12m	remaining: 6m 5s
7170:	learn: 0.0015252	total: 11m 59s	remaining: 4m 44s
7165:	learn: 0.0014964	total: 12m	remaining: 4m 44s
7301:	learn: 0.0014824	total: 12m	remaining: 4m 26s
6969:	learn: 0.0020307	total: 12m	remaining: 5m 13s
6633:	learn: 0.0014119	total: 12m	remaining: 6m 5s
7171:	learn: 0.0015252	total: 12m	remaining: 4m 43s
7302:	learn: 0.0014824	total: 12m	remaining: 4m 25s
7166:	learn: 0.0014964	total: 12m	remaining: 4m 44s
6970:	learn: 0.0020307	total: 12m	remaining: 5m 13s
6634:	learn: 0.0014119	total: 12m	remaining: 6m 5s
7172:	learn: 0.0015252	total: 12m	remaining: 4m 43s
7303:	learn: 0.0014824	total: 12m	remaining: 4m 25s
7167:	learn: 0.0014964	total: 12m	remaining: 4m 44s
7173:	learn: 0.0015252	total: 12m	remaining: 4m 43s
6635:	learn: 0.0014117	total: 12m	remaining: 6m 5s
6971:	learn: 0.0020307	total: 12m	remaining: 5m 12s
7304:	learn: 0.0014824	total: 12m	remaining: 4m 25s
7168:	learn: 0.0014964	total: 12m	remaining: 4m 44s
7174:	learn: 0.0015252	total: 12m	remaining: 4m 43s
6636:	learn: 0.0014113	total: 12m	remaining: 6m 5s
6972:	learn: 0.0020307	total: 12m	remaining: 5m 12s
7305:	learn: 0.0014821	total: 12m	remaining: 4m 25s
7175:	learn: 0.0015252	total: 12m	remaining: 4m 43s
6637:	learn: 0.0014109	total: 12m	remaining: 6m 5s
7169:	learn: 0.0014964	total: 12m	remaining: 4m 44s
6973:	learn: 0.0020307	total: 12m	remaining: 5m 12s

7306:	learn: 0.0014817	total: 12m	remaining: 4m 25s
6638:	learn: 0.0014110	total: 12m	remaining: 6m 4s
7170:	learn: 0.0014964	total: 12m	remaining: 4m 44s
7176:	learn: 0.0015252	total: 12m	remaining: 4m 43s
6974:	learn: 0.0020307	total: 12m	remaining: 5m 12s
7307:	learn: 0.0014811	total: 12m	remaining: 4m 25s
6639:	learn: 0.0014109	total: 12m	remaining: 6m 4s
7177:	learn: 0.0015252	total: 12m	remaining: 4m 43s
7171:	learn: 0.0014964	total: 12m	remaining: 4m 44s
6975:	learn: 0.0020307	total: 12m	remaining: 5m 12s
7308:	learn: 0.0014811	total: 12m	remaining: 4m 25s
6640:	learn: 0.0014109	total: 12m	remaining: 6m 4s
7178:	learn: 0.0015252	total: 12m	remaining: 4m 43s
7172:	learn: 0.0014959	total: 12m	remaining: 4m 44s
6976:	learn: 0.0020307	total: 12m 1s	remaining: 5m 12s
7309:	learn: 0.0014805	total: 12m	remaining: 4m 25s
7179:	learn: 0.0015252	total: 12m	remaining: 4m 43s
6641:	learn: 0.0014109	total: 12m 1s	remaining: 6m 4s
7173:	learn: 0.0014960	total: 12m 1s	remaining: 4m 44s
6977:	learn: 0.0020306	total: 12m 1s	remaining: 5m 12s
7310:	learn: 0.0014805	total: 12m 1s	remaining: 4m 25s
6642:	learn: 0.0014109	total: 12m 1s	remaining: 6m 4s
7180:	learn: 0.0015252	total: 12m	remaining: 4m 43s
7174:	learn: 0.0014960	total: 12m 1s	remaining: 4m 43s
7311:	learn: 0.0014805	total: 12m 1s	remaining: 4m 25s
6978:	learn: 0.0020307	total: 12m 1s	remaining: 5m 12s
7181:	learn: 0.0015251	total: 12m 1s	remaining: 4m 42s
6643:	learn: 0.0014107	total: 12m 1s	remaining: 6m 4s
7312:	learn: 0.0014805	total: 12m 1s	remaining: 4m 24s
6979:	learn: 0.0020307	total: 12m 1s	remaining: 5m 12s
7175:	learn: 0.0014955	total: 12m 1s	remaining: 4m 43s
7182:	learn: 0.0015251	total: 12m 1s	remaining: 4m 42s
6644:	learn: 0.0014107	total: 12m 1s	remaining: 6m 4s
7313:	learn: 0.0014805	total: 12m 1s	remaining: 4m 24s
7176:	learn: 0.0014953	total: 12m 1s	remaining: 4m 43s
7183:	learn: 0.0015248	total: 12m 1s	remaining: 4m 42s
6980:	learn: 0.0020307	total: 12m 1s	remaining: 5m 12s
6645:	learn: 0.0014106	total: 12m 1s	remaining: 6m 4s
7314:	learn: 0.0014805	total: 12m 1s	remaining: 4m 24s
7177:	learn: 0.0014954	total: 12m 1s	remaining: 4m 43s
7184:	learn: 0.0015248	total: 12m 1s	remaining: 4m 42s
6981:	learn: 0.0020307	total: 12m 1s	remaining: 5m 11s
6646:	learn: 0.0014105	total: 12m 1s	remaining: 6m 3s
7315:	learn: 0.0014805	total: 12m 1s	remaining: 4m 24s
6982:	learn: 0.0020307	total: 12m 1s	remaining: 5m 11s
7178:	learn: 0.0014954	total: 12m 1s	remaining: 4m 43s
7185:	learn: 0.0015248	total: 12m 1s	remaining: 4m 42s
6647:	learn: 0.0014102	total: 12m 1s	remaining: 6m 3s
7316:	learn: 0.0014805	total: 12m 1s	remaining: 4m 24s
7179:	learn: 0.0014953	total: 12m 1s	remaining: 4m 43s
7186:	learn: 0.0015248	total: 12m 1s	remaining: 4m 42s
6983:	learn: 0.0020307	total: 12m 1s	remaining: 5m 11s
6648:	learn: 0.0014097	total: 12m 1s	remaining: 6m 3s
7317:	learn: 0.0014805	total: 12m 1s	remaining: 4m 24s
6649:	learn: 0.0014097	total: 12m 1s	remaining: 6m 3s
7187:	learn: 0.0015248	total: 12m 1s	remaining: 4m 42s
7180:	learn: 0.0014953	total: 12m 1s	remaining: 4m 43s
6984:	learn: 0.0020307	total: 12m 1s	remaining: 5m 11s
7318:	learn: 0.0014805	total: 12m 1s	remaining: 4m 24s
7188:	learn: 0.0015248	total: 12m 1s	remaining: 4m 42s
7181:	learn: 0.0014953	total: 12m 1s	remaining: 4m 43s
6650:	learn: 0.0014092	total: 12m 1s	remaining: 6m 3s
6985:	learn: 0.0020306	total: 12m 2s	remaining: 5m 11s
7319:	learn: 0.0014805	total: 12m 1s	remaining: 4m 24s
7189:	learn: 0.0015248	total: 12m 1s	remaining: 4m 42s
6986:	learn: 0.0020306	total: 12m 2s	remaining: 5m 11s
7182:	learn: 0.0014953	total: 12m 2s	remaining: 4m 43s
6651:	learn: 0.0014090	total: 12m 2s	remaining: 6m 3s
7320:	learn: 0.0014805	total: 12m 2s	remaining: 4m 24s
7190:	learn: 0.0015248	total: 12m 1s	remaining: 4m 41s
6987:	learn: 0.0020306	total: 12m 2s	remaining: 5m 11s
7183:	learn: 0.0014948	total: 12m 2s	remaining: 4m 43s
6652:	learn: 0.0014086	total: 12m 2s	remaining: 6m 3s
7321:	learn: 0.0014805	total: 12m 2s	remaining: 4m 24s
7191:	learn: 0.0015248	total: 12m 1s	remaining: 4m 41s
6988:	learn: 0.0020306	total: 12m 2s	remaining: 5m 11s
7184:	learn: 0.0014948	total: 12m 2s	remaining: 4m 42s
6653:	learn: 0.0014086	total: 12m 2s	remaining: 6m 3s
7192:	learn: 0.0015248	total: 12m 2s	remaining: 4m 41s
7322:	learn: 0.0014805	total: 12m 2s	remaining: 4m 24s
6989:	learn: 0.0020306	total: 12m 2s	remaining: 5m 11s
7185:	learn: 0.0014948	total: 12m 2s	remaining: 4m 42s
7193:	learn: 0.0015248	total: 12m 2s	remaining: 4m 41s
6654:	learn: 0.0014086	total: 12m 2s	remaining: 6m 3s
7323:	learn: 0.0014802	total: 12m 2s	remaining: 4m 23s
7186:	learn: 0.0014948	total: 12m 2s	remaining: 4m 42s
6990:	learn: 0.0020306	total: 12m 2s	remaining: 5m 10s
7194:	learn: 0.0015248	total: 12m 2s	remaining: 4m 41s
6655:	learn: 0.0014086	total: 12m 2s	remaining: 6m 2s
7187:	learn: 0.0014948	total: 12m 2s	remaining: 4m 42s
7324:	learn: 0.0014802	total: 12m 2s	remaining: 4m 23s
7195:	learn: 0.0015242	total: 12m 2s	remaining: 4m 41s
6991:	learn: 0.0020306	total: 12m 2s	remaining: 5m 10s
7325:	learn: 0.0014798	total: 12m 2s	remaining: 4m 23s
6656:	learn: 0.0014086	total: 12m 2s	remaining: 6m 2s
7188:	learn: 0.0014948	total: 12m 2s	remaining: 4m 42s
7196:	learn: 0.0015242	total: 12m 2s	remaining: 4m 41s
6992:	learn: 0.0020306	total: 12m 2s	remaining: 5m 10s
7326:	learn: 0.0014793	total: 12m 2s	remaining: 4m 23s
6657:	learn: 0.0014086	total: 12m 2s	remaining: 6m 2s
7197:	learn: 0.0015242	total: 12m 2s	remaining: 4m 41s
7189:	learn: 0.0014948	total: 12m 2s	remaining: 4m 42s
6993:	learn: 0.0020307	total: 12m 2s	remaining: 5m 10s
7198:	learn: 0.0015241	total: 12m 2s	remaining: 4m 41s
7327:	learn: 0.0014793	total: 12m 2s	remaining: 4m 23s
6658:	learn: 0.0014086	total: 12m 2s	remaining: 6m 2s
7190:	learn: 0.0014944	total: 12m 2s	remaining: 4m 42s
7199:	learn: 0.0015241	total: 12m 2s	remaining: 4m 41s
6994:	learn: 0.0020307	total: 12m 2s	remaining: 5m 10s
7328:	learn: 0.0014793	total: 12m 2s	remaining: 4m 23s
7191:	learn: 0.0014943	total: 12m 2s	remaining: 4m 42s
6659:	learn: 0.0014083	total: 12m 2s	remaining: 6m 2s
7200:	learn: 0.0015241	total: 12m 2s	remaining: 4m 40s
6995:	learn: 0.0020306	total: 12m 3s	remaining: 5m 10s
7329:	learn: 0.0014793	total: 12m 2s	remaining: 4m 23s
7192:	learn: 0.0014943	total: 12m 3s	remaining: 4m 42s
6660:	learn: 0.0014080	total: 12m 3s	remaining: 6m 2s
7201:	learn: 0.0015241	total: 12m 2s	remaining: 4m 40s
7330:	learn: 0.0014793	total: 12m 3s	remaining: 4m 23s
6996:	learn: 0.0020306	total: 12m 3s	remaining: 5m 10s
7193:	learn: 0.0014943	total: 12m 3s	remaining: 4m 42s
6661:	learn: 0.0014078	total: 12m 3s	remaining: 6m 2s
7202:	learn: 0.0015241	total: 12m 2s	remaining: 4m 40s
6997:	learn: 0.0020306	total: 12m 3s	remaining: 5m 10s
7331:	learn: 0.0014793	total: 12m 3s	remaining: 4m 23s
7194:	learn: 0.0014943	total: 12m 3s	remaining: 4m 41s
7203:	learn: 0.0015241	total: 12m 3s	remaining: 4m 40s
6998:	learn: 0.0020306	total: 12m 3s	remaining: 5m 10s
6662:	learn: 0.0014074	total: 12m 3s	remaining: 6m 2s
7332:	learn: 0.0014793	total: 12m 3s	remaining: 4m 23s
7195:	learn: 0.0014943	total: 12m 3s	remaining: 4m 41s
7204:	learn: 0.0015241	total: 12m 3s	remaining: 4m 40s
6999:	learn: 0.0020306	total: 12m 3s	remaining: 5m 10s
6663:	learn: 0.0014074	total: 12m 3s	remaining: 6m 2s
7333:	learn: 0.0014793	total: 12m 3s	remaining: 4m 22s
7196:	learn: 0.0014943	total: 12m 3s	remaining: 4m 41s
7205:	learn: 0.0015241	total: 12m 3s	remaining: 4m 40s
7000:	learn: 0.0020306	total: 12m 3s	remaining: 5m 9s
7197:	learn: 0.0014943	total: 12m 3s	remaining: 4m 41s
6664:	learn: 0.0014074	total: 12m 3s	remaining: 6m 2s
7334:	learn: 0.0014793	total: 12m 3s	remaining: 4m 22s
7001:	learn: 0.0020306	total: 12m 3s	remaining: 5m 9s
7206:	learn: 0.0015241	total: 12m 3s	remaining: 4m 40s
6665:	learn: 0.0014072	total: 12m 3s	remaining: 6m 1s
7198:	learn: 0.0014943	total: 12m 3s	remaining: 4m 41s
7207:	learn: 0.0015241	total: 12m 3s	remaining: 4m 40s
7335:	learn: 0.0014788	total: 12m 3s	remaining: 4m 22s
7002:	learn: 0.0020306	total: 12m 3s	remaining: 5m 9s
6666:	learn: 0.0014069	total: 12m 3s	remaining: 6m 1s
7199:	learn: 0.0014943	total: 12m 3s	remaining: 4m 41s
7208:	learn: 0.0015241	total: 12m 3s	remaining: 4m 40s
7336:	learn: 0.0014788	total: 12m 3s	remaining: 4m 22s
7003:	learn: 0.0020306	total: 12m 3s	remaining: 5m 9s
6667:	learn: 0.0014069	total: 12m 3s	remaining: 6m 1s
7209:	learn: 0.0015241	total: 12m 3s	remaining: 4m 40s
7200:	learn: 0.0014943	total: 12m 3s	remaining: 4m 41s
7337:	learn: 0.0014785	total: 12m 3s	remaining: 4m 22s
7004:	learn: 0.0020306	total: 12m 3s	remaining: 5m 9s
6668:	learn: 0.0014067	total: 12m 3s	remaining: 6m 1s
7338:	learn: 0.0014781	total: 12m 3s	remaining: 4m 22s
7210:	learn: 0.0015241	total: 12m 3s	remaining: 4m 39s
7201:	learn: 0.0014943	total: 12m 3s	remaining: 4m 41s
6669:	learn: 0.0014063	total: 12m 3s	remaining: 6m 1s
7005:	learn: 0.0020306	total: 12m 4s	remaining: 5m 9s
7211:	learn: 0.0015241	total: 12m 3s	remaining: 4m 39s
7339:	learn: 0.0014778	total: 12m 3s	remaining: 4m 22s
7202:	learn: 0.0014943	total: 12m 4s	remaining: 4m 41s
6670:	learn: 0.0014063	total: 12m 4s	remaining: 6m 1s
7006:	learn: 0.0020306	total: 12m 4s	remaining: 5m 9s
7212:	learn: 0.0015241	total: 12m 3s	remaining: 4m 39s
7203:	learn: 0.0014943	total: 12m 4s	remaining: 4m 41s
7340:	learn: 0.0014776	total: 12m 4s	remaining: 4m 22s
7213:	learn: 0.0015241	total: 12m 3s	remaining: 4m 39s
6671:	learn: 0.0014060	total: 12m 4s	remaining: 6m 1s
7007:	learn: 0.0020306	total: 12m 4s	remaining: 5m 9s
7204:	learn: 0.0014943	total: 12m 4s	remaining: 4m 40s
7341:	learn: 0.0014771	total: 12m 4s	remaining: 4m 22s
7008:	learn: 0.0020306	total: 12m 4s	remaining: 5m 9s
7214:	learn: 0.0015241	total: 12m 4s	remaining: 4m 39s
6672:	learn: 0.0014056	total: 12m 4s	remaining: 6m 1s
7205:	learn: 0.0014943	total: 12m 4s	remaining: 4m 40s
7342:	learn: 0.0014767	total: 12m 4s	remaining: 4m 22s
7009:	learn: 0.0020306	total: 12m 4s	remaining: 5m 8s
6673:	learn: 0.0014056	total: 12m 4s	remaining: 6m 1s
7215:	learn: 0.0015241	total: 12m 4s	remaining: 4m 39s
7206:	learn: 0.0014943	total: 12m 4s	remaining: 4m 40s
7343:	learn: 0.0014765	total: 12m 4s	remaining: 4m 21s
7216:	learn: 0.0015241	total: 12m 4s	remaining: 4m 39s
7010:	learn: 0.0020306	total: 12m 4s	remaining: 5m 8s
6674:	learn: 0.0014053	total: 12m 4s	remaining: 6m
7207:	learn: 0.0014943	total: 12m 4s	remaining: 4m 40s
7217:	learn: 0.0015240	total: 12m 4s	remaining: 4m 39s
7344:	learn: 0.0014765	total: 12m 4s	remaining: 4m 21s
6675:	learn: 0.0014050	total: 12m 4s	remaining: 6m
7011:	learn: 0.0020306	total: 12m 4s	remaining: 5m 8s
7208:	learn: 0.0014943	total: 12m 4s	remaining: 4m 40s
7218:	learn: 0.0015240	total: 12m 4s	remaining: 4m 39s
7345:	learn: 0.0014766	total: 12m 4s	remaining: 4m 21s
6676:	learn: 0.0014047	total: 12m 4s	remaining: 6m
7012:	learn: 0.0020306	total: 12m 4s	remaining: 5m 8s
7209:	learn: 0.0014943	total: 12m 4s	remaining: 4m 40s
7219:	learn: 0.0015241	total: 12m 4s	remaining: 4m 38s
6677:	learn: 0.0014047	total: 12m 4s	remaining: 6m
7346:	learn: 0.0014765	total: 12m 4s	remaining: 4m 21s
7210:	learn: 0.0014943	total: 12m 4s	remaining: 4m 40s
7013:	learn: 0.0020306	total: 12m 4s	remaining: 5m 8s
7347:	learn: 0.0014766	total: 12m 4s	remaining: 4m 21s
7220:	learn: 0.0015241	total: 12m 4s	remaining: 4m 38s
7211:	learn: 0.0014943	total: 12m 4s	remaining: 4m 40s
6678:	learn: 0.0014042	total: 12m 4s	remaining: 6m
7014:	learn: 0.0020306	total: 12m 4s	remaining: 5m 8s
7348:	learn: 0.0014761	total: 12m 4s	remaining: 4m 21s
7221:	learn: 0.0015241	total: 12m 4s	remaining: 4m 38s
7212:	learn: 0.0014943	total: 12m 4s	remaining: 4m 40s
7015:	learn: 0.0020306	total: 12m 5s	remaining: 5m 8s
6679:	learn: 0.0014039	total: 12m 5s	remaining: 6m
7222:	learn: 0.0015241	total: 12m 4s	remaining: 4m 38s
7349:	learn: 0.0014755	total: 12m 4s	remaining: 4m 21s
7213:	learn: 0.0014943	total: 12m 5s	remaining: 4m 40s
7016:	learn: 0.0020306	total: 12m 5s	remaining: 5m 8s
6680:	learn: 0.0014037	total: 12m 5s	remaining: 6m
7350:	learn: 0.0014751	total: 12m 5s	remaining: 4m 21s
7223:	learn: 0.0015241	total: 12m 4s	remaining: 4m 38s
7214:	learn: 0.0014943	total: 12m 5s	remaining: 4m 39s
7017:	learn: 0.0020306	total: 12m 5s	remaining: 5m 8s
6681:	learn: 0.0014037	total: 12m 5s	remaining: 6m
7224:	learn: 0.0015241	total: 12m 5s	remaining: 4m 38s
7351:	learn: 0.0014747	total: 12m 5s	remaining: 4m 21s
7018:	learn: 0.0020306	total: 12m 5s	remaining: 5m 8s
7215:	learn: 0.0014943	total: 12m 5s	remaining: 4m 39s
6682:	learn: 0.0014036	total: 12m 5s	remaining: 5m 59s
7225:	learn: 0.0015240	total: 12m 5s	remaining: 4m 38s
7352:	learn: 0.0014747	total: 12m 5s	remaining: 4m 21s
7216:	learn: 0.0014943	total: 12m 5s	remaining: 4m 39s
7019:	learn: 0.0020306	total: 12m 5s	remaining: 5m 7s
6683:	learn: 0.0014031	total: 12m 5s	remaining: 5m 59s
7226:	learn: 0.0015241	total: 12m 5s	remaining: 4m 38s
7353:	learn: 0.0014747	total: 12m 5s	remaining: 4m 21s
7217:	learn: 0.0014943	total: 12m 5s	remaining: 4m 39s
7020:	learn: 0.0020306	total: 12m 5s	remaining: 5m 7s
7227:	learn: 0.0015241	total: 12m 5s	remaining: 4m 38s
6684:	learn: 0.0014028	total: 12m 5s	remaining: 5m 59s
7354:	learn: 0.0014747	total: 12m 5s	remaining: 4m 20s
7218:	learn: 0.0014943	total: 12m 5s	remaining: 4m 39s
7021:	learn: 0.0020306	total: 12m 5s	remaining: 5m 7s
7228:	learn: 0.0015240	total: 12m 5s	remaining: 4m 38s
6685:	learn: 0.0014028	total: 12m 5s	remaining: 5m 59s
7355:	learn: 0.0014743	total: 12m 5s	remaining: 4m 20s
7229:	learn: 0.0015240	total: 12m 5s	remaining: 4m 37s
7219:	learn: 0.0014943	total: 12m 5s	remaining: 4m 39s
7022:	learn: 0.0020306	total: 12m 5s	remaining: 5m 7s
6686:	learn: 0.0014028	total: 12m 5s	remaining: 5m 59s
7356:	learn: 0.0014743	total: 12m 5s	remaining: 4m 20s
7220:	learn: 0.0014943	total: 12m 5s	remaining: 4m 39s
7230:	learn: 0.0015240	total: 12m 5s	remaining: 4m 37s
7023:	learn: 0.0020306	total: 12m 5s	remaining: 5m 7s
6687:	learn: 0.0014024	total: 12m 5s	remaining: 5m 59s
7357:	learn: 0.0014743	total: 12m 5s	remaining: 4m 20s
7221:	learn: 0.0014943	total: 12m 5s	remaining: 4m 39s
7231:	learn: 0.0015241	total: 12m 5s	remaining: 4m 37s
7358:	learn: 0.0014743	total: 12m 5s	remaining: 4m 20s
6688:	learn: 0.0014020	total: 12m 5s	remaining: 5m 59s
7024:	learn: 0.0020306	total: 12m 6s	remaining: 5m 7s
7222:	learn: 0.0014943	total: 12m 5s	remaining: 4m 39s
7359:	learn: 0.0014743	total: 12m 5s	remaining: 4m 20s
7232:	learn: 0.0015241	total: 12m 5s	remaining: 4m 37s
7223:	learn: 0.0014943	total: 12m 6s	remaining: 4m 39s
7025:	learn: 0.0020306	total: 12m 6s	remaining: 5m 7s
6689:	learn: 0.0014015	total: 12m 6s	remaining: 5m 59s
7360:	learn: 0.0014739	total: 12m 6s	remaining: 4m 20s
7233:	learn: 0.0015241	total: 12m 5s	remaining: 4m 37s
7026:	learn: 0.0020306	total: 12m 6s	remaining: 5m 7s
7224:	learn: 0.0014940	total: 12m 6s	remaining: 4m 38s
7361:	learn: 0.0014734	total: 12m 6s	remaining: 4m 20s
6690:	learn: 0.0014015	total: 12m 6s	remaining: 5m 59s
7234:	learn: 0.0015240	total: 12m 5s	remaining: 4m 37s
7027:	learn: 0.0020306	total: 12m 6s	remaining: 5m 7s
7225:	learn: 0.0014940	total: 12m 6s	remaining: 4m 38s
7362:	learn: 0.0014729	total: 12m 6s	remaining: 4m 20s
6691:	learn: 0.0014013	total: 12m 6s	remaining: 5m 59s
7226:	learn: 0.0014940	total: 12m 6s	remaining: 4m 38s
7028:	learn: 0.0020306	total: 12m 6s	remaining: 5m 7s
7235:	learn: 0.0015240	total: 12m 6s	remaining: 4m 37s
7363:	learn: 0.0014729	total: 12m 6s	remaining: 4m 19s
6692:	learn: 0.0014013	total: 12m 6s	remaining: 5m 58s
7029:	learn: 0.0020306	total: 12m 6s	remaining: 5m 6s
7236:	learn: 0.0015240	total: 12m 6s	remaining: 4m 37s
7227:	learn: 0.0014939	total: 12m 6s	remaining: 4m 38s
7364:	learn: 0.0014729	total: 12m 6s	remaining: 4m 19s
6693:	learn: 0.0014008	total: 12m 6s	remaining: 5m 58s
7237:	learn: 0.0015241	total: 12m 6s	remaining: 4m 37s
7030:	learn: 0.0020306	total: 12m 6s	remaining: 5m 6s
7228:	learn: 0.0014940	total: 12m 6s	remaining: 4m 38s
7365:	learn: 0.0014729	total: 12m 6s	remaining: 4m 19s
6694:	learn: 0.0014004	total: 12m 6s	remaining: 5m 58s
7229:	learn: 0.0014939	total: 12m 6s	remaining: 4m 38s
7031:	learn: 0.0020306	total: 12m 6s	remaining: 5m 6s
7238:	learn: 0.0015241	total: 12m 6s	remaining: 4m 37s
7366:	learn: 0.0014729	total: 12m 6s	remaining: 4m 19s
6695:	learn: 0.0014001	total: 12m 6s	remaining: 5m 58s

7230:	learn: 0.0014939	total: 12m 6s	remaining: 4m 38s
7367:	learn: 0.0014728	total: 12m 6s	remaining: 4m 19s
7239:	learn: 0.0015241	total: 12m 6s	remaining: 4m 36s
7032:	learn: 0.0020306	total: 12m 6s	remaining: 5m 6s
6696:	learn: 0.0013996	total: 12m 6s	remaining: 5m 58s
7231:	learn: 0.0014939	total: 12m 6s	remaining: 4m 38s
7240:	learn: 0.0015240	total: 12m 6s	remaining: 4m 36s
7368:	learn: 0.0014729	total: 12m 6s	remaining: 4m 19s
7033:	learn: 0.0020306	total: 12m 6s	remaining: 5m 6s
7232:	learn: 0.0014939	total: 12m 6s	remaining: 4m 38s
6697:	learn: 0.0013992	total: 12m 6s	remaining: 5m 58s
7241:	learn: 0.0015241	total: 12m 6s	remaining: 4m 36s
7369:	learn: 0.0014729	total: 12m 6s	remaining: 4m 19s
7233:	learn: 0.0014939	total: 12m 6s	remaining: 4m 37s
7034:	learn: 0.0020306	total: 12m 7s	remaining: 5m 6s
6698:	learn: 0.0013992	total: 12m 7s	remaining: 5m 58s
7242:	learn: 0.0015240	total: 12m 6s	remaining: 4m 36s
7370:	learn: 0.0014729	total: 12m 6s	remaining: 4m 19s
7035:	learn: 0.0020306	total: 12m 7s	remaining: 5m 6s
7234:	learn: 0.0014939	total: 12m 7s	remaining: 4m 37s
6699:	learn: 0.0013992	total: 12m 7s	remaining: 5m 58s
7235:	learn: 0.0014938	total: 12m 7s	remaining: 4m 37s
7036:	learn: 0.0020306	total: 12m 7s	remaining: 5m 6s
7243:	learn: 0.0015240	total: 12m 6s	remaining: 4m 36s
7371:	learn: 0.0014725	total: 12m 7s	remaining: 4m 19s
6700:	learn: 0.0013992	total: 12m 7s	remaining: 5m 58s
7236:	learn: 0.0014939	total: 12m 7s	remaining: 4m 37s
7037:	learn: 0.0020306	total: 12m 7s	remaining: 5m 6s
7372:	learn: 0.0014721	total: 12m 7s	remaining: 4m 19s
7244:	learn: 0.0015240	total: 12m 7s	remaining: 4m 36s
6701:	learn: 0.0013990	total: 12m 7s	remaining: 5m 57s
7373:	learn: 0.0014721	total: 12m 7s	remaining: 4m 19s
7038:	learn: 0.0020306	total: 12m 7s	remaining: 5m 5s
7237:	learn: 0.0014939	total: 12m 7s	remaining: 4m 37s
7245:	learn: 0.0015240	total: 12m 7s	remaining: 4m 36s
6702:	learn: 0.0013988	total: 12m 7s	remaining: 5m 57s
7039:	learn: 0.0020306	total: 12m 7s	remaining: 5m 5s
7246:	learn: 0.0015240	total: 12m 7s	remaining: 4m 36s
7238:	learn: 0.0014939	total: 12m 7s	remaining: 4m 37s
7374:	learn: 0.0014721	total: 12m 7s	remaining: 4m 18s
6703:	learn: 0.0013988	total: 12m 7s	remaining: 5m 57s
7247:	learn: 0.0015241	total: 12m 7s	remaining: 4m 36s
7375:	learn: 0.0014721	total: 12m 7s	remaining: 4m 18s
7040:	learn: 0.0020306	total: 12m 7s	remaining: 5m 5s
7239:	learn: 0.0014939	total: 12m 7s	remaining: 4m 37s
6704:	learn: 0.0013984	total: 12m 7s	remaining: 5m 57s
7248:	learn: 0.0015240	total: 12m 7s	remaining: 4m 36s
7041:	learn: 0.0020306	total: 12m 7s	remaining: 5m 5s
7376:	learn: 0.0014716	total: 12m 7s	remaining: 4m 18s
7240:	learn: 0.0014936	total: 12m 7s	remaining: 4m 37s
6705:	learn: 0.0013984	total: 12m 7s	remaining: 5m 57s
7249:	learn: 0.0015240	total: 12m 7s	remaining: 4m 35s
7042:	learn: 0.0020306	total: 12m 7s	remaining: 5m 5s
7377:	learn: 0.0014716	total: 12m 7s	remaining: 4m 18s
7241:	learn: 0.0014936	total: 12m 7s	remaining: 4m 37s
6706:	learn: 0.0013980	total: 12m 7s	remaining: 5m 57s
7043:	learn: 0.0020306	total: 12m 7s	remaining: 5m 5s
7250:	learn: 0.0015240	total: 12m 7s	remaining: 4m 35s
7242:	learn: 0.0014931	total: 12m 7s	remaining: 4m 37s
7378:	learn: 0.0014716	total: 12m 7s	remaining: 4m 18s
7251:	learn: 0.0015240	total: 12m 7s	remaining: 4m 35s
7243:	learn: 0.0014927	total: 12m 7s	remaining: 4m 36s
7044:	learn: 0.0020306	total: 12m 8s	remaining: 5m 5s
6707:	learn: 0.0013977	total: 12m 7s	remaining: 5m 57s
7379:	learn: 0.0014716	total: 12m 7s	remaining: 4m 18s
7252:	learn: 0.0015240	total: 12m 7s	remaining: 4m 35s
6708:	learn: 0.0013977	total: 12m 8s	remaining: 5m 57s
7244:	learn: 0.0014922	total: 12m 8s	remaining: 4m 36s
7380:	learn: 0.0014711	total: 12m 8s	remaining: 4m 18s
7045:	learn: 0.0020306	total: 12m 8s	remaining: 5m 5s
7253:	learn: 0.0015240	total: 12m 7s	remaining: 4m 35s
7245:	learn: 0.0014922	total: 12m 8s	remaining: 4m 36s
6709:	learn: 0.0013977	total: 12m 8s	remaining: 5m 57s
7381:	learn: 0.0014711	total: 12m 8s	remaining: 4m 18s
7254:	learn: 0.0015240	total: 12m 7s	remaining: 4m 35s
7046:	learn: 0.0020304	total: 12m 8s	remaining: 5m 5s
7246:	learn: 0.0014918	total: 12m 8s	remaining: 4m 36s
6710:	learn: 0.0013977	total: 12m 8s	remaining: 5m 56s
7382:	learn: 0.0014711	total: 12m 8s	remaining: 4m 18s
7255:	learn: 0.0015240	total: 12m 8s	remaining: 4m 35s
7047:	learn: 0.0020304	total: 12m 8s	remaining: 5m 5s
7247:	learn: 0.0014918	total: 12m 8s	remaining: 4m 36s
7256:	learn: 0.0015240	total: 12m 8s	remaining: 4m 35s
6711:	learn: 0.0013973	total: 12m 8s	remaining: 5m 56s
7383:	learn: 0.0014711	total: 12m 8s	remaining: 4m 18s
7048:	learn: 0.0020304	total: 12m 8s	remaining: 5m 4s
7248:	learn: 0.0014918	total: 12m 8s	remaining: 4m 36s
7384:	learn: 0.0014711	total: 12m 8s	remaining: 4m 17s
7049:	learn: 0.0020304	total: 12m 8s	remaining: 5m 4s
7257:	learn: 0.0015240	total: 12m 8s	remaining: 4m 35s
6712:	learn: 0.0013971	total: 12m 8s	remaining: 5m 56s
7249:	learn: 0.0014916	total: 12m 8s	remaining: 4m 36s
7258:	learn: 0.0015240	total: 12m 8s	remaining: 4m 35s
7050:	learn: 0.0020304	total: 12m 8s	remaining: 5m 4s
7250:	learn: 0.0014916	total: 12m 8s	remaining: 4m 36s
7385:	learn: 0.0014707	total: 12m 8s	remaining: 4m 17s
6713:	learn: 0.0013971	total: 12m 8s	remaining: 5m 56s
7251:	learn: 0.0014916	total: 12m 8s	remaining: 4m 36s
7051:	learn: 0.0020304	total: 12m 8s	remaining: 5m 4s
7259:	learn: 0.0015240	total: 12m 8s	remaining: 4m 34s
7386:	learn: 0.0014707	total: 12m 8s	remaining: 4m 17s
6714:	learn: 0.0013971	total: 12m 8s	remaining: 5m 56s
7252:	learn: 0.0014916	total: 12m 8s	remaining: 4m 36s
7052:	learn: 0.0020304	total: 12m 8s	remaining: 5m 4s
7387:	learn: 0.0014707	total: 12m 8s	remaining: 4m 17s
7260:	learn: 0.0015240	total: 12m 8s	remaining: 4m 34s
6715:	learn: 0.0013967	total: 12m 8s	remaining: 5m 56s
7253:	learn: 0.0014916	total: 12m 8s	remaining: 4m 35s
7053:	learn: 0.0020304	total: 12m 8s	remaining: 5m 4s
7388:	learn: 0.0014707	total: 12m 8s	remaining: 4m 17s
7261:	learn: 0.0015240	total: 12m 8s	remaining: 4m 34s
7054:	learn: 0.0020304	total: 12m 9s	remaining: 5m 4s
7254:	learn: 0.0014916	total: 12m 8s	remaining: 4m 35s
7389:	learn: 0.0014707	total: 12m 8s	remaining: 4m 17s
6716:	learn: 0.0013967	total: 12m 9s	remaining: 5m 56s
7055:	learn: 0.0020303	total: 12m 9s	remaining: 5m 4s
7262:	learn: 0.0015240	total: 12m 8s	remaining: 4m 34s
7255:	learn: 0.0014916	total: 12m 9s	remaining: 4m 35s
7390:	learn: 0.0014707	total: 12m 9s	remaining: 4m 17s
7056:	learn: 0.0020303	total: 12m 9s	remaining: 5m 4s
7263:	learn: 0.0015240	total: 12m 8s	remaining: 4m 34s
7256:	learn: 0.0014916	total: 12m 9s	remaining: 4m 35s
6717:	learn: 0.0013966	total: 12m 9s	remaining: 5m 56s
7391:	learn: 0.0014707	total: 12m 9s	remaining: 4m 17s
7057:	learn: 0.0020303	total: 12m 9s	remaining: 5m 3s
7257:	learn: 0.0014916	total: 12m 9s	remaining: 4m 35s
7264:	learn: 0.0015240	total: 12m 9s	remaining: 4m 34s
7258:	learn: 0.0014916	total: 12m 9s	remaining: 4m 35s
7392:	learn: 0.0014707	total: 12m 9s	remaining: 4m 17s
7058:	learn: 0.0020303	total: 12m 9s	remaining: 5m 3s
6718:	learn: 0.0013963	total: 12m 9s	remaining: 5m 56s
7259:	learn: 0.0014916	total: 12m 9s	remaining: 4m 35s
7265:	learn: 0.0015240	total: 12m 9s	remaining: 4m 34s
7393:	learn: 0.0014707	total: 12m 9s	remaining: 4m 17s
7266:	learn: 0.0015240	total: 12m 9s	remaining: 4m 34s
6719:	learn: 0.0013962	total: 12m 9s	remaining: 5m 56s
7059:	learn: 0.0020303	total: 12m 9s	remaining: 5m 3s
7260:	learn: 0.0014916	total: 12m 9s	remaining: 4m 35s
7394:	learn: 0.0014707	total: 12m 9s	remaining: 4m 16s
7267:	learn: 0.0015235	total: 12m 9s	remaining: 4m 34s
7261:	learn: 0.0014911	total: 12m 9s	remaining: 4m 35s
6720:	learn: 0.0013962	total: 12m 9s	remaining: 5m 55s
7060:	learn: 0.0020303	total: 12m 9s	remaining: 5m 3s
7395:	learn: 0.0014707	total: 12m 9s	remaining: 4m 16s
7268:	learn: 0.0015235	total: 12m 9s	remaining: 4m 34s
6721:	learn: 0.0013958	total: 12m 9s	remaining: 5m 55s
7262:	learn: 0.0014911	total: 12m 9s	remaining: 4m 34s
7061:	learn: 0.0020303	total: 12m 9s	remaining: 5m 3s
7396:	learn: 0.0014707	total: 12m 9s	remaining: 4m 16s
7269:	learn: 0.0015235	total: 12m 9s	remaining: 4m 33s
7062:	learn: 0.0020295	total: 12m 9s	remaining: 5m 3s
7263:	learn: 0.0014911	total: 12m 9s	remaining: 4m 34s
6722:	learn: 0.0013958	total: 12m 9s	remaining: 5m 55s
7397:	learn: 0.0014707	total: 12m 9s	remaining: 4m 16s
7270:	learn: 0.0015235	total: 12m 9s	remaining: 4m 33s
6723:	learn: 0.0013958	total: 12m 9s	remaining: 5m 55s
7264:	learn: 0.0014911	total: 12m 9s	remaining: 4m 34s
7398:	learn: 0.0014707	total: 12m 9s	remaining: 4m 16s
7063:	learn: 0.0020295	total: 12m 9s	remaining: 5m 3s
7271:	learn: 0.0015235	total: 12m 9s	remaining: 4m 33s
7272:	learn: 0.0015235	total: 12m 9s	remaining: 4m 33s
6724:	learn: 0.0013958	total: 12m 9s	remaining: 5m 55s
7265:	learn: 0.0014911	total: 12m 9s	remaining: 4m 34s
7399:	learn: 0.0014707	total: 12m 9s	remaining: 4m 16s
7064:	learn: 0.0020295	total: 12m 10s	remaining: 5m 3s
7273:	learn: 0.0015235	total: 12m 9s	remaining: 4m 33s
6725:	learn: 0.0013958	total: 12m 10s	remaining: 5m 55s
7400:	learn: 0.0014707	total: 12m 9s	remaining: 4m 16s
7266:	learn: 0.0014911	total: 12m 10s	remaining: 4m 34s
7065:	learn: 0.0020295	total: 12m 10s	remaining: 5m 3s
7274:	learn: 0.0015235	total: 12m 9s	remaining: 4m 33s
6726:	learn: 0.0013958	total: 12m 10s	remaining: 5m 55s
7401:	learn: 0.0014707	total: 12m 10s	remaining: 4m 16s
7267:	learn: 0.0014911	total: 12m 10s	remaining: 4m 34s
7066:	learn: 0.0020295	total: 12m 10s	remaining: 5m 3s
7275:	learn: 0.0015235	total: 12m 10s	remaining: 4m 33s
6727:	learn: 0.0013954	total: 12m 10s	remaining: 5m 55s
7268:	learn: 0.0014911	total: 12m 10s	remaining: 4m 34s
7402:	learn: 0.0014707	total: 12m 10s	remaining: 4m 16s
7067:	learn: 0.0020295	total: 12m 10s	remaining: 5m 2s
7276:	learn: 0.0015235	total: 12m 10s	remaining: 4m 33s
6728:	learn: 0.0013954	total: 12m 10s	remaining: 5m 55s
7269:	learn: 0.0014911	total: 12m 10s	remaining: 4m 34s
7403:	learn: 0.0014707	total: 12m 10s	remaining: 4m 16s
7277:	learn: 0.0015234	total: 12m 10s	remaining: 4m 33s
7068:	learn: 0.0020295	total: 12m 10s	remaining: 5m 2s
6729:	learn: 0.0013954	total: 12m 10s	remaining: 5m 54s
7270:	learn: 0.0014911	total: 12m 10s	remaining: 4m 34s
7069:	learn: 0.0020296	total: 12m 10s	remaining: 5m 2s
7404:	learn: 0.0014704	total: 12m 10s	remaining: 4m 15s
7278:	learn: 0.0015234	total: 12m 10s	remaining: 4m 32s
6730:	learn: 0.0013954	total: 12m 10s	remaining: 5m 54s
7271:	learn: 0.0014911	total: 12m 10s	remaining: 4m 34s
7405:	learn: 0.0014697	total: 12m 10s	remaining: 4m 15s
7070:	learn: 0.0020295	total: 12m 10s	remaining: 5m 2s
7279:	learn: 0.0015234	total: 12m 10s	remaining: 4m 32s
6731:	learn: 0.0013952	total: 12m 10s	remaining: 5m 54s
7272:	learn: 0.0014911	total: 12m 10s	remaining: 4m 33s
7071:	learn: 0.0020296	total: 12m 10s	remaining: 5m 2s
7280:	learn: 0.0015234	total: 12m 10s	remaining: 4m 32s
7406:	learn: 0.0014697	total: 12m 10s	remaining: 4m 15s
7273:	learn: 0.0014911	total: 12m 10s	remaining: 4m 33s
6732:	learn: 0.0013952	total: 12m 10s	remaining: 5m 54s
7072:	learn: 0.0020296	total: 12m 10s	remaining: 5m 2s
7281:	learn: 0.0015234	total: 12m 10s	remaining: 4m 32s
7407:	learn: 0.0014697	total: 12m 10s	remaining: 4m 15s
7274:	learn: 0.0014911	total: 12m 10s	remaining: 4m 33s
6733:	learn: 0.0013951	total: 12m 10s	remaining: 5m 54s
7073:	learn: 0.0020296	total: 12m 10s	remaining: 5m 2s
7282:	learn: 0.0015234	total: 12m 10s	remaining: 4m 32s
7408:	learn: 0.0014697	total: 12m 10s	remaining: 4m 15s
7275:	learn: 0.0014911	total: 12m 10s	remaining: 4m 33s
7074:	learn: 0.0020288	total: 12m 11s	remaining: 5m 2s
6734:	learn: 0.0013951	total: 12m 11s	remaining: 5m 54s
7283:	learn: 0.0015234	total: 12m 10s	remaining: 4m 32s
7276:	learn: 0.0014911	total: 12m 11s	remaining: 4m 33s
7409:	learn: 0.0014697	total: 12m 10s	remaining: 4m 15s
7284:	learn: 0.0015234	total: 12m 10s	remaining: 4m 32s
6735:	learn: 0.0013951	total: 12m 11s	remaining: 5m 54s
7075:	learn: 0.0020287	total: 12m 11s	remaining: 5m 2s
7410:	learn: 0.0014697	total: 12m 11s	remaining: 4m 15s
7277:	learn: 0.0014911	total: 12m 11s	remaining: 4m 33s
7285:	learn: 0.0015234	total: 12m 10s	remaining: 4m 32s
7076:	learn: 0.0020287	total: 12m 11s	remaining: 5m 2s
6736:	learn: 0.0013951	total: 12m 11s	remaining: 5m 54s
7411:	learn: 0.0014697	total: 12m 11s	remaining: 4m 15s
7278:	learn: 0.0014911	total: 12m 11s	remaining: 4m 33s
7286:	learn: 0.0015234	total: 12m 11s	remaining: 4m 32s
7077:	learn: 0.0020286	total: 12m 11s	remaining: 5m 1s
6737:	learn: 0.0013951	total: 12m 11s	remaining: 5m 54s
7412:	learn: 0.0014697	total: 12m 11s	remaining: 4m 15s
7287:	learn: 0.0015234	total: 12m 11s	remaining: 4m 32s
7279:	learn: 0.0014911	total: 12m 11s	remaining: 4m 33s
7078:	learn: 0.0020286	total: 12m 11s	remaining: 5m 1s
7413:	learn: 0.0014697	total: 12m 11s	remaining: 4m 15s
6738:	learn: 0.0013948	total: 12m 11s	remaining: 5m 53s
7280:	learn: 0.0014911	total: 12m 11s	remaining: 4m 33s
7288:	learn: 0.0015230	total: 12m 11s	remaining: 4m 31s
7079:	learn: 0.0020286	total: 12m 11s	remaining: 5m 1s
7414:	learn: 0.0014697	total: 12m 11s	remaining: 4m 14s
6739:	learn: 0.0013948	total: 12m 11s	remaining: 5m 53s
7281:	learn: 0.0014911	total: 12m 11s	remaining: 4m 33s
7289:	learn: 0.0015230	total: 12m 11s	remaining: 4m 31s
7080:	learn: 0.0020286	total: 12m 11s	remaining: 5m 1s
7415:	learn: 0.0014697	total: 12m 11s	remaining: 4m 14s
6740:	learn: 0.0013944	total: 12m 11s	remaining: 5m 53s
7290:	learn: 0.0015230	total: 12m 11s	remaining: 4m 31s
7282:	learn: 0.0014911	total: 12m 11s	remaining: 4m 32s
7081:	learn: 0.0020286	total: 12m 11s	remaining: 5m 1s
7416:	learn: 0.0014693	total: 12m 11s	remaining: 4m 14s
7291:	learn: 0.0015230	total: 12m 11s	remaining: 4m 31s
7283:	learn: 0.0014911	total: 12m 11s	remaining: 4m 32s
7082:	learn: 0.0020286	total: 12m 11s	remaining: 5m 1s
6741:	learn: 0.0013940	total: 12m 11s	remaining: 5m 53s
7417:	learn: 0.0014693	total: 12m 11s	remaining: 4m 14s
7292:	learn: 0.0015230	total: 12m 11s	remaining: 4m 31s
7083:	learn: 0.0020286	total: 12m 11s	remaining: 5m 1s
6742:	learn: 0.0013936	total: 12m 11s	remaining: 5m 53s
7284:	learn: 0.0014911	total: 12m 11s	remaining: 4m 32s
7418:	learn: 0.0014693	total: 12m 11s	remaining: 4m 14s
7084:	learn: 0.0020286	total: 12m 11s	remaining: 5m 1s
7293:	learn: 0.0015230	total: 12m 11s	remaining: 4m 31s
7285:	learn: 0.0014905	total: 12m 11s	remaining: 4m 32s
6743:	learn: 0.0013932	total: 12m 11s	remaining: 5m 53s
7085:	learn: 0.0020287	total: 12m 12s	remaining: 5m 1s
7419:	learn: 0.0014693	total: 12m 11s	remaining: 4m 14s
7286:	learn: 0.0014899	total: 12m 12s	remaining: 4m 32s
7294:	learn: 0.0015230	total: 12m 11s	remaining: 4m 31s
6744:	learn: 0.0013932	total: 12m 12s	remaining: 5m 53s
7086:	learn: 0.0020283	total: 12m 12s	remaining: 5m
7420:	learn: 0.0014693	total: 12m 12s	remaining: 4m 14s
7295:	learn: 0.0015230	total: 12m 11s	remaining: 4m 31s
7287:	learn: 0.0014899	total: 12m 12s	remaining: 4m 32s
7087:	learn: 0.0020283	total: 12m 12s	remaining: 5m
6745:	learn: 0.0013929	total: 12m 12s	remaining: 5m 53s
7421:	learn: 0.0014689	total: 12m 12s	remaining: 4m 14s
7296:	learn: 0.0015230	total: 12m 12s	remaining: 4m 31s
7288:	learn: 0.0014897	total: 12m 12s	remaining: 4m 32s
7088:	learn: 0.0020274	total: 12m 12s	remaining: 5m
6746:	learn: 0.0013929	total: 12m 12s	remaining: 5m 53s
7422:	learn: 0.0014689	total: 12m 12s	remaining: 4m 14s
7297:	learn: 0.0015230	total: 12m 12s	remaining: 4m 31s
7289:	learn: 0.0014897	total: 12m 12s	remaining: 4m 32s
7089:	learn: 0.0020266	total: 12m 12s	remaining: 5m
6747:	learn: 0.0013925	total: 12m 12s	remaining: 5m 52s
7298:	learn: 0.0015230	total: 12m 12s	remaining: 4m 30s
7423:	learn: 0.0014689	total: 12m 12s	remaining: 4m 14s
7090:	learn: 0.0020266	total: 12m 12s	remaining: 5m
7290:	learn: 0.0014897	total: 12m 12s	remaining: 4m 32s
6748:	learn: 0.0013922	total: 12m 12s	remaining: 5m 52s
7299:	learn: 0.0015227	total: 12m 12s	remaining: 4m 30s
7091:	learn: 0.0020266	total: 12m 12s	remaining: 5m
7424:	learn: 0.0014689	total: 12m 12s	remaining: 4m 14s
7291:	learn: 0.0014892	total: 12m 12s	remaining: 4m 32s
7300:	learn: 0.0015227	total: 12m 12s	remaining: 4m 30s
6749:	learn: 0.0013918	total: 12m 12s	remaining: 5m 52s

7092:	learn: 0.0020266	total: 12m 12s	remaining: 5m
7425:	learn: 0.0014689	total: 12m 12s	remaining: 4m 13s
7292:	learn: 0.0014892	total: 12m 12s	remaining: 4m 31s
7301:	learn: 0.0015227	total: 12m 12s	remaining: 4m 30s
6750:	learn: 0.0013918	total: 12m 12s	remaining: 5m 52s
7093:	learn: 0.0020266	total: 12m 12s	remaining: 5m
7293:	learn: 0.0014893	total: 12m 12s	remaining: 4m 31s
7426:	learn: 0.0014689	total: 12m 12s	remaining: 4m 13s
7302:	learn: 0.0015226	total: 12m 12s	remaining: 4m 30s
6751:	learn: 0.0013918	total: 12m 12s	remaining: 5m 52s
7094:	learn: 0.0020266	total: 12m 12s	remaining: 5m
7294:	learn: 0.0014892	total: 12m 12s	remaining: 4m 31s
7303:	learn: 0.0015226	total: 12m 12s	remaining: 4m 30s
7427:	learn: 0.0014689	total: 12m 12s	remaining: 4m 13s
6752:	learn: 0.0013918	total: 12m 12s	remaining: 5m 52s
7095:	learn: 0.0020266	total: 12m 13s	remaining: 4m 59s
7304:	learn: 0.0015226	total: 12m 12s	remaining: 4m 30s
7295:	learn: 0.0014891	total: 12m 12s	remaining: 4m 31s
7428:	learn: 0.0014689	total: 12m 12s	remaining: 4m 13s
6753:	learn: 0.0013917	total: 12m 13s	remaining: 5m 52s
7096:	learn: 0.0020266	total: 12m 13s	remaining: 4m 59s
7429:	learn: 0.0014689	total: 12m 13s	remaining: 4m 13s
7305:	learn: 0.0015226	total: 12m 12s	remaining: 4m 30s
7296:	learn: 0.0014890	total: 12m 13s	remaining: 4m 31s
6754:	learn: 0.0013913	total: 12m 13s	remaining: 5m 52s
7097:	learn: 0.0020266	total: 12m 13s	remaining: 4m 59s
7297:	learn: 0.0014890	total: 12m 13s	remaining: 4m 31s
7430:	learn: 0.0014686	total: 12m 13s	remaining: 4m 13s
7306:	learn: 0.0015226	total: 12m 12s	remaining: 4m 30s
6755:	learn: 0.0013909	total: 12m 13s	remaining: 5m 52s
7098:	learn: 0.0020265	total: 12m 13s	remaining: 4m 59s
7298:	learn: 0.0014890	total: 12m 13s	remaining: 4m 31s
7431:	learn: 0.0014686	total: 12m 13s	remaining: 4m 13s
7307:	learn: 0.0015222	total: 12m 13s	remaining: 4m 30s
6756:	learn: 0.0013906	total: 12m 13s	remaining: 5m 51s
7299:	learn: 0.0014890	total: 12m 13s	remaining: 4m 31s
7432:	learn: 0.0014686	total: 12m 13s	remaining: 4m 13s
7099:	learn: 0.0020265	total: 12m 13s	remaining: 4m 59s
6757:	learn: 0.0013906	total: 12m 13s	remaining: 5m 51s
7308:	learn: 0.0015222	total: 12m 13s	remaining: 4m 29s
7300:	learn: 0.0014885	total: 12m 13s	remaining: 4m 31s
7433:	learn: 0.0014686	total: 12m 13s	remaining: 4m 13s
7100:	learn: 0.0020265	total: 12m 13s	remaining: 4m 59s
6758:	learn: 0.0013906	total: 12m 13s	remaining: 5m 51s
7309:	learn: 0.0015220	total: 12m 13s	remaining: 4m 29s
7301:	learn: 0.0014885	total: 12m 13s	remaining: 4m 31s
7101:	learn: 0.0020265	total: 12m 13s	remaining: 4m 59s
7434:	learn: 0.0014686	total: 12m 13s	remaining: 4m 13s
7302:	learn: 0.0014881	total: 12m 13s	remaining: 4m 30s
7102:	learn: 0.0020265	total: 12m 13s	remaining: 4m 59s
6759:	learn: 0.0013906	total: 12m 13s	remaining: 5m 51s
7310:	learn: 0.0015220	total: 12m 13s	remaining: 4m 29s
7435:	learn: 0.0014683	total: 12m 13s	remaining: 4m 12s
7303:	learn: 0.0014881	total: 12m 13s	remaining: 4m 30s
7311:	learn: 0.0015220	total: 12m 13s	remaining: 4m 29s
7103:	learn: 0.0020265	total: 12m 13s	remaining: 4m 59s
6760:	learn: 0.0013906	total: 12m 13s	remaining: 5m 51s
7436:	learn: 0.0014683	total: 12m 13s	remaining: 4m 12s
7304:	learn: 0.0014881	total: 12m 13s	remaining: 4m 30s
7437:	learn: 0.0014683	total: 12m 13s	remaining: 4m 12s
7312:	learn: 0.0015216	total: 12m 13s	remaining: 4m 29s
7104:	learn: 0.0020265	total: 12m 13s	remaining: 4m 59s
6761:	learn: 0.0013906	total: 12m 13s	remaining: 5m 51s
7305:	learn: 0.0014881	total: 12m 13s	remaining: 4m 30s
7306:	learn: 0.0014876	total: 12m 13s	remaining: 4m 30s
7438:	learn: 0.0014683	total: 12m 13s	remaining: 4m 12s
7105:	learn: 0.0020265	total: 12m 14s	remaining: 4m 58s
7313:	learn: 0.0015216	total: 12m 13s	remaining: 4m 29s
6762:	learn: 0.0013906	total: 12m 14s	remaining: 5m 51s
7307:	learn: 0.0014876	total: 12m 14s	remaining: 4m 30s
7106:	learn: 0.0020265	total: 12m 14s	remaining: 4m 58s
6763:	learn: 0.0013904	total: 12m 14s	remaining: 5m 51s
7439:	learn: 0.0014683	total: 12m 14s	remaining: 4m 12s
7314:	learn: 0.0015216	total: 12m 13s	remaining: 4m 29s
7107:	learn: 0.0020265	total: 12m 14s	remaining: 4m 58s
7308:	learn: 0.0014872	total: 12m 14s	remaining: 4m 30s
6764:	learn: 0.0013904	total: 12m 14s	remaining: 5m 51s
7440:	learn: 0.0014683	total: 12m 14s	remaining: 4m 12s
7315:	learn: 0.0015216	total: 12m 13s	remaining: 4m 29s
7108:	learn: 0.0020265	total: 12m 14s	remaining: 4m 58s
6765:	learn: 0.0013904	total: 12m 14s	remaining: 5m 50s
7309:	learn: 0.0014867	total: 12m 14s	remaining: 4m 30s
7441:	learn: 0.0014683	total: 12m 14s	remaining: 4m 12s
7316:	learn: 0.0015216	total: 12m 14s	remaining: 4m 29s
7109:	learn: 0.0020265	total: 12m 14s	remaining: 4m 58s
6766:	learn: 0.0013903	total: 12m 14s	remaining: 5m 50s
7310:	learn: 0.0014862	total: 12m 14s	remaining: 4m 30s
7317:	learn: 0.0015216	total: 12m 14s	remaining: 4m 29s
7110:	learn: 0.0020265	total: 12m 14s	remaining: 4m 58s
7442:	learn: 0.0014683	total: 12m 14s	remaining: 4m 12s
7443:	learn: 0.0014683	total: 12m 14s	remaining: 4m 12s
7111:	learn: 0.0020261	total: 12m 14s	remaining: 4m 58s
6767:	learn: 0.0013900	total: 12m 14s	remaining: 5m 50s
7318:	learn: 0.0015216	total: 12m 14s	remaining: 4m 28s
7444:	learn: 0.0014682	total: 12m 14s	remaining: 4m 12s
7311:	learn: 0.0014856	total: 12m 14s	remaining: 4m 30s
7112:	learn: 0.0020255	total: 12m 14s	remaining: 4m 58s
7319:	learn: 0.0015213	total: 12m 14s	remaining: 4m 28s
6768:	learn: 0.0013900	total: 12m 14s	remaining: 5m 50s
7312:	learn: 0.0014851	total: 12m 14s	remaining: 4m 29s
7445:	learn: 0.0014682	total: 12m 14s	remaining: 4m 11s
7320:	learn: 0.0015212	total: 12m 14s	remaining: 4m 28s
7113:	learn: 0.0020250	total: 12m 14s	remaining: 4m 58s
7446:	learn: 0.0014681	total: 12m 14s	remaining: 4m 11s
7313:	learn: 0.0014847	total: 12m 14s	remaining: 4m 29s
6769:	learn: 0.0013900	total: 12m 14s	remaining: 5m 50s
7321:	learn: 0.0015212	total: 12m 14s	remaining: 4m 28s
7314:	learn: 0.0014842	total: 12m 14s	remaining: 4m 29s
7114:	learn: 0.0020250	total: 12m 14s	remaining: 4m 57s
7447:	learn: 0.0014681	total: 12m 14s	remaining: 4m 11s
7322:	learn: 0.0015212	total: 12m 14s	remaining: 4m 28s
7315:	learn: 0.0014842	total: 12m 14s	remaining: 4m 29s
6770:	learn: 0.0013900	total: 12m 14s	remaining: 5m 50s
7115:	learn: 0.0020250	total: 12m 14s	remaining: 4m 57s
7448:	learn: 0.0014681	total: 12m 14s	remaining: 4m 11s
7316:	learn: 0.0014839	total: 12m 14s	remaining: 4m 29s
7116:	learn: 0.0020242	total: 12m 15s	remaining: 4m 57s
7323:	learn: 0.0015212	total: 12m 14s	remaining: 4m 28s
6771:	learn: 0.0013900	total: 12m 15s	remaining: 5m 50s
7449:	learn: 0.0014681	total: 12m 14s	remaining: 4m 11s
7317:	learn: 0.0014833	total: 12m 15s	remaining: 4m 29s
7117:	learn: 0.0020242	total: 12m 15s	remaining: 4m 57s
7324:	learn: 0.0015212	total: 12m 14s	remaining: 4m 28s
6772:	learn: 0.0013900	total: 12m 15s	remaining: 5m 50s
7450:	learn: 0.0014681	total: 12m 15s	remaining: 4m 11s
7318:	learn: 0.0014828	total: 12m 15s	remaining: 4m 29s
7118:	learn: 0.0020242	total: 12m 15s	remaining: 4m 57s
7325:	learn: 0.0015211	total: 12m 14s	remaining: 4m 28s
7451:	learn: 0.0014681	total: 12m 15s	remaining: 4m 11s
6773:	learn: 0.0013900	total: 12m 15s	remaining: 5m 50s
7319:	learn: 0.0014823	total: 12m 15s	remaining: 4m 29s
7119:	learn: 0.0020242	total: 12m 15s	remaining: 4m 57s
7326:	learn: 0.0015211	total: 12m 15s	remaining: 4m 28s
6774:	learn: 0.0013900	total: 12m 15s	remaining: 5m 50s
7320:	learn: 0.0014819	total: 12m 15s	remaining: 4m 29s
7452:	learn: 0.0014681	total: 12m 15s	remaining: 4m 11s
7120:	learn: 0.0020242	total: 12m 15s	remaining: 4m 57s
7327:	learn: 0.0015211	total: 12m 15s	remaining: 4m 28s
7321:	learn: 0.0014814	total: 12m 15s	remaining: 4m 28s
7121:	learn: 0.0020234	total: 12m 15s	remaining: 4m 57s
7453:	learn: 0.0014681	total: 12m 15s	remaining: 4m 11s
6775:	learn: 0.0013900	total: 12m 15s	remaining: 5m 49s
7328:	learn: 0.0015211	total: 12m 15s	remaining: 4m 27s
7322:	learn: 0.0014809	total: 12m 15s	remaining: 4m 28s
7454:	learn: 0.0014681	total: 12m 15s	remaining: 4m 11s
7122:	learn: 0.0020234	total: 12m 15s	remaining: 4m 57s
6776:	learn: 0.0013900	total: 12m 15s	remaining: 5m 49s
7323:	learn: 0.0014804	total: 12m 15s	remaining: 4m 28s
7455:	learn: 0.0014681	total: 12m 15s	remaining: 4m 10s
7330:	learn: 0.0015211	total: 12m 15s	remaining: 4m 27s
7123:	learn: 0.0020234	total: 12m 15s	remaining: 4m 57s
6777:	learn: 0.0013900	total: 12m 15s	remaining: 5m 49s
7456:	learn: 0.0014681	total: 12m 15s	remaining: 4m 10s
7324:	learn: 0.0014799	total: 12m 15s	remaining: 4m 28s
7331:	learn: 0.0015206	total: 12m 15s	remaining: 4m 27s
7124:	learn: 0.0020234	total: 12m 15s	remaining: 4m 56s
7457:	learn: 0.0014681	total: 12m 15s	remaining: 4m 10s
6778:	learn: 0.0013900	total: 12m 15s	remaining: 5m 49s
7325:	learn: 0.0014794	total: 12m 15s	remaining: 4m 28s
7332:	learn: 0.0015206	total: 12m 15s	remaining: 4m 27s
7125:	learn: 0.0020234	total: 12m 15s	remaining: 4m 56s
7458:	learn: 0.0014678	total: 12m 15s	remaining: 4m 10s
7333:	learn: 0.0015206	total: 12m 15s	remaining: 4m 27s
7326:	learn: 0.0014794	total: 12m 15s	remaining: 4m 28s
7126:	learn: 0.0020234	total: 12m 15s	remaining: 4m 56s
6779:	learn: 0.0013896	total: 12m 15s	remaining: 5m 49s
7459:	learn: 0.0014675	total: 12m 15s	remaining: 4m 10s
7334:	learn: 0.0015206	total: 12m 15s	remaining: 4m 27s
7327:	learn: 0.0014788	total: 12m 16s	remaining: 4m 28s
7127:	learn: 0.0020234	total: 12m 16s	remaining: 4m 56s
6780:	learn: 0.0013896	total: 12m 16s	remaining: 5m 49s
7460:	learn: 0.0014675	total: 12m 15s	remaining: 4m 10s
7128:	learn: 0.0020234	total: 12m 16s	remaining: 4m 56s
7335:	learn: 0.0015205	total: 12m 15s	remaining: 4m 27s
7328:	learn: 0.0014788	total: 12m 16s	remaining: 4m 28s
7461:	learn: 0.0014675	total: 12m 16s	remaining: 4m 10s
6781:	learn: 0.0013896	total: 12m 16s	remaining: 5m 49s
7329:	learn: 0.0014783	total: 12m 16s	remaining: 4m 28s
7129:	learn: 0.0020233	total: 12m 16s	remaining: 4m 56s
7336:	learn: 0.0015206	total: 12m 16s	remaining: 4m 27s
7462:	learn: 0.0014675	total: 12m 16s	remaining: 4m 10s
7330:	learn: 0.0014783	total: 12m 16s	remaining: 4m 28s
6782:	learn: 0.0013896	total: 12m 16s	remaining: 5m 49s
7130:	learn: 0.0020232	total: 12m 16s	remaining: 4m 56s
7463:	learn: 0.0014675	total: 12m 16s	remaining: 4m 10s
7337:	learn: 0.0015205	total: 12m 16s	remaining: 4m 27s
7331:	learn: 0.0014782	total: 12m 16s	remaining: 4m 27s
6783:	learn: 0.0013897	total: 12m 16s	remaining: 5m 49s
7464:	learn: 0.0014675	total: 12m 16s	remaining: 4m 10s
7131:	learn: 0.0020232	total: 12m 16s	remaining: 4m 56s
7338:	learn: 0.0015206	total: 12m 16s	remaining: 4m 26s
7332:	learn: 0.0014779	total: 12m 16s	remaining: 4m 27s
6784:	learn: 0.0013894	total: 12m 16s	remaining: 5m 48s
7465:	learn: 0.0014675	total: 12m 16s	remaining: 4m 9s
7132:	learn: 0.0020226	total: 12m 16s	remaining: 4m 56s
7339:	learn: 0.0015205	total: 12m 16s	remaining: 4m 26s
6785:	learn: 0.0013894	total: 12m 16s	remaining: 5m 48s
7333:	learn: 0.0014779	total: 12m 16s	remaining: 4m 27s
7466:	learn: 0.0014675	total: 12m 16s	remaining: 4m 9s
7340:	learn: 0.0015205	total: 12m 16s	remaining: 4m 26s
7133:	learn: 0.0020226	total: 12m 16s	remaining: 4m 55s
6786:	learn: 0.0013892	total: 12m 16s	remaining: 5m 48s
7467:	learn: 0.0014675	total: 12m 16s	remaining: 4m 9s
7334:	learn: 0.0014779	total: 12m 16s	remaining: 4m 27s
7341:	learn: 0.0015205	total: 12m 16s	remaining: 4m 26s
7134:	learn: 0.0020226	total: 12m 16s	remaining: 4m 55s
6787:	learn: 0.0013892	total: 12m 16s	remaining: 5m 48s
7335:	learn: 0.0014779	total: 12m 16s	remaining: 4m 27s
7468:	learn: 0.0014675	total: 12m 16s	remaining: 4m 9s
7342:	learn: 0.0015205	total: 12m 16s	remaining: 4m 26s
7135:	learn: 0.0020226	total: 12m 16s	remaining: 4m 55s
6788:	learn: 0.0013892	total: 12m 16s	remaining: 5m 48s
7336:	learn: 0.0014779	total: 12m 16s	remaining: 4m 27s
7136:	learn: 0.0020226	total: 12m 16s	remaining: 4m 55s
7469:	learn: 0.0014674	total: 12m 16s	remaining: 4m 9s
7343:	learn: 0.0015205	total: 12m 16s	remaining: 4m 26s
6789:	learn: 0.0013888	total: 12m 16s	remaining: 5m 48s
7337:	learn: 0.0014779	total: 12m 17s	remaining: 4m 27s
7137:	learn: 0.0020221	total: 12m 17s	remaining: 4m 55s
7344:	learn: 0.0015205	total: 12m 16s	remaining: 4m 26s
7470:	learn: 0.0014675	total: 12m 16s	remaining: 4m 9s
6790:	learn: 0.0013885	total: 12m 17s	remaining: 5m 48s
7338:	learn: 0.0014779	total: 12m 17s	remaining: 4m 27s
7471:	learn: 0.0014675	total: 12m 17s	remaining: 4m 9s
7138:	learn: 0.0020216	total: 12m 17s	remaining: 4m 55s
6791:	learn: 0.0013885	total: 12m 17s	remaining: 5m 48s
7345:	learn: 0.0015206	total: 12m 16s	remaining: 4m 26s
7472:	learn: 0.0014675	total: 12m 17s	remaining: 4m 9s
7139:	learn: 0.0020211	total: 12m 17s	remaining: 4m 55s
7339:	learn: 0.0014779	total: 12m 17s	remaining: 4m 27s
7346:	learn: 0.0015205	total: 12m 17s	remaining: 4m 26s
6792:	learn: 0.0013885	total: 12m 17s	remaining: 5m 48s
7473:	learn: 0.0014675	total: 12m 17s	remaining: 4m 9s
7340:	learn: 0.0014779	total: 12m 17s	remaining: 4m 27s
7140:	learn: 0.0020211	total: 12m 17s	remaining: 4m 55s
7347:	learn: 0.0015205	total: 12m 17s	remaining: 4m 26s
6793:	learn: 0.0013885	total: 12m 17s	remaining: 5m 47s
7474:	learn: 0.0014675	total: 12m 17s	remaining: 4m 9s
7141:	learn: 0.0020211	total: 12m 17s	remaining: 4m 55s
7341:	learn: 0.0014779	total: 12m 17s	remaining: 4m 26s
7348:	learn: 0.0015205	total: 12m 17s	remaining: 4m 25s
6794:	learn: 0.0013885	total: 12m 17s	remaining: 5m 47s
7475:	learn: 0.0014675	total: 12m 17s	remaining: 4m 8s
7142:	learn: 0.0020211	total: 12m 17s	remaining: 4m 55s
7342:	learn: 0.0014779	total: 12m 17s	remaining: 4m 26s
7349:	learn: 0.0015205	total: 12m 17s	remaining: 4m 25s
6795:	learn: 0.0013885	total: 12m 17s	remaining: 5m 47s
7476:	learn: 0.0014675	total: 12m 17s	remaining: 4m 8s
7143:	learn: 0.0020211	total: 12m 17s	remaining: 4m 54s
7343:	learn: 0.0014775	total: 12m 17s	remaining: 4m 26s
7350:	learn: 0.0015205	total: 12m 17s	remaining: 4m 25s
6796:	learn: 0.0013885	total: 12m 17s	remaining: 5m 47s
7477:	learn: 0.0014671	total: 12m 17s	remaining: 4m 8s
7351:	learn: 0.0015205	total: 12m 17s	remaining: 4m 25s
7344:	learn: 0.0014775	total: 12m 17s	remaining: 4m 26s
7478:	learn: 0.0014667	total: 12m 17s	remaining: 4m 8s
7144:	learn: 0.0020211	total: 12m 17s	remaining: 4m 54s
6797:	learn: 0.0013885	total: 12m 17s	remaining: 5m 47s
7352:	learn: 0.0015205	total: 12m 17s	remaining: 4m 25s
7345:	learn: 0.0014775	total: 12m 17s	remaining: 4m 26s
7479:	learn: 0.0014667	total: 12m 17s	remaining: 4m 8s
6798:	learn: 0.0013885	total: 12m 17s	remaining: 5m 47s
7145:	learn: 0.0020211	total: 12m 17s	remaining: 4m 54s
7353:	learn: 0.0015205	total: 12m 17s	remaining: 4m 25s
7346:	learn: 0.0014775	total: 12m 17s	remaining: 4m 26s
6799:	learn: 0.0013885	total: 12m 17s	remaining: 5m 47s
7480:	learn: 0.0014667	total: 12m 17s	remaining: 4m 8s
7146:	learn: 0.0020211	total: 12m 18s	remaining: 4m 54s
7354:	learn: 0.0015205	total: 12m 17s	remaining: 4m 25s
7347:	learn: 0.0014773	total: 12m 18s	remaining: 4m 26s
6800:	learn: 0.0013885	total: 12m 18s	remaining: 5m 47s
7481:	learn: 0.0014667	total: 12m 17s	remaining: 4m 8s
7147:	learn: 0.0020211	total: 12m 18s	remaining: 4m 54s
7355:	learn: 0.0015205	total: 12m 17s	remaining: 4m 25s
7348:	learn: 0.0014768	total: 12m 18s	remaining: 4m 26s
7482:	learn: 0.0014667	total: 12m 18s	remaining: 4m 8s
6801:	learn: 0.0013884	total: 12m 18s	remaining: 5m 47s
7356:	learn: 0.0015205	total: 12m 17s	remaining: 4m 25s
7148:	learn: 0.0020211	total: 12m 18s	remaining: 4m 54s
7349:	learn: 0.0014768	total: 12m 18s	remaining: 4m 26s
7483:	learn: 0.0014667	total: 12m 18s	remaining: 4m 8s
6802:	learn: 0.0013884	total: 12m 18s	remaining: 5m 46s
7357:	learn: 0.0015201	total: 12m 18s	remaining: 4m 25s
7149:	learn: 0.0020211	total: 12m 18s	remaining: 4m 54s
7350:	learn: 0.0014768	total: 12m 18s	remaining: 4m 26s
7484:	learn: 0.0014667	total: 12m 18s	remaining: 4m 8s
6803:	learn: 0.0013885	total: 12m 18s	remaining: 5m 46s
7150:	learn: 0.0020205	total: 12m 18s	remaining: 4m 54s
7358:	learn: 0.0015201	total: 12m 18s	remaining: 4m 24s
7485:	learn: 0.0014667	total: 12m 18s	remaining: 4m 7s
7351:	learn: 0.0014768	total: 12m 18s	remaining: 4m 25s
ing: 5m 3s

7396:	learn: 0.0014707	total: 12m 9s	remainin7359:	learn: 0.0015201	total: 12m 18s	remaining: 4m 24s
6804:	learn: 0.0013881	total: 12m 18s	remaining: 5m 46s
7151:	learn: 0.0020195	total: 12m 18s	remaining: 4m 54s
7352:	learn: 0.0014768	total: 12m 18s	remaining: 4m 25s
7486:	learn: 0.0014667	total: 12m 18s	remaining: 4m 7s
6805:	learn: 0.0013881	total: 12m 18s	remaining: 5m 46s
7360:	learn: 0.0015201	total: 12m 18s	remaining: 4m 24s
7152:	learn: 0.0020195	total: 12m 18s	remaining: 4m 54s
7487:	learn: 0.0014667	total: 12m 18s	remaining: 4m 7s
7353:	learn: 0.0014768	total: 12m 18s	remaining: 4m 25s
6806:	learn: 0.0013881	total: 12m 18s	remaining: 5m 46s
7361:	learn: 0.0015201	total: 12m 18s	remaining: 4m 24s
7488:	learn: 0.0014667	total: 12m 18s	remaining: 4m 7s
7153:	learn: 0.0020195	total: 12m 18s	remaining: 4m 53s
7354:	learn: 0.0014768	total: 12m 18s	remaining: 4m 25s
6807:	learn: 0.0013881	total: 12m 18s	remaining: 5m 46s
7362:	learn: 0.0015201	total: 12m 18s	remaining: 4m 24s
7489:	learn: 0.0014663	total: 12m 18s	remaining: 4m 7s
7154:	learn: 0.0020195	total: 12m 18s	remaining: 4m 53s
7355:	learn: 0.0014768	total: 12m 18s	remaining: 4m 25s
6808:	learn: 0.0013881	total: 12m 18s	remaining: 5m 46s
7490:	learn: 0.0014660	total: 12m 18s	remaining: 4m 7s
7363:	learn: 0.0015201	total: 12m 18s	remaining: 4m 24s
7356:	learn: 0.0014768	total: 12m 18s	remaining: 4m 25s
7155:	learn: 0.0020195	total: 12m 18s	remaining: 4m 53s
7364:	learn: 0.0015201	total: 12m 18s	remaining: 4m 24s
6809:	learn: 0.0013881	total: 12m 19s	remaining: 5m 46s
7357:	learn: 0.0014768	total: 12m 19s	remaining: 4m 25s
7491:	learn: 0.0014660	total: 12m 18s	remaining: 4m 7s
7156:	learn: 0.0020195	total: 12m 19s	remaining: 4m 53s
6810:	learn: 0.0013877	total: 12m 19s	remaining: 5m 46s
7365:	learn: 0.0015201	total: 12m 18s	remaining: 4m 24s
7492:	learn: 0.0014660	total: 12m 19s	remaining: 4m 7s
7358:	learn: 0.0014768	total: 12m 19s	remaining: 4m 25s
7157:	learn: 0.0020195	total: 12m 19s	remaining: 4m 53s
7359:	learn: 0.0014768	total: 12m 19s	remaining: 4m 25s
7158:	learn: 0.0020189	total: 12m 19s	remaining: 4m 53s
7366:	learn: 0.0015201	total: 12m 19s	remaining: 4m 24s
6811:	learn: 0.0013877	total: 12m 19s	remaining: 5m 45s
7493:	learn: 0.0014660	total: 12m 19s	remaining: 4m 7s
7360:	learn: 0.0014768	total: 12m 19s	remaining: 4m 25s
7159:	learn: 0.0020189	total: 12m 19s	remaining: 4m 53s
7367:	learn: 0.0015201	total: 12m 19s	remaining: 4m 24s
6812:	learn: 0.0013877	total: 12m 19s	remaining: 5m 45s
7494:	learn: 0.0014660	total: 12m 19s	remaining: 4m 7s
7160:	learn: 0.0020189	total: 12m 19s	remaining: 4m 53s
7368:	learn: 0.0015201	total: 12m 19s	remaining: 4m 23s
7361:	learn: 0.0014768	total: 12m 19s	remaining: 4m 24s
6813:	learn: 0.0013877	total: 12m 19s	remaining: 5m 45s
7369:	learn: 0.0015201	total: 12m 19s	remaining: 4m 23s
7495:	learn: 0.0014660	total: 12m 19s	remaining: 4m 6s
7362:	learn: 0.0014764	total: 12m 19s	remaining: 4m 24s
7161:	learn: 0.0020189	total: 12m 19s	remaining: 4m 53s
6814:	learn: 0.0013877	total: 12m 19s	remaining: 5m 45s
7363:	learn: 0.0014759	total: 12m 19s	remaining: 4m 24s
7496:	learn: 0.0014660	total: 12m 19s	remaining: 4m 6s
7370:	learn: 0.0015201	total: 12m 19s	remaining: 4m 23s
7162:	learn: 0.0020189	total: 12m 19s	remaining: 4m 52s
6815:	learn: 0.0013877	total: 12m 19s	remaining: 5m 45s
7497:	learn: 0.0014660	total: 12m 19s	remaining: 4m 6s
7364:	learn: 0.0014753	total: 12m 19s	remaining: 4m 24s
7371:	learn: 0.0015201	total: 12m 19s	remaining: 4m 23s
7498:	learn: 0.0014660	total: 12m 19s	remaining: 4m 6s
6816:	learn: 0.0013877	total: 12m 19s	remaining: 5m 45s
7163:	learn: 0.0020189	total: 12m 19s	remaining: 4m 52s
7365:	learn: 0.0014749	total: 12m 19s	remaining: 4m 24s
7372:	learn: 0.0015201	total: 12m 19s	remaining: 4m 23s
7499:	learn: 0.0014660	total: 12m 19s	remaining: 4m 6s
7164:	learn: 0.0020189	total: 12m 19s	remaining: 4m 52s
6817:	learn: 0.0013877	total: 12m 19s	remaining: 5m 45s
7366:	learn: 0.0014749	total: 12m 19s	remaining: 4m 24s
7373:	learn: 0.0015201	total: 12m 19s	remaining: 4m 23s
7165:	learn: 0.0020189	total: 12m 19s	remaining: 4m 52s
7500:	learn: 0.0014655	total: 12m 19s	remaining: 4m 6s
6818:	learn: 0.0013874	total: 12m 19s	remaining: 5m 45s
7367:	learn: 0.0014749	total: 12m 19s	remaining: 4m 24s
7374:	learn: 0.0015201	total: 12m 19s	remaining: 4m 23s
7166:	learn: 0.0020189	total: 12m 20s	remaining: 4m 52s
7501:	learn: 0.0014655	total: 12m 19s	remaining: 4m 6s
7368:	learn: 0.0014749	total: 12m 20s	remaining: 4m 24s
6819:	learn: 0.0013874	total: 12m 20s	remaining: 5m 45s
7375:	learn: 0.0015201	total: 12m 19s	remaining: 4m 23s
7167:	learn: 0.0020189	total: 12m 20s	remaining: 4m 52s
7369:	learn: 0.0014749	total: 12m 20s	remaining: 4m 24s
7502:	learn: 0.0014652	total: 12m 20s	remaining: 4m 6s
6820:	learn: 0.0013874	total: 12m 20s	remaining: 5m 44s
7376:	learn: 0.0015201	total: 12m 19s	remaining: 4m 23s
7168:	learn: 0.0020189	total: 12m 20s	remaining: 4m 52s
7503:	learn: 0.0014652	total: 12m 20s	remaining: 4m 6s
7370:	learn: 0.0014749	total: 12m 20s	remaining: 4m 24s
7377:	learn: 0.0015201	total: 12m 20s	remaining: 4m 22s
7169:	learn: 0.0020184	total: 12m 20s	remaining: 4m 52s
6821:	learn: 0.0013874	total: 12m 20s	remaining: 5m 44s
7504:	learn: 0.0014652	total: 12m 20s	remaining: 4m 6s
7371:	learn: 0.0014749	total: 12m 20s	remaining: 4m 23s
7378:	learn: 0.0015201	total: 12m 20s	remaining: 4m 22s
7372:	learn: 0.0014749	total: 12m 20s	remaining: 4m 23s
7505:	learn: 0.0014648	total: 12m 20s	remaining: 4m 5s
6822:	learn: 0.0013874	total: 12m 20s	remaining: 5m 44s
7170:	learn: 0.0020179	total: 12m 20s	remaining: 4m 52s
7373:	learn: 0.0014749	total: 12m 20s	remaining: 4m 23s
7379:	learn: 0.0015201	total: 12m 20s	remaining: 4m 22s
7506:	learn: 0.0014648	total: 12m 20s	remaining: 4m 5s
6823:	learn: 0.0013874	total: 12m 20s	remaining: 5m 44s
7171:	learn: 0.0020179	total: 12m 20s	remaining: 4m 52s
7507:	learn: 0.0014648	total: 12m 20s	remaining: 4m 5s
7374:	learn: 0.0014749	total: 12m 20s	remaining: 4m 23s
7380:	learn: 0.0015201	total: 12m 20s	remaining: 4m 22s
6824:	learn: 0.0013874	total: 12m 20s	remaining: 5m 44s
7508:	learn: 0.0014648	total: 12m 20s	remaining: 4m 5s
7172:	learn: 0.0020179	total: 12m 20s	remaining: 4m 51s
7375:	learn: 0.0014744	total: 12m 20s	remaining: 4m 23s
7381:	learn: 0.0015201	total: 12m 20s	remaining: 4m 22s
6825:	learn: 0.0013874	total: 12m 20s	remaining: 5m 44s
7509:	learn: 0.0014648	total: 12m 20s	remaining: 4m 5s
7173:	learn: 0.0020174	total: 12m 20s	remaining: 4m 51s
7376:	learn: 0.0014738	total: 12m 20s	remaining: 4m 23s
7382:	learn: 0.0015201	total: 12m 20s	remaining: 4m 22s
7510:	learn: 0.0014648	total: 12m 20s	remaining: 4m 5s
6826:	learn: 0.0013874	total: 12m 20s	remaining: 5m 44s
7174:	learn: 0.0020166	total: 12m 20s	remaining: 4m 51s
7377:	learn: 0.0014733	total: 12m 20s	remaining: 4m 23s
7511:	learn: 0.0014648	total: 12m 20s	remaining: 4m 5s
7383:	learn: 0.0015201	total: 12m 20s	remaining: 4m 22s
7512:	learn: 0.0014644	total: 12m 20s	remaining: 4m 5s
6827:	learn: 0.0013874	total: 12m 20s	remaining: 5m 44s
7175:	learn: 0.0020166	total: 12m 21s	remaining: 4m 51s
7378:	learn: 0.0014733	total: 12m 21s	remaining: 4m 23s
7384:	learn: 0.0015201	total: 12m 20s	remaining: 4m 22s
7513:	learn: 0.0014644	total: 12m 20s	remaining: 4m 5s
6828:	learn: 0.0013874	total: 12m 21s	remaining: 5m 44s
7176:	learn: 0.0020166	total: 12m 21s	remaining: 4m 51s
7379:	learn: 0.0014733	total: 12m 21s	remaining: 4m 23s
7385:	learn: 0.0015201	total: 12m 20s	remaining: 4m 22s
6829:	learn: 0.0013874	total: 12m 21s	remaining: 5m 43s
7514:	learn: 0.0014644	total: 12m 21s	remaining: 4m 5s
7380:	learn: 0.0014731	total: 12m 21s	remaining: 4m 23s
7177:	learn: 0.0020162	total: 12m 21s	remaining: 4m 51s
7515:	learn: 0.0014644	total: 12m 21s	remaining: 4m 4s
7386:	learn: 0.0015201	total: 12m 21s	remaining: 4m 22s
6830:	learn: 0.0013874	total: 12m 21s	remaining: 5m 43s
7516:	learn: 0.0014644	total: 12m 21s	remaining: 4m 4s
7381:	learn: 0.0014731	total: 12m 21s	remaining: 4m 22s
7178:	learn: 0.0020161	total: 12m 21s	remaining: 4m 51s
7387:	learn: 0.0015201	total: 12m 21s	remaining: 4m 22s
6831:	learn: 0.0013874	total: 12m 21s	remaining: 5m 43s
7517:	learn: 0.0014644	total: 12m 21s	remaining: 4m 4s
7382:	learn: 0.0014727	total: 12m 21s	remaining: 4m 22s
7179:	learn: 0.0020161	total: 12m 21s	remaining: 4m 51s
7388:	learn: 0.0015201	total: 12m 21s	remaining: 4m 21s
6832:	learn: 0.0013874	total: 12m 21s	remaining: 5m 43s
7383:	learn: 0.0014727	total: 12m 21s	remaining: 4m 22s
7518:	learn: 0.0014644	total: 12m 21s	remaining: 4m 4s
7180:	learn: 0.0020161	total: 12m 21s	remaining: 4m 51s
7389:	learn: 0.0015201	total: 12m 21s	remaining: 4m 21s
6833:	learn: 0.0013874	total: 12m 21s	remaining: 5m 43s
7384:	learn: 0.0014722	total: 12m 21s	remaining: 4m 22s
7519:	learn: 0.0014644	total: 12m 21s	remaining: 4m 4s
7181:	learn: 0.0020161	total: 12m 21s	remaining: 4m 51s
7390:	learn: 0.0015201	total: 12m 21s	remaining: 4m 21s
6834:	learn: 0.0013874	total: 12m 21s	remaining: 5m 43s
7385:	learn: 0.0014719	total: 12m 21s	remaining: 4m 22s
7520:	learn: 0.0014644	total: 12m 21s	remaining: 4m 4s
7386:	learn: 0.0014719	total: 12m 21s	remaining: 4m 22s
7182:	learn: 0.0020156	total: 12m 21s	remaining: 4m 50s
7391:	learn: 0.0015201	total: 12m 21s	remaining: 4m 21s
6835:	learn: 0.0013874	total: 12m 21s	remaining: 5m 43s
7387:	learn: 0.0014714	total: 12m 21s	remaining: 4m 22s
7521:	learn: 0.0014644	total: 12m 21s	remaining: 4m 4s
7183:	learn: 0.0020151	total: 12m 21s	remaining: 4m 50s
6836:	learn: 0.0013874	total: 12m 21s	remaining: 5m 43s
7392:	learn: 0.0015196	total: 12m 21s	remaining: 4m 21s
7388:	learn: 0.0014714	total: 12m 21s	remaining: 4m 22s
7522:	learn: 0.0014644	total: 12m 21s	remaining: 4m 4s
7184:	learn: 0.0020144	total: 12m 22s	remaining: 4m 50s
7389:	learn: 0.0014714	total: 12m 21s	remaining: 4m 22s
6837:	learn: 0.0013874	total: 12m 22s	remaining: 5m 43s
7393:	learn: 0.0015192	total: 12m 21s	remaining: 4m 21s
7523:	learn: 0.0014644	total: 12m 21s	remaining: 4m 4s
7185:	learn: 0.0020136	total: 12m 22s	remaining: 4m 50s
7390:	learn: 0.0014711	total: 12m 22s	remaining: 4m 21s
6838:	learn: 0.0013874	total: 12m 22s	remaining: 5m 43s
7394:	learn: 0.0015192	total: 12m 21s	remaining: 4m 21s
7524:	learn: 0.0014641	total: 12m 22s	remaining: 4m 4s
7186:	learn: 0.0020129	total: 12m 22s	remaining: 4m 50s
6839:	learn: 0.0013871	total: 12m 22s	remaining: 5m 42s
7395:	learn: 0.0015192	total: 12m 21s	remaining: 4m 21s
7391:	learn: 0.0014712	total: 12m 22s	remaining: 4m 21s
7525:	learn: 0.0014637	total: 12m 22s	remaining: 4m 3s
6840:	learn: 0.0013867	total: 12m 22s	remaining: 5m 42s
7396:	learn: 0.0015192	total: 12m 22s	remaining: 4m 21s
7187:	learn: 0.0020124	total: 12m 22s	remaining: 4m 50s
7392:	learn: 0.0014708	total: 12m 22s	remaining: 4m 21s
7526:	learn: 0.0014637	total: 12m 22s	remaining: 4m 3s
7188:	learn: 0.0020118	total: 12m 22s	remaining: 4m 50s
6841:	learn: 0.0013867	total: 12m 22s	remaining: 5m 42s
7393:	learn: 0.0014704	total: 12m 22s	remaining: 4m 21s
7397:	learn: 0.0015192	total: 12m 22s	remaining: 4m 21s
7527:	learn: 0.0014637	total: 12m 22s	remaining: 4m 3s
7398:	learn: 0.0015188	total: 12m 22s	remaining: 4m 20s
7189:	learn: 0.0020114	total: 12m 22s	remaining: 4m 50s
6842:	learn: 0.0013867	total: 12m 22s	remaining: 5m 42s
7394:	learn: 0.0014704	total: 12m 22s	remaining: 4m 21s
7528:	learn: 0.0014637	total: 12m 22s	remaining: 4m 3s
7399:	learn: 0.0015188	total: 12m 22s	remaining: 4m 20s
7395:	learn: 0.0014699	total: 12m 22s	remaining: 4m 21s
7190:	learn: 0.0020108	total: 12m 22s	remaining: 4m 50s
6843:	learn: 0.0013866	total: 12m 22s	remaining: 5m 42s
7529:	learn: 0.0014637	total: 12m 22s	remaining: 4m 3s
7400:	learn: 0.0015189	total: 12m 22s	remaining: 4m 20s
7191:	learn: 0.0020108	total: 12m 22s	remaining: 4m 49s
6844:	learn: 0.0013866	total: 12m 22s	remaining: 5m 42s
7396:	learn: 0.0014699	total: 12m 22s	remaining: 4m 21s
7401:	learn: 0.0015188	total: 12m 22s	remaining: 4m 20s
6845:	learn: 0.0013865	total: 12m 22s	remaining: 5m 42s
7192:	learn: 0.0020103	total: 12m 22s	remaining: 4m 49s
7530:	learn: 0.0014637	total: 12m 22s	remaining: 4m 3s
7397:	learn: 0.0014695	total: 12m 22s	remaining: 4m 21s
7402:	learn: 0.0015184	total: 12m 22s	remaining: 4m 20s
6846:	learn: 0.0013865	total: 12m 22s	remaining: 5m 42s
7531:	learn: 0.0014637	total: 12m 22s	remaining: 4m 3s
7193:	learn: 0.0020098	total: 12m 22s	remaining: 4m 49s
7398:	learn: 0.0014691	total: 12m 22s	remaining: 4m 21s
7403:	learn: 0.0015184	total: 12m 22s	remaining: 4m 20s
7532:	learn: 0.0014637	total: 12m 22s	remaining: 4m 3s
6847:	learn: 0.0013865	total: 12m 22s	remaining: 5m 41s
7399:	learn: 0.0014686	total: 12m 23s	remaining: 4m 21s
7194:	learn: 0.0020092	total: 12m 23s	remaining: 4m 49s
7404:	learn: 0.0015184	total: 12m 22s	remaining: 4m 20s
7533:	learn: 0.0014637	total: 12m 23s	remaining: 4m 3s
6848:	learn: 0.0013865	total: 12m 23s	remaining: 5m 41s
7400:	learn: 0.0014682	total: 12m 23s	remaining: 4m 20s
7405:	learn: 0.0015182	total: 12m 22s	remaining: 4m 20s
7195:	learn: 0.0020084	total: 12m 23s	remaining: 4m 49s
7534:	learn: 0.0014637	total: 12m 23s	remaining: 4m 3s
7401:	learn: 0.0014682	total: 12m 23s	remaining: 4m 20s
7406:	learn: 0.0015183	total: 12m 22s	remaining: 4m 20s
6849:	learn: 0.0013865	total: 12m 23s	remaining: 5m 41s
7196:	learn: 0.0020074	total: 12m 23s	remaining: 4m 49s
7535:	learn: 0.0014636	total: 12m 23s	remaining: 4m 2s
7402:	learn: 0.0014682	total: 12m 23s	remaining: 4m 20s
6850:	learn: 0.0013865	total: 12m 23s	remaining: 5m 41s
7407:	learn: 0.0015182	total: 12m 23s	remaining: 4m 20s
7197:	learn: 0.0020067	total: 12m 23s	remaining: 4m 49s
7403:	learn: 0.0014682	total: 12m 23s	remaining: 4m 20s
7536:	learn: 0.0014633	total: 12m 23s	remaining: 4m 2s
7198:	learn: 0.0020060	total: 12m 23s	remaining: 4m 49s
7537:	learn: 0.0014627	total: 12m 23s	remaining: 4m 2s
6851:	learn: 0.0013861	total: 12m 23s	remaining: 5m 41s
7404:	learn: 0.0014682	total: 12m 23s	remaining: 4m 20s
7408:	learn: 0.0015182	total: 12m 23s	remaining: 4m 19s
7199:	learn: 0.0020056	total: 12m 23s	remaining: 4m 49s
7538:	learn: 0.0014623	total: 12m 23s	remaining: 4m 2s
6852:	learn: 0.0013860	total: 12m 23s	remaining: 5m 41s
7405:	learn: 0.0014682	total: 12m 23s	remaining: 4m 20s
7409:	learn: 0.0015183	total: 12m 23s	remaining: 4m 19s
7539:	learn: 0.0014623	total: 12m 23s	remaining: 4m 2s
6853:	learn: 0.0013858	total: 12m 23s	remaining: 5m 41s
7200:	learn: 0.0020049	total: 12m 23s	remaining: 4m 49s
7406:	learn: 0.0014682	total: 12m 23s	remaining: 4m 20s
7540:	learn: 0.0014619	total: 12m 23s	remaining: 4m 2s
7410:	learn: 0.0015183	total: 12m 23s	remaining: 4m 19s
6854:	learn: 0.0013858	total: 12m 23s	remaining: 5m 41s
7201:	learn: 0.0020044	total: 12m 23s	remaining: 4m 48s
7407:	learn: 0.0014679	total: 12m 23s	remaining: 4m 20s
7541:	learn: 0.0014618	total: 12m 23s	remaining: 4m 2s
7411:	learn: 0.0015182	total: 12m 23s	remaining: 4m 19s
6855:	learn: 0.0013858	total: 12m 23s	remaining: 5m 41s
7202:	learn: 0.0020044	total: 12m 23s	remaining: 4m 48s
7408:	learn: 0.0014678	total: 12m 23s	remaining: 4m 20s
7542:	learn: 0.0014615	total: 12m 23s	remaining: 4m 2s
7412:	learn: 0.0015182	total: 12m 23s	remaining: 4m 19s
6856:	learn: 0.0013858	total: 12m 23s	remaining: 5m 40s
7543:	learn: 0.0014615	total: 12m 23s	remaining: 4m 2s
7203:	learn: 0.0020039	total: 12m 23s	remaining: 4m 48s
7409:	learn: 0.0014674	total: 12m 23s	remaining: 4m 20s
7413:	learn: 0.0015182	total: 12m 23s	remaining: 4m 19s
6857:	learn: 0.0013858	total: 12m 24s	remaining: 5m 40s
7204:	learn: 0.0020032	total: 12m 24s	remaining: 4m 48s
7544:	learn: 0.0014612	total: 12m 23s	remaining: 4m 2s
7410:	learn: 0.0014669	total: 12m 24s	remaining: 4m 19s
6858:	learn: 0.0013858	total: 12m 24s	remaining: 5m 40s
7205:	learn: 0.0020028	total: 12m 24s	remaining: 4m 48s
7414:	learn: 0.0015182	total: 12m 23s	remaining: 4m 19s
7545:	learn: 0.0014612	total: 12m 24s	remaining: 4m 1s
7411:	learn: 0.0014669	total: 12m 24s	remaining: 4m 19s
6859:	learn: 0.0013858	total: 12m 24s	remaining: 5m 40s
7206:	learn: 0.0020022	total: 12m 24s	remaining: 4m 48s
7415:	learn: 0.0015182	total: 12m 24s	remaining: 4m 19s
7546:	learn: 0.0014612	total: 12m 24s	remaining: 4m 1s
7412:	learn: 0.0014669	total: 12m 24s	remaining: 4m 19s
6860:	learn: 0.0013858	total: 12m 24s	remaining: 5m 40s

7207:	learn: 0.0020017	total: 12m 24s	remaining: 4m 48s
7547:	learn: 0.0014612	total: 12m 24s	remaining: 4m 1s
7413:	learn: 0.0014669	total: 12m 24s	remaining: 4m 19s
7416:	learn: 0.0015182	total: 12m 24s	remaining: 4m 19s
6861:	learn: 0.0013858	total: 12m 24s	remaining: 5m 40s
7208:	learn: 0.0020012	total: 12m 24s	remaining: 4m 48s
7548:	learn: 0.0014612	total: 12m 24s	remaining: 4m 1s
7414:	learn: 0.0014669	total: 12m 24s	remaining: 4m 19s
7417:	learn: 0.0015182	total: 12m 24s	remaining: 4m 19s
6862:	learn: 0.0013856	total: 12m 24s	remaining: 5m 40s
7209:	learn: 0.0020005	total: 12m 24s	remaining: 4m 48s
7549:	learn: 0.0014612	total: 12m 24s	remaining: 4m 1s
7415:	learn: 0.0014669	total: 12m 24s	remaining: 4m 19s
7418:	learn: 0.0015182	total: 12m 24s	remaining: 4m 18s
6863:	learn: 0.0013856	total: 12m 24s	remaining: 5m 40s
7550:	learn: 0.0014612	total: 12m 24s	remaining: 4m 1s
7210:	learn: 0.0019999	total: 12m 24s	remaining: 4m 48s
7416:	learn: 0.0014664	total: 12m 24s	remaining: 4m 19s
7419:	learn: 0.0015182	total: 12m 24s	remaining: 4m 18s
6864:	learn: 0.0013856	total: 12m 24s	remaining: 5m 40s
7551:	learn: 0.0014612	total: 12m 24s	remaining: 4m 1s
7211:	learn: 0.0019989	total: 12m 24s	remaining: 4m 47s
7417:	learn: 0.0014664	total: 12m 24s	remaining: 4m 19s
7420:	learn: 0.0015182	total: 12m 24s	remaining: 4m 18s
7552:	learn: 0.0014612	total: 12m 24s	remaining: 4m 1s
6865:	learn: 0.0013856	total: 12m 24s	remaining: 5m 39s
7212:	learn: 0.0019984	total: 12m 24s	remaining: 4m 47s
7418:	learn: 0.0014664	total: 12m 24s	remaining: 4m 19s
7421:	learn: 0.0015182	total: 12m 24s	remaining: 4m 18s
6866:	learn: 0.0013856	total: 12m 24s	remaining: 5m 39s
7553:	learn: 0.0014612	total: 12m 24s	remaining: 4m 1s
7213:	learn: 0.0019980	total: 12m 24s	remaining: 4m 47s
7419:	learn: 0.0014664	total: 12m 24s	remaining: 4m 19s
7422:	learn: 0.0015182	total: 12m 24s	remaining: 4m 18s
7554:	learn: 0.0014612	total: 12m 24s	remaining: 4m 1s
7214:	learn: 0.0019974	total: 12m 25s	remaining: 4m 47s
6867:	learn: 0.0013856	total: 12m 25s	remaining: 5m 39s
7215:	learn: 0.0019967	total: 12m 25s	remaining: 4m 47s
7420:	learn: 0.0014664	total: 12m 25s	remaining: 4m 18s
7555:	learn: 0.0014612	total: 12m 25s	remaining: 4m
7423:	learn: 0.0015182	total: 12m 24s	remaining: 4m 18s
6868:	learn: 0.0013856	total: 12m 25s	remaining: 5m 39s
7421:	learn: 0.0014661	total: 12m 25s	remaining: 4m 18s
7216:	learn: 0.0019962	total: 12m 25s	remaining: 4m 47s
7556:	learn: 0.0014612	total: 12m 25s	remaining: 4m
7424:	learn: 0.0015182	total: 12m 25s	remaining: 4m 18s
6869:	learn: 0.0013856	total: 12m 25s	remaining: 5m 39s
7217:	learn: 0.0019958	total: 12m 25s	remaining: 4m 47s
7422:	learn: 0.0014661	total: 12m 25s	remaining: 4m 18s
7557:	learn: 0.0014612	total: 12m 25s	remaining: 4m
6870:	learn: 0.0013855	total: 12m 25s	remaining: 5m 39s
7425:	learn: 0.0015182	total: 12m 25s	remaining: 4m 18s
7558:	learn: 0.0014612	total: 12m 25s	remaining: 4m
7423:	learn: 0.0014657	total: 12m 25s	remaining: 4m 18s
7218:	learn: 0.0019953	total: 12m 25s	remaining: 4m 47s
6871:	learn: 0.0013851	total: 12m 25s	remaining: 5m 39s
7426:	learn: 0.0015182	total: 12m 25s	remaining: 4m 18s
7559:	learn: 0.0014612	total: 12m 25s	remaining: 4m
7219:	learn: 0.0019948	total: 12m 25s	remaining: 4m 47s
7424:	learn: 0.0014653	total: 12m 25s	remaining: 4m 18s
6872:	learn: 0.0013851	total: 12m 25s	remaining: 5m 39s
7560:	learn: 0.0014612	total: 12m 25s	remaining: 4m
7425:	learn: 0.0014652	total: 12m 25s	remaining: 4m 18s
7427:	learn: 0.0015179	total: 12m 25s	remaining: 4m 18s
7220:	learn: 0.0019948	total: 12m 25s	remaining: 4m 46s
6873:	learn: 0.0013850	total: 12m 25s	remaining: 5m 39s
7561:	learn: 0.0014612	total: 12m 25s	remaining: 4m
7426:	learn: 0.0014652	total: 12m 25s	remaining: 4m 18s
7428:	learn: 0.0015179	total: 12m 25s	remaining: 4m 17s
7562:	learn: 0.0014612	total: 12m 25s	remaining: 4m
7221:	learn: 0.0019943	total: 12m 25s	remaining: 4m 46s
6874:	learn: 0.0013848	total: 12m 25s	remaining: 5m 38s
7427:	learn: 0.0014649	total: 12m 25s	remaining: 4m 18s
7429:	learn: 0.0015179	total: 12m 25s	remaining: 4m 17s
7563:	learn: 0.0014612	total: 12m 25s	remaining: 4m
7428:	learn: 0.0014643	total: 12m 25s	remaining: 4m 18s
7222:	learn: 0.0019935	total: 12m 25s	remaining: 4m 46s
6875:	learn: 0.0013848	total: 12m 25s	remaining: 5m 38s
7430:	learn: 0.0015179	total: 12m 25s	remaining: 4m 17s
7429:	learn: 0.0014643	total: 12m 25s	remaining: 4m 18s
7223:	learn: 0.0019931	total: 12m 25s	remaining: 4m 46s
7564:	learn: 0.0014606	total: 12m 25s	remaining: 4m
7431:	learn: 0.0015179	total: 12m 25s	remaining: 4m 17s
6876:	learn: 0.0013848	total: 12m 25s	remaining: 5m 38s
7430:	learn: 0.0014643	total: 12m 26s	remaining: 4m 17s
7224:	learn: 0.0019924	total: 12m 26s	remaining: 4m 46s
7565:	learn: 0.0014606	total: 12m 25s	remaining: 3m 59s
7432:	learn: 0.0015179	total: 12m 25s	remaining: 4m 17s
6877:	learn: 0.0013848	total: 12m 26s	remaining: 5m 38s
7431:	learn: 0.0014643	total: 12m 26s	remaining: 4m 17s
7225:	learn: 0.0019917	total: 12m 26s	remaining: 4m 46s
7566:	learn: 0.0014606	total: 12m 26s	remaining: 3m 59s
7433:	learn: 0.0015178	total: 12m 25s	remaining: 4m 17s
6878:	learn: 0.0013848	total: 12m 26s	remaining: 5m 38s
7432:	learn: 0.0014643	total: 12m 26s	remaining: 4m 17s
7226:	learn: 0.0019913	total: 12m 26s	remaining: 4m 46s
7567:	learn: 0.0014600	total: 12m 26s	remaining: 3m 59s
7433:	learn: 0.0014639	total: 12m 26s	remaining: 4m 17s
7434:	learn: 0.0015178	total: 12m 26s	remaining: 4m 17s
6879:	learn: 0.0013848	total: 12m 26s	remaining: 5m 38s
7227:	learn: 0.0019903	total: 12m 26s	remaining: 4m 46s
7568:	learn: 0.0014596	total: 12m 26s	remaining: 3m 59s
7434:	learn: 0.0014635	total: 12m 26s	remaining: 4m 17s
6880:	learn: 0.0013848	total: 12m 26s	remaining: 5m 38s
7435:	learn: 0.0015178	total: 12m 26s	remaining: 4m 17s
7228:	learn: 0.0019898	total: 12m 26s	remaining: 4m 46s
7569:	learn: 0.0014591	total: 12m 26s	remaining: 3m 59s
7435:	learn: 0.0014631	total: 12m 26s	remaining: 4m 17s
7436:	learn: 0.0015178	total: 12m 26s	remaining: 4m 17s
7229:	learn: 0.0019892	total: 12m 26s	remaining: 4m 46s
6881:	learn: 0.0013848	total: 12m 26s	remaining: 5m 38s
7570:	learn: 0.0014591	total: 12m 26s	remaining: 3m 59s
7437:	learn: 0.0015178	total: 12m 26s	remaining: 4m 17s
7436:	learn: 0.0014631	total: 12m 26s	remaining: 4m 17s
7571:	learn: 0.0014590	total: 12m 26s	remaining: 3m 59s
6882:	learn: 0.0013848	total: 12m 26s	remaining: 5m 38s
7230:	learn: 0.0019885	total: 12m 26s	remaining: 4m 45s
7438:	learn: 0.0015178	total: 12m 26s	remaining: 4m 16s
7437:	learn: 0.0014627	total: 12m 26s	remaining: 4m 17s
7572:	learn: 0.0014590	total: 12m 26s	remaining: 3m 59s
7231:	learn: 0.0019880	total: 12m 26s	remaining: 4m 45s
6883:	learn: 0.0013848	total: 12m 26s	remaining: 5m 38s
7439:	learn: 0.0015178	total: 12m 26s	remaining: 4m 16s
7438:	learn: 0.0014627	total: 12m 26s	remaining: 4m 17s
7232:	learn: 0.0019875	total: 12m 26s	remaining: 4m 45s
7573:	learn: 0.0014590	total: 12m 26s	remaining: 3m 59s
7440:	learn: 0.0015178	total: 12m 26s	remaining: 4m 16s
6884:	learn: 0.0013847	total: 12m 26s	remaining: 5m 37s
7439:	learn: 0.0014627	total: 12m 26s	remaining: 4m 16s
7233:	learn: 0.0019868	total: 12m 26s	remaining: 4m 45s
7574:	learn: 0.0014590	total: 12m 26s	remaining: 3m 59s
7441:	learn: 0.0015178	total: 12m 26s	remaining: 4m 16s
6885:	learn: 0.0013848	total: 12m 26s	remaining: 5m 37s
7440:	learn: 0.0014623	total: 12m 26s	remaining: 4m 16s
7442:	learn: 0.0015178	total: 12m 26s	remaining: 4m 16s
7234:	learn: 0.0019863	total: 12m 27s	remaining: 4m 45s
7575:	learn: 0.0014590	total: 12m 26s	remaining: 3m 59s
7443:	learn: 0.0015178	total: 12m 26s	remaining: 4m 16s
7441:	learn: 0.0014623	total: 12m 27s	remaining: 4m 16s
6886:	learn: 0.0013848	total: 12m 27s	remaining: 5m 37s
7235:	learn: 0.0019853	total: 12m 27s	remaining: 4m 45s
7444:	learn: 0.0015178	total: 12m 26s	remaining: 4m 16s
7576:	learn: 0.0014590	total: 12m 27s	remaining: 3m 58s
6887:	learn: 0.0013848	total: 12m 27s	remaining: 5m 37s
7236:	learn: 0.0019848	total: 12m 27s	remaining: 4m 45s
7445:	learn: 0.0015178	total: 12m 27s	remaining: 4m 16s
7442:	learn: 0.0014619	total: 12m 27s	remaining: 4m 16s
7577:	learn: 0.0014590	total: 12m 27s	remaining: 3m 58s
7237:	learn: 0.0019848	total: 12m 27s	remaining: 4m 45s
6888:	learn: 0.0013848	total: 12m 27s	remaining: 5m 37s
7446:	learn: 0.0015178	total: 12m 27s	remaining: 4m 16s
7443:	learn: 0.0014619	total: 12m 27s	remaining: 4m 16s
7578:	learn: 0.0014590	total: 12m 27s	remaining: 3m 58s
7238:	learn: 0.0019841	total: 12m 27s	remaining: 4m 45s
7447:	learn: 0.0015178	total: 12m 27s	remaining: 4m 16s
7579:	learn: 0.0014590	total: 12m 27s	remaining: 3m 58s
7444:	learn: 0.0014619	total: 12m 27s	remaining: 4m 16s
6889:	learn: 0.0013848	total: 12m 27s	remaining: 5m 37s
7448:	learn: 0.0015178	total: 12m 27s	remaining: 4m 15s
7239:	learn: 0.0019835	total: 12m 27s	remaining: 4m 44s
7445:	learn: 0.0014619	total: 12m 27s	remaining: 4m 16s
7580:	learn: 0.0014590	total: 12m 27s	remaining: 3m 58s
6890:	learn: 0.0013848	total: 12m 27s	remaining: 5m 37s
7240:	learn: 0.0019830	total: 12m 27s	remaining: 4m 44s
7449:	learn: 0.0015178	total: 12m 27s	remaining: 4m 15s
7446:	learn: 0.0014619	total: 12m 27s	remaining: 4m 16s
7581:	learn: 0.0014590	total: 12m 27s	remaining: 3m 58s
6891:	learn: 0.0013847	total: 12m 27s	remaining: 5m 37s
7241:	learn: 0.0019826	total: 12m 27s	remaining: 4m 44s
7450:	learn: 0.0015178	total: 12m 27s	remaining: 4m 15s
7582:	learn: 0.0014590	total: 12m 27s	remaining: 3m 58s
7447:	learn: 0.0014619	total: 12m 27s	remaining: 4m 16s
7242:	learn: 0.0019821	total: 12m 27s	remaining: 4m 44s
6892:	learn: 0.0013845	total: 12m 27s	remaining: 5m 37s
7583:	learn: 0.0014590	total: 12m 27s	remaining: 3m 58s
7451:	learn: 0.0015178	total: 12m 27s	remaining: 4m 15s
7448:	learn: 0.0014619	total: 12m 27s	remaining: 4m 16s
7452:	learn: 0.0015178	total: 12m 27s	remaining: 4m 15s
7584:	learn: 0.0014590	total: 12m 27s	remaining: 3m 58s
7243:	learn: 0.0019816	total: 12m 27s	remaining: 4m 44s
6893:	learn: 0.0013845	total: 12m 27s	remaining: 5m 36s
7449:	learn: 0.0014619	total: 12m 27s	remaining: 4m 16s
7453:	learn: 0.0015178	total: 12m 27s	remaining: 4m 15s
7585:	learn: 0.0014590	total: 12m 27s	remaining: 3m 58s
7244:	learn: 0.0019811	total: 12m 28s	remaining: 4m 44s
6894:	learn: 0.0013843	total: 12m 28s	remaining: 5m 36s
7450:	learn: 0.0014618	total: 12m 28s	remaining: 4m 15s
7454:	learn: 0.0015178	total: 12m 27s	remaining: 4m 15s
7586:	learn: 0.0014587	total: 12m 28s	remaining: 3m 57s
7245:	learn: 0.0019805	total: 12m 28s	remaining: 4m 44s
7451:	learn: 0.0014619	total: 12m 28s	remaining: 4m 15s
6895:	learn: 0.0013843	total: 12m 28s	remaining: 5m 36s
7455:	learn: 0.0015178	total: 12m 27s	remaining: 4m 15s
7587:	learn: 0.0014582	total: 12m 28s	remaining: 3m 57s
7246:	learn: 0.0019801	total: 12m 28s	remaining: 4m 44s
7452:	learn: 0.0014619	total: 12m 28s	remaining: 4m 15s
6896:	learn: 0.0013842	total: 12m 28s	remaining: 5m 36s
7456:	learn: 0.0015178	total: 12m 28s	remaining: 4m 15s
7588:	learn: 0.0014582	total: 12m 28s	remaining: 3m 57s
7247:	learn: 0.0019792	total: 12m 28s	remaining: 4m 44s
6897:	learn: 0.0013842	total: 12m 28s	remaining: 5m 36s
7589:	learn: 0.0014582	total: 12m 28s	remaining: 3m 57s
7453:	learn: 0.0014619	total: 12m 28s	remaining: 4m 15s
7457:	learn: 0.0015178	total: 12m 28s	remaining: 4m 15s
7248:	learn: 0.0019786	total: 12m 28s	remaining: 4m 44s
6898:	learn: 0.0013840	total: 12m 28s	remaining: 5m 36s
7458:	learn: 0.0015178	total: 12m 28s	remaining: 4m 14s
7454:	learn: 0.0014619	total: 12m 28s	remaining: 4m 15s
7590:	learn: 0.0014582	total: 12m 28s	remaining: 3m 57s
7249:	learn: 0.0019779	total: 12m 28s	remaining: 4m 43s
6899:	learn: 0.0013839	total: 12m 28s	remaining: 5m 36s
7459:	learn: 0.0015178	total: 12m 28s	remaining: 4m 14s
7455:	learn: 0.0014619	total: 12m 28s	remaining: 4m 15s
7591:	learn: 0.0014582	total: 12m 28s	remaining: 3m 57s
7250:	learn: 0.0019773	total: 12m 28s	remaining: 4m 43s
7460:	learn: 0.0015178	total: 12m 28s	remaining: 4m 14s
7456:	learn: 0.0014615	total: 12m 28s	remaining: 4m 15s
7592:	learn: 0.0014582	total: 12m 28s	remaining: 3m 57s
6900:	learn: 0.0013839	total: 12m 28s	remaining: 5m 36s
7251:	learn: 0.0019766	total: 12m 28s	remaining: 4m 43s
7461:	learn: 0.0015178	total: 12m 28s	remaining: 4m 14s
7457:	learn: 0.0014610	total: 12m 28s	remaining: 4m 15s
7593:	learn: 0.0014582	total: 12m 28s	remaining: 3m 57s
6901:	learn: 0.0013839	total: 12m 28s	remaining: 5m 36s
7462:	learn: 0.0015178	total: 12m 28s	remaining: 4m 14s
7252:	learn: 0.0019762	total: 12m 28s	remaining: 4m 43s
7458:	learn: 0.0014610	total: 12m 28s	remaining: 4m 15s
6902:	learn: 0.0013838	total: 12m 28s	remaining: 5m 35s
7594:	learn: 0.0014582	total: 12m 28s	remaining: 3m 57s
7463:	learn: 0.0015178	total: 12m 28s	remaining: 4m 14s
7253:	learn: 0.0019753	total: 12m 28s	remaining: 4m 43s
6903:	learn: 0.0013838	total: 12m 28s	remaining: 5m 35s
7459:	learn: 0.0014610	total: 12m 28s	remaining: 4m 15s
7595:	learn: 0.0014582	total: 12m 28s	remaining: 3m 57s
7464:	learn: 0.0015178	total: 12m 28s	remaining: 4m 14s
7254:	learn: 0.0019745	total: 12m 29s	remaining: 4m 43s
7460:	learn: 0.0014604	total: 12m 29s	remaining: 4m 14s
7596:	learn: 0.0014582	total: 12m 28s	remaining: 3m 56s
6904:	learn: 0.0013835	total: 12m 29s	remaining: 5m 35s
7255:	learn: 0.0019739	total: 12m 29s	remaining: 4m 43s
7465:	learn: 0.0015178	total: 12m 28s	remaining: 4m 14s
7461:	learn: 0.0014599	total: 12m 29s	remaining: 4m 14s
7597:	learn: 0.0014582	total: 12m 29s	remaining: 3m 56s
7256:	learn: 0.0019735	total: 12m 29s	remaining: 4m 43s
6905:	learn: 0.0013835	total: 12m 29s	remaining: 5m 35s
7598:	learn: 0.0014582	total: 12m 29s	remaining: 3m 56s
7466:	learn: 0.0015178	total: 12m 29s	remaining: 4m 14s
7462:	learn: 0.0014595	total: 12m 29s	remaining: 4m 14s
7257:	learn: 0.0019731	total: 12m 29s	remaining: 4m 43s
6906:	learn: 0.0013835	total: 12m 29s	remaining: 5m 35s
7599:	learn: 0.0014582	total: 12m 29s	remaining: 3m 56s
7463:	learn: 0.0014590	total: 12m 29s	remaining: 4m 14s
7467:	learn: 0.0015178	total: 12m 29s	remaining: 4m 14s
7258:	learn: 0.0019724	total: 12m 29s	remaining: 4m 42s
6907:	learn: 0.0013835	total: 12m 29s	remaining: 5m 35s
7600:	learn: 0.0014582	total: 12m 29s	remaining: 3m 56s
7464:	learn: 0.0014585	total: 12m 29s	remaining: 4m 14s
7468:	learn: 0.0015174	total: 12m 29s	remaining: 4m 13s
7601:	learn: 0.0014582	total: 12m 29s	remaining: 3m 56s
7259:	learn: 0.0019717	total: 12m 29s	remaining: 4m 42s
6908:	learn: 0.0013832	total: 12m 29s	remaining: 5m 35s
7602:	learn: 0.0014582	total: 12m 29s	remaining: 3m 56s
7469:	learn: 0.0015174	total: 12m 29s	remaining: 4m 13s
7465:	learn: 0.0014580	total: 12m 29s	remaining: 4m 14s
7260:	learn: 0.0019709	total: 12m 29s	remaining: 4m 42s
6909:	learn: 0.0013832	total: 12m 29s	remaining: 5m 35s
7470:	learn: 0.0015169	total: 12m 29s	remaining: 4m 13s
7603:	learn: 0.0014582	total: 12m 29s	remaining: 3m 56s
7466:	learn: 0.0014575	total: 12m 29s	remaining: 4m 14s
7261:	learn: 0.0019705	total: 12m 29s	remaining: 4m 42s
6910:	learn: 0.0013832	total: 12m 29s	remaining: 5m 35s
7471:	learn: 0.0015169	total: 12m 29s	remaining: 4m 13s
7467:	learn: 0.0014572	total: 12m 29s	remaining: 4m 14s
7604:	learn: 0.0014582	total: 12m 29s	remaining: 3m 56s
7262:	learn: 0.0019695	total: 12m 29s	remaining: 4m 42s
7472:	learn: 0.0015165	total: 12m 29s	remaining: 4m 13s
7468:	learn: 0.0014572	total: 12m 29s	remaining: 4m 14s
6911:	learn: 0.0013828	total: 12m 29s	remaining: 5m 35s
7605:	learn: 0.0014582	total: 12m 29s	remaining: 3m 56s
7263:	learn: 0.0019689	total: 12m 29s	remaining: 4m 42s
7473:	learn: 0.0015165	total: 12m 29s	remaining: 4m 13s
7606:	learn: 0.0014582	total: 12m 29s	remaining: 3m 55s
7469:	learn: 0.0014572	total: 12m 29s	remaining: 4m 14s
6912:	learn: 0.0013828	total: 12m 30s	remaining: 5m 34s
7264:	learn: 0.0019682	total: 12m 30s	remaining: 4m 42s
7607:	learn: 0.0014582	total: 12m 29s	remaining: 3m 55s
7474:	learn: 0.0015165	total: 12m 29s	remaining: 4m 13s
7470:	learn: 0.0014572	total: 12m 30s	remaining: 4m 13s
6913:	learn: 0.0013828	total: 12m 30s	remaining: 5m 34s
7608:	learn: 0.0014582	total: 12m 30s	remaining: 3m 55s
7265:	learn: 0.0019676	total: 12m 30s	remaining: 4m 42s
7475:	learn: 0.0015162	total: 12m 29s	remaining: 4m 13s
7471:	learn: 0.0014572	total: 12m 30s	remaining: 4m 13s

7609:	learn: 0.0014582	total: 12m 30s	remaining: 3m 55s
6914:	learn: 0.0013828	total: 12m 30s	remaining: 5m 34s
7266:	learn: 0.0019666	total: 12m 30s	remaining: 4m 42s
7476:	learn: 0.0015162	total: 12m 30s	remaining: 4m 13s
7472:	learn: 0.0014567	total: 12m 30s	remaining: 4m 13s
7610:	learn: 0.0014582	total: 12m 30s	remaining: 3m 55s
7477:	learn: 0.0015162	total: 12m 30s	remaining: 4m 12s
6915:	learn: 0.0013828	total: 12m 30s	remaining: 5m 34s
7267:	learn: 0.0019660	total: 12m 30s	remaining: 4m 42s
7473:	learn: 0.0014567	total: 12m 30s	remaining: 4m 13s
7611:	learn: 0.0014582	total: 12m 30s	remaining: 3m 55s
7478:	learn: 0.0015162	total: 12m 30s	remaining: 4m 12s
7474:	learn: 0.0014567	total: 12m 30s	remaining: 4m 13s
6916:	learn: 0.0013824	total: 12m 30s	remaining: 5m 34s
7268:	learn: 0.0019653	total: 12m 30s	remaining: 4m 41s
7612:	learn: 0.0014582	total: 12m 30s	remaining: 3m 55s
7269:	learn: 0.0019644	total: 12m 30s	remaining: 4m 41s
7475:	learn: 0.0014563	total: 12m 30s	remaining: 4m 13s
7479:	learn: 0.0015163	total: 12m 30s	remaining: 4m 12s
6917:	learn: 0.0013820	total: 12m 30s	remaining: 5m 34s
7613:	learn: 0.0014579	total: 12m 30s	remaining: 3m 55s
7476:	learn: 0.0014561	total: 12m 30s	remaining: 4m 13s
7480:	learn: 0.0015162	total: 12m 30s	remaining: 4m 12s
6918:	learn: 0.0013820	total: 12m 30s	remaining: 5m 34s
7270:	learn: 0.0019639	total: 12m 30s	remaining: 4m 41s
7477:	learn: 0.0014556	total: 12m 30s	remaining: 4m 13s
7481:	learn: 0.0015162	total: 12m 30s	remaining: 4m 12s
7614:	learn: 0.0014574	total: 12m 30s	remaining: 3m 55s
6919:	learn: 0.0013820	total: 12m 30s	remaining: 5m 34s
7478:	learn: 0.0014556	total: 12m 30s	remaining: 4m 13s
7482:	learn: 0.0015162	total: 12m 30s	remaining: 4m 12s
7271:	learn: 0.0019634	total: 12m 30s	remaining: 4m 41s
7615:	learn: 0.0014574	total: 12m 30s	remaining: 3m 55s
6920:	learn: 0.0013820	total: 12m 30s	remaining: 5m 34s
7483:	learn: 0.0015162	total: 12m 30s	remaining: 4m 12s
7479:	learn: 0.0014552	total: 12m 30s	remaining: 4m 12s
7272:	learn: 0.0019627	total: 12m 30s	remaining: 4m 41s
7616:	learn: 0.0014574	total: 12m 30s	remaining: 3m 54s
7484:	learn: 0.0015162	total: 12m 30s	remaining: 4m 12s
7480:	learn: 0.0014552	total: 12m 30s	remaining: 4m 12s
6921:	learn: 0.0013820	total: 12m 30s	remaining: 5m 33s
7617:	learn: 0.0014574	total: 12m 30s	remaining: 3m 54s
7273:	learn: 0.0019621	total: 12m 31s	remaining: 4m 41s
7485:	learn: 0.0015162	total: 12m 30s	remaining: 4m 12s
7481:	learn: 0.0014549	total: 12m 31s	remaining: 4m 12s
6922:	learn: 0.0013820	total: 12m 31s	remaining: 5m 33s
7274:	learn: 0.0019614	total: 12m 31s	remaining: 4m 41s
7618:	learn: 0.0014570	total: 12m 31s	remaining: 3m 54s
7482:	learn: 0.0014549	total: 12m 31s	remaining: 4m 12s
7486:	learn: 0.0015162	total: 12m 30s	remaining: 4m 12s
7275:	learn: 0.0019605	total: 12m 31s	remaining: 4m 41s
6923:	learn: 0.0013820	total: 12m 31s	remaining: 5m 33s
7619:	learn: 0.0014565	total: 12m 31s	remaining: 3m 54s
7487:	learn: 0.0015162	total: 12m 31s	remaining: 4m 11s
7483:	learn: 0.0014549	total: 12m 31s	remaining: 4m 12s
7276:	learn: 0.0019599	total: 12m 31s	remaining: 4m 41s
6924:	learn: 0.0013820	total: 12m 31s	remaining: 5m 33s
7484:	learn: 0.0014546	total: 12m 31s	remaining: 4m 12s
7488:	learn: 0.0015162	total: 12m 31s	remaining: 4m 11s
7620:	learn: 0.0014565	total: 12m 31s	remaining: 3m 54s
6925:	learn: 0.0013817	total: 12m 31s	remaining: 5m 33s
7277:	learn: 0.0019594	total: 12m 31s	remaining: 4m 41s
7485:	learn: 0.0014546	total: 12m 31s	remaining: 4m 12s
7489:	learn: 0.0015162	total: 12m 31s	remaining: 4m 11s
7621:	learn: 0.0014565	total: 12m 31s	remaining: 3m 54s
7486:	learn: 0.0014541	total: 12m 31s	remaining: 4m 12s
7278:	learn: 0.0019589	total: 12m 31s	remaining: 4m 40s
6926:	learn: 0.0013817	total: 12m 31s	remaining: 5m 33s
7490:	learn: 0.0015162	total: 12m 31s	remaining: 4m 11s
7487:	learn: 0.0014537	total: 12m 31s	remaining: 4m 12s
7622:	learn: 0.0014565	total: 12m 31s	remaining: 3m 54s
7488:	learn: 0.0014537	total: 12m 31s	remaining: 4m 12s
6927:	learn: 0.0013817	total: 12m 31s	remaining: 5m 33s
7279:	learn: 0.0019585	total: 12m 31s	remaining: 4m 40s
7491:	learn: 0.0015162	total: 12m 31s	remaining: 4m 11s
7623:	learn: 0.0014562	total: 12m 31s	remaining: 3m 54s
7489:	learn: 0.0014533	total: 12m 31s	remaining: 4m 11s
7492:	learn: 0.0015162	total: 12m 31s	remaining: 4m 11s
6928:	learn: 0.0013815	total: 12m 31s	remaining: 5m 33s
7280:	learn: 0.0019580	total: 12m 31s	remaining: 4m 40s
7624:	learn: 0.0014562	total: 12m 31s	remaining: 3m 54s
7490:	learn: 0.0014528	total: 12m 31s	remaining: 4m 11s
7281:	learn: 0.0019573	total: 12m 31s	remaining: 4m 40s
6929:	learn: 0.0013815	total: 12m 31s	remaining: 5m 33s
7493:	learn: 0.0015162	total: 12m 31s	remaining: 4m 11s
7625:	learn: 0.0014562	total: 12m 31s	remaining: 3m 54s
7491:	learn: 0.0014528	total: 12m 31s	remaining: 4m 11s
7282:	learn: 0.0019566	total: 12m 31s	remaining: 4m 40s
7494:	learn: 0.0015162	total: 12m 31s	remaining: 4m 11s
7492:	learn: 0.0014524	total: 12m 32s	remaining: 4m 11s
7626:	learn: 0.0014562	total: 12m 31s	remaining: 3m 53s
6930:	learn: 0.0013815	total: 12m 32s	remaining: 5m 32s
7283:	learn: 0.0019558	total: 12m 32s	remaining: 4m 40s
7493:	learn: 0.0014524	total: 12m 32s	remaining: 4m 11s
7495:	learn: 0.0015162	total: 12m 31s	remaining: 4m 11s
7627:	learn: 0.0014562	total: 12m 32s	remaining: 3m 53s
7284:	learn: 0.0019551	total: 12m 32s	remaining: 4m 40s
6931:	learn: 0.0013815	total: 12m 32s	remaining: 5m 32s
7494:	learn: 0.0014520	total: 12m 32s	remaining: 4m 11s
7628:	learn: 0.0014562	total: 12m 32s	remaining: 3m 53s
7496:	learn: 0.0015162	total: 12m 31s	remaining: 4m 11s
7285:	learn: 0.0019546	total: 12m 32s	remaining: 4m 40s
6932:	learn: 0.0013811	total: 12m 32s	remaining: 5m 32s
7495:	learn: 0.0014520	total: 12m 32s	remaining: 4m 11s
7629:	learn: 0.0014562	total: 12m 32s	remaining: 3m 53s
7286:	learn: 0.0019538	total: 12m 32s	remaining: 4m 40s
7497:	learn: 0.0015162	total: 12m 32s	remaining: 4m 10s
6933:	learn: 0.0013811	total: 12m 32s	remaining: 5m 32s
7496:	learn: 0.0014519	total: 12m 32s	remaining: 4m 11s
7287:	learn: 0.0019529	total: 12m 32s	remaining: 4m 39s
7498:	learn: 0.0015162	total: 12m 32s	remaining: 4m 10s
7630:	learn: 0.0014561	total: 12m 32s	remaining: 3m 53s
6934:	learn: 0.0013811	total: 12m 32s	remaining: 5m 32s
7497:	learn: 0.0014515	total: 12m 32s	remaining: 4m 11s
7499:	learn: 0.0015162	total: 12m 32s	remaining: 4m 10s
7288:	learn: 0.0019525	total: 12m 32s	remaining: 4m 39s
7631:	learn: 0.0014561	total: 12m 32s	remaining: 3m 53s
7500:	learn: 0.0015162	total: 12m 32s	remaining: 4m 10s
6935:	learn: 0.0013811	total: 12m 32s	remaining: 5m 32s
7289:	learn: 0.0019520	total: 12m 32s	remaining: 4m 39s
7498:	learn: 0.0014510	total: 12m 32s	remaining: 4m 11s
7632:	learn: 0.0014561	total: 12m 32s	remaining: 3m 53s
7501:	learn: 0.0015162	total: 12m 32s	remaining: 4m 10s
7290:	learn: 0.0019514	total: 12m 32s	remaining: 4m 39s
7499:	learn: 0.0014507	total: 12m 32s	remaining: 4m 10s
7633:	learn: 0.0014561	total: 12m 32s	remaining: 3m 53s
6936:	learn: 0.0013807	total: 12m 32s	remaining: 5m 32s
7291:	learn: 0.0019507	total: 12m 32s	remaining: 4m 39s
7502:	learn: 0.0015162	total: 12m 32s	remaining: 4m 10s
7500:	learn: 0.0014503	total: 12m 32s	remaining: 4m 10s
7634:	learn: 0.0014561	total: 12m 32s	remaining: 3m 53s
7503:	learn: 0.0015162	total: 12m 32s	remaining: 4m 10s
6937:	learn: 0.0013807	total: 12m 32s	remaining: 5m 32s
7292:	learn: 0.0019503	total: 12m 32s	remaining: 4m 39s
7501:	learn: 0.0014503	total: 12m 32s	remaining: 4m 10s
7635:	learn: 0.0014561	total: 12m 32s	remaining: 3m 53s
7504:	learn: 0.0015162	total: 12m 32s	remaining: 4m 10s
6938:	learn: 0.0013804	total: 12m 32s	remaining: 5m 32s
7502:	learn: 0.0014500	total: 12m 32s	remaining: 4m 10s
7293:	learn: 0.0019498	total: 12m 33s	remaining: 4m 39s
7636:	learn: 0.0014561	total: 12m 32s	remaining: 3m 52s
7503:	learn: 0.0014500	total: 12m 33s	remaining: 4m 10s
7505:	learn: 0.0015162	total: 12m 32s	remaining: 4m 10s
6939:	learn: 0.0013804	total: 12m 33s	remaining: 5m 32s
7637:	learn: 0.0014561	total: 12m 32s	remaining: 3m 52s
7294:	learn: 0.0019490	total: 12m 33s	remaining: 4m 39s
7638:	learn: 0.0014561	total: 12m 33s	remaining: 3m 52s
7504:	learn: 0.0014496	total: 12m 33s	remaining: 4m 10s
7506:	learn: 0.0015162	total: 12m 32s	remaining: 4m 10s
6940:	learn: 0.0013804	total: 12m 33s	remaining: 5m 31s
7295:	learn: 0.0019481	total: 12m 33s	remaining: 4m 39s
7505:	learn: 0.0014496	total: 12m 33s	remaining: 4m 10s
7507:	learn: 0.0015162	total: 12m 33s	remaining: 4m 9s
7639:	learn: 0.0014561	total: 12m 33s	remaining: 3m 52s
7296:	learn: 0.0019473	total: 12m 33s	remaining: 4m 39s
6941:	learn: 0.0013804	total: 12m 33s	remaining: 5m 31s
7506:	learn: 0.0014492	total: 12m 33s	remaining: 4m 10s
7508:	learn: 0.0015162	total: 12m 33s	remaining: 4m 9s
7640:	learn: 0.0014559	total: 12m 33s	remaining: 3m 52s
7297:	learn: 0.0019467	total: 12m 33s	remaining: 4m 38s
6942:	learn: 0.0013804	total: 12m 33s	remaining: 5m 31s
7507:	learn: 0.0014492	total: 12m 33s	remaining: 4m 10s
7641:	learn: 0.0014559	total: 12m 33s	remaining: 3m 52s
7509:	learn: 0.0015162	total: 12m 33s	remaining: 4m 9s
6943:	learn: 0.0013804	total: 12m 33s	remaining: 5m 31s
7298:	learn: 0.0019462	total: 12m 33s	remaining: 4m 38s
7508:	learn: 0.0014488	total: 12m 33s	remaining: 4m 9s
7642:	learn: 0.0014559	total: 12m 33s	remaining: 3m 52s
7510:	learn: 0.0015162	total: 12m 33s	remaining: 4m 9s
7509:	learn: 0.0014488	total: 12m 33s	remaining: 4m 9s
7511:	learn: 0.0015162	total: 12m 33s	remaining: 4m 9s
6944:	learn: 0.0013803	total: 12m 33s	remaining: 5m 31s
7299:	learn: 0.0019457	total: 12m 33s	remaining: 4m 38s
7643:	learn: 0.0014558	total: 12m 33s	remaining: 3m 52s
7510:	learn: 0.0014488	total: 12m 33s	remaining: 4m 9s
6945:	learn: 0.0013803	total: 12m 33s	remaining: 5m 31s
7644:	learn: 0.0014558	total: 12m 33s	remaining: 3m 52s
7300:	learn: 0.0019448	total: 12m 33s	remaining: 4m 38s
7512:	learn: 0.0015162	total: 12m 33s	remaining: 4m 9s
7511:	learn: 0.0014488	total: 12m 33s	remaining: 4m 9s
7301:	learn: 0.0019442	total: 12m 33s	remaining: 4m 38s
7645:	learn: 0.0014555	total: 12m 33s	remaining: 3m 52s
6946:	learn: 0.0013803	total: 12m 33s	remaining: 5m 31s
7513:	learn: 0.0015162	total: 12m 33s	remaining: 4m 9s
7512:	learn: 0.0014488	total: 12m 33s	remaining: 4m 9s
7302:	learn: 0.0019438	total: 12m 33s	remaining: 4m 38s
7646:	learn: 0.0014555	total: 12m 33s	remaining: 3m 51s
6947:	learn: 0.0013799	total: 12m 33s	remaining: 5m 31s
7513:	learn: 0.0014488	total: 12m 33s	remaining: 4m 9s
7514:	learn: 0.0015162	total: 12m 33s	remaining: 4m 9s
7303:	learn: 0.0019429	total: 12m 34s	remaining: 4m 38s
7514:	learn: 0.0014488	total: 12m 34s	remaining: 4m 9s
7647:	learn: 0.0014555	total: 12m 33s	remaining: 3m 51s
6948:	learn: 0.0013799	total: 12m 34s	remaining: 5m 31s
7515:	learn: 0.0015162	total: 12m 33s	remaining: 4m 9s
7304:	learn: 0.0019420	total: 12m 34s	remaining: 4m 38s
7515:	learn: 0.0014488	total: 12m 34s	remaining: 4m 9s
6949:	learn: 0.0013799	total: 12m 34s	remaining: 5m 30s
7648:	learn: 0.0014555	total: 12m 34s	remaining: 3m 51s
7516:	learn: 0.0015162	total: 12m 33s	remaining: 4m 9s
7305:	learn: 0.0019415	total: 12m 34s	remaining: 4m 38s
7516:	learn: 0.0014483	total: 12m 34s	remaining: 4m 9s
6950:	learn: 0.0013799	total: 12m 34s	remaining: 5m 30s
7517:	learn: 0.0015162	total: 12m 34s	remaining: 4m 8s
7649:	learn: 0.0014555	total: 12m 34s	remaining: 3m 51s
7306:	learn: 0.0019411	total: 12m 34s	remaining: 4m 38s
7517:	learn: 0.0014478	total: 12m 34s	remaining: 4m 9s
7650:	learn: 0.0014555	total: 12m 34s	remaining: 3m 51s
6951:	learn: 0.0013799	total: 12m 34s	remaining: 5m 30s
7518:	learn: 0.0015162	total: 12m 34s	remaining: 4m 8s
7518:	learn: 0.0014478	total: 12m 34s	remaining: 4m 8s
7651:	learn: 0.0014555	total: 12m 34s	remaining: 3m 51s
7307:	learn: 0.0019406	total: 12m 34s	remaining: 4m 37s
6952:	learn: 0.0013799	total: 12m 34s	remaining: 5m 30s
7519:	learn: 0.0015162	total: 12m 34s	remaining: 4m 8s
7519:	learn: 0.0014478	total: 12m 34s	remaining: 4m 8s
6953:	learn: 0.0013799	total: 12m 34s	remaining: 5m 30s
7520:	learn: 0.0015162	total: 12m 34s	remaining: 4m 8s
7308:	learn: 0.0019399	total: 12m 34s	remaining: 4m 37s
7652:	learn: 0.0014552	total: 12m 34s	remaining: 3m 51s
7520:	learn: 0.0014478	total: 12m 34s	remaining: 4m 8s
7309:	learn: 0.0019390	total: 12m 34s	remaining: 4m 37s
7521:	learn: 0.0015162	total: 12m 34s	remaining: 4m 8s
6954:	learn: 0.0013799	total: 12m 34s	remaining: 5m 30s
7653:	learn: 0.0014548	total: 12m 34s	remaining: 3m 51s
7310:	learn: 0.0019386	total: 12m 34s	remaining: 4m 37s
7521:	learn: 0.0014478	total: 12m 34s	remaining: 4m 8s
7522:	learn: 0.0015162	total: 12m 34s	remaining: 4m 8s
7654:	learn: 0.0014548	total: 12m 34s	remaining: 3m 51s
6955:	learn: 0.0013796	total: 12m 34s	remaining: 5m 30s
7311:	learn: 0.0019381	total: 12m 34s	remaining: 4m 37s
7522:	learn: 0.0014478	total: 12m 34s	remaining: 4m 8s
7523:	learn: 0.0015162	total: 12m 34s	remaining: 4m 8s
7655:	learn: 0.0014548	total: 12m 34s	remaining: 3m 51s
6956:	learn: 0.0013793	total: 12m 34s	remaining: 5m 30s
7523:	learn: 0.0014478	total: 12m 34s	remaining: 4m 8s
7524:	learn: 0.0015162	total: 12m 34s	remaining: 4m 8s
7312:	learn: 0.0019373	total: 12m 34s	remaining: 4m 37s
7656:	learn: 0.0014548	total: 12m 34s	remaining: 3m 50s
7524:	learn: 0.0014478	total: 12m 35s	remaining: 4m 8s
7525:	learn: 0.0015162	total: 12m 34s	remaining: 4m 8s
6957:	learn: 0.0013793	total: 12m 35s	remaining: 5m 30s
7313:	learn: 0.0019366	total: 12m 35s	remaining: 4m 37s
7657:	learn: 0.0014548	total: 12m 34s	remaining: 3m 50s
7526:	learn: 0.0015160	total: 12m 34s	remaining: 4m 8s
7525:	learn: 0.0014478	total: 12m 35s	remaining: 4m 8s
7314:	learn: 0.0019361	total: 12m 35s	remaining: 4m 37s
6958:	learn: 0.0013792	total: 12m 35s	remaining: 5m 30s
7526:	learn: 0.0014478	total: 12m 35s	remaining: 4m 8s
7658:	learn: 0.0014545	total: 12m 35s	remaining: 3m 50s
7527:	learn: 0.0015160	total: 12m 34s	remaining: 4m 7s
7315:	learn: 0.0019353	total: 12m 35s	remaining: 4m 37s
6959:	learn: 0.0013792	total: 12m 35s	remaining: 5m 29s
7659:	learn: 0.0014540	total: 12m 35s	remaining: 3m 50s
7527:	learn: 0.0014478	total: 12m 35s	remaining: 4m 8s
7528:	learn: 0.0015159	total: 12m 35s	remaining: 4m 7s
7316:	learn: 0.0019346	total: 12m 35s	remaining: 4m 36s
6960:	learn: 0.0013792	total: 12m 35s	remaining: 5m 29s
7660:	learn: 0.0014540	total: 12m 35s	remaining: 3m 50s
7528:	learn: 0.0014478	total: 12m 35s	remaining: 4m 7s
7529:	learn: 0.0015159	total: 12m 35s	remaining: 4m 7s
7317:	learn: 0.0019340	total: 12m 35s	remaining: 4m 36s
6961:	learn: 0.0013792	total: 12m 35s	remaining: 5m 29s
7661:	learn: 0.0014537	total: 12m 35s	remaining: 3m 50s
7529:	learn: 0.0014478	total: 12m 35s	remaining: 4m 7s
7530:	learn: 0.0015159	total: 12m 35s	remaining: 4m 7s
7318:	learn: 0.0019335	total: 12m 35s	remaining: 4m 36s
7662:	learn: 0.0014533	total: 12m 35s	remaining: 3m 50s
7530:	learn: 0.0014478	total: 12m 35s	remaining: 4m 7s
7531:	learn: 0.0015159	total: 12m 35s	remaining: 4m 7s
6962:	learn: 0.0013792	total: 12m 35s	remaining: 5m 29s
7319:	learn: 0.0019331	total: 12m 35s	remaining: 4m 36s
7663:	learn: 0.0014533	total: 12m 35s	remaining: 3m 50s
7531:	learn: 0.0014478	total: 12m 35s	remaining: 4m 7s
7532:	learn: 0.0015159	total: 12m 35s	remaining: 4m 7s
7320:	learn: 0.0019327	total: 12m 35s	remaining: 4m 36s
6963:	learn: 0.0013792	total: 12m 35s	remaining: 5m 29s
7664:	learn: 0.0014533	total: 12m 35s	remaining: 3m 50s
7532:	learn: 0.0014478	total: 12m 35s	remaining: 4m 7s
7533:	learn: 0.0015159	total: 12m 35s	remaining: 4m 7s
7321:	learn: 0.0019322	total: 12m 35s	remaining: 4m 36s
6964:	learn: 0.0013791	total: 12m 35s	remaining: 5m 29s
7533:	learn: 0.0014473	total: 12m 35s	remaining: 4m 7s
7665:	learn: 0.0014531	total: 12m 35s	remaining: 3m 50s
7534:	learn: 0.0015159	total: 12m 35s	remaining: 4m 7s
7322:	learn: 0.0019318	total: 12m 35s	remaining: 4m 36s
6965:	learn: 0.0013791	total: 12m 35s	remaining: 5m 29s
7534:	learn: 0.0014473	total: 12m 35s	remaining: 4m 7s
7666:	learn: 0.0014531	total: 12m 35s	remaining: 3m 50s
7535:	learn: 0.0015159	total: 12m 35s	remaining: 4m 7s
7323:	learn: 0.0019318	total: 12m 36s	remaining: 4m 36s
7535:	learn: 0.0014473	total: 12m 36s	remaining: 4m 7s
6966:	learn: 0.0013791	total: 12m 36s	remaining: 5m 29s

7536:	learn: 0.0015159	total: 12m 35s	remaining: 4m 7s
7324:	learn: 0.0019311	total: 12m 36s	remaining: 4m 36s
7536:	learn: 0.0014473	total: 12m 36s	remaining: 4m 7s
7668:	learn: 0.0014528	total: 12m 36s	remaining: 3m 49s
6967:	learn: 0.0013791	total: 12m 36s	remaining: 5m 29s
7537:	learn: 0.0015159	total: 12m 35s	remaining: 4m 6s
7325:	learn: 0.0019306	total: 12m 36s	remaining: 4m 36s
7537:	learn: 0.0014473	total: 12m 36s	remaining: 4m 6s
7669:	learn: 0.0014524	total: 12m 36s	remaining: 3m 49s
6968:	learn: 0.0013791	total: 12m 36s	remaining: 5m 28s
7538:	learn: 0.0015159	total: 12m 36s	remaining: 4m 6s
7326:	learn: 0.0019299	total: 12m 36s	remaining: 4m 35s
7538:	learn: 0.0014470	total: 12m 36s	remaining: 4m 6s
7670:	learn: 0.0014520	total: 12m 36s	remaining: 3m 49s
6969:	learn: 0.0013791	total: 12m 36s	remaining: 5m 28s
7539:	learn: 0.0015159	total: 12m 36s	remaining: 4m 6s
7327:	learn: 0.0019294	total: 12m 36s	remaining: 4m 35s
7539:	learn: 0.0014465	total: 12m 36s	remaining: 4m 6s
7671:	learn: 0.0014516	total: 12m 36s	remaining: 3m 49s
6970:	learn: 0.0013791	total: 12m 36s	remaining: 5m 28s
7540:	learn: 0.0015159	total: 12m 36s	remaining: 4m 6s
7540:	learn: 0.0014462	total: 12m 36s	remaining: 4m 6s
7328:	learn: 0.0019289	total: 12m 36s	remaining: 4m 35s
7672:	learn: 0.0014516	total: 12m 36s	remaining: 3m 49s
6971:	learn: 0.0013791	total: 12m 36s	remaining: 5m 28s
7541:	learn: 0.0015159	total: 12m 36s	remaining: 4m 6s
7541:	learn: 0.0014462	total: 12m 36s	remaining: 4m 6s
7329:	learn: 0.0019283	total: 12m 36s	remaining: 4m 35s
7673:	learn: 0.0014516	total: 12m 36s	remaining: 3m 49s
6972:	learn: 0.0013791	total: 12m 36s	remaining: 5m 28s
7542:	learn: 0.0014458	total: 12m 36s	remaining: 4m 6s
7542:	learn: 0.0015159	total: 12m 36s	remaining: 4m 6s
7330:	learn: 0.0019278	total: 12m 36s	remaining: 4m 35s
6973:	learn: 0.0013791	total: 12m 36s	remaining: 5m 28s
7674:	learn: 0.0014516	total: 12m 36s	remaining: 3m 49s
7543:	learn: 0.0014458	total: 12m 36s	remaining: 4m 6s
7543:	learn: 0.0015159	total: 12m 36s	remaining: 4m 6s
7331:	learn: 0.0019269	total: 12m 36s	remaining: 4m 35s
6974:	learn: 0.0013791	total: 12m 36s	remaining: 5m 28s
7675:	learn: 0.0014515	total: 12m 36s	remaining: 3m 49s
7544:	learn: 0.0014454	total: 12m 36s	remaining: 4m 6s
7544:	learn: 0.0015159	total: 12m 36s	remaining: 4m 6s
7332:	learn: 0.0019263	total: 12m 36s	remaining: 4m 35s
7545:	learn: 0.0014450	total: 12m 36s	remaining: 4m 6s
7676:	learn: 0.0014515	total: 12m 36s	remaining: 3m 49s
6975:	learn: 0.0013791	total: 12m 36s	remaining: 5m 28s
7545:	learn: 0.0015159	total: 12m 36s	remaining: 4m 6s
7677:	learn: 0.0014512	total: 12m 36s	remaining: 3m 48s
7333:	learn: 0.0019256	total: 12m 37s	remaining: 4m 35s
7546:	learn: 0.0014445	total: 12m 37s	remaining: 4m 6s
6976:	learn: 0.0013788	total: 12m 37s	remaining: 5m 28s
7334:	learn: 0.0019248	total: 12m 37s	remaining: 4m 35s
7546:	learn: 0.0015156	total: 12m 36s	remaining: 4m 6s
7678:	learn: 0.0014512	total: 12m 37s	remaining: 3m 48s
6977:	learn: 0.0013784	total: 12m 37s	remaining: 5m 27s
7547:	learn: 0.0014441	total: 12m 37s	remaining: 4m 5s
7335:	learn: 0.0019242	total: 12m 37s	remaining: 4m 34s
7679:	learn: 0.0014507	total: 12m 37s	remaining: 3m 48s
7547:	learn: 0.0015155	total: 12m 37s	remaining: 4m 5s
6978:	learn: 0.0013784	total: 12m 37s	remaining: 5m 27s
7336:	learn: 0.0019237	total: 12m 37s	remaining: 4m 34s
7548:	learn: 0.0015156	total: 12m 37s	remaining: 4m 5s
7548:	learn: 0.0014441	total: 12m 37s	remaining: 4m 5s
7680:	learn: 0.0014502	total: 12m 37s	remaining: 3m 48s
7337:	learn: 0.0019232	total: 12m 37s	remaining: 4m 34s
6979:	learn: 0.0013784	total: 12m 37s	remaining: 5m 27s
7549:	learn: 0.0014436	total: 12m 37s	remaining: 4m 5s
7549:	learn: 0.0015156	total: 12m 37s	remaining: 4m 5s
7681:	learn: 0.0014502	total: 12m 37s	remaining: 3m 48s
7338:	learn: 0.0019225	total: 12m 37s	remaining: 4m 34s
6980:	learn: 0.0013784	total: 12m 37s	remaining: 5m 27s
7550:	learn: 0.0014431	total: 12m 37s	remaining: 4m 5s
7550:	learn: 0.0015156	total: 12m 37s	remaining: 4m 5s
7682:	learn: 0.0014502	total: 12m 37s	remaining: 3m 48s
7339:	learn: 0.0019220	total: 12m 37s	remaining: 4m 34s
6981:	learn: 0.0013784	total: 12m 37s	remaining: 5m 27s
7551:	learn: 0.0014431	total: 12m 37s	remaining: 4m 5s
7551:	learn: 0.0015156	total: 12m 37s	remaining: 4m 5s
7340:	learn: 0.0019215	total: 12m 37s	remaining: 4m 34s
6982:	learn: 0.0013785	total: 12m 37s	remaining: 5m 27s
7683:	learn: 0.0014503	total: 12m 37s	remaining: 3m 48s
7552:	learn: 0.0015156	total: 12m 37s	remaining: 4m 5s
7552:	learn: 0.0014431	total: 12m 37s	remaining: 4m 5s
7684:	learn: 0.0014502	total: 12m 37s	remaining: 3m 48s
7553:	learn: 0.0015156	total: 12m 37s	remaining: 4m 5s
6983:	learn: 0.0013785	total: 12m 37s	remaining: 5m 27s
7341:	learn: 0.0019211	total: 12m 37s	remaining: 4m 34s
7553:	learn: 0.0014426	total: 12m 37s	remaining: 4m 5s
7685:	learn: 0.0014502	total: 12m 37s	remaining: 3m 48s
7554:	learn: 0.0015155	total: 12m 37s	remaining: 4m 5s
6984:	learn: 0.0013784	total: 12m 37s	remaining: 5m 27s
7554:	learn: 0.0014422	total: 12m 37s	remaining: 4m 5s
7555:	learn: 0.0015156	total: 12m 37s	remaining: 4m 5s
7342:	learn: 0.0019203	total: 12m 38s	remaining: 4m 34s
7686:	learn: 0.0014502	total: 12m 37s	remaining: 3m 48s
6985:	learn: 0.0013781	total: 12m 37s	remaining: 5m 27s
7556:	learn: 0.0015156	total: 12m 37s	remaining: 4m 4s
7555:	learn: 0.0014422	total: 12m 38s	remaining: 4m 5s
6986:	learn: 0.0013777	total: 12m 38s	remaining: 5m 26s
7687:	learn: 0.0014502	total: 12m 37s	remaining: 3m 47s
7343:	learn: 0.0019198	total: 12m 38s	remaining: 4m 34s
7557:	learn: 0.0015155	total: 12m 37s	remaining: 4m 4s
7556:	learn: 0.0014417	total: 12m 38s	remaining: 4m 5s
7558:	learn: 0.0015156	total: 12m 37s	remaining: 4m 4s
7688:	learn: 0.0014502	total: 12m 38s	remaining: 3m 47s
7344:	learn: 0.0019189	total: 12m 38s	remaining: 4m 34s
6987:	learn: 0.0013777	total: 12m 38s	remaining: 5m 26s
7557:	learn: 0.0014413	total: 12m 38s	remaining: 4m 4s
7559:	learn: 0.0015156	total: 12m 38s	remaining: 4m 4s
7689:	learn: 0.0014502	total: 12m 38s	remaining: 3m 47s
6988:	learn: 0.0013777	total: 12m 38s	remaining: 5m 26s
7558:	learn: 0.0014409	total: 12m 38s	remaining: 4m 4s
7560:	learn: 0.0015156	total: 12m 38s	remaining: 4m 4s
7345:	learn: 0.0019182	total: 12m 38s	remaining: 4m 34s
7690:	learn: 0.0014502	total: 12m 38s	remaining: 3m 47s
6989:	learn: 0.0013773	total: 12m 38s	remaining: 5m 26s
7561:	learn: 0.0015156	total: 12m 38s	remaining: 4m 4s
7559:	learn: 0.0014409	total: 12m 38s	remaining: 4m 4s
7346:	learn: 0.0019175	total: 12m 38s	remaining: 4m 33s
6990:	learn: 0.0013773	total: 12m 38s	remaining: 5m 26s
7562:	learn: 0.0015155	total: 12m 38s	remaining: 4m 4s
7691:	learn: 0.0014502	total: 12m 38s	remaining: 3m 47s
7560:	learn: 0.0014406	total: 12m 38s	remaining: 4m 4s
7347:	learn: 0.0019167	total: 12m 38s	remaining: 4m 33s
6991:	learn: 0.0013773	total: 12m 38s	remaining: 5m 26s
7563:	learn: 0.0015155	total: 12m 38s	remaining: 4m 4s
7692:	learn: 0.0014502	total: 12m 38s	remaining: 3m 47s
7561:	learn: 0.0014406	total: 12m 38s	remaining: 4m 4s
7348:	learn: 0.0019160	total: 12m 38s	remaining: 4m 33s
6992:	learn: 0.0013773	total: 12m 38s	remaining: 5m 26s
7564:	learn: 0.0015156	total: 12m 38s	remaining: 4m 4s
7693:	learn: 0.0014502	total: 12m 38s	remaining: 3m 47s
7562:	learn: 0.0014401	total: 12m 38s	remaining: 4m 4s
7349:	learn: 0.0019152	total: 12m 38s	remaining: 4m 33s
6993:	learn: 0.0013773	total: 12m 38s	remaining: 5m 26s
7694:	learn: 0.0014502	total: 12m 38s	remaining: 3m 47s
7565:	learn: 0.0015152	total: 12m 38s	remaining: 4m 4s
7350:	learn: 0.0019147	total: 12m 38s	remaining: 4m 33s
7563:	learn: 0.0014401	total: 12m 38s	remaining: 4m 4s
6994:	learn: 0.0013773	total: 12m 38s	remaining: 5m 26s
7695:	learn: 0.0014502	total: 12m 38s	remaining: 3m 47s
7566:	learn: 0.0015152	total: 12m 38s	remaining: 4m 3s
7564:	learn: 0.0014398	total: 12m 38s	remaining: 4m 4s
7351:	learn: 0.0019141	total: 12m 39s	remaining: 4m 33s
6995:	learn: 0.0013773	total: 12m 38s	remaining: 5m 25s
7567:	learn: 0.0015152	total: 12m 38s	remaining: 4m 3s
l: 12m 32s	remaining: 4m 39s
7499:	learn: 0.0014507	tota7696:	learn: 0.0014502	total: 12m 38s	remaining: 3m 47s
7565:	learn: 0.0014395	total: 12m 39s	remaining: 4m 4s
6996:	learn: 0.0013773	total: 12m 39s	remaining: 5m 25s
7352:	learn: 0.0019137	total: 12m 39s	remaining: 4m 33s
7568:	learn: 0.0015152	total: 12m 38s	remaining: 4m 3s
7697:	learn: 0.0014498	total: 12m 39s	remaining: 3m 46s
6997:	learn: 0.0013773	total: 12m 39s	remaining: 5m 25s
7353:	learn: 0.0019131	total: 12m 39s	remaining: 4m 33s
7566:	learn: 0.0014391	total: 12m 39s	remaining: 4m 4s
7569:	learn: 0.0015152	total: 12m 38s	remaining: 4m 3s
7698:	learn: 0.0014498	total: 12m 39s	remaining: 3m 46s
6998:	learn: 0.0013774	total: 12m 39s	remaining: 5m 25s
7570:	learn: 0.0015152	total: 12m 39s	remaining: 4m 3s
7699:	learn: 0.0014498	total: 12m 39s	remaining: 3m 46s
7567:	learn: 0.0014387	total: 12m 39s	remaining: 4m 4s
7354:	learn: 0.0019125	total: 12m 39s	remaining: 4m 33s
6999:	learn: 0.0013774	total: 12m 39s	remaining: 5m 25s
7571:	learn: 0.0015152	total: 12m 39s	remaining: 4m 3s
7700:	learn: 0.0014498	total: 12m 39s	remaining: 3m 46s
7568:	learn: 0.0014387	total: 12m 39s	remaining: 4m 3s
7355:	learn: 0.0019120	total: 12m 39s	remaining: 4m 32s
7000:	learn: 0.0013774	total: 12m 39s	remaining: 5m 25s
7572:	learn: 0.0015152	total: 12m 39s	remaining: 4m 3s
7569:	learn: 0.0014383	total: 12m 39s	remaining: 4m 3s
7701:	learn: 0.0014498	total: 12m 39s	remaining: 3m 46s
7001:	learn: 0.0013774	total: 12m 39s	remaining: 5m 25s
7356:	learn: 0.0019114	total: 12m 39s	remaining: 4m 32s
7702:	learn: 0.0014498	total: 12m 39s	remaining: 3m 46s
7573:	learn: 0.0015152	total: 12m 39s	remaining: 4m 3s
7570:	learn: 0.0014379	total: 12m 39s	remaining: 4m 3s
7357:	learn: 0.0019114	total: 12m 39s	remaining: 4m 32s
7002:	learn: 0.0013772	total: 12m 39s	remaining: 5m 25s
7703:	learn: 0.0014498	total: 12m 39s	remaining: 3m 46s
7574:	learn: 0.0015152	total: 12m 39s	remaining: 4m 3s
7571:	learn: 0.0014374	total: 12m 39s	remaining: 4m 3s
7358:	learn: 0.0019109	total: 12m 39s	remaining: 4m 32s
7003:	learn: 0.0013772	total: 12m 39s	remaining: 5m 24s
7575:	learn: 0.0015152	total: 12m 39s	remaining: 4m 3s
7704:	learn: 0.0014498	total: 12m 39s	remaining: 3m 46s
7572:	learn: 0.0014371	total: 12m 39s	remaining: 4m 3s
7359:	learn: 0.0019104	total: 12m 39s	remaining: 4m 32s
7004:	learn: 0.0013772	total: 12m 39s	remaining: 5m 24s
7705:	learn: 0.0014498	total: 12m 39s	remaining: 3m 46s
7576:	learn: 0.0015152	total: 12m 39s	remaining: 4m 2s
7573:	learn: 0.0014371	total: 12m 39s	remaining: 4m 3s
7360:	learn: 0.0019099	total: 12m 39s	remaining: 4m 32s
7005:	learn: 0.0013772	total: 12m 39s	remaining: 5m 24s
7574:	learn: 0.0014371	total: 12m 39s	remaining: 4m 3s
7577:	learn: 0.0015152	total: 12m 39s	remaining: 4m 2s
7706:	learn: 0.0014498	total: 12m 39s	remaining: 3m 46s
7361:	learn: 0.0019094	total: 12m 40s	remaining: 4m 32s
7006:	learn: 0.0013772	total: 12m 40s	remaining: 5m 24s
7575:	learn: 0.0014371	total: 12m 40s	remaining: 4m 3s
7707:	learn: 0.0014496	total: 12m 39s	remaining: 3m 45s
7578:	learn: 0.0015152	total: 12m 39s	remaining: 4m 2s
7362:	learn: 0.0019090	total: 12m 40s	remaining: 4m 32s
7007:	learn: 0.0013772	total: 12m 40s	remaining: 5m 24s
7576:	learn: 0.0014367	total: 12m 40s	remaining: 4m 3s
7708:	learn: 0.0014492	total: 12m 40s	remaining: 3m 45s
7579:	learn: 0.0015152	total: 12m 39s	remaining: 4m 2s
7363:	learn: 0.0019086	total: 12m 40s	remaining: 4m 32s
7008:	learn: 0.0013772	total: 12m 40s	remaining: 5m 24s
7709:	learn: 0.0014486	total: 12m 40s	remaining: 3m 45s
7577:	learn: 0.0014363	total: 12m 40s	remaining: 4m 3s
7580:	learn: 0.0015152	total: 12m 40s	remaining: 4m 2s
7710:	learn: 0.0014486	total: 12m 40s	remaining: 3m 45s
7364:	learn: 0.0019082	total: 12m 40s	remaining: 4m 32s
7581:	learn: 0.0015152	total: 12m 40s	remaining: 4m 2s
7578:	learn: 0.0014358	total: 12m 40s	remaining: 4m 2s
7009:	learn: 0.0013772	total: 12m 40s	remaining: 5m 24s
7711:	learn: 0.0014486	total: 12m 40s	remaining: 3m 45s
7365:	learn: 0.0019082	total: 12m 40s	remaining: 4m 31s
7010:	learn: 0.0013772	total: 12m 40s	remaining: 5m 24s
7582:	learn: 0.0015152	total: 12m 40s	remaining: 4m 2s
7712:	learn: 0.0014486	total: 12m 40s	remaining: 3m 45s
7579:	learn: 0.0014358	total: 12m 40s	remaining: 4m 2s
7011:	learn: 0.0013772	total: 12m 40s	remaining: 5m 24s
7366:	learn: 0.0019076	total: 12m 40s	remaining: 4m 31s
7583:	learn: 0.0015152	total: 12m 40s	remaining: 4m 2s
7713:	learn: 0.0014486	total: 12m 40s	remaining: 3m 45s
7367:	learn: 0.0019071	total: 12m 40s	remaining: 4m 31s
7580:	learn: 0.0014354	total: 12m 40s	remaining: 4m 2s
7012:	learn: 0.0013772	total: 12m 40s	remaining: 5m 23s
7714:	learn: 0.0014486	total: 12m 40s	remaining: 3m 45s
7584:	learn: 0.0015152	total: 12m 40s	remaining: 4m 2s
7368:	learn: 0.0019063	total: 12m 40s	remaining: 4m 31s
7581:	learn: 0.0014354	total: 12m 40s	remaining: 4m 2s
7585:	learn: 0.0015152	total: 12m 40s	remaining: 4m 2s
7715:	learn: 0.0014486	total: 12m 40s	remaining: 3m 45s
7013:	learn: 0.0013772	total: 12m 40s	remaining: 5m 23s
7369:	learn: 0.0019058	total: 12m 40s	remaining: 4m 31s
7586:	learn: 0.0015146	total: 12m 40s	remaining: 4m 1s
7716:	learn: 0.0014486	total: 12m 40s	remaining: 3m 45s
7582:	learn: 0.0014354	total: 12m 40s	remaining: 4m 2s
7014:	learn: 0.0013772	total: 12m 40s	remaining: 5m 23s
7370:	learn: 0.0019054	total: 12m 40s	remaining: 4m 31s
7587:	learn: 0.0015146	total: 12m 40s	remaining: 4m 1s
7717:	learn: 0.0014480	total: 12m 40s	remaining: 3m 44s
7583:	learn: 0.0014350	total: 12m 41s	remaining: 4m 2s
7371:	learn: 0.0019050	total: 12m 41s	remaining: 4m 31s
7015:	learn: 0.0013767	total: 12m 41s	remaining: 5m 23s
7588:	learn: 0.0015146	total: 12m 40s	remaining: 4m 1s
7372:	learn: 0.0019045	total: 12m 41s	remaining: 4m 31s
7718:	learn: 0.0014480	total: 12m 40s	remaining: 3m 44s
7584:	learn: 0.0014350	total: 12m 41s	remaining: 4m 2s
7016:	learn: 0.0013767	total: 12m 41s	remaining: 5m 23s
7589:	learn: 0.0015144	total: 12m 40s	remaining: 4m 1s
7719:	learn: 0.0014475	total: 12m 41s	remaining: 3m 44s
7373:	learn: 0.0019040	total: 12m 41s	remaining: 4m 31s
7585:	learn: 0.0014348	total: 12m 41s	remaining: 4m 2s
7017:	learn: 0.0013767	total: 12m 41s	remaining: 5m 23s
7590:	learn: 0.0015144	total: 12m 41s	remaining: 4m 1s
7374:	learn: 0.0019036	total: 12m 41s	remaining: 4m 30s
7018:	learn: 0.0013767	total: 12m 41s	remaining: 5m 23s
7720:	learn: 0.0014475	total: 12m 41s	remaining: 3m 44s
7591:	learn: 0.0015144	total: 12m 41s	remaining: 4m 1s
7586:	learn: 0.0014348	total: 12m 41s	remaining: 4m 2s
7375:	learn: 0.0019030	total: 12m 41s	remaining: 4m 30s
7721:	learn: 0.0014475	total: 12m 41s	remaining: 3m 44s
7587:	learn: 0.0014344	total: 12m 41s	remaining: 4m 2s
7019:	learn: 0.0013767	total: 12m 41s	remaining: 5m 23s
7592:	learn: 0.0015140	total: 12m 41s	remaining: 4m 1s
7722:	learn: 0.0014475	total: 12m 41s	remaining: 3m 44s
7376:	learn: 0.0019024	total: 12m 41s	remaining: 4m 30s
7020:	learn: 0.0013767	total: 12m 41s	remaining: 5m 23s
7588:	learn: 0.0014344	total: 12m 41s	remaining: 4m 1s
7593:	learn: 0.0015140	total: 12m 41s	remaining: 4m 1s
7377:	learn: 0.0019017	total: 12m 41s	remaining: 4m 30s
7723:	learn: 0.0014474	total: 12m 41s	remaining: 3m 44s
7021:	learn: 0.0013764	total: 12m 41s	remaining: 5m 22s
7589:	learn: 0.0014344	total: 12m 41s	remaining: 4m 1s
7594:	learn: 0.0015140	total: 12m 41s	remaining: 4m 1s
7378:	learn: 0.0019012	total: 12m 41s	remaining: 4m 30s
7590:	learn: 0.0014340	total: 12m 41s	remaining: 4m 1s
7022:	learn: 0.0013763	total: 12m 41s	remaining: 5m 22s
7724:	learn: 0.0014474	total: 12m 41s	remaining: 3m 44s
7595:	learn: 0.0015140	total: 12m 41s	remaining: 4m 1s
7379:	learn: 0.0019008	total: 12m 41s	remaining: 4m 30s
7023:	learn: 0.0013763	total: 12m 41s	remaining: 5m 22s
7725:	learn: 0.0014474	total: 12m 41s	remaining: 3m 44s
7591:	learn: 0.0014340	total: 12m 41s	remaining: 4m 1s
7596:	learn: 0.0015140	total: 12m 41s	remaining: 4m
7024:	learn: 0.0013763	total: 12m 41s	remaining: 5m 22s
7380:	learn: 0.0019003	total: 12m 41s	remaining: 4m 30s
7726:	learn: 0.0014474	total: 12m 41s	remaining: 3m 44s
7592:	learn: 0.0014335	total: 12m 41s	remaining: 4m 1s
7597:	learn: 0.0015138	total: 12m 41s	remaining: 4m

7025:	learn: 0.0013763	total: 12m 41s	remaining: 5m 22s
7727:	learn: 0.0014474	total: 12m 41s	remaining: 3m 43s
7593:	learn: 0.0014335	total: 12m 42s	remaining: 4m 1s
7598:	learn: 0.0015138	total: 12m 41s	remaining: 4m
7381:	learn: 0.0018998	total: 12m 42s	remaining: 4m 30s
7026:	learn: 0.0013763	total: 12m 42s	remaining: 5m 22s
7599:	learn: 0.0015138	total: 12m 41s	remaining: 4m
7594:	learn: 0.0014331	total: 12m 42s	remaining: 4m 1s
7382:	learn: 0.0018989	total: 12m 42s	remaining: 4m 30s
7728:	learn: 0.0014474	total: 12m 42s	remaining: 3m 43s
7600:	learn: 0.0015138	total: 12m 41s	remaining: 4m
7027:	learn: 0.0013763	total: 12m 42s	remaining: 5m 22s
7383:	learn: 0.0018985	total: 12m 42s	remaining: 4m 30s
7595:	learn: 0.0014328	total: 12m 42s	remaining: 4m 1s
7729:	learn: 0.0014470	total: 12m 42s	remaining: 3m 43s
7601:	learn: 0.0015138	total: 12m 42s	remaining: 4m
7028:	learn: 0.0013763	total: 12m 42s	remaining: 5m 22s
7384:	learn: 0.0018980	total: 12m 42s	remaining: 4m 29s
7596:	learn: 0.0014325	total: 12m 42s	remaining: 4m 1s
7730:	learn: 0.0014466	total: 12m 42s	remaining: 3m 43s
7602:	learn: 0.0015138	total: 12m 42s	remaining: 4m
7029:	learn: 0.0013763	total: 12m 42s	remaining: 5m 22s
7385:	learn: 0.0018976	total: 12m 42s	remaining: 4m 29s
7597:	learn: 0.0014325	total: 12m 42s	remaining: 4m 1s
7731:	learn: 0.0014466	total: 12m 42s	remaining: 3m 43s
7386:	learn: 0.0018972	total: 12m 42s	remaining: 4m 29s
7603:	learn: 0.0015138	total: 12m 42s	remaining: 4m
7030:	learn: 0.0013763	total: 12m 42s	remaining: 5m 21s
7598:	learn: 0.0014325	total: 12m 42s	remaining: 4m
7732:	learn: 0.0014466	total: 12m 42s	remaining: 3m 43s
7387:	learn: 0.0018968	total: 12m 42s	remaining: 4m 29s
7031:	learn: 0.0013763	total: 12m 42s	remaining: 5m 21s
7604:	learn: 0.0015138	total: 12m 42s	remaining: 4m
7599:	learn: 0.0014320	total: 12m 42s	remaining: 4m
7733:	learn: 0.0014466	total: 12m 42s	remaining: 3m 43s
7388:	learn: 0.0018961	total: 12m 42s	remaining: 4m 29s
7605:	learn: 0.0015136	total: 12m 42s	remaining: 3m 59s
7032:	learn: 0.0013763	total: 12m 42s	remaining: 5m 21s
7600:	learn: 0.0014316	total: 12m 42s	remaining: 4m
7606:	learn: 0.0015136	total: 12m 42s	remaining: 3m 59s
7734:	learn: 0.0014466	total: 12m 42s	remaining: 3m 43s
7389:	learn: 0.0018956	total: 12m 42s	remaining: 4m 29s
7033:	learn: 0.0013763	total: 12m 42s	remaining: 5m 21s
7601:	learn: 0.0014315	total: 12m 42s	remaining: 4m
7607:	learn: 0.0015136	total: 12m 42s	remaining: 3m 59s
7735:	learn: 0.0014466	total: 12m 42s	remaining: 3m 43s
7602:	learn: 0.0014311	total: 12m 42s	remaining: 4m
7390:	learn: 0.0018953	total: 12m 42s	remaining: 4m 29s
7608:	learn: 0.0015136	total: 12m 42s	remaining: 3m 59s
7034:	learn: 0.0013759	total: 12m 42s	remaining: 5m 21s
7603:	learn: 0.0014306	total: 12m 43s	remaining: 4m
7391:	learn: 0.0018948	total: 12m 43s	remaining: 4m 29s
7736:	learn: 0.0014466	total: 12m 42s	remaining: 3m 43s
7609:	learn: 0.0015136	total: 12m 42s	remaining: 3m 59s
7035:	learn: 0.0013759	total: 12m 43s	remaining: 5m 21s
7737:	learn: 0.0014466	total: 12m 42s	remaining: 3m 43s
7392:	learn: 0.0018941	total: 12m 43s	remaining: 4m 29s
7604:	learn: 0.0014306	total: 12m 43s	remaining: 4m
7610:	learn: 0.0015136	total: 12m 42s	remaining: 3m 59s
7738:	learn: 0.0014466	total: 12m 43s	remaining: 3m 42s
7036:	learn: 0.0013759	total: 12m 43s	remaining: 5m 21s
7605:	learn: 0.0014303	total: 12m 43s	remaining: 4m
7611:	learn: 0.0015136	total: 12m 42s	remaining: 3m 59s
7393:	learn: 0.0018936	total: 12m 43s	remaining: 4m 29s
7739:	learn: 0.0014466	total: 12m 43s	remaining: 3m 42s
7037:	learn: 0.0013759	total: 12m 43s	remaining: 5m 21s
7606:	learn: 0.0014299	total: 12m 43s	remaining: 4m
7394:	learn: 0.0018930	total: 12m 43s	remaining: 4m 28s
7740:	learn: 0.0014466	total: 12m 43s	remaining: 3m 42s
7612:	learn: 0.0015136	total: 12m 43s	remaining: 3m 59s
7395:	learn: 0.0018926	total: 12m 43s	remaining: 4m 28s
7607:	learn: 0.0014299	total: 12m 43s	remaining: 4m
7038:	learn: 0.0013758	total: 12m 43s	remaining: 5m 21s
7613:	learn: 0.0015136	total: 12m 43s	remaining: 3m 59s
7741:	learn: 0.0014466	total: 12m 43s	remaining: 3m 42s
7396:	learn: 0.0018922	total: 12m 43s	remaining: 4m 28s
7608:	learn: 0.0014299	total: 12m 43s	remaining: 3m 59s
7742:	learn: 0.0014466	total: 12m 43s	remaining: 3m 42s
7614:	learn: 0.0015131	total: 12m 43s	remaining: 3m 59s
7039:	learn: 0.0013758	total: 12m 43s	remaining: 5m 21s
7397:	learn: 0.0018918	total: 12m 43s	remaining: 4m 28s
7743:	learn: 0.0014466	total: 12m 43s	remaining: 3m 42s
7609:	learn: 0.0014299	total: 12m 43s	remaining: 3m 59s
7615:	learn: 0.0015131	total: 12m 43s	remaining: 3m 58s
7040:	learn: 0.0013758	total: 12m 43s	remaining: 5m 20s
7398:	learn: 0.0018914	total: 12m 43s	remaining: 4m 28s
7610:	learn: 0.0014299	total: 12m 43s	remaining: 3m 59s
7616:	learn: 0.0015131	total: 12m 43s	remaining: 3m 58s
7744:	learn: 0.0014466	total: 12m 43s	remaining: 3m 42s
7041:	learn: 0.0013758	total: 12m 43s	remaining: 5m 20s
7399:	learn: 0.0018909	total: 12m 43s	remaining: 4m 28s
7617:	learn: 0.0015131	total: 12m 43s	remaining: 3m 58s
7745:	learn: 0.0014466	total: 12m 43s	remaining: 3m 42s
7611:	learn: 0.0014299	total: 12m 43s	remaining: 3m 59s
7042:	learn: 0.0013758	total: 12m 43s	remaining: 5m 20s
7400:	learn: 0.0018904	total: 12m 43s	remaining: 4m 28s
7746:	learn: 0.0014466	total: 12m 43s	remaining: 3m 42s
7618:	learn: 0.0015131	total: 12m 43s	remaining: 3m 58s
7043:	learn: 0.0013758	total: 12m 43s	remaining: 5m 20s
7612:	learn: 0.0014299	total: 12m 43s	remaining: 3m 59s
7401:	learn: 0.0018899	total: 12m 44s	remaining: 4m 28s
7747:	learn: 0.0014466	total: 12m 43s	remaining: 3m 42s
7619:	learn: 0.0015131	total: 12m 43s	remaining: 3m 58s
7613:	learn: 0.0014299	total: 12m 44s	remaining: 3m 59s
7402:	learn: 0.0018895	total: 12m 44s	remaining: 4m 28s
7044:	learn: 0.0013758	total: 12m 44s	remaining: 5m 20s
7748:	learn: 0.0014466	total: 12m 43s	remaining: 3m 41s
7620:	learn: 0.0015131	total: 12m 43s	remaining: 3m 58s
7614:	learn: 0.0014295	total: 12m 44s	remaining: 3m 59s
7403:	learn: 0.0018891	total: 12m 44s	remaining: 4m 27s
7749:	learn: 0.0014466	total: 12m 44s	remaining: 3m 41s
7045:	learn: 0.0013758	total: 12m 44s	remaining: 5m 20s
7621:	learn: 0.0015131	total: 12m 43s	remaining: 3m 58s
7615:	learn: 0.0014295	total: 12m 44s	remaining: 3m 59s
7750:	learn: 0.0014466	total: 12m 44s	remaining: 3m 41s
7404:	learn: 0.0018886	total: 12m 44s	remaining: 4m 27s
7046:	learn: 0.0013758	total: 12m 44s	remaining: 5m 20s
7622:	learn: 0.0015127	total: 12m 44s	remaining: 3m 58s
7616:	learn: 0.0014295	total: 12m 44s	remaining: 3m 59s
7751:	learn: 0.0014466	total: 12m 44s	remaining: 3m 41s
7405:	learn: 0.0018882	total: 12m 44s	remaining: 4m 27s
7047:	learn: 0.0013758	total: 12m 44s	remaining: 5m 20s
7623:	learn: 0.0015127	total: 12m 44s	remaining: 3m 58s
7752:	learn: 0.0014466	total: 12m 44s	remaining: 3m 41s
7617:	learn: 0.0014295	total: 12m 44s	remaining: 3m 59s
7406:	learn: 0.0018877	total: 12m 44s	remaining: 4m 27s
7048:	learn: 0.0013758	total: 12m 44s	remaining: 5m 20s
7618:	learn: 0.0014295	total: 12m 44s	remaining: 3m 58s
7624:	learn: 0.0015127	total: 12m 44s	remaining: 3m 58s
7753:	learn: 0.0014466	total: 12m 44s	remaining: 3m 41s
7407:	learn: 0.0018873	total: 12m 44s	remaining: 4m 27s
7049:	learn: 0.0013758	total: 12m 44s	remaining: 5m 19s
7625:	learn: 0.0015127	total: 12m 44s	remaining: 3m 57s
7754:	learn: 0.0014460	total: 12m 44s	remaining: 3m 41s
7619:	learn: 0.0014295	total: 12m 44s	remaining: 3m 58s
7408:	learn: 0.0018868	total: 12m 44s	remaining: 4m 27s
7626:	learn: 0.0015127	total: 12m 44s	remaining: 3m 57s
7755:	learn: 0.0014460	total: 12m 44s	remaining: 3m 41s
7050:	learn: 0.0013758	total: 12m 44s	remaining: 5m 19s
7620:	learn: 0.0014295	total: 12m 44s	remaining: 3m 58s
7627:	learn: 0.0015127	total: 12m 44s	remaining: 3m 57s
7756:	learn: 0.0014460	total: 12m 44s	remaining: 3m 41s
7409:	learn: 0.0018864	total: 12m 44s	remaining: 4m 27s
7051:	learn: 0.0013758	total: 12m 44s	remaining: 5m 19s
7757:	learn: 0.0014460	total: 12m 44s	remaining: 3m 41s
7621:	learn: 0.0014295	total: 12m 44s	remaining: 3m 58s
7410:	learn: 0.0018859	total: 12m 44s	remaining: 4m 27s
7628:	learn: 0.0015127	total: 12m 44s	remaining: 3m 57s
7758:	learn: 0.0014460	total: 12m 44s	remaining: 3m 40s
7052:	learn: 0.0013758	total: 12m 44s	remaining: 5m 19s
7622:	learn: 0.0014295	total: 12m 44s	remaining: 3m 58s
7629:	learn: 0.0015127	total: 12m 44s	remaining: 3m 57s
7759:	learn: 0.0014460	total: 12m 44s	remaining: 3m 40s
7411:	learn: 0.0018854	total: 12m 45s	remaining: 4m 27s
7623:	learn: 0.0014295	total: 12m 45s	remaining: 3m 58s
7053:	learn: 0.0013758	total: 12m 45s	remaining: 5m 19s
7630:	learn: 0.0015127	total: 12m 44s	remaining: 3m 57s
7760:	learn: 0.0014460	total: 12m 45s	remaining: 3m 40s
7412:	learn: 0.0018850	total: 12m 45s	remaining: 4m 27s
7624:	learn: 0.0014295	total: 12m 45s	remaining: 3m 58s
7631:	learn: 0.0015127	total: 12m 44s	remaining: 3m 57s
7054:	learn: 0.0013758	total: 12m 45s	remaining: 5m 19s
7413:	learn: 0.0018845	total: 12m 45s	remaining: 4m 26s
7761:	learn: 0.0014458	total: 12m 45s	remaining: 3m 40s
7414:	learn: 0.0018840	total: 12m 45s	remaining: 4m 26s
7055:	learn: 0.0013758	total: 12m 45s	remaining: 5m 19s
7632:	learn: 0.0015127	total: 12m 45s	remaining: 3m 57s
7625:	learn: 0.0014291	total: 12m 45s	remaining: 3m 58s
7762:	learn: 0.0014455	total: 12m 45s	remaining: 3m 40s
7626:	learn: 0.0014286	total: 12m 45s	remaining: 3m 58s
7415:	learn: 0.0018836	total: 12m 45s	remaining: 4m 26s
7633:	learn: 0.0015127	total: 12m 45s	remaining: 3m 57s
7056:	learn: 0.0013758	total: 12m 45s	remaining: 5m 19s
7763:	learn: 0.0014455	total: 12m 45s	remaining: 3m 40s
7627:	learn: 0.0014286	total: 12m 45s	remaining: 3m 58s
7416:	learn: 0.0018831	total: 12m 45s	remaining: 4m 26s
7634:	learn: 0.0015127	total: 12m 45s	remaining: 3m 57s
7057:	learn: 0.0013757	total: 12m 45s	remaining: 5m 19s
7764:	learn: 0.0014455	total: 12m 45s	remaining: 3m 40s
7628:	learn: 0.0014286	total: 12m 45s	remaining: 3m 57s
7417:	learn: 0.0018826	total: 12m 45s	remaining: 4m 26s
7635:	learn: 0.0015127	total: 12m 45s	remaining: 3m 56s
7765:	learn: 0.0014455	total: 12m 45s	remaining: 3m 40s
7058:	learn: 0.0013757	total: 12m 45s	remaining: 5m 18s
7418:	learn: 0.0018821	total: 12m 45s	remaining: 4m 26s
7629:	learn: 0.0014287	total: 12m 45s	remaining: 3m 57s
7766:	learn: 0.0014455	total: 12m 45s	remaining: 3m 40s
7636:	learn: 0.0015127	total: 12m 45s	remaining: 3m 56s
7059:	learn: 0.0013757	total: 12m 45s	remaining: 5m 18s
7419:	learn: 0.0018817	total: 12m 45s	remaining: 4m 26s
7630:	learn: 0.0014286	total: 12m 45s	remaining: 3m 57s
7767:	learn: 0.0014455	total: 12m 45s	remaining: 3m 40s
7637:	learn: 0.0015127	total: 12m 45s	remaining: 3m 56s
7060:	learn: 0.0013757	total: 12m 45s	remaining: 5m 18s
7768:	learn: 0.0014455	total: 12m 45s	remaining: 3m 39s
7631:	learn: 0.0014287	total: 12m 45s	remaining: 3m 57s
7420:	learn: 0.0018809	total: 12m 45s	remaining: 4m 26s
7638:	learn: 0.0015124	total: 12m 45s	remaining: 3m 56s
7061:	learn: 0.0013757	total: 12m 45s	remaining: 5m 18s
7769:	learn: 0.0014455	total: 12m 45s	remaining: 3m 39s
7632:	learn: 0.0014287	total: 12m 46s	remaining: 3m 57s
7421:	learn: 0.0018805	total: 12m 46s	remaining: 4m 26s
7639:	learn: 0.0015124	total: 12m 45s	remaining: 3m 56s
7062:	learn: 0.0013757	total: 12m 46s	remaining: 5m 18s
7770:	learn: 0.0014455	total: 12m 45s	remaining: 3m 39s
7633:	learn: 0.0014287	total: 12m 46s	remaining: 3m 57s
7640:	learn: 0.0015124	total: 12m 45s	remaining: 3m 56s
7422:	learn: 0.0018801	total: 12m 46s	remaining: 4m 25s
7634:	learn: 0.0014286	total: 12m 46s	remaining: 3m 57s
7063:	learn: 0.0013757	total: 12m 46s	remaining: 5m 18s
7771:	learn: 0.0014455	total: 12m 46s	remaining: 3m 39s
7641:	learn: 0.0015124	total: 12m 45s	remaining: 3m 56s
7064:	learn: 0.0013757	total: 12m 46s	remaining: 5m 18s
7423:	learn: 0.0018796	total: 12m 46s	remaining: 4m 25s
7635:	learn: 0.0014287	total: 12m 46s	remaining: 3m 57s
7772:	learn: 0.0014455	total: 12m 46s	remaining: 3m 39s
7642:	learn: 0.0015120	total: 12m 46s	remaining: 3m 56s
7065:	learn: 0.0013754	total: 12m 46s	remaining: 5m 18s
7424:	learn: 0.0018790	total: 12m 46s	remaining: 4m 25s
7773:	learn: 0.0014455	total: 12m 46s	remaining: 3m 39s
7636:	learn: 0.0014287	total: 12m 46s	remaining: 3m 57s
7643:	learn: 0.0015120	total: 12m 46s	remaining: 3m 56s
7066:	learn: 0.0013754	total: 12m 46s	remaining: 5m 18s
7425:	learn: 0.0018785	total: 12m 46s	remaining: 4m 25s
7774:	learn: 0.0014455	total: 12m 46s	remaining: 3m 39s
7637:	learn: 0.0014287	total: 12m 46s	remaining: 3m 57s
7644:	learn: 0.0015120	total: 12m 46s	remaining: 3m 56s
7775:	learn: 0.0014455	total: 12m 46s	remaining: 3m 39s
7067:	learn: 0.0013754	total: 12m 46s	remaining: 5m 17s
7426:	learn: 0.0018780	total: 12m 46s	remaining: 4m 25s
7638:	learn: 0.0014286	total: 12m 46s	remaining: 3m 56s
7645:	learn: 0.0015115	total: 12m 46s	remaining: 3m 55s
7776:	learn: 0.0014455	total: 12m 46s	remaining: 3m 39s
7068:	learn: 0.0013754	total: 12m 46s	remaining: 5m 17s
7427:	learn: 0.0018776	total: 12m 46s	remaining: 4m 25s
7639:	learn: 0.0014286	total: 12m 46s	remaining: 3m 56s
7646:	learn: 0.0015115	total: 12m 46s	remaining: 3m 55s
7777:	learn: 0.0014455	total: 12m 46s	remaining: 3m 38s
7428:	learn: 0.0018771	total: 12m 46s	remaining: 4m 25s
7640:	learn: 0.0014286	total: 12m 46s	remaining: 3m 56s
7069:	learn: 0.0013754	total: 12m 46s	remaining: 5m 17s
7647:	learn: 0.0015115	total: 12m 46s	remaining: 3m 55s
7778:	learn: 0.0014455	total: 12m 46s	remaining: 3m 38s
7070:	learn: 0.0013754	total: 12m 46s	remaining: 5m 17s
7641:	learn: 0.0014283	total: 12m 46s	remaining: 3m 56s
7429:	learn: 0.0018766	total: 12m 46s	remaining: 4m 25s
7779:	learn: 0.0014455	total: 12m 46s	remaining: 3m 38s
7648:	learn: 0.0015115	total: 12m 46s	remaining: 3m 55s
7071:	learn: 0.0013754	total: 12m 46s	remaining: 5m 17s
7642:	learn: 0.0014282	total: 12m 46s	remaining: 3m 56s
7430:	learn: 0.0018761	total: 12m 47s	remaining: 4m 25s
7649:	learn: 0.0015115	total: 12m 46s	remaining: 3m 55s
7780:	learn: 0.0014455	total: 12m 46s	remaining: 3m 38s
7072:	learn: 0.0013751	total: 12m 47s	remaining: 5m 17s
7643:	learn: 0.0014283	total: 12m 47s	remaining: 3m 56s
7650:	learn: 0.0015115	total: 12m 46s	remaining: 3m 55s
7431:	learn: 0.0018757	total: 12m 47s	remaining: 4m 25s
7781:	learn: 0.0014455	total: 12m 47s	remaining: 3m 38s
7073:	learn: 0.0013747	total: 12m 47s	remaining: 5m 17s
7432:	learn: 0.0018754	total: 12m 47s	remaining: 4m 24s
7644:	learn: 0.0014282	total: 12m 47s	remaining: 3m 56s
7651:	learn: 0.0015115	total: 12m 46s	remaining: 3m 55s
7782:	learn: 0.0014455	total: 12m 47s	remaining: 3m 38s
7645:	learn: 0.0014279	total: 12m 47s	remaining: 3m 56s
7433:	learn: 0.0018749	total: 12m 47s	remaining: 4m 24s
7074:	learn: 0.0013746	total: 12m 47s	remaining: 5m 17s
7652:	learn: 0.0015115	total: 12m 47s	remaining: 3m 55s
7783:	learn: 0.0014455	total: 12m 47s	remaining: 3m 38s
7646:	learn: 0.0014274	total: 12m 47s	remaining: 3m 56s
7434:	learn: 0.0018745	total: 12m 47s	remaining: 4m 24s
7075:	learn: 0.0013746	total: 12m 47s	remaining: 5m 17s
7653:	learn: 0.0015115	total: 12m 47s	remaining: 3m 55s
7784:	learn: 0.0014455	total: 12m 47s	remaining: 3m 38s
7435:	learn: 0.0018738	total: 12m 47s	remaining: 4m 24s
7647:	learn: 0.0014274	total: 12m 47s	remaining: 3m 56s
7654:	learn: 0.0015115	total: 12m 47s	remaining: 3m 55s
7076:	learn: 0.0013746	total: 12m 47s	remaining: 5m 16s
7785:	learn: 0.0014455	total: 12m 47s	remaining: 3m 38s
7436:	learn: 0.0018733	total: 12m 47s	remaining: 4m 24s
7648:	learn: 0.0014274	total: 12m 47s	remaining: 3m 55s
7077:	learn: 0.0013746	total: 12m 47s	remaining: 5m 16s
7655:	learn: 0.0015115	total: 12m 47s	remaining: 3m 54s
7786:	learn: 0.0014455	total: 12m 47s	remaining: 3m 38s
7437:	learn: 0.0018729	total: 12m 47s	remaining: 4m 24s
7649:	learn: 0.0014274	total: 12m 47s	remaining: 3m 55s
7656:	learn: 0.0015115	total: 12m 47s	remaining: 3m 54s
7078:	learn: 0.0013746	total: 12m 47s	remaining: 5m 16s
7787:	learn: 0.0014455	total: 12m 47s	remaining: 3m 38s
7650:	learn: 0.0014274	total: 12m 47s	remaining: 3m 55s
7438:	learn: 0.0018723	total: 12m 47s	remaining: 4m 24s
7079:	learn: 0.0013746	total: 12m 47s	remaining: 5m 16s
7657:	learn: 0.0015115	total: 12m 47s	remaining: 3m 54s
7788:	learn: 0.0014455	total: 12m 47s	remaining: 3m 37s

7651:	learn: 0.0014270	total: 12m 47s	remaining: 3m 55s
7439:	learn: 0.0018719	total: 12m 47s	remaining: 4m 24s
7658:	learn: 0.0015115	total: 12m 47s	remaining: 3m 54s
7080:	learn: 0.0013746	total: 12m 47s	remaining: 5m 16s
7789:	learn: 0.0014455	total: 12m 47s	remaining: 3m 37s
7440:	learn: 0.0018715	total: 12m 47s	remaining: 4m 24s
7652:	learn: 0.0014266	total: 12m 47s	remaining: 3m 55s
7659:	learn: 0.0015115	total: 12m 47s	remaining: 3m 54s
7790:	learn: 0.0014455	total: 12m 47s	remaining: 3m 37s
7081:	learn: 0.0013746	total: 12m 48s	remaining: 5m 16s
7441:	learn: 0.0018712	total: 12m 48s	remaining: 4m 24s
7660:	learn: 0.0015115	total: 12m 47s	remaining: 3m 54s
7653:	learn: 0.0014266	total: 12m 48s	remaining: 3m 55s
7791:	learn: 0.0014455	total: 12m 47s	remaining: 3m 37s
7442:	learn: 0.0018706	total: 12m 48s	remaining: 4m 23s
7082:	learn: 0.0013746	total: 12m 48s	remaining: 5m 16s
7661:	learn: 0.0015115	total: 12m 47s	remaining: 3m 54s
7792:	learn: 0.0014455	total: 12m 48s	remaining: 3m 37s
7654:	learn: 0.0014266	total: 12m 48s	remaining: 3m 55s
7443:	learn: 0.0018701	total: 12m 48s	remaining: 4m 23s
7083:	learn: 0.0013746	total: 12m 48s	remaining: 5m 16s
7662:	learn: 0.0015115	total: 12m 48s	remaining: 3m 54s
7793:	learn: 0.0014455	total: 12m 48s	remaining: 3m 37s
7655:	learn: 0.0014266	total: 12m 48s	remaining: 3m 55s
7663:	learn: 0.0015115	total: 12m 48s	remaining: 3m 54s
7444:	learn: 0.0018695	total: 12m 48s	remaining: 4m 23s
7084:	learn: 0.0013746	total: 12m 48s	remaining: 5m 16s
7794:	learn: 0.0014455	total: 12m 48s	remaining: 3m 37s
7656:	learn: 0.0014263	total: 12m 48s	remaining: 3m 55s
7664:	learn: 0.0015115	total: 12m 48s	remaining: 3m 54s
7445:	learn: 0.0018690	total: 12m 48s	remaining: 4m 23s
7085:	learn: 0.0013746	total: 12m 48s	remaining: 5m 16s
7795:	learn: 0.0014455	total: 12m 48s	remaining: 3m 37s
7657:	learn: 0.0014263	total: 12m 48s	remaining: 3m 55s
7665:	learn: 0.0015115	total: 12m 48s	remaining: 3m 53s
7446:	learn: 0.0018686	total: 12m 48s	remaining: 4m 23s
7086:	learn: 0.0013746	total: 12m 48s	remaining: 5m 15s
7796:	learn: 0.0014455	total: 12m 48s	remaining: 3m 37s
7658:	learn: 0.0014263	total: 12m 48s	remaining: 3m 54s
7666:	learn: 0.0015115	total: 12m 48s	remaining: 3m 53s
7087:	learn: 0.0013746	total: 12m 48s	remaining: 5m 15s
7447:	learn: 0.0018682	total: 12m 48s	remaining: 4m 23s
7797:	learn: 0.0014455	total: 12m 48s	remaining: 3m 37s
7667:	learn: 0.0015115	total: 12m 48s	remaining: 3m 53s
7659:	learn: 0.0014263	total: 12m 48s	remaining: 3m 54s
7448:	learn: 0.0018678	total: 12m 48s	remaining: 4m 23s
7798:	learn: 0.0014455	total: 12m 48s	remaining: 3m 36s
7088:	learn: 0.0013746	total: 12m 48s	remaining: 5m 15s
7660:	learn: 0.0014263	total: 12m 48s	remaining: 3m 54s
7799:	learn: 0.0014455	total: 12m 48s	remaining: 3m 36s
7668:	learn: 0.0015115	total: 12m 48s	remaining: 3m 53s
7449:	learn: 0.0018674	total: 12m 48s	remaining: 4m 23s
7661:	learn: 0.0014262	total: 12m 48s	remaining: 3m 54s
7089:	learn: 0.0013746	total: 12m 48s	remaining: 5m 15s
7669:	learn: 0.0015115	total: 12m 48s	remaining: 3m 53s
7800:	learn: 0.0014455	total: 12m 48s	remaining: 3m 36s
7450:	learn: 0.0018668	total: 12m 49s	remaining: 4m 23s
7662:	learn: 0.0014262	total: 12m 48s	remaining: 3m 54s
7090:	learn: 0.0013746	total: 12m 49s	remaining: 5m 15s
7801:	learn: 0.0014455	total: 12m 48s	remaining: 3m 36s
7670:	learn: 0.0015115	total: 12m 48s	remaining: 3m 53s
7451:	learn: 0.0018664	total: 12m 49s	remaining: 4m 22s
7091:	learn: 0.0013745	total: 12m 49s	remaining: 5m 15s
7671:	learn: 0.0015115	total: 12m 48s	remaining: 3m 53s
7802:	learn: 0.0014455	total: 12m 48s	remaining: 3m 36s
7663:	learn: 0.0014259	total: 12m 49s	remaining: 3m 54s
7452:	learn: 0.0018660	total: 12m 49s	remaining: 4m 22s
7672:	learn: 0.0015115	total: 12m 48s	remaining: 3m 53s
7092:	learn: 0.0013745	total: 12m 49s	remaining: 5m 15s
7664:	learn: 0.0014259	total: 12m 49s	remaining: 3m 54s
7803:	learn: 0.0014450	total: 12m 49s	remaining: 3m 36s
7453:	learn: 0.0018655	total: 12m 49s	remaining: 4m 22s
7673:	learn: 0.0015115	total: 12m 49s	remaining: 3m 53s
7093:	learn: 0.0013745	total: 12m 49s	remaining: 5m 15s
7665:	learn: 0.0014259	total: 12m 49s	remaining: 3m 54s
7804:	learn: 0.0014450	total: 12m 49s	remaining: 3m 36s
7454:	learn: 0.0018650	total: 12m 49s	remaining: 4m 22s
7674:	learn: 0.0015115	total: 12m 49s	remaining: 3m 52s
7094:	learn: 0.0013746	total: 12m 49s	remaining: 5m 15s
7666:	learn: 0.0014259	total: 12m 49s	remaining: 3m 54s
7805:	learn: 0.0014450	total: 12m 49s	remaining: 3m 36s
7455:	learn: 0.0018645	total: 12m 49s	remaining: 4m 22s
7675:	learn: 0.0015115	total: 12m 49s	remaining: 3m 52s
7095:	learn: 0.0013746	total: 12m 49s	remaining: 5m 14s
7667:	learn: 0.0014259	total: 12m 49s	remaining: 3m 54s
7806:	learn: 0.0014450	total: 12m 49s	remaining: 3m 36s
7676:	learn: 0.0015115	total: 12m 49s	remaining: 3m 52s
7096:	learn: 0.0013746	total: 12m 49s	remaining: 5m 14s
7456:	learn: 0.0018641	total: 12m 49s	remaining: 4m 22s
7668:	learn: 0.0014259	total: 12m 49s	remaining: 3m 53s
7807:	learn: 0.0014450	total: 12m 49s	remaining: 3m 36s
7677:	learn: 0.0015115	total: 12m 49s	remaining: 3m 52s
7097:	learn: 0.0013746	total: 12m 49s	remaining: 5m 14s
7457:	learn: 0.0018634	total: 12m 49s	remaining: 4m 22s
7669:	learn: 0.0014259	total: 12m 49s	remaining: 3m 53s
7808:	learn: 0.0014445	total: 12m 49s	remaining: 3m 35s
7098:	learn: 0.0013745	total: 12m 49s	remaining: 5m 14s
7678:	learn: 0.0015115	total: 12m 49s	remaining: 3m 52s
7670:	learn: 0.0014259	total: 12m 49s	remaining: 3m 53s
7458:	learn: 0.0018630	total: 12m 49s	remaining: 4m 22s
7809:	learn: 0.0014440	total: 12m 49s	remaining: 3m 35s
7099:	learn: 0.0013746	total: 12m 49s	remaining: 5m 14s
7679:	learn: 0.0015115	total: 12m 49s	remaining: 3m 52s
7671:	learn: 0.0014259	total: 12m 49s	remaining: 3m 53s
7810:	learn: 0.0014440	total: 12m 49s	remaining: 3m 35s
7459:	learn: 0.0018625	total: 12m 49s	remaining: 4m 22s
7100:	learn: 0.0013745	total: 12m 49s	remaining: 5m 14s
7680:	learn: 0.0015115	total: 12m 49s	remaining: 3m 52s
7811:	learn: 0.0014436	total: 12m 49s	remaining: 3m 35s
7672:	learn: 0.0014259	total: 12m 50s	remaining: 3m 53s
7460:	learn: 0.0018621	total: 12m 50s	remaining: 4m 22s
7812:	learn: 0.0014436	total: 12m 49s	remaining: 3m 35s
7673:	learn: 0.0014259	total: 12m 50s	remaining: 3m 53s
7681:	learn: 0.0015115	total: 12m 49s	remaining: 3m 52s
7101:	learn: 0.0013745	total: 12m 50s	remaining: 5m 14s
7461:	learn: 0.0018616	total: 12m 50s	remaining: 4m 21s
7813:	learn: 0.0014436	total: 12m 50s	remaining: 3m 35s
7674:	learn: 0.0014259	total: 12m 50s	remaining: 3m 53s
7102:	learn: 0.0013745	total: 12m 50s	remaining: 5m 14s
7682:	learn: 0.0015115	total: 12m 50s	remaining: 3m 52s
7462:	learn: 0.0018613	total: 12m 50s	remaining: 4m 21s
7675:	learn: 0.0014256	total: 12m 50s	remaining: 3m 53s
7814:	learn: 0.0014436	total: 12m 50s	remaining: 3m 35s
7103:	learn: 0.0013745	total: 12m 50s	remaining: 5m 14s
7683:	learn: 0.0015115	total: 12m 50s	remaining: 3m 52s
7463:	learn: 0.0018608	total: 12m 50s	remaining: 4m 21s
7676:	learn: 0.0014256	total: 12m 50s	remaining: 3m 53s
7815:	learn: 0.0014436	total: 12m 50s	remaining: 3m 35s
7104:	learn: 0.0013745	total: 12m 50s	remaining: 5m 13s
7684:	learn: 0.0015115	total: 12m 50s	remaining: 3m 52s
7677:	learn: 0.0014256	total: 12m 50s	remaining: 3m 53s
7105:	learn: 0.0013745	total: 12m 50s	remaining: 5m 13s
7816:	learn: 0.0014436	total: 12m 50s	remaining: 3m 35s
7685:	learn: 0.0015115	total: 12m 50s	remaining: 3m 51s
7464:	learn: 0.0018599	total: 12m 50s	remaining: 4m 21s
7678:	learn: 0.0014256	total: 12m 50s	remaining: 3m 52s
7106:	learn: 0.0013745	total: 12m 50s	remaining: 5m 13s
7465:	learn: 0.0018596	total: 12m 50s	remaining: 4m 21s
7817:	learn: 0.0014436	total: 12m 50s	remaining: 3m 35s
7679:	learn: 0.0014256	total: 12m 50s	remaining: 3m 52s
7686:	learn: 0.0015115	total: 12m 50s	remaining: 3m 51s
7466:	learn: 0.0018590	total: 12m 50s	remaining: 4m 21s
7107:	learn: 0.0013745	total: 12m 50s	remaining: 5m 13s
7680:	learn: 0.0014256	total: 12m 50s	remaining: 3m 52s
7818:	learn: 0.0014436	total: 12m 50s	remaining: 3m 34s
7687:	learn: 0.0015115	total: 12m 50s	remaining: 3m 51s
7108:	learn: 0.0013745	total: 12m 50s	remaining: 5m 13s
7467:	learn: 0.0018585	total: 12m 50s	remaining: 4m 21s
7681:	learn: 0.0014256	total: 12m 50s	remaining: 3m 52s
7819:	learn: 0.0014434	total: 12m 50s	remaining: 3m 34s
7688:	learn: 0.0015115	total: 12m 50s	remaining: 3m 51s
7109:	learn: 0.0013745	total: 12m 50s	remaining: 5m 13s
7468:	learn: 0.0018582	total: 12m 50s	remaining: 4m 21s
7682:	learn: 0.0014256	total: 12m 50s	remaining: 3m 52s
7689:	learn: 0.0015115	total: 12m 50s	remaining: 3m 51s
7820:	learn: 0.0014434	total: 12m 50s	remaining: 3m 34s
7110:	learn: 0.0013745	total: 12m 50s	remaining: 5m 13s
7469:	learn: 0.0018576	total: 12m 51s	remaining: 4m 21s
7690:	learn: 0.0015115	total: 12m 50s	remaining: 3m 51s
7470:	learn: 0.0018573	total: 12m 51s	remaining: 4m 21s
7683:	learn: 0.0014256	total: 12m 51s	remaining: 3m 52s
7821:	learn: 0.0014434	total: 12m 50s	remaining: 3m 34s
7111:	learn: 0.0013745	total: 12m 51s	remaining: 5m 13s
7684:	learn: 0.0014256	total: 12m 51s	remaining: 3m 52s
7691:	learn: 0.0015115	total: 12m 50s	remaining: 3m 51s
7471:	learn: 0.0018568	total: 12m 51s	remaining: 4m 20s
7822:	learn: 0.0014434	total: 12m 51s	remaining: 3m 34s
7685:	learn: 0.0014256	total: 12m 51s	remaining: 3m 52s
7112:	learn: 0.0013745	total: 12m 51s	remaining: 5m 13s
7823:	learn: 0.0014434	total: 12m 51s	remaining: 3m 34s
7692:	learn: 0.0015115	total: 12m 51s	remaining: 3m 51s
7686:	learn: 0.0014256	total: 12m 51s	remaining: 3m 52s
7472:	learn: 0.0018562	total: 12m 51s	remaining: 4m 20s
7113:	learn: 0.0013743	total: 12m 51s	remaining: 5m 12s
7824:	learn: 0.0014434	total: 12m 51s	remaining: 3m 34s
7693:	learn: 0.0015115	total: 12m 51s	remaining: 3m 51s
7473:	learn: 0.0018554	total: 12m 51s	remaining: 4m 20s
7114:	learn: 0.0013743	total: 12m 51s	remaining: 5m 12s
7825:	learn: 0.0014434	total: 12m 51s	remaining: 3m 34s
7687:	learn: 0.0014252	total: 12m 51s	remaining: 3m 51s
7694:	learn: 0.0015115	total: 12m 51s	remaining: 3m 51s
7474:	learn: 0.0018548	total: 12m 51s	remaining: 4m 20s
7115:	learn: 0.0013743	total: 12m 51s	remaining: 5m 12s
7688:	learn: 0.0014249	total: 12m 51s	remaining: 3m 51s
7826:	learn: 0.0014434	total: 12m 51s	remaining: 3m 34s
7475:	learn: 0.0018544	total: 12m 51s	remaining: 4m 20s
7695:	learn: 0.0015115	total: 12m 51s	remaining: 3m 50s
7116:	learn: 0.0013743	total: 12m 51s	remaining: 5m 12s
7689:	learn: 0.0014245	total: 12m 51s	remaining: 3m 51s
7827:	learn: 0.0014434	total: 12m 51s	remaining: 3m 34s
7476:	learn: 0.0018536	total: 12m 51s	remaining: 4m 20s
7117:	learn: 0.0013743	total: 12m 51s	remaining: 5m 12s
7696:	learn: 0.0015115	total: 12m 51s	remaining: 3m 50s
7690:	learn: 0.0014245	total: 12m 51s	remaining: 3m 51s
7828:	learn: 0.0014434	total: 12m 51s	remaining: 3m 33s
7477:	learn: 0.0018532	total: 12m 51s	remaining: 4m 20s
7691:	learn: 0.0014244	total: 12m 51s	remaining: 3m 51s
7697:	learn: 0.0015115	total: 12m 51s	remaining: 3m 50s
7118:	learn: 0.0013743	total: 12m 51s	remaining: 5m 12s
7829:	learn: 0.0014434	total: 12m 51s	remaining: 3m 33s
7478:	learn: 0.0018525	total: 12m 51s	remaining: 4m 20s
7692:	learn: 0.0014244	total: 12m 51s	remaining: 3m 51s
7698:	learn: 0.0015115	total: 12m 51s	remaining: 3m 50s
7119:	learn: 0.0013743	total: 12m 51s	remaining: 5m 12s
7479:	learn: 0.0018518	total: 12m 51s	remaining: 4m 20s
7830:	learn: 0.0014434	total: 12m 51s	remaining: 3m 33s
7693:	learn: 0.0014244	total: 12m 51s	remaining: 3m 51s
7699:	learn: 0.0015115	total: 12m 51s	remaining: 3m 50s
7831:	learn: 0.0014434	total: 12m 51s	remaining: 3m 33s
7120:	learn: 0.0013743	total: 12m 52s	remaining: 5m 12s
7480:	learn: 0.0018513	total: 12m 52s	remaining: 4m 19s
7694:	learn: 0.0014244	total: 12m 52s	remaining: 3m 51s
7832:	learn: 0.0014434	total: 12m 51s	remaining: 3m 33s
7700:	learn: 0.0015115	total: 12m 51s	remaining: 3m 50s
7121:	learn: 0.0013743	total: 12m 52s	remaining: 5m 12s
7481:	learn: 0.0018509	total: 12m 52s	remaining: 4m 19s
7695:	learn: 0.0014244	total: 12m 52s	remaining: 3m 51s
7833:	learn: 0.0014434	total: 12m 52s	remaining: 3m 33s
7701:	learn: 0.0015115	total: 12m 51s	remaining: 3m 50s
7696:	learn: 0.0014244	total: 12m 52s	remaining: 3m 51s
7482:	learn: 0.0018505	total: 12m 52s	remaining: 4m 19s
7122:	learn: 0.0013743	total: 12m 52s	remaining: 5m 11s
7834:	learn: 0.0014434	total: 12m 52s	remaining: 3m 33s
7702:	learn: 0.0015115	total: 12m 52s	remaining: 3m 50s
7697:	learn: 0.0014244	total: 12m 52s	remaining: 3m 50s
7483:	learn: 0.0018500	total: 12m 52s	remaining: 4m 19s
7123:	learn: 0.0013743	total: 12m 52s	remaining: 5m 11s
7835:	learn: 0.0014434	total: 12m 52s	remaining: 3m 33s
7698:	learn: 0.0014244	total: 12m 52s	remaining: 3m 50s
7703:	learn: 0.0015115	total: 12m 52s	remaining: 3m 50s
7484:	learn: 0.0018495	total: 12m 52s	remaining: 4m 19s
7836:	learn: 0.0014433	total: 12m 52s	remaining: 3m 33s
7124:	learn: 0.0013743	total: 12m 52s	remaining: 5m 11s
7699:	learn: 0.0014244	total: 12m 52s	remaining: 3m 50s
7704:	learn: 0.0015115	total: 12m 52s	remaining: 3m 50s
7837:	learn: 0.0014433	total: 12m 52s	remaining: 3m 33s
7485:	learn: 0.0018486	total: 12m 52s	remaining: 4m 19s
7125:	learn: 0.0013739	total: 12m 52s	remaining: 5m 11s
7700:	learn: 0.0014244	total: 12m 52s	remaining: 3m 50s
7705:	learn: 0.0015115	total: 12m 52s	remaining: 3m 49s
7838:	learn: 0.0014433	total: 12m 52s	remaining: 3m 32s
7486:	learn: 0.0018483	total: 12m 52s	remaining: 4m 19s
7126:	learn: 0.0013739	total: 12m 52s	remaining: 5m 11s
7701:	learn: 0.0014244	total: 12m 52s	remaining: 3m 50s
7706:	learn: 0.0015115	total: 12m 52s	remaining: 3m 49s
7839:	learn: 0.0014433	total: 12m 52s	remaining: 3m 32s
7487:	learn: 0.0018478	total: 12m 52s	remaining: 4m 19s
7127:	learn: 0.0013739	total: 12m 52s	remaining: 5m 11s
7707:	learn: 0.0015115	total: 12m 52s	remaining: 3m 49s
7840:	learn: 0.0014433	total: 12m 52s	remaining: 3m 32s
7702:	learn: 0.0014244	total: 12m 52s	remaining: 3m 50s
7841:	learn: 0.0014433	total: 12m 52s	remaining: 3m 32s
7128:	learn: 0.0013738	total: 12m 52s	remaining: 5m 11s
7488:	learn: 0.0018471	total: 12m 52s	remaining: 4m 19s
7703:	learn: 0.0014244	total: 12m 52s	remaining: 3m 50s
7708:	learn: 0.0015115	total: 12m 52s	remaining: 3m 49s
7842:	learn: 0.0014433	total: 12m 52s	remaining: 3m 32s
7129:	learn: 0.0013738	total: 12m 53s	remaining: 5m 11s
7704:	learn: 0.0014244	total: 12m 53s	remaining: 3m 50s
7489:	learn: 0.0018466	total: 12m 53s	remaining: 4m 19s
7709:	learn: 0.0015115	total: 12m 52s	remaining: 3m 49s
7843:	learn: 0.0014433	total: 12m 52s	remaining: 3m 32s
7705:	learn: 0.0014244	total: 12m 53s	remaining: 3m 50s
7130:	learn: 0.0013737	total: 12m 53s	remaining: 5m 11s
7490:	learn: 0.0018461	total: 12m 53s	remaining: 4m 18s
7844:	learn: 0.0014433	total: 12m 53s	remaining: 3m 32s
7710:	learn: 0.0015115	total: 12m 52s	remaining: 3m 49s
7706:	learn: 0.0014244	total: 12m 53s	remaining: 3m 50s
7131:	learn: 0.0013737	total: 12m 53s	remaining: 5m 10s
7491:	learn: 0.0018456	total: 12m 53s	remaining: 4m 18s
7707:	learn: 0.0014244	total: 12m 53s	remaining: 3m 49s
7711:	learn: 0.0015115	total: 12m 53s	remaining: 3m 49s
7845:	learn: 0.0014433	total: 12m 53s	remaining: 3m 32s
7492:	learn: 0.0018451	total: 12m 53s	remaining: 4m 18s
7132:	learn: 0.0013737	total: 12m 53s	remaining: 5m 10s
7708:	learn: 0.0014244	total: 12m 53s	remaining: 3m 49s
7846:	learn: 0.0014433	total: 12m 53s	remaining: 3m 32s
7712:	learn: 0.0015115	total: 12m 53s	remaining: 3m 49s
7133:	learn: 0.0013737	total: 12m 53s	remaining: 5m 10s
7709:	learn: 0.0014244	total: 12m 53s	remaining: 3m 49s
7493:	learn: 0.0018446	total: 12m 53s	remaining: 4m 18s
7847:	learn: 0.0014433	total: 12m 53s	remaining: 3m 32s
7713:	learn: 0.0015115	total: 12m 53s	remaining: 3m 49s
7134:	learn: 0.0013737	total: 12m 53s	remaining: 5m 10s
7494:	learn: 0.0018443	total: 12m 53s	remaining: 4m 18s
7710:	learn: 0.0014244	total: 12m 53s	remaining: 3m 49s
7848:	learn: 0.0014433	total: 12m 53s	remaining: 3m 31s
7714:	learn: 0.0015115	total: 12m 53s	remaining: 3m 49s
7495:	learn: 0.0018438	total: 12m 53s	remaining: 4m 18s
7711:	learn: 0.0014244	total: 12m 53s	remaining: 3m 49s
7135:	learn: 0.0013736	total: 12m 53s	remaining: 5m 10s
7849:	learn: 0.0014433	total: 12m 53s	remaining: 3m 31s

7715:	learn: 0.0015115	total: 12m 53s	remaining: 3m 48s
7496:	learn: 0.0018432	total: 12m 53s	remaining: 4m 18s
7712:	learn: 0.0014241	total: 12m 53s	remaining: 3m 49s
7136:	learn: 0.0013736	total: 12m 53s	remaining: 5m 10s
7850:	learn: 0.0014433	total: 12m 53s	remaining: 3m 31s
7716:	learn: 0.0015115	total: 12m 53s	remaining: 3m 48s
7497:	learn: 0.0018428	total: 12m 53s	remaining: 4m 18s
7851:	learn: 0.0014433	total: 12m 53s	remaining: 3m 31s
7713:	learn: 0.0014237	total: 12m 53s	remaining: 3m 49s
7717:	learn: 0.0015115	total: 12m 53s	remaining: 3m 48s
7137:	learn: 0.0013732	total: 12m 53s	remaining: 5m 10s
7498:	learn: 0.0018425	total: 12m 53s	remaining: 4m 18s
7852:	learn: 0.0014433	total: 12m 53s	remaining: 3m 31s
7714:	learn: 0.0014237	total: 12m 53s	remaining: 3m 49s
7499:	learn: 0.0018421	total: 12m 54s	remaining: 4m 18s
7138:	learn: 0.0013730	total: 12m 53s	remaining: 5m 10s
7718:	learn: 0.0015115	total: 12m 53s	remaining: 3m 48s
7853:	learn: 0.0014433	total: 12m 53s	remaining: 3m 31s
7719:	learn: 0.0015115	total: 12m 53s	remaining: 3m 48s
7715:	learn: 0.0014237	total: 12m 54s	remaining: 3m 49s
7500:	learn: 0.0018416	total: 12m 54s	remaining: 4m 17s
7139:	learn: 0.0013730	total: 12m 54s	remaining: 5m 10s
7854:	learn: 0.0014432	total: 12m 54s	remaining: 3m 31s
7720:	learn: 0.0015115	total: 12m 53s	remaining: 3m 48s
7501:	learn: 0.0018411	total: 12m 54s	remaining: 4m 17s
7716:	learn: 0.0014237	total: 12m 54s	remaining: 3m 49s
7140:	learn: 0.0013730	total: 12m 54s	remaining: 5m 9s
7855:	learn: 0.0014432	total: 12m 54s	remaining: 3m 31s
7502:	learn: 0.0018407	total: 12m 54s	remaining: 4m 17s
7721:	learn: 0.0015110	total: 12m 54s	remaining: 3m 48s
7717:	learn: 0.0014237	total: 12m 54s	remaining: 3m 48s
7141:	learn: 0.0013730	total: 12m 54s	remaining: 5m 9s
7856:	learn: 0.0014432	total: 12m 54s	remaining: 3m 31s
7718:	learn: 0.0014237	total: 12m 54s	remaining: 3m 48s
7722:	learn: 0.0015110	total: 12m 54s	remaining: 3m 48s
7503:	learn: 0.0018400	total: 12m 54s	remaining: 4m 17s
7142:	learn: 0.0013730	total: 12m 54s	remaining: 5m 9s
7719:	learn: 0.0014232	total: 12m 54s	remaining: 3m 48s
7857:	learn: 0.0014432	total: 12m 54s	remaining: 3m 31s
7723:	learn: 0.0015110	total: 12m 54s	remaining: 3m 48s
7504:	learn: 0.0018396	total: 12m 54s	remaining: 4m 17s
7143:	learn: 0.0013730	total: 12m 54s	remaining: 5m 9s
7720:	learn: 0.0014232	total: 12m 54s	remaining: 3m 48s
7858:	learn: 0.0014432	total: 12m 54s	remaining: 3m 30s
7724:	learn: 0.0015110	total: 12m 54s	remaining: 3m 48s
7505:	learn: 0.0018393	total: 12m 54s	remaining: 4m 17s
7721:	learn: 0.0014232	total: 12m 54s	remaining: 3m 48s
7859:	learn: 0.0014432	total: 12m 54s	remaining: 3m 30s
7725:	learn: 0.0015110	total: 12m 54s	remaining: 3m 47s
7144:	learn: 0.0013730	total: 12m 54s	remaining: 5m 9s
7506:	learn: 0.0018387	total: 12m 54s	remaining: 4m 17s
7722:	learn: 0.0014232	total: 12m 54s	remaining: 3m 48s
7726:	learn: 0.0015106	total: 12m 54s	remaining: 3m 47s
7860:	learn: 0.0014432	total: 12m 54s	remaining: 3m 30s
7145:	learn: 0.0013730	total: 12m 54s	remaining: 5m 9s
7723:	learn: 0.0014232	total: 12m 54s	remaining: 3m 48s
7727:	learn: 0.0015106	total: 12m 54s	remaining: 3m 47s
7507:	learn: 0.0018383	total: 12m 54s	remaining: 4m 17s
7146:	learn: 0.0013730	total: 12m 54s	remaining: 5m 9s
7861:	learn: 0.0014432	total: 12m 54s	remaining: 3m 30s
7728:	learn: 0.0015106	total: 12m 54s	remaining: 3m 47s
7724:	learn: 0.0014232	total: 12m 54s	remaining: 3m 48s
7147:	learn: 0.0013730	total: 12m 54s	remaining: 5m 9s
7862:	learn: 0.0014432	total: 12m 54s	remaining: 3m 30s
7508:	learn: 0.0018377	total: 12m 55s	remaining: 4m 17s
7725:	learn: 0.0014232	total: 12m 55s	remaining: 3m 48s
7729:	learn: 0.0015106	total: 12m 54s	remaining: 3m 47s
7148:	learn: 0.0013730	total: 12m 55s	remaining: 5m 9s
7863:	learn: 0.0014432	total: 12m 54s	remaining: 3m 30s
7509:	learn: 0.0018373	total: 12m 55s	remaining: 4m 17s
7730:	learn: 0.0015107	total: 12m 54s	remaining: 3m 47s
7864:	learn: 0.0014432	total: 12m 54s	remaining: 3m 30s
7726:	learn: 0.0014227	total: 12m 55s	remaining: 3m 48s
7149:	learn: 0.0013730	total: 12m 55s	remaining: 5m 8s
7865:	learn: 0.0014432	total: 12m 55s	remaining: 3m 30s
7731:	learn: 0.0015106	total: 12m 54s	remaining: 3m 47s
7510:	learn: 0.0018368	total: 12m 55s	remaining: 4m 16s
7727:	learn: 0.0014227	total: 12m 55s	remaining: 3m 47s
7866:	learn: 0.0014432	total: 12m 55s	remaining: 3m 30s
7732:	learn: 0.0015106	total: 12m 55s	remaining: 3m 47s
7150:	learn: 0.0013730	total: 12m 55s	remaining: 5m 8s
7511:	learn: 0.0018364	total: 12m 55s	remaining: 4m 16s
7867:	learn: 0.0014432	total: 12m 55s	remaining: 3m 30s
7728:	learn: 0.0014227	total: 12m 55s	remaining: 3m 47s
7733:	learn: 0.0015106	total: 12m 55s	remaining: 3m 47s
7512:	learn: 0.0018355	total: 12m 55s	remaining: 4m 16s
7151:	learn: 0.0013730	total: 12m 55s	remaining: 5m 8s
7729:	learn: 0.0014227	total: 12m 55s	remaining: 3m 47s
7868:	learn: 0.0014432	total: 12m 55s	remaining: 3m 29s
7513:	learn: 0.0018351	total: 12m 55s	remaining: 4m 16s
7734:	learn: 0.0015106	total: 12m 55s	remaining: 3m 47s
7152:	learn: 0.0013730	total: 12m 55s	remaining: 5m 8s
7869:	learn: 0.0014432	total: 12m 55s	remaining: 3m 29s
7730:	learn: 0.0014227	total: 12m 55s	remaining: 3m 47s
7735:	learn: 0.0015106	total: 12m 55s	remaining: 3m 46s
7514:	learn: 0.0018347	total: 12m 55s	remaining: 4m 16s
7153:	learn: 0.0013730	total: 12m 55s	remaining: 5m 8s
7870:	learn: 0.0014432	total: 12m 55s	remaining: 3m 29s
7736:	learn: 0.0015106	total: 12m 55s	remaining: 3m 46s
7731:	learn: 0.0014227	total: 12m 55s	remaining: 3m 47s
7515:	learn: 0.0018339	total: 12m 55s	remaining: 4m 16s
7871:	learn: 0.0014432	total: 12m 55s	remaining: 3m 29s
7154:	learn: 0.0013730	total: 12m 55s	remaining: 5m 8s
7737:	learn: 0.0015106	total: 12m 55s	remaining: 3m 46s
7732:	learn: 0.0014227	total: 12m 55s	remaining: 3m 47s
7872:	learn: 0.0014432	total: 12m 55s	remaining: 3m 29s
7516:	learn: 0.0018330	total: 12m 55s	remaining: 4m 16s
7155:	learn: 0.0013730	total: 12m 55s	remaining: 5m 8s
7738:	learn: 0.0015102	total: 12m 55s	remaining: 3m 46s
7733:	learn: 0.0014227	total: 12m 55s	remaining: 3m 47s
7873:	learn: 0.0014432	total: 12m 55s	remaining: 3m 29s
7739:	learn: 0.0015102	total: 12m 55s	remaining: 3m 46s
7517:	learn: 0.0018327	total: 12m 55s	remaining: 4m 16s
7156:	learn: 0.0013727	total: 12m 55s	remaining: 5m 8s
7734:	learn: 0.0014227	total: 12m 55s	remaining: 3m 47s
7874:	learn: 0.0014432	total: 12m 55s	remaining: 3m 29s
7740:	learn: 0.0015102	total: 12m 55s	remaining: 3m 46s
7518:	learn: 0.0018323	total: 12m 56s	remaining: 4m 16s
7735:	learn: 0.0014227	total: 12m 56s	remaining: 3m 47s
7157:	learn: 0.0013727	total: 12m 56s	remaining: 5m 8s
7875:	learn: 0.0014432	total: 12m 55s	remaining: 3m 29s
7741:	learn: 0.0015102	total: 12m 55s	remaining: 3m 46s
7736:	learn: 0.0014227	total: 12m 56s	remaining: 3m 47s
7519:	learn: 0.0018315	total: 12m 56s	remaining: 4m 15s
7742:	learn: 0.0015102	total: 12m 55s	remaining: 3m 46s
7158:	learn: 0.0013727	total: 12m 56s	remaining: 5m 8s
7876:	learn: 0.0014432	total: 12m 56s	remaining: 3m 29s
7520:	learn: 0.0018311	total: 12m 56s	remaining: 4m 15s
7737:	learn: 0.0014227	total: 12m 56s	remaining: 3m 46s
7743:	learn: 0.0015102	total: 12m 56s	remaining: 3m 46s
7159:	learn: 0.0013727	total: 12m 56s	remaining: 5m 7s
7521:	learn: 0.0018308	total: 12m 56s	remaining: 4m 15s
7877:	learn: 0.0014432	total: 12m 56s	remaining: 3m 29s
7744:	learn: 0.0015102	total: 12m 56s	remaining: 3m 45s
7738:	learn: 0.0014227	total: 12m 56s	remaining: 3m 46s
7522:	learn: 0.0018299	total: 12m 56s	remaining: 4m 15s
7160:	learn: 0.0013727	total: 12m 56s	remaining: 5m 7s
7878:	learn: 0.0014432	total: 12m 56s	remaining: 3m 28s
7745:	learn: 0.0015102	total: 12m 56s	remaining: 3m 45s
7739:	learn: 0.0014227	total: 12m 56s	remaining: 3m 46s
7161:	learn: 0.0013727	total: 12m 56s	remaining: 5m 7s
7523:	learn: 0.0018290	total: 12m 56s	remaining: 4m 15s
7746:	learn: 0.0015102	total: 12m 56s	remaining: 3m 45s
7740:	learn: 0.0014227	total: 12m 56s	remaining: 3m 46s
7879:	learn: 0.0014432	total: 12m 56s	remaining: 3m 28s
7162:	learn: 0.0013727	total: 12m 56s	remaining: 5m 7s
7524:	learn: 0.0018286	total: 12m 56s	remaining: 4m 15s
7880:	learn: 0.0014432	total: 12m 56s	remaining: 3m 28s
7741:	learn: 0.0014227	total: 12m 56s	remaining: 3m 46s
7747:	learn: 0.0015102	total: 12m 56s	remaining: 3m 45s
7163:	learn: 0.0013727	total: 12m 56s	remaining: 5m 7s
7525:	learn: 0.0018281	total: 12m 56s	remaining: 4m 15s
7881:	learn: 0.0014432	total: 12m 56s	remaining: 3m 28s
7748:	learn: 0.0015102	total: 12m 56s	remaining: 3m 45s
7164:	learn: 0.0013727	total: 12m 56s	remaining: 5m 7s
7742:	learn: 0.0014227	total: 12m 56s	remaining: 3m 46s
7882:	learn: 0.0014432	total: 12m 56s	remaining: 3m 28s
7526:	learn: 0.0018272	total: 12m 56s	remaining: 4m 15s
7743:	learn: 0.0014227	total: 12m 56s	remaining: 3m 46s
7749:	learn: 0.0015102	total: 12m 56s	remaining: 3m 45s
7165:	learn: 0.0013724	total: 12m 56s	remaining: 5m 7s
7883:	learn: 0.0014432	total: 12m 56s	remaining: 3m 28s
7527:	learn: 0.0018267	total: 12m 57s	remaining: 4m 15s
7744:	learn: 0.0014227	total: 12m 56s	remaining: 3m 46s
7750:	learn: 0.0015102	total: 12m 56s	remaining: 3m 45s
7166:	learn: 0.0013724	total: 12m 57s	remaining: 5m 7s
7884:	learn: 0.0014432	total: 12m 56s	remaining: 3m 28s
7528:	learn: 0.0018263	total: 12m 57s	remaining: 4m 15s
7751:	learn: 0.0015102	total: 12m 56s	remaining: 3m 45s
7745:	learn: 0.0014223	total: 12m 57s	remaining: 3m 46s
7885:	learn: 0.0014432	total: 12m 56s	remaining: 3m 28s
7167:	learn: 0.0013724	total: 12m 57s	remaining: 5m 7s
7529:	learn: 0.0018255	total: 12m 57s	remaining: 4m 14s
7746:	learn: 0.0014223	total: 12m 57s	remaining: 3m 46s
7752:	learn: 0.0015102	total: 12m 56s	remaining: 3m 45s
7168:	learn: 0.0013724	total: 12m 57s	remaining: 5m 6s
7886:	learn: 0.0014432	total: 12m 57s	remaining: 3m 28s
7747:	learn: 0.0014220	total: 12m 57s	remaining: 3m 45s
7530:	learn: 0.0018249	total: 12m 57s	remaining: 4m 14s
7887:	learn: 0.0014432	total: 12m 57s	remaining: 3m 28s
7169:	learn: 0.0013724	total: 12m 57s	remaining: 5m 6s
7753:	learn: 0.0015102	total: 12m 57s	remaining: 3m 45s
7748:	learn: 0.0014220	total: 12m 57s	remaining: 3m 45s
7754:	learn: 0.0015102	total: 12m 57s	remaining: 3m 44s
7888:	learn: 0.0014432	total: 12m 57s	remaining: 3m 27s
7531:	learn: 0.0018239	total: 12m 57s	remaining: 4m 14s
7170:	learn: 0.0013724	total: 12m 57s	remaining: 5m 6s
7749:	learn: 0.0014220	total: 12m 57s	remaining: 3m 45s
7889:	learn: 0.0014432	total: 12m 57s	remaining: 3m 27s
7755:	learn: 0.0015102	total: 12m 57s	remaining: 3m 44s
7532:	learn: 0.0018236	total: 12m 57s	remaining: 4m 14s
7750:	learn: 0.0014220	total: 12m 57s	remaining: 3m 45s
7171:	learn: 0.0013724	total: 12m 57s	remaining: 5m 6s
7890:	learn: 0.0014432	total: 12m 57s	remaining: 3m 27s
7756:	learn: 0.0015102	total: 12m 57s	remaining: 3m 44s
7533:	learn: 0.0018233	total: 12m 57s	remaining: 4m 14s
7751:	learn: 0.0014220	total: 12m 57s	remaining: 3m 45s
7891:	learn: 0.0014432	total: 12m 57s	remaining: 3m 27s
7172:	learn: 0.0013724	total: 12m 57s	remaining: 5m 6s
7752:	learn: 0.0014220	total: 12m 57s	remaining: 3m 45s
7534:	learn: 0.0018233	total: 12m 57s	remaining: 4m 14s
7757:	learn: 0.0015102	total: 12m 57s	remaining: 3m 44s
7892:	learn: 0.0014432	total: 12m 57s	remaining: 3m 27s
7173:	learn: 0.0013724	total: 12m 57s	remaining: 5m 6s
7758:	learn: 0.0015102	total: 12m 57s	remaining: 3m 44s
7753:	learn: 0.0014220	total: 12m 57s	remaining: 3m 45s
7535:	learn: 0.0018233	total: 12m 57s	remaining: 4m 14s
7893:	learn: 0.0014432	total: 12m 57s	remaining: 3m 27s
7174:	learn: 0.0013720	total: 12m 57s	remaining: 5m 6s
7754:	learn: 0.0014220	total: 12m 57s	remaining: 3m 45s
7759:	learn: 0.0015102	total: 12m 57s	remaining: 3m 44s
7894:	learn: 0.0014432	total: 12m 57s	remaining: 3m 27s
7536:	learn: 0.0018224	total: 12m 57s	remaining: 4m 14s
7175:	learn: 0.0013720	total: 12m 57s	remaining: 5m 6s
7755:	learn: 0.0014219	total: 12m 58s	remaining: 3m 45s
7760:	learn: 0.0015102	total: 12m 57s	remaining: 3m 44s
7537:	learn: 0.0018220	total: 12m 58s	remaining: 4m 14s
7895:	learn: 0.0014432	total: 12m 57s	remaining: 3m 27s
7176:	learn: 0.0013720	total: 12m 58s	remaining: 5m 6s
7761:	learn: 0.0015102	total: 12m 57s	remaining: 3m 44s
7756:	learn: 0.0014220	total: 12m 58s	remaining: 3m 45s
7538:	learn: 0.0018216	total: 12m 58s	remaining: 4m 14s
7177:	learn: 0.0013720	total: 12m 58s	remaining: 5m 5s
7896:	learn: 0.0014432	total: 12m 58s	remaining: 3m 27s
7762:	learn: 0.0015102	total: 12m 57s	remaining: 3m 44s
7757:	learn: 0.0014220	total: 12m 58s	remaining: 3m 44s
7539:	learn: 0.0018216	total: 12m 58s	remaining: 4m 13s
7897:	learn: 0.0014432	total: 12m 58s	remaining: 3m 27s
7178:	learn: 0.0013719	total: 12m 58s	remaining: 5m 5s
7763:	learn: 0.0015102	total: 12m 58s	remaining: 3m 44s
7540:	learn: 0.0018216	total: 12m 58s	remaining: 4m 13s
7758:	learn: 0.0014220	total: 12m 58s	remaining: 3m 44s
7898:	learn: 0.0014432	total: 12m 58s	remaining: 3m 26s
7179:	learn: 0.0013719	total: 12m 58s	remaining: 5m 5s
7764:	learn: 0.0015102	total: 12m 58s	remaining: 3m 43s
7541:	learn: 0.0018208	total: 12m 58s	remaining: 4m 13s
7759:	learn: 0.0014220	total: 12m 58s	remaining: 3m 44s
7899:	learn: 0.0014432	total: 12m 58s	remaining: 3m 26s
7542:	learn: 0.0018204	total: 12m 58s	remaining: 4m 13s
7760:	learn: 0.0014220	total: 12m 58s	remaining: 3m 44s
7180:	learn: 0.0013719	total: 12m 58s	remaining: 5m 5s
7765:	learn: 0.0015102	total: 12m 58s	remaining: 3m 43s
7900:	learn: 0.0014432	total: 12m 58s	remaining: 3m 26s
7543:	learn: 0.0018195	total: 12m 58s	remaining: 4m 13s
7761:	learn: 0.0014220	total: 12m 58s	remaining: 3m 44s
7766:	learn: 0.0015102	total: 12m 58s	remaining: 3m 43s
7181:	learn: 0.0013719	total: 12m 58s	remaining: 5m 5s
7901:	learn: 0.0014432	total: 12m 58s	remaining: 3m 26s
7767:	learn: 0.0015102	total: 12m 58s	remaining: 3m 43s
7544:	learn: 0.0018192	total: 12m 58s	remaining: 4m 13s
7762:	learn: 0.0014220	total: 12m 58s	remaining: 3m 44s
7902:	learn: 0.0014432	total: 12m 58s	remaining: 3m 26s
7182:	learn: 0.0013719	total: 12m 58s	remaining: 5m 5s
7768:	learn: 0.0015102	total: 12m 58s	remaining: 3m 43s
7763:	learn: 0.0014220	total: 12m 58s	remaining: 3m 44s
7903:	learn: 0.0014432	total: 12m 58s	remaining: 3m 26s
7545:	learn: 0.0018188	total: 12m 58s	remaining: 4m 13s
7183:	learn: 0.0013719	total: 12m 58s	remaining: 5m 5s
7769:	learn: 0.0015102	total: 12m 58s	remaining: 3m 43s
7904:	learn: 0.0014432	total: 12m 58s	remaining: 3m 26s
7764:	learn: 0.0014220	total: 12m 58s	remaining: 3m 44s
7546:	learn: 0.0018185	total: 12m 58s	remaining: 4m 13s
7770:	learn: 0.0015101	total: 12m 58s	remaining: 3m 43s
7184:	learn: 0.0013719	total: 12m 58s	remaining: 5m 5s
7765:	learn: 0.0014219	total: 12m 59s	remaining: 3m 44s
7905:	learn: 0.0014432	total: 12m 58s	remaining: 3m 26s
7547:	learn: 0.0018180	total: 12m 59s	remaining: 4m 13s
7771:	learn: 0.0015101	total: 12m 58s	remaining: 3m 43s
7906:	learn: 0.0014432	total: 12m 58s	remaining: 3m 26s
7185:	learn: 0.0013719	total: 12m 59s	remaining: 5m 5s
7766:	learn: 0.0014219	total: 12m 59s	remaining: 3m 43s
7548:	learn: 0.0018180	total: 12m 59s	remaining: 4m 12s
7907:	learn: 0.0014432	total: 12m 59s	remaining: 3m 26s
7772:	learn: 0.0015101	total: 12m 58s	remaining: 3m 43s
7186:	learn: 0.0013719	total: 12m 59s	remaining: 5m 4s
7767:	learn: 0.0014219	total: 12m 59s	remaining: 3m 43s
7549:	learn: 0.0018178	total: 12m 59s	remaining: 4m 12s
7908:	learn: 0.0014432	total: 12m 59s	remaining: 3m 25s
7187:	learn: 0.0013719	total: 12m 59s	remaining: 5m 4s
7773:	learn: 0.0015101	total: 12m 59s	remaining: 3m 43s
7550:	learn: 0.0018175	total: 12m 59s	remaining: 4m 12s
7768:	learn: 0.0014219	total: 12m 59s	remaining: 3m 43s
7909:	learn: 0.0014432	total: 12m 59s	remaining: 3m 25s
7551:	learn: 0.0018167	total: 12m 59s	remaining: 4m 12s
7188:	learn: 0.0013719	total: 12m 59s	remaining: 5m 4s
7774:	learn: 0.0015096	total: 12m 59s	remaining: 3m 42s
7769:	learn: 0.0014219	total: 12m 59s	remaining: 3m 43s
7552:	learn: 0.0018162	total: 12m 59s	remaining: 4m 12s
7910:	learn: 0.0014432	total: 12m 59s	remaining: 3m 25s
7775:	learn: 0.0015096	total: 12m 59s	remaining: 3m 42s
7189:	learn: 0.0013719	total: 12m 59s	remaining: 5m 4s
7770:	learn: 0.0014220	total: 12m 59s	remaining: 3m 43s

7553:	learn: 0.0018158	total: 12m 59s	remaining: 4m 12s
7911:	learn: 0.0014432	total: 12m 59s	remaining: 3m 25s
7776:	learn: 0.0015096	total: 12m 59s	remaining: 3m 42s
7190:	learn: 0.0013719	total: 12m 59s	remaining: 5m 4s
7771:	learn: 0.0014220	total: 12m 59s	remaining: 3m 43s
7554:	learn: 0.0018158	total: 12m 59s	remaining: 4m 12s
7912:	learn: 0.0014432	total: 12m 59s	remaining: 3m 25s
7777:	learn: 0.0015096	total: 12m 59s	remaining: 3m 42s
7191:	learn: 0.0013719	total: 12m 59s	remaining: 5m 4s
7555:	learn: 0.0018155	total: 12m 59s	remaining: 4m 12s
7772:	learn: 0.0014219	total: 12m 59s	remaining: 3m 43s
7778:	learn: 0.0015096	total: 12m 59s	remaining: 3m 42s
7913:	learn: 0.0014432	total: 12m 59s	remaining: 3m 25s
7192:	learn: 0.0013719	total: 12m 59s	remaining: 5m 4s
7556:	learn: 0.0018151	total: 12m 59s	remaining: 4m 12s
7773:	learn: 0.0014219	total: 12m 59s	remaining: 3m 43s
7779:	learn: 0.0015096	total: 12m 59s	remaining: 3m 42s
7914:	learn: 0.0014432	total: 12m 59s	remaining: 3m 25s
7193:	learn: 0.0013719	total: 12m 59s	remaining: 5m 4s
7780:	learn: 0.0015096	total: 12m 59s	remaining: 3m 42s
7557:	learn: 0.0018142	total: 13m	remaining: 4m 12s
7774:	learn: 0.0014220	total: 12m 59s	remaining: 3m 43s
7915:	learn: 0.0014432	total: 12m 59s	remaining: 3m 25s
7194:	learn: 0.0013719	total: 13m	remaining: 5m 4s
7781:	learn: 0.0015096	total: 12m 59s	remaining: 3m 42s
7558:	learn: 0.0018139	total: 13m	remaining: 4m 11s
7775:	learn: 0.0014219	total: 13m	remaining: 3m 43s
7916:	learn: 0.0014432	total: 12m 59s	remaining: 3m 25s
7782:	learn: 0.0015096	total: 12m 59s	remaining: 3m 42s
7195:	learn: 0.0013719	total: 13m	remaining: 5m 3s
7559:	learn: 0.0018139	total: 13m	remaining: 4m 11s
7776:	learn: 0.0014220	total: 13m	remaining: 3m 43s
7917:	learn: 0.0014432	total: 13m	remaining: 3m 25s
7783:	learn: 0.0015096	total: 12m 59s	remaining: 3m 42s
7560:	learn: 0.0018130	total: 13m	remaining: 4m 11s
7196:	learn: 0.0013719	total: 13m	remaining: 5m 3s
7777:	learn: 0.0014219	total: 13m	remaining: 3m 42s
7918:	learn: 0.0014432	total: 13m	remaining: 3m 25s
7784:	learn: 0.0015096	total: 13m	remaining: 3m 41s
7919:	learn: 0.0014432	total: 13m	remaining: 3m 24s
7778:	learn: 0.0014219	total: 13m	remaining: 3m 42s
7197:	learn: 0.0013719	total: 13m	remaining: 5m 3s
7561:	learn: 0.0018128	total: 13m	remaining: 4m 11s
7785:	learn: 0.0015097	total: 13m	remaining: 3m 41s
7920:	learn: 0.0014432	total: 13m	remaining: 3m 24s
7198:	learn: 0.0013719	total: 13m	remaining: 5m 3s
7779:	learn: 0.0014219	total: 13m	remaining: 3m 42s
7786:	learn: 0.0015093	total: 13m	remaining: 3m 41s
7921:	learn: 0.0014432	total: 13m	remaining: 3m 24s
7562:	learn: 0.0018125	total: 13m	remaining: 4m 11s
7199:	learn: 0.0013719	total: 13m	remaining: 5m 3s
7780:	learn: 0.0014219	total: 13m	remaining: 3m 42s
7922:	learn: 0.0014431	total: 13m	remaining: 3m 24s
7787:	learn: 0.0015093	total: 13m	remaining: 3m 41s
7563:	learn: 0.0018116	total: 13m	remaining: 4m 11s
7200:	learn: 0.0013719	total: 13m	remaining: 5m 3s
7788:	learn: 0.0015090	total: 13m	remaining: 3m 41s
7781:	learn: 0.0014219	total: 13m	remaining: 3m 42s
7923:	learn: 0.0014431	total: 13m	remaining: 3m 24s
7564:	learn: 0.0018111	total: 13m	remaining: 4m 11s
7201:	learn: 0.0013719	total: 13m	remaining: 5m 3s
7789:	learn: 0.0015089	total: 13m	remaining: 3m 41s
7782:	learn: 0.0014219	total: 13m	remaining: 3m 42s
7924:	learn: 0.0014431	total: 13m	remaining: 3m 24s
7790:	learn: 0.0015089	total: 13m	remaining: 3m 41s
7202:	learn: 0.0013719	total: 13m	remaining: 5m 3s
7565:	learn: 0.0018107	total: 13m	remaining: 4m 11s
7925:	learn: 0.0014431	total: 13m	remaining: 3m 24s
7783:	learn: 0.0014219	total: 13m	remaining: 3m 42s
7203:	learn: 0.0013719	total: 13m	remaining: 5m 3s
7791:	learn: 0.0015089	total: 13m	remaining: 3m 41s
7566:	learn: 0.0018101	total: 13m 1s	remaining: 4m 11s
7926:	learn: 0.0014431	total: 13m	remaining: 3m 24s
7784:	learn: 0.0014219	total: 13m 1s	remaining: 3m 42s
7204:	learn: 0.0013715	total: 13m 1s	remaining: 5m 2s
7792:	learn: 0.0015089	total: 13m	remaining: 3m 41s
7567:	learn: 0.0018096	total: 13m 1s	remaining: 4m 11s
7927:	learn: 0.0014427	total: 13m	remaining: 3m 24s
7785:	learn: 0.0014219	total: 13m 1s	remaining: 3m 42s
7793:	learn: 0.0015089	total: 13m	remaining: 3m 41s
7205:	learn: 0.0013715	total: 13m 1s	remaining: 5m 2s
7568:	learn: 0.0018093	total: 13m 1s	remaining: 4m 10s
7928:	learn: 0.0014427	total: 13m 1s	remaining: 3m 24s
7786:	learn: 0.0014219	total: 13m 1s	remaining: 3m 42s
7794:	learn: 0.0015089	total: 13m 1s	remaining: 3m 40s
7569:	learn: 0.0018085	total: 13m 1s	remaining: 4m 10s
7206:	learn: 0.0013716	total: 13m 1s	remaining: 5m 2s
7787:	learn: 0.0014219	total: 13m 1s	remaining: 3m 41s
7929:	learn: 0.0014421	total: 13m 1s	remaining: 3m 23s
7795:	learn: 0.0015090	total: 13m 1s	remaining: 3m 40s
7207:	learn: 0.0013715	total: 13m 1s	remaining: 5m 2s
7570:	learn: 0.0018077	total: 13m 1s	remaining: 4m 10s
7788:	learn: 0.0014215	total: 13m 1s	remaining: 3m 41s
7930:	learn: 0.0014421	total: 13m 1s	remaining: 3m 23s
7796:	learn: 0.0015089	total: 13m 1s	remaining: 3m 40s
7208:	learn: 0.0013715	total: 13m 1s	remaining: 5m 2s
7571:	learn: 0.0018070	total: 13m 1s	remaining: 4m 10s
7931:	learn: 0.0014421	total: 13m 1s	remaining: 3m 23s
7789:	learn: 0.0014214	total: 13m 1s	remaining: 3m 41s
7209:	learn: 0.0013716	total: 13m 1s	remaining: 5m 2s
7797:	learn: 0.0015089	total: 13m 1s	remaining: 3m 40s
7572:	learn: 0.0018065	total: 13m 1s	remaining: 4m 10s
7790:	learn: 0.0014214	total: 13m 1s	remaining: 3m 41s
7932:	learn: 0.0014421	total: 13m 1s	remaining: 3m 23s
7210:	learn: 0.0013715	total: 13m 1s	remaining: 5m 2s
7798:	learn: 0.0015089	total: 13m 1s	remaining: 3m 40s
7933:	learn: 0.0014421	total: 13m 1s	remaining: 3m 23s
7573:	learn: 0.0018065	total: 13m 1s	remaining: 4m 10s
7791:	learn: 0.0014209	total: 13m 1s	remaining: 3m 41s
7211:	learn: 0.0013715	total: 13m 1s	remaining: 5m 2s
7792:	learn: 0.0014206	total: 13m 1s	remaining: 3m 41s
7574:	learn: 0.0018065	total: 13m 1s	remaining: 4m 10s
7212:	learn: 0.0013716	total: 13m 1s	remaining: 5m 2s
7799:	learn: 0.0015090	total: 13m 1s	remaining: 3m 40s
7934:	learn: 0.0014421	total: 13m 1s	remaining: 3m 23s
7793:	learn: 0.0014202	total: 13m 1s	remaining: 3m 41s
7575:	learn: 0.0018061	total: 13m 1s	remaining: 4m 10s
7213:	learn: 0.0013716	total: 13m 1s	remaining: 5m 1s
7800:	learn: 0.0015086	total: 13m 1s	remaining: 3m 40s
7935:	learn: 0.0014421	total: 13m 1s	remaining: 3m 23s
7576:	learn: 0.0018056	total: 13m 2s	remaining: 4m 10s
7794:	learn: 0.0014202	total: 13m 1s	remaining: 3m 41s
7214:	learn: 0.0013716	total: 13m 2s	remaining: 5m 1s
7936:	learn: 0.0014421	total: 13m 1s	remaining: 3m 23s
7801:	learn: 0.0015086	total: 13m 1s	remaining: 3m 40s
7795:	learn: 0.0014202	total: 13m 2s	remaining: 3m 41s
7577:	learn: 0.0018051	total: 13m 2s	remaining: 4m 9s
7802:	learn: 0.0015086	total: 13m 1s	remaining: 3m 40s
7937:	learn: 0.0014421	total: 13m 2s	remaining: 3m 23s
7215:	learn: 0.0013715	total: 13m 2s	remaining: 5m 1s
7796:	learn: 0.0014202	total: 13m 2s	remaining: 3m 41s
7578:	learn: 0.0018046	total: 13m 2s	remaining: 4m 9s
7803:	learn: 0.0015086	total: 13m 1s	remaining: 3m 40s
7938:	learn: 0.0014421	total: 13m 2s	remaining: 3m 23s
7216:	learn: 0.0013715	total: 13m 2s	remaining: 5m 1s
7797:	learn: 0.0014202	total: 13m 2s	remaining: 3m 40s
7579:	learn: 0.0018046	total: 13m 2s	remaining: 4m 9s
7804:	learn: 0.0015082	total: 13m 2s	remaining: 3m 39s
7939:	learn: 0.0014421	total: 13m 2s	remaining: 3m 22s
7217:	learn: 0.0013715	total: 13m 2s	remaining: 5m 1s
7798:	learn: 0.0014202	total: 13m 2s	remaining: 3m 40s
7805:	learn: 0.0015079	total: 13m 2s	remaining: 3m 39s
7580:	learn: 0.0018042	total: 13m 2s	remaining: 4m 9s
7940:	learn: 0.0014421	total: 13m 2s	remaining: 3m 22s
7218:	learn: 0.0013715	total: 13m 2s	remaining: 5m 1s
7799:	learn: 0.0014202	total: 13m 2s	remaining: 3m 40s
7581:	learn: 0.0018039	total: 13m 2s	remaining: 4m 9s
7806:	learn: 0.0015079	total: 13m 2s	remaining: 3m 39s
7941:	learn: 0.0014421	total: 13m 2s	remaining: 3m 22s
7582:	learn: 0.0018039	total: 13m 2s	remaining: 4m 9s
7800:	learn: 0.0014202	total: 13m 2s	remaining: 3m 40s
7219:	learn: 0.0013715	total: 13m 2s	remaining: 5m 1s
7807:	learn: 0.0015079	total: 13m 2s	remaining: 3m 39s
7942:	learn: 0.0014421	total: 13m 2s	remaining: 3m 22s
7801:	learn: 0.0014202	total: 13m 2s	remaining: 3m 40s
7220:	learn: 0.0013715	total: 13m 2s	remaining: 5m 1s
7583:	learn: 0.0018039	total: 13m 2s	remaining: 4m 9s
7808:	learn: 0.0015079	total: 13m 2s	remaining: 3m 39s
7802:	learn: 0.0014202	total: 13m 2s	remaining: 3m 40s
7943:	learn: 0.0014421	total: 13m 2s	remaining: 3m 22s
7221:	learn: 0.0013715	total: 13m 2s	remaining: 5m 1s
7584:	learn: 0.0018036	total: 13m 2s	remaining: 4m 9s
7803:	learn: 0.0014202	total: 13m 2s	remaining: 3m 40s
7809:	learn: 0.0015079	total: 13m 2s	remaining: 3m 39s
7222:	learn: 0.0013715	total: 13m 2s	remaining: 5m
7944:	learn: 0.0014421	total: 13m 2s	remaining: 3m 22s
7804:	learn: 0.0014198	total: 13m 2s	remaining: 3m 40s
7585:	learn: 0.0018036	total: 13m 2s	remaining: 4m 9s
7810:	learn: 0.0015077	total: 13m 2s	remaining: 3m 39s
7945:	learn: 0.0014421	total: 13m 2s	remaining: 3m 22s
7223:	learn: 0.0013715	total: 13m 2s	remaining: 5m
7805:	learn: 0.0014193	total: 13m 2s	remaining: 3m 40s
7586:	learn: 0.0018036	total: 13m 3s	remaining: 4m 9s
7811:	learn: 0.0015077	total: 13m 2s	remaining: 3m 39s
7224:	learn: 0.0013715	total: 13m 3s	remaining: 5m
7946:	learn: 0.0014421	total: 13m 2s	remaining: 3m 22s
7587:	learn: 0.0018036	total: 13m 3s	remaining: 4m 8s
7806:	learn: 0.0014193	total: 13m 3s	remaining: 3m 39s
7812:	learn: 0.0015077	total: 13m 2s	remaining: 3m 39s
7588:	learn: 0.0018032	total: 13m 3s	remaining: 4m 8s
7225:	learn: 0.0013715	total: 13m 3s	remaining: 5m
7947:	learn: 0.0014417	total: 13m 3s	remaining: 3m 22s
7807:	learn: 0.0014193	total: 13m 3s	remaining: 3m 39s
7813:	learn: 0.0015077	total: 13m 3s	remaining: 3m 39s
7589:	learn: 0.0018030	total: 13m 3s	remaining: 4m 8s
7226:	learn: 0.0013715	total: 13m 3s	remaining: 5m
7948:	learn: 0.0014417	total: 13m 3s	remaining: 3m 22s
7808:	learn: 0.0014193	total: 13m 3s	remaining: 3m 39s
7814:	learn: 0.0015077	total: 13m 3s	remaining: 3m 38s
7590:	learn: 0.0018024	total: 13m 3s	remaining: 4m 8s
7809:	learn: 0.0014193	total: 13m 3s	remaining: 3m 39s
7227:	learn: 0.0013715	total: 13m 3s	remaining: 5m
7949:	learn: 0.0014417	total: 13m 3s	remaining: 3m 21s
7815:	learn: 0.0015077	total: 13m 3s	remaining: 3m 38s
7950:	learn: 0.0014417	total: 13m 3s	remaining: 3m 21s
7591:	learn: 0.0018024	total: 13m 3s	remaining: 4m 8s
7810:	learn: 0.0014189	total: 13m 3s	remaining: 3m 39s
7816:	learn: 0.0015077	total: 13m 3s	remaining: 3m 38s
7228:	learn: 0.0013715	total: 13m 3s	remaining: 5m
7951:	learn: 0.0014417	total: 13m 3s	remaining: 3m 21s
7811:	learn: 0.0014185	total: 13m 3s	remaining: 3m 39s
7592:	learn: 0.0018022	total: 13m 3s	remaining: 4m 8s
7817:	learn: 0.0015077	total: 13m 3s	remaining: 3m 38s
7812:	learn: 0.0014181	total: 13m 3s	remaining: 3m 39s
7952:	learn: 0.0014417	total: 13m 3s	remaining: 3m 21s
7229:	learn: 0.0013715	total: 13m 3s	remaining: 5m
7593:	learn: 0.0018018	total: 13m 3s	remaining: 4m 8s
7818:	learn: 0.0015077	total: 13m 3s	remaining: 3m 38s
7813:	learn: 0.0014177	total: 13m 3s	remaining: 3m 39s
7953:	learn: 0.0014417	total: 13m 3s	remaining: 3m 21s
7230:	learn: 0.0013715	total: 13m 3s	remaining: 5m
7819:	learn: 0.0015077	total: 13m 3s	remaining: 3m 38s
7594:	learn: 0.0018018	total: 13m 3s	remaining: 4m 8s
7954:	learn: 0.0014417	total: 13m 3s	remaining: 3m 21s
7814:	learn: 0.0014177	total: 13m 3s	remaining: 3m 39s
7231:	learn: 0.0013715	total: 13m 3s	remaining: 5m
7595:	learn: 0.0018018	total: 13m 3s	remaining: 4m 8s
7820:	learn: 0.0015077	total: 13m 3s	remaining: 3m 38s
7815:	learn: 0.0014177	total: 13m 3s	remaining: 3m 39s
7955:	learn: 0.0014417	total: 13m 3s	remaining: 3m 21s
7232:	learn: 0.0013715	total: 13m 3s	remaining: 4m 59s
7596:	learn: 0.0018018	total: 13m 4s	remaining: 4m 8s
7821:	learn: 0.0015077	total: 13m 3s	remaining: 3m 38s
7816:	learn: 0.0014177	total: 13m 4s	remaining: 3m 38s
7956:	learn: 0.0014417	total: 13m 3s	remaining: 3m 21s
7233:	learn: 0.0013715	total: 13m 4s	remaining: 4m 59s
7822:	learn: 0.0015074	total: 13m 3s	remaining: 3m 38s
7597:	learn: 0.0018012	total: 13m 4s	remaining: 4m 7s
7817:	learn: 0.0014177	total: 13m 4s	remaining: 3m 38s
7957:	learn: 0.0014417	total: 13m 4s	remaining: 3m 21s
7234:	learn: 0.0013715	total: 13m 4s	remaining: 4m 59s
7823:	learn: 0.0015069	total: 13m 3s	remaining: 3m 38s
7598:	learn: 0.0018008	total: 13m 4s	remaining: 4m 7s
7818:	learn: 0.0014177	total: 13m 4s	remaining: 3m 38s
7958:	learn: 0.0014417	total: 13m 4s	remaining: 3m 21s
7235:	learn: 0.0013715	total: 13m 4s	remaining: 4m 59s
7824:	learn: 0.0015069	total: 13m 4s	remaining: 3m 37s
7599:	learn: 0.0018006	total: 13m 4s	remaining: 4m 7s
7819:	learn: 0.0014177	total: 13m 4s	remaining: 3m 38s
7959:	learn: 0.0014417	total: 13m 4s	remaining: 3m 20s
7236:	learn: 0.0013715	total: 13m 4s	remaining: 4m 59s
7600:	learn: 0.0018002	total: 13m 4s	remaining: 4m 7s
7825:	learn: 0.0015068	total: 13m 4s	remaining: 3m 37s
7820:	learn: 0.0014177	total: 13m 4s	remaining: 3m 38s
7960:	learn: 0.0014417	total: 13m 4s	remaining: 3m 20s
7601:	learn: 0.0017999	total: 13m 4s	remaining: 4m 7s
7826:	learn: 0.0015068	total: 13m 4s	remaining: 3m 37s
7237:	learn: 0.0013715	total: 13m 4s	remaining: 4m 59s
7821:	learn: 0.0014177	total: 13m 4s	remaining: 3m 38s
7961:	learn: 0.0014417	total: 13m 4s	remaining: 3m 20s
7602:	learn: 0.0017993	total: 13m 4s	remaining: 4m 7s
7827:	learn: 0.0015068	total: 13m 4s	remaining: 3m 37s
7238:	learn: 0.0013715	total: 13m 4s	remaining: 4m 59s
7822:	learn: 0.0014177	total: 13m 4s	remaining: 3m 38s
7962:	learn: 0.0014417	total: 13m 4s	remaining: 3m 20s
7603:	learn: 0.0017990	total: 13m 4s	remaining: 4m 7s
7828:	learn: 0.0015069	total: 13m 4s	remaining: 3m 37s
7239:	learn: 0.0013715	total: 13m 4s	remaining: 4m 59s
7963:	learn: 0.0014417	total: 13m 4s	remaining: 3m 20s
7823:	learn: 0.0014177	total: 13m 4s	remaining: 3m 38s
7829:	learn: 0.0015068	total: 13m 4s	remaining: 3m 37s
7964:	learn: 0.0014417	total: 13m 4s	remaining: 3m 20s
7604:	learn: 0.0017988	total: 13m 4s	remaining: 4m 7s
7240:	learn: 0.0013715	total: 13m 4s	remaining: 4m 59s
7824:	learn: 0.0014177	total: 13m 4s	remaining: 3m 38s
7830:	learn: 0.0015068	total: 13m 4s	remaining: 3m 37s
7965:	learn: 0.0014417	total: 13m 4s	remaining: 3m 20s
7605:	learn: 0.0017986	total: 13m 4s	remaining: 4m 7s
7241:	learn: 0.0013713	total: 13m 4s	remaining: 4m 58s
7825:	learn: 0.0014177	total: 13m 4s	remaining: 3m 38s
7966:	learn: 0.0014417	total: 13m 4s	remaining: 3m 20s
7831:	learn: 0.0015068	total: 13m 4s	remaining: 3m 37s
7826:	learn: 0.0014177	total: 13m 5s	remaining: 3m 37s
7967:	learn: 0.0014417	total: 13m 4s	remaining: 3m 20s
7606:	learn: 0.0017982	total: 13m 5s	remaining: 4m 6s
7242:	learn: 0.0013713	total: 13m 5s	remaining: 4m 58s
7832:	learn: 0.0015069	total: 13m 4s	remaining: 3m 37s
7827:	learn: 0.0014174	total: 13m 5s	remaining: 3m 37s
7607:	learn: 0.0017979	total: 13m 5s	remaining: 4m 6s
7968:	learn: 0.0014413	total: 13m 5s	remaining: 3m 20s
7243:	learn: 0.0013710	total: 13m 5s	remaining: 4m 58s
7833:	learn: 0.0015065	total: 13m 5s	remaining: 3m 37s
7828:	learn: 0.0014170	total: 13m 5s	remaining: 3m 37s
7608:	learn: 0.0017975	total: 13m 5s	remaining: 4m 6s
7969:	learn: 0.0014409	total: 13m 5s	remaining: 3m 19s
7244:	learn: 0.0013710	total: 13m 5s	remaining: 4m 58s
7829:	learn: 0.0014170	total: 13m 5s	remaining: 3m 37s
7834:	learn: 0.0015065	total: 13m 5s	remaining: 3m 36s
7970:	learn: 0.0014409	total: 13m 5s	remaining: 3m 19s
7609:	learn: 0.0017968	total: 13m 5s	remaining: 4m 6s
7830:	learn: 0.0014170	total: 13m 5s	remaining: 3m 37s
7245:	learn: 0.0013710	total: 13m 5s	remaining: 4m 58s
7971:	learn: 0.0014409	total: 13m 5s	remaining: 3m 19s
7835:	learn: 0.0015065	total: 13m 5s	remaining: 3m 36s
7610:	learn: 0.0017963	total: 13m 5s	remaining: 4m 6s
7831:	learn: 0.0014170	total: 13m 5s	remaining: 3m 37s
7246:	learn: 0.0013710	total: 13m 5s	remaining: 4m 58s
7972:	learn: 0.0014409	total: 13m 5s	remaining: 3m 19s
7611:	learn: 0.0017958	total: 13m 5s	remaining: 4m 6s
7832:	learn: 0.0014170	total: 13m 5s	remaining: 3m 37s
7836:	learn: 0.0015062	total: 13m 5s	remaining: 3m 36s

7247:	learn: 0.0013710	total: 13m 5s	remaining: 4m 58s
7973:	learn: 0.0014409	total: 13m 5s	remaining: 3m 19s
7612:	learn: 0.0017953	total: 13m 5s	remaining: 4m 6s
7833:	learn: 0.0014169	total: 13m 5s	remaining: 3m 37s
7974:	learn: 0.0014409	total: 13m 5s	remaining: 3m 19s
7837:	learn: 0.0015062	total: 13m 5s	remaining: 3m 36s
7834:	learn: 0.0014169	total: 13m 5s	remaining: 3m 37s
7248:	learn: 0.0013709	total: 13m 5s	remaining: 4m 58s
7613:	learn: 0.0017953	total: 13m 5s	remaining: 4m 6s
7838:	learn: 0.0015062	total: 13m 5s	remaining: 3m 36s
7975:	learn: 0.0014409	total: 13m 5s	remaining: 3m 19s
7249:	learn: 0.0013709	total: 13m 5s	remaining: 4m 58s
7835:	learn: 0.0014169	total: 13m 5s	remaining: 3m 37s
7250:	learn: 0.0013709	total: 13m 5s	remaining: 4m 57s
7614:	learn: 0.0017947	total: 13m 5s	remaining: 4m 6s
7839:	learn: 0.0015062	total: 13m 5s	remaining: 3m 36s
7976:	learn: 0.0014409	total: 13m 5s	remaining: 3m 19s
7836:	learn: 0.0014169	total: 13m 5s	remaining: 3m 36s
7251:	learn: 0.0013710	total: 13m 5s	remaining: 4m 57s
7977:	learn: 0.0014409	total: 13m 5s	remaining: 3m 19s
7615:	learn: 0.0017942	total: 13m 6s	remaining: 4m 6s
7840:	learn: 0.0015062	total: 13m 5s	remaining: 3m 36s
7837:	learn: 0.0014169	total: 13m 6s	remaining: 3m 36s
7252:	learn: 0.0013710	total: 13m 6s	remaining: 4m 57s
7978:	learn: 0.0014409	total: 13m 5s	remaining: 3m 19s
7616:	learn: 0.0017936	total: 13m 6s	remaining: 4m 5s
7838:	learn: 0.0014169	total: 13m 6s	remaining: 3m 36s
7841:	learn: 0.0015062	total: 13m 5s	remaining: 3m 36s
7253:	learn: 0.0013709	total: 13m 6s	remaining: 4m 57s
7617:	learn: 0.0017936	total: 13m 6s	remaining: 4m 5s
7979:	learn: 0.0014409	total: 13m 6s	remaining: 3m 18s
7839:	learn: 0.0014169	total: 13m 6s	remaining: 3m 36s
7254:	learn: 0.0013709	total: 13m 6s	remaining: 4m 57s
7980:	learn: 0.0014409	total: 13m 6s	remaining: 3m 18s
7842:	learn: 0.0015058	total: 13m 6s	remaining: 3m 36s
7618:	learn: 0.0017936	total: 13m 6s	remaining: 4m 5s
7843:	learn: 0.0015058	total: 13m 6s	remaining: 3m 36s
7840:	learn: 0.0014169	total: 13m 6s	remaining: 3m 36s
7981:	learn: 0.0014409	total: 13m 6s	remaining: 3m 18s
7255:	learn: 0.0013709	total: 13m 6s	remaining: 4m 57s
7619:	learn: 0.0017936	total: 13m 6s	remaining: 4m 5s
7841:	learn: 0.0014169	total: 13m 6s	remaining: 3m 36s
7256:	learn: 0.0013709	total: 13m 6s	remaining: 4m 57s
7982:	learn: 0.0014409	total: 13m 6s	remaining: 3m 18s
7844:	learn: 0.0015058	total: 13m 6s	remaining: 3m 35s
7620:	learn: 0.0017936	total: 13m 6s	remaining: 4m 5s
7842:	learn: 0.0014166	total: 13m 6s	remaining: 3m 36s
7257:	learn: 0.0013709	total: 13m 6s	remaining: 4m 57s
7843:	learn: 0.0014166	total: 13m 6s	remaining: 3m 36s
7983:	learn: 0.0014409	total: 13m 6s	remaining: 3m 18s
7621:	learn: 0.0017931	total: 13m 6s	remaining: 4m 5s
7845:	learn: 0.0015058	total: 13m 6s	remaining: 3m 35s
7984:	learn: 0.0014409	total: 13m 6s	remaining: 3m 18s
7844:	learn: 0.0014166	total: 13m 6s	remaining: 3m 36s
7258:	learn: 0.0013709	total: 13m 6s	remaining: 4m 57s
7622:	learn: 0.0017927	total: 13m 6s	remaining: 4m 5s
7846:	learn: 0.0015058	total: 13m 6s	remaining: 3m 35s
7985:	learn: 0.0014409	total: 13m 6s	remaining: 3m 18s
7845:	learn: 0.0014166	total: 13m 6s	remaining: 3m 35s
7847:	learn: 0.0015058	total: 13m 6s	remaining: 3m 35s
7259:	learn: 0.0013709	total: 13m 6s	remaining: 4m 56s
7623:	learn: 0.0017921	total: 13m 6s	remaining: 4m 5s
7986:	learn: 0.0014409	total: 13m 6s	remaining: 3m 18s
7846:	learn: 0.0014166	total: 13m 6s	remaining: 3m 35s
7624:	learn: 0.0017913	total: 13m 6s	remaining: 4m 5s
7260:	learn: 0.0013709	total: 13m 6s	remaining: 4m 56s
7848:	learn: 0.0015058	total: 13m 6s	remaining: 3m 35s
7987:	learn: 0.0014409	total: 13m 6s	remaining: 3m 18s
7847:	learn: 0.0014166	total: 13m 6s	remaining: 3m 35s
7625:	learn: 0.0017913	total: 13m 7s	remaining: 4m 5s
7261:	learn: 0.0013709	total: 13m 7s	remaining: 4m 56s
7988:	learn: 0.0014409	total: 13m 6s	remaining: 3m 18s
7849:	learn: 0.0015058	total: 13m 6s	remaining: 3m 35s
7848:	learn: 0.0014166	total: 13m 7s	remaining: 3m 35s
7626:	learn: 0.0017910	total: 13m 7s	remaining: 4m 4s
7262:	learn: 0.0013709	total: 13m 7s	remaining: 4m 56s
7989:	learn: 0.0014409	total: 13m 7s	remaining: 3m 17s
7627:	learn: 0.0017906	total: 13m 7s	remaining: 4m 4s
7849:	learn: 0.0014166	total: 13m 7s	remaining: 3m 35s
7850:	learn: 0.0015058	total: 13m 6s	remaining: 3m 35s
7263:	learn: 0.0013709	total: 13m 7s	remaining: 4m 56s
7851:	learn: 0.0015058	total: 13m 7s	remaining: 3m 35s
7990:	learn: 0.0014409	total: 13m 7s	remaining: 3m 17s
7850:	learn: 0.0014166	total: 13m 7s	remaining: 3m 35s
7628:	learn: 0.0017898	total: 13m 7s	remaining: 4m 4s
7264:	learn: 0.0013709	total: 13m 7s	remaining: 4m 56s
7852:	learn: 0.0015058	total: 13m 7s	remaining: 3m 35s
7991:	learn: 0.0014409	total: 13m 7s	remaining: 3m 17s
7851:	learn: 0.0014166	total: 13m 7s	remaining: 3m 35s
7629:	learn: 0.0017896	total: 13m 7s	remaining: 4m 4s
7853:	learn: 0.0015058	total: 13m 7s	remaining: 3m 35s
7265:	learn: 0.0013709	total: 13m 7s	remaining: 4m 56s
7992:	learn: 0.0014409	total: 13m 7s	remaining: 3m 17s
7852:	learn: 0.0014166	total: 13m 7s	remaining: 3m 35s
7630:	learn: 0.0017891	total: 13m 7s	remaining: 4m 4s
7854:	learn: 0.0015058	total: 13m 7s	remaining: 3m 34s
7266:	learn: 0.0013709	total: 13m 7s	remaining: 4m 56s
7993:	learn: 0.0014409	total: 13m 7s	remaining: 3m 17s
7853:	learn: 0.0014165	total: 13m 7s	remaining: 3m 35s
7994:	learn: 0.0014409	total: 13m 7s	remaining: 3m 17s
7631:	learn: 0.0017886	total: 13m 7s	remaining: 4m 4s
7855:	learn: 0.0015058	total: 13m 7s	remaining: 3m 34s
7267:	learn: 0.0013709	total: 13m 7s	remaining: 4m 56s
7854:	learn: 0.0014161	total: 13m 7s	remaining: 3m 35s
7995:	learn: 0.0014409	total: 13m 7s	remaining: 3m 17s
7632:	learn: 0.0017884	total: 13m 7s	remaining: 4m 4s
7855:	learn: 0.0014157	total: 13m 7s	remaining: 3m 34s
7856:	learn: 0.0015058	total: 13m 7s	remaining: 3m 34s
7268:	learn: 0.0013709	total: 13m 7s	remaining: 4m 55s
7996:	learn: 0.0014409	total: 13m 7s	remaining: 3m 17s
7633:	learn: 0.0017882	total: 13m 7s	remaining: 4m 4s
7857:	learn: 0.0015058	total: 13m 7s	remaining: 3m 34s
7856:	learn: 0.0014157	total: 13m 7s	remaining: 3m 34s
7269:	learn: 0.0013709	total: 13m 7s	remaining: 4m 55s
7634:	learn: 0.0017879	total: 13m 7s	remaining: 4m 4s
7997:	learn: 0.0014409	total: 13m 7s	remaining: 3m 17s
7858:	learn: 0.0015058	total: 13m 7s	remaining: 3m 34s
7857:	learn: 0.0014157	total: 13m 7s	remaining: 3m 34s
7998:	learn: 0.0014409	total: 13m 7s	remaining: 3m 17s
7270:	learn: 0.0013709	total: 13m 8s	remaining: 4m 55s
7859:	learn: 0.0015058	total: 13m 7s	remaining: 3m 34s
7635:	learn: 0.0017879	total: 13m 8s	remaining: 4m 3s
7858:	learn: 0.0014157	total: 13m 8s	remaining: 3m 34s
7999:	learn: 0.0014409	total: 13m 7s	remaining: 3m 16s
7271:	learn: 0.0013709	total: 13m 8s	remaining: 4m 55s
7860:	learn: 0.0015058	total: 13m 7s	remaining: 3m 34s
7636:	learn: 0.0017876	total: 13m 8s	remaining: 4m 3s
7859:	learn: 0.0014157	total: 13m 8s	remaining: 3m 34s
8000:	learn: 0.0014409	total: 13m 8s	remaining: 3m 16s
7272:	learn: 0.0013709	total: 13m 8s	remaining: 4m 55s
7861:	learn: 0.0015058	total: 13m 7s	remaining: 3m 34s
7637:	learn: 0.0017868	total: 13m 8s	remaining: 4m 3s
7860:	learn: 0.0014157	total: 13m 8s	remaining: 3m 34s
7273:	learn: 0.0013709	total: 13m 8s	remaining: 4m 55s
8001:	learn: 0.0014409	total: 13m 8s	remaining: 3m 16s
7862:	learn: 0.0015058	total: 13m 8s	remaining: 3m 34s
7638:	learn: 0.0017868	total: 13m 8s	remaining: 4m 3s
7861:	learn: 0.0014157	total: 13m 8s	remaining: 3m 34s
8002:	learn: 0.0014409	total: 13m 8s	remaining: 3m 16s
7863:	learn: 0.0015058	total: 13m 8s	remaining: 3m 34s
7639:	learn: 0.0017866	total: 13m 8s	remaining: 4m 3s
7274:	learn: 0.0013709	total: 13m 8s	remaining: 4m 55s
7862:	learn: 0.0014157	total: 13m 8s	remaining: 3m 34s
7864:	learn: 0.0015058	total: 13m 8s	remaining: 3m 33s
8003:	learn: 0.0014409	total: 13m 8s	remaining: 3m 16s
7640:	learn: 0.0017865	total: 13m 8s	remaining: 4m 3s
7865:	learn: 0.0015058	total: 13m 8s	remaining: 3m 33s
7863:	learn: 0.0014157	total: 13m 8s	remaining: 3m 34s
7275:	learn: 0.0013709	total: 13m 8s	remaining: 4m 55s
7641:	learn: 0.0017865	total: 13m 8s	remaining: 4m 3s
8004:	learn: 0.0014409	total: 13m 8s	remaining: 3m 16s
7864:	learn: 0.0014157	total: 13m 8s	remaining: 3m 34s
7866:	learn: 0.0015058	total: 13m 8s	remaining: 3m 33s
7642:	learn: 0.0017862	total: 13m 8s	remaining: 4m 3s
7276:	learn: 0.0013707	total: 13m 8s	remaining: 4m 55s
8005:	learn: 0.0014404	total: 13m 8s	remaining: 3m 16s
7865:	learn: 0.0014157	total: 13m 8s	remaining: 3m 33s
7643:	learn: 0.0017862	total: 13m 8s	remaining: 4m 3s
7867:	learn: 0.0015058	total: 13m 8s	remaining: 3m 33s
7277:	learn: 0.0013707	total: 13m 8s	remaining: 4m 55s
8006:	learn: 0.0014404	total: 13m 8s	remaining: 3m 16s
7644:	learn: 0.0017859	total: 13m 8s	remaining: 4m 3s
7866:	learn: 0.0014157	total: 13m 8s	remaining: 3m 33s
7868:	learn: 0.0015058	total: 13m 8s	remaining: 3m 33s
8007:	learn: 0.0014404	total: 13m 8s	remaining: 3m 16s
7278:	learn: 0.0013707	total: 13m 8s	remaining: 4m 54s
7867:	learn: 0.0014157	total: 13m 8s	remaining: 3m 33s
7645:	learn: 0.0017854	total: 13m 9s	remaining: 4m 2s
7869:	learn: 0.0015058	total: 13m 8s	remaining: 3m 33s
8008:	learn: 0.0014404	total: 13m 8s	remaining: 3m 16s
7279:	learn: 0.0013707	total: 13m 9s	remaining: 4m 54s
7868:	learn: 0.0014153	total: 13m 9s	remaining: 3m 33s
7646:	learn: 0.0017849	total: 13m 9s	remaining: 4m 2s
7870:	learn: 0.0015058	total: 13m 8s	remaining: 3m 33s
8009:	learn: 0.0014404	total: 13m 8s	remaining: 3m 16s
7280:	learn: 0.0013707	total: 13m 9s	remaining: 4m 54s
7647:	learn: 0.0017849	total: 13m 9s	remaining: 4m 2s
7869:	learn: 0.0014153	total: 13m 9s	remaining: 3m 33s
7871:	learn: 0.0015058	total: 13m 8s	remaining: 3m 33s
8010:	learn: 0.0014399	total: 13m 9s	remaining: 3m 15s
7648:	learn: 0.0017846	total: 13m 9s	remaining: 4m 2s
7281:	learn: 0.0013707	total: 13m 9s	remaining: 4m 54s
7872:	learn: 0.0015058	total: 13m 9s	remaining: 3m 33s
7870:	learn: 0.0014153	total: 13m 9s	remaining: 3m 33s
7649:	learn: 0.0017839	total: 13m 9s	remaining: 4m 2s
8011:	learn: 0.0014399	total: 13m 9s	remaining: 3m 15s
7282:	learn: 0.0013705	total: 13m 9s	remaining: 4m 54s
7873:	learn: 0.0015058	total: 13m 9s	remaining: 3m 33s
7871:	learn: 0.0014153	total: 13m 9s	remaining: 3m 33s
7650:	learn: 0.0017832	total: 13m 9s	remaining: 4m 2s
8012:	learn: 0.0014400	total: 13m 9s	remaining: 3m 15s
7872:	learn: 0.0014153	total: 13m 9s	remaining: 3m 33s
7283:	learn: 0.0013705	total: 13m 9s	remaining: 4m 54s
7874:	learn: 0.0015058	total: 13m 9s	remaining: 3m 32s
7651:	learn: 0.0017829	total: 13m 9s	remaining: 4m 2s
8013:	learn: 0.0014399	total: 13m 9s	remaining: 3m 15s
7873:	learn: 0.0014153	total: 13m 9s	remaining: 3m 33s
7284:	learn: 0.0013705	total: 13m 9s	remaining: 4m 54s
7875:	learn: 0.0015058	total: 13m 9s	remaining: 3m 32s
7652:	learn: 0.0017828	total: 13m 9s	remaining: 4m 2s
8014:	learn: 0.0014399	total: 13m 9s	remaining: 3m 15s
7874:	learn: 0.0014153	total: 13m 9s	remaining: 3m 33s
7285:	learn: 0.0013701	total: 13m 9s	remaining: 4m 54s
7876:	learn: 0.0015054	total: 13m 9s	remaining: 3m 32s
7653:	learn: 0.0017824	total: 13m 9s	remaining: 4m 2s
8015:	learn: 0.0014399	total: 13m 9s	remaining: 3m 15s
7875:	learn: 0.0014153	total: 13m 9s	remaining: 3m 32s
7286:	learn: 0.0013701	total: 13m 9s	remaining: 4m 54s
7877:	learn: 0.0015054	total: 13m 9s	remaining: 3m 32s
8016:	learn: 0.0014399	total: 13m 9s	remaining: 3m 15s
7654:	learn: 0.0017822	total: 13m 9s	remaining: 4m 1s
7287:	learn: 0.0013701	total: 13m 9s	remaining: 4m 53s
7876:	learn: 0.0014150	total: 13m 9s	remaining: 3m 32s
7878:	learn: 0.0015054	total: 13m 9s	remaining: 3m 32s
8017:	learn: 0.0014399	total: 13m 9s	remaining: 3m 15s
7655:	learn: 0.0017818	total: 13m 9s	remaining: 4m 1s
7877:	learn: 0.0014147	total: 13m 9s	remaining: 3m 32s
7879:	learn: 0.0015054	total: 13m 9s	remaining: 3m 32s
7288:	learn: 0.0013701	total: 13m 9s	remaining: 4m 53s
8018:	learn: 0.0014399	total: 13m 9s	remaining: 3m 15s
7656:	learn: 0.0017812	total: 13m 10s	remaining: 4m 1s
7880:	learn: 0.0015054	total: 13m 9s	remaining: 3m 32s
7878:	learn: 0.0014143	total: 13m 10s	remaining: 3m 32s
7289:	learn: 0.0013701	total: 13m 10s	remaining: 4m 53s
8019:	learn: 0.0014399	total: 13m 10s	remaining: 3m 15s
7657:	learn: 0.0017810	total: 13m 10s	remaining: 4m 1s
7881:	learn: 0.0015054	total: 13m 9s	remaining: 3m 32s
7879:	learn: 0.0014143	total: 13m 10s	remaining: 3m 32s
8020:	learn: 0.0014399	total: 13m 10s	remaining: 3m 14s
7290:	learn: 0.0013701	total: 13m 10s	remaining: 4m 53s
7882:	learn: 0.0015054	total: 13m 10s	remaining: 3m 32s
7880:	learn: 0.0014143	total: 13m 10s	remaining: 3m 32s
7658:	learn: 0.0017804	total: 13m 10s	remaining: 4m 1s
7291:	learn: 0.0013701	total: 13m 10s	remaining: 4m 53s
8021:	learn: 0.0014399	total: 13m 10s	remaining: 3m 14s
7883:	learn: 0.0015054	total: 13m 10s	remaining: 3m 32s
7659:	learn: 0.0017801	total: 13m 10s	remaining: 4m 1s
7881:	learn: 0.0014143	total: 13m 10s	remaining: 3m 32s
7292:	learn: 0.0013701	total: 13m 10s	remaining: 4m 53s
7884:	learn: 0.0015054	total: 13m 10s	remaining: 3m 31s
8022:	learn: 0.0014399	total: 13m 10s	remaining: 3m 14s
7660:	learn: 0.0017794	total: 13m 10s	remaining: 4m 1s
7882:	learn: 0.0014143	total: 13m 10s	remaining: 3m 32s
7293:	learn: 0.0013701	total: 13m 10s	remaining: 4m 53s
8023:	learn: 0.0014399	total: 13m 10s	remaining: 3m 14s
7885:	learn: 0.0015054	total: 13m 10s	remaining: 3m 31s
7883:	learn: 0.0014142	total: 13m 10s	remaining: 3m 32s
7661:	learn: 0.0017787	total: 13m 10s	remaining: 4m 1s
7294:	learn: 0.0013701	total: 13m 10s	remaining: 4m 53s
8024:	learn: 0.0014399	total: 13m 10s	remaining: 3m 14s
7886:	learn: 0.0015054	total: 13m 10s	remaining: 3m 31s
7884:	learn: 0.0014143	total: 13m 10s	remaining: 3m 32s
7662:	learn: 0.0017784	total: 13m 10s	remaining: 4m 1s
7295:	learn: 0.0013701	total: 13m 10s	remaining: 4m 53s
7885:	learn: 0.0014143	total: 13m 10s	remaining: 3m 31s
8025:	learn: 0.0014399	total: 13m 10s	remaining: 3m 14s
7887:	learn: 0.0015054	total: 13m 10s	remaining: 3m 31s
7663:	learn: 0.0017778	total: 13m 10s	remaining: 4m 1s
7886:	learn: 0.0014143	total: 13m 10s	remaining: 3m 31s
7296:	learn: 0.0013701	total: 13m 10s	remaining: 4m 52s
7888:	learn: 0.0015054	total: 13m 10s	remaining: 3m 31s
8026:	learn: 0.0014399	total: 13m 10s	remaining: 3m 14s
7887:	learn: 0.0014143	total: 13m 10s	remaining: 3m 31s
7297:	learn: 0.0013701	total: 13m 10s	remaining: 4m 52s
7664:	learn: 0.0017771	total: 13m 10s	remaining: 4m
7889:	learn: 0.0015054	total: 13m 10s	remaining: 3m 31s
7888:	learn: 0.0014143	total: 13m 10s	remaining: 3m 31s
8027:	learn: 0.0014399	total: 13m 10s	remaining: 3m 14s
7890:	learn: 0.0015054	total: 13m 10s	remaining: 3m 31s
7298:	learn: 0.0013697	total: 13m 11s	remaining: 4m 52s
7665:	learn: 0.0017767	total: 13m 11s	remaining: 4m
7891:	learn: 0.0015054	total: 13m 10s	remaining: 3m 31s
8028:	learn: 0.0014399	total: 13m 10s	remaining: 3m 14s
7889:	learn: 0.0014143	total: 13m 11s	remaining: 3m 31s
7299:	learn: 0.0013697	total: 13m 11s	remaining: 4m 52s
7666:	learn: 0.0017759	total: 13m 11s	remaining: 4m
7892:	learn: 0.0015054	total: 13m 10s	remaining: 3m 31s
8029:	learn: 0.0014399	total: 13m 11s	remaining: 3m 14s
7300:	learn: 0.0013697	total: 13m 11s	remaining: 4m 52s
7890:	learn: 0.0014143	total: 13m 11s	remaining: 3m 31s
7893:	learn: 0.0015054	total: 13m 11s	remaining: 3m 31s
7667:	learn: 0.0017752	total: 13m 11s	remaining: 4m
8030:	learn: 0.0014399	total: 13m 11s	remaining: 3m 13s
7301:	learn: 0.0013694	total: 13m 11s	remaining: 4m 52s
7891:	learn: 0.0014143	total: 13m 11s	remaining: 3m 31s
7894:	learn: 0.0015054	total: 13m 11s	remaining: 3m 30s
7668:	learn: 0.0017752	total: 13m 11s	remaining: 4m
8031:	learn: 0.0014399	total: 13m 11s	remaining: 3m 13s
7892:	learn: 0.0014143	total: 13m 11s	remaining: 3m 31s
7302:	learn: 0.0013694	total: 13m 11s	remaining: 4m 52s
7895:	learn: 0.0015054	total: 13m 11s	remaining: 3m 30s
8032:	learn: 0.0014399	total: 13m 11s	remaining: 3m 13s
7669:	learn: 0.0017746	total: 13m 11s	remaining: 4m
7896:	learn: 0.0015054	total: 13m 11s	remaining: 3m 30s
7303:	learn: 0.0013694	total: 13m 11s	remaining: 4m 52s
7893:	learn: 0.0014143	total: 13m 11s	remaining: 3m 31s
7897:	learn: 0.0015053	total: 13m 11s	remaining: 3m 30s

8033:	learn: 0.0014399	total: 13m 11s	remaining: 3m 13s
7670:	learn: 0.0017738	total: 13m 11s	remaining: 4m
7894:	learn: 0.0014142	total: 13m 11s	remaining: 3m 31s
7304:	learn: 0.0013692	total: 13m 11s	remaining: 4m 52s
7898:	learn: 0.0015053	total: 13m 11s	remaining: 3m 30s
8034:	learn: 0.0014399	total: 13m 11s	remaining: 3m 13s
7895:	learn: 0.0014143	total: 13m 11s	remaining: 3m 30s
7671:	learn: 0.0017738	total: 13m 11s	remaining: 4m
7305:	learn: 0.0013691	total: 13m 11s	remaining: 4m 51s
8035:	learn: 0.0014399	total: 13m 11s	remaining: 3m 13s
7899:	learn: 0.0015053	total: 13m 11s	remaining: 3m 30s
7672:	learn: 0.0017733	total: 13m 11s	remaining: 4m
7896:	learn: 0.0014143	total: 13m 11s	remaining: 3m 30s
7306:	learn: 0.0013688	total: 13m 11s	remaining: 4m 51s
8036:	learn: 0.0014399	total: 13m 11s	remaining: 3m 13s
7900:	learn: 0.0015053	total: 13m 11s	remaining: 3m 30s
7673:	learn: 0.0017726	total: 13m 11s	remaining: 4m
7307:	learn: 0.0013688	total: 13m 11s	remaining: 4m 51s
7897:	learn: 0.0014143	total: 13m 11s	remaining: 3m 30s
7901:	learn: 0.0015053	total: 13m 11s	remaining: 3m 30s
7674:	learn: 0.0017720	total: 13m 12s	remaining: 3m 59s
8037:	learn: 0.0014399	total: 13m 11s	remaining: 3m 13s
7308:	learn: 0.0013688	total: 13m 11s	remaining: 4m 51s
7898:	learn: 0.0014143	total: 13m 12s	remaining: 3m 30s
7902:	learn: 0.0015053	total: 13m 11s	remaining: 3m 30s
7675:	learn: 0.0017713	total: 13m 12s	remaining: 3m 59s
8038:	learn: 0.0014399	total: 13m 11s	remaining: 3m 13s
7899:	learn: 0.0014143	total: 13m 12s	remaining: 3m 30s
7309:	learn: 0.0013688	total: 13m 12s	remaining: 4m 51s
7903:	learn: 0.0015053	total: 13m 11s	remaining: 3m 30s
7676:	learn: 0.0017706	total: 13m 12s	remaining: 3m 59s
8039:	learn: 0.0014399	total: 13m 12s	remaining: 3m 13s
7900:	learn: 0.0014139	total: 13m 12s	remaining: 3m 30s
7310:	learn: 0.0013688	total: 13m 12s	remaining: 4m 51s
7677:	learn: 0.0017700	total: 13m 12s	remaining: 3m 59s
7904:	learn: 0.0015053	total: 13m 12s	remaining: 3m 29s
7901:	learn: 0.0014139	total: 13m 12s	remaining: 3m 30s
8040:	learn: 0.0014399	total: 13m 12s	remaining: 3m 12s
7311:	learn: 0.0013688	total: 13m 12s	remaining: 4m 51s
7678:	learn: 0.0017694	total: 13m 12s	remaining: 3m 59s
7905:	learn: 0.0015053	total: 13m 12s	remaining: 3m 29s
7902:	learn: 0.0014139	total: 13m 12s	remaining: 3m 30s
8041:	learn: 0.0014399	total: 13m 12s	remaining: 3m 12s
7312:	learn: 0.0013688	total: 13m 12s	remaining: 4m 51s
7679:	learn: 0.0017687	total: 13m 12s	remaining: 3m 59s
7906:	learn: 0.0015047	total: 13m 12s	remaining: 3m 29s
7903:	learn: 0.0014139	total: 13m 12s	remaining: 3m 30s
8042:	learn: 0.0014399	total: 13m 12s	remaining: 3m 12s
7313:	learn: 0.0013688	total: 13m 12s	remaining: 4m 51s
7680:	learn: 0.0017680	total: 13m 12s	remaining: 3m 59s
7907:	learn: 0.0015047	total: 13m 12s	remaining: 3m 29s
7904:	learn: 0.0014139	total: 13m 12s	remaining: 3m 30s
8043:	learn: 0.0014399	total: 13m 12s	remaining: 3m 12s
7681:	learn: 0.0017680	total: 13m 12s	remaining: 3m 59s
7908:	learn: 0.0015047	total: 13m 12s	remaining: 3m 29s
8044:	learn: 0.0014399	total: 13m 12s	remaining: 3m 12s
7314:	learn: 0.0013688	total: 13m 12s	remaining: 4m 50s
7905:	learn: 0.0014139	total: 13m 12s	remaining: 3m 29s
7682:	learn: 0.0017673	total: 13m 12s	remaining: 3m 59s
8045:	learn: 0.0014399	total: 13m 12s	remaining: 3m 12s
7315:	learn: 0.0013688	total: 13m 12s	remaining: 4m 50s
7909:	learn: 0.0015047	total: 13m 12s	remaining: 3m 29s
7906:	learn: 0.0014139	total: 13m 12s	remaining: 3m 29s
7683:	learn: 0.0017673	total: 13m 12s	remaining: 3m 58s
8046:	learn: 0.0014399	total: 13m 12s	remaining: 3m 12s
7907:	learn: 0.0014139	total: 13m 12s	remaining: 3m 29s
7910:	learn: 0.0015047	total: 13m 12s	remaining: 3m 29s
7316:	learn: 0.0013688	total: 13m 12s	remaining: 4m 50s
7684:	learn: 0.0017668	total: 13m 12s	remaining: 3m 58s
7908:	learn: 0.0014139	total: 13m 12s	remaining: 3m 29s
8047:	learn: 0.0014399	total: 13m 12s	remaining: 3m 12s
7317:	learn: 0.0013688	total: 13m 12s	remaining: 4m 50s
7911:	learn: 0.0015047	total: 13m 12s	remaining: 3m 29s
7685:	learn: 0.0017662	total: 13m 13s	remaining: 3m 58s
7318:	learn: 0.0013688	total: 13m 13s	remaining: 4m 50s
7909:	learn: 0.0014139	total: 13m 13s	remaining: 3m 29s
8048:	learn: 0.0014399	total: 13m 12s	remaining: 3m 12s
7912:	learn: 0.0015047	total: 13m 12s	remaining: 3m 29s
7686:	learn: 0.0017655	total: 13m 13s	remaining: 3m 58s
7910:	learn: 0.0014135	total: 13m 13s	remaining: 3m 29s
8049:	learn: 0.0014399	total: 13m 13s	remaining: 3m 12s
7319:	learn: 0.0013688	total: 13m 13s	remaining: 4m 50s
7913:	learn: 0.0015047	total: 13m 13s	remaining: 3m 29s
7911:	learn: 0.0014135	total: 13m 13s	remaining: 3m 29s
7687:	learn: 0.0017651	total: 13m 13s	remaining: 3m 58s
8050:	learn: 0.0014399	total: 13m 13s	remaining: 3m 12s
7320:	learn: 0.0013688	total: 13m 13s	remaining: 4m 50s
7914:	learn: 0.0015047	total: 13m 13s	remaining: 3m 28s
7912:	learn: 0.0014130	total: 13m 13s	remaining: 3m 29s
7688:	learn: 0.0017645	total: 13m 13s	remaining: 3m 58s
8051:	learn: 0.0014399	total: 13m 13s	remaining: 3m 11s
7321:	learn: 0.0013688	total: 13m 13s	remaining: 4m 50s
7913:	learn: 0.0014127	total: 13m 13s	remaining: 3m 29s
7689:	learn: 0.0017639	total: 13m 13s	remaining: 3m 58s
7915:	learn: 0.0015047	total: 13m 13s	remaining: 3m 28s
8052:	learn: 0.0014399	total: 13m 13s	remaining: 3m 11s
7322:	learn: 0.0013688	total: 13m 13s	remaining: 4m 50s
7914:	learn: 0.0014127	total: 13m 13s	remaining: 3m 29s
8053:	learn: 0.0014399	total: 13m 13s	remaining: 3m 11s
7916:	learn: 0.0015047	total: 13m 13s	remaining: 3m 28s
7690:	learn: 0.0017633	total: 13m 13s	remaining: 3m 58s
7915:	learn: 0.0014127	total: 13m 13s	remaining: 3m 28s
7323:	learn: 0.0013688	total: 13m 13s	remaining: 4m 49s
8054:	learn: 0.0014399	total: 13m 13s	remaining: 3m 11s
7916:	learn: 0.0014127	total: 13m 13s	remaining: 3m 28s
7917:	learn: 0.0015047	total: 13m 13s	remaining: 3m 28s
7691:	learn: 0.0017627	total: 13m 13s	remaining: 3m 58s
8055:	learn: 0.0014399	total: 13m 13s	remaining: 3m 11s
7324:	learn: 0.0013684	total: 13m 13s	remaining: 4m 49s
7917:	learn: 0.0014127	total: 13m 13s	remaining: 3m 28s
7692:	learn: 0.0017620	total: 13m 13s	remaining: 3m 58s
7918:	learn: 0.0015047	total: 13m 13s	remaining: 3m 28s
7918:	learn: 0.0014127	total: 13m 13s	remaining: 3m 28s
7325:	learn: 0.0013684	total: 13m 13s	remaining: 4m 49s
8056:	learn: 0.0014399	total: 13m 13s	remaining: 3m 11s
7693:	learn: 0.0017614	total: 13m 13s	remaining: 3m 57s
7919:	learn: 0.0015047	total: 13m 13s	remaining: 3m 28s
7919:	learn: 0.0014127	total: 13m 13s	remaining: 3m 28s
8057:	learn: 0.0014399	total: 13m 13s	remaining: 3m 11s
7326:	learn: 0.0013684	total: 13m 13s	remaining: 4m 49s
7694:	learn: 0.0017607	total: 13m 14s	remaining: 3m 57s
7920:	learn: 0.0014127	total: 13m 13s	remaining: 3m 28s
7920:	learn: 0.0015047	total: 13m 13s	remaining: 3m 28s
8058:	learn: 0.0014399	total: 13m 13s	remaining: 3m 11s
7327:	learn: 0.0013684	total: 13m 14s	remaining: 4m 49s
7921:	learn: 0.0014127	total: 13m 14s	remaining: 3m 28s
7695:	learn: 0.0017602	total: 13m 14s	remaining: 3m 57s
7921:	learn: 0.0015047	total: 13m 13s	remaining: 3m 28s
8059:	learn: 0.0014399	total: 13m 14s	remaining: 3m 11s
7922:	learn: 0.0014127	total: 13m 14s	remaining: 3m 28s
7328:	learn: 0.0013684	total: 13m 14s	remaining: 4m 49s
7696:	learn: 0.0017595	total: 13m 14s	remaining: 3m 57s
7922:	learn: 0.0015047	total: 13m 13s	remaining: 3m 28s
7923:	learn: 0.0014123	total: 13m 14s	remaining: 3m 28s
8060:	learn: 0.0014399	total: 13m 14s	remaining: 3m 11s
7697:	learn: 0.0017589	total: 13m 14s	remaining: 3m 57s
7923:	learn: 0.0015047	total: 13m 14s	remaining: 3m 28s
7329:	learn: 0.0013684	total: 13m 14s	remaining: 4m 49s
7924:	learn: 0.0014123	total: 13m 14s	remaining: 3m 27s
8061:	learn: 0.0014399	total: 13m 14s	remaining: 3m 10s
7330:	learn: 0.0013684	total: 13m 14s	remaining: 4m 49s
7698:	learn: 0.0017583	total: 13m 14s	remaining: 3m 57s
7924:	learn: 0.0015047	total: 13m 14s	remaining: 3m 27s
7925:	learn: 0.0014123	total: 13m 14s	remaining: 3m 27s
7699:	learn: 0.0017576	total: 13m 14s	remaining: 3m 57s
8062:	learn: 0.0014399	total: 13m 14s	remaining: 3m 10s
7331:	learn: 0.0013684	total: 13m 14s	remaining: 4m 49s
7925:	learn: 0.0015047	total: 13m 14s	remaining: 3m 27s
7926:	learn: 0.0014118	total: 13m 14s	remaining: 3m 27s
8063:	learn: 0.0014399	total: 13m 14s	remaining: 3m 10s
7700:	learn: 0.0017569	total: 13m 14s	remaining: 3m 57s
7927:	learn: 0.0014118	total: 13m 14s	remaining: 3m 27s
7926:	learn: 0.0015047	total: 13m 14s	remaining: 3m 27s
7332:	learn: 0.0013684	total: 13m 14s	remaining: 4m 49s
8064:	learn: 0.0014399	total: 13m 14s	remaining: 3m 10s
7701:	learn: 0.0017564	total: 13m 14s	remaining: 3m 57s
7928:	learn: 0.0014117	total: 13m 14s	remaining: 3m 27s
7333:	learn: 0.0013684	total: 13m 14s	remaining: 4m 48s
7927:	learn: 0.0015047	total: 13m 14s	remaining: 3m 27s
8065:	learn: 0.0014399	total: 13m 14s	remaining: 3m 10s
7702:	learn: 0.0017557	total: 13m 14s	remaining: 3m 57s
7929:	learn: 0.0014117	total: 13m 14s	remaining: 3m 27s
7334:	learn: 0.0013684	total: 13m 14s	remaining: 4m 48s
7928:	learn: 0.0015047	total: 13m 14s	remaining: 3m 27s
8066:	learn: 0.0014399	total: 13m 14s	remaining: 3m 10s
7703:	learn: 0.0017551	total: 13m 14s	remaining: 3m 56s
7930:	learn: 0.0014117	total: 13m 14s	remaining: 3m 27s
7335:	learn: 0.0013684	total: 13m 14s	remaining: 4m 48s
7929:	learn: 0.0015047	total: 13m 14s	remaining: 3m 27s
8067:	learn: 0.0014399	total: 13m 14s	remaining: 3m 10s
7931:	learn: 0.0014117	total: 13m 14s	remaining: 3m 27s
7336:	learn: 0.0013684	total: 13m 15s	remaining: 4m 48s
7704:	learn: 0.0017544	total: 13m 15s	remaining: 3m 56s
7930:	learn: 0.0015047	total: 13m 14s	remaining: 3m 27s
8068:	learn: 0.0014399	total: 13m 14s	remaining: 3m 10s
7932:	learn: 0.0014117	total: 13m 15s	remaining: 3m 27s
7705:	learn: 0.0017538	total: 13m 15s	remaining: 3m 56s
7931:	learn: 0.0015047	total: 13m 14s	remaining: 3m 27s
8069:	learn: 0.0014399	total: 13m 15s	remaining: 3m 10s
7933:	learn: 0.0014117	total: 13m 15s	remaining: 3m 27s
7337:	learn: 0.0013684	total: 13m 15s	remaining: 4m 48s
7706:	learn: 0.0017533	total: 13m 15s	remaining: 3m 56s
8070:	learn: 0.0014399	total: 13m 15s	remaining: 3m 10s
7932:	learn: 0.0015047	total: 13m 14s	remaining: 3m 27s
7934:	learn: 0.0014117	total: 13m 15s	remaining: 3m 26s
7707:	learn: 0.0017527	total: 13m 15s	remaining: 3m 56s
7338:	learn: 0.0013684	total: 13m 15s	remaining: 4m 48s
8071:	learn: 0.0014399	total: 13m 15s	remaining: 3m 9s
7933:	learn: 0.0015047	total: 13m 15s	remaining: 3m 27s
7935:	learn: 0.0014117	total: 13m 15s	remaining: 3m 26s
7339:	learn: 0.0013684	total: 13m 15s	remaining: 4m 48s
7708:	learn: 0.0017520	total: 13m 15s	remaining: 3m 56s
8072:	learn: 0.0014399	total: 13m 15s	remaining: 3m 9s
7936:	learn: 0.0014117	total: 13m 15s	remaining: 3m 26s
7934:	learn: 0.0015047	total: 13m 15s	remaining: 3m 26s
7340:	learn: 0.0013684	total: 13m 15s	remaining: 4m 48s
7709:	learn: 0.0017515	total: 13m 15s	remaining: 3m 56s
7937:	learn: 0.0014117	total: 13m 15s	remaining: 3m 26s
8073:	learn: 0.0014399	total: 13m 15s	remaining: 3m 9s
7935:	learn: 0.0015047	total: 13m 15s	remaining: 3m 26s
7341:	learn: 0.0013684	total: 13m 15s	remaining: 4m 48s
8074:	learn: 0.0014399	total: 13m 15s	remaining: 3m 9s
7936:	learn: 0.0015047	total: 13m 15s	remaining: 3m 26s
7938:	learn: 0.0014117	total: 13m 15s	remaining: 3m 26s
7710:	learn: 0.0017511	total: 13m 15s	remaining: 3m 56s
7342:	learn: 0.0013680	total: 13m 15s	remaining: 4m 47s
7939:	learn: 0.0014117	total: 13m 15s	remaining: 3m 26s
8075:	learn: 0.0014399	total: 13m 15s	remaining: 3m 9s
7937:	learn: 0.0015047	total: 13m 15s	remaining: 3m 26s
7711:	learn: 0.0017504	total: 13m 15s	remaining: 3m 56s
8076:	learn: 0.0014399	total: 13m 15s	remaining: 3m 9s
7938:	learn: 0.0015047	total: 13m 15s	remaining: 3m 26s
7343:	learn: 0.0013680	total: 13m 15s	remaining: 4m 47s
7940:	learn: 0.0014117	total: 13m 15s	remaining: 3m 26s
7712:	learn: 0.0017499	total: 13m 15s	remaining: 3m 55s
7939:	learn: 0.0015045	total: 13m 15s	remaining: 3m 26s
7344:	learn: 0.0013680	total: 13m 15s	remaining: 4m 47s
7941:	learn: 0.0014117	total: 13m 15s	remaining: 3m 26s
8077:	learn: 0.0014399	total: 13m 15s	remaining: 3m 9s
7713:	learn: 0.0017494	total: 13m 15s	remaining: 3m 55s
7940:	learn: 0.0015045	total: 13m 15s	remaining: 3m 26s
7345:	learn: 0.0013680	total: 13m 15s	remaining: 4m 47s
7942:	learn: 0.0014117	total: 13m 16s	remaining: 3m 26s
8078:	learn: 0.0014399	total: 13m 15s	remaining: 3m 9s
7714:	learn: 0.0017489	total: 13m 16s	remaining: 3m 55s
7941:	learn: 0.0015045	total: 13m 15s	remaining: 3m 26s
7943:	learn: 0.0014117	total: 13m 16s	remaining: 3m 26s
7346:	learn: 0.0013680	total: 13m 16s	remaining: 4m 47s
8079:	learn: 0.0014399	total: 13m 16s	remaining: 3m 9s
7942:	learn: 0.0015045	total: 13m 15s	remaining: 3m 26s
7715:	learn: 0.0017484	total: 13m 16s	remaining: 3m 55s
7944:	learn: 0.0014117	total: 13m 16s	remaining: 3m 25s
7347:	learn: 0.0013680	total: 13m 16s	remaining: 4m 47s
8080:	learn: 0.0014395	total: 13m 16s	remaining: 3m 9s
7943:	learn: 0.0015045	total: 13m 16s	remaining: 3m 26s
7716:	learn: 0.0017479	total: 13m 16s	remaining: 3m 55s
7945:	learn: 0.0014117	total: 13m 16s	remaining: 3m 25s
7348:	learn: 0.0013680	total: 13m 16s	remaining: 4m 47s
8081:	learn: 0.0014395	total: 13m 16s	remaining: 3m 8s
7944:	learn: 0.0015045	total: 13m 16s	remaining: 3m 25s
7717:	learn: 0.0017475	total: 13m 16s	remaining: 3m 55s
7946:	learn: 0.0014117	total: 13m 16s	remaining: 3m 25s
7349:	learn: 0.0013676	total: 13m 16s	remaining: 4m 47s
8082:	learn: 0.0014395	total: 13m 16s	remaining: 3m 8s
7945:	learn: 0.0015045	total: 13m 16s	remaining: 3m 25s
7718:	learn: 0.0017471	total: 13m 16s	remaining: 3m 55s
7947:	learn: 0.0014117	total: 13m 16s	remaining: 3m 25s
8083:	learn: 0.0014396	total: 13m 16s	remaining: 3m 8s
7946:	learn: 0.0015045	total: 13m 16s	remaining: 3m 25s
7350:	learn: 0.0013676	total: 13m 16s	remaining: 4m 47s
7719:	learn: 0.0017467	total: 13m 16s	remaining: 3m 55s
7948:	learn: 0.0014117	total: 13m 16s	remaining: 3m 25s
7720:	learn: 0.0017462	total: 13m 16s	remaining: 3m 55s
8084:	learn: 0.0014395	total: 13m 16s	remaining: 3m 8s
7947:	learn: 0.0015045	total: 13m 16s	remaining: 3m 25s
7351:	learn: 0.0013676	total: 13m 16s	remaining: 4m 46s
7949:	learn: 0.0014117	total: 13m 16s	remaining: 3m 25s
7721:	learn: 0.0017455	total: 13m 16s	remaining: 3m 55s
8085:	learn: 0.0014395	total: 13m 16s	remaining: 3m 8s
7948:	learn: 0.0015045	total: 13m 16s	remaining: 3m 25s
7352:	learn: 0.0013676	total: 13m 16s	remaining: 4m 46s
7722:	learn: 0.0017449	total: 13m 16s	remaining: 3m 54s
7950:	learn: 0.0014117	total: 13m 16s	remaining: 3m 25s
8086:	learn: 0.0014395	total: 13m 16s	remaining: 3m 8s
7353:	learn: 0.0013673	total: 13m 16s	remaining: 4m 46s
7949:	learn: 0.0015045	total: 13m 16s	remaining: 3m 25s
7723:	learn: 0.0017442	total: 13m 16s	remaining: 3m 54s
8087:	learn: 0.0014395	total: 13m 16s	remaining: 3m 8s
7951:	learn: 0.0014117	total: 13m 16s	remaining: 3m 25s
7354:	learn: 0.0013672	total: 13m 16s	remaining: 4m 46s
8088:	learn: 0.0014395	total: 13m 16s	remaining: 3m 8s
7724:	learn: 0.0017438	total: 13m 17s	remaining: 3m 54s
7950:	learn: 0.0015045	total: 13m 16s	remaining: 3m 25s
7952:	learn: 0.0014117	total: 13m 17s	remaining: 3m 25s
8089:	learn: 0.0014395	total: 13m 16s	remaining: 3m 8s
7725:	learn: 0.0017435	total: 13m 17s	remaining: 3m 54s
7355:	learn: 0.0013672	total: 13m 17s	remaining: 4m 46s
8090:	learn: 0.0014395	total: 13m 17s	remaining: 3m 8s
7951:	learn: 0.0015045	total: 13m 16s	remaining: 3m 25s
7953:	learn: 0.0014117	total: 13m 17s	remaining: 3m 25s
7726:	learn: 0.0017429	total: 13m 17s	remaining: 3m 54s
7356:	learn: 0.0013672	total: 13m 17s	remaining: 4m 46s
7727:	learn: 0.0017423	total: 13m 17s	remaining: 3m 54s
7954:	learn: 0.0014117	total: 13m 17s	remaining: 3m 24s
8091:	learn: 0.0014395	total: 13m 17s	remaining: 3m 7s
7952:	learn: 0.0015045	total: 13m 17s	remaining: 3m 25s
7357:	learn: 0.0013672	total: 13m 17s	remaining: 4m 46s
7955:	learn: 0.0014117	total: 13m 17s	remaining: 3m 24s
8092:	learn: 0.0014395	total: 13m 17s	remaining: 3m 7s
7728:	learn: 0.0017416	total: 13m 17s	remaining: 3m 54s
7953:	learn: 0.0015045	total: 13m 17s	remaining: 3m 25s
7358:	learn: 0.0013672	total: 13m 17s	remaining: 4m 46s

7956:	learn: 0.0014117	total: 13m 17s	remaining: 3m 24s
7954:	learn: 0.0015045	total: 13m 17s	remaining: 3m 24s
7729:	learn: 0.0017412	total: 13m 17s	remaining: 3m 54s
7957:	learn: 0.0014117	total: 13m 17s	remaining: 3m 24s
8094:	learn: 0.0014395	total: 13m 17s	remaining: 3m 7s
7359:	learn: 0.0013672	total: 13m 17s	remaining: 4m 46s
7955:	learn: 0.0015045	total: 13m 17s	remaining: 3m 24s
7730:	learn: 0.0017405	total: 13m 17s	remaining: 3m 54s
7958:	learn: 0.0014117	total: 13m 17s	remaining: 3m 24s
8095:	learn: 0.0014395	total: 13m 17s	remaining: 3m 7s
7956:	learn: 0.0015045	total: 13m 17s	remaining: 3m 24s
7731:	learn: 0.0017405	total: 13m 17s	remaining: 3m 53s
7360:	learn: 0.0013672	total: 13m 17s	remaining: 4m 45s
7959:	learn: 0.0014117	total: 13m 17s	remaining: 3m 24s
8096:	learn: 0.0014395	total: 13m 17s	remaining: 3m 7s
7732:	learn: 0.0017400	total: 13m 17s	remaining: 3m 53s
7957:	learn: 0.0015045	total: 13m 17s	remaining: 3m 24s
7960:	learn: 0.0014117	total: 13m 17s	remaining: 3m 24s
8097:	learn: 0.0014395	total: 13m 17s	remaining: 3m 7s
7361:	learn: 0.0013672	total: 13m 17s	remaining: 4m 45s
7733:	learn: 0.0017393	total: 13m 17s	remaining: 3m 53s
7958:	learn: 0.0015045	total: 13m 17s	remaining: 3m 24s
8098:	learn: 0.0014395	total: 13m 17s	remaining: 3m 7s
7961:	learn: 0.0014117	total: 13m 17s	remaining: 3m 24s
7734:	learn: 0.0017388	total: 13m 17s	remaining: 3m 53s
7362:	learn: 0.0013672	total: 13m 17s	remaining: 4m 45s
8099:	learn: 0.0014395	total: 13m 17s	remaining: 3m 7s
7959:	learn: 0.0015045	total: 13m 17s	remaining: 3m 24s
7735:	learn: 0.0017384	total: 13m 18s	remaining: 3m 53s
7962:	learn: 0.0014117	total: 13m 18s	remaining: 3m 24s
7363:	learn: 0.0013672	total: 13m 18s	remaining: 4m 45s
7960:	learn: 0.0015045	total: 13m 17s	remaining: 3m 24s
8100:	learn: 0.0014395	total: 13m 17s	remaining: 3m 7s
7736:	learn: 0.0017378	total: 13m 18s	remaining: 3m 53s
7963:	learn: 0.0014117	total: 13m 18s	remaining: 3m 24s
7961:	learn: 0.0015041	total: 13m 17s	remaining: 3m 24s
7364:	learn: 0.0013672	total: 13m 18s	remaining: 4m 45s
8101:	learn: 0.0014395	total: 13m 18s	remaining: 3m 6s
7962:	learn: 0.0015041	total: 13m 17s	remaining: 3m 24s
7737:	learn: 0.0017372	total: 13m 18s	remaining: 3m 53s
7964:	learn: 0.0014117	total: 13m 18s	remaining: 3m 23s
7365:	learn: 0.0013672	total: 13m 18s	remaining: 4m 45s
8102:	learn: 0.0014395	total: 13m 18s	remaining: 3m 6s
7963:	learn: 0.0015041	total: 13m 18s	remaining: 3m 24s
7738:	learn: 0.0017368	total: 13m 18s	remaining: 3m 53s
7965:	learn: 0.0014117	total: 13m 18s	remaining: 3m 23s
7366:	learn: 0.0013672	total: 13m 18s	remaining: 4m 45s
8103:	learn: 0.0014393	total: 13m 18s	remaining: 3m 6s
7739:	learn: 0.0017368	total: 13m 18s	remaining: 3m 53s
7964:	learn: 0.0015041	total: 13m 18s	remaining: 3m 23s
7367:	learn: 0.0013672	total: 13m 18s	remaining: 4m 45s
7966:	learn: 0.0014117	total: 13m 18s	remaining: 3m 23s
8104:	learn: 0.0014393	total: 13m 18s	remaining: 3m 6s
7965:	learn: 0.0015041	total: 13m 18s	remaining: 3m 23s
7740:	learn: 0.0017364	total: 13m 18s	remaining: 3m 53s
7966:	learn: 0.0015041	total: 13m 18s	remaining: 3m 23s
7967:	learn: 0.0014117	total: 13m 18s	remaining: 3m 23s
7368:	learn: 0.0013672	total: 13m 18s	remaining: 4m 45s
8105:	learn: 0.0014393	total: 13m 18s	remaining: 3m 6s
7741:	learn: 0.0017357	total: 13m 18s	remaining: 3m 52s
7967:	learn: 0.0015041	total: 13m 18s	remaining: 3m 23s
7968:	learn: 0.0014117	total: 13m 18s	remaining: 3m 23s
7369:	learn: 0.0013672	total: 13m 18s	remaining: 4m 45s
8106:	learn: 0.0014393	total: 13m 18s	remaining: 3m 6s
7742:	learn: 0.0017354	total: 13m 18s	remaining: 3m 52s
7968:	learn: 0.0015041	total: 13m 18s	remaining: 3m 23s
8107:	learn: 0.0014389	total: 13m 18s	remaining: 3m 6s
7969:	learn: 0.0014117	total: 13m 18s	remaining: 3m 23s
7743:	learn: 0.0017348	total: 13m 18s	remaining: 3m 52s
7969:	learn: 0.0015041	total: 13m 18s	remaining: 3m 23s
7370:	learn: 0.0013672	total: 13m 18s	remaining: 4m 44s
8108:	learn: 0.0014389	total: 13m 18s	remaining: 3m 6s
7970:	learn: 0.0014117	total: 13m 18s	remaining: 3m 23s
7744:	learn: 0.0017342	total: 13m 18s	remaining: 3m 52s
7970:	learn: 0.0015041	total: 13m 18s	remaining: 3m 23s
7371:	learn: 0.0013672	total: 13m 18s	remaining: 4m 44s
8109:	learn: 0.0014389	total: 13m 18s	remaining: 3m 6s
7971:	learn: 0.0014117	total: 13m 18s	remaining: 3m 23s
7745:	learn: 0.0017336	total: 13m 19s	remaining: 3m 52s
7971:	learn: 0.0015041	total: 13m 18s	remaining: 3m 23s
7372:	learn: 0.0013672	total: 13m 19s	remaining: 4m 44s
7972:	learn: 0.0014117	total: 13m 19s	remaining: 3m 23s
8110:	learn: 0.0014384	total: 13m 18s	remaining: 3m 6s
7746:	learn: 0.0017331	total: 13m 19s	remaining: 3m 52s
7972:	learn: 0.0015041	total: 13m 18s	remaining: 3m 23s
7373:	learn: 0.0013672	total: 13m 19s	remaining: 4m 44s
8111:	learn: 0.0014384	total: 13m 19s	remaining: 3m 5s
7973:	learn: 0.0014117	total: 13m 19s	remaining: 3m 23s
7973:	learn: 0.0015041	total: 13m 18s	remaining: 3m 22s
7747:	learn: 0.0017327	total: 13m 19s	remaining: 3m 52s
8112:	learn: 0.0014384	total: 13m 19s	remaining: 3m 5s
7974:	learn: 0.0014117	total: 13m 19s	remaining: 3m 22s
7374:	learn: 0.0013672	total: 13m 19s	remaining: 4m 44s
7974:	learn: 0.0015041	total: 13m 19s	remaining: 3m 22s
7748:	learn: 0.0017322	total: 13m 19s	remaining: 3m 52s
7975:	learn: 0.0014117	total: 13m 19s	remaining: 3m 22s
8113:	learn: 0.0014384	total: 13m 19s	remaining: 3m 5s
7375:	learn: 0.0013672	total: 13m 19s	remaining: 4m 44s
7975:	learn: 0.0015041	total: 13m 19s	remaining: 3m 22s
7749:	learn: 0.0017317	total: 13m 19s	remaining: 3m 52s
8114:	learn: 0.0014382	total: 13m 19s	remaining: 3m 5s
7976:	learn: 0.0015041	total: 13m 19s	remaining: 3m 22s
7976:	learn: 0.0014117	total: 13m 19s	remaining: 3m 22s
7750:	learn: 0.0017313	total: 13m 19s	remaining: 3m 51s
7376:	learn: 0.0013672	total: 13m 19s	remaining: 4m 44s
8115:	learn: 0.0014382	total: 13m 19s	remaining: 3m 5s
7977:	learn: 0.0014117	total: 13m 19s	remaining: 3m 22s
7977:	learn: 0.0015041	total: 13m 19s	remaining: 3m 22s
7751:	learn: 0.0017307	total: 13m 19s	remaining: 3m 51s
8116:	learn: 0.0014382	total: 13m 19s	remaining: 3m 5s
7377:	learn: 0.0013672	total: 13m 19s	remaining: 4m 44s
7978:	learn: 0.0014117	total: 13m 19s	remaining: 3m 22s
7752:	learn: 0.0017301	total: 13m 19s	remaining: 3m 51s
8117:	learn: 0.0014382	total: 13m 19s	remaining: 3m 5s
7978:	learn: 0.0015041	total: 13m 19s	remaining: 3m 22s
7979:	learn: 0.0014117	total: 13m 19s	remaining: 3m 22s
7378:	learn: 0.0013671	total: 13m 19s	remaining: 4m 44s
8118:	learn: 0.0014382	total: 13m 19s	remaining: 3m 5s
7753:	learn: 0.0017297	total: 13m 19s	remaining: 3m 51s
7980:	learn: 0.0014117	total: 13m 19s	remaining: 3m 22s
7379:	learn: 0.0013671	total: 13m 19s	remaining: 4m 43s
7979:	learn: 0.0015041	total: 13m 19s	remaining: 3m 22s
8119:	learn: 0.0014382	total: 13m 19s	remaining: 3m 5s
7981:	learn: 0.0014117	total: 13m 19s	remaining: 3m 22s
7380:	learn: 0.0013672	total: 13m 19s	remaining: 4m 43s
7754:	learn: 0.0017297	total: 13m 19s	remaining: 3m 51s
7980:	learn: 0.0015041	total: 13m 19s	remaining: 3m 22s
8120:	learn: 0.0014382	total: 13m 19s	remaining: 3m 5s
7982:	learn: 0.0014116	total: 13m 20s	remaining: 3m 22s
7755:	learn: 0.0017294	total: 13m 20s	remaining: 3m 51s
7381:	learn: 0.0013672	total: 13m 20s	remaining: 4m 43s
7981:	learn: 0.0015041	total: 13m 19s	remaining: 3m 22s
8121:	learn: 0.0014382	total: 13m 19s	remaining: 3m 4s
7983:	learn: 0.0014116	total: 13m 20s	remaining: 3m 22s
7382:	learn: 0.0013672	total: 13m 20s	remaining: 4m 43s
7756:	learn: 0.0017288	total: 13m 20s	remaining: 3m 51s
7982:	learn: 0.0015041	total: 13m 19s	remaining: 3m 22s
8122:	learn: 0.0014381	total: 13m 20s	remaining: 3m 4s
7984:	learn: 0.0014111	total: 13m 20s	remaining: 3m 21s
7757:	learn: 0.0017288	total: 13m 20s	remaining: 3m 51s
7383:	learn: 0.0013671	total: 13m 20s	remaining: 4m 43s
8123:	learn: 0.0014381	total: 13m 20s	remaining: 3m 4s
7985:	learn: 0.0014111	total: 13m 20s	remaining: 3m 21s
7983:	learn: 0.0015041	total: 13m 20s	remaining: 3m 22s
7758:	learn: 0.0017284	total: 13m 20s	remaining: 3m 51s
11s	remaining: 3m 31s
7897:	learn: 0.0015053	total: 13m8124:	learn: 0.0014382	total: 13m 20s	remaining: 3m 4s
7384:	learn: 0.0013672	total: 13m 20s	remaining: 4m 43s
7984:	learn: 0.0015041	total: 13m 20s	remaining: 3m 21s
7759:	learn: 0.0017279	total: 13m 20s	remaining: 3m 51s
7986:	learn: 0.0014111	total: 13m 20s	remaining: 3m 21s
7760:	learn: 0.0017275	total: 13m 20s	remaining: 3m 50s
8125:	learn: 0.0014376	total: 13m 20s	remaining: 3m 4s
7985:	learn: 0.0015041	total: 13m 20s	remaining: 3m 21s
7385:	learn: 0.0013671	total: 13m 20s	remaining: 4m 43s
7987:	learn: 0.0014111	total: 13m 20s	remaining: 3m 21s
8126:	learn: 0.0014376	total: 13m 20s	remaining: 3m 4s
7761:	learn: 0.0017269	total: 13m 20s	remaining: 3m 50s
7986:	learn: 0.0015041	total: 13m 20s	remaining: 3m 21s
7386:	learn: 0.0013670	total: 13m 20s	remaining: 4m 43s
8127:	learn: 0.0014376	total: 13m 20s	remaining: 3m 4s
7988:	learn: 0.0014111	total: 13m 20s	remaining: 3m 21s
7762:	learn: 0.0017264	total: 13m 20s	remaining: 3m 50s
7987:	learn: 0.0015041	total: 13m 20s	remaining: 3m 21s
8128:	learn: 0.0014376	total: 13m 20s	remaining: 3m 4s
7989:	learn: 0.0014111	total: 13m 20s	remaining: 3m 21s
7387:	learn: 0.0013670	total: 13m 20s	remaining: 4m 43s
7763:	learn: 0.0017264	total: 13m 20s	remaining: 3m 50s
8129:	learn: 0.0014376	total: 13m 20s	remaining: 3m 4s
7988:	learn: 0.0015041	total: 13m 20s	remaining: 3m 21s
7990:	learn: 0.0014111	total: 13m 20s	remaining: 3m 21s
7764:	learn: 0.0017258	total: 13m 20s	remaining: 3m 50s
7388:	learn: 0.0013670	total: 13m 20s	remaining: 4m 42s
8130:	learn: 0.0014376	total: 13m 20s	remaining: 3m 4s
7989:	learn: 0.0015041	total: 13m 20s	remaining: 3m 21s
7389:	learn: 0.0013670	total: 13m 20s	remaining: 4m 42s
7991:	learn: 0.0014111	total: 13m 20s	remaining: 3m 21s
7765:	learn: 0.0017258	total: 13m 21s	remaining: 3m 50s
8131:	learn: 0.0014376	total: 13m 20s	remaining: 3m 3s
7990:	learn: 0.0015041	total: 13m 20s	remaining: 3m 21s
7390:	learn: 0.0013670	total: 13m 21s	remaining: 4m 42s
7992:	learn: 0.0014111	total: 13m 21s	remaining: 3m 21s
7766:	learn: 0.0017254	total: 13m 21s	remaining: 3m 50s
7991:	learn: 0.0015041	total: 13m 20s	remaining: 3m 21s
8132:	learn: 0.0014376	total: 13m 20s	remaining: 3m 3s
7391:	learn: 0.0013670	total: 13m 21s	remaining: 4m 42s
7993:	learn: 0.0014111	total: 13m 21s	remaining: 3m 21s
7767:	learn: 0.0017248	total: 13m 21s	remaining: 3m 50s
7992:	learn: 0.0015041	total: 13m 20s	remaining: 3m 21s
8133:	learn: 0.0014376	total: 13m 21s	remaining: 3m 3s
7392:	learn: 0.0013670	total: 13m 21s	remaining: 4m 42s
7994:	learn: 0.0014111	total: 13m 21s	remaining: 3m 20s
7768:	learn: 0.0017245	total: 13m 21s	remaining: 3m 50s
7993:	learn: 0.0015041	total: 13m 21s	remaining: 3m 21s
8134:	learn: 0.0014376	total: 13m 21s	remaining: 3m 3s
7995:	learn: 0.0014111	total: 13m 21s	remaining: 3m 20s
7393:	learn: 0.0013670	total: 13m 21s	remaining: 4m 42s
7994:	learn: 0.0015041	total: 13m 21s	remaining: 3m 20s
7769:	learn: 0.0017241	total: 13m 21s	remaining: 3m 50s
8135:	learn: 0.0014376	total: 13m 21s	remaining: 3m 3s
7996:	learn: 0.0014111	total: 13m 21s	remaining: 3m 20s
7394:	learn: 0.0013667	total: 13m 21s	remaining: 4m 42s
7770:	learn: 0.0017237	total: 13m 21s	remaining: 3m 49s
7995:	learn: 0.0015041	total: 13m 21s	remaining: 3m 20s
7997:	learn: 0.0014111	total: 13m 21s	remaining: 3m 20s
8136:	learn: 0.0014376	total: 13m 21s	remaining: 3m 3s
7395:	learn: 0.0013667	total: 13m 21s	remaining: 4m 42s
7996:	learn: 0.0015041	total: 13m 21s	remaining: 3m 20s
7771:	learn: 0.0017232	total: 13m 21s	remaining: 3m 49s
8137:	learn: 0.0014376	total: 13m 21s	remaining: 3m 3s
7396:	learn: 0.0013667	total: 13m 21s	remaining: 4m 42s
7998:	learn: 0.0014111	total: 13m 21s	remaining: 3m 20s
7997:	learn: 0.0015041	total: 13m 21s	remaining: 3m 20s
8138:	learn: 0.0014376	total: 13m 21s	remaining: 3m 3s
7772:	learn: 0.0017228	total: 13m 21s	remaining: 3m 49s
7999:	learn: 0.0014111	total: 13m 21s	remaining: 3m 20s
7397:	learn: 0.0013667	total: 13m 21s	remaining: 4m 41s
8139:	learn: 0.0014376	total: 13m 21s	remaining: 3m 3s
7998:	learn: 0.0015041	total: 13m 21s	remaining: 3m 20s
7773:	learn: 0.0017223	total: 13m 21s	remaining: 3m 49s
8000:	learn: 0.0014111	total: 13m 21s	remaining: 3m 20s
8140:	learn: 0.0014376	total: 13m 21s	remaining: 3m 3s
7999:	learn: 0.0015041	total: 13m 21s	remaining: 3m 20s
7398:	learn: 0.0013667	total: 13m 21s	remaining: 4m 41s
7774:	learn: 0.0017222	total: 13m 21s	remaining: 3m 49s
8001:	learn: 0.0014108	total: 13m 21s	remaining: 3m 20s
8141:	learn: 0.0014376	total: 13m 21s	remaining: 3m 2s
8000:	learn: 0.0015041	total: 13m 21s	remaining: 3m 20s
8002:	learn: 0.0014105	total: 13m 21s	remaining: 3m 20s
7399:	learn: 0.0013667	total: 13m 22s	remaining: 4m 41s
7775:	learn: 0.0017217	total: 13m 22s	remaining: 3m 49s
8142:	learn: 0.0014376	total: 13m 21s	remaining: 3m 2s
8001:	learn: 0.0015041	total: 13m 21s	remaining: 3m 20s
8003:	learn: 0.0014101	total: 13m 22s	remaining: 3m 20s
7400:	learn: 0.0013664	total: 13m 22s	remaining: 4m 41s
7776:	learn: 0.0017217	total: 13m 22s	remaining: 3m 49s
8143:	learn: 0.0014376	total: 13m 22s	remaining: 3m 2s
8002:	learn: 0.0015041	total: 13m 21s	remaining: 3m 20s
8004:	learn: 0.0014101	total: 13m 22s	remaining: 3m 19s
7401:	learn: 0.0013664	total: 13m 22s	remaining: 4m 41s
7777:	learn: 0.0017213	total: 13m 22s	remaining: 3m 49s
8003:	learn: 0.0015041	total: 13m 22s	remaining: 3m 20s
8144:	learn: 0.0014376	total: 13m 22s	remaining: 3m 2s
8005:	learn: 0.0014101	total: 13m 22s	remaining: 3m 19s
7778:	learn: 0.0017206	total: 13m 22s	remaining: 3m 49s
8004:	learn: 0.0015041	total: 13m 22s	remaining: 3m 19s
7402:	learn: 0.0013664	total: 13m 22s	remaining: 4m 41s
8145:	learn: 0.0014376	total: 13m 22s	remaining: 3m 2s
8006:	learn: 0.0014101	total: 13m 22s	remaining: 3m 19s
8005:	learn: 0.0015041	total: 13m 22s	remaining: 3m 19s
7779:	learn: 0.0017202	total: 13m 22s	remaining: 3m 48s
8146:	learn: 0.0014376	total: 13m 22s	remaining: 3m 2s
8007:	learn: 0.0014101	total: 13m 22s	remaining: 3m 19s
8006:	learn: 0.0015041	total: 13m 22s	remaining: 3m 19s
7403:	learn: 0.0013664	total: 13m 22s	remaining: 4m 41s
8147:	learn: 0.0014376	total: 13m 22s	remaining: 3m 2s
7780:	learn: 0.0017197	total: 13m 22s	remaining: 3m 48s
8007:	learn: 0.0015041	total: 13m 22s	remaining: 3m 19s
8008:	learn: 0.0014101	total: 13m 22s	remaining: 3m 19s
7404:	learn: 0.0013664	total: 13m 22s	remaining: 4m 41s
8148:	learn: 0.0014376	total: 13m 22s	remaining: 3m 2s
7781:	learn: 0.0017190	total: 13m 22s	remaining: 3m 48s
8008:	learn: 0.0015036	total: 13m 22s	remaining: 3m 19s
8009:	learn: 0.0014097	total: 13m 22s	remaining: 3m 19s
7405:	learn: 0.0013664	total: 13m 22s	remaining: 4m 41s
8149:	learn: 0.0014376	total: 13m 22s	remaining: 3m 2s
7782:	learn: 0.0017184	total: 13m 22s	remaining: 3m 48s
8010:	learn: 0.0014092	total: 13m 22s	remaining: 3m 19s
8009:	learn: 0.0015036	total: 13m 22s	remaining: 3m 19s
7406:	learn: 0.0013664	total: 13m 22s	remaining: 4m 41s
8010:	learn: 0.0015036	total: 13m 22s	remaining: 3m 19s
7783:	learn: 0.0017184	total: 13m 22s	remaining: 3m 48s
8150:	learn: 0.0014370	total: 13m 22s	remaining: 3m 2s
8011:	learn: 0.0014089	total: 13m 22s	remaining: 3m 19s
7407:	learn: 0.0013664	total: 13m 22s	remaining: 4m 40s
7784:	learn: 0.0017184	total: 13m 22s	remaining: 3m 48s
8011:	learn: 0.0015036	total: 13m 22s	remaining: 3m 19s
8151:	learn: 0.0014370	total: 13m 22s	remaining: 3m 2s
7785:	learn: 0.0017184	total: 13m 23s	remaining: 3m 48s
8012:	learn: 0.0014089	total: 13m 22s	remaining: 3m 19s
8012:	learn: 0.0015036	total: 13m 22s	remaining: 3m 19s
7408:	learn: 0.0013664	total: 13m 23s	remaining: 4m 40s
8013:	learn: 0.0014085	total: 13m 23s	remaining: 3m 19s
8152:	learn: 0.0014370	total: 13m 22s	remaining: 3m 1s
7786:	learn: 0.0017179	total: 13m 23s	remaining: 3m 48s
8013:	learn: 0.0015036	total: 13m 22s	remaining: 3m 18s
7409:	learn: 0.0013664	total: 13m 23s	remaining: 4m 40s
8014:	learn: 0.0014080	total: 13m 23s	remaining: 3m 18s
8153:	learn: 0.0014370	total: 13m 23s	remaining: 3m 1s
7787:	learn: 0.0017176	total: 13m 23s	remaining: 3m 48s
8015:	learn: 0.0014080	total: 13m 23s	remaining: 3m 18s
8014:	learn: 0.0015036	total: 13m 22s	remaining: 3m 18s

7410:	learn: 0.0013664	total: 13m 23s	remaining: 4m 40s
8154:	learn: 0.0014369	total: 13m 23s	remaining: 3m 1s
8016:	learn: 0.0014077	total: 13m 23s	remaining: 3m 18s
8015:	learn: 0.0015036	total: 13m 23s	remaining: 3m 18s
7788:	learn: 0.0017171	total: 13m 23s	remaining: 3m 48s
8017:	learn: 0.0014077	total: 13m 23s	remaining: 3m 18s
7411:	learn: 0.0013664	total: 13m 23s	remaining: 4m 40s
8155:	learn: 0.0014370	total: 13m 23s	remaining: 3m 1s
8016:	learn: 0.0015036	total: 13m 23s	remaining: 3m 18s
7789:	learn: 0.0017171	total: 13m 23s	remaining: 3m 47s
7412:	learn: 0.0013664	total: 13m 23s	remaining: 4m 40s
8018:	learn: 0.0014077	total: 13m 23s	remaining: 3m 18s
8156:	learn: 0.0014365	total: 13m 23s	remaining: 3m 1s
8017:	learn: 0.0015036	total: 13m 23s	remaining: 3m 18s
7790:	learn: 0.0017168	total: 13m 23s	remaining: 3m 47s
8157:	learn: 0.0014364	total: 13m 23s	remaining: 3m 1s
7413:	learn: 0.0013664	total: 13m 23s	remaining: 4m 40s
8019:	learn: 0.0014077	total: 13m 23s	remaining: 3m 18s
8018:	learn: 0.0015036	total: 13m 23s	remaining: 3m 18s
8158:	learn: 0.0014364	total: 13m 23s	remaining: 3m 1s
7791:	learn: 0.0017168	total: 13m 23s	remaining: 3m 47s
7414:	learn: 0.0013664	total: 13m 23s	remaining: 4m 40s
8019:	learn: 0.0015036	total: 13m 23s	remaining: 3m 18s
8159:	learn: 0.0014360	total: 13m 23s	remaining: 3m 1s
8020:	learn: 0.0014077	total: 13m 23s	remaining: 3m 18s
7792:	learn: 0.0017162	total: 13m 23s	remaining: 3m 47s
8160:	learn: 0.0014359	total: 13m 23s	remaining: 3m 1s
7415:	learn: 0.0013664	total: 13m 23s	remaining: 4m 40s
8020:	learn: 0.0015036	total: 13m 23s	remaining: 3m 18s
8021:	learn: 0.0014077	total: 13m 23s	remaining: 3m 18s
7793:	learn: 0.0017162	total: 13m 23s	remaining: 3m 47s
7416:	learn: 0.0013664	total: 13m 23s	remaining: 4m 39s
8161:	learn: 0.0014359	total: 13m 23s	remaining: 3m 1s
8021:	learn: 0.0015036	total: 13m 23s	remaining: 3m 18s
8022:	learn: 0.0014077	total: 13m 23s	remaining: 3m 18s
7794:	learn: 0.0017155	total: 13m 23s	remaining: 3m 47s
7417:	learn: 0.0013664	total: 13m 23s	remaining: 4m 39s
8162:	learn: 0.0014355	total: 13m 23s	remaining: 3m
8023:	learn: 0.0014077	total: 13m 24s	remaining: 3m 18s
8022:	learn: 0.0015036	total: 13m 23s	remaining: 3m 18s
7795:	learn: 0.0017151	total: 13m 24s	remaining: 3m 47s
7418:	learn: 0.0013664	total: 13m 24s	remaining: 4m 39s
8163:	learn: 0.0014350	total: 13m 23s	remaining: 3m
8024:	learn: 0.0014077	total: 13m 24s	remaining: 3m 17s
8023:	learn: 0.0015033	total: 13m 23s	remaining: 3m 17s
7796:	learn: 0.0017146	total: 13m 24s	remaining: 3m 47s
7419:	learn: 0.0013663	total: 13m 24s	remaining: 4m 39s
8164:	learn: 0.0014350	total: 13m 24s	remaining: 3m
8025:	learn: 0.0014077	total: 13m 24s	remaining: 3m 17s
8024:	learn: 0.0015033	total: 13m 24s	remaining: 3m 17s
7797:	learn: 0.0017146	total: 13m 24s	remaining: 3m 47s
8165:	learn: 0.0014350	total: 13m 24s	remaining: 3m
7420:	learn: 0.0013663	total: 13m 24s	remaining: 4m 39s
8026:	learn: 0.0014077	total: 13m 24s	remaining: 3m 17s
8025:	learn: 0.0015033	total: 13m 24s	remaining: 3m 17s
7798:	learn: 0.0017142	total: 13m 24s	remaining: 3m 47s
8166:	learn: 0.0014350	total: 13m 24s	remaining: 3m
7421:	learn: 0.0013663	total: 13m 24s	remaining: 4m 39s
8026:	learn: 0.0015033	total: 13m 24s	remaining: 3m 17s
8167:	learn: 0.0014350	total: 13m 24s	remaining: 3m
7799:	learn: 0.0017136	total: 13m 24s	remaining: 3m 46s
8027:	learn: 0.0014077	total: 13m 24s	remaining: 3m 17s
7422:	learn: 0.0013663	total: 13m 24s	remaining: 4m 39s
8168:	learn: 0.0014350	total: 13m 24s	remaining: 3m
8027:	learn: 0.0015033	total: 13m 24s	remaining: 3m 17s
7800:	learn: 0.0017128	total: 13m 24s	remaining: 3m 46s
8028:	learn: 0.0014077	total: 13m 24s	remaining: 3m 17s
7423:	learn: 0.0013663	total: 13m 24s	remaining: 4m 39s
8169:	learn: 0.0014350	total: 13m 24s	remaining: 3m
8028:	learn: 0.0015033	total: 13m 24s	remaining: 3m 17s
7801:	learn: 0.0017122	total: 13m 24s	remaining: 3m 46s
8029:	learn: 0.0014077	total: 13m 24s	remaining: 3m 17s
7424:	learn: 0.0013663	total: 13m 24s	remaining: 4m 39s
8170:	learn: 0.0014350	total: 13m 24s	remaining: 3m
8029:	learn: 0.0015032	total: 13m 24s	remaining: 3m 17s
7802:	learn: 0.0017115	total: 13m 24s	remaining: 3m 46s
8030:	learn: 0.0014077	total: 13m 24s	remaining: 3m 17s
8171:	learn: 0.0014346	total: 13m 24s	remaining: 2m 59s
7425:	learn: 0.0013663	total: 13m 24s	remaining: 4m 38s
7803:	learn: 0.0017113	total: 13m 24s	remaining: 3m 46s
8031:	learn: 0.0014074	total: 13m 24s	remaining: 3m 17s
8030:	learn: 0.0015033	total: 13m 24s	remaining: 3m 17s
8172:	learn: 0.0014343	total: 13m 24s	remaining: 2m 59s
7804:	learn: 0.0017106	total: 13m 24s	remaining: 3m 46s
7426:	learn: 0.0013663	total: 13m 24s	remaining: 4m 38s
8031:	learn: 0.0015032	total: 13m 24s	remaining: 3m 17s
8032:	learn: 0.0014074	total: 13m 24s	remaining: 3m 17s
8173:	learn: 0.0014343	total: 13m 24s	remaining: 2m 59s
7805:	learn: 0.0017102	total: 13m 25s	remaining: 3m 46s
7427:	learn: 0.0013663	total: 13m 25s	remaining: 4m 38s
8032:	learn: 0.0015033	total: 13m 24s	remaining: 3m 17s
8033:	learn: 0.0014074	total: 13m 25s	remaining: 3m 17s
8174:	learn: 0.0014343	total: 13m 24s	remaining: 2m 59s
7428:	learn: 0.0013663	total: 13m 25s	remaining: 4m 38s
8033:	learn: 0.0015033	total: 13m 24s	remaining: 3m 16s
8175:	learn: 0.0014343	total: 13m 25s	remaining: 2m 59s
8034:	learn: 0.0014074	total: 13m 25s	remaining: 3m 16s
7806:	learn: 0.0017102	total: 13m 25s	remaining: 3m 46s
8176:	learn: 0.0014343	total: 13m 25s	remaining: 2m 59s
8035:	learn: 0.0014074	total: 13m 25s	remaining: 3m 16s
7429:	learn: 0.0013663	total: 13m 25s	remaining: 4m 38s
8034:	learn: 0.0015033	total: 13m 25s	remaining: 3m 16s
7807:	learn: 0.0017096	total: 13m 25s	remaining: 3m 46s
8177:	learn: 0.0014343	total: 13m 25s	remaining: 2m 59s
8036:	learn: 0.0014074	total: 13m 25s	remaining: 3m 16s
8035:	learn: 0.0015029	total: 13m 25s	remaining: 3m 16s
7808:	learn: 0.0017096	total: 13m 25s	remaining: 3m 45s
7430:	learn: 0.0013663	total: 13m 25s	remaining: 4m 38s
8178:	learn: 0.0014343	total: 13m 25s	remaining: 2m 59s
8037:	learn: 0.0014074	total: 13m 25s	remaining: 3m 16s
8036:	learn: 0.0015029	total: 13m 25s	remaining: 3m 16s
8179:	learn: 0.0014343	total: 13m 25s	remaining: 2m 59s
7809:	learn: 0.0017089	total: 13m 25s	remaining: 3m 45s
7431:	learn: 0.0013663	total: 13m 25s	remaining: 4m 38s
8038:	learn: 0.0014074	total: 13m 25s	remaining: 3m 16s
8037:	learn: 0.0015029	total: 13m 25s	remaining: 3m 16s
8180:	learn: 0.0014343	total: 13m 25s	remaining: 2m 59s
8039:	learn: 0.0014074	total: 13m 25s	remaining: 3m 16s
7432:	learn: 0.0013663	total: 13m 25s	remaining: 4m 38s
7810:	learn: 0.0017085	total: 13m 25s	remaining: 3m 45s
8038:	learn: 0.0015029	total: 13m 25s	remaining: 3m 16s
8181:	learn: 0.0014343	total: 13m 25s	remaining: 2m 58s
8040:	learn: 0.0014074	total: 13m 25s	remaining: 3m 16s
7811:	learn: 0.0017078	total: 13m 25s	remaining: 3m 45s
7433:	learn: 0.0013663	total: 13m 25s	remaining: 4m 38s
8039:	learn: 0.0015029	total: 13m 25s	remaining: 3m 16s
8041:	learn: 0.0014074	total: 13m 25s	remaining: 3m 16s
8182:	learn: 0.0014343	total: 13m 25s	remaining: 2m 58s
8040:	learn: 0.0015029	total: 13m 25s	remaining: 3m 16s
7434:	learn: 0.0013663	total: 13m 25s	remaining: 4m 38s
7812:	learn: 0.0017074	total: 13m 25s	remaining: 3m 45s
8183:	learn: 0.0014343	total: 13m 25s	remaining: 2m 58s
8042:	learn: 0.0014074	total: 13m 25s	remaining: 3m 16s
7435:	learn: 0.0013663	total: 13m 25s	remaining: 4m 37s
8041:	learn: 0.0015025	total: 13m 25s	remaining: 3m 16s
8184:	learn: 0.0014337	total: 13m 25s	remaining: 2m 58s
7813:	learn: 0.0017070	total: 13m 26s	remaining: 3m 45s
8043:	learn: 0.0014074	total: 13m 25s	remaining: 3m 15s
7436:	learn: 0.0013663	total: 13m 26s	remaining: 4m 37s
8042:	learn: 0.0015025	total: 13m 25s	remaining: 3m 16s
7814:	learn: 0.0017064	total: 13m 26s	remaining: 3m 45s
8185:	learn: 0.0014337	total: 13m 25s	remaining: 2m 58s
8044:	learn: 0.0014074	total: 13m 26s	remaining: 3m 15s
7815:	learn: 0.0017064	total: 13m 26s	remaining: 3m 45s
7437:	learn: 0.0013663	total: 13m 26s	remaining: 4m 37s
8043:	learn: 0.0015025	total: 13m 25s	remaining: 3m 15s
8186:	learn: 0.0014337	total: 13m 26s	remaining: 2m 58s
7816:	learn: 0.0017060	total: 13m 26s	remaining: 3m 45s
8045:	learn: 0.0014069	total: 13m 26s	remaining: 3m 15s
8044:	learn: 0.0015024	total: 13m 26s	remaining: 3m 15s
7438:	learn: 0.0013663	total: 13m 26s	remaining: 4m 37s
8187:	learn: 0.0014337	total: 13m 26s	remaining: 2m 58s
8045:	learn: 0.0015025	total: 13m 26s	remaining: 3m 15s
7817:	learn: 0.0017054	total: 13m 26s	remaining: 3m 45s
8046:	learn: 0.0014069	total: 13m 26s	remaining: 3m 15s
7439:	learn: 0.0013663	total: 13m 26s	remaining: 4m 37s
8188:	learn: 0.0014337	total: 13m 26s	remaining: 2m 58s
7818:	learn: 0.0017048	total: 13m 26s	remaining: 3m 44s
8046:	learn: 0.0015021	total: 13m 26s	remaining: 3m 15s
8047:	learn: 0.0014069	total: 13m 26s	remaining: 3m 15s
7440:	learn: 0.0013663	total: 13m 26s	remaining: 4m 37s
8189:	learn: 0.0014335	total: 13m 26s	remaining: 2m 58s
8047:	learn: 0.0015021	total: 13m 26s	remaining: 3m 15s
7819:	learn: 0.0017042	total: 13m 26s	remaining: 3m 44s
8048:	learn: 0.0014069	total: 13m 26s	remaining: 3m 15s
7441:	learn: 0.0013663	total: 13m 26s	remaining: 4m 37s
8190:	learn: 0.0014330	total: 13m 26s	remaining: 2m 58s
8048:	learn: 0.0015021	total: 13m 26s	remaining: 3m 15s
8049:	learn: 0.0014069	total: 13m 26s	remaining: 3m 15s
7820:	learn: 0.0017042	total: 13m 26s	remaining: 3m 44s
8191:	learn: 0.0014330	total: 13m 26s	remaining: 2m 58s
8050:	learn: 0.0014069	total: 13m 26s	remaining: 3m 15s
7442:	learn: 0.0013663	total: 13m 26s	remaining: 4m 37s
7821:	learn: 0.0017038	total: 13m 26s	remaining: 3m 44s
8049:	learn: 0.0015021	total: 13m 26s	remaining: 3m 15s
8192:	learn: 0.0014330	total: 13m 26s	remaining: 2m 57s
7443:	learn: 0.0013663	total: 13m 26s	remaining: 4m 37s
8051:	learn: 0.0014069	total: 13m 26s	remaining: 3m 15s
7822:	learn: 0.0017034	total: 13m 26s	remaining: 3m 44s
8193:	learn: 0.0014330	total: 13m 26s	remaining: 2m 57s
8050:	learn: 0.0015021	total: 13m 26s	remaining: 3m 15s
7444:	learn: 0.0013663	total: 13m 26s	remaining: 4m 36s
8052:	learn: 0.0014069	total: 13m 26s	remaining: 3m 15s
7823:	learn: 0.0017029	total: 13m 26s	remaining: 3m 44s
8051:	learn: 0.0015021	total: 13m 26s	remaining: 3m 15s
8194:	learn: 0.0014325	total: 13m 26s	remaining: 2m 57s
7824:	learn: 0.0017026	total: 13m 27s	remaining: 3m 44s
7445:	learn: 0.0013663	total: 13m 27s	remaining: 4m 36s
8053:	learn: 0.0014069	total: 13m 26s	remaining: 3m 14s
8052:	learn: 0.0015021	total: 13m 26s	remaining: 3m 15s
8195:	learn: 0.0014320	total: 13m 26s	remaining: 2m 57s
7825:	learn: 0.0017019	total: 13m 27s	remaining: 3m 44s
8054:	learn: 0.0014069	total: 13m 27s	remaining: 3m 14s
7446:	learn: 0.0013663	total: 13m 27s	remaining: 4m 36s
8053:	learn: 0.0015021	total: 13m 26s	remaining: 3m 14s
8196:	learn: 0.0014320	total: 13m 27s	remaining: 2m 57s
7826:	learn: 0.0017015	total: 13m 27s	remaining: 3m 44s
7447:	learn: 0.0013663	total: 13m 27s	remaining: 4m 36s
8055:	learn: 0.0014069	total: 13m 27s	remaining: 3m 14s
8054:	learn: 0.0015021	total: 13m 27s	remaining: 3m 14s
8197:	learn: 0.0014316	total: 13m 27s	remaining: 2m 57s
7448:	learn: 0.0013663	total: 13m 27s	remaining: 4m 36s
7827:	learn: 0.0017011	total: 13m 27s	remaining: 3m 44s
8056:	learn: 0.0014069	total: 13m 27s	remaining: 3m 14s
8198:	learn: 0.0014316	total: 13m 27s	remaining: 2m 57s
8055:	learn: 0.0015021	total: 13m 27s	remaining: 3m 14s
7449:	learn: 0.0013663	total: 13m 27s	remaining: 4m 36s
7828:	learn: 0.0017007	total: 13m 27s	remaining: 3m 43s
8057:	learn: 0.0014069	total: 13m 27s	remaining: 3m 14s
8199:	learn: 0.0014316	total: 13m 27s	remaining: 2m 57s
8056:	learn: 0.0015021	total: 13m 27s	remaining: 3m 14s
7829:	learn: 0.0017001	total: 13m 27s	remaining: 3m 43s
7450:	learn: 0.0013663	total: 13m 27s	remaining: 4m 36s
8058:	learn: 0.0014069	total: 13m 27s	remaining: 3m 14s
8200:	learn: 0.0014316	total: 13m 27s	remaining: 2m 57s
8057:	learn: 0.0015021	total: 13m 27s	remaining: 3m 14s
7451:	learn: 0.0013663	total: 13m 27s	remaining: 4m 36s
7830:	learn: 0.0017001	total: 13m 27s	remaining: 3m 43s
8059:	learn: 0.0014069	total: 13m 27s	remaining: 3m 14s
8201:	learn: 0.0014316	total: 13m 27s	remaining: 2m 57s
8058:	learn: 0.0015021	total: 13m 27s	remaining: 3m 14s
7452:	learn: 0.0013663	total: 13m 27s	remaining: 4m 36s
7831:	learn: 0.0016998	total: 13m 27s	remaining: 3m 43s
8202:	learn: 0.0014316	total: 13m 27s	remaining: 2m 56s
8060:	learn: 0.0014069	total: 13m 27s	remaining: 3m 14s
8059:	learn: 0.0015021	total: 13m 27s	remaining: 3m 14s
7453:	learn: 0.0013663	total: 13m 27s	remaining: 4m 35s
8061:	learn: 0.0014069	total: 13m 27s	remaining: 3m 14s
7832:	learn: 0.0016992	total: 13m 27s	remaining: 3m 43s
8203:	learn: 0.0014316	total: 13m 27s	remaining: 2m 56s
7454:	learn: 0.0013663	total: 13m 27s	remaining: 4m 35s
8060:	learn: 0.0015021	total: 13m 27s	remaining: 3m 14s
8062:	learn: 0.0014069	total: 13m 27s	remaining: 3m 14s
8204:	learn: 0.0014316	total: 13m 27s	remaining: 2m 56s
7833:	learn: 0.0016986	total: 13m 27s	remaining: 3m 43s
8061:	learn: 0.0015021	total: 13m 27s	remaining: 3m 14s
7455:	learn: 0.0013663	total: 13m 27s	remaining: 4m 35s
8205:	learn: 0.0014316	total: 13m 27s	remaining: 2m 56s
8063:	learn: 0.0014069	total: 13m 28s	remaining: 3m 13s
7834:	learn: 0.0016982	total: 13m 28s	remaining: 3m 43s
8206:	learn: 0.0014315	total: 13m 27s	remaining: 2m 56s
8062:	learn: 0.0015021	total: 13m 27s	remaining: 3m 14s
8064:	learn: 0.0014069	total: 13m 28s	remaining: 3m 13s
7456:	learn: 0.0013663	total: 13m 28s	remaining: 4m 35s
7835:	learn: 0.0016979	total: 13m 28s	remaining: 3m 43s
8063:	learn: 0.0015021	total: 13m 27s	remaining: 3m 13s
8207:	learn: 0.0014311	total: 13m 28s	remaining: 2m 56s
8065:	learn: 0.0014064	total: 13m 28s	remaining: 3m 13s
7836:	learn: 0.0016974	total: 13m 28s	remaining: 3m 43s
7457:	learn: 0.0013663	total: 13m 28s	remaining: 4m 35s
8208:	learn: 0.0014311	total: 13m 28s	remaining: 2m 56s
8064:	learn: 0.0015021	total: 13m 28s	remaining: 3m 13s
8066:	learn: 0.0014064	total: 13m 28s	remaining: 3m 13s
7837:	learn: 0.0016969	total: 13m 28s	remaining: 3m 42s
8209:	learn: 0.0014311	total: 13m 28s	remaining: 2m 56s
8065:	learn: 0.0015021	total: 13m 28s	remaining: 3m 13s
7458:	learn: 0.0013663	total: 13m 28s	remaining: 4m 35s
8067:	learn: 0.0014064	total: 13m 28s	remaining: 3m 13s
8210:	learn: 0.0014311	total: 13m 28s	remaining: 2m 56s
8066:	learn: 0.0015021	total: 13m 28s	remaining: 3m 13s
7838:	learn: 0.0016964	total: 13m 28s	remaining: 3m 42s
7459:	learn: 0.0013662	total: 13m 28s	remaining: 4m 35s
8068:	learn: 0.0014064	total: 13m 28s	remaining: 3m 13s
8067:	learn: 0.0015021	total: 13m 28s	remaining: 3m 13s
8211:	learn: 0.0014311	total: 13m 28s	remaining: 2m 56s
7460:	learn: 0.0013660	total: 13m 28s	remaining: 4m 35s
7839:	learn: 0.0016964	total: 13m 28s	remaining: 3m 42s
8068:	learn: 0.0015021	total: 13m 28s	remaining: 3m 13s
8069:	learn: 0.0014064	total: 13m 28s	remaining: 3m 13s
7461:	learn: 0.0013660	total: 13m 28s	remaining: 4m 35s
8212:	learn: 0.0014311	total: 13m 28s	remaining: 2m 55s
7840:	learn: 0.0016958	total: 13m 28s	remaining: 3m 42s
8070:	learn: 0.0014064	total: 13m 28s	remaining: 3m 13s
8069:	learn: 0.0015021	total: 13m 28s	remaining: 3m 13s
8213:	learn: 0.0014311	total: 13m 28s	remaining: 2m 55s
7462:	learn: 0.0013658	total: 13m 28s	remaining: 4m 34s
8071:	learn: 0.0014064	total: 13m 28s	remaining: 3m 13s
7841:	learn: 0.0016953	total: 13m 28s	remaining: 3m 42s
8070:	learn: 0.0015021	total: 13m 28s	remaining: 3m 13s
8214:	learn: 0.0014311	total: 13m 28s	remaining: 2m 55s
7463:	learn: 0.0013658	total: 13m 28s	remaining: 4m 34s
8072:	learn: 0.0014064	total: 13m 28s	remaining: 3m 13s
7842:	learn: 0.0016948	total: 13m 28s	remaining: 3m 42s
8071:	learn: 0.0015021	total: 13m 28s	remaining: 3m 13s
8215:	learn: 0.0014311	total: 13m 28s	remaining: 2m 55s
7464:	learn: 0.0013656	total: 13m 28s	remaining: 4m 34s
8072:	learn: 0.0015021	total: 13m 28s	remaining: 3m 13s
8073:	learn: 0.0014064	total: 13m 28s	remaining: 3m 12s
7843:	learn: 0.0016948	total: 13m 29s	remaining: 3m 42s
8216:	learn: 0.0014311	total: 13m 28s	remaining: 2m 55s
8073:	learn: 0.0015021	total: 13m 28s	remaining: 3m 12s
8074:	learn: 0.0014064	total: 13m 29s	remaining: 3m 12s
7465:	learn: 0.0013656	total: 13m 29s	remaining: 4m 34s

7844:	learn: 0.0016943	total: 13m 29s	remaining: 3m 42s
8217:	learn: 0.0014307	total: 13m 29s	remaining: 2m 55s
8074:	learn: 0.0015021	total: 13m 28s	remaining: 3m 12s
8075:	learn: 0.0014064	total: 13m 29s	remaining: 3m 12s
7845:	learn: 0.0016939	total: 13m 29s	remaining: 3m 42s
7466:	learn: 0.0013656	total: 13m 29s	remaining: 4m 34s
8218:	learn: 0.0014305	total: 13m 29s	remaining: 2m 55s
8075:	learn: 0.0015021	total: 13m 29s	remaining: 3m 12s
8076:	learn: 0.0014064	total: 13m 29s	remaining: 3m 12s
8219:	learn: 0.0014306	total: 13m 29s	remaining: 2m 55s
7846:	learn: 0.0016933	total: 13m 29s	remaining: 3m 42s
7467:	learn: 0.0013656	total: 13m 29s	remaining: 4m 34s
8077:	learn: 0.0014064	total: 13m 29s	remaining: 3m 12s
8076:	learn: 0.0015021	total: 13m 29s	remaining: 3m 12s
8220:	learn: 0.0014306	total: 13m 29s	remaining: 2m 55s
7847:	learn: 0.0016929	total: 13m 29s	remaining: 3m 41s
8078:	learn: 0.0014064	total: 13m 29s	remaining: 3m 12s
7468:	learn: 0.0013656	total: 13m 29s	remaining: 4m 34s
8077:	learn: 0.0015021	total: 13m 29s	remaining: 3m 12s
8221:	learn: 0.0014306	total: 13m 29s	remaining: 2m 55s
8079:	learn: 0.0014064	total: 13m 29s	remaining: 3m 12s
7848:	learn: 0.0016925	total: 13m 29s	remaining: 3m 41s
7469:	learn: 0.0013656	total: 13m 29s	remaining: 4m 34s
8078:	learn: 0.0015021	total: 13m 29s	remaining: 3m 12s
8080:	learn: 0.0014064	total: 13m 29s	remaining: 3m 12s
8222:	learn: 0.0014305	total: 13m 29s	remaining: 2m 54s
7849:	learn: 0.0016919	total: 13m 29s	remaining: 3m 41s
7470:	learn: 0.0013656	total: 13m 29s	remaining: 4m 34s
8081:	learn: 0.0014064	total: 13m 29s	remaining: 3m 12s
8079:	learn: 0.0015021	total: 13m 29s	remaining: 3m 12s
8223:	learn: 0.0014305	total: 13m 29s	remaining: 2m 54s
7850:	learn: 0.0016915	total: 13m 29s	remaining: 3m 41s
8080:	learn: 0.0015021	total: 13m 29s	remaining: 3m 12s
7471:	learn: 0.0013656	total: 13m 29s	remaining: 4m 33s
8082:	learn: 0.0014064	total: 13m 29s	remaining: 3m 12s
7851:	learn: 0.0016909	total: 13m 29s	remaining: 3m 41s
8224:	learn: 0.0014305	total: 13m 29s	remaining: 2m 54s
8081:	learn: 0.0015021	total: 13m 29s	remaining: 3m 12s
7852:	learn: 0.0016904	total: 13m 29s	remaining: 3m 41s
8083:	learn: 0.0014064	total: 13m 29s	remaining: 3m 11s
7472:	learn: 0.0013656	total: 13m 29s	remaining: 4m 33s
8225:	learn: 0.0014305	total: 13m 29s	remaining: 2m 54s
8082:	learn: 0.0015021	total: 13m 29s	remaining: 3m 12s
8084:	learn: 0.0014064	total: 13m 29s	remaining: 3m 11s
7853:	learn: 0.0016900	total: 13m 30s	remaining: 3m 41s
7473:	learn: 0.0013656	total: 13m 30s	remaining: 4m 33s
8226:	learn: 0.0014302	total: 13m 29s	remaining: 2m 54s
8085:	learn: 0.0014064	total: 13m 30s	remaining: 3m 11s
8083:	learn: 0.0015021	total: 13m 29s	remaining: 3m 11s
7854:	learn: 0.0016895	total: 13m 30s	remaining: 3m 41s
8227:	learn: 0.0014302	total: 13m 29s	remaining: 2m 54s
7474:	learn: 0.0013656	total: 13m 30s	remaining: 4m 33s
8086:	learn: 0.0014064	total: 13m 30s	remaining: 3m 11s
8084:	learn: 0.0015021	total: 13m 29s	remaining: 3m 11s
8228:	learn: 0.0014301	total: 13m 30s	remaining: 2m 54s
7475:	learn: 0.0013656	total: 13m 30s	remaining: 4m 33s
7855:	learn: 0.0016891	total: 13m 30s	remaining: 3m 41s
8087:	learn: 0.0014064	total: 13m 30s	remaining: 3m 11s
8229:	learn: 0.0014301	total: 13m 30s	remaining: 2m 54s
8085:	learn: 0.0015021	total: 13m 30s	remaining: 3m 11s
7476:	learn: 0.0013655	total: 13m 30s	remaining: 4m 33s
7856:	learn: 0.0016884	total: 13m 30s	remaining: 3m 41s
8088:	learn: 0.0014060	total: 13m 30s	remaining: 3m 11s
8230:	learn: 0.0014296	total: 13m 30s	remaining: 2m 54s
8086:	learn: 0.0015021	total: 13m 30s	remaining: 3m 11s
7477:	learn: 0.0013655	total: 13m 30s	remaining: 4m 33s
8089:	learn: 0.0014060	total: 13m 30s	remaining: 3m 11s
7857:	learn: 0.0016883	total: 13m 30s	remaining: 3m 40s
8231:	learn: 0.0014291	total: 13m 30s	remaining: 2m 54s
8087:	learn: 0.0015021	total: 13m 30s	remaining: 3m 11s
7478:	learn: 0.0013655	total: 13m 30s	remaining: 4m 33s
8090:	learn: 0.0014060	total: 13m 30s	remaining: 3m 11s
7858:	learn: 0.0016879	total: 13m 30s	remaining: 3m 40s
8232:	learn: 0.0014291	total: 13m 30s	remaining: 2m 53s
7479:	learn: 0.0013654	total: 13m 30s	remaining: 4m 33s
8088:	learn: 0.0015021	total: 13m 30s	remaining: 3m 11s
8091:	learn: 0.0014060	total: 13m 30s	remaining: 3m 11s
8233:	learn: 0.0014291	total: 13m 30s	remaining: 2m 53s
7859:	learn: 0.0016873	total: 13m 30s	remaining: 3m 40s
8089:	learn: 0.0015021	total: 13m 30s	remaining: 3m 11s
8092:	learn: 0.0014060	total: 13m 30s	remaining: 3m 11s
7480:	learn: 0.0013654	total: 13m 30s	remaining: 4m 33s
8234:	learn: 0.0014291	total: 13m 30s	remaining: 2m 53s
7860:	learn: 0.0016867	total: 13m 30s	remaining: 3m 40s
8090:	learn: 0.0015021	total: 13m 30s	remaining: 3m 11s
8093:	learn: 0.0014060	total: 13m 30s	remaining: 3m 10s
8235:	learn: 0.0014291	total: 13m 30s	remaining: 2m 53s
7481:	learn: 0.0013651	total: 13m 30s	remaining: 4m 32s
8091:	learn: 0.0015021	total: 13m 30s	remaining: 3m 11s
7861:	learn: 0.0016864	total: 13m 30s	remaining: 3m 40s
8094:	learn: 0.0014060	total: 13m 30s	remaining: 3m 10s
8236:	learn: 0.0014291	total: 13m 30s	remaining: 2m 53s
7482:	learn: 0.0013651	total: 13m 30s	remaining: 4m 32s
7862:	learn: 0.0016859	total: 13m 31s	remaining: 3m 40s
8092:	learn: 0.0015021	total: 13m 30s	remaining: 3m 11s
8095:	learn: 0.0014060	total: 13m 31s	remaining: 3m 10s
8237:	learn: 0.0014291	total: 13m 30s	remaining: 2m 53s
7483:	learn: 0.0013651	total: 13m 31s	remaining: 4m 32s
7863:	learn: 0.0016853	total: 13m 31s	remaining: 3m 40s
8096:	learn: 0.0014060	total: 13m 31s	remaining: 3m 10s
8238:	learn: 0.0014291	total: 13m 31s	remaining: 2m 53s
7864:	learn: 0.0016848	total: 13m 31s	remaining: 3m 40s
8093:	learn: 0.0015021	total: 13m 30s	remaining: 3m 10s
7484:	learn: 0.0013651	total: 13m 31s	remaining: 4m 32s
8097:	learn: 0.0014060	total: 13m 31s	remaining: 3m 10s
8239:	learn: 0.0014291	total: 13m 31s	remaining: 2m 53s
8094:	learn: 0.0015017	total: 13m 31s	remaining: 3m 10s
7485:	learn: 0.0013651	total: 13m 31s	remaining: 4m 32s
7865:	learn: 0.0016844	total: 13m 31s	remaining: 3m 40s
8240:	learn: 0.0014291	total: 13m 31s	remaining: 2m 53s
8098:	learn: 0.0014057	total: 13m 31s	remaining: 3m 10s
7486:	learn: 0.0013651	total: 13m 31s	remaining: 4m 32s
8095:	learn: 0.0015017	total: 13m 31s	remaining: 3m 10s
7866:	learn: 0.0016838	total: 13m 31s	remaining: 3m 40s
8099:	learn: 0.0014057	total: 13m 31s	remaining: 3m 10s
8241:	learn: 0.0014291	total: 13m 31s	remaining: 2m 53s
7867:	learn: 0.0016834	total: 13m 31s	remaining: 3m 39s
8096:	learn: 0.0015017	total: 13m 31s	remaining: 3m 10s
7487:	learn: 0.0013651	total: 13m 31s	remaining: 4m 32s
8100:	learn: 0.0014056	total: 13m 31s	remaining: 3m 10s
7868:	learn: 0.0016834	total: 13m 31s	remaining: 3m 39s
8242:	learn: 0.0014291	total: 13m 31s	remaining: 2m 52s
7488:	learn: 0.0013651	total: 13m 31s	remaining: 4m 32s
8097:	learn: 0.0015017	total: 13m 31s	remaining: 3m 10s
8101:	learn: 0.0014057	total: 13m 31s	remaining: 3m 10s
8243:	learn: 0.0014291	total: 13m 31s	remaining: 2m 52s
7869:	learn: 0.0016829	total: 13m 31s	remaining: 3m 39s
7489:	learn: 0.0013651	total: 13m 31s	remaining: 4m 32s
8098:	learn: 0.0015018	total: 13m 31s	remaining: 3m 10s
8102:	learn: 0.0014056	total: 13m 31s	remaining: 3m 10s
8244:	learn: 0.0014291	total: 13m 31s	remaining: 2m 52s
7870:	learn: 0.0016824	total: 13m 31s	remaining: 3m 39s
7490:	learn: 0.0013651	total: 13m 31s	remaining: 4m 31s
8103:	learn: 0.0014056	total: 13m 31s	remaining: 3m 9s
8099:	learn: 0.0015017	total: 13m 31s	remaining: 3m 10s
7491:	learn: 0.0013651	total: 13m 31s	remaining: 4m 31s
8245:	learn: 0.0014291	total: 13m 31s	remaining: 2m 52s
7871:	learn: 0.0016824	total: 13m 31s	remaining: 3m 39s
8104:	learn: 0.0014056	total: 13m 31s	remaining: 3m 9s
8246:	learn: 0.0014291	total: 13m 31s	remaining: 2m 52s
8100:	learn: 0.0015017	total: 13m 31s	remaining: 3m 10s
7492:	learn: 0.0013651	total: 13m 31s	remaining: 4m 31s
7872:	learn: 0.0016820	total: 13m 32s	remaining: 3m 39s
8105:	learn: 0.0014056	total: 13m 31s	remaining: 3m 9s
8247:	learn: 0.0014291	total: 13m 31s	remaining: 2m 52s
8101:	learn: 0.0015017	total: 13m 31s	remaining: 3m 10s
7493:	learn: 0.0013651	total: 13m 32s	remaining: 4m 31s
7873:	learn: 0.0016820	total: 13m 32s	remaining: 3m 39s
8102:	learn: 0.0015017	total: 13m 31s	remaining: 3m 10s
8106:	learn: 0.0014056	total: 13m 32s	remaining: 3m 9s
8248:	learn: 0.0014291	total: 13m 32s	remaining: 2m 52s
7874:	learn: 0.0016815	total: 13m 32s	remaining: 3m 39s
7494:	learn: 0.0013651	total: 13m 32s	remaining: 4m 31s
8249:	learn: 0.0014288	total: 13m 32s	remaining: 2m 52s
8103:	learn: 0.0015017	total: 13m 32s	remaining: 3m 9s
8107:	learn: 0.0014056	total: 13m 32s	remaining: 3m 9s
7875:	learn: 0.0016812	total: 13m 32s	remaining: 3m 39s
8250:	learn: 0.0014288	total: 13m 32s	remaining: 2m 52s
7495:	learn: 0.0013651	total: 13m 32s	remaining: 4m 31s
8104:	learn: 0.0015017	total: 13m 32s	remaining: 3m 9s
8108:	learn: 0.0014056	total: 13m 32s	remaining: 3m 9s
8251:	learn: 0.0014288	total: 13m 32s	remaining: 2m 52s
7876:	learn: 0.0016812	total: 13m 32s	remaining: 3m 38s
7496:	learn: 0.0013651	total: 13m 32s	remaining: 4m 31s
8105:	learn: 0.0015017	total: 13m 32s	remaining: 3m 9s
8109:	learn: 0.0014056	total: 13m 32s	remaining: 3m 9s
7877:	learn: 0.0016806	total: 13m 32s	remaining: 3m 38s
8252:	learn: 0.0014288	total: 13m 32s	remaining: 2m 51s
7497:	learn: 0.0013651	total: 13m 32s	remaining: 4m 31s
8106:	learn: 0.0015017	total: 13m 32s	remaining: 3m 9s
8110:	learn: 0.0014056	total: 13m 32s	remaining: 3m 9s
8253:	learn: 0.0014288	total: 13m 32s	remaining: 2m 51s
7498:	learn: 0.0013651	total: 13m 32s	remaining: 4m 31s
7878:	learn: 0.0016802	total: 13m 32s	remaining: 3m 38s
8107:	learn: 0.0015018	total: 13m 32s	remaining: 3m 9s
8111:	learn: 0.0014056	total: 13m 32s	remaining: 3m 9s
8254:	learn: 0.0014288	total: 13m 32s	remaining: 2m 51s
7499:	learn: 0.0013651	total: 13m 32s	remaining: 4m 30s
7879:	learn: 0.0016801	total: 13m 32s	remaining: 3m 38s
8108:	learn: 0.0015014	total: 13m 32s	remaining: 3m 9s
8112:	learn: 0.0014056	total: 13m 32s	remaining: 3m 9s
8255:	learn: 0.0014288	total: 13m 32s	remaining: 2m 51s
7500:	learn: 0.0013651	total: 13m 32s	remaining: 4m 30s
7880:	learn: 0.0016797	total: 13m 32s	remaining: 3m 38s
8256:	learn: 0.0014288	total: 13m 32s	remaining: 2m 51s
8109:	learn: 0.0015014	total: 13m 32s	remaining: 3m 9s
8113:	learn: 0.0014056	total: 13m 32s	remaining: 3m 8s
7501:	learn: 0.0013651	total: 13m 32s	remaining: 4m 30s
7881:	learn: 0.0016790	total: 13m 32s	remaining: 3m 38s
8257:	learn: 0.0014288	total: 13m 32s	remaining: 2m 51s
8110:	learn: 0.0015014	total: 13m 32s	remaining: 3m 9s
8114:	learn: 0.0014056	total: 13m 32s	remaining: 3m 8s
8258:	learn: 0.0014288	total: 13m 32s	remaining: 2m 51s
7882:	learn: 0.0016790	total: 13m 33s	remaining: 3m 38s
7502:	learn: 0.0013651	total: 13m 33s	remaining: 4m 30s
8259:	learn: 0.0014288	total: 13m 32s	remaining: 2m 51s
8111:	learn: 0.0015011	total: 13m 32s	remaining: 3m 9s
8115:	learn: 0.0014056	total: 13m 33s	remaining: 3m 8s
7503:	learn: 0.0013651	total: 13m 33s	remaining: 4m 30s
7883:	learn: 0.0016784	total: 13m 33s	remaining: 3m 38s
8260:	learn: 0.0014288	total: 13m 33s	remaining: 2m 51s
8112:	learn: 0.0015011	total: 13m 32s	remaining: 3m 9s
8116:	learn: 0.0014056	total: 13m 33s	remaining: 3m 8s
7504:	learn: 0.0013651	total: 13m 33s	remaining: 4m 30s
7884:	learn: 0.0016784	total: 13m 33s	remaining: 3m 38s
8117:	learn: 0.0014056	total: 13m 33s	remaining: 3m 8s
8261:	learn: 0.0014288	total: 13m 33s	remaining: 2m 51s
8113:	learn: 0.0015011	total: 13m 33s	remaining: 3m 8s
7505:	learn: 0.0013651	total: 13m 33s	remaining: 4m 30s
7885:	learn: 0.0016779	total: 13m 33s	remaining: 3m 38s
8114:	learn: 0.0015011	total: 13m 33s	remaining: 3m 8s
8118:	learn: 0.0014056	total: 13m 33s	remaining: 3m 8s
8262:	learn: 0.0014288	total: 13m 33s	remaining: 2m 50s
7506:	learn: 0.0013651	total: 13m 33s	remaining: 4m 30s
7886:	learn: 0.0016779	total: 13m 33s	remaining: 3m 37s
8119:	learn: 0.0014056	total: 13m 33s	remaining: 3m 8s
8115:	learn: 0.0015011	total: 13m 33s	remaining: 3m 8s
8263:	learn: 0.0014288	total: 13m 33s	remaining: 2m 50s
7507:	learn: 0.0013651	total: 13m 33s	remaining: 4m 30s
7887:	learn: 0.0016774	total: 13m 33s	remaining: 3m 37s
8120:	learn: 0.0014056	total: 13m 33s	remaining: 3m 8s
8116:	learn: 0.0015011	total: 13m 33s	remaining: 3m 8s
8264:	learn: 0.0014288	total: 13m 33s	remaining: 2m 50s
7508:	learn: 0.0013651	total: 13m 33s	remaining: 4m 29s
8121:	learn: 0.0014053	total: 13m 33s	remaining: 3m 8s
7888:	learn: 0.0016773	total: 13m 33s	remaining: 3m 37s
8117:	learn: 0.0015011	total: 13m 33s	remaining: 3m 8s
8265:	learn: 0.0014288	total: 13m 33s	remaining: 2m 50s
8122:	learn: 0.0014053	total: 13m 33s	remaining: 3m 8s
7509:	learn: 0.0013651	total: 13m 33s	remaining: 4m 29s
7889:	learn: 0.0016769	total: 13m 33s	remaining: 3m 37s
8118:	learn: 0.0015011	total: 13m 33s	remaining: 3m 8s
8266:	learn: 0.0014288	total: 13m 33s	remaining: 2m 50s
8123:	learn: 0.0014053	total: 13m 33s	remaining: 3m 7s
8119:	learn: 0.0015010	total: 13m 33s	remaining: 3m 8s
7510:	learn: 0.0013651	total: 13m 33s	remaining: 4m 29s
7890:	learn: 0.0016761	total: 13m 33s	remaining: 3m 37s
8267:	learn: 0.0014288	total: 13m 33s	remaining: 2m 50s
8124:	learn: 0.0014053	total: 13m 33s	remaining: 3m 7s
7511:	learn: 0.0013651	total: 13m 33s	remaining: 4m 29s
8120:	learn: 0.0015010	total: 13m 33s	remaining: 3m 8s
8268:	learn: 0.0014288	total: 13m 33s	remaining: 2m 50s
7891:	learn: 0.0016756	total: 13m 34s	remaining: 3m 37s
7512:	learn: 0.0013651	total: 13m 34s	remaining: 4m 29s
8125:	learn: 0.0014053	total: 13m 33s	remaining: 3m 7s
8121:	learn: 0.0015010	total: 13m 33s	remaining: 3m 8s
7513:	learn: 0.0013651	total: 13m 34s	remaining: 4m 29s
8269:	learn: 0.0014283	total: 13m 33s	remaining: 2m 50s
7892:	learn: 0.0016756	total: 13m 34s	remaining: 3m 37s
8126:	learn: 0.0014053	total: 13m 34s	remaining: 3m 7s
8122:	learn: 0.0015010	total: 13m 33s	remaining: 3m 8s
7514:	learn: 0.0013651	total: 13m 34s	remaining: 4m 29s
8270:	learn: 0.0014283	total: 13m 34s	remaining: 2m 50s
7893:	learn: 0.0016752	total: 13m 34s	remaining: 3m 37s
8123:	learn: 0.0015010	total: 13m 34s	remaining: 3m 7s
8127:	learn: 0.0014053	total: 13m 34s	remaining: 3m 7s
7515:	learn: 0.0013651	total: 13m 34s	remaining: 4m 29s
7894:	learn: 0.0016747	total: 13m 34s	remaining: 3m 37s
8271:	learn: 0.0014283	total: 13m 34s	remaining: 2m 50s
8124:	learn: 0.0015010	total: 13m 34s	remaining: 3m 7s
8128:	learn: 0.0014053	total: 13m 34s	remaining: 3m 7s
7516:	learn: 0.0013651	total: 13m 34s	remaining: 4m 29s
7895:	learn: 0.0016742	total: 13m 34s	remaining: 3m 37s
8272:	learn: 0.0014283	total: 13m 34s	remaining: 2m 49s
8125:	learn: 0.0015010	total: 13m 34s	remaining: 3m 7s
7896:	learn: 0.0016742	total: 13m 34s	remaining: 3m 36s
8129:	learn: 0.0014053	total: 13m 34s	remaining: 3m 7s
8273:	learn: 0.0014283	total: 13m 34s	remaining: 2m 49s
8126:	learn: 0.0015006	total: 13m 34s	remaining: 3m 7s
7517:	learn: 0.0013651	total: 13m 34s	remaining: 4m 28s
7897:	learn: 0.0016742	total: 13m 34s	remaining: 3m 36s
8130:	learn: 0.0014049	total: 13m 34s	remaining: 3m 7s
7518:	learn: 0.0013651	total: 13m 34s	remaining: 4m 28s
8274:	learn: 0.0014283	total: 13m 34s	remaining: 2m 49s
8127:	learn: 0.0015002	total: 13m 34s	remaining: 3m 7s
7898:	learn: 0.0016738	total: 13m 34s	remaining: 3m 36s
8131:	learn: 0.0014049	total: 13m 34s	remaining: 3m 7s
8275:	learn: 0.0014283	total: 13m 34s	remaining: 2m 49s
8128:	learn: 0.0015002	total: 13m 34s	remaining: 3m 7s
7519:	learn: 0.0013648	total: 13m 34s	remaining: 4m 28s
8132:	learn: 0.0014049	total: 13m 34s	remaining: 3m 7s
7899:	learn: 0.0016738	total: 13m 34s	remaining: 3m 36s
8129:	learn: 0.0015002	total: 13m 34s	remaining: 3m 7s
7520:	learn: 0.0013648	total: 13m 34s	remaining: 4m 28s
8276:	learn: 0.0014283	total: 13m 34s	remaining: 2m 49s
8133:	learn: 0.0014049	total: 13m 34s	remaining: 3m 6s
7900:	learn: 0.0016734	total: 13m 34s	remaining: 3m 36s
8130:	learn: 0.0015002	total: 13m 34s	remaining: 3m 7s
8277:	learn: 0.0014280	total: 13m 34s	remaining: 2m 49s
7521:	learn: 0.0013648	total: 13m 34s	remaining: 4m 28s
7901:	learn: 0.0016729	total: 13m 34s	remaining: 3m 36s
8134:	learn: 0.0014049	total: 13m 34s	remaining: 3m 6s
8131:	learn: 0.0015002	total: 13m 34s	remaining: 3m 7s

8278:	learn: 0.0014280	total: 13m 34s	remaining: 2m 49s
7902:	learn: 0.0016729	total: 13m 35s	remaining: 3m 36s
7522:	learn: 0.0013648	total: 13m 35s	remaining: 4m 28s
8135:	learn: 0.0014050	total: 13m 35s	remaining: 3m 6s
8132:	learn: 0.0015002	total: 13m 34s	remaining: 3m 7s
7903:	learn: 0.0016724	total: 13m 35s	remaining: 3m 36s
8279:	learn: 0.0014280	total: 13m 35s	remaining: 2m 49s
7523:	learn: 0.0013648	total: 13m 35s	remaining: 4m 28s
8136:	learn: 0.0014049	total: 13m 35s	remaining: 3m 6s
8133:	learn: 0.0015002	total: 13m 34s	remaining: 3m 6s
7904:	learn: 0.0016719	total: 13m 35s	remaining: 3m 36s
8280:	learn: 0.0014280	total: 13m 35s	remaining: 2m 49s
8137:	learn: 0.0014049	total: 13m 35s	remaining: 3m 6s
7524:	learn: 0.0013648	total: 13m 35s	remaining: 4m 28s
8134:	learn: 0.0015002	total: 13m 35s	remaining: 3m 6s
8281:	learn: 0.0014280	total: 13m 35s	remaining: 2m 49s
7905:	learn: 0.0016717	total: 13m 35s	remaining: 3m 35s
8138:	learn: 0.0014049	total: 13m 35s	remaining: 3m 6s
8135:	learn: 0.0015002	total: 13m 35s	remaining: 3m 6s
8282:	learn: 0.0014280	total: 13m 35s	remaining: 2m 48s
7525:	learn: 0.0013648	total: 13m 35s	remaining: 4m 28s
7906:	learn: 0.0016717	total: 13m 35s	remaining: 3m 35s
8283:	learn: 0.0014280	total: 13m 35s	remaining: 2m 48s
8136:	learn: 0.0015002	total: 13m 35s	remaining: 3m 6s
8139:	learn: 0.0014049	total: 13m 35s	remaining: 3m 6s
7907:	learn: 0.0016717	total: 13m 35s	remaining: 3m 35s
7526:	learn: 0.0013648	total: 13m 35s	remaining: 4m 27s
8284:	learn: 0.0014280	total: 13m 35s	remaining: 2m 48s
8140:	learn: 0.0014049	total: 13m 35s	remaining: 3m 6s
8137:	learn: 0.0015002	total: 13m 35s	remaining: 3m 6s
7908:	learn: 0.0016717	total: 13m 35s	remaining: 3m 35s
7527:	learn: 0.0013648	total: 13m 35s	remaining: 4m 27s
8141:	learn: 0.0014049	total: 13m 35s	remaining: 3m 6s
8285:	learn: 0.0014280	total: 13m 35s	remaining: 2m 48s
7909:	learn: 0.0016717	total: 13m 35s	remaining: 3m 35s
8138:	learn: 0.0015002	total: 13m 35s	remaining: 3m 6s
7528:	learn: 0.0013648	total: 13m 35s	remaining: 4m 27s
8142:	learn: 0.0014046	total: 13m 35s	remaining: 3m 6s
8286:	learn: 0.0014280	total: 13m 35s	remaining: 2m 48s
7910:	learn: 0.0016717	total: 13m 35s	remaining: 3m 35s
8139:	learn: 0.0015002	total: 13m 35s	remaining: 3m 6s
7529:	learn: 0.0013648	total: 13m 35s	remaining: 4m 27s
8287:	learn: 0.0014280	total: 13m 35s	remaining: 2m 48s
8143:	learn: 0.0014046	total: 13m 35s	remaining: 3m 5s
7911:	learn: 0.0016717	total: 13m 35s	remaining: 3m 35s
8140:	learn: 0.0015002	total: 13m 35s	remaining: 3m 6s
7530:	learn: 0.0013648	total: 13m 35s	remaining: 4m 27s
8288:	learn: 0.0014280	total: 13m 35s	remaining: 2m 48s
8144:	learn: 0.0014046	total: 13m 35s	remaining: 3m 5s
7912:	learn: 0.0016713	total: 13m 36s	remaining: 3m 35s
8141:	learn: 0.0015002	total: 13m 35s	remaining: 3m 6s
8289:	learn: 0.0014280	total: 13m 35s	remaining: 2m 48s
7531:	learn: 0.0013648	total: 13m 36s	remaining: 4m 27s
8145:	learn: 0.0014046	total: 13m 36s	remaining: 3m 5s
7913:	learn: 0.0016706	total: 13m 36s	remaining: 3m 35s
7532:	learn: 0.0013648	total: 13m 36s	remaining: 4m 27s
8142:	learn: 0.0015001	total: 13m 35s	remaining: 3m 6s
8290:	learn: 0.0014280	total: 13m 36s	remaining: 2m 48s
7914:	learn: 0.0016703	total: 13m 36s	remaining: 3m 35s
8146:	learn: 0.0014046	total: 13m 36s	remaining: 3m 5s
7533:	learn: 0.0013648	total: 13m 36s	remaining: 4m 27s
8291:	learn: 0.0014280	total: 13m 36s	remaining: 2m 48s
8143:	learn: 0.0015001	total: 13m 36s	remaining: 3m 5s
7915:	learn: 0.0016703	total: 13m 36s	remaining: 3m 34s
8147:	learn: 0.0014046	total: 13m 36s	remaining: 3m 5s
7534:	learn: 0.0013648	total: 13m 36s	remaining: 4m 27s
8292:	learn: 0.0014280	total: 13m 36s	remaining: 2m 47s
8144:	learn: 0.0014997	total: 13m 36s	remaining: 3m 5s
8148:	learn: 0.0014046	total: 13m 36s	remaining: 3m 5s
8293:	learn: 0.0014276	total: 13m 36s	remaining: 2m 47s
7916:	learn: 0.0016698	total: 13m 36s	remaining: 3m 34s
7535:	learn: 0.0013648	total: 13m 36s	remaining: 4m 26s
8145:	learn: 0.0014997	total: 13m 36s	remaining: 3m 5s
8149:	learn: 0.0014046	total: 13m 36s	remaining: 3m 5s
7536:	learn: 0.0013648	total: 13m 36s	remaining: 4m 26s
7917:	learn: 0.0016694	total: 13m 36s	remaining: 3m 34s
8294:	learn: 0.0014273	total: 13m 36s	remaining: 2m 47s
8146:	learn: 0.0014997	total: 13m 36s	remaining: 3m 5s
8150:	learn: 0.0014046	total: 13m 36s	remaining: 3m 5s
7537:	learn: 0.0013648	total: 13m 36s	remaining: 4m 26s
8147:	learn: 0.0014997	total: 13m 36s	remaining: 3m 5s
7918:	learn: 0.0016690	total: 13m 36s	remaining: 3m 34s
8295:	learn: 0.0014273	total: 13m 36s	remaining: 2m 47s
8151:	learn: 0.0014046	total: 13m 36s	remaining: 3m 5s
7538:	learn: 0.0013647	total: 13m 36s	remaining: 4m 26s
8148:	learn: 0.0014997	total: 13m 36s	remaining: 3m 5s
8296:	learn: 0.0014273	total: 13m 36s	remaining: 2m 47s
7919:	learn: 0.0016684	total: 13m 36s	remaining: 3m 34s
8152:	learn: 0.0014046	total: 13m 36s	remaining: 3m 5s
7539:	learn: 0.0013647	total: 13m 36s	remaining: 4m 26s
7920:	learn: 0.0016677	total: 13m 36s	remaining: 3m 34s
8149:	learn: 0.0014997	total: 13m 36s	remaining: 3m 5s
8297:	learn: 0.0014273	total: 13m 36s	remaining: 2m 47s
8153:	learn: 0.0014046	total: 13m 36s	remaining: 3m 4s
7540:	learn: 0.0013647	total: 13m 36s	remaining: 4m 26s
7921:	learn: 0.0016677	total: 13m 36s	remaining: 3m 34s
8150:	learn: 0.0014997	total: 13m 36s	remaining: 3m 5s
8298:	learn: 0.0014273	total: 13m 36s	remaining: 2m 47s
8154:	learn: 0.0014041	total: 13m 36s	remaining: 3m 4s
7922:	learn: 0.0016677	total: 13m 37s	remaining: 3m 34s
7541:	learn: 0.0013644	total: 13m 36s	remaining: 4m 26s
8151:	learn: 0.0014994	total: 13m 36s	remaining: 3m 5s
8155:	learn: 0.0014041	total: 13m 37s	remaining: 3m 4s
8299:	learn: 0.0014273	total: 13m 36s	remaining: 2m 47s
7923:	learn: 0.0016677	total: 13m 37s	remaining: 3m 34s
7542:	learn: 0.0013644	total: 13m 37s	remaining: 4m 26s
8152:	learn: 0.0014994	total: 13m 36s	remaining: 3m 5s
8300:	learn: 0.0014273	total: 13m 37s	remaining: 2m 47s
8156:	learn: 0.0014042	total: 13m 37s	remaining: 3m 4s
7924:	learn: 0.0016677	total: 13m 37s	remaining: 3m 33s
7543:	learn: 0.0013644	total: 13m 37s	remaining: 4m 26s
8153:	learn: 0.0014994	total: 13m 37s	remaining: 3m 4s
8301:	learn: 0.0014273	total: 13m 37s	remaining: 2m 47s
7925:	learn: 0.0016677	total: 13m 37s	remaining: 3m 33s
8154:	learn: 0.0014994	total: 13m 37s	remaining: 3m 4s
8302:	learn: 0.0014273	total: 13m 37s	remaining: 2m 47s
8157:	learn: 0.0014041	total: 13m 37s	remaining: 3m 4s
7544:	learn: 0.0013644	total: 13m 37s	remaining: 4m 25s
7926:	learn: 0.0016677	total: 13m 37s	remaining: 3m 33s
8303:	learn: 0.0014273	total: 13m 37s	remaining: 2m 46s
8155:	learn: 0.0014994	total: 13m 37s	remaining: 3m 4s
8158:	learn: 0.0014041	total: 13m 37s	remaining: 3m 4s
8304:	learn: 0.0014272	total: 13m 37s	remaining: 2m 46s
7545:	learn: 0.0013644	total: 13m 37s	remaining: 4m 25s
7927:	learn: 0.0016677	total: 13m 37s	remaining: 3m 33s
8156:	learn: 0.0014994	total: 13m 37s	remaining: 3m 4s
8159:	learn: 0.0014038	total: 13m 37s	remaining: 3m 4s
8305:	learn: 0.0014273	total: 13m 37s	remaining: 2m 46s
7546:	learn: 0.0013644	total: 13m 37s	remaining: 4m 25s
7928:	learn: 0.0016677	total: 13m 37s	remaining: 3m 33s
8160:	learn: 0.0014039	total: 13m 37s	remaining: 3m 4s
8157:	learn: 0.0014994	total: 13m 37s	remaining: 3m 4s
8306:	learn: 0.0014273	total: 13m 37s	remaining: 2m 46s
8161:	learn: 0.0014038	total: 13m 37s	remaining: 3m 4s
7929:	learn: 0.0016677	total: 13m 37s	remaining: 3m 33s
7547:	learn: 0.0013644	total: 13m 37s	remaining: 4m 25s
8158:	learn: 0.0014994	total: 13m 37s	remaining: 3m 4s
8307:	learn: 0.0014273	total: 13m 37s	remaining: 2m 46s
8162:	learn: 0.0014038	total: 13m 37s	remaining: 3m 4s
7930:	learn: 0.0016677	total: 13m 37s	remaining: 3m 33s
8159:	learn: 0.0014994	total: 13m 37s	remaining: 3m 4s
8308:	learn: 0.0014272	total: 13m 37s	remaining: 2m 46s
7548:	learn: 0.0013644	total: 13m 37s	remaining: 4m 25s
8163:	learn: 0.0014038	total: 13m 37s	remaining: 3m 3s
8160:	learn: 0.0014994	total: 13m 37s	remaining: 3m 4s
7931:	learn: 0.0016677	total: 13m 37s	remaining: 3m 33s
8309:	learn: 0.0014273	total: 13m 37s	remaining: 2m 46s
7549:	learn: 0.0013644	total: 13m 37s	remaining: 4m 25s
8161:	learn: 0.0014994	total: 13m 37s	remaining: 3m 4s
8310:	learn: 0.0014269	total: 13m 37s	remaining: 2m 46s
8164:	learn: 0.0014039	total: 13m 37s	remaining: 3m 3s
7932:	learn: 0.0016677	total: 13m 38s	remaining: 3m 33s
7550:	learn: 0.0013644	total: 13m 38s	remaining: 4m 25s
8162:	learn: 0.0014994	total: 13m 37s	remaining: 3m 4s
8311:	learn: 0.0014269	total: 13m 37s	remaining: 2m 46s
8165:	learn: 0.0014038	total: 13m 38s	remaining: 3m 3s
7933:	learn: 0.0016677	total: 13m 38s	remaining: 3m 33s
8312:	learn: 0.0014269	total: 13m 38s	remaining: 2m 46s
8163:	learn: 0.0014994	total: 13m 37s	remaining: 3m 3s
7551:	learn: 0.0013644	total: 13m 38s	remaining: 4m 25s
8166:	learn: 0.0014037	total: 13m 38s	remaining: 3m 3s
8313:	learn: 0.0014269	total: 13m 38s	remaining: 2m 45s
7934:	learn: 0.0016672	total: 13m 38s	remaining: 3m 32s
8167:	learn: 0.0014036	total: 13m 38s	remaining: 3m 3s
7552:	learn: 0.0013644	total: 13m 38s	remaining: 4m 25s
8164:	learn: 0.0014994	total: 13m 38s	remaining: 3m 3s
8314:	learn: 0.0014269	total: 13m 38s	remaining: 2m 45s
7935:	learn: 0.0016672	total: 13m 38s	remaining: 3m 32s
8165:	learn: 0.0014994	total: 13m 38s	remaining: 3m 3s
8168:	learn: 0.0014032	total: 13m 38s	remaining: 3m 3s
7553:	learn: 0.0013644	total: 13m 38s	remaining: 4m 25s
7936:	learn: 0.0016672	total: 13m 38s	remaining: 3m 32s
8315:	learn: 0.0014269	total: 13m 38s	remaining: 2m 45s
8169:	learn: 0.0014031	total: 13m 38s	remaining: 3m 3s
8166:	learn: 0.0014994	total: 13m 38s	remaining: 3m 3s
7937:	learn: 0.0016672	total: 13m 38s	remaining: 3m 32s
8316:	learn: 0.0014265	total: 13m 38s	remaining: 2m 45s
8170:	learn: 0.0014031	total: 13m 38s	remaining: 3m 3s
7554:	learn: 0.0013644	total: 13m 38s	remaining: 4m 24s
8167:	learn: 0.0014994	total: 13m 38s	remaining: 3m 3s
7938:	learn: 0.0016667	total: 13m 38s	remaining: 3m 32s
8168:	learn: 0.0014994	total: 13m 38s	remaining: 3m 3s
8317:	learn: 0.0014265	total: 13m 38s	remaining: 2m 45s
8171:	learn: 0.0014031	total: 13m 38s	remaining: 3m 3s
8169:	learn: 0.0014994	total: 13m 38s	remaining: 3m 3s
7939:	learn: 0.0016663	total: 13m 38s	remaining: 3m 32s
7555:	learn: 0.0013644	total: 13m 38s	remaining: 4m 24s
8318:	learn: 0.0014261	total: 13m 38s	remaining: 2m 45s
8172:	learn: 0.0014031	total: 13m 38s	remaining: 3m 3s
8170:	learn: 0.0014994	total: 13m 38s	remaining: 3m 3s
7940:	learn: 0.0016658	total: 13m 38s	remaining: 3m 32s
7556:	learn: 0.0013644	total: 13m 38s	remaining: 4m 24s
7941:	learn: 0.0016656	total: 13m 38s	remaining: 3m 32s
8319:	learn: 0.0014261	total: 13m 38s	remaining: 2m 45s
8173:	learn: 0.0014028	total: 13m 38s	remaining: 3m 2s
8171:	learn: 0.0014994	total: 13m 38s	remaining: 3m 3s
7557:	learn: 0.0013644	total: 13m 38s	remaining: 4m 24s
7942:	learn: 0.0016656	total: 13m 38s	remaining: 3m 32s
8320:	learn: 0.0014261	total: 13m 38s	remaining: 2m 45s
8174:	learn: 0.0014028	total: 13m 38s	remaining: 3m 2s
8172:	learn: 0.0014994	total: 13m 38s	remaining: 3m 3s
7943:	learn: 0.0016656	total: 13m 39s	remaining: 3m 31s
8321:	learn: 0.0014261	total: 13m 38s	remaining: 2m 45s
7558:	learn: 0.0013644	total: 13m 39s	remaining: 4m 24s
8173:	learn: 0.0014994	total: 13m 38s	remaining: 3m 2s
8175:	learn: 0.0014029	total: 13m 39s	remaining: 3m 2s
8322:	learn: 0.0014261	total: 13m 38s	remaining: 2m 45s
7944:	learn: 0.0016656	total: 13m 39s	remaining: 3m 31s
8174:	learn: 0.0014994	total: 13m 38s	remaining: 3m 2s
7559:	learn: 0.0013644	total: 13m 39s	remaining: 4m 24s
8176:	learn: 0.0014028	total: 13m 39s	remaining: 3m 2s
7945:	learn: 0.0016651	total: 13m 39s	remaining: 3m 31s
8323:	learn: 0.0014261	total: 13m 39s	remaining: 2m 44s
7560:	learn: 0.0013644	total: 13m 39s	remaining: 4m 24s
8175:	learn: 0.0014994	total: 13m 39s	remaining: 3m 2s
7946:	learn: 0.0016651	total: 13m 39s	remaining: 3m 31s
8177:	learn: 0.0014029	total: 13m 39s	remaining: 3m 2s
8324:	learn: 0.0014261	total: 13m 39s	remaining: 2m 44s
8176:	learn: 0.0014993	total: 13m 39s	remaining: 3m 2s
7561:	learn: 0.0013644	total: 13m 39s	remaining: 4m 24s
8178:	learn: 0.0014028	total: 13m 39s	remaining: 3m 2s
7947:	learn: 0.0016648	total: 13m 39s	remaining: 3m 31s
8325:	learn: 0.0014261	total: 13m 39s	remaining: 2m 44s
8177:	learn: 0.0014993	total: 13m 39s	remaining: 3m 2s
7562:	learn: 0.0013644	total: 13m 39s	remaining: 4m 24s
7948:	learn: 0.0016643	total: 13m 39s	remaining: 3m 31s
8179:	learn: 0.0014028	total: 13m 39s	remaining: 3m 2s
8326:	learn: 0.0014261	total: 13m 39s	remaining: 2m 44s
7563:	learn: 0.0013644	total: 13m 39s	remaining: 4m 23s
7949:	learn: 0.0016643	total: 13m 39s	remaining: 3m 31s
8178:	learn: 0.0014993	total: 13m 39s	remaining: 3m 2s
8180:	learn: 0.0014028	total: 13m 39s	remaining: 3m 2s
8327:	learn: 0.0014261	total: 13m 39s	remaining: 2m 44s
8181:	learn: 0.0014028	total: 13m 39s	remaining: 3m 2s
7564:	learn: 0.0013644	total: 13m 39s	remaining: 4m 23s
7950:	learn: 0.0016643	total: 13m 39s	remaining: 3m 31s
8179:	learn: 0.0014993	total: 13m 39s	remaining: 3m 2s
8328:	learn: 0.0014261	total: 13m 39s	remaining: 2m 44s
8182:	learn: 0.0014028	total: 13m 39s	remaining: 3m 2s
7565:	learn: 0.0013644	total: 13m 39s	remaining: 4m 23s
8180:	learn: 0.0014993	total: 13m 39s	remaining: 3m 2s
7951:	learn: 0.0016640	total: 13m 39s	remaining: 3m 31s
8329:	learn: 0.0014261	total: 13m 39s	remaining: 2m 44s
8183:	learn: 0.0014028	total: 13m 39s	remaining: 3m 1s
7566:	learn: 0.0013644	total: 13m 39s	remaining: 4m 23s
8181:	learn: 0.0014993	total: 13m 39s	remaining: 3m 2s
7952:	learn: 0.0016634	total: 13m 39s	remaining: 3m 31s
8330:	learn: 0.0014261	total: 13m 39s	remaining: 2m 44s
8184:	learn: 0.0014028	total: 13m 39s	remaining: 3m 1s
7953:	learn: 0.0016634	total: 13m 40s	remaining: 3m 30s
8331:	learn: 0.0014261	total: 13m 39s	remaining: 2m 44s
7567:	learn: 0.0013644	total: 13m 40s	remaining: 4m 23s
8182:	learn: 0.0014993	total: 13m 39s	remaining: 3m 2s
8185:	learn: 0.0014028	total: 13m 40s	remaining: 3m 1s
7954:	learn: 0.0016629	total: 13m 40s	remaining: 3m 30s
7568:	learn: 0.0013644	total: 13m 40s	remaining: 4m 23s
8332:	learn: 0.0014261	total: 13m 39s	remaining: 2m 44s
8183:	learn: 0.0014993	total: 13m 39s	remaining: 3m 1s
7569:	learn: 0.0013644	total: 13m 40s	remaining: 4m 23s
7955:	learn: 0.0016624	total: 13m 40s	remaining: 3m 30s
8186:	learn: 0.0014028	total: 13m 40s	remaining: 3m 1s
8333:	learn: 0.0014261	total: 13m 40s	remaining: 2m 43s
8184:	learn: 0.0014993	total: 13m 40s	remaining: 3m 1s
7570:	learn: 0.0013644	total: 13m 40s	remaining: 4m 23s
7956:	learn: 0.0016624	total: 13m 40s	remaining: 3m 30s
8187:	learn: 0.0014028	total: 13m 40s	remaining: 3m 1s
8334:	learn: 0.0014261	total: 13m 40s	remaining: 2m 43s
8185:	learn: 0.0014991	total: 13m 40s	remaining: 3m 1s
7571:	learn: 0.0013644	total: 13m 40s	remaining: 4m 23s
7957:	learn: 0.0016624	total: 13m 40s	remaining: 3m 30s
8335:	learn: 0.0014261	total: 13m 40s	remaining: 2m 43s
8186:	learn: 0.0014991	total: 13m 40s	remaining: 3m 1s
8188:	learn: 0.0014028	total: 13m 40s	remaining: 3m 1s
7572:	learn: 0.0013641	total: 13m 40s	remaining: 4m 22s
7958:	learn: 0.0016624	total: 13m 40s	remaining: 3m 30s
8336:	learn: 0.0014261	total: 13m 40s	remaining: 2m 43s
8189:	learn: 0.0014028	total: 13m 40s	remaining: 3m 1s
8187:	learn: 0.0014991	total: 13m 40s	remaining: 3m 1s
7573:	learn: 0.0013641	total: 13m 40s	remaining: 4m 22s
8337:	learn: 0.0014261	total: 13m 40s	remaining: 2m 43s
7959:	learn: 0.0016624	total: 13m 40s	remaining: 3m 30s
8190:	learn: 0.0014028	total: 13m 40s	remaining: 3m 1s
8188:	learn: 0.0014991	total: 13m 40s	remaining: 3m 1s
8338:	learn: 0.0014261	total: 13m 40s	remaining: 2m 43s
7960:	learn: 0.0016621	total: 13m 40s	remaining: 3m 30s
7574:	learn: 0.0013641	total: 13m 40s	remaining: 4m 22s
8191:	learn: 0.0014028	total: 13m 40s	remaining: 3m 1s
8189:	learn: 0.0014991	total: 13m 40s	remaining: 3m 1s
8339:	learn: 0.0014261	total: 13m 40s	remaining: 2m 43s
7961:	learn: 0.0016621	total: 13m 40s	remaining: 3m 30s
7575:	learn: 0.0013641	total: 13m 40s	remaining: 4m 22s
8192:	learn: 0.0014028	total: 13m 40s	remaining: 3m 1s
8190:	learn: 0.0014991	total: 13m 40s	remaining: 3m 1s
8340:	learn: 0.0014261	total: 13m 40s	remaining: 2m 43s

7962:	learn: 0.0016619	total: 13m 40s	remaining: 3m 30s
8193:	learn: 0.0014028	total: 13m 40s	remaining: 3m
7576:	learn: 0.0013641	total: 13m 40s	remaining: 4m 22s
8191:	learn: 0.0014991	total: 13m 40s	remaining: 3m 1s
8194:	learn: 0.0014028	total: 13m 40s	remaining: 3m
8341:	learn: 0.0014261	total: 13m 40s	remaining: 2m 43s
7963:	learn: 0.0016619	total: 13m 41s	remaining: 3m 29s
7577:	learn: 0.0013641	total: 13m 41s	remaining: 4m 22s
8192:	learn: 0.0014987	total: 13m 40s	remaining: 3m 1s
8195:	learn: 0.0014027	total: 13m 41s	remaining: 3m
8342:	learn: 0.0014261	total: 13m 40s	remaining: 2m 43s
7964:	learn: 0.0016614	total: 13m 41s	remaining: 3m 29s
7578:	learn: 0.0013641	total: 13m 41s	remaining: 4m 22s
8193:	learn: 0.0014983	total: 13m 40s	remaining: 3m
8343:	learn: 0.0014257	total: 13m 41s	remaining: 2m 42s
8196:	learn: 0.0014027	total: 13m 41s	remaining: 3m
7965:	learn: 0.0016614	total: 13m 41s	remaining: 3m 29s
7579:	learn: 0.0013641	total: 13m 41s	remaining: 4m 22s
8194:	learn: 0.0014983	total: 13m 41s	remaining: 3m
8344:	learn: 0.0014253	total: 13m 41s	remaining: 2m 42s
7580:	learn: 0.0013641	total: 13m 41s	remaining: 4m 22s
8197:	learn: 0.0014027	total: 13m 41s	remaining: 3m
7966:	learn: 0.0016614	total: 13m 41s	remaining: 3m 29s
8195:	learn: 0.0014983	total: 13m 41s	remaining: 3m
8345:	learn: 0.0014253	total: 13m 41s	remaining: 2m 42s
7581:	learn: 0.0013641	total: 13m 41s	remaining: 4m 21s
7967:	learn: 0.0016614	total: 13m 41s	remaining: 3m 29s
8198:	learn: 0.0014027	total: 13m 41s	remaining: 3m
8196:	learn: 0.0014983	total: 13m 41s	remaining: 3m
8346:	learn: 0.0014253	total: 13m 41s	remaining: 2m 42s
7968:	learn: 0.0016614	total: 13m 41s	remaining: 3m 29s
7582:	learn: 0.0013641	total: 13m 41s	remaining: 4m 21s
8197:	learn: 0.0014983	total: 13m 41s	remaining: 3m
8347:	learn: 0.0014253	total: 13m 41s	remaining: 2m 42s
8199:	learn: 0.0014025	total: 13m 41s	remaining: 3m
7969:	learn: 0.0016614	total: 13m 41s	remaining: 3m 29s
7583:	learn: 0.0013641	total: 13m 41s	remaining: 4m 21s
8348:	learn: 0.0014253	total: 13m 41s	remaining: 2m 42s
8200:	learn: 0.0014025	total: 13m 41s	remaining: 3m
8198:	learn: 0.0014983	total: 13m 41s	remaining: 3m
7970:	learn: 0.0016614	total: 13m 41s	remaining: 3m 29s
8349:	learn: 0.0014253	total: 13m 41s	remaining: 2m 42s
7584:	learn: 0.0013641	total: 13m 41s	remaining: 4m 21s
8201:	learn: 0.0014025	total: 13m 41s	remaining: 3m
8199:	learn: 0.0014983	total: 13m 41s	remaining: 3m
7971:	learn: 0.0016614	total: 13m 41s	remaining: 3m 29s
7585:	learn: 0.0013641	total: 13m 41s	remaining: 4m 21s
8350:	learn: 0.0014253	total: 13m 41s	remaining: 2m 42s
8202:	learn: 0.0014025	total: 13m 41s	remaining: 3m
8200:	learn: 0.0014983	total: 13m 41s	remaining: 3m
7972:	learn: 0.0016614	total: 13m 41s	remaining: 3m 28s
8351:	learn: 0.0014253	total: 13m 41s	remaining: 2m 42s
7586:	learn: 0.0013641	total: 13m 41s	remaining: 4m 21s
8203:	learn: 0.0014025	total: 13m 41s	remaining: 2m 59s
8201:	learn: 0.0014983	total: 13m 41s	remaining: 3m
7973:	learn: 0.0016614	total: 13m 42s	remaining: 3m 28s
7587:	learn: 0.0013640	total: 13m 42s	remaining: 4m 21s
8352:	learn: 0.0014253	total: 13m 41s	remaining: 2m 42s
8204:	learn: 0.0014025	total: 13m 42s	remaining: 2m 59s
8202:	learn: 0.0014983	total: 13m 41s	remaining: 3m
7974:	learn: 0.0016614	total: 13m 42s	remaining: 3m 28s
7588:	learn: 0.0013640	total: 13m 42s	remaining: 4m 21s
8353:	learn: 0.0014253	total: 13m 41s	remaining: 2m 41s
8205:	learn: 0.0014025	total: 13m 42s	remaining: 2m 59s
8203:	learn: 0.0014983	total: 13m 41s	remaining: 2m 59s
7975:	learn: 0.0016611	total: 13m 42s	remaining: 3m 28s
7589:	learn: 0.0013640	total: 13m 42s	remaining: 4m 21s
8354:	learn: 0.0014253	total: 13m 42s	remaining: 2m 41s
8204:	learn: 0.0014983	total: 13m 42s	remaining: 2m 59s
8206:	learn: 0.0014025	total: 13m 42s	remaining: 2m 59s
8355:	learn: 0.0014253	total: 13m 42s	remaining: 2m 41s
7590:	learn: 0.0013640	total: 13m 42s	remaining: 4m 20s
7976:	learn: 0.0016605	total: 13m 42s	remaining: 3m 28s
8205:	learn: 0.0014983	total: 13m 42s	remaining: 2m 59s
8207:	learn: 0.0014025	total: 13m 42s	remaining: 2m 59s
8356:	learn: 0.0014253	total: 13m 42s	remaining: 2m 41s
7591:	learn: 0.0013640	total: 13m 42s	remaining: 4m 20s
7977:	learn: 0.0016605	total: 13m 42s	remaining: 3m 28s
8206:	learn: 0.0014983	total: 13m 42s	remaining: 2m 59s
8208:	learn: 0.0014025	total: 13m 42s	remaining: 2m 59s
8207:	learn: 0.0014983	total: 13m 42s	remaining: 2m 59s
8357:	learn: 0.0014253	total: 13m 42s	remaining: 2m 41s
7592:	learn: 0.0013640	total: 13m 42s	remaining: 4m 20s
7978:	learn: 0.0016603	total: 13m 42s	remaining: 3m 28s
8209:	learn: 0.0014025	total: 13m 42s	remaining: 2m 59s
8208:	learn: 0.0014983	total: 13m 42s	remaining: 2m 59s
8358:	learn: 0.0014250	total: 13m 42s	remaining: 2m 41s
7593:	learn: 0.0013640	total: 13m 42s	remaining: 4m 20s
8210:	learn: 0.0014022	total: 13m 42s	remaining: 2m 59s
7979:	learn: 0.0016603	total: 13m 42s	remaining: 3m 28s
8209:	learn: 0.0014983	total: 13m 42s	remaining: 2m 59s
8359:	learn: 0.0014246	total: 13m 42s	remaining: 2m 41s
8211:	learn: 0.0014019	total: 13m 42s	remaining: 2m 59s
7980:	learn: 0.0016603	total: 13m 42s	remaining: 3m 28s
7594:	learn: 0.0013640	total: 13m 42s	remaining: 4m 20s
8360:	learn: 0.0014246	total: 13m 42s	remaining: 2m 41s
8212:	learn: 0.0014019	total: 13m 42s	remaining: 2m 59s
8210:	learn: 0.0014983	total: 13m 42s	remaining: 2m 59s
7981:	learn: 0.0016603	total: 13m 42s	remaining: 3m 28s
7595:	learn: 0.0013640	total: 13m 42s	remaining: 4m 20s
8361:	learn: 0.0014242	total: 13m 42s	remaining: 2m 41s
8213:	learn: 0.0014019	total: 13m 42s	remaining: 2m 58s
8211:	learn: 0.0014983	total: 13m 42s	remaining: 2m 59s
7982:	learn: 0.0016603	total: 13m 42s	remaining: 3m 27s
8362:	learn: 0.0014242	total: 13m 42s	remaining: 2m 41s
7596:	learn: 0.0013640	total: 13m 42s	remaining: 4m 20s
8212:	learn: 0.0014983	total: 13m 42s	remaining: 2m 59s
8214:	learn: 0.0014019	total: 13m 43s	remaining: 2m 58s
7983:	learn: 0.0016599	total: 13m 43s	remaining: 3m 27s
8363:	learn: 0.0014242	total: 13m 42s	remaining: 2m 40s
7597:	learn: 0.0013637	total: 13m 43s	remaining: 4m 20s
8213:	learn: 0.0014983	total: 13m 42s	remaining: 2m 58s
8215:	learn: 0.0014019	total: 13m 43s	remaining: 2m 58s
7984:	learn: 0.0016593	total: 13m 43s	remaining: 3m 27s
8364:	learn: 0.0014242	total: 13m 43s	remaining: 2m 40s
7598:	learn: 0.0013635	total: 13m 43s	remaining: 4m 20s
7985:	learn: 0.0016590	total: 13m 43s	remaining: 3m 27s
8214:	learn: 0.0014983	total: 13m 43s	remaining: 2m 58s
8216:	learn: 0.0014019	total: 13m 43s	remaining: 2m 58s
7599:	learn: 0.0013635	total: 13m 43s	remaining: 4m 19s
8365:	learn: 0.0014242	total: 13m 43s	remaining: 2m 40s
7986:	learn: 0.0016590	total: 13m 43s	remaining: 3m 27s
8215:	learn: 0.0014983	total: 13m 43s	remaining: 2m 58s
8217:	learn: 0.0014014	total: 13m 43s	remaining: 2m 58s
8366:	learn: 0.0014242	total: 13m 43s	remaining: 2m 40s
7600:	learn: 0.0013635	total: 13m 43s	remaining: 4m 19s
7987:	learn: 0.0016586	total: 13m 43s	remaining: 3m 27s
8216:	learn: 0.0014983	total: 13m 43s	remaining: 2m 58s
7601:	learn: 0.0013635	total: 13m 43s	remaining: 4m 19s
8367:	learn: 0.0014242	total: 13m 43s	remaining: 2m 40s
8218:	learn: 0.0014014	total: 13m 43s	remaining: 2m 58s
7988:	learn: 0.0016582	total: 13m 43s	remaining: 3m 27s
8217:	learn: 0.0014983	total: 13m 43s	remaining: 2m 58s
7602:	learn: 0.0013635	total: 13m 43s	remaining: 4m 19s
8368:	learn: 0.0014242	total: 13m 43s	remaining: 2m 40s
8219:	learn: 0.0014014	total: 13m 43s	remaining: 2m 58s
7989:	learn: 0.0016577	total: 13m 43s	remaining: 3m 27s
8218:	learn: 0.0014983	total: 13m 43s	remaining: 2m 58s
8369:	learn: 0.0014242	total: 13m 43s	remaining: 2m 40s
7603:	learn: 0.0013635	total: 13m 43s	remaining: 4m 19s
7990:	learn: 0.0016577	total: 13m 43s	remaining: 3m 27s
8220:	learn: 0.0014014	total: 13m 43s	remaining: 2m 58s
8219:	learn: 0.0014983	total: 13m 43s	remaining: 2m 58s
8370:	learn: 0.0014242	total: 13m 43s	remaining: 2m 40s
7604:	learn: 0.0013634	total: 13m 43s	remaining: 4m 19s
7991:	learn: 0.0016573	total: 13m 43s	remaining: 3m 26s
8221:	learn: 0.0014014	total: 13m 43s	remaining: 2m 58s
8220:	learn: 0.0014983	total: 13m 43s	remaining: 2m 58s
8371:	learn: 0.0014242	total: 13m 43s	remaining: 2m 40s
7605:	learn: 0.0013634	total: 13m 43s	remaining: 4m 19s
7992:	learn: 0.0016573	total: 13m 43s	remaining: 3m 26s
8222:	learn: 0.0014014	total: 13m 43s	remaining: 2m 58s
8221:	learn: 0.0014977	total: 13m 43s	remaining: 2m 58s
8372:	learn: 0.0014242	total: 13m 43s	remaining: 2m 40s
7606:	learn: 0.0013634	total: 13m 43s	remaining: 4m 19s
8223:	learn: 0.0014014	total: 13m 43s	remaining: 2m 57s
8222:	learn: 0.0014977	total: 13m 43s	remaining: 2m 58s
7993:	learn: 0.0016573	total: 13m 44s	remaining: 3m 26s
7607:	learn: 0.0013634	total: 13m 44s	remaining: 4m 19s
8373:	learn: 0.0014242	total: 13m 43s	remaining: 2m 39s
8224:	learn: 0.0014013	total: 13m 44s	remaining: 2m 57s
8223:	learn: 0.0014977	total: 13m 43s	remaining: 2m 57s
7608:	learn: 0.0013630	total: 13m 44s	remaining: 4m 18s
7994:	learn: 0.0016573	total: 13m 44s	remaining: 3m 26s
8374:	learn: 0.0014242	total: 13m 44s	remaining: 2m 39s
8225:	learn: 0.0014014	total: 13m 44s	remaining: 2m 57s
8224:	learn: 0.0014977	total: 13m 43s	remaining: 2m 57s
7609:	learn: 0.0013630	total: 13m 44s	remaining: 4m 18s
8375:	learn: 0.0014242	total: 13m 44s	remaining: 2m 39s
7995:	learn: 0.0016573	total: 13m 44s	remaining: 3m 26s
7610:	learn: 0.0013630	total: 13m 44s	remaining: 4m 18s
8226:	learn: 0.0014014	total: 13m 44s	remaining: 2m 57s
8225:	learn: 0.0014976	total: 13m 44s	remaining: 2m 57s
7996:	learn: 0.0016573	total: 13m 44s	remaining: 3m 26s
8376:	learn: 0.0014242	total: 13m 44s	remaining: 2m 39s
7611:	learn: 0.0013630	total: 13m 44s	remaining: 4m 18s
8227:	learn: 0.0014013	total: 13m 44s	remaining: 2m 57s
8226:	learn: 0.0014976	total: 13m 44s	remaining: 2m 57s
8377:	learn: 0.0014242	total: 13m 44s	remaining: 2m 39s
8228:	learn: 0.0014013	total: 13m 44s	remaining: 2m 57s
7997:	learn: 0.0016573	total: 13m 44s	remaining: 3m 26s
7612:	learn: 0.0013630	total: 13m 44s	remaining: 4m 18s
8378:	learn: 0.0014242	total: 13m 44s	remaining: 2m 39s
8227:	learn: 0.0014976	total: 13m 44s	remaining: 2m 57s
8229:	learn: 0.0014013	total: 13m 44s	remaining: 2m 57s
7998:	learn: 0.0016573	total: 13m 44s	remaining: 3m 26s
8379:	learn: 0.0014242	total: 13m 44s	remaining: 2m 39s
7613:	learn: 0.0013630	total: 13m 44s	remaining: 4m 18s
8228:	learn: 0.0014975	total: 13m 44s	remaining: 2m 57s
8230:	learn: 0.0014013	total: 13m 44s	remaining: 2m 57s
7999:	learn: 0.0016568	total: 13m 44s	remaining: 3m 26s
8380:	learn: 0.0014242	total: 13m 44s	remaining: 2m 39s
8231:	learn: 0.0014014	total: 13m 44s	remaining: 2m 57s
8229:	learn: 0.0014975	total: 13m 44s	remaining: 2m 57s
7614:	learn: 0.0013630	total: 13m 44s	remaining: 4m 18s
8381:	learn: 0.0014242	total: 13m 44s	remaining: 2m 39s
8000:	learn: 0.0016564	total: 13m 44s	remaining: 3m 26s
8232:	learn: 0.0014014	total: 13m 44s	remaining: 2m 57s
8230:	learn: 0.0014975	total: 13m 44s	remaining: 2m 57s
7615:	learn: 0.0013630	total: 13m 44s	remaining: 4m 18s
8382:	learn: 0.0014242	total: 13m 44s	remaining: 2m 39s
8001:	learn: 0.0016564	total: 13m 44s	remaining: 3m 25s
8233:	learn: 0.0014014	total: 13m 44s	remaining: 2m 56s
7616:	learn: 0.0013628	total: 13m 44s	remaining: 4m 18s
8231:	learn: 0.0014976	total: 13m 44s	remaining: 2m 57s
8383:	learn: 0.0014242	total: 13m 44s	remaining: 2m 38s
8002:	learn: 0.0016559	total: 13m 45s	remaining: 3m 25s
8234:	learn: 0.0014013	total: 13m 45s	remaining: 2m 56s
8232:	learn: 0.0014976	total: 13m 44s	remaining: 2m 57s
7617:	learn: 0.0013628	total: 13m 45s	remaining: 4m 17s
8384:	learn: 0.0014242	total: 13m 44s	remaining: 2m 38s
8235:	learn: 0.0014014	total: 13m 45s	remaining: 2m 56s
8003:	learn: 0.0016559	total: 13m 45s	remaining: 3m 25s
8233:	learn: 0.0014976	total: 13m 44s	remaining: 2m 56s
7618:	learn: 0.0013628	total: 13m 45s	remaining: 4m 17s
8236:	learn: 0.0014013	total: 13m 45s	remaining: 2m 56s
8385:	learn: 0.0014242	total: 13m 45s	remaining: 2m 38s
8004:	learn: 0.0016559	total: 13m 45s	remaining: 3m 25s
8237:	learn: 0.0014014	total: 13m 45s	remaining: 2m 56s
8234:	learn: 0.0014976	total: 13m 45s	remaining: 2m 56s
7619:	learn: 0.0013628	total: 13m 45s	remaining: 4m 17s
8386:	learn: 0.0014242	total: 13m 45s	remaining: 2m 38s
8005:	learn: 0.0016559	total: 13m 45s	remaining: 3m 25s
8238:	learn: 0.0014014	total: 13m 45s	remaining: 2m 56s
8235:	learn: 0.0014976	total: 13m 45s	remaining: 2m 56s
7620:	learn: 0.0013628	total: 13m 45s	remaining: 4m 17s
8006:	learn: 0.0016559	total: 13m 45s	remaining: 3m 25s
8387:	learn: 0.0014242	total: 13m 45s	remaining: 2m 38s
8239:	learn: 0.0014014	total: 13m 45s	remaining: 2m 56s
8236:	learn: 0.0014976	total: 13m 45s	remaining: 2m 56s
8007:	learn: 0.0016559	total: 13m 45s	remaining: 3m 25s
8388:	learn: 0.0014242	total: 13m 45s	remaining: 2m 38s
7621:	learn: 0.0013628	total: 13m 45s	remaining: 4m 17s
8008:	learn: 0.0016559	total: 13m 45s	remaining: 3m 25s
8237:	learn: 0.0014976	total: 13m 45s	remaining: 2m 56s
8240:	learn: 0.0014009	total: 13m 45s	remaining: 2m 56s
7622:	learn: 0.0013628	total: 13m 45s	remaining: 4m 17s
8389:	learn: 0.0014242	total: 13m 45s	remaining: 2m 38s
8009:	learn: 0.0016559	total: 13m 45s	remaining: 3m 25s
8241:	learn: 0.0014009	total: 13m 45s	remaining: 2m 56s
8238:	learn: 0.0014976	total: 13m 45s	remaining: 2m 56s
8390:	learn: 0.0014242	total: 13m 45s	remaining: 2m 38s
7623:	learn: 0.0013628	total: 13m 45s	remaining: 4m 17s
8010:	learn: 0.0016559	total: 13m 45s	remaining: 3m 25s
8391:	learn: 0.0014242	total: 13m 45s	remaining: 2m 38s
8239:	learn: 0.0014976	total: 13m 45s	remaining: 2m 56s
8242:	learn: 0.0014009	total: 13m 45s	remaining: 2m 56s
8011:	learn: 0.0016559	total: 13m 45s	remaining: 3m 24s
7624:	learn: 0.0013628	total: 13m 45s	remaining: 4m 17s
8392:	learn: 0.0014242	total: 13m 45s	remaining: 2m 38s
8243:	learn: 0.0014009	total: 13m 45s	remaining: 2m 55s
8240:	learn: 0.0014976	total: 13m 45s	remaining: 2m 56s
7625:	learn: 0.0013628	total: 13m 45s	remaining: 4m 17s
8012:	learn: 0.0016559	total: 13m 45s	remaining: 3m 24s
8393:	learn: 0.0014242	total: 13m 45s	remaining: 2m 38s
8244:	learn: 0.0014009	total: 13m 45s	remaining: 2m 55s
8394:	learn: 0.0014242	total: 13m 45s	remaining: 2m 37s
8241:	learn: 0.0014976	total: 13m 45s	remaining: 2m 56s
7626:	learn: 0.0013628	total: 13m 46s	remaining: 4m 17s
8013:	learn: 0.0016556	total: 13m 46s	remaining: 3m 24s
8242:	learn: 0.0014976	total: 13m 45s	remaining: 2m 56s
8245:	learn: 0.0014009	total: 13m 46s	remaining: 2m 55s
7627:	learn: 0.0013628	total: 13m 46s	remaining: 4m 16s
8395:	learn: 0.0014242	total: 13m 46s	remaining: 2m 37s
8014:	learn: 0.0016556	total: 13m 46s	remaining: 3m 24s
8243:	learn: 0.0014976	total: 13m 45s	remaining: 2m 55s
7628:	learn: 0.0013628	total: 13m 46s	remaining: 4m 16s
8396:	learn: 0.0014242	total: 13m 46s	remaining: 2m 37s
8246:	learn: 0.0014009	total: 13m 46s	remaining: 2m 55s
8015:	learn: 0.0016556	total: 13m 46s	remaining: 3m 24s
8244:	learn: 0.0014976	total: 13m 46s	remaining: 2m 55s
7629:	learn: 0.0013628	total: 13m 46s	remaining: 4m 16s
8397:	learn: 0.0014242	total: 13m 46s	remaining: 2m 37s
8247:	learn: 0.0014009	total: 13m 46s	remaining: 2m 55s
8245:	learn: 0.0014976	total: 13m 46s	remaining: 2m 55s
8016:	learn: 0.0016556	total: 13m 46s	remaining: 3m 24s
8398:	learn: 0.0014242	total: 13m 46s	remaining: 2m 37s
7630:	learn: 0.0013628	total: 13m 46s	remaining: 4m 16s
8248:	learn: 0.0014009	total: 13m 46s	remaining: 2m 55s
8017:	learn: 0.0016556	total: 13m 46s	remaining: 3m 24s
8246:	learn: 0.0014975	total: 13m 46s	remaining: 2m 55s
8399:	learn: 0.0014242	total: 13m 46s	remaining: 2m 37s
7631:	learn: 0.0013628	total: 13m 46s	remaining: 4m 16s
8249:	learn: 0.0014009	total: 13m 46s	remaining: 2m 55s
8018:	learn: 0.0016556	total: 13m 46s	remaining: 3m 24s
8247:	learn: 0.0014976	total: 13m 46s	remaining: 2m 55s
8400:	learn: 0.0014242	total: 13m 46s	remaining: 2m 37s
7632:	learn: 0.0013628	total: 13m 46s	remaining: 4m 16s
8250:	learn: 0.0014009	total: 13m 46s	remaining: 2m 55s
8019:	learn: 0.0016556	total: 13m 46s	remaining: 3m 24s
8401:	learn: 0.0014242	total: 13m 46s	remaining: 2m 37s
8248:	learn: 0.0014975	total: 13m 46s	remaining: 2m 55s
7633:	learn: 0.0013628	total: 13m 46s	remaining: 4m 16s

8251:	learn: 0.0014009	total: 13m 46s	remaining: 2m 55s
8020:	learn: 0.0016556	total: 13m 46s	remaining: 3m 24s
8402:	learn: 0.0014242	total: 13m 46s	remaining: 2m 37s
8249:	learn: 0.0014975	total: 13m 46s	remaining: 2m 55s
7634:	learn: 0.0013628	total: 13m 46s	remaining: 4m 16s
8252:	learn: 0.0014009	total: 13m 46s	remaining: 2m 55s
8250:	learn: 0.0014975	total: 13m 46s	remaining: 2m 55s
8021:	learn: 0.0016556	total: 13m 46s	remaining: 3m 23s
8403:	learn: 0.0014242	total: 13m 46s	remaining: 2m 37s
8253:	learn: 0.0014009	total: 13m 46s	remaining: 2m 54s
8251:	learn: 0.0014975	total: 13m 46s	remaining: 2m 55s
7635:	learn: 0.0013628	total: 13m 46s	remaining: 4m 16s
8022:	learn: 0.0016556	total: 13m 47s	remaining: 3m 23s
8404:	learn: 0.0014242	total: 13m 46s	remaining: 2m 36s
8254:	learn: 0.0014009	total: 13m 47s	remaining: 2m 54s
8252:	learn: 0.0014975	total: 13m 46s	remaining: 2m 55s
7636:	learn: 0.0013628	total: 13m 47s	remaining: 4m 15s
8023:	learn: 0.0016556	total: 13m 47s	remaining: 3m 23s
8405:	learn: 0.0014242	total: 13m 46s	remaining: 2m 36s
8255:	learn: 0.0014009	total: 13m 47s	remaining: 2m 54s
8253:	learn: 0.0014975	total: 13m 46s	remaining: 2m 54s
7637:	learn: 0.0013628	total: 13m 47s	remaining: 4m 15s
8256:	learn: 0.0014009	total: 13m 47s	remaining: 2m 54s
8024:	learn: 0.0016556	total: 13m 47s	remaining: 3m 23s
8406:	learn: 0.0014242	total: 13m 47s	remaining: 2m 36s
8254:	learn: 0.0014975	total: 13m 47s	remaining: 2m 54s
7638:	learn: 0.0013624	total: 13m 47s	remaining: 4m 15s
8257:	learn: 0.0014009	total: 13m 47s	remaining: 2m 54s
8255:	learn: 0.0014975	total: 13m 47s	remaining: 2m 54s
8025:	learn: 0.0016556	total: 13m 47s	remaining: 3m 23s
8407:	learn: 0.0014242	total: 13m 47s	remaining: 2m 36s
7639:	learn: 0.0013624	total: 13m 47s	remaining: 4m 15s
8256:	learn: 0.0014975	total: 13m 47s	remaining: 2m 54s
8258:	learn: 0.0014009	total: 13m 47s	remaining: 2m 54s
8026:	learn: 0.0016556	total: 13m 47s	remaining: 3m 23s
8408:	learn: 0.0014242	total: 13m 47s	remaining: 2m 36s
8257:	learn: 0.0014975	total: 13m 47s	remaining: 2m 54s
7640:	learn: 0.0013624	total: 13m 47s	remaining: 4m 15s
8259:	learn: 0.0014009	total: 13m 47s	remaining: 2m 54s
8409:	learn: 0.0014242	total: 13m 47s	remaining: 2m 36s
8027:	learn: 0.0016556	total: 13m 47s	remaining: 3m 23s
8258:	learn: 0.0014975	total: 13m 47s	remaining: 2m 54s
8410:	learn: 0.0014242	total: 13m 47s	remaining: 2m 36s
8260:	learn: 0.0014009	total: 13m 47s	remaining: 2m 54s
8028:	learn: 0.0016556	total: 13m 47s	remaining: 3m 23s
7641:	learn: 0.0013624	total: 13m 47s	remaining: 4m 15s
8411:	learn: 0.0014237	total: 13m 47s	remaining: 2m 36s
8259:	learn: 0.0014975	total: 13m 47s	remaining: 2m 54s
8261:	learn: 0.0014009	total: 13m 47s	remaining: 2m 54s
8029:	learn: 0.0016553	total: 13m 47s	remaining: 3m 23s
8260:	learn: 0.0014976	total: 13m 47s	remaining: 2m 54s
7642:	learn: 0.0013624	total: 13m 47s	remaining: 4m 15s
8412:	learn: 0.0014237	total: 13m 47s	remaining: 2m 36s
8262:	learn: 0.0014009	total: 13m 47s	remaining: 2m 54s
8261:	learn: 0.0014975	total: 13m 47s	remaining: 2m 54s
8030:	learn: 0.0016553	total: 13m 47s	remaining: 3m 22s
8263:	learn: 0.0014009	total: 13m 47s	remaining: 2m 53s
7643:	learn: 0.0013624	total: 13m 47s	remaining: 4m 15s
8413:	learn: 0.0014237	total: 13m 47s	remaining: 2m 36s
8262:	learn: 0.0014975	total: 13m 47s	remaining: 2m 53s
8264:	learn: 0.0014009	total: 13m 47s	remaining: 2m 53s
8031:	learn: 0.0016550	total: 13m 48s	remaining: 3m 22s
7644:	learn: 0.0013624	total: 13m 47s	remaining: 4m 15s
8414:	learn: 0.0014237	total: 13m 47s	remaining: 2m 35s
8265:	learn: 0.0014006	total: 13m 48s	remaining: 2m 53s
8263:	learn: 0.0014975	total: 13m 47s	remaining: 2m 53s
7645:	learn: 0.0013624	total: 13m 48s	remaining: 4m 14s
8032:	learn: 0.0016549	total: 13m 48s	remaining: 3m 22s
8415:	learn: 0.0014237	total: 13m 47s	remaining: 2m 35s
8266:	learn: 0.0014006	total: 13m 48s	remaining: 2m 53s
8264:	learn: 0.0014976	total: 13m 47s	remaining: 2m 53s
8033:	learn: 0.0016549	total: 13m 48s	remaining: 3m 22s
8416:	learn: 0.0014237	total: 13m 48s	remaining: 2m 35s
8267:	learn: 0.0014006	total: 13m 48s	remaining: 2m 53s
7646:	learn: 0.0013624	total: 13m 48s	remaining: 4m 14s
8265:	learn: 0.0014976	total: 13m 48s	remaining: 2m 53s
8034:	learn: 0.0016549	total: 13m 48s	remaining: 3m 22s
8417:	learn: 0.0014237	total: 13m 48s	remaining: 2m 35s
8268:	learn: 0.0014006	total: 13m 48s	remaining: 2m 53s
7647:	learn: 0.0013624	total: 13m 48s	remaining: 4m 14s
8266:	learn: 0.0014975	total: 13m 48s	remaining: 2m 53s
8418:	learn: 0.0014237	total: 13m 48s	remaining: 2m 35s
8035:	learn: 0.0016549	total: 13m 48s	remaining: 3m 22s
7648:	learn: 0.0013624	total: 13m 48s	remaining: 4m 14s
8269:	learn: 0.0014006	total: 13m 48s	remaining: 2m 53s
8419:	learn: 0.0014237	total: 13m 48s	remaining: 2m 35s
8036:	learn: 0.0016549	total: 13m 48s	remaining: 3m 22s
8270:	learn: 0.0014006	total: 13m 48s	remaining: 2m 53s
8267:	learn: 0.0014975	total: 13m 48s	remaining: 2m 53s
7649:	learn: 0.0013624	total: 13m 48s	remaining: 4m 14s
8037:	learn: 0.0016549	total: 13m 48s	remaining: 3m 22s
8420:	learn: 0.0014237	total: 13m 48s	remaining: 2m 35s
8268:	learn: 0.0014975	total: 13m 48s	remaining: 2m 53s
8271:	learn: 0.0014006	total: 13m 48s	remaining: 2m 53s
8038:	learn: 0.0016548	total: 13m 48s	remaining: 3m 22s
7650:	learn: 0.0013624	total: 13m 48s	remaining: 4m 14s
8269:	learn: 0.0014975	total: 13m 48s	remaining: 2m 53s
8421:	learn: 0.0014237	total: 13m 48s	remaining: 2m 35s
8272:	learn: 0.0014003	total: 13m 48s	remaining: 2m 52s
8039:	learn: 0.0016542	total: 13m 48s	remaining: 3m 22s
7651:	learn: 0.0013624	total: 13m 48s	remaining: 4m 14s
8270:	learn: 0.0014975	total: 13m 48s	remaining: 2m 53s
8422:	learn: 0.0014237	total: 13m 48s	remaining: 2m 35s
8273:	learn: 0.0014003	total: 13m 48s	remaining: 2m 52s
8271:	learn: 0.0014975	total: 13m 48s	remaining: 2m 53s
8040:	learn: 0.0016542	total: 13m 48s	remaining: 3m 21s
7652:	learn: 0.0013624	total: 13m 48s	remaining: 4m 14s
8423:	learn: 0.0014237	total: 13m 48s	remaining: 2m 35s
8274:	learn: 0.0014002	total: 13m 48s	remaining: 2m 52s
8272:	learn: 0.0014975	total: 13m 48s	remaining: 2m 52s
8041:	learn: 0.0016542	total: 13m 49s	remaining: 3m 21s
8424:	learn: 0.0014237	total: 13m 48s	remaining: 2m 34s
8275:	learn: 0.0014002	total: 13m 48s	remaining: 2m 52s
7653:	learn: 0.0013624	total: 13m 48s	remaining: 4m 14s
8273:	learn: 0.0014975	total: 13m 48s	remaining: 2m 52s
8425:	learn: 0.0014237	total: 13m 48s	remaining: 2m 34s
8042:	learn: 0.0016542	total: 13m 49s	remaining: 3m 21s
7654:	learn: 0.0013624	total: 13m 49s	remaining: 4m 13s
8276:	learn: 0.0014003	total: 13m 49s	remaining: 2m 52s
8426:	learn: 0.0014237	total: 13m 48s	remaining: 2m 34s
8274:	learn: 0.0014976	total: 13m 48s	remaining: 2m 52s
8043:	learn: 0.0016537	total: 13m 49s	remaining: 3m 21s
7655:	learn: 0.0013624	total: 13m 49s	remaining: 4m 13s
8427:	learn: 0.0014237	total: 13m 49s	remaining: 2m 34s
8275:	learn: 0.0014975	total: 13m 48s	remaining: 2m 52s
8277:	learn: 0.0014002	total: 13m 49s	remaining: 2m 52s
8428:	learn: 0.0014237	total: 13m 49s	remaining: 2m 34s
8278:	learn: 0.0014003	total: 13m 49s	remaining: 2m 52s
8276:	learn: 0.0014975	total: 13m 49s	remaining: 2m 52s
8044:	learn: 0.0016536	total: 13m 49s	remaining: 3m 21s
7656:	learn: 0.0013624	total: 13m 49s	remaining: 4m 13s
8429:	learn: 0.0014237	total: 13m 49s	remaining: 2m 34s
8277:	learn: 0.0014975	total: 13m 49s	remaining: 2m 52s
8279:	learn: 0.0014003	total: 13m 49s	remaining: 2m 52s
7657:	learn: 0.0013624	total: 13m 49s	remaining: 4m 13s
8045:	learn: 0.0016535	total: 13m 49s	remaining: 3m 21s
8430:	learn: 0.0014235	total: 13m 49s	remaining: 2m 34s
7658:	learn: 0.0013624	total: 13m 49s	remaining: 4m 13s
8278:	learn: 0.0014975	total: 13m 49s	remaining: 2m 52s
8280:	learn: 0.0014003	total: 13m 49s	remaining: 2m 52s
8046:	learn: 0.0016533	total: 13m 49s	remaining: 3m 21s
8431:	learn: 0.0014235	total: 13m 49s	remaining: 2m 34s
7659:	learn: 0.0013624	total: 13m 49s	remaining: 4m 13s
8279:	learn: 0.0014975	total: 13m 49s	remaining: 2m 52s
8047:	learn: 0.0016533	total: 13m 49s	remaining: 3m 21s
8281:	learn: 0.0014003	total: 13m 49s	remaining: 2m 52s
8432:	learn: 0.0014233	total: 13m 49s	remaining: 2m 34s
7660:	learn: 0.0013624	total: 13m 49s	remaining: 4m 13s
8280:	learn: 0.0014975	total: 13m 49s	remaining: 2m 52s
8282:	learn: 0.0014002	total: 13m 49s	remaining: 2m 51s
8048:	learn: 0.0016533	total: 13m 49s	remaining: 3m 21s
8433:	learn: 0.0014233	total: 13m 49s	remaining: 2m 34s
8281:	learn: 0.0014975	total: 13m 49s	remaining: 2m 52s
7661:	learn: 0.0013624	total: 13m 49s	remaining: 4m 13s
8283:	learn: 0.0014002	total: 13m 49s	remaining: 2m 51s
8049:	learn: 0.0016533	total: 13m 49s	remaining: 3m 21s
8284:	learn: 0.0014002	total: 13m 49s	remaining: 2m 51s
8434:	learn: 0.0014233	total: 13m 49s	remaining: 2m 33s
8282:	learn: 0.0014972	total: 13m 49s	remaining: 2m 51s
7662:	learn: 0.0013624	total: 13m 49s	remaining: 4m 13s
8050:	learn: 0.0016533	total: 13m 50s	remaining: 3m 20s
8435:	learn: 0.0014233	total: 13m 49s	remaining: 2m 33s
8285:	learn: 0.0014002	total: 13m 49s	remaining: 2m 51s
8283:	learn: 0.0014972	total: 13m 49s	remaining: 2m 51s
7663:	learn: 0.0013624	total: 13m 50s	remaining: 4m 12s
8436:	learn: 0.0014233	total: 13m 49s	remaining: 2m 33s
8051:	learn: 0.0016533	total: 13m 50s	remaining: 3m 20s
8286:	learn: 0.0014002	total: 13m 50s	remaining: 2m 51s
7664:	learn: 0.0013621	total: 13m 50s	remaining: 4m 12s
8284:	learn: 0.0014972	total: 13m 49s	remaining: 2m 51s
8437:	learn: 0.0014233	total: 13m 50s	remaining: 2m 33s
8052:	learn: 0.0016533	total: 13m 50s	remaining: 3m 20s
8287:	learn: 0.0014002	total: 13m 50s	remaining: 2m 51s
8285:	learn: 0.0014972	total: 13m 49s	remaining: 2m 51s
7665:	learn: 0.0013621	total: 13m 50s	remaining: 4m 12s
8053:	learn: 0.0016533	total: 13m 50s	remaining: 3m 20s
8438:	learn: 0.0014233	total: 13m 50s	remaining: 2m 33s
8288:	learn: 0.0013999	total: 13m 50s	remaining: 2m 51s
8286:	learn: 0.0014972	total: 13m 50s	remaining: 2m 51s
7666:	learn: 0.0013621	total: 13m 50s	remaining: 4m 12s
8054:	learn: 0.0016533	total: 13m 50s	remaining: 3m 20s
8289:	learn: 0.0013999	total: 13m 50s	remaining: 2m 51s
8287:	learn: 0.0014972	total: 13m 50s	remaining: 2m 51s
8439:	learn: 0.0014233	total: 13m 50s	remaining: 2m 33s
7667:	learn: 0.0013621	total: 13m 50s	remaining: 4m 12s
8288:	learn: 0.0014972	total: 13m 50s	remaining: 2m 51s
8055:	learn: 0.0016533	total: 13m 50s	remaining: 3m 20s
8440:	learn: 0.0014233	total: 13m 50s	remaining: 2m 33s
8290:	learn: 0.0013995	total: 13m 50s	remaining: 2m 51s
8289:	learn: 0.0014972	total: 13m 50s	remaining: 2m 51s
8441:	learn: 0.0014233	total: 13m 50s	remaining: 2m 33s
7668:	learn: 0.0013621	total: 13m 50s	remaining: 4m 12s
8056:	learn: 0.0016533	total: 13m 50s	remaining: 3m 20s
8291:	learn: 0.0013995	total: 13m 50s	remaining: 2m 51s
8290:	learn: 0.0014972	total: 13m 50s	remaining: 2m 51s
8442:	learn: 0.0014233	total: 13m 50s	remaining: 2m 33s
7669:	learn: 0.0013621	total: 13m 50s	remaining: 4m 12s
8292:	learn: 0.0013995	total: 13m 50s	remaining: 2m 50s
8057:	learn: 0.0016533	total: 13m 50s	remaining: 3m 20s
8291:	learn: 0.0014972	total: 13m 50s	remaining: 2m 51s
8058:	learn: 0.0016533	total: 13m 50s	remaining: 3m 20s
8293:	learn: 0.0013995	total: 13m 50s	remaining: 2m 50s
8443:	learn: 0.0014232	total: 13m 50s	remaining: 2m 33s
7670:	learn: 0.0013621	total: 13m 50s	remaining: 4m 12s
8292:	learn: 0.0014972	total: 13m 50s	remaining: 2m 50s
8059:	learn: 0.0016533	total: 13m 50s	remaining: 3m 19s
8444:	learn: 0.0014233	total: 13m 50s	remaining: 2m 32s
8294:	learn: 0.0013995	total: 13m 50s	remaining: 2m 50s
7671:	learn: 0.0013621	total: 13m 50s	remaining: 4m 12s
8293:	learn: 0.0014972	total: 13m 50s	remaining: 2m 50s
8060:	learn: 0.0016533	total: 13m 51s	remaining: 3m 19s
8445:	learn: 0.0014233	total: 13m 50s	remaining: 2m 32s
8295:	learn: 0.0013995	total: 13m 50s	remaining: 2m 50s
7672:	learn: 0.0013621	total: 13m 50s	remaining: 4m 12s
8294:	learn: 0.0014972	total: 13m 50s	remaining: 2m 50s
8446:	learn: 0.0014232	total: 13m 50s	remaining: 2m 32s
8296:	learn: 0.0013995	total: 13m 51s	remaining: 2m 50s
8061:	learn: 0.0016533	total: 13m 51s	remaining: 3m 19s
7673:	learn: 0.0013621	total: 13m 51s	remaining: 4m 11s
8295:	learn: 0.0014972	total: 13m 50s	remaining: 2m 50s
8447:	learn: 0.0014233	total: 13m 51s	remaining: 2m 32s
8062:	learn: 0.0016532	total: 13m 51s	remaining: 3m 19s
8297:	learn: 0.0013995	total: 13m 51s	remaining: 2m 50s
7674:	learn: 0.0013621	total: 13m 51s	remaining: 4m 11s
8296:	learn: 0.0014972	total: 13m 50s	remaining: 2m 50s
8448:	learn: 0.0014233	total: 13m 51s	remaining: 2m 32s
8063:	learn: 0.0016532	total: 13m 51s	remaining: 3m 19s
7675:	learn: 0.0013618	total: 13m 51s	remaining: 4m 11s
8298:	learn: 0.0013995	total: 13m 51s	remaining: 2m 50s
8297:	learn: 0.0014972	total: 13m 51s	remaining: 2m 50s
8449:	learn: 0.0014233	total: 13m 51s	remaining: 2m 32s
8064:	learn: 0.0016532	total: 13m 51s	remaining: 3m 19s
7676:	learn: 0.0013618	total: 13m 51s	remaining: 4m 11s
8299:	learn: 0.0013995	total: 13m 51s	remaining: 2m 50s
8298:	learn: 0.0014972	total: 13m 51s	remaining: 2m 50s
8450:	learn: 0.0014233	total: 13m 51s	remaining: 2m 32s
8065:	learn: 0.0016532	total: 13m 51s	remaining: 3m 19s
7677:	learn: 0.0013618	total: 13m 51s	remaining: 4m 11s
8300:	learn: 0.0013995	total: 13m 51s	remaining: 2m 50s
8451:	learn: 0.0014232	total: 13m 51s	remaining: 2m 32s
8299:	learn: 0.0014972	total: 13m 51s	remaining: 2m 50s
8066:	learn: 0.0016526	total: 13m 51s	remaining: 3m 19s
7678:	learn: 0.0013618	total: 13m 51s	remaining: 4m 11s
8301:	learn: 0.0013995	total: 13m 51s	remaining: 2m 50s
8067:	learn: 0.0016526	total: 13m 51s	remaining: 3m 19s
8300:	learn: 0.0014972	total: 13m 51s	remaining: 2m 50s
8452:	learn: 0.0014232	total: 13m 51s	remaining: 2m 32s
8302:	learn: 0.0013995	total: 13m 51s	remaining: 2m 49s
8068:	learn: 0.0016526	total: 13m 51s	remaining: 3m 19s
7679:	learn: 0.0013618	total: 13m 51s	remaining: 4m 11s
8301:	learn: 0.0014972	total: 13m 51s	remaining: 2m 50s
8453:	learn: 0.0014232	total: 13m 51s	remaining: 2m 32s
8303:	learn: 0.0013995	total: 13m 51s	remaining: 2m 49s
7680:	learn: 0.0013618	total: 13m 51s	remaining: 4m 11s
8302:	learn: 0.0014972	total: 13m 51s	remaining: 2m 49s
8069:	learn: 0.0016526	total: 13m 51s	remaining: 3m 18s
8454:	learn: 0.0014233	total: 13m 51s	remaining: 2m 31s
8304:	learn: 0.0013995	total: 13m 51s	remaining: 2m 49s
8303:	learn: 0.0014972	total: 13m 51s	remaining: 2m 49s
8070:	learn: 0.0016526	total: 13m 51s	remaining: 3m 18s
7681:	learn: 0.0013618	total: 13m 51s	remaining: 4m 11s
8455:	learn: 0.0014233	total: 13m 51s	remaining: 2m 31s
8305:	learn: 0.0013995	total: 13m 51s	remaining: 2m 49s
8304:	learn: 0.0014972	total: 13m 51s	remaining: 2m 49s
7682:	learn: 0.0013618	total: 13m 52s	remaining: 4m 10s
8071:	learn: 0.0016525	total: 13m 52s	remaining: 3m 18s
8456:	learn: 0.0014233	total: 13m 51s	remaining: 2m 31s
8306:	learn: 0.0013995	total: 13m 52s	remaining: 2m 49s
8305:	learn: 0.0014972	total: 13m 51s	remaining: 2m 49s
7683:	learn: 0.0013618	total: 13m 52s	remaining: 4m 10s
8457:	learn: 0.0014233	total: 13m 52s	remaining: 2m 31s
8072:	learn: 0.0016525	total: 13m 52s	remaining: 3m 18s
8307:	learn: 0.0013995	total: 13m 52s	remaining: 2m 49s
8306:	learn: 0.0014972	total: 13m 51s	remaining: 2m 49s
7684:	learn: 0.0013618	total: 13m 52s	remaining: 4m 10s
8458:	learn: 0.0014233	total: 13m 52s	remaining: 2m 31s
8308:	learn: 0.0013995	total: 13m 52s	remaining: 2m 49s
8073:	learn: 0.0016524	total: 13m 52s	remaining: 3m 18s
7685:	learn: 0.0013618	total: 13m 52s	remaining: 4m 10s
8459:	learn: 0.0014228	total: 13m 52s	remaining: 2m 31s
8307:	learn: 0.0014972	total: 13m 52s	remaining: 2m 49s
8074:	learn: 0.0016517	total: 13m 52s	remaining: 3m 18s
8309:	learn: 0.0013995	total: 13m 52s	remaining: 2m 49s
7686:	learn: 0.0013618	total: 13m 52s	remaining: 4m 10s
8460:	learn: 0.0014228	total: 13m 52s	remaining: 2m 31s
8308:	learn: 0.0014972	total: 13m 52s	remaining: 2m 49s
8310:	learn: 0.0013991	total: 13m 52s	remaining: 2m 49s
8075:	learn: 0.0016517	total: 13m 52s	remaining: 3m 18s
8461:	learn: 0.0014228	total: 13m 52s	remaining: 2m 31s
7687:	learn: 0.0013618	total: 13m 52s	remaining: 4m 10s
8311:	learn: 0.0013991	total: 13m 52s	remaining: 2m 49s
8309:	learn: 0.0014972	total: 13m 52s	remaining: 2m 49s

8076:	learn: 0.0016517	total: 13m 52s	remaining: 3m 18s
8312:	learn: 0.0013991	total: 13m 52s	remaining: 2m 48s
8462:	learn: 0.0014228	total: 13m 52s	remaining: 2m 31s
8310:	learn: 0.0014972	total: 13m 52s	remaining: 2m 49s
7688:	learn: 0.0013618	total: 13m 52s	remaining: 4m 10s
8077:	learn: 0.0016517	total: 13m 52s	remaining: 3m 18s
8311:	learn: 0.0014972	total: 13m 52s	remaining: 2m 49s
8463:	learn: 0.0014228	total: 13m 52s	remaining: 2m 31s
8313:	learn: 0.0013991	total: 13m 52s	remaining: 2m 48s
7689:	learn: 0.0013618	total: 13m 52s	remaining: 4m 10s
8078:	learn: 0.0016517	total: 13m 52s	remaining: 3m 18s
8314:	learn: 0.0013991	total: 13m 52s	remaining: 2m 48s
8312:	learn: 0.0014972	total: 13m 52s	remaining: 2m 48s
8464:	learn: 0.0014228	total: 13m 52s	remaining: 2m 31s
7690:	learn: 0.0013618	total: 13m 52s	remaining: 4m 10s
8079:	learn: 0.0016517	total: 13m 52s	remaining: 3m 17s
8315:	learn: 0.0013991	total: 13m 52s	remaining: 2m 48s
8313:	learn: 0.0014972	total: 13m 52s	remaining: 2m 48s
8465:	learn: 0.0014228	total: 13m 52s	remaining: 2m 30s
7691:	learn: 0.0013618	total: 13m 52s	remaining: 4m 9s
8466:	learn: 0.0014228	total: 13m 52s	remaining: 2m 30s
8316:	learn: 0.0013991	total: 13m 53s	remaining: 2m 48s
8314:	learn: 0.0014972	total: 13m 52s	remaining: 2m 48s
8080:	learn: 0.0016517	total: 13m 53s	remaining: 3m 17s
7692:	learn: 0.0013618	total: 13m 53s	remaining: 4m 9s
8317:	learn: 0.0013991	total: 13m 53s	remaining: 2m 48s
8467:	learn: 0.0014228	total: 13m 52s	remaining: 2m 30s
8315:	learn: 0.0014972	total: 13m 52s	remaining: 2m 48s
7693:	learn: 0.0013618	total: 13m 53s	remaining: 4m 9s
8081:	learn: 0.0016517	total: 13m 53s	remaining: 3m 17s
8468:	learn: 0.0014228	total: 13m 53s	remaining: 2m 30s
8318:	learn: 0.0013991	total: 13m 53s	remaining: 2m 48s
8316:	learn: 0.0014972	total: 13m 52s	remaining: 2m 48s
7694:	learn: 0.0013618	total: 13m 53s	remaining: 4m 9s
8082:	learn: 0.0016517	total: 13m 53s	remaining: 3m 17s
8469:	learn: 0.0014228	total: 13m 53s	remaining: 2m 30s
8319:	learn: 0.0013991	total: 13m 53s	remaining: 2m 48s
8317:	learn: 0.0014971	total: 13m 53s	remaining: 2m 48s
7695:	learn: 0.0013618	total: 13m 53s	remaining: 4m 9s
8083:	learn: 0.0016517	total: 13m 53s	remaining: 3m 17s
8320:	learn: 0.0013991	total: 13m 53s	remaining: 2m 48s
8470:	learn: 0.0014228	total: 13m 53s	remaining: 2m 30s
7696:	learn: 0.0013618	total: 13m 53s	remaining: 4m 9s
8318:	learn: 0.0014971	total: 13m 53s	remaining: 2m 48s
8084:	learn: 0.0016517	total: 13m 53s	remaining: 3m 17s
8321:	learn: 0.0013991	total: 13m 53s	remaining: 2m 48s
8471:	learn: 0.0014228	total: 13m 53s	remaining: 2m 30s
8319:	learn: 0.0014971	total: 13m 53s	remaining: 2m 48s
7697:	learn: 0.0013618	total: 13m 53s	remaining: 4m 9s
8322:	learn: 0.0013991	total: 13m 53s	remaining: 2m 47s
8085:	learn: 0.0016517	total: 13m 53s	remaining: 3m 17s
8472:	learn: 0.0014228	total: 13m 53s	remaining: 2m 30s
7698:	learn: 0.0013618	total: 13m 53s	remaining: 4m 9s
8320:	learn: 0.0014971	total: 13m 53s	remaining: 2m 48s
8323:	learn: 0.0013991	total: 13m 53s	remaining: 2m 47s
8086:	learn: 0.0016517	total: 13m 53s	remaining: 3m 17s
8473:	learn: 0.0014228	total: 13m 53s	remaining: 2m 30s
7699:	learn: 0.0013618	total: 13m 53s	remaining: 4m 9s
8321:	learn: 0.0014971	total: 13m 53s	remaining: 2m 48s
8324:	learn: 0.0013991	total: 13m 53s	remaining: 2m 47s
8087:	learn: 0.0016517	total: 13m 53s	remaining: 3m 17s
8474:	learn: 0.0014228	total: 13m 53s	remaining: 2m 30s
7700:	learn: 0.0013618	total: 13m 53s	remaining: 4m 8s
8325:	learn: 0.0013990	total: 13m 53s	remaining: 2m 47s
8322:	learn: 0.0014971	total: 13m 53s	remaining: 2m 47s
8088:	learn: 0.0016517	total: 13m 53s	remaining: 3m 17s
8475:	learn: 0.0014228	total: 13m 53s	remaining: 2m 29s
7701:	learn: 0.0013618	total: 13m 53s	remaining: 4m 8s
8326:	learn: 0.0013990	total: 13m 53s	remaining: 2m 47s
8476:	learn: 0.0014228	total: 13m 53s	remaining: 2m 29s
8323:	learn: 0.0014970	total: 13m 53s	remaining: 2m 47s
8089:	learn: 0.0016517	total: 13m 54s	remaining: 3m 16s
7702:	learn: 0.0013618	total: 13m 54s	remaining: 4m 8s
8327:	learn: 0.0013990	total: 13m 54s	remaining: 2m 47s
8477:	learn: 0.0014228	total: 13m 53s	remaining: 2m 29s
8324:	learn: 0.0014970	total: 13m 53s	remaining: 2m 47s
8090:	learn: 0.0016517	total: 13m 54s	remaining: 3m 16s
8328:	learn: 0.0013991	total: 13m 54s	remaining: 2m 47s
8325:	learn: 0.0014964	total: 13m 53s	remaining: 2m 47s
7703:	learn: 0.0013618	total: 13m 54s	remaining: 4m 8s
8478:	learn: 0.0014228	total: 13m 54s	remaining: 2m 29s
8091:	learn: 0.0016515	total: 13m 54s	remaining: 3m 16s
7704:	learn: 0.0013618	total: 13m 54s	remaining: 4m 8s
8329:	learn: 0.0013991	total: 13m 54s	remaining: 2m 47s
8326:	learn: 0.0014964	total: 13m 54s	remaining: 2m 47s
8092:	learn: 0.0016515	total: 13m 54s	remaining: 3m 16s
8479:	learn: 0.0014228	total: 13m 54s	remaining: 2m 29s
8327:	learn: 0.0014964	total: 13m 54s	remaining: 2m 47s
7705:	learn: 0.0013618	total: 13m 54s	remaining: 4m 8s
8330:	learn: 0.0013991	total: 13m 54s	remaining: 2m 47s
8093:	learn: 0.0016508	total: 13m 54s	remaining: 3m 16s
8480:	learn: 0.0014228	total: 13m 54s	remaining: 2m 29s
8328:	learn: 0.0014964	total: 13m 54s	remaining: 2m 47s
8331:	learn: 0.0013990	total: 13m 54s	remaining: 2m 47s
7706:	learn: 0.0013618	total: 13m 54s	remaining: 4m 8s
8481:	learn: 0.0014223	total: 13m 54s	remaining: 2m 29s
8094:	learn: 0.0016508	total: 13m 54s	remaining: 3m 16s
8332:	learn: 0.0013991	total: 13m 54s	remaining: 2m 46s
7707:	learn: 0.0013618	total: 13m 54s	remaining: 4m 8s
8329:	learn: 0.0014964	total: 13m 54s	remaining: 2m 47s
8482:	learn: 0.0014223	total: 13m 54s	remaining: 2m 29s
8095:	learn: 0.0016504	total: 13m 54s	remaining: 3m 16s
8333:	learn: 0.0013991	total: 13m 54s	remaining: 2m 46s
7708:	learn: 0.0013618	total: 13m 54s	remaining: 4m 8s
8483:	learn: 0.0014223	total: 13m 54s	remaining: 2m 29s
8330:	learn: 0.0014964	total: 13m 54s	remaining: 2m 47s
8096:	learn: 0.0016502	total: 13m 54s	remaining: 3m 16s
8334:	learn: 0.0013991	total: 13m 54s	remaining: 2m 46s
7709:	learn: 0.0013618	total: 13m 54s	remaining: 4m 7s
8484:	learn: 0.0014223	total: 13m 54s	remaining: 2m 29s
8331:	learn: 0.0014961	total: 13m 54s	remaining: 2m 47s
8097:	learn: 0.0016502	total: 13m 54s	remaining: 3m 16s
8335:	learn: 0.0013990	total: 13m 54s	remaining: 2m 46s
7710:	learn: 0.0013618	total: 13m 54s	remaining: 4m 7s
8485:	learn: 0.0014223	total: 13m 54s	remaining: 2m 28s
8098:	learn: 0.0016502	total: 13m 54s	remaining: 3m 15s
8332:	learn: 0.0014956	total: 13m 54s	remaining: 2m 46s
8336:	learn: 0.0013986	total: 13m 54s	remaining: 2m 46s
7711:	learn: 0.0013618	total: 13m 54s	remaining: 4m 7s
8486:	learn: 0.0014223	total: 13m 54s	remaining: 2m 28s
8333:	learn: 0.0014953	total: 13m 54s	remaining: 2m 46s
8099:	learn: 0.0016502	total: 13m 55s	remaining: 3m 15s
8337:	learn: 0.0013985	total: 13m 55s	remaining: 2m 46s
7712:	learn: 0.0013618	total: 13m 55s	remaining: 4m 7s
8487:	learn: 0.0014223	total: 13m 54s	remaining: 2m 28s
8334:	learn: 0.0014953	total: 13m 54s	remaining: 2m 46s
8100:	learn: 0.0016502	total: 13m 55s	remaining: 3m 15s
8338:	learn: 0.0013985	total: 13m 55s	remaining: 2m 46s
8488:	learn: 0.0014223	total: 13m 55s	remaining: 2m 28s
7713:	learn: 0.0013618	total: 13m 55s	remaining: 4m 7s
8101:	learn: 0.0016502	total: 13m 55s	remaining: 3m 15s
8335:	learn: 0.0014953	total: 13m 54s	remaining: 2m 46s
8339:	learn: 0.0013985	total: 13m 55s	remaining: 2m 46s
8489:	learn: 0.0014223	total: 13m 55s	remaining: 2m 28s
8102:	learn: 0.0016498	total: 13m 55s	remaining: 3m 15s
7714:	learn: 0.0013618	total: 13m 55s	remaining: 4m 7s
8340:	learn: 0.0013985	total: 13m 55s	remaining: 2m 46s
8336:	learn: 0.0014953	total: 13m 55s	remaining: 2m 46s
8490:	learn: 0.0014223	total: 13m 55s	remaining: 2m 28s
8103:	learn: 0.0016498	total: 13m 55s	remaining: 3m 15s
8337:	learn: 0.0014953	total: 13m 55s	remaining: 2m 46s
7715:	learn: 0.0013618	total: 13m 55s	remaining: 4m 7s
8341:	learn: 0.0013985	total: 13m 55s	remaining: 2m 46s
8491:	learn: 0.0014223	total: 13m 55s	remaining: 2m 28s
8104:	learn: 0.0016498	total: 13m 55s	remaining: 3m 15s
7716:	learn: 0.0013618	total: 13m 55s	remaining: 4m 7s
8338:	learn: 0.0014953	total: 13m 55s	remaining: 2m 46s
8342:	learn: 0.0013982	total: 13m 55s	remaining: 2m 45s
8105:	learn: 0.0016497	total: 13m 55s	remaining: 3m 15s
7717:	learn: 0.0013618	total: 13m 55s	remaining: 4m 7s
8339:	learn: 0.0014953	total: 13m 55s	remaining: 2m 46s
8493:	learn: 0.0014223	total: 13m 55s	remaining: 2m 28s
8343:	learn: 0.0013978	total: 13m 55s	remaining: 2m 45s
8106:	learn: 0.0016497	total: 13m 55s	remaining: 3m 15s
7718:	learn: 0.0013618	total: 13m 55s	remaining: 4m 6s
8340:	learn: 0.0014953	total: 13m 55s	remaining: 2m 46s
8344:	learn: 0.0013978	total: 13m 55s	remaining: 2m 45s
8494:	learn: 0.0014223	total: 13m 55s	remaining: 2m 28s
8107:	learn: 0.0016497	total: 13m 55s	remaining: 3m 15s
7719:	learn: 0.0013618	total: 13m 55s	remaining: 4m 6s
8345:	learn: 0.0013978	total: 13m 55s	remaining: 2m 45s
8495:	learn: 0.0014223	total: 13m 55s	remaining: 2m 27s
8341:	learn: 0.0014953	total: 13m 55s	remaining: 2m 46s
7720:	learn: 0.0013618	total: 13m 55s	remaining: 4m 6s
8108:	learn: 0.0016497	total: 13m 55s	remaining: 3m 14s
8496:	learn: 0.0014223	total: 13m 55s	remaining: 2m 27s
8346:	learn: 0.0013975	total: 13m 55s	remaining: 2m 45s
8342:	learn: 0.0014953	total: 13m 55s	remaining: 2m 45s
8109:	learn: 0.0016497	total: 13m 56s	remaining: 3m 14s
7721:	learn: 0.0013617	total: 13m 55s	remaining: 4m 6s
8343:	learn: 0.0014953	total: 13m 55s	remaining: 2m 45s
8497:	learn: 0.0014223	total: 13m 55s	remaining: 2m 27s
8347:	learn: 0.0013975	total: 13m 56s	remaining: 2m 45s
7722:	learn: 0.0013617	total: 13m 56s	remaining: 4m 6s
8110:	learn: 0.0016497	total: 13m 56s	remaining: 3m 14s
8344:	learn: 0.0014953	total: 13m 55s	remaining: 2m 45s
8348:	learn: 0.0013975	total: 13m 56s	remaining: 2m 45s
8498:	learn: 0.0014223	total: 13m 56s	remaining: 2m 27s
7723:	learn: 0.0013617	total: 13m 56s	remaining: 4m 6s
8111:	learn: 0.0016494	total: 13m 56s	remaining: 3m 14s
8345:	learn: 0.0014953	total: 13m 55s	remaining: 2m 45s
8349:	learn: 0.0013975	total: 13m 56s	remaining: 2m 45s
8499:	learn: 0.0014223	total: 13m 56s	remaining: 2m 27s
7724:	learn: 0.0013617	total: 13m 56s	remaining: 4m 6s
8346:	learn: 0.0014953	total: 13m 56s	remaining: 2m 45s
8112:	learn: 0.0016489	total: 13m 56s	remaining: 3m 14s
8350:	learn: 0.0013975	total: 13m 56s	remaining: 2m 45s
8500:	learn: 0.0014223	total: 13m 56s	remaining: 2m 27s
8347:	learn: 0.0014953	total: 13m 56s	remaining: 2m 45s
7725:	learn: 0.0013617	total: 13m 56s	remaining: 4m 6s
8113:	learn: 0.0016489	total: 13m 56s	remaining: 3m 14s
8501:	learn: 0.0014223	total: 13m 56s	remaining: 2m 27s
8351:	learn: 0.0013975	total: 13m 56s	remaining: 2m 45s
8348:	learn: 0.0014953	total: 13m 56s	remaining: 2m 45s
7726:	learn: 0.0013617	total: 13m 56s	remaining: 4m 6s
8114:	learn: 0.0016489	total: 13m 56s	remaining: 3m 14s
8502:	learn: 0.0014223	total: 13m 56s	remaining: 2m 27s
8352:	learn: 0.0013974	total: 13m 56s	remaining: 2m 44s
8349:	learn: 0.0014953	total: 13m 56s	remaining: 2m 45s
7727:	learn: 0.0013617	total: 13m 56s	remaining: 4m 5s
8115:	learn: 0.0016487	total: 13m 56s	remaining: 3m 14s
8353:	learn: 0.0013975	total: 13m 56s	remaining: 2m 44s
8503:	learn: 0.0014223	total: 13m 56s	remaining: 2m 27s
8350:	learn: 0.0014953	total: 13m 56s	remaining: 2m 45s
8354:	learn: 0.0013974	total: 13m 56s	remaining: 2m 44s
8116:	learn: 0.0016487	total: 13m 56s	remaining: 3m 14s
8504:	learn: 0.0014223	total: 13m 56s	remaining: 2m 27s
7728:	learn: 0.0013617	total: 13m 56s	remaining: 4m 5s
8351:	learn: 0.0014953	total: 13m 56s	remaining: 2m 45s
8355:	learn: 0.0013974	total: 13m 56s	remaining: 2m 44s
8505:	learn: 0.0014223	total: 13m 56s	remaining: 2m 26s
8117:	learn: 0.0016487	total: 13m 56s	remaining: 3m 14s
7729:	learn: 0.0013617	total: 13m 56s	remaining: 4m 5s
8352:	learn: 0.0014953	total: 13m 56s	remaining: 2m 44s
8356:	learn: 0.0013974	total: 13m 56s	remaining: 2m 44s
8506:	learn: 0.0014223	total: 13m 56s	remaining: 2m 26s
8118:	learn: 0.0016487	total: 13m 56s	remaining: 3m 13s
7730:	learn: 0.0013617	total: 13m 56s	remaining: 4m 5s
8353:	learn: 0.0014953	total: 13m 56s	remaining: 2m 44s
8119:	learn: 0.0016487	total: 13m 57s	remaining: 3m 13s
8507:	learn: 0.0014223	total: 13m 56s	remaining: 2m 26s
8357:	learn: 0.0013974	total: 13m 57s	remaining: 2m 44s
7731:	learn: 0.0013617	total: 13m 57s	remaining: 4m 5s
8508:	learn: 0.0014223	total: 13m 56s	remaining: 2m 26s
8120:	learn: 0.0016487	total: 13m 57s	remaining: 3m 13s
8354:	learn: 0.0014953	total: 13m 56s	remaining: 2m 44s
8358:	learn: 0.0013974	total: 13m 57s	remaining: 2m 44s
7732:	learn: 0.0013617	total: 13m 57s	remaining: 4m 5s
8121:	learn: 0.0016487	total: 13m 57s	remaining: 3m 13s
8509:	learn: 0.0014218	total: 13m 57s	remaining: 2m 26s
8355:	learn: 0.0014953	total: 13m 56s	remaining: 2m 44s
8122:	learn: 0.0016487	total: 13m 57s	remaining: 3m 13s
8359:	learn: 0.0013974	total: 13m 57s	remaining: 2m 44s
7733:	learn: 0.0013617	total: 13m 57s	remaining: 4m 5s
8510:	learn: 0.0014214	total: 13m 57s	remaining: 2m 26s
8356:	learn: 0.0014953	total: 13m 57s	remaining: 2m 44s
8123:	learn: 0.0016486	total: 13m 57s	remaining: 3m 13s
8360:	learn: 0.0013974	total: 13m 57s	remaining: 2m 44s
7734:	learn: 0.0013617	total: 13m 57s	remaining: 4m 5s
8511:	learn: 0.0014211	total: 13m 57s	remaining: 2m 26s
8357:	learn: 0.0014953	total: 13m 57s	remaining: 2m 44s
8512:	learn: 0.0014211	total: 13m 57s	remaining: 2m 26s
8124:	learn: 0.0016486	total: 13m 57s	remaining: 3m 13s
8361:	learn: 0.0013974	total: 13m 57s	remaining: 2m 44s
7735:	learn: 0.0013617	total: 13m 57s	remaining: 4m 5s
8358:	learn: 0.0014953	total: 13m 57s	remaining: 2m 44s
8513:	learn: 0.0014211	total: 13m 57s	remaining: 2m 26s
8125:	learn: 0.0016486	total: 13m 57s	remaining: 3m 13s
8362:	learn: 0.0013974	total: 13m 57s	remaining: 2m 43s
7736:	learn: 0.0013617	total: 13m 57s	remaining: 4m 4s
8514:	learn: 0.0014211	total: 13m 57s	remaining: 2m 26s
8359:	learn: 0.0014952	total: 13m 57s	remaining: 2m 44s
8363:	learn: 0.0013974	total: 13m 57s	remaining: 2m 43s
8126:	learn: 0.0016486	total: 13m 57s	remaining: 3m 13s
7737:	learn: 0.0013617	total: 13m 57s	remaining: 4m 4s
8515:	learn: 0.0014211	total: 13m 57s	remaining: 2m 25s
8360:	learn: 0.0014953	total: 13m 57s	remaining: 2m 44s
8364:	learn: 0.0013974	total: 13m 57s	remaining: 2m 43s
8127:	learn: 0.0016486	total: 13m 57s	remaining: 3m 12s
8516:	learn: 0.0014211	total: 13m 57s	remaining: 2m 25s
7738:	learn: 0.0013617	total: 13m 57s	remaining: 4m 4s
8361:	learn: 0.0014953	total: 13m 57s	remaining: 2m 44s
8365:	learn: 0.0013974	total: 13m 57s	remaining: 2m 43s
8517:	learn: 0.0014211	total: 13m 57s	remaining: 2m 25s
8128:	learn: 0.0016483	total: 13m 57s	remaining: 3m 12s
7739:	learn: 0.0013617	total: 13m 57s	remaining: 4m 4s
8362:	learn: 0.0014953	total: 13m 57s	remaining: 2m 43s
8366:	learn: 0.0013974	total: 13m 57s	remaining: 2m 43s
8518:	learn: 0.0014207	total: 13m 57s	remaining: 2m 25s
8363:	learn: 0.0014953	total: 13m 57s	remaining: 2m 43s
8129:	learn: 0.0016483	total: 13m 58s	remaining: 3m 12s
7740:	learn: 0.0013617	total: 13m 58s	remaining: 4m 4s
8367:	learn: 0.0013974	total: 13m 58s	remaining: 2m 43s
8519:	learn: 0.0014207	total: 13m 57s	remaining: 2m 25s
8364:	learn: 0.0014952	total: 13m 57s	remaining: 2m 43s
7741:	learn: 0.0013617	total: 13m 58s	remaining: 4m 4s
8130:	learn: 0.0016483	total: 13m 58s	remaining: 3m 12s
8368:	learn: 0.0013974	total: 13m 58s	remaining: 2m 43s
8520:	learn: 0.0014207	total: 13m 58s	remaining: 2m 25s
8365:	learn: 0.0014953	total: 13m 57s	remaining: 2m 43s
7742:	learn: 0.0013617	total: 13m 58s	remaining: 4m 4s
8521:	learn: 0.0014207	total: 13m 58s	remaining: 2m 25s
8131:	learn: 0.0016483	total: 13m 58s	remaining: 3m 12s
8369:	learn: 0.0013974	total: 13m 58s	remaining: 2m 43s
8366:	learn: 0.0014953	total: 13m 58s	remaining: 2m 43s
8132:	learn: 0.0016483	total: 13m 58s	remaining: 3m 12s
8522:	learn: 0.0014207	total: 13m 58s	remaining: 2m 25s
7743:	learn: 0.0013617	total: 13m 58s	remaining: 4m 4s
8370:	learn: 0.0013974	total: 13m 58s	remaining: 2m 43s
8133:	learn: 0.0016483	total: 13m 58s	remaining: 3m 12s
8367:	learn: 0.0014953	total: 13m 58s	remaining: 2m 43s
 12m 32s	remaining: 3m 52s

7294:	learn: 0.0019490	total:8523:	learn: 0.0014207	total: 13m 58s	remaining: 2m 25s
7744:	learn: 0.0013617	total: 13m 58s	remaining: 4m 4s
8134:	learn: 0.0016479	total: 13m 58s	remaining: 3m 12s
8371:	learn: 0.0013974	total: 13m 58s	remaining: 2m 43s
8368:	learn: 0.0014953	total: 13m 58s	remaining: 2m 43s
7745:	learn: 0.0013617	total: 13m 58s	remaining: 4m 4s
8524:	learn: 0.0014207	total: 13m 58s	remaining: 2m 25s
8135:	learn: 0.0016479	total: 13m 58s	remaining: 3m 12s
8372:	learn: 0.0013973	total: 13m 58s	remaining: 2m 42s
8369:	learn: 0.0014953	total: 13m 58s	remaining: 2m 43s
7746:	learn: 0.0013617	total: 13m 58s	remaining: 4m 3s
8525:	learn: 0.0014207	total: 13m 58s	remaining: 2m 24s
8373:	learn: 0.0013973	total: 13m 58s	remaining: 2m 42s
8370:	learn: 0.0014953	total: 13m 58s	remaining: 2m 43s
8136:	learn: 0.0016479	total: 13m 58s	remaining: 3m 12s
7747:	learn: 0.0013617	total: 13m 58s	remaining: 4m 3s
8526:	learn: 0.0014207	total: 13m 58s	remaining: 2m 24s
8374:	learn: 0.0013973	total: 13m 58s	remaining: 2m 42s
8371:	learn: 0.0014953	total: 13m 58s	remaining: 2m 43s
8137:	learn: 0.0016479	total: 13m 58s	remaining: 3m 11s
7748:	learn: 0.0013617	total: 13m 58s	remaining: 4m 3s
8372:	learn: 0.0014949	total: 13m 58s	remaining: 2m 42s
8527:	learn: 0.0014207	total: 13m 58s	remaining: 2m 24s
8375:	learn: 0.0013973	total: 13m 58s	remaining: 2m 42s
8138:	learn: 0.0016479	total: 13m 58s	remaining: 3m 11s
8373:	learn: 0.0014949	total: 13m 58s	remaining: 2m 42s
7749:	learn: 0.0013617	total: 13m 58s	remaining: 4m 3s
8376:	learn: 0.0013973	total: 13m 58s	remaining: 2m 42s
8528:	learn: 0.0014207	total: 13m 58s	remaining: 2m 24s
8139:	learn: 0.0016479	total: 13m 59s	remaining: 3m 11s
8374:	learn: 0.0014949	total: 13m 58s	remaining: 2m 42s
8377:	learn: 0.0013973	total: 13m 59s	remaining: 2m 42s
7750:	learn: 0.0013617	total: 13m 59s	remaining: 4m 3s
8529:	learn: 0.0014207	total: 13m 58s	remaining: 2m 24s
8140:	learn: 0.0016479	total: 13m 59s	remaining: 3m 11s
8375:	learn: 0.0014949	total: 13m 58s	remaining: 2m 42s
8378:	learn: 0.0013973	total: 13m 59s	remaining: 2m 42s
8530:	learn: 0.0014207	total: 13m 59s	remaining: 2m 24s
7751:	learn: 0.0013617	total: 13m 59s	remaining: 4m 3s
8376:	learn: 0.0014950	total: 13m 58s	remaining: 2m 42s
8141:	learn: 0.0016479	total: 13m 59s	remaining: 3m 11s
8379:	learn: 0.0013973	total: 13m 59s	remaining: 2m 42s
8531:	learn: 0.0014207	total: 13m 59s	remaining: 2m 24s
8377:	learn: 0.0014949	total: 13m 59s	remaining: 2m 42s
8142:	learn: 0.0016479	total: 13m 59s	remaining: 3m 11s
7752:	learn: 0.0013616	total: 13m 59s	remaining: 4m 3s
8380:	learn: 0.0013973	total: 13m 59s	remaining: 2m 42s
8532:	learn: 0.0014207	total: 13m 59s	remaining: 2m 24s
8378:	learn: 0.0014949	total: 13m 59s	remaining: 2m 42s
8143:	learn: 0.0016479	total: 13m 59s	remaining: 3m 11s
8381:	learn: 0.0013973	total: 13m 59s	remaining: 2m 42s
7753:	learn: 0.0013616	total: 13m 59s	remaining: 4m 3s
8379:	learn: 0.0014949	total: 13m 59s	remaining: 2m 42s
8533:	learn: 0.0014206	total: 13m 59s	remaining: 2m 24s
8144:	learn: 0.0016479	total: 13m 59s	remaining: 3m 11s
8382:	learn: 0.0013970	total: 13m 59s	remaining: 2m 41s
7754:	learn: 0.0013615	total: 13m 59s	remaining: 4m 3s
8380:	learn: 0.0014949	total: 13m 59s	remaining: 2m 42s
8534:	learn: 0.0014206	total: 13m 59s	remaining: 2m 24s
8383:	learn: 0.0013969	total: 13m 59s	remaining: 2m 41s
8145:	learn: 0.0016475	total: 13m 59s	remaining: 3m 11s
7755:	learn: 0.0013615	total: 13m 59s	remaining: 4m 2s
8381:	learn: 0.0014949	total: 13m 59s	remaining: 2m 42s
8535:	learn: 0.0014206	total: 13m 59s	remaining: 2m 23s
7756:	learn: 0.0013615	total: 13m 59s	remaining: 4m 2s
8146:	learn: 0.0016475	total: 13m 59s	remaining: 3m 11s
8384:	learn: 0.0013970	total: 13m 59s	remaining: 2m 41s
8382:	learn: 0.0014950	total: 13m 59s	remaining: 2m 41s
8536:	learn: 0.0014206	total: 13m 59s	remaining: 2m 23s
8147:	learn: 0.0016470	total: 13m 59s	remaining: 3m 10s
7757:	learn: 0.0013615	total: 13m 59s	remaining: 4m 2s
8383:	learn: 0.0014949	total: 13m 59s	remaining: 2m 41s
8385:	learn: 0.0013969	total: 13m 59s	remaining: 2m 41s
8537:	learn: 0.0014203	total: 13m 59s	remaining: 2m 23s
8148:	learn: 0.0016470	total: 13m 59s	remaining: 3m 10s
7758:	learn: 0.0013615	total: 13m 59s	remaining: 4m 2s
8384:	learn: 0.0014949	total: 13m 59s	remaining: 2m 41s
8538:	learn: 0.0014202	total: 13m 59s	remaining: 2m 23s
8386:	learn: 0.0013969	total: 13m 59s	remaining: 2m 41s
7759:	learn: 0.0013615	total: 14m	remaining: 4m 2s
8149:	learn: 0.0016466	total: 14m	remaining: 3m 10s
8385:	learn: 0.0014949	total: 13m 59s	remaining: 2m 41s
8539:	learn: 0.0014202	total: 13m 59s	remaining: 2m 23s
8387:	learn: 0.0013969	total: 14m	remaining: 2m 41s
8386:	learn: 0.0014949	total: 13m 59s	remaining: 2m 41s
7760:	learn: 0.0013615	total: 14m	remaining: 4m 2s
8150:	learn: 0.0016466	total: 14m	remaining: 3m 10s
8540:	learn: 0.0014202	total: 14m	remaining: 2m 23s
8388:	learn: 0.0013969	total: 14m	remaining: 2m 41s
8387:	learn: 0.0014949	total: 13m 59s	remaining: 2m 41s
7761:	learn: 0.0013615	total: 14m	remaining: 4m 2s
8389:	learn: 0.0013969	total: 14m	remaining: 2m 41s
8151:	learn: 0.0016465	total: 14m	remaining: 3m 10s
8541:	learn: 0.0014202	total: 14m	remaining: 2m 23s
8388:	learn: 0.0014949	total: 14m	remaining: 2m 41s
8390:	learn: 0.0013969	total: 14m	remaining: 2m 41s
8542:	learn: 0.0014202	total: 14m	remaining: 2m 23s
7762:	learn: 0.0013615	total: 14m	remaining: 4m 2s
8152:	learn: 0.0016466	total: 14m	remaining: 3m 10s
8389:	learn: 0.0014949	total: 14m	remaining: 2m 41s
8391:	learn: 0.0013969	total: 14m	remaining: 2m 41s
7763:	learn: 0.0013615	total: 14m	remaining: 4m 2s
8543:	learn: 0.0014202	total: 14m	remaining: 2m 23s
8153:	learn: 0.0016466	total: 14m	remaining: 3m 10s
8390:	learn: 0.0014949	total: 14m	remaining: 2m 41s
8392:	learn: 0.0013969	total: 14m	remaining: 2m 40s
7764:	learn: 0.0013615	total: 14m	remaining: 4m 1s
8544:	learn: 0.0014202	total: 14m	remaining: 2m 23s
8154:	learn: 0.0016462	total: 14m	remaining: 3m 10s
8391:	learn: 0.0014949	total: 14m	remaining: 2m 41s
8393:	learn: 0.0013969	total: 14m	remaining: 2m 40s
7765:	learn: 0.0013613	total: 14m	remaining: 4m 1s
8545:	learn: 0.0014202	total: 14m	remaining: 2m 23s
8392:	learn: 0.0014949	total: 14m	remaining: 2m 40s
8394:	learn: 0.0013969	total: 14m	remaining: 2m 40s
8155:	learn: 0.0016462	total: 14m	remaining: 3m 10s
8546:	learn: 0.0014202	total: 14m	remaining: 2m 22s
8393:	learn: 0.0014949	total: 14m	remaining: 2m 40s
7766:	learn: 0.0013613	total: 14m	remaining: 4m 1s
8156:	learn: 0.0016460	total: 14m	remaining: 3m 9s
8395:	learn: 0.0013968	total: 14m	remaining: 2m 40s
8547:	learn: 0.0014202	total: 14m	remaining: 2m 22s
8394:	learn: 0.0014949	total: 14m	remaining: 2m 40s
8157:	learn: 0.0016460	total: 14m	remaining: 3m 9s
7767:	learn: 0.0013613	total: 14m	remaining: 4m 1s
8548:	learn: 0.0014202	total: 14m	remaining: 2m 22s
8396:	learn: 0.0013965	total: 14m	remaining: 2m 40s
8395:	learn: 0.0014949	total: 14m	remaining: 2m 40s
8158:	learn: 0.0016455	total: 14m 1s	remaining: 3m 9s
8397:	learn: 0.0013961	total: 14m 1s	remaining: 2m 40s
8549:	learn: 0.0014202	total: 14m	remaining: 2m 22s
7768:	learn: 0.0013613	total: 14m 1s	remaining: 4m 1s
8398:	learn: 0.0013957	total: 14m 1s	remaining: 2m 40s
8396:	learn: 0.0014949	total: 14m	remaining: 2m 40s
8550:	learn: 0.0014202	total: 14m	remaining: 2m 22s
7769:	learn: 0.0013611	total: 14m 1s	remaining: 4m 1s
8159:	learn: 0.0016455	total: 14m 1s	remaining: 3m 9s
8551:	learn: 0.0014202	total: 14m 1s	remaining: 2m 22s
8399:	learn: 0.0013957	total: 14m 1s	remaining: 2m 40s
7770:	learn: 0.0013611	total: 14m 1s	remaining: 4m 1s
8397:	learn: 0.0014949	total: 14m	remaining: 2m 40s
8160:	learn: 0.0016455	total: 14m 1s	remaining: 3m 9s
8552:	learn: 0.0014202	total: 14m 1s	remaining: 2m 22s
7771:	learn: 0.0013611	total: 14m 1s	remaining: 4m 1s
8398:	learn: 0.0014949	total: 14m 1s	remaining: 2m 40s
8400:	learn: 0.0013957	total: 14m 1s	remaining: 2m 40s
8553:	learn: 0.0014202	total: 14m 1s	remaining: 2m 22s
8161:	learn: 0.0016455	total: 14m 1s	remaining: 3m 9s
8399:	learn: 0.0014949	total: 14m 1s	remaining: 2m 40s
7772:	learn: 0.0013611	total: 14m 1s	remaining: 4m 1s
8401:	learn: 0.0013957	total: 14m 1s	remaining: 2m 40s
8554:	learn: 0.0014202	total: 14m 1s	remaining: 2m 22s
8400:	learn: 0.0014949	total: 14m 1s	remaining: 2m 40s
8162:	learn: 0.0016455	total: 14m 1s	remaining: 3m 9s
8402:	learn: 0.0013957	total: 14m 1s	remaining: 2m 39s
8555:	learn: 0.0014202	total: 14m 1s	remaining: 2m 22s
7773:	learn: 0.0013611	total: 14m 1s	remaining: 4m
8163:	learn: 0.0016455	total: 14m 1s	remaining: 3m 9s
8401:	learn: 0.0014949	total: 14m 1s	remaining: 2m 40s
8403:	learn: 0.0013957	total: 14m 1s	remaining: 2m 39s
8556:	learn: 0.0014202	total: 14m 1s	remaining: 2m 21s
7774:	learn: 0.0013611	total: 14m 1s	remaining: 4m
8402:	learn: 0.0014949	total: 14m 1s	remaining: 2m 39s
8404:	learn: 0.0013957	total: 14m 1s	remaining: 2m 39s
8164:	learn: 0.0016451	total: 14m 1s	remaining: 3m 9s
8557:	learn: 0.0014202	total: 14m 1s	remaining: 2m 21s
7775:	learn: 0.0013611	total: 14m 1s	remaining: 4m
8403:	learn: 0.0014949	total: 14m 1s	remaining: 2m 39s
8558:	learn: 0.0014202	total: 14m 1s	remaining: 2m 21s
8405:	learn: 0.0013957	total: 14m 1s	remaining: 2m 39s
8165:	learn: 0.0016451	total: 14m 1s	remaining: 3m 9s
7776:	learn: 0.0013611	total: 14m 1s	remaining: 4m
8559:	learn: 0.0014197	total: 14m 1s	remaining: 2m 21s
8406:	learn: 0.0013957	total: 14m 1s	remaining: 2m 39s
8404:	learn: 0.0014949	total: 14m 1s	remaining: 2m 39s
8166:	learn: 0.0016450	total: 14m 1s	remaining: 3m 8s
8560:	learn: 0.0014197	total: 14m 1s	remaining: 2m 21s
7777:	learn: 0.0013611	total: 14m 1s	remaining: 4m
8407:	learn: 0.0013952	total: 14m 1s	remaining: 2m 39s
8405:	learn: 0.0014949	total: 14m 1s	remaining: 2m 39s
8167:	learn: 0.0016450	total: 14m 2s	remaining: 3m 8s
8561:	learn: 0.0014197	total: 14m 1s	remaining: 2m 21s
8408:	learn: 0.0013952	total: 14m 2s	remaining: 2m 39s
7778:	learn: 0.0013610	total: 14m 2s	remaining: 4m
8562:	learn: 0.0014197	total: 14m 1s	remaining: 2m 21s
8406:	learn: 0.0014949	total: 14m 1s	remaining: 2m 39s
8168:	learn: 0.0016450	total: 14m 2s	remaining: 3m 8s
8409:	learn: 0.0013952	total: 14m 2s	remaining: 2m 39s
7779:	learn: 0.0013610	total: 14m 2s	remaining: 4m
8407:	learn: 0.0014949	total: 14m 1s	remaining: 2m 39s
8563:	learn: 0.0014197	total: 14m 2s	remaining: 2m 21s
8169:	learn: 0.0016446	total: 14m 2s	remaining: 3m 8s
8410:	learn: 0.0013952	total: 14m 2s	remaining: 2m 39s
8408:	learn: 0.0014949	total: 14m 2s	remaining: 2m 39s
7780:	learn: 0.0013610	total: 14m 2s	remaining: 4m
8564:	learn: 0.0014197	total: 14m 2s	remaining: 2m 21s
8170:	learn: 0.0016446	total: 14m 2s	remaining: 3m 8s
8411:	learn: 0.0013952	total: 14m 2s	remaining: 2m 39s
8409:	learn: 0.0014949	total: 14m 2s	remaining: 2m 39s
7781:	learn: 0.0013610	total: 14m 2s	remaining: 4m
8565:	learn: 0.0014196	total: 14m 2s	remaining: 2m 21s
8171:	learn: 0.0016442	total: 14m 2s	remaining: 3m 8s
8412:	learn: 0.0013952	total: 14m 2s	remaining: 2m 38s
8410:	learn: 0.0014949	total: 14m 2s	remaining: 2m 39s
7782:	learn: 0.0013610	total: 14m 2s	remaining: 3m 59s
8566:	learn: 0.0014196	total: 14m 2s	remaining: 2m 20s
8172:	learn: 0.0016442	total: 14m 2s	remaining: 3m 8s
8411:	learn: 0.0014949	total: 14m 2s	remaining: 2m 39s
7783:	learn: 0.0013610	total: 14m 2s	remaining: 3m 59s
8413:	learn: 0.0013952	total: 14m 2s	remaining: 2m 38s
8567:	learn: 0.0014196	total: 14m 2s	remaining: 2m 20s
8412:	learn: 0.0014949	total: 14m 2s	remaining: 2m 38s
7784:	learn: 0.0013610	total: 14m 2s	remaining: 3m 59s
8173:	learn: 0.0016442	total: 14m 2s	remaining: 3m 8s
8568:	learn: 0.0014196	total: 14m 2s	remaining: 2m 20s
8414:	learn: 0.0013952	total: 14m 2s	remaining: 2m 38s
8413:	learn: 0.0014949	total: 14m 2s	remaining: 2m 38s
7785:	learn: 0.0013610	total: 14m 2s	remaining: 3m 59s
8174:	learn: 0.0016442	total: 14m 2s	remaining: 3m 8s
8415:	learn: 0.0013952	total: 14m 2s	remaining: 2m 38s
8569:	learn: 0.0014196	total: 14m 2s	remaining: 2m 20s
7786:	learn: 0.0013610	total: 14m 2s	remaining: 3m 59s
8414:	learn: 0.0014949	total: 14m 2s	remaining: 2m 38s
8175:	learn: 0.0016440	total: 14m 2s	remaining: 3m 8s
8570:	learn: 0.0014196	total: 14m 2s	remaining: 2m 20s
8416:	learn: 0.0013952	total: 14m 2s	remaining: 2m 38s
8415:	learn: 0.0014949	total: 14m 2s	remaining: 2m 38s
7787:	learn: 0.0013609	total: 14m 2s	remaining: 3m 59s
8176:	learn: 0.0016440	total: 14m 3s	remaining: 3m 7s
8571:	learn: 0.0014196	total: 14m 2s	remaining: 2m 20s
8416:	learn: 0.0014949	total: 14m 2s	remaining: 2m 38s
8417:	learn: 0.0013952	total: 14m 3s	remaining: 2m 38s
7788:	learn: 0.0013608	total: 14m 3s	remaining: 3m 59s
8177:	learn: 0.0016440	total: 14m 3s	remaining: 3m 7s
8572:	learn: 0.0014196	total: 14m 2s	remaining: 2m 20s
8417:	learn: 0.0014949	total: 14m 2s	remaining: 2m 38s
7789:	learn: 0.0013608	total: 14m 3s	remaining: 3m 59s
8418:	learn: 0.0013952	total: 14m 3s	remaining: 2m 38s
8178:	learn: 0.0016440	total: 14m 3s	remaining: 3m 7s
8573:	learn: 0.0014196	total: 14m 3s	remaining: 2m 20s
8418:	learn: 0.0014949	total: 14m 2s	remaining: 2m 38s
7790:	learn: 0.0013608	total: 14m 3s	remaining: 3m 59s
8419:	learn: 0.0013949	total: 14m 3s	remaining: 2m 38s
8574:	learn: 0.0014196	total: 14m 3s	remaining: 2m 20s
8419:	learn: 0.0014949	total: 14m 3s	remaining: 2m 38s
8179:	learn: 0.0016440	total: 14m 3s	remaining: 3m 7s
7791:	learn: 0.0013608	total: 14m 3s	remaining: 3m 58s
8575:	learn: 0.0014196	total: 14m 3s	remaining: 2m 20s
8420:	learn: 0.0013949	total: 14m 3s	remaining: 2m 38s
8420:	learn: 0.0014949	total: 14m 3s	remaining: 2m 38s
8180:	learn: 0.0016440	total: 14m 3s	remaining: 3m 7s
7792:	learn: 0.0013608	total: 14m 3s	remaining: 3m 58s
8576:	learn: 0.0014196	total: 14m 3s	remaining: 2m 19s
8421:	learn: 0.0014949	total: 14m 3s	remaining: 2m 37s
8421:	learn: 0.0013949	total: 14m 3s	remaining: 2m 38s
8181:	learn: 0.0016440	total: 14m 3s	remaining: 3m 7s
8577:	learn: 0.0014196	total: 14m 3s	remaining: 2m 19s
7793:	learn: 0.0013608	total: 14m 3s	remaining: 3m 58s
8422:	learn: 0.0013949	total: 14m 3s	remaining: 2m 37s
8422:	learn: 0.0014949	total: 14m 3s	remaining: 2m 37s
8182:	learn: 0.0016440	total: 14m 3s	remaining: 3m 7s
8578:	learn: 0.0014196	total: 14m 3s	remaining: 2m 19s
8423:	learn: 0.0013949	total: 14m 3s	remaining: 2m 37s
7794:	learn: 0.0013608	total: 14m 3s	remaining: 3m 58s
8423:	learn: 0.0014949	total: 14m 3s	remaining: 2m 37s
8183:	learn: 0.0016440	total: 14m 3s	remaining: 3m 7s
7795:	learn: 0.0013608	total: 14m 3s	remaining: 3m 58s
8579:	learn: 0.0014196	total: 14m 3s	remaining: 2m 19s
8424:	learn: 0.0014949	total: 14m 3s	remaining: 2m 37s
8424:	learn: 0.0013949	total: 14m 3s	remaining: 2m 37s
8184:	learn: 0.0016434	total: 14m 3s	remaining: 3m 7s
8425:	learn: 0.0013949	total: 14m 3s	remaining: 2m 37s
7796:	learn: 0.0013606	total: 14m 3s	remaining: 3m 58s
8425:	learn: 0.0014949	total: 14m 3s	remaining: 2m 37s
8580:	learn: 0.0014196	total: 14m 3s	remaining: 2m 19s
8185:	learn: 0.0016434	total: 14m 3s	remaining: 3m 7s
8426:	learn: 0.0013949	total: 14m 3s	remaining: 2m 37s
8426:	learn: 0.0014949	total: 14m 3s	remaining: 2m 37s
7797:	learn: 0.0013606	total: 14m 4s	remaining: 3m 58s
8581:	learn: 0.0014196	total: 14m 3s	remaining: 2m 19s
8427:	learn: 0.0013949	total: 14m 4s	remaining: 2m 37s
8186:	learn: 0.0016434	total: 14m 4s	remaining: 3m 6s
8582:	learn: 0.0014196	total: 14m 3s	remaining: 2m 19s
8427:	learn: 0.0014949	total: 14m 3s	remaining: 2m 37s
8428:	learn: 0.0013949	total: 14m 4s	remaining: 2m 37s
7798:	learn: 0.0013606	total: 14m 4s	remaining: 3m 58s
8187:	learn: 0.0016434	total: 14m 4s	remaining: 3m 6s
8583:	learn: 0.0014196	total: 14m 4s	remaining: 2m 19s
8428:	learn: 0.0014949	total: 14m 3s	remaining: 2m 37s
8429:	learn: 0.0013949	total: 14m 4s	remaining: 2m 37s
7799:	learn: 0.0013606	total: 14m 4s	remaining: 3m 58s
8584:	learn: 0.0014196	total: 14m 4s	remaining: 2m 19s
8429:	learn: 0.0014949	total: 14m 4s	remaining: 2m 37s
8188:	learn: 0.0016434	total: 14m 4s	remaining: 3m 6s
8430:	learn: 0.0013949	total: 14m 4s	remaining: 2m 37s
8430:	learn: 0.0014949	total: 14m 4s	remaining: 2m 37s
7800:	learn: 0.0013605	total: 14m 4s	remaining: 3m 58s
8585:	learn: 0.0014196	total: 14m 4s	remaining: 2m 19s
8189:	learn: 0.0016434	total: 14m 4s	remaining: 3m 6s
8431:	learn: 0.0013949	total: 14m 4s	remaining: 2m 37s

8431:	learn: 0.0014949	total: 14m 4s	remaining: 2m 36s
8586:	learn: 0.0014196	total: 14m 4s	remaining: 2m 18s
8432:	learn: 0.0013949	total: 14m 4s	remaining: 2m 36s
7801:	learn: 0.0013606	total: 14m 4s	remaining: 3m 57s
8190:	learn: 0.0016434	total: 14m 4s	remaining: 3m 6s
8432:	learn: 0.0014949	total: 14m 4s	remaining: 2m 36s
8587:	learn: 0.0014196	total: 14m 4s	remaining: 2m 18s
8433:	learn: 0.0013944	total: 14m 4s	remaining: 2m 36s
7802:	learn: 0.0013606	total: 14m 4s	remaining: 3m 57s
8433:	learn: 0.0014949	total: 14m 4s	remaining: 2m 36s
8191:	learn: 0.0016434	total: 14m 4s	remaining: 3m 6s
8588:	learn: 0.0014196	total: 14m 4s	remaining: 2m 18s
8434:	learn: 0.0014945	total: 14m 4s	remaining: 2m 36s
7803:	learn: 0.0013605	total: 14m 4s	remaining: 3m 57s
8434:	learn: 0.0013944	total: 14m 4s	remaining: 2m 36s
8192:	learn: 0.0016434	total: 14m 4s	remaining: 3m 6s
8589:	learn: 0.0014196	total: 14m 4s	remaining: 2m 18s
8435:	learn: 0.0013944	total: 14m 4s	remaining: 2m 36s
8435:	learn: 0.0014945	total: 14m 4s	remaining: 2m 36s
8193:	learn: 0.0016429	total: 14m 4s	remaining: 3m 6s
7804:	learn: 0.0013605	total: 14m 4s	remaining: 3m 57s
8590:	learn: 0.0014196	total: 14m 4s	remaining: 2m 18s
8436:	learn: 0.0013944	total: 14m 4s	remaining: 2m 36s
8436:	learn: 0.0014945	total: 14m 4s	remaining: 2m 36s
8591:	learn: 0.0014196	total: 14m 4s	remaining: 2m 18s
8194:	learn: 0.0016426	total: 14m 4s	remaining: 3m 6s
7805:	learn: 0.0013605	total: 14m 4s	remaining: 3m 57s
8437:	learn: 0.0014945	total: 14m 4s	remaining: 2m 36s
8592:	learn: 0.0014196	total: 14m 4s	remaining: 2m 18s
8437:	learn: 0.0013944	total: 14m 5s	remaining: 2m 36s
8195:	learn: 0.0016426	total: 14m 5s	remaining: 3m 6s
7806:	learn: 0.0013605	total: 14m 5s	remaining: 3m 57s
8593:	learn: 0.0014196	total: 14m 4s	remaining: 2m 18s
8438:	learn: 0.0013944	total: 14m 5s	remaining: 2m 36s
8438:	learn: 0.0014945	total: 14m 4s	remaining: 2m 36s
8196:	learn: 0.0016426	total: 14m 5s	remaining: 3m 5s
7807:	learn: 0.0013605	total: 14m 5s	remaining: 3m 57s
8594:	learn: 0.0014196	total: 14m 5s	remaining: 2m 18s
8439:	learn: 0.0013944	total: 14m 5s	remaining: 2m 36s
8439:	learn: 0.0014945	total: 14m 4s	remaining: 2m 36s
7808:	learn: 0.0013605	total: 14m 5s	remaining: 3m 57s
8197:	learn: 0.0016426	total: 14m 5s	remaining: 3m 5s
8595:	learn: 0.0014196	total: 14m 5s	remaining: 2m 18s
8440:	learn: 0.0013944	total: 14m 5s	remaining: 2m 36s
8440:	learn: 0.0014945	total: 14m 5s	remaining: 2m 36s
7809:	learn: 0.0013605	total: 14m 5s	remaining: 3m 57s
8198:	learn: 0.0016426	total: 14m 5s	remaining: 3m 5s
8441:	learn: 0.0013944	total: 14m 5s	remaining: 2m 36s
8596:	learn: 0.0014196	total: 14m 5s	remaining: 2m 17s
8441:	learn: 0.0014945	total: 14m 5s	remaining: 2m 35s
7810:	learn: 0.0013605	total: 14m 5s	remaining: 3m 56s
8199:	learn: 0.0016426	total: 14m 5s	remaining: 3m 5s
8597:	learn: 0.0014196	total: 14m 5s	remaining: 2m 17s
8442:	learn: 0.0014945	total: 14m 5s	remaining: 2m 35s
8442:	learn: 0.0013944	total: 14m 5s	remaining: 2m 35s
7811:	learn: 0.0013605	total: 14m 5s	remaining: 3m 56s
8200:	learn: 0.0016426	total: 14m 5s	remaining: 3m 5s
8598:	learn: 0.0014196	total: 14m 5s	remaining: 2m 17s
8443:	learn: 0.0013944	total: 14m 5s	remaining: 2m 35s
8443:	learn: 0.0014945	total: 14m 5s	remaining: 2m 35s
8201:	learn: 0.0016424	total: 14m 5s	remaining: 3m 5s
7812:	learn: 0.0013605	total: 14m 5s	remaining: 3m 56s
8599:	learn: 0.0014196	total: 14m 5s	remaining: 2m 17s
8444:	learn: 0.0013944	total: 14m 5s	remaining: 2m 35s
8444:	learn: 0.0014945	total: 14m 5s	remaining: 2m 35s
8600:	learn: 0.0014196	total: 14m 5s	remaining: 2m 17s
7813:	learn: 0.0013605	total: 14m 5s	remaining: 3m 56s
8202:	learn: 0.0016424	total: 14m 5s	remaining: 3m 5s
8445:	learn: 0.0013944	total: 14m 5s	remaining: 2m 35s
8445:	learn: 0.0014945	total: 14m 5s	remaining: 2m 35s
8601:	learn: 0.0014196	total: 14m 5s	remaining: 2m 17s
8446:	learn: 0.0013944	total: 14m 5s	remaining: 2m 35s
8203:	learn: 0.0016424	total: 14m 5s	remaining: 3m 5s
7814:	learn: 0.0013605	total: 14m 5s	remaining: 3m 56s
8446:	learn: 0.0014945	total: 14m 5s	remaining: 2m 35s
8447:	learn: 0.0013944	total: 14m 5s	remaining: 2m 35s
8602:	learn: 0.0014196	total: 14m 5s	remaining: 2m 17s
8204:	learn: 0.0016420	total: 14m 6s	remaining: 3m 5s
8447:	learn: 0.0014945	total: 14m 5s	remaining: 2m 35s
7815:	learn: 0.0013605	total: 14m 6s	remaining: 3m 56s
8448:	learn: 0.0013944	total: 14m 6s	remaining: 2m 35s
8603:	learn: 0.0014196	total: 14m 5s	remaining: 2m 17s
8205:	learn: 0.0016420	total: 14m 6s	remaining: 3m 4s
8448:	learn: 0.0014945	total: 14m 5s	remaining: 2m 35s
7816:	learn: 0.0013605	total: 14m 6s	remaining: 3m 56s
8449:	learn: 0.0013944	total: 14m 6s	remaining: 2m 35s
8604:	learn: 0.0014196	total: 14m 6s	remaining: 2m 17s
8206:	learn: 0.0016415	total: 14m 6s	remaining: 3m 4s
8449:	learn: 0.0014945	total: 14m 5s	remaining: 2m 35s
8450:	learn: 0.0013944	total: 14m 6s	remaining: 2m 35s
7817:	learn: 0.0013604	total: 14m 6s	remaining: 3m 56s
8605:	learn: 0.0014196	total: 14m 6s	remaining: 2m 17s
8207:	learn: 0.0016415	total: 14m 6s	remaining: 3m 4s
8450:	learn: 0.0014945	total: 14m 6s	remaining: 2m 35s
8451:	learn: 0.0013944	total: 14m 6s	remaining: 2m 35s
8606:	learn: 0.0014196	total: 14m 6s	remaining: 2m 16s
7818:	learn: 0.0013604	total: 14m 6s	remaining: 3m 56s
8208:	learn: 0.0016415	total: 14m 6s	remaining: 3m 4s
8451:	learn: 0.0014945	total: 14m 6s	remaining: 2m 34s
8452:	learn: 0.0013944	total: 14m 6s	remaining: 2m 34s
8607:	learn: 0.0014196	total: 14m 6s	remaining: 2m 16s
7819:	learn: 0.0013604	total: 14m 6s	remaining: 3m 55s
8209:	learn: 0.0016415	total: 14m 6s	remaining: 3m 4s
8452:	learn: 0.0014945	total: 14m 6s	remaining: 2m 34s
8453:	learn: 0.0013944	total: 14m 6s	remaining: 2m 34s
8608:	learn: 0.0014196	total: 14m 6s	remaining: 2m 16s
7820:	learn: 0.0013604	total: 14m 6s	remaining: 3m 55s
8210:	learn: 0.0016415	total: 14m 6s	remaining: 3m 4s
8453:	learn: 0.0014945	total: 14m 6s	remaining: 2m 34s
8609:	learn: 0.0014196	total: 14m 6s	remaining: 2m 16s
8454:	learn: 0.0013944	total: 14m 6s	remaining: 2m 34s
7821:	learn: 0.0013604	total: 14m 6s	remaining: 3m 55s
8211:	learn: 0.0016415	total: 14m 6s	remaining: 3m 4s
8610:	learn: 0.0014196	total: 14m 6s	remaining: 2m 16s
8454:	learn: 0.0014945	total: 14m 6s	remaining: 2m 34s
8212:	learn: 0.0016415	total: 14m 6s	remaining: 3m 4s
8455:	learn: 0.0013944	total: 14m 6s	remaining: 2m 34s
7822:	learn: 0.0013603	total: 14m 6s	remaining: 3m 55s
8455:	learn: 0.0014945	total: 14m 6s	remaining: 2m 34s
8213:	learn: 0.0016415	total: 14m 6s	remaining: 3m 4s
8611:	learn: 0.0014196	total: 14m 6s	remaining: 2m 16s
8456:	learn: 0.0013944	total: 14m 6s	remaining: 2m 34s
7823:	learn: 0.0013603	total: 14m 6s	remaining: 3m 55s
8456:	learn: 0.0014945	total: 14m 6s	remaining: 2m 34s
8214:	learn: 0.0016410	total: 14m 6s	remaining: 3m 4s
8612:	learn: 0.0014191	total: 14m 6s	remaining: 2m 16s
8457:	learn: 0.0013944	total: 14m 6s	remaining: 2m 34s
8457:	learn: 0.0014945	total: 14m 6s	remaining: 2m 34s
7824:	learn: 0.0013603	total: 14m 7s	remaining: 3m 55s
8215:	learn: 0.0016410	total: 14m 7s	remaining: 3m 3s
8613:	learn: 0.0014191	total: 14m 6s	remaining: 2m 16s
8458:	learn: 0.0013944	total: 14m 7s	remaining: 2m 34s
7825:	learn: 0.0013603	total: 14m 7s	remaining: 3m 55s
8216:	learn: 0.0016410	total: 14m 7s	remaining: 3m 3s
8458:	learn: 0.0014945	total: 14m 6s	remaining: 2m 34s
8614:	learn: 0.0014191	total: 14m 6s	remaining: 2m 16s
8459:	learn: 0.0013944	total: 14m 7s	remaining: 2m 34s
8217:	learn: 0.0016405	total: 14m 7s	remaining: 3m 3s
8459:	learn: 0.0014945	total: 14m 6s	remaining: 2m 34s
7826:	learn: 0.0013603	total: 14m 7s	remaining: 3m 55s
8460:	learn: 0.0013940	total: 14m 7s	remaining: 2m 34s
8615:	learn: 0.0014191	total: 14m 7s	remaining: 2m 16s
8218:	learn: 0.0016405	total: 14m 7s	remaining: 3m 3s
8461:	learn: 0.0013936	total: 14m 7s	remaining: 2m 34s
8460:	learn: 0.0014945	total: 14m 7s	remaining: 2m 34s
7827:	learn: 0.0013603	total: 14m 7s	remaining: 3m 55s
8616:	learn: 0.0014191	total: 14m 7s	remaining: 2m 15s
8219:	learn: 0.0016405	total: 14m 7s	remaining: 3m 3s
8461:	learn: 0.0014945	total: 14m 7s	remaining: 2m 33s
8617:	learn: 0.0014191	total: 14m 7s	remaining: 2m 15s
8462:	learn: 0.0013936	total: 14m 7s	remaining: 2m 33s
7828:	learn: 0.0013603	total: 14m 7s	remaining: 3m 55s
8220:	learn: 0.0016405	total: 14m 7s	remaining: 3m 3s
8618:	learn: 0.0014191	total: 14m 7s	remaining: 2m 15s
8463:	learn: 0.0013936	total: 14m 7s	remaining: 2m 33s
8462:	learn: 0.0014945	total: 14m 7s	remaining: 2m 33s
7829:	learn: 0.0013603	total: 14m 7s	remaining: 3m 54s
8619:	learn: 0.0014191	total: 14m 7s	remaining: 2m 15s
8221:	learn: 0.0016405	total: 14m 7s	remaining: 3m 3s
8463:	learn: 0.0014945	total: 14m 7s	remaining: 2m 33s
8464:	learn: 0.0013936	total: 14m 7s	remaining: 2m 33s
7830:	learn: 0.0013603	total: 14m 7s	remaining: 3m 54s
8222:	learn: 0.0016405	total: 14m 7s	remaining: 3m 3s
8464:	learn: 0.0014945	total: 14m 7s	remaining: 2m 33s
8620:	learn: 0.0014191	total: 14m 7s	remaining: 2m 15s
8465:	learn: 0.0013936	total: 14m 7s	remaining: 2m 33s
7831:	learn: 0.0013603	total: 14m 7s	remaining: 3m 54s
8465:	learn: 0.0014945	total: 14m 7s	remaining: 2m 33s
8621:	learn: 0.0014191	total: 14m 7s	remaining: 2m 15s
8223:	learn: 0.0016405	total: 14m 7s	remaining: 3m 3s
8466:	learn: 0.0013936	total: 14m 7s	remaining: 2m 33s
7832:	learn: 0.0013603	total: 14m 7s	remaining: 3m 54s
8466:	learn: 0.0014945	total: 14m 7s	remaining: 2m 33s
8622:	learn: 0.0014191	total: 14m 7s	remaining: 2m 15s
8467:	learn: 0.0013936	total: 14m 7s	remaining: 2m 33s
8224:	learn: 0.0016405	total: 14m 7s	remaining: 3m 3s
7833:	learn: 0.0013603	total: 14m 7s	remaining: 3m 54s
8467:	learn: 0.0014945	total: 14m 7s	remaining: 2m 33s
8623:	learn: 0.0014191	total: 14m 7s	remaining: 2m 15s
8468:	learn: 0.0013936	total: 14m 8s	remaining: 2m 33s
8225:	learn: 0.0016400	total: 14m 8s	remaining: 3m 2s
7834:	learn: 0.0013603	total: 14m 8s	remaining: 3m 54s
8468:	learn: 0.0014945	total: 14m 7s	remaining: 2m 33s
8469:	learn: 0.0013936	total: 14m 8s	remaining: 2m 33s
8624:	learn: 0.0014191	total: 14m 8s	remaining: 2m 15s
8226:	learn: 0.0016400	total: 14m 8s	remaining: 3m 2s
8469:	learn: 0.0014945	total: 14m 7s	remaining: 2m 33s
7835:	learn: 0.0013603	total: 14m 8s	remaining: 3m 54s
8470:	learn: 0.0013933	total: 14m 8s	remaining: 2m 33s
8227:	learn: 0.0016400	total: 14m 8s	remaining: 3m 2s
8625:	learn: 0.0014191	total: 14m 8s	remaining: 2m 15s
8470:	learn: 0.0014945	total: 14m 7s	remaining: 2m 33s
7836:	learn: 0.0013603	total: 14m 8s	remaining: 3m 54s
8471:	learn: 0.0013929	total: 14m 8s	remaining: 2m 33s
8626:	learn: 0.0014191	total: 14m 8s	remaining: 2m 14s
8471:	learn: 0.0014945	total: 14m 8s	remaining: 2m 32s
8228:	learn: 0.0016400	total: 14m 8s	remaining: 3m 2s
7837:	learn: 0.0013603	total: 14m 8s	remaining: 3m 54s
8472:	learn: 0.0013929	total: 14m 8s	remaining: 2m 32s
8627:	learn: 0.0014191	total: 14m 8s	remaining: 2m 14s
8229:	learn: 0.0016400	total: 14m 8s	remaining: 3m 2s
8472:	learn: 0.0014945	total: 14m 8s	remaining: 2m 32s
8473:	learn: 0.0013929	total: 14m 8s	remaining: 2m 32s
7838:	learn: 0.0013603	total: 14m 8s	remaining: 3m 53s
8628:	learn: 0.0014191	total: 14m 8s	remaining: 2m 14s
8230:	learn: 0.0016400	total: 14m 8s	remaining: 3m 2s
8473:	learn: 0.0014945	total: 14m 8s	remaining: 2m 32s
8474:	learn: 0.0013929	total: 14m 8s	remaining: 2m 32s
7839:	learn: 0.0013603	total: 14m 8s	remaining: 3m 53s
8474:	learn: 0.0014945	total: 14m 8s	remaining: 2m 32s
8629:	learn: 0.0014191	total: 14m 8s	remaining: 2m 14s
8231:	learn: 0.0016400	total: 14m 8s	remaining: 3m 2s
8475:	learn: 0.0013929	total: 14m 8s	remaining: 2m 32s
7840:	learn: 0.0013603	total: 14m 8s	remaining: 3m 53s
8630:	learn: 0.0014191	total: 14m 8s	remaining: 2m 14s
8475:	learn: 0.0014945	total: 14m 8s	remaining: 2m 32s
8232:	learn: 0.0016400	total: 14m 8s	remaining: 3m 2s
8476:	learn: 0.0013929	total: 14m 8s	remaining: 2m 32s
8476:	learn: 0.0014945	total: 14m 8s	remaining: 2m 32s
7841:	learn: 0.0013603	total: 14m 8s	remaining: 3m 53s
8631:	learn: 0.0014191	total: 14m 8s	remaining: 2m 14s
8233:	learn: 0.0016397	total: 14m 8s	remaining: 3m 2s
8477:	learn: 0.0013929	total: 14m 8s	remaining: 2m 32s
8477:	learn: 0.0014945	total: 14m 8s	remaining: 2m 32s
8632:	learn: 0.0014191	total: 14m 8s	remaining: 2m 14s
7842:	learn: 0.0013603	total: 14m 8s	remaining: 3m 53s
8234:	learn: 0.0016397	total: 14m 9s	remaining: 3m 1s
8478:	learn: 0.0013929	total: 14m 8s	remaining: 2m 32s
8633:	learn: 0.0014191	total: 14m 8s	remaining: 2m 14s
8478:	learn: 0.0014945	total: 14m 8s	remaining: 2m 32s
7843:	learn: 0.0013603	total: 14m 9s	remaining: 3m 53s
8634:	learn: 0.0014191	total: 14m 8s	remaining: 2m 14s
8479:	learn: 0.0013929	total: 14m 9s	remaining: 2m 32s
8235:	learn: 0.0016395	total: 14m 9s	remaining: 3m 1s
7844:	learn: 0.0013603	total: 14m 9s	remaining: 3m 53s
8479:	learn: 0.0014945	total: 14m 8s	remaining: 2m 32s
8635:	learn: 0.0014191	total: 14m 9s	remaining: 2m 14s
8480:	learn: 0.0013929	total: 14m 9s	remaining: 2m 32s
8236:	learn: 0.0016389	total: 14m 9s	remaining: 3m 1s
8480:	learn: 0.0014945	total: 14m 8s	remaining: 2m 32s
8636:	learn: 0.0014191	total: 14m 9s	remaining: 2m 13s
7845:	learn: 0.0013603	total: 14m 9s	remaining: 3m 53s
8481:	learn: 0.0013929	total: 14m 9s	remaining: 2m 31s
8237:	learn: 0.0016389	total: 14m 9s	remaining: 3m 1s
8637:	learn: 0.0014191	total: 14m 9s	remaining: 2m 13s
8481:	learn: 0.0014945	total: 14m 9s	remaining: 2m 31s
8238:	learn: 0.0016389	total: 14m 9s	remaining: 3m 1s
8482:	learn: 0.0013929	total: 14m 9s	remaining: 2m 31s
7846:	learn: 0.0013603	total: 14m 9s	remaining: 3m 53s
8638:	learn: 0.0014191	total: 14m 9s	remaining: 2m 13s
8482:	learn: 0.0014945	total: 14m 9s	remaining: 2m 31s
7847:	learn: 0.0013603	total: 14m 9s	remaining: 3m 52s
8483:	learn: 0.0013929	total: 14m 9s	remaining: 2m 31s
8239:	learn: 0.0016389	total: 14m 9s	remaining: 3m 1s
8639:	learn: 0.0014191	total: 14m 9s	remaining: 2m 13s
8240:	learn: 0.0016389	total: 14m 9s	remaining: 3m 1s
7848:	learn: 0.0013603	total: 14m 9s	remaining: 3m 52s
8483:	learn: 0.0014945	total: 14m 9s	remaining: 2m 31s
8484:	learn: 0.0013925	total: 14m 9s	remaining: 2m 31s
8640:	learn: 0.0014191	total: 14m 9s	remaining: 2m 13s
8484:	learn: 0.0014945	total: 14m 9s	remaining: 2m 31s
8241:	learn: 0.0016389	total: 14m 9s	remaining: 3m 1s
8485:	learn: 0.0013925	total: 14m 9s	remaining: 2m 31s
7849:	learn: 0.0013603	total: 14m 9s	remaining: 3m 52s
8641:	learn: 0.0014187	total: 14m 9s	remaining: 2m 13s
8486:	learn: 0.0013925	total: 14m 9s	remaining: 2m 31s
8485:	learn: 0.0014945	total: 14m 9s	remaining: 2m 31s
8242:	learn: 0.0016389	total: 14m 9s	remaining: 3m 1s
8642:	learn: 0.0014187	total: 14m 9s	remaining: 2m 13s
7850:	learn: 0.0013603	total: 14m 9s	remaining: 3m 52s
8486:	learn: 0.0014945	total: 14m 9s	remaining: 2m 31s
8243:	learn: 0.0016389	total: 14m 9s	remaining: 3m 1s
8487:	learn: 0.0013925	total: 14m 9s	remaining: 2m 31s
7851:	learn: 0.0013603	total: 14m 9s	remaining: 3m 52s
8487:	learn: 0.0014945	total: 14m 9s	remaining: 2m 31s
8643:	learn: 0.0014187	total: 14m 9s	remaining: 2m 13s
8244:	learn: 0.0016389	total: 14m 10s	remaining: 3m
8488:	learn: 0.0013925	total: 14m 9s	remaining: 2m 31s
7852:	learn: 0.0013603	total: 14m 10s	remaining: 3m 52s
8488:	learn: 0.0014945	total: 14m 9s	remaining: 2m 31s
8644:	learn: 0.0014187	total: 14m 9s	remaining: 2m 13s
8245:	learn: 0.0016389	total: 14m 10s	remaining: 3m
7853:	learn: 0.0013600	total: 14m 10s	remaining: 3m 52s
8489:	learn: 0.0013925	total: 14m 10s	remaining: 2m 31s
8489:	learn: 0.0014945	total: 14m 9s	remaining: 2m 31s
8490:	learn: 0.0013925	total: 14m 10s	remaining: 2m 31s
8645:	learn: 0.0014187	total: 14m 10s	remaining: 2m 13s
8246:	learn: 0.0016389	total: 14m 10s	remaining: 3m
7854:	learn: 0.0013600	total: 14m 10s	remaining: 3m 52s
8646:	learn: 0.0014187	total: 14m 10s	remaining: 2m 13s
8490:	learn: 0.0014945	total: 14m 9s	remaining: 2m 31s
8491:	learn: 0.0013925	total: 14m 10s	remaining: 2m 30s
7855:	learn: 0.0013600	total: 14m 10s	remaining: 3m 52s
8247:	learn: 0.0016385	total: 14m 10s	remaining: 3m
8491:	learn: 0.0014945	total: 14m 10s	remaining: 2m 30s
8647:	learn: 0.0014187	total: 14m 10s	remaining: 2m 12s
8492:	learn: 0.0013925	total: 14m 10s	remaining: 2m 30s
7856:	learn: 0.0013600	total: 14m 10s	remaining: 3m 51s

8492:	learn: 0.0014944	total: 14m 10s	remaining: 2m 30s
8493:	learn: 0.0013925	total: 14m 10s	remaining: 2m 30s
8248:	learn: 0.0016385	total: 14m 10s	remaining: 3m
8648:	learn: 0.0014187	total: 14m 10s	remaining: 2m 12s
8494:	learn: 0.0013925	total: 14m 10s	remaining: 2m 30s
7857:	learn: 0.0013600	total: 14m 10s	remaining: 3m 51s
8249:	learn: 0.0016385	total: 14m 10s	remaining: 3m
8493:	learn: 0.0014944	total: 14m 10s	remaining: 2m 30s
8649:	learn: 0.0014187	total: 14m 10s	remaining: 2m 12s
8250:	learn: 0.0016385	total: 14m 10s	remaining: 3m
8650:	learn: 0.0014187	total: 14m 10s	remaining: 2m 12s
7858:	learn: 0.0013600	total: 14m 10s	remaining: 3m 51s
8495:	learn: 0.0013925	total: 14m 10s	remaining: 2m 30s
8494:	learn: 0.0014944	total: 14m 10s	remaining: 2m 30s
8496:	learn: 0.0013925	total: 14m 10s	remaining: 2m 30s
8251:	learn: 0.0016379	total: 14m 10s	remaining: 3m
8651:	learn: 0.0014187	total: 14m 10s	remaining: 2m 12s
7859:	learn: 0.0013600	total: 14m 10s	remaining: 3m 51s
8495:	learn: 0.0014944	total: 14m 10s	remaining: 2m 30s
8497:	learn: 0.0013922	total: 14m 10s	remaining: 2m 30s
8652:	learn: 0.0014187	total: 14m 10s	remaining: 2m 12s
8252:	learn: 0.0016379	total: 14m 10s	remaining: 3m
7860:	learn: 0.0013600	total: 14m 10s	remaining: 3m 51s
8496:	learn: 0.0014944	total: 14m 10s	remaining: 2m 30s
8253:	learn: 0.0016379	total: 14m 10s	remaining: 3m
8498:	learn: 0.0013919	total: 14m 10s	remaining: 2m 30s
8653:	learn: 0.0014187	total: 14m 10s	remaining: 2m 12s
8497:	learn: 0.0014944	total: 14m 10s	remaining: 2m 30s
7861:	learn: 0.0013600	total: 14m 10s	remaining: 3m 51s
8499:	learn: 0.0013919	total: 14m 11s	remaining: 2m 30s
8254:	learn: 0.0016379	total: 14m 11s	remaining: 2m 59s
8498:	learn: 0.0014944	total: 14m 10s	remaining: 2m 30s
8654:	learn: 0.0014187	total: 14m 10s	remaining: 2m 12s
7862:	learn: 0.0013600	total: 14m 11s	remaining: 3m 51s
8500:	learn: 0.0013919	total: 14m 11s	remaining: 2m 30s
8255:	learn: 0.0016379	total: 14m 11s	remaining: 2m 59s
8499:	learn: 0.0014944	total: 14m 10s	remaining: 2m 30s
8655:	learn: 0.0014187	total: 14m 11s	remaining: 2m 12s
7863:	learn: 0.0013598	total: 14m 11s	remaining: 3m 51s
8501:	learn: 0.0013919	total: 14m 11s	remaining: 2m 29s
8256:	learn: 0.0016379	total: 14m 11s	remaining: 2m 59s
8500:	learn: 0.0014944	total: 14m 10s	remaining: 2m 30s
8656:	learn: 0.0014187	total: 14m 11s	remaining: 2m 12s
7864:	learn: 0.0013598	total: 14m 11s	remaining: 3m 51s
8502:	learn: 0.0013919	total: 14m 11s	remaining: 2m 29s
8257:	learn: 0.0016375	total: 14m 11s	remaining: 2m 59s
8657:	learn: 0.0014187	total: 14m 11s	remaining: 2m 11s
8501:	learn: 0.0014944	total: 14m 11s	remaining: 2m 29s
7865:	learn: 0.0013598	total: 14m 11s	remaining: 3m 50s
8502:	learn: 0.0014944	total: 14m 11s	remaining: 2m 29s
8503:	learn: 0.0013916	total: 14m 11s	remaining: 2m 29s
7866:	learn: 0.0013598	total: 14m 11s	remaining: 3m 50s
8258:	learn: 0.0016370	total: 14m 11s	remaining: 2m 59s
8658:	learn: 0.0014187	total: 14m 11s	remaining: 2m 11s
8503:	learn: 0.0014944	total: 14m 11s	remaining: 2m 29s
8504:	learn: 0.0013913	total: 14m 11s	remaining: 2m 29s
7867:	learn: 0.0013596	total: 14m 11s	remaining: 3m 50s
8659:	learn: 0.0014187	total: 14m 11s	remaining: 2m 11s
8259:	learn: 0.0016370	total: 14m 11s	remaining: 2m 59s
8505:	learn: 0.0013913	total: 14m 11s	remaining: 2m 29s
8504:	learn: 0.0014944	total: 14m 11s	remaining: 2m 29s
8660:	learn: 0.0014187	total: 14m 11s	remaining: 2m 11s
7868:	learn: 0.0013596	total: 14m 11s	remaining: 3m 50s
8260:	learn: 0.0016370	total: 14m 11s	remaining: 2m 59s
8505:	learn: 0.0014944	total: 14m 11s	remaining: 2m 29s
8506:	learn: 0.0013912	total: 14m 11s	remaining: 2m 29s
8661:	learn: 0.0014187	total: 14m 11s	remaining: 2m 11s
7869:	learn: 0.0013596	total: 14m 11s	remaining: 3m 50s
8261:	learn: 0.0016370	total: 14m 11s	remaining: 2m 59s
8662:	learn: 0.0014187	total: 14m 11s	remaining: 2m 11s
8506:	learn: 0.0014944	total: 14m 11s	remaining: 2m 29s
8507:	learn: 0.0013912	total: 14m 11s	remaining: 2m 29s
8262:	learn: 0.0016370	total: 14m 11s	remaining: 2m 59s
8663:	learn: 0.0014187	total: 14m 11s	remaining: 2m 11s
7870:	learn: 0.0013596	total: 14m 11s	remaining: 3m 50s
8507:	learn: 0.0014944	total: 14m 11s	remaining: 2m 29s
8508:	learn: 0.0013912	total: 14m 11s	remaining: 2m 29s
8263:	learn: 0.0016370	total: 14m 12s	remaining: 2m 58s
8509:	learn: 0.0013912	total: 14m 12s	remaining: 2m 29s
8508:	learn: 0.0014944	total: 14m 11s	remaining: 2m 29s
8664:	learn: 0.0014187	total: 14m 11s	remaining: 2m 11s
7871:	learn: 0.0013596	total: 14m 12s	remaining: 3m 50s
8264:	learn: 0.0016370	total: 14m 12s	remaining: 2m 58s
8510:	learn: 0.0013908	total: 14m 12s	remaining: 2m 29s
8509:	learn: 0.0014944	total: 14m 11s	remaining: 2m 29s
8665:	learn: 0.0014187	total: 14m 12s	remaining: 2m 11s
7872:	learn: 0.0013596	total: 14m 12s	remaining: 3m 50s
8265:	learn: 0.0016370	total: 14m 12s	remaining: 2m 58s
8511:	learn: 0.0013908	total: 14m 12s	remaining: 2m 28s
8510:	learn: 0.0014944	total: 14m 11s	remaining: 2m 29s
8666:	learn: 0.0014187	total: 14m 12s	remaining: 2m 11s
8266:	learn: 0.0016370	total: 14m 12s	remaining: 2m 58s
7873:	learn: 0.0013596	total: 14m 12s	remaining: 3m 50s
8512:	learn: 0.0013905	total: 14m 12s	remaining: 2m 28s
8511:	learn: 0.0014944	total: 14m 12s	remaining: 2m 28s
8667:	learn: 0.0014187	total: 14m 12s	remaining: 2m 10s
7874:	learn: 0.0013596	total: 14m 12s	remaining: 3m 50s
8513:	learn: 0.0013905	total: 14m 12s	remaining: 2m 28s
8267:	learn: 0.0016370	total: 14m 12s	remaining: 2m 58s
8512:	learn: 0.0014944	total: 14m 12s	remaining: 2m 28s
7875:	learn: 0.0013596	total: 14m 12s	remaining: 3m 49s
8668:	learn: 0.0014187	total: 14m 12s	remaining: 2m 10s
8268:	learn: 0.0016370	total: 14m 12s	remaining: 2m 58s
8513:	learn: 0.0014944	total: 14m 12s	remaining: 2m 28s
8514:	learn: 0.0013905	total: 14m 12s	remaining: 2m 28s
7876:	learn: 0.0013596	total: 14m 12s	remaining: 3m 49s
8669:	learn: 0.0014187	total: 14m 12s	remaining: 2m 10s
8269:	learn: 0.0016368	total: 14m 12s	remaining: 2m 58s
8515:	learn: 0.0013905	total: 14m 12s	remaining: 2m 28s
8514:	learn: 0.0014944	total: 14m 12s	remaining: 2m 28s
7877:	learn: 0.0013596	total: 14m 12s	remaining: 3m 49s
8670:	learn: 0.0014187	total: 14m 12s	remaining: 2m 10s
8515:	learn: 0.0014944	total: 14m 12s	remaining: 2m 28s
8270:	learn: 0.0016368	total: 14m 12s	remaining: 2m 58s
8516:	learn: 0.0013905	total: 14m 12s	remaining: 2m 28s
7878:	learn: 0.0013596	total: 14m 12s	remaining: 3m 49s
8516:	learn: 0.0014944	total: 14m 12s	remaining: 2m 28s
8671:	learn: 0.0014187	total: 14m 12s	remaining: 2m 10s
8271:	learn: 0.0016368	total: 14m 12s	remaining: 2m 58s
8517:	learn: 0.0013905	total: 14m 12s	remaining: 2m 28s
7879:	learn: 0.0013596	total: 14m 12s	remaining: 3m 49s
8517:	learn: 0.0014944	total: 14m 12s	remaining: 2m 28s
8672:	learn: 0.0014187	total: 14m 12s	remaining: 2m 10s
8272:	learn: 0.0016368	total: 14m 12s	remaining: 2m 58s
8518:	learn: 0.0013905	total: 14m 12s	remaining: 2m 28s
8518:	learn: 0.0014944	total: 14m 12s	remaining: 2m 28s
8673:	learn: 0.0014187	total: 14m 12s	remaining: 2m 10s
7880:	learn: 0.0013596	total: 14m 12s	remaining: 3m 49s
8273:	learn: 0.0016368	total: 14m 13s	remaining: 2m 57s
8519:	learn: 0.0013905	total: 14m 12s	remaining: 2m 28s
7881:	learn: 0.0013596	total: 14m 13s	remaining: 3m 49s
8519:	learn: 0.0014944	total: 14m 12s	remaining: 2m 28s
8674:	learn: 0.0014187	total: 14m 12s	remaining: 2m 10s
8274:	learn: 0.0016368	total: 14m 13s	remaining: 2m 57s
8520:	learn: 0.0013904	total: 14m 13s	remaining: 2m 28s
7882:	learn: 0.0013596	total: 14m 13s	remaining: 3m 49s
8675:	learn: 0.0014187	total: 14m 13s	remaining: 2m 10s
8520:	learn: 0.0014943	total: 14m 12s	remaining: 2m 28s
8275:	learn: 0.0016368	total: 14m 13s	remaining: 2m 57s
8521:	learn: 0.0013904	total: 14m 13s	remaining: 2m 27s
7883:	learn: 0.0013596	total: 14m 13s	remaining: 3m 49s
8521:	learn: 0.0014944	total: 14m 12s	remaining: 2m 27s
8676:	learn: 0.0014187	total: 14m 13s	remaining: 2m 10s
8522:	learn: 0.0013904	total: 14m 13s	remaining: 2m 27s
8276:	learn: 0.0016368	total: 14m 13s	remaining: 2m 57s
8522:	learn: 0.0014944	total: 14m 13s	remaining: 2m 27s
7884:	learn: 0.0013596	total: 14m 13s	remaining: 3m 48s
8277:	learn: 0.0016368	total: 14m 13s	remaining: 2m 57s
8523:	learn: 0.0013904	total: 14m 13s	remaining: 2m 27s
8523:	learn: 0.0014944	total: 14m 13s	remaining: 2m 27s
8678:	learn: 0.0014187	total: 14m 13s	remaining: 2m 9s
7885:	learn: 0.0013596	total: 14m 13s	remaining: 3m 48s
8278:	learn: 0.0016368	total: 14m 13s	remaining: 2m 57s
8524:	learn: 0.0013904	total: 14m 13s	remaining: 2m 27s
8679:	learn: 0.0014187	total: 14m 13s	remaining: 2m 9s
8279:	learn: 0.0016368	total: 14m 13s	remaining: 2m 57s
8524:	learn: 0.0014943	total: 14m 13s	remaining: 2m 27s
7886:	learn: 0.0013596	total: 14m 13s	remaining: 3m 48s
8680:	learn: 0.0014187	total: 14m 13s	remaining: 2m 9s
8525:	learn: 0.0013904	total: 14m 13s	remaining: 2m 27s
8525:	learn: 0.0014943	total: 14m 13s	remaining: 2m 27s
7887:	learn: 0.0013596	total: 14m 13s	remaining: 3m 48s
8280:	learn: 0.0016368	total: 14m 13s	remaining: 2m 57s
8681:	learn: 0.0014187	total: 14m 13s	remaining: 2m 9s
8526:	learn: 0.0013900	total: 14m 13s	remaining: 2m 27s
8526:	learn: 0.0014943	total: 14m 13s	remaining: 2m 27s
8682:	learn: 0.0014187	total: 14m 13s	remaining: 2m 9s
8281:	learn: 0.0016368	total: 14m 13s	remaining: 2m 57s
7888:	learn: 0.0013596	total: 14m 13s	remaining: 3m 48s
8527:	learn: 0.0013897	total: 14m 13s	remaining: 2m 27s
8527:	learn: 0.0014943	total: 14m 13s	remaining: 2m 27s
8683:	learn: 0.0014187	total: 14m 13s	remaining: 2m 9s
8528:	learn: 0.0013894	total: 14m 13s	remaining: 2m 27s
8282:	learn: 0.0016368	total: 14m 13s	remaining: 2m 57s
7889:	learn: 0.0013596	total: 14m 13s	remaining: 3m 48s
8528:	learn: 0.0014944	total: 14m 13s	remaining: 2m 27s
8684:	learn: 0.0014187	total: 14m 13s	remaining: 2m 9s
8529:	learn: 0.0013894	total: 14m 14s	remaining: 2m 27s
8685:	learn: 0.0014187	total: 14m 13s	remaining: 2m 9s
7890:	learn: 0.0013595	total: 14m 14s	remaining: 3m 48s
8529:	learn: 0.0014942	total: 14m 13s	remaining: 2m 27s
8283:	learn: 0.0016368	total: 14m 14s	remaining: 2m 56s
8686:	learn: 0.0014187	total: 14m 13s	remaining: 2m 9s
8530:	learn: 0.0013890	total: 14m 14s	remaining: 2m 27s
7891:	learn: 0.0013596	total: 14m 14s	remaining: 3m 48s
8530:	learn: 0.0014942	total: 14m 13s	remaining: 2m 27s
8687:	learn: 0.0014187	total: 14m 14s	remaining: 2m 8s
8284:	learn: 0.0016368	total: 14m 14s	remaining: 2m 56s
8531:	learn: 0.0013887	total: 14m 14s	remaining: 2m 26s
8688:	learn: 0.0014187	total: 14m 14s	remaining: 2m 8s
8531:	learn: 0.0014942	total: 14m 14s	remaining: 2m 26s
7892:	learn: 0.0013595	total: 14m 14s	remaining: 3m 48s
8285:	learn: 0.0016368	total: 14m 14s	remaining: 2m 56s
8532:	learn: 0.0013887	total: 14m 14s	remaining: 2m 26s
8532:	learn: 0.0014942	total: 14m 14s	remaining: 2m 26s
8689:	learn: 0.0014186	total: 14m 14s	remaining: 2m 8s
8286:	learn: 0.0016368	total: 14m 14s	remaining: 2m 56s
7893:	learn: 0.0013595	total: 14m 14s	remaining: 3m 47s
8533:	learn: 0.0013887	total: 14m 14s	remaining: 2m 26s
8287:	learn: 0.0016362	total: 14m 14s	remaining: 2m 56s
8690:	learn: 0.0014183	total: 14m 14s	remaining: 2m 8s
8533:	learn: 0.0014942	total: 14m 14s	remaining: 2m 26s
7894:	learn: 0.0013596	total: 14m 14s	remaining: 3m 47s
8534:	learn: 0.0013884	total: 14m 14s	remaining: 2m 26s
8288:	learn: 0.0016362	total: 14m 14s	remaining: 2m 56s
8534:	learn: 0.0014942	total: 14m 14s	remaining: 2m 26s
8691:	learn: 0.0014182	total: 14m 14s	remaining: 2m 8s
8535:	learn: 0.0013884	total: 14m 14s	remaining: 2m 26s
7895:	learn: 0.0013596	total: 14m 14s	remaining: 3m 47s
8289:	learn: 0.0016362	total: 14m 14s	remaining: 2m 56s
8535:	learn: 0.0014939	total: 14m 14s	remaining: 2m 26s
8692:	learn: 0.0014183	total: 14m 14s	remaining: 2m 8s
8536:	learn: 0.0013884	total: 14m 14s	remaining: 2m 26s
8290:	learn: 0.0016362	total: 14m 14s	remaining: 2m 56s
8536:	learn: 0.0014939	total: 14m 14s	remaining: 2m 26s
7896:	learn: 0.0013595	total: 14m 14s	remaining: 3m 47s
8693:	learn: 0.0014182	total: 14m 14s	remaining: 2m 8s
8291:	learn: 0.0016357	total: 14m 14s	remaining: 2m 56s
7897:	learn: 0.0013596	total: 14m 14s	remaining: 3m 47s
8537:	learn: 0.0013884	total: 14m 14s	remaining: 2m 26s
8537:	learn: 0.0014939	total: 14m 14s	remaining: 2m 26s
8694:	learn: 0.0014182	total: 14m 14s	remaining: 2m 8s
8292:	learn: 0.0016357	total: 14m 14s	remaining: 2m 55s
8538:	learn: 0.0014939	total: 14m 14s	remaining: 2m 26s
7898:	learn: 0.0013595	total: 14m 14s	remaining: 3m 47s
8538:	learn: 0.0013884	total: 14m 14s	remaining: 2m 26s
8695:	learn: 0.0014182	total: 14m 14s	remaining: 2m 8s
8293:	learn: 0.0016357	total: 14m 15s	remaining: 2m 55s
8539:	learn: 0.0014939	total: 14m 14s	remaining: 2m 26s
8539:	learn: 0.0013884	total: 14m 15s	remaining: 2m 26s
7899:	learn: 0.0013595	total: 14m 15s	remaining: 3m 47s
8696:	learn: 0.0014182	total: 14m 14s	remaining: 2m 8s
8294:	learn: 0.0016357	total: 14m 15s	remaining: 2m 55s
8540:	learn: 0.0014939	total: 14m 14s	remaining: 2m 26s
8540:	learn: 0.0013884	total: 14m 15s	remaining: 2m 26s
7900:	learn: 0.0013596	total: 14m 15s	remaining: 3m 47s
8697:	learn: 0.0014182	total: 14m 15s	remaining: 2m 7s
8541:	learn: 0.0014939	total: 14m 14s	remaining: 2m 25s
8295:	learn: 0.0016357	total: 14m 15s	remaining: 2m 55s
8541:	learn: 0.0013884	total: 14m 15s	remaining: 2m 25s
8698:	learn: 0.0014183	total: 14m 15s	remaining: 2m 7s
7901:	learn: 0.0013596	total: 14m 15s	remaining: 3m 47s
8542:	learn: 0.0014939	total: 14m 15s	remaining: 2m 25s
8542:	learn: 0.0013884	total: 14m 15s	remaining: 2m 25s
8296:	learn: 0.0016357	total: 14m 15s	remaining: 2m 55s
8699:	learn: 0.0014183	total: 14m 15s	remaining: 2m 7s
8543:	learn: 0.0014939	total: 14m 15s	remaining: 2m 25s
8543:	learn: 0.0013884	total: 14m 15s	remaining: 2m 25s
7902:	learn: 0.0013595	total: 14m 15s	remaining: 3m 46s
8700:	learn: 0.0014182	total: 14m 15s	remaining: 2m 7s
8297:	learn: 0.0016357	total: 14m 15s	remaining: 2m 55s
7903:	learn: 0.0013595	total: 14m 15s	remaining: 3m 46s
8544:	learn: 0.0014939	total: 14m 15s	remaining: 2m 25s
8701:	learn: 0.0014182	total: 14m 15s	remaining: 2m 7s
8544:	learn: 0.0013881	total: 14m 15s	remaining: 2m 25s
8298:	learn: 0.0016357	total: 14m 15s	remaining: 2m 55s
8545:	learn: 0.0014939	total: 14m 15s	remaining: 2m 25s
7904:	learn: 0.0013593	total: 14m 15s	remaining: 3m 46s
8702:	learn: 0.0014182	total: 14m 15s	remaining: 2m 7s
8299:	learn: 0.0016357	total: 14m 15s	remaining: 2m 55s
8545:	learn: 0.0013877	total: 14m 15s	remaining: 2m 25s
8546:	learn: 0.0014939	total: 14m 15s	remaining: 2m 25s
8703:	learn: 0.0014182	total: 14m 15s	remaining: 2m 7s
7905:	learn: 0.0013593	total: 14m 15s	remaining: 3m 46s
8546:	learn: 0.0013873	total: 14m 15s	remaining: 2m 25s
8300:	learn: 0.0016357	total: 14m 15s	remaining: 2m 55s
8547:	learn: 0.0014939	total: 14m 15s	remaining: 2m 25s
8704:	learn: 0.0014178	total: 14m 15s	remaining: 2m 7s
7906:	learn: 0.0013593	total: 14m 15s	remaining: 3m 46s
8301:	learn: 0.0016352	total: 14m 15s	remaining: 2m 55s
8547:	learn: 0.0013873	total: 14m 15s	remaining: 2m 25s
8548:	learn: 0.0014938	total: 14m 15s	remaining: 2m 25s
8705:	learn: 0.0014178	total: 14m 15s	remaining: 2m 7s
7907:	learn: 0.0013593	total: 14m 15s	remaining: 3m 46s
8302:	learn: 0.0016352	total: 14m 16s	remaining: 2m 54s
8548:	learn: 0.0013873	total: 14m 15s	remaining: 2m 25s
8549:	learn: 0.0014938	total: 14m 15s	remaining: 2m 25s
8706:	learn: 0.0014178	total: 14m 15s	remaining: 2m 7s
7908:	learn: 0.0013593	total: 14m 16s	remaining: 3m 46s
8550:	learn: 0.0014938	total: 14m 15s	remaining: 2m 25s
8549:	learn: 0.0013873	total: 14m 16s	remaining: 2m 25s
8303:	learn: 0.0016352	total: 14m 16s	remaining: 2m 54s
8707:	learn: 0.0014178	total: 14m 15s	remaining: 2m 6s
8551:	learn: 0.0014938	total: 14m 15s	remaining: 2m 24s
7909:	learn: 0.0013593	total: 14m 16s	remaining: 3m 46s
8708:	learn: 0.0014178	total: 14m 16s	remaining: 2m 6s
8304:	learn: 0.0016352	total: 14m 16s	remaining: 2m 54s
8550:	learn: 0.0013873	total: 14m 16s	remaining: 2m 25s
8552:	learn: 0.0014938	total: 14m 15s	remaining: 2m 24s
7910:	learn: 0.0013593	total: 14m 16s	remaining: 3m 46s
8709:	learn: 0.0014178	total: 14m 16s	remaining: 2m 6s

7683:	learn: 0.0013618	total: 13m 52s	remaining: 4m 10s8305:	learn: 0.0016349	total: 14m 16s	remaining: 2m 54s
8551:	learn: 0.0013873	total: 14m 16s	remaining: 2m 24s
8553:	learn: 0.0014937	total: 14m 16s	remaining: 2m 24s
7911:	learn: 0.0013593	total: 14m 16s	remaining: 3m 45s
8710:	learn: 0.0014178	total: 14m 16s	remaining: 2m 6s
8306:	learn: 0.0016349	total: 14m 16s	remaining: 2m 54s
8552:	learn: 0.0013873	total: 14m 16s	remaining: 2m 24s
8554:	learn: 0.0014937	total: 14m 16s	remaining: 2m 24s
7912:	learn: 0.0013593	total: 14m 16s	remaining: 3m 45s
8711:	learn: 0.0014178	total: 14m 16s	remaining: 2m 6s
8307:	learn: 0.0016349	total: 14m 16s	remaining: 2m 54s
8553:	learn: 0.0013873	total: 14m 16s	remaining: 2m 24s
7913:	learn: 0.0013593	total: 14m 16s	remaining: 3m 45s
8555:	learn: 0.0014937	total: 14m 16s	remaining: 2m 24s
8712:	learn: 0.0014178	total: 14m 16s	remaining: 2m 6s
8308:	learn: 0.0016349	total: 14m 16s	remaining: 2m 54s
7914:	learn: 0.0013593	total: 14m 16s	remaining: 3m 45s
8554:	learn: 0.0013873	total: 14m 16s	remaining: 2m 24s
8556:	learn: 0.0014937	total: 14m 16s	remaining: 2m 24s
8713:	learn: 0.0014178	total: 14m 16s	remaining: 2m 6s
8309:	learn: 0.0016349	total: 14m 16s	remaining: 2m 54s
7915:	learn: 0.0013593	total: 14m 16s	remaining: 3m 45s
8557:	learn: 0.0014937	total: 14m 16s	remaining: 2m 24s
8555:	learn: 0.0013873	total: 14m 16s	remaining: 2m 24s
8714:	learn: 0.0014178	total: 14m 16s	remaining: 2m 6s
8310:	learn: 0.0016345	total: 14m 16s	remaining: 2m 54s
7916:	learn: 0.0013593	total: 14m 16s	remaining: 3m 45s
8556:	learn: 0.0013873	total: 14m 16s	remaining: 2m 24s
8558:	learn: 0.0014937	total: 14m 16s	remaining: 2m 24s
8715:	learn: 0.0014178	total: 14m 16s	remaining: 2m 6s
8311:	learn: 0.0016344	total: 14m 16s	remaining: 2m 54s
7917:	learn: 0.0013593	total: 14m 16s	remaining: 3m 45s
8557:	learn: 0.0013873	total: 14m 16s	remaining: 2m 24s
8716:	learn: 0.0014178	total: 14m 16s	remaining: 2m 6s
8559:	learn: 0.0014937	total: 14m 16s	remaining: 2m 24s
8312:	learn: 0.0016344	total: 14m 17s	remaining: 2m 53s
7918:	learn: 0.0013593	total: 14m 17s	remaining: 3m 45s
8717:	learn: 0.0014178	total: 14m 16s	remaining: 2m 6s
8558:	learn: 0.0013873	total: 14m 17s	remaining: 2m 24s
8560:	learn: 0.0014937	total: 14m 16s	remaining: 2m 24s
8313:	learn: 0.0016340	total: 14m 17s	remaining: 2m 53s
7919:	learn: 0.0013593	total: 14m 17s	remaining: 3m 45s
8718:	learn: 0.0014178	total: 14m 16s	remaining: 2m 5s
8561:	learn: 0.0014937	total: 14m 16s	remaining: 2m 23s
8559:	learn: 0.0013870	total: 14m 17s	remaining: 2m 24s
7920:	learn: 0.0013593	total: 14m 17s	remaining: 3m 44s
8314:	learn: 0.0016340	total: 14m 17s	remaining: 2m 53s
8719:	learn: 0.0014178	total: 14m 17s	remaining: 2m 5s
8562:	learn: 0.0014937	total: 14m 16s	remaining: 2m 23s
8560:	learn: 0.0013870	total: 14m 17s	remaining: 2m 24s
8315:	learn: 0.0016336	total: 14m 17s	remaining: 2m 53s
7921:	learn: 0.0013593	total: 14m 17s	remaining: 3m 44s
8720:	learn: 0.0014178	total: 14m 17s	remaining: 2m 5s
8563:	learn: 0.0014937	total: 14m 17s	remaining: 2m 23s
8561:	learn: 0.0013870	total: 14m 17s	remaining: 2m 23s
8316:	learn: 0.0016330	total: 14m 17s	remaining: 2m 53s
7922:	learn: 0.0013593	total: 14m 17s	remaining: 3m 44s
8721:	learn: 0.0014178	total: 14m 17s	remaining: 2m 5s
8564:	learn: 0.0014937	total: 14m 17s	remaining: 2m 23s
8562:	learn: 0.0013870	total: 14m 17s	remaining: 2m 23s
8317:	learn: 0.0016329	total: 14m 17s	remaining: 2m 53s
8722:	learn: 0.0014178	total: 14m 17s	remaining: 2m 5s
7923:	learn: 0.0013593	total: 14m 17s	remaining: 3m 44s
8565:	learn: 0.0014937	total: 14m 17s	remaining: 2m 23s
8563:	learn: 0.0013870	total: 14m 17s	remaining: 2m 23s
8723:	learn: 0.0014178	total: 14m 17s	remaining: 2m 5s
8318:	learn: 0.0016329	total: 14m 17s	remaining: 2m 53s
7924:	learn: 0.0013593	total: 14m 17s	remaining: 3m 44s
8566:	learn: 0.0014937	total: 14m 17s	remaining: 2m 23s
8564:	learn: 0.0013870	total: 14m 17s	remaining: 2m 23s
8724:	learn: 0.0014178	total: 14m 17s	remaining: 2m 5s
8319:	learn: 0.0016324	total: 14m 17s	remaining: 2m 53s
8565:	learn: 0.0013870	total: 14m 17s	remaining: 2m 23s
7925:	learn: 0.0013593	total: 14m 17s	remaining: 3m 44s
8567:	learn: 0.0014937	total: 14m 17s	remaining: 2m 23s
8725:	learn: 0.0014178	total: 14m 17s	remaining: 2m 5s
8320:	learn: 0.0016324	total: 14m 17s	remaining: 2m 53s
8568:	learn: 0.0014937	total: 14m 17s	remaining: 2m 23s
8566:	learn: 0.0013870	total: 14m 17s	remaining: 2m 23s
7926:	learn: 0.0013593	total: 14m 17s	remaining: 3m 44s
8726:	learn: 0.0014178	total: 14m 17s	remaining: 2m 5s
8321:	learn: 0.0016324	total: 14m 17s	remaining: 2m 52s
8567:	learn: 0.0013870	total: 14m 17s	remaining: 2m 23s
8569:	learn: 0.0014936	total: 14m 17s	remaining: 2m 23s
8727:	learn: 0.0014178	total: 14m 17s	remaining: 2m 5s
7927:	learn: 0.0013593	total: 14m 17s	remaining: 3m 44s
8322:	learn: 0.0016324	total: 14m 18s	remaining: 2m 52s
8568:	learn: 0.0013870	total: 14m 18s	remaining: 2m 23s
8570:	learn: 0.0014936	total: 14m 17s	remaining: 2m 23s
8728:	learn: 0.0014178	total: 14m 17s	remaining: 2m 4s
7928:	learn: 0.0013590	total: 14m 18s	remaining: 3m 44s
8569:	learn: 0.0013870	total: 14m 18s	remaining: 2m 23s
8323:	learn: 0.0016324	total: 14m 18s	remaining: 2m 52s
8571:	learn: 0.0014936	total: 14m 17s	remaining: 2m 22s
8729:	learn: 0.0014178	total: 14m 17s	remaining: 2m 4s
8572:	learn: 0.0014936	total: 14m 17s	remaining: 2m 22s
8570:	learn: 0.0013866	total: 14m 18s	remaining: 2m 23s
8730:	learn: 0.0014178	total: 14m 18s	remaining: 2m 4s
7929:	learn: 0.0013590	total: 14m 18s	remaining: 3m 44s
8324:	learn: 0.0016324	total: 14m 18s	remaining: 2m 52s
8571:	learn: 0.0013866	total: 14m 18s	remaining: 2m 22s
8731:	learn: 0.0014178	total: 14m 18s	remaining: 2m 4s
8573:	learn: 0.0014936	total: 14m 18s	remaining: 2m 22s
7930:	learn: 0.0013590	total: 14m 18s	remaining: 3m 43s
8325:	learn: 0.0016321	total: 14m 18s	remaining: 2m 52s
8732:	learn: 0.0014178	total: 14m 18s	remaining: 2m 4s
8572:	learn: 0.0013866	total: 14m 18s	remaining: 2m 22s
8574:	learn: 0.0014931	total: 14m 18s	remaining: 2m 22s
8326:	learn: 0.0016321	total: 14m 18s	remaining: 2m 52s
8573:	learn: 0.0013866	total: 14m 18s	remaining: 2m 22s
8733:	learn: 0.0014178	total: 14m 18s	remaining: 2m 4s
7931:	learn: 0.0013590	total: 14m 18s	remaining: 3m 43s
8575:	learn: 0.0014931	total: 14m 18s	remaining: 2m 22s
8327:	learn: 0.0016321	total: 14m 18s	remaining: 2m 52s
8734:	learn: 0.0014178	total: 14m 18s	remaining: 2m 4s
8328:	learn: 0.0016321	total: 14m 18s	remaining: 2m 52s
7932:	learn: 0.0013590	total: 14m 18s	remaining: 3m 43s
8574:	learn: 0.0013866	total: 14m 18s	remaining: 2m 22s
8576:	learn: 0.0014931	total: 14m 18s	remaining: 2m 22s
8735:	learn: 0.0014178	total: 14m 18s	remaining: 2m 4s
8329:	learn: 0.0016321	total: 14m 18s	remaining: 2m 52s
8575:	learn: 0.0013866	total: 14m 18s	remaining: 2m 22s
7933:	learn: 0.0013590	total: 14m 18s	remaining: 3m 43s
8577:	learn: 0.0014931	total: 14m 18s	remaining: 2m 22s
8736:	learn: 0.0014173	total: 14m 18s	remaining: 2m 4s
8330:	learn: 0.0016321	total: 14m 18s	remaining: 2m 52s
8576:	learn: 0.0013866	total: 14m 18s	remaining: 2m 22s
8578:	learn: 0.0014931	total: 14m 18s	remaining: 2m 22s
7934:	learn: 0.0013590	total: 14m 18s	remaining: 3m 43s
8737:	learn: 0.0014168	total: 14m 18s	remaining: 2m 4s
8577:	learn: 0.0013866	total: 14m 18s	remaining: 2m 22s
8331:	learn: 0.0016321	total: 14m 18s	remaining: 2m 51s
7935:	learn: 0.0013590	total: 14m 18s	remaining: 3m 43s
8579:	learn: 0.0014931	total: 14m 18s	remaining: 2m 22s
8738:	learn: 0.0014168	total: 14m 18s	remaining: 2m 3s
8578:	learn: 0.0013866	total: 14m 18s	remaining: 2m 22s
7936:	learn: 0.0013590	total: 14m 19s	remaining: 3m 43s
8332:	learn: 0.0016321	total: 14m 19s	remaining: 2m 51s
8739:	learn: 0.0014168	total: 14m 18s	remaining: 2m 3s
8580:	learn: 0.0014931	total: 14m 18s	remaining: 2m 22s
8579:	learn: 0.0013866	total: 14m 19s	remaining: 2m 22s
7937:	learn: 0.0013590	total: 14m 19s	remaining: 3m 43s
8740:	learn: 0.0014168	total: 14m 18s	remaining: 2m 3s
8580:	learn: 0.0013866	total: 14m 19s	remaining: 2m 22s
8333:	learn: 0.0016321	total: 14m 19s	remaining: 2m 51s
8581:	learn: 0.0014931	total: 14m 18s	remaining: 2m 21s

8741:	learn: 0.0014167	total: 14m 19s	remaining: 2m 3s
8581:	learn: 0.0013866	total: 14m 19s	remaining: 2m 21s
8334:	learn: 0.0016320	total: 14m 19s	remaining: 2m 51s
8582:	learn: 0.0014931	total: 14m 19s	remaining: 2m 21s
8742:	learn: 0.0014166	total: 14m 19s	remaining: 2m 3s
7939:	learn: 0.0013588	total: 14m 19s	remaining: 3m 42s
8582:	learn: 0.0013866	total: 14m 19s	remaining: 2m 21s
8583:	learn: 0.0014931	total: 14m 19s	remaining: 2m 21s
8335:	learn: 0.0016317	total: 14m 19s	remaining: 2m 51s
8743:	learn: 0.0014166	total: 14m 19s	remaining: 2m 3s
8583:	learn: 0.0013866	total: 14m 19s	remaining: 2m 21s
7940:	learn: 0.0013588	total: 14m 19s	remaining: 3m 42s
8584:	learn: 0.0014931	total: 14m 19s	remaining: 2m 21s
8744:	learn: 0.0014163	total: 14m 19s	remaining: 2m 3s
8336:	learn: 0.0016317	total: 14m 19s	remaining: 2m 51s
8584:	learn: 0.0013866	total: 14m 19s	remaining: 2m 21s
7941:	learn: 0.0013588	total: 14m 19s	remaining: 3m 42s
8585:	learn: 0.0014931	total: 14m 19s	remaining: 2m 21s
8585:	learn: 0.0013866	total: 14m 19s	remaining: 2m 21s
8745:	learn: 0.0014163	total: 14m 19s	remaining: 2m 3s
8586:	learn: 0.0014931	total: 14m 19s	remaining: 2m 21s
8337:	learn: 0.0016317	total: 14m 19s	remaining: 2m 51s
7942:	learn: 0.0013588	total: 14m 19s	remaining: 3m 42s
8586:	learn: 0.0013866	total: 14m 19s	remaining: 2m 21s
8587:	learn: 0.0014931	total: 14m 19s	remaining: 2m 21s
8746:	learn: 0.0014163	total: 14m 19s	remaining: 2m 3s
8338:	learn: 0.0016317	total: 14m 19s	remaining: 2m 51s
8587:	learn: 0.0013866	total: 14m 19s	remaining: 2m 21s
8588:	learn: 0.0014931	total: 14m 19s	remaining: 2m 21s
7943:	learn: 0.0013588	total: 14m 19s	remaining: 3m 42s
8747:	learn: 0.0014163	total: 14m 19s	remaining: 2m 3s
8339:	learn: 0.0016317	total: 14m 19s	remaining: 2m 51s
8589:	learn: 0.0014931	total: 14m 19s	remaining: 2m 21s
8588:	learn: 0.0013866	total: 14m 19s	remaining: 2m 21s
7944:	learn: 0.0013586	total: 14m 19s	remaining: 3m 42s
8748:	learn: 0.0014163	total: 14m 19s	remaining: 2m 2s
8340:	learn: 0.0016317	total: 14m 19s	remaining: 2m 51s
8590:	learn: 0.0014931	total: 14m 19s	remaining: 2m 21s
8341:	learn: 0.0016317	total: 14m 20s	remaining: 2m 50s
8589:	learn: 0.0013866	total: 14m 20s	remaining: 2m 21s
8749:	learn: 0.0014162	total: 14m 19s	remaining: 2m 2s
7945:	learn: 0.0013586	total: 14m 20s	remaining: 3m 42s
8342:	learn: 0.0016317	total: 14m 20s	remaining: 2m 50s
8591:	learn: 0.0014931	total: 14m 19s	remaining: 2m 20s
8590:	learn: 0.0013866	total: 14m 20s	remaining: 2m 21s
8750:	learn: 0.0014162	total: 14m 19s	remaining: 2m 2s
7946:	learn: 0.0013586	total: 14m 20s	remaining: 3m 42s
8343:	learn: 0.0016317	total: 14m 20s	remaining: 2m 50s
8592:	learn: 0.0014931	total: 14m 19s	remaining: 2m 20s
8591:	learn: 0.0013866	total: 14m 20s	remaining: 2m 20s
8751:	learn: 0.0014162	total: 14m 20s	remaining: 2m 2s
7947:	learn: 0.0013586	total: 14m 20s	remaining: 3m 42s
8344:	learn: 0.0016317	total: 14m 20s	remaining: 2m 50s
8593:	learn: 0.0014931	total: 14m 20s	remaining: 2m 20s
8592:	learn: 0.0013866	total: 14m 20s	remaining: 2m 20s
7948:	learn: 0.0013586	total: 14m 20s	remaining: 3m 41s
8752:	learn: 0.0014162	total: 14m 20s	remaining: 2m 2s
8594:	learn: 0.0014931	total: 14m 20s	remaining: 2m 20s
8345:	learn: 0.0016317	total: 14m 20s	remaining: 2m 50s
8593:	learn: 0.0013866	total: 14m 20s	remaining: 2m 20s
7949:	learn: 0.0013586	total: 14m 20s	remaining: 3m 41s
8753:	learn: 0.0014162	total: 14m 20s	remaining: 2m 2s
8595:	learn: 0.0014931	total: 14m 20s	remaining: 2m 20s
8346:	learn: 0.0016317	total: 14m 20s	remaining: 2m 50s
8594:	learn: 0.0013863	total: 14m 20s	remaining: 2m 20s
7950:	learn: 0.0013586	total: 14m 20s	remaining: 3m 41s
8596:	learn: 0.0014931	total: 14m 20s	remaining: 2m 20s
8754:	learn: 0.0014162	total: 14m 20s	remaining: 2m 2s
8347:	learn: 0.0016317	total: 14m 20s	remaining: 2m 50s
8595:	learn: 0.0013863	total: 14m 20s	remaining: 2m 20s
7951:	learn: 0.0013586	total: 14m 20s	remaining: 3m 41s
8755:	learn: 0.0014162	total: 14m 20s	remaining: 2m 2s
8597:	learn: 0.0014931	total: 14m 20s	remaining: 2m 20s
8596:	learn: 0.0013863	total: 14m 20s	remaining: 2m 20s
8348:	learn: 0.0016317	total: 14m 20s	remaining: 2m 50s
8756:	learn: 0.0014162	total: 14m 20s	remaining: 2m 2s
8598:	learn: 0.0014931	total: 14m 20s	remaining: 2m 20s
7952:	learn: 0.0013586	total: 14m 20s	remaining: 3m 41s
8597:	learn: 0.0013863	total: 14m 20s	remaining: 2m 20s
8349:	learn: 0.0016317	total: 14m 20s	remaining: 2m 50s
8757:	learn: 0.0014162	total: 14m 20s	remaining: 2m 2s
8598:	learn: 0.0013863	total: 14m 20s	remaining: 2m 20s
7953:	learn: 0.0013586	total: 14m 20s	remaining: 3m 41s
8350:	learn: 0.0016317	total: 14m 20s	remaining: 2m 50s
8599:	learn: 0.0014931	total: 14m 20s	remaining: 2m 20s
8758:	learn: 0.0014162	total: 14m 20s	remaining: 2m 1s
8351:	learn: 0.0016317	total: 14m 21s	remaining: 2m 49s
8599:	learn: 0.0013863	total: 14m 20s	remaining: 2m 20s
7954:	learn: 0.0013586	total: 14m 21s	remaining: 3m 41s
8600:	learn: 0.0014931	total: 14m 20s	remaining: 2m 20s
8759:	learn: 0.0014160	total: 14m 20s	remaining: 2m 1s
8352:	learn: 0.0016317	total: 14m 21s	remaining: 2m 49s
8600:	learn: 0.0013863	total: 14m 21s	remaining: 2m 20s
8601:	learn: 0.0014931	total: 14m 20s	remaining: 2m 19s
7955:	learn: 0.0013586	total: 14m 21s	remaining: 3m 41s
8760:	learn: 0.0014160	total: 14m 20s	remaining: 2m 1s
8353:	learn: 0.0016317	total: 14m 21s	remaining: 2m 49s
8602:	learn: 0.0014931	total: 14m 20s	remaining: 2m 19s
8601:	learn: 0.0013863	total: 14m 21s	remaining: 2m 19s
7956:	learn: 0.0013586	total: 14m 21s	remaining: 3m 41s
8761:	learn: 0.0014157	total: 14m 21s	remaining: 2m 1s
8354:	learn: 0.0016317	total: 14m 21s	remaining: 2m 49s
8603:	learn: 0.0014931	total: 14m 21s	remaining: 2m 19s
7957:	learn: 0.0013586	total: 14m 21s	remaining: 3m 41s
8602:	learn: 0.0013860	total: 14m 21s	remaining: 2m 19s
8762:	learn: 0.0014156	total: 14m 21s	remaining: 2m 1s
8604:	learn: 0.0014931	total: 14m 21s	remaining: 2m 19s
8355:	learn: 0.0016317	total: 14m 21s	remaining: 2m 49s
7958:	learn: 0.0013586	total: 14m 21s	remaining: 3m 40s
8763:	learn: 0.0014156	total: 14m 21s	remaining: 2m 1s
8603:	learn: 0.0013860	total: 14m 21s	remaining: 2m 19s
8605:	learn: 0.0014931	total: 14m 21s	remaining: 2m 19s
8356:	learn: 0.0016317	total: 14m 21s	remaining: 2m 49s
7959:	learn: 0.0013586	total: 14m 21s	remaining: 3m 40s
8764:	learn: 0.0014156	total: 14m 21s	remaining: 2m 1s
7960:	learn: 0.0013586	total: 14m 21s	remaining: 3m 40s
8604:	learn: 0.0013860	total: 14m 21s	remaining: 2m 19s
8357:	learn: 0.0016317	total: 14m 21s	remaining: 2m 49s
8606:	learn: 0.0014931	total: 14m 21s	remaining: 2m 19s
8765:	learn: 0.0014156	total: 14m 21s	remaining: 2m 1s
7961:	learn: 0.0013586	total: 14m 21s	remaining: 3m 40s
8605:	learn: 0.0013860	total: 14m 21s	remaining: 2m 19s
8358:	learn: 0.0016317	total: 14m 21s	remaining: 2m 49s
8607:	learn: 0.0014931	total: 14m 21s	remaining: 2m 19s
8766:	learn: 0.0014156	total: 14m 21s	remaining: 2m 1s
8606:	learn: 0.0013855	total: 14m 21s	remaining: 2m 19s
8359:	learn: 0.0016317	total: 14m 21s	remaining: 2m 49s
7962:	learn: 0.0013586	total: 14m 21s	remaining: 3m 40s
8608:	learn: 0.0014931	total: 14m 21s	remaining: 2m 19s
8767:	learn: 0.0014157	total: 14m 21s	remaining: 2m 1s
8607:	learn: 0.0013854	total: 14m 21s	remaining: 2m 19s
8609:	learn: 0.0014931	total: 14m 21s	remaining: 2m 19s
8360:	learn: 0.0016317	total: 14m 21s	remaining: 2m 48s
7963:	learn: 0.0013586	total: 14m 21s	remaining: 3m 40s
8768:	learn: 0.0014156	total: 14m 21s	remaining: 2m
8608:	learn: 0.0013854	total: 14m 21s	remaining: 2m 19s
8610:	learn: 0.0014931	total: 14m 21s	remaining: 2m 19s
8361:	learn: 0.0016317	total: 14m 22s	remaining: 2m 48s
7964:	learn: 0.0013586	total: 14m 22s	remaining: 3m 40s
8769:	learn: 0.0014156	total: 14m 21s	remaining: 2m
8611:	learn: 0.0014931	total: 14m 21s	remaining: 2m 18s
8609:	learn: 0.0013850	total: 14m 22s	remaining: 2m 19s
8362:	learn: 0.0016317	total: 14m 22s	remaining: 2m 48s
7965:	learn: 0.0013586	total: 14m 22s	remaining: 3m 40s
8770:	learn: 0.0014156	total: 14m 21s	remaining: 2m
 2m 6s
7683:	learn: 0.0013618	total: 13m 52s	remaining: 8363:	learn: 0.0016313	total: 14m 22s	remaining: 2m 48s
8612:	learn: 0.0014931	total: 14m 21s	remaining: 2m 18s
8610:	learn: 0.0013850	total: 14m 22s	remaining: 2m 19s
7966:	learn: 0.0013586	total: 14m 22s	remaining: 3m 40s
8771:	learn: 0.0014156	total: 14m 22s	remaining: 2m
8613:	learn: 0.0014931	total: 14m 22s	remaining: 2m 18s
8611:	learn: 0.0013850	total: 14m 22s	remaining: 2m 18s
8772:	learn: 0.0014156	total: 14m 22s	remaining: 2m
8364:	learn: 0.0016313	total: 14m 22s	remaining: 2m 48s
7967:	learn: 0.0013586	total: 14m 22s	remaining: 3m 39s
8614:	learn: 0.0014931	total: 14m 22s	remaining: 2m 18s
8612:	learn: 0.0013850	total: 14m 22s	remaining: 2m 18s
8773:	learn: 0.0014156	total: 14m 22s	remaining: 2m
8365:	learn: 0.0016313	total: 14m 22s	remaining: 2m 48s
7968:	learn: 0.0013586	total: 14m 22s	remaining: 3m 39s
8615:	learn: 0.0014931	total: 14m 22s	remaining: 2m 18s
8613:	learn: 0.0013850	total: 14m 22s	remaining: 2m 18s
8774:	learn: 0.0014156	total: 14m 22s	remaining: 2m
8366:	learn: 0.0016307	total: 14m 22s	remaining: 2m 48s
8616:	learn: 0.0014931	total: 14m 22s	remaining: 2m 18s
8614:	learn: 0.0013850	total: 14m 22s	remaining: 2m 18s
7969:	learn: 0.0013586	total: 14m 22s	remaining: 3m 39s
8775:	learn: 0.0014156	total: 14m 22s	remaining: 2m
7970:	learn: 0.0013586	total: 14m 22s	remaining: 3m 39s
8367:	learn: 0.0016307	total: 14m 22s	remaining: 2m 48s
8615:	learn: 0.0013850	total: 14m 22s	remaining: 2m 18s
8617:	learn: 0.0014931	total: 14m 22s	remaining: 2m 18s
8776:	learn: 0.0014156	total: 14m 22s	remaining: 2m
7971:	learn: 0.0013586	total: 14m 22s	remaining: 3m 39s
8616:	learn: 0.0013850	total: 14m 22s	remaining: 2m 18s
8368:	learn: 0.0016306	total: 14m 22s	remaining: 2m 48s
8777:	learn: 0.0014156	total: 14m 22s	remaining: 2m
8618:	learn: 0.0014931	total: 14m 22s	remaining: 2m 18s
7972:	learn: 0.0013586	total: 14m 22s	remaining: 3m 39s
8617:	learn: 0.0013850	total: 14m 22s	remaining: 2m 18s
8778:	learn: 0.0014156	total: 14m 22s	remaining: 1m 59s
7973:	learn: 0.0013586	total: 14m 22s	remaining: 3m 39s
8369:	learn: 0.0016307	total: 14m 22s	remaining: 2m 48s
8619:	learn: 0.0014931	total: 14m 22s	remaining: 2m 18s
8618:	learn: 0.0013850	total: 14m 22s	remaining: 2m 18s
8779:	learn: 0.0014156	total: 14m 22s	remaining: 1m 59s
7974:	learn: 0.0013586	total: 14m 22s	remaining: 3m 39s
8370:	learn: 0.0016307	total: 14m 23s	remaining: 2m 47s
8620:	learn: 0.0014931	total: 14m 22s	remaining: 2m 18s
8619:	learn: 0.0013850	total: 14m 23s	remaining: 2m 18s
8780:	learn: 0.0014156	total: 14m 22s	remaining: 1m 59s
8371:	learn: 0.0016307	total: 14m 23s	remaining: 2m 47s
8621:	learn: 0.0014931	total: 14m 22s	remaining: 2m 17s
7975:	learn: 0.0013586	total: 14m 23s	remaining: 3m 39s
8620:	learn: 0.0013847	total: 14m 23s	remaining: 2m 18s
8372:	learn: 0.0016307	total: 14m 23s	remaining: 2m 47s
8781:	learn: 0.0014156	total: 14m 22s	remaining: 1m 59s
8782:	learn: 0.0014156	total: 14m 23s	remaining: 1m 59s
8373:	learn: 0.0016302	total: 14m 23s	remaining: 2m 47s
8622:	learn: 0.0014931	total: 14m 22s	remaining: 2m 17s
8621:	learn: 0.0013847	total: 14m 23s	remaining: 2m 17s
7976:	learn: 0.0013586	total: 14m 23s	remaining: 3m 38s
8374:	learn: 0.0016299	total: 14m 23s	remaining: 2m 47s
8783:	learn: 0.0014156	total: 14m 23s	remaining: 1m 59s
7977:	learn: 0.0013586	total: 14m 23s	remaining: 3m 38s
8622:	learn: 0.0013843	total: 14m 23s	remaining: 2m 17s
8623:	learn: 0.0014931	total: 14m 23s	remaining: 2m 17s
8784:	learn: 0.0014156	total: 14m 23s	remaining: 1m 59s
7978:	learn: 0.0013586	total: 14m 23s	remaining: 3m 38s
8375:	learn: 0.0016299	total: 14m 23s	remaining: 2m 47s
8623:	learn: 0.0013843	total: 14m 23s	remaining: 2m 17s
8624:	learn: 0.0014931	total: 14m 23s	remaining: 2m 17s
8785:	learn: 0.0014156	total: 14m 23s	remaining: 1m 59s
7979:	learn: 0.0013586	total: 14m 23s	remaining: 3m 38s
8376:	learn: 0.0016299	total: 14m 23s	remaining: 2m 47s
8625:	learn: 0.0014931	total: 14m 23s	remaining: 2m 17s
8624:	learn: 0.0013843	total: 14m 23s	remaining: 2m 17s
8786:	learn: 0.0014156	total: 14m 23s	remaining: 1m 59s
8377:	learn: 0.0016299	total: 14m 23s	remaining: 2m 47s
7980:	learn: 0.0013586	total: 14m 23s	remaining: 3m 38s
8626:	learn: 0.0014931	total: 14m 23s	remaining: 2m 17s
8625:	learn: 0.0013843	total: 14m 23s	remaining: 2m 17s
8378:	learn: 0.0016299	total: 14m 23s	remaining: 2m 47s
7981:	learn: 0.0013586	total: 14m 23s	remaining: 3m 38s
8787:	learn: 0.0014156	total: 14m 23s	remaining: 1m 59s
8627:	learn: 0.0014931	total: 14m 23s	remaining: 2m 17s
8379:	learn: 0.0016299	total: 14m 23s	remaining: 2m 46s
8626:	learn: 0.0013843	total: 14m 23s	remaining: 2m 17s
7982:	learn: 0.0013586	total: 14m 23s	remaining: 3m 38s
8788:	learn: 0.0014153	total: 14m 23s	remaining: 1m 59s
8628:	learn: 0.0014931	total: 14m 23s	remaining: 2m 17s
8380:	learn: 0.0016299	total: 14m 23s	remaining: 2m 46s
7983:	learn: 0.0013585	total: 14m 23s	remaining: 3m 38s
8627:	learn: 0.0013843	total: 14m 23s	remaining: 2m 17s
8789:	learn: 0.0014153	total: 14m 23s	remaining: 1m 58s
8381:	learn: 0.0016295	total: 14m 24s	remaining: 2m 46s
8629:	learn: 0.0014931	total: 14m 23s	remaining: 2m 17s
8628:	learn: 0.0013842	total: 14m 23s	remaining: 2m 17s
7984:	learn: 0.0013586	total: 14m 24s	remaining: 3m 38s
8790:	learn: 0.0014152	total: 14m 23s	remaining: 1m 58s
8630:	learn: 0.0014931	total: 14m 23s	remaining: 2m 17s
8382:	learn: 0.0016295	total: 14m 24s	remaining: 2m 46s
8629:	learn: 0.0013842	total: 14m 24s	remaining: 2m 17s
7985:	learn: 0.0013586	total: 14m 24s	remaining: 3m 37s
8631:	learn: 0.0014931	total: 14m 23s	remaining: 2m 16s
8791:	learn: 0.0014152	total: 14m 23s	remaining: 1m 58s
8383:	learn: 0.0016295	total: 14m 24s	remaining: 2m 46s
8630:	learn: 0.0013842	total: 14m 24s	remaining: 2m 17s
8632:	learn: 0.0014931	total: 14m 23s	remaining: 2m 16s
7986:	learn: 0.0013586	total: 14m 24s	remaining: 3m 37s
8792:	learn: 0.0014152	total: 14m 24s	remaining: 1m 58s
8384:	learn: 0.0016295	total: 14m 24s	remaining: 2m 46s
8631:	learn: 0.0013838	total: 14m 24s	remaining: 2m 16s
8633:	learn: 0.0014931	total: 14m 24s	remaining: 2m 16s
7987:	learn: 0.0013585	total: 14m 24s	remaining: 3m 37s
8793:	learn: 0.0014152	total: 14m 24s	remaining: 1m 58s
8385:	learn: 0.0016295	total: 14m 24s	remaining: 2m 46s
8632:	learn: 0.0013834	total: 14m 24s	remaining: 2m 16s
7988:	learn: 0.0013586	total: 14m 24s	remaining: 3m 37s
8634:	learn: 0.0014931	total: 14m 24s	remaining: 2m 16s
8386:	learn: 0.0016295	total: 14m 24s	remaining: 2m 46s
8794:	learn: 0.0014148	total: 14m 24s	remaining: 1m 58s
8633:	learn: 0.0013834	total: 14m 24s	remaining: 2m 16s
7989:	learn: 0.0013585	total: 14m 24s	remaining: 3m 37s
8635:	learn: 0.0014931	total: 14m 24s	remaining: 2m 16s
8387:	learn: 0.0016295	total: 14m 24s	remaining: 2m 46s
8634:	learn: 0.0013834	total: 14m 24s	remaining: 2m 16s
8795:	learn: 0.0014144	total: 14m 24s	remaining: 1m 58s
8636:	learn: 0.0014931	total: 14m 24s	remaining: 2m 16s
7990:	learn: 0.0013585	total: 14m 24s	remaining: 3m 37s
8635:	learn: 0.0013831	total: 14m 24s	remaining: 2m 16s
8637:	learn: 0.0014931	total: 14m 24s	remaining: 2m 16s
8796:	learn: 0.0014144	total: 14m 24s	remaining: 1m 58s
8388:	learn: 0.0016291	total: 14m 24s	remaining: 2m 46s
7991:	learn: 0.0013586	total: 14m 24s	remaining: 3m 37s
8636:	learn: 0.0013831	total: 14m 24s	remaining: 2m 16s
8638:	learn: 0.0014931	total: 14m 24s	remaining: 2m 16s
8797:	learn: 0.0014144	total: 14m 24s	remaining: 1m 58s
8389:	learn: 0.0016291	total: 14m 24s	remaining: 2m 45s
7992:	learn: 0.0013585	total: 14m 24s	remaining: 3m 37s
8637:	learn: 0.0013831	total: 14m 24s	remaining: 2m 16s
8639:	learn: 0.0014931	total: 14m 24s	remaining: 2m 16s
8798:	learn: 0.0014144	total: 14m 24s	remaining: 1m 58s
8390:	learn: 0.0016291	total: 14m 24s	remaining: 2m 45s
8638:	learn: 0.0013831	total: 14m 24s	remaining: 2m 16s
7993:	learn: 0.0013585	total: 14m 24s	remaining: 3m 37s
8640:	learn: 0.0014931	total: 14m 24s	remaining: 2m 15s
8799:	learn: 0.0014144	total: 14m 24s	remaining: 1m 57s
8391:	learn: 0.0016291	total: 14m 25s	remaining: 2m 45s
8639:	learn: 0.0013831	total: 14m 25s	remaining: 2m 16s
8641:	learn: 0.0014931	total: 14m 24s	remaining: 2m 15s

7994:	learn: 0.0013585	total: 14m 25s	remaining: 3m 36s
8392:	learn: 0.0016287	total: 14m 25s	remaining: 2m 45s
8800:	learn: 0.0014144	total: 14m 24s	remaining: 1m 57s
8640:	learn: 0.0013831	total: 14m 25s	remaining: 2m 16s
8642:	learn: 0.0014931	total: 14m 24s	remaining: 2m 15s
7995:	learn: 0.0013586	total: 14m 25s	remaining: 3m 36s
8393:	learn: 0.0016287	total: 14m 25s	remaining: 2m 45s
8641:	learn: 0.0013831	total: 14m 25s	remaining: 2m 15s
8801:	learn: 0.0014144	total: 14m 25s	remaining: 1m 57s
8643:	learn: 0.0014931	total: 14m 25s	remaining: 2m 15s
7996:	learn: 0.0013585	total: 14m 25s	remaining: 3m 36s
8802:	learn: 0.0014144	total: 14m 25s	remaining: 1m 57s
8394:	learn: 0.0016283	total: 14m 25s	remaining: 2m 45s
8642:	learn: 0.0013831	total: 14m 25s	remaining: 2m 15s
8644:	learn: 0.0014931	total: 14m 25s	remaining: 2m 15s
7997:	learn: 0.0013585	total: 14m 25s	remaining: 3m 36s
8803:	learn: 0.0014144	total: 14m 25s	remaining: 1m 57s
8395:	learn: 0.0016279	total: 14m 25s	remaining: 2m 45s
8643:	learn: 0.0013831	total: 14m 25s	remaining: 2m 15s
8645:	learn: 0.0014931	total: 14m 25s	remaining: 2m 15s
7998:	learn: 0.0013585	total: 14m 25s	remaining: 3m 36s
8804:	learn: 0.0014143	total: 14m 25s	remaining: 1m 57s
8396:	learn: 0.0016279	total: 14m 25s	remaining: 2m 45s
8644:	learn: 0.0013831	total: 14m 25s	remaining: 2m 15s
8646:	learn: 0.0014931	total: 14m 25s	remaining: 2m 15s
8397:	learn: 0.0016279	total: 14m 25s	remaining: 2m 45s
7999:	learn: 0.0013585	total: 14m 25s	remaining: 3m 36s
8805:	learn: 0.0014143	total: 14m 25s	remaining: 1m 57s
8647:	learn: 0.0014931	total: 14m 25s	remaining: 2m 15s
8645:	learn: 0.0013826	total: 14m 25s	remaining: 2m 15s
8398:	learn: 0.0016279	total: 14m 25s	remaining: 2m 45s
8000:	learn: 0.0013585	total: 14m 25s	remaining: 3m 36s
8806:	learn: 0.0014140	total: 14m 25s	remaining: 1m 57s
8646:	learn: 0.0013822	total: 14m 25s	remaining: 2m 15s
8648:	learn: 0.0014931	total: 14m 25s	remaining: 2m 15s
8399:	learn: 0.0016279	total: 14m 25s	remaining: 2m 44s
8807:	learn: 0.0014136	total: 14m 25s	remaining: 1m 57s
8001:	learn: 0.0013585	total: 14m 25s	remaining: 3m 36s
8649:	learn: 0.0014931	total: 14m 25s	remaining: 2m 15s
8647:	learn: 0.0013819	total: 14m 25s	remaining: 2m 15s
8400:	learn: 0.0016276	total: 14m 25s	remaining: 2m 44s
8002:	learn: 0.0013585	total: 14m 25s	remaining: 3m 36s
8650:	learn: 0.0014931	total: 14m 25s	remaining: 2m 14s
8808:	learn: 0.0014136	total: 14m 25s	remaining: 1m 57s
8648:	learn: 0.0013819	total: 14m 25s	remaining: 2m 15s
8401:	learn: 0.0016271	total: 14m 26s	remaining: 2m 44s
8651:	learn: 0.0014931	total: 14m 25s	remaining: 2m 14s
8003:	learn: 0.0013585	total: 14m 26s	remaining: 3m 35s
8809:	learn: 0.0014136	total: 14m 25s	remaining: 1m 56s
8649:	learn: 0.0013819	total: 14m 26s	remaining: 2m 15s
8652:	learn: 0.0014931	total: 14m 25s	remaining: 2m 14s
8402:	learn: 0.0016270	total: 14m 26s	remaining: 2m 44s
8004:	learn: 0.0013585	total: 14m 26s	remaining: 3m 35s
8650:	learn: 0.0013819	total: 14m 26s	remaining: 2m 15s
8810:	learn: 0.0014136	total: 14m 25s	remaining: 1m 56s
8653:	learn: 0.0014931	total: 14m 25s	remaining: 2m 14s
8403:	learn: 0.0016270	total: 14m 26s	remaining: 2m 44s
8005:	learn: 0.0013585	total: 14m 26s	remaining: 3m 35s
8654:	learn: 0.0014931	total: 14m 25s	remaining: 2m 14s
8811:	learn: 0.0014136	total: 14m 26s	remaining: 1m 56s
8651:	learn: 0.0013819	total: 14m 26s	remaining: 2m 14s
8404:	learn: 0.0016266	total: 14m 26s	remaining: 2m 44s
8655:	learn: 0.0014931	total: 14m 26s	remaining: 2m 14s
8812:	learn: 0.0014136	total: 14m 26s	remaining: 1m 56s
8006:	learn: 0.0013585	total: 14m 26s	remaining: 3m 35s
8652:	learn: 0.0013819	total: 14m 26s	remaining: 2m 14s
8656:	learn: 0.0014931	total: 14m 26s	remaining: 2m 14s
8405:	learn: 0.0016267	total: 14m 26s	remaining: 2m 44s
8813:	learn: 0.0014136	total: 14m 26s	remaining: 1m 56s
8007:	learn: 0.0013586	total: 14m 26s	remaining: 3m 35s
8653:	learn: 0.0013819	total: 14m 26s	remaining: 2m 14s
8657:	learn: 0.0014931	total: 14m 26s	remaining: 2m 14s
8814:	learn: 0.0014136	total: 14m 26s	remaining: 1m 56s
8406:	learn: 0.0016266	total: 14m 26s	remaining: 2m 44s
8654:	learn: 0.0013819	total: 14m 26s	remaining: 2m 14s
8008:	learn: 0.0013585	total: 14m 26s	remaining: 3m 35s
8658:	learn: 0.0014931	total: 14m 26s	remaining: 2m 14s
8815:	learn: 0.0014136	total: 14m 26s	remaining: 1m 56s
8407:	learn: 0.0016266	total: 14m 26s	remaining: 2m 44s
8009:	learn: 0.0013585	total: 14m 26s	remaining: 3m 35s
8655:	learn: 0.0013819	total: 14m 26s	remaining: 2m 14s
8659:	learn: 0.0014931	total: 14m 26s	remaining: 2m 14s
8656:	learn: 0.0013819	total: 14m 26s	remaining: 2m 14s
8816:	learn: 0.0014136	total: 14m 26s	remaining: 1m 56s
8010:	learn: 0.0013585	total: 14m 26s	remaining: 3m 35s
8408:	learn: 0.0016266	total: 14m 26s	remaining: 2m 44s
8657:	learn: 0.0013819	total: 14m 26s	remaining: 2m 14s
8660:	learn: 0.0014931	total: 14m 26s	remaining: 2m 13s
8817:	learn: 0.0014136	total: 14m 26s	remaining: 1m 56s
8011:	learn: 0.0013585	total: 14m 26s	remaining: 3m 35s
8661:	learn: 0.0014931	total: 14m 26s	remaining: 2m 13s
8409:	learn: 0.0016262	total: 14m 26s	remaining: 2m 43s
8658:	learn: 0.0013819	total: 14m 26s	remaining: 2m 14s
8012:	learn: 0.0013585	total: 14m 26s	remaining: 3m 34s
8818:	learn: 0.0014136	total: 14m 26s	remaining: 1m 56s
8662:	learn: 0.0014931	total: 14m 26s	remaining: 2m 13s
8410:	learn: 0.0016262	total: 14m 27s	remaining: 2m 43s
8659:	learn: 0.0013813	total: 14m 27s	remaining: 2m 14s
8013:	learn: 0.0013585	total: 14m 27s	remaining: 3m 34s
8663:	learn: 0.0014931	total: 14m 26s	remaining: 2m 13s
8819:	learn: 0.0014136	total: 14m 26s	remaining: 1m 55s
8411:	learn: 0.0016259	total: 14m 27s	remaining: 2m 43s
8664:	learn: 0.0014931	total: 14m 26s	remaining: 2m 13s
8660:	learn: 0.0013813	total: 14m 27s	remaining: 2m 14s
8014:	learn: 0.0013585	total: 14m 27s	remaining: 3m 34s
8820:	learn: 0.0014136	total: 14m 26s	remaining: 1m 55s
8412:	learn: 0.0016259	total: 14m 27s	remaining: 2m 43s
8661:	learn: 0.0013813	total: 14m 27s	remaining: 2m 13s
8821:	learn: 0.0014136	total: 14m 27s	remaining: 1m 55s
8665:	learn: 0.0014931	total: 14m 27s	remaining: 2m 13s
8015:	learn: 0.0013585	total: 14m 27s	remaining: 3m 34s
8413:	learn: 0.0016258	total: 14m 27s	remaining: 2m 43s
8662:	learn: 0.0013813	total: 14m 27s	remaining: 2m 13s
8666:	learn: 0.0014931	total: 14m 27s	remaining: 2m 13s
8822:	learn: 0.0014136	total: 14m 27s	remaining: 1m 55s
8016:	learn: 0.0013585	total: 14m 27s	remaining: 3m 34s
8414:	learn: 0.0016258	total: 14m 27s	remaining: 2m 43s
8663:	learn: 0.0013813	total: 14m 27s	remaining: 2m 13s
8667:	learn: 0.0014931	total: 14m 27s	remaining: 2m 13s
8823:	learn: 0.0014136	total: 14m 27s	remaining: 1m 55s
8415:	learn: 0.0016258	total: 14m 27s	remaining: 2m 43s
8017:	learn: 0.0013585	total: 14m 27s	remaining: 3m 34s
8664:	learn: 0.0013813	total: 14m 27s	remaining: 2m 13s
8668:	learn: 0.0014931	total: 14m 27s	remaining: 2m 13s
8824:	learn: 0.0014136	total: 14m 27s	remaining: 1m 55s
8416:	learn: 0.0016258	total: 14m 27s	remaining: 2m 43s
8825:	learn: 0.0014136	total: 14m 27s	remaining: 1m 55s
8665:	learn: 0.0013813	total: 14m 27s	remaining: 2m 13s
8669:	learn: 0.0014931	total: 14m 27s	remaining: 2m 13s
8018:	learn: 0.0013585	total: 14m 27s	remaining: 3m 34s
8417:	learn: 0.0016258	total: 14m 27s	remaining: 2m 43s
8826:	learn: 0.0014136	total: 14m 27s	remaining: 1m 55s
8670:	learn: 0.0014931	total: 14m 27s	remaining: 2m 12s
8666:	learn: 0.0013813	total: 14m 27s	remaining: 2m 13s
8019:	learn: 0.0013585	total: 14m 27s	remaining: 3m 34s
8418:	learn: 0.0016258	total: 14m 27s	remaining: 2m 42s
8827:	learn: 0.0014136	total: 14m 27s	remaining: 1m 55s
8671:	learn: 0.0014931	total: 14m 27s	remaining: 2m 12s
8667:	learn: 0.0013813	total: 14m 27s	remaining: 2m 13s
8020:	learn: 0.0013585	total: 14m 27s	remaining: 3m 34s
8419:	learn: 0.0016254	total: 14m 27s	remaining: 2m 42s
8668:	learn: 0.0013810	total: 14m 27s	remaining: 2m 13s
8828:	learn: 0.0014136	total: 14m 27s	remaining: 1m 55s
8672:	learn: 0.0014931	total: 14m 27s	remaining: 2m 12s
8420:	learn: 0.0016254	total: 14m 28s	remaining: 2m 42s
8021:	learn: 0.0013585	total: 14m 27s	remaining: 3m 34s
8673:	learn: 0.0014931	total: 14m 27s	remaining: 2m 12s
8829:	learn: 0.0014136	total: 14m 27s	remaining: 1m 54s
8669:	learn: 0.0013807	total: 14m 28s	remaining: 2m 13s
8022:	learn: 0.0013585	total: 14m 28s	remaining: 3m 33s
8830:	learn: 0.0014136	total: 14m 27s	remaining: 1m 54s
8421:	learn: 0.0016254	total: 14m 28s	remaining: 2m 42s
8674:	learn: 0.0014931	total: 14m 27s	remaining: 2m 12s
8670:	learn: 0.0013802	total: 14m 28s	remaining: 2m 13s
8675:	learn: 0.0014931	total: 14m 27s	remaining: 2m 12s
8422:	learn: 0.0016254	total: 14m 28s	remaining: 2m 42s
8023:	learn: 0.0013585	total: 14m 28s	remaining: 3m 33s
8831:	learn: 0.0014136	total: 14m 28s	remaining: 1m 54s
8671:	learn: 0.0013799	total: 14m 28s	remaining: 2m 12s
8423:	learn: 0.0016254	total: 14m 28s	remaining: 2m 42s
8676:	learn: 0.0014931	total: 14m 28s	remaining: 2m 12s
8832:	learn: 0.0014136	total: 14m 28s	remaining: 1m 54s
8024:	learn: 0.0013585	total: 14m 28s	remaining: 3m 33s
8672:	learn: 0.0013798	total: 14m 28s	remaining: 2m 12s
8424:	learn: 0.0016254	total: 14m 28s	remaining: 2m 42s
8677:	learn: 0.0014931	total: 14m 28s	remaining: 2m 12s
8833:	learn: 0.0014136	total: 14m 28s	remaining: 1m 54s
8673:	learn: 0.0013798	total: 14m 28s	remaining: 2m 12s
8025:	learn: 0.0013585	total: 14m 28s	remaining: 3m 33s
8425:	learn: 0.0016250	total: 14m 28s	remaining: 2m 42s
8678:	learn: 0.0014931	total: 14m 28s	remaining: 2m 12s
8834:	learn: 0.0014136	total: 14m 28s	remaining: 1m 54s
8674:	learn: 0.0013798	total: 14m 28s	remaining: 2m 12s
8426:	learn: 0.0016250	total: 14m 28s	remaining: 2m 42s
8026:	learn: 0.0013585	total: 14m 28s	remaining: 3m 33s
8835:	learn: 0.0014136	total: 14m 28s	remaining: 1m 54s
8679:	learn: 0.0014931	total: 14m 28s	remaining: 2m 12s
8675:	learn: 0.0013798	total: 14m 28s	remaining: 2m 12s
8027:	learn: 0.0013585	total: 14m 28s	remaining: 3m 33s
8427:	learn: 0.0016247	total: 14m 28s	remaining: 2m 42s
8836:	learn: 0.0014136	total: 14m 28s	remaining: 1m 54s
8676:	learn: 0.0013798	total: 14m 28s	remaining: 2m 12s
8680:	learn: 0.0014931	total: 14m 28s	remaining: 2m 11s
8028:	learn: 0.0013585	total: 14m 28s	remaining: 3m 33s
8428:	learn: 0.0016246	total: 14m 28s	remaining: 2m 41s
8837:	learn: 0.0014136	total: 14m 28s	remaining: 1m 54s
8677:	learn: 0.0013798	total: 14m 28s	remaining: 2m 12s
8681:	learn: 0.0014931	total: 14m 28s	remaining: 2m 11s
8429:	learn: 0.0016246	total: 14m 28s	remaining: 2m 41s
8029:	learn: 0.0013585	total: 14m 28s	remaining: 3m 33s
8678:	learn: 0.0013794	total: 14m 28s	remaining: 2m 12s
8838:	learn: 0.0014136	total: 14m 28s	remaining: 1m 54s
8682:	learn: 0.0014931	total: 14m 28s	remaining: 2m 11s
8430:	learn: 0.0016246	total: 14m 28s	remaining: 2m 41s
8839:	learn: 0.0014136	total: 14m 28s	remaining: 1m 54s
8683:	learn: 0.0014931	total: 14m 28s	remaining: 2m 11s
8030:	learn: 0.0013585	total: 14m 29s	remaining: 3m 33s
8679:	learn: 0.0013794	total: 14m 28s	remaining: 2m 12s
8431:	learn: 0.0016243	total: 14m 29s	remaining: 2m 41s
8840:	learn: 0.0014136	total: 14m 28s	remaining: 1m 53s
8684:	learn: 0.0014931	total: 14m 28s	remaining: 2m 11s
8031:	learn: 0.0013585	total: 14m 29s	remaining: 3m 32s
8680:	learn: 0.0013794	total: 14m 29s	remaining: 2m 12s
8841:	learn: 0.0014135	total: 14m 28s	remaining: 1m 53s
8432:	learn: 0.0016243	total: 14m 29s	remaining: 2m 41s
8685:	learn: 0.0014931	total: 14m 28s	remaining: 2m 11s
8032:	learn: 0.0013585	total: 14m 29s	remaining: 3m 32s
8681:	learn: 0.0013794	total: 14m 29s	remaining: 2m 11s
8842:	learn: 0.0014135	total: 14m 29s	remaining: 1m 53s
8433:	learn: 0.0016243	total: 14m 29s	remaining: 2m 41s
8686:	learn: 0.0014931	total: 14m 29s	remaining: 2m 11s
8843:	learn: 0.0014133	total: 14m 29s	remaining: 1m 53s
8682:	learn: 0.0013794	total: 14m 29s	remaining: 2m 11s
8434:	learn: 0.0016243	total: 14m 29s	remaining: 2m 41s
8033:	learn: 0.0013583	total: 14m 29s	remaining: 3m 32s
8687:	learn: 0.0014931	total: 14m 29s	remaining: 2m 11s
8844:	learn: 0.0014133	total: 14m 29s	remaining: 1m 53s
8683:	learn: 0.0013794	total: 14m 29s	remaining: 2m 11s
8688:	learn: 0.0014931	total: 14m 29s	remaining: 2m 11s
8435:	learn: 0.0016243	total: 14m 29s	remaining: 2m 41s
8034:	learn: 0.0013583	total: 14m 29s	remaining: 3m 32s
8684:	learn: 0.0013794	total: 14m 29s	remaining: 2m 11s
8845:	learn: 0.0014133	total: 14m 29s	remaining: 1m 53s
8689:	learn: 0.0014931	total: 14m 29s	remaining: 2m 11s
8035:	learn: 0.0013583	total: 14m 29s	remaining: 3m 32s
8436:	learn: 0.0016243	total: 14m 29s	remaining: 2m 41s
8846:	learn: 0.0014133	total: 14m 29s	remaining: 1m 53s
8685:	learn: 0.0013791	total: 14m 29s	remaining: 2m 11s
8036:	learn: 0.0013581	total: 14m 29s	remaining: 3m 32s
8690:	learn: 0.0014931	total: 14m 29s	remaining: 2m 10s
8847:	learn: 0.0014131	total: 14m 29s	remaining: 1m 53s
8437:	learn: 0.0016243	total: 14m 29s	remaining: 2m 41s
8686:	learn: 0.0013791	total: 14m 29s	remaining: 2m 11s
8037:	learn: 0.0013581	total: 14m 29s	remaining: 3m 32s
8691:	learn: 0.0014931	total: 14m 29s	remaining: 2m 10s
8848:	learn: 0.0014131	total: 14m 29s	remaining: 1m 53s
8687:	learn: 0.0013791	total: 14m 29s	remaining: 2m 11s
8438:	learn: 0.0016240	total: 14m 29s	remaining: 2m 40s
8692:	learn: 0.0014931	total: 14m 29s	remaining: 2m 10s
8038:	learn: 0.0013579	total: 14m 29s	remaining: 3m 32s
8688:	learn: 0.0013791	total: 14m 29s	remaining: 2m 11s
8849:	learn: 0.0014131	total: 14m 29s	remaining: 1m 53s
8439:	learn: 0.0016240	total: 14m 29s	remaining: 2m 40s
8693:	learn: 0.0014931	total: 14m 29s	remaining: 2m 10s
8689:	learn: 0.0013791	total: 14m 29s	remaining: 2m 11s
8039:	learn: 0.0013579	total: 14m 30s	remaining: 3m 32s
8440:	learn: 0.0016236	total: 14m 30s	remaining: 2m 40s
8850:	learn: 0.0014131	total: 14m 29s	remaining: 1m 52s
8694:	learn: 0.0014931	total: 14m 29s	remaining: 2m 10s
8040:	learn: 0.0013579	total: 14m 30s	remaining: 3m 31s
8690:	learn: 0.0013791	total: 14m 30s	remaining: 2m 11s
8851:	learn: 0.0014131	total: 14m 29s	remaining: 1m 52s
8695:	learn: 0.0014931	total: 14m 29s	remaining: 2m 10s
8441:	learn: 0.0016235	total: 14m 30s	remaining: 2m 40s
8041:	learn: 0.0013579	total: 14m 30s	remaining: 3m 31s
8696:	learn: 0.0014931	total: 14m 29s	remaining: 2m 10s
8691:	learn: 0.0013791	total: 14m 30s	remaining: 2m 10s
8852:	learn: 0.0014131	total: 14m 30s	remaining: 1m 52s
8042:	learn: 0.0013579	total: 14m 30s	remaining: 3m 31s
8442:	learn: 0.0016232	total: 14m 30s	remaining: 2m 40s
8697:	learn: 0.0014931	total: 14m 30s	remaining: 2m 10s
8692:	learn: 0.0013791	total: 14m 30s	remaining: 2m 10s
8853:	learn: 0.0014131	total: 14m 30s	remaining: 1m 52s
8443:	learn: 0.0016226	total: 14m 30s	remaining: 2m 40s
8043:	learn: 0.0013579	total: 14m 30s	remaining: 3m 31s
8698:	learn: 0.0014931	total: 14m 30s	remaining: 2m 10s
8693:	learn: 0.0013791	total: 14m 30s	remaining: 2m 10s
8854:	learn: 0.0014131	total: 14m 30s	remaining: 1m 52s
8444:	learn: 0.0016226	total: 14m 30s	remaining: 2m 40s
8044:	learn: 0.0013579	total: 14m 30s	remaining: 3m 31s
8694:	learn: 0.0013791	total: 14m 30s	remaining: 2m 10s
8699:	learn: 0.0014931	total: 14m 30s	remaining: 2m 10s
8855:	learn: 0.0014131	total: 14m 30s	remaining: 1m 52s
8445:	learn: 0.0016223	total: 14m 30s	remaining: 2m 40s
8700:	learn: 0.0014931	total: 14m 30s	remaining: 2m 9s
8695:	learn: 0.0013791	total: 14m 30s	remaining: 2m 10s
8045:	learn: 0.0013579	total: 14m 30s	remaining: 3m 31s
8856:	learn: 0.0014131	total: 14m 30s	remaining: 1m 52s
8446:	learn: 0.0016219	total: 14m 30s	remaining: 2m 40s
8701:	learn: 0.0014931	total: 14m 30s	remaining: 2m 9s
8696:	learn: 0.0013790	total: 14m 30s	remaining: 2m 10s
8046:	learn: 0.0013579	total: 14m 30s	remaining: 3m 31s
8857:	learn: 0.0014131	total: 14m 30s	remaining: 1m 52s
8447:	learn: 0.0016218	total: 14m 30s	remaining: 2m 39s
8697:	learn: 0.0013791	total: 14m 30s	remaining: 2m 10s
8858:	learn: 0.0014131	total: 14m 30s	remaining: 1m 52s
8702:	learn: 0.0014931	total: 14m 30s	remaining: 2m 9s
8448:	learn: 0.0016215	total: 14m 30s	remaining: 2m 39s
8047:	learn: 0.0013579	total: 14m 30s	remaining: 3m 31s
8698:	learn: 0.0013791	total: 14m 30s	remaining: 2m 10s
8859:	learn: 0.0014131	total: 14m 30s	remaining: 1m 52s
8449:	learn: 0.0016215	total: 14m 30s	remaining: 2m 39s

8699:	learn: 0.0013790	total: 14m 30s	remaining: 2m 10s
8703:	learn: 0.0014931	total: 14m 30s	remaining: 2m 9s
8048:	learn: 0.0013579	total: 14m 30s	remaining: 3m 31s
8860:	learn: 0.0014131	total: 14m 30s	remaining: 1m 51s
8450:	learn: 0.0016215	total: 14m 31s	remaining: 2m 39s
8700:	learn: 0.0013787	total: 14m 31s	remaining: 2m 10s
8704:	learn: 0.0014931	total: 14m 30s	remaining: 2m 9s
8049:	learn: 0.0013579	total: 14m 31s	remaining: 3m 31s
8861:	learn: 0.0014131	total: 14m 30s	remaining: 1m 51s
8701:	learn: 0.0013787	total: 14m 31s	remaining: 2m 9s
8451:	learn: 0.0016215	total: 14m 31s	remaining: 2m 39s
8705:	learn: 0.0014931	total: 14m 30s	remaining: 2m 9s
8050:	learn: 0.0013579	total: 14m 31s	remaining: 3m 30s
8862:	learn: 0.0014131	total: 14m 30s	remaining: 1m 51s
8702:	learn: 0.0013787	total: 14m 31s	remaining: 2m 9s
8452:	learn: 0.0016215	total: 14m 31s	remaining: 2m 39s
8706:	learn: 0.0014931	total: 14m 31s	remaining: 2m 9s
8863:	learn: 0.0014131	total: 14m 31s	remaining: 1m 51s
8051:	learn: 0.0013579	total: 14m 31s	remaining: 3m 30s
8703:	learn: 0.0013787	total: 14m 31s	remaining: 2m 9s
8453:	learn: 0.0016215	total: 14m 31s	remaining: 2m 39s
8864:	learn: 0.0014128	total: 14m 31s	remaining: 1m 51s
8707:	learn: 0.0014931	total: 14m 31s	remaining: 2m 9s
8052:	learn: 0.0013579	total: 14m 31s	remaining: 3m 30s
8704:	learn: 0.0013787	total: 14m 31s	remaining: 2m 9s
8454:	learn: 0.0016215	total: 14m 31s	remaining: 2m 39s
8053:	learn: 0.0013579	total: 14m 31s	remaining: 3m 30s
8708:	learn: 0.0014931	total: 14m 31s	remaining: 2m 9s
8865:	learn: 0.0014128	total: 14m 31s	remaining: 1m 51s
8705:	learn: 0.0013787	total: 14m 31s	remaining: 2m 9s
8054:	learn: 0.0013579	total: 14m 31s	remaining: 3m 30s
8866:	learn: 0.0014128	total: 14m 31s	remaining: 1m 51s
8455:	learn: 0.0016215	total: 14m 31s	remaining: 2m 39s
8709:	learn: 0.0014931	total: 14m 31s	remaining: 2m 9s
8706:	learn: 0.0013787	total: 14m 31s	remaining: 2m 9s
8055:	learn: 0.0013579	total: 14m 31s	remaining: 3m 30s
8867:	learn: 0.0014125	total: 14m 31s	remaining: 1m 51s
8456:	learn: 0.0016209	total: 14m 31s	remaining: 2m 39s
8710:	learn: 0.0014931	total: 14m 31s	remaining: 2m 8s
8707:	learn: 0.0013787	total: 14m 31s	remaining: 2m 9s
8868:	learn: 0.0014125	total: 14m 31s	remaining: 1m 51s
8056:	learn: 0.0013579	total: 14m 31s	remaining: 3m 30s
8457:	learn: 0.0016209	total: 14m 31s	remaining: 2m 38s
8708:	learn: 0.0013787	total: 14m 31s	remaining: 2m 9s
8711:	learn: 0.0014931	total: 14m 31s	remaining: 2m 8s
8869:	learn: 0.0014125	total: 14m 31s	remaining: 1m 51s
8057:	learn: 0.0013579	total: 14m 31s	remaining: 3m 30s
8712:	learn: 0.0014931	total: 14m 31s	remaining: 2m 8s
8458:	learn: 0.0016209	total: 14m 31s	remaining: 2m 38s
8709:	learn: 0.0013787	total: 14m 31s	remaining: 2m 9s
8870:	learn: 0.0014125	total: 14m 31s	remaining: 1m 50s
8058:	learn: 0.0013579	total: 14m 31s	remaining: 3m 30s
8713:	learn: 0.0014931	total: 14m 31s	remaining: 2m 8s
8710:	learn: 0.0013787	total: 14m 31s	remaining: 2m 9s
8459:	learn: 0.0016208	total: 14m 32s	remaining: 2m 38s
8714:	learn: 0.0014931	total: 14m 31s	remaining: 2m 8s
8871:	learn: 0.0014125	total: 14m 31s	remaining: 1m 50s
8059:	learn: 0.0013579	total: 14m 32s	remaining: 3m 29s
8711:	learn: 0.0013787	total: 14m 32s	remaining: 2m 8s
8460:	learn: 0.0016208	total: 14m 32s	remaining: 2m 38s
8715:	learn: 0.0014931	total: 14m 31s	remaining: 2m 8s
8872:	learn: 0.0014121	total: 14m 31s	remaining: 1m 50s
8060:	learn: 0.0013579	total: 14m 32s	remaining: 3m 29s
8712:	learn: 0.0013785	total: 14m 32s	remaining: 2m 8s
8716:	learn: 0.0014931	total: 14m 31s	remaining: 2m 8s
8461:	learn: 0.0016207	total: 14m 32s	remaining: 2m 38s
8061:	learn: 0.0013579	total: 14m 32s	remaining: 3m 29s
8873:	learn: 0.0014121	total: 14m 32s	remaining: 1m 50s
8717:	learn: 0.0014931	total: 14m 32s	remaining: 2m 8s
8713:	learn: 0.0013785	total: 14m 32s	remaining: 2m 8s
8062:	learn: 0.0013579	total: 14m 32s	remaining: 3m 29s
8462:	learn: 0.0016207	total: 14m 32s	remaining: 2m 38s
8874:	learn: 0.0014121	total: 14m 32s	remaining: 1m 50s
8718:	learn: 0.0014931	total: 14m 32s	remaining: 2m 8s
8714:	learn: 0.0013785	total: 14m 32s	remaining: 2m 8s
8463:	learn: 0.0016207	total: 14m 32s	remaining: 2m 38s
8063:	learn: 0.0013579	total: 14m 32s	remaining: 3m 29s
8719:	learn: 0.0014931	total: 14m 32s	remaining: 2m 8s
8875:	learn: 0.0014121	total: 14m 32s	remaining: 1m 50s
8715:	learn: 0.0013779	total: 14m 32s	remaining: 2m 8s
8464:	learn: 0.0016205	total: 14m 32s	remaining: 2m 38s
8720:	learn: 0.0014931	total: 14m 32s	remaining: 2m 7s
8716:	learn: 0.0013779	total: 14m 32s	remaining: 2m 8s
8064:	learn: 0.0013579	total: 14m 32s	remaining: 3m 29s
8876:	learn: 0.0014121	total: 14m 32s	remaining: 1m 50s
8465:	learn: 0.0016205	total: 14m 32s	remaining: 2m 38s
8717:	learn: 0.0013779	total: 14m 32s	remaining: 2m 8s
8721:	learn: 0.0014931	total: 14m 32s	remaining: 2m 7s
8065:	learn: 0.0013579	total: 14m 32s	remaining: 3m 29s
8877:	learn: 0.0014121	total: 14m 32s	remaining: 1m 50s
8466:	learn: 0.0016205	total: 14m 32s	remaining: 2m 38s
8718:	learn: 0.0013779	total: 14m 32s	remaining: 2m 8s
8878:	learn: 0.0014121	total: 14m 32s	remaining: 1m 50s
8722:	learn: 0.0014931	total: 14m 32s	remaining: 2m 7s
8066:	learn: 0.0013579	total: 14m 32s	remaining: 3m 29s
8719:	learn: 0.0013779	total: 14m 32s	remaining: 2m 8s
8467:	learn: 0.0016205	total: 14m 32s	remaining: 2m 37s
8879:	learn: 0.0014121	total: 14m 32s	remaining: 1m 50s
8067:	learn: 0.0013579	total: 14m 32s	remaining: 3m 29s
8723:	learn: 0.0014931	total: 14m 32s	remaining: 2m 7s
8468:	learn: 0.0016205	total: 14m 33s	remaining: 2m 37s
8720:	learn: 0.0013777	total: 14m 32s	remaining: 2m 8s
8724:	learn: 0.0014931	total: 14m 32s	remaining: 2m 7s
8068:	learn: 0.0013579	total: 14m 32s	remaining: 3m 28s
8880:	learn: 0.0014121	total: 14m 32s	remaining: 1m 49s
8469:	learn: 0.0016205	total: 14m 33s	remaining: 2m 37s
8725:	learn: 0.0014931	total: 14m 32s	remaining: 2m 7s
8721:	learn: 0.0013777	total: 14m 33s	remaining: 2m 7s
8069:	learn: 0.0013579	total: 14m 33s	remaining: 3m 28s
8881:	learn: 0.0014120	total: 14m 32s	remaining: 1m 49s
8470:	learn: 0.0016205	total: 14m 33s	remaining: 2m 37s
8722:	learn: 0.0013777	total: 14m 33s	remaining: 2m 7s
8726:	learn: 0.0014931	total: 14m 32s	remaining: 2m 7s
8070:	learn: 0.0013579	total: 14m 33s	remaining: 3m 28s
8471:	learn: 0.0016205	total: 14m 33s	remaining: 2m 37s
8723:	learn: 0.0013777	total: 14m 33s	remaining: 2m 7s
8882:	learn: 0.0014120	total: 14m 33s	remaining: 1m 49s
8727:	learn: 0.0014931	total: 14m 33s	remaining: 2m 7s
8472:	learn: 0.0016201	total: 14m 33s	remaining: 2m 37s
8724:	learn: 0.0013778	total: 14m 33s	remaining: 2m 7s
8071:	learn: 0.0013579	total: 14m 33s	remaining: 3m 28s
8883:	learn: 0.0014121	total: 14m 33s	remaining: 1m 49s
8728:	learn: 0.0014931	total: 14m 33s	remaining: 2m 7s
8884:	learn: 0.0014120	total: 14m 33s	remaining: 1m 49s
8473:	learn: 0.0016201	total: 14m 33s	remaining: 2m 37s
8725:	learn: 0.0013778	total: 14m 33s	remaining: 2m 7s
8072:	learn: 0.0013578	total: 14m 33s	remaining: 3m 28s
8885:	learn: 0.0014120	total: 14m 33s	remaining: 1m 49s
8729:	learn: 0.0014931	total: 14m 33s	remaining: 2m 7s
8474:	learn: 0.0016201	total: 14m 33s	remaining: 2m 37s
8073:	learn: 0.0013579	total: 14m 33s	remaining: 3m 28s
8726:	learn: 0.0013777	total: 14m 33s	remaining: 2m 7s
8886:	learn: 0.0014120	total: 14m 33s	remaining: 1m 49s
8730:	learn: 0.0014931	total: 14m 33s	remaining: 2m 6s
8475:	learn: 0.0016201	total: 14m 33s	remaining: 2m 37s
8074:	learn: 0.0013579	total: 14m 33s	remaining: 3m 28s
8887:	learn: 0.0014121	total: 14m 33s	remaining: 1m 49s
8727:	learn: 0.0013777	total: 14m 33s	remaining: 2m 7s
8476:	learn: 0.0016201	total: 14m 33s	remaining: 2m 36s
8075:	learn: 0.0013578	total: 14m 33s	remaining: 3m 28s
8731:	learn: 0.0014931	total: 14m 33s	remaining: 2m 6s
8888:	learn: 0.0014120	total: 14m 33s	remaining: 1m 49s
8728:	learn: 0.0013777	total: 14m 33s	remaining: 2m 7s
8477:	learn: 0.0016201	total: 14m 33s	remaining: 2m 36s
8076:	learn: 0.0013579	total: 14m 33s	remaining: 3m 28s
8729:	learn: 0.0013773	total: 14m 33s	remaining: 2m 7s
8732:	learn: 0.0014931	total: 14m 33s	remaining: 2m 6s
8889:	learn: 0.0014121	total: 14m 33s	remaining: 1m 49s
8478:	learn: 0.0016201	total: 14m 33s	remaining: 2m 36s
8730:	learn: 0.0013772	total: 14m 33s	remaining: 2m 7s
8890:	learn: 0.0014121	total: 14m 33s	remaining: 1m 48s
8733:	learn: 0.0014931	total: 14m 33s	remaining: 2m 6s
8077:	learn: 0.0013579	total: 14m 34s	remaining: 3m 27s
8731:	learn: 0.0013771	total: 14m 34s	remaining: 2m 6s
8734:	learn: 0.0014931	total: 14m 33s	remaining: 2m 6s
8479:	learn: 0.0016201	total: 14m 34s	remaining: 2m 36s
8891:	learn: 0.0014121	total: 14m 33s	remaining: 1m 48s
8078:	learn: 0.0013579	total: 14m 34s	remaining: 3m 27s
8732:	learn: 0.0013769	total: 14m 34s	remaining: 2m 6s
8735:	learn: 0.0014931	total: 14m 33s	remaining: 2m 6s
8892:	learn: 0.0014121	total: 14m 33s	remaining: 1m 48s
8480:	learn: 0.0016201	total: 14m 34s	remaining: 2m 36s
8733:	learn: 0.0013765	total: 14m 34s	remaining: 2m 6s
8079:	learn: 0.0013578	total: 14m 34s	remaining: 3m 27s
8736:	learn: 0.0014931	total: 14m 33s	remaining: 2m 6s
8481:	learn: 0.0016201	total: 14m 34s	remaining: 2m 36s
8893:	learn: 0.0014121	total: 14m 34s	remaining: 1m 48s
8080:	learn: 0.0013578	total: 14m 34s	remaining: 3m 27s
8734:	learn: 0.0013765	total: 14m 34s	remaining: 2m 6s
8894:	learn: 0.0014120	total: 14m 34s	remaining: 1m 48s
8737:	learn: 0.0014931	total: 14m 34s	remaining: 2m 6s
8482:	learn: 0.0016201	total: 14m 34s	remaining: 2m 36s
8081:	learn: 0.0013578	total: 14m 34s	remaining: 3m 27s
8735:	learn: 0.0013762	total: 14m 34s	remaining: 2m 6s
8738:	learn: 0.0014931	total: 14m 34s	remaining: 2m 6s
8895:	learn: 0.0014120	total: 14m 34s	remaining: 1m 48s
8082:	learn: 0.0013578	total: 14m 34s	remaining: 3m 27s
8483:	learn: 0.0016201	total: 14m 34s	remaining: 2m 36s
8736:	learn: 0.0013759	total: 14m 34s	remaining: 2m 6s
8896:	learn: 0.0014120	total: 14m 34s	remaining: 1m 48s
8739:	learn: 0.0014931	total: 14m 34s	remaining: 2m 6s
8083:	learn: 0.0013578	total: 14m 34s	remaining: 3m 27s
8484:	learn: 0.0016201	total: 14m 34s	remaining: 2m 36s
8737:	learn: 0.0013754	total: 14m 34s	remaining: 2m 6s
8084:	learn: 0.0013579	total: 14m 34s	remaining: 3m 27s
8740:	learn: 0.0014931	total: 14m 34s	remaining: 2m 5s
8897:	learn: 0.0014120	total: 14m 34s	remaining: 1m 48s
8485:	learn: 0.0016201	total: 14m 34s	remaining: 2m 36s
8738:	learn: 0.0013754	total: 14m 34s	remaining: 2m 6s
8085:	learn: 0.0013578	total: 14m 34s	remaining: 3m 27s
8898:	learn: 0.0014120	total: 14m 34s	remaining: 1m 48s
8741:	learn: 0.0014931	total: 14m 34s	remaining: 2m 5s
8486:	learn: 0.0016198	total: 14m 34s	remaining: 2m 35s
8739:	learn: 0.0013754	total: 14m 34s	remaining: 2m 6s
8086:	learn: 0.0013578	total: 14m 34s	remaining: 3m 26s
8899:	learn: 0.0014120	total: 14m 34s	remaining: 1m 48s
8487:	learn: 0.0016198	total: 14m 34s	remaining: 2m 35s
8740:	learn: 0.0013754	total: 14m 34s	remaining: 2m 6s
8742:	learn: 0.0014931	total: 14m 34s	remaining: 2m 5s
8087:	learn: 0.0013578	total: 14m 34s	remaining: 3m 26s
8900:	learn: 0.0014120	total: 14m 34s	remaining: 1m 48s
8741:	learn: 0.0013754	total: 14m 34s	remaining: 2m 5s
8488:	learn: 0.0016195	total: 14m 35s	remaining: 2m 35s
8743:	learn: 0.0014931	total: 14m 34s	remaining: 2m 5s
8901:	learn: 0.0014120	total: 14m 34s	remaining: 1m 47s
8088:	learn: 0.0013578	total: 14m 35s	remaining: 3m 26s
8744:	learn: 0.0014931	total: 14m 34s	remaining: 2m 5s
8742:	learn: 0.0013754	total: 14m 35s	remaining: 2m 5s
8489:	learn: 0.0016195	total: 14m 35s	remaining: 2m 35s
8902:	learn: 0.0014120	total: 14m 34s	remaining: 1m 47s
8089:	learn: 0.0013578	total: 14m 35s	remaining: 3m 26s
8745:	learn: 0.0014931	total: 14m 34s	remaining: 2m 5s
8490:	learn: 0.0016195	total: 14m 35s	remaining: 2m 35s
8743:	learn: 0.0013754	total: 14m 35s	remaining: 2m 5s
8903:	learn: 0.0014120	total: 14m 35s	remaining: 1m 47s
8090:	learn: 0.0013576	total: 14m 35s	remaining: 3m 26s
8746:	learn: 0.0014931	total: 14m 35s	remaining: 2m 5s
8744:	learn: 0.0013754	total: 14m 35s	remaining: 2m 5s
8491:	learn: 0.0016192	total: 14m 35s	remaining: 2m 35s
8904:	learn: 0.0014120	total: 14m 35s	remaining: 1m 47s
8091:	learn: 0.0013574	total: 14m 35s	remaining: 3m 26s
8747:	learn: 0.0014931	total: 14m 35s	remaining: 2m 5s
8745:	learn: 0.0013754	total: 14m 35s	remaining: 2m 5s
8492:	learn: 0.0016192	total: 14m 35s	remaining: 2m 35s
8905:	learn: 0.0014120	total: 14m 35s	remaining: 1m 47s
8092:	learn: 0.0013574	total: 14m 35s	remaining: 3m 26s
8493:	learn: 0.0016192	total: 14m 35s	remaining: 2m 35s
8746:	learn: 0.0013754	total: 14m 35s	remaining: 2m 5s
8906:	learn: 0.0014120	total: 14m 35s	remaining: 1m 47s
8748:	learn: 0.0014931	total: 14m 35s	remaining: 2m 5s
8093:	learn: 0.0013574	total: 14m 35s	remaining: 3m 26s
8494:	learn: 0.0016192	total: 14m 35s	remaining: 2m 35s
8747:	learn: 0.0013754	total: 14m 35s	remaining: 2m 5s
8907:	learn: 0.0014120	total: 14m 35s	remaining: 1m 47s
8749:	learn: 0.0014931	total: 14m 35s	remaining: 2m 5s
8908:	learn: 0.0014120	total: 14m 35s	remaining: 1m 47s
8094:	learn: 0.0013574	total: 14m 35s	remaining: 3m 26s
8495:	learn: 0.0016189	total: 14m 35s	remaining: 2m 35s
8748:	learn: 0.0013754	total: 14m 35s	remaining: 2m 5s
8750:	learn: 0.0014931	total: 14m 35s	remaining: 2m 4s
8095:	learn: 0.0013572	total: 14m 35s	remaining: 3m 25s
8909:	learn: 0.0014120	total: 14m 35s	remaining: 1m 47s
8496:	learn: 0.0016189	total: 14m 35s	remaining: 2m 34s
8749:	learn: 0.0013751	total: 14m 35s	remaining: 2m 5s
8751:	learn: 0.0014931	total: 14m 35s	remaining: 2m 4s
8096:	learn: 0.0013572	total: 14m 35s	remaining: 3m 25s
8497:	learn: 0.0016189	total: 14m 35s	remaining: 2m 34s
8910:	learn: 0.0014120	total: 14m 35s	remaining: 1m 47s
8750:	learn: 0.0013751	total: 14m 35s	remaining: 2m 5s
8752:	learn: 0.0014931	total: 14m 35s	remaining: 2m 4s
8097:	learn: 0.0013572	total: 14m 35s	remaining: 3m 25s
8498:	learn: 0.0016189	total: 14m 36s	remaining: 2m 34s
8911:	learn: 0.0014120	total: 14m 35s	remaining: 1m 46s
8751:	learn: 0.0013748	total: 14m 35s	remaining: 2m 4s
8753:	learn: 0.0014928	total: 14m 35s	remaining: 2m 4s
8098:	learn: 0.0013572	total: 14m 36s	remaining: 3m 25s
8499:	learn: 0.0016189	total: 14m 36s	remaining: 2m 34s
8912:	learn: 0.0014120	total: 14m 35s	remaining: 1m 46s
8754:	learn: 0.0014928	total: 14m 35s	remaining: 2m 4s
8752:	learn: 0.0013748	total: 14m 36s	remaining: 2m 4s
8913:	learn: 0.0014121	total: 14m 35s	remaining: 1m 46s
8099:	learn: 0.0013572	total: 14m 36s	remaining: 3m 25s
8500:	learn: 0.0016189	total: 14m 36s	remaining: 2m 34s
8755:	learn: 0.0014927	total: 14m 35s	remaining: 2m 4s
8914:	learn: 0.0014120	total: 14m 36s	remaining: 1m 46s
8753:	learn: 0.0013747	total: 14m 36s	remaining: 2m 4s
8100:	learn: 0.0013572	total: 14m 36s	remaining: 3m 25s
8756:	learn: 0.0014928	total: 14m 36s	remaining: 2m 4s
8501:	learn: 0.0016189	total: 14m 36s	remaining: 2m 34s
8915:	learn: 0.0014120	total: 14m 36s	remaining: 1m 46s
8754:	learn: 0.0013747	total: 14m 36s	remaining: 2m 4s
8101:	learn: 0.0013572	total: 14m 36s	remaining: 3m 25s
8757:	learn: 0.0014928	total: 14m 36s	remaining: 2m 4s
8502:	learn: 0.0016189	total: 14m 36s	remaining: 2m 34s
8755:	learn: 0.0013747	total: 14m 36s	remaining: 2m 4s
8102:	learn: 0.0013572	total: 14m 36s	remaining: 3m 25s
8916:	learn: 0.0014120	total: 14m 36s	remaining: 1m 46s
8758:	learn: 0.0014927	total: 14m 36s	remaining: 2m 4s
8503:	learn: 0.0016189	total: 14m 36s	remaining: 2m 34s
8756:	learn: 0.0013747	total: 14m 36s	remaining: 2m 4s
8917:	learn: 0.0014120	total: 14m 36s	remaining: 1m 46s
8759:	learn: 0.0014927	total: 14m 36s	remaining: 2m 4s
8103:	learn: 0.0013572	total: 14m 36s	remaining: 3m 25s
8504:	learn: 0.0016189	total: 14m 36s	remaining: 2m 34s
8757:	learn: 0.0013743	total: 14m 36s	remaining: 2m 4s
8918:	learn: 0.0014120	total: 14m 36s	remaining: 1m 46s
8760:	learn: 0.0014928	total: 14m 36s	remaining: 2m 3s
8104:	learn: 0.0013572	total: 14m 36s	remaining: 3m 24s
8505:	learn: 0.0016189	total: 14m 36s	remaining: 2m 33s
8758:	learn: 0.0013743	total: 14m 36s	remaining: 2m 4s
8919:	learn: 0.0014120	total: 14m 36s	remaining: 1m 46s
8105:	learn: 0.0013572	total: 14m 36s	remaining: 3m 24s
8761:	learn: 0.0014928	total: 14m 36s	remaining: 2m 3s
8759:	learn: 0.0013743	total: 14m 36s	remaining: 2m 4s

8506:	learn: 0.0016189	total: 14m 36s	remaining: 2m 33s
8106:	learn: 0.0013572	total: 14m 36s	remaining: 3m 24s
8762:	learn: 0.0014927	total: 14m 36s	remaining: 2m 3s
8760:	learn: 0.0013743	total: 14m 36s	remaining: 2m 4s
8920:	learn: 0.0014120	total: 14m 36s	remaining: 1m 46s
8107:	learn: 0.0013572	total: 14m 36s	remaining: 3m 24s
8507:	learn: 0.0016189	total: 14m 37s	remaining: 2m 33s
8761:	learn: 0.0013738	total: 14m 36s	remaining: 2m 3s
8763:	learn: 0.0014928	total: 14m 36s	remaining: 2m 3s
8921:	learn: 0.0014120	total: 14m 36s	remaining: 1m 45s
8508:	learn: 0.0016189	total: 14m 37s	remaining: 2m 33s
8762:	learn: 0.0013739	total: 14m 37s	remaining: 2m 3s
8108:	learn: 0.0013572	total: 14m 37s	remaining: 3m 24s
8764:	learn: 0.0014928	total: 14m 36s	remaining: 2m 3s
8922:	learn: 0.0014120	total: 14m 36s	remaining: 1m 45s
8763:	learn: 0.0013734	total: 14m 37s	remaining: 2m 3s
8509:	learn: 0.0016189	total: 14m 37s	remaining: 2m 33s
8109:	learn: 0.0013572	total: 14m 37s	remaining: 3m 24s
8765:	learn: 0.0014927	total: 14m 36s	remaining: 2m 3s
8764:	learn: 0.0013734	total: 14m 37s	remaining: 2m 3s
8923:	learn: 0.0014121	total: 14m 37s	remaining: 1m 45s
8510:	learn: 0.0016189	total: 14m 37s	remaining: 2m 33s
8766:	learn: 0.0014927	total: 14m 37s	remaining: 2m 3s
8110:	learn: 0.0013572	total: 14m 37s	remaining: 3m 24s
8765:	learn: 0.0013734	total: 14m 37s	remaining: 2m 3s
8924:	learn: 0.0014121	total: 14m 37s	remaining: 1m 45s
8767:	learn: 0.0014927	total: 14m 37s	remaining: 2m 3s
8511:	learn: 0.0016189	total: 14m 37s	remaining: 2m 33s
8766:	learn: 0.0013734	total: 14m 37s	remaining: 2m 3s
8111:	learn: 0.0013572	total: 14m 37s	remaining: 3m 24s
8925:	learn: 0.0014121	total: 14m 37s	remaining: 1m 45s
8768:	learn: 0.0014927	total: 14m 37s	remaining: 2m 3s
8767:	learn: 0.0013734	total: 14m 37s	remaining: 2m 3s
8512:	learn: 0.0016186	total: 14m 37s	remaining: 2m 33s
8112:	learn: 0.0013572	total: 14m 37s	remaining: 3m 24s
8926:	learn: 0.0014121	total: 14m 37s	remaining: 1m 45s
8769:	learn: 0.0014927	total: 14m 37s	remaining: 2m 3s
8768:	learn: 0.0013734	total: 14m 37s	remaining: 2m 3s
8513:	learn: 0.0016186	total: 14m 37s	remaining: 2m 33s
8113:	learn: 0.0013572	total: 14m 37s	remaining: 3m 23s
8927:	learn: 0.0014120	total: 14m 37s	remaining: 1m 45s
8770:	learn: 0.0014927	total: 14m 37s	remaining: 2m 2s
8769:	learn: 0.0013734	total: 14m 37s	remaining: 2m 3s
8514:	learn: 0.0016183	total: 14m 37s	remaining: 2m 33s
8771:	learn: 0.0014927	total: 14m 37s	remaining: 2m 2s
8928:	learn: 0.0014120	total: 14m 37s	remaining: 1m 45s
8114:	learn: 0.0013572	total: 14m 37s	remaining: 3m 23s
8770:	learn: 0.0013734	total: 14m 37s	remaining: 2m 2s
8772:	learn: 0.0014927	total: 14m 37s	remaining: 2m 2s
8515:	learn: 0.0016183	total: 14m 37s	remaining: 2m 32s
8771:	learn: 0.0013734	total: 14m 37s	remaining: 2m 2s
8115:	learn: 0.0013572	total: 14m 37s	remaining: 3m 23s
8929:	learn: 0.0014120	total: 14m 37s	remaining: 1m 45s
8773:	learn: 0.0014927	total: 14m 37s	remaining: 2m 2s
8772:	learn: 0.0013734	total: 14m 37s	remaining: 2m 2s
8516:	learn: 0.0016183	total: 14m 38s	remaining: 2m 32s
8930:	learn: 0.0014120	total: 14m 37s	remaining: 1m 45s
8116:	learn: 0.0013572	total: 14m 38s	remaining: 3m 23s
8774:	learn: 0.0014927	total: 14m 37s	remaining: 2m 2s
8773:	learn: 0.0013734	total: 14m 38s	remaining: 2m 2s
8931:	learn: 0.0014121	total: 14m 37s	remaining: 1m 44s
8774:	learn: 0.0013734	total: 14m 38s	remaining: 2m 2s
8517:	learn: 0.0016183	total: 14m 38s	remaining: 2m 32s
8932:	learn: 0.0014121	total: 14m 37s	remaining: 1m 44s
8775:	learn: 0.0014927	total: 14m 37s	remaining: 2m 2s
8117:	learn: 0.0013572	total: 14m 38s	remaining: 3m 23s
8775:	learn: 0.0013734	total: 14m 38s	remaining: 2m 2s
8933:	learn: 0.0014121	total: 14m 38s	remaining: 1m 44s
8118:	learn: 0.0013572	total: 14m 38s	remaining: 3m 23s
8518:	learn: 0.0016183	total: 14m 38s	remaining: 2m 32s
8776:	learn: 0.0014927	total: 14m 37s	remaining: 2m 2s
8934:	learn: 0.0014121	total: 14m 38s	remaining: 1m 44s
8776:	learn: 0.0013734	total: 14m 38s	remaining: 2m 2s
8519:	learn: 0.0016180	total: 14m 38s	remaining: 2m 32s
8777:	learn: 0.0014927	total: 14m 38s	remaining: 2m 2s
8119:	learn: 0.0013572	total: 14m 38s	remaining: 3m 23s
8777:	learn: 0.0013734	total: 14m 38s	remaining: 2m 2s
8935:	learn: 0.0014121	total: 14m 38s	remaining: 1m 44s
8520:	learn: 0.0016176	total: 14m 38s	remaining: 2m 32s
8778:	learn: 0.0014927	total: 14m 38s	remaining: 2m 2s
8778:	learn: 0.0013734	total: 14m 38s	remaining: 2m 2s
8120:	learn: 0.0013572	total: 14m 38s	remaining: 3m 23s
8936:	learn: 0.0014121	total: 14m 38s	remaining: 1m 44s
8521:	learn: 0.0016176	total: 14m 38s	remaining: 2m 32s
8779:	learn: 0.0013734	total: 14m 38s	remaining: 2m 2s
8779:	learn: 0.0014927	total: 14m 38s	remaining: 2m 2s
8121:	learn: 0.0013572	total: 14m 38s	remaining: 3m 23s
8937:	learn: 0.0014121	total: 14m 38s	remaining: 1m 44s
8780:	learn: 0.0013734	total: 14m 38s	remaining: 2m 1s
8522:	learn: 0.0016176	total: 14m 38s	remaining: 2m 32s
8780:	learn: 0.0014927	total: 14m 38s	remaining: 2m 1s
8938:	learn: 0.0014121	total: 14m 38s	remaining: 1m 44s
8781:	learn: 0.0013734	total: 14m 38s	remaining: 2m 1s
8122:	learn: 0.0013572	total: 14m 38s	remaining: 3m 23s
8523:	learn: 0.0016176	total: 14m 38s	remaining: 2m 32s
8781:	learn: 0.0014927	total: 14m 38s	remaining: 2m 1s
8782:	learn: 0.0013734	total: 14m 38s	remaining: 2m 1s
8123:	learn: 0.0013572	total: 14m 38s	remaining: 3m 22s
8939:	learn: 0.0014121	total: 14m 38s	remaining: 1m 44s
8524:	learn: 0.0016176	total: 14m 38s	remaining: 2m 32s
8782:	learn: 0.0014924	total: 14m 38s	remaining: 2m 1s
8783:	learn: 0.0013734	total: 14m 38s	remaining: 2m 1s
8940:	learn: 0.0014121	total: 14m 38s	remaining: 1m 44s
8124:	learn: 0.0013572	total: 14m 38s	remaining: 3m 22s
8525:	learn: 0.0016176	total: 14m 39s	remaining: 2m 31s
8783:	learn: 0.0014924	total: 14m 38s	remaining: 2m 1s
8784:	learn: 0.0013734	total: 14m 38s	remaining: 2m 1s
8941:	learn: 0.0014121	total: 14m 38s	remaining: 1m 43s
8785:	learn: 0.0013734	total: 14m 39s	remaining: 2m 1s
8125:	learn: 0.0013572	total: 14m 39s	remaining: 3m 22s
8784:	learn: 0.0014924	total: 14m 38s	remaining: 2m 1s
8526:	learn: 0.0016176	total: 14m 39s	remaining: 2m 31s
8942:	learn: 0.0014120	total: 14m 38s	remaining: 1m 43s
8786:	learn: 0.0013730	total: 14m 39s	remaining: 2m 1s
8785:	learn: 0.0014924	total: 14m 38s	remaining: 2m 1s
8527:	learn: 0.0016176	total: 14m 39s	remaining: 2m 31s
8126:	learn: 0.0013572	total: 14m 39s	remaining: 3m 22s
8943:	learn: 0.0014121	total: 14m 39s	remaining: 1m 43s
8787:	learn: 0.0013726	total: 14m 39s	remaining: 2m 1s
8786:	learn: 0.0014924	total: 14m 39s	remaining: 2m 1s
8127:	learn: 0.0013571	total: 14m 39s	remaining: 3m 22s
8528:	learn: 0.0016173	total: 14m 39s	remaining: 2m 31s
8944:	learn: 0.0014121	total: 14m 39s	remaining: 1m 43s
8788:	learn: 0.0013726	total: 14m 39s	remaining: 2m 1s
8787:	learn: 0.0014924	total: 14m 39s	remaining: 2m 1s
8128:	learn: 0.0013571	total: 14m 39s	remaining: 3m 22s
8529:	learn: 0.0016173	total: 14m 39s	remaining: 2m 31s
8945:	learn: 0.0014120	total: 14m 39s	remaining: 1m 43s
8788:	learn: 0.0014924	total: 14m 39s	remaining: 2m 1s
8129:	learn: 0.0013571	total: 14m 39s	remaining: 3m 22s
8789:	learn: 0.0013726	total: 14m 39s	remaining: 2m 1s
8946:	learn: 0.0014120	total: 14m 39s	remaining: 1m 43s
8530:	learn: 0.0016173	total: 14m 39s	remaining: 2m 31s
8789:	learn: 0.0014924	total: 14m 39s	remaining: 2m 1s
8130:	learn: 0.0013571	total: 14m 39s	remaining: 3m 22s
8947:	learn: 0.0014120	total: 14m 39s	remaining: 1m 43s
8790:	learn: 0.0013726	total: 14m 39s	remaining: 2m
8531:	learn: 0.0016173	total: 14m 39s	remaining: 2m 31s
8790:	learn: 0.0014924	total: 14m 39s	remaining: 2m
8791:	learn: 0.0013726	total: 14m 39s	remaining: 2m
8948:	learn: 0.0014120	total: 14m 39s	remaining: 1m 43s
8791:	learn: 0.0014919	total: 14m 39s	remaining: 2m
8131:	learn: 0.0013571	total: 14m 39s	remaining: 3m 22s
8532:	learn: 0.0016173	total: 14m 39s	remaining: 2m 31s
8949:	learn: 0.0014120	total: 14m 39s	remaining: 1m 43s
8792:	learn: 0.0013726	total: 14m 39s	remaining: 2m
8792:	learn: 0.0014919	total: 14m 39s	remaining: 2m
8950:	learn: 0.0014120	total: 14m 39s	remaining: 1m 43s
8132:	learn: 0.0013571	total: 14m 39s	remaining: 3m 21s
8793:	learn: 0.0013726	total: 14m 39s	remaining: 2m
8533:	learn: 0.0016173	total: 14m 39s	remaining: 2m 31s
8793:	learn: 0.0014919	total: 14m 39s	remaining: 2m
8951:	learn: 0.0014120	total: 14m 39s	remaining: 1m 42s
8794:	learn: 0.0013726	total: 14m 39s	remaining: 2m
8534:	learn: 0.0016173	total: 14m 40s	remaining: 2m 31s
8133:	learn: 0.0013571	total: 14m 39s	remaining: 3m 21s
8794:	learn: 0.0014919	total: 14m 39s	remaining: 2m
8134:	learn: 0.0013571	total: 14m 40s	remaining: 3m 21s
8535:	learn: 0.0016173	total: 14m 40s	remaining: 2m 30s
8952:	learn: 0.0014120	total: 14m 39s	remaining: 1m 42s
8795:	learn: 0.0013726	total: 14m 40s	remaining: 2m
8795:	learn: 0.0014919	total: 14m 39s	remaining: 2m
8536:	learn: 0.0016173	total: 14m 40s	remaining: 2m 30s
8953:	learn: 0.0014120	total: 14m 39s	remaining: 1m 42s
8135:	learn: 0.0013571	total: 14m 40s	remaining: 3m 21s
8796:	learn: 0.0013726	total: 14m 40s	remaining: 2m
8796:	learn: 0.0014919	total: 14m 39s	remaining: 2m
8537:	learn: 0.0016173	total: 14m 40s	remaining: 2m 30s
8136:	learn: 0.0013571	total: 14m 40s	remaining: 3m 21s
8954:	learn: 0.0014120	total: 14m 40s	remaining: 1m 42s
8797:	learn: 0.0013726	total: 14m 40s	remaining: 2m
8797:	learn: 0.0014919	total: 14m 40s	remaining: 2m
8955:	learn: 0.0014120	total: 14m 40s	remaining: 1m 42s
8137:	learn: 0.0013571	total: 14m 40s	remaining: 3m 21s
8538:	learn: 0.0016173	total: 14m 40s	remaining: 2m 30s
8798:	learn: 0.0013726	total: 14m 40s	remaining: 2m
8798:	learn: 0.0014919	total: 14m 40s	remaining: 2m
8799:	learn: 0.0013726	total: 14m 40s	remaining: 2m
8138:	learn: 0.0013571	total: 14m 40s	remaining: 3m 21s
8539:	learn: 0.0016170	total: 14m 40s	remaining: 2m 30s
8956:	learn: 0.0014120	total: 14m 40s	remaining: 1m 42s
8799:	learn: 0.0014919	total: 14m 40s	remaining: 2m
8800:	learn: 0.0013726	total: 14m 40s	remaining: 1m 59s
8540:	learn: 0.0016170	total: 14m 40s	remaining: 2m 30s
8957:	learn: 0.0014120	total: 14m 40s	remaining: 1m 42s
8139:	learn: 0.0013571	total: 14m 40s	remaining: 3m 21s
8800:	learn: 0.0014919	total: 14m 40s	remaining: 1m 59s
8801:	learn: 0.0013726	total: 14m 40s	remaining: 1m 59s
8958:	learn: 0.0014120	total: 14m 40s	remaining: 1m 42s
8541:	learn: 0.0016170	total: 14m 40s	remaining: 2m 30s
8140:	learn: 0.0013571	total: 14m 40s	remaining: 3m 21s
8801:	learn: 0.0014919	total: 14m 40s	remaining: 1m 59s
8959:	learn: 0.0014120	total: 14m 40s	remaining: 1m 42s
8802:	learn: 0.0013726	total: 14m 40s	remaining: 1m 59s
8542:	learn: 0.0016170	total: 14m 40s	remaining: 2m 30s
8141:	learn: 0.0013571	total: 14m 40s	remaining: 3m 20s
8802:	learn: 0.0014919	total: 14m 40s	remaining: 1m 59s
8803:	learn: 0.0013726	total: 14m 40s	remaining: 1m 59s
8960:	learn: 0.0014120	total: 14m 40s	remaining: 1m 42s
8543:	learn: 0.0016170	total: 14m 40s	remaining: 2m 30s
8142:	learn: 0.0013571	total: 14m 40s	remaining: 3m 20s
8804:	learn: 0.0013726	total: 14m 40s	remaining: 1m 59s
8961:	learn: 0.0014120	total: 14m 40s	remaining: 1m 42s
8803:	learn: 0.0014919	total: 14m 40s	remaining: 1m 59s
8544:	learn: 0.0016170	total: 14m 41s	remaining: 2m 30s
8962:	learn: 0.0014120	total: 14m 40s	remaining: 1m 41s
8143:	learn: 0.0013571	total: 14m 41s	remaining: 3m 20s
8805:	learn: 0.0013726	total: 14m 40s	remaining: 1m 59s
8804:	learn: 0.0014919	total: 14m 40s	remaining: 1m 59s
8545:	learn: 0.0016170	total: 14m 41s	remaining: 2m 29s
8144:	learn: 0.0013571	total: 14m 41s	remaining: 3m 20s
8963:	learn: 0.0014114	total: 14m 40s	remaining: 1m 41s
8806:	learn: 0.0013726	total: 14m 41s	remaining: 1m 59s
8964:	learn: 0.0014114	total: 14m 40s	remaining: 1m 41s
8805:	learn: 0.0014919	total: 14m 40s	remaining: 1m 59s
8546:	learn: 0.0016170	total: 14m 41s	remaining: 2m 29s
8145:	learn: 0.0013571	total: 14m 41s	remaining: 3m 20s
8965:	learn: 0.0014114	total: 14m 41s	remaining: 1m 41s
8807:	learn: 0.0013723	total: 14m 41s	remaining: 1m 59s
8806:	learn: 0.0014919	total: 14m 41s	remaining: 1m 59s
8547:	learn: 0.0016166	total: 14m 41s	remaining: 2m 29s
8966:	learn: 0.0014114	total: 14m 41s	remaining: 1m 41s
8146:	learn: 0.0013571	total: 14m 41s	remaining: 3m 20s
8808:	learn: 0.0013723	total: 14m 41s	remaining: 1m 59s
8548:	learn: 0.0016161	total: 14m 41s	remaining: 2m 29s
8807:	learn: 0.0014919	total: 14m 41s	remaining: 1m 59s
8967:	learn: 0.0014114	total: 14m 41s	remaining: 1m 41s
8809:	learn: 0.0013723	total: 14m 41s	remaining: 1m 59s
8147:	learn: 0.0013571	total: 14m 41s	remaining: 3m 20s
8549:	learn: 0.0016161	total: 14m 41s	remaining: 2m 29s
8968:	learn: 0.0014114	total: 14m 41s	remaining: 1m 41s
8808:	learn: 0.0014919	total: 14m 41s	remaining: 1m 59s
8550:	learn: 0.0016161	total: 14m 41s	remaining: 2m 29s
8148:	learn: 0.0013571	total: 14m 41s	remaining: 3m 20s
8810:	learn: 0.0013723	total: 14m 41s	remaining: 1m 58s
8809:	learn: 0.0014919	total: 14m 41s	remaining: 1m 59s
8969:	learn: 0.0014114	total: 14m 41s	remaining: 1m 41s
8551:	learn: 0.0016161	total: 14m 41s	remaining: 2m 29s
8149:	learn: 0.0013570	total: 14m 41s	remaining: 3m 20s
8811:	learn: 0.0013723	total: 14m 41s	remaining: 1m 58s
8810:	learn: 0.0014914	total: 14m 41s	remaining: 1m 58s
8970:	learn: 0.0014114	total: 14m 41s	remaining: 1m 41s
8150:	learn: 0.0013570	total: 14m 41s	remaining: 3m 20s
8552:	learn: 0.0016161	total: 14m 41s	remaining: 2m 29s
8812:	learn: 0.0013723	total: 14m 41s	remaining: 1m 58s
8811:	learn: 0.0014911	total: 14m 41s	remaining: 1m 58s
8971:	learn: 0.0014110	total: 14m 41s	remaining: 1m 41s
8151:	learn: 0.0013570	total: 14m 41s	remaining: 3m 19s
8553:	learn: 0.0016161	total: 14m 41s	remaining: 2m 29s
8812:	learn: 0.0014911	total: 14m 41s	remaining: 1m 58s
8972:	learn: 0.0014110	total: 14m 41s	remaining: 1m 40s
8813:	learn: 0.0013723	total: 14m 41s	remaining: 1m 58s
8152:	learn: 0.0013570	total: 14m 41s	remaining: 3m 19s
8554:	learn: 0.0016161	total: 14m 42s	remaining: 2m 28s
8814:	learn: 0.0013723	total: 14m 41s	remaining: 1m 58s
8973:	learn: 0.0014110	total: 14m 41s	remaining: 1m 40s
8813:	learn: 0.0014911	total: 14m 41s	remaining: 1m 58s
8153:	learn: 0.0013570	total: 14m 42s	remaining: 3m 19s
8974:	learn: 0.0014110	total: 14m 41s	remaining: 1m 40s
8555:	learn: 0.0016161	total: 14m 42s	remaining: 2m 28s
8815:	learn: 0.0013723	total: 14m 42s	remaining: 1m 58s
8814:	learn: 0.0014911	total: 14m 41s	remaining: 1m 58s
8975:	learn: 0.0014110	total: 14m 41s	remaining: 1m 40s
8154:	learn: 0.0013570	total: 14m 42s	remaining: 3m 19s
8556:	learn: 0.0016161	total: 14m 42s	remaining: 2m 28s
8816:	learn: 0.0013723	total: 14m 42s	remaining: 1m 58s
8976:	learn: 0.0014110	total: 14m 42s	remaining: 1m 40s
8815:	learn: 0.0014911	total: 14m 41s	remaining: 1m 58s
8817:	learn: 0.0013723	total: 14m 42s	remaining: 1m 58s
8155:	learn: 0.0013570	total: 14m 42s	remaining: 3m 19s
8557:	learn: 0.0016161	total: 14m 42s	remaining: 2m 28s
8816:	learn: 0.0014911	total: 14m 42s	remaining: 1m 58s
8977:	learn: 0.0014110	total: 14m 42s	remaining: 1m 40s
8817:	learn: 0.0014911	total: 14m 42s	remaining: 1m 58s
8818:	learn: 0.0013723	total: 14m 42s	remaining: 1m 58s
8156:	learn: 0.0013570	total: 14m 42s	remaining: 3m 19s
8978:	learn: 0.0014110	total: 14m 42s	remaining: 1m 40s
8558:	learn: 0.0016161	total: 14m 42s	remaining: 2m 28s
8818:	learn: 0.0014911	total: 14m 42s	remaining: 1m 58s
8819:	learn: 0.0013723	total: 14m 42s	remaining: 1m 58s
8979:	learn: 0.0014110	total: 14m 42s	remaining: 1m 40s
8157:	learn: 0.0013570	total: 14m 42s	remaining: 3m 19s
8819:	learn: 0.0014911	total: 14m 42s	remaining: 1m 58s
8559:	learn: 0.0016161	total: 14m 42s	remaining: 2m 28s
8820:	learn: 0.0013723	total: 14m 42s	remaining: 1m 57s
8980:	learn: 0.0014110	total: 14m 42s	remaining: 1m 40s
8158:	learn: 0.0013570	total: 14m 42s	remaining: 3m 19s
8560:	learn: 0.0016161	total: 14m 42s	remaining: 2m 28s
8820:	learn: 0.0014911	total: 14m 42s	remaining: 1m 57s
8821:	learn: 0.0013723	total: 14m 42s	remaining: 1m 57s
8981:	learn: 0.0014110	total: 14m 42s	remaining: 1m 40s
8159:	learn: 0.0013570	total: 14m 42s	remaining: 3m 19s
8561:	learn: 0.0016161	total: 14m 42s	remaining: 2m 28s
8821:	learn: 0.0014911	total: 14m 42s	remaining: 1m 57s

8982:	learn: 0.0014110	total: 14m 42s	remaining: 1m 39s
8822:	learn: 0.0013723	total: 14m 42s	remaining: 1m 57s
8160:	learn: 0.0013570	total: 14m 42s	remaining: 3m 18s
8822:	learn: 0.0014911	total: 14m 42s	remaining: 1m 57s
8983:	learn: 0.0014110	total: 14m 42s	remaining: 1m 39s
8562:	learn: 0.0016161	total: 14m 42s	remaining: 2m 28s
8823:	learn: 0.0013723	total: 14m 42s	remaining: 1m 57s
8161:	learn: 0.0013570	total: 14m 42s	remaining: 3m 18s
8823:	learn: 0.0014911	total: 14m 42s	remaining: 1m 57s
8984:	learn: 0.0014110	total: 14m 42s	remaining: 1m 39s
8563:	learn: 0.0016161	total: 14m 43s	remaining: 2m 28s
8162:	learn: 0.0013570	total: 14m 43s	remaining: 3m 18s
8824:	learn: 0.0014907	total: 14m 42s	remaining: 1m 57s
8824:	learn: 0.0013723	total: 14m 43s	remaining: 1m 57s
8985:	learn: 0.0014110	total: 14m 42s	remaining: 1m 39s
8564:	learn: 0.0016158	total: 14m 43s	remaining: 2m 27s
8825:	learn: 0.0013723	total: 14m 43s	remaining: 1m 57s
8825:	learn: 0.0014907	total: 14m 42s	remaining: 1m 57s
8163:	learn: 0.0013570	total: 14m 43s	remaining: 3m 18s
8986:	learn: 0.0014110	total: 14m 42s	remaining: 1m 39s
8565:	learn: 0.0016155	total: 14m 43s	remaining: 2m 27s
8826:	learn: 0.0013723	total: 14m 43s	remaining: 1m 57s
8826:	learn: 0.0014907	total: 14m 42s	remaining: 1m 57s
8164:	learn: 0.0013569	total: 14m 43s	remaining: 3m 18s
8987:	learn: 0.0014110	total: 14m 43s	remaining: 1m 39s
8827:	learn: 0.0013723	total: 14m 43s	remaining: 1m 57s
8566:	learn: 0.0016155	total: 14m 43s	remaining: 2m 27s
8827:	learn: 0.0014907	total: 14m 43s	remaining: 1m 57s
8988:	learn: 0.0014110	total: 14m 43s	remaining: 1m 39s
8165:	learn: 0.0013569	total: 14m 43s	remaining: 3m 18s
8828:	learn: 0.0013723	total: 14m 43s	remaining: 1m 57s
8567:	learn: 0.0016155	total: 14m 43s	remaining: 2m 27s
8828:	learn: 0.0014907	total: 14m 43s	remaining: 1m 57s
8989:	learn: 0.0014110	total: 14m 43s	remaining: 1m 39s
8829:	learn: 0.0013723	total: 14m 43s	remaining: 1m 57s
8166:	learn: 0.0013569	total: 14m 43s	remaining: 3m 18s
8568:	learn: 0.0016155	total: 14m 43s	remaining: 2m 27s
8829:	learn: 0.0014907	total: 14m 43s	remaining: 1m 57s
8990:	learn: 0.0014110	total: 14m 43s	remaining: 1m 39s
8830:	learn: 0.0013723	total: 14m 43s	remaining: 1m 56s
8569:	learn: 0.0016155	total: 14m 43s	remaining: 2m 27s
8830:	learn: 0.0014907	total: 14m 43s	remaining: 1m 56s
8167:	learn: 0.0013569	total: 14m 43s	remaining: 3m 18s
8831:	learn: 0.0013723	total: 14m 43s	remaining: 1m 56s
8570:	learn: 0.0016155	total: 14m 43s	remaining: 2m 27s
8991:	learn: 0.0014110	total: 14m 43s	remaining: 1m 39s
8831:	learn: 0.0014907	total: 14m 43s	remaining: 1m 56s
8992:	learn: 0.0014110	total: 14m 43s	remaining: 1m 38s
8168:	learn: 0.0013569	total: 14m 43s	remaining: 3m 18s
8832:	learn: 0.0013723	total: 14m 43s	remaining: 1m 56s
8571:	learn: 0.0016155	total: 14m 43s	remaining: 2m 27s
8832:	learn: 0.0014907	total: 14m 43s	remaining: 1m 56s
8993:	learn: 0.0014110	total: 14m 43s	remaining: 1m 38s
8169:	learn: 0.0013570	total: 14m 43s	remaining: 3m 17s
8833:	learn: 0.0013723	total: 14m 43s	remaining: 1m 56s
8572:	learn: 0.0016155	total: 14m 43s	remaining: 2m 27s
8833:	learn: 0.0014907	total: 14m 43s	remaining: 1m 56s
8170:	learn: 0.0013569	total: 14m 43s	remaining: 3m 17s
8994:	learn: 0.0014110	total: 14m 43s	remaining: 1m 38s
8573:	learn: 0.0016155	total: 14m 44s	remaining: 2m 27s
8834:	learn: 0.0014907	total: 14m 43s	remaining: 1m 56s
8834:	learn: 0.0013723	total: 14m 43s	remaining: 1m 56s
8995:	learn: 0.0014110	total: 14m 43s	remaining: 1m 38s
8171:	learn: 0.0013569	total: 14m 44s	remaining: 3m 17s
8574:	learn: 0.0016150	total: 14m 44s	remaining: 2m 26s
8835:	learn: 0.0014907	total: 14m 43s	remaining: 1m 56s
8835:	learn: 0.0013723	total: 14m 44s	remaining: 1m 56s
8996:	learn: 0.0014110	total: 14m 43s	remaining: 1m 38s
8172:	learn: 0.0013569	total: 14m 44s	remaining: 3m 17s
8575:	learn: 0.0016150	total: 14m 44s	remaining: 2m 26s
8836:	learn: 0.0014907	total: 14m 43s	remaining: 1m 56s
8836:	learn: 0.0013723	total: 14m 44s	remaining: 1m 56s
8997:	learn: 0.0014110	total: 14m 44s	remaining: 1m 38s
8576:	learn: 0.0016150	total: 14m 44s	remaining: 2m 26s
8173:	learn: 0.0013569	total: 14m 44s	remaining: 3m 17s
8837:	learn: 0.0014907	total: 14m 44s	remaining: 1m 56s
8998:	learn: 0.0014110	total: 14m 44s	remaining: 1m 38s
8837:	learn: 0.0013723	total: 14m 44s	remaining: 1m 56s
8999:	learn: 0.0014110	total: 14m 44s	remaining: 1m 38s
8577:	learn: 0.0016150	total: 14m 44s	remaining: 2m 26s
8838:	learn: 0.0014907	total: 14m 44s	remaining: 1m 56s
8174:	learn: 0.0013569	total: 14m 44s	remaining: 3m 17s
8838:	learn: 0.0013723	total: 14m 44s	remaining: 1m 56s
8578:	learn: 0.0016150	total: 14m 44s	remaining: 2m 26s
9000:	learn: 0.0014110	total: 14m 44s	remaining: 1m 38s
8839:	learn: 0.0014907	total: 14m 44s	remaining: 1m 56s
8175:	learn: 0.0013569	total: 14m 44s	remaining: 3m 17s
8579:	learn: 0.0016150	total: 14m 44s	remaining: 2m 26s
8839:	learn: 0.0013723	total: 14m 44s	remaining: 1m 56s
8840:	learn: 0.0014907	total: 14m 44s	remaining: 1m 55s
9001:	learn: 0.0014110	total: 14m 44s	remaining: 1m 38s
8580:	learn: 0.0016150	total: 14m 44s	remaining: 2m 26s
8176:	learn: 0.0013569	total: 14m 44s	remaining: 3m 17s
8840:	learn: 0.0013723	total: 14m 44s	remaining: 1m 55s
8841:	learn: 0.0014907	total: 14m 44s	remaining: 1m 55s
9002:	learn: 0.0014110	total: 14m 44s	remaining: 1m 37s
8177:	learn: 0.0013569	total: 14m 44s	remaining: 3m 17s
8581:	learn: 0.0016150	total: 14m 44s	remaining: 2m 26s
8842:	learn: 0.0014907	total: 14m 44s	remaining: 1m 55s
9003:	learn: 0.0014110	total: 14m 44s	remaining: 1m 37s
8841:	learn: 0.0013719	total: 14m 44s	remaining: 1m 55s
8582:	learn: 0.0016146	total: 14m 44s	remaining: 2m 26s
8178:	learn: 0.0013569	total: 14m 44s	remaining: 3m 17s
8842:	learn: 0.0013715	total: 14m 44s	remaining: 1m 55s
9004:	learn: 0.0014110	total: 14m 44s	remaining: 1m 37s
8843:	learn: 0.0014907	total: 14m 44s	remaining: 1m 55s
8583:	learn: 0.0016142	total: 14m 44s	remaining: 2m 25s
8179:	learn: 0.0013569	total: 14m 44s	remaining: 3m 16s
9005:	learn: 0.0014110	total: 14m 44s	remaining: 1m 37s
8844:	learn: 0.0014907	total: 14m 44s	remaining: 1m 55s
8843:	learn: 0.0013713	total: 14m 44s	remaining: 1m 55s
8584:	learn: 0.0016141	total: 14m 45s	remaining: 2m 25s
8180:	learn: 0.0013569	total: 14m 45s	remaining: 3m 16s
9006:	learn: 0.0014110	total: 14m 44s	remaining: 1m 37s
8845:	learn: 0.0014907	total: 14m 44s	remaining: 1m 55s
8844:	learn: 0.0013713	total: 14m 45s	remaining: 1m 55s
8585:	learn: 0.0016141	total: 14m 45s	remaining: 2m 25s
8181:	learn: 0.0013569	total: 14m 45s	remaining: 3m 16s
9007:	learn: 0.0014110	total: 14m 44s	remaining: 1m 37s
8846:	learn: 0.0014907	total: 14m 44s	remaining: 1m 55s
8845:	learn: 0.0013710	total: 14m 45s	remaining: 1m 55s
8586:	learn: 0.0016140	total: 14m 45s	remaining: 2m 25s
9008:	learn: 0.0014110	total: 14m 45s	remaining: 1m 37s
8847:	learn: 0.0014903	total: 14m 44s	remaining: 1m 55s
8182:	learn: 0.0013569	total: 14m 45s	remaining: 3m 16s
8846:	learn: 0.0013710	total: 14m 45s	remaining: 1m 55s
8587:	learn: 0.0016140	total: 14m 45s	remaining: 2m 25s
9009:	learn: 0.0014110	total: 14m 45s	remaining: 1m 37s
8848:	learn: 0.0014903	total: 14m 45s	remaining: 1m 55s
8847:	learn: 0.0013710	total: 14m 45s	remaining: 1m 55s
8183:	learn: 0.0013569	total: 14m 45s	remaining: 3m 16s
8588:	learn: 0.0016140	total: 14m 45s	remaining: 2m 25s
9010:	learn: 0.0014110	total: 14m 45s	remaining: 1m 37s
8848:	learn: 0.0013710	total: 14m 45s	remaining: 1m 55s
8849:	learn: 0.0014903	total: 14m 45s	remaining: 1m 55s
8184:	learn: 0.0013569	total: 14m 45s	remaining: 3m 16s
8589:	learn: 0.0016140	total: 14m 45s	remaining: 2m 25s
8849:	learn: 0.0013710	total: 14m 45s	remaining: 1m 55s
8850:	learn: 0.0014903	total: 14m 45s	remaining: 1m 54s
9011:	learn: 0.0014110	total: 14m 45s	remaining: 1m 37s
8185:	learn: 0.0013569	total: 14m 45s	remaining: 3m 16s
8850:	learn: 0.0013710	total: 14m 45s	remaining: 1m 54s
8590:	learn: 0.0016135	total: 14m 45s	remaining: 2m 25s
8851:	learn: 0.0014903	total: 14m 45s	remaining: 1m 54s
9012:	learn: 0.0014110	total: 14m 45s	remaining: 1m 36s
8591:	learn: 0.0016135	total: 14m 45s	remaining: 2m 25s
8186:	learn: 0.0013569	total: 14m 45s	remaining: 3m 16s
8851:	learn: 0.0013710	total: 14m 45s	remaining: 1m 54s
9013:	learn: 0.0014110	total: 14m 45s	remaining: 1m 36s
8852:	learn: 0.0014903	total: 14m 45s	remaining: 1m 54s
8852:	learn: 0.0013710	total: 14m 45s	remaining: 1m 54s
8592:	learn: 0.0016135	total: 14m 45s	remaining: 2m 25s
9014:	learn: 0.0014110	total: 14m 45s	remaining: 1m 36s
8187:	learn: 0.0013569	total: 14m 45s	remaining: 3m 16s
8853:	learn: 0.0014903	total: 14m 45s	remaining: 1m 54s
8853:	learn: 0.0013710	total: 14m 45s	remaining: 1m 54s
9015:	learn: 0.0014110	total: 14m 45s	remaining: 1m 36s
8188:	learn: 0.0013569	total: 14m 45s	remaining: 3m 15s
8593:	learn: 0.0016131	total: 14m 45s	remaining: 2m 24s
8854:	learn: 0.0014903	total: 14m 45s	remaining: 1m 54s
8854:	learn: 0.0013710	total: 14m 45s	remaining: 1m 54s
9016:	learn: 0.0014110	total: 14m 45s	remaining: 1m 36s
8855:	learn: 0.0014903	total: 14m 45s	remaining: 1m 54s
8189:	learn: 0.0013569	total: 14m 46s	remaining: 3m 15s
8594:	learn: 0.0016131	total: 14m 46s	remaining: 2m 24s
8855:	learn: 0.0013710	total: 14m 46s	remaining: 1m 54s
9017:	learn: 0.0014110	total: 14m 45s	remaining: 1m 36s
8856:	learn: 0.0014903	total: 14m 45s	remaining: 1m 54s
8190:	learn: 0.0013569	total: 14m 46s	remaining: 3m 15s
8595:	learn: 0.0016125	total: 14m 46s	remaining: 2m 24s
8856:	learn: 0.0013710	total: 14m 46s	remaining: 1m 54s
9018:	learn: 0.0014110	total: 14m 46s	remaining: 1m 36s
8857:	learn: 0.0014903	total: 14m 45s	remaining: 1m 54s
8596:	learn: 0.0016125	total: 14m 46s	remaining: 2m 24s
8191:	learn: 0.0013569	total: 14m 46s	remaining: 3m 15s
8857:	learn: 0.0013710	total: 14m 46s	remaining: 1m 54s
9019:	learn: 0.0014108	total: 14m 46s	remaining: 1m 36s
8858:	learn: 0.0014903	total: 14m 46s	remaining: 1m 54s
8597:	learn: 0.0016125	total: 14m 46s	remaining: 2m 24s
8192:	learn: 0.0013569	total: 14m 46s	remaining: 3m 15s
8859:	learn: 0.0014903	total: 14m 46s	remaining: 1m 54s
8858:	learn: 0.0013710	total: 14m 46s	remaining: 1m 54s
9020:	learn: 0.0014108	total: 14m 46s	remaining: 1m 36s
8598:	learn: 0.0016125	total: 14m 46s	remaining: 2m 24s
8193:	learn: 0.0013569	total: 14m 46s	remaining: 3m 15s
8859:	learn: 0.0013710	total: 14m 46s	remaining: 1m 54s
8860:	learn: 0.0014903	total: 14m 46s	remaining: 1m 53s
9021:	learn: 0.0014108	total: 14m 46s	remaining: 1m 36s
8194:	learn: 0.0013569	total: 14m 46s	remaining: 3m 15s
8599:	learn: 0.0016125	total: 14m 46s	remaining: 2m 24s
8860:	learn: 0.0013710	total: 14m 46s	remaining: 1m 53s
9022:	learn: 0.0014107	total: 14m 46s	remaining: 1m 35s
8861:	learn: 0.0014903	total: 14m 46s	remaining: 1m 53s
8600:	learn: 0.0016125	total: 14m 46s	remaining: 2m 24s
8195:	learn: 0.0013569	total: 14m 46s	remaining: 3m 15s
8861:	learn: 0.0013710	total: 14m 46s	remaining: 1m 53s
8862:	learn: 0.0014903	total: 14m 46s	remaining: 1m 53s
9023:	learn: 0.0014108	total: 14m 46s	remaining: 1m 35s
8196:	learn: 0.0013569	total: 14m 46s	remaining: 3m 15s
8862:	learn: 0.0013710	total: 14m 46s	remaining: 1m 53s
8601:	learn: 0.0016125	total: 14m 46s	remaining: 2m 24s
9024:	learn: 0.0014107	total: 14m 46s	remaining: 1m 35s
8863:	learn: 0.0014903	total: 14m 46s	remaining: 1m 53s
8197:	learn: 0.0013569	total: 14m 46s	remaining: 3m 14s
8863:	learn: 0.0013710	total: 14m 46s	remaining: 1m 53s
9025:	learn: 0.0014107	total: 14m 46s	remaining: 1m 35s
8864:	learn: 0.0014903	total: 14m 46s	remaining: 1m 53s
8602:	learn: 0.0016124	total: 14m 46s	remaining: 2m 24s
8198:	learn: 0.0013569	total: 14m 46s	remaining: 3m 14s
8864:	learn: 0.0013710	total: 14m 46s	remaining: 1m 53s
9026:	learn: 0.0014103	total: 14m 46s	remaining: 1m 35s
8865:	learn: 0.0014903	total: 14m 46s	remaining: 1m 53s
8603:	learn: 0.0016124	total: 14m 47s	remaining: 2m 23s
8199:	learn: 0.0013569	total: 14m 47s	remaining: 3m 14s
8865:	learn: 0.0013710	total: 14m 47s	remaining: 1m 53s
8200:	learn: 0.0013569	total: 14m 47s	remaining: 3m 14s
8866:	learn: 0.0014903	total: 14m 46s	remaining: 1m 53s
9027:	learn: 0.0014097	total: 14m 46s	remaining: 1m 35s
8604:	learn: 0.0016124	total: 14m 47s	remaining: 2m 23s
8866:	learn: 0.0013710	total: 14m 47s	remaining: 1m 53s
8867:	learn: 0.0014903	total: 14m 46s	remaining: 1m 53s
8201:	learn: 0.0013569	total: 14m 47s	remaining: 3m 14s
9028:	learn: 0.0014097	total: 14m 47s	remaining: 1m 35s
8605:	learn: 0.0016124	total: 14m 47s	remaining: 2m 23s
8868:	learn: 0.0014903	total: 14m 47s	remaining: 1m 53s
8867:	learn: 0.0013706	total: 14m 47s	remaining: 1m 53s
8202:	learn: 0.0013569	total: 14m 47s	remaining: 3m 14s
8606:	learn: 0.0016124	total: 14m 47s	remaining: 2m 23s
9029:	learn: 0.0014097	total: 14m 47s	remaining: 1m 35s
8869:	learn: 0.0014903	total: 14m 47s	remaining: 1m 53s
8868:	learn: 0.0013702	total: 14m 47s	remaining: 1m 53s
8203:	learn: 0.0013569	total: 14m 47s	remaining: 3m 14s
8607:	learn: 0.0016124	total: 14m 47s	remaining: 2m 23s
9030:	learn: 0.0014097	total: 14m 47s	remaining: 1m 35s
8870:	learn: 0.0014903	total: 14m 47s	remaining: 1m 52s
8869:	learn: 0.0013699	total: 14m 47s	remaining: 1m 53s
8608:	learn: 0.0016124	total: 14m 47s	remaining: 2m 23s
8204:	learn: 0.0013569	total: 14m 47s	remaining: 3m 14s
9031:	learn: 0.0014097	total: 14m 47s	remaining: 1m 35s
8871:	learn: 0.0014903	total: 14m 47s	remaining: 1m 52s
8870:	learn: 0.0013699	total: 14m 47s	remaining: 1m 52s
8609:	learn: 0.0016124	total: 14m 47s	remaining: 2m 23s
9032:	learn: 0.0014095	total: 14m 47s	remaining: 1m 35s
8205:	learn: 0.0013569	total: 14m 47s	remaining: 3m 14s
8872:	learn: 0.0014903	total: 14m 47s	remaining: 1m 52s
8871:	learn: 0.0013699	total: 14m 47s	remaining: 1m 52s
8610:	learn: 0.0016121	total: 14m 47s	remaining: 2m 23s
9033:	learn: 0.0014094	total: 14m 47s	remaining: 1m 34s
8873:	learn: 0.0014903	total: 14m 47s	remaining: 1m 52s
8206:	learn: 0.0013569	total: 14m 47s	remaining: 3m 13s
8611:	learn: 0.0016121	total: 14m 47s	remaining: 2m 23s
8872:	learn: 0.0013699	total: 14m 47s	remaining: 1m 52s
8874:	learn: 0.0014903	total: 14m 47s	remaining: 1m 52s
9034:	learn: 0.0014094	total: 14m 47s	remaining: 1m 34s
8207:	learn: 0.0013569	total: 14m 47s	remaining: 3m 13s
8873:	learn: 0.0013699	total: 14m 47s	remaining: 1m 52s
8612:	learn: 0.0016121	total: 14m 47s	remaining: 2m 22s
8875:	learn: 0.0014899	total: 14m 47s	remaining: 1m 52s
8208:	learn: 0.0013569	total: 14m 47s	remaining: 3m 13s
9035:	learn: 0.0014095	total: 14m 47s	remaining: 1m 34s
8613:	learn: 0.0016121	total: 14m 48s	remaining: 2m 22s
8874:	learn: 0.0013699	total: 14m 47s	remaining: 1m 52s
8876:	learn: 0.0014895	total: 14m 47s	remaining: 1m 52s
9036:	learn: 0.0014094	total: 14m 47s	remaining: 1m 34s
8209:	learn: 0.0013569	total: 14m 48s	remaining: 3m 13s
8875:	learn: 0.0013699	total: 14m 48s	remaining: 1m 52s
8614:	learn: 0.0016121	total: 14m 48s	remaining: 2m 22s
8877:	learn: 0.0014895	total: 14m 47s	remaining: 1m 52s
9037:	learn: 0.0014095	total: 14m 47s	remaining: 1m 34s
8615:	learn: 0.0016121	total: 14m 48s	remaining: 2m 22s
8210:	learn: 0.0013569	total: 14m 48s	remaining: 3m 13s
8876:	learn: 0.0013699	total: 14m 48s	remaining: 1m 52s
8878:	learn: 0.0014895	total: 14m 47s	remaining: 1m 52s
9038:	learn: 0.0014094	total: 14m 48s	remaining: 1m 34s
8616:	learn: 0.0016121	total: 14m 48s	remaining: 2m 22s
8877:	learn: 0.0013699	total: 14m 48s	remaining: 1m 52s
8879:	learn: 0.0014895	total: 14m 48s	remaining: 1m 52s
8211:	learn: 0.0013569	total: 14m 48s	remaining: 3m 13s
9039:	learn: 0.0014094	total: 14m 48s	remaining: 1m 34s
8617:	learn: 0.0016121	total: 14m 48s	remaining: 2m 22s
8880:	learn: 0.0014895	total: 14m 48s	remaining: 1m 51s
8878:	learn: 0.0013699	total: 14m 48s	remaining: 1m 52s
8212:	learn: 0.0013569	total: 14m 48s	remaining: 3m 13s
9040:	learn: 0.0014094	total: 14m 48s	remaining: 1m 34s
8618:	learn: 0.0016121	total: 14m 48s	remaining: 2m 22s
8881:	learn: 0.0014895	total: 14m 48s	remaining: 1m 51s
8879:	learn: 0.0013699	total: 14m 48s	remaining: 1m 52s
8213:	learn: 0.0013569	total: 14m 48s	remaining: 3m 13s
9041:	learn: 0.0014094	total: 14m 48s	remaining: 1m 34s
8619:	learn: 0.0016121	total: 14m 48s	remaining: 2m 22s
8882:	learn: 0.0014895	total: 14m 48s	remaining: 1m 51s
9042:	learn: 0.0014094	total: 14m 48s	remaining: 1m 34s

8214:	learn: 0.0013569	total: 14m 48s	remaining: 3m 13s
8880:	learn: 0.0013699	total: 14m 48s	remaining: 1m 51s
8620:	learn: 0.0016121	total: 14m 48s	remaining: 2m 22s
8883:	learn: 0.0014895	total: 14m 48s	remaining: 1m 51s
9043:	learn: 0.0014094	total: 14m 48s	remaining: 1m 33s
8621:	learn: 0.0016121	total: 14m 48s	remaining: 2m 22s
8215:	learn: 0.0013568	total: 14m 48s	remaining: 3m 12s
8881:	learn: 0.0013699	total: 14m 48s	remaining: 1m 51s
8884:	learn: 0.0014895	total: 14m 48s	remaining: 1m 51s
9044:	learn: 0.0014094	total: 14m 48s	remaining: 1m 33s
8216:	learn: 0.0013569	total: 14m 48s	remaining: 3m 12s
8622:	learn: 0.0016121	total: 14m 48s	remaining: 2m 21s
8885:	learn: 0.0014895	total: 14m 48s	remaining: 1m 51s
8882:	learn: 0.0013698	total: 14m 48s	remaining: 1m 51s
9045:	learn: 0.0014094	total: 14m 48s	remaining: 1m 33s
8217:	learn: 0.0013569	total: 14m 48s	remaining: 3m 12s
8886:	learn: 0.0014895	total: 14m 48s	remaining: 1m 51s
9046:	learn: 0.0014094	total: 14m 48s	remaining: 1m 33s
8623:	learn: 0.0016121	total: 14m 49s	remaining: 2m 21s
8883:	learn: 0.0013698	total: 14m 48s	remaining: 1m 51s
8887:	learn: 0.0014895	total: 14m 48s	remaining: 1m 51s
8624:	learn: 0.0016121	total: 14m 49s	remaining: 2m 21s
8218:	learn: 0.0013569	total: 14m 49s	remaining: 3m 12s
9047:	learn: 0.0014094	total: 14m 48s	remaining: 1m 33s
8884:	learn: 0.0013699	total: 14m 49s	remaining: 1m 51s
8625:	learn: 0.0016121	total: 14m 49s	remaining: 2m 21s
8888:	learn: 0.0014895	total: 14m 48s	remaining: 1m 51s
9048:	learn: 0.0014094	total: 14m 49s	remaining: 1m 33s
8219:	learn: 0.0013568	total: 14m 49s	remaining: 3m 12s
8626:	learn: 0.0016121	total: 14m 49s	remaining: 2m 21s
8885:	learn: 0.0013698	total: 14m 49s	remaining: 1m 51s
8889:	learn: 0.0014895	total: 14m 48s	remaining: 1m 51s
9049:	learn: 0.0014094	total: 14m 49s	remaining: 1m 33s
8220:	learn: 0.0013569	total: 14m 49s	remaining: 3m 12s
8886:	learn: 0.0013699	total: 14m 49s	remaining: 1m 51s
8890:	learn: 0.0014895	total: 14m 49s	remaining: 1m 50s
8627:	learn: 0.0016121	total: 14m 49s	remaining: 2m 21s
9050:	learn: 0.0014094	total: 14m 49s	remaining: 1m 33s
8221:	learn: 0.0013569	total: 14m 49s	remaining: 3m 12s
8887:	learn: 0.0013699	total: 14m 49s	remaining: 1m 51s
8628:	learn: 0.0016121	total: 14m 49s	remaining: 2m 21s
8891:	learn: 0.0014895	total: 14m 49s	remaining: 1m 50s
9051:	learn: 0.0014094	total: 14m 49s	remaining: 1m 33s
8888:	learn: 0.0013699	total: 14m 49s	remaining: 1m 51s
8222:	learn: 0.0013568	total: 14m 49s	remaining: 3m 12s
8629:	learn: 0.0016121	total: 14m 49s	remaining: 2m 21s
8892:	learn: 0.0014895	total: 14m 49s	remaining: 1m 50s
9052:	learn: 0.0014094	total: 14m 49s	remaining: 1m 33s
8223:	learn: 0.0013568	total: 14m 49s	remaining: 3m 12s
8889:	learn: 0.0013698	total: 14m 49s	remaining: 1m 51s
8630:	learn: 0.0016117	total: 14m 49s	remaining: 2m 21s
8893:	learn: 0.0014895	total: 14m 49s	remaining: 1m 50s
9053:	learn: 0.0014094	total: 14m 49s	remaining: 1m 32s
8224:	learn: 0.0013568	total: 14m 49s	remaining: 3m 12s
8890:	learn: 0.0013698	total: 14m 49s	remaining: 1m 50s
8894:	learn: 0.0014895	total: 14m 49s	remaining: 1m 50s
8631:	learn: 0.0016117	total: 14m 49s	remaining: 2m 21s
9054:	learn: 0.0014094	total: 14m 49s	remaining: 1m 32s
8225:	learn: 0.0013568	total: 14m 49s	remaining: 3m 11s
8891:	learn: 0.0013699	total: 14m 49s	remaining: 1m 50s
8895:	learn: 0.0014895	total: 14m 49s	remaining: 1m 50s
8632:	learn: 0.0016117	total: 14m 49s	remaining: 2m 20s
9055:	learn: 0.0014094	total: 14m 49s	remaining: 1m 32s
8892:	learn: 0.0013698	total: 14m 49s	remaining: 1m 50s
8226:	learn: 0.0013568	total: 14m 49s	remaining: 3m 11s
9056:	learn: 0.0014094	total: 14m 49s	remaining: 1m 32s
8896:	learn: 0.0014895	total: 14m 49s	remaining: 1m 50s
8633:	learn: 0.0016117	total: 14m 50s	remaining: 2m 20s
8893:	learn: 0.0013698	total: 14m 49s	remaining: 1m 50s
9057:	learn: 0.0014094	total: 14m 49s	remaining: 1m 32s
8227:	learn: 0.0013568	total: 14m 50s	remaining: 3m 11s
8634:	learn: 0.0016117	total: 14m 50s	remaining: 2m 20s
8897:	learn: 0.0014895	total: 14m 49s	remaining: 1m 50s
8228:	learn: 0.0013568	total: 14m 50s	remaining: 3m 11s
8894:	learn: 0.0013698	total: 14m 50s	remaining: 1m 50s
9058:	learn: 0.0014091	total: 14m 49s	remaining: 1m 32s
8635:	learn: 0.0016117	total: 14m 50s	remaining: 2m 20s
8898:	learn: 0.0014895	total: 14m 49s	remaining: 1m 50s
8895:	learn: 0.0013699	total: 14m 50s	remaining: 1m 50s
8229:	learn: 0.0013568	total: 14m 50s	remaining: 3m 11s
9059:	learn: 0.0014091	total: 14m 50s	remaining: 1m 32s
8899:	learn: 0.0014895	total: 14m 50s	remaining: 1m 50s
8636:	learn: 0.0016117	total: 14m 50s	remaining: 2m 20s
8900:	learn: 0.0014895	total: 14m 50s	remaining: 1m 49s
8896:	learn: 0.0013699	total: 14m 50s	remaining: 1m 50s
9060:	learn: 0.0014091	total: 14m 50s	remaining: 1m 32s
8230:	learn: 0.0013569	total: 14m 50s	remaining: 3m 11s
8637:	learn: 0.0016114	total: 14m 50s	remaining: 2m 20s
8901:	learn: 0.0014895	total: 14m 50s	remaining: 1m 49s
8897:	learn: 0.0013699	total: 14m 50s	remaining: 1m 50s
8638:	learn: 0.0016114	total: 14m 50s	remaining: 2m 20s
8231:	learn: 0.0013569	total: 14m 50s	remaining: 3m 11s
9061:	learn: 0.0014091	total: 14m 50s	remaining: 1m 32s
8902:	learn: 0.0014894	total: 14m 50s	remaining: 1m 49s
8898:	learn: 0.0013699	total: 14m 50s	remaining: 1m 50s
8639:	learn: 0.0016114	total: 14m 50s	remaining: 2m 20s
9062:	learn: 0.0014091	total: 14m 50s	remaining: 1m 32s
8232:	learn: 0.0013569	total: 14m 50s	remaining: 3m 11s
8899:	learn: 0.0013699	total: 14m 50s	remaining: 1m 50s
8903:	learn: 0.0014895	total: 14m 50s	remaining: 1m 49s
9063:	learn: 0.0014091	total: 14m 50s	remaining: 1m 31s
8233:	learn: 0.0013569	total: 14m 50s	remaining: 3m 11s
8640:	learn: 0.0016114	total: 14m 50s	remaining: 2m 20s
8904:	learn: 0.0014895	total: 14m 50s	remaining: 1m 49s
8900:	learn: 0.0013698	total: 14m 50s	remaining: 1m 49s
9064:	learn: 0.0014091	total: 14m 50s	remaining: 1m 31s
8641:	learn: 0.0016114	total: 14m 50s	remaining: 2m 19s
8234:	learn: 0.0013568	total: 14m 50s	remaining: 3m 10s
8901:	learn: 0.0013698	total: 14m 50s	remaining: 1m 49s
8905:	learn: 0.0014895	total: 14m 50s	remaining: 1m 49s
9065:	learn: 0.0014091	total: 14m 50s	remaining: 1m 31s
8642:	learn: 0.0016114	total: 14m 50s	remaining: 2m 19s
8235:	learn: 0.0013568	total: 14m 50s	remaining: 3m 10s
8902:	learn: 0.0013698	total: 14m 50s	remaining: 1m 49s
9066:	learn: 0.0014091	total: 14m 50s	remaining: 1m 31s
8906:	learn: 0.0014890	total: 14m 50s	remaining: 1m 49s
8236:	learn: 0.0013569	total: 14m 51s	remaining: 3m 10s
8643:	learn: 0.0016114	total: 14m 51s	remaining: 2m 19s
8903:	learn: 0.0013699	total: 14m 51s	remaining: 1m 49s
9067:	learn: 0.0014091	total: 14m 50s	remaining: 1m 31s
8237:	learn: 0.0013568	total: 14m 51s	remaining: 3m 10s
8907:	learn: 0.0014890	total: 14m 50s	remaining: 1m 49s
8644:	learn: 0.0016109	total: 14m 51s	remaining: 2m 19s
9068:	learn: 0.0014091	total: 14m 50s	remaining: 1m 31s
8904:	learn: 0.0013698	total: 14m 51s	remaining: 1m 49s
8238:	learn: 0.0013568	total: 14m 51s	remaining: 3m 10s
9069:	learn: 0.0014091	total: 14m 50s	remaining: 1m 31s
8908:	learn: 0.0014890	total: 14m 50s	remaining: 1m 49s
8645:	learn: 0.0016109	total: 14m 51s	remaining: 2m 19s
8905:	learn: 0.0013698	total: 14m 51s	remaining: 1m 49s
8239:	learn: 0.0013568	total: 14m 51s	remaining: 3m 10s
8646:	learn: 0.0016109	total: 14m 51s	remaining: 2m 19s
9070:	learn: 0.0014087	total: 14m 51s	remaining: 1m 31s
8909:	learn: 0.0014890	total: 14m 51s	remaining: 1m 49s
8906:	learn: 0.0013699	total: 14m 51s	remaining: 1m 49s
8240:	learn: 0.0013568	total: 14m 51s	remaining: 3m 10s
9071:	learn: 0.0014087	total: 14m 51s	remaining: 1m 31s
8647:	learn: 0.0016109	total: 14m 51s	remaining: 2m 19s
8907:	learn: 0.0013699	total: 14m 51s	remaining: 1m 49s
8910:	learn: 0.0014890	total: 14m 51s	remaining: 1m 48s
8241:	learn: 0.0013568	total: 14m 51s	remaining: 3m 10s
9072:	learn: 0.0014087	total: 14m 51s	remaining: 1m 31s
8908:	learn: 0.0013698	total: 14m 51s	remaining: 1m 49s
8648:	learn: 0.0016109	total: 14m 51s	remaining: 2m 19s
8911:	learn: 0.0014890	total: 14m 51s	remaining: 1m 48s
9073:	learn: 0.0014087	total: 14m 51s	remaining: 1m 30s
8242:	learn: 0.0013568	total: 14m 51s	remaining: 3m 10s
8912:	learn: 0.0014890	total: 14m 51s	remaining: 1m 48s
8909:	learn: 0.0013698	total: 14m 51s	remaining: 1m 49s
9074:	learn: 0.0014087	total: 14m 51s	remaining: 1m 30s
8649:	learn: 0.0016109	total: 14m 51s	remaining: 2m 19s
8243:	learn: 0.0013569	total: 14m 51s	remaining: 3m 9s
9075:	learn: 0.0014087	total: 14m 51s	remaining: 1m 30s
8913:	learn: 0.0014889	total: 14m 51s	remaining: 1m 48s
8910:	learn: 0.0013698	total: 14m 51s	remaining: 1m 48s
8650:	learn: 0.0016109	total: 14m 51s	remaining: 2m 19s
9076:	learn: 0.0014087	total: 14m 51s	remaining: 1m 30s
8914:	learn: 0.0014890	total: 14m 51s	remaining: 1m 48s
8244:	learn: 0.0013567	total: 14m 51s	remaining: 3m 9s
8911:	learn: 0.0013698	total: 14m 51s	remaining: 1m 48s
8651:	learn: 0.0016109	total: 14m 51s	remaining: 2m 18s
9077:	learn: 0.0014087	total: 14m 51s	remaining: 1m 30s
8912:	learn: 0.0013698	total: 14m 51s	remaining: 1m 48s
8245:	learn: 0.0013567	total: 14m 51s	remaining: 3m 9s
8915:	learn: 0.0014889	total: 14m 51s	remaining: 1m 48s
8652:	learn: 0.0016109	total: 14m 52s	remaining: 2m 18s
9078:	learn: 0.0014087	total: 14m 51s	remaining: 1m 30s
8913:	learn: 0.0013698	total: 14m 51s	remaining: 1m 48s
8246:	learn: 0.0013567	total: 14m 52s	remaining: 3m 9s
8916:	learn: 0.0014890	total: 14m 51s	remaining: 1m 48s
9079:	learn: 0.0014087	total: 14m 51s	remaining: 1m 30s
8653:	learn: 0.0016109	total: 14m 52s	remaining: 2m 18s
8914:	learn: 0.0013698	total: 14m 52s	remaining: 1m 48s
9080:	learn: 0.0014087	total: 14m 51s	remaining: 1m 30s
8247:	learn: 0.0013567	total: 14m 52s	remaining: 3m 9s
8917:	learn: 0.0014890	total: 14m 51s	remaining: 1m 48s
8654:	learn: 0.0016109	total: 14m 52s	remaining: 2m 18s
9081:	learn: 0.0014087	total: 14m 52s	remaining: 1m 30s
8915:	learn: 0.0013698	total: 14m 52s	remaining: 1m 48s
8655:	learn: 0.0016109	total: 14m 52s	remaining: 2m 18s
8248:	learn: 0.0013567	total: 14m 52s	remaining: 3m 9s
8918:	learn: 0.0014890	total: 14m 52s	remaining: 1m 48s
8916:	learn: 0.0013698	total: 14m 52s	remaining: 1m 48s
9082:	learn: 0.0014087	total: 14m 52s	remaining: 1m 30s
8249:	learn: 0.0013567	total: 14m 52s	remaining: 3m 9s
8656:	learn: 0.0016109	total: 14m 52s	remaining: 2m 18s
8919:	learn: 0.0014890	total: 14m 52s	remaining: 1m 48s
8917:	learn: 0.0013698	total: 14m 52s	remaining: 1m 48s
9083:	learn: 0.0014087	total: 14m 52s	remaining: 1m 29s
8657:	learn: 0.0016109	total: 14m 52s	remaining: 2m 18s
8250:	learn: 0.0013567	total: 14m 52s	remaining: 3m 9s
8920:	learn: 0.0014890	total: 14m 52s	remaining: 1m 47s
8918:	learn: 0.0013698	total: 14m 52s	remaining: 1m 48s
9084:	learn: 0.0014087	total: 14m 52s	remaining: 1m 29s
8658:	learn: 0.0016109	total: 14m 52s	remaining: 2m 18s
8251:	learn: 0.0013567	total: 14m 52s	remaining: 3m 9s
8921:	learn: 0.0014890	total: 14m 52s	remaining: 1m 47s
8919:	learn: 0.0013698	total: 14m 52s	remaining: 1m 48s
9085:	learn: 0.0014087	total: 14m 52s	remaining: 1m 29s
8659:	learn: 0.0016109	total: 14m 52s	remaining: 2m 18s
9086:	learn: 0.0014087	total: 14m 52s	remaining: 1m 29s
8252:	learn: 0.0013567	total: 14m 52s	remaining: 3m 8s
8922:	learn: 0.0014889	total: 14m 52s	remaining: 1m 47s
8920:	learn: 0.0013698	total: 14m 52s	remaining: 1m 47s
8660:	learn: 0.0016109	total: 14m 52s	remaining: 2m 18s
9087:	learn: 0.0014087	total: 14m 52s	remaining: 1m 29s
8921:	learn: 0.0013698	total: 14m 52s	remaining: 1m 47s
8923:	learn: 0.0014890	total: 14m 52s	remaining: 1m 47s
8253:	learn: 0.0013567	total: 14m 52s	remaining: 3m 8s
8661:	learn: 0.0016109	total: 14m 52s	remaining: 2m 17s
9088:	learn: 0.0014087	total: 14m 52s	remaining: 1m 29s
8922:	learn: 0.0013698	total: 14m 52s	remaining: 1m 47s
8924:	learn: 0.0014886	total: 14m 52s	remaining: 1m 47s
8254:	learn: 0.0013567	total: 14m 52s	remaining: 3m 8s
8662:	learn: 0.0016109	total: 14m 52s	remaining: 2m 17s
9089:	learn: 0.0014087	total: 14m 52s	remaining: 1m 29s
8923:	learn: 0.0013698	total: 14m 52s	remaining: 1m 47s
8925:	learn: 0.0014886	total: 14m 52s	remaining: 1m 47s
8663:	learn: 0.0016109	total: 14m 53s	remaining: 2m 17s
9090:	learn: 0.0014087	total: 14m 52s	remaining: 1m 29s
8255:	learn: 0.0013567	total: 14m 53s	remaining: 3m 8s
8924:	learn: 0.0013698	total: 14m 53s	remaining: 1m 47s
8926:	learn: 0.0014886	total: 14m 52s	remaining: 1m 47s
8664:	learn: 0.0016109	total: 14m 53s	remaining: 2m 17s
9091:	learn: 0.0014087	total: 14m 52s	remaining: 1m 29s
8256:	learn: 0.0013567	total: 14m 53s	remaining: 3m 8s
8925:	learn: 0.0013698	total: 14m 53s	remaining: 1m 47s
8927:	learn: 0.0014886	total: 14m 52s	remaining: 1m 47s
8665:	learn: 0.0016109	total: 14m 53s	remaining: 2m 17s
9092:	learn: 0.0014087	total: 14m 53s	remaining: 1m 29s
8926:	learn: 0.0013698	total: 14m 53s	remaining: 1m 47s
8257:	learn: 0.0013567	total: 14m 53s	remaining: 3m 8s
8928:	learn: 0.0014886	total: 14m 53s	remaining: 1m 47s
8666:	learn: 0.0016109	total: 14m 53s	remaining: 2m 17s
9093:	learn: 0.0014087	total: 14m 53s	remaining: 1m 28s
8927:	learn: 0.0013698	total: 14m 53s	remaining: 1m 47s
8258:	learn: 0.0013567	total: 14m 53s	remaining: 3m 8s
8929:	learn: 0.0014886	total: 14m 53s	remaining: 1m 47s
8667:	learn: 0.0016109	total: 14m 53s	remaining: 2m 17s
9094:	learn: 0.0014087	total: 14m 53s	remaining: 1m 28s
8930:	learn: 0.0014884	total: 14m 53s	remaining: 1m 46s
8928:	learn: 0.0013698	total: 14m 53s	remaining: 1m 47s
8259:	learn: 0.0013567	total: 14m 53s	remaining: 3m 8s
8668:	learn: 0.0016109	total: 14m 53s	remaining: 2m 17s
8929:	learn: 0.0013698	total: 14m 53s	remaining: 1m 47s
8931:	learn: 0.0014884	total: 14m 53s	remaining: 1m 46s
9095:	learn: 0.0014084	total: 14m 53s	remaining: 1m 28s
8669:	learn: 0.0016109	total: 14m 53s	remaining: 2m 17s
8260:	learn: 0.0013567	total: 14m 53s	remaining: 3m 8s
9096:	learn: 0.0014080	total: 14m 53s	remaining: 1m 28s
8932:	learn: 0.0014884	total: 14m 53s	remaining: 1m 46s
8930:	learn: 0.0013698	total: 14m 53s	remaining: 1m 46s
8670:	learn: 0.0016109	total: 14m 53s	remaining: 2m 16s
8261:	learn: 0.0013567	total: 14m 53s	remaining: 3m 8s
9097:	learn: 0.0014080	total: 14m 53s	remaining: 1m 28s
8933:	learn: 0.0014884	total: 14m 53s	remaining: 1m 46s
8931:	learn: 0.0013698	total: 14m 53s	remaining: 1m 46s
8671:	learn: 0.0016109	total: 14m 53s	remaining: 2m 16s
8934:	learn: 0.0014884	total: 14m 53s	remaining: 1m 46s
8262:	learn: 0.0013567	total: 14m 53s	remaining: 3m 7s
9098:	learn: 0.0014080	total: 14m 53s	remaining: 1m 28s
8672:	learn: 0.0016109	total: 14m 53s	remaining: 2m 16s
8263:	learn: 0.0013567	total: 14m 53s	remaining: 3m 7s
8932:	learn: 0.0013698	total: 14m 53s	remaining: 1m 46s
8935:	learn: 0.0014884	total: 14m 53s	remaining: 1m 46s
9099:	learn: 0.0014080	total: 14m 53s	remaining: 1m 28s
8673:	learn: 0.0016109	total: 14m 54s	remaining: 2m 16s
8264:	learn: 0.0013567	total: 14m 54s	remaining: 3m 7s
8933:	learn: 0.0013698	total: 14m 54s	remaining: 1m 46s
8936:	learn: 0.0014884	total: 14m 53s	remaining: 1m 46s
9100:	learn: 0.0014080	total: 14m 53s	remaining: 1m 28s
8674:	learn: 0.0016109	total: 14m 54s	remaining: 2m 16s
8265:	learn: 0.0013567	total: 14m 54s	remaining: 3m 7s
8937:	learn: 0.0014884	total: 14m 53s	remaining: 1m 46s
8934:	learn: 0.0013698	total: 14m 54s	remaining: 1m 46s
9101:	learn: 0.0014080	total: 14m 53s	remaining: 1m 28s
8938:	learn: 0.0014884	total: 14m 53s	remaining: 1m 46s
8675:	learn: 0.0016109	total: 14m 54s	remaining: 2m 16s
8266:	learn: 0.0013567	total: 14m 54s	remaining: 3m 7s
8935:	learn: 0.0013698	total: 14m 54s	remaining: 1m 46s
9102:	learn: 0.0014080	total: 14m 54s	remaining: 1m 28s
8267:	learn: 0.0013567	total: 14m 54s	remaining: 3m 7s
8939:	learn: 0.0014884	total: 14m 54s	remaining: 1m 46s
8676:	learn: 0.0016109	total: 14m 54s	remaining: 2m 16s
8936:	learn: 0.0013698	total: 14m 54s	remaining: 1m 46s
9103:	learn: 0.0014080	total: 14m 54s	remaining: 1m 28s
8940:	learn: 0.0014884	total: 14m 54s	remaining: 1m 45s
8268:	learn: 0.0013567	total: 14m 54s	remaining: 3m 7s
8937:	learn: 0.0013698	total: 14m 54s	remaining: 1m 46s
8677:	learn: 0.0016109	total: 14m 54s	remaining: 2m 16s
9104:	learn: 0.0014080	total: 14m 54s	remaining: 1m 27s
8941:	learn: 0.0014884	total: 14m 54s	remaining: 1m 45s

8938:	learn: 0.0013698	total: 14m 54s	remaining: 1m 46s
8269:	learn: 0.0013567	total: 14m 54s	remaining: 3m 7s
8678:	learn: 0.0016109	total: 14m 54s	remaining: 2m 16s
9105:	learn: 0.0014080	total: 14m 54s	remaining: 1m 27s
8942:	learn: 0.0014884	total: 14m 54s	remaining: 1m 45s
8939:	learn: 0.0013698	total: 14m 54s	remaining: 1m 46s
8270:	learn: 0.0013567	total: 14m 54s	remaining: 3m 7s
9106:	learn: 0.0014080	total: 14m 54s	remaining: 1m 27s
8679:	learn: 0.0016109	total: 14m 54s	remaining: 2m 16s
8940:	learn: 0.0013698	total: 14m 54s	remaining: 1m 45s
8943:	learn: 0.0014881	total: 14m 54s	remaining: 1m 45s
9107:	learn: 0.0014080	total: 14m 54s	remaining: 1m 27s
8271:	learn: 0.0013567	total: 14m 54s	remaining: 3m 6s
8941:	learn: 0.0013698	total: 14m 54s	remaining: 1m 45s
8680:	learn: 0.0016109	total: 14m 54s	remaining: 2m 15s
9108:	learn: 0.0014080	total: 14m 54s	remaining: 1m 27s
8944:	learn: 0.0014881	total: 14m 54s	remaining: 1m 45s
8272:	learn: 0.0013567	total: 14m 54s	remaining: 3m 6s
8681:	learn: 0.0016109	total: 14m 54s	remaining: 2m 15s
8942:	learn: 0.0013698	total: 14m 54s	remaining: 1m 45s
9109:	learn: 0.0014080	total: 14m 54s	remaining: 1m 27s
8945:	learn: 0.0014881	total: 14m 54s	remaining: 1m 45s
8273:	learn: 0.0013567	total: 14m 54s	remaining: 3m 6s
8682:	learn: 0.0016105	total: 14m 55s	remaining: 2m 15s
8943:	learn: 0.0013698	total: 14m 55s	remaining: 1m 45s
9110:	learn: 0.0014080	total: 14m 54s	remaining: 1m 27s
8946:	learn: 0.0014881	total: 14m 54s	remaining: 1m 45s
8274:	learn: 0.0013567	total: 14m 55s	remaining: 3m 6s
8683:	learn: 0.0016105	total: 14m 55s	remaining: 2m 15s
9111:	learn: 0.0014080	total: 14m 54s	remaining: 1m 27s
8944:	learn: 0.0013698	total: 14m 55s	remaining: 1m 45s
8947:	learn: 0.0014881	total: 14m 54s	remaining: 1m 45s
8275:	learn: 0.0013567	total: 14m 55s	remaining: 3m 6s
9112:	learn: 0.0014080	total: 14m 55s	remaining: 1m 27s
8945:	learn: 0.0013698	total: 14m 55s	remaining: 1m 45s
8684:	learn: 0.0016105	total: 14m 55s	remaining: 2m 15s
8276:	learn: 0.0013567	total: 14m 55s	remaining: 3m 6s
8948:	learn: 0.0014881	total: 14m 55s	remaining: 1m 45s
9113:	learn: 0.0014080	total: 14m 55s	remaining: 1m 27s
8946:	learn: 0.0013698	total: 14m 55s	remaining: 1m 45s
8685:	learn: 0.0016104	total: 14m 55s	remaining: 2m 15s
8277:	learn: 0.0013567	total: 14m 55s	remaining: 3m 6s
8949:	learn: 0.0014881	total: 14m 55s	remaining: 1m 45s
9114:	learn: 0.0014080	total: 14m 55s	remaining: 1m 26s
8278:	learn: 0.0013567	total: 14m 55s	remaining: 3m 6s
8686:	learn: 0.0016101	total: 14m 55s	remaining: 2m 15s
8947:	learn: 0.0013698	total: 14m 55s	remaining: 1m 45s
8950:	learn: 0.0014881	total: 14m 55s	remaining: 1m 44s
9115:	learn: 0.0014080	total: 14m 55s	remaining: 1m 26s
8279:	learn: 0.0013567	total: 14m 55s	remaining: 3m 6s
8687:	learn: 0.0016101	total: 14m 55s	remaining: 2m 15s
8948:	learn: 0.0013698	total: 14m 55s	remaining: 1m 45s
8951:	learn: 0.0014881	total: 14m 55s	remaining: 1m 44s
9116:	learn: 0.0014080	total: 14m 55s	remaining: 1m 26s
8688:	learn: 0.0016101	total: 14m 55s	remaining: 2m 15s
8280:	learn: 0.0013567	total: 14m 55s	remaining: 3m 5s
8949:	learn: 0.0013698	total: 14m 55s	remaining: 1m 45s
8952:	learn: 0.0014881	total: 14m 55s	remaining: 1m 44s
9117:	learn: 0.0014080	total: 14m 55s	remaining: 1m 26s
8689:	learn: 0.0016100	total: 14m 55s	remaining: 2m 15s
8281:	learn: 0.0013567	total: 14m 55s	remaining: 3m 5s
8950:	learn: 0.0013698	total: 14m 55s	remaining: 1m 44s
9118:	learn: 0.0014080	total: 14m 55s	remaining: 1m 26s
8953:	learn: 0.0014880	total: 14m 55s	remaining: 1m 44s
8690:	learn: 0.0016100	total: 14m 55s	remaining: 2m 14s
8951:	learn: 0.0013698	total: 14m 55s	remaining: 1m 44s
8282:	learn: 0.0013567	total: 14m 55s	remaining: 3m 5s
8954:	learn: 0.0014880	total: 14m 55s	remaining: 1m 44s
9119:	learn: 0.0014080	total: 14m 55s	remaining: 1m 26s
8691:	learn: 0.0016100	total: 14m 55s	remaining: 2m 14s
8952:	learn: 0.0013698	total: 14m 55s	remaining: 1m 44s
8283:	learn: 0.0013562	total: 14m 55s	remaining: 3m 5s
8955:	learn: 0.0014881	total: 14m 55s	remaining: 1m 44s
9120:	learn: 0.0014080	total: 14m 55s	remaining: 1m 26s
8692:	learn: 0.0016100	total: 14m 56s	remaining: 2m 14s
8953:	learn: 0.0013698	total: 14m 56s	remaining: 1m 44s
9121:	learn: 0.0014080	total: 14m 55s	remaining: 1m 26s
8956:	learn: 0.0014881	total: 14m 55s	remaining: 1m 44s
8284:	learn: 0.0013560	total: 14m 56s	remaining: 3m 5s
8954:	learn: 0.0013698	total: 14m 56s	remaining: 1m 44s
8693:	learn: 0.0016100	total: 14m 56s	remaining: 2m 14s
9122:	learn: 0.0014080	total: 14m 55s	remaining: 1m 26s
8955:	learn: 0.0013698	total: 14m 56s	remaining: 1m 44s
8957:	learn: 0.0014880	total: 14m 55s	remaining: 1m 44s
8285:	learn: 0.0013560	total: 14m 56s	remaining: 3m 5s
8694:	learn: 0.0016100	total: 14m 56s	remaining: 2m 14s
8956:	learn: 0.0013698	total: 14m 56s	remaining: 1m 44s
9123:	learn: 0.0014080	total: 14m 56s	remaining: 1m 26s
8958:	learn: 0.0014880	total: 14m 56s	remaining: 1m 44s
8695:	learn: 0.0016100	total: 14m 56s	remaining: 2m 14s
8957:	learn: 0.0013698	total: 14m 56s	remaining: 1m 44s
9124:	learn: 0.0014080	total: 14m 56s	remaining: 1m 25s
8286:	learn: 0.0013560	total: 14m 56s	remaining: 3m 5s
8959:	learn: 0.0014880	total: 14m 56s	remaining: 1m 44s
8696:	learn: 0.0016100	total: 14m 56s	remaining: 2m 14s
8958:	learn: 0.0013693	total: 14m 56s	remaining: 1m 44s
9125:	learn: 0.0014080	total: 14m 56s	remaining: 1m 25s
8960:	learn: 0.0014880	total: 14m 56s	remaining: 1m 43s
8287:	learn: 0.0013560	total: 14m 56s	remaining: 3m 5s
8697:	learn: 0.0016100	total: 14m 56s	remaining: 2m 14s
8959:	learn: 0.0013693	total: 14m 56s	remaining: 1m 44s
8961:	learn: 0.0014880	total: 14m 56s	remaining: 1m 43s
9126:	learn: 0.0014080	total: 14m 56s	remaining: 1m 25s
8960:	learn: 0.0013693	total: 14m 56s	remaining: 1m 43s
8698:	learn: 0.0016100	total: 14m 56s	remaining: 2m 14s
8288:	learn: 0.0013560	total: 14m 56s	remaining: 3m 5s
8962:	learn: 0.0014881	total: 14m 56s	remaining: 1m 43s
9127:	learn: 0.0014080	total: 14m 56s	remaining: 1m 25s
8961:	learn: 0.0013693	total: 14m 56s	remaining: 1m 43s
8699:	learn: 0.0016100	total: 14m 56s	remaining: 2m 14s
8289:	learn: 0.0013560	total: 14m 56s	remaining: 3m 4s
8963:	learn: 0.0014880	total: 14m 56s	remaining: 1m 43s
9128:	learn: 0.0014080	total: 14m 56s	remaining: 1m 25s
8962:	learn: 0.0013693	total: 14m 56s	remaining: 1m 43s
8700:	learn: 0.0016100	total: 14m 56s	remaining: 2m 13s
8290:	learn: 0.0013560	total: 14m 56s	remaining: 3m 4s
8964:	learn: 0.0014880	total: 14m 56s	remaining: 1m 43s
9129:	learn: 0.0014080	total: 14m 56s	remaining: 1m 25s
8963:	learn: 0.0013693	total: 14m 56s	remaining: 1m 43s
8701:	learn: 0.0016100	total: 14m 56s	remaining: 2m 13s
8291:	learn: 0.0013560	total: 14m 56s	remaining: 3m 4s
8965:	learn: 0.0014880	total: 14m 56s	remaining: 1m 43s
9130:	learn: 0.0014080	total: 14m 56s	remaining: 1m 25s
8964:	learn: 0.0013693	total: 14m 56s	remaining: 1m 43s
9131:	learn: 0.0014080	total: 14m 56s	remaining: 1m 25s
8966:	learn: 0.0014881	total: 14m 56s	remaining: 1m 43s
8702:	learn: 0.0016100	total: 14m 57s	remaining: 2m 13s
8292:	learn: 0.0013560	total: 14m 57s	remaining: 3m 4s
8965:	learn: 0.0013693	total: 14m 57s	remaining: 1m 43s
9132:	learn: 0.0014080	total: 14m 56s	remaining: 1m 25s
8967:	learn: 0.0014880	total: 14m 56s	remaining: 1m 43s
8703:	learn: 0.0016100	total: 14m 57s	remaining: 2m 13s
8293:	learn: 0.0013560	total: 14m 57s	remaining: 3m 4s
8968:	learn: 0.0014880	total: 14m 56s	remaining: 1m 43s
9133:	learn: 0.0014080	total: 14m 57s	remaining: 1m 25s
8966:	learn: 0.0013693	total: 14m 57s	remaining: 1m 43s
8704:	learn: 0.0016100	total: 14m 57s	remaining: 2m 13s
8294:	learn: 0.0013560	total: 14m 57s	remaining: 3m 4s
8969:	learn: 0.0014880	total: 14m 57s	remaining: 1m 43s
8967:	learn: 0.0013693	total: 14m 57s	remaining: 1m 43s
9134:	learn: 0.0014080	total: 14m 57s	remaining: 1m 24s
8705:	learn: 0.0016100	total: 14m 57s	remaining: 2m 13s
8295:	learn: 0.0013560	total: 14m 57s	remaining: 3m 4s
8970:	learn: 0.0014880	total: 14m 57s	remaining: 1m 42s
9135:	learn: 0.0014080	total: 14m 57s	remaining: 1m 24s
8968:	learn: 0.0013693	total: 14m 57s	remaining: 1m 43s
8706:	learn: 0.0016100	total: 14m 57s	remaining: 2m 13s
8296:	learn: 0.0013560	total: 14m 57s	remaining: 3m 4s
8971:	learn: 0.0014880	total: 14m 57s	remaining: 1m 42s
9136:	learn: 0.0014080	total: 14m 57s	remaining: 1m 24s
8969:	learn: 0.0013693	total: 14m 57s	remaining: 1m 43s
8707:	learn: 0.0016100	total: 14m 57s	remaining: 2m 13s
8297:	learn: 0.0013560	total: 14m 57s	remaining: 3m 4s
9137:	learn: 0.0014080	total: 14m 57s	remaining: 1m 24s
8972:	learn: 0.0014880	total: 14m 57s	remaining: 1m 42s
8970:	learn: 0.0013693	total: 14m 57s	remaining: 1m 42s
8708:	learn: 0.0016098	total: 14m 57s	remaining: 2m 13s
8298:	learn: 0.0013560	total: 14m 57s	remaining: 3m 4s
8971:	learn: 0.0013693	total: 14m 57s	remaining: 1m 42s
9138:	learn: 0.0014080	total: 14m 57s	remaining: 1m 24s
8973:	learn: 0.0014881	total: 14m 57s	remaining: 1m 42s
8709:	learn: 0.0016095	total: 14m 57s	remaining: 2m 12s
8299:	learn: 0.0013560	total: 14m 57s	remaining: 3m 3s
9139:	learn: 0.0014080	total: 14m 57s	remaining: 1m 24s
8972:	learn: 0.0013689	total: 14m 57s	remaining: 1m 42s
8974:	learn: 0.0014881	total: 14m 57s	remaining: 1m 42s
8300:	learn: 0.0013560	total: 14m 57s	remaining: 3m 3s
8710:	learn: 0.0016095	total: 14m 57s	remaining: 2m 12s
9140:	learn: 0.0014080	total: 14m 57s	remaining: 1m 24s
8973:	learn: 0.0013689	total: 14m 57s	remaining: 1m 42s
8975:	learn: 0.0014880	total: 14m 57s	remaining: 1m 42s
8711:	learn: 0.0016095	total: 14m 57s	remaining: 2m 12s
8301:	learn: 0.0013560	total: 14m 58s	remaining: 3m 3s
9141:	learn: 0.0014080	total: 14m 57s	remaining: 1m 24s
8974:	learn: 0.0013689	total: 14m 58s	remaining: 1m 42s
8976:	learn: 0.0014880	total: 14m 57s	remaining: 1m 42s
8712:	learn: 0.0016095	total: 14m 58s	remaining: 2m 12s
8302:	learn: 0.0013560	total: 14m 58s	remaining: 3m 3s
8975:	learn: 0.0013688	total: 14m 58s	remaining: 1m 42s
9142:	learn: 0.0014080	total: 14m 57s	remaining: 1m 24s
8713:	learn: 0.0016095	total: 14m 58s	remaining: 2m 12s
8977:	learn: 0.0014880	total: 14m 57s	remaining: 1m 42s
8976:	learn: 0.0013688	total: 14m 58s	remaining: 1m 42s
8303:	learn: 0.0013560	total: 14m 58s	remaining: 3m 3s
9143:	learn: 0.0014080	total: 14m 58s	remaining: 1m 24s
8978:	learn: 0.0014880	total: 14m 58s	remaining: 1m 42s
8714:	learn: 0.0016095	total: 14m 58s	remaining: 2m 12s
8977:	learn: 0.0013688	total: 14m 58s	remaining: 1m 42s
8304:	learn: 0.0013560	total: 14m 58s	remaining: 3m 3s
9144:	learn: 0.0014080	total: 14m 58s	remaining: 1m 23s
8979:	learn: 0.0014880	total: 14m 58s	remaining: 1m 42s
8715:	learn: 0.0016095	total: 14m 58s	remaining: 2m 12s
8978:	learn: 0.0013688	total: 14m 58s	remaining: 1m 42s
8305:	learn: 0.0013560	total: 14m 58s	remaining: 3m 3s
8980:	learn: 0.0014879	total: 14m 58s	remaining: 1m 41s
9145:	learn: 0.0014080	total: 14m 58s	remaining: 1m 23s
8716:	learn: 0.0016094	total: 14m 58s	remaining: 2m 12s
8979:	learn: 0.0013688	total: 14m 58s	remaining: 1m 42s
8981:	learn: 0.0014879	total: 14m 58s	remaining: 1m 41s
8306:	learn: 0.0013560	total: 14m 58s	remaining: 3m 3s
9146:	learn: 0.0014079	total: 14m 58s	remaining: 1m 23s
8717:	learn: 0.0016095	total: 14m 58s	remaining: 2m 12s
8980:	learn: 0.0013685	total: 14m 58s	remaining: 1m 41s
8982:	learn: 0.0014879	total: 14m 58s	remaining: 1m 41s
9147:	learn: 0.0014079	total: 14m 58s	remaining: 1m 23s
8307:	learn: 0.0013560	total: 14m 58s	remaining: 3m 3s
8718:	learn: 0.0016095	total: 14m 58s	remaining: 2m 12s
8981:	learn: 0.0013685	total: 14m 58s	remaining: 1m 41s
8983:	learn: 0.0014879	total: 14m 58s	remaining: 1m 41s
8308:	learn: 0.0013560	total: 14m 58s	remaining: 3m 2s
9148:	learn: 0.0014078	total: 14m 58s	remaining: 1m 23s
8719:	learn: 0.0016095	total: 14m 58s	remaining: 2m 11s
8982:	learn: 0.0013685	total: 14m 58s	remaining: 1m 41s
9149:	learn: 0.0014074	total: 14m 58s	remaining: 1m 23s
8309:	learn: 0.0013559	total: 14m 58s	remaining: 3m 2s
8984:	learn: 0.0014879	total: 14m 58s	remaining: 1m 41s
8720:	learn: 0.0016095	total: 14m 58s	remaining: 2m 11s
9150:	learn: 0.0014074	total: 14m 58s	remaining: 1m 23s
8983:	learn: 0.0013685	total: 14m 58s	remaining: 1m 41s
8310:	learn: 0.0013559	total: 14m 58s	remaining: 3m 2s
8985:	learn: 0.0014879	total: 14m 58s	remaining: 1m 41s
9151:	learn: 0.0014074	total: 14m 58s	remaining: 1m 23s
8721:	learn: 0.0016095	total: 14m 59s	remaining: 2m 11s
8311:	learn: 0.0013559	total: 14m 59s	remaining: 3m 2s
8984:	learn: 0.0013685	total: 14m 59s	remaining: 1m 41s
9152:	learn: 0.0014074	total: 14m 58s	remaining: 1m 23s
8986:	learn: 0.0014879	total: 14m 58s	remaining: 1m 41s
8722:	learn: 0.0016094	total: 14m 59s	remaining: 2m 11s
8985:	learn: 0.0013685	total: 14m 59s	remaining: 1m 41s
9153:	learn: 0.0014074	total: 14m 58s	remaining: 1m 23s
8312:	learn: 0.0013559	total: 14m 59s	remaining: 3m 2s
8987:	learn: 0.0014879	total: 14m 58s	remaining: 1m 41s
8723:	learn: 0.0016095	total: 14m 59s	remaining: 2m 11s
8986:	learn: 0.0013683	total: 14m 59s	remaining: 1m 41s
9154:	learn: 0.0014074	total: 14m 59s	remaining: 1m 22s
8313:	learn: 0.0013559	total: 14m 59s	remaining: 3m 2s
8988:	learn: 0.0014879	total: 14m 59s	remaining: 1m 41s
8724:	learn: 0.0016089	total: 14m 59s	remaining: 2m 11s
8989:	learn: 0.0014879	total: 14m 59s	remaining: 1m 41s
8987:	learn: 0.0013683	total: 14m 59s	remaining: 1m 41s
9155:	learn: 0.0014074	total: 14m 59s	remaining: 1m 22s
8314:	learn: 0.0013559	total: 14m 59s	remaining: 3m 2s
8725:	learn: 0.0016089	total: 14m 59s	remaining: 2m 11s
8990:	learn: 0.0014879	total: 14m 59s	remaining: 1m 40s
8988:	learn: 0.0013683	total: 14m 59s	remaining: 1m 41s
9156:	learn: 0.0014074	total: 14m 59s	remaining: 1m 22s
8315:	learn: 0.0013559	total: 14m 59s	remaining: 3m 2s
8991:	learn: 0.0014879	total: 14m 59s	remaining: 1m 40s
8726:	learn: 0.0016089	total: 14m 59s	remaining: 2m 11s
8989:	learn: 0.0013683	total: 14m 59s	remaining: 1m 41s
9157:	learn: 0.0014074	total: 14m 59s	remaining: 1m 22s
8316:	learn: 0.0013559	total: 14m 59s	remaining: 3m 2s
8992:	learn: 0.0014879	total: 14m 59s	remaining: 1m 40s
8990:	learn: 0.0013678	total: 14m 59s	remaining: 1m 40s
8727:	learn: 0.0016089	total: 14m 59s	remaining: 2m 11s
9158:	learn: 0.0014074	total: 14m 59s	remaining: 1m 22s
8993:	learn: 0.0014879	total: 14m 59s	remaining: 1m 40s
8728:	learn: 0.0016089	total: 14m 59s	remaining: 2m 11s
8317:	learn: 0.0013559	total: 14m 59s	remaining: 3m 1s
8991:	learn: 0.0013678	total: 14m 59s	remaining: 1m 40s
9159:	learn: 0.0014074	total: 14m 59s	remaining: 1m 22s
8729:	learn: 0.0016089	total: 14m 59s	remaining: 2m 10s
8994:	learn: 0.0014879	total: 14m 59s	remaining: 1m 40s
8318:	learn: 0.0013559	total: 14m 59s	remaining: 3m 1s
8992:	learn: 0.0013678	total: 14m 59s	remaining: 1m 40s
9160:	learn: 0.0014074	total: 14m 59s	remaining: 1m 22s
8730:	learn: 0.0016089	total: 14m 59s	remaining: 2m 10s
8995:	learn: 0.0014879	total: 14m 59s	remaining: 1m 40s
8319:	learn: 0.0013559	total: 14m 59s	remaining: 3m 1s
8993:	learn: 0.0013678	total: 14m 59s	remaining: 1m 40s
8731:	learn: 0.0016089	total: 14m 59s	remaining: 2m 10s
8996:	learn: 0.0014878	total: 14m 59s	remaining: 1m 40s
9161:	learn: 0.0014074	total: 14m 59s	remaining: 1m 22s
8994:	learn: 0.0013678	total: 15m	remaining: 1m 40s
8320:	learn: 0.0013559	total: 15m	remaining: 3m 1s
8997:	learn: 0.0014879	total: 14m 59s	remaining: 1m 40s
8732:	learn: 0.0016089	total: 15m	remaining: 2m 10s
9162:	learn: 0.0014074	total: 14m 59s	remaining: 1m 22s
8998:	learn: 0.0014879	total: 14m 59s	remaining: 1m 40s
8733:	learn: 0.0016089	total: 15m	remaining: 2m 10s
8995:	learn: 0.0013678	total: 15m	remaining: 1m 40s
8321:	learn: 0.0013559	total: 15m	remaining: 3m 1s
9163:	learn: 0.0014074	total: 15m	remaining: 1m 22s
8999:	learn: 0.0014879	total: 14m 59s	remaining: 1m 39s
8996:	learn: 0.0013678	total: 15m	remaining: 1m 40s
9164:	learn: 0.0014074	total: 15m	remaining: 1m 22s
8734:	learn: 0.0016089	total: 15m	remaining: 2m 10s
8322:	learn: 0.0013559	total: 15m	remaining: 3m 1s
8323:	learn: 0.0013559	total: 15m	remaining: 3m 1s
9165:	learn: 0.0014074	total: 15m	remaining: 1m 21s
9000:	learn: 0.0014879	total: 15m	remaining: 1m 39s
8997:	learn: 0.0013678	total: 15m	remaining: 1m 40s
8735:	learn: 0.0016089	total: 15m	remaining: 2m 10s
8324:	learn: 0.0013559	total: 15m	remaining: 3m 1s

9166:	learn: 0.0014073	total: 15m	remaining: 1m 21s
8736:	learn: 0.0016089	total: 15m	remaining: 2m 10s
8998:	learn: 0.0013678	total: 15m	remaining: 1m 40s
9001:	learn: 0.0014879	total: 15m	remaining: 1m 39s
8325:	learn: 0.0013559	total: 15m	remaining: 3m 1s
9167:	learn: 0.0014073	total: 15m	remaining: 1m 21s
8737:	learn: 0.0016089	total: 15m	remaining: 2m 10s
8999:	learn: 0.0013678	total: 15m	remaining: 1m 40s
9002:	learn: 0.0014879	total: 15m	remaining: 1m 39s
8326:	learn: 0.0013559	total: 15m	remaining: 3m
9168:	learn: 0.0014073	total: 15m	remaining: 1m 21s
9000:	learn: 0.0013678	total: 15m	remaining: 1m 39s
8738:	learn: 0.0016089	total: 15m	remaining: 2m 9s
9003:	learn: 0.0014879	total: 15m	remaining: 1m 39s
9001:	learn: 0.0013678	total: 15m	remaining: 1m 39s
8327:	learn: 0.0013559	total: 15m	remaining: 3m
9169:	learn: 0.0014073	total: 15m	remaining: 1m 21s
8739:	learn: 0.0016089	total: 15m	remaining: 2m 9s
8328:	learn: 0.0013559	total: 15m	remaining: 3m
9004:	learn: 0.0014879	total: 15m	remaining: 1m 39s
9002:	learn: 0.0013678	total: 15m	remaining: 1m 39s
8740:	learn: 0.0016089	total: 15m	remaining: 2m 9s
9170:	learn: 0.0014073	total: 15m	remaining: 1m 21s
8329:	learn: 0.0013559	total: 15m	remaining: 3m
8741:	learn: 0.0016089	total: 15m	remaining: 2m 9s
9005:	learn: 0.0014879	total: 15m	remaining: 1m 39s
9003:	learn: 0.0013678	total: 15m	remaining: 1m 39s
9171:	learn: 0.0014072	total: 15m	remaining: 1m 21s
8330:	learn: 0.0013559	total: 15m 1s	remaining: 3m
9006:	learn: 0.0014878	total: 15m	remaining: 1m 39s
9172:	learn: 0.0014067	total: 15m	remaining: 1m 21s
8742:	learn: 0.0016089	total: 15m 1s	remaining: 2m 9s
9004:	learn: 0.0013678	total: 15m 1s	remaining: 1m 39s
8331:	learn: 0.0013559	total: 15m 1s	remaining: 3m
9005:	learn: 0.0013678	total: 15m 1s	remaining: 1m 39s
8743:	learn: 0.0016089	total: 15m 1s	remaining: 2m 9s
9007:	learn: 0.0014879	total: 15m	remaining: 1m 39s
9173:	learn: 0.0014063	total: 15m 1s	remaining: 1m 21s
9006:	learn: 0.0013678	total: 15m 1s	remaining: 1m 39s
8332:	learn: 0.0013559	total: 15m 1s	remaining: 3m
9008:	learn: 0.0014879	total: 15m	remaining: 1m 39s
8744:	learn: 0.0016089	total: 15m 1s	remaining: 2m 9s
9174:	learn: 0.0014063	total: 15m 1s	remaining: 1m 21s
9007:	learn: 0.0013678	total: 15m 1s	remaining: 1m 39s
9009:	learn: 0.0014878	total: 15m 1s	remaining: 1m 39s
8333:	learn: 0.0013559	total: 15m 1s	remaining: 3m
8745:	learn: 0.0016089	total: 15m 1s	remaining: 2m 9s
9175:	learn: 0.0014063	total: 15m 1s	remaining: 1m 20s
9008:	learn: 0.0013678	total: 15m 1s	remaining: 1m 39s
8334:	learn: 0.0013559	total: 15m 1s	remaining: 3m
9010:	learn: 0.0014879	total: 15m 1s	remaining: 1m 38s
8746:	learn: 0.0016089	total: 15m 1s	remaining: 2m 9s
9009:	learn: 0.0013678	total: 15m 1s	remaining: 1m 39s
9176:	learn: 0.0014063	total: 15m 1s	remaining: 1m 20s
8335:	learn: 0.0013559	total: 15m 1s	remaining: 2m 59s
8747:	learn: 0.0016089	total: 15m 1s	remaining: 2m 9s
9010:	learn: 0.0013674	total: 15m 1s	remaining: 1m 38s
9177:	learn: 0.0014063	total: 15m 1s	remaining: 1m 20s
9011:	learn: 0.0014879	total: 15m 1s	remaining: 1m 38s
8336:	learn: 0.0013559	total: 15m 1s	remaining: 2m 59s
9011:	learn: 0.0013674	total: 15m 1s	remaining: 1m 38s
9012:	learn: 0.0014879	total: 15m 1s	remaining: 1m 38s
8748:	learn: 0.0016089	total: 15m 1s	remaining: 2m 8s
8337:	learn: 0.0013559	total: 15m 1s	remaining: 2m 59s
9178:	learn: 0.0014063	total: 15m 1s	remaining: 1m 20s
9013:	learn: 0.0014879	total: 15m 1s	remaining: 1m 38s
8749:	learn: 0.0016089	total: 15m 1s	remaining: 2m 8s
9012:	learn: 0.0013674	total: 15m 1s	remaining: 1m 38s
8338:	learn: 0.0013559	total: 15m 1s	remaining: 2m 59s
9179:	learn: 0.0014063	total: 15m 1s	remaining: 1m 20s
9014:	learn: 0.0014879	total: 15m 1s	remaining: 1m 38s
9013:	learn: 0.0013674	total: 15m 1s	remaining: 1m 38s
8750:	learn: 0.0016087	total: 15m 1s	remaining: 2m 8s
9015:	learn: 0.0014878	total: 15m 1s	remaining: 1m 38s
9180:	learn: 0.0014063	total: 15m 1s	remaining: 1m 20s
8339:	learn: 0.0013559	total: 15m 1s	remaining: 2m 59s
9014:	learn: 0.0013674	total: 15m 1s	remaining: 1m 38s
8751:	learn: 0.0016087	total: 15m 2s	remaining: 2m 8s
9016:	learn: 0.0014879	total: 15m 1s	remaining: 1m 38s
8340:	learn: 0.0013559	total: 15m 2s	remaining: 2m 59s
9181:	learn: 0.0014063	total: 15m 1s	remaining: 1m 20s
9015:	learn: 0.0013674	total: 15m 2s	remaining: 1m 38s
9017:	learn: 0.0014879	total: 15m 1s	remaining: 1m 38s
8752:	learn: 0.0016087	total: 15m 2s	remaining: 2m 8s
8341:	learn: 0.0013559	total: 15m 2s	remaining: 2m 59s
9182:	learn: 0.0014063	total: 15m 1s	remaining: 1m 20s
9016:	learn: 0.0013673	total: 15m 2s	remaining: 1m 38s
9018:	learn: 0.0014879	total: 15m 1s	remaining: 1m 38s
8753:	learn: 0.0016087	total: 15m 2s	remaining: 2m 8s
9183:	learn: 0.0014063	total: 15m 2s	remaining: 1m 20s
8342:	learn: 0.0013559	total: 15m 2s	remaining: 2m 59s
9017:	learn: 0.0013673	total: 15m 2s	remaining: 1m 38s
9019:	learn: 0.0014878	total: 15m 2s	remaining: 1m 38s
8754:	learn: 0.0016087	total: 15m 2s	remaining: 2m 8s
9184:	learn: 0.0014063	total: 15m 2s	remaining: 1m 20s
9018:	learn: 0.0013673	total: 15m 2s	remaining: 1m 38s
8343:	learn: 0.0013559	total: 15m 2s	remaining: 2m 59s
9020:	learn: 0.0014877	total: 15m 2s	remaining: 1m 37s
9185:	learn: 0.0014063	total: 15m 2s	remaining: 1m 19s
8755:	learn: 0.0016084	total: 15m 2s	remaining: 2m 8s
9019:	learn: 0.0013673	total: 15m 2s	remaining: 1m 38s
8344:	learn: 0.0013559	total: 15m 2s	remaining: 2m 58s
8756:	learn: 0.0016084	total: 15m 2s	remaining: 2m 8s
9186:	learn: 0.0014063	total: 15m 2s	remaining: 1m 19s
9021:	learn: 0.0014877	total: 15m 2s	remaining: 1m 37s
9020:	learn: 0.0013670	total: 15m 2s	remaining: 1m 37s
8757:	learn: 0.0016084	total: 15m 2s	remaining: 2m 8s
9187:	learn: 0.0014063	total: 15m 2s	remaining: 1m 19s
8345:	learn: 0.0013557	total: 15m 2s	remaining: 2m 58s
9022:	learn: 0.0014877	total: 15m 2s	remaining: 1m 37s
9021:	learn: 0.0013666	total: 15m 2s	remaining: 1m 37s
8758:	learn: 0.0016084	total: 15m 2s	remaining: 2m 7s
9188:	learn: 0.0014063	total: 15m 2s	remaining: 1m 19s
9022:	learn: 0.0013666	total: 15m 2s	remaining: 1m 37s
8346:	learn: 0.0013557	total: 15m 2s	remaining: 2m 58s
9023:	learn: 0.0014877	total: 15m 2s	remaining: 1m 37s
9189:	learn: 0.0014063	total: 15m 2s	remaining: 1m 19s
8759:	learn: 0.0016084	total: 15m 2s	remaining: 2m 7s
9023:	learn: 0.0013662	total: 15m 2s	remaining: 1m 37s
8347:	learn: 0.0013557	total: 15m 2s	remaining: 2m 58s
9024:	learn: 0.0014877	total: 15m 2s	remaining: 1m 37s
9190:	learn: 0.0014063	total: 15m 2s	remaining: 1m 19s
8760:	learn: 0.0016084	total: 15m 2s	remaining: 2m 7s
8348:	learn: 0.0013557	total: 15m 2s	remaining: 2m 58s
9024:	learn: 0.0013660	total: 15m 2s	remaining: 1m 37s
9191:	learn: 0.0014063	total: 15m 2s	remaining: 1m 19s
9025:	learn: 0.0014877	total: 15m 2s	remaining: 1m 37s
8761:	learn: 0.0016084	total: 15m 3s	remaining: 2m 7s
9025:	learn: 0.0013660	total: 15m 3s	remaining: 1m 37s
9026:	learn: 0.0014877	total: 15m 2s	remaining: 1m 37s
9192:	learn: 0.0014063	total: 15m 2s	remaining: 1m 19s
8349:	learn: 0.0013557	total: 15m 3s	remaining: 2m 58s
8762:	learn: 0.0016084	total: 15m 3s	remaining: 2m 7s
9193:	learn: 0.0014063	total: 15m 2s	remaining: 1m 19s
9027:	learn: 0.0014877	total: 15m 2s	remaining: 1m 37s
9026:	learn: 0.0013655	total: 15m 3s	remaining: 1m 37s
8350:	learn: 0.0013557	total: 15m 3s	remaining: 2m 58s
8763:	learn: 0.0016081	total: 15m 3s	remaining: 2m 7s
9028:	learn: 0.0014877	total: 15m 3s	remaining: 1m 37s
9194:	learn: 0.0014063	total: 15m 3s	remaining: 1m 19s
9027:	learn: 0.0013655	total: 15m 3s	remaining: 1m 37s
8351:	learn: 0.0013557	total: 15m 3s	remaining: 2m 58s
8764:	learn: 0.0016081	total: 15m 3s	remaining: 2m 7s
9195:	learn: 0.0014063	total: 15m 3s	remaining: 1m 18s
9028:	learn: 0.0013655	total: 15m 3s	remaining: 1m 37s
9029:	learn: 0.0014877	total: 15m 3s	remaining: 1m 37s
8352:	learn: 0.0013557	total: 15m 3s	remaining: 2m 58s
8765:	learn: 0.0016081	total: 15m 3s	remaining: 2m 7s
9196:	learn: 0.0014063	total: 15m 3s	remaining: 1m 18s
9029:	learn: 0.0013651	total: 15m 3s	remaining: 1m 37s
9030:	learn: 0.0014877	total: 15m 3s	remaining: 1m 36s
8353:	learn: 0.0013557	total: 15m 3s	remaining: 2m 58s
8766:	learn: 0.0016080	total: 15m 3s	remaining: 2m 7s
9197:	learn: 0.0014063	total: 15m 3s	remaining: 1m 18s
9031:	learn: 0.0014877	total: 15m 3s	remaining: 1m 36s
9030:	learn: 0.0013645	total: 15m 3s	remaining: 1m 36s
8354:	learn: 0.0013557	total: 15m 3s	remaining: 2m 57s
8767:	learn: 0.0016080	total: 15m 3s	remaining: 2m 6s
9032:	learn: 0.0014877	total: 15m 3s	remaining: 1m 36s
9198:	learn: 0.0014063	total: 15m 3s	remaining: 1m 18s
8355:	learn: 0.0013557	total: 15m 3s	remaining: 2m 57s
9031:	learn: 0.0013642	total: 15m 3s	remaining: 1m 36s
8768:	learn: 0.0016080	total: 15m 3s	remaining: 2m 6s
9033:	learn: 0.0014877	total: 15m 3s	remaining: 1m 36s
9199:	learn: 0.0014063	total: 15m 3s	remaining: 1m 18s
8356:	learn: 0.0013557	total: 15m 3s	remaining: 2m 57s
9032:	learn: 0.0013642	total: 15m 3s	remaining: 1m 36s
8769:	learn: 0.0016080	total: 15m 3s	remaining: 2m 6s
9034:	learn: 0.0014877	total: 15m 3s	remaining: 1m 36s
9200:	learn: 0.0014063	total: 15m 3s	remaining: 1m 18s
8357:	learn: 0.0013557	total: 15m 3s	remaining: 2m 57s
9033:	learn: 0.0013636	total: 15m 3s	remaining: 1m 36s
8770:	learn: 0.0016080	total: 15m 3s	remaining: 2m 6s
9035:	learn: 0.0014876	total: 15m 3s	remaining: 1m 36s
9201:	learn: 0.0014063	total: 15m 3s	remaining: 1m 18s
8358:	learn: 0.0013554	total: 15m 4s	remaining: 2m 57s
9034:	learn: 0.0013636	total: 15m 3s	remaining: 1m 36s
8771:	learn: 0.0016080	total: 15m 4s	remaining: 2m 6s
9202:	learn: 0.0014063	total: 15m 3s	remaining: 1m 18s
8359:	learn: 0.0013554	total: 15m 4s	remaining: 2m 57s
9036:	learn: 0.0014876	total: 15m 3s	remaining: 1m 36s
9035:	learn: 0.0013636	total: 15m 4s	remaining: 1m 36s
9203:	learn: 0.0014063	total: 15m 3s	remaining: 1m 18s
8772:	learn: 0.0016081	total: 15m 4s	remaining: 2m 6s
8360:	learn: 0.0013554	total: 15m 4s	remaining: 2m 57s
9037:	learn: 0.0014876	total: 15m 3s	remaining: 1m 36s
9204:	learn: 0.0014063	total: 15m 4s	remaining: 1m 18s
9036:	learn: 0.0013632	total: 15m 4s	remaining: 1m 36s
8773:	learn: 0.0016081	total: 15m 4s	remaining: 2m 6s
9038:	learn: 0.0014876	total: 15m 4s	remaining: 1m 36s
8361:	learn: 0.0013554	total: 15m 4s	remaining: 2m 57s
9205:	learn: 0.0014063	total: 15m 4s	remaining: 1m 17s
9037:	learn: 0.0013629	total: 15m 4s	remaining: 1m 36s
9039:	learn: 0.0014876	total: 15m 4s	remaining: 1m 36s
8774:	learn: 0.0016081	total: 15m 4s	remaining: 2m 6s
9206:	learn: 0.0014063	total: 15m 4s	remaining: 1m 17s
9038:	learn: 0.0013625	total: 15m 4s	remaining: 1m 36s
8362:	learn: 0.0013554	total: 15m 4s	remaining: 2m 57s
8775:	learn: 0.0016081	total: 15m 4s	remaining: 2m 6s
9040:	learn: 0.0014876	total: 15m 4s	remaining: 1m 35s
8363:	learn: 0.0013554	total: 15m 4s	remaining: 2m 56s
9207:	learn: 0.0014063	total: 15m 4s	remaining: 1m 17s
9039:	learn: 0.0013625	total: 15m 4s	remaining: 1m 36s
9041:	learn: 0.0014876	total: 15m 4s	remaining: 1m 35s
8776:	learn: 0.0016081	total: 15m 4s	remaining: 2m 6s
9208:	learn: 0.0014063	total: 15m 4s	remaining: 1m 17s
8364:	learn: 0.0013554	total: 15m 4s	remaining: 2m 56s
9040:	learn: 0.0013625	total: 15m 4s	remaining: 1m 35s
9209:	learn: 0.0014059	total: 15m 4s	remaining: 1m 17s
8777:	learn: 0.0016081	total: 15m 4s	remaining: 2m 5s
9042:	learn: 0.0014876	total: 15m 4s	remaining: 1m 35s
9041:	learn: 0.0013621	total: 15m 4s	remaining: 1m 35s
8365:	learn: 0.0013554	total: 15m 4s	remaining: 2m 56s
9210:	learn: 0.0014055	total: 15m 4s	remaining: 1m 17s
8778:	learn: 0.0016081	total: 15m 4s	remaining: 2m 5s
9043:	learn: 0.0014876	total: 15m 4s	remaining: 1m 35s
8366:	learn: 0.0013554	total: 15m 4s	remaining: 2m 56s
9042:	learn: 0.0013621	total: 15m 4s	remaining: 1m 35s
8779:	learn: 0.0016081	total: 15m 4s	remaining: 2m 5s
9211:	learn: 0.0014055	total: 15m 4s	remaining: 1m 17s
9044:	learn: 0.0014876	total: 15m 4s	remaining: 1m 35s
8367:	learn: 0.0013554	total: 15m 4s	remaining: 2m 56s
8780:	learn: 0.0016081	total: 15m 4s	remaining: 2m 5s
9043:	learn: 0.0013621	total: 15m 4s	remaining: 1m 35s
9212:	learn: 0.0014055	total: 15m 4s	remaining: 1m 17s
8368:	learn: 0.0013554	total: 15m 5s	remaining: 2m 56s
8781:	learn: 0.0016079	total: 15m 5s	remaining: 2m 5s
9045:	learn: 0.0014876	total: 15m 4s	remaining: 1m 35s
9044:	learn: 0.0013621	total: 15m 5s	remaining: 1m 35s
9213:	learn: 0.0014055	total: 15m 4s	remaining: 1m 17s
8782:	learn: 0.0016079	total: 15m 5s	remaining: 2m 5s
9046:	learn: 0.0014876	total: 15m 4s	remaining: 1m 35s
8369:	learn: 0.0013554	total: 15m 5s	remaining: 2m 56s
9214:	learn: 0.0014055	total: 15m 4s	remaining: 1m 17s
8783:	learn: 0.0016079	total: 15m 5s	remaining: 2m 5s
9045:	learn: 0.0013621	total: 15m 5s	remaining: 1m 35s
9047:	learn: 0.0014876	total: 15m 4s	remaining: 1m 35s
9215:	learn: 0.0014055	total: 15m 5s	remaining: 1m 16s
8370:	learn: 0.0013554	total: 15m 5s	remaining: 2m 56s
8784:	learn: 0.0016079	total: 15m 5s	remaining: 2m 5s
9046:	learn: 0.0013621	total: 15m 5s	remaining: 1m 35s
9216:	learn: 0.0014055	total: 15m 5s	remaining: 1m 16s
8371:	learn: 0.0013554	total: 15m 5s	remaining: 2m 56s
9048:	learn: 0.0014876	total: 15m 5s	remaining: 1m 35s
8785:	learn: 0.0016079	total: 15m 5s	remaining: 2m 5s
9047:	learn: 0.0013621	total: 15m 5s	remaining: 1m 35s
8372:	learn: 0.0013554	total: 15m 5s	remaining: 2m 55s
9217:	learn: 0.0014055	total: 15m 5s	remaining: 1m 16s
9049:	learn: 0.0014876	total: 15m 5s	remaining: 1m 35s
8786:	learn: 0.0016079	total: 15m 5s	remaining: 2m 5s
9048:	learn: 0.0013621	total: 15m 5s	remaining: 1m 35s
9218:	learn: 0.0014055	total: 15m 5s	remaining: 1m 16s
8373:	learn: 0.0013554	total: 15m 5s	remaining: 2m 55s
9050:	learn: 0.0014876	total: 15m 5s	remaining: 1m 34s
8787:	learn: 0.0016079	total: 15m 5s	remaining: 2m 4s
9049:	learn: 0.0013621	total: 15m 5s	remaining: 1m 35s
9219:	learn: 0.0014055	total: 15m 5s	remaining: 1m 16s
8374:	learn: 0.0013554	total: 15m 5s	remaining: 2m 55s
9051:	learn: 0.0014876	total: 15m 5s	remaining: 1m 34s
8788:	learn: 0.0016079	total: 15m 5s	remaining: 2m 4s
8375:	learn: 0.0013554	total: 15m 5s	remaining: 2m 55s
9050:	learn: 0.0013621	total: 15m 5s	remaining: 1m 34s
9220:	learn: 0.0014051	total: 15m 5s	remaining: 1m 16s
9052:	learn: 0.0014876	total: 15m 5s	remaining: 1m 34s
8789:	learn: 0.0016079	total: 15m 5s	remaining: 2m 4s
8376:	learn: 0.0013551	total: 15m 5s	remaining: 2m 55s
9221:	learn: 0.0014051	total: 15m 5s	remaining: 1m 16s
9053:	learn: 0.0014876	total: 15m 5s	remaining: 1m 34s
9051:	learn: 0.0013621	total: 15m 5s	remaining: 1m 34s
8790:	learn: 0.0016076	total: 15m 5s	remaining: 2m 4s
9222:	learn: 0.0014051	total: 15m 5s	remaining: 1m 16s
8377:	learn: 0.0013551	total: 15m 5s	remaining: 2m 55s
9052:	learn: 0.0013621	total: 15m 5s	remaining: 1m 34s
9054:	learn: 0.0014876	total: 15m 5s	remaining: 1m 34s
8791:	learn: 0.0016076	total: 15m 6s	remaining: 2m 4s
9223:	learn: 0.0014051	total: 15m 5s	remaining: 1m 16s
8378:	learn: 0.0013551	total: 15m 6s	remaining: 2m 55s
9055:	learn: 0.0014876	total: 15m 5s	remaining: 1m 34s
9053:	learn: 0.0013617	total: 15m 6s	remaining: 1m 34s
8792:	learn: 0.0016076	total: 15m 6s	remaining: 2m 4s
9224:	learn: 0.0014048	total: 15m 5s	remaining: 1m 16s
8379:	learn: 0.0013551	total: 15m 6s	remaining: 2m 55s
9054:	learn: 0.0013613	total: 15m 6s	remaining: 1m 34s
9056:	learn: 0.0014876	total: 15m 5s	remaining: 1m 34s
9225:	learn: 0.0014048	total: 15m 5s	remaining: 1m 16s
8793:	learn: 0.0016076	total: 15m 6s	remaining: 2m 4s
9226:	learn: 0.0014048	total: 15m 6s	remaining: 1m 15s
8380:	learn: 0.0013551	total: 15m 6s	remaining: 2m 55s
9057:	learn: 0.0014876	total: 15m 5s	remaining: 1m 34s
9055:	learn: 0.0013613	total: 15m 6s	remaining: 1m 34s
8794:	learn: 0.0016076	total: 15m 6s	remaining: 2m 4s
8381:	learn: 0.0013551	total: 15m 6s	remaining: 2m 54s
9227:	learn: 0.0014048	total: 15m 6s	remaining: 1m 15s
9056:	learn: 0.0013613	total: 15m 6s	remaining: 1m 34s
8795:	learn: 0.0016076	total: 15m 6s	remaining: 2m 4s
9058:	learn: 0.0014876	total: 15m 6s	remaining: 1m 34s
9228:	learn: 0.0014048	total: 15m 6s	remaining: 1m 15s
9057:	learn: 0.0013608	total: 15m 6s	remaining: 1m 34s
8382:	learn: 0.0013551	total: 15m 6s	remaining: 2m 54s
8796:	learn: 0.0016072	total: 15m 6s	remaining: 2m 3s

9059:	learn: 0.0014876	total: 15m 6s	remaining: 1m 34s
9058:	learn: 0.0013608	total: 15m 6s	remaining: 1m 34s
9229:	learn: 0.0014048	total: 15m 6s	remaining: 1m 15s
8383:	learn: 0.0013551	total: 15m 6s	remaining: 2m 54s
8797:	learn: 0.0016072	total: 15m 6s	remaining: 2m 3s
9060:	learn: 0.0014873	total: 15m 6s	remaining: 1m 33s
9059:	learn: 0.0013608	total: 15m 6s	remaining: 1m 34s
9230:	learn: 0.0014048	total: 15m 6s	remaining: 1m 15s
8384:	learn: 0.0013551	total: 15m 6s	remaining: 2m 54s
9061:	learn: 0.0014873	total: 15m 6s	remaining: 1m 33s
9060:	learn: 0.0013608	total: 15m 6s	remaining: 1m 33s
9231:	learn: 0.0014048	total: 15m 6s	remaining: 1m 15s
8798:	learn: 0.0016072	total: 15m 6s	remaining: 2m 3s
8385:	learn: 0.0013551	total: 15m 6s	remaining: 2m 54s
9062:	learn: 0.0014873	total: 15m 6s	remaining: 1m 33s
8799:	learn: 0.0016072	total: 15m 6s	remaining: 2m 3s
9232:	learn: 0.0014048	total: 15m 6s	remaining: 1m 15s
9063:	learn: 0.0014873	total: 15m 6s	remaining: 1m 33s
8386:	learn: 0.0013551	total: 15m 6s	remaining: 2m 54s
9061:	learn: 0.0013608	total: 15m 6s	remaining: 1m 33s
9233:	learn: 0.0014048	total: 15m 6s	remaining: 1m 15s
8800:	learn: 0.0016072	total: 15m 6s	remaining: 2m 3s
9064:	learn: 0.0014873	total: 15m 6s	remaining: 1m 33s
9062:	learn: 0.0013608	total: 15m 6s	remaining: 1m 33s
8387:	learn: 0.0013551	total: 15m 6s	remaining: 2m 54s
9234:	learn: 0.0014048	total: 15m 6s	remaining: 1m 15s
9065:	learn: 0.0014873	total: 15m 6s	remaining: 1m 33s
8801:	learn: 0.0016072	total: 15m 7s	remaining: 2m 3s
9063:	learn: 0.0013608	total: 15m 7s	remaining: 1m 33s
8388:	learn: 0.0013551	total: 15m 7s	remaining: 2m 54s
9235:	learn: 0.0014048	total: 15m 6s	remaining: 1m 15s
9066:	learn: 0.0014873	total: 15m 6s	remaining: 1m 33s
8802:	learn: 0.0016072	total: 15m 7s	remaining: 2m 3s
9064:	learn: 0.0013608	total: 15m 7s	remaining: 1m 33s
9236:	learn: 0.0014048	total: 15m 7s	remaining: 1m 14s
8389:	learn: 0.0013551	total: 15m 7s	remaining: 2m 54s
9067:	learn: 0.0014873	total: 15m 6s	remaining: 1m 33s
9065:	learn: 0.0013608	total: 15m 7s	remaining: 1m 33s
8803:	learn: 0.0016072	total: 15m 7s	remaining: 2m 3s
8390:	learn: 0.0013551	total: 15m 7s	remaining: 2m 53s
9237:	learn: 0.0014048	total: 15m 7s	remaining: 1m 14s
9068:	learn: 0.0014873	total: 15m 7s	remaining: 1m 33s
8804:	learn: 0.0016072	total: 15m 7s	remaining: 2m 3s
8391:	learn: 0.0013551	total: 15m 7s	remaining: 2m 53s
9066:	learn: 0.0013608	total: 15m 7s	remaining: 1m 33s
9238:	learn: 0.0014048	total: 15m 7s	remaining: 1m 14s
8805:	learn: 0.0016072	total: 15m 7s	remaining: 2m 3s
9069:	learn: 0.0014873	total: 15m 7s	remaining: 1m 33s
8392:	learn: 0.0013551	total: 15m 7s	remaining: 2m 53s
9239:	learn: 0.0014048	total: 15m 7s	remaining: 1m 14s
9067:	learn: 0.0013608	total: 15m 7s	remaining: 1m 33s
8806:	learn: 0.0016072	total: 15m 7s	remaining: 2m 2s
9070:	learn: 0.0014873	total: 15m 7s	remaining: 1m 32s
9068:	learn: 0.0013608	total: 15m 7s	remaining: 1m 33s
9240:	learn: 0.0014048	total: 15m 7s	remaining: 1m 14s
8393:	learn: 0.0013551	total: 15m 7s	remaining: 2m 53s
8807:	learn: 0.0016072	total: 15m 7s	remaining: 2m 2s
9069:	learn: 0.0013608	total: 15m 7s	remaining: 1m 33s
9071:	learn: 0.0014873	total: 15m 7s	remaining: 1m 32s
9241:	learn: 0.0014048	total: 15m 7s	remaining: 1m 14s
8808:	learn: 0.0016072	total: 15m 7s	remaining: 2m 2s
8394:	learn: 0.0013551	total: 15m 7s	remaining: 2m 53s
9070:	learn: 0.0013608	total: 15m 7s	remaining: 1m 32s
9072:	learn: 0.0014873	total: 15m 7s	remaining: 1m 32s
9242:	learn: 0.0014048	total: 15m 7s	remaining: 1m 14s
8809:	learn: 0.0016072	total: 15m 7s	remaining: 2m 2s
9071:	learn: 0.0013604	total: 15m 7s	remaining: 1m 32s
8395:	learn: 0.0013551	total: 15m 7s	remaining: 2m 53s
9073:	learn: 0.0014873	total: 15m 7s	remaining: 1m 32s
9243:	learn: 0.0014048	total: 15m 7s	remaining: 1m 14s
8810:	learn: 0.0016072	total: 15m 7s	remaining: 2m 2s
9072:	learn: 0.0013603	total: 15m 7s	remaining: 1m 32s
8396:	learn: 0.0013551	total: 15m 7s	remaining: 2m 53s
9074:	learn: 0.0014873	total: 15m 7s	remaining: 1m 32s
8811:	learn: 0.0016072	total: 15m 8s	remaining: 2m 2s
9244:	learn: 0.0014048	total: 15m 7s	remaining: 1m 14s
9073:	learn: 0.0013598	total: 15m 7s	remaining: 1m 32s
8397:	learn: 0.0013551	total: 15m 8s	remaining: 2m 53s
9075:	learn: 0.0014873	total: 15m 7s	remaining: 1m 32s
9245:	learn: 0.0014048	total: 15m 7s	remaining: 1m 14s
8812:	learn: 0.0016072	total: 15m 8s	remaining: 2m 2s
9074:	learn: 0.0013596	total: 15m 8s	remaining: 1m 32s
9076:	learn: 0.0014873	total: 15m 7s	remaining: 1m 32s
8398:	learn: 0.0013551	total: 15m 8s	remaining: 2m 53s
9246:	learn: 0.0014048	total: 15m 8s	remaining: 1m 13s
8813:	learn: 0.0016072	total: 15m 8s	remaining: 2m 2s
9075:	learn: 0.0013596	total: 15m 8s	remaining: 1m 32s
8399:	learn: 0.0013551	total: 15m 8s	remaining: 2m 53s
9077:	learn: 0.0014873	total: 15m 8s	remaining: 1m 32s
9247:	learn: 0.0014048	total: 15m 8s	remaining: 1m 13s
8814:	learn: 0.0016072	total: 15m 8s	remaining: 2m 2s
9076:	learn: 0.0013596	total: 15m 8s	remaining: 1m 32s
9078:	learn: 0.0014873	total: 15m 8s	remaining: 1m 32s
8400:	learn: 0.0013551	total: 15m 8s	remaining: 2m 52s
9248:	learn: 0.0014048	total: 15m 8s	remaining: 1m 13s
8815:	learn: 0.0016072	total: 15m 8s	remaining: 2m 2s
9077:	learn: 0.0013596	total: 15m 8s	remaining: 1m 32s
8401:	learn: 0.0013551	total: 15m 8s	remaining: 2m 52s
9079:	learn: 0.0014873	total: 15m 8s	remaining: 1m 32s
8816:	learn: 0.0016072	total: 15m 8s	remaining: 2m 1s
9249:	learn: 0.0014048	total: 15m 8s	remaining: 1m 13s
9078:	learn: 0.0013592	total: 15m 8s	remaining: 1m 32s
9080:	learn: 0.0014873	total: 15m 8s	remaining: 1m 31s
8817:	learn: 0.0016072	total: 15m 8s	remaining: 2m 1s
8402:	learn: 0.0013551	total: 15m 8s	remaining: 2m 52s
9079:	learn: 0.0013592	total: 15m 8s	remaining: 1m 32s
9081:	learn: 0.0014873	total: 15m 8s	remaining: 1m 31s
9250:	learn: 0.0014048	total: 15m 8s	remaining: 1m 13s
8818:	learn: 0.0016072	total: 15m 8s	remaining: 2m 1s
8403:	learn: 0.0013551	total: 15m 8s	remaining: 2m 52s
9080:	learn: 0.0013588	total: 15m 8s	remaining: 1m 31s
9251:	learn: 0.0014048	total: 15m 8s	remaining: 1m 13s
9082:	learn: 0.0014873	total: 15m 8s	remaining: 1m 31s
8819:	learn: 0.0016072	total: 15m 8s	remaining: 2m 1s
8404:	learn: 0.0013551	total: 15m 8s	remaining: 2m 52s
9252:	learn: 0.0014048	total: 15m 8s	remaining: 1m 13s
9083:	learn: 0.0014873	total: 15m 8s	remaining: 1m 31s
9081:	learn: 0.0013584	total: 15m 8s	remaining: 1m 31s
8820:	learn: 0.0016072	total: 15m 8s	remaining: 2m 1s
8405:	learn: 0.0013551	total: 15m 8s	remaining: 2m 52s
9082:	learn: 0.0013584	total: 15m 8s	remaining: 1m 31s
9084:	learn: 0.0014873	total: 15m 8s	remaining: 1m 31s
9253:	learn: 0.0014048	total: 15m 8s	remaining: 1m 13s
8821:	learn: 0.0016072	total: 15m 8s	remaining: 2m 1s
8406:	learn: 0.0013551	total: 15m 9s	remaining: 2m 52s
9254:	learn: 0.0014048	total: 15m 8s	remaining: 1m 13s
9083:	learn: 0.0013584	total: 15m 9s	remaining: 1m 31s
9085:	learn: 0.0014873	total: 15m 8s	remaining: 1m 31s
8822:	learn: 0.0016072	total: 15m 9s	remaining: 2m 1s
9255:	learn: 0.0014048	total: 15m 8s	remaining: 1m 13s
8407:	learn: 0.0013551	total: 15m 9s	remaining: 2m 52s
9086:	learn: 0.0014873	total: 15m 8s	remaining: 1m 31s
8823:	learn: 0.0016072	total: 15m 9s	remaining: 2m 1s
9084:	learn: 0.0013581	total: 15m 9s	remaining: 1m 31s
8408:	learn: 0.0013551	total: 15m 9s	remaining: 2m 52s
9256:	learn: 0.0014048	total: 15m 9s	remaining: 1m 12s
9087:	learn: 0.0014873	total: 15m 9s	remaining: 1m 31s
8824:	learn: 0.0016072	total: 15m 9s	remaining: 2m 1s
9085:	learn: 0.0013578	total: 15m 9s	remaining: 1m 31s
8409:	learn: 0.0013551	total: 15m 9s	remaining: 2m 51s
9257:	learn: 0.0014048	total: 15m 9s	remaining: 1m 12s
9088:	learn: 0.0014873	total: 15m 9s	remaining: 1m 31s
9086:	learn: 0.0013578	total: 15m 9s	remaining: 1m 31s
8825:	learn: 0.0016072	total: 15m 9s	remaining: 2m
8410:	learn: 0.0013551	total: 15m 9s	remaining: 2m 51s
9258:	learn: 0.0014048	total: 15m 9s	remaining: 1m 12s
9087:	learn: 0.0013578	total: 15m 9s	remaining: 1m 31s
9089:	learn: 0.0014873	total: 15m 9s	remaining: 1m 31s
8411:	learn: 0.0013551	total: 15m 9s	remaining: 2m 51s
8826:	learn: 0.0016072	total: 15m 9s	remaining: 2m
9259:	learn: 0.0014048	total: 15m 9s	remaining: 1m 12s
9090:	learn: 0.0014873	total: 15m 9s	remaining: 1m 30s
8412:	learn: 0.0013551	total: 15m 9s	remaining: 2m 51s
8827:	learn: 0.0016069	total: 15m 9s	remaining: 2m
9088:	learn: 0.0013574	total: 15m 9s	remaining: 1m 31s
9260:	learn: 0.0014046	total: 15m 9s	remaining: 1m 12s
9091:	learn: 0.0014873	total: 15m 9s	remaining: 1m 30s
9089:	learn: 0.0013574	total: 15m 9s	remaining: 1m 31s
8828:	learn: 0.0016069	total: 15m 9s	remaining: 2m
8413:	learn: 0.0013551	total: 15m 9s	remaining: 2m 51s
9261:	learn: 0.0014046	total: 15m 9s	remaining: 1m 12s
9090:	learn: 0.0013574	total: 15m 9s	remaining: 1m 30s
9092:	learn: 0.0014873	total: 15m 9s	remaining: 1m 30s
8829:	learn: 0.0016069	total: 15m 9s	remaining: 2m
9262:	learn: 0.0014046	total: 15m 9s	remaining: 1m 12s
9093:	learn: 0.0014873	total: 15m 9s	remaining: 1m 30s
8414:	learn: 0.0013551	total: 15m 9s	remaining: 2m 51s
9091:	learn: 0.0013574	total: 15m 9s	remaining: 1m 30s
9263:	learn: 0.0014046	total: 15m 9s	remaining: 1m 12s
8830:	learn: 0.0016069	total: 15m 9s	remaining: 2m
9094:	learn: 0.0014873	total: 15m 9s	remaining: 1m 30s
9092:	learn: 0.0013573	total: 15m 9s	remaining: 1m 30s
8415:	learn: 0.0013551	total: 15m 10s	remaining: 2m 51s
9095:	learn: 0.0014873	total: 15m 9s	remaining: 1m 30s
9093:	learn: 0.0013573	total: 15m 10s	remaining: 1m 30s
9264:	learn: 0.0014046	total: 15m 9s	remaining: 1m 12s
8831:	learn: 0.0016069	total: 15m 10s	remaining: 2m
8416:	learn: 0.0013551	total: 15m 10s	remaining: 2m 51s
9096:	learn: 0.0014873	total: 15m 9s	remaining: 1m 30s
9094:	learn: 0.0013573	total: 15m 10s	remaining: 1m 30s
9265:	learn: 0.0014046	total: 15m 9s	remaining: 1m 12s
9097:	learn: 0.0014873	total: 15m 9s	remaining: 1m 30s
8832:	learn: 0.0016069	total: 15m 10s	remaining: 2m
8417:	learn: 0.0013551	total: 15m 10s	remaining: 2m 51s
9095:	learn: 0.0013573	total: 15m 10s	remaining: 1m 30s
9266:	learn: 0.0014046	total: 15m 10s	remaining: 1m 11s
9098:	learn: 0.0014873	total: 15m 9s	remaining: 1m 30s
8833:	learn: 0.0016069	total: 15m 10s	remaining: 2m
8418:	learn: 0.0013551	total: 15m 10s	remaining: 2m 50s
9096:	learn: 0.0013573	total: 15m 10s	remaining: 1m 30s
9267:	learn: 0.0014046	total: 15m 10s	remaining: 1m 11s
9099:	learn: 0.0014873	total: 15m 10s	remaining: 1m 30s
8834:	learn: 0.0016065	total: 15m 10s	remaining: 2m
8419:	learn: 0.0013551	total: 15m 10s	remaining: 2m 50s
9097:	learn: 0.0013573	total: 15m 10s	remaining: 1m 30s
9268:	learn: 0.0014046	total: 15m 10s	remaining: 1m 11s
9100:	learn: 0.0014873	total: 15m 10s	remaining: 1m 29s
9098:	learn: 0.0013573	total: 15m 10s	remaining: 1m 30s
8420:	learn: 0.0013551	total: 15m 10s	remaining: 2m 50s
8835:	learn: 0.0016064	total: 15m 10s	remaining: 1m 59s
9269:	learn: 0.0014046	total: 15m 10s	remaining: 1m 11s
9101:	learn: 0.0014873	total: 15m 10s	remaining: 1m 29s
8421:	learn: 0.0013551	total: 15m 10s	remaining: 2m 50s
9102:	learn: 0.0014872	total: 15m 10s	remaining: 1m 29s
9270:	learn: 0.0014046	total: 15m 10s	remaining: 1m 11s
9099:	learn: 0.0013573	total: 15m 10s	remaining: 1m 30s
8836:	learn: 0.0016064	total: 15m 10s	remaining: 1m 59s
9103:	learn: 0.0014872	total: 15m 10s	remaining: 1m 29s
9271:	learn: 0.0014046	total: 15m 10s	remaining: 1m 11s
8422:	learn: 0.0013551	total: 15m 10s	remaining: 2m 50s
9100:	learn: 0.0013573	total: 15m 10s	remaining: 1m 29s
8837:	learn: 0.0016065	total: 15m 10s	remaining: 1m 59s
9104:	learn: 0.0014872	total: 15m 10s	remaining: 1m 29s
9272:	learn: 0.0014046	total: 15m 10s	remaining: 1m 11s
8423:	learn: 0.0013551	total: 15m 10s	remaining: 2m 50s
9101:	learn: 0.0013573	total: 15m 10s	remaining: 1m 29s
8838:	learn: 0.0016065	total: 15m 10s	remaining: 1m 59s
9105:	learn: 0.0014872	total: 15m 10s	remaining: 1m 29s
9273:	learn: 0.0014046	total: 15m 10s	remaining: 1m 11s
8424:	learn: 0.0013551	total: 15m 10s	remaining: 2m 50s
9102:	learn: 0.0013573	total: 15m 10s	remaining: 1m 29s
9106:	learn: 0.0014872	total: 15m 10s	remaining: 1m 29s
8839:	learn: 0.0016064	total: 15m 11s	remaining: 1m 59s
9274:	learn: 0.0014046	total: 15m 10s	remaining: 1m 11s
9103:	learn: 0.0013573	total: 15m 11s	remaining: 1m 29s
8425:	learn: 0.0013551	total: 15m 11s	remaining: 2m 50s
9107:	learn: 0.0014872	total: 15m 10s	remaining: 1m 29s
8840:	learn: 0.0016065	total: 15m 11s	remaining: 1m 59s
9275:	learn: 0.0014046	total: 15m 10s	remaining: 1m 11s
9104:	learn: 0.0013569	total: 15m 11s	remaining: 1m 29s
8426:	learn: 0.0013551	total: 15m 11s	remaining: 2m 50s
9108:	learn: 0.0014872	total: 15m 10s	remaining: 1m 29s
9276:	learn: 0.0014046	total: 15m 11s	remaining: 1m 11s
8841:	learn: 0.0016065	total: 15m 11s	remaining: 1m 59s
9105:	learn: 0.0013566	total: 15m 11s	remaining: 1m 29s
9109:	learn: 0.0014871	total: 15m 11s	remaining: 1m 29s
8427:	learn: 0.0013551	total: 15m 11s	remaining: 2m 49s
8842:	learn: 0.0016065	total: 15m 11s	remaining: 1m 59s
9277:	learn: 0.0014046	total: 15m 11s	remaining: 1m 10s
9110:	learn: 0.0014871	total: 15m 11s	remaining: 1m 28s
9106:	learn: 0.0013562	total: 15m 11s	remaining: 1m 29s
8428:	learn: 0.0013551	total: 15m 11s	remaining: 2m 49s
9278:	learn: 0.0014046	total: 15m 11s	remaining: 1m 10s
8843:	learn: 0.0016064	total: 15m 11s	remaining: 1m 59s
9111:	learn: 0.0014871	total: 15m 11s	remaining: 1m 28s
8429:	learn: 0.0013551	total: 15m 11s	remaining: 2m 49s
9107:	learn: 0.0013562	total: 15m 11s	remaining: 1m 29s
9279:	learn: 0.0014046	total: 15m 11s	remaining: 1m 10s
8844:	learn: 0.0016064	total: 15m 11s	remaining: 1m 59s
8430:	learn: 0.0013551	total: 15m 11s	remaining: 2m 49s
9112:	learn: 0.0014871	total: 15m 11s	remaining: 1m 28s
9108:	learn: 0.0013563	total: 15m 11s	remaining: 1m 29s
9280:	learn: 0.0014046	total: 15m 11s	remaining: 1m 10s
8845:	learn: 0.0016064	total: 15m 11s	remaining: 1m 58s
8431:	learn: 0.0013551	total: 15m 11s	remaining: 2m 49s
9113:	learn: 0.0014871	total: 15m 11s	remaining: 1m 28s
9109:	learn: 0.0013563	total: 15m 11s	remaining: 1m 29s
9281:	learn: 0.0014046	total: 15m 11s	remaining: 1m 10s
8432:	learn: 0.0013548	total: 15m 11s	remaining: 2m 49s
8846:	learn: 0.0016064	total: 15m 11s	remaining: 1m 58s
9114:	learn: 0.0014871	total: 15m 11s	remaining: 1m 28s
9110:	learn: 0.0013563	total: 15m 11s	remaining: 1m 28s
9282:	learn: 0.0014046	total: 15m 11s	remaining: 1m 10s
8433:	learn: 0.0013547	total: 15m 11s	remaining: 2m 49s
8847:	learn: 0.0016064	total: 15m 11s	remaining: 1m 58s
9111:	learn: 0.0013563	total: 15m 11s	remaining: 1m 28s
9115:	learn: 0.0014871	total: 15m 11s	remaining: 1m 28s
9283:	learn: 0.0014046	total: 15m 11s	remaining: 1m 10s
9112:	learn: 0.0013560	total: 15m 11s	remaining: 1m 28s
8434:	learn: 0.0013547	total: 15m 12s	remaining: 2m 49s
8848:	learn: 0.0016064	total: 15m 12s	remaining: 1m 58s
9284:	learn: 0.0014046	total: 15m 11s	remaining: 1m 10s
9116:	learn: 0.0014867	total: 15m 11s	remaining: 1m 28s
9113:	learn: 0.0013560	total: 15m 12s	remaining: 1m 28s
8849:	learn: 0.0016064	total: 15m 12s	remaining: 1m 58s
8435:	learn: 0.0013548	total: 15m 12s	remaining: 2m 49s
9117:	learn: 0.0014867	total: 15m 11s	remaining: 1m 28s
9285:	learn: 0.0014042	total: 15m 12s	remaining: 1m 10s
9114:	learn: 0.0013560	total: 15m 12s	remaining: 1m 28s
8850:	learn: 0.0016064	total: 15m 12s	remaining: 1m 58s
8436:	learn: 0.0013547	total: 15m 12s	remaining: 2m 48s
9118:	learn: 0.0014867	total: 15m 12s	remaining: 1m 28s
9286:	learn: 0.0014039	total: 15m 12s	remaining: 1m 10s
9115:	learn: 0.0013560	total: 15m 12s	remaining: 1m 28s
8437:	learn: 0.0013547	total: 15m 12s	remaining: 2m 48s
8851:	learn: 0.0016058	total: 15m 12s	remaining: 1m 58s
9119:	learn: 0.0014867	total: 15m 12s	remaining: 1m 28s
9287:	learn: 0.0014039	total: 15m 12s	remaining: 1m 9s
9116:	learn: 0.0013560	total: 15m 12s	remaining: 1m 28s
8438:	learn: 0.0013548	total: 15m 12s	remaining: 2m 48s
9120:	learn: 0.0014867	total: 15m 12s	remaining: 1m 27s
8852:	learn: 0.0016058	total: 15m 12s	remaining: 1m 58s
9288:	learn: 0.0014039	total: 15m 12s	remaining: 1m 9s
8853:	learn: 0.0016058	total: 15m 12s	remaining: 1m 58s
8439:	learn: 0.0013548	total: 15m 12s	remaining: 2m 48s
9117:	learn: 0.0013560	total: 15m 12s	remaining: 1m 28s

9121:	learn: 0.0014867	total: 15m 12s	remaining: 1m 27s
9289:	learn: 0.0014039	total: 15m 12s	remaining: 1m 9s
9118:	learn: 0.0013560	total: 15m 12s	remaining: 1m 28s
8440:	learn: 0.0013547	total: 15m 12s	remaining: 2m 48s
8854:	learn: 0.0016058	total: 15m 12s	remaining: 1m 58s
9122:	learn: 0.0014867	total: 15m 12s	remaining: 1m 27s
9290:	learn: 0.0014039	total: 15m 12s	remaining: 1m 9s
8441:	learn: 0.0013544	total: 15m 12s	remaining: 2m 48s
9119:	learn: 0.0013560	total: 15m 12s	remaining: 1m 28s
8855:	learn: 0.0016058	total: 15m 12s	remaining: 1m 57s
9123:	learn: 0.0014867	total: 15m 12s	remaining: 1m 27s
9291:	learn: 0.0014039	total: 15m 12s	remaining: 1m 9s
9120:	learn: 0.0013560	total: 15m 12s	remaining: 1m 27s
8442:	learn: 0.0013544	total: 15m 12s	remaining: 2m 48s
8856:	learn: 0.0016058	total: 15m 12s	remaining: 1m 57s
9124:	learn: 0.0014867	total: 15m 12s	remaining: 1m 27s
9292:	learn: 0.0014039	total: 15m 12s	remaining: 1m 9s
8443:	learn: 0.0013544	total: 15m 12s	remaining: 2m 48s
8857:	learn: 0.0016058	total: 15m 12s	remaining: 1m 57s
9121:	learn: 0.0013560	total: 15m 12s	remaining: 1m 27s
9293:	learn: 0.0014039	total: 15m 12s	remaining: 1m 9s
9125:	learn: 0.0014867	total: 15m 12s	remaining: 1m 27s
9294:	learn: 0.0014039	total: 15m 12s	remaining: 1m 9s
8444:	learn: 0.0013544	total: 15m 13s	remaining: 2m 48s
8858:	learn: 0.0016058	total: 15m 13s	remaining: 1m 57s
9122:	learn: 0.0013560	total: 15m 13s	remaining: 1m 27s
9126:	learn: 0.0014867	total: 15m 12s	remaining: 1m 27s
9295:	learn: 0.0014039	total: 15m 12s	remaining: 1m 9s
8445:	learn: 0.0013544	total: 15m 13s	remaining: 2m 48s
8859:	learn: 0.0016058	total: 15m 13s	remaining: 1m 57s
9127:	learn: 0.0014867	total: 15m 12s	remaining: 1m 27s
9123:	learn: 0.0013560	total: 15m 13s	remaining: 1m 27s
9296:	learn: 0.0014039	total: 15m 12s	remaining: 1m 9s
8446:	learn: 0.0013544	total: 15m 13s	remaining: 2m 47s
9297:	learn: 0.0014036	total: 15m 13s	remaining: 1m 8s
9128:	learn: 0.0014867	total: 15m 12s	remaining: 1m 27s
8860:	learn: 0.0016058	total: 15m 13s	remaining: 1m 57s
9124:	learn: 0.0013560	total: 15m 13s	remaining: 1m 27s
8447:	learn: 0.0013544	total: 15m 13s	remaining: 2m 47s
9298:	learn: 0.0014036	total: 15m 13s	remaining: 1m 8s
9129:	learn: 0.0014867	total: 15m 13s	remaining: 1m 27s
8861:	learn: 0.0016058	total: 15m 13s	remaining: 1m 57s
9125:	learn: 0.0013556	total: 15m 13s	remaining: 1m 27s
9299:	learn: 0.0014036	total: 15m 13s	remaining: 1m 8s
8448:	learn: 0.0013544	total: 15m 13s	remaining: 2m 47s
9130:	learn: 0.0014867	total: 15m 13s	remaining: 1m 26s
8862:	learn: 0.0016058	total: 15m 13s	remaining: 1m 57s
9126:	learn: 0.0013552	total: 15m 13s	remaining: 1m 27s
9300:	learn: 0.0014036	total: 15m 13s	remaining: 1m 8s
8449:	learn: 0.0013544	total: 15m 13s	remaining: 2m 47s
9131:	learn: 0.0014867	total: 15m 13s	remaining: 1m 26s
8863:	learn: 0.0016058	total: 15m 13s	remaining: 1m 57s
9301:	learn: 0.0014036	total: 15m 13s	remaining: 1m 8s
9127:	learn: 0.0013548	total: 15m 13s	remaining: 1m 27s
9132:	learn: 0.0014867	total: 15m 13s	remaining: 1m 26s
8450:	learn: 0.0013544	total: 15m 13s	remaining: 2m 47s
9302:	learn: 0.0014036	total: 15m 13s	remaining: 1m 8s
8864:	learn: 0.0016058	total: 15m 13s	remaining: 1m 56s
9128:	learn: 0.0013543	total: 15m 13s	remaining: 1m 27s
9133:	learn: 0.0014867	total: 15m 13s	remaining: 1m 26s
9303:	learn: 0.0014036	total: 15m 13s	remaining: 1m 8s
8865:	learn: 0.0016058	total: 15m 13s	remaining: 1m 56s
8451:	learn: 0.0013544	total: 15m 13s	remaining: 2m 47s
9129:	learn: 0.0013540	total: 15m 13s	remaining: 1m 27s
9134:	learn: 0.0014867	total: 15m 13s	remaining: 1m 26s
9304:	learn: 0.0014033	total: 15m 13s	remaining: 1m 8s
8866:	learn: 0.0016058	total: 15m 13s	remaining: 1m 56s
8452:	learn: 0.0013544	total: 15m 13s	remaining: 2m 47s
9130:	learn: 0.0013540	total: 15m 13s	remaining: 1m 26s
9135:	learn: 0.0014867	total: 15m 13s	remaining: 1m 26s
9305:	learn: 0.0014029	total: 15m 13s	remaining: 1m 8s
8867:	learn: 0.0016058	total: 15m 13s	remaining: 1m 56s
9131:	learn: 0.0013539	total: 15m 14s	remaining: 1m 26s
9306:	learn: 0.0014024	total: 15m 13s	remaining: 1m 8s
8453:	learn: 0.0013544	total: 15m 14s	remaining: 2m 47s
9136:	learn: 0.0014861	total: 15m 13s	remaining: 1m 26s
8868:	learn: 0.0016058	total: 15m 14s	remaining: 1m 56s
9307:	learn: 0.0014024	total: 15m 13s	remaining: 1m 7s
9137:	learn: 0.0014858	total: 15m 13s	remaining: 1m 26s
9132:	learn: 0.0013535	total: 15m 14s	remaining: 1m 26s
8869:	learn: 0.0016058	total: 15m 14s	remaining: 1m 56s
8454:	learn: 0.0013544	total: 15m 14s	remaining: 2m 47s
8870:	learn: 0.0016058	total: 15m 14s	remaining: 1m 56s
9308:	learn: 0.0014024	total: 15m 14s	remaining: 1m 7s
9133:	learn: 0.0013532	total: 15m 14s	remaining: 1m 26s
9138:	learn: 0.0014858	total: 15m 13s	remaining: 1m 26s
8455:	learn: 0.0013544	total: 15m 14s	remaining: 2m 46s
9309:	learn: 0.0014024	total: 15m 14s	remaining: 1m 7s
8871:	learn: 0.0016055	total: 15m 14s	remaining: 1m 56s
9139:	learn: 0.0014858	total: 15m 14s	remaining: 1m 26s
9134:	learn: 0.0013527	total: 15m 14s	remaining: 1m 26s
8456:	learn: 0.0013544	total: 15m 14s	remaining: 2m 46s
9310:	learn: 0.0014024	total: 15m 14s	remaining: 1m 7s
9135:	learn: 0.0013523	total: 15m 14s	remaining: 1m 26s
9140:	learn: 0.0014858	total: 15m 14s	remaining: 1m 25s
8872:	learn: 0.0016055	total: 15m 14s	remaining: 1m 56s
9311:	learn: 0.0014024	total: 15m 14s	remaining: 1m 7s
8457:	learn: 0.0013544	total: 15m 14s	remaining: 2m 46s
9136:	learn: 0.0013523	total: 15m 14s	remaining: 1m 26s
8873:	learn: 0.0016055	total: 15m 14s	remaining: 1m 56s
9312:	learn: 0.0014024	total: 15m 14s	remaining: 1m 7s
9141:	learn: 0.0014858	total: 15m 14s	remaining: 1m 25s
8458:	learn: 0.0013544	total: 15m 14s	remaining: 2m 46s
8874:	learn: 0.0016055	total: 15m 14s	remaining: 1m 55s
9137:	learn: 0.0013521	total: 15m 14s	remaining: 1m 26s
9142:	learn: 0.0014858	total: 15m 14s	remaining: 1m 25s
9313:	learn: 0.0014024	total: 15m 14s	remaining: 1m 7s
8459:	learn: 0.0013544	total: 15m 14s	remaining: 2m 46s
9138:	learn: 0.0013517	total: 15m 14s	remaining: 1m 26s
8875:	learn: 0.0016055	total: 15m 14s	remaining: 1m 55s
9143:	learn: 0.0014858	total: 15m 14s	remaining: 1m 25s
9314:	learn: 0.0014024	total: 15m 14s	remaining: 1m 7s
9139:	learn: 0.0013517	total: 15m 14s	remaining: 1m 26s
8460:	learn: 0.0013544	total: 15m 14s	remaining: 2m 46s
8876:	learn: 0.0016055	total: 15m 14s	remaining: 1m 55s
9144:	learn: 0.0014858	total: 15m 14s	remaining: 1m 25s
9315:	learn: 0.0014024	total: 15m 14s	remaining: 1m 7s
9140:	learn: 0.0013517	total: 15m 14s	remaining: 1m 25s
8461:	learn: 0.0013544	total: 15m 14s	remaining: 2m 46s
8877:	learn: 0.0016055	total: 15m 14s	remaining: 1m 55s
9145:	learn: 0.0014858	total: 15m 14s	remaining: 1m 25s
9316:	learn: 0.0014024	total: 15m 14s	remaining: 1m 7s
9141:	learn: 0.0013517	total: 15m 14s	remaining: 1m 25s
8462:	learn: 0.0013544	total: 15m 15s	remaining: 2m 46s
9317:	learn: 0.0014024	total: 15m 14s	remaining: 1m 6s
8878:	learn: 0.0016055	total: 15m 15s	remaining: 1m 55s
9146:	learn: 0.0014858	total: 15m 14s	remaining: 1m 25s
9142:	learn: 0.0013517	total: 15m 15s	remaining: 1m 25s
8879:	learn: 0.0016055	total: 15m 15s	remaining: 1m 55s
8463:	learn: 0.0013544	total: 15m 15s	remaining: 2m 46s
9318:	learn: 0.0014024	total: 15m 14s	remaining: 1m 6s
9147:	learn: 0.0014858	total: 15m 14s	remaining: 1m 25s
8880:	learn: 0.0016055	total: 15m 15s	remaining: 1m 55s
9143:	learn: 0.0013517	total: 15m 15s	remaining: 1m 25s
9319:	learn: 0.0014024	total: 15m 15s	remaining: 1m 6s
9148:	learn: 0.0014858	total: 15m 15s	remaining: 1m 25s
8464:	learn: 0.0013544	total: 15m 15s	remaining: 2m 45s
9320:	learn: 0.0014024	total: 15m 15s	remaining: 1m 6s
9144:	learn: 0.0013517	total: 15m 15s	remaining: 1m 25s
8881:	learn: 0.0016055	total: 15m 15s	remaining: 1m 55s
9321:	learn: 0.0014024	total: 15m 15s	remaining: 1m 6s
8465:	learn: 0.0013544	total: 15m 15s	remaining: 2m 45s
9149:	learn: 0.0014858	total: 15m 15s	remaining: 1m 25s
9145:	learn: 0.0013517	total: 15m 15s	remaining: 1m 25s
8882:	learn: 0.0016054	total: 15m 15s	remaining: 1m 55s
9322:	learn: 0.0014024	total: 15m 15s	remaining: 1m 6s
9146:	learn: 0.0013517	total: 15m 15s	remaining: 1m 25s
9150:	learn: 0.0014858	total: 15m 15s	remaining: 1m 24s
8466:	learn: 0.0013544	total: 15m 15s	remaining: 2m 45s
8883:	learn: 0.0016054	total: 15m 15s	remaining: 1m 55s
9323:	learn: 0.0014024	total: 15m 15s	remaining: 1m 6s
9324:	learn: 0.0014024	total: 15m 15s	remaining: 1m 6s
9147:	learn: 0.0013514	total: 15m 15s	remaining: 1m 25s
8467:	learn: 0.0013544	total: 15m 15s	remaining: 2m 45s
9151:	learn: 0.0014858	total: 15m 15s	remaining: 1m 24s
8884:	learn: 0.0016054	total: 15m 15s	remaining: 1m 54s
9325:	learn: 0.0014024	total: 15m 15s	remaining: 1m 6s
9152:	learn: 0.0014858	total: 15m 15s	remaining: 1m 24s
9148:	learn: 0.0013514	total: 15m 15s	remaining: 1m 25s
8468:	learn: 0.0013544	total: 15m 15s	remaining: 2m 45s
8885:	learn: 0.0016054	total: 15m 15s	remaining: 1m 54s
9326:	learn: 0.0014024	total: 15m 15s	remaining: 1m 6s
9153:	learn: 0.0014858	total: 15m 15s	remaining: 1m 24s
9149:	learn: 0.0013514	total: 15m 15s	remaining: 1m 25s
8886:	learn: 0.0016054	total: 15m 15s	remaining: 1m 54s
9327:	learn: 0.0014024	total: 15m 15s	remaining: 1m 5s
8469:	learn: 0.0013544	total: 15m 15s	remaining: 2m 45s
9150:	learn: 0.0013514	total: 15m 15s	remaining: 1m 24s
9154:	learn: 0.0014858	total: 15m 15s	remaining: 1m 24s
8887:	learn: 0.0016052	total: 15m 15s	remaining: 1m 54s
9328:	learn: 0.0014024	total: 15m 15s	remaining: 1m 5s
9151:	learn: 0.0013514	total: 15m 16s	remaining: 1m 24s
8470:	learn: 0.0013544	total: 15m 16s	remaining: 2m 45s
9155:	learn: 0.0014858	total: 15m 15s	remaining: 1m 24s
8888:	learn: 0.0016052	total: 15m 16s	remaining: 1m 54s
9329:	learn: 0.0014021	total: 15m 15s	remaining: 1m 5s
9152:	learn: 0.0013514	total: 15m 16s	remaining: 1m 24s
8471:	learn: 0.0013544	total: 15m 16s	remaining: 2m 45s
9156:	learn: 0.0014858	total: 15m 15s	remaining: 1m 24s
9330:	learn: 0.0014017	total: 15m 15s	remaining: 1m 5s
9153:	learn: 0.0013514	total: 15m 16s	remaining: 1m 24s
8889:	learn: 0.0016052	total: 15m 16s	remaining: 1m 54s
8472:	learn: 0.0013544	total: 15m 16s	remaining: 2m 45s
9157:	learn: 0.0014858	total: 15m 15s	remaining: 1m 24s
9154:	learn: 0.0013514	total: 15m 16s	remaining: 1m 24s
9331:	learn: 0.0014017	total: 15m 16s	remaining: 1m 5s
8890:	learn: 0.0016052	total: 15m 16s	remaining: 1m 54s
8473:	learn: 0.0013544	total: 15m 16s	remaining: 2m 45s
9158:	learn: 0.0014858	total: 15m 16s	remaining: 1m 24s
9332:	learn: 0.0014017	total: 15m 16s	remaining: 1m 5s
8474:	learn: 0.0013544	total: 15m 16s	remaining: 2m 44s
9155:	learn: 0.0013514	total: 15m 16s	remaining: 1m 24s
8891:	learn: 0.0016052	total: 15m 16s	remaining: 1m 54s
9159:	learn: 0.0014858	total: 15m 16s	remaining: 1m 24s
9333:	learn: 0.0014017	total: 15m 16s	remaining: 1m 5s
9156:	learn: 0.0013514	total: 15m 16s	remaining: 1m 24s
8475:	learn: 0.0013544	total: 15m 16s	remaining: 2m 44s
8892:	learn: 0.0016053	total: 15m 16s	remaining: 1m 54s
9334:	learn: 0.0014017	total: 15m 16s	remaining: 1m 5s
9157:	learn: 0.0013514	total: 15m 16s	remaining: 1m 24s
9160:	learn: 0.0014858	total: 15m 16s	remaining: 1m 23s
8476:	learn: 0.0013544	total: 15m 16s	remaining: 2m 44s
9335:	learn: 0.0014017	total: 15m 16s	remaining: 1m 5s
8893:	learn: 0.0016053	total: 15m 16s	remaining: 1m 53s
9158:	learn: 0.0013514	total: 15m 16s	remaining: 1m 24s
9161:	learn: 0.0014858	total: 15m 16s	remaining: 1m 23s
8477:	learn: 0.0013541	total: 15m 16s	remaining: 2m 44s
9336:	learn: 0.0014017	total: 15m 16s	remaining: 1m 5s
9162:	learn: 0.0014858	total: 15m 16s	remaining: 1m 23s
9159:	learn: 0.0013514	total: 15m 16s	remaining: 1m 24s
8894:	learn: 0.0016053	total: 15m 16s	remaining: 1m 53s
8478:	learn: 0.0013541	total: 15m 16s	remaining: 2m 44s
9337:	learn: 0.0014017	total: 15m 16s	remaining: 1m 4s
9163:	learn: 0.0014858	total: 15m 16s	remaining: 1m 23s
9160:	learn: 0.0013510	total: 15m 16s	remaining: 1m 23s
8895:	learn: 0.0016053	total: 15m 16s	remaining: 1m 53s
8479:	learn: 0.0013541	total: 15m 16s	remaining: 2m 44s
8896:	learn: 0.0016052	total: 15m 16s	remaining: 1m 53s
9338:	learn: 0.0014017	total: 15m 16s	remaining: 1m 4s
9164:	learn: 0.0014858	total: 15m 16s	remaining: 1m 23s
9161:	learn: 0.0013506	total: 15m 16s	remaining: 1m 23s
8480:	learn: 0.0013541	total: 15m 17s	remaining: 2m 44s
9339:	learn: 0.0014017	total: 15m 16s	remaining: 1m 4s
8897:	learn: 0.0016052	total: 15m 17s	remaining: 1m 53s
9165:	learn: 0.0014858	total: 15m 16s	remaining: 1m 23s
9162:	learn: 0.0013506	total: 15m 17s	remaining: 1m 23s
9340:	learn: 0.0014017	total: 15m 16s	remaining: 1m 4s
8481:	learn: 0.0013541	total: 15m 17s	remaining: 2m 44s
9166:	learn: 0.0014858	total: 15m 16s	remaining: 1m 23s
8898:	learn: 0.0016052	total: 15m 17s	remaining: 1m 53s
9163:	learn: 0.0013506	total: 15m 17s	remaining: 1m 23s
9341:	learn: 0.0014017	total: 15m 17s	remaining: 1m 4s
8482:	learn: 0.0013541	total: 15m 17s	remaining: 2m 44s
8899:	learn: 0.0016051	total: 15m 17s	remaining: 1m 53s
9167:	learn: 0.0014858	total: 15m 17s	remaining: 1m 23s
9164:	learn: 0.0013503	total: 15m 17s	remaining: 1m 23s
9168:	learn: 0.0014858	total: 15m 17s	remaining: 1m 23s
8483:	learn: 0.0013541	total: 15m 17s	remaining: 2m 43s
9342:	learn: 0.0014017	total: 15m 17s	remaining: 1m 4s
8900:	learn: 0.0016051	total: 15m 17s	remaining: 1m 53s
9165:	learn: 0.0013499	total: 15m 17s	remaining: 1m 23s
9169:	learn: 0.0014858	total: 15m 17s	remaining: 1m 23s
9343:	learn: 0.0014017	total: 15m 17s	remaining: 1m 4s
8484:	learn: 0.0013541	total: 15m 17s	remaining: 2m 43s
8901:	learn: 0.0016051	total: 15m 17s	remaining: 1m 53s
9166:	learn: 0.0013495	total: 15m 17s	remaining: 1m 23s
9170:	learn: 0.0014858	total: 15m 17s	remaining: 1m 22s
9344:	learn: 0.0014017	total: 15m 17s	remaining: 1m 4s
8485:	learn: 0.0013541	total: 15m 17s	remaining: 2m 43s
8902:	learn: 0.0016051	total: 15m 17s	remaining: 1m 53s
9171:	learn: 0.0014858	total: 15m 17s	remaining: 1m 22s
9167:	learn: 0.0013492	total: 15m 17s	remaining: 1m 23s
9345:	learn: 0.0014017	total: 15m 17s	remaining: 1m 4s
8486:	learn: 0.0013541	total: 15m 17s	remaining: 2m 43s
9168:	learn: 0.0013492	total: 15m 17s	remaining: 1m 23s
8903:	learn: 0.0016051	total: 15m 17s	remaining: 1m 52s
9172:	learn: 0.0014858	total: 15m 17s	remaining: 1m 22s
9346:	learn: 0.0014017	total: 15m 17s	remaining: 1m 4s
9169:	learn: 0.0013492	total: 15m 17s	remaining: 1m 23s
8487:	learn: 0.0013541	total: 15m 17s	remaining: 2m 43s
8904:	learn: 0.0016051	total: 15m 17s	remaining: 1m 52s
9173:	learn: 0.0014858	total: 15m 17s	remaining: 1m 22s
9347:	learn: 0.0014017	total: 15m 17s	remaining: 1m 4s
9170:	learn: 0.0013487	total: 15m 17s	remaining: 1m 22s
8488:	learn: 0.0013541	total: 15m 17s	remaining: 2m 43s
8905:	learn: 0.0016051	total: 15m 17s	remaining: 1m 52s
9174:	learn: 0.0014858	total: 15m 17s	remaining: 1m 22s
9348:	learn: 0.0014017	total: 15m 17s	remaining: 1m 3s
9171:	learn: 0.0013483	total: 15m 17s	remaining: 1m 22s
8906:	learn: 0.0016051	total: 15m 18s	remaining: 1m 52s
8489:	learn: 0.0013541	total: 15m 18s	remaining: 2m 43s
9175:	learn: 0.0014858	total: 15m 17s	remaining: 1m 22s
9349:	learn: 0.0014017	total: 15m 17s	remaining: 1m 3s
9172:	learn: 0.0013480	total: 15m 18s	remaining: 1m 22s
8907:	learn: 0.0016051	total: 15m 18s	remaining: 1m 52s
9176:	learn: 0.0014858	total: 15m 17s	remaining: 1m 22s
8490:	learn: 0.0013541	total: 15m 18s	remaining: 2m 43s
9350:	learn: 0.0014017	total: 15m 17s	remaining: 1m 3s
9173:	learn: 0.0013480	total: 15m 18s	remaining: 1m 22s
9177:	learn: 0.0014858	total: 15m 17s	remaining: 1m 22s
8908:	learn: 0.0016051	total: 15m 18s	remaining: 1m 52s
8491:	learn: 0.0013541	total: 15m 18s	remaining: 2m 43s
9174:	learn: 0.0013480	total: 15m 18s	remaining: 1m 22s
9351:	learn: 0.0014017	total: 15m 18s	remaining: 1m 3s
9178:	learn: 0.0014858	total: 15m 17s	remaining: 1m 22s
9175:	learn: 0.0013475	total: 15m 18s	remaining: 1m 22s
8909:	learn: 0.0016051	total: 15m 18s	remaining: 1m 52s
8492:	learn: 0.0013541	total: 15m 18s	remaining: 2m 42s
9352:	learn: 0.0014017	total: 15m 18s	remaining: 1m 3s
9179:	learn: 0.0014858	total: 15m 18s	remaining: 1m 22s
9176:	learn: 0.0013474	total: 15m 18s	remaining: 1m 22s
8910:	learn: 0.0016051	total: 15m 18s	remaining: 1m 52s

8493:	learn: 0.0013541	total: 15m 18s	remaining: 2m 42s
9353:	learn: 0.0014017	total: 15m 18s	remaining: 1m 3s
9177:	learn: 0.0013470	total: 15m 18s	remaining: 1m 22s
9180:	learn: 0.0014858	total: 15m 18s	remaining: 1m 21s
8494:	learn: 0.0013541	total: 15m 18s	remaining: 2m 42s
9354:	learn: 0.0014017	total: 15m 18s	remaining: 1m 3s
8911:	learn: 0.0016051	total: 15m 18s	remaining: 1m 52s
9181:	learn: 0.0014858	total: 15m 18s	remaining: 1m 21s
9178:	learn: 0.0013467	total: 15m 18s	remaining: 1m 22s
8495:	learn: 0.0013541	total: 15m 18s	remaining: 2m 42s
9355:	learn: 0.0014017	total: 15m 18s	remaining: 1m 3s
8912:	learn: 0.0016051	total: 15m 18s	remaining: 1m 52s
9182:	learn: 0.0014858	total: 15m 18s	remaining: 1m 21s
8496:	learn: 0.0013541	total: 15m 18s	remaining: 2m 42s
9356:	learn: 0.0014017	total: 15m 18s	remaining: 1m 3s
9179:	learn: 0.0013467	total: 15m 18s	remaining: 1m 22s
8913:	learn: 0.0016051	total: 15m 18s	remaining: 1m 51s
9183:	learn: 0.0014858	total: 15m 18s	remaining: 1m 21s
9357:	learn: 0.0014017	total: 15m 18s	remaining: 1m 3s
8497:	learn: 0.0013541	total: 15m 18s	remaining: 2m 42s
9180:	learn: 0.0013463	total: 15m 18s	remaining: 1m 21s
8914:	learn: 0.0016045	total: 15m 18s	remaining: 1m 51s
9184:	learn: 0.0014858	total: 15m 18s	remaining: 1m 21s
9358:	learn: 0.0014017	total: 15m 18s	remaining: 1m 2s
8498:	learn: 0.0013541	total: 15m 18s	remaining: 2m 42s
9181:	learn: 0.0013461	total: 15m 18s	remaining: 1m 21s
8915:	learn: 0.0016045	total: 15m 18s	remaining: 1m 51s
9185:	learn: 0.0014858	total: 15m 18s	remaining: 1m 21s
9359:	learn: 0.0014017	total: 15m 18s	remaining: 1m 2s
8499:	learn: 0.0013541	total: 15m 19s	remaining: 2m 42s
9182:	learn: 0.0013461	total: 15m 19s	remaining: 1m 21s
8916:	learn: 0.0016045	total: 15m 19s	remaining: 1m 51s
9360:	learn: 0.0014017	total: 15m 18s	remaining: 1m 2s
9186:	learn: 0.0014858	total: 15m 18s	remaining: 1m 21s
9183:	learn: 0.0013461	total: 15m 19s	remaining: 1m 21s
8500:	learn: 0.0013541	total: 15m 19s	remaining: 2m 42s
8917:	learn: 0.0016045	total: 15m 19s	remaining: 1m 51s
9361:	learn: 0.0014017	total: 15m 18s	remaining: 1m 2s
9187:	learn: 0.0014858	total: 15m 18s	remaining: 1m 21s
8501:	learn: 0.0013541	total: 15m 19s	remaining: 2m 41s
9184:	learn: 0.0013456	total: 15m 19s	remaining: 1m 21s
8918:	learn: 0.0016045	total: 15m 19s	remaining: 1m 51s
9188:	learn: 0.0014858	total: 15m 19s	remaining: 1m 21s
9362:	learn: 0.0014017	total: 15m 19s	remaining: 1m 2s
9185:	learn: 0.0013456	total: 15m 19s	remaining: 1m 21s
8502:	learn: 0.0013541	total: 15m 19s	remaining: 2m 41s
8919:	learn: 0.0016045	total: 15m 19s	remaining: 1m 51s
9363:	learn: 0.0014017	total: 15m 19s	remaining: 1m 2s
9189:	learn: 0.0014858	total: 15m 19s	remaining: 1m 21s
9186:	learn: 0.0013456	total: 15m 19s	remaining: 1m 21s
9190:	learn: 0.0014858	total: 15m 19s	remaining: 1m 20s
8503:	learn: 0.0013541	total: 15m 19s	remaining: 2m 41s
8920:	learn: 0.0016045	total: 15m 19s	remaining: 1m 51s
9364:	learn: 0.0014017	total: 15m 19s	remaining: 1m 2s
9187:	learn: 0.0013456	total: 15m 19s	remaining: 1m 21s
9191:	learn: 0.0014857	total: 15m 19s	remaining: 1m 20s
8921:	learn: 0.0016045	total: 15m 19s	remaining: 1m 51s
9365:	learn: 0.0014017	total: 15m 19s	remaining: 1m 2s
8504:	learn: 0.0013541	total: 15m 19s	remaining: 2m 41s
9188:	learn: 0.0013456	total: 15m 19s	remaining: 1m 21s
9192:	learn: 0.0014858	total: 15m 19s	remaining: 1m 20s
8922:	learn: 0.0016045	total: 15m 19s	remaining: 1m 51s
9366:	learn: 0.0014017	total: 15m 19s	remaining: 1m 2s
8505:	learn: 0.0013541	total: 15m 19s	remaining: 2m 41s
9189:	learn: 0.0013456	total: 15m 19s	remaining: 1m 21s
9193:	learn: 0.0014858	total: 15m 19s	remaining: 1m 20s
8923:	learn: 0.0016045	total: 15m 19s	remaining: 1m 50s
9367:	learn: 0.0014017	total: 15m 19s	remaining: 1m 2s
9194:	learn: 0.0014858	total: 15m 19s	remaining: 1m 20s
9190:	learn: 0.0013456	total: 15m 19s	remaining: 1m 20s
8506:	learn: 0.0013541	total: 15m 19s	remaining: 2m 41s
9368:	learn: 0.0014017	total: 15m 19s	remaining: 1m 1s
8924:	learn: 0.0016045	total: 15m 19s	remaining: 1m 50s
9195:	learn: 0.0014857	total: 15m 19s	remaining: 1m 20s
9191:	learn: 0.0013456	total: 15m 19s	remaining: 1m 20s
8507:	learn: 0.0013541	total: 15m 19s	remaining: 2m 41s
8925:	learn: 0.0016045	total: 15m 20s	remaining: 1m 50s
9369:	learn: 0.0014017	total: 15m 19s	remaining: 1m 1s
9196:	learn: 0.0014857	total: 15m 19s	remaining: 1m 20s
9370:	learn: 0.0014017	total: 15m 19s	remaining: 1m 1s
8508:	learn: 0.0013541	total: 15m 20s	remaining: 2m 41s
8926:	learn: 0.0016045	total: 15m 20s	remaining: 1m 50s
9192:	learn: 0.0013456	total: 15m 20s	remaining: 1m 20s
9197:	learn: 0.0014857	total: 15m 19s	remaining: 1m 20s
8927:	learn: 0.0016045	total: 15m 20s	remaining: 1m 50s
9371:	learn: 0.0014017	total: 15m 19s	remaining: 1m 1s
8509:	learn: 0.0013541	total: 15m 20s	remaining: 2m 41s
9198:	learn: 0.0014857	total: 15m 19s	remaining: 1m 20s
9193:	learn: 0.0013456	total: 15m 20s	remaining: 1m 20s
8928:	learn: 0.0016045	total: 15m 20s	remaining: 1m 50s
9372:	learn: 0.0014014	total: 15m 20s	remaining: 1m 1s
9199:	learn: 0.0014857	total: 15m 20s	remaining: 1m 20s
8510:	learn: 0.0013541	total: 15m 20s	remaining: 2m 41s
9194:	learn: 0.0013452	total: 15m 20s	remaining: 1m 20s
8929:	learn: 0.0016045	total: 15m 20s	remaining: 1m 50s
9373:	learn: 0.0014014	total: 15m 20s	remaining: 1m 1s
9200:	learn: 0.0014857	total: 15m 20s	remaining: 1m 19s
8511:	learn: 0.0013541	total: 15m 20s	remaining: 2m 40s
9195:	learn: 0.0013452	total: 15m 20s	remaining: 1m 20s
8930:	learn: 0.0016045	total: 15m 20s	remaining: 1m 50s
8512:	learn: 0.0013541	total: 15m 20s	remaining: 2m 40s
9374:	learn: 0.0014014	total: 15m 20s	remaining: 1m 1s
9201:	learn: 0.0014857	total: 15m 20s	remaining: 1m 19s
9196:	learn: 0.0013452	total: 15m 20s	remaining: 1m 20s
8931:	learn: 0.0016045	total: 15m 20s	remaining: 1m 50s
8513:	learn: 0.0013541	total: 15m 20s	remaining: 2m 40s
9375:	learn: 0.0014014	total: 15m 20s	remaining: 1m 1s
9202:	learn: 0.0014857	total: 15m 20s	remaining: 1m 19s
9197:	learn: 0.0013452	total: 15m 20s	remaining: 1m 20s
9376:	learn: 0.0014014	total: 15m 20s	remaining: 1m 1s
8932:	learn: 0.0016045	total: 15m 20s	remaining: 1m 49s
8514:	learn: 0.0013541	total: 15m 20s	remaining: 2m 40s
9203:	learn: 0.0014857	total: 15m 20s	remaining: 1m 19s
9198:	learn: 0.0013452	total: 15m 20s	remaining: 1m 20s
9377:	learn: 0.0014013	total: 15m 20s	remaining: 1m 1s
8933:	learn: 0.0016045	total: 15m 20s	remaining: 1m 49s
8515:	learn: 0.0013541	total: 15m 20s	remaining: 2m 40s
9204:	learn: 0.0014857	total: 15m 20s	remaining: 1m 19s
9199:	learn: 0.0013448	total: 15m 20s	remaining: 1m 20s
8934:	learn: 0.0016045	total: 15m 20s	remaining: 1m 49s
9205:	learn: 0.0014857	total: 15m 20s	remaining: 1m 19s
8516:	learn: 0.0013541	total: 15m 20s	remaining: 2m 40s
9378:	learn: 0.0014013	total: 15m 20s	remaining: 1m
9200:	learn: 0.0013448	total: 15m 20s	remaining: 1m 19s
8935:	learn: 0.0016045	total: 15m 20s	remaining: 1m 49s
8517:	learn: 0.0013541	total: 15m 21s	remaining: 2m 40s
9379:	learn: 0.0014013	total: 15m 20s	remaining: 1m
9206:	learn: 0.0014857	total: 15m 20s	remaining: 1m 19s
8936:	learn: 0.0016045	total: 15m 21s	remaining: 1m 49s
9201:	learn: 0.0013448	total: 15m 21s	remaining: 1m 19s
8518:	learn: 0.0013541	total: 15m 21s	remaining: 2m 40s
9207:	learn: 0.0014857	total: 15m 20s	remaining: 1m 19s
9380:	learn: 0.0014013	total: 15m 20s	remaining: 1m
8937:	learn: 0.0016045	total: 15m 21s	remaining: 1m 49s
9208:	learn: 0.0014857	total: 15m 20s	remaining: 1m 19s
9381:	learn: 0.0014013	total: 15m 20s	remaining: 1m
9202:	learn: 0.0013448	total: 15m 21s	remaining: 1m 19s
8938:	learn: 0.0016045	total: 15m 21s	remaining: 1m 49s
8519:	learn: 0.0013541	total: 15m 21s	remaining: 2m 40s
9209:	learn: 0.0014857	total: 15m 20s	remaining: 1m 18s
9203:	learn: 0.0013448	total: 15m 21s	remaining: 1m 19s
9382:	learn: 0.0014013	total: 15m 21s	remaining: 1m
9210:	learn: 0.0014857	total: 15m 21s	remaining: 1m 18s
8939:	learn: 0.0016045	total: 15m 21s	remaining: 1m 49s
8520:	learn: 0.0013541	total: 15m 21s	remaining: 2m 39s
9204:	learn: 0.0013448	total: 15m 21s	remaining: 1m 19s
9211:	learn: 0.0014857	total: 15m 21s	remaining: 1m 18s
9383:	learn: 0.0014013	total: 15m 21s	remaining: 1m
8521:	learn: 0.0013541	total: 15m 21s	remaining: 2m 39s
8940:	learn: 0.0016045	total: 15m 21s	remaining: 1m 49s
9205:	learn: 0.0013442	total: 15m 21s	remaining: 1m 19s
9384:	learn: 0.0014013	total: 15m 21s	remaining: 1m
9212:	learn: 0.0014857	total: 15m 21s	remaining: 1m 18s
9206:	learn: 0.0013442	total: 15m 21s	remaining: 1m 19s
8522:	learn: 0.0013540	total: 15m 21s	remaining: 2m 39s
8941:	learn: 0.0016045	total: 15m 21s	remaining: 1m 49s
9385:	learn: 0.0014013	total: 15m 21s	remaining: 1m
9207:	learn: 0.0013442	total: 15m 21s	remaining: 1m 19s
8523:	learn: 0.0013540	total: 15m 21s	remaining: 2m 39s
9213:	learn: 0.0014857	total: 15m 21s	remaining: 1m 18s
8942:	learn: 0.0016041	total: 15m 21s	remaining: 1m 48s
9386:	learn: 0.0014013	total: 15m 21s	remaining: 1m
9208:	learn: 0.0013442	total: 15m 21s	remaining: 1m 19s
8524:	learn: 0.0013540	total: 15m 21s	remaining: 2m 39s
9214:	learn: 0.0014857	total: 15m 21s	remaining: 1m 18s
8943:	learn: 0.0016041	total: 15m 21s	remaining: 1m 48s
9209:	learn: 0.0013439	total: 15m 21s	remaining: 1m 19s
8525:	learn: 0.0013540	total: 15m 21s	remaining: 2m 39s
9387:	learn: 0.0014013	total: 15m 21s	remaining: 1m
9215:	learn: 0.0014857	total: 15m 21s	remaining: 1m 18s
9210:	learn: 0.0013435	total: 15m 21s	remaining: 1m 18s
8944:	learn: 0.0016041	total: 15m 21s	remaining: 1m 48s
8526:	learn: 0.0013540	total: 15m 21s	remaining: 2m 39s
9216:	learn: 0.0014857	total: 15m 21s	remaining: 1m 18s
9388:	learn: 0.0014013	total: 15m 21s	remaining: 60s
9211:	learn: 0.0013434	total: 15m 21s	remaining: 1m 18s
8945:	learn: 0.0016041	total: 15m 21s	remaining: 1m 48s
9389:	learn: 0.0014013	total: 15m 21s	remaining: 59.9s
9217:	learn: 0.0014857	total: 15m 21s	remaining: 1m 18s
8527:	learn: 0.0013540	total: 15m 22s	remaining: 2m 39s
8946:	learn: 0.0016041	total: 15m 22s	remaining: 1m 48s
9212:	learn: 0.0013434	total: 15m 22s	remaining: 1m 18s
9218:	learn: 0.0014857	total: 15m 21s	remaining: 1m 18s
9390:	learn: 0.0014013	total: 15m 21s	remaining: 59.8s
8528:	learn: 0.0013536	total: 15m 22s	remaining: 2m 39s
8947:	learn: 0.0016041	total: 15m 22s	remaining: 1m 48s
9213:	learn: 0.0013432	total: 15m 22s	remaining: 1m 18s
9219:	learn: 0.0014857	total: 15m 21s	remaining: 1m 17s
8948:	learn: 0.0016041	total: 15m 22s	remaining: 1m 48s
9391:	learn: 0.0014013	total: 15m 22s	remaining: 59.7s
8529:	learn: 0.0013536	total: 15m 22s	remaining: 2m 38s
9214:	learn: 0.0013428	total: 15m 22s	remaining: 1m 18s
9220:	learn: 0.0014857	total: 15m 22s	remaining: 1m 17s
9392:	learn: 0.0014013	total: 15m 22s	remaining: 59.6s
8949:	learn: 0.0016041	total: 15m 22s	remaining: 1m 48s
9215:	learn: 0.0013428	total: 15m 22s	remaining: 1m 18s
9221:	learn: 0.0014857	total: 15m 22s	remaining: 1m 17s
9393:	learn: 0.0014013	total: 15m 22s	remaining: 59.5s
8530:	learn: 0.0013536	total: 15m 22s	remaining: 2m 38s
8950:	learn: 0.0016041	total: 15m 22s	remaining: 1m 48s
9216:	learn: 0.0013427	total: 15m 22s	remaining: 1m 18s
9222:	learn: 0.0014857	total: 15m 22s	remaining: 1m 17s
9394:	learn: 0.0014013	total: 15m 22s	remaining: 59.4s
8531:	learn: 0.0013536	total: 15m 22s	remaining: 2m 38s
8951:	learn: 0.0016041	total: 15m 22s	remaining: 1m 48s
9217:	learn: 0.0013424	total: 15m 22s	remaining: 1m 18s
9395:	learn: 0.0014013	total: 15m 22s	remaining: 59.3s
9223:	learn: 0.0014857	total: 15m 22s	remaining: 1m 17s
9218:	learn: 0.0013424	total: 15m 22s	remaining: 1m 18s
8532:	learn: 0.0013536	total: 15m 22s	remaining: 2m 38s
9396:	learn: 0.0014013	total: 15m 22s	remaining: 59.2s
8952:	learn: 0.0016041	total: 15m 22s	remaining: 1m 47s
9219:	learn: 0.0013420	total: 15m 22s	remaining: 1m 18s
8533:	learn: 0.0013536	total: 15m 22s	remaining: 2m 38s
9224:	learn: 0.0014857	total: 15m 22s	remaining: 1m 17s
9397:	learn: 0.0014013	total: 15m 22s	remaining: 59.1s
8953:	learn: 0.0016041	total: 15m 22s	remaining: 1m 47s
9225:	learn: 0.0014857	total: 15m 22s	remaining: 1m 17s
8534:	learn: 0.0013536	total: 15m 22s	remaining: 2m 38s
9220:	learn: 0.0013416	total: 15m 22s	remaining: 1m 17s
9226:	learn: 0.0014857	total: 15m 22s	remaining: 1m 17s
8535:	learn: 0.0013535	total: 15m 22s	remaining: 2m 38s
9398:	learn: 0.0014013	total: 15m 22s	remaining: 59s
9221:	learn: 0.0013416	total: 15m 22s	remaining: 1m 17s
8954:	learn: 0.0016041	total: 15m 22s	remaining: 1m 47s
9227:	learn: 0.0014857	total: 15m 22s	remaining: 1m 17s
9399:	learn: 0.0014013	total: 15m 22s	remaining: 58.9s
8536:	learn: 0.0013536	total: 15m 23s	remaining: 2m 38s
9222:	learn: 0.0013416	total: 15m 23s	remaining: 1m 17s
9228:	learn: 0.0014857	total: 15m 22s	remaining: 1m 17s
8955:	learn: 0.0016037	total: 15m 23s	remaining: 1m 47s
9229:	learn: 0.0014857	total: 15m 22s	remaining: 1m 16s
8537:	learn: 0.0013536	total: 15m 23s	remaining: 2m 38s
9400:	learn: 0.0014013	total: 15m 22s	remaining: 58.8s
9223:	learn: 0.0013416	total: 15m 23s	remaining: 1m 17s
8956:	learn: 0.0016037	total: 15m 23s	remaining: 1m 47s
8538:	learn: 0.0013536	total: 15m 23s	remaining: 2m 37s
9224:	learn: 0.0013413	total: 15m 23s	remaining: 1m 17s
9230:	learn: 0.0014857	total: 15m 22s	remaining: 1m 16s
9401:	learn: 0.0014013	total: 15m 23s	remaining: 58.7s
8539:	learn: 0.0013536	total: 15m 23s	remaining: 2m 37s
8957:	learn: 0.0016037	total: 15m 23s	remaining: 1m 47s
9231:	learn: 0.0014857	total: 15m 23s	remaining: 1m 16s
9225:	learn: 0.0013413	total: 15m 23s	remaining: 1m 17s
9402:	learn: 0.0014013	total: 15m 23s	remaining: 58.6s
8958:	learn: 0.0016036	total: 15m 23s	remaining: 1m 47s
8540:	learn: 0.0013536	total: 15m 23s	remaining: 2m 37s
9232:	learn: 0.0014857	total: 15m 23s	remaining: 1m 16s
9403:	learn: 0.0014013	total: 15m 23s	remaining: 58.5s
8959:	learn: 0.0016036	total: 15m 23s	remaining: 1m 47s
9226:	learn: 0.0013413	total: 15m 23s	remaining: 1m 17s
8541:	learn: 0.0013535	total: 15m 23s	remaining: 2m 37s
9233:	learn: 0.0014857	total: 15m 23s	remaining: 1m 16s
8960:	learn: 0.0016036	total: 15m 23s	remaining: 1m 47s
9404:	learn: 0.0014013	total: 15m 23s	remaining: 58.4s
9227:	learn: 0.0013413	total: 15m 23s	remaining: 1m 17s
8542:	learn: 0.0013536	total: 15m 23s	remaining: 2m 37s
9234:	learn: 0.0014857	total: 15m 23s	remaining: 1m 16s
8961:	learn: 0.0016036	total: 15m 23s	remaining: 1m 46s
9228:	learn: 0.0013413	total: 15m 23s	remaining: 1m 17s
9405:	learn: 0.0014013	total: 15m 23s	remaining: 58.3s
9235:	learn: 0.0014857	total: 15m 23s	remaining: 1m 16s
8543:	learn: 0.0013536	total: 15m 23s	remaining: 2m 37s
8962:	learn: 0.0016036	total: 15m 23s	remaining: 1m 46s
9229:	learn: 0.0013413	total: 15m 23s	remaining: 1m 17s
9406:	learn: 0.0014013	total: 15m 23s	remaining: 58.2s
9236:	learn: 0.0014857	total: 15m 23s	remaining: 1m 16s
8963:	learn: 0.0016036	total: 15m 23s	remaining: 1m 46s
8544:	learn: 0.0013536	total: 15m 23s	remaining: 2m 37s
9230:	learn: 0.0013413	total: 15m 23s	remaining: 1m 16s
8964:	learn: 0.0016036	total: 15m 23s	remaining: 1m 46s
8545:	learn: 0.0013536	total: 15m 23s	remaining: 2m 37s
9407:	learn: 0.0014013	total: 15m 23s	remaining: 58.1s
9237:	learn: 0.0014857	total: 15m 23s	remaining: 1m 16s
8546:	learn: 0.0013536	total: 15m 23s	remaining: 2m 37s
8965:	learn: 0.0016033	total: 15m 24s	remaining: 1m 46s
9231:	learn: 0.0013413	total: 15m 23s	remaining: 1m 16s
9408:	learn: 0.0014009	total: 15m 23s	remaining: 58s
9238:	learn: 0.0014857	total: 15m 23s	remaining: 1m 16s
8547:	learn: 0.0013536	total: 15m 24s	remaining: 2m 36s
9409:	learn: 0.0014009	total: 15m 23s	remaining: 57.9s
8966:	learn: 0.0016033	total: 15m 24s	remaining: 1m 46s
9239:	learn: 0.0014857	total: 15m 23s	remaining: 1m 15s
9232:	learn: 0.0013409	total: 15m 24s	remaining: 1m 16s
8548:	learn: 0.0013536	total: 15m 24s	remaining: 2m 36s
8967:	learn: 0.0016033	total: 15m 24s	remaining: 1m 46s
9240:	learn: 0.0014857	total: 15m 23s	remaining: 1m 15s
9233:	learn: 0.0013409	total: 15m 24s	remaining: 1m 16s
9410:	learn: 0.0014009	total: 15m 24s	remaining: 57.8s
9241:	learn: 0.0014857	total: 15m 24s	remaining: 1m 15s
8549:	learn: 0.0013536	total: 15m 24s	remaining: 2m 36s
8968:	learn: 0.0016033	total: 15m 24s	remaining: 1m 46s
9234:	learn: 0.0013407	total: 15m 24s	remaining: 1m 16s
9411:	learn: 0.0014009	total: 15m 24s	remaining: 57.7s

8969:	learn: 0.0016033	total: 15m 24s	remaining: 1m 46s
9242:	learn: 0.0014857	total: 15m 24s	remaining: 1m 15s
9235:	learn: 0.0013407	total: 15m 24s	remaining: 1m 16s
9412:	learn: 0.0014009	total: 15m 24s	remaining: 57.6s
8550:	learn: 0.0013535	total: 15m 24s	remaining: 2m 36s
8970:	learn: 0.0016033	total: 15m 24s	remaining: 1m 46s
9413:	learn: 0.0014009	total: 15m 24s	remaining: 57.5s
9243:	learn: 0.0014857	total: 15m 24s	remaining: 1m 15s
8551:	learn: 0.0013536	total: 15m 24s	remaining: 2m 36s
9236:	learn: 0.0013407	total: 15m 24s	remaining: 1m 16s
9414:	learn: 0.0014008	total: 15m 24s	remaining: 57.4s
8971:	learn: 0.0016033	total: 15m 24s	remaining: 1m 45s
9244:	learn: 0.0014857	total: 15m 24s	remaining: 1m 15s
8552:	learn: 0.0013536	total: 15m 24s	remaining: 2m 36s
9237:	learn: 0.0013407	total: 15m 24s	remaining: 1m 16s
8972:	learn: 0.0016033	total: 15m 24s	remaining: 1m 45s
9415:	learn: 0.0014008	total: 15m 24s	remaining: 57.3s
9245:	learn: 0.0014857	total: 15m 24s	remaining: 1m 15s
8553:	learn: 0.0013535	total: 15m 24s	remaining: 2m 36s
9238:	learn: 0.0013403	total: 15m 24s	remaining: 1m 16s
9246:	learn: 0.0014857	total: 15m 24s	remaining: 1m 15s
8973:	learn: 0.0016033	total: 15m 24s	remaining: 1m 45s
9416:	learn: 0.0014008	total: 15m 24s	remaining: 57.2s
9239:	learn: 0.0013403	total: 15m 24s	remaining: 1m 16s
9247:	learn: 0.0014857	total: 15m 24s	remaining: 1m 15s
8974:	learn: 0.0016033	total: 15m 24s	remaining: 1m 45s
8554:	learn: 0.0013535	total: 15m 24s	remaining: 2m 36s
9417:	learn: 0.0014008	total: 15m 24s	remaining: 57.1s
9240:	learn: 0.0013404	total: 15m 24s	remaining: 1m 15s
9248:	learn: 0.0014857	total: 15m 24s	remaining: 1m 15s
8555:	learn: 0.0013536	total: 15m 24s	remaining: 2m 36s
8975:	learn: 0.0016033	total: 15m 25s	remaining: 1m 45s
9418:	learn: 0.0014008	total: 15m 24s	remaining: 57s
8976:	learn: 0.0016033	total: 15m 25s	remaining: 1m 45s
8556:	learn: 0.0013535	total: 15m 25s	remaining: 2m 36s
9241:	learn: 0.0013403	total: 15m 25s	remaining: 1m 15s
9249:	learn: 0.0014857	total: 15m 24s	remaining: 1m 14s
9419:	learn: 0.0014008	total: 15m 24s	remaining: 56.9s
8977:	learn: 0.0016033	total: 15m 25s	remaining: 1m 45s
8557:	learn: 0.0013535	total: 15m 25s	remaining: 2m 35s
9242:	learn: 0.0013403	total: 15m 25s	remaining: 1m 15s
9420:	learn: 0.0014008	total: 15m 25s	remaining: 56.9s
9250:	learn: 0.0014857	total: 15m 24s	remaining: 1m 14s
8978:	learn: 0.0016033	total: 15m 25s	remaining: 1m 45s
9243:	learn: 0.0013403	total: 15m 25s	remaining: 1m 15s
8558:	learn: 0.0013536	total: 15m 25s	remaining: 2m 35s
9421:	learn: 0.0014008	total: 15m 25s	remaining: 56.8s
8979:	learn: 0.0016033	total: 15m 25s	remaining: 1m 45s
9244:	learn: 0.0013403	total: 15m 25s	remaining: 1m 15s
9251:	learn: 0.0014857	total: 15m 25s	remaining: 1m 14s
9422:	learn: 0.0014008	total: 15m 25s	remaining: 56.7s
8559:	learn: 0.0013536	total: 15m 25s	remaining: 2m 35s
9245:	learn: 0.0013403	total: 15m 25s	remaining: 1m 15s
8980:	learn: 0.0016033	total: 15m 25s	remaining: 1m 45s
9252:	learn: 0.0014854	total: 15m 25s	remaining: 1m 14s
9423:	learn: 0.0014008	total: 15m 25s	remaining: 56.6s
8560:	learn: 0.0013536	total: 15m 25s	remaining: 2m 35s
9246:	learn: 0.0013403	total: 15m 25s	remaining: 1m 15s
8981:	learn: 0.0016033	total: 15m 25s	remaining: 1m 44s
9424:	learn: 0.0014008	total: 15m 25s	remaining: 56.5s
9253:	learn: 0.0014854	total: 15m 25s	remaining: 1m 14s
8561:	learn: 0.0013535	total: 15m 25s	remaining: 2m 35s
9247:	learn: 0.0013403	total: 15m 25s	remaining: 1m 15s
9425:	learn: 0.0014007	total: 15m 25s	remaining: 56.4s
8982:	learn: 0.0016033	total: 15m 25s	remaining: 1m 44s
8562:	learn: 0.0013535	total: 15m 25s	remaining: 2m 35s
9254:	learn: 0.0014854	total: 15m 25s	remaining: 1m 14s
9248:	learn: 0.0013399	total: 15m 25s	remaining: 1m 15s
9426:	learn: 0.0014007	total: 15m 25s	remaining: 56.3s
8983:	learn: 0.0016030	total: 15m 25s	remaining: 1m 44s
9255:	learn: 0.0014854	total: 15m 25s	remaining: 1m 14s
9249:	learn: 0.0013395	total: 15m 25s	remaining: 1m 15s
8563:	learn: 0.0013535	total: 15m 25s	remaining: 2m 35s
9427:	learn: 0.0014007	total: 15m 25s	remaining: 56.2s
8564:	learn: 0.0013536	total: 15m 25s	remaining: 2m 35s
9256:	learn: 0.0014854	total: 15m 25s	remaining: 1m 14s
9250:	learn: 0.0013395	total: 15m 25s	remaining: 1m 14s
8984:	learn: 0.0016030	total: 15m 25s	remaining: 1m 44s
9257:	learn: 0.0014854	total: 15m 25s	remaining: 1m 14s
9428:	learn: 0.0014007	total: 15m 25s	remaining: 56.1s
8565:	learn: 0.0013535	total: 15m 25s	remaining: 2m 35s
9251:	learn: 0.0013395	total: 15m 25s	remaining: 1m 14s
8985:	learn: 0.0016030	total: 15m 26s	remaining: 1m 44s
8566:	learn: 0.0013535	total: 15m 26s	remaining: 2m 34s
9429:	learn: 0.0014007	total: 15m 25s	remaining: 56s
9252:	learn: 0.0013395	total: 15m 26s	remaining: 1m 14s
9258:	learn: 0.0014854	total: 15m 25s	remaining: 1m 14s
8567:	learn: 0.0013536	total: 15m 26s	remaining: 2m 34s
8986:	learn: 0.0016030	total: 15m 26s	remaining: 1m 44s
9430:	learn: 0.0014007	total: 15m 26s	remaining: 55.9s
9253:	learn: 0.0013395	total: 15m 26s	remaining: 1m 14s
9259:	learn: 0.0014854	total: 15m 25s	remaining: 1m 13s
8568:	learn: 0.0013536	total: 15m 26s	remaining: 2m 34s
8987:	learn: 0.0016030	total: 15m 26s	remaining: 1m 44s
9431:	learn: 0.0014007	total: 15m 26s	remaining: 55.8s
9260:	learn: 0.0014854	total: 15m 26s	remaining: 1m 13s
9254:	learn: 0.0013395	total: 15m 26s	remaining: 1m 14s
8569:	learn: 0.0013536	total: 15m 26s	remaining: 2m 34s
9432:	learn: 0.0014007	total: 15m 26s	remaining: 55.7s
9261:	learn: 0.0014849	total: 15m 26s	remaining: 1m 13s
8988:	learn: 0.0016030	total: 15m 26s	remaining: 1m 44s
9255:	learn: 0.0013395	total: 15m 26s	remaining: 1m 14s
8570:	learn: 0.0013536	total: 15m 26s	remaining: 2m 34s
9433:	learn: 0.0014007	total: 15m 26s	remaining: 55.6s
8989:	learn: 0.0016030	total: 15m 26s	remaining: 1m 44s
9256:	learn: 0.0013393	total: 15m 26s	remaining: 1m 14s
9262:	learn: 0.0014849	total: 15m 26s	remaining: 1m 13s
8571:	learn: 0.0013535	total: 15m 26s	remaining: 2m 34s
9434:	learn: 0.0014007	total: 15m 26s	remaining: 55.5s
8990:	learn: 0.0016030	total: 15m 26s	remaining: 1m 43s
9263:	learn: 0.0014849	total: 15m 26s	remaining: 1m 13s
9257:	learn: 0.0013393	total: 15m 26s	remaining: 1m 14s
9435:	learn: 0.0014007	total: 15m 26s	remaining: 55.4s
8572:	learn: 0.0013536	total: 15m 26s	remaining: 2m 34s
9264:	learn: 0.0014849	total: 15m 26s	remaining: 1m 13s
8991:	learn: 0.0016030	total: 15m 26s	remaining: 1m 43s
9258:	learn: 0.0013393	total: 15m 26s	remaining: 1m 14s
9436:	learn: 0.0014007	total: 15m 26s	remaining: 55.3s
9265:	learn: 0.0014849	total: 15m 26s	remaining: 1m 13s
8992:	learn: 0.0016030	total: 15m 26s	remaining: 1m 43s
8573:	learn: 0.0013536	total: 15m 26s	remaining: 2m 34s
9259:	learn: 0.0013393	total: 15m 26s	remaining: 1m 14s
9437:	learn: 0.0014007	total: 15m 26s	remaining: 55.2s
9266:	learn: 0.0014849	total: 15m 26s	remaining: 1m 13s
8993:	learn: 0.0016030	total: 15m 26s	remaining: 1m 43s
8574:	learn: 0.0013535	total: 15m 26s	remaining: 2m 34s
9260:	learn: 0.0013390	total: 15m 26s	remaining: 1m 13s
9438:	learn: 0.0014007	total: 15m 26s	remaining: 55.1s
9267:	learn: 0.0014849	total: 15m 26s	remaining: 1m 13s
8994:	learn: 0.0016030	total: 15m 26s	remaining: 1m 43s
8575:	learn: 0.0013535	total: 15m 27s	remaining: 2m 33s
9261:	learn: 0.0013389	total: 15m 27s	remaining: 1m 13s
9268:	learn: 0.0014849	total: 15m 26s	remaining: 1m 13s
9439:	learn: 0.0014007	total: 15m 26s	remaining: 55s
8995:	learn: 0.0016030	total: 15m 27s	remaining: 1m 43s
9262:	learn: 0.0013389	total: 15m 27s	remaining: 1m 13s
8576:	learn: 0.0013536	total: 15m 27s	remaining: 2m 33s
9269:	learn: 0.0014849	total: 15m 26s	remaining: 1m 12s
9440:	learn: 0.0014007	total: 15m 26s	remaining: 54.9s
8996:	learn: 0.0016030	total: 15m 27s	remaining: 1m 43s
9270:	learn: 0.0014849	total: 15m 26s	remaining: 1m 12s
9263:	learn: 0.0013389	total: 15m 27s	remaining: 1m 13s
8577:	learn: 0.0013536	total: 15m 27s	remaining: 2m 33s
9441:	learn: 0.0014007	total: 15m 27s	remaining: 54.8s
9271:	learn: 0.0014849	total: 15m 27s	remaining: 1m 12s
8997:	learn: 0.0016030	total: 15m 27s	remaining: 1m 43s
9264:	learn: 0.0013389	total: 15m 27s	remaining: 1m 13s
8578:	learn: 0.0013535	total: 15m 27s	remaining: 2m 33s
9442:	learn: 0.0014007	total: 15m 27s	remaining: 54.7s
9272:	learn: 0.0014845	total: 15m 27s	remaining: 1m 12s
9265:	learn: 0.0013389	total: 15m 27s	remaining: 1m 13s
8579:	learn: 0.0013535	total: 15m 27s	remaining: 2m 33s
8998:	learn: 0.0016030	total: 15m 27s	remaining: 1m 43s
9443:	learn: 0.0014007	total: 15m 27s	remaining: 54.6s
8580:	learn: 0.0013535	total: 15m 27s	remaining: 2m 33s
9266:	learn: 0.0013389	total: 15m 27s	remaining: 1m 13s
9273:	learn: 0.0014845	total: 15m 27s	remaining: 1m 12s
8999:	learn: 0.0016030	total: 15m 27s	remaining: 1m 43s
9444:	learn: 0.0014007	total: 15m 27s	remaining: 54.5s
8581:	learn: 0.0013533	total: 15m 27s	remaining: 2m 33s
9274:	learn: 0.0014845	total: 15m 27s	remaining: 1m 12s
9267:	learn: 0.0013389	total: 15m 27s	remaining: 1m 13s
9000:	learn: 0.0016029	total: 15m 27s	remaining: 1m 42s
9445:	learn: 0.0014007	total: 15m 27s	remaining: 54.4s
9268:	learn: 0.0013389	total: 15m 27s	remaining: 1m 13s
9275:	learn: 0.0014845	total: 15m 27s	remaining: 1m 12s
8582:	learn: 0.0013533	total: 15m 27s	remaining: 2m 33s
9001:	learn: 0.0016030	total: 15m 27s	remaining: 1m 42s
9269:	learn: 0.0013389	total: 15m 27s	remaining: 1m 13s
9446:	learn: 0.0014007	total: 15m 27s	remaining: 54.3s
9276:	learn: 0.0014845	total: 15m 27s	remaining: 1m 12s
8583:	learn: 0.0013533	total: 15m 27s	remaining: 2m 33s
9002:	learn: 0.0016030	total: 15m 27s	remaining: 1m 42s
9447:	learn: 0.0014007	total: 15m 27s	remaining: 54.2s
9270:	learn: 0.0013389	total: 15m 27s	remaining: 1m 12s
9277:	learn: 0.0014845	total: 15m 27s	remaining: 1m 12s
8584:	learn: 0.0013533	total: 15m 27s	remaining: 2m 32s
9003:	learn: 0.0016030	total: 15m 27s	remaining: 1m 42s
9448:	learn: 0.0014007	total: 15m 27s	remaining: 54.1s
9278:	learn: 0.0014845	total: 15m 27s	remaining: 1m 12s
9271:	learn: 0.0013389	total: 15m 27s	remaining: 1m 12s
8585:	learn: 0.0013533	total: 15m 28s	remaining: 2m 32s
9004:	learn: 0.0016030	total: 15m 28s	remaining: 1m 42s
9279:	learn: 0.0014845	total: 15m 27s	remaining: 1m 11s
9449:	learn: 0.0014007	total: 15m 27s	remaining: 54s
8586:	learn: 0.0013533	total: 15m 28s	remaining: 2m 32s
9272:	learn: 0.0013389	total: 15m 28s	remaining: 1m 12s
9005:	learn: 0.0016030	total: 15m 28s	remaining: 1m 42s
9450:	learn: 0.0014007	total: 15m 27s	remaining: 53.9s
9273:	learn: 0.0013389	total: 15m 28s	remaining: 1m 12s
9280:	learn: 0.0014845	total: 15m 27s	remaining: 1m 11s
8587:	learn: 0.0013533	total: 15m 28s	remaining: 2m 32s
9006:	learn: 0.0016030	total: 15m 28s	remaining: 1m 42s
9451:	learn: 0.0014007	total: 15m 28s	remaining: 53.8s
9274:	learn: 0.0013385	total: 15m 28s	remaining: 1m 12s
8588:	learn: 0.0013533	total: 15m 28s	remaining: 2m 32s
9281:	learn: 0.0014845	total: 15m 28s	remaining: 1m 11s
9007:	learn: 0.0016030	total: 15m 28s	remaining: 1m 42s
9452:	learn: 0.0014007	total: 15m 28s	remaining: 53.7s
9275:	learn: 0.0013385	total: 15m 28s	remaining: 1m 12s
9282:	learn: 0.0014845	total: 15m 28s	remaining: 1m 11s
8589:	learn: 0.0013533	total: 15m 28s	remaining: 2m 32s
9008:	learn: 0.0016030	total: 15m 28s	remaining: 1m 42s
9453:	learn: 0.0014007	total: 15m 28s	remaining: 53.6s
9276:	learn: 0.0013385	total: 15m 28s	remaining: 1m 12s
9283:	learn: 0.0014845	total: 15m 28s	remaining: 1m 11s
8590:	learn: 0.0013533	total: 15m 28s	remaining: 2m 32s
9454:	learn: 0.0014003	total: 15m 28s	remaining: 53.5s
9009:	learn: 0.0016030	total: 15m 28s	remaining: 1m 42s
9277:	learn: 0.0013385	total: 15m 28s	remaining: 1m 12s
9284:	learn: 0.0014845	total: 15m 28s	remaining: 1m 11s
8591:	learn: 0.0013533	total: 15m 28s	remaining: 2m 32s
9455:	learn: 0.0014003	total: 15m 28s	remaining: 53.4s
9278:	learn: 0.0013385	total: 15m 28s	remaining: 1m 12s
9010:	learn: 0.0016030	total: 15m 28s	remaining: 1m 41s
9285:	learn: 0.0014845	total: 15m 28s	remaining: 1m 11s
8592:	learn: 0.0013533	total: 15m 28s	remaining: 2m 32s
9279:	learn: 0.0013385	total: 15m 28s	remaining: 1m 12s
9286:	learn: 0.0014845	total: 15m 28s	remaining: 1m 11s
9011:	learn: 0.0016029	total: 15m 28s	remaining: 1m 41s
9456:	learn: 0.0014003	total: 15m 28s	remaining: 53.3s
9280:	learn: 0.0013385	total: 15m 28s	remaining: 1m 11s
8593:	learn: 0.0013534	total: 15m 28s	remaining: 2m 31s
9457:	learn: 0.0014003	total: 15m 28s	remaining: 53.2s
9287:	learn: 0.0014845	total: 15m 28s	remaining: 1m 11s
9012:	learn: 0.0016030	total: 15m 28s	remaining: 1m 41s
9281:	learn: 0.0013385	total: 15m 28s	remaining: 1m 11s
9288:	learn: 0.0014845	total: 15m 28s	remaining: 1m 11s
8594:	learn: 0.0013533	total: 15m 28s	remaining: 2m 31s
9458:	learn: 0.0014003	total: 15m 28s	remaining: 53.1s
9013:	learn: 0.0016030	total: 15m 29s	remaining: 1m 41s
9282:	learn: 0.0013385	total: 15m 29s	remaining: 1m 11s
9459:	learn: 0.0014003	total: 15m 28s	remaining: 53s
8595:	learn: 0.0013533	total: 15m 29s	remaining: 2m 31s
9014:	learn: 0.0016025	total: 15m 29s	remaining: 1m 41s
9289:	learn: 0.0014845	total: 15m 28s	remaining: 1m 10s
9283:	learn: 0.0013383	total: 15m 29s	remaining: 1m 11s
9460:	learn: 0.0014003	total: 15m 28s	remaining: 52.9s
9015:	learn: 0.0016025	total: 15m 29s	remaining: 1m 41s
9290:	learn: 0.0014845	total: 15m 28s	remaining: 1m 10s
8596:	learn: 0.0013533	total: 15m 29s	remaining: 2m 31s
9284:	learn: 0.0013383	total: 15m 29s	remaining: 1m 11s
9461:	learn: 0.0014003	total: 15m 29s	remaining: 52.8s
9016:	learn: 0.0016025	total: 15m 29s	remaining: 1m 41s
9291:	learn: 0.0014845	total: 15m 29s	remaining: 1m 10s
8597:	learn: 0.0013533	total: 15m 29s	remaining: 2m 31s
9462:	learn: 0.0014003	total: 15m 29s	remaining: 52.7s
9285:	learn: 0.0013382	total: 15m 29s	remaining: 1m 11s
9292:	learn: 0.0014845	total: 15m 29s	remaining: 1m 10s
9017:	learn: 0.0016025	total: 15m 29s	remaining: 1m 41s
9463:	learn: 0.0014003	total: 15m 29s	remaining: 52.6s
9286:	learn: 0.0013382	total: 15m 29s	remaining: 1m 11s
8598:	learn: 0.0013533	total: 15m 29s	remaining: 2m 31s
9293:	learn: 0.0014845	total: 15m 29s	remaining: 1m 10s
9018:	learn: 0.0016025	total: 15m 29s	remaining: 1m 41s
9464:	learn: 0.0014003	total: 15m 29s	remaining: 52.5s
9287:	learn: 0.0013382	total: 15m 29s	remaining: 1m 11s
8599:	learn: 0.0013533	total: 15m 29s	remaining: 2m 31s
9294:	learn: 0.0014845	total: 15m 29s	remaining: 1m 10s
9465:	learn: 0.0013998	total: 15m 29s	remaining: 52.4s
9019:	learn: 0.0016025	total: 15m 29s	remaining: 1m 41s
9288:	learn: 0.0013382	total: 15m 29s	remaining: 1m 11s
8600:	learn: 0.0013533	total: 15m 29s	remaining: 2m 31s
9466:	learn: 0.0013998	total: 15m 29s	remaining: 52.3s
9295:	learn: 0.0014845	total: 15m 29s	remaining: 1m 10s
9020:	learn: 0.0016025	total: 15m 29s	remaining: 1m 40s
9289:	learn: 0.0013382	total: 15m 29s	remaining: 1m 11s
8601:	learn: 0.0013533	total: 15m 29s	remaining: 2m 31s
9467:	learn: 0.0013998	total: 15m 29s	remaining: 52.2s
9296:	learn: 0.0014845	total: 15m 29s	remaining: 1m 10s
9021:	learn: 0.0016019	total: 15m 29s	remaining: 1m 40s
9290:	learn: 0.0013381	total: 15m 29s	remaining: 1m 10s
8602:	learn: 0.0013533	total: 15m 29s	remaining: 2m 30s
9468:	learn: 0.0013998	total: 15m 29s	remaining: 52.1s
9297:	learn: 0.0014845	total: 15m 29s	remaining: 1m 10s
9022:	learn: 0.0016019	total: 15m 29s	remaining: 1m 40s
8603:	learn: 0.0013533	total: 15m 29s	remaining: 2m 30s
9291:	learn: 0.0013381	total: 15m 29s	remaining: 1m 10s
9469:	learn: 0.0013998	total: 15m 29s	remaining: 52s
9298:	learn: 0.0014845	total: 15m 29s	remaining: 1m 10s
8604:	learn: 0.0013533	total: 15m 30s	remaining: 2m 30s
9292:	learn: 0.0013380	total: 15m 30s	remaining: 1m 10s
9023:	learn: 0.0016015	total: 15m 30s	remaining: 1m 40s
9299:	learn: 0.0014845	total: 15m 29s	remaining: 1m 9s
9470:	learn: 0.0013998	total: 15m 29s	remaining: 51.9s
9293:	learn: 0.0013380	total: 15m 30s	remaining: 1m 10s
8605:	learn: 0.0013533	total: 15m 30s	remaining: 2m 30s
9300:	learn: 0.0014845	total: 15m 29s	remaining: 1m 9s
9024:	learn: 0.0016015	total: 15m 30s	remaining: 1m 40s
9471:	learn: 0.0013998	total: 15m 30s	remaining: 51.8s
9294:	learn: 0.0013380	total: 15m 30s	remaining: 1m 10s
8606:	learn: 0.0013533	total: 15m 30s	remaining: 2m 30s

9301:	learn: 0.0014845	total: 15m 29s	remaining: 1m 9s
9025:	learn: 0.0016015	total: 15m 30s	remaining: 1m 40s
9295:	learn: 0.0013380	total: 15m 30s	remaining: 1m 10s
9472:	learn: 0.0013998	total: 15m 30s	remaining: 51.7s
9302:	learn: 0.0014845	total: 15m 30s	remaining: 1m 9s
8607:	learn: 0.0013533	total: 15m 30s	remaining: 2m 30s
9473:	learn: 0.0013998	total: 15m 30s	remaining: 51.6s
9296:	learn: 0.0013380	total: 15m 30s	remaining: 1m 10s
9303:	learn: 0.0014845	total: 15m 30s	remaining: 1m 9s
9026:	learn: 0.0016011	total: 15m 30s	remaining: 1m 40s
8608:	learn: 0.0013533	total: 15m 30s	remaining: 2m 30s
9474:	learn: 0.0013998	total: 15m 30s	remaining: 51.5s
9027:	learn: 0.0016011	total: 15m 30s	remaining: 1m 40s
9304:	learn: 0.0014844	total: 15m 30s	remaining: 1m 9s
9297:	learn: 0.0013380	total: 15m 30s	remaining: 1m 10s
8609:	learn: 0.0013533	total: 15m 30s	remaining: 2m 30s
9475:	learn: 0.0013998	total: 15m 30s	remaining: 51.4s
9028:	learn: 0.0016011	total: 15m 30s	remaining: 1m 40s
9305:	learn: 0.0014844	total: 15m 30s	remaining: 1m 9s
9298:	learn: 0.0013380	total: 15m 30s	remaining: 1m 10s
8610:	learn: 0.0013533	total: 15m 30s	remaining: 2m 30s
9476:	learn: 0.0013998	total: 15m 30s	remaining: 51.3s
9299:	learn: 0.0013380	total: 15m 30s	remaining: 1m 10s
9029:	learn: 0.0016011	total: 15m 30s	remaining: 1m 39s
9306:	learn: 0.0014844	total: 15m 30s	remaining: 1m 9s
9477:	learn: 0.0013998	total: 15m 30s	remaining: 51.3s
8611:	learn: 0.0013533	total: 15m 30s	remaining: 2m 30s
9300:	learn: 0.0013380	total: 15m 30s	remaining: 1m 9s
9307:	learn: 0.0014844	total: 15m 30s	remaining: 1m 9s
9030:	learn: 0.0016011	total: 15m 30s	remaining: 1m 39s
9478:	learn: 0.0013998	total: 15m 30s	remaining: 51.2s
8612:	learn: 0.0013533	total: 15m 30s	remaining: 2m 29s
9301:	learn: 0.0013380	total: 15m 30s	remaining: 1m 9s
9479:	learn: 0.0013998	total: 15m 30s	remaining: 51.1s
9308:	learn: 0.0014844	total: 15m 30s	remaining: 1m 9s
9031:	learn: 0.0016011	total: 15m 30s	remaining: 1m 39s
9302:	learn: 0.0013380	total: 15m 30s	remaining: 1m 9s
9032:	learn: 0.0016011	total: 15m 31s	remaining: 1m 39s
9309:	learn: 0.0014844	total: 15m 30s	remaining: 1m 8s
9480:	learn: 0.0013998	total: 15m 30s	remaining: 51s
8613:	learn: 0.0013533	total: 15m 31s	remaining: 2m 29s
9303:	learn: 0.0013380	total: 15m 31s	remaining: 1m 9s
9033:	learn: 0.0016011	total: 15m 31s	remaining: 1m 39s
9310:	learn: 0.0014844	total: 15m 30s	remaining: 1m 8s
9481:	learn: 0.0013998	total: 15m 30s	remaining: 50.9s
8614:	learn: 0.0013533	total: 15m 31s	remaining: 2m 29s
9304:	learn: 0.0013380	total: 15m 31s	remaining: 1m 9s
9311:	learn: 0.0014844	total: 15m 30s	remaining: 1m 8s
9034:	learn: 0.0016009	total: 15m 31s	remaining: 1m 39s
9482:	learn: 0.0013998	total: 15m 31s	remaining: 50.8s
8615:	learn: 0.0013533	total: 15m 31s	remaining: 2m 29s
9305:	learn: 0.0013380	total: 15m 31s	remaining: 1m 9s
9483:	learn: 0.0013998	total: 15m 31s	remaining: 50.7s
9312:	learn: 0.0014844	total: 15m 31s	remaining: 1m 8s
9035:	learn: 0.0016009	total: 15m 31s	remaining: 1m 39s
8616:	learn: 0.0013533	total: 15m 31s	remaining: 2m 29s
9484:	learn: 0.0013998	total: 15m 31s	remaining: 50.6s
9306:	learn: 0.0013380	total: 15m 31s	remaining: 1m 9s
9313:	learn: 0.0014844	total: 15m 31s	remaining: 1m 8s
9036:	learn: 0.0016009	total: 15m 31s	remaining: 1m 39s
8617:	learn: 0.0013533	total: 15m 31s	remaining: 2m 29s
9485:	learn: 0.0013998	total: 15m 31s	remaining: 50.5s
9307:	learn: 0.0013380	total: 15m 31s	remaining: 1m 9s
9314:	learn: 0.0014844	total: 15m 31s	remaining: 1m 8s
9037:	learn: 0.0016009	total: 15m 31s	remaining: 1m 39s
8618:	learn: 0.0013533	total: 15m 31s	remaining: 2m 29s
9486:	learn: 0.0013998	total: 15m 31s	remaining: 50.4s
9308:	learn: 0.0013380	total: 15m 31s	remaining: 1m 9s
9315:	learn: 0.0014844	total: 15m 31s	remaining: 1m 8s
9038:	learn: 0.0016009	total: 15m 31s	remaining: 1m 39s
9487:	learn: 0.0013998	total: 15m 31s	remaining: 50.3s
8619:	learn: 0.0013533	total: 15m 31s	remaining: 2m 29s
9039:	learn: 0.0016009	total: 15m 31s	remaining: 1m 38s
9309:	learn: 0.0013378	total: 15m 31s	remaining: 1m 9s
9488:	learn: 0.0013998	total: 15m 31s	remaining: 50.2s
9316:	learn: 0.0014844	total: 15m 31s	remaining: 1m 8s
9310:	learn: 0.0013372	total: 15m 31s	remaining: 1m 8s
8620:	learn: 0.0013533	total: 15m 31s	remaining: 2m 29s
9489:	learn: 0.0013998	total: 15m 31s	remaining: 50.1s
9040:	learn: 0.0016009	total: 15m 31s	remaining: 1m 38s
9317:	learn: 0.0014844	total: 15m 31s	remaining: 1m 8s
9311:	learn: 0.0013372	total: 15m 31s	remaining: 1m 8s
9490:	learn: 0.0013998	total: 15m 31s	remaining: 50s
8621:	learn: 0.0013533	total: 15m 31s	remaining: 2m 28s
9041:	learn: 0.0016008	total: 15m 31s	remaining: 1m 38s
9312:	learn: 0.0013372	total: 15m 31s	remaining: 1m 8s
9491:	learn: 0.0013998	total: 15m 31s	remaining: 49.9s
9318:	learn: 0.0014844	total: 15m 31s	remaining: 1m 8s
8622:	learn: 0.0013533	total: 15m 32s	remaining: 2m 28s
9042:	learn: 0.0016008	total: 15m 32s	remaining: 1m 38s
9492:	learn: 0.0013998	total: 15m 31s	remaining: 49.8s
9313:	learn: 0.0013372	total: 15m 32s	remaining: 1m 8s
8623:	learn: 0.0013533	total: 15m 32s	remaining: 2m 28s
9319:	learn: 0.0014844	total: 15m 31s	remaining: 1m 7s
9043:	learn: 0.0016009	total: 15m 32s	remaining: 1m 38s
9314:	learn: 0.0013372	total: 15m 32s	remaining: 1m 8s
9493:	learn: 0.0013998	total: 15m 32s	remaining: 49.7s
8624:	learn: 0.0013533	total: 15m 32s	remaining: 2m 28s
9320:	learn: 0.0014844	total: 15m 31s	remaining: 1m 7s
9044:	learn: 0.0016008	total: 15m 32s	remaining: 1m 38s
9315:	learn: 0.0013369	total: 15m 32s	remaining: 1m 8s
8625:	learn: 0.0013533	total: 15m 32s	remaining: 2m 28s
9045:	learn: 0.0016006	total: 15m 32s	remaining: 1m 38s
9494:	learn: 0.0013998	total: 15m 32s	remaining: 49.6s
9321:	learn: 0.0014844	total: 15m 32s	remaining: 1m 7s
9316:	learn: 0.0013365	total: 15m 32s	remaining: 1m 8s
8626:	learn: 0.0013533	total: 15m 32s	remaining: 2m 28s
9495:	learn: 0.0013998	total: 15m 32s	remaining: 49.5s
9046:	learn: 0.0016006	total: 15m 32s	remaining: 1m 38s
9322:	learn: 0.0014844	total: 15m 32s	remaining: 1m 7s
9317:	learn: 0.0013365	total: 15m 32s	remaining: 1m 8s
8627:	learn: 0.0013533	total: 15m 32s	remaining: 2m 28s
9496:	learn: 0.0013998	total: 15m 32s	remaining: 49.4s
9323:	learn: 0.0014844	total: 15m 32s	remaining: 1m 7s
9047:	learn: 0.0016006	total: 15m 32s	remaining: 1m 38s
8628:	learn: 0.0013533	total: 15m 32s	remaining: 2m 28s
9318:	learn: 0.0013362	total: 15m 32s	remaining: 1m 8s
9497:	learn: 0.0013998	total: 15m 32s	remaining: 49.3s
9324:	learn: 0.0014844	total: 15m 32s	remaining: 1m 7s
8629:	learn: 0.0013533	total: 15m 32s	remaining: 2m 28s
9048:	learn: 0.0016006	total: 15m 32s	remaining: 1m 38s
9319:	learn: 0.0013362	total: 15m 32s	remaining: 1m 8s
9498:	learn: 0.0013998	total: 15m 32s	remaining: 49.2s
8630:	learn: 0.0013533	total: 15m 32s	remaining: 2m 27s
9325:	learn: 0.0014844	total: 15m 32s	remaining: 1m 7s
9049:	learn: 0.0016006	total: 15m 32s	remaining: 1m 37s
9320:	learn: 0.0013362	total: 15m 32s	remaining: 1m 7s
8631:	learn: 0.0013533	total: 15m 32s	remaining: 2m 27s
9499:	learn: 0.0013998	total: 15m 32s	remaining: 49.1s
9326:	learn: 0.0014844	total: 15m 32s	remaining: 1m 7s
9050:	learn: 0.0016006	total: 15m 32s	remaining: 1m 37s
8632:	learn: 0.0013533	total: 15m 32s	remaining: 2m 27s
9327:	learn: 0.0014844	total: 15m 32s	remaining: 1m 7s
9321:	learn: 0.0013362	total: 15m 32s	remaining: 1m 7s
9500:	learn: 0.0013998	total: 15m 32s	remaining: 49s
9051:	learn: 0.0016006	total: 15m 32s	remaining: 1m 37s
8633:	learn: 0.0013533	total: 15m 33s	remaining: 2m 27s
9322:	learn: 0.0013362	total: 15m 33s	remaining: 1m 7s
9328:	learn: 0.0014844	total: 15m 32s	remaining: 1m 7s
9501:	learn: 0.0013998	total: 15m 32s	remaining: 48.9s
9052:	learn: 0.0016006	total: 15m 33s	remaining: 1m 37s
9329:	learn: 0.0014839	total: 15m 32s	remaining: 1m 6s
8634:	learn: 0.0013533	total: 15m 33s	remaining: 2m 27s
9053:	learn: 0.0016006	total: 15m 33s	remaining: 1m 37s
9323:	learn: 0.0013362	total: 15m 33s	remaining: 1m 7s
9502:	learn: 0.0013998	total: 15m 32s	remaining: 48.8s
8635:	learn: 0.0013533	total: 15m 33s	remaining: 2m 27s
9330:	learn: 0.0014839	total: 15m 32s	remaining: 1m 6s
9503:	learn: 0.0013998	total: 15m 33s	remaining: 48.7s
9324:	learn: 0.0013362	total: 15m 33s	remaining: 1m 7s
9054:	learn: 0.0016006	total: 15m 33s	remaining: 1m 37s
9331:	learn: 0.0014839	total: 15m 33s	remaining: 1m 6s
8636:	learn: 0.0013533	total: 15m 33s	remaining: 2m 27s
9055:	learn: 0.0016006	total: 15m 33s	remaining: 1m 37s
9325:	learn: 0.0013362	total: 15m 33s	remaining: 1m 7s
9504:	learn: 0.0013998	total: 15m 33s	remaining: 48.6s
9332:	learn: 0.0014839	total: 15m 33s	remaining: 1m 6s
9505:	learn: 0.0013998	total: 15m 33s	remaining: 48.5s
9326:	learn: 0.0013362	total: 15m 33s	remaining: 1m 7s
9056:	learn: 0.0016006	total: 15m 33s	remaining: 1m 37s
8637:	learn: 0.0013533	total: 15m 33s	remaining: 2m 27s
9333:	learn: 0.0014839	total: 15m 33s	remaining: 1m 6s
9506:	learn: 0.0013998	total: 15m 33s	remaining: 48.4s
8638:	learn: 0.0013533	total: 15m 33s	remaining: 2m 27s
9327:	learn: 0.0013362	total: 15m 33s	remaining: 1m 7s
9057:	learn: 0.0016006	total: 15m 33s	remaining: 1m 37s
9507:	learn: 0.0013998	total: 15m 33s	remaining: 48.3s
9334:	learn: 0.0014839	total: 15m 33s	remaining: 1m 6s
8639:	learn: 0.0013533	total: 15m 33s	remaining: 2m 26s
9328:	learn: 0.0013362	total: 15m 33s	remaining: 1m 7s
9058:	learn: 0.0016006	total: 15m 33s	remaining: 1m 36s
9335:	learn: 0.0014839	total: 15m 33s	remaining: 1m 6s
9508:	learn: 0.0013998	total: 15m 33s	remaining: 48.2s
8640:	learn: 0.0013533	total: 15m 33s	remaining: 2m 26s
9059:	learn: 0.0016006	total: 15m 33s	remaining: 1m 36s
9329:	learn: 0.0013362	total: 15m 33s	remaining: 1m 7s
9336:	learn: 0.0014839	total: 15m 33s	remaining: 1m 6s
9509:	learn: 0.0013998	total: 15m 33s	remaining: 48.1s
9060:	learn: 0.0016006	total: 15m 33s	remaining: 1m 36s
8641:	learn: 0.0013533	total: 15m 33s	remaining: 2m 26s
9330:	learn: 0.0013362	total: 15m 33s	remaining: 1m 6s
9510:	learn: 0.0013998	total: 15m 33s	remaining: 48s
9337:	learn: 0.0014839	total: 15m 33s	remaining: 1m 6s
9061:	learn: 0.0016006	total: 15m 34s	remaining: 1m 36s
9511:	learn: 0.0013998	total: 15m 33s	remaining: 47.9s
9331:	learn: 0.0013362	total: 15m 33s	remaining: 1m 6s
8642:	learn: 0.0013533	total: 15m 34s	remaining: 2m 26s
9338:	learn: 0.0014839	total: 15m 33s	remaining: 1m 6s
9062:	learn: 0.0016006	total: 15m 34s	remaining: 1m 36s
8643:	learn: 0.0013533	total: 15m 34s	remaining: 2m 26s
9332:	learn: 0.0013362	total: 15m 34s	remaining: 1m 6s
9512:	learn: 0.0013995	total: 15m 33s	remaining: 47.8s
9339:	learn: 0.0014839	total: 15m 33s	remaining: 1m 5s
9063:	learn: 0.0016006	total: 15m 34s	remaining: 1m 36s
9333:	learn: 0.0013362	total: 15m 34s	remaining: 1m 6s
8644:	learn: 0.0013533	total: 15m 34s	remaining: 2m 26s
9513:	learn: 0.0013991	total: 15m 34s	remaining: 47.7s
9340:	learn: 0.0014839	total: 15m 33s	remaining: 1m 5s
9334:	learn: 0.0013362	total: 15m 34s	remaining: 1m 6s
9064:	learn: 0.0016006	total: 15m 34s	remaining: 1m 36s
8645:	learn: 0.0013533	total: 15m 34s	remaining: 2m 26s
9341:	learn: 0.0014839	total: 15m 34s	remaining: 1m 5s
9514:	learn: 0.0013991	total: 15m 34s	remaining: 47.6s
9335:	learn: 0.0013358	total: 15m 34s	remaining: 1m 6s
9065:	learn: 0.0016006	total: 15m 34s	remaining: 1m 36s
8646:	learn: 0.0013531	total: 15m 34s	remaining: 2m 26s
9336:	learn: 0.0013354	total: 15m 34s	remaining: 1m 6s
9342:	learn: 0.0014839	total: 15m 34s	remaining: 1m 5s
9515:	learn: 0.0013991	total: 15m 34s	remaining: 47.5s
9066:	learn: 0.0016001	total: 15m 34s	remaining: 1m 36s
8647:	learn: 0.0013531	total: 15m 34s	remaining: 2m 26s
9337:	learn: 0.0013354	total: 15m 34s	remaining: 1m 6s
9343:	learn: 0.0014839	total: 15m 34s	remaining: 1m 5s
9516:	learn: 0.0013991	total: 15m 34s	remaining: 47.4s
9067:	learn: 0.0016001	total: 15m 34s	remaining: 1m 36s
9517:	learn: 0.0013991	total: 15m 34s	remaining: 47.3s
9338:	learn: 0.0013354	total: 15m 34s	remaining: 1m 6s
8648:	learn: 0.0013531	total: 15m 34s	remaining: 2m 25s
9344:	learn: 0.0014839	total: 15m 34s	remaining: 1m 5s
9068:	learn: 0.0016001	total: 15m 34s	remaining: 1m 35s
9518:	learn: 0.0013991	total: 15m 34s	remaining: 47.2s
9339:	learn: 0.0013354	total: 15m 34s	remaining: 1m 6s
9345:	learn: 0.0014839	total: 15m 34s	remaining: 1m 5s
8649:	learn: 0.0013531	total: 15m 34s	remaining: 2m 25s
9519:	learn: 0.0013991	total: 15m 34s	remaining: 47.1s
9340:	learn: 0.0013354	total: 15m 34s	remaining: 1m 5s
9069:	learn: 0.0016001	total: 15m 34s	remaining: 1m 35s
9346:	learn: 0.0014839	total: 15m 34s	remaining: 1m 5s
9520:	learn: 0.0013991	total: 15m 34s	remaining: 47s
8650:	learn: 0.0013531	total: 15m 34s	remaining: 2m 25s
9341:	learn: 0.0013354	total: 15m 34s	remaining: 1m 5s
9347:	learn: 0.0014839	total: 15m 34s	remaining: 1m 5s
9070:	learn: 0.0016001	total: 15m 34s	remaining: 1m 35s
9521:	learn: 0.0013991	total: 15m 34s	remaining: 46.9s
8651:	learn: 0.0013531	total: 15m 34s	remaining: 2m 25s
9348:	learn: 0.0014838	total: 15m 34s	remaining: 1m 5s
9342:	learn: 0.0013354	total: 15m 34s	remaining: 1m 5s
9071:	learn: 0.0016001	total: 15m 35s	remaining: 1m 35s
9522:	learn: 0.0013991	total: 15m 34s	remaining: 46.8s
8652:	learn: 0.0013530	total: 15m 35s	remaining: 2m 25s
9349:	learn: 0.0014839	total: 15m 34s	remaining: 1m 4s
9343:	learn: 0.0013353	total: 15m 35s	remaining: 1m 5s
9523:	learn: 0.0013991	total: 15m 34s	remaining: 46.7s
9072:	learn: 0.0016001	total: 15m 35s	remaining: 1m 35s
9344:	learn: 0.0013350	total: 15m 35s	remaining: 1m 5s
9350:	learn: 0.0014839	total: 15m 34s	remaining: 1m 4s
9524:	learn: 0.0013991	total: 15m 35s	remaining: 46.6s
8653:	learn: 0.0013530	total: 15m 35s	remaining: 2m 25s
9345:	learn: 0.0013350	total: 15m 35s	remaining: 1m 5s
9073:	learn: 0.0016001	total: 15m 35s	remaining: 1m 35s
9525:	learn: 0.0013991	total: 15m 35s	remaining: 46.5s
9351:	learn: 0.0014838	total: 15m 35s	remaining: 1m 4s
8654:	learn: 0.0013530	total: 15m 35s	remaining: 2m 25s
9346:	learn: 0.0013346	total: 15m 35s	remaining: 1m 5s
9074:	learn: 0.0016001	total: 15m 35s	remaining: 1m 35s
9526:	learn: 0.0013991	total: 15m 35s	remaining: 46.4s
9352:	learn: 0.0014838	total: 15m 35s	remaining: 1m 4s
8655:	learn: 0.0013530	total: 15m 35s	remaining: 2m 25s
9075:	learn: 0.0016001	total: 15m 35s	remaining: 1m 35s
9347:	learn: 0.0013346	total: 15m 35s	remaining: 1m 5s
9527:	learn: 0.0013991	total: 15m 35s	remaining: 46.3s
9353:	learn: 0.0014838	total: 15m 35s	remaining: 1m 4s
9076:	learn: 0.0016001	total: 15m 35s	remaining: 1m 35s
9348:	learn: 0.0013346	total: 15m 35s	remaining: 1m 5s
8656:	learn: 0.0013531	total: 15m 35s	remaining: 2m 25s
9354:	learn: 0.0014839	total: 15m 35s	remaining: 1m 4s
9528:	learn: 0.0013991	total: 15m 35s	remaining: 46.2s
9077:	learn: 0.0016001	total: 15m 35s	remaining: 1m 35s
8657:	learn: 0.0013530	total: 15m 35s	remaining: 2m 25s
9349:	learn: 0.0013346	total: 15m 35s	remaining: 1m 5s
9355:	learn: 0.0014839	total: 15m 35s	remaining: 1m 4s
9529:	learn: 0.0013991	total: 15m 35s	remaining: 46.1s
9078:	learn: 0.0016001	total: 15m 35s	remaining: 1m 34s
9356:	learn: 0.0014839	total: 15m 35s	remaining: 1m 4s
8658:	learn: 0.0013530	total: 15m 35s	remaining: 2m 24s
9350:	learn: 0.0013346	total: 15m 35s	remaining: 1m 4s
9530:	learn: 0.0013991	total: 15m 35s	remaining: 46s
8659:	learn: 0.0013530	total: 15m 35s	remaining: 2m 24s
9357:	learn: 0.0014838	total: 15m 35s	remaining: 1m 4s
9079:	learn: 0.0015996	total: 15m 35s	remaining: 1m 34s
9351:	learn: 0.0013346	total: 15m 35s	remaining: 1m 4s
9531:	learn: 0.0013991	total: 15m 35s	remaining: 45.9s
8660:	learn: 0.0013530	total: 15m 35s	remaining: 2m 24s
9358:	learn: 0.0014838	total: 15m 35s	remaining: 1m 4s
9352:	learn: 0.0013346	total: 15m 35s	remaining: 1m 4s
9080:	learn: 0.0015996	total: 15m 36s	remaining: 1m 34s
9532:	learn: 0.0013991	total: 15m 35s	remaining: 45.8s
8661:	learn: 0.0013530	total: 15m 36s	remaining: 2m 24s
9359:	learn: 0.0014838	total: 15m 35s	remaining: 1m 3s
9353:	learn: 0.0013346	total: 15m 36s	remaining: 1m 4s
9081:	learn: 0.0015996	total: 15m 36s	remaining: 1m 34s
9533:	learn: 0.0013990	total: 15m 35s	remaining: 45.7s
8662:	learn: 0.0013530	total: 15m 36s	remaining: 2m 24s
9360:	learn: 0.0014838	total: 15m 35s	remaining: 1m 3s
9354:	learn: 0.0013346	total: 15m 36s	remaining: 1m 4s

9082:	learn: 0.0015992	total: 15m 36s	remaining: 1m 34s
9534:	learn: 0.0013990	total: 15m 36s	remaining: 45.6s
9361:	learn: 0.0014838	total: 15m 36s	remaining: 1m 3s
8663:	learn: 0.0013530	total: 15m 36s	remaining: 2m 24s
9535:	learn: 0.0013990	total: 15m 36s	remaining: 45.5s
9355:	learn: 0.0013346	total: 15m 36s	remaining: 1m 4s
9083:	learn: 0.0015992	total: 15m 36s	remaining: 1m 34s
9362:	learn: 0.0014839	total: 15m 36s	remaining: 1m 3s
8664:	learn: 0.0013530	total: 15m 36s	remaining: 2m 24s
9084:	learn: 0.0015992	total: 15m 36s	remaining: 1m 34s
9536:	learn: 0.0013989	total: 15m 36s	remaining: 45.5s
9356:	learn: 0.0013346	total: 15m 36s	remaining: 1m 4s
9537:	learn: 0.0013989	total: 15m 36s	remaining: 45.4s
9363:	learn: 0.0014838	total: 15m 36s	remaining: 1m 3s
9357:	learn: 0.0013346	total: 15m 36s	remaining: 1m 4s
9085:	learn: 0.0015992	total: 15m 36s	remaining: 1m 34s
8665:	learn: 0.0013530	total: 15m 36s	remaining: 2m 24s
9538:	learn: 0.0013989	total: 15m 36s	remaining: 45.3s
9364:	learn: 0.0014839	total: 15m 36s	remaining: 1m 3s
9358:	learn: 0.0013346	total: 15m 36s	remaining: 1m 4s
9086:	learn: 0.0015992	total: 15m 36s	remaining: 1m 34s
8666:	learn: 0.0013530	total: 15m 36s	remaining: 2m 24s
9539:	learn: 0.0013989	total: 15m 36s	remaining: 45.2s
9365:	learn: 0.0014838	total: 15m 36s	remaining: 1m 3s
9359:	learn: 0.0013346	total: 15m 36s	remaining: 1m 4s
9087:	learn: 0.0015988	total: 15m 36s	remaining: 1m 34s
8667:	learn: 0.0013530	total: 15m 36s	remaining: 2m 23s
9540:	learn: 0.0013988	total: 15m 36s	remaining: 45.1s
9366:	learn: 0.0014839	total: 15m 36s	remaining: 1m 3s
9360:	learn: 0.0013342	total: 15m 36s	remaining: 1m 3s
9088:	learn: 0.0015988	total: 15m 36s	remaining: 1m 33s
8668:	learn: 0.0013530	total: 15m 36s	remaining: 2m 23s
9541:	learn: 0.0013988	total: 15m 36s	remaining: 45s
9367:	learn: 0.0014839	total: 15m 36s	remaining: 1m 3s
9361:	learn: 0.0013342	total: 15m 36s	remaining: 1m 3s
9089:	learn: 0.0015989	total: 15m 36s	remaining: 1m 33s
8669:	learn: 0.0013531	total: 15m 36s	remaining: 2m 23s
9542:	learn: 0.0013988	total: 15m 36s	remaining: 44.9s
9368:	learn: 0.0014839	total: 15m 36s	remaining: 1m 3s
9362:	learn: 0.0013342	total: 15m 36s	remaining: 1m 3s
9090:	learn: 0.0015989	total: 15m 37s	remaining: 1m 33s
9543:	learn: 0.0013988	total: 15m 36s	remaining: 44.8s
8670:	learn: 0.0013530	total: 15m 37s	remaining: 2m 23s
9363:	learn: 0.0013342	total: 15m 37s	remaining: 1m 3s
9369:	learn: 0.0014839	total: 15m 36s	remaining: 1m 2s
9091:	learn: 0.0015988	total: 15m 37s	remaining: 1m 33s
9544:	learn: 0.0013988	total: 15m 36s	remaining: 44.7s
8671:	learn: 0.0013530	total: 15m 37s	remaining: 2m 23s
9364:	learn: 0.0013342	total: 15m 37s	remaining: 1m 3s
9092:	learn: 0.0015986	total: 15m 37s	remaining: 1m 33s
9370:	learn: 0.0014838	total: 15m 36s	remaining: 1m 2s
9545:	learn: 0.0013984	total: 15m 37s	remaining: 44.6s
9365:	learn: 0.0013342	total: 15m 37s	remaining: 1m 3s
8672:	learn: 0.0013530	total: 15m 37s	remaining: 2m 23s
9546:	learn: 0.0013984	total: 15m 37s	remaining: 44.5s
9093:	learn: 0.0015986	total: 15m 37s	remaining: 1m 33s
9371:	learn: 0.0014839	total: 15m 37s	remaining: 1m 2s
9366:	learn: 0.0013342	total: 15m 37s	remaining: 1m 3s
8673:	learn: 0.0013530	total: 15m 37s	remaining: 2m 23s
9547:	learn: 0.0013984	total: 15m 37s	remaining: 44.4s
9372:	learn: 0.0014838	total: 15m 37s	remaining: 1m 2s
9094:	learn: 0.0015983	total: 15m 37s	remaining: 1m 33s
9367:	learn: 0.0013342	total: 15m 37s	remaining: 1m 3s
8674:	learn: 0.0013530	total: 15m 37s	remaining: 2m 23s
9548:	learn: 0.0013983	total: 15m 37s	remaining: 44.3s
9368:	learn: 0.0013342	total: 15m 37s	remaining: 1m 3s
9095:	learn: 0.0015978	total: 15m 37s	remaining: 1m 33s
9373:	learn: 0.0014838	total: 15m 37s	remaining: 1m 2s
9549:	learn: 0.0013983	total: 15m 37s	remaining: 44.2s
8675:	learn: 0.0013530	total: 15m 37s	remaining: 2m 23s
9096:	learn: 0.0015978	total: 15m 37s	remaining: 1m 33s
9374:	learn: 0.0014838	total: 15m 37s	remaining: 1m 2s
9369:	learn: 0.0013342	total: 15m 37s	remaining: 1m 3s
9550:	learn: 0.0013983	total: 15m 37s	remaining: 44.1s
8676:	learn: 0.0013530	total: 15m 37s	remaining: 2m 22s
9375:	learn: 0.0014838	total: 15m 37s	remaining: 1m 2s
9097:	learn: 0.0015978	total: 15m 37s	remaining: 1m 32s
9370:	learn: 0.0013342	total: 15m 37s	remaining: 1m 2s
9551:	learn: 0.0013982	total: 15m 37s	remaining: 44s
9098:	learn: 0.0015978	total: 15m 37s	remaining: 1m 32s
8677:	learn: 0.0013531	total: 15m 37s	remaining: 2m 22s
9376:	learn: 0.0014838	total: 15m 37s	remaining: 1m 2s
9371:	learn: 0.0013342	total: 15m 37s	remaining: 1m 2s
9552:	learn: 0.0013982	total: 15m 37s	remaining: 43.9s
9099:	learn: 0.0015978	total: 15m 37s	remaining: 1m 32s
9377:	learn: 0.0014838	total: 15m 37s	remaining: 1m 2s
9372:	learn: 0.0013342	total: 15m 37s	remaining: 1m 2s
8678:	learn: 0.0013531	total: 15m 37s	remaining: 2m 22s
9553:	learn: 0.0013982	total: 15m 37s	remaining: 43.8s
9100:	learn: 0.0015978	total: 15m 38s	remaining: 1m 32s
9373:	learn: 0.0013342	total: 15m 38s	remaining: 1m 2s
9554:	learn: 0.0013982	total: 15m 37s	remaining: 43.7s
9378:	learn: 0.0014838	total: 15m 37s	remaining: 1m 2s
8679:	learn: 0.0013530	total: 15m 38s	remaining: 2m 22s
9101:	learn: 0.0015978	total: 15m 38s	remaining: 1m 32s
9374:	learn: 0.0013342	total: 15m 38s	remaining: 1m 2s
9555:	learn: 0.0013982	total: 15m 37s	remaining: 43.6s
8680:	learn: 0.0013530	total: 15m 38s	remaining: 2m 22s
9379:	learn: 0.0014838	total: 15m 37s	remaining: 1m 1s
9102:	learn: 0.0015978	total: 15m 38s	remaining: 1m 32s
9556:	learn: 0.0013982	total: 15m 38s	remaining: 43.5s
9380:	learn: 0.0014832	total: 15m 38s	remaining: 1m 1s
9375:	learn: 0.0013342	total: 15m 38s	remaining: 1m 2s
8681:	learn: 0.0013530	total: 15m 38s	remaining: 2m 22s
9103:	learn: 0.0015978	total: 15m 38s	remaining: 1m 32s
9557:	learn: 0.0013982	total: 15m 38s	remaining: 43.4s
9381:	learn: 0.0014832	total: 15m 38s	remaining: 1m 1s
9376:	learn: 0.0013342	total: 15m 38s	remaining: 1m 2s
8682:	learn: 0.0013530	total: 15m 38s	remaining: 2m 22s
9558:	learn: 0.0013982	total: 15m 38s	remaining: 43.3s
9104:	learn: 0.0015978	total: 15m 38s	remaining: 1m 32s
9382:	learn: 0.0014832	total: 15m 38s	remaining: 1m 1s
9377:	learn: 0.0013342	total: 15m 38s	remaining: 1m 2s
8683:	learn: 0.0013530	total: 15m 38s	remaining: 2m 22s
9559:	learn: 0.0013982	total: 15m 38s	remaining: 43.2s
9105:	learn: 0.0015978	total: 15m 38s	remaining: 1m 32s
9383:	learn: 0.0014832	total: 15m 38s	remaining: 1m 1s
8684:	learn: 0.0013530	total: 15m 38s	remaining: 2m 22s
9378:	learn: 0.0013342	total: 15m 38s	remaining: 1m 2s
9560:	learn: 0.0013982	total: 15m 38s	remaining: 43.1s
9384:	learn: 0.0014832	total: 15m 38s	remaining: 1m 1s
9106:	learn: 0.0015978	total: 15m 38s	remaining: 1m 32s
9561:	learn: 0.0013982	total: 15m 38s	remaining: 43s
8685:	learn: 0.0013530	total: 15m 38s	remaining: 2m 22s
9379:	learn: 0.0013342	total: 15m 38s	remaining: 1m 2s
9562:	learn: 0.0013982	total: 15m 38s	remaining: 42.9s
9385:	learn: 0.0014832	total: 15m 38s	remaining: 1m 1s
9107:	learn: 0.0015978	total: 15m 38s	remaining: 1m 31s
8686:	learn: 0.0013530	total: 15m 38s	remaining: 2m 21s
9380:	learn: 0.0013342	total: 15m 38s	remaining: 1m 1s
9563:	learn: 0.0013982	total: 15m 38s	remaining: 42.8s
9386:	learn: 0.0014832	total: 15m 38s	remaining: 1m 1s
9381:	learn: 0.0013342	total: 15m 38s	remaining: 1m 1s
8687:	learn: 0.0013530	total: 15m 38s	remaining: 2m 21s
9108:	learn: 0.0015978	total: 15m 38s	remaining: 1m 31s
9564:	learn: 0.0013982	total: 15m 38s	remaining: 42.7s
9387:	learn: 0.0014832	total: 15m 38s	remaining: 1m 1s
9382:	learn: 0.0013342	total: 15m 38s	remaining: 1m 1s
9109:	learn: 0.0015978	total: 15m 39s	remaining: 1m 31s
8688:	learn: 0.0013530	total: 15m 39s	remaining: 2m 21s
9565:	learn: 0.0013982	total: 15m 38s	remaining: 42.6s
9388:	learn: 0.0014832	total: 15m 38s	remaining: 1m 1s
9110:	learn: 0.0015978	total: 15m 39s	remaining: 1m 31s
9383:	learn: 0.0013342	total: 15m 39s	remaining: 1m 1s
9389:	learn: 0.0014832	total: 15m 38s	remaining: 1m
9566:	learn: 0.0013982	total: 15m 38s	remaining: 42.5s
8689:	learn: 0.0013530	total: 15m 39s	remaining: 2m 21s
9384:	learn: 0.0013339	total: 15m 39s	remaining: 1m 1s
9111:	learn: 0.0015978	total: 15m 39s	remaining: 1m 31s
9390:	learn: 0.0014832	total: 15m 38s	remaining: 1m
9567:	learn: 0.0013982	total: 15m 39s	remaining: 42.4s
8690:	learn: 0.0013530	total: 15m 39s	remaining: 2m 21s
9112:	learn: 0.0015978	total: 15m 39s	remaining: 1m 31s
9385:	learn: 0.0013339	total: 15m 39s	remaining: 1m 1s
9568:	learn: 0.0013982	total: 15m 39s	remaining: 42.3s
9391:	learn: 0.0014832	total: 15m 39s	remaining: 1m
8691:	learn: 0.0013530	total: 15m 39s	remaining: 2m 21s
9392:	learn: 0.0014832	total: 15m 39s	remaining: 1m
9113:	learn: 0.0015978	total: 15m 39s	remaining: 1m 31s
9569:	learn: 0.0013982	total: 15m 39s	remaining: 42.2s
9386:	learn: 0.0013339	total: 15m 39s	remaining: 1m 1s
8692:	learn: 0.0013530	total: 15m 39s	remaining: 2m 21s
9393:	learn: 0.0014832	total: 15m 39s	remaining: 1m
9114:	learn: 0.0015978	total: 15m 39s	remaining: 1m 31s
9570:	learn: 0.0013982	total: 15m 39s	remaining: 42.1s
9387:	learn: 0.0013339	total: 15m 39s	remaining: 1m 1s
8693:	learn: 0.0013530	total: 15m 39s	remaining: 2m 21s
9394:	learn: 0.0014832	total: 15m 39s	remaining: 1m
9115:	learn: 0.0015978	total: 15m 39s	remaining: 1m 31s
9571:	learn: 0.0013982	total: 15m 39s	remaining: 42s
8694:	learn: 0.0013530	total: 15m 39s	remaining: 2m 21s
9388:	learn: 0.0013339	total: 15m 39s	remaining: 1m 1s
9116:	learn: 0.0015978	total: 15m 39s	remaining: 1m 31s
9395:	learn: 0.0014832	total: 15m 39s	remaining: 1m
8695:	learn: 0.0013530	total: 15m 39s	remaining: 2m 20s
9572:	learn: 0.0013982	total: 15m 39s	remaining: 41.9s
9389:	learn: 0.0013339	total: 15m 39s	remaining: 1m 1s
9117:	learn: 0.0015978	total: 15m 39s	remaining: 1m 30s
9396:	learn: 0.0014832	total: 15m 39s	remaining: 1m
9573:	learn: 0.0013982	total: 15m 39s	remaining: 41.8s
8696:	learn: 0.0013530	total: 15m 39s	remaining: 2m 20s
9390:	learn: 0.0013339	total: 15m 39s	remaining: 1m
9118:	learn: 0.0015978	total: 15m 39s	remaining: 1m 30s
9397:	learn: 0.0014832	total: 15m 39s	remaining: 1m
8697:	learn: 0.0013530	total: 15m 39s	remaining: 2m 20s
9574:	learn: 0.0013982	total: 15m 39s	remaining: 41.7s
9391:	learn: 0.0013339	total: 15m 39s	remaining: 1m
9398:	learn: 0.0014832	total: 15m 39s	remaining: 1m
9119:	learn: 0.0015978	total: 15m 40s	remaining: 1m 30s
9575:	learn: 0.0013982	total: 15m 39s	remaining: 41.6s
8698:	learn: 0.0013530	total: 15m 40s	remaining: 2m 20s
9399:	learn: 0.0014832	total: 15m 39s	remaining: 60s
9392:	learn: 0.0013339	total: 15m 40s	remaining: 1m
9120:	learn: 0.0015978	total: 15m 40s	remaining: 1m 30s
9576:	learn: 0.0013982	total: 15m 39s	remaining: 41.5s
9400:	learn: 0.0014832	total: 15m 39s	remaining: 59.9s
8699:	learn: 0.0013530	total: 15m 40s	remaining: 2m 20s
9393:	learn: 0.0013339	total: 15m 40s	remaining: 1m
9121:	learn: 0.0015978	total: 15m 40s	remaining: 1m 30s
9577:	learn: 0.0013982	total: 15m 40s	remaining: 41.4s
9401:	learn: 0.0014832	total: 15m 39s	remaining: 59.8s
8700:	learn: 0.0013530	total: 15m 40s	remaining: 2m 20s
9394:	learn: 0.0013339	total: 15m 40s	remaining: 1m
9122:	learn: 0.0015978	total: 15m 40s	remaining: 1m 30s
9578:	learn: 0.0013982	total: 15m 40s	remaining: 41.3s
8701:	learn: 0.0013530	total: 15m 40s	remaining: 2m 20s
9402:	learn: 0.0014832	total: 15m 40s	remaining: 59.7s
9123:	learn: 0.0015978	total: 15m 40s	remaining: 1m 30s
9395:	learn: 0.0013339	total: 15m 40s	remaining: 1m
9579:	learn: 0.0013982	total: 15m 40s	remaining: 41.2s
9403:	learn: 0.0014832	total: 15m 40s	remaining: 59.6s
8702:	learn: 0.0013530	total: 15m 40s	remaining: 2m 20s
9396:	learn: 0.0013339	total: 15m 40s	remaining: 1m
9124:	learn: 0.0015978	total: 15m 40s	remaining: 1m 30s
9580:	learn: 0.0013982	total: 15m 40s	remaining: 41.1s
9404:	learn: 0.0014832	total: 15m 40s	remaining: 59.5s
9397:	learn: 0.0013339	total: 15m 40s	remaining: 1m
9581:	learn: 0.0013982	total: 15m 40s	remaining: 41s
8703:	learn: 0.0013529	total: 15m 40s	remaining: 2m 20s
9125:	learn: 0.0015974	total: 15m 40s	remaining: 1m 30s
9405:	learn: 0.0014832	total: 15m 40s	remaining: 59.4s
9398:	learn: 0.0013339	total: 15m 40s	remaining: 1m
8704:	learn: 0.0013529	total: 15m 40s	remaining: 2m 19s
9126:	learn: 0.0015975	total: 15m 40s	remaining: 1m 29s
9582:	learn: 0.0013982	total: 15m 40s	remaining: 40.9s
9399:	learn: 0.0013339	total: 15m 40s	remaining: 1m
9406:	learn: 0.0014832	total: 15m 40s	remaining: 59.3s
8705:	learn: 0.0013529	total: 15m 40s	remaining: 2m 19s
9583:	learn: 0.0013982	total: 15m 40s	remaining: 40.8s
9127:	learn: 0.0015974	total: 15m 40s	remaining: 1m 29s
9400:	learn: 0.0013339	total: 15m 40s	remaining: 59.9s
9407:	learn: 0.0014832	total: 15m 40s	remaining: 59.2s
8706:	learn: 0.0013528	total: 15m 40s	remaining: 2m 19s
9584:	learn: 0.0013982	total: 15m 40s	remaining: 40.7s
9401:	learn: 0.0013339	total: 15m 40s	remaining: 59.8s
8707:	learn: 0.0013528	total: 15m 40s	remaining: 2m 19s
9128:	learn: 0.0015974	total: 15m 40s	remaining: 1m 29s
9408:	learn: 0.0014832	total: 15m 40s	remaining: 59.1s
9585:	learn: 0.0013982	total: 15m 40s	remaining: 40.6s
9402:	learn: 0.0013339	total: 15m 40s	remaining: 59.7s
8708:	learn: 0.0013528	total: 15m 41s	remaining: 2m 19s
9129:	learn: 0.0015975	total: 15m 41s	remaining: 1m 29s
9409:	learn: 0.0014832	total: 15m 40s	remaining: 59s
9586:	learn: 0.0013982	total: 15m 40s	remaining: 40.5s
9130:	learn: 0.0015974	total: 15m 41s	remaining: 1m 29s
9403:	learn: 0.0013339	total: 15m 41s	remaining: 59.6s
8709:	learn: 0.0013528	total: 15m 41s	remaining: 2m 19s
9410:	learn: 0.0014832	total: 15m 40s	remaining: 58.9s
9587:	learn: 0.0013982	total: 15m 40s	remaining: 40.4s
9131:	learn: 0.0015975	total: 15m 41s	remaining: 1m 29s
9404:	learn: 0.0013336	total: 15m 41s	remaining: 59.5s
8710:	learn: 0.0013528	total: 15m 41s	remaining: 2m 19s
9588:	learn: 0.0013982	total: 15m 41s	remaining: 40.3s
9411:	learn: 0.0014832	total: 15m 41s	remaining: 58.8s
9132:	learn: 0.0015975	total: 15m 41s	remaining: 1m 29s
9405:	learn: 0.0013336	total: 15m 41s	remaining: 59.4s
8711:	learn: 0.0013528	total: 15m 41s	remaining: 2m 19s
9589:	learn: 0.0013982	total: 15m 41s	remaining: 40.2s
9412:	learn: 0.0014832	total: 15m 41s	remaining: 58.7s
9133:	learn: 0.0015975	total: 15m 41s	remaining: 1m 29s
9590:	learn: 0.0013982	total: 15m 41s	remaining: 40.1s
9413:	learn: 0.0014832	total: 15m 41s	remaining: 58.6s
9406:	learn: 0.0013336	total: 15m 41s	remaining: 59.3s
8712:	learn: 0.0013528	total: 15m 41s	remaining: 2m 19s
9134:	learn: 0.0015975	total: 15m 41s	remaining: 1m 29s
8713:	learn: 0.0013528	total: 15m 41s	remaining: 2m 18s
9591:	learn: 0.0013982	total: 15m 41s	remaining: 40s
9414:	learn: 0.0014832	total: 15m 41s	remaining: 58.5s
9407:	learn: 0.0013336	total: 15m 41s	remaining: 59.2s
8714:	learn: 0.0013528	total: 15m 41s	remaining: 2m 18s
9135:	learn: 0.0015974	total: 15m 41s	remaining: 1m 29s
9592:	learn: 0.0013982	total: 15m 41s	remaining: 39.9s
9415:	learn: 0.0014827	total: 15m 41s	remaining: 58.4s
9593:	learn: 0.0013982	total: 15m 41s	remaining: 39.8s
9408:	learn: 0.0013336	total: 15m 41s	remaining: 59.1s
9136:	learn: 0.0015975	total: 15m 41s	remaining: 1m 28s
8715:	learn: 0.0013528	total: 15m 41s	remaining: 2m 18s
9416:	learn: 0.0014827	total: 15m 41s	remaining: 58.3s
9594:	learn: 0.0013982	total: 15m 41s	remaining: 39.7s
8716:	learn: 0.0013528	total: 15m 41s	remaining: 2m 18s
9409:	learn: 0.0013336	total: 15m 41s	remaining: 59s
9137:	learn: 0.0015974	total: 15m 41s	remaining: 1m 28s
9595:	learn: 0.0013982	total: 15m 41s	remaining: 39.6s
9417:	learn: 0.0014827	total: 15m 41s	remaining: 58.2s
8717:	learn: 0.0013528	total: 15m 41s	remaining: 2m 18s
9410:	learn: 0.0013336	total: 15m 41s	remaining: 59s
9138:	learn: 0.0015974	total: 15m 41s	remaining: 1m 28s
9596:	learn: 0.0013982	total: 15m 41s	remaining: 39.5s
9418:	learn: 0.0014827	total: 15m 41s	remaining: 58.1s
8718:	learn: 0.0013528	total: 15m 42s	remaining: 2m 18s
9139:	learn: 0.0015975	total: 15m 42s	remaining: 1m 28s
9597:	learn: 0.0013982	total: 15m 41s	remaining: 39.4s
9411:	learn: 0.0013336	total: 15m 42s	remaining: 58.9s
9419:	learn: 0.0014827	total: 15m 41s	remaining: 58s
8719:	learn: 0.0013528	total: 15m 42s	remaining: 2m 18s
9598:	learn: 0.0013982	total: 15m 41s	remaining: 39.3s
9140:	learn: 0.0015975	total: 15m 42s	remaining: 1m 28s

9412:	learn: 0.0013336	total: 15m 42s	remaining: 58.8s
8720:	learn: 0.0013528	total: 15m 42s	remaining: 2m 18s
9599:	learn: 0.0013982	total: 15m 42s	remaining: 39.3s
9420:	learn: 0.0014827	total: 15m 41s	remaining: 57.9s
9141:	learn: 0.0015974	total: 15m 42s	remaining: 1m 28s
9413:	learn: 0.0013336	total: 15m 42s	remaining: 58.7s
9600:	learn: 0.0013982	total: 15m 42s	remaining: 39.2s
8721:	learn: 0.0013528	total: 15m 42s	remaining: 2m 18s
9414:	learn: 0.0013336	total: 15m 42s	remaining: 58.5s
9142:	learn: 0.0015974	total: 15m 42s	remaining: 1m 28s
9421:	learn: 0.0014827	total: 15m 42s	remaining: 57.8s
9601:	learn: 0.0013982	total: 15m 42s	remaining: 39.1s
8722:	learn: 0.0013528	total: 15m 42s	remaining: 2m 17s
9415:	learn: 0.0013336	total: 15m 42s	remaining: 58.4s
9143:	learn: 0.0015971	total: 15m 42s	remaining: 1m 28s
9422:	learn: 0.0014827	total: 15m 42s	remaining: 57.7s
9602:	learn: 0.0013982	total: 15m 42s	remaining: 39s
9144:	learn: 0.0015970	total: 15m 42s	remaining: 1m 28s
9416:	learn: 0.0013336	total: 15m 42s	remaining: 58.3s
8723:	learn: 0.0013528	total: 15m 42s	remaining: 2m 17s
9423:	learn: 0.0014827	total: 15m 42s	remaining: 57.6s
9603:	learn: 0.0013982	total: 15m 42s	remaining: 38.9s
9145:	learn: 0.0015971	total: 15m 42s	remaining: 1m 28s
9417:	learn: 0.0013336	total: 15m 42s	remaining: 58.2s
8724:	learn: 0.0013528	total: 15m 42s	remaining: 2m 17s
9424:	learn: 0.0014827	total: 15m 42s	remaining: 57.5s
9418:	learn: 0.0013336	total: 15m 42s	remaining: 58.1s
9604:	learn: 0.0013982	total: 15m 42s	remaining: 38.8s
9146:	learn: 0.0015970	total: 15m 42s	remaining: 1m 27s
8725:	learn: 0.0013528	total: 15m 42s	remaining: 2m 17s
9425:	learn: 0.0014827	total: 15m 42s	remaining: 57.4s
9605:	learn: 0.0013982	total: 15m 42s	remaining: 38.7s
9147:	learn: 0.0015970	total: 15m 42s	remaining: 1m 27s
9419:	learn: 0.0013336	total: 15m 42s	remaining: 58s
8726:	learn: 0.0013528	total: 15m 42s	remaining: 2m 17s
9420:	learn: 0.0013336	total: 15m 42s	remaining: 57.9s
9148:	learn: 0.0015965	total: 15m 42s	remaining: 1m 27s
9606:	learn: 0.0013978	total: 15m 42s	remaining: 38.6s
9426:	learn: 0.0014827	total: 15m 42s	remaining: 57.3s
8727:	learn: 0.0013528	total: 15m 42s	remaining: 2m 17s
9607:	learn: 0.0013978	total: 15m 42s	remaining: 38.5s
9149:	learn: 0.0015965	total: 15m 43s	remaining: 1m 27s
9421:	learn: 0.0013336	total: 15m 42s	remaining: 57.8s
9427:	learn: 0.0014827	total: 15m 42s	remaining: 57.2s
9608:	learn: 0.0013978	total: 15m 42s	remaining: 38.4s
8728:	learn: 0.0013528	total: 15m 43s	remaining: 2m 17s
9150:	learn: 0.0015965	total: 15m 43s	remaining: 1m 27s
9422:	learn: 0.0013336	total: 15m 43s	remaining: 57.7s
9428:	learn: 0.0014827	total: 15m 42s	remaining: 57.1s
9609:	learn: 0.0013978	total: 15m 42s	remaining: 38.3s
8729:	learn: 0.0013529	total: 15m 43s	remaining: 2m 17s
9151:	learn: 0.0015965	total: 15m 43s	remaining: 1m 27s
9423:	learn: 0.0013336	total: 15m 43s	remaining: 57.6s
9429:	learn: 0.0014826	total: 15m 42s	remaining: 57s
9610:	learn: 0.0013978	total: 15m 43s	remaining: 38.2s
9152:	learn: 0.0015965	total: 15m 43s	remaining: 1m 27s
8730:	learn: 0.0013527	total: 15m 43s	remaining: 2m 17s
9424:	learn: 0.0013336	total: 15m 43s	remaining: 57.5s
9430:	learn: 0.0014827	total: 15m 43s	remaining: 56.9s
9611:	learn: 0.0013978	total: 15m 43s	remaining: 38.1s
9153:	learn: 0.0015965	total: 15m 43s	remaining: 1m 27s
9425:	learn: 0.0013336	total: 15m 43s	remaining: 57.4s
9431:	learn: 0.0014827	total: 15m 43s	remaining: 56.8s
9612:	learn: 0.0013978	total: 15m 43s	remaining: 38s
8731:	learn: 0.0013527	total: 15m 43s	remaining: 2m 17s
9154:	learn: 0.0015965	total: 15m 43s	remaining: 1m 27s
9426:	learn: 0.0013336	total: 15m 43s	remaining: 57.3s
9432:	learn: 0.0014824	total: 15m 43s	remaining: 56.7s
9613:	learn: 0.0013978	total: 15m 43s	remaining: 37.9s
9155:	learn: 0.0015965	total: 15m 43s	remaining: 1m 26s
8732:	learn: 0.0013527	total: 15m 43s	remaining: 2m 16s
9427:	learn: 0.0013336	total: 15m 43s	remaining: 57.2s
9614:	learn: 0.0013978	total: 15m 43s	remaining: 37.8s
9433:	learn: 0.0014823	total: 15m 43s	remaining: 56.6s
9156:	learn: 0.0015965	total: 15m 43s	remaining: 1m 26s
9428:	learn: 0.0013336	total: 15m 43s	remaining: 57.1s
8733:	learn: 0.0013525	total: 15m 43s	remaining: 2m 16s
9615:	learn: 0.0013978	total: 15m 43s	remaining: 37.7s
9157:	learn: 0.0015965	total: 15m 43s	remaining: 1m 26s
9434:	learn: 0.0014820	total: 15m 43s	remaining: 56.5s
8734:	learn: 0.0013525	total: 15m 43s	remaining: 2m 16s
9429:	learn: 0.0013336	total: 15m 43s	remaining: 57s
9435:	learn: 0.0014820	total: 15m 43s	remaining: 56.4s
9616:	learn: 0.0013978	total: 15m 43s	remaining: 37.6s
9158:	learn: 0.0015965	total: 15m 43s	remaining: 1m 26s
8735:	learn: 0.0013525	total: 15m 43s	remaining: 2m 16s
9436:	learn: 0.0014819	total: 15m 43s	remaining: 56.3s
9430:	learn: 0.0013335	total: 15m 43s	remaining: 56.9s
9617:	learn: 0.0013978	total: 15m 43s	remaining: 37.5s
9159:	learn: 0.0015965	total: 15m 43s	remaining: 1m 26s
8736:	learn: 0.0013525	total: 15m 44s	remaining: 2m 16s
9437:	learn: 0.0014819	total: 15m 43s	remaining: 56.2s
9160:	learn: 0.0015965	total: 15m 44s	remaining: 1m 26s
9431:	learn: 0.0013335	total: 15m 44s	remaining: 56.8s
9618:	learn: 0.0013978	total: 15m 43s	remaining: 37.4s
8737:	learn: 0.0013525	total: 15m 44s	remaining: 2m 16s
9161:	learn: 0.0015965	total: 15m 44s	remaining: 1m 26s
9432:	learn: 0.0013336	total: 15m 44s	remaining: 56.7s
9619:	learn: 0.0013978	total: 15m 43s	remaining: 37.3s
9438:	learn: 0.0014819	total: 15m 43s	remaining: 56.1s
8738:	learn: 0.0013525	total: 15m 44s	remaining: 2m 16s
9162:	learn: 0.0015965	total: 15m 44s	remaining: 1m 26s
9433:	learn: 0.0013336	total: 15m 44s	remaining: 56.6s
9439:	learn: 0.0014819	total: 15m 43s	remaining: 56s
9620:	learn: 0.0013978	total: 15m 44s	remaining: 37.2s
9163:	learn: 0.0015962	total: 15m 44s	remaining: 1m 26s
8739:	learn: 0.0013525	total: 15m 44s	remaining: 2m 16s
9440:	learn: 0.0014819	total: 15m 44s	remaining: 55.9s
9434:	learn: 0.0013335	total: 15m 44s	remaining: 56.5s
9164:	learn: 0.0015962	total: 15m 44s	remaining: 1m 26s
9621:	learn: 0.0013978	total: 15m 44s	remaining: 37.1s
8740:	learn: 0.0013525	total: 15m 44s	remaining: 2m 16s
9435:	learn: 0.0013335	total: 15m 44s	remaining: 56.4s
9441:	learn: 0.0014819	total: 15m 44s	remaining: 55.8s
9622:	learn: 0.0013978	total: 15m 44s	remaining: 37s
9165:	learn: 0.0015961	total: 15m 44s	remaining: 1m 25s
9442:	learn: 0.0014819	total: 15m 44s	remaining: 55.7s
8741:	learn: 0.0013525	total: 15m 44s	remaining: 2m 15s
9436:	learn: 0.0013335	total: 15m 44s	remaining: 56.3s
9623:	learn: 0.0013978	total: 15m 44s	remaining: 36.9s
9166:	learn: 0.0015962	total: 15m 44s	remaining: 1m 25s
9443:	learn: 0.0014819	total: 15m 44s	remaining: 55.6s
9437:	learn: 0.0013335	total: 15m 44s	remaining: 56.2s
9624:	learn: 0.0013974	total: 15m 44s	remaining: 36.8s
9167:	learn: 0.0015961	total: 15m 44s	remaining: 1m 25s
8742:	learn: 0.0013525	total: 15m 44s	remaining: 2m 15s
9444:	learn: 0.0014819	total: 15m 44s	remaining: 55.5s
9625:	learn: 0.0013974	total: 15m 44s	remaining: 36.7s
9438:	learn: 0.0013335	total: 15m 44s	remaining: 56.1s
9168:	learn: 0.0015962	total: 15m 44s	remaining: 1m 25s
8743:	learn: 0.0013525	total: 15m 44s	remaining: 2m 15s
9626:	learn: 0.0013974	total: 15m 44s	remaining: 36.6s
9445:	learn: 0.0014819	total: 15m 44s	remaining: 55.4s
9439:	learn: 0.0013335	total: 15m 44s	remaining: 56s
9627:	learn: 0.0013974	total: 15m 44s	remaining: 36.5s
9169:	learn: 0.0015961	total: 15m 44s	remaining: 1m 25s
8744:	learn: 0.0013522	total: 15m 44s	remaining: 2m 15s
9446:	learn: 0.0014819	total: 15m 44s	remaining: 55.3s
9628:	learn: 0.0013974	total: 15m 44s	remaining: 36.4s
9440:	learn: 0.0013335	total: 15m 44s	remaining: 56s
8745:	learn: 0.0013522	total: 15m 45s	remaining: 2m 15s
9170:	learn: 0.0015961	total: 15m 45s	remaining: 1m 25s
9629:	learn: 0.0013974	total: 15m 44s	remaining: 36.3s
9447:	learn: 0.0014819	total: 15m 44s	remaining: 55.2s
9171:	learn: 0.0015961	total: 15m 45s	remaining: 1m 25s
9441:	learn: 0.0013332	total: 15m 45s	remaining: 55.9s
8746:	learn: 0.0013522	total: 15m 45s	remaining: 2m 15s
9630:	learn: 0.0013971	total: 15m 44s	remaining: 36.2s
9448:	learn: 0.0014819	total: 15m 44s	remaining: 55.1s
9172:	learn: 0.0015962	total: 15m 45s	remaining: 1m 25s
9442:	learn: 0.0013332	total: 15m 45s	remaining: 55.8s
8747:	learn: 0.0013522	total: 15m 45s	remaining: 2m 15s
9631:	learn: 0.0013971	total: 15m 45s	remaining: 36.1s
9449:	learn: 0.0014819	total: 15m 45s	remaining: 55s
9173:	learn: 0.0015961	total: 15m 45s	remaining: 1m 25s
9443:	learn: 0.0013332	total: 15m 45s	remaining: 55.6s
9632:	learn: 0.0013972	total: 15m 45s	remaining: 36s
9450:	learn: 0.0014819	total: 15m 45s	remaining: 54.9s
8748:	learn: 0.0013522	total: 15m 45s	remaining: 2m 15s
9444:	learn: 0.0013332	total: 15m 45s	remaining: 55.5s
9174:	learn: 0.0015962	total: 15m 45s	remaining: 1m 25s
9633:	learn: 0.0013972	total: 15m 45s	remaining: 35.9s
8749:	learn: 0.0013522	total: 15m 45s	remaining: 2m 15s
9451:	learn: 0.0014815	total: 15m 45s	remaining: 54.8s
9445:	learn: 0.0013332	total: 15m 45s	remaining: 55.4s
9175:	learn: 0.0015962	total: 15m 45s	remaining: 1m 24s
9634:	learn: 0.0013971	total: 15m 45s	remaining: 35.8s
8750:	learn: 0.0013522	total: 15m 45s	remaining: 2m 14s
9452:	learn: 0.0014815	total: 15m 45s	remaining: 54.7s
9446:	learn: 0.0013332	total: 15m 45s	remaining: 55.4s
9635:	learn: 0.0013972	total: 15m 45s	remaining: 35.7s
9176:	learn: 0.0015962	total: 15m 45s	remaining: 1m 24s
8751:	learn: 0.0013522	total: 15m 45s	remaining: 2m 14s
9453:	learn: 0.0014815	total: 15m 45s	remaining: 54.6s
9636:	learn: 0.0013971	total: 15m 45s	remaining: 35.6s
9447:	learn: 0.0013332	total: 15m 45s	remaining: 55.3s
9177:	learn: 0.0015962	total: 15m 45s	remaining: 1m 24s
8752:	learn: 0.0013522	total: 15m 45s	remaining: 2m 14s
9454:	learn: 0.0014815	total: 15m 45s	remaining: 54.5s
9637:	learn: 0.0013972	total: 15m 45s	remaining: 35.5s
8753:	learn: 0.0013522	total: 15m 45s	remaining: 2m 14s
9178:	learn: 0.0015962	total: 15m 45s	remaining: 1m 24s
9448:	learn: 0.0013332	total: 15m 45s	remaining: 55.2s
9455:	learn: 0.0014815	total: 15m 45s	remaining: 54.4s
9638:	learn: 0.0013972	total: 15m 45s	remaining: 35.4s
9449:	learn: 0.0013332	total: 15m 45s	remaining: 55s
9456:	learn: 0.0014815	total: 15m 45s	remaining: 54.3s
8754:	learn: 0.0013522	total: 15m 45s	remaining: 2m 14s
9179:	learn: 0.0015962	total: 15m 45s	remaining: 1m 24s
9450:	learn: 0.0013332	total: 15m 45s	remaining: 54.9s
9457:	learn: 0.0014815	total: 15m 45s	remaining: 54.2s
9639:	learn: 0.0013972	total: 15m 45s	remaining: 35.3s
9180:	learn: 0.0015961	total: 15m 46s	remaining: 1m 24s
8755:	learn: 0.0013522	total: 15m 46s	remaining: 2m 14s
9451:	learn: 0.0013332	total: 15m 46s	remaining: 54.8s
9458:	learn: 0.0014815	total: 15m 45s	remaining: 54.1s
9640:	learn: 0.0013972	total: 15m 45s	remaining: 35.2s
9181:	learn: 0.0015962	total: 15m 46s	remaining: 1m 24s
8756:	learn: 0.0013522	total: 15m 46s	remaining: 2m 14s
9459:	learn: 0.0014815	total: 15m 45s	remaining: 54s
9452:	learn: 0.0013332	total: 15m 46s	remaining: 54.7s
9641:	learn: 0.0013971	total: 15m 46s	remaining: 35.1s
8757:	learn: 0.0013522	total: 15m 46s	remaining: 2m 14s
9182:	learn: 0.0015961	total: 15m 46s	remaining: 1m 24s
9460:	learn: 0.0014815	total: 15m 46s	remaining: 53.9s
9453:	learn: 0.0013332	total: 15m 46s	remaining: 54.6s
9642:	learn: 0.0013971	total: 15m 46s	remaining: 35s
8758:	learn: 0.0013522	total: 15m 46s	remaining: 2m 14s
9183:	learn: 0.0015961	total: 15m 46s	remaining: 1m 24s
9461:	learn: 0.0014815	total: 15m 46s	remaining: 53.8s
9454:	learn: 0.0013332	total: 15m 46s	remaining: 54.5s
9643:	learn: 0.0013971	total: 15m 46s	remaining: 34.9s
8759:	learn: 0.0013522	total: 15m 46s	remaining: 2m 13s
9184:	learn: 0.0015961	total: 15m 46s	remaining: 1m 23s
9462:	learn: 0.0014815	total: 15m 46s	remaining: 53.7s
9644:	learn: 0.0013972	total: 15m 46s	remaining: 34.8s
9455:	learn: 0.0013332	total: 15m 46s	remaining: 54.5s
9185:	learn: 0.0015961	total: 15m 46s	remaining: 1m 23s
8760:	learn: 0.0013522	total: 15m 46s	remaining: 2m 13s
9463:	learn: 0.0014815	total: 15m 46s	remaining: 53.6s
9645:	learn: 0.0013972	total: 15m 46s	remaining: 34.7s
9456:	learn: 0.0013332	total: 15m 46s	remaining: 54.4s
8761:	learn: 0.0013522	total: 15m 46s	remaining: 2m 13s
9464:	learn: 0.0014815	total: 15m 46s	remaining: 53.5s
9186:	learn: 0.0015961	total: 15m 46s	remaining: 1m 23s
9457:	learn: 0.0013332	total: 15m 46s	remaining: 54.3s
9646:	learn: 0.0013972	total: 15m 46s	remaining: 34.6s
8762:	learn: 0.0013522	total: 15m 46s	remaining: 2m 13s
9465:	learn: 0.0014815	total: 15m 46s	remaining: 53.4s
9647:	learn: 0.0013972	total: 15m 46s	remaining: 34.5s
9187:	learn: 0.0015961	total: 15m 46s	remaining: 1m 23s
9458:	learn: 0.0013332	total: 15m 46s	remaining: 54.2s
9466:	learn: 0.0014815	total: 15m 46s	remaining: 53.3s
8763:	learn: 0.0013522	total: 15m 46s	remaining: 2m 13s
9648:	learn: 0.0013972	total: 15m 46s	remaining: 34.4s
9188:	learn: 0.0015961	total: 15m 46s	remaining: 1m 23s
9459:	learn: 0.0013332	total: 15m 46s	remaining: 54s
9467:	learn: 0.0014815	total: 15m 46s	remaining: 53.2s
9649:	learn: 0.0013971	total: 15m 46s	remaining: 34.3s
9189:	learn: 0.0015961	total: 15m 47s	remaining: 1m 23s
8764:	learn: 0.0013522	total: 15m 47s	remaining: 2m 13s
9468:	learn: 0.0014815	total: 15m 46s	remaining: 53.1s
9460:	learn: 0.0013332	total: 15m 47s	remaining: 54s
9650:	learn: 0.0013971	total: 15m 46s	remaining: 34.2s
9190:	learn: 0.0015961	total: 15m 47s	remaining: 1m 23s
9461:	learn: 0.0013332	total: 15m 47s	remaining: 53.9s
9469:	learn: 0.0014815	total: 15m 46s	remaining: 53s
8765:	learn: 0.0013522	total: 15m 47s	remaining: 2m 13s
9191:	learn: 0.0015961	total: 15m 47s	remaining: 1m 23s
9651:	learn: 0.0013971	total: 15m 46s	remaining: 34.1s
9192:	learn: 0.0015961	total: 15m 47s	remaining: 1m 23s
9462:	learn: 0.0013332	total: 15m 47s	remaining: 53.8s
8766:	learn: 0.0013522	total: 15m 47s	remaining: 2m 13s
9652:	learn: 0.0013971	total: 15m 47s	remaining: 34s
9470:	learn: 0.0014815	total: 15m 47s	remaining: 52.9s
9193:	learn: 0.0015961	total: 15m 47s	remaining: 1m 23s
9463:	learn: 0.0013332	total: 15m 47s	remaining: 53.6s
9471:	learn: 0.0014815	total: 15m 47s	remaining: 52.8s
8767:	learn: 0.0013522	total: 15m 47s	remaining: 2m 13s
9194:	learn: 0.0015961	total: 15m 47s	remaining: 1m 22s
9653:	learn: 0.0013971	total: 15m 47s	remaining: 33.9s
9464:	learn: 0.0013332	total: 15m 47s	remaining: 53.5s
9472:	learn: 0.0014809	total: 15m 47s	remaining: 52.7s
8768:	learn: 0.0013522	total: 15m 47s	remaining: 2m 13s
9195:	learn: 0.0015961	total: 15m 47s	remaining: 1m 22s
9654:	learn: 0.0013971	total: 15m 47s	remaining: 33.9s
9465:	learn: 0.0013332	total: 15m 47s	remaining: 53.5s
8769:	learn: 0.0013522	total: 15m 47s	remaining: 2m 12s
9473:	learn: 0.0014804	total: 15m 47s	remaining: 52.6s
9196:	learn: 0.0015961	total: 15m 47s	remaining: 1m 22s
9655:	learn: 0.0013971	total: 15m 47s	remaining: 33.8s
9466:	learn: 0.0013332	total: 15m 47s	remaining: 53.3s
8770:	learn: 0.0013522	total: 15m 47s	remaining: 2m 12s
9474:	learn: 0.0014804	total: 15m 47s	remaining: 52.5s
9197:	learn: 0.0015961	total: 15m 47s	remaining: 1m 22s
9656:	learn: 0.0013971	total: 15m 47s	remaining: 33.7s
9467:	learn: 0.0013332	total: 15m 47s	remaining: 53.3s
8771:	learn: 0.0013522	total: 15m 47s	remaining: 2m 12s
9475:	learn: 0.0014804	total: 15m 47s	remaining: 52.4s
9198:	learn: 0.0015961	total: 15m 47s	remaining: 1m 22s
9657:	learn: 0.0013971	total: 15m 47s	remaining: 33.6s
9468:	learn: 0.0013332	total: 15m 47s	remaining: 53.1s
9476:	learn: 0.0014804	total: 15m 47s	remaining: 52.3s
8772:	learn: 0.0013522	total: 15m 47s	remaining: 2m 12s
9199:	learn: 0.0015960	total: 15m 47s	remaining: 1m 22s
9658:	learn: 0.0013967	total: 15m 47s	remaining: 33.5s
9469:	learn: 0.0013332	total: 15m 47s	remaining: 53s
9477:	learn: 0.0014801	total: 15m 47s	remaining: 52.2s
9200:	learn: 0.0015961	total: 15m 47s	remaining: 1m 22s
8773:	learn: 0.0013522	total: 15m 48s	remaining: 2m 12s
9659:	learn: 0.0013967	total: 15m 47s	remaining: 33.4s
9201:	learn: 0.0015961	total: 15m 48s	remaining: 1m 22s
9470:	learn: 0.0013332	total: 15m 48s	remaining: 53s
9478:	learn: 0.0014801	total: 15m 47s	remaining: 52.1s
8774:	learn: 0.0013522	total: 15m 48s	remaining: 2m 12s
9202:	learn: 0.0015961	total: 15m 48s	remaining: 1m 22s

9471:	learn: 0.0013332	total: 15m 48s	remaining: 52.9s
9660:	learn: 0.0013967	total: 15m 47s	remaining: 33.3s
9479:	learn: 0.0014801	total: 15m 47s	remaining: 52s
8775:	learn: 0.0013522	total: 15m 48s	remaining: 2m 12s
9472:	learn: 0.0013332	total: 15m 48s	remaining: 52.7s
9203:	learn: 0.0015961	total: 15m 48s	remaining: 1m 22s
9661:	learn: 0.0013967	total: 15m 48s	remaining: 33.2s
9480:	learn: 0.0014801	total: 15m 48s	remaining: 51.9s
9473:	learn: 0.0013332	total: 15m 48s	remaining: 52.6s
8776:	learn: 0.0013522	total: 15m 48s	remaining: 2m 12s
9662:	learn: 0.0013967	total: 15m 48s	remaining: 33.1s
9204:	learn: 0.0015959	total: 15m 48s	remaining: 1m 21s
9481:	learn: 0.0014801	total: 15m 48s	remaining: 51.8s
9663:	learn: 0.0013967	total: 15m 48s	remaining: 33s
9205:	learn: 0.0015959	total: 15m 48s	remaining: 1m 21s
9482:	learn: 0.0014801	total: 15m 48s	remaining: 51.7s
9474:	learn: 0.0013332	total: 15m 48s	remaining: 52.5s
8777:	learn: 0.0013522	total: 15m 48s	remaining: 2m 12s
9664:	learn: 0.0013967	total: 15m 48s	remaining: 32.9s
9206:	learn: 0.0015959	total: 15m 48s	remaining: 1m 21s
9475:	learn: 0.0013332	total: 15m 48s	remaining: 52.5s
9483:	learn: 0.0014801	total: 15m 48s	remaining: 51.6s
8778:	learn: 0.0013522	total: 15m 48s	remaining: 2m 11s
9207:	learn: 0.0015959	total: 15m 48s	remaining: 1m 21s
9665:	learn: 0.0013967	total: 15m 48s	remaining: 32.8s
9476:	learn: 0.0013332	total: 15m 48s	remaining: 52.4s
9484:	learn: 0.0014801	total: 15m 48s	remaining: 51.5s
9208:	learn: 0.0015959	total: 15m 48s	remaining: 1m 21s
8779:	learn: 0.0013522	total: 15m 48s	remaining: 2m 11s
9666:	learn: 0.0013967	total: 15m 48s	remaining: 32.7s
9477:	learn: 0.0013332	total: 15m 48s	remaining: 52.3s
9209:	learn: 0.0015959	total: 15m 48s	remaining: 1m 21s
9485:	learn: 0.0014801	total: 15m 48s	remaining: 51.4s
9667:	learn: 0.0013967	total: 15m 48s	remaining: 32.6s
8780:	learn: 0.0013522	total: 15m 48s	remaining: 2m 11s
9478:	learn: 0.0013332	total: 15m 48s	remaining: 52.1s
9210:	learn: 0.0015959	total: 15m 48s	remaining: 1m 21s
9486:	learn: 0.0014801	total: 15m 48s	remaining: 51.3s
9668:	learn: 0.0013967	total: 15m 48s	remaining: 32.5s
8781:	learn: 0.0013522	total: 15m 48s	remaining: 2m 11s
9487:	learn: 0.0014801	total: 15m 48s	remaining: 51.2s
9479:	learn: 0.0013332	total: 15m 48s	remaining: 52s
9211:	learn: 0.0015955	total: 15m 49s	remaining: 1m 21s
9669:	learn: 0.0013967	total: 15m 48s	remaining: 32.4s
8782:	learn: 0.0013522	total: 15m 49s	remaining: 2m 11s
9480:	learn: 0.0013332	total: 15m 49s	remaining: 51.9s
9488:	learn: 0.0014801	total: 15m 48s	remaining: 51.1s
9212:	learn: 0.0015952	total: 15m 49s	remaining: 1m 21s
9670:	learn: 0.0013967	total: 15m 48s	remaining: 32.3s
9213:	learn: 0.0015951	total: 15m 49s	remaining: 1m 20s
9481:	learn: 0.0013332	total: 15m 49s	remaining: 51.8s
8783:	learn: 0.0013522	total: 15m 49s	remaining: 2m 11s
9489:	learn: 0.0014801	total: 15m 48s	remaining: 51s
9671:	learn: 0.0013967	total: 15m 48s	remaining: 32.2s
9214:	learn: 0.0015950	total: 15m 49s	remaining: 1m 20s
9672:	learn: 0.0013967	total: 15m 49s	remaining: 32.1s
9482:	learn: 0.0013332	total: 15m 49s	remaining: 51.8s
9490:	learn: 0.0014801	total: 15m 49s	remaining: 50.9s
8784:	learn: 0.0013522	total: 15m 49s	remaining: 2m 11s
9215:	learn: 0.0015944	total: 15m 49s	remaining: 1m 20s
9483:	learn: 0.0013332	total: 15m 49s	remaining: 51.6s
9673:	learn: 0.0013963	total: 15m 49s	remaining: 32s
9491:	learn: 0.0014801	total: 15m 49s	remaining: 50.8s
8785:	learn: 0.0013522	total: 15m 49s	remaining: 2m 11s
9216:	learn: 0.0015944	total: 15m 49s	remaining: 1m 20s
9674:	learn: 0.0013964	total: 15m 49s	remaining: 31.9s
9484:	learn: 0.0013332	total: 15m 49s	remaining: 51.6s
9492:	learn: 0.0014801	total: 15m 49s	remaining: 50.7s
8786:	learn: 0.0013522	total: 15m 49s	remaining: 2m 11s
9217:	learn: 0.0015944	total: 15m 49s	remaining: 1m 20s
9675:	learn: 0.0013964	total: 15m 49s	remaining: 31.8s
9485:	learn: 0.0013329	total: 15m 49s	remaining: 51.5s
9493:	learn: 0.0014801	total: 15m 49s	remaining: 50.6s
9218:	learn: 0.0015944	total: 15m 49s	remaining: 1m 20s
8787:	learn: 0.0013522	total: 15m 49s	remaining: 2m 10s
9676:	learn: 0.0013963	total: 15m 49s	remaining: 31.7s
9486:	learn: 0.0013329	total: 15m 49s	remaining: 51.4s
9494:	learn: 0.0014801	total: 15m 49s	remaining: 50.5s
9219:	learn: 0.0015944	total: 15m 49s	remaining: 1m 20s
9677:	learn: 0.0013963	total: 15m 49s	remaining: 31.6s
8788:	learn: 0.0013520	total: 15m 49s	remaining: 2m 10s
9495:	learn: 0.0014801	total: 15m 49s	remaining: 50.4s
9487:	learn: 0.0013329	total: 15m 49s	remaining: 51.3s
9678:	learn: 0.0013963	total: 15m 49s	remaining: 31.5s
9220:	learn: 0.0015944	total: 15m 49s	remaining: 1m 20s
8789:	learn: 0.0013520	total: 15m 49s	remaining: 2m 10s
9488:	learn: 0.0013329	total: 15m 49s	remaining: 51.1s
9496:	learn: 0.0014801	total: 15m 49s	remaining: 50.3s
9221:	learn: 0.0015944	total: 15m 49s	remaining: 1m 20s
8790:	learn: 0.0013520	total: 15m 49s	remaining: 2m 10s
9679:	learn: 0.0013964	total: 15m 49s	remaining: 31.4s
9489:	learn: 0.0013329	total: 15m 49s	remaining: 51s
8791:	learn: 0.0013520	total: 15m 50s	remaining: 2m 10s
9497:	learn: 0.0014801	total: 15m 49s	remaining: 50.2s
9222:	learn: 0.0015944	total: 15m 50s	remaining: 1m 20s
9680:	learn: 0.0013960	total: 15m 49s	remaining: 31.3s
9490:	learn: 0.0013329	total: 15m 50s	remaining: 50.9s
8792:	learn: 0.0013520	total: 15m 50s	remaining: 2m 10s
9498:	learn: 0.0014801	total: 15m 49s	remaining: 50.1s
9681:	learn: 0.0013956	total: 15m 49s	remaining: 31.2s
9223:	learn: 0.0015944	total: 15m 50s	remaining: 1m 19s
9491:	learn: 0.0013329	total: 15m 50s	remaining: 50.8s
9499:	learn: 0.0014801	total: 15m 49s	remaining: 50s
9682:	learn: 0.0013952	total: 15m 50s	remaining: 31.1s
8793:	learn: 0.0013519	total: 15m 50s	remaining: 2m 10s
9224:	learn: 0.0015944	total: 15m 50s	remaining: 1m 19s
9492:	learn: 0.0013326	total: 15m 50s	remaining: 50.7s
9500:	learn: 0.0014801	total: 15m 50s	remaining: 49.9s
9683:	learn: 0.0013952	total: 15m 50s	remaining: 31s
8794:	learn: 0.0013519	total: 15m 50s	remaining: 2m 10s
9493:	learn: 0.0013326	total: 15m 50s	remaining: 50.6s
9501:	learn: 0.0014801	total: 15m 50s	remaining: 49.8s
9225:	learn: 0.0015944	total: 15m 50s	remaining: 1m 19s
9684:	learn: 0.0013952	total: 15m 50s	remaining: 30.9s
9494:	learn: 0.0013326	total: 15m 50s	remaining: 50.5s
8795:	learn: 0.0013519	total: 15m 50s	remaining: 2m 10s
9685:	learn: 0.0013952	total: 15m 50s	remaining: 30.8s
9502:	learn: 0.0014801	total: 15m 50s	remaining: 49.7s
9226:	learn: 0.0015944	total: 15m 50s	remaining: 1m 19s
9495:	learn: 0.0013326	total: 15m 50s	remaining: 50.4s
8796:	learn: 0.0013520	total: 15m 50s	remaining: 2m 9s
9686:	learn: 0.0013952	total: 15m 50s	remaining: 30.7s
9503:	learn: 0.0014801	total: 15m 50s	remaining: 49.6s
9227:	learn: 0.0015944	total: 15m 50s	remaining: 1m 19s
9496:	learn: 0.0013326	total: 15m 50s	remaining: 50.3s
8797:	learn: 0.0013520	total: 15m 50s	remaining: 2m 9s
9687:	learn: 0.0013952	total: 15m 50s	remaining: 30.6s
9504:	learn: 0.0014801	total: 15m 50s	remaining: 49.5s
9228:	learn: 0.0015944	total: 15m 50s	remaining: 1m 19s
9497:	learn: 0.0013326	total: 15m 50s	remaining: 50.2s
9688:	learn: 0.0013952	total: 15m 50s	remaining: 30.5s
9505:	learn: 0.0014801	total: 15m 50s	remaining: 49.4s
9229:	learn: 0.0015944	total: 15m 50s	remaining: 1m 19s
8798:	learn: 0.0013520	total: 15m 50s	remaining: 2m 9s
9498:	learn: 0.0013326	total: 15m 50s	remaining: 50.1s
9689:	learn: 0.0013952	total: 15m 50s	remaining: 30.4s
9506:	learn: 0.0014801	total: 15m 50s	remaining: 49.3s
9499:	learn: 0.0013326	total: 15m 50s	remaining: 50s
9230:	learn: 0.0015944	total: 15m 50s	remaining: 1m 19s
9690:	learn: 0.0013952	total: 15m 50s	remaining: 30.3s
8799:	learn: 0.0013520	total: 15m 50s	remaining: 2m 9s
9507:	learn: 0.0014801	total: 15m 50s	remaining: 49.2s
9691:	learn: 0.0013952	total: 15m 50s	remaining: 30.2s
9500:	learn: 0.0013326	total: 15m 50s	remaining: 49.9s
9508:	learn: 0.0014801	total: 15m 50s	remaining: 49.1s
9231:	learn: 0.0015944	total: 15m 51s	remaining: 1m 19s
8800:	learn: 0.0013520	total: 15m 51s	remaining: 2m 9s
9692:	learn: 0.0013952	total: 15m 50s	remaining: 30.1s
9501:	learn: 0.0013326	total: 15m 51s	remaining: 49.8s
9509:	learn: 0.0014801	total: 15m 50s	remaining: 49s
9232:	learn: 0.0015944	total: 15m 51s	remaining: 1m 19s
9693:	learn: 0.0013952	total: 15m 50s	remaining: 30s
8801:	learn: 0.0013519	total: 15m 51s	remaining: 2m 9s
9510:	learn: 0.0014801	total: 15m 50s	remaining: 48.9s
9502:	learn: 0.0013326	total: 15m 51s	remaining: 49.7s
9233:	learn: 0.0015941	total: 15m 51s	remaining: 1m 18s
9694:	learn: 0.0013952	total: 15m 51s	remaining: 29.9s
8802:	learn: 0.0013519	total: 15m 51s	remaining: 2m 9s
9511:	learn: 0.0014801	total: 15m 51s	remaining: 48.8s
9503:	learn: 0.0013326	total: 15m 51s	remaining: 49.6s
9234:	learn: 0.0015941	total: 15m 51s	remaining: 1m 18s
9695:	learn: 0.0013952	total: 15m 51s	remaining: 29.8s
9512:	learn: 0.0014801	total: 15m 51s	remaining: 48.7s
8803:	learn: 0.0013519	total: 15m 51s	remaining: 2m 9s
9504:	learn: 0.0013325	total: 15m 51s	remaining: 49.5s
9235:	learn: 0.0015941	total: 15m 51s	remaining: 1m 18s
9696:	learn: 0.0013949	total: 15m 51s	remaining: 29.7s
9513:	learn: 0.0014801	total: 15m 51s	remaining: 48.6s
9505:	learn: 0.0013325	total: 15m 51s	remaining: 49.4s
8804:	learn: 0.0013519	total: 15m 51s	remaining: 2m 9s
9236:	learn: 0.0015941	total: 15m 51s	remaining: 1m 18s
9514:	learn: 0.0014801	total: 15m 51s	remaining: 48.5s
9697:	learn: 0.0013949	total: 15m 51s	remaining: 29.6s
9506:	learn: 0.0013325	total: 15m 51s	remaining: 49.3s
8805:	learn: 0.0013519	total: 15m 51s	remaining: 2m 9s
9507:	learn: 0.0013325	total: 15m 51s	remaining: 49.2s
9237:	learn: 0.0015941	total: 15m 51s	remaining: 1m 18s
9515:	learn: 0.0014801	total: 15m 51s	remaining: 48.4s
9698:	learn: 0.0013946	total: 15m 51s	remaining: 29.5s
8806:	learn: 0.0013519	total: 15m 51s	remaining: 2m 8s
9516:	learn: 0.0014801	total: 15m 51s	remaining: 48.3s
9238:	learn: 0.0015941	total: 15m 51s	remaining: 1m 18s
9699:	learn: 0.0013945	total: 15m 51s	remaining: 29.4s
9508:	learn: 0.0013325	total: 15m 51s	remaining: 49.1s
8807:	learn: 0.0013519	total: 15m 51s	remaining: 2m 8s
9700:	learn: 0.0013945	total: 15m 51s	remaining: 29.3s
9239:	learn: 0.0015941	total: 15m 51s	remaining: 1m 18s
9509:	learn: 0.0013325	total: 15m 51s	remaining: 49s
9517:	learn: 0.0014801	total: 15m 51s	remaining: 48.2s
9701:	learn: 0.0013945	total: 15m 51s	remaining: 29.2s
8808:	learn: 0.0013519	total: 15m 51s	remaining: 2m 8s
9240:	learn: 0.0015941	total: 15m 51s	remaining: 1m 18s
9518:	learn: 0.0014801	total: 15m 51s	remaining: 48.1s
9241:	learn: 0.0015941	total: 15m 52s	remaining: 1m 18s
9702:	learn: 0.0013945	total: 15m 51s	remaining: 29.1s
9510:	learn: 0.0013325	total: 15m 52s	remaining: 48.9s
9519:	learn: 0.0014801	total: 15m 51s	remaining: 48s
8809:	learn: 0.0013519	total: 15m 52s	remaining: 2m 8s
9242:	learn: 0.0015941	total: 15m 52s	remaining: 1m 17s
9511:	learn: 0.0013325	total: 15m 52s	remaining: 48.8s
9703:	learn: 0.0013945	total: 15m 51s	remaining: 29s
8810:	learn: 0.0013519	total: 15m 52s	remaining: 2m 8s
9520:	learn: 0.0014801	total: 15m 51s	remaining: 47.9s
9243:	learn: 0.0015941	total: 15m 52s	remaining: 1m 17s
9704:	learn: 0.0013945	total: 15m 52s	remaining: 28.9s
9512:	learn: 0.0013325	total: 15m 52s	remaining: 48.7s
8811:	learn: 0.0013519	total: 15m 52s	remaining: 2m 8s
9521:	learn: 0.0014801	total: 15m 52s	remaining: 47.8s
9244:	learn: 0.0015941	total: 15m 52s	remaining: 1m 17s
9705:	learn: 0.0013945	total: 15m 52s	remaining: 28.8s
9513:	learn: 0.0013325	total: 15m 52s	remaining: 48.6s
8812:	learn: 0.0013519	total: 15m 52s	remaining: 2m 8s
9522:	learn: 0.0014801	total: 15m 52s	remaining: 47.7s
9514:	learn: 0.0013323	total: 15m 52s	remaining: 48.5s
9245:	learn: 0.0015941	total: 15m 52s	remaining: 1m 17s
9706:	learn: 0.0013945	total: 15m 52s	remaining: 28.7s
8813:	learn: 0.0013519	total: 15m 52s	remaining: 2m 8s
9523:	learn: 0.0014801	total: 15m 52s	remaining: 47.6s
9246:	learn: 0.0015941	total: 15m 52s	remaining: 1m 17s
9515:	learn: 0.0013323	total: 15m 52s	remaining: 48.4s
9707:	learn: 0.0013945	total: 15m 52s	remaining: 28.6s
8814:	learn: 0.0013519	total: 15m 52s	remaining: 2m 8s
9524:	learn: 0.0014801	total: 15m 52s	remaining: 47.5s
9516:	learn: 0.0013323	total: 15m 52s	remaining: 48.3s
9247:	learn: 0.0015941	total: 15m 52s	remaining: 1m 17s
9708:	learn: 0.0013945	total: 15m 52s	remaining: 28.5s
9517:	learn: 0.0013323	total: 15m 52s	remaining: 48.2s
8815:	learn: 0.0013519	total: 15m 52s	remaining: 2m 7s
9525:	learn: 0.0014801	total: 15m 52s	remaining: 47.4s
9248:	learn: 0.0015941	total: 15m 52s	remaining: 1m 17s
9709:	learn: 0.0013945	total: 15m 52s	remaining: 28.4s
9518:	learn: 0.0013323	total: 15m 52s	remaining: 48.1s
9526:	learn: 0.0014801	total: 15m 52s	remaining: 47.3s
8816:	learn: 0.0013519	total: 15m 52s	remaining: 2m 7s
9710:	learn: 0.0013941	total: 15m 52s	remaining: 28.4s
9249:	learn: 0.0015941	total: 15m 52s	remaining: 1m 17s
9519:	learn: 0.0013323	total: 15m 52s	remaining: 48s
9527:	learn: 0.0014801	total: 15m 52s	remaining: 47.2s
8817:	learn: 0.0013519	total: 15m 52s	remaining: 2m 7s
9711:	learn: 0.0013941	total: 15m 52s	remaining: 28.3s
9250:	learn: 0.0015941	total: 15m 52s	remaining: 1m 17s
9520:	learn: 0.0013323	total: 15m 52s	remaining: 47.9s
9528:	learn: 0.0014801	total: 15m 52s	remaining: 47.1s
8818:	learn: 0.0013519	total: 15m 53s	remaining: 2m 7s
9251:	learn: 0.0015941	total: 15m 53s	remaining: 1m 17s
9521:	learn: 0.0013323	total: 15m 53s	remaining: 47.8s
9712:	learn: 0.0013941	total: 15m 52s	remaining: 28.2s
9529:	learn: 0.0014801	total: 15m 52s	remaining: 47s
8819:	learn: 0.0013519	total: 15m 53s	remaining: 2m 7s
9252:	learn: 0.0015941	total: 15m 53s	remaining: 1m 16s
9530:	learn: 0.0014801	total: 15m 52s	remaining: 46.9s
9522:	learn: 0.0013323	total: 15m 53s	remaining: 47.7s
9713:	learn: 0.0013941	total: 15m 52s	remaining: 28.1s
8820:	learn: 0.0013519	total: 15m 53s	remaining: 2m 7s
9253:	learn: 0.0015941	total: 15m 53s	remaining: 1m 16s
9531:	learn: 0.0014801	total: 15m 53s	remaining: 46.8s
9523:	learn: 0.0013323	total: 15m 53s	remaining: 47.6s
9714:	learn: 0.0013941	total: 15m 53s	remaining: 28s
8821:	learn: 0.0013519	total: 15m 53s	remaining: 2m 7s
9254:	learn: 0.0015941	total: 15m 53s	remaining: 1m 16s
9524:	learn: 0.0013321	total: 15m 53s	remaining: 47.5s
9532:	learn: 0.0014801	total: 15m 53s	remaining: 46.7s
9715:	learn: 0.0013941	total: 15m 53s	remaining: 27.9s
8822:	learn: 0.0013519	total: 15m 53s	remaining: 2m 7s
9525:	learn: 0.0013317	total: 15m 53s	remaining: 47.4s
9533:	learn: 0.0014799	total: 15m 53s	remaining: 46.6s
9255:	learn: 0.0015941	total: 15m 53s	remaining: 1m 16s
8823:	learn: 0.0013519	total: 15m 53s	remaining: 2m 7s
9716:	learn: 0.0013941	total: 15m 53s	remaining: 27.8s
9526:	learn: 0.0013317	total: 15m 53s	remaining: 47.3s
9256:	learn: 0.0015941	total: 15m 53s	remaining: 1m 16s
9534:	learn: 0.0014799	total: 15m 53s	remaining: 46.5s
9717:	learn: 0.0013941	total: 15m 53s	remaining: 27.7s
8824:	learn: 0.0013519	total: 15m 53s	remaining: 2m 6s
9527:	learn: 0.0013317	total: 15m 53s	remaining: 47.2s
9257:	learn: 0.0015941	total: 15m 53s	remaining: 1m 16s
9535:	learn: 0.0014799	total: 15m 53s	remaining: 46.4s
9718:	learn: 0.0013941	total: 15m 53s	remaining: 27.6s
8825:	learn: 0.0013519	total: 15m 53s	remaining: 2m 6s
9528:	learn: 0.0013317	total: 15m 53s	remaining: 47.1s
9258:	learn: 0.0015941	total: 15m 53s	remaining: 1m 16s
9536:	learn: 0.0014799	total: 15m 53s	remaining: 46.3s
9719:	learn: 0.0013941	total: 15m 53s	remaining: 27.5s
8826:	learn: 0.0013519	total: 15m 53s	remaining: 2m 6s
9529:	learn: 0.0013317	total: 15m 53s	remaining: 47s
9720:	learn: 0.0013941	total: 15m 53s	remaining: 27.4s
9537:	learn: 0.0014799	total: 15m 53s	remaining: 46.2s
9259:	learn: 0.0015941	total: 15m 53s	remaining: 1m 16s
9721:	learn: 0.0013941	total: 15m 53s	remaining: 27.3s
8827:	learn: 0.0013519	total: 15m 53s	remaining: 2m 6s
9538:	learn: 0.0014799	total: 15m 53s	remaining: 46.1s
9530:	learn: 0.0013317	total: 15m 53s	remaining: 46.9s
9260:	learn: 0.0015941	total: 15m 54s	remaining: 1m 16s
9722:	learn: 0.0013941	total: 15m 53s	remaining: 27.2s
9531:	learn: 0.0013317	total: 15m 54s	remaining: 46.8s
8828:	learn: 0.0013519	total: 15m 54s	remaining: 2m 6s

9539:	learn: 0.0014799	total: 15m 53s	remaining: 46s
9261:	learn: 0.0015941	total: 15m 54s	remaining: 1m 16s
9723:	learn: 0.0013941	total: 15m 53s	remaining: 27.1s
9532:	learn: 0.0013317	total: 15m 54s	remaining: 46.7s
8829:	learn: 0.0013519	total: 15m 54s	remaining: 2m 6s
9540:	learn: 0.0014799	total: 15m 53s	remaining: 45.9s
9262:	learn: 0.0015941	total: 15m 54s	remaining: 1m 15s
9724:	learn: 0.0013941	total: 15m 54s	remaining: 27s
9533:	learn: 0.0013317	total: 15m 54s	remaining: 46.6s
8830:	learn: 0.0013519	total: 15m 54s	remaining: 2m 6s
9725:	learn: 0.0013941	total: 15m 54s	remaining: 26.9s
9541:	learn: 0.0014799	total: 15m 54s	remaining: 45.8s
9263:	learn: 0.0015941	total: 15m 54s	remaining: 1m 15s
9534:	learn: 0.0013317	total: 15m 54s	remaining: 46.5s
9726:	learn: 0.0013941	total: 15m 54s	remaining: 26.8s
9542:	learn: 0.0014799	total: 15m 54s	remaining: 45.7s
8831:	learn: 0.0013519	total: 15m 54s	remaining: 2m 6s
9535:	learn: 0.0013317	total: 15m 54s	remaining: 46.4s
9264:	learn: 0.0015941	total: 15m 54s	remaining: 1m 15s
9727:	learn: 0.0013941	total: 15m 54s	remaining: 26.7s
9543:	learn: 0.0014796	total: 15m 54s	remaining: 45.6s
8832:	learn: 0.0013519	total: 15m 54s	remaining: 2m 6s
9265:	learn: 0.0015941	total: 15m 54s	remaining: 1m 15s
9536:	learn: 0.0013317	total: 15m 54s	remaining: 46.3s
9728:	learn: 0.0013941	total: 15m 54s	remaining: 26.6s
9544:	learn: 0.0014796	total: 15m 54s	remaining: 45.5s
8833:	learn: 0.0013519	total: 15m 54s	remaining: 2m 5s
9537:	learn: 0.0013317	total: 15m 54s	remaining: 46.2s
9266:	learn: 0.0015941	total: 15m 54s	remaining: 1m 15s
9545:	learn: 0.0014796	total: 15m 54s	remaining: 45.4s
9729:	learn: 0.0013941	total: 15m 54s	remaining: 26.5s
9538:	learn: 0.0013317	total: 15m 54s	remaining: 46.1s
8834:	learn: 0.0013519	total: 15m 54s	remaining: 2m 5s
9267:	learn: 0.0015941	total: 15m 54s	remaining: 1m 15s
9546:	learn: 0.0014796	total: 15m 54s	remaining: 45.3s
9730:	learn: 0.0013941	total: 15m 54s	remaining: 26.4s
9539:	learn: 0.0013317	total: 15m 54s	remaining: 46s
9731:	learn: 0.0013941	total: 15m 54s	remaining: 26.3s
9268:	learn: 0.0015941	total: 15m 54s	remaining: 1m 15s
8835:	learn: 0.0013519	total: 15m 54s	remaining: 2m 5s
9547:	learn: 0.0014796	total: 15m 54s	remaining: 45.2s
9732:	learn: 0.0013941	total: 15m 54s	remaining: 26.2s
9540:	learn: 0.0013317	total: 15m 54s	remaining: 45.9s
9269:	learn: 0.0015941	total: 15m 54s	remaining: 1m 15s
8836:	learn: 0.0013519	total: 15m 54s	remaining: 2m 5s
9548:	learn: 0.0014796	total: 15m 54s	remaining: 45.1s
9733:	learn: 0.0013941	total: 15m 54s	remaining: 26.1s
9541:	learn: 0.0013317	total: 15m 54s	remaining: 45.8s
8837:	learn: 0.0013519	total: 15m 55s	remaining: 2m 5s
9270:	learn: 0.0015941	total: 15m 55s	remaining: 1m 15s
9549:	learn: 0.0014796	total: 15m 54s	remaining: 45s
9734:	learn: 0.0013936	total: 15m 54s	remaining: 26s
9542:	learn: 0.0013317	total: 15m 55s	remaining: 45.7s
9550:	learn: 0.0014796	total: 15m 54s	remaining: 44.9s
8838:	learn: 0.0013519	total: 15m 55s	remaining: 2m 5s
9271:	learn: 0.0015941	total: 15m 55s	remaining: 1m 15s
9735:	learn: 0.0013935	total: 15m 54s	remaining: 25.9s
9543:	learn: 0.0013317	total: 15m 55s	remaining: 45.6s
9551:	learn: 0.0014796	total: 15m 54s	remaining: 44.8s
9736:	learn: 0.0013935	total: 15m 55s	remaining: 25.8s
8839:	learn: 0.0013519	total: 15m 55s	remaining: 2m 5s
9272:	learn: 0.0015941	total: 15m 55s	remaining: 1m 14s
9544:	learn: 0.0013317	total: 15m 55s	remaining: 45.5s
9737:	learn: 0.0013935	total: 15m 55s	remaining: 25.7s
9552:	learn: 0.0014796	total: 15m 55s	remaining: 44.7s
9273:	learn: 0.0015941	total: 15m 55s	remaining: 1m 14s
8840:	learn: 0.0013519	total: 15m 55s	remaining: 2m 5s
9545:	learn: 0.0013317	total: 15m 55s	remaining: 45.4s
9738:	learn: 0.0013935	total: 15m 55s	remaining: 25.6s
9553:	learn: 0.0014796	total: 15m 55s	remaining: 44.6s
9546:	learn: 0.0013317	total: 15m 55s	remaining: 45.3s
9274:	learn: 0.0015941	total: 15m 55s	remaining: 1m 14s
8841:	learn: 0.0013519	total: 15m 55s	remaining: 2m 5s
9739:	learn: 0.0013935	total: 15m 55s	remaining: 25.5s
9554:	learn: 0.0014796	total: 15m 55s	remaining: 44.5s
9547:	learn: 0.0013317	total: 15m 55s	remaining: 45.2s
8842:	learn: 0.0013519	total: 15m 55s	remaining: 2m 5s
9275:	learn: 0.0015941	total: 15m 55s	remaining: 1m 14s
9740:	learn: 0.0013934	total: 15m 55s	remaining: 25.4s
9555:	learn: 0.0014796	total: 15m 55s	remaining: 44.4s
9548:	learn: 0.0013317	total: 15m 55s	remaining: 45.1s
9276:	learn: 0.0015941	total: 15m 55s	remaining: 1m 14s
9741:	learn: 0.0013934	total: 15m 55s	remaining: 25.3s
8843:	learn: 0.0013519	total: 15m 55s	remaining: 2m 4s
9556:	learn: 0.0014796	total: 15m 55s	remaining: 44.3s
9549:	learn: 0.0013317	total: 15m 55s	remaining: 45s
9742:	learn: 0.0013932	total: 15m 55s	remaining: 25.2s
9277:	learn: 0.0015941	total: 15m 55s	remaining: 1m 14s
8844:	learn: 0.0013519	total: 15m 55s	remaining: 2m 4s
9557:	learn: 0.0014796	total: 15m 55s	remaining: 44.2s
9550:	learn: 0.0013317	total: 15m 55s	remaining: 44.9s
9743:	learn: 0.0013928	total: 15m 55s	remaining: 25.1s
9278:	learn: 0.0015941	total: 15m 55s	remaining: 1m 14s
8845:	learn: 0.0013519	total: 15m 55s	remaining: 2m 4s
9551:	learn: 0.0013317	total: 15m 55s	remaining: 44.8s
9558:	learn: 0.0014796	total: 15m 55s	remaining: 44.1s
9744:	learn: 0.0013928	total: 15m 55s	remaining: 25s
9279:	learn: 0.0015941	total: 15m 56s	remaining: 1m 14s
8846:	learn: 0.0013519	total: 15m 56s	remaining: 2m 4s
9559:	learn: 0.0014796	total: 15m 55s	remaining: 44s
9552:	learn: 0.0013317	total: 15m 56s	remaining: 44.7s
9745:	learn: 0.0013928	total: 15m 55s	remaining: 24.9s
9560:	learn: 0.0014796	total: 15m 55s	remaining: 43.9s
9280:	learn: 0.0015941	total: 15m 56s	remaining: 1m 14s
8847:	learn: 0.0013519	total: 15m 56s	remaining: 2m 4s
9553:	learn: 0.0013316	total: 15m 56s	remaining: 44.6s
9746:	learn: 0.0013928	total: 15m 55s	remaining: 24.8s
9281:	learn: 0.0015941	total: 15m 56s	remaining: 1m 13s
9561:	learn: 0.0014796	total: 15m 55s	remaining: 43.8s
9554:	learn: 0.0013316	total: 15m 56s	remaining: 44.5s
8848:	learn: 0.0013519	total: 15m 56s	remaining: 2m 4s
9747:	learn: 0.0013928	total: 15m 56s	remaining: 24.7s
9562:	learn: 0.0014796	total: 15m 56s	remaining: 43.7s
9282:	learn: 0.0015941	total: 15m 56s	remaining: 1m 13s
9555:	learn: 0.0013316	total: 15m 56s	remaining: 44.4s
8849:	learn: 0.0013519	total: 15m 56s	remaining: 2m 4s
9748:	learn: 0.0013928	total: 15m 56s	remaining: 24.6s
9563:	learn: 0.0014796	total: 15m 56s	remaining: 43.6s
9283:	learn: 0.0015941	total: 15m 56s	remaining: 1m 13s
9749:	learn: 0.0013928	total: 15m 56s	remaining: 24.5s
9556:	learn: 0.0013316	total: 15m 56s	remaining: 44.3s
8850:	learn: 0.0013519	total: 15m 56s	remaining: 2m 4s
9564:	learn: 0.0014796	total: 15m 56s	remaining: 43.5s
9284:	learn: 0.0015941	total: 15m 56s	remaining: 1m 13s
9750:	learn: 0.0013928	total: 15m 56s	remaining: 24.4s
9557:	learn: 0.0013316	total: 15m 56s	remaining: 44.2s
9565:	learn: 0.0014792	total: 15m 56s	remaining: 43.4s
8851:	learn: 0.0013519	total: 15m 56s	remaining: 2m 4s
9285:	learn: 0.0015941	total: 15m 56s	remaining: 1m 13s
9558:	learn: 0.0013314	total: 15m 56s	remaining: 44.1s
9566:	learn: 0.0014792	total: 15m 56s	remaining: 43.3s
9751:	learn: 0.0013928	total: 15m 56s	remaining: 24.3s
8852:	learn: 0.0013519	total: 15m 56s	remaining: 2m 3s
9567:	learn: 0.0014792	total: 15m 56s	remaining: 43.2s
9559:	learn: 0.0013314	total: 15m 56s	remaining: 44s
9286:	learn: 0.0015941	total: 15m 56s	remaining: 1m 13s
9752:	learn: 0.0013928	total: 15m 56s	remaining: 24.2s
9287:	learn: 0.0015941	total: 15m 56s	remaining: 1m 13s
9560:	learn: 0.0013314	total: 15m 56s	remaining: 43.9s
9753:	learn: 0.0013928	total: 15m 56s	remaining: 24.1s
9568:	learn: 0.0014792	total: 15m 56s	remaining: 43.1s
8853:	learn: 0.0013519	total: 15m 56s	remaining: 2m 3s
9288:	learn: 0.0015941	total: 15m 56s	remaining: 1m 13s
9561:	learn: 0.0013314	total: 15m 56s	remaining: 43.8s
9569:	learn: 0.0014792	total: 15m 56s	remaining: 43s
9754:	learn: 0.0013923	total: 15m 56s	remaining: 24s
8854:	learn: 0.0013519	total: 15m 57s	remaining: 2m 3s
9289:	learn: 0.0015941	total: 15m 57s	remaining: 1m 13s
9562:	learn: 0.0013314	total: 15m 56s	remaining: 43.7s
9570:	learn: 0.0014792	total: 15m 56s	remaining: 42.9s
9755:	learn: 0.0013923	total: 15m 56s	remaining: 23.9s
9290:	learn: 0.0015941	total: 15m 57s	remaining: 1m 13s
8855:	learn: 0.0013519	total: 15m 57s	remaining: 2m 3s
9563:	learn: 0.0013314	total: 15m 57s	remaining: 43.6s
9756:	learn: 0.0013923	total: 15m 56s	remaining: 23.8s
9571:	learn: 0.0014792	total: 15m 56s	remaining: 42.8s
9291:	learn: 0.0015941	total: 15m 57s	remaining: 1m 12s
8856:	learn: 0.0013519	total: 15m 57s	remaining: 2m 3s
9564:	learn: 0.0013314	total: 15m 57s	remaining: 43.5s
9757:	learn: 0.0013923	total: 15m 57s	remaining: 23.7s
9292:	learn: 0.0015941	total: 15m 57s	remaining: 1m 12s
9572:	learn: 0.0014792	total: 15m 57s	remaining: 42.7s
8857:	learn: 0.0013519	total: 15m 57s	remaining: 2m 3s
9565:	learn: 0.0013314	total: 15m 57s	remaining: 43.4s
9758:	learn: 0.0013923	total: 15m 57s	remaining: 23.6s
9293:	learn: 0.0015941	total: 15m 57s	remaining: 1m 12s
9573:	learn: 0.0014792	total: 15m 57s	remaining: 42.6s
8858:	learn: 0.0013519	total: 15m 57s	remaining: 2m 3s
9566:	learn: 0.0013314	total: 15m 57s	remaining: 43.3s
9759:	learn: 0.0013923	total: 15m 57s	remaining: 23.5s
9294:	learn: 0.0015941	total: 15m 57s	remaining: 1m 12s
9567:	learn: 0.0013314	total: 15m 57s	remaining: 43.2s
9574:	learn: 0.0014792	total: 15m 57s	remaining: 42.5s
8859:	learn: 0.0013519	total: 15m 57s	remaining: 2m 3s
9760:	learn: 0.0013923	total: 15m 57s	remaining: 23.4s
9295:	learn: 0.0015941	total: 15m 57s	remaining: 1m 12s
9568:	learn: 0.0013314	total: 15m 57s	remaining: 43.1s
9575:	learn: 0.0014792	total: 15m 57s	remaining: 42.4s
9761:	learn: 0.0013923	total: 15m 57s	remaining: 23.3s
8860:	learn: 0.0013519	total: 15m 57s	remaining: 2m 3s
9296:	learn: 0.0015941	total: 15m 57s	remaining: 1m 12s
9569:	learn: 0.0013314	total: 15m 57s	remaining: 43s
9576:	learn: 0.0014792	total: 15m 57s	remaining: 42.3s
9762:	learn: 0.0013923	total: 15m 57s	remaining: 23.2s
8861:	learn: 0.0013519	total: 15m 57s	remaining: 2m 2s
9570:	learn: 0.0013314	total: 15m 57s	remaining: 42.9s
9297:	learn: 0.0015941	total: 15m 57s	remaining: 1m 12s
9577:	learn: 0.0014792	total: 15m 57s	remaining: 42.2s
9763:	learn: 0.0013923	total: 15m 57s	remaining: 23.1s
8862:	learn: 0.0013519	total: 15m 57s	remaining: 2m 2s
9571:	learn: 0.0013314	total: 15m 57s	remaining: 42.8s
9298:	learn: 0.0015938	total: 15m 57s	remaining: 1m 12s
9578:	learn: 0.0014792	total: 15m 57s	remaining: 42.1s
9764:	learn: 0.0013922	total: 15m 57s	remaining: 23s
8863:	learn: 0.0013519	total: 15m 57s	remaining: 2m 2s
9572:	learn: 0.0013314	total: 15m 57s	remaining: 42.7s
9299:	learn: 0.0015938	total: 15m 58s	remaining: 1m 12s
9579:	learn: 0.0014792	total: 15m 57s	remaining: 42s
9765:	learn: 0.0013922	total: 15m 57s	remaining: 22.9s
9573:	learn: 0.0013314	total: 15m 58s	remaining: 42.6s
9300:	learn: 0.0015932	total: 15m 58s	remaining: 1m 12s
8864:	learn: 0.0013519	total: 15m 58s	remaining: 2m 2s
9766:	learn: 0.0013922	total: 15m 57s	remaining: 22.9s
9580:	learn: 0.0014792	total: 15m 57s	remaining: 41.9s
9301:	learn: 0.0015932	total: 15m 58s	remaining: 1m 11s
9574:	learn: 0.0013314	total: 15m 58s	remaining: 42.5s
8865:	learn: 0.0013519	total: 15m 58s	remaining: 2m 2s
9767:	learn: 0.0013922	total: 15m 58s	remaining: 22.8s
9581:	learn: 0.0014792	total: 15m 58s	remaining: 41.8s
9302:	learn: 0.0015932	total: 15m 58s	remaining: 1m 11s
9575:	learn: 0.0013313	total: 15m 58s	remaining: 42.4s
8866:	learn: 0.0013519	total: 15m 58s	remaining: 2m 2s
9768:	learn: 0.0013922	total: 15m 58s	remaining: 22.7s
9582:	learn: 0.0014792	total: 15m 58s	remaining: 41.7s
9576:	learn: 0.0013314	total: 15m 58s	remaining: 42.3s
9303:	learn: 0.0015932	total: 15m 58s	remaining: 1m 11s
8867:	learn: 0.0013519	total: 15m 58s	remaining: 2m 2s
9769:	learn: 0.0013922	total: 15m 58s	remaining: 22.6s
9577:	learn: 0.0013314	total: 15m 58s	remaining: 42.2s
9583:	learn: 0.0014792	total: 15m 58s	remaining: 41.6s
9304:	learn: 0.0015932	total: 15m 58s	remaining: 1m 11s
8868:	learn: 0.0013519	total: 15m 58s	remaining: 2m 2s
9770:	learn: 0.0013922	total: 15m 58s	remaining: 22.5s
9584:	learn: 0.0014792	total: 15m 58s	remaining: 41.5s
9578:	learn: 0.0013314	total: 15m 58s	remaining: 42.1s
9305:	learn: 0.0015932	total: 15m 58s	remaining: 1m 11s
8869:	learn: 0.0013518	total: 15m 58s	remaining: 2m 2s
9771:	learn: 0.0013922	total: 15m 58s	remaining: 22.4s
9579:	learn: 0.0013314	total: 15m 58s	remaining: 42s
9585:	learn: 0.0014792	total: 15m 58s	remaining: 41.4s
9306:	learn: 0.0015932	total: 15m 58s	remaining: 1m 11s
8870:	learn: 0.0013519	total: 15m 58s	remaining: 2m 2s
9772:	learn: 0.0013922	total: 15m 58s	remaining: 22.3s
9586:	learn: 0.0014789	total: 15m 58s	remaining: 41.3s
9580:	learn: 0.0013313	total: 15m 58s	remaining: 41.9s
9307:	learn: 0.0015932	total: 15m 58s	remaining: 1m 11s
8871:	learn: 0.0013519	total: 15m 58s	remaining: 2m 1s
9773:	learn: 0.0013922	total: 15m 58s	remaining: 22.2s
9581:	learn: 0.0013313	total: 15m 58s	remaining: 41.8s
9308:	learn: 0.0015932	total: 15m 58s	remaining: 1m 11s
9587:	learn: 0.0014789	total: 15m 58s	remaining: 41.2s
9774:	learn: 0.0013922	total: 15m 58s	remaining: 22.1s
8872:	learn: 0.0013519	total: 15m 58s	remaining: 2m 1s
9309:	learn: 0.0015932	total: 15m 58s	remaining: 1m 11s
9588:	learn: 0.0014789	total: 15m 58s	remaining: 41.1s
9582:	learn: 0.0013313	total: 15m 58s	remaining: 41.7s
9775:	learn: 0.0013922	total: 15m 58s	remaining: 22s
8873:	learn: 0.0013519	total: 15m 59s	remaining: 2m 1s
9310:	learn: 0.0015932	total: 15m 59s	remaining: 1m 10s
9589:	learn: 0.0014789	total: 15m 58s	remaining: 41s
9583:	learn: 0.0013313	total: 15m 59s	remaining: 41.6s
9776:	learn: 0.0013922	total: 15m 58s	remaining: 21.9s
8874:	learn: 0.0013519	total: 15m 59s	remaining: 2m 1s
9311:	learn: 0.0015932	total: 15m 59s	remaining: 1m 10s
9590:	learn: 0.0014785	total: 15m 58s	remaining: 40.9s
9584:	learn: 0.0013312	total: 15m 59s	remaining: 41.5s
9777:	learn: 0.0013922	total: 15m 59s	remaining: 21.8s
9591:	learn: 0.0014785	total: 15m 58s	remaining: 40.8s
8875:	learn: 0.0013519	total: 15m 59s	remaining: 2m 1s
9312:	learn: 0.0015932	total: 15m 59s	remaining: 1m 10s
9778:	learn: 0.0013922	total: 15m 59s	remaining: 21.7s
9585:	learn: 0.0013312	total: 15m 59s	remaining: 41.4s
9592:	learn: 0.0014785	total: 15m 59s	remaining: 40.7s
8876:	learn: 0.0013519	total: 15m 59s	remaining: 2m 1s
9313:	learn: 0.0015932	total: 15m 59s	remaining: 1m 10s
9586:	learn: 0.0013312	total: 15m 59s	remaining: 41.3s
9779:	learn: 0.0013922	total: 15m 59s	remaining: 21.6s
8877:	learn: 0.0013519	total: 15m 59s	remaining: 2m 1s
9593:	learn: 0.0014785	total: 15m 59s	remaining: 40.6s
9587:	learn: 0.0013312	total: 15m 59s	remaining: 41.2s
9314:	learn: 0.0015932	total: 15m 59s	remaining: 1m 10s
9780:	learn: 0.0013922	total: 15m 59s	remaining: 21.5s
9594:	learn: 0.0014785	total: 15m 59s	remaining: 40.5s
8878:	learn: 0.0013519	total: 15m 59s	remaining: 2m 1s
9588:	learn: 0.0013312	total: 15m 59s	remaining: 41.1s
9315:	learn: 0.0015932	total: 15m 59s	remaining: 1m 10s
9781:	learn: 0.0013922	total: 15m 59s	remaining: 21.4s
9595:	learn: 0.0014785	total: 15m 59s	remaining: 40.4s
9589:	learn: 0.0013312	total: 15m 59s	remaining: 41s
8879:	learn: 0.0013519	total: 15m 59s	remaining: 2m 1s
9316:	learn: 0.0015932	total: 15m 59s	remaining: 1m 10s
9782:	learn: 0.0013922	total: 15m 59s	remaining: 21.3s
9596:	learn: 0.0014784	total: 15m 59s	remaining: 40.3s
9590:	learn: 0.0013312	total: 15m 59s	remaining: 40.9s
8880:	learn: 0.0013519	total: 15m 59s	remaining: 2m
9783:	learn: 0.0013919	total: 15m 59s	remaining: 21.2s
9317:	learn: 0.0015932	total: 15m 59s	remaining: 1m 10s
9591:	learn: 0.0013312	total: 15m 59s	remaining: 40.8s
9597:	learn: 0.0014784	total: 15m 59s	remaining: 40.2s
8881:	learn: 0.0013519	total: 15m 59s	remaining: 2m
9784:	learn: 0.0013919	total: 15m 59s	remaining: 21.1s
9318:	learn: 0.0015932	total: 15m 59s	remaining: 1m 10s
9598:	learn: 0.0014784	total: 15m 59s	remaining: 40.1s
9592:	learn: 0.0013312	total: 15m 59s	remaining: 40.7s
8882:	learn: 0.0013519	total: 15m 59s	remaining: 2m
9319:	learn: 0.0015932	total: 16m	remaining: 1m 10s

9785:	learn: 0.0013919	total: 15m 59s	remaining: 21s
9599:	learn: 0.0014784	total: 15m 59s	remaining: 40s
9593:	learn: 0.0013312	total: 16m	remaining: 40.6s
8883:	learn: 0.0013519	total: 16m	remaining: 2m
9786:	learn: 0.0013919	total: 15m 59s	remaining: 20.9s
9320:	learn: 0.0015932	total: 16m	remaining: 1m 9s
9600:	learn: 0.0014784	total: 15m 59s	remaining: 39.9s
8884:	learn: 0.0013519	total: 16m	remaining: 2m
9594:	learn: 0.0013312	total: 16m	remaining: 40.5s
9787:	learn: 0.0013919	total: 15m 59s	remaining: 20.8s
9321:	learn: 0.0015932	total: 16m	remaining: 1m 9s
8885:	learn: 0.0013519	total: 16m	remaining: 2m
9601:	learn: 0.0014784	total: 15m 59s	remaining: 39.8s
9595:	learn: 0.0013312	total: 16m	remaining: 40.4s
9788:	learn: 0.0013919	total: 16m	remaining: 20.7s
8886:	learn: 0.0013519	total: 16m	remaining: 2m
9322:	learn: 0.0015932	total: 16m	remaining: 1m 9s
9602:	learn: 0.0014784	total: 16m	remaining: 39.7s
9789:	learn: 0.0013919	total: 16m	remaining: 20.6s
8887:	learn: 0.0013519	total: 16m	remaining: 2m
9596:	learn: 0.0013312	total: 16m	remaining: 40.3s
9323:	learn: 0.0015932	total: 16m	remaining: 1m 9s
9603:	learn: 0.0014784	total: 16m	remaining: 39.6s
8888:	learn: 0.0013519	total: 16m	remaining: 2m
9790:	learn: 0.0013919	total: 16m	remaining: 20.5s
9597:	learn: 0.0013312	total: 16m	remaining: 40.2s
9604:	learn: 0.0014784	total: 16m	remaining: 39.5s
9324:	learn: 0.0015932	total: 16m	remaining: 1m 9s
8889:	learn: 0.0013519	total: 16m	remaining: 1m 59s
9791:	learn: 0.0013919	total: 16m	remaining: 20.4s
9598:	learn: 0.0013312	total: 16m	remaining: 40.1s
9605:	learn: 0.0014784	total: 16m	remaining: 39.4s
9792:	learn: 0.0013919	total: 16m	remaining: 20.3s
9325:	learn: 0.0015932	total: 16m	remaining: 1m 9s
8890:	learn: 0.0013518	total: 16m	remaining: 1m 59s
9599:	learn: 0.0013312	total: 16m	remaining: 40s
9606:	learn: 0.0014784	total: 16m	remaining: 39.3s
9326:	learn: 0.0015932	total: 16m	remaining: 1m 9s
9793:	learn: 0.0013919	total: 16m	remaining: 20.2s
9600:	learn: 0.0013312	total: 16m	remaining: 39.9s
8891:	learn: 0.0013519	total: 16m	remaining: 1m 59s
9601:	learn: 0.0013312	total: 16m	remaining: 39.8s
9607:	learn: 0.0014784	total: 16m	remaining: 39.2s
9794:	learn: 0.0013919	total: 16m	remaining: 20.1s
9327:	learn: 0.0015932	total: 16m	remaining: 1m 9s
8892:	learn: 0.0013518	total: 16m	remaining: 1m 59s
9602:	learn: 0.0013312	total: 16m	remaining: 39.7s
9608:	learn: 0.0014784	total: 16m	remaining: 39.1s
9328:	learn: 0.0015932	total: 16m 1s	remaining: 1m 9s
9795:	learn: 0.0013919	total: 16m	remaining: 20s
9609:	learn: 0.0014784	total: 16m	remaining: 39s
8893:	learn: 0.0013518	total: 16m 1s	remaining: 1m 59s
9603:	learn: 0.0013312	total: 16m 1s	remaining: 39.6s
9796:	learn: 0.0013919	total: 16m	remaining: 19.9s
9329:	learn: 0.0015932	total: 16m 1s	remaining: 1m 9s
9610:	learn: 0.0014784	total: 16m	remaining: 38.9s
8894:	learn: 0.0013518	total: 16m 1s	remaining: 1m 59s
9604:	learn: 0.0013312	total: 16m 1s	remaining: 39.5s
9797:	learn: 0.0013919	total: 16m	remaining: 19.8s
9330:	learn: 0.0015932	total: 16m 1s	remaining: 1m 8s
9611:	learn: 0.0014784	total: 16m	remaining: 38.8s
8895:	learn: 0.0013518	total: 16m 1s	remaining: 1m 59s
9605:	learn: 0.0013312	total: 16m 1s	remaining: 39.4s
9798:	learn: 0.0013919	total: 16m 1s	remaining: 19.7s
9331:	learn: 0.0015932	total: 16m 1s	remaining: 1m 8s
9612:	learn: 0.0014784	total: 16m 1s	remaining: 38.7s
9606:	learn: 0.0013312	total: 16m 1s	remaining: 39.3s
8896:	learn: 0.0013518	total: 16m 1s	remaining: 1m 59s
9799:	learn: 0.0013919	total: 16m 1s	remaining: 19.6s
9332:	learn: 0.0015932	total: 16m 1s	remaining: 1m 8s
9607:	learn: 0.0013312	total: 16m 1s	remaining: 39.2s
9613:	learn: 0.0014784	total: 16m 1s	remaining: 38.6s
8897:	learn: 0.0013518	total: 16m 1s	remaining: 1m 59s
9800:	learn: 0.0013916	total: 16m 1s	remaining: 19.5s
9614:	learn: 0.0014784	total: 16m 1s	remaining: 38.5s
9333:	learn: 0.0015932	total: 16m 1s	remaining: 1m 8s
9608:	learn: 0.0013312	total: 16m 1s	remaining: 39.1s
8898:	learn: 0.0013518	total: 16m 1s	remaining: 1m 58s
9801:	learn: 0.0013916	total: 16m 1s	remaining: 19.4s
9609:	learn: 0.0013312	total: 16m 1s	remaining: 39s
8899:	learn: 0.0013518	total: 16m 1s	remaining: 1m 58s
9615:	learn: 0.0014784	total: 16m 1s	remaining: 38.4s
9334:	learn: 0.0015932	total: 16m 1s	remaining: 1m 8s
9802:	learn: 0.0013916	total: 16m 1s	remaining: 19.3s
8900:	learn: 0.0013518	total: 16m 1s	remaining: 1m 58s
9610:	learn: 0.0013312	total: 16m 1s	remaining: 38.9s
9616:	learn: 0.0014784	total: 16m 1s	remaining: 38.3s
9803:	learn: 0.0013916	total: 16m 1s	remaining: 19.2s
9335:	learn: 0.0015932	total: 16m 1s	remaining: 1m 8s
8901:	learn: 0.0013518	total: 16m 1s	remaining: 1m 58s
9611:	learn: 0.0013312	total: 16m 1s	remaining: 38.8s
9804:	learn: 0.0013916	total: 16m 1s	remaining: 19.1s
9617:	learn: 0.0014784	total: 16m 1s	remaining: 38.2s
9336:	learn: 0.0015930	total: 16m 1s	remaining: 1m 8s
8902:	learn: 0.0013518	total: 16m 1s	remaining: 1m 58s
9612:	learn: 0.0013312	total: 16m 1s	remaining: 38.7s
9805:	learn: 0.0013916	total: 16m 1s	remaining: 19s
9618:	learn: 0.0014784	total: 16m 1s	remaining: 38.1s
9337:	learn: 0.0015930	total: 16m 2s	remaining: 1m 8s
9613:	learn: 0.0013312	total: 16m 1s	remaining: 38.6s
8903:	learn: 0.0013518	total: 16m 2s	remaining: 1m 58s
9806:	learn: 0.0013916	total: 16m 1s	remaining: 18.9s
9619:	learn: 0.0014784	total: 16m 1s	remaining: 38s
9338:	learn: 0.0015930	total: 16m 2s	remaining: 1m 8s
9620:	learn: 0.0014784	total: 16m 1s	remaining: 37.9s
9807:	learn: 0.0013916	total: 16m 1s	remaining: 18.8s
8904:	learn: 0.0013518	total: 16m 2s	remaining: 1m 58s
9614:	learn: 0.0013312	total: 16m 2s	remaining: 38.5s
9339:	learn: 0.0015930	total: 16m 2s	remaining: 1m 7s
9808:	learn: 0.0013916	total: 16m 1s	remaining: 18.7s
9621:	learn: 0.0014784	total: 16m 1s	remaining: 37.8s
9615:	learn: 0.0013312	total: 16m 2s	remaining: 38.4s
8905:	learn: 0.0013518	total: 16m 2s	remaining: 1m 58s
9340:	learn: 0.0015930	total: 16m 2s	remaining: 1m 7s
9809:	learn: 0.0013916	total: 16m 2s	remaining: 18.6s
9622:	learn: 0.0014784	total: 16m 2s	remaining: 37.7s
8906:	learn: 0.0013518	total: 16m 2s	remaining: 1m 58s
9616:	learn: 0.0013312	total: 16m 2s	remaining: 38.3s
9341:	learn: 0.0015930	total: 16m 2s	remaining: 1m 7s
9810:	learn: 0.0013916	total: 16m 2s	remaining: 18.5s
9623:	learn: 0.0014784	total: 16m 2s	remaining: 37.6s
8907:	learn: 0.0013518	total: 16m 2s	remaining: 1m 57s
9617:	learn: 0.0013312	total: 16m 2s	remaining: 38.2s
9342:	learn: 0.0015930	total: 16m 2s	remaining: 1m 7s
9811:	learn: 0.0013916	total: 16m 2s	remaining: 18.4s
9618:	learn: 0.0013312	total: 16m 2s	remaining: 38.1s
8908:	learn: 0.0013518	total: 16m 2s	remaining: 1m 57s
9624:	learn: 0.0014784	total: 16m 2s	remaining: 37.5s
9343:	learn: 0.0015930	total: 16m 2s	remaining: 1m 7s
9812:	learn: 0.0013916	total: 16m 2s	remaining: 18.3s
9619:	learn: 0.0013312	total: 16m 2s	remaining: 38s
8909:	learn: 0.0013518	total: 16m 2s	remaining: 1m 57s
9625:	learn: 0.0014784	total: 16m 2s	remaining: 37.4s
9813:	learn: 0.0013916	total: 16m 2s	remaining: 18.2s
9344:	learn: 0.0015930	total: 16m 2s	remaining: 1m 7s
9620:	learn: 0.0013312	total: 16m 2s	remaining: 37.9s
9626:	learn: 0.0014784	total: 16m 2s	remaining: 37.3s
8910:	learn: 0.0013518	total: 16m 2s	remaining: 1m 57s
9814:	learn: 0.0013916	total: 16m 2s	remaining: 18.1s
9621:	learn: 0.0013312	total: 16m 2s	remaining: 37.8s
9627:	learn: 0.0014784	total: 16m 2s	remaining: 37.2s
9345:	learn: 0.0015930	total: 16m 2s	remaining: 1m 7s
8911:	learn: 0.0013518	total: 16m 2s	remaining: 1m 57s
9815:	learn: 0.0013916	total: 16m 2s	remaining: 18s
9622:	learn: 0.0013310	total: 16m 2s	remaining: 37.7s
9628:	learn: 0.0014784	total: 16m 2s	remaining: 37.1s
9346:	learn: 0.0015930	total: 16m 2s	remaining: 1m 7s
8912:	learn: 0.0013518	total: 16m 2s	remaining: 1m 57s
9816:	learn: 0.0013916	total: 16m 2s	remaining: 17.9s
9629:	learn: 0.0014784	total: 16m 2s	remaining: 37s
9623:	learn: 0.0013310	total: 16m 2s	remaining: 37.6s
9347:	learn: 0.0015930	total: 16m 3s	remaining: 1m 7s
8913:	learn: 0.0013518	total: 16m 3s	remaining: 1m 57s
9817:	learn: 0.0013916	total: 16m 2s	remaining: 17.8s
9624:	learn: 0.0013310	total: 16m 3s	remaining: 37.5s
9630:	learn: 0.0014784	total: 16m 2s	remaining: 36.9s
9348:	learn: 0.0015930	total: 16m 3s	remaining: 1m 7s
8914:	learn: 0.0013518	total: 16m 3s	remaining: 1m 57s
9818:	learn: 0.0013916	total: 16m 2s	remaining: 17.8s
9625:	learn: 0.0013310	total: 16m 3s	remaining: 37.4s
9631:	learn: 0.0014784	total: 16m 2s	remaining: 36.8s
8915:	learn: 0.0013518	total: 16m 3s	remaining: 1m 57s
9349:	learn: 0.0015930	total: 16m 3s	remaining: 1m 6s
9819:	learn: 0.0013916	total: 16m 3s	remaining: 17.7s
9626:	learn: 0.0013310	total: 16m 3s	remaining: 37.3s
9632:	learn: 0.0014784	total: 16m 3s	remaining: 36.7s
8916:	learn: 0.0013518	total: 16m 3s	remaining: 1m 57s
9350:	learn: 0.0015926	total: 16m 3s	remaining: 1m 6s
9820:	learn: 0.0013916	total: 16m 3s	remaining: 17.6s
9627:	learn: 0.0013310	total: 16m 3s	remaining: 37.2s
9633:	learn: 0.0014784	total: 16m 3s	remaining: 36.6s
9351:	learn: 0.0015926	total: 16m 3s	remaining: 1m 6s
8917:	learn: 0.0013518	total: 16m 3s	remaining: 1m 56s
9821:	learn: 0.0013916	total: 16m 3s	remaining: 17.5s
9634:	learn: 0.0014784	total: 16m 3s	remaining: 36.5s
9628:	learn: 0.0013310	total: 16m 3s	remaining: 37.1s
8918:	learn: 0.0013518	total: 16m 3s	remaining: 1m 56s
9352:	learn: 0.0015926	total: 16m 3s	remaining: 1m 6s
9822:	learn: 0.0013916	total: 16m 3s	remaining: 17.4s
9635:	learn: 0.0014780	total: 16m 3s	remaining: 36.4s
9353:	learn: 0.0015926	total: 16m 3s	remaining: 1m 6s
9629:	learn: 0.0013310	total: 16m 3s	remaining: 37s
8919:	learn: 0.0013518	total: 16m 3s	remaining: 1m 56s
9823:	learn: 0.0013916	total: 16m 3s	remaining: 17.3s
9636:	learn: 0.0014780	total: 16m 3s	remaining: 36.3s
9630:	learn: 0.0013310	total: 16m 3s	remaining: 36.9s
9354:	learn: 0.0015925	total: 16m 3s	remaining: 1m 6s
9824:	learn: 0.0013916	total: 16m 3s	remaining: 17.2s
8920:	learn: 0.0013518	total: 16m 3s	remaining: 1m 56s
9355:	learn: 0.0015925	total: 16m 3s	remaining: 1m 6s
9637:	learn: 0.0014780	total: 16m 3s	remaining: 36.2s
9631:	learn: 0.0013310	total: 16m 3s	remaining: 36.8s
9825:	learn: 0.0013916	total: 16m 3s	remaining: 17.1s
9356:	learn: 0.0015925	total: 16m 3s	remaining: 1m 6s
8921:	learn: 0.0013518	total: 16m 3s	remaining: 1m 56s
9632:	learn: 0.0013310	total: 16m 3s	remaining: 36.7s
9826:	learn: 0.0013916	total: 16m 3s	remaining: 17s
9357:	learn: 0.0015925	total: 16m 3s	remaining: 1m 6s
9638:	learn: 0.0014780	total: 16m 3s	remaining: 36.1s
8922:	learn: 0.0013518	total: 16m 3s	remaining: 1m 56s
9827:	learn: 0.0013916	total: 16m 3s	remaining: 16.9s
9633:	learn: 0.0013310	total: 16m 3s	remaining: 36.6s
8923:	learn: 0.0013518	total: 16m 4s	remaining: 1m 56s
9358:	learn: 0.0015925	total: 16m 4s	remaining: 1m 6s
9639:	learn: 0.0014780	total: 16m 3s	remaining: 36s
9828:	learn: 0.0013916	total: 16m 3s	remaining: 16.8s
9634:	learn: 0.0013310	total: 16m 4s	remaining: 36.5s
8924:	learn: 0.0013518	total: 16m 4s	remaining: 1m 56s
9359:	learn: 0.0015925	total: 16m 4s	remaining: 1m 5s
9829:	learn: 0.0013913	total: 16m 3s	remaining: 16.7s
9640:	learn: 0.0014780	total: 16m 3s	remaining: 35.9s
9635:	learn: 0.0013310	total: 16m 4s	remaining: 36.4s
8925:	learn: 0.0013518	total: 16m 4s	remaining: 1m 56s
9830:	learn: 0.0013913	total: 16m 4s	remaining: 16.6s
9360:	learn: 0.0015925	total: 16m 4s	remaining: 1m 5s
9641:	learn: 0.0014780	total: 16m 4s	remaining: 35.8s
9636:	learn: 0.0013310	total: 16m 4s	remaining: 36.3s
8926:	learn: 0.0013518	total: 16m 4s	remaining: 1m 55s
9831:	learn: 0.0013913	total: 16m 4s	remaining: 16.5s
9642:	learn: 0.0014780	total: 16m 4s	remaining: 35.7s
9361:	learn: 0.0015925	total: 16m 4s	remaining: 1m 5s
8927:	learn: 0.0013518	total: 16m 4s	remaining: 1m 55s
9637:	learn: 0.0013310	total: 16m 4s	remaining: 36.2s
9832:	learn: 0.0013913	total: 16m 4s	remaining: 16.4s
9362:	learn: 0.0015925	total: 16m 4s	remaining: 1m 5s
9643:	learn: 0.0014780	total: 16m 4s	remaining: 35.6s
8928:	learn: 0.0013518	total: 16m 4s	remaining: 1m 55s
9638:	learn: 0.0013310	total: 16m 4s	remaining: 36.1s
9833:	learn: 0.0013913	total: 16m 4s	remaining: 16.3s
9363:	learn: 0.0015925	total: 16m 4s	remaining: 1m 5s
9644:	learn: 0.0014780	total: 16m 4s	remaining: 35.5s
9639:	learn: 0.0013308	total: 16m 4s	remaining: 36s
8929:	learn: 0.0013518	total: 16m 4s	remaining: 1m 55s
9834:	learn: 0.0013913	total: 16m 4s	remaining: 16.2s
9640:	learn: 0.0013308	total: 16m 4s	remaining: 35.9s
9645:	learn: 0.0014780	total: 16m 4s	remaining: 35.4s
9364:	learn: 0.0015925	total: 16m 4s	remaining: 1m 5s
9641:	learn: 0.0013308	total: 16m 4s	remaining: 35.8s
8930:	learn: 0.0013518	total: 16m 4s	remaining: 1m 55s
9835:	learn: 0.0013913	total: 16m 4s	remaining: 16.1s
9646:	learn: 0.0014780	total: 16m 4s	remaining: 35.3s
9365:	learn: 0.0015925	total: 16m 4s	remaining: 1m 5s
9642:	learn: 0.0013308	total: 16m 4s	remaining: 35.7s
8931:	learn: 0.0013518	total: 16m 4s	remaining: 1m 55s
9836:	learn: 0.0013913	total: 16m 4s	remaining: 16s
9366:	learn: 0.0015925	total: 16m 4s	remaining: 1m 5s
9647:	learn: 0.0014780	total: 16m 4s	remaining: 35.2s
9643:	learn: 0.0013308	total: 16m 4s	remaining: 35.6s
9837:	learn: 0.0013913	total: 16m 4s	remaining: 15.9s
9367:	learn: 0.0015925	total: 16m 5s	remaining: 1m 5s
8932:	learn: 0.0013517	total: 16m 5s	remaining: 1m 55s
9648:	learn: 0.0014780	total: 16m 4s	remaining: 35.1s
9644:	learn: 0.0013308	total: 16m 5s	remaining: 35.5s
9838:	learn: 0.0013913	total: 16m 4s	remaining: 15.8s
8933:	learn: 0.0013517	total: 16m 5s	remaining: 1m 55s
9368:	learn: 0.0015925	total: 16m 5s	remaining: 1m 5s
9649:	learn: 0.0014780	total: 16m 4s	remaining: 35s
9645:	learn: 0.0013308	total: 16m 5s	remaining: 35.4s
9839:	learn: 0.0013913	total: 16m 4s	remaining: 15.7s
9369:	learn: 0.0015925	total: 16m 5s	remaining: 1m 4s
8934:	learn: 0.0013518	total: 16m 5s	remaining: 1m 55s
9650:	learn: 0.0014780	total: 16m 4s	remaining: 34.9s
8935:	learn: 0.0013518	total: 16m 5s	remaining: 1m 54s
9646:	learn: 0.0013308	total: 16m 5s	remaining: 35.3s
9840:	learn: 0.0013913	total: 16m 5s	remaining: 15.6s
9370:	learn: 0.0015925	total: 16m 5s	remaining: 1m 4s
9651:	learn: 0.0014780	total: 16m 5s	remaining: 34.8s
8936:	learn: 0.0013518	total: 16m 5s	remaining: 1m 54s
9647:	learn: 0.0013308	total: 16m 5s	remaining: 35.2s
9371:	learn: 0.0015925	total: 16m 5s	remaining: 1m 4s
9841:	learn: 0.0013913	total: 16m 5s	remaining: 15.5s
9652:	learn: 0.0014780	total: 16m 5s	remaining: 34.7s
9842:	learn: 0.0013913	total: 16m 5s	remaining: 15.4s
8937:	learn: 0.0013517	total: 16m 5s	remaining: 1m 54s
9648:	learn: 0.0013308	total: 16m 5s	remaining: 35.1s
9372:	learn: 0.0015925	total: 16m 5s	remaining: 1m 4s
9653:	learn: 0.0014780	total: 16m 5s	remaining: 34.6s
9843:	learn: 0.0013913	total: 16m 5s	remaining: 15.3s
9649:	learn: 0.0013308	total: 16m 5s	remaining: 35s
8938:	learn: 0.0013517	total: 16m 5s	remaining: 1m 54s
9373:	learn: 0.0015925	total: 16m 5s	remaining: 1m 4s
9844:	learn: 0.0013913	total: 16m 5s	remaining: 15.2s
9654:	learn: 0.0014780	total: 16m 5s	remaining: 34.5s
9650:	learn: 0.0013308	total: 16m 5s	remaining: 34.9s
9845:	learn: 0.0013913	total: 16m 5s	remaining: 15.1s
8939:	learn: 0.0013518	total: 16m 5s	remaining: 1m 54s
9651:	learn: 0.0013308	total: 16m 5s	remaining: 34.8s
9655:	learn: 0.0014780	total: 16m 5s	remaining: 34.4s
9374:	learn: 0.0015925	total: 16m 5s	remaining: 1m 4s
9846:	learn: 0.0013913	total: 16m 5s	remaining: 15s
8940:	learn: 0.0013517	total: 16m 5s	remaining: 1m 54s
9652:	learn: 0.0013308	total: 16m 5s	remaining: 34.7s
9656:	learn: 0.0014780	total: 16m 5s	remaining: 34.3s
9375:	learn: 0.0015925	total: 16m 5s	remaining: 1m 4s
9653:	learn: 0.0013308	total: 16m 5s	remaining: 34.6s
8941:	learn: 0.0013518	total: 16m 5s	remaining: 1m 54s
9847:	learn: 0.0013913	total: 16m 5s	remaining: 14.9s
9657:	learn: 0.0014780	total: 16m 5s	remaining: 34.2s
8942:	learn: 0.0013517	total: 16m 6s	remaining: 1m 54s
9376:	learn: 0.0015925	total: 16m 6s	remaining: 1m 4s
9848:	learn: 0.0013908	total: 16m 5s	remaining: 14.8s
9654:	learn: 0.0013308	total: 16m 6s	remaining: 34.5s
9658:	learn: 0.0014780	total: 16m 5s	remaining: 34.1s
8943:	learn: 0.0013517	total: 16m 6s	remaining: 1m 54s
9655:	learn: 0.0013308	total: 16m 6s	remaining: 34.4s

9377:	learn: 0.0015925	total: 16m 6s	remaining: 1m 4s
9849:	learn: 0.0013905	total: 16m 5s	remaining: 14.7s
9659:	learn: 0.0014780	total: 16m 5s	remaining: 34s
8944:	learn: 0.0013517	total: 16m 6s	remaining: 1m 53s
9656:	learn: 0.0013308	total: 16m 6s	remaining: 34.3s
9660:	learn: 0.0014780	total: 16m 5s	remaining: 33.9s
9850:	learn: 0.0013905	total: 16m 6s	remaining: 14.6s
9378:	learn: 0.0015925	total: 16m 6s	remaining: 1m 3s
9657:	learn: 0.0013308	total: 16m 6s	remaining: 34.2s
9851:	learn: 0.0013904	total: 16m 6s	remaining: 14.5s
9661:	learn: 0.0014780	total: 16m 6s	remaining: 33.8s
8945:	learn: 0.0013517	total: 16m 6s	remaining: 1m 53s
9379:	learn: 0.0015925	total: 16m 6s	remaining: 1m 3s
9658:	learn: 0.0013308	total: 16m 6s	remaining: 34.1s
9852:	learn: 0.0013904	total: 16m 6s	remaining: 14.4s
9662:	learn: 0.0014780	total: 16m 6s	remaining: 33.7s
9380:	learn: 0.0015925	total: 16m 6s	remaining: 1m 3s
8946:	learn: 0.0013517	total: 16m 6s	remaining: 1m 53s
9659:	learn: 0.0013308	total: 16m 6s	remaining: 34s
9663:	learn: 0.0014780	total: 16m 6s	remaining: 33.6s
9853:	learn: 0.0013904	total: 16m 6s	remaining: 14.3s
9381:	learn: 0.0015925	total: 16m 6s	remaining: 1m 3s
8947:	learn: 0.0013517	total: 16m 6s	remaining: 1m 53s
9660:	learn: 0.0013308	total: 16m 6s	remaining: 33.9s
9382:	learn: 0.0015925	total: 16m 6s	remaining: 1m 3s
8948:	learn: 0.0013517	total: 16m 6s	remaining: 1m 53s
9854:	learn: 0.0013904	total: 16m 6s	remaining: 14.2s
9664:	learn: 0.0014780	total: 16m 6s	remaining: 33.5s
9661:	learn: 0.0013307	total: 16m 6s	remaining: 33.8s
9383:	learn: 0.0015925	total: 16m 6s	remaining: 1m 3s
9665:	learn: 0.0014780	total: 16m 6s	remaining: 33.4s
9855:	learn: 0.0013904	total: 16m 6s	remaining: 14.1s
8949:	learn: 0.0013517	total: 16m 6s	remaining: 1m 53s
9662:	learn: 0.0013307	total: 16m 6s	remaining: 33.7s
9384:	learn: 0.0015925	total: 16m 6s	remaining: 1m 3s
9666:	learn: 0.0014780	total: 16m 6s	remaining: 33.3s
9856:	learn: 0.0013904	total: 16m 6s	remaining: 14s
8950:	learn: 0.0013517	total: 16m 6s	remaining: 1m 53s
9663:	learn: 0.0013307	total: 16m 6s	remaining: 33.6s
9385:	learn: 0.0015925	total: 16m 6s	remaining: 1m 3s
9667:	learn: 0.0014780	total: 16m 6s	remaining: 33.2s
9857:	learn: 0.0013904	total: 16m 6s	remaining: 13.9s
8951:	learn: 0.0013517	total: 16m 6s	remaining: 1m 53s
9664:	learn: 0.0013308	total: 16m 6s	remaining: 33.5s
9386:	learn: 0.0015925	total: 16m 7s	remaining: 1m 3s
9668:	learn: 0.0014780	total: 16m 6s	remaining: 33.1s
8952:	learn: 0.0013517	total: 16m 7s	remaining: 1m 53s
9858:	learn: 0.0013904	total: 16m 6s	remaining: 13.8s
9665:	learn: 0.0013308	total: 16m 7s	remaining: 33.4s
9387:	learn: 0.0015925	total: 16m 7s	remaining: 1m 3s
9669:	learn: 0.0014780	total: 16m 6s	remaining: 33s
9859:	learn: 0.0013904	total: 16m 6s	remaining: 13.7s
8953:	learn: 0.0013518	total: 16m 7s	remaining: 1m 52s
9666:	learn: 0.0013306	total: 16m 7s	remaining: 33.3s
9388:	learn: 0.0015925	total: 16m 7s	remaining: 1m 2s
9860:	learn: 0.0013905	total: 16m 7s	remaining: 13.6s
9670:	learn: 0.0014780	total: 16m 6s	remaining: 32.9s
9667:	learn: 0.0013307	total: 16m 7s	remaining: 33.2s
8954:	learn: 0.0013517	total: 16m 7s	remaining: 1m 52s
9389:	learn: 0.0015925	total: 16m 7s	remaining: 1m 2s
9671:	learn: 0.0014780	total: 16m 7s	remaining: 32.8s
9861:	learn: 0.0013904	total: 16m 7s	remaining: 13.5s
9668:	learn: 0.0013307	total: 16m 7s	remaining: 33.1s
8955:	learn: 0.0013517	total: 16m 7s	remaining: 1m 52s
9390:	learn: 0.0015925	total: 16m 7s	remaining: 1m 2s
9672:	learn: 0.0014780	total: 16m 7s	remaining: 32.7s
9862:	learn: 0.0013904	total: 16m 7s	remaining: 13.4s
9669:	learn: 0.0013307	total: 16m 7s	remaining: 33s
9673:	learn: 0.0014780	total: 16m 7s	remaining: 32.6s
9391:	learn: 0.0015925	total: 16m 7s	remaining: 1m 2s
8956:	learn: 0.0013517	total: 16m 7s	remaining: 1m 52s
9670:	learn: 0.0013307	total: 16m 7s	remaining: 32.9s
9863:	learn: 0.0013904	total: 16m 7s	remaining: 13.3s
9674:	learn: 0.0014780	total: 16m 7s	remaining: 32.5s
9392:	learn: 0.0015925	total: 16m 7s	remaining: 1m 2s
9671:	learn: 0.0013307	total: 16m 7s	remaining: 32.8s
8957:	learn: 0.0013517	total: 16m 7s	remaining: 1m 52s
9864:	learn: 0.0013904	total: 16m 7s	remaining: 13.2s
9675:	learn: 0.0014780	total: 16m 7s	remaining: 32.4s
9393:	learn: 0.0015925	total: 16m 7s	remaining: 1m 2s
9672:	learn: 0.0013307	total: 16m 7s	remaining: 32.7s
9865:	learn: 0.0013903	total: 16m 7s	remaining: 13.1s
8958:	learn: 0.0013517	total: 16m 7s	remaining: 1m 52s
9676:	learn: 0.0014780	total: 16m 7s	remaining: 32.3s
9866:	learn: 0.0013902	total: 16m 7s	remaining: 13s
9394:	learn: 0.0015925	total: 16m 7s	remaining: 1m 2s
9673:	learn: 0.0013307	total: 16m 7s	remaining: 32.6s
8959:	learn: 0.0013517	total: 16m 7s	remaining: 1m 52s
9677:	learn: 0.0014780	total: 16m 7s	remaining: 32.2s
9395:	learn: 0.0015925	total: 16m 7s	remaining: 1m 2s
9867:	learn: 0.0013902	total: 16m 7s	remaining: 12.9s
9674:	learn: 0.0013307	total: 16m 7s	remaining: 32.5s
8960:	learn: 0.0013517	total: 16m 7s	remaining: 1m 52s
9678:	learn: 0.0014780	total: 16m 7s	remaining: 32.1s
9868:	learn: 0.0013902	total: 16m 7s	remaining: 12.8s
9396:	learn: 0.0015925	total: 16m 8s	remaining: 1m 2s
9675:	learn: 0.0013307	total: 16m 7s	remaining: 32.4s
9679:	learn: 0.0014780	total: 16m 7s	remaining: 32s
8961:	learn: 0.0013517	total: 16m 8s	remaining: 1m 52s
9869:	learn: 0.0013902	total: 16m 7s	remaining: 12.7s
9397:	learn: 0.0015925	total: 16m 8s	remaining: 1m 2s
9676:	learn: 0.0013307	total: 16m 8s	remaining: 32.3s
9680:	learn: 0.0014780	total: 16m 7s	remaining: 31.9s
9870:	learn: 0.0013902	total: 16m 7s	remaining: 12.6s
8962:	learn: 0.0013517	total: 16m 8s	remaining: 1m 52s
9398:	learn: 0.0015925	total: 16m 8s	remaining: 1m 1s
9677:	learn: 0.0013307	total: 16m 8s	remaining: 32.2s
9681:	learn: 0.0014780	total: 16m 7s	remaining: 31.8s
9871:	learn: 0.0013902	total: 16m 8s	remaining: 12.6s
9399:	learn: 0.0015925	total: 16m 8s	remaining: 1m 1s
8963:	learn: 0.0013517	total: 16m 8s	remaining: 1m 51s
9682:	learn: 0.0014780	total: 16m 8s	remaining: 31.7s
9678:	learn: 0.0013307	total: 16m 8s	remaining: 32.1s
9400:	learn: 0.0015925	total: 16m 8s	remaining: 1m 1s
9872:	learn: 0.0013902	total: 16m 8s	remaining: 12.5s
9679:	learn: 0.0013307	total: 16m 8s	remaining: 32s
8964:	learn: 0.0013517	total: 16m 8s	remaining: 1m 51s
9401:	learn: 0.0015925	total: 16m 8s	remaining: 1m 1s
9683:	learn: 0.0014780	total: 16m 8s	remaining: 31.6s
9680:	learn: 0.0013307	total: 16m 8s	remaining: 31.9s
9873:	learn: 0.0013902	total: 16m 8s	remaining: 12.4s
8965:	learn: 0.0013517	total: 16m 8s	remaining: 1m 51s
9402:	learn: 0.0015925	total: 16m 8s	remaining: 1m 1s
9684:	learn: 0.0014780	total: 16m 8s	remaining: 31.5s
9681:	learn: 0.0013307	total: 16m 8s	remaining: 31.8s
9874:	learn: 0.0013902	total: 16m 8s	remaining: 12.3s
8966:	learn: 0.0013517	total: 16m 8s	remaining: 1m 51s
9403:	learn: 0.0015925	total: 16m 8s	remaining: 1m 1s
9685:	learn: 0.0014780	total: 16m 8s	remaining: 31.4s
9682:	learn: 0.0013307	total: 16m 8s	remaining: 31.7s
9875:	learn: 0.0013902	total: 16m 8s	remaining: 12.2s
8967:	learn: 0.0013517	total: 16m 8s	remaining: 1m 51s
9404:	learn: 0.0015925	total: 16m 8s	remaining: 1m 1s
9686:	learn: 0.0014780	total: 16m 8s	remaining: 31.3s
9876:	learn: 0.0013902	total: 16m 8s	remaining: 12.1s
9405:	learn: 0.0015925	total: 16m 8s	remaining: 1m 1s
9687:	learn: 0.0014780	total: 16m 8s	remaining: 31.2s
8968:	learn: 0.0013517	total: 16m 8s	remaining: 1m 51s
9683:	learn: 0.0013307	total: 16m 8s	remaining: 31.6s
9406:	learn: 0.0015925	total: 16m 8s	remaining: 1m 1s
9877:	learn: 0.0013902	total: 16m 8s	remaining: 12s
9684:	learn: 0.0013307	total: 16m 8s	remaining: 31.5s
8969:	learn: 0.0013517	total: 16m 8s	remaining: 1m 51s
9688:	learn: 0.0014780	total: 16m 8s	remaining: 31.1s
9878:	learn: 0.0013902	total: 16m 8s	remaining: 11.9s
9407:	learn: 0.0015925	total: 16m 9s	remaining: 1m
9685:	learn: 0.0013303	total: 16m 9s	remaining: 31.4s
8970:	learn: 0.0013517	total: 16m 9s	remaining: 1m 51s
9689:	learn: 0.0014780	total: 16m 8s	remaining: 31s
9408:	learn: 0.0015925	total: 16m 9s	remaining: 1m
9879:	learn: 0.0013902	total: 16m 8s	remaining: 11.8s
9686:	learn: 0.0013298	total: 16m 9s	remaining: 31.3s
9690:	learn: 0.0014777	total: 16m 8s	remaining: 30.9s
9409:	learn: 0.0015925	total: 16m 9s	remaining: 1m
8971:	learn: 0.0013517	total: 16m 9s	remaining: 1m 51s
9880:	learn: 0.0013902	total: 16m 8s	remaining: 11.7s
9691:	learn: 0.0014777	total: 16m 8s	remaining: 30.8s
9687:	learn: 0.0013295	total: 16m 9s	remaining: 31.2s
9410:	learn: 0.0015925	total: 16m 9s	remaining: 1m
8972:	learn: 0.0013517	total: 16m 9s	remaining: 1m 50s
9881:	learn: 0.0013902	total: 16m 9s	remaining: 11.6s
9692:	learn: 0.0014777	total: 16m 9s	remaining: 30.7s
9688:	learn: 0.0013290	total: 16m 9s	remaining: 31.1s
9882:	learn: 0.0013902	total: 16m 9s	remaining: 11.5s
9411:	learn: 0.0015925	total: 16m 9s	remaining: 1m
8973:	learn: 0.0013517	total: 16m 9s	remaining: 1m 50s
9693:	learn: 0.0014777	total: 16m 9s	remaining: 30.6s
9689:	learn: 0.0013290	total: 16m 9s	remaining: 31s
8974:	learn: 0.0013517	total: 16m 9s	remaining: 1m 50s
9412:	learn: 0.0015925	total: 16m 9s	remaining: 1m
9883:	learn: 0.0013902	total: 16m 9s	remaining: 11.4s
9694:	learn: 0.0014777	total: 16m 9s	remaining: 30.5s
9690:	learn: 0.0013290	total: 16m 9s	remaining: 30.9s
9695:	learn: 0.0014777	total: 16m 9s	remaining: 30.4s
9884:	learn: 0.0013902	total: 16m 9s	remaining: 11.3s
8975:	learn: 0.0013517	total: 16m 9s	remaining: 1m 50s
9413:	learn: 0.0015925	total: 16m 9s	remaining: 1m
9691:	learn: 0.0013291	total: 16m 9s	remaining: 30.8s
9696:	learn: 0.0014777	total: 16m 9s	remaining: 30.3s
9885:	learn: 0.0013902	total: 16m 9s	remaining: 11.2s
9414:	learn: 0.0015925	total: 16m 9s	remaining: 1m
9692:	learn: 0.0013290	total: 16m 9s	remaining: 30.7s
8976:	learn: 0.0013517	total: 16m 9s	remaining: 1m 50s
9697:	learn: 0.0014777	total: 16m 9s	remaining: 30.2s
9886:	learn: 0.0013902	total: 16m 9s	remaining: 11.1s
9415:	learn: 0.0015921	total: 16m 9s	remaining: 1m
9693:	learn: 0.0013288	total: 16m 9s	remaining: 30.6s
9698:	learn: 0.0014777	total: 16m 9s	remaining: 30.1s
9887:	learn: 0.0013902	total: 16m 9s	remaining: 11s
8977:	learn: 0.0013517	total: 16m 9s	remaining: 1m 50s
9416:	learn: 0.0015920	total: 16m 9s	remaining: 1m
9694:	learn: 0.0013288	total: 16m 9s	remaining: 30.5s
9699:	learn: 0.0014777	total: 16m 9s	remaining: 30s
8978:	learn: 0.0013517	total: 16m 10s	remaining: 1m 50s
9888:	learn: 0.0013902	total: 16m 9s	remaining: 10.9s
9417:	learn: 0.0015916	total: 16m 10s	remaining: 59.9s
9695:	learn: 0.0013288	total: 16m 9s	remaining: 30.4s
9700:	learn: 0.0014777	total: 16m 9s	remaining: 29.9s
9889:	learn: 0.0013902	total: 16m 9s	remaining: 10.8s
8979:	learn: 0.0013517	total: 16m 10s	remaining: 1m 50s
9418:	learn: 0.0015916	total: 16m 10s	remaining: 59.8s
9696:	learn: 0.0013288	total: 16m 10s	remaining: 30.3s
9890:	learn: 0.0013902	total: 16m 9s	remaining: 10.7s
9419:	learn: 0.0015916	total: 16m 10s	remaining: 59.7s
9701:	learn: 0.0014777	total: 16m 9s	remaining: 29.8s
9697:	learn: 0.0013288	total: 16m 10s	remaining: 30.2s
8980:	learn: 0.0013517	total: 16m 10s	remaining: 1m 50s
9891:	learn: 0.0013902	total: 16m 10s	remaining: 10.6s
9702:	learn: 0.0014777	total: 16m 10s	remaining: 29.7s
9420:	learn: 0.0015916	total: 16m 10s	remaining: 59.6s
9698:	learn: 0.0013287	total: 16m 10s	remaining: 30.1s
8981:	learn: 0.0013517	total: 16m 10s	remaining: 1m 49s
9892:	learn: 0.0013902	total: 16m 10s	remaining: 10.5s
9703:	learn: 0.0014777	total: 16m 10s	remaining: 29.6s
9421:	learn: 0.0015916	total: 16m 10s	remaining: 59.5s
9699:	learn: 0.0013287	total: 16m 10s	remaining: 30s
9893:	learn: 0.0013902	total: 16m 10s	remaining: 10.4s
9704:	learn: 0.0014777	total: 16m 10s	remaining: 29.5s
8982:	learn: 0.0013517	total: 16m 10s	remaining: 1m 49s
9422:	learn: 0.0015916	total: 16m 10s	remaining: 59.4s
9894:	learn: 0.0013902	total: 16m 10s	remaining: 10.3s
9705:	learn: 0.0014777	total: 16m 10s	remaining: 29.4s
9700:	learn: 0.0013287	total: 16m 10s	remaining: 29.9s
8983:	learn: 0.0013517	total: 16m 10s	remaining: 1m 49s
9895:	learn: 0.0013902	total: 16m 10s	remaining: 10.2s
9423:	learn: 0.0015916	total: 16m 10s	remaining: 59.3s
9701:	learn: 0.0013287	total: 16m 10s	remaining: 29.8s
9706:	learn: 0.0014777	total: 16m 10s	remaining: 29.3s
9896:	learn: 0.0013902	total: 16m 10s	remaining: 10.1s
8984:	learn: 0.0013517	total: 16m 10s	remaining: 1m 49s
9424:	learn: 0.0015916	total: 16m 10s	remaining: 59.2s
9702:	learn: 0.0013287	total: 16m 10s	remaining: 29.7s
9707:	learn: 0.0014777	total: 16m 10s	remaining: 29.2s
9897:	learn: 0.0013902	total: 16m 10s	remaining: 10s
8985:	learn: 0.0013517	total: 16m 10s	remaining: 1m 49s
9703:	learn: 0.0013287	total: 16m 10s	remaining: 29.6s
9425:	learn: 0.0015916	total: 16m 10s	remaining: 59.1s
9898:	learn: 0.0013902	total: 16m 10s	remaining: 9.9s
9708:	learn: 0.0014777	total: 16m 10s	remaining: 29.1s
9704:	learn: 0.0013287	total: 16m 10s	remaining: 29.5s
9426:	learn: 0.0015916	total: 16m 10s	remaining: 59s
8986:	learn: 0.0013517	total: 16m 10s	remaining: 1m 49s
9899:	learn: 0.0013902	total: 16m 10s	remaining: 9.8s
9709:	learn: 0.0014777	total: 16m 10s	remaining: 29s
9705:	learn: 0.0013287	total: 16m 10s	remaining: 29.4s
9427:	learn: 0.0015916	total: 16m 11s	remaining: 58.9s
9900:	learn: 0.0013902	total: 16m 10s	remaining: 9.71s
8987:	learn: 0.0013517	total: 16m 11s	remaining: 1m 49s
9710:	learn: 0.0014777	total: 16m 10s	remaining: 28.9s
9901:	learn: 0.0013902	total: 16m 10s	remaining: 9.61s
9428:	learn: 0.0015916	total: 16m 11s	remaining: 58.8s
9706:	learn: 0.0013287	total: 16m 11s	remaining: 29.3s
8988:	learn: 0.0013517	total: 16m 11s	remaining: 1m 49s
9711:	learn: 0.0014776	total: 16m 10s	remaining: 28.8s
9902:	learn: 0.0013901	total: 16m 10s	remaining: 9.51s
9429:	learn: 0.0015913	total: 16m 11s	remaining: 58.7s
9707:	learn: 0.0013287	total: 16m 11s	remaining: 29.2s
8989:	learn: 0.0013517	total: 16m 11s	remaining: 1m 49s
9712:	learn: 0.0014776	total: 16m 11s	remaining: 28.7s
9903:	learn: 0.0013901	total: 16m 11s	remaining: 9.41s
9430:	learn: 0.0015913	total: 16m 11s	remaining: 58.6s
9708:	learn: 0.0013287	total: 16m 11s	remaining: 29.1s
8990:	learn: 0.0013517	total: 16m 11s	remaining: 1m 49s
9713:	learn: 0.0014776	total: 16m 11s	remaining: 28.6s
9431:	learn: 0.0015913	total: 16m 11s	remaining: 58.5s
9904:	learn: 0.0013901	total: 16m 11s	remaining: 9.31s
9709:	learn: 0.0013287	total: 16m 11s	remaining: 29s
8991:	learn: 0.0013517	total: 16m 11s	remaining: 1m 48s
9714:	learn: 0.0014776	total: 16m 11s	remaining: 28.5s
9432:	learn: 0.0015913	total: 16m 11s	remaining: 58.4s
9905:	learn: 0.0013900	total: 16m 11s	remaining: 9.22s
9715:	learn: 0.0014776	total: 16m 11s	remaining: 28.4s
8992:	learn: 0.0013517	total: 16m 11s	remaining: 1m 48s
9710:	learn: 0.0013287	total: 16m 11s	remaining: 28.9s
9433:	learn: 0.0015913	total: 16m 11s	remaining: 58.3s
9906:	learn: 0.0013900	total: 16m 11s	remaining: 9.12s
9716:	learn: 0.0014776	total: 16m 11s	remaining: 28.3s
9711:	learn: 0.0013287	total: 16m 11s	remaining: 28.8s
8993:	learn: 0.0013517	total: 16m 11s	remaining: 1m 48s
9434:	learn: 0.0015913	total: 16m 11s	remaining: 58.2s
9907:	learn: 0.0013900	total: 16m 11s	remaining: 9.02s
9712:	learn: 0.0013287	total: 16m 11s	remaining: 28.7s
8994:	learn: 0.0013516	total: 16m 11s	remaining: 1m 48s
9717:	learn: 0.0014776	total: 16m 11s	remaining: 28.2s
9435:	learn: 0.0015913	total: 16m 11s	remaining: 58.1s
9908:	learn: 0.0013900	total: 16m 11s	remaining: 8.92s
9713:	learn: 0.0013287	total: 16m 11s	remaining: 28.6s
9909:	learn: 0.0013900	total: 16m 11s	remaining: 8.82s
9718:	learn: 0.0014776	total: 16m 11s	remaining: 28.1s
8995:	learn: 0.0013516	total: 16m 11s	remaining: 1m 48s
9436:	learn: 0.0015913	total: 16m 11s	remaining: 58s
9714:	learn: 0.0013287	total: 16m 11s	remaining: 28.5s
9910:	learn: 0.0013900	total: 16m 11s	remaining: 8.73s
9719:	learn: 0.0014776	total: 16m 11s	remaining: 28s
8996:	learn: 0.0013517	total: 16m 12s	remaining: 1m 48s
9715:	learn: 0.0013287	total: 16m 12s	remaining: 28.4s
9437:	learn: 0.0015913	total: 16m 12s	remaining: 57.9s
9720:	learn: 0.0014776	total: 16m 11s	remaining: 27.9s
9911:	learn: 0.0013900	total: 16m 11s	remaining: 8.63s
8997:	learn: 0.0013516	total: 16m 12s	remaining: 1m 48s
9438:	learn: 0.0015913	total: 16m 12s	remaining: 57.8s

9716:	learn: 0.0013287	total: 16m 12s	remaining: 28.3s
9721:	learn: 0.0014776	total: 16m 11s	remaining: 27.8s
9912:	learn: 0.0013900	total: 16m 11s	remaining: 8.53s
8998:	learn: 0.0013516	total: 16m 12s	remaining: 1m 48s
9439:	learn: 0.0015913	total: 16m 12s	remaining: 57.7s
9717:	learn: 0.0013287	total: 16m 12s	remaining: 28.2s
9722:	learn: 0.0014776	total: 16m 12s	remaining: 27.7s
9913:	learn: 0.0013900	total: 16m 12s	remaining: 8.43s
8999:	learn: 0.0013516	total: 16m 12s	remaining: 1m 48s
9440:	learn: 0.0015913	total: 16m 12s	remaining: 57.6s
9718:	learn: 0.0013287	total: 16m 12s	remaining: 28.1s
9723:	learn: 0.0014776	total: 16m 12s	remaining: 27.6s
9914:	learn: 0.0013900	total: 16m 12s	remaining: 8.33s
9000:	learn: 0.0013516	total: 16m 12s	remaining: 1m 47s
9441:	learn: 0.0015913	total: 16m 12s	remaining: 57.5s
9719:	learn: 0.0013287	total: 16m 12s	remaining: 28s
9724:	learn: 0.0014776	total: 16m 12s	remaining: 27.5s
9915:	learn: 0.0013900	total: 16m 12s	remaining: 8.24s
9001:	learn: 0.0013516	total: 16m 12s	remaining: 1m 47s
9720:	learn: 0.0013287	total: 16m 12s	remaining: 27.9s
9442:	learn: 0.0015913	total: 16m 12s	remaining: 57.4s
9916:	learn: 0.0013900	total: 16m 12s	remaining: 8.14s
9725:	learn: 0.0014776	total: 16m 12s	remaining: 27.4s
9002:	learn: 0.0013516	total: 16m 12s	remaining: 1m 47s
9917:	learn: 0.0013900	total: 16m 12s	remaining: 8.04s
9726:	learn: 0.0014776	total: 16m 12s	remaining: 27.3s
9443:	learn: 0.0015913	total: 16m 12s	remaining: 57.3s
9721:	learn: 0.0013287	total: 16m 12s	remaining: 27.8s
9444:	learn: 0.0015913	total: 16m 12s	remaining: 57.2s
9003:	learn: 0.0013516	total: 16m 12s	remaining: 1m 47s
9918:	learn: 0.0013900	total: 16m 12s	remaining: 7.94s
9727:	learn: 0.0014776	total: 16m 12s	remaining: 27.2s
9722:	learn: 0.0013287	total: 16m 12s	remaining: 27.7s
9445:	learn: 0.0015910	total: 16m 12s	remaining: 57.1s
9004:	learn: 0.0013516	total: 16m 12s	remaining: 1m 47s
9723:	learn: 0.0013287	total: 16m 12s	remaining: 27.6s
9728:	learn: 0.0014776	total: 16m 12s	remaining: 27.1s
9919:	learn: 0.0013900	total: 16m 12s	remaining: 7.84s
9446:	learn: 0.0015910	total: 16m 12s	remaining: 57s
9724:	learn: 0.0013287	total: 16m 12s	remaining: 27.5s
9005:	learn: 0.0013516	total: 16m 12s	remaining: 1m 47s
9729:	learn: 0.0014776	total: 16m 12s	remaining: 27s
9920:	learn: 0.0013900	total: 16m 12s	remaining: 7.75s
9447:	learn: 0.0015910	total: 16m 13s	remaining: 56.9s
9725:	learn: 0.0013287	total: 16m 13s	remaining: 27.4s
9006:	learn: 0.0013516	total: 16m 13s	remaining: 1m 47s
9921:	learn: 0.0013900	total: 16m 12s	remaining: 7.65s
9730:	learn: 0.0014776	total: 16m 12s	remaining: 26.9s
9448:	learn: 0.0015910	total: 16m 13s	remaining: 56.7s
9922:	learn: 0.0013900	total: 16m 12s	remaining: 7.55s
9726:	learn: 0.0013287	total: 16m 13s	remaining: 27.3s
9007:	learn: 0.0013516	total: 16m 13s	remaining: 1m 47s
9731:	learn: 0.0014776	total: 16m 12s	remaining: 26.8s
9923:	learn: 0.0013900	total: 16m 13s	remaining: 7.45s
9449:	learn: 0.0015910	total: 16m 13s	remaining: 56.6s
9008:	learn: 0.0013516	total: 16m 13s	remaining: 1m 47s
9727:	learn: 0.0013287	total: 16m 13s	remaining: 27.2s
9732:	learn: 0.0014776	total: 16m 13s	remaining: 26.7s
9924:	learn: 0.0013900	total: 16m 13s	remaining: 7.35s
9450:	learn: 0.0015910	total: 16m 13s	remaining: 56.5s
9728:	learn: 0.0013287	total: 16m 13s	remaining: 27.1s
9009:	learn: 0.0013516	total: 16m 13s	remaining: 1m 46s
9733:	learn: 0.0014776	total: 16m 13s	remaining: 26.6s
9925:	learn: 0.0013900	total: 16m 13s	remaining: 7.25s
9729:	learn: 0.0013287	total: 16m 13s	remaining: 27s
9451:	learn: 0.0015910	total: 16m 13s	remaining: 56.4s
9010:	learn: 0.0013516	total: 16m 13s	remaining: 1m 46s
9926:	learn: 0.0013900	total: 16m 13s	remaining: 7.16s
9734:	learn: 0.0014775	total: 16m 13s	remaining: 26.5s
9730:	learn: 0.0013287	total: 16m 13s	remaining: 26.9s
9452:	learn: 0.0015910	total: 16m 13s	remaining: 56.3s
9927:	learn: 0.0013900	total: 16m 13s	remaining: 7.06s
9011:	learn: 0.0013516	total: 16m 13s	remaining: 1m 46s
9735:	learn: 0.0014770	total: 16m 13s	remaining: 26.4s
9453:	learn: 0.0015910	total: 16m 13s	remaining: 56.2s
9731:	learn: 0.0013287	total: 16m 13s	remaining: 26.8s
9928:	learn: 0.0013900	total: 16m 13s	remaining: 6.96s
9454:	learn: 0.0015910	total: 16m 13s	remaining: 56.1s
9736:	learn: 0.0014770	total: 16m 13s	remaining: 26.3s
9732:	learn: 0.0013287	total: 16m 13s	remaining: 26.7s
9012:	learn: 0.0013516	total: 16m 13s	remaining: 1m 46s
9929:	learn: 0.0013900	total: 16m 13s	remaining: 6.86s
9733:	learn: 0.0013287	total: 16m 13s	remaining: 26.6s
9455:	learn: 0.0015910	total: 16m 13s	remaining: 56s
9737:	learn: 0.0014770	total: 16m 13s	remaining: 26.2s
9930:	learn: 0.0013900	total: 16m 13s	remaining: 6.76s
9013:	learn: 0.0013516	total: 16m 13s	remaining: 1m 46s
9456:	learn: 0.0015910	total: 16m 13s	remaining: 55.9s
9734:	learn: 0.0013287	total: 16m 13s	remaining: 26.5s
9738:	learn: 0.0014770	total: 16m 13s	remaining: 26.1s
9931:	learn: 0.0013900	total: 16m 13s	remaining: 6.67s
9014:	learn: 0.0013516	total: 16m 14s	remaining: 1m 46s
9735:	learn: 0.0013287	total: 16m 13s	remaining: 26.4s
9457:	learn: 0.0015910	total: 16m 14s	remaining: 55.8s
9739:	learn: 0.0014770	total: 16m 13s	remaining: 26s
9932:	learn: 0.0013900	total: 16m 13s	remaining: 6.57s
9736:	learn: 0.0013287	total: 16m 14s	remaining: 26.3s
9015:	learn: 0.0013516	total: 16m 14s	remaining: 1m 46s
9740:	learn: 0.0014770	total: 16m 13s	remaining: 25.9s
9458:	learn: 0.0015910	total: 16m 14s	remaining: 55.7s
9933:	learn: 0.0013896	total: 16m 13s	remaining: 6.47s
9737:	learn: 0.0013287	total: 16m 14s	remaining: 26.2s
9016:	learn: 0.0013516	total: 16m 14s	remaining: 1m 46s
9741:	learn: 0.0014770	total: 16m 13s	remaining: 25.8s
9934:	learn: 0.0013896	total: 16m 13s	remaining: 6.37s
9459:	learn: 0.0015910	total: 16m 14s	remaining: 55.6s
9742:	learn: 0.0014770	total: 16m 14s	remaining: 25.7s
9935:	learn: 0.0013896	total: 16m 14s	remaining: 6.27s
9738:	learn: 0.0013287	total: 16m 14s	remaining: 26.1s
9017:	learn: 0.0013516	total: 16m 14s	remaining: 1m 46s
9460:	learn: 0.0015910	total: 16m 14s	remaining: 55.5s
9743:	learn: 0.0014770	total: 16m 14s	remaining: 25.6s
9739:	learn: 0.0013287	total: 16m 14s	remaining: 26s
9936:	learn: 0.0013896	total: 16m 14s	remaining: 6.18s
9461:	learn: 0.0015910	total: 16m 14s	remaining: 55.4s
9018:	learn: 0.0013516	total: 16m 14s	remaining: 1m 45s
9937:	learn: 0.0013896	total: 16m 14s	remaining: 6.08s
9744:	learn: 0.0014770	total: 16m 14s	remaining: 25.5s
9462:	learn: 0.0015910	total: 16m 14s	remaining: 55.3s
9740:	learn: 0.0013287	total: 16m 14s	remaining: 25.9s
9019:	learn: 0.0013516	total: 16m 14s	remaining: 1m 45s
9938:	learn: 0.0013893	total: 16m 14s	remaining: 5.98s
9745:	learn: 0.0014770	total: 16m 14s	remaining: 25.4s
9463:	learn: 0.0015910	total: 16m 14s	remaining: 55.2s
9020:	learn: 0.0013516	total: 16m 14s	remaining: 1m 45s
9741:	learn: 0.0013287	total: 16m 14s	remaining: 25.8s
9939:	learn: 0.0013893	total: 16m 14s	remaining: 5.88s
9746:	learn: 0.0014770	total: 16m 14s	remaining: 25.3s
9742:	learn: 0.0013287	total: 16m 14s	remaining: 25.7s
9464:	learn: 0.0015908	total: 16m 14s	remaining: 55.1s
9021:	learn: 0.0013516	total: 16m 14s	remaining: 1m 45s
9747:	learn: 0.0014770	total: 16m 14s	remaining: 25.2s
9940:	learn: 0.0013893	total: 16m 14s	remaining: 5.78s
9743:	learn: 0.0013287	total: 16m 14s	remaining: 25.6s
9022:	learn: 0.0013516	total: 16m 14s	remaining: 1m 45s
9465:	learn: 0.0015908	total: 16m 14s	remaining: 55s
9748:	learn: 0.0014770	total: 16m 14s	remaining: 25.1s
9941:	learn: 0.0013893	total: 16m 14s	remaining: 5.69s
9744:	learn: 0.0013287	total: 16m 14s	remaining: 25.5s
9466:	learn: 0.0015908	total: 16m 14s	remaining: 54.9s
9023:	learn: 0.0013516	total: 16m 14s	remaining: 1m 45s
9749:	learn: 0.0014770	total: 16m 14s	remaining: 25s
9942:	learn: 0.0013893	total: 16m 14s	remaining: 5.59s
9745:	learn: 0.0013287	total: 16m 15s	remaining: 25.4s
9024:	learn: 0.0013516	total: 16m 15s	remaining: 1m 45s
9750:	learn: 0.0014770	total: 16m 14s	remaining: 24.9s
9943:	learn: 0.0013893	total: 16m 14s	remaining: 5.49s
9467:	learn: 0.0015908	total: 16m 15s	remaining: 54.8s
9746:	learn: 0.0013287	total: 16m 15s	remaining: 25.3s
9944:	learn: 0.0013893	total: 16m 14s	remaining: 5.39s
9025:	learn: 0.0013516	total: 16m 15s	remaining: 1m 45s
9751:	learn: 0.0014770	total: 16m 14s	remaining: 24.8s
9468:	learn: 0.0015908	total: 16m 15s	remaining: 54.7s
9747:	learn: 0.0013287	total: 16m 15s	remaining: 25.2s
9945:	learn: 0.0013893	total: 16m 15s	remaining: 5.29s
9026:	learn: 0.0013516	total: 16m 15s	remaining: 1m 45s
9752:	learn: 0.0014770	total: 16m 15s	remaining: 24.7s
9748:	learn: 0.0013287	total: 16m 15s	remaining: 25.1s
9469:	learn: 0.0015908	total: 16m 15s	remaining: 54.6s
9946:	learn: 0.0013893	total: 16m 15s	remaining: 5.2s
9027:	learn: 0.0013516	total: 16m 15s	remaining: 1m 45s
9753:	learn: 0.0014770	total: 16m 15s	remaining: 24.6s
9947:	learn: 0.0013893	total: 16m 15s	remaining: 5.1s
9749:	learn: 0.0013287	total: 16m 15s	remaining: 25s
9470:	learn: 0.0015908	total: 16m 15s	remaining: 54.5s
9028:	learn: 0.0013516	total: 16m 15s	remaining: 1m 44s
9754:	learn: 0.0014770	total: 16m 15s	remaining: 24.5s
9948:	learn: 0.0013893	total: 16m 15s	remaining: 5s
9750:	learn: 0.0013287	total: 16m 15s	remaining: 24.9s
9471:	learn: 0.0015908	total: 16m 15s	remaining: 54.4s
9029:	learn: 0.0013516	total: 16m 15s	remaining: 1m 44s
9755:	learn: 0.0014770	total: 16m 15s	remaining: 24.4s
9751:	learn: 0.0013287	total: 16m 15s	remaining: 24.8s
9472:	learn: 0.0015908	total: 16m 15s	remaining: 54.3s
9949:	learn: 0.0013893	total: 16m 15s	remaining: 4.9s
9030:	learn: 0.0013516	total: 16m 15s	remaining: 1m 44s
9756:	learn: 0.0014770	total: 16m 15s	remaining: 24.3s
9752:	learn: 0.0013287	total: 16m 15s	remaining: 24.7s
9031:	learn: 0.0013516	total: 16m 15s	remaining: 1m 44s
9950:	learn: 0.0013893	total: 16m 15s	remaining: 4.8s
9473:	learn: 0.0015908	total: 16m 15s	remaining: 54.2s
9753:	learn: 0.0013287	total: 16m 15s	remaining: 24.6s
9032:	learn: 0.0013516	total: 16m 15s	remaining: 1m 44s
9757:	learn: 0.0014770	total: 16m 15s	remaining: 24.2s
9474:	learn: 0.0015908	total: 16m 15s	remaining: 54.1s
9951:	learn: 0.0013893	total: 16m 15s	remaining: 4.71s
9033:	learn: 0.0013516	total: 16m 15s	remaining: 1m 44s
9758:	learn: 0.0014770	total: 16m 15s	remaining: 24.1s
9754:	learn: 0.0013287	total: 16m 15s	remaining: 24.5s
9475:	learn: 0.0015908	total: 16m 15s	remaining: 54s
9034:	learn: 0.0013516	total: 16m 15s	remaining: 1m 44s
9952:	learn: 0.0013893	total: 16m 15s	remaining: 4.61s
9759:	learn: 0.0014770	total: 16m 15s	remaining: 24s
9755:	learn: 0.0013287	total: 16m 15s	remaining: 24.4s
9476:	learn: 0.0015908	total: 16m 16s	remaining: 53.9s
9035:	learn: 0.0013516	total: 16m 16s	remaining: 1m 44s
9953:	learn: 0.0013893	total: 16m 15s	remaining: 4.51s
9756:	learn: 0.0013287	total: 16m 16s	remaining: 24.3s
9760:	learn: 0.0014770	total: 16m 15s	remaining: 23.9s
9477:	learn: 0.0015908	total: 16m 16s	remaining: 53.8s
9954:	learn: 0.0013893	total: 16m 15s	remaining: 4.41s
9036:	learn: 0.0013516	total: 16m 16s	remaining: 1m 44s
9757:	learn: 0.0013287	total: 16m 16s	remaining: 24.2s
9761:	learn: 0.0014770	total: 16m 15s	remaining: 23.8s
9478:	learn: 0.0015908	total: 16m 16s	remaining: 53.7s
9955:	learn: 0.0013893	total: 16m 16s	remaining: 4.31s
9037:	learn: 0.0013516	total: 16m 16s	remaining: 1m 43s
9479:	learn: 0.0015908	total: 16m 16s	remaining: 53.6s
9758:	learn: 0.0013287	total: 16m 16s	remaining: 24.1s
9762:	learn: 0.0014770	total: 16m 16s	remaining: 23.7s
9956:	learn: 0.0013893	total: 16m 16s	remaining: 4.21s
9759:	learn: 0.0013284	total: 16m 16s	remaining: 24s
9038:	learn: 0.0013516	total: 16m 16s	remaining: 1m 43s
9480:	learn: 0.0015908	total: 16m 16s	remaining: 53.5s
9957:	learn: 0.0013893	total: 16m 16s	remaining: 4.12s
9763:	learn: 0.0014770	total: 16m 16s	remaining: 23.6s
9481:	learn: 0.0015908	total: 16m 16s	remaining: 53.3s
9760:	learn: 0.0013284	total: 16m 16s	remaining: 23.9s
9958:	learn: 0.0013893	total: 16m 16s	remaining: 4.02s
9039:	learn: 0.0013516	total: 16m 16s	remaining: 1m 43s
9764:	learn: 0.0014770	total: 16m 16s	remaining: 23.5s
9761:	learn: 0.0013284	total: 16m 16s	remaining: 23.8s
9959:	learn: 0.0013893	total: 16m 16s	remaining: 3.92s
9482:	learn: 0.0015908	total: 16m 16s	remaining: 53.2s
9040:	learn: 0.0013516	total: 16m 16s	remaining: 1m 43s
9762:	learn: 0.0013284	total: 16m 16s	remaining: 23.7s
9765:	learn: 0.0014770	total: 16m 16s	remaining: 23.4s
9960:	learn: 0.0013893	total: 16m 16s	remaining: 3.82s
9483:	learn: 0.0015908	total: 16m 16s	remaining: 53.1s
9041:	learn: 0.0013516	total: 16m 16s	remaining: 1m 43s
9961:	learn: 0.0013893	total: 16m 16s	remaining: 3.73s
9763:	learn: 0.0013284	total: 16m 16s	remaining: 23.6s
9766:	learn: 0.0014770	total: 16m 16s	remaining: 23.3s
9484:	learn: 0.0015908	total: 16m 16s	remaining: 53s
9042:	learn: 0.0013516	total: 16m 16s	remaining: 1m 43s
9962:	learn: 0.0013893	total: 16m 16s	remaining: 3.63s
9767:	learn: 0.0014770	total: 16m 16s	remaining: 23.2s
9764:	learn: 0.0013284	total: 16m 16s	remaining: 23.5s
9485:	learn: 0.0015908	total: 16m 16s	remaining: 52.9s
9963:	learn: 0.0013893	total: 16m 16s	remaining: 3.53s
9043:	learn: 0.0013516	total: 16m 16s	remaining: 1m 43s
9765:	learn: 0.0013284	total: 16m 16s	remaining: 23.4s
9486:	learn: 0.0015908	total: 16m 17s	remaining: 52.8s
9768:	learn: 0.0014770	total: 16m 16s	remaining: 23.1s
9964:	learn: 0.0013893	total: 16m 16s	remaining: 3.43s
9044:	learn: 0.0013516	total: 16m 17s	remaining: 1m 43s
9487:	learn: 0.0015908	total: 16m 17s	remaining: 52.7s
9766:	learn: 0.0013284	total: 16m 17s	remaining: 23.3s
9769:	learn: 0.0014770	total: 16m 16s	remaining: 23s
9045:	learn: 0.0013515	total: 16m 17s	remaining: 1m 43s
9965:	learn: 0.0013893	total: 16m 16s	remaining: 3.33s
9767:	learn: 0.0013284	total: 16m 17s	remaining: 23.2s
9770:	learn: 0.0014770	total: 16m 16s	remaining: 22.9s
9488:	learn: 0.0015908	total: 16m 17s	remaining: 52.6s
9046:	learn: 0.0013515	total: 16m 17s	remaining: 1m 42s
9966:	learn: 0.0013893	total: 16m 17s	remaining: 3.23s
9771:	learn: 0.0014770	total: 16m 17s	remaining: 22.8s
9768:	learn: 0.0013284	total: 16m 17s	remaining: 23.1s
9489:	learn: 0.0015908	total: 16m 17s	remaining: 52.5s
9047:	learn: 0.0013515	total: 16m 17s	remaining: 1m 42s
9967:	learn: 0.0013893	total: 16m 17s	remaining: 3.14s
9772:	learn: 0.0014770	total: 16m 17s	remaining: 22.7s
9490:	learn: 0.0015908	total: 16m 17s	remaining: 52.4s
9769:	learn: 0.0013284	total: 16m 17s	remaining: 23s
9048:	learn: 0.0013515	total: 16m 17s	remaining: 1m 42s
9968:	learn: 0.0013893	total: 16m 17s	remaining: 3.04s
9773:	learn: 0.0014765	total: 16m 17s	remaining: 22.6s
9491:	learn: 0.0015908	total: 16m 17s	remaining: 52.3s
9770:	learn: 0.0013284	total: 16m 17s	remaining: 22.9s
9049:	learn: 0.0013515	total: 16m 17s	remaining: 1m 42s
9969:	learn: 0.0013890	total: 16m 17s	remaining: 2.94s
9774:	learn: 0.0014760	total: 16m 17s	remaining: 22.5s
9492:	learn: 0.0015908	total: 16m 17s	remaining: 52.2s
9970:	learn: 0.0013890	total: 16m 17s	remaining: 2.84s
9771:	learn: 0.0013284	total: 16m 17s	remaining: 22.8s
9050:	learn: 0.0013515	total: 16m 17s	remaining: 1m 42s
9493:	learn: 0.0015908	total: 16m 17s	remaining: 52.1s
9775:	learn: 0.0014755	total: 16m 17s	remaining: 22.4s
9971:	learn: 0.0013890	total: 16m 17s	remaining: 2.74s
9772:	learn: 0.0013284	total: 16m 17s	remaining: 22.7s
9494:	learn: 0.0015908	total: 16m 17s	remaining: 52s
9051:	learn: 0.0013515	total: 16m 17s	remaining: 1m 42s
9776:	learn: 0.0014755	total: 16m 17s	remaining: 22.3s
9972:	learn: 0.0013886	total: 16m 17s	remaining: 2.65s
9773:	learn: 0.0013284	total: 16m 17s	remaining: 22.6s
9777:	learn: 0.0014755	total: 16m 17s	remaining: 22.2s
9052:	learn: 0.0013515	total: 16m 17s	remaining: 1m 42s
9495:	learn: 0.0015908	total: 16m 17s	remaining: 51.9s
9973:	learn: 0.0013886	total: 16m 17s	remaining: 2.55s
9774:	learn: 0.0013284	total: 16m 17s	remaining: 22.5s
9778:	learn: 0.0014755	total: 16m 17s	remaining: 22.1s
9053:	learn: 0.0013515	total: 16m 18s	remaining: 1m 42s
9775:	learn: 0.0013284	total: 16m 17s	remaining: 22.4s
9496:	learn: 0.0015908	total: 16m 18s	remaining: 51.8s
9974:	learn: 0.0013886	total: 16m 17s	remaining: 2.45s
9779:	learn: 0.0014755	total: 16m 17s	remaining: 22s

9776:	learn: 0.0013284	total: 16m 18s	remaining: 22.3s
9497:	learn: 0.0015908	total: 16m 18s	remaining: 51.7s
9054:	learn: 0.0013515	total: 16m 18s	remaining: 1m 42s
9975:	learn: 0.0013886	total: 16m 17s	remaining: 2.35s
9780:	learn: 0.0014755	total: 16m 17s	remaining: 21.9s
9777:	learn: 0.0013284	total: 16m 18s	remaining: 22.2s
9498:	learn: 0.0015908	total: 16m 18s	remaining: 51.6s
9055:	learn: 0.0013515	total: 16m 18s	remaining: 1m 41s
9976:	learn: 0.0013886	total: 16m 18s	remaining: 2.25s
9781:	learn: 0.0014755	total: 16m 18s	remaining: 21.8s
9499:	learn: 0.0015908	total: 16m 18s	remaining: 51.5s
9778:	learn: 0.0013284	total: 16m 18s	remaining: 22.1s
9782:	learn: 0.0014755	total: 16m 18s	remaining: 21.7s
9056:	learn: 0.0013515	total: 16m 18s	remaining: 1m 41s
9977:	learn: 0.0013886	total: 16m 18s	remaining: 2.16s
9779:	learn: 0.0013284	total: 16m 18s	remaining: 22s
9783:	learn: 0.0014755	total: 16m 18s	remaining: 21.6s
9500:	learn: 0.0015908	total: 16m 18s	remaining: 51.4s
9978:	learn: 0.0013886	total: 16m 18s	remaining: 2.06s
9057:	learn: 0.0013515	total: 16m 18s	remaining: 1m 41s
9780:	learn: 0.0013284	total: 16m 18s	remaining: 21.9s
9784:	learn: 0.0014755	total: 16m 18s	remaining: 21.5s
9979:	learn: 0.0013886	total: 16m 18s	remaining: 1.96s
9501:	learn: 0.0015908	total: 16m 18s	remaining: 51.3s
9058:	learn: 0.0013515	total: 16m 18s	remaining: 1m 41s
9781:	learn: 0.0013281	total: 16m 18s	remaining: 21.8s
9980:	learn: 0.0013886	total: 16m 18s	remaining: 1.86s
9785:	learn: 0.0014755	total: 16m 18s	remaining: 21.4s
9502:	learn: 0.0015908	total: 16m 18s	remaining: 51.2s
9059:	learn: 0.0013515	total: 16m 18s	remaining: 1m 41s
9782:	learn: 0.0013281	total: 16m 18s	remaining: 21.7s
9981:	learn: 0.0013886	total: 16m 18s	remaining: 1.76s
9786:	learn: 0.0014755	total: 16m 18s	remaining: 21.3s
9503:	learn: 0.0015908	total: 16m 18s	remaining: 51.1s
9783:	learn: 0.0013281	total: 16m 18s	remaining: 21.6s
9060:	learn: 0.0013515	total: 16m 18s	remaining: 1m 41s
9982:	learn: 0.0013886	total: 16m 18s	remaining: 1.67s
9787:	learn: 0.0014755	total: 16m 18s	remaining: 21.2s
9504:	learn: 0.0015908	total: 16m 18s	remaining: 51s
9061:	learn: 0.0013515	total: 16m 18s	remaining: 1m 41s
9784:	learn: 0.0013281	total: 16m 18s	remaining: 21.5s
9788:	learn: 0.0014755	total: 16m 18s	remaining: 21.1s
9983:	learn: 0.0013886	total: 16m 18s	remaining: 1.57s
9062:	learn: 0.0013515	total: 16m 18s	remaining: 1m 41s
9505:	learn: 0.0015908	total: 16m 18s	remaining: 50.9s
9785:	learn: 0.0013281	total: 16m 18s	remaining: 21.4s
9789:	learn: 0.0014755	total: 16m 18s	remaining: 21s
9984:	learn: 0.0013886	total: 16m 18s	remaining: 1.47s
9063:	learn: 0.0013515	total: 16m 19s	remaining: 1m 41s
9506:	learn: 0.0015908	total: 16m 19s	remaining: 50.8s
9786:	learn: 0.0013281	total: 16m 19s	remaining: 21.3s
9790:	learn: 0.0014755	total: 16m 18s	remaining: 20.9s
9985:	learn: 0.0013886	total: 16m 18s	remaining: 1.37s
9507:	learn: 0.0015908	total: 16m 19s	remaining: 50.7s
9986:	learn: 0.0013886	total: 16m 18s	remaining: 1.27s
9787:	learn: 0.0013281	total: 16m 19s	remaining: 21.2s
9064:	learn: 0.0013515	total: 16m 19s	remaining: 1m 40s
9791:	learn: 0.0014755	total: 16m 18s	remaining: 20.8s
9788:	learn: 0.0013281	total: 16m 19s	remaining: 21.1s
9508:	learn: 0.0015908	total: 16m 19s	remaining: 50.6s
9065:	learn: 0.0013515	total: 16m 19s	remaining: 1m 40s
9987:	learn: 0.0013886	total: 16m 19s	remaining: 1.18s
9792:	learn: 0.0014755	total: 16m 19s	remaining: 20.7s
9789:	learn: 0.0013281	total: 16m 19s	remaining: 21s
9509:	learn: 0.0015905	total: 16m 19s	remaining: 50.5s
9066:	learn: 0.0013515	total: 16m 19s	remaining: 1m 40s
9793:	learn: 0.0014755	total: 16m 19s	remaining: 20.6s
9988:	learn: 0.0013886	total: 16m 19s	remaining: 1.08s
9790:	learn: 0.0013281	total: 16m 19s	remaining: 20.9s
9989:	learn: 0.0013886	total: 16m 19s	remaining: 980ms
9794:	learn: 0.0014755	total: 16m 19s	remaining: 20.5s
9067:	learn: 0.0013515	total: 16m 19s	remaining: 1m 40s
9510:	learn: 0.0015905	total: 16m 19s	remaining: 50.4s
9795:	learn: 0.0014755	total: 16m 19s	remaining: 20.4s
9791:	learn: 0.0013277	total: 16m 19s	remaining: 20.8s
9990:	learn: 0.0013886	total: 16m 19s	remaining: 882ms
9511:	learn: 0.0015905	total: 16m 19s	remaining: 50.3s
9068:	learn: 0.0013515	total: 16m 19s	remaining: 1m 40s
9796:	learn: 0.0014755	total: 16m 19s	remaining: 20.3s
9991:	learn: 0.0013886	total: 16m 19s	remaining: 784ms
9792:	learn: 0.0013277	total: 16m 19s	remaining: 20.7s
9797:	learn: 0.0014755	total: 16m 19s	remaining: 20.2s
9512:	learn: 0.0015905	total: 16m 19s	remaining: 50.2s
9069:	learn: 0.0013515	total: 16m 19s	remaining: 1m 40s
9992:	learn: 0.0013886	total: 16m 19s	remaining: 686ms
9793:	learn: 0.0013277	total: 16m 19s	remaining: 20.6s
9513:	learn: 0.0015905	total: 16m 19s	remaining: 50.1s
9798:	learn: 0.0014755	total: 16m 19s	remaining: 20.1s
9070:	learn: 0.0013515	total: 16m 19s	remaining: 1m 40s
9993:	learn: 0.0013886	total: 16m 19s	remaining: 588ms
9794:	learn: 0.0013277	total: 16m 19s	remaining: 20.5s
9514:	learn: 0.0015905	total: 16m 19s	remaining: 49.9s
9994:	learn: 0.0013886	total: 16m 19s	remaining: 490ms
9799:	learn: 0.0014755	total: 16m 19s	remaining: 20s
9795:	learn: 0.0013277	total: 16m 19s	remaining: 20.4s
9071:	learn: 0.0013515	total: 16m 19s	remaining: 1m 40s
9515:	learn: 0.0015905	total: 16m 20s	remaining: 49.8s
9995:	learn: 0.0013886	total: 16m 19s	remaining: 392ms
9800:	learn: 0.0014755	total: 16m 19s	remaining: 19.9s
9796:	learn: 0.0013277	total: 16m 19s	remaining: 20.3s
9072:	learn: 0.0013515	total: 16m 20s	remaining: 1m 40s
9996:	learn: 0.0013886	total: 16m 19s	remaining: 294ms
9516:	learn: 0.0015905	total: 16m 20s	remaining: 49.7s
9801:	learn: 0.0014755	total: 16m 19s	remaining: 19.8s
9797:	learn: 0.0013277	total: 16m 20s	remaining: 20.2s
9073:	learn: 0.0013515	total: 16m 20s	remaining: 1m 40s
9997:	learn: 0.0013886	total: 16m 19s	remaining: 196ms
9517:	learn: 0.0015905	total: 16m 20s	remaining: 49.6s
9802:	learn: 0.0014755	total: 16m 19s	remaining: 19.7s
9798:	learn: 0.0013277	total: 16m 20s	remaining: 20.1s
9998:	learn: 0.0013886	total: 16m 20s	remaining: 98ms
9803:	learn: 0.0014755	total: 16m 20s	remaining: 19.6s
9074:	learn: 0.0013515	total: 16m 20s	remaining: 1m 39s
9518:	learn: 0.0015905	total: 16m 20s	remaining: 49.5s
9999:	learn: 0.0013886	total: 16m 20s	remaining: 0us
9799:	learn: 0.0013277	total: 16m 20s	remaining: 20s
9804:	learn: 0.0014755	total: 16m 20s	remaining: 19.5s
9519:	learn: 0.0015905	total: 16m 20s	remaining: 49.4s
9075:	learn: 0.0013515	total: 16m 20s	remaining: 1m 39s
9805:	learn: 0.0014755	total: 16m 20s	remaining: 19.4s
9800:	learn: 0.0013277	total: 16m 20s	remaining: 19.9s
9076:	learn: 0.0013515	total: 16m 20s	remaining: 1m 39s
9520:	learn: 0.0015905	total: 16m 20s	remaining: 49.3s
9806:	learn: 0.0014755	total: 16m 20s	remaining: 19.3s
9077:	learn: 0.0013515	total: 16m 20s	remaining: 1m 39s
9801:	learn: 0.0013277	total: 16m 20s	remaining: 19.8s
9807:	learn: 0.0014755	total: 16m 20s	remaining: 19.2s
9521:	learn: 0.0015904	total: 16m 20s	remaining: 49.2s
9078:	learn: 0.0013515	total: 16m 20s	remaining: 1m 39s
9802:	learn: 0.0013277	total: 16m 20s	remaining: 19.7s
9808:	learn: 0.0014755	total: 16m 20s	remaining: 19.1s
9803:	learn: 0.0013277	total: 16m 20s	remaining: 19.6s
9522:	learn: 0.0015904	total: 16m 20s	remaining: 49.1s
9079:	learn: 0.0013515	total: 16m 20s	remaining: 1m 39s
9809:	learn: 0.0014755	total: 16m 20s	remaining: 19s
9804:	learn: 0.0013277	total: 16m 20s	remaining: 19.5s
9523:	learn: 0.0015904	total: 16m 20s	remaining: 49s
9810:	learn: 0.0014755	total: 16m 20s	remaining: 18.9s
9805:	learn: 0.0013273	total: 16m 20s	remaining: 19.4s
9524:	learn: 0.0015904	total: 16m 20s	remaining: 48.9s
9080:	learn: 0.0013515	total: 16m 20s	remaining: 1m 39s
9811:	learn: 0.0014755	total: 16m 20s	remaining: 18.8s
9806:	learn: 0.0013270	total: 16m 20s	remaining: 19.3s
9525:	learn: 0.0015904	total: 16m 21s	remaining: 48.8s
9081:	learn: 0.0013515	total: 16m 21s	remaining: 1m 39s
9812:	learn: 0.0014755	total: 16m 20s	remaining: 18.7s
9807:	learn: 0.0013270	total: 16m 20s	remaining: 19.2s
9526:	learn: 0.0015904	total: 16m 21s	remaining: 48.7s

[Parallel(n_jobs=-1)]: Done   3 out of   5 | elapsed: 16.7min remaining: 11.1min
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed: 17.1min finished

In [85]:
#final_pred = final_pred[:,1]
final_pred

array([[0.99807534, 0.00192466],
       [0.99809975, 0.00190025],
       [0.99804961, 0.00195039]])

In [87]:
#StackingClassifier?

In [101]:
train_metadata_processed.head()

,age_approx,clin_size_long_diam_mm,tbp_lv_A,tbp_lv_Aext,tbp_lv_B,tbp_lv_Bext,tbp_lv_C,tbp_lv_Cext,tbp_lv_H,tbp_lv_Hext,...,tbp_lv_location_simple_Head & Neck,tbp_lv_location_simple_Left Arm,tbp_lv_location_simple_Left Leg,tbp_lv_location_simple_Right Arm,tbp_lv_location_simple_Right Leg,tbp_lv_location_simple_Torso Back,tbp_lv_location_simple_Torso Front,tbp_lv_location_simple_Unknown,isic_id,target
0,0.146694,-0.511069,0.067613,0.380443,-0.257500,-0.659882,-0.192995,-0.407543,-0.288931,-0.917620,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,ISIC_0015670,0
1,0.146694,-1.624050,2.935019,2.959583,-0.369545,-0.527265,1.126869,0.906538,-2.708061,-3.006591,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ISIC_0015845,0
2,0.146694,-0.304536,0.650540,0.625867,1.835454,1.466075,1.644677,1.385391,0.835409,0.339647,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,ISIC_0015864,0
3,0.515280,-0.407803,-1.433104,-0.780446,-1.294561,-1.291919,-1.583639,-1.355725,0.318926,-0.166282,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,ISIC_0015902,0
4,-0.221891,-0.688917,1.188031,1.455843,-0.344179,-0.268249,0.250792,0.349419,-1.396095,-1.590171,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,ISIC_0024200,0

In [88]:
sub_df = pd.concat([X_test['isic_id'],pd.Series(final_pred[:,1])],axis=1)
sub_df.head()

        isic_id         0
0  ISIC_0015657  0.001925
1  ISIC_0015729  0.001900
2  ISIC_0015740  0.001950

In [139]:
from tqdm import tqdm
#train_predict = stacking_model.predict(X_train_final.drop(columns=['isic_id'],axis=1))
X_val = train_metadata_processed.drop(columns=['isic_id','target'])
y_val = train_metadata_processed['target']

y_val_pred = np.array([])
for i in tqdm(range(0,len(X_val),1000)):
    if len(X_val)-i > 1000:
        y_val_pred = np.append(y_val_pred,
                                stacking_model.predict(X_val[i:i+1000]))
    else:
        y_val_pred = np.append(y_val_pred,
                                stacking_model.predict(X_val[i:]))
    
#y_val_pred = stacking_model.predict(X_val)

100%|██████████| 402/402 [02:45<00:00,  2.43it/s]

In [147]:
sum(np.array(y_val_pred == y_val).astype(int)) / len(y_val)

fp = sum(np.array((y_val_pred==1)&(y_val==0)).astype(int)) / len(y_val)
fn = sum(np.array((y_val_pred==0)&(y_val==1)).astype(int)) / len(y_val)

fp, fn

(0.01107567714475925, 0.0)

In [91]:
#stacking_model.final_estimator?

In [37]:
#sub_df.to_csv('submission.csv', index=False)